### ISSUE TITLE
Add dynamic min zoom level

### ISSUE THREAD

**Issue by gdt** [streetcomplete/StreetComplete#10]
In dense areas, the current zoom settings seem sensible.   But in less populated areas, you can have a view with only 1 quest but it doesn't show until you zoom in.   So as long as the view would not be cluttered, they should show.   Perhaps also some indication of how many (enabled) quests are in the current view.

**Comment by westnordost** [comment]
The map rendering framework I use (Tangram-ES) is in a relatively early state of development regarding map markers. So currently, this is simply not possible.
As are many other marker-related features such as grouping markers together and showing more important quests above less important quests.

Be assured though that I am monitoring the progress of this framework and when something becomes possible with reasonable effort, I will be amongst the first to make use of that.
