### ISSUE TITLE
[Quest] surface of leisure=pitch

### ISSUE THREAD

**Issue by Etua** [streetcomplete/StreetComplete#1170]
### General
Affected tag(s) to be modified/added: [surface of leisure:pitch](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch)
Question asked: **What type of surface does this pitch have?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose (in tennis or football surface changes playing technique slightly, also one may prefer other types of surface than concrete or asphalt)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Picture selection quest.

**Element selection:** 
ways with leisure=pitch and without surface tag, nodes could be too ambiguous as few pitches that are close together may be tagged as one

**Comment by westnordost** [comment]
What values should be selectable?

**Comment by Etua** [comment]
Definitely those listed in "Special" section in https://wiki.openstreetmap.org/wiki/Key:surface + grass, sand and asphalt, concrete, earth for some lower class pitches. Are any sports that use more than that?

**Comment by Etua** [comment]
Pétanque may use some kind of gravel, but I suppose that combination is not very common.

**Comment by HolgerJeromin** [comment]
> Pétanque may use some kind of gravel, but I suppose that combination is not very common.

I would use `surface=clay` for this.

**Comment by michaelblyons** [comment]
> Pétanque may use some kind of gravel, but I suppose that combination is not very common.

Where I played pétanque, the surface was always `compacted`.
