### ISSUE TITLE
Construction quest should have option "exact date is known"

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#1341]
**Use case**
Let's say I have an construction quest (https://github.com/westnordost/StreetComplete/issues/685). Actually it is not rare in Germany (at least) to see signs or so for bigger projects explaining the project and when it ends (estimated) or so.

**Proposed Solution**
As such, maybe we can use this info and add a "Other answer" -> "End date is known", which then opens a date picker (maybe only month/year though, as that is often only given).

**Comment by westnordost** [comment]
@matkoniecz : Is this doable and feasible?

**Comment by matkoniecz** [comment]
There are tags for that - https://wiki.openstreetmap.org/wiki/Key:opening_date but I had no good idea how to fit it into interface - hiding it in "can'y say" is a bit weird.

**Comment by westnordost** [comment]
Well it would be hidden in "Other answers...". Simply answering "no" (not finished yet) is not wrong, but I guess if it is technically possible, such an answer option would be nice to have so that the app does not ask again and again while it is still under construction.
