### ISSUE TITLE
Add quest (modes of transport information (hiking/bicycle/etc) to guideposts)

### ISSUE THREAD

**Issue by sun-geo** [streetcomplete/StreetComplete#1412]
### General
The main osm-wiki-article you can find here: https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost
Affected tag(s) to be modified/added: not clean yet for me, to be discussed, in case of hiking there are different options available, maybe `hiking=yes` or `guidepost=hiking` or `guidepost:hiking=yes`
or
all three schemes together, so it will create some redundancy, but it's maybe ok ...
What do you think about the scheme type which could/should be used?
For me it doesn't matter, so far I get any of this tags uploaded :-)

Question asked: to be find out in detail, initial starting proposal could be:
**For which mode of locomotion(Fortbewegungsart) will this guidepost give some help?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Btw, for similar purpose I asked for adding these information also to the iD-Editor preset, see here:
https://github.com/openstreetmap/iD/issues/6439
Unfortunately the request was closed there without implementation so far.
Do you think we need to asked the tagging-mailing-list (regarding the scheme) before?

**Comment by westnordost** [comment]
Sounds reasonable.

**Comment by rugk** [comment]
BTW, related `information` quests: https://github.com/westnordost/StreetComplete/issues/1226 https://github.com/westnordost/StreetComplete/issues/1115

**Comment by majkaz** [comment]
IMHO, `guidepost=hiking` is definitively the wrong approach. There are many guideposts, where the guidepost is a combination of `hiking=yes`, `bicycle=yes`, `ski=yes` and even sometimes `horse=yes`

Examples: 
[hiking+bicycle](https://osm.fit.vutbr.cz/fody/files/1618.jpg) 
[hiking+horse](https://osm.fit.vutbr.cz/fody/files/22454.jpg)
[hiking+ski](https://osm.fit.vutbr.cz/fody/files/23900.jpg)
[hiking+ski+bicycle](https://osm.fit.vutbr.cz/fody/files/26132.jpg)

**Comment by westnordost** [comment]
Looking at this again, I have three issues / questions about this:
1. What to tag if this is a general guidepost, one that just shows the direction towards nearby villages and POIs, so are not obviously made for any specific mode of transportation?
2. How to treat if `hiking=yes`, does this implicitly mean that it is not a guidepost for bicyclists? Or that it is simply not defined (yet)? In any case, this increases the complexity of the quest
3. What is the use case of this information? Is this information used in any app? In general, I recognize that to record that somewhere is a guidepost is good for orientation, but that's about it in terms of use cases for mapping guideposts

**Comment by majkaz** [comment]
Here is the situation in Czechia, where the guideposts and route markings are standardised to a high level:
1. There are two different types of guideposts here. Belonging to an route (hiking/foot/bicycle/horse/mtb/wheelchair) and the second type which stands alone. These might be [diy local guideposts](https://osm.fit.vutbr.cz/fody/files/18265.jpg) or [city guideposts](https://mapy.cz/s/paromasana). The last type isn't a guidepost according the osm-wiki definition, but often will be mapped anyway by somebody. We have just started to use city=yes for the last type to separate it from the rest.
2. Guidepost with hiking=yes belongs to foot/hiking route. There might be a bicycle route going part or even whole way along, but the plain hiking=yes means just this - hiking or foot. Bicycling might be not permitted here (for example national nature reserve, biking is allowed only if explicitly permitted or on category highway=residential and up) or possible only for an experienced MTB rider (something like MTB:scale=2+ and up). MTB-riders often use these routes. The probability that you'll need to carry the bike is quite high, however.
3. Use-case: again, Czech maps do contain guideposts as important information. You can plan your route just "from guidepost to guidepost", the Czech tourist club has even an website allowing just this. You could walk it without a map in terrain, using [route markings](https://osm.fit.vutbr.cz/fody/files/28227.jpg). The Czech community uses guideposts to map and check if routes are mapped correctly or if these didn't change in the meantime.
4. Again, "our" point of view: almost anybody could answer it correctly, the markers shows who the route belongs to. More or less complete example [in Czech](https://wiki.openstreetmap.org/wiki/Cs:%C4%8Cesko/Edita%C4%8Dn%C3%AD_standardy_a_konvence#Turistick.C3.A9_zna.C4.8Den.C3.AD) . It is common knowledge here. This system was "exported" to Poland, Romania and some other countries.

This quest would be relatively easy here but might be something quite different elsewhere.

**Comment by westnordost** [comment]
Hm, I did not follow up on your reply. So now I do.

The reply to point 3 is convincing enough. Also, the idea to define route relations using only some connection-vertices has been floating around in the community for some years now - this is similar.

However, I'd still close this as will not fix mainly because the average joe will not (always) be able to tell apart with certainty if a guidepost is meant for hikers, bicyclists or are generic ones (the ones you'd denote as city / diy).
There are some other minor issues but that is the main reason to close it.

**Comment by westnordost** [comment]
But anyway, creating this quest should be pretty easy. So if your community in Czech Republic wants to do this, you can always create a slightly modified version of this app to deploy on your phon(es).

**Comment by Hufkratzer** [comment]
In Saxony (Germany) it is often quite easy to tell if a guidepost is meant for hikers, bicyclists, horse riders etc.; examples:
* https://commons.wikimedia.org/wiki/File:Wegweiser,_Stadt_Wehlen.jpg
* https://commons.wikimedia.org/wiki/File:2016_Reitweg_Kaufbach_Dresden.jpg

If it is unclear the tags don't have to be added.

waymarkedtrails.org suppots these tags: example:
* https://riding.waymarkedtrails.org/#guidepost?id=4346273994
(this guidepost is only visible on the riding map, there is even a link to the image in the detail section).
