### ISSUE TITLE
New quest: Which level is this POI on?

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#1487]
I feel like this is a valuable new quest: asking SC users to answer on which level a POI is located.

It could be asked just for PoIs inside building ways that are tagged with (building:levels + roof:levels) > 1. It would be very useful for indoor mapping in shopping malls, too.

The UI should also allow a person to mark that an amenity spans multiple levels, cause it's easy to tag.

**Comment by westnordost** [comment]
> It could be asked just for PoIs inside building ways that are tagged with (building:levels + roof:levels) > 1

That would not be enough. Think of all the mixed use buildings where in the street level floor, there are shops, and the rest is apartments or offices. Not sure right now if shopping malls etc. have a tag that indicates how many indoor levels they have.

**Comment by MegaArthur** [comment]
> Think of all the mixed use buildings where in the street level floor, there are shops, and the rest is apartments or offices

The quest could be further restricted not to include building=apartment or even to only include building=retail

**Comment by MegaArthur** [comment]
Or, even better, make a parent-child relation for quests. It could for example be a child of the building levels and building type quests and only appear after they've been solved and the value is not building=apartment

**Comment by westnordost** [comment]
But is there a tag that indicates how many indoor levels a building/mall has?

**Comment by matkoniecz** [comment]
`shop=mall and "building:levels"=*` find 13 objects in Kraków http://overpass-turbo.eu/s/KVh

While there are probably some malls where all shops are on one level and other are used by warehouses/offices/whatever it would probably useful to tag this also in such cases.

Globally there are 6k+ such malls - see http://overpass-turbo.eu/s/KVn

**Comment by westnordost** [comment]
+ train stations + airport terminals?

Though especially for the former, there are also many train stations that do not have several levels, none one could enter anyway.

**Comment by matkoniecz** [comment]
Query for shops in malls (extending it should be relatively easy to cover other amenities and other multilevel objects):

```
[bbox:{{bbox}}];
area["shop"="mall"]["building:levels"]["building:levels"!=1]->.a;
node(area.a)[shop][!level][location!=outdoor];out meta;
```

http://overpass-turbo.eu/s/KVD

Not there is question what should be asked and entered - there are countries that are 0-indexed (ground floor, first floor), there are countries with 1-indexed levels (first floor, second floor). I remember there was discussion where it turned to be quite tricky, maybe it was SC related.

**Comment by matkoniecz** [comment]
I am unsure about question, my idea is

> On which building level $NAME is located?

and it is quite broken.

It would be easiest to tag answer as "level:ref" tag, but tagging `level` tag would help editing in Vespucci and JOSM in indoor mode.

Maybe have two fields, one for name/code of building level (`level:ref`) and second for 0-indexed `level` tag?

**Comment by westnordost** [comment]
The "clueless" user shouldn't be confronted with such a thing (0-indexed level)

**Comment by westnordost** [comment]
There was a discussion half a year ago or so about exactly this thing, initiated by my quest to show the level of a POI in the question if it has one. Not sure if I remember what was the outcome of it.

**Comment by MegaArthur** [comment]
On the first time solving the quest, the user could be asked whether buildings in their countries are 0-indexed or otherwise.

In the former case, SC would add level=* tags and in the latter, it would add level:ref=* tags.

**Comment by westnordost** [comment]
Sorry, this is out of the question because the 0-indexed thing is not something that is consistent within a country. (For example, malls on a slope, with two street level floors.) The numbering is only consistent within a building complex.
Is adding level:ref *always* considered to be correct?

**Comment by MegaArthur** [comment]
I think level:ref is designed to always be correct, but let's also hear it from someone else.

By the way, a bit offtopic, but considering buildings on a slope, how should one answer the building:levels quest in SC? Is it n or n+1 levels if one is partially inside a hill?

**Comment by westnordost** [comment]
> By the way, a bit offtopic, but considering buildings on a slope, how should one answer the building:levels quest in SC? Is it n or n+1 levels if one is partially inside a hill?

The graphic shown in the quest actually shows a building on a slope.

**Comment by HolgerJeromin** [comment]
Could someone change the title and first post?
A (flag) Pol and (Point of Interest) PoI looks the same on my device. 
It took a while why it is useful to tag on what level a flag pol(e) is mounted on a building wall.

**Comment by goldfndr** [comment]
References:
* wiki: [`level`](https://wiki.openstreetmap.org/wiki/Key:level) (`level:ref` is in the [Level denominations section](https://wiki.openstreetmap.org/wiki/Key:level#Level_denominations)), [Simple Indoor Tagging](https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging), [`addr:floor`](https://wiki.openstreetmap.org/wiki/Key:addr:floor)
* Discussions: #1270, [Tagging list on Nabble](http://gis.19327.n8.nabble.com/The-actual-use-of-the-level-tag-td5931695.html) [(Tagging list traditional)](https://lists.openstreetmap.org/pipermail/tagging/2019-January/042330.html), [Anton Khorev's diary](https://www.openstreetmap.org/user/Anton%20Khorev/diary/46933)
* Outcome: https://github.com/westnordost/StreetComplete/commit/fbb8b3464f1e652cd3fb70bc5979585e24edec2a

(New quest ideas *should* use [the template](https://github.com/westnordost/StreetComplete/blob/master/.github/ISSUE_TEMPLATE/quest-suggestion.md), but mobile apps might not implement issue templates.)

**Comment by westnordost** [comment]
Good to know, so the app could just always tag the level:ref or addr:floor.

The documentation for `level:ref` better, but looking at taginfo, `addr:floor` is used twice as much as `level:ref`, despite the wiki page of `addr:floor` saying otherwise.

**Comment by westnordost** [comment]
Open question is how to exclude or otherwise deal with malls (, train stations, airport plazas etc) that only have one storey, like shopping arcades. For these, there will be no elevators denominating the level, nor floor numbering plates visible anywhere.

This can lead to the following problems:
- some users tagging the shop's level as "EG", some others as "0" in Germany (EG = ground floor)
- some users tagging the one floor there is as "0" (Europeans), some as "1" (Americans, Russians, ...), not knowing that in the place they are currently, the typical floor numbering scheme is different from what they use themselves in common language

**Comment by xuiqzy** [comment]
Maybe saying something like "starting with 0 for the ground level" the first time a quest of this sort is answered as a popup and/or every time in the question is not perfect but not that bad after all?

**Comment by westnordost** [comment]
Well, in the USA, the levels start with 1.
This is also how (usually/often) the malls are tagged there.

**Comment by xuiqzy** [comment]
We could first tag something like the elevator availability with e.g. [elevator=*](https://taginfo.openstreetmap.org/keys/elevator) and then ask this quest saying "as found in the elevator"?
Still not good for indoor maps, but for finding a specific shop.
For computing data for indoor maps, a tag stating the `level:ref` of the first and the ground level could help then.

**Comment by westnordost** [comment]
So a solution would be to download the malls and then all shops within that mall and check if all the shops do not have a level (or level ref etc) tagged or they have all the same level tagged. If that is the case, don't show this quest.

**Comment by matkoniecz** [comment]
> The documentation for level:ref better, but looking at taginfo, addr:floor is used twice as much as level:ref, despite the wiki page of addr:floor saying otherwise.

https://wiki.openstreetmap.org/wiki/Key:addr:floor and https://wiki.openstreetmap.org/wiki/Key:level:ref were now modified and expanded. Review and edits are welcomed.

**Comment by andrewharvey** [comment]
I didn't see this when I posted #2620, but it seems my ideas are already discussed and covered here.

Agreed we should ask for `level:ref` which is directly surveyable where lift/wayfinding signage exists to label floor numbers/codes.

`addr:floor` is fine but only for addressing. Around me you'd typically find `addr:floor` being used for office buildings, but `level:ref` for shopping centers (malls), airports etc.

**Comment by westnordost** [comment]
So this would now be easier to do since we moved away from Overpass download

**Comment by westnordost** [comment]
https://user-images.githubusercontent.com/4661658/141856293-cfd2b100-bdf1-457b-8383-394f04a6cea5.mp4

**Comment by westnordost** [comment]
The levels are determined by surrounding shops in 50m radius.

I am unsure whether I should add a number input to enable inputting a level that is not displayed (e.g. no shop in 50m radius is on the same level as this shop) or if this is a really rare case that should be covered by leaving a note anyway.
Also, if a shop is located on 2 or more floors, the correct input would be "0;1" or "0-2" or whatever, which this interface doesn't cover.

**Comment by westnordost** [comment]
Final version:

https://user-images.githubusercontent.com/4661658/141872479-564c7d6e-d6d2-48cb-a8d3-5a27447866f2.mp4

**Comment by tiptoptom** [comment]
What about asking this quest also for surveillance, phones etc.?

**Comment by matkoniecz** [comment]
@tiptoptom It would be likely better posted as a new issue.

Static phones seems to be dying and really rare (but maybe there are places where it is not true? if yes - where?) and for surveillance I am not sure is it viable to locate it. But if it is mapped then maybe it is worth asking.
