### ISSUE TITLE
Immediately upload solved quests when back on wifi

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#1538]
**Use case**
I'd like to get solved quests faster online.

**Proposed Solution**
I set StreetComplete to upload immediately when on wifi. If it's technically possible, I'd propose that StreetComplete detects (in the background) when there is wifi and then uploads solved quests immediately without the need of further user interaction. The current implementation (version 13.0) seems to upload only when the app has been opened by the user. This behaviour may lead to an unnecessary and avoidable delay between solving the quest and uploading it.

**Comment by westnordost** [comment]
This is correct, StreetComplete doesn't do anything while not active. I'm a bit reluctant though to add such a feature. I always hate it if other apps do stuff in the background without my consent.

**Comment by smichel17** [comment]
You could show a low-priority notification (no pop-up) when they get back on wifi. "You're back on wifi, upload completed quests now?" Dismissing it would take no action until the next time you open the app. Clicking it could either upload in the background or open the app, where it would start uploading in the foreground.

**Comment by westnordost** [comment]
Yes, good idea

**Comment by Echolon** [comment]
I wonder once you solved some quests... why you would not like to upload it?

**Comment by westnordost** [comment]
Hm, my first comment got 8 upvotes but the starting comment got no upvotes. I am still a bit reluctant about this.

There is also really no hurry in getting changes uploaded. StreetComplete has the most advanced automatic conflict resolution of any OSM editor, so edits made with StreetComplete are "good" for a long time.

**Comment by matkoniecz** [comment]
I think that it is safe to close it as a rejected...
