### ISSUE TITLE
What kind of memorial is this

### ISSUE THREAD

**Issue by afmenez** [streetcomplete/StreetComplete#1572]
### General
Affected tag(s) to be modified/added: [Memorial](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial)
Question asked: **What kind of Memorial is this?**
- memorial=war_memorial - war memorial
- memorial=plaque - Commemorative plaque
- memorial=blue_plaque - mainly in UK. See Blue plaque
- memorial=statue - statue (personage/animal) Statue
- memorial=bust - bust
- memorial=sculpture - non figurative sculpture
- memorial=stele - stele
- memorial=obelisk - obelisk - Small ones only for others see historic=monument and man_made=obelisk
- memorial=stone - block of stone used as support.
- memorial=stolperstein - Stolperstein - almost not in use.
- memorial=cross - memorial cross - Do not confuse with historic=wayside_cross and man_made=cross
- memorial=ghost_bike - a white bicycle to remember cyclists who died in traffic accidents.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by matkoniecz** [comment]
Note that war memorial may be easily sculpture, cross, stone, obelisk,  statue and all other ones.

**Comment by afmenez** [comment]
I agree, I am just following the [current documentation](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial) for the tag.

**Comment by matkoniecz** [comment]
Yes, but while OSM Wiki should document current state of tagging (sometime self-contradictory, confusing or worse) but quest should distill it into something that makes sense (see building quest).

**Comment by westnordost** [comment]
Applies to about 100000 elements.

As @matkoniecz said, there needs to be a presorting / reality check before implementing it. Taginfo and taghistory will be a good source. The main work here is to collect representive pictures.

**Comment by kmpoppe** [comment]
While thinking about how to implement this (It would be an easy images quest) I found that the `war_memorial` could get added WW1, WW2 or WW1,WW2 given which war it depicts. What would be the simplest other example quest that ask a second question (which a designable Form) and then delivers 2 answers to the main class of the quest?

**Comment by kmpoppe** [comment]
I'd love to implement this ... I have a general idea how to add a quest with photos (take parking_type as a reference) ... but how on earth do I manage to get the pictures into Android Studio? I might be missing a point in the CONTRIBUTING doc, but I didn't see anything. @matkoniecz / @westnordost could any of you throw a few screenshots at me, how to do that? Would be much appreciated.
K

**Comment by matkoniecz** [comment]
>  but how on earth do I manage to get the pictures into Android Studio?

You put them into folders https://github.com/westnordost/StreetComplete/tree/master/app/src/main/res/drawable-mdpi https://github.com/westnordost/StreetComplete/tree/master/app/src/main/res/drawable-hdpi https://github.com/westnordost/StreetComplete/tree/master/app/src/main/res/drawable-xhdpi https://github.com/westnordost/StreetComplete/tree/master/app/src/main/res/drawable-xxhdpi

Doing it manually is obnoxious, I was unaware about any automation, I failed to find way to automate it.

I ended creating https://github.com/matkoniecz/rescaling_for_android - a ruby script for doing this. 

If you want I may document it better and maybe make it properly configurable. Its dependencies is Ruby (for running script) and imagemagick (for image resizing).

Script is pretty trivial and in the ends it just runs some commands, so porting it to Bash or whatever else should be fairly easy.

**Comment by westnordost** [comment]
You can for testing only add the photo in the appropriate size to xxhdpi, later when the pictures are final, add them rescaled to the other folders. I think there was some plugin you could download that would do this automatically. Right now I do not find it.

Please note that this quest requires some research what types of memorials should reasonably be displayed as options, aka checking back the OSM tagging with the real world. The pictures themselves need to be representative without implicitly narrowing it down more than the tag does.
For example, for the surface quest we used an image of rectangular small (10x20cm) grey paving stones for `surface=paving_stones`. This led to some confusion whether paving stone plates (what you find on normal sidewalks) would also be in the same category or if other weirder shaped paving stones in other colors would also be in the same category.

So, the research which options should be displayed plus finding of fitting correctly licensed photos will be the most work and it can be done here in this issue ticket. The implementation itself are just a few lines of code then.

Also, did you abandon #2030?

**Comment by kmpoppe** [comment]
Thanks for the input.

For #2030, I'm not yet fully happy with the icon plus, just like here, I don't quite understand how and where I shall place the icon in the latter SVG, what good would that do without giving it some meta information/putting them in some XML?

**Comment by westnordost** [comment]
Oh I ditched that large svg file. Every icon now is in its own file, you should revisit the /res/ directory

**Comment by matkoniecz** [comment]
>  I think there was some plugin you could download that would do this automatically. Right now I do not find it.

Android Drawable Importer - but it is (was) abandoned and failed to work.

It has fork at https://github.com/Vincent-Loi/android-drawable-importer-intellij-plugin but it has disabled issues panel so hard to say whatever it actually works

https://stackoverflow.com/questions/19196616/is-there-a-way-to-create-xxhdpi-xhdpi-hdpi-mdpi-and-ldpi-drawables-from-a-lar

**Comment by kmpoppe** [comment]
> Oh I ditched that large svg file. Every icon now is in its own file, you should revisit the /res/ directory

That's great. Will then need to make the crossing icon nice and then revive 2030.
