### ISSUE TITLE
Place does not exist anymore answer option

### ISSUE THREAD

**Issue by SK53** [streetcomplete/StreetComplete#1673]
I've just noted an inexperienced user changing opening hours to "closed down", they successfully closed my note, but the relevant POI was not updated with disused:amenity. I don't want to raise this directly with the user, and am not familiar with the StreetComplete interface, so cannot absolutely be sure this is a bug.

The relevant changeset was [77693359](https://www.openstreetmap.org/changeset/77693359) with the add opening hours challenge. Note I've now updated amenity, name & shop tags.

**Comment by matkoniecz** [comment]
> I don't want to raise this directly with the user, and am not familiar with the StreetComplete interface, so cannot absolutely be sure this is a bug.

SC interface info:

User entered opening hours question.

User selected "other answers" and from that menu "no regular opening hours...".

User was supposed to select "other answers" and from that menu "Can't say..." that allows either to hide the answer or create a note.

Idea to add "not existing anymore" leaving prewritten notes was rejected in #1097 Directly editing to delete shop was rejected in #1097 and is too complex (`disused:amenity` is not always correct).

Maybe "not existing anymore" that leads to a hide quest/create note (basically duplicating "Can't say...") would be a good idea? I have very limited data here, but I noticed that people often struggle with that and "there is no obvious way to handle gone objects" is one of few complaints that I heard about SC.

(I assume here that user is using SC in English - see #1674)

**Comment by SK53** [comment]
Yes, they look to be local to me. Perhaps add a fixme in this case to give regular local mappers a better chance of noticing this - "Check non-standard opening hours via StreetComplete" or similar. I'd not have spotted it without the note being closed.

**Comment by westnordost** [comment]
> Maybe "not existing anymore" that leads to a hide quest/create note (basically duplicating "Can't say...") would be a good idea?

Yes, might be a solution. It could trigger a confirmation dialog, saying that he should leave a note and explain the situation and whether he would like to do this now, leading directly to the "create note instead" dialog.

**Comment by peternewman** [comment]
> Perhaps add a fixme in this case to give regular local mappers a better chance of noticing this - "Check non-standard opening hours via StreetComplete" or similar. I'd not have spotted it without the note being closed.

As @SK53 suggested, why not a fixme rather than a note, so it's attached to the object in question, given we already know the object?

**Comment by HolgerJeromin** [comment]
Are `fixme` on the object or notes more likely to be seen/fixed? I do not know.

**Comment by peternewman** [comment]
> Are `fixme` on the object or notes more likely to be seen/fixed? I do not know. Probably a note

Notes show up for everyone on the map, but iD for example shows fixme's as notifications in the editor.

Shouldn't we be trying to encourage the ecosystem to better support fixme's if that's the problem, they just seem to make more logical sense given it's entirely unambiguous which object you're referring to.

**Comment by RubenKelevra** [comment]
Agreed a Fixme on the object is better than a node, especially if the area is densely mapped.

**Comment by kmpoppe** [comment]
Just my two cents on fixme vs. note. Notes are more prominent as they've got their own layer on osm.org and thus are more likely to be fixed. Then again, some people might be looking for `fixme`s in particular or, like me, use JOSM, where a fixme is *always* shown by a "F" on the node, but notes must be downloaded for the area you're working in.
So why not make the reference in the note two-way? The note already says which object it belongs to, so we could add a `fixme=There's information on this object in note https://osm.org/note/12345` to the object once the note is published?

**Comment by MCMic** [comment]
I second this problem, I started using Street Complete a few days ago and the lack of a «This is not the right object» kind of answer is clearly missing.

I had several cases where it would ask me opening hours of a shop but it was a restaurant with another name, or it was asking the name of some kind of shop but it was another kind.

If there are technical difficulties related to this, the menu option can just lead to a note textfield, but there need to be an option in the menu stating the object/building is not the one expected or is gone.

**Comment by peternewman** [comment]
> So why not make the reference in the note two-way?

Then you've just doubled the work required to tidy it up afterwards and increased the chances of someone forgetting part of it, so the fixme remains, but the note is closed or vice versa.

As I see it, the only advantage of notes for issues with a nwr is you can have a discussion on them. Rather than double-tagging @kmpoppe the correct solution would again be in the ecosystem for e.g. iD to search for open notes within a radius of the object which feature the object's identifier/URL and flag them in a similar way to fixme's, rather than us manually adding links.

**Comment by peternewman** [comment]
> I had several cases where it would ask me opening hours of a shop but it was a restaurant with another name, or it was asking the name of some kind of shop but it was another kind.

To get to the underlying issue of this, #2074 would cover resurveying that your restaurant had changed and so wouldn't be asking these questions.

**Comment by westnordost** [comment]
Ah, this has been implemented for v28. Let's close this.
