### ISSUE TITLE
Quest marker visible and flickering after solving a quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#1747]
Sometimes the quest marker is still visible and flickering during the automatic zoom-out after solving a quest (and maybe even after that for a short time). When I tap the marker I am asked to answer the same quest again.
In some cases it happened that the marker changed to a different quest (and switched to several different quest types while flickering), e.g. from opening hours to path surface before it disappeared. I never managed to tap the marker in such cases, so I can't say whether I would be asked to tell path surface of some resaurant.
It seems to happen more often when phone "feels slow" (maybe due to some backgroud work being done, probably unrelated to StreetComplete). Then the wrong marker stays longer, so the issue may not be noticable on more recent devices due to higher performance.

S4 mini, AOKP Nougat
StreetComplete 17.3 (GitHub release)

**Comment by Helium314** [comment]
Actually I just noticed that sometimes (rarely) all visbile quest markers flicker when panning or zooming the map...

**Comment by westnordost** [comment]
This is a known bug and already reported here: https://github.com/tangrams/tangram-es/issues/2133

**Comment by riQQ** [comment]
Duplicate of #1713
