### ISSUE TITLE
Quest focus-ring appears shifted.

### ISSUE THREAD

**Issue by Sequynth** [streetcomplete/StreetComplete#1810]
**How to Reproduce**
It happens for every quest type. I tried complete reinstall, still appears shifted

**Versions affected**
v19 (fDroid)
Android 6.0
LG G4 H815

**Comment by smichel17** [comment]
It's fixed, just not released yet.

**Comment by Sequynth** [comment]
I got the newest version from fDroid today, but the shift is still present, albeit smaller than before
![Capture+_2020-05-10-14-42-32](https://user-images.githubusercontent.com/29228990/81500774-9fcdad00-92d4-11ea-8919-e6931173bb9c.png)

**Comment by westnordost** [comment]
If you rotate the map, does the selection ring "wander" or does it stay at the same position relatively to the pin?

**Comment by smichel17** [comment]
Always the same relative position (slightly below, slightly left).

**Comment by westnordost** [comment]
What's your device? Specifically, what is the DPI of your device?

**Comment by smichel17** [comment]
Device is a Samsung Galaxy S6, specifically the SM-G920A.

xxxhdpi, if that's what you were looking for

**Comment by westnordost** [comment]
Ok, then it is likely a problem with tangram-es which apparently treats pixel offsets for elements in layers differently than for markers.

I can reproduce it on a xxxhdpi emulator. On a hdpi device, the circle offsets slightly to the right.

Though, the backlog of bugs I reported in tangram-es is already so full, I kind of don't want to add even more there as long as the others are not fixed. Partly because I will have to research the exact problem myself as well and create a minimal example. Perhaps someone else would like to do that and report the exact problem? Setup would be a map data layer consisting of a single dot at a certain position and a map marker at the same position, then, add a certain same offset for both in the style.

**Comment by Sequynth** [comment]
My density is: 1440 x 2560 pixels, 16:9 ratio (~538 ppi density). I cannot convert that  to '*hdpi' units like smichel17.

Same behaviour as he describes, offset is constant under rotation.

Does the tangram issue also explain, why the pin is is not exactly on the steps? Its position also changes under rotation (probably rotating around the point it should be contantly point to)

**Comment by westnordost** [comment]
Maybe

**Comment by RubenKelevra** [comment]
I'm not really a fan of pixel peaking on rendering libraries, but I can confirm a very slightly wrong position of the pins.

It's around 10% of the pin size too far down, and stay too far down on the rotation.

Android 9
18:9  6" display with 1080 x 2160px (401ppi)


![Screenshot_20200516-190445~2](https://user-images.githubusercontent.com/614929/82125754-71eed980-97a8-11ea-9074-1b40082d8b93.jpg)

**Comment by RubenKelevra** [comment]
I'm not really a fan of pixel peaking on rendering libraries, but I can confirm a very slightly wrong position of the pins.

It's around 10% of the pin size too far down, and stay too far down on the rotation.

But the ring stays where it should be in my case.

Android 9
18:9  6" display with 1080 x 2160px (401ppi)

![Screenshot_20200516-190445~2](https://user-images.githubusercontent.com/614929/82126192-50432180-97ab-11ea-845e-be2f2d7481cd.jpg)

![Screenshot_20200516-192608__01](https://user-images.githubusercontent.com/614929/82126198-59cc8980-97ab-11ea-9e37-1cc83f129bc1.jpg)

![Screenshot_20200516-192601](https://user-images.githubusercontent.com/614929/82126204-6c46c300-97ab-11ea-8801-d868185dc887.jpg)

**Comment by Helium314** [comment]
I tested this a bit and noticd that when changing "display size" in display settings, the marker moves further away from the dot when "display size" decreases.
![size](https://user-images.githubusercontent.com/43007630/86927979-43500800-c134-11ea-826e-6d8294f90a3e.png)
display size (smallest width): large (320) - normal (360) - small (400) - smaller (??) - smallest (514)
The "smallest width" is something I found in developer settings and is changed by "display size". I don't know what it really means, but it looks like some (non-physical) dpi setting and thus might be relevant.

In the screenshots the (pixel) distance between the center of the dot and the center of the blue circle is constant.
For the marker it is hard to determine a center, but at least the horizontal distance between the (vertical) center line of the marker and the center of the dot is constant.

So to me this looks like the centers of dot, marker and circle have the same distance at all display size settings, while actually they should scale.

**Comment by westnordost** [comment]
Thank you for the input! What is the "display width" setting?

**Comment by Helium314** [comment]
Display size (I assume you mean this) is found in display and accessibility settings (at least in all versions of Lineage OS I used), and basically changes the size of text and icons. Why it has such a confusing name I don't know.

**Comment by westnordost** [comment]
Ok I'd say it simulates a different DPI.

**Comment by Helium314** [comment]
Actually, where are quest marker (bottom/tip) and dot supposed to be located?
The dot always seems to be higher than the quest location (especially visible at low zoom levels)
The marker is too high for me and seems to be too low for others, see https://github.com/westnordost/StreetComplete/issues/1810#issuecomment-629680223

**Comment by westnordost** [comment]
So is the pin the one thing that is shifted and not the selection ring?

Am 9. Juli 2020 09:27:02 MESZ schrieb Helium314 <notifications@github.com>:
>Actually, where are quest marker (bottom/tip) and dot supposed to be
>located?
>The dot always seems to be higher than the quest location (especially
>visible at low zoom levels)
>The marker is too high for me and seems to be too low for others, see
>https://github.com/westnordost/StreetComplete/issues/1810#issuecomment-629680223

**Comment by Helium314** [comment]
I think it's both.
The sizes of pin, circle and dot scale with "display size"
But the pixel-distance between dot and circle center does not scale with "display size", likely the same applies to distance of dot and pin center (not 100% sure, because location of pin center is not that obvious).
The distances need to scale in order to get correct alignment.

When reading https://developer.android.com/training/multiscreen/screendensities#TaskUseDP it might be that the distances are defined in px, but the sizes are in dp.
(and with this link, the "smallest width" setting also makes sense to me, likely this is screen width in dp)

**Comment by westnordost** [comment]
That's good information. I think we collected enough info now to make a reasonable bug report. I think the source may be that actually the offsets given in the style are not adjusted at all for different DPIs.

**Comment by westnordost** [comment]
was fixed already in v30
