### ISSUE TITLE
New quest: Ask if a fuel station offers self service

### ISSUE THREAD

**Issue by naposm** [streetcomplete/StreetComplete#1827]
### General
Affected tag(s) to be modified/added: [self_service](https://wiki.openstreetmap.org/wiki/Key:self_service)
Question asked: **Does this fuel station offer self service?** (yes / no / only)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

Like most of the quests there's a question and three option: yes, no or only when the fuel station only offers self service.

**Element selection:**
 ```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“amenity=fuel and self_service!=*”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “amenity=fuel and self_service!=*”
  node["amenity"="fuel"]["self_service"!~".*"]({{bbox}});
  way["amenity"="fuel"]["self_service"!~".*"]({{bbox}});
  relation["amenity"="fuel"]["self_service"!~".*"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Metadata needed:** It would be useful in Italy since not every fuel station has self service and a lor of them aren't tagged as self service anyway.

**Proposed GUI:**   (may make an image later)

|     | **Does this fuel station offer self service?** |                          |
|-----|------------------------------------------------|--------------------------|
| yes | no                                             | only offers self service |
|     |                                                |                          |
|     |                                                |                          |

**Comment by westnordost** [comment]
In Germany at least, I haven't seen one fuel station that is not self service. So, it must be researched first in which countries it would be reasonable to ask.

**Comment by RubenKelevra** [comment]
Yeah, for Germany and most of Europe this would probably be just spam - since all of them are only self-service.

In Greece (some years ago) I encountered some non-self-service fuel stations. But I'm not sure how this looks today.

**Comment by matkoniecz** [comment]
And in USA it depends on state, AFAIK some make self-service illegal.

**Comment by smichel17** [comment]
I think that's down to just New Jersey, now.

**Comment by Atrate** [comment]
Poland has quite a few non-self-service gas stations to be honest

**Comment by westnordost** [comment]
Ok well, we need a list of countries where this concept exists. We now have PL, US-NJ. Anyone willing to do the research? Maybe @naposm ?

**Comment by smichel17** [comment]
US-NJ should not offer the quest because there are *no* self-service gas stations, by law.

**Comment by naposm** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Filling_station), I can say Japan (they call them serufu). In Italy we also need some self service tagging. Then, according to [this article from CarRentals.com](https://www.carrentals.com/blog/how-to-pump-gas-by-country/) it could be useful in these countries: developing countries, China, New Zealand, France, Greece, Hungary, Iceland, Portugal, Argentina, Canada, Chile

For now illegal self service is in Brazil, US-NJ, US-OR (tem. lifted), South Africa,  the town of Weymouth, Massachusetts, and the town of Huntington, New York.

**Comment by callis** [comment]
In Albania most fuel stations offer fuel service

**Comment by westnordost** [comment]
Before I mark this as "new quest for certain countries", @naposm can you explain what practical use this information has?

**Comment by naposm** [comment]
@westnordost I thought it might be useful to add this information because no one tags it and it was useful on Ca reste ouvert until some weeks ago, when it only showed fuel stations with self service. Now it was changed to all, but in the future it might be useful to have this kind of information because it might be a good filter on navigators for people traveling abroad.

**Comment by westnordost** [comment]
Ah, so the information can be used as similarly to opening hours - if it is not self service, it may have shorter opening hours (if the opening hours field is not specified).
Still, quite an unimportant info, would probably be quite low in the list.

**Comment by peternewman** [comment]
> Then, according to [this article from CarRentals.com](https://www.carrentals.com/blog/how-to-pump-gas-by-country/) it could be useful in these countries: developing countries, China, New Zealand, France, Greece, Hungary, Iceland, Portugal, Argentina, Canada, Chile

I've driven through quite a lot of France over the years and never not done self-service from my memory. Talking to a Kiwi there may occasionally be assistants in NZ but it's optional and rare. I don't particularly remember them in Iceland, but that was a long time ago so things may have changed anyway.

This also might not be a good one to collect currently given some places may possibly be doing things differently during the pandemic.

**Comment by kjonosm** [comment]
Does https://wiki.openstreetmap.org/wiki/Key:self_service include https://wiki.openstreetmap.org/wiki/Key:self_checkout or https://wiki.openstreetmap.org/wiki/Key:automated or both?

**Comment by RubenKelevra** [comment]
> Before I mark this as "new quest for certain countries", @naposm can you explain what practical use this information has?

Practical use might be for disabled people, to find a fuel station where they don't have to squeeze themselves between the car and the fuel pump and walk into the shop, but instead, have someone to help them or do the fuel service for them.

**Comment by Mannshoch** [comment]
https://www.handicap-search.ch/tankstellen/

**Comment by naposm** [comment]
Hello everyone! 🤗 I tried to implement this today and somehow it works.

More precisely, I implemented two quests: one for full service and another one for self service, following the [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel#Service).

I did this because I think that the full service tag is useful for people with disabilities as @RubenKelevra suggested, while the self service tag is a tag that might be useful (see the reason why I opened this issue, Ca reste ouvert, which was a very useful project last year required the self service tag on fuel stations to choose which ones to show).

They both are very low in the list, in their respective sections.

I made some tests and will leave some screenshot, I recycled the police type icon for now, but if @westnordost agrees and thinks this is useful I can take time and make the icons and open a pull request.


**Self service quest**:
<img width="250" src="https://user-images.githubusercontent.com/63296731/116457811-65498100-a853-11eb-911f-0d116a4f7ada.png"> 

Debug:
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458346-12bc9480-a854-11eb-96a0-014a69a082d0.png">
Answer "YES":
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458780-89599200-a854-11eb-8d58-01214914d386.png">
Answer "NO":
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458836-99717180-a854-11eb-96b6-9e326e1b24e0.png">

**Full service quest**:
<img width="250" src="https://user-images.githubusercontent.com/63296731/116457893-7f835f00-a853-11eb-8d12-cba3e177078a.png">
<img width="250" src="https://user-images.githubusercontent.com/63296731/116457970-988c1000-a853-11eb-888c-b52ac6a4e205.png">

Debug:
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458542-4dbec800-a854-11eb-80d5-6b36e1d9e44e.png">
Answer "YES":
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458133-c8d3ae80-a853-11eb-8a2b-cec4ad1fce80.png">
Answer "NO":
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458231-e99c0400-a853-11eb-9eb5-3c38c6a81308.png">
Answer "It only offers full service":
<img width="250" src="https://user-images.githubusercontent.com/63296731/116458306-06383c00-a854-11eb-9331-b815a810859f.png">

**Comment by matkoniecz** [comment]
@naposm 

> westnordost added new quest and removed feedback required help wanted labels on May 18, 2020 

Idea of the quest is accepted already, so PR may be opened

One annoying and time consuming part will be researching where this quest should be asked and in which countries it is useless (I cannot check that as it appears as this quest branch is not yet pushed to a public repo - https://github.com/naposm/StreetComplete/branches/active )

Note that `full_service` tag is barely used, just 200 uses worldwide so it may be a good idea to check on tagging mailing list is it a good idea to start adding it on all fuel stations (is it good enough for SC quest?).

**Comment by westnordost** [comment]
I also don't know what "full service" is supposed to mean? That it also has a shop? That there are vacuum cleaners and tyre inflators available? 🤷

**Comment by naposm** [comment]
> One annoying and time consuming part will be researching where this quest should be asked and in which countries it is useless (I cannot check that as it appears as this quest branch is not yet pushed to a public repo - https://github.com/naposm/StreetComplete/branches/active )

I'm pushing this right now so you can see

> Note that `full_service` tag is barely used, just 200 uses worldwide so it may be a good idea to check on tagging mailing list is it a good idea to start adding it on all fuel stations (is it good enough for SC quest?).

I had this doubt, but it's in the wiki so I think it's "official", anyway if anyone can help me to sort this out I'd be very glad, I can try to send a mail tomorrow, but I don't know if I have to make a formal request or anything on the wiki.



> I also don't know what "full service" is supposed to mean? That it also has a shop? That there are vacuum cleaners and tyre inflators available? shrug

I think it means there's an operator, that's what I understood, we call it "Servito" here in Italy.

**Comment by RubenKelevra** [comment]
> I also don't know what "full service" is supposed to mean? That it also has a shop? That there are vacuum cleaners and tyre inflators available? 🤷 

Yeah I think it makes more sense to do individual tags for those amenities (somehow) which might also have different opening hours, like a car wash and vaccum cleaners might not be available during the night, while a tyre inflator is, as well as the shop and fuel.

Might not be super critical, but it would be neat if we could help motorists to find the right station and keep the details up to date. :)

**Comment by matkoniecz** [comment]
If meaning is unclear then it should not be included in SC.

Note that OSM Wiki may be edited by anyone at all, in the same way as OSM map data.

**Comment by smichel17** [comment]
"Full service" is a term I know and (prior to a few minutes ago) would have assumed is common knowledge. It means that you don't pump your own gas; you drive up and roll down your window; an employee will come over and you'll tell them what you want (e.g. full tank of regular) and pay; they pump the gas and hand back any change / your card; and you drive off.

**Comment by westnordost** [comment]
Where is the difference to self_service=no then?

**Comment by riQQ** [comment]
Probably to tag a gas station that has both options (see also [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel#Service)).

**Comment by naposm** [comment]
> Where is the difference to self_service=no then?

I think that's only a way to say that there's no self service, the full service should be mandatory in that case (or assumed)

**Comment by naposm** [comment]
@matkoniecz I just pushed my code on my fork now if you want to see

**Comment by opk12** [comment]
1.

Should `Only` be prominent, next to `Yes` and `No`?

If offered a binary choice, I translate "self-service only" to `Yes` and don't bother looking around under `Other answers`, which usually has exceptional cases for inability to answer. If I had not seen [the screenshots above in the issue](https://github.com/streetcomplete/StreetComplete/issues/1827#issuecomment-828707672) and read the wiki, I would not have imagined the choice is ternary and has an answer under the menu.


2.

Is tagging the self-service / full-service hours being implemented or planned? (`self_service:conditional` / `full_service:conditional` [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity=fuel#Service))

If it is not being implemented: does answering `Yes` today prevent the station from being targeted by a future, hypothetical hours quest? Here where I am, a station with both `self_service=yes` and `full_service=yes` always offers them on different hours, so that's the POI filter condition for a hypothetical hours quest. But if, somewhere else in the world, self-service depends only on the driver's choice, or vehicle type, or something else that cannot be programmatically filtered out, then a hypothetical hours quest would have to exclude a station that has both `yes` ([`No unanswerable quests`](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#users))

**Comment by opk12** [comment]
3. Italian law forbids self-service LPG (GPL in Italian) so what about having only the options `No` and `Leave a note`; or auto-tagging `No`; or adding `fixme=*` if `Yes` is chosen? I imagine there may be other countries with similar restrictions, where the approach would then be reused.

(Self-service CNG (metano in Italian) has historically been illegal, but it seems legalized since recently, from Google)

**Comment by mnalis** [comment]
In Croatia also LPG is always done by attendant, but all fuel pumps for standard gas/diesel cars I've ever seen are self-service by default (although you can almost always call attendant to do it for you, and sometimes they might approach themselves if they see you're confused). After filling the tank, you have to go in to the cashier to actually pay (for vast majority of them - there are few which are fully autonomous)

(It might differ for fuel for HGV / yachts, though)

**Comment by naposm** [comment]
Grazie @opk12 per le informazioni!

> what about having only the options No and Leave a note; or auto-tagging No; or adding fixme=* if Yes is chosen? I imagine there may be other countries with similar restrictions, where the approach would then be reused.

Unfortunately I'm not sure I'd be able to do it now, but maybe in the future I will.

For now I decided to just remove the full service quest since the tag is too new and not "officially" adopted.

I apologize for just noticing these comments!

**Comment by opk12** [comment]
Thank you for your great work. BTW You may want to get in touch with the Italian community's chat, if you're not already on matrix or telegram already.

**Comment by naposm** [comment]
Sure, I can join the conversation via Matrix 😁
