### ISSUE TITLE
Add a roof type to buildings with roof:level=0

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#1929]
I think at a minimum there should be the ability to tag roofs where roof level = 0 (and probably it's < 3 storeys or whatever, also possibly filtered to countries which have enough rainfall to not all be flat).

_Originally posted by @peternewman in https://github.com/westnordost/StreetComplete/issues/1889#issuecomment-650794445_

See #1889 for some of the background and previous discussion.

**Comment by westnordost** [comment]
So, we need a list of countries where it is uncommon to have non-flat roofs at all.

**Comment by matkoniecz** [comment]
In Poland flat roofs happen (especially for garages, supermarkets, industrial sites, offices), but non-flat roofs without entire building level in roof are typical - especially for houses.

**Comment by westnordost** [comment]
I don't expect any country in Europe to have almost exclusively flat roofs.

**Comment by peternewman** [comment]
So it looks like:
https://data.worldbank.org/indicator/AG.LND.PRCP.MM?name_desc=false&view=map
https://databank.worldbank.org/reports.aspx?source=2&type=metadata&series=AG.LND.PRCP.MM

Poland is one of the lower European countries at 600mm/year.

The data is CC-BY ( https://datacatalog.worldbank.org/public-licenses#cc-by ), so do you for example just want the rainfall by country (maybe averaged over the last five years) and then a threshold can be set (and potentially tweaked in future), or do you just want straight boolean data in SC?

**Comment by westnordost** [comment]
Rainfall is a very rough measure anyway because the real data we want is not the average rainfall, but whether flat roofs are most common. We just assume that has to do with rainfall.

So better round up those countries where rainfall is quite low and then have a look at satellite pictures / streetview to confirm it.

**Comment by peternewman** [comment]
> Rainfall is a very rough measure anyway because the real data we want is not the average rainfall, but whether flat roofs are most common. We just assume that has to do with rainfall.

Yeah fair enough.
 
> So better round up those countries where rainfall is quite low and then have a look at satellite pictures / streetview to confirm it.

Okay, here's a sheet for collaborative data-gathering:
https://docs.google.com/spreadsheets/d/1Oc4i2KsF-FyJ-Bxpu1dcbGK1Wrae7mHeg_CM2rpNBc8/edit?usp=sharing

**Comment by peternewman** [comment]
> I'd suggest some sort of binary search would make sense, unless you feel we need to check every country below a rough level @westnordost ?

So we've made some good collective progress @westnordost . How much more do we need to do overall to progress this from a data gathering perspective? Are you happy with a binary search at the bottom end, perhaps with a few spot checks?

I see there are a number of countries with no rainfall data we presumably either just skip these for now or will need to check them individually (which may be diminishing returns).

I can look at adding a lookup to the country codes you need from what it currently has too, which I guess will be required assuming it's going into the same style data files as the other stuff?

**Comment by westnordost** [comment]
Since rainfall is only an indication and there are certainly also cultural aspects, it would be better to actually check each/more via satellite imagery.

**Comment by bansan85** [comment]
To unlock this issue, do you think it's possible to work with white list instead of waiting someone use Google Earth in all countries in the world ?

For example, I agree that all countries in Europe have non flat root when the root is not occupied.
I traveled in lots of countries in Europe and I never saw in a country that main building have flat roof. High buildings have flat roof but 99% of buildings in a country are small buildings.

**Comment by westnordost** [comment]
To complete that linked Google doc takes maybe  up to one hour, possibly less.

On 8 December 2020 13:42:48 CET, LE GARREC Vincent <notifications@github.com> wrote:
>To unlock this issue, do you think it's possible to work with white
>list instead of waiting someone use Google Earth in all countries in
>the world ?
>
>For example, I agree that all countries in Europe have non flat root
>when the root is not occupied.
>I traveled in lots of countries in Europe and I never saw in a country
>that main building have flat roof. High buildings have flat roof but
>99% of buildings in a country are small buildings.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/1929#issuecomment-740596906

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by bansan85** [comment]
Ok. Thanks. I will complete within few days for countries a know.

**Comment by westnordost** [comment]
Previous research was done by looking at Google aerial imagery. No need for local knowledge

**Comment by bansan85** [comment]
I completed the doc. It was three very long hours but it's done :)

**Comment by westnordost** [comment]
Wow, thanks for your work! I'll get to this soon!

**Comment by westnordost** [comment]
So that's this then:

https://ent8r.github.io/blacklistr/?data=EG,LY,SA,QA,AE,BH,DZ,MR,JO,KW,OM,YE,TN,IR,SD,SY,ML,AF,MA,PK,MT,TJ,BF,NE,IQ,TD,ER

I also added to the list of countries for which not to ask those where it's "100% flat in desert, not flat not in desert".

**Comment by pbb72** [comment]
I really don't understand the reasoning for basing this question on the country.

- Most countries have major variations in culture and climate over their area. You can't base anything on the "average" for the whole country. Even a small country like for example Belgium has differences between the north, east, south and west of the country.

- Even if there was a country that was so homogeneous, you are excluding the possibility of anyone to be an exception. What if the reason for having a slanted roof was technical instead of based on culture or rainfall? 

- How reliable is a check with Google maps? How many of the millions of buildings in a country were actually checked? For even a tiny 1%, you'd already have to check 10,000 out of 1 million buildings. In the cities as well as the countryside, and divided over all districts. Was that done?

**Comment by matkoniecz** [comment]
> You can't base anything on the "average" for the whole country.

Yes, we can. While it is not very accurate plenty of things can be usefully established on that scale. Even with checks based on small samples that may be not representative.

> How many of the millions of buildings in a country were actually checked?

Tiny sample. Hopefully representative. If list can be usefully improved - let us know, more through research is welcomed. Though it is likely that it would be more useful elsewhere.

**Comment by mnalis** [comment]
@pbb72 it is not intended to be 100% proof, it is intended to reduce [spam tasks](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete). There will always be some situations where some quests might be useful, but will not be shown (and vice-versa: there will always be some situations where some useless questions will be asked). 

So the balancing is between sometimes missing some potentially useful answers, and overloading users with spam quests which will induce them to give up on using app completely (which is much more serious problem)

**Comment by smichel17** [comment]
Also it is just the default, right? So if someone lives in a country with mostly flat roofs, but their area has other types, they can enable the quest from the settings.

**Comment by mnalis** [comment]
@smichel17 I don't think so... At least judging by other quests - for example in Croatia `What is the reference number of this postbox?` is marked as `Never shown in Croatia`. I can enable/disable it, but my preference only takes effect when I am traveling aboard - it is simply never shown while I'm in Croatia. At least it looks to me that way. 

Maybe a developer setting to 'always enable all quests' could be added to override that behaviour, but I'm not quite sure it is necessarily good idea (unless it is well hidden, like android developer options)

**Comment by matkoniecz** [comment]
> Also it is just the default, right? So if someone lives in a country with mostly flat roofs, but their area has other types, they can enable the quest from the settings.

No, it is not possible to change this without compiling your own version.

> I can enable/disable it, but my preference only takes effect when I am traveling aboard - it is simply never shown while I'm in Croatia

Exactly

> Maybe a developer setting to 'always enable all quests' could be added to override that behaviour, but I'm not quite sure it is necessarily good idea (unless it is well hidden, like android developer options)

Hard to describe it as an option, but you can run your own modified SC version, where what is enabled/disabled differs.

**Comment by smichel17** [comment]
Ah. Right. There are *also* quests that are disabled by default but can be enabled, like the vegetarian quest (because it requires you to go inside). But the regional block does not work like that. Do you know if it would be much effort to change that (for regional block, add an option to distinguish between hard block and soft block)?

**Comment by michaelblyons** [comment]
@smichel17 I'm not sure that would work either, because this doesn't toggle the _quest._ It toggles a _condition_ of the quest. If your building has `roof:levels` > 0, you can still see the roof shape. (Unless SC no longer asks for `roof:levels` at all in those countries.)

**Comment by smichel17** [comment]
Ah, yes. I suppose in that case it would need to be split out into two entries in the quest selection: roof shape when roof:levels=0 and roof shape when roof:levels>0. Then the =0 quest could be disabled by default in certain countries. At this point we are bumping up against not being worth the effort to implement, though, considering that previously =0 was simply not asked in any country.
