### ISSUE TITLE
"What Street" quest should not be asked for house numbers that belong to an interpolation which already defines the street

### ISSUE THREAD

**Issue by harry-wg** [streetcomplete/StreetComplete#2112]
Currently, streetComplete unnecessarily asks for a street name in cases where the house number belongs to an interpolation that already defines the street.

Example:

- Node [3035882703 ](https://www.openstreetmap.org/node/3035882703)defines addr:housenumber=96
- It is a member of way [350655164](https://www.openstreetmap.org/node/3035882703)
- way 350655164 defines addr:street=The Sunny Road

Asking this quest in the above circumstance wastes questor's time asking for information which is already known. It is also data inefficient, because answering the quest causes the OSM database to contain multiple unnecessary duplication of information that is more efficiently stored in the interpolation. Questor's time would be better spent answering other quests and the unnecessary duplication would be eliminated.

**Proposed Solution**

Before asking this quest, StreetComplete should check if the house number belongs to an interpolation, and should eliminate it if the interpolation contains an addr:street.

**Comment by westnordost** [comment]
Can you share a link to the wiki that explains this tagging schema? I didn't know this was valid.

**Comment by matkoniecz** [comment]
around 95 000 cases of such tagging worldwide - https://taginfo.openstreetmap.org/keys/addr%3Ainterpolation#combinations

For comparison `add:street` is used over 98 000 000 times ( https://taginfo.openstreetmap.org/keys/addr%3Astreet )

**Comment by westnordost** [comment]
I didn't mean `addr:interpolation` in general, I know that the tag exists, but I meant whether to tag the street on the interpolation way instead of the address nodes is the way to go. I now looked into the wiki myself, on https://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation it is written 

> As long as we don't have a node or building outline for each house(number) along a way, it's also possible to use automatic number interpolation. For that, draw a way connecting the existing house numbers and mark it with the type of interpolation as shown in the picture above. Additional tags such as addr:street=* are still added to the objects with the addr:housenumber=* tag, the interpolation way only gets the addr:interpolation=* tag.

**Comment by matkoniecz** [comment]
> I didn't mean addr:interpolation in general, I know that the tag exists, but I meant whether to tag the street on the interpolation way instead of the address nodes is the way to go

See https://taginfo.openstreetmap.org/keys/addr%3Ainterpolation#combinations and type addr:street - it shows how often this tags are combined
![screen01](https://user-images.githubusercontent.com/899988/94255099-0243e480-ff28-11ea-846c-0629810d3546.png)

`addr:interpolation` is used more than 2 000 000 times, "around 95 000" is for just `addr:street` combined with `addr:interpolation`.

**Comment by harry-wg** [comment]
>  I didn't know this was valid

Why would it not be valid? It would not be possible to have an interpolation involving more than one value of addr_street and therefore it makes much more sense to put it in the interpolation rather than repeating it in every node of the interpolation.

Functionally, it works -- as can be demonstrated by the OSM search [96 The Sunny Road](https://www.openstreetmap.org/search?query=96%20the%20sunny%20road#map=19/51.66189/-0.03616&layers=N). OSM could not find a result if that syntax were invalid.

**Comment by harry-wg** [comment]
> whether to tag the street on the interpolation way instead of the address nodes is the way to go

It's something that **ought** to be encouraged from the point of view of data efficiency. A single interpolation can supply the street for many, possibly even hundreds of address nodes, avoiding unnecessary duplication.

**Comment by westnordost** [comment]
> Functionally, it works -- as can be demonstrated by the OSM search 96 The Sunny Road. OSM could not find a result if that syntax were invalid.

Well, and the [opening hours parser](https://github.com/simonpoole/OpeningHoursParser/) also understands `Mon to Di: 8-10 P.M.`. This doesn't make these opening hours valid though. Data consumers, if they are smart, and Nominatim is smart, support more than would be valid, to simply catch more data. It would not surprise me if Nominatim would do other smart stuff that if housenumbers have no assigned street, that it will fuzzily assume that the street closest to the housenumber is the assigned street. But that doesn't make this tagging valid, or in our case, complete.

Editors on the other hand should I think try to lean towards enforcing valid tagging. For example, when resurveying a shop with opening hours like above, the app will retag it to `Mo-Tu 8:00-22:00`. Also, if the opening hours cannot be parsed at all, the app treats it as if it has never been tagged, so any answer the user gives overwrites the invalid opening hours string.

**Comment by westnordost** [comment]
Since the wiki currently quite clearly says that the street should be set on each address node and not on the interpolation, I'd tend to have StreetComplete not understand the tagging you suggest and use around your neighbourhood. I acknowledge your argument about that it would make sense, but this is not decisive, decisive is what is considered as valid tagging.

But the was wiki also just written by people. Maybe you can point me to a discussion on the wiki, mailing list, forum or anywhere else that suggests that this sentence in the wiki should be deleted and mentioned that to tag the street on the interpolation line is fine as well?

**Comment by matkoniecz** [comment]
> Or look at the history of the wiki article and find out who wrote this there and why?

This instruction is since 2011 where current page content was created by copying it from a different wiki page - see https://wiki.openstreetmap.org/w/index.php?title=Addresses&diff=prev&oldid=713305

I have not looked at history at that different page but instruction seems to be remaining since 2011.

**Comment by harry-wg** [comment]
I've posted a question in the discussion page on that tag. Perhaps it did not work in the interpolation at that time, or perhaps the author of that article simply did not realise that it would be more data-efficient (and easier for the editor) to put it in the interpolation.

So maybe put this on hold until we get an answer to that.

**Comment by HolgerJeromin** [comment]
`addr:interpolation` is not invented for data-efficiency but to be a transitional feature till we have tagged the house numbers in between. https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Karlsruhe_Schema

> We expect this "interpolation way" to be a temporary construct.

I would really oppose against moving a street information to the interpolation line. 

Having no street on the interpolation line filling the information means:
Multiple copy the start/end node, adjust the position and house number. Delete the interpolation line. Done.

Having a street on the interpolation line filling the information means:
Multiple copy the start/end node, adjust the position and house number. Moving the street information in all (new and even the start/end) node. Delete the interpolation line. Done.

**Comment by HolgerJeromin** [comment]
But this discussion is perhaps moving in a false direction. The information is there and could be cleaned up without being outdoor (shown by a QA tool).
SC has the quest rule: "Easily answerable by everyone from the outside **but a survey is necessary**"
So perhaps these nodes should be really skipped.

**Comment by westnordost** [comment]
Yes, you do have a point. Any idea how to find such nodes via overpass?

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Relative_to_other_elements_.28around.29 should be able to find it

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Buildings_crossed_by_roads_that_are_not_tagged_as_tunnel_or_covered

http://overpass-turbo.eu/s/YuL

Main problem is that it is very, very slow.

**Comment by matkoniecz** [comment]
Original example is dead, more are easy to find with http://overpass-turbo.eu/s/YuQ - but for now I just found many, many mistagging. I fixed what I found, but I still have not found an eligible test case.

I plan to go through more matches and delete invalid taggings once I found something matching original report.

**Comment by westnordost** [comment]
I don't understand what you are doing, your second overpass-turbo link does not make sense. Also, yeah, it's unbelievably slow. There must be another solution without `around` - after all we want to find address nodes that are **part of** an `addr:interpolation` way, not address nodes that intersect with an interpolation way.

**Comment by westnordost** [comment]
Maybe something like: get all interpolation ways with `addr:street`, then get all nodes of these ways with `addr:housenumber`. With recurse-down, it should be possible?

**Comment by matkoniecz** [comment]
> Maybe something like: get all interpolation ways with addr:street, then get all nodes of these ways with addr:housenumber. With recurse-down, it should be possible?

That would not detect `addr:housenumber` without `addr:street` tagged on building that is in way of `addr:interpolation` line with `addr:street` but it can be safely skipped and not supported (I think)...

> your second overpass-turbo link does not make sense

http://overpass-turbo.eu/s/YuQ finds objects with addr:street and addr:interpolation tags (useful, as the original example is gone)

**Comment by harry-wg** [comment]
> The information is there and could be cleaned up without being outdoor (shown by a QA tool).

I agree, which is why I posted the original question (despite being unaware at the time that the tagging was incorrect).

> Any idea how to find such nodes via overpass?

Is it possible to:

- get **list1** = all nodes in bounding box with addr:housenumber but no addr_street 
- get **list2** = all ways in bounding box with the addr:interpolation tag
- for each way in list2 with an addr:street tag, delete all of its nodes from list1
- remaining nodes in list1 should be housenumbers that the street cannot be resolved from the interpolation way

**Comment by westnordost** [comment]
Still working on this, @matkoniecz ?

**Comment by westnordost** [comment]
@matkoniecz I hope you did not start working on it yet because the housenumber quest is not anymore based on overpass

**Comment by matkoniecz** [comment]
Fortunately no, I was working through the other ones (where my activity was visible)

**Comment by matkoniecz** [comment]
Looking at it again with new download - code will still be basically the same as in AddRailwayCrossingBarrier

**Comment by westnordost** [comment]
Same method,  yes

On 4 November 2020 12:58:20 CET, Mateusz Konieczny <notifications@github.com> wrote:
>Looking at it again with new download - code will still be basically
>the same as in AddRailwayCrossingBarrier
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2112#issuecomment-721690084

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jtracey** [comment]
Related issue: #2307

Doing this will cause some potential weirdness in Canada because there are plenty of interpolations that will give the wrong street (one such example is linked in that issue). But so long as that issue gets fixed, the housenumber is tagged, and you don't have an unlucky intersection where the housenumbers have overlapping ranges on the cross streets, it should be fixable remotely. I have found some intersections already with this property, but none that also happened to have a building overlapping, and intuitively it seems like the combination should be rare enough to fix on a case-by-case basis, so it's *probably* fine?

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/node/4411875737#map=19/51.64325/-0.09305 is my new test case
