### ISSUE TITLE
Bicycle Rental (docking station) capacity

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2129]
### General
Affected tag(s) to be modified/added: [capacity](https://wiki.openstreetmap.org/wiki/Key:capacity)
Question asked: **What is the capacity of this bicycle rental dock?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - London has 292 candidates alone.

### Ideas for implementation
Could just be a rehash of #1181, as in directly part of the bike parking quest (possibly just with different text). Although personally I find the bike parking ones too ambiguous to answer whereas the docks have very clear demarked positions for wheels you can count.

**Element selection:** 
`amenity=bicycle_rental and capacity!=*`

**Proposed GUI:**
Same as the other two capacity quests.

**Comment by westnordost** [comment]
How is capacity defined for such bicycle rentals? Also, how to distinguish a "human operated" bicycle rental from such a docking station?

**Comment by peternewman** [comment]
Sorry, I didn't link to the more useful page:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental

> Number of parking spaces available. 

There's also the cargo bike capacity.

A rental shop should apparently use (IMHO again not some great tagging, but that's what the wiki says):
https://wiki.openstreetmap.org/wiki/Key:service:bicycle:rental

**Comment by Lukas458** [comment]
At the moment, at least in Germany we use amenity=bicycle_rental also for many human-operated bicycle rental shops like https://www.openstreetmap.org/node/5002053020

In many tourism-citis there are some shops which might also sell bikes, but their first purpose is to rent them. For example you need to order a bike when you want to buy which would be an exception. You can't sell a bike immediately. Other human-operated shops do not sell bikes at all; and then we use amenity=bicycle_rental.

I think it's controversial that amenity=bicycle_rental would be only for not-attended stations. service:bicycle:rental can be used for mainly selling shops, but what about the shops which have their focus clearly on renting bikes? Would this be shop=rental and rental=bicycle then?

rental=bicycle and service:bicycle:rental would then be kind of duplicate.

But maybe we have other tags to distinguish? Something like network=*, which do only the docker stations have usually?

**Comment by peternewman** [comment]
> At the moment, at least in Germany we use amenity=bicycle_rental also for many human-operated bicycle rental shops like https://www.openstreetmap.org/node/5002053020

Ah damn, well that's against the wiki guidance.

> I think it's controversial that amenity=bicycle_rental would be only for not-attended stations. service:bicycle:rental can be used for mainly selling shops, but what about the shops which have their focus clearly on renting bikes? Would this be shop=rental and rental=bicycle then?

Yeah I did say I didn't think it was a great tagging scheme. Indeed shop=rental is exactly what the wiki says.

> rental=bicycle and service:bicycle:rental would then be kind of duplicate.

Agreed.

> But maybe we have other tags to distinguish? Something like network=*, which do only the docker stations have usually?

Yeah network and/or operator could be the key then. Hopefully no-one tags that on shops? They'd be brand at best I'd imagine.

**Comment by westnordost** [comment]
Looking for `network` or `operator` seems to work, though reduces the number of eligible elements somewhat. Could someone find out the numbers for which this would still be applicable?

**Comment by peternewman** [comment]
I get 305 in Southern England, so the same sort of numbers as I had before. There are a load with capacity which could be re-validated if they've added more docks to them too.

`amenity=bicycle_rental and capacity!=* and (network=* or operator=*)`

I get timeouts if I try to run over larger areas with this:
https://overpass-turbo.eu/s/YEb

**Comment by westnordost** [comment]
7724

**Comment by Lukas458** [comment]
Hmm, network=* seems to be well, but operator=* could be tagged to stations as well as to human-operated ones.

**Comment by peternewman** [comment]
> 7724

What's the magic trick @westnordost ?

> Hmm, network=* seems to be well, but operator=* could be tagged to stations as well as to human-operated ones.

Network could be too in theory (if you could hire and return to different manned shops?

What about an other answer of "It is human-operated" which tags or something:
https://wiki.openstreetmap.org/wiki/Key:service:bicycle:rental ?

I guess we're assuming you can't see the capacity of a human run place from the outside?

**Comment by westnordost** [comment]
> What's the magic trick @westnordost ?

increase timeout time: https://overpass-turbo.eu/s/YIB

> What about an other answer of "It is human-operated"

Maybe... on the other hand, users could always leave a note.

**Comment by peternewman** [comment]
> > What's the magic trick @westnordost ?
> 
> increase timeout time: https://overpass-turbo.eu/s/YIB

Ah I just assumed that was frowned upon.

> > What about an other answer of "It is human-operated"
> 
> Maybe... on the other hand, users could always leave a note.

That too, although that would only stop other people getting the quest when someone fixed it wouldn't it?

**Comment by camelCaseNick** [comment]
> Maybe... on the other hand, users could always leave a note.

What's the problem with the quest either setting capacity=* or fixing an incorrectly tagged rental place to shop=rental + service:bicycle:rental=yes?

**Comment by Lukas458** [comment]
> shop=rental + service:bicycle:rental=yes?

Hmm yes, I think if the quest would make the offer to answer celarly thatit's an human-operated rental station/shopm then this would be ok.
But whether the community would be fine with this tagging?
For renderers it's very hard to support shop=rental, but I know that's not an argument.

Also, in my eyes rental=* would be the subtag for shop=rental. But we have this problem also with car rentals etc. service:XXX:rental=yes is actually for shops with another main-tag, where the focus is on selling things.

**Comment by peternewman** [comment]
Yeah it seems to me the better solution for OSM as a whole would be to add another tag to differentiate shop from dock for example, potentially if people need to know the difference between a street based rental (i.e. a manned dock) and a bricks and mortar shop.

But that's not really the job of SC. Fixing the wiki and then getting iD to improve all the tags would be an eventual end game IMHO.

**Comment by Lukas458** [comment]
> But that's not really the job of SC. Fixing the wiki and then getting iD to improve all the tags would be an eventual end game IMHO.

Yes, true. But before that isn't done, I do not see a real chance to solve this issue, do you? It would be surely better to solve that first, as we pointed out, and _then_ adding the quest for the amenity=bicycle_rental POIs.

**Comment by westnordost** [comment]
I can add the blocked-tag to this issue, however in the wiki the tagging for bicycle rental shops is described so even though I do not like this tag, it seems to be accepted currently.

**Comment by peternewman** [comment]
> I do not see a real chance to solve this issue, do you?

I can happily go and tag the capacity of all the docking stations near me, and hide or leave a note on the ones which are run by a human.

Therefore we can gather some useful data, and I don't see why we shouldn't start doing so now. Like with the edge cases for non-existent bus stops, we can always refine the query as the tagging improves to filter out more human operated ones, e.g. if a human_operated=yes/no tag was added, we could exclude human_operated=yes from this quest, and possibly add another quest to improve the tagging of human_operated too.

**Comment by Etua** [comment]
I don't see this quest working in any city that uses hybrid system where there are rental stations defined as an area around some point but every bicycle is equipped with GPS and can be left anywhere in the city for a small fee thus they use individual wheel locks rather than docking. So you have a marked rental stations but defining their capacity is virtually impossible.

**Comment by peternewman** [comment]
Hmm yeah agreed @Etua . I'm surprised places like that have "docking stations", are they even called and tagged as such? In the UK the hire bikes that work on that principal can be dumped anywhere (and often are, with similar issues abroad from what I've seen in the news). I'd assumed by the time you've gone as far as adding the tech to lock them anywhere, you may as well let people drop them anywhere, rather than having to walk to the docking station first.

Can you link to some example nodes anyway?

> So you have a marked rental station but defining it's capacity is virtually impossible.

Well that was my issue with the standard bike parking quest all along. Most of the types of parking used in the UK ( https://wiki.openstreetmap.org/wiki/Key:bicycle_parking ) are ambiguous IMHO in terms of capacity, e.g. if you take the simple "n" stand, is it one bike, or one either side? Some of the wider stands, you could potentially get two bikes each side, so four in total.

Actually I see there are some hybrid ones in the UK:
https://beryl.cc/news/discover-beryl-bays

I think similar to my discussion above, and previous discussions on car parks etc, you could make an estimate of the bay capacity. Some of the Beryl bays have locks, so those could be counted too.

**Comment by matkoniecz** [comment]
> What's the problem with the quest either setting capacity=* or fixing an incorrectly tagged rental place to shop=rental + service:bicycle:rental=yes?

It seems 100% valid to tag place offering bicycle rental and no other services as `amenity=bicycle_rental`.

Nothing in `amenity=bicycle_rental` tag indicates that human-operated places are excluded. Many places are tagged in this way.

Note: I made wiki edits right now, no matter what original user of this tag intended it is clearly used not only for docking stations.

Notenote: Maybe this edits are wrong and `amenity=bicycle_rental` should be used solely for docking stations and other use is invalid? In such case it likely should be discussed at OSM Wiki/tagging mailing list.

-----------------------

For how this quest can be implemented...

(1) invent a new tag for specifying whether point is human operated or a docking station and promote it and once accepted SC can ask about it (not going to do this)

(2) ask for ones tagged with `network` / `operator` / `wikidata:network` / `'wikipedia:network` / `wikidata:operator` / `wikipedia:operator` where it indicates that it is certain that it is a docking station. Data can be partially pulled from NSI, see https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json .

But it would be necessary to check whether (1) NSI includes only 100% pure docking ports there (2) ask for extra property documenting whether entry is 100% pure docking.

**Comment by kjonosm** [comment]
> Notenote: Maybe this edits are wrong and amenity=bicycle_rental should be used solely for docking stations and other use is invalid? In such case it likely should be discussed at OSM Wiki/tagging mailing list.

the proposal and voting process was for docking stations only, see wiki [here](https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dbicycle_rental&oldid=58166)

**Comment by kjonosm** [comment]
> (1) invent a new tag for specifying whether point is human operated or a docking station and promote it and once accepted SC can ask about it (not going to do this)

Maybe [`self_service=yes`](https://wiki.openstreetmap.org/wiki/Key:self_service) could be of use here.

**Comment by matkoniecz** [comment]
> the proposal and voting process was for docking stations only, see wiki here

Oho. For now I added https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dbicycle_rental&diff=2193096&oldid=2192730 - not entirely sure how it should be handled

**Comment by matkoniecz** [comment]
1) based on discussion and existing mapping it is perfectly fine to use `amenity=bicycle_rental` for human operated rental locations

2) https://wiki.openstreetmap.org/wiki/Proposed_features/bicycle_rental:type was created

So for now this is blocked, but the proposal for classifying bicycle rental locations may unblock this.

**Comment by matkoniecz** [comment]
I am tempted to close it and reopen once some tagging is established to distinguish human-operated shops and automated docking stations.

**Comment by westnordost** [comment]
TBH the proposal is kind of bad. I wrote on the talk page why I find it problematic but there was no reply.

And I don't think a proposal is necessary to implement this quest. It can be implemented with existing tags.

To mark whether something is a docking station or not (or is not really a docking station but works that way), `self_service` could be used, no? Or otherwise/additionally, ask only if the bicycle rental station is part of a `network`.

**Comment by peternewman** [comment]
I think this can be unblocked now can't it? Given for better or worse the proposal has been accepted:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental#Types_of_bicycle_rental

There are already 7000 tagged explicitly, plus @westnordost proposed suggested selection. Another ~1000 could be added via NSI if just the TfL ones were set to add this tag.
