### ISSUE TITLE
New quest: defibrillator:location

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#2146]
### General
Affected tag(s) to be modified/added: [defibrillator:location](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator)
Question asked: **Where is this defib located?**

*On the outside wall of x opposite y*

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
 - You may need to filter by `indoor=no` if you want to limit this to outside surveys only, but there is still value to asking this question inside.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Proposed GUI:**
I guess the UI is just a text area with a max length, and some examples of good descriptions.

**Comment by westnordost** [comment]
Hmm, I think this would be quite problematic because of the free text input. Don't you think that adding this info through this app could negatively affect the data quality of this tag? That the data quality of this tag is good is very important - better not set at all than not accurate.

**Comment by westnordost** [comment]
@matkoniecz did we talk about this at the start of September?

**Comment by Cj-Malone** [comment]
> Don't you think that adding this info through this app could negatively affect the data quality of this tag?

I think any issues that could be caused by people adding it through StreetComplete are equally as plausible to be caused by somebody mapping with JOSM.

I guess it comes down to a QA problem, maybe StreetComplete should reject certain values, like under x chars. And we should have another QA tool monitoring OSM data to ensure this tag has quality data in it.

> That the data quality of this tag is good is very important - better not set at all than not accurate.

The inverse is also true, a defib with no context (other than cords) could be worse than not having an accurate description of it's location, especially in areas that aren't as well mapped.

**Comment by matkoniecz** [comment]
> @matkoniecz did we talk about this at the start of September?

No, it has not appeared in discussion (I looked at this tag, it seemed to not be obviously fitting SC so I have not proposed this)

**Comment by qugebert** [comment]
> maybe StreetComplete should reject certain values, like under x chars.

What do you think would be an acceptable minimum of chars for a useful description?

**Comment by Cj-Malone** [comment]
I don't have a number off the top of my head, we could look at the current values and make a better decision. It may be different per language.

Is this going to be a hard minimum, or a soft one? Like complex addr:housenumbers, SC recommends against them but the user can still input them.

**Comment by westnordost** [comment]
Not sure if this is necessary... I would also have said that a minimum word count may be better, but then we have Thai, Chinese etc. that do not even have whitespaces between words. Also, Chinese letters are syllables or even words on their own which means that these text are naturally much shorter when you just count the number of characters.

**Comment by qugebert** [comment]
Makes sense. I made an overpass-query and looked over the short descriptions, there were much asian sign descriptions with only two signs, so the minimum length should be removed.

**Comment by qugebert** [comment]
Ok, i've now seen there are currently about 80 nodes with defibrillator:location = fixme.
Should we include these into element selection?

**Comment by matkoniecz** [comment]
80 objects is not worth doing this (what user wanted to express? this should be replaced with proper `fixme`)

**Comment by westnordost** [comment]
80 seems really minuscule. Also, is it clear that the fixme refers to the location description rather than the location description?
