### ISSUE TITLE
a simple team modus for mapping parties

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2189]
**Use case**
Currently, it's complicated to use SC with multiple people, since SC shows all quests to everyone. In a mapping party you usually don't want to spread and have everyone walking a street alone, but walk in small groups. Walking the same route with multiple people will lead to many conflicts in the edits, reducing the efficiency because some data will be captured multiple times.

**Proposed Solution**
Create a simple team modus, where you enter the total number of team members, and your member number.

Every team member will only see his part of the quests, which are filtered based on the IDs from OSM database with a simple modulo operation on the ID.

This way there are no conflicts.

While having the team modus active, SC should track in which area the user is using SC. After exiting the team modus again, those areas' quest cache should be invalidated automatically to make sure that the quests solved by the other team members won't be displayed the next time the user want to map there.

**Comment by westnordost** [comment]
Hm! This is a really nice idea. I really like how simple it is conceptually!

What would you propose - how should the UI look like for that?

**Comment by matkoniecz** [comment]
Have setting "Split items among people" asking to enter how many people are in group and which one is your number? Maybe with info that each number should be unique.

Maybe show toast on start reminding that you see only small part of quests if that setting is enabled.

**Comment by matkoniecz** [comment]
Main problem is way splitting, but I think that it is survivable even if slightly less than half of split ways are not handled. There is a possibility to have a local database with exceptions for modulo rule and split ways getting added there (as some of them would be not matched by modulo rule) but it should be fine also without that.

**Comment by RubenKelevra** [comment]
> Hm! This is a really nice idea. I really like how simple it is conceptually!
> 
> What would you propose - how should the UI look like for that?

Well, I would keep it very simple.

Just move the 'Settings' in the menu to the second row and put a Team-Modus on the right side with a group with 3 stick persons.

Then ask for the number of team members and then show colors or maybe even better, some cool avatars - if you find some free ones like those on Netflix for example and write "each team member needs to use a unique avatar."

> Main problem is way splitting, but I think that it is survivable even if slightly less than half of split ways are not handled. 

Even that isn't an issue since the way is only shown to one person. If he/she cuts it, the cache on the other phones wouldn't know that. So as long as the group stays somewhat together, the cut ways shouldn't show up.

Maybe we could just delay the upload of cut ways some minutes - but that leaves the possibility that the data isn't uploaded at all because the app is closed while the timer is running.

**Comment by rugk** [comment]
Why is this issue still open if it has been implemented in https://github.com/streetcomplete/StreetComplete/pull/2557?

@FloEdelmann Note to (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged. :slightly_smiling_face:

**Comment by FloEdelmann** [comment]
@rugk Oh sorry, I forgot to update the PR description once I marked the PR as ready for review. Thanks for the reminder!
