### ISSUE TITLE
Improve camera following position

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#2191]
### Use case

I usually want the position of the map to follow my movement. However, I usually do not want the map to be centered on my position, because I am mapping exclusively things in front of me — I would prefer to have my position fixed at about here:

<img height="400" alt="3/4 of the way from the top of the screen, horizontally centered" src="https://user-images.githubusercontent.com/6563664/97014210-90b48180-1539-11eb-95d8-12c5c5fbbfb1.png">

In theory, this is what the compass mode is for. However, in practice, the direction of the compass changes far too erratically, making the map hard to read — there is some stabilization already that prevents the map from spinning around completely, but it still creates jitter. Also, your position is still in the center of the screen instead of closer to the bottom. So instead, I just keep the map unlocked and pan around as I walk down the street. (I am actually curious whether anybody finds compass mode useful.)

### Proposed Solution

I do not have a particular solution I like enough to propose it. However, I have a couple partial ideas; maybe with a few more brains we can turn them into a solution.

- Modify compass mode to add additional stabilization (eg, slower turning)
    - If needed, add a control for the user to quickly rotate the view 90°
- Some way to unlock the camera from the *exact* center, but still move the map with your position.
    - One option, borrowed from some games have this and call it a "semi-locked" camera: allow panning, but only a little bit, so that your position always stays within a certain area (eg, the black rectangle):
        <img height="400" alt="3/4 of the way from the top of the screen, horizontally centered" src="https://user-images.githubusercontent.com/6563664/97019350-be9cc480-153f-11eb-9a75-e198da61408d.png">
       Of course, right now, panning the map stops following your position, so there would need to be a way to toggle this. Maybe an additional state of the gps button, instead of making it disappear while following.
    - Another option: The gps button does not disappear when following location. Pressing it allows you to pan the view freely, but it still moves when you move (keeps the same position relative to your location). And the icon could change to either something like locked/unlocked, linked/unlinked, or arrows in/out (like this: ![image](https://user-images.githubusercontent.com/6563664/97047043-de47e300-1567-11eb-9f19-1bc6c3c99220.png))
- A mode that locks the camera in the position shown above (horizontally centered, 1/4 from bottom of screen), and changes the effect of dragging with one finger — horizontal movement would rotate, and vertical would tilt.

**Comment by RubenKelevra** [comment]
Hey, this sounds pretty great.

I've noticed that I like to turn the camera a lot, since the compass function is completely unusable at the moment. But as soon as you start turning the view, it unlocks from following the movements of the GPS.

I think it should just start to unlock from the movement of the GPS after the dot left the screen and is shown with an arrow at the edge of the screen.

Any rotation, tilting, panning shouldn't decouple it from the GPS movements, and just keep the dot at the relative position in the screen.

And magnetic heading dampening would be nice, too.

**Comment by westnordost** [comment]
I think this is not worth the effort.

I understand that it makes sense to see more of the map which is in front of you (in the direction you are walking/looking) than what's behind you, but we already have this feature. Just tilt the map. You will automatically see more of what is in front of you than what is behind you, due to the magic of perspective.

If the compass rotation is not working well, then rather the feature request would be to orient the map according to the movement direction rather than this.

**Comment by smichel17** [comment]
> If the compass rotation is not working well, then rather the feature request would be to orient the map according to the movement direction rather than this.

If this works\* then I think this would help. This seems to me like it would be a bit more work than *some* of the options I proposed (adding a little more stabilization to the compass view, for example).

\*OsmAnd's "Orient map to direction of movement" feature rotates back to north up when it can't determine which direction you're moving in, which consistently happens when stopping at red lights :confused:

**Comment by westnordost** [comment]
Hm well, one way or another, I do not plan to spend more time on tinkering about the camera following or not following stuff. I put way too much effort in this already.

**Comment by smichel17** [comment]
Okay. I *may* take a look at it myself. In the event that I do, would it be okay to remove (or significantly change) "compass mode"?

I'd be interested to know how many people find it useful, or even know it exists.

**Comment by smichel17** [comment]
Okay. I *may* take a look at it myself. In the event that I do, would it be okay to remove (or significantly change) "compass mode"?

I'd be interested to know how many people find it useful, or even know it exists.

**Comment by westnordost** [comment]
Well, it is at least ok to experiment with removing or significantly changing compass mode. I can not guarantee you that I'll merge it.

**Comment by westnordost** [comment]
Related:  #1040

**Comment by rouelibre1** [comment]
This would really improve the experience when using the app on a bicycle. I tried the compass mode and I'd love to use it more in the future but right now every little handlebar movement and road bump will make it shake. (Hope this describes it properly, I'm not completely clear on the impacts of "compass mode" and "GPS follow location" on/off on the experience for now)

**Comment by FloEdelmann** [comment]
Since #2465 / 5df2040f07db3feb23eee4c2bb78ed40885f4255 I've used compass mode with the phone mounted to my bike multiple times, and it worked quite well.

@smichel17, @RubenKelevra, @rouelibre1 Have you already tested that change recently? Does that change work well enough for you, too?

**Comment by smichel17** [comment]
I have not tested the change… I don't do very much mapping in the winter, it's too cold to use a touchscreen! (I have a pair of smartphone-compatible gloves, but they're thin and don't do much when it's below freezing out.)

**Comment by RubenKelevra** [comment]
@FloEdelmann I've tested at least the beta for v30.

I got a OnePlus 5T, which has in general pretty good sensors.

While the motion is now smooth, I still get a rotation left and right for each step, basically.

So we need a frequency filter which removes everything below say 3 Hz.

**Comment by rouelibre1** [comment]
@FloEdelmann I tried again (mounted on my bike) and it's much better now.

**Comment by smichel17** [comment]
I've gotten a chance to try this and I agree it's much better now. Not perfect, and especially I'd still be interested in a way to move the map as I move but without myself being centered on the screen… but it's good enough that I'm not going to be annoyed enough to experiment with adding that functionality for a long time. So, closing.
