### ISSUE TITLE
Add GPS trail for paths walked

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2209]
**Use case**

When mapping cities, especially where there are lots of small streets/ways interconnecting, there are often some confusion where exactly is quest located in relation to user. Rotating the map, and using compass viewfield helps, but is not perfect (especially since compass/orientation sensor is not perfect in mobile phones).

**Proposed Solution**

What would help is (preference-enabled?) GPX-track drawn on the screen, so user can see where s/he's been prior to reaching current location.
(Something similar to OsmAnd "record GPX" mode), or this mockup:
![Screenshot_20201027_171847](https://user-images.githubusercontent.com/156656/97330683-d4302800-1878-11eb-86f4-7cae8a2e1129.jpg)

Also, it would show user what streets have been traveled already and letting him/her decide where to go next. The GPX track could be removed if some amount of time had passed since it was last updated (maybe 6 hours? or 24h?), or could be left to user to clear it (for example, by disabling GPX option, and reenabling it later if s/he still wants it) 

Alternatively, instead of full GPX track, only a last (few) hundred meters could be shown as disappearing trail ([spacewar!-alike](https://en.wikipedia.org/wiki/File:Spacewar_gameplay.jpg)). While a little less useful, it would help with immediate orienting, and would avoid the issue of deciding when to remove displayed GPX track. Something like this mockup:
![Screenshot_20201027_171725_de westnordost streetcomplete2](https://user-images.githubusercontent.com/156656/97337731-f2018b00-1880-11eb-81f7-c6be8c16c439.jpg)

(I'm obviously not artist, the idea is the line is thickest and most opaque at the current location, and thins out and/or gets more transparent the father away it gets, and at far enough point it simply disappears)

**Comment by westnordost** [comment]
This would maybe a nice gimmick. I have no objections against if someone wanted to experiment with an implementation. But I myself won't work on this.

**Comment by rhhsm** [comment]
Could be a nice tool to draw ways on the map by walking them...

**Comment by Cj-Malone** [comment]
I think a more useful aspect of this feature would be to upload the traces to OSM so they can be used to re align areas.

**Comment by matkoniecz** [comment]
> I think a more useful aspect of this feature would be to upload the traces to OSM so they can be used to re align areas.

This really should not be bundled in as it easily can be a massive privacy issue. If someone wants to upload traces - great! But I think that it really should be done as a separate app.

**Comment by Cj-Malone** [comment]
> > I think a more useful aspect of this feature would be to upload the traces to OSM so they can be used to re align areas.
> 
> This really should not be bundled in as it easily can be a massive privacy issue. If someone wants to upload traces - great! But I think that it really should be done as a separate app.

You can already track a users specific route by looking at the changesets, the solved quests are uploaded in the order they were answered. Although I would agree that it needs to be obvious in the UI, opt in and other precautions taken such as trimming the beginning and end of the trace.

I don't seem to have much luck using other apps to trace my route, but I think that's down to Google changing the way background GPS works.

**Comment by matkoniecz** [comment]
> You can already track a users specific route by looking at the changesets, the solved quests are uploaded in the order they were answered. 

Unlike GPS tracks it will not allow you to locate exact start and end of path taken by user, can be easily stopped by not solving quests in some areas and will not happen automatically just by keeping the app open.

Also, there is a feature to disable autoupload of solutions, primarily to make it harder or at least delayed.

**Comment by peternewman** [comment]
> I don't seem to have much luck using other apps to trace my route, but I think that's down to Google changing the way background GPS works.

I've done it successfully with Vespucci, but did have the app open in the foreground and it took a few attempts for the trace to actually upload successfully.

**Comment by rhhsm** [comment]
> I don't seem to have much luck using other apps to trace my route, but I think that's down to Google changing the way background GPS works.

I'm using BackCountry Navigator (demo version), very reliable!

**Comment by Lee-Carre** [comment]
> I think that it really should be done as a separate app.

I have to concur.
Why reinvent the wheel?

If one wants to capture traces for upload, there are tools for that. If one wants a personal (offline) log of where one has been, there are (other) tools for that.

A user could run such other tools in tandem with StreetComplete.
In fact, trying to do both would compromise each. A trace would be contaminated with all the starting & stopping of movement (as the user pauses for each quest), and I feel should be performed separately as a straight-shot following of the way.

I'm reminded of the POSIX principle of ‘do one job, and do it well’.

For StreetComplete to remain good in its niche, it should avoid trying to become a general editor. If people want a general editor, there are plenty to be found.

**Comment by matkoniecz** [comment]
Note that in addition recent changes in Android made "record GPS track" more tricky, recent removal of StreetComplete from Google app-store was related to that.

**Comment by ChildishGiant** [comment]
For uploading traces, I think as long as it's off by default then there's no reason not to add it. Also routes could be capped at the first & last change so there's no need to ask a user when to stop or start.

**Comment by matkoniecz** [comment]
> then there's no reason not to add it

Main reasons are

- this code will not implement and maintain itself
- sending GPS tracks outside is extra complexity to explain to user
- it may cause trigger happy Google ban bot to ban StreetComplete again
- more features are making other features harder to find

It is not "absolutely no" but there are some negatives.

**Comment by ChildishGiant** [comment]
Those are all fair points, I'd like to see this feature but agree that it'd need to be delicately implemented and it's probably at the bottom of the pile when it comes to priority.

**Comment by HolgerJeromin** [comment]
A trace of a walking Streetcomplete user (sometimes even going inside) is not so good compared to a car or bicycle for most osm uses (aligning aerial images)
