### ISSUE TITLE
Making disabled quests more discoverable

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2243]
**Use case**
Users are often unaware that StreetComplete comes with some quests disabled by default. In some cases people are actually interested in quests that were disabled.

As number of quests grows (what is great!) it gets harder and more time consuming to hunt for ones that come disabled.

**Proposed Solution**
Add new "X disabled quest types" entry in settings, below "quest selection", with X being number of disable quests. Opening this would show list of quests similar to one in "Quest selection" but without ability to reorder them and only disabled ones would be listed.

BTW, maybe for "quest selection" show "reorder, enable and disable quests" subtitle?

**Comment by smichel17** [comment]
What about making the subtitle "X disabled quests" and changing the title to "Quest selection & order"? Or "Quest priority", if the first one is too long (the subtitle should make it clear that you can enable/disable).

**Comment by matkoniecz** [comment]
I also thought about problem "where this few disabled quests are in list of so many quests?"

Scrolling through entire list and hunting for some specific ones seems not an ideal solution.

**Comment by westnordost** [comment]
Why do you want this? Will the kosher quest be by default disabled? Cause I guess it makes sense to enable it for Israel and only for Israel.

**Comment by matkoniecz** [comment]
> Why do you want this?

1) Typical person will never change any settings
2) Among people who change some setting, looking through all of them, especially through long lists is unusual
3) And there is small group of people who (like me) will go through all possible settings

This makes quests disabled by default quite hidden, most SC users are likely unaware about them.

In addition, with so long quest list "you can go to quest list and enable quests hidden by default such as vegan/vegetarian quest" is a bit irritating as you need to go through extremely long list to find and switch on this interesting ones.

> kosher quest

Yes, kosher quest reminded me about the issue and how nicer it would to have instructions "go into this specific setting to enable quest interesting to you" over "and you now need to scroll through five kilometers long list".

> Will the kosher quest be by default disabled?

replied in https://github.com/westnordost/StreetComplete/pull/2244#issuecomment-723451884 to keep discussion about kosher PR in one place

**Comment by westnordost** [comment]
I think @smichel17 suggestion would work well.

**Comment by smichel17** [comment]
Not sure if you want to put in the effort, but I will also note in any case you may want to handle translations with [plurals](https://developer.android.com/guide/topics/resources/string-resource#Plurals)

**Comment by goldfndr** [comment]
Instead of "*X* disabled quests" as subtitle, how about "*X* of *Y* quests enabled"? If that might be too intimidating for new users, maybe only display it after *Z* achievements?

**Comment by FloEdelmann** [comment]
One part of @smichel17's suggestion has now been implemented in #2843.
