### ISSUE TITLE
Add answers "rack" & "wide_stands" to "bicycle parking type" quest

### ISSUE THREAD

**Issue by rouelibre1** [streetcomplete/StreetComplete#2250]
Can we add 2 answers to the "bicycle parking type" quest ?

- "rack", which is quite specific and differs from the "stands" type
- "wide_stands" which is also specific and different from the "stands" type

Both are mainstream in the areas where I'm completing quests and I'd hate to lower the quality of the OSM data.

The usage of a "rack" in the real world differs a little bit from the "stands" as it's sometimes difficult to attach both the wheel and the frame of the bicycle with this type, so there's real value in including this type. 

I can provide pictures for both "rack" and "wide_stands" types.

See #330 for history about the "rack" type.

**Comment by matkoniecz** [comment]
I would argue that introducing `=wide_stands` value was a mistake, that really should be a subtype of stands (`bicycle_parking=stands stands=wide` or similar).

Any wide stand is also a stand, "different from the "stands" type" is not really true.

**Comment by westnordost** [comment]
Well, you mention #330 yourself, the discussion already took place and to not include wide stands and rack was deliberate. @matkoniecz already made the argument against wide stands, regarding "rack", it is simply ill-defined, so it is somewhat of a wishy-washy value. You state it yourself - 

> as it's sometimes difficult to attach both the wheel and the frame of the bicycle with this type

That's not a very helpful classification of bicycle parking types then. `stands` is for locking possibilities where you can lock the frame, `wall_loops` or what it is called is for insecure locking possibilities (front wheel).

**Comment by rouelibre1** [comment]
>  @matkoniecz already made the argument against wide stands

After reading his answer, I agree that the `wide_stands` type doesn't add a lot of value compared to `stands`. It really should have been a subtype. I now believe it's best to not implement this type.

> regarding "rack", it is simply ill-defined, so it is somewhat of a wishy-washy value.
 
> That's not a very helpful classification of bicycle parking types then. 

While I do agree that `rack` definition can be a little blurry, I still believe there is value in making it available in the app. 
I think it really helps to describe the type of bicycle parking that are neither clearly wheelbenders ( `wall_loops`) nor `stands`. 

Yes, there are many forms of hybrids/racks (as we can see on pictures from around the world), allowing the user to attach more or less easily both the front wheel & the frame (depending on the type of rack, lock, and bicycle). So the situation is not always clearly black or white.

I would argue that while racks don't have the same shape / do not provide the same confort everywhere, they are usually the same across one city/area. So what doesn't seem uniform enough when you look at it globally makes a lot of sense locally, as users will know what to expect in a given city when they see `stands` or `rack`. They may prefer one or another based on the confort they provide for the bicycle they are using.

It might not provide satisfaction for the mind in terms of classification, but users locally will know how to differenciate and classify `rack` from `stands` and `wall_loops`. I don't believe introducing `rack` was a mistake (which makes it a different story than `wide_stands`) and some cities are deploying more of this type of bicycle parking (for ex. where I live, they are currently heavily installing them on the streets). 

For locals, it will be useful to map these, for example in their discussions with city services/officials. There are places where bicycle parking is heavily deployed, and it's sometimes 50/50 between racks and stands. That can be quite confusing for users on what to answer if the `rack` choice is not available and discourage them from answering (happened to me the other day, before opening this issue)

In some cities, racks might be of poor quality (better than wall loops, but still inferior to stands) and it might help to have them clearly identified in case of discussions between citizens and city officials (ie: should we keep them or replace them with stands ?). This will not  be possible if they are not distinguished from stands, but I doubt users will take the habit to tag them as wall loops if they don't ressemble them enough.

Some example of racks pictures, that I would neither describe as wall loops, nor as stands

![ZoomIMG_0562-500](https://user-images.githubusercontent.com/73238613/98472010-4f39fc80-21f0-11eb-81b5-d75aef1316b4.jpg)
![Web-images17](https://user-images.githubusercontent.com/73238613/98472013-53661a00-21f0-11eb-8b54-531f46bbd817.jpg)
![rack-3](https://user-images.githubusercontent.com/73238613/98472016-55c87400-21f0-11eb-87f4-1472c4e117d7.jpg)
![1280px-Bicycle_rack_in_Kraków,_Poland](https://user-images.githubusercontent.com/73238613/98472241-1d299a00-21f2-11eb-90c2-19bd8f6cdccc.jpg)

**Comment by westnordost** [comment]
If the pictures you posted are all racks in your opinion, then that is part of the problem with `rack`s, they are so different that it seems impossible to find a photo of an exemplary rack.

I guess what some of these have in common (except for the last and second one) is that you have a thing to put your front wheel  in and also another thing to lock your frame to. If this is the defining feature of racks and we can find an exemplary picture, maybe rack could be included after all.

**Comment by matkoniecz** [comment]
https://user-images.githubusercontent.com/73238613/98472241-1d299a00-21f2-11eb-90c2-19bd8f6cdccc.jpg - I tagged this specific bicycle parking as `bicycle_parking=wall_loops` and I would argue that it was correct tagging in the same way as a very big spiral allowing proper locking of bicycle would be `bicycle_parking=stands` ( https://www.openstreetmap.org/node/2501373208 )

**Comment by smichel17** [comment]
From my layperson's point of view, I can think of two criteria that I would consider when deciding to call something a rack or a stand. Unfortunately, I've now thought about the problem too much to trust my intuition on how I apply these criteria.

1. Does it have one loop or multiple?
    - My first thought was, "isn't this a simple question? One loop = stand; multiple = rack." So maybe this is the main criteria.
    - I would expect a rack to have a repeating pattern of loops. Not sure if this is always true.
2. Can it be used without being attached to the ground?

There are two situations that I am fairly confident are clear cut (but would be interested to see if there are exceptions I'm not thinking of):

- If it has one loop and it will not stand (heh) on its own, then it is a stand.

- If it has multiple loops and it will stand on its own, then it is a rack.

It is pictures like the one @matkoniecz posted and the last one @rouelibre1 posted that give me pause. They both hold multiple bikes, and the latter has all repeating loops, but I am not sure whether to call them stands or racks. But the first is not uniform and the second must be attached to the ground to stand.

**Comment by rouelibre1** [comment]
> I guess what some of these have in common (except for the last and second one) is that you have a thing to put your front wheel in and also another thing to lock your frame to. 

These criteria make sense to me, I would phrase it slightly differently : a thing to put your front wheel in + a way to lock the frame (doesn't have to physically be a different element). Phrased like this, I would say that the second picture fits the description.

>If this is the defining feature of racks and we can find an exemplary picture, maybe rack could be included after all.

Also, looking at [the picture](https://wiki.openstreetmap.org/wiki/File:Triton_Bike_Rack.png) that illustrates the rack type on the [wiki page](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking) I believe we got the concept right and it would be properly illustrated by such imagery, even if racks come in various shapes over the world.

One paramount difference that I can thing of between racks and stands is that it will always be nearly impossible to fit a cargo bike in a rack, while stands will do the job most of the time.

**Comment by thymaro** [comment]
The type `handlebar_holder` is quite common in Switzerland and looks like this: https://westnordost.de/p/30762.jpg. Here's the associated note in OSM: https://www.openstreetmap.org/note/2551384. The current options didn't satisfy me and I am often in a similar position, in which I feel coerced into choosing a certain type of bicycle parking, even though none of the definitions fit quite right. I think a little more diversity than the current five or six types would be better. Should I open a new issue about this, because it doesn't concern the two types in the issue name?

**Comment by westnordost** [comment]
As long as it is not prevalent, I think it is better to leave a note (with a photo).

**Comment by thymaro** [comment]
> As long as it is not prevalent, I think it is better to leave a note (with a photo).

I'll continue doing that until Piagno starts complaining about my notes. That's the person that takes care of all the notes I produce with SC.

**Comment by westnordost** [comment]
As this hasn't been going forward, I'll close this.
As said, the difficulty with including a "rack" type is is that it is either not clear what a rack would be or there are so many completely different things that probably should be tagged "racks", that it is very hard to find a representative picture of it.

Also, of the shown example racks, some have bad security (only locking front wheel possible), some are like stands. So if the implied security cannot be derived from that tag, it doesn't really add information value to differentiate between stands <=> racks. It makes sense to differentiate between stands and wheelbenders [because the latter have worse security](https://bikeswelcome.org/bikes-welcome/what-is-a-wheel-bender/).

Incidentally, in the linked article, those bicycle parkings are described as *"A ‘wheel-bender’ is a bike rack that only supports the parked bike via part of the wheel, creating a very real risk of damage."*, making it sound like this is a subtype of a rack. If the one defining factor of a bike rack is that the rack is **one** object, i.e. it's all connected, then a "rack", is not a meaningful tag, as it is both unspecific and categorizes the parking using a property that is quite irrelevant.
