### ISSUE TITLE
Organizing Github issues — labels for specific quests

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#2283]
**Use case**
- [Some] quests are discussed in multiple issues
- There is often useful information about why certain decisions were made in the older issues
    - For example, https://github.com/westnordost/StreetComplete/issues/2250#issuecomment-723573081
- It is often hard to find the prior issues, especially if you did not take part in them
    - A keyword search turns up many issues that are unrelated, only mentioning the quest type in passing
    - I usually end up finding one issue and then reading through it for other issues mentioned manually, like https://github.com/westnordost/StreetComplete/issues/2254#issuecomment-723649655

**Proposed Solution**

Create labels like `quest: building type`, and apply them to issues with interesting discussion/decisions about that quest.

In order to keep this a reasonable amount of effort:

- Add a few collaborators with the "triage" permission level, since this may not be a good use of @westnordost's time.
    - e.g. people who are already leaving comments like "see prior discussion: #X, #Y".
      @RubenKelevra, @peternewman, @cyclingcat, myself, etc
- Don't pre-emptively add labels or for search old issues to tag. Instead, we can add labels and tag issues any time we are already going searching back for that type of issue, instead of (or in addition to) mentioning the previous issues in a comment.

**Comment by westnordost** [comment]
I don't particularly see the value in your suggestion but I am happy to be proven otherwise. Help in triaging issues is always welcome. I understand that you are up for it?

**Comment by smichel17** [comment]
I am. I also see @rhhsm, @RubenKelevra, and @FloEdelmann :+1:'d this issue, maybe they are too? (:+1: this comment if so?)

**Comment by westnordost** [comment]
Ok, I've added you as a collaborator? I didn't see any option how to control the access more fine-grained

**Comment by smichel17** [comment]
On https://github.com/westnordost/StreetComplete/settings/access you should have something like this:

![image](https://user-images.githubusercontent.com/6563664/99301887-89397d00-2846-11eb-97a3-fc0f088df650.png)

**Comment by westnordost** [comment]
I don't, I have this:

![image](https://user-images.githubusercontent.com/4661658/99302346-898a4600-284f-11eb-8f19-8aea21a9d232.png)

**Comment by smichel17** [comment]
Hmm. Maybe it is different for organizations? My screenshot is from https://github.com/LibreShift/red-moon

**Comment by westnordost** [comment]
Probably. But I'm fine with it, I trust you.

**Comment by smichel17** [comment]
I added the [`quest: building-type` label](https://github.com/westnordost/StreetComplete/issues?q=label%3A%22quest%3A+building-type%22+) and tagged a few issues with it.

Note (for anyone else who does this later: this is *not* an attempt to tag *every* issue that is about that quest — only the ones with significant discussion, that we might want to refer back to instead of repeating the same arguments. For example, this one was intentionally not tagged: https://github.com/westnordost/StreetComplete/issues/2138

I also did not try to comprehensively tag every issue with useful discussion about it, only the ones that I remembered seeing recently (and the original issue/PR that added the quest). So if you remember a useful discussion on the subject and it's not tagged, you're not going crazy :)

**Comment by peternewman** [comment]
> I understand that you are up for it?

I'm happy to do so too if you want more people.

> Hmm. Maybe it is different for organizations?

Well that brings me nicely onto my other point @westnordost . I wonder if it would help to create a StreetComplete-project organisation which you could shuffle the related projects into (obviously not Tangram, but everything created for or by SC):
https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#streetcomplete-related-projects

See for example:

**Comment by peternewman** [comment]
> I understand that you are up for it?

I'm happy to do so too if you want more people.

> Hmm. Maybe it is different for organizations?

Well that brings me nicely onto my other point @westnordost . I wonder if it would help to create a StreetComplete-project organisation which you could shuffle the related projects into (obviously not Tangram, but everything created for or by SC):
https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#streetcomplete-related-projects

See for example:
https://github.com/codespell-project/
https://github.com/LibreShift/

This would mean you could share permissions across repos if you wanted as well as making it easier for users to locate related projects such as the SC map style and report issues in the right repo, rather than having to dig into that contributing file and browse around.

**Comment by westnordost** [comment]
Ok, did this now. I also invited you

**Comment by peternewman** [comment]
Thanks @westnordost , although I don't seem to be able to triage currently.

**Comment by smichel17** [comment]
It seems I am no longer able to create labels, although I can still tag issues with existing labels. :confused: I suspect this is related to the change to an organization. (And *now* https://github.com/streetcomplete/StreetComplete/settings/access should have options :)

**Comment by westnordost** [comment]
Okay, appears that "triage" access rights are not enough to create labels. I changed your rights.

**Comment by smichel17** [comment]
After using these for a couple months, I can say they're definitely useful. I've referred to the labels regularly where before I would have had to flounder through a bunch of vague searches to find the right issue.

That said, I think labels are not the best abstraction for this type of organizing. The number of categories of common questions/answers is bound to grow, and the more it does, the more this will clutter the labels.

Also, it's difficult to link directly to a label — you have to go to the issue list => label list => specific label => edit the search query to remove `is:open` so it shows both open & closed issues => copy/paste the url. And then you end up with something gross like this: https://github.com/streetcomplete/StreetComplete/issues?q=label%3A%22feature%3A+quest+display%22+.

In order to render that nicely, like [`feature: quest display`](https://github.com/streetcomplete/StreetComplete/issues?q=label%3A%22feature%3A+quest+display%22+), you need to write:
```markdown
[`feature: quest display`](https://github.com/streetcomplete/StreetComplete/issues?q=label%3A%22feature%3A+quest+display%22+)
```

Instead, I think we should create an FAQ. That's really what it is — I've been doing contortions to not use the words "Frequently Asked Question" anywhere above. I think a pinned discussion thread is the best format for this. Each top level comment should be a topic, like I currently have with tags — `feature: quest display` or `quest: building type`.Then, in the replies, anyone can mention issues/discussions which contain important context (no special repo permissions necessary). Links to any of comments can just be pasted in to a comment and they'll be rendered nicely by github. People can even vote on them so the most-useful faq items bubble to the top, for people sorting by points.

@westnordost If that sounds good to you, I can set it up and delete the labels I've added; then you can remove my special repo access (or downgrade from contributor to reporter).

**Comment by smichel17** [comment]
Also cc @matkoniecz @peternewman

**Comment by mnalis** [comment]
@smichel17 there seems to exist [this SC FAQ in OSM Wiki](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ) do you suggest creating another one, or a section in that one over there?

**Comment by smichel17** [comment]
@mnalis I did not know that existed. It is similar to what I was thinking, but not the same. I was thinking of something more like a "development FAQ". The use case is still the same as it was when I opened this issue — making it easier to find the context for historically relevant decisions — I am just proposing a change in solution. I think it is reasonable to create a new FAQ here on GitHub, rather than the OSM wiki, because this is the place where it will be used.

**Comment by mnalis** [comment]
Sure, makes sense to be on GitHub. Though, it probably should not have `FAQ` in name, to avoid confusion. Maybe `Quest suggestion guidelines` or `Frequently suggested quests` or something better...

**Comment by smichel17** [comment]
Starting this

**Comment by smichel17** [comment]
Working through converting the labels to comments in https://github.com/streetcomplete/StreetComplete/discussions/2789. I like this solution much more so far.

**Comment by smichel17** [comment]
Also if anyone has a better name, I really like "Glossary", but "Development Glossary" is a bit awkward. It should be short so it fits in the pin at the top of the discussions page, though.

**Comment by mnalis** [comment]
Hm, "glossary" is confusing to me as it looks like "definition of words"... To me, "development glossary" would probably mean more like explanation of what Kotlin function in SC does, or something like that... 

"Frequently suggested quests" or "Quest suggestion guidelines" (as mentioned before) seem much more descriptive to me, but I agree it is longer... "Popular Quests" is shorter, but losses quite a bit of the meaning - maybe something in that direction would be more up to the point than "Development Glossary" ? Maybe "Problematic Quests", "Quests with issues" ?

**Comment by smichel17** [comment]
"Index" was my first idea, and maybe is the better word. I didn't choose it because indexes are usually alphabetical, and this one is not.

I also considered "Table of Contents", but that would imply something more comprehensive.

**Comment by smichel17** [comment]
> To me, "development glossary" would probably mean more like explanation of what Kotlin function in SC does, or something like that...

I think this is largely because of the word "development", which is not really the right word :P

I originally wrote it as "Development *Decision* Glossary", but "glossary" got cut off (on a vertical monitor). Maybe "design" would better. I guess "index" gets points here too, for length.

"Reference" is another good word.

> Frequently suggested quests / Quest suggestion guidelines

That's not what it is, exactly. I don't intend to put a link in there just because it is frequently suggested — I would add to the index when there is some discussion that I want to find again (such as an *explanation* of why a popular suggestion won't be implemented). This *happens* to also be *useful* as a sort-of-faq, when sorted by popularity, but it's not in FAQ format; it's more like a set of bookmarks.

**Comment by riQQ** [comment]
Throwing in *compendium* as a term

**Comment by mnalis** [comment]
@smichel17 Is the purpose just so we can link to some part of it when we suggest new quest for closing; or should people who intend to suggest quests be able to find it by themselves? 

If latter, it probably should be something that will catch their search terms and stand out - which most probably will contain word "quest" somewhere in it. "Quest Decision Tree" , "Quest Compendium", "Quest Design Index", "Designing Quests Pitfalls" ?

**Comment by smichel17** [comment]
I would say the purpose is mostly us finding links more quickly, and if someone suggesting a quest finds it, that's just an extra bonus.

**Comment by smichel17** [comment]
I've used it a few times and it's working well enough for me; I'm going to close this issue. Feel free to continue using it for meta-discussion about #2789 if there's anything else we should change.

**Comment by smichel17** [comment]
There is one annoying bug where GitHub's auto-shorten feature messes up if you have any query params. So,
`https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707`
gets shortened to https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707 and links the top-level discussion instead of [#2789 (comment)](https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707) (this link created manually).

**Comment by smichel17** [comment]
After a while of using this, I have mostly been the only one maintaining it. I'm not sure if others are using it, hopefully so, but it's been useful for *me* in any case.

Recently @matkoniecz added a [reply](https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1083442), and this made me realize that spreading the links out between multiple comments is going to be a pain. For example, as there are more replies, GitHub starts collapsing them by default— blegh.

So, updated plan:

- I'm going to move all the entries into the top-level comment
- Anyone can reply to those comments with suggestions of links to be added *or* changes to make
- When I've addressed the suggestions, I'll hide it and any replies as "outdated"
    - This is a tracking mechanism for me, so I know what I've incorporated. Also for readers, since the visible comments might have useful links that I didn't add yet.

This means meta-discussion in replies is fine, so there's probably not very much use for this thread any more, unless you have a suggestion for totally overhauling the thing.

This means meta-discussion in replies is fine
