### ISSUE TITLE
Provide hint in "can't say" menu for cycleways than you can tag "cycleway:both=no" with SC

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2285]
**Use case**
Multiple users left massive amount of notes "there is no cycleway of any kind here".

I dismissed it, but it keeps happening. This time in Poland with 90 notes by user who was confused by StreetComplete interface.

http://resultmaps.neis-one.org/osm-notes-country?c=Poland - part of notestorm here
![x9wUJp1](https://user-images.githubusercontent.com/899988/99306900-16d09900-2856-11eb-8ab8-5fcf417b5e0c.png)

Triggered by https://forum.openstreetmap.org/viewtopic.php?pid=808508#p808508

**Proposed Solution**
Have in "can't say" menu entry for "no cycleway of any kind here" that would either tag `cycleway:both=no` or educate user how to solve the quest.

Maybe also make "no cycleway" answer more prominent with some big red X as part of the icon in selecting answers?

EDIT: more links https://www.openstreetmap.org/note/2465507 https://www.openstreetmap.org/note/2465506 https://www.openstreetmap.org/note/2465505 https://www.openstreetmap.org/note/2455823

**Comment by matkoniecz** [comment]
It happened earlier, more than once, but I kept dismissing it as "isolated incident, also interface changed since that time".

**Comment by FloEdelmann** [comment]
> Maybe also make "no cycleway" answer more prominent with some big red X as part of the icon in selecting answers?

+1 from me for this suggestion. I've needed to search the correct graphic for "no cycleways" multiple times. Also, the sidewalks quest's answers do have a red :x: and a green :heavy_check_mark:, so it'd make the user interface more consistent.

**Comment by westnordost** [comment]
Should the answer option educate people about how to select it, or (pre)select it?

**Comment by matkoniecz** [comment]
> Should the answer option educate people about how to select it, or (pre)select it?

Probably educate. Someone confused about this is likely to be confused how to fill it.

It is also possible that someone failed to consider some more exotic bicycle infrastructure such as contraflow without a dedicated lane.

But it would offer a quicker way to solve this common case: "can't say" -> "select case" -> "confirm"

**Comment by travnick** [comment]
The whole issue was because the person that was adding the comments didn't see the "no cycle way" option on mobile because of screen size/not obvious icon.

Sorry for that.

**Comment by westnordost** [comment]
Assuming you are that person, how could this be made more clear?

**Comment by travnick** [comment]
It wasn't me :D. I need some time to ask the questions and see how the app is used in such cases.

**Comment by theraser** [comment]
Sometimes I get confused using the cycleway-questions, too.

The issue here I think is that you don't recognize the "there is no cycleway"-icon as that option in the first moment when scrolling through the available options.

> > Maybe also make "no cycleway" answer more prominent with some big red X as part of the icon in selecting answers?
> 
> +1 from me for this suggestion. I've needed to search the correct graphic for "no cycleways" multiple times. Also, the sidewalks quest's answers do have a red ❌ and a green ✔️, so it'd make the user interface more consistent.

Yes, that's what I would suggest to make this more clear without any complex changes. Just replace the current icon for "no cycleways":

![Street-Complete_2](https://user-images.githubusercontent.com/7988080/102541064-37d41600-40b0-11eb-88de-f9cd75db42be.png)

with the existing one with a ❌ (from sidewalks question):

![Street-Complete_1](https://user-images.githubusercontent.com/7988080/102541113-4cb0a980-40b0-11eb-8535-2195d25a071d.png)

Done! :-)

**Comment by matkoniecz** [comment]
After encountering next set of notes I implemented something very similar as the first part: https://github.com/streetcomplete/StreetComplete/pull/2385

**Comment by smichel17** [comment]
I think #2405 would work, but is an inelegant solution. What about this as an alternative (albeit, higher development effort)?

- Break the form apart into two steps.
- In the first step, simply enter the *markings* on each side.
- In the second step, enter how the bicycle traffic flows.
    - Perhaps sometimes this can be skipped, depending on what markings are entered.

If the tagging schema allows, you could split this into two quests.

**Comment by smichel17** [comment]
Or maybe the other way around would work better. First select the directions of flow (none, one, both), then select the markings for one/both way only (no travel would have no markings, unless we want to distinguish between unmarked and explicitly forbidden).

**Comment by matkoniecz** [comment]
> In the first step, simply enter the markings on each side.

And at that point people would create note "no cycleway here" like some of them are doing now.

**Comment by smichel17** [comment]
> Or maybe the other way around would work better.

**Comment by matkoniecz** [comment]
Still, it would likely take me full day to implement and test (plus @westnordost  time for reviews) and I bet that it would not solve the problem.

**Comment by smichel17** [comment]
> I bet that it would not solve the problem.

- Question 1: May bicycles ride on this street?
    - Side 1:
        - [ ] :x: No
        - [x] :arrow_up: Yes, only in the direction of traffic
        - [ ] :arrows_clockwise: Yes, in both directions
    - Side 2:
        - [x] :x: No
        - [ ] :arrow_down: Yes, only in the direction of traffic
        - [ ] :arrows_clockwise: Yes, in both directions
- Question 2: Is there a bicycle lane?
    - Side 1:
        - [ ] :black_large_square: No markings, but cyclists ride on the road
        - [ ] :arrow_double_up: Lane shared explicitly with other traffic
        - [ ] :bike: Cycle lane
        - [ ] (etc)
    - Side 2:
        - [ ] :black_large_square: No markings
        - [ ] :no_entry_sign: Explicitly forbidden

You really think that someone is going to look for "cyclists may not ride on this street" in the "other options" menu with that first question?

> it would likely take me full day to implement

Yes, I totally acknowledge it's higher effort, maybe not worth it at this point in time.

**Comment by matkoniecz** [comment]
partial revert proposed in https://github.com/streetcomplete/StreetComplete/issues/6984
