### ISSUE TITLE
Show other nearby objects of the same type when answering quests

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2354]
**Use case**
There have been a number of quests already where it would help (e.g. bench backrests, postboxes etc), but it's become even more vital with "Is x still present?". We need to be able to see all the other nearby x's while answering the quest. But likewise for any other nodes not visible on the map, so when I answer or re-confirm a postbox, it can show the nearby ones so I know I'm actually answering the quest on the right node.

**Proposed Solution**
When you select the bin for example, it should show the other nearby bins in a say 30m radius or whatever as dots on the map (probably in a different colour to the quest dot). Presumably this shouldn't be too hard now you're downloading the whole tile and processing it offline, we'd only need to keep the co-ordinates of them.

Otherwise any time the nodes are added at different times (e.g. if I notice one is missing and add it now), or just if I didn't get a chance to answer both adjacent postboxes in one go, myself or the next person is left with a pin/quest and no idea which of the two it applies to.

This is on v28.0-beta1 onwards

**Comment by westnordost** [comment]
Would surely be a good improvement, but would also be very much work to implement. I do see it less dramatic than you, because when answering that the X is not there, the user is warned that he should look around if he sees the X somewhere near and that in doubt, he should rather leave a note. Leaving a note will also lead to that the maybe wrongly placed X is moved to the correct location.

The other problematic case would be that there are two Xs really close to one another and people might wrongfully answer that both exist even though one is gone (already). I'd expect that the user will notice that something is not right when he is asked for the second X, and will leave a note. But even if he doesn't notice (or the situation is as described in your last paragraph), it would only lead to that a bogus X still continues to be on the map. It's not nice, but not critical.

**Comment by peternewman** [comment]
> Would surely be a good improvement, but would also be very much work to implement.

I thought you're fetching and parsing the tile already to find quests, so storing just the co-ordinates of the nearest `amenity=phone_box` and rendering on the map wouldn't be too complex. Or do you just mean it's a lot more complicated than adding another quest? Rendering them on the map would also work, but I'm assuming they're not in the tile.

> I do see it less dramatic than you, because when answering that the X is not there, the user is warned that he should look around if he sees the X somewhere near and that in doubt, he should rather leave a note. Leaving a note will also lead to that the maybe wrongly placed X is moved to the correct location.

I'd agree with you mostly for the case of one X and no others being visible nearby, I can leave a note and update the map (and I did just this). Although that rather relies on me manually tapping the other nearby quests to confirm they aren't also another X.

I don't think it's that simple though. If there are two benches and two bins on the map:
`bench bin bench bin`

But in reality one bin has gone so it's now:
`bench bin bench`

When I'm on SC I'll probably see one quest pin and three dots. When I go to answer the first bench exists quest, I don't know what the other things are, so I say yes. I then get the right most bin, I can see a bin so I say yes. I get a bench and say yes, then another bin and realise I said yes to the wrong bin so I have to leave a note.

Similarly if one of those benches has a backrest and one doesn't. Or multiple recycling bins with different stuff they accept.

> The other problematic case would be that there are two Xs really close to one another and people might wrongfully answer that both exist even though one is gone (already). I'd expect that the user will notice that something is not right when he is asked for the second X, and will leave a note. But even if he doesn't notice (or the situation is as described in your last paragraph), it would only lead to that a bogus X still continues to be on the map. It's not nice, but not critical.

You also assume it's always the same user answering the quests, and always at the same time.

I've just added another ticket machine next to one I'd earlier tagged as existing. From my understanding because I didn't modify the first one at this time, N months after they were each last modified they'll pop up again with the do they exist question. Which means they could be separate surveys by the same person or different people, so they have to keep track of which one they answered the question on.

I answered the collection times for one post box, but did the other one on the next trip; it relied on me personally remembering which one I'd read collection times from last time, to ensure I read the other one this time.

This all gets far more complicated when the other items are on another level, so potentially adjacent but in reality no-where near the one I'm trying to answer.

**Comment by matkoniecz** [comment]
> Or do you just mean it's a lot more complicated than adding another quest?

Yes. It is significantly more complicated.

**Comment by peternewman** [comment]
Okay, so in terms of other options. I'm guessing the data just isn't in the map tiles to keep them small (i.e. it's not just a style that can be turned on like day/night mode)?

Alternatively can I suggest a slightly bolder step, hiding the existence quest, and probably others like postboxes when there is another object of the same type within say 10m or whatever. I assume that should be easier to query for? I've just been doing a road which was full of pairs of phoneboxes and single ones, benches and bins, which was a bit of a memory challenge with the current behaviour.

**Comment by rouelibre1** [comment]
Just to add feedback on that topic : I've struggled with this more than once for bicycle parkings capacity.

My most recent example : there was just one quest marker on the SC map asking "How many bikes can be parked here ?" and I saw there were 6 small groups of bicycle stands, but no idea how they were mapped in osm.

I ended up leaving a note in the app https://www.openstreetmap.org/note/2464162 and back at home I found out these were mapped as one single node with the total capacity = 82 (https://www.openstreetmap.org/node/4792307307). I could also have "cheated" with another app like Vespucci of course.

So I believe it can confuse some users who will give up when faced with such situations or make mistakes and provide wrong answers.

**Comment by peternewman** [comment]
@westnordost from what I vaguely understand of the #2506 / Element First Class stuff, would this finally enable this, as you'd then have all map data to begin with and could tag ones of the same type nearby to an active quest to not be cleaned up? Then it's just some GUI stuff to show them at the appropriate time?

**Comment by westnordost** [comment]
Yes, it would enable this,  but it would still need to be implemented 

Am 25. März 2021 04:28:14 MEZ schrieb Peter Newman ***@***.***>:
***@***.*** from what I vaguely understand of the #2506 / Element
>First Class stuff, would this finally enable this, as you'd then have
>all map data to begin with and could tag ones of the same type nearby
>to an active quest to not be cleaned up? Then it's just some GUI stuff
>to show them at the appropriate time?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2354#issuecomment-806336615

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
