### ISSUE TITLE
New quest for adding turn:lanes

### ISSUE THREAD

**Issue by hubtux** [streetcomplete/StreetComplete#2361]
will there be a new quest for turning possibilities of a lane at intersections or turns?
Sometimes it is not allowed to turn left to avoid oncoming traffic, but it is allowed to turn there from other directions.
so the value turn:lanes will be filled by direction.

**Comment by westnordost** [comment]
Maybe. You could suggest such a quest type.

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/101669631-7cc5d000-3a52-11eb-8e86-5bc1a25e9d63.png)
