### ISSUE TITLE
minor UI improvement: +/- buttons on step count quest

### ISSUE THREAD

**Issue by jtracey** [streetcomplete/StreetComplete#2362]
**Use case**

Counting steps can be a bit tedious, especially on larger staircases.

**Proposed Solution**

Add the +/- buttons from the housenumber quest to the step counting quest, so you can just hit the + button once per step (e.g., as you're climbing them) instead of counting in your head then typing it in. Obviously a very minor improvement, just thought it might be an easy UI change since it's already in the app.

**Comment by peternewman** [comment]
Personally I don't think I'd trust my tapping of a button on the screen while walking to be that accurate, but maybe others don't have such fat fingers/

**Comment by jtracey** [comment]
I mean, I don't see why it would be any more difficult than the housenumber quest? Or using [one of these](https://nextcity.org/images/made/File_HandCounter_920_606_80.jpg).

**Comment by peternewman** [comment]
> I mean, I don't see why it would be any more difficult than the housenumber quest?

I don't know about you but I walk to the next house, check the number and then use the buttons on the house number quest.

> Or using [one of these](https://nextcity.org/images/made/File_HandCounter_920_606_80.jpg).

I'd be happy with one of those (or something linked into the volume buttons or whatever). My comment was making sure I'm pressing the right part of the screen as I take my steps while concentrating on walking up the stairs not falling over them.

**Comment by westnordost** [comment]
Yeah, see @peternewman

**Comment by smichel17** [comment]
search keywords: increment steps counter

**Comment by HolgerJeromin** [comment]
We could make a "count mode" and count clicks on the hardware volume keys on the phone :-)

Camera apps often/always can trigger capturing an image by that, too.

**Comment by timothywashere** [comment]
I trust tapping a button more than my ability to keep a number in my head for several minutes.
If there's more than about 10 steps I'd have to say the number out loud to keep track, then everyone nearby thinks I'm a lunatic.

**Comment by peternewman** [comment]
> We could make a "count mode" and count clicks on the hardware volume keys on the phone :-)

Cough!
> > Or using [one of these](https://nextcity.org/images/made/File_HandCounter_920_606_80.jpg).
> 
> I'd be happy with one of those (or something linked into the volume buttons or whatever).

Although I also manage to regularly miss-trigger the camera button on my phone, but that's probably a bit different as this would only do something in this mode presumably.

> I trust tapping a button more than my ability to keep a number in my head for several minutes.

We use a lot of touchscreens and touchscreen control panels in my day job, even sitting at a desk/standing still it can be easy to miss-press, especially if you're not looking at the screen. To make it reliable especially given you're walking up or down stairs at the time you'd need to do far more than just copy the buttons from the housenumber quest. You'd probably want one or more of the following:

1. Tactile feedback each time you tap a button (but how do you differentiate + from -, although I guess you should only be pressing + in counting mode)
2. Large buttons, like 25%+ of the screen, but how do you get out of this mode, and how do you ensure you don't exit it early without realising (I guess it could just discard your work at that point).

> If there's more than about 10 steps I'd have to say the number out loud to keep track, then everyone nearby thinks I'm a lunatic.

You haven't mastered the counting in your head thing then? :stuck_out_tongue_winking_eye:

**Comment by jtracey** [comment]
I guess I'll chime in again since it's being brought up (I didn't want to beat a dead horse last time, so just dropped it):

>I don't know about you but I walk to the next house, check the number and then use the buttons on the house number quest.

I do not stop walking when doing house number quests, and I suspect in denser urban areas with lots of quests, most people don't -- I look up, see the next number, look down, tap the quest, double tap + in most cases, and repeat, all without stopping. I think avoiding this feature is being overly cautious, and in any case, I agree with others that I'm far more likely to mess up counting dozens of steps in my head than I am to just tap a decently large touch screen button every time I step. It would also probably be even easier when just looking at a large set of stairs, without climbing them.

>You haven't mastered the counting in your head thing then?

This is rude and unhelpful.
