### ISSUE TITLE
Quest symbols sometimes obstruct house numbers

### ISSUE THREAD

**Issue by Amateuhr** [streetcomplete/StreetComplete#2364]
Sometimes house numbers are completely obstructed by the quest symbols. This creates difficulties in finding the correct loacation on site. Zooming in or out does not help. It seems that both the house number and the quest symbol placement follow the same algorithm. Solutions could be semi-transparent symbols, the possibility to temporarily hide the symbols or to use a different algorithm for the placement.
![Screenshot_20201210_090326_de westnordost streetcomplete](https://user-images.githubusercontent.com/75780443/101753809-5a27cb80-3ad3-11eb-864a-fb283d36f477.jpg)

**Comment by Helium314** [comment]
This is pretty similar to #1609.
If the house number is tagged on the building, you should see it when answering the quest. If it is on a node inside the building, unfortunately this doesn't work. Rotating and zooming the map often helps, but this is really annoying...

@westnordost: is it possible to show the number in the quest in case it is only on a node inside the building? For the house number quest those nodes are already analyzed, so maybe it is possible to re-use this?

**Comment by westnordost** [comment]
>  is it possible to show the number in the quest in case it is only on a node inside the building

No.
Nothing can be done for when the housenumber is a node within the building outline.

**Comment by westnordost** [comment]
I tried making the housenumber labes not collide with anything, but then the housenumbers are simply obscured mostly by the pins and you can't read them. So right now, this nothing can't be done about this. Maybe after the new tangram-es version comes out.
