### ISSUE TITLE
Don't ask for backrest on bench:type=stand_up

### ISSUE THREAD

**Issue by SupaplexOSM** [streetcomplete/StreetComplete#2365]
**Use case**
There is a tagging for "stand-up benches", which can be specified using the addition ["bench:type=stand_up"](https://wiki.openstreetmap.org/wiki/Key:bench:type) on normal bench objects ("amenity=bench"). SC asks for these objects whether they have a backrest. However, this type of bench is not intended to lean against and also from a constructional point of view it is often unclear whether one can speak of a backrest here or not. Therefore, the question usually cannot be answered clearly for these objects and "backrest" is unnecessary/should not be used in this case.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Bench_type_stand_up_01.jpg/320px-Bench_type_stand_up_01.jpg) ![](https://wiki.openstreetmap.org/w/images/thumb/2/29/Bench_type_stand_up_02.jpg/320px-Bench_type_stand_up_02.jpg)

**Proposed Solution**
Don't ask for a beckrest on objects tagged with "bench:type=stand_up".

(See also [this note](https://www.openstreetmap.org/note/2421292) in german language.)

**Comment by westnordost** [comment]
Mh I would actually say any `bench:type` (for now). Maybe not `seated` but it is not clear if `seated` is the "normal" bench or if it implies that it is a normal bench with backrest. So better not ask at all for any of these.

**Comment by SupaplexOSM** [comment]
Why not? Because the value is implied (block usually don't have backrests, loungers have one)? I think it should still be asked in the other cases, because "backrest" is something like the "main attribute" of a bench, but "bench:type" is rarely used (for tagging and evaluation)...

**Comment by westnordost** [comment]
> Because the value is implied?

Yes

**Comment by peternewman** [comment]
Forgive my ignorance @SupaplexOSM but even looking at the pictures and the Google Translate of the discussion I'm none the wiser. The upper bar in both cases looks very much like a backrest to me (compared to if only the upper one existed and you perched on it (like sitting on a railing). Are you suggesting they stand on the lower one (the wooden one on the left picture) and then sit on the upper bar? That just seems like a way youths like to sit on any bench even a traditional one.

FWIW I think it would help to add an image, even if it's just a stick figure crudely drawn on top, to illustrate how these benches are supposed to be used so we can differentiate them.
