### ISSUE TITLE
Ask oneway quest for ways with `cycleway=opposite`

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#2366]
**Use case:**
Tagging a way with `cycleway=opposite` without `oneway=yes` doesn't make sense. Osmose already [warns about these mistakes](https://github.com/osm-fr/osmose-backend/blob/master/plugins/Bicycle.validator.mapcss) (e.g. [here](http://osmose.openstreetmap.fr/de/map/#zoom=17&lat=48.10143&lon=11.789091&item=2030&level=1&tags=&fixable=)).

**Proposed Solution:**
Integrate this case into the oneway quest.

**Comment by westnordost** [comment]
What exactly is the problem?

**Comment by FloEdelmann** [comment]
According to the [`cycleway` OSM Wiki page](https://wiki.openstreetmap.org/wiki/Key:cycleway), if a way is tagged with `cycleway=opposite` (or `cycleway=opposite_lane` or `cycleway=opposite_share_busway`), it should also be tagged with `oneway=yes` and `oneway:bicycle=no`.

If `cycleway=opposite` is tagged without `oneway=yes`, then either just `oneway=yes` could be missing (which the oneway quest could add), or `cycleway=opposite` is wrong (which the oneway quest could remove).

With *the oneway quest* I mean the one that asks "Is this a one-way street?".

**Comment by westnordost** [comment]
Okay, understood

**Comment by matkoniecz** [comment]
There are 1453 such ways worldwide - http://overpass-turbo.eu/s/119d

2486 after expanding to some variants - http://overpass-turbo.eu/s/119f

**Comment by westnordost** [comment]
That's not really many.

I think this should/can't be done.

In such cases, if the user answers `oneway=yes`, there is not problem. However, if he answers that it is not a oneway, it's unclear what StreetComplete should do with the `cycleway` tag. The `cycleway(:*)=opposite(_*)` tagging is ambiguous in some cases and even if possible at all, it will be quite difficult to interpret the type of cycleway and set it to something not `opposite` correctly. So, to retag `cycleway` cannot be done and be correct 100% of the cases without asking the user more questions.

Examples:
- `cycleway=opposite_lane` on street that is not a oneway (any more). On which side is the lane? `cycleway=opposite_lane` means that there is a lane in contraflow direction and it is undefined whether there is any lane in flow direction. Thus, changing it to `cycleway=lane` could be wrong
- any `cycleway:*=opposite_*` is ambiguous and it is not clear what it means, thus it is not clear how it would need to be changed to mean the same when the `opposite` stuff is removed

The cycleway-stuff is being asked every few years. Any such invalid tagging will be overwritten by StreetComplete when re-answering the cycleway question. Thus, these warnings/errors are also treatable in STreetComplete as is.
