### ISSUE TITLE
Layer not shown on check exists quest

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2367]
Layer not shown on check exists quest

Or possibly not shown when layer=-1

E.g. https://www.openstreetmap.org/node/3359292021

**How to Reproduce**
E.g. https://www.openstreetmap.org/node/3359292021

**Versions affected**
SC v28.0-beta1

**Comment by peternewman** [comment]
Although looking at the code, do we need to tag:
`tags["location"] == "underground"`

Or level.

**Comment by westnordost** [comment]
Yes, `level`. 

`layer` is only for renderers. `layer=-1` doesn't mean it's underground.

**Comment by peternewman** [comment]
Okay. The path its on is tagged as tunnel=yes which doesn't seem right for an object, but I'm not sure anyone has worked out the formal levels of the station.

**Comment by matkoniecz** [comment]
For this specific object I opened https://www.openstreetmap.org/note/2460829
