### ISSUE TITLE
Question about height limit below a bridge – but there is no bridge

### ISSUE THREAD

**Issue by stefannagy** [streetcomplete/StreetComplete#2370]
Yesterday I installed StreetComplete 27.2 via F-Droid. I used StreetComplete before but I had flashed my phone some days ago. When flashing my phone I formatted the data partition so I guess this was really a fresh install of SteetComplete.

I took a walk and answered some StreetComplete questions. One of the questions was "What is the height limit below the bridge?" for a track and since it didn't make any sense I added a note, see https://www.openstreetmap.org/note/2460905. I thought that there was a data problem but when I came home and took a closer look I couldn't find a good reason for this question…

**How to Reproduce**
I didn't try to reproduce this bug. Please tell me if you need more info.

**Versions affected**
Android version: 10 (LineageOS 17.1 without gapps)
StreetComplete version: 27.2

**Comment by westnordost** [comment]
> I didn't try to reproduce this bug. Please tell me if you need more info.

Can you please go into the settings and select "clear quest cache", then download this area again?

**Comment by stefannagy** [comment]
I cleared the quest cache and yes, I can reproduce this bug. I get the question "Was ist die Durchfahrtshöhe unter dieser Brücke?" ("What is the height limit below the bridge?") for way 155237135 again.

**Comment by westnordost** [comment]
Ok, I'll have a look

**Comment by stefannagy** [comment]
Great, thanks!

**Comment by westnordost** [comment]
Ok, the problem was that the algorithm to find out whether two ways intersects was counting touching endpoints also as an intersection. Weird that this didn't strike someone's attention earlier.
