### ISSUE TITLE
Override "back" button to avoid exit during new achievement animation

### ISSUE THREAD

**Issue by goldfndr** [streetcomplete/StreetComplete#2371]
**Use case**
Each time I achieve a new achievement, I receive the animation and expect to use the "back" button to stop it. Tapping "back" does admittedly stop it, but also includes the adverse side-effect of exiting the app. (It's admittedly just a couple of taps to launch anew from Recents.)

**Proposed Solution**
Temporarily override the "back" button to function as an animation halt/dismiss instead of an app exit during newly achieved achievement animation.

**Comment by westnordost** [comment]
That's a bug

**Comment by westnordost** [comment]
Hm, it's not a bug after all, but certainly feels like one. So Ill implement this.
