### ISSUE TITLE
Not all quests are shown

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#2373]
There are lot of nearby quests and I want to answer a certain one but cannot. The UI (even on highest zoom) only displays a small circle, not the actual quest. If I solve some of the nearby quests, then suddenly the circle turns to a proper quest and can be solved.

However, this is not always possible. For example, if I can answer the opening hours clearly for one shop (but the UI does not let me do this, only circle) and the neighbouring one does not show the opening times, I cannot answer the opening times at all.

**How to Reproduce**
A random example I just now can display on my phone. (I wish I could do screen shots there ..):
I go to 50.75758, 7.07124. There are three quests at the end of the tram line, the "upper" two are shown, the lowest one is only a circle, even at highest zoom level.

**Versions affected**
Version V27.2 Android 10

**Comment by Helium314** [comment]
You can
* hide the quest for the neighbouring shop: other anwers -> can't say -> no, just hide
* answer that the neighbouring shop does not show the opening hours: other answers -> no opening hours sign

**Comment by hmartink** [comment]
Well, this works if I really cannot answer the opening times for the other store, i.e. I've actually looked at the other store's opening times. And yes, this really means looking, because often it is hidden somewhere in the front or at some door. Time I do not want to spend, just to answer the quest I can readily do (because I'm seeing the the opening times right in front of my eyes and have a second to spare to enter or confirm them, but not to walk to the next store (which I'm not interested in at all) and search and then return.)

Another common use case is that I see some part of a street or some building and then I see the circle in StreetComplete, indicating that there is a quest. I'd love to answer the quest, but not to answer other quests hoping to uncover the quest I'm actually interested in. Often happens when I ride my bike or in a traffic jam when my wife drives - I can easily spot some things and correct them, but there is little opportunity and desire to investigate much at this point of time.

**Comment by Helium314** [comment]
I would still say hiding unwanted nearby quests is the way to go in such cases. It's a bit slow as it takes many taps (but that's still better than e.g. having many overlapping quest pins where you will have the same problem that some are not reachable without hiding/answering others).

If you want to go back later to fill in the semi-hidden opening hours you can restore hidden quests in the settings.

**Comment by hmartink** [comment]
In the example I cited in my initial post (unrelated to opening times, just the first occurrence I found by chance while reporting) there is plenty of space to turn the circle into a quest. If it is too crowded, I might understand this selection. But I would assume that a user should be able to zoom in as much as necessary to see any quest. In the past, this was the case (well, a similar bug was present earlier (last year)? and it got fixed.

**Comment by Helium314** [comment]
As far as I remember, zooming in 'as much as necessary' (would definitely be useful in such cases) is not possible in Tangram ES (which is used to display the map)

**Comment by smichel17** [comment]
For context, see also the opposite problem, https://github.com/streetcomplete/StreetComplete/issues/2358 (and all the issues linked from there)

**Comment by hmartink** [comment]
Thanks for the pointers, and they explain a related, but different problem. In that issues the question is which quests to show, e.g. should building levels be shown? Roof tops? So the casual (or car) user would only see some quests, not all. This is interesting, but I know how to configure which quests I see (and the priority).

This issues is about selecting between the same type of quests. So three shops adjacent. Four road pavings (think of a crossing) etc. Of course, sometimes there *might* be competitions between different quests (type of building and building levels), but this would be a related by different problem.

What I've also experienced is that quests jump. E.g. when I answer the type of building the next quest (levels) briefly shows up but becomes invisible and the same quest (here: building levels) but for the adjacent building is now shown. Once I've answered this, I'm now back to the initial building just to do the same jump again for the roof top.

So in both cases (same quests appear for nearby objects and same quests already on nearby objects) StreetComplete chooses which one to display and I cannot override this. I might work around this as Helium314 indicated (but I'm not completely sure I understood) but this would be time consuming, especially if I just want (or I'm just able to) map this singular object, not the same quest on a nearby object.

If the underlying display engine is not able to do this, maybe this bug should be forwarded to allow for this (if I understood Helium314 correct).

**Comment by westnordost** [comment]
I'm sorry that you invested so much time into describing the issue. It cannot be fixed.

**Comment by hmartink** [comment]
Thanks for the information. This is a pity, as I encounter this regularly, that I cannot fix the obvious. Hopefully at some time in the future (e.g. when Tangram ES gets improved) this can be tackled again.

**Comment by westnordost** [comment]
There is not such a fine-grained control over which pins are shown and which not possible with the map rendering library we use. And even if there was, it stands to question what exactly could be changed from the current behavior. But as said, it doesn't even make sense to talk about this because it is not possible anyway.

**Comment by rhhsm** [comment]
One of my main frustrations with SC too. Would it be possible to allow further zoom in with reduced map tile quality or even without map, just so I can select the particular quest and then zoom out again? Or to show all quest pins (maybe as an option), even if they overlap? It will be more difficult to select the sliver of a pin that's not on top, but it at leaves gives you a chance. I surveyed a shopping street today, with a string of shop quests with only a few of them selectable. It happened the selectable shops had changed, so I needed the information about the unselectable shops so that I could figure out which was which.
