### ISSUE TITLE
Incorrect rendering of building boundaries (confusing)

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#2374]
![24429](https://user-images.githubusercontent.com/46402758/102235030-31983b00-3ef2-11eb-9a9c-a2341c6b0c42.jpg)
![Bildschirmphot](https://user-images.githubusercontent.com/46402758/102235033-3230d180-3ef2-11eb-8ae2-5155967cc758.png)

I stood in front of the buildings shown in the photograph. Position is 50.76966, 7.04487. I was asked what the left building is (where the 22 is printed). A small fraction of it belongs to the building with the sattelite dish on top. While this is clearly shown in www.openstreetmap.org, Streetcomplete puts the boundary of the two buildings different, i.e. as if the door (with the 22 above) belongs to the leftmost building. (Where the garage starts). My note was (obviously) closed because in the Web version everything is right, while StreetComplete displays it wrong.

For this instance I can of course fix this (by ignoring StreetComplete's incorrect rendering) and answer the quests appropriately (which I did not do yet on purpose). However, this appears to be some rendering issue thus I report it.

**How to Reproduce**
Go to 50.76966, 7.04487 and look how the boundaries of building 22 are rendered. Compare the output of StreetComplete and www.openstreetmap.org

**Versions affected**
StreetComplete v27.2
Android 10

**Comment by Helium314** [comment]
According to history, the buildings were modified recently: https://www.openstreetmap.org/changeset/95803576
I am not sure how long it takes until maps displayed in StreetComplete are updated, but usually it's a few days.

**Comment by westnordost** [comment]
Don't see a problem here.

![image](https://user-images.githubusercontent.com/4661658/102380695-84dcbd00-3fc8-11eb-99a8-bb84371e49d6.png)

**Comment by Helium314** [comment]
Just for reference: this is what it looked like yesterday: (minor differences)
![sc](https://user-images.githubusercontent.com/43007630/102392265-2408b100-3fd7-11eb-9c0b-5bed28ed54ce.png)
