### ISSUE TITLE
Pause resurvey of opening times

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#2375]
**Use case**

Recently a new quest appeared, asking me to reconfirm opening times. In general, I think this is a very good quest (I always wondered how to keep this up to date). However, currently in the pandemic with various scales of lockdowns opening times change rapidly. For example, in November many restaurants changed into takeways with different opening times. Tomorrow many shops are closing in my part of the world, thus their opening times are exceptional yesterday and tomorrow. And until the pandemic boils down I expect further similliar changes to come, where opening times change frequently. So I believe it does not make sense to answer this quest right now, at least not in general. Maybe groceries or pharmacies would work, but I do not know for other countries and regions and making exceptions to them appears error prone at the least.

**Proposed Solution**
Pause this new quest until a sufficient part of the population (at least in many parts of the world) has received a vaccine and thus stores are operating more reliable again. Without being able to predict the development (and I may be very off here) I would say at least until Q3/2021. Then for all stores ask this quest again, even if the opening time was answered already in 2020. This would have the added benefit that bankrupt stores (which are unfortunately likely to be - I've already read reports on them) would be easily spotted because the mapper would leave a note when trying to determine the "new" opening time.

**Comment by Helium314** [comment]
If you use the more frequent resurvey intervals, the quest is asked every 6 months anyway. So you can enter the current opening hours now and answer the quest again by Q3/2021.

My impression is that many shops kept the opening hours constant after the changes in first half of 2020, so in my opinion asking makes sense. (Although for restaurants and similar this may be questionable, as they have to deal with quickly changing regulations.)

**Comment by westnordost** [comment]
I also say this is each individual user's choice whether one wants to record it or not. Personally, I usually record it unless it is clear that these are just temporary opening hours.

**Comment by matkoniecz** [comment]
Note that if it makes no sense to answer this right now in your area - you can switch it off in the app settings.
