### ISSUE TITLE
In Credits, "Art contributors" section link authors.txt files residing at GitHub

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2379]
**Use case**
It would be nice to clearly list also this contributors.

**Proposed Solution**
Do it in the same way as code contributors are linked to Github statistics.

**Comment by westnordost** [comment]
This is something different. People who contributed code specifically contributed code to this project. While in the authors.txt, each the authors and licenses for various works (mostly photos) are credited - those didn't actually contribute to the project but just put their work under an open license.

Many licenses, even the most basic ones, like the CC license

> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, **but not in any way that suggests the licensor endorses you or your use.** 

(emphasis mine) actually forbid to convey the impression that the licensor endorses how I use his work. If I make it look like he contributed to the project, that falls very much into this definition.

So I am not going to do this for two reasons:
1. legal concerns
2. dignify people who really contribute to this project and not diluting their contribution by mentioned all kind of people unrelated to the project. For example all the achievement graphics that Judith Gastell contributed specifically for this project - that was a lot of work, and it very much makes a difference if she made them just for this project or if I found these in some "free vector graphics archive"
