### ISSUE TITLE
Misleading two-way bicycle traffic icon at one-way streets

### ISSUE THREAD

**Issue by theraser** [streetcomplete/StreetComplete#2382]
I noticed that the cycleway quests got a misleading icon for "none, but cyclist may use road in both directions". This is the same "sharrow" icon used for "lane shared explicitly with other traffic" (pictograms.svg), which in reality isn't the same at all.

<img src="https://user-images.githubusercontent.com/7988080/102545338-681eb300-40b6-11eb-801a-27993d82777b.png" width="200"> <img src="https://user-images.githubusercontent.com/7988080/102546481-fba4b380-40b7-11eb-96c4-a2469e57cdab.png" width="200">

Maybe we could use a part of this public domain image to indicate two-way bicycle traffic or modify the existing "cycle lane, both directions"/"cycle track, both directions" icon?

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Zusatzzeichen_1000-32_-_Radfahrer_kreuzen_von_rechts_und_links%2C_StVO_1997.svg/800px-Zusatzzeichen_1000-32_-_Radfahrer_kreuzen_von_rechts_und_links%2C_StVO_1997.svg.png" width=200>

Source: [Wikipedia German two-way cycling traffic](https://de.wikipedia.org/wiki/Datei:Zusatzzeichen_1000-32_-_Radfahrer_kreuzen_von_rechts_und_links,_StVO_1997.svg)

**Comment by matkoniecz** [comment]
> misleading icon

Note that some places often use this sharrow icon on streets with contraflow without explicit lane. Photo below from Poznań, Poland.

![external-content duckduckgo com](https://user-images.githubusercontent.com/899988/102546851-91404300-40b8-11eb-98bc-9b99162cbdce.jpeg)

And some countries like Poland do not use sign that you linked.

**Comment by westnordost** [comment]
I've also seen places in Germany with bicycle contraflow and a bike pictogram printed on the road. Maybe without this double roof, but there was a bicycle pictogram.

**Comment by theraser** [comment]
Thanks for the feedback, very interesting!

Okay, so there are different signs on the road to indicate two-way bicycle traffic. But I still would suggest to modify the icon for the app: at the moment there is the same icon for two completely different tasks which confuses me (no amateur) every time I use the app :slightly_smiling_face: I think that some kind of icon with two arrows (don't need to be the German sign 1:1) would be more intuitive - and would be understandable in all countries.

**Comment by theraser** [comment]
Thanks for pushing the change that fast, just saw it after updating :+1:

For me this is fine as I'm known to the app/OSM, but I'm working/training with people which are not familiar with the details of cycling infrastructure and apps in general - which is why I try to make it as easy to use and self-explaining as possible. The discussed question is only asked for **one-way** streets and I would suggest to add an icon with **two** arrows as this is the "special" feature we want to know ("both directions"). That way one ordinary person could understand the general meaning by looking at the icon without reading the description first.

I think that the usage of (country-specific...) one-way signs in combination with a bicycle and two arrows instead of using the symbols on the street would be even better, but this would require a lot of work to get all the different signs. Two simple arrows should be easy to use worldwide.

Current status:
<img src="https://user-images.githubusercontent.com/7988080/103153247-827c1f00-478f-11eb-9d1f-4d12017533aa.png" width="300">
