### ISSUE TITLE
Is this bus stop well lit or has a light? 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2383]
### General
Affected tag(s) to be modified/added: [lit](https://wiki.openstreetmap.org/wiki/Key:lit)
Question asked: **Is this bus stop well lit or has a light?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

We currently don't have a quest for lights on a bus stop. In remote areas there are lights on the bus stops and the intersections, but not on the street itself. 

At night you might feel a bit more comfortable waiting on a well lit bus stop, than in pitch darkness. So there's one possible usecase for the data.

**Comment by matkoniecz** [comment]
> In remote areas there are lights on the bus stops

In which country? At least in Poland it is rather unusual.

**Comment by RubenKelevra** [comment]
> > In remote areas there are lights on the bus stops and the intersections, but not on the street itself.
> 
> In which country? At least in Poland it is rather unusual, so such quest would not be useful there.

Germany 

They started to install solar powered motion lights like 10 years ago in my area and some bus stops also have permanent lighting from grid power.

**Comment by matkoniecz** [comment]
6159 bus tops in Germany with tagged `lit` - http://overpass-turbo.eu/s/11l5 

So StreetComplete would not be inventing completely new tagging.

**Comment by RubenKelevra** [comment]
> 6159 bus tops in Germany with tagged `lit` - http://overpass-turbo.eu/s/11l5
> 
> So StreetComplete would not be inventing completely new tagging.

Thanks for checking!

I saw some bus stops tagged with this information, that's why I thought about having a quest for this in SC would be nice!

**Comment by matkoniecz** [comment]
>  Question asked: Is this bus stop well lit or has a light?

Note though that not so well lit and well lit both will be `lit=yes`

**Comment by RubenKelevra** [comment]
> > Question asked: Is this bus stop well lit or has a light?
> 
> Note though that not so well lit and well lit both will be `lit=yes`

I was referring with 'well lit' to street lamp coverage. Some bus stops are off the road enough to be in the dark in the night.

So we have to decide how to inform the user: Is a bus stop with a glass roof and a street lamp in the vicinity lit? Or is it only lit when there's a dedicated light in the bus stop?

I feel like the answer is always yes, when the bus stop is well illuminated, regardless where the light comes from.

**Comment by peternewman** [comment]
> So we have to decide how to inform the user: Is a bus stop with a glass roof and a street lamp in the vicinity lit? Or is it only lit when there's a dedicated light in the bus stop?
> 
> I feel like the answer is always yes, when the bus stop is well illuminated, regardless where the light comes from.

> At night you might feel a bit more comfortable waiting on a well lit bus stop, than in pitch darkness. So there's one possible usecase for the data.

IMHO the text that has been merged for this quest seems a bit ambiguous; "Is this bus stop lit?".

I think there are broadly six cases:
- Shelter with light - Clearly for a bus stop with a light, the answer is yes
- Shelter without light, but street lit - Possibly depends on shelter material, could be darker or lighter than street, possibly unusual
- Shelter without light, street not lit - Clearly no
- Just pole, with light - Clearly lit, not something I've seen (unless bus stop sign on streetlamp)
- Just pole, street lit - Probably, if street is well lit or light is near to stop
- Just pole, street not lit - Clearly no

Pedantically for the middle cases the bus stop itself isn't lit, but for pretty much any use case I can think of (apart from possibly if the bus stop has power, although it could have an electronic display but not a light), it probably still fits the criteria. What answer do we actually want for those ones though? I wonder if some form of hint words would help?

**Comment by andrewharvey** [comment]
When I started with SC I misunderstood the lit quests as "Does this feature have dedicated lighting?", but it was pointed out to me that this quest is simply is this area illuminated at night (even from spilt light from other features), which can be hard to answer, as how bright does it need to be considered lit? Just bright enough that I don't need a torch to walk on a moonless night?

So I agree that some extra quest hints that has more detail about how to answer the quest would be helpful and result in higher data quality.

**Comment by smichel17** [comment]
As an osm-layperson reading this, it seems like an upstream tagging proposal of `lit:dedicated` (or something to that effect, to distinguish from "incidentally lit by nearby lights") might be useful, though probably not _necessary_.

**Comment by peternewman** [comment]
> So I agree that some extra quest hints that has more detail about how to answer the quest would be helpful and result in higher data quality.

Any suggested wording then? @andrewharvey 

> though probably not _necessary_.

I think that's the reality. In reality a brightness measure of some sort (hugely vague and variable unless you have a lux meter) is likely to be far more relevant regarding whether someone feels safe (which seems to be the main reason for asking) than the method of lighting the area, e.g. a smoking shelter under a brightly lit factory may be far brighter than a single lamp in a bus stop in the middle of no-where, although it doesn't have dedicated lighting, and the surrounding area may feel much safer due to better lighting too.

**Comment by andrewharvey** [comment]
> Any suggested wording then? @andrewharvey

"Is this area bright enough to walk on a moonless night without a torch?" I don't know, I always find it hard to objectively answer, whereas does it have dedicated lighting much easier to answer objectively.

**Comment by smichel17** [comment]
> a brightness measure of some sort is likely to be far more relevant regarding whether someone feels safe

Hmm, I agree with this. I was thinking from the perspective of whether it is likely to *stay* lit. If it has dedicated lighting, then someone cares about that area staying lit, whereas incidental lighting may change — the factory closes or changes its working hours and now the sidewalk is no longer lit. I don't really care what happens, just sharing in case an outsider's perspective is useful; feel free to use or ignore it :)

**Comment by peternewman** [comment]
> > Any suggested wording then? @andrewharvey
> 
> "Is this area bright enough to walk on a moonless night without a torch?" I don't know, I always find it hard to objectively answer,

Yeah agreed.

> whereas does it have dedicated lighting much easier to answer objectively.

Also agreed, although it's unfortunately not how the tags currently fall.

> > a brightness measure of some sort is likely to be far more relevant regarding whether someone feels safe
> 
> Hmm, I agree with this. I was thinking from the perspective of whether it is likely to _stay_ lit. If it has dedicated lighting, then someone cares about that area staying lit, whereas incidental lighting may change — the factory closes or changes its working hours and now the sidewalk is no longer lit. I don't really care what happens, just sharing in case an outsider's perspective is useful; feel free to use or ignore it :)

Maybe my factory was a bit too contrived, although taking the more normal example of a glass bus stop under a street lamp, the level of lighting is likely to be similar and it's less incidental. Generally the council should maintain the lights, although the possible edge case is if they start turning them off late at night to save electricity (but then does the bus still run then...).

**Comment by endolith** [comment]
Yeah I just ended up hiding this quest because it's too ambiguously worded and I never know how to answer unless it has dedicated lights.
