### ISSUE TITLE
No links immediately after changing theme

### ISSUE THREAD

**Issue by goldfndr** [streetcomplete/StreetComplete#2384]
Immediately after I change theme, the links tab in My profile displays "You have no links yet" (which ought to have a period as it is a complete sentence) instead of the usual list of links.

**How to Reproduce**
1. Launch StreetComplete.
2. *navigation*, My profile, *links*
3. Observe list of links.
4. *back button*
5. *navigation*, Settings
6. Select theme - change to a different theme.
7. *back button*
8. *navigation*, My profile, *links*
9. Observe placeholder text.

There might be a bit of a dependency on how quickly step 8 is executed after step 7, or the particular theme from/to in step 6 (I was doing Auto [dark/night at the time] to Light and others). Repeating steps 7 and 8 after 9 does result in the expected list of links, so it is self-correcting.

**Versions affected**
v28.0-beta1 and v28.0-beta2

**Comment by matkoniecz** [comment]
I have seen such "nothing here" in numerous Andoid apps as temporary state on loading/restyling. Not sure is it avoidable.

**Comment by goldfndr** [comment]
I neglected to add that, when this happens, I can switch tabs (e.g. to/from statistics, achievements) and the links tab remains unpopulated.

**Comment by matkoniecz** [comment]
Oh, that is different. I though that it is just a flash of empty list.

**Comment by westnordost** [comment]
what is your android version?

**Comment by goldfndr** [comment]
Android 10 (security patch level is August 1, 2020) on an LG V50 (software V450P20f).

**Comment by westnordost** [comment]
Hm, I can't reproduce it. Also Android 10.

**Comment by westnordost** [comment]
By the way, @goldfndr, someone noticed in the chat (OSM slack) that the taginfo JSON is hopelessly outdated. Do you plan to maintain it in the future?

**Comment by westnordost** [comment]
Now I can reproduce it, sometimes. Android does sometimes not call the `onLayout` or `onPreDraw` listener. Even requesting a new layout pass in order to get the callback called does not seem to work (tested).
So, I fear this is a will not fix / cannot fix.
