### ISSUE TITLE
Upload existing photos instead of just taking photos when adding notes

### ISSUE THREAD

**Issue by RayBB** [streetcomplete/StreetComplete#2387]
Thanks for building this great app 👍  I've really enjoyed using it and contributing to OSM with it while exploring new places.

**Use case**
Right now, when I add a note there is only an option to add a photo via the camera. This is a nice feature and works well. However, often times I want to snap a picture or a few pictures as I walk down a street and then upload them at the end. Also, it would be nice to be able to edit the photo in my photos app to make sure I don't accidentally have someone's face in it and that the photo isn't blurry. 

**Proposed Solution**

Either:
1. Add a button for gallery to viewfinder
2. Add a gallery button next to the camera button

I've uploaded two examples of option 1 and one example of option 2.

<details>
  <summary>Large Screenshots</summary>
  
Instagram gallery in viewfinder: 
![image](https://user-images.githubusercontent.com/921217/102654218-46541900-4114-11eb-9e53-ebcb99057dc4.png)

Whatsapp gallery in viewfinder:
![image](https://user-images.githubusercontent.com/921217/102654247-53710800-4114-11eb-9e92-f41482d153aa.png)

Craigslist gallery button next to upload:
![image](https://user-images.githubusercontent.com/921217/102654282-6257ba80-4114-11eb-8006-4cfebfbf3fab.png)

  
</details>

**Comment by HolgerJeromin** [comment]
This is on purpose
https://github.com/streetcomplete/StreetComplete/issues/1567#issuecomment-531736725

**Comment by RayBB** [comment]
I see the auto of repo is concerned about copyright issues and sees this as a way of stopping.
While people could just take photos of a copyrighted things directly I suspect this is more to prevent the less savy user for being able to make the mistake on accident.
