### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#2388]
GitHub's [dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically), which automatically opens PRs when dependecies are updated, [now supports Gradle in Kotlin](https://github.blog/changelog/2020-12-18-dependabot-gradle-kotlin-and-composer-v2-support/). It also has support for updating GitHub Actions.

If you like, I can open a PR with the `dependabot.yml` configuration file.

**Comment by matkoniecz** [comment]
As far as I know, updating dependencies here requires manual testing (due to fact that many issues manifest in way hard to automatically test for).

So dependabot may be less useful than in for example something that has decent test coverage monitoring outputs that matter.

**Comment by FloEdelmann** [comment]
That's true, I didn't think about that. Dependabot might still be useful for notifying about updates, though. If that isn't necessary either, I'll close the issue.

**Comment by westnordost** [comment]
That's not necessary. Android Studio already does.
