### ISSUE TITLE
Automatically open keyboard for certain quests

### ISSUE THREAD

**Issue by RayBB** [streetcomplete/StreetComplete#2389]
**Use case**
I am adding a lot of house numbers to a neighborhood while walking around.
Right now the process is:
1. Tap Question
2. Tap the blue box to enter house number
3. Enter number
4. Tap enter on keyboard

I would like step 2 to be automated.

**Proposed Solution**
Automatically focus input to the text entry open keyboard for quests that require typed responses.

I can imagine some use case where this is disruptive to someone's flow. However, since the "other answers" option is still visible and keyboard entry is generally expected I think this would be a net win for most people in most cases. I certainly feel like it would be a good UX improvement.

We may need to do is come up with a list of quests where we want the keyboard to automatically show. 

PS: Yesterday I completed my 1000th quest! 🎉 https://old.reddit.com/r/openstreetmap/comments/kfgijk/1000_complete_on_streetcomplete/

**Comment by smichel17** [comment]
https://github.com/streetcomplete/StreetComplete/issues/2131#issuecomment-703248678

**Comment by RayBB** [comment]
womp, I tried searching for "keyboard" but somehow missed this answer.

Though I do wish that it was possible to have keyboard auto popup the incrementing numbers on the side is a pretty nice feature and I'll give it a shot.

**Comment by smichel17** [comment]
I found it by [searching "automatic open keyboard"](https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+automatic+open+keyboard). In fairness though, I wouldn't expect you to find that response since the keywords are not in the issue title; I knew what I was looking for :)

**Comment by smichel17** [comment]
And there's a handful of other issues about other specific quest types, like #1772
