### ISSUE TITLE
Extend list of buildings with conservatory

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#2390]
### General
This issue is a proposal to add another building type "conservatory" to the list of answers for "What kind of building is this?". Conservatories are common in residential areas, e.g. [Herrenchiemgaustraße 12 to 38](https://www.openstreetmap.org/#map=19/48.11406/11.60971) has some conservatories.

Affected tag(s) to be modified/added: [building](https://wiki.openstreetmap.org/wiki/Tag:building%3Dconservatory)
Question asked: **What kind of building is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**
The example picture could be: https://wiki.openstreetmap.org/wiki/File:Wintergarten_(Eingefahrener_Sonnenschutz)_(Anemometer).jpg
That one is from the wiki page https://wiki.openstreetmap.org/wiki/Tag:building%3Dconservatory

**Comment by matkoniecz** [comment]
Note that there is massive tail of rare building types and StreetComplete will never allow to tag all of them. 

Conservatory may be rare enough that leaving notes in case of encountering them may be acceptable.

**Comment by smichel17** [comment]
Maybe that quest should explicitly support leaving a note as part of the flow? As in, a "not listed" option at the bottom which opens a text box and leaves a note in the background; and SC should also not ask the quest for any node with a note like this attached.

**Comment by westnordost** [comment]
I've looked at the number of usages on taginfo and on the number of usages of other building types that are also not taggable with StreetComplete currently. conservatory is very far down that list.
