### ISSUE TITLE
Ask which specific shop is here (for shop=yes objects)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2391]
### General
Affected tag(s) to be modified/added: [shop](https://wiki.openstreetmap.org/wiki/Key:shop)
Question asked: **What kind of a shop is here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - obviously some rare shop types and ones not included in iD presets will require a note
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)  115 490 ( https://overpass-turbo.eu/s/11o2 )

### Ideas for implementation

**Element selection:**  `shop=yes and !amenity and !tourism and name`

**Metadata needed:** Already present presets for shop types

**Proposed GUI:** Reuse interface for quest about disused shops (so most of the work was done already)

**Comment by westnordost** [comment]
Thought about that too,  but i think for many shops tagged with shop=yes, it is really hard to say and in many cases,  there is no proper tag value for that. 

Am 21. Dezember 2020 13:03:57 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>### General>
>Affected tag(s) to be modified/added:
>[shop](https://wiki.openstreetmap.org/wiki/Key:shop)>
>Question asked: **What kind of a shop is here?**>
>>
>### Checklist>
>Checklist for quest suggestions (see guidelines):>
>- [x] 🚧 To be added tag is established and has a useful purpose>
>- [x] 🤔 Any answer the user can give must have an equivalent tagging
>(Quest should not reappear to other users when solved by one) -
>obviously some rare shop types and ones not included in iD presets will
>require a note>
>- [x] 🐿️ Easily answerable by everyone from the outside but a survey
>is necessary >
>- [x] 💤 Not an overwhelming percentage of elements have the same
>answer (No spam)>
>- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
>>
>>
>### Ideas for implementation>
>>
>**Element selection:**  `shop=yes and !amenity and !tourism and name`>
>>
>>
>**Metadata needed:** Already present presets for shop types>
>>
>>
>**Proposed GUI:** Reuse interface for quest about disused shops (so
>most of the work was done already)>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/streetcomplete/StreetComplete/issues/2391

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
How often this bad cases happen? It seems to me that it is rare enough that it should be OK.

>  it is really hard to say

In such case note with photo would be really useful. 

>  there is no proper tag value for that.

If such cases would be revealed then the iD preset (and maybe entire tagging scheme) needs a new value

**Comment by westnordost** [comment]
But there may be shops which simply cannot be defined further

**Comment by matkoniecz** [comment]
> But there may be shops which simply cannot be defined further

I have never encountered case of that. Do you have maybe some examples? Maybe it is possible to invent shop value for them... (in the worst case cases tagging like `shop=electronics;honey` is always possible)

**Comment by westnordost** [comment]
I don't have an example for that but I am pretty sure such shops exist and there should be somehow possible to treat these cases.

**Comment by matkoniecz** [comment]
In such case I would probably end proposing a new tag for that (not going to do this now, as I have no idea why shop would be not taggable more specifically than `shop=yes`)
