### ISSUE TITLE
Parking access might omit parking=street_side

### ISSUE THREAD

**Issue by jdhoek** [streetcomplete/StreetComplete#2408]
A new user added `access=yes` to a parking area mapped as `amenity=parking` with `parking=street_side` based on the parking access quest. This is not wrong of course, but for parking amenities tagged with `parking=street_side` the overwhelming majority is likely to be found at the sides of public access roads, and any conditions tagged on it are probably better done in bulk for all such parking areas in an area, along with any `parking:lane` tagging on the roads themselves. As the default access value already is `yes` for this kind of amenity, it is a bit redundant.

I would suggest removing `parking=street_side` from the parking access quest. The access-question makes a lot of sense for `parking=surface`, but may waste user's efforts for `parking=street_side`.

What do you think?

**Comment by matkoniecz** [comment]
> What do you think?

Makes sense to me, but I will wait a bit whatever someone has a good counterargument.

**Comment by matkoniecz** [comment]
If someone would be interested in making first PR - that is quite nice and simple to do.

**Comment by westnordost** [comment]
The code is here: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/parking_access/AddParkingAccess.kt
