### ISSUE TITLE
Cannot take photo for note

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2410]
A user reported that since v28.0, he cannot take a photo anymore.

Reproducible on Pixel3 XL and Pixel 4XL, both Android 11. Maybe it is an issue that occurs on Android 11 only.
Anyone here with an Android 11 device that can confirm it?

https://user-images.githubusercontent.com/4661658/103011119-ae9e6280-4539-11eb-8a14-ade489d48b78.mp4

**Comment by callis** [comment]
Yes, not working on pixel 2, on android 11. Nothing happens when pressing the blue camera icon

**Comment by tapetis** [comment]
This issue is probably related to the [package visibility changes](https://developer.android.com/about/versions/11/privacy/package-visibility) in Android 11, because the `packageManager.resolveActivity()` function is used when tapping the button.

**Comment by westnordost** [comment]
Thank you @tapetis
