### ISSUE TITLE
Street Name for Building: can't select name of path

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2411]
When entering the street name a building belongs to I can tap on a road to fill the name quickly, but when I tap on a (named) path, no name is pre-filled.
Could the option of selecting a path name be added?

**Comment by HolgerJeromin** [comment]
Can you show ussuch an example path?

**Comment by Helium314** [comment]
https://www.openstreetmap.org/way/243085211#map=18/48.21534/16.43939 (probably it was not exactly this segment)
I see it's actually tagged as cycleway, not path. Maybe any named way with highway=... should be selectable?

**Comment by matkoniecz** [comment]
Probably not all, `highway=proposed` that is not shown at all would be confusing, `highway=platform` would be useless and so on.

But adding `path`, `footway`, `cycleway` is likely reasonable if https://www.openstreetmap.org/way/337688913 has address based on nearby cycleway.

**Comment by matkoniecz** [comment]
Code: https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddAddressStreet.kt#L27 https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/data/meta/OsmTaggings.kt 

Seems that making and testing PR would be relative simple.

**Comment by Helium314** [comment]
Is this really the right place? I tried replacing `ALL_ROADS` with `ALL_PATHS`, but still can't select the cycleway (but can select a nearby road, which is a bit confusing)

**Comment by Helium314** [comment]
ok, invalidating the quest cache and re-scanning did the trick.
