### ISSUE TITLE
Answer option "is mapped separately" for question "Does this bus stop have a shelter?"

### ISSUE THREAD

**Issue by Nielkrokodil** [streetcomplete/StreetComplete#2412]
The app asks "does this bus stop have a shelter?" with answer options yes/no and "the whole stop is covered" (German gesamte Haltestelle ist überdacht). 
The wiki states, it is possible to map the shelter as an extra object. In this case, a "shelter=separate" tag should be added to the bus_stop node. https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop

Right now, the app doesn't give this answer option nor does it check if there is a shelter next to it. This will produce duplicate mapping in those cases where there is a separate shelter. This issue is also occurring on the bench-question on bus stops #1079. 

**Proposed Solution**

- (I dont know if this is possible) Check for shelters nearby or in the stop_area-relation and filter out those.
- Add answer option "is mapped separately"

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Talk:Key:shelter#shelter.3Dseparate https://wiki.openstreetmap.org/wiki/User_talk:M!dgard#shelter.3Dseparate (I think that shelter=separate is not needed, and not wanted).

It would be anyway impossible to support it in SC, as user is unable to check whatever there is mapped a separate `amenity=shelter`

> This issue is also occurring on the bench-question on bus stops

The same situation, and bench=separate has 22 uses worldwide https://taginfo.openstreetmap.org/keys/bench#values

**Comment by westnordost** [comment]
See @matkoniecz. If `shelter=seperate` should gain popularity, there is the option to not ask again every 4 years if `shelter=seperate` so to not destroy this data. However, currently it's not really in use at all.

**Comment by CaptainWilco** [comment]
https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element

**Comment by andrewharvey** [comment]
> https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element

Answering yes to the quest doesn't add another `amenity=shelter` feature it just adds `shelter=yes` to the bus stop, so you're adding an attribute of the bus stop not a second shelter. Therefore you're not breaking the one feature one OSM element guide because the bus stop feature is still only mapped as one OSM element, `amenity=shelter` not the `highway=bus_stop`.

**Comment by CaptainWilco** [comment]
So, you can add sidewalk=right/left/both to a highway with separate mapped sidewalk? I don't think so.

**Comment by CaptainWilco** [comment]
Oh sorry! Now I understand the wiki... You are right. My fault!

**Comment by CaptainWilco** [comment]
But https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform says:
>shelter 	yes / no 	If there is a shelter that is not tagged separately with amenity=shelter
