### ISSUE TITLE
Recycling Quest: Quest by color

### ISSUE THREAD

**Issue by flippipe** [streetcomplete/StreetComplete#2413]
### General
Affected tag(s) to be modified/added: [recycling](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling)

Nowadays, recycling quest ask for the materials. But would be easier if the quest was by color.

**Use case**
In my country, we have rules what can be deposit in the containers and containers have associated colors. Those rules, can be translated for a group of materials.

The Portuguese wiki already has that information in the respective [recycling](https://wiki.openstreetmap.org/wiki/Pt:Tag:amenity%3Drecycling) tag in Portugal and Brazil.

If not all countries have this kind of rules, a [google search](https://www.google.com/search?q=recycling+sorting+bins&tbm=isch) shows it is not uncommon also.

Another examples: [Germany](https://mademoisellein.de/german-garbage-disposal#Colour_is_the_Key), [Spain](https://www.trevorhuxham.com/2014/04/how-to-recycle-in-spain.html), [Japan](https://jpninfo.com/9826)

**Proposed Solution**
In countries or regions where those rules exists, be possible to indicate what residues the recycling facility accept by the color codes. This will help to add the proper tags to OSM improving information quality and also help the users of StreetComplete.

If in its own country, it is easier to select few colors that choose a lot of materials. If the user it is a foreigner country, do not need to know the recycling rules/system in that country to be able to add that information in StreetComplete.

**Comment by HolgerJeromin** [comment]
In Germany these waste bin colors are not the same in all regions.
residual waste can be in green or black bins.
Your link shows the same "Black or Grey Bins (Restmüll)" which makes the whole idea not useful at least in Germany.

**Comment by matkoniecz** [comment]
What worse, even with national standards some will have an unusual colors.

**Comment by Helium314** [comment]
I am not 100% sure, but I think it can even depend on regional waste management companies, so the regions do not have to reflect any political / federal states

**Comment by westnordost** [comment]
So, will not fix.
