### ISSUE TITLE
Fix maxspeed quest for Russia

### ISSUE THREAD

**Issue by literannn** [streetcomplete/StreetComplete#2415]
When solving maxspeed quest in Russian Federation, StreetComplete adds wrong tag (maxspeed:type=RU:urban/RU:rural instead of maxspeed=RU:urban/RU:rural). 

In Russia (and, as I know, in Romania) widely used maxspeed=RU:urban/RU:rural tags, look at:

https://wiki.openstreetmap.org/wiki/Key:maxspeed#Values
https://taginfo.openstreetmap.org/tags/maxspeed=RU%3Aurban
https://taginfo.openstreetmap.org/tags/maxspeed=RU%3Arural

these tags are supported by OsmAnd, MapsMe and converters

**Comment by westnordost** [comment]
This has been discussed before. I will not implement country-specific tagging schemas. OSM is a global map, it makes no sense to have different tagging schemese for the same things in different countries. 

> these tags are supported by OsmAnd, MapsMe and converters

And so are maxspeed:type=RU:urban and source:maxspeed=RU:urban I strongly assume.

**Comment by literannn** [comment]
OK, but maxspeed:type tag requires **maxspeed** tag too:
https://wiki.openstreetmap.org/wiki/Key:maxspeed:type

`maxspeed:type=* describes how a speed limit has been set into force. It should be accompanied by a maxspeed=* tag. `

add maxspeed=60/90 + maxspeed:type=RU:urban/RU:rural - it will be OK

**Comment by rhhsm** [comment]
> 
> 
> OK, but maxspeed:type tag requires **maxspeed** tag too:

I've been wondering about this too. It would be nice if SC adds this as well as the XX:urban/rural tag, but this would need the input of reliable speed limit data for all countries where SC could be used.

**Comment by literannn** [comment]
I don't understand, why we add _source_ tag without _main_ tag

**Comment by westnordost** [comment]
@rhhsm , @literannn 
> I don't understand, why we add source tag without main tag

See #457

Also see for as to why `maxspeed:type` and not `source:maxspeed` or other alternatives are used: 
https://github.com/streetcomplete/StreetComplete/issues/492#issuecomment-326080750

I'm closing this because nothing changed since then.

**Comment by PiRomant** [comment]
At least `maxspeed:type=RU:urban` must be dublicated as `maxspeed=RU:urban` since `maxspeed` remains blank now.
