### ISSUE TITLE
After undo, quest not shown again

### ISSUE THREAD

**Issue by Lotus815** [streetcomplete/StreetComplete#2418]
**How to Reproduce**
1. Answer quest
2. Undo last quest
3. Quest is not asked again; expected: quest is asked again immediately

**Versions affected**
v28.0

**Comment by westnordost** [comment]
This is the case for certain quests. Technical reasons. Feel free to comment here if this should happen independent of which quest type.
It is the case for at least these quest types:
![image](https://user-images.githubusercontent.com/4661658/103172814-7e670480-4856-11eb-885b-eaf299cb91e6.png)

**Comment by thefeiter** [comment]
It happened to me today for adding surface type and Adding if way is lit.

**Comment by westnordost** [comment]
Can you say which element exactly? I'd like to look at the history of that element.

**Comment by thefeiter** [comment]
Uhm, what do you mean by element?

**Comment by thefeiter** [comment]
Should be, `AddRoadSurface` and `AddWayLit`

**Comment by smichel17** [comment]
> Uhm, what do you mean by element?

Can you find the specific road where it happened? (on https://www.openstreetmap.org)

**Comment by thefeiter** [comment]
Buchenweg, Mackenzell, 36088 Hünfeld, Germany

**Comment by matkoniecz** [comment]
> Uhm, what do you mean by element?

Way, node or relation. For example https://www.openstreetmap.org/way/79704320


You can right-click on map and select second option from the bottom - https://wiki.openstreetmap.org/wiki/Query_features_tool

Or find it in edit history: https://www.openstreetmap.org/user/theFeiter/history#map=15/50.6592/9.7899

**Comment by westnordost** [comment]
According to the edit history, 
```
16:13:28 you added surface=asphalt
16:13:33 you added lit=yes
16:13:43 you reverted lit=yes
16:13:45 you reverted surface=asphalt
```

You do have auto-upload on or off?

**Comment by thefeiter** [comment]
Auto upload is on.

**Comment by thefeiter** [comment]
The edit history is correct, but the Task disappeared in the App. I wanted to choose a different surface.

**Comment by westnordost** [comment]
If you restart the app, does the quest pin appear then?

**Comment by thefeiter** [comment]
> If you restart the app, does the quest pin appear then?

No, it doesn't.

**Comment by thefeiter** [comment]
Invalidating the cache fixes it.

**Comment by westnordost** [comment]
Yes, this is no surprise.

So, it is not a display issue but an issue during the upload process. After an upload of one undo, the [diffResult](https://wiki.openstreetmap.org/wiki/API_v0.6#Response_9) is parsed and the (expectedly) one updated element is returned.
The [`OsmInChangesetsUploader`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/data/osm/upload/OsmInChangesetsUploader.kt#L32-L35) then calls for each updated element (usually it is just this one) `update` on the [`OsmElementUpdateController`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquest/OsmElementUpdateController.kt).

Since the upload itself worked, I think the issue must be somewhere in `OsmElementUpdateController` or in `OsmQuestGiver`. Unlikely but possible would also be that for some reason, the OSM API returns several updated elements even though just one updated element was uploaded, this could at least also trigger this issue.

**Comment by westnordost** [comment]
It would maybe be helpful to have the logs for when the upload happened. The app "LogCat Reader" from F-Droid could be used for that for example.

**Comment by thefeiter** [comment]
> It would maybe be helpful to have the logs for when the upload happened. The app "LogCat Reader" from F-Droid could be used for that for example.

Can you give me a small introduction to this process? 
After Start recording logcat, opening streetcomplete, repeating the upload-undo, saving logcat I only get:
```
<<< log_count = 5 >>>
[01-07 20:29:12.767 18224:18224 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[01-07 20:29:18.261 18224:18224 D/LogcatReader]
[Logcat] onActivityInBackground

[01-07 20:29:48.085 18224:18224 D/LogcatReader]
[Logcat] onActivityInForeground

[01-07 20:29:48.085 18224:18224 D/LogcatReader]
[Logcat] Posting pending logs

[01-07 20:29:48.106 18224:18224 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected
```

**Comment by thefeiter** [comment]
Logging via ADB should have worked.
[logcat_sc_trimmed.txt](https://github.com/streetcomplete/StreetComplete/files/5783646/logcat_sc_trimmed.txt)

**Comment by westnordost** [comment]
Nice, thank you and glad that worked! Is it possible to go back in time and see what was the log output at 16:13 today?

**Comment by thefeiter** [comment]
16:13 does not seem right, I am searching for the right timestamp...

**Comment by thefeiter** [comment]
Can't find a log from when it originally happened...

**Comment by westnordost** [comment]
@thefeiter sent me the full log via a private channel.

The relevant part I could find was

```
01-07 20:41:06.402 19338 19388 D OsmQuestUpload: Uploaded osm quest AddRoadSurface for way #79704320
01-07 20:41:09.852 19338 19388 D OsmQuestUpload: Uploaded osm quest AddWayLit for way #79704320
01-07 20:41:11.793 19338 19388 D UndoOsmQuestUpload: Uploaded undo osm quest AddWayLit for way #79704320
01-07 20:41:13.525 19338 19388 D UndoOsmQuestUpload: Uploaded undo osm quest AddRoadSurface for way #79704320
```

... but this was not from this afternoon but at around 9. Am I right to assume that this log is actually from later when you tried to reproduce the issue? (Were you successful?)

**Comment by thefeiter** [comment]
Correct, and I was able to fully reproduce.

**Comment by westnordost** [comment]
Oh, you were! Good! I think I will try to reproduce it on the same element with a debug version then

**Comment by westnordost** [comment]
Ok, found it! Thank you for your part!

**Comment by Lotus815** [comment]
Thanks for fixing!
