### ISSUE TITLE
Does <xy> still exists not uploaded for non-existent answer in offline mode

### ISSUE THREAD

**Issue by Lotus815** [streetcomplete/StreetComplete#2419]
**How to Reproduce**
1. Disable mobile data
2. Load quests with wifi connection
3. Disable wifi connection
4. Answer quest "Does <xy> still exists" with "no"
5. Enable wifi/data connection
6. Streetcomplete uploads quest answers
7. "Does <xy> still exists" with "no" is not uploaded and gets asked again; expected behaviour: gets uploaded and not asked again

**Versions affected**
v28.0

**Comment by westnordost** [comment]
Should not depend on the upload method. 

Need more information:
- you have an example element where it didn't work? Has that element been modified in the meantime? 
- always reproducible?

Am 27. Dezember 2020 12:32:51 MEZ schrieb Lotus815 <notifications@github.com>:
>
>**How to Reproduce**
>1. Disable mobile data
>2. Load quests with wifi connection
>3. Disable wifi connection
>4. Answer quest "Does <xy> still exists" with "no"
>5. Enable wifi/data connection
>6. Streetcomplete uploads quest answers
>7. "Does <xy> still exists" with "no" is not uploaded and gets asked
>again; expected behaviour: gets uploaded and not asked again
>
>**Versions affected**
>v28.0
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2419

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Lotus815** [comment]
Actually I can't find the upload method setting anymore in the app.

This is the changeset which was affected:
https://www.openstreetmap.org/changeset/96268887
Unfortunately the timestamp has no seconds, so it is not visible whether the deleted node has been deleted in the initial upload or in just the same minute manually again by myself.

**Comment by westnordost** [comment]
Menu -> Settings -> The first setting at the top

**Comment by westnordost** [comment]
So did you answer for two benches that they do not exist anymore? Or just for one but two times for that one because the first time, nothing seemed to change?

**Comment by Lotus815** [comment]
> Menu -> Settings -> The first setting at the top

"automatic upload" is set to "on"


> So did you answer for two benches that they do not exist anymore? Or just for one but two times for that one because the first time, nothing seemed to change?

I have answered not existing for only one bench in the above change set. After automatic upload, the quest appeared again and I answered again.
Maybe to be more precise: I loaded the quests of the target area at home in wifi, then I left home (no mobile data enabled), and once I was back home in wifi, the upload started. The small difference to my above initial description is, I have not disabled/enabled any data connection explicitly.

The issue may be reproduced faster by adding testdata with old check_date into the OSM database instead of searching for more non-existent objects.

**Comment by peternewman** [comment]
I do the vast majority of my uploads in offline mode, I'd imagine this one was, and I managed to delete some stuff (although all 28.0-beta1):
https://www.openstreetmap.org/node/731009778/history
https://www.openstreetmap.org/node/5278645365/history
https://www.openstreetmap.org/node/534993836/history
https://www.openstreetmap.org/node/2825375410/history

> So did you answer for two benches that they do not exist anymore? Or just for one but two times for that one because the first time, nothing seemed to change?

I've had things which appear to have prompted a few times in succession, but I can't tell if they're actually instances of #2354 or bugs in the SC not exist.

**Comment by westnordost** [comment]
I found the culprit.

What likely happened was that the changeset in which the app tried to upload the deletion was already closed. In that case, the OSM API returns the HTTP conflict error code. The app interpreted that as "oh, then this means the element changed, so I'll drop the user's answer".

**Comment by Lotus815** [comment]
> I found the culprit.

I have doubts. Maybe you found something else.

> What likely happened was that the changeset in which the app tried to upload the deletion was already closed.

https://www.openstreetmap.org/changeset/96268887

When you look in this changeset I have referenced above: it is opened 15:41 and closed 16:13. All changes in the changeset are made 15:41. The changeset can not have been closed at the time I was asked again for the quest.

**Comment by Lotus815** [comment]
Kindly re-open the issue. I have not found any option on my side.

**Comment by westnordost** [comment]
This is a misunderstanding. The changesets are closed and opened automatically by the app, there is not any option about this.
