### ISSUE TITLE
Delay for new quest after splitting way

### ISSUE THREAD

**Issue by Lotus815** [streetcomplete/StreetComplete#2420]
**How to Reproduce**
1. Answer quest with "different across way"
2. Split way
3. Quest for the split way is often shown with delay; expected bahaviour: quests are shown immediately after splitting the way

I think, the split is sometimes not uploaded immediately to OSM, which causes the problem.

**Versions affected**
v28.0

**Comment by westnordost** [comment]
Same as #2418
