### ISSUE TITLE
Quest "to which street does housenumber belong" not shown immediately

### ISSUE THREAD

**Issue by Lotus815** [streetcomplete/StreetComplete#2421]
**How to Reproduce**
1. Map house numbers
2. Be happy to have mapped all
3. Search for new quests
4. Quest "to which street does housenumber belong" is shown for many mapped houses; expected: quest is shown immediately after entering the house number.

Setting: default priority order (housenumber before street).

Maybe there is a maximum number of quest limit, which not shows the expected quest?

**Versions affected**
v28.0

**Comment by westnordost** [comment]
Same reason as #2418.

When download happened, the houses were not eligible for the street name quest because there was no address assigned to the house. After you uploaded your answers, the houses became eligible but you returned home already.
