### ISSUE TITLE
Delay reload quests for new area (initial GPS inaccurate)

### ISSUE THREAD

**Issue by Lotus815** [streetcomplete/StreetComplete#2422]
**Use case**
My phone often has a very inaccurate (up to kilometers) initial GPS position (maybe based on cell tower). Short time after, the actual position is reported.

Due to this, quests which are not near my actual area are frequently loaded. This is a problem in rural areas during mapping.

**Proposed Solution**
Check position accuracy before automatically loading quests
Ideas:
- Check if position is GPS based (if possible)
- Check for position accuracy (e.g. <200m)
- Reload quest for new area with delay (e.g. 2sec)

**Comment by westnordost** [comment]
I wouldn't want to add a delay.

However, checking the accuracy is perfectly possible. I'll add that if the accuracy is less than 68% confidence that the position is within a circle of 300m radius around the returned position, the position is rejected. The minimum size of a downloaded tile is roughly 300x300m
