### ISSUE TITLE
Do not retag highway=living_street into service roads if user selected "it is service road" in road name quest

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2431]
**How to Reproduce**

Have an unnamed `highway=living_street` fulfilling role of service road.

User will survey it, correctly answer that it has no name and that it acts as service road.

Expected: it remains tagged as `highway=living_street` but with `noname=yes`

What happens: retagged to `highway=service`

See https://www.openstreetmap.org/note/2476104#map=18/50.00878/19.94949

**Versions affected**

v25.1 (did this edit), applies also to current one

**Comment by westnordost** [comment]
Why should a living street not have a name?

**Comment by matkoniecz** [comment]
For example in my city some parts have no named streets but named neighborhoods.

Or driveway/access road is not considered as named but is signed as living street.

**Comment by westnordost** [comment]
ok

**Comment by DerDings** [comment]
I also know a lot of driveways which are signed as a living street by their owner. Since it is currently not possible to tag this way correctly as driveway and as a living street, the mapper has to decide which property is more important on that way. This decision should not be made by an application.

**Comment by westnordost** [comment]
> Since it is currently not possible to tag this way correctly as driveway and as a living street

By the way, yes it is possible:
```
highway=service
living_street=yes
```

https://wiki.openstreetmap.org/wiki/Key:living_street
