### ISSUE TITLE
No comma input

### ISSUE THREAD

**Issue by programmin1** [streetcomplete/StreetComplete#2433]
The asking for address quest doesn't have a comma input, just numbers. However looking at other-answers, for duplex/apartment etc. with multiple numbers on a building, it says to use commas. The input gives just numbers on the on screen keyboard however.

**How to Reproduce**
Tap any non address building for house number question.

**Versions affected**
v28 from FDroid.

**Comment by westnordost** [comment]
That's an issue of your keyboard, not of the app.
