### ISSUE TITLE
Surface: Add "concrete:plates" and "concrete:lanes" as answer options

### ISSUE THREAD

**Issue by aikencz** [streetcomplete/StreetComplete#2437]
**Use case**
Many roads, footpaths etc. have concrete surfaces consisting of full-width or lane plates. Currently, it isn't possible to choose these options.

**Proposed Solution**
Please add `concrete:plates` and `concrete:lanes` to the answer option set.

**Comment by HolgerJeromin** [comment]
https://taginfo.openstreetmap.org/keys/surface#values

Place 17 of the values for this tag.

**Comment by Helium314** [comment]
Judging from @HolgerJeromin's link it's used more often than other available options like unhewn_cobblestone, grass_paver, metal
But I guess the answer from #481 still applies.

**Comment by RubenKelevra** [comment]
Would be nice to have this options.

Currently we're forced to either create a not for each way or tag the not-so-fitting 'paving_stones'.

Concrete on the other hand isn't fitting either, since it's not one large surface, but large plates either creating a surface or track-lanes.

**Comment by aikencz** [comment]
I use `concrete:plates` very often - much more than e.g. rock, metal or wood.

**Comment by matkoniecz** [comment]
Personally I consider `concrete:plates` so different that I am not answering `concrete` for them in SC, but switching to Vespucci.

But maybe it is regional weirdness as in Poland it is used on tracks and it is normal to have noticeable misalignment between plates - making them irritating for anything except heavy machinery.

**Comment by kauevestena** [comment]
Also, concrete:plates is very common in Brazil, please add!

**Comment by FloEdelmann** [comment]
The hardest challenge will be finding good pictures that make the difference clear between `concrete`, `concrete:plates` and `paving_stones`. Maybe the current `concrete` surface picture will need to be changed.

For reference, our current images:

<table>
<tr>
	<td><code>concrete</code>
	<td><code>paving_stones</code>
<tr>
	<td><img src="https://raw.githubusercontent.com/streetcomplete/StreetComplete/v35.0/app/src/main/res/drawable-xxhdpi/surface_concrete.jpg" width="200">
	<td><img src="https://raw.githubusercontent.com/streetcomplete/StreetComplete/v35.0/app/src/main/res/drawable-xxhdpi/surface_paving_stones.jpg" width="200">
</table>

### Photo suggestions

Note that photos will need to be cropped to square and maybe color-adjusted:

<table>
<tr>
	<th>Surface
	<th width="226">Thumbnail
	<th>Source, license
	<th>Resolution
	<th>Notes
<tr>
	<td><code>concrete:lanes</code>
	<td><img src="https://wiki.openstreetmap.org/w/images/thumb/7/7e/Concrete_lanes.png/522px-Concrete_lanes.png" width="200">
	<td><a href="https://wiki.openstreetmap.org/wiki/File:Concrete_lanes.png">OSM Wiki</a><br>CC-BY-SA 2.0 :heavy_check_mark: 
	<td>579×665 :x:
	<td>left side is cut off
<tr>
	<td><code>concrete:lanes</code>
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/%D0%91%D0%B5%D1%82%D0%BE%D0%BD%D0%BD%D0%B0_%D0%B2%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE%D0%B2%D0%B0_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%BD%D0%B0_%D0%9F%D0%BE%D0%BB%D0%BE%D0%BD%D0%B8%D0%BD%D1%83_%D0%A0%D1%83%D0%BD%D1%83.jpg/800px-%D0%91%D0%B5%D1%82%D0%BE%D0%BD%D0%BD%D0%B0_%D0%B2%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE%D0%B2%D0%B0_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%BD%D0%B0_%D0%9F%D0%BE%D0%BB%D0%BE%D0%BD%D0%B8%D0%BD%D1%83_%D0%A0%D1%83%D0%BD%D1%83.jpg" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:%D0%91%D0%B5%D1%82%D0%BE%D0%BD%D0%BD%D0%B0_%D0%B2%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE%D0%B2%D0%B0_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%BD%D0%B0_%D0%9F%D0%BE%D0%BB%D0%BE%D0%BD%D0%B8%D0%BD%D1%83_%D0%A0%D1%83%D0%BD%D1%83.jpg">Wikimedia Commons</a><br>CC-BY-SA 4.0 :heavy_check_mark: 
	<td>3264×2448 :heavy_check_mark: 
	<td>good candidate
<tr>
	<td><code>concrete:lanes</code>
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Fitzroy_Island_concrete_pathway.jpg/800px-Fitzroy_Island_concrete_pathway.jpg" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:Fitzroy_Island_concrete_pathway.jpg">Wikimedia Commons</a><br>CC-BY-SA 4.0 :heavy_check_mark: 
	<td>3840×2160 :heavy_check_mark: 
	<td>sand has low contrast to concrete, needs color adjusting
<tr>
	<td><code>concrete:plates</code>
	<td><img src="https://wiki.openstreetmap.org/w/images/e/ed/Dscf0222_600.jpg" width="200">
	<td><a href="https://wiki.openstreetmap.org/wiki/File:Dscf0222_600.jpg">OSM Wiki</a><br>no license :x:
	<td>600×450 :x:
	<td>
<tr>
	<td><code>concrete</code> (or <br><code>concrete:plates</code>?)
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/2014-08-29_15_33_15_View_across_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG/800px-2014-08-29_15_33_15_View_across_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:2014-08-29_15_33_15_View_across_Stuyvesant_Avenue_in_Ewing,_New_Jersey,_with_concrete_pavement_likely_dating_to_the_1950s.JPG">Wikimedia Commons</a><br>CC-BY-SA 4.0 :heavy_check_mark: 
	<td>3264×2448 :heavy_check_mark: 
	<td>
<tr>
	<td><code>concrete</code> (or <br><code>concrete:plates</code>?)
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/2014-08-29_15_33_50_Closeup_of_pavement_along_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG/800px-2014-08-29_15_33_50_Closeup_of_pavement_along_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:2014-08-29_15_33_50_Closeup_of_pavement_along_Stuyvesant_Avenue_in_Ewing,_New_Jersey,_with_concrete_pavement_likely_dating_to_the_1950s.JPG">Wikimedia Commons</a><br>CC-BY-SA 4.0 :heavy_check_mark: 
	<td>3264×2448 :heavy_check_mark: 
	<td>
<tr>
	<td><code>concrete</code>
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Concrete_access_road_to_Melchetcourt_Farm_-_geograph.org.uk_-_738978.jpg/400px-Concrete_access_road_to_Melchetcourt_Farm_-_geograph.org.uk_-_738978.jpg" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:Concrete_access_road_to_Melchetcourt_Farm_-_geograph.org.uk_-_738978.jpg">Wikimedia Commons</a><br>CC-BY-SA 2.0 :heavy_check_mark: 
	<td>427×640 :x:
	<td>
<tr>
	<td><code>concrete</code>
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Concrete_road_passing_Lovell%27s_Farm_-_geograph.org.uk_-_2299363.jpg/800px-Concrete_road_passing_Lovell%27s_Farm_-_geograph.org.uk_-_2299363.jpg" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:Concrete_road_passing_Lovell%27s_Farm_-_geograph.org.uk_-_2299363.jpg">Wikimedia Commons</a><br>CC-BY-SA 2.0 :heavy_check_mark: 
	<td>4000×3000 :heavy_check_mark: 
	<td>
<tr>
	<td><code>concrete</code>
	<td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/2014-08-29_15_31_39_View_southeast_along_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG/800px-2014-08-29_15_31_39_View_southeast_along_Stuyvesant_Avenue_in_Ewing%2C_New_Jersey%2C_with_concrete_pavement_likely_dating_to_the_1950s.JPG" width="200">
	<td><a href="https://commons.wikimedia.org/wiki/File:2014-08-29_15_31_39_View_southeast_along_Stuyvesant_Avenue_in_Ewing,_New_Jersey,_with_concrete_pavement_likely_dating_to_the_1950s.JPG">Wikimedia Commons</a><br>CC-BY-SA 4.0 :heavy_check_mark: 
	<td>3264×2448 :heavy_check_mark: 
	<td>shadow is distracting
</table>

I didn't find any good pictures for `concrete:plates`. Maybe someone of you (@aikencz, @RubenKelevra, @matkoniecz, @kauevestena) can take a good photo and release it here?

**Comment by matkoniecz** [comment]
427×640 one seems good for concrete:plates, even if after cropping it would be a relatively poor resolution

https://www.geograph.org.uk/photo/3131358 may be fitting

**Comment by westnordost** [comment]
Note that new images should fit to other images, i.e. show only the surface, not the surroundings. The final crop must be at least 360x360.

**Comment by aikencz** [comment]
Could we utilize the images from the OSM documentation (https://wiki.openstreetmap.org/wiki/Key:surface)?


>Note that new images should fit to other images, i.e. show only the surface, not the surroundings. The final crop must be at least 360x360.
>

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/File:Dscf0222_600.jpg is listed above, has no license, has low resolution (but passable), has some distracting shade (but passable)

Or is there some other image for this surface type?

**Comment by westnordost** [comment]
"Concrete without full cover"?
