### ISSUE TITLE
Allow to specify "day before holiday" in opening hours

### ISSUE THREAD

**Issue by vnmabus** [streetcomplete/StreetComplete#2440]
In some places is common to have different closing hours the day before a holiday. It seems that the syntax used for specifying dates in OSM allows one to use "PH - 1 day" for this case (it is more general than that, but I think that this case is enough). Could this option be allowed when selecting days for opening hours?

**Comment by westnordost** [comment]
Certainly there are some instances of this, but I think it is a too low count to warrant the effort for an implementation for that.
According to taginfo, this notation is used only 15 times worldwide.

See also https://github.com/streetcomplete/StreetComplete/pull/2045#issuecomment-678838772

**Comment by matkoniecz** [comment]
So, you should leave note with a photo of opening hours notes - or add it directly with a Vespucci that supports even far more insane opening hours rules (at cost of more complex input interface).
