### ISSUE TITLE
"Does this still exist?" cannot be undone

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#2441]
If you delete an object by answering "no" to the "Does this still exist", you cannot undo this with the undo button

**How to Reproduce**

1. Find a "Does this still exist" quest (I tried with a bench)
2. Answer "no" 
3. Hit the undo button
You are asked to undo the previous quest, not the "Does this still exist" quest.

**Versions affected**

StreetComplete 28.1
Android 9

**Comment by westnordost** [comment]
This is a correct, it cannot be undone. It's not a bug.

**Comment by Atrate** [comment]
It might be worth considering making it undoable, as this is a potentially very destructive action

**Comment by westnordost** [comment]
Very well, but this is not a bug.

Also, no idea how to revert a deletion. There is no API endpoint for that.

**Comment by DerDings** [comment]
I sometimes restore old objects using 
a [python script] (https://github.com/Zverik/simple-revert/blob/master/restore_version.py), which worked well for me. But I don't know how it works technically.



Maybe StreetComplete should only add lifecycle prefixes rather than fully deleting objects. This allows other users to see more easily what a StreetComplete user did, and to maybe correct something.

**Comment by matkoniecz** [comment]
> Also, no idea how to revert a deletion. There is no API endpoint for that.

Creating new node with the same tags and position should be fine, though history would be lost. Though looking at https://www.openstreetmap.org/node/1/history - it seems to be possible.

**Comment by westnordost** [comment]
Ok, but how?

**Comment by westnordost** [comment]
If it retains the id, it's better cause the history is not lost.

**Comment by mnalis** [comment]
> Maybe StreetComplete should only add lifecycle prefixes rather than fully deleting objects. This allows other users to see more easily what a StreetComplete user did, and to maybe correct something.

+1 for [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) instead of deleting

**Comment by westnordost** [comment]
There is no lifecycle prefix for "doesn't exist anymore". Also wouldn't make sense.

**Comment by matkoniecz** [comment]
removed:, demolished:, razed: are used for things utterly gone (and apparently also for things mostly gone).

But yes, shop that is fully gone should be deleted, not retagged.

**Comment by DerDings** [comment]
> 
> 
> If it retains the id, it's better cause the history is not lost.

The script I have linked above does retain the id, and thus the history. That was the only reason for me using this instead of just copying the tags from the history of the deleted object.

**Comment by mnalis** [comment]
> removed:, demolished:, razed: are used for things utterly gone (and apparently also for things mostly gone).

Yes, especially [removed:](https://wiki.openstreetmap.org/wiki/Key:removed:) sounds versatile.

Problem is that deleted nodes lose all history, and are **hard to find and fix**, even if problem is noticed in relatively short time by accident (which is the about the way you can easily find them - like "hmmm I'm pretty sure I mapped this before and now it's not there"). If lifecycle prefix is used instead, problems are _much_ easier to spot, and more advanced mapper can easily decide on desktop if the node is to be deleted altogether,  resurveyed, repurposed, or something else needs to be done. Also, experienced mapper can easily periodically run overpass checks for lifecycle prefix and take care of them in their area of interest.

> But yes, shop that is fully gone should be deleted, not retagged.

But it depends what is meant by "fully gone", doesn't it? shop=vacant, waiting someone else to rent space? In abandoned state requiring serious repairs / rebuilding to be usable? Repurposed for something else (like shop in ground floor of apartment building becoming living space)? Whole building razed to the ground? Whole building razed to the ground _and_ something else built there?

While @DerDings tool repurposed in SC to restore node with same id might help if the mapper which deleted by accident realizes that in a very short time and undoes it, it is still remedy for only part of the problem - there are a lots of cases where person that originally deletes the node does not immediately (or ever) realize they did not want to do that. Using lifecycle prefix instead of deleting nodes/ways takes care of that.

**Comment by Lukas458** [comment]
I would be fine with lifecycle prefixes in most of the cases, too. There's also the thing that for example some amenity=telephone ones, which were last edited 10 years ago or something, are not so precisely in their position and maybe an SC user is asked whether the telephone is there, the user doesn't see it and deletes it, but when he/she walks a few meters more then a telephone comes up and maybe this one was meant with the osm node. But for sure I know, that's not an SC issue.

But so, some elments might still exist but are hard to find.

I can imagine also one other issue, I don't know what SC does when a telephone is not on the aboveground, but in the underground for example, see https://www.openstreetmap.org/node/8142359335
I don't know whether level=* is supported, so maybe a user is asked about it's existence standing on the ground level and so he/she cannot see the object, but I'm not sure about this.

**Comment by westnordost** [comment]
As far as I know, especially lifecycle prefixes such as `removed:` or `demolished:` are frowned upon. OpenStreetMap data should reflect what is there now on the ground, so nothing planned or already removed should be added.
If an object is deleted, the history is not lost, only hard to access / find out. This is a problem of the API then and I think a client using the OSM API should use the OSM API as it is intended - i.e. delete things that are gone.

> But it depends what is meant by "fully gone", doesn't it? shop=vacant, waiting someone else to rent space?

Shop nodes are not deleted.

---

I'd like to remind everyone that the app shows the following warning every time the user selects that a thing does not exist anymore:

> **Warning: This cannot be undone!**
>
> Are you sure that it does not exist, not even at 
> a slightly different location? When in doubt, 
> better leave a note instead.
>
> [Leave Note]    [It does not exist]

**Comment by rhhsm** [comment]
A side remark: once I went to survey a car park quest, but only saw a nice grass field with a few benches instead. So I made a note that there's no car park there, and back home deleted it using iD. The next week, I passed that location on the other side, and saw the entrance to the _underground_ car park... so it would be nice if in car park quests, it would be clear if it's about an above-ground or underground car park.... :)

**Comment by Lukas458** [comment]
Yeah. It's a similar thing I think for every vending_machine, telephone or something where it is asked after, which has the tag level≠0, indoor=yes or location=underground. Maybe something has to be implemented that in these cases there is taken special care.

**Comment by matkoniecz** [comment]
> maybe a note within the question or something

Definitely supported for location=underground. Maybe also for other things you mention.

**Comment by lightonflux** [comment]
Just an idea: Other software like the file manager nautilus or gmail just delay a potentially harmful action by a few seconds or minutes.

So if there was a deletion, couldn't SC just hold the change it in a persistent cache (in case the app is closed) and then submit the deletion to the api after 2 minutes or so. 

Of course this would only be helpful in situations where a user doesn't see e.g. a post box behind a tree (maybe bc the poi wasn't at the correct location), deletes it prematurely and then wants to revert it.

**Comment by westnordost** [comment]
If someone wants to help getting this implemented, you could do that by reading and understanding the python script mentioned and explain what is the method to revert a deletion.

**Comment by JeanFred** [comment]
Coming here because, of course, I was out surveying the other day, got confused at an intersection, and mistakenly marked a phone booth as non-existent ^_^"

I understand the rationale that OSM deletions are not undoable (or at least not easily). But as far as I can tell, my mistaken deletion has not been propagated to OSM yet − it only exists locally on my phone. Maybe my case is a bit special because I only ever sync back home on WiFi (and most of the time while surveying I don’t even have mobile data on) − I have actually avoided uploaded my changes since then to avoid the mistake propagating.

So while I understand that the app offers the same undo options for local changes and uploaded changes (but behaves differently under the hood), it does feel "wrong" to not be able to undo a local change.

**Comment by Helium314** [comment]
@JeanFred 
In your case you could modify the phone booth in some other editor and then try uploading. If an element was changed since it was downloaded to StreetComplete, your edit/deletion should be discarded as far as I know.

**Comment by FloEdelmann** [comment]
The [python script](https://github.com/Zverik/simple-revert/blob/master/restore_version.py) mentioned by @DerDings does the following (simplified for StreetComplete's "undo" case):

1. [Download object history](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L86-L101), e.g. https://api.openstreetmap.org/api/0.6/node/917249225/history
	- The API response might be too large, [then it fails](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L94-L101).
2. Check if the to be restored version number [is in bounds](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L115-L124), i.e. `> 0` and `< last_version`.
3. Assign the to be restored version [to `vref` variable](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L115-L124).

Steps 1 to 3 can be simplified by just querying the to be restored version from the API, e.g. https://api.openstreetmap.org/api/0.6/node/917249225/2

4. [Set `vref.version` to `last_version`](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L140-L142) (e.g. 3 in the example) and add it to changes to be uploaded.
5. [Find refs](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/restore_version.py#L143-L172) in to be restored object (if it is a way (`<nd>`) or relation (`<member>`), so this can be skipped in StreetComplete).
6. [Open a changeset](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/common.py#L182-L188).
7. [Create an OSM change XML](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/common.py#L128-L160), with the sorted changes.
8. [Upload the change XML](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/common.py#L191-L222) to the changeset.
9. [Close the changeset](https://github.com/Zverik/simple-revert/blob/c6d181047ff723cfacef65ccd66ff6c5887520b3/common.py#L224-L229).

**Comment by FloEdelmann** [comment]
So for StreetComplete's case, this boils down to the following:

Assuming a node with ID `OBJECT_ID` with `NUMBER` versions. The `CheckExistence` quest deletes that node, adding version `NUMBER+1` where `visibility=false`. Now we want to undo that.

E.g. `OBJECT_ID=917249225`, `NUMBER=2` (same example as above)

1. Get to be restored version's `<node>` from API:
	`https://api.openstreetmap.org/api/0.6/node/OBJECT_ID/NUMBER`
	e.g. https://api.openstreetmap.org/api/0.6/node/917249225/2
2. Set `version` attribute of that `<node>` to `NUMBER+1`
3. Open a changeset.
4. Create and upload a OSM change XML like this:
	```xml
	<osmChange version="0.6">
	  <action>
	    <node changeset="CHANGESET_ID" version="NUMBER+1" visibility="true"> <!-- plus other attributes from step 1 -->
	      <!-- tags from step 1 -->
	    </node>
	  </action>
	</osmChange>
	```
5. Close the changeset.

**Comment by westnordost** [comment]
Thank you for your research!

StreetComplete does not record the version number at which an element was deleted. So probably the revert must find out that version by itself. I understand that the OSM element to be uploaded in the osmChange with visibility=true must have the same version number as the deleted version(?)

**Comment by FloEdelmann** [comment]
> I understand that the OSM element to be uploaded in the osmChange with visibility=true must have the same version number as the deleted version(?)

Yes, that surprised me, too.

I've found an object where this exact script was used to revert a StreetComplete existence quest answer: https://www.openstreetmap.org/node/436172390/history

* Version 3 deletes the node (via StreetComplete)
* Version 4 restores the node (via restore-version.py)

The [OSM change XML of version 4 which you can download](https://www.openstreetmap.org/api/0.6/changeset/96458185/download) has `version="4"` though. Maybe that's changed by the OSM API and it doesn't actually matter when uploading?

**Comment by westnordost** [comment]
Yeah, maybe

**Comment by matkoniecz** [comment]
@FloEdelmann Thanks!

Warning: below I speculation, I need to test it on a test server.

As I understand  `<modify>` it simply replaces whatever data OSM object currently has with new one:

So I could upload osmchange with https://www.openstreetmap.org/node/436172390/history in version 6 and whatever contents I would push would replace current one.

And, to be more specific, if one would upload osmchange assigning location/tags to deleted node it would get resurrected.

More specifically if node 436172390 existed in version 2, was deleted in version 3, then deleting tags/position from version 2 as version 4 will undo deletion.

As there is no special support for undeletion one must use script to obtain old state (easy for deleted nodes, tricky for relations containing other objects or other more complex cases).

```
<?xml version="1.0" encoding="UTF-8"?>
<osmChange (snip) >
 <modify>
  <node id="436172390" visible="true" version="4" changeset="96458185" timestamp="2020-12-26T16:25:56Z" user="okwithmydecay" uid="10370720" lat="51.5504334" lon="-0.1025027">
   <tag k="amenity" v="telephone"/>
   <tag k="booth" v="KX100"/>
   <tag k="covered" v="booth"/>
  </node>
 </modify>
</osmChange>
```

This seems to match a bit cryptic https://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id

Note that https://wiki.openstreetmap.org/wiki/Manually_undelete_node is very close to that expect "Do not increment the version= number"

**Comment by FloEdelmann** [comment]
From https://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id:

> A version number must be provided as well, it must match the current version of the element in the database.

Apparently, that's always the case, not only for restoring deleted objects.

**Comment by riQQ** [comment]
Pretty sure this is to detect if in the meantime someone else changed the object you're uploading.

**Comment by andrewharvey** [comment]
> As far as I know, especially lifecycle prefixes such as removed: or demolished: are frowned upon. OpenStreetMap data should reflect what is there now on the ground, so nothing planned or already removed should be added.

Maybe by some, but not by everyone. removed: demolished: are more like the note= tag, it's there for other editors. eg. if the building is still visible on imagery, then leaving it's outline there but with removed: informs other armchair mappers not to re-map the building.

**Comment by westnordost** [comment]
Ok turns out that undeletion (at least of nodes) is really easy: Just upload the deleted element as "modified", using the same version as the deleted version. Implemented and tested now in the dev branch.
