### ISSUE TITLE
shoulder

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2444]
### General
Affected tag(s) to be modified/added: [shoulder](https://wiki.openstreetmap.org/wiki/Key:shoulder)
Question asked: Is there a shoulder on this road?

- Yes on both sides
- Only on left side
- Only on right side
- Differs along the way

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose

Established, and useful for cyclists and cycle planning.

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary

The only issue here is that the wiki says a shoulder should be wide enough for a vehicle, although to me a shoulder only wide enough for a bicycle but not a car is still a shoulder. So this might make it hard to do a quest before this is resolved on the tag documentation.

- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)

Maybe depends on the region and classification of the road, but it's certainly not something that you can usually guess a default.

- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Yes any highway=* which applies to motor vehicles.

**Comment by westnordost** [comment]
Roads within built-up areas usually have no shoulders right?

**Comment by andrewharvey** [comment]
> Roads within built-up areas usually have no shoulders right?

Probably around the same occurrence as cycleways. We ask for cycleways even though a very high proportion of answers are no so figured may as well ask for shoulders too.

**Comment by peternewman** [comment]
This probably varies by country and highway class.

E.g. in the UK only motorways and a few bits of A road have it:
https://en.wikipedia.org/wiki/Shoulder_(road)#United_Kingdom

Whereas cycleways are very common in residential areas. I'm guessing this is a population density thing @andrewharvey as you seem to be based in Australia.

Also this tag doesn't seem to cope with dynamic hard shoulders as used on UK "smart" motorways:
https://en.wikipedia.org/wiki/Smart_motorway#Dynamic_hard_shoulder

**Comment by matkoniecz** [comment]
> Yes any highway=* which applies to motor vehicles.

Definitely not all, skipping `highway=service`, `highway=pedestrian`, `highway=track` is definitely needed. Maybe also `highway=residential`, roads with unpaved surfaces, roads with low max speed, `highway=living_street` and some other.

**Comment by westnordost** [comment]
Well I was thinking, maybe only ask this for roads in the countryside. Using a fuzzy filter like:
- only ask for bigger roads (tertiary and up maybe)
- only ask if there is no sidewalk
- only ask if it is not lit
- if the speed limit (if given?) is above 50 km/h or maxspeed:type contains "rural" (or not contains urban/zone)

**Comment by matkoniecz** [comment]
> only ask if it is not lit

Maybe Poland is unique here but there are often stretches of lit road also in the countryside (for example at more complex motorway/expressway intersections)

**Comment by peternewman** [comment]
> > only ask if it is not lit
> 
> Maybe Poland is unique here but there are often stretches of lit road also in the countryside (for example at more complex motorway/expressway intersections)

This is true for the UK too, most Motorways are still lit (although they aren't bothering to replace the lighitng on others), but they'll nearly all have hard shoulders.

**Comment by andrewharvey** [comment]
> Definitely not all, skipping highway=service, highway=pedestrian, highway=track is definitely needed. Maybe also highway=residential, roads with unpaved surfaces, roads with low max speed, highway=living_street and some other.
> 
> Well I was thinking, maybe only ask this for roads in the countryside. Using a fuzzy filter like:

I think it's fine to start with a narrow focus. There will always be exceptions so any rules will miss out some features, but I think that's okay at the start.

> only ask for bigger roads (tertiary and up maybe)

Agreed that bigger tertiary and up roads is good rather than flood residential roads with this quest.

> only ask if there is no sidewalk

I can give plenty of examples where there is a sidewalk and a shoulder, at least from my experience that's not a good indicator.

> only ask if it is not lit

Again I'm not sure if this is a useful indicator.

> if the speed limit (if given?) is above 50 km/h or maxspeed:type contains "rural" (or not contains urban/zone)

This would work, but I think highway classification would be a much stronger indicator than maxspeed.

Many maxspeed's were entered not through StreetComplete so will be lacking the maxspeed:type tag, again from my experience this tag is just not present enough to be an indicator (and as far as I know, SC won't ask to complete this tag for a pre-existing maxspeed tag).

**Comment by westnordost** [comment]
I also asked about it in the German forum: https://forum.openstreetmap.org/viewtopic.php?id=71597

So far the idea is to ask it for `highway=trunk` and for rural roads. Best way to find rural roads would be to look at roads with maxspeed > 60 or maxspeed:type/source:maxspeed/maxspeed/zone:traffic/... does not contain "zone" or "urban".

Furthermore, it was brought up that cycleways and parking lanes are also a special type of shoulder (in German at least), so one must be cautious how to word the question.

**Comment by andrewharvey** [comment]
I agree that there are some intricacies. In the community here we'll often debate if something is a shoulder which is signposted for use by bicycles, or if it's a wide cycle lane.

Usually a shoulder as an emergency stopping lane wouldn't allow parking, and if parking was allowed usually I'd tag that as a parking:lane instead, but I won't go as so far to say this should be the blanket rule.

I'd also ask it for highway=motorway, especially motorway tunnels or bridges might not have a shoulder and an explicit shoulder=no then becomes very useful.

The OSM wiki also seems to indicate use on a hard shoulder only, so I think the tag remains unclear if a soft shoulder can be mapped as a shoulder with unpaved surface. Or if we need a new soft shoulder tag.

I'm fine if you decide that the tag needs further development or it's not ready for a SC quest yet.

**Comment by westnordost** [comment]
Hm maybe wait. But on the other hand, just waiting will usually change nothing, best to try to actively resolve such uncertainties as early as possible. If you have an interest in that, maybe you'd like to find the details and/or write a proposal about it.

**Comment by matkoniecz** [comment]
See https://lists.openstreetmap.org/pipermail/tagging/2021-January/thread.html#58857 thread - shoulder tagging turns out to be far more useful and important that I expected

**Comment by Lee-Carre** [comment]
> Maybe Poland is unique here but there are often stretches of lit road also in the countryside

Not just Poland; same in Jersey, too. Though, the distinction between urban and rural is much less clear, here, being small.

**Comment by peternewman** [comment]
Thanks for this @westnordost .

> Also this tag doesn't seem to cope with dynamic hard shoulders as used on UK "smart" motorways: https://en.wikipedia.org/wiki/Smart_motorway#Dynamic_hard_shoulder

I'm still unclear how we're supposed to tag the bits of smart motorway in the UK though; the wiki says:
> A shoulder, often serving as an emergency stopping lane, is a reserved lane by the verge of a road or motorway

The quest question says:
https://github.com/streetcomplete/StreetComplete/blob/6a5297ff2bc289256f4e7191771c39d5dde2d0dc/app/src/main/res/values/strings.xml#L1134

From the wiki I'd probably say no, as it's not reserved; from the question probably yes, as it can have one.

This page on the wiki confirms my wiki interpretation is the preferred option:
https://wiki.openstreetmap.org/wiki/Roads_in_the_United_Kingdom#Additional_Highway_Tags_for_the_United_Kingdom

I wonder if the question should be tweaked to be this or similar:
Does this road have a shoulder (a reserved lane)?

**Comment by westnordost** [comment]
> I'm still unclear how we're supposed to tag the bits of smart motorway in the UK though; the wiki says:

Doesn't matter. It is not asked for motorways.

**Comment by peternewman** [comment]
> Doesn't matter. It is not asked for motorways.

Oops, I'd missed that bit. Although is that not worth asking (in the UK at least), given that particular feature?

**Comment by westnordost** [comment]
StreetComplete doesn't ask anything for motorways

**Comment by peternewman** [comment]
Ah, well not intentionally, although I, and this other random user, have certainly answered questions about emergency phones near motorways:
https://www.openstreetmap.org/changeset/112506945

And I'd assume similar happens for bridges etc. So if you're trying to avoid them for safety reasons or something it may need further tweaking...
