### ISSUE TITLE
Display/filter/highlight layer property of objects

### ISSUE THREAD

**Issue by keynlotepan** [streetcomplete/StreetComplete#2446]
**Use case**

In my residential environment https://www.openstreetmap.org/#map=19/48.18086/11.55255 there are lots of stacked objects. For example pedestrians move in different layers than cars. In many situations it is impossible to distinguish whether an indicated object (path, ...) is on one or another layer. 

**Proposed Solution**

It would be very helpful to display at least the layer property of a selected object, or maybe better, to filter or highlight a specified layers in the map.

**Comment by westnordost** [comment]
The layer property is somewhat of a technical property that doesn't translate to human related terms. If the app said "it's on layer 2", it wouldn't mean anything. the layer property is just for renderers to know what is above what else, thus only makes sense in context.

What you are looking for is `level` (or `level:ref` / `addr:level`) and for this, there is already an implementation. If the element a quest refers to is in for example `level=UG`, it will be displayed like this in the quest form. It'd f.e. say "on level UG: What are the opening hours of Mamma Mia? (Italian Restaurant)"

**Comment by keynlotepan** [comment]
Sorry, I cannot find this level indicator in the quest form (s. screen shot)

![Screenshot_20210102-221625_Street�Complete](https://user-images.githubusercontent.com/11136173/103466806-876d3f80-4d48-11eb-99a9-90724b1659f9.png)

**Comment by keynlotepan** [comment]
Sorry, now I saw it: "unterirdisch"
