### ISSUE TITLE
Quest doesn't properly clear when completed, can be duplicated

### ISSUE THREAD

**Issue by emersonveenstra** [streetcomplete/StreetComplete#2447]
Sometimes, if you do a quest, the icon doesn't disappear and you can do the same quest twice. It's an intermittent bug, it only happens if there's no zoom or screen movement during a quest (and even then is still intermittent).

**How to Reproduce**
1. Find a quest that doesn't zoom when you click on it.
2. Complete the quest
3. Quest might stay there, complete the quest again

**Versions affected**
Android 9, StreetComplete 28.1

I've attached a video showing the bug, and the duplicated quest shown in the video is here: https://www.openstreetmap.org/way/17865142/history 

https://user-images.githubusercontent.com/5402360/103469426-93e69d80-4d32-11eb-85e5-aac963b7f355.mp4

**Comment by westnordost** [comment]
Hm, and if you move the map in between, the icon vanishes?

**Comment by westnordost** [comment]
Hm interesting, I can't reproduce this with the given reproduction (Android 10). Did you answer anything else for that way section?

**Comment by matkoniecz** [comment]
I had similar phantom quests remaining, but I never managed to consistently reproduce it.

**Comment by emersonveenstra** [comment]
> 
> 
> Hm, and if you move the map in between, the icon vanishes?

Correct, if the phantom one appears and you move or zoom the map, it disappears.

> Hm interesting, I can't reproduce this with the given reproduction (Android 10). Did you answer anything else for that way section?

I didn't answer anything else. It's only happened 2 or 3 times over the 100ish quests I've done with v28.1, so I can't reproduce it on demand.

**Comment by westnordost** [comment]
Hm well, whatever that is, I'll just add a check that if it is solved already, the form will not be opened again.
