### ISSUE TITLE
StreetComplete cannot interpret implicit maxspeed tags

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2449]
**How to Reproduce**
The wiki documents how implicit maxspeeds may be tagged as `maxspeed=<countrycode>:<zone type>`.

This schema is currently not understood by StreetComplete. 

Please add parsing for implicit maxspeeds in the maxspeed tag.

**Versions affected**
v29.0-beta1

**Comment by matkoniecz** [comment]
Where this parsing would be needed?

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/1998#issuecomment-676787192 (judging by #2450 it seems that you expected max speed resurvey quest where such parsing would be needed - it does not exist)

**Comment by westnordost** [comment]
Wow, jesus, I just read https://github.com/streetcomplete/StreetComplete/issues/1998#issuecomment-676787192 (and answer(s) again). Just having `maxspeed:signed=yeS/no` would really be a big step in the right direction IMO.

**Comment by matkoniecz** [comment]
> Wow, jesus, I just read #1998 (comment) (and answer(s) again). Just having maxspeed:signed=yeS/no would really be a big step in the right direction IMO.

Asking your opinion about such tag was on my TODO list, now I will put there "make proposal for `maxspeed:signed`" (though if someone else wants to do this - feel free)

**Comment by RubenKelevra** [comment]
> > Wow, jesus, I just read #1998 (comment) (and answer(s) again). Just having maxspeed:signed=yeS/no would really be a big step in the right direction IMO.
> 
> Asking your opinion about such tag was on my TODO list, now I will put there "make proposal for `maxspeed:signed`" (though if someone else wants to do this - feel free)

I feel like the proposal should a bit more broader and explicitly depricate the 'maxspeed:source', 'maxspeed:type' which makes it impossible to properly get any definitive information about the actual speed limit from the database. 

Additionally the [proposal for `zone:traffic`](https://wiki.openstreetmap.org/wiki/Proposed_features/trafficzone) could be picked up to mark streets as within an urban area, which gives them a default speedlimit.

While this may sound a bit redundant as well, there are certain rules in cities which don't apply to a rural context, like parking laws, overtaking etc which has nothing to do with maxspeed. 

A city street would usually be marked just once as a zone:traffic, but the maxspeed might change from implizit to explicit and back over time when signs are changed.

**Comment by RubenKelevra** [comment]
@westnordost well, there was never a proposal to make "maxspeed:source" or "maxspeed:type" a tag. Someone just created a page in the wiki - that's it.

So I don't see a reason why there shouldn't be a properly designed tagging scheme for this.

**Comment by matkoniecz** [comment]
StreetComplete is not going to just start tagging in a new scheme not used by anyone else and not accepted by community.

**Comment by smichel17** [comment]
> Well, there was never a proposal to make "maxspeed:source" or "maxspeed:type" a tag. Someone just created a page in the wiki - that's it.
> 
> So I don't see a reason why there shouldn't be a properly designed tagging scheme for this.

There is no technical reason why SC can't start using a new tag, but it is a policy decision by @westnordost not to do this.

In my opinion, it is a wise decision. Popular editors have a lot of power to influence a new tagging schema, or even force it on the community (particularly SC, where the specific tags are not shown to mappers before upload, whereas IIRC iD will let you add arbitrary tags). But consolidation of power is dangerous to communities; checks and balances keep them stable (see also: US politics). So I think it is very healthy for the longevity of OSM to establish a behavioral standard that editors shall not decide on tagging standards.
