### ISSUE TITLE
Erste Hilfe Stationen - Polizei - Krankenhaus - Kriegsgräber

### ISSUE THREAD

**Issue by wolli** [streetcomplete/StreetComplete#2453]
**Use case**

**Proposed Solution**

**Comment by wolli** [comment]
Krankenhaus fehlt

**Comment by matkoniecz** [comment]
> Krankenhaus fehlt

What you mean by "missing hospital"?

**Comment by westnordost** [comment]
I'll close this "feedback required" ticket early because the description is inadequate.
