### ISSUE TITLE
One answer remains after Upload

### ISSUE THREAD

**Issue by chris-est** [streetcomplete/StreetComplete#2460]
After answering some quests and uploading them, one answer did not seem to get uploaded (there is still a red '1' displayed on the upload button).
Answered some more quests and uploaded them, but one answer still remains.

Can i somehow see which answer is not uploaded or a history of the quests i did?

**How to Reproduce**
Answer some quests, then upload

**Versions affected**
Android: v9.0
StreetComplete: v28.1 (FDroid)

Here is the _adb logcat_:
```
01-06 14:47:52.364  4933  4966 I Upload  : Starting upload
01-06 14:47:52.368  4933  4966 I CommentNoteUpload: Commented on 0 notes
01-06 14:47:52.368  4933  4966 I DeleteOsmElementUpload: Deleting Elements
01-06 14:47:52.370  4933  4966 I UndoOsmQuestUpload: Undoing quest changes
01-06 14:47:52.375  4933  4966 I OsmQuestUpload: Applying quest changes
01-06 14:47:52.573  4933  4966 I SplitOsmWayUpload: Splitting ways
01-06 14:47:52.575  4933  4966 I CreateNotesUpload: Uploading create notes
01-06 14:47:52.575  4933  4966 I CreateNotesUpload: Created 0 notes
01-06 14:47:52.576  4933  4966 I Upload  : Finished upload
```

**Comment by westnordost** [comment]
Hmm, nothing out of the ordinary in that log. Can you show the debug and verbose log statements too?

**Comment by chris-est** [comment]
> Hmm, nothing out of the ordinary in that log. Can you show the debug and verbose log statements too?

How can i output the debug log statements?
_adb logcat *:D_ did not output more information

**Comment by westnordost** [comment]
Hmm okay, so I guess there are no debug log statements.

I think the only thing that will help us here would be to get our hands on your database. Possibly there is a `adb` command to download that database from your device?

**Comment by chris-est** [comment]
Is the database stored in a file?
I have adb shell access so i can download it from the device if i know where to search for it.

**Comment by westnordost** [comment]
Yes, it is. It should be `/data/data/de.westnordost.streetcomplete/streetcomplete.db`

**Comment by chris-est** [comment]
> Yes, it is. It should be `/data/data/de.westnordost.streetcomplete/streetcomplete.db`

I got the database :-)
Is it safe to upload here or should i change something in the database? (Also see my edited last message)

**Comment by westnordost** [comment]
What quest was it? In which table? Do you have the "original" database without your fix?

**Comment by westnordost** [comment]
In the database itself there is no private information, you can safely post it here or send it as an attachment to my email address osm@westnordost.de

**Comment by chris-est** [comment]
> What quest was it? In which table? Do you have the "original" database without your fix?
```
table: osm_quests_full
quest_id	quest_type	quest_status	tag_changes	changes_source	last_update	element_id	element_type	geometry_polylines	geometry_polygons
4795	DetailRoadSurface	ANSWERED		survey	1603395297931	17671569	WAY		
```
Here is the database before i changed it (had to zip it for upload to github): [streetcomplete_backup.db.zip](https://github.com/streetcomplete/StreetComplete/files/5777581/streetcomplete_backup.db.zip)

**Comment by westnordost** [comment]
Okay, found the issue: The quest type "DetailRoadSurface" (has been merged into "RoadSurface" does not exist anymore, hence the uploader doesn't know what to do with it.

**Comment by chris-est** [comment]
Thanks for looking into this and for the clarification.

**Comment by westnordost** [comment]
Mh I am still wondering what I should do about it:
1. do nothing. People who solved that particular quest but did not upload it before updating to the version that removed that quest are stuck with the counter displaying "1" forever
2. sweep (on startup) all quests that don't exist anymore once or every time the app starts
3. on fetching quests from database, register if any quest type does not exist anymore and remove that. (A little weird though that a GET should trigger a DELETE of something)
4. let `getCount` return only the count of valid columns of the table

Yeah, I am leaning towards 1 too, because your case is somewhat like an edge case. On the other hand, who knows how many users are out there having exactly that problem but never got around to reporting it.
The cleanest solution I'd say is solution 2

**Comment by matkoniecz** [comment]
I would say that 2 would much nicer, "are stuck with the counter displaying "1" forever" is quite ugly and as usual tiny minority bothers to report bugs.

Counting only existing quests also sounds fine, as long as it is not going to cause divergences in other places (like warning about many not uploaded quests).
