### ISSUE TITLE
Tactile pavings at bus stops and crosswalks in Denmark

### ISSUE THREAD

**Issue by cookieblues** [streetcomplete/StreetComplete#2463]
Howdy,

I live in Copenhagen in Denmark, and I recently started using the app. I was sad to find that there wasn't a quest for tactile pavement at crosswalks, since almost all crosswalks around here have tactile pavement.

Upon checking available quests, I noticed that the quest does in fact exist but only for certain countries (https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingUtil.kt). However, Denmark is not included.

I was wondering if Denmark could be added to this list?
Or what would it take to include Denmark in this list?

**Comment by westnordost** [comment]
The country list is based on some research done, mostly by looking at random samples with Google StreetView and alike.

If you are of the opinion that tactile does exist (enough) in Denmark that it is worth asking about it, i.e. is not something very exotic, could you please share with us some pictures (from Google StreetView, own pictures, from other sources) that show tactile pavings on crosswalks for documentation?

**Comment by cookieblues** [comment]
I will. It's late at night here, but I can walk around and gather some tomorrow.

**Comment by westnordost** [comment]
It might be easier to just link a few examples from StreetView

**Comment by westnordost** [comment]
Ok, found three in Copenhagen, I guess this is evidence enough

https://www.google.de/maps/@55.6784588,12.5646018,3a,75y,274.67h,77.03t/data=!3m9!1e1!3m7!1sZVcqp1-oZshtOtQTpUKiaQ!2e0!7i16384!8i8192!9m2!1b1!2i28

https://www.google.de/maps/@55.7065545,12.5156411,3a,24.6y,142.73h,73.85t/data=!3m9!1e1!3m7!1sH8Q6qrvYnNDU58q3JN5jTw!2e0!7i16384!8i8192!9m2!1b1!2i66

https://www.google.de/maps/@55.7065545,12.5156411,3a,24.6y,142.73h,73.85t/data=!3m9!1e1!3m7!1sH8Q6qrvYnNDU58q3JN5jTw!2e0!7i16384!8i8192!9m2!1b1!2i66
