### ISSUE TITLE
Give priority to address (housenumber) quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2464]
**Use case**
To be able to get "Address" (housenumber) quest, one currently first needs to solve "building type" quest. The reasoning is (as far as I get from other issues) is that some building types (garages, sheds...) do not have house numbers, so it makes no sense to ask for them there. This is highly unoptimal.

While valid observation that some building do not have address, there are few issues with this fact blocking the address quest:
- the "Address" quest is (or should be) a **high priority**. One of the main uses of map is to find something on it, and that something is in majority of cases defined by its address (the other common way is by searching for "closest amenity of some type"). 
- the "Building type" quest is (or should be) of a very **low priority**. Not only is there much lower usability of such data (most being covered by separate landuse polygons), but there is confusion/dispute between [building](https://wiki.openstreetmap.org/wiki/Key:building) and [building:use](https://wiki.openstreetmap.org/wiki/Key:building:use) (with most people mapping it the "wrong" way), also it is often hard to answer correctly (eg. there is often no way to know what was original purpose of the building when it was built without visiting cadastre), and even more often mapped incorrectly (eg. `building=house` when it should be `building=apartments` etc.), and even more problems because purpose is sometimes shared (shop+apartments or shop+house etc). Actually, if it was not being prerequisite for "Address" quest, it should probably be disabled by default as it is arguably likely to pollute the database with incorrect data when used by average mapper.
- the issue is additionally aggravated  by the fact that even after solving the "Building type" quest, and having auto-upload, the "Address" quest does not show immediately (like for example steps-related quests do), requiring another resurvey at the later time (#1550, #1510).

**Proposed Solution**

I propose to **make address quest a priority**. It is one of the most useful quests SC offers, and effectively disabling such high priority quest by low priority quest is counterproductive.

One way to do this would be to always ask for address quest first, and have an additional answer `This building does not have an address (it is garage or shed or similar)` (which can then let user choose building type, or simply mark it as having no address).

**Comment by matkoniecz** [comment]
> While valid observation that some building do not have address, there are few issues with this fact blocking the address quest:

I see no other sane way of handling `building=yes`.

Ask housenumber for every building and leave trail of pointless notes? Merge building type and address quest into one?

**Comment by matkoniecz** [comment]
> One way to do this would be to always ask for address quest first, and have an additional answer This building does not have an address (it is garage or shed or similar) (which can then let user choose building type, or simply mark it as having no address).

Both address quest and building quest are quite complex, merging them into one would make it even more awfully complicated. Not sure is it possible to get sane interface in this way (and that completely skips problem of implementing this)

**Comment by smichel17** [comment]
See #1717

**Comment by westnordost** [comment]
See @matkoniecz , while desireable, I see no way to do this

**Comment by mnalis** [comment]
@matkoniecz but there _is_ a simple option of tagging the building without address like garage etc with [noaddress=yes](https://wiki.openstreetmap.org/wiki/Key:noaddress) or [nohousenumber=yes](https://wiki.openstreetmap.org/wiki/Key:nohousenumber) - there is no need to leave notes requiring mapper attention.

(Later, "building type" quest can remove `noaddress`/`nohousenumber` tag when building is tagged as garage or shed where such tag is implied.)

So the procedure for "house number" quest would be modified:
- if polygon already has `addr:housenumber` or has `nohousenumber=yes` or has no `building=*` tag, skip house number quest; otherwise, ask for house number
- if the user selects house number, add tag `addr:housenumber=XXXX`; and if user selects **it has no housenumber - it is something like shed or garage** add tag `nohousenumber=yes` instead

And procedure for "building type" quest, would be modified slightly modified too:
- if polygon is not marked with `building=yes` tag, skip the "building type quest", otherwise ask for building type.
- if the user selects a building type, modify `building=yes` to `building=XXXX`
- if building type selected is one for which it is implied to have no address, remove `nohousenumber=yes` if it is exists, as it is redundant (although harmless, so it's no big deal even if we miss some obscure building type)

That way, quests should work correctly, no matter to which one the user has given priority.

(Of course there are other options like "leave a note" etc. which I have not mentioned here, because they would remain the same and do not change the behavior.)

Could you explain why this would not be possible to do, or what am I missing why this would be terrible idea?
Or perhaps it maybe _could_ be done in this way (thus immensely improving situation with address quest)?

**Comment by matkoniecz** [comment]
>  noaddress=yes or nohousenumber=yes

Spamming this on `building=yes` (instead of tagging building properly) is not an option.

**Comment by mnalis** [comment]
@matkoniecz Why do you think adding **appropriate and truthful tag which conveys extra information** to a building would be spamming? buildings with no addresses are minority in my experience anyway, and while _I do agree with you that adding type that implies more information is preferable_, it should not be a hard requirement.  

If mapper opts to provide that extra information about building type later, the **end situation would be the same as now**, so no problems there, right? But if user decides that they care about house numbers only, but not building types, we would **end up with more useful information** (if you agree with me that address has more use then building type?)

Besides, if we call "spamming" anything that does not provide maximum amount of detail, should we then also remove `building=residential` as "spamming", as it gives LESS information than `building=house` (which in turn provides even less information than `building=detached`)? 

Because if the idea is to force users to do quests they do not consider important in order to be able to do quests they do consider important, it is not working that well in longer periods, as it build frustration and leads to users giving up (either on whole app, or on both quests). And that it _is_ frustrating, can be clearly seen in sheer number of issues raising this "housenumber" question in various forms.

**Comment by westnordost** [comment]
It is not an option not because @matkoniecz would not accept it, but the community would not accept it.

Just read up on [`nosquare`](https://github.com/openstreetmap/iD/issues/6332) for example, the discussion caused quite a stir.

**Comment by mnalis** [comment]
@westnordost I absolutely agree with you that there are some tagging ideas that are not a good ideas and will cause a stir like in `nosquare` example. However, I have not found any such objections on [talk page](https://wiki.openstreetmap.org/wiki/Talk:Key:nohousenumber) for [nohousenumber=yes](https://wiki.openstreetmap.org/wiki/Key:nohousenumber) nor [noaddress=yes](https://wiki.openstreetmap.org/wiki/Key:noaddress), nor in various StreetComplete issues I've found on the subject? 

Could you point me to the thread in issue discussing why `nohousenumber=yes` where community raised concerns that it is evil? I'm genuinely interested in why it would be a bad idea, as I did not find it. 

(Also, I apologize if my response came off as harsh to either you or @matkoniecz if any of you read it that way, as that was never my intention - I'm highly grateful to both of you and everybody who contributed to SC and OSM as whole - but English is not my native language so I apologize for any possible blunders). 

But I'd like to try to find an angle to solve this problem, as the current workaround (manually adding new note for each housenumber as "housenumber quest" is not popping up) is probably even more spammy than marking only garages without housenumbers with `nohousenumber=yes` (not to mention way more work intensive, prone to errors and frustrating).

**Comment by westnordost** [comment]
It did not come off as harsh, don't worry. I come off as frank in English as well.

> However, I have not found any such objections on talk page for nohousenumber=yes nor noaddress=yes, nor in various StreetComplete issues I've found on the subject?

Because noone yet tried to add this information to every building in the world. Same with `oneway` tag, really.

**Comment by matkoniecz** [comment]
> Because noone yet tried to add this information to every building in the world

It has not happened yet, but I am pretty sure that people would not be happy if SC would start adding it on a large scale. Even adding `cycleway:both=no` is considered as problematic by some (it is minority, but more avoidable tag would have larger share of protests).

> Also, I apologize if my response came off as harsh to either you or @matkoniecz if any of you read it that way, as that was never my intention - I'm highly grateful to both of you and everybody who contributed to SC and OSM as whole - but English is not my native language so I apologize for any possible blunders

Exactly the same for me

**Comment by mnalis** [comment]
@westnordost  But it **wouldn't be added to every build in the world** (in my suggestion), it would be added only to buildings which **really have no house numbers** (and then only for a period of time until same [or other] user add more specific building type).

As you mention `oneway=yes` tag, that is good example in my point -- should people refuse to add `oneway=yes` to oneway streets, because they could be adding more precision by using [lanes:backward=*](https://wiki.openstreetmap.org/wiki/Key:lanes#Lanes_in_different_directions) (in combination with `lanes:forward=*`) ? I think not, and many people do add `oneway=yes` to oneway streets, and OSM is better map then if they did't add oneway information in any way.

I do think that prioritizing housenumber quests (at least if user has put "housenumber quest" priority over "building quest") is much more advantageous  then the potential "spam problem" of some buildings without house number being marked with `nohousenumber=yes` (at least for a period of time until someone marks them as `garage` or `shed`).

As I have not seen any such objections in 7+ years the noaddress/nohousenumber have been in existence, I do not think it should be a problem (but if complaints do start coming in, we can always revert the change - although I do not think it would happen).

@matkoniecz  I didn't read the discussion about `cycleway:both=no`, but it would seem to me to mean the same as `cycleway=no`, so it might be redundant and less common - and thus be less wanted. But `nohousenumber=yes` only has alternative of using `noaddress=yes`, and I'd be happy with using either one as a marker. Heck, we could even use `note=not_a_building_with_housenumber` or `fixme=mark_specific_building_type` if you think something like that would be preferable.

Also, if people keep current default priority of quests ("building type" preferred to "housenumber"), nothing would change for them. So only more advanced users which do want to change priority of quests and do want to mark housenumbers first would generate `noaddress=yes`, and only for a time until they or other SC user marks a specific type of a building (and all that only in cases when they do actually answer the question instead of skipping it - which is actually most likely thing they'd do if they want to map only important stuff like addresses). 

So I do not think that would be such a big torrent of `noaddress=yes` (or similar) tags, nor that it would persist for infinity.

---

So, I do think doing it this way would be the best solution. But if not, what would be the alternative? I'd even accept if housenumber quest was always shown for all `building=*`, and I would do `Can't say / hide for me` to house number question. In fact, virtually *anything* would be better than current solution IMHO.

**Comment by westnordost** [comment]
> But it wouldn't be added to every build in the world (in my suggestion), it would be added only to buildings which really have no house numbers

Well, same situation as `nonsquare=yes`, no? It would only be added to nonsquare buildings and most buildings have 90° corners.

Anyway, I am just voicing what I am pretty sure the broader community will say about this. You are free to post to the mailing list, wiki or other broader communication channels with your suggestion.

**Comment by mnalis** [comment]
OK, I've asked at https://wiki.openstreetmap.org/wiki/Talk:Key:noaddress. Would you consider reopening with `feedback required` label (so it does not get lost until some feedback is acquired)?

**Comment by westnordost** [comment]
Such comments on the wiki might remain unseen and uncommented for years. After all, who watches this page? I think it is better to post to a channel where people are actually reading along, f.e. the tagging mailing list. I'd then also mention and stress not only "if this would be okay" but what advantage this would bring if this was done.

In the unlikely event that people do not disprove of that, it'd be better if you opened a new issue for it to be implemented.

**Comment by matkoniecz** [comment]
Yes, wiki pages have little to no traffic. Tagging mailing list is the best place for critical overview of tagging ideas from diverse community (and wiki proposal process , but it would be not applicable here).

**Comment by mnalis** [comment]
Ok, I've written more detailed use case on tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2021-January/058199.html

**Comment by mnalis** [comment]
It has been a month without new discussions in tagging list thread, So I'd thought to summarize results:

- total discussion time: 11 days (basically all of it in last 5 days)
- total of 11 people contributed to the discussion (8 if we exclude myself,  @westnordost and @matkoniecz  who also were participating in this github issue)
- 40 messages total (25 if we exclude myself,  @westnordost and @matkoniecz - many were my clarifications)

My general impression was that in the end there is no general dissent against using the `noaddress=yes` tag on objects that do not have address even if there are plenty of them, and in fact majority seemed to think it is fine. 

Few (mostly tangential, except last one) subthreads were raised:
- One bigger subthread argued with idea that addresses visible on the ground (or lack of them) might be incorrect (ie. in disagreement with official database) and thus mappers on the ground should not be mapping them at all - but majority seemed to disagree with that idea and instead uphold "ground truth" rule.
- Other subthread argued that in some countries, it is not buildings that have addresses, but whole cadastral areas (or group of them), so it is not `building` polygons which should have addresses (or lack of them).
- in hindsight, I probably should have created two separate threads for same `noaddress=yes` tag to isolate aerial mapping issue with SC on-the-ground issue, but at the time it made sense to send one message with two use cases, as it was the same tag with same issue (eg. _"is mapping noaddress=yes on objects where it is likely implicit OK?"_)

So it seems to me that implementing `noaddress=yes` as discussed in this issue should not raise any great public outcry.
 
But I'm obviously biased, so I'd like (especially @westnordost) feedback if I should open new (cleaner) ticket for this idea or how we should proceed (if at all, of course)?

**Comment by westnordost** [comment]
Let's postpone that until after I am done with the layers-feature. I think probably it will be much better anyway to use that instead of via a quest to record housenumbers efficiently.

**Comment by andrewharvey** [comment]
> Other subthread argued that in some countries, it is not buildings that have addresses, but whole cadastral areas (or group of them), so it is not building polygons which should have addresses (or lack of them).

This is true for me. A backyard shed or garage usually has an address in the sense that the parcel of land that the house sits on has an address so the shed and garage are considered at that address. So not correct to really say they have no address, but because we usually don't map the cadastre and usually just map the address on the main building at the address there's no good solution.

**Comment by mnalis** [comment]
Initial version of **Address overlay**  seems to have been implemented in [v48.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v48.0-alpha1)
