### ISSUE TITLE
Add skip button for questions

### ISSUE THREAD

**Issue by pawlosck** [streetcomplete/StreetComplete#2466]
Please add button to skip current question. If possible button should be in main window, not as menuitem.

For example:
There are questions for bus stops.
1. question about "shelter" -> https://wiki.openstreetmap.org/wiki/Key:shelter
2. question about "tactile_paving" -> https://wiki.openstreetmap.org/wiki/Key:tactile_paving
3. question about "bench" -> https://wiki.openstreetmap.org/wiki/Key:bench

For questions 1 and 3 I can answer from longer distance (from bus or from other side of street), but I can't answer for question 3 because I can't skip question 2.

If next question is connected with current question, please skip all questions connected with current question.

**Comment by westnordost** [comment]
You can
1. in the settings, change the order in which the quests are displayed. So you can move "bench" up. Maybe we should consider moving it up by default, @matkoniecz ?
2. for each quest, when you answer "can't say", press on "No, just hide" to just hide the quest, i.e. skip it.

**Comment by smichel17** [comment]
Related: #124

**Comment by pawlosck** [comment]
How to change order of questions? I can't find this option.
What does "No, just hide"? Is it hidden forever or only today?

**Comment by westnordost** [comment]
Click on the menu button -> Settings -> Quest Selection. There, note the hint at the top

Yes, it is hidden forever. You can bring hidden quests back by tapping on "Restore hidden quests" in the setting. I am thinking about removing this functionality altogether, I think it is rarely used.

**Comment by pawlosck** [comment]
> Click on the menu button -> Settings -> Quest Selection. There, note the hint at the top
> 
I didn't see it. I should go to a oculist ;-).

> Yes, it is hidden forever. You can bring hidden quests back by tapping on "Restore hidden quests" in the setting. I am thinking about removing this functionality altogether, I think it is rarely used.
No, you shouldn't. It's great feature, but should be added new options.
1. Add timeout, after which question will be visible again. 
2. Show hidden questions in current view (as checkbox)
3. Show list of hidden questions (with location) with option to show question again

**Comment by mnalis** [comment]
Please do not remove it, I use it regularly (as TangremES does not follow my priorities, I hide quests for myself to answer ones I consider priorities, and then later unhide them all again to solve less important ones if I have time left). It would suit my workflow better if there was an option to "unhide only currently shown area" too, but that is probably too much to ask...

**Comment by smichel17** [comment]
@mnalis What decides the quests you consider priorities? Would your use case be solved by #1654 and/or #124? If so, please consider adding your use case to #2457.

**Comment by mnalis** [comment]
@smichel17 yes, fully user-configurable presets (like in OsmAnd) would be a best #1654 fix for me. (I've started filling #2457)

**Comment by Helium314** [comment]
> Yes, it is hidden forever.

Hiding does _not_ hide the quests forever. They pop up again after a few weeks (which is a bit annoying, because I often use it to hide 'unsolvable' quests, which usually means features I cannot reach)

**Comment by westnordost** [comment]
Mh okay, but I guess the question is answered. I'll leave the "hide" functionality unchanged.
