### ISSUE TITLE
Residential: Multiple values "match" for same building type

### ISSUE THREAD

**Issue by novoid** [streetcomplete/StreetComplete#2467]
Note: This is no software bug. It's a usability bug which leads to wrong meta-data for residential buildings.

When answering "What kind of building is this?" you currently get a list of possible values:

- House: single-familiy home
- Detached house: free-standing single-family home
- Semi-detached house: pair of two single-family homes
- Row houses: a linear row of similar single-family homes
- [others]

The issue I see here is that those are _not_ categories that are described in a way that they are clearly distinct and separate categories. 

**Any row house, semi-detached house, or detached house is _also_ a "House"** according to the terms and descriptions above. It is a super-class, if you will.

So if the users reads "House: single-familiy home" she will not "parse" the list any further. This happened to me as well, mis-classifying many houses before recognizing the issue which I had to fix in JOSM. To make it even more difficult, there is no enhanced undo feature that would allow to fix those issues in the app (except undoing just the last decisions). Such an advanced undo is suggested within https://github.com/streetcomplete/StreetComplete/issues/2418 and https://github.com/streetcomplete/StreetComplete/issues/748. 

As a matter of fact, the missing distinction continues with other terms as well. **Any semi-detached house can be also classified as a row house and vice versa.** The way I see it is that two similar single-family homes are "Semi-detached house" whereas three or more are "Row houses". I might be wrong here as I am no OSM expert.

**How to Reproduce**

1. Open app, wait for GPS fix
2. answer a "What kind of building is this?" quest
3. read "House" for any given detached, semi-detached or row house and do think that "house is a suitable match" (not reading the other classifications that would provide better matching categories)
4. continue with other quests, keeping the mis-classified house meta-data

**Proposed fix**

As users of SteetComplete do not necessary know OSM-definitions by heart, you do need to extend the descriptions such that they are able to detect mismatches according to names+descriptions. One possible approach would be:

- "House: single-familiy home" -> "Non-detached House: single-familiy home, not similar to (semi-)detached houses"
- "Row houses: a linear row of similar single-family homes" -> "Row houses: a linear row of three or more similar single-family homes"

I can not comment on other languages as my device is set to English only.

**Versions affected**

v28.1

**Source files affected**

At least:

- `app/src/main/res/values-en-rGB/strings.xml`
- `app/src/main/res/values-en/strings.xml`
- `app/src/main/res/values/strings.xml`

**Comment by matkoniecz** [comment]
> wrong meta-data for residential buildings.

Note that tagging detached house as `building=house` (or even `building=residential`) is not incorrect, wrong or inaccurate.

**Comment by westnordost** [comment]
> Note that tagging detached house as building=house [...] is not [...] inaccurate.

Maybe it can be considered a little inaccurate (imprecise) because there is a more "detailed" tag in that case.
But in any case, claiming in the app that `building=house` would be _"single family homes that are **not** (semi-)detached houses"_ would simply be wrong. `building=house` is defined as a single family home and it is simply not further defined if it is in a detached house or not.

But anyway, it is of course favoured if the user answered with the more precise value. I was about to suggest something, but turns out it is already the case:
- the `house` option is deliberately shown in the list below `detached`, so that people see `detached` first and `house` later
- both `house` and `detached` have a description, it should be clear what these two are for
- the icon for `house` already suggests that `house` should be selected for buildings for single families which have no space around them (are not detached or semi-detached)

**Comment by novoid** [comment]
> Note that tagging detached house as `building=house` (or even `building=residential`) is not incorrect, wrong or inaccurate.
> 
> In addition there is tiny to no difference between how `building=house` and `building=detached` and similar building values are used.

I understand.

Then I want to note that as a user, I do find this irritating: there is a list of overlapping options where I may only choose one. In my opinion, the options presented to the user should provide a set of options where only one is matching. Too many things may go wrong if not. If OSM wants to have as precise meta-data as possible (which I would prefer), the options should reflect that situation.

**Comment by smichel17** [comment]
See the end part of https://github.com/streetcomplete/StreetComplete/issues/1716#issuecomment-581161759 for more context. Perhaps that will help with ideas for a better description that does not overlap.

**Comment by novoid** [comment]
> Maybe it can be considered a little inaccurate (imprecise) because there is a more "detailed" tag in that case.

I see.

> But anyway, it is of course favoured if the user answered with the more precise value. I was about to suggest something, but turns out it is already the case:
> 
>     * the `house` option is deliberately shown in the list below `detached`, so that people see `detached` first and `house` later

I don't feel convinced by this argument because at least I tend to read through the list at least once in order to find out about the options. As a user, I get confused quite easily when I do have to choose exactly one value from that list and several might match.

Furthermore, the order of the options is changing as soon as you start choosing and solved multiple quests. This way, I chose the "wrong" (i.e., not the best fitting option) and saw this (slightly wrong option) at the top the next time. 

>     * both `house` and `detached` have a description, it should be clear what these two are for

To me, it was not clear at all.
 
>     * the icon for `house` already suggests that `house` should be selected for buildings for single families which have no space around them (are not detached or semi-detached)

Good idea and nice try ;-) However, people are trained that icons are not that relevant for value distinction as you suggest here. As a matter of fact, the icon for "House" also fits for the descriptions of "Detached house" (it can be interpreted as a detached house in the foreground whereas there are different buildings in the background) as well as "semi-attached" (the right hand side may be interpreted as attached) as well as "row house" (with a little fantasy and a loose definition of "similar" related to the houses left and right).
Icon design helps, yes, but almost all apps are not designed such that icon content is a necessary part of class distinction. Therefore, users are not even closely trained to take icon design into account when the label categories are overlapping.

**Comment by novoid** [comment]
I guess it all boils down to:

- The values have developed over time.
- Values are not representing distinct classes of things. They overlap.
- IMHO: The user typically expects distinct classes of choices within single choice sets
- StreetComplete may (my preference) or may not compensate these differences for its user interface with certain goals:
  - Get the best match for options from the users with the highest level of detail possible
  - Minimize the level of confusion by not adding super- or sub-classes of other values (i.e., stick to one level of abstraction)

If StreetComplete does not want to decide on these things or handle them in a different way, we don't have to discuss personal preferences and close this issue. I was just giving feedback as an IT-savvy person with some background on semantics and user interface design and a friend of OSM but surely not an OSM expert.

I'm well aware that most people do not even understand the implications of the subtle issue I described here. Therefore, most users might just select the less specific option and go on.

**Comment by riQQ** [comment]
I'm in a similar situation as @novoid.

There's definitely room for improving the building types descriptions:

- it was not clear to me that "Row houses" should only be used when multiple houses are mapped as a single *area*. Maybe it would be an option to clarify this in the help text. I know that the plural is used, but I didn't reach the conclusion that it is only to be used for a single *area* comprising multiple houses. I had to look it up in the wiki.
- the single-family distinction is pretty confusing to me. Does it mean I have to walk up to the door and check all the nameplates for the building? Where is the cutoff between "Apartment building" (*apartment*) and "House" (*house*)?
- The description of "Semi-detached house" in StreetComplete is conflicting with the wiki's description:
  - StreetComplete: 
    > pair of two single-family homes
  - [Wiki](https://wiki.openstreetmap.org/wiki/Tag%3Abuilding%3Dsemidetached_house):
     > A house that is attached to another house on one side

**Comment by westnordost** [comment]
Well, I guess you are right: Only because the de-facto situation is that `house` means "a single family home (could be a detached etc too, it's just not defined in more detail)" and thus data consumers must keep this in mind doesn't mean that the app needs to propagate this definition. The app can describe it what you would like it to be (i.e. excluding detached) in order to contribute to that users select the most precise value.
