### ISSUE TITLE
Enable pitch surface quest also for `leisure=track`

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#2468]
### General
Affected tag(s) to be modified/added: [surface](https://wiki.openstreetmap.org/wiki/Key:surface)
Question asked: **What surface does this sport track have?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam):
      Most will probably have `surface=tartan`, but there are enough that have a different surface: https://overpass-turbo.eu/s/1294
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort):
      Taginfo shows that only 17.35% of 87 274 objects with `leisure=track` have a `surface` tag: https://taginfo.openstreetmap.org/tags/leisure=track#combinations

### Ideas for implementation

**Element selection:**
`leisure=track and !surface and (!access or access!=private)` (+ maybe `and sport`)

**Proposed GUI:**
Same as "What surface does this sport field have?" quest (#1170 / #2377).

**Comment by matkoniecz** [comment]
What kind of sports are not appearing on `leisure=pitch` and are appearing on `leisure=track`? It would be necessary to add them to list of valid sports.

Right now it is

```
        "multi", "soccer", "tennis", "basketball", "equestrian", "athletics", "volleyball",
        "bmx", "american_football", "badminton", "pelota", "horse_racing", "skateboard",
        "disc_golf", "futsal", "cycling", "gymnastics", "bowls", "boules", "netball",
        "handball", "team_handball", "field_hockey", "padel", "horseshoes", "tetherball",
        "gaelic_games", "australian_football", "racquet", "rugby_league", "rugby_union", "rugby",
        "canadian_football", "softball", "sepak_takraw", "cricket", "pickleball", "lacrosse",
        "roller_skating", "baseball", "shuffleboard", "paddle_tennis", "korfball", "petanque",
        "croquet", "four_square", "shot-put",
```

https://github.com/streetcomplete/StreetComplete/blob/25d0984bcedc5d4daf617486f2c71d22dbc03633/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddPitchSurface.kt#L9

**Comment by FloEdelmann** [comment]
Taginfo lists only 4 [`sport` combinations](https://taginfo.openstreetmap.org/tags/leisure=track#combinations):

* 33.84%: `sport=running` → **This one is missing from the list above**
* 16.45%: `sport=athletics` → already included
* 1.54%: `sport=equestrian` → already included
* 1.52%: `sport=multi` → already included

Additionally, the wiki lists some more:

* `sport=cycling` → already included
* `sport=horse_racing` → already included
* `sport=dog_racing` → **This one is missing from the list above**
* `sport=toboggan` → **This one is missing from the list above**

**Comment by matkoniecz** [comment]
I guess that the same icon and switching question based on what is tagged would be fine...

**Comment by westnordost** [comment]
I think so too

**Comment by rhhsm** [comment]
> Is anything missing?

"table_tennis" please

**Comment by matkoniecz** [comment]
table_tennis is deliberately excluded as asking about surface would be confusing

Even as human with direct tag access I am unsure what should be tagged - surface of area around table? Surface of table?

Also, only areas are included anyway.

**Comment by rhhsm** [comment]
Sorry, I once needed it but it was missing, but it must have been the "What sport is played here?"-quest
