### ISSUE TITLE
winter service quest

### ISSUE THREAD

**Issue by jtracey** [streetcomplete/StreetComplete#2471]
### General
Affected tag(s) to be modified/added: [winter_service](https://wiki.openstreetmap.org/wiki/Key:winter_service)
Question asked: **Is this X maintained in the winter?** (where X is a `highway=*`)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

In areas with annual snowfall, knowing which paths and roads are still accessible (for small vehicles, bicycles, wheelchairs, and the otherwise handicapped)  in winter is crucial for navigation. Most of such places have some but not all roads and paths winter maintained.

### Ideas for implementation

**Element selection:** 
Selection should be limited to `highway=*` ways, perhaps those that already have a `surface=*` tag (maybe even further filtered to paved ways, since while there are certainly unpaved paths that are winter maintained, the most pressing use is for people who would likely be sticking to paved ways). In general the tag is very similar to surface tagging.

**Metadata needed:** 
 The quest would have to be geofenced to areas with annual snowfall, otherwise you'll end up with entire countries where the quest is meaningless. It would also be helpful if the quest was only asked in that area's snowy season, which primarily varies based on hemisphere. Wikipedia has [a map of the world by snowfall](https://commons.wikimedia.org/wiki/File:Countries_receiving_snowfall.png), clearly all the areas in light blue could have the quest enabled. Beyond that, I don't know how to identify which regions the quest should be asked; e.g., I don't know how to geofence places like California, where half of it is coastal that gets essentially zero snow, and half of it is mountains that are very snowy. I suppose just disable by default, but allow people to enable it.

**Proposed GUI:**
The UI would be similar to the surface selection quest, but there are only three possible answers: "Yes" (the way is consistently maintained in winter), "No" (the way is frequently covered in snow or ice in winter), and "Limited" (the way is occasionally maintained, like stretches of sidewalk that are patchwork cleared by residents).

**Comment by matkoniecz** [comment]
Note also that quest is verifiable by survey only when:

- there is an explicit sign about winter maintemance

or 

- snowfall happened
- road was gritted/snowplowed

What worse, recent snowfall with snowplowing/gritting is not evidence of lack of winter maintenance - road may be simply of a lower priority.

----

Where it would be useful? In some countries at least nearly all public roads would be `winter_service=yes`

In Poland I would expect it to be over 99.8% of public roads, though that number is pure guess. So at least there this quest would be pointless.

**Comment by DerDings** [comment]
It would be very useful with public foot / cycle ways and service roads in Germany. Many parts of the public cycle network don't have any winter service.
However, while winter_service=no is often declared by a sign, this is not the case with winter_service=yes. But for public, signed ways winter service can be assumed unless otherwise stated (in Germany).

Since this is limited to public, signed ways, the filter may be 
`highway=service and !service` (to not find driveways etc.)
for roads
and
`(  highway~footway|cycleway or ( highway=path and (bicycle~designated|official or foot~designated|official) )  ) and (!informal or informal=no)` for ways, only if they're inside an area `leisure=park or landuse=cemetry` to make sure only really public ways are included.

**Comment by westnordost** [comment]
TBH I don't really see this a viable for a quest. 
Not all places where there is winter service is signed to be that way and the other way round. In cities, you can assume that there are no signs at all (except maybe a few footpaths with a warning sign that there is **no** winter service). It is not well verifiable outside of times where there is snow and even then, not really, see @matkoniecz 
Plus, it would add huge amounts of spam, again, the answer in cities will always everywhere be "yes". Outside of cities, the answer will almost everywhere be "don't know / not signposted", however this should be tagged.
