### ISSUE TITLE
house number quest only appears several minutes after building type is added

### ISSUE THREAD

**Issue by schmittlauch** [streetcomplete/StreetComplete#2474]
Related to #2473, I finally disabled the *number of house levels* and *roof shape* to be asked for the house number after determining the building type. This takes valuable time when just walking around a village and prevents me from adding building type and house number in one go.
Unfortunately, after adding the building type it took several minutes until the new question for the house number popped up. That wasn't the case for the *house levels* and *roof shape* quests when I had them enabled.
I have the impression that the building type change needs to commited to the OSM db and the open quests have to be re-fetched before the house number quest appears. Manually looking for quests (re-fetching) doesn't work immediately after adding the building type. 

**How to Reproduce**

1. disable the *number of house levels* and *roof shape* quests
1. go to a house with undetermined building type and add a type to it that allows house numbers (e.g. single-family-house)
1. See that after adding the type, no new quest appears immediately. The house number quest only appears after several minutes. 

**Versions affected**

StreetComplete v28.1

**Comment by schmittlauch** [comment]
might be related to #1550 #1510

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_doesn.27t_the_housenumber_quest_appear_immediately.3F https://github.com/streetcomplete/StreetComplete/issues/1119 https://github.com/streetcomplete/StreetComplete/issues/1369

**Comment by mnalis** [comment]
#1119 (and linked #1510 elsewhere) was great explanation back then when SC used overpass queries, but if I understand correctly that is no longer a case?

The same thing is with FAQ and #1369  (the workaround mentioned there to force-download small are to get housenumber quest to appear does not work for me, BTW. Should it?). 

Or is SC still using overpass queries, I'm confused? And if it now works on downloaded OSM data instead, perhaps a new description of why it is (in current SC operating mode) still problem to show address quest immediately after building type quest is solved would be very nice.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/2438#issuecomment-754031120

**Comment by matkoniecz** [comment]
> force-download small area to get housenumber quest to appear does not work for me, BTW. Should it?

Invalidating quest cache and downloading new quests should work. Hard to say without knowing affected location, maybe objects are not eligible for some other reason.

> The same thing is with FAQ

Good point, I updated also FAQ
