### ISSUE TITLE
Extend list of buildings with fire_station

### ISSUE THREAD

**Issue by rakulle** [streetcomplete/StreetComplete#2476]
**Use case**

At question what kind of building is this it might be nice to say, that it is a fire station. Even small villages in Germany have a volunteer Firestation.
**Proposed Solution**

Extend list of buildings with fire_station

**Comment by matkoniecz** [comment]
Is it actually a separate, distinguishable type of building construction?

**Comment by rakulle** [comment]
The building type is not specific, only the use of building. When specifying i choose normal house, public building, office building and so on. Therefore i thougt it migtht be useful to have also the possibility to add  amenity=fire_station and maybe even name=* according to https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfire_station or https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dfire_station

**Comment by matkoniecz** [comment]
Note that building quest is tagging `building=*` value, not `amenity=*`.

**Comment by rakulle** [comment]
Sorry, i am just starting to understand. I Found building with value  fire_station  here  https://wiki.openstreetmap.org/wiki/Key:building
![whattypeofbuilding](https://user-images.githubusercontent.com/77207966/104106933-4087c880-52b9-11eb-9a55-08170b82d2b9.jpg)

**Comment by rakulle** [comment]
We would probably then also need police etc. maybe it makes sense to create a category like emergency? 

![hospital-etc](https://user-images.githubusercontent.com/77207966/104107152-93ae4b00-52ba-11eb-8e3a-4da87c71b9d2.jpg)

**Comment by westnordost** [comment]
"bürgerliche Einrichtungen"? Das hört sich seltsam an, ich würde schreiben "öffentliche Einrichtungen". (Nicht alle Übersetzungen ins deutsche sind von mir)

Anyway, as @matkoniecz said, the quest only asks for the type of building. This confuses many newcomers, but in OpenStreetMap the data what kind of building something is and what kind of amenity, leisure, shop etc is in there are actually separate information. The former is just about the building (architecture, style, ....), the latter is the actual information that is shown OSM based mapping apps.

**Comment by westnordost** [comment]
But on the other hand, the building for a fire station is special usually - it is a big kind of garage with high ceilings mostly.

**Comment by rakulle** [comment]
I guess, the bigger question is about concept: how far acctual mapping is supposed to be done using streetcomplete. Or is the main goal to answer only specific questions, and if not possible, then just  leaving a note.  If mapping: 
>würde schreiben "öffentliche Einrichtungen" (public services?) then we probably have to think of more categories, to subsumize for example child care, school and university within maybe "Education"/"Bildungseinrichtung" 
>This confuses many newcomers
In my opinion, welcoming newcomers ist the main Value of Streetcomplete. When i first installed it, I experienced the sprit of "please come along and have fun", which got me started.

**Comment by westnordost** [comment]
Well, StreetComplete can't just make up building values. If something like `buliding=education` or something already existed before, I would have added that instead of school / university / college.

**Comment by rakulle** [comment]
Hi there, yes, we should not try to fix open streetmap here. For me, StreetComplete appears like a Layer between nerdy geek Place OSM (>hard to get in) and me/other People that want to have some Fun and interesting Moments while being outside and wandering around. A Layer that gives me the opportunity to contribute with no hazzle.

**Comment by boly38** [comment]
What should we select for police ? Emergency?

**Comment by mnalis** [comment]
> What should we select for police ? Emergency?


Does the [StreetComplete/FAQ#Building Type Quest - Why don't I see the right types](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?) help?  You shouldn't need to know what the building is being used for in order to answer that quest. You only need to answer _"how does the building style looks like from the outside"_. So, the question is basically  _"What does architectural style of that specific building in which police station in situated visually looks closest to?"_ 

That being said, in most of my areas, I'd probably choose general `Civic building` category and confirm that. Or maybe `Government building` under it. But if that building looks more like regular office building (depending on exact police branch and its use), i might choose `Office building` instead.
