### ISSUE TITLE
New quest - Non-assistance dog allowed or not in leisure=playground and leisure=park

### ISSUE THREAD

**Issue by Codain** [streetcomplete/StreetComplete#2478]
### General
Affected tag(s) to be modified/added: [dog](https://wiki.openstreetmap.org/wiki/Key:dog)
Question asked: **Are non-assistance dogs allowed here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 
Select features with (`leisure=park` or `leisure=playground`) and (no `dog` key or `dog=yes`).

**Proposed GUI:**

In an allow >not allowed order:

- dog=unleashed: Icon with a dog and its owner with no leash + "Unleashed allowed"
- dog=leashed: Icon with a dog and its owner linked by a leash + "Leashed only"
- dog=no: Icon with a dog crossed/stroken + "Not allowed"
- Not signed / I don't know

**Comment by DerDings** [comment]
I like the Idea, but it probably should be limited to certain countries. 
In Germany, for example, rules for that may vary by city and are not necessarily signed ([source (de)](https://totehunde.de/leinenpflicht-in-deutschland/)). In my experience, those unsigned local statutes are very common, so the answer **Not signed** would become spam. 
So the quest shouldn't be enabled in Germany.

**Comment by westnordost** [comment]
Yeah, that's the question, if there is any country or state out there, which is so (well) regulated that you can expect a sign about whether dogs are allowed here or not for every park and playground. I know it is this way for Hamburg, at least for "official / tended by city gov" parks but I can't say the same for the next suburb beyon the city limits.

**Comment by westnordost** [comment]
Closing because there is not enough information (yet) about where one can assume that this thing is signed or not.

> So the quest shouldn't be enabled in Germany.

Germany is well known that a lot of things are signposted that wouldn't be in other countries. So if it is not (always) signed not even in Germany, I think we don't need to discuss further. Singapore, UK maybe? Anyway, research would need to be done and it seems nothing is happening here. Also, it is quite difficult to research because certainly also within one country, the situation differs between cities and countryside.

**Comment by westnordost** [comment]
A possibility would be to use `dog:signed=no` in places where it is not signed, but given that the tag is not used at all yet, I'd rather wait for either a reasonable amount of `dog` (and `dog:signed=no`) tags being tagged on playgrounds and parks, a proposal or at least some more information on for which countries it can be expected that oftentimes this information is signed.

**Comment by codeinabox** [comment]
There are quite a few playgrounds in London that have signs no dogs are allowed in that area. I can take some photos if that helps

**Comment by mnalis** [comment]
- ref: https://github.com/streetcomplete/StreetComplete/discussions/6142
