### ISSUE TITLE
Map doesn't reflect OSM changes from several days ago

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#2479]
Changes in OSM that change the rendering of the map are not reflected in StreetComplete. In the data source https://www.jawg.io/lab/maps the changes are reflected.

Is the tile cache never invalidated or updated? Is there a way to manually invalidate or update the tile cache besides clearing the app's data in Anroid?

**How to Reproduce**
Make a change in OSM that will change the rendering of the map. It won't be reflected in StreetComplete. 

**Versions affected**
StreetComplete 28.1 on Android 10

**Comment by westnordost** [comment]
[See `MapTilesDownloadCacheConfig`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/maptiles/MapTilesDownloadCacheConfig.kt):
- the tiles downloaded from jawg.io are considered **fresh for 24 hours** (i.e. app will not attempt to download it). 
- tiles that are not fresh anymore are kept in the cache for up to 2 weeks, the same time quests that are not refreshed are kept in the cache.

So when you are unlucky, the app just downloaded the map from jawg.io just before the changes resulted in a new tile to be created. Thus, the tiles are 1-2 days behind the OSM data.

**Comment by riQQ** [comment]
So there's no way to manually update the tiles or invalidate the tile cache?

**Comment by smichel17** [comment]
I don't think so. Of course, you could always clear data for the whole app through Android and then reconfigure StreetComplete. Much more work, to be sure, but to be honest I am having trouble understanding when it would be important to have updates faster than 24-48 hours. It seems like a very rare event, so it's probably okay if you have to spend 5 minutes logging into osm again and changing settings to do it. For a long time, many areas of the world were using the NextZen tiles, which were *years* old, and even then most things worked okay (exception: a few intersections that were changed into roundabouts).

**Comment by riQQ** [comment]
It can be confusing when the map doesn't match the quest highlighting of a *way* and the corresponding question exactly.

It might be a problem in the caching mechanism and I wanted to understand how the caching works, because the change wasn't reflected even after 3 days. This conflicts with what *westnordost* said

> Thus, the tiles are 1-2 days behind the OSM data.

Checking back now I got the new tiles after opening StreetComplete after 3.5 days.

**Comment by smichel17** [comment]
> It can be confusing when the map doesn't match the quest highlighting of a way and the corresponding question exactly.

I agree it is confusing. I was sharing my experience that it is rare, even when using tiles that are several years old. With a delay of a few days, I would guess it almost never happens. So, that delay does not seem like a big deal to me.

**Comment by riQQ** [comment]
Yes, it's not a big deal. Still strange that it took *StreetComplete* between 44 and 48 hours to get the changes from *jawg.io*.

- Update *jawg.io*: ~ 36 hours
  > These data change every day and are also visible on your maps with a delay of about two days

  https://blog.jawg.io/jawg-is-evolving-every-day/
- Update *StreetComplete*: ~ 48 hours
- Total: ~ 84 hours = 3.5 days

**Comment by riQQ** [comment]
I made a change on the 1st of April and now 20 days later it's still not reflected in StreetComplete whereas https://www.jawg.io/lab/maps is updated.

**Comment by westnordost** [comment]
The map tiles shouldn't be kept around for that long without being updated.

According to the cache control, the tiles are considered fresh for 24 hours (= will not be downloaded again) and cleared after latest 14 days.

I think I can do nothing further here without logs. This means you'd need to download Android Studio, compile the app from master and let it run on your smartphone while looking at the download logs.

**Comment by georg-d** [comment]
> So there's no way to manually update the tiles or invalidate the tile cache in StreetComplete?

You could manually trigger SC to delete cached data in SC's settings menu - this will retain your login etc. but this does not reliably delete all map tiles as of v37; you must additionally go to android cache deletion. See https://github.com/streetcomplete/StreetComplete/issues/3475

**Comment by westnordost** [comment]
> but this does not reliably delete all map tiles as of v37

Not "not reliably". It does not delete map tiles.

**Comment by mnalis** [comment]
> Not "not reliably". It does not delete map tiles.

Oh? v37.0 still asks when `Delete cache` is pressed: `Delete all downloaded map data, including quests? Data is refreshed after 0.5 days and unused data is deleted after 14.0 days automatically.`, which would seem to imply to me that map tiles (or at least some other map data beside quests) are included in that data to be removed? 

Or perhaps translations should be updated if it (no longer?) removes map tile cache?

**Comment by mnalis** [comment]
(for the benefit of people following links to this ticket)

>>   Not "not reliably". It does not delete map tiles.
> Oh? v37.0 still asks when Delete cache is pressed: Delete all downloaded map data, including quests? Data is refreshed after 0.5 days and unused data is deleted after 14.0 days automatically., which would seem to imply to me that map tiles (or at least some other map data beside quests) are included in that data to be removed?

I'm not 100% sure, but I think this behaviour has changes somewhere before `v52.0`, and **now the cached jawgmaps vector tiles are removed also**:

This code seems to be called on when `Delete cache` is selected:

https://github.com/streetcomplete/StreetComplete/blob/1320cab649d434e9eee03f8db1ee12f851a2b936/app/src/main/java/de/westnordost/streetcomplete/screens/settings/SettingsFragment.kt#L200-L204

and first one seems to be related to purging the tiles cache:
https://github.com/streetcomplete/StreetComplete/blob/1320cab649d434e9eee03f8db1ee12f851a2b936/app/src/main/java/de/westnordost/streetcomplete/data/maptiles/MapTilesDownloadCacheConfig.kt#L30-L35


caveat emptor: one still has to **exit the SC, remove it from recent apps, and restart the SC**, as otherwise it seems some additional memory-cache remains.  I've tried to do that with mobile data & wifi disabled, and indeed there was no map on subsequent start of SC.
