### ISSUE TITLE
Prioritize notes when activated

### ISSUE THREAD

**Issue by natrius** [streetcomplete/StreetComplete#2480]
When someone activates the notes these kind of quests should get prioritized. In a city where a lot is happening the notes should be somehow highligted or at least shown at top no matter what. As "Show notes" is opt-in, if no additional setting is wanted, it should just be changed.

**Comment by matkoniecz** [comment]
Notes are prioritized. Can you link location where notes are blocked by nearby non-note quest?

Note that notes may block nearby notes at as one zooms out all quest icons will disappear.

**Comment by westnordost** [comment]
No answer, closing.
