### ISSUE TITLE
Residential streets flooded again with cycleway quests (regression?)

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2486]
Hi there,

after the update to StreetComplete v29.0 some villages are again flooded with cycleway quests for residential streets. See this screenshot:

![cycleways](https://user-images.githubusercontent.com/32601012/104131783-febe5700-5378-11eb-8157-4c722292074d.png)

Take the quest for <a href="https://www.openstreetmap.org/way/31585957">OSM way 31585957</a> as an example, it's the one marked with the red arrow. It is tagged with
```
    "highway"="residential"
    "maxspeed"="30"
    "name"="Fasanenweg"
```
Could this be some kind of a regression of issue #2251? There this quest was disabled for `highway=residential` (it was discussed to leave this quest for "maxspeed>30" residential ways though. But here we have a way explicitly tagged with `maxspeed=30`...)

(I cross-checked it with SC v28.1, it seems indeed as if this problem was reintroduced with v29.0.)

The cycling cat

**Comment by riQQ** [comment]
The `maxspeed` tag was removed from the filter, see https://github.com/streetcomplete/StreetComplete/issues/2448#issuecomment-756791107.

**Comment by westnordost** [comment]
Yes, it is a regression. It has been fixed on master and will be gone in the next update.
