### ISSUE TITLE
bicycle_road=yes roads should not be included in maxspeed quest

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#2488]
See my https://www.openstreetmap.org/note/2491235
> Unable to answer "What is the speed limit for Marktweg here?" for https://osm.org/way/23940497 via StreetComplete 29.0:
> This is a bicycle road...

Someone answered that this one implies `maxspeed=30` in Germany which is not obvious even to an advanced mapper.
Perhaps they should be filtered. 
A special answer was rejected in #2238

**Comment by westnordost** [comment]
Makes sense

**Comment by westnordost** [comment]
by the way, you are encouraged to contribute such small enhancements yourself with a PR, this way you will also see your name being credited in the changelog.

**Comment by HolgerJeromin** [comment]
> by the way, you are encouraged to contribute such small enhancements yourself with a PR, this way you will also see your name being credited in the changelog.

Thank you. I have done in the past. Will try in the future, but will not be able to compile it. Which is always suboptimal. 

You always can fake the author like I got added by @matkoniecz in 
https://github.com/gravitystorm/openstreetmap-carto/commit/fa79ac061a87593f93e4d64bc8b256cd722b9943
git is so great :-)
