### ISSUE TITLE
Quest suggestion: Roof material

### ISSUE THREAD

**Issue by tobylorenz** [streetcomplete/StreetComplete#2490]
**Use case**
When mapping houses, there are already questions, on number of base and roof levels, roof format, etc.
Another good visual detail is the roof material.

**Proposed Solution**
With the same conditions, roof forms are quested, there should be a question, what roof material the house has.
The tag is documented here: https://wiki.openstreetmap.org/wiki/Key:roof:material.
The proposed options/pictures might depend on the country/region. In our area (Germany, Hesse) we mainly have asbestos, copper, grass, metal, plastic, roof_tiles, tar_paper.

**Comment by matkoniecz** [comment]
How one distinguishes eternit and asbestos (I even thought that it is the same thing)?

How `asphalt` is distinguished from `tar_paper`?

How one may distinguish corrugated plastic from corrugated metal?

How one may distinguish `roof_tiles` from plastic/metal sheets formed to look like roof tile?

**Comment by tobylorenz** [comment]
Good questions.

> How one distinguishes eternit and asbestos (I even thought that it is the same thing)?

That's mostly the same thing for me. More generic it's all cement corrugated sheeting. **Eternit** is one large manufacturer of it. And in the past there material contained **asbestos**.
So maybe we should suggest to OSM to replace these values with just **cement** or **corrugated** or **corrugated_sheeting**.

> How asphalt is distinguished from tar_paper?

In the pictures it seems that asphalt is corrugated and tar_paper is flat. But this is not reflected in the short description. And in fact it's hard to distinguish between corrugated sheeting from asphalt or cement. Both often come colored.
My suggestion here: Drop asphalt and just leave **corrugated_sheeting** and **tar_paper**, because this can be differentiated visually.

> How one may distinguish corrugated plastic from corrugated metal?

In Germany we sometimes have flat plastic roofs in different gray or white colors. That's the modern variant of tar_paper, I would say.
There are corrugated plastic roofs, but these are then usually transparent and used for car ports.
Flat metal roofs are usually not colored, but from raw material, zinc, alu, copper, ... as shown in the picture.
My suggestion: Only use one of the **corrugated** variant here, as in first answer.

> How one may distinguish roof_tiles from plastic/metal sheets formed to look like roof tile?

Not only this. A roof_tile can be from metal, clay/terracota, or concrete. And they are all hard to distinguish, unless you know the manufacturers.
My suggestion: **metal* should only be the flat, non corrugated form.

I mean in general we could suggest also to differentiate between roof material (metal, cement, wood, tar, ...) and form of roof surface (flat, corrugated). But this would probably be too much change.

**Comment by matkoniecz** [comment]
This is segment of `roof:material=metal` ( https://www.castorama.pl/blachod-mod-grafit-7016-1205x870-id-1115226.html ), looks almost exactly like roof tiles from street level (or exactly).

![Blachodachowka_modulowa_1210_x_720_mm_grafitowa-927890-505541](https://user-images.githubusercontent.com/899988/104200360-d9892180-5428-11eb-8be0-0552ed2a93ec.jpeg)

**Comment by tobylorenz** [comment]
Yes, I know ;-) Maybe we need to cleanup the roof:material tag in OpenStreetMap first.

With my proposal, I would set such a metal segment to

- roof:covering=roof_tiles
- roof:colour=black
- roof:material=metal, if known

**Comment by westnordost** [comment]
You should read the [quest suggestion guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete), specifically I see the following guidelines not being fulfilled. Please use the appropritate template next time you propose a quest ([this one](https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md)).

As @matkoniecz implicitly stated without saying it directly is that it is very difficult for surveyors to choose the right value here.

> 👨‍💻 Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary
> 🐿️ Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible

What material it is exactly seems to be quite hard to determine without being the owner or something of the house. Additionally, the roof is way up for many buildings, to determine anything than the shape or levels will be too much to ask for many buildings. So even if hte values of the roof material are straightened out, I just don't see this in StreetComplete. Slate could be plastic, tiles could be metal etc etc

> 🤷 Useful purpose: Especially for tags that are not that well established yet - they should have some application. As by the design of OpenStreetMap, there are countless things that could be collected, such as the color of the cycleway, the brightness of street lamps, etc. and sometimes things like these are even documented on the wiki (because it is a wiki, obviously). That does not mean that it makes sense to collect this information (in this app).

Also, this guideline. Even if it was possible to accurately crowdsource the information about roof materials, there is to date no useful application for that out there except maybe 3d representation of a building.

**Comment by tobylorenz** [comment]
I read the guidelines. But I wasn't able to find the mentioned template. Can you reference the issue template from the guidelines? ;-)

> there is to date no useful application for that out there except maybe 3d representation of a building.

Exactly. https://osmbuildings.org/ provides nice 3D diagrams of my town. What's inadequate is mostly the roof shape, covering shape and roof color. As my town is a little hilly, it's not a problem to see how the roofs look like here. The only thing I often cannot judge, it the material it's made of.

But ok, there are still plenty of quests lefts, although I answered already >2000 of them ;-)

**Comment by tobylorenz** [comment]
Ah, I see, the difference is "Feature request" vs "Quest suggestion" on ticket creation. Yes, now I found it.
