### ISSUE TITLE
New quest - can you overtake on this road?

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#2492]
### General
Affected tag(s) to be modified/added: [Key:overtaking](https://wiki.openstreetmap.org/wiki/Key:overtaking)
Question asked: **Is is possible to overtake on this road?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
Probably all highways smaller than trunks/primaries but larger than service/residential.

**Metadata needed:** 
There may be countries where overtaking is always legal. Asking about overtaking would also most probably only make sense in the case of roads with marked lanes where lanes = 2.

**Proposed GUI:**
A GUI similar to the sidewalk UI could be used, where the user selects the kind of markings for forward and backward lanes. Alternatively, it could just be a question with "yes, no, no markings, yes for forward, yes for backward" answers.

**Comment by matkoniecz** [comment]
Is this tag used anywhere or even potentially usable (except "hyperdetailed 3D renders from OSM data")?  Even AB Street is not getting close to using it.

**Comment by westnordost** [comment]
But

> 💤 Not an overwhelming percentage of elements have the same answer (No spam)

**Comment by Atrate** [comment]
> But
> 
> > zzz Not an overwhelming percentage of elements have the same answer (No spam)

At least where I live it varies between "yes" and "no" pretty equally.

> Is this tag used anywhere or even potentially usable (except "hyperdetailed 3D renders from OSM data")? Even AB Street is not getting close to using it.

Wouldn't be surprised if routers gave it a very, very small weight when the tag gets more popular. Now that you mention it, AB street may actually try to use it creatively.

**Comment by westnordost** [comment]
> Wouldn't be surprised if routers gave it a very, very small weight when the tag gets more popular. Now that you mention it, AB street may actually try to use it creatively.

Well, ABstreet is mostly about city planning while no-overtaking restrictions are usually to be found on country roads in my experience, so it is not that relevant for ABstreet.

I'd say it is relevant for navigation apps that would display the appropriate sign when on that section of road.

However, the spam problem and the useful purpose aside for a moment, could you link a google maps location where such a overtaking restriction would be in place?

**Comment by Atrate** [comment]
> could you link a google maps location where such a overtaking restriction would be in place?

Do you mean just provide a street that has overtaking restrictions? I thought they were quite common but here's one: https://www.google.com/maps/@49.9161643,20.1923962,3a,75y,324.1h,67.02t/data=!3m6!1e1!3m4!1sEzc7sUXSsPj4jdQcxsvc_g!2e0!7i13312!8i6656

**Comment by westnordost** [comment]
Interesting, I would have expected that there is a sign. But the other thing I expected is there - the continuous (double) line. So it is the same as in Germany. 

I think then it is much more efficient and precise to record this data from satellite imagery at home. (That's one point in the quest guidelines too)

**Comment by Atrate** [comment]
I guess we gotta wait for better quality aerial to become available :/

**Comment by naposm** [comment]
In Italy we have this sign for cars
![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Italian_traffic_signs_-_divieto_di_sorpasso.svg/300px-Italian_traffic_signs_-_divieto_di_sorpasso.svg.png)
and this one for trucks / hgvs:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Italian_traffic_signs_-_divieto_di_sorpasso_tra_autotreni.svg/900px-Italian_traffic_signs_-_divieto_di_sorpasso_tra_autotreni.svg.png" width="300" />

They are useful when roads have no lane markings (in rural areas or small towns).

**Comment by westnordost** [comment]
> I guess we gotta wait for better quality aerial to become available :/

Okay, bad aerial coverage would be an argument in favour of this quest in StreetComplete - after all, I also implemented the lanes quest. However, the other issue would be the spam problem, which is why I don't see this quest right now for StreetComplete.

**Comment by naposm** [comment]
> However, the other issue would be the spam problem, which is why I don't see this quest right now for StreetComplete.

How about asking this only for tertiary and residential roads which are not oneway and have 2 lanes (so 1 lane each way) or without lane markings(of course this should be asked after the lanes quest and the oneway one if applicable). This would reduce spam by a lot. Also, this information could later be used for other future quests [I propose (informally as an idea) hgv allowed streets, but I think there are better uses for sure]).

**Comment by westnordost** [comment]
Plus exclude roads in built-up areas. Yeah. But there is yet another problem, related to "less efficient than doing it with aerial imagery": It is very unlikely that the section for which the prohibition for overtaking applies is already split up correctly when a user with StreetComplete arrives. So he'd have to split it up first. Since this is on the country-side, it is likely that he is a passenger in a car/bus and that he may not have the best internet connection. So it will possibly be quite challenging to do the splitting correctly/accurately, plus he likely needs to return to the same location later to do the actual answer for the split up paths because of the way the splitting works technically.
