### ISSUE TITLE
new quest - bike parking access 

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#2496]
### General
Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access)
Question asked: **Is it restricted who may park their bike here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
see below
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
see below
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

About the "no spam" and "useful purpose" points:

A few years ago, I would have considered this quest spammy. Most bicycle parkings were either public, or for customers. I didn't know any case where a shop owner checked if their bicycle parking was really only used by customers. Thus, the access tag wasn't really necessary.
Now I see some change here. Many newly-built apartment or office buildings come with bicycle parkings, only for their residents/employees. Where I live, in the Ruhr Area, we're just at the beginning of this process. But having a look at advanced countries like Denmark, this will develop rapidly.
Even in areas where there are very few private bicycle parkings (yet), they're at least divided in public/customers. Once the bicycle may become more popular with the masses, shop owners may start enforcing to have their parkings used by customers only. So tagging this here is also useful.

### Ideas for implementation
 identically to the car parking access quest

**Element selection:** 
`amenity=bicycle_parking and bicycle_parking!=informal and (!access or access=unknown`

**Metadata needed:** 

**Proposed GUI:**
can be copied from car parking access quest, solely the question itself should be changed.

**Comment by westnordost** [comment]
Makes sense to me. Just like with playgrounds, people tend to map bicycle stands from aerial imagery (if it is detailed enough) and then of course, it might turn out that many (or some) of these are actually not public.

**Comment by matkoniecz** [comment]
In Poland it would be extremely spammy for now, with bicycle parkings mapped rather on survey.

**Comment by Helium314** [comment]
The _element selection_ would have to be severely limited to avoid spam, maybe to shed/locker/building types.
I can't remember seeing any stands or wall loops that have limited access. Even if it's obviously intended for customers I never saw this explicitely signed (prohibited for non-costumers).

**Comment by DerDings** [comment]
> The _element selection_ would have to be severely limited to avoid spam, maybe to shed/locker/building types.
> I can't remember seeing any stands or wall loops that have limited access. 

I strongly disagree. Most mapped but private bicycle parkings I know are stands or wall loops. Some of them are not even covered. ([have a look](https://overpass-turbo.eu/s/12pS))
Most shed/locker/building bicycle parkings should be access=yes + fee=yes, sometimes even maxstay=*, but not private. They're somewhat equal to multi_storey car parks, which may be privately operated but are publically accessible.
For sure there are private shed/locker/building bicycle parkings, but most of them aren't mapped at all, because we don't map what's inside private buildings.

>Even if it's obviously intended for customers I never saw this explicitely signed (prohibited for non-costumers).

This may indeed be a problem. If they are located together with a parking area for cars I would consider a "parking for custstomers only" sign to be effective to any kind of vehicle. 
If there is no sign (e.g. signed customer car park behind the shop but unsigned bicycle parking next to the door), I would consider it as public.
Since as stated bicycle parking strain is increasing in many places, those signs may be added later. But if resurvey intervals for this quest aren't too long, I think we can deal with that.


Note that there are also some car parks not clearly signed where mappers need to assume, so they can do for bicycle parkings as well.

**Comment by Helium314** [comment]
> I strongly disagree. Most mapped but private bicycle parkings I know are stands or wall loops. Some of them are not even covered.

Here I strongly disagree, as I actually remember only two cases where I possibly got a quest for a private bicycle parking, both were sheds.

I Used your overpass query to look at a few cities, and it seems that usually 2-3% of bicycle parkings are tagged as private, so I guess this would not count as spam.
My 'usual' area has 0.2% tagged as private, which is why I see it as spam.

**Comment by DerDings** [comment]
I'm very happy to see parts of this introduced with #2507 so fast 🚀.

I still think there is a need in some places to make the filtering less exclusive than `bicycle_parking ~ building|lockers|sheds`.

From my point of view, it is difficult to derive additional indicators from current osm data like in #2507, because there are many cities where bicycle parking access isn't tagged at all. Among those cities is Copenhagen, which is very preceding regarding bicycle infrastructure. 
So other sources need to be found. 

One could imagine that `covered` places are more likely to be private, but in my experience, there are a lot of non-covered but staff-only (and thus `access=private`) bicycle parkings.


Another approach is to keep the strict filtering as a default, and define some countries where all bicycle parkings are asked for.

Private bicycle parkings are often added as a part of "[green building](https://en.wikipedia.org/wiki/Green_building)", meaning constructing or refurbishing buildings with sustainability in mind. There are many different national rules and standards for this, but two of them are standing out:
- **[BREEAM](https://www.breeam.com/discover/technical-standards/)** - UK-based, but internationally used. Has national operators in the Netherlands, Spain, Norway, Sweden and Germany [[1](https://en.wikipedia.org/wiki/BREEAM#National_operators)]. ([Example what it may say on bicycle parking](https://www.breeam.com/NC2018/#07_transport/tra02_a.htm#Cycle))
- (**LEED** - US-based, but I can' find out if it says something on parking spaces)
- **BNB** Germany-based, clearly says something about bicycle parking spaces number and quality. I couldn't find the details, though.
- ...

So it may be reasonable to start the country whitelist with the UK, NL, ES, NO, SE, DE, and add more countries based on further feedback here or in later issues.
