### ISSUE TITLE
Upload all quests into one changeset

### ISSUE THREAD

**Issue by martinstingl** [streetcomplete/StreetComplete#2498]
Can you please add an option to upload all solved quests into exactly one changeset?

Currently for each category containing solved quests there is created an extra changeset.

**Comment by guerda** [comment]
There was a discussion four years ago.
https://github.com/streetcomplete/StreetComplete/issues/21

Simple summary: It's a feature and Tobias does not see any value to collect single changes into a larger change set.

**Comment by martinstingl** [comment]
It is annoying to me because in the list of my changesets the normal changesets gets concealed under the huge amount of the ones from StreetComplete.

The current behaviour prevents me (and many more for sure) from using this app.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/21#issuecomment-292709936

> Thus, The only gain I see from grouping all solved quests within a survey together is to have less changesets. But it is not the goal to have as few changesets as possible, but to lay them out in a meaningful, descriptive way. The type of changeset that must be avoided are those that seem to hide certain (very different) changes within a larger set of harmless changes. Not saying that would be the case, my point is that the goal should be to have as meaningful changesets as possible, not as few as possible.

> The type of change can be told apart on first glance by people doing QA: they can focus on checking those quests that are known to sometimes be misunderstood and/or critical things such as street names

> Possibility of programmatically and reliably reconstruct what changes (what =quest type) any user exactly did from the OSM change history alone, without the need to either add "proprietary" tags to elements (god forbid) or somehow transfer analytics data to a third party. A must for statistics and (thus) finding systematically introduced errors (don't need to be bugs, may be systematic misunderstandings).
