### ISSUE TITLE
No quest for roof shape, if roof:levels=0

### ISSUE THREAD

**Issue by tobylorenz** [streetcomplete/StreetComplete#2499]
Normally, when I answer the quest "How many levels does this building have?", I get as next quest "What basic shape does this building's roof have?". However this only works, if roof:levels > 0.

I understand that the roof shape is only asked under the condition "roof:levels=*".
But it seems that "roof:levels=0" is handled the same as if this key isn't set at all.

**How to Reproduce**
Set roof:levels = 0, and the quest for roof shape is not showing up.
Try the same with roof:levels > 0, and the quest for roof shape is shown.

**Versions affected**
I'm using StreetComplete v29.0 currently.

**Comment by westnordost** [comment]
In which country?

**Comment by westnordost** [comment]
Ah, nevermind. For technical reasons, it will not show right away after solving the building levels quest, but later (next time the area is downloaded).

**Comment by tobylorenz** [comment]
You close issues so fast, you didn't even give me time to confirm that it's actually solved!

I just tested it again. Roof shape quests come up immediately, after setting the roof:levels. But if it's 0, it never asks for the roof:shape. To me this doesn't seem to be a question of download or cache behavior.

I looked in the code and I think the issue is here:
https://github.com/streetcomplete/StreetComplete/blob/ebde7be170c9734a02145d29d6444a14ca58d855/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShape.kt#L33
It just checks, if roof:levels != 0. But according to your quest documentation, it should check, if the root:levels is set, even if set to 0.

So do we have a bug or not?

**Comment by westnordost** [comment]
We don't have a bug, see my last comment.

**Comment by westnordost** [comment]
Trust me. I didn't just close the bug 2 hours ago, I actually looked in the code myself too

**Comment by tobylorenz** [comment]
> For technical reasons, it will not show right away after solving the building levels quest, but later (next time the area is downloaded).

Yes, I read it. Now, second time ;-)
Although I don't understand why the download/update behavior is then different in my experience for roof:levels=0.

> We don't have a bug, see my last comment.

Ok, accepted. Thanks.

**Comment by westnordost** [comment]
`getApplicableElements` is called on download, `isApplicableTo` is called after each upload. On download, more information is available, i.e. the geometry of that element and others.

**Comment by tobylorenz** [comment]
Yeah, my issue is that I don't understand Kotlin yet.

I would have expected a query like `get("roof:levels") == null`. But in fact it asks for `get("roof:levels") == "0"`. 

And this looked somehow contradicting to the documentation here:
https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

Because this doesn't say anything about "0". It just says the quest is asked, if `roof:levels=*`, so != null.

**Comment by westnordost** [comment]
Good point, I updated the documentation in the wiki
