### ISSUE TITLE
Export nearby quests to PDF for printing

### ISSUE THREAD

**Issue by odanoburu** [streetcomplete/StreetComplete#2500]
answering quests is best done on/after a survey, but sometimes it's not possible or not desirable to have a phone on you while out in the street. you could memorize quests or write them down on paper, but being able to export and print them automatically should be easier.

**Use case**
- in some urban areas in some parts of the world it's not safe to display a mobile phone out in the street (specially at night, and at least one quest should be done at night for reliable results)
- in poorer parts of the globe not everyone might have a smart-phone (although this is increasingly rare), but mapping would still be useful and one could have several people filling paper quest-surveys and one person entering them on street complete in a single smart-phone.

**Proposed Solution**
exporting all the quests in a given area to a print-friendly PDF. (there might be other/better options)

I do realise this might not be very high-priority since it's a bit of an uncommon problem and there are good-enough low-tech solutions (the aforementioned memorization or writing down on paper), so I'm mostly just throwing the idea out there in case it's not too difficult to implement or if it's more common of a problem than I thought.

**Comment by westnordost** [comment]
Whoa, that is an exotic suggestion...

I think the right tool for the use case you describe would actually be to print out a standard OSM map and then fill in the blanks in that map. There is even a service for that, check out https://wiki.openstreetmap.org/wiki/Field_Papers
But you may as well just generate the PDF from the openstreetmap website and use that as a base.

**Comment by westnordost** [comment]
Another kind of survey I tested a few years back which was also quite efficient to survey street-side-things was this:
Use a small notebook, start your survey at a predefined point, then walk down the road and note down everything you see on the way (on the side you are walking). When you turn a corner, cross an intersection etc. note that down. You'll end up with a list of linear things that may look like this ("-"  means new house)

```
-
34   Denn's Biomarkt
garbage bin
36
-
38 - Lecker Schlachter
-
40
-
construction site (42-50?)
====
Danneberg Road, continuing on straight...
====
park, dogs allowed
playground, part of park, two bins
-
```

You get the idea. What kind of things you note down depends on the focus you want to set.

**Comment by westnordost** [comment]
Also, finally you could use an old and cheap smartphone, maybe partly broken one, not your main one. The app works with Android versions down to 4.2

**Comment by odanoburu** [comment]
> Whoa, that is an exotic suggestion...

yeah, sorry about that :sweat_smile: 

thanks for the alternatives! I think I'll go with the low-tech solutions indeed

**Comment by rhhsm** [comment]
Some interesting read on the importance of good maps for the "developing world" [https://www.bbc.com/news/business-52650856](url)
