### ISSUE TITLE
recycling quests: clear/colored glass, carton

### ISSUE THREAD

**Issue by NESC1US** [streetcomplete/StreetComplete#2502]
**Use case**

recycling quest is missing local features such as specific containers for clear and colored glass, tetrapack cartons, and old toys containers which are often together with containers for old clothes.. what do you think?
**Proposed Solution**

**Comment by FloEdelmann** [comment]
In which countries are those containers common to find?
I've never seen them (in Germany).

**Comment by Helium314** [comment]
I Austria separate containers for clear and colored glass exist in some places, but I can't remember ever seeing one type without the other.

**Comment by NESC1US** [comment]
Czechia or Czech republic or whatever we should call this place now... (what do you like more?)

> I Austria separate containers for clear and colored glass exist in some places, but I can't remember ever seeing one type without the other.
hmm, thats a good point, most of the glass recycling containers I seen are as two containers, one internally separated, or less often just a colored one.

**Comment by rhhsm** [comment]
The Netherlands also has separate collection of brown, green and clear glass 
![image](https://user-images.githubusercontent.com/69100427/104749616-b11c6280-575b-11eb-94a1-dd924e890b98.png)

**Comment by FloEdelmann** [comment]
Oh... Of course we have that separation of glass colors in Germany :facepalm: 
I don't see the point of having that distinction in OSM though. When a recycling center has `recycling:glass_bottles=yes`, there will be either one general glass container (for all colors) or separate glass containers for all colors. Why would it be interesting to have that information?

Tetrapack cartons and old toys is a different story though.

Just for reference, a related discussion: #2156

**Comment by westnordost** [comment]
@NESC1US , are there containers specifically only for tetra pack containers, or any kind of packaging?

Can you show some pictures of these toy containers and tetra pack containers?

**Comment by westnordost** [comment]
ping

**Comment by NESC1US** [comment]
here's your ![tetra trash can](https://user-images.githubusercontent.com/15976294/106400221-6cf8b580-641d-11eb-82d4-90a3019def95.jpg)
