### ISSUE TITLE
Outdated building shape

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#2503]
I found a building which needed to be split up into 3 parts (consisted of 3 separate single-family homes), which I did in iD by reducing the size of one of them to correspond to the area of the northernmost, and adding 2 more for the homes south of it. New quests for the newly created buildings appeared in SC, but the shape of the original building remained unchanged. Because I wasn't sure what the effect would be of answering the quest on the original building shape, I only answered the ones on the new shapes where it was clear to which building they corresponded. It shows on my screen like this now 
![Screenshots_2021-01-15-17-29-32 1](https://user-images.githubusercontent.com/69100427/104748140-09526500-575a-11eb-99a4-6745f06119b1.png).
Maybe not a bug, but not very elegant...

**How to Reproduce**
Split building (in iD for instance) by reducing the area of the original building to correspond to one of the parts of the building, and add new areas as required.

**Versions affected**
Android 10 and StreetComplete v29.1 on LG Q60

**Comment by westnordost** [comment]
Just to understand:
- You split it up a building into several buildings
- the original building still exists but with a smaller outline
- quests for the new buildings were created
- quest for the old building remained. when tapping on it, it still has the old outline

Correct?

**Comment by rhhsm** [comment]
Yes. The original building is way 174629216, what I did is found in changeset 97489694
