### ISSUE TITLE
improvement of quest "Does it still exists?" for objects mapped on a different layer

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#2505]
The quest "Does it still exists" is asking for objects which can be mapped on different layers. A typical example are phones.
They can be mapped on "normal" street level (no layer) as well as with layer property assigned (e.g. -1; phone on underground level).
To avoid confusion and erroneous deletion of existing objects, in case of the asked object has a layer property assigned the layer should be displayed in the quest as well to indicate that the object is on a different level/layer.

**Versions affected**
Android 5.1 / StreetComplete v28.1

**Comment by Lukas458** [comment]
Yeah, I agree. Here was also a misinterpretation because the level=* key was not taken into account: https://www.openstreetmap.org/note/2466265

Another quest, but also such misinterpretations could be solved by displaying the layer.

**Comment by westnordost** [comment]
Good idea, I implemented it like this now:

![image](https://user-images.githubusercontent.com/4661658/104815724-88a56e80-5816-11eb-80e9-acca5c6c539b.png)

I also took the liberty to put the fix into my time machine so it will have been available since about 2 years. You are welcome!

**Comment by Helium314** [comment]
Since apparently a significant part of people ignore the level even though it is displayed, the are-you-sure popup could also warn if the object to delete has some level/underground tag.
But is it likely that people ignoring the level in one place will actually see it in the other? Not sure...

**Comment by riQQ** [comment]
Maybe the text is not clear enough. What do you think about: "not at ground level (level 2)" or "below ground level (level -1)" / "above ground level (level 2)"?

**Comment by smichel17** [comment]
Imo the only way you can do this in a way that people won't ignore AND won't be annoying is to visualize it on the map. This is where people are looking to determine which element they are looking at.

To start: how about relocating the "level" blurb to either right above or below the active pin? I think we are updating the objects shown on screen (adding the highlight) anyway, so this should not have an effect on re-rendering performance.
