### ISSUE TITLE
bike parking fee 

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#2507]
### General
Affected tag(s) to be modified/added: [fee](https://wiki.openstreetmap.org/wiki/Key:fee)
Question asked: **does it cost a fee to park a bike here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
only if thoughtfully filtered
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
 identically to the car parking fee quest

**Element selection:** 
`amenity=bicycle_parking and access!~no|private and (name or bicycle_parking~building|lockers|shed or capacity>=100) and !fee and !fee:conditional`

I know most bicycle parkings dont't cost any fee, so I did some research.
I queried all bicycle parkings somewhere in central europe (with a bbox that didn't make overpass-turbo complain about the amount of data. I didn't record that, it was somewhat the size of France+Germany) with a given `bicycle_parking` tag to a csv file. Then I did some computer-noob level excel analysis. I excluded all Items tagged with `access~no|private`. This is what I found out:

(0/grey: `!fee`; no/orange: `fee=no`; yes/blue: `fee and fee!=no`) data: © OpenStreetMap contributors, obtained 2020-11-30
1. named bicycle parkings are likely to cost fee 
![grafik](https://user-images.githubusercontent.com/42044179/104765158-bcc25600-5768-11eb-9d10-5d0f7d89a61a.png)
0: `!name`, 1: `name`

2. within the _unnamed_ bicycle parkings, `bicycle_parking~building|lockers|shed` have a notable share of items with a fee. 
![grafik](https://user-images.githubusercontent.com/42044179/104765195-ce0b6280-5768-11eb-92ad-6e65c3a81b24.png)

3. within the _unnamed_ bicycle parkings which are _not_ `bicycle_parking~building|lockers|shed`, the larger ones (103<capacity<153) are likely to cost a fee. 
![grafik](https://user-images.githubusercontent.com/42044179/104765234-df546f00-5768-11eb-9223-7de670257f53.png)
 Since there's not so many large bicycle parkings, I'd combine the upper categories to everything >=100.

**Metadata needed:** 
I don't think so

**Proposed GUI:**
can be copied from car parking fee quest, solely the question itself should be changed.

**Comment by Atrate** [comment]
I second this proposal, fee information for very large bike parkings is highly useful

**Comment by matkoniecz** [comment]
Thanks for research! Is it actually useful to ask it for small `bicycle_parking~building|lockers|shed` ?

> within the unnamed bicycle parkings, bicycle_parking~building|lockers|shed have a notable share of items with a fee.

Is it happening also if you exclude large ones? I suspect that big size may be the best signal.

**Comment by peternewman** [comment]
I think you might find this varies by country. In the UK for example in the Greater London type area, ~550 with fee=no versus 41 with fee=yes (and one of those should actual be rental I think).

Although about ~10,000 without it tagged as yes or no.

I think they generally want people to cycle rather than drive, so e.g. all the big areas next to stations are free, so you cycle to the station then get on the train.

**Comment by DerDings** [comment]
> 
> 
> Thanks for research! Is it actually useful to ask it for small `bicycle_parking~building|lockers|shed` ?
> 
> > within the unnamed bicycle parkings, bicycle_parking~building|lockers|shed have a notable share of items with a fee.
> 
> Is it happening also if you exclude large ones? I suspect that big size may be the best signal.

Yes, it is. 
This is the shares by bicycle_parking when excluding those larger than 103 spaces:
![grafik](https://user-images.githubusercontent.com/42044179/105045088-c8af6000-5a67-11eb-9db6-2cd220df1abc.png)
There is nearly no change for lockers and sheds, and only a small decrease for buildings.
When also excluding those where capacity isn't tagged at all, it looks like this:
![grafik](https://user-images.githubusercontent.com/42044179/105045372-23e15280-5a68-11eb-8364-62151e79ad4d.png)
There are nearly no more buildings with a fee, but still nearly nothing changes with lockers and sheds.
Looking at this, I'd assume that buildings indeed must be big to cost fee. However, the capacity of those often isn't tagged, because it is difficult to count those from the outside.
That said, `bicycle_parking ~ lockers|shed` is really necessary because it doesn't depend on the capacity. So extending this to `bicycle_parking ~ building|lockers|shed` is easy.

For completeness, I re-checked the names as well. This is how it looks when excluding `bicycle_parking ~ building|lockers|shed` and high capacities:
![grafik](https://user-images.githubusercontent.com/42044179/105046364-4fb10800-5a69-11eb-9080-bc66deac87ea.png)
The blue bar is smaller than before, but still significant. So I'd keep this as an indicator as well.
