### ISSUE TITLE
New achievement: waymarkedtrails.org

### ISSUE THREAD

**Issue by theraser** [streetcomplete/StreetComplete#2510]
I just discovered this tool myself and find it really useful for all kinds of traveling/discovering marked routes at a place.

A short description could be: "A map for viewing and downloading marked trails for hiking, cycling, mountain biking, inline skating, horse riding and winter sport slopes."

**Comment by westnordost** [comment]
Ideas like that should better go into the forum. Maybe even create an own topic to collect ideas:
 https://github.com/streetcomplete/StreetComplete/discussions
