### ISSUE TITLE
improve quest "Check if element still exists" for newspaper vending machines

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#2512]
**Use case**
I want to suggest an improvement for the quest "Check if element still exists" for newspaper vending machines (NVM). There are NVM which have a name tag. Those ones display that name during the survey question. This is very helpful if there are two or more NVM next to each other.

But there are also NVM which do not have a name, but a brand tag. It would be nice to see the brand value in the survey question, esp. when there is no name tag of that node.

To show you what i mean, this is a NVM with a name tag:
https://www.openstreetmap.org/node/4192397931

And this one has no name, but a brand:
https://www.openstreetmap.org/node/4253350433

This is an example place, where you have three NVM next to each other:
https://www.openstreetmap.org/node/4253350433
https://www.openstreetmap.org/node/4253350432
https://www.openstreetmap.org/node/4253350431

**Proposed Solution**
Add the value of the brand tag to the question in case it exists and no name tag exists.

I fear there might be an impact on other survey questions of that "Check if element still exists" type I do not if that is a real problem and if yes, i do not know how to address this problem yet. Maybe make a separate quest only for NVM?

**Comment by westnordost** [comment]
Right, this was kind of missing

**Comment by peternewman** [comment]
It might also be worth falling back to operator and possibly network too.
