### ISSUE TITLE
[UX report] Recycling quest for residential trash, what to do? Simplified German version?

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#2515]
**Use case**

The [recycling material quest](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#recycling_material) has popped up for me.
Now, this is a waste bin for some residential buildings.

I was confused by that big list of options it offered me ([nearly the same screen as here](https://github.com/streetcomplete/StreetComplete/issues/1745))…
Also, I only know the terms "Biomüll", "Gelbe Tonne/Sack" and "Papiermüll" (all three buckets that were present at that location)…
And I have no clue on what to put in each thing – okay, paper trash and organic waste is quite obvious (though that oil question then its really a tricky question? Motor oil should not be put into organic waste, should it? But cooking oil should?)…
But I was really out of my depth when now judging whether I can put these things [in the "Gelber Sack"](https://de.wikipedia.org/wiki/Gelber_Sack), as we say in Germany – [okay it's known in English-speaking countries as well, apparently](https://en.wikipedia.org/wiki/Yellow_sack).
It [felt like this game of Zeit](https://www.zeit.de/wissen/umwelt/2018-08/muelltrennung-gelber-sack-infografik) when I've filled that quest and in the ends I still was unsure whether that is correct.

Furthermore, this thing is private only (for residents). so should not there be a "This is private" in the menu? Does not SC usually not ask for private things? Should not I then also select/tag this as private, as the information is of low value? (Okay, for residents or people who cough… circumvent… some security features there, it may also be useful… but hmm…)

**Proposed Solution(s)**

* First I was about to suggest that you could simplify the quest for German users, at least? Just ask whether there is one of three container types (and maybe general garbage, so six)… Then you could code that knowledge of what to put into each container (which is likely well-defined in Germany) into each bin.
* However, I saw https://github.com/streetcomplete/StreetComplete/issues/1745 then and I wonder whether the button was intended for me? Because this is not really for recycling – well, yeah, partially it is, but the wiki page lists `amenity=waste_disposal` as “A medium size disposal bin, typically for bagged up household or industrial waste“, which fits perfectly here. However, in my example I did never intend to choose that, because it's not at all for "_general garbage_", it's only for some selected items (I thought maybe a garbage can would be considered for general garbage, but not that…). So maybe the description could be changed or another item be added for household-related trash?
* If I should instead tag it as "private only" add an option for that…

I'm sorry for this less-structured report, I hope you can take some things to change out of it. As I'm still not entirely sure about the tagging scheme and what I am now expected to do there, I don't really know any other suggestions. Feel free to create separate issues and close this one.

**Comment by Helium314** [comment]
As you can see in you linked Wikipedia article, not even within Germany the gelber Sack is the same everywhere (in some places metal cans don't belong in there), so simple color coding is not possible.

I would answer _cans_ and _plastic packaging_ for the gelber Sack as it is described at Wikipedia, and not put any oil to _garden waste_ (even if it's organic... whether it's actually ok depends on how the waste is processed, similar to meat)

**Comment by rugk** [comment]
Well… okay… and then what in "Biomüll" (i.e. organic waste)? These oils?

**Comment by westnordost** [comment]
You have biomüll containers? 

Anyway, map what is on the ground. Does the container say cooking oil is accepted?  No? Then don't check that box.

On 18 January 2021 22:17:55 CET, rugk <notifications@github.com> wrote:
>Well… okay… and then what in "Biomüll" (i.e. organic waste)? These
>oils?>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/streetcomplete/StreetComplete/issues/2515#issuecomment-762474220

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Well… the container says nothing. Especially "Gelber Sack" is "Gelber Sack"…
That's why there is a huge "gap" of interpretation there…

> You have biomüll containers?

Of course…?

But yeah, it seems this is not a thing in whole Germany: https://www.nabu.de/umwelt-und-ressourcen/abfall-und-recycling/bioabfall/index.html

**Comment by rugk** [comment]
Okay, I see  [as here on some bins](https://de.wikipedia.org/wiki/Gelber_Sack#/media/Datei:M%C3%BClltonnen_diverse.JPG) there is a special listing of what you can put in, but that is not there anywhere, also even there it is only on the yellow bin (i.e. Gelbe Tonne) and not on the brown (Bioabfall), grey (Restmüll) or blue (Papiermüll).
Thus, if I could just select what bins (colors) there are, that would be a huge simplification. :smiley:

**Comment by westnordost** [comment]
>> You have biomüll containers?
>
> Of course…?

You are linking to the biotonne. Yes, individual households may have that. But this is not a public container.

In general, you are talking about the tonnen. They are not public, they are for inviddual households or at least for one (apartment) house.

**Comment by rugk** [comment]
Oh yes, so _actually_ that is wrongly tagged, is not it?

As indicated in the original issue:
> Furthermore, this thing is private only (for residents). so should not there be a "This is private" in the menu? Does not SC usually not ask for private things? Should not I then also select/tag this as private, as the information is of low value? (Okay, for residents or people who cough… circumvent… some security features there, it may also be useful… but hmm…)

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt - right now it is not filtering out tagged with `access=private` or `no` (no access based filtering from what I see).

If there are correctly tagged `amenity = recycling and recycling_type = container` with `access` where this quest should be hidden it may be useful to add it.

**Comment by rugk** [comment]
Ah yeah, then it's obvious why it asks this. [According to taginfo](https://taginfo.openstreetmap.org/keys/?key=recycling_type#combinations) 6149 elements (2.46%) do have some `access` tag, at least. (I guess most of these are `private`, because why tag it otherwise?)

**Comment by Helium314** [comment]
> You are linking to the biotonne. Yes, individual households may have that. But this is not a public container.

It's not Germany, but at least in some places there are Biotonnen not belonging to a single household, and (often) accessible for everyone: https://www.wien.gv.at/umwelt/ma48/beratung/muelltrennung/biogener-abfall/sammlung.html

Cooking oils should go there only if it's mentioned, because it's ok if the waste goes to a biogas plant, but bad if it goes to compost.

**Comment by westnordost** [comment]
Anyway, so this could be solved by not asking for private containers.
