### ISSUE TITLE
Ask for recycling_type=container if it's still up to date

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#2516]
### General
Affected tag(s) to be modified/added: [amenity=recycling](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling)
Question asked: Is the information about this container up to date? (What can be left here?)

This could be similar to the "What can be left here for recycling?" quest (or the same?). The reason is, that the "Is this still here?" (I don't know if it's asked for containers yet) just ask if the object still here and not if you can still leave the same trash as stored. 

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Proposed GUI:**

**Comment by matkoniecz** [comment]
It is asked already, though it is not asked for containers with unusual recycling materials - see https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt#L42
