### ISSUE TITLE
Selectable icon below "OK" button

### ISSUE THREAD

**Issue by cascafico** [streetcomplete/StreetComplete#2520]
Difficult to select/deselect answers.

**How to Reproduce**

When I select a recycle quest, at the bottom some selectable icons appear. When I select one of these, the rightmost icon is hidden by "OK" button, making change in select status very difficult.

**Versions affected**
v29.1

**Comment by westnordost** [comment]
You can pull up the bottom sheet

On 21 January 2021 13:36:05 CET, Giovanni <notifications@github.com> wrote:
>
>Difficult to select/deselect answers.
>
>**How to Reproduce**
>
>When I select a recycle quest, at the bottom some selectable icons
>appear. When I select one of these, the rightmost icon is hidden by
>"OK" button, making change in select status very difficult.
>
>**Versions affected**
>v29.1
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2520

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
