### ISSUE TITLE
Create and use wrapper for SQLite database

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2521]
Currently, all the DAO (data access objects) that are used to access and update data persisted into the app's SQLite database use Android platform classes (`SQLiteOpenHelper`, `SQLiteDatabase`, the cursor class etc) to access the data.

This has a few disadvantages:
1. Since the Android platform classes are only available in the Android SDK, the code for the DAOs must be unit tested on a device running Android (emulator or real) and not just on the development machine. 
    - This is slow
    - There is some weirdness and incompatibilities with Android unit tests with a mocking framework. See #2028 
2. The API for the SQLite database access are a little cumbersome to use.  Cumbersome enough in fact that I wrote some extension functions in \streetcomplete\ktx\SQLiteDatabase.kt. This code could instead be part of a convenience wrapper.
3. All the DAO classes and those classes that depend on them would be part of a core of the app that could be reused on other platforms such as iOS (#1892) if there weren't the dependency to Android platform classes

So, there are good reasons to do this even beyond point 3 (iOS port), thus it makes sense to do it even if it is unclear if there will ever be an iOS port. Likely it will not even add a lot of code as the code from the extension functions can be reused into the wrapper class(es).

**Comment by westnordost** [comment]
If anyone would like to have a go here, please ask me first. I am currently doing quite a lot of restructuring in the codebase at the DAOs, so there is potential for laborious merge conflicts.

**Comment by westnordost** [comment]
Got working on it now because it makes sense to do this together with implementing proper coroutines support in the app's architecture which in turn got more important because the in-dev version is quite a bit slower (more I/O operations) than the current live version.

**Comment by matkoniecz** [comment]
Is it merged already?

I am running right now into `java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.InstantiatorProvider2 (alternate: interface org.mockito.plugins.InstantiatorProvider)` and I wonder is it still expected to happen and is it useful to try resolve this.
