### ISSUE TITLE
Do not show name quest if road has name:right and name:left

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2526]
If a road is tagged with name:right and name:left, then my understanding is that that is correct tagging, and it should not also have a name tag. Therefore StreetComplete should not ask for the name of the road.

**How to Reproduce**
Go to a way with name:right and name:left tagged, but without name or noname tagged, e.g. https://www.openstreetmap.org/way/29017408

StreetComplete shows the name quest, asking for the name of the road.

I assume that this would add name or noname tag, without overwriting name:right and name:left, but I haven't actually tried it as fortunately I spotted it coming up on a road I had recently added those tags to.

**Versions affected**
StreetComplete 29.1
Android 10

**Comment by matkoniecz** [comment]
Good catch, thanks!

**Comment by westnordost** [comment]
Can someone provide a link to the wiki that states that if `name:left/right` is specified, no `name` should be specified?

Having always a name if the road has one or several names would be good for at least "backward compatibility", i.e. for all those data consumers that do not support the mentioned tag. Which should be.... almost every data consumer I know. At least, pretty much any map renderer.

**Comment by matkoniecz** [comment]
> Can someone provide a link to the wiki that states that if name:left/right is specified, no name should be specified?

Even if it should be specified, then using StreetComplete is not a good tool for that. Mapper is quite likely to be confused and miss one of sides, survey is not necessary and local community may have preferences how name should be specified (used separator and so on).

**Comment by arrival-spring** [comment]
I agree with the above, situations where the name is different on left and right are rare, but quite specific and in the places local to me, the road doesn't really have a name, but houses either side have different street addresses.

**Comment by BalooUriza** [comment]
> Can someone provide a link to the wiki that states that if `name:left/right` is specified, no `name` should be specified?

I don't think it's in the wiki, however, it seems intuitive to me that `name:[left|right]=*` is tagged, this is equivalent to `name=*`.

**Comment by westnordost** [comment]
Okay, fair enough
