### ISSUE TITLE
Tagging housenumber on a long terrace and text wrapping

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2527]
When tagging a comma-separated list of house numbers on a long terrace ( as per https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers ), the text auto-scales until it gets quite small. Then, when it's at it's smallest it obviously text wraps at some point and often some or all of the existing content will disappear (sometimes even within a number boundary), which is a bit concerning at first as well as being hard to read.

**How to Reproduce**
E.g. `301,303,305,307,` is the most that will fit. Trying to add the 3 of 309 appears to wipe all the previous input (but doesn't in reality).

**Possible fixes**
- Make it wrap onscreen
- Make the box get bigger as soon as you enter a comma (as it's no longer a single house number)

**Versions affected**
SC v29.1

Edit, I know in some cases I could use a hyphen, but it's potentially ambiguous, especially if e.g. a house has been split so it's actually 301,303A,303B,305 etc.

**Comment by westnordost** [comment]
Why not 301-309?

**Comment by peternewman** [comment]
> Why not 301-309?

> Edit, I know in some cases I could use a hyphen, but it's potentially ambiguous, especially if e.g. a house has been split so it's actually 301,303A,303B,305 etc.

**Comment by BalooUriza** [comment]
> Why not 301-309?

I believe this literal string could actually be read literally as a singular address in various parts of the US.  [Kevin Kenny confirmed this is the case](https://lists.openstreetmap.org/pipermail/tagging/2021-January/057920.html) at least in Queens, NY.

**Comment by mnalis** [comment]
Also in Croatia, but for smaller (usually single digit0 numbers only...  

So while housenumbers are usually postfixed with letter `a`, `b`, `c` etc., they are sometimes instead (or in addition!) tagged with extra `-1`, `-2` etc. at the end (so one can have `1-2`, `42-3`, and even things like `1a-2` -- none of which indicate ranges but are single housenumbers)

**Comment by westnordost** [comment]
Tried to fix this. Unfortunately, it cannot be done. Setting that the text field may have several lines doesn't work together with scaling.

**Comment by peternewman** [comment]
> Tried to fix this. Unfortunately, it cannot be done. Setting that the text field may have several lines doesn't work together with scaling.

That's a shame @westnordost . What about my alternative suggestion, growing the width of the box when you enter a comma, or at least when you do other answers, it has multiple house numbers (like the house name option does)?

Shouldn't it be a cantfix rather than a wontfix? :thinking:

**Comment by westnordost** [comment]
Hm, I must have overread this. I'll try this out

**Comment by westnordost** [comment]
I tried it out, it is only possible by 30px or so to not overlap with other elements on small screens and it would not solve the problem anyway, so still won't fix.

If you have a big chain of housenumbers on one house, I'd also consider leaving a note with pictures so it can be mapped more precisely later.

**Comment by peternewman** [comment]
> I tried it out, it is only possible by 30px or so to not overlap with other elements on small screens and it would not solve the problem anyway, so still won't fix.

I'm a bit confused @westnordost . When I choose "other answers" > "No house number but a name...", the box almost triples in width on my small screen (and still with some borders), the +/- buttons go (and I get a new subtitle). Can't we have a version of that for this issue?

> If you have a big chain of housenumbers on one house, I'd also consider leaving a note with pictures so it can be mapped more precisely later.

I'd agree that's the ideal end-game, but equally I'm assuming the routers can use the existing number data, so I'd like to add that data immediately. I assume you're not interested in adding an option where it add it and then opens a partially populated note for you to add the pictures for splitting it?
