### ISSUE TITLE
Add opening_hours:covid19

### ISSUE THREAD

**Issue by Larostos** [streetcomplete/StreetComplete#2528]
### General
Affected tag(s) to be modified/added: [Key:opening_hours:covid19](https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19)
Question asked: **Are there special opening hours during the coronavirus pandemic?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
In accordance with the tag, answers could be "same", "different", "it's closed" or "can't say"
* "same" just inserts value "same" to the tag
* "different" leads to the same input method used for "opening_hours=", to be inserted as values to the tag
* "it's closed" inserts value "closed", but there should probably be an info box above the answers, similar to the way it is with wheelchair accessibility, that "closed" really means completely closed, excluding takeaway or delivery
* "can't say" lets people leave a note or skip the question entirely.

I believe there's little value to letting users add the tags "open" or "restricted", as described inthe wiki, as the question is then probably best answered with "can't say" and left to other users.

One issue I see with this question is that the answers are subject to frequent change at short notice. This question might have to be answered differently every two or so months, depending on the country and region.

**Comment by FloEdelmann** [comment]
See also #1774 and #2270.
