### ISSUE TITLE
Add _checked to the set of keys considered for check_date

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2529]
**Use case**
While looking at some other tags, I've just discovered 251 uses of collection_times_checked:
https://overpass-turbo.eu/s/12JQ

I wouldn't be surprised if other people have done similar for other keys too.

Maybe also add date_checked, although that doesn't seem to be on a key:
https://taginfo.openstreetmap.org/search?q=_checked#keys

**Proposed Solution**
Add _checked to the set of keys considered for check_date

**Comment by BalooUriza** [comment]
Seems like for consistency sake, it make be worthwhile to change that value to `check_date=*` and remove the original `*_checked=*` tag when doing so, no?

**Comment by peternewman** [comment]
> Seems like for consistency sake, it make be worthwhile to change that value to `check_date=*` and remove the original `*_checked=*` tag when doing so, no?

Yep, the magic that's already in SC will actually go one better and if I check the collection times will delete that tag and add `check_date:collection_times`:
https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/test/java/de/westnordost/streetcomplete/data/meta/ResurveyUtilsTest.kt#L112-L133

**Comment by westnordost** [comment]
I decided not to do this. Reasons:
1. usage of `collection_times_checked` is miniscule. Looks like this might even be used by just one person.
2. that tag is a nonstandard way to refer to another key. Deleting keys with a regex of `.*_checked` might have negative side-effects that we cannot foresee now
