### ISSUE TITLE
[meta] bicycle infrastructure quest split: physical/legal

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2530]
After discovering some issues with legal definitions in different countries about the restrictions on sidewalks(see https://github.com/streetcomplete/StreetComplete/issues/2276) and having two different styles of cycle tracks in Germany (optional and mandatory ones) I think we should discuss how to restructure the quest in two separate ones:

Physical bicycle infrasture and Legal bicycle infrasture. 

While physical is basically pretty much what we got now, we need an additional legal one. 

Since legal systems are different for each country or state, we need to create a quest variant as we go to progress and implement each country - redundancies can obviously be merged here. 

As an example: In Germany we want to capture for cycle tracks which sign is valid for this part of the way. 

After which we can on one hand modify the cycleway tags to more precise ones and add the traffic-signs as numbers. 

We can ignore all cycleways (or roads with cycleways) which already got the traffic-sign numbers tagged. 

## How you can help:

Go ahead and create a new quest ticket for your country or state and let us know if the current quest for cycleways is accurately for your.

Please add if a legal cycleway quest is necessary and how the different options would look like tag-wise. 

Please make sure to read the [guideline on new quests](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete) before you post, for any additional detail you can provide.

/cc @westnordost

**Comment by peternewman** [comment]
> Go ahead and create a new quest ticket for your country or state and let us know if the current quest for cycleways is accurately for your.

Can I suggest rather than generating hundreds of issues for this one quest, something more collaborative would make more sense, see for example the GitHub discussions and the threading being used for Quest Preset use cases:
https://github.com/streetcomplete/StreetComplete/discussions/2457

Similarly if there was a discussion topic on this and a top level comment was created per country/state, people could reply to that if it needed discussion.

Or something like a Google Spreadsheet may help again if the quest format is already known enough that it could be used to export the metadata.

**Comment by RubenKelevra** [comment]
Yeah this makes more sense :)

**Comment by westnordost** [comment]
I'd prefer if you created an actual quest suggestion in the usual template, adding the note that this needs research about where such (and what) signs for declaring a cycleway mandatory exist. Maybe directly add a google spreadsheet for collaborative contribution of that information with sources and add an (example) research for for example Germany.

**Comment by matkoniecz** [comment]
It is also for me unclear which tags would be added by this new proposed quest ad which questions would be answered and how current quest would be split.

**Comment by westnordost** [comment]
So, please, as mentioned, create a new ticket for this using the quest template and write down what research work exactly is required. It may be best to start with an example how the research should be done. Maybe like this:

<table>
<tr><th>Country</th><th>Sign</th><th>Tagging</th></tr>
<tr><td rowspan="4">DE[1]</td><td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Zeichen_237_-_Sonderweg_Radfahrer%2C_StVO_1992.svg/90px-Zeichen_237_-_Sonderweg_Radfahrer%2C_StVO_1992.svg.png"/></td><td><code>traffic_sign=DE:237</code></td></tr>
<tr><td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg/90px-Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg.png"/></td><td><code>traffic_sign=DE:240</code></td></tr>
<tr><td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Zeichen_241-30_-_getrennter_Rad-_und_Fu%C3%9Fweg%2C_StVO_1992.svg/90px-Zeichen_241-30_-_getrennter_Rad-_und_Fu%C3%9Fweg%2C_StVO_1992.svg.png"/></td><td><code>traffic_sign=DE:241</code></td></tr>
<tr><td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Zeichen_239_-_Sonderweg_Fu%C3%9Fg%C3%A4nger%2C_StVO_1992.svg/90px-Zeichen_239_-_Sonderweg_Fu%C3%9Fg%C3%A4nger%2C_StVO_1992.svg.png"/><br><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Zusatzzeichen_1022-10_-_Radfahrer_frei%2C_StVO_1992.svg/60px-Zusatzzeichen_1022-10_-_Radfahrer_frei%2C_StVO_1992.svg.png"/></td><td><code>traffic_sign=DE:239,1022-10</code></td></tr>
</table>

[1] https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren

On the other hand, maybe linking to an appropriate page on the wiki is enough and quicker.
