### ISSUE TITLE
app crashes by some quests

### ISSUE THREAD

**Issue by MakiWolf** [streetcomplete/StreetComplete#2533]
**How to Reproduce**

When showing some quests in debug mode the app crashes

**It affects this quests:**
- Can you contribute anything to this note?
- Is this a oneway street?
- What does the (house) number ... belong to?

![issue](https://user-images.githubusercontent.com/73300633/105867344-4853a680-5ff5-11eb-987c-c6ea213bd322.gif)

**Versions affected**

Version: 30.0-beta1 Latest build from source code (26.01.2021)

**Comment by matkoniecz** [comment]
Yes, it is a debug-only test functionality.

This is useful only for some types of testing and appearing only in debug-only compilations - so crashes here are acceptable.

This specific quest is special as it relies not only on OSM data. If there is sane way to make it not crashing pull requests are welcomed.
