### ISSUE TITLE
Further reduce the number of cycleway quests for maxspeed=30 ways

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2536]
Hi there,

it's me again, still wondering why there are villages with many cyclingway quests in maxspeed=30 zones where other villages don't show them anymore. So I tried to find a pattern behind this and my current suspect is the following combination of tags:

```
maxspeed=30
zone:traffic=DE:urban
```
While this combination isn't widespread in general, there seem to be clusters where it occurs quite often. See [this Overpass turbo query](http://overpass-turbo.eu/s/12Vd).

However, this tag combination is necessary but not sufficient for the superfluous cycleway quests. See for example this screenshot:

![cycleway](https://user-images.githubusercontent.com/32601012/106252931-1f126080-6217-11eb-8acb-0c86389f825a.png)

For way 1 (= [OSM way 31774388](https://www.openstreetmap.org/way/31774388)) the cycleway quest is displayed while for way 2 (= [OSM way 31774385](https://www.openstreetmap.org/way/31774385)) it's not. If you compare the tags of these ways, the only difference is the "name" tag.

(BTW: Investigations like this are an additional use case for profiles! I wished I had a possibility to use a profile with no quests at all in order to deliberately activate just a single quest which would remove cluttering the display (and the screenshot) with quests irrelevant for this issue). 

(See also issues #2251 and #2486.)

The cycling cat

**Comment by westnordost** [comment]
It is not showing for Weisse Gasse because the footway branching off from Lindenstraße leading into the park is both almost parallel to the street for a few meters and close enough to the street that the algorithm decided that it might be a separately mapped sidewalk. The cycleway quest is thus not shown.

---

Regarding the `zone:traffic`:

I've looked at the code, the part of the filter that is relevant is 
```
highway = residential and (
  maxspeed > 30
  or (maxspeed ~ ".*mph" and maxspeed !~ "([1-9]|1[0-9]|20) mph")
  or $NOT_IN_30_ZONE_OR_LESS
)
```
and I guess what you would like it to be is
```
highway = residential and not (
  maxspeed <= 30
  and (maxspeed !~ ".*mph" or maxspeed ~ "([1-9]|1[0-9]|20) mph")
  and $IN_30_ZONE_OR_LESS
)
```

However, the `not` operator is not supported in the filter syntax. So far there hasn't been the necessity for it, plus back when the statements were still translated to overpass QL, it would have increased complexity by a lot.

For just treating contradictory data more cautiously, it is also not worth to implement.

Or is it not contradictory? Is the `zone:traffic` tagging actually meant to tag only the difference urban/rural? Well, we can't really say at this point because `zone:traffic` never went past the proposal process and there is no extensive description. taginfo registers about 4% of `zone:traffic` to be `DE:zone30`, so de-facto it is contradictory.

I will close this ticket, however if someone wants to implement the `not` operator for the element filter syntax because maybe that feature will come in handy later as well, the code is in the `de.westnordost.data.elementfilter`, the core of it is the parser which is at `de.westnordost.data.elementfilter.ElementFiltersParser.kt`

**Comment by cyclingcat** [comment]
Indeed, `zone:traffic` has been a proposal for almost 12 years now. The most elaborated description seems to be [this OSM wiki page](https://wiki.openstreetmap.org/wiki/Proposed_features/trafficzone). The tag combination in my examples could be read as "This is an urban road, so the the general default speed limit of 50 km/h for those streets applies. However, there is a separate 'maxspeed' tag which overrides the speed limit part of the more generic 'zone:traffic' tag, so the real speed limit for this street is 30 km/h".

But anyway, SC seems do behave different depending on the existence of the tag "zone:traffic". I dug a little into the code and found this snippet in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/meta/OsmTaggings.kt:

```kotlin
val MAXSPEED_TYPE_KEYS = listOf(
    "source:maxspeed",
    "zone:maxspeed",
    "maxspeed:type",
    "zone:traffic"
)
```


If `zone:traffic` is such a questionable, rarely used and unapproved tag, why do you take this tag into account at all? Would it be an idea to simply remove this tag from the above mentioned ```MAXSPEED_TYPE_KEYS``` list (don't know about any side effects though)?

The cycling cat

**Comment by westnordost** [comment]
It is not that rarely used.

**Comment by cyclingcat** [comment]
At least the combination with `maxspeed=30` seems to be quite uncommon. See the aforementioned Overpass turbo link: In most places there is not a single appearance of it while they occur in other places a little more often. It doesn't seem to depend on criteria like small villages vs. big cities or geographic regions, the usage of this tag combination looks quite arbitrary to me (maybe dependent on the local mapper communities, this would explain the occurrences in clusters).

At least all affected places will show the cycleway quest for many short residential streets (including dead ends) where the chance to encounter any kind of cycleways is next to zero. Some excellent examples are some regions of Lübeck or the small village of Starkenschwind (200 inhabitants, near Bamberg):

![Starkenschwind](https://user-images.githubusercontent.com/32601012/106310707-40e60480-6264-11eb-88f7-6119e57cba4d.jpg)

Anyway: Is there a reason for `"zone:traffic"` to be included into the filter expression at all? I searched the code for the identifier MAXSPEED_TYPE_KEYS and found it in the files **AddCycleway.kt**, **AddMaxSpeed.kt** and **AddWayLit.kt**.

The cycling cat

**Comment by cyclingcat** [comment]
So what is the user supposed to do if he faces the situation shown above? I see three possibilities here:

1. **Answer** all those cycleway quests, no matter whether it's useful or not. Definitely spammy, but at least restricted to some regions. It's also somewhat spammy in regard to superfluous tags in the OSM database, but you could argue "this is the way OSM works: every user can put any kind of tags into it". (Users knowing the local situation would be able do this even remotely.)

2. **Deactivate** the cycleway quest in those regions. Perhaps many users affected by this problem will do this (as I did during the few weeks before #2251 was implemented). People entering and leaving those region often will have to deactivate und reactivate this quest just as often with this strategy.

3. **Hide** all those quests. A tedious task, but at least a one-time one without the need to toggle this quest type often and without the risk to forget its reactivation (see point 2.)

Some villages in my home territory also show this problem (this was the trigger for my investigations) and speaking for myself, I tend towards solution 1 to get rid of this problem permanently. But how will other users living in affected regions decide? Perhaps it would be a good idea to rethink the necessity of the `zone:traffic` filter, at least for the cycleway quest, and, if necessary, implement a separate list (e. g. MAXSPEED_TYPE_KEYS_FOR_CYCLEWAYS) without the  `zone:traffic` entry just for this quest type. if this `zone:traffic` filter is really needed for the other two quest types.

The cycling cat

**Comment by riQQ** [comment]
I think the correct solution would be to tag the streets properly, if they are in a max speed 30 zone.

```
maxspeed=30
zone:traffic=DE:urban
```
is not enough to declare a 30 zone.

At the moment there are the following options one of the following options
| Tag | Amount | Tag key status | Tag value documented |
| --- | --- | --- | --- |
[source:maxspeed](https://taginfo.openstreetmap.org/keys/source%3Amaxspeed#values)=DE:zone30 | 72 507 | [in use](https://wiki.openstreetmap.org/wiki/Key:source:maxspeed) | ✅
[zone:maxspeed](https://taginfo.openstreetmap.org/keys/zone:maxspeed#values)=DE:30 | 60 458 | [in use](https://wiki.openstreetmap.org/wiki/Key:zone:maxspeed) | ✅
[maxspeed:type](https://taginfo.openstreetmap.org/keys/maxspeed%3Atype#values)=DE:zone30 | 37 744 | [in use](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type) | ✅
[zone:traffic](https://taginfo.openstreetmap.org/keys/zone%3Atraffic#values)=DE:zone30 | 6 199 | [in use](https://wiki.openstreetmap.org/wiki/Key:zone:traffic) | ❌

**Comment by cyclingcat** [comment]
Of course there are clearer ways to tag max speed 30 zones than using `zone:traffic=DE:urban` and overwriting the maxspeed part of it with `maxspeed=30`, but the SC user should never need to know about these tagging subtleties. He only sees the many cycleway quests in some regions and has to make the decision what to do with them.

The max speed quest is disabled by default (see issue #1281).

The cycling cat

**Comment by riQQ** [comment]
> Of course there are clearer ways to tag max speed 30 zones than using `zone:traffic=DE:urban` and overwriting the maxspeed part of it with `maxspeed=30`

`maxspeed=30` and `zone:traffic=DE:urban` on its own  is not a way to tag a max speed 30 zone. This is just incorrect or incomplete data.

In this case, how would StreetComplete know , if the data is correct or not?

**Comment by cyclingcat** [comment]
Hi,

so you think that a maxspeed of 30 shouldn't be sufficient to prevent this quest from being asked for a residential street, only do this for maxspeed 30 **_zones_**? I'm not sure which approach would be the superior one, but regardless of this: The mentioned tagging is reality in surprisingly many regions as shown in the examples above (screenshot and Overpass turbo query). In my opinion these regions are too many to ignore, and no matter if this is considered as valid tagging or not, the user cannot change it with SC, and in these regions you get flooded with this kind of quests. Here is an even more extreme example (it's Botnang, a district of Stuttgart; note the white circles which also represent cycleway quests as I deactivated all other quests before I made this screenshot):

![Botnang](https://user-images.githubusercontent.com/32601012/107155238-a1b5c100-6977-11eb-8a46-36316538ae68.jpg)


So the main question remains: **What do you want the user to do in those regions with dozens of cycleway quests in residential areas as shown in the screenshot above?** (I mentioned three possibilities [here](https://github.com/streetcomplete/StreetComplete/issues/2536#issuecomment-770370476), all of them unsatisfactory IMHO.)

The cycling cat

**Comment by westnordost** [comment]
Well, either ignore them or just answer them truthfully.

**Comment by smichel17** [comment]
> What do you want the user to do in those regions with dozens of cycleway quests in residential areas as shown in the screenshot above?

To be fair, while "dozens" is a lot, it is also… not a lot… (right is zoomed out from left)

<img src="https://user-images.githubusercontent.com/6563664/107156527-b5145c80-6976-11eb-9eee-aa24d6e67403.png" height="500"> <img src="https://user-images.githubusercontent.com/6563664/107156548-e12fdd80-6976-11eb-847d-0070913ec1ea.png" height="500">

**Comment by cyclingcat** [comment]
:smile::smile::smile:

Yes, I have seen similar pictures on my screen during a short period last year when I activated the building quests (which I'm normally not very interested in; I did this only because in the villages I regularly cycle through no other quests were left at that time. Fortunately the resurvey quests came some weeks afterwards.)

However, the situation described in this issue is somewhat different because the cycleway quests mentioned here are shown in regions where almost certainly no cycleways exist (residential streets with max speed of 30 km/h, often short, sometimes dead ends).

The cycling cat
