### ISSUE TITLE
Clarify that photos attached to a note are resized

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2538]
Photos attached to notes are resized to max. 1280x1280. This is understandable, but often reduces readability of text.

Since most recent phones have high resolution cameras where text on a small part of an image is still readable, people might be uploading photos where text would be readable in original size, but no after automatic resizing done by SC.

I suggest that the resizing is mentioned when attaching photos to avoid unexpected problems when trying to read text from notes with attached photos.

**Comment by westnordost** [comment]
There is soo much text already in the note input form

**Comment by Helium314** [comment]
I definitely agree, but sometimes I notice people uploading photos with text that is unreadable because of resizing (also did it myself once or twice)

Once a photo is added, the 'adding a photo will...' text disappears. Here something like 'photo(s) will be resized to 1280 pixels' could be shown.

**Comment by westnordost** [comment]
it disappears to make space for the attached photos

**Comment by mnalis** [comment]
Also see related https://github.com/streetcomplete/StreetComplete/issues/2497#issuecomment-760214653

**Comment by Helium314** [comment]
Right, implementing #2497 should solve this... I guess it would be a better solution anyway, so I'll close this issue
