### ISSUE TITLE
"Do these steps have a ramp?  What kind?"

### ISSUE THREAD

**Issue by osm-spiregrain** [streetcomplete/StreetComplete#2543]
When you encounter the "Do these steps have a ramp?  What kind?", the tag applied is something like ramp=yes, or ramp:stroller=yes, etc.   This tag is applied to the steps way.   However, in many cases there is a ramp that is separately-mapped already, and StreetComplete does not take account of this.   The naive user will think "yes, there is a ramp", and will tap accordingly.    But in such cases it is better to say that there is no ramp associated with the steps.   Routers and map-users will be able to find the separate ramp.

For example https://www.openstreetmap.org/way/119105768 these steps do not have a ramp, because there is a separate ramp.  (https://www.openstreetmap.org/way/613594534 ).  In this case the ramp is a significant piece of infrastructure.

A more minor case would be these steps - https://www.openstreetmap.org/way/621248077 which have this separate ramp: https://www.openstreetmap.org/way/621248088

I can think of three possible solutions-

1. StreetComplete could try to parse the surrounding ways, looking for separately-mapped ramps before asking the question.
2. The wording of the options could make it clear that if there is a separate ramp, the appropriate answer is to say No.
3. List the separate ramp as a different answer, and tag the steps way with ramp=separate.  (As described here - https://wiki.openstreetmap.org/wiki/Key:ramp )

**Comment by Helium314** [comment]
Are there really cases where stroller or bike ramps are mapped separately?
Your example looks like wheelchair ramp to me, and for those StreetComplete already asks whether it's separate (not sure how it's tagged in the end).

**Comment by osm-spiregrain** [comment]
Thanks for your response.  I've given two examples, which one do you mean?  Both of them have separate ways taking somewhat different routes from the step way that triggers StreetComplete.

I've not seen any cases where StreetComplete offers a "Separate" option for a ramp.  I get something like the attached.  
![Screenshot_20210131-195626](https://user-images.githubusercontent.com/42609760/106396214-73c40000-63fe-11eb-88ee-e54b23222d2c.png)

**Comment by Helium314** [comment]
Select wheelchair, tap ok, then select separate or not

**Comment by matkoniecz** [comment]
Can you give a photo of situation where stroller or bike ramps are mapped separately and are not a wheelchair ramps?

**Comment by osm-spiregrain** [comment]
@Helium314 - I hadn't realised that it was behind the wheelchair option.   Is there any reason that the other types cannot be separate?

@matkoniecz I can provide photos but not right away.   I'm also not clear on what the difference between the types of ramps are.  To me, if there is an inclined path running from the top of the stairs to the bottom (perhaps via some twists and turns), it's a general purpose ramp, not obviously dedicated to any user type.

**Comment by Helium314** [comment]
> Is there any reason that the other types cannot be separate?

For a bicycle ramp I would expect you need steps to walk on while pushing your bicycle, so can't be separate.
A stroller ramp probably could be separate, but if it doesn't have steps I'd probably identify it a (steep?) wheelchair ramp.

**Comment by osm-spiregrain** [comment]
@Helium314 So the intent of the ramp= tag on stairs is to capture ramps that are essentially part of the stair struncture, and run right next to the treads and risers (or top of them)?
