### ISSUE TITLE
Quest for describing `amenity=water` more specifically

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#2547]
### General
Affected tag(s) to be modified: [`amenity=water`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwater) (deprecated because it has an unclear meaning)
Question asked: **What kind of water place is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary.
      I have created a [MapRoulette task](https://maproulette.org/browse/challenges/15922) but noticed that it is difficult to map with only areal imagery. Especially water taps / pumps / wells are difficult to distinguish.
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam).
      Probably most will be water taps, but I have no data to back this up.
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort).
      Probably not; it's only 816 elements worldwide (see [Taginfo](https://taginfo.openstreetmap.org/tags/?key=amenity&value=water) and [Overpass](https://overpass-turbo.eu/?w=%22amenity%22%3D%22water%22+global&R)).

### Ideas for implementation

**Element selection:** `nodes, ways with amenity=water`

**Metadata needed:** None

**Proposed GUI:**

Image selection quest with these options:

* Water tap (`man_made=water_tap`)
* Place for filling fresh water tanks (`amenity=water_point`)
* Animal drinking place (`amenity=watering_place`)
* Natural spring (`natural=spring`)
* Fountain (`amenity=fountain`)
* Well (`man_made=water_well`)
* Prabably more?

---

Not sure if this is worth the effort, given that there are only 816 elements worldwide. But because it can't be solved otherwise, maybe we should give it a shot nevertheless? I'm open to your opinions.

**Comment by westnordost** [comment]
Yeah, ... that's really not worth the effort.

**Comment by matkoniecz** [comment]
Just 816 uses worldwide.

**Comment by westnordost** [comment]
So will not fix, not only because of the implementation effort but also the translation effort.

Additionally, your suggested options are just assumptions what the individual `amenity=water` *might* mean. But we don't know that, as that tag is so ill defined. So it may very well be that a considerate amount of these elements will not fit into any of these category and people will have to leave notes.
