### ISSUE TITLE
Change the theme to dark when the sun goes sets

### ISSUE THREAD

**Issue by Kezxo** [streetcomplete/StreetComplete#2550]
**Use case**

Often when I'm using the app with the theme set to "auto" it uses the light theme even though it is dark outside.

**Proposed Solution**

The auto theme setting should change it over to the dark theme when the sun sets and vice versa or there should be a separate sun-based theme setting.

**Comment by westnordost** [comment]
That's up to the system to the Android system to decide. What Android version do you have?

**Comment by Kezxo** [comment]
it does? 

I'm using 7.0.

**Comment by Kezxo** [comment]
My phone has a blue light filter setting that I have set to a custom schedule, it's not a dark mode so I don't have it set to the sunset but rather when I feel like it's getting late if that makes sense. It can be set to the sunset but that's a bit much for orange displays since I get about 8 hours of daylight these days..

 Is that what the auto setting use to switch the theme? I didn't expect that since it's not a dark mode sadly, wish it was.

I would still like the app to follow the sunset though regardless of my phone settings.

**Comment by westnordost** [comment]
Yes, it calls
```kotlin
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_AUTO)
```
if you select the "auto" option.

This automatically changes the mode between day and night based on the time and location. If this does not work, it is an issue of your Android system or maybe another app that interferes with this system behavior.

Starting with Android 9, there is a better night mode where you are able to set a preference (always day, always night, based on time of day) for the whole OS and by default all apps that support day and night mode will follow this setting automatically. StreetComplete also will.

**Comment by Kezxo** [comment]
That sounds great, shame my phone is stuck on 7.

It's now 19:46 and streetcomplete switched to night mode, 30 min ago when I posted this it was in day mode. It didn't care about the custom schedule to the blue light filter..

It's weird, I have never noticed another app use this weird schedule that was apparently from my phone all along. OsmAnd has a setting for sunrise that works real well.

Not sure what's going on but I will switch it manually then I guess.
