### ISSUE TITLE
Extra nodes are created on a map, when answering kerb quests if kerb is a line and road is an area

### ISSUE THREAD

**Issue by ksetdekov** [streetcomplete/StreetComplete#2552]
If a road is tagged as area=yes with a kerb as barrier=kerb as a separate way along the road edge, then StreetComplete ask a quests for each of the nodes of the kerb and edits individual nodes instead of the whole kerb way.

**How to Reproduce**

1.  Find a way that is mapped as an area ([example road](https://www.openstreetmap.org/way/676704608))
2.  Have a quest "Is there tactile paving on this curb here?" or "What is the height of this curb?" enabled.
3.  On the edge of the area=yes highway, there will be a different quest for each of the nodes of the kerb way. ([example kerb after answering quests](https://www.openstreetmap.org/way/676250804); [affected kerb before answering quests](https://www.openstreetmap.org/way/676250800);  [coordinates of an area with examples](https://www.openstreetmap.org/query?lat=55.75594&lon=37.64840)) 

**Versions affected**
Problems seen on:
- Pixel 3a XL, Android 11
- App - 30.0-beta1 and one previous version

**Comment by westnordost** [comment]
Hmm, interesting location. I've never seen a place where cerb barriers were used this extensively, but after all, why not.

The root problem here is that at the location where the `highway=footway` intersects with the `barrier=kerb`, StreetComplete thinks there is a kerb barrier here. It doesn't consider that the `highway=footway` there is an area
