### ISSUE TITLE
Lanes quest doesn't allow for multiple, unmarked lanes

### ISSUE THREAD

**Issue by opk12** [streetcomplete/StreetComplete#2553]
A road with more than one unmarked lane is a common real-world occurrence and [the wiki](https://wiki.openstreetmap.org/wiki/Key:lanes) tags it as `lanes=<count> + lane_markings=no`. With the current quest UI, clicking on unmarked lanes does not also ask for the count.

**Comment by opk12** [comment]
The quest should also pop up for `lane_markings=no` without a `lanes=<count>`, to complete roads tagged so far using the quest.

**Comment by HolgerJeromin** [comment]
See #2299 for problems with that.

**Comment by matkoniecz** [comment]
> See #2299 for problems with that.

Thanks! I was trying to locate it.

Though way to specify lane count in cases where it is clear and obvious would be nice.

Sometimes lane markings appear and disappear, splitting roads in tiny segments on every crossing is not helpful - tagging `lanes=2` on everything would be much nicer. (I have not created issue for that as I have not thought how to implement it)

**Comment by opk12** [comment]
#2299 is not related to this bug. Thanks, I did not see it. There are a few cases of #2299 in the heart of the biggest cities, but this is about everywhere else.

Unmarked lane number is usually self-evident and obvious for most roads here, at least in Italian urban areas.  The main reasons are age of the paint that disappears (due to poor road maintainance), heavy municipal economic interest in delimiting parking spaces, frequency of road maintainance (poor maintainance leads to fixing again and again). This is not about difficult answer or inappropriate parking.

**Comment by HolgerJeromin** [comment]
Solution of #2299 is the root cause for your problem.
There are some roads which are problematic to tag. So it was decided to drop lane tagging when there is no marking. 

We did not find a better way to not show the quest for tiny unmarked 5 meter wide roads (or tag them better) but still show the quest where we have clear lanes (what ever the markings are).

**Comment by westnordost** [comment]
So to summarize, @opk12:

1. Yes, it is reasonable to record the number lanes also for roads that have no unmarked lanes, there is no argument there
2. And yes, many such roads exist where the lanes are unmarked but the lane count is 4 and above
3. But, such roads as described in #2299 exist and it would be too much to ask of StreetComplete users to ask questions that cannot be answered without doubt, see quest guidelines for 
 >🐿️ Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible

If the road is large enough, it should also be possible to either see the lane count from aerial imagery or measure the width from aerial imagery precisely. This is currently the best and most efficient solution.
