### ISSUE TITLE
automatically invalidate an area when manual quest scan is initiated

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2554]
**Use case**
Many quests have dependencies on another quests and in many cases those do now show immediately after the prerequisite quest is solved, but take some time, in effect forcing user to take several resurveys of the same area in order to solve all the quests there. That is often inconvenient to user, leading to frustration.

Typical example: to fully map addresses one has to finish `addr:street` quest, but for that quest to show one must first solve `addr:housenumber`, and for that to show one must first solve `building` quest.

[Common workaround](https://github.com/streetcomplete/StreetComplete/issues/2474#issuecomment-757332552) (at least only one known to me is to do) to force followup quests to appear is:
- click menu, click "Settings", click "Invalidate quest cache",  click "Invalidate", click back
- click menu, click "Scan for quests here"
- only after that, new quest will become available

That is 7 clicks if executed in perfect order (ie. your finger doesn't slip) per refresh.

So in example above (just wanting to map housenumbers in virgin area) my current mapping session looks like:
- solve half a dozen quests to map `building`
- do 7-clicks-refresh
- solve half a dozen quests to map `addr:housenumber`
- do 7-clicks-refresh
- solve half a dozen quests to map `addr:street`
- walk 50-100 meters
- repeat

While in some cases it is **slightly less annoying** than having to visit same area 3 times on 3 separate days, it is far from ideal.

**Proposed Solution**

While ideal solution obviously would be for quests to appear automatically, that seems to require very much work (https://github.com/streetcomplete/StreetComplete/issues/1119#issuecomment-402692157).

As an easier workaround, to make needed procedure much less painful, I propose at least changing that 7-clicks-refresh to 2-clicks-refresh, that is:
- when user selects "Scan for quests here", before quests are downloaded for shown area, the area is first invalidated.

If that is not possible, those might be alternatives:
- alternatively, if invalidating just some data is also hard to program, invalidate all data on "Scan for quests here"
- alternatively, if invalidating all data is problematic for some reason in some cases, then split current "Scan for quests here" to 2 buttons ("Clear&Scan" and "Additive Scan")

It would help somewhat alleviate (without too much effort, hopefully) IMHO one of the two biggest problems StreetComplete has at the moment  (the other problem being not having easy way to switch between custom "presets" (https://github.com/streetcomplete/StreetComplete/issues/1654, https://github.com/streetcomplete/StreetComplete/projects/2 so users have to manually turn on/off lots of the quests all the time)

**Comment by westnordost** [comment]
A side effect of the layers implementation will be that quests will appear immediately even when a local change (not yet uploaded) is made.
