### ISSUE TITLE
Bridge height limit quest without a bridge

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2555]
Hi there,

here's again a strange one: A bridge height limit quest is displayed for a street without a bridge leading over it. See this screenshot:

![no_bridge](https://user-images.githubusercontent.com/32601012/107064413-c2491400-67db-11eb-97da-62e513ecb68a.jpg)

This is OSM way [57977064](https://www.openstreetmap.org/way/57977064), there's nothing bridge/tunnel/layer-related in its tags:

```
name=Aachbachstraße
smoothness=excellent
highway=residential
motor_vehicle=destination
surface=asphalt
```

However, there is a stream parallel to this street and some bridges branching from this street over the stream to the east (with `bridge=yes`  and `layer=1`). Don't know if this matters here.

(StreetComplete 30.0 on three devices with different Android versions.)

The cycling cat

**Comment by matkoniecz** [comment]
Probably triggered by touching bridges: https://www.openstreetmap.org/way/685121399 https://www.openstreetmap.org/way/685121388 https://www.openstreetmap.org/way/108339631

**Comment by westnordost** [comment]
Ok, so exclude roads that only intersect with a bridge in an end node. Should be doable.

**Comment by westnordost** [comment]
If anyone else would like to fix this, the code is in 
[`AddMaxHeight.kt line 73-93`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeight.kt#L73-L93)
The unit tests for this would need to be extended by this case too.

**Comment by matkoniecz** [comment]
Though note that in this case OSM data is also incorrect anyway (though workaround for that still would be nice).

**Comment by westnordost** [comment]
Why is it incorrect?

**Comment by matkoniecz** [comment]
The bridge is not reaching centerline of road, right? The crossing with the east-west road at the bottom is not actually in half no the bridge?

See also https://wiki.openstreetmap.org/wiki/File:Bridge-Junction-Connection.png from https://wiki.openstreetmap.org/wiki/Key:bridge

**Comment by westnordost** [comment]
It's preferred, doesn't mean that it is wrong.

**Comment by westnordost** [comment]
Okay, can't reproduce this. The shown way does not have any maxheight quest.

Before v28.0, a quest would have been shown for this road. It is possible that this quest was created before v28.0 and not updated since. See #2370.

**Comment by cyclingcat** [comment]
Hm... strange. I got this quest on all of my Android devices, even on my Samsung tablet (Android 8.1) which I normally never use for StreetComplete (except for testing purposes). So I just double-checked it on this device:

- Cleared the cache and all data of SC in the Android app settings
- Started SC and disabled all quests except for the bridge height quest
- Panned to the map section shown in the screenshot and searched for new quests there

The bridge height quest reappeared immediately. The same procedure on my Cubot Quest (Android 9.0): The quest also appeared here!

I tried to find another appearance of this phenomenon and finally succeeded at [OSM way 128116943](https://www.openstreetmap.org/way/128116943). The situation is similar: It's a residential street parallel to a stream and near its northern end there is a small foot bridge over it which has a common node with the street.

The cycling cat

**Comment by westnordost** [comment]
So, you continue to be able to reproduce the issue with the way mentioned in the thread starter, even after clearing the cache and downloading the area again?

**Comment by westnordost** [comment]
Nevermind, I could reproduce it with way 128116943

**Comment by cyclingcat** [comment]
Can confirm that _both_ appearances of this quest are gone with SC v30.1. :+1: 

The cycling cat
