### ISSUE TITLE
Same answer for both sides of a street

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2560]
**Use case**
Many of quests ask about some feature which can be on one side or both sides of the road. Cycleway, sidewalk are two examples. It's common for both sides to have the same answer, however currently one must choose each side separately. This is time consuming and mundane.

**Proposed Solution**
For these quests the middle of the road should be tapable, when tapped the answer will be applied to both sides.

**Comment by westnordost** [comment]
How to top communicate this functionality to the user? What if he taps on it inadvertently?

Am 8. Februar 2021 09:26:58 MEZ schrieb Andrew Harvey <notifications@github.com>:
>**Use case**
>Many of quests ask about some feature which can be on one side or both
>sides of the road. Cycleway, sidewalk are two examples. It's common for
>both sides to have the same answer, however currently one must choose
>each side seperately. This is time consuming and mundane.
>
>**Proposed Solution**
>For these quests the middle of the road should be tapable, when tapped
>the answer will be applied to both sides.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2560

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andrewharvey** [comment]
> How to top communicate this functionality to the user? What if he taps on it inadvertently?

I think it would be fairly obvious, it's what I intrinsically attempted to do before realising it didn't work. Tapping inadvertently will help with discovery.

**Comment by mnalis** [comment]
While I can see the merit of allowing easier tagging of both sides to same value, I do not like proposed solution at all - especially as you say user is likely to click on the middle, then they would think that is the only  to tag, and we'd get mostly (probably wrongly) stuff tagged on both sides. But some other way which  

Also usability is probably country dependent - for example in Croatia, you'd in most cases find cycleway only on one side (and consider yourself lucky if you find it at all). Sidewalks are around 30% chance of no sidewalk, 30% on one side only, 30% on both sides...

**Comment by andrewharvey** [comment]
>  For example, having user input data on one side of the road normally, and then long pressing other side of the road to set it to same value as already mapped side?

I find that's not much more efficient than just selecting both sides, the goal here is to reduce time (taps, especially long taps) and increase accuracy (there is a small chance with each selection my fat fingers will hit the wrong selection, so less selections means less errors).

> and consider yourself lucky if you find it at all

Yeah some ridiculous high like 95% of the time I'm answering no cycleway, so having an option to say no for both sides at the same time is best.

> 30% on both sides...

30% is significant and such a feature would help 30% of the time

**Comment by FloEdelmann** [comment]
I often use StreetComplete on my bike with the phone mounted to the handlebar, so it's often a bit shaky.

Reducing the touch area sizes (because the street width is divided by three instead of two) would make tapping the right one more difficult.

I agree that an option to apply the same answer to both sides might be useful though.

**Comment by mnalis** [comment]
> I find that's not much more efficient than just selecting both sides, the goal here is to reduce time (taps, especially long taps) 

that is true, just one of alternatives that crossed my mind... Hopefully there are better alternatives.

> Yeah some ridiculous high like 95% of the time I'm answering no cycleway, so having an option to say no for both sides at the same time is best.

Perhaps the best would be to implement **"repeat same answer"** icon as we have for `How many levels does this building have?` quest? That would cover the problem even better (just one click to mark both sides as `no cycleway` if that was your previous answer, which seems likely if 95% of them are like that), AND it would reduce accidental user errors (mapping both sides with same value, even if only one side has that value).

And in addition it would cover another use case which just "same answer for both sides" solution wouldn't do - that is when road is split into many segments (eg. sidewalk only on left side of the road, but road is cut on 20 places, so I have to answer all road quests 20 times with same answers). 

> 30% is significant and such a feature would help 30% of the time

Sure, that's why I said I see the merit in this proposal

**Comment by mnalis** [comment]
> I often use StreetComplete on my bike with the phone mounted to the handlebar, so it's often a bit shaky.
> Reducing the touch area sizes (because the street width is divided by three instead of two) would make tapping the right one more difficult.

I agree - while I don't solve quests with mobile phone mounted on my bicycle handlebars, I have same problems on foot in winter with gloves on (which make fingers bigger _and_ reduces accuracy) - so I too am against reducing size of clickable areas.

**Comment by FloEdelmann** [comment]
> repeat same answer

See #2542.

**Comment by pulimento** [comment]
Perhaps we can add it to the "Other responses" button, with this options:
- Yes, both of them
- No, none of them
And tapping on either option will mark, as if the user will have selected manually. So you have visual confirmation of what are you submitting. 
In cases of streets having both of none of them, it saves the user a couple of taps
What do you guys think?

**Comment by westnordost** [comment]
Actually, I find @mnalis idea by far the best solution. It is at the same time unobstrusive but not hidden, consistent with another form, doesn't need additional text+translations and kills two flies with one swat: making it faster to answer "no cycleway at all here" and also making it faster to repeat the answer for several continuous short stretches of road.

I'd close this issue in favor of #2542

**Comment by HolgerJeromin** [comment]
> Actually, I find @mnalis idea by far the best solution. 

You mean "small icon with the last answer"?
Just a note: The user have to be clear about the direction. The new way could be in the oposite direction or even 90° rotated to the last way.

**Comment by westnordost** [comment]
> Just a note: The user have to be clear about the direction. The new way could be in the oposite direction or even 90° rotated to the last way.

This should not be up to the user to be cautious about. The app should intelligently apply the sides selected before. This means that additionally to the last answer, the orientation of the last way must be persisted as well.

**Comment by westnordost** [comment]
Closed in favour of #2542
