### ISSUE TITLE
Suggested Quest: Royal Cypher for post boxes

### ISSUE THREAD

**Issue by pigsonthewing** [streetcomplete/StreetComplete#2563]
### General

On items with tag [Tag:amenity=post_box] 

Note: applies to UK only (could be applied to some Commonwealth territories if requested by local mappers)

Affected tag(s) to be modified/added: [Tag:royal_cypher=*] ( https://wiki.openstreetmap.org/wiki/Key:royal_cypher )

Question asked: **What is the royal cypher on this post box**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x ] 🚧 To be added tag is established and has a useful purpose
- [x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

A set of radio buttons with the values as listed at https://wiki.openstreetmap.org/wiki/Key:royal_cypher from which only one, or "no value", may be selected. Can use thumbnail mages fro that age if desired. Since "EIIR" is the commonest value it should be prominent. "Scottish Crown" will be the commonest value in Scotland.

Note: useful purpose is to aid enthusiasts, conservationists, and photographers looking for boxes with older or rare cyphers.

**Comment by westnordost** [comment]
>[x ] 🚧 To be added tag is established and has a useful purpose
> Note: useful purpose is to aid enthusiasts, conservationists, and photographers looking for boxes with older or rare cyphers.

Hm, I don't know about that. I'd not implement that at least. But if you would implement that, I'd merge it and I can give you a few pointers where to start. The pictures on the wiki are not that well visible (red on red), maybe it would be better to use some SVG versions of these initials instead.

**Comment by matkoniecz** [comment]
See  #1370

**Comment by pigsonthewing** [comment]
> 
> 
> if you would implement that, I'd merge it and I can give you a few pointers where to start.

Thank you. I'm not a developer, alas, so that isn't going to happen.

**Comment by pigsonthewing** [comment]
> See #1370

The reasons given there for rejecting the quest are farcical.

As suggested there a further reason for adding this data is for historic maps.

**Comment by RobJN** [comment]
@atomoil: Any interest in the above? Know you've been looking at the idea of adding quests to StreetComplete.

**Comment by matkoniecz** [comment]
> The reasons given there for rejecting the quest are farcical.

Have you seen that thread? Given

> Apart from agents querying a database to find the rare cyphers, I can't think of a use case outside of that.

the closure note

> Ok, well, I rather not have this in the app because the usefulness of this tag is a bit unclear and, if Pokemon Go is involved, the I see a data quality issue. In other words, if a rare cypher leads to an advantage in that game, there will be people who deliberately input wrong data to get this advantage.

was reasonable

**Comment by RobJN** [comment]
I think #1370 gets a bit confused when it starts talking about Niantic - as in making a decision based on arguments related to Niantic seems odd. Why is it odd? Because for some reason OpenStreetMappers in the UK have added Royal Cypher details on 32k out of 73k post boxes. Some might be because of Niantic but I don't expect it is that many. I add them and had no idea there was / wasn't a connection to Niantic.

Are they useful? Unknown, but as noted 32k of 73k have been added to OSM in the UK so the community certainly seems to enjoy adding them even if not "useful". Given how widely the community add them it seems harsh to outright reject. If someone can do the hard work it feels it is worth adding this just because the community clearly enjoys adding them.

**Comment by GeorgeHoneywood** [comment]
To be honest I'm not sure a casual Pokémon Go vandal would go to the effort of downloading an app which can only modify PoIs -- they could just use ID which is a much more visible and useful tool for their goals (i.e. actually making new PoIs).

I think rejecting the old PR over that was perhaps a little unreasonable. However I'm not a postbox fan and would probably turn the quest off anyways ¯\_ (ツ) _/¯

**Comment by pigsonthewing** [comment]
On Mon, 8 Feb 2021 at 20:49, Mateusz Konieczny <notifications@github.com> wrote:
>
> The reasons given there for rejecting the quest are farcical.
>
> Have you seen that thread?

Are you suggesting that I would write about it without having first read it?

> Given
>
> Apart from agents querying a database to find the rare cyphers, I can't think of a use case outside of that.

That is not the only rationale for including the data given in the thread.

> the closure note
>
> Ok, well, I rather not have this in the app because the usefulness of this tag is a bit unclear and, if Pokemon Go is involved, the I see a data quality issue. In other words, if a rare cypher leads to an advantage in that game, there will be people who deliberately input wrong data to get this advantage.
>
> was reasonable

It is not reasonable; it is farcical.

-- 
Andy Mabbett
@pigsonthewing
http://pigsonthewing.org.uk

**Comment by smichel17** [comment]
Let's please dial the combativeness in this thread down a notch. We're all on the same team here, even when we disagree.

**Comment by TurnrDev** [comment]
I started the original thread and since then I have:
1) Stopped playing Pokemon Go
2) Still think postboxes are cool
3) Gained some code knowledge

> Hm, I don't know about that. I'd not implement that at least. But if you would implement that, I'd merge it and I can give you a few pointers where to start. The pictures on the wiki are not that well visible (red on red), maybe it would be better to use some SVG versions of these initials instead.

I'd be happy to give it a try if @pigsonthewing is unsure where to start

**Comment by arrival-spring** [comment]
I'm up for giving this a go.
I agree that it's a fun thing to add, even though there isn't particular usefulness to the data.
