### ISSUE TITLE
Add Mapillary/OpenStreetCam images

### ISSUE THREAD

**Issue by FinixFighter** [streetcomplete/StreetComplete#2568]
**Use case**
I think that using images from Mapillary and KartaView (former OpenStreetCam) can be extremely useful in order to add even more details to OSM.

**Proposed Solution**
The solution used could be similar to that of openstreetmap.org. There could be a button which enable traces along the streets. These traces correspond to the sequences of images captured by users; by clicking on them you can view the correspondant photo.
In the screenshot below you can see how OSM website handle it, by clicking on the green "point" you can view the corresponding image.
![Screenshot at 2021-02-11 18-25-36](https://user-images.githubusercontent.com/19877271/107674016-cd49eb80-6c96-11eb-82ed-cb875da315b5.png)
![Screenshot at 2021-02-11 18-27-11](https://user-images.githubusercontent.com/19877271/107674043-d2a73600-6c96-11eb-9f5f-3a3ee3cab34c.png)

**Comment by caugner** [comment]
One issue I see with OpenStreetCam integration in StreetComplete is that the photos might be months or years old, so I tend to say it's not a reliable source for many quests. When switching to an OpenStreetCam view, incompatible quests should therefore be hidden.

**Comment by matkoniecz** [comment]
For areas where there up to date images (not ones taken years or months ago) it may be acceptable to look at OpenStreetCam/Mapillary on a computer screen and solve StreetComplete tasks on the phone.

But it does not require any implementation on StreetComplete side.

Merging it into StreetComplete would require significant implementation effort and would require educating people about using outdated imagery and handling all kind of breakage on third-party services (upside-down Mapillary images bug, outages on external services etc).

It seems clear to me that bundling it into SC is not a good idea - even if it would take 0 development effort and 0 maintenance effort.

**Comment by mnalis** [comment]
I agree with @matkoniecz. 

In addition to everything said, StreetComplete is intended for **physical on-location** survey of missing details **which are verified on the ground by the mapper** (ie. you should not use StreetComplete for editing of data on location at which you are at that moment and is visible by you  (eg. current location +-100meter).  SC even warns you if you try to map outside of estimated visible range to **only map what you see by your own eyes on the ground**. 

And if you are on the ground at that location, Mapillary and KartaView are completely useless, as they would only show what you can much better (and much more recently) see with your own eyes. 

For general purpose OSM editor, there is a plenty of [choices](https://wiki.openstreetmap.org/wiki/Editors), including [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) on Android mobile phones, which sounds much more like a good target  for this. 

Trying to make StreetComplete into another Vespucci would make all of its advantages disappear.

**Comment by FinixFighter** [comment]
OK, thank you everyone for your answers! :)
