### ISSUE TITLE
Roads rendering glitch when at the edge of the screen

### ISSUE THREAD

**Issue by mxxcon** [streetcomplete/StreetComplete#2571]
I can't seem to reproduce it every time, but a couple of times I noticed that roads that are close together at the edge of the screen render with artifacts. If I pan the map just a couple of pixels, it switches between correct and messed up rendering.

![Screenshot_20210210-192733_StreetComplete-ANIMATION](https://user-images.githubusercontent.com/847140/107826461-f29c2f80-6d52-11eb-9826-0d56424f7b7c.gif)

Animation aligned the maps to easier see where it's happening.

**How to Reproduce**
Pan map left/right

**Versions affected**
StreetComplete v30.0
Galaxy S20FE Android 11

**Comment by westnordost** [comment]
Shown location: https://www.openstreetmap.org/#map=19/40.57923/-73.97521

**Comment by westnordost** [comment]
Can't reproduce, however, this is a problem with tangram-es. Would you mind opening a bug here instead?

https://github.com/tangrams/tangram-es/issues

By the way, the animation you posted is a little confusing. First I though the problem would be that the **entire screen** shifts to the right.
