### ISSUE TITLE
What is non-detached home?

### ISSUE THREAD

**Issue by Garbulix** [streetcomplete/StreetComplete#2572]
Hi,

I try to translate StreetComplete and I cannot find proper information what `non-detached single-family home` really is (`quest_buildingType_house_description2`). Is it just terraced house?

**Comment by FloEdelmann** [comment]
Please see the discussion in #2467.

**Comment by matkoniecz** [comment]
> Please see the discussion in #2467.

+1

> Is it just terraced house?

Also semidetached house and any other kind of house. See https://wiki.openstreetmap.org/wiki/Tag:building%3Dhouse

StreetComplete description is narrower to encourage more specific tagging.

**Comment by matkoniecz** [comment]
@Garbulix If you need futher help - please let us know what is unclear, if the question is answered: you can close the issue to mark it as resolved.

**Comment by Garbulix** [comment]
The problem with discussion #2467 is that I barely understand it, but maybe that understanding isn't necessary.

As I currently guess - _non-detached single-family home_ is just **any** single-family home that is not detached (something like a superset)? 

You know - yesterday I just thought that non-detached home is just another, exact kind of home (like semi-detached or detached) and I got frustrated, because I couldn't find any information non-detached houses is (wiki wasn't helpful at all, because there wasn't a word about them) - I was looking for a keyword "non-detached" and I couldn't find it. 

If _non-detached home_ is something like that mentioned _superset_, maybe `non-detached single-family home` should be changed to `any non-detached single-family home`? That would be more self-explanatory IMO.

**Comment by smichel17** [comment]
> The problem with discussion #2467 is that I barely understand it,

Try the relevant parts of https://github.com/streetcomplete/StreetComplete/issues/1716#issuecomment-581161759 maybe?

**Comment by matkoniecz** [comment]
> As I currently guess - non-detached single-family home is just any single-family home that is not detached (something like a superset)?

Yes, exactly.

> You know - yesterday I just thought that non-detached home is just another, exact kind of home (like semi-detached or detached) 

No, it is group of various house types (it is not an ideal classification, and a bit weird one - result of SC trying to encourage specific tagging within what OSM tagging scheme allows)

> (wiki wasn't helpful at all, because there wasn't a word about them) - I was looking for a keyword "non-detached" and I couldn't find it.

It is caused by SC using this term to restrict definition of one of tags (this encourages also correct, and more specific tagging)

**Comment by westnordost** [comment]
alright, I'd say the question is answered. A "house" should be translated to be "any single familiy home that is not a detached house".
