### ISSUE TITLE
App crashes during quests download/synchronization

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#2573]
After a certain time frame using the app in different locations with obviously different quest downloads the app begins to crash when synchronizing quests. As far the 1st crash during quest download/synchronization occured the app is crashing each time when trying to download/synchronize quests.
The download/synchronization is always taken place offline via WLAN.

Workaround:
- cleaning up the app quest cache
- closing app
- cleaning up all temporary files of the smart phone using a 3rd party app (this includes the StreetComplete Map tiles as well)
- starting app again 
- map(s)/quests are synchronized/downloaded again

**Versions affected**
Android 5.1
StreetComplete v29.1

**Comment by westnordost** [comment]
You got the app from Google Play or F-Droid?
Does it crash, i.e. the app exists, or does it report that the download could not finish because of an error?

**Comment by ironspock** [comment]
App is/was downloaded from F-Droid.
Just to clarify:
The app does not crash when downloading/installing it from an app store. 
Basically I'm using the app in "offline" mode. Mean I synchronize answered quests/download new quests (partially for different locations as well) via WLAN. So this is working fine for a time frame (multiple days). Then it suddendly crashs when synchronizing quests - as far as I've observed after uploading answered quests and during download of new quests. Partially the "running cursor" on magnifier icon stucks and the app crashs. Afterwards the mentioned workaround is used to download map tiles/new quests.

**Comment by westnordost** [comment]
And the app did not ask you to send the crash report?
Did this happen when you upload the answers while downloading new quests?

**Comment by ironspock** [comment]
Yes for both question.
But no mail settings were configured so far. I've done now.
So, in case of a crash occurence, I'll be able to send the report.

**Comment by westnordost** [comment]
Ok, since I cannot do anything with this report without further information, I'll close this bug because I will get all the info I need from when you send me a crash report when this happens again via email.
