### ISSUE TITLE
Don't ask for height limit of parking exit

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2575]
Parking garage exits usually don't have a sign specifying height limit, so I think StreetComplete should not ask for exits.
According to https://wiki.openstreetmap.org/wiki/Tag:amenity=parking_entrance "The distinction between entrances which function as exits, entrances or both is defined by the oneway=* tag of the highway=* connected to the parking_entrance node."

There could be multiple exits with different height limits where asking would make sense, but I guess this is rather uncommon. And still, they are exits. Thus "What is the height limit of this parking entrance?" does not apply.

**Comment by matkoniecz** [comment]
Using amenity=parking_**entrance** for exit seems really weird. Is it really established practice? Hopefully wiki is wrong there, and only rare cases are tagged this way.

(and yes, I know about `entrance=exit`)

**Comment by Helium314** [comment]
I agree it seems weird, but that's what the wiki says...
I had a short look around and only found few such cases, but that's maybe because usually entrance and exit are in the same place.

**Comment by matkoniecz** [comment]
Well, in many cases it turns out that info on wiki is wrong/outdated, hopefully it is the case here.

**Comment by westnordost** [comment]
Well, whatever is in the wiki has the habit to become somewhat de-facto tagging over time. Is there any tag with which one can distinguish parking exits from parking entrances?

**Comment by westnordost** [comment]
The "and/or exit" part has been in the wiki since its creation though (2011)

**Comment by matkoniecz** [comment]
> Is there any tag with which one can distinguish parking exits from parking entrances?

Wiki right now recommends checking oneway direction - what may be just complex if parking entrance node is on building outline and becomes obnoxious if it would require building and analysis of routing graph.

> The distinction between entrances which function as exits, entrances or both is defined by the oneway=* tag of the highway=* connected to the parking_entrance node.

**Comment by westnordost** [comment]
Looks like will-not-fix then

**Comment by matkoniecz** [comment]
And technically height restriction of exit also may be relevant in extreme cases.

**Comment by mnalis** [comment]
> Parking garage exits usually don't have a sign specifying height limit

[Max Headroom](https://www.imdb.com/title/tt0092402/trivia?item=tr0598898) begs to differ.

**Comment by westnordost** [comment]
Okay, will not fix then.
