### ISSUE TITLE
Add detail to crossing sound signals and vibration changeset message

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2577]
When the traffic signals sound and traffic signals vibration quests are answered the comment on the changeset is 
"Add traffic_signals:vibration tag", e.g. https://www.openstreetmap.org/changeset/99294493
Or "Add traffic_signals:sound tag", e.g. https://www.openstreetmap.org/changeset/99263090

All other quests (I think) have more meaningful comments, e.g. "Add whether pedestrian crossing has an island" (https://www.openstreetmap.org/changeset/99305683) etc.

(All changesets are just random recent ones I found through OSMCha).

How about "Add whether traffic signals have sound signals" and "Add whether traffic signals have tactile indication that it's safe to cross".

I'm up for fixing this (easy change, but I want to contribute).

Also related, is there a reason for changeset comments not being localised? If it's an enhancement that's wanted then I'll open a different issue for it.

**Comment by matkoniecz** [comment]
> How about "Add whether traffic signals have sound signals" and "Add whether traffic signals have tactile indication that it's safe to cross".

Seems to be an improvement for me.

**Comment by matkoniecz** [comment]
> Also related, is there a reason for changeset comments not being localised?

I am guessing that because it would 

(a) require extra code: translating this extra strings, supporting selection of proper one, if one moves through language boundary then you need to open a new changeset and so one

(b) require extra data: where given language is preferable

(c) language is a political issue in various places, mistakes or something that can be treated as a political statement done silently on behalf of user may be problematic, as result maintaining (b) requires dealing will all that.

So it would be a significant effort.

**Comment by arrival-spring** [comment]
My thinking was that it could be set to the interface language, rather than the country language (I agree with your points about the problems of that). Mostly this will match the language (or one of the languages) of the country the quest is solved in.
I guess it doesn't affect me since I'm in an English speaking country and my first language is English, but don't know what other people would think who maybe don't even speak English (either well, or at all).

**Comment by kjonosm** [comment]
> Also related, is there a reason for changeset comments not being localised? If it's an enhancement that's wanted then I'll open a different issue for it.

As a non-native English speaker, I would very much appreciate localised changeset comments. I am happy to help translating if necessary.

**Comment by matkoniecz** [comment]
@kjonosm Just in case that you are unaware about it. Translating of other parts of the app is possible already, help is really welcomed: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app
