### ISSUE TITLE
Building subdivision

### ISSUE THREAD

**Issue by ISibboI** [streetcomplete/StreetComplete#2585]
In my area many buildings that are touching but have a different purpose each are merged into one. For example there is an apartment building sharing a wall with row houses. 

It would be nice to be able to request a house to be subdivided. At the moment all I can do is make a comment, but that seems too manual for a seemingly more common issue.

**Comment by matkoniecz** [comment]
> The UI for this. Doing a "slice" is maybe quite imprecise with fingers on a small screen.

Even in Vespucci I have trouble with doing it.

**Comment by arrival-spring** [comment]
> 1. It is very **complex**. Already the splitting of a way is roughly 1500 lines of code. I know no OSM editor that offers to slice an area into two, i.e. in JOSM the workflow to do that would be: 1. add vertices to the outline at the points where the slice should happen, 2. mark both vertices and press "P" ("split"), 3. draw a line from vertex 1 to vertex 2, 4. mark that line and the first half of the split area, press "C" ("combine"), 5. repeat step 3, 6. repeat step 4 but with the other half

UtilsPlugin2 in JOSM provides "Split Object" which just requires two nodes on the outline.
https://josm.openstreetmap.de/wiki/Help/Plugin/UtilsPlugin2

Not saying that makes it easy to implement here though.

**Comment by ISibboI** [comment]
Well an actual UI would be amazing, I see that it would be lots of work.

I actually rather thought about a special marker in the OSM data that hints that the building requires subdivision would be good. Then someone on a PC can go through these markers and correct the buildings. But yeah, that might also be difficult from just the satellite image.

**Comment by mnalis** [comment]
@ISibboI I usually just long press at location to write a note "split building here". Notes are universal tool for such things.

**Comment by westnordost** [comment]
So anyway, I'd evaluate the effort (2-3 weeks full-time) vs gain very strongly on the "it's not worth it" scale, so this is why I will not implement it and would advise possible contributors to also not spend time on it. For this reason, I will close it.
If someone finds this ticket later and still would like to give it a try to implement, be my guest.

**Comment by smichel17** [comment]
Keywords for searching: split building part

**Comment by matkoniecz** [comment]
Building-Type Quest: This ist a building:part #3351 is related
