### ISSUE TITLE
Feature request: Option to relocate an item

### ISSUE THREAD

**Issue by jrmhaig** [streetcomplete/StreetComplete#2586]
**Use case**

A couple of times now I have left notes to indicate that a bus stop has moved (see [here](https://www.openstreetmap.org/note/2540924#map=18/51.39782/-0.02409) for example). Generally these notes are resolved quite quickly (so that link may not work) but it would save time for me and the person reviewing the note if there were a 'one-click' way to do this rather than having to make sure I have written up enough information to find the original item.

**Proposed Solution**

I would propose an option in 'Other options' for 'this X has moved', which then allows the user to drop a pin at the new location. This could then either;

a. Automatically relocate the item
b. If (a) cannot be done by the app, create a note including the item reference and the new location

**Comment by westnordost** [comment]
What things would move?

**Comment by jrmhaig** [comment]
> What things would move?

In the note I left (which I see has already been resolved) the node is the bus stop here 

* https://www.openstreetmap.org/node/469774417

and this is what I would want to move. It is just bus stops that I have seen marked in the wrong place so far but it could apply to other things too, such as dustbins and benches.

**Comment by FloEdelmann** [comment]
I had a similar case with a postbox once: https://www.openstreetmap.org/changeset/93301811

**Comment by riQQ** [comment]
I have seen a cigarette vending machine that was moved across the street.

**Comment by rhhsm** [comment]
In addition, there are also objects that were put on the map in the wrong place, and such mistakes could be corrected by moving them to the right place. I moved 3 shops today (with iD) after I noticed they were in the wrong place during a survey using SC.

**Comment by matkoniecz** [comment]
Main problem here is that if one notices that 

- at location A there is mapped a bin/vending machine/shop
- it is not present there
- matching object is present at location B

moving still may be incorrect. Maybe shop has address tagged? Maybe at location B bin is already mapped? To make such edit you need to see full data :(

**Comment by jrmhaig** [comment]
> Maybe at location B bin is already mapped? To make such edit you need to see full data

I can see that this is a problem and I would suggest that having a shortcut to create a note with all the relevant information may be preferable to automatically moving the item.

**Comment by mnalis** [comment]
Also, there could be a problem with quality of GPS reception, especially in cities, which always complicates mapping on ground. 
In addition to that, I'm afraid novice users might move wrong things around by accident.

**Comment by Helium314** [comment]
There could be a 'select location' button added to the note screen. When tapped, a position selector is shown (similar to the one for 'create new note') and an 'ok' button. On tapping 'ok' the coordinates are inserted into the note text.

Potential problem: I have no idea how to actually set coordinates for a node manually (using ID editor, didn't try anything else).

**Comment by westnordost** [comment]
Hm, see @matkoniecz ... I think in case of a moved object, it is always better to leave a note. The object might also have moved "really" (and not just mismapped in the first place), in which case it is likely that the surrounding elements (for example the bench at a bus stop, but also maybe the street layout etc) changed because the whole area was renovated.
