### ISSUE TITLE
Added "doesn't exist" answer option to the building type quest

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#2587]
**Use case**

I think it's a frequent problem with buildings on the country side. Oftentimes I find tagged buildings that do not exist anymore. In these cases, I usually have to leave a note saying the building doesn't exist, manually. But doing this is complicated and requires rework.

**Proposed Solution**

Added "doesn't exist" answer option to the building type quest

**Comment by arrival-spring** [comment]
I have had the same issue and have also had to leave notes and then remember to go back and fix it later.

**Comment by matkoniecz** [comment]
what should be done if building has also tagged

- address tags
- shop/office/amenity is tagged also on a building element

Also, special handling would be needed if building is mapped as multipolygon, has mapped `building:part=yes`.

What about `shop` `office` etc nodes/areas inside building?

**Comment by westnordost** [comment]
Well, see @matkoniecz

**Comment by tiptoptom** [comment]
In most cases,
