### ISSUE TITLE
Suggestion: What specialties does this doctor have?

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#2599]
### General
Affected tag(s) to be modified/added: [healthcare:specialty](https://wiki.openstreetmap.org/wiki/Key:healthcare:speciality)
Question asked: **What specialties does this doctor have?** / **What kind of doctor is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
  - Possibly; at least in Germany it's usually written in the sign outside what specialities a doctor has. Many of them may also have a website, which makes a survey unnecessary, but many also do not. No idea how this looks in other countries, though.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
  - Not all of them are general practitioners, and many of those even have multiple specialities.
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)
  - Would apply to healthcare:doctor (60k) and amenity:doctors (130k), No idea whether that's enough.

### Ideas for implementation

**Element selection:** (amenity:doctors or healthcare:doctor) and not healthcare:speciality

**Proposed GUI:** Perhaps similar to iD:

![image](https://user-images.githubusercontent.com/1692688/108618383-f77d7500-741d-11eb-94ed-ffe003f0491e.png)

Just hopefully with translations and explanations about the values. Ideally the values should match what's written on the office signs

**Comment by FloEdelmann** [comment]
See also #1020

**Comment by matkoniecz** [comment]
Please, mention things missing from #1020 there.

> Would apply to healthcare:doctor (60k) and amenity:doctors (130k), No idea whether that's enough.

That is definitely enough to pass that requirement.
