### ISSUE TITLE
Ask if this crossing is lit

### ISSUE THREAD

**Issue by jnk0** [streetcomplete/StreetComplete#2600]
### General
Affected tag(s) to be modified/added: [lit](https://wiki.openstreetmap.org/wiki/Key:lit) for [crossing](https://wiki.openstreetmap.org/wiki/Key:crossing)
Question asked: **Is this crossing lit?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** `crossing=*`

**Comment by matkoniecz** [comment]
Why it would be useful? StreetComplete asks already whatever street is lit and allows splitting way as an answer.

How crossing can be lit without making at least short section of footway/road also being lit.

**Comment by jnk0** [comment]
In my hometown marked crossings are often separately lit, even if the street itself is lit. And as a pedestrian you know that this is useful.

**Comment by jnk0** [comment]
So the question could also be: Is this crossing lit separately?

**Comment by westnordost** [comment]
Is this how the tag on a crossing node is supposed to be interpreted, though?

Am 21. Februar 2021 14:53:05 MEZ schrieb Janek <notifications@github.com>:
>So the question could also be: Is this crossing lit separately?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2600#issuecomment-782861667

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> In my hometown marked crossings are often separately lit, even if the street itself is lit.

That means that short section of footway/road is lit, right? In such cases I split them and answer lit quest appropriately.

**Comment by jnk0** [comment]
> > In my hometown marked crossings are often separately lit, even if the street itself is lit.
> 
> That means that short section of footway/road is lit, right? In such cases I split them and answer lit quest appropriately.

A crossing does not necessarily means a separate footway is tagged, doesn't it? Often I see it placed on a road without separate footway. And why should I split the road in such cases if (only) the crossing is separately lit? The light illuminates only the crossing.

I'm with @westnordost, the lit attribute for crossings indicates a separate illumination and imho it is worth to ask about and tag it.

**Comment by westnordost** [comment]
> I'm with @westnordost, the lit attribute for crossings indicates a separate illumination and imho it is worth to ask about and tag it.

That is not at all what I wrote.

**Comment by matkoniecz** [comment]
> And why should I split the road in such cases if (only) the crossing is separately lit? The light illuminates only the crossing.

Can you link/attach a picture of lit `highway=crossing` where road is not lit?

**Comment by matkoniecz** [comment]
Also, StreetComplete is not a good place to introduce a brand new tagging without discussing it elsewhere. Note that less than 4000 crossing worldwide has `lit` tag - http://overpass-turbo.eu/s/13Xn - out of [4 898 000](https://taginfo.openstreetmap.org/tags/highway=crossing) `highway=crossing` nodes.

I am not convinced that tagging it on every single crossing is a good idea.

**Comment by jnk0** [comment]
> > I'm with @westnordost, the lit attribute for crossings indicates a separate illumination and imho it is worth to ask about and tag it.
> 
> That is not at all what I wrote.

Okay, sorry for that. I may have misunderstood you.

> > And why should I split the road in such cases if (only) the crossing is separately lit? The light illuminates only the crossing.
> 
> Can you link/attach a picture of lit `highway=crossing` where road is not lit?

I have no self made pictures, but see: [1](https://images.ctfassets.net/xytfb1vrn7of/2w7e6FUNM8sJ6xUoFJ0U7M/62717fe0a09a07b22ec81c9a6cc53a0b/IMG_beleuchteter_F____g__nger__berweg.jpg?w=1026&h=580&fm=jpg&q=80), [2](https://www.safestreets.de/images/massnahmen/zebrastreifen/apl-smart01.jpg)

> In case of someone tagging that something like
> 
> ![aircrosswalk02](https://user-images.githubusercontent.com/899988/108633455-9df46500-7474-11eb-83b9-1a3c532efdfa.jpg)
> 
> is a lit crossing I would expect `highway=*` representing road to be split with short section tagged as `lit=yes`.

Wouldn't it be much easier to add lit=yes to crossing tag?

> Also:
> 
> > Not an overwhelming percentage of elements have the same answer (No spam)
> 
> Asking it on every single crossing on unlit roads would result in very spammy questions.

Okay, the number of illuminated crossings is growing, but yes the majority still do not have dedicated lighting. So this argument of yours is true.

It was not really my intention to start a debate here. My suggestion is based on the documentation for tag _crossing_, which lists _lit_ as an appropriate attribute. I can very well see a use case for it, and I don't see why lighting the road or path should cause dedicated lighting of the crossing not to be emphasized. Because that makes a difference in the real world and just in the application of the map. If you don't see it that way, close this issue.

**Comment by matkoniecz** [comment]
> Wouldn't it be much easier to add lit=yes to crossing tag?

Yes, but 

- part of road with `lit=no` is incorrect
- editing becomes more fragile (street lamps dismantled? Now you need to look at even more places to retag it)
- processing becomes more obnoxious

**Comment by BalooUriza** [comment]
Is this not already handled on `highway=footway`, `footway=crossing` ways?

>

**Comment by jnk0** [comment]
First of all, I would like to note that I appreciate @matkoniecz's constructive feedback.

Let me take up the open points listed in this issue.

I would like to have it noted that whether a road is lit and/or whether a marked crossing is lit separately are two different statements. Therefore the (existing or not) `lit` attribute on objects with `highway=*` just cannot replace the additional `lit` attribute on objects with `crossing=marked`. The lighting belongs to the crossing and not to the road. If the crossing is removed in the real world, the road is not (additionally) illuminated there either.

Personally, here I would also mark an otherwise unlit road as `lit` at the location of the dedicated lit crossing (3-5 meters, really?). But that's for everyone to decide and doesn't matter for this quest, in my humble opinion.

> Also, StreetComplete is not a good place to introduce a brand new tagging without discussing it elsewhere. Note that less than 4000 crossing worldwide has `lit` tag - http://overpass-turbo.eu/s/13Xn - out of [4 898 000](https://taginfo.openstreetmap.org/tags/highway=crossing) `highway=crossing` nodes.

The comment about the spamming factor is valid, after a reality check, I would therefore like to propose the following customized selector: `highway=crossing` and `crossing=marked`

In a radius around my hometown, this leads to the following result: 103 without lit and 13 with lit tag. Hen-and-egg problem because StreetComplete has not yet implemented this question, I would guess. Might even have a better answer ratio than "Does this crossing have an island?" otherwise. But beware, of course, this is not representative.

Could you consider implementing the question "Is this (marked) crossing separately illuminated?" under adjusted conditions?

**Comment by westnordost** [comment]
All in all, I am with you there, @jnk0 and I think this information has also some value: I expect that lit crossings are a safer to cross than unlit ones.

The problem is, and I noted that at the very beginning of this thread but was probably misunderstood, that even though `lit` is listed as a tag that would be a "useful combination", it is not described at all how this tag should be interpreted or when it should be tagged. You assumed that `lit=yes` means that specifically this crossing is lit, i.e. the lighting is part of the crossing. But since any form of documentation is missing, other people might interpret this as "there is light at the crossing". So, at the very least, it should be documented **first** in the wiki, what `lit` on a crossing node should mean before any quest is implemented that uses that definition.

**Comment by jnk0** [comment]
> The problem is, and I noted that at the very beginning of this thread but was probably misunderstood, that even though `lit` is listed as a tag that would be a "useful combination", it is not described at all how this tag should be interpreted or when it should be tagged. You assumed that `lit=yes` means that specifically this crossing is lit, i.e. the lighting is part of the crossing. But since any form of documentation is missing, other people might interpret this as "there is light at the crossing" or even something different. So, at the very least, it should be documented **first** in the wiki, what `lit` on a crossing node should mean before any quest is implemented that uses that definition.

I agree completely.

**Comment by mnalis** [comment]
I must admit that I am totally confused. Especially I do not understand @westnordost last comment which distinguishes from _"specifically this crossing is lit"_ and _"there is light at the crossing"_? To me that two sentences mean the same ie. that _"when I stand at that crossing I can see my immediate surroundings at night"_? I mean, if something is `lit` then there must be `light` there by its physics definition?

Also I do not seem to understand what is the possible confusion with [lit=yes](https://wiki.openstreetmap.org/wiki/Key:lit) tag on `node` (or `way`) marked with [crossing=*](https://wiki.openstreetmap.org/wiki/Key:crossing) tag. I percieve only one definition: that that `node` (or `way`) is lit (ie. _"illuminated by source or reflection of photons"_, meaning _"I can see on night"_ on that point if it is on `node`, or on that whole way if it is on a `way`).

Can someone try to explain to me in more detail/example what is the other definition of `lit=yes` that is causing confusion, as I don't seem to get it?

Or is it maybe about strength of the light, eg. difference _"there is light exactly above me"_ vs. _"there is light illuminating my way, but it coming from regular street lightning 3 meters away"_ (which is what I think [lit:perceived=*](https://wiki.openstreetmap.org/wiki/Key:lit:perceived) should be about; or even more micromapped with something like [light_source](https://wiki.openstreetmap.org/wiki/Proposed_features/Key:light_source))?

**Comment by jnk0** [comment]
Following @nordwestost's documentation reference, I was more interested in checking how/where the necessary reconciliation for a doc entry could take place.

But to answer your question briefly from my humble point of view:

**"this crossing is (specifically) lit"**: there is dedicated lighting at the crossing that illuminates just that.

Examples:

![marked_crossing_lit](https://user-images.githubusercontent.com/3634281/109123847-9077fd00-774a-11eb-9dc5-c19a6c7cc44a.jpg) ![IMG_beleuchteter_F____g__nger__berweg](https://user-images.githubusercontent.com/3634281/109123771-7b02d300-774a-11eb-8081-36a255aaf613.jpg)

**"there is light at the crossing"**: The crossing is lit by e.g. general street lighting.

**Comment by matkoniecz** [comment]
> "this crossing is (specifically) lit": there is dedicated lighting at the crossing that illuminates just that.

So if entire street is brightly lit and there is no dedicated light for just crossing it is `lit=no`?

**Comment by jnk0** [comment]
> > "this crossing is (specifically) lit": there is dedicated lighting at the crossing that illuminates just that.
> 
> So if entire street is brightly lit and there is no dedicated light for just crossing it is `lit=no`?

I must admit that I don't know the answer to this question either (yet). Currently, I do not add a lit attribute at such a crossing. Precisely because `lit=no` can be misinterpreted.

**Comment by mnalis** [comment]
> > > "this crossing is (specifically) lit": there is dedicated lighting at the crossing that illuminates just that.

Thanks for explanation. But then, how would the data consumer use that information exactly? I would think the user would be **more interested in how bright** the light is at the crossing (as indicated by [lit:perceived=*](https://wiki.openstreetmap.org/wiki/Key:lit:perceived)) and not what was design decision on placing lights. 

After all, "general street lightning" might happen to be so close to the crossing to have the same (of even stronger!) lightning effect that "specific lamps on crossing", and if it is same or better lit, would users prefer one to another? 

> > So if entire street is brightly lit and there is no dedicated light for just crossing it is `lit=no`?
> 
> I must admit that I don't know the answer to this question either (yet). Currently, I do not add a lit attribute at such a crossing. Precisely because `lit=no` can be misinterpreted.

Not adding `lit=no` is indeed correct in such a case in my opinion too (as it would mean it is dark), but then we have a problem: how would SC distinguish between "crossing that was mapped but does not have it's own lightning" and "crossing that was not mapped yet for `lit` tag"? As both don't have `lit` tag. If it cannot distinguish, then it can't be implemented as quest would remain forever open in such cases.

**Comment by westnordost** [comment]
Okay, in conclusion, to map something like "crossing has dedicated lighting", a new tag (value) is necessary, for example `lit=dedicated` or better a new key because it collides with other `lit` tagging.
However, this cannot happen here but should be discussed on the ML, forum, wiki or as a proposal.

**Comment by westnordost** [comment]
You can leave a note here if / after this happened and it came to a positive conclusion. However, maybe it would even be better to then create a new quest suggestion and just link to this because this thread became quite long.

**Comment by BalooUriza** [comment]
> Following @westnordost documentation reference, I was more interested in checking how/where the necessary reconciliation for a doc entry could take place.
> 
> But to answer your question briefly from my humble point of view:
> 
> **"this crossing is (specifically) lit"**: there is dedicated lighting at the crossing that illuminates just that.
> 
> Examples:
> 
> ![marked_crossing_lit](https://user-images.githubusercontent.com/3634281/109123847-9077fd00-774a-11eb-9dc5-c19a6c7cc44a.jpg) ![IMG_beleuchteter_F____g__nger__berweg](https://user-images.githubusercontent.com/3634281/109123771-7b02d300-774a-11eb-8081-36a255aaf613.jpg)
> 
> **"there is light at the crossing"**: The crossing is lit by e.g. general street lighting.

If the way the crossing is on is tagged with the following, it will already get picked up by the existing lit quest.

`highway=footway
footway=crossing`
