### ISSUE TITLE
Text being cut off

### ISSUE THREAD

**Issue by AlertSubject** [streetcomplete/StreetComplete#2605]
When being asked the "does this place offer kosher food" the options are "yes" "no" "only" 
I'm assuming the only option is cut off 
(see Screenshot attached) 

**How to Reproduce**
Click on the affected quest type

**Versions affected**
Android 10, streetcomplete 30.01

![Screenshot_20210222-211048.jpg](https://user-images.githubusercontent.com/72819077/108764667-3234f980-7553-11eb-83bd-73210fa58f4a.jpg)

**Comment by mnalis** [comment]
That sounds OK to me. Brevity of the buttons is likely on purpose, so they fit in one line. 

The meanings are:

- `No` - No, the place does not provide ANY kosher food
- `Yes` - Yes, the place provides some kosher food (among other, non-kosher food)
- `Only` - the place provides ONLY kosher food (no non-kosher food is offered)

Perhaps English translation of long description can be improved to also describe what "Only" means, if that is unclear.

**Comment by AlertSubject** [comment]
Yeah now that you're saying it makes sense. But the first time I read it it felt like something was missing
So I'm not sure if the text should be changed or not

**Comment by westnordost** [comment]
To what though?

**Comment by riQQ** [comment]
*"Exclusivley"* might be an option. But for me *"only"* was clear.

**Comment by westnordost** [comment]
I asked on OSM slack (mostly populated by US-Americans), noone seems to have a problem with "only". So I'll leave it this way.
