### ISSUE TITLE
SC in rapidly developing neighbourhoods

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#2607]
**Use case**
Today I surveyed a rapidly developing neighbourhood of Sofia, where small detached houses and summerhouses, connected with unlit gravel roads without pavements, are regularly demolished and replaced with apartment blocks. The building companies here are responsible for adding pavements, illumination and asphalt to the roads around their projects, which leads to a patchwork of roads for which these tags are different and that are likely to change rapidly. Look at this spot https://goo.gl/maps/2wrnJgwt68BciubV6 (node 2136604022), for instance: on the right older detached houses, on the left a new apartment block that's finished except the pavement in front of it is still "under construction" in October 2020 but is finished now. Take one step forward and you'll go back to how it was in 2012... I'm wondering how SC could contribute to keep this information up to date by stimulating regular resurveys. There is the building completion quest, but these will not lead to resurvey of other tags that are likely to change when a building is completed, such as illumination, pavements and surface of nearby roads.

**Proposed Solution**
When a building completion quest is answered with Yes, resurvey quests should result that ask if properties of nearby roads such as surface, illumination and pavements are still the same or have changed. I don't now, however, how to explain to a computer what is "nearby" (immediately adjacent roads, the nearest road, all roads within 30 m, ...?). Roads that already have illumination, pavements or asphalt surface should not be quested about that tag, because it's unlikely to chance (get worse). If there's no change, ask again 3-6 months later (it might take a while after the building is finished before its environment is finished).

**Comment by westnordost** [comment]
I would say, at least the solution presented is not possible from the technical side.

**Comment by westnordost** [comment]
So, I'll close this as will not fix. The mechanism of notes is I guess still the best one here. Oftentimes I see notes on the map that act as a reminder that something is renovated or constructed here.
