### ISSUE TITLE
Don't ask for roof shape of high buildings

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2609]
Following PR #2556 StreetComplete started asking for roof shape of many buildings where it can't be determined from street level.

I think it is reasonable to limit the quest to buildings with less than 4 or 5 levels if `roof:levels` does not exist.
After all, the bad visiblity could very well be the reason why `roof:levels` was left empty.

**Comment by westnordost** [comment]
Yes, makes sense!

**Comment by westnordost** [comment]
and

>  if roof:levels does not exist.

...or is 0. Maybe even some formula - Ask only if `(roof:levels ?: 0) + 4 - building:levels >= 0`

**Comment by Helium314** [comment]
> Maybe even some formula - Ask only if (roof:levels ?: 0) + 4 - building:levels >= 0

Yes, I think this would be better!

And thanks for fixing the title, didn't notice that at all

**Comment by ygra** [comment]
In some places, buildings have quite good height data (e.g. most of Rostock's buildings), due to where the initial import was from. This can be another – perhaps more reliable – indicator for whether to ask or not.

**Comment by Helium314** [comment]
Using height would definitely make sense. Then levels could be translated (approximately) into height.

Maybe something like: Ask only if `(height ?: building:levels * 3 + (roof:levels ?: 0) * 3) - (roof:levels ?: 0) * 3 < 15` (likely can be simplified)
This assumes one level is equal to 3 m (far off for industial or many older apartment buildings, but roughly ok for newer buildings), and then height = building:levels * 3 + roof:levels * 3.

**Comment by westnordost** [comment]
The formula is now `buildingLevels / (roofLevels + 2f) < 2f`

**Comment by andrewharvey** [comment]
I recently used street complete to add roof shapes to buildings up to 36 levels. With tall buildings you just need to move further away instead of standing at the base to observe the roof shape.

I get the reasoning for removing it, but it was very useful and certainly helped me add roof shapes I wouldn't have otherwise added.

**Comment by westnordost** [comment]
Sometimes you can't move further away. Streetcomplete can't know if there is enought space or not, so it is better to be on the safe side than asking (too many) unanswerable questions.

**Comment by RubenKelevra** [comment]
I feel like this doesn't apply for every area. If the buildings are built on a slope you can easily observe the roofs from street level - just from a little bit more distance (up the hill/mountain).

**Comment by westnordost** [comment]
Of course it is different for every area. We need to find some compromise. That formula is one.

**Comment by mnalis** [comment]
Perhaps the roof shape can be asked always, if `highway` closest to that `building` has [incline](https://wiki.openstreetmap.org/wiki/Key:incline) tag set? It would seem to me to cover most (if not all) such "hilly" issues, without adverse effects elsewhere  (of course, only if such filter is not too complicated to implement)

**Comment by Helium314** [comment]
I wasn't sure whether I really wanted to open this issue because of what is mentioned in the last comments.

I found many (now) 'too high' buildings where it was possible to answer the roof shape quest because they are on hilly ground, or sometimes because is was possible to move further away.
But then, for many more buildings of similar height I previously hadn't answered roof levels because it simply wasn't possible from street level. With the update all of them were eligible for the roof shape quest, and most of them don't qualify as _Easily answerable by everyone from the outside_.

(since v30 I also answered the quest some 15+ story buildings, but for _all_ of them the roof was flat, so think for high buildings there is very little value to be added anyway)

**Comment by Helium314** [comment]
@westnordost I just got the roof quest for an 8 level building without `roof:levels`, despite 8/(0+2) being larger than 2.

In https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShape.kt it looks like _isRoofProbablyVisibleFromBelow_ always returns `null` if `roof:levels` does not exist (line 53). Since the result of _isRoofProbablyVisibleFromBelow_ is only compared to `false`, `null` is treated like `true` (lines 34 and 43).
No `roof:levels` means that the roof shape quest is always shown (at least if roofs are not usually flat in my country)

**Comment by westnordost** [comment]
#2666

**Comment by timor** [comment]
I was about to open an issue like this when I found this.  From what I have mapped so far, I was confronted with a number of buildings I _thought_ I had the roof shape correct, but when I checked aerial footage, I noticed I was off. In effect, I stopped tagging roofs except for when I could see them from quite a distance away, or had aerial footage for cross-checking.  Could there be a kind of minimum distance based on the number of levels the building has? E.g. for something like 2+1 levels, it is easy to spot a high hipped roof when standing only 20 meters away, but telling the difference between `roof=mansard` or the mansard-like one with the flat top (what's the value for this?), or a very flat hipped roof is already impossible.

So the question is, in addition to the building levels, could the quest be hidden if you stand too near? Should that be a separate issue?

**Comment by matkoniecz** [comment]
> Should that be a separate issue?

Yes, in general comments in closed issues are very likely to be missed. New issues are cheap and at least I prefer them - if issue is related to some closed issue just link it.

Though in this specific case I am not entirely sure that it is doable in a good way
