### ISSUE TITLE
Allow for more frequent map data refreshes

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#2611]
**Use case**

In my area there's a lot of missing buildings and also some other map errors that have to be fixed before being able to accurately solve some quests via StreetComplete. Until a few hours ago I'd have said that changes to the OSM data don't appear on the rendered map at all, but tonight it finally updated, so it takes perhaps a few days to show up. One problem with that is that quests will show up for buildings that are not visible on the map, because they're new. Or they refer to buildings that have replaced those that are visible on the map (e.g. when splitting/merging ways).

**Proposed Solution**

Shortening the lifetime of the map cache might be one option, albeit at the expense of more data being transferred, so perhaps that has to be balanced.

Another option would be to provide an explicit option to refresh the map itself, just like there's already an option to do so for quests.

A third option, that at least would solve the quest/map mismatch would be to not show quests pertaining to objects that are new or have changed shape/position since the map tile has been cached.

**Comment by matkoniecz** [comment]
> Another option would be to provide an explicit option to refresh the map itself, just like there's already an option to do so for quests.

You can try uploading your solutions (if in manual upload mode), then reinstalling the app (and logging in again). Or removing app data.

This will not lose anything as data is uploaded to OSM, even star count will be synchronized.

It may be useful in general - what is the current delay between editing in OSM and update on JawgMaps, used to display background map?

**Comment by riQQ** [comment]
See also #2479

**Comment by westnordost** [comment]
Okay, I reduced the max age until the map data is not consiered fresh anymore to 12 hours (in the development branch)

**Comment by ygra** [comment]
Sorry for not finding #2479. I searched, but apparently not for the right keywords ...

**Comment by matkoniecz** [comment]
> Sorry for not finding #2479. I searched, but apparently not for the right keywords ...

If you looked that it is not a problem! And now anyone looking will have an easier job :)
