### ISSUE TITLE
Z-fighting in place=square

### ISSUE THREAD

**Issue by tguen** [streetcomplete/StreetComplete#2612]
I found a few areas with z-fighting issues. They are all tagged as `place=square`. At high zoom levels they are rendered in gray which covers the paths through the square. If camera is tilted, the borders and steps are partly visible and flicker as the camera is moved. 

Here are 2: https://www.openstreetmap.org/#map=18/45.51875/-122.68054
and a third: https://www.openstreetmap.org/#map=19/45.52237/-122.67078

v30.0

**Comment by westnordost** [comment]
This is an upstream issue, please post this issue at https://github.com/tangrams/tangram-es/issues (if there isn't an issue like this already)
