### ISSUE TITLE
Option to turn the map in direction of my movement

### ISSUE THREAD

**Issue by godot42** [streetcomplete/StreetComplete#2614]
Please add a possibility to turn the map on the screen in the direction of my movement

Currently I even don 't understand the orientation at times. I had been standing at a crossing, not taking the quests, because I wasn't sure, what lane and street they now actually refer to. (And zooming/panning in and out to understand is really confusing)

- It is not to the north - north at top (there is a north indication going in a seemingly completely arbitrary direction.)
- It is not the direction of my movement - actually I would assume standing in the street 90 deg "the other direction"

Or is the feature there and I missed it ? Please add to the FAQ in this case (or refer me to it)

Thanks

Martin

Notes: 

- Fairphone 2
- GPS on
   already since quite some time
   mobile data on (so satellite data is available via internet)
   position seems fairly accurate

**Comment by TurnrDev** [comment]
It does have the option when the GPS is pinned to your current location

**Comment by FloEdelmann** [comment]
See also #1040 and #2191

**Comment by godot42** [comment]
I KNEW, there must be some duplicate... Just had been blind finding them.

**Comment by mnalis** [comment]
@godot42 also, https://github.com/streetcomplete/StreetComplete/issues/2209 might help with orienteering on the map
