### ISSUE TITLE
Make the house number visible if avilable (and not hidden by the quest)

### ISSUE THREAD

**Issue by godot42** [streetcomplete/StreetComplete#2615]
It would be nice to see the house number (if already set) if a quest refers to a house.,
Currently I don't see it / it might be hidden by the quest itself.
This would help make sure I answer the quest for the correct house. (Currently I have to count: "Ok, this is the fourth house out of  five  row houses here (...and yes my view of reality and OSM agree, that there are fifth row houses)"

**Comment by FloEdelmann** [comment]
See also #1609 and #2364

**Comment by godot42** [comment]
I KNEW, there must be some duplicate... Just had been blind (again) finding them. Thanks for pointing out.
