### ISSUE TITLE
Steps clarification

### ISSUE THREAD

**Issue by pl71** [streetcomplete/StreetComplete#2617]
Regarding steps, IMHO `material` key is more appropriate than `surface`.
Sand, dirt, cobblestones... all that is more or less appropriate to roads than steps, 
and these values can go to a submenu not to clutter the main screen.
The picture of stones is not so relevant when we have steps made of stones. 
You know how stone steps look like.

**Comment by matkoniecz** [comment]
> Regarding steps, IMHO material key is more appropriate than surface.

StreetComplete is following standard tagging (see https://taginfo.openstreetmap.org/tags/highway=steps#combinations )

Do you have any reason to expect that https://wiki.openstreetmap.org/wiki/Tag%3Ahighway%3Dsteps is wrong? (disclaimer: yes, I am one of authors of that page)

>  Sand, dirt, cobblestones... all that is more or less appropriate to roads than steps,

See `surface=dirt` case in https://wiki.openstreetmap.org/wiki/Tag%3Ahighway%3Dsteps#Examples 

Do you expect that it is wrong? (I added that after noone objected to this for quite long time - see https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dsteps/Archive_1#trail_steps )

**Comment by pl71** [comment]
Yes, I fully agree with the wiki page. Anyway, pictures in StreetComplete are not the same. Especially for `stone`. 
Regarding the `surface=dirt `case in the wiki - looks like a dirt path with wooden steps, or `flat_steps`.

**Comment by matkoniecz** [comment]
> pictures in StreetComplete are not the same

It is not necessary for images to be exactly the same - it is enough to convey the same meaning.

Is anything wrong with StreetComplete images?

**Comment by westnordost** [comment]
No  answer
