### ISSUE TITLE
Ability to add answer the same type of quest for several items in one go

### ISSUE THREAD

**Issue by godot42** [streetcomplete/StreetComplete#2618]
I stand on a street and can see the shape of the roof of several (free standing) houses across the street. For three of them in a row, SC is asking for the root type.

It would be nice to be able to select all of the quests and answer them in one go.
Note: After I answered it for the second building, SC asked back, whether I'm checking in reality. Yes, I see this concern, also for the my proposed feature. So I'm quite fine with "No, we won't do it because..."
I'm also not sure, if this should be set only for specific quests; only for certain pre-conditions, ....

[Also I might just create my next duplicate - despite trying to find an existing entry.]

**Comment by smichel17** [comment]
It is a duplicate; I've done the same thing. https://github.com/streetcomplete/StreetComplete/issues/826#issuecomment-362786776

If you remember what keywords you searched for, please add them in a comment so that this one will show up for the next person!
