### ISSUE TITLE
when swiping at the edge of downloaded tiles they're weird

### ISSUE THREAD

**Issue by Identitaet** [streetcomplete/StreetComplete#2619]
Disclaimer
I'm unsure if it's even a bug but it's a bit strange and I wanted to check.

**How to Reproduce**
Download quests and the tiles wich belong to them.
Activate airplane mode
Swipe till the edge
You'll see it switching between both versions weirdly
https://youtu.be/YcI6JAy6QoA

**Versions affected**
The new one with team mode but might already be older.

**Comment by westnordost** [comment]
Thanks, I added your video to the upstream issue
