### ISSUE TITLE
ask for level:ref of shops/amenities inside multistory shopping centers

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2620]
### General
Affected tag(s) to be modified/added: [level:ref](https://wiki.openstreetmap.org/wiki/Key:level:ref)
Question asked: **What level number is this X on?**

Asked for all shop=* or amenity=* inside a shop=mall area and inside a building area with building:levels > 1.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
Yes established tag, very useful for data consumers to know what level the amenity/shop is on.

Two tags for levels exist https://wiki.openstreetmap.org/wiki/Key:level and https://wiki.openstreetmap.org/wiki/Key:level:ref. `level` requires a numeric value, however shopping centres might have LG, G, UG, 1, 2, 3 etc signposted which would be the values for `level:ref` but `level` would need to be LG -> 0, G -> 1, UG -> 2, 1 -> 3, 2 -> 4, 3 -> 5. So I'm suggesting `level:ref` since this is the value that corresponds to the level code which is directly surveyable from wayfinding signage, elevator signage etc.

Alternatively we could allow for either level:ref or level. With level being used if level number is calculated by counting floors, or level:ref if level code/number is based on signage.

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

Yes, a value for level:ref is set.

- [x] 🐿️ Easily answerable by everyone from

Yes, typically 

- [x]  the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by westnordost** [comment]
Is this not a duplicate of #1487?

**Comment by andrewharvey** [comment]
seems like it, I searched and read through a bunch of tickets but not sure why I didn't find this one
