### ISSUE TITLE
[Bug|FR] Do not ask for level count of outline

### ISSUE THREAD

**Issue by limbusdev** [streetcomplete/StreetComplete#2621]
Complex buildings are modeled as a relation containing a polygon of some building type with role "outline" and multiple polygons of type "buildingpart" with role "buildingpart".

I expect the app to ask for the level count, roof type and so on for each building part. But not for the outline.

Cheers,
Georg

**Comment by westnordost** [comment]
Duplicate of #606?

**Comment by limbusdev** [comment]
Almost. So it's rather a FR to be able to set levels of building parts.

**Comment by matkoniecz** [comment]
`building:part` may be created for many reasons, many of them have no way to set them `building:levels` - so asking for all of them makes no sense.

Also, if someone splits building in such parts in general they are setting `building:levels` if needed.

Is there a way to detect `building:part` where asking this makes sense?
