### ISSUE TITLE
[Bug|FR] Do not ask for housenumber of buldings with address node

### ISSUE THREAD

**Issue by limbusdev** [streetcomplete/StreetComplete#2622]
Some building that have multiple entries, have multiple addresses - sometimes even with different streets. In such cases it is good practice to create nodes as part of the building polygon and give them the type "address". So each entry gets the correct address.

In those cases (if a building polygon contains an address node), the app should not ask for an address of the whole buiding.

Cheers,
Georg

**Comment by westnordost** [comment]
The housenumber quest is disabled for France.

See #2427 and https://t.me/osmfr/26320

**Comment by HolgerJeromin** [comment]
I think "FR" is feature request and not "France", but I could be wrong.

**Comment by matkoniecz** [comment]
> Do not ask for housenumber of buldings with address node

StreetComplete is already avoiding this.

Is it possible that node is outside building geometry? Can you link any specific situation where this happens?

**Comment by limbusdev** [comment]
Yes. With FR I mean "feature request".

**Comment by westnordost** [comment]
Okay, anyway, see @matkoniecz

**Comment by limbusdev** [comment]
Yeah. Seems to be right. Worked now : )
