### ISSUE TITLE
Stairs: which side up quest

### ISSUE THREAD

**Issue by DennisKempel** [streetcomplete/StreetComplete#2623]
Hello, I am relatively often answering the stairs quest that asks to note which side of the stairs leads up. For some reason I am not getting behind this. Comparing the quest to the "has this road a footpath" I feel like I should press either left or right side whichever would likely be used to access the stairs direction upstairs. However, it seem sthe quest marks alsways the left side as "this side up" on the drawing. Is there a bug? I do not feel it makes any difference which side I enter.

**How to Reproduce**
Answer a stairs quest

**Versions affected**
latest stable android

**Comment by westnordost** [comment]
There is a discussion forum with Q&A where you could ask this. Anyway, also a duplicate.

#2239

Please make the effort and search in the issue tracker before you post an issue. The triaging of ever the same issues takes away valuable development time. Today I closed 5 issues that were duplicates.

**Comment by DennisKempel** [comment]
I did search, not not the forums, sorry.
