### ISSUE TITLE
Map orientation "direction heading"

### ISSUE THREAD

**Issue by DennisKempel** [streetcomplete/StreetComplete#2624]
When mapping I would prefer the map orientation "direction I am heading to" over all else. I now this exists and thanks also for making the movements more smooth with some recent update. However, after having answered the first quest the app does not seem to get back into the "direction heading mode" and pressing the littel compass item only switches between north and some other direction, but it never seems to be the real direction I am heading in.

**How to Reproduce**
Map some quest while in "direction heading map orientation mode"

**Versions affected**
Android, latest

**Comment by westnordost** [comment]
#1040

**Comment by DennisKempel** [comment]
...not sure. I have read the other issue, but it seems to be related to magnets? I have no issue with my Pixel 3 and compass mode on Google maps, for example. Also, it does work on start in SC, just no more after having answered the first quest. It seems to me.

But nevermind, I appreciate the great work you do on SC and love mapping the world with it.

**Comment by mnalis** [comment]
@DennisKempel yes, magnets (also called "compass") is what mobile phones often use to see in which direction they are pointing - it only works if the phone is held (mostly) horizontally. That compass/magnet reading then can be used either to show the user direction it is facing, or to rotate whole map so physical area in front of user is on the upper)part of the phone screen "in front of" point showing user position. 

This is the way SC currently determines direction you are facing, and is very useful as you can (for example) simply rotate to your right and map also rotates in such a way that what you see in front of you is in front (on the top part) of your screen.
Unfortunately, that does not work well if you are either not holding your phone horizontally, or if you are having magnets or electromagnetically active devices close to you phone, of if your phone does not happen to have compass ([Pixel3 does](https://www.gsmarena.com/google_pixel_3-9256.php)).

The other way to determine the direction (that you are generally going in) is to sample your GPS coordinates over some distance, and then calculate in what direction you seem to be going. Advantage of that method is it can work if your compass doesn't work and is less jittery. The disadvantage is that it is also more lagging (ie. if you change direction it won't change instantly but after some number of meters if traveled), it will always show average if you are moving in zig-zag pattern (so never showing correct direction in that case),  and it cannot show you direction unless you are actively moving (ie. you have to walk for example 50m in one direction for it to pick it up - if you just rotate in place, it won't detect you are now looking in another direction). 

So, #1040 was about adding support for this mode of operation too (if user chooses that).
