### ISSUE TITLE
Disappearing quests

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2628]
Sometimes (very rarely) it happens that most/all of the quests simply disappear while mapping. This is not a huge problem as the can be downloaded again, but very confusing when it occurs.

Today I went answering quests, and after a while they were gone, maybe after uploading a bunch of answered quests. A few quests remained (mostly roof shapes); I strongly suspect these were at places where I had previously answered some (building level) quests. I had to download the area again to make the other quests come back.

I had originally downloaded the area quite a while ago, so I think that the quests were auto-deleted 2 weeks (?) after the orignial download. But just yesterday I had invalidated the quest cache, and had the area downloaded / updated just an hour before all the quests disappeared.

So I suspect that re-downloaded quests still retain their original download date. Could this be the what was happening? And then I was going through this area almost exactly 2 weeks after the initial download?

**Comment by TurnrDev** [comment]
I've had issues with quests not updating even after invalidating the cache. I thought it might have been an overpass issue

**Comment by smichel17** [comment]
As far as I understand, invalidating the cache means exactly those words — it is not the same as *clearing* the cache. So it only means that when new data is received, it will replace the old data, not that the old data will immediately disappear.

**Comment by Helium314** [comment]
> It only means that when new data is received, it will replace the old data

This is what I am not sure about, It might be that unchanged data is not replaced (which makes sense, except for the download date)

**Comment by westnordost** [comment]
> So I suspect that re-downloaded quests still retain their original download date. Could this be the what was happening? And then I was going through this area almost exactly 2 weeks after the initial download?

That is possible. But I am completely refactoring that part anyway.

**Comment by westnordost** [comment]
(Disclaimer: I didn't check)

**Comment by westnordost** [comment]
You are right, @Helium314: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquest/OsmQuestDao.kt#L77

So after a month or so, even if that quest was re-downloaded, it will be cleaned up.

**Comment by Helium314** [comment]
> But I am completely refactoring that part anyway.

Good to hear, so at least this shouldn't be additional work
