### ISSUE TITLE
Quest priority (or overlaping quests)

### ISSUE THREAD

**Issue by MarcinOrlowski** [streetcomplete/StreetComplete#2629]
If there is more than one quest for the same location, they overlap and this leads to problems. For example. If there's a mailbox, first I get the quest about what is the time for mails to be taken out. Once I answer that, I get the question to confirm if the mailbox is still there :) It's often not. But I still have to answer the first question about hours to tell, "no there's no mailbox".

Other problem overlapping (or multiple quests per point) causes: imagine stairs. You can have quests: how many stairs are there, what the direction is, what type of stairs is it, does it have a handle. But because all these are for the same element, their overlap. And if I drive by (so I can often say if there's a handle or what direction it is) I cannot tell how many steps are there or what type is it. But... these questions are shown first so in result I cannot give any update to the element.

The solution would be to show a dialog/popup with all quests for that point. I could then select which one I want/can solve.

**Comment by matkoniecz** [comment]
> But I still have to answer the first question about hours to tell, "no there's no mailbox".

Note that in "other answer..." answer there should be "it does not exist"

Is

> Once I answer that, I get the question to confirm if the mailbox is still there :) It's often not

still happening in case of using that option?

**Comment by matkoniecz** [comment]
> The solution would be to show a dialog/popup with all quests for that point. I could then select which one I want/can solve.

Seems to be covered by #124

**Comment by MarcinOrlowski** [comment]
> Note that in "other answer..." answer there should be "it does not exist"

This is just an example. It this particular case it might work, but I still do not know if there are other quests.

> still happening in case of using that option?

No. But that's UX bug anyway.

**Comment by MarcinOrlowski** [comment]
> Seems to be covered by #124

Perfect. Upvoted.

**Comment by matkoniecz** [comment]
> This is just an example. It this particular case it might work

If that specific case (question asked about something marked as gone) is present then it may be a separate bug (as the question should not be asked after app got machine-readable info that object is gone and is scheduled for deletion).

> Perfect. Upvoted.

Great! +1 helps to notice what is wanted (what is useful to know especially for complex issues like that one)
