### ISSUE TITLE
Add skybridges/skyways as an option to the building quest

### ISSUE THREAD

**Issue by Identitaet** [streetcomplete/StreetComplete#2630]
**Use case**

Enable mapping of such structures
(I mean those enclosed skyways which have a roof and walls like 
http://correctionalnews.com/wp-content/uploads/2018/09/SonomaCounty-800x445.jpg
Or
https://placesjournal.org/wp-content/uploads/2016/05/yoos-james-multilevel-metropolis-15.jpg
**Proposed Solution**

Ideally add a tag for those kinds of structures

Sadly it's a bit unclear how to tag them but I found this
https://wiki.openstreetmap.org/wiki/Item:Q16636

**Comment by matkoniecz** [comment]
>  https://wiki.openstreetmap.org/wiki/Item:Q16636

Note that it is contentless bot-generated data item page. If there is no entry on OSM Wiki then taginfo entry is far more useful (in this case: https://taginfo.openstreetmap.org/tags/?key=building&value=skyway )

**Comment by westnordost** [comment]
I'd say that this building type (if you can say that it is a building) is far too rare to be in that list. Better leave a note in that case.

**Comment by Identitaet** [comment]
Okay so I didn't find the right tag at first

But I checked again and it seems that instead of skyway building=bridge is used
https://taginfo.openstreetmap.org/tags/building=bridge

This one got 1.5k uses
Don't know if you'd consider that relevant enough

**Comment by Discostu36** [comment]
I also think `building=bridge` should be added. These structures are very common in urban areas, and it should be possible to tag them correctly with SC.

**Comment by kmpoppe** [comment]
Given we have "Pagoda" in the "Religious Buildings" area, which has less than 150 uses in the map, I'd also say, that adding `building=bridge` with 1.7k uses wouldn't be totally out of touch. Additionally, @Discostu36 has cleaned up the Wiki to make it clear, what that tag means.

Again, in my urban area there are plentyful where that'll apply:
![grafik](https://user-images.githubusercontent.com/24451207/134779547-f93d9853-7133-45e4-828a-064e5a1e9266.png)

That would be my solution that I can PR any time, given @westnordost would accept it.
![grafik](https://user-images.githubusercontent.com/24451207/134779569-56fce866-9065-46c9-a42d-efa504a2f27c.png)
![grafik](https://user-images.githubusercontent.com/24451207/134779585-66cce429-b37c-4788-ac5d-cbfd4d1576c6.png)

**Comment by westnordost** [comment]
Oh, that's the meaning of `building=bridge`?

**Comment by westnordost** [comment]
Anyway, the icon looks good. Since you seem to already have implemented it, care to create a PR to include it?

**Comment by kmpoppe** [comment]
Done. Included a German translation (as per my testing), if you want this to be done with POEdit, you can remove the file from the branch as I allowed edits from maintainers.
