### ISSUE TITLE
Add elevators/elevators to building type quest

### ISSUE THREAD

**Issue by Identitaet** [streetcomplete/StreetComplete#2631]
**Use case**

https://www.openstreetmap.org/way/316934510
Here we have a micrommaped part of a building
I'd be more accurate to have building=elevator here
**Proposed Solution**

Add elevator (shafts) as a building type

**Comment by westnordost** [comment]
Hmm, is the building=yes even correct there? Should this be classified as a building at all? What would be the tagging for this?

**Comment by Identitaet** [comment]
Well ideally I'd be building:part=elevator since it's basically always part of a building

**Comment by Identitaet** [comment]
Well ideally I'd be building:part=elevator since it's basically always part of a building (https://www.openstreetmap.org/way/329832856)

I guess I'd be required to ask if it's a building part but that just seems quite weird and vague

**Comment by matkoniecz** [comment]
Some are standalone.

Not entirely how to deal with it, so far I was using `building=elevator_housing` for ones where StreetComplete user in Warsaw created notes.

For this specific one `building=transportation` would also fit (part of a subway station).

![external-content duckduckgo com](https://user-images.githubusercontent.com/899988/109836830-db12e100-7c44-11eb-85b4-a520eda91de7.jpeg)

**Comment by Discostu36** [comment]
`building=elevator` is not a common tag on OSM. 

![grafik](https://user-images.githubusercontent.com/30999326/110036396-3aecb300-7d3d-11eb-80dd-174d1d406eed.png)
(statistics from [taginfo](https://taginfo.openstreetmap.org/search?q=elevator#values))



The [documented](https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator) and often used alternative is `highway=elevator`. I don't think streetcomplete should provide the possibility to tag this as a building. Users should leave a note instead: "this is not a building".

**Comment by matkoniecz** [comment]
> I don't think streetcomplete should provide the possibility to tag this as a building. 

StreetComplete is only asking if someone already tagged them as `building=yes` (what for say https://github.com/streetcomplete/StreetComplete/issues/2631#issuecomment-789838622 seems acceptable).

But use is so low that one should probably use note anyway.

**Comment by Identitaet** [comment]
Yeah seems reasonable
