### ISSUE TITLE
Cycleway quest can add incorrect sidewalk tag

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2633]
On a road which does not have a sidewalk or cycleway tagged and the cycleway quest is answered with "explicitly shared-use sidewalk" on one side and "none" on the other, the tags that are added are
`cycleway:left = track`
`cycleway:segregated = no`
`cycleway:right = no`
Which are all correct (left and right as appropriate).

But it also adds `sidewalk = left`
This implies there is ONLY a sidewalk on the left, and it means that the sidewalk quest does not then show up.

In the case that there is also a sidewalk on the right (which is only for pedestrian use) it is not possible to add this information.

I agree that the sidewalk tag is added in this case, so I see a few different options:

1. When the quest is answered this way it should then immediately ask about the sidewalks.
2. Tag `sidewalk:left = yes` (and don't tag `sidewalk:right` or `sidewalk`). Then also adjust the sidewalk quest so that it is asked for roads which have one of `sidewalk:left` and `right` set (but not both). This could be a separate enhancement, as roads with one of those tagged but not the other seems like incomplete data to me.
3. Make the sidewalk quest show up before the cycleway quest by default.
4. Don't add the `sidewalk` tag in situations like this.

Each of these has problems though:
1. This isn't how any other quest works, and users may not want to tag sidewalks, or at least not want to tag them immediately.
2. `sidewalk:left` and `right` are not very widely used or supported (~2,000,000 uses of `sidewalk`, ~20,000 uses of `sidewalk:left` and `right` combined).
3. Cycleway information is more useful, so in general it should show up first.
4. If the sidewalk quest is not then answered, this leaves the information incomplete and arguably incorrect.

**Comment by westnordost** [comment]
Hm, right. Good analysis. You are right, none of the options is optimal. Not sure what should best be done about it.

**Comment by westnordost** [comment]
Maybe: Only add **any** `sidewalk=*` tag if the sidewalk situation is defined (implicitly) on **both** sides.

**Comment by westnordost** [comment]
So yeah, I implemented option 4.
