### ISSUE TITLE
Cannot build on Linux since adding checksums of dependency libs

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#2637]
Since f1a4fd1fb9db7d7c8a05cea3cd5d18a720bfad8f, trying to build on Linux results in this error message:
```
> Dependency verification failed for configuration ':app:_internal_aapt2_binary'
  One artifact failed verification: aapt2-4.1.2-6503028-linux.jar (com.android.tools.build:aapt2:4.1.2-6503028) from repository Google
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.6/userguide/dependency_verification.html#sec:troubleshooting-verification
```
It also generates a report that says, if I'm confident this is a false positive, I can generate the missing verification metadata with
```
gradle --write-verification-metadata sha256 help
```
Running this allows me to build, and produces the following diff:
```diff
diff --git a/gradle/verification-metadata.xml b/gradle/verification-metadata.xml
index 43b17d62d..38d43deb4 100644
--- a/gradle/verification-metadata.xml
+++ b/gradle/verification-metadata.xml
@@ -606,6 +606,9 @@
          </artifact>
       </component>
       <component group="com.android.tools.build" name="aapt2" version="4.1.2-6503028">
+         <artifact name="aapt2-4.1.2-6503028-linux.jar">
+            <sha256 value="562e25ec5223cca805cac6284a250dfebbc5ba24c9f619da7819995405bdbf88" origin="Generated by Gradle"/>
+         </artifact>
          <artifact name="aapt2-4.1.2-6503028-windows.jar">
             <sha256 value="6106c332d0168a97f3bac1868cffe82af28b2953c91a781a033e5e04be8fe2f8" origin="Generated by Gradle"/>
          </artifact>
```
…which is how I figured out that it's a result of building on Linux — there's a different version of build tools.
I have not done any verification of this hash, but I could send a PR with the change if you'd like.

---

Aside: Originally it actually produced a *bunch* of cryptic error messages that basically prevented me from running *any* gradle task. I ended up having to manually `rm -rf ~/.gradle/caches`, at which point this was the only error left.

**Comment by westnordost** [comment]
Yeah, looks like that featur eof gradle somehow does not work correctly (yet). On my dev branch, I already removed that checksum library again...

I think I will remove it on master, too. Then, regenerate it before changing the repository resolution order from jCenter -> maven central to maven central -> jCenter.

(FYI jCenter is being shut down, all the library authors need to post their libs somewhere else, possibly maven central. The checksum stuff is a security measure, to ensure that the dependency is not silently exchanged with another malicious one)
