### ISSUE TITLE
Don't ask for roof shape of terraced houses

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#2638]
**Use case**
This is a follow-up to #2609. I think the new feature of not asking roof shape for high buildings is good but maybe it could be improved even further. If you are standing in front of terraced houses with 4-5 levels (e.g. in Kiel, Germany) it is not possible to determine if the roof shape is gabled or saltbox. The difference can only be seen from the side, but the side view is obstructed by the adjacent buildings. 
[![Building seen from front, roof shape not possible to determine](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/D%C3%BCppelstra%C3%9Fe_%2807%29_%2826860900558%29.jpg/320px-D%C3%BCppelstra%C3%9Fe_%2807%29_%2826860900558%29.jpg)](https://commons.wikimedia.org/wiki/File:D%C3%BCppelstra%C3%9Fe_(07)_(26860900558).jpg)

**Proposed Solution**
If a building has more than 4 levels and is connected to at least 2 other buildings (sharing at least 2 nodes with each), don't show the roof quest.
![grafik](https://user-images.githubusercontent.com/30999326/110035947-97030780-7d3c-11eb-897b-511dc01ca390.png)

Maybe this use case is too "special", but I'd be interested in your thougths.

**Comment by westnordost** [comment]
Yeah to be honest, I find that is far too much implementation complexity for some kind of smartness that is not even that accurate (both on the false-positive and on the false-negative side).

**Comment by peternewman** [comment]
You'd technically need to check the height of the adjacent buildings too, consider attached garages on either side of a tall building, it would incorrectly fail this test.
