### ISSUE TITLE
Sport pitch lighting

### ISSUE THREAD

**Issue by boothym** [streetcomplete/StreetComplete#2639]
Since the app is already asking for the sport and surface of a pitch, I thought asking users for lit=yes/no on pitches would be a good idea for a new quest.

The question would be: Is this sport pitch lit? or Does this sport pitch have floodlights?

Useful for football pitches, skateparks etc.

**Comment by peternewman** [comment]
It would help if you can use the template @boothym :
https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md

You can always edit your existing issue

**Comment by matkoniecz** [comment]
Note that `lit=yes` may apply without floodlights.

**Comment by boothym** [comment]
@peternewman well I've mentioned the affected tag, question to be asked and considered the checklist - is there any more information in particular that is required?

@matkoniecz can you give an example?

**Comment by matkoniecz** [comment]
Small pitches may be lit by regular street lamps present nearby.

**Comment by Helium314** [comment]
> can you give an example?

in many parks there are small pitches that are lit well enough for walking, but there is no floodlight

**Comment by boothym** [comment]
Fair enough - the question doesn't have to be about floodlights then, suppose it's similar to the lit question for paths/roads.

**Comment by peternewman** [comment]
> @peternewman well I've mentioned the affected tag, question to be asked and considered the checklist - is there any more information in particular that is required?

I thought it auto-labels something, but it seems not.

It would at least mean it was laid out in a consistent way with other quest suggestions which makes it quicker for people to look for them and compare them.

You haven't actually detailed the element selection, I assume you're just thinking `leisure=pitch`?

But presumably it should exclude the indoor tennis court:
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch#Indoor_tennis_court

And possibly the table tennis table; is the pitch actually lit, or the general area?
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch#Table_tennis_table

As @matkoniecz sort of alluded to (although I assume that is more a reference to say a small basketball hoop):
> Small pitches may be lit by regular street lamps present nearby.

**Comment by boothym** [comment]
Yes I do mean leisure=pitch.

I had a read of the new quest issue template and I feel that I followed it. Given there's already other quests for leisure=pitch - i.e. surface, sport - plus path/road lighting, then it met the checklist criteria and implementation/GUI is similar to those quests. ☺️ 

Indoor pitches and buildings are already excluded from the sport quests: https://github.com/streetcomplete/StreetComplete/blob/d32bc3c0f49d6c53248e5d097ea1b74641f196a2/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddPitchSurface.kt#L29

Suppose it is slightly subjective but that's not any different for example to someone marking a path as lit when there's overspill light from a road. But if it too dark to play table tennis when the sun's gone away then it's not lit! 😉

**Comment by smichel17** [comment]
There are two purposes of the checklist. One is to prevent adding bad quests. The other is to make it easy to discuss whether a quest should be added. If you include the checklist, along with a short explanation of your reasoning, like the template suggests, then it's easy for someone to point to where they disagree. Without that, it puts the burden on the person replying to tie your reasoning to the checklist and then state their disagreement.

**Comment by eginhard** [comment]
I will try to implement this, as discussed with @matkoniecz on Discord.
