### ISSUE TITLE
"Does this still exist? ($BRAND)" is too unspecific

### ISSUE THREAD

**Issue by schuetzm** [streetcomplete/StreetComplete#2640]
**How to Reproduce**
Not sure how to reproduce. I was walking around with my mobile phone which has no mobile internet access, so the quests I solved were not being uploaded immediately; now that they've been uploaded at home, the quest has disappeared.

After entering the collection times for [this postbox](https://www.openstreetmap.org/node/366339764), a new quest appeared at the same position asking "Does this still exist? (Deutsche Post)". So, the first problem is that it's not clear what the question is referring to; it would be nice if it asked "Does this *postbox* still exist?" or something similar.

As right next to it there is a phone, I was not sure whether the question was actually about the postbox, or if it was about the phone which someone might have accidentally mistagged. I've now checked this, and the phone is correctly tagged with "Deutsche Telekom AG" as operator, so I assume the quest was indeed referring to the postbox. This then leads to the second bug/problem: As I've just entered the collection times of this postbox, it's pointless to ask whether it still exists...

**Versions affected**
StreetComplete v30.1, German language

**Comment by TurnrDev** [comment]
When online, I've always had answering the times make it skip the "does this still exist?" question. I wonder if this is related to being offline?

**Comment by smichel17** [comment]
Probably yes. https://github.com/streetcomplete/StreetComplete/issues/2506 may change that.

**Comment by westnordost** [comment]
No, it isn't related to being online or offline.

Anyway, @schuetzm , this has been fixed by @FloEdelmann 16 days ago and the fix is part of the v31.0 release that I released a couple of days ago 😄

**Comment by westnordost** [comment]
If you got the app from F-Droid, it may take up to a few days to months till it is updated.

**Comment by schuetzm** [comment]
@westnordost Yes, I'm used to the delays by now :-) Just to be sure, the first issue was fixed in [this PR](https://github.com/streetcomplete/StreetComplete/pull/2594), right? The second (minor) problem of the existance being asked is probably not fixable easily, because quests cannot take previous answers into account before the data is re-downloaded...

**Comment by Helium314** [comment]
Not sure, but it might be fixed as part of #2506

**Comment by FloEdelmann** [comment]
In #2594, it was fixed that the existence quest didn't show the feature name, but only the element name. I.e. it should be now "Does this postbox still exist? (Deutsche Post)" instead of "Does this still exist? (Deutsche Post)".

The issue that the existence quest is shown right after answering the collection times quest may be related to offline mode, but will probably be fixed as part of #2506.
