### ISSUE TITLE
Expand note selection

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#2641]
Currently notes are only shown if they contain a question mark. I think that should be expanded to also check for "#suveryme". It's used in the UK when something needs to be check on the ground, we have a QA tool that highlights theses notes, although a lot of them overlap by also containing a question mark not all of them do. I find myself rephrasing some notes to contain a question mark just to get it visible in StreetComplete.

**Comment by westnordost** [comment]
Can you provide some numbers on #surveyme?

**Comment by westnordost** [comment]
Also, do you know that you can change this in the settings? (to show all notes you haven't contributed to yet)

**Comment by Cj-Malone** [comment]
> Can you provide some numbers on #surveyme?

No, I don't know how to query notes.

> Also, do you know that you can change this in the settings? (to show all notes you haven't contributed to yet)

I know that, but default is king. That also  doesn't change that these notes have been tagged as needing on the ground knowledge, and StreetComplete is a on the ground OSM editor.

**Comment by ENT8R** [comment]
> Can you provide some numbers on #surveyme?

[https://ent8r.github.io/NotesReview/?query=#surveyme&limit=1000&closed=true](https://ent8r.github.io/NotesReview/?query=%23surveyme&limit=1000&closed=true) returns 605 notes in total and 411 notes which are still open as of now.

**Comment by mnalis** [comment]
> [https://ent8r.github.io/NotesReview/?query=#surveyme&limit=1000&closed=true](https://ent8r.github.io/NotesReview/?query=%23surveyme&limit=1000&closed=true) returns 605 notes in total and 411 notes which are still open as of now.

@ENT8R  Interestingly, that link just forwards to the main page without doing the query specified (both in Firefox and Chromium). But I can manually enter the query and it works just fine then! Nice tool, BTW

**Comment by Marc-marc-marc** [comment]
there are even more notes with #survey, wouldn't it be relevant to include it ?

**Comment by westnordost** [comment]
Maybe. Would you like to do some research as to whether the #survey hashtag is actually used to denote that?

**Comment by westnordost** [comment]
Tried to do the research, however, when entering #survey, even "#survey", NotesReview searches simply for "survey" (without the hashtag).

Created a bug report here. https://github.com/ENT8R/NotesReview/issues/66

**Comment by westnordost** [comment]
Ok I researched via http://resultmaps.neis-one.org/osm-notes (click on country, then on "only open notes".
#surveyme is only really used in UK so far. #survey is not used at all. There are like 6 or so of them in France, but all these **also** include #surveyme.
