### ISSUE TITLE
Duplicate answer possibility

### ISSUE THREAD

**Issue by AlertSubject** [streetcomplete/StreetComplete#2642]
When you answer the "who accepts donations for this clothing bin" quest in Germany it will show you suggestions based on what you type 
When trying to enter "Deutsches Rotes Kreuz" it'll suggest both that name as well as "Deutsches Rotes Kreuz e.V"
The average user is unlikely to know which one to pick and so am I

**How to Reproduce**
Find the above mentioned quest in Germany and start typing deutsches Rotes Kreuz 
Suggestions will pop up 

**Versions affected**
Android 10
Streetcomplete 31.0

**Comment by matkoniecz** [comment]
This hints are autogenerated from OSM data, and are not curated manually in StreetComplete.

If this values are equivalent local community may decide to mass replace one by another (please consult with local community before doing anything, see https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct )

Polish community did it with `operator=Euronet Sp. z o.o.` vs `operator=Euronet` in automated edit documented at  https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fix_overly_verbose_Euronet_Sp._z_o.o.

**Comment by matkoniecz** [comment]
See  #2194 for previous discussion and more info. I will close this one as equivalent.

Note: in this specific case I am lacking local knowledge, mass edit may be a wrong solution. But it looks like exactly like a case where mass replace was a correct solution.

Note: before mass editing please read https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct  and obey it
