### ISSUE TITLE
Wrong surface tags on Dutch cycleways (highway=cycleway)

### ISSUE THREAD

**Issue by A67-A67** [streetcomplete/StreetComplete#2644]
The Netherlands has a lot of cycleways. Many of them, especially those along roads, have sidewalks. Pedestrians are allowed to use cycleways, if no separate footpath or sidewalk is available.

The established tagging scheme for the surface of those cycleways is the same as for roads: the tag surface describes the main area (in this case the cycleway), the tag sidewalk:surface, or sidewalk:(both|left|right):surface, describes the sidewalk surface.

StreetComplete users are adding different tags to the cycleways, that are tagged with highway=cycleway. They use cycleway:surface for the cycleway and footway:surface for the sidewalk. The tag cycleway:surface is even added as a duplicate when the cycleway already has a surface tag. When I try to correct it to the tagging scheme that we use in the Netherlands, the wrong tags are later added again as a duplicate.

It seems to be caused by the tagging in Germany, where cycleways cannot have sidewalks. These are considered combined foot-cycleways there. This is however not the case in the Netherlands. Here cycleways can have sidewalks. And cycleways with sidewalks aren’t combined foot-cycleways, they are cycleways.

I don’t know for sure, but I thought highway=path with bicycle=designated, foot=designated should be used on these German-style combined foot-cycleways. I think the tagging with cycleway:surface and footway:surface makes sense in that case. However when highway=cycleway is used, the surface tag clearly describes the cycleway.

So for a highway=cycleway, StreetComplete should use the tag surface for the cycleway surface and sidewalk:surface for the sidewalk surface. If this cannot be done globally, it should at least be corrected in the Netherlands.

**How to Reproduce**
The tags are added in the quest AddCyclewayPartSurface.

**Versions affected**
It is added by StreetComplete 21.0 and 31.0.

**Comment by matkoniecz** [comment]
Is this tagging scheme documented at OSM wiki?

https://taginfo.openstreetmap.org/keys/sidewalk%3Asurface seems to not be very common.

It is used 178 times worldwide in combination with `highway=cycleway` - https://overpass-turbo.eu/s/14OP

Is it actually a standard and/or preferred scheme? Is `cycleway:surface` actually considered as incorrect?

https://overpass-turbo.eu/s/14OR `cycleway:surface` has 1184 uses in just Netherlands, including uses on `highway=cycleway` (I have not investigated how much of that was added by StreetComplete), including 497 on `highway=cycleway` https://overpass-turbo.eu/s/14OU

**Comment by A67-A67** [comment]
The tag sidewalk:surface is normally used as sidewalk:both:surface, sidewalk:left:surface and sidewalk:right:surface as per [documentation](https://wiki.openstreetmap.org/w/index.php?title=Key:sidewalk&uselang=nl#Additional_tags).

[The wiki](https://wiki.openstreetmap.org/wiki/Key:surface#Surface_for_foot-_and_cycleways) describes both tags sidewalk:surface and cycleway:surface. The tag footway:surface is not described there. The tag cycleway:surface is used there for cycle lanes on roads, so a surface tag for a secondary part of the way.

The main usage for cycleway:surface in the Nehterlands is for cycle lanes. Those 497 on cycleways are presumably added by StreetComplete users.

**Comment by mnalis** [comment]
Those seem to be additional counts for those combinations:
- `highway=cycleway` + `sidewalk:both:surface`: 14 https://overpass-turbo.eu/s/14P4
- `highway=cycleway` + `sidewalk:left:surface`: 34 https://overpass-turbo.eu/s/14P5
- `highway=cycleway` + `sidewalk:right:surface`: 49 https://overpass-turbo.eu/s/14P6

**Comment by Famlam** [comment]
Also, to be complete, note that the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway) of `highway=cycleway` only lists `surface`, not `cycleway:surface`, as a useful combination. Usage: ~623k in combination with `highway=cycleway`, (compared to ~7k `cycleway:surface` cases). 

> I would say that in the worst case this tags are duplicates, or tagging schema considered locally as inferior - not incorrect

The [wiki](https://wiki.openstreetmap.org/wiki/Key%3Acycleway%3Asurface) of `cycleway:surface` clearly explains: *It is useful for `highway=*` tagged with `cycleway=*`* ***where just `surface=*` is not sufficient.*** 
It is also incorrect - as explained by A67-A67 - in the sense that there's no `cycleway` (lane, track, share_busway, ...) **on** a `highway=cycleway`. A `highway=cycleway` **is** the cycleway. (A sidewalk on a way is a "special lane", just like cycleway=lane and cycleway=track on i.e. `highway=primary`)

Besides that, the risk of having such unneeded duplicate tagging is also to get conflicting tagging; I've had a few cases already (and [more](https://overpass-turbo.eu/s/14Ph) exist) where it said something like `surface=asphalt` + `cycleway:surface=paving_stones` + `footway:surface=*`. Which is correct in that case?

**Comment by mnalis** [comment]
@Famlam I agree with you that on `highway=cycleway` just `surface=*` should be preferred tag for defining cycleway surface (same as 'surface=*' on 'highway=residential' marks a surface of residential road, or 'surface=*'  on `highway=footway` marks the surface of footway). 

As for **multiple tags, those are most probably errors**, although if we go strictly by definition those would be valid theoretically (eg. 58% is cycleway which is paving_stones, and 48% is footway which is something else, and everything remaining [so just 4% of separating space in between and on edges] is asphalt). 

But I do not think such nano-mapping is realistic - SC should probably just stick to main tag and **remove redundant ones** in this case. Specifically, I'd prefer it if SC on `highway=cycleway` would update `surface` and remove `surface:cycleway` (as that is by far the most common way to map it, as you note)

That would make [AddCyclewayPartSurface.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddCyclewayPartSurface.kt) somewhat more complicated however, as `highway=path|footway|bridleway` with `bicycle=yes|designated|...` should still be marked with `cycleway:surface` instead.

**Comment by matkoniecz** [comment]
> Also, to be complete, note that the wiki of highway=cycleway only lists surface, not cycleway:surface, as a useful combination. Usage: ~623k in combination with highway=cycleway, (compared to ~7k cycleway:surface cases).

Well, probably in many cases `highway=cycleway` is cycleway, not cycleway+footway (what may be considered as cycleway with sidewalk).

> The wiki of cycleway:surface clearly explains: It is useful for highway=* tagged with cycleway=* where just surface=* is not sufficient.

I know, I wrote most of that page ( https://wiki.openstreetmap.org/w/index.php?title=Key:cycleway:surface&action=history ) :)

> It is also incorrect - as explained by A67-A67 - in the sense that there's no cycleway (lane, track, share_busway, ...) on a highway=cycleway

But if `highway=cycleway` refers to something segregated in cyclist and pedestrian part - it has clear footway part and cycleway part, right?

> where it said something like surface=asphalt + cycleway:surface=paving_stones + footway:surface=*. Which is correct in that case?

In such case I would say that either `surface` was paved wrongly and it should be `surface=paved` or `surface=paving_stones` if `footway:surface=paving_stones`

----------------------------------------------

Is it actually a standard and/or preferred scheme? Is `cycleway:surface` actually considered as clearly incorrect in such case? Can you link me to a discussion on nl mailing list/forum/Discord/Telegram where such opinion is considered as consensus?

Because actual use of that tag is far too low to consider it as some established standard overriding global one - see https://github.com/streetcomplete/StreetComplete/issues/2644#issuecomment-792994870

**Comment by A67-A67** [comment]
`But if highway=cycleway refers to something segregated in cyclist and pedestrian part - it has clear footway part and cycleway part, right?`

There are two approaches. The 'German approach' is that paths cannot have sidewalks, so they are considered combined foot-cyclepaths. The 'Dutch approach' is that it's a cycleway with sidewalk, just as a road can have a sidewalk. These sidewalks even look the same and can be continuous where a road changes into a cycleway ([example](https://www.google.com/maps/@51.4616926,5.6189741,3a,75y,130.18h,71.64t/data=!3m7!1e1!3m5!1sK2oQHSQKnKT77nGAFkATow!2e0!6s%2F%2Fgeo3.ggpht.com%2Fcbk%3Fpanoid%3DK2oQHSQKnKT77nGAFkATow%26output%3Dthumbnail%26cb_client%3Dsearch.revgeo_and_fetch.gps%26thumb%3D2%26w%3D96%26h%3D64%26yaw%3D23.500635%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656)). 

Indeed there is a clear footway part, but a road with a sidewalk also has a clear footway part. There you'd also use surface for the 'car part' and sidewalk:*:surface for the footway part.

StreetComplete seems to be based on the German approach. This is however not how we tag in the Netherlands, so this tagging scheme shouldn't be imposed. I think it's clear to see it in the usage of surface vs cycleway:surface on highway=cycleway. 

The surface of sidewalks is generally not mapped, because it isn't rendered and it's predominantly the same (paving stones) in the Netherlands. I think that explains the low numbers. But sidewalk:*:surface is the documented value, while footway:surface seems to be invented.

I've raised the issue on the [Dutch forum](https://forum.openstreetmap.org/viewtopic.php?id=72165). It wasn't really discussed before, because it wasn't an issue. This usage of cycleway:surface wasn't applied before StreetComplete started adding those.

**Comment by matkoniecz** [comment]
> (example)

Interesting, basically the same feature in Poland would be described as "footway and cycleway along road", maybe even "sidewalk with cycleway", not as "cycleway along road with sidewalk"

**Comment by smootheFiets** [comment]
I'm happy this issue was raised.  As an active cycleway mapper in NL, `cycleway:surface` on `highway=cycleway` strikes me as wrong for the reasons given above.  SC should never use this on cycleways, certainly not in the NL (probably nowhere, but I can't speak for everywhere).  I am happy for SC to help surface tagging on Dutch cycleways, but please use `surface` instead of `cycleway:surface`.
As A67-A67 points out, most sidewalks in this country are paving_stones.  I rarely bother tagging that, myself.  When I do, I'm not sure whether I use `sidewalk:*:surface` or `footway=surface`.  I don't have strong feelings about that part, but A67-A67's reasoning to prefer `sidewalk:*:surface` makes sense to me.

PS, somewhat off-topic: the reason why combined foot-bicycle paths are tagged as cycleways in the NL is probably because they're typically signposted as such. `traffic_sign=NL:G11` does _not_ exclude pedestrians.  The similar-looking DE:237 does, that's why there are signs like DE:240 and DE:241 (which don't exist in NL, but I seem to remember seeing similar signs in PL).

**Comment by westnordost** [comment]
> These sidewalks even look the same and can be continuous where a road changes into a cycleway (example).

Man, this looks really nice. There is even a curb between the sidewalk and cycleway.

Anyway, the `cycleway:surface` and `footway:surface` is only asked for cycleways with `segregated = yes`. I believe, a cycleway with a sidewalk should be tagged like for example this
```
highway=cycleway
sidewalk=right
```
, so without `segregated = yes` because for a normal road 
```
highway=residential
sidewalk=right
segregated=yes  // <- what's segregated?? the existence of a sidewalk is already a segregation per se!
```
would be wrong/superfluous too.

**Comment by westnordost** [comment]
> JOSM validator complains if foot=yes (which it frequently is, although it's not necessary in NL) and segregated is missing. 

Well, that makes sense. `foot=yes` on an element tagged with `sidewalk=yes/both/left/right` is equally superfluous as `segregated=yes`.

**Comment by westnordost** [comment]
Basically, any `highway=footway/cycleway/path` with `foot=yes` is understood by data consumers as (also) a footway.

**Comment by A67-A67** [comment]
The tag `segregated=yes` is also added by StreetComplete users in a sequence of additions that ends with the surface tags we're talking about:
1) Is this cycleway accessible for pedestrians? --> `foot=yes` is added
2) Is this combined foot-cycleway segregated? --> `segregated=yes` is added
3) What is the surface of this combined foot-cycleway? --> `cycleway:surface` and `footway:surface` are added

**Comment by matkoniecz** [comment]
> Is this cycleway accessible for pedestrians?

As far as I know StreetComplete has no such quest. There is "Are pedestrians forbidden to walk on this road here?", not asked for cycleways.

But if `foot=yes highway=cycleway` is tagged two next steps will happen in current SC version.

**Comment by westnordost** [comment]
So, what to do here now?

Maybe don't ask for segregation and dont ask for segregated-surface if a sidewalk is tagged, i.e. `sidewalk ~ both|yes|left|right`?

**Comment by matkoniecz** [comment]
That makes sense. I also thought about disabling cycleway surface quest in NL.
