### ISSUE TITLE
Confusion about "Saltbox" roofing

### ISSUE THREAD

**Issue by michaelblyons** [streetcomplete/StreetComplete#2648]
The wiki guidance on `roof:shape=saltbox` is very different than the images shown in SC. I imagine SC got the images and their names from a previous version of the wiki table, but now I'm not sure what to do.

FWIW, I am kind of annoyed that the wiki changed. I didn't know that shapes of roof even *had names* until I started editing OSM.

**Comment by westnordost** [comment]
And from roof:shape wiki page:

![image](https://user-images.githubusercontent.com/4661658/110536967-5c291700-8122-11eb-96ac-2c71a0c95972.png)

So basically, StreetComplete is using double_saltbox for roofs with that big inclination on both sides and flat/almost flat in the middle and saltbox for big inclination on one side and slight inclination on the other.

**Comment by matkoniecz** [comment]
Resolving that would be great idea, but sadly tagging scheme needs to be fixed here - not StreetComplete.

So issue was closed not because everything is fine, but because it is not fixable by modifying StreetComplete.
