### ISSUE TITLE
German translation: "jeder" statt "alle"

### ISSUE THREAD

**Issue by exmatrikulator** [streetcomplete/StreetComplete#2649]
https://github.com/streetcomplete/StreetComplete/blob/0f96eb1fdd028b19affc6cddf0e7d0d6d4ba7e97/app/src/main/res/values-de/strings.xml#L1017

"Jetzt wählen alle in eurer Gruppe eine eigene Farbe aus:" müsste es nicht "Jetzt wählt jeder in eurer Gruppe eine eigene Farbe aus:" heißen?

**Comment by matkoniecz** [comment]
Note that in general anyone may improve translation, see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by FloEdelmann** [comment]
It was actually me who changed the translation from "jeder" to "alle", because I wanted to avoid the word "jeder" and discussions about it needing to be gendered ("jede:r" / "jede\*r"). I thought that the words "alle" and "jeder" can be used interchangeably in this context, but it seems there is a tiny difference in meaning: https://german.stackexchange.com/a/15120

I'd say the difference is minor enough so we can keep "alle", but I'm open for discussion (here or in [POEditor](https://poeditor.com/projects/po_edit?id_language=55&id=97843#showComments290389069)).

**Comment by westnordost** [comment]
In general, un"gendered" language is used in StreetComplete, "jeder" would be fine. But to avoid the issue alltogether by using different words might even be preferrable, I see myself doing this often too. In this case, I'd also say that "alle" would be acceptable.

Maybe "Jetzt wählen alle in eurer Gruppe **jeweils** eine eigene Farbe aus:" makes it clearer? (I honestly don't know)

**Comment by westnordost** [comment]
Übrigens fehlt in der deutschen Übersetzung ein bischen dass jeder halt eine andere Farbe als jeder andere auswählen soll. Im englischen "unique". Eventuell wird das etwas klarer wenn man schreibt "Jetzt wählen alle in eurer Gruppe jeweils eine Farbe:"?

**Comment by exmatrikulator** [comment]
Sorry, falls das hier der falsche Ort sein sollte.

OK, ich versteh das Problem mit "jeder".
Das angesprochene Problem mit "unique" von @westnordost hatte ich nämlich auch.

Wie wäre es einfach mit "Wähle deine Farbe" oder "Wähle deine Farbe in der Gruppe" (wie bei Mensch ärgere dich nicht)

**Comment by westnordost** [comment]
"Jetzt wähle deine Farbe" hört sich gut an. 

The question is, if the source string should also be changed to "Now, choose your color:" or if that should only be changed in the German translation.

**Comment by matkoniecz** [comment]
> The question is, if the source string should also be changed to "Choose your color:" or if that should only be changed in the German translation.

"Choose your color:" + more explicit info that everyone should do it on their phone seems like a good idea, but current version is also OK.

**Comment by FloEdelmann** [comment]
For reference, my original English version was "Everybody in the group has to choose a unique color (on their own phone) now.": [`f79f783` (#2557)](https://github.com/streetcomplete/StreetComplete/pull/2557/commits/f79f783ab63f9b0e218a5b7599ac3fddf3bf75f9#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R833)

**Comment by westnordost** [comment]
> Oder ganz anders: „Wählt jetzt alle eine jeweils eigene Farbe:“?

Well, in the absence of a super-good suggestion, I went with this for now. It's better then the current German translation.
