### ISSUE TITLE
The small circles that replace pins when zoomed out are positioned too high

### ISSUE THREAD

**Issue by JohnVeness** [streetcomplete/StreetComplete#2650]
**How to Reproduce**
When you can see quest pins that appear with the very tip of their point on a road, say, then zoom out, the small circle that replaces them will appear too high up on the screen. That is, it will be above/alongside the road (looking like the quest is for a building instead), not on the road.

I think the centre of the small circle should align with the tip of the pin.

Hopefully these two videos will make this clear - look at the four quests along a road in the middle of the screen. Also see how they seem to move from one side of the road to the other when the map is rotated.

https://user-images.githubusercontent.com/2512915/110649903-f71d0200-81b1-11eb-8a62-c53b1349a64c.mp4

https://user-images.githubusercontent.com/2512915/110655287-d30fef80-81b6-11eb-9137-ccb1ea0f7160.mp4

**Versions affected**

Android 9, StreetComplete 31

**Comment by westnordost** [comment]
Okay, this is deliberate because the dots should not be visible while the the pin is. The dot does not vanish when the pin becomes visible but instead is simply obscured by it. It is not possible to make it vanish when the pin is displayed.

**Comment by westnordost** [comment]
Initially it was one (in internal tests). I didn't really like it, because the pin conveyed the impression that one could tap on it, which you can't

**Comment by smichel17** [comment]
> It is not possible to make it vanish when the pin is displayed.

Tangram hides POIs that overlap, right? I wonder if we could work around this by making either the pin or the dot have slightly larger dimensions, so for the purposes of Tangram it has a larger collision radius, but the actual image would have transparency so you can still see the map below? So it would still look the same, but for collision purposes it would be more like this:

![image](https://user-images.githubusercontent.com/6563664/110688147-2b57e900-81d9-11eb-8925-694765f6b8af.png)

**Comment by westnordost** [comment]
> Tangram hides POIs that overlap, right?

Only if one tells it to. On that zoom, it is deliberate that the overlapping dots are not hidden.

**Comment by Atrate** [comment]
>> Tangram hides POIs that overlap, right?

> Only if one tells it to.

@westnordost Where in the code can the quest pins themselves be made to overlap without hiding? I'd like to try it in my fork to see how it feels

**Comment by westnordost** [comment]
It is in the style yaml file, not in the code

**Comment by Atrate** [comment]
> It is in the style yaml file, not in the code

Which property would that be? Seems setting `collide: true` for `streetcomplete_pins` or `streetcomplete_selected_pins` does nothing.

**Comment by matkoniecz** [comment]
Have you modified https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/assets/map_theme/jawg/streetcomplete.yaml#L75 and build app with the modified map style?
