### ISSUE TITLE
Make it easier to reach top items in "Select" windows (e.g. cycleway quest)

### ISSUE THREAD

**Issue by JohnVeness** [streetcomplete/StreetComplete#2651]
**Use case**
Certain quest types use a "Select" window. Items at the top of this window are hard to reach when using a phone one-handed, on large-screen phones.

I notice this problem particularly in the cycleway quest, where (at least round my way) the usual answer is that there is no cycleway (top-left of the screen), which has to be set for both sides of the street. Moving the thumb repeatedly from the bottom to the top and back again is irritating!

See video:

https://user-images.githubusercontent.com/2512915/110660581-9a264980-81bb-11eb-9622-72df9e652dc7.mp4

**Proposed Solution**
It would be nice instead if the Select windows could be made to work more like the windows that appear when setting a surface type (asphalt etc.), which appear at the bottom of the screen, with the most recently-used entries first, and where the user can scroll up to see other entries.

See video:

https://user-images.githubusercontent.com/2512915/110660844-e1143f00-81bb-11eb-92a4-b66ffbdfe01a.mp4

**Comment by TurnrDev** [comment]
Maybe locking the "No bike path available" option behind an acknowledgement screen that we've reviewed all the options could be the solution.

Or perhaps I'd becomes usable after you've answered _x_ amount of bike lane quests? 

![Screenshot_20210310-191811.jpg](https://user-images.githubusercontent.com/11667059/110685547-4e34ce00-81d6-11eb-97fc-f77eacc24133.jpg)

I've answered loads and the majority is None-None, that's a lot of presses and a lot of time loss. I only have little legs and even I have to slow down to answer everything so anything to prevent time loss would be great.

**Comment by JohnVeness** [comment]
Although I appreciate the talk about the special case of "No bike path available"/None-None, I wonder if that could be spun off into its own bug?

For the particular problem I was really trying to highlight in this bug, it's not just the None option, but also the single cycle-lane option that is hard to reach on the top row. Or whatever happens to be in the top row in any other Select windows.

Rather than trying to find special-case solutions, I think a general solution of changing the behaviour/appearance of the Select windows, as mentioned in the original post, would be preferable.

**Comment by westnordost** [comment]
I acknowledge the problem, but displaying the selection dialog "in" that bottom sheet below would be inconsistent with the rest of the UI, in my opinion. Nowhere else there is a UI the exchanges the content of that bottom sheet (for a selection to be made).

**Comment by westnordost** [comment]
So, I'll close this as will not fix
