### ISSUE TITLE
Cycleway selections upside-down in countries driving on the left

### ISSUE THREAD

**Issue by JohnVeness** [streetcomplete/StreetComplete#2652]
I'm not sure if this is a bug or a feature request, but is there a reason that the cycleways appear seemingly upside-down, at least here in the UK (where we drive on the left).

See screenshot:

![Screenshot_20210310-164512](https://user-images.githubusercontent.com/2512915/110665591-6e599280-81c0-11eb-87a8-bdf809a7b896.png)

It would seem more natural to me to see instead something like:

![Screenshot_20210310-164512](https://user-images.githubusercontent.com/2512915/110666640-6a7a4000-81c1-11eb-8eea-9e190108148f.png)

**Comment by TurnrDev** [comment]
I was wondering this too

**Comment by westnordost** [comment]
Yeah, the dialog shows the graphic for the right side of the road. For the UK, India etc, it means it is upside down.

There is actually no graphic for the left side of the road, it is rotated by 180° in the UI component for that. Not sure right now how difficult it would be to instead show the left side of the road in that dialog for countries in which the people drive on the wrong side of the road. ;-)

Anyone who is interested in this is welcome to give it a try. The code is in 
https://github.com/streetcomplete/StreetComplete/blob/25790b3ec805268377f1029dc60ade0c50e208a9/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCyclewayForm.kt#L209

**Comment by JohnVeness** [comment]
Thanks. I'm not sure I understand though - if you mean we should currently be shown different things depending on whether we click on the ????? on one side of the road or the other, I don't at the moment.

**Comment by westnordost** [comment]
No, always the right side is shown as far as I remember.

**Comment by JohnVeness** [comment]
So, would a fix be to just rotate the graphics in "/res/graphics/cycleway graphics/*_l.svg" by 180 degrees? I'm not clear why there needs to be a change in the code.

**Comment by westnordost** [comment]
Maybe. Try it out

**Comment by westnordost** [comment]
But probably not, I think in the street-preview, there'd then be the cycleways in the center of the street and the "road" each on the outer side.

**Comment by riQQ** [comment]
Isn't the solution to mirror the graphics on the vertical axis?

**Comment by matkoniecz** [comment]
> Isn't the solution to mirror the graphics on the vertical axis?

Maybe it is viable, but someone would need to implement and test it.

**Comment by Helium314** [comment]
Simply mirroring the "bus lane" graphics is probably not a good idea

**Comment by RubenKelevra** [comment]
> Simply mirroring the "bus lane" graphics is probably not a good idea

I mean the "BUS" part could just be excluded from this rule :)

**Comment by peternewman** [comment]
> There is actually no graphic for the left side of the road, it is rotated by 180° in the UI component for that. Not sure right now how difficult it would be to instead show the left side of the road in that dialog for countries in which the people drive on the wrong side of the road. ;-)

> Thanks. I'm not sure I understand though - if you mean we should currently be shown different things depending on whether we click on the ????? on one side of the road or the other, I don't at the moment.

> No, always the right side is shown as far as I remember.

Surely ideally in countries that drive on the right, when you click the left hand side of the road it should show the current images, but rotated 180 degrees (as it does when you've chosen them)? Then in the UK and other left hand side countries it should swap which image is rotated.

This seems to be what does the rotate:
https://github.com/streetcomplete/StreetComplete/blob/3fc8c086a09b6ae6bbc2552271003d43ee5e0027/app/src/main/java/de/westnordost/streetcomplete/view/StreetSideSelectPuzzle.kt#L204

Although it looks correct to me when they are selected in the rotatable mirror of the road, so I think it's just the choice screen needs fixing IMHO.

**Comment by Helium314** [comment]
What about changing
https://github.com/streetcomplete/StreetComplete/blob/25790b3ec805268377f1029dc60ade0c50e208a9/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCyclewayForm.kt#L211
to
`val items = getCyclewayItems(isRight).map { it.asItem(false) }`? (always use `false` instead of `isLeftHandTraffic`)

Then the cycleway type picker is always showing images for right hand traffic, but in the cycleway view the correct image is used.

**Comment by westnordost** [comment]
As said, everyone is welcome to try it out. I can't answer any questions because I would need to look at the code and probably try around myself. If I did that, then I could just do it myself.

**Comment by Helium314** [comment]
I tried it and it looks as I described.
Could this change cause any further problems? As far as I understand not, but I have the impression I understand only a fraction of the cycleway form...

**Comment by peternewman** [comment]
> Then the cycleway type picker is always showing images for right hand traffic, but in the cycleway view the correct image is used.

> I tried it and it looks as I described.
> Could this change cause any further problems? As far as I understand not, but I have the impression I understand only a fraction of the cycleway form...

Can you share some before and after pictures @Helium314 for say the UK and a RHD country? Currently I consistently get a dialog allowing me to select image based on the right hand side of the road in that country (e.g. the arrows and bus signs look as they would on the right hand side of each road in that country).

It sounds and looks to me like your change would result in me always getting a RHD right hand side of the road, which would be even more confusing.

If this form is going to be changed, wouldn't it be even clearer if it showed you them in the correct orientation for the side of the road you're picking, rather than always being pinned to a specific side of the road?

This could possibly be done for the pavement quest too, although may be more complicated there as I'm guessing the tick and cross are embedded in the image? Can Android have an overlay over the top?

**Comment by Helium314** [comment]
> Can you share some before and after pictures @Helium314 for say the UK and a RHD country?

As I wrote, you will always get images for right hand traffic in the cycleway type selection dialog (this is new), and the correct images in the cycleway (left|right) selection (unchanged).

> It sounds and looks to me like your change would result in me always getting a RHD right hand side of the road, which would be even more confusing.

Ok, then better forget my idea.

**Comment by peternewman** [comment]
> As I wrote, you will always get images for right hand traffic in the cycleway type selection dialog (this is new), and the correct images in the cycleway (left|right) selection (unchanged).

What do you mean by "right hand traffic"? The right hand side of the road, or a right hand drive view of a country, or both?

**Comment by Helium314** [comment]
> What do you mean by "right hand traffic"? The right hand side of the road, or a right hand drive view of a country, or both?

however you want to call it if `isLeftHandTraffic` is set to false

**Comment by peternewman** [comment]
> however you want to call it if `isLeftHandTraffic` is set to false

I'd call that a right hand drive country.

But in this case it's also a don't rotate the image (which shows the default, which happens to be the right hand side of the road in a right hand drive country). So it would fix @JohnVeness initial request, but IMHO if we're going to change it, making the dialogue so it shows the relevant selection for the side of the road you've picked would seem like the obvious change to me.

**Comment by westnordost** [comment]
Did you test this? This does not solve the issue. Now, the icons in the select dialog are all shown as if it was right hand traffic. Previously it was just an inconvenience, not it will be a source of confusion.

I reverted the commit because I don't know when you will have the time to solve this issue properly. Hint: Rotate the graphics by 180° for display in the dialog for left-hand traffic .

**Comment by matkoniecz** [comment]
Yes, I realized it after committing.

> Hint: Rotate the graphics by 180° for display in the dialog for left-hand traffic. See [RotateDrawable](https://developer.android.com/reference/android/graphics/drawable/RotateDrawable)

That was my initial attempt.

But AStreetSideSelectFragment expects drawable id, not drawable and it would require deeper changes to allow this. So I ended with some extra drawable flipped manually.

**Comment by westnordost** [comment]
You got something wrong here
1. The cycleway form does not inherit from AStreetSideSelectFragment
2. I think the class you mean is ImageListPickerDialog, but that dialog accepts `DisplayItem`, look at what classes implement that interface

**Comment by westnordost** [comment]
@matkoniecz I suggest to replace the mock shadow for these selections with a white outline instead (similar to the pin icons), this way you don't need to flounder with edge cases where that mock shadow is supposed to be.

**Comment by westnordost** [comment]
So don't worry about the shadows, I will adapt the graphics after you create the PR. (Also, you should use [RotateDrawable](https://developer.android.com/reference/android/graphics/drawable/RotateDrawable) unless there is a good reason not to)

**Comment by peternewman** [comment]
As I mentioned, once the ability to rotate sides exists:
> If this form is going to be changed, wouldn't it be even clearer if it showed you them in the correct orientation for the side of the road you're picking, rather than always being pinned to a specific side of the road?

I think it's just a case of XORing whether the country is left hand drive and whether we're picking the left hand side of the road (or vice versa).
