### ISSUE TITLE
Follow Compass seems to use magnetic north, not true north

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#2653]
When following the compass in tilted-map mode, the orientation of the map is off by a few degrees. As far as I can tell, this deviation is close to the magnetic declination for my location (about -7°). So when I'm walking down a straight sidewalk, the map is always turned to point my dot slightly to the right. It also makes it a little more difficult to tell what I'm facing.

I know some apps can compensate for this. [This link](https://developer.android.com/reference/android/hardware/GeomagneticField) looks promising, but I would have no idea how to implement it.

If I'm wrong and that's already taken into account, then disregard, and I would blame the phone, but I have some other apps that seem to work as expected (e.g. GPS Status).

**How to Reproduce**

Tap location button to center your dot. Tap the north arrow. Point your phone down a straight line, see what the map shows.

**Versions affected**

I'm using Android 9, SC 30.1 at the moment. I got back into SC more heavily with a new phone, but I think the issue has been present for awhile. This obviously affects some locations more than others.

**Comment by westnordost** [comment]
The declination is taken into account, see

https://github.com/streetcomplete/StreetComplete/blob/5df2040f07db3feb23eee4c2bb78ed40885f4255/app/src/main/java/de/westnordost/streetcomplete/map/Compass.kt#L151

Maybe it's applied the wrong way around, i.e. it should be +, not - here?:
https://github.com/streetcomplete/StreetComplete/blob/5df2040f07db3feb23eee4c2bb78ed40885f4255/app/src/main/java/de/westnordost/streetcomplete/map/Compass.kt#L108

I don't live that far up north to ascertain that by testing. Though, looking at the [documentation ](https://developer.android.com/reference/android/hardware/GeomagneticField#getDeclination()), ...

> positive [degrees] means the magnetic field is rotated east that much from true north

I'd say, the compass angle **minus** the declination is the true north angle.

For the true north correction to be applied, you need to turn on your GPS in the app, it is not enough to simply scroll to your location.

**Comment by westnordost** [comment]
Maybe you would like to look into that yourself. I linked the relevant sections in the code, you could (download Android studio and) set a breakpoint there, to see what are the actual values.

**Comment by pkoby** [comment]
I might give this a try when I have time. This does sound likely as the cause, because if I'm honest, it looked more like 15° instead of 7° off, which could be fixed by switching the sign.

**Comment by HolgerJeromin** [comment]
@westnordost could try that with the next beta. No other user will complain :-)

**Comment by westnordost** [comment]
Rather not, because I am pretty sure the current implementation is correct. Wouldn't you say that too, when comparing the implementation with the documentation?

**Comment by pkoby** [comment]
Alright, I found the time to work this out. After struggling with the learning curve that is Android Studio and nearly killing my computer at 95% RAM, I built the APK with that one sign change (- to +).

I tested it outdoors unobstructed by buildings, and it seems to perform as I hoped it would: looking straight down a sidewalk, the line on the map is perfectly vertical.

I took pictures of my phone screen and the surroundings, but it's night now and they didn't turn out great. I'll take some in daylight tomorrow and see what you think.

**Comment by westnordost** [comment]
Where are you located? Maybe I can replicate this setup with a mock location to confirm

**Comment by pkoby** [comment]
I'm in Huntington, West Virginia, USA. But looking at this map https://www.ngdc.noaa.gov/geomag/WMM/data/WMM2020/WMM2020_D_BoZ_MILL.pdf, there might be some places where the issue would be more pronounced (e.g. Maine, USA is more like -16° compared to my -7°).

**Comment by westnordost** [comment]
And could you explain shortly how you notice / reproduce this issue? I.e. how did you determine in the app, that the compass must be pointing in the wrong direction?

**Comment by pkoby** [comment]
If I'm facing straight down a line in real life (like a sidewalk), phone aligned with that line, and the app is centered on location in angled follow-compass mode (so tap location button, tap north arrow), the sidewalk on the map is not straight from the top to the bottom of the screen, but angled slightly, as if my blue dot is facing slight to the right.

Example: if I were to face due north on a sidewalk, the line on the map would be angled slightly to the west (left at the top of the screen).

**Comment by westnordost** [comment]
I tried to no avail to reproduce this at my location (+3° declination), but it turned out that the precision difference between the compasses I have are much greater than the declination, the compasses were each more that 20° off.
Also, depending on how I tilted the phone (f.e. lay flat on table vs hold in front), the calculated North was also very different.

In the lack of being being able to confirm if that change is correct, I looked at OsmAnd source code. They do indeed seem to add the declination, not subtract it: 

https://github.com/osmandapp/OsmAnd/blob/fdb6570ebe6f7973032a61323591ecb4c3f94799/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L537

**Comment by smichel17** [comment]
@zyphlar said in https://github.com/streetcomplete/StreetComplete/issues/1040#issuecomment-782547850,

> Galaxy S8 is nearly always off by at least 30-120 degrees and jittery as heck despite doing every calibration available

FYI, depending on your location, it's possible at least some of the "always off" was a result of this issue.

**Comment by zyphlar** [comment]
I agree with westnordost's comment, my issue is more consistent with an inaccurate and inconsistent sensor reading, than a magnetic declination issue. My top three theories are: phone case interference, vehicle (especially EV) interference, and just crappy sensors
