### ISSUE TITLE
Where roof shape quest should be asked?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2655]
Currently roof shape quest will be asked for

`demolished:building=yes` + `building:levels=1` what is undesirable 

(and will be probably asked also for `proposed:building=yes` + `building:levels=1` etc)

Changing it is simple - but should it be limited to solely `building=* building!=no`  with `building:levels` or is it also desirable to ask on `building:part=*` geometries?

**Comment by matkoniecz** [comment]
Question is asking about "buildings" what is highly confusing for building parts, so I plan to make commit that will limit it to solely `building=*` objects.

Let me know if that is a bad idea.

**Comment by matkoniecz** [comment]
I asked a bit in https://github.com/streetcomplete/StreetComplete/commit/6ce6b64b329f12bee1646829946e6a22446d6f42#diff-352a2785558ff4730bd2eef1204824388e860e175ecc8ce767e4261469da4843 where this behavior was previously changed.

**Comment by westnordost** [comment]
Yeah, it should not be asked for building parts or demolished buildings. To have at least `building and building!=no` in the filter makes sense.

**Comment by andrewharvey** [comment]
> Yeah, it should not be asked for building parts 

Many building parts will have a valid roof tag, but I guess you don't want to ask since sometimes it's not a roof?

**Comment by matkoniecz** [comment]
Right now main problem is that question in SC asks about "building" what is highly confusing when you got tiny sliver of building.

Also, for some more complicated buildings `building:part` may have `building:levels` but not have roof at all (covered by other building part).

I have not attempted to fix first problem as I see no way to solve second.

**Comment by andrewharvey** [comment]
Sure there are cases where it won't have a valid roof tag, but there will be many cases where it will. So I guess this change makes it more conservative and tries to reduce the instances of an "unable to map" answer.

**Comment by matkoniecz** [comment]
Yes. In general I think that avoiding false positives is far more important than avoiding false negatives.

Especially as false negatives will affect anyone mapping in a given area (and return with phone/app change/reset).

And in general there is usually enough tasks generated to keep nearly everyone busy (I am quite active mapper and still have flood of tasks in range of morning walk with my father!). Though I guess that in poorly mapped areas (for example missing buildings) or in more rural areas it is possible to actually solve all tasks.

**Comment by DerDings** [comment]
> historic
> 
> Right now main problem is that question in SC asks about "building" what is highly confusing when you got tiny sliver of building.

This would be solvable by using a different question string in this case.
> 
> Also, for some more complicated buildings `building:part` may have `building:levels` but not have roof at all (covered by other building part).

would be possible with this filter (Do I do the indentations right?)
```
ways, relations with (
                     roof:levels
                     or (
                        building:levels and (building and building!=no)
                     )
)
          and !roof:shape and !3dr:type and !3dr:roof
```
I think it's safe to assume that anything with explicitly tagged roof levels also has a roof. Even if it is a building part, a building under constuction where only windows are missing yet, or a `historic=monument` without `building=monument`.




However, I know the first point needs some more work to be implemented. Are building parts with separate roof shapes common enough to justify this?

**Comment by matkoniecz** [comment]
> Are building parts with separate roof shapes common enough to justify this?

No idea at all, is it common then creating a new issue would be the best.

> I think it's safe to assume that anything with explicitly tagged roof levels also has a roof. 

That would be a viable solution
