### ISSUE TITLE
Building type for buildings under construction

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#2656]
Often when I'm surveying a building under construction, I'm in doubt whether to first tag it as "under construction" or to first add its building type. Here, construction sites should have an information sign that tells exactly what kind of building is under construction, which gives an excellent opportunity to unambiguously determine its building type, which is lost when the building is completed and the sign is removed. I think SC should stimulate to use this opportunity and enable tagging a building both as "under construction" and with its building type at any moment in the work flow, by:
- asking building type of buildings that have earlier been tagged as under construction,
- offer "building is under construction" as an answer option for the house number quest, for buildings that have earlier been tagged with a building type tag.

**Comment by matkoniecz** [comment]
Tagging exact building type immediately is 100% fine.

Constructions sites can be mapped as area (`landuse=construction`).

Advantage of `building=construction construction=apartments` in `landuse=construction` area over `building=apartments` in `landuse=construction` area seems tiny, I would not consider it as a good reason to implement this extra interface.

**Comment by rhhsm** [comment]
Most buildings under construction that I see are not in a landuse=construction area. I guess the enhancements I propose are easy to implement.
Does a building, not tagged as under construction but inside a landuse=construction area, trigger the "Is this building completed?" quest?

**Comment by matkoniecz** [comment]
> Does a building, not tagged as under construction but inside a landuse=construction area, trigger the "Is this building completed?" quest?

No, as retagging/remapping `landuse=construction` is not feasible in StreetComplete (for start, geometry often needs to be adjusted)

**Comment by westnordost** [comment]
So I'll close this as will not fix. It's your choice whether to immediately tag it as the building it is going to be, or as a building-in-construction first.

**Comment by rhhsm** [comment]
Disappointed, as choosing one is excluding the other now, and adding the 2 options I proposed seems very little effort.

**Comment by matkoniecz** [comment]
> adding the 2 options I proposed seems very little effort.

Are you interested in submitting a pull request? (in such case maybe @westnordost would accept it, though asking before starting coding would be a good idea).

As new interface and special handling is needed here, coding and testing time would be measured in hours - not minutes.

**Comment by rhhsm** [comment]
I'm sorry, but I haven't coded since I passed my Pascal course in university :) I though it would be a matter of adding a category to the building type quest (ask for building=construction in addition to building=yes) and to copy-paste an answer option from the building type quest to the house number quest, but if it's more complicated, I understand that it won't be fixed.
