### ISSUE TITLE
convert ambigous power=station to one of the 3 (or 4) tag that replaces it

### ISSUE THREAD

**Issue by Marc-marc-marc** [streetcomplete/StreetComplete#2657]
### General
Affected tag(s) to be modified/added: power=station
Question asked: **what is it ?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
Most of those objects have been "armchair fixed" when the information allowed it. it remains therefore many object for which a survey is necessary (object too small to be visible on satellite imagery in the case of power=substation, aerial imagery of poor quality to other, ...)
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
**Element selection:** power=station :-)

**Proposed GUI:**
1.  answer : an electricity substation
description : A facility which controls the flow of electricity in a power network with transformers, switchgear or compensators.
Fix : change power=station into power=substation. 
2. answer : a power plant
description : An industrial facility where power (electricity, useful heat, biogas) is produced.
Fix : change power=station into power=plant
3. answer : a generator
description : A device which converts one form of energy to another, for example, an electrical generator
Fix : change power=station into power=generator
4. answer : a pipeline substation
description : Facilities required for pipeline operation
Fix : change power=station info pipeline=substation
answer number 4 is less common, but would decrease the need to make a note
5. gone -> fix change power=sub_station into was:power=sub_station
6. other -> note+photo

answer 4 is much less frequent. anser 6 has never happened to me yet. if the number of answer needs to be reduced, answer 4 and/or 5 can be removed

**Comment by westnordost** [comment]
This is probably not eligible because the average user might not be able to distinguish these from one another. It is not as if one can expect a big sign in front of the facility. Average users will see a fenced off area with "danger high voltage" signs and "electricity things" (transformers, tesla coils 😉, electricity pylons), if they are lucky, and that's it. How should they decide whether it is 1, 2, or 3, or 4?

**Comment by Marc-marc-marc** [comment]
it seemed to me that the pictures in the wiki about these 4 elements are quite representative.
if the user is unable to answer, a photo of the item and/or the information sign is very usefull, one user should have only a very few number of objets during one survey, so it's not boring

**Comment by rhhsm** [comment]
Seems like a relatively large effort to create for a very small (compared to other POIs) number of quests. However, I would like to have a way to tag building=service as (minor) substation through SC (most service buildings I see during a survey in populated areas are minor substations).

**Comment by matkoniecz** [comment]
>  clock4 Applies to a reasonable number of elements (Worth the effort)

Not entirely sure, just 1884 worldwide - https://taginfo.openstreetmap.org/tags/power=station#overview

**Comment by westnordost** [comment]
Ok then, I'll close this as will not fix.

**Comment by Marc-marc-marc** [comment]
What order of magnitude is considered large enough?

**Comment by westnordost** [comment]
How should I answer this? I decide this on a case-by-case basis: Time and effort to implement it, to translate it vs number of quests generated and value added in general. Using this formula: π ×👍.
So, if time vs effort was the only problem, I'd say that you or anyone else interested in this is welcome to create a PR for that, but alas it is not the only problem, see my first comment. It might be better to create notes for these places, asking in prose (or marking with "#surveyme" in the note) for locals to supply this information (with photos).

**Comment by Marc-marc-marc** [comment]
I have noted your opinion on the supposed difficulty of the question for the average contributor.
If I ask the question about the number of items, it is no longer for this quest but in general.
For example power=power=sub_station has the same problem and has ~9000 items.
I understand the "on a case-by-case basis"
But I thought you could have told me an order of magnitude (10k ? 100k ? 1M ? 10M ? ), for example based on the quest having been accepted with the least number of items, so that I avoid proposing other ideas if they are too "small" in your eyes.
As for creating 10k notes to say "here is an ambiguous deprecated tag", it's a bit of a deluge. especially when there are several tags like that.

**Comment by matkoniecz** [comment]
in my opinion:

100k or 1M usage is definitely passing "Applies to a reasonable number of elements (Worth the effort)"

10k would depend on difficulty in implementing it.

Note that there is difference between "currently Xk quests, new will appear in future as people map new things" and "currently Xk quest, new ones are not appearing and once gone it will not appear again" roughly applying to deprecation-related ones.

**Comment by Marc-marc-marc** [comment]
thank, this gives me an order of magnitude and the difference between the depreciated tags and the others is quite relevant

**Comment by smichel17** [comment]
This was already implied with the "time and effort to implement it" piece, but I'll just point it out: if someone is willing to send a PR implementing the quest, then this lowers the time & effort to implement quite a bit (only reviewing is needed). I think https://github.com/streetcomplete/StreetComplete/pull/1743 is a good example of this, where it would be low priority to implement, since it is limited to one country, but because someone came with a PR, it was accepted. (It is *also* an example of "more quests will appear in the future".)

**Comment by matkoniecz** [comment]
> then this lowers the time & effort to implement quite a bit (only reviewing is needed).

Note that maintenance is also needed, in some cases it may be noticeable.
