### ISSUE TITLE
building levels asked on building=roof

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2658]
The building levels quest shouldn't be asked for building=roof. Unless there is > 1 levels inside the roof usually it doesn't make sense to say there is 1 level if it's just a roof.

**Comment by matkoniecz** [comment]
Can you link the object where this question was asked? Maybe it was roof, but it was mistagged? Maybe it was asking a bout roof shape?

NOte where https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.kt#L33 SC defines which `building` values will trigger question.

**Comment by andrewharvey** [comment]
Oh sorry my mistake, I mixed up two buildings right next to each other.
