### ISSUE TITLE
Add clarification for building level quest

### ISSUE THREAD

**Issue by erus** [streetcomplete/StreetComplete#2661]
I've completed two of these quests today and fixed them later when I realized that I had set the wrong number of levels. 

Some countries start counting levels from 0 (ground floor, 1, 2, 3, etc...) but OSM starts at 1 : the picture could have the levels numbered inside it to help ? 

Thanks !

**Comment by Helium314** [comment]
Why would it be helpful to have numbered levels? A building that only has level 0 still has one level, same as a building that only has level 1.
A building that has levels HP, M, 1, 2, 3 has five levels (assuming none are underground)

**Comment by HolgerJeromin** [comment]
If one user is confused (to even find this repo) others have probably the same issue.
Perhaps we could add a "3" somewhere beside the building and a "2" beside the roof

**Comment by erus** [comment]
Sorry if I was not clear. 
When asked about the number of level, I suggested that the picture on the quest show how OSM counts levels for a building. 
The question is worded in such a way that I first answered with the number of "floors" for the building.

**Comment by HolgerJeromin** [comment]
@erus your phone is set to English?

**Comment by erus** [comment]
@HolgerJeromin no, French...

**Comment by erus** [comment]
![building_levels_illustration](https://user-images.githubusercontent.com/317840/111339335-f8e63a00-8677-11eb-9b7e-0dfc67497909.png)
Here's a quick sketch of what I had in mind.

**Comment by westnordost** [comment]
I'd rather keep the UI as tidy as possible, so, not have those small numbers float around in the illustration since there are already two (long) labels and two edit inputs there (plus the usual UI elements).

**Comment by andrewharvey** [comment]
> The question is worded in such a way that I first answered with the number of "floors" for the building.

Ground Floor, 1, 2, 3 still has 4 floors. I've always answered this quest externally by counting windows though, never by looking at the lift buttons.

**Comment by erus** [comment]
If anyone finds this bugreport in the future : the translation was reworked with https://github.com/streetcomplete/StreetComplete/commit/d09b56d8982231f5feed4cefe74488fcc79b04f2
