### ISSUE TITLE
Don't ask for roof:shape on amenity=parking, building=*

### ISSUE THREAD

**Issue by Sequynth** [streetcomplete/StreetComplete#2663]
SC asked me for the roof:shape of [this](https://www.openstreetmap.org/way/200983701) multi_storey parking, when it was (wrongly) tagged with `building=garage`. I changed it to `building=parking` but SC still asks for the roof:shape.

I suggest that SC does not ask for roof:shape of `amenity=parking, parking=multi_storey` as most of these buildings don't actually have a roof and the top floor is used for parking as well. Since 'no roof' ist not an option, this could confuse users to select `roof:shape=flat`, which actually suggests, that the top floor is covered and protected from rain/sun.
A search with taginfo also tells me, that no `parking=multi_storey` is tagged with `roof:shape=*`

**Comment by matkoniecz** [comment]
I would say that in this case building has flat roof used as a parking.

**Comment by westnordost** [comment]
See @matkoniecz . I see no reason to not ask for roof shape. There will be multilevel parkings where there is a roof on top of the top floor to protect against weather
