### ISSUE TITLE
StreetComplete doesn't get location with Google Location Accuracy disabled

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#2664]
**How to Reproduce**
Disable *Google Location Accuracy* (sometimes also called high accurarcy location) in the location settings. Open StreetComplete and walk around a bit. StreetComplete doesn't display the current location whereas other apps as OsmAnd or GPSTest pick up the location after ~ 5-10 seconds.

I'm guessing this is not intended behavior. Why does StreetComplete behave differently?

**Versions affected**
StreetComplete 31.0 on Android 10

**Comment by westnordost** [comment]
I have no idea what "Google Location Accuracy" is. Anyway, StreetComplete does not use the Google Location Services, so it is dependent on whatever the GPS sensor reports back to the app via the Android API for that.

**Comment by riQQ** [comment]
It's sometimes also called *high accurarcy location*. But something has to be different, because it works in other apps with the same settings.

**Comment by westnordost** [comment]
Ok, so that is part of the propietary Google Location services which this app does not use. The disadvantage of that is clear - the app won't get a location fast, except if it already has a location because some other app uses the google location services.

I did not change anything on that location finding code recently.

**Comment by westnordost** [comment]
Anyway, this is not a bug. When not using the location services, it can and will take longer to get a fix.

**Comment by riQQ** [comment]
It's not getting a fix at all. I was riding the bike around for 15 minutes and it didn't get a location, while the other apps mentioned in the OP got a location after some seconds.

**Comment by westnordost** [comment]
It can theoretically take an arbitrary amount of time until the GPS fix is there.

The code for receiving location is all in [FineLocationManager.kt](https://github.com/streetcomplete/StreetComplete/blob/3fc8c086a09b6ae6bbc2552271003d43ee5e0027/app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt), quite a compact class. If you would like to debug, you could start by setting breakpoints in `onLocationChanged`

**Comment by riQQ** [comment]
This might be fixed since #4139 / version 45.0.
I will report back when I have tested a bit.
