### ISSUE TITLE
Quest suggestion: is this speed bump still here?

### ISSUE THREAD

**Issue by joepie91** [streetcomplete/StreetComplete#2672]
I *think* this technically counts as a quest suggestion, even though I'm suggesting an extension of an existing quest.

### General
Affected tag(s) to be modified/added: [traffic_calming](https://wiki.openstreetmap.org/wiki/Key:traffic_calming) (+ their check date)
Question asked: **Is this speedbump still here?**

Motivation: I regularly route bicycle trips using OsmAnd, and I'm running into a *lot* of warnings for what seems like phantom speed bumps; speed bumps that once were there, but now aren't anymore, or that never existed in the first place. I suspect many of the speed bump nodes on OSM are outdated.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

Conceptually, this is not really any different from "is this bench still here?", except with speedbumps. I think it would be reasonable to just add it to that quest type, which would also eliminate the need for custom imagery.

One possible complexity is that there are different types of speed bumps - I think there does at least need to be a distinction between short speed bumps and so-called 'speed tables', as these will look aesthetically very different to the surveyor, and they may not recognize a speed table when asked for a speed bump.

I'm not sure which terminology would be best-recognized for speed tables, by an average surveyor with no road design background. In Dutch, "wegverhoging" ("raised road") would probably understood by most, but I don't know whether that works internationally.

**Element selection:** N/A

**Metadata needed:** N/A

**Proposed GUI:** Same as for other node presence checks.

**Comment by westnordost** [comment]
Not sure, I have not heard of any place where a speed bump has been **removed**. Are you sure that the speed bumps haven't been mapped erronously in the first place? What would you think would be a reasonable interval in which to ask for every single speed bump if it is still there?

**Comment by joepie91** [comment]
> Not sure, I have not heard of any place where a speed bump has been removed. Are you sure that the speed bumps haven't been mapped erronously in the first place? 

I believe it's a mix of both; in some cases I suspect they were erroneously mapped, but I've also run into a few cases where the road was recently reconstructed and (if my memory serves correctly) this involved removing speed bumps due to other layout changes making them redundant - or, in some cases, moving them so far away that they cannot really be considered to exist in the original position anymore.

> What would you think would be a reasonable interval in which to ask for every single speed bump if it is still there?

Hmm, hard to say. I feel this is more of a non-urgent long-term cleanup task, as I think erroneously reporting a speed bump does not have a significant negative impact (unlike eg. directing someone with health issues to a non-existent bench to rest). Every year or less frequently would probably be fine, and it could probably be a low-priority task.

**Comment by smichel17** [comment]
Every year is one of, if not the shortest resurvey interval :P If the alternative is not doing resurvey quests at all, I think 4-8 years is a more reasonable range.

**Comment by gojhub** [comment]
Sometimes they are removed. I know some cases in my hometown (instead they switched to "Fahrgassenversätze") and I found some (German) newspaper articles about such removings:

https://www.sueddeutsche.de/muenchen/fuerstenfeldbruck/strassenbau-schwellen-werden-eingeebnet-1.3783227

https://www.wz.de/nrw/kreis-mettmann/velbert-neviges-und-wuelfrath/wuelfrath-strassenkissen-sind-nicht-mehr-da_aid-31529617



Am 25. März 2021 16:45:14 MEZ schrieb Tobias Zwick ***@***.***>:
>Not sure, I have not heard of any place where a speed bump has been
>**removed**. Are you sure that the speed bumps haven't been mapped
>erronously in the first place? What would you think would be a
>reasonable interval in which to ask for every single speed bump if it
>is still there?

**Comment by matkoniecz** [comment]
> Not sure, I have not heard of any place where a speed bump has been removed. Are you sure that the speed bumps haven't been mapped erronously in the first place? What would you think would be a reasonable interval in which to ask for every single speed bump if it is still there?

I have seen cases where speed bump was damaged over time by traffic and reconstructed at different location (or was not reconstructed). Also some cases of intentional damage, but typically limited to removal of some sections.

https://www.google.pl/maps/@50.0793737,19.8815963,3a,75y,115.9h,59.84t/data=!3m6!1e1!3m4!1sUSDljO-QrOOnfuhVO5TiOA!2e0!7i13312!8i6656

![screen14](https://user-images.githubusercontent.com/899988/112540943-12436080-8db3-11eb-97ac-40f753d7af7f.png)

**Comment by matkoniecz** [comment]
> What would you think would be a reasonable interval in which to ask for every single speed bump if it is still there?

No sure, vast majority would stay for long. 8 years? If it would be implemented I would gladly test it to check what would be fitting interval in my area.

**Comment by peternewman** [comment]
They certainly talked about it in the UK:
https://www.independent.co.uk/news/uk/home-news/speed-bumps-disappear-uk-roads-air-pollution-government-plan-emissions-councils-remove-a7862811.html

**Comment by joepie91** [comment]
Great, thanks!
