### ISSUE TITLE
Gebäudeeigenschaften direkt nacheinander erfassen

### ISSUE THREAD

**Issue by chrissikay** [streetcomplete/StreetComplete#2676]
**Use case**
Aktuell ist erst ein Upload einer Eigenschaft notwendig, bevor die nächste Frage erscheint. Bei 3 aufeinander aufbauenden Eigenschaften (Art des Hauses, Anzahl der Stockwerke, Dachform) ist das ein nicht unerheblicher Mehraufwand bei der Datenaufnahme (besonders, wenn kein Internet verfügbar ist).

**Proposed Solution**
Aanalog zu der Erfassung der Eigenschaften von Wegen / Straßen, sollten die Fragen bei Gebäuden direkt aufeinander aufbauen.

**Comment by FloEdelmann** [comment]
See also #124.

**Comment by westnordost** [comment]
Ja, das ist Teil des nächsten großen Releases.

**Comment by RubenKelevra** [comment]
Hey @chrissikay, wenns geht nur Tickets auf Englisch verfassen, damit niemand ausgeschlossen wird die zu lesen und zu verstehen. Danke! :)

**Comment by smichel17** [comment]
<details>
<summary>If you worry your English will be misunderstood, you can include both English and your native language, with one of them hidden inside a drop-down like this.</summary>

Hidden text goes in here.
</details>

---

This is how you do it:

```html
<details>
<summary>If you worry your English will be misunderstood, you can include both English and your native language, with one of them hidden inside a drop-down like this.</summary>

Hidden text goes in here.
</details>
```

**Comment by westnordost** [comment]
Nur um es klarzustellen: Wenn du Englisch nicht flüssig beherrscht, ist es OK in der Sprache deiner Wahl hier zu posten. Niemanden auszuschließen geht in beide Richtungen.

---

Just to clarify. It is OK to post in any language if you are not fluent in English. Not wanting to exclude anyone goes in both directions.

**Comment by peternewman** [comment]
> See also #124.

Depending on exactly what @chrissikay wants, this may or may not be solved by #124 (although based on the Google Translate I don't think it would be).

There are two similar/overlapping feature requests:

Immediately ask the next available quest when one has been answered (none of the quests, if I've picked good examples depend on the previous ones, you can answer all of them at the moment offline/without auto-upload, but you currently have to manually tap to select the next quest after answering the previous one):
Road name>Road surface>lit>pavement/sidewalk
This is what #124 is about.

Secondly, for quests which depend on each other, allow you to answer the dependent ones without upload and re-query delay (be that offline, with auto-upload off or just slow OSM API). E.g.:
pavement/sidewalk>pavement/sidewalk surface
It only asks the pavement/sidewalk surface once it's confirmed there is one. This isn't covered by #124 that I can see, but I think there were other issues about it.

**Comment by chrissikay** [comment]
> See also #124.
sorry. i didn't find this issue.

@westnordost - Danke für dein Verständnis. Ich schließe nun diesen zusätzlichen Issue, um weitere Irritationen zu vermeiden.
