### ISSUE TITLE
"Is this still here?"-quest for emergency=access_point

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#2679]
I think it wouldn't be wrong to ask for emergency=access_point if they still exist. But I don't know how the situation is outside of Germany and how often emergency=access_point are changed.

https://wiki.openstreetmap.org/wiki/Tag:emergency%3Daccess_point

**Comment by matkoniecz** [comment]
>  But I don't know how the situation is outside of Germany

Use anyway seems to be quite focused on Germany and surrounding areas https://taginfo.openstreetmap.org/tags/emergency=access_point#map

**Comment by HolgerJeromin** [comment]
The "old" https://wiki.openstreetmap.org/wiki/Tag:highway=emergency_access_point is more often used.

**Comment by tiptoptom** [comment]
So the question is, if 

- it should only be asked for emergency=access_point
- it should be asked for both tags
- it should be asked for both tags and highway=emergency_access_point should be replaced by emergency=access_point

**Comment by matkoniecz** [comment]
> and highway=emergency_access_point should be replaced by emergency=access_point

no, that is a bad idea for SC to do such things except cases where there is a clear and unambiguous support

And in cases where there is a clear and unambiguous support you can just make a bot edit.

**Comment by tiptoptom** [comment]
So @matkoniecz you think, it should be asked for both tags?

**Comment by westnordost** [comment]
Of course it should, but the tag should not be changed

Am 28. März 2021 13:35:13 MESZ schrieb tiptoptom ***@***.***>:
>So @matkoniecz you think, it should be asked for both tags? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2679#issuecomment-808884334

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tiptoptom** [comment]
@westnordost Is there an ability to show the reference number (ref=*) in the quest? I think this would be a nice feature to verify the note.

**Comment by westnordost** [comment]
Possible. However, any thing the "Is this still here? (X)" asks for, it must be possible to refer to it somehow. I.e. the X must be "emergency access point" in this case.

StreetComplete uses the (translated) preset from the iD editor for that. All the presets are managed here https://github.com/openstreetmap/id-tagging-schema
And I noticed that a preset for `highway=emergency_access_point` and also `emergency=access_point` is missing from the presets. There is an issue for that here https://github.com/openstreetmap/id-tagging-schema/issues/20

Until this is resolved, this feature is blocked.

**Comment by matkoniecz** [comment]
that repo seems to be very inactive - last commit in January (  https://github.com/openstreetmap/id-tagging-schema/commits/main ), PRs are not processed.

maybe extracting iD presets to a separate repo was done to reduce focus on tagging-specific issues?

**Comment by westnordost** [comment]
As long as iD uses this, it will be maintained. Though I wonder, Quincy has almost not been active at all on GitHub since 2021. Didn't the OSMF want to employ one maintainer for iD and wouldn't that be Quincy?

**Comment by matkoniecz** [comment]
I also though so - and iD activity seems to be quite reduced, see https://github.com/openstreetmap/iD/graphs/contributors (and it seems to be not happening on other branches... https://github.com/openstreetmap/iD/branches/active )

**Comment by westnordost** [comment]
I just implemented that. It's still not asked until it gets added to the id-tagging-schema but at least from the side of streetcomplete, it is ready.

**Comment by tiptoptom** [comment]
openstreetmap/id-tagging-schema#504
highway=emergency_access_point is in the presets now. Just out of interest, when and how are the ID presets coming into Streetcomplete?

**Comment by westnordost** [comment]
I'll do now.

**Comment by westnordost** [comment]
https://github.com/streetcomplete/StreetComplete/commit/c6f553859274157079ad429e9f485b8c069cb6d2

**Comment by tiptoptom** [comment]
Let's see when the next version will be released. :joy:
