### ISSUE TITLE
side_hipped roof shape

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2681]
Add support for `side_hipped` roof shape. Per https://wiki.openstreetmap.org/wiki/Key:roof:shape

> Half of a hipped roof, not the same as half-hipped. One vertical gabled side, one 'hip' with three sloped faced. This is common on semi-detached properties where the whole building has a hipped roof but each house has a side_hipped roof.

They are extremely common for houses (probably 30% hipped, 30% gabled, 30% side_hipped) around me.

Currently it's unclear to users how they should map these, even myself I'm just randomly choosing either hipped or gabled each time which is not ideal!

Doing an image of this is tricky to clearly show the difference between hipped and gabled, but if you'd accept a PR I can try.

**Comment by westnordost** [comment]
Can you show a picture?

Am 26. März 2021 12:11:45 MEZ schrieb Andrew Harvey ***@***.***>:
>Add support for `side_hipped` roof shape. Per
>https://wiki.openstreetmap.org/wiki/Key:roof:shape
>
>> Half of a hipped roof, not the same as half-hipped. One vertical
>gabled side, one 'hip' with three sloped faced. This is common on
>semi-detached properties where the whole building has a hipped roof but
>each house has a side_hipped roof.
>
>They are extremely common for houses (probably 30% hipped, 30% gabled,
>30% side_hipped) around me.
>
>Currently it's unclear to users how they should map these, even myself
>I'm just randomly choosing either hipped or gabled each time which is
>not ideal!
>
>Doing an image of this is tricky to clearly show the difference between
>hipped and gabled, but if you'd accept a PR I can try.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2681

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by peternewman** [comment]
> Can you show a picture?

Take:
https://wiki.openstreetmap.org/w/images/thumb/6/67/Roof2_4.jpg/671px-Roof2_4.jpg

Cut in half along the long edge, discard one half.

AKA map that roof as two separate semi-detached buildings.

The jagged brickwork pattern in the middle here represents the party wall between the two houses:
https://en.wikipedia.org/wiki/Semi-detached#/media/File:ParkwayHousesSeacroft.jpg

Therefore you'd be answering the roof quest twice, once for each half of that roof.

See also:
https://all-loft-conversions.co.uk/wp-content/uploads/2016/11/new-gable-from-hipped-w-vel.jpg
https://fet.uwe.ac.uk/conweb/house_ages/1930s1hip.jpg

I think this can also happen for half-hipped, pyramidal, mansard and perhaps to some extent dome and onion, but perhaps more rarely. I think I've seen some side-half-hipped (someone has even used it 100 times).

**Comment by smichel17** [comment]
>The jagged brickwork pattern in the middle here represents the party wall between the two houses:
>  [![image](https://user-images.githubusercontent.com/6563664/112660408-52efb800-8e4d-11eb-8f2b-1d836eec7f8c.png)](https://en.wikipedia.org/wiki/Semi-detached#/media/File:ParkwayHousesSeacroft.jpg)


That whole building wouldn't be mapped as a semi-detached?

**Comment by peternewman** [comment]
> That whole building wouldn't be mapped as a semi-detached?

It should be mapped as two:
https://wiki.openstreetmap.org/wiki/Tag:building%3Dsemidetached_house

See also:
https://wiki.openstreetmap.org/wiki/Key:building#Accommodation

**Comment by smichel17** [comment]
> Interconnected homes of more than two units (commonly called a "triplex", "quadruplex", or more generally a “multiplex” should be tagged as building=terrace or building=house, depending on the configuration of the units. 

Interesting. Most 2-unit interconnected homes in my area are mapped as a single building, which I have been tagging as semi-detached.

**Comment by peternewman** [comment]
I used to make that mistake with terrace. Actually it looks like we need another https://github.com/streetcomplete/StreetComplete/commit/781e07833e6843a245a9ac8d41d9a4cfeda91aed

As SC has it wrong for semidetached too.

**Comment by westnordost** [comment]
I'm leaning towards will-not-fix. The roof shape is supposed to be the "simple" roof shape, in other words, the basic roof shape.

Not picture for this exists on the wiki and as far as I remember, that tag did not exist or wasn't described when the quest first got implemented. This means, that such situations are usually tagged `hipped`. Introducing `side_hipped` implicitly redefines the `hipped` tag.

You can change my mind by showing me evidence that data consumers that actually use the roof shape data interpret `side_hipped` differently.

**Comment by andrewharvey** [comment]
> https://all-loft-conversions.co.uk/wp-content/uploads/2016/11/new-gable-from-hipped-w-vel.jpg
> https://fet.uwe.ac.uk/conweb/house_ages/1930s1hip.jpg

Yes that's it.

> This means, that such situations are usually tagged hipped.

That's fine if that's the intention. Currently it's just not clear in SC if I should select hipped or gabled or has multiple roof types.

Non-rectangular buildings are common, so with the example pictures it can be hard to tell what tag to select for more hybrid roof shapes.

> You can change my mind by showing me evidence that data consumers that actually use the roof shape data interpret side_hipped differently.

I have no idea about that.
