### ISSUE TITLE
Handrail Left/Right/Centre

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2683]
### General
Affected tag(s) to be modified/added: [handrail:left](https://wiki.openstreetmap.org/wiki/Key:handrail:left)/[handrail:right](https://wiki.openstreetmap.org/wiki/Key:handrail:right)/[handrail:center](https://wiki.openstreetmap.org/wiki/Key:handrail:center)
Question asked: **Does this staircase have a handrail on the left/right/center?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - See https://wiki.openstreetmap.org/wiki/Key:handrail
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - Yes
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - Yes
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - Yes
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - Yes

See also #2162, #1390 and #503.

@westnordost previously said:
Okay, makes sense. Though, I would limit this quest to specifying whether it has a handrail or not, not where it is.

_Originally posted by @westnordost in https://github.com/streetcomplete/StreetComplete/issues/1390#issuecomment-491617731_

Can I suggest the extension is beneficial for a few reasons:

- For blind/partially sighted people, if they are going downstairs it would allow any routing/guidance apps to direct them which side of the stairs have the handrail, so they're not lunging for something while heading downhill. See also the kerb stuff where we're adding a comparable level of detail.
- For anyone with physical/muscular issues (e.g. stroke/amputation etc) they may have limited, or no strength/grip on one side, so route planners could either direct them to walk a certain direction if for leisure (e.g. clockwise not anti-clockwise on a circular walk) or to take a different route. Otherwise their only option may be to go down backwards.

### Ideas for implementation
Like the sidewalk quest, but with a middle "lane" too.

**Element selection:** 

Either finding pre-tagged handrails, so people can filter out this level of detail, or just replacing the existing quest and using that data to not ask it for handrail=no.

**Comment by westnordost** [comment]
> Can I suggest the extension is beneficial for a few reasons:

>     For blind/partially sighted people, if they are going downstairs it would allow any routing/guidance apps to direct them which side of the stairs have the handrail, so they're not lunging for something while heading downhill. See also the kerb stuff where we're adding a comparable level of detail.
>     For anyone with physical/muscular issues (e.g. stroke/amputation etc) they may have limited, or no strength/grip on one side, so route planners could either direct them to walk a certain direction if for leisure (e.g. clockwise not anti-clockwise on a circular walk) or to take a different route. Otherwise their only option may be to go down backwards.

That is... very very specific. Too specific. Think about the effort it takes to implement and translate it, but also the effort it takes from the contributors to gather all that data worldwide for that case. I'll close this as will not fix for now. If there is in the future actually an app that uses this data, I may reconsider.

**Comment by peternewman** [comment]
> That is... very very specific. Too specific.

Is it any different to the kerb stuff? It certainly feels like it's got a more "wholesome" use than Royal Cypher for example, they've also got broadly comparable uptake.

> Think about the effort it takes to implement and translate it, but also the effort it takes from the contributors to gather all that data worldwide for that case. I'll close this as will not fix for now.

Are you actively going to refuse a PR then? It would really be nice to sort out some labelling as mentioned here:
https://github.com/streetcomplete/StreetComplete/discussions/2549

> If there is in the future actually an app that uses this data, I may reconsider.

I haven't looked to confirm there isn't, well OSM2World claims to use it.

**Comment by westnordost** [comment]
> Are you actively going to refuse a PR then?

Probably not. If you are going to make one, let me know and I will look a little deeper into that tagging to see if it is in any way problematic of some sort.

> OSM2World

3D rendering doesn't count as use case.
