### ISSUE TITLE
Inaccurate description for semi-detached house

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#2685]
From https://github.com/streetcomplete/StreetComplete/issues/2681:

---

@peternewman
> The jagged brickwork pattern in the middle here represents the party wall between the two houses: 
> https://en.wikipedia.org/wiki/Semi-detached#/media/File:ParkwayHousesSeacroft.jpg
> Therefore you'd be answering the roof quest twice, once for each half of that roof.

@smichel17
>  [![image](https://user-images.githubusercontent.com/6563664/112660408-52efb800-8e4d-11eb-8f2b-1d836eec7f8c.png)](https://en.wikipedia.org/wiki/Semi-detached#/media/File:ParkwayHousesSeacroft.jpg)
> That whole building wouldn't be mapped as a semi-detached?

@peternewman:
> It should be mapped as two:
> https://wiki.openstreetmap.org/wiki/Tag:building%3Dsemidetached_house
> See also:
> https://wiki.openstreetmap.org/wiki/Key:building#Accommodation

@smichel17
> Most 2-unit interconnected homes in my area are mapped as a single building, which I have been tagging as semi-detached.

@peternewman

> I used to make that mistake with terrace. Actually it looks like we need another https://github.com/streetcomplete/StreetComplete/commit/781e07833e6843a245a9ac8d41d9a4cfeda91aed
> 
> As SC has it wrong for semidetached too.

**Comment by smichel17** [comment]
@peternewman What should the description be for semi-detached? What's the right way to handle a situation where a semi-detached house is mapped as a single object? (Also what is the right osm term for "object"? node? relation?)

Is it always wrong to have a semi-detached house that is not touching another semi-detached? In that case it seems fine to tag the whole thing as semi-detached and then later a quest could be added to split the house (e.g. https://github.com/streetcomplete/StreetComplete/issues/2585) or it could be done with another tool.

**Comment by westnordost** [comment]
This seems like a dejavu. We already had this topic before. I can't find it now.

In a nutshell:
1. The buildings were not drawn with StreetComplete
2. Some semi-detached buildings are mapped as one building, some as one building. This is the de-facto situation.
3. There is not the possibility to split up a building
3. Thus, in StreetComplete, the naming should be to be inclusive to both

**Comment by riQQ** [comment]
See also #2467

**Comment by peternewman** [comment]
Thanks for opening @smichel17 .

> This seems like a dejavu. We already had this topic before. I can't find it now.

In terms of the deja-vu, specifically you probably mean:
https://github.com/streetcomplete/StreetComplete/issues/2467#issuecomment-756907183

Or the terrace house thing.

> In a nutshell:
> 
>     1. The buildings were not drawn with StreetComplete
> 
>     2. Some semi-detached buildings are mapped as one building, some as one building. This is the de-facto situation.

Do you mean "mapped as one building, others as two buildings"?
 
>     3. There is not the possibility to split up a building in the app
> 
>     4. Thus, in StreetComplete, the naming should be to be inclusive to both

Surely as per other topics where this has come up (toilets, parking etc), SC shouldn't create or redefine tags? The wiki seems fairly clear that it's half of a physical building.

Personally I'd agree the tagging scheme is a bit flawed, as this is opposite to terraced house, logically if they were actually designed from scratch you'd probably want separate terms for the run (a terrace/a pair of semis) and the singular (a terraced/semi). Then you can get any interesting stats like how many of each type in an area.

**Comment by westnordost** [comment]
> Do you mean "mapped as one building, others as two buildings"?

Yes

> Surely as per other topics where this has come up (toilets, parking etc), SC shouldn't create or redefine tags? The wiki seems fairly clear that it's half of a physical building.

It isn't redefining tags. Maybe it is clear now(?), I don't know. See the discussion page, it wasn't so clear before and I recall various discussions on this on various channels with different opinions. In any case, based on my experience, I am claiming that the de-facto situation is that the tag is used in both ways. You are welcome to prove me wrong.
Also, the point still stands, StreetComplete users are not destroying any data this way: The building was mapped as two separate halfs / one whole building outline for both halves before, users of STreetComplete are just adding if that building (halves) are (part of) a semi-detached. This is nevertheless important information - actually especially for those who want to "clean up" the taggings because only then, they know that any one building is semi-detached so they'll be able to split it up / merge it together accordingly.

**Comment by peternewman** [comment]
> > Surely as per other topics where this has come up (toilets, parking etc), SC shouldn't create or redefine tags? The wiki seems fairly clear that it's half of a physical building.
> 
> It isn't redefining tags.

Okay maybe not tags, but as was pointed out here, it's redefining the English word/phrase at least:

>     English wikipedia [1]: A semi-detached house (often abbreviated to semi) is a single family duplex dwelling house that shares one common wall with the next house.
>     Collins dictionary [2]: A semi-detached house is a house that is joined to another house on one side by a shared wall.
>     Cambridge Dictionary [3]: A house that is semi-detached is one that is joined to another similar house on only one side.
>     Dictionary.com [4]: partly detached of or relating to a house joined by a party wall to another house or row of houses.

> Maybe it is clear now(?), I don't know.

The first instance of the Tag:building=semidetached_house page:
https://wiki.openstreetmap.org/w/index.php?title=Tag:building%3Dsemidetached_house&oldid=1632198

Likewise the first of Key:building:
https://wiki.openstreetmap.org/w/index.php?title=Key:building&direction=next&oldid=638796

As a native speaker, my best guess is the confusion may be two-fold. Firstly there is no defined tagging for the pair of semis and secondly the differences with terrace; consider:
I live in a terrace - multiple
My house is a terraced house - singular
My house is (mid/end of) terrace - singular
I live in a semi(-detached) house - singular

In the UK at least, people don't commonly talk specifically the building they share a party wall with, we talk about our neighbours, but they are the ones on both sides, whether detached, semi or terraced.

> In any case, based on my experience, I am claiming that the de-facto situation is that the tag is used in both ways. You are welcome to prove me wrong.

That may well be the case, and like others it's burnt. However SC only references the whole building in it's description. Changing it from:
Semi-detached house
pair of two single-family homes

To:
Semi-detached house
or occasionally pair of two single-family homes

Or dropping the occasionally depending on strength of feeling, would improve things.

Interestingly I see the UK translation just has "semi-detached house" for the second line.

> Also, the point still stands, StreetComplete users are not destroying any data this way: The building was mapped as two separate halfs / one whole building outline for both halves before, users of STreetComplete are just adding if that building (halves) are (part of) a semi-detached. This is nevertheless important information - actually especially for those who want to "clean up" the taggings because only then, they know that any one building is semi-detached so they'll be able to split it up / merge it together accordingly.

Assuming the other half hasn't been destroyed, rebuilt or whatever (admittedly generally rare). But you've got to craft some complicated query to filter out semis which share two or more nodes with another semi.

Given the current app description, and a pair of semis which have been correctly mapped as two areas, what are they going to tag them as? House currently says "non-detached single-family home"/"not detached house" which is the best fit for a single semi of the SC choices. So to match the wiki, people then need to convert those house taggings to semi too.

I'll say again, I don't think the current tagging is the best it could be, but like the gendered toilets it would seem better to me if we don't continue to make it worse:
> Personally I'd agree the tagging scheme is a bit flawed, as this is opposite to terraced house, logically if they were actually designed from scratch you'd probably want separate terms for the run (a terrace/a pair of semis) and the singular (a terraced/semi). Then you can get any interesting stats like how many of each type in an area.

**Comment by westnordost** [comment]
Right. Let's find a wording for the description that is inclusive to both. And is short.

Maybe
```` 
**Semi-detached house**
or pair of these
```
?

**Comment by westnordost** [comment]
Or for the description:

> home(s) that share a wall with a twin

?

**Comment by smichel17** [comment]
Hmm, maybe I have misunderstood and been tagging these wrong. 

https://www.google.com/maps/@42.3268198,-72.6436574,3a,75y,218.71h,98.33t/data=!3m6!1e1!3m4!1sAB9u-sZ0GKFcYySly5tZ2A!2e0!7i13312!8i6656

This is a two family house. It was originally built as a detached house, but has been renovated to be two units. Both are apartments, but the owner used to live in one side. It's split roughly like this:

![house](https://user-images.githubusercontent.com/6563664/112777142-ee8d4e00-9030-11eb-9ea7-e693156d3783.png)

(I would have screenshotted street view, but I'm not sure the copyright)

According to the discussion here, as I understand it, this should be tagged either "detached house" or "apartments". Up until now, I would have tagged this as a semi-detached house.

**Comment by SafetyIng** [comment]
> In any case, based on my experience, I am claiming that the de-facto situation is that the tag is used in both ways. You are welcome to prove me wrong.
For example, through incorrect wording in Streetcomplete. 
And no, we don't need to find a new wording. We need to use the wording from Wiki. And this is clear. An semi/duplex-Building is builded by two semidetached-Buildings. 

When there is a error, because there are only one building, than make a note and repair it. But it is not the duty of SC to find a new wording.

**Comment by peternewman** [comment]
@SafetyIng I think your quoting got messed up, I think you possibly mean this (you need gaps between different levels of quoting)

> > In any case, based on my experience, I am claiming that the de-facto situation is that the tag is used in both ways. You are welcome to prove me wrong.

> For example, through incorrect wording in Streetcomplete.
> And no, we don't need to find a new wording. We need to use the wording from Wiki. And this is clear.

> > > An semi/duplex-Building is builded by two semidetached-Buildings.

> When there is a error, because there are only one building, than make a note and repair it. But it is not the duty of SC to find a new wording.

**Comment by SafetyIng** [comment]
> @SafetyIng I think your quoting got messed up, I think you possibly mean this (you need gaps between different levels of quoting)

Cleaned up - Thx

**Comment by peternewman** [comment]
> Hmm, maybe I have misunderstood and been tagging these wrong.
> 
> https://www.google.com/maps/@42.3268198,-72.6436574,3a,75y,218.71h,98.33t/data=!3m6!1e1!3m4!1sAB9u-sZ0GKFcYySly5tZ2A!2e0!7i13312!8i6656
> 
> This is a two family house. It was originally built as a detached house,

From my understanding that means it should be `building=detached`

> the value may be used to classify the type of building. Note that it may be not the same as the building's current use (tagged using building:use=*). For example, a hospital building that is abandoned or repurposed to be a marketplace is still a building=hospital, and to mark active hospitals amenity=hospital is used.

> but has been renovated to be two units. Both are apartments, but the owner used to live in one side. It's split roughly like this:

Although it then seems to go a bit vague as there's no guidance for when building:use is more specific than just residential!

Are the left and right doors entrances to the two apartments?

> According to the discussion here, as I understand it, this should be tagged either "detached house" or "apartments". Up until now, I would have tagged this as a semi-detached house.

I'd probably imagine the apartment use is going to be more relevant to most people than the fact it was in the form of a single family home. E.g. it may have multiple families, multiple addresses etc.

**Comment by smichel17** [comment]
> Are the left and right doors entrances to the two apartments?

Correct. The ground floor layout is something like this (not exactly to scale):

![image](https://user-images.githubusercontent.com/6563664/112859113-0e108f00-90a2-11eb-9f34-3217a8269af9.png)

The entrances on the side are the two porches you can see, which lead into each respective apartment's kitchen, then bathroom and living room.

The two yellow lines are the ground floor windows, in the left apartment's living room.

The blue lines are staircases from each living room to the upstairs. The red line is a removable section of wall (with some hassle; it's screwed in) that allows larger objects like beds to be carried upstairs.

Upstairs, the left apartment has one bedroom and bathroom (I think… it might be 2 beds & 1 bath). The right apartment has 2 beds & 1 bath upstairs, and a staircase to the attic, which is large enough to serve as another bedroom (or den, etc).

The left and right apartments have different house numbers (not just different letters for the same number).

**Comment by westnordost** [comment]
How about changing the description to _"Adjoined single-family home(s)"_?

@SafetyIng @riQQ

**Comment by peternewman** [comment]
> The entrances on the side are the two porches you can see, which lead into each respective apartment's kitchen, then bathroom and living room.
> 
> The two yellow lines are the ground floor windows from the drawing above, in the left apartment's living room.
> 
> The blue lines are staircases from each living room to the upstairs. The red line is a removable section of wall (with some hassle; it's screwed in) that allows larger objects like beds to be carried upstairs.

So many questions, but not really SC related. I think in the UK they'd generally split it top and bottom, rather than this crazy arrangement so there would be one staircase to upstairs which would be one apartment and downstairs would be another one. Although in blocks of flats they do sometimes build them so they're like this (e.g. see the scissor flat drawing here):
https://en.wikipedia.org/wiki/Apartment#Maisonette

So I guess based on Wikipedia's definition it should be a maisonette, which has some usage:
https://taginfo.openstreetmap.org/tags/building=maisonette#overview

But given it was built as a detached house presumably building=house and residential usage.

**Comment by peternewman** [comment]
> How about changing the description to _"Adjoined single-family home(s)"_?
> 
> @SafetyIng @riQQ

I think if it was _"Adjoined single-family home"_ that would match the wiki. Your suggestion is still ambiguous and allows both types of tagging (presumably by design), but I guess it's better than the status quo as it at least acknowledges the wiki's definition that it should be a singular home rather than only mentioning the pair.

**Comment by riQQ** [comment]
> 
> 
> How about changing the description to _"Adjoined single-family home(s)"_?
> 
> @SafetyIng @riQQ

It's better and I can't think of any improvement in the current situation. Optimally, it would be clearly defined in the wiki :(.
