### ISSUE TITLE
Don't ask for opening hours of malls

### ISSUE THREAD

**Issue by kjonosm** [streetcomplete/StreetComplete#2687]
Shops within a mall may often have individual opening hours, see e.g. [here](https://www.openstreetmap.org/note/2594966)

**Comment by andrewharvey** [comment]
> Shops within a mall may often have individual opening hours, see e.g. here

That's fine, SC already asks for each individual shop opening hours even when the mall has opening hours tagged.

I for asking for opening hours of malls. According to taginfo 11% of malls have an opening_hours tagged https://taginfo.openstreetmap.org/tags/shop=mall#combinations, so I don't think this is insignificant enough not to ask.

**Comment by smichel17** [comment]
I'll +1 @andrewharvey, I'm not a big mallgoer but my local malls mostly have both individual shop hours *and* hours for the whole mall.

**Comment by westnordost** [comment]
Malls usually have opening hours posted, too. F.e. you won't be able to go inside a mall at 3 in the morning. So, no reason to exclude malls from that quest.
