### ISSUE TITLE
bicycles not allowed here as answer to cycleway quest

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2688]
In the existing "Is there a cycleway here" quest, under the other answers there should be an option "bicycles not allowed here", which instead of tagging cycleway=no tags bicycle=no which kind of implies there is no cycleway.

**Comment by westnordost** [comment]
I wouldnt like to conflate this. People might assume wrongly that bicycles are not allowed if there is no bicycle infrastructure and the road does not look safe. 
Also I'd guess that an explicit prohibition is rare enough that it's ok to leave a note. 
The worst is not asked for motorroads and motorways after all

Am 28. März 2021 13:00:04 MESZ schrieb Andrew Harvey ***@***.***>:
>In the existing "Is there a cycleway here" quest, under the other
>answers there should be an option "bicycles not allowed here", which
>instead of tagging cycleway=no tags bicycle=no which kind of implies
>there is no cycleway.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2688

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andrewharvey** [comment]
Fair enough.
