### ISSUE TITLE
Extend curb quest to highway=crossings without a way

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2689]
**Use case**
In my area, most sidewalks are directly connected to the street, not separated by a green strip. So mapping them as individual lines is wrong IMHO.

So crossings are single nodes on the highway, while the sidewalks are tags on the highway.

**Proposed Solution**
Is there a chance to extend the curb-quest to single node crossings as well, with `curb:right/left` or `curb:forward/backward`?

**Comment by matkoniecz** [comment]
`curb:right/left` or `curb:forward/backward`

See https://taginfo.openstreetmap.org/search?q=curb%3Aforward https://taginfo.openstreetmap.org/search?q=curb%3Aright - this would mean that StreetComplete would be inventing new tags, without them being accepted by community.

Is such tagging idea accepted and welcomed? If no, then it is definitely not going to be added to SC.

**Comment by RubenKelevra** [comment]
@matkoniecz well, JOSM uses `kerb=*` on crossings.

`kerb:right/left` (or `: forward/backward` - not sure which one would fit better here) is just for detailing if it's different per side.

The subkey `:right/left` isn't new and used all over the database and is documented in the wiki:

> Alternatively, on the crossing node, kerb:left=* and kerb:right=* can be used.

Source: [Key:crossing#Accessibility](https://wiki.openstreetmap.org/wiki/Key:crossing#Accessibility)

**Comment by matkoniecz** [comment]
OK, `kerb:right` has some minimal use - https://taginfo.openstreetmap.org/keys/kerb%3Aright

**Comment by westnordost** [comment]
>  So mapping them as individual lines is wrong IMHO. 

Not wrong, but not not wrong.

**Comment by westnordost** [comment]
Anyway, I'd say that the use is too minimal. There is not even documentation for that on the wiki. (You can create one that documents the current use, but this wouldn't make it possible to create a quest for now as of now.) Current use of this tag is at 0.02% of all crossings.

> In my area, most sidewalks are directly connected to the street, not separated by a green strip. So mapping them as individual lines is wrong IMHO.

I used to have the same opinion on that, but it changed latest after having to implement the cycleway quest. It seems like a swift solution to put the sidewalk and cycleway onto the road way, but if you cross a certain level of detail, it becomes really really hard to manage, both for mappers, for data consumers and (smart) editing software.

**Comment by westnordost** [comment]
So, won't fix for now

**Comment by RubenKelevra** [comment]
> > In my area, most sidewalks are directly connected to the street, not separated by a green strip. So mapping them as individual lines is wrong IMHO.
> 
> I used to have the same opinion on that, but it changed latest after having to implement the cycleway quest. It seems like a swift solution to put the sidewalk and cycleway onto the road way, but if you cross a certain level of detail, it becomes really really hard to manage, both for mappers, for data consumers and (smart) editing software.

I agree on complex intersections, but there's IMHO no point to add individual ways for the sidewalk next to the street. 

It's pretty messy - since there's hardly any source for the exact position of the way, let alone the center of the sidewalk which leads to the distance from the street is randomly chosen by each mapper.

It also breaks the assumption that you can reach the street if the sidewalk is tagged on the street, while an individual way has the assumption by routers that you need an intersection to be able to reach the road.

I tend to put the details around large intersections, and just connect the sidewalks to the road afterwards - but only if there's a reliable source for this information. 


> Anyway, I'd say that the use is too minimal. There is not even documentation for that on the wiki. (You can create one that documents the current use, but this wouldn't make it possible to create a quest for now as of now.) Current use of this tag is at 0.02% of all crossings.

Well yeah, the information is sparsely available in the database, but it's very valuable for wheelchair users. I think that the information is hardly captured is more of an argument to add it than not.

It's easily parseable, follows a common tagging scheme and is easily parseable by routers for wheelchair users.

**Comment by RubenKelevra** [comment]
@westnordost forgot to mention you :)

**Comment by matkoniecz** [comment]
@RubenKelevra Note that none of your arguments answers reason for rejecting this idea for now.

**Comment by RubenKelevra** [comment]
@matkoniecz wrote:

> @RubenKelevra Note that none of your arguments answers reason for rejecting this idea for now.

Okay, maybe I got something wrong. What's the reason to reject it?

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/2689#issuecomment-808923012
