### ISSUE TITLE
Asking the colour of buildings.

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#2694]
### General
Affected tag(s) to be added: [`building:colour`](https://wiki.openstreetmap.org/wiki/Key:building:colour) (and [`roof:colour`](https://wiki.openstreetmap.org/wiki/Key:roof:colour) in a similar but separate quest)
Example of items with these tags: https://www.openstreetmap.org/way/272006373 and https://www.openstreetmap.org/way/62278743

The colour of buildings and roofs is mainly used in 3D renderings like [OSMBuildings](https://osmbuildings.org)—it could also in theory be used for 2D maps, but I haven’t seen any using these tags.
Some neighbourhoods are famous for their colourful houses, and such a quest can help noticing them in maps.
It can also be useful to help spreading the use of OSM: one feedback I often get when sharing OSMBuildings links to non-OSM people is that its buildings are colorless. It could also be helpful when planning walks to choose colourful streets, which are not always known.
Finally, colours might be useful as they provide additional reference points (e.g., “let’s meet next to the red building on this street”).

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one): all building have colors. However, there is no `many` value for the tag `building:colour`: there might be some corner cases in which the user would just want to say that there are many colors without picking any particular.
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: see discussion below for how to pick colours. The roof colour may be taken from aerial imagery instead of a survey.
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam): this may depend on the region. I guess that this is similar than the building-level quest.
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort).

### Ideas for implementation

**Element selection:** 
As this key is currently mainly used by 3D renderer, I suggest only asking for buildings with a number of levels already referenced.

For `roof:colour`, I suggest selecting all building with a `roof:shape` key already filled in, filtering out high buildings and flat roofs.

These selections would also have the advantage that these building quests would be late, thus focussing first on the important properties of buildings (building type and number of levels) before more aesthetic properties (like roof shape and building colours—although roof shape has non-aesthetic applications).

**Ideas for the GUI:**
The wiki for [`roof:colour`](https://wiki.openstreetmap.org/wiki/Key:roof:colour) suggests a limited amount of values which I think is usually enough for most cases, and can fit quite easily on a StreetComplete quest.

The key `building:colour` is trickier as the wiki [suggests](https://wiki.openstreetmap.org/wiki/Key:colour) either to use hexadecimal colours (with far too many options), or a very limited set of colours. This limited set of colour doesn’t have common values like orange, for instance, and I find it quite limiting (orange is a common choice in my city).

An possible approach would be to only suggest the 16 basic colour names as a choice. An other approach would be to use the user’s camera. For instance by displaying a rectangle whose colour is the one of the pixel in the middle of what its camera is looking at—or the average colour of the given picture—, and asking the user to press a button when the colour fits. I don’t know how difficult such a camera-based colour picker would be to implement.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+building%3Acolour+is%3Aclosed or more specifically https://github.com/streetcomplete/StreetComplete/issues/1358#issuecomment-475990007

**Comment by Mbodin** [comment]
Oh, sorry, I missed this other quest suggestion.

I disagree with the unimportantness of this information, but I fully agree with the other arguments.
