### ISSUE TITLE
Don't ask "What barriers are used at this railway crossing?" for disused railway

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#2695]
Since #1413 StreetComplete doesn't ask this quest for abandonned railway. I think it should be the same for [disused railways](https://wiki.openstreetmap.org/wiki/Tag:railway%3Ddisused) as it seems to me that disused railways never have barriers.

Thanks for maintaining SC, and therefore OSM.

**Comment by westnordost** [comment]
Makes sense, thanks

**Comment by 351293** [comment]
> Since #1413 StreetComplete doesn't ask this quest for abandonned railway. I think it should be the same for [disused railways](https://wiki.openstreetmap.org/wiki/Tag:railway%3Ddisused) as it seems to me that disused railways never have barriers.
> 
> Thanks for maintaining SC, and therefore OSM.

This does not work in germany. railway=disused means, that there were no trains at the moment, but normally the rails and the "Bahnübergangssicherungsanlage" (DE) is still there. So the railway crossing still has barriers, but they remain opened.

**Comment by westnordost** [comment]
But they are not relevant anymore for routing

**Comment by westnordost** [comment]
As you say

>  So the railway crossing still has barriers, but they remain opened.
