### ISSUE TITLE
building levels from high ground

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2697]
I don't think the tags exist yet, but a common issue I face when answering the building levels quest is that it's defined and indeed building:levels is defined from the low side of the building.

However it's common with residential houses on a slope that the front of the house will have 1 level visible, but the back of the house actually has a level under it which meets the sloping land. So technically this should be building:levels=2, but that's not visible from the street level.

Ideally OSM would support two tags, building:levels:from_high_ground and building:levels:from_low_ground then one could just tag the information they can survey.

Until then, I know a lot of my surveyed building levels are probably wrong because I can only see from the street and not backyard.

**Comment by westnordost** [comment]
Well, posting this here is the wrong place.

**Comment by andrewharvey** [comment]
Feel free to close if you like, it's more just feedback for SC and to document this scenario as something that we need to tackle (on the tagging front) to make SC a better experience.

We need some place to track these kinds of issues as they do affect users of SC and need to be worked on.

**Comment by westnordost** [comment]
Ok.

Well, what you are looking for is an "OpenStreetMap tagging scheme issue tracker". Maybe post that in the discussion page on the wiki page for building:levels.

**Comment by andrewharvey** [comment]
I already did a month or so ago at https://wiki.openstreetmap.org/wiki/Talk:Key:building:levels#levels_between_low_and_high_ground
