### ISSUE TITLE
"Add pitch surface" quest display issue for sport=running

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#2698]
The "add pitch surface" quest has a display issue for sport=running. Instead of highlights just the way, it highlights the whole surface inside the way.

**How to Reproduce**
See [this POI](https://www.openstreetmap.org/way/922945221) for exemple

**Versions affected**
v31.1

**Comment by matkoniecz** [comment]
It should be simple to change default here, but not

> It's unclear/undecided whether closed ways should be treated as areas for this tag so it is advised to always add an area=yes/no tag in the case of closed ways.

at https://wiki.openstreetmap.org/wiki/Tag:leisure=track that as far as I can say is a good advise. Maybe it is a good idea for a quest?

**Comment by matkoniecz** [comment]
![screen05](https://user-images.githubusercontent.com/899988/112968623-c3981c80-914c-11eb-9839-7ac82ae3838f.png)
