### ISSUE TITLE
Tiles taking several days to update

### ISSUE THREAD

**Issue by tlocke** [streetcomplete/StreetComplete#2701]
Hi, thanks for the wonderful app, I use it daily and it's a great contribution to the OSM ecosystem. I use StreetComplete in conjunction with the iD editor on OpenStreetMap.org, but I find that after I've made an edit using iD it takes a long time (several days) before the change is visible in StreetComplete. I notice that the quests refer to the updated information but it seems that it's the tiles that are out of date. If it's possible to update the tiles more quickly, that would be amazing! Thanks :-)

I'm on Android 10 and StreetComplete v31.1.

**Comment by riQQ** [comment]
See also #2479.

**Comment by RubenKelevra** [comment]
Hey,

we [answered this question a while ago on Twitter](https://twitter.com/StreetComplete/status/1360691755264401408?s=19). This behavior is intended and I don't think it'll change, due to much higher bandwidth and server load, doing soo.

**Comment by matkoniecz** [comment]
> I notice that the quests refer to the updated information

Quests are using OSM editing API that is updated immediately.

Tiles are from different source, provided by JawgMaps and updating on own schedule (see https://github.com/streetcomplete/StreetComplete#sponsors for more info).

There is also additionally on-device caching, see #2479
