### ISSUE TITLE
Opening Hours: Suggest 10-4 on Sundays in the UK

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2702]
When I'm adding opening hours for a shop for Sundays, it's most likely going to be 10:00-16:00 on a Sunday as that's the law for most shops here in the UK.

Currently it defaults to 08:00-18:00 and can get annoying to change

**Comment by westnordost** [comment]
Bakeries are not open before 10:00 on Sunday in the UK?

**Comment by kmpoppe** [comment]
This applies to Large Shops (>280 m2) in Wales and England: https://www.gov.uk/trading-hours-for-retailers-the-law

Therefore a small bakery with less than 280 m2 would not be bound to this rule.

**Comment by westnordost** [comment]
Hi @kmpoppe 👋, welcome back!

Regarding this ticket, well, if this is not even uniform for all shops on Sundays in the UK, I really don't think it is worth the effort to adapt the default here.

In regards to opening hours, I am thinking for a long time already that the interface from-to with that wallclock is really bad. (It is an Android system component) and a simple input field(s) in the form of `__:__ - __:__` with the numbers-only keyboard would be much faster and easier. A PR for that would be very welcome. If you feel the same, you could give it a try.

**Comment by TurnrDev** [comment]
> Bakeries are not open before 10:00 on Sunday in the UK?

I don't know for sure

> This applies to Large Shops (>280 m2) in Wales and England: https://www.gov.uk/trading-hours-for-retailers-the-law

A **lot** of small stores still follow their rule, at least near me.

I'm running some figures on Overpass to see if my local findings match a regional level. I will edit when I have the results.

**Comment by andrewharvey** [comment]
> a simple input field(s) in the form of __:__ - __:__ with the numbers-only keyboard would be much faster and easier.

Probably faster yes. Though the one thing I like about the wall clock is it converts from 12 to 24 hour times for me.

**Comment by kmpoppe** [comment]
> Probably faster yes. Though the one thing I like about the wall clock is it converts from 12 to 24 hour times for me.

The solution to this is easy: Give the user the option to choose which entry method they'd like.

a) the wall-clock
b) an entry field with numbers only and the visual formatting that @westnordost showed
c) an entry field that automagically converts something like this:
`0800a1100p` using `"(([0-1][0-9]|2[0-3])([0-5][0-9])([a|p])?)"gmi` into `08:00-23:00`
One could build a [regex-callback function](https://stackoverflow.com/questions/375420/java-equivalent-to-phps-preg-replace-callback) and use that to convert the given string. 

I don't know when I could find the time to implement something like that. @westnordost could you create a project ("time-entry redesign") and put this Issue in it, that would make glueing everything together easier?

K

**Comment by matkoniecz** [comment]
> The solution to this is easy: Give the user the option to choose which entry method they'd like.

That is not a always a good idea. You add config here and there and end with monster that is hard to test and requires configuration to use properly (obviously, it is oversimplification - but there is a good reason why settings are not added to SC unless absolutely necessary)

**Comment by kmpoppe** [comment]
I hear you, Mateusz. I work for a software company and our main product has upwards of 600 parameters, which isn't always easy to understand for administrators. The key is to have a default value that works for everyone (i.e. keep the current method as the default value) and allow those who _actively want_ to change something the possibility to do so.

I think it's good that SC hasn't got a whole load of parameters - because the main focus of the app is to put _consistent_ data into OSM.

In this case I believe that configuration would be in order because it's focus is the UI, not the data that it results into.

K

**Comment by westnordost** [comment]
I am with @matkoniecz here. We can test if `__:__ - __:__` (with added AM/PM somehow if the user's locale is in a place with AM/PM) is really better, and if it is, replace it. If not, then not. Regex won't do though, it'd need to be a custom view component cause it needs to be basically either a composite view of several edit texts and text views with some control regarding automatically focussing the next edit text when the input on the first is done or some completely custom component with own rendering (maybe this would actually be easier).

**Comment by kmpoppe** [comment]
Agreed.

Can you access the region/time settings of the device from inside the app? Never tried that...

K

**Comment by westnordost** [comment]
You mean in the Code? Pretty sure, yes. The user of course not.
