### ISSUE TITLE
V31.1 Beta - Quests flash while zooming. 

### ISSUE THREAD

**Issue by MaestroGlanz** [streetcomplete/StreetComplete#2703]
Night theme, because after 18:00
Version 31.1 beta
Finished a street name quest
Zoomed out, while doing so, the finished quest was visible for a moment.
Zoomed in and out to test
Scrolled to another place.
Finished a roof shape quest.
Zoomed in and out to test.
Same behavior
Scrolled back to the place with street name quest.
Zoomed in and out
No flashing.
Back to the place of the roof quest.
Zoomed in and out.
No flashing.

**Comment by westnordost** [comment]
Upstream issue, see
https://github.com/tangrams/tangram-es/issues/2133
