### ISSUE TITLE
What forms of payment are accepted here? (focusing on small businesses in the United States)

### ISSUE THREAD

**Issue by 1ec5** [streetcomplete/StreetComplete#2704]
### General
Affected tag(s) to be modified/added: [`payment:cash`](https://wiki.openstreetmap.org/wiki/Key:payment:cash), [`payment:cheque`](https://wiki.openstreetmap.org/wiki/Key:payment:cheque), [`payment:credit_cards`](https://wiki.openstreetmap.org/wiki/Key:payment:credit_cards), [`payment:debit_cards`](https://wiki.openstreetmap.org/wiki/Key:payment:debit_cards)
Question asked: **What forms of payment are accepted here?**

The following answers are for the United States; I don’t think any answers could be generalized globally.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
    * You don’t want to accidentally order at a sit-down restaurant, finish your meal, and only then realize you can’t pay.
    * You don’t want to accidentally get your hair cut and then realize you can’t pay.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
    * Virtually every restaurant or shop in the U.S. posts either the logos of credit/debit cards they accept or a “cash only” sign.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
    * Small businesses, especially in ethnic enclaves, are often cash-only establishments or only accept one credit card but not another.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

[![cash only](https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/*_CASH_ONLY_*_No_Debit_Cards%3B_No_Credit_Cards_%2833172689610%29.jpg/1024px-*_CASH_ONLY_*_No_Debit_Cards%3B_No_Credit_Cards_%2833172689610%29.jpg)](https://commons.wikimedia.org/wiki/File:*_CASH_ONLY_*_No_Debit_Cards;_No_Credit_Cards_%2833172689610%29.jpg)
[![restaurant](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/MetairieRoadMarkTwainTwain.JPG/576px-MetairieRoadMarkTwainTwain.JPG)](https://commons.wikimedia.org/wiki/File:MetairieRoadMarkTwainTwain.JPG)
[![hairdresser](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Fantastic_Sams_Ypsilanti.JPG/628px-Fantastic_Sams_Ypsilanti.JPG)](https://commons.wikimedia.org/wiki/File:Fantastic_Sams_Ypsilanti.JPG)

### Ideas for implementation

Probably similar to the `accepts_cash` quest.

**Element selection:** 

`amenity=restaurant`, `amenity=fast_food`, `amenity=cafe`, `amenity=ice_cream`, `shop=*` without `payment:*=*`

Not `amenity=fuel`, because gas stations accept a wider variety of payment options that might be worth implementing in a separate quest.

Not `tourism=*`, `leisure=*`, or `office=*`, because these facilities generally require booking an appointment, seat, or room in advance, which means they’re less likely to display accepted payment methods at the door.

Some `shop=*` values like `doityourself`, `department_store`, and `supermarket` tend to be big-box stores, so the fact that they all accept every major credit card isn’t very interesting. I think this quest should try to focus on POI types that are more likely to be small businesses.

**Metadata needed:** 

I’m most familiar with the situation in the United States, so maybe limit the quest to the U.S. for now to avoid the issues that seemed to derail #1573?

**Proposed GUI:**

The `payment:*` tagging scheme is very complex, but here are the options that would be useful in 99.99% of the cases in the United States. It starts with a menu of options, each of which can be unset or set to Yes or No. Selecting “Credit card” or “Contactless” reveals a secondary menu of logos.

* Cash (`payment:cash`)
* Check (`payment:cheque`)
* Credit card (`payment:credit_cards`)
   * American Express (`payment:american_express`)
   * Discover (`payment:discover_card`)
   * Mastercard (`payment:mastercard`)
   * Visa (`payment:visa`)
* Debit card (`payment:debit_cards`)
* Contactless (`payment:contactless`)
   * Apple Pay (`payment:apple_pay`)
   * Google Pay (`payment:google_pay`)

The `payment:*` scheme isn’t exhaustive, allowing for a partial answer. For example, if a storefront window only displays credit card logos but doesn’t explicitly indicate whether cash is accepted, the user can simply leave the “Cash” option unset. Or they can set it to Yes knowing that cashless businesses are unheard of in that area. (There are some cashless stores these days, but they’re rare and concentrated in certain cities.)

**Comment by TurnrDev** [comment]
With contactless and chip cards only recently arriving in America, I reckon it could be interesting to see the statistics of how often these technologies are advertised as accepted

**Comment by westnordost** [comment]
Some comments and additions:
- can't be `shop=*` as there is also `shop=vacant`, `shop=no` etc. Could use a similar list as for the opening hours quest
- would be an indoor-only quest, i.e. disabled by default, because not all shops have this information out front (especially those not that accept "all" payments)
- check: Really, you can pay with check in the US? And then you get the back the change as cash?
- cash: Is there really any place that does not allow cash? Wouldn't that be against the law? After all, it's legal tender no?

Since this is properly categorized, maybe this could be reduced to asking
[ ] credit card
[ ] debit card
, that's it. What kind of credit cards could then be a folllow-up quest. Regarding contactless, anyone knows the numbers on how much google and apple pay are actually accepted worldwide? Just looked up for Master card, they claim something like 36 million, Amex has less  "'many' millions", they say. Or is google and apple pay chained to a credit card or something like that, so that it is automatically accepted if the business accepts credit cards?

**Comment by andrewharvey** [comment]
> cash: Is there really any place that does not allow cash? Wouldn't that be against the law? After all, it's legal tender no?

Yes I've mapped a few (in Australia), it's a growing trend since cash is a pain to deal with compared to contactless. It's legal, retailers can set their payment terms https://www.canstar.com.au/credit-cards/payment-options/.

**Comment by westnordost** [comment]
In Australia. Maybe for this point, it would be worth to research in which countries it is legal to not accept cash and not show the "accepts cash" option there as it is implicitly "yes".

**Comment by 1ec5** [comment]
> * can't be `shop=*` as there is also `shop=vacant`, `shop=no` etc. Could use a similar list as for the opening hours quest

Yes, that would be a good starting point, though this proposal attempts to limit the set of tags even further to exclude big-box stores like `shop=doityourself` and `shop=supermarket` that typically accept every major form of payment. (That said, my area has [cash-and-carry supermarkets](https://nominatim.openstreetmap.org/ui/search.html?polygon=1&q=Cash%20and%20carry%2C%20Santa%20Clara%20County%2C%20California) that only accept cash. But you can tell from the name, so no surveying is needed.)

> * would be an indoor-only quest, i.e. disabled by default, because not all shops have this information out front (especially those not that accept "all" payments)

For sure, a more comprehensive quest would require indoor surveying. But I figured we could scope the quest tightly enough (small businesses in the U.S.) to assume the majority of candidate POIs post acceptable forms of payment at the door. I’ve say the photos in the original post are the norm in the U.S., rather than the exception. We could scope the quest more tightly to eateries to make that assumption even more reliable.

> * check: Really, you can pay with check in the US? And then you get the back the change as cash?

[Yes](https://www.quora.com/Why-do-most-grocery-stores-still-accept-checks-Why-not-just-force-people-to-use-debit-credit) and yes, but in practice, personal checks are [used rarely](https://www.quora.com/Why-do-people-still-use-checks-in-grocery-stores) these days compared to debit cards. Occasionally, I still see check acceptance signposted next to the credit card logos, but most of the time, if checks are mentioned at all, it’s a “no checks” sign. Some businesses might prefer the lower fees for cashing checks; others want to avoid the hassle of dealing with bad checks.

> * cash: Is there really any place that does not allow cash? Wouldn't that be against the law? After all, it's legal tender no?

In general, [it is lawful](https://smallbusiness.chron.com/rules-businesses-accepting-cash-70791.html) for privately owned retail businesses to decline cash. In the past, you’d only hear of a car dealership or furniture store declining large purchases by cash, but cashless stores have become more commonplace [in recent years](https://www.pbs.org/newshour/show/how-kids-are-adapting-to-a-cashless-culture). Last year, [San Francisco reacted by banning cashless stores](https://sf.eater.com/2020/5/12/21255983/san-francisco-sfpd-cash-coronavirus).

> Since this is properly categorized, maybe this could be reduced to asking
> [ ] credit card
> [ ] debit card
> , that's it. What kind of credit cards could then be a folllow-up quest.

There’s no way to tag “there are no other payment methods”, so maybe we should keep `payment:cash=yes` as an option to give us confidence that the POI is reasonably completely tagged. It would be fine to split out individual cards as a separate quest, but the basic quest could still depict the Visa/Mastercard/Amex/Discover logos as evidence of credit card acceptance, something to look for.

> Regarding contactless, anyone knows the numbers on how much google and apple pay are actually accepted worldwide? Just looked up for Master card, they claim something like 36 million, Amex has less "'many' millions", they say. Or is google and apple pay chained to a credit card or something like that, so that it is automatically accepted if the business accepts credit cards?

I proposed including this option only for completeness. I’ve lived in Silicon Valley since these payment methods were introduced, so my experience is probably quite biased. I do see Apple Pay and Google Pay logos – [even on parking meters](https://www.flickr.com/photos/willbuckner/43610719490) – but even here, at most POIs, you still have to walk up to the cash register to know whether NFC is accepted.

> Maybe for this point, it would be worth to research in which countries it is legal to not accept cash and not show the "accepts cash" option there as it is implicitly "yes".

I was under the impression that country-specific quests were OK since there’s already a payment-related quest for Sweden. But if there’s a desire to generalize the quest to cover a wider range of countries, I agree that additional research would be necessary to avoid a poor experience elsewhere.

**Comment by mnalis** [comment]
> In Australia. Maybe for this point, it would be worth to research in which countries it is legal to not accept cash and not show the "accepts cash" option there as it is implicitly "yes".

Perhaps this might be useful: https://en.wikipedia.org/wiki/Legal_tender#Status_by_country

**Comment by kmpoppe** [comment]
> Perhaps this might be useful: https://en.wikipedia.org/wiki/Legal_tender#Status_by_country
There's a literal ton of techno-babble involved but TL;DR - yes, even in Germany merchants can refuse to accept cash, they just have to state that crystal-clear before a purchase is imminent.

**Comment by 1ec5** [comment]
>> Since this is properly categorized, maybe this could be reduced to asking
>>   [ ] credit card
>>   [ ] debit card
>>   , that's it. What kind of credit cards could then be a folllow-up quest.
> 
> There’s no way to tag “there are no other payment methods”, so maybe we should keep payment:cash=yes as an option to give us confidence that the POI is reasonably completely tagged. It would be fine to split out individual cards as a separate quest, but the basic quest could still depict the Visa/Mastercard/Amex/Discover logos as evidence of credit card acceptance, something to look for.

As long as the quest doesn’t claim to cover all accepted payment methods, the simplified approach of just asking about credit and debit card acceptance would allow this quest to apply more generally to all kinds of businesses and probably not just in the U.S. Then more focused quests would be possible: not only the credit card logo quest, but also for instance a `payment:contactless` quest in specific geographies and POI types where we know NFC acceptance is common. That quest would look for `payment:contactless` specifically rather than `payment:*`. This is what you were suggesting, but it took me a little while to come to the same realization. 😅

The simplified credit/debit quest could still instruct the user to look for signs that say “cash only” just in case it isn’t obvious that it’s the way to identify a No and No.

**Comment by matkoniecz** [comment]
> But I figured we could scope the quest tightly enough (small businesses in the U.S.) to assume the majority of candidate POIs post acceptable forms of payment at the door. I’d say the photos in the original post are the norm in the U.S., rather than the exception. We could scope the quest more tightly to eateries to make that assumption even more reliable.

Note that majority is not sufficient, you would need a vast majority (or clear dominance at least). If 51% of places have such sign it is not good enough, if 97% have it then I think it would be fine to consider it as an outside quest.

BTW, I asked on https://osmus.slack.com/archives/C029HV951/p1649497612363789

**Comment by matkoniecz** [comment]
My plan is to ask "Can you pay here with card?" with following answers:

* Debit cards only
* Credit cards only
* Neither debit nor credit cards allowed

-------------

Google Pay, Apple Pay and similar are becoming more popular but there are outrageous amounts of local variants. https://wiki.openstreetmap.org/wiki/Key:payment lists some of them.

If that simple quest would become actually used then some more complex one can be created asking about all kinds of payments available (cash, cheque, BLIK, Apple Pay, Google Pay, Girocard, Rupay, UTA, ICSF and many other requiring extensive metadata).

It could be triggered if `payment:cash`, `payment:coins`, `payment:notes` are all not tagged and `payment:others=no` is not set. Or maybe when only credit/debit card status is set and other payment tags are not present.

-------------

I had an idea to skip objects tagged with `brand` `wikipedia:brand` `wikidata:brand` as such objects will almost always accept cash and credit cards and debit cards.

-------------

It appears than in USA distinguishing between brands of credit/debit cards may have dubious utility.

In Poland it definitely has zero utility.

**Comment by 1ec5** [comment]
> I had an idea to skip objects tagged with brand wikipedia:brand wikidata:brand as such objects will almost always accept cash and credit cards and debit cards.

Filtering by the absence of a brand tag is a great idea, a much more reliable way to limit the quest to small businesses than filtering by POI type. Some small businesses still operate very small chains of a few locations apiece, so they might still have `brand` without `brand:wikidata`. However, this might be difficult to distinguish from an undertagged POI.

> It appears than in USA distinguishing between brands of credit/debit cards may have dubious utility.

For context, OSMUS Slack was asked about Visa, MasterCard, Discover, and American Express. For decades, the latter two have struggled to shake a reputation of getting rejected by merchants, but [according to this report](https://www.nerdwallet.com/article/credit-cards/discover-american-express-acceptance), they more or less caught up to Visa/MasterCard during the pandemic. That statistic is for businesses that accept credit cards in general, but small businesses are somewhat more likely to accept only one or two of the cards.

Aside from the “Big Four”, there’s the second tier of credit cards: Diners Club, JCB, and UnionPay. I see these logos on most gas stations these days, but I have no idea if they’re prevalent enough on eateries or other small businesses for a quest – or too prevalent.

**Comment by matkoniecz** [comment]
BTW, I am considering extending range of asked places to what similar quests asks: https://github.com/streetcomplete/StreetComplete/blob/18189f123416d9a0b332e50afab58b857452b416/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt#L17-L49 (which would likely imply extracting this listing to some shared place)

And to exclude at least `shop=supermarket`

> Even if the quest doesn’t ask which specific credit cards are accepted, I’d still recommend including the logos in the quest so mappers know to look for them as an indication of credit card acceptance.

Not entirely sure - it is going to be disabled by default and what would be worth showing may depend on location.

**Comment by mnalis** [comment]
> It appears than in USA distinguishing between brands of credit/debit cards may have dubious utility. 
> In Poland it definitely has zero utility.

Some countries do have a problem with some of the cards (see https://github.com/streetcomplete/StreetComplete/issues/3219), but still, I do support this more coarse quest (there can always be followup quest for details, I guess). Or simply stay away from AmEx / Diners and one should be mostly safe :smile:

**Comment by 1ec5** [comment]
I’ll let the AmEx discussion play out in #3219. Some of the other payment types still sound like they would also be useful to collect, especially for smaller POIs like vending machines and perhaps for POIs in countries where electronic payments are more common. But the credit and debit question satisfies the highest priority in the U.S. for now.
