### ISSUE TITLE
What kind of entrance is this?

### ISSUE THREAD

**Issue by 1ec5** [streetcomplete/StreetComplete#2706]
### General
Affected tag(s) to be modified/added: [`entrance`](https://wiki.openstreetmap.org/wiki/Key:entrance)
Question asked: ~~**Who can use this building entrance?**~~ **What kind of entrance is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
    * More specific tags than `entrance=yes` would allow routers to route to the correct side of the building.
    * Some renderers like osm-carto distinguish `entrance=main` from other `entrance=*` values.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
    * This depends on whether armchair mappers have been mapping only the main entrances or all the entrances they can see from aerial imagery.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

`entrance=yes` that is one of multiple `entrance=*` nodes along a `building=*` way. Maybe require the building to cover enough area or filter out things like `building=garage` to avoid spamming the user about insignificant buildings.

**Metadata needed:** 

**Proposed GUI:**

Select one:

* Main entrance – `entrance=main`
* Side or back entrance – `entrance=secondary`
* Entrance for staff only – `entrance=service` `access=private`
* Entrance for deliveries only – `entrance=service` `access=delivery`
* Exit only – `entrance=exit`
* Emergency exit – `entrance=emergency`

**Comment by matkoniecz** [comment]
"Everyone (main entrance) – entrance=main" 

What about entrances to residential buildings where `entrance=staircase` may fit or houses where main one will be still private?

Or is it covered by " filter out things like building=garage to avoid spamming the user about insignificant buildings."?

**Comment by andrewharvey** [comment]
How about just "What type of entrance is this?" instead of trying to conflate entrance= and access=?

**Comment by 1ec5** [comment]
Yes, I was assuming that the quest could generally filter out buildings that only have private entrances. Even so, a house’s front door could still validly be `entrance=main` even as `access=private` would apply. So maybe the only problem is the wording. Would it be weird to ask, “Which of the building’s entrances is this?” and answer simply that it’s the main entrance?

**Comment by 1ec5** [comment]
I reworded the original post to focus on the “kind” of entrance rather than access, but I left in a distinction between staff-only and delivery-only entrances, in case that makes sense at enough POIs.

**Comment by mnalis** [comment]
@1ec5 Additionally note that wiki for [entrance=main](https://wiki.openstreetmap.org/wiki/Tag:entrance%3Dmain) specifically notes `This tag should only be used for the primary entrance to a publicly accessible building (like access=yes)` and that you should `Use a different value for private buildings and residences, such as yes, home, service, staircase`

**Comment by 1ec5** [comment]
Yes, it looks like that was later added to the wiki page without discussion even though it wasn’t part of [the approved proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/entrance), and there have been [discussions](https://wiki.openstreetmap.org/wiki/Talk:Key:entrance#definition_for_entrance.3Dhome_is_not_clear) about potentially deprecating that usage in favor of `entrance=main`.

Regardless, I think it would make sense for this quest to try to avoid private buildings and residences, since classifying entrances on those buildings is less commonly useful for navigation by the general public. Unfortunately, `building=yes` could be either public or private, but I think any of the following strategies would mitigate the problem:

* Only consider buildings that already have multiple entrances tagged as `entrance=yes`. These buildings are less likely to be private buildings and are more likely to need entrance classification.
* Only consider nonresidential `building=*` or `building:use=*` values.
* Only consider non-apartment buildings over a certain size (way area or length).
* Offer the user more options like “Home entrance” and “Garage door”.

**Comment by matkoniecz** [comment]
> Unfortunately, building=yes could be either public or private, but I think any of the following strategies would mitigate the problem:

Note that such buildings can be simply skipped, StreetComplete will ask used to classify `building=yes` objects.

**Comment by westnordost** [comment]
I am not sure if this can be made into a quest because of @matkoniecz 's first comment: Not all entrances (to residential buildings) are staircases, so in many cases, it is not possible to get more detailed than `entrance=yes`.

As an example, I took this picture today:
![36769](https://user-images.githubusercontent.com/4661658/114283835-2e4e2f80-9a4c-11eb-874d-21d6c8c8a296.jpg)
Sorry about the resolution. anyway, entrance 37 and 39 are clearly staircases, but 37a is just an entrance. (And left and right of that entrance, you actually see two more entrances but without a housenumber). For these entrances, it is not possible to get more detailed than `yes`.

**Comment by 1ec5** [comment]
> to residential buildings

What if the quest avoids residential buildings and `building=yes` (in case it’s residential)?

**Comment by westnordost** [comment]
Hm well, I could imagine a building similar to the one shown  but it's an office (or generic commercial) building. I mean, it is easy to see if something is a main entrance, it is easy to see if something is a staircase entrance. And then there is "other entrance", `entrance=yes`.

**Comment by westnordost** [comment]
For example this building:
![image](https://user-images.githubusercontent.com/4661658/114284580-2644be80-9a51-11eb-82a8-8ea65563d780.png)

https://www.google.de/maps/@53.585263,9.9534988,3a,60y,348.55h,87.92t/data=!3m6!1e1!3m4!1sEQ2gRX3u_aniJOfRnhQZhA!2e0!7i13312!8i6656

There are three (or four) entrances. I'd say that all three classify as "an" entrance. Neither of them is "main" nor a staircase.

**Comment by 1ec5** [comment]
In my opinion, “other entrance” would correspond to one of the other values, like [`entrance=secondary`](https://wiki.openstreetmap.org/wiki/Tag:entrance%3Dsecondary) or `entrance=service` (which could have distinct options). If we’re concerned that it may not be possible to distinguish between a secondary entrance and a service entrance, then even a simple “Is this the main entrance?” quest would still prove a benefit to navigation use cases.

**Comment by westnordost** [comment]
I'd also get away from `entrance=yes`, but the prerequisite for that is that for all kinds of possible entrance types, there is a corresponding tag. Can `entrance=secondary` be understood as "just another entrance"? I.e. in that picture above, would every entrance be tagged as secondary then?

**Comment by matkoniecz** [comment]
> would every entrance be tagged as secondary then?

That seems to be a logical conclusion, but it seems quite silly result.

 (BTW, behind the left tree trunk I think there is `entrance=garage` - though that is not making `entrance=secondary` less silly)

**Comment by 1ec5** [comment]
If each of the entrances (other than the garage) is of equal importance, wouldn’t they all be main entrances?

**Comment by westnordost** [comment]
Well, for the example image, we don't know how important each entrance is.
So in conclusion, main/secondary entrances only really make sense for (public) buildings where it is obvious. And this means, for the entrances in the photo, is is not so relevant (not public) and there is no tag that can be more precise than `entrance=yes`.

**Comment by matkoniecz** [comment]
What kind of entrance is here? (where no entrance is marked) #3941 is a new related idea

**Comment by deevroman** [comment]
Based on #3941. Indeed, we cannot change their type for all entrance=yes. But what if we filter out some of them? For example, select only entrance for `building=apartments/house/...` Or ask about entrance=yes if it doesn't have `access=*`

**Comment by matkoniecz** [comment]
@deevroman I suspect that some still will be `=yes` or not surveyable :(

>  Or ask about entrance=yes if it doesn't have access=*

That would require allowing to tag `access`, basically a new quest. I thought about it and have no good idea how to ask it in way that would gather relevant info (`entrance=staircase`) without turning into "yes, it is `access=private`" spam.

**Comment by mnalis** [comment]
(ref: there is discussion related to this on https://community.openstreetmap.org/t/entrance-staircase-issues-initially-was-new-tag-idea-entrance-unclassifiable-or-other-way-of-marking-that-entrance-yes-is-not-really-assignable-to-more-specific-entrance-categories/8894)

**Comment by matkoniecz** [comment]
Yeah, and it went nowhere as far as StreetComplete is concerned as there was no support for tagging that SC would need to make such quest viable.

There were some complaints about `entrance=staircase` but also not rising to the point where things need changing, I think (though maybe someone will make thread calling for its deprecation/avoidance...)
