### ISSUE TITLE
Use disused:shop instead of shop=vacant

### ISSUE THREAD

**Issue by scaidermern** [streetcomplete/StreetComplete#2707]
If a shop is closed StreetComplete removes all tags and adds [`shop=vacant`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvacant). This tag has become rather controversial, though. This place is no longer a shop, so it shouldn't get tagged as a shop. Also, every data consumer needs to add a special handling for `shop=vacant`, i.e. for excluding it when rendering shops. Therefore it would be better to use the [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) instead, i.e. `disused:shop=<former shop value>`.

**Comment by kmpoppe** [comment]
Additionally, the information what kind of shop it was doesn't get lost in the object's history but is still visible in the disused state. That might not be helpful for automatic data consumers but for a human contributor.

So: Am in agreement for `disused:shop=*`.

K

**Comment by matkoniecz** [comment]
I also would say that `disused:shop=yes` is preferred over `shop=vacant`

But note that SC cannot retag old value of shop, as user has no opportunity to confirm/reject that shop type remain match current `shop` value (shop could disappear, new of different type appear and disappear and then become resurveyed).

Though I would not say that `shop=vacant` is wrong/controversial. I just think that it is not the preferred variant.

BTW, I tried to find where it is applied to confirm that SC actually uses `shop=vacant` and at least Github search failed.

**Comment by scaidermern** [comment]
> BTW, I tried to find where it is applied to confirm that SC actually uses `shop=vacant` and at least Github search failed.

I noticed it in one of my own changesets, created with StreetComplete 30.1 about a month ago.

**Comment by kmpoppe** [comment]
@matkoniecz 
https://github.com/streetcomplete/StreetComplete/blob/a8973ae5c5b313315ddc15daa46567013de61971/app/src/main/java/de/westnordost/streetcomplete/quests/shop_type/ShopGoneDialog.kt#L69-L71

**Comment by scaidermern** [comment]
> On the points made:
> 
>     * that data consumers need to take special care regarding `shop=vacant` is a relatively weak point, as this tag has been around for a very long time and there is also `shop=no` (etc.)

While `shop=no` might be in use (currently 3k occurrences according to taginfo) I fail to see why this should be a valid tag. There is also no documentation at the Wiki.

>     * at the very least, StreetComplete should support (i.e. ask for) `disused:shop=*` too

I think it already does that. StreetComplete already asks if `disused:shop=*` is still vacant, if I recall correctly.

>     * `shop=vacant` is also used for non-shops. For example if there was a bakery before, `amenity=bakery` would turn into `shop=vacant`. Is this possible with the disused scheme as well?

Sure. `amenity=bakery` will become `disused:amenity=bakery`. See [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) in the OSM wiki for more details.

**Comment by westnordost** [comment]
> While shop=no might be in use (currently 3k occurrences according to taginfo) I fail to see why this should be a valid tag. There is also no documentation at the Wiki.

No idea why it exists. Maybe for something like `craft=*` where one would usually assume that it is (also) a shop but it isn't?

**Comment by matkoniecz** [comment]
> While shop=no might be in use (currently 3k occurrences according to taginfo) I fail to see why this should be a valid tag. There is also no documentation at the Wiki.

? See https://taginfo.openstreetmap.org/tags/shop=no#wiki that links to https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dno

(it is primarily used on `amenity=fuel` to indicate that it has no matching shop)

> Sorry, I did not understand this sentence.

There could be following sequence of events

- `shop=greengrocer` exists and becomes mapped in OSM
- `shop=greengrocer` is replaced by `shop=pets` - and OSM is not updated
- `shop=pets` gets closed and is now vacant - and OSM is not updated
- mapper with StreetComplete visits and marks `shop=greengrocer` as vacant - both `shop=vacant` and `disused:shop=yes` are correct, but `disused:shop=greengrocer` would be wrong (and even  `disused:shop=pets` could be wrong of all traces of that shop type are removed)

**Comment by scaidermern** [comment]
> > While shop=no might be in use (currently 3k occurrences according to taginfo) I fail to see why this should be a valid tag. There is also no documentation at the Wiki.
> 
> ? See https://taginfo.openstreetmap.org/tags/shop=no#wiki that links to https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dno
> 
> (it is primarily used on `amenity=fuel` to indicate that it has no matching shop)

You are correct, I failed to find this entry. However this wiki page states "Tag `shop=no` _was_ used [...]". It also doesn't get mentioned at the wiki page for [`amenity=fuel`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel).

**Comment by westnordost** [comment]
@matkoniecz Hm well, ok I think this is a rather minor problem though.

**Comment by scaidermern** [comment]
> There could be following sequence of events
> 
>     * `shop=greengrocer` exists and becomes mapped in OSM
> 
>     * `shop=greengrocer` is replaced by `shop=pets` - and OSM is not updated
> 
>     * `shop=pets` gets closed and is now vacant - and OSM is not updated
> 
>     * mapper with StreetComplete visits and marks `shop=greengrocer` as vacant - both `shop=vacant` and `disused:shop=yes` are correct, but `disused:shop=greengrocer` would be wrong (and even  `disused:shop=pets` could be wrong of all traces of that shop type are removed)

Well, `disused:shop=greengrocer` is a correct as `shop=greengrocer` has been while the shop actually was a pet shop. We don't introduce any new error with this scheme. The error is caused by wrong data in the first place. Wrong data doesn't automagically become correct data.

**Comment by kmpoppe** [comment]
While my original argument was, that I wanted to keep the original `shop=*` and just make it `disused:` I can somewhat follow @matkoniecz in that the state might not be correct in OSM anyway, so just disusing it wouldn't change much about that being incorrect in the first place.

What if we changed shop=vacant to disused:shop=yes? That value is used 4 times as often as the next value clothes and is also the first thing mentioned on the wiki page as the alternative?

**Comment by westnordost** [comment]
Streetcomplete doesn't usually "upgrade" tags as long as they are not deprecated.

On April 1, 2021 8:43:05 AM GMT+02:00, Kai Michael Poppe ***@***.***> wrote:
>While my original argument was, that I wanted to keep the original
>`shop=*` and just make it `disused:` I can somewhat follow @matkoniecz
>in that the state might not be correct in OSM anyway, so just disusing
>it wouldn't change much about that being incorrect in the first place.
>
>What if we changed shop=vacant to disused:shop=yes? That value is used
>4 times as often as the next value clothes and is also the first thing
>mentioned on the wiki page as the alternative?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2707#issuecomment-811684343

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rhhsm** [comment]
I think the difference between the two options is small and often irrelevant: maybe a vacant shop is more likely to be re-purposed again as a shop (it may have a "for rent" sign on it), while a disused shop is more likely to be on its way to become an abandoned shop? What is more important is that SC can handle new purposes of a vacant shop, which may be another shop, but also a craft, an amenity (bakery, restaurant), an office, a dentist, etc.

**Comment by andrewharvey** [comment]
> maybe a vacant shop is more likely to be re-purposed again as a shop (it may have a "for rent" sign on it), while a disused shop is more likely to be on its way to become an abandoned shop?

I use both tags shop=vacant and diused:shop=yes as meaning the exact same thing. The shop is empty currently but just needs a new tenant and fit out.

**Comment by matkoniecz** [comment]
> Well, disused:shop=greengrocer is a correct as shop=greengrocer has been while the shop actually was a pet shop. We don't introduce any new error with this scheme. The error is caused by wrong data in the first place. Wrong data doesn't automagically become correct data.

Yes, but `disused:shop=yes` avoids introducing this mistake, that cannot be caught by user.

> added the enhancement label 6 days ago

I guess that it means that if someone cares about it they can write a PR, I am doing it right now :)
