### ISSUE TITLE
Preference to use 12-hour AM/PM for opening hours instead of 24hr

### ISSUE THREAD

**Issue by wolfgang42** [streetcomplete/StreetComplete#2709]
**Use case**
When surveying in the US, shops invariably use AM and PM rather than 24-hour times. This introduces a bit of room for error when mentally converting times.

**Proposed Solution**

Make a preference (or use the system localization setting?) to display the times and time picker with AM/PM rather than 24-hour times.

**Related discussion**
This came up tangentially in https://github.com/streetcomplete/StreetComplete/issues/2702#issuecomment-810966366.

**Comment by westnordost** [comment]
Does the UI not use the AM/PM stuff automatically depending on the locale of the user?

**Comment by westnordost** [comment]
Mh no, it doesn't. The code is in `TimeRange.kt` function `timeOfDayToString` always uses 24-hours-format.

With this function, it could be checked:
https://developer.android.com/reference/android/text/format/DateFormat#is24HourFormat(android.content.Context)
