### ISSUE TITLE
Cannot open any quests

### ISSUE THREAD

**Issue by wolfgang42** [streetcomplete/StreetComplete#2711]
I have a Verizon QTAQTZ tablet, running Android 5.1.1, with StreetComplete 31.1 installed from F-Droid. On this device, I can't click on any of the quest markers, but everything else works—I can drag the map around, click on other UI elements, etc; just not open any quests. I have a phone with the same version of StreetComplete installed and working, so this is presumably some sort of device-specific bug. It's also been like this for more than a year now (I've just not bothered to report it), so it's not a recent regression in StreetComplete, either. 

Since this problem seems to be particular to my device, I'm happy to dig in with Android Studio and a debugger to figure out what the issue is; but as it's a pretty complex app I'm not sure where to start looking.

**Comment by peternewman** [comment]
Do notes do the same thing @wolfgang42 ?

What about if you tap the compass icon to try a different orientation (including 3D)?

I assume you've tried the obvious of uninstalling it completely and then putting it back on?

A screenshot might help someone to spot something different if you can get one easily?

**Comment by westnordost** [comment]
You can set a breakpoint in `QuestsMapFragment.kt` in the function `onSingleTapConfirmed` and then step through it. That is the place where the click is getting processed.

**Comment by wolfgang42** [comment]
> Do notes do the same thing?

Good thought, but yeah, I can't click them either.

> What about if you tap the compass icon to try a different orientation (including 3D)?

I didn't realize that was a thing you could do. However, it doesn't seem to make any difference.

> I assume you've tried the obvious of uninstalling it completely and then putting it back on?

Yeah, and also clearing the app's data and cache.

> A screenshot might help someone to spot something different if you can get one easily?

I can, but unfortunately it looks exactly the way you'd expect. I also tried turning on “Show layout bounds” but it seems like the map doesn't use them.

<hr/>

Now, on to debugging. I set a breakpoint here: https://github.com/streetcomplete/StreetComplete/blob/a8973ae5c5b313315ddc15daa46567013de61971/app/src/main/java/de/westnordost/streetcomplete/map/QuestsMapFragment.kt#L108 and confirmed that this function is being called, but it seems that `pickResult` is always `null`. I also tried investigating `pickLabel`, but quickly ran into `com.mapzen.tangram.NativeMap` and was unable to step any further. Seems like I'll probably need to dig into Tangram to figure out what might be going wrong, any hints for how to go about doing that? I've never done anything with native code on Android before.

**Comment by westnordost** [comment]
As I thought,  so it is an issue. You should passt this in the bugtracker of tangram-es and supply as much information about your device as possible.  It may help to try out one of their sample apps and see if you can reproduce the issue there. 

I can be of no assistance for debugging things in native code,  also never done that before. Maybe on tangram-es, there is a guide for that
