### ISSUE TITLE
Tag maxwidth:physical on specific barriers

### ISSUE THREAD

**Issue by ohrie** [streetcomplete/StreetComplete#2713]
### General
Affected tag(s) to be modified/added: [maxwidth:physical](https://wiki.openstreetmap.org/wiki/Key:maxwidth:physical)
Question asked: **What's the maximum width vehicles can pass here?**

If barriers like [bollards](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard) or [blocks](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dblock), standing in/on street it maybe could be impassable for some vehicles.

So the width between multiple barriers (if existing) or between the barrier and the edge of the way should be measured.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Width could be measured like discussed in https://github.com/streetcomplete/StreetComplete/issues/698. Since not everybody has a measuring tape with them.

### Ideas for implementation

**Element selection:** 
Every barrier mentioned above should be selectable. As they are available as points *and* ways, I would concentrate only on points since only those could be blocking way.

**Metadata needed:** 
No metadata necessary.

**Proposed GUI:**
A dialog where the user puts in the maxwidth in meter, for which one input field is necessary.

**Comment by westnordost** [comment]
Makes sense. So, asked for vertices of highways that are bollards, blocks etc.

But why maxwidth:physical and not simply maxwidth?

**Comment by ohrie** [comment]
The difference between [maxwidth](https://wiki.openstreetmap.org/wiki/Key:maxwidth) and [maxwidth:physical](https://wiki.openstreetmap.org/wiki/Key:maxwidth:physical) is, that the former is the "legal restriction" with a traffic sign. Where as barriers especially on foot-/cycleways don't have a sign like on streets for motor vehicles.

**Comment by matkoniecz** [comment]
If both are the same or there is no legal limit I would expect `maxwidth` to be fine. I would expect `maxwidth:physical` to be used in cases where it is larger than signed limit.

Note that https://wiki.openstreetmap.org/wiki/Key:maxwidth:physical usage is minimal.

**Comment by RubenKelevra** [comment]
@matkoniecz I don't see a reason why we should missuse the tag `maxwidth` which is clearly defined as legal restriction, not a physical instead of a tag which is defined to be exactly this kind of information were collecting: a maximum physical width.

Can you elaborate this further?

Usage is minimal since it requires an physical measurement which is more complex than adding a number from a sign.

**Comment by RubenKelevra** [comment]
> **Element selection:**
> Every barrier mentioned above should be selectable. As they are available as points _and_ ways, I would concentrate only on points since only those could be blocking way.

We should make sure that a point with this tag is also part of a way with an `highway=*` tag. Individual points are somewhat common for bollards etc.

And we probably also want to filter out `highway=*` ways which are tagged with `area=yes`. Example: https://www.openstreetmap.org/node/470997260

**Comment by westnordost** [comment]
Reading this again, it sounds a bit peculiar to tag `maxwidth` on `bollard` and `block` vertices of a way. But anyway, I guess it would be understood what it is supposed to mean.

However. Both are used to restrict motor vehicle traffic. I do not really see a useful use case to know exactly how broad a vehicle could be to still go around this barrier. Fire fighters will (usually) just be able to remove the bollard. All other vehicles who do not have a key to remove the bollard have no business beyond the bollard anyway.
Looking at the example image for bollards on the OSM wiki,
<a href="https://wiki.openstreetmap.org/wiki/File:Traffic_bollard_removable_with_key_on_a_footway.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Traffic_bollard_removable_with_key_on_a_footway.jpg/320px-Traffic_bollard_removable_with_key_on_a_footway.jpg"></a>
the question also arises which distance should exactly be measured? How far into the green should still be considered passable? Basically, in such cases, the user has to measure at least two distances: To the left and to the right of the bollard, to find the largest distance. For every bollard. There are a lot of bollards mapped and the usefulness of it is somewhat questionable. Hence, I am closing this as will not fix for that the following points of the quest guidelines are not well fulfilled:

- 🤷 Useful purpose
- 💤 No spam
- 🐿️ Easy answer

To record `maxwidth` on `traffic_calming=choker` (and similar) however has already been implemented. So at least this issue can be considered partly fixed, partly rejected.
Any other kind of barriers where asking for the max physical width is useful and not spammy can be added in the future.
