### ISSUE TITLE
Add surface to cycleways which are tagged as cycleway:right:surface or cycleway:left:surface

### ISSUE THREAD

**Issue by ohrie** [streetcomplete/StreetComplete#2714]
### General
Affected tag(s) to be modified/added: [cycleway:left:surface / cycleway:right:surface](https://wiki.openstreetmap.org/wiki/Key:cycleway:surface)
Question asked: **Which surface has the cycleway?**

Currently it's only possible to add the surface of a separate cycleway. Many cycleways are located on-street or some tracks are mapped not as extra way. So this would add the possibility to add the surface also on those types of cycleway.

If the cycleway has the same surface as street, this value should be adopted.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddCyclewayPartSurface.kt could be extended for handling also the right or left lane.

**Element selection:** 
```
way["cycleway:right"][!"cycleway:right:surface"]({{bbox}});
way["cycleway:left"][!"cycleway:left:surface"]({{bbox}});
```

**Proposed GUI:**
Analogous to the selection of cycleway type, first the correct side of the cycleway on the street should be select. Afterwards the existing surface dialog could be used.

**Comment by matkoniecz** [comment]
In areas familiar to me vast majority cycleway lanes would have exactly the same surface as road, so I would ask for ones that are a separate way tagged on the road `cycleway:both=track` and similar.

**Comment by DerDings** [comment]
Also think of sidewalk:(left|right|both):surface. It is also useful and probably only little extra work to implement it together with the cycle way surface quest requested here.

**Comment by arrival-spring** [comment]
n.b. comment in https://github.com/streetcomplete/StreetComplete/pull/3735#pullrequestreview-891355704

> Let's add this quest but let's not add any further detailing quests for street-sides for now.
