### ISSUE TITLE
Zoom level sometimes changes after bringing back SC to the foreground

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2715]
Hi there,

the zoom level I have set sometimes gets restored to a certain (default?) value after I switched to OsmAnd and back to SC. This behaviour is quite annoying, because there is always a reason a user zooms in or out; if the zoom level changes without the user's intention the user has to set it again. On the other hand it's sometimes useful or even necessary to temporarily switch from SC to another app in order to look up something and/or other tasks, in conjunction with OSM or something totally different.

<h3>How to Reproduce</h3>

**Variant 1:**

- Make sure that the GPS button in the lower right corner of the display **is not visible** (i. e. the map is tied to the GPS position).
- Zoom in or out.
- Switch to a different app. Any will do.
- Switch back to SC.

You'll notice that the zoom level has changed (restored to the default value?)

**Variant 2:**

- Make sure that the GPS button in the lower right corner of the display **is visible** (i. e. the map is _not_ tied to the GPS position).
- Zoom in or out.
- Switch to a different app. Any will do.
- Switch back to SC.

You'll notice that the zoom level is retained. (This is the behaviour the user would expect.) However:

- Tap on the GPS button.

You'll notice that the zoom level has changed.

I can reproduce both variants of this issue reliably.

<h3>Versions affected</h3>

Android 9.0
StreetComplete 31.1 (but I have been observing this for some months now, so this behaviour wasn't introduced with some recent SC version)

The cycling cat

**Comment by westnordost** [comment]
When the app goes into the background, the app stops tracking the GPS position.

Each time the app comes into foreground, the app starts tracking the GPS position. 
When it starts tracking the position, indeed, it zooms to zoom 19 once.

This is not a bug but simply the current behavior.

If I remember correctly, it was implemented so that if you press the GPS button (and the location is found), it will zoom to your position - not only X,Y but also Z.

**Comment by westnordost** [comment]
I am working at these classes anyway right now. I will change it so that it will only zoom to 19 the first time (per creation of the map view) the GPS location becomes known

**Comment by cyclingcat** [comment]
Okay, this explains both variants. But:

> When it starts tracking the position, indeed, it zooms to zoom 19 once.

Would it be an idea always to save the zoom level when the app goes into the background and restore it after it comes to the foreground again (instead setting the zoom level to the fixed value of 19)?

The cycling cat

**Comment by westnordost** [comment]
Nothing needs to be restored, this is the default behavior. Zooming to 19 is specifically overriding this "default" whenever GPS tracking started + the first location was reported back by the Android system.

**Comment by cyclingcat** [comment]
Obviously typed simultaneously :smile_cat: Feel free to close this issue if you don't need it as a reminder.

The cycling cat
