### ISSUE TITLE
'What can be left for recycle?' quest not showing up anymore

### ISSUE THREAD

**Issue by Mr-Mime** [streetcomplete/StreetComplete#2717]
The mentioned quest seems buggy to me.
Nearby are some [nodes](https://www.openstreetmap.org/node/8528580235) tagged as `amenity=recycling, recycling_type=container`, which **do not show** up in the app.  

I created a new [node](https://www.openstreetmap.org/node/8587320117) tagged with `amenity=recycling`, solved the 'What type?' quest with `container`.  
This one is now tagged as `amenity=recycling, recycling_type=container, location=overground` and **is shown** in SC for the 'What can be left?' quest.

So for me the only difference is the `location` tag.

I took a quick look at the code and the filter but am not experienced and familiar enough to find anything.
However if I can help out somehow, let me know.

**Versions affected**
Android 9: SC v31.3
Andorid 10: SC v25.1 (checked this one because I thought maybe it has something to do with the new way of loading introduced by SC v26)

**Comment by Helium314** [comment]
I think recycling containers need to be at least 20m (or something like this) away from other recycling containers to be eligible for the quest.
When they are too close together you can't know for which one you anwer the quest, or whether there is another one at all.

**Comment by matkoniecz** [comment]
And in general groups of containers are usually much better representable by a single node with all info about available materials.

Splitting it into separate nodes is not really helpful for any conceivable use.

**Comment by matkoniecz** [comment]
Closing as it is deliberate: see https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt#L46

```
 /* Also, exclude recycling containers right next to another because the user can't know if
         * certain materials are already recycled in that other container */
        val containerPositions = LatLonRaster(bbox, 0.0005)
```
