### ISSUE TITLE
add answer "Does not exist anymore" to the building type quest.

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2719]
Suggestion to add a "Does not exist anymore" answer to the building type quest to mark buildings that did exist but are now demolished/razed buildings. I realise this would only capture a small group of buildings that were still building=yes and demolished before anyone tagged the building type, but it does happen.

Ideally these would be tagged as demolished:building=yes or razed:building=yes or removed:building=yes so that armchair mappers looking at imagery which has the building can see a surveyor has checked it as no longer there.

**Comment by ygra** [comment]
You can just say »cannot answer this« and leave a note, I guess. It's not like building disappearing is _that_ frequent compared to the alternatives.

**Comment by andrewharvey** [comment]
> You can just say »cannot answer this« and leave a note, I guess. It's not like building disappearing is that frequent compared to the alternatives.

Yeah I realise that, but I feel it's better to have an answer there as it get's automatically tagged and easier than addressing notes later.

Now that I know "Cannot answer" just leaves a note it's okay, but before this I'd often not choose that because I can answer it, it's just the answer is "Something else". So I feel two options "Cannot answer" and "Something else" would be better. But this is off-topic here.

**Comment by westnordost** [comment]
Yes, in this case it is better to leave a note. It was kind of deliberate to exclude "larger" things from direct deletion.

Moreover, currently, it is only possible to remove POIs (that is: `node`s), not ways, not relations. 

Removing these is more complex, as usually if you remove a building, you also want all the vertices of that building removed, too. But only those vertices that are not used by any other way. Also, if the building is a multipolygon relation (yes, they appear as quests in StreetComplete too), then it is even more complex: All elements of that relation should (probably) also be removed, including their nodes, except if they are referenced by anything else.

So of course, this could be implemented, and it would not be **too** hard, but leaving note in this case is really equally good or better than deleting it directly.

**Comment by andrewharvey** [comment]
> Removing these is more complex, as usually if you remove a building, you also want all the vertices of that building removed, too. But only those vertices that are not used by any other way. Also, if the building is a multipolygon relation (yes, they appear as quests in StreetComplete too), then it is even more complex: All members of that relation should (probably) also be removed, including their nodes, except if they are referenced by anything else (other ways, other relations)

Another reason for just retagging as razed:building=*, better for OSM mappers, easier for SC.

**Comment by kmpoppe** [comment]
With this coming up in #3823 again, wouldn't it be worth an other answer "does not exist anymore" and then either show a message box explaining what to do (leave a note) much like the "No cycleway at all" answer in AddCycleway _and/or_ allow the user to directly forward to a note window with the text "This building seems to no longer exist" pre filled?

**Comment by smichel17** [comment]
It seems silly to me to show a message box explaining what to do, when we could have that option open the note dialog directly, maybe with some text pre-filled.
