### ISSUE TITLE
Add "lit=limited" answer option to the quest "Is this way lit?"

### ISSUE THREAD

**Issue by wielandb** [streetcomplete/StreetComplete#2721]
In germany at least, every street lantern has to be on all night long, except if it is marked with street sign Number 394, a red stripe with white edges. So, regardless of when someone encounters a street(light), it is possible to tell if this light will be on the whole night or only partially. [According to the german wiki](https://wiki.openstreetmap.org/wiki/DE:Key:lit), those streets can be tagged with `lit=limited`.

**Problem:** It is not possible to give an answer in StreetComplete that will add the tag `lit=limited` to a way.

**Proposed solution:** Add another value to the "more options" menu, the one that already contains the options for `lit=automatic` and `lit=24/7`, that says something like "yes, but not all night".

I thought about the potential problem concerning the Quest-Guideline _"👨‍💻 Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary"_, as I think it is probable most people will not have this knowledge and most people will tag a road where `lit=limited` is appropriate with `lit=yes`. But I don't think it's a real problem that should prevent implementation, because the `lit=24/7` answer option is also affected by this potential problem. If I come across a lit way at night that is lit 24/4, I may just answer `yes` because I don't know that `24/7` would be more appropriate. 
So for `limited`, as for `24/7`, some kind of background or local knowledge is needed, but if it is tagged with `yes` instead it's not a big problem as it is okay to tag things with `yes`, even if a more special value would be appropriate.

**Comment by matkoniecz** [comment]
see https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+lit%3Dlimited+is%3Aclosed+ and more specifically #430

**Comment by wielandb** [comment]
I tried presenting my arguments why this should be included as an option, not as for example a rephrasation of the whole quest. 

My train of thought is that if `24/7` is okay to be added as an answer in SC it's probably also okay to add `limited` as well, as all counter arguments against adding `limited` also apply for `24/7`, but `24/7` is implemented in SC. 

When I am encountering a way with red rings, I currently always have to leave a Note (mostly for myself), so that I later add the tag in an editor myself later. I think that is unnessecarily complicated. I know that a "complete rephrasation", possibly including a confirmation dialog like in #430 , would be very much work to account for some flimsy StVO-quirk. I just would apprechiate a way for someone who _knows_ that this is the appropriate tag to add it via SC. Everyone who doesn't just answers `yes`, which is also completely fine.

**Comment by westnordost** [comment]
> But I don't think it's a real problem that should prevent implementation, because the lit=24/7 answer option is also affected by this potential problem.

This would be a reason to remove the 24/7, not a reason to include the `limited` option - otherwise that'd be whataboutism.
But in any case, `24/7` is less problematic than `limited` because anyone can see it who is not an expert while `limited` needs explanation and is problematic anyway, as described in detail in the linked ticket.

**Comment by wielandb** [comment]
Okay, fair point. 
I knew from the start that implementing this would pose a challenge, but I thought I'd give it a shot with my simplified proposal.
I guess I'll close the issue then.
