### ISSUE TITLE
maxspeed:type=FX:* in France (F*X* <> F*R*)

### ISSUE THREAD

**Issue by Marc-marc-marc** [streetcomplete/StreetComplete#2725]
https://www.openstreetmap.org/way/147585879/history
taginfo show more than 2800 maxspeed:type=FX:* in France métropolitan
https://taginfo.openstreetmap.fr/keys/maxspeed:type#values search FX:
https://taginfo.openstreetmap.org/tags/maxspeed%3Atype=FX%3Aurban#chronology
https://overpass-turbo.eu/s/15WG

**How to Reproduce**
I have no idea if the bug needs something specific to happen.
If necessary, I will write to the concerned contributor to get more information.

**Versions affected**
28.1 at least

**Comment by westnordost** [comment]
What is the issue?

**Comment by peternewman** [comment]
I'd assume @Marc-marc-marc is questioning why it's being tagged with FX not FR.

ISO seems to say FR should be used:
https://www.iso.org/obp/ui#iso:code:3166:FX

**Comment by Marc-marc-marc** [comment]
yes it should be FR for France
this was probably correct before, see the history graph which indicates a recent change

**Comment by westnordost** [comment]
Nothing changed in that manner in StreetComplete.

StreetComplete is using the CountryBoundaries library which uses a serialized version of this file from JOSM: 
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/boundaries.osm

In this file, the metropolitan France area polygon is added.

Maybe if FX is not recommended, that polygon should be removed from that file. However, I don't read this from the linked document.

**Comment by Marc-marc-marc** [comment]
thanks for the fix.
I started the mass editing procedure to correct objects in the database

**Comment by westnordost** [comment]
Thank you! though, better to defer this until after a new version has been released with this change.
