### ISSUE TITLE
Check for existence of grit bins

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2726]
Grit bins can be removed or moved, so their existence should be checked for every few years.

There are 19000 objects tagged as `amenity=grit_bin`, so plenty of them to check.

**Comment by matkoniecz** [comment]
`amenity=grit_bin` is in iD presets - so it is not blocked like #2679

As far as I see it makes sense

**Comment by westnordost** [comment]
Makes sense, yeah.

**Comment by matkoniecz** [comment]
implemented by @arrival-spring - thanks!

**Comment by georg-d** [comment]
Dear all, does the quest design consider that many grit bins are only visible during winter time but collected & stored centrally during the summer time? In other words, do we avoid the situation that people are asked "does it still exist?" during summer time  and correctly answer "no" but the grit bin is added again few months laterby some mapper?

**Comment by matkoniecz** [comment]
@georg-d Not at all. How such grit bins are marked as present seasonally? With `seasonal=yes` or other value of `seasonal` tag? (it would be possible to exclude grit bins tagged as seasonal)

(if it is not indicated at all, I would consider this to be quite problematic way of tagging)

**Comment by georg-d** [comment]
@matkoniecz https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrit_bin does not suggest any tags concerning season. But as these features are obviously only required in cold time, personally, I never even thought of marking them explicitly as seasonal - it seemed like explicitly telling plant pots may be moved to the inside during winter, or equipment of open air bathing areas (volley ball nets, pontons for swimmers,...). 

Back to the quest: Would it be difficult to show the quest only during "winter time" of current position/region? If no, that would be an effective solution. Alternatively, we may simply refine the wording, e.g. extending to "Does it still exist? (grit bin) Note: May be present only in cold season."

**Comment by westnordost** [comment]
Yes, it would not be trivial. Then maybe remove checking for the existence of grit bins again.

**Comment by matkoniecz** [comment]
I posted https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dgrit_bin#Marking_grit_bins_placed_only_during_winter.3F and will commit removal of grit bin checks :(

**Comment by peternewman** [comment]
It's not worth doing this by country is it? In the UK (or at least England) they are present 365 days of the year.

**Comment by matkoniecz** [comment]
Probably no.

**Comment by georg-d** [comment]
Before removal of the quest: What about just re-wording it like in my last comment? i.e. make the human aware and let user decide whether grit bin seems permanently removed or just temporarily. If human is in doubt (e.g. during warm season), he/she will simply ignore the question and someone will see the very same quest some months later during winter when it's obvious.

**Comment by westnordost** [comment]
Problem is, what should the user answer if he does not see a grit bin in the summer then?

**Comment by georg-d** [comment]
Similar as for "is this street lit?" quest at daytime: If I cannot tell the aswer for sure at the moment, I simply close the quest and someone (maybe myself) will pick it again later when a solid answer is possible.

**Comment by westnordost** [comment]
But the street lanterns are not removed during the day

**Comment by westnordost** [comment]
In other words, you can still answer it, but just less conveniently so

**Comment by georg-d** [comment]
You're correct, the latern is not removed. But the quest is not whether a certain latern exists, but whether a feature is lit - and that makes quite a difference: At day time, I _can often not tell "sufficiently reliably"_ where the latern's light shines to (angel of light emittance and shades by houses/trees/embarkments/...) and sometimes I can't even predict whether a latern is still in use at all (is it in working state? switched on?). Hence, I quit/skip maybe a quater of "is this feature lit?" instead of just doing rough guessing .

**Comment by matkoniecz** [comment]
Note "Consider enabling "Is lit" quest only during night enhancement" #1285

Also there is a difference between being forced to make educated guesses (often quite reliable) and requiring a clairvoyance/extreme knowledge of a given area.
