### ISSUE TITLE
Disable AddProhibitedForPedestrians quest in Sweden

### ISSUE THREAD

**Issue by riiga** [streetcomplete/StreetComplete#2729]
As outlined in the previous issue I opened (#2472), having this quest enabled leads to users adding `foot=no` to lots of roads you are *legally* allowed to walk on in Sweden. In general, signs forbidding pedestrian entry are very uncommon here and private road owners can't ban pedestrian traffic. I suggest the quest be disabled for all users contributing with StreetComplete in Sweden as it adds very little benefit and is more likely to lead to bad data than actually improve it.

**Comment by matkoniecz** [comment]
Some quests are disabled in some countries, because of consensus of local community was that they do not want them (for example address collection in France).

Is there a broad support among Swedish mappers that this quest should be completely disabled? Can you link for example mailing list thread?

Some quests got additional filtering as result of such discussion that hopefully allowed to resolve problematic part (like cycleway surface quest in Netherlands).

**Comment by riiga** [comment]
I haven't asked on any mailing lists yet, but I will ask on IRC.

**Comment by matkoniecz** [comment]
Checking first on IRC may be a good idea, but ideally it would be something linkable.

This way once year later there is an issue "please enable AddProhibitedForPedestrians in Sweden" it is possible to link something as an explanation.

(also, maybe problem can be resolved without full disablement)

**Comment by westnordost** [comment]
> In general, signs forbidding pedestrian entry are very uncommon

Yes, they are very uncommon everywhere. The app clearly asks if it is explicitly forbidden, not if it is not safe to walk there. And it only asks if there is no sidewalk and the speed limit indicates that it is clearly outside of a residential area.

**Comment by riiga** [comment]
Then I guess we're back to the issue I previously opened in January: If the app asks for forbidden but users keep adding it, it's clearly a problematic quest and the question is not clear enough.

**Comment by westnordost** [comment]
Maybe it is a translation issue? Did you look at how the quest looks like in Swedish?

**Comment by matkoniecz** [comment]
@riiga Have you checked is Swedish translation causing problems here?

**Comment by matkoniecz** [comment]
Closing as inactive, can be reopened. 

Please comment if translation was verified (if you are unable to check it, I can find current Swedish translation though I am unable to judge it).

If translation is OK and Swedish community reached consensus that this quest should be disabled there - please link the discussion.

**Comment by riiga** [comment]
@matkoniecz Yes, I think the translation is problematic. I've joined the translation project (after seeing your call for it in the OSM World Discord) and updated the text to read (in translation) "Is there a signed prohibition [for pedestrians] to walk on this road?" which should probably help with it. I think it's probably fine to keep the quest with that updated translation.

**Comment by matkoniecz** [comment]
@riiga Thank you for fixing root of the problem! Hopefully the problem will disappear once translation is updated.

**Comment by rskedgell** [comment]
It's nice to know that it could be resolved for Sweden without resorting to whatiffery about mandatory sidewalk use and obstruction.

In the UK, it results in roads having foot=no where no prohibition exists when the user doesn't understand the question. Where the user does understand and answers truthfully, we get undesirable foot=yes on highway segments in the middle of junctions.

I'll be checking where foot=no has been added by SC near me and when (if?) I come across a correct use, I'll add a traffic_sign=GB625.1 + foot=no node at the sign position and source:foot=sign to the affected way(s). The rest will need a lot of tedious checking of streetside imagery and discussion via changeset comments before they can be removed.
