### ISSUE TITLE
Switch to using released NSI rather than the latest commit branch?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2731]
@bhousel about NSI use in https://github.com/streetcomplete/StreetComplete/blob/master/buildSrc/src/main/java/UpdateNsiPresetsTask.kt :

> Also - it makes me nervous when people just pull a file off our main branch.
> NSI publishes releases so downstream projects don't need to worry about breakage.
>
> More info here:
> https://github.com/osmlab/name-suggestion-index/wiki/Downloading-the-Data
>
> They should probably fetch the latest stable presets with a semver-range URL like:
> https://cdn.jsdelivr.net/npm/name-suggestion-index@5/dist/presets/nsi-id-presets.min.json

Likely it would require just changing URL in https://github.com/streetcomplete/StreetComplete/blob/master/buildSrc/src/main/java/UpdateNsiPresetsTask.kt + testing, posting as issue so it will not be forgotten

**Comment by westnordost** [comment]
Yes, that would suffice and yes, I agree.

**Comment by matkoniecz** [comment]
Done by #2733

Thanks to @UKChris-osm (hint: you can have "fixes #2733" in commit - on merge GitHub will automatically close the issue)
