### ISSUE TITLE
Quest: How many solar panel modules does this generator have

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2735]
### General
Affected tag(s) to be modified/added: [generator:solar:modules](https://wiki.openstreetmap.org/wiki/Key%3Agenerator%3Asolar%3Amodules)
Question asked: **How many solar panel modules does this generator have?**
(That doesn't scan very well, but something like that)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
Over 72000 uses of `generator:solar:modules`, although I can't find that it was voted on.
"Tagging the number of modules is helpful for estimating the power output of a solar installation." (from the wiki).
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
Unless it's on top of a tall building, or is a very large solar farm. Things mapped as nodes should definitely be surveyable, 'small' areas should be too, but not sure if that can easily be selected, or how small 'small' should be.
If it's just on top of a one or two storey house then it's usually easy to count the modules when on the road next to the house.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
Over 780000 objects tagged with `generator:type=solar_photovoltaic_panel`, 353000 are nodes.

**Element selection:** 
Nodes (and areas?) with `power=generator` and `generator:type=solar_photovoltaic_panel` and without `generator:solar:modules` already.

**Metadata needed:** 
I don't expect this will be different in different countries.

**Proposed GUI:**
Simple numeric input, similar to the number of bikes or number of steps quests.

**Comment by matkoniecz** [comment]
I am not sure why it is useful - and created https://wiki.openstreetmap.org/wiki/Talk:Key:generator:solar:modules#Why_it_is_useful.3F

**Comment by arrival-spring** [comment]
There are a few comments on there already, and it seems that it has some value.

[A link](https://wiki.openstreetmap.org/wiki/Renewable_energy_in_the_United_Kingdom/Rooftop_Solar_PV) from the UK quarterly project [Q3 2019](https://wiki.openstreetmap.org/wiki/UK_2019_Q3_Project:_Solar_Power) gives more details on how to map rooftop solar, and mentions this tag.
Key bit: "In most cases you won't know the power output it gives, but it might be useful to record the number of modules, or the estimated area (see below). Both of these make it possible for data users to make a heuristic estimate of the power."
And then also puts this tag into a section "A couple of extra tags that have been deemed not-too-important".
So seems to be a bit double minded.

Maybe we should not tag this if `generator:output:electricity` has a value other than `yes` or `small_installation` (the first and second most used values), or maybe try to test if `generator:output:electricity` is actually a number with units, and not tag the number of modules in that case.

**Comment by matkoniecz** [comment]
Yes, it seems to be at least potentially. Not sure about "Easily answerable by everyone from the outside but a survey is necessary" - I worry that decent part of them will not be visible from the ground at all.

**Comment by arrival-spring** [comment]
Yes, quite a few are, but also a good number aren't.
I guess it depends on whether it's on the side of the roof facing the road, the roof shape and how tall the building is. But those aren't really things that would be easy to filter by.

**Comment by arrival-spring** [comment]
I had a look at some solar panels on houses near me today and found that it was mostly easy to count the number of modules.

I'd almost suggest that the quest could be disabled by default, as it's a slightly more advanced quest, and it's more likely to get some things which can't easily be answered. However I feel like I've seen in another issue at some point that that sort of thing isn't meant to be a reason for disabling quests by default.

**Comment by westnordost** [comment]
I think this kind of information (anything on solar panels) should rather be collected using aerial imagery.

**Comment by arrival-spring** [comment]
Ok, aerial imagery isn't always good enough to see the details and for residential rooftop solar I thought this would be good to capture on the ground, and would make for a suitable quest.

**Comment by westnordost** [comment]
The roof shape quest is already problematic because oftentimes you can't see it from the ground. Quests that ask for what's **on** the roof will be even more problematic. Sure, one can limit that to `building:levels=1` or `2` buildings but that doesn't solve the issue of solar panels that are for example on the south side of the roof but the public road is on the North side of the house.

Additionally, see @matkoniecz concerns. So, I'll close this.
