### ISSUE TITLE
Height limit asked for parking entrance connected to steps only

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2736]
The height limit quest is asked for [this node](https://www.openstreetmap.org/node/1328470254), which is connected to a highway=steps and nothing else.

According to the wiki "The differentiation between different kind of entrances for different kind of transportation modes (car, foot, …) is defined by setting the correct access tags (access=*)."
But I think the exclusive connection to steps (or: no connection to a road) should be sufficient for the entrance to be excluded from the height limit quest.

**Comment by matkoniecz** [comment]
Why? It seems to be a clear tagging mistake and may be worth reporting in seems Osmose.

It can be nonexisting - but it seems really rare and StreetComplete is allowed to show weird things in presence of wrong data.

It can be existing - in which case what is wrong with asking it?

--------------------

Or is it a pedestrian entrance into a parking? What seems very unusual and wrong tagging, even if OSM Wiki is technically not considering it as invalid.

**Comment by Helium314** [comment]
> Or is it a pedestrian entrance into a parking? What seems very unusual and wrong tagging, even if OSM Wiki is technically not considering it as invalid.

Yes it is.
Why is it wrong tagging? From the quoted part of the wiki I understand that also a foot entrance to the parking should be tagged with `amenity=parking_entrance`

**Comment by HolgerJeromin** [comment]
I don't like it, but it seems every entrance to a parking building should get this tag according to the wiki.
And at the footway exit a `max_height` tag is not useful (even for drivers with are taller than 2 meters :-)

**Comment by westnordost** [comment]
Can you cite the part of the wiki that claims this? When was this added, by whom? Any reasons given why that tagging makes sense?

On April 12, 2021 9:02:19 AM GMT+02:00, Holger Jeromin ***@***.***> wrote:
>I don't like it, but it seems every entrance to a parking building
>should get this tag according to the wiki.
>And at the footway exit a `max_height` tag is not useful (even for
>drivers with are taller than 2 meters :-)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2736#issuecomment-817542815

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
>  Why is it wrong tagging? From the quoted part of the wiki I understand that also a foot entrance to the parking should be tagged with amenity=parking_entrance

In any tagging that I encountered so far it was always used for a car entrance.

Note that OSM Wiki is often wrong, incomplete and should not be treated as an absolute truth - I made thousands of wiki edits and there is still long list of pages that I know to be incomplete, wrong, misleading, inaccurate etc.

**Comment by HolgerJeromin** [comment]
> Can you cite the part of the wiki that claims this? When was this added, by whom? 

> The differentiation between different kind of entrances for different kind of transportation modes (car, foot, …) is defined by setting the correct access tags (access=*).

ref https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity=parking_entrance section "entering by foot"
Was in the wiki from the beginning.

> Any reasons given why that tagging makes sense?

Someone can be happy to find all foot entrances to find his car again. Perhaps a big department_store has 10 entrances but the multistorage parking in the same building has only one.

**Comment by Helium314** [comment]
Interestingly I just noticed that the wiki entry and the node I liked above were created by the same user....

It seems weird to me that something that has been in the wiki for almost 10 years has been wrong all the time (why actually?) without even any discussion in the wiki.

**Comment by Helium314** [comment]
> ref https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity=parking_entrance section "entering by foot"
> Was in the wiki from the beginning.

Not just the talk page, also the line from the wiki entry
> The differentiation between different kind of entrances for different kind of transportation modes (car, foot, …) is defined by setting the correct access tags (access=*).

makes it clear that foot entrances can (should?) be tagged with `amenity=parking_entrance`

**Comment by westnordost** [comment]
hmm, how would a "foot-only" (or foot+bicycle+etc) entrance to a parking be tagged with access?

**Comment by Helium314** [comment]
As far as I understand:
(motor_)vehicle=no
or access=no and foot=yes

But since highway=footway and highway=steps have do not allow vehicles as per default restriction, an exclusive connection to such a way implies foot-only anyway, and thus does not have to be tagged explicitely. (like the node linked in first post)

Anyway, it might be relevant to see how many uses this actually has.
For the case with (motor_)vehicle=no or access=no and foot=yes I only found 291 nodes.
For parking entrances not connected to road for motor vehicles (steps, foot path, path) I have no idea how to seach.

**Comment by DerDings** [comment]
> For parking entrances not connected to road for motor vehicles (steps, foot path, path) I have no idea how to seach.

I wrote an overpass query:
https://overpass-turbo.eu/s/16dt

**Comment by Helium314** [comment]
> https://overpass-turbo.eu/s/16du

This is great, thank you! So it's more than 1000 nodes in Germany alone, much more than the 291 I found.
Restricting to [parking~"^underground|multi-storey$"] (as StreetComplete does) removes roughly half of the nodes, but more than enough remain.

So I think it would be ok to ask only for parking entrances connected to highways that are not path|footway|cycleway|steps|corridor (from @DerDings' overpass query), and simply not care about access (foot-only entrance connected to a road seems unlikely).
