### ISSUE TITLE
support more specific values of tactile paving

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#2738]
**Use case**

In the wiki there are currently five values documented for [Key:tactile_paving](https://wiki.openstreetmap.org/wiki/Key:tactile_paving): `yes`, `no`, `contrasted`, `primitive`, `incorrect`. 
To visually impaired people, `tactile_paving=contrasted` is about as important as `tactile_paving=yes` is important to fully blind people who use a white cane. 
`tactile_paving=incorrect` can warn data users that they need to pay extra attention here, because the paving may lead them in the wrong direction.

However, Streetcomplete can currently only handle the most common, generic values `yes` and `no` for the sake of simplicity. This seems reasonable since not every user knows how tactile paving is done correctly (even pavers don't always know – one main reason why `tactile_paving=incorrect` is important). But some users may know the other possibilities, but cannot choose them.
Even worse, the tactile paving quest may delete one of the specific values and replace them by a generic one when doing a resurvey. So I think something should be done here.

**Simple Solution**
Simplest way to prevent the resurvey from removing the specific tags  `contrasted`, `primitive`, `incorrect` is to modify the element filter, like this for example:
exchange this
```
(
          !tactile_paving
          or tactile_paving = no and tactile_paving older today -4 years
          or tactile_paving older today -8 years
        )
```
by this
```
(
          !tactile_paving
          or tactile_paving = no|unknown and tactile_paving older today -4 years
          or tactile_paving = yes and tactile_paving older today -8 years
        )
```
I added `unknown` here because according to taginfo it's the third most used value with 3 522 occurrences. 

**Advanced Solution**
Implement all five documented values to SC. `yes` and `no` remain the only two options visible on the main screen, but 
_"Yes, it even has great contrast visually (⩾70%)"_ -> `contrasted` and  
_"Yes, but it is incorrect or incomplete"_ -> `incorrect`
are added to the "other answers" menu. Just for those who know the difference. `primitive` should not be included, because it is very subjective.
If a user doesn't see those additional options, or doesn't know how to use them, they can still add data in the same quality as it is currently done.
I don't think that any unknowing user will be confused by the new options. The current photos for this quest are general enough to make unknowing users just select _"yes"_ if there's any tactile paving present.

For resurvey, the form then needs to be modified. Instead of just asking the question again, it would need to ask "Is the tactile paving here still like this?" and show what is currently tagged underneath:
_"tactile paving is present"_ for `yes`
_"no or incomplete tactile paving"_ for `no`
_"contrasted tactile paving is present"_ for `contrasted`
_"yes, but it is incorrect or incomplete"_ for `incorrect`
_"not explicitly, but there are other tactual elements"_ for `primitive`
There are two phrases containing the word "incomplete", but I don't see a problem here because it's just the resurvey strings. A user will see the incomplete tactile paving and choose "yes, still this way".

The cycle way resurvey also uses this principle, so it's already known by the users.

**My Opinion**
Personally I like the advanced approach more, because I know *a lot* of places with incorrect tactile paving. But there's currently no handy way to tag this. They're *the* reason for me to stop, wait until SC has uploaded all it's changes, open Vespucci, download data, edit the feature manually, upload data in Vespucci, go back to SC, select the tactile paving quest, select "can't say..." -> "no, just hide".
Also I think that the first time users see one of the lesser common options, they may become sensitized to the needs of visually impaired people, and the effort that is put into making public space accessible. Consequently, becoming the next person to also have a look to the "other answers..." menu and contributing their part to make accessibility mapping even better.

**Comment by FloEdelmann** [comment]
Could it be made into a separate quest that turns `tactile_paving=yes` into one of the more specialized values? However, it should be easy for surveyors then.

**Comment by DerDings** [comment]
> 
> 
> Could it be made into a separate quest that turns `tactile_paving=yes` into one of the more specialized values?

I think this is not possible. There is no special tagging for correct, but non-contrasted tactile pavings, they just remain `tactile_paving=yes`. So unless something like `not:tactile_paving=contrasted` is established, not every answer would have its eqivalent tagging.

Also, the specific values are common and established (~3000 elements according to taginfo), but compared to `yes` and `no` they're still quite niche.

**Comment by DerDings** [comment]
I know this is affecting the [👨‍💻 Users are no experts](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#users) rule. But since it does not add a new quest, does not add anything to the screens shown by default on first survey, and only shows the new "expert" options on resurvey if someone explicitly tagged them before, I think it should be acceptable.
Additionaly, it heavily improves the [💵 Valuable Surveyors](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#users) point, because surveyors don't need to switch apps just to add one tag.

**Comment by peternewman** [comment]
> I know this is affecting the [man_technologist Users are no experts](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#users) rule.

> _"yes, but it is incorrect or incomplete"_ for `incorrect`

I'd suggest that filtering out `incorrect` from the resurvey quest may be the safest option. From reading the wiki, I don't think you can simplify what is incorrect about paving to a succinct overview, so if I'm presented with the question "Is the tactile paving here still like this?", how do I know if it's incorrect/incomplete or has been resolved by the council?

> _"not explicitly, but there are other tactual elements"_ for `primitive`

Probably similar for this (again unless you're going to be more explicit about what the other elements are.

Suggestion, you probably want tactile not tactual:
> _"not explicitly, but there are other tactual elements"_ for `primitive`

> _"Yes, it even has great contrast visually (⩾70%)"_ -> `contrasted`
Regarding this, the wiki isn't very clear, but my obvious question from life and the wiki pictures would be does the red terracotta colour count as 70% within grey/concrete, what about black/tarmac? Aside from it making the form a bit busier I wonder if you could potentially get more tagging of that directly and show it all the time, but with a hint it would certainly be fine to put in other answers IMHO.

**Comment by DerDings** [comment]
> Suggestion, you probably want tactile not tactual:
> 
> > _"not explicitly, but there are other tactual elements"_ for `primitive`
> 

Probably. Translations preferably should be done by native speakers anyway.
In German, we have two expressions for tactile elements: "taktile Elemente" (from latin "tactilis") and "tastbare Elemente". They both have the same meaning, but the former is commonly used to describe paving stones, buttons, etc. which are _designated_ to be tactile, while the latter is used in the broader meaning of "anything that can be groped".
It was probably a misconception to assume that "tactile elements" in English has the same connotation as in German, and people would immediately think of this common [ribbed paving](https://www.lintel-gruppe.de/sites/default/files/inline-images/Barriflex_Rippenplatte_0.png) stone.

**Comment by westnordost** [comment]
I guess what could be done is the solution you mentioned as the "easy solution", so that StreetComplete does not destroy more detailed data by asking again.
For actually offering that choice, rather not. See the arguments that came up in this discussion.

**Comment by DerDings** [comment]
@westnordost:
> I guess what could be done is the solution you mentioned as the "easy solution", so that StreetComplete does not destroy more detailed data by asking again.

@DerDings:
> **Simple Solution**
> Simplest way to prevent the resurvey from removing the specific tags `contrasted`, `primitive`, `incorrect` is to modify the element filter, like this for example:
> exchange this
> 
> ```
> (
>           !tactile_paving
>           or tactile_paving = no and tactile_paving older today -4 years
>           or tactile_paving older today -8 years
>         )
> ```
> 
> by this
> 
> ```
> (
>           !tactile_paving
>           or tactile_paving = no|unknown and tactile_paving older today -4 years
>           or tactile_paving = yes and tactile_paving older today -8 years
>         )
> ```
> 
> I added `unknown` here because according to taginfo it's the third most used value with 3 522 occurrences.

I just had the idea that the filter could be improved even more:

```
(
          !tactile_paving or tactile_paving=unknown
          or tactile_paving = no and tactile_paving older today -4 years
          or tactile_paving = yes and tactile_paving older today -8 years
        )
```
This way, `tactile_paving=unknown` is treated as if it was not set at all.

**Comment by Helium314** [comment]
> I'd suggest that filtering out incorrect from the resurvey quest may be the safest option. From reading the wiki, I don't think you can simplify what is incorrect about paving to a succinct overview, so if I'm presented with the question "Is the tactile paving here still like this?", how do I know if it's incorrect/incomplete or has been resolved by the council?

Since `incorrect` appears to be quite useful, there could be an answer _"yes, but only on one side of the crosswalk"_ to at least cover a common case of incorrect tactile pavings

**Comment by peternewman** [comment]
> Since `incorrect` appears to be quite useful, there could be an answer _"yes, but only on one side of the crosswalk"_ to at least cover a common case of incorrect tactile pavings

Yeah true, although then you still have the grey area where you've got a crossing with an island, but only tactile at the sides not on the island. If we've tagged it has having an island the partially sighted person presumably thinks they've just got to the island when they hit the first tactile paving.
