### ISSUE TITLE
Change barrier=yes on nodes into more specific values

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#2739]
### General
Affected tag(s) to be modified/added: [barrier](https://wiki.openstreetmap.org/wiki/Key:barrier)
Question asked: **What kind of barrier is here?**

The wiki says on [barrier=yes](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dyes) "Unspecific barrier value, it is always better to use more specific one if possible. Still, sometimes when mapping from aerial images or surveying something in distance it may be necessary to use it."

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
crucial for routing
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
armchair mappers may add barrier=yes. iD even adds this automatically if a user opens the "barriers" menu, but then doesn't choose a specific type.

### Ideas for implementation

**Element selection:** 
nodes with `barrier=yes|unknown`
Maybe even limit it to nodes which are part of a `highway` way, because they're the ones important for routing.

**Metadata needed:** 
Metadata is not necessary. But, like in the orchard quest, a pre-selection of common values would be nice. There are a lot of possible values. Data may be derived from current use of the tags. Is there a source to get such tag usage statistics per country? Or a way to create the statistics with a script?

**Proposed GUI:**
list/grid to select from. Either with symbols (like the building type quest) or with photos (like the crop quest). I don't know what is the better UI design.
On the wiki there are already photos for nearly all of the values.

Answers:
[bollard](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard)
[chain](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dchain)
[jersey barrier](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Djersey_barrier)
([kerb](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb)) is it imaginable that someone can see a kerb from aerial imagery but cannot determine that it is a kerb?
[log](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlog)
[rope](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Drope)

[block](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dblock)
([bump gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbump_gate))
([bus trap](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbus_trap))
[cattle grid](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcattle_grid)
[cycle barrier](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier)
[debris](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Ddebris)
[entrace](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dentrance)
[HEET](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfull-height_turnstile)
[gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate)
[sliding gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dsliding_gate)
[hampshire gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dhampshire_gate)
[height restrictor](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dheight_restrictor)
([horse stile](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dhorse_stile))
([kent carriage gap](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkent_carriage_gap)) UK-specific according to the wiki
[kissing gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkissing_gate)
[lift gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlift_gate)
([motorcycle barrier](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dmotorcycle_barrier))
[sally port](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dsally_port)
[spikes](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dspikes)
[stile](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dstile)
[sump buster](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dsump_buster)
([swing gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dswing_gate)) (isn't that just a gate?)
[turnstile](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dturnstile)
[wicket gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwicket_gate)

A similar quest was once suggested for ways (#2100). It wasn't followed up on because some linear barriers require a specific direction of the way. But this problem doesn't affect nodes, which this quest suggestion is about.

**Comment by matkoniecz** [comment]
Seems very promising to me, hopefully will not run into issues like #2100

From quick check in my relatively well mapped city there are some quest candidates.

Most of the work would go into curating list of values that need to be supported and locating representative images that will be clearly recognisable and looking well in the app.

**Comment by matkoniecz** [comment]
>  (kerb) is it imaginable that someone can see a kerb from aerial imagery but cannot determine that it is a kerb?

Maybe with right resolution some kind of line will be visible but meaning will be unclear?

>  (bump gate)

I will skip this one, it feels really rare. Though I started looking for a photo just in case ( https://discord.com/channels/413070382636072960/413070502580453387/831986113806860298 for start)

>  (kent carriage gap) UK-specific according to the wiki

Single use worldwide, definitely will be skipped

>  sally port

Seems very unlikely to be tagged `barrier=yes` - I will skip it

>  wicket gate

AFAIK it is tagged as `barrier=gate` anyway - likely StreetComplete will continue doing it this way

**Comment by matkoniecz** [comment]
Initial version: images will be DEFINITELY cropped (into squares?), recentered, exchanged to better.

But comments about selectable barriers and labels are welcome already.

![screen](https://user-images.githubusercontent.com/899988/114925681-b3ac5800-9e2f-11eb-8925-7de640f3effa.png)

**Comment by DerDings** [comment]
> 
> But comments about selection of shown barriers and labels are welcome already.

Looks great to me.
Some thoughts:

- I think it should be clarified when to choose chain/rope and when to choose bollard, if the chain/rope is spanned between bollards. Maybe it's enough to use photos for chain and rope which show it spanned between bollards?

- A simple entrance is not that obvious and people may select what is surrounding the entrance. Your wording "Passage through wall/fence/etc" is actually good, but people may overlook it. So I would put barrier=entrance always in first place, so this option cannot be missed.

This is what I think cold be misunderstood otherwise:

This is a _chain_, even if it's supported by bollards:
![](https://photoeverywhere.co.uk/britain/liverpool/mersey_waterfont.jpg)
This is an _entrance_, even if surrounded by chains:
![mersey_waterfont_entrance](https://user-images.githubusercontent.com/42044179/114931055-012bc380-9e36-11eb-80dd-ad9811099b8e.jpg)





upper image by [PhotoEverywhere.co.uk](http://www.photoeverywhere.co.uk), CC-BY 2.5
lower image is my own edit of the upper one.

**Comment by matkoniecz** [comment]
> I think it should be clarified when to choose chain/rope and when to choose bollard, if the chain/rope is spanned between bollards

I admit that I am not sure what is the recommended tagging here, probably either option is used

**Comment by DerDings** [comment]
> 
> 
> > I think it should be clarified when to choose chain/rope and when to choose bollard, if the chain/rope is spanned between bollards
> 
> I admit that I am not sure what is the recommended tagging here, probably either option is used

I would always tag the more restrictive type.
- A chain always implies chain limitations, regardless whether it's spanned between walls or supported by bollards. One would need to step over it, or even lift a bicycle over (if allowed).
- Bollards however are less limiting. They're only preventing access of broader vehicles, but leave enough space for bicycles (or even wheelchairs) for example. The wiki says on [Tag:barrier=bollard](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard): "By default access=no, foot=yes, bicycle=yes and similar are implied."

So tagging the less limiting `bollard=yes` in a place where there's a chain between them would cause routing issues.

**Comment by westnordost** [comment]
Hmm, that's a lot of choices. Couldn't the `stile` be squeezed into one option?

When choosing / curating the values, you should not only take into account the numbers on taginfo but weigh how likely it is that a `barrier=yes` is not specified in more detail. In particular:
- How likely is it for example that someone tagged an entrance within a barrier as `barrier=yes`? I'd say very very unlikely. This might be true for other values as well.
- Could there be other types of features that are additionally tagged with `barrier=yes` - as an attribute? Those need to be excluded from the filter

**Comment by matkoniecz** [comment]
> Hmm, that's a lot of choices. 

And I bet that 80%+ will be simply `barrier=gate` / `barrier=bollard` from top of the list, but including just that would be problematic.

> Couldn't the stile be squeezed into one option?

I would say no given how different they can be ( https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dstile#Stile_details ). 

Also, each selection is anyway tagged differently (`stile` tag).

> Could there be other types of features that are additionally tagged with barrier=yes - as an attribute? Those need to be excluded from the filter

I looked for them and have not found such cases on nodes (so far). But in such case it should be generally possible to anyway tag type of a barrier. Maybe I can try searching for nodes with `barrier=yes` and at least N tags to increase chance of finding something.

> How likely is it for example that someone tagged an entrance within a barrier as barrier=yes? I'd say very very unlikely. This might be true for other values as well.

I imagined that it may be result of path clearly going through a wall, but aerial image not allowing to decide is there a gate there or a gateless opening.

Though I have no good idea which values will be useful here, as `barrier=yes` on nodes seems very weird to use for me. I have some such location in my city, I am curious what is there. In the end I just put all common barrier values present on nodes.

**Comment by DerDings** [comment]
> - How likely is it for example that someone tagged an entrance within a barrier as `barrier=yes`? I'd say very very unlikely. This might be true for other values as well.

I already did this multiple times. If there is a gap in a wall or hedge, it is often not possible to determine whether there is a gate in this gap or not. The hedge or wall is casting a heavy shadow, while a gate made of wire would throw nearly no shadow and may be hard to see from aerial imagery.

If options need to be reduced, I would rather ditch the kerb. Kerbs are found along roads most times, and there they are discernible from context. 

However, in the situation below, there are both a bollard and a kerb. From aerial imagery it just looked like an entrance (there are hedges on both sides. Sadly, I don't have a larger picture of this situation). I often find situations like this, even in the Ruhr Area, where there are multiple excellent sources of aerial imagery available.
aerial imagery:
![_20210416_083458.JPG](https://user-images.githubusercontent.com/42044179/114981721-b4c0a200-9e8e-11eb-87c3-6380dab2fd80.JPG)
The shadow of the bollard is hardly visible. The kerb not at all.
reality:
![33425.jpg](https://user-images.githubusercontent.com/42044179/114981062-ad4cc900-9e8d-11eb-9caf-2a341cbbd97d.jpg)

.

> - Could there be other types of features that are additionally tagged with `barrier=yes` - as an attribute? Those need to be excluded from the filter

Nearly everything can be a barrier when placed right in the way. But what should be excluded here? An `amenity=bench backrest=no` ist still better to be determined as `barrier=block` instead of `barrier=yes`, because it has the same physical restrictional properties of a block, but is not as restrictive as a turnstile for example.
I think it is still better to find a proper value for `barrier=*` in this cases, even if the object also has additional properties.

**Comment by DerDings** [comment]
I see I mainly brought up @matkoniecz points here. I didn't see you already answered.

**Comment by matkoniecz** [comment]
> I already did this multiple times.

was very useful as I never (I think) used `barrier=yes` on nodes, so info from actual users of that tag was very useful
