### ISSUE TITLE
What sort of traffic calming is here? (for nodes, ways, areas tagged traffic_calming=yes)

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#2742]
### General
Affected tag(s) to be modified/added: [traffic_calming](https://wiki.openstreetmap.org/wiki/Key:traffic_calming)
Question asked: **What sort of traffic calming device is here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

There are currently around 14k nodes tagged as traffic_calming = yes: https://taginfo.openstreetmap.org/tags/traffic_calming=yes

### Ideas for implementation

Replace traffic_calming=yes with the common values from https://wiki.openstreetmap.org/wiki/Key:traffic_calming

**Comment by arrival-spring** [comment]
This would need some good pictures/diagrams to make clear the difference between things like bump, hump and cushion. The descriptions on the wiki makes it clear enough, but that's too much text to go in the app.

**Comment by westnordost** [comment]
But in general, this could work. As @arrival-spring said, will depend on the quality of the images / illustrations.

**Comment by rhhsm** [comment]
Would be good to also ask for zebra crossings if they are raised (traffic light-regulated ones should possibly be excluded).

**Comment by matkoniecz** [comment]
As nearly all the work here will be selecting value, finding good short descriptions (sometimes repeating OSM tag is not the best idea) and finding images.

If someone is irritated by manual image resizing - I am using https://github.com/matkoniecz/rescaling_for_android to avoid doing this manually.

**Comment by matkoniecz** [comment]
List of potential values like one in https://github.com/streetcomplete/StreetComplete/issues/2739#issue-856319828 may be a potential first step (and requires no coding).

Note that different values may apply to nodes/ways/areas.

**Comment by FloEdelmann** [comment]
[Most commonly used](https://taginfo.openstreetmap.org/keys/traffic_calming#values) (apart from `yes` and `no`):

<table>
  <tr>
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Traffic_calming_example.jpg"><img src="https://wiki.openstreetmap.org/w/images/thumb/1/15/Traffic_calming_example.jpg/120px-Traffic_calming_example.jpg"></a><br>
      <code>bump</code><br>
      (241k usages)
    <td>
      <a href="https://commons.wikimedia.org/wiki/File:Speed_hump_with_car.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Speed_hump_with_car.jpg/300px-Speed_hump_with_car.jpg" width="120"></a><br>
      <code>hump</code><br>
      (180k usages)
    <td>
      <a href="https://commons.wikimedia.org/wiki/File:N%C3%A1zovsk%C3%A1,_zv%C3%BD%C5%A1en%C3%BD_p%C5%99echod.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/N%C3%A1zovsk%C3%A1%2C_zv%C3%BD%C5%A1en%C3%BD_p%C5%99echod.jpg/320px-N%C3%A1zovsk%C3%A1%2C_zv%C3%BD%C5%A1en%C3%BD_p%C5%99echod.jpg" width="120"></a><br>
      <code>table</code><br>
      (113k usages)
  <tr>
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Trafficcalming-island.jpg"><img src="https://wiki.openstreetmap.org/w/images/thumb/3/30/Trafficcalming-island.jpg/120px-Trafficcalming-island.jpg"></a><br>
      <code>island</code><br>
      (69k usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Rubber_speed_cushions.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Rubber_speed_cushions.jpg/120px-Rubber_speed_cushions.jpg"></a><br>
      <code>cushion</code><br>
      (26k usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Ferry_Road,_Eastham,_Wirral_-_DSC03451.JPG"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Ferry_Road%2C_Eastham%2C_Wirral_-_DSC03451.JPG/120px-Ferry_Road%2C_Eastham%2C_Wirral_-_DSC03451.JPG"></a><br>
      <code>choker</code><br>
      (21k usages)
  <tr>
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:North_Luzon_Expressway_Rumble_Strips.jpg"><img src="https://wiki.openstreetmap.org/w/images/thumb/4/4a/North_Luzon_Expressway_Rumble_Strips.jpg/120px-North_Luzon_Expressway_Rumble_Strips.jpg"></a><br>
      <code>rumble_strip</code><br>
      (18k usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:One-lane_chicane_1.jpg"><img src="https://wiki.openstreetmap.org/w/images/thumb/4/4d/One-lane_chicane_1.jpg/120px-One-lane_chicane_1.jpg"></a><br>
      <code>chicane</code><br>
      (14k usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Traffic_calming-dip.jpg"><img src="https://wiki.openstreetmap.org/w/images/thumb/9/93/Traffic_calming-dip.jpg/120px-Traffic_calming-dip.jpg"></a><br>
      <code>dip</code><br>
      (4k usages)
</table>

Additional possible options:

<table>
  <tr>
    <td>
      <a href="https://commons.wikimedia.org/wiki/File:Wuppertal_-_Schwarzbach_05_ies.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Wuppertal_-_Schwarzbach_05_ies.jpg/320px-Wuppertal_-_Schwarzbach_05_ies.jpg" width="120"></a><br>
      <code>painted_island</code><br>
      (309 usages, no wiki entry)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Obecn%C3%AD.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Obecn%C3%AD.jpg/120px-Obecn%C3%AD.jpg"></a><br>
      <code>mini_bumps</code><br>
      (170 usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Traffic_calming_-_choked_table.png"><img src="https://wiki.openstreetmap.org/w/images/thumb/7/7e/Traffic_calming_-_choked_table.png/120px-Traffic_calming_-_choked_table.png"></a><br>
      <code>choked_table</code><br>
      (162 usages, bad image)
  <tr>
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Traffic_calming-double_dip.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Traffic_calming-double_dip.jpg/120px-Traffic_calming-double_dip.jpg"></a><br>
      <code>double_dip</code><br>
      (115 usages)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Traffic_calming_-_choked_island.png"><img src="https://wiki.openstreetmap.org/w/images/thumb/0/09/Traffic_calming_-_choked_island.png/120px-Traffic_calming_-_choked_island.png"></a><br>
      <code>choked_island</code><br>
      (37 usages, bad image)
    <td>
      <a href="https://wiki.openstreetmap.org/wiki/File:Actibump1.jpg"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Actibump1.jpg/120px-Actibump1.jpg"></a><br>
      <code>dynamic_bump</code><br>
      (19 usages)
</table>

The images are linked to their respective source. Please suggest better images if you have any!

**Comment by westnordost** [comment]
Is `island` really used that much on the road way? I've seen instances where someone drew a polygon and tagged it like that.

The photos are TBH all not that helpful in my opinion. there is too much else in the picture

**Comment by RubenKelevra** [comment]
I feel like there's one missing which is pretty common here in NRW, Germany in my area.

While the whole street is paved with asphalt, the intersection is paved with red paving stones. One this visual differentiate the intersection and also the rumbling from the paving stones avoid that people drive too fast.

Not sure if there's a tag for this. I mainly just used the surface tag so far for that.

Here's an example:

https://www.volksfreund.de/region/konz-saarburg-hochwald/rote-pflastersteine-an-der-kreuzung_aid-5522097

**Comment by RubenKelevra** [comment]
Also, it makes sense to completely disable this quest for the Nederlands as long as we have no feedback from mappers from the Netherlands if this makes sense. Reason being that the Nederlands have traffic calming built into their national guidelines for constructing roads. It's basically everywhere.

So maybe they map streets without any traffic calming rather than marking each traffic calming infrastructure which is put somewhere.

**Comment by matkoniecz** [comment]
> So maybe they map streets without any traffic calming rather than marking each traffic calming infrastructure which is put somewhere.

In such case it will not be asked ("for nodes, ways, areas tagged traffic_calming=yes").

Though if `traffic_calming=yes` is used on entire `highway=*` then such case should be likely excluded (not checked is such tagging used at all).

**Comment by peternewman** [comment]
> Would be good to also ask for zebra crossings if they are raised (traffic light-regulated ones should possibly be excluded).

There are at least some traffic light regulated ones with a raised crossing, there was even a sign informing you of such I spotted on a recent walk.

**Comment by matkoniecz** [comment]
Preliminary review:

From https://wiki.openstreetmap.org/wiki/Key:traffic_calming and https://taginfo.openstreetmap.org/keys/?key=traffic_calming#values


`bump` short bump
`hump` long bump 
`table` Table (flat in the middle)
`cushion` long bump, not blocking buses (too long description!)
`island` Island
`choker` Narrowed road
`chicane` Deliberate sharp curve(s)
`rumble_strip` Rumble strip

**Comment by smichel17** [comment]
Layperson chiming in: before this issue, while I was well aware of all of these structures individually, and that they belonged to a category of essentially "things to slow cars down for safety", I had no idea that the category was called [traffic calming](https://en.wikipedia.org/wiki/Traffic_calming).

I am not suggesting you avoid the term; I think it's a good learning opportunity. However, I do think that the question should be obvious without relying on people to know the term in advance.

**Comment by peternewman** [comment]
> While the whole street is paved with asphalt, the intersection is paved with red paving stones. One this visual differentiate the intersection and also the rumbling from the paving stones avoid that people drive too fast.

It's the same height as the main road surface then @RubenKelevra ? Those things are common in some parts of the UK, but they are also tables (i.e. the junction is at a raised height relative to the rest of the road).

> `bump` short bump
> `hump` long bump

They are/were nicknamed sleeping policemen in the UK, which may be a good way to differentiate between bump and hump (same size as a person lying down in the road).

> `cushion` long bump, not blocking buses (too long description!)

I think the key thing is they don't cover the entire width of the road/lane. I believe the theory is that any vehicle driving at the correct speed rides over them fairly impact free (compared to a bump/hump), but you need to be going relatively slow to line up with them to do so.

**Comment by arrival-spring** [comment]
> `cushion` long bump, not blocking buses (too long description!)

How about `cushion` long, narrow bump?

**Comment by matkoniecz** [comment]
> I believe the theory is that any vehicle driving at the correct speed rides over them fairly impact free (compared to a bump/hump), but you need to be going relatively slow to line up with them to do so.

Ones that I know are serious bump to any car smaller than large pickup truck (except single tracked ones that can go to side).

Not sure is it theory vs practice or Poland vs functional road design...

**Comment by westnordost** [comment]
> They are/were nicknamed sleeping policemen in the UK

And incorrupt policeman in India. Mostly just the short ones, IIRC.

Anyway, is it necessary to actually name them when we show pictures of them?

**Comment by matkoniecz** [comment]
One tricky part is that I will need speed bump and hump images that do not differ by construction type:

so either asphalt hump and bump (ideally also table)

or plastic bump and hump (ideally also table)

or paving stone hump and paving stone bump (ideally also table)

otherwise people WILL become confused and mark based on material, not geometry/type

Or maybe use icons? Something like

![480px-Speed_hump_(3000986949)](https://user-images.githubusercontent.com/899988/135154822-a0aace52-cb41-4e33-a311-95802eaec591.jpg)

**Comment by peternewman** [comment]
> Anyway, is it necessary to actually name them when we show pictures of them?

I thought the consensus had been that pictures would be a challenge to differentiate.

@matkoniecz I'm impressed they're constructing plastic tables and paving bumps near you! Most of the ones near me are asphalt for the smaller bits and paving for the larger stuff. I may be able to get some pictures of them and cushions at some point.

**Comment by westnordost** [comment]
Icon illustrations are probably not a good idea. Too abstract.

Am 29. September 2021 03:39:21 MESZ schrieb Peter Newman ***@***.***>:
>> Anyway, is it necessary to actually name them when we show pictures
>of them?
>
>I thought the consensus had been that pictures would be a challenge to
>differentiate.
>
***@***.*** I'm impressed they're constructing plastic tables and
>paving bumps near you! Most of the ones near me are asphalt for the
>smaller bits and paving for the larger stuff. I may be able to get some
>pictures of them and cushions at some point.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2742#issuecomment-929751163

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
Rumble strips candidates:

https://commons.wikimedia.org/wiki/File%3A2008%5F03%5F28%5F%2D%5FAltoona%5F%2D%5FPark%5FAve%5Fat%5FFrankstown%5FRd%2EJPG

https://commons.wikimedia.org/wiki/File%3AZebra%5Fzone%5Fat%5Firiomote%2Ejpg

https://commons.wikimedia.org/wiki/File%3ARumble%5Fstrips%5Fat%5Fthe%5Fparking%5Fof%5FIKEA%5Fin%5FW%C3%BCrzburg%2Ejpg

https://commons.wikimedia.org/wiki/Category:Rumble_strips

https://petscan.wmflabs.org/?edits%5Bbots%5D=both&edits%5Banons%5D=both&search_max_results=500&depth=100&project=wikimedia&language=commons&cb_labels_no_l=1&categories=Rumble%20strips&ns%5B6%5D=1&cb_labels_yes_l=1&since_rev0=&cb_labels_any_l=1&edits%5Bflagged%5D=both&interface_language=en&before=&doit=

**Comment by matkoniecz** [comment]
Chokers:

https://www.geograph.ie/photo/2371053
https://www.geograph.ie/photo/2350574
https://www.geograph.ie/photo/5063298
https://www.geograph.ie/photo/1930424

Islands:

https://www.geograph.ie/photo/3192155
https://www.geograph.ie/photo/2642333

cushion

https://www.geograph.org.uk/photo/6486906
