### ISSUE TITLE
Asking for addr:street if addr:housenumber has just been added

### ISSUE THREAD

**Issue by kmpoppe** [streetcomplete/StreetComplete#2743]
Hello everyone,

Ludwig Anten reports in https://t.me/OSM_de/53072, that he was asked for a `addr:housenumber` and for `building:levels` directly afterwards, even though he was expecting to be able to add `addr:street`.

While https://github.com/streetcomplete/StreetComplete/blob/9d8b615164700455a6762f2341fb7fa1523556ac/app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.kt#L137-L138 lists both quests directly after one another in the "Important data"-category, that didn't seem to happen.

The reason is simple: https://github.com/streetcomplete/StreetComplete/blob/9d8b615164700455a6762f2341fb7fa1523556ac/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddAddressStreet.kt#L24-L25 only applies, when `addr:housenumber` exists.

So obviously the AddAddressStreet Quest will not be included in the "first" filter - i.e. would only apply if you had answered the housenumber and then searched for new quests in the same place again.

If we want to keep the filter the same (which is okay-ish in my view), would there be a way to mark Quests (AddHousenumber) that will ask the app to re-evaluate the quests at the given position because a Quest was answered that is important to a filter of another quest (AddAddressStreet) ?

^Kai

**Comment by TurnrDev** [comment]
I think quests for any given object should be re-evaluated as soon as a question is answered 

Related, I hate waiting for new quests to load when marking a shop as a new type of shop.

**Comment by westnordost** [comment]
Ok, I could go into detail into why, but I will skip to the point:

1. The address street quest does currently not pop up when you answer the house number quest, not even if you uploaded it
2. For the next major version, the address street quest will pop up immediately after answering the house number quest, even if you are offline

**Comment by kmpoppe** [comment]
@westnordost 🤷‍♂️ I always love details, but anyhousel. Thanks, will pass the information on!

**Comment by westnordost** [comment]
Details about the big-ass refactor are here, https://github.com/streetcomplete/StreetComplete/issues/2506 with pictures
