### ISSUE TITLE
Check for existence of more things

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2744]
I think the following things should also be checked for existence.

These should probably be checked every 2 years:
- Barbecues (`amenity=bbq`) ~25000 uses and is an iD preset
  - There could also be a quest about whether or not the bbq is covered or what fuel it uses, but that would be a separate issue
- Defibrillator (`emergency=defibrillator`) ~37000 uses and is an iD preset
  - There's the quest asking if defibrillators are indoors, but if that had already been set then the object wouldn't otherwise be changed by SC

And these every 4 years:
- Life rings (`emergency=life_ring`) ~4000 uses and is an iD preset
- Emergency phones (`emergency=phone`) ~52000 uses and is an iD preset
- Flagpole (`man_made=flagpole`) ~63000 uses and is an iD preset

I'm not fully sure on which ones should be 2 or 4 years, but I think it would be good to check for the existence of all of these at some interval.

**Comment by westnordost** [comment]
`emergency=defibrillator` will be difficult as they are often in buildings (and small). We wouldn't want a defibrillator be deleted only because a surveyor wasn't able to see it from the outside and/or was looking in the wrong room for it.

For the rest, I'd say that it makes sense, yeah.

**Comment by arrival-spring** [comment]
That makes sense, although if someone can't find a defibrillator when looking for it then that would be a problem.

**Comment by matkoniecz** [comment]
`man_made=flagpole` and `emergency=phone` - what about 6 or 8 years? This things are very stable (at least in my experience).

**Comment by arrival-spring** [comment]
I'd say that emergency phones are probably more stable than flagpoles in my experience.
I'd suggested 2 and 4 years because those are the only current timescales for checking existence.

**Comment by arrival-spring** [comment]
@matkoniecz does this mean you are working on this?

**Comment by matkoniecz** [comment]
@arrival-spring For now I implemented it and will be testing is it a good idea (testing is more time-consuming part).

If I will think that it is a good idea, I will make PR (or commit directly if sure).

But if you are interested - feel free to implement, test and make a PR.

**Comment by Lukas458** [comment]
I think amenity=ticket_validator` might also be worth resurveying. Similar to `amenity=vending_machine` + `vending=public_transport_tickets`, ticket validators get sometimes removed in these days because people are using more eletric/internet-based solutions for buying pt-tickets, so ticket validators aren't needed so much anymore.

I could look for that `amenity=ticket_validator` gets an iD preset

**Comment by matkoniecz** [comment]
> I could look for that amenity=ticket_validator gets an iD preset

Yes, that is a required part (and likely would be useful anyway).

**Comment by westnordost** [comment]
emergency phones may be very stable, but also it'd be quite bad if it is not there anymore if one needs it. So it is ok to check more often for such things even if the chance is smaller that they are not there anymore. Also, emergency phones are likely in areas where there are not that many other quests do do right?

**Comment by westnordost** [comment]
I didn't add flagpole because there are both apparently a lot of them and the usefulness to keep this info up to date is not really apparent to me.

**Comment by matkoniecz** [comment]
> Also, emergency phones are likely in areas where there are not that many other quests do do right?

I have seen them solely along motorways.

**Comment by Lukas458** [comment]
> I could look for that amenity=ticket_validator gets an iD preset
I'm going to work on this, but peopla @ iD seem to be not that far in merging new presets...

**Emergency phones** are also usual (or mandatory?) in subway stations (or genreally at stations).. But there they might be difficult to check/people have to be careful with the levels, often in subway stations there are several and you need to check on which level the phone really is

**Comment by arrival-spring** [comment]
> also add ticket validator (#2744)

There's no iD preset for that at the moment, but that seems to make it just that the quest doesn't show up for those things until that's the case.

> I didn't add flagpole because there are both apparently a lot of them and the usefulness to keep this info up to date is not really apparent to me.

Not sure there are a lot in comparison to other things, but actually yes, I see our point about it not being useful to keep that info up to date.

**Comment by Lukas458** [comment]
Maybe also **amenity=toilets** (so surely only those without access=private or customers) are worth resurveying in the existence quest? I'm not completely sure know if that often happens, but in my area some public toilets are getting closed for a long time (or forever) either due to renovations or due to vandalism/too expensive costs for the operator.

**Comment by Lukas458** [comment]
Thank you!

**Comment by Lukas458** [comment]
Hi,
can I put another idea and a question here, concerning the eistence quest?

1. amenity=bench and leisure=picnic_table get resurveyed (every 6 / 4 years), so maybe adding also **amenity=lounger** to them could make sense? It's a relatively new tag (for public loungers). **An iD preset exists.**

2. And where I see that: Did someone think of the objects which have a **seasonal**-Tag? For example some benches. **seasonal** seems to be not so often combined with amneity=bench according to taginfo (https://taginfo.openstreetmap.org/keys/seasonal#combinations), but it _can_ appear. So is there any way to ask for those objects only when it would be there "seasonal", or to exclude those objects from the quest?

**Comment by matkoniecz** [comment]
>  can I put another idea and a question here, concerning the eistence quest?

In general it is better to open a new issue - comments in old one can be easily missed and forgotten of not implemented immediately.

> So is there any way to ask for those objects only when it would be there according to "seasonal", or to exclude those objects from the quest?

Just 42 worldwide - see https://overpass-turbo.eu/s/19Ed

Excluding `seasonal` objects still may make sense

**Comment by Lukas458** [comment]
Yeah, seasonal seems to be not sooo common/widespread, but surely as a reason also because people often just do not know about. If they see a bench at summer and do not come along at this point at autumn or winter again, they cannot know whether the object is seasonal or isn't.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/amenity=lounger#chronology - barely anything will qualify for check existence quest, even with more often checking enabled. But tag makes sense, grows quickly and effort to add it is minimal so I will implement it.

> Yeah, seasonal seems to be not sooo common/widespread, but surely as a reason also because people often just do not know about. If they see a bench at summer and do not come along at this point at autumn or winter again, they cannot know whether the object is seasonal or isn't.

Still, if only 42 objects worldwide are tagged (note: I checked only benches!) then implementing parsing of seasonal tag is definitely not worth it. Maybe even reviewing pull request adding it would be not worth doing.

**Comment by matkoniecz** [comment]
![screen02](https://user-images.githubusercontent.com/899988/126683874-882ac082-576e-458f-ae5b-2a038d56f8b4.png)
Right now to even see it one would need to enable more often checking of existence of things AND look for oldest mapped loungers.

See https://overpass-turbo.eu/s/19Ei for old ones
