### ISSUE TITLE
Maxspeed quest should tag a road as lit when that is asked

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2745]
In the UK the speed limit can depend on whether or not there is street lighting, so when a user selects "No sign, defaults apply" and then "Yes, no sign" they are then asked if the road is lit (if that hasn't been set already).

However this does not set `lit` on the road, and it feels like it should have done.

**Comment by westnordost** [comment]
I guess nothing speaks against this.

**Comment by arrival-spring** [comment]
However when working on this I realised that the quest doesn't quite work in the UK in all situations.

Single and dual carriageway roads (`maxspeed:type=nsl_single` or `nsl_dual`) can be lit and should still have that `maxspeed:type` set, at the moment this assumes that any lit road is `nsl_restricted`.

See [maxspeed:type#UK](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type#UK) on the wiki:
`nsl_restricted` means 30 mph for cars
`nsl_single` means 60 mph for cars
`nsl_dual` means 70 mph for cars

So it's quite important to get the difference between these right.

At the moment, if I was asked for the maxspeed of a single carriageway national speed limit road I would want the app to set at least `maxspeed:type=nsl_single` and probably also `maxspeed=60 mph`, whether or not the road is lit.

I don't have an option that leads to that though. If I say that the speed limit is defined by a sign then I have to enter a numeric value for the sign, but the national speed limit sign is white with a black diagonal line (main picture on the  [maxspeed:type wiki page](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type)) and this wouldn't add the correct `maxspeed:type`.

If there is a single carriageway lit road that is national speed limit then if I say that there is no sign and defaults apply then the app will add `maxspeed:type=nsl_restricted` which implies 30 mph, but it should be `nsl_single` and 60 mph.

Perhaps the solution to this is another top level option in the UK which is "National Speed Limit" (all UK drivers will know what this means), this should then ask if it's single or dual carriageway and add `nsl_single` or `nsl_dual` as appropriate, and would ideally have an image of the sign to confirm.

I would also suggest that (in the UK) when implicit maxspeeds are set that the appropriate maxspeed is also set.

**Comment by peternewman** [comment]
> However this does not set `lit` on the road, and it feels like it should have done.

Yes, please! I didn't realise it didn't do this, I think I normally see it the other way round (possibly due to my priorities) where it asks if it's lit when I've already told it that it is, but assumed that would be fixed by https://github.com/streetcomplete/StreetComplete/milestone/14 but maybe it's actually this I'm thinking of.

**Comment by westnordost** [comment]
Or as a third choice: lit, unlit, white sign with black diagonal line

On April 15, 2021 1:13:17 AM GMT+02:00, arrival-spring ***@***.***> wrote:
>However when working on this I realised that the quest doesn't quite
>work in the UK in all situations.
>
>Single and dual carriageway roads (`maxspeed:type=nsl_single` or
>`nsl_dual`) can be lit and should still have that `maxspeed:type` set,
>at the moment this assumes that any lit road is `nsl_restricted`.
>
>See
>[maxspeed:type#UK](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type#UK)
>on the wiki:
>`nsl_restricted` means 30 mph for cars
>`nsl_single` means 60 mph for cars
>`nsl_dual` means 70 mph for cars
>
>So it's quite important to get the difference between these right.
>
>At the moment, if I was asked for the maxspeed of a single carriageway
>national speed limit road I would want the app to set at least
>`maxspeed:type=nsl_single` and probably also `maxspeed=60 mph`, whether
>or not the road is lit.
>
>I don't have an option that leads to that though. If I say that the
>speed limit is defined by a sign then I have to enter a numeric value
>for the sign, but the national speed limit sign is white with a black
>diagonal line (main picture on the  [maxspeed:type wiki
>page](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type)) and this
>wouldn't add the correct `maxspeed:type`.
>
>If there is a single carriageway lit road that is national speed limit
>then if I say that there is no sign and defaults apply then the app
>will add `maxspeed:type=nsl_restricted` which implies 30 mph, but it
>should be `nsl_single` and 60 mph.
>
>Perhaps the solution to this is another top level option in the UK
>which is "National Speed Limit" (all UK drivers will know what this
>means), this should then ask if it's single or dual carriageway and add
>`nsl_single` or `nsl_dual` as appropriate, and would ideally have an
>image of the sign to confirm.
>
>I would also suggest that (in the UK) when implicit maxspeeds are set
>that the appropriate maxspeed is also set.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2745#issuecomment-819908449

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by arrival-spring** [comment]
> Yes, please! I didn't realise it didn't do this, I think I normally see it the other way round (possibly due to my priorities) where it asks if it's lit when I've already told it that it is, but assumed that would be fixed by https://github.com/streetcomplete/StreetComplete/milestone/14 but maybe it's actually this I'm thinking of.

By default, maxspeed is asked before lit (if maxspeed is enabled) and maxspeed only asks if a road is lit if that hasn't already been set.

> Or as a third choice: lit, unlit, white sign with black diagonal line

Those aren't mutually exclusive though (a road could be lit and have that sign).

**Comment by peternewman** [comment]
> Or as a third choice: lit, unlit, white sign with black diagonal line

Presented exactly like that seems pretty ambiguous to me @westnordost . As @arrival-spring pointed out, a road can be lit and have the sign.

> By default, maxspeed is asked before lit (if maxspeed is enabled) and maxspeed only asks if a road is lit if that hasn't already been set.

Yeah, I think I'd possibly changed the order before.

> See [maxspeed:type#UK](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type#UK) on the wiki:
> `nsl_restricted` means 30 mph for cars
> `nsl_single` means 60 mph for cars
> `nsl_dual` means 70 mph for cars

Any reason you've skipped `nsl_motorway`?

**Comment by arrival-spring** [comment]
> Any reason you've skipped `nsl_motorway`?

Only really because it's not currently being set by the app

Also I feel like it should be assumed by data consumers for `highway=motorway` where no other `maxspeed` is set.

**Comment by westnordost** [comment]
Probably you are right, @peternewman 

So, to also add `lit=yes/no` is something that could be added in a minor update. Adding such an option with that sign should go into a major update, in other words, those two things should be done in two different PRs. 
Would you like to implement this, @arrival-spring ?

**Comment by arrival-spring** [comment]
Ok, that sounds good, yes, I've already started working on it anyway.

**Comment by westnordost** [comment]
I will close this issue because the PR that directly fixes the thing in the title has been superceded by a PR that does more than described here.
