### ISSUE TITLE
Quest repeatedly appearing for a node that has the requested information already

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#2746]
A bus stop node 2417952159 that hasn't changed for 7 years and that has a bench at the stop according to OSM, keeps appearing as a bus stop bench quest. I replied yes to it a few times already, but it keeps returning after a few weeks. Puzzling...
![Screenshot_20210415-144701](https://user-images.githubusercontent.com/69100427/114864489-b9874680-9df9-11eb-9137-d5196be5bf40.png)

**Comment by westnordost** [comment]
Can you tell me the location?

**Comment by rhhsm** [comment]
https://www.openstreetmap.org/node/2417952159

**Comment by westnordost** [comment]
The wrong method was used - it tried to always add the information. In this case, this led to the answer being (silently) rejected.

**Comment by rhhsm** [comment]
FYI the same quest appeared again yesterday (using version 31.3)
