### ISSUE TITLE
Answering that traffic calming is gone should not delete nodes

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2752]
**How to Reproduce**
I enabled short resurvey interval (may be not needed) and scanned around https://www.openstreetmap.org/node/5254567356

I answered "it is gone"

> D/QuestController: Deleted NODE #5254567356 in frame of quest CheckExistence

It should not happen as it may change road geometry.

**Versions affected**
9d8b615164700455a6762f2341fb7fa1523556ac (Android should not be relevant here)

**Comment by matkoniecz** [comment]
not checked: maybe nodes are deleted only when road is straight and node is i the middle of ways (without crossing between various ways) and deletion would not affect anything? That is unlikely, as it seems to be not worth extra complexity.

**Comment by westnordost** [comment]
did you check that it actually deleted the node and not just stripped it off its tags?

**Comment by matkoniecz** [comment]
> did you check that it actually deleted the node and not just stripped it off its tags?

No, I just looked into log and have not investigated further. Is such deletion converted later into tag blanking?

**Comment by westnordost** [comment]
yes, see `DeleteSingleOsmElementUploader` on master or `DeletePoiNodeAction` on the dev branch

**Comment by matkoniecz** [comment]
OK, in such case I got scared by this log entry and things are working as expected (maybe except log message)
