### ISSUE TITLE
Does this shop sell tobacco products?

### ISSUE THREAD

**Issue by kuba-orlik** [streetcomplete/StreetComplete#2757]
### General
Affected tag(s) to be modified/added: [sells:tobacco](https://wiki.openstreetmap.org/wiki/Key%3Asells%3Atobacco)
Question asked: **Does XY sell tobacco products?**

Although it'd be useful for users of tobacco products, my main motivation for adding this is to be able to filter out shops that do sell tobacco/cigarettes etc, making boycotting tobacco sellers easier.

Although it might seem like too much information for some, I think it's in line with, for example "does this restaurant have vegan options on the menu".

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**

Does this place sell tobacco products? (For example: cigarettes) |  
-- | --
Yes \| No |

**Comment by matkoniecz** [comment]
Main problem is with

> tag is established

part.

> I think it's in line with, for example "does this restaurant have vegan options on the menu".

Main difference is that tagging vegetarian restaurants was established as OK tagging scheme.

Tagging every single shop as having tobacco products or not is not established and StreetComplete is avoiding introducing such changes on its own.

> sells:tobacco

One extra thing on looking through it again: not entirely sure is it something how that should be set when you can buy cigarettes but tobacco itself is not available.
