### ISSUE TITLE
Quest: Can you provide a photo of [...]?

### ISSUE THREAD

**Issue by NotSoImportant** [streetcomplete/StreetComplete#2762]
### General
Affected tag(s) to be ~~modified~~/added:: [Key:wikimedia_commons](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons)

Question asked: **Can you provide a photo of [...]?**

Answers:
1. &#128269; Search on wikimedia common
1. &#128247; Take photo

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] ? 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
    - foto can only be taken outside, but can also be answered at home by linking existing images
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
1. &#128269; Search
    - provide a text box prefilled with the name of the item + a "search" button
    - call the [wikimedia commons API](https://commons.wikimedia.org/w/api.php?action=help&modules=opensearch) and render results
    - user to select 1 file or 1 category

1. &#128247; Take foto
    - take/select a photo
    - have meta data prefilled
    - optional: enter description
    - upload
Two possible implementations:
    1. call the [wikimedia commons app](https://github.com/commons-app) intent (if installed)
        - if possible *Title* prefilled with the type and name of the item
        - auto-providing a category is not possible with the current app, I guess
    1. alternative: implement own **simple** upload interface
        - Name and categorie are already prefilled (maybe not even shown).
        - I am unsure about how to deal with the "depiction" field
        - User can provide a description
        - For simplicity, one license should be choosen already
        - Cons:
            - Need to deal with another login (maybe there is a way to sign into wikimedia with osm account?)
            - Need to deal with more details of the API

**Proposed GUI:**
&#128269; Search
- select file
![image](https://user-images.githubusercontent.com/35758921/115130778-9378c680-9ff2-11eb-81e3-3ae07adc264c.png)
- or select category
![image](https://user-images.githubusercontent.com/35758921/115130913-e4d58580-9ff3-11eb-8136-8d8936826e02.png)

&#128247; Take foto
![image](https://user-images.githubusercontent.com/35758921/115130783-a8edf080-9ff2-11eb-90af-9ae9d27ba3e9.png)

Login for new users
<img src="https://user-images.githubusercontent.com/35758921/115139176-c80b7300-a030-11eb-8d86-7fbc289fd7f0.png" width="260">

**Element selection:** 
Theoretically any node, but some are more valuable / common. We can start with some and extend over time.
I checked usage of *wikimedia_commons* tag, using overpass in Germany / Middle Europe.

Suggested:
- [Key:tourism=*](https://wiki.openstreetmap.org/wiki/Key:tourism), e.g.
    - [Tag:tourism=artwork][osm_art] &#8594; **very often** used
    - [Tag:information=guidepost][osm_guide] &#8594; often used
    - [Tag:information=board][osm_board] &#8594; used
- [Key:historic=*](https://wiki.openstreetmap.org/wiki/Key:historic), e.g.
    - [Tag:historic=memorial](https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dmemorial) &#8594; **very often** used
    - [Tag:historic=milestone](https://wiki.openstreetmap.org/wiki/Tag:historic=milestone) &#8594; often used, also *boundary_stone*, *wayside_cross* and *wayside_shrine* 

Also seen / rarely used:
- [Key:shop=*](https://wiki.openstreetmap.org/wiki/Key:shop) &#8594; often used in Germany Tübingen, also *office*
- [Key:amenity=*](https://wiki.openstreetmap.org/wiki/Key:amenity) &#8594; often used in Germany Tübingen (*restaurant*, *cafe*), elsewhere often *fountain*
- [Tag:highway=bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway=bus%20stop) &#8594; used in Germany Tübingen and Kassel 
- [Tag:natural=tree](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree) &#8594; often used in Germany Kassel
- [Tag:man_made=survey_point](https://wiki.openstreetmap.org/wiki/Tag:man_made=survey_point) &#8594; used in Germany Saxonia
- [Tag:information=map][osm_map]
- [Tag:emergency=defibrillator](https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Ddefibrillator) in France
- [Key:place=*](https://wiki.openstreetmap.org/wiki/Key%3Aplace) - quite some, but low percentage of all places
- [Tag:historic=castle](https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dcastle =250x250) - only ~70 in europe so far

**Automatically adding categories:**
For the sake of simplification, categories should be automatically added based on osm tags.
This can be driven very deep.
As far as I understand the wikimedia community, a category is not required but highly desired. So uploading initially with very broad categories might be ok and can be refined by the community later.
Additionally the categories could be combined with e.g. the respective country to be more specific.

Maybe this should be extracted to a mapping file, but maybe even to a whole new project, conceptually like [openstreetmap/id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema)

Examples:

| Tag: information=*                                        | Wikimedia commons category |
| -------------                                                      | ------------- |
| [Tag:information=board][osm_board]             | [Category:Information_boards][cat_board]  |
| [Tag:information=map][osm_map]                  | [Category:Photographs_of_maps][cat_map] |
| [Tag:information=guidepost][osm_guide]       | [Category:Guide_signs][cat_guide] |

[osm_board]: https://wiki.openstreetmap.org/wiki/Tag:information%3Dboard
[cat_board]: https://commons.wikimedia.org/wiki/Category:Information_boards
[osm_map]: https://wiki.openstreetmap.org/wiki/Tag:information%3Dmap
[cat_map]: https://commons.wikimedia.org/wiki/Category:Photographs_of_maps
[osm_guide]: https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost 
[cat_guide]: https://commons.wikimedia.org/wiki/Category:Guide_signs

| Tag:tourism=artwork                              | Wikimedia commons category |
| -------------                                                      | ------------- |
| [Tag:tourism=artwork][osm_art]                      | [Category:Art_works][cat_art] | 
| [Tag:artwork_type=sculpture][osm_sculpture] | [Category:Sculptures][cat_sculpture] | 
| [Tag:artwork_type=statue][osm_statue]           | [Category:Statues][cat_statue] |

[osm_art]: https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dartwork
[cat_art]: https://commons.wikimedia.org/wiki/Category:Art_works
[osm_sculpture]: https://wiki.openstreetmap.org/wiki/Tag:artwork_type%3Dsculpture
[cat_sculpture]: https://commons.wikimedia.org/wiki/Category:Sculptures
[osm_statue]: https://wiki.openstreetmap.org/wiki/Tag:artwork_type%3Dstatue
[cat_statue]: https://commons.wikimedia.org/wiki/Category:Statues

Please suggest additions/changes...

**Comment by matkoniecz** [comment]
That was proposed a bit, though this version is the best one so far and actually solves some problems present in earlier proposals.

Though some of problems discussed there remain.

See #1601 https://github.com/streetcomplete/StreetComplete/issues/1601#issuecomment-544299633

See #1883 https://github.com/streetcomplete/StreetComplete/issues/1883#issuecomment-638806649

See #1515

**Comment by NotSoImportant** [comment]
Thank you @matkoniecz. Seems I did not do a good search before.
I read trough these (and also some linked) proposals and comments now.

Which are the problems you think remain? Hopefully we can find solutions together.
- login?
- quality?
- copyright?
- effort?

**Comment by matkoniecz** [comment]
Primary problem is that it turns it from OSM editor into OSM editor and Wikimedia Commons upload app.

And requires app author to research and satisfy requirements of another community. Also, copyright issues are trickier with photos - for start see https://commons.wikimedia.org/wiki/Commons:Freedom_of_panorama

Communicating to user that they need two logins, obey rules of two different communities and tricky parts of copyright would be quite hard. Someone crossed Germany=Denmark border? Now they are not allowed to take photos of tourism=artwork unless it is a very old artwork.

The first three points from https://github.com/streetcomplete/StreetComplete/issues/1601#issuecomment-544299633 all apply also here.

I suspect that it would work better as a separate app (potentially reusing StreetComplete code).

See also https://github.com/commons-app/apps-android-commons/issues/883 ("Nearby notable things from OpenStreetMap" in Wikimedia Commons App) - though on that side they would be in turn unhappy about "and add `wikimedia_commons` tag to the OSM element"

> Seems I did not do a good search before.

Hopefully with even more varied description it is more likely that next person with this idea will be more succesfull.

**Comment by westnordost** [comment]
I've looked at the Wikimedia commons app for Android and iOS and I'd say that this app already provides all the functionality to add photos to Wikimedia commons. I see no point in replicating this functionality in this app.

Granted, of course, the link to OpenStreetMap is missing, but as you said yourself, this is something that can be done better at home. It also then free from the corset of quest type limitations (filtering the right elements for which it is applicable) and you can - at home with iD or JOSM - also add the tag to things other than historic things and artworks but anything.

**Comment by westnordost** [comment]
Also, a search through wikimedia commons requires internet connection. No other quest type currently requires internet connection.

I think the workflow to add images to wikimedia common is already good as it is: If I understood the Wikimedia Commons app correctly, there is already a mechanism for Wikimedians to request photos to be taken of a certain object which will then be shown in that app.

**Comment by NotSoImportant** [comment]
@westnordost you are right with your points. I am finally searching for an easy roundtrip to include images into osm data and have not found it yet.

I have the wikimedia commons app installed and used it to upload new photos, but am not aware of such functionality to request photos / show such requests.

**Comment by NotSoImportant** [comment]
@matkoniecz Thank you for commenting on the details and providing the link to the wikimedia app issue. Unfortutately it looks inaktive, but I will try to follow up on it.

**Comment by matkoniecz** [comment]
@NotSoImportant App itself is active, this specific issue is probably of the "if someone cares they will implement it or hire someone to implement it".

On topic of linking Wikimedia Commons and OSM objects - https://wiki.openstreetmap.org/wiki/OSM_%E2%86%94_Wikidata_matcher is very useful for that (by linking WIkidata objects you are indirectly link Wikimedia Commons categories and directly link images in Wikidata entries that are always from Wikimedia Commons)

There is also https://fist.toolforge.org/wdfist/ for adding images to Wikidata entries

(many, many objects can get images this way)
