### ISSUE TITLE
Traffic lights tactile indication (signals vibration) asked before  traffic signals button

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#2763]
**How to Reproduce**
Go to an appropriate traffic signal (without any button to request a traffic signal change). I.e. one without `button_operated` set and without `traffic_signals:vibration`.

Then, the [`traffic_signals_vibration`](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#traffic_signals_vibration) quest ("Do these traffic lights have a tactile indication for blind people for when it's safe to cross?") is asked before even [`traffic_signals_button`](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#traffic_signals_button) ("Do these traffic lights have a button to request a walk signal?") (if I use the default priority).

`traffic_signals_vibration`:
![traffic_signals_vibration](https://user-images.githubusercontent.com/11966684/115144382-9b655480-a04c-11eb-97ac-80e1b9f5c2f1.png)

IMHO this makes, logically no sense, because when `traffic_signals_vibration` quest of course requires a `traffic_signals_button` quest answered with "yes", i.e. it requires a button at the traffic light.

This results in two issues:
* the order is not logical, so answering the dependent question before the requirement that this question needs feels weird (that is not that bad though but well… confusing)
* If there is no button, what should I answer to `traffic_signals_vibration`? I may answer "No", but if the traffic sign has no button, it feels quite useless to answer that and may result in strange inaccurate data.
  I miss a "Other answer" -> "Actually, there is no button" answer possibility, which may then also skip the `traffic_signals_button` quest, respectively, answer both.

**Versions affected**

v31.2 I guess

**Comment by westnordost** [comment]
> IMHO this makes, logically no sense, because when traffic_signals_vibration quest of course requires a traffic_signals_button quest answered with "yes", i.e. it requires a button at the traffic light.

No, it doesn't.

This is `traffic_signals_button=yes` + `traffic_signals_vibration=yes`. You need to press the button to request a walk signal, and at the bottom there is also a vibrating arrow.
![taster](https://user-images.githubusercontent.com/4661658/115146635-9eb20d80-a057-11eb-9990-e54acb76d717.jpg)

This is `traffic_signals_button=no` + `traffic_signals_vibration=yes`. You can't press the button to request a walk signal, there is only a vibrating arrow at the bottom.
![blinde](https://user-images.githubusercontent.com/4661658/115146680-c903cb00-a057-11eb-8593-29c8e695e89c.jpg)

**Comment by rugk** [comment]
Ahhh okay, you’re right of course! I only thought of treaffic signals without any button (yellow thing) at all.
