### ISSUE TITLE
Distinguish between zebra crossings and other marked crossings

### ISSUE THREAD

**Issue by daPhipz** [streetcomplete/StreetComplete#2764]
### General
This is a proposal to add another answer option to the "What kind of crossing is this?" quest. 
In Germany, many crossings are marked like this:

![](https://www.fuerboeck.at/uploads/pics/bm_radfahrerueberfahrt2.jpg)

I would tag the above example as

```
highway=crossing
crossing=uncontrolled
```

When it comes to German traffic regulation/law (StVO), these crossings are different from zebra crossings. This is why I think there should also be a "Zebra crossing" option. When the user selects this answer, StreetComplete should tag as follows:

```
highway=crossing
crossing=marked
crossing_ref=zebra
```

**Affected tag(s) to be modified/added:**
- [`crossing`](https://wiki.openstreetmap.org/wiki/Key:crossing)
- [`crossing_ref`](https://wiki.openstreetmap.org/wiki/Key:crossing_ref)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 
Same as before, just with one more option.

**Proposed GUI:**
Same as before, just with one more option.

**Comment by mnalis** [comment]
Firstly, I'd always go with `crossing=marked` as opposed to `crossing=uncontrolled`, as it not only less ambiguous but also  [more used](https://taginfo.openstreetmap.org/keys/crossing#values), and [they mean the same thing](https://wiki.openstreetmap.org/wiki/Key:crossing).

As for adding [crossing_ref=zebra](https://wiki.openstreetmap.org/wiki/Tag:crossing_ref%3Dzebra), can it also be drawn even when the pedestrian crossing is marked with traffic lights in Germany? In Croatia it can (and in majority of cases is), potentially creating confusion (eg. problem for _"Easily answerable by everyone"_).

Also, in Croatia, it is called zebra (and marked with `crossing=marked` + `crossing_ref=zebra`) only if:
- it is pedestrian-only (and not when combined with other crossings [like bicycle](https://image.dnevnik.hr/media/images/996x562/Nov2018/61601046-pjesacki-prijelaz.jpg))
- stipes are [full-width across whole crossing](https://objektivno.hr/wp-content/uploads/2016/01/zebra_pje%C5%A1a%C4%8Dki-prijelaz_pje%C5%A1aci_promet_fah.jpg) (not when marked only on sides - as in your picture, or [here](https://www.mapillary.com/app/?lat=45.79441817472224&lng=15.949356509166705&z=17&focus=map&pKey=pKHrnElQ5i00k2ExzXOD_w&x=0.6753147136822742&y=0.7589167217422942&zoom=1.827586206896552))
- it is without traffic lights (ie. never added on `crossing=traffic_lights`, even if zebra stripes are drawn on the street)

So the crossing node in your picture in Croatia would be tagged as:
```
highway=crossing
crossing=marked
bicycle=designated
foot=no
oneway=no
```

but **without** `crossing_ref=zebra`.

(Also, out of interest, can you add picture of other types of `crossing=marked` crossings in Germany, and how they differ in traffic control as opposed to the picture of crossing you already posted? for _"tag [...] has a useful purpose"_)

**Comment by westnordost** [comment]
The example picture is not a crossing for pedestrians at all. **Any** marked crossing for pedestrians is a zebra.

**Comment by DerDings** [comment]
> 
> The example picture is not a crossing for pedestrians at all. **Any** marked crossing for pedestrians is a zebra.

No, if pedestrians and cyclists share the same way, the crossing may also be marked like that.

Those markings are there to illustrate that the cycle way is part of the prioritized road. Vehicles need to give way to cyclists here. 
When part of a shared foot&cycle way, this may lead to the strange situation that cyclists are prioritized (because they're vehicles on a prioritized road) at the same place where pedestrians are not (because it doesn't have zebra markings). Yip, german traffic rules are that complicated. Please correct me if this really confusing regulation has been simplified now.

But I don't know if this difference is currently documented anywhere in the wiki.

**Comment by westnordost** [comment]
> cyclists are prioritized (because they're vehicles on a prioritized road) at the same place where pedestrians are not

Source?

**Comment by westnordost** [comment]
Nevermind, you are right.

**Comment by westnordost** [comment]
So, actually, we are talking about "unmarked crossing" for pedestrians, "marked crossing" for cyclists, but when in OSM, the cycle track and sidewalk are both mapped as one way (or as tags on the road).

**Comment by DerDings** [comment]
> 
> 
> So, actually, we are talking about "unmarked crossing" for pedestrians, "marked crossing" for cyclists, but when in OSM, the cycle track and sidewalk are both mapped as one way (or as tags on the road).

They can even be one element in reality:
![grafik](https://user-images.githubusercontent.com/42044179/115201315-7e389080-a0f5-11eb-9dd4-455c5ead0c51.png) © [RVR](https://www.luftbilder.geoportal.ruhr/), 2020, [dl-de/by-2-0](https://www.govdata.de/dl-de/by-2-0)

It is one marked crossing which is used by both cyclists and pedestrians. But it is not a zebra crossing. There's also no crossing sign, traffic is ruled by regular "give way" and "priority road" signs.

**Comment by daPhipz** [comment]
> The example picture is not a crossing for pedestrians at all.

Yes, I know that. It was just to illustrate - imagine it _was_ a crossing for pedestrians. In this case, I would tag it as noted.

**Comment by daPhipz** [comment]
@DerDings's picture is better. My problem is that, with StreetComplete, one is unable to distinguish between a crossing where the markings are on the side (like in the picture) and a crossing with a zebra. Those are two different things in traffic law, and should this be marked different in my opinion.

**Comment by westnordost** [comment]
Hm okay, but is adding the `crossing_ref` actually the correct way to map this situation?

**Comment by DerDings** [comment]
> Hm okay, but is adding the `crossing_ref` actually the correct way to map this situation?


The documentation of crossing_ref=zebra is very clear here. An uncontrolled crossing with zebra markings therefore is
```
highway=crossing
crossing=uncontrolled
crossing_ref=zebra
```
A crossing where only the passage outline is marked is correctly tagged
```
highway=crossing
crossing=uncontrolled       // the original issue suggests crossing=marked. But the english documentation just says marked is a duplicate of uncontrolled. Giving those tags different meanings shouldn't be done by SC
```
So making a difference in the "what type of crossing is here?" quest is possible. So far this probably works in every country.


What probably is more difficult is to make a new quest to check all marked crossings of an undefined type, because there is no counterpart for `crossing_ref=zebra` to indicate that a crossing is marked, but not a zebra crossing.
In Germany this would work by adding `bicycle=yes` to said crossings where only the passage is marked. Maybe also in the Netherlands, but I don't know their rules in detail. Either way this would be a very country-specific quest.

The whole definition of the different crossing tags is very bad. When `crossing=island` became `crossing:island=yes`, the same should have happended to `crossing:marked=*` and `crossing:controlled=*` imo. But that's not to be discussed here.

**Comment by westnordost** [comment]
StreetComplete doesn't use `crossing=uncontrolled` though, but `crossing=marked`.

> What probably is more difficult is to make a new quest to check all marked crossings of an undefined type, because there is no counterpart for crossing_ref=zebra to indicate that a crossing is marked, but not a zebra crossing.

Yes, that would be impossible, there is no `crossing-ref=not_zebra`

**Comment by westnordost** [comment]
Anyway, for this extension of this quest to be possible, we need to be able to tag both situations:
- a zebra crossing
- a not-zebra crossing

I didn't read into the wiki yet, can you tell if this is the case? If not, I'll close this and it can be reopened until the community can agree on a tag that can be used for that.

**Comment by Cj-Malone** [comment]
Currently there is no tagging for "is not a zebra crossing", so you can't have a quest "Is this crossing a zebra crossing?". However unless I'm confused, you could move it up into the current crossing type and have it as a 4th answer.

**Comment by westnordost** [comment]
I could, but then there is no difference between "this is not a zebra crossing" and "it hasn't been checked yet if this is a zebra crossing".

**Comment by Cj-Malone** [comment]
> I could, but then there is no difference between "this is not a zebra crossing" and "it hasn't been checked yet if this is a zebra crossing".

Isn't that the current situation anyway?

**Comment by Cj-Malone** [comment]
What about, the current "What kind of crossing is this?" quest having answers closer to the building type quest.
You get the current 3 answers as top level options, selectable and valid, but then the open up to have more specific options.
- Traffic signals
  - Pelican
  - Toucan
  - Puffin
  - Tiger
  - Pegasus
- Uncontrolled
  - Zebra
- Unmarked

Although, this is getting pretty specific to GB (British colonies?), and it'll be hard to explain the difference between most types of crossings.

**Comment by matkoniecz** [comment]
Note that animal crossing names are utterly inapplicable in nearly al countries except UK.

**Comment by westnordost** [comment]
> Isn't that the current situation anyway?

Yes, and bad tagging design can be a reason for not including something in StreetComplete. Currently it is not possible to find out in OSM whether something is "not a zebra crossing" or "it hasn't been checked yet if this is a zebra crossing".
So, StreetComplete will not enter there to try rectify this situation if there is no tag to do that.

**Comment by daPhipz** [comment]
That's unfortunate, but completely understandable. Thank you for considering it, though!

**Comment by nicorikken** [comment]
I came to this issue as I found the current (v33.1) UI a bit ambiguous. It shows an image with a zebra but asks whether it is marked or not. I wasn't sure if these more simple markings would be considered 'marked'. Turns out they do, after finding this issue and looking through the StreetComplete sourcecode.
