### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by tparcina** [streetcomplete/StreetComplete#2765]
**Use case**
It is hard to orientate when StreetComplete is always looking north, and I am walking and looking south. Then, my right is left, and my left is right.

**Proposed Solution**
It would be great if map would rotate just like I rotate ma mobile phone. If I look south, I would like the map to rotate and look to south as well. Plenty of other applications have this functionality and they will be almost useless without it. Some of them are route planning and night sky watching.

Thank you in advance and best regards.

**Comment by FloEdelmann** [comment]
Try clicking on the GPS button (so the map follows your position) and then the compass button. Then the app should already do what you want :)

**Comment by kmpoppe** [comment]
At the very least, you can manually rotate the map by holding one finger stationary on the display and rotating the other one around it.

**Comment by tparcina** [comment]
> Try clicking on the GPS button (so the map follows your position) and then the compass button. Then the app should already do what you want :)

This does not work for me. If I click on compass button, just the view changes (from top to more 3D like), but it does not rotate the map.

**Comment by andrewharvey** [comment]
> This does not work for me. If I click on compass button, just the view changes (from top to more 3D like), but it does not rotate the map.

You need to first click the locate button in the bottom right, and not pan the map so that it stays locked on your GPS location, then you can press the compass button. Maybe it should still match the compass bearing even if you've panned the map so it's not locked?

> At the very least, you can manually rotate the map by holding one finger stationary on the display and rotating the other one around it.

Very hard to do one handed.

**Comment by kmpoppe** [comment]
> Very hard to do one handed.

It works for me, even one-handed (holding phone firm with fingers 3-5 and rotating with 1 and 2, counting with thumb = 1).

**Comment by andrewharvey** [comment]
> It works for me, even one-handed (holding phone firm with fingers 3-5 and rotating with 1 and 2, counting with thumb = 1).

That takes skill. When I try the map does rotate, but I also end up zooming out a long way, and bumping the undo button with my palm.

**Comment by tparcina** [comment]
> You need to first click the locate button in the bottom right, and not pan the map so that it stays locked on your GPS location, then you can press the compass button. Maybe it should still match the compass bearing even if you've panned the map so it's not locked?

:star_struck: 
It works! :grin: 
I do not know how I did not figure this one before. I am sure that I was experimenting with compass button.

Anyway, thank you for info!

Best regards.

**Comment by smichel17** [comment]
> Maybe it should still match the compass bearing even if you've panned the map so it's not locked?

I think this would be confusing if your current position is offscreen. It could tilt and rotate *toward* your current position.. I'm not sure if this is any better than the current behavior, though.

**Comment by BalooUriza** [comment]
It would be helpful if it were possible to keeo direction of travel
upwards, as some devices (Pixel, for example) have some serious magnetic
compass shortcomings.

**Comment by smichel17** [comment]
That's https://github.com/streetcomplete/StreetComplete/issues/1040 :slightly_smiling_face:

**Comment by ChildishGiant** [comment]
> Try clicking on the GPS button (so the map follows your position) and then the compass button.

I came to GitHub to request this functionality, it's currently hidden behind a sequence of button pressed that I never thought to try. Maybe a pointer somewhere would help UX?

**Comment by mnalis** [comment]
@ChildishGiant do you have a suggestion what would have helped you to discover it? 

For what it's worth, it is mentioned in StreetComplete [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_to_use_2D.2F3D_and_GPS_following.2Frotation.3F), which is available from `menu` / `About`, and contains this and few other helpful hints / explanations.

**Comment by ChildishGiant** [comment]
I was looking in settings, expecting it to be an option in there so didn't see the FAQ. My first thought is that there should be an option for it in settings but maybe a catch-all "any questions? Look at the FAQ or open an issue" kind of message at the bottom of the settings would be better

**Comment by smichel17** [comment]
@ChildishGiant did you ever find the "tilt the map" option (by tapping the compass when you're already facing north), when the map is *not* locked to your position?

I'm thinking that, if you press the gps button to start following your position, and the map is already tilted, then it should enter compass mode directly (rather than the current, weird, behavior where we keep the current tilt angle).
