### ISSUE TITLE
Add "it is still being constructed" in can't say for addresses

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2773]
**Use case**
Quite often I get address quest for buildings still being constructed, and there is no reasonable way to answer that.

(In fact i got one right now)

Even asking people living there will not help as on that case it is not possible

**Proposed Solution**
Add "it is still being constructed" in can't say menu. It works retag building to `building=construction` (it is revocable with SC alone as it will ask is construction finished and building value).

Maybe string from building quest can be reused, so translators have no additional work (but maybe this may cause problems in some languages?)

I would be happy to implement it

**Comment by rhhsm** [comment]
That's what I proposed in #2656 second bullet

**Comment by westnordost** [comment]
Well, it is also not possible to retag a building to another building in the housenumber quest but a note has to be left. Why should there be a dedicated option for construction sites? I find this very specific and IMO it is not worth implementing. You wrote you would implement this yourself, but there is also always to consider to not litter the (other answer menu) UI with too many rare answers

**Comment by matkoniecz** [comment]
> Why should there be a dedicated option for construction sites? I find this very specific and IMO it is not worth implementing. You wrote you would implement this yourself, but there is also always to consider to not litter the (other answer menu) UI with too many rare answers

Maybe my area has unusually many contsruction sites and this construction sites for some reason are tagged with specific building values differing from `building=construction`

And I am trying to edit directly whenever possible as I create many many notes anyway, and notes that I created often hang on for long time unsolved so I am trying to reduce how many I create.

But of that would be an overkill for StreetComplete I am fine with having it only in my fork.

**Comment by westnordost** [comment]
Hm let's leave this open for a little while to see what others think

Am 21. April 2021 08:38:32 MESZ schrieb Mateusz Konieczny ***@***.***>:
>> Why should there be a dedicated option for construction sites? I find
>this very specific and IMO it is not worth implementing. You wrote you
>would implement this yourself, but there is also always to consider to
>not litter the (other answer menu) UI with too many rare answers
>
>Maybe my area has unusually many contsruction sites and this
>construction sites for some reason are tagged with specific building
>values differing from `building=construction`
>
>And I am trying to edit directly whenever possible as I create many
>many notes anyway, and notes that I created often hang on for long time
>unsolved so I am trying to reduce how many I create.
>
>But of that would be an overkill for StreetComplete I am fine with
>having it only in my fork.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2773#issuecomment-823816429

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
