### ISSUE TITLE
[v32.0-alpha] Notes are no longer blocking quest recreation

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2776]
Expected: note is blocking quest recreation, like before
What happens: it is not blocking

**How to Reproduce**
Uninstall app.

Install fresh version from the latest commit.

Zoom to https://www.openstreetmap.org/note/2397573#map=19/50.08110/19.88406&layers=N / https://www.openstreetmap.org/note/2397574#map=19/50.08110/19.88406&layers=N  area, scan for quests.

Note that geometry of way is not changed since notes were created

**Versions affected**
Tested on https://github.com/streetcomplete/StreetComplete/commit/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1 - latest master

**Comment by westnordost** [comment]
Can't reproduce for https://www.openstreetmap.org/note/2397573#map=19/50.08099/19.88372&layers=N

**Comment by westnordost** [comment]
Also not https://www.openstreetmap.org/note/2397574#map=19/50.08110/19.88406&layers=N or https://www.openstreetmap.org/note/2565074

**Comment by matkoniecz** [comment]
Weird. I will try to install again from scratch.

**Comment by westnordost** [comment]
Also can't reproduce if I close the note -> re-download -> quest appears. If I reopen the note and re-download, quest disappears again.

**Comment by matkoniecz** [comment]
Hopefully it is not caused by some weird threading bug on download (if note download is delayed/timeouts...)

**Comment by westnordost** [comment]
Something that happens never/almost never would be that the OSM map data download takes longer than the notes download. So, I didn't test that case. Looking at the code however, this should also not be a problem

**Comment by westnordost** [comment]
I just tested that. The quests in question appear then, but as soon as the notes download is done, they vanish again. So, expected behavior.

**Comment by matkoniecz** [comment]
I am going to blame cosmic rays but found something else.
