### ISSUE TITLE
[bug] Asking existence of bench right after asking if it has a backrest

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#2777]
SC asked me the existence of a bench just after the quest "Does this bench have a backrest ? " This is kinda weird to ask the existence of an object just after a quest on this object.

**Comment by westnordost** [comment]
Which version?

Am 21. April 2021 13:03:05 MESZ schrieb letypequividelespoubelles ***@***.***>:
>SC asked me the existence of a bench just after the quest "Does this
>bench have a backrest ? " This is kinda weird to ask the existence of
>an object just after a quest on this object.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2777

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by letypequividelespoubelles** [comment]
Oh sorry, forgot to tell it. It was with 31.2 from playstore. Now with 31.3, I can't check, I don't have those quests in my neighboorhood.

**Comment by westnordost** [comment]
That's ok, just wanted to check if this occurs in the v32-alpha.

The mechanism how quests are unlocked changed with v32-alpha, so I will close this as obsolete.
