### ISSUE TITLE
lane quest: unclear if oneway is "no markings" or "one marked line"

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#2778]
Am I rong or is this a bit confusing? 

v31.3

**Comment by matkoniecz** [comment]
It depends on a situation, sometimes you have line markings sometimes not.

For example https://www.google.pl/maps/@50.0940366,19.8931333,3a,55.4y,351.3h,89.73t/data=!3m6!1e1!3m4!1sAt-GMLDtT67xlfOe-h7XkA!2e0!7i13312!8i6656

![screen01](https://user-images.githubusercontent.com/899988/115593653-117bec80-a2d5-11eb-9c5a-1bd0355b537d.png)

has two tiny oneway roads with one marked lane - https://www.openstreetmap.org/way/251185140 https://www.openstreetmap.org/way/441972550#map=19/50.09420/19.89304&layers=N

**Comment by tiptoptom** [comment]
According to the wiki page (https://wiki.openstreetmap.org/wiki/Key:lane_markings) I would say that the key lane_markings is about makings which split the road into several lanes and not about makings which delimits the road.

**Comment by westnordost** [comment]
@tiptoptom it doesn't matter what you answer there, it will be tagged the same if there is just one lane.

**Comment by westnordost** [comment]
(without lane_markings)

**Comment by westnordost** [comment]
Or well: If you answer "is has no markings", it tags `lane_markings=no` and nothing more. If you answer "it has lanes: 1" it removes any `lane_markings` tag and sets `lanes=1`.

**Comment by tiptoptom** [comment]
Ok, I see. Thank you :pray:
