### ISSUE TITLE
app:theme->android:theme to supress spam in logs

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2779]
Logs show `"I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead."` spam.

Making that change has not resulted in obvious breakage and it seems to be safe according to quick checks.

Opening an issue as I am right now doing something else and maybe @westnordost knows why it was not done.

**Comment by westnordost** [comment]
Ok. You can just commit that to master

**Comment by matkoniecz** [comment]
If you are unaware about any traps I will check once more and commit directly.

**Comment by westnordost** [comment]
I am unaware

**Comment by matkoniecz** [comment]
https://stackoverflow.com/questions/57279615/what-is-the-difference-b-w-apptheme-androidtheme-in-android-programming

> What happens if I use android:theme instead of app:theme in MaterialDesign/AppCompat or any other custom view?

> If you do that, view's attributes that are available in all views will be customizable but any new attribute added by the custom view won't be customizable through theme. 

as far as I see this is not used in SC and I see no differences in how app looks like... (and 2019 answer may be outdated anyway)
