### ISSUE TITLE
OpenID login for cweiske.de fails

### ISSUE THREAD

**Issue by cweiske** [streetcomplete/StreetComplete#2781]
When trying to login in to OpenStreetmap in Streetcomplete the first time via OpenID, I get an error:

German:
> Authorisierungsserver kann nicht erreicht werden

English translation is about:
> Authorization server cannot be reached.

The last time I could login into StreetComplete via OpenID was 3-4 years ago. Since then I could not log in anymore but never managed to file a bug report here.

**How to Reproduce**
1. Menu -> Profile
2. Login window opens, click "Login"
3. Browser window with OpenStreetmap's Login window appears
4. Click the OpenID logo
5. Enter `http://cweiske.de` as OpenID and click "Login"
6. Error message toast pops up

**Versions affected**
- StreetComplete v31.2 (from f-droid.org)
- Android 10 (LineageOS 17.1)

**Log messages**
```
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: Error during authorization
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: oauth.signpost.exception.OAuthCommunicationException: Error for URL http://id.cweiske.de/?openid.assoc_handle=60806c99000a1a4037b561c0&openid.ax.if_available=ext4%2Cext5%2Cext6%2Cext7%2Cext8&openid.ax.mode=fetch_request&openid.ax.required=ext0%2Cext1%2Cext2%2Cext3&openid.ax.type.ext0=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ax.type.ext1=http%3A%2F%2Faxschema.org%2FnamePerson&openid.ax.type.ext2=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ax.type.ext3=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ax.type.ext4=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffriendly&openid.ax.type.ext5=http%3A%2F%2Faxschema.org%2Fcontact%2Fcity%2Fhome&openid.ax.type.ext6=http%3A%2F%2Faxschema.org%2Fcontact%2Fstate%2Fhome&openid.ax.type.ext7=http%3A%2F%2Faxschema.org%2Fcontact%2Fweb%2Fdefault&openid.ax.type.ext8=http%3A%2F%2Faxschema.org%2Fmedia%2Fimage%2Faspect11&openid.identity=http%3A%2F%2Fcweiske.de%2F&openid.mode=checkid_setup&openid.return_to=https%3A%2F%2Fwww.openstreetmap.org%2Fauth%2Fopenid%2Fcallback%3F_method%3Dpost%26openid1_claimed_id%3Dhttp%253A%252F%252Fcweiske.de%252F%26rp_nonce%3D2021-04-21T18%253A19%253A05ZtadPd3&openid.sreg.optional=postcode%2Cnickname&openid.sreg.required=email%2Cfullname&openid.trust_root=https%3A%2F%2Fwww.openstreetmap.org
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at de.westnordost.streetcomplete.settings.OAuthFragment$OAuthWebViewClient.onReceivedError(OAuthFragment.kt:183)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:337)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at Ve.a(chromium-SystemWebView.apk-default-424011403:1)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at Tv.handleMessage(chromium-SystemWebView.apk-default-424011403:133)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at android.os.Looper.loop(Looper.java:214)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-21 20:19:03.986 14176 14176 E OAuthDialogFragment: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by matkoniecz** [comment]
Hello!

Can you login at https://www.openstreetmap.org/ itself, outside any app?

Login is handled almost completely externally, StreetComplete just shows openstreetmap.org website within app and receives some info from it (in rough summary).

There is an open issue at https://github.com/openstreetmap/openstreetmap-website/issues/3134 - "OpenID Login error" so it seems likely that this login issue is not broken in StreetComplete itself. Maybe you can provide useful info there.

> Since then I could not log in anymore but never managed to file a bug report here.

Horrible workaround, but maybe you can create a new account? (sorry, I had no idea right now for anything better if OpenID is broken)

**Comment by cweiske** [comment]
I can login fine on openstreetmap.org. Never had any problems there.

**Comment by matkoniecz** [comment]
@cweiske 

So, cweiske.de is your own site and registration is not open? Is it maybe possible to setup test account so that I would be able to reproduce error?

**Comment by westnordost** [comment]
The error happens in the [`oauth.signpost`](https://github.com/mttkay/signpost) library. I looked into the current source, and that error is thrown when there is an IOException when trying to communicate with the URL.

@cweiske Are you sure that your log pasted here is complete? The stack trace should be longer - it should also include the stack trace of the IOException that caused OAuthCommunicationException to be thrown.

In any case, it would probably make more sense to post the problem over there.

**Comment by matkoniecz** [comment]
It is likely not a StreetComplete issue, and while I would be happy to test it and report it in some other project right now I lack any required to do this.

See https://github.com/streetcomplete/StreetComplete/issues/2781#issuecomment-824681451

Note https://github.com/mttkay/signpost#oauth-service-providers

> If neither Signpost nor the OAuth service providers out there would be buggy, then Signpost would work with all of them.

It is likely bug in either Signpost or your site.
