### ISSUE TITLE
Update background map with new buildings

### ISSUE THREAD

**Issue by cserpell** [streetcomplete/StreetComplete#2782]
**Use case**
I love using StreetComplete when going out the streets. I noticed many buildings are missing in the map, so I add some notes, and when at home, I add the buildings in the map. After a few days, I go out again, aiming to add the details of those new buildings. Nevertheless, while the new quests appear, the buildings do not. It would be nicer if there is an option to update the base map, in order to better orientate new quests for these new buildings. Otherwise, when many new buildings appear, you don't know which one is the quest asking for.

**Proposed Solution**
I don't know how StreetComplete stores the map/building information that is displayed as background. I would love having a way to easily update it to a newer version, or better if it is done automatically.

**Comment by matkoniecz** [comment]
>  I don't know how StreetComplete stores the map/building information that is displayed as background. I would love having a way to easily update it to a newer version, or better if it is done automatically.

Map in background is from OSM but indirectly (hosting sponsored by JawgMaps - see https://github.com/streetcomplete/StreetComplete#sponsors ).

Like other map displays it is not updating immediately and is not feasible to do this, unless someone has piles of money for super-hosting (and if someone has piles of money for StreetComplete there are better ways to spend it :) ).

Partially see #2479

This specific part will have also noticeable improvements in the next version.

So I will close it as partially unfixable, partially as already done but not released (better description for map cache clearing), partially as possible already as clearing map cache is possible already.

**Comment by cserpell** [comment]
Ï am sorry, now I found #2611 and #2479 regarding the same, it was difficult searching on closed issues. Thanks for the feedback. I will wait for the next version, then!
