### ISSUE TITLE
Include highway=service in surface quest

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2783]
https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddRoadSurface.kt#L60-L64

currently `highway=service` is excluded from the surface quest.

I think we should include it.

Possibly if you're worried about too many quests you could exclude `service=driveway`, which would limit to smaller less important connections from house to street, but still include other service roads like lane ways or alleys.

**Comment by Helium314** [comment]
see #1734

**Comment by andrewharvey** [comment]
I'll close this and comment over there.

**Comment by westnordost** [comment]
Hm okay, let's try it. Include service roads but exclude at least driveways.

**Comment by westnordost** [comment]
But if it reportedly leads to too much spam, it would need to be reverted again. Anyone wants to implement it?

**Comment by HolgerJeromin** [comment]
What about parking aisle?

**Comment by westnordost** [comment]
It's not a dead end way, like a drive through you go in and you go out. I only excluded the dead ends now
