### ISSUE TITLE
[v32.0-alpha] Geometry is not shown when splitting way

### ISSUE THREAD

**Issue by ENT8R** [streetcomplete/StreetComplete#2785]
When trying to split a way in the latest version, the geometry is not visible at all which might lead to confusion...

<img src="https://user-images.githubusercontent.com/25306497/115681460-d6210280-a354-11eb-8e18-3817f24ecbe8.jpg" width="300px">

**Comment by westnordost** [comment]
Thank you, @ENT8R !
