### ISSUE TITLE
Don't ask for tactile paving if kerb=no

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2792]
kerb=no implies there is no kerb edge/roadside so there's nowhere for tactile paving to be

**How to Reproduce**
Create a note similar to [8655918705](https://www.openstreetmap.org/node/8655918705), check on StreetComplete

**Versions affected**
At least 31.3

**Comment by kmpoppe** [comment]
I wonder if this could become a "map maintenance" Quest. Because if someone tags a crossing with `kerb=no` to have tactile paving, it could imply that no is wrong and flush would be the better value - which could be hard to discern?

**Comment by TurnrDev** [comment]
Oooh you've got a point here. kerb=no could trigger "Is there truly no kerb or is it a flush kerb?"

I like it!

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/node/8655918705

> highway = crossing
> crossing = unmarked
> kerb = no

means that there is no kerb. But in such case tactile paving still may be present. Even especially for such places as hint in the form of kerb is missing and it is quite hidden for blind people.

**Comment by matkoniecz** [comment]
![screen07](https://user-images.githubusercontent.com/899988/115828605-39bb3680-a40e-11eb-8752-ffe4a6ad4698.png)


https://www.google.pl/maps/@50.0896216,19.9134498,3a,35.7y,250.76h,70.87t/data=!3m6!1e1!3m4!1sbZxTm1oDwDmm-Wwen7Pm0A!2e0!7i13312!8i6656

https://www.openstreetmap.org/?mlat=50.08960&mlon=19.91341#map=19/50.08960/19.91341&layers=N

example of tactile paving without kerb

> kerb=no implies there is no kerb edge/roadside so there's nowhere for tactile paving to be

seems to be not true. But maybe asking for tactile paving there makes no sense for other reasons?

> Oooh you've got a point here. kerb=no could trigger "Is there truly no kerb or is it a flush kerb?"

what would be tagged on "truly no kerb" answer?

**Comment by TurnrDev** [comment]
Oooh yeah, I keep forgetting that. a quest that doesn't change the data would forever reappear.

I guess you've proved me wrong regarding my assumption too

**Comment by matkoniecz** [comment]
In such case I think it should be fine close it?

**Comment by kmpoppe** [comment]
> what would be tagged on "truly no kerb" answer?

For that we've got `not:kerb=no` - the `not:`-namespace is designed for marking things _really, really, not_ being something even though it might look like it from afar.

**Comment by TurnrDev** [comment]
> > what would be tagged on "truly no kerb" answer?
> 
> For that we've got `not:kerb=no` - the `not:`-namespace is designed for marking things _really, really, not_ being something even though it might look like it from afar.

Surely that would make it a double negative so `kerb=yes`?

**Comment by kmpoppe** [comment]
> Surely that would make it a double negative so `kerb=yes`?

Not necessarily. You could combine `not:kerb=no+kerb=flush` like [on this object's name](https://www.openstreetmap.org/way/371536228)

**Comment by westnordost** [comment]
And how to tag things that are really really *really* not something? 🤔

Am 23. April 2021 10:37:43 MESZ schrieb Kai Michael Poppe ***@***.***>:
>> what would be tagged on "truly no kerb" answer?
>
>For that we've got `not:kerb=no` - the `not:`-namespace is designed for
>marking things _really, really, not_ being something even though it
>might look like it from afar.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2792#issuecomment-825498511

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kmpoppe** [comment]
> And how to tag things that are really really *really* not something? 🤔

Obviously, this has some logical boundaries that might not be automateable through an app like SC and must be changed with complete tag-access to an object.
