### ISSUE TITLE
kort.ch linked in the privacy policy is dead

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2793]
Todo:

* [x] delete wheelmap and kort.ch mentions from privacy policy raw string
* [x] eliminate it on POEditor across all langauges
* [ ] verify that kort.ch is eliminated after the translation update
 
----------

**How to Reproduce**
Open privacy policy. Click Kort link. Get

![screen08](https://user-images.githubusercontent.com/899988/115829329-28bef500-a40f-11eb-860f-5fae3968e254.png)

**Versions affected**
Latest at time of writing ( a51c2a911406edce166bfb621f629ebe91c8f119 ) - https://github.com/streetcomplete/StreetComplete/blob/a51c2a911406edce166bfb621f629ebe91c8f119/app/src/main/res/values/strings.xml#L172

It is probably necessary to change it in the root source, without changing string name and go through all languages to edit them to also remove URL there. Is there a smarter way to do this?

Note that we need to start mentioning also Esri privacy policy but that would be likely done better as an extra string (to not invalidate existing translation and make eventual replacement possible without invalidating privacy policy translations again)

**Comment by matkoniecz** [comment]
Alternative: link site preserved by internet archive but that likely is a bad idea as it points user to a dead project.

**Comment by westnordost** [comment]
Yeah, true. Maybe both wheelmap and kort should be removed. Should be easier to do this also in languages one doesn't know as then the whole second part of the sentence is cut off.
Would you do that?

> Note that we need to start mentioning also Esri privacy policy but that would be likely done better as an extra string (to not invalidate existing translation and make eventual replacement possible without invalidating privacy policy translations again)

This is already implemented. The privacy statement of the `VectorTileProvider` used is added to the privacy policy programmatically. so, part of #2772

**Comment by matkoniecz** [comment]
Removing just Kort should be doable without issues, but I think that whole sentence can be removed without losing anything truly important (and that is supposed to be short explanation of the situation)

>  Would you do that?

Yes

**Comment by matkoniecz** [comment]
Removal was good, because it seems some were translated as

> Everything contributed by StreetComplete is added directly to the OpenStreetmap. There is no intervention by third-party apps. This is also true of <a href="https://wheelmap.org">wheelmap.org</a> or <a href="http://www.kort.ch">Kort</a>. 

(or maybe it is just automatic translator screwing up?)

Ans I see how original text may be understood in this way.

**Comment by westnordost** [comment]
Nice, thank you!

**Comment by matkoniecz** [comment]
So now it is 100% complete.

What remained is to push new English strings to POEditor, though it is not urgent as risk that someone will translate privacy policy right now seems low. I considered doing this but failed to even find script handling this part.

I run translation update from Gradle build script to verify that nothing was missed, fixed also one translation that I missed before.
