### ISSUE TITLE
12h time format seeams to be always used independ of local setting for quest "Do the opening hours still are...?

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#2795]
phone: CAT S30
Android: 5.1
Streetcomplete v31.2 (downloaded from F-Droid)

Issue description:
Independent of the mobile phones local settings for time format (here 24 hour format ) as it is generally used in Germany the app is now showing a slightly confusing/irritating 12 hour format in quest "Do the opening hours still are ?"

example:
since v31.2:   Mo.-Fr. 11:30 vorm.- 6:00 nachm.

In pre v31.2 the opening hours for the example above were still shown as:   Mo.-Fr. 11:30 - 18:00

From version history this behavior was introduced with ticket #2709.

In fact I think this is confusing because when checking opening hours you have to "translate" the used local time format into the time format now used by the app. This can be lead to misunderstanding.

Best regards
ironspock

**Comment by TurnrDev** [comment]
I don't seem to have this issue, I see [a 24-hour clock](https://user-images.githubusercontent.com/11667059/115954050-bae5fc80-a4e6-11eb-9018-1ac0ef7ad749.jpg), however, when I choose to type in the time, the [keyboard refuses to open](https://user-images.githubusercontent.com/11667059/115954084-e36df680-a4e6-11eb-9f7f-36255ae6a87b.jpg).

I'm using 31.3 installed via Google Play Store

**Comment by ironspock** [comment]
just to clarifiy the issue, please find enclosed a screenshot
![Screenshot_2021-04-24-11-31-33](https://user-images.githubusercontent.com/68661025/115954458-790e8380-a4f1-11eb-8dee-6d78b32cdd3f.png)

**Comment by westnordost** [comment]
Can you please also post a screenshot how the dialog looks for you? 

Am 24. April 2021 11:38:44 MESZ schrieb ironspock ***@***.***>:
>just to clarifiy the issue, please find enclosed a screenshot
>![Screenshot_2021-04-24-11-31-33](https://user-images.githubusercontent.com/68661025/115954458-790e8380-a4f1-11eb-8dee-6d78b32cdd3f.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2795#issuecomment-826065542

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
I mean the "select a time range now" dialog

**Comment by ironspock** [comment]
The "select time range now" is still the 24-hours clock as before.
The reported issue is mainly related to the time representation as per screen shot above. The same time presentation (12 hour format as per screenshot) occurs after selecting a new/change time range.
This screenshot is showing a very basic/simple time range to check. But having complex time settings (including times around/past  midnight) it will be a "challenge" to check for someone not being used to the american/english time representation.

**Comment by westnordost** [comment]
Did you check your android system settings? You can select in the settings whether you want hours represented in 12-hour format or 24-hour format.

**Comment by ironspock** [comment]
Had a quick check.. It is/always was 24 hour.
To be sure I just changed the system settings to 12 hour with a check in App (now 12 hour clock was shown).
After resetting the system settings to 24 hour the time representation in App is now again as expected.
... strange behavior...
Ticket can be closed.
