### ISSUE TITLE
Has the name of this bus stop changed?

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2797]
I've noticed that a few bus stops near me have changed names, so figured that would be a good thing to ask for occasionally.

I don't think bus stops are likely to change names very often, so maybe only ask every 5/6 years.
The name quest is by default above all other bus stop quests, so they wouldn't affect the age of the element being changed going forward.

I see it working the same as other maintenance type quests, in that if the name already exists the quest would change to asking "Is this still the name of this bus stop?" and the previous name would be auto filled.

I'm happy to implement this, but just checking if it would be wanted and getting some feedback.

**Comment by matkoniecz** [comment]
In area where I edit such changes occasionally happen, but are rare with vast majority not changing.

And such changes being mapped by editors in general on their own.

Similarly to street names.

**Comment by westnordost** [comment]
Same opinion as @matkoniecz. That happens quite rarely and if it does, then they often also change location. Something that cannot be corected with SC.

**Comment by arrival-spring** [comment]
Fair enough

**Comment by peternewman** [comment]
I was going to suggest this could be covered by bus stop existence, but in the UK at least even that is somewhat complicated, see https://github.com/streetcomplete/StreetComplete/issues/2566

**Comment by BalooUriza** [comment]
On Sun, Apr 25, 2021 at 5:51 AM arrival-spring ***@***.***>
wrote:

> I've noticed that a few bus stops near me have changed names, so figured
> that would be a good thing to ask for occasionally.
>
I could see this as being useful for checking bus stop refs, too. I feel
like tying this to the mean interval for system changes should be good, but
we'd need to work out what a meaningful average time for transit agencies
to change things up would be.  My experience with Trimet and Tulsa Transit
suggests they make major changes annually.
