### ISSUE TITLE
source:maxspeed quest in Belgium

### ISSUE THREAD

**Issue by Vakonof** [streetcomplete/StreetComplete#2798]
Belgium consists of 3 regions: Flanders (VLG), Wallonia (WAL) and the Brussels Capital Region (BRU). Each of them have different default max speeds. (urban maxspeed of 50 km/h in Flanders and Wallonia, 30 km/h in Brussels and rural maxspeed of 70 km/h in Flanders and Brussels, 90 km/h in Wallonia)

Thus, the max speed sources for urban and rural areas are tagged as `source:maxspeed=BE-VLG:*`/`BE-WAL:*`/`BE-BRU:*` as also listed on the [Wiki](https://wiki.openstreetmap.org/wiki/Key:maxspeed#Implicit_maxspeed_values).
 
`source:maxspeed=BE-VLG:*`/`BE-WAL:*`/`BE-BRU:*` have 20809 combined usages
`source:maxspeed=BE:*` has 2606 combined usages

**EDIT: it isn't `source:maxspeed=` that gets added by StreetComplete, but `maxspeed:type=`, but the same reasoning still applies**

**Expected result**
For example when adding a max speed source to an urban road in Flanders, `source:maxspeed=BE-VLG:urban` should be added.

**Actual result**
Generic `source:maxspeed=BE:urban` gets added.

**Versions affected**
SC v31.3, Android 11

**Comment by westnordost** [comment]
Hm ok, then the quest should probably be disabled in Belgium because the app does not have this information (where in Belgium any given way is located).

**Comment by peternewman** [comment]
That sounds like the short term, is the long term not to mark this as a blocker, and get the JOSM data fixed so it can do the regions, or does SC not use the regions, I see this lists US-TX as an example:
https://github.com/westnordost/countryboundaries#usage

@Vakonof here is the data from JOSM that countryboundaries (and hence SC) is using:
```
  <relation id='-29660'>
    <member type='way' ref='-28940' role='outer' />
    <member type='way' ref='-29432' role='outer' />
    <member type='way' ref='-29434' role='outer' />
    <tag k='ISO3166-1:alpha2' v='BE' />
    <tag k='maxspeed:living_street' v='20' />
    <tag k='maxspeed:motorway' v='120' />
    <tag k='maxspeed:rural' v='90' />
    <tag k='maxspeed:source' v='http://ec.europa.eu/transport/road_safety/going_abroad/belgium/speed_limits_en.htm' />
    <tag k='maxspeed:source2' v='http://www.code-de-la-route.be/textes-legaux/sections/ar/code-de-la-route/170-art11-v15-170' />
    <tag k='maxspeed:source3' v='http://www.code-de-la-route.be/textes-legaux/sections/ar/code-de-la-route/182-art22bis' />
    <tag k='maxspeed:urban' v='50' />
    <tag k='name:en' v='Belgium' />
    <tag k='type' v='multipolygon' />
  </relation>
```

It looks from that that JOSM would be getting the wrong speeds too.

I think @westnordost has previously said SC doesn't tag the actual speed, so it would just need to know the region details (and perhaps some logic to decide which countries to use the region and which to use the country), see also #2725 .

Although if I'm reading 36f9301cd28f4809707ee7137b588050f8c56845 right, I assume all the subdivisions and FX/EU have been stripped out of  app/src/main/assets/boundaries.ser

**Comment by westnordost** [comment]
Yes, in theory if that JOSM boundaries file would also get the boundaries for the subregions of Belgium, in theory I could implement that. But to be honest, I want to put the least amount of effort into the maxspeed quest.

> Although if I'm reading 36f9301 right, I assume all the subdivisions and FX/EU have been stripped out of app/src/main/assets/boundaries.ser

No, just FX and EU.

**Comment by peternewman** [comment]
> Yes, in theory if that JOSM boundaries file would also get the boundaries for the subregions of Belgium, in theory I could implement that. But to be honest, I want to put the least amount of effort into the maxspeed quest.

Fair enough, I guess someone from Belgium could volunteer.

@Vakonof might be interested in fixing/reporting what appears like it will probably be incorrect tagging by JOSM anyway.

> > Although if I'm reading [36f9301](https://github.com/streetcomplete/StreetComplete/commit/36f9301cd28f4809707ee7137b588050f8c56845) right, I assume all the subdivisions and FX/EU have been stripped out of app/src/main/assets/boundaries.ser
> 
> No, just FX and EU.

Ah okay, I was just guessing based on the relatively large amount of changes.

**Comment by hgcvm** [comment]
Issue was also reported in https://github.com/streetcomplete/StreetComplete/issues/1216

**Comment by westnordost** [comment]
Hm, looks like my opinion on this got softer over time. Or, I willingness to quarrel with the maxspeed-scheme went down.

Anyway, my current stance would be to remove the quest for Belgium. But if any of you would like to ask whats the opinion on that in the Belgian community first, then I'll wait with this.

**Comment by westnordost** [comment]
ping

**Comment by Vakonof** [comment]
I asked in the Belgian Matrix channel. They are in favor of keeping the quest activated as it is, and manually changing the tags.

**Comment by westnordost** [comment]
Cool, thanks for the feedback
