### ISSUE TITLE
Keyboard doesn't appear when using the time input fields in the opening hours quest

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2799]
Hi there,

@TurnrDev's comment (https://github.com/streetcomplete/StreetComplete/issues/2795#issuecomment-826063895) inspired me to try it out myself and found out that this issue doesn't occur with each time picker:

**How to Reproduce**

- Find an **opening hours** quest and open the associated time picker.
- Instead of choosing the time from the time picker, tap on the keyboard icon. A form with two fields (hour/minute) appears.
- Tap into one of the two fields. You would expect the (numeric) keyboard to appear, but nothing happens. It's impossible to enter a time here, you have to go back to the time picker by tapping on the clock icon.

However, this bug does **not** appear with the time picker of the **post box collecting times** quest. Here the keyboard appears as expected.

**Versions affected**

Tested with two devices with Android 8.1 and 9.0 repectively. SC v31.3 on each.

The cycling cat

**Comment by westnordost** [comment]
I suspect some Android fuckery that needs to be worked around.

**Comment by cyclingcat** [comment]
After all it's conspicious that one quest shows this bug while another doesn't. Maybe some other participants with different devices and Android flavours/versions could test if they get this effect too?

The cycling cat

**Comment by mnalis** [comment]
I can confirm both points (failure of keyboard to pop up on _**opening hours**_ quest, but opening normally on **_postbox collection times_** quest. On Huawei P30 Pro,  EMUI 11 (Android 10), StreetComplete v31.3

**Comment by riQQ** [comment]
Same for me, Android 10 / Nokia 2.2 / StreetComplete 31.3

**Comment by mnalis** [comment]
Interestingly, that same SC v31.3 (from f-droid) **does not show** the keyboard icon at all on older Xiaomi Redmi Note 3 pro with MIUI 10.2 (Android 6.0.1). 

But it also shows difference between _**opening hours**_ and **_postbox collection times_** quests: former shows android time picker with 12hour am/pm, and latter show 24hour variant (which was mentioned in some other issue IIRC), even after full uninstall / install SC cycle.

**Comment by westnordost** [comment]
> But it also shows difference between opening hours and postbox collection times quests: former shows android time picker with 12hour am/pm, and latter show 24hour variant (which was mentioned in some other issue IIRC), even after full uninstall / install SC cycle.

Oh, that's a bug. Can you create a report for that?

**Comment by smichel17** [comment]
On Android 7.0 I can't find where there's the option to do keyboard entry at all :shrug:
Tapping on the numbers changes between minutes and hours (setting an hour also swaps to minutes).
<img src="https://user-images.githubusercontent.com/6563664/116144306-b6c70400-a6cb-11eb-8c89-f528d4ccf908.png" height="400" alt="Date picker for postbox collection quest, in debug version of the app" />

**Comment by westnordost** [comment]
That's a feature that was added only in later android versions

**Comment by westnordost** [comment]
Just going to ping @tapetis here as he often knows the correct answer/workaround to Android-related issues 😄
