### ISSUE TITLE
OSM link display sometimes broken(?)

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#2801]
The display of links in your profile was broken and did not display any links.
I found this by swiping through these screens a lot of times (all other ones work, e.g. the country ones or the most solved quests).
I could even close the menu and go back to it, so it was no temporary display bug.

The app is an old installation I just upgraded.

At another try after I locked my screen and when I was just about to reproduce this when writing this issue/for this issue, the links had suddenly appeared again…

**How to Reproduce**

Go to the menu “My profile” at the right panel.

It displayed “You have no links yet” or so.

**Versions affected**

v31.3 from F-Droid

**Comment by westnordost** [comment]
I remember seeing this too and looking into it too, but I never was able to reproduce it reliably.

**Comment by rugk** [comment]
With which version, would probably be a good question to ask first to try to isolate the issue.

**Comment by westnordost** [comment]
With many versions
