### ISSUE TITLE
Steps quest asking should not be interrupted by 

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#2802]
**Use case**

These step quests are not asked together usually for steps:
![grafik](https://user-images.githubusercontent.com/11966684/116008278-077b2600-a614-11eb-9fc7-31e53d24dbce.png)

Because usually, when you never surveyed a step with StreetComplete (SC), all quests are needed to be completed.
And of course it’s also quite efficient to answer all of them together while you are at that step.

The problem is that these quests are interrupted by one big – very popular (often shown) – quest:
> Is this stretch of way lit?

![](https://wiki.openstreetmap.org/w/images/thumb/4/49/StreetComplete_quest_streetlight.svg/138px-StreetComplete_quest_streetlight.svg.png)

**Proposed Solution**

All steps quests should be asked together.
The problem is users are unlikely (at least I felt so) to answer the lit quest, so they could complete the other useful quests.

As such, I’d propose to change the order.

**Comment by westnordost** [comment]
No I think it is more important to keep the order roughly in the order of value of this information rather than that all quests that ask about a similar feature are together.

**Comment by andrewharvey** [comment]
The value of information is subjective and depends on your use case, but regardless @rugk you can re-order the quests in the settings to move the lit quest down and the steps up to change priority.

**Comment by matkoniecz** [comment]
Also, see  "Show all quests for element at once" at #124 - open and waiting for implementation of someone is interested

**Comment by TurnrDev** [comment]
> you can re-order the quests in the settings 

OH MY GOD. I with I knew this sooner! Best hidden feature
