### ISSUE TITLE
Improve check existence quest wording

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2806]
**Use case**
Current wording:
https://github.com/streetcomplete/StreetComplete/blob/79d78db7c905d87a9a80260d8bdf2be53a34daa1/app/src/main/res/values/strings.xml#L449-L450

The quest will ask using arguments (name, featureName.value), where name will be the first of ("name", "ref", "brand", "operator"). So if you imagine Google started installing benches everywhere, and they were tagged with some combination of:
```
amenity=bench
name=Sergey's Seat
ref=600913
brand=Google
operator=Google RESTful
```

Giving these possible results:
```
Is this still here? (bench)
Is Sergey's Seat still here? (bench)
Is 600913 still here? (bench)
Is Google still here? (bench)
Is Google RESTful still here? (bench)
```

**Proposed Solution**
IMHO, these work for big brands where the name/brand thing is what they're known for, e.g. McDonald’s, but doesn't where it's not the main thing they are known for as in these examples, or e.g. a BT phonebox or Royal Mail postbox.

I was going to just do a PR, but given there are a few options, some other input might work (and maybe some consideration of how they translate).

I think one of these options would be clearer:
For the unnamed one:
```
Is this %s still here?
Is this bench still here?
```

Or if you really want to keep the brackets:
```
Is this (%s) still here?
Is this (bench) still here?
```
For the named ones:
```
Is %1$s %2$s still here?
Is Sergey's Seat bench still here?
Is 600913 bench still here?
Is Google bench still here?
Is Google RESTful bench still here?
```

Or (slightly longer):
```
Is this %1$s %2$s still here?
Is this Sergey's Seat bench still here?
Is this 600913 bench still here?
Is this Google bench still here?
Is this Google RESTful bench still here?
```

Alternative (I think this is my preferred choice):
```
Is this %2$s (%1$s) still here?
Is this bench (Sergey's Seat) still here?
Is this bench (600913) still here?
Is this bench (Google) still here?
Is this bench (Google RESTful) still here?
```
I'm assuming the substitution would let you just do this and swap the order in the translation?

**Comment by matkoniecz** [comment]
> Is this %s still here?

Te problem here is with translations, and confusing translators ofheavily declined languages. For example in Polish equivalent of "this" is declined and you need to say:

bench (word "bench" is feminine in Polish): Czy **ta** ławka nadal tu jest? 

but for telephone (work "telephone" is masculine in Polish): Czy **ten** telefon nadal tu jest?

See https://en.wikipedia.org/wiki/Polish_grammar#Gender

The same happens in German at least.

**Comment by peternewman** [comment]
> > Is this %s still here?
> 
> Te problem here is with translations, and confusing translators ofheavily declined languages.

> The same happens in German at least.

Ah yes, I'd blanked my der, die, das, die from my mind somehow!

So does `Is %1$s %2$s still here?` work in Polish/German?

> Version with brackets is less ugly, as there is no sentence with obviously broken language and that weird construction actually helps.
> 
> (just explaining reasons for that)

Sorry you're for or against the brackets? And with which word in brackets.

The one that really jars with me is:
`Is BT still here? (telephone)`

Which makes no sense in English.

I guess we could make use of the translations (assuming the substitution lets you swap the order) and just fix the non-gendered languages and leave a note in POEditor.

Or try and get the gender of the objects added to the ID presets...

**Comment by westnordost** [comment]
> Or try and get the gender of the objects added to the ID presets...

I guess this would be theoretically possible. In a precursor to the iD presets (a private project, I think I deleted this in the meantime from github) that was the plan initially. But for each individual language, there would need to be some code to properly refer to it in the different grammatical cases. I figure this would be a huge effort.

**Comment by matkoniecz** [comment]
> So does Is %1$s %2$s still here? work in Polish/German?

In Polish "Czy ławka/telefon/sklep "`name`" nadal tu jest?" seems to be working

**Comment by westnordost** [comment]
Anyway, I don't think anything can be done about making this better.

**Comment by westnordost** [comment]
(In German, it isn't working)

> Ist Telefonzelle "BT" noch hier?

the "die ..." is missing.

**Comment by peternewman** [comment]
> > Or try and get the gender of the objects added to the ID presets...
> 
> I guess this would be theoretically possible. In a precursor to the iD presets (a private project, I think I deleted this in the meantime from github) that was the plan initially. But for each individual language, there would need to be some code to properly refer to it in the different grammatical cases. I figure this would be a huge effort.

Yeah I'd agree that certainly wouldn't be easy, I might see what the iD people think as it could presumably improve the clarity of their messages too.

> Anyway, I don't think anything can be done about making this better.

Maybe not in every language, but "Is this BT telephone still here?" is an improvement in English without even changing the order.

And if you can use the numbered references to swap the order then in Polish @matkoniecz confirms that "Czy ławka/telefon/sklep "name" nadal tu jest?" works too. So that could be set in POEditor as `Czy %2s "%1s" nadal tu jest?`

**Comment by westnordost** [comment]
Yeah as said, this does not work in German.

**Comment by peternewman** [comment]
So don't touch the German translation then; I'm a bit confused why we can't improve the others because of that?

"Is BT still here? (telephone)" does not work in English. BT is almost an adjective for the telephone, so it's like saying "Is red still here? (telephone)" or "Where is the nearest red? (telephone)"

We could always add a comment in the file and/or in POEditor so people don't forget about the gender of words.
https://github.com/streetcomplete/StreetComplete/blob/a4ef00f7bdc973d1ac7e6bf1af88f832abcf952b/app/src/main/res/values/strings.xml#L733-L736

**Comment by westnordost** [comment]
A lot of strings would need to be changed then, wouldn't they? This pattern "Is X? (Y)" is used in quite a lot of quests.

**Comment by matkoniecz** [comment]
Still, if that is an improvement for English text and changes could be made without invalidating all translations, maybe it would be a good idea?

Not sure how translators can be made aware that they are free to use quotes trick if their language requires this, like in German.

**Comment by peternewman** [comment]
> A lot of strings would need to be changed then, wouldn't they? This pattern "Is X? (Y)" is used in quite a lot of quests.

So having a look, it's used in the following:
```
grep \(% app/src/main/res/values/strings.xml | grep -v streetName
    <string name="quest_openingHours_name_type_title">"What are the opening hours of %1$s (%2$s)?"</string>
    <string name="quest_openingHours_no_name_title">"What are the opening hours of this place? (%s)"</string>
    <string name="quest_openingHours_resurvey_name_type_title">"Are these opening hours for %1$s (%2$s) still correct?"</string>
    <string name="quest_openingHours_resurvey_no_name_title">"Are these opening hours still correct (%s)?"</string>
    <string name="quest_placeName_title_name">"What is the name of this place? (%s)"</string>
    <string name="quest_wheelchairAccess_name_type_title">Is %1$s (%2$s) wheelchair accessible?</string>
    <string name="quest_existence_title">Is this still here? (%s)</string>
    <string name="quest_existence_name_title">Is %1$s still here? (%2$s)</string>
    <string name="quest_accepts_cash_type_title">"Does %1$s (%2$s) accept cash payment?"</string>
    <string name="quest_charging_station_name_capacity_title">"How many cars can be charged at this charging station (%s) at the same time?"</string>
    <string name="quest_drinking_water_title">Is the water potable here? (%s)</string>
```

quest_openingHours_name_type_title, quest_wheelchairAccess_name_type_title and quest_accepts_cash_type_title all end up as McDonalds (Fast Food).

Looking at the others, even changing to `Is %1$s (%2$s) still here?` or `Is this still here? %1$s (%2$s)` would be a lot less jarring than the current option IMHO.

I can't really tell you why, but McDonalds or Tesco or whatever just seem naturally fine on their own (without necessarily needing the fast food/supermarket clarification), I don't know if it's because they're common, oddly if you asked me "Is this Shell still here? (petrol station)" I'd probably be fine with it (although I'd prefer "Shell garage"), but I can't really say why. I guess the branding of shops etc is far more obvious than telephones or post boxes or car charging points or toilets (or perhaps for at least the first two it's not the primary operation of the company and hence not what they're known for).

> Not sure how translators can be made aware that they are free to use quotes trick if their language requires this, like in German.

In the POEditor CSV import you can add comment, context and reference but none of that seems to exist in Android so I guess you'd need to add it manually (which seems to happen naturally via comments in my experience when people are unsure).

**Comment by westnordost** [comment]
> In the POEditor CSV import you can add comment, context and reference but none of that seems to exist in Android so I guess you'd need to add it manually (which seems to happen naturally via comments in my experience when people are unsure).

It's possible to just add a comment above the string in the strings.xml

However, if "Is %1$s still here? (%2$s)" is simply changed to "Is %1$s (%2$s) still here?", I think a comment is probably not even necessary.

**Comment by mnalis** [comment]
Out of curiosity, if English version of text is changed (or if such a comment were to be added), do translators get any kind of notification?
(for new strings, I see them pop up in "Untranslated" on POeditor, but for modified texts I don't think so?)
Is there a way to mark them as fuzzy automatically, or indicate in some other way then need checking up and maybe modifying?

**Comment by westnordost** [comment]
> Out of curiosity, if English version of text is changed (or if such a comment were to be added), do translators get any kind of notification?

When importing new strings to POEditor, I can select whether to mark all updated translations in all languages as fuzzy, or not.
In this case, I'd probably not mark them as fuzzy (but maybe look at all translations of this particular string by hand and change the format)

**Comment by peternewman** [comment]
> It's possible to just add a comment above the string in the strings.xml

Yeah I'd seen the comments, I assumed you were manually importing/exporting them as they aren't mentioned on their help.

> However, if "Is %1$s still here? (%2$s)" is simply changed to "Is %1$s (%2$s) still here?", I think a comment is probably not even necessary.

:+1: 

To be clear, I'd rather have "Is %1$s %2$s still here?" with a comment in POEditor if required, but "Is %1$s (%2$s) still here?" is a reasonable compromise.
