### ISSUE TITLE
SC Creates wrong notes (photos are not available in note)

### ISSUE THREAD

**Issue by pawlosck** [streetcomplete/StreetComplete#2808]
Create any note with photo.
- Notes are created as anonymous user.
- photos are not available in note. Server return error 404

For example: https://westnordost.de/p/38938.jpg

SC 31.3
Android: 9.0

Similar issue from 2019

**Comment by westnordost** [comment]
Always reproducible?

**Comment by pawlosck** [comment]
Yes. I created today a lot of notes and all were created as anonymous user and all photos are not available. Link is available in note, but server return 404.

**Comment by westnordost** [comment]
How did you upload the note creations as an anonymous user?

**Comment by pawlosck** [comment]
Note was created as anonymous user, but I created using SC.

**Comment by westnordost** [comment]
You mean, you created the note, then you logged in and then you uploaded it?

**Comment by pawlosck** [comment]
No. I am all time logged in SC. The same time, I tried to answer for normal questions an it looks correctly.

**Comment by westnordost** [comment]
Ah okay, so you didn't create the note as an anonymous user, but logged in into your OSM account.

**Comment by pawlosck** [comment]
Yes. I tried to use SC as always, but creating notes is broken.

**Comment by westnordost** [comment]
I can't reproduce this:
https://www.openstreetmap.org/note/2639597#map=18/53.54779/10.00149&layers=N

**Comment by westnordost** [comment]
...which means that this is likely the same issue as #2102 which will be fixed/mitigated in the next major version.

**Comment by pawlosck** [comment]
https://www.openstreetmap.org/note/2639496

**Comment by pawlosck** [comment]
So, could you tell me, why notes were created as anonymous user?

**Comment by westnordost** [comment]
They were? I didn't notice that. What is the link again?

**Comment by pawlosck** [comment]
This note and other next to Dolnobrzeska street.
https://www.openstreetmap.org/note/2639496#map=18/51.15267/16.86645&layers=N

**Comment by westnordost** [comment]
Hm TBH I have no idea. The notes are from you?

The code is like this:

```
            // let's fail early in case of no authorization
            if (!userController.isLoggedIn) {
                throw OsmAuthorizationException(401, "Unauthorized", "User is not authorized")
            }

            Log.i(TAG, "Starting upload")

            ...
```

Whatever wrong happened there, I think you are the first to encounter this and likely the easiest solution would be to log out and then log in again.

**Comment by pawlosck** [comment]
Yes, these notes are mine. I will try to log out and maybe tomorrow or next days I will try it again.

**Comment by matkoniecz** [comment]
Caused by https://github.com/openstreetmap/openstreetmap-website/issues/3184 which will also break commenting in some cases

**Comment by mnalis** [comment]
Seems to be solved now in https://github.com/openstreetmap/openstreetmap-website/issues/3185
