### ISSUE TITLE
Option Restore hidden tasks does not restore hidden notes

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#2810]
If i select the option restore hidden tasks, all hidden tasks except the hidden notes are restored. I would have expected that notes are tasks too. Thus i would have expected to see them again on selecting the aforementioned option. 

Can't notes be made visible again once hidden?

**How to Reproduce**
Hide a note. Go to settings and select the option to restore hidden tasks.

**Versions affected**
Android 11, SC v31.3

**Comment by westnordost** [comment]
Okay, whatever the behavior was for v31.3, it is definitely both restore quests + note quests with v32 now
