### ISSUE TITLE
Adding photo to note should allow uploading photos already taken

### ISSUE THREAD

**Issue by daniel-j-h** [streetcomplete/StreetComplete#2813]
**Use case**

When long pressing the map and adding a note, the user can attach a photo.

Clicking on the "adding a photo" button gets the user into a camera view, but does not allow to upload a photo already taken e.g. ten minutes ago. It would be great if the user not only has the option to take a picture on the spot, but can select an image from the gallery.

**Proposed Solution**

For some reason the camera view is restricted to taking photos, but does not allow the user to select a photo already taken before. Is this on purpose? What are the reasons behind this? To not allow for random photos to be uploaded? Or do we need to control the photo's metadata?

Ideally the user could take a photo on the spot, or select a photo taken a while ago, too.

Thoughts?

**Comment by daniel-j-h** [comment]
Adding how I came across this: I was out in a rush and have seen a new shop where a cafe used to be. I quickly double-pressed the power button to get me into the camera app, and took a picture. Ten or so minutes later when I was still out on the go but had a bit of free time, I wanted to add a note with this picture included. This was not possible.

**Comment by mnalis** [comment]
It had been suggested before, see https://github.com/streetcomplete/StreetComplete/issues/1730#issuecomment-719114321 and https://github.com/streetcomplete/StreetComplete/issues/1567#issuecomment-531736725 why it is not likely to be implemented (even though it would be useful sometimes)

**Comment by westnordost** [comment]
Right, so it is a duplicate.
