### ISSUE TITLE
[already in v31] at least some flags are overly stretched horizontally

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2819]
![screen](https://user-images.githubusercontent.com/899988/116454252-13f3be80-a860-11eb-8e8d-16684cdbde3a.png)

**How to Reproduce**
Edit in Israel/Cyprus, login, view flag screen
**Versions affected**
v31, v32

**Comment by peternewman** [comment]
Does it render correctly when you tap on it?

It's centre:
https://github.com/streetcomplete/StreetComplete/blob/4626f5eb5d277ebb77412d0b59ef01ddb7eb19b1/app/src/main/res/raw/flag_alignments.yml#L114

i.e.
https://github.com/streetcomplete/StreetComplete/blob/6bb4e0c11ee109262d26f4473a4c14375729f3d7/app/src/main/java/de/westnordost/streetcomplete/user/CircularFlagView.kt#L109-L112
https://github.com/streetcomplete/StreetComplete/blob/6bb4e0c11ee109262d26f4473a4c14375729f3d7/app/src/main/java/de/westnordost/streetcomplete/user/CircularFlagView.kt#L116

The numbers all look plausible to me from a quick play.

**Comment by westnordost** [comment]
When you tap on it, it's not the CircularFlagView anymore

**Comment by westnordost** [comment]
But anyway, Peter is on the right track here. The configuration seems correct, there must be some bug in CircularFlagView. To try to reproduce, I'd probably create a simple test fragment that I can open from the settings or so in which only one CircularFlagView of my choosing is displayed
