### ISSUE TITLE
UK NaPTAN data matching verification quest

### ISSUE THREAD

**Issue by kymckay** [streetcomplete/StreetComplete#2823]
### General
Affected tag(s) to be modified/added: [naptan:verified](https://wiki.openstreetmap.org/wiki/Key:naptan:verified), [check_date](https://wiki.openstreetmap.org/wiki/Key:check_date) (proposing new `check_date:naptan` suffix)
Question asked: **Are any of the following codes signed on this bus stop?**

I wanted to break this off from #2566 to keep issues focused to one specific task as I think https://github.com/streetcomplete/StreetComplete/issues/2566#issuecomment-828383425 nicely deals with the unmarked bus stops part of verification.

This issue intends to propose a quest to deal with verifying that the naptan data is matched to the right stop to begin with (for the signed physical stops only). Why must this be done:
1. The original data itself isn't always correct (either mismatched primary keys from what's on the ground or incorrect about the bus stop still existing)
2. Conflation with OSM elements during import processes may have mismatched elements when stops are close together

Context: In the NaPTAN data set both the `naptan:AtcoCode` and `naptan:NaptanCode` (as they're tagged in OSM) can individually be considered as a primary key for a bus stop. All other `naptan:` related tags are irrelevant as far as we need to be concerned since the primary keys provide the link for future re-import or for data consumers to use the source data. We just need to verify that the keys tagged match what's on the ground.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (unsure, see implementation below)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Bus stop name would need to be shown somewhere for identification if there are a few close together

1. Present buttons with the codes and an extra "none of the above"
2. If user chooses a code, remove `naptan:verified=*` tag if present and add a `check_date:naptan=*` tag. We can assume that if one `naptan:` code is present the corresponding one is correct too (discrepancies there are a concern for importers/data users not SC users).
3. If user chooses that none of the codes match,  ??? - this is the tricky part, ideally they could enter the codes that are present and another mapper familiar with the data could later review them and decide what to do, is opening a note an option?
4. There would need to be another option for "can't answer this" to say "no bus stop exists here by that name"

**Element selection:** 
Find `highway=bus_stop` elements that have either or both of `naptan:AtcoCode`/`naptan:NaptanCode` tagged (note we're ignoring `naptan:verified` as due to miscommunication around how it should be used we can't assume meaning)

**Metadata needed:** 
UK only quest

**Proposed GUI:**

**Comment by TurnrDev** [comment]
Might I suggest `naptan:verified=yes` - it's already an established tag with roughly the same number other uses as removing the tag. It's more explicit too. I know the original suggestion was to remove the naptan:verified tag, but I feel this works better.

[`no`](https://taginfo.openstreetmap.org/tags/naptan%3Averified=no#chronology) lost about 20k uses in the past 12 years
[`yes`](https://taginfo.openstreetmap.org/tags/naptan%3Averified=yes#chronology) gained about 11k uses in the past 12 years

I can't say for sure, but it looks like explicitly setting the value to yes is actually more common than removing the tag entirely. 

Also, my explicitly setting the value to yes, we can ensure the tag was intentionally changed and **not** removed my somebody unsure of the tags meaning. I recently removed thousands of incorrect usage of naptan tags outside the UK, so it's not uncommon for these tags to not be understood.

**Comment by TurnrDev** [comment]
I'm all for a `check_date:naptan` tag however. Sometimes bus stops move and then a new bus stop with a new ID ends up in the location of an old bed stop.

**Comment by kymckay** [comment]
The issue I see with continuing to use the `naptan:verified` tag at all is the intended original use has not been followed and so it's unclear what it semantically means when people tag it (are people marking at by verifying the codes as this quest seeks to verify or are they checking other naptan values or simply just checking if the stop exists).

A `check_date` tag has a clear meaning and provides more information than a boolean value. In fact, `check_date:naptan` may be a bad idea for similar unclear semantic reasons, it should probably be even more specific with `check_date:naptan:(AtcoCode|NaptanCode)=*` (depending which the user chooses). This explicitly confirms what was surveyed on the ground.

**Comment by 10992-osm** [comment]
Just a thought, but what would be tagged if neither of the codes is signed on a bus stop that is physically present?  What if no alternative code is available either?

I know that many bus stops near me don't have the code marked, in terms of timetable they just have a PDF timetable printed off on A4 from the operator's website.

**Comment by kymckay** [comment]
@10992-osm A great question, and honestly I have no immediate answer for it. However that's part of the reason to open this issue, it may be that such a quest isn't feasible and we figure that out through conversation here.

Do the stops near you have a short code on the sign at the top of the stop pole/shelter? If I'm remembering correctly, all of the stops in Aberdeen have that and it's actually the suffix part of the AtcoCode (which is made up of an area code prefix and stop code suffix) which can be used to identify the stop. Not sure if that's a regional thing.

**Comment by 10992-osm** [comment]
> @10992-osm A great question, and honestly I have no immediate answer for it. However that's part of the reason to open this issue, it may be that such a quest isn't feasible and we figure that out through conversation here.
> 
> Do the stops near you have a short code on the sign at the top of the stop pole/shelter? If I'm remembering correctly, all of the stops in Aberdeen have that and it's actually the suffix part of the AtcoCode (which is made up of an area code prefix and stop code suffix) which can be used to identify the stop. Not sure if that's a regional thing.

The nearest stop to where I am currently sitting has a flag which only gives the name of the local council, a bus icon and the words "Bus stop".  (It's also currently rotated to be parallel to the road, but that's not terribly relevant, it just needs to be reported to the council).  In the timetable case is a printout from the bus company for 1 of the 3 routes that serve the bus stop.  The timetable only lists timing points, and this particular stop is not a timing point.

The equivalent stop in the other direction (as listed on bustimes.org, ergo NaPTAN) doesn't exist in any sense: no bus stops there (even though they're timetabled to), there is no flag, no road marking, no raised paving, no safe place to stop (it's in a parking bay). There are quite a few stops like this that don't even have their name listed.  Some other bus stops near me have their own customised timetables.  I seem to recall there is a reference number in one of the corners, and I think it's an AtcoCode, but I'll have to check.  Some of them list the NaPTAN code, but these might be in a different council area.  Definitely in the adjacent council area, on the timetable it advertises Traveline's SMS service that you text the NaPTAN code to.

**Comment by TurnrDev** [comment]
> Do the stops near you have a short code on the sign at the top of the stop pole/shelter? If I'm remembering correctly, all of the stops in Aberdeen have that and it's actually the suffix part of the AtcoCode (which is made up of an area code prefix and stop code suffix) which can be used to identify the stop. Not sure if that's a regional thing.

Definitely regional, stops with regular services here (Thanet, Kent) will show the NaptanCode (Not the AtcoCode) but some stops which aren't regular won't have any code or name on the sign.

**Comment by Cj-Malone** [comment]
[bustimes.org](https://bustimes.org/) isn't the best way to visualise NaPTAN.

For instance, take this [one](https://bustimes.org/stops/021014841) as an example. The website says nothing about it other than times, when in NaPTAN it is actually defined as a hail and ride bus stop, between [here](https://www.openstreetmap.org/?mlat=51.91711&mlon=-0.67914#map=19/51.91711/-0.67914) and [here](https://www.openstreetmap.org/?mlat=51.91864&mlon=-0.67667#map=19/51.91864/-0.67667). In reality hail and ride bus stops aren't marked, they don't have a flag, a shelter, a time table, or a stopping point.

As for this quest, how frequently is NaPTAN wrong? Maybe our 10 year old import is wrong, but even then, of the ones where I've check reference codes, they seem remarkably accurate. I think we can clean this is a part of NaPTAN data remotely.

**Comment by TurnrDev** [comment]
> As for this quest, how frequently is NaPTAN wrong? Maybe our 10 year old import is wrong, but even then, of the ones where I've check reference codes, they seem remarkably accurate. I think we can clean this is a part of NaPTAN data remotely.

I've been using `souce:date` and `naptan:RevisionNumber` to show what revision an osm element using using regarding naptan data. In me quest of updating NaPTAN data in Kent, I've noticed some stops have moved drastically since the original import, so I do still think we need a nationwide update of some sort.

**Comment by TurnrDev** [comment]
I just had a thought, how about we ask if the AtcoCode and NaptanCode as visible at the bus stop and tag them with the `*:signed` suffix?

`naptan:*:signed=yes/no`
`naptan:verified=yes/no`

Perhaps ask which is more prominent if both are present and !ref, then set the ref value to the more prominent one?

For example, node has:
highway=bus_stop
name=*
naptan:AtcoCode=*
naptan:NaptanCode=*
!ref

Question: "Which of the following codes are visible at this bus stop:
ATCO: x
NaPTAN: x"

Answer tree:

- Both -> "Which is more prominent?" -> ATCO -> `naptan:AtcoCode:signed=yes` + `naptan:NaptanCode:signed=yes` + `ref=$naptan:AtcoCode` + `naptan:verified=yes`
- Both -> "Which is more prominent?" -> NaPTAN-> `naptan:AtcoCode:signed=yes` + `naptan:NaptanCode:signed=yes` + `ref=$naptan:NaptanCode` + `naptan:verified=yes`
- ATCO -> `naptan:AtcoCode:signed=yes` + `naptan:NaptanCode:signed=no` + `ref=$naptan:AtcoCode` + `naptan:verified=yes`
- NaPTAN-> `naptan:AtcoCode:signed=no` + `naptan:NaptanCode:signed=yes` + `ref=$naptan:NaptanCode` + `naptan:verified=yes`
- None -> `naptan:AtcoCode:signed=no` + `naptan:NaptanCode:signed=no` -> Ask existing bus stop ref quest

**Comment by westnordost** [comment]
To be honest, as this example shows as well, every ticket about "NaPTAN/ATCO" quickly devolves into a big wall of text and I have stopped following these tickets. If you **do** come to a conclusion, I'd suggest that someone from the UK community implements these yourself as a PR. I can offer technical review of that but will request that it is also reviewed by the UK community before it is included in the app.

**Comment by kymckay** [comment]
I had assumed as much 😄

I think this quest idea may just be too nuanced to do in a simple fashion for good UX, but at least these tickets can serve as a reference point for that if no conclusion is reached

**Comment by kymckay** [comment]
@TurnrDev 

> I just had a thought, how about we ask if the AtcoCode and NaptanCode as visible at the bus stop and tag them with the `*:signed` suffix?

I like the idea as it solves the tagging for the negative cases. Is this suffix in use somewhere already or a new idea? A quick search didn't net me any info, but I may have missed a wiki page somewhere.

> Perhaps ask which is more prominent if both are present and !ref, then set the ref value to the more prominent one?

My concern with something like this is twofold:
1. It complicates the quest
2. There's an unclear situation where neither is more prominent and both are signed

**Comment by TurnrDev** [comment]
> 
> 
> @TurnrDev
> 
> > I just had a thought, how about we ask if the AtcoCode and NaptanCode as visible at the bus stop and tag them with the `*:signed` suffix?
> 
> I like the idea as it solves the tagging for the negative cases. Is this suffix in use somewhere already or a new idea? A quick search didn't net me any info, but I may have missed a wiki page somewhere.

[*:signed](https://taginfo.openstreetmap.org/search?q=%3Asigned) is a new-ish suffix (name:signed has been around since 2014, but others appeared over the past 3 years), already used several places on StreetComplete and I'm all for using it more.

**Comment by westnordost** [comment]
Alright, I don't see how this is actionable, so I'll close this. If you find there is something actionable, you can create a PR yourself or write another ticket (after conferring with the parties involved) with very clear things that should be filtered for and what should be tagged.
