### ISSUE TITLE
Add a re-order handle icon to the quests list to hint that it is user sortable

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2828]
**Use case**
SC allows you to re-order quests, but this is not obvious at all. I missed this until it was pointed out here and so did someone else https://github.com/streetcomplete/StreetComplete/issues/2802#issuecomment-829609238.

Re-ordering quests makes mappers happier and more likely to continue doing quests, allowing mappers to have easier to answer quests appear first, or quests that they are more interested in appear first.

**Proposed Solution**
Add the standard re-order handle to the left of the quests list, which makes it obvious to users that quests can be re-ordered.

![reorder-horizontal](https://user-images.githubusercontent.com/117278/116627958-7ac4c500-a991-11eb-84ab-07554e677776.png)

**Comment by mnalis** [comment]
That is true - I've noticed in other parts of StreetComplete too that myself (and seemingly others) are **trained to ignore** the description text below title, **even if it is very short and clearly written** (like here where quite clearly it says _"Long-press and move a quest to reorder its priority for display on the map"_)

And it is true that **simple visual cue** like suggested almost always works much much better.

However, on mobile device (especially smartphones), screen estate is at premium. Putting reorder icon on each quest line **will** reduce screen estate for description by about 25%, making most of remaining one-line _Quest descriptions_ expand to two lines, which will make (already quite cubersome) _Quest selection_ even less usable.

So it is an interesting usability choice - should we make useful feature much easier for new users to discover, knowing that the cost is going to be **lower usability forever** for everyone who has already learned of that feature?

Perhaps the feature discovery could be made in some other way, which is not going to have long-term negative consequences. Like **short auto-loop animation** showing how to reorder and enable/disable quests the first few times the user enter the _Quest selection_ menu? (for example until users checks a checkbox named "don't show this hint anymore" below animation?)

**Comment by smichel17** [comment]
Another option is a "reorder quests" menu item, which would replace the check box with a handle until you switch back.

**Comment by andrewharvey** [comment]
> That is true - I've noticed in other parts of StreetComplete too that myself (and seemingly others) are trained to ignore the description text below title, even if it is very short and clearly written (like here where quite clearly it says "Long-press and move a quest to reorder its priority for display on the map")

Totally, I've never noticed that text before, and didn't believe you until I checked the app. Right or wrong, I 

> Another option is a "reorder quests" menu item, which would replace the check box with a handle until you switch back.

Great idea! Should solve @mnalis's concerns about screen real estate.

**Comment by TurnrDev** [comment]
I wonder how many other texts I've missed and if a simple style change can fix that

**Comment by HolgerJeromin** [comment]
The podcast player antennapod has small "handles" on the left of all episodes:
https://raw.githubusercontent.com/AntennaPod/AntennaPod/develop/app/src/main/play/listings/en-US/graphics/phone-screenshots/04.png

**Comment by matkoniecz** [comment]
> I wonder how many other texts I've missed and if a simple style change can fix that

Make secondary text more dark and less gray?

**Comment by westnordost** [comment]
I think there is enough space for such a handle

**Comment by smichel17** [comment]
> I wonder if a simple style change can fix that

Perhaps showing the same text as a toast when you first enter the quest selection screen?

**Comment by goldfndr** [comment]
Maybe rename from "Quest selection" to "Quest selection and order"?

**Comment by FloEdelmann** [comment]
I opened a PR with both changes: #2843

<img src="https://user-images.githubusercontent.com/202916/116974831-ffc81b00-acbe-11eb-9a8d-36d79dad5a35.png" width="40%"> <img src="https://user-images.githubusercontent.com/202916/116975029-43bb2000-acbf-11eb-8054-6cfb9e849805.png" width="40%">
