### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by MaxHeimbrock** [streetcomplete/StreetComplete#2829]
Hello, I just found this app and wanted to give it a try, but the log in screen is blank for me.

**How to Reproduce**
When I press on "Mein Profil" (my profile) I see one button only saying "Anmelden" (log in). When I press it, I see a blank screen. I can tell that the blank screen is a new layout sliding in from the right side. The toolbar on the top still works and I can go back and forth between the two screens.

![Screenshot_20210430-082419_StreetComplete](https://user-images.githubusercontent.com/43608204/116657742-36d0c080-a98f-11eb-8f37-9298d9c9a540.jpg)

![Screenshot_20210430-082413_StreetComplete](https://user-images.githubusercontent.com/43608204/116657787-46e8a000-a98f-11eb-82e9-78b54236e7a8.jpg)

First time I solved some tasks and then tried to log in. Then I installed it a second time and solved no quest at the start but immediatly tried to log in, still had the same issue. 

**Versions affected**
Fresh download of v31.3 from the play store on a Samsung A3 (2017) with android 8.0.0. The language is german.

**Comment by matkoniecz** [comment]
To check one unlikely case that results in this behaviour: you have a an enabled browser app on the phone, right?

**Comment by MaxHeimbrock** [comment]
Yes, default is the standard Samsung browser.

**Comment by MaxHeimbrock** [comment]
It was the right hint anyway, since I just now saw that my Chrome browser does not work properly and also only shows me a blank screen. Now I deactivated Chrome and the StreetComplete app crashes when pressing "Anmelden" (log in). So the standard browser option does not help here and it always wants Chrome I guess, even though I also have Samsung Internet, Brave and Via browser installed on the phone. Should I close the issue then?

**Comment by matkoniecz** [comment]
Ideally it would work not only with Chrome, and maybe it is fixable on SC side.

Are you maybe able to access app logs? (it is possible for example via Android Studio and via LogCat on a rooted devices)

> Now I deactivated Chrome

Are links from other applications working? For clicking on credit text in Vespucci editor (displayed on the bottom of the map). 

Maybe you need to change default browser somewhere.

Can you press "JawgMap" on the bottom of map and select "OK" in open URL? Is this working or is it also broken?

**Comment by MaxHeimbrock** [comment]
Hello again,

> Can you press "JawgMap" on the bottom of map and select "OK" in open URL? Is this working or is it also broken?

Yes, that works, the link is opened in Samsung Internet.

> Are you maybe able to access app logs? (it is possible for example via Android Studio and via LogCat on a rooted devices)

Sorry, I have no Android Studio installed right now and the device is not rooted.

> Maybe you need to change default browser somewhere.

I think I have every possible setting set to use Samsung Internet, even reinstalled the app when Chrome was deactivated so it would not even see it.

![Screenshot_20210430-110555_Settings](https://user-images.githubusercontent.com/43608204/116674522-0ac03a00-a9a5-11eb-9523-62b4777e350a.jpg)

**Comment by westnordost** [comment]
What you need is the android system webview, an app that is always installed on every device. Did you deactivate it by chance? 

Am 30. April 2021 11:18:36 MESZ schrieb MaxHeimbrock ***@***.***>:
>Hello again,
>
>> Can you press "JawgMap" on the bottom of map and select "OK" in open
>URL? Is this working or is it also broken?
>
>Yes, that works, the link is opened in Samsung Internet.
>
>> Are you maybe able to access app logs? (it is possible for example
>via Android Studio and via LogCat on a rooted devices)
>
>Sorry, I have no Android Studio installed right now and the device is
>not rooted.
>
>> Maybe you need to change default browser somewhere.
>
>I think I have every possible setting set to use Samsung Internet, even
>reinstalled the app when Chrome was deactivated so it would not even
>see it.
>
>![Screenshot_20210430-110555_Settings](https://user-images.githubusercontent.com/43608204/116674522-0ac03a00-a9a5-11eb-9523-62b4777e350a.jpg)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2829#issuecomment-829961985

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Atrate** [comment]
> Sorry, I have no Android Studio installed right now and the device is not rooted.

I think you can also grab the logs via `adb logcat` (https://www.siteforinfotech.com/capture-android-logs-minimal-adb-and-fastboot/), without root

**Comment by MaxHeimbrock** [comment]
> What you need is the android system webview, an app that is always installed on every device. Did you deactivate it by chance?

Yes it is deactivated. I just saw [this thread](https://eu.community.samsung.com/t5/andere-smartphones/galaxy-a50-webview-deaktiviert/td-p/1158803) about how it only is active when Chrome is deactivated and the other way around, I can confirm this behaviour on my phone. So if I deactivate Chrome, webview is activated and the App then crashes if I want to log in. If I activate Chrome, webview is deactivated and the page stays empty but does not crash.

> I think you can also grab the logs via adb logcat (https://www.siteforinfotech.com/capture-android-logs-minimal-adb-and-fastboot/), without root

I'll look into this now, thanks for the info.

**Comment by MaxHeimbrock** [comment]
So the problem kind of solved itself in the following way:

I recorded logs with the solution of @atrate and saw the crash
`04-30 10:27:26.139 14833 14833 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 438910520 actual: 335912602`

In the app settings, my webview was actually on version 66.0.3359.126 and after I updated it manually through the Play Store it was on version 90.0.4430.91, but the crash was still happening and the log still said "actual: 335912602". I restarted the phone, still saw the same crash, then activated Chrome again and now I see the log in screen in the app :smile: 

It seems that there is something going on with the webview (https://onlinemarketing.de/technologie/app-crash-android-update-system-webview-notig), also I did not change anything in Chrome and it stopped displaying websites from yesterday to today. I guess the restart did the trick...

Thanks everyone for your help 👍

**Comment by matkoniecz** [comment]
`Caused by: android.util.AndroidRuntimeException (...) Failed to verify WebView provider`

It seems to not be fixable by StreetComplete and an external bug without viable workaround.

Great that it works now, happy mapping!
