### ISSUE TITLE
New quest: What kind of outdoor seating is this?

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#2833]
### General
Affected tag(s) to be modified/added: [outdoor_seating](https://wiki.openstreetmap.org/wiki/Key:outdoor_seating)
Question asked: **What kind of outdoor seating is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose. The tag is established, but [values other than `yes` are not really used yet](https://taginfo.openstreetmap.org/keys/?key=outdoor_seating#values) and there are probably no projects using those values.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** `leisure = outdoor_seating and (!outdoor_seating or outdoor_seating = yes)

**Proposed GUI:** Image selection quest with images for the values listed here: https://wiki.openstreetmap.org/wiki/Key:outdoor_seating#Rare_values

---

I'm not sure if this is worth the effort. We'd need to find representative images and make sure that not too many notes would need to be created because the options don't contain a fitting one.

A similar but distinct quest was suggested in #1176.

**Comment by westnordost** [comment]
I'd say that two things speak against this:

1. I don't really see the useful purpose of this.
2. The tags are not really established yet
