### ISSUE TITLE
stop asking for building levels of building=industrial

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2835]
Many have no building levels or have them really tricky.

Example: https://www.openstreetmap.org/note/2649967 https://www.openstreetmap.org/way/229419620#map=19/50.05394/19.97661

![39985](https://user-images.githubusercontent.com/899988/116828358-7de0d080-ab9e-11eb-97e9-fa9cb3fe702f.jpg)

I will make commit if noone will protest.

**Comment by eginhard** [comment]
Level heights can vary a lot as well, so the resulting building:levels might not be very informative on its own.

**Comment by westnordost** [comment]
On the other hand, @matkoniecz , I think that industrial buildings were once excluded and got added later. Maybe look in the history first as to why this happened.

For your example here it would be pretty clear that it is building:levels=2 TBH.

**Comment by matkoniecz** [comment]
> For your example here it would be pretty clear that it is building:levels=2 TBH.

I would not be sure, I would not be surprised at all by having 3 levels or a single high  space.

also, another view: https://gazetakrakowska.pl/krakow-odkryli-tajemnice-stopnia-wodnego-dabie-zdjecia/ga/c1-15200368/zd/45627626

![5f6f98c969a62_p](https://user-images.githubusercontent.com/899988/116882211-76fca100-ac24-11eb-9aad-e0728431d18e.jpg)

Other cases: https://commons.wikimedia.org/wiki/File:Linden_power_plant_Elisenstrasse_Ihme_river_Linden-Nord_Hannover_Germany_02.jpg https://en.wikipedia.org/wiki/File:Martinlaakson_voimalaitos.JPG https://commons.wikimedia.org/wiki/File:Walters_Ranch_Hop_Kiln_in_2019,_4×5.jpg https://en.wikipedia.org/wiki/File:Koebergnps.jpg https://commons.wikimedia.org/wiki/File:Kernkraftwerk_Stendal_Panorama_2012.jpg

**Comment by matkoniecz** [comment]
> I think that industrial buildings were once excluded and got added later. Maybe look in the history first as to why this happened.

I looked through https://github.com/streetcomplete/StreetComplete/commits/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels and it appears that it was always asked for them

**Comment by matkoniecz** [comment]
Fixed in https://github.com/streetcomplete/StreetComplete/commit/320117340ae317e759d70388515534be7fc163d5 (also, added two tests - mostly to have a place to keep that photo list)
