### ISSUE TITLE
Give hint to user when solving "It does not belong to named street" subanswer

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2836]
**Use case**
When solving _**"What street does the (house) number X belong to?"**_,  user can choose _**"It does not belong to a named street"**_ answer. It will show "Place name:" and a picture of a city silhouette, but it is not clear to user what needs to be done after that (especially when different signs are used in [their](https://hr.wikipedia.org/wiki/Datoteka:Prometni_znak_C79.svg) [country](https://hr.wikipedia.org/wiki/Datoteka:Prometni_znak_C80.svg))
![sc_town](https://user-images.githubusercontent.com/156656/116829308-ee3e2080-aba3-11eb-906d-a6906e6fed79.jpg)

**Proposed Solution**
To make it more clear, I see two possibilities:
- Immediately upon selecting this answer, put a blinking cursor automatically inside an edit field where user is supposed to enter name of the town. (In v31.3 on Android 10 Huawei P30 Pro, this happens automatically in  _**"What is the height limit of this tunnel?"**_ or _**"What is the name of this road?"**_ quests, so it clear that user needs to type something in. Interestingly, placing blinking cursor automatically in input field does not happen in some other quests like _**"What is the house number of this building?"**_ where it might also help).

- Alternatively, If the above behavior is not possible to force (but instead happens by accident depending on android version etc.), maybe we could use placeholder text like **"Enter town name here"** to indicate to users where they should click to continue with quest (like for example done in this same quest to hint at how to enter street name):
![sc_addr](https://user-images.githubusercontent.com/156656/116829679-6a853380-aba5-11eb-8b87-b72c3bfccc7f.jpg)

**Comment by westnordost** [comment]
a blinking cursor would probably make sense

**Comment by rhhsm** [comment]
I think the icon of the city scape is more confusing than it is helpful, so just removing it so you get a text field that looks like any other should be enough.
I was wondering if this feature could be enhanced by offering a short list of suggestions (the names of the 3-4 nearest nodes that have a place= tag), in a way similar to the suggested street names in the street name quest? This would greatly help a consistent good quality of addresses in areas where street names are not used for addresses. Here in Bulgaria, the communist-era apartment block suburbs have a block number - suburb - city format, while in Japan, addresses are formed by numbered houses, neighbourhoods, suburbs, city.
