### ISSUE TITLE
[v32.0-alpha] Can't select quests on specific way, no idea why

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2853]
https://www.openstreetmap.org/way/566820432

There's a couple quests here in need I
Of resolving but under 32alpha I can't select it. No clue why? 

Not sure what causes this or what can be done to fix it, sorry I couldn't be of help

**Comment by westnordost** [comment]
Hm sorry, can't reproduce that. A building levels quest is displayed and I can select it no problem.

I noticed you left a note. https://www.openstreetmap.org/note/1327197
Before or after you could not select any quests on that shop?

**Comment by TurnrDev** [comment]
It was before couldn't select the quests, but that's just because it appeared on the screen first. I cleared my cache and rescanned and now it works. That was weird.

**Comment by westnordost** [comment]
It's still an issue. But now I know what might be the root.

No quests should be displayed where there is a note. They should be invisible. I think when you try to open an invisible quest, it just does not work. So somehow that part was working correctly, but that invisible quest was still shown on the map

**Comment by TurnrDev** [comment]
What's weird is I answered the note in my fork in debug mode, but both the fork and your version both had the issue ⚠️ 

Your version wasn't opened until after I answered the note, I think?

**Comment by westnordost** [comment]
So you answered that note, and then "below" that note you answered were the other quests?

**Comment by TurnrDev** [comment]
Correctamundo

**Comment by westnordost** [comment]
I tested whether the hiding of quests that are at the position of a note works. It does: On download, I delayed the download of the notes so that it was done after downloading the map data. I saw a quest popping up at the position of the note, then when the notes finished downloading, the quest vanished again.

**Comment by westnordost** [comment]
Though a different algorithm is used to determine if a quest is at a note position for
1. **getting all quests for display in a bbox**: the positions of all notes are truncated to 5 decimals and all quests whose center that is also truncated to 5 decimals is equal to those truncated note positions is not displayed. A latlon position with 5 decimals has an accuracy of roughly 1 meter.
2. getting one quest: here, it is checked whether the quest is within 1 meter of a note.

So this is where the discrepancy could come from.
