### ISSUE TITLE
Service building operator

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#2859]
### General
Affected tag(s) to be modified/added: [operator](https://wiki.openstreetmap.org/wiki/Key:operator), as part of [building=service](https://wiki.openstreetmap.org/wiki/Tag:building%3Dservice)
Question asked: **Who is operating this service building?**

I have in interest in infrastructure buildings. The current tagging is generic (`building=service`), which is fine. Not everybody can distinguish different types of service buildings. Yet a strong indicator of the the type of service building is the operator. The name can give a hint if this service building is used by a energy company, a grid operator, a telecom operator, the public transport company, etc. Most service building have a company name on them, so this should be easy to tag.

The operator tag has value by itself, but can also be used to find service buildings and improve the tagging at a later stage. This refinement is outside of the scope of StreetComplete.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

On service buildings, ask for the operator. This should be a free format, although there will probably be a limited number of values in practice.

I would put this quite low on the priority list.

**Element selection:**
-

**Metadata needed:** 
-

**Proposed GUI:**

**Comment by Helium314** [comment]
I haven't looked at service buildings in detail, but I would assume not all have the operator visible from the outside.
Is there a way to tag this?

**Comment by westnordost** [comment]
Exactly, what @Helium314 wrote. Not all, and I'd even say, only a small percentage of service buildings have their operator written somewhere.

Also, `operator` I think it should not be a property at all of `building=service` but of the amenity/power/man_made/.... etc feature.
