### ISSUE TITLE
[v32.0-alpha1] housenumber quest does not appear

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2863]
@lukashass reported that sometimes, the housenumber quest would not pop up after answering the building quest.

> 1. had building levels disabled and wondered why no house number quest was offered.
> 2. then deleted all app data and saw the building levels quest.
>     1. When disabling the building levels quest at this point no quest is offered.
>     2. When answering the building levels quest, the house number quest is offered.
>     3. When scanning for quests at this point the house number quest will be replaced by the roof shape quest.

**Comment by westnordost** [comment]
I can indeed reproduce this with https://www.openstreetmap.org/way/450582253

Nice, finally a reproducible bug

**Comment by westnordost** [comment]
Okay, actually the whole download of housenumber quests was broken. Thanks for the report, @lukashass

**Comment by peternewman** [comment]
So this sounds like I wasn't imagining it in https://github.com/streetcomplete/StreetComplete/discussions/2834#discussioncomment-712225 either then! :smile:
