### ISSUE TITLE
base map does not appear

### ISSUE THREAD

**Issue by openbrian** [streetcomplete/StreetComplete#2866]
Map does not appear.  Quests do and OSM notes do.  Zoom in or out works, but still no base map.  Any theme, any overpass server.  Doesn't matter.  

**How to Reproduce**

Open the app.

**Versions affected**

Android 10, Street complete v19.0

**Comment by openbrian** [comment]
And I just spotted new versions available via F-Droid.

**Comment by matkoniecz** [comment]
> Street complete v19.0

This is ancient. Please, open a new issue if it is reproducible in something recently released: https://github.com/streetcomplete/StreetComplete/releases
