### ISSUE TITLE
Splitting ways in team mode

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2868]
After splitting a way in team mode, only some segments are shown for further quests.

Would it be possible to show all segments when auto-upload is disabled? 
Before uploading it shouldn't have a "real" id from which the team is determined, so that's why I think it could probably be done.

**Comment by HolgerJeromin** [comment]
The non-uploaded elements gets negative ids (which will be replaced by the osm server on upload). 

It is probably possible to generate **always only** ids which matches the current team filter (in no team mode we probably have internal team size 1 which does not collide with this change). Regardless of auto-upload.

**Comment by matkoniecz** [comment]
> It is probably possible to generate always only ids which matches the current team filter

What if someone changes team filter settings?

**Comment by Helium314** [comment]
If new ids are negative, it should be even easier by allowing every id < 0

**Comment by mnalis** [comment]
@Helium314 This would work nicely in offline mode, by giving both old and a new way to the person who split it.

But I'm not so sure team mode would work so nicely with split, if auto-upload is enabled. 

For example, in two-member team, even if one member creates only **even** ids: `-2`, `-4`, `-6`, I'm not sure that uploading them to OSM servers will result in real (positive) ids that are **even**, would it? ie. OSM server might create new ids just by doing a normal increment by one (somebody needs to check if that is the case!), which could lead to a case when OSM server creates new id which is **odd**, which would result in that all quests on that new way would **not be shown to any team member** (unless they all did manual rescan).

**Comment by westnordost** [comment]
I also thought about a solution here but nothing comes to mind. 

Maybe keep around another database table in which the (current) ids of all created elements by this app (uploaded and not uploaded) are kept. Quests for element ids in that table are always shown.

**Comment by matkoniecz** [comment]
> Quests for element ids in that table are always shown.

But no longer that cache timeout

**Comment by westnordost** [comment]
Anyway, so the solution with the negative ids would work without that extra database table. So this could be implemented right away. The other, hmm... maybe later(?)

**Comment by smichel17** [comment]
As a workaround, upload of split ways could be delayed until after team mode is exited. I think the separate table solution sounds like a better idea in the long run, but that could be added later.

Also, if auto-upload stays enabled — When downloading quests, I assume the last-modified date is included? In that case, when in team mode, any newly-downloaded element that has been modified since team mode was entered should be excluded. That way if person A splits a way and uploads, then person B refreshes their data, B and A will not potentially both see the same quest.

**Comment by westnordost** [comment]
#2873
