### ISSUE TITLE
Quest "Welche Art von Fußgängerüberweg ist das?" is difficult to answer in case of `crossing:island = yes`

### ISSUE THREAD

**Issue by sjakobi** [streetcomplete/StreetComplete#2869]
At https://www.openstreetmap.org/node/8491607831 there's an open quest "Welche Art von Fußgängerüberweg ist das?". The options are:

* Kreuzung mit Ampel
* Kreuzung mit Markierung
* Kreuzung ohne Markierungen

Since there is a traffic island, the crossing is in some way marked. The picture suggests a zebra crossing though, and it's not that.

Should I select one of the existing options? It would be nice if the app could offer better guidance in this case.

I'm using v31.3.

(BTW: I really enjoy contributing to OSM via this awesome app! :heart:)

**Comment by westnordost** [comment]
Kreuzung ohne Markierungen it is. An island is no marking.

**Comment by sjakobi** [comment]
> Kreuzung ohne Markierungen it is.

Thanks! I've submitted that option.

Maybe the wording could be improved to say "Kreuzung mit Zebrastreifen". That way it would be clearer what kind of marking is meant.

**Comment by westnordost** [comment]
Problem is that not every marked crossing has a zebra. In Germany, generally yes, but except if it is not a crossing for pedestrians but just bicyclists for example

**Comment by sjakobi** [comment]
OK. Could the illustrative pictures be more specific in the case of `crossing:island = yes`? So "Kreuzung ohne Markierungen" would show an island without any additional markings. That should be pretty clear.

**Comment by westnordost** [comment]
Hmm, maybe. Would you like to look for a fitting picture (with a fitting license)?

**Comment by matkoniecz** [comment]
And note that making own and publishing it under an open license is a viable solution (that is how current unmarked crossing image was produced).

**Comment by sjakobi** [comment]
> And note that making own and publishing it under an open license is a viable solution

I'm going to give this a try.

**Comment by peternewman** [comment]
> Could the illustrative pictures be more specific in the case of `crossing:island = yes`? So "Kreuzung ohne Markierungen" would show an island without any additional markings. That should be pretty clear.

Isn't this usually asked before `crossing:island` quest though, so we'll either need a split-screen image or to risk everyone getting confused the other way.

**Comment by sjakobi** [comment]
@peternewman My suggestion was to use the new picture only when `crossing:island = yes` is already known, as it was in the case of https://www.openstreetmap.org/node/8491607831. So I don't see any potential for additional confusion.

**Comment by peternewman** [comment]
Yep, I'm just making the point that given a bare highway=crossing and the use of SC alone, that scenario doesn't happen by default @sjakobi :
https://github.com/streetcomplete/StreetComplete/blob/b6fe0821a783b0018728420849bb5ff7326b6429/app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.kt#L164-L165

Obviously in the case of that node if the island status has been tagged already it will, but then they may have tagged the crossing type too.

**Comment by westnordost** [comment]
Did you find a good picture, @sjakobi ?

**Comment by rugk** [comment]
> Problem is that not every marked crossing has a zebra pattern. In Germany, generally yes, but except if it is not a crossing for pedestrians but just bicyclists for example

I don't really get that last example with a crossing for bicycles… How does that look like? After all, in German law, IIRC, only zebra pattern signals the priority order which [this quest](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#tactile_paving) is about…

[Or is it](https://wiki.openstreetmap.org/wiki/Key:crossing)? Actually the wiki lists `crossing=marked` and `crossing=zebra`?
What was the reason for not including both? (I guess this depends on the use case the collected data is actually used for)
…at least in Germany you could include it.

> In Germany, generally yes

…otherwise I would have asked to just change the German translation, but in such a case that is of course not possible…

**Comment by westnordost** [comment]
> I don't really get that last example with a crossing for bicycles… How does that look like?

You see it on the right side of this photo

![20210630_140302](https://user-images.githubusercontent.com/4661658/125113603-2a808680-e0e9-11eb-8ee4-90aa0e0d2b0e.jpg)

**Comment by rugk** [comment]
Ah of course now I get it. So basically [what is also shown in  the wiki](https://wiki.openstreetmap.org/wiki/File:568_Radfurt_Osterstr_Fr-Ebert-Str.jpg) if you'd remove the traffic lights there… the only question would be you maybe would need a differentiation between passenger stuff and bicycle ways
Especially in your GMaps example, the bicycle way is marked, but the passenger one is not – I'm not sure what I would choose in the quest there…

**Comment by westnordost** [comment]
I'll close this as OP did seem to lose interest in finding a different photo and TBH the current photo is OK. If a photo of an island or some other marking (not on the road) was shown, people might be confused what to answer if there is not even that (not an island or other marking)
