### ISSUE TITLE
Options dissapear when switching to splitscreen mode.

### ISSUE THREAD

**Issue by thibaultmol** [streetcomplete/StreetComplete#2870]
Turning on Android's splitscreen feature causes the 'yes/no' options for the openinghours re-survey quest to dissapear.
This issue is happening on my old backup phone (Nexus 5X). Don't know about modern versions of android

**How to Reproduce**
When I open the app, click on an opening hours re-survey quest. Then hold down the app switcher button (so android goes into splitscreen mode). The other options (yes/no) dissapear and don't come back even when I exit splitscreen mode

VIDEO: https://streamable.com/u7o70u (backup video link: https://photos.app.goo.gl/XDjj8fnmC1qWJVeS7 )

**Versions affected**

streetcomplete 31.3
Android 8.1

EDIT: I would have just done a normal screen recording. But my backup phone's storage is literally at the limit so can't even install a recording app XD

**Comment by peternewman** [comment]
Happens on SC 32.0alpha2 Android 9 too.

Also note how the buttons change from embedded in the menu to separate blue ones.

I can't get it to happen with other quests.

**Comment by peternewman** [comment]
I hadn't tried that one before, but I can't get it to break now.

I think the location kept resetting, but I'm not certain.

**Comment by thibaultmol** [comment]
> Same with cycleway quest, no?

Which quest exactly?
