### ISSUE TITLE
Add level filtering widget to display quests / declutter screen

### ISSUE THREAD

**Issue by Codain** [streetcomplete/StreetComplete#2874]
**Use case**
With the increase of indoor mapping and feature checking in SC some areas are cluttered with a lot of quests and it can be hard to focus on the level I'm in. Examples are multi level railway stations with lot of maps, terminals, boards, staircases... Repeated at different levels. I've noticed that the level is displayed in the quest when available but when I'm on second floor I don't want first floor quests to disturb me and stop me from identifying current floor quests.

**Proposed Solution**
Add a widget to enable/disable level filtering and select which level(s) to display. This will imply to parse level tags including scalar levels (1), level ranges (2-10) and intermediate levels (0.5).

**Comment by matkoniecz** [comment]
JOSM has something similar and it appears only if there are buildings with `level` tag

**Comment by andrewharvey** [comment]
Or even just short-term fix would be to sort quests by level. I did some indoor quests the other day and found myself having to keep changing levels in the elevator as some quests were hidden by quests on other levels.

> JOSM has something similar and it appears only if there are buildings with level tag

For the implementation if any of the quest features contain `level` or `level:ref` tags, then show the level filter UI based on the available level:ref/level values present in the data.

**Comment by Atrate** [comment]
Partially related: #1487. POIs without a level tag would also have to be handled — either displayed on all levels or not displayed at all.

**Comment by peternewman** [comment]
See also (which I thought I'd raised before, but evidentially not) https://github.com/streetcomplete/streetcomplete-mapstyle/issues/100 regarding how they are displayed on the map. I guess this filtering could link into that and only show the ones on your level.

> JOSM has something similar and it appears only if there are buildings with `level` tag

It's potentially more subtle and relevant if there are any level things visible on-screen. If you look around Oxford Circus there are the paths to get to the underground, with their `level` tags mapped, and then footpaths on the ground which don't have any tagging (which seems fair enough), we should still be able to show either a particular level of the underground, or hide all the underground stuff.

**Comment by westnordost** [comment]
TBH I am not sure how helpful this really is without a full indoor rendering support. The helpfulness of this button even in JOSM is so-so.

**Comment by peternewman** [comment]
> TBH I am not sure how helpful this really is without a full indoor rendering support.

It would mean you could hide e.g. the underground paths. IMHO it interacts with #2878 and #2373. i.e. there is a benefit for removing subways and underpasses when mapping the surface layer. But personally I wouldn't remove them entirely because I think you can still answer (some or all of those quests), although https://github.com/streetcomplete/streetcomplete-mapstyle/issues/100 would help that.

I guess I'm trying to say there are other uses for this aside from indoor mapping.

**Comment by matkoniecz** [comment]
> The helpfulness of this button even in JOSM is so-so.

well, it turns map from mess impossible to edit to something comprehensible for me

StreetComplete currently is extremely hard to use in multilevel malls

(though I am not entirely sure is level switcher going to help much, even for experienced users)

**Comment by mnalis** [comment]
For those interested, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) does implement level filter:

![small_Screenshot_20241111_171308_SCEE](https://github.com/user-attachments/assets/8b883dd8-5e27-43cc-a770-a7d4b78e7a63)


That being said, I'm using that functionality extremely rarely, as I'm personally not a big fan of mapping malls / railway stations / etc. from mobile - I find it that it is usually way too hard to properly orient oneself:
- GPS signal has absolutely huge errors (if available at all), 
- mobile phones do not seem to  even try to provide smart inertial navigation (why, oh why?), 
- tiles do no properly render indoor features (so one often needs SCEE Custom overlay too just to be able to display corridors indoors).

So one is restricted to constructing the maze walked in their head. As I'm not very good at it (or else I'd likely opt for career of professional chess player :smiley:)  most of my POIs inside malls are only _very_ approximately located (i.e. closest to one side of the mall) or even just more-or-less randomly placed inside a mall polygon. I do try to at least add `level=*`, though.

Another app which people might try to help with indoor mapping is [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door), which also has some support (but still lacking, IMHO, especially rendering or corridors part -- but that one hopefully is [soon to change](https://mastodon.online/@everydoor@en.osm.town/113437163026794727), so follow him up if you're interested).

**Comment by dbdean** [comment]
> For those interested, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) does implement level filter:
> 
> ![small_Screenshot_20241111_171308_SCEE](https://github.com/user-attachments/assets/8b883dd8-5e27-43cc-a770-a7d4b78e7a63)
> 
> 
> That being said, I'm using that functionality extremely rarely, as I'm personally not a big fan of mapping malls / railway stations / etc. from mobile - I find it that it is usually way too hard to properly orient oneself:
> - GPS signal has absolutely huge errors (if available at all), 
> - mobile phones do not seem to  even try to provide smart inertial navigation (why, oh why?), 
> - tiles do no properly render indoor features (so one often needs SCEE Custom overlay too just to be able to display corridors indoors).
> 
> So one is restricted to constructing the maze walked in their head. As I'm not very good at it (or else I'd likely opt for career of professional chess player :smiley:)  most of my POIs inside malls are only _very_ approximately located (i.e. closest to one side of the mall) or even just more-or-less randomly placed inside a mall polygon. I do try to at least add `level=*`, though.
> 
> Another app which people might try to help with indoor mapping is [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door), which also has some support (but still lacking, IMHO, especially rendering or corridors part -- but that one hopefully is [soon to change](https://mastodon.online/@everydoor@en.osm.town/113437163026794727), so follow him up if you're interested).
> 

Is this still available in SCEE? I can't seem to find it.

**Comment by mahlersand** [comment]
> > For those interested, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) does implement level filter:
> > ![small_Screenshot_20241111_171308_SCEE](https://github.com/user-attachments/assets/8b883dd8-5e27-43cc-a770-a7d4b78e7a63)
> > That being said, I'm using that functionality extremely rarely, as I'm personally not a big fan of mapping malls / railway stations / etc. from mobile - I find it that it is usually way too hard to properly orient oneself:
> > 
> > * GPS signal has absolutely huge errors (if available at all),
> > * mobile phones do not seem to  even try to provide smart inertial navigation (why, oh why?),
> > * tiles do no properly render indoor features (so one often needs SCEE Custom overlay too just to be able to display corridors indoors).
> > 
> > So one is restricted to constructing the maze walked in their head. As I'm not very good at it (or else I'd likely opt for career of professional chess player 😃)  most of my POIs inside malls are only _very_ approximately located (i.e. closest to one side of the mall) or even just more-or-less randomly placed inside a mall polygon. I do try to at least add `level=*`, though.
> > Another app which people might try to help with indoor mapping is [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door), which also has some support (but still lacking, IMHO, especially rendering or corridors part -- but that one hopefully is [soon to change](https://mastodon.online/@everydoor@en.osm.town/113437163026794727), so follow him up if you're interested).
> 
> Is this still available in SCEE? I can't seem to find it.

It is in the quick settings you can enable deeper in the settings if you have expert settings enabled :D
