### ISSUE TITLE
new opening hours UI only shows 12 hour format, previous UI showing both is better

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2877]
The opening hours UI recently changed and personally I feel it has regressed. Previously it would show both 12 and 24 hour time, which is great when some signs are in 12 hour and others in 24 hours. This greatly reduces the risk of errors when trying to convert between the two systems.

Now it only uses 12 hour time.

Further for someone who always forgets if midday/midnight are 12 am or pm, the current UI asking me to choose am or pm makes it much harder to get right.

**Comment by westnordost** [comment]
It shows what you set in your system preferences.  If you set that it should show the 12 hour clock, it shows that,  if you set it should show the 24 hour clock,  it shows that. 
If you find the 12 hot clock confusing,  why are you using it? 

Am 13. Mai 2021 06:00:35 MESZ schrieb Andrew Harvey ***@***.***>:
>The opening hours UI recently changed and personally I feel it has
>regressed. Previously it would show both 12 and 24 hour time, which is
>great when some signs are in 12 hour and others in 24 hours. This
>greatly reduces the risk of errors when trying to convert between the
>two systems.
>
>Now it only uses 12 hour time.
>
>Further for someone who always forgets if midday/midnight are 12 am or
>pm, the current UI asking me to choose am or pm makes it much harder to
>get right.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2877

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andrewharvey** [comment]
But system preference != signposted. My system preference is 12 hour format which I prefer, however if a venue is signposted as 24 hour then I'd like to be able to enter in 24 hour as signposted. Likewise if venue is signposted in 12 hour I should be able to enter that in the 12 hour format. Otherwise if you force only one entry scheme, then the mapper has to do the conversion from signposted, which is an extra source of errors.

**Comment by westnordost** [comment]
I don't know what you are talking about,  regarding that there used to be the possibility to choose 

Am 13. Mai 2021 12:50:20 MESZ schrieb Andrew Harvey ***@***.***>:
>But system preference != signposted. My system preference is 12 hour
>format which I prefer, however if a venue is signposted as 24 hour then
>I'd like to be able to enter in 24 hour as signposted. Likewise if
>venue is signposted in 12 hour I should be able to enter that in the 12
>hour format. Otherwise if you force only one entry scheme, then the
>mapper has to do the conversion from signposted, which is an extra
>source of errors.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2877#issuecomment-840478873

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andrewharvey** [comment]
> I don't know what you are talking about,  regarding that there used to be the possibility to choose

I managed to downgrade to 31.1 which has the previous UI which shows both 12 and 24 hour formats together. 31.3 uses a different UI which doesn't how both 12 and 24 hour formats.

![Screenshot_20210513-213350_Street_Complete](https://user-images.githubusercontent.com/117278/118120436-3cb8ae00-b433-11eb-8123-0e5ab071f648.png)

**Comment by westnordost** [comment]
Where do you see the 12 hour format in this picture?

**Comment by andrewharvey** [comment]
> Where do you see the 12 hour format in this picture?

The outside ring is 12 hour format, the inside ring is 24 hours. Of course the entry is still 24 hours so to select 6pm you still need to choose the 18, however it's much easier to enter this way (at least for me) because if you see signposted as 18 you choose the 18 if signposted as 6pm you see the 18 is aligned to the 6 and so know to select the 18.

**Comment by westnordost** [comment]
Yes, or in other words, that is not a selector for the 12 hour format at all but the selector for the 24 hour format.

**Comment by westnordost** [comment]
Would it make sense to show the times in 12 hour format in countries where the 12 hour format is used and the 24 hour format in countries where the 24 hour format is used?

https://en.wikipedia.org/wiki/Date_and_time_representation_by_country#/media/File:12_24_Hours_World_Map.svg

**Comment by andrewharvey** [comment]
> Would it make sense to show the times in 12 hour format in countries where the 12 hour format is used and the 24 hour format in countries where the 24 hour format is used?

No I don't think so, because in my opinion the time selector shouldn't be in the users device time format, rather it should always show both 12 and 24 hour formats so that regardless on how the opening hours are signposted, the user can enter that data. (yes I know that my screenshot is the 24 hour format selector, but it makes it easier to enter pm 12 hour format times too because of the UI).

That said, I can't comment on what makes sense for other countries, but at least for me in Australia, opening hour signs use either 12 or 24 hour format (maybe half half).

**Comment by westnordost** [comment]
In that picture I linked, Australia is also shown as "both in common use". I'd say for people who know the 24 hour clock at all, it is not problem to switch mentally between the two. So if you see "3 PM" somewhere, it's easy to translate that to "15".

How about those not really familiar with that, f.e. Americans?

**Comment by smichel17** [comment]
I don't think I've ever seen a 24 hour time signed in the US.

I personally use 24h time on my phone and prefer entering times in that format (as @andrewharvey notes, the rings make it easy to translate between the two), but I suspect a very small % of other Americans do the same (but maybe a higher % among SC users / people interested in OSM?).

Despite using 24h time on my phone for around 5 years, I still semi-regularly mix them up when I'm not paying attention (glance at phone at 19:00, brain sees only the "9:00" part). It's fine when I'm paying attention, though.

**Comment by westnordost** [comment]
Anyway, I'd close this then.

This was implemented because someone requested it, because he was confused by the (for him) unfamiliar 24 hours clock.

If you now say that previously, you liked it better, then, what should I do?

I made a suggestion https://github.com/streetcomplete/StreetComplete/issues/2877#issuecomment-840663225 but there was no reply.

**Comment by mnalis** [comment]
Maybe it could be a setting in preferences `Preferred time format:` with options `auto` (default, do as it does now) / `12h` / `24h`? That might make everyone happy?
