### ISSUE TITLE
Allow one more zoom step

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#2878]
**Use case**:
In densely populated areas, quests often overlap each other and cause some of them not to be shown. I often use SC when on public transport and solve only certain kinds of quests which are sometimes obscured by ones that I can't solve when in a bus but don't want to hide for when I go there on foot. Allowing the user to zoom in further would help the overlapped quests be shown.

**Proposed solution**:
Allow the zoom to go one step further (if it's defined in steps). I haven't tested it with aerial imagery in v32 but it would probably help there as well, to see more details. 

If that's not desirable in SC, where can the max zoom be changed? I'd implement this in my fork for personal use.

**Comment by rhhsm** [comment]
#2373 (would like to re-post my final post there)

**Comment by westnordost** [comment]
f.e. in `onMapReady` in `QuestsMapFragment`:
 `ctrl.maximumZoomLevel = 21.0f`

**Comment by westnordost** [comment]
Looks like 20.5, the default, is already the maximum that tangram-es allows. If you want this to be changed, you'd have to create a ticket at tangram-es first.

**Comment by westnordost** [comment]
No, it isn't. It is not possible.

**Comment by Atrate** [comment]
> Some SDKs also allow multiple tap feature picking... like if there are 2 overlapping icons, the first tap brings up the top icon, but the second tap brings up the "hidden" icon.
(https://github.com/tangrams/tangram-es/issues/2264#issuecomment-840714209)

Is this a possibility in the case of SC?

**Comment by mnalis** [comment]
I've now added a FAQ entry for [Some quests are obstructed by other quests, and I can't zoom in enough](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Some_quests_are_obstructed_by_other_quests,_and_I_can't_zoom_in_enough) with some workarounds listed.
