### ISSUE TITLE
oauth_communication_error Android 4.2.2

### ISSUE THREAD

**Issue by 7tonin** [streetcomplete/StreetComplete#2881]
Hi, I wonder if such a device (android 4.2.2) can connect oauth.

**Comment by westnordost** [comment]
Depends on if your device accepts the SSL certificate of openstreetmap.org. Really old versions of Android do not recognize Let's Encrypt as a trusted root CA.

**Comment by 7tonin** [comment]
This 6+ years old device can run a firefox browser to access a letsencrypt ssl website, but I don't know if any android app can do the same.

**Comment by westnordost** [comment]
Firefox does not use the system root CAs but its own ones.

So maybe there is something you yourself can do about it, maybe you can somehow add the root ca of Let's Encrypt to the system list if trusted CAs. Then it should work. If you do, you could write your solution back here to help other people with an old phone like yours to use this app. 

Support for Android < 5 is scheduled to be dropped soon anyway. Only 0.35% of this app's users use an Android < 5, so nothing will be done from my side.

**Comment by mnalis** [comment]
There is a good writeup about issue at https://letsencrypt.org/2020/11/06/own-two-feet.html

they note:
>     Update, December 21 2020
>    Thanks to community feedback and our wonderful partners at IdenTrust, we will be able to continue to offer service without interruption to people using older Android devices. We flagged the content of this blog post that is no longer accurate.

**Comment by westnordost** [comment]
As far as I know, this is not directly related. Otherwise, @7tonin would have no problem here
