### ISSUE TITLE
Reversing deletion of bicycle parking isn't possible

### ISSUE THREAD

**Issue by Flugschwein** [streetcomplete/StreetComplete#2884]
**How to Reproduce**

* Look for a bicycle parking capacity quest
* Select OTHER ANSWERS --> It does not exist... --> IT DOES NOT EXIST
* Try to reverse your action

I do not know if that is everything required to reproduce as I didn't try to reproduce in order to prevent me from accidentally deleting further nodes from OSM. I had deactivated the automatically uploading of answers and had a few answers in "queue" already, maybe that is important, as another bicycle parking answer was uploaded in the same changeset to OSM.

Maybe this also affects other types of nodes, but as said I didn't want to unintentionally delete stuff from OSM.

**Versions affected**

31.3

**Comment by matkoniecz** [comment]
Since v32 you can undo deletions of places even after you have already uploaded it (#2441)

https://github.com/streetcomplete/StreetComplete/blob/f7550d180ba3a700fa3c2171085d967a6cce62cd/app/src/main/res/raw/changelog.yml#L48

**Comment by matkoniecz** [comment]
BTW, in earlier versions StreetComplete warns that deletions are impossible to undo.

**Comment by Flugschwein** [comment]
Sorry I only searched in open issues, and didn't think about closed ones. Sorry for wasting your time :-)
