### ISSUE TITLE
Support PET as recycling material

### ISSUE THREAD

**Issue by robryk** [streetcomplete/StreetComplete#2885]
**Use case**
Answering recycling_material quest for containers for PET beverage bottles.

In the area I live (German Switzerland) it's quite common to see recycling containers for PET beverage[^] bottles only (sometimes, but not always, accompanied by a separate container for all other plastic bottles). OSM doesn't have a `recycling:` tag for PET bottles (let alone PET beverage bottles). Looking at POIs around Zürich it seems that people use `recycling:PET=yes` (https://overpass-turbo.eu/s/17pQ) for PET beverage bottle containers.

I would like to be able to answer the recycling_material quest for containers that admit only PET beverage bottles. `recycling:plastic_bottles` is too wide (and corresponds to a different, also present in the area, type of container); `recycling:PET` is the stand-in that appears to be used.

**Proposed Solution**

Add `recycling:PET` as an option in recycling_material quest, at least for Switzerland.

[^] They are only for beverage bottles (bottles from other potable liquids are not desired). Smaller ones are sometimes marked with just the word "PET", larger ones usually have a better description.

**Comment by matkoniecz** [comment]
> OSM doesn't have a recycling: tag for PET bottles (let alone PET beverage bottles).

In such case it would be preferable for mappers to select some solution of that.

BTW, StreetComplete has already "plastic bottles" answer. Are there plastic bottles not made from PET?

**Comment by robryk** [comment]
> In such case it would be preferable for mappers to select some solution of that.

So what should I do when I encounter this quest now? Should I just switch it off?

How should one go about to try to cause that to happen?

> Are there plastic bottles not made from PET?

Yes. A good approximation is that all non-transparent bottles are not made from PET (so e.g. the white milk bottles, the typical washing detergent bottle, etc.). There are also non-PET transparent bottles, but they're used more rarely in disposable products (IIRC I've only consciously seen a disposable one sold in a pharmacy).

The reason why I think making this distinction is important is that places where you can dispose of non-PET bottles are rarer than the places where you can only dispose of PET beverage bottles.

**Comment by westnordost** [comment]
> So what should I do when I encounter this quest now? Should I just switch it off?

You could, or, you leave a note instead in that case.

**Comment by robryk** [comment]
I will continue to leave notes for now then.

BTW. When I left a [note](https://www.openstreetmap.org/note/2661738) in such case, someone resolved it by using `recycling:PET=yes`.

**Comment by matkoniecz** [comment]
`recycling:PET=yes` is it place where pet can be recycled in general or only pet bottles?

**Comment by westnordost** [comment]
I hope you can't recycle pets there! 🐶

**Comment by riQQ** [comment]
The wiki defines it as follows:

recycling:PET=yes/no | This usually includes PET (or PETE: Polyethylene terephthalate) bottles
-- | --

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling#Materials

**Comment by Lee-Carre** [comment]
Related, since it's common in [Jersey](http://www.gov.je/recycling) (the island, not the YankLand state of New Jersey).

An option for plastic bags being accepted at a recycling collection point. Typically there's a dedicated receptacle for them, too.
