### ISSUE TITLE
Provide more context for shop_type

### ISSUE THREAD

**Issue by robryk** [streetcomplete/StreetComplete#2886]
**Use case**

When I am asked if a particular shop is still vacant, I can't tell _which_ shop this is about if it's no longer vacant. I just see a building with 2-3 shops in it and don't know which is the one that used to be vacant.

**Proposed Solution**

Provide names of shops in the same building that are already mapped. Consider prominently displaying the address of the vacant shop (to avoid confusion with shops in the neighbouring building).

It might make sense to disable this quest if there is more than one vacant shop in the vicinity (according to the map), to avoid them being mistaken for each other. I haven't encountered this situation in real life though.

**Comment by matkoniecz** [comment]
Getting list of nearby shop may fall into category of "technically possible, outrageous amount of work requires and de facto impossible"

In case of such situations I usually use Vespucci.

**Comment by westnordost** [comment]
Or, leave a note with a photo. Maybe those two other shops are mising and/or also wrong

**Comment by robryk** [comment]
Would you accept contributions? I, perhaps naively, think that finding nearby (same address or close proximity if addresses are incomplete) shops would be similarly complex to the logic that detects [roads under a bridge](https://github.com/streetcomplete/StreetComplete/blob/c225404d6184e337839f06f47af4ed94aef74478/app/src/main/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeight.kt#L93).

**Comment by matkoniecz** [comment]
Note that main difference here is that this info would be needed not at moment when app is scanning for quests (supported already!), but when quests are displayed.

So it would need to fetched when quest is opened, with an acceptable performance. Or pregenerated and updated when related data changes as result of answering other quests).

**Comment by robryk** [comment]
> Or pregenerated and updated when related data changes as result of answering other quests).

Thanks, I haven't thought about possible effects from other quests (a quick scan of currently extant quests indicates that place_name could change such data).

It seems that if we modify an object we regenerate quests that this object is a subject of (i.e. generate them anew and remove old ones). I'll study that code some more and think about a reasonable way to do something similar here (or to look those other objects up when the quest is being solved).

**Comment by matkoniecz** [comment]
> (a quick scan of currently extant quests indicates that place_name could change such data).

Also: answering shop type itself and answering other quests and selecting that object is now vacant/contains other object.
