### ISSUE TITLE
[v32.0-alpha2] Don't show the quest reorder handle icon for the note quest

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2887]
Hi there,

issue #2828 introduced the quest reorder handle icon in order to give the user a hint that the quest order can be changed. However, this icon is currently also shown for the note quest which cannot be moved away from the first position. I guess it would make sense not to show this icon for this entry:

![quest_reorder](https://user-images.githubusercontent.com/32601012/118479922-e3da6580-b711-11eb-9b15-8f207315f951.png)

BTW: Are the "technical reasons" mentioned in https://github.com/streetcomplete/StreetComplete/issues/1815#issuecomment-624313612 and https://github.com/streetcomplete/StreetComplete/issues/1815#issuecomment-624313876 still valid considering the new architecture of v32 or could the note quest be treated like any other quest now, with the ability to be reordered and disabled?

The cycling cat

**Comment by westnordost** [comment]
Yes, still valid. Quests should not be shown when there is a note. This is not an "architectural issue" but a feature.

**Comment by cyclingcat** [comment]
Okay. But the handle of this entry should be removed, shouldn't it?

The cycling cat

**Comment by matkoniecz** [comment]
Pinging @FloEdelmann - author of #2843 (hopefully it is OK)

**Comment by FloEdelmann** [comment]
I already reacted to https://github.com/streetcomplete/StreetComplete/issues/2887#issuecomment-842260979 with a :+1: :wink:
