### ISSUE TITLE
Woodchip path surface

### ISSUE THREAD

**Issue by 10992-osm** [streetcomplete/StreetComplete#2889]
**Use case**
For the quest "What surface does this path have here?", there is not currently an option for woodchip.  The most recent case of this was in [note 2672366](https://osm.org/note/2672366), the picture of which I attach here, in case it is deleted (as I understand note images are).  I have at least once had to leave a note to myself so I could later tag it with `surface=woodchips`, which is the most used tagging ([taginfo](https://taginfo.openstreetmap.org/keys/surface#values) 3569 (the others being `surface=`: `wood_chips` (12), `wood_chippings` (8), `wood_mulch` (6), `wood_chip` (6), `wooden_chips` (3), `wood_shavings` (2), `Bark_wood_Chip` (1); possibly `bark_wood` (9), `wooden_chaff` (3)).  There is currently no documentation on the wiki for this tag.

Other case in [note 2629714](https://osm.org/note/2629714).

![Image of woodchips from note 2672366](https://user-images.githubusercontent.com/83511672/118698532-6e9d8c00-b808-11eb-98e5-db86fd6ae741.jpg)

**Proposed Solution**
There should, in my view, be an option to choose woodchips, which is not currently present.    It is likely only wanted for paths and tracks, rather than any other ways.  The path should then be tagged with `surface=woodchips`.

**Comment by matkoniecz** [comment]
Note that for relatively rare surface tags leaving note (or switching to Vespucci) may be fine. Not sure is `surface=woodchips` popular enough to include it as an option.

**Comment by ygra** [comment]
I noticed the same with surface=stepping_stones and after taking a look at taginfo I thought that it's probably intentional to leave out the very rare surface types. Perhaps the overflow menu could be split into "More answers" and "Other" which creates a note to make that option a bit more visible.

**Comment by matkoniecz** [comment]
Looking now at taginfo: 0.01% of surface values, lower than `bricks` and broken values such as `trail`/`dirt/sand` `paving_stones:30` and duplicates like `soil`.

Is it maybe unusually often present in not-yet tagged places? And appearing in many notes made by StreetComplete? I have not noticed it while reviewing/solving notes left by SC users ( https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#solving-notes )

**Comment by westnordost** [comment]
Woodchips is rare, but at least it is an in-use tag.

I'd say it is only likely to be used on paths (not on roads, tracks). Are paths less often tagged with surface than roads?

**Comment by matkoniecz** [comment]
34.85% of `highway=tertiary` have `surface` - https://taginfo.openstreetmap.org/tags/highway=tertiary#combinations

23.15% `highway=path` has it https://taginfo.openstreetmap.org/tags/highway=path#combinations

22.14% `highway=footway` has it https://taginfo.openstreetmap.org/tags/highway=footway#combinations

**Comment by westnordost** [comment]
Ah well, then let's add it. woodchips is I'd say the most used one in the list of reasonable used values that are not supported in this app yet.
Maybe the picture posted could be used, @10992-osm do you know the license of this one? Is this from you?

**Comment by 10992-osm** [comment]
> Ah well, then let's add it. woodchips is I'd say the most used one in the list of reasonable used values that are not supported in this app yet.
> Maybe the picture posted could be used, @10992-osm do you know the license of this one? Is this from you?

Yes, it's mine.  It's from the note originally linked.  You may use it if it adequate for your needs. Do I need to declare a licence for it since I took it, or is me saying you may use it enough, or…?

**Comment by westnordost** [comment]
Yes, you need to declare the license. Eligible would be public domain (cc-0), cc-by 3.0 or cc-by-sa 3.0

**Comment by 10992-osm** [comment]
> Yes, you need to declare the license. Eligible would be public domain (cc-0), cc-by 3.0 or cc-by-sa 3.0

[CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), I think.

**Comment by FloEdelmann** [comment]
I've uploaded the image to Wikimedia Commons (mentioning your name and license of course): https://commons.wikimedia.org/wiki/File:Woodchips_surface.jpg

And I opened a PR with this change: #2920
