### ISSUE TITLE
Migrate to View Binding (kotlin-android-extensions are deprecated)

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2890]
Since a short while, the 'kotlin-android-extensions' Gradle plugin is deprecated. See https://goo.gle/kotlin-android-extensions-deprecation

The warning suggests to move to View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by sumanabhi** [comment]
hey @westnordost,

I really liked the concept and would love to work on this with you.

**Comment by westnordost** [comment]
Great! Feel free to create a (draft) PR for this and let me know if you need any help / want me to review the code. I just read up on the migration guide, it seems to be quite straightforward but quite a bit of handiwork.

**Comment by sumanabhi** [comment]
hey @westnordost,

I have started working on this, you can have a look at this [Draft PR](https://github.com/streetcomplete/StreetComplete/pull/2894)

also need to discuss something related to some Custom Views and XML as Enabling the ViewBinding comes with lots of changes in XML as well as Custom Layout Views.
