### ISSUE TITLE
Global ranking is missing a digit on OnePlus 6

### ISSUE THREAD

**Issue by Fjeldsoe1** [streetcomplete/StreetComplete#2891]
The bug I have is inside the "My Profile" tab, where the global rank shouldn't be 679. The global rank should have a fourth digit, since I have a friend which is better ranked on the Denmark rank, but he have a fourth digit on his global rank.

![billede](https://user-images.githubusercontent.com/32813257/118771840-4c951f80-b883-11eb-9755-f0148c0ea89d.png)

**How to Reproduce**
I have not done anything except checking my rank on OnePlus 6

**Versions affected**
Android version 10, OxygenOS version 10.3.10. StreetComplete Version 31.3

**Comment by westnordost** [comment]
What is your osm username?

Am 19. Mai 2021 09:22:44 MESZ schrieb Fjeldsoe1 ***@***.***>:
>The bug I have is inside the "My Profile" tab, where the global rank
>shouldn't be #679. The global rank should have a fourth digit, since I
>have a friend which is better ranked on the Denmark rank, but he have a
>fourth digit on his global rank.
>
>![billede](https://user-images.githubusercontent.com/32813257/118771840-4c951f80-b883-11eb-9755-f0148c0ea89d.png)
>
>
>**How to Reproduce**
>I have not done anything except checking my rank on my OnePlus 6
>
>**Versions affected**
>Android version 10, OxygenOS version 10.3.10. StreetComplete Version
>31.3
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2891

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Fjeldsoe1** [comment]
My Osm name is: DjmcFjelle

**Comment by westnordost** [comment]
Can acknowledge the bug, your rank in DK is 103 currently and worldwide, it is 6608, so it is a display problem
