### ISSUE TITLE
AddProhibitedForPedestrians quest not applicable in UK

### ISSUE THREAD

**Issue by tvage** [streetcomplete/StreetComplete#2895]
We are getting a number of users setting roads with foot=use_sidepath, which is invalid in the UK as there is no legal requirement to use a sidepath and almost every road apart from motorways and equivalent can be walked (even if not safe). In the few cases where there is a no pedestrians sign, there is not normally a side path anyway. Hence it would be better if this quest was not offered in the UK.

Regards,
Mike

**Comment by matkoniecz** [comment]
Right now I am confused.

> The law gives pedestrians a number of rights in the UK, some of which might come as a bit of a surprise… 

(...)

> A pedestrian is free to walk along the side of any carriageway other than a motorway or a motorway slip road (although whether they should if there is a footpath nearby is a matter for debate) unless a police officer in uniform is directing traffic. If they order a pedestrian to stop, then the pedestrian must do so. 

https://www.saga.co.uk/magazine/motoring/cars/enjoying/the-rights-you-didnt-know-pedestrians-have (from 2017)

But I also found https://www.gov.uk/guidance/the-highway-code/rules-for-pedestrians-1-to-35 - is it not legally binding?

> Pavements (including any path along the side of a road) should be used if provided.

Or is using "should" not "must" significant here? And it is recommendation pretending to be legally binding?

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/The_Highway_Code

> Certain rules in The Highway Code are legal requirements, and are identified by the words ‘must’ or ‘must not’.

so part about using pavement is a recommendation, not a legal requirement, so `foot=use_sidepath` is not applicable. But `sidewalk=separate` still would be.

**Comment by tvage** [comment]
Yes that's right. The quest also results in people setting foot=no because they consider it unsafe to walk along a road even though it is legally allowed. As almost no highways are prohibited to pedestrians in the UK, the quest is not applicable here. It should only be enabled in countries that have laws restricting where pedestrians can walk.

**Comment by matkoniecz** [comment]
> As almost no highways are prohibited to pedestrians in the UK

Oh, that is important info. If explicit signs forbidding pedestrian traffic are extremely rare then it may make sense to disable it.

Especially if situation "pedestrians are legally allowed but using that would be weird" is a common situation.

**Comment by westnordost** [comment]
It is everywhere very rare that using a road is forbidden to pedestrians.

I'd say what we should do is to remove 
```kotlin
changes.add("foot", "use_sidepath")
```
but leave
```kotlin
changes.modify("sidewalk", "separate")
```

**Comment by tommycrock** [comment]
I've just been asked if it is prohibited for pedestrians to walk on a road in the UK. If I understand this resolution that shouldn't happen any more? I should only be asked if there is a separate pavement instead of no pavement?

**Comment by peternewman** [comment]
Hi @tommycrock ,

No, the question will still be asked in the UK, the only thing that's changed is how the answers are tagged, they are now as follows:
https://github.com/streetcomplete/StreetComplete/blob/04872c5933358e29f47e4b20978da82e2daa7884/app/src/main/java/de/westnordost/streetcomplete/quests/foot/AddProhibitedForPedestrians.kt#L43-L47

The only change being `foot=use_sidepath` is no longer tagged if you respond there is a separate sidewalk/pavement.

**Comment by tvage** [comment]
As almost all roads can be walked on in the UK, and those that are prohibited are very likely to have already been captured I think that StreetComplete should not be asking if pedestrians are prohibited for general highways. We get lots of people setting foot=no because they think it is dangerous or because they are trying to influence a router, not realising that the tag is intended for the legal position not the safety.

**Comment by peternewman** [comment]
> those that are prohibited are very likely to have already been captured

I'm still seeing the quest quite a bit in the UK, so doesn't that imply there are other cases which haven't been captured yet:

- Roads with a separate sidewalk which has been mapped but the road itself not tagged `sidewalk=separate`
- Roads with a separate sidewalk which has **not** been mapped
- Roads without a sidewalk which haven't been tagged `foot=yes` or `foot=no`, ideally with a sidewalk tag too.

Don't we risk missing all of those if we just disable the quest, which doesn't help routers?

> We get lots of people setting foot=no because they think it is dangerous or because they are trying to influence a router, not realising that the tag is intended for the legal position not the safety.

Isn't the solution to that to improve the wording, not just disable the quest?

**Comment by tvage** [comment]
I'm completely happy for the quest to ask whether there is a separate sidewalk and whether it is on one side or both, but asking whether walking is allowed is unnecessary in the UK and is leading to incorrect tagging. The lack of a foot= value should not be taken to mean the road has not been tagged correctly. It is completely unnecessary for the vast majority of roads as almost every road can be legally walked and the default works fine.

**Comment by tommycrock** [comment]
It seems like a weird quest to me as the default is foot=yes, whereas explicitly tagging foot=yes may encourage some foot routers down some very dangerous (yet legal) roads? The sign for no pedestrians isn't even shown in the highway code (no bikes or no cars are). I would at least hope the quest asks if the sign exists (not sure if this happens but have seen follow ups to e.g. weight) but am not convinced we should be asking just because it's been tagged as no sidewalk. I presume the only way to store and share the answer is by modifying the tagging?
