### ISSUE TITLE
Ask if construction begun on green/brownfields

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2896]
### General
Affected tag(s) to be modified/added: [landuse=brownfield](https://wiki.openstreetmap.org/wiki/Tag:landuse=brownfield), [landuse=greenfield](https://wiki.openstreetmap.org/wiki/Tag:landuse=greenfield)
Question asked: **Has construction begun at this brownfield/greenfield?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
If `no` then add checked date and ask again later, if yes the change to `landuse=construction`.

- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
Yes, if under construction then there will be cranes, heavy equiptment etc. If not then it will just be empty land.

- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
90k + 60k

**Comment by matkoniecz** [comment]
The problem is, that at least in my experience, construction often starts on part of green/brownfields.

Or includes larger area, not included in mapped green/brownfields.

Or both.

**Comment by westnordost** [comment]
Green- and brownfields may stay so for decades. I mean, the very fact that they are mapped as such is an indicator that they may actually be more permanent. Also, if it is re-tagged to construction site, what happens after that? There is no "upgrade path" to migrate from construction site to something else, one could just say that a construction site is a little more volatile than a greenfield, so it makes more sense to check if construction finished. But that doesn't change the fact that some mapping must be done after construction finished in any case, be it when before a construction site was tagged or be it when before a green/brownfield was tagged.

**Comment by andrewharvey** [comment]
> The problem is, that at least in my experience, construction very often starts on part of green/brownfields.

Sometimes, yes sometimes no, but you're right that we don't have a good way to handle if only part of the site started development.

> Green- and brownfields may stay so for decades.

Asking yearly shouldn't be overly burdensome for mappers.

> Also, if it is re-tagged to construction site, what happens after that? There is no "upgrade path" to migrate from construction site to something else

Ask if construction has finished? If it has then retag the landuse as was:landuse=construction, or you could ask what kind of landuse is there now, eg residential then tag landuse=residential.
