### ISSUE TITLE
Add support for Thai language

### ISSUE THREAD

**Issue by ppnplus** [streetcomplete/StreetComplete#2900]
A lot of progress have been made in Thai but I can't see the translations being applied in the app, possibly because it's disabled. Translator credits for Thai are also not displayed.

**How to Reproduce**

1. Switch the device's display language to Thai.
2. Open StreetComplete.
3. Open the About menu. There is progress display on how much the app has been translated, but none of the app's messages displayed are in Thai.
**Versions affected**

Android 11 on Samsung S20FE 5G (G781B), StreetComplete v.32.0 downloaded from this repository.

**Comment by matkoniecz** [comment]
Thai is translated in 46% right now. From what I remember @westnordost enables languages translated in about 60%.

**Comment by matkoniecz** [comment]
And big thanks to people translating it into Thai and other languages!

BTW, right now following languages are fully translated (though some improvements may be still useful): English, Dutch, Romanian, Polish, Korean, Italian, Swedish, German, Galician, French, Hungarian, Spanish, Bulgarian, Czech, Croatian, Portugese (BR)

If you know any other language, translation help is appreciated: see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by westnordost** [comment]
Yeah, I think for a Thai, it would look very off-putting to see an app where only every second or so string is translated and the rest is in English. So best would be 100% or something close to it (80%?).

The 60% @matkoniecz mentioned was more like the limit where I start to consider to remove a language again, for the mentioned reason.

But in any case, if you would like to see the fruit of your labour so far, and see the Thai in context, I could prepare a special version of v32.0 with Thai added for you to try out. Would you like that?

**Comment by matkoniecz** [comment]
I documented this to avoid giving misleading info in the future - https://github.com/streetcomplete/StreetComplete/commit/98268338ce84f07898b6331eb538f0de0dbbf29e
