### ISSUE TITLE
Add App-Showcase: Windy Maps

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2901]
This is the current listing of App-Showcases:

![Screenshot_20210525-195628242](https://user-images.githubusercontent.com/614929/119545758-74a8e500-bd93-11eb-80e2-eb8b482445a5.jpg)

I feel like Windy Maps would be cool to be showcased here as well:

https://community.windy.com/topic/10032/windy-launches-new-ios-and-android-app-windy-maps-offline-maps-for-your-travel

**Comment by matkoniecz** [comment]
Note that Windy Maps app has basically invisible attribution (hidden somewhere is setting). For that reason I would be against adding it to the showcase.

From what I remember I have not contacted them recently that they should fix attribution.

**Comment by westnordost** [comment]
See magic earth

**Comment by HolgerJeromin** [comment]
ref #2902

**Comment by RubenKelevra** [comment]
> No, because this would be like an advertisement. I did not include any other OSM end user app as well.

Not sure what that "advertisement" would be about. The App is free of charge and has no in-app payment options. 

It's just a company who developed a pretty cool navigation app for Android and iOS for free. 

> Also, only completely open source software is linked.

Maybe we could add a special category for non-free Apps which has no payment options? 🤔

I'm sure users appreciate the recommendations to use apps which use OSM data they contributed to. While open source software is nice, I don't think it's necessary to restrict us to only show them.

_Originally posted by @RubenKelevra in https://github.com/streetcomplete/StreetComplete/issues/2902#issuecomment-856013510_

**Comment by RubenKelevra** [comment]
@matkoniecz wrote:

> Note that Windy Maps app has basically invisible attribution (hidden somewhere is setting). For that reason I would be against adding it to the showcase.
> 
> From what I remember I have not contacted them recently that they should fix attribution.

In this case we should remove KartaView as well. Just found it via StreetComplete's showcase.

It shows a company name as source for the map data, which couldn't be more wrong.

Only when the user clicks on the information icon about the company, you find out that its actually OpenStreetMap-Data.

![IMG_20210808_100844](https://user-images.githubusercontent.com/614929/128625685-cd035bf4-9bf4-4cec-b92f-25ff01a746ef.jpg)

**Comment by westnordost** [comment]
The map view is not their product, crowd sourced street view imagery is. The map view in which you can browse the imagery could be google maps for that matter.  

What matters is that it is a tool and a source to contribute to OpenStreetMap. This is why it is included in the list, it is not a product for the end user (nav or map app)

On 8 August 2021 10:15:26 CEST, ***@***.***" ***@***.***> wrote:
***@***.*** wrote:
>
>> Note that Windy Maps app has basically invisible attribution (hidden
>somewhere is setting). For that reason I would be against adding it to
>the showcase.
>> 
>> From what I remember I have not contacted them recently that they
>should fix attribution.
>
>In this case we should remove KartaView as well. Just found it via
>StreetComplete's showcase.
>
>It shows a company name as source for the map data, which couldn't be
>more wrong.
>
>Only when the user clicks on the information icon about the company,
>you find out that its actually OpenStreetMap-Data.
>
>![IMG_20210808_100844](https://user-images.githubusercontent.com/614929/128625685-cd035bf4-9bf4-4cec-b92f-25ff01a746ef.jpg)
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2901#issuecomment-894761333

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
