### ISSUE TITLE
Add App-Showcase: Magic Earth

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2902]
This is the current listing of App-Showcases:

![Screenshot_20210525-195628242](https://user-images.githubusercontent.com/614929/119546175-ebde7900-bd93-11eb-9cf6-2615a86e49a8.jpg)

I feel like Magic Earth would be cool to be showcased here as well:

https://www.magicearth.com/

**Comment by matkoniecz** [comment]
Note that Magic Earth App has basically invisible attribution (tiny text on bottom of the map, disappears almost immediately). For that reason I would be against adding it to the showcase.

**Comment by westnordost** [comment]
No, because this would be like an advertisement. I did not include any other OSM end user app as well.

Also, only completely open source software is linked.

**Comment by RubenKelevra** [comment]
> No, because this would be like an advertisement. I did not include any other OSM end user app as well.

Not sure what that "advertisement" would be about. The App is free of charge and has no in-app payment options. 

It's just a company who developed a pretty cool navigation app for Android and iOS for free. 

> Also, only completely open source software is linked.

Maybe we could add a special category for non-free Apps which has no payment options? 🤔

I'm sure users appreciate the recommendations to use apps which use OSM data they contributed to. While open source software is nice, I don't think it's necessary to restrict us to only show them.

**Comment by mnalis** [comment]
@RubenKelevra I for one would highly dislike if SC was promoting non-free software. And it would get demoted as app with [anti-features](https://f-droid.org/en/docs/Anti-Features/) on f-droid app store too. But it is westnordost choice, of course.

**Comment by RubenKelevra** [comment]
@mnalis which antifeature would this request apply to?

Ads?

Because the App has a page with recommendations the user can visit which links to a website which offers a free app? 🤔

**Comment by mnalis** [comment]
@RubenKelevra I was thinking of the one described "`promotes other non-libre apps or plugins`"

**Comment by RubenKelevra** [comment]
@mnalis 

I feel like this is more geared towards apps which can be extended by downloading additional apps, which are not free. Like OsmAnd has some.

**Comment by RubenKelevra** [comment]
@westnordost wrote:

> Also, only completely open source software is linked.

I couldn't find the source code beeing released for the mapillary android app and despite [promises in 2018](https://blog.mapillary.com/update/2018/11/06/capture-sdk.html) the android SDK never appeared on Github.

So why is this app allowed in the list while obviously not open source at all? 🤔

**Comment by westnordost** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/2901#issuecomment-894806855

**Comment by mnalis** [comment]
Mapillary **android app** is definitely not open source / free software (even the issue  that tracked that had [disappeared](https://github.com/mapillary/mapillary_issues/issues/1124)), but it's other interfaces like https://github.com/mapillary/mapillary_tools and https://github.com/mapillary/josm-mapillary-plugin are free software / open source.

So I guess it's listed under same criteria like the other OpenStreetMap-based services which do not have android app at all (like [uMap](http://umap.openstreetmap.fr/en/), [disaster.ninja](https://disaster.ninja/live/) etc.)
