### ISSUE TITLE
Achievement oddness after upgrade to 32.0

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#2903]
Android updated me to the latest 32.0 release today. After my first round of offline Streetcompleting I was presented with 20+ achievement notifications that had to be dismissed individually. Most seemed to be related to the number of days I have contributed via the app, although a few were related to number of edits etc. I think some achievements were displaying out of order, but I wasn't paying too much attention as dismissing them quickly became tedious.  

I assume this many achievements at once is a bug? This is the use after upgrading so I doubt I've waited too long between uploads.  

The "star" counter was reset as part of the upgrade, but oddly the achievements seem to require knowledge of previous app contributions. 

**How to Reproduce**

1. Upgrade to 32.0
2. Set Streetcomplete to offline mode. 
3. Cache an area.
3. Roam and do some quests.
4. Manual upload over WiFi.  

**Versions affected**
Streetcomplete v32.0
Android: 10

**Comment by matkoniecz** [comment]
a bit offtopic info:

> The "star" counter was reset as part of the upgrade, but oddly the achievements seem to require knowledge of previous app contributions.

Both should be synchronized across devices and installs, so star count should be eventually restored.

**Comment by westnordost** [comment]
What level did they show, the notifications? Was it like from the start all over again?

**Comment by InsertUser** [comment]
I think the most common one started the levels from scratch. Although the notifications were familiar I did think at one point that it might have been a new achievement that I was at a high level for at its first introduction. I started to see other contribution based ones mixed in later on. My previous stars had restored themselves when I checked yesterday.

**Comment by westnordost** [comment]
Well, as long as your statistics are not re-synced yet, the app does not know if you **really** only got 0 quests solved so far or if the data has not been downloaded yet. So quests you solve will trigger the achievements again.

Given that this is only likely to happen on reinstall or once on upgrade to v32.0, I think I will not expend time on this to mitigate this somehow.
