### ISSUE TITLE
New "edit history" feature menu bar doesn't appear

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2904]
Hi there,

the new "edit history" feature introduced with v32.0 never shows the quest bar in the left side on my device! At first I didn't understand at all how this feature generally works (the menu item shows all quests I recently solved but what to do with them?) until I found a nice video in one of the tickets here a few days ago which displays this bar.

There could be a connection to the similar issue #2787 with the exception that I have _never_ seen this bar so far while @Helium314 couldn't reproduce this behaviour reliably.

Cubot Quest, Android 9.0 (= the same version as @Helium314 - maybe a hint?)

Let me know if you want me make some tests or provide logs.

The cycling cat

**Comment by westnordost** [comment]
What happens when you tap on the button then?

**Comment by cyclingcat** [comment]
Do you mean the quest button? The object gets highlighted (as it would if it were a real quest), but logically no quest appears.

The cycling cat

**Comment by westnordost** [comment]
I mean the undo button

**Comment by cyclingcat** [comment]
A menu consisting of two items appears: "Show edit history", "Revert latest edit" (roughly backtranslated). If I tap on the first one, just the icons of the recently solved quests appear. See the video:

https://user-images.githubusercontent.com/32601012/119562906-2e5d8100-bda7-11eb-89b1-6feef8188c4e.mp4

The cycling cat

**Comment by westnordost** [comment]
Thanks, a video was helpful. Hmm, do you have animations off?

**Comment by matkoniecz** [comment]
> Hmm, do you have animations off?

I have animation duration scale set to off, can reproduce this bug.

Setting it to normal value fixes it, so this guess was correct.

BTW, there are some other glitches with disabled animations. Is it considered as a bug to have a minor visual glitches with disabled animations? For example beginning of bouncing balls has them teleporting around.

**Comment by westnordost** [comment]
Weird, the bouncing balls do actually not animate. Well, I guess minor glitches are minor glitches, so technically bugs, though maybe bundle them in one bug or something? Wouldn't want this bugtracker to be flooded with nothingness.

**Comment by cyclingcat** [comment]
Indeed, animations are disabled as much as possible on my devices. This is the setting that obviously breaks the display of the side bar on my phone. As soon as I change this, the bar gets displayed:

![animations](https://user-images.githubusercontent.com/32601012/119612721-8377b200-bdfc-11eb-888c-f2128cc34775.png)

The cycling cat
