### ISSUE TITLE
Links in notes should be clickable

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2905]
It would be nice if links in notes were clickable.

I noticed this as I have it set to show all notes and when I added a new note with a photo the link was not clickable.
On that note, it does seem a bit odd to add a note through the app and have it appear as a quest to be solved, but having read the comments where this change was discussed, that does seem to be the desired behaviour when the "show all notes" option is on.

The text in the note popup is selectable and then Android seems to recognise that it's a url and auto selects the whole thing on a long press and adds a tooltip option to open the link, but this isn't very intuitive.

**Comment by peternewman** [comment]
> On that note, it does seem a bit odd to add a note through the app and have it appear as a quest to be solved, but having read the comments where this change was discussed, that does seem to be the desired behaviour when the "show all notes" option is on.

OT, but that's been raised with comments from https://github.com/streetcomplete/StreetComplete/issues/2692#issuecomment-846636228 onwards
