### ISSUE TITLE
Bouncing balls are teleporting with animation duration scale set to off

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2906]
**How to Reproduce**

animation duration scale set to off

maybe have also many edits?

**Versions affected**
v32.0

Looking at animation it seems that resizing gets broken?

https://user-images.githubusercontent.com/899988/119566281-40d9b980-bdab-11eb-9ab8-8f53ca2a7686.mp4

**Comment by matkoniecz** [comment]
I mentioned also other glitches, but I realised that I either do not remember them or cannot reproduce them, this seems the biggest one.

Still priority is incredibly minor here and not worth significant research.

**Comment by westnordost** [comment]
Okay, that's a glitch. But it looks really cool, actually... like a firework!
