### ISSUE TITLE
App currently not available on Google Play

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2909]
### StreetComplete has been removed from Google Play

The message:

![image](https://user-images.githubusercontent.com/4661658/119580075-0595b580-bdc0-11eb-850a-94ba2c7a3aae.png)

---

I couldn't find anything in the linked articles

- [Permissions](https://play.google.com/about/privacy-security-deception/permissions/)
- [Location Permissions](https://support.google.com/googleplay/android-developer/answer/9888170#location-permissions)
- [Help Center](https://support.google.com/googleplay/android-developer/answer/9799150)

...that would explain in what way the app is not compliant with the Developer Program Policies. Apparently it is about background location permissions. And so, the link to "Developer Permission Declaration" leads to a page that looks like that...
![image](https://user-images.githubusercontent.com/4661658/119580447-b4d28c80-bdc0-11eb-9f92-62d3254ede66.png)
...which makes sense, because the app does not use any background location permissions.

What doesn't make sense is that the app got removed from Google Play.

**Comment by westnordost** [comment]
I already wrote a message to the policy support team. Content:

> It is claimed that the app does not comply with the Location Permissions policy and it has been removed from Google Play. I believe this is a mistake:
> 
> The app DOES NOT request location in the background or foreground service
> The app DOES NOT display any ads or track its users in any way, i.e. transmit their location anywhere
> The app DOES request location when the app is in foreground. The location is used to
> 1. download data in the vicinity of the user. This data is indispensable for the core functionality of the app
> 2. display the user's position for orientation on the map, like any map-based app does
> 
> The purpose of the location permission is clearly communicated to the user.
> 
> PLEASE NOTE: 
> In the Google Play Console -> App content -> Sensitive app permissions
> I am UNABLE to make any statement because there is only the text "Your app doesn't request sensitive permissions, so you don't need to do anything here" and nothing else. A bug in the Play Console?

**Comment by westnordost** [comment]
It is possible that even if the app does not have the `ACCESS_BACKGROUND_LOCATION` permission in its manifest, a dependency has it so that in the merged manifest, the app will request that permission.

Android Studio has this handy feature where one can directly view the merged manifest:

![image](https://user-images.githubusercontent.com/4661658/119581267-82c22a00-bdc2-11eb-8173-af50289f8f99.png)

**Result: Nope, contrary to the claim, no background permission is requested.**

So, I am out of ideas. I am now almost 100% sure this is a bug in their policy-checker-bot.

**Comment by matkoniecz** [comment]
If someone wants to install it in meantime:

https://github.com/streetcomplete/StreetComplete/releases/tag/v32.0 has an apk file (you will need to enable installing apk files in settings, note that you should install only trusted apk files and some are actually malicious)

https://f-droid.org/en/packages/de.westnordost.streetcomplete/ has not yet made v32 available but has older versions

-----------------------

> So, I am out of ideas. I am now almost 100% sure this is a bug in their policy-checker-bot.

Or in display and actual complaint is something else?

Though now I remember that MAPS.ME fork also got removed with claim that map app does not need location permission...

I will check have they also got "doesn't comply with location permission policy".

-----------------------

Argh. Do you think that it is worth posting "buggy automatic review by Google randomly bans app" in places like https://news.ycombinator.com/ ?

With goal of being noticed by human in Google who actually will not be ignored?

Or is it better to wait a bit and hope that this email will be actually processed?

**Comment by matkoniecz** [comment]
Not sure exact ban reason for Organic Maps.

They are back but with a different app id, so maybe they uploaded it from a different account? See https://github.com/organicmaps/organicmaps/commit/83ee96607ded948c2041f66e89ee1dabbad4c4a1

**Comment by peternewman** [comment]
Looks like it was probably a name clash not a ban, unless you saw an actual ban:
https://github.com/organicmaps/organicmaps/issues/97

**Comment by dbf256** [comment]
In organicmaps chat they mentioned that there was an issue with location permission, so their app was removed. @westnordost I think you can check with their team how they solved it (see contacts at https://organicmaps.app/) or check in their repo are there any related commits.

**Comment by matkoniecz** [comment]
@dbf256 I just asked on one of their Telegram channels.

**Comment by simonpoole** [comment]
You could all just stop widely speculating and ask somebody that knows what is going on? See https://twitter.com/vespucci_editor/status/1330997796745457665

google has two different definitions of background access of location data that contradict each other, but the important bit that -any- potential access of location data while the app is not visible (for example changing something in the settings or quickly using a different app), including access in a "foreground service", is what is relevant. As this is clearly the case with SC, you simply need to fulfill googles criteria  (notices, video, privacy policy) and all will be fine and dandy. 

Don't bother trying to reason, you are only communicating with bots.

**Comment by westnordost** [comment]
Good to know that this is a wider phenomen and does not only affect SC. Looks like Google bots will have to read through quite a few appeals then. 

Anyway, SC does not even use the users' location in a foreground service (unlike Vespucci, SC does not have the feature to record a GPX track) and the privacy policy is very clear on for what the location is used,  always has been.

So, I think your assesment/assumption may be wrong. But you are right, no sense in speculating, let's wait on what is their response. I'll post it here as soon as I get it.

Am 26. Mai 2021 14:00:42 MESZ schrieb Simon Poole ***@***.***>:
>You could all just stop widely speculating and ask somebody that knows
>what is going on? See
>https://twitter.com/vespucci_editor/status/1330997796745457665
>
>google has two different definitions of background access of location
>data that contradict each other, but the important bit that -any-
>potential access of location data while the app is not visible (for
>example changing something in the settings or quickly using a different
>app), including access in a "foreground service", is what is relevant.
>As this is clearly the case with SC, you simply need to fulfill googles
>criteria  (notices, video, privacy policy) and all will be fine and
>dandy. 
>
>Don't bother trying to reason, you are only communicating with bots.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2909#issuecomment-848709833

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by simonpoole** [comment]
> 
> Good to know that this is a wider phenomen and does not only affect SC. Looks like Google bots will have to read through quite a few appeals then. Anyway, SC does not even use the users' location in a foreground service (unlike Vespucci, SC does not have the feature to record a GPX track) and the privacy policy is very clear on for what the location is used, always has been. So, I think your assesment/assumption may be wrong. But you are right, no sense in speculating, let's wait on what is their response. I'll post it here as soon as I get it. 

I just made the point wrt the foreground service as google explicitly states in their documentation that accessing location in a foreground service is not background access, to illustrate that it has literally nothing to do with any of their other policies and definitions. I suspect that the -only- use that could be compliant without the declaration is  "single use on user interaction" location access. Their privacy policy requirements require mentioning specific words so you should review the policy too.

**Comment by westnordost** [comment]
Ah, ok

Am 26. Mai 2021 14:30:13 MESZ schrieb Simon Poole ***@***.***>:
>> 
>> Good to know that this is a wider phenomen and does not only affect
>SC. Looks like Google bots will have to read through quite a few
>appeals then. Anyway, SC does not even use the users' location in a
>foreground service (unlike Vespucci, SC does not have the feature to
>record a GPX track) and the privacy policy is very clear on for what
>the location is used, always has been. So, I think your
>assesment/assumption may be wrong. But you are right, no sense in
>speculating, let's wait on what is their response. I'll post it here as
>soon as I get it. 
>
>I just made the point wrt the foreground service as google explicitly
>states in their documentation that accessing location in a foreground
>service is not background access, to illustrate that it has literally
>nothing to do with any of their other policies and definitions. I
>suspect that the -only- use that could be compliant without the
>declaration is  "single use on user interaction" location access. Their
>privacy policy requirements require mentioning specific words so you
>should review the policy too.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2909#issuecomment-848728356

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Do you have a link to the doc that mentions the specific words that must be mentioned? 
(I didn't consider bot-optimising the privacy statement yet, LOL)

Am 26. Mai 2021 14:30:13 MESZ schrieb Simon Poole ***@***.***>:
>> 
>> Good to know that this is a wider phenomen and does not only affect
>SC. Looks like Google bots will have to read through quite a few
>appeals then. Anyway, SC does not even use the users' location in a
>foreground service (unlike Vespucci, SC does not have the feature to
>record a GPX track) and the privacy policy is very clear on for what
>the location is used, always has been. So, I think your
>assesment/assumption may be wrong. But you are right, no sense in
>speculating, let's wait on what is their response. I'll post it here as
>soon as I get it. 
>
>I just made the point wrt the foreground service as google explicitly
>states in their documentation that accessing location in a foreground
>service is not background access, to illustrate that it has literally
>nothing to do with any of their other policies and definitions. I
>suspect that the -only- use that could be compliant without the
>declaration is  "single use on user interaction" location access. Their
>privacy policy requirements require mentioning specific words so you
>should review the policy too.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2909#issuecomment-848728356

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by simonpoole** [comment]
Just checked seems that I misremembered: the required text is for the notice that you have to display the first time location data is used, I simply used a variant of the same for the privacy statement to be on the safe side (as they will literally be checking with a bot).

The requirements, not only wrt the text, are listed here:

https://support.google.com/googleplay/android-developer/answer/9799150#prominent_disclosure&zippy=%2Cstep-provide-prominent-in-app-disclosure

**Comment by matkoniecz** [comment]
@westnordost Is there some useful way how can I help here or should I rather finish satellite view PR?

**Comment by westnordost** [comment]
No, I'll wait on their answer.

**Comment by smichel17** [comment]
https://github.com/mpcjanssen/simpletask-android/issues/1102

**Comment by westnordost** [comment]
How is this relevant?

**Comment by smichel17** [comment]
Sorry, I pasted the link and then switched apps, planning to come back and edit later; didn't realize I'd posted. Edited now.

**Comment by westnordost** [comment]
I still did not get a reply from Google yet, so I looked into what policies the app **would have to** fulfill **if** the app used the background location permission. In that case, it does not fulfill:

> You must provide an in-app disclosure of your data access, collection, use and sharing. The in-app disclosure:
> - Must be within the app itself, not only in the app description or on a website;
> - Must be displayed in the normal usage of the app and not require the user to navigate into a menu or settings;
> - Must describe the data being accessed or collected;
> - Must explain how the data will be used and/or shared;
> - Cannot only be placed in a privacy policy or Terms of Service; and
> - Cannot be included with other disclosures unrelated to personal or sensitive data collection.
> 
> The language in the disclosure MUST include the following elements:
>
> 1. The term 'location'
> 2. A list of all the features that use location in the background

So, currently the information how the location permission is used is displayed in the in-app privacy statement and also in case the user denies the permission, in a separate dialog / toast but not **before** the location permission is requested.

**Comment by westnordost** [comment]
So I changed the behavior to be like this

<img src="https://user-images.githubusercontent.com/4661658/120121523-4452b380-c1a4-11eb-81ac-5983bcaa70ff.png"/> <img src="https://user-images.githubusercontent.com/4661658/120121524-474da400-c1a4-11eb-8365-787303f65950.png"/> <img src="https://user-images.githubusercontent.com/4661658/120121526-49affe00-c1a4-11eb-930f-1635d52f5697.png"/>

1. The location permission is now (unnecessarily) mentioned in the 2nd step of the tutorial. Unnecessarily because basically in the first step of the tutorial, it is already mentioned that "quests are downloaded in your vicinity". But Google wants the keyword "location" and "a list of features" which would include the trivial "showing the users position on the map". If Google recognizes their mistake, I'd maybe shorten that sentence.
2. The location permission is now asked **after** the tutorial, not basically at first app start (during step 1 of the tutorial). The downside of this is that the app will not zoom to the users location and have possibly downloaded the quests already when the user exists the tutorial. On the other hand, it's clearer to the user this way. So personally, I think it is better this way. When the map view is visible in the background, it is also clearer from the context why location permission is necessary.
3. Once after the user denied the location permission after the tutorial, a dialog with an explanation is shown, this is pretty similar to the way it was before, only that the text is a little longer now (i.e. "lists all features").

Finally, I modernized the code in that class a bit. The code there however is very complex and there are many different cases to cover. I'd be grateful if some of you would check out the current master and report any issues.

**Comment by matkoniecz** [comment]
> The downside of this is that the app will not zoom to the users location

I think that it is not better at all.

I made a clean install.

I got placed somewhere in Asia and needed to manually locate me (press location arrow on a screen border). This seems to not be obvious to someone new.

**Comment by matkoniecz** [comment]
Not sure is it implementable and Google-bot-safe but I would ask for permission between second and third tutorial step.

**Comment by westnordost** [comment]
What do you mean, you got placed in Asia? By default (with no location), the world map will be shown. Once location is known, the view should zoom in to your location.

>  I would ask for permission between second and third tutorial step.

Yeah, I tested that as well. But this had the problem that had a few problems:
1. the "Deny" button is at the same place as the "Next" button. If one clicks through the tutorial without reading (I expect quite a few people do this), then the location is denied . This is much less likely to happen if the view changes and the map is visible in the background
2. probably solveable, but the way I implemented it, the permission was asked during transition to step 3, so the animation was not visible

**Comment by matkoniecz** [comment]
> What do you mean, you got placed in Asia?

It zoomed me to some random location in Asia. I am now trying to reproduce it (on a physical device, no emulator only bug this time).

It seems that tapping a lot on tutorial screens can cause initial map view to show a random(?) location worldwide - usually ocean. 

But second part, zooming to the current user location seems to work fine even then - but sometimes it also fails. Not sure how to trigger this one, I though I can achieve it by switching to a different app works - it also kills temporarily mpa.

Overall I suspect upstream Tangram bug. And requires doing weird things to trigger, solely for little confusion.

BTW, is it happening, again, only on my phone?

Full bug:

https://user-images.githubusercontent.com/899988/120184922-d47b1200-c211-11eb-9d0c-002165a7a316.mp4

Asia waves hello (just to demonstrate that yes, you can be placed in Asia):

https://user-images.githubusercontent.com/899988/120184699-8f56e000-c211-11eb-825d-11c7370727ac.mp4



> Yeah, I tested that as well. But this had a few problems:

Good points, and in this case asking was better than testing on my own :)

**Comment by westnordost** [comment]
I think if you move the map (move, pinch, zoom, ...) in any way before the GPS location is discovered and the zoom initiated, then the app won't automatically zoom to your location. Because then you are not in the "follow my gps location" mode.

**Comment by westnordost** [comment]
> Good points, and in this case asking was better than testing on my own :)

What?

**Comment by westnordost** [comment]
- Fixed that the map can me moved by reaching through the tutorial background (upper half did not capture touch input)
- Made it so that any panning **before** a location is known does not disable the "follow my gps location" mode.

**Comment by peternewman** [comment]
Out of interest, if you keep hitting deny, can you actually use SC without the location permission? Does it add an extra tag/note into commits when you do so? I guess it's a similar scenario to if you override the I'm nearby warning, although you could be further away?

**Comment by smichel17** [comment]
You can. And it's not "keep" hitting deny; SC will only ask for location permission once at the start, and when you press the location button, if not previously granted. When solving quests, it will show you a dialog reminding you that SC is intended for on-site surveying. If you select the option to the effect of "proceed anyway", the same dialog will appear for the next quest, but this one will have a checkbox to not show it any more this session (as will subsequent ones, if you don't select the checkbox). So in summary, there's a few extra taps each session, you'll need to manually download quests, and you won't have the dot to orient yourself, but otherwise it works the same.

**Comment by matkoniecz** [comment]
>> Good points, and in this case asking was better than testing on my own :)

> What?

I thought about implementing it - and in such case I would duplicate what you tried already.

> Out of interest, if you keep hitting deny, can you actually use SC without the location permission? 

Yes, but you need to pan map and fetch quests on your own.

**Comment by westnordost** [comment]
So but you remain on your standpoint that it would be better to have the dialog pop up between step 2 and step 3?

**Comment by matkoniecz** [comment]
> So but you remain on your standpoint that it would be better to have the dialog pop up between step 2 and step 3?

No, I was convinced by what you discovered in your testing.

**Comment by westnordost** [comment]
Ok, I guess what is missing now is that Streetcomple should request background location because now it fulfills the policy for that 🙄, haha.

I'll wait for a reply from google until tomorrow, if there is nothing from them, I'll just release v32.1

**Comment by matkoniecz** [comment]
> Ok, I guess what is missing now is that Streetcomple should request background location because now it fulfills the policy for that roll_eyes, haha.

`if(requestsBackgroundLocation(appId) XOR fullfillsRequirementsForBackroundLocation(appId)) banApp(appId);`

**Comment by westnordost** [comment]
Jesus christ!

![upload_streetcomplete_error](https://user-images.githubusercontent.com/4661658/120313255-05bf1500-c2da-11eb-901b-0375db5fdd64.png)

This helpful message comes up every time I try to upload the new release!

**Comment by westnordost** [comment]
Alright, with Chrome it worked. I hope I don't have to use Chrome now always for that. 

After submitting the new update for review, I got the message that review can take up to a week.

**Comment by HolgerJeromin** [comment]
> Alright, with Chrome it worked. I hope I don't have to use Chrome now always for that.

Try [Vivaldi](https://vivaldi.com/de/). Is the same browser engine but without most/all google stuff

**Comment by simakuutio** [comment]
Got upgrade from Play Store so app is back. This ticket can be closed, I guess.

**Comment by matkoniecz** [comment]
Confirmed by someone who has it not installed :)

**Comment by westnordost** [comment]
Huh, I didn't get any email about it or any other feedback in the Google Play console.

Well okay then...

**Comment by westnordost** [comment]
After 3 weeks, got this template reply:

> Hi Tobias,
>
> Thank you for your patience.
>
> Due to adjusted work schedules at this time, we are currently experiencing longer than usual process times and we appreciate your understanding. 
>
> I see that your app, StreetComplete (de.westnordost.streetcomplete), is published on Google Play, but it still violates Google Play Policy. I’ve included details below about the specific issue with your app and what you can do to keep your app compliant on Google Play.
>
> **Step 1: Review the policy violation with your app**
>
> We found that your app is not compliant with the Location Permissions policy, or we were unable to review and verify your in-app experience for compliance with this policy.
>
> If you have determined that your app does not require location in the background, complete the following steps to remove background usage and reach compliance:
>
>   - For any APK targeting Android 10 or newer (SDK level 29 or higher):
>     - Remove the  ACCESS_BACKGROUND_LOCATION permission from your app APK or app bundle
>     - [If minimum SDK level is 28 or lower] If you’re using ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION, examine your code paths and restrict usage to foreground purposes only (learn more)
>      - You should no longer see the Location declaration listed under App Content
>  - For any APK targeting Android 9 or older (SDK level 28 or lower):
>    - If you’re already using ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION, examine your code paths and restrict usage to foreground purposes only (learn more)
>    - In your console declaration, select “No” to the question “Does your app access location in the background in APKs or app bundles targeting Android 9 or older?”
>
> Note: If your app targets SDK level 29 or higher but minimum SDK level is 28 or lower, for apps that use either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION, you must also check your code paths and restrict usage to foreground purposes only (even if you have removed ACCESS_BACKGROUND_LOCATION).
>
> If you are still facing issues after examining your code paths and restricting usage to foreground purposes only, please review any third party SDKs used in the app that may be accessing location in the background.
>
> For additional help, you can review the following resources: 
>
>  - Location permissions - Developer Policy Center
>  - Requesting access to background location - Play Console Help
>  - Evaluate background location access & Background location access checklist - Documentation for app developers
>  - Google Play PolicyBytes on YouTube
>
> Please update your app to fix this issue. You may also want to double check that your app complies with all other Developer Program Policies.
>
> **Step 2:  Submit a compliant update or remove permissions**
>
>   - Make the necessary updates to address the issue(s) identified above.
>     - To continue using location in the background, submit or update your Developer Permission Declaration along with a compliant version of your app in the Play Console for approval.
>     - If your app is not eligible to access location in the background or does not meet requirements for accessing location in the background, please remove the permission from your manifest and in-app functionality.
>   - Double check that your app is compliant with all other Developer Program Policies 
>   - Sign in to your Play Console and submit the update to your app.
>
> Please let me know if you have any other questions. We thank you again for your patience while we reviewed your issue.
> Regards,
> Billie
> The Google Play Team
>
> Please visit the Google Play Developer Policy Center and Google Play's Academy for App Success to learn more about building policy compliant and high quality apps. You can also visit the Android Developers Blog for the latest Android and Google Play news for app and game developers.

**Comment by westnordost** [comment]
My reply:

> Hello Billie
>
> I am sorry to say that, but your reply is not helpful: It comes almost 3 weeks late and ignores everything I wrote in the appeal. It really looks very much like a automatic template reply.
>
> Still, for your convenience, I will summarize in bullet points:
>
> - The app DOES NOT use the background location permission for SDK level 29 and higher
>
>  - The app DOES NOT use background location on SDK level 28 and lower. There are no code paths in the apps or any dependencies that use location in the background: Not in a background service or anywhere else
>
>  - The app DOES actually fulfill all the policies to use background location, even though it does not use it
>
>> To continue using location in the background, submit or update your Developer Permission Declaration along with a compliant version of your app in the Play Console for approval.
>
>  - I am CAN NOT submit or update a Developer Permission Declaration because the link leads to a page that simply says "Your app doesn't request sensitive permissions, so you don't need to do anything here". See attached screenshot, this is what I see.
>
> \- Tobias Zwick

Attachment:
<img width="320" alt="Screenshot 2021-06-14 at 21 41 32" src="https://user-images.githubusercontent.com/4661658/121952567-b73f5b00-cd5c-11eb-8ae4-7e87415a36d2.png">

**Comment by westnordost** [comment]
@simonpoole let me guess, the above reply is exactly the same reply you got?

**Comment by simonpoole** [comment]
> 
> 
> @simonpoole let me guess, the above reply is exactly the same reply you got?

Not going to do a word for word comparison, but it looks like the canned reply we got on our 1st appeal when we were still arguing that we don't access location in the background.

**Comment by westnordost** [comment]
Communication is faster now. Maybe they had technical problems and/or I am communicating with a real person now. Their reply: 



> Hi Tobias,
> Thanks again for contacting the Google Play team.
> 
> Kindly understand that I'm not able to provide further details as much as I'd like to help.
> 
> As informed in our previous email, if you haven't already addressed in the latest app update, please check your code paths and restrict usage to foreground purposes only even if you have removed ACCESS_BACKGROUND_LOCATION, if your app uses either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION and target SDK level is 29 or higher but minimum SDK level is 28 or lower. Also as a reminder, please note that any third party SDKs used in the app that may be accessing location in the background.
>
> We appreciate your understanding.
> 
> Thanks for your continued support of Google Play.
> Regards,
> Billie
> The Google Play Team
> 
> Please visit the Google Play Developer Policy Center and Google Play's Academy for App Success to learn more about building policy compliant and high quality apps. You can also visit the Android Developers Blog for the latest Android and Google Play news for app and game developers.

So, they again did not read my email and this is another canned reply.

**Comment by westnordost** [comment]
My reply:

> Hello Billie
> 
> Even though I find it curious, to say the least, that apparently the exact details for the decisions made are not documented,
> 
> I am not asking for help and I am not asking for further details.
> 
> I am refuting both the claims made by the Google Play Team that the app
> 
> - does use background location at all (yes, also below SDK level 28 and also by some dependency), and...
> - that it does not fulfill the policies for using background location
>
> In other words, your decision has been made in error (twice).
> 
> Please refer to my last email for details. Let me know if you have any questions.
> 
> - Tobias Zwick

**Comment by westnordost** [comment]
And their reply

> Hi Tobias,
> Thanks again for contacting the Google Play team.
> 
> As mentioned in our previous conversation, please note that even if an app does not have ACCESS_BACKGROUND_LOCATION permission, it's still possible that the app accesses location in background caused by any third party SDKs used in the app, if the app's target SDK level is 29 or higher but minimum SDK level is 28 or lower and uses either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION.
> 
> In case you need further information, you can always refer back to the below pages.
> 
> - Location permissions - Developer Policy Center
> - Requesting access to background location - Play Console Help
> - Evaluate background location access & Background location access checklist - Documentation for app developers
> - Google Play PolicyBytes on YouTube
>
> We again appreciate your understanding.
>
> Thanks for your continued support of Google Play.
> Regards,
> Billie
> The Google Play Team
> 
> Please visit the Google Play Developer Policy Center and Google Play's Academy for App Success to learn more about building policy compliant and high quality apps. You can also visit the Android Developers Blog for the latest Android and Google Play news for app and game developers.

Only now I noticed that parts of it is a carbon copy of the previous email but the first paragraph is not, it is just the same but written in different words. So am I conversing with a bot, or not? Does the bot have different phrasings at hand to appear human? If it is a human, why can he not tell me how they reached that conclusion, not documented at all? Policy-checker-bot just outputs "violation" with no explanation? So many questions.

**Comment by westnordost** [comment]
So, my answer... I am dedicated to get to the bottom of this. They can not forever palm us of with canned replies.

> Hello Billie
>
> You already mentioned this part in the three preceding emails. And I already answered you twice that I did check this: No dependencies declare any location permission and on all code paths, the app unsubscribes from location access when the app goes into background.
>
> Again, I believe the decision was made in error. If you remain on your position, please kindly provide how you came to that conclusion and we may start the conversation from there.
>
> Honestly, I am not even sure if I have been conversing with a real person so far. If you are not a bot, please write something to indicate that, f.e. your hobby (my hobby is OpenStreetMap), thank you.
>
> - Tobias Zwick

**Comment by Cj-Malone** [comment]
Is this less or more of a headache than the F-Droid update stuff that happened a while ago? :p

**Comment by matkoniecz** [comment]
> If it is a human, why can he not tell me how they reached that conclusion

Maybe it is a poorly paid human with rigid script or bunch of a canned answers, supposed to answer 60 mails every hour, all day long?

**Comment by HolgerJeromin** [comment]
For us techy people it is hard to believe, but this stupid ("have your tried to restart your computer") answers are often solving the problem.
But here we have a deep technical answer from westnordost which should have escalated to the next support level with more qualified persons.
I really like the captcha question "what is your hobby?". Mine is btw programming and osm. :-)

**Comment by smichel17** [comment]
> I am in no hurry.

If that changes, historically it seems like the best way to escalate is to make a fuss on social media :slightly_frowning_face: (mine: drums, games, aikido).

**Comment by westnordost** [comment]
I wrote

> Hello Billie
> 
> I haven't heard back from you yet.
> 
> Did you review the policy violation and came to the conclusion that indeed the decision was made in error, or is this still ongoing?
> 
> Tobias Zwick

**Comment by westnordost** [comment]
And they wrote back

> Hi Tobias,
> 
> Thanks again for contacting the Google Play Team.
> 
> I see your app *StreetComplete (de.westnordost.streetcomplete)* was 
> resubmitted earlier and has already been approved.
> 
> As a reminder, you can always refer back to the below references for the 
> previous *Location Permissions *policy issue:
> 
>   * Location permissions
>     <https://support.google.com/googleplay/android-developer/answer/9888170#location-permissions> -
>     Developer Policy Center
>   * Requesting access to background location
>     <https://support.google.com/googleplay/android-developer/answer/9799150> -
>     Play Console Help
>   * Evaluate background location access
>     <https://developer.android.com/training/location/background#evaluate> &
>     Background location access checklist
>     <https://developer.android.com/training/location/background#checklist> -
>     Documentation for app developers
>   * Google Play PolicyBytes on YouTube
>     <https://www.youtube.com/watch?v=TDF-GvnKC18>
> 
> Thanks for working with us and for your support of Google Play.
> 
> Regards,
> Billie
> The Google Play Team
> 
> Please visit the Google Play _Developer Policy Center_ 
> <https://play.google.com/about/developer-content-policy/> and Google 
> Play's _Academy for App Success_ 
> <https://www.google.com/url?q=https%3A%2F%2Fplayacademy.exceedlms.com%2Fstudent%2Fcatalog%3Futm_source%3Dshortlink%26utm_medium%3Dgco%26utm_campaign%3Dgeneric&sa=D&sntz=1&usg=AFQjCNFCGuodLDu7nVRXeWMLYJks7wbqDw> 
> to learn more about building policy compliant and high quality apps. You 
> can also visit the _Android Developers Blog_ 
> <https://android-developers.googleblog.com/> for the latest Android and 
> Google Play news for app and game developers.
>

**Comment by westnordost** [comment]
And I wrote

> Hi Billie
> 
> This is correct, I published several updates since and they were all 
> approved. However, I did not change anything in regards to access to 
> location in the background. The app did not use background location 
> before and it is not using it now.
> 
> Why am I being persistent about it if the issue apparently resolved itself?
> 
> Because as long as I don't know what caused the app to flagged as 
> violating location policy, I have no guarantee that it will not be 
> blocked again tomorrow for the same reason.
> 
> Tobias Zwick
>
