### ISSUE TITLE
Fire hydrant type quest has no option for "does not exist"

### ISSUE THREAD

**Issue by tguen** [streetcomplete/StreetComplete#2913]
Some quests, like "does this bench have a backrest?" and "what can be recycled here?" have an option to indicate that the feature doesn't exist. There is no such option for the quest "what kind of fire hydrant is this?" I found myself wanting this option a couple times recently, and had to resort to using another editor to remove the features.

**Comment by matkoniecz** [comment]
Similarly - maybe enable "delete object" or "replace shop" mode for car wash type quest?

**Comment by matkoniecz** [comment]
Not yet tested code solving this and adding also deletion mode for some other quests: https://github.com/streetcomplete/StreetComplete/compare/master...matkoniecz:delete_more?expand=1
