### ISSUE TITLE
Adding HDYC to showcase

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2916]
I think that http://hdyc.neis-one.org/ has some pretty cool/useful statistics and it seems missing from showcase.

Not the greatest example of mobile website ever, but works also on mobile.

Some other services by Pascal such as notes overview also may be worth listing.

**Comment by FloEdelmann** [comment]
https://resultmaps.neis-one.org/ is already included in StreetComplete:

https://github.com/streetcomplete/StreetComplete/blob/42cf4c2443302d9896d1fc93a62c3e2cc1d88147/app/src/main/java/de/westnordost/streetcomplete/data/user/achievements/AchievementsModule.kt#L61-L68

All of Pascal's tools are listed on that website, including http://hdyc.neis-one.org/. So in my opinion, adding all tools to the showcase individually is not necessary.

**Comment by matkoniecz** [comment]
huh, I managed to lose myself in naming of stuff in OSM ecosystem
