### ISSUE TITLE
Is it possible to use StreetComplete to link pictures from mapillary and commons to an object?

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#2923]
**Use case**
Link amenity=shelter to photos of shelter in the vicinity
do the same for tourism=wilderness_hut and alpine_hut.

**Proposed Solution**

**Comment by matkoniecz** [comment]
From new quest template:

- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

in case of objects without image, there is no tag that could be applied.

**Comment by westnordost** [comment]
You could do this with the website editor (iD) on openstreetmap.org. There is really no necessity to be on-site to do this.

**Comment by matkoniecz** [comment]
And https://osm.wikidata.link/ allows to detect potential matches with Wikidata, what links images added to Wikidata entries (remember to review proposed matches!)
