### ISSUE TITLE
bus stop bench options

### ISSUE THREAD

**Issue by jklebes** [streetcomplete/StreetComplete#2924]
It's hard to answer "does this bus stop have a bench (yes/no)" when there is a board that doesn't really count as a bench.  Could you please add a third option that registers ```bench=stand_up_bench```?

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/bench=stand_up_bench is barely used and "stand up bench" seems to be oxymoron to me

I would say that answering "no bench" is entirely correct for them.

I have seen people leaning on trees or inverted U bicycle parkings, but does not make them benches.

**Comment by RubenKelevra** [comment]
Maybe we could clarify this somehow in the quest itself?

**Comment by matkoniecz** [comment]
Is it likely that people will tag this specific not-a-bench as a bench?

**Comment by cyclingcat** [comment]
At least I was wondering myself some months ago what to answer for this type of "bench" inside the shelter of a bus stop in a village nearby where _all_ of the bus stop shelters have this kind of "bench":

![pseudo_bench](https://user-images.githubusercontent.com/32601012/120024868-1af12680-bff0-11eb-9be9-5609a8db9fd3.jpg)

So I'd support @RubenKelevra's suggestion to change just the wording - in German we have the more general word "Sitzgelegenheit", don't know if there is a similar fitting word in English (maybe "seat" instead of "bench" is enough? Or "bench or seat"?)

The cycling cat

**Comment by RubenKelevra** [comment]
@cyclingcat thats a normal bench to me. I don't think we need to explain this.

But there are benches like this in some countries:

![images.jpeg](https://user-images.githubusercontent.com/614929/120029599-9a81f400-bff6-11eb-806d-0c0f3da74c6b.jpeg)

![ENIbv1IUYAcBTNH.png](https://user-images.githubusercontent.com/614929/120029626-a4a3f280-bff6-11eb-8c63-c472289219f2.png)

![bus-stop-roofing-shed-250x250.jpg](https://user-images.githubusercontent.com/614929/120029638-a8d01000-bff6-11eb-9c3e-4e0657768670.jpg)

**Comment by cyclingcat** [comment]
Yes, your second example is further away from "usual" benches than mine. (The first one is "bench=yes; backrest=no" :smile:) I have even seen separate seats with a greater distance between them in the wild. So if "bench=yes/no" is the only key/value pair here, a change in wording would make definitely sense IMHO.

The cycling cat

**Comment by jklebes** [comment]
Thanks, mine are a narrow, angled board like middle picture or worse.  I had been tagging them "no" before I knew about the ```stand_up_bench``` option anyway and will continue to do so.  A person who needs to sit down can't use it.

**Comment by westnordost** [comment]
So, I understand that most/all people would tag this stand-up bench simply as "no" and I'd say, that's fair.

We could consider changing the wording to "Does this bus stop have a bench **to sit on**", but that really souds like a tautology. Or add the word "proper", but that could be misunderstood, i.e. one would need to define what proper is.

So I'd opt to do nothing here. Any thumbs?

**Comment by cyclingcat** [comment]
Hm... the problem here is the definition of "bench" which is similar, but not identical to the requirement "something to sit on". As we see here, there are benches you're not really be able to sit on. On the other hands there are kinds of seats which actually aren't benches, so I wouldn't consider "a bench to sit on" as a tautology. However this sounds like an intersection, so how to answer the quest for "something you can sit on without being a bench" like in @RubenKelevra's third picture above? ("Proper" is too vague and doesn't improve something here.)

Unfortunately, the corresponding page in the [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:bench) doesn't add something to this discussion either. It doesn't mention if the key "bench" in fact means "something to sit on even if it's not a genuine bench", it only means the exception "bench=stand_up_bench". It all depends on how this key is meant. From the viewpoint of usefulness it's more important if someone can sit on it, so this should be reflected in the wording IMHO.

The cycling cat

**Comment by matkoniecz** [comment]
> As we see here, there are benches you're not really be able to sit on.

Is it actually named/referred to as bench beyond some marketing lies?

**Comment by jklebes** [comment]
Didn't mean to spark a whoie debate of what a bench is, I thought I was pointing out a missing detail in implementation.  In my view the openstreetmap community has already solved the problem as well as possible by the existence of the ```bench=stand_up_bench``` option, and, since it exists, it would be most honest to use it where applicable.

**Comment by cyclingcat** [comment]
Don't know how these "stand up benches" are referred to in the regions they appear, but maybe it's best to consider it from the viewpoint of an average SC user: How would _he_ consider this object? Or, perhaps even better: How is this kind of objects usually called in those regions where they appear? (I haven't seen something like that in Germany so far, they seem to be uncommon here.)

Another idea: Move these border cases into the "Other answers" menu. Add two more items:

1. "It's a bench you cannot sit on" (tag as `bench=stand_up_bench`)
2. "It's not a bench but separate seats" (tag as `bench=yes'  as long as there is no better tagging)

Don't know if it's worth the effort though, and of course this won't solve the inadequate definition of the key "bench", especially the "non-bench seating capabilities"

The cycling cat

**Comment by RubenKelevra** [comment]
The major drawback of these "stand-up benches" is that older people or people who need a benches, can't use it for this purpose.

Maybe we should ask for "is this bench you can comfortably sit on?"

Yes -> tag `bench=yes`
"stand-up bench" -> `bench=sta...`
No -> tag `bench=no`

---

If there's really the need in the future to differentiate between seats and benches etc we could add an additional quest which picks up the `bench=yes` ones and shows pictures of different types.

**Comment by peternewman** [comment]
> I would say that answering "no bench" is entirely correct for them.

Really?

Wikipedia says:
"A bench is a long seat on which multiple people may sit at the same time."
"Sitting requires the buttocks resting on a more or less horizontal structure, such as a chair or the ground. Special ways of sitting are with the legs horizontal, and in an inclined seat."

Surely this structure is far more of a bench and this bus stop is more bench than not-bench, compared to say one with just a pole and nothing else?

> I have seen people leaning on trees or inverted U bicycle parkings, but does not make them benches.

I'd agree with that, but these things at a shelter aren't natural or designed to store your bike, do we really think they've been installed for any purpose other than sitting?

> don't know if there is a similar fitting word in English (maybe "seat" instead of "bench" is enough? Or "bench or seat"?)

Seat covers the more general case of anywhere to sit in English, perhaps "bench or other seat" to help the translators?

> @cyclingcat thats a normal bench to me. I don't think we need to explain this.

I think pedantically that's three seats, as it's not a long seat.

> Yes, your third example is further away from "usual" benches than mine. (The second one is "bench=yes; backrest=no" smile)

The back is glass so technically you could use it as a backrest.

It feels to me like these perch seats may be another example of hostile architecture:
https://en.wikipedia.org/wiki/Hostile_architecture

> We could consider changing the wording to "Does this bus stop have a bench **to sit on**", but that really souds like a tautology. Or add the word "proper", but that could be misunderstood, i.e. one would need to define what proper is. Also, the same people that consider the above as some kind of bench would maybe also consider that it is possible to more or less sit on these.

If we're looking at some improved wording, we probably need something that would translate well, e.g. a generic definition like the ability to swing/lift up your feet, which would differentiate those two types. Although it might not be possible to do that at 10 degrees, but maybe it would provide most of the resting ability for an OAP?

> So I'd opt to do nothing here.

> Unfortunately, the corresponding page in the [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:bench) doesn't add something to this discussion either.

To me, from the more holistic point of view, this is what needs fixing! I'd accept that maybe more people might tag particular details like this using SC than other tools, but its no good if some people are adding it via iD without this background as then you get different results and the data quickly becomes garbage.

> It all depends on how this key is meant. From the viewpoint of usefulness it's more important if someone can sit on it, so this should be reflected in the wording IMHO.

But doesn't this depend on the user, we're working on the stereotypical person who has a medical need to sit down, but if they're overweight then the armrests could possibly make them unsuitable, or for some people the height is more relevant for comfort. I assume we're not saying we'll tag things with armrests as bench=no?

**Comment by westnordost** [comment]
Jesus, isn't there a word for the activity of spending huge amount of time on insignificant details? Let it be X. Then, I call you out for doing X.

You all know the drill, as long as a distinction like this is not discussed in the wider community, properly documented in the wiki or established, it makes no sense to introduce it here in the app.

**Comment by westnordost** [comment]
So if you want to do X and define the hell out of a bench, then you should do it in the appropriate community channel (wiki, mailing list, forum,...). In the interest of maybe redirecting this energy there, I'll close this issue. You could link back here to any discussion you start there.

**Comment by peternewman** [comment]
> Jesus, isn't there a word for the activity of spending huge amount of time on insignificant details? Let it be X. Then, I call you out for doing X.

I think you mean bikeshedding;
https://en.wikipedia.org/wiki/Law_of_triviality

> You all know the drill, as long as a distinction like this is not discussed in the wider community, properly documented in the wiki or established, it makes no sense to introduce it here in the app.

Yes, we're actually agreeing, I was just trying to add some counter-points for why we shouldn't stop tagging (or encouraging the stopping of tagging) of bus stops with bench like things as bench=no.
