### ISSUE TITLE
consider asking about building levels when `height` is tagged

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2927]
original issue title: consider asking about roof shape when height is tagged

**Use case**
1) building levels is not asked if `height` is tagged - https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.kt
2) roof shape is not asked unless building levels are tagged - https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShape.kt
3) as result one of imports is planning to deliberately skip importing available height to avoid disabling roof shape quests. This seems to not be a good way of doing things.

**Proposed Solution**
Ideally SC would not discourage using `height` tag. Maybe just ask for roof shape if `height` is tagged on a building, in area where roofsAreUsuallyFlatAt is not true?

triggered by https://discord.com/channels/413070382636072960/789437210797408277/847899428483629076

**Comment by westnordost** [comment]
Sure, this would make sense. Of course, the same limitations as for building levels should apply: If the height is greater than X, don't show it because it is likely that the roof can not be shown from below.

On the other hand, what buildings do not have building levels? Maybe only those that also don't really have a roof? Industrial buildings, man-made building-like things etc?

**Comment by matkoniecz** [comment]
I understood that reasoning goes like this:

It is not useful to ask for building levels (for estimating height) for `building=apartments` with `height=`  as height is known already.

But for such building it may still make sense to ask for building shape.

Or maybe it is still useful to ask for building levels with known `height`?

**Comment by HolgerJeromin** [comment]
> Or maybe it is still useful to ask for building levels with known height?

Yes. IMO levels are interesting even with known height.

**Comment by smichel17** [comment]
+1. Use case: estimating square footage of housing

**Comment by matkoniecz** [comment]
> Yes. IMO levels are interesting even with known height.

Re-titling the issue then, especially given +1 from @westnordost
