### ISSUE TITLE
seamark:bridge:clearance_height for bridges over waterways

### ISSUE THREAD

**Issue by Tomagori** [streetcomplete/StreetComplete#2929]
### General
This information is highly relevant to people planning boating trips, especially when navigating canals. The relevant information is often sign-posted close to the bridge, so should be easy to obtain and enter into StreetComplete.

Affected tag(s) to be modified/added: [seamark:bridge:clearance_height, seamark:bridge:clearance_height_closed, seamark:bridge:clearance_height_open](https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dbridge#Clearances).
Question asked: **What's the vertical clearance for boats/ships below this bridge?**

When a `bridge=movable` or equivalent is involved: **What's the vertical clearance for boats/ships below this bridge when the bridge is closed?** and **What's the vertical clearance for boats/ships below this bridge when the bridge is open?**.

EDIT: just noticed "closed" and "open" might invite misunderstandings. When a bridge is closed for street traffic, it can be considered open for marine traffic, so maybe it should rather be "when closed for street traffic" or something similar.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
This could more or less be the exact same thing that already exists for bridges with streets underneath them, only this time for waterways that run under those bridges. 

**Element selection:** 
EDIT: It is of note that these `seamark:` tags are most often applied to a single node on the waterway that's just below the bridge. Ideally, a node tagged with `seamark:type=bridge` should already exist where this quest is relevant. In case it is not, this node may have to be created by StreetComplete first. When then adding the clearance value, `seamark:type=bridge` should be added to that node as well. 

Waterways under bridges could be identified by looking for ways and areas tagged with `natural=water` and/or `waterway=*`, with anything but "no" tagged for the `boat=*` and `ship=*` (or subtype) keys, that intersect with ways or areas tagged with `bridge=*`.

seamark:bridge:clearance_height_closed and seamark:bridge:clearance_height_open would only have to be checked if `bridge=*` is set to `movable`. Also check out the values for [`seamark:bridge:category=*`](https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dbridge#Categories) that denote movable bridges of various types that should be checked for as well probably.

**Proposed GUI:**
Pretty much nearly the same thing that already exists for bridges, just with a boat instead of a car in the image.

**Comment by matkoniecz** [comment]
What would be tagged if such sign is not present?

**Comment by Tomagori** [comment]
Good question, maybe something similar to how it is with streets, asking if there is at least X amount of clearance, with X depending on whether the waterway is only tagged with `boat=*` or `ship=*`. However, it's possible we'd be talking about sizes too hard to gauge with eyes only, and requirements for boats or ships might differ too much to allow for universally applicable answers, so maybe "there is no sign" should just hide the quest or create a `fixme= measure clearance`.

**Comment by smichel17** [comment]
The problem is that whatever is tagged for "There is no sign" must hide the quest for everyone, not just the person who selected the option.

> - [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

**Comment by Tomagori** [comment]
In this case, using [`no_indications`](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values) would seem appropriate. The [current wiki article](https://wiki.openstreetmap.org/wiki/Seamarks/Bridges#Clearances) doesn't reference non-numerical values, but this seems well within the logic of the tag.

**Comment by Tomagori** [comment]
To add to this idea: Looking at the seamark tags, it seems they're being neglected a fair bit. When setting `seamark:bridge:clearance_height`, there might also be added value in adding `seamark:type=bridge` to the same node.

**Comment by westnordost** [comment]
A user of this app is usually on foot. It'll often not be possible to see what's on the sign that is facing the river or body of water.

**Comment by Tomagori** [comment]
Speaking only from personal experience, these signs are very visible to people passing by these bridges on adjacent paths. Especially in areas with canals, you'll often find cycleways or footpaths next to them, so I don't think this should be an issue. I actually only had this idea because I noticed a bunch of these signs on a jog one day.

**Comment by westnordost** [comment]
I think this only works if there is a footway alongside the river. In Hamburg, most bridges are like this:
https://www.google.de/maps/@53.5816545,10.0102479,3a,75y,112.89h,71.66t/data=!3m6!1e1!3m4!1ssWE15hFKjloJhaXe6iOj8Q!2e0!7i13312!8i6656

In your area, it might be different, but the simple fact that in other areas, the quest may always not be answerable is problematic because
> 🐿️ Easily answerable by everyone from the outside but a survey is necessary

**Comment by Tomagori** [comment]
In my case, it was actually just outside of Hamburg, coincidentally :D I see what you mean. I'd still say that in those cases, you can look over the railing and probably spot the sign if it's there, I've even seen clearance values edged into the ground on top of the bridge (close to the railing), so I think it would still be doable. But I understand if this kills it for you.

**Comment by smichel17** [comment]
A higher-effort solution could filter to only situations with a footway alongside, reversing the logic from the cycleway/sidewalk quest. I can't say if that's worth the effort.

**Comment by Tomagori** [comment]
I'd say that, as it breathes life into a neglected but highly useful tag and considering the information is out there, (often) visible, with too few people taking the time to actually enter it, SC could make a very valuable contribution here.

**Comment by westnordost** [comment]
Alright, maybe. However:
- What tag exactly to use if there is no sign?
- should only be asked for bridges crossing rivers with `boat=yes`

**Comment by Tomagori** [comment]
I'd suggest:

- If there is no sign, tag `no_indications`
- I'd not only restrict it to `yes`, but go for anything except `no`. If SC usually doesn't tag `private`, then exclude that, but I'd say there's value in adding the quest for `permissive` and especially for `designated` too. In addition to the `boat=*` key,  I'd consider the cases where `boat=*` is missing, but one of the more specific subtags is present (`motorboat=*`, `sailboat=*`, `canoe=*`). Arguably, `ship=*` should be covered as well. While the clearance tag may be moot for large bridges like the [Øresund Bridge](https://en.wikipedia.org/wiki/%C3%98resund_Bridge), the various inland commercial shipping routes throughout continental Europe for example provide ample use cases for the tag (and it's already in use there). So if a bridge crosses the Danube where there's no `boat=*` but only a `ship=*` tag, the quest makes sense there too. Therefore, to avoid inaccuracies and impossible quests, maybe excessively long bridges could be excluded (anything over like 300 meters), but the `ship=*` tag could generally be covered as well.
- At least [in Germany](https://de.wikipedia.org/wiki/Br%C3%BCckendurchfahrtsh%C3%B6he#Schifffahrt), clearance values seem to be calculated from a variance-adjusted point. As the signs (at least the ones I know) all only mention one value (though some bridges occasionally have [gauges](https://de.wikipedia.org/wiki/Br%C3%BCckendurchfahrtsh%C3%B6he#/media/Datei:Durchfahrtsh%C3%B6he_je_nach_Wasserstand,_animiert.gif), either in addition or exclusively), this shouldn't be an issue for mappers in the field. When there is no clear sign, `no_indications` should be used, as the seamark tag doesn't accommodate variability as far as I know.

**Comment by matkoniecz** [comment]
> If there is no sign, tag no_indications

Is it tagging scheme that is in use? Seems not from looking at https://taginfo.openstreetmap.org/keys/seamark%3Abridge%3Aclearance_height#values

**Comment by Tomagori** [comment]
Good point! I suppose `unknown` would work as well, `no_indications`, as it is used for [maxheight](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values) on streets, might be more accurate, however.

**Comment by matkoniecz** [comment]
I also would prefer `no_indications` but it should be validated on some general forum before using in SC (to be done if it is a remaining step).

In general I worry about problem of bridges with such signage that are surveyable only from water - despite carrying footway/road.

**Comment by Tomagori** [comment]
True, I'll open a thread on the wiki if this moves forward. Maybe a differentiation would be sensible. If I can't see a sign, but I can't see the bridge from the side either, I tag "unknown", if I see the side and there's no sign, I tag "no_indications". But I'd have to check back with people on the wiki.

**Comment by matkoniecz** [comment]
If you look for feedback tagging mailing list may be far better - on OSM Wiki you likely will get just reply from me :)

**Comment by westnordost** [comment]
A new issue can be reopened when the tagging issues have been resolved (by using the usual channels)
