### ISSUE TITLE
Bench quest order confusing

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#2931]
I found an old bench.
I got the quest "in this bench still there?"
After that: "has this bench a backrest?"

I am not sure if I changed order...

Is it possible to skip "still existing quest" if there is no backrest? But what if someone disabled the backrest quest?

**Comment by matkoniecz** [comment]
In turn some people were confused by asking about backrest of nonexisting benches (or other features of nonexisting objects).

**Comment by HolgerJeromin** [comment]
Hm, you are right.

**Comment by matkoniecz** [comment]
In general in this case both orders can be tricky. And while possible to implement

> Is it possible to skip "still existing quest" if there is no backrest? But what if someone disabled the backrest quest?

it would be quite fragile.

So I would go with the current simpler method.

**Comment by HolgerJeromin** [comment]
Ok.

**Comment by peternewman** [comment]
The exception to this though is the resurvey type quests (e.g. post box ones), where that quest has to be above the existence one, or it never gets resurveyed.
