### ISSUE TITLE
Quest form remains open for "too long"

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2936]
Sometimes when I answer a quest and tap on a different pin while the old quest form is still open, I get asked whether I really want to discard my answer.
This is very noticable (but not limited to) when there is some load, e.g. from downloading/persisting data or from background apps.

With somewhat older versions this did not happen (tested with a 4 week old 32-alpha1 I had still lying around). I suspect this is caused by the fix for #2876.
In the old version, the quest form disappears almost immediately after tapping ok, and I can answer more quests (and even if it doesn't, I never get the discard dialog). The "quest solved" animation then sometimes plays up to a few seconds later, when the form for the next quest is already open, or even a few quests later in extreme cases.
But a late animation is really minor compared to being blocked until the quest form disappears.

It seems like the quest form does not disappear until processing (generating new quests, db updates) is finished.
Can this be changed to back, so background work does not stop me from answering more quests?

**Comment by westnordost** [comment]
Should be fixed on master.

This also triggered a crash - when someone tapped "OK" really fast (before it could close) twice.
