### ISSUE TITLE
Every contribution is gone after Update

### ISSUE THREAD

**Issue by lm41** [streetcomplete/StreetComplete#2938]
All contribution stars I've had before the update are gone after the update. Every inapp statistic is gone.

**How to Reproduce**
I dont know, i've just upgradet and opened the app with bad Internetconnection

**Versions affected**
Android 9 StreetComplete 32.0

**Comment by westnordost** [comment]
It will sync eventually, give it some time.

**Comment by riQQ** [comment]
See also #2903
