### ISSUE TITLE
Include non-node benches in bench questions

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#2939]
**Use case**

Some (yes, only 19k vs. 1.5M nodes) benches are modelled as ways and not as nodes. Those are currently excluded from StreetComplete bench quests as far as I can read the source.

They seem to be mostly used when the bench is not the standard 2-seat bench with rectangular footprint, but perhaps a more elaborate shape with corners or curves.

**Proposed Solution**

Include ways with amenity=bench for bench-related quests in the same way as nodes are currently considered.

**Comment by matkoniecz** [comment]
Is there any bench quest except backrest one?

**Comment by 10992-osm** [comment]
Not a specific bench one, but the [quest for existence](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt) (sounds philosophical) seems only to check bench nodes, rather than ways.

**Comment by ygra** [comment]
Backrest and existence, yes. And if I'm reading the code [here](https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/java/de/westnordost/streetcomplete/quests/bench_backrest/AddBenchBackrest.kt) correctly (never written or read any Kotlin), then this also seems to exclude ways.

**Comment by matkoniecz** [comment]
> Not a specific bench one, but the quest for existence (sounds philosophical) seems only to check bench nodes, rather than ways.

Thanks, I forgot that benches appear also there!

Note that existence quest is supporting deleting only nodes, as way deletion is too complicated to handle it without user looking at data (just for benches - there are cases where way should be deleted and cases where just tags from way should be removed and cases where part of tags should be removed from way).

So it is basically about backrest.

**Comment by ygra** [comment]
> Note that existence quest is supporting deleting only nodes, as way deletion is too complicated to handle it without user looking at data

Not knowing the code, but perhaps if deletion isn't possible for a feature, a note could be added instead. This is already the case with other quests. Or is being able to delete a feature (and how it works exactly) a quest property and cannot vary among features handled by the quest?
