### ISSUE TITLE
building=house wie building=yes behandeln

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#2945]
**Use case**

**Proposed Solution**

Einige Gebäude sind mit building:house vorbelegt. 
In diesem Fall fragt SC nicht nach dem Gebäudetyp (Reihenhaus, Mehrfamilienhaus, ...), obwohl eine eindeutige Antwort möglich wäre.
Daher mein Vorschlag, auch bei building:house  den Gebäudetyp abfragen.

**Comment by RubenKelevra** [comment]
Hey biketeur,

please write tickets in English. German cannot be understood by everyone who might want to participate in this project.

**Comment by Helium314** [comment]
What should be tagged if `building=house` _is_ the correct type?

**Comment by westnordost** [comment]
> In diesem Fall fragt SC nicht nach dem Gebäudetyp (Reihenhaus, Mehrfamilienhaus, ...), obwohl eine eindeutige Antwort möglich wäre.

Nicht immer. Siehe @Helium314 . Zum Beispiel ein Einfamilienhaus ohne Garten drumherum (z.B. direkt an das nächste Haus gebaut) ist kein `building=detached` sondern einfach nur `building=house`.

**Comment by biketeur** [comment]
Mag sein, dass es solche Gebäude gibt, hab ich noch nicht gesehen, dafür aber Dutzende, insbesondere Reihenhäuser, die mit house vorbelegt dind

**Comment by Helium314** [comment]
Es gibt sie, Beispiel: https://commons.wikimedia.org/wiki/File:97,_High_Street,_Wheatley.jpg

Dutzende falsch getaggte building=house sind wohl kein ausreichender Grund um bei 40 Millionen building=house so oft zu fragen bis etwas anderes ausgewählt wird.

Reihenhäuser (building=terrace) können geteilt werden (und sind meiner Erfahrung nach meistens geteilt). Für einzelne Einheiten ist dann building=house korrekt.

**Comment by matkoniecz** [comment]
Also, note that even if different value would be a better fit than `building=house` - then value from retagging is very, very low. Is there any case where it matters?

(Personally I use `building=house` for anything constructed as single-family house)

**Comment by biketeur** [comment]
OK, ich ziehe hiermit meinen Vorschlag zurück.
