### ISSUE TITLE
Weekly Scores and Ranks

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2946]
I've played SC with a friend and she was quite disappointed that she can't "beat" me, cause I had a headstart of month. 

I was wondering if the game and competition factor wouldn't work better if we had weekly stats instead of epoch ones. 

We currently have a lot of empty real estate on the profile page:

![Screenshot_20210604-153309769](https://user-images.githubusercontent.com/614929/120810065-05798080-c54b-11eb-82d9-4a8521c86a69.jpg)

Maybe we could move the current stats down to the bottom and have a weekly counter in the top for the current week and show the results of the last week below. 

This way friends can compete which eachother on a weekly basis.

**Comment by 10992-osm** [comment]
If I'm correct, this might also require modifications to the [web server statistics](https://github.com/streetcomplete/sc-statistics-service), as well as the main app.  Anyway, it seems a reasonable idea.  I wonder what other statistics one might include.

**Comment by RubenKelevra** [comment]
We could in theory query the OSM profile and get the OSM friends and their stats couldn't be shown there. 🤔

**Comment by westnordost** [comment]
Technically, this is well possible and actually not that much effort. I would accept a PR that implements this. Actually, it would need to be two PRs, one for the UI here, one for the generation of the stats, as @10992-osm correctly mentions.

**Comment by lukashass** [comment]
As a first version I would try to do something like the following. While there is definitely room for improving the design, I think this should be sufficient as a first step.

![profile](https://user-images.githubusercontent.com/32853499/138176181-2c908cc0-2274-4b47-ac04-bb6e6ff51641.png)

**Comment by westnordost** [comment]
Hmm, why show last week? You can't change anything from last week, I think it might be better to only show things that the user can improve (by contributing). If it is to show a (positive?) change, there is also another issue/idea to animate the changes since one last had a look in the profile screen.
Maybe you can replace "last week" with "current month"

**Comment by lukashass** [comment]
> Hmm, why show last week?

I thought about it as "the results of last weeks competition". You might be right though, I like "current month" as well.
