### ISSUE TITLE
bridge:structure should not be tagged on man_made=bridge

### ISSUE THREAD

**Issue by tguen** [streetcomplete/StreetComplete#2948]
> [Use bridge:structure=* to describe the load-bearing architecture of individual bridge spans. [...] Sometimes a bridge will have more than one type of span in its length.](https://wiki.openstreetmap.org/wiki/Key:bridge:structure): 

The wiki says the tag may be used on unclosed ways but not areas.

man_made=bridge is meant to tag an area which outlines the entire bridge. Since different parts of the bridge may have different structures, the tags should not be used together.

**Comment by matkoniecz** [comment]
Typical `man_made=bridge` has single structure and bridge:structure is well applicable to it,

In this case I think that it is fixable by editing wiki.

Can you give example of mapped bridges have "different parts of the bridge may have different structures"? In cases that I know the proper taggiging would be multiple `man_made=bridge` areas.

**Comment by andrewharvey** [comment]
Agreed with @matkoniecz I think it's helpful and good to tag the bridge:structure on the man_made=bridge area.

I would think different parts of the bridge with different structures, would just be two different bridges, so exactly what @matkoniecz suggests to have two man_made=bridge areas.

**Comment by tguen** [comment]
In Portland, some bridges have one structure (e.g. truss) over the river (or most of it), then continue as a beam bridge for hundreds of feet past the bank. The whole bridge is referred to by one name, so it should be mapped as one area.

[Morrison bridge at the river](https://www.google.com/maps/@45.5156454,-122.6677918,3a,65.7y,354.05h,87.14t/data=!3m6!1e1!3m4!1sFdBXupIiqgwun2CAPMMn_w!2e0!7i13312!8i6656)

[Hundreds of feet away](https://www.google.com/maps/@45.5166197,-122.660774,3a,48.9y,323.16h,87.11t/data=!3m6!1e1!3m4!1s15xKAC_JN60aBux9L-n5dw!2e0!7i16384!8i8192)

[A better example](http://www.japanfocus.org/data/incheon_bridge.jpg)

`man_made=bridge`:
> [the object represents the bridge as a whole](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge)

**Comment by matkoniecz** [comment]
How it is mapped in OSM right now?

**Comment by tguen** [comment]
Incorrectly, according to the wiki, which I've been meaning to fix for a while. I was the one who mapped it that way for unrelated reasons.

**Comment by matkoniecz** [comment]
Main question here is - which way can be used to detect/mark unusual cases that `man_made=bridge` is a mix of different structures?

(hopefully - there is some standard tag applied to `man_made=bridge` areas in such case)

**Comment by tguen** [comment]
[There isn't.](https://taginfo.openstreetmap.org/tags/man_made=bridge#combinations) That's probably why the wiki says not to use `bridge:structure` on areas. The best solution may be to revive the [`type=bridge` proposal](https://wiki.openstreetmap.org/wiki/Relations/Proposed/Bridges_and_Tunnels) and edit it to allow for multiple outline roles.

**Comment by matkoniecz** [comment]
Even if there is standard tag it is likely to not appear in such list - number of such bridges is quite low.

**Comment by westnordost** [comment]
If there isn't a tag for that (`man_made:part=yes` maybe, analog to to `building:part=yes`?), there is also not anything we can do here.
