### ISSUE TITLE
Map turns black after resizing the window in multi-window mode

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#2950]
https://user-images.githubusercontent.com/6892794/120895387-01b62e80-c61d-11eb-8b6c-2f93daec218d.mp4

The top app is v32.1 from the Play Store and the bottom one was built from the current master branch (da5cb321546bace9ba39910bad6977051d01c6d1). My device is running Android 11.

**Comment by matkoniecz** [comment]
Map turns black also around second 20 in https://github.com/streetcomplete/StreetComplete/issues/2909#issuecomment-851416655 - without multi-window but also on manipulating screen (app switching)

**Comment by FloEdelmann** [comment]
@tapetis Is this still reproducible with the latest releases? [Version 35.0](https://github.com/streetcomplete/StreetComplete/releases/tag/v35.0) contained #3259, which could maybe have fixed this (but also introduced a similar issue #3405). But maybe this is also a completely different (possibly Tangram-related) problem.

**Comment by tapetis** [comment]
I cannot reproduce this bug with version 37.0 on my Android 12 device. I will close this issue.
