### ISSUE TITLE
Primary, Secondary and Tertiary roads can have sidewalks too

### ISSUE THREAD

**Issue by FinixFighter** [streetcomplete/StreetComplete#2951]
I noticed that the app doesn't ask for pavements (sidewalks) if the road is a primary road or a secondary road. In my city there are some of these streets which have sidewalks (and some of them have bike lanes too), so I think the app should ask for this information also in the case of primary and secondary roads. If these roads remain like this, there could be routing problem with some app when choosing "by foot" option, since these kind of roads will be avoided when by foot (because they have a minor weight). For example Maps.Me and Organic Maps have this problem.

Just find a primary or secondary road, then try to set a route from a point A to B (place both on the same way, so the route should be just straight). I'll add some examples made by me using Organic Maps:
![195786253_4372130306132734_8221612121661394431_n](https://user-images.githubusercontent.com/19877271/120915750-d592c000-c6a5-11eb-8a79-38f3faf92892.jpg)
![196682670_265474348702294_3237183231095572888_n](https://user-images.githubusercontent.com/19877271/120915751-d6c3ed00-c6a5-11eb-9925-741282902002.jpg)

**Comment by matkoniecz** [comment]
Add sidewalk quest should be asked for `highway=primary` `=primary_link` `=secondary` `=secondary_link` =tertiary` without `highway=footway` `=path` `=cycleway` mapped along them.

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L23

Can you link case where it is not being asked?

**Comment by FinixFighter** [comment]
It's not asked, for instance, for "Via Nazionale Adriatica Sud": https://www.openstreetmap.org/way/815627042
And here is another example of what happens by creating a route from A to a quite distant point B on Via Nazionale Adriatica Nord: instead of remaining on the same street, Organic Maps routes me through smaller streets, but no one use those streets even if there's traffic, because I don't care about cars if I am walking!
![195615064_230122041921448_8038289326465374499_n](https://user-images.githubusercontent.com/19877271/120919846-0120a500-c6bc-11eb-9026-bab3c6496c70.jpg)

**Comment by matkoniecz** [comment]
Interesting. It is actually not being asked here. I suspect that it may run into quest count limit and will appear after some of nearby sidewalk quests are solved. But I see no mention of hitting this limits in log (maybe it is just not logged anymore)?

**Comment by westnordost** [comment]
https://github.com/streetcomplete/StreetComplete/blob/23d919cbc711a488fed62f2172cbed4e547e03fa/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L33

**Comment by matkoniecz** [comment]
In other words: once you answer quest asking whether this street is lit you will get sidewalk quest displayed.

**Comment by peternewman** [comment]
But you can't, as that's a catch 22:
https://github.com/streetcomplete/StreetComplete/blob/31a51693165996b4f79ff449f5667c36b1493bf9/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt#L23-L30
https://github.com/streetcomplete/StreetComplete/blob/31a51693165996b4f79ff449f5667c36b1493bf9/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt#L65-L71
https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/java/de/westnordost/streetcomplete/data/meta/OsmTaggings.kt#L26-L31

This only has:
`maxspeed=50`

So it won't get the max speed quest:
https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeed.kt#L13-L14

So there is no way to get from this state to answering sidewalk and/or lit for this way.

**Comment by FinixFighter** [comment]
If I understood well, sidewalk quest will come up only if that one has one of those tags ("source:maxspeed","zone:maxspeed" etc...). Now, the maxspeed has been added via OpenStreetMap website, then there won't be the condition for the sidewalk quest to come up. Is that right? If so, isn't it fixable just by adding "maxspeed" to MAXSPEED_TYPE_KEYS list?

**Comment by westnordost** [comment]
Hmm so maybe:
- ask **sidewalk** also if `~${(MAXSPEED_TYPE_KEYS + "maxspeed").joinToString("|")} ~ .*urban|.*zone.* `
- ask **lit** also if `maxspeed` <= 60

**Comment by peternewman** [comment]
> If I understood well, sidewalk quest will come up only if that way has one of those tags ("source:maxspeed","zone:maxspeed" etc...).

No, the **lit** quest will only appear with those tags and a sidewalk tagged.

> Now, if the maxspeed has been added via OpenStreetMap website, then there won't be the condition for the sidewalk quest to come up. Is that right?

Yes, if they only tag maxspeed and not the other things.

> If so, isn't it fixable just by adding "maxspeed" to MAXSPEED_TYPE_KEYS list?

No, unless maxspeed has been (incorrectly) tagged as something like `.*urban|.*zone.*` rather than a numeric value.

>     * ask **sidewalk** also if `~${(MAXSPEED_TYPE_KEYS + "maxspeed").joinToString("|")} ~ .*urban|.*zone.* `

As above, I don't think that specific clause will sort it will it, if `maxspeed` has numeric values in.

>     * ask **lit** also if `maxspeed` <= 60

That sounds good to me.

**Comment by andrewharvey** [comment]
Does the sidewalk tag depend on maxspeed? It should be asked regardless of the maxspeed value, maxspeed:type or no maxspeed tag at all.

**Comment by matkoniecz** [comment]
> ask sidewalk also if ~${(MAXSPEED_TYPE_KEYS + "maxspeed").joinToString("|")} ~ .*urban|.*zone.* 

+1 though in case of numeric keys it will not help.

Ask also on maxspeed <=50 (and on similar mph)? Though it will ask on interchanges.

Ask where there are nearby sidewalks marked? It could be very problematic for performance.

> ask lit also if maxspeed <= 60

+1, on interchanges it may happen but such complex junctions are also likely to be lit (at least in Poland)
