### ISSUE TITLE
Ask about sidewalks on highway=trunk

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2953]
https://github.com/streetcomplete/StreetComplete/blob/23d919cbc711a488fed62f2172cbed4e547e03fa/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L23

ensures that the sidewalk quest is never asked on `highway=trunk`. In my opinion it should be, because you can't make any reasonable assumption if it will have a sidewalk or not, many do, many don't, so it's better to explicitly survey and tag it.

I found many routers avoid highway=trunk, so I've been mapping out sidewalk presence to assist and having SC ask would be perfect.

**Comment by matkoniecz** [comment]
Where `highway=trunk` are likely/possibly/plausibly having a sidewalks?

In Poland it is basically impossible, but here OSM mapping community is misusing `trunk` to mark expressways.

**Comment by andrewharvey** [comment]
> Where highway=trunk are likely/possibly/plausibly having a sidewalks?

I can only speak for where I edit actively, in Australia this is the case.

According to https://wiki.openstreetmap.org/wiki/Tag:highway=trunk#International_equivalence we use it to mark national highways, for example the main road connecting capital cities like Sydney to Brisbane. This is based on importance in the network.

For example here https://www.openstreetmap.org/way/575738505 this national highway that connects Sydney and Brisbane I walk past every day, has school children walking along it Monday to Friday, those kinds aren't walking on the road, they are taking the footpath (sidewalk).

> In Poland it is basically impossible

maybe you can add a special case in the app to disable it there?

> but here OSM mapping community is misusing trunk to mark expressways.
> expressway=* indicates if this road is an expressway: a dual-carriageway (divided) highway with high-speed design features, plus limited access to adjacent properties or grade-seperated interchanges.

That sounds like `highway=motorway`.

**Comment by andrewharvey** [comment]
It's worth noting on the wiki for highway=trunk it says

> In different countries, either performance or importance is used as the defining criterion for trunk – see #International equivalence and Highway:International equivalence for guidance on road classification in different countries.

So places where it's used based on high performance road, yes sidewalk is less likely, but in places where it's just for importance of the road, then sidewalk may be very likely.

**Comment by matkoniecz** [comment]
> According to https://wiki.openstreetmap.org/wiki/Tag:highway=trunk#International_equivalence we use it to mark national highways, for example the main road connecting capital cities like Sydney to Brisbane. This is based on importance in the network.

Nice that `highway=trunk` is used here correctly :)

Looking at https://www.openstreetmap.org/way/575738505 - is `maxspeed=60` typical or unusual on such `highway=trunk` with a sidewalk? Maybe filtering by max speed would be viable.

**Comment by andrewharvey** [comment]
> Looking at https://www.openstreetmap.org/way/575738505 - is maxspeed=60 typical or unusual on such highway=trunk with a sidewalk? Maybe filtering by max speed would be viable.

Typical, I'd say trunk roads with maxspeed >= 80 are less likely to have a sidewalk, and those with maxspeed <= 70 are more likely to have a sidewalk. Not always but a reasonable guide.

I wish StreetComplete had a user setting "spam me" that would ask all quests and not try to filter them...

**Comment by matkoniecz** [comment]
@andrewharvey If you (or someone else) would be able to find `highway=trunk` with <70 maxspeed, without `sidewalk` and without nearby `highway=footway/path/cycleway` it would help.

(https://www.openstreetmap.org/way/575738505 has mapped sidewalks along it, so SC would not ask there anyway)

**Comment by peternewman** [comment]
> @andrewharvey If you (or someone else) would be able to find `highway=trunk` with <70 maxspeed, without `sidewalk` and without nearby `highway=footway/path/cycleway` it would help.

Do you mean somewhere <70 without pavements, or without them mapped in OSM?

**Comment by westnordost** [comment]
I will close this as will not fix, as both it is very unlikely for trunks to have sidewalks, and if they do (f.e. very broad arterials, like maybe here https://www.google.de/maps/@14.0671061,100.6175887,3a,75y,168.62h,85.86t/data=!3m6!1e1!3m4!1s5pp4G6nrwiGM4yrtdVIXzw!2e0!7i16384!8i8192 ), it would be quite confusing to tag the sidewalks on the roadway itself. Tagging sidewalks on the roadway itself is okay for smaller roads, but the broader a road becomes, the less practical is this tagging.

**Comment by peternewman** [comment]
Trunk road with sidewalk, although it's separate:
https://goo.gl/maps/sxrjp6V8bn5ptRmy9

**Comment by andrewharvey** [comment]
> as both it is very unlikely for trunks to have sidewalks,

I disagree, there are very common in some parts of the world.

>  it would be quite confusing to tag the sidewalks on the roadway itself. Tagging sidewalks on the roadway itself is okay for smaller roads, but the broader a road becomes, the less practical is this tagging.

Respectfully, I again disagree. Tagging sidewalks should be done on both the roadway (using `separate` value) and as a separate way for data consumers and for the data to best represent and model reality. This is for all roads, regardless small or big.

> (https://www.openstreetmap.org/way/575738505 has mapped sidewalks along it, so SC would not ask there anyway)

Yeah because I mapped it already. Mapping these as separate ways is not too common yet in my area, so there are plenty of trunk roads with sidewalks without a tag or separate way mapped, probably 90% of the ones in Sydney fit into this category.

**Comment by smichel17** [comment]
Tagging sidewalks on the roadway itself seems useful even for roads where it *ought* to be mapped separately, since it provides something which could be searched for and fixed in id/josm.

**Comment by westnordost** [comment]
Ok. Country-side trunks are excluded by the usual filter anyway.
