### ISSUE TITLE
Maxspeed zone sign has no "zone" label in Poland, mismatches with actual signs in other places

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2954]
I think that special graphic in max speed quests in Poland would be helpful and be less confusing for mappers.

Image from https://doba.pl/dsw/artykul/komentarze/26044/64/
![image](https://user-images.githubusercontent.com/899988/121171663-0d8d3500-c857-11eb-90e1-355c97ddd12f.png)

**Comment by westnordost** [comment]
...and in most countries, the zone label is above the 30, not below

**Comment by matkoniecz** [comment]
https://commons.wikimedia.org/wiki/Category:Diagrams_of_speed_limit_zone_road_signs has some signs that may be useful (though some may be historic or outdated)

**Comment by peternewman** [comment]
> New Zealand question: https://commons.wikimedia.org/wiki/File_talk:New_Zealand_road_sign_R1-8.1_(10).svg https://en.wikipedia.org/wiki/Talk:Road_signs_in_New_Zealand#Zone_speed_limits%3F

Neither https://www.nzta.govt.nz/roadcode/general-road-code/road-code/about-limits/speed-limits/ nor my tame Kiwi seem to show a difference, or even list the square sign. The best bet was "I’m not sure 🤔 maybe it’s just a design that changed over time?". Have you tried StreetView or similar to try and find some square signs?
