### ISSUE TITLE
Resurveyed lit on motorways

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#2955]
I found a 6 years old motorway with `lit=no`.
Because of this line:
https://github.com/streetcomplete/StreetComplete/blob/cc463fcf17699a6631c8a1945d9bb76f58d54bfb/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt#L37
I got asked if the motorway is still not lit.  (I configured SC to ask me more often so a 6 year old way is triggered after 4 years)

IMO this `lit=no` list should be a bit filtered...

https://www.openstreetmap.org/changeset/105908426#map=17/48.74043/10.19655

**Comment by matkoniecz** [comment]
> SC should ask me more often

> IMO this lit=no list should be a bit filtered...

What exactly is requested here? Asking more frequently? Not resurveying `lit` on ways where this quest would not be asked in the first place?

BTW, `highway=bus_stop` `lit` would also be triggered here - and should rather trigger own quest. So I definitely limit to asking on roads. Butresurvey for motorways seems fine.

**Comment by HolgerJeromin** [comment]
> What exactly is requested here? Asking more frequently? 

Sorry, tried to explain why showing a 6 year old way is no bug even if the code shows 8 years. Rewritten the post a bit.

> Not resurveying lit on ways where this quest would not be asked in the first place?

Yes, I expected the lit quest on no motorways at all. 
But feel free to close this issue as wontfix.

**Comment by matkoniecz** [comment]
> Sorry, tried to explain why showing a 6 year old way is no bug even if the code shows 8 years.

Have you enabled more frequent resurvey in settings?

**Comment by smichel17** [comment]
@matkoniecz The issue is indeed about not resurveying `lit` on ways where the quest would not be asked in the first place.  
The part you're focusing on was intended something like, "Please don't get distracted by the dates; I enabled more-frequent-resurvey, so that part is working as expected". But with language issues it had the opposite effect :laughing:
