### ISSUE TITLE
Sitzbänke auf Karte darstellen

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#2960]
Wenn ich an einer Bank vorbeikomme, wird manchmal gefragt, ob die Bank noch ex., manchmal wird nicht gefragt.
Im letzteren Fall kann a) schon jemand anderes die Frage beantwortet haben oder b) die Bank ist noch nicht erfasst.
Bei b) könnte ich eine Notiz bzgl. der Ex. hinterlassen.

**Comment by westnordost** [comment]
Out of scope
