### ISSUE TITLE
No download possible while uploading

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2967]
I am unable to download new quests while an upload is running. Is this normal?
Even on WiFI the upload takes about one second per answered quest, so I'm sometimes blocked for several minutes.

**Comment by mnalis** [comment]
Perhaps the reason is so the download will have the latest data (including your changes)? I'm completely guessing here, but doing it in parallel might lead to wrongly repeated or missing quests?

**Comment by westnordost** [comment]
No, it is not normal.

Which version? What exactly is not working for the download?

**Comment by westnordost** [comment]
Also, I need the log, do you have the log?

**Comment by westnordost** [comment]
But maybe it **would** make sense to serialize access to the OSM API, i.e. while download is running, querying/updating map data is blocked and the other way round. However, this is currecntly not the case, so I don't see how download should not be possible while uploading.

**Comment by Helium314** [comment]
Using recent master (except for today's commit) with some personal modifications. None of these touches anything with upload or download, but in theory the problem could be my fault. I can try reproducing in a "default" version.
Auto-upload is off, download was started manually.

I cut the log down quite a bit:
```
06-12 13:18:09.219 16849 16928 I Upload  : Starting upload
06-12 13:18:09.523 16849 17043 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
<some more uploads skipped, now the download starts>
06-12 13:18:21.525 16849 16928 I Download: Starting download (48.2868482, 14.2877197 -> 48.2941580, 14.2932129)
06-12 13:18:22.324 16849 16871 W reetcomplete.h: Long monitor contention with owner DefaultDispatcher-worker-7 (17043) at void de.westnordost.streetcomplete.data.osm.edits.MapDataWithEditsSource.rebuildLocalChanges()(MapDataWithEditsSource.kt:342) waiters=0 in java.util.List de.westnordost.streetcomplete.data.osm.edits.MapDataWithEditsSource.getGeometries(java.util.Collection) for 1.092s
06-12 13:18:22.330 16849 16875 D OsmQuestController: AddHousenumber requires surrounding map data to determine applicability to WAY#121035389
<many more uploads, nothing containing the word 'download'>
06-12 13:48:51.924 16849 17043 I OsmQuestController: Persisted 1 new and removed 0 already resolved quests in 0.0s
06-12 13:48:53.359 16849 17043 I ChangesetManager: Created changeset #106250625
06-12 13:48:53.483 16849 17043 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
06-12 13:48:59.343 16849 17043 I OsmQuestController: Created 0 quests for 27 updated elements in 5.8s
06-12 13:48:59.346 16849 17043 I OsmQuestController: Persisted 0 new and removed 0 already resolved quests in 0.0s
06-12 13:49:16.401 16849 17043 I Upload  : Finished upload
06-12 13:49:16.534 16849 18815 V MapTilesDownload: Tile 16/35369/22702 in cache
<now download starts>
```
The upload takes half an hour because I left the phone alone with screen off, so it spent most of the time doing nothing.

**Comment by Helium314** [comment]
Ok, I just noticed that actually in my build of SC I actually have some change related to download:
Auto-download is disabled when auto-upload is switched off (basically the pre-v28(?) behavior, helps a lot when moving fast with slow internet).

**Comment by westnordost** [comment]
Alright so this is a non-bug. However, I think it would make sense to serialize access to the OSM API, I'll do that.

**Comment by westnordost** [comment]
RElated here may be that sometimes quests can be answered twice - this may be a race condition between download and applying the user's answer.

**Comment by westnordost** [comment]
I should make the upload and the download use the same (serialized) background service, this way it is guaranteed that download and upload will never happen at the same time and the side effect is that the upload will also be wrapped in a (foreground) service, which means it cannot be cancelled by the Android system when the app is sent into the background.

**Comment by Helium314** [comment]
> which means it cannot be cancelled by the Android system when the app is sent into the background.

This is great, thanks. Then I don't need to keep the screen on when uploading a few hundred answers.

Could you prioritize downloads over uploads? So that uploading is suspended until download is finished.

**Comment by westnordost** [comment]
Mhh, this would be more difficult because it would involve canceling the current job when a specific new one arrives but then also restart it after that is done. Why would you want that? 

Am 21. August 2021 08:36:44 MESZ schrieb Helium314 ***@***.***>:
>> which means it cannot be cancelled by the Android system when the app
>is sent into the background.
>
>This is great, thanks. Then I don't need to keep the screen on when
>uploading a few hundred answers.
>
>Could you prioritize downloads over uploads? So that uploading is
>suspended until download is finished.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2967#issuecomment-903069238

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
As mentioned, upload takes about one second for each answer. When not immediately uploading answers, there are often a few hundred changes awaiting upload, and after starting upload it means I can't download new quests for the next 5-10 minutes.
Sometimes I just kill the app so I can download quests sooner...

**Comment by smichel17** [comment]
You could use a queue, where uploads are inserted one item at a time at the end and downloads are inserted at the front. That way, triggering a new download would finish uploading the current quest, then start on the download, then resume any remaining uploads.

On August 21, 2021 9:44:24 AM UTC, Tobias Zwick ***@***.***> wrote:
>Mhh, this would be more difficult because it would involve canceling the current job when a specific new one arrives but then also restart it after that is done. Why would you want that? >
>
>
>Am 21. August 2021 08:36:44 MESZ schrieb Helium314 ***@***.***>:
>
>>> which means it cannot be cancelled by the Android system when the app
>
>>is sent into the background.
>
>>
>
>>This is great, thanks. Then I don't need to keep the screen on when
>
>>uploading a few hundred answers.
>
>>
>
>>Could you prioritize downloads over uploads? So that uploading is
>
>>suspended until download is finished.
>
>>
>
>>-- >
>>You are receiving this because you were assigned.
>
>>Reply to this email directly or view it on GitHub:
>
>>https://github.com/streetcomplete/StreetComplete/issues/2967#issuecomment-903069238
>
>
>
>-- >
>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
>
>
>
>-- >
>You are receiving this because you are subscribed to this thread.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/streetcomplete/StreetComplete/issues/2967#issuecomment-903091056
-- 
To respect your time, I try to write short, functional emails.

**Comment by westnordost** [comment]
Ok, I actually found that download and upload is already serialized. But the foreground notification was missing.
