### ISSUE TITLE
"same as adjacent street" option

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#2968]
For quests like speedlimit an option would be nice to say the street has the same properties as an adjacent street. When you walk a road and come to an intersection you often don't know, if you are in an area with speedlimit or in a city. But when there is no sign, you can be sure, that the other streets have the same speedlimit.

**Comment by matkoniecz** [comment]
Which tags StreetComplete would use in such situation?

As far as I know this answer cannot be applied as no tagging in OSM exists for such situation - maxspeed is always tagged specifically, with no existing tagging for that.

**Comment by tiptoptom** [comment]
@matkoniecz I think you got me wrong. I mean, it would be nice if you are in the maxspeed quest for street1 you can just klick on street2 and street1 would get the maxspeed tag of street2. So this would just be an alternative to typing the speedlimit in.

**Comment by matkoniecz** [comment]
What if street2 is not yet tagged with maxspeed?

**Comment by Helium314** [comment]
It could be done like for the address street quest, where selecting a street without name does nothing.
But then there would need to be some indication which streets already have maxspeed tagged.

**Comment by westnordost** [comment]
And then we'll have confused users that report bugs that tapping on a street to apply the maxspeed limit for an adjacent street does not work.

**Comment by tiptoptom** [comment]
@westnordost Maby there could be a pop-up message, saying that the chosen way has no speedlimit or a special speedlimit.
