### ISSUE TITLE
smarter text search in tag features search - at least trailing spaces should not remove matches

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2971]
**Use case**
Make easier to find features when replacing gone shops

Note: it may belong rather in https://github.com/westnordost/osmfeatures

To reproduce, with English as language: 

find name/opening hours/etc quest
select "can't say" -> "it does not exist"
place typing cursor in "A(n)"
type "boutique" - works as expected, sows relevant matches
press space - does not work as expected, matches are lost

As bonus: "boutique foobar" should also match terms produced by "boutique". Writing also shop name is not expected but some users will do it anyway: https://www.openstreetmap.org/note/2521421 ("Wpisałem chyba butik i nazwę" - "I probably wrote boutique and its name").

**Comment by westnordost** [comment]
`.trim()`

**Comment by matkoniecz** [comment]
I though about splitting on space and searching also each word separately, to support case of someone writing multiple words, with one matching.

**Comment by westnordost** [comment]
Nah. Because there can well be presets that consist of several words.
