### ISSUE TITLE
Expand the addr:housenumber quest to nodes for addresses not tied to specific or entire buildings.

### ISSUE THREAD

**Issue by squeak9** [streetcomplete/StreetComplete#2972]
**Use case**

Sometimes you walk past a building that has multiple individual house numbers all with different positions but it's still just a single building and it's mapped accordingly, this means that streetcomplete can't add house numbers in the correct positions.

Other times you might map a building like [this apartment building](https://www.openstreetmap.org/way/44617780), [this one](https://www.openstreetmap.org/way/26309146) ([mapillary](https://www.mapillary.com/app/?pKey=NkjHRZUY0zvH6F9c19XXqQ&focus=photo)) or [this rowhouse/terrace](https://www.openstreetmap.org/way/166881422) and you can clearly see from aerial imagery and/or street level photos that this is a single apartment building with multiple entrances but you can't find out what the house numbers are or if they are there at all and you can't get there physically so you just add things like `entrance=staircase` or `entrance=home` if it's a terrace/rowhouse. Later on someone else walking by with the app can't add addresses to those entrances, ~~just~~ and not just the entire building.

**Proposed Solution**

StreetComplete could search for single nodes that could have possible potential house numbers like `entrance=*` or partial addresses like `addr:street=*` and ask if the nodes have house numbers and what they are.

This could even be expanded to other nodes that might have addresses like businesses or stores.

Another solution could be that StreetComplete could add the functionality of adding nodes with addresses to features like buildings where entrances aren't mapped but this could be outside of the scope of the app and more work.

**Comment by andrewharvey** [comment]
I encounter this occasionally and always just add a note on the map at the entrances to say it's an entrance with address X, and then later map it with iD/JOSM.

**Comment by Helium314** [comment]
So something like:
If the building has no house number and more than one entrance: ask for each entrance, and ignore entrances when checking whether the building has a house number (otherwise you can only tag one entrance)

Or:
If the building has more than one entrance, ask for each, even if the building already has _one_ house number (don't ask if there are multiple address nodes not on entrances)


Aside from technical things: how likely is it that a house has multiple entrances tagged that have the same address (house number and unit)?

(with _entrance_ in this comment I mean only `entrance ~ yes|main`)

**Comment by squeak9** [comment]
> I encounter this occasionally and always just add a note on the map at the entrances to say it's an entrance with address X, and then later map it with iD/JOSM.

That works for the first use case I guess.

> Or:
> If the building has more than one entrance, ask for each, even if the building already has _one_ house number (don't ask if there are multiple address nodes not on entrances)

I think this one would let you map all those 13A, 13B, 13C addresses which is always nice so it seems like the better option.

**Comment by mnalis** [comment]
@squeak9 it works for other use cases too - you just need to long press at the desired location on the map, and then can add note at that specific location (and not just in center of building, as when you answer `can't say` in response to question)

Or, if you're keen on adding new elements (instead of notes) while on the go, you can use editors tailored for that purpose, like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci), but that comes with higher learning curve.

**Comment by matkoniecz** [comment]
>  If the building has more than one entrance, ask for each, even if the building already has one house number (don't ask if there are multiple address nodes not on entrances)

Such address duplication would be definitely unwanted at least in Poland. It would be considered as extremely unusual and invalid and pointless and unwanted tagging.

**Comment by westnordost** [comment]
The suggestion has (at least) one issue, see @matkoniecz , and is not trivial to implement. Also, I plan to add a dedicated "add housenumbers" view in StreetComplete, so this is not really necessary IMO.

If the entrances are visible from aerial imagery and a surveyor adds for example `addr:housenumber=6-18` to the building, another mapper should in most cases have no problem to use this information to put housenumbers on the individual entrances later.

**Comment by matkoniecz** [comment]
> another mapper should in most cases have no problem to use this information to put housenumbers on the individual entrances later.

sadly in many cases order is not obvious, see say https://www.openstreetmap.org/#map=19/50.07144/19.88182


![screen](https://user-images.githubusercontent.com/899988/122673311-1c1d0a00-d1d0-11eb-8f74-70be9ac31453.png)

**Comment by Cj-Malone** [comment]
What's your opinion on this bit?

> or partial addresses like addr:street=* and ask if the nodes have house numbers and what they are.

Take [this](https://www.openstreetmap.org/node/8875376826) node as an example.

Sometimes I come across new contributors using StreetComplete and I like to make sure they have some address quests nearby. Currently that means tracing a bunch of buildings. Skipping the buildings would certainly be quicker for me.

> Also, I plan to add a dedicated "add housenumbers" view in StreetComplete, so this is not really necessary IMO.

Really intrigued by this, looking forward to it.
