### ISSUE TITLE
Be able to tag any building as demolished or destroyed

### ISSUE THREAD

**Issue by ancarda** [streetcomplete/StreetComplete#2974]
**Use case**
The other day, a friend of mine saw a local business burn down. He subsequently updated Google Maps to indicate the business is temporally closed, but wasn't able to figure out how to make the same edit on OpenStreetMap. I had a look on the wiki and wasn't entirely sure how to tag it either.

As far as I can tell, you change this:

```
amenity=restaurant
building=yes
```

To this:

```
destroyed:amenity=restaurant
destroyed:building=yes
```

**Proposed Solution**
I think StreetComplete might be a good app to be able to make these edits. I imagine you could tap on any building and mark it as demolished or destroyed. For destroyed, perhaps it could ask you how (fire and earthquake?), and add the relevant tags. This wiki page: https://wiki.openstreetmap.org/wiki/Key:destroyed: seems to suggest `damage:type` might exist, but is not documented?

I appreciate this is a rough idea, and maybe needs some standardization on the wiki first. I'm not sure where else to ask.

**Comment by matkoniecz** [comment]
>  I imagine you could tap on any building and mark it as demolished or destroyed.

For such editing I would recommend Vespucci. StreetComplete is intentionally offering only predefined quests, not a full scale editing.

**Comment by smichel17** [comment]
I'm going to convert this to a discussion since I am quite sure that the feature as-is would be rejected as out-of-scope.
