### ISSUE TITLE
Link to FAQ (in Settings / About menu)

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2976]
**Use case**
When people have a problem with StreetComplete, or can't find or don't understand something, they will look for help.
Currently, they seem to stumble to "Report error" and land to GitHub issues and report new issue, while their problem might be listed in [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ). Latest example in request for Undo in https://github.com/streetcomplete/StreetComplete/issues/2970, but there were many more I've noticed through time.

**Proposed Solution**
as mentioned in https://github.com/streetcomplete/StreetComplete/issues/2817#issuecomment-856719258, linking to [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ) in `About` menu, before `Report error`, and mentioning FAQ in `Report error` might help users faster with less effort, while reducing time spent on new / duplicate issues. 

Example mockup (with changes indicated in red):
 ![SC_FAQ_medium](https://user-images.githubusercontent.com/156656/122598653-689c0480-d06d-11eb-961d-3c4d2ecad75a.png)

**Comment by westnordost** [comment]
I just refined the issue templates to mention the FAQ.

**Comment by mnalis** [comment]
Oh, OK. But IMHO it still might be worth to **include link to FAQ** in the **StreetComplete menu** as suggested - some people will not go full effort to report an issue, but would still read the FAQ and learn something (even maybe few other things that they aren't specifically looking for but looking interesting - that happens to me often with many things, so I open then in new tabs and then read them). Sometimes I even skim the FAQ of the app I'm using if I'm not having any particular issues, and learn new things.
