### ISSUE TITLE
Scrape translator stats from POEditor

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2980]
It is really laborious to extract the information which translators contributed how many words to each language translation. This information is necessary to fairly mention the translators in the credits.

So far, translators are mentioned for each language roughly in the order in how much they contributed, but even this rough order is really time-intensive to research.

**Proposed solution**
Write a script that scrapes the HTML pages of POEditor for that information (number of words translated) and puts it into a f.e. YAML file that is structured like this:
```
it:
  Mirco Zorzo: 9766
  Manuel Tassi: 254
  marco: 123
eu:
  Osoitz: 6889
```

When this information is available, the statistic can be generated automatically, thus less time is spent on going though this manually. Also, it would be possible with very little effort to make the translator credits much more interesting to look at and explore (f.e. use the bubble view like with the quest statistics)

**Comment by westnordost** [comment]
Ideally, the script would be a gradle task written in kotlin. See `buildSrc` for other gradle tasks.

**Comment by matkoniecz** [comment]
Seems to be the same idea as https://github.com/streetcomplete/StreetComplete/issues/629#issuecomment-857715399

**Comment by westnordost** [comment]
Yes, it is. But that was just a comment in another ticket.

**Comment by westnordost** [comment]
I started researching this and ended up with a WIP implementation. There are some things left to do but I lost interest for now:
- use session cookie (etc) for querying the page(s)
- scrape the contributors HTML page for the user id + user name(already researched where the information is located)

@matkoniecz, you seemed to be interested to do this, maybe you or someone else would like to continue?

The branch name is `scrape-translator-credits`, see [ StreetComplete/buildSrc/src/main/java/GetTranslatorCreditsTask.kt ](https://github.com/streetcomplete/StreetComplete/blob/scrape-translator-credits/buildSrc/src/main/java/GetTranslatorCreditsTask.kt)

**Comment by peternewman** [comment]
Is it worth having this as a standalone Gradle task in a separate repo so other people can use it? I know I had a look when it was first mentioned and couldn't find any existing code or GitHub Actions or whatever and given 114 people have found that issue and voted for it there is obviously desire within the community. I assume something like that could be included in the existing Gradle workflow fairly easily.

Just to confirm if anyone else wants to work on it, they'd either need to setup a separate test project or be granted additional rights on the POEditor setup as per https://github.com/streetcomplete/StreetComplete/issues/629#issuecomment-859140811

**Comment by matkoniecz** [comment]
> Is it worth having this as a standalone Gradle task in a separate repo so other people can use it?

Higher risk of it getting noticed by POEditor and treated as something unwanted.

**Comment by peternewman** [comment]
> Higher risk of it getting noticed by POEditor and treated as something unwanted.

Yes maybe, but they're pretty short-sighted if they choose to block a feature which a large number of people have asked for and someone has implemented for them for free!

**Comment by westnordost** [comment]
It is how it is
