### ISSUE TITLE
Split changesets that would have large bounding boxes

### ISSUE THREAD

**Issue by zombiewizard45** [streetcomplete/StreetComplete#2988]
If a user completes a quest type in two different places and uploads them together they are all added in a single changeset with a massive bounding box. In some cases, the bounding box spans over several countries or even worldwide [like here](https://www.openstreetmap.org/changeset/106624474), [here](https://www.openstreetmap.org/changeset/106674441), [here](https://www.openstreetmap.org/changeset/106149906), or [here](https://www.openstreetmap.org/changeset/105936232). The disadvantages of changesets with large bounding boxes have been discussed in the past, and generally they are seen as unfavorable. As such, I suggest that changesets be split up automatically if they would have a bounding box over a certain size, such as more than 25,000 square kilometers or having a diagonal length more than 150 kilometers.

**Comment by westnordost** [comment]
This is a duplicate

On June 21, 2021 5:29:26 PM GMT+02:00, zombiewizard45 ***@***.***> wrote:
>If a user completes a quest type in two different places and uploads
>them together they are all added in a single changeset with a massive
>bounding box. In some cases, the bounding box spans over several
>countries or even worldwide [like
>here](https://www.openstreetmap.org/changeset/106624474),
>[here](https://www.openstreetmap.org/changeset/106674441),
>[here](https://www.openstreetmap.org/changeset/106149906), or
>[here](https://www.openstreetmap.org/changeset/105936232). The
>disadvantages of changesets with large bounding boxes have been
>discussed in the past, and generally they are seen as unfavorable. As
>such, I suggest that changesets be split up automatically if they would
>have a bounding box over a certain size, such as more than 25,000
>square kilometers or having a diagonal length more than 150 kilometers.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2988

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+large+bounding+boxes+is%3Aclosed

**Comment by vpzomtrrfrt** [comment]
All of those issues are closed, has this problem been resolved?

**Comment by matkoniecz** [comment]
Changesets are not split, explanation is in one of closed issues.

Part of reason is that it makes easier to spot users who use SC incorrectly, without survey, based on guessing.
