### ISSUE TITLE
Check if element still exists may leave items with no tag

### ISSUE THREAD

**Issue by naomap** [streetcomplete/StreetComplete#2989]
OSM object : https://www.openstreetmap.org/node/2870940712
Changeset : https://www.openstreetmap.org/changeset/98225797

This node has been left with no tag rather than being removed. This might be due to the fact it belongs to a relation, however it should have been removed (in this case at least) rather than left as an orphan node.

**Comment by westnordost** [comment]
I.e. the app cannot know if the deleted element fulfills a meaningful role in the relation or not,  so it rather does not delete it if the element is referred to by another way or relation

**Comment by naomap** [comment]
Does this quest cover via nodes of a relation ? This sounds like a bad idea to me. 
IMHO the quest should do nothing rather than leaving dirty data behind : if it decides that it should not delete the object it should propose it to the user.

**Comment by westnordost** [comment]
> Does this quest cover via nodes of a relation ? This sounds like a bad idea to me.

That was an example. Suppose that a `highway=crossing` is also a via node in a turn restriction relation or something like that.

**Comment by westnordost** [comment]
Another example: Suppose that a `highway=crossing` is also part of a new kind of route relation where the route is not made up of consecutive connected ways but only of consecutive bus stops and support points (for routing) and that crossing is actually a support point. So, a meaningful role in a (new kinf of) relation could even be one where the member itself is maybe not even assigned a `role`.

**Comment by naomap** [comment]
I'm not sure what the solution is, however it is not satisfactory to leave dirty data behind. A compromise might be to add a fixme so that a mapper can inspect the node and decide to remove it or not. I do not really like the idea to split the job between people using StreetComplete and other mappers tidying up behind them though...

**Comment by matkoniecz** [comment]
It can be:

- keep as is
- StreetComplete skips nodes in relations
- maintaining list of relation types where node can be safely deleted/removed from relation, allow delettion of nodes in such cases (and removal from relation if node is also belonging to a way)

BTW, I want to register my opinion that relations such as https://www.openstreetmap.org/relation/4246999#map=17/48.93487/2.34591&layers=N are confusing silliness, without real value but making editing harder. Especially to newbie mappers (SC issues are the smallest issue).

Such relation are obnoxious in maintenance, require constant upkeep, with dubious value, likely to be missing some elements and in general waste of time. And excellent generator of tricky to handle issues in editors :/

![screen](https://user-images.githubusercontent.com/899988/123051142-bf089a80-d401-11eb-8441-021d82939afe.png)

**Comment by naomap** [comment]
I would opt for the 3d option – however this is probably the hardest to implement ? 
I certainly agree with your opinion on these relations. These were produced in the past to help extracting data, which is at the very least questionable. The good news is that this is no longer used, and we plan to tidy this up and only keep elements that relate to public transport. This will most likely be done after the summer though.

**Comment by matkoniecz** [comment]
> I would opt for the 3d option – however this is probably the hardest to implement ?

Yes, and it may fall under "unreasonably complex, not going to happen" or "waiting for someone caring enough to implement it"

**Comment by naomap** [comment]
... or no longer needed as relations are going to be tidied up :-)
I leave it to you to close it :-)

**Comment by matkoniecz** [comment]
yeah, if it happens with relations that are supposed to be existing then it may be worth reopening

But relations known to me either are not going to have elements where this quest applies or empty node should continue to be present.

So I will close it, as implementing workaround would be quite obnoxious.

**Comment by westnordost** [comment]
From the point of view of this issue, there are broadly two types of relations:
1. "collection" relations, which represent a collection of other elements. site relations, such train station relations and even multipolygon relations would count in that category. Maybe even route relations. For these, it would be ok to remove the element.
2. functional relations, which express a relation (haha, hence the name I guess) beyond a mere collection between several other elements. Such relations often also require special  handling in other situations, such as splitting the way. Turn restrictions, turn lanes etc would fall into that category. Here, it would not be ok to remove the element as the element gains meaning beyond its own tags.
