### ISSUE TITLE
"Does it offer Halal products" same as Kosher quest. 

### ISSUE THREAD

**Issue by SMUsamaShah** [streetcomplete/StreetComplete#2990]
### General
Affected tag(s) to be modified/added:
https://wiki.openstreetmap.org/wiki/Key:diet:halal

I am from Pakistan living in UK and this was the first thing I wanted to fill up with StreetComplete. 

Some places/shops offer everything halal. Turkish restaurants on the other hand offer Halal food and also offer wine (which is not Halal), I can still go and eat food there. If this quest is available I'll be marking all Halal food restaurants and shops in my area.

### Ideas for implementation
This can be implemented exactly the same way as Kosher. This Quest is not needed in Muslim countries because it's all Halal there.

This is my second attempt at contributing to OpenStreetMap data because of StreetComplete only. I don't understand lots of terminology it offers so please don't I have missed some info.

**Comment by peternewman** [comment]
See also some past discussion in https://github.com/streetcomplete/StreetComplete/issues/639 which got closed when the Kosher one was implemented. I'll state again there are plenty of Halal labelled shops and restaurants around my area of London and I believe some of the big chain supermarkets offer Halal stuff too.

**Comment by matkoniecz** [comment]
From my notes on issues to be posted:

I posted in Indonesia group.

> Hello! Sorry for the English, I want to ask some Indonesia-specific questions related to StreetComplete.
StreetComplete is an app for Android allowing to map without any OSM-specific knowledge, it just asks some questions. Questions should be answerable by someone who is mapping his surroundings, without going through tutorials or explanations.
I contribute to that project and some time ago "Is this restaurant halal?" was proposed as a new quests suitable for the Indonesia.
So my questions are:
>
>    are there both halal and not halal restaurants in Indonesia?
>    is it always possible to distinguish halal and not halal restaurant, without going inside?

I got reply from @jeisenbe

> “Are there both halal and not halal restaurants in Indonesia?” - yes
> "is it always possible to distinguish halal and not halal restaurant, without going inside?” - sometimes, but not always.
> Some restaurants specifically advertise that they serve pork or dog meat, which make them clearly non-Halal, and many restaurants will have a symbol on the window or door which distinguishes them as Halal. But most restaurant’s are small and have limited signage. You can try to guess by the cuisine, but sometimes that is not accurate.

**Comment by westnordost** [comment]
Why did you ask on the Indonesia group at all? Couldn't it be the same as the kosher quest? Disabled by default?

**Comment by matkoniecz** [comment]
> Why did you ask on the Indonesia group at all?

I though that maybe it can be enabled by default in some regions, also to check which objects shoul get that question.

**Comment by SMUsamaShah** [comment]
What can be done to add this feature?

**Comment by matkoniecz** [comment]
Someone would need to implement quest, similar to how it was done in #2244

One of things to do is finding an icon, matching StreetComplete style and fitting this quest.

**Comment by Helium314** [comment]
Adding the quest itself is pretty simple as you mentioned in the initial post.

Work is necessary for the Icon, for selecting countries where the quest should (not) be shown, and for element selection (restaurants, supermarkets, ... and when not to show, e.g. a purely vegan restaurant should be halal anyway if I understand correctly)

**Comment by SMUsamaShah** [comment]
Word Halal written in Arabic (with green font or background usually) is the most common way. I can make the icons. You are right about vegan being halal *except* Alcohol/Wine.

**Comment by Helium314** [comment]
If you can find some suitable vector graphics with a license that allows usage in StreetComplete that would be useful.

So the halal quest basically needs to be asked regardless of other diets, because they may mean there are halal products being sold, but there is no way to know whether it is halal=yes or halal=only.

**Comment by FloEdelmann** [comment]
There seems to be a consensus on a Halal logo: https://www.google.com/search?q=halal+logo&tbm=isch
Here is a CC0-licensed SVG version: https://openclipart.org/detail/320701/halal-sticker

<img src="https://openclipart.org/image/400px/320701" width="200">

**Comment by westnordost** [comment]
Nice. For the quest icon, just the Arabic word for halal should be used because otherwise the icon would be too busy.

**Comment by Helium314** [comment]
@SMUsamaShah you said that this quest is not necessary in muslim countries because everything is halal.
However, at least in Turkey there are [alcoholic drinks](https://en.wikipedia.org/wiki/Rak%C4%B1) and in Indonesia there are places serving pork and dog meat (see above).

So it would help to have some more information which countries can be excluded from this quest.

**Comment by westnordost** [comment]
A place that serves alcoholic drinks doesn't make the place `diet:halal=no`. It would only be `diet:halal=no` if that place had **nothing** halal.

So, I am not an expert on halal, should the quest type be disabled for certain countries where either in every place, there is something halal to eat (muslim countries)?

**Comment by Helium314** [comment]
> So, I am not an expert on halal, should the quest type be disabled for certain countries where either in every place, there is something halal to eat (muslim countries)?

@SMUsamaShah said that it should, but only mentioned that it should be disabled in muslim countries because everything is halal there.
My question was aiming at which countries do count as "muslim enough" so the quest would not be necessary.

**Comment by SMUsamaShah** [comment]
At the moment I am only certain about Pakistan and Saudi Arabia. Looked up a bit on internet and its confusing. For example I read about Bahrain where pork sale is allowed. Same goes for UAE.
So probably exclude these initially and more later on request.

**Comment by SMUsamaShah** [comment]
> A place that serves alcoholic drinks doesn't make the place `diet:halal=no`. It would only be `diet:halal=no` if that place had **nothing** halal.

What if a place has only one halal item on their menu. Saying that halal=yes would be unfair. I don't know if open maps already support this but halal=yes and halal=only are very sensible choices for these cases.

**Comment by westnordost** [comment]
There should be "a reasonable eating choice", I think was the wording. So for example for vegetarians, there shouldn't be just a salad.

**Comment by Lee-Carre** [comment]
> I believe some of the big chain supermarkets offer Halal stuff too.

Of those I've asked, in Jersey (which has similar chain retailers to the UK), several have said that they either have a section of ‘blessed’ (though not necessarily accredited) products, or all of their (meat) products are.

I've encountered food service places (restaurants, cafes) which have said that their catering supplier's (meat) products are all Halal.

I think an important distinction needs to be made between accreditation or simply observing religious slaughter. From what I've read (as a non-religious layman), accreditation matters for orthodox theists.

**Comment by SMUsamaShah** [comment]
I took the existing kosher icon and modified it
https://gist.github.com/SMUsamaShah/e511796930599726979f2fd7326c4718#file-halal_txt_compressed-svg

Tools used:
https://svgedit.netlify.app/editor/index.html to edit and save text as image
https://www.visioncortex.org/vtracer/ to convert image to vector
https://jakearchibald.github.io/svgomg/ to minify svg

**Comment by SMUsamaShah** [comment]
> There should be "a reasonable eating choice", I think was the wording. So for example for vegetarians, there shouldn't be just a salad.

I am saying about having single item on menu because on Uber Eats I found a place under halal listing with exactly 1 halal item in menu. There was a second one, it was mix of many dishes including halal meat plus pork. It's same as calling a dish vegetarian because it has salad in it.

For now, I believe having Halal with same specs/flexibility as Kosher will be good enough. I will be marking all halal only shops at least. These are the shops where I can go and just pick anything without thinking.

Will it be OK if I submit a pull request? I don't do Android development so I will be basically copy the Kosher pull request and modify it for Halal.

**Comment by westnordost** [comment]
Sounds good! Things to note:
- the quest icons are in /res/graphics/quest icons. The halal icon should have the same orange background as kosher, only with the arabic halal-writing instead. I can recommend Inkscape to edit SVG files. When you are done, you can import an SVG with Android Studio as a vector asset
- Make sure you search the entire project for "AddKosher" and also add your "AddHalal" at those places too.

**Comment by SMUsamaShah** [comment]
Submitted this pull request #3331

**Comment by FloEdelmann** [comment]
> Submitted this pull request #3331 

@SMUsamaShah please don't close the issue before the pull request is merged. It will be closed automatically when merged, because you wrote `fixes #2990` in the PR description.

By the way, there's no need to also write `closes #2990` in a PR comment, as only the PR description will be parsed. It doesn't make any difference whether you use the `fixes` or `closes` keyword in the PR description, both work the same.

**Comment by peternewman** [comment]
@SMUsamaShah I've been pondering whether we should stop asking the Halal quest on vegetarian/vegan ONLY places.

From a bit of reading it seems it might make sense for vegan, but there are some complexities for vegetarian, although I'm guessing the average vegetarian restaurant is unlikely to know how their milk cows were slaughtered or what they were fed on, so asking the question there may be pointless. I'm also assuming a vegan restaurant won't use vanilla in ALL of it's dishes.
https://allplants.com/blog/lifestyle/vegan-diet-is-it-halal
https://crueltyfreereviews.com/articles/is-vegan-food-halal/

Does that seem broadly sensible to you/match with your experiences? While quite a lot of food places near me have Halal signage, there are only a handful of vegetarian only and no vegan only places, so I've not got much to work with, just some possibly misplaced logic.

**Comment by SMUsamaShah** [comment]
Reading your linked pages, I didn't know vanilla can be considered not halal. Its my favorite flavor in ice-cream and other things that use it. A search on it returned mixed results so i don't know what the general consensus is, but where I live, i have never heard that it's considered haram.

For eating Vegan food, I will probably only look for amount alcohol to consider whether or not I should eat it. As for asking for halal on vegan only places, you are right they wouldn't know. You are probably correct in suggesting that we should stop asking for halal on vegan only places.

**Comment by peternewman** [comment]
> Reading your linked pages, I didn't know vanilla can be considered not halal. Its my favorite flavor in ice-cream and other things that use it. A search on it returned mixed results so i don't know what the general consensus is, but where I live, i have never heard that it's considered haram.

Oh dear, I hope I've not ruined your favourite ice-cream! It was news to me too.

> For eating Vegan food, I will probably only look for amount alcohol to consider whether or not I should eat it.

👍 

> As for asking for halal on vegan only places, you are right they wouldn't know. You are probably correct in suggesting that we should stop asking for halal on vegan only places.

Cool, I've opened #3883 for this!
