### ISSUE TITLE
Max height quest is too limiting in terms of how many digits I can enter

### ISSUE THREAD

**Issue by waldyrious** [streetcomplete/StreetComplete#3000]
I've been adding max heights in Portuguese highways and in some cases I haven't been able to input the correct value, because the signed height is so large (more than 10 meters) that it requires more than 3 digits (or more than 4 characters, if you count the decimal point), and StreetComplete does not allow me to enter any more text.

For example, I [recently had to edit](https://www.openstreetmap.org/changeset/107038928) the `maxheight` value of two ways from "11.5" to "11.49" (the actual value in the sign). [Here's another instance](https://www.openstreetmap.org/way/382467899) of a `maxheight` value of "26.1", that I was only able to enter in abbreviated form using StreetComplete (unfortunately I can't recall if I had to round or just truncate a trailing zero, but I _do_ recall that the sign did have four digits).

**How to Reproduce**
- Try to add a max height containing more than three digits, e.g. "12.34".
- StreetComplete won't allow you to enter any more text after "12.3".

**Versions affected**
v33.0-beta1

**Comment by matkoniecz** [comment]
Note that with this change `12.34` will look like this:

![screen](https://user-images.githubusercontent.com/899988/123686769-73fee500-d850-11eb-8501-cb0bbf659e0c.png)


but it is so rare so I think that it would be OK?

**Comment by westnordost** [comment]
No, that's not okay. Yes, `EditText` does not support `autoSizeMinTextSize` etc, but what should work is to put the edit text into a `AutofitLayout`, see for example housename layout.

**Comment by westnordost** [comment]
I see you self-assigned this. When you fix it, please note that there is also a layout for Australia and Canada which would need to be adapted too

**Comment by waldyrious** [comment]
Thanks for the quick fix! And wow, I hadn't realized this was issue #3000! What do I win? 😄

**Comment by smichel17** [comment]
Probably a few extra :star:'s from the MaxHeight quests you're now able to solve ;)

**Comment by waldyrious** [comment]
Hey @westnordost, I'm not sure if this is a regression but I am again unable to enter large height values (10m or more). This time it's not due to a limitation in the total number of characters, but due to only being able to input a single digit before the decimal point. I will upload a screen recording of me hitting this limitation as soon as I'm able to.

**Comment by matkoniecz** [comment]
I can confirm that it is happening, though I never seen maxheight so large - but if it is a problem, then opening a new issue may be a good idea (is such signed height limit popular in Australia?)

**Comment by waldyrious** [comment]
> but if it is a problem, then opening a new issue may be a good idea

I'd rather reuse this one since it allows the context to remain in the same place (as a end-user, the issue is exactly the same even though the underlying cause may be different).

> (is such signed height limit popular in Australia?)

I don't know about Australia (I assume you're asking because the Australian version of the maxheight quest was changed in ee3a293cdc44d6c1b357f69318ce8f8521441eaa; I believe `app/src/main/res/layout/quest_maxheight_meter.xml`, which was also changed in that commit, is the one that matters to me and most people).

That said, and to answer your question: Here in Portugal, it is quite common, at least in the North, to have extremely high "clearances" simply because of the geography of the terrain. [Here's a Mapillary shot](https://www.mapillary.com/app/?lat=41.284097435318&lng=-8.2567562194753&z=17&pKey=4326783544021208&focus=photo) corresponding to my note [3865957](https://www.openstreetmap.org/note/3865957), for example.

**Comment by mnalis** [comment]
> I'd rather reuse this one since it allows the context to remain in the same place (as a end-user, the issue is exactly the same even though the underlying cause may be different).

GitHub creates links between issues easily when you mention it (e.g. just specify `Has same user-visible effect at issue #3000` in new ticket and GitHub will add a link to both automatically). The problem with commenting on closed tickets is (among other things) that they are **quite easily overlooked and forgotten about**, as they are **not** shown as something that needs fixing. Also, several smaller linked issues is much better than one big ticket with many comments from usability perspective.

**Comment by waldyrious** [comment]
Right, good points. I'll go ahead and open an new issue, then.
