### ISSUE TITLE
Reset building type to unknown, when user indicates so in House-number quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3001]
**Use case**

When solving `house number (address)` quest, I'm often asked about address for a building that does does not have an address (garage, shed, etc). Luckily, there is `It has no house number...` answer, which (after confirming it is not a `house` or whatever), allows me to leave a note - in which I dutifully report correct building type, and then do manual tagging at home with JOSM from all that collected notes.

I guess it happens because armchair mappers see residential neighborhood, and mark all averagely sized buildings as `building=house` or `building=residential`, but whatever the cause is, the problem is unnecessary extra work that brings to StreetComplete user in post-processing, which could've easily been solved at the ground.

**Proposed Solution**

It would be great if the StreetComplete mappers on the ground could correct building type when they see it, instead of creating notes for extra manual work later.

Now with `v32+` that we have StreetComplete which happily works offline and offers quest which depend another quests immediately, I think that the easiest way would be this:

- when user answers that the **building type is not correct** (in response to question `This building was tagged as: house`) instead of leaving the note, simply mark that building as `building=yes`. Then the SC will automatically detect there is quest for building type available, and generate new `building type quest`, where user could choose correct type (or leave note with picture - as always). And even if the user would skip this followup quest, the map would still be improved (**specific but incorrect tag** replaced by **more general but correct tag**)
- alternative option would be in such case to chain `building type quest` answers to `house number quest` as followup question (for example, somewhat like it does in `recycling` quest when `plastic` is selected), but that seems like chaining things too deep IMHO.

**Comment by westnordost** [comment]
Hmm, good idea... I wonder why something like this was not implemented before already? I think this should have worked even before v32 offline

**Comment by cyclingcat** [comment]
What a coincidence - I wanted to open almost EXACTLY the same ticket one or two weeks ago, created a screenshot, started to write some sentences offline but haven't found the time to finish it until now :smile:

I have encountered this situation many, many times during my cycle rides/walks through villages in (German) agricultural regions. In many cases the house number quests were asked for buildings looking as annexes to former farmhouses which turned into residential houses at some time. These annexes, often with a large and high door, could have been barns, sheds or stables in earlier times and now regularly serve as garages or workshops. Nevertheless these kinds of buildings are often tagged with `building=house`, thus triggering the house number quest, however, most of them don't have a house number (there may be exceptions though). They were possibly mapped by aerial imagery, mistagged as `building=house` and never touched again.

This screenshot shows a typical situation with four objects in a small area:

![missing_housenumbers](https://user-images.githubusercontent.com/32601012/123610994-6cfcb600-d801-11eb-80d5-0cdcf32265a3.png)

None of the shown buildings the house number quest is asked for has a housenumber, none of them are residential houses. My suggestion would have been @mnalis' second proposal, but either way would be an improvement. As correcting this mistagging of these buildings definitely needs survey on the ground, SC would be an ideal tool.

The cycling cat

**Comment by westnordost** [comment]
How to tag a buliding annex though?

**Comment by cyclingcat** [comment]
There is the rarely used tag `building=annexe` ([less than 1500 occurences](https://taginfo.openstreetmap.org/tags/building=annexe)). It's not even mentioned in the (German or English) OSM wiki and seems to be used only in [a few places in the world](https://taginfo.openstreetmap.org/tags/building=annexe#map). But there is no need for such a tag IMHO; such an annex could be handled here like any other building, after all it's a separate OSM way, just sharing some nodes with its neighbour. The main point is that this would be a good opportunity to replace the faulty value `house` with something better: ideally a correct value from the long list or even a simple `yes`.

The cycling cat
