### ISSUE TITLE
Unable to validate the number of lanes on a way !

### ISSUE THREAD

**Issue by vincegre** [streetcomplete/StreetComplete#3005]
I noticed a new type of informations request (see screenshot below) but I'm unable to complete it as there is no OK to validate nowhere even if I go in options (Autres options...) offered :(

![Screenshot_20210626-110233_Street­Complete](https://user-images.githubusercontent.com/3164888/123693841-dd82f180-d858-11eb-9d99-961a2d329830.png)

Select it on map and then you can only escape to continue to fill other requests but can't fill that one properly !

OnePlus 7 Pro running Android 11 and StreetComplete 32.1

Thanks

**Comment by vincegre** [comment]
> You have to fill in the other side, too.
> Edit: I want to note that I also had someone confused by this quest. But they didn't know at all that the bars with question marks are clickable.

oki will check tomorrow when out as I thought that if there was no lane on other side of street I didn't need to do anything for it ;)

**Comment by mnalis** [comment]
I've mentioned this in [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#I.27m_missing_the_.22OK.22_button_when_solving_a_quest.21) now.

**Comment by vincegre** [comment]
@riQQ Thanks for clarification and I better understand now how it works or similar requests where I had never the OK button showing up ;)
@mnalis Thanks for the update of FAQ ;)
