### ISSUE TITLE
Search/filter by quest name in preferences

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3008]
**Use case**

Especially as we don't have [quest presets](https://github.com/streetcomplete/StreetComplete/issues/1654), but in other cases too, more avid users need to frequently modify their quest list **manually**, which is quite big (and only getting bigger). This is time consuming and hard to use. What might help to ease the pain, is **quickly finding the quest** to enable/disable. It would help even the casual users quickly trying to find a quest, instead of manually wading through tons of quests.

**Proposed Solution**

It would be quite useful if one had **filter as you type** functionality in quest selection screen, for example activated by clicking on `magnifying glass` icon. Then user could for example type `cyc` and list of displayed quests would show only quests having that text in somewhere in their name (`LIKE "%cyc%"` in SQL-lingo), for example limiting the list to only those quests:

- Is there a **cyc**leway here? What type?
- What type of re**cyc**ling facility is this?
- How many motor**cyc**les can be parked here?
- What type of bi**cyc**le parking is this?
 
If one has `OsmAnd`, `magnifying glass` / `Categories` (or Android preferences search) is good example of the idea I propose.
(I can make a SC mockup if wanted, ie. there is possibility of this).

**Comment by FloEdelmann** [comment]
Note that drag'n'drop has to be disabled once the quest list is filtered.

**Comment by 10992-osm** [comment]
> Note that drag'n'drop/reordering has to be disabled while the quest list is filtered.

One could even design it such that the filtered results allow you to do a one click enable/disable, but if you clicked on the main part of the quest (rather than the tickbox), it could then take you to that quest's location in the full list, allowing re-ordering.
