### ISSUE TITLE
"Does this crossing have an island" asked when a footpath crosses a tram line

### ISSUE THREAD

**Issue by chatcannon** [streetcomplete/StreetComplete#3012]
The app asks if there is an island when a footpath crosses a tram line (a single pair of rails for one tram, not a pair of tram lines for two trams going in opposite directions). Since the rails have a fixed gauge, there is no way to put an island on such a crossing so the question is pointless.

**How to Reproduce**
View this node with the quest "Does this crossing have an island?" enabled:
https://www.openstreetmap.org/node/2475078762

Here is one where I was already asked the quest and have answered it:
https://www.openstreetmap.org/node/906706785

**Versions affected**
32.2 and previous versions for the last few months

**Comment by chatcannon** [comment]
![Screenshot showing the issue](https://user-images.githubusercontent.com/2848682/124222385-565ca480-db0a-11eb-822b-b83ff6593e3c.png)

**Comment by matkoniecz** [comment]
Note that it appears only where `highway=crossing` was used incorrectly, `railway=crossing` should be used there,

https://wiki.openstreetmap.org/wiki/Tag:highway=crossing?uselang=en

(there is also https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_crossing introduced by iD validator, also in places without an actual crossing)
