### ISSUE TITLE
Many bollard quests in rows of bollards

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#3017]
**Use case**

Sometimes there are long rows of bollards, where each bollard is tagged `barrier=bollard`. This creates a lot of bollard type quests. 
![_20210704_204701.JPG](https://user-images.githubusercontent.com/42044179/124396451-ed437f80-dd09-11eb-9bd2-23235666d76b.JPG)![_20210704_204825.JPG](https://user-images.githubusercontent.com/42044179/124396454-f03e7000-dd09-11eb-86aa-1ae2cb26e577.JPG)
This example is a chain which is supported by bollards. Each bollards is mapped as a `barrier=bollard`, and all of them are part of a way tagged `barrier=chain`.

Also, if there is a street crossing a line of bollards, often only the bollards which are in the center of the road are removable. I fear surveyors may start at the end of the the bollard row, starting to answer the quests. After the first few fixed bollards they get tired of looking at each bollard thoroughly, and solve all other quests by choosing fixed. Thus, they may incorrectly also tag the crucial bollard as fixed, even though it is removable.

**Proposed Solution**

Only show the bollard type quest for nodes which are part of at least one `highway=*`-way, which should be simple. Those bollards are the ones which are important for routing.

Maybe also ask for nodes which are part of a way which is part of a `highway=*`-relation, e.g. a pedestrian area Multipolygon. But that's probably more complicated.

**Comment by DerDings** [comment]
I just tried another place where there is a row of bollards, but unexpectedly there wasn't a bunch of quests. So I looked at the quest's code more detailed, and found it already excludes free-floating nodes. It must be the chain in the example above which triggered the quest. Maybe just filter out `barrier`—ways? 
https://github.com/streetcomplete/StreetComplete/blob/c9367d31082e7a102e1442811cb38d35c1fb3d24/app/src/main/java/de/westnordost/streetcomplete/quests/bollard_type/AddBollardType.kt#L29
 Could possibly be extended by
            .filter { it.tags["barrier"] != ". *" }

(I'm not sure about the syntax)

I don't understand why areas are excluded at the moment, though.

**Comment by matkoniecz** [comment]
Or allow only bollards on `highway=*` ways?

**Comment by DerDings** [comment]
> Or allow only bollards on `highway=*` ways?

That was my first idea, but as I saw the current filter is less restrictive, I thought that it may be an advantage being less restrictive. `disused:highway` was the first non-highway which came to my mind. One could also imagine a bollard placed on a `railway=platform`, or in a `railway` which is used by [draisines](https://en.wikipedia.org/wiki/Draisine).

But most important to me are untagged ways which are part of  `highway` multipolygons.

**Comment by westnordost** [comment]
What do @FloEdelmann  and @RubenKelevra think?

**Comment by RubenKelevra** [comment]
Well the target information we like to get from around the world is if a path or a highway can be driven on by an ambulance or other emergency vehicles or if its permanently blocked by a non-removable bollard.

I think we might want to flip the filter and do a whitelist on `highway=*` with the exclusion for `highway=construction`.

**Comment by RubenKelevra** [comment]
Here is a similar case:

![IMG_20210704_234118.jpg](https://user-images.githubusercontent.com/614929/124400256-613d5200-dd21-11eb-80c2-feee5b4d95e8.jpg)

Don't get me wrong, this info is still collectable, since with a row a user can identify the n pole of the barrier, but this is not helpful for routing.

Additionally the users might collect wrong information if there are a lot of poles in a row due to the fact that they are not rendered.
