### ISSUE TITLE
Bad wording for bicycle charging station

### ISSUE THREAD

**Issue by HaasJona** [streetcomplete/StreetComplete#3018]
I just got asked how many cars can be charged at a bicycle charging station, which doesn't make sense.

https://www.openstreetmap.org/note/2740291
https://www.openstreetmap.org/node/7012867594

This node has bicycle=yes and motorcar=no, which should be filtered out according to the information in #2281, but apparently the quest still appears.

**How to Reproduce**
Navigate to said node and get quest

**Versions affected**
v 33.0
Android 10

**Comment by westnordost** [comment]
Which quest? About operator or about capacity?

**Comment by FloEdelmann** [comment]
> How many cars can be charged at this charging station (STAWAG) at the same time?

That seems to be the charging station capacity quest.

This node should already be excluded by the current filter:

https://github.com/streetcomplete/StreetComplete/blob/267ee3b39ab285384ef0c1b93f0a0d788a5b715f/app/src/main/java/de/westnordost/streetcomplete/quests/charging_station_capacity/AddChargingStationCapacity.kt#L13-L18

However, it was [updated just yesterday](https://www.openstreetmap.org/node/7012867594/history) to include these tags; before that, it would have been included by the filter. Maybe @HaasJona you downloaded the data before the change was made?

**Comment by HaasJona** [comment]
> However, it was updated just yesterday to include these tags; before that, it would have been included by the filter. Maybe @HaasJona you downloaded the data before the change was made?

Ouch, I thought I checked the date when that information was added to the node but I seem to have gotten confused. Probably not a bug then.
