### ISSUE TITLE
v33.0 crashes 1 min after starting

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#3019]
The app updated to v33.0 this morning, and since then it crashes exactly 60 s after I start it, no matter what I'm doing in the app (browsing the map, solving quests, uploading quests, doing nothing). Only when after starting the app I go into a settings screen (profile, about, etc) and then do nothing, it goes back to main screen 1 min after startup, and then crashes after another 60 s. When I start uploading (as soon as the icon appears, when on manual upload), it uploads 1 quest in the very beginning (about 11 s after startup, at the same time as the quest pins appear on the map) and then nothing until the app crashes after 60 s.

**Versions affected**
v33.0, Android 10, LG Q60

**Comment by westnordost** [comment]
Any crash report?

**Comment by rhhsm** [comment]
No, it just disappears from the screen. It's still shown among the open apps, but opening it from there is like starting it up from scratch (I get the survey confirmation questions again).

**Comment by westnordost** [comment]
You got the app from F-Droid or Google PlaY?

**Comment by rhhsm** [comment]
Google Play

**Comment by westnordost** [comment]
I don't see any related crashes on Google Play. I also cannot reproduce it.

But kindly download the app from F-Droid. This version will ask you to send a crash report via email when one occurs.

**Comment by rhhsm** [comment]
I can do that. Will the results of my survey this morning be saved (haven't been able to upload them yet)?

**Comment by westnordost** [comment]
No, as you need to reinstall the app. You should upload all your changes before uninstalling the app from google play

**Comment by rhhsm** [comment]
I did, but now it's v32.2 so no problems

**Comment by westnordost** [comment]
Uhm, so we have to wait until F-Droid updates the app to v33

**Comment by westnordost** [comment]
Actually, it is already built, so it shouldn't be long now
https://f-droid.org/wiki/index.php?title=de.westnordost.streetcomplete/lastbuild_3301&redirect=no

**Comment by westnordost** [comment]
v33 is available

**Comment by westnordost** [comment]
@rhhsm can you still reproduce this?

**Comment by rhhsm** [comment]
So far so good. No crashes on v33.0 after a fresh install, both from F-droid and Google Play.
