### ISSUE TITLE
Add opening_hours=closed for amenities and shops that don't work, but still exist

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#3020]
**Use case**
For the opening hours quest, I frequently come across shops, cafes and restaurants that have obviously not been working for some time (dirty windows, fallen leaves, shutters down whenever I pass by, etc.), but are not vacant (the original furniture is still there) or can't be judged not to exist any more (because of the closed shutters). They could open again any moment after a little cleaning. I would like to have an alternative answer for these cases.

**Proposed Solution**
Add an answer option "It has been closed for some time", which adds opening_hours=closed

**Comment by andrewharvey** [comment]
I would tag this as `disused:*=*` https://wiki.openstreetmap.org/wiki/Key:disused:

**Comment by rhhsm** [comment]
> 
> 
> I would tag this as `disused:*=*` https://wiki.openstreetmap.org/wiki/Key:disused:

That's an option too. And of course objects tagged in this way should become the subject of the resurvey quest...

**Comment by westnordost** [comment]
Due to Covid-19?

**Comment by matkoniecz** [comment]
> opening_hours=closed

This is a really bad tagging that should be never used, it creates a nasty trap without a good reason.

> I would tag this as disused:*=* https://wiki.openstreetmap.org/wiki/Key:disused:

That is much better

**Comment by rhhsm** [comment]
Shops that are vacant are now tagged as disused:, isn't it? I'm looking for a tag that is "less disused" than disused:, for shops that are not empty  but not working.

**Comment by westnordost** [comment]
Due to Covid-19?

**Comment by rhhsm** [comment]
> 
> 
> Due to Covid-19?

Maybe there is a higher number of such cases these days, but I expect cases will always occur.

**Comment by westnordost** [comment]
>> opening_hours=closed

> This is a really bad tagging that should be never used, it creates a nasty trap without a good reason.

[It is valid though](https://openingh.openstreetmap.de/evaluation_tool/?EXP=closed). Why do you think it creates a nasty trap?

**Comment by matkoniecz** [comment]
> It is valid though. Why do you think it creates a nasty trap?

Anything processing shop, museum etc data now needs to parse opening hours to hide ones not actually existing.

(Here I treat completely closed shop as no longer being a place where you can buy stuff/services - so as something that is no longer a shop)

I would consider it as trolltag of used on shop= or amenity=museum and so on

( https://wiki.openstreetmap.org/wiki/Trolltag )

I think that it would be fine on things where it is not implied that they are open sometimes, but a poor idea otherwise.

Yes, even open shop can be "open on Monday 10:00-12:00" but in general one can make a reasonable guess of opening hours just based on that shop/amenity/eatery exists.

This tag breaks that and makes OSM data harder to interpret.

**Comment by westnordost** [comment]
Alright,  so this is a wnf then,  there is no lifecycle prefix that is softer that disused

**Comment by FloEdelmann** [comment]
Maybe the wording of the “It's vacant” option can be adjusted though?

E.g. “It's vacant or always closed”

**Comment by westnordost** [comment]
Bit long... does "its disused" make sense?

**Comment by rhhsm** [comment]
My dilemma when I'm standing in front of a shop with closed shutters is: is it a coincidence that it's shut whenever I pass by? Is the operator just on holiday, or maybe in hospital recovering from COVID? Will I create an error on the map, and decreased business for this shop, if I answer that it's vacant? I can't see if it's vacant or not, because the shutters are closed! Or a restaurant which still has all the furniture inside (chairs on top of the tables, so not vacant, translated as "empty" in the Dutch version I'm using) so it could open any time. Is the operator on holiday, or has he fired his staff because of covid and is waiting for the right moment to hire them again and reopen? That moment may never come if I now add to the map that it's vacant (assuming everybody is searching on OSM for restaurant suggestions). Or is it end of business, and is the renter of the space hoping to rent it out to another restaurant operator and make it look more attractive by leaving the furniture inside? There's no "for rent" sign though... 
Google Maps is using a "temporarily closed" tag for this, maybe we should do the same? Or should the meaning of disused:shop be redefined (and the wording of the quest adapted to it) so it includes these cases? Such cases should also be resurveyed more regularly than verifiably vacant shops/restaurants, maybe once a  month?
Or am I the only one who experiences this dilemma?

**Comment by westnordost** [comment]
I generally stopped mapping / updating opening hours since the pandemic and will only continue it after

**Comment by mnalis** [comment]
I still map opening hours of the places I find working (as I find it quite useful); but if the place is not working and does not have notice explaining why it is closed / when it will reopen, I simply ignore opening_hours quest for that place and move on (I do not even hide it, unless I've passed it several times and it was always closed). 

That way I avoid the ambiguity of **why** it is not working at the moment I was passing, while still collecting useful information about places that **are** working.
