### ISSUE TITLE
Add shells as a surface option

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#3021]
**Use case**
When surveying in the Netherlands, I had a need to be able to choose "shells" as a surface option for (foot/cycle) paths.

**Proposed Solution**
Add the "shells" option for surfaces, at least for paths. There are 20 options available now, so there's place for one more without adding another row. Although the geographic scope of use is limited (NL and US east coast), I think it is the most frequent option not offered yet that is not a duplicate of an even more frequent surface. This photo could be used (I have more)
![20210614_09281](https://user-images.githubusercontent.com/69100427/124579553-e3c82d80-de57-11eb-9188-644ac5290676.jpg)

**Comment by westnordost** [comment]
Too rare. You can leave a note.

**Comment by rhhsm** [comment]
I think the question should be what to use the remaining free spot in the 3x7 matrix of surfaces for. It's not rare in NL.

**Comment by westnordost** [comment]
You are welcome to do research on that via taginfo and report the result in the discussion forum.

**Comment by PanderMusubi** [comment]
I think is covers it but the definition should also mention shells perhaps https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal

Another example is https://asfaltwinkel.nl/media/attmgipx/jlousberg_20210223_asfaltwinkel_nl_r1_4244_print.jpg?height=600

Online hard to find pictures of but the Netherlands is full of these asphalt walkways with a shell top layer, hence unsuitable for roller skating e.g.

**Comment by mnalis** [comment]
@PanderMusubi  There are many asphalt surfaces that are unsuitable for roller skating (or even for bicycle driving!). 

- [v39.0-beta1](https://github.com/streetcomplete/StreetComplete/discussions/3626) contains  #1630 which should allow you to map that fact.

**Comment by PanderMusubi** [comment]
Thanks, that is indeed a good additional quest.

**Comment by Derkades** [comment]
In the Netherlands, it is a common surface in natural areas like forests and parks. Please reconsider adding it!

I usually tag it as 'compacted' when it is a fine and firm surface that is easy to cycle on.

In case it is useful, here is another picture, of a finer type compared to the original post:

![shells](https://github.com/user-attachments/assets/67ef149d-82b8-45f9-9179-f3a10fa1e5d2)
(public domain)

**Comment by rhhsm** [comment]
Note that in the Dutch SC translation of "fine gravel" (_Fijn grind, fijn gravel, schelpengrit_), this surface is included. Translated by Peter, 3 years ago. If the Dutch OSM community has consensus that `shells `= `fine_gravel`, we can leave it at that.

**Comment by PanderMusubi** [comment]
In the Netherlands, those shells are also mixed with asphalt. So there are several surfaces:
- loose shells
- compacted on dirt road
- mixed in asphalt top layer

**Comment by mnalis** [comment]
So, I'd say:

- loose shells => `surface=fine_gravel`
- compacted on dirt road => `surface=compacted`
- mixed in asphalt top layer => `surface=asphalt` or [surface=chipseal](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal)[^1] (with perhaps [asphalt:type=*](https://wiki.openstreetmap.org/wiki/Key:asphalt:type), not taggable by regular StreetComplete, but a note may be left)

All of them could/should be more detailed with [smoothness=*](https://wiki.openstreetmap.org/wiki/Key:smoothness) (in "[Surface quality](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#smoothness)" quest, disabled by default)

[^1]:  see https://github.com/streetcomplete/StreetComplete/issues/4265 & https://github.com/Helium314/SCEE/issues/561
