### ISSUE TITLE
Make option to hide a quest accessible more easily

### ISSUE THREAD

**Issue by demsjf8** [streetcomplete/StreetComplete#3023]
**Use case**

Often times, there are multiple quests for objects in close vicinity, especially if the objects make up a bigger one, but the extent of each composing object is small. E.g. paths that are split into smaller path segments over a short stretch of distance, e.g. because the surface type alternates between those short segments. Then, based on the granularity with which those objects can be shown in StreetComplete, it is sometimes difficult to answer a certain type of quest (e.g. regarding surface) correctly, because it is not easy to identify which part of the path the quest actually refers to. That is perfectly ok, as it is to some extent the flip side of the simplicity that the tool offers.
However, while some quests cannot be answered, others pertaining to the same objects might be answerable easily and safely, i.e. without the ambiguity described above. E.g. street lighting usually extends for some distance, so related quests can be answered somewhat safely for smaller objects close to each other, even without knowing exactly which object (of several similar ones in close proximity) the quest relates to. E.g. I recently had a 100m stretch of path that was split into sections of roughly 2m each.
But while the former quests are still active, the latter ones cannot be accessed.
This currently can be addressed by selecting "cannot answer", then "hide" for the former quests. However, this is somewhat cumbersome if it needs to be done frequently.
I.e. in my example, while I knew the entire path was lit, so it was ok to blindly answer that quest, I had to hide 40 or so "what is the surface" quests (because I wasn't really sure which segment was which to be able to safely add surface information) just to be able to answer the "is this lit" quests.

**Proposed Solution**

Add the "hide quest" option directly to the "Other answers" quest menu, or even its own entry besides "other answers" (but the latter might add too many options at that level).

**Comment by smichel17** [comment]
See also: https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-889066

**Comment by demsjf8** [comment]
Sorry, I was not aware of that discussion thread being maintained. As my proposal is already covered in that list, should I close the present issue?

**Comment by smichel17** [comment]
Well, I added this issue to that list before linking to it :grin:. I don't think any of the other issues are a duplicate of this one. My proposal in https://github.com/streetcomplete/StreetComplete/issues/1913#issuecomment-828632563 overlaps with your proposed solution here, but the issue is about a different problem.

**Comment by westnordost** [comment]
If the problem is that a quest that requires some walking around / walkin down a street to solve obscures a quest that could be solved right away, then wouldn't a solution be to change the order in which the quests are displayed to "easy to answer quests right here and now first, quests that need some walkin around last"?

**Comment by demsjf8** [comment]
@westnordost, thanks for the feedback. I think changing the order in which quests are getting displayed as per your thought _ad hoc_ seems to make sense in any case. It doesn't solve my challenge though.
If features are too small and too close to other similar features, and answering a quest requires knowing which feature exactly it relates to (because the otherwise welcome simplifications done by SC make it difficult to sufficiently grasp the details of the underlying structure), that is what I want to avoid without too much effort. Walking up and down the street doesn't help much to understand whether a quest refers to a certain 2m stretch of a path, or the segment right next to it.
Earlier today found the option to change the priorities of quests in the app myself, will give that a try (e.g. put "is this lit" before "what surface").

**Comment by westnordost** [comment]
But then, if the core problem is that it is often not clear to which section of a way a quest refers to,  how would hiding it temporarily solve the issue?

**Comment by demsjf8** [comment]
It does not solve the issue _per se_, you are right. But to me, the underlying issue is maybe also not too important to be solved by StreetComplete. I.e. I would do all the quests in the field that are straight-forward, and then potentially do stuff that isn't with another tool, separately, offline. Thus my proposal was aimed at further stream-lining the "straight-forward" part.
I was looking for a somewhat low-hanging fruit. Trying to get a more thorough solution of the underlying issue into StreetComplete would obviously also be worthwhile. But not sure the benefit/effort ratio would be large enough.
But I am certainly open to it (and if I had the expertise would be happy to contribute). E.g. it might be possible to display a bit more of contextual detail around an object that is subject of a quest. E.g. somehow highlight adjacent path segments (vs. the entire path being naturally rendered). Or adjacent point objects of same type (e.g. benches) if a quest pertains to one of those (so I can infer e.g. in a park with a lot of benches coming in groups which one a particular quest refers to, by seeing its position in relation to the position of other nearby objects of same type).

**Comment by westnordost** [comment]
> .e. I would do all the quests in the field that are straight-forward, and then potentially do stuff that isn't with another tool, separately, offline

Yes, I understand this request and I came to the same conclusion here https://github.com/streetcomplete/StreetComplete/issues/2565#issuecomment-872584909
this is why I am wondering if the use case / issue of yours will not be fixed when this is merged anyway.

**Comment by westnordost** [comment]
> E.g. somehow highlight adjacent path segments (vs. the entire path being naturally rendered). Or adjacent point objects of same type (e.g. benches)

At least the thing with the benches is planned

**Comment by demsjf8** [comment]
Sounds good, thanks.
Should I close this issue then for the time being?

**Comment by westnordost** [comment]
I'd like that

**Comment by demsjf8** [comment]
Ok, thanks for looking into this.

**Comment by peternewman** [comment]
> > E.g. somehow highlight adjacent path segments (vs. the entire path being naturally rendered). Or adjacent point objects of same type (e.g. benches)
> 
> At least the thing with the benches is planned

Are you by any chance talking about #2354 @westnordost ?

**Comment by westnordost** [comment]
Yes

On July 8, 2021 4:48:04 AM GMT+02:00, Peter Newman ***@***.***> wrote:
>> > E.g. somehow highlight adjacent path segments (vs. the entire path
>being naturally rendered). Or adjacent point objects of same type (e.g.
>benches)
>> 
>> At least the thing with the benches is planned
>
>Are you by any chance talking about #2354 @westnordost ?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3023#issuecomment-876078382

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
