### ISSUE TITLE
No decimal separator available for maxheight on some devices

### ISSUE THREAD

**Issue by demsjf8** [streetcomplete/StreetComplete#3024]
On some devices, the virtual keyboard displayed to enter the value for a maxheight quest does not include a point nor a comma. On another device, those, and additional characters, are available as expected.

Not sure whether this has to do with the device type (tablet vs. phone), Android version (Android 7.0 or older vs. Android 8.0 and newer), and/or something else entirely.

See attached screen shots for an example of each case.

![Screenshot_20210706-144027](https://user-images.githubusercontent.com/50327776/124605551-4fb49100-de6c-11eb-8940-5451f3a961a3.png)
![Screenshot_20210706-144740](https://user-images.githubusercontent.com/50327776/124605588-5cd18000-de6c-11eb-8866-455184db5809.png)

**How to Reproduce**

On an affected device (see below), try to add a fractional value in response to a maxheight quest

**Versions affected**

Samsung Galaxy Tab S3 with Android 7.0
StreetComplete v33.0

**Comment by westnordost** [comment]
Does it make a difference if you change the language of your phone to English or German? (comma vs point as decimal operator)

**Comment by westnordost** [comment]
The input field is correctly set to "numberDecimal", which means, a number and a decimal (".") can be entered. If the keyboard doesn't let you, it is a bug in whatever keyboard software you are using, nothing can be done about this in the app.

**Comment by westnordost** [comment]
So I'll close this but you are still welcome to answer the question posed earlier, maybe this helps others.

**Comment by westnordost** [comment]
> Strange thing to me is that I would be the only affected by this topic, given that I am using the Samsung standard keyboard that comes with the official device firmware.

Likely you are not.  Samsung has been known for doing stupid shit in their firmware, so a bug like that is not entirely surprising. I bet you will find tons of posts about it if you search on stackoverflow and similar. 

I faintly remember something about this - maybe this exact issue (maybe with a different form) has been reported already before. As far as I remember, this was limited ot certain Samsung tablets, Samsung phones were not affected.

To be fair, it has gotten much better with more recent Android versions, 7.0 after all is already a bit aged.

**Comment by smichel17** [comment]
+1 on Samsung. Even though SC says dashes are allowed in the house number quest, and even though the Samsung numerical keyboard *shows* the dash symbol, I can't add them without switching to the letter keyboard. Go figure.

**Comment by riQQ** [comment]
You can install another keyboard app. Gboard works correctly on my phone.

**Comment by demsjf8** [comment]
Thanks for all the feedback and suggestions, I'll look into installing a separate keyboard app.
