### ISSUE TITLE
Want to specify "no regular opening hours" on particular weekdays

### ISSUE THREAD

**Issue by jleedev** [streetcomplete/StreetComplete#3025]
**Use case**

It's not uncommon for shops to have a combination of regular opening hours and "by appointment" opening hours.

Such as:

```
Tu-Th 10:00-18:00 open "by appointment only",
Fr 10:00-17:00 open "by appointment only",
Sa 09:00-14:00 open "by appointment only"
```

Or

```
Mo,We-Fr 10:00-16:00;
Tu,Sa "by appointment"
```

StreetComplete has the option for "no regular opening hours" but does not allow associating a particular weekday with this value, so I end up entering these hours by hand later.

**Proposed Solution**

Having selected my weekdays, it should be possible to enter the comment either instead of or in addition to the opening hours.

**Comment by westnordost** [comment]
Yes, it is quite common to see such "with comment" rules on opening hours plates of doctors. But other than the walk-in hours (reserved for emergencies), you'd usually need an appointment anyway. And if you got an appointment, you are not really that interested in the "by appointment" opening hours.

So, I deem the value of specifying opening hours "by appointment" as minor. The rest ("kitchen closes before the bar closes") is really really rare.

Furthermore, and that is more important, it is both really difficult to communicate to the user what this "modifier" is supposed to be and to display and offer this option in the UI without clutter. If it is not crystal clear how this modifier should be used, it will lead to wrong data.

For example, users might write these opening hours 
![48032](https://user-images.githubusercontent.com/4661658/124631414-a8dbef00-de83-11eb-8763-69ccbf9fd92f.jpg)
as
```
Mo-Th 8:30-12:00 "und nach Vereinbarung",
Mo,Tu,Th 15:00-17;30 "und nach Vereinbarung",
Fr 8:30-13:00 "und nach Vereinbarung"
```
which I believe would be wrong, as "and by appointment" refers to the whole days, so
```
Mo-Th 8:30-12:00,
Mo,Tu,Th 15:00-17;30,
Fr 8:30-13:00,
Mo-Fr "nach Vereinbarung"
```
(with comma) would be correct.

There is simply no standard format in which the comment for a particular opening hours line on the opening hours plate should be interpreted. Sometimes just smacking the comment at the end would work, sometimes, like in this example, not.

I can't think of a way how this could be communicated to the user. It starts with how this "comment" or "modifier" should be named. But it doesn't end there, as sometimes the modifier refers to the hours, sometimes to the days, sometimes to all. So as far as the UI is concerned, it would need to be possible to have this option for all three (as you suggest). I see no way to add this to the UI without it being possibly misunderstood or cluttering it.

One thing that would alleviate this issue would be to **just** support "by appointment" (make it a checkbox), but still then
1. we don't know to how many elements this would apply - i.e. is it worth it also in relation to how useful this information is?
2. still no concept how this could be put into the UI. If I didn't convince you that adding this information is not worth it, you are welcome to post some mockups how it could look.

**Comment by westnordost** [comment]
So I'll close this as will not fix.

**Comment by NotSoImportant** [comment]
Suggestion:
- add "by appointment" as another select value in addition to "add time", "add weekday", "new day off" 
    ![Screenshot_20220417-233232](https://user-images.githubusercontent.com/35758921/163733329-ba7fb4d8-9fda-4355-8894-7dd99c201434.png)

- if a day has a time and "by appointment" treat it as "or" (and show this by using a newline with a separate delete button)
- I agree that the "and" case (where you can only make appointments in a certain timerange) might not be that common / helpful

Use the same to parse existing opening hours for re-survey

**Comment by westnordost** [comment]
This might work UX-wise. Though, the "by appointment" string would need to be localized, i.e. written localized into the tag value. Localized with the local language wherever the quest is being solved, not the language the user set on his phone. So, conversely, this option can only be offered where a translation of "by appointment" is available.
Also, for being able to properly parse opening hours with such "by appointment" rules, one would need a whole array of aliases for this that are commonly used. E.g. in German "nur nach Vereinbarung", "nach Vereinbarung", "nur bei vorheriger telefonischer Vereinbarung" etc... many possible fuzzy aliases possible - for each language.
Hence, given these difficulties alone, I do not think that an implementation is worth it. However, if you would like to give it a go, the source is in https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours (the parser is in https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/osm/opening_hours )

**Comment by NotSoImportant** [comment]
Thanks for pointing to the constraints. 

1. For the localized input message the same approach can be used as already implemented for "no regular opening hours": a text input. Ideally prefilled with the last entered value. 
2. For parsing on re-survey I am naively guessing there is no need to parse the string content at all. Just put every text as is there.
For parsing extension or addition the parsing should already existing, (`,` vs `;`), right? 
Examples:
```
Mo "nur nach Vereinbarung" 
Tu 11-16
    "nach Vereinbarung"* (addition: new line) 
Th 11-17 "nur nach Vereinbarung"* (extension: same line) 
Fr-Sa "nur bei vorheriger telefonischer Vereinbarung"*
```

*in case this breaks the layout, show a clickable icon instead

Maybe in addition we should advice people to not use words like "and", "or", "only" inside of the text (at least when used together with a time) 

So it would only be possible to add "TIME or by appointment" (addition = two lines) in SC, but existing "TIME and by appointment" (extension) would be correctly displayed.
