### ISSUE TITLE
Max height quest is asked for private parking entrance

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#3026]
**How to Reproduce**
Navigate to node with

tag | value
-- | --
amenity | parking_entrance
access | private

E.g.: https://www.openstreetmap.org/node/4031909374#map=19/50.10982/8.69998

**Versions affected**
StreetComplete 32.2

I checked the code, and it doesn't check for `access = private` on the nodes. I can send a PR if this is considered a bug.

**Comment by westnordost** [comment]
Hm well, but the parking entrance is usually visible from a public space, isn't it? That's the reason why the app differentiates between private and not at all.

**Comment by riQQ** [comment]
But what value is there in tagging it, if it's only private, i.e. it's only relevant for a really small amount of people?

**Comment by westnordost** [comment]
True, less valuable, but there are also larger parkings that are tagged as private. For example a parking building for some office complex where you need to rent a space or pay a membership fee or something.

**Comment by DerDings** [comment]
Could also be 
`access=private`
`motorcar=yes`
or a similar combination. 

I know some parking entrances like that, which are publically accessible for cars only, but other vehicles (e.g. delivery vehicles, company vehicles of any category) are possible too, just not for everybody.

**Comment by andrewharvey** [comment]
> But what value is there in tagging it, if it's only private, i.e. it's only relevant for a really small amount of people?

It's helpful for those people who use it, eg. delivery drivers, moving trucks, visitors and the residents/office workers.

So I think we should still ask even when marked as private, as it helps create a more complete database.

**Comment by riQQ** [comment]
Okay, looks like it should be kept the way it is.
