### ISSUE TITLE
share profile as text to other apps

### ISSUE THREAD

**Issue by JensKorte** [streetcomplete/StreetComplete#3028]
**Use case**
I want to show my friends what a big street completer I am.

**Proposed Solution**
Share a text string to other apps: My StreetComplete profile: <Name> ★ 123 - Rang in Deutschland: #1234 - Globaler Rang: #1234 - Tage aktiv: 12 - Level aller Erfolge: 12 . https://wiki.openstreetmap.org/wiki/StreetComplete

or at least provide a "copy to clipboard".
With this feature I could show how cool I am and advertise StreetComplete

**Comment by westnordost** [comment]
Better make a screenshot then

**Comment by mnalis** [comment]
Or send a link to your profile at [HowDidYouContribute](https://hdyc.neis-one.org/) if you want to show your overall OpenStreetMap contributions, and not just those made in StreetComplete

**Comment by JensKorte** [comment]
> [HowDidYouContribute](https://hdyc.neis-one.org/) 
Thanks.

**Comment by mnalis** [comment]
Related: if you want your HDYC profile to be available to everyone (and not only to other OSM contributors after they log in; as it currently is due to GDPR), you can enable that by linking it on your OSM profile page as described [here](https://neis-one.org/2017/11/public-profiles-on-hdyc/)
