### ISSUE TITLE
StreetComplete is excluded from adb backup

### ISSUE THREAD

**Issue by gdt** [streetcomplete/StreetComplete#3030]
**Description**

In preparing for a phone migration I did adb backup and unpacked it.  The streetcomplete app was missing.
The FAQ does not say that it being missing from backups is a feature.   (Yes, I realize that the local state is minor.)

**How to Reproduce**

Do adb backup and then use something like Android Backup Extractor https://github.com/nelenkov/android-backup-extractor to unpack the backup.   Look for StreetComplete without success.

**Versions affected**

StreetComplete 33.0

**Comment by westnordost** [comment]
Why should it be included?

**Comment by gdt** [comment]
So that when you back up your phone and restore it, it's there.   That's the point of backup, as I see it.

I see the point that I think you're trying to make that there isn't a lot of state, but there is still the count of completed quests, and more importantly the records of quests the user said they didn't know, and configuration of quest types not to do, etc.

Why do you think the app and the settings should disappear across backup/restore?

**Comment by gdt** [comment]
(This is prompted by a real situation of backup/restore for phone upgrade.)

**Comment by westnordost** [comment]
I don't think the app should disappear. But f.e. the downloaded quest cache, the downloaded tiles etc. Even the quest count and stats is simply resynced after login

**Comment by gdt** [comment]
Sure, the cache stuff should be omitted, as well as things that can be synced.  And it's fine to omit the oauth cookies as a security measure.

I did "adb backup" and then I unpacked it and I see most apps, but things like Signal are missing that explicitly exclude themselves.

I wonder if you just do "adb backup" and unpack if you see StreetComplete there.
I am using an old copy of an extractor that I no longer remember where I got i from, but this might be the normal thing now:
https://github.com/nelenkov/android-backup-extractor

**Comment by gdt** [comment]
Backups are disabled in line 29 of app/src/main/AndroidManifest.xml

**Comment by smichel17** [comment]
It was added in https://github.com/streetcomplete/StreetComplete/commit/611005bd3e4ebd0cffc9e5f117c3920ff13eecdd. The commit message is,

> do not allow backup
> 
> backup has some security implications. Plus, the local data of StreetComplete will almost all the time be above the 25MB limit, so backup does not work most of the time anyway. To backup downloaded quests makes no sense. The only thing that makes sense would be not-uploaded-yet answers, but they should not be stored for a lengthy period anyway plus we wouldn't want these answers to be spread over all of the user's devices (cause then there would be upload conflicts)

**Comment by gdt** [comment]
It's still a bug not to back up the config of which quests the user wants to ignore.   I don't find any config export/import in the app.

**Comment by westnordost** [comment]
I'm not sure if it is possible to specify what exactly will be backed up and what not

On July 8, 2021 2:44:24 PM GMT+02:00, Greg Troxel ***@***.***> wrote:
>It's still a bug not to back up the config of which quests the user
>wants to ignore.   I don't find any config export/import in the app.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3030#issuecomment-876407792

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So what should be backed up: OAuth key, edits (hidden notes, hidden osm quests, osm edits, note edits, ...), key-value store (containing OAuth key and other preferences).

I had a brief look at the documentation again.

25 MB limit remains.

[There is an API](https://developer.android.com/reference/android/app/backup/BackupAgent#onFullBackup(android.app.backup.FullBackupDataOutput)) to declare programmatically what should be backed up and what not. However, it is not fine-grained enough. It is by file, though I got just one database file in which several tables should be backed up, others not. It is possible but takes more effort to split the db into two parts, one part is a "cache", one part is the info that should be backed up.

But in total, I do not consider the effort worth it to implement, so I'll close this.

**Comment by westnordost** [comment]
If it is worth **your** effort, you are free to try to implement this (and open a PR) but I don't think it is.

And anyway, note this: https://developer.android.com/guide/topics/manifest/application-element#allowbackup

> Note: If your app targets Android 11 (API level 30) or higher, you cannot disable device-to-device migration of your app's files. The system automatically allows this functionality.
> You can still disable cloud-based backup and restore of your app's files by setting this attribute to false, even if your app targets Android 11 (API level 30) or higher.

So, the option only affects backup to cloud, it appears.

**Comment by mnalis** [comment]
> It's still a bug not to back up the config of which quests the user wants to ignore. I don't find any config export/import in the app.

Related issue for import/export of config settings is https://github.com/streetcomplete/StreetComplete/issues/273
