### ISSUE TITLE
Option to point StreetComplete on my own instance of OSM

### ISSUE THREAD

**Issue by AvtechScientific** [streetcomplete/StreetComplete#3033]
**Use case**

I run my own instance of the OSM website and would like to be able to edit my private maps with StreetComplete

**Proposed Solution**

Create an option in the settings that will allow to point StreetComplete to other instances rather than OSM.

**Comment by matkoniecz** [comment]
It can be achieved by a (hopefully relatively simple) modification of a source code.

Note that in such case one would also need to ensure that notes, photos, usage statistics are also querying separate services.

Bug reports also likely should be directed elsewhere (question to @westnordost here, I am guessing that some assumptions may not hold true for such service and bug reports would not be valid).

It is not something that normal user needs to do so I see no reason for including it in the standard release.

Though pull requests making it easier (theorethical PR changing config in one place not five would be likely an improvement)

**Comment by westnordost** [comment]
This is open source,  you can build your own modified version for your private map
