### ISSUE TITLE
Use of "weekdays" is not correct in English

### ISSUE THREAD

**Issue by Xcodo** [streetcomplete/StreetComplete#3035]
In several quests (such as the postbox collection times quest) there are dialogues which refer to "weekdays". These are used to refer to all days of the week, but in English the word "weekday" usually refers only to Monday to Friday.

From [Wikipedia](https://en.wikipedia.org/wiki/Workweek_and_weekend):

    A weekday or workday is any day of the working week.

In usual British English at least, the correct word would simply be "days", e.g.
- "Select weekdays" -> "Select days"
- "Add weekdays" -> "Add days"

**How to Reproduce**
On one of the affected quests, click "Add Opening Hours" and the dialog shows as this
![image](https://user-images.githubusercontent.com/6715247/124990483-58f25900-e038-11eb-8d20-473232a2f86b.png)

**Versions affected**
StreetComplete v33.0

**Comment by 10992-osm** [comment]
I agree with this, however, I'd add that you could also say `days of the week` if you wanted to, as well as just `days`.

**Comment by Xcodo** [comment]
Yes, that would also work, but might be too long for smaller screens I guess?

**Comment by westnordost** [comment]
days of the week it is then

**Comment by westnordost** [comment]
Right, I forgot to update strings-en before release, so this is not included in v33.1 but the next version, sorry
