### ISSUE TITLE
[☺bug] SC Asks the number of lanes while it's already tagged 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#3038]
SC asks for the number of lane while lanes:backward and lanes:forward are already tagged. 

**How to Reproduce**

check this [POI](https://www.openstreetmap.org/way/533322284)

**Versions affected**
 v33.0 from playstore

Thanks all for SC & OSM

**Comment by FloEdelmann** [comment]
It seems like we should add `and (!lanes:backward or !lanes:forward)` to the element filter:

https://github.com/streetcomplete/StreetComplete/blob/3ad9222308733f0cb5e5bf24a25c49d89cd3bbc1/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L10-L22

**Comment by andrewharvey** [comment]
You could also argue that both turn:lanes:forward and turn:lanes:backward if tagged properly with none values also imply the number of lanes, though I think it's fine to still set lane counts in this case.

**Comment by westnordost** [comment]
> It seems like we should add and (!lanes:backward or !lanes:forward) to the element filter:

What if only one is set and the other is not?

**Comment by letypequividelespoubelles** [comment]
I can't see a situation where only one is tagged and it's not a mistag. So it should be re surveyed imho.

**Comment by westnordost** [comment]
Yeah nvm, deleted my comment
