### ISSUE TITLE
Automatically add note with picture for opening hours

### ISSUE THREAD

**Issue by svengeboers** [streetcomplete/StreetComplete#3040]
**Use case**
I live in an area where a lot of opening hours from shops are missing, and I would like to be able to automatically start a note (or something similar) where i can include a picture of the opening hours. After that, it is easy to process it later on a computer (which is less tedious than inputting it on a smartphone). If it is a note, it may even be processed by another person (although that might clutter the note layer a bit).
**Proposed Solution**
In the "Add opening hours" quest type, also add a button to make a picture just like when you add a note. The picture can then be automatically attached to a note placed at that location with a generic description (or tag) like "opening hours picture of <insert shop>".

A next step may be to add some OCR software on top of it to automatically get a first draft of the opening hours, which can then be corrected if necessary.

**Comment by mnalis** [comment]
When answering the "opening hours" quest, you can already do `Other answers` / `Can't say` / `OK` to leave a note (with a picture and any text you care to add) at that exact node (so you know exactly what shop/amenity that opening hours are for). 

As for OCR, that was already discussed in issue https://github.com/streetcomplete/StreetComplete/issues/1186

**Comment by matkoniecz** [comment]
Leaving note is already preferable.

In general StreetComplete opening hours interface is at least intended to be nice to use for simple opening hours. I am curious what you are using on PC that is more usable.

Encouraging mass opening notes intended to be processed by others is not a good idea.
