### ISSUE TITLE
Does it have an air pump / compressor ?

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3053]
### General
**Rationale**: especially for bicycle users, flat tires are a problem, and way to inflate tires is needed. Fuel stations especially often offer compressed air pump, but many times its availability is not mapped in OSM. This quests aims to improve that. When tagged on fuel station, this information is also useful for motor vehicles owners.

Affected tag(s) to be modified/added: [compressed_air](https://wiki.openstreetmap.org/wiki/Key:compressed_air) and [service:bicycle:pump](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:pump)
Question asked: **Does ____ have an air pump / compressor ?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
   Located outside for majority of quests. Only sometimes in cases of `shop=bicycle` it might be necessary to enter the shop (if pump is not located outside).
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
The question should be asked on following nodes/areas:
* [amenity=fuel](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel)
* [shop=bicycle](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle)
* [amenity=bicycle_repair_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station)

when they contain neither [compressed_air](https://wiki.openstreetmap.org/wiki/Key:compressed_air) nor [service:bicycle:pump](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:pump) tags.

(additionally, we may want to skip asking the quest if there is [amenity=compressed_air](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air) or (another) [amenity=bicycle_repair_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station) very close by)

**Metadata needed:** 

**Proposed UI:**

The quest should offer three answers:
- not available to public
  sets `service:bicycle:pump=no` and `compressed_air=no`
- air compressor
  sets `compressed_air=yes`
- manual bicycle pump
  sets `service:bicycle:pump=yes`

(If the idea would be accepted, I could try to make a PR for this myself).

**Comment by vehrmann** [comment]
Great idea!
Two initial issues/thoughts:
1) At fuel stations the common compressors mostly work for Schrader (car) valves only.
These compressors work for Dunlop and Sclaverand (old and modern bicycle) valves only with an adapter which is barely available at those places, so you would have to carry one yourself.
2) Compressors at fuel stations mostly supply pressures of up to 5 bar, which is enough for car tires, but not enough for e.g. roadbike tires.

**Comment by matkoniecz** [comment]
Is it already common or accepted to put `compressed_air=yes/no` on all `amenity=fuel` objects?

Is it already common or accepted to put `compressed_air=yes/no` on all `shop=bicycle` objects?

**Comment by vehrmann** [comment]
> Is it already common or accepted to put `compressed_air=yes/no` on all `amenity=fuel` objects?
Not common, but it seems to be used in some areas (e.g. France ([overpass](https://overpass-turbo.eu/s/19o2)))

> Is it already common or accepted to put `compressed_air=yes/no` on all `shop=bicycle` objects?
Seems to be more or less common (e.g. in parts of Munich ([overpass](https://overpass-turbo.eu/s/19o1))

[This](https://www.openstreetmap.org/node/378145690) is a good example how to tag pressure and valve.

**Comment by mnalis** [comment]
> Is it already common or accepted to put `compressed_air=yes/no` on all `amenity=fuel` objects?

If they have that level of detail, it seems so. In [this region](http://overpass-turbo.eu/s/19oZ) of Europe (it barfs out if I try larger regions), it says about `16%` of the `amenity=fuel` have `compressed_air=*` tag. I'm guessing many of fuel stations either are not mapped to such level of detail (which this quest hopes to improve!) or maybe have separately mapped `amenity=compressed_air` nearby; but my _Overpass-fu_ is unfortunately too low to confirm that.

> Is it already common or accepted to put `compressed_air=yes/no` on all `shop=bicycle` objects?

on `shop=bicycle`, `service:bicycle:pump` is much more common that `compressed_air` at about [8% mapped](http://overpass-turbo.eu/s/19p0) 

_(Unfortunately my Overpass-turbo API quota run out while trying to [count](http://overpass-turbo.eu/s/19p6) for `amenity=bicycle_repair_station`, while trying to debug while I'm getting only 2 counts instead of 3; I'll retry later)_

**Comment by westnordost** [comment]
I can't imagine any bicycle repair station that does not have an air pump

**Comment by mnalis** [comment]
@westnordost wrote:
> I can't imagine any bicycle repair station that does not have an air pump

Lucky you. Unfortunately, I can :cry:. In fact, here in Croatia, it is unfortunately quite common situation.

For example, for [city of Zagreb](http://overpass-turbo.eu/s/19pd), overpass shows 5 repair stations, 1 without details, 2 explicitly marked that they do **not have air pump**, and 2 explicitly marked that they do have air pump. (and I'm pretty sure I've marked one more without air pump; but it no longer shows on map; maybe the rest of it has been stolen too)

The story I'm most familiar with goes like this: someone gets hold of EU funds to support sustainable mobility, and they build some bicycle repair stations with solar-powered air compressor (instead of 10x of repair stations with manual pumps for the same money, but oh well). Few months later, someone steals the compressor (interestingly, they do not steal the solar panels). Or sometimes, the battery dies. In any case, it no longer works. But, as the funds for the project are spent, it remains in such sad state for years (or forever, or until rest of it is stolen).

**Comment by vehrmann** [comment]
> I can't imagine any bicycle repair station that does not have an air pump

It would be interesting to distinguish between compressor and pump.
And as there are not too many fuel stations, bike shops and repair stations, the amount of quests would be limited and could therefore be quite detailed
- compressor and/or pump?
- supported valve types
- maximum pressure
- manometer available?

**Comment by westnordost** [comment]
What about fuel stations that **do** have an air compressor (with car valve) but have a sign saying that it is forbidden to use it for the bike? (Not because it is not possible but because ... I don't know, I figure some people are stupid and try to use it on a Dunlop or Sclaverand valve and either wreck their valve or the compressor with that and/or blow up their tyres and the fuel station owners want to be in the clear legally)

**Comment by vehrmann** [comment]
How about `compressed_air:access=customers`
This tag is used for two bicycle shops in Munich. 

`access:compressed_air` is used around Paris several times.

**Comment by mnalis** [comment]
@westnordost had that really happened or is it purely theoretical question?

<details>Because, it just wouldn't work but wouldn't damage the compressor... I guess you could use compressor arm as a level to damage fully extended presta valve if you really wanted, but it wouldn't hurt the compressor arm, so I don't see why the fuel station owners would restrict it because of that. As for the legal cover up, due to pressures involved, you're much more likely to blow up car tires then bicycle ones with too strong compressor, as they typically run on lower nominal pressures - as @vehrmann noted, more realistic problem is that the compressor might too weak to fill up your racing bicycle tire. So I don't see that as a reasonable action for them, either. Still, stranger thing have happened...</details>

Anyway, in such (hypothetical?) case there would be `leave a note` explaining this exceptional situation, and later adding `description` and/or `compressed_air:access` or something.  

The air compressor *is* there for the public use, it is just that the owner placed **some restrictions** on it's use, of which there might be many: opening_hours, season (for example no air/water offered in winter), payment required, free in itself but you're required to purchase something else in order to get access, only available to fully COVID-19 vaccinated, or many other possibilities... 

The very similar issues with random restrictions might be with toilets for example (no access unless you first bought something on fuel stations, or closed in winter for public toilets in parks, or fee etc.), or fancy restaurants (dress code and/or reservation and/or platinum credit card required) etc. I think `leave note` in SC is good enough for such cases, as it seems unrealistic to create additional quests to cover all such  possibilities. 

But additional access quests may be created later if it becomes obvious there is a need for them (lots of notes), sure.

**Comment by mnalis** [comment]
@vehrmann I agree, if this quest gets in and is used, there might be interest for creating followup quests for even more details (valve types, max pressure, etc). 

But not in this one, as per [quest guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete) one should do:
⚛️ Atomic quests: Per quest, only one thing should need to be answered by the user.

**Comment by andrewharvey** [comment]
> What about fuel stations that do have an air compressor (with car valve) but have a sign saying that it is forbidden to use it for the bike? (Not because it is not possible but because ... I don't know, I figure some people are stupid and try to use it on a Dunlop or Sclaverand valve and either wreck their valve or the compressor with that and/or blow up their tyres and the fuel station owners want to be in the clear legally)

All the ones I've encountered are designed for the car, nothing stopping you from using on a bike, but don't expect to set the pressure and it'll all be okay. They are designed to pump a lot of volume quickly and before it has a chance to detect the increase in pressure it'll already have blown your bike tire. So you need to not rely on the auto cut off feature.

But if we are just tagging if an air pump exists or not then we don't need to also try and tag who it's intended for in the same quest.

**Comment by westnordost** [comment]
> @westnordost had that really happened or is it purely theoretical question?

Not theoretical. Very common in Hamburg.

**Comment by westnordost** [comment]
> They are designed to pump a lot of volume quickly and before it has a chance to detect the increase in pressure it'll already have blown your bike tire. So you need to not rely on the auto cut off feature.

There are different models. The digital ones where you set the target air pressure, but also those that just have one button for "add pressure" with an analog display that shows the current pressure.

**Comment by vehrmann** [comment]
Maybe this should not solely be seen as a bicycle quest but as a mobility quest.
As @andrewharvey stated, at fuel stations it would just ask for availability of compressed air, which is already a common tag/amenity at fuel stations. 
The technical details of how to use (or not use at all) fuel station compressors should be left to maps/apps/services using this feature specifically for cyclists.

As an addition, the amenities at fuel stations could be put into quests. E.g. Wiping water, vacuum cleaner and the respective fee, car wash and maximum vehicle height, vending machine for paying 24/7, attached supermarket,...

**Comment by matkoniecz** [comment]
> What about fuel stations that do have an air compressor (with car valve) but have a sign saying that it is forbidden to use it for the bike?

Make separate quest (noncyclist but general) for compressed_air on fuel stations? After all, it may be used also by car drivers.

Have separate answer "cyclists not allowed" (a bit too long and not sure how to tag it - `compressed_air:access=customers` is not suitable as buying food at fuel station shop still does not allow you to pump a bike...)

**Comment by vehrmann** [comment]
How about `compressed_air:access:bicycle=no` for fuel stations which explicitly do not allow cyclists to use the compressor?

**Comment by mnalis** [comment]
@matkoniecz wrote:
> Have separate answer "cyclists not allowed" (a bit too long and not sure how to tag it - `compressed_air:access=customers` is not suitable as buying food at fuel station shop still does not allow you to pump a bike...)

Well, **this** is supposed to be that generic quest, as stated at the top _"Rationale: especially for bicycle users [...] also useful for motor vehicles owners."_. 

If the access is often limited in some countries, than I think it warrants separate "access" quest (limited to such countries?) that would also need to apply to separate `amenity=compressed_air` nodes.  I've started https://github.com/streetcomplete/StreetComplete/discussions/3066 for discussion about access restrictions, as I feel it needs to be separate quest, as it asks for additional access info and not weather `compressed_air` is there or not, so let's take access restrictions discussion there.

**Comment by matkoniecz** [comment]
> How about compressed_air:access:bicycle=no for fuel stations which explicitly do not allow cyclists to use the compressor?

Makes sense to me, but as it is unused for now ( https://taginfo.openstreetmap.org//search?q=compressed_air%3Aaccess%3Abicycle%3Dno ) it should be checked with wider OSM community.

**Comment by matkoniecz** [comment]
I asked on https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dfuel#compressed_air.3Dyes.2Fno

**Comment by matkoniecz** [comment]
> had that really happened or is it purely theoretical question?

And I got umprompted note that forbidding cyclist to use compressor happens in UK.

**Comment by matkoniecz** [comment]
I also asked on tagging right now https://lists.openstreetmap.org/pipermail/tagging/2021-December/thread.html#63273

**Comment by mnalis** [comment]
So, after completing my first easy quest, I think I'd be willing to try my hand on this one.
Any objections / important notes before I start?

**Comment by westnordost** [comment]
Maybe first outline how you intend to address the issues raised in this ticket.

A few additional thoughts:
- wording should maybe add "...a working..." to address the issue you raised that some bicycle repair stations do not have an air pump
- asking for a pump for bicycle (repair) shops may require you to go inside (-> disable quest) while for fuel stations, not. Two quests then? Or maybe only start for fuel stations?
- can someone confirm whether there are any fuel stations that **do not** have an air compressor?
- how to tag the situation if a fuel station has an air compressor but there is a sign that it is forbidden to use for bicycle tyres?
- For bicycle (repair) shops, the answer may differ depending on how nice you ask. For some, it may be similar situation as asking for a tool to quickly borrow. (I know some bicycle shops have a policy to not lend any of their tools). How to handle that?

**Comment by mnalis** [comment]
> Maybe first outline how you intend to address the issues raised in this ticket.

I though I already did, but to summarize:
- about extra details of air_compressor/pump (e.g. supported valve types, max pressures, bicycle compatibility, limited access - to cyclists, seasonal, opening_hours...): **separate quest(s) if notes show that is wanted; adhering to " :atom_symbol: Atomic quests: Per quest, only one thing should need to be answered by the user."**
- is it common enough to warrant a quest? **Yes, it seems to me, overpass links and statistics above**
- can't imagine bicycle repair stations without a pump - **explained that it is (unfortunately) quite common (mostly due to vandalism/theft), at least in this non-quite-west parts of the Europe**
- community consensus on mailing list / talk page - **mixed bag, as always, but no huge red flags against IMHO**. 
  <details>

  Few people would want everyone micromapping as separate amenity (as they indicate they do elsewhere for other subtags; e.g. they dislike sub-tags like `atm=yes` on `amenity=bank` and want separately micro mapped node `amenity=atm` at exact location in polygon of `amenity=bank`) but most to me seemed okay with coarse mapping if micromapping is not available. 
  Most of tagging list discussion then went on tangent to analyze if it is both micromapped and mapped coarsely as tag, should that then be changed by micromapper to `atm=separate` or if creating a separate relation connecting `bank` and `atm`  is preferred; physics of exploding tires when overpressurized; disparging state of OSM tools; problems with relational databases and horrible UI implementations of relation editing in OSM software etc. Business as usual; but I did not feel big community outrage at the idea of continuing to add `compressed_air` tag to fuel stations, which is about as good as one can expect there :smiley: 

  </details>

**Comment by mnalis** [comment]
> A few additional thoughts:
> 
> wording should maybe add "...a working..." to address the issue you raised that some bicycle repair stations do not have an air pump

Absolutely, will do that. I also hope to collect some feedback and help during PR, too

> asking for a pump for bicycle (repair) shops may require you to go inside (-> disable quest) while for fuel stations, not. Two quests then? Or maybe only start for fuel stations?

Ah, I missed that bit... Which of the following whould you prefer (or do you have other suggestion):
  * two multianswer (compressor/manual/no) quests: one for `amenity=fuel` + `amenity=bicycle_repair_station` (which do not require entering the premise, and enabled by default) and one for `shop=bicycle` (which might require entering the premises, so disabled by default)
   *  three separate yes/no quest (with one disabled by default). Might be the cleanest approach, but I am (somewhat) uneasy with such proliferation of quests, as there are many already.
  * only one multianswer quest with all three amenities, disabled by default (I dislike that, as I'd like for quest to be enabled by default)
  
> can someone confirm whether there are any fuel stations that **do not** have an air compressor?

I can; I wouldn't be suggesting this quest in the first place otherwise. In my part of the city, about 1/3 of fuel stations do not have air compressor. On motorway it is much better chance, but then in smaller towns/villages it gets much worse again. 

> how to tag the situation if a fuel station has an air compressor but there is a sign that it is forbidden to use for bicycle tyres?

I would expect users to leave a note, but it you feel that it is going to be common situation, I can add it in other answers (_"it has air compressor, but it is forbidden to use it for bicycles"_ to tag `bicycle=no` on it). But as noted at the top, restrictions on use (as well as other bicycle compatibility details) are probably best left for followup quests (it that turns out to be popular enough).

> For bicycle (repair) shops, the answer may differ depending on how nice you ask. For some, it may be similar situation as asking for a tool to quickly borrow. (I know some bicycle shops have a policy to not lend any of their tools). How to handle that?

I though clarifying by wording, like for access for playground e.g. _"is the air compressor available to general public"_. Because, if what I'd mark  depends on goodwill of other people, I could also mark many  `building=house` here with `drinking_water=yes` :smile:  (in my experience, when running out of water after cycling some 100km from home, in a village without working shop/pub/spring, nicely asking first villager for some water, they were happy to help. But luck and human kindness are usually unmappable in OSM, so I'd prefer only mapping things which are always available to _any_ member of general public)

**Comment by westnordost** [comment]
> two multianswer (compressor/manual/no) quests

Are there really fuel stations with manual air pumps?

> I though clarifying by wording, like for access for playground e.g. "is the air compressor available to general public"

OK, seems to coincide with the wiki definition too. But it has to be made very clear.

So, I prefer:
- one quest that asks for air compressor on fuel stations (no mention of bicycles) - yes/no
- one quest that asks whether a bicycle repair station or bicycle shop has a working air pump - yes/no

>  I am (somewhat) uneasy with such proliferation of quests, as there are many already.

What's the reason? It's not really that much more code.

**Comment by mnalis** [comment]
> OK, seems to coincide with the wiki definition too. But it has to be made very clear.
> 
> So, I prefer:
>     * one quest that asks for air compressor on fuel stations (no mention of bicycles) - yes/no 
>     * one quest that asks whether a bicycle repair station or bicycle shop has a working air pump - yes/no

OK, I'll do it that way. My only regret is that it would make bicycle repair station quest disabled by default too (and it need not be so, as its almost always outside). But I concede that it does make sense to be grouped together. Oh well, people who care would hopefully enable those.

> > I am (somewhat) uneasy with such proliferation of quests, as there are many already.
> 
> What's the reason? It's not really that much more code.

Well, while I'm generally averse to copy/pasting to duplicate code (and prefer instead putting common code in one place), the main reason why I would prefer lower number of quest generally is in consideration for non-basic users (e.g. those who will open setting/quest list and modify it - it already hard for users to wade through that big list, and it's only going to become harder). Also, if there are 3 quests, one would need 3 icons. 

But as you say, 2 quests is probably good enough compromise, so I'm fine with that.

**Comment by westnordost** [comment]
I think there is nothing against it in principle to have the same icon for multiple quests if they ask about the same thing.
Anyway, I meant to say that the other quest doesn't need to be disabled by default if the quest makes it clear that it is about a publicly available air pump (located on the outside of the shop).
