### ISSUE TITLE
Address nodes not on the building outline

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3056]
I suspect this is a tagging issue, but I don't know if SC could do something clever like notice there is a building nearby, or I guess more accurately notice there is a floating address node nearby and offer to migrate it, or just hide the quest?

**How to Reproduce**
Some examples:
https://www.openstreetmap.org/node/431530379
https://www.openstreetmap.org/node/431530373

**Versions affected**
v33.0

**Comment by westnordost** [comment]
I don't see how

**Comment by matkoniecz** [comment]
Especially as nearby address nodes may refer to separate not yet mapped buildings.

Such misplaced addresses are - at least in my opinion - a tagging mistake.

**Comment by peternewman** [comment]
I guess I was imagining perhaps hiding the quest when there's a node with say only address properties (not on a way/area) within X metres of the edge of the building.

> Such misplaced addresses are - at least in my opinion - a tagging mistake.

Yeah you're probably right. This flags the same thing as unaddressed):
https://wiki.openstreetmap.org/wiki/Qa.poole.ch_(QA_tool)

The wiki seems to encourage some things like using a node, but isn't exclusive about it.

**Comment by Cj-Malone** [comment]
Almost related to this, I'd be interested in getting the house number quest to be asked on nodes. e.g. [n8875376844](https://www.openstreetmap.org/node/8875376844) or [n8878398733](https://www.openstreetmap.org/node/8878398733) with a building tag.

**Comment by javiersanp** [comment]
In Spain or Italy, the recommendation for address is to put them not in the area of the building or parcel but in nodes in the outline. Please see this building[building](https://www.openstreetmap.org/way/395543628) and how it has five different addresses in two streets. 

This results in numerous false errors. When users try to fix them, SC put it in the building, resulting in duplicated information. 

Although I know it's difficult to detect this case to exclude them as errors, you can consider to prevent the duplication. When the user fixs the address check for nearby elements with the same data that are not amenities, shops or any other feature by themselves. Give a warning preventing to input a duplicate.

**Comment by matkoniecz** [comment]
> In Spain or Italy, the recommendation for address is to put them not in the area of the building or parcel but in nodes in the outline. Please see this buildingbuilding and how it has five different addresses in two streets.

(1) It would be better as a new issues
(2) Can you link this recommendations?
