### ISSUE TITLE
SC v33.1 not available on Google Play Store yet

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3057]
Hi,

SC seems to have got stuck at v33.0 on Google Play Store. Anything went wrong here (or there)?

The cycling cat

**Comment by westnordost** [comment]
No idea, wrong issue tracker

**Comment by peternewman** [comment]
It's not another instance of #2909 then @westnordost ? Have Google said if it's been approved or not? I'm guessing there isn't a Google issue tracker we as "end users" could follow for it's release, although I appreciate you may be fed up of dealing with their nonsense. I guess we can always install the APK directly...

**Comment by westnordost** [comment]
Hu, sorry

**Comment by westnordost** [comment]
I misread @cyclingcat 's comment, I thought he wrote about F.Droid

**Comment by westnordost** [comment]
Oh jeez, I just forgot to press the "release" button. :-(

There is a two-step process, first you enter all the info, then you click on review, which displays all the info and you need to input some more info, then you click on release. It's published now, usually takes a few hours or so to appear. I am sorry about that!

**Comment by peternewman** [comment]
Great thanks, I know what a pain managing releases on multiple platforms can be. I was a little confused by your initial comment though!

It's now offering the update via Google Play anyway thanks.
