### ISSUE TITLE
Ask ref for fire_hydrant in France

### ISSUE THREAD

**Issue by millecentdix** [streetcomplete/StreetComplete#3059]
Hi,
For attribut emergency=fire_hydrant, we are asked about the fire_hydrant:type, it will be interesting to ask the ref number too.
Thanks for reading :)

**Comment by matkoniecz** [comment]
1) Note that quest suggestion has a helpful template: https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md

It would be the best to either open a new issue while filling it (or even better, copy it to that issue)

---------------

2)

Note that at least in some regions fire hydrants have no numbers obtainable by field survey (for example in Poland).

Where fire hydrants almost always have numbers?

----------------

See #922 - especially

> How is the ref helpful data?
> In which countries do hydrants have refs?
> How to distinguish the ref from other numbers (if any) that may possibly be found on the hydrants? Per-Country-guids necessary?

**Comment by millecentdix** [comment]
Damed ! I haven't found the guideline suggestion template.
In France, most fire hydrants have a number, but not all.
I don't no if there is a regional ref.

**Comment by matkoniecz** [comment]
Looking at https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-5537552160.jpg and https://commons.wikimedia.org/wiki/Category:Fire_hydrants_in_France# in general it seems that many (most? almost all?) fire hydrants in France have a clear `ref` signed.

Still, do you know how this refs are used? For orientation purposes, maybe by firefighters?

**Comment by millecentdix** [comment]
I have find informations in multiple technical guide edited by French firefighters. Hydrants are all referenced, but the reference making can various.
This ref is used to identify the hydrant, completed with address or GNSS location.
https://sdis41.fr/uploads/DECI/RECUEIL%20DES%20FICHES%20TECHNIQUES_V2.pdf page 12
https://www.pyrenees-atlantiques.gouv.fr/content/download/17382/114697/file/RDDECI64%20d%c3%a9finitif.pdf page 45

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/125657130-9c41636d-0e65-46df-b806-fb87e4204f89.png)

So there are two numbers? How will the user be able to differenciate?

**Comment by tiptoptom** [comment]
In Germany and some other countries there is a sing at each underground fire hydrant which shows the diameter, the position in relation to the sign and optional the reference number.
Here two examples:
https://wiki.openstreetmap.org/wiki/File:Hydrantenschild_mit_Legende.svg
https://wiki.openstreetmap.org/wiki/File:Hydrantenschild_Beispielgrafik_2009-01-29.svg

And here we already discussed about additional quests for fire hydrants:
https://github.com/streetcomplete/StreetComplete/issues/362#issuecomment-312503053

**Comment by westnordost** [comment]
Alright, I will close this on the basis that on the hydrant, there will often be several numbers and it is not clear for a non-expert which one is supposed to be the `ref`, not even in the examples shown by the OP.

**Comment by Lee-Carre** [comment]
> In which countries do hydrants have refs?

As far as I know, hydrants in Jersey don't have ref (at least, not one which is apparent during survey).

All hydrants which I've encountered are fire_hydrant:type=underground with only a metal plate covering the (counter-sunk) connector and a nearby yellow ‘H’-plate with some numbers (which definitely aren't unique per hydrant).

If such a quest is ever implemented, then it shouldn't ask for hydrants within Jersey (and probably the other Channel Islands) since it would be impossible to answer.

**Comment by pyrog** [comment]
Hi Tobias,

Could you reopen this issue ?

In France this is simple: on the hydrant, there is only one ref.
Usually a short ref like 30 or 030 : the pillar number 30 of the city.

But yes there is a "full" and unique ref in the firefighter GIS like `P39470.00030` (P mean pillar, 39470 is the city code and 00030 is the hydrant number in the city).

So in this example, the pillar is tagged:
* `ref=030`
* `ref:FR:SDIS39=P39470.00030`

The quest should only ask the `ref`, and `ref:FR:SDIS39` come from imports, firefighter, local OSM experts…

One example on [OSM Hydrant](https://www.osmhydrant.org/beta/#{%22map%22:{%22lat%22:46.67551760094028,%22lon%22:5.555921769555946,%22zoom%22:17.626548544746438,%22rotation%22:0,%22visibleBaseLayer%22:%22osm%22,%22visibleOverlays%22:[%22FireHydrant%22,%22WaterTank%22,%22SuctionPoint%22,%22DryRiserInlet%22],%22markers%22:[{%22key%22:%22search%22,%22lat%22:46.4713146,%22lon%22:6.0635871,%22label%22:%22Chemin%20des%20Tourbières,%20Les%20Rousses,%20Saint-Claude,%20Jura,%20Bourgogne-Franche-Comté,%20France%20métropolitaine,%2039220,%20France%22,%22description%22:{%22road%22:%22Chemin%20des%20Tourbières%22,%22village%22:%22Les%20Rousses%22,%22municipality%22:%22Saint-Claude%22,%22county%22:%22Jura%22,%22state%22:%22Bourgogne-Franche-Comté%22,%22region%22:%22France%20métropolitaine%22,%22postcode%22:%2239220%22,%22country%22:%22France%22,%22country_code%22:%22fr%22}}]},%22activeFeature%22:{%22lat%22:46.674893699999984,%22lon%22:5.5554739,%22id%22:%22node/6187978701%22,%22edit%22:{%22isActive%22:false,%22isPanelVisible%22:false},%22isPopupVisible%22:true},%22setting%22:{%22labelProperty%22:null,%22language%22:%22en%22,%22doClustering%22:true,%22doOgdVienna%22:false,%22doPhotoIntegration%22:true},%22ui%22:{%22sidebar%22:null}}):
<img width="548" alt="Hydrant 2 in Lons-le-Saunier" src="https://user-images.githubusercontent.com/2158081/154421913-4c8ff373-627f-4ab9-8f5e-63dc1fe4d684.png">

**Note:** This app publish pictures in Wikimedia Commons with the template `{{On OSMHydrant}}`.
You could have a look with this [search](https://commons.wikimedia.org/w/index.php?search=On+OSMHydrant&title=Special:MediaSearch&go=Lire&type=image).

Also, Wikimedians use the category [Fire hydrants in France](https://commons.wikimedia.org/wiki/Category:Fire_hydrants_in_France) (and subcategories).
Underground fire hydrant could have a sign, see category [Underground fire hydrants in France](https://commons.wikimedia.org/wiki/Category:Underground_fire_hydrants_in_France).

**Comment by matkoniecz** [comment]
So in France hydrants have either a single number signed or none? And most of them have this number signed?

**Comment by pyrog** [comment]
Yes 😃 

I was a firefighter: usually we must see the reference painted on the pillar (or on a sign) quickly and easily.
The captain to check data of the pillar on a listing.

But mainly, the ref is used to identifying correctly the hydrant to report pressure, flow… measurement, defects.

I have a lot of hydrant pictures in various places in France (not published yet). I could publish some examples

**Comment by matkoniecz** [comment]
then https://github.com/streetcomplete/StreetComplete/issues/3059#issuecomment-880031279 question appears to be resolved, as only one number will be visible

which also resolves https://github.com/streetcomplete/StreetComplete/issues/3059#issuecomment-889408914

So quest limited to France has chance of working well

> In France the color is normalised, that could be a useful quest too.

Is this colour also mattering in any way at all and there is a potential for use of this data?

**Comment by pyrog** [comment]
![20190105_151501](https://user-images.githubusercontent.com/2158081/154444465-8489d849-79ff-4284-a6af-133d54f9160f.jpg)
![20190105_152229](https://user-images.githubusercontent.com/2158081/154444471-ae9ad273-0040-47ab-ad22-b47e348dfbc2.jpg)
![20190512_182217](https://user-images.githubusercontent.com/2158081/154444480-73be13ae-4411-4b27-9349-56cf5fac55ae.jpg)
![20190523_125159](https://user-images.githubusercontent.com/2158081/154444483-b05c67a1-d7ed-4713-a8f3-bd318b235cdd.jpg)
![20190716_163730](https://user-images.githubusercontent.com/2158081/154444491-5ea4f907-88f2-4597-9df7-cb589469c546.jpg)
![20190724_204021](https://user-images.githubusercontent.com/2158081/154444494-b3d9b554-1c42-4ff1-a5d5-a3fe244120d3.jpg)
![20190921_113804](https://user-images.githubusercontent.com/2158081/154444497-21114e61-4141-41aa-b219-f1671a220331.jpg)
![20200521_151744](https://user-images.githubusercontent.com/2158081/154444501-171dea19-abb9-431e-bbaa-3c1d9c498c0a.jpg)
![20210222_1133532675150671929638841](https://user-images.githubusercontent.com/2158081/154444504-686ded34-45fa-4de8-98cd-8ea2ad834b76.jpg)
![20210609_160536](https://user-images.githubusercontent.com/2158081/154444516-2a30ca57-ef12-4ff7-99e4-8cd54b84910d.jpg)
![20210730_111607](https://user-images.githubusercontent.com/2158081/154444520-7fe70403-7b50-4144-b55b-0d640932c055.jpg)
![20210903_155954](https://user-images.githubusercontent.com/2158081/154444522-1e0e40cf-88e5-4505-bd0b-7e528443583e.jpg)
![DSC00640](https://user-images.githubusercontent.com/2158081/154444527-d830b049-fff9-47fc-8549-7aab45d27dc0.jpg)
![DSC07277](https://user-images.githubusercontent.com/2158081/154444529-fefd09a0-66b6-48d1-9567-afd419c8ae2a.jpg)
![DSC07291](https://user-images.githubusercontent.com/2158081/154444531-e3317261-9b4a-4601-99b6-3ce741e73311.jpg)
![DSC07295](https://user-images.githubusercontent.com/2158081/154444532-51568990-cc10-4777-8c55-91ce67490473.jpg)
![DSC08055](https://user-images.githubusercontent.com/2158081/154444535-f24129a9-b9c7-4c55-a9af-7e6f7371f010.jpg)

Here this an exception: a reference was painted, but when the city renumbered hydrants, they don't removed the old ref.
So in this case, SC contributors could type both ref and local expert will clean data.
(Here I guess that the bigger in size is the ref: **226**)
![20210307_104608](https://user-images.githubusercontent.com/2158081/154444512-859885d1-85e5-48f2-bd09-028d44e97877.jpg)

**Comment by matkoniecz** [comment]
https://user-images.githubusercontent.com/2158081/154444531-e3317261-9b4a-4601-99b6-3ce741e73311.jpg

Is mapper supposed to enter `ref=P290.020` here?

It appears to be case where full ref (mentioned in https://github.com/streetcomplete/StreetComplete/issues/3059#issuecomment-1042640399 ) is signed.

**Comment by pyrog** [comment]
>Is mapper supposed to enter ref=P290.020 here?
Yes

Is it an issue ?

**Comment by pyrog** [comment]
I think the **best way to contribute** for fire hydrants (but also for fountains, drinking waters…) is to **take** and publish **pictures**.

OSM Hydrant online app do already that in Wikimedia Commons, so this is not an issue.

When publishing a picture, the template `{{On OSMHydrant|type=node|OSM_ID=7023395269}}` should be added so the picture could be displayed on OSM Hydrant map.
Also categories too:
- `[[Category:Underground fire hydrants]]` for `fire_hydrant:type=underground`
- `[[Category:Pillar fire hydrants]]` for `fire_hydrant:type=pillar`

For other POIs, the standard template is better {{On OSM|type=node|OSM_ID=7023395269}}.
Categories could be added on the quest code or founded on wikidata.

With both templates, the pictures are automatically added to the hidden category [On OSM](https://commons.wikimedia.org/wiki/Category:On_OSM).

**Comment by letypequividelespoubelles** [comment]
@pyrog I think that discussions about publishing pictures in W commons should be in a new issue, this is just a issue about the fire hydrant ref quest.

Moreover, a quest to publish pictures in W commons may bi triggered by many others POI, like guidepost, spring, etc

**Comment by letypequividelespoubelles** [comment]
ping @matkoniecz, so it seems it meets all the criteria to create a new quest ?

**Comment by letypequividelespoubelles** [comment]
@matkoniecz @westnordost Is this quest ok for you ? Or do we miss something ?

**Comment by matkoniecz** [comment]
I see no reason to close this issue and reject it, but I am a bit suspicious about it. I am also not planning to implement it.

**Comment by letypequividelespoubelles** [comment]
If you want an exemple of how usefull it is, firefighters in south of France now create their map based on OSM data, and they're happy when ref of hydrant are in the OSM database (see for ex [this talk in last SotM France](https://peertube.openstreetmap.fr/w/2SZvqwjCWRktC2mxxPCjiF)).

**Comment by matkoniecz** [comment]
I worry more about SC side - how likely is that fire hydrants will have non-ref codes? Multiple codes? Etc.

I expect this data to be useful, I know that similar data is used in Poland.

**Comment by letypequividelespoubelles** [comment]
>how likely is that fire hydrants will have non-ref codes?

I would say around 10% of hydrants I see. Then it'll be tagged ref:signed=no, as for the opening hours quest and others

> Multiple codes?

I map a lot fire hydrant and I have never seen such case. If it happen, it's the responsability of SC user to hide the quest / create a note, but same as for any other quest.

**Comment by matkoniecz** [comment]
@mcliquid Yes!

Note that westnordost added the "new quest" label. It means that this quest is considered as viable and implementing it is welcome. And noone declared that they plan to work on it.

So feel free to implement it!

But I would recommend #4428 as the first priority to avoid having several unfinished things with work sunk into them.

And if I post already then I will link https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md that may be useful but you probably have seen it.

**Comment by crackwitz** [comment]
Germany: those signs/plaques accompany *every* underground hydrant and even some pillar hydrants. The signs' appearance is [standardized across the nation](https://de.wikipedia.org/wiki/Hinweisschilder_zu_Stra%C3%9Feneinbauten#Regionale_und_unternehmensspezifische_Unterschiede). The `ref` on a German hydrant sign is the notably smaller number in the top right corner.

I would welcome this quest being enable-able in Germany, though I think it should stay disabled by default because
- these ref numbers are quite a bit (3x) _smaller_ than the rest of the sign and require getting closer to be readable
- users may need a briefing on the layout of these signs, so they know what they're looking at and what's being asked
  - "(schematic of sign) this is your first hydrant ref quest, look for this number, not the other ones" and allow the user to view that any time they want, right from the quest?

(I Am Not A Firefighter)

**Comment by tiptoptom** [comment]
I think, the best thing would be a template as in the diameter quest.

**Comment by matkoniecz** [comment]
note that it is better to make new issue in such case - posts in old issues are likely to be missed
