### ISSUE TITLE
Add "handlebar holder" to list of bicycle parking options

### ISSUE THREAD

**Issue by efmkoene** [streetcomplete/StreetComplete#3061]
**Use case**
In Switzerland, the "handlebar holder" version of bicycle parking is the most common (https://wiki.openstreetmap.org/wiki/Key:bicycle_parking), but I couldn't find it in StreetComplete (which is so much fun, by the way, thanks!). So I need to leave a comment on the map, each time.

**Proposed Solution**
Unless I'm mistaken and simply didn't see it correctly in the app, adding the "handlebar holder" as on the Wikipedia page to the options for bicycle parking should solve this.

**Comment by matkoniecz** [comment]
https://taginfo.osm.ch/keys/bicycle_parking#values shows 144 handlebar holders across entire Switzerland right now, at 5.09% of tagged values, after `stands` `wall_loops` `shed` `rack`

https://taginfo.openstreetmap.org/keys/bicycle_parking#values shows 214 worldwide, at 0.08% share, at 17th position.

Main work here would be done by translators that could be confused by this quite unusual type.

> In Switzerland, the "handlebar holder" version of bicycle parking is the most common

Maybe it is the most common across not-yet-tagged ones? Or in your area?

**Comment by efmkoene** [comment]
Interesting statistics, more than half of the world's mapped handlebar holders are in Switzerland, then. In my area (Zürich), I'd bet that handlebar holders definitely cover 50%+ of all bicycle parking options. But I remember that in the Netherlands or England, I only rarely saw this type... I leave it up to you to decide what to do, OK? And I'll understand it if it's closed or something, as it's not the most pressing issue on the map.
