### ISSUE TITLE
Thai language translation complete

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#3062]
The community has finished translating StreetComplete into Thai, do we need to do anything to incorporate it into the app?

**Comment by matkoniecz** [comment]
To get Thai translation it should be enough to update StreetComplete to v33 and have Thai as system language on the phone.

See https://github.com/streetcomplete/StreetComplete/discussions/3016

> Added Thai translation by Mishari, PPNplus, Kamthorn and more

Thanks for translating! 


Further translation will be needed as StreetComplete grows and adds new things, in rare cases also existing text is changed. And as one uses translated app it is easier to spot mistakes/inconsistencies. So I hope that translation will continue to be maintained :)
