### ISSUE TITLE
New quest: Add ref and/or addr:flats for entrance=staircase

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#3064]
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref) [entrance=staircase](https://wiki.openstreetmap.org/wiki/Tag:entrance:staircase) 
Question asked: **What is the number of this staircase?**

Staircase numbers are usually listed near the door, so they are easy to find:

<details>
  <summary>Example</summary>

![saint-petersburg-DSCF0509](https://user-images.githubusercontent.com/25708359/125459344-1f53549a-e2db-496a-8345-b9af6b86772b.jpg)

</details>

According to TagInfo's [statistics](https://taginfo.openstreetmap.org/tags/entrance=staircase#combinations), the `ref` has 64% `entrance=staircase`

Case example:
<details>
  <summary>St. Petersburg in Russia: </summary>

https://osm.cupivan.ru/entrance/#452/?z=16&lat=59.94933187585085&lon=30.48688888549805

![Screenshot 2021-07-13 at 16-57-51 Карта подъездов и номера квартир OSM](https://user-images.githubusercontent.com/25708359/125464876-b96963ab-e694-4e64-9edd-d2aa3b8e31e8.png)

</details>

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
`entrance=staircase` owned by `building=apartments`

**Metadata needed:** 

**Proposed UI:**

![SC2](https://user-images.githubusercontent.com/25708359/125461092-fd9607a6-59ad-46f4-ba3b-bcf00a817e5f.png)

**Comment by matkoniecz** [comment]
What would be tagged if it is unsigned or it has no assigned ref?

>  entrance=staircase owned by building=apartments

Probably also `entrance=main` on `building=apartments` outline.

**Comment by westnordost** [comment]
Well I can say that for the apartment building I live in, the entrance does not have `ref`.

**Comment by westnordost** [comment]
And I have never seen that, too. At least I did not notice it.

**Comment by rhhsm** [comment]
I'd welcome this quest: the entrance number (letter) is an important part of most Bulgarian apartment addresses, so you would need it to navigate to within a few metres of someone's apartment. A typical address would for instance be 
Vasil Levski street 45,
entrance A, apartment 21,
1000 Sofia,
where the apartment building at Vasil Levski 45 may be 100 m long, so you'd need to know the entrance letter to know that you should be looking at the first entrance next to no. 43.
The quest could be asked for all entrances of apartment buildings that have more than one entrance node on their perimeter, incl. entrance=yes (but not amenity=parking_entrance). Apartment buildings with a single staircase do not have named entrances. For (rare) cases where an entrance is not a staircase with a letter, this could be an option in the "other answers" list. The quest could also change entrance=yes to entrance=staircase when the user enters a letter/number. For Bulgaria, the value should not be restricted to numbers, as letters in the order of the Cyrillic alphabet are used (А, Б, В, Г, Д, Е, ...).
The quest could be off by default except in countries that use this address system.

**Comment by westnordost** [comment]
Can you also explain about the Russian (and bulgarian?) addressing system?

F.e. this node https://www.openstreetmap.org/node/4799790368#map=19/59.95241/30.47455

Why does the next entrance have a completely different address? In the case of that node, what can actually be seen on the entrancE?

**Comment by rhhsm** [comment]
I'm not familiar with Russian addresses, but there are probably similarities with the Bulgarian one. The whole apartment building has one address with "house number" 32 к1, while each entrance has a number, while for each entrance the apartment numbers are also given.
For apartment buildings in Bulgaria, 2 systems are in use. The most familiar is probably the one where each apartment building has a street and house number (it's actually attached to the parcel of land it stands on, so for a piece of land with 2 houses on it, both houses will have the same house number). If an apartment building has more than one staircase, each of them will have a letter, and apartment numbering starts from scratch for each entrance (so there will be an entrance A, apartment 1 and an entrance Б, apartment 1 in the same building). There's another one where street names are not used, and instead apartment buildings have a building (blok) number and a neighbourhood name (addr:place= is used). We used to live in apartment 82, entrance A, blok 474, Mladost 4, 1715 Sofia, where Mladost 4 is one of 4 neighbourhoods within Mladost quarter (115,000 inhabitants). The second one is tricky to use with SC, as the consensus is that the blok number goes into the house  number field, preceded by бл. which SC doesn't like because it doesn't expect a house number that starts with letters. The neighbourhood name is also tricky to enter (see https://github.com/streetcomplete/StreetComplete/issues/2836#issuecomment-839425667 )

**Comment by andrewharvey** [comment]
I think we should just enable this for regions who opt in and not globally.

**Comment by matkoniecz** [comment]
In Poland it would be typically as follows:

building https://www.openstreetmap.org/way/522102945

entrances with ref https://www.openstreetmap.org/node/8365768620 

But sometimes entrances have no codes and only flat address range is shown (`addr:flats=69-92`)

In really rare cases no sign at all is present or it is damaged.

**Comment by westnordost** [comment]
I see, so the numbers at the entrances are the flat numbers

**Comment by matkoniecz** [comment]
> I see, so the numbers at the entrances are the flat numbers

Not necessarily.

See https://www.openstreetmap.org/node/8365768620 - entrance C, flat range 69-92 (`addr:flats=69-92 `yes=C`).

Right now I am in flat that in staircase II, I also have seen "21 Foobar Street, staircase 3, flat 17" type of addresses.

**Comment by westnordost** [comment]
Okay... then can someone summarize how this quest could be implemented so that it confirms to the quest guidelines?

> 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

How to tag absense of "ref"? And if there is a "ref", what to tag actually? `ref`, `addr:flats`, `addr:unit`, `addr:housenumber`, something else? How is the user going to know if a number shown next to the entrance is a "ref", flat number, unit number etc?

> 💤 Not an overwhelming percentage of quests have the same answer (No spam)

How to avoid huge numbers of false-positives? I.e. entrances that do not have a ref?

**Comment by matkoniecz** [comment]
> How to tag absense of "ref"? 

Not sure ( https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-879141371 ).

`ref:unsigned` ?

> How is the user going to know if a number shown next to the entrance is a "ref", flat number, unit number etc?

In Poland it would be quite clear from context.

flat range is typically quite obvious (first of all it is range, ranges at different entrances form continuous stream - when one staircase has 1-20 range next will have 21-40 and the next 41-something).

In Poland housenumber would typically mention street, while staircase ref not.

**Comment by westnordost** [comment]
@matkoniecz so you suggest that if the user enters a range, it should be tagged with `addr:flats`, otherwise with `ref`?

**Comment by matkoniecz** [comment]
In Poland it would work. No promises about say Russia or Bulgaria.

**Comment by deevroman** [comment]
>How to avoid huge numbers of false-positives? I.e. entrances that do not have a ref?

In Russia, if there are several stairs in a building, they almost always have `ref`.
As suggested above, it makes sense to ask `ref` if there is more than one staircase in the building.

In Russia, the entrance number can easily be found near the front door on signs and distinguished from the apartment numbers.


<details>
  <summary>Example 1</summary>

![ex1](https://user-images.githubusercontent.com/25708359/125689416-50de2aa6-817d-4842-91ac-20d973a8798b.png)
</details>

<details>
  <summary>Example 2</summary>

![ex2](https://user-images.githubusercontent.com/25708359/125689430-1a799f2a-67c0-4af0-be37-3707ba8a57fc.png)
</details>

<details>
  <summary>Example 3</summary>

![ex3](https://user-images.githubusercontent.com/25708359/125689444-a5fa81b8-7d22-4575-93b9-644b77b13e59.png)
</details>

In Russia, you can't have two identical apartment numbers in one building. Therefore, it is not necessary to specify the entryway number to indicate the residential address. But even if the apartment numbers are somehow in order, in large buildings it is not clear which staircase leads to the right apartment. 

<img width="372" alt="Снимок экрана 2021-07-14 в 23 49 26" src="https://user-images.githubusercontent.com/25708359/125691369-768fbbdf-f09e-4261-a079-a204400a3fd6.png">

And apartment numbers can go out of order:

<details>
  <summary>Example 4</summary>

![ex4](https://user-images.githubusercontent.com/25708359/125689454-643a0175-73d0-46e4-bdcb-8f84b71e95d8.png)
</details>


>@matkoniecz so you suggest that if the user enters a range, it should be tagged with addr:flats, otherwise with ref?

For Russia, this is quite different. Perhaps a little confused rendering osm.org, which displays the numbers of apartments in the entrance, but not the number of the entrance.

About add:flats there was already a discussion #1862 Perhaps it is worth to return to it after that

But now we are talking about the tag `ref`, which is much easier to fill

**Comment by westnordost** [comment]
I would have thought that `addr:unit` would be the right way to "ref" an entrance. But anyway. To summarize:

In russia, both ref and flats are always shown on every entrance
In Poland, sometimes ref and sometimes flats are shown on every entrance

Correct?

**Comment by andrewharvey** [comment]
> I would have thought that addr:unit would be the right way to "ref" an entrance. But anyway. To summarize:

No `addr:unit` would be the individual unit number, it sounds like this ref is the entrance number/letter which may led to several units.

I reckon `addr:flats` should be a different quest because they are independent, you could have just ref, or just addr:flats or both.

**Comment by Helium314** [comment]
In Austria it's a bit similar. There are entrances for different staircases (part of the official address as _Stiege_), but `addr:unit` is used instead of ref for the entrance. It feels like the Russian/Polish way of tagging might be somewhat more correct, but in my understanding it's almost the same (with `addr:unit` being less specific).

**Comment by andrewharvey** [comment]
>  but addr:unit is used instead of ref for the entrance.

According to the wiki "The number, letter, or name of a single unit or flat that exists within a larger complex." so `addr:unit` should only be used on the entrance if the entrance leads to a single unit, otherwise it should be `addr:flats` for the unit numbers accessible via the entrance.

`ref` should be used when it's some other number/letter not related to the unit/flat numbers themselves.

**Comment by matkoniecz** [comment]
>  In Poland, sometimes ref and sometimes flats are shown on every entrance

Yes, and almost always at least one of that is shown for `building=apartments` with multiple `entrance=staircase`/`entrance=main`

**Comment by westnordost** [comment]
Ok then let's consider we add this quest for Russia + a few selected regions first. Have a quest for `ref` or for `addr:flats` first? What can be surveyed more easily and which is the more important information?
Would there be any more issues?

**Comment by matkoniecz** [comment]
> Have a quest for ref or for addr:flats first? What can be surveyed more easily and which is the more important information?

I would say that in Poland ease of collecting and importance is very similar.

And quest would have minimal differences. I would even consider filling both in a single quest.

**Comment by trolleway** [comment]
I wait for easy survey tool for addr:flats and entrance ref for many years, it ideal usecase for StreetComplete in any ex-ussr city. 

> Ok then let's consider we add this quest for Russia + a few selected regions first. Have a quest for `ref` or for `addr:flats` first? What can be surveyed more easily and which is the more important information?
In real life, for delivery, or for emergency call, in Russia both number in use: street - housenumber - entrance - flat, so we need both quests at same time. 
If one quest should be implemented first, addr:flats is more useful. Geomarketing studies using count of flats in building to estimate population for city blocks for optimal shops and city transport planing. Now we use proprietary reformagkh.ru dataset.

![image](https://user-images.githubusercontent.com/4630662/126220084-b8c2b478-a852-4fb9-8d19-4fe56da3c7e9.png)

**Comment by deevroman** [comment]
Let me add. You will almost always find both `ref` and `addr:flats`. Seeing `ref` is usually easier because it is often written larger so you can see it from a distance.  And the answer to the question will be a number or a letter. 


The numbers in `addr:flats` are sometimes (usually found in older houses with complicated shapes) not in order ([Example 4](https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-880231076)), so you have to think a bit about the interface of the quest. Also note that OSM has no way to tell which floors are which apartments. That is, we must give the user to enter, for example, `addr:flats=3-7;10;14;16-18`, but so that he did not start doing useless work entering the apartments, which are in series `addr:flats=1-10;11-20;21-29;30-39....`. 


So it seems to me better to separate these quests. 

Both quests are useful. But if you decide in what order to ask, first ask `ref` (faster to answer), and the next quest `addr:flats`

**Comment by rhhsm** [comment]
For Bulgaria, the ref quest should have priority, as the addr:flats one is not useful (flat numbering starts again for each entrance, so you definitely need the entrance ref to find the right apartment, and it's only of statistical interest to know which other flat numbers exist behind each entrance door).
The quest should be asked for each building=apartment that has more than one entrance=yes or entrance=staircase node on its perimeter. The quest question could be "What reference does this entrance have?", where "reference" can be translated to what is appropriate for each country ("number" for Russia, "letter" for Bulgaria).
I'm wondering if SC should also change an entrance=yes tag to entrance=staircase in case the quest is answered? Most apartment buildings here that have entrances tagged, seem to have entrance=yes that should be entrance=staircase

**Comment by andrewharvey** [comment]
> I'm wondering if SC should also change an entrance=yes tag to entrance=staircase in case the quest is answered? Most apartment buildings here that have entrances tagged, seem to have entrance=yes that should be entrance=staircase

I think that should only be done if the user is asked is this entrance a staircase, would would need to be another quest. Though I'm not sure how that would work when you answer "no it's not a staircase it just a regular entrance" because entrance=yes was correct. Otherwise if it's just an entrance to a lobby area then it would be bad to blindly tag that as staircase.

**Comment by matkoniecz** [comment]
>  I'm wondering if SC should also change an entrance=yes tag to entrance=staircase in case the quest is answered? Most apartment buildings here that have entrances tagged, seem to have entrance=yes that should be entrance=staircase

It should not be asked for `entrance=yes`

**Comment by rhhsm** [comment]
> It should not be asked for `entrance=yes`

I think that for an apartment building that has two or more entrance nodes on its perimeter that are tagged as entrance=yes, these entrances are very likely to be staircase entrances. There are many such cases in my area, and it would be a pity not to include them in the quest. If they happen to be other kinds of entrances, that should lead to choosing the "other answers" option and probably lead to creating a note. Alternatively, a "What kind of entrance is this?" quest could be created.

**Comment by andrewharvey** [comment]
> Alternatively, a "What kind of entrance is this?" quest could be created.

#2706

**Comment by matkoniecz** [comment]
> Element selection:
> entrance=staircase owned by building=apartments

I think that more complex query is needed - `entrance=staircase|main` within `building=apartments|residential` line that has at least 2 `entrance=staircase|main`

Why? There are apartment towers with exactly one entrance, asking there would be pointless.

See https://www.openstreetmap.org/way/233374385

![screen10](https://user-images.githubusercontent.com/899988/140427475-d6745e29-30cb-41fe-96fe-143281a68327.png)

**Comment by deevroman** [comment]
> There are apartment towers with exactly one entrance, asking there would be pointless.

`ref` really doesn't need to ask. However, asking `addr:flats` is not so pointless.

**Comment by matkoniecz** [comment]
> However, asking `addr:flats` is not so pointless.

Why? 

Range will be typically not shown.

It does not matter for navigation, as everyone gets through the same entrance.

**Comment by deevroman** [comment]
> Range will be typically not shown.

osm.org renders `addr:flats`

>It does not matter for navigation, as everyone gets through the same entrance.

Indeed, `addr:flats` does not help in navigating for apartment towers. But `addr:flats` gives information about the building's population. Which, as @trolleway said, is useful for researchers.

**Comment by matkoniecz** [comment]
> Range will be typically not shown.

I meant that it is often not shown on door / sign and not feasible to survey.

**Comment by deevroman** [comment]
> it is often not shown on door / sign and not feasible to survey.

In multistory buildings, you need to know the floor you need to go up, so there are still signs near the entrance to buildings with one entrance. The only thing is that sometimes these signs are located near the elevators, i.e. you have to enter the building, which is often impossible.

**Comment by HolgerJeromin** [comment]
I know an appartement building with two entrances (each for about 10 appartements) and no numbers for visitors, only names on the bell buttons. 
If you visit someone you have to search for the name and if you are unlucky you have to walk to the other entrance. 

https://www.openstreetmap.org/node/976655730

**Comment by deevroman** [comment]
As stated somewhere earlier, this quest is not offered for all countries.
For example, in Russia they do not write the names of the owners on the public sign, so apartment numbers are used. [Read more](https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-880231076)

**Comment by matkoniecz** [comment]
I opened https://community.openstreetmap.org/t/marking-that-entrance-staircase-main-has-no-sign-with-code-in-area-where-it-is-to-be-expected/910 to confirm `ref:signed=no`

In which countries it would make sense? Russia, Bulgaria, Poland so far.

---------------

In some other countries it may make sense to ask about `addr:flats` (though that would need `addr:flats:signed=no` ....)

**Comment by deevroman** [comment]
> In which countries it would make sense?

`ref` + `addr:flats` is similarly used in Belarus and Ukraine.

Similar addressing is apparently in the Baltic countries: ref does not seem to be used, but `addr:flats` is used. But it's worth clarifying

**Comment by matkoniecz** [comment]
`addr:flats` is more commons - but for example in USA reportedly `ref` assigned to staircases is not a thing.

**Comment by deevroman** [comment]
`entrance=staircase` a more accurate tag in the proposed countries:
_The door to the entrance/front /stairs in an apartment building_ (auto translated)
https://wiki.openstreetmap.org/wiki/RU:Key:entrance

But in other countries it's just a staircase:
_Door to staircase_
https://wiki.openstreetmap.org/wiki/Key:entrance


And this difference makes it possible to distinguish a non-residential staircase from the one that leads to apartments and which therefore will have `ref` `addr:flats`

**Comment by matkoniecz** [comment]
>  Question asked: What is the number of this staircase?

I propose more generic

> What is the code of this entrance?

**Comment by matkoniecz** [comment]
An icon is definitely missing (@westnordost - are you interested in making one?)

-------------------------------------

I also need to redo interface: I based it on housenumber quest one, but ironically I need to add back functionality that I removed.

Right now it asks about entrance code and flat range, and allows to send question after filling either or both.

It likely should instead ask first what is known:

- entrance code
- flat range
- both entrance code and flat range
- neither

and then proceed to showing matching interface

current one (yes, the frankestein question is bad, likely I will go with "How this entrance is signed?")

![screen04](https://user-images.githubusercontent.com/899988/165337149-2e6bb965-42da-429e-9fb8-470e5d32d6d5.png)


-------------------------------------

I suspect that in Belarus, Ukraine, Lithuania, Estonia, Slovakia, Czech Republic would be eligible. Maybe also some other countries, but this are most likely and makes sense to ask their communities first.

If anyone wants to help: feel free to contact them and leave here a link.

https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-880360125 suggests Austria but I am not sure.

**Comment by deevroman** [comment]
Do not forget that there may be several ranges of apartments. you need something like a + button.

**Comment by Zverik** [comment]
![pochemu-v-sankt-peterburge-takaya-strannaya-i-neponyatnaya-numeratsiya-kvartir1](https://user-images.githubusercontent.com/766031/165344099-de39fe82-feb8-4cc5-a825-6dfe7a5e175d.jpg)

**Comment by Helium314** [comment]
> [#3064 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-880360125) suggests Austria but I am not sure.

* in Austria `ref` is almost never used for such entrances, usually `addr:unit` is, so this would make tagging and probably element selection depend on country
* sometimes `addr:unit` is tagged on a node inside building (needs to be excluded)
* sometimes entrances are inside the building area instead of on the outline (e.g. in a building passage)
* there is only `addr:unit`, no `addr:flats`

So: also not sure if Austria should be included...

**Comment by matkoniecz** [comment]
@Zverik @deevroman Is it rare annoying case (and leaving note with photo would be OK)? Or a standard situation?

In Poland about 99.8% or more would be a single range, so "leave note for weird cases" would be acceptable. But maybe it is not going to work everywhere.

**Comment by Zverik** [comment]
This is an exception, common to Saint-Petersburg older houses. Of course most of the ranges are simple `A-B`. I'm not a StreetComplete user, but I dislike strict forms. So I posted the image to remind you of non-trivial cases. I agree that a note might work in such cases.

**Comment by deevroman** [comment]
> Is it rare annoying case (and leaving note with photo would be OK)? Or a standard situation?

Multiple intervals have 1-5%

<details>
<summary>With multiple intervals</summary>

<img width="1432" alt="Снимок экрана 2022-04-26 в 21 30 29" src="https://user-images.githubusercontent.com/25708359/165368058-b1d579dc-3911-4d93-a52c-9814946fa980.png">

<img width="1427" alt="Снимок экрана 2022-04-26 в 21 28 39" src="https://user-images.githubusercontent.com/25708359/165370002-7150fac2-a7cb-431e-9f55-28ff510265e9.png">

</details>

<details>
<summary>All</summary>

<img width="1426" alt="Снимок экрана 2022-04-26 в 21 30 16" src="https://user-images.githubusercontent.com/25708359/165368086-f0a497c5-3d90-4ddc-bc61-52bcb588e1fc.png">

<img width="1431" alt="Снимок экрана 2022-04-26 в 21 29 01" src="https://user-images.githubusercontent.com/25708359/165370023-d4ce7e57-71e3-436c-9007-facfa6836e2d.png">

</details>

And among them there are often intervals from one flat (usually on the ground floor)

**Comment by rhhsm** [comment]
> I also need to redo interface: I based it on housenumber quest one, but ironically I need to add back functionality that I removed.
> 
> Right now it asks about entrance code and flat range, and allows to send question after filling either or both.
> 
> It likely should instead ask first what is known:
> 
>     * entrance code
> 
>     * flat range
> 
>     * both entrance code and flat range
> 
>     * neither
> 
> 
> and then proceed to showing matching interface
> 
> I suspect that in Belarus, Ukraine, Lithuania, Estonia, Slovakia, Czech Republic would be eligible. Maybe also some other countries, but this are most likely and makes sense to ask their communities first.
> 
Bulgaria would be eligible. Here the entrance reference is always a letter, and apartments are numbered from 1 for each entrance (so in the same apartment block, there is likely to be a flat "entr. A ap. 1" and another flat "entr. Б ap. 1"; knowing just the flat number is not enough to be sure to find it).
I don't like to call the entrance reference "code" as it might be confused with the passcode to open the entrance access door. Maybe call it "character" or "symbol"? For Bulgaria this could be translated as "буква".
For Bulgaria it would make sense to only ask for the entrance letter; the flat range is not very interesting to map (knowing the total number of flats in each entrance is not useful to know when looking for an address).

**Comment by nagisa** [comment]
It is not a cultural norm nor a building code to maintain the little sign above the entryway specifying flat ranges in Lithuania. If you find any, these signs will be above entryways to apartment complexes built during the period of Soviet occupation. Even then, nobody will bother replacing them if, perchance, the sign has fallen off or the entryway door has been replaced at some point. Given a couple more decades this kind of signage will be endangered species.

As an exercise in proving my own intuition, I went through a block of buildings built during 1970~1980s and surveyed their entryways. Most of the buildings in the surveyed area have multiple entrances. I found 4 signed entryways, 1 entryway with a missing sign (the sign has fallen off/been removed) and 9 entryways with a door which does not contain Soviet Sweat in its list of ingredients. Out of those 9, none had a sign.

As thus I would argue that this quest makes little sense in Lithuania.

**Comment by matkoniecz** [comment]
> As thus I would argue that this quest makes little sense in Lithuania.

Thanks for feedback! Then it will be disabled there. For comparison this type of signage is maintained in Poland and it is present on new apartments. See say https://commons.wikimedia.org/wiki/File:Signed_entrance_in_a_residential_apartment_building.jpg for photo of such plaque in recently constructed building.

**Comment by Dimitar5555** [comment]
> If it is eligible elsewhere, hopeflly people will mention it after it is released.

Hungary, North Macedonia and Slovenia seem to also have a scheme for panel buildings' entrances.

**Comment by matkoniecz** [comment]
@mnalis Is such quest applicable in Croatia or not?

**Comment by matkoniecz** [comment]
@Dimitar5555 Any idea how North Macedonia community can be contacted?

**Comment by Dimitar5555** [comment]
> @Dimitar5555 Any idea how North Macedonia community can be contacted?

Unfortunately no. The last post on their forum from a Macedonian person is from 2017. You can try there but I doubt that there will be any responses.

**Comment by mnalis** [comment]
> @mnalis Is such quest applicable in Croatia or not?

No, I don't think so. At least I've never seen it. 

<details>

Addressing scheme at least is kept simple here: if there are multiple unconnected entrances to the apartment building, each gets it's own housenumber (usually e.g. `17a`, `17b`, `17c`...). They do get creative with numbering schemes (so you can't always count on numbers increasing in one direction, although usually they do), but still you only need `street name` and `house number` to find the correct entrance.

</details>

**Comment by Zverik** [comment]
So a friend from North Macedonia told me that apartment buildings there usually have numbers (`ref`) on entrances, but no apartment numbers.

**Comment by matkoniecz** [comment]
I think that it would be fine to add it, the first step will have two extra options that will be very rarely used but it should be fine...

**Comment by 05storm26** [comment]
I am not sure what this quest is about and what this quest will do but this is how it is in hungary:

In hungary the "panel" (= russian style prefabricated concreate buildings) have usually more than 1 entrance and then two starcases separatly behind each entrance. On each entrance flats reachable have numbers from 1-30 for example.

The entries/starcases have letters as designators, e.g.: a, b, c, d. 

Addresses of flats look like this: <streetname> <housenumber> / <starcase designator> <flatnumber>

E.g.: in a building like this on Example street, which has house number 4. You could have two flats inside of the building numbered e.g.: 5.

One is Example street 4/A 5
The other is Example street 4/B 5.

So the starcase designator is neccessary for the proper address. The actual "door number" for the flat is reused on the next staircase, in the same building.

Right now as far as I can in hungary I see people not tagging these buildings / building's entrances with multiple addresses (maybe because people here don't know how to tag these?). Usually on Openstreetmap on these building only the housenumber is given and you cannot see from the address on openstreetmap that there are two different starcases/entrances e.g.: 4/A and 4/B. I am not even sure myself how to properly tag such addresses on a single building.

Regarding other apartment types (non panel buildings) like newly build apartments with multiple entrences and staircases under the same housenumber the situation is the same, mostly only the housenumber is tagged on the building and the other parts/information about the addresses is not on the map.

**Comment by matkoniecz** [comment]
@05storm26 

See https://github.com/streetcomplete/StreetComplete/pull/4066#issuecomment-1145974286 for how tagging works and which tags are used (`ref` for staircase designator, `addr:flats` for flat range, `ref:signed=no` if nothing is signed)

**Comment by 05storm26** [comment]
@matkoniecz Whould this quest show for buildings where the starcases/entries are not already mapped? Only the housenumber? For example like this:

![Screenshot from 2022-06-20 12-04-53](https://user-images.githubusercontent.com/8590289/174578644-cd79265a-4bf4-430a-8d5c-fba80da8c671.png)


Would the quest show for the houses which are tagged: 92, 90, 88, 86? Or because they don't have their starcases/entries mapped already this quest wouldn't show?

**Comment by matkoniecz** [comment]
> Would the quest show for the houses which are tagged: 92, 90, 88, 86?

No, as entrances are not mapped. Entrance quest would also not appear as footways are not reaching buildings.

**Comment by matkoniecz** [comment]
> For buildings which are not connected to footways but there is a very close footway as in the picture can you have a separate "where are the entrences of this building?" quest? 

That is quite tricky to implement and may take horrendous effort. Right now I do not have even idea how to implement it, but I put it onto pile of ideas
