### ISSUE TITLE
Do not ask Vegetarian Quest for POI with diet:vegan=only

### ISSUE THREAD

**Issue by starsep** [streetcomplete/StreetComplete#3072]
**Use case**
Right now even if a POI has diet:vegan=only Vegetarian Quest is asked.
According to https://wiki.openstreetmap.org/wiki/Key:diet:vegan diet:vegan=only implies diet:vegetarian=only (makes sense).
Example of POI where Quest is asked: https://www.openstreetmap.org/node/8359986392
Example of POI where I responded: https://www.openstreetmap.org/changeset/104325841

**Proposed Solution**
I would like to replace https://github.com/streetcomplete/StreetComplete/blob/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1/app/src/main/java/de/westnordost/streetcomplete/quests/diet_type/AddVegetarian.kt#L13 to `(!diet:vegetarian and diet:vegan != only)`

I haven't checked whether the syntax is correct and whether it works yet.
I am happy to make PR if it makes sense

**Comment by westnordost** [comment]
A PR is welcome, however if `diet:vegan = only`, we'd want to not ask at all, also not after 2 years.
