### ISSUE TITLE
Ask whether waste disposal is public

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3074]
### General
Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access)
Question asked: **Is this garbage dumpster accessible to a general public?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam) - I expect that large majority will be "private", but density should not be overwhelming
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) 6700 just in Poland

### Ideas for implementation

**Element selection:** amenity=waste_disposal and !access

**Metadata needed:** No

**Proposed UI:** Boolean yes/no may be sufficient

### Extra

http://overpass-turbo.eu/s/19we

Almost certainly nearly all of them are actually access=private, but sometimes - for example on cemeteries - access is actually public. So armchair editing is not fully viable.

![screen01](https://user-images.githubusercontent.com/899988/126061714-8e903342-04b2-43ba-b11d-78be109abf05.png)

![aa](https://wiki.openstreetmap.org/w/images/6/6b/Waste_container.jpg) - in Poland typically placed inside `building=garbage_shed`

**Comment by mnalis** [comment]
In Croatia, those `amenity=waste_disposal` **which are mapped on OSM** are in vast majority the ones displayed in picture above, and intended for `building=apartments` which are near them. But it more as a convenience then an restriction (eg. nobody really would think anything if the container in front of your apartment was full so you walk few dozen meters to another closest container "belonging" to nearby flat).

Those are in roughly two categories:
- Some of `amenity=waste_disposal` are standalone without a shed (like in the picture above), and those are in vast majority of cases `access=yes` as explained above (some are near buildings that just never had a garbage_shed, but also graveyards and other amenities, etc.)
- Some are in `building=garbage_shed`, which might also be `access=yes` or `access=permissive` (it is **not really well regulated, so impossible to answer to casual mapper**) although some (very rare) might have locks on them which would identify them as `access=private`. 

In addition to those big metal containers, there are also a lot of:
-  smaller (and from black plastic, not metal) containers intended for `building=detached` private standalone houses, which would always be `access=private` in case that **they were mapped** in OSM (which they almost **never are** - as it would be quite useless data, pertaining only to the private house owner, who is quite likely aware (s)he has such trash container :smile:). They might also (as often as not) be situated inside the private backyard, and only pushed on street on days it is scheduled to be picked up.

**Comment by matkoniecz** [comment]
> nobody really would think anything if the container in front of your apartment was full so you walk few dozen meters to another closest container "belonging" to nearby flat

The same in Poland, often there is no strict assignment - but using far away one (say driving by car and leaving bags of trash) would not be allowed.

**Comment by mnalis** [comment]
> The same in Poland, often there is no strict assignment - but using far away one (say driving by car and leaving bags of trash) would not be allowed.

_"Would not be allowed **by whom**?"_ - ie. is using far one **actually illegal** _or_ are the residents there "just" **angry/suspicious**? (I do not actually know the answer in this case, even for my own country - do you know for Poland, @matkoniecz?)

Wiki for [key:access](https://wiki.openstreetmap.org/wiki/Key:access) says 
> "Access values describe **legal permissions/restrictions** and should follow ground truth e.g. signage or legal ruling and not introduce guesswork. It **does not describe common or typical use**, even if signage is generally ignored. "

So to correctly map, one would have to have knowledge if:
- even **using a nearby container is actually illegal, but is everyday occurrence and nobody ever complains** (in which case, according to above wiki, it is still `access=private` - in which case one might be **_almost_** tempted to propose `access:defacto=*` tag)
- using **nearby container is legal, but using far one is not -- and there is a law** detailing exactly what "near" and "far" mean (in which case it could only be correctly marked via some convoluted extension of [conditional restrictions](https://wiki.openstreetmap.org/wiki/Conditional_restrictions), and needs per-country research)
- **using any container (near of far) is legal, but** uneducated (in law) residents would **likely get angry** (in which case it is `access=yes` and `hazard=residents` :smile: )
- or, one could try asking local residents if it is ok to drop your trash there, and mark as `access=permissive` only if they say "yes" (and "can't say" if there is no one of locals to ask)

Any ideas how it could be improved? (so far it seems to break at least some of `Easy answer`, `Users are no experts` and `no false-positives` [SC tenets](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete), at least in Croatia)

**Comment by matkoniecz** [comment]
As far as I know - actually illegal (though very hard to prosecute like similar case of a dumping trash in a forest).

But I am not a lawyer.

**Comment by mnalis** [comment]
If all 99% of them are near residential buildings and are actually `access=private` (in Poland; for this "big" kind I'd tend to mark them as `access=permissive` in Croatia if I were to map accessibility of them - unless I actually found the law that forbids it), could we filter quest to make it less spammy?

Eg. only ask for `access` if `amenity=waste_disposal` is inside (or close to?) `landuse=cemetery` or `amenity=grave_yard` (and maybe some other amenity?) 

Or better yet, reverse logic: ask for `access` on `amenity=waste_disposal` only if there is no `building=residential|apartments|detached|house|...` in radius of xxx meters of it? (I do not know how expensive those queries are, but it should not be a problem if judging by Poland or Croatia examples - one mapper would not be likely to encounter more than dozen or two of such quests during an hour walk)

**Comment by westnordost** [comment]
If those bins are used anyway by neighbours or passerbys (even though it is "officially" illegal), why do you think it makes sense to ask if they are private or not? Or for that matter, map them at all? I figure that every house has waste disposals. Shall we add the waste disposals for every apartment house to the map and add `access=private`? That doesn't really make sense to me.

**Comment by matkoniecz** [comment]
> Or for that matter, map them at all?

Not a fan of that - see also https://github.com/gravitystorm/openstreetmap-carto/issues/419 ("
Add rendering for amenity=waste_disposal")

> Shall we add the waste disposals for every apartment house to the map

That seems rather pointless to me. But people added them, without marking them as private.

So I want to detect the problematic ones and mark them as private and though that it could be a general SC quest.

> If those bins are used anyway by neighbours or passerbys (even though it is "officially" illegal), why do you think it makes sense to ask if they are private or not?

In Poland they will be either outright locked or with posted signs such as "private" or "only for residents of XYZ address" or "only for NAME OF RESIDENTIAL AREA".

Rare ones (typically in front of cementery) will be actually for a public use.

**Comment by westnordost** [comment]
In Hamburg, 100% or near 100% of garbage disposals will be private, associated with an apartment building. Usually locked.

I guess maybe technically, garbage bins that are underground are large enough to be in reality `amenity=waste_disposal` but I think as they appear like normal bins, they'll usually be mapped as bins: https://de.wikipedia.org/wiki/Unterflurbeh%C3%A4lter

**Comment by matkoniecz** [comment]
I guess that it goes on "in my private fork only" pile.

(feel free to reopen if I closed too soon)
