### ISSUE TITLE
Ask for plug type on charging_station.

### ISSUE THREAD

**Issue by Eric-Sparks** [streetcomplete/StreetComplete#3075]
**Use case**

Electric vehicles use different types of plugs for charging. If a particular charging station doesn't support a particular socket then the user can't use that station. Users should be able to search for charging stations with plugs that work with their vehicle.

**Proposed Solution**

Using the [socket tag](https://wiki.openstreetmap.org/wiki/Key:socket) , one can specify what is supported by the particular charging station.

In the U.S. the most common ones are:
* type1
* type1_combo
* chademo
* tesla_standard
* tesla_supercharger

Maybe show a small graphic next to each option so people know what socket is what. Also, some charging stations support multiple sockets on a single station so the ability to provide the number of sockets of each type at each station is important.

**Comment by matkoniecz** [comment]
See #903 #117
