### ISSUE TITLE
building_type quest missing 'supermarket' type

### ISSUE THREAD

**Issue by jyasskin** [streetcomplete/StreetComplete#3078]
The commercial building types (https://github.com/streetcomplete/StreetComplete/blob/d932c2ff576500094e4e8a2bb1c3133fed6b8866/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/BuildingType.kt#L87) don't include [`building=supermarket`](https://wiki.openstreetmap.org/wiki/Key:building#Commercial).

**Comment by jyasskin** [comment]
`supermarket` is in [JOSM's presets](https://josm.openstreetmap.de/svn/trunk/resources/data/defaultpresets.xml) but not [iD's](https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets/building). I guess it's debatable whether to use that value or just `retail`?

**Comment by matkoniecz** [comment]
I would say that it is differentiated by large area and single building level. But we have `building=kiosk` selectable and the same could be said here...

**Comment by westnordost** [comment]
`retail` would be fine, though we could revisit if any further common building types could be included.

**Comment by westnordost** [comment]
What are the top building types that are not included by number of usages currently?

**Comment by matkoniecz** [comment]
`barn` (skipped and covered by `farm_auxiliary` for god reasons), `ruins` (but `ruins=yes` is used and preferable) `cabin`, `public` (deprecated for good reasons), `manufacture`, `collapsed` (result of HOT-quality mapping, should not be used), `boathouse` (over 68k usages), `semi` (but `semidetached_house` is used and preferable), `ger`, `storage_tank` (but `man_made=storage_tank` is available and used), `allotment_house`,  `building=stable` (32k uses), `slurry_tank` (is it really a building?), `transformer_tower`, `silo` (`man_made=silo` is used instead), `commercial;residential`, `damaged` (HOT strikes again), `cowshed`, `trullo`, `sty`, `grandstand` (sounds like an incorrect tagging for the renderer) and finally `supermarket`.

All other are below 10k occurences worldwide

**Comment by westnordost** [comment]
Okay, so let's reduce this list based on your comments. I'll eliminate some more:

- cabin (there was at least one issue about that already, hmm)
- manufacture (covered with industrial. IMO since we can't look inside, it's hard to distinguish from generic industrial)
- boathouse
- ger (tents. Often not stationary, wouldn't like to include that. I think this is also HOT mapping in Mongolia or something?)
- allotment_house (actually, I personally have been missing this. I have always been unsure how to tag these - bungalow? No too small. shed? No, too many windows / obviously used for more. Hut? There is an associatation with primitive huts in Africa)
- transformer_tower (I'd say this is covered by `shed`)
- stable (covered by `farm_auxiliary`)
- commercial;residential (using `residential` is perfectly fine)
- cowshed (covered by `farm_auxiliary`)
- sty (covered by `farm_auxiliary`)
- grandstand (what do you mean, @matkoniecz ?)
- supermarket

**Comment by matkoniecz** [comment]
> `transformer_tower` (I'd say this is covered by `shed`)

No, that is for https://wiki.openstreetmap.org/wiki/Tag:building%3Dtransformer_tower

if anything that is covered by `building=service`

![screen04](https://user-images.githubusercontent.com/899988/126192734-7b5cc31a-00ea-412c-a9d0-2390e273baa3.png)

>> grandstand (sounds like an incorrect tagging for the renderer)
>grandstand (what do you mean, @matkoniecz ?)

I have some doubts about tagging say https://commons.wikimedia.org/wiki/File:Gelsenkirchen_-_Schalker_Feld_-_Parkstadion_04_ies.jpg as a building, but I looked at https://en.wikipedia.org/wiki/Grandstand and all examples there are not worse than `building=roof` or `building=ship` for permanently moored ones. So I retract that comment.

**Comment by westnordost** [comment]
> if anything that is covered by building=service

Sorry, mistyped or something, that's what I meant.

**Comment by HolgerJeromin** [comment]
Under/in a grandstand there are often facilities which are located inside a building: Toilets, shops, [nuclear reactors](https://en.wikipedia.org/wiki/Chicago_Pile-1#:~:text=space under the stands)

**Comment by rhhsm** [comment]
Transformer towers are covered by building=service, but I'd much rather have an option to tag them with
building=service
power=substation
substation=minor_distribution
in SC. Almost all service buildings in my area can be tagged more specifically like this.

**Comment by westnordost** [comment]
This is out of scope of the building type quest. 

Anyway, remain to consider are


- cabin (there was at least one issue about that already, hmm)
- boathouse (still don't undestand why there are so many, hmm)
- allotment_house
- grandstand
- supermarket

I'd further exclude supermarket, actually, because supermarket is already covered by `retail`. How do a `retail` building differ from a `supermarket` building? I don't think in any way. If a supermarket moves out of such a retail building, f.e. a shop selling motorcycle clothes could move in no problem. There are also very small supermarkets, so `supermarket` can't exclusively mean those kind of "hyper markets" such as Wallmart. And even those, instead there could be a large do it yourself shop in there, or a building supplies store or a garden center or a furniture store,... . And even if it was just about the size, then this doesn't need an own tag - the size can already be calculated from the area.

**Comment by matkoniecz** [comment]
> boathouse (still don't undestand why there are so many, hmm)

After looking https://taginfo.openstreetmap.org/tags/building=boathouse#map I checked random part of western shore 

![screen04](https://user-images.githubusercontent.com/899988/126876582-46110644-a19b-4ef2-b727-a729872de75b.png)

in region of https://www.openstreetmap.org/way/955020989

Looking at this object it seems to come from some undocumented import of the official data (I commented on the changeset, maybe it is just not linked in the changeset comment)

**Comment by jyasskin** [comment]
To figure out what, if any, PR I should write:

* My confusion about supermarkets could have been cleared up by a more detailed description string ([`quest_buildingType_retail_description`](https://github.com/streetcomplete/StreetComplete/blob/6b86eb09260f06858dd927e56c28939dbfe0961e/app/src/main/res/values/strings.xml#L719)). Would it make sense to add big-box stores to the examples there? In my dialect, that would cover supermarkets as well as Walmart, Lowe's, etc non-food stores. 

* `cabin` appears to have been included in `bungalow` by #2047 / 2a026dda59eb6127d4eea907a578f598918392d0, so I think there's no change needed.
* [`allotment_house`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dallotment_house), [`boathouse`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dboathouse), and [`grandstand`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dgrandstand) have pictures in the wiki, so I can add those if people want.

**Comment by westnordost** [comment]
Thanks for the research!

To include supermarkets in the description sounds like a good idea. I was thinking,  maybe even renane it to "retail" (like the tag) and mention "building housing shop, ..."?

Allotment house is sth Id definitely include. It needs an icon. What could be a good motive? Same as shed but with a single window + shovel + sunflower?

Boathouse is fine I guess... if it is really that common... still feels like a really uncommon tag.

Any idea for an icon for a grandstand? Or just be and show a ball, like for stadium

On 2 August 2021 07:11:46 CEST, Jeffrey Yasskin ***@***.***> wrote:
>To figure out what, if any, PR I should write:
>
>* My confusion about supermarkets could have been cleared up by a more
>detailed description string
>([`quest_buildingType_retail_description`](https://github.com/streetcomplete/StreetComplete/blob/6b86eb09260f06858dd927e56c28939dbfe0961e/app/src/main/res/values/strings.xml#L719)).
>Would it make sense to add big-box stores to the examples there? In my
>dialect, that would cover supermarkets as well as Walmart, Lowe's, etc
>non-food stores. 
>
>* `cabin` appears to have been included in `bungalow` by #2047 /
>2a026dda59eb6127d4eea907a578f598918392d0, so I think there's no change
>needed.
>*
>[`allotment_house`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dallotment_house),
>[`boathouse`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dboathouse),
>and
>[`grandstand`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dgrandstand)
>have pictures in the wiki, so I can add those if people want.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3078#issuecomment-890720840

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> Any idea for an icon for a grandstand?

View from the side/cross section view? Something like

![screen06](https://user-images.githubusercontent.com/899988/127840819-43d20674-d497-4af6-a6ef-b893994f3a0d.png)

from http://photos1.blogger.com/blogger/1670/2029/1600/Olympic%20Cross%20Section.0.jpg

> Or just be and show a ball, like for stadium

Afaik many are in places where no soccer matches take place...

**Comment by matkoniecz** [comment]
> Any idea for an icon for a grandstand?

View from the side/cross section view? Something like

![screen06](https://user-images.githubusercontent.com/899988/127840819-43d20674-d497-4af6-a6ef-b893994f3a0d.png)

from http://photos1.blogger.com/blogger/1670/2029/1600/Olympic%20Cross%20Section.0.jpg

> Or just be and show a ball, like for stadium

Afaik many are in places where no soccer matches take place...

**Comment by westnordost** [comment]
![allotment_house](https://user-images.githubusercontent.com/4661658/128066603-93379e64-9deb-4461-9777-d36e4d773758.png)

**Comment by westnordost** [comment]
![boathouse](https://user-images.githubusercontent.com/4661658/128070952-810e9e4b-4c59-49ca-80cc-eb103d804ae3.png)
