### ISSUE TITLE
Show FIXME tags and allow for additional information

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3084]
**Use case**

If a node/way contains [fixme=*](https://wiki.openstreetmap.org/wiki/Key:fixme) tag, it denotes that the item needs fixing; often (or always if string contains `#surveyme`, as in notes) because it needs surveying. SC currently handles Notes, but not the `fixme` tag which fulfills similar purpose. It would be nice if it supported that too.

It could also help with https://github.com/streetcomplete/StreetComplete/discussions/3083 or https://github.com/streetcomplete/StreetComplete/discussions/2477#discussioncomment-439407 and similar

**Proposed Solution**

If the node with `fixme` tag exists and OSM note does not exist at the same place; it should be shown in the same way as the existing OSM Note, eg. with with question `Can you contribute anything to this fixme?` and then showing the content of `fixme` tag. It should also use filtering that Notes use (eg. adapt to `Show all notes` preference, and to existence of `#surveyme` in tag) 

- if the user selects `No, hide`, it should be hidden in the same way as the note is (entry in local ignore-DB I guess?)
- if the user types text / adds a picture and clicks `OK`, new note should be created at that location with a context (ex. if there was `fixme=has this supermarket reopened?` and user answers `yes, opening hours are now xxxx` the new OSM Note created would say `user responded to "fixme=has this supermarket reopened?" with: yes, opening hours are now xxxx`). Creation of the note would turn it into regular note quest (and as explained at the top, `fixme` would be ignored on locations which have **both** `fixme` tag and open OSM Note)
- (optionally, we could add additional button `this has already been fixed`, which would remove `fixme` tag, but it is probably safer and simpler to let the user leave note and let somebody else updates it if it makes sense).

(Also note previous/closed related issue https://github.com/streetcomplete/StreetComplete/issues/1775; this provides new idea that addresses shortcomings of previous suggestion)

**Comment by matkoniecz** [comment]
Note that many fixme values are cryptic or do not require a survey. See https://taginfo.openstreetmap.org/keys/fixme#values

I display `fixme` in my fork and it is typically usable only to trigger switch to Vespucci.

For example `fixme=continue?` requires context of where such node is placed.

**Comment by mnalis** [comment]
> Note that many fixme values are cryptic or do not require a survey. See https://taginfo.openstreetmap.org/keys/fixme#values

True, but that is also currently the case with notes. Some of them are solvable only on the ground, some of them are not (eg. `Are those buildings mapped correctly?`). And even when not completely solvable on the ground, useful information/pictures could often be added on the ground which can make them solvable in the chair (where previously they were not). 

> For example `fixme=continue?` requires context of where such node is placed.

I've added useful information to Notes phrased in the same way (eg `no, it ends here` + picture, or `yes, it continues to xxx` + picture + sometimes new note `track from SW continues up to here`), so I think I'd also be able to contribute to those in `fixme` tags too. 

Position of the node with `fixme=continue?` would be shown on the SC map, so you'd have as much context there as you have on desktop, right? 
Also note that `fixme=continue?` specifically (with question mark) is most often put by armchair mapping as not enough detail is visible from aerial/satellite photos. On the ground, even if mapper were to put fixme instead of a OSM Note (which is less likely), it would much more likely be tag `fixme=continue` (without question mark), as the mapper is quite well aware that road continues, but lacks the time/will to follow it all the way) 

But if we (later?) feel the need to reduce the number of that quests,  we can show by default only those containing `#surveyme` (at canonical hashtag) and limited number of other popular keywords like `name`, `resurvey`, `check`, `verify`, `survey`, `tracktype`, `refine` etc. (just quick stroll on top few fixme tags, I can increase it if that is the way to be taken). Also, we can use preference value of `Show all notes` there too to select if want to show all `fixme`s or just limited number of them.

**Comment by matkoniecz** [comment]
> True, but that is also currently the case with notes. Some of them are solvable only on the ground, some of them are not (eg. Are those buildings mapped correctly?). And even when not completely solvable on the ground, useful information/pictures could often be added on the ground which can make them solvable in the chair (where previously they were not).

Notes are less prone to that as they clearly are not tightly bind to specific objects, so things like "check ref tag" are far less likely.

> Position of the node with fixme=continue? would be shown on the SC map, so you'd have as much positional context there as you have on desktop, right?

positional? Yes. But `fixme=continue?` can be also on pipeline, cutline, power line and other things invisible from within SC.

**Comment by westnordost** [comment]
I trust that @matkoniecz has a very distinguished opinion about this matter since he added a quest in his fork that displays fixme in the app. His observations also match what I'd expect: That most "fixmes" are not directed at surveyors, i.e. ask for something to be clarified on site but refer to a data issue that must be solved with an advanced editor.

**Comment by westnordost** [comment]
And **IF** it is the case that a fixme needs on-site information after all, the someone who created the fixme or the one who is trying to solve it, could just post a note, inviting others to contribute.

**Comment by matkoniecz** [comment]
From additional check on real data in area where I never mapped:

https://www.openstreetmap.org/way/937425684 - perfect for checking in place
https://www.openstreetmap.org/node/3666523468/history - useless and confusing to show in SC
https://www.openstreetmap.org/node/5727738626 - useless and confusing to show in SC (context of other tags is crucial)
https://www.openstreetmap.org/relation/6851381 - unclear even with context
https://www.openstreetmap.org/way/455174226 - unclear even with context, I removed it
https://www.openstreetmap.org/way/240819164 - useless and confusing to show in SC
https://www.openstreetmap.org/node/5170078008 - `fixme=continue` at end of way - how SC mapper is supposed to help here?

**Comment by matkoniecz** [comment]
I proposed somewhere showing fixme as opt-in special quest for advanced users who use Vespucci anyway. But it goes against SC vision, and is likely a feature creep.

**Comment by Helium314** [comment]
I also show fixmes im my modified version, and have similar experience.

Often I see something completely unclear like `fixme=yes`, or problems where I cannot help.
Then there are quite a few cases where I could help, but frequently there is no need any more as some other SC user took care of it (`fixme=capacity` for bicycle parkings, `fixme=wheelchair`, `fixme=opening hours`, `fixme=what type is this building?`, `fixme=does this still exist?`). Here I only make a note to later remove the fixme tag.

What I can do is for fixmes like `fixme=exact location`, here the feature name is usually enough to identify the element. But of course this requires opening a new note at the more precise location, which is not directly related to the fixme "quest".
And my dreaded enemy, the fixme that asks whether the element is a tree or a shrub (there are too many of those in Vienna, and I _really_ don't care about the answer)

**Comment by matkoniecz** [comment]
> I also show fixmes im my modified version, and have similar experience. (...) Here I only make a note to later remove the fixme tag.

If you do it often you may want to steal my fixme quest code which has option to delete fixme tag directly in SC.

**Comment by Helium314** [comment]
> If you do it often you may want to steal my fixme quest code which has option to delete fixme tag directly in SC.

Thanks, will definitely use it!

**Comment by matkoniecz** [comment]
Is it a good idea to have `fixme` quest disabled by default? Opt-in for advanced users who want to notice them and complete edit with Vespucci?

It is something that I would personally like, but it sounds like a feature creep and deviating from vision of SC where everything is usable by newbies.

**Comment by mnalis** [comment]
@matkoniecz and @Helium314 raise good points about `fixme` values which are not easy to solve on the ground (or even anywhere), especially as they already have been doing that. At the bottom of https://github.com/streetcomplete/StreetComplete/issues/3084#issuecomment-883477983 I **suggested to limit the quest to certain values found in taginfo**, which would indicate that on-the-ground-survey is indeed intended means to solve the problem, which IMHO should help alleviate that issue.

But I agree that even such filtering heuristics might be non-perfect, and might sometimes result in unsolvable quest  (as example, even our current heuristic which tries to do same for Notes is far from perfect in this regard and does produce "unsolvable" quests sometimes). 

I would be interested in opinion of others, especially those who have looked at `fixme` tags already on the ground, if even such filter which would only include `fixme`s that contain `#surveyme`, `resurvey`, `name`, `tracktype`  etc. (from taginfo) would produce too many false-positive quest (eg. quests that cannot be solved by regular on-the-ground SC users without resorting to Vespucci or other tools). 

If that is indeed the case that the quest would be mostly useless for regular SC users, then I agree it would not be good fit for (original/upstream) StreetComplete and idea should be dropper here (and only used in unofficial forks when useful).
If however limiting would make it likely that regular users might actually be able to solve it majority of cases (eg. if filtered/limited number of `fixme` quests shown could be **at least as solvable** as current `Notes` quest), then perhaps it might be considered for implementation.

**Comment by rhhsm** [comment]
Apparently code for this quest already exists, so couldn't it just be included as an option (default off quest) so we can collect some more user experience? I'd definitely like to try how it works in my area.

**Comment by Helium314** [comment]
There is the idea to have such features in a special version of StreetComplete, see #3003
You can try it using the version I linked somewhere in the discussion

**Comment by matkoniecz** [comment]
>  so couldn't it just be included as an option (default off quest) so we can collect some more user experience?

Released version is not a place for such experimental testing.

**Comment by westnordost** [comment]
Anyway, based on what had been written by @matkoniecz and me, I'll close this as will not fix.

**Comment by mnalis** [comment]
[SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (_"SC Expert Edition"_) allows users to enable _"half-quest"_ (for lack of better name) for `fixme` tags. If enabled, the icon is kept small (just a dot), and only when zoomed-in, so as to not make map unreadable when zoomed-out (like in that OsmAnd example). 

You can then click on it and choose to:
- move the POI slightly
- remove the object from the map, if it does not exist any more
- leave full OSM note (with images) for later solving in more advanced editor
- remove the `fixme` tag
- edit raw tags if wanted (only if expert mode is enabled). 

It looks like this (you might notice I'm having several extra features enabled, you can choose not to in order to look more like regular StreetComplete, or you might choose to enable even more of them):


https://github.com/streetcomplete/StreetComplete/assets/156656/8d9c31ac-fff2-4da8-80dd-63f2c56d9571

 
Otherwise SCEE aims to looks mostly the same as regular StreetComplete by default (and only enable some extra features if you choose so in Settings); so perhaps @Dimitar5555 (and other interested parties) may want to give it a try.

Personally, I have `fixme`s enabled in several presets, although even when enabled I only ever solve about 1/3 of them (mostly because many are  like `continue` or `verify tags` often require more much work than I'm willing to invest. I'm still happy to see them, even if I don't solve them). YMMV.

**Comment by matkoniecz** [comment]
Overlays also should be possible to handle without deep OSM knowledge.

`fixmes` in their current state go beyond https://github.com/streetcomplete/StreetComplete/blob/master/OVERLAY_GUIDELINES.md
