### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#3085]
**Use case**
I would like to have presets which I can quickly use depending on what I'm working on. For example, sometimes I just want to do some armchair sessions with Mapillary to specify the road surface, the number of lanes, and whether sidewalks exists. Other times I'm on my bicycle so I can tag things that I can see from the road, but no more, other times I'm on foot and I can do detail mapping. Setting and unsettling the quests manually every time is tedious.

**Proposed Solution**

I would like an option such as "Epic" or "Quest profile" that can allow me to pre-select quests with a few taps.

**Comment by smichel17** [comment]
This is being implemented in #2565. Other related issues: #1654, #3034, and somewhat #2944

**Comment by smichel17** [comment]
For folks over email: I originally mixed up the numbers during copy/paste, edited to fix now.

**Comment by westnordost** [comment]
Interesting that you mention mapillary.

If you are at home having mapillary at hand,  why don't you use a more flexible editor like the one on the website (iD) or Josm?

On 21 July 2021 11:59:45 CEST, smichel17 ***@***.***> wrote:
>For folks over email: I originally mixed up the numbers during
>copy/paste, edited to fix now.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3085#issuecomment-884060011

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mishari** [comment]
@westnordost StreetComplete allows me to just enter information without having to go through many interfaces. Sometimes this is more relaxing :)
