### ISSUE TITLE
next_check_date

### ISSUE THREAD

**Issue by gtrus21** [streetcomplete/StreetComplete#3086]
Add tag next_check_date=* support
https://wiki.openstreetmap.org/wiki/Key:next_check_date

**Comment by matkoniecz** [comment]
How it would work? SC is unable to guess what needs to be rechecked and it could be something not supported by SC.

**Comment by gtrus21** [comment]
OK...

**Comment by mnalis** [comment]
Also, [taginfo](https://taginfo.openstreetmap.org/keys/next_check_date) on that wiki page claims "This key does not appear in the OSM database"
