### ISSUE TITLE
Abfragen-Reihenfolge bei Wohngebäuden wird nicht berücksichtigt

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3093]
For some buildings I cannot determine the type of building with this unit, but I can determine the number of floors and roof shape.
 If I switch off the query for the type of building in the settings, the number of floors and roof shape is not asked, although the switches for these queries are set to.
 If I change the order of the queries (number of floors, roof shape, building type, all queries to on), the building type is still asked first.

**Comment by matkoniecz** [comment]
That is because StreetComplete is unable to guess whether `building=yes` is one where answering number of floors and roof shape is possible.

StreetComplete prefers some false negatives (not asking quest where it can be answered) over false positives (quest impossible to answer) - false positive question would be asked for every single mapper and generate stream of useless notes.


See for example cases for industrial buildings where building level count is not answerable (at least from outside): https://commons.wikimedia.org/wiki/File:Linden_power_plant_Elisenstrasse_Ihme_river_Linden-Nord_Hannover_Germany_02.jpg https://en.wikipedia.org/wiki/File:Martinlaakson_voimalaitos.JPG https://commons.wikimedia.org/wiki/File:Walters_Ranch_Hop_Kiln_in_2019,_4×5.jpg https://en.wikipedia.org/wiki/File:Koebergnps.jpg https://commons.wikimedia.org/wiki/File:Kernkraftwerk_Stendal_Panorama_2012.jpg

**Comment by westnordost** [comment]
Danke,  @matkoniecz , das ist der Grund warum Streetcomplete nicht für building=yes fragt.

Fehlen dir Gebäudesrten, @biketeur ?

**Comment by biketeur** [comment]
Nein, mir fehlen keine Gebäudearten.
Aber eure Antworten stellen mich nicht zufrieden.
SC bietet Schalter an, die ich ein- oder ausschalten kann und gibt mir sogar die Möglichkeit, die Reihenfolge der Abfragen zu verändern.
Ich will dies nutzen, aber es wird nicht zugelassen.
Die Begründung des unnötigen Datentransfers kann ich nicht nachvollziehen:
Ich habe ein Gebiet heruntergeladen, den Flugzeugmodus eingestellt, um sämtlichen Datenverkehr zu unterbinden, ein Gebäude als House getaggt, und sofort erschien die Frage nach den Stockwerken, also kein zusätzlicher Datenverkehr.
Dass SC nicht erraten kann, ob bei building=yes eine Antwort auf die Anzahl der Stockwerke und die Dachform möglich ist, ist einleuchtend. Aber ich als Anwender, der vor dem Gebäude steht, kann die Stockwerkanzahl und die Dachform von außen betrachtend eindeutig beantworten.
Warum kann ich die Gebäudeart nicht immer eindeutig bestimmen?
Zwei Beispiele:
Technologiezentrum in der Nähe einer Universität, an einem der Gebäude steht von außen sichtbar, das hier die Roboterforschung der Abteilung Maschinenbau zu finden ist. Ist dies jetzt ein Hochschulgebäude oder ein Bürogebäude (ist vermutlich nur angemietet von der Uni). Ich kann und will dies nicht entscheiden, wohl aber sehe ich, dass das Gebäude 3 Stockwerke hoch ist und ein Flachdach hat. Aber diese Werte läßt mich SC z.Z. nicht eingeben .
2. Beispiel
Größeres, freistehendes Haus (ehemalige Direktorenvilla). Es könnte sein, dass dieses Haus aufgrund seiner Größe heute von mehreren Familien bewohnt wird, also ein Mehrfamilienhaus ist.
Da der Hauseingang an der Seite und von der Straße aus nicht einsehbar ist wegen eines Vordaches, sind somit Klingel und Briefkästen nicht einsehbar und somit die Gebäudeart nicht eindeutig bestimmbar, wohl aber Stockwerke und Dachform.

Vielleicht denkt ihr Mal über einen Expertenmodus nach? 😀

**Comment by westnordost** [comment]
> Die Begründung des unnötigen Datentransfers kann ich nicht nachvollziehen
> Ich habe ein Gebiet heruntergeladen, den Flugzeugmodus eingestellt, um sämtlichen Datenverkehr zu unterbinden, ein Gebäude als House getaggt, und sofort erschien die Frage nach den Stockwerken, somit kein zusätzlicher Datenverkehr.

Diese Begründung wurde nirgends genannt. Es geht darum, dass Nutzer möglichst nicht Fragen gefragt werden, die sie nicht beantworten können. Siehe auch [Quest Guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete).

> Technologiezentrum in der Nähe einer Universität

Bürogebäude. Aber letztlich ist beides OK. Ein Auditorium beispielsweise wäre eindeutig ein Uni-Gebäude. Für ein Bürogebäude innerhalb eines Krankenhauskomplexes würde ich auch Bürogebäude wählen, letztlich ist Krankenhausgebäude aber auch OK aus meiner Sicht.

> Größeres, freistehendes Haus (ehemalige Direktorenvilla). Es könnte sein, dass dieses Haus aufgrund seiner Größe heute von mehreren Familien bewohnt wird, somit ein Mehrfamilienhaus ist.

Egal, freistehendes Haus ist es trotzdem. Die Frage nach dem Gebäudetyp bezieht sich in erster Linie darauf, als was es errichtet wurde (wenn es offensichtlich ist). Aber letztlich meiner Meinung nach wäre beides erstmal exakter als `building=yes`.

> PS: in Vespucci ist es möglich, Stockwerke und Dachform einzugeben, aber building=yes stehen zu lassen.

Natürlich, aber Vespucci funktioniert ja auch ganz anders. StreetComplete wird nie versuchen, ein besseres Vespucci zu sein, beide Apps haben ihre Zielgruppe und ihre Berechtigung.

**Comment by mnalis** [comment]
see also related issue about another quest blocked by `building=yes` (with more discussion/explanations): https://github.com/streetcomplete/StreetComplete/issues/2464

**Comment by Helium314** [comment]
>    Größeres, freistehendes Haus (ehemalige Direktorenvilla). Es könnte sein, dass dieses Haus aufgrund seiner Größe heute von mehreren Familien bewohnt wird, somit ein Mehrfamilienhaus ist.
>    Da der Hauseingang an der Seite und von der Straße aus nicht einsehbar ist wegen eines Vordaches, sind somit Klingel und Briefkästen nicht einsehbar und somit die Gebäudeart nicht eindeutig bestimmbar, wohl aber Stockwerke und Dachform.

"residential" gibts auch noch für solche unklaren Fälle

> Vielleicht denkt ihr mal über einen Expertenmodus nach? 

siehe #471, und möglicherweise irgendwann mal #3003
