### ISSUE TITLE
Zoom using the +/- volume button

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#3095]
It is often very inconvenient to zoom with two fingers or with the buttons in the lower right corner. For example, when zooming with two fingers the map can turn, and the buttons on the screen are uncomfortable if the phone is in the right hand. It would also help to solve #3094.

So I suggest adding a setting that enables scaling with the volume buttons. There is such a thing, for example, in the Vespucci editor and in Yandex.Maps. (upd: and OsmAnd (disabled by default))

**Comment by westnordost** [comment]
Is this enabled by default in the apps you mentioned?

**Comment by deevroman** [comment]
In Vespucci - yes, in Yandex.maps - no

**Comment by biketeur** [comment]
Zoomen mit den Lautstärketasten ist sicherlich eine gute Idee.
Eine weitere Idee, die ich sehr begrüßen würde, wäre, wenn die Buttons fürs Zoomen und die akt. Position als Gesamtblock von mir als User belibig

**Comment by westnordost** [comment]
I am still not sure about this... it feels like a hack/misuse to do this. Vespucci should not be taken as a reference, it also uses the "I am a game" fullscreen-mode.

**Comment by andrewharvey** [comment]
> "I am a game" fullscreen-mode.

Oh is that why every time I try to swipe up from the bottom of the screen to go back to the home screen Vespucci seems to hijack the gesture.

**Comment by matkoniecz** [comment]
> Oh is that why every time I try to swipe up from the bottom of the screen to go back to the home screen Vespucci seems to hijack the gesture.

BTW, it can be disabled in advanced settings of Vespucci.

**Comment by deevroman** [comment]
> Vespucci should not be taken as a reference
What about OsmAnd? It also has this setting (disabled by default)

**Comment by Helium314** [comment]
If this feature will be added, _please_ include a setting to switch it off. I still use the volume buttons for their original purpose.

**Comment by westnordost** [comment]
I will close this as will not fix for now on the grounds that I think it is unexpected (for the user) and uncommon that an app hijacks the volume buttons to make them do something different. And as you all know, I am very wary to add new settings to the app.
