### ISSUE TITLE
Quest "Is this still here? (...)" should include amenity=drinking_water

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3102]
**Use case**

StreetComplete should ask to check if instances of `amenity=drinking_water` are still present in order to remove instances that don't exist anymore.

Here is an example: https://www.openstreetmap.org/node/349336485

This Overpass query finds old instances:

```
node[amenity=drinking_water]({{bbox}})->.all;
(.all; - nwr.all(newer:"2010-04-01T00:00:00Z");
);
out body;
>;
out skel qt;
```
You can use it directly at https://osm.li/NwJ 

**Proposed Solution**

Extend the existing quest "Is this still here? (...)"

**Comment by westnordost** [comment]
Ok
