### ISSUE TITLE
AddCrossingType should have "no crossing" and "forbidden" answers

### ISSUE THREAD

**Issue by jyasskin** [streetcomplete/StreetComplete#3106]
**Use case**
I've been describing crosswalks in my neighborhood by drawing sidewalks at home using aerial photography, and then walking around with StreetComplete to fill in details. Sometimes the aerial photography is unclear, and I wind up drawing a crossing where there isn't one, but then the StreetComplete quests aren't enough to correct that during my survey. There are two kinds of mistakes:

1) The crossing just doesn't exist. This has 3 sub-cases:
   1. https://www.openstreetmap.org/note/2777232 was a place where one traffic light controls both parts of the street, and pedestrians have to cross on the outside edges of the overall intersection.

   1. https://www.openstreetmap.org/changeset/108846698 is a little more ambiguous: the street geometry is the same, but there's no traffic light. Pedestrians should still cross on the outside edges.

   1. https://www.bing.com/maps?osid=f592579f-02d5-4684-9ace-c3a780f5b2d9&cp=45.514298~-122.622983&lvl=19&dir=62.119&pi=0&style=x&mo=z.0&v=2&sV=2&form=S00027 is even more ambiguous. There's a legal crossing here, but as you can see from the ghost bike, it's a really bad idea, and pedestrians should walk a block to the light-controlled intersections a block away.

I don't think the app needs to have an opinion on which of these should omit the `highway=crossing` tag, although I don't oppose an opinion either. The wiki doesn't express an opinion, and it's worth having the option in order to support the first case above.

2) The crossing has a sign forbidding crossing there: https://www.openstreetmap.org/note/2773674 / ![Photograph of a no crossing sign](https://westnordost.de/p/51502.jpg). 

**Proposed Solution**

For (1), I'd remove the `highway=crossing` node and `footway=crossing` way, and if there's a short `footway=sidewalk` segment attached to the crossing way whose other end is another sidewalk, ideally that should also be removed.

For (2), I'd do the above, and also add a `crossing=no` tag.

It's also plausible to collapse (1) and (2) and always add the `crossing=no` tag.

**Comment by matkoniecz** [comment]
If `highway=crossing` is tagged and there is no crossing then it is too complex to solve automatically based on simple answers.

In such cases mapper should create a note with photos and leave it to more experienced/involved, or edit on its own with Vespucci. Or with JOSM/iD back at home.

**Comment by jyasskin** [comment]
Auto-fill a note for all but the simplest cases, but the case without a `footway=crossing`, and maybe the case with a short one that just connects 2 sidewalks, seem simple enough to handle.

**Comment by matkoniecz** [comment]
(1) If crossing was mapped and is not existing anymore then it is basically 100% certain that something seriously changed there, benefit from automatically removing part of the problem is dubious

(2) It is not simple to implement anyway

**Comment by mnalis** [comment]
I agree with @matkoniecz that such a conflict likely indicates bigger issue, which should be solved outside the StreetComplete. But the idea that StreetComplete could detect such conflict, and open a prefilled note as @jyasskin suggests (while still allowing the user to add text and especially pictures to the note, of course) does sound useful and interesting. 
After all, you do have to be on the ground to provide more information needed to fix such problem.

**Comment by jyasskin** [comment]
I'm happy to start a PR for whatever part of this looks like a good idea. For now, that seems like just an option in the Can't Say menu that pre-fills a note?

**Comment by westnordost** [comment]
StreetComplete doesn't prefill notes as a principle (except for the info in which context a note was created, if it was created in the context of a quest answer). It is not planned to change that, it would open up a whole new can of worms.

**Comment by westnordost** [comment]
Also, I've read your initial comments and examples, though it was a little difficult to understand how the situations differed. In any case, note this PR https://github.com/streetcomplete/StreetComplete/pull/2999 which will add a quest that adds `highway=crossing` to vertices where a footway and a road cross (basically).
