### ISSUE TITLE
AddTactilePavingCrosswalk and AddTactilePavingKerb should interact better

### ISSUE THREAD

**Issue by jyasskin** [streetcomplete/StreetComplete#3107]
**Use case**

In an intersection like https://www.openstreetmap.org/node/40538731, the app will ask about tactile paving 12 times when there are only 8 places (the AddTactilePavingKerb quests) that could have tactile paving or not. The `highway=crossing` nodes can be inferred from the kerb tags, and a `yes` answer to AddTactilePavingCrosswalk answers 2 kerb nodes at once. It would be nice if the app optimized this interaction a bit.

This was discussed some in #2347, but here I'm suggesting an improvement to how we live with the double-tagging that the community seems to have settled on.

**Proposed Solution**

1) In AddTactilePavingKerb.applyAnswerTo(), we should look for the next nodes in the adjacent `footway=crossing` way, and if those are a `highway=crossing` node and then a `barrier=kerb; tactile_paving=*` node, we should set the crossing node's `tactile_paving` key to the appropriate value.

2) In AddTactilePavingCrosswalk.applyAnswerTo(true), we should look for a unique `footway=crossing` way that contains the `highway=crossing` node, step out to find its kerbs, and set them to `tactile_paving=yes`. In AddTactilePavingCrosswalk.applyAnswerTo(false), if both kerbs are set to `tactile_paving=yes`, something's out of date, so it'd be nice to flag both kerbs to be re-quested, but it's not obvious how to do that.
  I think the `highway=traffic_signals; crossing=traffic_signals` case is irrelevant here, because those only happen at the center of an intersection without separated sidewalks, so there won't be any kerb nodes to modify.

**Comment by westnordost** [comment]
This would probably make sense. However, this is not possible in `applyAnswerTo`, that is not how the function works or should work. A quest answer is always only applied to one element. This is a limitation of the app, but I am happy about that limitation, I need to limit the complexity of the app somehow.

However, this may be a good validation check for a validator. See if `tactile_paving` differs for the crossing node (if it is set) with the tagging for the kerbs.
