### ISSUE TITLE
Show other quests for the same node/line/area

### ISSUE THREAD

**Issue by mbraeutigam** [streetcomplete/StreetComplete#3108]
**Use case**

When doing a mapping walk I often encounter the following issue:
Sometimes it is not possible to answer a quest because of no full sight of the object (e.g. how many levels does a building have) but sometimes there are other quests hidden under the same node/line/area which only can be accessed with moving around the priorities of quests or hiding the quest manually.

**Proposed Solution**

Add a selector for all possible quests for the currently selected node/line/area to left side like you've done it already for the edit history. So it would be fast and easy to switch to other quests and complete them without having to hassle with the mentioned hacks above (change priority, hide quests).

Mockup:
![image](https://user-images.githubusercontent.com/4228180/127748427-b5f46c71-62a1-4d05-aa25-d6d9b2d15ec1.png)

**Comment by matkoniecz** [comment]
See #124

**Comment by mnalis** [comment]
I agree, mockup does not look bad.

But, while helping part of the bigger problem (multiple quests for same item), it does not solve other related problem (eg. that in this example quest that is just right of selected house is obscured and cannot be selected; and same workarounds as @mbraeutigam mentioned must be applied to reach it). 

It would be nice if solution to be adopted covered **_both_** of those frequent issues (perhaps "skip to next hidden nearby quest" button/icon :fast_forward: or something like that?)

**Comment by smichel17** [comment]
For reference, the discussion of "complete all quests for one object in a row" is at https://github.com/streetcomplete/StreetComplete/issues/1969 and https://github.com/streetcomplete/StreetComplete/issues/2710#issuecomment-812444576 ([via](https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1083149)).

Selecting the next *nearby* quest (not just for the same object) is something new, which I have not seen suggested before.

**Comment by mnalis** [comment]
@smichel17 there has been some talk about how to address the issue of nearby "obscured" quest. https://github.com/streetcomplete/StreetComplete/issues/2359#issuecomment-869039152 lists some of them, but I'm sure there were more. 

Current workaround [seems to be](https://github.com/streetcomplete/StreetComplete/issues/2359#issuecomment-869145132) `Other answers` / `Can't say` / `No, just hide`, then **solving the quest** which shows, and then `Undo` / `Show edit history` / click the hidden quest / confirm the hidden quest / `Undo`, which is rather cumbersome.

**Comment by smichel17** [comment]
Thanks for the link, added it in https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-646708
