### ISSUE TITLE
Don't set check_date for "Is this [...] still here?" quest

### ISSUE THREAD

**Issue by dafadllyn** [streetcomplete/StreetComplete#3110]
The [`check_date`](https://wiki.openstreetmap.org/wiki/Key:check_date) tag for "Is this [...] still here?" quests is problematical, as it gives the impression that all properties (tags) of an object have been checked on that date, for example that the existence of a postbox and its collection times and reference number (if tagged) have been checked. Please set a `check_date:existence` tag instead.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/keys/check_date%3Aexistence is used just 136 times worldwide...

**Comment by westnordost** [comment]
Tag is not documented and has miniscule usage.

Usage history looks like it has been pushed by a single user or tool. 

> as it gives the impression that all properties (tags) of an object have been checked on that date, for example that the existence of a postbox and its collection times and reference number (if tagged) have been checked.

I doubt that. check_date has always been about existence, or at least it had been unspecified what exactly had been checked (which comes down to: at least existence had been checked), never "all tags", as it is not always possible to verify all tagged values on-site. F.e. a place has opening hours, but doesn't have them posted. 

On 1 August 2021 18:03:08 CEST, dafadllyn ***@***.***> wrote:
>The [`check_date`](https://wiki.openstreetmap.org/wiki/Key:check_date)
>tag for "Is this [...] still here?" quests is problematical, as it
>gives the impression that all properties (tags) of an object have been
>checked on that date, for example that the existence of a postbox and
>its collection times and reference number (if tagged) have been
>checked. Please set a `check_date:existence` tag instead.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3110

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by dafadllyn** [comment]
There's also `checked_exists:date` with 606 uses, but i think it makes more sense to stick with one tagging scheme.

> never "all tags", as it is not always possible to verify all tagged values on-site

I thought that if something can't be verified on-site (or on the operator's website), it doesn't belong in OSM. Only checking the existence of a shop, restaurant or postbox without also checking it's opening hours or collection times doesn't make much sense in my opinion.

Note that there's no other tag for "everything last checked on", but there are tags for "existence last checked on". Do i have to add 10 `last_checked:*` tags if i check all 10 tags of an object?

**Comment by westnordost** [comment]
There are plenty of things in OSM that can't be checked on-site. Things tagged should be verifiable, one way or another.

**Comment by 10992-osm** [comment]
For discussion on this topic, see issues #2074, [this comment](https://github.com/streetcomplete/StreetComplete/issues/2508#issuecomment-761579232) in #2508, also #2592 to a lesser extent.

**Comment by westnordost** [comment]
Thanks for the link! Right, in https://github.com/streetcomplete/StreetComplete/issues/2508#issuecomment-761579232 I articulated better than in this ticket why the app uses the tag it uses.

**Comment by dafadllyn** [comment]
Sorry, i didn't see #2508. I'll comment there.

**Comment by westnordost** [comment]
You can comment there, if you like, but it would be more productive to discuss a possible replacement of `check_date` for marking if something still exists on the tagging mailing list or better as a proposal on the wiki.

**Comment by dafadllyn** [comment]
Okay, if you think so.

(Besides, #2508 isn't appropriate anyway because it requested to "use check_date:existence instead of check_date in the existence quest" while i requested to not use check_date.)

**Comment by westnordost** [comment]
You requested to

>  Please set a check_date:existence tag instead.

**Comment by dafadllyn** [comment]
Yes, you are right. ☺️ I should watch my language... `check_date:existence` was meant as a proposed solution. The actual request was to stop using check_date for the "existence questions".

**Comment by dafadllyn** [comment]
https://lists.openstreetmap.org/pipermail/tagging/2021-August/062147.html
