### ISSUE TITLE
Improve photos for What type of bollard is this.

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#3112]
For the "What type of bollard is this?" quest the photos mostly just look like the same kind of bollard but with different material.

I think it would be better if the graphics were zoomed into the distinct feature for type of bollard.

I tried to search for the graphics https://github.com/streetcomplete/StreetComplete/search?q=bollard_removable_with_key but couldn't find where they are stored to do a PR? Where are the graphics so I can propose a PR?

For example like this for removable with key, clearly showing the lock.

![removable_with_key](https://user-images.githubusercontent.com/117278/127944345-e0614802-7397-4287-b2b3-da04ae943939.jpg)

**Comment by mnalis** [comment]
@andrewharvey  I can see old graphic at https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/drawable-xxhdpi/bollard_removable_with_key.jpg; there are also other resolutions listed in https://github.com/streetcomplete/StreetComplete/commit/3a384aa95fe05a1bb48d742e4fe3f00b61f809c6. 

I don't know if there is upstream version in repository besides that (I would expect to find one if it exists at https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics but can't see it there either)

**Comment by andrewharvey** [comment]
Thank you. GitHub mustn't have searched for file names.

> (It would IMHO be nice if replacement picture could contain little more of the bollard though, instead of just this zoomed-in view of the lock.)

I can, this one I posted is cropped so I can include more bollard, though for this quest we already know it's a bollard and we need to clearly show the distinguishing features between the types of bollards.

**Comment by matkoniecz** [comment]
https://github.com/matkoniecz/rescaling_for_android may be useful (if rescaling image files manually is still required by Android Studio)

In my opinion showing just relevant parts of bollards would be fine.

Pinging @FloEdelmann  as relevant

**Comment by westnordost** [comment]
I don't find this important. Important are the titles, as bollards can look very different anyway.

On 3 August 2021 08:07:42 CEST, Mateusz Konieczny ***@***.***> wrote:
>https://github.com/matkoniecz/rescaling_for_android may be useful (if
>rescaling image files manually is still required by Android Studio)
>
>In my opinion showing just relevant parts of bollards would be fine.
>
>Pinging @FloEdelmann  as relevant
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3112#issuecomment-891559904

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by FloEdelmann** [comment]
The original sources for the images can be found here:

https://github.com/streetcomplete/StreetComplete/blob/6b86eb09260f06858dd927e56c28939dbfe0961e/app/src/main/res/authors.txt#L33-L38

For the specific image (removable with key), I actually prefer the current image. Anyone will recognize a lock as "I need a key to open this", but that hole with a triangular pin is maybe a bit more unfamiliar (but common for bollards).

**Comment by mnalis** [comment]
@andrewharvey yes, GitHub `Search or jump to` in the upper left corner only searches for content inside a files... To find a file by its name, one must go to `Code` tab, and then click on the `Go to file` button (the upper-middle of the screen on desktop). Somewhat confusing, I agree.
