### ISSUE TITLE
Ramp quest adds ramp=yes when only a bicycle ramp is present

### ISSUE THREAD

**Issue by AndrewHain** [streetcomplete/StreetComplete#3113]
The ramp quest adds the tag ramp=yes as well as ramp:bicycle=yes for bicycle ramps, for instance https://www.openstreetmap.org/way/157427177/history

**How to Reproduce**

Choose bicycle ramp in the Ramp quest.

**Versions affected**

StreetComplete 31.3, Android 11.

**Comment by matkoniecz** [comment]
Is it wrong?

**Comment by westnordost** [comment]
No, it's not wrong. `ramp=yes` means "there is a ramp", `ramp:xxxx=yes` specifies the type(s) of ramp.
