### ISSUE TITLE
Ask which direction a stop sign applies to

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3118]
### General
Affected tag(s) to be modified/added: [direction](https://wiki.openstreetmap.org/wiki/Key:direction) or maybe [stop=all](https://wiki.openstreetmap.org/wiki/Key:stop)
Question asked: **In which direction do cars have to stop here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [x] 🚧 To be added tag is established and has a useful purpose ([used by OsmAnd](https://github.com/osmandapp/OsmAnd/issues/2246#issuecomment-354642637) at least)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) - More than 200,000 `stop` and similar with `give_way` do not have `direction` tagged

### Ideas for implementation

**Element selection:** 
`highway=stop` and `highway=give_way`
`direction!=*`
`stop!=*`
EDIT: exclude nodes on highways with `oneway=*`
Simplest case is where the node is in the middle of a way and not crossing any other ways.
The use of `stop=*` is a bit mixed, to me `stop=minor` is ambiguous and it would be better for the exact locations of stops to be tagged. So maybe leave out nodes which are members of two or more ways.

**Proposed UI:**
Vaguely similar to the steps direction quest.
Select the direction in which cars are going that they have to stop (or say that all directions have to stop, if we include nodes on crossing ways).

Once implemented this could easily be extended to include other things that need a direction tagging

**Comment by matkoniecz** [comment]
>  Easily answerable by everyone from the outside but a survey is necessary

Are there any cases where it is

- not determinable automatically (by looking for nearest road crossing)
- not possible to determine it basing on existing OSM data

?

I always considered it weird that Osmose complains about this.

**Comment by arrival-spring** [comment]
I think that mostly it could be determinable automatically, but sometimes it might be close between two roads or might be in the middle of a road and either side of a crossing or something.

**Comment by matkoniecz** [comment]
Stop signs, at least in my experience, are just before the crossing.

**Comment by arrival-spring** [comment]
Sometimes crossings are close to road junctions too though

**Comment by matkoniecz** [comment]
Can you give any example of any stop sign where this requires survey?

(and that leaves open question how often it happens)

**Comment by matkoniecz** [comment]
Also, see #658 - but the reason for closing no longer applies (I think).

**Comment by arrival-spring** [comment]
I did a quick search, but didn't find that issue.

https://www.openstreetmap.org/node/2608078007 but that should actually be `traffic_calming`
If this https://www.openstreetmap.org/node/1107477871 were slightly different then the automatic version would get the direction wrong
https://www.openstreetmap.org/node/8617620120 does it apply to the crossing or the main road? (Can be answered from aerial)

Not sure how many actually really need surveying then or how they could easily be selected for a quest

**Comment by westnordost** [comment]
Yeah, I would say this shouldn't be a quest.
- See https://github.com/streetcomplete/StreetComplete/issues/3118#issuecomment-892585161
- I believe oftentimes, for cases where the answer will not be the same as what an automatic algorithm would determine, more would need to be fixed, such as the node to be moved etc.
- No convincing examples have been shown that show that a problem that needs fixing exists and that it can only or better be fixed by surveying the site
