### ISSUE TITLE
A quest for FIXMEs

### ISSUE THREAD

**Issue by winkeldings** [streetcomplete/StreetComplete#3119]
I often encounter objects with a fixme tag, that request input from someone on site. Unfortunately I cannot see those requests in StreetComplete. An example would be the fixme 'missing address'. If I would have seen this fixme in StreetComplete, I could have given useful information to solve it by leaving a note.

The fixme quest could be like the note quest. The message would be shown and the user would be asked, if they can provide any useful information. If they choose to do so, the information is added as a note above the object with the fixme.

I know that many fimxes could lead to confusion with unexperienced mappers. Therefore the quest should be disabled by default.

**Comment by matkoniecz** [comment]
See #3084
