### ISSUE TITLE
Resurvey of Access Restrictions

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#3120]
### General
Affected tag(s) to be modified/added: [`access` and some others](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation)
Question asked: **Are these access restrictions still correct?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

Resurvey only. If there are access restrictions it makes sense to resurvey them from time to time since they will greatly impact any routing.

**Proposed UI:**

While there are many tags listed in the [access wiki article](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation) it would be better to have the users just ask if the access rights are correct. If not they should open a node and shoot a picture of the signage.

Rendering the tags (at least the most common ones) for review as signs or offer a "building set" to construct the signage found there is probably too much effort.

So the easiest solution would probably be to have a translation for each vehicle type in the tag list and just have a red X or a green ✓next to it.

**Comment by mnalis** [comment]
- Do the access tags really change that often where you live (without the rest of the area being changed)? 

  Over here in Croatia, if something is `access=private` in vast majority of cases it will stay that way for a looong time - unless the area is razed and rebuilt, but that usually **requires much more editing** then just updating access tags. Same if it was public and the land was sold to someone else who for example builds apartment house there and makes it private. 

  So in my experience, when access tags do change, there is high probability that other things have changed too, and the are likely needs more complete remapping effort (eg. Vespucci/JOSM).

- Also, do you intend to ask only on `highway=*` which already has `access/foot/bicycle/...=*`, or on all `highway=*` even it has not access restrictions mapped, or even on more elements (`barrier=*`, `parking`, `entrance` etc)?

- From the UI perspective, it does not sound very nice showing such a big table (there are a ton of access tags!). JOSM for example asks only for **some** of them (`foot`, `wheelchair`, `bicycle`, `ski`, `snowmobile`, `dog`, `horse`, `all vehicles`, `motor vehicles`) and it is already hard even on desktop. And then, **_each of them_** can be unset if unknown (or mapper didn't care enough), or have values like `yes`, `no`, `dismount`, `official`, `designated`, `permissive`, `destination`, `delivery`, `permit`, `private`, etc.) - and [they are really being used](https://taginfo.openstreetmap.org/keys/?key=access#values) so **simple checkbox** idea is likely out (is the `private` access green :heavy_check_mark: or red `X` ? How about `permit`? And `delivery`? `permissive`? etc.)

  Having SC user **check all that entries in the table in _correct_ way is likely unrealistic**, especially as many of the tags require more elaborate explanation from the wiki; so the quest to me looks too complex for SC (now, if we were talking about Vespucci users, I _might_ be more generous).

Could you give examples of uses cases where access tags only might change in a way that would be easy to verify and mark if changed?

**Comment by RubenKelevra** [comment]
Well, it's more that all access tags I encounter in the database are actually wrong. Either misunderstood tags or misunderstood law is extremely common.

So it's more the case that I like to review the access rights which have no check_date while surveying to make sure it's correct. It's extremely hard to walk around and check access rights with editors like Vespucci. Doing it on the desktop is also hard, as there's low coverage of mapillary here in Germany - as dashcams are basically a grey zone.

Well, this quest is probably not really for beginners but it would be nice if we could add a way to review those tags - worst case as a simple list of key=value for expert users.

**Comment by mnalis** [comment]
Also to note, if the problems is **_misunderstanding_** or tags/laws, just fixing the tags won't help much - even when you fix tags, people will came after you and retag them to "wrong" values, because they will (due to their misunderstanding) think that it is **_you_** who is mapping wrongly. 

So it would be prudent to try to reach all those users - first via local mailing lists / other official communication channels in order to **reach consensus how things should be mapped**, and after that on **changeset comments** (and even `note` tags on nodes/ways if problematic users do not seem to follow the changeset comments)  in order to reach those who mistag. Only after that process is well underway IMHO does it make sense to try to go out fixing old values; otherwise one would be fighting the uphill battle...

**Comment by mnalis** [comment]
For interested parties, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork), does allow for selectively adding (even very complex) access restrictions either via regular quests/overlays, or via custom overlay, e.g.:

![small_Screenshot_20240909_144319_SCEE](https://github.com/user-attachments/assets/52d59200-4eaa-49e6-b602-423432648693) ![small_Screenshot_20240909_144239_SCEE](https://github.com/user-attachments/assets/020ad234-ecac-4dba-a862-193c8bc26827)

The UI however does require that mapper is familiar with OSM tagging (so is not a good match for StreetComplete).
