### ISSUE TITLE
Suddenly surrounded by a large number of invisible footpaths

### ISSUE THREAD

**Issue by pipatron** [streetcomplete/StreetComplete#3124]
Maybe a week ago a lot of quests started showing up for paths that are invisible on the map. Since the paths are invisible, short, and plentiful, they are close to impossible to discern from each other.

I tried to hide these quests but that only uncovers the _Is this stretch of way lit?_ quests which are _not_ possible to hide for paths only.

I feel that I could easily answer all of these if I could just see the paths and how they are located relative to other paths, but right now it's impossible to be sure it's the right path and not for example one 5 metres to the side. Here is an example from my area:

![image](https://user-images.githubusercontent.com/14086495/128407424-c509039a-c5e7-4943-849a-e421bf1af0f5.png)

I suspect this massive changeset is what introduced all these _footpath_ entries: https://www.openstreetmap.org/changeset/108889483

I'm filing this as a bug because I don't think there should be quests available for things that are invisible on the map, so either the quests should go, or the paths should be visible. I would personally prefer if the paths were visible, if possible.

I'm using v33.1 installed from F-Droid, LineageOS (not even sure about the OS version, I can dig that up if you believe it's a local issue)

**Comment by westnordost** [comment]
That is 6 days ago. Actually, the background map should be only 1 day old. Maybe they currently experience server issues. In any case, nothing can be done about that from our side.

**Comment by riQQ** [comment]
See also #2479.

**Comment by pipatron** [comment]
> See also #2479.

Ok, it could perhaps be related to that issue because as mentioned, this happened 6 days ago and I have tried to clear the cache periodically during the week but I'm still getting the same data. I guess I have to wait another week and see what happens.

**Comment by riQQ** [comment]
Clearing the cache doesn't help here afair. You have to clear all data, but then you also lose your settings including the login.

**Comment by pipatron** [comment]
I noticed today that my map is now synchronized with the quests, and it must have happened with the last week or so (I rarely check the map near my house since I've solved most of the quests).

I did not have to clear the cache (in fact, never helped), but just had to wait for what seems to have been at least 2 weeks.
