### ISSUE TITLE
Order of Quest Selection and Priority resets

### ISSUE THREAD

**Issue by GlOwl** [streetcomplete/StreetComplete#3125]
The order of the "Quest selection and Priority" sometimes resets. Might only happen with every new update and when you login to a new OSM account. (The activation of the quest types does not change.)

**How to Reproduce**
Go to "Quest selection and Priority" in the settings change the order.
Afterwards update the app to v33.2 or log in with a new OSM account the order is resetted to default.

**Versions affected**
v33.2

**Comment by matkoniecz** [comment]
Which version you updated from?

**Comment by westnordost** [comment]
It reset once, in v32.0. This was announced in the release notes of v31.1, v31.2 and v31.3
