### ISSUE TITLE
Move to top/bottom for Order of Quests

### ISSUE THREAD

**Issue by GlOwl** [streetcomplete/StreetComplete#3126]
**Use case**
Option to Move a quest type all the way to the top or bottom in the order instantly.

**Proposed Solution**
A double tap on the quest icon in the order&selection menu could open a popup that lets you choose to move to top bottom or cancel the operation.

**Comment by smichel17** [comment]
Note that the ability to re-order quests may be replaced in an upcoming version with the ability to change between quest visibility "Presets". See https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-879866839

**Comment by westnordost** [comment]
Yeah, I'll close this one. In the next version, maybe the new default order will also be more to your liking.
