### ISSUE TITLE
[Quest] Ask if a restaurant/business has air conditioning

### ISSUE THREAD

**Issue by naposm** [streetcomplete/StreetComplete#3127]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Does X have air conditioning?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (*by looking at the "box" outside of the building*)
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Overpass query for restaurants, bars, libraries and apartments, where the answer could be more balanced between yes and no, almost every hotel has air conditioning and the same goes for malls, supermarkets etc.:
```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“(type:way or type:node) and (amenity=restaurant or amenity=bar or amenity=library or tourism=apartment) and air_conditioning!=*”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “amenity=restaurant and air_conditioning!=*”
  way["amenity"="restaurant"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “amenity=bar and air_conditioning!=*”
  way["amenity"="bar"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “amenity=library and air_conditioning!=*”
  way["amenity"="library"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “tourism=apartment and air_conditioning!=*”
  way["tourism"="apartment"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “amenity=restaurant and air_conditioning!=*”
  node["amenity"="restaurant"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “amenity=bar and air_conditioning!=*”
  node["amenity"="bar"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “amenity=library and air_conditioning!=*”
  node["amenity"="library"]["air_conditioning"!~".*"]({{bbox}});
  // query part for: “tourism=apartment and air_conditioning!=*”
  node["tourism"="apartment"]["air_conditioning"!~".*"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Metadata needed:** None, but maybe there are some laws for this

**Proposed UI:** Simple Yes/No quest like the lit way one.

Wiki page for the tag: https://wiki.openstreetmap.org/wiki/Key:air_conditioning
Currently used on 14 594 nodes and 7 693 areas (mainly amenities, so I think restaurants and bars),
Maybe it should be disabled by default settings if implemented.

Some other businesses where this could be useful, based on the amount of time spent there by customers and the fact that they are usually local businesses:
- Convenience stores
- Bakeries
- Variety stores
- Charity stores
- Second hand stores
- Hairdressers (even if almost all of them have it, might still be useful in some cases)
- Lottery shops (lottery tickets shops)
- Stationery shops
- Bookstores
- Gift shops

What do you think? Could this be useful in your opinion?

P.S. Sorry for bringing the issue count to 100 :cry:

**Comment by peternewman** [comment]
I suspect the likelihood of this varies a lot by country too, e.g. in more temperate places it's probably rarer.

**Comment by HaasJona** [comment]
I don't think this is "easily answerable by everyone from the outside". Air conditioning units are often on the backside of the building (that might not be accessible to the public) and at least where I live, they're also often indoors (sometimes visible, sometimes in service areas) with only a vent going outside. 

Often the only indication that they have air conditioning is the indoor temperature when you enter the building on a hot day. Or sometimes their advertisement (that may or may not be false)

**Comment by peternewman** [comment]
> I don't think this is "easily answerable by everyone from the outside".

There are a number of other quests which don't necessarily hit this criteria (e.g. dietary ones), which as @naposm mentioned means it would probably be disabled by default:

> Maybe it should be disabled by default settings if implemented.

**Comment by westnordost** [comment]
A quest like that would be
- by default disabled because users need to go inside
- only enabled in countries where it is reasonable to assume that some businesses have AC, some don't

**Comment by matkoniecz** [comment]
I was thinking about icon - what about snowflake?

If disabled by default - then I think that limiting by country/time is not needed. User can enable it during summer for example.

**Comment by smichel17** [comment]
Icon-- include some squiggly lines to represent blowing air

**Comment by matkoniecz** [comment]
not yet merged into master, but can be already safely closed

**Comment by peternewman** [comment]
> not yet merged into master, but can be already safely closed

I wonder why the fixes tagging didn't do that automatically, unless it only applies to the main branch, which seems a bit odd.

**Comment by matkoniecz** [comment]
> unless it only applies to the main branch

Exactly this
