### ISSUE TITLE
Quest title when resurveying Cycleway's only tagged as cycleway=lane

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3129]
On a way tagged:
`cycleway=lane`

The quest question is correctly "Is this still the cycleway situation here?" but the picture doesn't show any cycleway info.

When the quest is completed, in my case it ends up being tagged as:
```
cycleway:both=lane
cycleway:both:lane=exclusive
```

**How to Reproduce**
See for example:
https://www.openstreetmap.org/way/236840721

**Versions affected**
SC v33.2
Android 9

Looking into the code, it seems it's probably this that's upsetting things:
https://github.com/streetcomplete/StreetComplete/blob/75d6ddf264d27d02c652b696eb7a060efd751528/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/CyclewayItem.kt#L12-L17

Which calls:
https://github.com/streetcomplete/StreetComplete/blob/75d6ddf264d27d02c652b696eb7a060efd751528/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/CyclewayItem.kt#L7-L10

As this will presumably be an `UNKNOWN_LANE`.

I think if some of the logic from:
https://github.com/streetcomplete/StreetComplete/blob/75d6ddf264d27d02c652b696eb7a060efd751528/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCyclewayForm.kt#L110-L112

Was added into `getTitle`, the ambiguity would go away so it was just a normal, non-resurvey, quest.

**Comment by matkoniecz** [comment]
So what you report here is missing prefill of lane on both sides?

**Comment by peternewman** [comment]
Well I thought I was, but then when I dug into the code further, it looks like it can't pre-fill unless `cycleway:lane` is set too, so instead not showing it as a resurvey would at least remove the confusion.

**Comment by westnordost** [comment]
This is not a bug. As you ascertained yourself, "unknown lane" is treated as if it hasn't been tagged yet at all.

It is not possible to do any logic like you suggested in the `getTitle` method.

**Comment by peternewman** [comment]
> It is not possible to do any logic like you suggested in the `getTitle` method.

I'm a bit confused @westnordost , `getTitle` already has:
https://github.com/streetcomplete/StreetComplete/blob/75d6ddf264d27d02c652b696eb7a060efd751528/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L55-L59

How come it can't become something like:
```
    override fun getTitle(tags: Map<String, String>) : Int =
        val countryCode = countryInfo.countryCode
        val sides = createCyclewaySides(tags, false)
        if (sides != null && (sides?.left?.takeIf { it.isAvailableAsSelection(countryCode) } != null || sides?.right?.takeIf { it.isAvailableAsSelection(countryCode) } != null)
            R.string.quest_cycleway_resurvey_title
        else
            R.string.quest_cycleway_title2
```

Or is it some sort of special basic function or something?

**Comment by westnordost** [comment]
Ok, I guess it would be possible to change the wording in that case.

I always found it useful, because if the question is phrased that way, I know that the tag before was incomplete/wrong/weird.

By the way, 
```kotlin
sides != null && (sides?.left?.takeIf { it.isAvailableAsSelection(countryCode) } != null || sides?.right?.takeIf { it.isAvailableAsSelection(countryCode) } != null
````
is really an inconvenient way to write

```kotlin
listOf(sides?.left, sides?.right).all { it?.isAvailableAsSelection(countryCode) == true }
````

**Comment by peternewman** [comment]
> Ok, I guess it would be possible to change the wording in that case.

Thanks.

> I always found it useful, because if the question is phrased that way,

Yeah I can see that point, although without details of the tags, I can't do anything useful with that info or even know if it's SC or the tagging at fault.

IMHO, the ideal compromise would be a little note line inserted below the question in scenarios like this, saying something like "StreetComplete was unable to understand the existing tagging", which would be the best of all worlds.

> I know that the tag before was incomplete/wrong/weird.

While I can see the logic in `cycleway=lane` or  `cycleway:both=lane` not being acceptable on their own, I can also see they'd be very tempting as standalone tags for someone to use.

> By the way,
> 
> ```kotlin
> sides != null && (sides?.left?.takeIf { it.isAvailableAsSelection(countryCode) } != null || sides?.right?.takeIf { it.isAvailableAsSelection(countryCode) } != null
> ```
> 
> is really an inconvenient way to write
> 
> ```kotlin
> listOf(sides?.left, sides?.right).all { it?.isAvailableAsSelection(countryCode) == true }
> ```

Ah that's clever, I'm still very new to Kotlin as you can probably tell!

**Comment by peternewman** [comment]
It looks like it's already covered (as they aren't listed as valid tags), but this should also do the same thing for resurvey of ambiguous ones:
https://github.com/streetcomplete/StreetComplete/blob/71d40086d47265546af3b8dd6dd7c524f5f69a3e/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L346-L351

**Comment by westnordost** [comment]
Ah sorry, wanted to implement this but it turned out it is not possible after all. `getTitle` gets passed just the tags, not the location of the relevant element. Thus, in the `getTitle` function, it is not known where the element the quest refers to is (in which country).

And I wouldn't want to extend the interface for something so unimportant.

**Comment by peternewman** [comment]
I got excited and thought the changes in #3206 might sort it

> Ah sorry, wanted to implement this but it turned out it is not possible after all. `getTitle` gets passed just the tags, not the location of the relevant element.

But I assume they just give you the countryInfo API, still not the location of a particular element.

As a compromise, what if we passed in Belgium all the time, which would at least catch some of the most obvious ones (although probably not the one I reported), or do you not feel that's worth the effort?

**Comment by westnordost** [comment]
That would be a bad hack, I don't do that.

**Comment by peternewman** [comment]
I'd describe it as a partial fix, it would resolve some of the issues, but without fixing all of them which would require the full change.
