### ISSUE TITLE
Add quest for amenity=car_wash details

### ISSUE THREAD

**Issue by Codain** [streetcomplete/StreetComplete#3131]
SC can ask for following details on amenity=car_wash POIs:

- self_service=yes/no
- automated=yes/no
- vacuum_cleaner=yes/no

**Comment by matkoniecz** [comment]
> self_service=yes/no
> automated=yes/no

it is being asked already

> vacuum_cleaner=yes/no

Where it would be bundled with amenity=car_wash? At least in Poland vacuum_cleaner=yes/no is occasionally present on amenity=fuel but is separate from car washes (but my experience here is small)

**Comment by westnordost** [comment]
Additionally, `vacuum_cleaner=yes/no` is a relatively new tag, with miniscule usage. Less than 0.15% of all fuel stations have this tagged at all, so at the moment I'd say that the tag is not widespread enough. Also, I did not really look out for it, but my impression is that just about any fuel station has self service vacuum cleaners (in Germany).

**Comment by westnordost** [comment]
Also, please use the quest suggestion template next time you propose a new quest.
