### ISSUE TITLE
Is this bench lit?

### ISSUE THREAD

**Issue by opk12** [streetcomplete/StreetComplete#3134]
### General
Affected tag(s) to be modified/added: [lit=*](https://wiki.openstreetmap.org/wiki/Key:lit) on [amenity=bench](https://wiki.openstreetmap.org/wiki/Tag:amenity=bench)
Question asked: **Is this bench lit?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose: Usability, safety, privacy
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

This could be an addition to the quests that already ask whether some object is lit, or it could be an entirely new quest.

**Comment by opk12** [comment]
Picnic tables [leisure=picnic_table](https://wiki.openstreetmap.org/wiki/Tag:leisure=picnic_table) may be included, however [taginfo](https://taginfo.openstreetmap.org/tags/?key=leisure&value=picnic_table#combinations) says that `lit` is almost always `no` at the time of writing, so I am not sure about that.

**Comment by 10992-osm** [comment]
How does one determine whether a bench is lit?

Must it have its own dedicated light, or will being alongside a lit street be sufficient?

**Comment by mnalis** [comment]
> Must it have its own dedicated light, or will being alongside a lit street be sufficient?

@10992-osm I would assume (it this quest would be accepted) that both would be `lit=yes`, as was the case in [Is this bus stop lit?](https://github.com/streetcomplete/StreetComplete/issues/2383#issuecomment-752362503)

As for the quality/strength of light, there exists [lit:perceived](https://wiki.openstreetmap.org/wiki/Key:lit:perceived) OSM tag, but StreetComplete doesn't use it currently AFAIK (And/or one might even micromap each individual [highway=street_lamp](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp)).

**Comment by opk12** [comment]
A well-administered city center has well-lit items alongside well-lit streets, but
- Any bench with `covered=yes` may be lit or not, depending on many factors, coverage height and shape, bench-specific lighting, light intensity from around.
- The bench may be the dark spot on a badly lit street, parking, square. `lit=yes` has many meanings - weak lighting from nearby houses, public lighting made weak by trees or excessive distance, bad spots that are not enough to make it worth to cut the way into a lot of pieces. For an area, such as a parking or square, OSM does not even allow to "cut" just to specify where it is lit, if I understand correctly.
- The bench may be the lit spot under a lighting source, on an otherwise dark street, parking, square. Also consider parks, suburbs, foot paths in general, everything that is not a residential road in a city center.

This is complementary to the bus stop lighting quest, for the bus stops that have `bench=separate`.

Similar to the bus stop lighting and the street lighting quests, `lit=yes` does not require a dedicated light source.

**Comment by westnordost** [comment]
As noted, the bus stop lit quest is already a little bit problematic in this regard, because it can be fuzzy. But at least, for bus stops, there are sometimes dedicated lighting, which makes the quest somewhat reasonable to ask. For benches, there will never be dedicated lighting, that lighting will always be from the nearby way.

For footways etc. it is much less fuzzy, because either there are lanterns along the way or not. So I will close this as will not fix as at best, this information is a duplication of information.
