### ISSUE TITLE
Category for Quests

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [streetcomplete/StreetComplete#3135]
**Buildings Quest**

**Streets Quest**

And more...

**Comment by westnordost** [comment]
Why though? In any case, please use the forum https://github.com/streetcomplete/StreetComplete/discussions to toss around loose ideas for improvements. The issue tracker is only for actionable stuff.

**Comment by matkoniecz** [comment]
Also, it sounds like you want what described previously under term "preset" - see "Add quest presets" #1654 and other
