### ISSUE TITLE
Handrail quest: specify the position of the handrail

### ISSUE THREAD

**Issue by opk12** [streetcomplete/StreetComplete#3136]
The handrail is useful or not, depending on one's weak side, so the handrail quest could
- search for `handrail=yes` or absent (it currently only searches for `handrail` absence)
- ask which side the handrail is

### General
Affected tag(s) to be modified/added: `handrail:left`, `handrail:right`, `handrail:center`. [Wiki link](https://wiki.openstreetmap.org/wiki/Key:handrail).

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

The UI could be analogous to the sidewalk quest.

**Comment by Helium314** [comment]
Has anything changed since #2683?

**Comment by opk12** [comment]
Thank you for the link.
