### ISSUE TITLE
Ability to use satellite images

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [streetcomplete/StreetComplete#3137]
With this feature, you can do questions about roads (lanes, surface and ...) and many other quests.

**Comment by matkoniecz** [comment]
it is almost almost implemented - see #2794

though I worry a bit that people would use it to guess answers without surveying

**Comment by Helium314** [comment]
> though I worry a bit that people would use it to guess answers without surveying

Especially this issue implies the user wants to do exactly this...

Is the used background map visible in the changeset?

**Comment by mnalis** [comment]
yes, that's what worries me too, more than little. Perhaps, is satellite map is activated, at least `source=survey` in changeset should be  replaced with `source=satellite` or `source=Esri imagery` or whatever it is using.

**Comment by mnalis** [comment]
As noted in https://github.com/streetcomplete/StreetComplete/issues/3137, there is potential that this feature would likely be used for mapping things not surveyed on the ground. While it is is not necessarily  bad in itself, it does heavily influence decisions made by other mapper (so far, StreetComplete changets could've be assumed to be made from the data visible on the ground, with this PR it is no longer the case - eg. roof type and more might actually be from satellite images).

I think it should **definitely be noted** (eg. by changing changeset  tag from `source=survey` to `source=Esri` or `source=Esri;survey` if map provider was changed from default to indicate the fact)

**Comment by Cj-Malone** [comment]
[imagery_used](https://wiki.openstreetmap.org/wiki/Key:imagery_used) would be a better tag.
