### ISSUE TITLE
Clarify reference number quest

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3140]
This is a scenario where I'm certainly just ignorant. But if I'm confused, then certainly other regular people are confused, so I'll take one for the team and look silly here :)

<img src="https://user-images.githubusercontent.com/6563664/128724561-cdeb6900-d7fd-46a3-9c7d-50b3337df653.png" alt="Sign reading: q30 | Little Neck // MTA | Drop Off Only // | Horace Harding Exp & 224 st" height="500"/> 

I came across a "what is the reference number for this bus stop" quest recently, with a sign like the one in the picture, and answered "q30", since that's the only thing on the sign that really looks like a number/code. But then, a few blocks down, I [came across the pictured sign](https://www.openstreetmap.org/note/2786748), and realized that q30 is actually the number for the bus **route**.

At this point, I realized that I wasn't really sure what I was supposed to be tagging and that I don't know if "reference number" has any more specific meaning in this context besides "number to identify a thing" (e.g. does "reference number for this stop" imply we're talking about the route vs the stop; when I write this it sounds silly, but it was an actual source of confusion…).

I had a similar confusion with the reference number quest a while back, when I was tagging [these berths](https://www.openstreetmap.org/#map=19/42.10606/-72.59498); I wasn't sure whether I should be tagging the berth number or number(s) of the bus routes stopped there. In that case, the berths were clearly marked with a number on the side, so I took a guess that this was the right one; then when SC asked the follow-up quests, like "Is this stop lit?", the little clarifying text above the question said "Berth number N", so I was confident I'd answered correctly.

This experience suggests that a better phrasing for the reference number quest would help with my confusion. Although, I recall an earlier conversation, which I cannot find now, that discussed why only the generic phrasing is used.

**Comment by westnordost** [comment]
To me it looks like the bus stop does not have a ref number, only a name ("Horace Harding Exp & 224 St").

The quest is asked in the US based on the information I got from US mappers that bus stops in the US always have a ref number but only sometimes have a name. I don't remember who said that.

**Comment by westnordost** [comment]
Btw, what does this mean - "no standing"?

**Comment by smichel17** [comment]
> Horace Harding Exp & 224 St

That seems like it would be redundant to tag, since it's just the roads that the stop is located on the corner of. Although maybe helpful for searching.

> information I got from US mappers

I would not have an expectation that this kind of thing is the same in every state, except for federally operated transportation like Amtrak or cross-state bus lines like Greyhound. In _some_ ways the US is more comparable to the EU than any of its members individually.

> Btw, what does this mean - "no standing"?

Beats me ¯\\\_(ツ)\_/¯. I asked someone who lives in New York; I'll let you know when I find out.

**Comment by andrewharvey** [comment]
> Btw, what does this mean - "no standing"?

I guess it means your vehicle on the road can't stand there, ie. you can't bring the car to speed=0 unless held up by traffic or signals. Because otherwise you'd block the bus coming in. At least that's what it means in Australia, I'm not sure about in US.

**Comment by westnordost** [comment]
Anyway, I don't think anything can be clarified with the quest. Reference numbers can be found at extremely different places and have extremely different formats. Or do you have a concrete suggestion for a wording change?

An option "Ref does not exist" already exists IIRC.

**Comment by peternewman** [comment]
> > Horace Harding Exp & 224 St
> 
> That seems like it would be redundant to tag, since it's just the roads that the stop is located on the corner of. Although maybe helpful for searching.

Maybe if they're always on corners. In the UK they are often part way down a road and named after that road. That name is also likely to appear in any timetable, so you could presumably just use a relation to find all the stops on that route and see their names, without having to find the names of the ways they intersect with. But as you've alluded to, that's the bus stop name not it's ref.

> > Btw, what does this mean - "no standing"?
> 
> I guess it means your vehicle on the road can't stand there, ie. you can't bring the car to speed=0 unless held up by traffic or signals. Because otherwise you'd block the bus coming in. At least that's what it means in Australia, I'm not sure about in US.

In the UK, we have bus stands with signs saying "Bus stand only, won't pick up passengers here", for the bus to stand at while there's a gap in it's timetable. It could mean the bus driver isn't allowed to loiter there (in their bus) until it's time to pick up passengers.

**Comment by smichel17** [comment]
> Or do you have a concrete suggestion for a wording change?

Now that you ask, the best I can come up with off hand is, "What reference number identifies this %s?" But I'm not sure that would have helped this case, since I still probably would have answered `q30` until I saw the second sign.

So I guess I will close this as a cannot-fix, since there is nothing to be done and I do not want to propose disabling the quest by default, since it is one that this is particularly important (enables better public transit directions).
