### ISSUE TITLE
New quest: Is this picnic table covered?

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#3142]
### General
Rationale: When hiking (or just walking around the city/countryside) it is nice to know whether a picnic table is covered, for example on very sunny days or when it's raining.

Affected tag(s) to be modified/added: [Key:covered](https://wiki.openstreetmap.org/wiki/Key:covered)
Question asked: **Is this picnic table covered?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
All nodes tagged with [leisure=picnic_table](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpicnic_table)

**Proposed UI:**
Simple yes/no UI, like with "Is this bicycle parking covered"?

**Comment by andrewharvey** [comment]
+1 if possible quest selection would ignore where it's spatially inside or on the same way/node as a building=roof or amenity=shelter which both would already imply covered.

**Comment by westnordost** [comment]
It would be asked independent of that.

**Comment by Helium314** [comment]
If this quest gets implemented, it should be clear whether the cover is supposed to protect from sun or from rain.
I've very rarely seen picnic tables that were sufficiently protected from rain to stay dry while sitting (on the bench).

**Comment by westnordost** [comment]
As far as I know, `covered=*` is for covered against weather, i.e. rain.

**Comment by mnalis** [comment]
Yes, I agree, `covered=*` is for protection against rain/snow/hail (cover can be glass / plastic / acrylic too). 

(Related: there is also https://wiki.openstreetmap.org/wiki/Key:shade for mapping protection from sun.)
