### ISSUE TITLE
StreetComplete devel version in ShowQuestForms has some incomplete quests

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3145]
Devel build contains useful Debug section, with `Show Quest Forms` which in nice for debugging what quest forms do, and checking translations etc. Some forms (which make use of searching _iD presets_?) however do not behave the same as the real quest, eg. they miss major part of the functionality that quest has. 

It would be nice if those quests too would offer full functionality, as then people could check how things work  (like https://github.com/streetcomplete/StreetComplete/issues/2643) without creating fake nodes in OSM to serve for test.

**How to Reproduce**
- build and install devel version of StreetComplete
- go to `menu` / `Settings` / `Debug/Show Quest Forms`
- click on `What type of shop is this` or `This shop has been vacant. What's there now?`
- click to `A(n)...` and some shop name like `shoe`
- notice that  it **does not show** as-you-type dropdown, which is different than what real form does

**Versions affected**
v33.2-devel (with [few patches](https://github.com/mnalis/StreetComplete/releases/tag/v33.2-mnalis-questprofiles-helium314) which should be unrelated)

**Comment by westnordost** [comment]
Won't fix
