### ISSUE TITLE
(When no GPS signal) clicking GPS button does not return to North, even when follow-me is disabled

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3147]
If there is **no GPS signal**, clicking Compass button misbehaves, as SC does not seem to disengage follow-me mode in such situation (usually follow-me is enabled by clicking `GPS` icon, and disabled by scrolling the map).

**What I would expect**
- when no GPS signal (and especially if I moved the map manually), follow-me mode should be **disengaged**, so pressing compass icon first time should rotate **North to point up** (it works that way when GPS signal is strong)

**What actually happens**
- when no GPS signal, **even after moving the map manually**, follow-me mode **refuses to disengage**, and pressing compass button only switches between 2D/3D, never rotating the map to north again

**How to Reproduce**
- Start SC in area where there is no GPS signal
- move map to disengage possible [follow-me mode](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_to_use_2D.2F3D_and_GPS_following.2Frotation.3F)
- click on Compass, expecting it would rotate map to "North is up"
- see it instead engages 3D follow-me mode, and that it will never rotate to "North is up" no matter how many times you press it (until you regain GPS signal strength)

Video example:

https://user-images.githubusercontent.com/156656/128779388-2f41d446-17c9-40cd-aa03-2fa06974ff82.mp4

**Versions affected**
EMUI 11 (Android 10), StreetComplete v33.2

**Comment by smichel17** [comment]
I noticed a possibly-related bug the other day: when I previously had a location fix, then turned off location services (the dot no longer appeared on the map), when I scrolled my previous position off screen, "current location direction" pointer would still appear. Fixed by closing the app completely (swiping away from recents) and re-opening.

Back to this bug: I can reproduce it. I'll look into both sometime soon (maybe over the weekend?).

**Comment by smichel17** [comment]
Okay, so there's a few parts to this bug.

1. The bug @mnalis reported with the compass — fixing this was easy, done in #3166.

2. When location services are turned off, it doesn't automatically turn off compass mode. This should also be an easy fix.

3. When location services are turned off, some part of this is not propagated to the part of the app that displays the location pointer pin. Needs a little more research.
