### ISSUE TITLE
Immediately resurvey any incomplete cycleway tagging

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3148]
**Use case**
Off the back of #3129 it's clear some common cycleway tagging is incomplete for example `cycleway=lane` or `cycleway:both=lane`  without a valid `cycleway:both:lane` value, we could fix this immediately, we don't need to wait for a resurvey time period to expire.

**Proposed Solution**
Expand the existing element search logic to use the isAvailableAsSelection function to filter partial tagging and show it for resurvey immediately too.

**Comment by westnordost** [comment]
This should only be done for clearly incomplete tagging though. Not tagging that the app does not understand.

**Comment by peternewman** [comment]
I assume you mean so it would ask for say:
`cycleway=shared_lane`

But not (as it just doesn't understand foo):
```
cycleway=shared_lane
cycleway:lane=foo
```

Like a tweaked version of hasOnlyKnownCyclewayTags:
https://github.com/streetcomplete/StreetComplete/blob/71d40086d47265546af3b8dd6dd7c524f5f69a3e/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L373-L385

It looks like this could also usefully mop up the ambiguous ones too:
https://github.com/streetcomplete/StreetComplete/blob/71d40086d47265546af3b8dd6dd7c524f5f69a3e/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L346-L351

**Comment by westnordost** [comment]
Somehow I continuously underestimate the effort of your enhancement suggestions. Anyway, here it is, but it would be good if someone else would review this code: #3206

**Comment by smichel17** [comment]
> Somehow I continuously underestimate the effort of your enhancement suggestions

Seems not a coincidence that they're often related to handling tagging corner cases.

**Comment by peternewman** [comment]
Sorry I'm clearly repeatedly so awkward! :laughing: :nerd_face:
