### ISSUE TITLE
Use the biggest/smallest address as appropriate when using the address +/- buttons

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3149]
**Use case**
If you tag a pair of semi detached houses or a terrace with multiple house numbers (e.g. ~12-14~ or 21,19,17), currently it just appears to take the first (or last) number it parses when you press +/- to number the next property.

**Proposed Solution**
Store the biggest (14/21) and smallest (12/17) values separately from the parsed house numbers and use the appropriate ones to suggest the next house i.e. 11/16 for - or 15/22 for + in my examples.

**Comment by westnordost** [comment]
Can not reproduce.

**Comment by westnordost** [comment]
Please provide some examples `addr:housenumber` for which it does not work.

**Comment by peternewman** [comment]
> Complication: 12-14 might be the full address, not "houses twelve through fourteen". In New York City, the first number often indicates which street/avenue it is between ([example](https://www.openstreetmap.org/#map=19/40.74891/-73.74806)). So in that case, I'd rather if `12-14` were incremented to `12-15`.

Yeah I just gave that as an example (which admittedly I didn't test), I know I'd seen the issue, but couldn't remember exactly where.

Personally I try and avoid it due to the ambiguity, especially if I actually mean 12 and 14 but not 13.

> I don't think there's a way to do the right thing in all situations, so just let's pick the one that does the best overall.

:+1: 

I do accept if you were tagging both sides of the street at once (with odds/evens split) then in *some* circumstances, this behaviour may be useful, but only if the numbers aren't clockwise around a cul-de-sac and are equally offset.

> Please provide some examples `addr:housenumber` for which it does not work.

Tag `12,10`
Hit + on the next house
Get 11

Tag `12,10`
Hit - on the next house
Get 11!

`10,12` works correctly incrementing and decrementing as does `12-14`.

With my second made up original example, I get an even more unusual behaviour:
Tag `21,19,17`
Hit + on the next house
Get 18

Tag `21,19,17`
Hit - on the next house
Get 20!

Likewise with `21-17`.

FWIW, I do this where it matches the order of the houses (from left to right as that's how English is written).

**Comment by westnordost** [comment]
Can you explain why one would tag housenumber ranges in descending order? I never did that and I am not sure if such tagging should be expected.

**Comment by peternewman** [comment]
> Can you explain why one would tag housenumber ranges in descending order?

> FWIW, I do this where it matches the order of the houses (from left to right as that's how English is written).

So given houses numbered like this in a terrace:
`21 19 17 15`
I would tag them as:
`21,19,17,15`

To give you a hint which end of the block the number you want may be.

Also in particularly long runs of numbers, it's far easier and less risk of errors inputting them as I walk along (if I'm walking the right way).

> I never did that and I am not sure if such tagging should be expected.

I didn't spot anything in the wiki recommending it, or equally advising against it.

**Comment by westnordost** [comment]
Okay, that was much more effort than expected... wouldn't have done it if I knew before. But now, it works with any weird combination:

`21/4, 4c` +: 22 -: 3
`18a-12d, 2, 6-8` +: 19 -: 1
etc

**Comment by westnordost** [comment]
Actually, I changed it so that reverse ranges (f.e. `16-2`) are interpreted to mean basically the same as `16/2`

**Comment by peternewman** [comment]
> Okay, that was much more effort than expected... wouldn't have done it if I knew before. But now, it works with any weird combination:

Thanks for that @westnordost and sorry for finding an awkward one!

> Actually, I changed it so that reverse ranges (f.e. `16-2`) are interpreted to mean basically the same as `16/2`.

Ah cool, I was a bit confused about one test case, but I guess that makes sense from what @smichel17 said.

From looking at the tests, I'd think these should also be true:
4<4c
4c<5

But I appreciate you might not want to deal with that level of complexity!

**Comment by peternewman** [comment]
Very true, I didn't know if it would upset the sorting/max stuff if the values weren't comparable and if it might just discard them?

e.g. `2, 4, 6A, 6B` should give +7, -1

**Comment by westnordost** [comment]
> e.g. 2, 4, 6A, 6B should give +7, -1

yes
