### ISSUE TITLE
Quest: Is this cycle barrier traversable by bicycle?

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3151]
### General

This quest would enhance [`barrier=cycle_barrier`](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier) with information regarding [bicycle access](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier#Bicycle_access), i.e. one of:
- [`bicycle=no`](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dno)
- [`bicycle=dismount`](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddismount)
- [`bicycle=yes`](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dyes)

Question asked: **Is this cycle barrier traversable by bicycle?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [X] 🚧 To be added tag is established and has a useful purpose: [34'195](https://taginfo.openstreetmap.org/tags/barrier=cycle_barrier#combinations) nodes are tagged with both `barrier=cycle_barrier` and `bicycle=*`. The information is useful for bicycle routing, especially for cases with [`bicycle=dismount`](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddismount) and [`bicycle=no`](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dno), where alternative routes are needed.
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one): Yes, see above
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: the question can probably not reliably be answered using aerial imagery, traversability should be determinable by almost all people
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam): Of the 34'195 with `bicycle=*`, 28'408 = **83% have `bicycle=yes`**, not sure if this is spamming...
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort): `barrier=cycle_barrier` is used [97'894 times](https://taginfo.openstreetmap.org/tags/barrier=cycle_barrier#overview), i.e. **63'699 cases would need surveying**: Is that a large enough number?

### Ideas for implementation

**Element selection:** Overpass snippet: [`node["barrier"="cycle_barrier"][!"bicycle"]({{bbox}});`](https://overpass-turbo.eu/s/1acg)

**Metadata needed:** Probably not needed.

**Proposed UI:**
- Yes
- Dismounting is needed
- No

(including pictures)

**Comment by westnordost** [comment]
Isn't the point of a cycle barrier that it is not?

**Comment by westnordost** [comment]
Okay, actually, I will close this.

There are different sizes of bicycles (Rennrad vs Lastenrad), so it's not possible to blanket say that it is not or that it is traversible. What is necessary are the actual layout and distances of the barrier.

You may be interested in looking at and voting for this proposal: https://wiki.openstreetmap.org/wiki/Proposed_features/Advanced_cycle_barrier_tagging

**Comment by andrewharvey** [comment]
> There are different sizes of bicycles (Rennrad vs Lastenrad), so it's not possible to blanket say that it is not or that it is traversible. What is necessary are the actual layout and distances of the barrier.

![2021-08-11_23-31](https://user-images.githubusercontent.com/117278/129038146-5e2d12fa-2048-4881-ae00-21c45015c272.png)

**Comment by mnalis** [comment]
@andrewharvey nice picture, although [recumberants](https://en.wikipedia.org/wiki/Recumbent_bicycle) are missing

**Comment by andrewharvey** [comment]
Yeah I don't know why they left that out, in the same [document](https://www.transport.nsw.gov.au/system/files/media/documents/2021/Cycleway-Design-Toolbox-Web.pdf) I got this from they mention recumbents later in typical sizes.

![2021-08-12_07-28](https://user-images.githubusercontent.com/117278/129105965-d551a297-6498-4edc-9c17-0e893d8930ca.png)

**Comment by Kovoschiz** [comment]
Out of curiosity, what's the project's view on `bicycle=dismount`? It is in dispute with `bicycle=no`. https://wiki.openstreetmap.org/wiki/Tag:bicycle=dismount

**Comment by matkoniecz** [comment]
> Out of curiosity, what's the project's view

Issues on issue tracker are a poor place for open ended discussion

**Comment by Kovoschiz** [comment]
> 
> 
> > Out of curiosity, what's the project's view
> 
> Issues on issue tracker are a poor place for open ended discussion

The fact that this tag isn't rejected in closing this issue was a worrying sign it is not a concern. Now that I read https://github.com/streetcomplete/StreetComplete/issues/2760#issuecomment-898546177 I'm reassured.

**Comment by mnalis** [comment]
@Kovoschiz I don't quite get what is a concern for you here?
- whether some tag is good idea or bad idea, and should it be used by OSM community or not, is something that gets discussed on [Tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list) and then (hopefully) documented on specific OSM wiki page (like [Tag:bicycle=dismount](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddismount), and *not* on StreetComplete github issue tracker. So those are the places you should be looking at, not here.
- Now, if StreetComplete is doing something that OSM community has decided is a **bad idea** (in places listed above), then you would open an issue here in StreetComplete github issue tracker. However, quick looks tells me that StreetComplete **does not seem to be doing anything with that tag specifically**, so I don't understand why would you ask here about it?
```
% cd StreetComplete
% fgrep -r dismount app/src/main/{java,res}
%
```
