### ISSUE TITLE
Feature request double click

### ISSUE THREAD

**Issue by Tauvic** [streetcomplete/StreetComplete#3152]
Please when selecting a street pavement. Add DoubleClick support to make updates faster

**Comment by smichel17** [comment]
What would you double click on? What would you expect to happen when you double click?

**Comment by Tauvic** [comment]
For example specify road surface requires selection of a specific road
surface image, then move down and press ok to confirm

Some other selections have even bigger lists of options and large amounts
of movement.

Just double click and that confirms your selection.

**Comment by westnordost** [comment]
Move down? You mean, move your thumb down, you don't need to scroll.

A double-tap would likely result in many answers given by accident, so this will not be implemented. A double tap is also not something that is common in smartphone UI (long-tap is).
