### ISSUE TITLE
More clearly signpost option to change shop type

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3153]
I've been looking through StreetComplete notes and have found quite a few times where people have said they are unable to answer the opening hours quest and their comment is that something else is there instead (saying what it is).

Maybe change the option in other answers from "It does not exist" to "It does not exist or there is something else here" or something like that so that people can more clearly see that that's an option.

**Comment by westnordost** [comment]
That's too long.  The answer options inthe menu must be very short. Also, it sounds a bit redundant. The question asked is about that particular shop, to answer that this particular shop does not exists sounds reasonable. Maybe a language issue?

**Comment by arrival-spring** [comment]
Maybe, these were all in the UK and I don't think I checked but I presume they would all/most be native English speakers.

I can see why it might not be obvious, especially if you're asked about a building I'd be thinking that it does exist, it's just there's something else there now.

Not sure how best to rephrase my suggestion to be shorted but retain the meaning though.

**Comment by westnordost** [comment]
But one is not asked about a building in this case, but about a shop of some sort.

**Comment by arrival-spring** [comment]
When a shop is tagged on a building (rather than just a node) it can feel like it's asking about the building.

It's not a huge issue, but I did come across several notes from different people who seemed to have not spotted the option. Obviously I replied to point it out for them.

**Comment by westnordost** [comment]
That option also doesn't exist for that long. Maybe they didn't know about it yet (or the note is already old). I'll close this issue for now, as no clearer wording suggestion that is at the same time still short has been found.
