### ISSUE TITLE
Add Showcase: Organic Maps

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#3154]
Organic Maps is a quite new Android App which offers a pretty wide variety of features and is based on OpenStreetMap data.

I think it's worth a showcase:

https://organicmaps.app/

**Comment by matkoniecz** [comment]
To be more exact, it is MAPS.ME fork made with involvement of some original authors, with various unwanted, ugly parts (that were intended to extract some money from users) being removed.

**Comment by westnordost** [comment]
And its open source and has proper attribution to OpenStreetMap. Looks like a good candidate.
