### ISSUE TITLE
Don't ask for roof shapes that likely involve guessing

### ISSUE THREAD

**Issue by timor** [streetcomplete/StreetComplete#3155]
Problem: Standing right next to a building, being asked for the roof shape is either hard or impossible to answer correctly in a surprising number of cases.

The cases I experienced basically boiled down to standing too close to a building (depends on building height and/or levels) and a rather flat roof shape. This concerns all roof shapes which are not gabled and which can be very flat.

Possible improvements that come to mind:
- Depending on building height/levels, don't ask for roof shapes inside a certain radius of the current position
- Don't ask for all roof shapes, but precede a question like "Does this building have a gabled roof".
- Provide an answer choice like "Cannot see clearly from my current position"/"Must be identified from further away".
- Based on user position, add a "Are you sure you could distinguish all possible roof shapes"-kind of like confirmation if the user is likely to be too close to a high building/difficult roof shape.

These Ideas are only based on the UI, I don't have any idea how feasible this is from a data point of view.

(from https://github.com/streetcomplete/StreetComplete/issues/2609#issuecomment-897872446)

Used Version: StreetComplete 33.2 on Android 10

Edit: added fourth idea for improvement

**Comment by Helium314** [comment]
I don't think this makes sense... it's like not hiding the opening hours quest when you're too far away to read the sign. 
StreetComplete does not force you to answer the quest from your current position.

Plus, making this based on position will likely be not feasible. In my experience being close to tall buildings noticeably distorts GPS signal, and thus your position may easily be off by some 20 m.

**Comment by timor** [comment]
> I don't think this makes sense... it's like not hiding the opening hours quest when you're too far away to read the sign.
> StreetComplete does not force you to answer the quest from your current position.
It does ask for confirmation though when you want to answer a question which is a bit further away from your position.  So I think this would also fall into the "Are you sure you actually took a good look at this?" category.

> Plus, making this based on position will likely be not feasible. In my experience being close to tall buildings noticeably distorts GPS signal, and thus your position may easily be off by some 20 m.
True.  Sometimes I need to be quite a bit further away though, more around 100 m or so, to be able to identify the roof of a building with 3 levels.

**Comment by Helium314** [comment]
> It does ask for confirmation though when you want to answer a question which is a bit further away from your position. So I think this would also fall into the "Are you sure you actually took a good look at this?" category.

Hmm right, a similar question when you're really close would make sense.

> True. Sometimes I need to be quite a bit further away though, more around 100 m or so, to be able to identify the roof of a building with 3 levels.

For nearly flats roofs definitely, but for most roofs in my area 20 m is enough. So it will be hard to define some "universal" good distance...

**Comment by timor** [comment]
> For nearly flats roofs definitely, but for most roofs in my area 20 m is enough. So it will be hard to define some "universal" good distance...

Yes, and if you base it on position, then height would also have to be factored in, theoretically.  I guess any kind distance threshold would be very conservative.

**Comment by matkoniecz** [comment]
My main problem here is that in many cases being very, very close to building still allows you to answer it.

In some cases I went around and answered while being close to a building or even inside.

**Comment by timor** [comment]
> My main problem here is that in many cases being very, very close to building still allows you to answer it.

I agree.  The idea is to try to find out whether these cases can be distinguished in a practical manner based on building data, requested roof data, and/or viewer position.
 
> In some cases I went around and answered while being close to a building or even inside.

Do you mean based on sight at that moment, or based on memory?

**Comment by matkoniecz** [comment]
> Do you mean based on sight at that moment, or based on memory?

I looked around, remembered how it looks like and counted levels - and entered data while in an elevator inside (or while waiting in a queue)

**Comment by westnordost** [comment]
Maybe the roof type quest should be disabled by default, with a message like "sometimes difficult to see and adds a massive amount of quests".

The information itself is very unimportant (almost exclusively 3D-rendering, and at that, not even precise one) and also at the same time often easier to acquire from satellite imagery.

**Comment by matkoniecz** [comment]
It is also quite confusing - especially as it is not often clear which shape should be considered as basic for a given roof.

**Comment by westnordost** [comment]
I'll close this one as will not fix then.
