### ISSUE TITLE
New Quest : Addition of information on existing telecom street cabinets. (street_cabinet=telecom)

### ISSUE THREAD

**Issue by u4y0u** [streetcomplete/StreetComplete#3157]
### General
Affected tag(s) to be modified/added: [Operator](https://wiki.openstreetmap.org/wiki/Key:operator)  [telecom / telecom:medium] (https://wiki.openstreetmap.org/wiki/Key:telecom:medium)

[ref](https://wiki.openstreetmap.org/wiki/Key:ref)
OR
[telecom / ref:FR:ARCEP](https://wiki.openstreetmap.org/wiki/Key:ref:FR:ARCEP) (fibre france)
OR
[telecom / ref:FR:PTT](https://wiki.openstreetmap.org/wiki/Key:ref:FR:PTT) (copper france)
OR
.... other Country

Question asked: What is the name of the operator?
Answer: a text value that can be entered manually or chosen from a list depending on the country.

What type of medium is used? 
Answer: a text value which can be chosen among three values currently (fiber, copper and coaxial)

What is the reference? 
Response: an alphanumeric value greater than two characters minimum or NC = not known or without label.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation
Examples of images to recognize the operator:
https://wiki.openstreetmap.org/wiki/Key:ref:FR:SFR
https://wiki.openstreetmap.org/wiki/Key:ref:FR:Orange

Examples of images for retrieving the ARCEP reference :
https://wiki.openstreetmap.org/wiki/Key:ref:FR:ARCEP 
Examples of images to recognize the logo on the fiber cabinet:
https://wiki.openstreetmap.org/wiki/File:ISO_7010_W004.svg
Examples of images to recognize a copper cabinet:
https://wiki.openstreetmap.org/wiki/Key:ref:FR:PTT

**Element selection:** 
telecom:medium=fibre OR telecom:medium=copper OR telecom:medium=coaxial

**Metadata needed:** 
What is the ARCEP reference? *[France]
Response: an alphanumeric value greater than two characters minimum or NC = not known or without label.

**Proposed UI:**

**Comment by flacombe** [comment]
Hi Eric

This is a really good one, thank you.

I currently can't use StreetCOmplete properly due to a bogus phone, I'm not used of quests asking questins with free text answers.
That could be a good start to collect refs. However I'm not sure regional or national particularisms could be easily included in a worldwide scope application like street complete.

**Comment by u4y0u** [comment]
The strings (strings.xml) can be different depending on the country configured in the Android development, so we can reasonably ask questions adapted to the country and put answers in the corresponding specific tags.
The only question lies in knowing each specificity of the country concerned.

**Comment by arrival-spring** [comment]
What sort of thing is this data used for?
Most people don't have much interaction with street cabinets, so it doesn't affect them what the operator is or what the reference is surely?

**Comment by 10992-osm** [comment]
How does one find out the operator, or the medium?  Where I live (England), I don't think it's very obvious a lot of the time, though you sometimes get stickers on some boxes advertising that fibre is now available.  I think you can often see a number though, which might help to identify the operator, but I don't know how to read it.  Maybe I'll take some photos next time I see one.

**Comment by matkoniecz** [comment]
> What sort of thing is this data used for?

Is there even a potential use? (beyond "it can be 3D rendered")

**Comment by flacombe** [comment]
At least in France, such data has following potential use:
* Public domain occupancy inventory, for cities administration inspecting how pavements or other various public space are occupied (very lack of knowledge on those topic in many places)
* Operational usage for technicians using mobile apps with OSM data to find their daily working premises better than any operator internal dataset could enable them to (Each day, weeks of time are lost searching for the right address).
* OSM could become a reliable database to be used in public disturbance signaling applications, offered to citizens to warn their public administration or operators about ongoing situations or destroyed equipment in streets. Such cabinets are often subject to such problems: https://twitter.com/u4y0u/status/1147764634872623105?s=20
Currently available solutions aren't so usable without contextual data about concerned equipments
* Etc.

**Comment by 10992-osm** [comment]
> At least in France, such data has following potential use:
> 
>     * Public domain occupancy inventory, for cities administration inspecting how pavements or other various public space are occupied (very lack of knowledge on those topic in many places)
> 
>     * Operational usage for technicians using mobile apps with OSM data to find their daily working premises better than any operator internal dataset could enable them to (Each day, weeks of time are lost searching for the right address).
> 
>     * OSM could become a reliable database to be used in public disturbance signaling applications, offered to citizens to warn their public administration or operators about ongoing situations or destroyed equipment in streets. Such cabinets are often subject to such problems: https://twitter.com/u4y0u/status/1147764634872623105?s=20
>       Currently available solutions aren't so usable without contextual data about concerned equipments
> 
>     * Etc.

Is OpenStreetMap the best place to maintain a database of public infrastructure, though (in detail beyond the existence/location of something)?  If yes, is StreetComplete the best tool for that?  I'd say this quest is not usable **in the UK**, since I don't believe this information is obvious enough from the outside that it can be done by someone with no knowledge of such installations.

I do not think that 

> Easily answerable by everyone from the outside but a survey is necessary

is met, really.

You might be able to get a ref, but an operator is pushing it, as the cabinets are generally blank (though most will be [Openreach](https://en.wikipedia.org/wiki/Openreach "Openreach on Wikipedia"), except in [Hull](https://en.wikipedia.org/wiki/KCOM_Group "KCOM Group on Wikipedia"), with some [Virgin](https://en.wikipedia.org/wiki/Virgin_Media "Virgin Media on Wikipedia"), with some other operators perhaps in rural areas that Openreach deems unworthy of faster internet).  The cable type will mostly be unknown.

**Comment by u4y0u** [comment]
Hello,
For the question on the location of fiber street cabinets in other countries.
It is true that in France, the yellow triangular danger warning logo helps to easily ensure that we are dealing with a fiber cabinet.
I don't think this is a problem in other countries for several reasons:
These cabinets are recent and leave traces of new installations on the public domain (recent trenches, repair of the sidewalk, etc.)
The cabinet model is often very similar from one city to another, or even is the subject of a public market at the country level.
These cabinets are sometimes clearly identified with signs (advertising for the operator or other)
example: https://www.alamy.com/stock-photo-a-bt-openreach-fibre-broadband-street-cabinet-49131962.html

**Comment by u4y0u** [comment]
For the question on the use of data by the public:

In France, the authority in charge of communications (ARCEP) makes this map available to the public: (link pointing to Paris in the example)
https://cartefibre.arcep.fr/index.html?lng=2.3521017600280345&lat=48.85651799074185&zoom=17.4808865580665&mode=normal&legende=true&filter=true&trimestre=2021T1
As we can see, each green point is a fiber dwelling and a click on the point allows you to know the reference of the cabinet (ref: FR: ARCEP) but not its location.
Here is therefore a useful addition to the public who wants to know the place of are connection in case of dysfunction to give possible details.
Each link in the chain, from the customer to the operator's subcontractor, can use this information easily and therefore intervene quickly, whether for creation or maintenance.
The municipalities or local state service can also use this information to deduce the number of customers and the impacted area in the event of a problem with the street equipment. This principle is valid in any country.

**Comment by u4y0u** [comment]
For the question:
"Is OpenStreetMap the best place to maintain a database of public infrastructure ...
I do not think that."

I would be careful not to answer this question, which is a huge debate. I would therefore limit myself to citing a few other keys which were created to be used and filled in as well as possible and where there are identical or similar reference fields, of which the public does not seem to have a direct use but which are nevertheless numerous and well. entered in the OSM database:
charging_station (operator, network, capacity, ref ...)
post_box (operator, ref)
man_made = pipeline (ref diameter pressure ...)
substation (operator ref substance ...)
marker (operator utility ref ...)
I forgot many others ;-)

**Comment by flacombe** [comment]
> Is OpenStreetMap the best place to maintain a database of public infrastructure

Yes it does, as any visible infrastructure with interaction with other features in the environment.

> You might be able to get a ref, but an operator is pushing it, as the cabinets are generally blank

Then how does technicians are supposed to know it's the one they should work in?
We've got that problem in France, technicians get confused in front of a row of blank cabinets, and choose the wrong one. True story.
Sometimes, reference and operator signage are mandatory by law as well.

> It is true that in France, the yellow triangular danger warning logo helps to easily ensure that we are dealing with a fiber cabinet.

It's an ISO 7010-W004 sign, recognized worldwide.

**Comment by westnordost** [comment]
See @10992-osm. I doubt that this is easily answerable by anyone. And with anyone, I do mean people that are not technicians that work for the telecom network

> What type of medium is used?

How would that be visible from the outside?

> What is the name of the operator?
> What is the reference?

There may be many numbers on such a box. Which one is the ref? Which one is the operator?

---

To be honest, as a layman, I always thought that these boxes are from the power network or something. See, this is how far the ignorance goes, even from a fellow mapping nerd.

**Comment by Helium314** [comment]
> > What type of medium is used?
> 
> How would that be visible from the outside?

As far as I understood `fiber` must have the laser warning sign, so that would actually be easy to identify.
But coaxial or copper? The linked example for copper is just blank except for the letters _SEM_

> What is the name of the operator?

The image in https://wiki.openstreetmap.org/wiki/Key:ref:FR:SFR (linked as example how to recognize the operator) looks very confusing. I wouldn't be able to extract the correct answer _SFR_ from the image.

> What is the reference?

Seeing the reference number examples, I would actually just disable the quest if there is no auto-complete or other help. Typing such a rather long "meaningless" (for the user) text is prone to errors.

Are there any universal patterns in the reference numbers (maybe per country or operator)?

**Comment by matkoniecz** [comment]
> As far as I understood fiber must have the laser warning sign, so that would actually be easy to identify.

I have never seen it on any outdoor equipment in Poland and we have decent amount of fiber. Maybe it hold true in France?

**Comment by flacombe** [comment]
Indeed, ISO laser sign could inform mappers that a given cabinet is dedicated to FTTH service.
This is recommended on https://wiki.openstreetmap.org/wiki/Tag:telecom:medium%3Dfibre

We are dealing with connection points. As many networks, cabinets have a shape adapted to the service they host as to ease technician's work.
As you may read on https://wiki.openstreetmap.org/wiki/Tag:telecom%3Dconnection_point, shapes a distinguishable from copper to fibre.
This because contracts are made with furniture providers so th look are often the same for a given network, which roll out began at a given period.
It is possible to document in wiki as many cabinet shape as they exist in reality.

Operators are often signed on cabinets. On connection points cabinet, you'll see BT (now Openreach), Orange (https://wiki.openstreetmap.org/wiki/File:French_orange_ftth_id.jpg)...

Finally, there are indeed official regulatory framework for network points codification
Here are some in France
https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:ARCEP (link to government documentation at the bottom)
https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:Orange
https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:SFR

**Comment by flacombe** [comment]
> I see this as too technical for the average user.

Aren't users able to choose the quest they use depending on their interests?

As I understand this proposal will be dismissed because it exists some situations where information isn't visible and should be deducted from public policies?
That's not fair regarding every else moments when the operator logo is visible for instance.

Instead, we should be happy to find use cases where consistency can be checked among contradictory inputs (logo and ref for instance). Users could be provided with useful hints to refine their survey.

**Comment by mnalis** [comment]
> There may be many numbers on such a box. Which one is the ref? Which one is the operator?

Agreed; it is problematic for regular users, see https://github.com/streetcomplete/StreetComplete/issues/3059 for similar example too (`fire_hydrant`). 

Regarding street cabinets in particular, in Croatia, the cabinets too are mostly not marked whose they are (much less what is their purpose). I guess operators have their own database with locations of where their stuff is (and even more importantly, how/where it's interconnected/uplinked)

> To be honest, as a layman, I always thought that these boxes are from the power network or something. See, this is how far the ignorance goes, even from a fellow mapping nerd.

Obligatory [xkcd comic](https://xkcd.com/2501)

**Comment by flacombe** [comment]
> Obligatory xkcd comic

I wonder why we spent years to write documentation if we should assume that people won't read it.
The same as making maps and assume people won't use them.

It regularly comes to my mind that applications like StreetComplete help us to deal with ambient complexity. Why should we refrain from helping mappers to collect more detailed information if they would be lost on their own?

**Comment by Helium314** [comment]
> It regularly comes to my mind that applications like StreetComplete help us to deal with ambient complexity. Why should we refrain from helping mappers to collect more detailed information if they would be lost on their own?

From [quest guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete): _Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary_
Users can't be expected to know which shape of street cabinet (typically?) contains `copper` and which `coaxial` (this is already assuming `fiber` is always correctly signed)
Users can't be expected to be able to extract `SFR` from the given operator example.
Users can't be expected to read anything of the documentation.

The only part that appears to be always answerable without any further knowledge would be the reference.

**Comment by flacombe** [comment]
> Users can't be expected to know which shape of street cabinet (typically?) contains `copper` and which `coaxial` (this is already assuming `fiber` is always correctly signed)

That's not what is expected here.
Picture comparison will be enough.
This one is always `copper`: https://wiki.openstreetmap.org/wiki/File:French_copper_PCP.jpg
Relevant question is not `Are you aware of medium running in this cabinet?` but `Is that what you see?`
Mappers won't even be aware of streetcomplete putting telecom:medium=copper on the node they complete.

> Users can't be expected to be able to extract SFR from the given operator example.
No indeed. Just identifying a logo if it is visible on the cabinet.
The logic to extract SFR from the ref is for developers, not mappers.

Challenge is to adapt proposed possibilities to user's location and get an extensive inventory of possibilities.

**Comment by mnalis** [comment]
@flacombe  apart from problems mentioned earlier, it also seems to be very specific to one specific country. StreetComplete quests IMHO works best if the same quest with same answers is in all countries. I do not think SC even supports different per-country logic at all (apart for disabling quest for some countries - I could be wrong there, though). 

> Then how does technicians are supposed to know it's the one they should work in?
We've got that problem in France, technicians get confused in front of a row of blank cabinets, and choose the wrong one. True story.

That is the additional problem, then - how would the user know which cabinet (s)he is providing answer for, if there are few of them in a row (as mentioned above)? StreetComplete currently lacks support for showing nearby cabinets and similar quest requirements  (this problem exists for several other quests, for example https://github.com/streetcomplete/StreetComplete/issues/3174#issuecomment-900049972). And without support for it, users would be answering randomly when there are multiple cabinets at nearby locations, which would likely be worse than no answers at all.

**Comment by matkoniecz** [comment]
>  I do not think SC even supports different per-country logic at all

There is some special display of road traffic signs in maxheight and maxweight quest and some quests are enabled/disabled based on a country.

**Comment by flacombe** [comment]
> That is the additional problem, then - how would the user know which cabinet (s)he is providing answer for, if there are few of them in a row (as mentioned above)?

Mappers aren't always knowledgeable about operational problems ones may endure. Value of OSM contribution is different: when they collect visual signs from ground, mappers help a large diversity of people to get prepared or compute information with a more extensive point of view (point of view this large diversity of people don't usually have on their own).
My point was to explain what kind of challenges asking people what they see help to tackle.
