### ISSUE TITLE
Support splitting ways at "is this way lit" quest

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#3163]
**Use case**
Very long ways are sometimes only partially lit, not for the whole way. At the moment it's not possible to adequately answer the "is this way lit?" quest for them. 
![Screenshot_20210814_170903](https://user-images.githubusercontent.com/30999326/129450739-78cc8574-0440-4392-a478-40ef588a605b.jpg)

**Proposed Solution**
Enable the feature of splitting ways also for this quest.

**Comment by westnordost** [comment]
It is enabled

**Comment by Discostu36** [comment]
I don't see it in v33.2
![Screenshot_20210814_171458](https://user-images.githubusercontent.com/30999326/129450909-41826e42-4d6c-48ad-9290-f026c42abf70.jpg)

**Comment by westnordost** [comment]
You can't split areas:
https://www.openstreetmap.org/way/260641871#map=18/54.18178/7.89305

**Comment by Discostu36** [comment]
I didn't realize this is an area, sorry.

**Comment by HolgerJeromin** [comment]
> (By the way, is splitting areas also not supported in JOSM, or am I missing this feature? I haven't found how to do this easily.)

You need to use a plugin
https://josm.openstreetmap.de/wiki/Help/Plugin/UtilsPlugin2

Vespucci has this native
