### ISSUE TITLE
disable power=pole material quest by default

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3169]
It is not something where benefit of collecting data is quite minor and it (for a good reason) was mentioned in many places as an example of StreetComplete asking for the sake of asking.

Value of getting this data and quest variety is not worth the costs - time of mappers, damage to credibility of StreetComplete and silliness of that

I think that overall this quest should not be asked by default. It is fine to have possibility of enabling it, but that should be enough.

Related to #3161 that disables roof shape quest by default.

**Comment by peternewman** [comment]
FWIW this was the original issue that added it, with their reasoning for surveying it #187 .

> It is ~**not**~ something where benefit of collecting data is **quite minor** and it (for a good reason) was mentioned in many places as an example of StreetComplete asking for the sake of asking.

So it's very important to collect and you're in favour of it? :stuck_out_tongue_winking_eye:

**Comment by westnordost** [comment]
Unlike roof shapes, power pole material is 
- only really ascertainable from survey, usually not from aerial imagery
- quest density of it is much less dense. Particularly, it is not present in areas city centers where there are otherwise a lot of quests but mostly on the countryside, where there are less things to answer anyway
- In #187, @flacombe gave some points how this information could be used

**Comment by Helium314** [comment]
The quest is also somewhat useful for maintenance; I noticed roughly 20% of the power poles I was asked about don't exist any more.

**Comment by peternewman** [comment]
> The quest is also somewhat useful for maintenance; I noticed roughly 20% of the power poles I was asked about don't exist any more.

Shouldn't they be in the CheckExistence quest either way then, unlike a lot of that other stuff it's pretty hard for them to hide round a corner or out of sight!

Although I'm surprised yours are going @Helium314 , are they burying the cables instead, how else is distribution happening? These are generally last mile for me, with huge pylons doing the central distribution.

**Comment by Helium314** [comment]
> Shouldn't they be in the CheckExistence quest either way then, unlike a lot of that other stuff it's pretty hard for them to hide round a corner or out of sight!

Asking for each power pole seems redundant, as they usually disappear in groups. And SC currently can't remove the power line, so a note is necessary anyway.

> Although I'm surprised yours are going @Helium314 , are they burying the cables instead, how else is distribution happening? These are generally last mile for me, with huge pylons doing the central distribution.

Not sure what's going on. Maybe they got replaced by underground cables when reconstructing roads or telecom lines (update to fiber)

**Comment by peternewman** [comment]
> Asking for each power pole seems redundant, as they usually disappear in groups. And SC currently can't remove the power line, so a note is necessary anyway.

Very good point!

> Not sure what's going on. Maybe they got replaced by underground cables when reconstructing roads or telecom lines (update to fiber)

Wouldn't that make them telegraph poles not power ones?

**Comment by flacombe** [comment]
Hi all

This must be said that StreetComplete power pole's material quest is a key component to encourage mappers to look for this information.
It is particularly useful for infrastructures sensitivity to climate and weather (a line supported by wooden poles through a forest is weaker than one supported by metal or concrete).

OSM France conclude a partnership with Enedis recently this year and pole's material survey is a major point. OSM's ability to collect such property they currently ignore caught attention of power networks operators.
This process is expected to be reinforced shortly.

> Wouldn't that make them telegraph poles not power ones?

It depends who the operator is.
See https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole#Find_the_appropriate_utility
Former power poles can be kind of sold to telecom operator, but can remain in the power distribution network assets and left for rent.

**Comment by westnordost** [comment]
So I will close this request/suggestion to disable this quest type by default.

**Comment by peternewman** [comment]
> > Wouldn't that make them telegraph poles not power ones?
> 
> It depends who the operator is.
> See https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole#Find_the_appropriate_utility

Ah I see, there's a separate `man_made=utility_pole` for more general poles for telephony etc. Would there be benefit in asking for the material of those for the same reason (i.e. is telephone and particularly Internet access now sufficiently important that knowing they might fall over too would be beneficial). Although I appreciate the cable/fibre is considerably lighter and so there's less strain on the poles.

> Former power poles can be kind of sold to telecom operator, but can remain in the power distribution network assets and left for rent.

I'm still personally curious what's happened to the power cable that used to be on the pole (before it was former). It seems a bit crazy if they're going to the effort of burying it, but not putting ducts in for other services AND leaving the poles in situ!

**Comment by flacombe** [comment]
> Ah I see, there's a separate `man_made=utility_pole` for more general poles for telephony etc.

`power=pole` was introduced way before a more general solution appeared and it's too late to move it toward newer `man_made=utility_pole`.
`power=pole` should be `man_made=utility_pole + utility=power`.

> Would there be benefit in asking for the material of those for the same reason (i.e. is telephone and particularly Internet access now sufficiently important that knowing they might fall over too would be beneficial). Although I appreciate the cable/fibre is considerably lighter and so there's less strain on the poles.

I completely second that, material is always important
 

> I'm still personally curious what's happened to the power cable that used to be on the pole (before it was former). It seems a bit crazy if they're going to the effort of burying it, but not putting ducts in for other services AND leaving the poles in situ!

It happens very often in France as well.
Heavy machines come to bury the power cable but the old telephone lines remain on the poles.
Yes it's crazy.

**Comment by peternewman** [comment]
> > Ah I see, there's a separate `man_made=utility_pole` for more general poles for telephony etc.
> 
> `power=pole` was introduced way before a more general solution appeared and it's too late to move it toward newer `man_made=utility_pole`.
> `power=pole` should be `man_made=utility_pole + utility=power`.

In which case adding that one should be a complete no-brainer, as it's just asking the same question for a different style of tagging.

> > Would there be benefit in asking for the material of those for the same reason (i.e. is telephone and particularly Internet access now sufficiently important that knowing they might fall over too would be beneficial). Although I appreciate the cable/fibre is considerably lighter and so there's less strain on the poles.
> 
> I completely second that, material is always important

I guess that might be slightly more controversial for some people, if they feel e.g. they're less likely to collapse.

Do you want to open new issues for one/both to get them added (or maybe even a Pull Request for the former should be pretty easy), given you've got lots of strong use cases for why it should be gathered? I found one to test on here https://www.openstreetmap.org/node/7685905010

> > I'm still personally curious what's happened to the power cable that used to be on the pole (before it was former). It seems a bit crazy if they're going to the effort of burying it, but not putting ducts in for other services AND leaving the poles in situ!
> 
> It happens very often in France as well.
> Heavy machines come to bury the power cable but the old telephone lines remain on the poles.
> Yes it's crazy.

Ah, how bizarre!

**Comment by flacombe** [comment]
> In which case adding that one should be a complete no-brainer, as it's just asking the same question for a different style of tagging.

However poles and towers aren't power devices like transformers are, neither a pier is a waterway (cf waterway=pier). This is confusing and prevent further development of more detailed semantic.
 
> I guess that might be slightly more controversial for some people, if they feel e.g. they're less likely to collapse.

Collapse way also come from external causes
https://twitter.com/enedis_LR/status/1427922876070563842

> Do you want to open new issues for one/both to get them added (or maybe even a Pull Request for the former should be pretty easy), given you've got lots of strong use cases for why it should be gathered? I found one to test on here https://www.openstreetmap.org/node/7685905010

Done with #3184 3185
