### ISSUE TITLE
Update quest "board_type"

### ISSUE THREAD

**Issue by ba179** [streetcomplete/StreetComplete#3171]
At the moment the quest of the "board_type" of "information=board" ask for eg. "history, geology,..." but some types are missing.

I suggest to add the following terms to the list:
- art
- astronomy
- sport
- technology

I am not that good at coding, but would it be just to add the tags in the follwing files (+ translation)?
AddBoardTypeForm.kt 
BoardType.kt

**Comment by matkoniecz** [comment]
See #1226 and #1920 - from what I remember it was considered and rare values were left for notes.

But maybe situation changed?

**Comment by westnordost** [comment]
Not really: https://taginfo.openstreetmap.org/keys/board_type#values

sport is at 0.38%
technology is at 0.24%
astronomy is at 0.24%
art is at 0.18%

There is also 
sight at 0.72%  (<= though I don't like this one, a sight is likely something else, f.e. geology, historic etc)
hiking at 0.39% <= probably hiking map with trails + various information about local wildlife etc. "map" is better for that IMO

**Comment by matkoniecz** [comment]
> sport is at 0.38% <= can't really imagine what this would look like. Would it explain the sport...?

I have seen some describing nordic walking and route with posted recommended exercises to do while following it.

**Comment by westnordost** [comment]
Ah, or a board at a fitness trail explaining the excercises you can make here

**Comment by westnordost** [comment]
So, I added `sport` because on fitness-trails in parks and forests they may occur more often. I left the rest, it is not used enough to justify the space used.
