### ISSUE TITLE
Adding `waste` types on `amenity=waste_basket`

### ISSUE THREAD

**Issue by 10992-osm** [streetcomplete/StreetComplete#3173]
### General
Affected tag(s) to be modified/added: [`waste`](https://wiki.openstreetmap.org/wiki/Key:waste)
Question asked: **What sort of waste does this bin take?**

Multiple selection of at least (`waste=x;y;…`):

- [**`trash`**](https://wiki.openstreetmap.org/wiki/Tag%3Awaste%3Dtrash)
- [**`dog_excrement`**](https://wiki.openstreetmap.org/wiki/Tag%3Awaste%3Ddog_excrement)
(these are the ones listed on presets on JOSM and iD)

And possibly also:
- [**`cigarettes`**](https://wiki.openstreetmap.org/wiki/Tag%3Awaste%3Dcigarettes)
- [**`organic`**](https://wiki.openstreetmap.org/wiki/Tag%3Awaste%3Dorganic)
(these are listed on the wiki, and seem sensible values)

And perhaps:
- [**`recycling`**](https://wiki.openstreetmap.org/wiki/Tag%3Awaste%3Drecycling)

The wiki for [`waste`](https://wiki.openstreetmap.org/wiki/Key:waste) does not suggest that listed (semi-colon-separated) values can be used, but it is in use, according to [Taginfo](https://taginfo.openstreetmap.org/keys/waste#values "global Taginfo page for Key:waste values")

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose **(it is in use, allows identification of different types of bins: a bin only for dog excrement is no use if you are trying to dispose of something else)**
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam) **(not sure about this one, globally most `amenity=waste_basket` tagged with `waste=*` are tagged with `waste=trash`.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) **(yes, only just over 15% of `amenity=waste=basket`s have a `waste=*` tag)

### Ideas for implementation

**Element selection:**
`amenity=waste_basket` without a `waste=*` tag.

**Metadata needed:** 
There may be different customs in different countries which could affect this.
In the United Kingdom, most of the values are likely to be `waste=trash`, `waste=dog_excrement`, with a few `waste=dog_excrement;trash` and some with `waste=recycling` (perhaps combined).

**Proposed UI:**
Probably just a list (perhaps with images) of the types of waste, multiple can be selected.  + `Can't say` and `Does not exist`.

- `waste=dog_excrement`:
[![Red bin for dog waste only](https://wiki.openstreetmap.org/w/images/thumb/8/84/Dog_waste_bin.jpg/480px-Dog_waste_bin.jpg)](https://wiki.openstreetmap.org/wiki/File:Dog_waste_bin.jpg)
- `waste=trash` (`waste=litter` is also present, but I think it's more or less the same.  *trash* is more American, and can also refer to general household waste for incineration or landfill, whereas *litter* only really refers to small amounts of rubbish produced while one is out and about):
![litter bin in Liverpoo (Man vyi, Public domain, via Wikimedia Commons)l](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Litter_bin_Liverpool.jpg/363px-Litter_bin_Liverpool.jpg)
(Man vyi, Public domain, via Wikimedia Commons)
- `waste=cigarette`:
[![Cigarette disposal attached to a standard bin](https://user-images.githubusercontent.com/83511672/129627592-96d20eec-a3d7-45f5-a9b0-3e1b29631d5e.png)](https://www.geograph.org.uk/photo/444912)
(attached to bin, can be found stand-alone)

**Comment by 10992-osm** [comment]
Just as an update, I've found that (in England, at least):

>In recent years national guidance on the disposal of dog waste has changed and it is no longer necessary to separate dog waste from other types of household waste.
>For this reason, dedicated dog waste bins are no longer required and waste can be disposed of in any available litter bin or your black household bin.
>Some parish areas in South Gloucestershire have opted to continue providing dog waste bins, but others have removed some or all dog bins and ask responsible dog owners to use dual use bins, formally litter bins.

(from [South Gloucestershire](https://www.southglos.gov.uk/environment-and-planning/street-care-and-cleaning/dog-fouling-and-bins/)

This could mean that dedicated dog waste bins disappear, and that all litter bins are effectively `waste=dog_excrement;trash`.  However, any remaining dog waste bins will not start accepting litter, because (at the very least) they are often not the right shape to accept it.

**Comment by westnordost** [comment]
Hmm, I would so that I agree with you here:

> 💤 Not an overwhelming percentage of quests have the same answer (No spam) **(not sure about this one, globally most amenity=waste_basket tagged with waste=* are tagged with waste=trash.

Too many waste bins are just "normal" waste bins, without any signs or whatnot indicating that you can or cannot put cigarettes or something else inside.

Also, I doubt the usefulness of hte information. Dog-shit-only bins are usually placed in places where this is also the main expected litter (f.e. at the exact same location where you get dog shit bags). On cigarettes, I doubt that smokers would search with their smartphone for the closest bin that has a cigarette bin and time that with the time they are finished with their smoke. That's not an "amenity" a user would search for, it is rather an amenity to keep the street clean(er) from cigarette bums.

**Comment by peternewman** [comment]
> Dog-shit-only

Just for your info @westnordost , excrement would be the more formal word, or poo/mess (specifically for dogs/animals) the more informal, the word you've chosen, while everyone will know what you mean, is very informal and more usually used as a swear word! :laughing:
