### ISSUE TITLE
crossing quest seems to have an inverted answers

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3176]
At least in debug form mode answering "yes" will tag `crossing=no` (not tested in real editing)

**Comment by westnordost** [comment]
Oops!

Am 17. August 2021 10:41:09 MESZ schrieb Mateusz Konieczny ***@***.***>:
>At least in debug form mode answering "yes" will tag `crossing=no` (not
>tested in real editing)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3176

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
