### ISSUE TITLE
nodes with visibility=no just show up in quests

### ISSUE THREAD

**Issue by Tauvic** [streetcomplete/StreetComplete#3177]
node with tag visibility=no are not visible therefore should not appear in quests
visibility=no is used to enable keeping track of items that once existsted and where imported by an automated proces but now no longer exists. This prevents repeated deletions and reimports of non-existing items from datasets

**How to Reproduce**
set a node to visibility=no and quests will still be asked

**Versions affected**
all StreetComplete versions

**Comment by andrewharvey** [comment]
It looks like there are only ~100 occurances in OSM https://taginfo.openstreetmap.org/tags/visibility=no

A much better and more widely accepted scheme is https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_decay, then data consumers don't need to looks for some special tag.

**Comment by westnordost** [comment]
Asditionally, that Tag is not documented, no idea what if is supposed to mean. Are there invisible buildings, invisible roads? Things that are not there should not be mapped.

**Comment by Tauvic** [comment]
How does streetcomplete handle this situation? 
does it implement lifecycle and how?
Just ignoring imports and stating that we only should use manual input will not help.
We get more and more open data where government publishes information on streets, streetfurnature such as benches, playgrounds 

Nodes get imported and we need some reference.

**Comment by matkoniecz** [comment]
> visibility=no is used to enable keeping track of items that once existsted and where imported by an automated proces but now no longer exists.

Such objects should be deleted.

> reimports of non-existing items from datasets

If someone reimports deleted items then import process is faulty. It should be resolved by fixing such data in source databases or by recording faulty data - outside OSM database.

>  does it implement lifecycle and how?

Lifecycle prefixes require no special implementation to be supported.
