### ISSUE TITLE
Allow for more building types, especially museum

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#3179]
**Use case**
When categorizing buildings, I repeatedly have trouble finding the right one. While some building types are very detailed where I really need to check (house for a single family or for several flats - tricky sometimes) or for cars: One garage, multi garage, carport etc., in other parts the lists are rather short. I can leave notes, however, the downside is that I cannot register further information myself (e.g. house number, number of stories, roof shape, ...) because I often do not return to this place in a reasonable timeframe.

If the list is intended to be extended, then I will report more missing types beyond the specific ones in the next two paragraphs.

During my holidays we visited quite a few museums. And I could not tag them, unfortunately. So museum should definitely be added, they are often entire buildings and I checked that openstreetmap supports this. They could have opening times as well (probably beyond this feature request, but a logical consequence).

I also repeatedly had buildings which consistent of two parts, e.g. an old farm house extended by a modern part. I got two questions, for each part. If I answer "free standing family house" (sorry, rough translation from DE to EN), then both parts would ask for a house number, which does not make sense, as there is only one house number.

**Proposed Solution**
Add building type "museum".

Add building type "part of another (connected) building".

And clarify (at least in this feature request) if the list is intended to be extended, so that I could report more missing building types.

**Comment by 10992-osm** [comment]
In [this comment](https://github.com/streetcomplete/StreetComplete/issues/2265#issuecomment-727120117) in #2265, which was about adding libraries, it was said that for these, civic building (as a generic category) should be used.  The situation may have changed since then, though you may wish to read that issue.

**Comment by matkoniecz** [comment]
In general museum is not a building type.

> During my holidays we visited quite a few museums. And I could not tag them, unfortunately.

Some museums are in a church buildings (there is option for that), some in a buildings constructed as a residential (there are options). Sometimes I miss https://taginfo.openstreetmap.org/tags/building=palace but it is a but hard to justify putting it into SC.

Some museums are in purpose-build buildings, but there is nearly nothing unifying them more than "it is a civic building" (there is an option for that).

Overall, this quest asks about building type ( https://wiki.openstreetmap.org/wiki/Key:building ), not what is housed by a building.

**Comment by smichel17** [comment]
Some of the points brought up here are duplicates of previous conversations; you can find an incomplete list here: https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-646403

From memory, this much at least is a **new argument**:

> I can leave notes, however, the downside is that I cannot register further information myself (e.g. house number, number of stories, roof shape, ...) because I often do not return to this place in a reasonable timeframe.

@westnordost What do you think of "it will unlock another StreetComplete quest" as a reason to lower the threshold for inclusion?

> two parts

This seems perhaps worth discussing in a separate issue. Although I recall a similar discussion issue in the past, so please search first; please let me know if you find it and I'll add it to https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-646403.

**Comment by matkoniecz** [comment]
BTW, https://github.com/streetcomplete/StreetComplete/commit/98fccb460be61def0fd43482a31104ca89929aac#diff-27bdddb4ab370a8bd4531b218643d24a3388efdf7879f8b7748faf17cebeab5d added recently allotment house, boathouse and grandstand as selectable,

**Comment by Helium314** [comment]
> > two parts
> 
> This seems perhaps worth discussing in a separate issue. Although I recall a similar discussion issue in the past, so please search first; please let me know if you find it and I'll add it to [#2789 (comment)](https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-646403).

#1870 is about answering 'this is only a part of a building'

**Comment by hmartink** [comment]
I disagree. Museums are (at least in those parts I've visited) dedicated buildings. Some are reused buildings (e.g. old palaces), but often the building was build for this purpose. And often they occupy entire buildings, so I could tag them "multi flat house" but how would then others know this is a museum?

I apologize if I might not understand fundamental concepts of OSM, I'm mainly a SC user and going by its UI.

**Comment by matkoniecz** [comment]
> but how would then others know this is a museum?

Good question!

Museum will be marked as `amenity=museum` and may be inside a tenement house:

- https://www.openstreetmap.org/node/8261763064 museum
- inside a house https://www.openstreetmap.org/relation/9932482

- https://www.openstreetmap.org/node/9015266574 museum
- inside a castle https://www.openstreetmap.org/relation/2270819

- https://www.openstreetmap.org/way/233371578 museum and building housing it (constructed to house it) mapped as one object 

Similarly church building (`building=church`) may house place of worship (`amenity=place_of_worship`) but may also hold a museum, warehouse or apartments.

**Comment by westnordost** [comment]
See @matkoniecz
