### ISSUE TITLE
Store was long empty - what to enter?

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#3180]
For the first time I encountered a new type of quest. (The following strings are rough reverse translations back to English). "This store was long vacant, what is there now"? I remember I had three answers (sorry, I'm not sure how to reproduce this for reporting), the first one contained "..." as option, then leave a note or smmilar and a third option.

I saw a new shop in there, so I naturally entered the new shop name in the first answer. However, this answer was not accepted, it appeared as if I needed to enter specific strings. However, there was no indication which strings would be required (and if so, I would have expected either a selection or at least word completion). I ended up leaving notes, hoping that some other mapper will read the note and complete it. Especially in my last vacation, this seems to be a wrong assumption, so the update (which I could have done) looks to be far in the future.

**How to Reproduce**
Go to a store which (was) vacant and tagged as such. Tap on the quest. Enter a "random" string in the first entry. Answer will be rejected. No clue what is expected here.

**Versions affected**
Android: 10
StreetComplete: v33.2

**Comment by Helium314** [comment]
The auto-complete should actually show you a couple of suggestions.
You are supposed to enter the type of the shop and choose a type from suggensions. If there is no reasonably suitable choice you open a note.

Maybe the wording could be refined to indicate that the type is required, and not the name?

**Comment by matkoniecz** [comment]
1) what was language of the interface?

2) it is asking about building type, not building name. At least it is supposed to do so

3) Maybe give some hint if there is no matching entry?

**Comment by matkoniecz** [comment]
If you want you can help translating - see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app (it seems possible that translation can be improved)

**Comment by hmartink** [comment]
The interface language is German.

It was not clear to me what to enter there. I assumed "shop empty -> new shop" and entered the new name.

**Comment by matkoniecz** [comment]
The direction is

> Type kind of place here

> Hier Art des Ortes eingeben

can it be improved in German so it will be clear that shop type is being requested?

**Comment by hmartink** [comment]
Just to clarify: Do I need to type in there "Geschäft" (store)? Where do I know those strings from?

**Comment by matkoniecz** [comment]
In English I would input things like "bakery" "shoe store", "shoemaker", "restaurant", "candy maker".

**Comment by westnordost** [comment]
@hmartink :

Du gibst ein, was für eine Art von Geschäft jetzt dort ist. Die Formulierung "Art von Ort" ist deswegen so allgemein, weil dort jetzt ja auch z.B. ein Restaurant sein könnte, das fällt ja nicht unbedingt unter "Geschäft". Mit anderen Worten, wenn da jetzt zum Beispiel ein Blumenladen drin ist, dann gibst du genau das ein. StreetComplete sollte das dann autovervollständigen.

**Comment by westnordost** [comment]
Hast Du eine Idee für eine bessere Formulierung?

**Comment by hmartink** [comment]
Ich bin selbst in einigen Projekten Übersetzer, ich denke, die Übersetzung ist i.O., gerade nach dieser Diskussion.

Now that I understand the concept (better), I will hopefully handle this type of quest when I encounter it next time.

I think this issue can be closed, as it is a combination of me not reading completely correct, and me not understanding the concept of "..." / auto completion. 

The only thing I wonder is that here I'm suddenly asked about the type of a store, while in other discussions I was told that a building is a building (and even "museum" might be too specific), i.e. I did not discover a quest which asked me about initial types of stores, so the concept of changing the type was alien too me. I guess I need to learn quite a bit more about OSM.
