### ISSUE TITLE
When the app is in an RTL language, arrows for list items are not flipped

### ISSUE THREAD

**Issue by mhmdanas** [streetcomplete/StreetComplete#3181]
First off, before I start, I just want to say I am grateful for this app. Aside from very minor issues like this one, everything has been working smoothly. The app is beautiful and generally easy to use, even for OSM newbies like me. Thank you for making this.

**How to Reproduce**
1. Change to an RTL language (e.g. Arabic)
2. Open the settings page
3. The arrow for chosen quests list tile is rotated the wrong way

Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/32234660/129814952-6aed8c72-e934-4f26-a9bc-c524462619f2.png)

**Versions affected**

I am using StreetComplete 33.2 on Android 11.

**Comment by westnordost** [comment]
Thank you for the report! Don't hesitate to report any more issues with RTL languages. RTL support is not as well tested as it could be.

Alright, I also found more problems. I fixed:
- the bug as described here - the orientation of that chevron
- the animation when entering and exiting a submenu as indicated by that chevron
- padding in the edit history sidebar
- the side at which the edit history sidebar appears (it should always appear on the left) and its animation
- the side at which the quest answer bubbles appear on holding the phone in landscape orientation (it should always appear on the left) and its animation
