### ISSUE TITLE
When the app is in an RTL language, the number of contributions beside the star on the home page is not shown

### ISSUE THREAD

**Issue by mhmdanas** [streetcomplete/StreetComplete#3184]
**How to Reproduce**
1. Change to an RTL language (e.g. Arabic)
2. Go to the home page
3. See that the number of contributions is not visible (maybe because it's on the left of the star now, thus outside of the screen's bounds?)

Screenshot:

![screenshot](https://user-images.githubusercontent.com/32234660/129893804-56b0a514-357c-4dbe-9194-58d4e62e879e.png)

**Versions affected**

I am using StreetComplete 33.2 on Android 11. The phone is a Galaxy A51 if it matters.

**Comment by westnordost** [comment]
Already fixed, thanks
