### ISSUE TITLE
maxheight quests: Can't enter non-integer values due to limited number keypad

### ISSUE THREAD

**Issue by neuschaefer** [streetcomplete/StreetComplete#3186]
When answering a MaxHeight quest, a keypad pops up that has digits 0-9, _backspace_, and _done_. This makes it impossible to enter fractional numbers such as 2.3m, which do regularly occur in the world.

My perspective is limited to heights in meters, but a similar problem might occur for feet-and-inches values.

**How to Reproduce**

Answer a height limit quest, try to type a non-integer number.

**Versions affected**

Android 10 (vendor LG), StreetComplete v32.2

**Comment by matkoniecz** [comment]
See #1322 #1212

Samsung keyboard is known to be buggy and app is not really able to do anything about it. If you know sane workaround let us know, but for now see https://github.com/streetcomplete/StreetComplete/issues/1212#issuecomment-425876063

**Comment by matkoniecz** [comment]
In theory some special menu entry could be added when user is running Samsung but that would be complicated overkill to support buggy third-party software :/

**Comment by neuschaefer** [comment]
Ah, sorry for the duplicate.

(Small note: In my case it's not Samsung, but LG)
