### ISSUE TITLE
Resurveying of stiles

### ISSUE THREAD

**Issue by 10992-osm** [streetcomplete/StreetComplete#3187]
See also: #2991, #3141, #3188.

I think it would probably be advantageous to re-survey stiles.

I said [here](https://github.com/streetcomplete/StreetComplete/issues/2991#issuecomment-900486882 "link to comment in issue #2991") (clarified and expanded for this issue):

> As far as I can tell, stiles are never resurveyed.  I agree with what Philip Barnes' said (summarised in [this comment](https://github.com/streetcomplete/StreetComplete/issues/2991#issuecomment-899841013)) about resurveying stiles at regular intervals.  I'm not really sure what the interval should be, but my starting suggestion would be 5 years.  In the UK, stiles are gradually being replaced in many areas, and they are not supposed to be installed where one did not exist before (I'm not sure at this precise moment whether this is a legal requirement, or just guidance, it might say in one of the links in my comment on #3141).  I'm not sure whether it would be worth asking the whole stile type quest again, or not.

An alternative could be to just show the stile type it is tagged as, along with possible replacements (see #3188), and if it's tagged `stile=stepover` without a `material=*` tag, then the two options for the step-over stile could be displayed (as discussed in #2991 and added in #3175).  Under `Other answers…`, one could have `It's another type of stile`, which would remove the `stile=*` tag, and any associated tags (`material`, `height`, `width`, `step_count`, `dog_gate`, plus any others currently removed when a `barrier=stile` is changed to a `barrier=kissing_gate`)

If the whole stile type quest is asked again, I think that the current value could be put first in the list, I'm not sure if you already do this for other resurveying quests (e.g. surface of ways), if not, I don't think it's crucial, just helpful.

I'm going to post a message on [Talk-GB] for opinions specifically about re-surveying stiles (combined with #3188).
I will ask about:
- how often stiles should be re-surveyed, and
- which tags should be removed if a stile type is changed (or if the stile is removed entirely).

I will post updates:
- when I've sent the message to the list, and
- when I seem to have received all the responses I'm going to get.

**Comment by 10992-osm** [comment]
The message has now been posted on [Talk-GB]:
[[Talk-GB] Removal of and changes to stiles](https://lists.openstreetmap.org/pipermail/talk-gb/2021-August/027488.html)

**Comment by 10992-osm** [comment]
Since it has now been 7 days since I posted the [message on the [Talk-GB] mailing list](https://lists.openstreetmap.org/pipermail/talk-gb/2021-August/027488.html "Message on the [Talk-GB] mailing list about removal and changes to stiles"), I'll summarise the responses below, as far as they relate to resurveying stiles, see #3188 for any other responses:

- [David Woolley](https://lists.openstreetmap.org/pipermail/talk-gb/2021-August/027490.html) thinks that things only *get reviewed when people feel like it*, rather than when they should be.  He cites the example that *one should probably review shops every six months, but the reality is probably more like 10 years*.  He doesn't think *many people are going to set themselves schedules for re-surveying stiles*.
- [Edward Bainton](https://lists.openstreetmap.org/pipermail/talk-gb/2021-August/027492.html) picked *15 years* out of thin air as a re-survey interval.
- [Phil Barnes](https://lists.openstreetmap.org/pipermail/talk-gb/2021-August/027568.html) thinks that it is not as simple as just picking an interval at which stiles should be re-surveyed.  He says that the *likelyhood* (sic) *of replacement depends
heavily on location and usage*.  He suggests that stiles on long, rural paths are less likely to be replaced than stiles on a path that *forms a circular walk of a couple of
miles that is close to a settlement*, or indeed if the path *forms part of a walking route
relation as these are part of encouraging tourism*.  He suggests we should *look for stiles on paths where others have been replaced*.

**Comment by westnordost** [comment]
So far the check existence quest only re-asks for things for at most every 6 years. If we extend that to include things that are expected to change on even longer time periods, there are maybe a couple of more objects one would want to include there as well.
If that is done, I suggest to use power of twos for the categories (every year, two years, 4 years, 8 years, 16 years, ...) so that we don't get trapped in trying to adjust the resurvey-intervals too precisely because that 'd be a futile endeavour.

I'll leave this to @matkoniecz because it's his quest.

**Comment by 10992-osm** [comment]
> …I suggest to use power of twos for the categories (every year, two years, 4 years, 8 years, 16 years, ...) so that we don't get trapped in trying to adjust the resurvey-intervals too precisely because that 'd be a futile endeavour.

In which case, I'd suggest either 8 or 16 years as being an appropriate value for re-surveying.

---

Whether it's necessary or useful, I don't know, but one could consider implementing varying re-survey intervals based on tagging.  Any `barrier=stile` tagged with `material=stone` is likely to remain for longer than any tagged with another value (most of which will be `material=wood`).  There may, however, be little point in refining it in this way.

I'm not sure how many of the other suggestions I received are easily implementable.  It seems that re-surveying stiles that are part of a route relation more often makes sense.  I don't really know how route relations work, and whether it might be the case that only the path is a member, not the stile.

The suggestions regarding whether a stile is near a town or on a circular walk, or whether other stiles have been replaced seem to be much more difficult to implement technically, even though I don't have a great technical knowledge of how StreetComplete works.

**Comment by matkoniecz** [comment]
Looking at this task it seemed to be trivially implementable by extending AddStileType

But: `AddStileType` should not delete (for example) `steps`

If there was stepover stile and it was resurveyed and answer is "stepover stile" it is not a valid reason to delete `steps` tags.

But if there was stepover stile and now it is a squeezer stile - `steps` tags should be deleted.

But if there was squeezer stile and now it is a stepover stile - `steps` tags should be deleted.

Given that neither `applyAnswerTo` nor current `AddStileTypeForm` has access to current tags it is not solvable...

There are options

- wontfix this idea
- implement "is it still some stile or is it now a kissing gate?"
- implement special initStateFromTags like in opening hours

**Comment by Helium314** [comment]
> Given that neither `applyAnswerTo` nor current `AddStileTypeForm` has access to current tags it is not solvable...

Doesn't `osmElement!!.tags["steps"]` work here? See e.g. AddCyclewayForm

**Comment by matkoniecz** [comment]
> Yes it has access.

ops. That simplifies things!

BTW, maybe `tags` would be better name than `changes`?
