### ISSUE TITLE
Show nodes/area information, even if no task exists for it

### ISSUE THREAD

**Issue by carstenhag** [streetcomplete/StreetComplete#3190]
**Use case**
I walk along a street and see a small shop. I look on StreetComplete, but it is missing there - there is no icon or area showing any element there. I take a note and then figure out on my laptop that the node already exists. See https://www.openstreetmap.org/note/2809531.  
Had this with shops but also other amenities that don't get displayed at StreetComplete.

**Proposed Solution**
Idea 1: Have a toggle to show or hide extra data that exists at OSM. Could be a good way to solve it. When tapping on the area or node, tags are displayed.
Idea 2: Always show an icon for extra data that is not solvable/improved with current quests.

**Other considerations**
Of course I could just use vespucci or another osm editor, but StreetComplete's UI + this feature proposal would complement eachother imo. A full osm editor is too much, but the current thing causes unnecessary overhead for me.

**Comment by matkoniecz** [comment]
See  "Show other nearby objects of the same type when answering quests" #2354 

See also #2461 - big part was implemented but not actual part of displaying data.

> I walk along a street and see a small shop. I look on StreetComplete, but it is missing there - there is no icon or area showing any element there. 

Note that fully surveyed POIs will not be listed in SC. Shop with opening hours recently checked etc will not create a quest.

**Comment by westnordost** [comment]
So this is will not fix, but maybe something that solves this  use case will be implemented in the future

**Comment by carstenhag** [comment]
>Note that fully surveyed POIs will not be listed in SC. Shop with opening hours recently checked etc will not create a quest.

That is fine in itself, but I don't know whether a shop is mapped at all if there's no quest for that specific shop.

**Comment by matkoniecz** [comment]
Yes, and right now StreetComplete is sadly not suitable at all for detecting missing not mapped shops.
