### ISSUE TITLE
Upload changes in a collection

### ISSUE THREAD

**Issue by debuglevel** [streetcomplete/StreetComplete#3196]
**Use case**

After collecting a hundred quests in offline mode, I upload them at home and watch how each single change is uploaded. That's not really a big deal, but still seems a bit odd.

**Proposed Solution**

If there is an OSM endpoint to upload a collection of changes, upload all of them in a single request. If there is no such endpoint: just close this issue 😀

**Comment by westnordost** [comment]
It is possible, this is how all other editors do it. However, it is not possible in StreetComplete. I explain how the upload works here, if you are interested:

https://www.youtube.com/watch?v=Amk_Yvyau7A

I think the thing that bothers you the most is that all the quests on the map blink all the time during upload. This is an issue of the map rendering and cannot be fixed (without exchanging the map renderer, see #3123. What you can do, is just send the app into the background, it will continue to upload the changes.
However, currently it **might** be that after some time, the app will stop / cancel uploading further when it is in the background for too long. I didn't test it, but I think this may happen. However, this would be fixed as a side effect of fixing #2967 .

**Comment by debuglevel** [comment]
It was rather mere curiosity why they are not handled together. Thanks for the explanation! :-)

**Comment by westnordost** [comment]
Ok, short answer: If the upload for one change fails due to a conflict, it doesn't matter for the rest.
