### ISSUE TITLE
Bollards which are actually traffic signs

### ISSUE THREAD

**Issue by debuglevel** [streetcomplete/StreetComplete#3197]
We've got a lot OSM `bollard`s around here which are not really classical bollards, but act as such: they are just traffic signs standing in the middle of the path 😀. I just wondered if I should just mark them as `fixed` (which traffic signs obviously are) or if something else should be done here. :-)

**Comment by westnordost** [comment]
Do they actually act as bollards? I mean, all traffic signs are on the sidewalk, but they usually wouldn't block the path for a car to drive on the sidewalk if it wanted to right?

**Comment by westnordost** [comment]
Anyway, if the sign really acts as a bollard, I'd say `fixed` is fine. Or instead leave a note with a photo, so that (also) the traffic sign can be tagged.

**Comment by debuglevel** [comment]
Yes, they are actually combined bollard / traffic signs (e.g. german traffic sign 239) blocking the way. Maybe our city is just weird :-). I'll just tag them as `fixed` - thanks!

**Comment by 10992-osm** [comment]
> Yes, they are actually combined bollard / traffic signs (e.g. german traffic sign 239) blocking the way (e.g. a small entrace path into a park). Maybe our city is just weird :-). I'll just tag them as `fixed` - thanks!

We have things like that in the UK.  I've found an example of a [shared use path bollard](https://uk.glasdon.com/road-safety/bike-lane-bollards/mini-ensign-tm-bollard).

**Comment by HolgerJeromin** [comment]
> We have things like that in the UK. I've found an example of a shared use path bollard.

Glasdon is so "smart" to redirect users from Germany to the German main page.
If you want to have a look at an image, use google image search with "glasdon mini-ensign-tm-bollard".

**Comment by 10992-osm** [comment]
> > We have things like that in the UK. I've found an example of a shared use path bollard.
> 
> Glasdon is so "smart" to redirect users from Germany to the German main page.
> If you want to have a look at an image, use google image search with "glasdon mini-ensign-tm-bollard".

Or see this hotlinked image (may not work):
![Plastic bollard with integrated segregated path sign](https://uk.glasdon.com/images/products/400/Mini-Ensign-017.jpg)
