### ISSUE TITLE
Add photo of small bridge, with span supported by simple supports on sides of a bridge

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3211]
I am 100% sure that there was issue for that, closed long time ago because I failed to find a decent photo for it.

But I failed to track it down.

But I just found one that looks usable to me

Either way, I propose to add https://commons.wikimedia.org/wiki/File:Gorzyce_032.jpg to selectable bridges, as this quest asks for some looking like it and it is not clear which answer from currently available is fitting

![Gorzyce_032](https://user-images.githubusercontent.com/899988/130620305-0215e2f9-c075-4de2-b5da-891972e93477.jpg)

EDIT: I opened issue instead of making PR/commit as I want to confirm that it is a good idea and I am supposed to be doing something else right now

**Comment by Helium314** [comment]
might not be necessary once #2867 gets done...

**Comment by westnordost** [comment]
Jup, and it will get done
