### ISSUE TITLE
existing postr_box collection_times not recognized

### ISSUE THREAD

**Issue by olafhering** [streetcomplete/StreetComplete#3212]
**How to Reproduce**
`post_box` node [1736664785](https://www.openstreetmap.org/node/1736664785) has `collection_times` since two years, via changeset [72684081](https://www.openstreetmap.org/changeset/72684081)

StreeComplete still asks for collection times.

**Versions affected**

v33.2 from fdroid.

**Comment by Helium314** [comment]
You can set the resurvey interval to ask less often, then you should not be asked for another 2 years.

**Comment by olafhering** [comment]
I'm not sure what that means. There are questions whether a node has still correct data, and there are questions for missing data.
On this node the question should be whether the data are still accurate. Nothing is missing AFAICS.

**Comment by Helium314** [comment]
The quest whether the data is accurate and whether it is missing is the same here, see #2136 and maybe linked issues

**Comment by matkoniecz** [comment]
Some questions are resurvey questions asked when OSM data is old and likely to be stale.

Unlike in opening hours quest in this case there is no support to just confirm that current data is correct - it is simply reasked.

**Comment by peternewman** [comment]
See also #2105 which I think was the original, anyway I believe this is a duplicate.

I believe #2986 will resolve this.

**Comment by riQQ** [comment]
This will be implemented by #2986.
