### ISSUE TITLE
Unexpected lint invalid arguments during build

### ISSUE THREAD

**Issue by alanorth** [streetcomplete/StreetComplete#3225]
Error during build of v34.0-beta1 and master branch:

```console
...
> Task :app:lintVitalAnalyzeRelease FAILED
Could not deserialize /home/aorth/src/git/StreetComplete/app/build/intermediates/incremental/lintVitalAnalyzeRelease to a lint model: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException

> Task :app:minifyReleaseWithR8
WARNING:R8: Library class android.content.res.XmlResourceParser implements program class org.xmlpull.v1.XmlPullParser

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalAnalyzeRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Internal error: Unexpected lint invalid arguments
```

**How to Reproduce**
Building master branch with OpenJDK 11:

```console
$ ./gradlew clean aR -Dorg.gradle.java.home=/usr/lib/jvm/java-11-openjdk
```

I had been building this successfully the same way before v34.0-beta1.

**Comment by matkoniecz** [comment]
For me I can run a regular build, but `./gradlew clean aR` causes the same crash.

I guess the next step would be to use bisecting to locate commit that caused this issues.

`./gradlew :app:lintVitalAnalyzeRelease` seems to trigger the same problem, much quicker.

For completeness:

I did it on 5c4ab848c with `java --version` giving

```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

and ` lsb_release -a` giving 

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

I ran `./gradlew clean aR` (have not tracked where Java home is) everything went fine.

**Comment by Helium314** [comment]
Same problem with JRE from Android Studio, but builds when switching back to previously used gradle 4.2.2 (and using `lintOptions` instead of `lint`)

**Comment by westnordost** [comment]
So when building with gradle 4.2.2, it works?

**Comment by Helium314** [comment]
For me it does
