### ISSUE TITLE
Provide feedback to user if no object type matches in "what is here now" dialog

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3227]
**Use case**
Would fix root cause of confusion from https://github.com/streetcomplete/StreetComplete/issues/3180

**Proposed Solution**
Show something like

> enter shop type, not shop name - so "bakery", not "Ancient Oak"

if no object type matches

**Comment by westnordost** [comment]
Or "No results. Remember to enter the type of object, for example 'bakery', not the name"

**Comment by smichel17** [comment]
I don't think this is the best way to fix the root cause. As I see it, there are two problems:

1. **The question is not clear.** The user was just asked a question about a specific shop, like "What are the opening hours of *The Prancing Pony*?" So of course when they say it's not here anymore, and the app asks "What's here now?", they're going to answer with the name of whatever replaced it.
    - Ideally, we would allow them to answer intuitively, with the name of the new store, then change the tags in such a way that the next quest is "what type of shop is this?" But, if I recall correctly, this is not technically possible / the shop type is needed first.
    - Next-best would be to make the form two-part, asking first the name, then the shop type. But [multi-tag quests](https://github.com/streetcomplete/StreetComplete/issues/2127) have been rejected in the past, so this is also out.
    - At the very least, the title of the dialog should be **"What type of shop is here now?"**

2. **It's unclear that only specific values are allowed.** The field *looks* like a free-form text box.
    - When the drop-down is not visible due to too many options, there should be a :arrow_down_small: icon to the right of the text box (where the (:exclamation:) icon appears, when an invalid answer is entered).
    - *Ideally* tapping the icon would open a scrollable drop-down list. A lower-effort implementation could be showing a message or toast like "Please type more characters".
    - *Ideally* if the user types an invalid sequence (no matching entries), the (:exclamation:) and message should show immediately (instead of when the `OK` button is pressed). But for a lower-effort implementation, this can be skipped, or only triggered on :arrow_down_small: tap).

**Comment by mnalis** [comment]
good ideas @smichel17 , athough **_"What type of shop is here now?"_** is somewhat problematic, as it **need not be a _"shop"_** (it could be doctors, or fast food / restaurant, or real estate agent, or post office...)

**Comment by matkoniecz** [comment]
> Ideally, we would allow them to answer intuitively, with the name of the new store, then change the tags in such a way that the next quest is "what type of shop is this?" But, if I recall correctly, this is not technically possible / the shop type is needed first.

This one is not really possible - even tagging `name=given name` `shop=yes` is not really feasible as it is not necessarily a shop :(

Also, that will just turn into an opposite problem: people giving kind of object and this getting into `name` field.

-------------------------------------------------

> The field looks like a free-form text box.

Hmmm, maybe an ideal solution would result in showing a new iD-like menu on selecting this option? With list of object types, especially recently selected. And search box on top?

![screen05](https://user-images.githubusercontent.com/899988/140270936-13fb870c-1983-4634-a042-719691286cce.png)

That would require opening a new menu on selecting this, rather than remaining inside this radio button selection.

The good thing is that such menu would be needed for "add POI using StreetComplete".

**Comment by smichel17** [comment]
> **_"What type of shop is here now?"_** is somewhat problematic, as it **need not be a _"shop"_**

It could be, **What kind of place is here now?**

**Comment by smichel17** [comment]
Ooh! I just had an idea: What if we made it a separate option? Similar to this:

> #### What shop is here now?
> - [ ] _______________
> - [ ] It is not a shop, but a…
>    _\________________
> - [ ] It's vacant
> - [ ] Something else (leave a note)

The last three are the same as what happens today. The first one tags `name=given name` and `shop=yes`, so that we can show the follow-up quest, "What kind of shop is `given name`?"

**Comment by mnalis** [comment]
> It could be, **What kind of place is here now?**

That indeed is more general, but I'm not very happy with `place` as  a choice - even in English, it could mean different things, and I've already had problems with translating it, as it could mean anything from name of town, name of square where the shop/xxx is located, or name of the shop/xxx itself. In addition `kind of place` can be confusing as it does not explicitly ask for `type` which is better choice than `kind` IMHO (`what kind of place is this?` would suggest to me an answer along the lines of  `a nice, quiet place to chill out` or  `a place for rich celebrities only` or `not a kind of place where respectable lady would go at night alone` etc.)
Is there a better alternative than `place`, while still being somewhat more generic than `shop` ?
 
Also, `place` doesn't lend itself to usage in your second suggestion `What shop is here now?` / `It is not a shop, but a ...` - converting that to `What kind of place is here now?` is not ideal as mentioned above, but `It is not a place, but a ...` doesn't work _at all_ for me. 

> Ooh! I just had an idea: What if we made it a separate option?

I'm not too happy about multiple-quests-in-one idea (eg. `name=given name` + `shop=yes`), as it need not be a shop (but say `amenity=doctors` so we'd be mistagging until someone (if anyone) solves the followup question, which is worse idea than just leaving old wrong data around -- *and* the user might not know a name anyway). And it looks confusing to me anyway, as we offer the user to type two **completely different** things in the same multi-choice dialog window.
I'd much prefer if it would ask for _**one thing only**_.

**Comment by smichel17** [comment]
`type` instead of `kind` makes sense.

I was not able to think of any better word than `place`. Then I used a thesaurus, and found that there is a technically-better word: `establishment`. It is 100% the right word, but is also quite formal (and old-fashioned sounding). I *think* it's common enough that it will not be confusing, but I'm not totally sure.
