### ISSUE TITLE
Make quest findable in debug menu "Show quest form"

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3229]
**Use case**
Make easier to debug specific quest without scrolling for lightyears

**Proposed Solution**
The same code as for main quest list would be hopefully applicable

**Comment by westnordost** [comment]
I agree that would be convenient. But given the limited amount of users for such a feature (you, me, a couple of more people), I find it is somewhat not worth the time.
You are free to contribute something like that of course, but feature requests for debug features like this I almost always classify as will not fix, just as this one now.

**Comment by matkoniecz** [comment]
OK, I will try implementing it - I hope that it is not something complex and most of code is easy to reuse.

**Comment by smichel17** [comment]
An alternative would be to literally re-use the quest list fragment for this view — make a subclass that overrides the action on checking the box to show the form, instead.

**Comment by matkoniecz** [comment]
As I understand, it can be implemented ("You are free to contribute something like that of course") but waits for commits made by someone else.

**Comment by smichel17** [comment]
Understood. I think I actually looked into it at some point and concluded that it was not as simple as I'd hoped.
