### ISSUE TITLE
better display of statistics, show how things changed

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3230]
idea by @westnordost 

> show progress (how number changed) on opening stat screen. E.g. if you are now rank #100 instead of rank #125 since you last visited that screen, it would be nice if this change is animated (in a fun way?) instead of it being displayed as if it has always been that way

If anyone is aware about some open source project implementing such display - let me know

**Comment by westnordost** [comment]
> If anyone is aware about some open source project implementing such display 

What display exactly? Animations are part of Android. If you want to animate counting from e.g. 125 down to 100, that can be done with normal animators, see the quest statistics dialog.

Nicer than that would be perhaps something like a tally counter (i.e. the numbers animate in and out from above and below)
![hs6594_1-large](https://user-images.githubusercontent.com/4661658/131386338-f950959e-9718-4e15-9c34-bf074ac8e5a4.jpg)

Would you agree?

Actually, maybe not only for that, but also for the counter in the quest statistics dialog and for the star counter.

I searched quickly if there is any lib for that and didn't find any. But actually, it should be pretty straightforward to implement it as a custom view. The view could accept a decimal number, f.e. 1234.5 which would lead to the view being displayed as the first 3 digits being 1 2 3 and the last one halfway from 4 to 5. With this behavior in place, adding animation to that is easy, using the same method as we use now: With animators.

**Comment by mnalis** [comment]
Sounds like a nice touch, but do note that it might be demotivating too (after all, usually for _each_ user that gained rank, _all_ other users who are now below him/her had to lose rank). 

Eg. if you didn't contribute for some days and go on a multi-hour mapping session, and then visit the statistics, only to see your position counter counting in animation to worse position - sounds like it might be demotivating for some users at least.

Maybe only do the animation if the position of the user actually **improved** ?

**Comment by westnordost** [comment]
> Maybe only do the animation if the position of the user actually improved ?

Yeah, good idea
