### ISSUE TITLE
 Exclude aeroway=terminal buildings from building quest

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3233]
**Use case**
Right now `aeroway=terminal building=yes` will trigger the building quest and no available answer really matches (unless it is supposed to be "public transport"), but airport terminal have quite distinct purpose and style.

**Proposed Solution**
Exclude `aeroway=terminal` from building quest.

Or maybe provide an additional entry covering this?

Or maybe I should answer "public transport building"?

**Comment by westnordost** [comment]
> Exclude aeroway=terminal from building quest.

Sounds reasonable. Or any `aeroway` as this is already a description of what this building is?

**Comment by matkoniecz** [comment]
`aeroway=hangar` has an answer, though value of that that on something with `aeroway=hangar` is minimal and likely to be in inaccessible places.

Other things from https://wiki.openstreetmap.org/wiki/Aeroways should not appear in buildings or would end in confusing questions
