### ISSUE TITLE
Long ways aren't showing any quests

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3234]
**How to Reproduce**
[This track](https://www.openstreetmap.org/way/976570335#map=17/-30.53631/151.64779&layers=N) is asking me for a surface type.

[This track](https://www.openstreetmap.org/way/976570336) is not (in fact, it has no quests at all).

Other than the size/length, I'm not sure what is different in the two tracks that could be causing one to have quests but not the other.

**Versions affected**
StreetComplete v34.0-beta1 on Android 10

**Comment by smichel17** [comment]
I'm not 100% sure how the filters work, but my best guess is that one of its nodes is part of a driveway, and driveways are excluded from the surface type quest:

https://github.com/streetcomplete/StreetComplete/blob/95940485376b08782aa288f6330c8e81632d9f91/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddRoadSurface.kt#L14

**Comment by matkoniecz** [comment]
Longer ways are not getting quests (actually, it is one of few design decisions when I would definitely do things differently)

**Comment by westnordost** [comment]
See @matkoniecz . Yeah, maybe this can be removed now. IIRC this was added before splitting ways was introduced.

**Comment by matkoniecz** [comment]
Though it may be preferable to keep it for the forest quest (leaf type).

**Comment by 10992-osm** [comment]
If long ways are included:

How would it work (with really long ways)?  One would perhaps not see the quest pin at the start, and one may not walk along the complete length (one might turn of down a side path etc).  If one reviews the whole length of the way, one could split the way at a convenient point, but if one does not scroll over the whole way, how would this be dealt with?

**Comment by matkoniecz** [comment]
Yes, for really long ways user would be more likely to miss quest - or split basing on which part was surveyed.

Maybe repeating quest icon would be nice, but may be irritating to implement

**Comment by westnordost** [comment]
Alright, let's do it then. But maybe not for areas, since there is no "split area".
