### ISSUE TITLE
Newly added buildings and other features not drawn to map unless the quest is selected

### ISSUE THREAD

**Issue by Olzaq** [streetcomplete/StreetComplete#3235]
Newly added buildings and other features not drawn to map unless the quest is selected. When selecting new quest then the building is displayed, but only during that time. It disappears after selecting something else or completing the quest.

Clearing cache didn't help.

**How to Reproduce**
Find new building and click new quest

**Versions affected**
SC 33.2 and older, Android 9

**Comment by Olzaq** [comment]
![Screenshot_20210901-014534](https://user-images.githubusercontent.com/4409766/131586627-83b1acc8-67cf-4bbb-854c-271e24d5249c.png)

An example where 2 new buildings are added, but only showing if the quest is selected.

**Comment by mnalis** [comment]
That is to be expected - it takes some time (day or two) for tiles to be updated. See https://github.com/streetcomplete/StreetComplete/issues/2479#issuecomment-757489111 and surroundings.

**Comment by smichel17** [comment]
It's funny, when we were using the nextzen rules which were *years* out of date, we got relatively few big reports of this type. Now that the map tiles are updated quickly, people seem much more likely to assume that means they are updated *instantly.*
