### ISSUE TITLE
Improved strategy for tagging cycle and foot way surface

### ISSUE THREAD

**Issue by apophenic-treehugger** [streetcomplete/StreetComplete#3238]
**PREFACE**
_**Abbreviations/terms**_
* OSM : openstreetmap
* SC : Street Complete
* CCFW : "combined cycle and footway" (may be segregated or not), for example `highway=path + foot=designated + bicycle=designated` (or similar, see [osm wiki](https://wiki.openstreetmap.org/wiki/Key:segregated) for details).
* overtagging : the presence of redundant tags, here in particular using both (`cycleway:surface=* + footway:surface=*`) and `surface=*`, or using `cycleway:surface=* + footway:surface=*` if they have the same value (in which case there should only be `surface=*` instead)

_**Assumptions**_
I am assuming a consensus on these points:
* The a priori assumption is that OSM tags are correct. In absence of other information, there is no reason to assume that tags are wrong.
* Nevertheless, it is totally OK to check, verify, update tags from time to time, especially tags or combinations thereof which are known to error-prone (e. g. `opening_hours` which tend to outdate). However, until they are found to be wrong, existing tags are assumed correct.
* Features should be tagged (a) as simple as possible and (b) as verbose as necessary to reflect all relevant and known information. If the number of tags can be reduced without loss of information, this is in general the way to go. (exceptions may be if this would render the information much harder to understand)

**USE CASE**
The proposal aims to solve two related issues which have been discussed in [#3222](https://github.com/streetcomplete/StreetComplete/issues/3222l).
1) For segregated CCFW, SC currently creates quests that result in surface overtagging in at least two very frequently occuring cases
 -  Case I: If there is already a `surface=*` tag (in theory this means that both ways have the same surface), SC does not trust this tag, but instead adds `cycleway:surface=* + footway:surface=*` nevertheless
-  Case II: Regardless of the above, SC _always_ adds `cycleway:surface=* + footway:surface=*`, even if they are the same. This is unnecessarily explicit, since `surface=*` would suffice in this case.

2) A very active and experienced OSM mapper reported in the ([same discussion](https://github.com/streetcomplete/StreetComplete/issues/3222l)) that they have made the experience that a `surface=*` tag on segregated CCFWs is not always reliable. They estimate the wrong tagging frequency to be as high as 10% in some areas.

**PROPOSED SOLUTION**
I propose a two-fold strategy aiming at (a) adding information (tags) _if and only if_ needed and (b) verifying pre-existing information (tags) with three desirable properties:
* missinginformation is added
* overtagging is avoided
* tags that are prone two errors and/or outdating are verified from time to time and corrected/updated if necessary

**(a) Getting the information right, while avoiding overtagging**
1) If there is a CCFW without a `segregated=*` tag, ask the user to add it.
1) If there is a CCFW with `segregated=no` and missing `surface=*`, ask the user to add it.
1) If there is a CCFW with `segregated=yes` and `surface=*`, trust this tag (or ask the user to confirm it, see below)
1) If there is a CCFW with `segregated=yes` and no `surface=*`, give the user a 2-stage quest: (i) _"Do the cycle and foot track have the same surface?"_ (ii) If yes, ask for it and add it as `surface=*`. If not, ask for each individually and add them as `cycleway:surface=* + footway:surface=*`

**(b) Verify pre-existing information**
In order to address the issue that `surface=*` is not reliable on segregated CCFWs, create a quest to verify the surface (in analogy to verifying `opening_hours`):
1) If there is `cycleway:surface=* + footway:surface`, don't do anything.
1) If there is no surface tag at all, don't do anything (optionally create a type (a) quest instead).
1) If there is a `surface=* + surface:check_date` and it is younger than a certain age, don't do anything. (the specific age is not subject of this proposal; perhaps 1 or 2 years, but should be discussed elsewhere, in case this proposal gets accepted)
1) If there is `surface=*` but no `surface:check_date` or `surface:check_date` is too old, then ask the user to verify this tag, e. g. _"Is it still the case that the surface of **both** the cycleway **and** the footway are paving stones?"_ (i) If yes, update `surface:check_date=*` and exit. If no, delete `surface=*`, delete `surface:check_date` and exit or optionally continue with a quest of type (a)

**Comment by matkoniecz** [comment]
> The a priori assumption is that OSM tags are correct. In absence of other information, there is no reason to assume that tags are wrong.

There is noticeable minority  people not using `paved` where footway and cycleway part both are paved but with a different surface.

**Comment by apophenic-treehugger** [comment]
I guess a useful refinement to the proposed strategy might be to include quests to specify the generic `surface=paved`, `surface=unpaved` and `surface=ground` tags.

**Comment by matkoniecz** [comment]
The problem is that some people used, recommended and defended use of `surface=asphalt` where only cycleway part is such.

**Comment by mnalis** [comment]
Also, note that CCFW as described above could have **other** transportation ways of traversing it too. IOW, just because some way is (and has surface) for foot and bicycle traffic, does not mean that other transportation modes are not possible too, or that do not have their separate surface. 

Also is problematic the fact that we also **may not assume** that just because some transportation mode is **not mapped**, that it **does not exist** (eg. it might have been just a rough `highway=path` mapping, and then some cyclist micromapped `bicycle=designated` on it. It does not mean that other transport modes on that path do not exist - it might be just that nobody bothered so far to map it)

For example, https://taginfo.openstreetmap.org/tags/bicycle=designated#combinations mentions that it `bicycle=designated` is quite often (`6.5%`) used with `horse=*` (there might be [others](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation) too, I haven't looked into details). I don't live if horse-country, but I can imagine a way being tagged with `highway=path` + `bicycle=designated` + `foot=designated` + `horse=designated`, and horse-surface being different from foot/bicycle one.

**Comment by apophenic-treehugger** [comment]
As I'm understanding folks here, you'd be totally fine with an app routinely tagging
`maxspeed=60 + maxspeed:psv=60 + maxspeed:hgv=60 + maxspeed:bus=60 + maxspeed:bicycle=60  + maxspeed:forward=60 + maxspeed:lanes:forward=60|60 + maxspeed:lanes:backward=60|60`, because there are some cases where one of these tags is necessary but missing.

I think it's conceivable that some experienced mappers will be put off by this.

I may be getting something wrong, but it seems to me that you @matkoniecz and @mnalis either
(A) don't see a problem or 
(B) don't believe there is a solution to it.
I disagree with both.

**Comment by apophenic-treehugger** [comment]
No offense intended. I'm just trying to pin down the problem. I find it hard to grasp what's the nature of the objections:
(a) Do you think there is no problem with the current SC behaviour? or
(b) Do you think there is no solution to it? or
(c) Do you think the proposed solution is not the best?

**Comment by matkoniecz** [comment]
(1) I am not 100% happy about current behaviour

(2) it is not true that it is useless/bad in the way like maxspeed example would be

(3) one of assumptions that you made was not always true

(4) either solution is not perfect (overtagging Vs not correcting cases where `surface` was misleading)

(5) I would be fine with asking only on `surface=paved` and where `surface` is not tagged, I am also fine with the current solution

**Comment by mnalis** [comment]
@apophenic-treehugger No offense received. Mostly (c) in my case, as I was just noting an issue with proposed solution here, for further consideration when weighting pros and cons of each possible implementation.

Also, every solution I can think of (including currently implemented one) has some drawbacks, so I do not currently see that it can be 100% fixed at the moment. It is just that this suggestion (in its current form) looks likely to introduce more problems then it solves (IMHO).

**Comment by westnordost** [comment]
Alright, I read through your proposal finally. It's very well written, thank you!

> 1. If there is a CCFW without a segregated=* tag, ask the user to add it.

I fear this would add the "overtagging" simply at a different point. Then, every single path in the woods will have a `segregated=*` tagged. StreetComplete currently only asks for whether a foot- and cycleway is segregated if it is paved.
I find it preferrable to have `cycleway:surface=*` on all eligible segregated cycleways than to have `segregated=*` on **all** paths.

So, this ruins your suggestion (a) basically. Do you really find it better to tag `segregated=*`  on all paths or did you overlook this issue?

> (b)

The surfaces are already checked again - every 8 years.

---

In general, I am not really convinced that to use as little tags as possible is more important than being explicit about what has been surveyed. I find it more important to be explicit.

**Comment by Spammann** [comment]
I want to add my support to this proposal. In fact, I had basically the same idea before seeing it here. 😁

A mapper in my region started adding identical `cycleway:surface=*` + `footway:surface=*` to paths that already had an identical `surface=*`. I found this irritatingly redundant, suspected a beginner and removed those tags. Only then I noticed that StreetComplete was responsible. So I guess I come from the same place as the OP, @apophenic-treehugger.

I agree with the [last objection](https://github.com/streetcomplete/StreetComplete/issues/3238#issuecomment-913567421), which the OP did unfortunately not respond to anymore, against step 1. I guess the core of the proposal really only starts at step 3. So how about starting there?

Are there still other strong objections? If so, could you try to express them again?
