### ISSUE TITLE
Kerbs for existing crossings

### ISSUE THREAD

**Issue by davidpnewton** [streetcomplete/StreetComplete#3239]
In the most recent beta 34.0 #2999 is fixed. That means crossing nodes are added for non-crossing type ways meeting a highway. The quests which trigger then involve saying whether the crossing has an island, what type of kerbs it has, what type of crossing it is and whether it has tactile paving.

Three of those four quests also trigger for crossing nodes on crossing ways where they meet highway ways. However the quest to set a kerb type on this crossing node never triggers. To me this should trigger for all highway=crossing nodes, regardless of whether they are for a crossing type way meeting a highway type way or for a non-crossing type way meeting a highway.

**Comment by westnordost** [comment]
Sorry, I have difficulties to understand what you mean.

Do you mean to say that for crossings that are already tagged with `highway=crossing`, the app should also ask for its kerb (height)?

**Comment by davidpnewton** [comment]
You have difficulties. However you understand correctly. For nodes already tagged with highway=crossing the app should ask for the type of kerb.

**Comment by westnordost** [comment]
Hmm, I guess this would be possible. It would be a separate quest though.

**Comment by westnordost** [comment]
And it should not be asked for crossing nodes that are part of a `highway=footway + footway=crossing`

**Comment by Lee-Carre** [comment]
> it should not be asked for crossing nodes that are part of a `highway=footway + footway=crossing`

Why's that?

My reading of the OP's description yields the inverse interpretation.

I've encountered crossings, which have a highway=footway (complete with footway=crossing) intersecting with a highway=[various types of roads for motor vehicles], which lacked a kerb=*, for which this quest being asked would make sense and the answer easy to determine.

**Comment by westnordost** [comment]
Because for crossings that are mapped using footway=crossing, the app already asks for the kerb height at the node at which the kerb is located (vertex between a footway=crossing and a footway=sidewalk)

**Comment by westnordost** [comment]
The example you posted is already tagged with a lowered kerb.

**Comment by davidpnewton** [comment]
Erm yeah. That's because I tagged it that way when I solved the Streetcomplete quests.

Version 1 created by me 11 months ago was simply a node showing the intersection of the cycle track with the residential street. I had meant to get round to creating a pedestrian crossing manually, but hadn't. Version 2 created by changeset 110384611 with Streetcomplete added the pedestrian crossing tagging to the node and set the kerb tag to lowered. Version 3 created by changeset 110384615 set it as an unmarked crossing. Version 4 created by changeset 110384617 set it as not having an island in the middle of the road. Version 5 created changeset 110384620 set it as having tactile pavings present.

Versions 2, 3, 4 and 5 were all created using Streetcomplete. Version 2 was the new quest created by dealing with bug #2999. Had it been tagged highway=crossing on the way instead of cycleway=crossing on the way the new quest wouldn't have triggered. Both the node marking the actual intersection of the way ways and nodes 8038473011 and 8038473013, marking the actual, physical kerbs for the ends of the crossing way themselves are tagged fully. You'll notice that nodes 8038473011 and 8038473013 have also been edited by me using Streetcomplete.

**Comment by westnordost** [comment]
So, not sure what exactly is you feature request then.

Am 8. September 2021 00:26:09 MESZ schrieb davidpnewton ***@***.***>:
>Erm yeah. That's because I tagged it that way when I solved the
>Streetcomplete quests.
>
>Version 1 created by me 11 months ago was simply a node showing the
>intersection of the cycle track with the residential street. I had
>meant to get round to creating a pedestrian crossing manually, but
>hadn't. Version 2 created by changeset 110384611 with Streetcomplete
>added the pedestrian crossing tagging to the node and set the kerb tag
>to lowered. Version 3 created by changeset 110384615 set it as an
>unmarked crossing. Version 4 created by changeset 110384617 set it as
>not having an island in the middle of the road. Version 5 created
>changeset 110384620 set it as having tactile pavings present.
>
>Versions 2, 3, 4 and 5 were all created using Streetcomplete. Version 2
>was the new quest created by dealing with bug #2999. Had it been tagged
>highway=crossing on the way instead of cycleway=crossing on the way the
>new quest wouldn't have triggered. Both the node marking the actual
>intersection of the way ways and nodes 8038473011 and 8038473013,
>marking the actual, physical kerbs for the ends of the crossing way
>themselves are tagged fully. You'll notice that nodes 8038473011 and
>8038473013 have also been edited by me using Streetcomplete.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3239#issuecomment-914667627

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by davidpnewton** [comment]
To illustrate exactly what I mean I have created way 983418831, consisting of nodes 9092700173, 9092700174 and 9092700175 with changeset 111217762.

This way is tagged using the Unmarked Crossing preset in ID and so has footway=crossing as part of its tagging. Node 9092700174 is where it intersects with way 875768634, the pre-existing residential road. Normally I would then automatically use ID's built-in error-spotting code to create a crossing node for the two ways automatically. I deliberately created the crossing node manually and untagged to illustrate what I mean.

In Streetcomplete 34.1 the way triggers the quests for lighting and surface. Solving them as lit and an asphalt surface leaves no further quests triggered. That is the behaviour I am wanting changed. The quest introduced by #2999 to tag for kerb type and incidentally create a crossing in such a situation should then trigger for node 9092700174. Were the way tagged with cycleway=crossing using an ID preset appropriate to a cycle track then that quest would trigger. Solving this quest would then lead to the further quests about the type of crossing present, whether an island is present at the crossing and whether tactile paving is present triggering.

Further where there is an existing crossing node of any kind denoted by tagging of highway=crossing then a quest to tag the type of kerb present at the crossing should trigger. This is separate to the behaviour of #2999 because that quest both tags for the type of kerb and actually creates the crossing.

**Comment by westnordost** [comment]
I see, thank you for elaborating. 

The quest does not trigger for [way 983418831](https://www.openstreetmap.org/way/983418831) because it has `footway=crossing` tagged. Why does it not trigger? The reason was discussed here:

https://github.com/streetcomplete/StreetComplete/pull/2999#pullrequestreview-720881532
cc @jyasskin

In short:
1. (In reference to the linked ticket:) In case it is not a crossing, the whole crossing-way should be removed, not only the node tagged as not-a-crossing. StreetComplete can't do that, however.
2. Regarding kerbs: If the sidewalk is mapped as a separate way rather than on the road itself, we know that at this position, the sidewalk-infrastructure a higher level of detail is mapped. Tagging `kerb=*` is likely unwanted on the crossing node itself but should instead be tagged on the actual location of the kerb.

**Comment by westnordost** [comment]
So, we may have misunderstood each other, but what would be viable as a quest from a rough look at it would be the following:

For `highway=crossing` that are tagged on a road-way and **do not intersect with any footway** which may indicate the crossing to be mapped in more detail (i.e. with `footway=crossing` + `highway=footway`), we can ask about the kerb height and tag this information onto the `highway=crossing` node.

The current kerb height quest looks to tag the kerb height information on the `barrier=kerb` nodes. A proposed quest could also tag the kerb height information on the `highway=crossing` node but should only do this if the barrier is not already tagged (or taggable) on the `barrier=kerb` nodes) because the latter is more detailed.

**Comment by arrival-spring** [comment]
This quest would have a problem if there is a different kerb on each side of the crossing.

I [asked on the forum](https://community.openstreetmap.org/t/what-to-tag-when-there-is-a-different-kerb-on-each-side-of-a-crossing/100141) and the only solution is to leave a note (with photo) in that situation, for the crossing to be mapped in more detail later.

This should be rare enough that it is not a blocker though.
