### ISSUE TITLE
Kerbs different for each side

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3246]
The new add kerbs/crossing quest does not allow specifying different kerbs, but I already encountered several cases where one side is `raised` and the oder side is `no`.
According to [wiki](https://wiki.openstreetmap.org/wiki/Key:kerb) `kerb:left` and `kerb:right` should be used in such cases (but only has ~ 1500 uses each).

Maybe some "other answer" could be added which then allows selecting the kerbs for each side?

**Comment by westnordost** [comment]
Hm, I'd rather not implement that, too much effort. Let's first keep it as case for "leave note".

**Comment by westnordost** [comment]
Why much effort:

We'd need (vector) illustrations for all the different kerb types so that they can be displayed in that "street side select" UI.

And then of course, the extra effort to show that form etc.

**Comment by Helium314** [comment]
Sounds reasonable,especially with the necessity of adding new vector graphics.

@westnordost: Does StreetComplete ask the add crossing quest if `kerb:left` or `kerb:right` are tagged?

**Comment by westnordost** [comment]
No, only if the vertex has no tags at all so far

Am 6. September 2021 08:37:58 MESZ schrieb Helium314 ***@***.***>:
>Sounds reasonable,especially with the necessity of adding new vector
>graphics.
>
***@***.***: Does StreetComplete ask the add crossing quest if
>`kerb:left` or `kerb:right` are tagged?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3246#issuecomment-913383138

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
