### ISSUE TITLE
Images of bridges are ambiguous

### ISSUE THREAD

**Issue by pigsonthewing** [streetcomplete/StreetComplete#3247]
None of the bridges in the app (screenshot below) look anything like either of the brick bridges (one with a single arch, one with several; both made of brick and both with a horizontal deck) in my pictures*; which are of a type common in the UK and elsewhere. Its not clear to me (and, I suspect, to a lot of other people) which image to select.

[Both of the images are taken by me and are on Wikimedia Commons; feel free to use either]

![1200px-Tower_Bridge_-_Tame_Valley_Canal_-_panoramio](https://user-images.githubusercontent.com/89541/132025205-75fcc2b3-cede-4e8a-b362-7ae1049c364f.jpg)
![1200px-Bridge_over_River_Tame_opposite_Hamstead_Station_-_2016-12-17_-_Andy_Mabbett_-_03](https://user-images.githubusercontent.com/89541/132025210-85942543-ee3a-4158-9fd2-73652f8905db.jpg)
![2021-08-27 22 50 38](https://user-images.githubusercontent.com/89541/132024929-9763be7d-a54b-4180-81b1-809b2b0887ff.jpg)

**Comment by Helium314** [comment]
does #2867 help?

**Comment by westnordost** [comment]
It's an arch. But anyway, see #2867. Different images will be used starting in the next version.

**Comment by westnordost** [comment]
Specificially, look at this preview:

<img src="https://user-images.githubusercontent.com/4661658/131896774-4b3bf89b-5699-4c85-b110-ad5ecfaeb4d7.png"/>

**Comment by westnordost** [comment]
And to answer your question, both are arch bridges.

**Comment by pigsonthewing** [comment]
> 
> 
> does #2867 help?

Without the labels; no.

**Comment by pigsonthewing** [comment]
> 
> 
> Specificially, look at this preview:
> 
> ![](https://user-images.githubusercontent.com/4661658/131896774-4b3bf89b-5699-4c85-b110-ad5ecfaeb4d7.png)

This does not resolve the issue. What is supposed to be an arched bridge shows a lattice construction. It does not resemble either of the bridges in my images.

**Comment by pigsonthewing** [comment]
> 
> 
> And to answer your question, both are arch bridges.

I didn't ask a question. I know what type of bridges my pictures depict. I am unclear why you have closed this unresolved ticket.

**Comment by westnordost** [comment]
Well, if you are unsure, just leave a note.

And if you already know which type of bridge to select, then this was not an actual issue but you just assumed that people **may** be confused what to answer.

**Comment by mnalis** [comment]
@pigsonthewing there are literally dozens of different details of bridges. Letting the user choose between dozens of pictures would be counterproductive (even now we have some duplicates for ease of recognizing, but it is really something that should be reduced, not expanded on). 

The main point I think is that it has a straight surface on which you drive, and an arch  (and not to guess exactly which of the arch variants it is). See https://wiki.openstreetmap.org/wiki/Tag:bridge:structure%3Darch

If you have specific idea how to improve some of those hand-drawn pictures to better represent all variants of arch bridges as described by the OSM wiki, that would be useful. (but no photos, see linked issue for reasoning why).

**Comment by pigsonthewing** [comment]
> Well, if you are unsure, just leave a note.

There is little point leaving a note to say a ttag is missing from OSM, when it can easily be seen that that tag is missing.

> And if you already knew which type of bridge to select, then this was not an actual issue but you just assumed that people **may** be confused what to answer.

I said I knew which type of bridge I was looking at when I took my photographs. I also said - despite that - that "It's not clear to me (and, I suspect, to a lot of other people) which image to select." That is an actual issue.

**Comment by matkoniecz** [comment]
> There is little point leaving a note to say a ttag is missing from OSM, when it can easily be seen that that tag is missing.

Adding photo allows it to be fixed remotely

**Comment by mnalis** [comment]
> "It's not clear to me (and, I suspect, to a lot of other people) which image to select."

@pigsonthewing Yes, I think I get the problem. But, do you have any **suggestions how to improve** the [new pictures](https://github.com/streetcomplete/StreetComplete/issues/3247#issuecomment-912667101) in order to make it easier for you (and possibly other people) to recognize which picture represents your bridge? (preferably in a way that would not create even more confusion for other users - like adding a lot of new pictures might)

It is not easy for **me** (for example) to guess what would help **you** choose the right picture.

**Comment by peternewman** [comment]
> Specificially, look at this preview:
> 
> ![](https://user-images.githubusercontent.com/4661658/131896774-4b3bf89b-5699-4c85-b110-ad5ecfaeb4d7.png)

What about putting a dotted line down the middle and representing both styles on the same image @westnordost ?

I suspect it only applies to arch and hump back and wouldn't make sense for the rest. I did find a small handful of hump back bridges which weren't stone although the vast majority were. The non-stone ones I found didn't have a lattice structure underneath though.

**Comment by westnordost** [comment]
hm, what if for arch bridges, no lattice construction is shown at all? (i.e. the red is solid)

**Comment by peternewman** [comment]
I think that's what @pigsonthewing proposed:

> What is supposed to be an arched bridge shows a lattice construction. It does not resemble either of the bridges in my images.

It would work for me, I was only suggesting the split-screen so people can see both styles. If you look here, there are three (well 2.5) different styles of arch bridge shown:
https://wiki.openstreetmap.org/wiki/Tag:bridge:structure%3Darch

Or similar to what I see you've done with arch, you could just list various duplicates (perhaps further down the list) and people can pick the one that best matches their bridge (even if they tag the same value).

As I mentioned, for humpback it seems even more relevant, I've not found a picture of a humpback that looks like yours with the structure below.
