### ISSUE TITLE
Don't ask for vegetarian meals if it's already marked as vegan

### ISSUE THREAD

**Issue by khao-soi** [streetcomplete/StreetComplete#3249]
When optional tasks vegetarian / vegan meals on menu are enabled, and you mark a restaurant as vegan, you are still being asked if it has vegetarian meals on the menu. I here agree with the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:diet:vegan) that vegetarianism is implied when the restaurant is already marked as vegan.

Thank you.

**Comment by Helium314** [comment]
If a restaurant is `vegan=only`, the vegetarian quest is not asked.
If a restaurant is `vegan=yes`, the vegetarian quest ist still useful to choose between `vegetarian=only` and `vegetarian=yes`

**Comment by khao-soi** [comment]
You're right. Meals could be all vegetarian and some of them vegan. But it still could lead to many redundant `vegan=yes` && `vegetarian=yes` taggings. I guess I'll just ignore and hide the quest.

**Comment by 10992-osm** [comment]
What happens if someone says there are no vegetarian meals when `vegan=yes` is set?  Or is it not currently an option?

**Comment by mnalis** [comment]
> What happens if someone says there are no vegetarian meals when vegan=yes is set?

@10992-osm good question! You should try it out and if it is broken, report a new issue (as closed issues get little love).

With my (quite limited!) understanding of the  [AddVegetarian.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/diet_type/AddVegetarian.kt)  likely nothing special would happen -- so "impossible" combination `vegan=yes` + `vegetarian=no` would be tagged. 

Perhaps such invalid combination should be catched and additional action taken (`are you sure, because it is mapped as Vegan?!`) ?

Or (I don't know if there is capability in SC for that) if `vegan=yes` then disable `No` as an answer for `Vegetarian` (and have users leave a note if diet is wrongly mapped).

**Comment by Helium314** [comment]
Vegan is asked only if vegetarian is yes or only.
So vegan=yes would have to be added with a different editor without adding vegetarian (not sure how often this happens) _and_ vegan=yes has to be wrong. Looking at overpass, I found 2 places with this invalid combination in all Europe, both not tagged with StreetComplete.

And I doubt that restaurants would actually switch from vegan=yes to vegetarian=no.
So I am reasonably certain that no one would ever see such a dialog.

**Comment by mnalis** [comment]
@Helium314 oops, sorry, I used obsolete tags (missed the `diet:` prefix), don't know if I mislead you to use them in your query too (I've edited post now). Updated [overpass-turbo query](http://overpass-turbo.eu/s/1aSo) finds 90 "broken" combinations. I don't know how to easily check if any of those changes were made with StreetComplete though (please share a query if you do!)

Anyway, if dialog is too much effort, we could at least remove `diet:vegan` tag (or force `diet:vegan=no` if that is preferable) when we map `diet:vegetarian=no` answer ? That would make sure there is no invalid data, at not much effort.
Does that sound reasonable?

**Comment by Helium314** [comment]
@mnalis I only looked in Europe, which explains part of the difference. Second, your query also finds vegan=only and vegetarian=no, which can never be added with StreetComplete (if one tag exists, the quest for the other will not appear).
And interestingly, every of the "bad" places I checked showed the invalid combination was added by OpenVegeMap.

> Anyway, if dialog is too much effort, we could at least remove `diet:vegan` tag (or force `diet:vegan=no` if that is preferable) when we map `diet:vegetarian=no` answer ? That would make sure there is no invalid data, at not much effort.
> Does that sound reasonable?

Sounds good, and should be simple to implement
