### ISSUE TITLE
barrier=gate shines through buildings

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3250]
**How to Reproduce**

In SC look at a `barrier=gate`, e.g. https://www.openstreetmap.org/node/7553279682 , then tilt the view such that a building would block the view of this `barrier=gate`. The gates "shine" through buildings. This was probably not intended. It happens in both day and night mode.

![barrier_gate-fs8](https://user-images.githubusercontent.com/4726277/132054969-c1726225-6ee1-4e93-bf4c-accba3feab71.png)

**Versions affected**

SC 33.2 on Android 10

**Comment by westnordost** [comment]
Can't be fixed, if I remember correctly, because points (and text) are always drawn on top
