### ISSUE TITLE
A separately mapped `barrier=kerb` is ignored

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#3255]
A separately mapped `barrier=kerb` is ignored, the tags `barrier=kerb`, `kerb`, `tactile_paving` get added to the intersecting node, even if `barrier=kerb` or more tags exist on the separate `barrier=kerb` line.
It would make sense to add these tags to the separate line (or split it if it is too long or the values vary along the length.)

**How to Reproduce**
When a `barrier=kerb` mapped as a line intersects a sidewalk (`highway=footway` + `footway=sidewalk|link`) the information of the `barrier=kerb` tag  and others get asked for / added to the intersecting node.
![image](https://user-images.githubusercontent.com/34302971/132092135-cbedae04-b651-4f77-9db6-cc33998c7fc2.png)

**Versions affected**
StreetComplete 33.2

**Comment by joshinils** [comment]
As a sidenote: these short lengths of kerb, sidwewalk, footway=link etc. can be rather small, and thus difficult to distinguish from oneanother on the map in the app, so more detail in the map or the possibility to underlay imagery would be great! also seeing them all at once for a reference relative to one another would also be great! sometimes i just see a quest "somewhere" beside an intersectiton i just added details to, and it is hard to know which way the quest is referring to

**Comment by matkoniecz** [comment]
> get added to the intersecting node

That is deliberate, as kerb is often lowered for the crossing.

So it is asked and tagged there.

**Comment by joshinils** [comment]
> That is deliberate, as kerb is often lowered for the crossing.

so streetcomplete deliberately duplicates the information of the way on a node that is part of a way which has the same information?
even if the crossing kerb line is very short and only covers the lowered part?

**Comment by matkoniecz** [comment]
> even if the crossing kerb line is very short and only covers the lowered part

Is it a common and/or recommended way of tagging?

**Comment by westnordost** [comment]
>> even if the crossing kerb line is very short and only covers the lowered part

> Is it a common and/or recommended way of tagging?

That tagging wouldn't make much sense. That would be analogous to as if we would map a walled property with a gate by drawing a line tagged with `barrier=gate` across the road (but also completely leave out the `barrier=wall`).

Looking at taginfo, it seems to be use by some though: 16% of all `kerb=*`  are tagged on ways (the rest on nodes).

**Comment by matkoniecz** [comment]
> 16% of all kerb=* are tagged on ways

Note that it may represent longer kerbs, not just short section lowered for crossing

**Comment by joshinils** [comment]
https://overpass-turbo.eu/s/1aUC at least in some parts of berlin most kerbvs are mapped as ways, and there are also separate sidewalks present.
i don't know what the negative of mapping the info twice would be, but i feel like there has to be a negative

**Comment by matkoniecz** [comment]
> most kerbvs are mapped as ways, and there are also separate sidewalks present

This is not a problem. This would be a problem only if

- crossing-specific kerb would be a separate way (about 1 to 3m long sometimes longer). Now that kerb is often lowered just for the crossing (unable to check this even in linked area - overpass turbo crashes my mobile browser). 
- this would be accepted and recommended 
- tagging kerb info on node on footway way would be considered as unacceptable by consensus of mappers

**Comment by matkoniecz** [comment]
> most kerbvs are mapped as ways, and there are also separate sidewalks present

This is not a problem. This would be a problem only if

- crossing-specific kerb would be a separate way (about 1 to 3m long sometimes longer). Note that kerb is often lowered just for the crossing (unable to check this even in linked area - overpass turbo crashes my mobile browser). Long way of `barrier=kerb` with node where it crosses footway is fully fine.
- and kerbs mapped as way would be without `kerb` tag
- and this way tagging without tags on node attached to the way would be accepted and recommended 
- and tagging kerb info on node on footway way would be considered as unacceptable by consensus of mappers

**Comment by matkoniecz** [comment]
And if current behaviour is not ok, then it would be necessary to do asking on short kerb ways. There is no reliable way to verify by SC mapper what exactly is represented by such short kerb way.

**Comment by westnordost** [comment]
@matkoniecz At least in Neukölln, it is indeed

https://overpass-turbo.eu/s/1aVb

Neukölln was super-micromapped as part of the [Straßenraumkarte Neukölln](https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=parkingmap#16/52.4801/13.4421).

---

So yes, in cases where very short stretches of kerb are tagged with `kerb=lowered` or whatever, recording this information additionally on the node is a duplication. However, a duplication that **cannot be avoided**:

The reason is that it is not a mistake to tag `kerb=raised` or similar on the whole kerb line and only tag on the vertex where the footway crosses the kerb line that there is a lowered kerb here. In fact, that is the most common way to tag it. (This is the same mapping scheme as for `barrier=wall`s where  `barrier=entrance` are mapped on vertices of that wall.)

This means that for any application (like StreetComplete), it is not possible to find out whether on any point where a footway crosses a "raised" kerb line, there is really a raised kerb, or it simply hasn't been tagged on that node yet that it is a lowered kerb.
