### ISSUE TITLE
Tag maxwidth on traffic_calming=choker (and similar)

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3258]
### General
Affected tag(s) to be modified/added: [maxwidth](https://wiki.openstreetmap.org/wiki/Key:maxwidth)
Question asked: **What is the max width allowed through this XY?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose - Allows you to route a larger vehicle through obstructions
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - Can operate in the same way as maxheight when it's not signed.
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - Can operate in the same way as maxheight when it's not signed.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Same idea as the maxheight quest

**Element selection:**
https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dchoker

Presumably also the others in these two:
https://wiki.openstreetmap.org/wiki/Key:traffic_calming#By_causing_lateral_deviation
https://wiki.openstreetmap.org/wiki/Key:traffic_calming#Both_lateral_and_vertical_deflection

Although island and chicane may not always be signed.

**Metadata needed:** 
Same idea as the maxheight quest, it can use the existing metric/imperial selection.

**Proposed UI:**
Same idea as the maxheight quest

### See also:
#2713 which was more generic and about things like bollards blocking the way, it also required measuring where most of these are signed so far easier to answer.

**Comment by andrewharvey** [comment]
> where most of these are signed so far easier to answer

Probably regional, all the ones around me are not signed with a distance. Even lacking siganage I'm still for having such a quest but probably not enabled by default for regions which aren't signposted (I can use the measure app on my phone to measure the distance)

**Comment by mnalis** [comment]
(related discussion about methods and problems/solutions with measuring widths: https://github.com/streetcomplete/StreetComplete/issues/698)

**Comment by westnordost** [comment]
What choker wouldn't be broad enough to still allow any kind of vehicle? Do you think there are chokers that are too narrow for SUVs or trucks?

**Comment by Helium314** [comment]
Does it actually count as established if the combination of `traffic_calming=choker` and `maxwidth` does not occur on any element in OSM? See https://taginfo.openstreetmap.org/tags/traffic_calming=choker#combinations

**Comment by peternewman** [comment]
> Probably regional, all the ones around me are not signed with a distance. Even lacking siganage I'm still for having such a quest but probably not enabled by default for regions which aren't signposted (I can use the measure app on my phone to measure the distance)

> (related discussion about methods and problems/solutions with measuring widths: #698)

Ah okay @andrewharvey . How do you know if you can drive through them then, or do you just have to guess and hope you don't scrape?

From my understanding maxwidth is the legal signed width, whereas maxwidth:physical is for measured widths.

> What choker wouldn't be broad enough to still allow any kind of vehicle? Do you think there are chokers that are too narrow for SUVs or trucks?

See some van widths here:
https://www.smarthire.co.uk/vehicle-dimensions.htm

And a signed 6'6" choker here:
https://goo.gl/maps/mgYYbuGK3zetzoEq5

Various websites are a bit vague about with or without wing mirror type widths, but for a Luton Box Van you can see the *internal* width is > 6'6". I think our recent Long Wheelbase Transit was labelled as 2.01m on the dash, so too big.

> Does it actually count as established if the combination of `traffic_calming=choker` and `maxwidth` does not occur on any element in OSM? See https://taginfo.openstreetmap.org/tags/traffic_calming=choker#combinations

I don't know if it should actually be on the way, not the node (like bridges seem to be), but there aren't zero, it's on 198 on the GB taginfo, which is either 5% or 0.31% depending on which side, although that's looking at all traffic calming:
https://taginfo.openstreetmap.org.uk/keys/traffic_calming#combinations

It's also on the no value worldwide list, with 330 instances, so 2/3 of all tagging is currently in the UK:
https://taginfo.openstreetmap.org/keys/traffic_calming#combinations

Exploring a little of Belgium they aren't quite so extreme the ones I found, more just half a chicane.

**Comment by andrewharvey** [comment]
> Ah okay @andrewharvey . How do you know if you can drive through them then, or do you just have to guess and hope you don't scrape?

Well they are designed such that all normal vehicles can travel through, the same width as a normal traffic lane. eg https://www.mapillary.com/app/?pKey=376973660296811

If they are mostly signposted like in your example then that seems like a good quest to enable by default.

> From my understanding maxwidth is the legal signed width, whereas maxwidth:physical is for measured widths.

Perhaps the quest should then ask what the signposted width is, asking just for the width you might have people measuring the physical width.

**Comment by westnordost** [comment]
@peternewman interesting, that looks dangerous.

**Comment by peternewman** [comment]
> Well they are designed such that all normal vehicles can travel through, the same width as a normal traffic lane. eg https://www.mapillary.com/app/?pKey=376973660296811

Ah yeah, we have some like that too, or at least chicane style.

We also have random things like this:
https://goo.gl/maps/aaW74qmkcK7rp52g7

A pair of one way chokers and a wider middle bit which is legally restricted to buses. 

> If they are mostly signposted like in your example then that seems like a good quest to enable by default.

I think they generally are from my experience. I guess you need to signpost them or the council would get sued for damaged vehicles.

> Perhaps the quest should then ask what the signposted width is, asking just for the width you might have people measuring the physical width.

Yes, good point. The height one asks and shows a sign to make it clearer.

One thing, which I know was discussed in the other issue before, having looked I've seen signs showing just imperial, and both on Google StreetView, so in the UK at least, the app would either need to be imperial only (whereas I see the height one is metric), or allow both sets of values to be entered.

> @peternewman interesting, that looks dangerous.

A little, although as it's signed you just have a sign in the vehicle so you know. I think it's mostly to stop bigger trucks going down small side roads. It's no different to bridge heights where HGVs/lorries and buses are regularly driving into them, which also causes impact on whatever is going over the bridge, at least one of these just damages the vehicle and blocks the road for a bit.

**Comment by peternewman** [comment]
Now we've got the road width quest, can't we add this quest because we can then fall back to a (ideally separate) version of the AR width measuring quest when we get to a choker which isn't signed?

Personally I'm not really interested in measuring the width of some average road, but chokers and bridge heights which aren't signed would seem to be very useful.
