### ISSUE TITLE
Add a Take Picture button to the menu of the quest to fill hours of work.

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#3263]
Hours editor is great for filling, uncomplicated tables (where there are no breaks, and the institution opens and closes at the same time)

But, for example, take this schedule (open in JOSM)
<details>
  <summary>Example</summary>
<img width="491" alt="Снимок экрана 2021-09-05 в 23 42 05" src="https://user-images.githubusercontent.com/25708359/132140919-27afd99d-2989-4cd1-ab91-1a1fd86311ee.png">
</details>

In StreetComplete it still doesn't look that scary, but it's already tedious to fill in.
<details>
  <summary>StreetComplete</summary>

![Screenshot_2021-09-05-23-45-31](https://user-images.githubusercontent.com/25708359/132141109-2d49bc29-35a9-405e-8df7-bda874c79044.png)

</details>
But if the place is going to be open on weekends, you might have to add a few more lines. It takes a lot of time, and it's so easy to make a mistake. 

You can leave a note with a photo, but that takes four clicks. And what's more, the user may not know that by answering "I don't know" you can add a note with a photo, because the user actually sees the hours of operation. 

So I propose to take the Take Picture button to the start screen of the quest.

The options I came up with were:
<details>
  <summary>Button in the quest title</summary>

![sc6](https://user-images.githubusercontent.com/25708359/132141233-9742e4ee-6ec1-459d-ab7a-43e5657e7c88.png)

</details>

<details>
  <summary>The button next to the add clock button.</summary>

![sc_hours](https://user-images.githubusercontent.com/25708359/132141256-3e9025bb-8acc-4867-b2af-bba57da371c3.png)

</details>

<details>
  <summary>Button next to the Other options button.</summary>

![sc5](https://user-images.githubusercontent.com/25708359/132141424-0989b18f-6d5a-48e5-9e8d-e1e289b71124.png)

</details>

**Comment by westnordost** [comment]
In case you find it more efficient to add the opening hours with JOSM, the better workflow than to add such a feature to StreetComplete would be to just take a photo, with the photo app.

Photos can even be imported in JOSM if they include GPS coordinates.

**Comment by deevroman** [comment]
The problem is that, for example, in shopping malls a lot of POIs in one place GPS will not be able to accurately indicate the location of the photo. Especially in a building. 

In addition, you will need to switch to the camera app, and then hide the quest on the map. 

Linking a photo to a POI helped when adding a clock through a more convenient editor to the user himself or a more experienced user, but who has not been near the place.

**Comment by smichel17** [comment]
> In addition, you will need to switch to the camera app, and then hide the quest on the map.

The dialog where you hide the quest should also have an option to leave a note. The note dialog has a shortcut to open the camera app and the quest will be hidden when you submit the note, so I think the process is reasonably streamlined.

**Comment by jabdoa2** [comment]
I would second this one. Often it would be easier to take a photo and complete the timetable later. Especially when there are a lot of shops or when it is crowded.

**Comment by mnalis** [comment]
@jabdoa2 it is already possible to take picture of opening hours, you just need to click `other answers`, `Can't say` and confirm with `OK` when it asks you if you _"want to leave a note instead"_. Then you can leave a note with picture(s).

This issue is mostly about discoverability (it is not a very intuitive to click on `Can't say` in order to take a photo - at least for someone who has never used StreetComplete and found out it is always an option there to leave a note), and (maybe) to reduce number or clicks needed to take a picture by one or two.
