### ISSUE TITLE
Easier sorting of quest priority

### ISSUE THREAD

**Issue by Moohan** [streetcomplete/StreetComplete#3264]
**Use case**
Sorting quests has always been laborious and could be multiplied with 'quest presets'. In a single preset I might want cycling quests to be prioritized, then housing, then road, etc. but in another, I might want a different order. Currently, I would have to drag-drop each quest individually to achieve the desired order.

**Proposed Solution**
Long press on a quest brings up a small menu with 2 options: 'Send to top', and 'Send XX quests to top' where XX is the quest type e.g. cycling, accessibility, building, etc.

**Comment by westnordost** [comment]
The feature of sorting of quest priorities is actually a candidate for removal (after an evaluation period), so no features that build upon it will be implemented.

Did you see the default sort order in v34? There should be little reason to change this order.

**Comment by mnalis** [comment]
> The feature of sorting of quest priorities is actually a candidate for removal (after an evaluation period)

While I agree that this issue (while nice idea) is probably not **that** important when considering adding complexity to UI (after all, you usually only setup the Presets once, so even if it is not the easiest, it is not **such** a big deal); I would ask to please do not remove the quest reordering functionality. It works, and it is useful to several people in discussion (see below https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-879866839).

Not everyone in _every situation_ wants the ***"solve the easiest quests firsts"*** strategy. It is great that it is default now, but sometimes people have different priorities (as can be seen in linked thread).

**Comment by smichel17** [comment]
I suggest we create a GitHub Discussion about the potential removal of sorting and design options in that space, since it seems to pop up in many different issues. I'd make it myself but I don't think I'll get around to that before something has been decided :)

**Comment by westnordost** [comment]
So anyway, I do not plan to implement this, even if the quest sorting should stay
