### ISSUE TITLE
Remove leisure=marina from wheelchair quest

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3270]
1) sailing with people on wheelchair is a quite special operation - and getting such person via gangplank to the yacht is going to trump any marina inaccessibility

2) it is unclear what is supposed to be checked by  mapper

3) marinas are large enough that parts can be accessible and parts not and that is better to be mapped by mapping `highway=steps` etc

Note that it is distinct from trading wheelchair accessibility of ferries and ferry terminals

**Comment by matkoniecz** [comment]
I can send some specific images of location where I got this quest and 

- have no idea how to answer
- see no value in that answer, no matter what interpretation will be taken
- situation is confusing to me,  would be even worse to a newbie

**Comment by westnordost** [comment]
Ok

**Comment by westnordost** [comment]
Some marinas have restaurants, some have toilets. But they could be mapped separately anyway.

**Comment by matkoniecz** [comment]
In this case it makes sense to ask and tag on restaurants and toilets
