### ISSUE TITLE
Map animations are sometimes skipped

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3275]
There are two parts to this bug.

### How to Reproduce

It can be reproduced with any two animations, but this is the easiest/most obvious repro.

1. "Fling" your finger across the screen to pan the map, so that there is some momentum and the map continues moving after you raise your finger.
2. While the map is still moving, press the gps button
    - You need a gps fix for this, but it's not necessary in general; you can also reproduce with the zoom buttons.

**Expected:** Any of these:
- The map will immediately come to a complete halt (no more momentum), then pan normally back to my location.
- The first animation will finish and then the map will pan normally back to my location.
- Something fancier where the animations are composed (but that's a lot of work to implement).

**Actual:** The map finishes moving due to momentum, then instantly snaps back to my location, skipping the animation.

**Versions affected:** Android 7.0 and StreetComplete v34.0, but it's been around for a while (maybe forever)

### I propose not to fix this (unless it turns out to be easy)

- It is a minor annoyance.
- I expect it is relatively difficult to fix, especially without introducing other bugs, like some actions only being halfway applied.
- It may be resolved with #3123 

### How to Reproduce

I am not sure that this is 100% reliable, but it was this particular time when I tested:

1. Same as above
2. Same as above
3. Press the zoom in/out button, or any other tap-button animation (compass button to tilt/rotate the map when unlocked, zooming to focus on the quest)
    - Panning and other "gesture animations" are not affected

**Expected:** Animation plays as normal, since there is no overlapping animation.

**Actual:** Camera instantly snaps to end state, as if it were still animating like above.

Sometimes panning around to arbitrary locations will fix this after some time.

I'm not sure if it's related, but also sometimes zooming to a quest simply doesn't happen, and the quest geometry ends up covered by the quest form.

One or both of these may be an upstream issue, I'm not sure.

**Comment by smichel17** [comment]
I'll likely look into this eventually, but it's way far down my priority list; it won't be for a few months at least.

**Comment by matkoniecz** [comment]
I am pretty sure that it is Tangram issue and maybe intentional.

**Comment by westnordost** [comment]
> I propose not to fix this (unless it turns out to be easy)

Ok.

Yeah the ... multiple-animations-at-the-same-time is not perfect. tangram-es does not support it at all, the CameraManager is some kind of compatibility layer to enable exactly that. Apparently there are small issues with that, but I will not fix them because #3123

**Comment by smichel17** [comment]
It feels like you have both responded to "bug" 1, which I proposed not to fix, and skipped over responding to bug 2, which is about a **single** animation being skipped, i.e. the map getting "stuck" in a state of skipping animations.

**Comment by smichel17** [comment]
Perhaps this is a better demonstration of the problem

https://user-images.githubusercontent.com/6563664/132863821-5bbc33fb-5459-42b3-909a-6fe92726f69a.mp4

**Comment by smichel17** [comment]
> I am pretty sure that it is Tangram issue and maybe intentional.

I am also pretty sure that "bug" 1, reproduced at 00:07 in the recording above, is intentional.  
I am even more certain that bug 2, reproduced afterwards, is not.

While playing around to get the recording, I found that the fix is to do another "fling" of the map and let it come to a complete stop. So basically, the probably-intentional lock-out is not being lifted when the fling is "interrupted" by an animation.

**Comment by smichel17** [comment]
I should not have gotten sucked into looking at this, but I did. I'll stop here, but my current best guess is that it might be related to one of these callbacks, where we respond differently depending on whether there is currently an animation playing.

https://github.com/streetcomplete/StreetComplete/blob/4d5fa6d5b211f3f7e3c5330068cfff43feff3bc9/app/src/main/java/de/westnordost/streetcomplete/map/tangram/KtMapController.kt#L103-L112

https://github.com/streetcomplete/StreetComplete/blob/4d5fa6d5b211f3f7e3c5330068cfff43feff3bc9/app/src/main/java/de/westnordost/streetcomplete/map/tangram/KtMapController.kt#L121-L131

Docs describing the callbacks here: https://tangrams.readthedocs.io/en/master/API-Reference/android-sdk/0.11.0/com/mapzen/tangram/MapChangeListener.html
