### ISSUE TITLE
More details for railway crossings

### ISSUE THREAD

**Issue by 351293** [streetcomplete/StreetComplete#3276]
StreetComplete could ask for more details about railway crossings. (railway=crossing AND railway=level_crossing)
Example given in german:
"Gibt es an diesem Bahnübergang Andreaskreuze?"
crossing:saltire=yes/no

"Gibt es an diesem Bahnübergang Lichtzeichen?"
crossing:light=yes/no

"Gibt es an diesem Bahnübergang akustische Signale?"
crossing:bell=yes/no

And for railway=crossing only: "Gibt es an diesem Bahnübergang Umlaufgitter?"
crossing:chicane=yes/no

**Comment by peternewman** [comment]
It would be best to use the relevant issue type for these @351293 , or at least edit them to use the quest suggestion template:
https://github.com/streetcomplete/StreetComplete/blob/master/.github/ISSUE_TEMPLATE/quest-suggestion.md

e.g. does anything currently make use of this data?

**Comment by matkoniecz** [comment]
> crossing:bell=yes/no

Sounds usable by blind people, but requires waiting for a train

**Comment by 351293** [comment]
> It would be best to use the relevant issue type for these @351293 , or at least edit them to use the quest suggestion template:
> https://github.com/streetcomplete/StreetComplete/blob/master/.github/ISSUE_TEMPLATE/quest-suggestion.md
> 
> e.g. does anything currently make use of this data?

Yes, I realised that I used the wrong template after opening this issue, but I don't know how to correct it. I'm not really used to github and my english skills are not that good.. I someone can correct my mistake it would be good.

**Comment by 351293** [comment]
> > crossing:bell=yes/no
> 
> Sounds usable by blind people, but requires waiting for a train

Yes, sounds für blind people, chicane for cyclists (implies dismount), saltire and light would improve map data while it is pretty easy to verify for users.

**Comment by westnordost** [comment]
There were quest suggestions for this before, you should search for an issue before you create one. They are closed. Please understand that we can not have tickets for the same things over and over again. If you have something to contribute, add it to these (closed) tickets.

**Comment by peternewman** [comment]
> Yes, I realised that I used the wrong template after opening this issue, but I don't know how to correct it.

For next time you can (ideally click the relevant button), but also edit your post, copy this:
https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/.github/ISSUE_TEMPLATE/quest-suggestion.md

Paste it into there and fill in the blanks.
