### ISSUE TITLE
Enhance Quest: "What barriers are used at this railway crossing?"

### ISSUE THREAD

**Issue by 351293** [streetcomplete/StreetComplete#3277]
In my opinion 2 things were missing in the "What barriers are used at this railway crossing?"-Quest:
- Also railway crossings for pedestrians (railway=crossing) can have barriers, so the quest should also show up on railway=crossing, not only at railway=level_crossing.
- In GB some crossings were secured with gates (crossing:barrier=gate). This answer should be available in GB.

**Comment by westnordost** [comment]
Needs research (overpass) on what kind of barriers are to be expected on pedestrian barriers.

**Comment by westnordost** [comment]
Option for pedestrian barrier should also include `crossing:chicane`

**Comment by 351293** [comment]
> Needs research (overpass or sophox) on what kind of barriers are to be expected on pedestrian barriers.

As I work with railways as daily business: Most common is chicane, full and gate.

**Comment by westnordost** [comment]
...and none. So we have 4 options, that's cool, so they fit into one line.

Are you interested in contributing the illustrations for chicane and gate? The current graphics are here:
https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics/railway%20crossing%20icons

**Comment by matkoniecz** [comment]
> As I work with railways as daily business: Most common is chicane, full and gate.

It is about situation worldwide, across different countries.

BTW, note that Sophox data is missing most of OSM data

**Comment by westnordost** [comment]
So how is this named in English?

https://de.wikipedia.org/wiki/Umlaufgitter#/media/Datei:Umlaufgitter.jpg

**Comment by 351293** [comment]
> So how is this named in English?
> 
> https://de.wikipedia.org/wiki/Umlaufgitter#/media/Datei:Umlaufgitter.jpg

In OSM it's called a chicane

**Comment by westnordost** [comment]
Hmm, if there is a chicane but nothing else, would it be tagged with `crossing:barrier=no` or `crossing:barrier=yes` ?

**Comment by matkoniecz** [comment]
> https://de.wikipedia.org/wiki/Umlaufgitter#/media/Datei:Umlaufgitter.jpg

It is a pedestrian chicane ( https://commons.wikimedia.org/wiki/Category:Pedestrian_chicanes ) in OSM known as `barrier=cycle_barrier` ( https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier )

chicane in OSM also will be https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dchicane

**Comment by 351293** [comment]
> Hmm, if there is a chicane but nothing else, would it be tagged with `crossing:barrier=no` or `crossing:barrier=yes` ?

Correct tagging would be:
crossing:barrier=no
AND
crossing:chicane=yes

**Comment by 351293** [comment]
> > https://de.wikipedia.org/wiki/Umlaufgitter#/media/Datei:Umlaufgitter.jpg
> 
> It is a pedestrian chicane ( https://commons.wikimedia.org/wiki/Category:Pedestrian_chicanes ) in OSM known as `barrier=cycle_barrier` ( https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier )
> 
> chicane in OSM also will be https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dchicane
> 
> > Hmm, if there is a chicane but nothing else, would it be tagged with crossing:barrier=no or crossing:barrier=yes ?
> 
> no idea

See my comment above. In this case it's tagged as crossing:chicane

**Comment by matkoniecz** [comment]
>  crossing:chicane=yes

If it is in use then it would be worth documenting at https://wiki.openstreetmap.org/wiki/Tag:railway%3Dcrossing

**Comment by westnordost** [comment]
It's mentioned here https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging

**Comment by matkoniecz** [comment]
> It's mentioned here https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging

added to wiki

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/142062328-5df4f583-27cc-4d83-ae3b-58deec43950b.png)
