### ISSUE TITLE
Logging in onto a new phone should not show again all achievement notifications

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3282]
**Use case**
Showing say 50 notifications about quests is an irritating and results in a pointless drudgery on dismissing all of them

**Proposed Solution**
Do not show quests that were awarded as result of updating statistics from external service. In rare cases it may result in missing some notifications, but it seems better over spam on a new device

![screen01](https://user-images.githubusercontent.com/899988/132984023-71929149-dc76-4ff3-820e-74434bd3c07b.png)

**Comment by mnalis** [comment]
I remember it happening to me once (way back in the past), but never since, although I've uninstalled and installed freshly StreetComplete (and forks) and logged into it dozens of times on several different devices. 

Maybe it only happens in some specific circumstances?

**Comment by matkoniecz** [comment]
In this case I 

- did it on emulator
- solved quests before logging in
- had quite large amount of edits made both in SC and in general what may have increased various processing times

**Comment by westnordost** [comment]
I think it would additionally be fair to remove any notifications for new achievements on a new app-start. They are not that important, and if the user chose not to tap on these then, he'll also not choose to tap on them now.

**Comment by westnordost** [comment]
I'd classify this as a bug because IIRC there is even code in place that should prevent this.
