### ISSUE TITLE
Imprecise German translation of #574

### ISSUE THREAD

**Issue by jabdoa2** [streetcomplete/StreetComplete#3283]
**How to Reproduce**

Switch app to German and find an unmapped crossing. It will ask you if the traffic light is "on-demand" which is not the same as "button operated". Unfortunately, the latter is tagged in OSM. I definitely tagged a few crossing incorrectly because of this because some lights will turn green for pedestrians no matter if you press the button or not. Those would not qualify as on-demand but still as button-operated as there is a button.

https://github.com/streetcomplete/StreetComplete/issues/574

**Versions affected**
34.1

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app - translations can be updated by anyone

(note: I am unable to read this language, so I am unable to day is there a problem here or not)

**Comment by westnordost** [comment]
Ich habe es geändert in "Gibt es an dieser Ampel ein Knopf um als Fußgänger grün zu bekommen?"

**Comment by FloEdelmann** [comment]
I took the liberty to fix some grammar issues ("ein" -> "einen", missing comma before "um", uppercase " Grün") and change the wording to "Gibt es an dieser Ampel einen Knopf, um als Fußgänger Grün anzufordern?".
