### ISSUE TITLE
Leaving custom notes location have random location error

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3284]
IOW, **_"Notes are left on quite different locations then indicated by Note marker on the screen"_**

When one does long-press on screen, there is a possibility to leave an OSM note (and adjust its exact location on the map). However, OSM Note does not happen at that indicated location, but with some random drift of dozens up to hundred of meters. That makes it pretty problematic to be useful.

I have a feeling that this positional error might have been happening less before (I might have said not at all, but now when I think about it I recall some situations where I assumed I have just made an error, but never went to investigate), but I could be wrong (maybe I just didn't try to use it that much, or phone model / language / Android version makes a difference).

**How to Reproduce**
Long press on the screen, adjust note if needed (or not), and leave note. Firstly I assumed I just made an error when leaving note, but it become obvious the positioning error is happening way to regularly for that. Although sometimes there is no noticable error at all (eg. https://www.openstreetmap.org/note/2850474, https://www.openstreetmap.org/note/2850551, https://www.openstreetmap.org/note/2850527 all point to the pretty much the same point). I could not determine why is there sometimes no error, when there is smaller error, and when there is a bigger positional error.

Here are for example 3 notes made with same phone, all 3 left at the same location (path 3-way split)
- https://www.openstreetmap.org/note/2850480 - left in OsmAnd, with perfect precision.
- https://www.openstreetmap.org/note/2850556 - left with SC 33.0, drifts some 20m into the sea, even if screen shows it exactly at crossing
- https://www.openstreetmap.org/note/2850533 - left with SC 34.1, drifts some 42m into the sea, even if screen shows it exactly at crossing

So I've taken a screenshot just before leaving the Notes to be sure it's not me:
![test7_33_0](https://user-images.githubusercontent.com/156656/133169704-62c46d02-b05c-4768-b92c-54f6b3d8e152.png) ![test7_34_1](https://user-images.githubusercontent.com/156656/133169698-9c22caad-9e52-40ce-8656-2f55b73c9925.png)

Even if there was GPS reception error, it should not matter, as notes are user-draggable and positioned at exact map location at maximum zoom in. Notes should be left at position indicated by the marker, right?

(there are more examples, I can provide them with screenshots for most of them if needed)

**Versions affected**
Android 6.0.1 (MIUI 10.2)

**Comment by smichel17** [comment]
I think I've got it, give me a moment to test.

**Comment by smichel17** [comment]
Confirmed, I think. It happens when you are following your gps position before the note. It happens here:

https://github.com/streetcomplete/StreetComplete/blob/fe895b7a5d20339cf920e90b0629f1b565897c3f/app/src/main/java/de/westnordost/streetcomplete/map/MainFragment.kt#L467-L476

- Earlier, when you long-press on the map and click "create note", we stop the map from following your position.
- The function above gets called when you press OK to submit the note.
- `screenPosition` in the arguments is the X and Y coordinates of the note pointer on your device's screen.
- On the last line quoted, we ask Tangram (though a couple layers of wrappers) for the Lat/Lon of those coordinates on the screen.
- :exclamation: On the first line of the function, `closeBottomSheet()` resumes following your location! This scrolls the map back to where you are, and so the screen coordinates are pointing at the wrong place on the map.
    - I imagine some of the wackier offsets would happen if you're using compass mode.

**Comment by timothywashere** [comment]
I thought I was going crazy with my notes all over the place.
Is the workaround for this issue to stand exactly still whilst making a note?

**Comment by smichel17** [comment]
The workaround is to disable "follow mode" (e.g. by scrolling the map) before creating a note. Or to create a note only directly on top of yourself, but that's less practical :)

**Comment by westnordost** [comment]
Thank you, @smichel17 ! I moved the line below that.

**Comment by mnalis** [comment]
Hope it will work! Although now `closeBottomSheet()` will never be called if `mapFragment` or `mapView` is `null` (if I correctly parse what the code does).

I don't know if that situation ever happens, but since it was handled in code before, I'd thought I'd mention it (if nothing else, a chance for me to learn a little)

**Comment by westnordost** [comment]
mapView or mapFragment may be null if the fragment has already been detached (has been destroyed). Then, there is no bottom sheet to close anyway anymore.
