### ISSUE TITLE
Can't zoom out when task selected

### ISSUE THREAD

**Issue by pschonmann** [streetcomplete/StreetComplete#3285]
![Screenshot_20210914-192028](https://user-images.githubusercontent.com/6333844/133304605-f64a6728-470c-4471-9e6e-086d7a36c5fc.png)
<!-- 
Please provide a clear and concise description of the bug. 

**How to Reproduce**
Tap on task with long description. Popup cover zoom buttons

**Versions affected**
Latest v 34.1

**Comment by FloEdelmann** [comment]
See and #3094, in particular https://github.com/streetcomplete/StreetComplete/issues/3094#issuecomment-889422166

Zooming is possible while the quest form is open, just not via the zoom buttons.
