### ISSUE TITLE
Allow people to convert paths to steps as an other answer

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3288]
**Use case**
I agree it's quite common when someone is mapping footways from imagery, they usually can't tell if there are steps or not, so this is well suited for someone doing StreetComplete to pickup on. And knowing if there are steps or not is incredibly important for pedestrian routing.
_Originally posted by @andrewharvey in https://github.com/streetcomplete/StreetComplete/discussions/3088#discussioncomment-1040091_

Isn't the main benefit that you can then go on to answer the remaining step quests about the new steps immediately and accurately (and without having to write more notes)?

In the same way as you can go e.g. diet related quest->shop isn't here anymore->different type of food place, name of shop, diet related quest on new shop etc
_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/discussions/3088#discussioncomment-1044090_

I've now personally seen steps just tagged as a path both in the countryside and in urban environments. Yes, you can leave a note, but either you need to try and populate which way up (which is particularly hard to describe), handrail, surface, count etc (i.e. reinventing the wheel and storing that information in a note). Or you need to wait for it to be re-tagged and then revisit it.

**Proposed Solution**
If I can split the way in streetcomplete already, would it be an issue to have the alternative answer "actually steps here" just go ahead and retag the footway as steps?

_Originally posted by @andrewharvey in https://github.com/streetcomplete/StreetComplete/discussions/3088#discussioncomment-1040349_

i.e. add an other answer to a (foot) way that it is actually steps
<hr>
There is a smaller, but possibly still valid argument for being able to do the reverse if you want to micro-map landings on long staircases you could split it and convert them back to paths. This might be more complicated, although IIRC the splitting steps thing would deal with removing most of any existing tagged info.

**Comment by westnordost** [comment]
For which quests do you suggest to do this?

**Comment by peternewman** [comment]
> For which quests do you suggest to do this?

Lit way
Path surface
I suspect instances of AddFootwayPartSurface where the bike is a ramp and the footpath is steps are sufficiently rare they could be handled with a note? Although if it's just a quest property like similar stuff is (does not exist etc), it might not hurt to add it.

If only we had some magic data on which tags were used on which quests :wink: although actually this wants the quest selection tags, not the output tags

Probably all the stair related ones, in terms of un-tagging stairs.

**Comment by timothywashere** [comment]
As above, for me it would be most commonly used on "What type of surface is this?" For footpaths and sometimes "is this way lit?".

**Comment by smichel17** [comment]
Thematically, it seems like it would fit well with the upcoming smoothness quest

**Comment by matkoniecz** [comment]
> I've now personally seen steps just tagged as a path both in the countryside and in urban environments. Yes, you can leave a note

I want to confirm this. I do this quite often, in various places. Switching to Vespucci is possible, but doing it fully in SC would be great.

**Comment by matkoniecz** [comment]
> For which quests do you suggest to do this?

Is lit, path surface

This happening for AddFootwayPartSurface indicates quite serious changes and likely needs full data access to resolve properly

**Comment by peternewman** [comment]
> Thematically, it seems like it would fit well with the upcoming smoothness quest

Agreed, seems like another obvious one to ask it on.

> This happening for AddFootwayPartSurface indicates quite serious changes and likely needs full data access to resolve properly

Presumably in my theoretical example they should be tagged as two separate ways with one foot only and one bike only, otherwise I guess the steps would apply to both?

Are there any other quests asked of paths? I assume a track shouldn't be tagged as a track if it's got steps in, so that would want a note and re-tagging too?

**Comment by matkoniecz** [comment]
> Presumably in my theoretical example they should be tagged as two separate ways with one foot only and one bike only, otherwise I guess the steps would apply to both?

Yes. Though in especially badly designed places cycleway can be actually interrupted by steps.

> I assume a track shouldn't be tagged as a track if it's got steps in, so that would want a note and re-tagging too?

Yes, if `highway=track` is actually `higway=steps` then it is likely mistagged in the first place. And looking at data around would be likely a good idea.

**Comment by smichel17** [comment]
> **another** obvious one

I was actually thinking of *only* asking it there.

For example, if the way is lit across the whole thing, why would it make sense to split it and convert to steps in that question? It seems it would make more sense to answer that it is lit, then split it later at a question where the single step matters to the answer.

Say the surface is different around the step (concrete instead of asphalt). You'd split the way twice and answer asphalt for the outer segments and concrete for the center. Then, when it asks the smoothness quest, you'd answer normally for the asphalt sections and answer "it is actually a step(s)" for the concrete section.

If the surface were all concrete, you'd wait to split the way until the smoothness quest.

The only downside I see, is if the stuff we tag for paths is not desirable to be tagged on steps, but I'm having trouble thinking of what those things are. And of course, we could remove those tags when converting to steps.

**Comment by matkoniecz** [comment]
> For example, if the way is lit across the whole thing, why would it make sense to split it and convert to steps in that question?

It would result in the same thing but...

If StreetComplete asks about nonexisting object, or describes similar but not actually existing object then

(a) mapper should notice mismatch
(b) mapper can be confused (optional)
(c) mapper should have option to answer in way matching reality - and if there is no direct option: leave note

**Comment by matkoniecz** [comment]
Note also other case: `highway=pedestrian smoothness=excellent` asking about lit status. That in part is actually steps. The solution "answer yes, and on smoothness quest actually split it" would fail as smoothness quest will be never asked!

**Comment by Lee-Carre** [comment]
I frequently encounter this stairs-tagged-as-path problem.

Most paths, in Jersey, seem to have been (armchair-)mapped from (outdated) imagery which lacked the resolution to make clear where there were steps.

Correcting this, in SC, would help a lot.

**Comment by smichel17** [comment]
> If StreetComplete asks about nonexisting object, or describes similar but not actually existing object

@matkoniecz I don't quite understand. Regardless of how the tagging actually is, in my mind stairs are a type of path. If a human asked me "is this path lit?" and pointed to a path with stairs on it, I would not be confused in the slightest. So I guess I don't understand how the mapper would notice a mismatch.

> Note also other case: highway=pedestrian smoothness=excellent asking about lit status. That in part is actually steps. The solution "answer yes, and on smoothness quest actually split it" would fail as smoothness quest will be never asked!

This seems like a contradiction. The wiki says [`smoothness=excellent`](https://wiki.openstreetmap.org/wiki/Key:smoothness#Values) means "Usable by (thin_rollers) roller blade, skate board and all below" and is "As-new asphalt or concrete, smooth paving stones with seamless connections, etc." How can stairs be usable by roller blades? Unless they are not stairs at all (e.g. a ramp). So, I would expect StreetComplete to follow the normal approach to mistagging: leave a note (or wait for the resurvey quest and *then* split the way).

**Comment by FloEdelmann** [comment]
Well, if we already implement it for the smoothness quest, it won't hurt to also add the "Here are actually steps" answer to the `AddPathSurface` and `AddWayLit` quests, too.

If someone notices that the question there mentions a path/way and not steps, they can directly correct the tagging via the new option. If they don't, they'll likely notice in the smoothness quest and correct it there. If they don't either, they at least not make the tagging mistake bigger than it was in the first place.

**Comment by peternewman** [comment]
> > **another** obvious one
> 
> I was actually thinking of _only_ putting it there.
> 
> For example, if the way is lit across the whole thing, why would it make sense to split it and convert to steps in that question? It seems it would make more sense to answer that it is lit, then split it later at a question where the single step matters to the answer.

That all relies on you gambling that the other tag hasn't been tagged already and means you have to know that, and have both quests asked.

> Well, if we already implement it for the smoothness quest, it won't hurt to also add the "Here are actually steps" answer to the `AddPathSurface` and `AddWayLit` quests, too.

Yes, I envisage it being the same as `isReplaceShopEnabled` and we just turn it on for all quests asked on a path.

Has anyone seen the reverse (aside from landings):

> There is a smaller, but possibly still valid argument for being able to do the reverse if you want to micro-map landings on long staircases you could split it and convert them back to paths. This might be more complicated, although IIRC the splitting steps thing would deal with removing most of any existing tagged info.

**Comment by Cj-Malone** [comment]
Today I wanted to change a track to a path. I could split it in the correct place via the surface quest, I changed it's type once I got home in JOSM. I don't know if this is common enough to deserve an option like this or carry on using notes.

**Comment by peternewman** [comment]
> Today I wanted to change a track to a path. I could split it in the correct place via the surface quest, I changed it's type once I got home in JOSM. I don't know if this is common enough to deserve an option like this or carry on using notes.

Aside from the track type quest, is there actually any difference in the questions asked @Cj-Malone ? The main thing I feel with steps is that there is a lot of other info to be gathered (which way is up, handrail, ramp, step count). Particularly expressing which way is up succinctly in a note, as well as the other info means it's a lot more work, whereas if you left a note when you got to the track type quest, you could survey all the other bits already (maybe lit isn't asked for tracks) and the edit when processing the note is pretty trivial and quick.

**Comment by Cj-Malone** [comment]
> processing the note is pretty trivial and quick.

True, but it's also infinitely quicker to fix something directly.


I think it's more a question of frequency. Things that happen more frequently obviously deserve more development time and UI space than things that are less frequent. I doubt tracks -> paths are actually that common, so isn't worth the UI space, but it's still good to get the idea out there and for others to share opinions.

**Comment by smichel17** [comment]
Something like layers, or my proposed alternative, [bulk edit mode](https://github.com/streetcomplete/StreetComplete/issues/2461#issuecomment-755638075), would allow for changing things like this, without adding options like this to every quest for paths.
