### ISSUE TITLE
Increasing the number of installations in the beta testing program - Google Play

### ISSUE THREAD

**Issue by olekstomek** [streetcomplete/StreetComplete#3289]
On Google Play, I can see that it is no longer possible to sign up for the beta version of the application. Are you considering increasing this number?

**Comment by westnordost** [comment]
Beta-release and public release are usually not far apart, maybe one week. That one week is reserved to weed out any critical bugs (and let the translators catch up with the newest strings). So the purpose of the beta is not "get the latest features now while it's hot!!" but rather to limit the damage in case something is wrong with the release (crashes or worse, corruption of data).

My experience is, that on Google Play, pretty much everyone will tap on that "join the beta" button. Back when the app had about 8000 users, about 70% were on the beta. That was not the intention. This is why I limited the number to 5000 users. Currently, there are 5628 beta users but at least, that's just about 25% of all users now.

So, right now I don't see any good reason to increasing that number. But what you can do, if you would like to test, is to download the releases from GitHub. You can watch any new releases and download and install the attached APK. Beta releases are also released on GitHub, e.g. https://github.com/streetcomplete/StreetComplete/releases/tag/v34.0-beta1 was released there and so will v35.0-beta1.
Once the public release is released, Google Play will automatically update your beta version.

**Comment by olekstomek** [comment]
Thank you for the interesting information and detailed explanation. Now I look at it from a different angle. :)

**Comment by smichel17** [comment]
Out of curiosity, do you have stats on how many of the beta users are on the latest version? As proxy for whether they're actively using SC-- I imagine a possible problem would be that some number of people stopped mapping but never left the beta. I guess that's when you can bump the limit.

**Comment by westnordost** [comment]
No

**Comment by jidanni** [comment]
I would add an explanation to https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete ,
else some users might think "Those guys' beta program filled up and they don't even know it. Sounds like an unmaintained app to me!"

**Comment by matkoniecz** [comment]
If someone manages to conclude that regularly updated app with full beta program is not maintained, then they would be unlikely to notice, read and comprehend such info.
