### ISSUE TITLE
Question "Is this still the bike path situation here?" does not match accompanying task

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3291]
**How to Reproduce**
Open a quest "Is this still the bike path situation here?" Note how the questions implies that you should check a given situation. Instead you are prompted to (re)map a situation.
![Screenshot_20210916-161013_Street%ADComplete-fs8](https://user-images.githubusercontent.com/4726277/133732429-23002231-2779-41c4-9ff8-d6a542205cdb.png)

Either the question or the task should be changed so that question and task fit to each other. Maybe the quest can (and should?) show the already mapped situation?

**Versions affected**
StreetComplete 34.1 on Android 10.

**Comment by FloEdelmann** [comment]
Can you share a link to a specific street on openstreetmap.org where this occurs?

Maybe this is related to #3129.

**Comment by Helium314** [comment]
See #2120: The current situation is considered ambiguous or invalid and thus not shown (sometimes showing one side pre-filled, but not the other).
This has become more freuqent since #3206 was implemented.

**Comment by ltog** [comment]
If it's any help, it's https://www.openstreetmap.org/way/26572503

So this was closed, since it's a duplicate of https://github.com/streetcomplete/StreetComplete/issues/2120, right?

**Comment by Helium314** [comment]
> If it's any help, it's https://www.openstreetmap.org/way/26572503

`cycleway=opposite_lane` seems to be the problem here. According to [wiki](https://wiki.openstreetmap.org/wiki/Tag:cycleway=opposite_lane) it should be combined with `oneway:bicycle=no` (missing on that way) and the side of the cycle lane is not specified.

> So this was closed, since it's a duplicate of #2120, right?

yes

**Comment by westnordost** [comment]
No, opposite lane is understood. It's missing what kind of name it is: Radstreifen or Schutzstreifen.

Am 19. September 2021 08:55:49 MESZ schrieb Helium314 ***@***.***>:
>> If it's any help, it's https://www.openstreetmap.org/way/26572503
>
>`cycleway=opposite_lane` seems to be the problem here. According to
>[wiki](https://wiki.openstreetmap.org/wiki/Tag:cycleway=opposite_lane)
>it should be combined with `oneway:bicycle=no` (missing on that way)
>and the side of the cycle lane is not specified.
>
>> So this was closed, since it's a duplicate of #2120, right?
>
>yes
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3291#issuecomment-922425207

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
