### ISSUE TITLE
Undo/revert last change

### ISSUE THREAD

**Issue by NicoHood** [streetcomplete/StreetComplete#3292]
**Use case**
Sometimes after finishing an action you realize, that you made a mistake. It would be good to revert that.

**Proposed Solution**
On the top left corner is a counter of how many things you have fixed. I'd expect an option to click on that and show a history of the fixed objects. Then you can click on an entry and reopen the question or chose to revert that action.

**Comment by matkoniecz** [comment]
Note that this functionality is available already, see bottom left.

**Comment by NicoHood** [comment]
Oh what a shame. My Display is broken at that place and I could not see it. Sorry for that!
