### ISSUE TITLE
Rotate map with compass

### ISSUE THREAD

**Issue by Jonisos** [streetcomplete/StreetComplete#3297]
**Use case**
When walking, turn the map according to the direction of the phone. This would help in easier localization of the quests. Also, most phones are longer in the vertical direction, therefore providing more quests in line of sight.

**Proposed Solution**

1. It could be done similarly to the osmAnd app, where pushing the compass button switches between different modes. The first mode would then be the top down mode, the second the also currently implemented 3D view and finally the third view would be top down with orientation according the phone rotation.

2. Or a simple option in the settings.

(Thanks for all your work :) )

**Comment by Jonisos** [comment]
Sorry I was dumb. I just noticed it's doing this already in the 3D view..I honestly never noticed this behavior before and just checked what happens when I push the compass. Didn't have GPS turned on so it did not rotate...

**Comment by mnalis** [comment]
for reference how to use it (if it seems confusing), see [this FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_to_use_2D.2F3D_and_GPS_following.2Frotation.3F)
