### ISSUE TITLE
The sports pitch lighting quest shows up during daytime

### ISSUE THREAD

**Issue by rYR79435** [streetcomplete/StreetComplete#3299]
The lighting quests for ways don't, as expected.

**Comment by FloEdelmann** [comment]
That is deliberate:

https://github.com/streetcomplete/StreetComplete/blob/04e4f80d29432922b7c21c3db00064ddf0ba05bf/app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.kt#L182

See also this conversation: https://github.com/streetcomplete/StreetComplete/pull/2872#discussion_r693349838

**Comment by rYR79435** [comment]
Thanks a lot. I should have searched outside of issues too...
