### ISSUE TITLE
update shouldn't breack user preferences

### ISSUE THREAD

**Issue by zlita** [streetcomplete/StreetComplete#3305]
Upon updating StreeetComplete to the version 34.0 the user quest priority preferences are overridden with the new default quest priority.
This seems to me to be a bad practice to break user preference. I think that it would be better to change it only if the user use the default priority, as a user which changed it will probably prefer his/her preferences to the new default (otherwise their preference would already be the same as the new default ones).
For me, it resulted in quite a loss of time to get back to preference which match my interest, I would guess that I'm not the only one.

**Versions affected**
34.0. I didn't check but the 34.1 and 34.2 versions are probably affected too.

**Comment by westnordost** [comment]
Yes, sorry that this caused you invonceniences. The versions are released however, nothing can be changed about this now.

And in any case, this had technical reasons too. For the quest presets implementation, it was compeletely changed how this feature worked internally.

**Comment by zlita** [comment]
I understand that we can't change the released version but is it possible to fix this for future release ? Some people could update directly to, let's say 34.3, without passing by intermediate version to avoid this.

I understand that it may be a bit too much work for just a few people but if someone indicates me where to look I could try to implement a fix to this problem.

**Comment by westnordost** [comment]
No, it isn't, because as said, the implementation changed completely. I.e. how the quest type order and the quest visibilities are stored.

**Comment by HolgerJeromin** [comment]
Westnordost once said that there was a time there were 80% of the users using the beta.
I do not expect there are many users which had not updated by now. And even less users which had visited the settings and therefor would loose quest order.
