### ISSUE TITLE
Self-Service laundrette: Places exist that do both

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#3309]
I got this feedback via email

> Just trying the latest Beta, it's looking good. I noticed the quest regarding laundry/ launderette. The Laundry in the screenshot, allows self service, or a a member of staff performing this service. Can I suggest that 'Both' is added as an option? This is very common, certainly in the UK.

![image](https://user-images.githubusercontent.com/4661658/134166951-82469299-f670-479d-b066-b659de32439f.png)

---

So, it should maybe be three answer options:
1. self service only -> `self_service=yes + laundry_service=no`
2. no self service -> `self_service=no + laundry_service=yes`
3. ??? -> `self_service=yes + laundry_service=yes`

Alternatively, the wording could be changed to specifically asking for self service (and not "Is this a...").

**Comment by FloEdelmann** [comment]
The third answer could be "Optional"

**Comment by chrisdebian** [comment]
Thanks for raising this, Tobias. 

In the UK, the term 'Service Wash' is used, when someone performs the service on behalf of the customer.

Could the third option be: "Self Service and Service Wash available"

Not sure whether this would make sense outside of the UK.

Thanks,

Chris

chris_debian

**Comment by westnordost** [comment]
Would this make sense?:

"Is this a self-service laundry?"
Yes | No | Optional

**Comment by mnalis** [comment]
> "Is this a self-service laundry?"
>  Yes | No | Optional

I'd probably _guess_ what was meant, but it does not sound as ideal answer (in combination with that question).

If the question was _**"Does this laundry provide a self-service?"**_ instead, then the _**"(it's) optional"**_ would sound much more understandable to me (as a non-native speaker).

Also, @kmpoppe suggestion is IMHO even more clear about what exactly is being asked (but requires a more verbose quest type).

**Comment by westnordost** [comment]
The quest is now:

**Does this laundry provide a self-service?**
[No] [Optionally] [Only]
