### ISSUE TITLE
Names for pedestrian zones within squares are removed by other mappers

### ISSUE THREAD

**Issue by WoOS2** [streetcomplete/StreetComplete#3310]
As can be seen on https://www.openstreetmap.org/changeset/111407406#map=17/36.78418/14.55700 some other mappers disagree with assigning names to highway=pedestrian within a square which already has (the same) name and remove them repeatedly (that's how I noticed).

One example is "Piazza Duca Degli Abruzzi" in the lower left corner of the change set map part. It has unnamed "highways" which cause StreetComplete to ask for their names. Fayor, which seems to maintain the region, is of the opinion that naming them is superflous as the square is already named. I am not so sure because not naming the "highways" leads to strange navigation instructions and routing is apparently what the "highways" are for (they in no way represent something on the square distinguishable from the rest of it).

I do not know what is the correct mapping practise (naming or not naming) but the current state, where rather high effort questions (finding sign, correctly typing the name into the app at least once) from StreetComplete are reverted back by maintainers should not continue.

**Comment by matkoniecz** [comment]
There are several parts here

1) is such name removal correct? If no, then it is not a SC problem. And in case of disagreement ideally it would be discussed elsewhere - OSM forum, mailing list, some other discussion place of italian community. with more general community. Not only with the closest highly active mapper and on some issue tracker.

2) In case that such name removal is correct then `noname=yes` tag should be applied

3) As far as I know such roads also should have `name` tags. Looking at random squares in Italy https://www.openstreetmap.org/changeset/111407406#map=19/40.84726/14.26644 https://www.openstreetmap.org/changeset/111407406#map=19/41.88135/12.48351 https://www.openstreetmap.org/changeset/111407406#map=19/41.89618/12.48341 https://www.openstreetmap.org/changeset/111407406#map=19/42.46050/14.22368 it seems that deleting name tags seems to be not done, but I am not active member of Italian mapping community

From first look it seems that someone removed correctly mapped `name` tag what should be changed (but I would recommend consulting Italian community!) and SC and your mapping is fine.

**Comment by westnordost** [comment]
Your SC mapping is fine and the way SC works is fine. Theoretically, all street ways within plazas could be inferred (with some effort) **IF** every street way within a plaza could be assumed to have the name of the plaza. (And thus, addresses of buildings within that plaza would have addresses like "Piazza Mercado 1", "2", "3" etc...)

In reality however, we cannot assume that. There could be a plaza at the intersection of two streets which does have a name, yet the (e.g. turned-pedestrian) streets that cross it though still retain their name and thus, the addresses still refer to those street and not the plaza.

**Comment by WoOS2** [comment]
Asked on the Italian forum (in English) in https://forum.openstreetmap.org/viewtopic.php?pid=841855

**Comment by matkoniecz** [comment]
I reverted mentioned edit in https://www.openstreetmap.org/changeset/111562588 and restored correctly mapped names.

In case that this edit was wrong or further reverts are needed - I would be happy to discuss it on https://forum.openstreetmap.org/viewtopic.php?pid=841855 or https://t.me/c/1124175268/41519 or in https://www.openstreetmap.org/changeset/111407406 or in https://www.openstreetmap.org/changeset/111562588

I will close this issue as StreetComplete is - as far as I am aware - 100% fine.
