### ISSUE TITLE
StreetComplete "stalls" on bad connections uploading a picture

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#3313]
I noticed that if I leave StreetComplete on auto upload I often see it stalling (the network connection) if I created one, two notes with pictures.

If I deactivate the automatic sync fetching new quests is perfectly fine, even if I only have 2G.

So I was wondering if StreetComplete could check how good the connection speed is, by timing the next fetch for quests. Only if the connection is reasonable fast it then tries to upload answers and pictures - while aborting if it takes too long, to not interrupt the downloads of new quests.

I'm currently mostly using the WiFi uploads only mode, but this often leads to dozens of answers in the queue as I forget to start the app when I'm home again.

**Comment by westnordost** [comment]
What do you mean with "stalls"? Anyway, I believe that such behavior would likely lead to users being confused why the thngs are not uploaded.

**Comment by Helium314** [comment]
I think problem is that you can't download while an upload is running. And when photos for notes are being uploaded, this upload can take quite long on a bad connection.

Maybe note sync could be done parallel to OSM data sync, having note and OSM data up/download serialized separately?
Then the data download would finish (relatively) quickly, but notes would only be downloaded once pictures are uploaded.
Though it would mean the download symbol may keep spinning for a long time after data download is finished...
