### ISSUE TITLE
Reword "Are pedestrians forbidden to walk on this road" quest

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3316]
**Use case**

There is a quest asking `Are pedestrians `**`forbidden`**` to walk on this road?`.

![Screenshot_20210907-125249_Street%ADComplete-fs8](https://user-images.githubusercontent.com/4726277/134622904-e26f51cb-d754-4a03-97a3-e3cc240ce7a0.png)

Since I (believe to) know that there is a tag `foot=*` involved in the background, this quest gives me some cognitive dissonance. (Answering `Yes` would be `foot=no` and vice versa.)

Further I believe that even for people not knowing the tagging scheme this is not the most intuitive way to ask the queston.

**Proposed Solution**

I propose to reword question and logic of this quest:

`Are pedestrians `**`allowed`**` to walk on this road?`

**Comment by matkoniecz** [comment]
> Since I (believe to) know that there is a tag foot=* involved in the background

BTW - you can confirm this by undoing edits (bottom left of the screen) and not confirming undo. It lists what was changed as result of the edit

**Comment by matkoniecz** [comment]
See also #1342 (found with https://github.com/streetcomplete/StreetComplete/issues?q=%22Are+pedestrians+allowed+to+walk+on+this+road%3F%22 )

Especially

> The wording of this quest has been changed intentionally with https://github.com/westnordost/StreetComplete/commit/32e20dd7c5658f39815a1545ab3dcd7a22f366c2
> In v10 the question was the way you propose it right now, but there was a huge discussion on the tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2019-February/042852.html about this quest which lead to the reworing of the question. Did you already read that thread?

I will close it as a duplicate for now (though if after reread of #1342 and https://lists.openstreetmap.org/pipermail/tagging/2019-February/042852.html you think that it should be changed again - please comment)

**Comment by smichel17** [comment]
One potential change, in translation: "Are pedestrians forbidden to walk...?" is unusual phrasing. "Are pedestrians forbidden from walking...?" would flow better.

**Comment by smichel17** [comment]
See also: #2472 (my suggestion at https://github.com/streetcomplete/StreetComplete/issues/2472#issuecomment-7572589490)

**Comment by ltog** [comment]
@matkoniecz : Thank you for the hint on how to see what a change in SC does. And also thank you for pointing out the discussion that was previously happening.

It was not clear to me that such extensive discussions already have taken place.

I disagree with @westnordost 's statement  at https://github.com/streetcomplete/StreetComplete/issues/1342#issuecomment-465286787
> As the default is that pedestrians are allowed on roads (and more generally in law: all is allowed unless forbidden), it is clearer to ask for it being forbidden.

but we can leave it at that. I guess there has already been spent more than enough energy on this...

Thank you all for working hard on making the best possible map database!
