### ISSUE TITLE
Add possibility to add (street, bus stop) names in some other languages for some countries

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#3317]
**Use case**
Most of the time, when I want to answer to street name, bus stop name, (and quite rarely place name) quests, I would like to give the answer in at least two languages. For example, in Russia, all is written in Russian (Cyrillic), and a transliteration in Latin. In Uzbekistan, it's written both in Uzbek, Russian, and Latin transliteration. In France, it's in French and, in some region, in the regional language too : Creole, Breton, Occitan, Corsican, Alsatian, etc. ..

See a Russian bus stop name for example.
![IMG_20210921_121148](https://user-images.githubusercontent.com/54240434/134627646-bdc4cb6f-9ac2-458b-827a-bc611cc0b8a7.jpg)

**Proposed Solution**
For these three quests, it would be nice to have a "add another languages" button after typing the name in the main language to be able to add it. There should be maybe some kind of wording to say that the first given language must be the official language.

Thanks a lot

**Comment by FloEdelmann** [comment]
This is the same request as in #2610. Feel free to add your information as a comment there.

I'll close this issue to keep the issue tracker clean and manageable.

**Comment by letypequividelespoubelles** [comment]
Thanks @FloEdelmann I haven't seen it.

**Comment by westnordost** [comment]
#2610 is about multiple names for names of businesses. This is about multiple names for bus stops and and street names.

@letypequividelespoubelles do you have infos on which tags are used for the examples you made?

**Comment by westnordost** [comment]
So by the way, this exists and is taken into account:

https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/additionalStreetsignLanguages.yml

It would just need to be extended.

**Comment by letypequividelespoubelles** [comment]
>#2610 is about multiple names for names of businesses. This is about multiple names for bus stops and and street names.

It's true, but I guess it's heavily linked : the needs and UX will be the same, so maybe we should reword the title of #2610 to include the three add name quests (street, business, and bus stop) to have the discussion in a single issue. 

>@letypequividelespoubelles do you have infos on which tags are used for the examples you made?

For Corsican, Breton, occitan, the used code are in the wiki ( https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes), for creole I'll check, I don't know if it's done for Alsatian.

**Comment by westnordost** [comment]
>reword the title of #2610 to include the three add name quests (street, business, and bus stop)

What? **This is already implemented for street and bus stops!** #2610 is about using the same interface for businesses as for streets and bus stops.

Anyway, what I need from you is, **for each country** where it is common that street signs or bus stop signs have the name in another language or in a romanized version below the original name:
- the ISO-639-1 codes of these. If these are romanizations, I need the information how this is usually tagged. It differs per country, some use `int_name`, some use e.g. `ja-Latn`
- a link to a source that proofs this. E.g. a link to StreetView, a photo, a wiki article

And at that point, you could, if you want, directly create a PR by editing https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/additionalStreetsignLanguages.yml

**Comment by westnordost** [comment]
ping

**Comment by letypequividelespoubelles** [comment]
@westnordost I'm on holydays, I'll see it when I'll be back 😃

**Comment by westnordost** [comment]
That would require the user to know the ISO code. Better add any languages that actually may occur to the linked list. You can create a PR if you find that a language is missing (source needed).
