### ISSUE TITLE
add more option to "Do these traffic lights have a button to request a walk signal?" quest

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#3318]
**Use case**
Sometimes, for the "Do these traffic lights have a button to request a walk signal?" quest, we have to leave a note because there are no traffic lights at all,it's just a marked cross.

**Proposed Solution**
Add an option to.let the user answer "it's just a marked cross without any traffic lights" and "it's an unmarked cross". The UX will be better than leaving a note. Thanks.

**Comment by westnordost** [comment]
Hmm no, we can not add an other-answer option to fix every incorrect tagging, this is what "leave a note" is for. Maybe some guy in your area made all these mistakes when mapping from satellite imagery. I don't see an indication that this is systematically mapped wrong.
