### ISSUE TITLE
add `check_date:surface` when setting `surface` tag

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#3319]
**Use case**
Some roads get re-finished and the set value for `surface` is no longer correct, for future improvements a `check_date:surface` should be added, so "old" values can be re-checked via streetcomplete. 
i.e. roads with a `surface` tags but missing `check_date:surface` can get updated or get added a `check_date:surface`.

In future streetcomplete _could_ re-check old `check_date:surface`, if it sets it now.

In my neighborhood, some roads have `surface` values older than 6 years, and I have resorted to manually checking every road and setting a `check_date:surface` to enable filtering in josm, having this in streetcomplete would make this a lot easier.

Also, for a future `surface`-quest this could be implemented as well for the same reasons.

**Comment by westnordost** [comment]
StreetComplete already updates the `check_date:surface` when re-checking the surface, but only if the surface didn't change or when the tag already exists.

**Comment by joshinils** [comment]
ah, so if the surface gets added for the first time, then it doesnt get added 

now i'm interested in knowing how it is decided when to re-check a surface tag without a check_date and after what time.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface

For example https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddRoadSurface.kt#L18-L19

In this case `surface` on roads will be asked for unpaved roads that were not modified for 4 years and paved that were not modified for 12 years. This values are affected by global resurvey parameter that cab be set in settings.

You can look at other surface quests and look for similar code (just search for "years")

**Comment by matkoniecz** [comment]
>  i.e. roads with a surface tags but missing check_date:surface can get updated or get added a check_date:surface.

Seems to be a repeat of #1836 - and from what I remember conclusion of https://github.com/streetcomplete/StreetComplete/issues/1836#issuecomment-663094863 was that there is preference to not add check_date key on every edit (disclaimer: I was one of people with such opinion)
