### ISSUE TITLE
Add building nodes to address quest

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3324]
**Use case**
Buildings can be mapped as nodes for various reasons, such as lacking good aerial imagery, or not enough time to trace building outlines. Yes, buildings should always be mapped as areas where possible but there are over 1 million nodes tagged as building.

I don't know an easy way to break down the numbers of building types and address details just for nodes but in a random section of the UK there were about 1000 out of 1800 nodes tagged as `building=yes` and the rest as something more specific. Just over 500 of the buildings which weren't `yes` did not have `addr:housenumber` or `addr:housename`

As well as enhancing additional data this would make it easier to conduct housenumber surveys for more advanced users who could create representative nodes before a survey which would be much quicker than tracing all of the buildings.

In some cases I can imagine it being a bit hard to tell what building a node refers to from a map alone, so perhaps this would go better with aerial imagery, if/when that gets implemented.

**Proposed Solution**
Add nodes to this section
https://github.com/streetcomplete/StreetComplete/blob/36b236c2cd3639b9b71f0a50b0b9e428977bb107/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L170-L182

(so addresses are only asked for nodes with an appropriate building tag, not e.g. `building=yes` and I am not suggesting modifying the building type quest to include nodes)

There might also need to be some checking in the rare case of a building node inside a building way.

**Comment by matkoniecz** [comment]
The problem with building nodes is that there could be a validly mapped address nodes next to them.

**Comment by arrival-spring** [comment]
Hadn't thought of that, does it really happen much?

**Comment by matkoniecz** [comment]
No idea. Also, building geometries are often very important to know which building is getting asked about. Especially in trickier areas and with poor GPS signal.

**Comment by matkoniecz** [comment]
After thinking about it again: I would recommend closing it due to high risk of being unable to identify buildings. In many places where I was mapping I would be unable to answer such questions if buildings would be mapped as nodes. Identifying specific building would be not really viable.
