### ISSUE TITLE
Switching between multiple quest selections and priorities

### ISSUE THREAD

**Issue by jolesh** [streetcomplete/StreetComplete#3329]
**Use case**
I have several "modes" of mapping with SC
*Intense: Mapping with all quest enabled also building quest (Mostly in my home area)
*Normal: Most quest but not all (for areas I don't visit too frequently)
*Biking: Where I only have very few quest types enabled (to quickly cover big areas)

**Proposed Solution**
First of all I would suggest an option to activate all quests in one click in addition to the already existing option to deselect all.
In addition I would suggest a feature, which allows people to easily switch between quest selections and priorities. Maybe something like this, where you start with one set and can add others later on:
![SC Questselection](https://user-images.githubusercontent.com/29330125/135104516-c507a507-2335-478b-94a7-1807242ba43d.png)

**Comment by smichel17** [comment]
This exists! Added in version 34. It's called quest presets, and you can find it in the overflow menu on that screen.

**Comment by mnalis** [comment]
(related issue for the reference: https://github.com/streetcomplete/StreetComplete/issues/1654)
