### ISSUE TITLE
Render power lines on the map

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#3338]
**Use case**
When doing the power pole material quest, the quest icons have no reference, they just float in a void, often in a forest or grass landuse. The lack of spatial awareness becomes an issue when some poles are already tagged (could be earlier quest actions), multiple power lines are close to one another and/or other spatial features are missing. Then you become unsure if you are tagging the right pole, or the next one in line.

To illustrate, this is my current view:
![image](https://user-images.githubusercontent.com/7458098/135770596-40e727a4-18cf-437e-a9f4-014581df4f6d.png)

While this can actually be this situation in practice:
![image](https://user-images.githubusercontent.com/7458098/135770650-33af5a0a-180f-4a60-8a10-6aaf54a9a678.png)

**Proposed Solution**
Render the power lines and power poles on the map.
Similar to how other quests relate to rendered objects, the power pole material quest would benefit if the objects are visualized.
Power lines and power poles are already mapped on the default Openstreetmap.org website, using simple lines and small squares/circles.

![image](https://user-images.githubusercontent.com/7458098/135769960-2871ab5c-4a0e-4c62-a8f8-9abe3d7d0aae.png)

More general, I think it is valuable to render the nodes and ways to which the quests relate.

**Comment by smichel17** [comment]
I haven't investigated the cause of this, but it's one of two things, and for both this issue should be tracked elsewhere:

1. Power pole data is not present in the tiles from Jawg. This would be my best guess, as they are (intentionally) lightweight tiles. I'm not sure where Jawg does issue tracking off hand.

2. They are present in the yours but not displayed by the app -- in this case, this issue should be moved to https://github.com/streetcomplete/streetcomplete-mapstyle

**Comment by westnordost** [comment]
This seems to be quite the virtual issue, if you must make up mock-up-screenshots of the app?

Anyway, I don't understand what is the issue of this at all. Shops are also not shown. But their location is when you are asked about it. And that should be enough. Power poles are far apart, your location is shown on the map and SC should be used only on a survey.

**Comment by kmpoppe** [comment]
I'm unsure if shops and power poles are comparable here. A shop-quest is very clearly visible within the confines of a building. As much as quests for bike racks can be almost always clearly compared against the road layout.

In the above mentioned case, given I was walking along the track that branches off right above the `D 301` label, I was unsure if I was able to distinguish whether the quest is meant for the pole along the first or second main power line - getting closer to them to determine my own location clearer might be impossible and/or prohibited.

It might be a niche problem, but I can understand OP's intentions.

**Comment by matkoniecz** [comment]
> Power poles are far apart

Not always!

https://www.openstreetmap.org/#map=19/50.07602/19.87570 (one power line unmappeed, only pole marked, one I think terminates there and also there is a power tower).

I was testing map with a family member and they answered "metal" for wooden power pole as they spotted power tower, not power pole (and missed distinction).

I also have seen wooden pole next to concrete one, but it is also really rare.

**Comment by nicorikken** [comment]
> This seems to be quite the virtual issue, if you must make up mock-up-screenshots of the app?

Common, really? I was following the feature request template as best as possible which asks for mockups for improved clarity, if applicable. I made the extra effort to get the point across as best as possible.

If you're looking for a real screenshot, I'll add one in this comment.

> Anyway, I don't understand what is the issue of this at all. Shops are also not shown. But their location is when you are asked about it. And that should be enough. Power poles are far apart, your location is shown on the map and SC should be used only on a survey.

I only use StreetComplete when doing a survey. But often times power poles are not easily accessible and have to be mapped from a distance. Like standing on the side of the road and looking 100 or 200 meters out into the countryside where the poles are. And from a distance it is easy to distinguish material, but harder to define exact position in relation to the map.

>> Power poles are far apart

> Not always!

This!

When you have 3 or 4 power poles close to another, without other references (because it is all in a `landuse=grass` area), it goes well for the first 1 or 2 poles, but it becomes confusing when those icons have disappeared. Then sometimes I get doubts which poles I tagged and which I didn't. And I also encountered situations where multiple lines are close to one another, and some poles are already mapped, but not all. I encounter situations when there are about 6 poles close to one another and I only see 2 quests because other poles already have been tagged. Than it becomes impossible to complete the quest when you're standing on the side of the road, unsure which poles are which.

I scrolled back to a region I countered such situations This screenshot is of a number of poles in a field, with minimal reference for orientation. And there is another line close-by which is already tagged but this cannot be viewed on the map to prevent tagging mistakes:

![photo_2021-10-04_11-05-03](https://user-images.githubusercontent.com/7458098/135823984-21f503a9-23ff-4f7d-aeeb-2ce0e81333ac.jpg)

A makeshift solution is to open the Vespucci app, but that takes more time, the whole reason why I prefer StreetComplete in the first place.

I already started looking into the code how the maps are built up and how it can be expanded. It is a new domain to me, but hopefully there are already useful Tangram examples with power lines to reuse.

> I also have seen wooden pole next to concrete one, but it is also really rare.

I'm currently in France, most of the times the lines have a single type, but some times poles of different functions have different materials, or there can be multiple lines close to one another with different materials.

**Comment by matkoniecz** [comment]
> I already started looking into the code how the maps are built up and how it can be expanded.

For map style see https://github.com/streetcomplete/streetcomplete-mapstyle

There are some plans to allow more advanced display of things, but this is a huge project.

**Comment by westnordost** [comment]
Ok, I understand. So I agree it would make sense to at least display power lanes when the quest form is open.

This is actually almost possible, but we might want to wait with that until we have explored whether we want to migrate to MapLibre or not.

**Comment by nicorikken** [comment]
>Ok, I understand. So I agree it would make sense to **at least display power lanes when the quest form is open**.

Great! I like that refinement. They can still help for orientation but also clutter the view, so I can see a reason to hide them when the quest is inactive.

> This is actually almost possible, but we might want to wait with that until we have explored whether we want to migrate to MapLibre or not.

No problem, I consider this to be a small usability improvement for 1 particular quest, so it has a low priority.

**Comment by smichel17** [comment]
Perhaps as a maybe-easier-to-implement temporary solution: use the same element filter as the quest to select all power poles in the area, then display them as dots (like collapsed quests) only when the quest form is open.

https://github.com/streetcomplete/StreetComplete/blob/73b577dc57c5542672401288c743e915d4e26ace/app/src/main/java/de/westnordost/streetcomplete/quests/powerpoles_material/AddPowerPolesMaterial.kt#L10-L14

The main thing I'm unsure about is how long running the db query for the quests would take / whether we could do it just-in-time as the quest form is opened, or whether it needs to be cached. I *think* it should be fast enough, since it's a simple query.
