### ISSUE TITLE
[v36.0-beta2] "Movement direction" mode button mismatch

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3345]
Hi there,

this afternoon I tried out the new "follow movement direction" mode introduced with v36 while rolling through some villages nearby on one of my bikes. It's indeed a huge usability improvement for cyclists - much less need to pan and turn the map manually :+1: (The old "compass mode" has never been useful on my phones due to huge jitter.) The new mode seems to be tied to the 3D view though - is this really necessary? I have always considered this 3D view as irritating (e.g. roads in greater distance look like smaller ways) and tried to avoid it, now I'm forced to use it if I want to make use of the new mode :frowning_face: 

However, the button in the lower right corner sometimes didn't reflect the current mode. If I clicked on the orange icon it turned into a red arrow but the map orientation didn't change at all. In these cases another tap on this button changed the arrow colour to black and the map rotates correctly so the movement direction points to the upper side of the display (as I would have expected after the first tap).

This occured several times, but so far I wasn't able to reproduce this behaviour reliably. Maybe some action on the map (clicking on some buttons, moving/rotating the map manually) doesn't update an internal status flag (or similar)?

I will keep on watching and try to find a pattern behind this phenomenon - maybe it can be fixed until the final v36.0 gets released.

SC v36.0-beta2, Android 9

The cycling cat

**Comment by cyclingcat** [comment]
Just for the record: This issue still pops up occasionally here.  I sometimes see the red arrow in the lower right corner although the map does _not_ follow my position. If I tap on the red arrow now, the map turns into my movement direction and follows it, the red arrow button doesn't change.

The cycling cat

**Comment by matkoniecz** [comment]
Not sure should I advise you to make a new issue or not given that it is apparently really erratic, but make one if you can reproduce it reliably (or semi reliably).

**Comment by cyclingcat** [comment]
Indeed, this behaviour is rare and erratic and I still did not succeed in reproducing it reliably or finding a pattern behind it. I just wanted to register here that this phenomenon is still present in v40, in case someone else has a similar issue and finds this ticket via the search function.

It's not a big annoyance IMHO, at least myself, I can live with it. Another tap on the button reliably fixes it for the moment. If I ever find a pattern behind the occurances of this problem, I will open another ticket with a detailled description how to reproduce it.

The cycling cat
