### ISSUE TITLE
Map rotates/zooms/moves to an inadequate position after opening the quest form

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3346]
Hi there,

this one looks like a bug that must have been introduced many versions ago, but since the introduction of quests for longer OSM ways in v35.0 its impact has become more adverse.

If I click on a quest icon concerning a way, the quest form appears and the map rotates/zooms/moves. If I remember correctly, the zoom was calculated in a way that the whole way was completely visible on the displayed map section (which makes sense in order to show the way in its context). But sometimes the zoom/movement/rotation of the displayed map isn't really helpful, because the affected way is either not visible in its entirety or, even worse, not visible at all. For me it looks like some miscalculation takes place under certain cirumstances yet unknown to me.

I didn't succeed in reproducing the issue step by step, but I face it quite often. If I close the quest form, zoom/pan/rotate the map manually and click on the same quest again, the displayed map section often also changes, making things sometimes better, sometimes worse.

See these screenshots:

A road surface quest...

![Quest](https://user-images.githubusercontent.com/32601012/136258830-e230b293-8d67-4b97-83d6-24e3c640baa4.png)

... after the click on it, the map zooms and pans, but the zoom factor is much too high and the affected road is displayed near the upper border of the screen:

![After_click](https://user-images.githubusercontent.com/32601012/136258837-fc90dcaf-0c40-48e1-a4f9-68e738e95c24.png)

During the next time I will try to narrow down this effect a little bit.

The cycling cat

**Comment by westnordost** [comment]
Yes, I know. I believe this must be a tangram-bug if this is true but I have been too lazy to investigate. For anyone wanting to give it a shot, the code is in 

https://github.com/streetcomplete/StreetComplete/blob/d677942d774e8b394d17f76a717b588b9a2a8539/app/src/main/java/de/westnordost/streetcomplete/map/tangram/KtMapController.kt#L234-L279

**Comment by westnordost** [comment]
Will be solved with #3123
