### ISSUE TITLE
"What barriers are used at this railway crossing" - stop asking for light_rail?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3347]
Since 7 days https://www.openstreetmap.org/way/234074325 is `railway=light_rail` and "What barriers are used at this railway crossing" questions appeared around it.

It is on edge of tram and light_rail, so edit changing it from `railway=tram` is not really wrong.

Maybe not asking for level crossing type on all `railway=light_rail` would make things worse, likely many are far less tram-like.

Or would be it a good idea to add `light_rail` to the filter at https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/railway_crossing/AddRailwayCrossingBarrier.kt#L23 ?

**Comment by westnordost** [comment]
Why?

**Comment by matkoniecz** [comment]
Hmm, rereading all related tag docs once more it seems that it is case of edit being wrong. I posted on https://www.openstreetmap.org/changeset/111888389 and will revert it in future
