### ISSUE TITLE
Shops with video surveillance are shown as surveillance cameras in the quest question

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#3360]
I recently had SC ask me about opening hours of surveillance cameras and was a bit confused. Both because the name implied a shop and because the feature was a surveillance camera I could not see. I initially assumed that SC mentioned the operator of the camera there.

See this note: https://www.openstreetmap.org/note/2861345

Perhaps this question should be reworded for things that are under video surveilalnce, but are themselves not cameras.

**Versions affected**

34.1

**Comment by matkoniecz** [comment]
This shop has `man_made=surveillance` what seems to be incorrect to me.

It is a surveilled shop, not a surveillance camera.

I have removed `man_made=surveillance` tag in https://www.openstreetmap.org/changeset/112327298

**Comment by matkoniecz** [comment]
Overall I would consider it as a case of invalid OSM data becoming noticeable, not as an OSM bug. See also https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dsurveillance#Surveilled_location

**Comment by ygra** [comment]
Oh, I missed that one. In that case, it's indeed a tagging error.
