### ISSUE TITLE
What type of Stile/Gate/Gap is here?

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3372]
### General
Affected tag(s) to be modified/added: [stile](https://wiki.openstreetmap.org/wiki/Key:stile)
Question asked: **What type of Stile/Gate/Gap is here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Anywhere where a `highway=path/footway` intersects/crosses a `barrier=wall/fence/hedge/guard_rail`

For example this node (and the one above it):
https://www.openstreetmap.org/node/7287751590

**Metadata needed:** 
None

**Proposed UI:**
It can probably just chuck you into the existing stile quest, especially when gaps are added as mentioned in https://github.com/streetcomplete/StreetComplete/issues/3188#issue-973861400

**Comment by matkoniecz** [comment]
It can appear also in city. Hopfefully number of false positives where existing mapping is wrong is low...

Not sure what would be the best but maybe separate quest reusing assets would be better to allow disabling/enabling this one separately.

And would allow a more precise title(s).

>  intersects/crosses

Only where it intersects. Note not-fully-mapped bridges and tunnels.

**Comment by peternewman** [comment]
> It can appear also in city.

Good point, I don't think there should be other answers there.

> Hopfefully number of false positives where existing mapping is wrong is low...

How do you mean? Where they don't cross?

> Not sure what would be the best but maybe separate quest reusing assets would be better to allow disabling/enabling this one separately.

Yeah fair point, is there some cleverer way we can use identical code but just two different sets of node queries?

> And would allow a more precise title(s).

I think you can do that already can't you, like the tram/bus quests?

> > intersects/crosses
> 
> Only where it intersects. Note not-fully-mapped bridges and tunnels.

Having looked, the top of my two example nodes just crosses and doesn't intersect. Curiously iD doesn't flag that as a warning...

**Comment by peternewman** [comment]
> > How do you mean? Where they don't cross?
> 
> For example where there is a hedge, very large gap (50m? 20m?) with footway inside and then another hedge. With hedge mapped as one line intersecting with footway.

Ah I see, which would hopefully generate a note and have the mapping corrected.

> Yes, but everything gets far more complex.

Yeah that makes sense.

> Someone may wish to disable as their area is unlucky to have many false positives, finding quest with title not shown in quest list would be weird and so on.

Although I think you have to have the tram and bus quests combined.

**Comment by matkoniecz** [comment]
> With path/footway being dynamic substitution of the relevant term? 

likely not - question objects will be nodes on intersection and topology is (I think) lost when title is shown, so it cannot be set.

And anyway `highway=path surface=paving_stones` or `highway=footway surface=gravel` are valid taggings.

**Comment by 10992-osm** [comment]
> It can appear also in city. Hopfefully number of false positives where existing mapping is wrong is low...
> 
> Not sure what would be the best but maybe separate quest reusing assets would be better to allow disabling/enabling this one separately.
> 
> And would allow a more precise title(s).
> 
> > intersects/crosses
> 
> Only where it intersects. Note not-fully-mapped bridges and tunnels.

Is this because it's only technically possible to check for intersection, or just because it's more appropriate for this quest?

**Comment by 10992-osm** [comment]
> way/route is a bit too generic - as it includes also roads
> 
> path - would it inclde in English also paved footways?

Do you mean the ones that run alongside roads for cars (a.k.a. pavements, or sidewalks in en-US)?

If you do, I imagine most people would understand it, but I'm not sure how many would actually say it in that case.

**Comment by peternewman** [comment]
> In Polish translation I will use "ścieżka/chodnik" as both very strogly indicate surface ("ścieżka", Polish for path strongly indicates `surface=unpaved` and 'chodnik' - strongly indicates `surface=paved`). I remember similar claims for path/footway in English.

Not according to the dictionary:
https://dictionary.cambridge.org/dictionary/english/path

I'd probably think it's a bit more at the muddy end, but I can't immediately think of one specifically for paved routes. @smichel17 @andrewharvey

**Comment by 10992-osm** [comment]
In everyday English (at least where I'm from: England), no-one uses the word *footway*.  If it is ever used, it will be referring to the path alongside the road which is normally called the *pavement* (`sidewalk` in OSM), as opposed to the carriageway.

A *path* can have any sort of surface, I think.  At some point, you might end up calling it a *track* (particularly if it is paved and/or wider (for vehicles) and/or also for cycles).  In my experience `highway=track` does not entirely match up with what I call a *track* in day-to-day life.  The photo you put above, @matkoniecz, is something that I personally would call a *path*.

Like @peternewman, I also can't think of a word for paved paths.

**Comment by matkoniecz** [comment]
>  Anywhere where a highway=path/footway intersects/crosses a barrier=wall/fence/hedge/guard_rail

I think that I will extend it to `highway~path|footway|cycleway` intersecting `barrier~wall|fence|hedge|guard_rail|retaining_wall|city_wall` and separate quest where road intersects one of this barriers.

(why separate quest for roads? Because it is typical to have gate for road and separately mapped path without a barrier along it)

**Comment by matkoniecz** [comment]
Wow, I expected it to be a niche quest with thousands question generated worldwide. But still worth it due to high importance.

But https://overpass-turbo.eu/s/1daz reveals many more cases than I expected.

Including some tricky ones like https://www.openstreetmap.org/node/206351942 https://www.openstreetmap.org/way/692929794 (a tunnel entrance) that right now would qualify. I guess that excluding nodes that are touched by `tunnel and tunnel != no` will be needed.

**Comment by Helium314** [comment]
Same case with bridges, see https://www.openstreetmap.org/node/78135912 or https://www.openstreetmap.org/way/28101153.
Then it might need to look at level/layer, see https://www.openstreetmap.org/node/5759605902 where the road has level=-1 and the barrier has layer=1.

**Comment by matkoniecz** [comment]
Thanks! I just excluded all bridges, too many false positives here.
