### ISSUE TITLE
Extending bus stop questions to train stop

### ISSUE THREAD

**Issue by Dignusss** [streetcomplete/StreetComplete#3374]
Is it possible to extend the questions for bus stops also to other public transport?
The [public_transport=platform](https://wiki.openstreetmap.org/wiki/DE:Tag:public_transport%3Dplatform) could be used for this.

**Comment by michaelblyons** [comment]
Can you skip the bin questions if an actual bin is marked within 3m of the platform?

**Comment by FloEdelmann** [comment]
@michaelblyons There was a similar discussion before: https://github.com/streetcomplete/StreetComplete/issues/2760#issuecomment-898202943

To me, it seems that it would be possible (similar to e.g. the cycleway quest being skipped if there is a parallel cycleway mapped) but too difficult to be worth the benefit (i.e. being less spammy). It's just a Yes/No quest, after all.

I'll hide your comment and this answer as off-topic (for this issue), but feel free to open a GitHub discussion  or another issue for this improvement if you want to add anything.
