### ISSUE TITLE
Resurvey barrier type (with frequency depending on current type)

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3382]
### General
Affected tag(s) to be modified/added: [barrier=*](https://wiki.openstreetmap.org/wiki/Key:barrier)
Question asked: **What type of barrier is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

#### Maybe resurvey every 6 months?

Some of the barrier types recognised by SC can be quite temporary and should be resurveyed pretty quickly:

* Chain
* Rope
* Removeable wire
* Big immovable object
* jersey barrier
* log
* debris

#### Maybe resurvey every year?

In addition, `barrier`=`gate` is commonly used in my area where a more specific type of gate could be more useful. So resurvying barrier=gate reasonably often might be useful to catch these.

#### Maybe resurvey every few years?

The other barrier values should probably be resurveyed too, but perhaps less frequently than the above.

**Proposed UI:**

Is there still this type of barrier here?

Possible answers:

* Yes
* No barrier
* Different/More specific barrier
  -> leads to current selection form

**Comment by westnordost** [comment]
> Maybe in future, with layer view?

Probably not.

Then it is WNF.
