### ISSUE TITLE
AchievementLevels text field is not visible on small screen

### ISSUE THREAD

**Issue by Altonss** [streetcomplete/StreetComplete#3388]
The "AchievementLevels" text field of the first profle section is not visible. It is probably hidden by the "OSM Profile" and "Logout" buttons. It is impossible to scroll down to see the text. This probably happens because my smartphone has a small display.

![Screenshot_2021-10-15-22-58-19](https://user-images.githubusercontent.com/66519591/137554830-b80b32ab-e3d1-40fc-8e23-a4503e568e83.png)

**How to Reproduce**
- Open StreetComplete
- Tap the hamburger menu on the top right corner
- Tap on "My Profile"

**Versions affected**
- Android 5.0.1
- StreetComplete v36.0
- A small screen size

**Comment by westnordost** [comment]
What smartphone do you have?

**Comment by Altonss** [comment]
A Samsung Galaxy Core Prime

**Comment by smichel17** [comment]
It has a [4.5" screen](https://www.gsmarena.com/samsung_galaxy_core_prime-6716.php), in a 5:3 ratio (for comparison, my [Galaxy S6](https://www.gsmarena.com/samsung_galaxy_s6-6849.php) is 5.1", but has a slightly taller 16:9 ratio).
Looks quite nice, actually.

**Comment by Altonss** [comment]
Thanks a lot @westnordost <3
