### ISSUE TITLE
Bug: The *road* in the illustration is asked on the steps incline test

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3392]
The *road* in the illustration is asked on the steps incline test

**How to Reproduce**
Steps incline uses:
https://github.com/streetcomplete/StreetComplete/blob/6490c40d3e578067333f89baabba1328a442b580/app/src/main/java/de/westnordost/streetcomplete/quests/steps_incline/AddStepsInclineForm.kt#L24
Which uses:
https://github.com/streetcomplete/StreetComplete/blob/0857679a146abaf474f051f8e8d12225d9a10ff3/app/src/main/res/layout/quest_street_side_puzzle.xml#L19
Which uses:
https://github.com/streetcomplete/StreetComplete/blob/318471c7a39488902b1986c56a10c291fb94561c/app/src/main/res/values/strings.xml#L816

**Versions affected**
Latest from looking at the code

Sort of related to this:
way/route is a bit too generic - as it includes also roads
_Originally posted by @matkoniecz in https://github.com/streetcomplete/StreetComplete/issues/3372#issuecomment-941571516_

**Comment by peternewman** [comment]
> How about "the segment"?

Yeah or "the way" works for me, but maybe it's too OSM specific.

**Comment by matkoniecz** [comment]
Current state of solving #3364

![screen14](https://user-images.githubusercontent.com/899988/137685327-80152f3f-218d-472d-9238-6151cd422986.png)

(right now it works by having two `de.westnordost.streetcomplete.view.StreetSideSelectPuzzle` layouts - and I need to figure out how to make them selectable, in the same way as entries in other quests
![screen15](https://user-images.githubusercontent.com/899988/137685636-d985d16d-e11e-4bc9-987c-49a43ecded79.png)
are selectable. Or replace them with something like `RotatedCircleDrawable` that would be redrawn as rotation changes)

**Comment by matkoniecz** [comment]
Posted here as I am not really happy about the text. I even thought about getting back to the original with "road" replaced by "steps".

**Comment by westnordost** [comment]
Hint: Just inflate two `R.layout.labeled_icon_button_cell` into a horizontal linear layout and then "manually" assign the pictures and text to it.
Making them round: `myImageView.outlineProvider = CircularOutlineProvider` should be enough.
Rotating them: just with `myImageView.rotation`

**Comment by westnordost** [comment]
You neither need `RotatedCircleDrawable`. In fact, it could be deleted if both the steps include quest and the oneway quest used (your) new interface.

**Comment by matkoniecz** [comment]
`<string name="quest_oneway_tutorial">The road in the illustration is rotated the same as on the map at the location of the pin. Note the indicated direction. </string>`

Not useful for incline quest and I think it would not be useful for oneway quest using this interface.

**Comment by westnordost** [comment]
If this is not in progress, I would like to take this after all because I am currently refactoring code close to this. Is this ok?

**Comment by westnordost** [comment]
I started working on it
