### ISSUE TITLE
Adding that a building is a toilet should add amenity=toilets

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3398]
When you say that the type of a building is a toilet it feels like you are saying that the building is a toilet and would expect that to be tagged. In reality it only changes the building key.

If it also added `amenity=toilets` then the follow-up questions about toilets would also be asked.

I can see that this might be unwanted as one could argue that it adds something that the user has not totally explicitly stated.

Also, perhaps some additional checks would be needed to see if the building has other feature tags.

**Comment by westnordost** [comment]
The toilet could be tagged as a node within the building.  Tagging the toilet ob the building would lead to double-tagging in that case

**Comment by arrival-spring** [comment]
Hmm, good points well made.

Perhaps a new quest, but I feel like it's too rare to be worth making

**Comment by matkoniecz** [comment]
> as there is no way to tag "there is no public toilet inside".

In theory one may tag https://taginfo.openstreetmap.org/keys/building%3Ause
