### ISSUE TITLE
Add option to disable trace

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#3400]
**Use case**
Very recently StreetComplete started showing traces. Reading #2209 I do see the use case, however, I also read the opposing views. I personally have two issues with this feature:

1. My GPS is not always very reliable. So now the screen is garbled with fake movement, while my phone tries to find its position. This also counters the rationale for the request, as I cannot be 100% sure the path is correct.

2. I do not have a privacy shield on my screen. Now everybody who is able to look at my smartphone can see the path I traversed. I believe those privacy shields are not very common on phones, either.

**Proposed Solution**
Add a configuration option to switch this track on and off in the settings. Actually, I assumed there to be one but unfortunately I could not locate one, hence this bug report. Additional bonus, if the track can be easily deleted (e.g. to remove the fake movement by GPS location or when I want to deliberately show the phone with StreetComplete running to other people), e.g. a "delete now" setting.

**Comment by smichel17** [comment]
I am pretty sure it will be deleted when you close StreetComplete (including clearing it from recent apps).

**Comment by westnordost** [comment]
Correct. So you can clear it any time by doing that. It is not planned to add an option to disable it completely.
