### ISSUE TITLE
Indicate current download action in the notification

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3410]
From https://github.com/streetcomplete/StreetComplete/issues/3406#issuecomment-946876940

> The download spinner is shown when the download didn't finish yet. This can have a lot of different reasons
> - poor connection / no reply. Waiting for timeout
> - data is actually already downloaded but database to insert the new stuff is locked (used by another thread, e.g. the cleanup job) so it waits for its turn
> - there is a lot of osm element data that needs to be inserted. It may take very long
> - quests are being generated. With a lot of data downloaded, it can take a lot of time
> - there are a lot of quests that need to be inserted. It may take very long
> - or again the database is locked here and it waits for the cleanup job to finish

As a user, if the download is taking a long time, it is useful to know which of these is the reason. For example, if it is a network issue, I might try moving to a location with better signal, toggling airplane mode or finding wifi (might need to kill the app in order to retry); if I am waiting for quests to be written to the DB, I definitely should NOT kill the app.

F-Droid has multi-stage notification like this (including progress bars; I'm not asking for those (yet)).

**Comment by westnordost** [comment]
Sure, something like this could be done. A progress bar of sorts could also be shown for e.g. the quests as they are generated. The big steps that take longest in local testing is 1. writing OSM elements to DB and 2. generating the quests.

**Comment by westnordost** [comment]
The obstrusive download view has been replaced by a simple spinning animation at the top left (around the star), i.e. the upload and the download share the same progress bar. Hence, there is no obvious place to put the information anymore and I would not want to reserve UI space for such information, as it is somewhat unimportant (from the user's point of view, it doesn't matter much where the download is "stuck")

**Comment by mnalis** [comment]
In order not to eat screen estate, spinner could have a different color depending on in which stage it is, but that is likely too much effort, and would need to be separately documented...
