### ISSUE TITLE
What is the reference number of this defibrilator?

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3412]
### General
 
 Affected tag(s) to be modified/added: [ref=*](https://wiki.openstreetmap.org/wiki/Key:ref) on [emergency=defibrillator](https://wiki.openstreetmap.org/wiki/Tag:emergency=defibrillator) Question asked: **What is the reference number of this defibrilator?**
 ### Checklist
 
 Checklist for quest suggestions (see guidelines):
 
   * [x] :construction: To be added tag is established and has a useful purpose - @rjw62 's https://osm.mathmos.net/defib/progress/S/ notes "Note that this matching is not perfect, and if there are multiple nearby AEDs, or an EAD is a long way from its postcode centriod, they may not be matched correctly.". A lot of these have refs, so could be matched perfectly if this data was gathered.
   * [x] :thinking: Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
   * [x] :chipmunk: Easily answerable by everyone from the outside but a survey is necessary
   * [x] :zzz: Not an overwhelming percentage of elements have the same answer (No spam)
   * [x] :clock4: Applies to a reasonable number of elements (Worth the effort)
 
 
 ### Ideas for implementation
 
 **Element selection:**
 
emergency=defibrillator nodes in countries where defibrilators usually have numbers (certainly includes UK), which have no ref=* tag, and ref:signed=* (if present) is not equal to "no".
 
 **Proposed GUI:**
 
 Q: What is the reference number of this defibrilator?
 
   * The reference number is [ ________________ ]
   * The number is not shown or is unreadable.
   * This defibrilator does not have a number (perhaps it is a private defibrilator).
 
 In the first case ref=* is set to the value given. In the second case ref:signed=no is set. In the third case ref=no is set.
 
 (There has been some discussion about ref=* more generally in #81.) This quest suggestion was stolen from the post box one, #1556.

**Comment by peternewman** [comment]
> > To be added tag is established and has a _useful purpose_
> 
> Pardon my ignorance, but what is the useful purpose of `ref` of AED to OSM users?

As I said in the quest suggestion template (although I'd tagged it against the wrong question initially:

> @rjw62 's https://osm.mathmos.net/defib/progress/S/ notes "Note that this matching is not perfect, and if there are multiple nearby AEDs, or an EAD is a long way from its postcode centriod, they may not be matched correctly.". A lot of these have refs, so could be matched perfectly if this data was gathered.

For example given these two nodes, and one listing in Robert's thing, which is the correct defibrilator:
https://www.openstreetmap.org/node/9192012306
https://www.openstreetmap.org/node/9192012301

More generally, it's the same purpose as any ref, to tie OSM to real data:
https://wiki.openstreetmap.org/wiki/Key:ref

Like all of these:
https://taginfo.openstreetmap.org/projects/tag2link#tags

Robert takes it a step further by using an external data source to effectively QA OSM and flag where the gaps are.

> I certainly would _hope_ they have they own database of their AEDs instead of depending of OSM.

You could say the same about post box refs, fire hydrant diameters, even the power pole materials etc, unfortunately it's often not the case, or not compatible for some licence reason.

> And even if they want to have that database of `ref`s synced with OSM for convenience, I would hope they use some (semi-)automated tools for that purpose, instead of sending workers with StreetComplete to roam around the city and fill in the `ref`s ?

Matching two separate geographically positions accurately and correctly is unfortunately very hard, again see Robert's pages for some demos of why and what he tries to do to work around it.

**Comment by matkoniecz** [comment]
@peternewman In which countries/areas it would be useful?

**Comment by Lee-Carre** [comment]
For Jersey, defibrillators are *supposed* to have an ID, but not all of them do. So, the utility of enabling this quest is unclear, for the Bailiwick / island. I don't know about the other Channel Islands.

**Comment by peternewman** [comment]
> @peternewman In which countries/areas it would be useful?

Well probably not the UK for a while from what @rjw62 has said (and probably until that new database comes in).

Broadly it's useful in any countries where the reference number data is available as open data (even if the locations aren't) and someone is willing to pull together a site to compare the two.

> For Jersey, defibrillators are _supposed_ to have an ID, but not all of them do.

Can you FoI them or equivalent @Lee-Carre  to get the list of IDs to know whcih ones you're missing?

> So, the utility of enabling this quest is unclear, for the Bailiwick / island. I don't know about the other Channel Islands.

Same question, if you can get the data you can use the list of refs to get a list of probably missing AEDs.

**Comment by matkoniecz** [comment]
"In which countries/areas it would be useful?" remains open.

Is there some area where 

- substantial amount of AED carry some clearly identifiable `ref`
- there are no AED with other numbers easy to be mistaken for `ref`
- collected `ref` data would be useful

?

**Comment by matkoniecz** [comment]
Closed as no area where this quest is worth asking was identified. If anyone is aware - please share such info.
