### ISSUE TITLE
Move "More options" answers (besides "can't say" and clarification answers) into the form body

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3416]
**Use case**

The motivation is closely related to https://github.com/streetcomplete/StreetComplete/issues/3387. It took me thousands of quests before "open other options menu and leave a note" became part of my main thought process when trying to decide between answers, and I still sometimes forget that there's other tagging options in that menu ("No house number but a name...").

**Proposed Solution**

Put "other options" which result in tagging changes into a list at the bottom of each form, so they can be accessed by scrolling. The current location of "other options" would be replaced by "Can't say", which opens a menu with "leave a note", "just hide", and any clarification options (things which just open an explanation dialog).

This was pulled out of https://github.com/streetcomplete/StreetComplete/issues/1913#issuecomment-828632563, as a part that makes sense to do independently.

**Comment by westnordost** [comment]
You can experiment with it, but I don't think this would be an improvement and introduces some UX issues IMO. So, it is not planned.
