### ISSUE TITLE
Allow adding access=customers for playgrounds

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#3433]
Often I find playgrounds which are useable for customers only.
The operator could be a biergarden, hotel or even a big funpark.
IMO they should not be tagged as private or public. 
You need to take action (order a drink, book a room or plan longer time because of the fee) to be able to use it.

I propose to add this into the "others menu" to the quest.

**Comment by matkoniecz** [comment]
Note #3429 #3473 that I want to solve before likely using the same interface here.

Current wording is as depicted above, new proposed wording is

> Open to general public
> Open only to people visiting a specific place (e.g. customers)
> Not open to general public

**Comment by matkoniecz** [comment]
![screen](https://user-images.githubusercontent.com/899988/145486540-95ed54b7-30eb-481d-a6a0-8f3fd7ef4eb5.png)

**Comment by smichel17** [comment]
Didn't we also change the question (form title) to something like, "Who is allowed to use this playground?"

**Comment by matkoniecz** [comment]
Looking at it again I am worried a bit.

Is it likely that people would answer "only individual(s) with permission" for age restricted playground (say, with sign that it is for play by children with ages up to X, or older than Y)

**Comment by HolgerJeromin** [comment]
I am unsure if this will be a problem. 
All playgrounds are age limited at least in Germany.

**Comment by matkoniecz** [comment]
I asked around and unanimous response is that this is clear ( https://discord.com/channels/413070382636072960/413070502580453387/922950548150423553 and earlier)
