### ISSUE TITLE
Bike lanes with a dashed line are not advisory lanes in France

### ISSUE THREAD

**Issue by Rudloff** [streetcomplete/StreetComplete#3461]
**Use case**

When adding a cycleway StreetComplete asks if it has a continuous line or dashed line. If it has a dashed line, it will add `cycleway:both:lane=advisory`.

But in France, a dashed line does not mean a lane is an advisory lane.
Cars are forbidden on the vast majority of bike lanes and those usually have a dashed line. (The continuous line is usually only used for cycle tracks.)
We also have advisory lanes that cars can use only if they need to avoid another car coming from the opposite direction, but those are somewhat new and also have a dashed line (and I think the dashes are less wide).

**Proposed Solution**

Maybe StreetComplete could ask directly if the lane is advisory or not instead of asking if the line is continuous when the user is in France.

**Comment by westnordost** [comment]
So far, there is either no interest in it and/or participants didn't get to the core of the topic. I tried to give some (auto-translated) pointers to pick them up from where they are.

FYI v37.0 of Streetcomplete now still has the option for exclusive and advisory cycle lane but a (provisional, based on the comments here) altered wording and the correct illustrations, i.e. dashed lane for "exclusive", dashed lane without cycle pictogram but ">>" for "advisory".

**Comment by westnordost** [comment]
Maybe @Phyks and @Florimondable as authors of CyclOSM are interested in the linked French forum topic.

**Comment by Phyks** [comment]
Thanks for the notification @westnordost! The notion of exclusive / advisory is not really present in France, compared to other countries, as we could discuss it at SOTM a few years ago.

Regarding https://github.com/streetcomplete/StreetComplete/issues/3461#issuecomment-953965760, "Bande cyclable obligatoire" is not really common in France. The law states that cycling infrastructure are never mandatory, except if there is a local law (from the mayor) which makes them mandatory. This is a very special situation with really often discrepancies between (vertical) signage (blue circle sign = mandatory) and real legal basis (no such local law). 

Regarding the initial issue of "chaucidou", I would actually add `cycleway=lane + cycleway:lane=advisory` to the French wiki (see https://github.com/cyclosm/cyclosm-cartocss-style/issues/111). This should probably be pointed out on talk-fr mailing-list for feedbacks. cc @naomap @charlesmillet who are working a lot with bicycle tagging / OSM FR:Bicycle wiki page.

**Comment by westnordost** [comment]
> Regarding the initial issue of "chaucidou", I would actually add `cycleway=lane + cycleway:lane=advisory` to the French wiki 

@Phyks This is how StreetComplete currently (v37) tags it. The question was whether

1. `cycleway=lane + cycleway:lane=advisory` or
2. `cycleway=shared_lane + cycleway:lane=advisory`

would be more fitting. Neither is mandatory for cyclists.

In general, (1) has legislation on how (much) cars may use this, cars may usually stop but not park and may cross into the lane only if necessary and usually has some minimum width 
(2) has usually no legal implications at all regarding usage of cars / bicycles, also no minimum width, i.e. more or less has the legal status of a shoulder

**Comment by Phyks** [comment]
Personnally, I'd rather use option 1 (`cycleway=lane`) over `cycleway=shared_lane`. For these _chaucidou_, cycle lanes are indeed lanes and only considered as shoulders in case of two vehicles crossing (normal use is car in the middle / cyclist in the lanes - exceptional use is car on the shoulder / lane for crossing). The meaning of `cycleway=shared_lane` (at least in France) is really captured by this picture from the OSM wiki https://wiki.openstreetmap.org/wiki/File:Sharrows_Toronto_2011.jpg. It is basically no infrastructure nor dedicated space for cyclists.

Additionnally, _chaucidou_ quality are seen as higher than other kind of bicycle infrastructure by French cycle lobbyists.

**Comment by westnordost** [comment]
Oh, really? Even dedicated lanes and tracks?

On 3 November 2021 13:34:16 CET, Lucas Verney ***@***.***> wrote:
>Personnally, I'd rather use option 1 (`cycleway=lane`) over
>`cycleway=shared_lane`. For these _chaucidou_, cycle lanes are indeed
>lanes and only considered as shoulders in case of two vehicles crossing
>(normal use is car in the middle / cyclist in the lanes - exceptional
>use is car on the shoulder / lane for crossing). The meaning of
>`cycleway=shared_lane` (at least in France) is really captured by this
>picture from the OSM wiki
>https://wiki.openstreetmap.org/wiki/File:Sharrows_Toronto_2011.jpg. It
>is basically no infrastructure nor dedicated space for cyclists.
>
>Additionnally, _chaucidou_ quality is seen as higher than other kind of
>bicycle infrastructure by French cycle lobbyists.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3461#issuecomment-958990123

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Ok! So then the way StreetComplete tags the situation in v37 is what seems to be preferred. @Phyks did you want to update the wiki or did you want to let this go through the French mailing list another time?

**Comment by Phyks** [comment]
It seems to me this discussion should probably pass through talk-fr, which is more active than the French forum, before editing the French wiki. @Rudloff would you like to handle this?

**Comment by Rudloff** [comment]
I am not subscribed to talk-fr.
@Phyks Would you mind making the post?

**Comment by matkoniecz** [comment]
Pinging @Phyks - have you did this or willing to do this?

I guess that posting in English on French mailing list is a poor idea so I am not available for this.

**Comment by westnordost** [comment]
ping @Phyks

**Comment by westnordost** [comment]
Anyway, I'll close this issue. Let us know if there is any action required by StreetComplete. Maybe even in a new ticket (referencing this one), as this is so long already.
