### ISSUE TITLE
Bordsteine

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3467]
Ich habe folgende Nachricht erhalten, die ich hiermit weiterleite:

Hallo,
Mir ist aufgefallen, dass du mit SC bei manchen Kreuzungen einen Node mit kerb=raised hinterlässt. Das ist auch korrekt, aber der highway=crossing Tag fehlt dort. So ist es als Bordstein in der Mitte der Straße gemappt, ohne Kreuzung, und der iD-Editor zeigt es als Datenproblem an.

Beispiele:

https://www.openstreetmap.org/node/268556148 https://www.openstreetmap.org/node/4109929771

Das sollte so nicht sein, weiß nicht ob es durch einen Bug in SC oder irgendwie in der Eingabe entsteht.

Die Nodes sind dort, wo sich zwei Wege kreuzen und eigentlich ein highway=crossing hingehört. Auch die SC-Beschreibung im Änderungssatz sagt “Add whether there is a crossing”, sollte also wahrscheinlich eigentlich das highway=crossing dort setzen, wo es noch fehlt an kreuzenden Wegen:

https://www.openstreetmap.org/changeset/111826858

**Comment by biketeur** [comment]
Kommentator hat die Antwort zur Kenntnis genommen, wird in Zukunft meine SC-Eingaben bzgl. Bordsteinen händisch korrigieren.

**Comment by westnordost** [comment]
Und auf welche Weise will er das korrigieren?

**Comment by biketeur** [comment]
Die Antwort des Kommentators lautete:

Hmm ja, Ein bisschen komisch ist das schon. Mit dem vereinzelten kerb=* wird wahrscheinlich auch kein Parser was mit anfangen können. Aber ich werde dann wohl manuell weiter highway=crossing hinzufügen, falls ich so einem Node begegne. Danke für’s melden.

Meine Antwort hierauf:
Wäre es vielleicht sinnvoll, wenn ich zukünftig keine Bordsteine mehr mit SC tagge?

Deine Frage werde ich auch weiterleiten und die Antworten hier posten.

**Comment by biketeur** [comment]
Hier die Antwort:

Nein, alles gut. Soweit ich es verstehe, tritt es ja nur auf, wenn ein kreuzender Weg noch keine crossing-Tags besitzt und die Bordsteine an der Stelle beidseitig erhöht ist. Kann dann überprüfen, ob ich ein highway=crossing und crossing=unmarked hinzufüge oder die Kreuzung verschiebe oder lösche, je nachdem wie es aussieht. Kannst also definitiv weiterhin die Bordsteine mappen.
