### ISSUE TITLE
StreetComplete does not expect the 255-character limit on keys/values

### ISSUE THREAD

**Issue by neuschaefer** [streetcomplete/StreetComplete#3471]
In OpenStreetMap's data model, keys and values [have a maximum length of 255 characters](https://wiki.openstreetmap.org/wiki/Elements#Tag). In rare circumstances, such as when entering a very complex table of opening hours, it may happen that StreetComplete constructs a value longer than this limit. When uploading the changeset, SC fails with a fairly unspecific error and suggests to the user that they send an email to the developers.

I can imagine two approaches on how to improve the situation:

1. Count the number of characters in each key/value before uploading; Present an error message that explains the issue and suggests actions.
2. Display the error message from the OSM server when upload errors occur. I'm not sure, but I think it might describe the problem, in this situation. (I tried uploading the same value using the _iD_ web editor, and got an error message on upload that told me that something is too long.)

**How to Reproduce**

Enter a long tag value, for example with the opening hours quest.

**Versions affected**

Experienced on SC v32.2 and Android 10.

**Comment by westnordost** [comment]
And what actions should be suggested which the user can solve?

**Comment by mnalis** [comment]
`Leave a note (with picture)` / `hide`? That way at least someone else can perhaps manually craft working `opening_hours`. IMHO trying to explain the problem to the user, and suggesting ways to shorten it is way too complicated (given target SC audience).

**Comment by smichel17** [comment]
One way to handle it would be to create a note with the tagging that *would* have been generated. Then someone online could take a look and see if it can be [golfed](https://en.wikipedia.org/wiki/Code_golf) to fit.

**Comment by matkoniecz** [comment]
I would give info to user, as they would give later email that note was commented on/closed.

**Comment by mnalis** [comment]
> One way to handle it would be to create a note with the tagging that _would_ have been generated

That should work; I've now [checked](https://www.openstreetmap.org/note/2916564) and Notes API seems not be limited to 255 characters as the rest of the [API 0.6](https://wiki.openstreetmap.org/wiki/API_v0.6#Maximum_string_lengths)

**Comment by mmd-osm** [comment]
Notes are limited to 2000 unicode characters at the moment.

**Comment by smichel17** [comment]
The one downside I see to this approach is that an open note prevents any additional quests from being asked at that point. I think this is okay, since a too-long answer is a rare thing.

**Comment by Lee-Carre** [comment]
For the curious, a broader context on the 255 character limit problem, and how it might be solved: openstreetmap/openstreetmap-website#2025 (“Increase max key and value max length”).
