### ISSUE TITLE
Delete cached map does not delete all

### ISSUE THREAD

**Issue by georg-d** [streetcomplete/StreetComplete#3475]
in SC, I see quests for OSM data which is not shown in the map (e.g. asking for surface of a street which is not visible), so it's very difficult to tell apart which of the streets, houses,... the quest is about. Hence, I want to manually enforce a refresh of the outdated map tile cache. Deleting the map cache works _except for_ the currently viewed area - which is exactly the area I want to update 👿

After reading https://github.com/streetcomplete/StreetComplete/issues/3260 and https://github.com/streetcomplete/StreetComplete/issues/3124#issuecomment-894569422 and seeing they are considered fixed, I report this as new issue.

**How to Reproduce**

1. open any area in StreetComplete, wait until the map shows
2. switch data off for your mobile, so you can reliably tell whether cache was been deleted (because SC cannot load the tiles when being offline)
3. in SC, tap 3-lines-icon, Einstellungen/settings, Zwischenspeicher löschen / delete cache, confirm pop-up dialog with löschen/delete
4. click back button until you reach the map and see the map is still shown. Closing and re-opening the app does not cause any change.
5. close SC by opning the taks/app switcher and swiping SC out of the screen
6. go to Android launcher, long-tap SC icon, open app details, tap speicher und Cache / memory and cache, tap cache leeren / clear cache, wait until 0 B are shown for cache
7. open SC again and see the map is now gone - unless you did forget step 5... Side note: I do not understand how map can be shown despite cache is shown to have 0 Byte.

![click sequence](https://user-images.githubusercontent.com/45993293/139586722-ec52ef8c-9af2-4d35-b3db-2fffd9cfd2d6.jpg)

**Versions affected**
36.1 and 37

**Comment by smichel17** [comment]
> Side note: I do not understand how map can be shown despite cache is shown to have 0 Byte.

Probably it is still cached in RAM.

**Comment by mnalis** [comment]
> Probably it is still cached in RAM.

Probably, but that does make tile cleanup part of `Delete cache` rather useless. It would be good if after deleting cache the map display could be somehow reinitialized so TangramES is forced to start anew without cache, and thus download new data?

**Comment by georg-d** [comment]
> > Side note: I do not understand how map can be shown despite cache is shown to have 0 Byte.
> 
> Probably it is still cached in RAM.

That is inconsistent with display of 0 Byte cache content - 0 Byte is 0 Byte regardless of cache storage locations (processor's registers, RAM, internal storage, SD card, cloud, SIM card, modem, whatever else).

**Comment by mnalis** [comment]
@georg-d At least in my Android, that 0 byte `cache` is **explicitly counted** as being part of `Internal storage` (which is quite [well defined](https://www.tutorialspoint.com/android/android_internal_storage.htm) in android world - and does not include neither `cloud storage` nor `RAM`, etc). So android app could well be using 0 bytes  internal non-volatile storage cache, **and** 150 MB RAM, at the same time. 

Also note that there are tons of different `cache` mechanisms, and one **should not assume** that internal storage cache that Android OS  talks about is related to any other kind of cache (like processor instruction cache, TLB cache, or in this case, TangramES RAM cache)

Still, it does not change the fact that it would be nice if SC could reinitialize TangramES view from scratch (thus making it drop its RAM cache) when `Delete cache` is selected.

**Comment by westnordost** [comment]
The "Zwischenspeicher löschen" **does not** clear the background map tiles. Only the actual map data, i.e. the quest pins.

Should it?

The option in the setting was introduced that if a user **knows** that something major changed in his area and wants to have quests for it **now**, that he can clear the quest cache. If I remember correctly, the option was also named "clear quest cache" first.

**Comment by westnordost** [comment]
So should the option be renamed back to "clear quest cache" or should it also clear the tiles? What are the use cases?

**Comment by smichel17** [comment]
I think it should also clear the tiles. If the user just wants some more recent data, I think that should be accessible by hitting "scan for quests here" in an area that has already been scanned recently. Opening up the settings to clear things is for when the normal flow has failed.

Related: are quests cached separately from OSM data? If so, I think the setting should clear OSM data, too. From the user's perspective, these are not distinct caches.

**Comment by georg-d** [comment]
> should the option be renamed back to "clear quest cache" or should it also clear the tiles? What are the use cases?

IMO it shall also clear tiles because achiving this is a litte difficult to figure out (e.g. deleting cache from app info is _not always_ working). The need to delete tile cache has been voiced by several users in other issues, for me, mainly 1) quests about invisible map features are hard to answer, 2) you can't tell apart for which feature a quest is about. This happens frequently (around 30 times in 1 week of intense usage).

**Comment by peternewman** [comment]
> The option in the setting was introduced that if a user **knows** that something major changed in his area and wants to have quests for it **now**, that he can clear the quest cache. If I remember correctly, the option was also named "clear quest cache" first.

> So should the option be renamed back to "clear quest cache"

I would say yes in the short term, as that's what, and all, that it does. As I mentioned in another comment I expected it to clear tiles too based on how it's currently worded.

> or should it also clear the tiles? What are the use cases?

> I think it should also clear the tiles. If the user just wants some more recent data, I think that should be accessible by hitting "scan for quests here" in an area that has already been scanned recently. Opening up the settings to clear things is for when the normal flow has failed.

I'd agree with @smichel17 . I think there are a few distinct use cases:

- The data for the place I'm at is stale, I'd like to force a refresh; ideally this should just update the local are, if I'm generally offline I don't want to discard cached data for another area I can continue to use (even if it may be a little bit stale)
- I've just returned from a holiday or travels, I'd like to promptly discard the data from that remote area as it's no longer of any use to me. Clearing the whole cache (tile and quest) is probably the only sane way to do this, rather than trying to specify an area to delete

> Related: are quests cached separately from OSM data? If so, I think the option should clear OSM data, too. From the user's perspective, these are not distinct caches.

I'd agree with this too, also the data is interlinked, if my quests are stale, my OSM data probably is too, and possibly my tiles as well if they've been re-rendered.

I guess ideally when refreshing the tiles it would just honour all the existing HTTP caching, there's no point re-downloading the same identical file from the tile-server again.

**Comment by georg-d** [comment]
> I guess ideally when refreshing the tiles it would just honour all the existing HTTP caching, there's no point re-downloading the same identical file from the tile-server again.

IMHO we shall go the KISS way and prefer to delete _all cache data_ instead - that's most likely simpler to implement than _"keep the data but do not render until verified that tile server has nothing newer"_, simpler to communicate to users, and making tabula rasa & relying on nothing is also the desirable behavior for such a fallback feature (as _smichel17_ wrote "_Opening up the settings to clear things is for when the normal flow has failed._")

**Comment by westnordost** [comment]
ok

**Comment by peternewman** [comment]
> I think it's confusing when you try to clear the cache and everything isn't gone (ie, if it just marks tiles as "stale, need to be re-checked". Ideally, even if we're keeping the same http-cached tile, it should be hidden until we verify that it is still the latest tile. That would be possible if we were maintaining our own cache, but we're using the standard OkHTTP cache (see also [tangrams/tangram-es#2298](https://github.com/tangrams/tangram-es/issues/2298)). Without implementing our own cache, I think the lesser of two evils is to re-download a few tiles, rather than showing stale data after it has ostensibly been deleted, causing confusion like this issue.

Agreed, but I was talking about my first use case of a forced refresh.

> IMHO we shall go the KISS way and prefer to delete _all cache data_ instead

I certainly agree, the delete option may as well delete everything.

> making tabula rasa & relying on nothing is also the desirable behavior for such a fallback feature (as _smichel17_ wrote "_Opening up the settings to clear things is for when the normal flow has failed._")

> in SC, I see quests for OSM data which is not shown in the map (e.g. asking for surface of a street which is not visible), so it's very difficult to tell apart which of the streets, houses,... the quest is about. Hence, I want to manually enforce a refresh of the outdated map tile cache.

Going back to your original request, and @smichel17 's comment. It still feels to me that you want option 1 of my suggestions here, what would be a pull down from the top in many apps to force a refresh (and keep you hooked on your social media). You don't actually care about some other tiles you happen to have cached, just that the one you're looking at is visibly wrong and needs updating.

> How often this happens depends on how much change happens in OSM data for the area you currently are, e.g. I ran into the issue 0 times in 1 week in Montafon mountains (stable data), but around 30 times in 1 week in Orpierre (many new ways etc).

As you yourself acknowledge @georg-d some parts of the map are fine, so ideally we shouldn't be hammering the phone, network and tile server unnecessarily for those parts, but just for the bit in front of you that's actually wrong (and hoping the tile server has regenerated it).

I've not looked at how easy this is to do in OkHTTP, whether you'd need two different caching contexts with different stale settings and you'd have to switch between them when doing a forced refresh or if there's a simpler way.

**Comment by georg-d** [comment]
> Going back to your original request, and @smichel17 's comment. It still feels to me that you want option 1 of my suggestions here
> ...
> You don't actually care about some other tiles you happen to have cached, just that the one you're looking at is visibly wrong and needs updating.

You interpreted my need correctly :)

> As you yourself acknowledge @georg-d some parts of the map are fine, so ideally we shouldn't be hammering the phone, network and tile server unnecessarily for those parts, but just for the bit in front of you that's actually wrong (and hoping the tile server has regenerated it).

Yes, ideally. For operational implementation, I still strongly favor the other, all-or-nothing, KISS  approach because the feature we are talking about is kind of "last resort", thus

- it's infrequently used compared to other features like _"answering a quest with time selection"_, so, IMHO our limited resources shall go to the latter. 
- it shall be reliable & robust. The more rules & exceptions, the more lengthy & error prone the implementation, especially considering the seemingly quite independant technical layers of SC.
- it's used when the usual flow failed, so when users interact with it, they might not anymore be calm, friendly, focused. Then, usability and supportability is key. If users stumble across issues that might be related to stale data, a description for the delete feature shall be easy & straightforward and the result easy & relibale to anticipate. Imagine they cleaned data and moved a little and find there, the data is also "bad" - quite a number of users might think the data cleaning feature is buggy or did not help for their issue, thus cause unnecessary support efforts. The other users that understand well what happened will repeat the data cleaning. But that is tedious to do again and again - so many  users will zoom out a lot and then clean, thus, delete more or less "all" anyway. That's massively limiting the potential benefit of a fine grained data deletion feature. 
- As quests & tiles live in a cache of limited size and they have a short designated time to live, data outside your current area will relatively likely be already invalid when you move to that area again. For example when you visited a friend yesterday and go there in 3 weeks again, much of data will be downloaded freshly anyway - limiting the benefit of keeping it before.

Please don't get me wrong: I agree to your point and just value it lower than KISS _for this specific feature_ ⚖😊

**Comment by georg-d** [comment]
@westnordost I tested the feature in v37.1 and it works - thank you 😀 I observed I need to close & restart the app to see an effect. Is that just on my device or expected? If expected, is it easy to show an according message after data was deleted?
