### ISSUE TITLE
Allow choosing photos from the gallery for uploading to notes

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#3476]
**Use case**
From my personal experience, the native camera app is better than the camera in apps like StreetComplete.
I am often outside when it is dark. The system's camera app supports night mode. The camera in other apps takes bad photos in the darkness.
I wish I could take the photo for a note with the camera app and upload it to StreetComplete later.
Is this possible?

**Comment by FloEdelmann** [comment]
This is a duplicate. See #1567, #1730, #2813, #3014.

**Comment by mnalis** [comment]
Added to [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Can_I_choose_photos_from_the_gallery_for_uploading_to_notes.2C_instead_of_using_camera.3F) now...
