### ISSUE TITLE
Separate map theme and interface theme mode

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [streetcomplete/StreetComplete#3485]
**Use case**

One might use a dark theme interface but would prefer a light theme map also. Currently light and dark theme currently can only be set simultaniously.

**Proposed Solution**

I propose let's separate the map theme to day and night and the interface theme to light and dark. Also set the default interface theme to follow system, not light. Might be helpful:
https://github.com/organicmaps/organicmaps/issues/749

**Comment by smichel17** [comment]
Is this about personal preference, or dark theme usability during the day? If the latter, maybe #3378 is enough.

**Comment by IHateTheProgrammingClass** [comment]
It's personal preference.

**Comment by westnordost** [comment]
As far as I know, it is not possible to have multiple "themes" at once in Android. So it would need to be a custom solution and this is IMO too much effort for a personal preference (that has been uttered just once so far).

**Comment by matkoniecz** [comment]
But it would be required to implement such feature.

**Comment by IHateTheProgrammingClass** [comment]
> As far as I know, it is not possible to have multiple "themes" at once in Android.

That's true. But that also was not the point of this issue.

**Comment by IHateTheProgrammingClass** [comment]
I don't get how would that be different. I don't believe separating the toggle for styling to the two interfaces would be that hard.
