### ISSUE TITLE
Is this a public orchard?

### ISSUE THREAD

**Issue by Stugeb** [streetcomplete/StreetComplete#3491]
### General
Affected tag(s) to be modified/added: [orchard](https://wiki.openstreetmap.org/wiki/Key:orchard)
Question asked: **Is this a public orchard?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [ ] 🚧 To be added tag is established and has a useful purpose (Medium often used but would be worth to establish (useful purpose i think))
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation
resurvey: **no**
question criteria: **landuse=orchard and orchard!=\***
icon: **\res\graphics\quest icons\apple.svg**

**Proposed UI:**
Should look pretty much like the "Is this parking public"-Quest
### Open Questions
Not sure about tagging in German so called "Streuobstwiesen"(public orchards).
Public orchard could be tagged:
**landuse=orchard** and **orchard=meadow_orchard** (priority of use: orchard)
or
**landuse=meadow** and **meadow=meadow_orchard** (priority of use: meadow)
or
**landuse=meadow_orchard** (neutral but very rare in use)
Thats why it maybe would be smart to ask if its more a meadow or a orchard in case its public.
Public orchard could be tagged:
**landuse=orchard** and **orchard=plantage**

### See also:
https://wiki.openstreetmap.org/wiki/Tag:orchard%3Dmeadow_orchard 
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dorchard 
https://wiki.openstreetmap.org/wiki/Key:access
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dmeadow_orchard

## Edits of the Idea
Question What kind of orchard is this?
Answer 1: private owned orchard -> orchard=private
Answer 2: meadow orchard -> orchard=meadow_orchard
Answer 3: big plantage -> orchard=plantation

**Comment by matkoniecz** [comment]
Where this would be useful? In Poland it would fail

>  Not an overwhelming percentage of quests have the same answer (No spam)

requirement

**Comment by Stugeb** [comment]
It could be useful to find places to get fruits from (I know this as tradition to go to meadow orchards and collecting apples). I don't really know were these meadow orchards are a thing. Maybe it would be a good idea to just ask this Question in specific countries. Most of the orchards are public but I guess about 10% of all orchards are private owned plantages. I would say even if the answer ist mostly yes it's worth to answer this because there is a big difference between plantages and "just some forgotten fruit trees".

**Comment by matkoniecz** [comment]
> Most of the orchards are public but I guess about 10% of all orchards are private owned plantages

Where such situation is present?

This is definitely not true in Poland.

**Comment by Stugeb** [comment]
Yes I wasn't sure where these public meadows are spread. It seems like this is only german-speaking-countries thing (see [orchard=meadow_orchard](https://wiki.openstreetmap.org/wiki/Tag:orchard%3Dmeadow_orchard)) . Maybe this Quest is only useful for the regions where are these differences between orchards are common.

**Comment by smichel17** [comment]
If this is a germany-only thing (and especially if it is just regional), how common are these orchards? If it's something like 100 total orchards, probably less work to tag them manually than implement a quest.

**Comment by Stugeb** [comment]
No they aren't rare. Heres a map of the tagged meadow_orchard (only some of the real meadow orchard are also tagged as one.)
![orchard=meadow_orchard](https://user-images.githubusercontent.com/63794122/140652096-14a79042-8d83-41eb-9a59-4cd7ea4014af.png)

**Comment by westnordost** [comment]
That something is a meadow orchard (Streuobstwiese) doesn't mean at all that it is public. It is just a meadow with some trees on it. 

In any case, like with any other place in agricultural use (e.g. a meadow), you'll usually not find a sign like "private property" at the boundary of a meadow. That doesn't know it is not private. So, whether or not a meadow orchard is private or not is not really verifiable on-site.

If you want to find edible fruit near you, try the app from mundraub.
