### ISSUE TITLE
Bicycle capacity is asked wrong (?)

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#3498]
**How to Reproduce**

https://www.openstreetmap.org/way/286048080#map=19/51.87775/8.50811&layers=N

I am asked for bicycle capacity for that object.
But the object has already this info since 2 years

**Versions affected**

v37.0
Android 10

**Comment by matkoniecz** [comment]
It is one of resurvey quests asked for old data. There is a setting to ask such questions less often.

**Comment by matkoniecz** [comment]
For technical side: see https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bike_parking_capacity/AddBikeParkingCapacity.kt#L17

**Comment by riQQ** [comment]
So the problem is that it's not clear from the question that it is a resurvey. Shouldn't it be treated differently if it is a resurvey? Prefill with the current value and ask if it's still correct.

**Comment by matkoniecz** [comment]
This is done for cycleway and opening hours quests where verifying is easier than survey.

Here one needs to count spaces anyway, though adding some extra step(s) would reduce error rate ("Are you sure that it is 6, not 8 as marked right now?"). But that would be time-consuming to implement and worth doing if there is noticeable error rate from OSM mappers.

**Comment by riQQ** [comment]
So as a (hopefully) low effort fix resurveys could be marked as such in the quest UI, maybe simply by adding the text *resurvey* or something similar.

**Comment by FloEdelmann** [comment]
That is deliberate. See https://github.com/streetcomplete/StreetComplete/issues/2174#issuecomment-710683825.

**Comment by HolgerJeromin** [comment]
Damn. I got bitten by this in the past. Thanks!
