### ISSUE TITLE
Using external address data

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#3508]
**Use case**
OSMUK is in the process of computing address points from Open Data. However we have no source for `addr:housenumber`/`addr:housename`, a survey will be required. We are working to get a MapComplete theme set up due to it being cross platform, but I'd love for it to be StreetComplete too. [Here](https://www.openstreetmap.org/node/8875376820) is an example of the data we can compute, there wont be an import into OSM (but it's not impossible we start adding nodes manually/with MapWithAI support).

**Proposed Solution**
Have a quest to read data from our API, prompt the user for the house number, and add a new node to OSM with the combined data.

At the moment, we are erring on the side of caution, if there is some ambiguity over existence of an address we aren't prompting for that data. However there is always the possibility of false positives getting through, an alternate answer of "no address here" could be fed back to us to remove the point for any future requests for addresses in the given bbox.

**Comment by westnordost** [comment]
Can you describe exactly how this will interact with the add housenumber quest? Or would it be a new quest?

**Comment by Cj-Malone** [comment]
For external data, I think it would be implemented as an new quest.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/discussions/2477

**Comment by westnordost** [comment]
Ok, then could you then create a new issue using the 

https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md

template? Because I have difficulties imagining how exactly this would be a quest.

In general, MapComplete seems to be more geared towards these kind of assisted imports but it is certainly also possible in StreetComplete as long as the effort/impact is ratio turns out to be worth it.

**Comment by westnordost** [comment]
If you have difficulties imagining how the quest would look like yourself (too), you might want to start a discussion first, like the one @matkoniecz mentioned.

**Comment by matkoniecz** [comment]
Also, it would be worth explaining how it would be better from existing address collection in SC.

Would it capture more addresses? Add entries with some extra data? Or is it entirely about mapping addresses without presence of buildings (in such case I am unsure whether mapper can really verify it)? 

Also, what kind of broken data is present that requires verification?

**Comment by Cj-Malone** [comment]
> Also, it would be worth explaining how it would be better from existing address collection in SC.

> Would it capture more addresses? Add entries with some extra data? Or is it entirely about mapping addresses without presence of buildings (in such case I am unsure whether mapper can really verify it)?

This wouldn't be asked in areas that already have OSM buildings, the existing StreetComplete quests to identify building types and add addresses work great. This is for areas without buildings (a significant portion of GB), it'll allow us to collect addresses at a faster rate.

> Also, what kind of broken data is present that requires verification?

If we compute `addr:street` it may need validation, but `AddAddressStreet` already covers nodes, so one solution would be to just not add any other data as part of this quest. Just and a node at the point with `addr:housenumber` that the user answered.

**Comment by Cj-Malone** [comment]
I'm unsure of how much the quest suggestion template will help, but maybe this will.

- We give StreetComplete a list of points (something like [this](https://osm-uk-addresses.russss.dev/addresses/18/128577/86944.json))
- StreetComplete excludes any points within OSM buildings (as this would just duplicate quests/data)
- Quest pins show up at these points with "What house number is here?"
- Once answered StreetComplete adds a node with the answer.

This data will only be computed for GB.

The UI would be incredibly similar to the existing house number quest. With an other answer of "No address here". I think the recent work that highlights other data while a quest is selects could be great here too.

If you still want a new issue, a discussion or for me to jump on the OSMUS Slack, let me know.
