### ISSUE TITLE
streetcomplete sets oneway:motor_vehicle instead of oneway

### ISSUE THREAD

**Issue by dieterdreist** [streetcomplete/StreetComplete#3513]
In this changeset: https://www.openstreetmap.org/changeset/76360960

on this way: https://www.openstreetmap.org/way/158028012

This is a oneway street so setting oneway:motor_vehicle=yes is not standard tagging
It is a tag which has currently 450 uses: https://taginfo.openstreetmap.org/keys/oneway%3Amotor_vehicle#chronology

the oneway tag applies to vehicles only, and there isn't legally a permission for bicycles in the road either.

**How to Reproduce**

**Versions affected**

**Comment by Helium314** [comment]
Looks like it was added already 7 years ago, when StreetComplete didn't exist: https://www.openstreetmap.org/way/158028012/history

**Comment by matkoniecz** [comment]
Are you using Osmcha? Then it is https://github.com/mapbox/osmcha-frontend/issues/492 and before you report bug/complain on changeset/complain about changeset you alays need to check real history.

**Comment by dieterdreist** [comment]
sorry for this wrong bug, I am aware of osmcha but in this case was looking at the Josm history view. I guess I have looked at the wrong line but will revisit this tomorrow to see whether there is eventually a bug somewhere else.

**Comment by matkoniecz** [comment]
No problem! I also have more share of confused bug reports.
