### ISSUE TITLE
Lower priority quest hides higher priority quests?

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3519]
In this example, higher-priority `cycleway` quest is not being asked until lower-priority `speed limit` quest was answered.

**How to Reproduce**
Enable both quests, with `cycleway` having priority (being positioned above) `speed limit` quest. I would expect that first `cycleway` quest was asked, and then `speed limit`. If reality, it happens in opposite order. It happened in several different locations, here is one example (at https://www.openstreetmap.org/way/101165290):

https://user-images.githubusercontent.com/156656/142738455-f69ff98a-b0b1-4ad6-9d12-c8af849a3797.mp4

Note: `cycleway` quest is asked at the middle of the road, while `speed limit` is asked on both ends of the road, don't know if it is related.

**Versions affected**
StreetComplete `v38.0beta1+` (actually https://github.com/mnalis/StreetComplete/commit/2c130289d227bb943c25fdc4d50bbe31ff9c46b3) on Android 10

**Comment by smichel17** [comment]
I'm pretty sure it's because the cycleway is only asked on roads with certain `maxspeed` values:

https://github.com/streetcomplete/StreetComplete/blob/6ca37cc8f1beb94bc6d59020b645694b3c9fce85/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L301-L326

**Comment by smichel17** [comment]
So basically the same thing as the building type and address quests.

**Comment by mnalis** [comment]
Oh, thanks @smichel17! Thanks might be the reason. It sounds like strange dependency, though (especially as maxspeed quest is disabled by default - is it intended that most of cycleway quests in cities would thus effectively be disabled by default too?)

I've seen `!maxspeed or maxspeed > 20 or ...` and have though it would trigger if no maxspeed that is present. It is quite complex (to me), but now looking at the top as you quoted it does indeed seem to have extra checks for `highway=residential` which are very similar to the rest (only using `>30` instead `>20`) but also seem to miss that `!maxspeed` qualifier? Is that intended? 

I'm trying to grasp logic here why for example `highway=unclassified` without `maxspeed` would be asked for cycleway, but `highway=residential` without `maxspeed` wouldn't (if I'm even reading that correctly at all - for example I'm confused what is the difference between conditions in `ways with (...)` block and those outside of it)?

**Comment by mnalis** [comment]
Because reading the comment above does not seem to indicate that the intention is to exclude streets which do not have maxspeed mapped (but only to exclude streets which are mapped as "too low speed"):

```
        /* Excluded is
          - anything explicitly tagged as no bicycles or having to use separately mapped sidepath
          - if not already tagged with a cycleway: streets with low speed or that are not paved, as
            they are very unlikely to have cycleway infrastructure
          - if not already tagged, roads that are close (15m) to foot or cycleways (see #718)
          - if already tagged, if not older than 4 years or if the cycleway tag uses some unknown value
        */
```

If that is correct, shouldn't `highway = residential` case also have that `or !maxspeed` as do other highway types?

**Comment by smichel17** [comment]
> I'm confused what is the difference between conditions in ways with (...) block and those outside of it

I am ~~80%~~\* sure that there is no difference; that in order to reflect the meaning, the opening parenthesis should go on a new line, not the same line as `ways with`. (Aside: this is the kind of thing that I was talking about in https://github.com/streetcomplete/StreetComplete/discussions/3302#discussioncomment-1370818).

I looked at the git blame and `highway=residential` used be excluded entirely, then was added only when the speed limit is high enough. So it seems intentional. I vaguely remember this being discussed, too. The [commit](https://github.com/streetcomplete/StreetComplete/commit/6502a21bfa7104da37f2e1d0fa9511d056f5ef23) is dated 2020-11-09, maybe that'll help you search for a related issue?

\*pre-posting edit: incidentally, this was also where the parentheses were added, so I can confirm that they aren't related to the `where` in any special way

**Comment by westnordost** [comment]
> I'm trying to grasp logic here why for example highway=unclassified without maxspeed would be asked for cycleway, but highway=residential without maxspeed wouldn't

Because `highway=unclassified` roads are very unlikely to have a speed limit so low that it makes no sense to have any cycleway infrastructure. It's a very different situation for residential roads. Most residential streets have no cycle track. I **guess** this is also the reason why I didn't include `or !maxspeed`. `maxspeed` is missing for lots and lots of roads, so if there was `or !maxspeed` it would only lead to spamming `cycleway:both=no` all over the place.

Maybe a little motivation to turn on the maxspeed quest. It is disabled because it often takes much more time to ascertain it on foot.

**Comment by mnalis** [comment]
OK, I follow that most residential streets wouldn't have cycleways.

But I still don't follow why would having `maxspeed` tagged (instead of implicit default) make residential street **_more likely_** to have a cycleway? In my experience, explicit `maxspeed` signs (on residential roads) are actually much more likely to _reduce_ maximum allowed speed in the city, not increase it. If that is true globally, **_not having explicit_** `maxspeed` makes residential road actually **_more likely_** to have cycleway, not less likely.

And if the idea was to give motivation for bicycle users interested in `cycleway` quest to solve `maxspeed` quest in order to get `cycleway` quest enabled, it still does not seem to me like it would work -  even if one were to diligently solve `maxspeed` on all residential roads, vast majority of them would have default maxspeed (for example, 60 km/h in Croatia inside city, where residential streets are), so would be marked by SC only with `maxspeed:type=HR:urban` (and not with `maxspeed` tag), which does not seem to be checked, so `cycleway` quest **_would still not be asked_**?

**Comment by mnalis** [comment]
I've done more research and it **_still looks like an oversight to me_** instead of intentional change.

6502a21bfa7104da37f2e1d0fa9511d056f5ef23 that made that changes says `ask for cycleways for residential roads with >30km/h` which is not what it really does (majority of untagged residential roads would be equivalent of `maxspeed:type=XX:urban`, which is **above 30km/h** in all countries I'm aware of).

And it seems to be in response to previous commit ea3ad82b08f6c167dc261ab057eeb8389ab17d55, which did _"cycleways: do not ask for residential roads after all (#2251)"_ - which was found too restrictive.

To me, both of those, as well as comments in the code linked (see https://github.com/streetcomplete/StreetComplete/issues/3519#issuecomment-974711328) seem to _indicate the intention was to **make all residential roads eligible for cycleway quest, except those that are so slow that they are unlikely to have/need cycling infrastructure**_.

Of course, I'm not the author, so I would defer there to the people that made the change, but still it seems like a typo to me. (and if it is instead myself who is wrong, then at least the comment in the code should be changed to indicate true intentions of the filter)

**Comment by mnalis** [comment]
According to https://github.com/streetcomplete/StreetComplete/issues/2251#issuecomment-723866344 it might be indeed that (while not really logical from road speed side), streets not marked in `maxspeed quest` are indeed ignored, as a sort of arbitrary quest-limiting (eg. "no-spam") filter.
 
In other words, `maxspeed` quest is indeed a pre-requisite for solving `cycleway` quests in a city (eg. on residential streets).
Perhaps [comment in code](https://github.com/streetcomplete/StreetComplete/issues/3519#issuecomment-974711328) should be updated to reflect this?

**Comment by matkoniecz** [comment]
@mnalis Feel free to make PR in such cases.

Here I made commit adding this comment ( https://github.com/streetcomplete/StreetComplete/commit/ea00b99805b1997bc9092ef03482dc8e1fce3b45 ) , but mostly because I had the entire issue on a TODO list - otherwise I would miss it.
