### ISSUE TITLE
Add state and/or city rank to profile

### ISSUE THREAD

**Issue by Bubu** [streetcomplete/StreetComplete#3524]
**Use case**
I think the ranks displayed in the profile are a very useful motivation for people to continue mapping (there has been an on-going competition between a few friends :-)). But they still feel like very abstract numbers (being number #2000 in DE doesn't feel very different from being #4000). I think it would be very interesting for people to get more detailed statistics on how they are doing in their state or city, maybe they can easily compete from #10 or even first place in areas with less mappers.

**Proposed Solution**
In addition to tracking the worldwide and country specific stats and displaying a rank there, we could track contributions in and display a rank for every city and/or state (not sure what's a good resolution, here in Berlin that's both the same anyway ;-)).

(I searched and didn't find a proposal for this yet, sorry if I maybe missed something.)

**Comment by mcliquid** [comment]
The state as a further subdivision would be really great. The county could also be another useful subdivision (at least in Germany and Austria). Individual cities could be almost boring, at least in rural regions, because there are at least not so many mappers in this intensity there yet.

Additionally, I would find it great if you could call up the ranking to see who is below or above you and how much distance you have to the people.

**Comment by Suburbanno** [comment]
+1

**Comment by westnordost** [comment]
Not possible currently. This would require a boundaries file that included all the subdivisions of all the countries. Also, it would require localization of the names of all the subdivisions of all countries. Also, if one wanted to display the stats with the "country bubbles", also all the flags (if any!) of the country subdivisions.

StreetComplete currently uses the boundaries file from JOSM which only includes boundaries of countries (+ state boundaries of US, CA, IN, AU, CN). As a JSON, it looks like this:

https://github.com/streetcomplete/sc-statistics-service/blob/master/data/boundaries.json

So in theory, of these countries, it would be possible. But in practice, as written, we'd still need all the state names and localize them and have all those flags as small vector graphics. This is too much effort for the gain.

**Comment by Bubu** [comment]
@westnordost Despite your warning, I went ahead and implemented a prototype of this functionality for DE. :upside_down_face: 

There's a bunch of missing bits and pieces, but overall this works now, including the statistics server part.

It's done for DE specifically; for US, CA, IN, AU, CN it's "just" missing images, so it falls back to country flag; for everything else it's missing the subdivision polygons in the geojson file:

![image](https://user-images.githubusercontent.com/105185/143154285-a9110a2b-6623-499d-8dda-1c6ca49b5905.png)

(I tried using the coat of arms, instead of flags which that didn't work out well, so I'd switch that to the flag images)

Should I try to clean this up and send pull requests? (at https://github.com/streetcomplete/sc-statistics-service and here)

**Comment by westnordost** [comment]
Wow! Okay, so since you put so much effort in it, I'll say in detail what needs to be done. For Germany:

# Preparatory work
_**in other repositories**_

1. Ask the people at JOSM if they would merge a PR that adds subdivisions of Germany to https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm and if there are specific requirements for that. If not, it must unfortunately be forked and thus the file must be maintained in a separate repository from JOSM in the future ( :-( ). 
2. Edit the https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm and add accurate boundaries. The boundaries should be minimum as accurate as that any places (hamlets, ...) are on the right side of the borders and at most need to be as accurate as per-street or whatever other requirements the JOSM developers pose.
3. Android drawables of flags of federal states should be added in this repository https://github.com/westnordost/flags-vector-drawables-android (additionally to the streetcomplete repository). If a flag is too complex, the SVG should be simplified first. I did this with many other flags too, see https://github.com/westnordost/flags-vector-drawables-android/blob/master/res/modifications.txt . You'll notice that a few German flags are already available in that repository

# Implementation

1. There is a Java console program in https://github.com/westnordost/countryboundaries/blob/master/generator/src/main/java/de/westnordost/countryboundaries/Main.java . With this, we generate a new 
    - boundaries.json file (commented out code) 
    - a new boundaries180x90.ser file (binary blob consumed by the countryboundaries library that the app uses to determine what point is in what country
4. The new *.ser file is put into StreetComplete. Maybe some code needs to be adapted in the statistics controller so that the app doesn't filter out country subdivision codes
5. The new boundaries.json is put into https://github.com/streetcomplete/sc-statistics-service . Again, maybe some code needs to be adapted so that it does not discard country subdivision codes
6. The UI of the app needs to be updated to handle statistics with country-subdivision codes. Rather than your prototype implementation, I think it would be better to not have a third sub-tab because it doesn't fit horizontally and it will be empty for most users. Instead, implment it so that the user can "pop" a bubble so that instead of the whole country, all the smaller bubbles for the subdivisions are shown instead. Possible UX for that could be long-press and a hint displayed somewhere prominently that one can do that.

# Deployment

1. The updated https://github.com/streetcomplete/sc-statistics-service is deployed on the webspace. Since all contributions in Germany currently have no subdivisions recorded, all entries of all users who ever contributed at least one edit in Germany needs to be cleared from the database so that it is fetched anew. It will take considerable time to recover from this dent in the data because a cron-job very inefficiently has to crawl through the edit history of each individual user (because there is no good API endpoint for that).

**Comment by westnordost** [comment]
Regarding for which countries it may be worth the effort to do this, here is the statistics for how many people contribute with StreetComplete:

<img src="https://user-images.githubusercontent.com/4661658/112069907-fcdcf500-8b6c-11eb-873e-607e6eccdd6f.png"/>

**Comment by smichel17** [comment]
> a boundaries file that included all the subdivisions of all the countries

> localization of the names of all the subdivisions of all countries

> all the flags (if any!) of the country subdivisions.

FWIW, these all seem like things which are independently useful outside of SC, so it would be best to either find or create a project for sourcing them. JOSM and https://github.com/westnordost/flags-vector-drawables-android already exist for boundaries and flags. Translations of country subdivisions seems like… surely someone must have done this already?

**Comment by Bubu** [comment]
Thanks for your in-depth reply, let me go through the points and explain what/how I already did things:

> Ask the people at JOSM if they would merge a PR that adds subdivisions of Germany to https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm and if there are specific requirements for that. If not, it must unfortunately be forked and thus the file must be maintained in a separate repository from JOSM in the future ( :-( ).
> Edit the https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm and add accurate boundaries. The boundaries should be minimum as accurate as that any places (hamlets, ...) are on the right side of the borders and at most need to be as accurate as per-street or whatever other requirements the JOSM developers pose.

For now I did this super cheap and hackyly, but it worked surprisingly well:

```
# inside the sc-statistics-service data directory
curl -LOJ https://github.com/isellsoap/deutschlandGeoJSON/raw/main/2_bundeslaender/3_mittel.geo.json
jq -s '{type:"FeatureCollection",features:(.[0].features + .[1].features)}' boundaries.json 3_mittel.geo.json > combined.geo.json
```

I then updated the `boundaries.ser` file included in the streetcomplete repo via the countryboundaries-genrator tool ingesting the combined.geo.json and tested the result in the sample app (it still seems to perform adequately as well).

Bringing this upstream sound like a good idea if that's possible though.

> Android drawables of flags of federal states should be added in this repository https://github.com/westnordost/flags-vector-drawables-android (additionally to the streetcomplete repository). If a flag is too complex, the SVG should be simplified first. I did this with many other flags too, see https://github.com/westnordost/flags-vector-drawables-android/blob/master/res/modifications.txt . You'll notice that a few German flags are already available in that repository

Ah, nice, I didn't know of that repo. For now I just imported the coat of arms svgs into android studio vector drawables, looking for alternative versions of broken imports (13/16 worked fine on first try, 3 needed workaround). I agree that some time should be spent on getting this in proper shape. (Also I still like the coat of arms more than the flags and I have some Idea what I'd want to do with those instead of throwing them into the ballpit, but getting this working with just the flags for now sounds way easier overall)

> The new *.ser file is put into StreetComplete. Maybe some code needs to be adapted in the statistics controller so that the app doesn't filter out country subdivision codes

This is indeed filtered out right now. I currently went with copying all the logic around the country statistics for now and adapting it to a completely new statistics list which filters the opposite way (only subdivisions are taken into account). This might or might not be a good solution depending a bit on how other things shake out. I'll open a draft MR with what I have and then we can look at this in more detail later.

> The new boundaries.json is put into https://github.com/streetcomplete/sc-statistics-service . Again, maybe some code needs to be adapted so that it does not discard country subdivision codes

I added `states` and `statesRank` json fields here as that seemed like the most backward compatible way to add this functionality. The app then parses these new fields if they are there and old versions just ignore it. It's probably best to discuss this on a concrete proposal. I'll see if I can open a draft MR at the statistics server repo soon.

> The UI of the app needs to be updated to handle statistics with country-subdivision codes. Rather than your prototype implementation, I think it would be better to not have a third sub-tab because it doesn't fit horizontally and it will be empty for most users. Instead, implment it so that the user can "pop" a bubble so that instead of the whole country, all the smaller bubbles for the subdivisions are shown instead. Possible UX for that could be long-press and a hint displayed somewhere prominently that one can do that.

I have a few ideas for that (some are a bit far-off):

* Only show the additional tab when there's actually any data inside
* Have the tabs laid out in two rows (that's still not great though, but *would* solve the horizontal space issue)
* Alternatively throw everything into the same ballpit (i.e. have a large Germany bubble next to smaller German state bubbles). I think this would work pretty well actually? At least for most people the tab should currently be fairly empty anyway. :shrug: 
* Have the state bubbles (de-emphasized) inside the country bubbles and similarly to your idea be able to focus on a single country view
* I guess yours would be the slightly easier option to the above (just show countries and be able to "zoom into" on one.
* Instead of having the states in a ballpit alltogether we could make it into a collectors album, where you fill in the flags/coat-of-arms in a separate tab (this is the far-off thing I was talking about :))

> The names of the subdivision codes need to be added somewhere because AFAIK this is not provided by Java's Locale. I think it is not necessary to localize those, so it could go into just another *.yml file. The names are referred to when tapping on a country-subdivision bubble and in the main profile screen when you see a rank like "# 34 in Berlin"

Yup, I suppose having local-names + english names available would be nice to have. But local-only names should also be good enough for a first version. 
(Like @smichel17 said, it should probably be fairly easy to come by a list for each country we want to add that maps abbreviations to local names and possibly english names).

> The updated https://github.com/streetcomplete/sc-statistics-service is deployed on the webspace. The boundaries table is deleted (so it is generated anew from the given boundaries.json). Since all contributions in Germany currently have no subdivisions recorded, all entries of all users who ever contributed at least one edit in Germany needs to be cleared from the database so that it is fetched anew. It will take considerable time to recover from this dent in the data because a cron-job very inefficiently has to crawl through the edit history of each individual user (because there is no good API endpoint for that).

I thought about this a bit and the best idea I could come up with is to add a background job which goes through all the changesets which are currently mapped to DE and have no subdivsion recorded and recheck them against the new boundaries table and update them (we should probably save the centerpoint alongside this if we are already doing this, so we don't have to do it again in the future if we ever wanted to map it in even more detail). I have no idea how long that would take exactly, maybe a few weeks? The good thing with that solution above is there should be no "downtime"/data degradation during this reindexing as it's just iteratively enhanced in the background.

> Regarding for which countries it may be worth the effort to do this, here is the statistics for how many people contribute with StreetComplete:

Thanks, I wondered about this! If we ever get this fully done for DE (:crossed_fingers: ) I'd be interested doing France and Canada next. :-) Hopefully others would be interested in doing the work for other countries.

**Comment by westnordost** [comment]
> for now I did this super cheap and hackyly, but it worked surprisingly well

Hmm, that's interesting. However, 
- yeah, it's hacky. To just update the boundaries would then be a lot more laborious
- the borders don't align with the borders in the boundaries.osm file. This means that on more or less thin lines along the German border, the countryboundaries library will likely return something like `DE-BW, FR`. These erronous results may confound other logic

> coat of arms

Mh, I am mixed about that.
- Many states of countries do not have a coat of arms, but a flag. US-American states do have an "emblem" which is just as fine though. In total, I think it can be expected that more states have a flag than an emblem
- coat of arms and emblems tend to depict animals, people, things etc. and thus vector graphics of these tend to be insanely complex ad thus a hell to simplify. E.g. Toronto coat of arms vs flag
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Coat_of_arms_of_Toronto.svg/564px-Coat_of_arms_of_Toronto.svg.png"/> (1MB) vs <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Toronto%2C_Canada.svg/640px-Flag_of_Toronto%2C_Canada.svg.png"/> (1KB). Yeah, some states have the coat of arms in their flag, but at least it's only some

> I added states and statesRank json fields here as that seemed like the most backward compatible way to add this functionality

Sounds reasonable.

> I have a few ideas for that

> Have the tabs laid out in two rows

This will be difficult, AFAIK this material component does not support multiline, so it would need to be replaced with something self-made. This will be effort that could be spent better elsewhere.

> Collectors album

Hm well, a "collectors album" is already something we have on a different view - the achievements and to a degree the link collection.

>  best idea I could come up with is to add a background job which goes through all the changesets which are currently mapped to DE and have no subdivsion recorded and recheck them against the new boundaries table and update them

Not sure if this is worth the extra effort. The app is mostly used by people who do not contribute (much) using other apps so my gut feeling is that little extra traffic would be avoided this way.

**Comment by JesseWeinstein** [comment]
Has this been deployed? It looks like the stats service is returning US states now (rather than all of the US, but this seems to break the display on the app).

**Comment by matkoniecz** [comment]
Labels: wontfix 

See also https://github.com/streetcomplete/StreetComplete/issues/3524#issuecomment-977753221
