### ISSUE TITLE
"It does not exist" answer unclear

### ISSUE THREAD

**Issue by That-Annoying-Guy** [streetcomplete/StreetComplete#3527]
**Use case**
"Does this street have a sidewalk" quest needs "It does not exist" as many streets do not have sidewalks and creating a Crew note is tedious to create and process by the OSM community compared to what could be done otherwise.

**Proposed Solution**
"Does this street have a sidewalk" quest needs "It does not exist" answer as implemented in the "Is this bicycle parking covered" quest.
NOTE: MANY quests need their own "It does not exist" answers. (e.g. "What kind of building is this", "Is this picnic table covered", "what is the house number of this building", etc.)

**Comment by matkoniecz** [comment]
Have you tried tapping on each side and selecting that given side has no sidewalk and repeating it for the other side of road?

And then pressing OK?

Whole point of that quest is to allow mark whether it has sidewalk or not.

**Comment by FloEdelmann** [comment]
For the picnic table cover quest, this is already supported. Note that "It does not exist" refers to a missing picnic table, not a missing cover.

**Comment by Helium314** [comment]
> **Proposed Solution** "Does this street have a sidewalk" quest needs "It does not exist" answer as implemented in the "Is this bicycle parking covered" quest.

"It does not exist" refers to the object the quest is about (street or bicycle parking). So what answer do you want to give by that? "The street does not exist", or "the street does not have a sidewalk"?

You should *definitely not* answer "It does not exist" when asked whether a bicycle parking is not covered when you mean that the bicycle paring is not covered. (result: bicycle parking will be deleted)

**Comment by Helium314** [comment]
So maybe what "it" is referring to should be clarified.
Changing "It does not exist" to "this <object/place> does not exist" would help, but can get too long.

So maybe the text asking for confirmation could be adjusted from
"Are you sure that it does not exist, ..."
to something that includes the object, e.g.
"Are you sure that this bicycle parking does not exist, ..."
(Bad example, not working in all languages. But you get the idea)

**Comment by matkoniecz** [comment]
From what I remember it is shown already

**Comment by smichel17** [comment]
I don't think so. I could not find a quest to test with (or get it to show on the example forms), but from the code:

https://github.com/streetcomplete/StreetComplete/blob/d52f0ad0ed942d4dc807077d3f8fb5adfacebd4a/app/src/main/res/values/strings.xml#L1008-L1010

https://github.com/streetcomplete/StreetComplete/blob/b88db5db89c2c87f122de6aa948cc65197c51196/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractQuestAnswerFragment.kt#L342-L349

And/or maybe the confirmation action should be changed to `Delete` instead of `It does not exist`

**Comment by westnordost** [comment]
What exactly is unclear?

**Comment by That-Annoying-Guy** [comment]
The issue was that I was too stupid to use the GUI provided to say there was no sidewalks.

Dear SC Community, please accept my apologies for causing this storm of controversy.
Please just close this issue and not talk about it again.
