### ISSUE TITLE
Text style when showing nearby elements

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3530]
v38.0-beta1
In light theme, text for nearby elements is shown in same style as house numbers.
When switching to dark theme, the text doesn't change style with the rest of the map, making it harder to read:

![text_contrast](https://user-images.githubusercontent.com/43007630/143030377-def8ece5-a99a-4af9-ac25-593c3829f49e.png)

I think for readability and consistency, used style should always be same as for house numbers.

Maybe this is a map style issue? But I think the text style used is set in SC code, and not in the yaml files from mapstyle.

**Comment by westnordost** [comment]
This is because in markers, the constants from the map style cannot be accesed. See https://github.com/tangrams/tangram-es/issues/2305

**Comment by westnordost** [comment]
workarounded now, by accident referred to the wrong issue in the commit.

**Comment by smichel17** [comment]
For future reference, that's https://github.com/streetcomplete/StreetComplete/commit/02ace9dfff492a1122f27ba04f3a8be315e4a5cb
