### ISSUE TITLE
[Quest] Do these steps have tactile paving at the top and bottom?

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3534]
Apologies for mistakes, this is my first attempt at this:

### General
Affected tag(s) to be modified/added: [tactile_paving=] (https://wiki.openstreetmap.org/wiki/Key:tactile_paving)
Question asked: Do these steps have tactile paving at the top and bottom?
Answers same as crossing Yes / No / Can't Say

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [ ] 🚧 To be added tag is established and has a useful purpose - highway=steps has 16 913 instances of tactile_paving
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - yes
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - yes
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam) - Most are no, but more and more are yes as areas are redeveloped
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort) - believe so. I am in the UK. Not sure about other countries?

### Ideas for implementation
Copy and paste the crossing quest :-)

highway=steps
tactile_paving is unset

**Metadata needed:**  No meta data needed, but probably enabled/disabled on country by country basis

<!-- If you have any idea on how the UI (the form appearing when the quest is asked) should look like.
I am willing to try and get some photos, if needed, but the same images for Crossing can be used.

**Comment by westnordost** [comment]
Supposedly having tactile paving at the top is enough?

**Comment by westnordost** [comment]
I am not sure I have seen this anywhere though. Also not sure if this makes sense (to build). After all, steps are already quite tactile?

**Comment by timothywashere** [comment]
![PXL_20211017_145454125](https://user-images.githubusercontent.com/87654968/143249559-47489654-13db-4496-a5eb-d527332f7ddf.jpg)

The paving is for blind people, is placed on the footpath near the steps to warn them of the steps and to help them find the steps.

**Comment by timothywashere** [comment]
If I was writing a routing algorithm for assistive technology I would favour routes with the tactile crossings and steps etc over the ways without the tags, so I think it does serve a purpose.

**Comment by timothywashere** [comment]
Visited a new housing estate and all the stairs have them.
![PXL_20211125_185944282](https://user-images.githubusercontent.com/87654968/143500927-b15f94b7-85e3-4ea5-93ae-713000b158cb.jpg)
![Uploading PXL_20211125_190110053.jpg…]()

**Comment by timothywashere** [comment]
![PXL_20211125_190110053](https://user-images.githubusercontent.com/87654968/143501003-e9cb540b-2596-43e9-8954-eedb3cf44523.jpg)
![PXL_20211125_190350353](https://user-images.githubusercontent.com/87654968/143501014-312a3628-178e-46b2-8116-f7200eb42346.jpg)
![Uploading PXL_20211125_190439353.jpg…]()

**Comment by timothywashere** [comment]
![Uploading PXL_20211125_190439353.jpg…]()

**Comment by timothywashere** [comment]
![PXL_20211125_190439353](https://user-images.githubusercontent.com/87654968/143501073-209413a9-1b2d-4c35-a1ad-2f00f1c650dd.jpg)

**Comment by matkoniecz** [comment]
I would expect `tactile_paving` to be tagged rather on the first/last node of steps in such cases.

**Comment by timothywashere** [comment]
> I would expect `tactile_paving` to be tagged rather on the first/last node of steps in such cases.

Yes, according to the wiki that seems to be the way to do it.

How are crossings tagged by SC ? 
Does it tag the end nodes when the crossing is a way?

**Comment by westnordost** [comment]
It tags the curbs

Am 27. November 2021 21:20:40 MEZ schrieb timothywashere ***@***.***>:
>> I would expect `tactile_paving` to be tagged rather on the first/last
>node of steps in such cases.
>
>Yes, according to the wiki that seems to be the way to do it.
>
>How are crossings tagged by SC ? 
>Does it tag the end nodes when the crossing is a way?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3534#issuecomment-980795805

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by timothywashere** [comment]
Saw one today with tactile paving at the top but not bottom.

**Comment by westnordost** [comment]
Blocked because: It first needs to be discussed whether to set the tag on the steps way or on the nodes at which the tactile paving is located (usually start and end node of steps way).

See also the linked PR

**Comment by timothywashere** [comment]
If anyone wishes to raise this for discussion or a proposal and needs photos to illustrate, I have quite a few daytime photos now.

**Comment by mnalis** [comment]
I've asked on:
- https://wiki.openstreetmap.org/wiki/Talk:Key:tactile_paving#how_to_mark_on_steps%3F
- https://lists.openstreetmap.org/pipermail/tagging/2023-February/067042.html
- https://community.openstreetmap.org/t/tactile-paving-on-highway-steps/9215

**Comment by matkoniecz** [comment]
Hmmm, it may be better to ask in one place or in other just mention that discussion started (I responded at Wiki and realised that probably noone else will answer there)

**Comment by mnalis** [comment]
> Hmmm, it may be better to ask in one place or in other just mention that discussion started (I responded at Wiki and realised that probably noone else will answer there)

Yeah, joys of community fragmentation :cry:.
It's not that I enjoy wasting time posting the same thing three times either... :sob:  But in my experience, even if you designate one place for discussion, it doesn't really work - most ML people don't want to go to forum, forum people refuse to check ML, and neither of them like using wiki talk and will continue discussing in their turf... So hopefully people will bring same arguments elsewhere too. 

I'll summarize here from all three places afterwards.

**Comment by arrival-spring** [comment]
@mnalis Summary seems to be

>- tactile_paving=* should be marked on highway=steps way itself (and not on end nodes), and it is to be assumed that paving is only at top/bottom (and does not follow along the whole length of the steps, as that apparently doesn’t happen in real life)
>- if the tactile paving is only present on one side of the steps (most usually top of the steps, as it is the version that makes sense), it should be marked as tactile_paving=partial instead of tactile_paving=yes (which would be used if paving is present on both sides), and data consumer is to infer that.
>- in addition / alternatively, tactile_paving=incorrect might be used if tactile paving is only marked at the bottom (i.e. as wiki says “Where tactile paving is used but not in a sensible way”)

Question is what to do on the quest, could we just keep it consistent with other tactile paving quests and have one option in other answers for incorrect if it is not present at both top and bottom, or do we have one for each of "only at the top" and "only at the bottom"?

This also leads to a question of what would people do if steps are split into multiple parts (perhaps with footway in between).
