### ISSUE TITLE
junction=roundabout implies oneway=yes, quest shows bidirectional cycling lanes

### ISSUE THREAD

**Issue by lgommans** [streetcomplete/StreetComplete#3536]
The [`junction=roundabout`](https://lgms.nl/p/osm/cached-wiki/?page=Tag:junction%3Droundabout) wiki page states that "*[`oneway=yes`](https://lgms.nl/p/osm/cached-wiki/?page=Tag:oneway%3Dyes) is implied and redundant*".

When completing the cycling lanes quest for [this roundabout](https://www.openstreetmap.org/way/390812782), with [`cycleway=lane`](https://lgms.nl/p/osm/cached-wiki/?page=Tag:cycleway%3Dlane) but no `oneway` tag, StreetComplete asked about lanes in both directions. Cyclists are not allowed to drive against the flow of traffic in a typical roundabout so this question makes little sense, I assume that is the same practically everywhere but I could be wrong. A [similar roundabout here](https://www.openstreetmap.org/way/514329108) asks about only one direction, a relevant-seeming difference being that `cycleway=lane` is not set.

This was using v37.1 if I'm not mistaken (the last modified timestamp of the apk in `/data/app` is 45 minutes after the changeset).

**Comment by timothywashere** [comment]
It may be implied and obvious to a human, but might be more difficult for software to know which way around a path on a roundabout is meant to be going

**Comment by matkoniecz** [comment]
In such case `junction=roundabout` is sadly implied - so direction of the way still matters as like with `oneway=yes`.

**Comment by matkoniecz** [comment]
Can someone provide example of place where it is happening?

@lgommans Are you willing to share location?

![screen01](https://user-images.githubusercontent.com/899988/143308338-1ac1fdcf-a843-49c0-9787-08bd392e36bd.png)

![screen02](https://user-images.githubusercontent.com/899988/143309187-e7d00b22-3431-47a9-8622-846095445558.png)

**Comment by lgommans** [comment]
I think `cycleway=lane` may need to be set:

> A similar roundabout here asks about only one direction, a relevant-seeming difference being `cycleway=lane` not being set.

**Comment by lgommans** [comment]
Indeed, found a new spot to reproduce by looking with overpass-turbo for [`way[cycleway=lane][junction=roundabout]`](http://overpass-turbo.eu/s/1dqd): https://www.openstreetmap.org/way/368286616

**Comment by matkoniecz** [comment]
> I think cycleway=lane may need to be set:

Yes, I can confirm this using https://www.openstreetmap.org/way/52524941

**Comment by westnordost** [comment]
I suspect that the cycleway parser interprets `cycleway=lane` as `cycleway:both=lane` also for oneway streets. Will check...

**Comment by lgommans** [comment]
W00t, so quick! :) Thanks!

**Comment by westnordost** [comment]
Thanks!

Releasing a new version right now
