### ISSUE TITLE
Bridge type quest

### ISSUE THREAD

**Issue by chrisdebian** [streetcomplete/StreetComplete#3537]
Hi, all.

I've just noticed a new (to me) quest, concerning bridge types. It was good to see this quest, but it would be clearer if when adding bridge detail, some text accompanied the icon suggestions. I'm not familiar with the bridge tags, so maybe they could be referenced?

I hope this helps, just trying to make the quests even better.

![Screenshot_20211125-073859](https://user-images.githubusercontent.com/17935223/143400163-d6b96dd1-8616-46ee-abcd-176bd0bcadd2.png)

Thanks,

Chris
chris_debian

**Comment by matkoniecz** [comment]
I proposed it in #842 and it was rejected.

Though if some specific bridge is tricky and not really fitting any image - can you link/attach its photo?

**Comment by timothywashere** [comment]
I don't know how you could simply describe bridge structures in a way people would understand 

Cantilever bridges is a pretty big omission, although it has only been used once according to tag-info, people are likely to be miss-tagging cantilever bridges as beam bridges or arch bridges, which they are not.


double cantilever / kissing cantilever bridge
https://www.google.com/maps/@50.7967247,-3.4437155,3a,75y,30.36h,91.75t/data=!3m7!1e1!3m5!1sbCKA3lcPrOtqZA-WCO8q4A!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DbCKA3lcPrOtqZA-WCO8q4A%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D62.638126%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192

single cantilever bridge
https://www.google.com/maps/@50.3965125,-4.1239422,3a,75y,321h,99.82t/data=!3m6!1e1!3m4!1sXWuLb3B-uVg3g0fijB-CNw!2e0!7i16384!8i8192

Balanced cantilever bridges:
https://www.google.com/maps/@50.7934068,-3.4451428,3a,69.4y,197.78h,100.04t/data=!3m6!1e1!3m4!1sGxdtUHGw0V8s2iaqOzPBEA!2e0!7i16384!8i8192
https://www.google.com/maps/@51.0286726,-4.1981918,3a,75y,331.93h,100.87t/data=!3m7!1e1!3m5!1s2AWSFz_D-A8nFGN4j-yu4w!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3D2AWSFz_D-A8nFGN4j-yu4w%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D226.3275%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

**Comment by Helium314** [comment]
The quest is about `bridge:structure`, and is already asked for `bridge=cantilever` (which is used more than 1000 times according to taginfo)

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/keys/bridge%3Astructure#values seems to have single use of `cantilever`

So it should be discussed more widely with OSM community - https://wiki.openstreetmap.org/wiki/Tagging_mailing_list or maybe https://wiki.openstreetmap.org/wiki/Forum before it would be added to StreetComplete.

Editor adding new tags, especially if tags are hidden from user, without consulting community is a poor idea. 

>  is already asked for `bridge=cantilever` (which is used more than 1000 times according to taginfo)

Though only 191 is on `man_made=bridge` where this quest is being asked

http://overpass-turbo.eu/s/1dr3

-----------------------------

BTW, it seems we miss the most popular value: `beam` 

> A bridge that has no additional support between both ends.

**Comment by timothywashere** [comment]
> The quest is about `bridge:structure`, and is already asked for `bridge=cantilever` (which is used more than 1000 times according to taginfo)

That's odd. Guess the bridge tags are a mess. bridge= should describe the function of the bridge. bridge:structure would describe the design of the bridge. cantilever is obviously a structure. 


Image #2 is a beam bridge. It can have supports, butting underneath the deck, but no other reinforcement. ie it's the lack of red bits that makes it a beam bridge.

**Comment by matkoniecz** [comment]
Ah, I though that bridge without pillars would be a separate type.

**Comment by timothywashere** [comment]
If you forgive the crudeness and incompetence of my work, a cantilever would want to look something like this
![cantilever](https://user-images.githubusercontent.com/87654968/143443528-d96b882a-f175-49dd-a2ed-5416dfbc2a32.png)

**Comment by matkoniecz** [comment]
>  a cantilever would want to look something like this

Thanks for idea - but for now main blocker is lack of accepted tag. I lack knowledge here, maybe cantilever being missing makes some sort of sense.

New tag should be discussed with wider community before being used by SC.

**Comment by chrisdebian** [comment]
Hi, all.

I was thinking of the actual values, such as the ones found in the 'Values' section, here:

https://wiki.openstreetmap.org/wiki/Key:bridge

If it works for everyone else, then I'm happy to leave this.

Thanks,

Chris.

**Comment by timothywashere** [comment]
I know, sorry for hijacking your thread.

It would be nice if there was a description available, but where would it fit on the screen?

Perhaps there could just be a button next to "Can't Say" that would take you to the wiki page.

**Comment by timothywashere** [comment]
> > a cantilever would want to look something like this
> 
> Thanks for idea - but for now main blocker is lack of accepted tag. I lack knowledge here, maybe cantilever being missing makes some sort of sense.
> 
> New tag should be discussed with wider community before being used by SC.

I know, I intend to do something about this

**Comment by westnordost** [comment]
Alright, so best open a new issue after that
