### ISSUE TITLE
Uncommon German names shown for French places

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3538]
Hi there,

the town and village names in the Alsace region in the east of France are all shown in German language. This is at least very confusing as no German map, guidepost or road sign show "Schlettstadt" and "Oberehnheim" instead of the French names "Sélestat" and "Obernai" repectively (not to mention French maps/signs). Even German wikipedia redirects these German names from ancient times immediately to their French counterparts. The only (very few) exceptions are big and thus well-known towns close to the German border like Straßburg/Strasbourg or Mülhausen/Mulhouse, but Germans know of course the French names, too.

Could this be improved? Or is this in fact a Tangram issue and nothing can be done on SC side? The standard map on [www.osm.org](www.osm.org) shows the French names despite the fact that my Firefox browser is configured to prefer German. OsmAnd has a setting "Map language" with a list of languages to select from plus "Local names" (this setting is not connected to the app language setting which can be changed separately).

The same could be valid for former German regions in eastern Europe like Poland and the Czech Republic where you can find a funny mixture of German and Czech/Polish names on the SC map display, probably depending on the existence of the appropriate tags in OSM. (I'm not able to gauge how widespread the German names are in these countries though.)

The cycling cat

**Comment by matkoniecz** [comment]
>  The standard map on www.osm.org shows the French names despite the fact that my Firefox browser is configured to prefer German.

That is because it always shows `name` tag (local name).

For people using German language StreetComplete shows `name:de` if this tag was set.

> probably depending on the existence of the appropriate tags in OSM

Yes, exactly

> I'm not able to gauge how widespread the German names are in these countries though.

See http://overpass-turbo.eu/s/1drJ (press "run" to run query)

> This is at least very confusing as no German map, guidepost or road sign show "Schlettstadt" and "Oberehnheim" instead of the French names "Sélestat" and "Obernai" repectively

Would it be correct to say that this places have no German names but used to have? In such case retagging `name:de` to `old_name:de` would be viable but should be discussed with others.

Another option is to always show local names, but that in turn would make Greece/Russia quite confusing at least to me.

**Comment by matkoniecz** [comment]
So the questions is:

Is it incorrect to say "Oberehnheim is the German name for Obernai" ?

Is it preferable to always show local names over showing names in language of app?

**Comment by cyclingcat** [comment]
> See http://overpass-turbo.eu/s/1drJ (press "run" to run query)

I didn't mean the dissemination of the corresponding OSM tags but the one "in the wild" (e.g. on German maps, in German newspapers and so on). Sorry for the confusion.

> So the questions is:
> 
> Is it incorrect to say "Oberehnheim is the German name for Obernai" ?

Thie is certainly the correct German name, but you won't see it anywhere in Germany (at least according to my own experience).

> Is it preferable to always show local names over showing names in language of app?

In this case (Alsace) I would say: Absolutely. But I'm not sure if this can be generalised (hence I explicitly mentioned Poland/Czechia where the German names were probably common in pre-World War II times but I don't know about today). And then there are Arabic and Chinese names...

The cycling cat

**Comment by westnordost** [comment]
I don't see how this has anything to do with the app. The app just shows the data as it is tagged.

**Comment by matkoniecz** [comment]
> I don't see how this has anything to do with the app. The app just shows the data as it is tagged.

app can always show `name` (local name) instead of preferring names in language used by user (`name:de` in this case)

**Comment by riQQ** [comment]
Maybe the selection criterion could the alphabet. Use name, if it's the same alphabet (latin, cyrillic, etc.). Otherwise, use the localized name if it exists.

**Comment by matkoniecz** [comment]
For reference, name selection in map is done here: https://github.com/streetcomplete/streetcomplete-mapstyle/blob/jawg/global.yaml#L54
