### ISSUE TITLE
Add option to disable pop sound when solving a quest

### ISSUE THREAD

**Issue by NiklasMM** [streetcomplete/StreetComplete#3539]
I would love an option to disable the pop sound when solving a quest or at least have the app respect DND mode and not play it.

**Comment by matkoniecz** [comment]
See #2966

You can configure it by phone-wide sound system obeyed by apps in general.

https://github.com/streetcomplete/StreetComplete/issues/2966#issuecomment-862744441 has some research how it is named at least on one specific phone

**Comment by NiklasMM** [comment]
Of course I can disable it by muting media sound, but as stated in the issue you linked that affects all media and makes it impossible to e.g. listen to music while using street complete.

**Comment by FloEdelmann** [comment]
You can disable *Screen touch* sounds (click sound when tapping Androids back or home button etc.; or in StreetComplete: solving a quest) independently from adjusting *Media sound volume*.

**Comment by NiklasMM** [comment]
Interesting. This does not seem to be true. The plop when solving quests reacts to the media volume and nothing else. I always have screen tap sounds disabled, I don't know if Street Complete has any other sounds, but that's the only one I'm hearing.

This is on Android 11, Lineage OS to be precise.

**Comment by Helium314** [comment]
StreetComplete enables sound effects it a certain [system setting](https://developer.android.com/reference/android/provider/Settings.System#SOUND_EFFECTS_ENABLED) is enabled.
On my phone (LineageOS 16) this setting is set by "Touch sounds" setting.

The related part (TouchSoundPreferenceController in settings app) is the same in 16 and 18. Not sure what else has changed in LineageOS 18.

**Comment by matkoniecz** [comment]
@NiklasMM Do you have "Touch sounds" setting or "Sound effects" or similar?

Which Lineage OS version you use?

https://gitlab.com/LineageOS/issues/android/-/issues?scope=all&state=all&search=SOUND_EFFECTS_ENABLED claims that no bugs about this were filed so far (note, you need to log in to search - seriously GitLab)

**Comment by westnordost** [comment]
Well, the app respects the system setting. It makes no sense to introduce an app-setting that does the same in case the system-wide setting doesn't work.
