### ISSUE TITLE
New Quest: What kind of water is it?

### ISSUE THREAD

**Issue by hungerburg** [streetcomplete/StreetComplete#3542]
For once, a quest on something not man made :) Might be a nice pastime nevertheless. There are lots (at least in my area) "natural=water" features mapped, that lack a specific "water=*" tag. Wording perhaps:

Is this a
- lake, pond
- river, stream, oxbow
- canal, reservoir, wastewater

or is it in fact something else, a wetland, a pool, a swimming_pool, etc?

**Comment by smichel17** [comment]
Can you edit your post to fit the [quest suggestion template](https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md)?

<details><summary>Copied here for convenience</summary>

```
<!-- 
Please read the guidelines for new quest suggestions before posting one: 
https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete
-->

### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

<!-- If the answer is not obvious, please add a short explanation below each item. -->
### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)

<!--
All of the above should be fulfilled. 
If you are not sure about how one condition applies to your suggestion or you have (very) strong reasons that a condition may not needed to be satisfied in your case, just note that down. Someone else may come up with some ideas.
-->

### Ideas for implementation

<!-- If you have any idea for how elements should be selected, add it here. -->
**Element selection:** 

<!-- If you have any idea whether metadata per country is needed, add it here. If you know where to get this data from, mention it here too -->
**Metadata needed:** 

<!-- If you have any idea on how the UI (the form appearing when the quest is asked) should look like.
You can use any way to propose a UI. Feel free to include a mockup. 
Do include all answer possibilities you consider for that quest. -->
**Proposed UI:**
```
</details>

**Comment by hungerburg** [comment]
I've read that, what formalities are to be met?

**Comment by peternewman** [comment]
Just to lay it out in that format please @hungerburg as it makes it easier to parse/process and compare.

E.g. you haven't mentioned any UI preference

**Comment by peternewman** [comment]
From a practical point of view, we'll need to work out how to offer and differentiate between these in a user-friendly way (my bold):
natural=water water=lake | A lake:  a body of relatively still fresh or salt water, localized in a basin  that is surrounded by land. **Artificially** created **lakes should instead be tagged as** water=pond or water=reservoir.
natural=water water=oxbow - An oxbow lake: U-shaped body of water formed when a wide meander from the main stem of a river is cut off to create a lake.
natural=water water=pond - A pond: a body of standing water, man-made in **most** cases, that is usually smaller than a lake.

Personally I despair why it's not natural=water water=lake lake=oxbow or something, or maybe even natural=water water=body body=lake lake=oxbow, but there we go.

**Comment by matkoniecz** [comment]
Important thing to check: are known, accepted and documented values of `water` covering all valid `natural=water`?

See https://wiki.openstreetmap.org/wiki/Key:water

I see nothing obvious missing so I started review of local `natural=water`

**Comment by hungerburg** [comment]
A bit of background: In the local forum a member of project group to "modernize river areas" asked, if there were "problems running the modernization". I used their recipe to look at what would be targeted and "modernized" a few rivers and a few swimming_pools :) Someone else on the forum mentioned, they would like a roulette, but from my impression of the data I thought, that this might not always be so easy from the aerial. So I concluded, StreetComplete to the rescue :)

One more look later at the data, e.g. closed ways with natural=water and no water: and size>10000 (1ha), many indeed can be classified from aerial, and if not, probably hard on site too. So closing this, sorry for the noise. Thank you for comments.

**Comment by peternewman** [comment]
I think you may have closed this a bit prematurely @hungerburg . I think @matkoniecz may agree from his comments too.

I'm not sure how easily you could tell whether a pond/lake is man-made or not from a satellite view (although it may not be much easier on-site).

One thing that did stand out from my quick look was golf course water hazards, they seem to have another tag so should possibly be excluded.
