### ISSUE TITLE
Clicking on this quest crashes

### ISSUE THREAD

**Issue by ChildishGiant** [streetcomplete/StreetComplete#3545]
**How to Reproduce**
Try to click on the "How is the footpath and bike path laid out" on this way https://www.openstreetmap.org/way/290526051

https://user-images.githubusercontent.com/13716824/143682048-699c3d8b-0776-4115-b8ff-dc5e4ac062a3.mp4

The report feature also doesn't work with protonmail but that's a separate issue.

**Comment by Helium314** [comment]
Which version are you using? There was a bug like this in v37.something

> The report feature also doesn't work with protonmail but that's a separate issue.

Does it work with other apps? Maybe it's a protonmail issue

**Comment by matkoniecz** [comment]
> The report feature also doesn't work with protonmail but that's a separate issue.

Weird. Looking at logs would be needed, maybe protonmail app is not registering itself as email provider?

Is [this link](mailto:example@example.com) opening in protonmail app? If not, then protonmail is simply broken in this aspect. If this one opens empty email to example@example.com then investigating more can help.

**Comment by mnalis** [comment]
@matkoniecz looking at `11th` second in the video, it seems that Protonmail opens, but complains that `The address '' is invalid and was removed`

Also in the video it seems that not only recipient e-mail was lost, but message body (which should containt the report) also looks empty.

(As a datapoint, in my experience at least `StreetComplete v37.2` worked normally with `K-9` mail client, filling both the `To:` field and report in message body.)

**Comment by matkoniecz** [comment]
@mnalis That is why I want to test is it working with simplest possible thing, a mailto: link

**Comment by ChildishGiant** [comment]
> Which version are you using? There was a bug like this in v37.something
Ah, I'm on 37.1. I imagine that updating will fix this. I'm happy to do tests for the proton mail issue but I think this may be on their end as I recall a similar issue with another app. I've tried a simple mailto: and that's working

**Comment by matkoniecz** [comment]
> I recall a similar issue with another app

In such case I would be happy to blame Proton mail - and I would report problem to them. Maybe they made some mistake in handling triggering from other apps in general?

> Ah, I'm on 37.1. I imagine that updating will fix this. 

And in this case I will blame 37.1 - please upgrade to fix this (though 38 has another bug with losing GPS position)
