### ISSUE TITLE
[Quest] Is there a live departures board at this stop/station/platform?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#3553]
### General
Affected tag(s) to be modified/added: [Key:passenger_information_display)](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display)
Question asked: **Is there a live departures board at this stop/station/platform?**
I'm not sure which of the three is the right option, so I will let you decide.

Answers:
yes - add `passenger_information_display=yes`
no - add `passenger_information_display=no`

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
It can depend on the area. Some areas might have a lot of stops with live departures boards, some areas might have none. I'm not sure if that one applies to this quest or not.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/1974#issuecomment-661904019

Right now it appears to be blocked until tagging is clarified.

https://wiki.openstreetmap.org/wiki/Talk:Key:departures_board https://wiki.openstreetmap.org/wiki/Talk:Key:passenger_information_display

I would discuss it first at tagging mailing list (or possibly somewhere else) to establish a clear tag for marking this, before making a quest.

Note - this person will not be me, but it can be you, whoever you are reading this. If you have trouble with how to post to tagging mailing list I can help.

This can be also discussed elsewhere, or done via a proposal.

**Comment by matkoniecz** [comment]
Closing per https://github.com/streetcomplete/StreetComplete/issues/1974#issuecomment-687033697

I am also not entirely sure is this information useful to collect, but it is a separate issue.
