### ISSUE TITLE
Problem with switching languages

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#3554]
SC is having some problem when changing it's language. I assume that it's because language files are downloaded on the go which causes some delay.
**How to Reproduce**

1. Search for quests in the area and open a few of them to check in what language they are
2. Go to Setting in SC and change the app language (it will either close itself or do nothing)
3. Notice that the language in settings changed to the default language of the phone
4. Check the same quests: if you haven't used that language before, SC will default to the phone's default language. Otherwise it will show it in the language selected.
**Versions affected**

StreetComplete v38.1
Android version: EMUI 10.0.0.262

**Comment by matkoniecz** [comment]
What happens when you change language to Polish?

For my phone changing language to Polish works while Bulgarian/Russian/German/French does not.

I though that it may be related to listing Polish as secondary phone language, but adding French to preferred language list changed nothing.

https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app lists Bulgarian as a fully translated

>  I assume that it's because language files are downloaded on the go which causes some delay.

No, all translations are in app. You can check by disabling internet and switching phone system language.

**Comment by Dimitar5555** [comment]
Changing it to Polish does nothing even after restarting the app.

**Comment by matkoniecz** [comment]
That is weird. I switched off phone, changed phone to French and interface is still English.

I restarted phone.

Still English.

Enabled internet and now is in French. I was wrong and it is actually downloaded, I see now bunch of apps reporting downloading of language files.

**Comment by Dimitar5555** [comment]
A possible solution could be to make the menu for changing the language a separate screen/window (I'm not sure what's the exact terminology) and add a download button for each language. After the download is started, there can  be something to show the progress and when done there can be an `Apply` button next to it.

A second solution could be to show a popup that says `Downloading language` with a progress bar and after it's done, it's applied to the app.

These solutions are not exactly solutions but it will make it clear to the user that something is happening.

**Comment by mnalis** [comment]
Perhaps it might have something to do with those split-APK thingies that Google Play allegedly seems to do? My debug build is single `.apk` file of about  52.2 MB. When manually unzipping it, it seems the Croatian and many other languages texts are stored inside `resources.arsc` with size of about 4.2 MB. It would be interesting to see if F-droid version is also affected...

**Comment by smichel17** [comment]
I was going to suggest the same thing. I'm pretty confident that the extra download is a Google Play split bundle thing.

**Comment by matkoniecz** [comment]
If it is a new thing then it would explain why I was sure that it is included and why debug build worked fine when I tested language switching.

**Comment by smichel17** [comment]
It's been around for ~1 year, I think, but became mandatory this July. https://developer.android.com/guide/app-bundle/

**Comment by westnordost** [comment]
https://developer.android.com/guide/app-bundle/configure-base#disable_config_apks

**Comment by westnordost** [comment]
all languages should now be bundled on Google Play, so each individual installation of the app will be about 1MB larger - that's okay.
