### ISSUE TITLE
Add NotesReview link as a SC achievement

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3559]
**Use case**

1. I've always like the idea of connecting SC surveyors with armchair mappers, as some tasks are more efficient to do one way or the other. The social element is also nice; it builds a little more community feeling.

2. When I finished mapping my immediate walkable area in SC (~20-30 minute walking radius from my house), there was a drop in how much I went mapping for a while. At that point, something like NotesReview might be a natural transition for mapping, for people who aren't ready to just jump into iD without any particular direction.

**Proposed Solution**

Add an achievement which links to [NotesReview](https://ent8r.github.io/NotesReview/?query=StreetComplete&limit=100&start=true) (same link from `CONTRIBUTING.md`). It could be awarded something like every 1000 quests answered or every 50 notes opened.

**Comment by smichel17** [comment]
Icon for the link: https://github.com/ENT8R/NotesReview/blob/main/app/svg/assets/notesreview-small.svg

There's already an achievement for number of quests answered ("Surveyor"), so if we only add it to that, then there's no additional artwork required. There's currently no achievement for opening notes, so that would require artwork.

**Comment by westnordost** [comment]
The NotesReview is not really interesting for the target group of SC. To add such link should come after linking to some comprehensive / easy introductions to desktop editors (iD / JOSM)

**Comment by matkoniecz** [comment]
I think that for narrow group of very active SC users it would be worth showing.

After 1000 edits rather than after 100 edits.

**Comment by smichel17** [comment]
I think that addressing other SC users' notes is an ideal way to transition from SC-only mapper to someone who also uses other editors. After mapping with SC for a while, you will probably leave many "can't say" notes. So, when you transition to another editor and look at those notes created by other SC users, you have this context about what kind of situation you're looking at.

So, I agree that it would be good to *also* include a link to a other editor documentation, but I think it should come at the same time as the NotesReview link, not before.

1000 edits may not be the right number. Maybe it should be 1500 or 2000. Or 1500 edits *and* 50 notes opened.

**Comment by westnordost** [comment]
Does anyone know a good and comprehensive beginners guide or videos to JOSM / iD?

**Comment by matkoniecz** [comment]
iD has quite nice built-in walkthrough, though I am not sure how well it works in practice

JOSM - no idea. Asked some time ago and found nothing

**Comment by matkoniecz** [comment]
https://learnosm.org/en/josm/ is pinned on Discord in #josm channel - I have not reviewed it so far

**Comment by matkoniecz** [comment]
There is also an official https://josm.openstreetmap.de/wiki/Introduction
