### ISSUE TITLE
[Quest] What's the name of this school?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#3560]
### General
Affected tag(s) to be modified/added: [Key:name](https://wiki.openstreetmap.org/wiki/Key:name) on [Tag:amenity=school](https://wiki.openstreetmap.org/wiki/Tag:amenity=school)
Question asked: **What's the name of this school?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
Currently there are ~1.1 million `amenity=school` objects of which ~1 million have names. That leaves ~100k schools without names.

### Ideas for implementation
Same as other `name` quests.

**Element selection:** 
`amenity=school` objects with no `name` tag

**Metadata needed:** 

**Proposed UI:**

**Comment by mnalis** [comment]
Doesn't it already ask `What is the name of this place` for it ?

I think it should: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt#L61

**Comment by Dimitar5555** [comment]
It also asks for schools.
