### ISSUE TITLE
Add answer option "It's another type of barrier" to "More Answers..."-section of Cycle-Barrier-Type and Bollard-Type quest

### ISSUE THREAD

**Issue by wielandb** [streetcomplete/StreetComplete#3563]
**Use case**
Since the Cycle-Barrier-Quest came out, I noticed some cycle-barriers in my area are not actually cycle-barriers but bollards or something else. When I came across some gates today that were tagged as bollards, I got the idea that the re-tagging could be done directly in StreetComplete as we already have a quest to determine barrier types.

**Proposed Solution**
Add the answer option "It's another type of barrier" to the "More Answers..." section of the quests "What kind of cycle barrier is this?" and "What kind of bollard is this?". When chosen, it converts `barrier=cycle_barrier` and `barrier=bollard` back to `barrier=yes` (similar in the way that a building gets "converted" back to `building=yes` when you answer that the building type is wrong in the housenumber quest), which would promt the Barrier-Type-Quest to show up, allowing quick correction of false bollards and cycle_barriers.

Of course, I would apprechiate feedback if falsely tagged `cycle_barrier`s and `bollard`s are a occurence for other users too to see if this addition is worth the effort.

**Comment by ygra** [comment]
Haven't seen wrongly-tagged barriers here in the vicinity yet, but I could imagine it happens sometimes. And in those cases an answer option that spells out what's wrong instead of having to write a note can be useful.

**Comment by matkoniecz** [comment]
Interesting idea, I will look at how often this quest results in notes.

For reference, it was #3487 that added it

https://ent8r.github.io/NotesReview/?view=map&query=Unable%20to%20answer%20%22What%20type%20of%20bicycle%20barrier%20is%20this%3F%22&status=null&before=null indicates that so far just 8 notes were opened for this quest.

So I will close this one without implementing.
