### ISSUE TITLE
Add button to swap sides of road for cycleway, sidewalk, etc

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3572]
**Use case**
The semi-new "prefill last answer" button for this type of quest is great. However, sometimes I want to apply those answers to the opposite sides of the road than I currently have the map oriented.

I originally thought that this would be easy: just rotate the map 180°, tap the pre-fill button, then rotate back. Unfortunately, when I tried it in practice, the rapid rotation was disorienting; it took me longer to double-check that I was applying the pre-fill to the correct sides than it would have for me to fill out the form normally.

**Proposed Solution**
If the answers for each side of the road are different, show a button like :arrows_counterclockwise: which swaps which sides of the road the answers are applied to. It can inhabit the same position where the pre-fill button sits, since the two will never be shown at the same time.

**Comment by westnordost** [comment]
This just adds clutter for a functionality that is already there, as you stated.

**Comment by smichel17** [comment]
It is about convenience/speed. Same as adding the pre-fill button in the first place — it does not enable anything new, just a faster and less confusing way to do a common thing.

**Comment by westnordost** [comment]
yes

**Comment by westnordost** [comment]
But I don't like that it fraughts the interface with buttons,  so I don't plan to include that
