### ISSUE TITLE
Raise fire hydrant diameter quest only for a subset of fire hydrant types

### ISSUE THREAD

**Issue by demsjf8** [streetcomplete/StreetComplete#3575]
In my understanding at least for where I live (Germany), wall hydrants usually do not have a sign that gives further specifics regarding the wall hydrant, in particular not the hydrant diameter. In fact, unlike for e.g. pillar and underground hydrants, which are typically connected to a "standardized" pipe network, the diameter of the pipe feeding a wall hydrant is typically not any of the "standard" diameters. Underground and pillar hydrants are usually connected to a "standardized" pipe network so that the given diameter can be usefully used to derive an approximation of the strength of the flow of water that can be expected.
As wall hydrants are typically added to buildings of some sort, the plumbing to feed the hydrants needs to be custom designed such that a certain level of "performance" at the hydrant is achieved, taking into account the specifics of the particular building (e.g. the floor at which a wall hydrant is located). Thus it seems not useful to capture a hydrant diameter for wall hydrants (the performance of the hydrant does not need to be derived, but it has been designed to a known specification).

Thus the proposal to suppress/not raise the fire hydrant diameter quest for wall hydrants.

While technically correct to answer the quest with "no sign", this in my understanding will be the answer for the vast majority of (if not all) wall hydrants, so why ask the question in the first place?

What I obviously don't know is what the situation elsewhere, i.e. whether this would apply generally, or only a subset of countries.

**Comment by smichel17** [comment]
The quest is only enabled in a handful of EU countries: DE, BE, GB, PL, IE, FI, NL

Does it make more sense to **exclude** wall hydrants from the quest, or to ask the quest **only** for certain [types of hydrants](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant#fire_hydrant:type.3D.2A_details)?
Worldwide, it looks like almost all mapped hydrants are underground or pillar: https://taginfo.openstreetmap.org/keys/fire_hydrant%3Atype#values
I'm not sure how to restrict a search to just the countries we ask in.

The code for the quest is here: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/fire_hydrant/AddFireHydrantDiameter.kt

**Comment by FloEdelmann** [comment]
Ping @thefeiter as author of that quest.

**Comment by demsjf8** [comment]
From (my) user perspective, I would think that the more relevant piece of information for a data consumer is the hydrant type, because that is most relevant in actually finding the hydrant in the first place (by knowing what to look for). So I'd tend towards the "ask the quest only for certain types of hydrants" option, in the sense of having the hydrant type quest raised first if the type info is missing.
Similarly, it might be less confusing to an SC user to only get asked the diameter question (suggesting that there should be a sign to look for) if the user is likely to actually find a sign with the desired information.
In my (regionally very limited) experience, even pillar hydrants usually don't have sign. So far, I found only one pillar hydrant that had one. That was on private property, and the sign looked more like a hand-made one rather than the "official-looking" signs that the local public operator puts up. I've yet to see a sign for public (as far as discernible from context) pillar hydrant. But as said, my experience is regionally very limited, and I like the quest to be raised for pillar hydrants anyway so I know the info is missing and can try to find it by other means.

**Comment by smichel17** [comment]
> So I'd tend towards the "ask the quest only for certain types of hydrants" option, in the sense of having the hydrant type quest raised first if the type info is missing.

Note: we could ask the quest only for fire hydrants which have a type, without restricting what the type is. So it's still a choice between:

- Ask for any fire hydrant that has a type, unless the type is `wall`.
- Ask only for some types of fire hydrants (e.g. just underground or pillar)

**Comment by demsjf8** [comment]
I'd vote for the second. I.e. raise only for hydrants where the type is defined, AND the type has a certain value (those types where it is positive that there is going to be an explicit sign with the hydrant data, i.e. definitely underground, arguably pillar).

Will change the title of this issue accordingly.

**Comment by demsjf8** [comment]
@matkoniecz, thanks for creating and merging the patch!
Everyone, thanks for your input, feedback, and the clarifying discussions!
