### ISSUE TITLE
House number with letters, not just numbers

### ISSUE THREAD

**Issue by angoca** [streetcomplete/StreetComplete#3579]
**Use case**

In many Latin American countries, the street names follow the pattern of a grid, with numbers: Calle 1, Calle 2, etc. Some of these streets have extra letters like Calle 1A, Calle 2B Bis, Carrera 3, Diagonal 4, etc.

The house number is not just a single number along the street, but it includes the number of the previous street. For example 1-1, 2-7. The problem is when the previous street has letters like 2B Bis-1. The application only allows entering numbers, hyphens, and periods, not other characters, because it shows the numeric keyboard.

A more complete description of this street naming convention, specifically for Colombia is at:

* https://wiki.openstreetmap.org/wiki/Colombia/Guide_for_mapping#Street_names
* https://wiki.openstreetmap.org/wiki/ES:Colombia/Nomenclatura_para_calles (In Spanish)

I have inserted the house number in this changeset: https://www.openstreetmap.org/changeset/114756007#map=19/4.71035/-74.05844 but as you can see, the number is not 127-15, but 127B-15 (https://www.openstreetmap.org/way/804814179). The surrounding streets are Calle 127B and Calle 127B Bis.

**Proposed Solution**

The current numeric keyboard is great for most of the house numbers in the world. However, it will be great to change the keyboard to the complete one (qwerty) to fulfill with more complex house numbers.

**Comment by matkoniecz** [comment]
What happens when you press abc Burton toward right?


Though maybe in some regions it should be default

**Comment by angoca** [comment]
I haven't seen that ABC button. That what I was asking.
You can close the ticket.

**Comment by matkoniecz** [comment]
Though if in Colombia very large part of addresses includes not only numbers but other signs...

Then full keyboard appearing as default may make sense - so it would be OK to open an issue for that if it is necessary there.
