### ISSUE TITLE
geo: intent does not change map location

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3580]
SC implemented `geo:` intent back in https://github.com/streetcomplete/StreetComplete/issues/190 - however (as noted by @smichel17  in https://github.com/streetcomplete/StreetComplete/issues/426#issuecomment-989337939) while it does seem to open SC when it is selected in list of supported apps, it does not seems to position SC at specified coordinates (instead SC seems to remain at last coordinates it was on). Correct  behaviour should be that SC positions to specified `geo:` location.

**How to Reproduce**
- open some other mapping app like OsmAnd
- click an `share geo:` button in it
- select StreetComplete in the list
- StreetComplete `v38.1` opens, but **does not position** to location that was selected in OsmAnd

Note: the bug is reproducible with vanilla `38.1`, however if I try to share to @Helium314 fork  `v34.0-beta1` version (that I also have installed, in parallel) it seems to change position fine there. So perhaps something broke between those versions? 

**Versions affected**
SC v38.1, Android 10

**Comment by matkoniecz** [comment]
How one may trigger this functionality?

**Comment by mnalis** [comment]
> How one may trigger this functionality?

Uh, I made 4 bullet points on how to reproduce; should some of them be better explained @matkoniecz? (or did you simply not see them?)

One needs some other mapping/navigation app in addition to StreetComplete in order to reproduce this bug - in _"How to reproduce"_ I've selected OsmAnd as popular open source app with which it can be reproduced, although one can use for example Vespucci or other apps which support `geo:` intent sharing. 

Or did I misunderstand what you are asking?

**Comment by matkoniecz** [comment]
Sorry, I somehow failed at reading (I got distracted by something as I was going through notifications), sorry.

**Comment by matkoniecz** [comment]
And now for actually useful comment.

Note that in `v34.0-beta1` this works only when "follow current location" is disabled, otherwise move is immediately undone. But it works in such case.

**Comment by HolgerJeromin** [comment]
This is a recurring regression:
#2227, #1426

**Comment by matkoniecz** [comment]
bisecting between `v34.0-beta1` and current version found 5820b40132845c74a7a82080c689a065ecaa533d as point where it reappeared

**Comment by smichel17** [comment]
https://github.com/streetcomplete/StreetComplete/blob/ab3b1d756b9de73de75354e8d976df83e420cb4b/app/src/main/java/de/westnordost/streetcomplete/MainActivity.kt#L118-L125

Perhaps the `FragmentContainerView` means the `MainFragment` is initialized late and still null at the time of this call?

**Comment by matkoniecz** [comment]
> Probably a good idea to write a test or two for it

Personally I have no good idea how to setup something automatically testing this

**Comment by westnordost** [comment]
In StreetComplete, there are not any UI tests. I think UI tests are not worth the effort. It is likely that you identified the issue correctly. Not sure how this could best be fixed though... adding a delay?
