### ISSUE TITLE
translation issue in French regarding clay tennis court

### ISSUE THREAD

**Issue by alexnoob** [streetcomplete/StreetComplete#3584]
Hello, I hope it's the right place to warn about a small issue regarding French translation of "clay" for tennis courts: currently it's misleading as it's using the litteral translation of the word ("argile"), while clay court should be translated by "terre battue".

Proof: Check the French article linked from Wikipedia "clay court" article https://en.m.wikipedia.org/wiki/Clay_court

Hope that helps!

**Comment by matkoniecz** [comment]
Good news: translations are relatively easy to fix by anyone, see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

You can translate StreetComplete at POEditor. You can add missing translations and improve existing ones.

The only required skills here are ability to read English text and write in your own language.

Follow [**this link** to improve the translations](https://poeditor.com/join/project/IE4GC127Ki):

[![POEditor](https://poeditor.com/public/images/logo_small.png)](https://poeditor.com/join/project/IE4GC127Ki)

After joining, the [main site of the POEditor](https://poeditor.com/projects/) should list StreetComplete for logged in users.

**Comment by matkoniecz** [comment]
Though this specific is a bit tricky - it is currently used only for pitch surfaces, but defined in way that allows it to be used for example in path surface quest (but this seems unlikely?)

**Comment by alexnoob** [comment]
Thanks, I left a comment on POEditor!

**Comment by FloEdelmann** [comment]
> it is currently used only for pitch surfaces

See `Surface.kt`:

https://github.com/streetcomplete/StreetComplete/blob/7fcad22711e28da4866aeac42c9e89bd2dd81cd6/app/src/main/java/de/westnordost/streetcomplete/quests/surface/Surface.kt#L48-L55

> allows it to be used for example in path surface quest (but this seems unlikely?)

I'd say, @alexnoob feel free to update the translation now. If (at some point in the future) we decide to add clay to e.g. the list of possible "path surface" answers, we either remember this issue and split it into two strings, or we forget it and it comes up again when updating the French translation.

**Comment by FloEdelmann** [comment]
By the way, @alexnoob thanks for translating some other French strings!

**Comment by alexnoob** [comment]
Nice, I've updated the "clay" string. Thanks a lot for your feedback!
