### ISSUE TITLE
[Feature request] Add option to split building

### ISSUE THREAD

**Issue by J4gQBqqR** [streetcomplete/StreetComplete#3585]
A lot of times, non-detached twon houses are mapped as a single unit on map. However, there might be 4-5 standalone unit and street addresses on that mapped unit. Currently, there is no way to split the building easily in this software. As a result, street number cannot be added correctly.

Can this software add capability to split a single building into several units and add the street number for each of them?

Thank you.

**Comment by matkoniecz** [comment]
See #2585
