### ISSUE TITLE
Building levels list removes new entries too quickly

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3593]
The new buildings level list with remembering answer count is useful if you have a lot of houses with similar levels. But it is quite annoying if you move from an area with 1-2 level houses to an area with higher houses, e.g. 4-6 levels.
If you do this, you will see your last answer, and a bunch of 1-2 levels answers. This gets better only after solving many building level quests, and I foud it rather irritating.

I don't know how the selection of answers works exactly, but some ideas for improvement:
* show the last 2 or 3 answers instead of only the last one
* remember fewer previous answers
* forget (some) previous answers after a while, or upon restart

Note that the ideas are for this specific use case, so they may make things worse in different cases. Not sure what should be considered here.

**Comment by westnordost** [comment]
Currently the last answers are persisted (forever). I am also thinking about whether it wouldn't make sense to completely drop the functionality that it is persisted but instead only memorize it for this session (i.e.  until the app is ended)

**Comment by matkoniecz** [comment]
For me it is very useful as in my area buildings are almost always 1, 2, 2+1, 1+1, 4, 5, 10, 12 levels.

So losing history on closing app would be frustrating.

**Comment by smichel17** [comment]
> I don't know how the selection of answers works exactly

- Check the last 30\* answers in the history and get the 6 most common ones.
   \*Sometimes more, but not for the building levels quest.
- If the most recent answer is not included, then add it.
   - If there were fewer than 6, it's just added. If there were 6, it replaces the least-common answer.

As I said back when I [added the feature](https://github.com/streetcomplete/StreetComplete/pull/3373#discussion_r730184583), I'm pretty confident that the algorithm is right, but the numbers I chose were totally off-the-cuff estimates.

> Currently the last answers are persisted (forever).

Technically they are never cleared, but only the last 100 entries are persisted.

> some ideas for improvement

Those are pretty much the solutions I came up with in https://github.com/streetcomplete/StreetComplete/discussions/3493#discussioncomment-1602090. That discussion was about building **type**, so my [conclusion](https://github.com/streetcomplete/StreetComplete/discussions/3493#discussioncomment-1745118) was, "I suspect it's a good idea to show more recent entries, but I want to change only one thing at a time, so I'll change just the sort order first." That's in https://github.com/streetcomplete/StreetComplete/pull/3564.

So, this is good evidence that, at least for the building levels quest, we need tweaks. Also, I realized when writing the earlier paragraph that there are only recent 5 entries in the building levels quest; the building type quest suggests 6 values, which is what I was thinking about when I picked 30 history entries.

Overall, the two most promising ideas I see are:

1. Just lower the amount of history considered.
2. Show more most-recent answers (2 or 3), and also track *more* history.

I'll get https://github.com/streetcomplete/StreetComplete/pull/3564 merged, then send something for this.

**Comment by smichel17** [comment]
Like the building type quest, I would like to only change one thing at a time and test its affects before making other changes.

Since the affect of just lowering the history considered is pretty well-known, I think here I'd like to try showing more recent answers and see if that helps. @Helium314 would you be up for testing that?ddd

**Comment by Helium314** [comment]
> would you be up for testing that to see if it helps?

Sure, just tell me what to change!

**Comment by smichel17** [comment]
To change how much history is considered, change the `30` here.

https://github.com/streetcomplete/StreetComplete/blob/3f7a787ea61e5a565edffbf2b2b9f66b2945eb1e/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevelsForm.kt#L35

To change how many most-recent values are shown, change the `1` here.

https://github.com/streetcomplete/StreetComplete/blob/3f7a787ea61e5a565edffbf2b2b9f66b2945eb1e/app/src/main/java/de/westnordost/streetcomplete/quests/LastPickedValuesStore.kt#L41

This one also affects the building type quest; I plan to pull it up into a parameter so they can be different, but for testing it doesn't matter.

**Comment by matkoniecz** [comment]
@smichel17 Thanks for your improvements on this topic! The recent changes feel much smarter now with clippy-type "computer is trying to be smart, fails" issues.

(because there is no better place for this)

**Comment by smichel17** [comment]
> The recent changes feel much smarter now with clippy-type "computer is trying to be smart, fails" issues.

I am having trouble interpreting whether you mean this in a good way or bad way :laughing:
If you were a native speaker I would say it sounds sarcastic-ish, but I am pretty sure it is meant literally.

Anyway, I agree that it is the type of "smart"/algorithmic behavior that SC usually does not do. I introduced it, so I'm willing to do the legwork of tweaking the algorithm until it's in a good spot.

That said, it's also an easy algorithm to balance— as I noted above, both the parameters are basically knobs to tweak *how "smart" it tries to be;* turning either of them to the extreme reverts to the original behavior. The new behavior started with the knobs turned pretty far towards "smart," and now we're slowly dialing them back (by using more most-recent values or considering less history) toward "simple" until we find a middle ground where we get some of the benefits of the smartness without the clippy failures.

> (because there is no better place for this)

https://github.com/streetcomplete/StreetComplete/discussions/3493 or a new discussion would be good too. This is also fine— the steps to fix this issue are known, so there's no discussion to derail :)

**Comment by matkoniecz** [comment]
>  If you were a native speaker I would say it sounds sarcastic-ish, but I am pretty sure it is meant literally.

Whops. No, it was not sarcastic at all sorry. Yes, it is an improvement.

**Comment by smichel17** [comment]
No functional changes, but you can now tweak both parameters in one place:

https://github.com/streetcomplete/StreetComplete/blob/583da6031f3b3c2ee086c7f5c9ede08c5ee283da/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevelsForm.kt#L35

Also the number of recently-picked items, if you want.

**Comment by Helium314** [comment]
This looks good!
I currently have it at `historyCount` 15, but so far only had time for one short session. First impression was definitely better than with 30. But I definitely need to do more testing...

**Comment by smichel17** [comment]
My suspicion is that for the building levels, less history is the right direction. For the building type, I think something like 6/50/3 might be the way to go. I'll try it next time I get the chance.

**Comment by smichel17** [comment]
I haven't found a neighborhood with varied-enough heights to test out different values yet.

<details><summary>However, I found an area with a good variety of building types and tested it with a different values, and it worked amazingly well.</summary>
.
"Which values?", you ask. Goo d question. I'm not sure. I updated them and installed the debug version on my phone over a month ago, and I no longer remember. Then I moved, and the desktop with the corresponding code isn't fully set up yet. Once it is, I'll send a PR updating the values.
</details>

**Comment by Helium314** [comment]
I was quite happy with reducting `historyCount` to 15. When inadvertently switching back to 30 (forgot to keep the change when doing new build) the annoyance was back.
Still haven't tried a different `first` value, but it really didn't feel necessary.
