### ISSUE TITLE
Show geometry for cycle lane quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3594]
When answering the cycleway quest, there is an "displayed separately" answer. However, cycleways and footways are displayed in the same style. Thus it could happen that the user chooses "displayed separately", but the separate way actually is not tagged as a cycleway.

Since SC now can display surrounding features, it might be a good idea to show nearby paths where bicycles are allowed.

(same could be done for the sidewalk quest)

**Comment by matkoniecz** [comment]
The main problem is that cycleway along road can be quite far away, which runs into limited radius, which will not be increased for performance reasons (#3549).

Though maximum that I found in my city was about 14m and that was enough to fit tram tracks between road and cycleway - https://www.openstreetmap.org/way/291583155 .

But on the other hand display in some cases manages to be confusing.

https://www.openstreetmap.org/#map=19/50.07571/19.88917 - blue - cycleway

in app (with modified quest selection making all road eligible for cycleway quest - for testing)

note that East cycleway is not marked

![screen04](https://user-images.githubusercontent.com/899988/146603163-4f53bd6c-6257-48f2-85b0-9682001e86fd.png)

(also https://www.openstreetmap.org/way/226525327 is somehow not selected by filter, but I have not investigated this)

note that here upper cycleways visible on screen are not marked - is it going to be confusing? Probably yes.

![screen05](https://user-images.githubusercontent.com/899988/146603277-036135a1-e44a-4972-be15-8cf0e8015352.png)

https://www.openstreetmap.org/#map=19/50.07250/19.88838 works better, though it also shows ground path with legal cycling

![screen06](https://user-images.githubusercontent.com/899988/146603426-e56334bd-5a7c-4e70-ab23-49c741e1785d.png)

https://www.openstreetmap.org/#map=19/50.05898/19.92217

![screen07](https://user-images.githubusercontent.com/899988/146603606-71064280-c841-4219-b3a7-2598540d9b19.png)


---------------

I was testing

```
    override fun getHighlightedElements(element: Element, getMapData: () -> MapDataWithGeometry) =
        getMapData().filter("ways with " +
            "highway = cycleway or " +
            "(highway ~ path|footway and bicycle ~ yes|designated) or " +
            "(highway=construction and construction ~ cycleway)")
```

and I am considering WONTFIXing this or increasing range for getHighlightedElements in all cases or specifically in this quest. But increasing it to to just 40m means that it queries 178% of previous area...

**Comment by Helium314** [comment]
Thanks!
I will test your `getHighlightedElements`, and added a setting for conveniently changing `highlightedElementsRadius`

But it looks like for properly showing nearby ways, the nearby element highlighting would need to be changed. Currently it is done only around the center, which is bad in case of long ways.

**Comment by Helium314** [comment]
Using higher `highlightedElementsRadius` works surprisingly well. Even with 100 m it takes my ancient S4 mini less than a second to show nearby cycleways.
But it would be necessary to display nearby cycleways along the whole way (instead of just near the center), which can give enourmous bounding boxes for long roads... so if we don't find an efficient way for querying only close to the road, this is probably `wontfix`.

As for confusingly non-highlighted cycleways: this frequently happens near bridges, or if the layer tag of cycleway and road is different for some other reason. But I wouldn't find it confusing in most situations...

**Comment by matkoniecz** [comment]
I also thought about it and invented nothing useful so I will wontfix it, without prejudice to implementing it if someone has good idea that would be performant, with reasonable code.

But I would not recommend it as a focus.

A pity, idea was promising.

**Comment by Helium314** [comment]
The most promising thing I found would be using [spatialite](https://www.gaia-gis.it/fossil/libspatialite/home), which should be able to return points inside a polygon. But that's a bit too much just for adding such nice-but-not-necessary functionality.

**Comment by smichel17** [comment]
Another option would be pre-processing/indexing, like how we generate quests on download. It does still have a battery cost, though.

**Comment by Helium314** [comment]
Could this be implemented now that the cache allows for much faster `getMapDataWithGeometry`?
