### ISSUE TITLE
Capitalisation for place names

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3595]
I often have to manually change place names for proper capitalisation.
Following #3495 and #3523 I think it might make sense to request word capitalisation for place names as well.

Currently `AutoCorrectAbbreviationsEditText` is the thing to change, and it uses sentence capitalisation. Switching to word capitalisation would also affect other things like road names... not sure if this is a good thing

**Comment by westnordost** [comment]
word capitalization would also make sense for road names, so it sounds like a good idea

**Comment by Helium314** [comment]
Hmm, I just had a look at some random places, and I think thar word capitalization for road names is rather bad: in Germany it's not that much of a problem (only some names like "An der Hochschule" need to be corrected). But in Slovenia, streets have names like "Poljanska cesta", or "Kristanova ulica", i.e. the "gasse" part you know from German is a separate word that should not be capitalised.

**Comment by westnordost** [comment]
Ok. Then the same thing may be true for place names, no?

**Comment by matkoniecz** [comment]
In cases where we have New York City, [Central City](https://www.openstreetmap.org/relation/194875#map=16/44.3683/-103.7627&layers=N) or [Spišská Stará Ves](https://www.openstreetmap.org/node/26036678) (Ves -> Village) then it is also capitalized.

And, as far as I know, no region duplicates `place` value into `name` (and such names are often staying despite settlement status changes or being advertising - Central City is a village, Spišská Stará Ves is a town)

**Comment by ZeLonewolf** [comment]
Is the list of exceptions small enough that they can be simply white-listed in some way?  Punctuation cases can be handled by rule, while cases that start with [a-z] should be exceptionally rare.

**Comment by mnalis** [comment]
In Croatia too capitalizing each word of road name would be a bad idea; majority of road names have lower-case words like "ulica" / "cesta" / "put"  / "odvojak" (meaning street / road / way / ...)

For place names, it is much better, I guess (with quick browse of http://overpass-turbo.eu/s/1egN) about 95% or more would have all words in caps.

**Comment by timothywashere** [comment]
Bus stop names too if you have the time, They're always Capitalised Each Word In The UK .

**Comment by Helium314** [comment]
Looks like for bus stop names it's the same as road names: capitalised in some countries, but definitely not everywhere.
How to solve?
* simply changing to word capitalisation will be horrible in some countries, so can't do that
* user choice using a setting would be possible, but having a setting for such a "detail" doesn't fit SC style
* setting capitalisation by country should be possible. I can imagine this being confusing to some people though

Place names:
I think I caused some confusion here. With place name I meant where [`AddPlaceName`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt) quest is asked ("What is the name of this place?"), and not elements with the `place` tag.

**Comment by westnordost** [comment]
I think this is a will not fix then. The complexity to add this small convenience is just too high.
