### ISSUE TITLE
Swipe between achievement notifications

### ISSUE THREAD

**Issue by boothym** [streetcomplete/StreetComplete#3596]
Made some edits recently and once the upload finished, the bell icon showed I had five notifications. 

I opened the first notification, read it, then pressed ok (or whatever the button is, I can't remember) to dismiss it. I then had to do the same thing another four times to get rid of the other notifications.

There should be a way to swipe or move between the remaining notifications once you've opened the first one to save you having to go in and out of each one.

**Comment by westnordost** [comment]
Hmm, I understand. However, such a minor inconvenience is not worth the time and effort to implement.

**Comment by smichel17** [comment]
Seems like you are not opposed to some feature like this existing, just to spending the effort, so I'll switch the label from `wontfix` to `needs PR`.

**Comment by westnordost** [comment]
Not really. Implementing this also requires to change how the notification-system works, probably making it more complex. Even if once finished, this needs to be maintained. So yes, this is a will not fix.
