### ISSUE TITLE
Show surrounding elements in highway construction quests

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#3598]
**Use case**
The highway construction quest is asked for objects wich are not shown in the map. That makes orientation difficult if there are multiple things under construction.
![multiple construction quests](https://user-images.githubusercontent.com/42044179/146608616-4b80e7f9-1369-4c04-ad6d-e2cfaf379946.png)![construction quest](https://user-images.githubusercontent.com/42044179/146608641-280d44f0-0107-42b5-95c2-9a794a4da44c.png)
(images above show (i. e. don't show) a roundabout with adjacent roads and a nearby footway under construction)

**Proposed Solution**
It would be nice to see nearby features under construction when opening a construction quest.

The usual radius to search for objects should be sufficient, so we don't run into problems like with #3594. The main point is to see if a piece of way is in front of a junction or behind it, as construction phases often range from one junction to another. When there is no junction nearby, there's probably everything still under construction or everything is finished.

I think both, paths and roads, should be shown at the same time. But they should be distinguishable. Maybe give roads a different colour than paths, and/or draw them heavier.
![mockup](https://user-images.githubusercontent.com/42044179/146612478-8affb143-6b00-44e4-be69-f5fcd5e95f94.jpg)

**Comment by matkoniecz** [comment]
> I think both, paths and roads, should be shown at the same time. But they should be distinguishable. Maybe give roads a different colour than paths, and/or draw them heavier.

Not really possible or easy to implement as far as I know

**Comment by matkoniecz** [comment]
Have you solved quests in this area? If not - can you link it for testing?

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/3594#issuecomment-997159297

> But it looks like for properly showing nearby ways, the nearby element highlighting would need to be changed. Currently it is done only around the center, which is bad in case of long ways.

And I suspect that performance hit of opening very long `highway=construction` would be problematic if it would be queried along its entire way.

**Comment by westnordost** [comment]
Yes, it would. One reason why footways/cycleways are not highlighted when answering the sidewalk/cycleway quest. On the other hand, there are not that many "highway construction quests" plus under-construction ways are not shown on the map already. 

DerDings - if there is a whole new neighbourhood being constructed, I'd expect all of the roads there to be finished at the same time, or as you say from junction to junction. You know your GPs position on the map, so IMO there is little reason to know how the in-construction ways are located to each other. It is more important to see how the ways are located to you. I.e. I claim that if you are on-site, you should have no problem to identify which roads are in construction and which are done.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/3594#issuecomment-997397937 - there is no good idea for performant querying everything along ways.

And `highway=construction` can be really long.
