### ISSUE TITLE
Show geometry for crossing quests

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3599]
I noticed that sometimes people confuse crossings with other nearby crossings.
See https://www.openstreetmap.org/node/8615277295 and https://www.openstreetmap.org/node/6557473402 which both have an incorrect `crossing:island=yes`, likely because there actually is a island at a different nearby crossing.

Showing geometry should help people with identifying the correct crossing.

(I was originally going to suggest not asking for crossings that are not part of a road, but showing geometry should help as well, and in more cases)

**Comment by westnordost** [comment]
Geometry of what?

**Comment by Helium314** [comment]
Right, that was quite ambiguous...
Showing nearby crossings was the idea. Probably nodes with highway=crossing (if not excluded by some other filter, like the exclusion of driveways). I thought about ways with footway/cycleway=crossing, but showing them might be bad because this is not tagged at many crossings.
