### ISSUE TITLE
House Type quest: also allow caching "residential" and other more generic types

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3600]
**Use case**

User wants to solve important `house address` quests, but is blocked by first having to solve less important `building type` quest (see https://github.com/streetcomplete/StreetComplete/issues/2464 for background).

However, precise solving of `building type` quest can be time consuming (eg. is it `house` / `detached` / `semi-detached` / `apartments` / `...` - see https://github.com/streetcomplete/StreetComplete/discussions/3558#discussioncomment-1745167). Some users are also quite allergic to giving _potentially wrong answers_ (myself included). Thus, such user would choose easy way out and select easier, more generic answer like `residential` (or `commercial` etc). This works, and user can then happily proceed to solve `house address` quests (which is the thing that s/he wanted to do in the first place).  

However, when such more generic answer as `residential` is selected, the **result is not cached in recent answers** (as it is for more precise answers like `detached`), so for each next building user again has to repeat more complex multi-step-process of selecting `residential`, instead of just selecting it from the recents list. This gets annoying very fast, which is unwanted, and a heavy price to pay for such a small difference between marking building as `residential` vs. `semi-detached`.

**Proposed Solution**
Allow `residential` and other more-generic building types to also be cached. Thus, users who use it would not get penalized. @smichel17 [volunteered](https://github.com/streetcomplete/StreetComplete/discussions/3558#discussioncomment-1745379) to do it, if that would be accepted.

(Alternatively, problem could be avoided by allowing users that manually turn off `building type` quest to solve `house address` quests;  but that has already been discussed at https://github.com/streetcomplete/StreetComplete/issues/2464)

**Comment by westnordost** [comment]
Hm, I guess that'd be okay. Though, there still needs to be the warning that if possible you should select a more specific value **every time** one selects that generic value.

Also, if this is about the housenumber quest, soon(ish) there will be a special view with which you can contribute housenumbers more efficiently.

**Comment by smichel17** [comment]
@mnalis Do you want to wait until the new house number view is available and see if that alleviates your concerns? Or would you still want this, regardless?

**Comment by mnalis** [comment]
@smichel17  Yes, this would still be useful whenever solving `building type` quest.

The new address quest view, if successful, would only allow me to **_choose when_** to solve `building type` quest (e.g. solve it only when I am bored / in area which is mostly solved otherwise; and skip it when I'm in _"only have time for really useful stuff"_ mode).

**Comment by smichel17** [comment]
Well, I must admit, that did not work the way I expected :laughing:

The simple fix does indeed make 'Residential' appear in the recent items… but still as an expandable category!

<img src="https://user-images.githubusercontent.com/6563664/147172834-e405f708-fac9-4cb2-b900-df8c383f3392.png" width="350" /> <img src="https://user-images.githubusercontent.com/6563664/147172876-5325f6d0-89ef-4e77-8634-6ae5b335a14a.png" width="350" /> <img src="https://user-images.githubusercontent.com/6563664/147172878-8744ddab-09a3-4de1-9c3f-3d8140039395.png" width="350" />

I could try to fix this. However, that would involve mucking with the layout. At that point, I wonder if it would be a better use of time to just implement https://github.com/streetcomplete/StreetComplete/issues/3387. @mnalis If https://github.com/streetcomplete/StreetComplete/issues/3387 were implemented, would this feature still be (as) useful?

**Comment by westnordost** [comment]
I also gave it a shot. To solve that the residential building is shown as a category in the top items, I added `.map { Item2(it.value, it.image, it.title, it.description) }` to `getInitialItems()` in order to remove the sub-items from that item so that it is not displayed as a group. This however means that StreetComplete of course no longer recognizes this as a group and thus does not display the "warning that if possible you should select a more specific value".

So, given that the other ticket mentioned was already implemented, I do no think it is worth investing (more) time and complexity into somehow marking items as a "category but not really a category right here".

**Comment by mnalis** [comment]
Interesting, that would work for me just fine (but not globally for everyone, of course), but I'm unable to find right place to put that `.map { Item2(it.value, it.image, it.title, it.description) }` inside `getInitialItems()`... :cry: 
Do you still have a branch you worked on, or could give a hint?

**Comment by westnordost** [comment]
No, don't have a branch. After `mostCommonWithin`.
