### ISSUE TITLE
[Quest enhancement] when asking if surveillance cam still exist, show image of type

### ISSUE THREAD

**Issue by lightonflux** [streetcomplete/StreetComplete#3607]
When doing the maintainance quest were you check if surveillance cams still exist it would be helpful if one knew which type of cam one is looking for. Because sometimes they are hard to spot and could be errounously be deleted.

So knowing which type tolook for maybe even with an example image would be a great help.

**Comment by westnordost** [comment]
This is not really possible with the current quest. The only thing the quest can do is to tell the name of what it is and display nearby other surveillance cams. If the iD tagging scheme had different presets for different types of cameras ("panning surveillance camera", "dome surveillance camera", ...) , it would display the different names. But I doubt that would make sense.
