### ISSUE TITLE
Bug display

### ISSUE THREAD

**Issue by zelandonii** [streetcomplete/StreetComplete#3611]
Hi,

There is a lack of translation in French in the attached screenshot. We must replace the word "cet" with "ce".

Cordially.
![Screenshot_20211230-194256_Street�Complete](https://user-images.githubusercontent.com/78958071/147782775-ac1a7a28-0f7f-4f15-9d46-32e86247e6e0.png)

**Comment by smichel17** [comment]
Hi and thank you for the report. If you are willing, you can fix this yourself by updating the translation in POEditor.
Details here: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by zelandonii** [comment]
Hi and thanks for your message,
I have corrected the translation in POEditor. Is there anything else to do to make it effective?

**Comment by matkoniecz** [comment]
Thanks for a fix!

> Is there anything else to do to make it effective?

No, just wait for an update. Release includes pulling in changes and merging them with code.
