### ISSUE TITLE
Railway electrification system

### ISSUE THREAD

**Issue by dlichtistw** [streetcomplete/StreetComplete#3612]
### General

Affected tag(s) to be modified/added: [electrified=*](https://wiki.openstreetmap.org/wiki/Key:electrified)
Question asked: **Is this railway section electrified?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
Usefulness depends on the use case, but it is definitely established.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
If there is some kind of electrification, it can be tagged. If it is not electrified, then `electrified=no` applies.
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
Overhead contact lines (`electrified=contact_line`) should be very easy to spot for everyone, 3rd rail (`electrified=rail`), 4th rail systems (`electrified=4th_rail`) and APS systems (`electrified=ground-level_power_supply`) may need a closer look, but should be distinguishible with the help of images.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
For my country, the ratio of electrified track kilometers is about 0.5. For other countries, this number may be higher or lower.
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)
The number of railway elements is not as large as for highways, but (at least for most of Europe) still considerable. Based on a short overpass query (see below), there are probably in the order of 10<sup>5</sup> fixable railway elements in Germany.

### Ideas for implementation

**Element selection:**
Pretty much every railway track in active use should have an `electrified=*` tag.
Funiculars should be excluded, maybe monorails too.

Something along the line of the following overpass query:
```
(
  way["railway"="rail"]({{bbox}});
  way["railway"="light_rail"]({{bbox}});
  way["railway"="tram"]({{bbox}});
  way["railway"="subway"]({{bbox}});
  way["railway"="narrow_gauge"]({{bbox}});
  way["railway"="preserved"]({{bbox}});
)->.tracks;
way.tracks[!"electrified"];
```

It does also apply to a small portion of `highway=*` elements. But it may be hard to find a good subset, where this quest would be reasonable.

**Metadata needed:**
No metadata necessary.

**Proposed UI:**
Choice illustrated by images:
 * not electrified (`electrified=no`)
 * contact line (`electrified=contact_line`)
 * third rail (`electrified=rail`)
 * fourth rail (`electrified=4th_rail`)
 * ground level (`electrified=ground_level_power_supply`)

There is no option for `electrified=yes`. Instead, (I think) users should leave a note if the electrification system is not one of the above. (This is probably very rare.)

There should be the option to split the way if the electrification system changes.

I am not sure whether photos can be suitable, or schematic illustrations would be clearer.

**Comment by matkoniecz** [comment]
`railway=tram` seems basically always `electrified=contact_line` in my experience with really rare exceptions.

In Poland at least it would be locally spammy (the same answer over and over again) but this data would be actually useful as electrification distinguishes minor/dead/abandoned lines from more important.

**Comment by matkoniecz** [comment]
Is geound-level power supply basically third rail placed lower?

**Comment by dlichtistw** [comment]
> Is ground-level power supply basically third rail placed lower?

Similar, but not entirely the same:
- [Third rails](https://en.wikipedia.org/wiki/Third_rail) are usually located on the side of the main rails. They use the main rails or a fourth rail as ground conductor. These systems are usually not suitable for public spaces since the conducting surfaces are hardly protected.
- [Ground level power supply](https://en.wikipedia.org/wiki/Ground-level_power_supply) systems usually have both conductors running parallel between the main rails. They are flush with the ground, and only activate when entirely covered by a compatible vehicle to be safe in public spaces.

I quickly hacked together a basic draft for the new quest and created #3614 for it. It is still missing icons and graphics. (Be aware that this is my first time with Kotlin and I have hardly any idea, what I am doing...)

**Comment by westnordost** [comment]
Hmm, I don't think StreetComplete is appropriate tool to record this information. I am sorry that you already put effort in an initial implementation but I don't see any way this can be part of this app. Emojis from quest guidelines sprinkled for overview:
1. 👨‍💻/🐿️ I imagine that laypersons will have issues with identifying the type of electrification system, even with pictures. There is certainly other infrastructure stuff running along rail tracks, people will mistake these
2. 💤 The electrification system will be the same for one track or actually for the whole (metro) system in one city at least. So, no, the answer will be the same 99% of the time in the same place. 
3. 🕵️ Train and metro tracks are certainly not well accessible from outside of being in that train and outside of train/metro stations. So, the map will be full of unsolvable because unreachable quests, not only in tunnels, on rail yards etc.
4. 💵 Information on kind of electrification system can - with StreetComplete - only ever be recorded mostly randomly at train/metro stations and stops. This kind of patchy data is not very useful. The better, more effective and more efficient alternative is to look into wikipedia or look at some photos of metro stops, select all the tracks of that metro line and tag it all at once with JOSM. Of, if it should be more user-friendly and quest-like, then it would make more sense to add this as a layer to MapComplete 
5. 🤷 Finally, I very much doubt the usefulness of this information. I can't make up a use case that would make this data relevant to end users and even ... whatever ... train car manufactors will certainly not look onto patchy OpenStreetMap data to determine which kind of electrification system their customer is using but just look it up somewhere else. The best I can think of is some kind of visualization layer that shows things like the different voltages and the different systems used in international comparison.

**Comment by westnordost** [comment]
> I quickly hacked together a basic draft for the new quest and created #3614 for it. It is still missing icons and graphics. (Be aware that this is my first time with Kotlin and I have hardly any idea, what I am doing...)

On the technical side though, the PR looks very good, I'd only have some very minor things to complain about. But alas, sorry about having wasted your time. I should have replied here earlier. Generally, quest suggestions that are "OK"ed get the "new quest" label after discussion (if any is necessary).

**Comment by dlichtistw** [comment]
> The electrification system will be the same for one track or actually for the whole (metro) system in one city at least. So, no, the answer will be the same 99% of the time in the same place.

It seems that this quest would mainly be relevant in yards. On of the reasons may be that the general network electrification information is not dependable there. Aerial imagery is usually not suitable to reliably recognise contact lines or contact rails. And especially subway networks may use different systems for different sections of the same line.

> Train and metro tracks are certainly not well accessible from outside of being in that train and outside of train/metro stations. So, the map will be full of unsolvable because unreachable quests, not only in tunnels, on rail yards etc.

As long as there is some regular passenger service on a line, I would not consider a railway track inaccessible. In fact, for me who does not own a car, it would be more accessible than most freeways. And yards and industrial lines, which seem to have the most gaps, are usually quite well accessible by road.

> Finally, I very much doubt the usefulness of this information.

I would refer to [OpenRailwayMap](https://openrailwaymap.org/) for end users of that data and use cases. Just filling in the gaps there would already be good. (And in certain aspects, OSM is not that far off in terms of quality and coverage of what I sometimes get to see in the railway business.)

> But alas, sorry about having wasted your time.

No worry. Seeing a new language is definitely not a waste of time. I may even just use my own build, because I definitely see some utility in this and other potential railway related quests. I would really prefer staying on the regular release, though.

**Comment by matkoniecz** [comment]
> I can't make up a use case that would make this data relevant to end users 

I have seen many railway maps showing this info.

It can be useful for deciding importance of railway when having general purpose rendering and showing it later or earlier depending on it (even if styling itself would be the same).

I have seen several games using OSM data as input, including transport games (this is theoretical use though I consider it likely)

**Comment by matkoniecz** [comment]
> This kind of patchy data is not very useful.

Sometimes aerial images are hard to interpret and sources you mention are often outdated. In such cases fragmentary data can be useful to verify other data sources and help to interprete them.

> So, no, the answer will be the same 99% of the time in the same place.

That was my main worst.

**Comment by smichel17** [comment]
> I may even just use my own build

Note that you would not be the only person doing this— at least @matkoniecz, @Helium314, @mnalis all run their own forks (in order from most to least customized). https://github.com/streetcomplete/StreetComplete/discussions/3003 might be interesting/relevant here.

**Comment by peternewman** [comment]
>> 2. 💤 The electrification system will be the same for one track or actually for the whole (metro) system in one city at least. So, no, the answer will be the same 99% of the time in the same place.
> That was my main worry.

Maybe this is just the hotch-potch nature of London, but we've certainly got multiple different types of electrification at the same station, and I think some lines change part way along from my understanding (or at least used to).

Although I appreciate it will be far more repetitive than say the number of road lanes in the same area.

**Comment by matkoniecz** [comment]
Closing as  #3614 was rejected.

**Comment by westnordost** [comment]
It is not uncommon. Metro systems and suburban transit systems are often incompatible with each other (different spur width, voltage, electrification system) and it is common that at one stations, metro systems and suburban transit systems meet. Some cities even have several metro systems that are incompatible with each other, e.g. Bangkok: [Metropolitan Rapit Transit
](https://en.wikipedia.org/wiki/MRT_(Bangkok)), [Airport Rail Link](https://en.wikipedia.org/wiki/Airport_Rail_Link_(Bangkok)) and [Bangkok Mass Transit System](https://en.wikipedia.org/wiki/BTS_Skytrain) along with regular (suburban) maybe electrified train tracks. Doesn't make invalid my point though.
