### ISSUE TITLE
"What can be left here for recycling?" quest clarification

### ISSUE THREAD

**Issue by pl71** [streetcomplete/StreetComplete#3615]
When we have 2 or more amenity=recycling close together, it is not clear which container is referred to. 
Suppose it is valid for other amenities of the same type which are very close to each other.
It could be solved by providing additional info from the existing tags, or increased zoom level.

**How to Reproduce**
Start this quest when 2 or more recycling containers are close together (several meters apart),

**Versions affected**
Android 9
StreetComplete 38.2

**Comment by matkoniecz** [comment]
>  Start this quest when 2 or more recycling containers are close together (several meters apart),

Can you provide location where it happens? Or is it a theoretical concern?

This quest excludes such poorly mapped places where single `amenity=recycling` object is not used.

**Comment by pl71** [comment]
https://www.openstreetmap.org/node/4922800657

**Comment by peternewman** [comment]
> This quest excludes such poorly mapped places where single `amenity=recycling` object is not used.

Have they not been allowed now the display of nearby elements happens? I thought that was one of the things it would enable?

**Comment by HolgerJeromin** [comment]
> When we have 2 or more amenity=recycling close together, it is not clear which container is referred to.

I found this today, which is very fine:

![rps20220102_214006_474](https://user-images.githubusercontent.com/2410353/147888921-14cfc3fb-7243-4f7d-a7b3-5fce5153de55.jpg)

**Comment by matkoniecz** [comment]
> Have they not been allowed now the display of nearby elements happens? I thought that was one of the things it would enable?

Yes, my claim was outdated - I remembered old code version. Sorry.

**Comment by westnordost** [comment]
So, this is a solved issue. If there is a nearby other container mapped, users will see this within the app.
