### ISSUE TITLE
missing option in quest "what kind of bicycle barrier"

### ISSUE THREAD

**Issue by fionnb** [streetcomplete/StreetComplete#3619]
The above mentioned quest is missing a choice (and picture) for a simple single barrier.
The attached picture has been taken by me and may serve as an example.
It may also be included as you see fit in future versions of StreetComplete.

**How to Reproduce**
Open Quest, see Options

**Versions affected**
Every version since the barrier quest was introduced
![20220106_164048](https://user-images.githubusercontent.com/4482889/148416175-6df39f18-8dd8-43d6-8605-097a92a2e5cb.jpg)

**Comment by matkoniecz** [comment]
The problem is that I would have no good idea how to tag it as a human.

Which tags are fitting here?

See https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier https://wiki.openstreetmap.org/wiki/Key:barrier

**Comment by matkoniecz** [comment]
For now I would recommend leaving notes with a photo on encountering cases like this.

**Comment by westnordost** [comment]
It's **functionally** the same as `cycle_barrier=single` I'd say, and that is what counts. I would tag it as that, but see @matkoniecz , you could also leave a note

**Comment by westnordost** [comment]
Maybe the picture you took could be added to the wiki (once it has been decided whta it should be tagged as). Could you upload this photo to the openstreetmap wiki and/or state that you license it under a CC-license such as CC-BY 4.0, CC-BY-SA 4.0 or CC-0 ?

**Comment by matkoniecz** [comment]
You can also upload to https://commons.wikimedia.org/ if you want (and will be available at OSM Wiki)
