### ISSUE TITLE
osmose bugs

### ISSUE THREAD

**Issue by u6aab** [streetcomplete/StreetComplete#3620]
**Use case**
i go mapping with streetcomplete and vespucci, and there are a lot of missing fire hydrant and postbox bugs from osmose on vespucci, which require closing and manually adding in a fire hydrant or postbox.

**Proposed Solution**
adding an "is there a fire hydrant here" quest which would add a fire hydrant and close the issue if answered yes, and label the issue as a false positive if answered no would be nice. same with postboxes.

**Comment by peternewman** [comment]
See #3418 this is likely to be a wontfix I think.

Also please can you use the new quest template.

You can copy it from here:
https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/.github/ISSUE_TEMPLATE/quest-suggestion.md

Also more generally what's the quality of the source data like? The random postbox I looked at appears to be mapped on the wrong side of the data from the source data (or there's an offset):
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.768542&lon=1.669216&item=7051%2C8025&level=1%2C2%2C3&tags=
https://www.google.com/maps/@50.7680013,1.6689206,3a,75y,330.54h,77.67t/data=!3m6!1e1!3m4!1sDNHLcTCVggNCXQ04dh3Ecg!2e0!7i16384!8i8192

So you'd want to move the nodes around too, not just create them.

They do have lots of quests for France at least, so there might be some possibly efficiency in a common quest using their API if suitable.

**Comment by u6aab** [comment]
looking at the locations again, i understand, and i look forward to whatever feature was mentioned in the issue you linked. thanks for the great app.
