### ISSUE TITLE
Bridge-related quests show up when there's no bridge nearby

### ISSUE THREAD

**Issue by arch0345** [streetcomplete/StreetComplete#3625]
I noticed 2 notes  [here](https://www.openstreetmap.org/note/2991060) and [here](https://www.openstreetmap.org/note/2917704) where SC users are getting bridge-related quests when there's no bridge nearby. I'm not sure how to reproduce this issue as I haven't encountered this myself.

**Versions affected**
37.0-38.2

**Comment by matkoniecz** [comment]
there are bridges over ways shown there

https://www.openstreetmap.org/?mlat=45.51369&mlon=-122.66737#map=19/45.51369/-122.66737
https://www.openstreetmap.org/?mlat=45.52657&mlon=-122.79767#map=18/45.52657/-122.79767

while showing quest icon exactly at bridge location would be nicer - that would be a separate issue and without any clear solution how to achieve this

**Comment by Helium314** [comment]
It should be possible to show nodes that trigger this quest using `getHighlightedElements`, but this would require getting elements along the entire road, not just near the center as it is done now.
It might be possible using [R-tree custom queries](https://sqlite.org/rtree.html#custom_r_tree_queries) if #3609 actually proves useful enough to be implemented.
