### ISSUE TITLE
Quest icon (glitch) is shown near on the map when a quest is selected

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#3627]
**How to Reproduce**

 I just opened some quests, maybe also the quest type matters? (if so: hydrant quest), and it showed me the quest icon near that quest bubble again.
 (I almost thought this was intentional, but I have no idea what the intention/use case could be behind that.)

When I "closed" (i.e. dismissed the question asked/bottom panel), it hided the icon again. This was reproducible at the time I experienced this, but I cannot reproduce it right now anymore. (Maybe a visual glitch depending on the map internals/display mode)

![grafik](https://user-images.githubusercontent.com/11966684/148690622-4c018da7-db20-48fa-948f-ee75625cec8a.png)

**Versions affected**

StreetComplete v38.2 from F-Droid

Pixel 4
Android 11 / CalyxOS 2.11.0
Build RQ3A.211001.001.202112110

**Comment by FloEdelmann** [comment]
This is a deliberate feature; please see the PR #3480 and the referenced issues.

How could the UX of this feature be improved in your opinion?

**Comment by mnalis** [comment]
To admit, I was also little confused when confirming kindergarden node opening hours, and nearby shop building north of it lit up. (As the shop was a polygon and not a node, it didn't show the quest icon, so that confused me a little):

![small_Screenshot_20220109_180212_de westnordost streetcomplete mn debug](https://user-images.githubusercontent.com/156656/148692624-cf5ea773-d664-4887-a1ef-ac1b97316d53.jpg)

Perhaps when polygons are lit up, a quest icon could be drawn in the middle of them (if that is not too much work). It might help with that variant... About the original issue (both are quest icons on nodes), I'm not sure how it could be improved. I've added the question to the [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#When_I_click_on_quest.2C_several_similar_icons_pop_up.2C_why.3F) at least.

**Comment by rugk** [comment]
> How could the UX of this feature be improved in your opinion?

Ahhh, I see. Yeah, for opening hours I saw the orange highlight that is alos visible in the screenshot of @mnalis both as a dot with name and 
That was fine for me and I actually found it quite useful to choose the correct shop and not miss it or so.

That is however way less "intrusive" than the quest marker for the "hydrant quest" which looks as if it appears at a totally random position. 
I guess the problem that makes it look like a glitch is that the "pointer"/"speech bubble"/marker thing is actually missing, so I do not even know exactly _where_ the next quest of that thing is, which makes it a little unhelpful.

I'd tend to better have the same orange dot you have for opening hours then, and maybe on "hover", i.e. on mobiles basically when tapping there, you could show what kind of quest it is.
After all, if that always shows the same quest type only, then it is not really necessary to "explain" again what quest is shown there.

> Perhaps when polygons are lit up, a quest icon could be drawn in the middle of them (if that is not too much work). 

Alternatively… or additionally, they could be desaturated/transparent or so to make them less apparent, though that could still look like a gliztch.

**Comment by matkoniecz** [comment]
> you could show what kind of quest it is.

It is not a quest. It is showing when other nearby objects of the same type are present.

**Comment by mnalis** [comment]
@matkoniecz ah, but is it then not result of the same code in @rugk's and my picture? I assumed I was shown that purple shop, because it was eligible for the same _quest_ - I would not consider that `shop=convenience` and `amenity=kindergarten` are "objects of the same type" (for fire hydrants they are, of course)? Or am I misunderstanding something?

**Comment by rugk** [comment]
> It is not a quest. It is showing when other nearby objects of the same type are present.

Okay, but wyh does it show the quest icon then? Sorry, but thatr is even more confusing… :see_no_evil:

**Comment by riQQ** [comment]
Would it help to use a square, a triangle or another shape to differentiate between the quest object and the other nearby objects?

**Comment by rugk** [comment]
…or just a b/w  or greyish version or so.

Still find all that not really a good solution.

So the UX challenge boilds down to: How can we communicate a POI position of related POIs for a quest, that are itself not (_necessarily_) quests itself _and_ make it clear these are no quests, but also no random map glitches…

The current solutions are:
* A quest icon without bubble -> as said, IMHO too similar to a real quest and looks like a glitch, one cannot see it's exact position.
* The orange highlighting -> IMHO this is fine, though it may be unclear for quests that what that should mean (I mean, what _are_ these highlights? For opening hours where the shop name is stated this is quite fine, but otherwise hmm…).

**Comment by rugk** [comment]
Okay, I do have an idea:

Actually the solution should be pretty simple, because we are talking about a map-style thing here, are not we?
So if we have a "real icon" in the size of how other maps display "usual" POIs that is not colored differently, and that is flat, very much smaller and not an "overlay" as the quest icons currently are. I imagine just a circle and a _small_ pictogram. (even maybe simpler than the current quest icons because you otherwise cannot distinguish them)
Technically, that may require being able to dynamically adjust the map style, however, does not it?

**Comment by smichel17** [comment]
It shows the icon so that you do not confuse the hydrant you are answering a quest about with a hydrant which is nearby, but already tagged (i.e. it would not produce a quest, so you'd have no idea that it existed).

On January 9, 2022 7:03:09 PM UTC, rugk ***@***.***> wrote:
>> It is not a quest. It is showing when other nearby objects of the same type are present.
>
>
>
>Okay, but wyh does it show the quest icon then? Sorry, but that is even more confusing… :see_no_evil: >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/streetcomplete/StreetComplete/issues/3627#issuecomment-1008355331
>
>You are receiving this because you are subscribed to this thread.
>
>
>
>Message ID: ***@***.***>
-- 
To respect your time, I try to write short, functional emails.

**Comment by matkoniecz** [comment]
> I imagine just a circle and a small pictogram

That would it even more similar to the quest icons which are in the circle

**Comment by westnordost** [comment]
And making it smaller will not help either, only people may miss it. The icon has this white edge so that it is clearly visible on the map. I don't see any way to improve it TBH

**Comment by mnalis** [comment]
perhaps making non-primary object more dull (reduce saturation in HSL) or more "ghosty" (increase lightness in HSL) might help? eg.

 ![sc_fire_hydrant_color_HSL_saturation](https://user-images.githubusercontent.com/156656/148808758-cc0ce35f-b494-4921-b334-791304d86dcd.png) ![sc_fire_hydrant_color_HSL_lightness](https://user-images.githubusercontent.com/156656/148808748-f707fe13-3b13-4af6-bc83-fd90ba5317c8.png)

or make them party transparent (Alpha channel)?

**Comment by matkoniecz** [comment]
Or maybe show at bottom "2 objects like this within 30m"?

Would also give hint that it is not quest target being shown and that range is limited.

**Comment by smichel17** [comment]
More brainstorming: could allow them to be tapped, which shows a toast "This is a nearby hydrant."

On January 10, 2022 7:45:04 PM UTC, Mateusz Konieczny ***@***.***> wrote:
>Or maybe show at bottom "2 objects like this within 30m"?
>
>Would also give hint that it is not quest target being shown and that range is limited.
>

-- 
To respect your time, I try to write short, functional emails.

**Comment by rugk** [comment]
> The icon has this white edge so that it is clearly visible on the map. I don't see any way to improve it TBH.

Sure, but that's not the problem here. It's rather better if it is less visible to some point… :upside_down_face: 

> And making it smaller will not help either, only people may miss it.

Well… that's kinda the point? You need to see it, but it should not distract and you should not get confused by it…

> That would it even more similar to the quest icons which are in the circle

Hmm no? I doubt so.

My main point is: flatten it, so it is a POI of a map, not a "quest marker" on top of it, which has a totally different perspective.

I quickly _sketched_ a draft here (It's a sketch, it's ugly, but just to demonstrate my point):
![grafik](https://user-images.githubusercontent.com/11966684/148833758-c4620069-b45b-42be-a6b4-3bbb2adac764.png)

Also possible without a circle:
![grafik](https://user-images.githubusercontent.com/11966684/148833788-85fcb856-e776-4609-8702-6963bb104a32.png)

This is of course maybe a little too extreme and subtle, but it makes it very clear this is no quest… :upside_down_face: 

All I proposed is how "usual" map apps display POIs [like OrganicMap](https://organicmaps.app/) with a little icon/circle:
![grafik](https://user-images.githubusercontent.com/11966684/148834146-3849b839-847f-4671-aebc-a4e6e1dcea06.png)

You could do the same… after all, technically, it also _is_ a POI, just one only shown in situations where that is most interesting.

**Comment by riQQ** [comment]
Another option: show a hint the first a quest with POIs nearby is shown.

**Comment by westnordost** [comment]
Such icons on organicmaps stay upright and are not glued on the map

**Comment by westnordost** [comment]
I tried making it slightly transparent, but this doesn't really change anything. I will close this.
