### ISSUE TITLE
Expand to become a full editor

### ISSUE THREAD

**Issue by jidanni** [streetcomplete/StreetComplete#3629]
Surely a little more work could be done, and then Street Complete could be a full-fledged editor.

**Comment by matkoniecz** [comment]
see README

also it would be far more than

> little more work

**Comment by Helium314** [comment]
There is #2461 which is a step towards a simple editor, but it will still be a while until this is implemented (if at all)

**Comment by FloEdelmann** [comment]
See also https://github.com/streetcomplete/StreetComplete/discussions/3003
