### ISSUE TITLE
Changing surface in new smoothness quest fails

### ISSUE THREAD

**Issue by SupaplexOSM** [streetcomplete/StreetComplete#3636]
I have noticed an error several times today when trying to change the surface of a path using the new smoothness quest. By clicking on "More answers" [de: "Weitere Antworten"] and then "Is other surface" [de: "Ist andere Oberfläche"], the app asks whether the displayed surface is correct. If clicking "No", the surface quest should appear again.

In my case, this only worked at the beginning of my mapping tour - maybee only the first time I tried it (I was mapping offline). In all following attempts, the smoothness quest appeared again instead of the surface quest.

**How to Reproduce**
This error only seems to appear under certain conditions, which I unfortunately cannot reproduce exactly at the moment. The following conditions may have something to do with it:

- I was mapping offline.
- I was splitting paths to distinguish different surfaces. Possibly the error only occurred afterwards.
- The error did not appear on the first attempt but later. When it appeared, however, it happened permanently and in all places where the smoothness quest was located.
- I was mainly mapping surfaces and smoothness on footways (dunno if this is relevant).

**Versions affected**
StreetComplete: v39.0-beta1 (Android 10)

**Comment by mnalis** [comment]
- Possibly related: https://github.com/streetcomplete/StreetComplete/issues/3290

I've also experienced that with smoothness quest too before

**Comment by westnordost** [comment]
fixed by  #3290
