### ISSUE TITLE
confusing smoothness for paths

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3639]
In a city park where only pedestrians are allowed following are quite confusing.

"Only passable on foot" can be plausibly confused with legal restriction limiting path to foot traffic.

"Properly usable only by off-road vehicles" appears to exclude walking, while foot traffic is actually included

Not sure how to improve it

![screen01](https://user-images.githubusercontent.com/899988/149388036-e0382371-4425-48c1-9191-ff5fb09b2f70.png)

**Comment by mcliquid** [comment]
That's what I was thinking. With a small trail which is maximum 50 cm wide fits actually only "impassable", since I could not drive here practically with the vehicle. Also alone because of the steepness there.
As a pedestrian it would be very comfortable.

Maybe a different question could be asked for "paths" in general, maybe more in the direction of bicycle.

**Comment by mnalis** [comment]
@mcliquid Hmmm, well, the quest asks  "What is the **surface** quality" though, so it does not talk about any other possible (vehicle or pedestrian) restrictions on it (eg. maxweight, maxheight, maxwidth, oneway, access=private, etc.)

But we already know that people do not always read the text on the screen, so it would be prudent to try to improve it.

> In a city park where only pedestrians are allowed following are quite confusing.

> - "Only passable on foot" can be plausibly confused with legal restriction limiting path to foot traffic.
 
@matkoniecz Maybe something along the lines of:
- "Not usable by any vehicles, only passable on foot"
- "(Terrain is) too rough for any vehicle - it is only passable on foot"

> - "Properly usable only by off-road vehicles" appears to exclude walking, while foot traffic is actually included

- "Properly usable only by off-road vehicles and pedestrians"
- "Usable only on foot and by off-road vehicles"
- "Too rough for all vehicles not rated as off-road capable"

**Comment by westnordost** [comment]
alright, I used a similar wording. Thanks!

**Comment by matkoniecz** [comment]
Is it necessary to change translations? This seems change big enough to not use just fuzziness for that. (especially with that fuzziness accident in translations)

**Comment by westnordost** [comment]
I'd mark the translations as fuzzy, yes

**Comment by matkoniecz** [comment]
I thought about outright renaming string codes to force retranslation.

**Comment by westnordost** [comment]
I think it is fine because the meaning is still the same, just a refinement/clarification.
