### ISSUE TITLE
Changesets sometimes do not get closed, which can lead to excessive large bounding boxes

### ISSUE THREAD

**Issue by DHWinterWolf** [streetcomplete/StreetComplete#3640]
As per https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ it seems like the app is supposed to close a changeset after 20 minutes of inactivity, or in case case after one hour. Generally, this works fairly well, but sometimes this seems to fail. I've seen this on a few occasions where when out on a surveying session, that some quests don't get uploaded. It often seems to be the case that if logging on to OSM and checking your open changesets, no changeset is created for them.

Generally, when surveying around home, this isn't a major problem, but some recent travel between the UK and Chile has shown problems. An example would be https://www.openstreetmap.org/changeset/116101839 - you can see various ways here. I'll pick two as an example:

* https://www.openstreetmap.org/way/23300112 was modified on a walk in my local area, but for some reason StreetComplete didn't sync. This would have been some time mid-late December 2021.
* The next time I used StreetComplete was in Chile on 12 January 2022, and this included https://www.openstreetmap.org/way/269528037

Despite the changes being made more than three weeks apart, StreetComplete merged these into a single changeset, which led to a very valid comment by Lee Carré on https://www.openstreetmap.org/changeset/116101839 and the other changesets at the time about the bounding box for the changeset being much bigger than it should be.

I have StreetComplete set to automatically upload changes. I'd suggest a check on opening StreetComplete for non-uploaded changes, to see if existing changes from more than an hour ago are pending, and to at least start a new changeset then. There should have been an active data connection during both surveying sessions, but I can't be completely sure, so right now I'm not sure what causes the changesets not to be uploaded successfully. 

I was using StreetComplete 38.2 at the time, but have noticed that occasional deferral of changeset uploads for the last few versions. I'm afraid I don't have a record of exactly when it started, sorry. If I can provide any further information, please do let me know.

**Comment by riQQ** [comment]
See also 
- #1100
- #1940
- #2053
- #2988

**Comment by matkoniecz** [comment]
>  I've seen this on a few occasions where when out on a surveying session, that some quests don't get uploaded. 

Note that v39.0-beta1 (alter than affected StreetComplete 38.2) includes:

>  Fix rarely quest answers don't get uploaded automatically until next restart of app (#3494)

which may fix root problem of the issue

**Comment by DHWinterWolf** [comment]
I've just read through the description of issue #3494, and I think this is the root cause of what I've seen. Do you think I should close this issue as a duplicate, or leave it open as it described another possible check that might be worth implementing (though this would probably be a feature request rather than a bug, in that case)?

**Comment by DHWinterWolf** [comment]
> See also
> 
> * [close changeset if user moved significantly #1100](https://github.com/streetcomplete/StreetComplete/issues/1100)
> * [Quests counted in wrong country #1940](https://github.com/streetcomplete/StreetComplete/issues/1940)
> * [Split changesets to prevent huge areas #2053](https://github.com/streetcomplete/StreetComplete/issues/2053)
> * [Split changesets that would have large bounding boxes #2988](https://github.com/streetcomplete/StreetComplete/issues/2988)

I suspect these are all related to the same issue. I've just checked my country list, and was surprised to see Ghana there. However, since the bounding box on this change set is so large, it's entirely possible it's come out somewhere odd when averaging the whole bounding box.

**Comment by matkoniecz** [comment]
> I'd suggest a check on opening StreetComplete for non-uploaded changes, to see if existing changes from more than an hour ago are pending, and to at least start a new changeset then

This is basically supposed to happen already.

I propose to close this issue and reopen it in case of problem continuing in v39.0 or later.

Can you close it? This way you will be able to reopen it in the future.

**Comment by DHWinterWolf** [comment]
Sounds sensible, I'll close it now, thank you!

**Comment by Lee-Carre** [comment]
See also [changeset #116088511](//www.openstreetmap.org/changeset/116088511) which I suspect is another manifestation of this same bug. The mapper gives details of how he was using SC at the time.

**Comment by smichel17** [comment]
I don't have time to review all of the links from https://github.com/streetcomplete/StreetComplete/issues/3640#issuecomment-1013695355 right now, but please let me know if any of them are important or hard-to-find enough that they should be added to https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1058716
