### ISSUE TITLE
Allow renaming quest presets

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#3642]
**Use case**
I made several quest presets but I change the quests inside the presets sometimes. Therefore it would be practical to change the name of the whole preset.

**Proposed Solution**
Add a little pen icon next to the trash can to change the name.

**Comment by smichel17** [comment]
Related to / planned as part of https://github.com/streetcomplete/StreetComplete/issues/3228

**Comment by westnordost** [comment]
closing as duplicate

**Comment by mnalis** [comment]
`preset rename` is now implemented in [v49.0-beta1](https://github.com/streetcomplete/StreetComplete/discussions/4573) (see https://github.com/streetcomplete/StreetComplete/issues/3228#issuecomment-1294568667 and below)
