### ISSUE TITLE
Simplify building type quest

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3645]
**Use case**
Building type is a difficult quest to answer, even for experienced mappers.

**Proposed Solution**
I am creating this issue to track the discussion in https://github.com/streetcomplete/StreetComplete/discussions/3558, so that it does not get forgotten. Please discuss possible solutions there. Once we have a solution, we can move back here to track the implementation.

**Comment by matkoniecz** [comment]
Right now it is not really actionable, it is like "make app easier to use", "make app faster". It is always desirable and such unspecific issues to not really help.

It is also not mentioning specific sources of confusion or what tends to go wrong.

**Comment by westnordost** [comment]
I also didn't really find anything actionable in #3558, most of it seems to involve around `building:use`, to which I already replied earlier several times: If there is just `building=yes`, it is still an improvement in detail to add `building=residential` even if the actual building was once a train station (or the other way round). The correct `building:use` vs `building` values can always be added later. Mandating the user to make this distinction won't simplify anything, quite the contrary.

**Comment by smichel17** [comment]
Specific sources of confusion are mentioned in https://github.com/streetcomplete/StreetComplete/discussions/3558. I can copy them here if needed.

> it is still an improvement in detail to add `building=residential`

Kind of? It prevents using SC to add further detail later. But I think I also mentioned this already in the other issue, and I do not have the bandwidth to argue it further right now. :/
