### ISSUE TITLE
Migrate to Material Design 3

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#3650]
The dependency `com.google.android.material:material:1.5.0` now has support for Material Design 3.

There is some migration to be done for that: https://material.io/blog/migrating-material-3

As far as I understand, Material Design introduces a new look for all the default components starting with Android 12 and gives the user the ability to define some system-wide color schemes. See https://m3.material.io/ 

Anyone interesting in doing this migration?

**Comment by rugk** [comment]
I'd be happy to test it (with Android 12 here).

**Comment by westnordost** [comment]
Best if the one who implemented this also tested this. But it shouldn't be too complicated to do this without much knowledge of the code. Most of it will be a search and replace and following the migration guide linked. Are you interested to do that?

**Comment by rugk** [comment]
Not yet here, I'll keep it in mind though.

**Comment by westnordost** [comment]
I'll just update the dependency but not migrate to Material 3. The differences are not big, but what is changed looks ugly or decreases usability, e.g.
- smaller text but bigger padding on buttons decreases readability
- all buttons are round now, which makes them all look like tags (e.g. the "open" tag on github, see above)
- but FABs are now mostly rectangular and light-pink.  because... 🤷??
- default background is not white but very light pink... eh 🤷?
- top (and bottom) navigation also have that light pink background and don't stand out from the rest of the view (I think there is not even a shadow or divider line)
- plus the difference in styles is causing all sorts of subtle glitches I'd need to fix. I don't really wan to invest the time to make work a style that is just less good than the current one.

Maybe some time Google will come up with Material 4 or something.

**Comment by rugk** [comment]
What I heard as a good thing about Material Design 3 though is that it can adapt to the color you choose in your system settings, i.e. all apps are also styled somewhat like that. That sounds cool, actually. (without knowing how it works/looks like)
