### ISSUE TITLE
Allow paths/steps to be converted to escalators/travelators

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3652]
**Use case**
Similar to #3288 steps which are actually escalators (or travelators) are sometimes not tagged as such.

**Proposed Solution**
Similar to #3288 add an other-answer to add conveying:
https://wiki.openstreetmap.org/wiki/Key%3Aconveying

I appreciate you could leave a note, but then it needs processing; also you can answer all the questions about it anyway, so it's a bit odd to go down the can't say route to add more info, and a bit vague if you just drop a note in the general area, then you've got to specify which way it is too, especially because (at least in London), there are often steps nearby too.

**Comment by westnordost** [comment]
Escalators outside of buildings are rare enough that I think "can't say" is enough.

**Comment by peternewman** [comment]
Ah, I hadn't realised about that filtering; I've opened #3654 to fix the data issue that actually caused this.
