### ISSUE TITLE
Also ask for Halal/Kosher for shop=convenience

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3653]
**Use case**
We currently ask for Halal/Kosher for https://wiki.openstreetmap.org/wiki/Tag:shop=supermarket but there are also some https://wiki.openstreetmap.org/wiki/Tag:shop=convenience which sell Halal/Kosher products too. There are ~50 tagged in London (and none tagged with diet:halal=no/only) so it's likely it's just people specifically tagging some, rather than it not being very widespread.

**Proposed Solution**
Search for convenience too, no other changes required.

Happy to make the PR, just thought I should raise an issue as others may e.g. feel it's too rare or that such small shops wouldn't have that range (although I don't personally feel that's the case).

**Comment by westnordost** [comment]
ok
