### ISSUE TITLE
Ask if steps/paths are indoors

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3654]
### General
Affected tag(s) to be modified/added: [indoor](https://wiki.openstreetmap.org/wiki/Key:indoor)
Question asked: **Is this path indoors?** **Are these steps indoors?**

Triggered by:

> Escalators outside of buildings are rare enough that I think "can't say" is enough.
> 
> _Originally posted by @westnordost in https://github.com/streetcomplete/StreetComplete/issues/3652#issuecomment-1016495864_

I hadn't even realised there was filtering for this as e.g. 90% of the recent stairs mapping I've done has been in tube (underground) stations which seemingly aren't tagged as indoor. Some are tagged as tunnel, some aren't tagged at all.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - It's being asked for these things already
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
All steps/paths under/within buildings

**Proposed UI:**
Simple Yes/No

**Comment by peternewman** [comment]
This would also make https://github.com/streetcomplete/streetcomplete-mapstyle/issues/100 mostly redundant.

And some of my frustration/confusion when being asked whether a separate ramp is mapped and I can't see it to know.

**Comment by westnordost** [comment]
Is there any chance a footway within a building outline is not going to be indoor?

**Comment by peternewman** [comment]
Yes, at the Barbican for example, all the walkways are underneath the tower blocks, but on columns, I think that's covered but not indoor:
https://en.wikipedia.org/wiki/Barbican_Estate

**Comment by westnordost** [comment]
You mean arcades?

**Comment by kjonosm** [comment]
> Is there any chance a footway within a building outline is not going to be indoor?

Wouldn't that be a [`tunnel=building_passage`](https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dbuilding_passage)?

**Comment by peternewman** [comment]
I think some could be arcades, some colonnades. I'm not really sure where something like the walkway on the left of this picture fits:
https://static.standard.co.uk/homesandproperty/s3fs-public/thumbnails/image/2019/07/05/17/Barbican10-0.jpg?width=990

Or:
https://www.e-architect.com/images/jpgs/london/london_building_aw230607_2720.jpg

Also any mapped roof type structure (e.g. at a station) would cover a path but it wouldn't be indoors. Like the walkway at the front of this picture:
https://commons.wikimedia.org/wiki/File:Euston_Station_entrance,_August_2021.jpg

**Comment by westnordost** [comment]
I'll close this because this should rather be a maproulette task or validation. If an `indoor=yes` is missing on one way,  it is unlikely not the only way that is missing this tag,  so it needs to be added not only for steps but every way within the same building. 

Checking for every single way segment whether it is inside a building outline is somewhat expensive to check when in 99.9% or more of cases this is irrelevant.
Also,  it is really an OSM detail whether something should be considered indoors or a building passage. Same with building passage or covered. This,  difficult to answer and possibly answered differently by different users that may answer questions within the same building. 

Overall,  streetcomplete is no linter/validator, there are other tools better suited for that.

**Comment by peternewman** [comment]
> I'll close this because this should rather be a maproulette task or validation. If an `indoor=yes` is missing on one way, it is unlikely not the only way that is missing this tag,

But how can you tell from satellite imagery (which is presumably what MapRoulette will give), whether it's indoors/covered/arcade/colonade/tunnel etc? You need to do an on the ground survey (using a tool like SC) or have StreetView style imagery to be able to answer that question.

> so it needs to be added not only for steps but every way within the same building.

Which is why I suggested the quest for both steps **and** paths.

> Checking for every single way segment whether it is inside a building outline is somewhat expensive to check when in 99.9% or more of cases this is irrelevant.

I assume it would likewise be too expensive to do so for all the steps/path quests SC asks (even if cached so it's only checked once per way)?

> Also, it is really an OSM detail whether something should be considered indoors or a building passage. Same with building passage or covered. This is difficult to answer and possibly answered differently by different users that may answer questions within the same building.

Yeah I'd certainly agree pinning down whether it's indoors/covered/arcade/colonade/tunnel etc and getting consistent definitions for all of them could be a challenge.

> Overall, streetcomplete is no linter/validator, there are other tools better suited for that.

Yep fair enough, although I feel like we've hit a bit of an impasse, please can we do something to fix it? I get asked about large numbers of paths/steps which are under the cover of a building (the exact type of cover is somewhat irrelevant); because https://github.com/streetcomplete/streetcomplete-mapstyle/issues/100 is not available, I'm stuck with a Kim's game style memory challenge to try and identify the path/steps on the ground to answer the question.

Could I suggest one of the following solutions:
1. Filter them out so I never see the quests - expensive
2. Do https://github.com/streetcomplete/streetcomplete-mapstyle/issues/100 so I can answer the quest - possibly clutters the map a bit more
3. Do this quest (#3654) so I can correctly tag them first causing them to be filtered out
4. Add an other answer to the steps/paths quests of it's indoors/covered/tunnel (tagging `=yes`, which could subsequently be improved to be more accurate by others if desired) and also filter covered/tunnel out from the steps/path quests to match

Out of curiosity, why are indoor ways excluded anyway, just because of "Easily answerable by everyone from the outside but a survey is necessary"? Similar to a shopping mall, most of the quests I'm being asked are for stations and other high traffic public areas, so going inside is not a big imposition (indeed it's part of my planned route), although I appreciate there's no simple way to differentiate that from some other less well trafficked areas. Maybe it could be a second set of quests which are disabled by default?

**Comment by matkoniecz** [comment]
> I'm stuck with a Kim's game style memory challenge to try and identify the path/steps on the ground to answer the question.

You can also open notes that it is a way missing an indoor tag or edit directly with Vespucci (for quests where indoor ways are excluded)

If that happens often "can't say" option may be a good idea

> why are indoor ways excluded anyway

For some quests indoor ways will have obvious answer or be inaccessible or both

**Comment by peternewman** [comment]
> > I'm stuck with a Kim's game style memory challenge to try and identify the path/steps on the ground to answer the question.
> 
> You can also open notes that it is a way missing an indoor tag or edit directly with Vespucci (for quests where indoor ways are excluded)
> 
> If that happens often "can't say" option may be a good idea

Yes, it does very much so, see for example the paths around/under/through these places (off the top of my head):
https://www.openstreetmap.org/node/3663368460
https://www.openstreetmap.org/node/7159162454
https://www.openstreetmap.org/node/5614077964

A lot are tagged as tunnel at least, I guess you could get a bit philosophical about what's indoors...

> > why are indoor ways excluded anyway
> 
> For some quests indoor ways will have obvious answer or be inaccessible or both

I don't think the steps incline and some of the other quests are necessarily obvious, I appreciate they could be inaccessible, but hopefully the access tag filtering would cover that.

**Comment by matkoniecz** [comment]
@peternewman Which quests would benefit from that? `surface`?
