### ISSUE TITLE
Improve picture for fixed bollard

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3657]
I find the fixed bollard image difficult to distinguish at a glance from e.g. removable and flexible. The bollard is not obviously fixed.

Most fixed bollards I come across are concrete ones, so I think an image of one of them would be better for that option.

I can't find an open licensed image I'm happy with though, e.g.

[Multiply bollards shown, so possibly misleading](https://www.flickr.com/photos/ell-r-brown/40046350391)

[Bollard is at the side of the road](https://commons.wikimedia.org/wiki/File:Lord_North_Street_bollards_7.jpg)

Unless someone has or can find a better image then I imagine I could quite easily find a concrete bollard and take a picture of it, but would this be wanted?

**Comment by westnordost** [comment]
Well, many fixed bollards in my area **are** those metal bollards that in fact do not visually differ a lot from those that can be removed. Sometimes, I even have to try to lift them up to see if they are fixed or not. If the picture was like those you suggest, users might wrongfully assume that if there is a bollard that looks **in style** similar to the picture for a removable one, it is removable.

**Comment by arrival-spring** [comment]
Fair enough, although I still feel that the image for fixed does not clearly show that it is fixed (the text obscures the bottom of it).

**Comment by mnalis** [comment]
Well, I also think current pictures are not ideal. They are very similar, and what @arrival-spring notes the text obscures critical part of it (difference `fixed` / `flexible` is basically only in part which is hidden by text).

Perhaps something like this more robust bollard might be better match for `fixed`?
![IMG_20220122_132800](https://user-images.githubusercontent.com/156656/150884415-de1b5ddd-5969-47de-b0da-943aa2b51ade.jpg)

**Comment by matkoniecz** [comment]
> the pictures change place due to LRU

This can be enabled/disabled

>  more different picture like the ones suggested

From my testing - it results quite often in people answering based on superficial differences on photos (like stone vs concrete curb in curb height quest)

**Comment by mnalis** [comment]
> > the pictures change place due to LRU
> 
> This can be enabled/disabled

Then perhaps we set the **order to _always_ be from most rigid to most removable**: `fixed`, `flexible`,  `foldable`, `rising`, `removable`? 
And pictures for `fixed` and `flexible` moved up a little so their bottom  is not obscured by text. 
That might help, while retaining  similarly (on the purpose) looking pictures.
![small_Screenshot_20220125_131336_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/150979305-54dab32b-9e0d-4d8f-8a79-51458b1138d8.jpg)

**Comment by matkoniecz** [comment]
https://commons.wikimedia.org/wiki/File:Flexible_bollard.jpg has not enough space in photo so new one would be needed - https://commons.wikimedia.org/wiki/Category:Flexible_bollards or Geograph or uncategorized Commons pictures can hold something usable.

You can also take own photo or find other openly licensed one.

https://wiki.openstreetmap.org/wiki/File:Bollard_in_residential_area.png has enough space to recrop, but bollard would be tiny. Or without top?

Are you interested in finding a better image for a flexible bollard? (I can make commit itself if you prefer to avoid it)

Reopening as recropping fixed bollard image is a good idea and quite easy to do (I will do it, but I will wait for a better flexible bollard image).

**Comment by HolgerJeromin** [comment]
I would only show the bottom as we do for "foldable" right now.
Even the flexible image could be used IMO.
![image](https://user-images.githubusercontent.com/2410353/150999004-7459395e-8c5c-4474-b257-fa910c80936b.png)

**Comment by matkoniecz** [comment]
But for flexible bottom is not actually important at all.

**Comment by smichel17** [comment]
Possible/desirable to align the text along the top? Then you can keep the same pictures without obscuring the relevant part.

**Comment by matkoniecz** [comment]
That would break consistency without good reason. Better photos are strictly superior solutions, and bollards should be fairly easy to take photos by someone who cares about this problem.

**Comment by FloEdelmann** [comment]
Also, as noticed by @matkoniecz in https://github.com/streetcomplete/StreetComplete/commit/f8e899982ac059111d429d4963c9f29100d01eb8#r64597901, the current image for fixed bollard has no license that is usable for StreetComplete.

**Comment by westnordost** [comment]
@mnlis picture would be a fine replacement. What is the license?

**Comment by mnalis** [comment]
@westnordost CC-BY is fine with me (if we're talking about my photo in https://github.com/streetcomplete/StreetComplete/issues/3657#issuecomment-1020666101)

**Comment by westnordost** [comment]
4.0?

**Comment by mnalis** [comment]
@westnordost Yes, CC-BY 4.0 is OK

**Comment by matkoniecz** [comment]
@mnalis How you want to be credited? I plan to upload it to Wikimedia Commons so it will be usable at OSM Wiki. Would you prefer "mnalis", "Matija Nalis" or something else?

**Comment by mnalis** [comment]
@matkoniecz I'm also User:Mnalis on Wikimedia Commons, so probably easiest to attribute to that
