### ISSUE TITLE
Ask for shoulder on either side of the road

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#3659]
Trying out the new shoulder quest I encountered roads which had a shoulder on one side of the road only, similar to other quests SC should support this via the standard interface and `shoulder:left`, `shoulder:right` tags.

**Comment by westnordost** [comment]
Were those oneways?

**Comment by andrewharvey** [comment]
> Were those oneways?

No, it was this way https://www.openstreetmap.org/way/732008307

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/search?q=shoulder%3Aright seems to not be widely used

**Comment by westnordost** [comment]
Hmm, that part looks like a sidewalk
https://www.google.de/maps/@-33.7197409,151.1410982,3a,75y,273.54h,67.41t/data=!3m7!1e1!3m5!1sJsOtjbEqG6O5KKRQGNbzXA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DJsOtjbEqG6O5KKRQGNbzXA%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D75.953026%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192

**Comment by westnordost** [comment]
Oh, it's on the left. Is this really broad enough for a car? What is this supposed to be, is it really a shoulder? Why only this short stretch?

**Comment by westnordost** [comment]
Could it be that it is supposed to be a choker (2 lanes to 1 lane before the intersection) but without actually making the roadway thinner but just putting up some markings?

Looking further, it looks like the markings continue after the intersection, but it doesn't look like it is broad enough for a vehicle...

https://www.google.de/maps/@-33.7195632,151.1390352,3a,75y,266.4h,69.24t/data=!3m6!1e1!3m4!1sjfZPLgvN9gY3uVbszRpiGg!2e0!7i16384!8i8192

And it varies in width wildly, plus there are obstacles (power line posts, trees, garbage bins, signs). Though, for the most part of the road, following it further, it looks like it would actually be usable as a shoulder but it's a somewhat smooth transition.

So I guess, though difficult to decide, it would probably a `shoulder=yes`. 

I am just wondering, if this situation, that the shoulder "starts earlier" on one side than on the other is common enough that it is worth to change the UI changing the quest from a simple yes/no question to a similar interface as the sidewalk question. After all, leaving a note is always possible. Does someone have numbers on this? `oneway !~ yes|-1 and junction != roundabout and (shoulder~left|right or (shoulder:left=yes and shoulder:right=no) or (shoulder:left=no and shoulder:right=yes))`?

**Comment by westnordost** [comment]
Hm I wonder what is this: Is this a shoulder or a parking lane?

https://www.google.de/maps/@-33.726997,151.1391074,3a,75y,174.08h,69.88t/data=!3m6!1e1!3m4!1sRSwwI6FQEnVaO0BRKkJRGA!2e0!7i16384!8i8192

Possibly some kind of multi purpose non-driving lane? But how would that project to OSM tags?

**Comment by matkoniecz** [comment]
> https://www.google.de/maps/@-33.726997,151.1391074,3a,75y,174.08h,69.88t/data=!3m6!1e1!3m4!1sRSwwI6FQEnVaO0BRKkJRGA!2e0!7i16384!8i8192

I would consider it as parking lane, but if people would handle it differently I would not consider it as a mistake. Though for me it is not a shoulder, unless all of them park then illegally (shoulder for me is only for emergency parking)

**Comment by andrewharvey** [comment]
> https://taginfo.openstreetmap.org/search?q=shoulder%3Aright seems to not be widely used

Got to compare with the alternative tagging `shoulder=right` https://taginfo.openstreetmap.org/search?q=shoulder%3Dright.

`shoulder:right=*` appears 9,835 times vs `shoulder=right` which appears 11,012 times.
`shoulder:left=*` appears 649 times vs `shoulder=left` which appears 2,589 times.

So while the wiki correctly documents both as in use it would appear the latter style has slightly more support. Regardless there exists a tag in use, one or the other. I guess which you use depends what the user surveys. If they only confirm one side then you can only tag `shoulder:left/right=*` if they confirm both sides then you can tag `shoulder=left/right/both`. 

> Oh, it's on the left. Is this really broad enough for a car? 

Yes it looks like you could fit a car there though without any buffer.

> What is this supposed to be, is it really a shoulder?

Who knows what it's supposed to be, it's quite common to see a road built and then later they'll paint the lines and sometimes the there is more sometimes less space between where they laid the bitumen vs where they paint the lines.

It's a space between the curb and the travel lanes, and wide enough for a car to stop so you could call it a shoulder.

> Why only this short stretch?

It's very common to see this, just the way it is.

> Could it be that it is supposed to be a choker (2 lanes to 1 lane before the intersection) but without actually making the roadway thinner but just putting up some markings?

No I would not say so.

> And it varies in width wildly, plus there are obstacles (power line posts, trees, garbage bins, signs). Though, for the most part of the road, following it further, it looks like it would actually be usable as a shoulder but it's a somewhat smooth transition.

Yes very common for the shoulder to vary in width, I always thought it just comes down to how much spare asphalt the street works had on the day they laid it, but who really knows.

It's tricky because for me a shoulder is different to an emergency stopping lane, the latter is purpose built as one, it's almost like an extra lane but reserved from normal use. Whereas a shoulder is never usually purposely constructed as any particular infrastructure it's more like a buffer space, most of the time not wide enough for a car and which serves as an informal bicycle lane (which is why I really want to map shoulders because they make a big difference to bicycle routing for safety, I'd much rather be on a 100km/hr road with a shoulder than one where I'm riding in the traffic lane).

The OSM wiki takes a different view.

In my experience it's common to see rubbish bins in the shoulder on bin day.

> So I guess, though difficult to decide, it would probably a shoulder=yes.

But it's only on one side of the road for some sections.

> Hm I wonder what is this: Is this a shoulder or a parking lane?
> https://www.google.de/maps/@-33.726997,151.1391074,3a,75y,174.08h,69.88t/data=!3m6!1e1!3m4!1sRSwwI6FQEnVaO0BRKkJRGA!2e0!7i16384!8i8192
> 
> Possibly some kind of multi purpose non-driving lane? But how would that project to OSM tags?

If it's wide enough for cars then I'd call it a parking lane given there are no signs saying you can't park (therefore you can park). If it's not wide enough for a car I'd call it a shoulder.

If you'd like I can find more examples of shoulders only on one side of the road.

**Comment by westnordost** [comment]
Ok so I'll change this to a street side select UI but I postpone it to v40

**Comment by westnordost** [comment]
Alright, changed the interface to a left-right-select like for sidewalks
