### ISSUE TITLE
Ask access and fee for slipways

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3661]
### General
Two separate, but strongly related, quests. Same thoughts apply to both I think.

Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access) and [fee](https://wiki.openstreetmap.org/wiki/Key:fee)
Question asked: **Who is allowed to use this slipway? May be free or paid.**
Question asked: **Do you have to pay to use this slipway?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose - 5.7% of slipways have `access` tagged, 2.95% have `fee` tagged - [taginfo](https://taginfo.openstreetmap.org/tags/leisure=slipway#combinations)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - slipways I have come across are generally clear as to these things (to the same extent that parking is)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) - more than 40,000 elements, so not loads but I'd be happy to take the effort

### Ideas for implementation

**Element selection:** 
`nodes and ways with leisure=slipway and ( access=unknown or !access )`

`nodes and ways with leisure=slipway and access~ yes|customers|public and ( !fee or fee older today -8 years )`

**Metadata needed:** 
Don't think any

**Proposed UI:**
Essentially the same as equivalent parking quests.

I don't think it should have the customers option for the access quest.

And I think that time conditional restrictions are so rare that that isn't needed for fee?

**Other**
I'm happy to implement these quest if they are accepted.

**Comment by matkoniecz** [comment]
Fee can be tricky, some smaller one will be paid during summer and free during other parts of the year.

Access should be relatively simple but I lack sense to judge is it a good idea to tag it on the every single slipway

**Comment by westnordost** [comment]
> I don't think it should have the customers option for the access quest.

Maybe "permissive". Slipways are usually owned by **someone**, be it a sailing club or whatever. Also, at least in my experience, especially such slipways that are on semi-private land such as of sailing or yacht clubs are not really signed because the area they are in are already kind of private if you are not a member.

Which is why I think this quest may be difficult to answer without asking someone on-site - and depending on who you ask or how nicely you ask, you will get a different answer.

**Comment by westnordost** [comment]
So, based on that I think it would be difficult to answer and/or there is the danger that private/permissive slipways are tagged as public, I'd close this.

**Comment by arrival-spring** [comment]
Hmm, I suppose so

**Comment by matkoniecz** [comment]
But

> I'm happy to implement these quest if they are accepted.

is appreciated! Good luck with finding something obvious enough for a SC quest.
