### ISSUE TITLE
Meetup, Social and Teamwork

### ISSUE THREAD

**Issue by busterbeam** [streetcomplete/StreetComplete#3666]
**Use case**

I haven't used it much, in fact I don't really want to use it but I know this is a good cause.. so my "use case" would be a solution

**Proposed Solution**

Allow people to connect in the app to work collaboratively or competitively.  Maybe add a leader board to see who covers the most "quests" a day, etc...  The app gives me a score but I have no idea if that is any good or if I want to spend more time using this app.  I have no sense if anyone uses this app in my area.

**Comment by mnalis** [comment]
- When you press `menu` button (top right of the screen), you'll find `Team Mode` there for collaborative mapping

- You can use https://hdyc.neis-one.org/ to compare your username with some other username (any even without comparison it will tell you the `Type?` of mapper you are). It is OSM-wide, though, not StreetComplete-specific.

- related: https://github.com/streetcomplete/StreetComplete/issues/3524

**Comment by westnordost** [comment]
>  app to work collaboratively

See @mnalis , you can already do that!

> competitively / leader board

This is a deliberate omission. The primary motivation to use this app should be to do the mapping itself

If you don't have fun and/or motivation to use it as is, then maybe you shouldn't use it. OpenStreetMap is a hobby after all. That being said, there are some ideas to make the mapping itself a little more fun, by adding some nice animations, statistics etc.
What already exists for example if you tap on your profile (and have some quests solved), you see various contribution statistics.
