### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [streetcomplete/StreetComplete#3667]
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:lintVitalAnalyzeRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Internal error: Unexpected lint invalid arguments
```

Could you please take a look? Thanks!

**Comment by westnordost** [comment]
> Internal error

Seems to be an internal issue in the tooling. Any help to find the cause of this error is appreciated.

**Comment by matkoniecz** [comment]
@linsui have you also reported this bug on F-droid  bug tracker?

They run own build infrastructure and builds actually work on Android Studio so it is F-droid specific.

@linsui 
Also, is there anywhere instruction how to run F-droid build process locally to debug the issue?

(I am willing to look into it but list time I tried to do something with F-droid the documentation was pretty bad)

**Comment by linsui** [comment]
I'm a contributor of F-Droid. The easist way is teting it in the CI. See https://gitlab.com/fdroid/fdroiddata/-/blob/master/CONTRIBUTING.md.

**Comment by westnordost** [comment]
@matkoniecz it is reproducible locally for me.

**Comment by linsui** [comment]
Thanks!
