### ISSUE TITLE
Unable to obtain location on GrapheneOS

### ISSUE THREAD

**Issue by ojoeth** [streetcomplete/StreetComplete#3668]
Hello,
I have tried using both the f-droid and google play versions, with and without google play services (sandboxed). The OS location toggle is turned on and other apps (Google Maps, Organic Maps, Vanadium Browser) are able to obtain my location without issues both independantly and with google play location APIs.

My OS is GrapheneOS Android 12 on a Google Pixel 6.

**Comment by matkoniecz** [comment]
Please, check permissions - maybe you refused to give location permission to SC?

**Comment by westnordost** [comment]
What happens when you tap on the location button on the lower right corner?
