### ISSUE TITLE
Handling shelter=separate / bench=separate etc.?

### ISSUE THREAD

**Issue by Lukas458** [streetcomplete/StreetComplete#3669]
**Use case**
highway=bus_stop with bench=separate or shelter=separate ...

**Description**
Hi,
when I look at the **bus_stop_shelter** quest for example, I see the line
       ` and (!shelter or shelter older today -4 years)`

there.
My question is now, what would SC do with bus_stop-nodes where the "shelter" value is not "yes" or "no", but "separate", e. g. at https://www.openstreetmap.org/node/306001628 ?

The shelter is mapped separately there, because it's a few meters away from the position where the bus actually stops.
And the bus_stop for this gets a "separate" value.
I know that this mapping practice is not *so* popular or popular yet, but I don't think it's wrong anyway.

Even it's more correct than mapping a shelter separately AND filling the bus_stop node's "shelter" field with a "yes", which is even more often mapping practice in osm at the moment.

I know this is not the place to discuss this, but my intention is that SC can handle these mapping situations.

The "separate" value is there to ensure that another one is NOT generated at the bus stop, because then we would have a duplication with shelter=yes at the bus stop and a single amenity=shelter.

**So my question is: for the bus stop linked, would SC ask a user for actualising the "shelter" value if it gets older than 4 years?**
Because then, a user would have only the options "yes" or "no" to choose and so he would instinctly choose "yes" of course, which would case a duplicate.

**Proposed Solution**
Exclude highway=bus_stops with "shelter=separate" from the bus_stop_shelter quest,
those with "bench=separate" from the bus_stop_bench quest
and
those with "bin=separate" from the bus_stop_bin quest.

**Comment by westnordost** [comment]
> So my question is: for the bus stop linked, would SC ask a user for actualising the "shelter" value if it gets older than 4 years?

Correct.

> Proposed Solution

I'd say, no. `*=separate` on the mentioned keys is not even documented.  We cannot possibly change implementation of every editor when someone invents a new non-backward compatible tag value (and wants this tag value recognized).  `shelter=yes` etc. was never defined in a way that then "a shelter should be drawn" at the bus stop, but `shelter=yes` etc. is simply to denote that this bus stop has this feature and always has been. E.g. `tactile_paving=yes` on a bus stop means that this bus stop features tactile paving, not that there is tactile paving at the bus stop node.

**Comment by matkoniecz** [comment]
Note also that `=separate` value was discussed a bit and it seems to me that there is no consensus to redefine this keys in backward incompatible way.

See tagging mailing list and will talk pages of some affected keys.

> The "separate" value is there to ensure 

Redefining this boolean keys (yes/no) and adding `separate` will not ensure or solve anything - this would require throwing out our collected data and resurrecting from scratch with a new definition.

It can, at most, give false hope that broken processing will work.
