### ISSUE TITLE
Sichtbarkeit eigener Notizen

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3670]
Im Juli letzten Jahres hatte ich eine Meldung gemacht (#3049) , dass ich meine eigenen Notizen nicht mehr sehe.
Die Antwort darauf war, dass dies gewollt sei und die Lösung sei:
„Einfach #surveyme im Text einer Notiz oder eines Kommentars schreiben, dann WIRD die Notiz in StreetComplete immer angezeigt.“

Ich habe dies einige Male ausprobiert, jedoch nie meine eigenen Kommentare gesehen.
Da die allermeisten meiner Notizen spätestens nach einer Woche bearbeitet und geschlossen wurden, war mir dies im Grunde egal.
Jetzt häufen sich aber meine offenen Notizen und ich verliere die Übersicht.
Bei der Suche nach einer Lösung bin ich zufällig auf folgendes gestoßen:
Ich habe einer eigenen Notiz, die in SC für mich nicht sichtbar war, als weiteren Kommentar ein #surveyme hinzugefügt (per Vespucci).
Und siehe, jetzt sehe ich meine eigene Notiz.
Bei zwei weiteren Tests, einmal nur
 #surveyme
Und dann
 #surveyme
Test
sehe ich meine eigenen Notizen nicht.
Siehe
https://www.openstreetmap.org/?mlat=51.6159086&mlon=7.4988585#map=16/51.6159/7.4952
3 eigene Kommentare im Schrebergarten, nur der mittlere ist in SC für mich sichtbar.

Was mache ich falsch?

Dann noch eine Anmerkung:
Ich habe im letzten Jahr etwa 2000 Notizen verfasst. Erwartet ihr wirklich, dass ich so oft ein #surveyme schreibe, damit ich meine eigenen offenen Notizen sehe?

**Comment by matkoniecz** [comment]
Note that #surveyme should be used only if further survey is needed at that location.

**Comment by biketeur** [comment]
Das hört sich ganz danach an, #survey nicht mehr verwenden, und das Problem ist gelöst.

**Comment by mnalis** [comment]
@biketeur Related: you can use https://my-notes.osm-hr.org/ or https://ent8r.github.io/NotesReview/ to find your own notes (and then solve them in editor of your choice)

**Comment by westnordost** [comment]
@biketeur Notizen werden dir in der App selbst nicht angezeigt wenn:
- du derjenige bist der zuletzt diese kommentiert hat, es sei denn der Text enthält "#surveyme"
- du derjenige bist der die Notiz mit StreetComplete erstellt hat und die Notiz noch keine weiteren Kommentare enthält
- die Notiz weder eine Frage noch den Text "#surveyme" enthält UND du in den Einstellungen eingestellt hast, keine Notizen die nicht als Frage formuliert sind anzuzeigen

Dein Wunsch diese Funktionalität zu umgehen scheint darin zu fußen, dass du das Notiz-Feature nicht so nutzt wie es gedacht ist. Leider schreibst du nicht, was dein Anwendungsfall ist. Ich schreibe mal wie es gedacht ist:

Mit StreetComplete sollten nur Notizen **vor Ort angelegt** werden. Diese Notiz https://www.openstreetmap.org/note/3020247 macht keinen Sinn, denn wenn du (mit StreetComplete) schon vor Ort bist, was soll dann der Marker dass man hier vor Ort "etwas" überprüfen soll - du bist doch schon da? Wenn Du dir von zuhause für deine nächste Begehung einen Reminder/Marker setzen möchtest, einen Ort genauer zu betrachten/erfassen, dann lege diese Notiz von der osm.org Website aus an. Dann werden dir diese Notizen dann in StreetComplete auch angezeigt.

**Comment by mnalis** [comment]
- related case for showing all notes, with more reasoning why: https://github.com/streetcomplete/StreetComplete/issues/2692
- also might be related, if user does not need notes to be public https://github.com/streetcomplete/StreetComplete/issues/1992 (all local notes would be visible on that device)
