### ISSUE TITLE
ATM tag not removed when answering shop does not exist

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3678]
When a shop that has an ATM is closed / replaced, it cannot be assumed that the next shop also has an ATM.
Thus I think the ATM tag should be removed on shop does not exist answer.

**Comment by HolgerJeromin** [comment]
I think you mean the tag:
https://wiki.openstreetmap.org/wiki/Tag:atm=yes

**Comment by westnordost** [comment]
@mnalis

**Comment by mnalis** [comment]
> Oh, so should the issue be posted on https://github.com/mnalis/StreetComplete-taginfo-categorize?

@Helium314 yes, that would be the best, as `KEYS_THAT_SHOULD_BE_REMOVED_WHEN_SHOP_IS_REPLACED` is (re-)generated periodically from that repo.

**Comment by westnordost** [comment]
> (re-)generated periodically 

How?

**Comment by mnalis** [comment]
> > (re-)generated periodically

> How?

By me typing `make update` (which adds newly detected tags as unclassified), followed by manual classification and `make` - and then copying newly generated `KEYS_THAT_SHOULD_BE_REMOVED_WHEN_SHOP_IS_REPLACED` from [StreetComplete-taginfo-categorize/sc_to_remove.txt](https://github.com/mnalis/StreetComplete-taginfo-categorize/blob/master/sc_to_remove.txt)  to [StreetComplete/OsmTaggings.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/meta/OsmTaggings.kt)  to make a new PR.
