### ISSUE TITLE
Nearby objects with text are sometimes displayed so close to quest icon that quest looks like it is intended for the nearby object

### ISSUE THREAD

**Issue by xuiqzy** [streetcomplete/StreetComplete#3681]
**How to Reproduce**

Zoom in just so much that clicking a quest does not zoom in the map view further but not more.
On this zoom level, click on a quest that is very near another quest of the same type like two recycling containers.

Now the nearby object might have a name/operator that is displayed and it looks like the name is displayed for the object of the quest because they are displayed so close to each other.
This may lead to confusion resulting in answering the quest for the nearby object instead of for the intended object.

**Versions affected**

StreetComplete v39.1
Android 11

One possible solution would be to always zoom the view closer if there are other objects of the same type (very close) nearby or generally zoom in on more zoom levels (but that might be annoying).

**Comment by westnordost** [comment]
Can you post a screenshot?

**Comment by matkoniecz** [comment]
@xuiqzy Can you post a screenshot?

**Comment by xuiqzy** [comment]
Sorry for the late reply!

![Screenshot_1](https://user-images.githubusercontent.com/7362712/152146653-d1364716-9b80-404e-a91c-b72f9842a4b3.jpg)
Above screenshot from roughly here: https://www.openstreetmap.org/node/864945521
If they would be even closer together like in the second screenshot below, the text would even more seem to be describing the current quest.

![Screenshot_2](https://user-images.githubusercontent.com/7362712/152146673-86aa4308-bc69-4418-b427-2996b1128aab.jpg)
Above screenshot from roughly here: https://www.openstreetmap.org/node/8290066460

**Comment by FloEdelmann** [comment]
See also https://github.com/streetcomplete/StreetComplete/discussions/3700.

**Comment by westnordost** [comment]
Well, the app does not automatically zoom in because it would be very disruptive for the user experience if it zoomed in and back out again for every quest tapped. If one really has to look closer because the objects on the map are too close to each other, the user can do this manually.

I don't really know what to do about it and I also don't see it as a major issue. Also displaying the name/brand/operator of the selected object would not help in this case, because if the text is too close to each other, it is also not shown. So I'll close it. After all, there is always the fallback of leaving a note if a contributor is unsure, which is mentioned in the tutorial.

**Comment by xuiqzy** [comment]
Thanks for your answer!
My concern was not that the user is unsure but that they just accept that the current question is for the object (with the name) that is actually close by, thus answering the question for the wrong object.
I also find zooming in distracting if it happens too often!
Would it be possible to only zoom in (and maybe not all the way) for quests where other objects are really close by and but not zoom in for others? Therefore, only zooming in in a few cases where disambiguation of the current from the nearby objects is needed?

**Comment by westnordost** [comment]
Well, the current object is not shown separately. If any icon is shown separately from the one highlighted, that's a separate object. No matter how close it is.
Such "smart" behavior like you meantion would be something that I think would not be transparent/comprehensible for the user. It would feel like "hm sometimes it zooms in, sometimes not, maybe a bug". Also, the user would have no control over such behavior and could/would be perceived such as unwanted. I am very cautious with adding such automatisms.
