### ISSUE TITLE
Show pillar hydrant images in hydrant position quest

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#3686]
_Originally posted by @mpawelski in https://github.com/streetcomplete/StreetComplete/issues/3368#issuecomment-1024183330:_

#### Use case

When being asked about the position of a fire hydrant with `fire_hydrant:type=pillar`, the selectable images only show underground hydrants. This confuses users.

#### Proposed Solution

If `fire_hydrant:type` is `pillar`, show pillar hydrant images ~and possibly (if no image can be found) hide the "parking spot" option~.
For `fire_hydrant:type=underground`, keep the existing images.

#### Possible images

* `fire_hydrant:position=green`:
	* https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-6472528792.jpg
* `fire_hydrant:position=sidewalk`:
	* https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-7190010477.jpg
* `fire_hydrant:position=lane`:
	* maybe https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-6464454770.jpg (I think this is best)
	* maybe https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-4144060539_2.jpg
	* maybe https://commons.wikimedia.org/wiki/File:Fire-fighting-facility_node-7127875243.jpg
* `fire_hydrant:position=parking_lot`:
	* @mnalis' image [below](https://github.com/streetcomplete/StreetComplete/issues/3686#issuecomment-1024936939)

**Comment by westnordost** [comment]
Pictures looks good. I wanted to reply that the on-street fire hydrant looks like it is on (asphalted) sidewalk. But I checked the location, it is the street. Interestingly, it doesn't seem to exist anymore now:

 https://www.google.de/maps/@45.8200067,10.5385954,3a,48.3y,274.67h,53.79t/data=!3m6!1e1!3m4!1s-jBfM3QkHQVzxCMCgqID7g!2e0!7i13312!8i6656

**Comment by mnalis** [comment]
I have seen one on parking lot just the other day, I can go and take picture of that.

**Comment by mnalis** [comment]
Something like this (I have few other angles if needed). CC-BY 4.0
![IMG_20220129_133104](https://user-images.githubusercontent.com/156656/151667711-4e0d5eed-c7a1-4c11-920f-3b4e8eba187c.jpg)
