### ISSUE TITLE
Quest is marked but text does not appear

### ISSUE THREAD

**Issue by julietkilo** [streetcomplete/StreetComplete#3688]
Selecting a quest leads to a marked quest, but the text "e.g. what is the housenumber.." does not appear on screen.
Problem appeared with V39.1 (beta) of streetcomplete but is observed for all quests.

**How to Reproduce**
Select an arbitrary quest in Streetcomplete V39.1
Android 11
LG G8S ThinQ device

**Versions affected**

![Screenshot_20220126-091324](https://user-images.githubusercontent.com/452072/151589125-cb339bf4-12cd-4cfa-8606-c5a1577fe0c4.png)
![Screenshot_20220126-091236](https://user-images.githubusercontent.com/452072/151589140-0f86f190-f47f-447b-a632-01e6039b964b.png)
![Screenshot_20220126-091219](https://user-images.githubusercontent.com/452072/151589149-92fdcecd-4de7-4cf2-b510-8ac28ec5119c.png)

**Comment by matkoniecz** [comment]
Is it happening always or sometimes?

**Comment by riQQ** [comment]
Related to #3337?

**Comment by smichel17** [comment]
If it is the same as described in https://github.com/streetcomplete/StreetComplete/issues/3337#issuecomment-946141454… I agree that there is not really a way to prevent it, but maybe we can recognize when it happens and either automatically re-download, or show a message to the user saying they need to redownload.

@julietkilo You could test whether re-downloading the area fixes the bug.

**Comment by julietkilo** [comment]
I thought it is happened always, but I have a few new insights. It seems to work ok just for new types of quests in this version (for example the "road shoulder quest"). And it seems to fail for all quests that I had in my quest preset (Aufgabenauswahl). 
After switching from my own quest preset to the "Standard" quest preset, it seems to fail for just the quests remaining in the cache. 
After updating/reloading the quests (Hier nach Aufgaben suchen) it works ok for all reloaded quests.

**Comment by westnordost** [comment]
Ok, as expected. So it is the same as #3337 , see my explanations in this ticket why this (rarely) can happen. The solution always is to clear the cache in the app settings or download the area in question again.
