### ISSUE TITLE
change position of quest overview and quest presets overview

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#3689]
**Use case**

In most cases, when I go into the quest settings, I go straight on to the quest presets overview, because I don't want to just rearrange individual quests. Therefore I would find it handy if the position of quest overview and quest presets overview could be changed. 

**Proposed Solution**

As a solution, I would prefer that when you go into the quest settings, you first see only the quest preset overview and tap on a preset to get to the quest overview.

**Comment by matkoniecz** [comment]
The problem is that many people do not use presets at all, especially people new to SC and that would make things more confusing for them.

**Comment by mnalis** [comment]
see also @smichel17 idea in https://github.com/streetcomplete/StreetComplete/issues/3228#issuecomment-910757966

**Comment by tiptoptom** [comment]
Ok, I see the problem. And I think #3228 may be a better solution. So you may close this issue.

**Comment by Korb** [comment]
Does this issue discuss changing the order of rows in the `Manage Presets` screen table (manually or semi-automatically alphabetically)?

I use [SCEE](https://github.com/Helium314/SCEE) and have a dozen presets for different tasks, but the `SCEE`' repository has a rule - to discuss in its issue tracker only what distinguishes `SCEE` from `StreetComplete`. The 'Manage Presets' functionality is identical in both applications, so I'd like to discuss it (or support a previously published proposal) here.
