### ISSUE TITLE
Remove duplicate operators in Italy

### ISSUE THREAD

**Issue by naposm** [streetcomplete/StreetComplete#3690]
In the [metadata file](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/country_metadata/IT.yml) there are a lot of duplicates for the operators. 

Would a cleanup be accepted or are they automatically generated? I'm already working with the Italian community to categorize the various operators and remove the duplicates (like _"Poste Italiane"_ and _"Poste italiane"_ for the Name Suggestion Index, so when ready I could submit a PR for StreetComplete.

**Comment by mnalis** [comment]
Those files seem to be (semi)-automatically regenerated, so I don't think editing them directly is best course of action.

About the best way to solve this, see https://github.com/streetcomplete/StreetComplete/pull/3352#issuecomment-939199676 and below (I too have yet to delve into it for fixing `HR`...)

**Comment by matkoniecz** [comment]
they are automatically generated, though regeneration is run manually (tool used for that is right now broken and replacement is not good enough to run on every release for all countries)
 
Once OSM data is fixed: please let us know, I can rerun such script for Italy

https://github.com/streetcomplete/StreetComplete/pull/3352#issuecomment-939233807 may be helpful (I automated this process a bit, though note https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct for edits that are not confirmed by human)

**Comment by peternewman** [comment]
> Would a cleanup be accepted or are they automatically generated? I'm already working with the Italian community to categorize the various operators and remove the duplicates (like _"Poste Italiane"_ and _"Poste italiane"_ for the Name Suggestion Index, so when ready I could submit a PR for StreetComplete.

Excellent, I'd strongly encourage that, it seems like the only sane way out of this in the long term, with some countries hopefully getting there sooner than others.

Out of curiosity I just had a look at NSI and comparison with the SC data for the UK:

- NSI lists 36
- The current GB list is 166
- Doing a comparison ignoring case, whitespace and removing `-` and `, ` & ` and `'` and then removing duplicates gives 123 rows
- Of which two have semicolons...
- A quick eyeball, with no fact checking, suggests 48 are obvious duplicates (removing `^The ` gets a lot more, `.` does a few, removing ` Ltd$` would do a few, but is probably more country specific)
- In all my naive simplification gets it down to 70, so NSI is at least half way there already. The differences look to mostly be shop/supermarket "operated" ATMs.

@matkoniecz could we apply at least some basic de-duplication to the script please? In rough sanity (and simplicity) order, making it case insensitive, comparing without whitespace and then comparing with no punctuation characters would improve things massively I think. It would also fix @naposm two initial examples. It could store the one with the most initial elements to decide what OSM currently thinks is the "official" naming case/punctuation of something, while avoiding duplicating.

Doing something more involved like including the NSI versions (when not duplicated), or ideally putting the NSI ones in front in a weighted way, would also be nice (given we're already using NSI for some other shop related stuff.

**Comment by matkoniecz** [comment]
> could we apply at least some basic de-duplication to the script please?

Yes, though note that it would be applied to "temporary one" (the proper one can not be even really tested without setting up some fake data input for it). It will be definitely minimal conflation , I do not want to discover that some country has ABC and A-B-C which are separate banks.

Maybe just lowercasing?

For reference see https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/atmOperators.yml#L2333

**Comment by matkoniecz** [comment]
> Doing something more involved like including the NSI versions (when not duplicated), or ideally putting the NSI ones in front in a weighted way, would also be nice (given we're already using NSI for some other shop related stuff.

This is also a potential idea, not sure is it worth creating issue for that.

**Comment by matkoniecz** [comment]
Done the first in https://github.com/streetcomplete/StreetComplete/commit/4112b152af58481e1dc593cce8ce42a698312806

I would wait with the second until NSI has a better coverage

**Comment by matkoniecz** [comment]
> Thanks. Do you mean you've updated a temporary script then, rather than just manually processed the data?

Yes, modification to "temporary" script

> It seems to have simply dropped the duplicate rows, but not combined their totals:

Yes - it is anyway purely help/debug info not used by SC

> the total (and hence the ordering) of an entry, should be the total of all entries which result in the same value when conflated.

While I agree with assuming that duplicates can be skipped I prefer to count only correctly tagged data

> I'm happy to create a new issue to discuss it.

OK

> Please could we also do the same tricks to https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/chargingStationOperators.yml

I will look into into it (may quite a lot of time if I have not run my script for charging stations already)

**Comment by peternewman** [comment]
> Yes, modification to "temporary" script

Cool, is that code online somewhere?

> > It seems to have simply dropped the duplicate rows, but not combined their totals:
> 
> Yes - it is anyway purely help/debug info not used by SC
> 
> > the total (and hence the ordering) of an entry, should be the total of all entries which result in the same value when conflated.
> 
> While I agree with assuming that duplicates can be skipped I prefer to count only correctly tagged data

But regardless of the displayed count, the total node count covered has increased which should push the item up the list. There's no guarantee the highest listed item is "correctly" tagged, just popular...

> > I'm happy to create a new issue to discuss it.
> 
> OK

Done as #3708 

> > Please could we also do the same tricks to https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/chargingStationOperators.yml
> 
> I will look into into it (may quite a lot of time if I have not run my script for charging stations already)
> 
> EDIT: yes, I need to query for every single country. It will update this data as a side effect.

Ah that sounds somewhat more tedious!

I think the charging operators one definitely wants whitespace (or just normal spaces) dropped, there are about five duplicates listed for PodPoint with a combination of spacing or case issues!

**Comment by matkoniecz** [comment]
> Cool, is that code online somewhere?

I pushed it to https://gitlab.com/matkoniecz/osm_tag_analysis_ruby

Relevant commit is https://gitlab.com/matkoniecz/osm_tag_analysis_ruby/-/commit/2b1c9a98c7c7caa6b26288770a5f251f50dd8669

(used gitlab for some minor projects where I am not even interested in them being easy to found and I must say that gitlab interface is annoying. Maybe not terrible but it is death by thousand cuts. As long as GitHub is not requiring Microsoft account for log in I am unlikely to switch. I am tempted to write listing of 9 000 000 things wrong with interface there but it would be waste of time)

> But regardless of the displayed count, the total node count covered has increased which should push the item up the list. There's no guarantee the highest listed item is "correctly" tagged, just popular...

I would need to check it, but I am pretty sure that list position is not influencing anything.

> Ah that sounds somewhat more tedious!

It runs automatically overpass query for each country - I am definitely not doing it manually

**Comment by westnordost** [comment]
Warning, though: Manually editing `atmOperators.yml` etc. will eventually be overwritten by the file generated by

https://github.com/streetcomplete/StreetComplete/blob/7d763dc2bbf2247b1f8dbae0fa6084f64e47fefe/buildSrc/src/main/java/SophoxCountValueByCountryTask.kt

as soon/if Sophox will be usable again. So if you are doing any smart stuff like removing duplicate names that only differ in lowercase/uppercase, you should add this improvement to that task too.

**Comment by westnordost** [comment]
de-duplication logic would need to be added at line 47 in the linked file. See `val result`.

**Comment by peternewman** [comment]
> > Cool, is that code online somewhere?
> 
> I pushed it to https://gitlab.com/matkoniecz/osm_tag_analysis_ruby

Thanks, that's good to know thanks @matkoniecz .

> (used gitlab for some minor projects where I am not even interested in them being easy to found to test it as a GitHub alternative. And I must say that Gitlab interface is annoying. Maybe not terrible but it is death by thousand cuts and in urn GitHub made one that I really like. As long as GitHub is not requiring Microsoft account for log in I am unlikely to switch. I am tempted to write listing of 9 000 000 things wrong with interface there but it would be waste of time)

Off-topic, but you could do like https://github.com/dear-github/dear-github (if it doesn't already exist, but rediscovering it for the link was a challenge).

> > But regardless of the displayed count, the total node count covered has increased which should push the item up the list. There's no guarantee the highest listed item is "correctly" tagged, just popular...
> 
> I would need to check it, but I am pretty sure that list position is not influencing anything.

From my testing of the existing data, it impacts which one is shown first (i.e. the list isn't sorted in the app; so if 6 Asda and 5 ASDA took it above 10 Another Store, the combined Asda should show up first when I press A, but won't with the current fix.

> > Ah that sounds somewhat more tedious!
> 
> It runs automatically overpass query for each country - I am definitely not doing it manually

Glad to hear it.

> Warning, though: Manually editing `atmOperators.yml` etc. will eventually be overwritten by the file generated by
> 
> https://github.com/streetcomplete/StreetComplete/blob/7d763dc2bbf2247b1f8dbae0fa6084f64e47fefe/buildSrc/src/main/java/SophoxCountValueByCountryTask.kt
> 
> as soon/if Sophox will be usable again. So if you are doing any smart stuff like removing duplicate names that only differ in lowercase/uppercase, you should add this improvement to that task too.

The comments in #3202 seem a bit mixed @westnordost , if it actually works currently (but with old/stale/partial) data, I'm happy to make the changes on that script.

**Comment by matkoniecz** [comment]
> it actually works currently (but with old/stale/partial) data

Exactly - only some tiny fraction of expected data was returned.

Which actually should be sufficient for testing.

Just commit solely script changes, without committing corrupted data and it should be fine.

**Comment by smichel17** [comment]
GitLab has also become less FLOSS-friendly in recent times (gitlab.com especially so), and I no longer would recommend it for ethical reasons. In a new discussion, instead of off-topic here.

**Comment by naposm** [comment]
Thanks for the comments, will let the Italian community know!

**Comment by naposm** [comment]
Thanks for the comments! I will send a message to the Italian community on Telegram/Matrix.
