### ISSUE TITLE
Building type: public storage

### ISSUE THREAD

**Issue by Kreuger** [streetcomplete/StreetComplete#3691]
Hey I just started using your app. Where I live we have a public storage facility but I cant seem to find it in the buildings. Am I missing it or is this not an option?

**Comment by mnalis** [comment]
Only the [most common](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/BuildingType.kt) building types are available, [not all](https://wiki.openstreetmap.org/wiki/Key:building) of them... 

For others not in the list, you can click `Other Answers` / `Can't say` / `Leave a note instead`

**Comment by matkoniecz** [comment]
> a public storage facility

Is such building basically a publicly accessible warehouse? Warehouse is taggable.

Which other building type from https://wiki.openstreetmap.org/wiki/Key:building would be used?

Note that you tag building type, not what operates there (it should not change if all users would leave and building would be vacant).

Also, see @mnalis : only the most popular building types are listed

**Comment by Kreuger** [comment]
Well yes and no. Its a building with multiple storage units. So like a room with a roll up garage door, and lock. I ended up going straight to the OSM site and adding it there with my laptop.

**Comment by matkoniecz** [comment]
`building=container` is for container used as a building, not for a building where containers smaller or larger are placed 

like https://wiki.openstreetmap.org/wiki/File:Sparkasse_Jena_SB-Container.jpg

**Comment by smichel17** [comment]
Is "public" a misnomer here? If it is something like one nearby me, you still have to pay for use of the storage area. The one by me is maybe most *similar* to multiple_garages.

**Comment by matkoniecz** [comment]
I will close it as it seems that StreetComplete does not require changes. In case that it appears that something specific needs to be done this issue can be reopened or new one created.

**Comment by Kreuger** [comment]
> Is "public" a misnomer here? If it is something like one nearby me, you still have to pay for use of the storage area. The one by me is maybe most *similar* to multiple_garages.

Im not sure why you assume that public storage would mean its free.

At any rate, Im ok with you closing this. I dont see kt being an ongoing issue.
