### ISSUE TITLE
Corsia d'emergenza - traduzione italiana 

### ISSUE THREAD

**Issue by czanongit** [streetcomplete/StreetComplete#3696]
Nei testi della traduzione italiana, il quesito sulla corsia di emergenza lungo le strade non risulta comprensibile, per difetto si traduzione, sembra. 

In the Italian interface emergency lane question is not understandable.

Nella domanda è scritto "sottoterra" e mi pare fuori luogo, così come "bordo" non risulta chiaro: dalla spiegazione in inglese si intende invece la corsia d'emergenza.
![IMG_20220130_141410_996](https://user-images.githubusercontent.com/91224850/151701218-606e6ece-9075-4fab-8393-20ef451d609b.jpg)

**Comment by FloEdelmann** [comment]
Could you help improving the translation?

See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app on how to do that.

**Comment by FloEdelmann** [comment]
The relevant translations have been changed by "Mannivu" now, so I'm closing this. Note that I can't judge how good the translations are.

![image](https://user-images.githubusercontent.com/202916/152020241-c4087ad7-a4df-4558-8382-252335f45cfb.png)
