### ISSUE TITLE
railroad crossing answering, Passaggio a livello 

### ISSUE THREAD

**Issue by czanongit** [streetcomplete/StreetComplete#3697]
Trying to answer to a question about a railroad crossing, the app crashes
![IMG_20220130_141656_809](https://user-images.githubusercontent.com/91224850/151701398-2ccf9080-15ee-4d0b-98ea-6df1df022870.jpg)
![IMG_20220130_141659_702](https://user-images.githubusercontent.com/91224850/151701400-3d7be98c-c5bd-4bb7-b5ec-d5607c6662bb.jpg)

**Comment by FloEdelmann** [comment]
Please send the crash report if you didn't already. See https://github.com/streetcomplete/StreetComplete/issues/3504#issuecomment-969127888 on how to do that.

**Comment by matkoniecz** [comment]
Which app version you use? Can you update?

One of old releases had bug like this.

**Comment by matkoniecz** [comment]
@czanongit 

Which app version you use? Can you update?

One of old releases had bug like this.

**Comment by czanongit** [comment]
Hi all, you are right! The problem seems to be with older releases, with
the updated app there is no more crash.
Thank you very much
