### ISSUE TITLE
UI: Improve "Star+Number" Interaction

### ISSUE THREAD

**Issue by tordans** [streetcomplete/StreetComplete#3698]
Szenario: I am a new SC user, discovering the UI:

![image](https://user-images.githubusercontent.com/111561/151715061-008f081d-d283-47c6-a74c-847197798a7a.png)

This issue is more of a usability report based on my own experience with some rough ideas about improvements.

Here is, what I am wondering about:

* What is the _star+number_?
* Why cannot I click it, when I can click all other elements on the map?
--
* I find the user profile star-section: I wonder, is this section what the star hints at and if so, why is the number from the map-screen not on this profile-star-section-screen?
--
* I just uploaded changes and the stars count up and there is a spinning animation. Afterwards the notice-bell shows (2) and there is the congrats-animation on click. Just because of the timing I assume the number was live counting my achievement points(?); what does the spinner do? If this is the achievement-UI, should the achievement-animation be triggered there instead?

---

Suggestions, depending on how this is actually meant to work…

- Link the star to the profile-star-section.
- Add a modal to the star, explaining the number and UI.
- If the profile-star-section-screen is connected, show the number there and use the additional space on that screen to explain it.
- (See above:) If the star-section is about achievements, trigger the achievement animation from there, which would explain it some more.

**Comment by matkoniecz** [comment]
Just an explanation for you: star counts answered and applied edits (quest answers). Spinner indicates changes being uploaded to OSM database (it can be immediately, it can be delayed if SC is unable or not allowed to upload right now).

Achievement levels are counted on the profile screen.

**Comment by westnordost** [comment]
> why is the number from the map-screen not on this profile-star-section-screen

Why, it is! Not sure what you mean. The star counter is also on that profile page.

> Add a modal to the star, explaining the number and UI.

I don't think this is necessary. User answers one quest, counter goes up by one. User answers another quest, counter goes up again! What could that mean?!

> Link the star to the profile-star-section.

Hm, all the other things that are tappable are clearly recognizable as buttons. The star counter is just some floating text.

**Comment by matkoniecz** [comment]
See also #1478

It is relatively prominent part of interface and some very new users tried interacting with it

**Comment by matkoniecz** [comment]
> Hm, all the other things that are tappable are clearly recognizable as buttons. The star counter is just some floating text.

Noticeable part of people tries to tap it, likely because similar interface element is typically clickable and links statistics/leaderboard.
