### ISSUE TITLE
UI: Consider changing the nose of the speech bubble

### ISSUE THREAD

**Issue by tordans** [streetcomplete/StreetComplete#3699]
This is a design and usability feedback.

I wonder, what benefit the speech bubble nose adds to the UI…
There is one downside: It suggest that the point where the bubble points to, has something to do with the question. As in a chat, where the nose of the bubble points to the user who is speaking. 

However, in SC this leads to edge cases like below, where the nose points to a different street than the one I am answering the question for.

As a new SC user who is not yet familiar with the UI, I found this misleading.

Ideas …

- Remove the nose. It removes a bit of uniqueness, but in the end it's not too big of a loss IMO.
- Make the nose intelligent and have it point to the map bin (move it at the top of the speech bubble when I move the map or resize the panel)
- Ignore this usability issue since users will figure it out; and it's only an issue in densely mapped areas.

![image](https://user-images.githubusercontent.com/111561/151715541-f0442ba1-c05a-43c0-87f3-3a730fdf74f0.png)

**Comment by westnordost** [comment]
You are the first to mention it. I think you get the UX idea: The quest is asking the question. Does the view not automatically scroll so it centers the quest for you? (Yes, you can move it afterwards)

It's certainly doable - with some effort - to make the nose move and point toward the selected quest, but I fear such a gimmick would actually more distract the user than help to make it clearer.

**Comment by westnordost** [comment]
"Wie gut ist... beschaffen" hört sich komisch an, hab ich das so übersetzt? "Wie ist die Oberflächenbeschaffenheit dieses Weges" sollte doch auch passen.

**Comment by westnordost** [comment]
So, will close this. I also changed the wording of the question.
