### ISSUE TITLE
Improve wording for sidewalks

### ISSUE THREAD

**Issue by tordans** [streetcomplete/StreetComplete#3701]
In cases like below, where the tagging is not just "`highway=path`", but "`highway=footway`" and even "[`footway=sidewalk`](https://wiki.openstreetmap.org/wiki/DE:Tag:footway%3Dsidewalk)" the translations could be more precise.

As a new user, unfamiliar with the 3D view and how to orientate myself on the map and how to read the quests, I was hesitant and had to think to make user I understood the UI correctly. For me, this issue was particularly strong since the local mapping was done in a way where road and sidewalk blurred together in one white area (screenshot below).

This hesitation could be resolved in large part by making the translation UI more conditional.

For example: 

- `highway=path`, ask about "segment of way" (DE "Ist dieser Wegeabschnitt beleuchtet?")
- `highway=footway`, ask about "segment of footway" (DE "Ist dieser Teil Fußweg beleuchtet?" "Ist dieser Teil vom Fußweg beleuchtet?" "Ist dieser Abschnitt des Fußweges beleuchtet?")
- `highway=footway + footway=sidewalk`, ask about "segment of sidewalk" (DE "Ist dieser Gehweg-Teil beleuchtet?" "Ist dieser Teil des Gehwegs beleuchtet?")

![image](https://user-images.githubusercontent.com/111561/151716196-3a3a5435-9576-4b02-b1e2-4d95bfc04af9.png)

![image](https://user-images.githubusercontent.com/111561/151715963-275b27c2-5d17-4952-8930-7f6c2e646ec3.png)

**Comment by matkoniecz** [comment]
Translations are actually fairly easy to improve to anyone: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

In Polish I used 

> sidewalk/path

as anything else was unclear and misleading.

**Comment by smichel17** [comment]
Reminder, also: "way" as it is used in OSM is jargon. It is a common English word, but more in the sense of "route" or "journey". Examples of common use are:

- The school is **on the way** to my house.
- I'll stop at the market **on my way** home tonight.
- There is **no way** past this obstacle.
    - Also metaphorically: There is **no way** I'll have dinner ready by 5:00.

I can't think of a better word that unambiguously covers all the cases that "way" does, but it should be avoided when possible.

**Comment by westnordost** [comment]
@smichel17 this does not apply to German though, "Weg" translates both to "way" and "path". Hence maybe the wrong use by @tordans .

**Comment by westnordost** [comment]
Most sidewalks are actually not tagged with `footway=sidewalk`. So looking at this tag will only be helpful in a few cases. Better do something like @matkoniecz proposed. 

Looking at the current English wording ( "Is this stretch of way lit?" ), I think it better stays as is, because as @smichel17 mentioned, it somehow covers any path/footway/sidewalk by referring to the section as a "way", i.e. as part of a journey.

In German, we could just change the translation to "Ist dieser (Geh)wegabschnitt beleuchtet?"

**Comment by westnordost** [comment]
I did this now
