### ISSUE TITLE
Wrong cycleway:both=* key is added but this key is not valid, use cycleway=lane instead

### ISSUE THREAD

**Issue by urbalazs** [streetcomplete/StreetComplete#3703]
This app adds `cycleway:both=*` to roads, but this key is not valid. Based on the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dlane) the following tags are valid:

- `cycleway=lane` if cycle lanes are on the right **and** left side of the road
- `cycleway:right=lane` if cycle lane is on the right side only
- `cycleway:left=lane` if cycle lane is on the left side only

The renderers cannot parse `cycleway:both=*` so cycle lanes are not displayed if the tagging is wrong.

**How to Reproduce**
Tell the app that the road has cycle lanes on both side. See the change set produced by the app.

**Versions affected**
Current master, see the [source code](https://github.com/streetcomplete/StreetComplete/search?q=cycleway%3Aboth).

**Comment by matkoniecz** [comment]
`cycleway:both=lane` seems OK for https://wiki.openstreetmap.org/wiki/File:K_515_bei_Erichsburg.jpg

I edited wiki in https://wiki.openstreetmap.org/w/index.php?title=Tag:cycleway%3Dlane&diff=2256167&oldid=2104970 and https://wiki.openstreetmap.org/wiki/Tag:cycleway:both%3Dlane is existing already (I created it some time ago)

I am not aware of an existing proposal to deprecate `cycleway:both=lane` (even proposed) or considering it as invalid though I admit that I would prefer using `cycleway:left=lane` + `cycleway:right=lane`

> Based on the OSM wiki the following tags are valid:

OSM Wiki is very often incomplete, sometimes is wrong

> cycle lanes are not displayed if the tagging is wrong.

Lack of support does not automatically indicate that tagging is wrong. Feel free to request support in relevant projects

**Comment by mnalis** [comment]
I agree generally with @matkoniecz , if support is missing in some specific renderer, support should be asked to be added there...

However, even looking just at standard bicycle related layers at osm.org website, while `CyclOSM` seems to work in all cases:
https://www.openstreetmap.org/way/313655013#map=19/51.81754/9.87430&layers=Y (right only)
https://www.openstreetmap.org/way/22991675#map=18/51.81862/9.85566&layers=Y (both)

`Cycle map` seems to **fail** for `cycleway:both=lane` case:
https://www.openstreetmap.org/way/313655013#map=19/51.81754/9.87430&layers=C (right only)
https://www.openstreetmap.org/way/22991675#map=18/51.81862/9.85566&layers=C (both)

Given that combination of  `cycleway:left=lane` +  `cycleway:right=lane` seems **better supported** alternative, perhaps that **_should be preferred way to tag_** in SC?
https://www.openstreetmap.org/way/599925272#map=21/51.71304/9.17846&layers=C (right + left  `Cycle map`)
https://www.openstreetmap.org/way/599925272#map=21/51.71304/9.17846&layers=Y (right + left  `CyclOSM`)

**Comment by matkoniecz** [comment]
Personally I consider ease of tagging as more important. If one side of road loses `lane` (or never had it) then one needs to remove `cycleway:both`, add `cycleway:right`, add `cycleway:left` instead of just changing one value.

The same goes for `cycleway:both`

**Comment by mnalis** [comment]
So, basically, all arguments are in favor or mapping `cycleway:right` + `cycleway:left`, instead of using `cycleway:both` ?

Should this issue then be reopened, and SC updated to follow that convention?

**Comment by matkoniecz** [comment]
Still, it has benefit of being a single tag instead of two and some people it is important.

It is definitely better than `cycleway=lane` when cycleway lane is on both sides.

You can ping `@westnordost` I guess, from what I remember he had preference to `cycleway:both` scheme. I do not have very strong feelings on this topic. Not large enough to even make PR changing that.

Another option is to make PR stopping use of `cycleway:both`, may be relatively simple (if that topic had no PR so far).

**Comment by urbalazs** [comment]
Please note that some validators can show warnings if `:right` and `:left` have the same value and they will suggest to remove the right and left indicators and use the key without them.

**Comment by mnalis** [comment]
@urbalazs Ah. Do note that wiki also (quite correctly IMHO) states:

> cycleway:both=lane -  such tagging are better than cycleway=lane as many people used cycleway=lane where only one side of road has a cycleway lane 

So it seems then that **all** available options have problems:
- `cycleway=lane` is ambiguous
- `cycleway:right=lane` + `cycleway:left=lane` is warned about by validators (and longer than needed)
- `cycleway:both=lane` is not supported by some renderers

Thus it is probably best idea to lobby the renderers you use to support  `cycleway:both=lane`, as that is only option that does _not_ lead to additional problems, and is likely the simplest and most easy to lobby for.

**Comment by matkoniecz** [comment]
Note that

> cycleway:both=lane - such tagging are better than cycleway=lane as many people used cycleway=lane where only one side of road has a cycleway lane

was added to OSM Wiki by me, in direct reaction to this issue

> So it seems then that all available options have problems:

Welcome to cycleway tagging :)

**Comment by mnalis** [comment]
> > cycleway:both=lane - such tagging are better than cycleway=lane as many people used cycleway=lane where only one side of road has a cycleway lane
> 
> was added to OSM Wiki by me, in direct reaction to this issue

Still, it matches my experience. Never have I used (nor have I met anyone who has) `cycleway=lane` (or any `cycleway=*`) in a way that indicates that the cycleway lane is on both sides of the street. It seems like ridiculously rare situation to be used as a main use of the tag.

It was always used only as **generic** _"yes, this road has a cycleway lane somewhere"_. Even if some default was to be assumed (which it should not), it would be _"on one side of the street where cycleway lanes usually are in this country"_ (which is most definitely **_not_ on both sides**, at least not in Croatia and surrounding countries I've cycled)

**Comment by wusatosi** [comment]
The support for cycleway:both is sometimes not supported on 3rd party apps. Can we use cycleway=lane instead of cycleway:both?

**Comment by mnalis** [comment]
@wusatosi have you read https://github.com/streetcomplete/StreetComplete/issues/3703#issuecomment-1027104884 ? It outlines while `cycleway=lane` is bad choice (and worse then others). 

If some commonly used tag like `cycleway:both` (almost a [million usages](https://taginfo.openstreetmap.org/keys/cycleway:both#overview) by now) is not supported in you favorite 3rd party app, it would probably be best to lobby your 3rd party app to add support for it. 

(For comparison, `cycleway=lane` has [less then 300k](https://taginfo.openstreetmap.org/tags/cycleway=lane#overview) usages, and even whole `cycleway=*` is slightly less popular than `cycleway:both=*`)
