### ISSUE TITLE
Leaderboard for Rank in country and global rank 

### ISSUE THREAD

**Issue by UnixPhonez** [streetcomplete/StreetComplete#3706]
**Use case**
Adds a little competition to the game

**Proposed Solution**
A leaderboard for the two categories "Rank in Country" and " Global Rank"
It would display the top 10, 50 or 100 for rank in country and for global rank it would display top 100

**Comment by mpikzink** [comment]
IT should also display the next 10 positions depending of my own rank. Otherweise the gap between a pro and beginner ist to big.

**Comment by mnalis** [comment]
- See https://github.com/streetcomplete/StreetComplete/issues/2541#issuecomment-770297767 and other comments, as well as https://github.com/streetcomplete/StreetComplete/discussions/2598

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/sc-statistics-service/issues/20

In general I will close it for reasons similar to #2541 - pushing gamification too hard may lead to bad results and there were already cases of people answering questions without survey
