### ISSUE TITLE
True monochromatic red-black night mode

### ISSUE THREAD

**Issue by eumiro** [streetcomplete/StreetComplete#3716]
**Use case**

When walking in dark/low light environment, looking from time to time at a bright phone screen (even in dark mode), forces the eyes quickly adapt to its blue light and then back to the dark environment.

**Proposed Solution**

I'd like to have a true monochromatic night mode using colors between `#000000` and `#FF0000` only. That would have no influence on the user's night vision.

**Comment by matkoniecz** [comment]
That would be a very significant redesign and quite significant effort to achieve this.

**Comment by HolgerJeromin** [comment]
Android 11 can make the screen black / white in the night. Perhaps this helps you.

**Comment by mnalis** [comment]
My EMUI 11.0 (Android 10) has this too, when you set  "digital balance". It would be nice if it was "black / dull red" instead of "black / dull white" though. Something to suggest to Android makers I guess. 

There are also free apps like [Red moon](https://f-droid.org/en/packages/com.jmstudios.redmoon/) which allow making display reddish for night mode system-wide.

**Comment by 10992-osm** [comment]
> Android 11 can make the screen black / white in the night. Perhaps this helps you.

Called as part of ["Bedtime mode" in "Digital wellbeing"](https://blog.google/outreach-initiatives/digital-wellbeing/improve-your-sleep/).

It can also tint it amber ("[Night Light](https://source.android.com/devices/tech/display/night-light)")

**Comment by westnordost** [comment]
Actually I think I will make the background for the forms etc. `#000000` black on dark mode instead of the dark grey they are currently.

**Comment by smichel17** [comment]
Helps (a little) with https://github.com/streetcomplete/StreetComplete/issues/3378, too :)

**Comment by westnordost** [comment]
There is one reason though I notice now: Modal dialogs darken the rest of the background so they stand out more. If the background is already black, there is nothing to darken and so the boundaries of the dialog are not well visible.

I researched long whether it is possible to change the color of the background-darken: No, it is hardcoded.
