### ISSUE TITLE
SC asks for opening_hours check for disused:shop

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#3718]
SC asks for opening_hours check for vacant shops. This makes no sense, because the shop is closed forever.

**How to Reproduce**

- Have a former shop node with disused:shop key and also the tag opening_hours with a meaningful value (the value of the former shop)
- SC asks to check the opening_hours although the node is already marked as vacant

I am not sure about the desired behavior of the app. Maybe it should not even ask for a opening hours check or it could help to remove that tagging.

**Versions affected**

v40.0-beta1

**Comment by matkoniecz** [comment]
Can you link a specific object where it happened?

How this object was described in a question?

I am betting that OSM data is somehow wrong there.

**Comment by Helium314** [comment]
see #2712

**Comment by Strubbl** [comment]
So yes, it's an error in the OSM data: disused:shop, which has opening:hours. Don't we want to fix this with SC?

**Comment by matkoniecz** [comment]
I think it would be fine to skip such objects and require old opening hours to match the same criteria as new opening hours ( https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt#L98 )

Possible loss is that SC would not ask anymore about opening hours on say gates with old opening hours.

**Comment by peternewman** [comment]
If this is fixed the same thing wants applying to CheckOpeningHoursSigned too I think.

**Comment by matkoniecz** [comment]
> If this is fixed the same thing wants applying to CheckOpeningHoursSigned too I think.

answered in PR

**Comment by westnordost** [comment]
> Have a former shop node with disused:shop key and also the tag opening_hours with a meaningful value (the value of the former shop)

@Strubbl How is this meaningful and not a tagging mistake? A disused shop has no opening hours.

**Comment by Strubbl** [comment]
Of course this is a tagging mistake. I thought SC might want to detect that it is asking for checking opening hours for a disused shop and finally don't ask and maybe ask to open a note or fix that data issue.

**Comment by Strubbl** [comment]
I just searched for an example node, which has wrong data: https://www.openstreetmap.org/node/3663837425
If you go there with SC, then you hide the question regarding "is this shop still vacant", i get the opening hours question although it is a [disused:shop](https://wiki.openstreetmap.org/wiki/Key:disused:shop?uselang=de).
Now, in the opening hours quest, i say "does not exist". It is only possible to open a note now. I cannot mark it as vacant.

**Comment by matkoniecz** [comment]
> If you go there with SC, then you hide the question regarding "is this shop still vacant"

Yes, the problem happens only when someone either

- disables  "is this shop still vacant" quest
- moves quest order so OH quest is above vacant quest
- hides specific "is this shop still vacant" quest instead of answering it

**Comment by Strubbl** [comment]
In my case, because i opened the issue, the opening hours quest occured at first. In my opinion the quest order was okay and i did not see the "is this shop still vacant" quest. Unfortunately i cannot reproduce it anymore since i corrected the node. Please see version #8 of https://www.openstreetmap.org/node/4294027197/history

**Comment by matkoniecz** [comment]
> i did not see the "is this shop still vacant" quest

Weird. Maybe you hid it earlier and forgot? Or there is another path to that?

Or you reordered/disable quest types and forgot about it? (can you check quest order and enablement in settings?)

**Comment by Helium314** [comment]
> > i did not see the "is this shop still vacant" quest
> 
> Weird. Maybe you hid it earlier and forgot? Or there is another path to that?
> 
> Or you reordered/disable quest types and forgot about it? (can you check quest order and enablement in settings?)

Before the fix a week ago, the shop was and last edited (and closed) 5 months ago, and has no general `check_date` or similar (only one for opening hours). So even with more frequent resurveys, "is this shop still vacant" will not be asked.

But `check_date:opening_hours` is very clear here, older than 6 months, and is preferred over the last edit date. So opening hours will be asked. (well, maybe not any more after the recent PR)
