### ISSUE TITLE
Sichtbarkeit eigener Notizen

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3721]
<!-- 
Ich habe vor kurzem ein Problem gemeldet (#3670) und bin erstaunt über die Art und Weise, wie es behandelt wird:
Ich beschreibe das Problem und stelle die Frage, ob ich vielleicht falsche Eingaben mache. Als Antwort erhalte ich Informationen, unter welchen Bedingungen Notizen angezeigt werden. Aber genau daran halte ich mich. Ich selber finde keinen Fehler in meinen Eingaben. Auch keiner der Kommentatoren weist auf eine Fehleingabe hin. Für mich heißt dass, dass sich SC nicht so verhält wie behauptet. Und dies ist im Umkehrschluss ein FEHLER.
Also, liebe Entwickler, es wäre schön, wenn ihr meine Meldung auch entsprechend einstufen würdet.
Und es ist völlig irrelevant, warum ich eine Notiz eintragen will und ob ich es vor Ort oder Zuhause eintrage. Wenn ich ein #surveyme in eine Notiz schreibe, soll SC sie mir anzeigen laut Entwicklung. Und dies geschieht nicht.

**Comment by matkoniecz** [comment]
See #3670 especially https://github.com/streetcomplete/StreetComplete/issues/3670#issuecomment-1021026662

If you want to answer to that comment it would be better to

- to in that issue
- actually answer it
