### ISSUE TITLE
SC should ignore highway=proposed

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3723]
For some quests, SC seems to ask for attributes of [highway=proposed](https://wiki.openstreetmap.org/wiki/Key:highway#Lifecycle).
Such "highways" should always be ignored by SC.

**How to Reproduce**
See https://www.openstreetmap.org/note/3037310 for example where `lit` quest was asked on https://www.openstreetmap.org/way/934592248

**Versions affected**
StreetComplete 39.1, Android 10

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt

Thanks for reporting but I have no idea how it happened.

**Comment by mnalis** [comment]
ops, sorry for the noise @matkoniecz. 

I was sure I did that in official version, but it seems I was not as I cannot reproduce it there now but can in local fork. 
I'll investigate locally for the cause

**Comment by matkoniecz** [comment]
Yeah, see https://github.com/mnalis/StreetComplete/blob/mnalis-everything/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt#L23
