### ISSUE TITLE
Automatic checking of image sizes in PRs?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3725]
I was reviewing #3724 and as part of it I 

- opened documentation
- opened each image
- checked expected sizes and compared with actual sizes

It seems like something reasonable to automate, though it depends on layout (see https://github.com/streetcomplete/StreetComplete/pull/3695#issuecomment-1027250892 ) so may be a bit tricky and require processing Kotlin code.

**Comment by westnordost** [comment]
Yes, it would be very tricky, because the pictures can simply have different sizes for each different form. This is why I do not think this is doable.
