### ISSUE TITLE
Being unnecessarily asked for shoulders on slow trunk roads (e.g. in cities)

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3727]
You get asked for shoulders (as originally suggested in #2444) on roads with only 30mph in cities because they're also trunk roads.

The accepted speed limits
https://github.com/streetcomplete/StreetComplete/blob/9eb9a2eb360f4a246aa4598bf57bddb6caf2e3c6/app/src/main/java/de/westnordost/streetcomplete/quests/shoulder/AddShoulder.kt#L33-L34

Incidentally, is the speed regex right here; 50 kmh is 31 mph, but you're only matching from 40mph up; with all the other maxspeed regex, there seems to be a much tighter coupling between units. I think you either want `3[1-9]|` at the start or `> 60`.

Are overridden by the `highway=trunk` tagging:
https://github.com/streetcomplete/StreetComplete/blob/9eb9a2eb360f4a246aa4598bf57bddb6caf2e3c6/app/src/main/java/de/westnordost/streetcomplete/quests/shoulder/AddShoulder.kt#L25

Ideally it wants to be:
```
speed>fast
or ((!speed or speed>fast) and (highway=trunk)
```

At least in the UK, you generally only get those slow speeds on major roads in cities, at which point you don't have the space for shoulders and I'm not sure what benefit they'd be at that speed versus "all lane running" and having more lanes when there isn't an accident.

**How to Reproduce**
Answer the quest for here (except I already have):
https://www.openstreetmap.org/way/279154275

**Versions affected**
SC 40-beta1

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/1fPV confirms that `highway=trunk` `maxspeed=30 mph` will have shoulders really rarely - and what tagged may be a mistake.

**Comment by westnordost** [comment]
A trunk is certainly a road where one (=data consumers) would expect a certain stage of infrastructure, but I am not familiar with the `trunk` tagging in Britain. In Germany, roads are usually not tagged `trunk` unless they are "a bit like motorways". 

We can fix the filter for `mph` speeds. I'll let the filter start at 35 mph because anything between 30 and 35 is uncommon and 30 mph would still be too low.
I change the filter like this: `!maxspeed and hw = trunk or maxspeed >= fast`, i.e. the default assumption is that trunk maxspeed is "fast"

**Comment by peternewman** [comment]
> A trunk is certainly a road where one (=data consumers) would expect a certain stage of infrastructure, but I am not familiar with the `trunk` tagging in Britain. In Germany, roads are usually not tagged `trunk` unless they are "a bit like motorways".

I think in the UK it's based on the importance aspect (i.e. A road/B road) which are mostly fast/major (except in city centres).

> We can fix the filter for `mph` speeds. I'll let the filter start at 35 mph because anything between 30 and 35 is uncommon and 30 mph would still be too low. I change the filter like this: `!maxspeed and hw = trunk or maxspeed >= fast`, i.e. the default assumption is that trunk maxspeed is "fast"

Thanks, that makes sense.
