### ISSUE TITLE
Prioritise showing crossing quests on the way instead of the node

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#3730]
Currently quests about crossings are asked on the node, even when the crossing line is mapped like in the example below.
Node in picture: https://www.openstreetmap.org/node/6294129135
![image](https://user-images.githubusercontent.com/19364673/152775520-ce2ab78f-a8fd-4b80-8117-d1bc9c46601d.png)

**How to Reproduce**

1. Find a detailed crossing, which has quests
2. Click on the quest for it. The crossing node gets selected instead of the way.
**Versions affected**

StreetComplete 39.1
Android 10

**Comment by matkoniecz** [comment]
I am pretty sure that mapping this properties on node is preferable to mapping them on ways, as all crossings mapped should have `highway=crossing` node and only some will have `footway=crossing` way.

Is this accurate?

Therefore SC will tag this feature on `highway=crossing` node rather on `footway=crossing` way.

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/traffic_signals_sound/AddTrafficSignalsSound.kt#L18

**Comment by Dimitar5555** [comment]
> I am pretty sure that mapping this properties on node is preferable to mapping them on ways, as all crossings mapped should have `highway=crossing` node and only some will have `footway=crossing` way.
> Is this accurate?

That's true, but most of this information is repeatedly asked on roads with more than one way per direction which duplicates the information(for example the crossing that is northwest from that node).

> Therefore SC will tag this feature on `highway=crossing` node rather on `footway=crossing` way.
> 
> https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/traffic_signals_sound/AddTrafficSignalsSound.kt#L18

That's also true but SC asks these quests for ways only if the crossing node doesn't have the required tags.

**Comment by matkoniecz** [comment]
> That's also true but SC asks these quests for ways only if the crossing node doesn't have the required tags.

No, it is not asked for ways at all. Traffic signal sound will be never asked on ways (`nodes with`) unless you use some modified version.

> That's true, but most of this information is repeatedly asked on roads with more than one way per direction which duplicates the information(for example the crossing that is northwest from that node).

In rare but existing cases dual carriageway will have some of this properties different on each carriageway (and recording such cases is likely the most useful for potential users of this data), similarly single `footway=crossing` may include all four pedestrian crossings on a typical crossing of two roads. Here also detailed info may differ.

**Comment by westnordost** [comment]
crossing properties are never tagged on the way as far as I know but always on the node.

**Comment by Dimitar5555** [comment]
> No, it is not asked for ways at all. Traffic signal sound will be never asked on ways (`nodes with`) unless you use some modified version.

I recall that it was asked at some point but it might've been for other types of crossings.


> In rare but existing cases dual carriageway will have some of this properties different on each carriageway (and recording such cases is likely the most useful for potential users of this data), similarly single `footway=crossing` may include all four pedestrian crossings on a typical crossing of two roads. Here also detailed info may differ.

In such cases, SC has the option to cut ways.

> crossing properties are never tagged on the way as far as I know but always on the node.


https://taginfo.openstreetmap.org/keys/traffic_signals:sound
https://taginfo.openstreetmap.org/keys/crossing:island
https://taginfo.openstreetmap.org/keys/button_operated

Feel free to also check the wiki and point me to which tag is not used on ways.

**Comment by matkoniecz** [comment]
All are clearly tagged on nodes rather on ways, what matches

> I am pretty sure that mapping this properties on node is preferable to mapping them on ways, as all crossings mapped should have `highway=crossing` node and only some will have `footway=crossing` way.

even if not matches stronger claim ("never tagged on the way").
