### ISSUE TITLE
Being unnecessarily asked for shoulders on both sides of one way roads

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3732]
You get asked for shoulders (as originally suggested in #2444) on BOTH sides of oneway roads, rather than just the slow side (i.e. the side you drive on)

The wiki has this ( https://wiki.openstreetmap.org/wiki/Key:shoulder#Usage ):
> Data users should assume that if a generic [shoulder]()=yes is specified and the road is a oneway, it is on the right in countries which drive on the right and on the left side in those which drive on the left (Japan, the UK, Australia, etc.).

So it would be nice to behave like the cycleway quest, only asking on the driving side of one-way roads, but maybe if we want to be really thorough have an other answer where you can say they exist on both sides, although it seems very unlikely to me, especially if there is more than one lane.

**How to Reproduce**
Answer the quest for here (except I already have):
https://www.openstreetmap.org/way/279154275

**Versions affected**
SC 40-beta1

**Comment by westnordost** [comment]
Yes, this is deliberate.

> Data users should assume that if a generic [shoulder](https://github.com/streetcomplete/StreetComplete/issues/3732)=yes is specified and the road is a oneway, it is on the right in countries which drive on the right and on the left side in those which drive on the left (Japan, the UK, Australia, etc.).

I wrote that. And it is true, of course. `=yes` is less specific, but data consumers can assume with good confidence that the shoulder will only be one the driving side if it is a oneway. Probably most data consumers are only interested in knowing whether there is a shoulder at all. But that doesn't mean that recording it in more detail is not ok.

**Comment by peternewman** [comment]
Doesn't that hit the spam aspect though by needlessly asking on the "fast" side of the road too for one-ways?
