### ISSUE TITLE
Image misplaced on compacted option in smoothness quest

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3736]
See image:
<img src="https://user-images.githubusercontent.com/77166354/152874896-be0e313e-d22b-4add-8314-e09f86022a7b.png" width="500">

The "very bumpy and uneven" option has the image in a weird place for me. I guess something to do with the line wrapping playing up. 

What other information is needed to fix this?

**Comment by peternewman** [comment]
> What other information is needed to fix this?

Screen resolution and SC/Android versions probably.

Which quest exactly or what way?

I don't have those exact options so I guess this is 40.0 release?

**Comment by matkoniecz** [comment]
Screen resolution would be useful and maybe sufficient to reproduce it.

Phone model, Android version, SC version are in general useful.

**Comment by westnordost** [comment]
The icon is inserted as an ImageSpan. I think it must be a bug in Android handling ImageSpans in multiline text

**Comment by arrival-spring** [comment]
This is 40.0 beta 1
Motorola moto one
Screen resolution 1520 by 720
`surface=compacted` (on both road and path versions of the quest)

**Comment by westnordost** [comment]
@FloEdelmann any idea? Otherwise I will close this as will not fix. In my eyes this is simply a bug in the text view that cannot handle ImageSpans that would wrap to the next line.

**Comment by FloEdelmann** [comment]
I'll have a look later.

**Comment by FloEdelmann** [comment]
It looks fine in the emulator with Android 11:

<img src="https://user-images.githubusercontent.com/202916/153280290-a0872655-1af3-4aca-88d2-d15cbd833216.png" width="300">

What is you Android version?

Maybe it's an issue for older versions of Android (before 10) only:
https://github.com/streetcomplete/StreetComplete/blob/57034acb370370982ccc80a645bd47f5e0b8be60/app/src/main/java/de/westnordost/streetcomplete/ktx/Drawable.kt#L28

**Comment by FloEdelmann** [comment]
Anyway, I think there's nothing we can do on our side, unfortunately :slightly_frowning_face:

**Comment by westnordost** [comment]
Thanks for investigating!

**Comment by arrival-spring** [comment]
> What is your Android version?

Android 10

Thanks for having a look

**Comment by mnalis** [comment]
I can confirm this looks broken on my Android 10 (Huawei P30 Pro, EMUI 11.0.0) too - and not only `Very bumpy and uneven` but also `almost impassable`:

![Screenshot_huawei_p30pro_android10_SC391](https://user-images.githubusercontent.com/156656/153295607-b4a845c6-0001-4b23-a744-416692c005af.jpg)

In Croatian version (on the same phone), only `Very bumpy and uneven` is broken, if that info helps :
![Screenshot_huawei_p30pro_android10_SC391_hrv](https://user-images.githubusercontent.com/156656/153295757-8e865c59-b997-4897-8187-8138645ed267.jpg)

My older Xiaomi Redmi Note 3 Pro testing phone (running Android 6.0.1) seems to look fine, though.

**Comment by westnordost** [comment]
Maybe ALIGN_BOTTOM doesn't have this bug on Android 10, for anyone who wants to try it

**Comment by westnordost** [comment]
Only the second one

**Comment by mnalis** [comment]
sure, will do.

**Comment by mnalis** [comment]
> Only the second one

Hmmm @westnordost, it seems when I only change the second one (https://github.com/mnalis/StreetComplete/commit/dcee43fc149424343ecedabd212cee0c0192c5c3) the display remains broken (`.apk` from https://github.com/mnalis/StreetComplete/actions/runs/1820842507)

However when initially I did change both (https://github.com/mnalis/StreetComplete/commit/dde56499b9260789352f3c7ae3bd6ce9b6d0d434) that `.apk` corrects the problem (https://github.com/mnalis/StreetComplete/actions/runs/1820693088)

**Comment by westnordost** [comment]
Oh, Android Q is Android 10

**Comment by mnalis** [comment]
OK, I'll try then with:

```diff
-    val alignment = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) ImageSpan.ALIGN_CENTER else ImageSpan.ALIGN_BASELINE
+    val alignment = if (Build.VERSION.SDK_INT > Build.VERSION_CODES.Q) ImageSpan.ALIGN_CENTER else ImageSpan.ALIGN_BOTTOM
```

**Comment by westnordost** [comment]
Try 
`if (Build.VERSION.SDK_INT > 29) ImageSpan.ALIGN_CENTER else ImageSpan.ALIGN_BASELINE`
and maybe add a comment that states that ALIGN_CENTER does not work correctly on SDK 29 with reference to this ticket

**Comment by mnalis** [comment]
That PR works on my Android 10 and Android 6 phones. `ALIGN_BASELINE` looks even little nicer than `ALIGN_BOTTOM` originally tried for workaround: 
![Screenshot_20220210_003026_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/156656/153309508-555f6f07-2e9a-4e84-b9e7-7b5ff00dd2e5.jpg)
