### ISSUE TITLE
Ask what happens where waterway and highway cross

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3749]
Inspired by the recent quests about what happens when barriers and roads/paths cross.

### General
Affected tag(s) to be modified/added: [tunnel=culvert](https://wiki.openstreetmap.org/wiki/Tag:tunnel=culvert) or [bridge=yes](https://wiki.openstreetmap.org/wiki/Tag:bridge=yes) and appropriate [layer](https://wiki.openstreetmap.org/wiki/Key:layer) tag or [ford=yes](https://wiki.openstreetmap.org/wiki/Tag:ford%3Dyes)

Question asked: **What happens where this road crosses this river/stream?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
This shows up as a QA issue in a number of places, if there is a ford that is useful to know for routing, bridge is useful if it has weight limit.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
I think this should maybe only be asked for roads (not paths), as sometimes a stream does just cross a path, maybe in a small channel or maybe running over a path and I'm not sure that should always be tagged with `ford=yes`.
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
Most places mapped like this have been done from aerial imagery and it presumably isn't good enough to see whether it's a bridge or culvert.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
All places where road and waterway cross on the same level (waterway not mapped as an area). The ways need not share a node.

In fact maybe avoid those that share a node, because if it's meant to be a bridge or culvert then that node should be deleted, which could affect geometry (if either stream or road isn't perfectly straight either side).

If it's meant to be a ford then a node would need to be added at the intersection.

**Metadata needed:** 

**Proposed UI:**
What happens where this road crosses this river/stream?
* The road is on a bridge (split the road)
* The stream is in a culvert (split the stream)
* There is a ford

Splitting would then lead to the split UI and request exactly two split points on the relevant way, after which suitable tags would be added to the relevant section.

**Issues:**
This needs quite a lot going on behind the scenes, e.g.:

Detection of crossing ways would need to be implemented (as far as I can see the crossing barrier/highway quest looks for a shared node.

Splitting UI would need to be extended slightly to be able to request a specific number of splits.

Detecting which bit of the stream/highway is the middle, and validating that it solves the quest (i.e. there is now no highway and waterway crossing each other here). Or maybe the splitting UI could be made to request a split on each side of the crossing separately somehow.

**Comment by westnordost** [comment]
> Detection of crossing ways would need to be implemented

The functions for checking if two ways intersect already exist, but it is very expensive to do without first sorting all the geometry into a spatial index. (That index would need to be implemented first too)

Furthermore, it seems like you missed on very important thing:

> Affected tag(s) to be modified/added: [tunnel=culvert](https://wiki.openstreetmap.org/wiki/Tag:tunnel=culvert) or [bridge=yes](https://wiki.openstreetmap.org/wiki/Tag:bridge=yes) and appropriate [layer](https://wiki.openstreetmap.org/wiki/Key:layer) tag or [ford=yes](https://wiki.openstreetmap.org/wiki/Tag:ford%3Dyes)

`tunnel=culvert` is set on the small segment **of the stream** that is a culvert. `bridge=yes` is set on the segment **of the road** that crosses over the stream. And `ford=yes` is set **on the node** that is the intersection point between the two. Issues:
1. 2/3 options **require** splitting up the way first. This will be difficult to communicate to the user
2. Depending on the answer selected, **different elements** need to be modified. This is a showstopper, StreetComplete is designed to only handle changes on 1 element.

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/StreetComplete/discussions/2426

I considered implementing it but given enormous implementation cost and risk that it will be too complex to use - I decided that other things are better to handle

**Comment by Helium314** [comment]
It's still a _lot_ of effort to implement (as quests currently are bound to a single element), and geometry analysis is likely to slow down quest creation considerably.

If you really want this, you can use the Osmose quest in [EE](https://github.com/Helium314/StreetComplete) to find the issues (item 1070), a custom overlay that lets you select (and then split) the ways, and the tag editor to convert a part into a bridge or culvert.
What you can't do is connect both ways and add a ford.
