### ISSUE TITLE
Nearby sidewalk detection got worse

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3752]
For a while now I've been getting sidewalk and cyclecway quests on roads where the quest wasn't asked in older versions of SC. In all cases a sidewalk or cycleway was already mapped separately.

I think this comes from https://github.com/streetcomplete/StreetComplete/commit/3707554da8f00bb111252d41b7496e678e8ba137, where the 'generous buffer for possible grass verge' was reduced from 6 to 4 (meters). It appears that the check for parking lanes is done as a replacement for the 2 meters, but very often the parking is not tagged.

So my suggestion is to a default width of 2 (instead of 0) if there is no parking to get back the previous behavior.
[Edit: actually this is divided by two, so use 4 by default for parking lanes on both sides?]

And btw is there a specific reason for assuming `highway=primary` has `BROAD_LANE`s if no  lanes are tagged, but if lanes are tagged, their width is `LANE`?

**Comment by Helium314** [comment]
https://www.openstreetmap.org/way/827240535
Quest shown on master, but not shown in when increasing the 'buffer' from 4 to 6. And I am **very** sure that in older versions the siedwalk quest did not appear on this road, or I would have solved it a long time ago.

**Comment by westnordost** [comment]
> And btw is there a specific reason for assuming highway=primary has BROAD_LANEs if no lanes are tagged, but if lanes are tagged, their width is LANE?

Well spotted. Yes, this is deliberate. Primary roads tend to be broader than secondary,tertiary,... so this is to pay respect to that. This is the `guess....` function after all.

Anyway, a 4m grass verge is pretty generous still. Basically, the filter is fuzzy, so, whatever we set the min distance to, there will always be cases where it is asked and I think it is okay. `cycleway=separate` is kind of missing anyway.

**Comment by westnordost** [comment]
Also, is the Erdbergstraße really a 3-laned road? Sectionally there are no markings for one or the other or both sides, but looking at the traffic, one can see that it is clearly used as a 4-laned road.

https://www.google.de/maps/@48.1892753,16.4172851,3a,75y,262.73h,64.34t/data=!3m6!1e1!3m4!1sQscK8wVag3rcskcLi7RZIw!2e0!7i13312!8i6656

**Comment by Helium314** [comment]
The linked section has two lanes on one side (straight and turn), and one plus a parking lane on the other side. South east of the nearby bus stops, Erdbergstraße turns into a two lane road with two parking lanes.

**Comment by smichel17** [comment]
> Well spotted. Yes, this is deliberate. Primary roads tend to be broader than secondary,tertiary,... so this is to pay respect to that. This is the `guess....` function after all.

Since the question came up, it may be worth a comment saying this?
