### ISSUE TITLE
Ask for more specific values for office=yes POIs without other top-level tags

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3753]
### General
Affected tag(s) to be modified/added: [office](https://wiki.openstreetmap.org/wiki/Key:office)
Question asked: **What type of office is %s?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - It is possible that it will trigger adding missing `office` values to iD presets or discover other issues in the OSM tagging, triggering new work
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - in some cases may be tricky, but overall I think that it is OK. In some cases adding office type may be doable based on this name.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) - over 70 000 https://wiki.openstreetmap.org/wiki/Tag:office=yes

### Ideas for implementation

See #2391 #2759 which did it for shops

**Element selection:** `office=yes`, possibly exclude ones with top-level tags and tagged on entire buildings, maybe limit to just nodes

**Metadata needed:** iD presets as #2391 #2759

**Proposed UI:**

See #2391 #2759 which did it for shops

**Comment by westnordost** [comment]
- 🤔 The list is of possible values is very very long and obviously open-ended. Doesn't really seem to be eligible
- 🚧 How does it have a useful purpose? I'd predict that the vast majority of all things (still) tagged as `office=yes` are basically private companies / offices that do not fit into any category as presented by the app. Stuff like employment agencies, government agencies, etc. will usually already be tagged more specifically from the start
- 🤔/🐿️ There'll be a lot of cases where there is just the name of the company(?) on the door bell nameplate. What is the user supposed to answer then?

**Comment by agent-redd** [comment]
I can confirm from my mapping experience, that it"s hard to survey the type of an office. 
Maybe just ask for the name of the office, if it isn"t tagged yet?

**Comment by matkoniecz** [comment]
>  Maybe just ask for the name of the office, if it isn"t tagged yet?

This is done already.

I will close, possibly reopen after testing.
