### ISSUE TITLE
Missing translation for playground quest

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3766]
Hi there,

the string "Who is allowed to use this playground?" isn't translated to German (the possible answers are). See the screenshot:

![SC40_playground](https://user-images.githubusercontent.com/32601012/154072050-a0477e63-d5ae-4fc1-ba63-fb83d4f5cc7a.jpg)

I don't find this string on POEditor, so I'd guess it's missing there completely. Maybe something went wrong when switching from "Is this playground publicly accessible?" to this new question string?

SC 40.0, Realme 8 Pro, Android 11.

The cycling cat

**Comment by matkoniecz** [comment]
`    <string name="quest_playground_access_title2">Who is allowed to use this playground?</string>` is not yet present in POEditor, see https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=97843&id_language=55&search=playground

#3712 is the relevant PR
