### ISSUE TITLE
Overlapping text on welcome screen

### ISSUE THREAD

**Issue by jleedev** [streetcomplete/StreetComplete#3767]
**How to Reproduce**
1. Open the app
2. Press "Next" twice

**Versions affected**
Version 40.0, Android 12.

[video]
![screenshot]

[screenshot]: https://user-images.githubusercontent.com/23022/154120140-d6b2f015-3b49-4771-ad1d-9a4a33a1a56f.png
[video]: https://user-images.githubusercontent.com/23022/154119483-0c47e87b-c0f8-4a69-888a-4b4f7ea7fc04.mp4

**Comment by westnordost** [comment]
I just made the next button not clickable while the animations are not done. 

That's easier and less code than trying to cancel / finish all the animations that are going on when going to the next step and the new user is supposed to read the tutorial after all anyway.
