### ISSUE TITLE
Google Play - link to source repository against policy because it contains info on donating

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#3768]
...unless those links lead to their own billing system, which charges a hefty commission. 

The policy doesn't seem to make any difference between "in-app-payment" and donations (to FOSS software, at that) except if the donation is for a non-profit (i.e. tax-excempt) organization. StreetComplete has been displaying links to Patreon, Liberapay and Github Sponsors in-app, so I'll have to remove this.

Furthermore, it was rejected because they write I need to supply login credentials for them. I.e., login credentials for an openstreetmap account. It's a bit absurd, would they request login credentials for an email client too? Or an app that enables you to connect with your google account?

### Message from Google Play

![image](https://user-images.githubusercontent.com/4661658/154077493-bacb4301-99ba-4e6e-bb3c-a875fbb9b188.png)

#### Links:
- [Payments](https://support.google.com/googleplay/android-developer/answer/9858738/) policy
- [Web.archive.org of the same page to see how it changed since 2020](http://web.archive.org/web/2021*/https://support.google.com/googleplay/android-developer/answer/9858738/)

**Comment by westnordost** [comment]
I read the payments policy again yesterday and decided to appeal first because in my opinion, "payment" in paragraph 4 clearly refers to how payment is defined in paragraph 2, not any exchange of money.

#### Appeal

> Issue 1: 
>
> I presume the payment policy you are referring to is
>
>> 2. [...] apps [...] accepting payment for access to in-app features or services, including any app functionality, digital content or goods (collectively “in-app purchases”), must use Google Play’s billing system for those transactions
>> 4. [...] apps may not lead users to a payment method other than Google Play's billing system. [...] 
>
> The donation links do not violate this policy, because no features, services, functionalities, content or goods are exchanged: they are not payments but donations. I.e. all functionality is available without any donations.
>
> Issue 2:
>
> No account is required to use this app. The donations are also not connected with an account. Also, the account is at a third party (OpenStreetMap, e.g. like a Wikipedia account). However, I don't expect you to take me by my word, so I created an OpenStreetMap account for you and provided the details in the prelaunch report settings.

**Comment by westnordost** [comment]
#### Reply

The answer is a bit longer but most is a template, the relevant part in respect of donation links is:

>
> [...]
>
>During review, we found that your app violates the [Payments](https://support.google.com/googleplay/android-developer/answer/9858738) policy. Specifically, Google Play's billing system must not be used in cases where payments include tax exempt donations. You can read through the Payments policy page for more details.
>
>**For example, your app currently solicits donations.** You can refer to the attached screenshot for additional information.
>
>Donations may only be collected within an app under certain conditions:
>
> 1. _The donations are for a validated tax-exempt organization (for example, a validated 501(c)(3) charitable organization in the United States or the local equivalent), and_
> 2. _The donations are collected through a secure payment system._
>
> [...]
>
> **Step 2: Submit your proof of eligibility and/or update your app**
>
> If the donations are for a validated tax-exempt organization, please reply to this email and attach proof of the organization’s tax-exempt status (for example, Internal Revenue Service determination letter for entities in the United States).
>
> Alternatively, if the organization is not a tax-exempt organization, you must remove the donation functionality from your app, or use Google Play's billing system when collecting donations.
> 
> ![de westnordost streetcomplete](https://user-images.githubusercontent.com/4661658/154315615-2b73a9b0-d0a1-4e0a-a20b-355dd48d3758.png)

I'd say this answer confirms that the rejection was not a misjudgement of a reviewer but official policy, because it very much looks like this reply was written with predefined text blocks / templates.

**Comment by westnordost** [comment]
### Update rejected

The update was rejected again, with the usual template text (as in the first message) that it is in violation of the payment policy and without further explanation. However, a screenshot of the current version was attached:
![image](https://user-images.githubusercontent.com/4661658/154922528-0f65c747-fd94-4e22-ab79-6d262abcee1a.png)

### Interpretation

The reviewers are interpreting the [payments policy](https://support.google.com/googleplay/android-developer/answer/9858738/) in the strictest and at the same time most creative sense. Given the last message I got from them, I have to assume this is official (undocumented) policy. The rule most likely be violated would be

> [...] apps may not lead users to a payment method other than Google Play's billing system. This prohibition includes [...] leading users to other payment methods via [...] In-app [...] links [...]

Supplying the link to the project's home on GitHub seems to have been interpreted to be indirectly leading to a payment method. 

This is all quite ridiculous and just one step away from _"(FOSS) projects must keep it a secret from users that they can donate!"_ - which I finally see no basis at all for in the payments policy.

### Action taken

So, I removed the link and explain why I removed the link. By mentioning where to find the information, the dialog still kind of fulfills its purpose but avoids linking anywhere.

![image](https://user-images.githubusercontent.com/4661658/154930110-86ba1283-bd2d-4389-a56f-b3c66e7dd9e9.png)

I know, I could just completely remove that dialog, but I find it worthwile to see where the confines of the (undocumented parts) of the payment policy are. If merely **informing** users about the possibility to donate was expounded to be equal to "leading to payment methods (via in-app links)", then it would at least be interesting to the broader public if that was exposed.
... if it is not already interesting  as-is.

**Comment by matkoniecz** [comment]
I wonder are they going to interpret "mentioning that repository exists and mentioning that donate options are there" as linking and having donate option on repository as "payment method".

**Comment by westnordost** [comment]
This is what we'll find out.

**Comment by michaelblyons** [comment]
That. Is. Absurd.

**Comment by peternewman** [comment]
As @FloEdelmann noticed, it's done the trick :partying_face: :

Version 40.2 seems to be available in Google Play again.

_Originally posted by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/3748#issuecomment-1048232860_

**Comment by peternewman** [comment]
I don't know whether it's worth the hassle of rejection or retranslation, but your message says "even linking to our project home is not allowed", but none of your links on the main page are explicitly called "project home". Would it be worth changing the text to "...source repository..." or vice versa?

**Comment by westnordost** [comment]
Oh, nice, I didn't notice.

**Comment by timothywashere** [comment]
Thank you for your considering supporting this app. Unfortunately, due to Google's illegal anti-competitive policies, we are not allowed to tell you how to support this app with donations. We aren't even allowed to tell you how to get to our project home page. Instead please click on this fart button.

**Comment by westnordost** [comment]
😆 that would be funny, I actually laughed. But I didn't want to be overly salty in that message because the goal of this dialog is to inform users about that they can donate, not to get users upset about Google.

**Comment by timothywashere** [comment]
On a serious note, do you think they would allow something along the lines of
We aren't allowed to ask you for money, but if you want to contribute in other ways, please click on this link to our project home page.

**Comment by westnordost** [comment]
I don't want to gamble. Also, that message sounds like you cannot donate at all.

**Comment by michaelblyons** [comment]
> We aren't allowed to ask you for money _in the app,_ but if you want to contribute in other ways, please click on this link to our project home page.

Maybe? Or is that too close to the knife's edge?

**Comment by timothywashere** [comment]
Is this a new policy of Google?
Were the donate buttons new to SC?

I find this ridiculous and might e-mail a tech news website. Do you mind if I mention SC and link this thread? 
I won't unless it's ok.

**Comment by westnordost** [comment]
Sure, go ahead!

The donate buttons have been added end of 2019, Google Play does not manually review every app update, though.

So, whether the app update was rejected because their [payment policy](https://support.google.com/googleplay/android-developer/answer/9858738/) changed, or whether their official interpretation of the policy changed, or whether it just went under the radar since it was implemented, I cannot say.

At least in 2019, there was [a case](https://news.ycombinator.com/item?id=21268389) where another app update was rejected because it contained a donate button. That case was even mentioned on several tech-news sites. So, even though the policy linked above does not spell out a prohibition of donate buttons (that lead somewhere else than In-App-Purchases), this is no precedent. 
The (minor) precedent here is that linking to the project home was interpreted as "leading users to a payment method", mentioning it in the context of donations.

**Comment by comparesheriff** [comment]
> Is this a new policy of Google? Were the donate buttons new to SC?
> 
> I find this ridiculous and might e-mail a tech news website. Do you mind if I mention SC and link this thread? I won't unless it's ok.

Great Idea!

You could additionally ask Catima if you could include their recent problems with PlayStory Compliance changes to emphasize the ridiculousness:
https://github.com/CatimaLoyalty/Android/issues/439

**Comment by udittmer** [comment]
> Is this a new policy of Google? 

Lots of apps have had this happen. I've had mine rejected twice for using language like "support app development" and "donate via Paypal" etc. Now I just mention that it's possible to gift me something from an Amazon wish list, along with a link to my web page where that is explained. And on that page people will also find a link to donate via Paypal :-)

**Comment by Altonss** [comment]
> I find this ridiculous and might e-mail a tech news website. Do you mind if I mention SC and link this thread?
> I won't unless it's ok.

This issue is cited here https://www.theregister.com/2022/03/02/google_blocks_android_tool/ :)

**Comment by riQQ** [comment]
Aren't the following excerpts from the article a misrepresentation, because all sponsor links point to and will benefit westnordost directly:

> StreetComplete was telling people they could give to OpenStreetMap, but it's not allowed to any more

> [StreetComplete](https://github.com/streetcomplete/StreetComplete), a free Android program designed to help people to contribute to OpenStreetMap, was blocked from Google's Play Store, merely for urging users to donate – to someone else.

**Comment by westnordost** [comment]
Oof, too bad the very premise of the story is wrong. Donations are for maintenance and development of the app by me, not for OpenStreetMap in general.

**Comment by dietmerc** [comment]
> > Is this a new policy of Google?
> 
> Lots of apps have had this happen. I've had mine rejected twice for using language like "support app development" and "donate via Paypal" etc. Now I just mention that it's possible to gift me something from an Amazon wish list, along with a link to my web page where that is explained. And on that page people will also find a link to donate via Paypal :-)

🤔 nothing personal
