### ISSUE TITLE
Ability to change recent edits

### ISSUE THREAD

**Issue by kwoot** [streetcomplete/StreetComplete#3775]
As a newbie I sometimes make mistakes. It happens.

If I could see something like a red dot on an object I just entered data for, I would like to be presented with the same edit choice as before but this time I could enter a more correct value.

Hope this is a clear enough request.

**Comment by matkoniecz** [comment]
Is ability to undo edit sufficient?

Note button in bottom left of the screen.

**Comment by kwoot** [comment]
No, I'm afraid not. It only shows the last edit and not second or third or forth as far as I can tell. Also the gui changes to something that I as a newbie do not understand. A long list of houses on the left side. The rest of the gui is awesome and I love to add data to OSM. Maybe I should RTFM somewhere?

**Comment by matkoniecz** [comment]
> It only shows the last edit and not second or third or forth as far as I can tell

Can you attach screenshot? It should list all recently made edits (older ones may be not shown from what I remember)

**Comment by kmpoppe** [comment]
> Clearly I did not understand what I saw. I will retry.

You could always post a screenshot of the steps you were taking so that we can understand what you're looking at and what you're expecting.

As a longtime IT supporter I'm glad to help you figure it out!

**Comment by matkoniecz** [comment]
Closing, as it appears to be already present. Maybe it is similar case as someone who had damaged bottom-left corner of the screen?

Though it can be reopened if either there is an idea how to improve interface or something is not working.
