### ISSUE TITLE
Porting this application to Ubuntu Touch

### ISSUE THREAD

**Issue by kwoot** [streetcomplete/StreetComplete#3776]
I know, put your keyboard where your mouth is, but this ticket is just a placeholder for those who are interested in porting this application to the Ubuntu Touch operating system for mobile devices.

**Comment by matkoniecz** [comment]
See #2756 #1386 especially https://github.com/streetcomplete/StreetComplete/issues/1386#issuecomment-488432864

> That's too much work. It would be a completely different application. In my opinion, for any new mobile OS, be it FOSS or not, it is imperative that they support running applications written for Android, so mirror the Android API in one way or the other.
The mobile OS market is simply saturated, no software creator will bother creating a completely different application for some per mill of the market share.

In short, that would be a new separate project that would reuse some of assets from StreetComplete. Quest data and graphics could be reusable, all interface would need to be implemented from scratch.

Or running in emulator/compatibility layer of some kind.

**Comment by matkoniecz** [comment]
If you are interested in starting such new project - then you are welcome!

Feel free to announce it in https://github.com/streetcomplete/StreetComplete/discussions

But note that it would be an enormous project and right now StreetComplete supports Android with iOS support in category "requires about year of work", Linux support is not even planned.

**Comment by kwoot** [comment]
Well, as the marketing manager of the UBports Foundation I took the liberty of making this issue and mention this in our biweekly news letter to currently 2672  worldwide subscribers. I know chancer are slim, but I think this project deserves a brave soul who like to dig in. Let's see what happens.
