### ISSUE TITLE
Is this road oneway for bicycles too?

### ISSUE THREAD

**Issue by coolultra1** [streetcomplete/StreetComplete#3778]
### General
Affected tag(s) to be modified/added: [oneway:bicycle](https://wiki.openstreetmap.org/wiki/Key:oneway:bicycle)
Question asked: **Can bicycles pass through this road both ways?**

### Checklist
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

Some oneway streets allow cyclists to pass through both ways. This is tagged by [oneway:bicycle](https://wiki.openstreetmap.org/wiki/Key:oneway:bicycle). I think, asking about this might be nice, as the information is really useful for cyclists.

**Comment by matkoniecz** [comment]
> Not an overwhelming percentage of quests have the same answer (No spam)

How to distinguish oneway roads where it makes sense to ask this?

See also #533

**Comment by matkoniecz** [comment]
Also, it is mostly covered by already present #671

**Comment by FloEdelmann** [comment]
> it is mostly covered by already present #671

What if there is no cycleway, but bicycles may still pass through in both directions? (e.g. traffic signs [oneway, not for bicycles](https://images.gutefrage.net/media/fragen-antworten/bilder/351837449/4_full.png?v=1590609298000) and [entry forbidden, not for bicycles](https://www.hellwegeranzeiger.de/wp-content/uploads/2021/03/630_0900_1645288_IMG_1535.jpg))

**Comment by coolultra1** [comment]
As already said in #533 (which I had overlooked), #671 should cover this mostly... I think?

**Comment by matkoniecz** [comment]
> The cycleway quest only allows answering two-way bicycle lanes or tracks:

There should be entry for cyclists allowed on road in that direction, without separate lane.

May have special phrasing on oneway roads.

**Comment by coolultra1** [comment]
![image](https://user-images.githubusercontent.com/77762440/154757337-847031c3-b020-4ed5-9bc9-f3acfba1ca35.png)
![image](https://user-images.githubusercontent.com/77762440/154757351-6aee053a-2f06-42eb-b0ab-c54b8dd86f4e.png)

German signs for this, btw

**Comment by coolultra1** [comment]
So maybe just add it to the current cycleway quest?

**Comment by matkoniecz** [comment]
It is in the current cycleway quest as far as I know.

**Comment by coolultra1** [comment]
Making this issue entirely useless? Man, I should really look deeper before creating issues.

**Comment by FloEdelmann** [comment]
> It is in the current cycleway quest as far as I know.

No, as I have said, there are only these answers for oneway roads:

![](https://user-images.githubusercontent.com/202916/154754867-6dfe1abc-3335-4a6b-bb80-0a3ccd20fe83.png)

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/253191907 should generate quest and is oneway and should include matching option

**Comment by kmpoppe** [comment]
Bloody auto upload...

It seems the way doesn't generate the cycleway quest :/

**Comment by matkoniecz** [comment]
> It seems the way doesn't generate the cycleway quest :/

Disabling uploads, answering that it has sidewalks, answering 100km/h as speed limit generates cycleway quest with an expected option.

**Comment by matkoniecz** [comment]
third from the top on the right side

![Screenshot_20220218-224414](https://user-images.githubusercontent.com/899988/154765785-3cff586e-fb2f-4ab6-b621-df82d6a943c9.png)

**Comment by kmpoppe** [comment]
Right... What you want to answer @coolultra1 @mnalis @FloEdelmann is this:

For the side ALONG the oneway: None
![photo_2022-02-19_08-57-52](https://user-images.githubusercontent.com/24451207/154792365-c66ac471-9f36-4c28-b73c-f42c887ef921.jpg)
For the side CONTRA the oneway: None, but cyclist may use road in both directions
![photo_2022-02-19_08-57-46](https://user-images.githubusercontent.com/24451207/154792379-6ffaa862-1c69-4728-99a2-d176c07beda2.jpg)

This yields `cycleway:left=no`+`cycleway:right=no`+`oneway:bicycle=no`
![photo_2022-02-19_08-57-57](https://user-images.githubusercontent.com/24451207/154792408-315e5b4a-da05-44a3-98a3-5678cecd2361.jpg)

I find this rather unintuitive, especially as you don't see the direction of the oneway in the UI and thus, if you just happen to select the side ALONG the oneway first, you don't get to see the other option.

If using "no cycleway at all" from "Other answers" you get an ominous infobox "Note all the available options: some cases are not obvious like a oneway road that allows cyclists in both directions!" ...

Maybe an addition to the "Other answers" _only_ for oneways could be something like "No cycleway but allowed on road in both directions" that THEN selects the above mentioned combination by itself?

Kai

**Comment by mnalis** [comment]
Thanks @kmpoppe, that really was unintuitive that the choice is hidden unless other side is marked as `none` first! I hate it when UI elements disappear... 

- **_Couldn't that answer be shown all the time?_**

Also, when chosen, it makes following changes:

```
cycleway:left = no
cycleway:right = no
oneway:bicycle = no
```

- However, as user confirmed the bicycle traffic is explicitly allowed there (due to sign saying so), perhaps **_we should also add_** [bicycle=yes](https://wiki.openstreetmap.org/wiki/Tag:bicycle=yes) in that case? It should be simple and reasonable.
