### ISSUE TITLE
Sport only surface images are a different size to highway surface images

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3780]
On the sports pitch surface quest the images which are unique to sports pitches are a different size to images which are also used in highway surface quests:

![Surfaces](https://user-images.githubusercontent.com/77166354/154768236-4672e7f2-6afc-4449-8503-fa4a6c67b48a.png)

Looking at the different folders of drawables this appears to be the case for all screen sizes

**Versions affected**

Android 10 SC 40 beta 1

**Comment by matkoniecz** [comment]
`mdpi`, `hdpi`, `xhdpi`, `xxhdpi` images are all affected

@mnalis not entirely sure why you have not got this problem (smaller screen?) but images are badly sized. A bit irritating to fix (I need to crop images again) but should be easy to fix.

**Comment by westnordost** [comment]
While you are at it, I noticed some unused surface images you (I think) added some time ago. Maybe you could check if they should be deleted.

**Comment by matkoniecz** [comment]
@westnordost Do you remember which ones were affected or some way to find them? I am pretty sure that I added only ones that were needed and see no good way to detect unused ones.

**Comment by matkoniecz** [comment]
Oh, I found three unused images that were supposed to be used.
