### ISSUE TITLE
Ask about charging station brand, not about charging station operator

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3782]
The problem here is similar to McDonald's: many of them are not actually operated by McDonald's - but are part of franchise and actual operations/risking money etc is done by independent businesses.

Similarly, as soon as there is any charging operator franchise the displayed brand and actual operator will be mismatching.

**Comment by westnordost** [comment]
🤷 IDK, ok. Same with ATMs then too?

**Comment by matkoniecz** [comment]
> Same with ATMs then too?

Maybe? Not sure is franchise ATM a concept that makes sense.

But what user is actually surveying and can check is branding, not an operator - so question and tagging should be about it.

**Comment by 10992-osm** [comment]
> > Same with ATMs then too?
> 
> Maybe? Not sure is franchise ATM a concept that makes sense.
> 
> But what user is actually surveying and can check is branding, not an operator - so question and tagging should be about it.

Several things come up if you perform a web search for "ATM franchise", not least [atmfranchise.com](https://atmfranchise.com/).  I'm not sure what the appropriate tags for these would be, though.

I also have a vague feeling that some supermarkets (/supermarket banks) in the UK might have their own-branded ATMs, but I suspect they don't operate them.  This would have to be checked, though.

**Comment by westnordost** [comment]
So, what about this then?

**Comment by matkoniecz** [comment]
There is one question: what about places where `operator` tag is present, maybe because SC users solved this quest?

I think that quest should be asked again, though it will result in some double surveys :(

I plan to wait a bit for reaction on https://github.com/gravitystorm/openstreetmap-carto/issues/4575 https://github.com/gravitystorm/openstreetmap-carto/issues/4450 https://github.com/osmlab/name-suggestion-index/issues/6158#issuecomment-1156064646 (I may be wrong or missing something)

**Comment by peternewman** [comment]
> There is one question: what about places where `operator` tag is present, maybe because SC users solved this quest?
> 
> I think that quest should be asked again, though it will result in some double surveys :(

Can we not also (a bit like the house name and number quest), have an option to populate both when they're known, like these examples:

> Tesco at least clearly display their name on their ATM, but in slightly smaller letters detail which bank is operating them (which is how I've answered that quest in the past). The ASDA branded ones are actually Barclays when you use them.

**Comment by westnordost** [comment]
ping

**Comment by flacombe** [comment]
It's not clear here if we deal about a brand name or a network.

On https://wiki.openstreetmap.org/wiki/Key:network#Amenities, we can read 

> In conjunction with [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[bicycle_rental](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental) or [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm) or [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station), this key identifies an organization or brand that operates a similar amenity in various other locations.

Should we update the quest to ask for those two properties as to enable mappers to get the difference?
In case of two separate quests "What is the network?" and "What is the operator?", mappers could be confused and put the wrong name inside the wrong property.

**Comment by matkoniecz** [comment]
@westnordost I remmeber about this one, but this would require deciding on tagging and maybe asking community - and I am still processing https://community.openstreetmap.org/t/surface-fine-gravel-is-it-for-loose-gravel-or-duplicate-of-surface-compacted/7533 triggered by surface overlay

**Comment by mnalis** [comment]
ref: https://community.openstreetmap.org/t/streetcomple-asking-for-operator-on-charging-stations/105320

**Comment by westnordost** [comment]
Feel free to reopen  when this becomes actionable.
