### ISSUE TITLE
Tapping off disabled message still enables quest

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3783]
When enabling a 'disabled by default' quest there's a message that pops up with options to enable or cancel.

If instead of tapping on one of the buttons you tap outside of the popup then the popup goes away but the quest is enabled anyway.

This seems counter-intuitive and I'd expect it not to enable the quest.

**Comment by matkoniecz** [comment]
I agree that it is unexpected and it should be rather interpreted as cancelling.

**Comment by mnalis** [comment]
@tapetis I (as an user) would expect that **_rotating the phone does not make any changes to the form_** (i.e. the form should remain displayed in the same state no matter how much phone is rotated). Meaning, the rotation of phone should never answer any question being asked of user nor change the current UI  state (it may of course _resize_ windows as needed, but not remove them or open new ones).

I'm usually running with auto-rotation disabled, but I've enabled it now to test, and it indeed not only _"clicks `OK` button in the name of user"_, but it also resets any "search" of the quests that was in progress, which I would find highly annoying (if I were running in autorotate mode, which luckily I'm not :smile:) 

I'm (as non-android programmer) actually quite amazed that android OS does not handle that as a default case automatically  unless specifically overridden by the app (e.g. I would be shocked if changing screen resolution on my laptop would close any of my open windows and/or randomly assumed answers on open dialog forms).

**Comment by kmpoppe** [comment]
Got an idea ... let me quickly pop up Android Studio ...
