### ISSUE TITLE
Does this cycle path have a sidewalk? (ask only in Netherlands)

### ISSUE THREAD

**Issue by joepie91** [streetcomplete/StreetComplete#3785]
### General
Affected tag(s) to be modified/added: [sidewalk](https://wiki.openstreetmap.org/wiki/Key:sidewalk)
Question asked: **Does this cycle path have a sidewalk?**

Rationale: sidewalks for cycle paths are very common in the Netherlands, but not universal, and seem to frequently be left unmapped entirely. IMO, it would be a good idea to 'extend' the sidewalk question to (standalone) cycle paths as well, at least in the Netherlands.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Same selection logic as for "does this street have a sidewalk", but with `highway=cycleway` instead.

**Metadata needed:** #2644 suggests that the concept of "cycle paths with sidewalks" may be specific to the Netherlands, and not applicable elsewhere.

**Proposed UI:** Identical UI as for the sidewalk question for streets.

**Comment by kmpoppe** [comment]
![Screenshot_20220220_052743.jpg](https://user-images.githubusercontent.com/24451207/154828410-55c9a872-8292-4abe-93eb-5a5053a66c99.jpg)

There's an answer to the existing Cycleway quest that yields the answer `cycleway:*=track` ... Is that what you mean by a "sidewalk for bicycles"?

**Comment by matkoniecz** [comment]
@kmpoppe The quest that you mention is asked on roads without separately mapped sidewalks, @joepie91 proposes asking about sidewalk presence on cycleways which are either standalone or mapped along road.

**Comment by matkoniecz** [comment]
Ways with `foot=designated` and `segregated=yes`, ways with `segregated=no` would be excluded, right?

@joepie91 So it is supposed to improve ways such as [this example](https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg)
![800px-Witosa_bike_2](https://user-images.githubusercontent.com/899988/154829487-d6831d2f-7cda-49c9-a0c4-47cf8d93ecfe.jpg)
which are tagged just as `highway=cycleway` without hint about pedestrian part?

How such ways with just bicycle part would be marked? (pedestrians on such ways may or may be not allowed to walk and be required or not to yield to cyclists) ([example](http://www.polskaniezwykla.pl/web/place/50578,krakow-rowerem-do-tynca.html) below)
![324292](https://user-images.githubusercontent.com/899988/154829574-385c7cce-4682-4937-80d0-bb5ddaa3112a.jpg)

**Comment by kmpoppe** [comment]
> @kmpoppe The quest that you mention is asked on roads without separately mapped sidewalks, @joepie91 proposes asking about sidewalk presence on cycleways which are either standalone or mapped along road.

Must. Stop. Answering. Issues. In. the. Middle. of. The. Night.

Thanks for the clarification, Mateusz!

**Comment by joepie91** [comment]
> Ways with `foot=designated` and `segregated=yes`, ways with `segregated=no` would be excluded, right?

I think excluding `segregrated=yes` is a reasonable constraint, yes. We *do* have some paths in the Netherlands that would qualify as segregated paths (typically former mixed-use paths which had line markings added later, but no kerb), so if a path is explicitly declared as being segregated, it should probably just be left alone.

I'm less sure about `segregated=no`. I'm not sure under which circumstances people would enter that, and I can imagine that at least some of those cases might be "well no, it's a sidewalk, not segregated" - in which case you *would* want to ask about sidewalks, if none are defined yet.

> @joepie91 Is it supposed to improve ways such as [this example](https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg)

More or less. I've just taken a picture of [the bike path behind my house](https://www.openstreetmap.org/way/379626466#map=19/51.72123/5.35846), which illustrates what I mean much more clearly:

![IMG_20220220_142229](https://user-images.githubusercontent.com/1663259/154844912-c40ccb6f-ce42-4571-826e-ac9d985c58fa.jpg)

You'll notice that there's a sidewalk on *both* sides, and one of them is separated. There is no street anywhere nearby; this is an 'artery bike path', a stand-alone bike path that's meant as a central path to travel across the town. So the sidewalks really do both belong to the bike path. This design is not uncommon in the Netherlands.

Mapping this as `segregated=yes` wouldn't make much semantic sense (it's clearly designed *like* a sidewalk!), and there would be no way to represent the separated sidewalk in that at all.

> How such ways with just bicycle part would be marked?

`sidewalk=no`. That shouldn't affect the routability for pedestrians if pedestrian access is not otherwise forbidden on bike paths, as I understand it. The `sidewalk` tag is, AFAIK, purely an additive tag that indicates there is *also* a sidewalk, in addition to the mapped way itself.

**Comment by matkoniecz** [comment]
> Mapping this as segregated=yes wouldn't make much semantic sense (it's clearly designed like a sidewalk!),

Just as a note: in Poland in would be mapped as `highway=path`[1] `bicycle=designated` `foot=designated` `segregated=yes` and someone describing it as cycleway with sidewalk would be very unusual (though they would be likely understood)

One of alternative taggings would be marking as two separate `highway=cycleway` line and `highway=footway` line which would cause problems for quest as proposed here.

[1] `highway=cycleway`  `bicycle=designated` `foot=designated` `segregated=yes`  or `highway=footway`  `bicycle=designated` `foot=designated` `segregated=yes` are also sometimes present.

------------------------------

The important questions are:

- does it make sense to ask such question outside Netherlands?
- is `sidewalk` tag really a good way to record it and worth promoting?
- should it be asked on all `highway=cycleway` without `segregated=yes` and without `sidewalk=*`?

**Comment by joepie91** [comment]
> and someone describing it as cycleway with sidewalk would be very unusual (though they would be likely understood)

Ah, I think that's a cultural difference then. Here pretty much everybody would describe it as a "cycle path with a sidewalk", I can't even really think of how one would describe a segregated path here!

> One of alternative taggings would be marking as two separate highway=cycleway line and highway=footway line which would cause problems for quest as proposed here.

In practice, sidewalks in NL seem to only really be mapped separately when they have a distinctly different shape or noticeable distance from the corresponding street. This also seems to hold true for bike paths. The street-sidewalk quest currently accounts for this by having a "mapped separately" option, and I think it's reasonable to do the same thing here, also for UI consistency.

> does it make sense to ask such question outside Netherlands?

I'm inclined to say "no". The Netherlands has unusually widespread cycling infrastructure, so I don't expect bike-path-with-sidewalk to be 'staple' infrastructure in other countries, and the fact that in both Germany and Poland these would be considered segregated, suggests that NL is indeed an outlier here.

> is sidewalk tag really a good way to record it and worth promoting?

It's my understanding that `sidewalk` tags are preferable for streets where the sidewalk is attached directly or closely to the street, because of the routing complexity that's introduced by having separate footpaths; there's no (standardized) way in OSM to associate a given footpath with a corresponding street. That also makes it hard for navigation software to eg. display the name of a street or path.

> should it be asked on all highway=cycleway without segregated=yes and without sidewalk=*?

In NL, yes, I think so, or at least with similar filters to the street-sidewalk question. I've found there to be rather many of those as well, but I wouldn't consider them *spammy*, because there genuinely are very different answers for different streets. I'd expect it to be similar for cycle paths here.

**Comment by matkoniecz** [comment]
@joepie91 

Is there some Wiki page documenting this `sidewalk` tagging scheme on cycleways? Either in English or local language?

I seem to remember discussing it but unable to track down (see https://wiki.openstreetmap.org/w/index.php?search=sidewalk+cycleway+netherlands or https://wiki.openstreetmap.org/wiki/Key:sidewalk ).

(I want to be 100% sure that it is a tagging scheme that s considered as clearly wanted, and tagging `sidewalk` is considered as desirable)

**Comment by joepie91** [comment]
I don't know of any documentation for `sidewalk` tags *on cycleways specifically*, for that I've simply looked at the usage of this tag on cycleways in NL using Overpass, and determined that it seems to be an established practice here already.

There's some general documentation [here](https://wiki.openstreetmap.org/wiki/Sidewalks#Sidewalk_as_refinement_to_a_highway) about mapping sidewalks as refinement tags, though, and that's from where I'm drawing the rationale for mapping them as refinements rather than separate ways, for example. Various Dutch mappers I've spoken to in the past have also suggested that a refinement tag is the norm for regular streets here. This is also how StreetComplete currently handles street sidewalks, AFAIK.

Following from that, I can't see a reason why this rationale wouldn't be portable to bike paths in NL, at least; they are essentially streets too, just limited to bicycles and the like, and that they are considered a 'path' rather than a 'street' or 'road' seems like purely an OSM-specific technicality :)

(I've been saying "bike path" throughout this issue, but to clarify, I am specifically referring to the *stand-alone* cycle paths which either run alongside a road but are physically detached from it, or which exist independently of any road. Sidewalk tagging would not make sense for a cycle lane on a regular road or street, for example.)

**Comment by matkoniecz** [comment]
I am asking as I want to confirm that this tagging is both desired and documented - partially because StreetComplete can really encourage specific tagging. And because once someone complains I can explain that it was following standard tagging that was both documented and considered as desirable.

**Comment by joepie91** [comment]
Right, that makes sense. Unfortunately I've often found written documentation lacking for Dutch mapping practices in general, but [this](https://forum.openstreetmap.org/viewtopic.php?id=70746) is one thread where the matter is discussed in Dutch, and the consensus there also seems to be that `sidewalk` is the optimal way to tag it ("it provides more directional information" is one stated reason). It also [mentions](https://forum.openstreetmap.org/viewtopic.php?pid=803303#p803303) that the (suspected) reason for the existence of the `segregated` tag, namely a legally-defined German traffic sign, does not have an equivalent in Dutch law.

**Comment by joepie91** [comment]
Ah, I've found [wiki documentation](https://wiki.openstreetmap.org/wiki/NL:Cycleway#Troittoir)!

**Comment by matkoniecz** [comment]
I also added to https://wiki.openstreetmap.org/wiki/Key:sidewalk#Deprecation_of_sidewalk.3Dnone

**Comment by matkoniecz** [comment]
I posted https://forum.openstreetmap.org/viewtopic.php?pid=856305#p856305 - will look at it in few days

**Comment by westnordost** [comment]
Not sure if/why special treatment (=different tagging that the rest of the world) for one country is warranted. It'd require exceptions in just about any data consumer. Including this app, of course. 

I predict this would likely lead to somewhat of a chaos in tagging. Best case scenario is that all cycleways in the Netherlands are both tagged with `segregated=*` **and** `sidewalk=*` or something. I mean, it is not even a prediction. Reading that forum thread, people mentioned that `segregated=*` is only (3x more) widespread in the Netherlands because of some validators (in JOSM etc?) that push `segregated=*` (worldwide). So we already have this.

StreetComplete already does not ask for cycleway segregation if that cycleway has a sidewalk, see #2644.

For emphasizing that a cycleway is really "like a road" and the accompanying footway is "like a sidewalk to that cycleway road", with curb and all, I'd suggest to then just map that as a separate footway (`highway=footway` + `footway=sidewalk`) instead of squeezing this into current tagging. No/very few data consumers will expect a sidewalk tag on `highway=cycleway` and know how to interpret this correctly.

**Comment by westnordost** [comment]
**Some** cycleways in the Netherlands are like this, but certainly not all. For example, the typical cycle track alongside a road is not like that of course. But there is not any way how to distinguish a cycleway that is potentially "like a road" from separately mapped cycleways that run alongside roads.

The result is that potentially every such cycleway will be tagged with `sidewalk=*` which could even be considered wrong in some cases. Additionally, the implementation of this quest itself would be quite difficult because nearby `highway=footway` need to be interpreted as "potentially a separately mapped sidewalk to this cycleway", just like for the sidewalk-quest.
Even if I don't implement this quest myself, I will be the one who will have to maintain it and I will take the blame. I just have to say, that is too complex and I doubt every mapper in the Netherlands will be OK with the tagging this quest would imply.
