### ISSUE TITLE
Show nearby addresses in housenumber quest

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3790]
**Use case**

I'm adding housenumbers on a street with different numbers on each side (usually odds and evens), all of the houses are essentially identical (perhaps semi-detached or terraced) so it's not necessarily obvious exactly where I'm up to just based on rough GPS location and the map.

At the moment I can tap onto the next quest for a house (either street or building levels) and it tells me what number that is and then I can remember that when I enter the next one on that side, but it would be nicer if I could see nearby house numbers when I'm answering the quest and that would save me from making mistakes.

(Obviously for house numbers added enough time ago they show up on the map, but recent ones aren't rendered yet).

**Proposed Solution**

I've played around a bit with this locally and it does seem beneficial, however I'm opening an issue rather than just a PR as I have questions about implementation and not sure if it's wanted anyway.

* In MainFragment add "addr:housenumber" then "addr:housename" to the possibilities for the title of highlighted elements.
* In AddHousenumber add highlighted elements, possibly excluding any shop, amenity, etc.
* Possibly add an icon (smaller version of housenumber quest icon) to use in PinIcons. Here it would need to not return that for shops, amenities etc. so it wouldn't affect highlighted elements for shop quests where no icon is shown

**Comment by smichel17** [comment]
It would also be nice if I could tap on a nearby housenumber to pre-fill that into the form (and then use +/- to adjust). I was going to open a separate discussion about that and it can be tracked separately, but this seems like a good first step towards it.

**Comment by westnordost** [comment]
Worth a try, let's see how it looks
