### ISSUE TITLE
[Feature request] Don't duplicate addresses

### ISSUE THREAD

**Issue by k-yle** [streetcomplete/StreetComplete#3791]
**Use case**

In countries where addresses have been imported as nodes, the StreetComplete Quest `AddHousenumber` is still valuable since it lets mappers associate an address with a building. 

However, this quest causes the address to be mapped twice, since StreetComplete doesn't delete the identical address node when a mapper adds an address to a building. [Example changeset](https://osm.org/changeset/117418094)

**Proposed Solution**

If a user adds an address like `12` `Example Street`, and there is already a nearby address node for `12` `Example Street`, then StreetComplete should delete that node. If that node has other tags, like `addr:suburb` or import-specific tags like `ref:linz:address_id` then those tags would be copied from the node to the building before deleting the node.

**Comment by matkoniecz** [comment]
In this case address node was placed outside building. Is such mapping considered as acceptable and valid in this area?

If yes, it will be necessary to disable address quest there.

**Comment by k-yle** [comment]
> In this case address node was placed outside building. Is such mapping considered as acceptable and valid in this area?

This is how addresses were imported in New Zealand ([example](https://www.openstreetmap.org/edit#map=19/-36.80598/174.75511)), but it is preferred to move the address nodes within the building outline, or merge them into the building.

> If yes, it will be necessary to disable address quest there.

I'm not suggesting that the quest be disabled, since it is useful to have the address tags on the building instead of a node.    
If StreetComplete can't delete the existing node, then we can modify the NZ address conflation tool to delete the duplicate nodes instead.

**Comment by matkoniecz** [comment]
StreetComplete can't delete the existing node - and I see no way to implement it in a reliable way without damaging data in many cases.

**Comment by matkoniecz** [comment]
Would it be OK to close it as "no change made" on SC side?

**Comment by k-yle** [comment]
If StreetComplete can't prevent this from happening then we can make the NZ address conflation tool delete the nodes. I'm suprised that this isn't an issue in other countries though

**Comment by matkoniecz** [comment]
In at least one country address quest was disabled because such addresses were considered as valid. In at least Poland importing addresses and placing them outside associated buildings is considered as a major address import mistake.

**Comment by Helium314** [comment]
There are/were similar issues for France #2427 and Spain #3162
