### ISSUE TITLE
"Create new note" UI uses unusual English

### ISSUE THREAD

**Issue by Eiim** [streetcomplete/StreetComplete#3792]
The "Create new note" UI says "Best write the note in the locally spoken language or otherwise English". Using "best" like this is fairly uncommon, at least where I am (Ohio, so midwestern AmE), usually, an exclamation, and usually quite informal ("Best get going then!"). The "or otherwise English" bit also feels slightly off. I would suggest something like "Ideally, write the note in the local language, or otherwise in English" or "Write the note in the locally spoken language, or alternatively English."

![image](https://user-images.githubusercontent.com/24627058/155052399-42965d85-b064-4f54-9e2e-0d424d03e429.png)

**Versions affected**
Using version 40.0 from F-Droid.

**Comment by matkoniecz** [comment]
I opened #3794 (as PR as I am both not a native speaker and author of this text - thanks for noticing and reporting!)
