### ISSUE TITLE
No suggestions on disused:amenity areas

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3798]
https://www.openstreetmap.org/way/426232580

Using 40.0-beta1, although I get no suggestions whatsoever regardless of what I type.

My assumption in my case, and possibly both, is that the disused aspect of the node/way is impacting on the suggestions/tagging.

_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/issues/3774#issuecomment-1043674065_

No its not related. First check if the issue persists with v40.1 before you open a ticket

_Originally posted by @westnordost in https://github.com/streetcomplete/StreetComplete/issues/3774#issuecomment-1044348982_

It's still present in v40.2 unfortunately.

Possibly the killer clue, the quest marker appears bottom right, rather than the middle of the way/area like you'd normally expect, presumably whatever decides if something is an area doesn't understand it either?

**Comment by peternewman** [comment]
> Possibly the killer clue, the quest marker appears bottom right, rather than the middle of the way/area like you'd normally expect, presumably whatever decides if something is an area doesn't understand it either?

Or maybe that's just because vertex is in the list of options:
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/disused/_amenity.json

**Comment by mnalis** [comment]
Confirm I can reproduce that on that house number `54` on f-droid SC 40.1 (latest version at the moment).

**Comment by Helium314** [comment]
> Possibly the killer clue, the quest marker appears bottom right, rather than the middle of the way/area like you'd normally expect, presumably whatever decides if something is an area doesn't understand it either?

This is strange, I've only seen this (plus highlighting outline only) on relations.
Maybe because the same nodes are used by the building https://www.openstreetmap.org/way/747751383 ?

**Comment by matkoniecz** [comment]
At least corner effect may be related to `IS_AREA_EXPR` - note that this object has no tags that would be recognized by StreetComplete as an area

**Comment by matkoniecz** [comment]
Yes, it is somehow `IS_AREA_EXPR` (maybe iD presets are asked for shoplike matches on way and none match as all are declared to be on areas?)

After adding `disused:amenity` to be considered as an area it works:

![screen](https://user-images.githubusercontent.com/899988/155271790-e779f56d-15ad-4f14-99aa-b56c708e84cf.png)

**Comment by matkoniecz** [comment]
(the tricky part is to solve it generally in way that is not impacting performance - not sure is running IS_AREA_EXPR with each lifecycle prefix is likely to cause issues)

**Comment by peternewman** [comment]
> Yes, it is somehow `IS_AREA_EXPR` (maybe iD presets are asked for shoplike matches on way and none match as all are declared to be on areas/nodes?)

Yeah it looks like it filters based on the type of feature to suggest, based on this:
https://github.com/streetcomplete/StreetComplete/blob/88d71c4a792376d82d5b1863553cf96f551088f7/app/src/main/java/de/westnordost/streetcomplete/ktx/Element.kt#L29-L35

So it's looking for features for LINEs and not finding appropriate ones.

> Not sure what can be done here - support common lifecycle prefixes by repeating this check multiple times with `disused:` etc prefix added? Somehow strip all *: prefixes when passing data to that check? Support just `disused:amenity` `disused:shop` as other are unlikely to appear as quests?

I'd suggest stripping lifecycle prefixes could be the easy fix.

The more involved solution, but probably with fewer surprises down the line, would be to use the iD presets instead of IS_AREA_EXPR to decide on whether its an area or not (based on whether it matches one of them and area is listed, plus the existing closed/multipolygon), then it will always keep up with new tagging styles.
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/disused/_amenity.json

**Comment by peternewman** [comment]
This is indeed working fine now thanks. Initially the pin was still in the wrong place, but a rescan sorted that too!
