### ISSUE TITLE
Update instructions for v41 are obscured and vague

### ISSUE THREAD

**Issue by pigsonthewing** [streetcomplete/StreetComplete#3801]
My Android 11 device just prompted me to update the app. It was updated to v40.2

1. The "what's new" section on the Play Store entry still refers to the changelog for v39.1
2. The actual version history for 40.2 - accessed from within the app - includes, under the earlier v40.0 heading, a note to "manually update after Feb 21!", to v41

Not having used the app for a few weeks, despite making intermediate updates, I had not seen the latter until today.

The latter does not say what is meant by "manually update". It is not clear whether this means:

1. Uninstall the app and reinstall from the Play Store
2. Install by downloading the apk
3. Trigger a manual update from inside the Play store (how?)
4. Something else.

I suspect many people will not see this guidance, and others - like me - will not understand it.

More clarity, please.

**Comment by peternewman** [comment]
Somewhat related, see #3744 .

It just means you will need to go to the Play Store and choose to update SC yourself (if it normally updates automatically), as it will need to prompt for the new permission for Augmented Reality.

**Comment by westnordost** [comment]
v41 will soon follow. The whole update was delayed by 1-2 weeks because of #3768

Do not label things that are not bugs as bugs.

**Comment by pigsonthewing** [comment]
> Please do not label things that are not bugs as bugs.

This repository offers three options for reporting issues. This is neither a feature request nor a quest suggestion.

Inadequate or - as it now transpires - misleading documentation is a bug. HTH.

As the matter is not resolved, it is not clear why the issue has been closed.

**Comment by westnordost** [comment]
You can open a blank issue. The link at the bottom.

I cannot change the changelog of already released versions, hence this part is "will not fix", if you will.

As to the source of this issue, i.e. the confusion triggered by this part of the changelog, the question has been answered, hence the issue is closed.

**Comment by pigsonthewing** [comment]
> I cannot change the changelog of already released version

No. But the changelog of a future version can include a correction.

The Play Store can be updated to show the correct venison and the URL of the latest changelog.

> the source of this issue, i.e. the confusion triggered by this part of the changelog

The source of the issue is not "the confusion caused", which is a symptom (or effect), but the thing - the bug - **causing** the confusion.

Until that and the above are fixed, the issue is not resolved.

**Comment by westnordost** [comment]
> No. But the changelog of a future version can include a correction.

True, noted. If there will be another v40.x

**Comment by Marc-marc-marc** [comment]
suggestion:
make a 40.x version without asking for augmented reality permission in order to have the automatic update.
this version could display a message at the opening to indicate the problem

**Comment by rugk** [comment]
BTW nothing did ask me anything during the update. (Android 12)

Even if, I think all important permissions are runtime permissions nowadays, so an update should not be prevented. In my case the app was installed from F-Droid.

**Comment by westnordost** [comment]
I see,  that's good and interesting to hear
