### ISSUE TITLE
Destination sign quest on highways after intersections

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#3806]
### General
Related issues: #38 (Quest mentioned but not created?)
Affected tag(s) to be modified/added: [destination=*](https://wiki.openstreetmap.org/wiki/Key:destination)
Question asked: **Are there direction signs at this intersection?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [X] 🚧 To be added tag is established and has a useful purpose
 - destination=* has almost 500k uses on ways
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
 - If there is no tag, there is currently no suitable tagging for it. Not sure if "destination=no" would be best.
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
I'm not an expert in overpass, but you would have to select all highways that are passable by motor vehicles and are directly after an intersection. In addition, probably only major roads should be included, such as motorway, trunk, primary, secondary, tertiary.

**Possible Impediments:** 
- If there are multiple lanes the tag destination:lanes and a different UI should be used
- The correct input must be explained to the user (separation with semicolon, no distance information, ...)?
- [destionation:symbol=*](https://wiki.openstreetmap.org/wiki/Key:destination:symbol) would be a helpful addition, but also very complicated. Maybe as an separate quest

**Proposed UI:**
In the quest, a destination sign could appear, in which there is a text field to enter the value.
The sign should be different depending on the road type and country. (Blue, Yellow, White with blue border, ...)
To enter multiple values, it might be easiest if the user simply makes a new line per value and the app then lines up the values with semicolons one after the other.

![destination_sign](https://user-images.githubusercontent.com/3351668/155375009-7e79ba3a-fea6-4359-941f-9afc2051e3b8.png)

**Comment by matkoniecz** [comment]
> If there is no tag, there is currently no suitable tagging for it. Not sure if "destination=no" would be best.

That would be a fundamental blocker.

**Comment by mcliquid** [comment]
> If there is no way to answer "no signed destination" them SC would ask over and over again in the same place

I am aware of that. Currently destination=no is used only 6 times, but could be used for that of course. Or after consultation with the community rather a destination=not_signed.
Also possible would be the use of "destination:sign=no" for this quest.

**Comment by andrewharvey** [comment]
You would need to check for existing `destination_sign` relations https://wiki.openstreetmap.org/wiki/Relation:destination_sign

**Comment by westnordost** [comment]
See @matkoniecz , also
- I doubt it would be acceptable to put this tag at every intersection, even if a destination:signed=no was set. Filtering out candidates for which intersections to ask and for which not to ask would be a very complex and fuzzy filter, resulting in many false-positives
- Looking at the wiki page, it's not that easy - there are destination signs per lane, even destination signs forward / backward and even relations. This is just too much complexity to deal with, it is not worth it even if there was tagging for every case and a good filter to find only places where it should be asked

**Comment by tiptoptom** [comment]
> You would need to check for existing `destination_sign` relations https://wiki.openstreetmap.org/wiki/Relation:destination_sign

According to the wiki, "all approaches can co-exist"

https://wiki.openstreetmap.org/wiki/Relation:destination_sign#Should_I_tag_destinations_using_a_destination_sign_relation_or_directly_on_ways?

**Comment by matkoniecz** [comment]
Yes, but that would be wasting peoples time to survey what is surveyed.

**Comment by Mannshoch** [comment]
Please Rethink this request. I propose to add a destination Question to all motorway_link I don't know any Motorway link without a Sign.

**Comment by mnalis** [comment]
- (related discussion: https://github.com/streetcomplete/StreetComplete/discussions/5035)

**Comment by andrewharvey** [comment]
I've been using the SCEE implementation of this, but find it quite buggy. It asks for destination signs in on segments leading away from an intersection (maybe it didn't get the driving side correct?).

I think overall it would be better to have this as a custom overlay, similar to SCEE's Turn Restrictions overlay. Allowing users to select the from/to ways then tag at the destination sign details into a `type=destination_sign` relation.

**Comment by mnalis** [comment]
> I've been using the SCEE implementation of this, but find it quite buggy. It asks for destination signs in on segments leading away from an intersection (maybe it didn't get the driving side correct?).

It would be nice to report the problem there if you didn't already @andrewharvey , if there is a bug (instead of inherit limitation due to lack of data), perhaps it might be fixed and quest made more usable. 🤷‍♂️
