### ISSUE TITLE
Übernahme der Straßennamen klappt nicht zuverlässig

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#3810]
Die Übernahme der Straßennamen klappt nicht zuverlässig.

**How to Reproduce**
Teilweise muss ich an verschiedenen Stellen auf die Straße tippen, bevor der Straßenname übernommen wird.

Manchmal muss ich ich den Straßennamen von Hand eingeben

**Versions affected**
v40.2 (Gerät: coral Pixel 4 XL)

**Comment by kmpoppe** [comment]
Wurde mit #3797 schon gemeldet und von Autor gelöst, ist aber noch nicht im Release.

**Comment by OpenGreenStreet** [comment]
@kmpoppe. okay, vielen Dank für Deine Rückmeldung
