### ISSUE TITLE
Allow tagging tactile_paving=incorrect for when only one side of a crossing has it

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3813]
**Use case**
It affects also crossing ques, but is `no` really correct when only one side has paving?

_Originally posted by @matkoniecz in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1039607154_

Probably `incorrect` is the right thing there. The wiki has "or if only one sloped kerb at a crossing has tactile paving" as an example of `incorrect`.

_Originally posted by @arrival-spring in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1039612736_

OT, but I'd appreciate some clarity/a new option for this (I normally just tag no as it's not yes). Also on a crossing with an island, if its only on either side but not on the island which is right?

_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1040544178_

There was a bit of a discussion here: https://github.com/streetcomplete/StreetComplete/issues/2738

I'd support having an other answers button of "Tactile paving only at the top or only at the bottom" and similarly for the crossing quest "Tactile paving only on one side" which would tag `incorrect` after a confirmation.

_Originally posted by @arrival-spring in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1040650287_

See also #2738 .

I appreciate incorrect is low usage currently (0.11%) but I don't know about others but I'd certainly have been tagging no when it's only on one side (given "Does this crosswalk have tactile pavings on both sides?") although I'm not sure how many of those I've had. 

As mentioned I've also been tagging no if it's on the kerbs but not on the island as it's not on both sides of the two crossings, but I appreciate that probably needs a more general tagging discussion to find out what is the "correct" answer, or asking a blind person. @matkoniecz do you have contacts/feedback from your tactile maps?

**Proposed Solution**
Add an other answer for only on one side of the crossing

**Comment by matkoniecz** [comment]
See also https://wiki.openstreetmap.org/wiki/Talk:Key:tactile_paving#tactile_paving_only_on_one_side

**Comment by westnordost** [comment]
Okay, so add the option "Only one side" and tag that as `incorrect` then?

**Comment by matkoniecz** [comment]
Yes.

**Comment by RubenKelevra** [comment]
In the past I answered this with 'no' (we have a lot of them here). Do we resurvey them, so a 'no' can be improved to an 'incorrect' over time?

**Comment by matkoniecz** [comment]
Resurveying all makes no sense, but you can for example remove such tagging in your nearby area and map them again if you think that many were mistaken (JOSM and level0 are likely to be useful).

Or use Vespucci on noticing places like this to retag.

**Comment by Cj-Malone** [comment]
Tactile paving is resurveyed, for a "no" it's 4 years since last edit by default. If StreetComplete is set to resurvey more often it goes to 2 years.
