### ISSUE TITLE
Bollard type quest should allow retag barrier type

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#3817]
I just had a "barrier bollard type quest" but had a boom barrier in front of me.
So imo it would be nice if there were a menu entry:
Other/is different barrier
To trigger the existing barrier quest.

**Comment by arrival-spring** [comment]
That would seem to be consistent with other quests, to have such an option in 'other answers'.

**Comment by kmpoppe** [comment]
By now, using @matkoniecz 's ent8r request, there are 44 notes where people couldn't answer this quest.

So maybe it's worth the effort implementing the "other option" now?

K

**Comment by matkoniecz** [comment]
It seems a good idea to me.

**Comment by mnalis** [comment]
Sooooo, does all that mean someone is volunteering to work on it? :smile: 

(If nobody else wants to do it, I can probably give it a try at weekend...)

**Comment by matkoniecz** [comment]
@mnalis Feel free to implement it!

(I plan to do something today with one of cases where I volunteered: https://github.com/streetcomplete/StreetComplete/issues/assigned/matkoniecz )

**Comment by mnalis** [comment]
Implemented. I'll also make another PR for similar option for `cycle barrier type` quest (with `not a cycle barrier` other answer)
