### ISSUE TITLE
Google Play: "This app is not compatible with any of your devices"

### ISSUE THREAD

**Issue by tastrax** [streetcomplete/StreetComplete#3820]
Is there some reason why these devices are no longer compatible? Running 39,1 and cant get any more recent updates

**Comment by matkoniecz** [comment]
Are you running F-droid or Google Play or Github Release?

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/StreetComplete/discussions/3819#discussioncomment-2264442

**Comment by matkoniecz** [comment]
I get

> This app is no longer compatible with your device. Contact the developers for more info

**Comment by westnordost** [comment]
I need more information. Why does the Installation fail?

**Comment by westnordost** [comment]
FYI the app was tested on non-AR-capable devices and it installed just fine. To people who can test with non-AR-capable devices:
- what if you install the debug version? Same issue?
- what if you uninstall first, then reinstall? Same issue?
- what if you download and install the release from github? Same issue? If yes, do you have any way to ascertain more information about why install failed? Maybe something in the system log?

**Comment by westnordost** [comment]
Actually, also for me, the app does not appear in the Play Store anymore. When I access the store via the browser, it claims both that it is installed and that it is not compatible.
![Screenshot_20220228-134850_Firefox](https://user-images.githubusercontent.com/4661658/155986342-4bf510b8-f373-4c91-a49a-23d70ee558c2.jpg)

**Comment by julietkilo** [comment]
In Google Playstore I didn't got a match searching for streetcomplete. Following the direct hyperlink to streetcomplete in Google playstore I got the message "app not available for your device". After downloading APK from github I can successfully run AR quests on my device:  LG G8ThinQ, Android 11.

**Comment by westnordost** [comment]
Amyone know if there is a public bugtracker for Google Play?

**Comment by ricloy** [comment]
AFAIK, there are two type of messages that Google Play might show: "This app is no **available** for any  of you devices" and "This app is not **compatible** with any of your devices". I get the first one and one of my devices is AR compatible (it's listed in https://developers.google.com/ar/devices).

**Comment by scaidermern** [comment]
Same problem for me. Installed version is 40.2 from PlayStore. Update not possible ("app is not compatible"). Device is Samsung S9 running Android 10 / LineageOS 17.1.

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/156003427-413d3809-1993-4000-ad78-bd19730e6716.png)

**Comment by svenpilz** [comment]
Also can no longer find it in the Play store. Direct link says it is not compatible with my device. Tested with a Google Pixel 5 running Android 12. Currently 40.2 is installed.

**Comment by westnordost** [comment]
v41.1 released, the app should show up again as soon as it is through review

**Comment by westnordost** [comment]
Just after releasing v41.1 I noticed that OpenGL ES 3.0 is actually not required but optional (only if AR measuring stuff is used). Not sure how many users have such old devices<sup>1</sup> but anyway, the next minor update will also lower the minimum required OpenGL ES version back to 2.0.

<sup>1</sup> According to Android documentation, (at least) devices originally built for Android Ice Cream Sandwich (Android 4.0) are affected.

**Comment by tastrax** [comment]
Thanks - I will wait for the new release and see how I go (For info - my case was via GooglePlay store)
