### ISSUE TITLE
Can't see again a quest after undoing it

### ISSUE THREAD

**Issue by tuxayo** [streetcomplete/StreetComplete#3829]
**How to Reproduce**
- "is this camera still there?"
- answer no
- undo
- quest doesn't show up again

even after redownloading the area

I don't know if it happens every time.

**Versions affected**
40.2

**Comment by HolgerJeromin** [comment]
Duplicate of #2861

**Comment by matkoniecz** [comment]
Yes, it is ugly but right there is no good idea how to fix it.
