### ISSUE TITLE
Disable width quests for placement=transition

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#3833]
[placement=transition](https://wiki.openstreetmap.org/wiki/Tag:placement%3Dtransition) is used on a short piece of way joining two different pieces of road/cycleway. It's width can not easily be measured. So the with quest should be disabled for those pieces.

![Screenshot_20220303-204132_1.png](https://user-images.githubusercontent.com/42044179/156640981-2e50509f-b10a-4066-b8e9-7a8f17326290.png)
a `placement=transition` piece of road

![Screenshot_20220303-203725_1.png](https://user-images.githubusercontent.com/42044179/156641208-09375e7a-58bc-426a-8002-66a8484654ae.png)
a `placement=transition` piece of cycleway

**Comment by westnordost** [comment]
First time I hear of that tag. But if it is supported by JOSM, it seems to be fine.
