### ISSUE TITLE
Disable shoulder quest for junction=roundabout

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#3834]
Roundabouts often have an inner circle which is used by trailers of long vehicles.
![Screenshot_20220219-100953_1.png](https://user-images.githubusercontent.com/42044179/156642056-93423400-96b6-4b42-acf4-03148276fdb1.png)
They look similar to shoulders so people may tend to answer the shoulder quest incorrectly. True roundabouts never have shoulders in my experience (you shouldn't stop a car right within a junction), so the quest may be disabled there.

However, it should not be disabled for `junction=circular`. Circular junctions other than roundabouts are diverse, so there may be some with actual shoulders.

**Comment by westnordost** [comment]
I don't see an inherent reason why no roundabout could have a shoulder. Roundabouts are not that common that it is spammy asking shoulders also for them.
