### ISSUE TITLE
Google Appstore shows v39.1 release notes

### ISSUE THREAD

**Issue by FredericBourgeon** [streetcomplete/StreetComplete#3836]
In the "What's new" section of the Google AppStore, the link to the v39.1 release notes is available.

This does not match the latest version available through the appstore.

**Comment by westnordost** [comment]
Not for me, it doesn't.

![image](https://user-images.githubusercontent.com/4661658/156759268-b0bca34c-387f-459a-b7e4-266290e457ae.png)

**Comment by westnordost** [comment]
In any case, I checked, the link supplied in the google play console is correct, so if it displays something else for you, it is a google play store issue.
