### ISSUE TITLE
elementFilter syntax - and/or precedence

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3838]
**Use case**
Less confusing `elementFilter` syntax - @mnalis run into it when making their PR (see https://github.com/streetcomplete/StreetComplete/pull/3789#pullrequestreview-894601577 )

**Proposed Solution**

1) ensure that SC will crash on start (or at least on quest scan) with error when one of filters is in `a or b and !c or !a` - and allow `(a or b) and (!c or !a)` or `a or (b and !c) or !a`
2) add precedence of `and` over `or` in `elementFilter` syntax
3) document this `elementFilter` behaviour

**Comment by matkoniecz** [comment]
@westnordost Have you maybe tried (1) or (2) and turned out to be irritatingly complex or consider either of this solutions as poor idea?

(asking as I did zero coding with `elementFilter` parser so far)

**Comment by westnordost** [comment]
This is wrong. There is operator precedence. 

`a or (b and c)` is equivalent to `a or b and c`
