### ISSUE TITLE
No AddLanes quest for motorway and trunk roads lacking a surface tag

### ISSUE THREAD

**Issue by kidhanis** [streetcomplete/StreetComplete#3849]
The **AddLanes** quest is shown only on ways that satisfy `surface ~ ${ANYTHING_PAVED.joinToString("|")}`, but **AddRoadSurface** excludes roads that are very likely to have lanes.
https://github.com/streetcomplete/StreetComplete/blob/727e46f57528eed6a89e1025d9f5f6739091e271/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddRoadSurface.kt#L53-L54

### Observed behavior
The lane quest won't show up for trunk, trunk_link, motorway, and motorway_link unless surface info is added from outside StreetComplete.

### Expected behavior
The lane quest shows up for these four highway values regardless of their surface tag.

**Comment by matkoniecz** [comment]
It applies also for two different quests, nice find!

Congratulations for reporting!

**Comment by HolgerJeromin** [comment]
> Expected behavior
> The lane quest shows up for these four highway values regardless of their surface tag.

I think the commit changes to add motorway to some quests. I think it was deliberate that they are excluded.

**Comment by matkoniecz** [comment]
Which ones? [AddProhibitedForPedestrians.kt](https://github.com/streetcomplete/StreetComplete/commit/42b5b5d81c79e1cfc7c1f49daef8d86fe03e3797#diff-e531b2d4b7959c42a2d17dd5bc49b3bfa1075333020d8b8661850822093d9091) still has `and highway ~ trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified` filter - so `highway=motorway` may now be passing "is now paved" check but will be excluded anyway

**Comment by HolgerJeromin** [comment]
Ah. Missread the diff. Sorry for the noise :)
