### ISSUE TITLE
cycle_barrier quest: unclear whether cycle_barrier=single also applies to multiple cycle barriers

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#3852]
**How to Reproduce**

You get this cycle barrier quest:
![barrier-single-node](https://user-images.githubusercontent.com/11966684/157050031-10eb3e75-1133-469e-9f8d-6697a9d7cba1.png)

The first answer possibility is describes as "two barriers" and there are others where the number of barriers matters (i.e. the one with three barriers).

Now, you however see a barrier that is the same, but multiple barriers. Barriers that are just like `bicycle_parking=stands`, but **not** used for parking actually – but well… as a barrier. And you can actually quite easily (you may slow down with a bike) get through them easily at multiple positions.

Here is a sketch:
![barrier-multiple-ones drawio](https://user-images.githubusercontent.com/11966684/157052336-459838f8-fc2f-4fd1-9909-aa6d2738267c.svg)

original drawIo file, if someone wants to modify that: 
[barrier-multiple-ones.zip](https://github.com/streetcomplete/StreetComplete/files/8198361/barrier-multiple-ones.zip)

Maybe the wording could be improved here?

Or is there a better tagging scheme and you want a "Other answer" -> "There are multiple barriers" and then you maybe can choose whether there is enough space between them to get through?

**Versions affected**

v41.1

**Comment by matkoniecz** [comment]
> IMO this is the first answer, as you reach the barriers are at the same time.

This seems to be a clearly matching tagging, maybe it would be possible to make it more clear for SC mappers...

**Comment by westnordost** [comment]
Can you make a photo of the situation? I don't understand the situation you describe.

**Comment by rugk** [comment]
Unfortunately I cannot. What is missing about the description/pic I "draw" (:upside_down_face:) there?

Edit: I edited the relevant sentence a bit, a "not" was missing e.g.

**Comment by westnordost** [comment]
Or you have the location on openstreetmap?

**Comment by legofahrrad** [comment]
This issue comes from OSM Note https://www.openstreetmap.org/note/2988479 and https://www.openstreetmap.org/note/3022412. There is also one photo:
![77452](https://user-images.githubusercontent.com/92865620/157116206-0485ccf6-eb8c-45b4-8ca4-b3477c8dc1af.jpg)

**Comment by rugk** [comment]
Ah there was a picture, sorry, did not notice that…

**Comment by westnordost** [comment]
Ah, I see. I was confused as to whether each of those "cycle barriers" would be each be mapped as a single cycle barrier.

Looking at the current text however "Durchgang zwischen zwei Barrieren" seems to be clear enough. From the choices offered, that is the thing that would fit the most. I think the only reason why there is doubt at all is because there is doubt as to whether this is actually a cycle barrier at all.

But anyway, I think an actionable change is to change the wording from "...two barriers" to just "...barriers".
