### ISSUE TITLE
More clarity around hospital and medical facility types

### ISSUE THREAD

**Issue by RayBB** [streetcomplete/StreetComplete#3868]
Apologies if this is already documented somewhere but from reading the wiki and readme I couldn't find the answer.

I keep up with notes for Florida and noticed this user had many similar questions/problems about how to label places.

How should this user handle more specific medical places?
Examples:
* "Surgery Center. Do I call this a hospital?" - [note](https://www.openstreetmap.org/note/3084164#c6606545) 
* "I called it a hospital but it is a nursing home. How should I enter it?" - [note](https://www.openstreetmap.org/note/3084169#c6606550)
* "Not hospital but building with a bunch of medical specialist. What do I call it?" [note](https://www.openstreetmap.org/note/3084170#c6606551)
* "Not hospital but eye specialist. What do I call it?" - [note](https://www.openstreetmap.org/note/3084171#c6606552)
* "Not hospital but health specialist." - [note](https://www.openstreetmap.org/note/3084172#c6606553)

**How to Reproduce**
I can just read the users notes

**Versions affected**

Unknown

**Comment by westnordost** [comment]
Well, there is an ongoing misunderstanding what actually is asked in the quest that asks for the building type:

It is only the building type that is asked for, not whatever exact amenity is inside this building. A hospital or dedicated medical facility will have a unique layout, i.e. it has been constructed for that purpose. A building with many doctors etc. inside could as well be an office building (or even an apartment building).

You cite 5 notes, but they are all by the same person. So it should just be explained to that person that it is not about the amenity inside but just the type of building. Also note that it is possible to select "public building" (the "category") if it is not possible to determine it more specifically and/or it is something else than anything listed in that category but still somehow a public building (~an amenity)

**Comment by smichel17** [comment]
See also https://github.com/streetcomplete/StreetComplete/discussions/3558
