### ISSUE TITLE
House number validator rejects slash-laden house numbers in Vietnam

### ISSUE THREAD

**Issue by 1ec5** [streetcomplete/StreetComplete#3872]
The address quest requires a relatively rigid format for `addr:housenumber` that allows a single slash but requires a single digit or single letter to follow it:

https://github.com/streetcomplete/StreetComplete/blob/88d71c4a792376d82d5b1863553cf96f551088f7/app/src/main/java/de/westnordost/streetcomplete/quests/address/HousenumberAnswerValidator.kt#L5-L6

This doesn’t work for the vast majority of urban addresses in Vietnam. Vietnam’s urban address format includes house numbers that resemble a POSIX relative file path that starts from a lane off an arterial road and recurses through each alley until you reach the destination. For example, this is a [valid address](https://congan.com.vn/doi-song/song-o-noi-so-nha-dai-hon-so-chung-minh-thu_36586.html):

> Số 1806/127/2/6/15/48/2A Huỳnh Tấn Phát
> Khu phố 6, thị trấn Nhà Bè, huyện Nhà Bè
> Thành phố Hồ Chí Minh

translation:

> Number 1806/127/2/6/15/48/2A, Huỳnh Tấn Phát street
> Ward 6, Nhà Bè town, Nhà Bè district
> Ho Chi Minh City

or more verbosely (but no one would write this):

> Number 2A, alley 48, alley 15, alley 6, alley 2, alley 127, alley 1806, Huỳnh Tấn Phát street
> Ward 6, Nhà Bè town, Nhà Bè district
> Ho Chi Minh City

There’s even a word for the most deeply nested addresses, [_siêu xuyệt_](https://en.wiktionary.org/wiki/siêu_xuyệt#Vietnamese), but 2–4 slashes are not at all uncommon.

StreetComplete would be very helpful for surveying addresses in these dense neighborhoods, since it’s very difficult to collect them more systematically. [Sometimes these addresses even get deleted](https://www.openstreetmap.org/changeset/59631625) by Westerners who are unfamiliar with Vietnamese addressing and mistake them for vandalism or botched imports.

/ref https://github.com/openstreetmap/iD/pull/4235#discussion_r133900734

**Comment by 1ec5** [comment]
Incidentally, “bis” is also a common alternative to “B” as a house number suffix (like in French).

**Comment by FloEdelmann** [comment]
There is a file that allows additional house number regexes per country:
https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/additionalValidHousenumberRegex.yml

"bis" is already allowed there for France.

Would you like to try writing a regex for Vietnam, testing it and creating a PR?

**Comment by westnordost** [comment]
If housenumbers are basically driving directions, can they be expected to be seen on housenumber signs?

**Comment by 1ec5** [comment]
Yes:

[![](https://image.thanhnien.vn/w2048/Uploaded/2022/dcxpcwvo/2017_07_27/4_kjbh.jpg)](https://thanhnien.vn/hem-sai-gon-ke-chuyen-dac-san-sieu-xuyet-khien-dan-buon-khong-ten-post682914.html)

There are potentially multiple routes to the destination, but this is the one that’s signposted because of how parcels have been subdivided over time.

**Comment by matkoniecz** [comment]
@1ec5 are these your photos? If yes, would you agree to publish them on some free license?

**Comment by westnordost** [comment]
Mateusz doing necro-maintenance :-P

Is this a result of some TODO list you found on an old computer? X-)

**Comment by 1ec5** [comment]
No, I linked both photos to their sources, from Vietnamese news sources. But [this forum post](https://community.openstreetmap.org/t/addrcorner-or-addr-street2/109598/19) contains some openly licensed examples from KartaView.

**Comment by matkoniecz** [comment]
> Is this a result of some TODO list you found on an old computer? X-)

kind of

I have some OSM-related media, I am archiving/deleting/putting them on https://codeberg.org/matkoniecz/OpenStreetMap_-_presentation_materials
