### ISSUE TITLE
Separated cycleway/footpath surface quest

### ISSUE THREAD

**Issue by owiecc** [streetcomplete/StreetComplete#3875]
A separated path with fully defined surfaces is still shown as a path surface quest. See e.g. https://www.openstreetmap.org/#map=19/57.01065/9.94684 with these tags: 
```
highway=path
separated=yes
bicycle=designated
foot=designated
cycleway:surface=asphalt
footway:surface=paving_stones
```
Tagging after [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath). 

`highway=path` + `separated=yes` should ask separately for surface of footway and surface of cycleway.

**Comment by matkoniecz** [comment]
`separated=yes` is barely used, it should be `segregated=yes`

https://taginfo.openstreetmap.org/tags/separated=yes

> Tagging after [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath).

This tag is not mentioned here.

`segregated=yes` is

**Comment by owiecc** [comment]
My mistake. I did not even see these as different words. They were nor segregated in my mind ;)
