### ISSUE TITLE
SC asks for building-type, though defined via building:part

### ISSUE THREAD

**Issue by MaestroGlanz** [streetcomplete/StreetComplete#3881]
I just want to mention a case, where a building is sectioned into two parts inside with two house numbers.
Ludwigstraße 34 and 36 Traunstein

Building types are each defined by the subtag "part". The general outline is just tagged as building. 

Please have a short look, if this is a tagging error or an error in SC.

**Comment by matkoniecz** [comment]
I believe that in such case

- ideally `building=` also would be tagged with specific value
- it would be really hard to exclude such cases
- such cases with `building:part` having specific value and fully filling `building=yes` are really, really rare

so current behavior is OK
