### ISSUE TITLE
Improve building=terrace 

### ISSUE THREAD

**Issue by osmlover** [streetcomplete/StreetComplete#3882]
- It is not necessary to offer the quest building=terrace in the Netherlands.
- Furthermore the description of building=terrace should be extended.

### Motivation for deactivation of building=terrace in the Netherlands:
All buildings in the Netherlands are imported from the so called BAG (some kind of cadastral office for the Netherlands).
That way all individual buildings in a row of terraced houses are automatically mapped individually.
For this reason building=terrace is not needed in the Netherlands and shouldn't be used. It only leads to errors in OSM.
In fact, I corrected numerous incorrectly mapped building=terrace  last month.

### Motivation for improvement of the description worldwide:
First of all, I must confess that I myself have mapped houses incorrectly. It turned out that this was done also other users in the Netherlands  as well. Most of them had used StreetComplete.
A quick search in Germany revealed a similar picture. For example https://www.openstreetmap.org/way/403080845/history, https://www.openstreetmap.org/way/226115006/history and https://www.openstreetmap.org/way/421876104/history .
I assume a change of the description would help to prevent such an error in other countries as well.

**Here is my proposal for the description:**

**Old description:**
Row houses
a linear row of similar single-family homes

**New description:**
Row houses
a linear row of similar single-family homes;
for a single house in such a row use HOUSE

### Further Information:

I proposed such changes in the Dutch Forum one month ago (https://forum.openstreetmap.org/viewtopic.php?id=74992).
There are only some replies, but it has been read by several hundred users and no one has opposed it.
Here is the translation:

**Member lyctkel:**
Hi,
in the last few days I have corrected numerous incorrectly indicated terraced houses (building=terrace).
(There were also some leisure=outdoor_seating among (terrace<>terras) :-) ).
The vast majority of them were made by mappers with StreetComplete.
A few days ago, I was informed by A67-A67 that in NL all terraced houses are indicated as building=house (with data from the BAG).
I think it would be useful to hide the option building=terrace in StreetComplete in the Netherlands. Something like this could be made by StreetComplete country dependent.
My questions to you:
- Do you think the suggestion to request a change in StreetComplete is correct?
- Has anyone contacted the developer(s) and asked for a change?
  I remember that somewhere on the forum there was a question from the developer(s) to the Dutch community.
- Does it make more sense to contact them via the forum or the bug tracker?

**Member emvee:**
Yes, I think it would be good if StreetComplete changes the default (for the Netherlands).
See also BUGs StreetComplete.

**Member A67-A67:**
To be clear, the tag building=terrace is meant for a row of row houses mapped as one way, not an individual row house as they are mapped in the Netherlands. With StreetComplete, this difference does not seem clear to mappers.

**Comment by matkoniecz** [comment]
See also #3793 #1973

**Comment by osmlover** [comment]
Hi,
I withdraw my request to **change the description**. 
This is already discussed in the mentioned issus and have escaped my attention when reporting. Sorry I am a beginner with GitHub. 

However, I would still like to keep the other request to **deactivate the quest building=terrace in the Netherlands**  open.

**Comment by mnalis** [comment]
@osmlover perhaps a better Dutch translation which clearly notes that it is not for single houses (like it was done for German language in linked tickets) would be good solution? You can contribute better translation(s) yourself by clicking hamburger / `About` / `Help translate this app` in the StreetComplete app.

(e.g. there are no Pagodas in Croatia for example, but it is likely too much work to tailor a list of answers for each country specifically, especially if misunderstandings could be more easily avoided with better translation so it is clear what is offered by which answer - and not only that, but better translation would also help Dutch people outside of Netherlands when solving quests is countries where terrace buildings exist)

**Comment by westnordost** [comment]
Thank you @mnalis, this is my view as well. It would be a bottomless pit (of maintenance work) to establish different sets of allowed values for tags for different countries and regions. So this is not going to be done.

If you think what is there now (quite clear description for terrace-houses + mention in description of `house`) is not enough, maybe adding in parenthesis in the Dutch description for terrace-houses is a good compromise.

**Comment by osmlover** [comment]
@mnalis and @westnordost
I do understand, you have a much better overview of the code and the effort to make changes than I do. I had assumed it would be easy to do a country specific deactivation of a tag.
The suggestion to change the dutch description is good. 
I use StreetComplete in the English version so I was not aware of the problem. Since I am not a native speaker I will not do any translation. A good and compact translation I better leave to the native speakers. I will post the suggestion in the thread in the dutch forum. 
Thanks for StreetComplete.
