### ISSUE TITLE
Does this vending machine still exist?

### ISSUE THREAD

**Issue by gdprdatasubect** [streetcomplete/StreetComplete#3886]
### General
Affected tag(s) to be modified/added: [Tag:amenity=vending_machine](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dvending_machine)
Question asked:
**Does this vending machine still exist?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation
Check for last edit date or check date, if more than 3 years ago ask question

**Element selection:** 
Yes: Set new check date
Yes, but not here: Open new note
No: Delete node or open new note

**Metadata needed:** 
None

**Proposed UI:**

**Comment by westnordost** [comment]
It is already asked. Every 4 years for `parking_tickets`, `public_transport_tickets` vending machines and every 2 years for any other vending machine. It is not asked for `fuel` vending machines.

**Comment by westnordost** [comment]
See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L25

**Comment by JLZIMMERMANN** [comment]
It would be better to push **survey:date** (almost ~objects in OSM)  than check_date [about ~300K objects in OSM)
![image](https://user-images.githubusercontent.com/4929752/158812501-a368c19d-d059-42b6-b9cd-b24c08a53cb7.png)
![image](https://user-images.githubusercontent.com/4929752/158812755-92204fb4-ea6c-4c0d-b443-25a05a2c0a3a.png)
