### ISSUE TITLE
Quest list CSV questions/irregularities

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#3887]
**How to Reproduce**

I used/downloaded the file here:
https://github.com/streetcomplete/StreetComplete/actions/runs/1998418078

Now I opened it and looked at the "existence" quest:
![image](https://user-images.githubusercontent.com/11966684/158899211-69c826e9-9f9b-417e-8bfa-4b68a482f7e6.png)

* which [clearly exists in the wiki](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#existence)
* …but is included as [not being found in the wiki, see:
  ![image](https://user-images.githubusercontent.com/11966684/158899398-0a6730db-7866-46f5-9a35-030d0dcd7606.png) 
* but at the same time is correctly found as being in the wiki:
  ![image](https://user-images.githubusercontent.com/11966684/158899482-54ed3032-74b3-46e5-af88-ee0cea98a5a8.png)

Should not it verify/combine the existence by using the package name?
![image](https://user-images.githubusercontent.com/11966684/158899626-e7b1387c-dced-46ee-a3a5-6eeeb1e7f0d2.png)

…or is the issue it doe snot detect and can thus combine the quest name?

This seems to happen for a lot of entries, 50 ones do not have a quest name entry and are only detected as being in the wiki.

**Comment by rugk** [comment]
Ahhhh AFAIK it uses the question title to detect it and [since v42](https://github.com/streetcomplete/StreetComplete/releases/tag/v42.0-beta1) generalized and changed so much titles by removing the `[…]` placeholder stuff etc., they are now misdetected.

Thus, this is mostly a wiki maintenance task…

**Comment by FloEdelmann** [comment]
Exactly: It detects that some quest titles in the wiki do not match any quest titles in the repo. And that there are quests in the repo whose titles do not match any quest titles in the wiki. It's up to the wiki editor to recognize that some quests just have an updated title, and thus make the same changes in the repo.

**Comment by rugk** [comment]
I am at it…

**Comment by rugk** [comment]
Oh I see problems coming though now given multiple quests share the same question title being asked now… :astonished: 

(see "Is this place wheelchair accessible?")

**Comment by FloEdelmann** [comment]
I added a workaround for that in https://github.com/streetcomplete/StreetComplete/commit/462134ee7f22ad8bc9484daee9937585d7b932fd (since `AddMaxHeight` and `AddMaxPhysicalHeight` first shared the same quest title):

Add the quest name (e.g. `AddMaxHeight`) to the icon's `alt` text in the wiki. Some icons already had this anyway, that's why I chose to check it there.

**Comment by rugk** [comment]
> Add the quest name (e.g. AddMaxHeight) to the icon's alt text in the wiki. 

Well… that's not what an alt text is supposed to be used, its an accessibility feature after all. And some already have a proper alt text that I would avoid to remove…

But as I have no other better idea (except of some hidden comment or so) we could maybe at least have some splitting there? Like allowing an alt text of `AddPostboxRoyalCypher: a yellow crown on a green background` to extract the hint?

**Comment by FloEdelmann** [comment]
> some already have a proper alt text that I would avoid to remove

You don't need to replace the alt text; the quest name can be part of the alt text e.g. like this (from https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_streetsurface.svg):

> Icon of the quest "RoadSurface" of the app StreetComplete showing a rough street with white border on a yellow background.

A hidden HTML comment with the quest name in the icon cell should work, too.

> we could maybe at least have some splitting there?

You can write the alt text like that, the regex doesn't care :wink:
