### ISSUE TITLE
An impossible race condition

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#3888]
I got this crash report recently:

```
java.util.NoSuchElementException: Key
       nodes, ways, relations with
         historic = wayside_shrine
         and !religion
         and access !~ private|no
    is missing in the map.
at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
at kotlin.collections.MapsKt.getValue(Unknown Source:0)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataXtKt.getElementFilterExpression(MapDataXt.kt:30)
```

But the code in qestion is 
```kotlin
private val filterExpCache: MutableMap<String, ElementFilterExpression> = HashMap()

private fun getElementFilterExpression(expr: String): ElementFilterExpression {
    if (!filterExpCache.containsKey(expr)) {
        synchronized(filterExpCache) {
            if (!filterExpCache.containsKey(expr)) {
                filterExpCache[expr] = expr.toElementFilterExpression()
            }
        }
    }
    return filterExpCache.getValue(expr)
}
```

Anyone, any idea how this is possible? I.e. how it is possible that the key does not exist in the map at the return statement? (`String.toElementFilterExpression()` returns an `ElementFilterExpression`, not nullable)

**Comment by kmpoppe** [comment]
Could this be some weird threading issue? Would it help to put the whole `if`-block into `synchronized`?

**Comment by westnordost** [comment]
I think it must be, but the `synchronized` should prevent this. And the whole `if` block is already in the ´synchronized` block, i fyou look closely.

**Comment by kmpoppe** [comment]
Well the first line of `getElementFilterExpression` is `if (!filterExpCache.containsKey(expr)) {`.
I see that the very same line is within `synchronized` again, but I wonder if the first access to the Cache being outside of `synchronized` causes the issue (because it checks for the contents of the Map before the sync gets initialized)?

**Comment by westnordost** [comment]
Why/how? This could only be a potential problem if elements from the `filterExpCache` are ever removed (but they are not), the way I see it.

**Comment by tapetis** [comment]
As far as I understand the code of Java's `HashMap`, the insertion of a new element into the map is a complex process that can result in a rearranging of the map's internal tree structure. This rearranging process is only started after the new elements is added to an empty position in the tree, At this time, `containsKey` returns `true`.

During rearranging, however, elements may be temporarily removed from the tree. This can result in previously inserted keys not being in the map during the iteration of the map's nodes and thus in `getValue` returning `null`.

**Comment by kmpoppe** [comment]
That sound like a damn good explanation of the problem @tapetis 👍

**Comment by westnordost** [comment]
Oh wow, I never thought of that. One lives and learns. Makes me wonder what would happen if one adds another value (in another thread) while the rearranging process is being done. Anyway, so either I have to use synchronized everywhere when accessing a HashMap or use ConcurrentHashMap.

**Comment by westnordost** [comment]
I've used this pattern in 2 more places, they should be fixed now. Thank you @tapetis !
