### ISSUE TITLE
"Alcohol shop" and "Alcohol" should be able to find "Off licence (Alcohol shop)" entry

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3894]
to reproduce:

- switch language to en-GB
- find some opening hours question or similar
- answer "does not exists"
- try to search for "Alcohol shop" (fails)
- "Off licence" (finds "Off licence (Alcohol shop)")

Likely other searches could be more eager

**Comment by peternewman** [comment]
Isn't some of this the terms part of the translation? I've added stuff for hairdressers/barber in the past (although it would be nice if it fell through to the en/en-US if en-GB didn't exist.

But I'd probably agree that matching `\balcohol shop\b` ought to work. I assume a bracket counts as a word boundary.

**Comment by matkoniecz** [comment]
> Isn't some of this the terms part of the translation?

Well yes, in EN-GB iD presets `shop=alcohol` is described as "Off licence (Alcohol shop)"

**Comment by peternewman** [comment]
I meant:
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/shop/hairdresser.json
https://github.com/openstreetmap/id-tagging-schema/blob/6b29ff9668de1be6cc14c2034e08266c51669e96/dist/translations/en-GB.json#L3621-L3624
https://github.com/openstreetmap/id-tagging-schema/blob/6b29ff9668de1be6cc14c2034e08266c51669e96/dist/translations/en.json#L7315-L7318
versus
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/shop/alcohol.json
https://github.com/openstreetmap/id-tagging-schema/blob/6b29ff9668de1be6cc14c2034e08266c51669e96/dist/translations/en-GB.json#L3456-L3458
https://github.com/openstreetmap/id-tagging-schema/blob/6b29ff9668de1be6cc14c2034e08266c51669e96/dist/translations/en.json#L7018-L7021

I don't know if SC or iD isn't falling back to the en terms if en-GB isn't populated, or SC/osmfeatures isn't searching the terms data at all regardless of translation status?

It looks like it's one of the former, as you can now type barber and it will offer "Hairdresser", so it must be searching the terms, but they're just not getting populated by default (which might make sense for other languages, but not really for variants of English...

**Comment by westnordost** [comment]
Related code:

https://github.com/westnordost/osmfeatures/blob/master/library/src/main/java/de/westnordost/osmfeatures/FeatureDictionary.java#L321-L329

Feature dictionary does not recognize "(" (and everything else except whitespace) as a separator of a word. So, it looks like the splitting of words in a string could be smarter.
A PR is welcome if tests are added for the modified behavior.

**Comment by westnordost** [comment]
But I'd prefer if you opened an issue in that repo first.
