### ISSUE TITLE
House number quest does not immediately appear when selecting house type as bungalow

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3899]
When selecting house type as "detached house" or "house" the house number quest immediately appears. If I select bungalow, it doesn't appear, I get no further quests.

I have manual upload of quests selected. 

I can't think of a reason why it shouldn't do this for bungalows too, is it a bug?

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L203-L206

Looking at https://taginfo.openstreetmap.org/tags/building=bungalow#combinations https://taginfo.openstreetmap.org/tags/building=house#combinations it seems that they are less likely to have addresses, but most of them will still have them

If we assume that houses and bungalows have the same rate of address being mapped as separate nodes or not yet mapped

And that about 100% houses have addresses

Then about 60% of bungalows have addresses.

**Comment by matkoniecz** [comment]
But note rejected "Add building=bungalow to buildings with an address" #3039

**Comment by timothywashere** [comment]
I suspect most UK mappers are tagging bungalow just as a house that happens to have one floor.

Over 75% have a street name and 66% have a house number in the UK
https://taginfo.openstreetmap.org.uk/tags/building=bungalow#combinations

This would be even higher if SC asked for house numbers for bungalows as I have tagged thousands of houses using only SC.

Could this be enabled for the UK only ?

**Comment by westnordost** [comment]
No, there are not country/region specific interpretations of what tags mean.

Anyway, if ~60% of all bungalows are actually (1-storey) detached houses, that still leaves us with 40% that are holiday homes or similar. I am not sure if it is acceptable to add `nohousenumber=yes` to that many elements and it may also be irritating for the user to be asked for housenumbers for each individual holiday bungalow on a camping ground.

> If it's not meant for residential houses the English translation should be changed to Chalet or something.

https://en.wikipedia.org/wiki/Chalet ... seems to be different from `tourism=chalet`. 
https://en.wikipedia.org/wiki/Cottage also is too broad.
Also, it would probably not be acceptable to use a different name for `building=bungalow` than "Bungalow". "Bungalow / Chalet / Cottage" or similar would probably also not be acceptable because there **is** `building=chalet` (etc.), used 4k+ times.

I think the best bet would be to make it clear in the description. The description is "small detached house (summer house, holiday cottage, cabin …)"

**Comment by peternewman** [comment]
> Anyway, if ~60% of all bungalows are actually (1-storey) detached houses, that still leaves us with 40% that are holiday homes or similar. I am not sure if it is acceptable to add `nohousenumber=yes` to that many elements and

To look at it the other way, doesn't that mean 60% of bungalows are incorrectly tagged (based on the OSM definitions) so we should resurvey them (and maybe terraced houses, if we're being really clever smaller than a certain size/with multiple addresses) to fix the invalid tagging?

Or maybe even ask the question, if they say there is no housenumber, it can ask "Is it really a chalet?" or conversely if they tag a housenumber on a bungalow it could ask if it's actually a house, with a check_date avoiding the quest reoccuring.

From my reading of the German bungalow it's pretty similar to the English one ( https://wiki.openstreetmap.org/wiki/Tag:building%3Dbungalow ) and judging by the large numbers of them in e.g. Berlin (especially with housenumbers), there are probably a lot which are miss-tagged too.

> it may also be irritating for the user to be asked for housenumbers for each individual holiday bungalow on a camping ground.

I assume you don't want to complicate it by isolating by the landuse (given most buildings, regardless of type) are unlikely to be numbered on a camping ground (or only numbered/named for the purposes of knowing which one you're booked into? Actually, by that argument, surely most holiday homes will have some form of identification, so you know which one to go to/people can track it. Aside from maybe shed type things on allotments, I can't think of many places they wouldn't be identified.

> > If it's not meant for residential houses the English translation should be changed to Chalet or something.
> 
> https://en.wikipedia.org/wiki/Chalet ... seems to be different from `tourism=chalet`.

Yes, agreed, I think what's meant in OSM land by bungalow is what we'd often call a chalet in the UK.

> https://en.wikipedia.org/wiki/Cottage also is too broad.

Agreed, a cottage is just a small house.

> Also, it would probably not be acceptable to use a different name for `building=bungalow` than "Bungalow". "Bungalow / Chalet / Cottage" or similar would probably also not be acceptable because there **is** `building=chalet` (etc.), used 4k+ times.
> I think the best bet would be to make it clear in the description. The description currently is _"small detached house (summer house, holiday cottage, cabin …)"_

Would dropping the word house help, e.g.:
_"small detached dwelling (summer house, holiday cottage, cabin …)"_

You don't really _live_ there (from my understanding of what OSM means by the word bungalow).

**Comment by timothywashere** [comment]
> 

It will be a lot more than 66% of bungalows mapped in the UK that are houses. You can't use the lack of house number as evidence that a building is not a home, since SC doesn't ask. 

In the UK chalet means a small, mostly wooden type structure which is not a home. The wikipedia article does not reflect UK usage.

https://www.google.com/search?q=chalet+uk&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjzpbXum9f2AhWBUcAKHWdCCn4Q_AUoAXoECAIQAw&biw=2143&bih=1287&dpr=1.5
https://www.google.com/search?q=bungalow+uk&client=firefox-b-d&hl=en-GB&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi87ISIntf2AhXbiVwKHRXkCM8Q_AUoAXoECAEQAw&biw=2143&bih=1287&dpr=1.5

**Comment by westnordost** [comment]
> doesn't that mean 60% of bungalows are incorrectly tagged (based on the OSM definitions) so we should resurvey them

No, because the definition of `building=bungalow` is inherently ambiguous regarding that matter. Regardless of what the wiki says, it looks like ~60% of buildings tagged with `building=bungalow` are detached houses (with housenumbers). It is the current de-facto tagging practice, not incorrect. Just ambiguous.

**Comment by westnordost** [comment]
So, I'd opt to not have this in. Recently came by a large allotments area where every allotment house was tagged as a bungalow (which is not exactly wrong, just maybe imprecise / misleading) - would be not very cool if StreetComplete asked for the housenumber for every of those.

**Comment by timothywashere** [comment]
I find this odd.

If it's so unclear that no-one knows what it means then you should probably remove it as an option for building type.
Or add more questions to clarify what is meant by bungalow and add extra tags accordingly.

**Comment by matkoniecz** [comment]
@timothywashere 

Is there some accepted alternative tagging that would allow to avoid this confusion? And this distinguish this cases?

AFAIK no.

(I am not working on it as I (1) not fully understanding the problem (2) already working to fix several other quagmires and starting dealing also with that would be a bad idea)

**Comment by timothywashere** [comment]
If the user selects residential you could change it to building=house with levels = 1
If the user selects holiday you can add something like tourism=chalet
I don't know what an allotment bungalow is, maybe it's just a building=shed

**Comment by matkoniecz** [comment]
>  If the user selects holiday you can add something like tourism=chalet

No, as it may be inactive (and building be unused or used for a different purpose) or mapped already as node/area
