### ISSUE TITLE
Can't enter letters as part of house number, when also entering house name

### ISSUE THREAD

**Issue by animmo** [streetcomplete/StreetComplete#3904]
Normally, when entering a house number (only), an **ABC** button appears to the right of the text input box to allow the keyboard to be changed to the QWERTY keyboard so that letters can be added to the house number.

However if you select `Other Answers...` then the `Both a house number and a name...` option, the house number entry in this dialog is missing the **ABC** button, so it is not possible to add letters to the house number.

**Comment by Cj-Malone** [comment]
I got caught by this a couple weeks ago, but forgot to fix it + report it.

https://www.openstreetmap.org/way/471099851

**Comment by kmpoppe** [comment]
Changed the object to reflect the correct address, so your example is now reflected in **Version #5** of the obejct.

**Comment by timothywashere** [comment]
On a slightly related question. Is it possible the number version could allow for the letters A and B? I find it annoying having to switch to the full alpha keypad just to enter 1A or 1B.
