### ISSUE TITLE
Enable "convert to steps" option for service ways also

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3908]
Hi there,

is there a reason why the handy "convert to steps" menu option isn't available for "highway=service" OSM ways? In the past I came across many missing steps on the map and wondered why I couldn't convert them via Street Complete after splitting the ways, and some short tests suggest that all of these ways are tagged with "highway=service". Even if some of them were mistagged as such and would have been better tagged as (e. g.) "highway=footway", retagging the steps part would be always an improvement, but currently it's seemingly not possible with SC, which is a pity since the user is on-site at that moment and would be able to correct this (together with many steps-related taggings).

The cycling cat

**Comment by matkoniecz** [comment]
Mostly because it was assumed that in case of such mistakes things are tragically messed up in general and edit with proper editor is needed.

For example you would be able to create disjoint `highway=service` ending as steps everywhere.

**Comment by westnordost** [comment]
Yeah, leaving a note is better in that case.

**Comment by cyclingcat** [comment]
Avoiding mistakes is a good point, of course. I was just wondering why some of the smoothness/surface quests show the "convert to steps" menu item while others don't.

The cycling cat

**Comment by westnordost** [comment]
If any quest shows the "convert to steps" answer for `highway=service`, it is a bug
