### ISSUE TITLE
State resurvey interval in settings

### ISSUE THREAD

**Issue by mfbehrens99** [streetcomplete/StreetComplete#3909]
It would be great to give some more information on the resurvey interval. If it is implemented as a fixed amount of time in days it would make sense to replace it with a number input or state the amount of days short, normal, long corespondents with. If the terms short, normal and long apply a factor to base times then it would also be possible to display the factor in the settings, although that would not look very elegant.

**Comment by HolgerJeromin** [comment]
"every" quest has an own default interval. 
The setting is used to use the double or half of the defined time.

**Comment by westnordost** [comment]
See @HolgerJeromin , the resurvey interval depends on the quest type. The setting just adds a multiplicator:
Less often: double the time between intervals
More often: half the time between the intervals

**Comment by westnordost** [comment]
Currently. This may change. This is why it is vague.
