### ISSUE TITLE
[seating quest] Change radio buttons to checkboxes

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#3911]
**Use case**
I really like the new seating quest – but however, it is not possible to tag `indoor_seating` _and_ `takeaway` as an example.

**Proposed Solution**
The radio buttons allow one pick out of the options only, checkboxes would allow multiple tags.
I made a really poor mock-up, maybe this helps to understand my idea;
![grafik](https://user-images.githubusercontent.com/92865620/159780659-0ce690b3-3fba-46a7-bde8-1fb1aa00e9d3.png)

If only takeaway would be selected then, tag `takeaway=only`, if multiple things get selected, tag each key with `yes`.

One thing I raise fears with is, that users would click just one thing if they don't know about the others but SC nevertheless tags that the other features doesn't exist.
Example: User sees an ice cream shop with outdoor seating and taps 'outdoor seating' – 'OK'. SC would tag in this case `outdoor_seating=yes` and `indoor_seating=no`. That would be wrong if there is indoor seating which was just missed by the user.
Maybe the 'only' can be highlighted somehow, as it is also clear in the current version.

**Comment by westnordost** [comment]
So does the meat shack have takeaway seating?

**Comment by westnordost** [comment]
In any case, the thing I wanted to point at with this rhetorical question was that the question is clearly about seating, not takeaway.  See the quest guidelines. StreetComplete does not ask about several things at once, asking to fill takeaway + seating would be that.

Takeaway is only mentioned as a way to say "no seating at all", incidentally recording the takeaway=only information on the side when it is the case.

**Comment by kjonosm** [comment]
Why not say: "No seating (takeaway only)"?

**Comment by mnalis** [comment]
> Why not say: "No seating (takeaway only)"?

While a little longer, I do agree that it reduces a chances for wrong answer. It would need re-translation, though.

As a less invasive option (or in addition to above), to avoid wrong answers, it might also be helpful to reverse the order of the answers,   so `Both indoor and outdoor seating` is placed first, and `Takeaway only` shown last.

**Comment by westnordost** [comment]
makes sense, changed it
