### ISSUE TITLE
New Quest: Building Colour

### ISSUE THREAD

**Issue by Itschotsch** [streetcomplete/StreetComplete#3913]
### General
Affected tag(s) to be modified/added: [Colour](https://wiki.openstreetmap.org/wiki/Key:building:colour)
Question asked: **What colour is this building?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ x ] 🚧 To be added tag is established and has a useful purpose
The Colour tag is used for building visualisation. Since the building type, number of levels and roof shape are quests with this very goal already, it makes sense to ask for this information as well.
- [ x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ x ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ x ] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Requires: building=* or building:part=* 
Useful combination: roof:colour=*

**Metadata needed:**
Whether the feature is a building or not.

**Proposed UI:**
What colour is this building?
Choose one:
[Grid of the 3x7=21 most common colours or example images just like for the road surface quest. For example concrete, white paint, red bricks etc.]

More answers...
-> Different colour... (show simple colour picker)
-> Different parts have different colours... (usual solution)
-> Not answerable... (usual solution)

**Comment by peternewman** [comment]
See https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+building%3Acolour+is%3Aclosed or more specifically https://github.com/streetcomplete/StreetComplete/issues/1358#issuecomment-475990007 and https://github.com/streetcomplete/StreetComplete/issues/1358#issuecomment-595232339

_Originally posted by @matkoniecz in https://github.com/streetcomplete/StreetComplete/issues/2694#issuecomment-809285597_
