### ISSUE TITLE
Mark disused residential buildings

### ISSUE THREAD

**Issue by nils-werner** [streetcomplete/StreetComplete#3916]
**Use case**

Nowadays, there is a housing crisis in many countries of the world. Rent is going up, development cannot keep up, and many property owners decide to disusue or abandon their property instead of developing it. Especially the value of undeveloped and unoccupied properties quickly raises, creating an incentive to either not develop them, or kick out existing tenants. This of course further increases the supply/demand unbalance, raising prices even further.

Many municipalities have laws outlawing disused residential properties to counteract this problem. What most municipalities are missing however is an easily accessible, unified database of disused residential buildings.

This is where OSM and StreetComplete could come in. We could create a database of

```
bulding=residential/apartments/terrace/house/detached/semidetached_house
disused=yes
```

buildings, and allow officials to [list them on Overpass Turbo](http://overpass-turbo.eu/?w=(building%3Dresidential%20or%20building%3Dapartments%20or%20building%3Dterrace%20or%20building%3Dhouse%20or%20build%3Ddetached%20or%20building%3Dsemidetached_house)%20and%20(disused%3Dyes%20or%20abandoned%3Dyes)&R
) and maybe react more quickly.

**Proposed Solution**

A quick way to mark existing residential buildings as `disused=yes` in StreetComplete.

Of course the UI would then be flooded with questions, and there is not much gain in specifically tagging buildings with `disused=no` just to hide this question. So this task should probably not be enabled by default. An alternative way of producing engagement without annoying everybody else should eventually be found.

**Comment by mnalis** [comment]
Doesn't sound like a good idea to me; both the huge spam and adding useless tag to majority of buildings. 
What would be better solution in your case IMHO is one of the following:

- use StreetComplete normally, and when you find disused building which is not drawn as disused (i.e. with dashed instead of full line), long press at that location and add a Note saying that this building is disused (so it can later be edited as disused in other, more comfortable desktop editor)
- do not use StreetComplete but some other editor like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) for the task, and mark building as disused directly on the ground, without need for post-processing (can be combined with above; use StreetComplete normally and then long press on location of building and select "Open in Vespucci")

**Comment by matkoniecz** [comment]
>  when you find disused building which is not drawn as disused (i.e. with dashed instead of full line)

As far as I know iD is doing this, SC has no special rendering.

**Comment by matkoniecz** [comment]
To quote https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&template=quest-suggestion.md

> Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
> - [ ] 🚧 To be added tag is established and has a useful purpose
> - [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

I am not expecting that any region, city or country would consider adding https://taginfo.openstreetmap.org/tags/disused=no to all used buildings as a good idea.

**Comment by nils-werner** [comment]
I agree, that's why I specifically *advised against adding `disused=no`*.

Instead I was proposing a UI that does not require this tag to be set in order for the task to appear. Maybe long-tap on an item and show a list of tasks there.

**Comment by HolgerJeromin** [comment]
> Instead I was proposing a UI that does not require this tag to be set in order for the task to appear. 

We need the tag "for the task to NOT appear" again if the user has answered "nope".
This has nothing to do with the GUI but data selection.

**Comment by matkoniecz** [comment]
> Instead I was proposing a UI that does not require this tag to be set in order for the task to appear. Maybe long-tap on an item and show a list of tasks there.

That kind of interface is on list of large possible project, once (if) that will be available then this can be reopened.

**Comment by andrewharvey** [comment]
This gave me the thought of forcing a re-survey, I opened https://github.com/streetcomplete/StreetComplete/issues/3918 to discuss.
