### ISSUE TITLE
Add AR support for Huawei devices with Huawei AR Engine

### ISSUE THREAD

**Issue by endim8** [streetcomplete/StreetComplete#3917]
**Use case**
Adding support for AR Engine would allow a lot of users to access AR quests. Some Huawei phones also have a time-of-flight sensor, which would allow for more accurate measurements than a standard ARCore phone.

**Proposed Solution**
add support for AR Engine on Huawei devices.
https://developer.huawei.com/consumer/en/hms/huawei-arengine/

**Comment by matkoniecz** [comment]
Is this phone listed on https://developers.google.com/ar/devices ?

**Comment by endim8** [comment]
> Is this phone listed on https://developers.google.com/ar/devices ?
My one (P40 pro) isn't due to the Huawei ban, which prevents google working with Huawei, but AR Engine devices before the ban such as the P30, P20, Mate 20 etc 

> If not, then adding AR support would be likely very significant effort - for a specific family of devices (it would make more sense to support it if that would be some open standard not limited to a single producer)

I agree that an open standard would be much nicer, but that isn't always possible, for example Apple's ARKit is closed source.

**Comment by endim8** [comment]
I have decided to sell my p40 pro due to the locked bootloader :/ if someone else wants to continue this feel free 👍

**Comment by matkoniecz** [comment]
yeah, that needs someone with Huawei device or at least Huawei-specific emulator (and likely is problematic anyway due to likely huge code complexity just to support Huawei-specific functionality)

**Comment by mnalis** [comment]
I do have Huawei P30 Pro (which seems to also be listed at https://developers.google.com/ar/devices), however I'm not using  Huawei App Galery, nor Google Play Store (as I refuse to accept their respective ToS).

That being said, it does seem to say that `com.coogle.ar.core` comes preinstalled:
```
HWVOG:/ $ pm list packages .ar
package:com.huawei.ar.measure
package:com.huawei.arengine.service
package:com.google.ar.core
```

Also, I do have Huawei-provided-by-default `AR Measure` app which seems to work just fine.

However, StreetComplete **does not** seem to recognize AR (i.e. measuring quests disabled by default, and when I click on `AR Measure Horizontal` (or `AR Measure Vertical`) in Debug SC build, nothing happens, etc.

Logcat contains quite a lot of fast-moving stuff, so I would need guidance what to look for:

<details>

<summary>logcat contains many things like...</summary>

```
04-04 02:45:15.968  1437  1437 I JobScheduler: isComponentUsable: 5a6a709 #u0a61/262200667 com.google.ar.core/.services.profiles.ProfileDownloadJobService component not present
04-04 02:45:15.968  1437  1437 I JobScheduler: isComponentUsable: 5a6a709 #u0a61/262200667 com.google.ar.core/.services.profiles.ProfileDownloadJobService component not present

04-04 02:45:18.299   722  9279 I AR_impl : enableActivityEvent activity[0], event[1] reportLatency[1000000000]ns
04-04 02:45:18.299   722  9279 I ArHal   : (ArEnableActivityEvent:1473):activity[0] event[1] latency[1000000000 ns]
04-04 02:45:18.300   722  9279 I ArHal   : (ArDataEnableActivityEvent:742):successfully
04-04 02:45:18.300   722  9279 I ArHal   : (ArDataGetState:1389):id[2]
04-04 02:45:18.301   722  9279 W ArHal   : (ArDataGetActivityIndex:263):invalid activity[31]
04-04 02:45:18.301   722  9279 W ArHal   : (ArDataGetState:1420):unknown activity[31], discard
04-04 02:45:18.301   722  9279 I AR_impl : enableActivityEvent end, pid[2402]
04-04 02:45:18.301   722  9279 I ArHal   : (ArDataGetState:1389):id[2]
04-04 02:45:18.302   722  9279 W ArHal   : (ArDataGetActivityIndex:263):invalid activity[31]
04-04 02:45:18.302   722   778 I ArHal   : (ArDataNetlinkCb:959):cmd[2].length[264]
04-04 02:45:18.302   722  9279 W ArHal   : (ArDataGetState:1420):unknown activity[31], discard
04-04 02:45:18.302   722   779 I AR_impl : ActChangedCb start count[11]
04-04 02:45:18.304   722   779 I AR_impl : able to onActivityChangedV1_1
04-04 02:45:18.304   722   779 I AR_impl : ActChangedCb end, pid[722]
04-04 02:45:18.308   722  9279 I AR_impl : enableActivityEvent activity[0], event[2] reportLatency[1000000000]ns
04-04 02:45:18.308   722  9279 I ArHal   : (ArEnableActivityEvent:1473):activity[0] event[2] latency[1000000000 ns]
04-04 02:45:18.309   722  9279 I ArHal   : (ArDataEnableActivityEvent:742):successfully
04-04 02:45:18.309   722  9279 I ArHal   : (ArDataGetState:1389):id[2]
04-04 02:45:18.309   722  9279 W ArHal   : (ArDataGetActivityIndex:263):invalid activity[31]
04-04 02:45:36.194  1044  1117 I FusionD : (FdOnArData:492):ar count 1
04-04 02:45:36.194  1044  1117 I AR_FusionD: (SendMessage:435):socket 14 send 32 data:
04-04 02:45:36.195  1044  1117 I FusionD : (FdOnArData:492):ar count 1
04-04 02:45:36.195  1044  1117 I AR_FusionD: (SendMessage:435):socket 14 send 32 data:
04-04 02:45:36.195  1044  1117 I FusionD : (FdOnArData:492):ar count 1
04-04 02:45:36.195  1044  1117 I AR_FusionD: (SendMessage:435):socket 14 send 32 data:
04-04 02:45:36.198   722   779 I AR_impl : able to onActivityChangedV1_1
04-04 02:45:36.198   722   779 I AR_impl : ActChangedCb end, pid[722]
04-04 02:45:36.216 24762 25881 I QuestAutoSyncer: All downloaded in radius of 244 meters around user (9 tiles)
04-04 02:45:36.853  1044  1118 I FusionD : (FlpDisableAr:654):stop AR.
04-04 02:45:36.869   722   778 I ArHal   : (ArDataNetlinkCb:959):cmd[2].length[240]

```

</details>

Let me know if there is something I can help with there @matkoniecz .

**Comment by matkoniecz** [comment]
I admit that I am not sure but maybe @westnordost can do something here (he implemented AR quests)

**Comment by endim8** [comment]
@mnalis try also updating ARCore, afaik the one that's shipped by default is just a shell app, and needs updating to actually work

https://www.apkmirror.com/apk/google-inc/arcore/

**Comment by mnalis** [comment]
related: https://github.com/streetcomplete/StreetComplete/issues/2093#issuecomment-693538356 and below

**Comment by mnalis** [comment]
Thanks @endim8, that appears to be the issue! 

After updating `ARCore` from that link, it seems that SC recognizes it and it seems to work (although I've had it fail sometimes by showing a black screen instead of camera input, and I had to clear SC from cache for it to start working again).

Amazing that manufacturers intentionally ship non-functional app in the ROM - that sounds crazy. 
Although now that I think about it, I guess it had to do with their spying ability - I seem to recall that system apps can override restrictions user tries to place upon them. And by forcing the user to upgrade, they can deploy newest spying code, while still retaining system permissions.

**Comment by HolgerJeromin** [comment]
> Amazing that manufacturers intentionally ship non-functional app in the ROM - that sounds crazy.

No one can retest all features before launching such complex software as a phone.
AR will be tested after implementing and probably not very often afterwards.

Updating system code is much easier then hiding it in some obscure AR library.
