### ISSUE TITLE
Add showcase: OsmHydrant

### ISSUE THREAD

**Issue by FinixFighter** [streetcomplete/StreetComplete#3922]
www.osmhydrant.org is a useful website showing position of hydrants, fire stations, water tanks etc. 
Benefits of this map are numerous (look here https://www.osmhydrant.org/en/about) and I think it would be nice to have it in the showcase section.
Moreover: I think the showcase section is very nice, and it's cool to discover a new project every time you reach a new level!

**Comment by FloEdelmann** [comment]
It was already added in #3616:

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/user/achievements/AchievementsModule.kt#L253-L260
