### ISSUE TITLE
Feature request: allow multiple ref numbers for bus stops

### ISSUE THREAD

**Issue by mretoolforge** [streetcomplete/StreetComplete#3924]
**Use case**

The StreetComplete quest for a missing bus stop reference number is useful, but quite often when a stop is served by multiple transit agencies, they will each have their own reference number for it.

**Proposed Solution**
The user could tap "Can't Say" > "There are multiple reference numbers" or similar to access a prompt allowing multiple numbers to be entered.

There are two ways to show multiple ref numbers - either a semicolon-separated list, or by using namespaces to specify the operator for each. The latter is preferable because the order of the list would be arbitrary and difficult to parse. The tagging would be like: ref:MTA=, ref:JHU=, etc. The difficult aspect would be how to ask for the operator name. One option would be a dropdown which pulls its listing from existing tags in the area. Another would be to allow the user to manually type it, but this could introduce inconsistencies as there are a number of ways to name the same operator.

The most effective but most time consuming way to distinguish operators for multiple reference numbers might be to include some kind metadata file which has a fixed/standardized list of possible operators based on region. (Country or state/province etc.) The list of operators with overlapping service within a given region's network is usually finite and short, so I think this would be possible to implement if necessary.

**Comment by matkoniecz** [comment]
> The tagging would be like

Is it proposal to invent a new tagging or is it already in use?

In general, how often this situation is happening? Is it just local peculiarity in one city, even large, then likely "open note with photos" is a preferred solution.

**Comment by mretoolforge** [comment]
> > The tagging would be like
> 
> Is it proposal to invent a new tagging or is it already in use?

Already in use, but the extent to how much it's been tagged.

> In general, how often this situation is happening? Is it just local peculiarity in one city, even large, then likely "open note with photos" is a preferred solution.

Most of Maryland, DC, and Virginia you will see this on some stops on a given route. Pennsylvania and New Jersey I'm aware this is true as well, I can't speak to places outside the eastern US in detail though. For example, in Maryland you might have WMATA (Washington, DC area transit), MTA (Maryland state transit, a county/city run-transit service, and/or an education (grade school or university related) transit service all serving the same stop. In a number of suburban towns, the majority of stops have multiple operators and reference numbers. I have been avoiding the quest lately because it is usually asked at stops where this is the case.

**Comment by mretoolforge** [comment]
I think this circumstance is likely very widespread the more I think about it, just knowing how common it is for municipalities to have overlapping transit operations. To implement this in a conservative way, maybe the multiple ref numbers + operator input should only be possible if and only if there are existing ref:operator tags in the area to distinguish them. A metadata file explicitly defining where they are present could be compiled based on a query against OSM's database. (The reason a static file based on a query might be better than pulling directly from a query is that erroneous/seldom used ref:namespace tags could be removed from it.)

**Comment by westnordost** [comment]
How is it tagged?

**Comment by matkoniecz** [comment]
> The tagging would be like: ref:MTA=, ref:JHU=, etc. The difficult aspect would be how to ask for the operator name.
(...)
> Already in use, but the extent to how much it's been tagged varies.

**Comment by westnordost** [comment]
Yeah, I think it is not possible to create a quest for that. However, StreetComplete should probbly not ask for the `ref` if any `ref:.*` is tagged

**Comment by mretoolforge** [comment]
That makes sense, thank you. I'll try to tag all the shared stops locally so they don't come up in quests. The tagging convention seems to be to use the operator acronym so it's hard to get around that unfortunately

**Comment by matkoniecz** [comment]
Just in case you are unfamiliar with it: Vespucci is quite nice to complement SC for such cases (though leave note + edit at home also would work).
