### ISSUE TITLE
Arabic Text showing up instead of English in places in v42

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3926]
**How to Reproduce**
Latest version, many StreetComplete screens on my phone appear to have Arabic text instead of English. Sample screenshots:

![image](https://user-images.githubusercontent.com/12725310/160301607-209f2412-68d9-4531-b1a0-868d1582d11d.png)
![image](https://user-images.githubusercontent.com/12725310/160301619-ad7ba374-a7a2-4af4-b66a-0620eb938364.png)
![image](https://user-images.githubusercontent.com/12725310/160301624-0f9f0eb5-a9d1-41ac-a4e3-e07a17f3b7aa.png)

**Versions affected**
StreetComplete v42.0. Did not happen in v42.0-beta1
OnePlus 6T Running Android 11 (OxygenOS 11.1.2.2)

**Comment by westnordost** [comment]
That's weird... In the Android language settings, which languages do you have selected? (It is a list of preferred languages)

**Comment by westnordost** [comment]
Actually, it's Persian. It looks like a translator on POEditor who wanted to contribute in Persian accidentally selected English (AU) and didn't notice his mistake. I removed the translations in Persian and mailed the user.

**Comment by andrewharvey** [comment]
Does anyone know in POEditor if you can subscribe to change notifications, or if the translations go into a PR on GitHub before being merged? This issue has made the app unusable for the last 18 days and still ongoing, so we need better review/checks in place to prevent this again.

**Comment by mnalis** [comment]
@andrewharvey No subscription for that as far I know (at least I've never manage to find it - best I have is to monitor GitHub releases and when I see that new beta is out, I rush to see if there are new strings to translate (although I haven't yet considered checking all strings to see if some of them were broken by someone!)

POEditor does have an [API](https://poeditor.com/docs/api), so I guess it should be possible to locally fetch a list of translations of known language daily and then `diff` it against previous version, to notify one of any string changes in language they're watching.

Probably this API call: https://poeditor.com/docs/api#terms_list, but I guess it is less of programming problem than of manpower one - who will monitor the strings? I could run it locally to monitor Croatian, but other people would need to get their API token and monitor language of their choice for changes...

**Comment by matkoniecz** [comment]
You can watchlist https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/values-en-rAU/strings.xml or even better https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/app/src/main/res/values-en-rAU/strings.xml - maybe https://www.followthatpage.com/ or similar service is good enough?

But this file is modified just before release so if damage is done between beta and normal release it will be likely missed.

Maybe there is some generic service/tool for watchlisting changes of file on Github or in a repository? Or clone repository in cron and watchlist local file?

**Comment by eginhard** [comment]
The translation sync could be done in a PR instead of direct commits, so people watching the repository are notified and can review it.

**Comment by HolgerJeromin** [comment]
JFYI: We could add a Github action when there is a specific change in a PR.

For example:
https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1310/files
adds a comment to a specific issue when the build fails.

**Comment by andrewharvey** [comment]
I like these suggestions of using a PR instead of direct commits. POEditor doesn't seem to have any review system in place so a GitHub PR can become the place where it can be reviewed, discussed and approved before merging.

**Comment by matkoniecz** [comment]
> I like these suggestions of using a PR instead of direct commits.

Note that it has negative effects of imposing extra effort/trouble for @westnordost - which is a serious negative effect, as replacing him is not really feasible (see https://en.wikipedia.org/wiki/Bus_factor )

And it is an isolated accident, right?

**Comment by andrewharvey** [comment]
> Note that it has negative effects of imposing extra effort/trouble for @westnordost - which is a serious negative effect, as replacing him is not really feasible (see https://en.wikipedia.org/wiki/Bus_factor )

That's up to @westnordost, I was thinking having the translations commit in a branch that gets a PR, then if no comments or issues by anyone else after 24hrs its can be merged. It should help open the project up to more collaborators.

I could try to setup a GitHub action that pulls in translations and updates a PR if open, or opens a new one if no existing PR to try and reduce the manual workload, is there interest in that?

**Comment by westnordost** [comment]
No, that's alright. I usually review the strings pulled from POEditor, this one slipped through.
