### ISSUE TITLE
Make "Is smoking allowed here" quest never show for certain buildings in the United Kingdom 

### ISSUE THREAD

**Issue by berrely** [streetcomplete/StreetComplete#3930]
**Use case**

Under the Health Act 2006, smoking in enclosed spaces in any pubs, restaurants and nightclubs are illegal in the UK.

**Proposed Solution**

StreetComplete should not display this quest for pubs, restaurants or nightclubs in the UK.

**Comment by matkoniecz** [comment]
is both "only allowed outside" / "not allowed at all" a distinction that matters?

**Comment by mretoolforge** [comment]
In both the UK and the United States, smoking is effectively always allowed outdoors and never allowed indoors. I am surprised it is not disabled by default in either of these countries because it is kind of a pointless question to ask.

**Comment by matkoniecz** [comment]
It is disabled there (like everywhere else): https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/smoking/AddSmoking.kt#L45

On enabling you get message

> This quest type is disabled by default because it is not useful in some regions and you will likely have to enter the place to be able to answer a quest of this type.

ans user needs to confirm.

It is not blocked in UK (user can enable it there).

> smoking is effectively always allowed outdoors and never allowed indoors

Is it certain (or nearly certain) that bar/restaurant/biergarten/cafe will have outside part?

**Comment by mretoolforge** [comment]
It is not certain that there will be a formal outside part for customers, but it is common/accepted to smoke or drink at the street side of an establishment. (Drinking outdoors is legal in the UK, and illegal in most of the US but its de facto allowed so long as you "brown bag" it.)

**Comment by matkoniecz** [comment]
it appears that no changes are needed
