### ISSUE TITLE
Splitting sidewalk quest does not allow you to solve for segments

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3935]
I guess this only affects manual upload
A long road had the sidewalk quest so I split it where the sidewalk changed. I then could not answer the question for my segments because no quests appeared. After uploading all my changes later on, the quest now appears again.

Video after the way has been split
https://youtu.be/SD6WD5FP9QMding!-- 

**How to Reproduce**
Turn off auto uploads, find a quest with sidewalk quest, split the way, no quests appear for new segments
**Versions affected**

V42.0

**Comment by timothywashere** [comment]
I've seen this happen a few times also where undoing a split doesn't let you answer the original quest again.

**Comment by matkoniecz** [comment]
Is there a nearby `highway=footway`? Sidewalk quest tries to not appear if sidewalk is mapped as a separate object and maybe you run into case where entire long one was not detecting nearby footway and after split both started to detect it.

**Comment by matkoniecz** [comment]
> I've seen this happen a few times also where undoing a split doesn't let you answer the original quest again.

I have no straightforward idea what may be going on here.

**Comment by timothywashere** [comment]
Some parts have a footpath on one side of the road, yes

https://www.openstreetmap.org/#map=18/50.42541/-4.14689

One side of the road has no sidewalk at all for the section by the woods

**Comment by westnordost** [comment]
I am actually surprised that the quest showed up in the first place, after all there is a parellel footway really close by.

So if there is a bug, the bug is likely that the quest was shown in the first place. And this should be reproducable, right?
Would you undo the split of the way and keep the road as it is for now? Then we can have a look at this particular data example to see why the sidewalk quest turned up at all.

**Comment by timothywashere** [comment]
I undid the split before uploading, the quest still shows up.

Let me know when you've finished as I want to map it manually using iD before I forget if you're going to remove it from SC.

**Comment by westnordost** [comment]
I can not reproduce this. (At least) [way #742790695](https://www.openstreetmap.org/way/742790695) is close enough to the Tamerton Foliot Road to inhibit a quest from being created.

I think what likely happened is that a smaller bounding box, for example around the Cann Hause was downloaded. This bounding box thus included the Tamerton Foliot Road but not [way #742790695](https://www.openstreetmap.org/way/742790695) so the app did not find any footway that was too close the road to inhibit asking for a sidewalk.
