### ISSUE TITLE
Feature Request: Show the cat also on the International Cat Day (August 8th)

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3937]
... and not just on April 1st :smile: :smiley_cat: 

(![cat](https://user-images.githubusercontent.com/32601012/161299118-c467340c-f57c-4099-bbb8-6508d7dc902a.jpg))

The cycling cat  
# 👍 😸

**Comment by mnalis** [comment]
cf. https://github.com/streetcomplete/StreetComplete/discussions/3915#discussioncomment-2481863 :smile:

**Comment by matkoniecz** [comment]
This Cat Day is not really recognizable compared to the 1st April.

**Comment by westnordost** [comment]
jup

**Comment by westnordost** [comment]
Nice screenshot by the way - "Katzenstraße" :-)

**Comment by cyclingcat** [comment]
Of course this proposal was far from being meant seriously, however, being known as a cat lover I felt called to open this jokey ticket :rofl:

BTW: The "Katzenstraße" (German for "cat street") in the screenshot lies in the city centre of Lüneburg (I faked the GPS position on my smartphone).

The cycling cat
