### ISSUE TITLE
social_facility:for=*

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3940]
### General
Affected tag(s) to be modified/added: [social_facility:for](https://wiki.openstreetmap.org/wiki/Key:social_facility:for)
Question asked: **Who is served by this social facility?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (this one may be location dependent...)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[social_facility](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dsocial_facility) + [social_facility](https://wiki.openstreetmap.org/wiki/Key:social_facility)=[group_home](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dgroup_home) / [nursing_home](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dnursing_home) / [assisted_living](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dassisted_living) / [day_care](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dday_care) / [shelter](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dshelter) / [ambulatory_care](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dambulatory_care) / [outreach](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Doutreach) / [clothing_bank](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dclothing_bank) / [food_bank](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dfood_bank) / [soup_kitchen](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dsoup_kitchen)

**Metadata needed:** None

**Proposed UI:** Selecting from list (text? / images?), note that multiple selection is OK.

I am not 100% sure, mostly as I am not highly familiar with this topic but it appears to be something with a potential for a quest.

Main worry is how likely is that such objects can be surveyed from outside - ones that I am familiar with would be, but maybe I missed more discreet ones. And it is likely that situation is different in other regions and such objects may be more hidden or not specifying their purpose in other regions of the world.

**Comment by westnordost** [comment]
The difficulty with this is that it often overlaps with `social_facility`

**Comment by westnordost** [comment]
So, I think the selections available for #3939 must not orient itself on the tag values for `social_facility`, but instead offer real life things and tag accordingly `social_facility` and `social_facility:for`. In other words, these should not be separate quests.
