### ISSUE TITLE
What kind of entrance is here? (where no entrance is marked)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3941]
### General
Affected tag(s) to be modified/added: [entrance](https://wiki.openstreetmap.org/wiki/Key:entrance) / [noexit](https://wiki.openstreetmap.org/wiki/Key:noexit)
Question asked: **What kind of entrance is here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose (also, it may enable #3064)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) (hundreds in just Kraków, Poland - see https://overpass-turbo.eu/s/1hkN )

### Ideas for implementation

**Element selection:** find nodes shared between building and linear footway (maybe add also roads?), such as https://www.openstreetmap.org/node/9344552612

Skip cases where node is shared by building passage such as https://www.openstreetmap.org/node/5832373046

**Metadata needed:** None

**Proposed UI:**

Include option "there is no entrance here" that would apply `noexit=yes` There are cases of footway leading into wall which may be tagged as footway terminating on shared node with building (though I would not use such tagging)

**Comment by matkoniecz** [comment]
note #2706 which failed due to fact that some `entrance=yes` should remain `entrance=yes`

this has no such problem (I hope)

**Comment by westnordost** [comment]
Does this actually happen a lot? I think (even) JOSM gives you a warning when you let a footway end in a building outline.

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/1hl5 it seems so, about 1000 in central Berlin (and that is without taking roads, only foot ways)

![screen06](https://user-images.githubusercontent.com/899988/161382337-d3ab141f-278c-40be-9fcf-2efc9dc8da95.png)

though some would need to be skipped...

**Comment by mcliquid** [comment]
I've just added service streets in your query and may you have a look at this area: https://overpass-turbo.eu/s/1hlv
Also this area is quite interesting: https://overpass-turbo.eu/s/1hly
Just to think about how to handle these.
