### ISSUE TITLE
Better indicate when there is no GPS signal

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3944]
**Use case**
When GPS signal is lost,  it can be hard for user to know, and thus wrong mapping can occur. It happened to me several times (that I noted!), especially when map layout in new location without GPS signal was similar to map layout where GPS was last available. (such GPS signal loss happens often especially if I turn off screen to save battery as there is nothing to map for some distance, or enter/exit buildings etc.) 

<Details>

<summary>Main visibility problems:</summary>

- if the map is in "3D follow mode" (i.e. GPS icon shows `arrowhead` instead of `dot`), it is not possible to say **at all** if the GPS signal is available or not (in "2D mode", i.e. when GPS icon is shown as a `dot`, the `dot` is blinking where there is no GPS signal, so it is at least somewhat visible, although it can be surprisingly easy to overlook)
- the GPS position on the map remain same shape and color, no matter if GPS is available or not
- direction the phone is pointed at (i.e. the blue section of the circle in front of GPS position dot on the map) is showing direction even if the location is totally wrong, which is highly misleading. 

</details>

See the video, especially about 00:00:09 - 00:00:14 for example of how misleading it can be.

https://user-images.githubusercontent.com/156656/161667162-e8c3edbf-226b-4c55-b193-335047a17c76.mp4

**Proposed Solution**

I propose to implement (ideally all of) following suggestions, in order to make it clear that the GPS position on the map is invalid and thus avoid user unknowingly mapping invalid data:

- if the GPS signal is lost, make the `arrowhead` GPS icon **blink also** (same as when `dot` GPS icon is blinking)
- if the GPS signal is lost, turn **blue** `dot` on the map indicating user position to **grey** `dot` (or `hexagon` or `smaller circle` or `hollow circle` or some other shape understandable to colorblind persons too).
- if the GPS signal is lost, **disable showing** direction the phone (i.e. the blue **section of the circle** in front of GPS position dot) 

(all of the above should return to normal when GPS signal is reacquired, of course)

**Comment by rugk** [comment]
@mnalis Did you try have a look on how other mapping apps (Osmand, Maps[.me], Google Maps etc.) do this? Maybe that can inspire a solution here? (i.e. collect "relevant art", as [GNOME would call it](https://wiki.gnome.org/Design/Apps/Documents))

Out of the head of my mind I don't recall it right now given I don't have no GPS signal so often. :ups

**Comment by mnalis** [comment]
Yes, ideas are inspired by other apps. IIRC OsmAnd has as a map pointer a blue arrowhead (when moving direction is known), or blue hollow circle (when moving direction is not known) with transparant blue circle section extending in direction where user is looking (like in SC).

When the GPS signal is lost, that transparent circle section is removed, and blue hollow circle becomes grey. I'll try to take some screenshots with apps I'm using,  but I'm not sure if I'll get a chance before weekend.

**Comment by matkoniecz** [comment]
> if the GPS signal is lost, make the arrowhead GPS icon blink also (same as when dot GPS icon is blinking)

Maybe make it gray or disappear? Blinking is really irritating, especially in the center of field of view.

**Comment by mnalis** [comment]
>>  if the GPS signal is lost, make the arrowhead GPS icon blink also (same as when dot GPS icon is blinking)

> Maybe make it gray or disappear? Blinking is really irritating, especially in the **center of field of view**.

In that **third** bullet point that you quote, I was talking about `GPS icon` in **_lower right_** corner (where there is currently `dot GPS icon` which  _is **already** blinking_, see video at `00:01-00:04` for example), and **not** about `circle on the map` (so - not in the _center of field of field of view_). (Also, that blinking in the _corner_ is intended to be noticeable/annoying, as it needs to draw user attention that the app is _unusable_ at that moment for normal use)

About making `the circle on map` grey, I do agree that it should not be blinking but should instead turn different color - that was in fact what I was trying to suggest with **second** bullet point in the proposal (albeit I originally suggested orange, not grey), i.e.:

> if the GPS signal is lost, turn **blue** `dot` on the map indicating user position to **orange** `dot` (or `hexagon` or some other shape).

**Comment by matkoniecz** [comment]
I think that in general it is a good idea, as long as it is not requiring massive amount of tricky code. (and I expect it to be not requiring it)

**Comment by mnalis** [comment]
gallery OsmAnd:
- when GPS is visible, `map pointer` is either blue triangle (if moving direction is known) or blue hollow circle, both with `looking direction` shown as transparent blue circle sector. Also `clickable icon` on bottom right is colored blue.
 
![small_Screenshot_20220410_163425_net osmand plus](https://user-images.githubusercontent.com/156656/162635679-1e6aea67-8cd0-40e2-a1bc-6d58b4d18f33.jpg) ![small_Screenshot_20220410_163215_net osmand plus](https://user-images.githubusercontent.com/156656/162635682-52be948d-a6e3-4bbe-800b-a66b94892e49.jpg)

- When GPS signal is lost, `map pointer` turns to smaller grey circle, and `looking direction` disappears and is replaced by bigger transparent grey `error circle`. Also `clickable icon` is colored grey.

![small_Screenshot_20220410_171754_net osmand plus](https://user-images.githubusercontent.com/156656/162635698-27d1b6ba-b104-4f3a-962d-2075734b20ed.jpg)

**Comment by RubenKelevra** [comment]
We currently have a blue dot with a white circle and a larger blue dot which is half transparent with a darker blue circle around to mark the area of GPS accuracy.

If the GPS accuracy is very vague the area will become really large and the slight blue tint of the whole map might not be obvious.

How about removing the two dot solution and make just one dot which changes its size depending on the GPS accuracy? Additionally we could change the transparency depending on the size - so if the dot is small it is solid and if it spreads out more it gets more and more transparent. 

This would remove the misleading center dot if the GPS is very inaccurate. 

If the GPS completely unavailable we could just use the last position and decrease the accuracy value of the last measurement received with something like 2 meters / second. 

This allows for a smooth transition from an accurate to an inaccurate state without a large "jump" in the display if the GPS gets spotty in an area and struggles with a fix.

**Comment by mnalis** [comment]
Gallery Vespucci: when GPS is visible, `map pointer` is tranparent blue triangle with solid blue outline; when GPS is lost, `map pointer` becomes completely filled black triangle (at last known location).

![small_Screenshot_20220410_163159_de blau android](https://user-images.githubusercontent.com/156656/162635783-764cae03-c10b-4d8c-a4dd-7a25644e0409.jpg) ![small_Screenshot_20220410_171736_de blau android](https://user-images.githubusercontent.com/156656/162635790-9d2e4b46-d2aa-4a22-9d67-8303254a4000.jpg)

**Comment by mnalis** [comment]
Gallery OrganicMaps: when GPS is available, both `map pointer` and `clickable icon` are solid blue arrowhead. When GPS signal is lost, `map pointer` becomes grey triangle (at last known location) and `clickable icon` becomes grey "sniper dot"
![small_Screenshot_20220410_163241_app organicmaps](https://user-images.githubusercontent.com/156656/162636011-838da0d1-7360-48c8-a574-8382d994e954.jpg) ![small_Screenshot_20220410_171840_app organicmaps](https://user-images.githubusercontent.com/156656/162636022-1f86c6d6-51c6-4c62-a665-33f1b96992fb.jpg)

**Comment by mnalis** [comment]
Gallery Trekarta:
When GPS is available, `map pointer` is hollow arrowhead with orange outline,  and `clickable icon` is filled orange arrowhead. When GPS signal is lost, `map pointer` disappears and `clickable icon` becomes animated "radar search"
![small_Screenshot_20220410_163328_mobi maptrek](https://user-images.githubusercontent.com/156656/162636161-6ea6b200-4f8c-473a-96cb-df9e79ce1c67.jpg) 

https://user-images.githubusercontent.com/156656/162636179-2945679e-e548-4db8-8f91-24b92c8cc2f9.mp4
