### ISSUE TITLE
Improve shoulder quest wording to prevent potential mis-taggings

### ISSUE THREAD

**Issue by 10992-osm** [streetcomplete/StreetComplete#3962]
See [this discussion on Talk-GB](https://lists.openstreetmap.org/pipermail/talk-gb/2022-April/028816.html).

Some users appear to be tagging shoulders that may not be sufficiently wide.

We should consider changing the wording, which I personally think reads a bit oddly:

> Does this road have a shoulder?
>A shoulder is a clearly demarcated emergency stopping lane that allows vehicles to stop safely completely beside the traffic lane, although not always (fully) on paved surface.

My concerns about the wording (other than references to width) are in "completely beside" and "on paved surface" (→ "on a paved surface").

**Comment by andrewharvey** [comment]
I think giving users an option answer "a narrow shoulders exists, that bicycles can use but a car can't fit" would also help reduce the mis-tagging.

**Comment by tommycrock** [comment]
How about something like:
A shoulder is a clearly demarcated emergency stopping lane, wide enough for a car to stop safely beside (off) the traffic lane, on a firm surface (not necessarily paved).

**Comment by arrival-spring** [comment]
@andrewharvey How would that answer get tagged?

**Comment by systemed** [comment]
Really the quest shouldn't be enabled in the UK - roads don't have shoulders here, apart from limited-access motorways and a very few roads like them.

**Comment by trigpoint** [comment]
The same user has also tagged a section of urban secondary road with shoulder=no ( the road has a separately mapped cycleway. This quest could rapidly get very very silly indeed if it is asking about normal urban or rural roads.

Other than on motorways and a few 70 mph dual carriageways shoulders just are not a thing in the UK.

I have not seen the actual street complete quest as it appears to not be available in the latest version available on f-droid.

I believe this task should either be disabled in the UK or restricted to expressways, motorways and motor roads along with the above suggested improvements on width.

**Comment by westnordost** [comment]
Here is the filter for the quest: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/shoulder/AddShoulder.kt

So, what exactly is bad with the wording? English is not my native language. Is there a problem with the content or with the wording?

**Comment by tommycrock** [comment]
It's only implicit that it should be wide enough for a vehicle, and that could be a bike. So I'd make it explicit and also clear it means a car. I've tried to make it even clearer the whole car must be off the traffic lane although this was already pretty clear. There was also a missing 'a' in "on a paved surface". I tried to clarify that a grassy verge isn't a (hard) shoulder.

**Comment by trigpoint** [comment]
The wording itself is not an issue.

"A shoulder is a clearly demarcated emergency stopping lane that allows vehicles to stop safely completely beside the traffic lane, although not always (fully) on paved surface."

A mapper has tagged roads that do not match that criteria as yes, which I has commented on but they have yes to reply.

The issue with this quest is that in the UK shoulders only exist on motorways and qa few limited access roads. Other than that shoulders are not a thing.

I have got an old Android phone running with the latest version and am finding that it is asking if rural tertiary and secondary roads have shoulders, which tagging every rural road with shoulder=no would be as spammy as bicycle=yes on residential roads.

To illustrate what a rural road is typically like in the UK, and this is one where I am being asked the question.

https://www.mapillary.com/app/?pKey=181433950428020

Rural roads are typically enclosed by hedges, or in mountainous by walls. There is often a grass verge, where a pedestrian can stand if needed.

Also the presence of a 60 mph legal speed limit on tertiary.secondary roads does not often mean that is in anyway achievable.

**Comment by westnordost** [comment]
There seem to be several issues mentioned. Let's focus on one issue in this ticket: To minimize mistaggings by achieving a clearer wording. For other issues, open a new ticket.

So, regarding the wording, someone mentioned that "vehicle" may be misunderstood as "bicycle", yes? So is there any better wording that would make it clear that what is meant is that it is for cars and other 4-wheeled vehicles?

> A mapper has tagged roads that do not match that criteria as yes, which I has commented on but they have yes to reply.

Okay, TBH that's not really a reason to open a ticket on this issue tracker... maybe he just didn't read the description?

**Comment by westnordost** [comment]
Going back to the mailing list discussion:

> One of the sections they have tagged [with shoulder=yes(, I suppose)] is
> https://www.mapillary.com/app/?pKey=401380041319740

Yes, this is definitely a shoulder. There is even some sort of gravel to have a semi-solid surface. See the wiki page: https://wiki.openstreetmap.org/wiki/Key:shoulder

**Comment by andrewharvey** [comment]
> So, regarding the wording, someone mentioned that "vehicle" may be misunderstood as "bicycle", yes? So is there any better wording that would make it clear that what is meant is that it is for cars and other 4-wheeled vehicles?

motor vehicle

Vehicle alone can be ambiguous if it includes bicycles or not.

**Comment by westnordost** [comment]
motor vehicles, you mean like motorbikes?

**Comment by andrewharvey** [comment]
full width motor vehicles? I don't know....

"wide enough for all vehicles" should be sufficient.

**Comment by westnordost** [comment]
or "vehicles" => "any road user"?

> A shoulder is a clearly demarcated emergency stopping lane that allows **any road user** to stop safely completely beside the traffic lane, although not always (fully) on paved surface.

TBH I kind of think that the current wording is clear enough in that any person with some common sense could not misunderstand it and that this issue has actually been opened for other reasons maybe? But then again, I am not a native speaker and maybe the current wording is really ambiguous. So what about the suggestion above?

**Comment by MikaelBe** [comment]
"A shoulder is a clearly demarcated emergency stopping lane that allows **any motor vehicle** to stop safely completely **outside** the traffic lane **on a hard surface, which may not necessarily be completely paved**.

Not a native speaker either, but I think this might be clearer in terms of conveying that the shoulder surface shouldn't cause the car to slide down into a ditch.

On the other hand, I wouldn't complain if the quest asked for "no shoulder", "bicycle width shoulder", or "full width shoulder".

**Comment by westnordost** [comment]
> On the other hand, I wouldn't complain if the quest asked for "no shoulder", "bicycle width shoulder", or "full width shoulder".

Such distinction would certainly make sense. Though there is no tagging (yet) to distinguish properly between "hard/full shoulders",  and "half shoulders" (and not-broad-enough-for-any-vehicle shoulders)

There is only `verge=*` but I think this would be for verges of grass that are not even a shoulder (e.g. not broad enough, and/or not fit for a vehicle to stop) - definition is a little fuzzy.

**Comment by davidpnewton** [comment]
> Going back to the mailing list discussion:
> 
> > @trigpoint wrote:
> > One of the sections they have tagged [with shoulder=yes(, I suppose)] is
> > https://www.mapillary.com/app/?pKey=401380041319740
> 
> Yes, this is definitely a shoulder. There is even some sort of gravel to have a semi-solid surface. See the wiki page: https://wiki.openstreetmap.org/wiki/Key:shoulder

No it is not a "shoulder" in the sense that should be tagged as such. It is simply a small area at the edge of the road. It cannot be used to safely and fully get a car out of the running lanes of the road. That is a "shoulder" which should be tagged as such and as has been correctly pointed out they are very rare in the UK. The only instance I can think of one existing outside of a motorway is the A2 in between the M25 and M2.

**Comment by westnordost** [comment]
Well, see the wiki page. Sure, you cannot safely change into a soft shoulder and then slow down like you would do with a hard shoulder, but you can slow down and then cross into the soft shoulder. Nobody is disputing the fact that a hard shoulder is safer / more useful.

**Comment by mnalis** [comment]
> full width motor vehicles? I don't know....

Maybe I'm missing something obvious, but if we mean it has to be wide enough for a **_"car"_**, than why don't we simply say **_"car"_** (but keep trying to use much less specific "vehicle" word)? Most people will have a pretty good idea how wide average car is (and even if they're off it is surely only by small amount?)

> "wide enough for all vehicles" should be sufficient.

[This](https://en.wikipedia.org/wiki/Crawler-transporter) is full-width motor vehicle too (and cars are those small thingies on the parking beside it)
