### ISSUE TITLE
"source:addr=FHRS Open Data" and shops that do not exist

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3968]
In revision 7, and FHRS ID was added to this node:
https://www.openstreetmap.org/way/239228134/history

In revision 8 and 9 the type/brand of shop was changed, so all the stuff in https://github.com/mnalis/StreetComplete-taginfo-categorize is stripped out, including (quite correctly) FHRS ID (see https://github.com/mnalis/StreetComplete-taginfo-categorize/issues/2) but `source:addr=FHRS Open Data` is left, despite referring to a source which is no longer present...

There are 34k of these, comprising 38% of source address in the UK:
https://taginfo.openstreetmap.org.uk/keys/source:addr#values

So I'd think potentially worth special casing to delete this key if it equals that value.

Also in the note that triggered this:
https://www.openstreetmap.org/note/3115259

The address appears to have changed too confusingly:
https://ratings.food.gov.uk/business/en-GB/426284
https://ratings.food.gov.uk/business/en-GB/424773/Pret-A-Manger-Unit-1-London

**How to Reproduce**
Mark as not present a shop with "source:addr=FHRS Open Data".

**Versions affected**
v42

**Comment by matkoniecz** [comment]
Why `source:addr` would become incorrect if address data was unchanged?

**Comment by kmpoppe** [comment]
It doesn't become inherently wrong but it's not verifiable anymore because the FHRS database will no longer show the information associated to the ID the has since been removed from the object.

**Comment by Cj-Malone** [comment]
I'm against `source:addr=FHRS Open Data` being added in the first place, I only do `source=FHRS Open Data` on the changeset. But I don't think it's StreetCompletes job to remove them.

> The address appears to have changed too confusingly:
> https://ratings.food.gov.uk/business/en-GB/426284
> https://ratings.food.gov.uk/business/en-GB/424773/Pret-A-Manger-Unit-1-London

FYI I'm pretty sure that is [this Pret](https://www.openstreetmap.org/node/874743800). The [one](https://www.openstreetmap.org/way/239228134) were talking about doesn't seem to have a FHRS listing yet.

**Comment by matkoniecz** [comment]
> It doesn't become inherently wrong but it's not verifiable anymore because the FHRS database will no longer show the information associated to the ID the has since been removed from the object.

You can still check the history of the object.

> I'm against `source:addr=FHRS Open Data` being added in the first place

I would be tempted to classify it this way. Alternative is starting complicated interpreting of values of various objects which will grow quickly into something complex and annoying.

**Comment by peternewman** [comment]
> I'm against `source:addr=FHRS Open Data` being added in the first place, I only do `source=FHRS Open Data` on the changeset.

I think I'd broadly agree with you there.

> But I don't think it's StreetCompletes job to remove them.

Even when it's removed the related info? This feels like something a human editor would probably/hopefully do, and seems to be pretty trivial to do with a bit of basic logic.

> FYI I'm pretty sure that is [this Pret](https://www.openstreetmap.org/node/874743800). The [one](https://www.openstreetmap.org/way/239228134) were talking about doesn't seem to have a FHRS listing yet.

Ah yes, that seems most likely, I was going to comment in https://www.openstreetmap.org/note/3115259 but then I saw you'd already commented before :laughing: .

> Alternative is starting complicated interpreting of values of various objects which will grow quickly into something complex and annoying.

I don't think it needs to be very complex at all. We currently have a list of keys we know we're going to remove (managed in https://github.com/mnalis/StreetComplete-taginfo-categorize ), we just extend that to also have some key-value pairs we'll also remove. I don't think we need to do anything clever like checking if there was an FHRS ID, we don't bother with that level of complexity and interaction for the existing keys, so I don't see why we need to if there are values too.

**Comment by Cj-Malone** [comment]
> Even when it's removed the related info? This feels like something a human editor would probably/hopefully do, and seems to be pretty trivial to do with a bit of basic logic.

It hasn't though, it's removed `fhrs:id`, not any `addr:*`. I really don't like `source:addr=FHRS Open Data` but I don't remove it when a shop closes. I only remove it when I've used another source to amend the address, or I've updated `fhrs:id` and put `source=FHRS Open Data` on the changeset.

Maybe StreetComplete should remove `source:addr=FHRS Open Data` if any of the address quests are answered, but I don't think they run on shop nodes anyway.

**Comment by matkoniecz** [comment]
Looking at it: `source:addr=FHRS Open Data` is correct, even if mostly useless. SC was not touching address.

The root of problem is that `source:addr` should not be added or at least mention `fhrs:id` value, so it would not be confusing once shop is replaced.

Address at this location is still based on FHRS Open Data.

One may introduce special rewrite rule to deal with it, but I would rather (if I would be active in a given area or knew that it has a clear support from local community) either delete all `source:addr=FHRS Open Data` or rewrite them to something like `source:addr=FHRS Open Data (fhrs id of this object is 3872328742378)` 

In fact, if there would be consensus among local community (on their talk mailing list?) I could run either version of bot edit, but I would likely not propose it.

**Comment by westnordost** [comment]
So... what's the conclusion?

**Comment by mnalis** [comment]
> It doesn't become inherently wrong but it's not verifiable anymore because the FHRS database will no longer show the information associated to the ID the has since been removed from the object.

Sure, but I do not think it is something that SC needs to handle specially. It might no longer be **verifiable** (without fetching related history, at least), but FHRS is **still** the source of that address data, so leaving that tag `source:addr=FHRS Open Data` as-is (as it is currently being done) is **not incorrect**.

<details>

e.g. imagine if building was mapped as it was visible via Bing satellite view, and it was thus also mapped with `source=bing`. Now is Bing view was updated with newer images, and it happens that building is now **not** visible anymore due to it being occluded by clouds or snow cover, is `source=bing` now incorrect and should be removed, as it is no longer verifiable?  In my opinion no, and thus `source=bing` should stay when users edit unrelated tags of that building.

</details>

> So... what's the conclusion?

In my opinion, **no action is needed to be taken by SC** (but outside of SC people might want to put `source:addr=FHRS Open Data` in _changeset comments_ instead of _tags_ in the future, to preemptively avoid issues like that). 

(But of course it is only my opinion, not necessarily the source of universal truth  :upside_down_face:)

**Comment by peternewman** [comment]
> It hasn't though, it's removed `fhrs:id`, not any `addr:*`. I really don't like `source:addr=FHRS Open Data` but I don't remove it when a shop closes.

Would you not add the relevant FHRS ID to that source tag though? I sort of assumed people doing manual edits would do some kind of admin of that field if it changed significantly.

> Maybe StreetComplete should remove `source:addr=*` if any of the address quests are answered, but I don't think they run on shop nodes anyway.

Retail and shop are both included:
https://github.com/streetcomplete/StreetComplete/blob/3ebe33558231df618c330e9f50120257652fc02a/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L215-L219

**Comment by matkoniecz** [comment]
> Retail and shop are both included:

as building types which is asked for areas only, not for shop nodes (so one more poor piece of tagging should be present - to map shop and building together as a single area)

**Comment by matkoniecz** [comment]
I consider it as a problematic tagging in general: so I want to repeat:

if I would be active in a given area or knew that it has a clear support from local community then I would either 

(a) delete all `source:addr=FHRS Open Data` 
or
(b) rewrite them to something like `source:addr=FHRS Open Data (fhrs id of this object is 3872328742378)` 

In fact, if there would be consensus among local community (on their talk mailing list?) I could run either version of bot edit, but I would not propose it. As obtaining consensus for bot edit is 90% of work necessary to do it and it is far from certain that there would be an agreement.

**Comment by Cj-Malone** [comment]
I don't think it's worth bringing it up on Talk GB, there will never be consensus.
