### ISSUE TITLE
Opening hours: allow to choose "every n-th weekday a month" 

### ISSUE THREAD

**Issue by NotSoImportant** [streetcomplete/StreetComplete#3969]
**Use case**
Need to describe regular, non-weekly opening hours
- e.g. "every 1st and 3rd tuesday a month" 

**Proposed Solution**
Toggle button next to the weekdays
- only appears when checked
- default: "every"
- if toggled a popup with 5 checkboxes and an ok button, if closed shows selected values as text in the toggle button right side

![IMG_20220418_002225](https://user-images.githubusercontent.com/35758921/163734397-a7fa9577-2f36-447a-9fcc-7ab80377f48f.jpg)

Result could be displayed similar to osm syntax (_weekday_range_):
- Tue. [1,3] = first and third Tuesday a month
- Sat. [-1] = last Saturday a month

![IMG_20220418_004039](https://user-images.githubusercontent.com/35758921/163734936-3d8f7124-6bf7-4d04-b652-c6b5cbe2368c.jpg)

Imho this is still clean to read.

**Comment by westnordost** [comment]
This will not be implemented.

Opening hours like this are really really rare. A note should suffice. 

Also, it litters the interface for such 0.1% cases that may confuse users in the 99.9% cases, which is the reason I would not even accept a PR for that.

**Comment by NotSoImportant** [comment]
Fair enough, thanks. Although I found several of these already, a note could probably be good enough. 

Seems I need to change my mind about "cannot be answered", when in fact I could, but just not with the options available.

**Comment by NotSoImportant** [comment]
Out of interst: how will this be displayed for re-survey?

**Comment by westnordost** [comment]
Opening hours that are valid but cannot be represented in the UI are not resurveyable in the app, i.e. are never asked again

**Comment by NotSoImportant** [comment]
Very interesting 👍
This is indeed helpful to take such priority decisions. 

So this "test" is not a classic test with assertion, but rather a way of fetching and then manually checking percentage of supported and unsupported opening hour patterns, right? 
When is it run / where can somebody see the output directly (or even trigger it maybe) ?

I was checking opening hours with weekday range using [overpass](https://overpass-turbo.eu/s/1hPw). Where I found ~250 compared to &gt; 100.000 others in south of Germany.

**Comment by westnordost** [comment]
It's not a test at all. It's a java program that outputs its output to the console.
