### ISSUE TITLE
Non-unique Changeset Comments irritate users

### ISSUE THREAD

**Issue by kmpoppe** [streetcomplete/StreetComplete#3972]
In [this](https://t.me/osmappsundeditoren/3117) Telegram message a user expressed irritation about three changesets ([119813682](https://osm.org/changeset/119813682), [119813700](https://osm.org/changeset/119813700), [119813707](https://osm.org/changeset/119813707)) being split although them being created within the same hour and having the same changeset comment ("Add path surfaces").

The edits have been split along the value of the `StreetComplete:quest_type` key in the changeset. These are different for each of the three CS, so there's nothing wrong code-wise, yet it would be less irritable when the quests had unique comments.

These are the source-files with changeset comments that are non-unique:

**Add maximum heights** in
 * `max_height\AddMaxHeight.kt` and
 * `max_height\AddMaxPhysicalHeight.kt` 

**Add path surfaces** in
 * `surface\AddCyclewayPartSurface.kt`,
 * `surface\AddFootwayPartSurface.kt` and
 * `surface\AddPathSurface.kt`

**Add wheelchair access to toilets** in
 * `wheelchair_toilets\AddWheelchairAccessToilets.kt` and
 * `wheelchair_toilets\AddWheelchairAccessToiletsPart.kt`

**Determine whether construction is now completed** in
 * `construction\MarkCompletedBuildingConstruction.kt` and
 * `construction\MarkCompletedHighwayConstruction.kt`

I would recommend to change the CS comments as follows:

 * `max_height\AddMaxHeight.kt` [keep]
 * `max_height\AddMaxPhysicalHeight.kt` "Add maximum physical heights" 
 * `surface\AddCyclewayPartSurface.kt` "Add cycleway path surfaces"
 * `surface\AddFootwayPartSurface.kt` "Add footway path surfaces"
 * `surface\AddPathSurface.kt` [keep]
 * `construction\MarkCompletedBuildingConstruction.kt` "Determine whether building construction is now completed"
 * `construction\MarkCompletedHighwayConstruction.kt` "Determine whether highway construction is now completed"
 * `wheelchair_toilets\AddWheelchairAccessToilets.kt` [keep]
 * `wheelchair_toilets\AddWheelchairAccessToiletsPart.kt` "Add wheelchair access to toilets in another object"

Any feelings on this?

K

**Comment by kmpoppe** [comment]
Thanks for removing the bug label, the Issue template insisted ;)

**Comment by westnordost** [comment]
>Thanks for removing the bug label, the Issue template insisted ;)

FYI

![image](https://user-images.githubusercontent.com/4661658/163870371-74a3a0ae-731b-430d-a37a-41cefe1d094a.png)

**Comment by kmpoppe** [comment]
> FYI

Dark mode problems ... Didn't really see it at first glance 🤦‍♂️

**Comment by kmpoppe** [comment]
> E.g. will the `AddBusStopLit` be grouped with the other "Add lit" quests or be grouped with the other bus stop quests?

That'll be interesting to think about a solution because any groupings (like "bus related stuff" rather than "light related stuff") would have to be kept together for the time the CS are open, which would then feel strange if bus and light related quest groups would have to be grouped (so it would need a prioritization of one group over another ...) That's a task and a half!

> Also, e.g. the "add surface to sidewalks left and right of the street" is UX wise, technically and what it tags very different from the other surface quests and one of the main reasons to put every quest into its own changeset is so that it can be found out easily if there a systematic problem with any of the above (UX, logic, ....).

We are not arguing about whether `StreetComplete:quest_type` is the right way to split CS to have a way to find these systematic problems. That's a keeper.

**Comment by westnordost** [comment]
> That'll be interesting to think about a solution because any groupings (like "bus related stuff" rather than "light related stuff") would have to be kept together for the time the CS are open, which would then feel strange if bus and light related quest groups would have to be grouped (so it would need a prioritization of one group over another ...) That's a task and a half!

Not, not automatically of course! I meant, for the developer(s) to decide.

**Comment by kmpoppe** [comment]
> Not, not automatically of course! I meant, for the developer(s) to decide.

That's obvious, but:
 * Upload 1: AddBusStopLit and AddPitchLit ==> Group to "Add information about lighting"
vs.
 * Upload 1: AddBusStopLit and AddBinStatusOnBusStop ==> Group to "Add information to bus stop"
 * Upload 2 after 59 mins: AddPitchLit ==> The first group has to be kept because the lighting of a pitch is not a bus stop and a second CS has to be created.

What to do in these two scenarios will have to be decided beforehand from the developer's side which I was thinking of ... Not even thinking about a dynamic grouping left to the user.

**Comment by westnordost** [comment]
> dynamic grouping left to the user.

I think there is still a misunderstanding. The grouping would be hardcoded into code. E.g. 
```kotlin
class MyQuestType : QuestType {
    override val groupToChangesetOf = "AddPathSurface"
}
```

**Comment by kmpoppe** [comment]
Ah, so any one quest is only in one group. Well, then it's "only" a matter of time until we found working groups for all 135 quests :-)

NTL, shouldn't we change the CS comments until then - or are you planning on getting the grouping done for the next version or something?

**Comment by westnordost** [comment]
Not planning anything, just entertained the thought.

**Comment by westnordost** [comment]
Anyway, I think your idea to be more specific in the changeset comments is good
