### ISSUE TITLE
“Unable to answer” note for “is this still here”

### ISSUE THREAD

**Issue by Animyos** [streetcomplete/StreetComplete#3973]
When creating a note using the “Unable to answer button” on a “is this still here” quest, Streetcomplete doesn’t put enough information into the note for other mappers to understand **what** exactly needs verification about whether it’s still there.
(See screenshot below for an example in German)
![ksnip_20220419-104430.png](https://user-images.githubusercontent.com/82672160/163962822-afee41fc-9d26-4585-ba4a-05b4c6e1fabd.png)
Kind regards
Animyos Fox

**Comment by Animyos** [comment]
P.S. Yes, I know that you could look at the node linked in the note, but I think it would make things easier when it’s directly mentioned what should be verified for existence.

**Comment by westnordost** [comment]
Clicking the link to the object will yield any necessary information, I see no issue with requiring to click a link. Besides, you can also usually see it on the map.
