### ISSUE TITLE
[v43.0-beta1] Better wording in German for the "Is there an air compressor available here?" quest.

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#3974]
I think instead of "Gibt es hier Pressluft?", "Kann man hier den Reifendruck prüfen?" or "Gibt es hier einen Luftkompressor?" would be a better wording.

**Versions affected**

v43.0-beta1

**Comment by FloEdelmann** [comment]
I agree that the current wording sounds a bit off, I like your second suggestion better.

Note that you can improve translations yourself: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by legofahrrad** [comment]
Hey, I commented on the current German translation already as well (on POEditor):
> "Pressluft" habe ich noch nie gehört, ist "Druckluft" vielleicht besser? Evtl. auch "Gibt es hier einen Druckluft-Kompressor"?

So, @westnordost what do you think?

**Comment by tiptoptom** [comment]
> Hey, I commented on the current German translation already as well (on POEditor):
> 
> > "Pressluft" habe ich noch nie gehört, ist "Druckluft" vielleicht besser? Evtl. auch "Gibt es hier einen Druckluft-Kompressor"?
> 
> So, @westnordost what do you think?

I only know "Presslufthammer" =)

**Comment by FloEdelmann** [comment]
> commented on the current German translation

For reference, here is the comment on POEditor: https://poeditor.com/projects/po_edit?id_language=55&id=97843#showComments368651739

**Comment by westnordost** [comment]
changed it. In the future, please just comment on poeditor to find a better wording.
