### ISSUE TITLE
Bug: SC keeps asking for sidewalk

### ISSUE THREAD

**Issue by NotSoImportant** [streetcomplete/StreetComplete#3976]
Initial:
`sidewalk=both`

After answering the quest "does this street have a sidewalk" (or similar translation):
```
sidewalk=both
sidewalk:left=separate
sidewalk:right=yes
```
SC keeps asking the quest for the same part of the road endlessly

![IMG_20220420_102014](https://user-images.githubusercontent.com/35758921/164183925-61b58419-c9c3-4b7e-a102-15bfb7ce20cb.jpg)

**Versions affected**
Sc v 42.0

**Comment by westnordost** [comment]
If I remember right,
```
sidewalk=both
sidewalk:left=separate
sidewalk:right=yes
```
is parsed as invalid because contradictory parsing and thus it is asked again.

Do you mean that StreetComplete itself tags roads this way? If yes, do you have an example where this happened?

**Comment by NotSoImportant** [comment]
Ah I checked again and (other than I first wrote) it initially was
```
sidewalk=both
sidewalk:left=separate
```
So by this already invalid before. 
Then after SC asked, `sidewalk:right=yes` was added. 

It could be automatically fixed if SC would remove the "sidewalk" tag after the quest has been answered with "left" and "right". What do you think?

**Comment by westnordost** [comment]
Yes, it is a bug that StreetComplete doesn't remove `sidewalk`

**Comment by NotSoImportant** [comment]
Thank you 🎉
The tests you added look good 🙂
