### ISSUE TITLE
Don't ask for opening hours for leisure=horse_riding

### ISSUE THREAD

**Issue by Hufkratzer** [streetcomplete/StreetComplete#3978]
According to [taginfo](https://taginfo.openstreetmap.org/tags/leisure=horse_riding#projects) and your [source code](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt) you ask for opening hours for leisure=horse_riding, but you don't ask it for leisure=sports_centre
> because these are often sports clubs which have no walk-in opening hours but training times

I think this is even more true for leisure=horse_riding. 

Only 218 of 15k (1,5%) leisure=horse_riding have some opening_hours tagged, which is a lower percentage than for leisure=sports_centre (7020 / 215k = 3,3%). This is probably not incomplete tagging but rather reflects reality. There may be an office somewhere on larger facilities which may have fixed opening hours, but this does not mean that the whole facility is closed when the office is closed. There are often privately owned horses on such facilities and their owners may need access to them independently from opening hours.

**Comment by Hufkratzer** [comment]
The bug label was added automatically. I didn't want to say that it is a bug; I just didn't find a more appropriate way to submit this issue.

**Comment by westnordost** [comment]
sports_centre was removed from this list in #1423

**Comment by westnordost** [comment]
yes I know, I was just providing some context
