### ISSUE TITLE
"Disable Automatic Zoom" feature

### ISSUE THREAD

**Issue by basings** [streetcomplete/StreetComplete#3980]
**Use case**

When you click on an icon, e.g. a street that's much longer than the current visible part, the app zooms out and it takes a second for this although I just want to answer the question. I don't want to see the whole thing. When you're finished it zooms back, so it's double the time.

**Proposed Solution**

- new entry in settings to enable/disable automatic zoom
- enable/disable automatic zoom

**Comment by mnalis** [comment]
Related: StreetComplete follows Android system settings, so if you go there in `Developer options` and set `Animator duration scale` from `1x` to `off`, the change will happen **_instantly_** instead of zooming-in/out animation (You can also opt there to just make it faster - or slower - instead of disabling it completely).

**Comment by basings** [comment]
@mnalis Thank you! I didn't know about that setting. I'll test it over the next days. It's still moving the visible area but it's faster.

**Comment by 10992-osm** [comment]
> Related: StreetComplete follows Android system settings, so if you go there in `Developer options` and set `Animator duration scale` from `1x` to `off`, the change will happen **_instantly_** instead of zooming-in/out animation (You can also opt there to just make it faster - or slower - instead of disabling it completely).

Where does one find that?

**Comment by basings** [comment]
@10992-osm tap the Build Number option 7 times in the android settings. You can then find a developer tools entry

**Comment by westnordost** [comment]
> I just want to answer the question. I don't want to see the whole thing

You need to know the feature's extend to properly answer a quest though. Let's say you are asked for the surface of the road here but the road goes on for another few hundred meters. You need to check at the other end too.

**Comment by cyclingcat** [comment]
On the other hand see issue #3346 - the automatic zoom currently doesn't work reliably due to a bug in tangram.

The cycling cat

**Comment by basings** [comment]
@westnordost I agree! 

I might have not given the best example for why I created this issue. It always boils down to that the app zooms although it wouldn't be neccessary. 

- When selecting a parking lot, it zooms in, although the current zoom level would have been sufficient.
- If you are at a lower zoom level and select a road icon, the map zooms in, although the road would have been perfectly visible.

I entered many entries now, and the auto zooming annoys me most of the time. That's why I created the issue. Disabling the animation helps a lot as suggested by mnalis but I need to test it in the field today. I'll report back when I solved some hundreds quest.

Other somewhat related issues I saw now when I looked for examples: 

- If a road is in the lower part of the screen (fully visible) and you click on the icon, the road is highlited in full extend, the map doesn't move and the road becomes hidden by the popup message which contradicts the final goal to see the full feature when entering the information.
- simetimes it zooms too much into the map such that the road is not visible in full extend and cuts the ends.

**Comment by westnordost** [comment]
So, not to zoom at all is no option because this may result in wrong answers.

And when to zoom and when not to zoom is a calibrating issue. If you feel adventorous, you may try to play around with this "knob" yourself by checking out the source code and deploying a debug version on your phone. Would you be up to it? Then I can point you at the relevant portions of the code and how to setup the environment.

**Comment by basings** [comment]
@westnordost I was in the field now and I had the animations disabled which speeded everything up which was nice. I guess the annoying part was now that when I click on a road icon it zooms in and my position wasn't in the view anymore althoughit's just the road ahead of me and I clicked on it while approaching the road but not yet being there. 

I'd need to get familiarized again with android studio, it's been a (long!) while since I checked it out. I haven't done any real android developing. I'll check it out and will get back to you but I din't know when I'll get to it.

**Comment by westnordost** [comment]
Well good to hear you once checked it out. So you know the process: Download and install Android Studio, checkout this project via git and open it in Android Studio, connect your phone via USB + enable and allow debugging and press the ![image](https://user-images.githubusercontent.com/4661658/164429694-daebe788-9832-4071-a624-f936fd640d85.png) icon to run, basically.

In Android Studio, press `Ctrl`+`N` and type `FocusGeometryMapComponent` to navigate to that class, the logic in question is in the function `beginFocusGeometry`.

**Comment by basings** [comment]
@westnordost Hey, I checked out the master branch and get 5 errors with build.grade.kts and Gradle sync failes. Hence, I can't run the app. I also checked out v41 but that's the same. Problem with my install?

```
Unresolved reference: isCheckReleaseBuilds: 79
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
...
```

**Comment by matkoniecz** [comment]
It is compiling for me. I would try regular - check have you checked out latest master, pull, restart, clear cache, upgrade dependencies if Android Studio suggests it.

If it does not help: specify revision being tried and link gist/pastebin with full error log.

**Comment by basings** [comment]
@matkoniecz just wanted to let you know that it works now. Reading is key. I just commented out line 79ff of build.gradle. I can start playing now.

**Comment by basings** [comment]
I tweaked the settings and could improve the zoom feature but I want to test it further and familiarize myself with the surrounding code more. I'll fork and create a pull request when I'm happy.

**Comment by westnordost** [comment]
Any update on this?

**Comment by hamishmb** [comment]
> Related: StreetComplete follows Android system settings, so if you go there in `Developer options` and set `Animator duration scale` from `1x` to `off`, the change will happen **_instantly_** instead of zooming-in/out animation (You can also opt there to just make it faster - or slower - instead of disabling it completely).

Would this be why the zoom sometimes jolts in and out for me? Maybe Android changes the setting under high load or low power mode? I haven't noticed that it always behaves differently in low power mode, though.

**Comment by westnordost** [comment]
Closing as there is no reply. Feel free to create a PR if you have something.
