### ISSUE TITLE
Add "building part" option to building quests

### ISSUE THREAD

**Issue by Squamoto** [streetcomplete/StreetComplete#3988]
**Use case**
A lot of buildings in OSM are actually just parts of an adjacent building (at least in my area). This leads to SC users solving all kind of quests for this building part, including street and house numbers. In the end, we have duplicate addresses and an incorrect building=* tag. Examples:

https://www.openstreetmap.org/way/484951811
https://www.openstreetmap.org/way/474315937
https://www.openstreetmap.org/way/503185814

**Proposed Solution**
An easy solution would be to add an "It's a building part" option to these quests and to leave a note for this building, so that someone can fix the building manually.

Another option could be to let the SC user select the adjacent building, where this building part belongs to and automatically merge the buildings by tagging the building in question with building:part=* and increasing the size of the adjacent building to include the new building part.

**Comment by matkoniecz** [comment]
> An easy solution would be to add an "It's a building part" option to these quests and to leave a note for this building, so that someone can fix the building manually.

You can leave note already. Which should be used already if app exists question where data being asked about does not exist

> Another option could be to let the SC user select the adjacent building, where this building part belongs to and automatically merge the buildings by tagging the building in question with building:part=* and increasing the size of the adjacent building to include the new building part.

See #3351

https://github.com/streetcomplete/StreetComplete/issues/3351#issuecomment-939315915
