### ISSUE TITLE
Fix #1977 for the new four option quests

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#3993]
**Use case**
Fix #1977 but for the new four option quests (seating and card types).

**Proposed Solution**
Either shrink the gap between answers, push the question up a bit again or at least make the default options match (as I've just spotted).

**Comment by peternewman** [comment]
> at least make the default options match (as I've just spotted).

See #3994 for this part of it...

**Comment by westnordost** [comment]
Ok I don't know what you think needs to be done here and wether it is already done / how much of it is done. Please open a new issue with screenshots to illustrate if there is still an issue somewhere.
