### ISSUE TITLE
Selecting English (Australia) as app language displays Arabic characters

### ISSUE THREAD

**Issue by toddletoon** [streetcomplete/StreetComplete#4011]
Having English (Australia) seleced as the apps default language displays Arabic text in some menus and buttons. An example is the "Show all notes" menu selection being in Arabic, but "Keep screen on" menu option is in English.

**How to Reproduce**
Have English (Australia) seleced as the apps default language

**Versions affected**
StreetComplete v42.0
Android 12
Samsung Galaxy S10+

![Screenshot_20220505-124823_StreetComplete](https://user-images.githubusercontent.com/97598030/166856968-207ad2f0-949b-4a56-afa7-2558c5106061.png)

**Comment by matkoniecz** [comment]
Try upgrading to v43.

**Comment by mnalis** [comment]
F-droid is also at `43.0` - https://f-droid.org/en/packages/de.westnordost.streetcomplete/#latest so it should be easy to upgrade
