### ISSUE TITLE
Translation export in poeditor platform is a bit buggy

### ISSUE THREAD

**Issue by Mazurs** [streetcomplete/StreetComplete#4014]
When exporting the strings as .po file, it loses the original string and instead shows context.

 For example, when I download StreetComplete project in Latvian, I see a translation unit like this:

> #:
> msgid "produce_chili"
> msgstr "Čili"

In the msgid I should be able to see original string, not the internal identifier.

At first I thought that it's the issue with the with the poeditor site, so I sent them the issue report and this is what they replied (redacted):

> There is nothing wrong with the exported file. You are receiving this entry because the owner of the project has set a label on that string. The string you are talking about 'Chili' is the corresponding msgstr of the msgid 'produce_chili' in the English (US) language, the Default Reference Language set by the project owner. The Default Reference Language is the language shown in the Language Page, where you translate the strings.

> That's why when you translate you see this text (Chili) and in the exported file you see this text (produce_chili).

**How to Reproduce**
* Go to the poeditor export page for this project and in my case, the Latvian language
* Select the .po (Gettext PO) file option and press Export.
* Examine the downloaded file.

**Comment by matkoniecz** [comment]
Is there some specific usecase where this matters?

Note that in Android project translation text is matched to identifiers such as produce_chili - not to original text (which may be not unique).

**Comment by Mazurs** [comment]
@mnalis 

> there are some advantages, surely - e.g. if a misspelling of original English text is corrected, not all translation need to be redone from scratch as they would need to be otherwise

The PO format does account for that. In the [po format](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) page this kind of reference is placed after the "#:"

In the chilli example, the correct way would be

> #: produce_chili
> msgid "Chili"
> msgstr "Čili"

**Comment by Mazurs** [comment]
@matkoniecz

> Is there some specific usecase where this matters?

My usecase is that I usually translate with desktop translation tools, that have integrated translation tools, like translation memory and terminology database. These tools can help translators to be more consistent and more productive.

If the exported .po file deviates from the spec, the tooling and the workflow doesn't work.

> And in general - why it should be considered as a bug/problem?

That is up to you. If other translators aren't using external translation tools that use .po format, then it doesn't matter. I already completed the translation process in the web app, so I won't benefit much if it gets fixed, but I just thought you might want to know.

> Note that in Android project translation text is matched to identifiers such as produce_chili - not to original text (which may be not unique).

I already touched on that point in my replay to @mnalis.

**Comment by westnordost** [comment]
Localization on Android doesn't work with source strings but with source ids. When importing the [`strings.xml`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/values/strings.xml) to POEditor as a source which contains both the ids and strings in a language, one has the option to also overwrite the "translations" in a selected language, so it can be populated with the actual source strings and not just the ids.

---

As far as Android is concerned, the **identifier** of the message is `produce_chili` and "Chili" is just the default translation for that. And that's how POEditor seems to handle this as well. 

I don't know about the po-spec, but if the `po` format cannot account for the case that the identifier is a different string than the source string, then you should not export to `po` but e.g. to `csv` - I am sure software support for that format should be just as fine.

If on the other hand the export really should look like this

> #: produce_chili
> msgid "Chili"
> msgstr "Čili"

, even though `produce_chili` is not the "label" but the identifier and `Chili` is not the identifier but the source string, then I have to play the ball back to POEditor folks. As said, I don't know much about the po-spec.
