### ISSUE TITLE
Available old map tiles not used

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4015]
When map tiles are older than 14 days, the files will remain in the cache, but the tiles are not displayed.
This can lead to situations where map data is available, but there is no background map shown.

**How to Reproduce**
1. Have a fresh install of StreetComplete
2. Download two areas (manual or automatic doesn't matter)
3. Wait a week
4. Open StreetComplete and download one of the areas again
5. Wait another week
6. Disable internet connection
7. Open StreetComplete and check both areas
8. See that map and quests in the area only downloaded 2 weeks ago has disappeared (not totally surprising)
9. See that map in the area downloaded 1 week ago has disappeared, but quests are still shown
10. Check `[internal storage]/Android/data/de.westnordost.streetcomplete/cache/tile_cache` and see a bunch of 2 week old files

So it seems the tile cache prefers not showing tiles over showing "too old" tiles.
At the same time the old unused tiles are not deleted, and apparently just sitting around waiting until the cache reaches maximum size.

Suggestions for solution, in order of my personal preference:
* Use available tiles if there is no internet connection (and download them again if there is connection)
* Always download map tiles when downloading an area to have the same download time for both
* Delete tiles after 14 days, as they aren't used for anything

**Versions affected**
StreetComplete 42.0 (F-Droid)

**Comment by westnordost** [comment]
Hmm, as you know, the cache is managed by OkHttp. I am not sure if it allows such control over it. 

Anyway, the way your suggestion could work is to let the `MapFragment` listen to connectivity changes and store the connectivity state (connected to internet or not) in a local boolean variable.
Then, in `MapFragment.createHttpHandler` in `configureRequest`, use the cache control with very large `maxStale` if not connected and otherwise the normal one.

**Comment by Helium314** [comment]
Ok, I got it working and more or less ready for PR, but I noticed that it would be possible to have different `cacheControl` for `MapFragment` (which I understand goes to Tangram for downloading tiles when scrolling) and `MapTilesDownloader` (which downloads tiles as part of the data data download).
I think it would be ok to always set longer `maxStale` in `MapFragment`, independent of connection, because old map tiles will be replaced when downloading data anyway, and without data the importance of having recent tiles is rather low.

**Comment by Helium314** [comment]
This alternative would also reduce problems with a bad internet connection (online, but tiles can't be downloaded)

**Comment by westnordost** [comment]
Hmm, right
