### ISSUE TITLE
Quest suggestion: Direction of travel affected by traffic signals

### ISSUE THREAD

**Issue by fnordiff** [streetcomplete/StreetComplete#4018]
### General
Affected tag(s) to be modified/added: [traffic_signals:direction](https://wiki.openstreetmap.org/wiki/Key:traffic_signals:direction)
Question asked: **What is the direction of travel affected by the traffic signals?** (Ask only for nodes which are part of exactly one highway.)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

If traffic lights are tagged on all incoming paths to an intersection and this tag is missing, then a router could falsely rate the route lower because it recognizes several separate traffic lights.

The three values ​​[forward|backward|both] are widely used and are included in the presets of iD and JOSM.

### Ideas for implementation

**Element selection:** 
Ask for any
- node, that is 
- tagged with <code>highway=traffic_signals</code> and
- has <code>traffic_signals:direction</code> either not tagged or value != <code>[forward|backward|both]</code> and
- belongs to exactly one <code>highway=</code> (ignore other ways like <code>landuse=</code>)

**Metadata needed:** 

**Proposed UI:**
- Show nearby traffic lights to help the user identify the queried traffic light (I believe the bench quest behaves similarly: when asking if the bench has a backrest, other nearby benches are shown)
- Display three answer buttons, each representing a road with arrows oriented like the map (I believe the oneway quest and the steps incline quest behave similarly)
- The two answers "Arrow in one direction" and "Arrow in opposite direction" lead to <code>traffic_signals:direction=forward</code> and <code>traffic_signals:direction=backwards</code> respectively
- The answer "Arrow in both directions" leads to <code>traffic_signals:direction=both</code>
- If the highway is one-way and the selected answer is not the direction of the highway, display a security prompt "Are you sure...?"

**Comment by 10992-osm** [comment]
Sounds good.

> * clock4 Applies to a reasonable number of map data (Worth the effort)

There seem to be quite a few elements (although I don't know how to check how many (and what type of) ways a node is in):

[https://overpass-turbo.eu/s/1igd](https://overpass-turbo.eu/s/1igd)

> * If the highway is one-way and the selected answer is not the direction of the highway, display a security prompt "Are you sure...?"

Also, is it actually worth asking worth asking for one-way roads?

**Comment by FloEdelmann** [comment]
Maybe related to #3118?

**Comment by mnalis** [comment]
Also, it might be problematic to determine which traffic signal is it exactly? Not all of them need to be mapped (it is quite conceivable that only some of them are mapped), and even if location is exact, there might be multiple of them. e.g. [traffic_signal=blinker](https://wiki.openstreetmap.org/wiki/Key:traffic_signals) is often placed atop/near `traffic_signals=signal` for problematic intersections, but facing different direction, or intersections have different ones for [pedestrians/cyclists/cars](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Tagging)  etc.

**Comment by westnordost** [comment]
I don't think this quest satisfies the 💵 Valuable Surveyors / 💤 No spam point in the guidelines. 

In particular, shouldn't this value be deducable more efficiently from where the node is put? E.g. if it is on the intersection point, i.e. the intersection is probably mapped in less detail, it would be for all directions and if it is mapped on the actual position of the traffic lights, it would be towards the direction of the intersection.

Someone using JOSM, Vespucci etc. will have a better overview over the layout of the intersection, i.e. how it is mapped exactly, to derive the proper value. I am specifically thinking about more complex intersections.

This data should better be gathered with e.g. MapRoulette.

**Comment by fnordiff** [comment]
regarding one-way streets:
I can imagine that a one-way street is allowed in the opposite direction for bicycles, for example. Does the traffic signal also apply to bicycles driving in the opposite direction? I can't answer that based on an aerial image.

And many traffic signals in one-way streets already have <code>traffic_signals:direction</code> tagged. There may be reasons for this. And since these traffic signals are no longer queried they do not spam the users.

For example, in the Berlin area you can search for traffic lights as part of ways with <code>oneway=yes</code> and find
* 561 traffic_signals in one-way streets tagged as "traffic_signals:direction"="forward"
* 27 traffic_signals in one-way streets tagged as "traffic_signals:direction"="backward" (which did surprise me due to oneway=**yes**)
* 9 traffic_signals in one-way streets tagged as "traffic_signals:direction"="both"


> Maybe related to #3118?

A traffic sign such as stop or give-way never affects both directions. And such signs AFAIK only appear when approaching an intersection, not in the middle of a road. However, traffic lights _can affect both directions_ and _can occur at any distance from an intersection_.

Maybe some values like <code>traffic_signals=emergency</code> should be excluded.


> E.g. if it is on the intersection point

The quest is _only_ about traffic signals that are _not_ on the crossing point. And traffic signals mapped at the actual location do not always affect traffic heading towards the intersection.

Of course, there will be a majority of `traffic_signals:direction=forward` when considering one-way streets. Traffic signals on non-one-way streets could majority affect traffic towards a nearby intersection, but that's not true in all cases. I have a feeling that a survey of traffic lights direction would bring up more non-default values ​​than the quest whether "small" streets are one-way or not. Vespucci could be used, but I don't think an offline editor without local knowledge would be enough.

**Comment by westnordost** [comment]
Hm I see. Though, it still does not convince me that this is worth the effort to implement and the time of the surveyors. Maybe the direction a small percentage of traffic signals cannot be determined by looking at an aerial picture (or even almost automatically be determined by looking at the geometry), but that IMO does not warrant asking for the other 99% where the outcome is always pretty clear. 
Better would be if there was a proper WYSIWYG visualization in iD and JOSM for traffic signal directions.
