### ISSUE TITLE
Disable by default in Russia the quest Does the traffic light have a tactile indication? (vibrating button)

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4021]
Tactile indication in the form of a vibrating button is not used in Russia. If there is an indication, then this is a maximum of sound and tactile markings.

If you look at the statistics, then 23 pieces is extremely small and looks more like mappers' mistakes.
https://taginfo.geofabrik.de/russia/keys/traffic_signals%3Avibration#values

Therefore, I suggest at least turning off this quest in Russia by default. A small discussion in a local chat found no objections https://t.me/ruosm/648821

**Comment by matkoniecz** [comment]
Note that it is possible to disable quest completely in Russia, it is not possible to disable it by default and keep possible to enable it.

> If you look at the statistics, then 23 pieces is extremely small and looks more like mappers' mistakes.

but that sounds like a good reason to remove it completely. Can you confirm that it would be an improvement?

**Comment by deevroman** [comment]
I think it's possible to disable it. There are no objections to complete deletion in the local chat yet. https://t.me/ruosm/649051
