### ISSUE TITLE
Don't ask for an air compressor when it's already mapped

### ISSUE THREAD

**Issue by paunofu** [streetcomplete/StreetComplete#4022]
I don't know if it's done on purpose or not, but in my opinion it's not necessary to ask if there is an air compressor when it's already map separated in the same area or near.

![Screenshot_2022-05-06-16-09-50-266_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/94412187/167509955-407309df-cd84-4b8b-9a07-42b310c868ab.jpg)

**Comment by 10992-osm** [comment]
Do you have a link to that location in your example image on OpenStreetMap?

**Comment by paunofu** [comment]
https://www.openstreetmap.org/node/9008320647

**Comment by westnordost** [comment]
Well, I am not sure about this.

`compressed_air` is a property of a fuel station, while `amenity=compressed_air` is a map feature. If the latter is mapped separately, tagging the former is as much of a duplication as e.g.
- `toilets=yes` on a mall that is also indoor-mapped in detail including the room(s) with `amenity=toilets`
- `shelter=yes` on a bus stop that has a separately mapped shelter nearby

For the above, it is considered as just fine. It seems to me that allowing the duplication here is only consistent with how it is done for certain other properties of other map features. 

However, if also in this case this is considered fine, then separately mapped compressed air should not be highlighted at all by the quest. @mnalis , this is your quest, what would you say?

**Comment by matkoniecz** [comment]
>  then separately mapped compressed air should not be highlighted at all by the quest

It is still useful as it makes harder to miss an existing one

**Comment by westnordost** [comment]
> It is still useful as it makes harder to miss an existing one

But yields confusion / issues like this one.

**Comment by riQQ** [comment]
What about using `=separate`? It has 45 uses for [`compressed_air=`](https://taginfo.openstreetmap.org/keys/?key=compressed_air#values) and separate is also used as a value for sidewalks and cycle ways.

**Comment by westnordost** [comment]
Uhh, `*=separate` is a really bad idea if it has not been documented to be a valid value right from the start (from the proposal)

**Comment by matkoniecz** [comment]
> What about using =separate? It has 45 uses for [compressed_air=](https://taginfo.openstreetmap.org/keys/?key=compressed_air#values) and separate is also used as a value for sidewalks and cycle ways.

It is not solving any problems and introduces new.

**Comment by mnalis** [comment]
> However, if also in this case this is considered fine, then separately mapped compressed air should not be highlighted at all by the quest. @mnalis , this is your quest, what would you say?

> > It is still useful as it makes harder to miss an existing one
> But yields confusion / issues like this one.

I agree with @matkoniecz here, it is IMHO helpful to show it, as it can be on the side/back of the fuel station and easy to miss. And we want user to manually confirm its existence (or we could automatically tag `compressed_air=yes` when separately micromapped `amenity=compressed_air` is found inside it).

So while I do acknowledge that current situation is not perfect, I still consider it better solution then _hiding_ separately micromapped `amenity=compressed_air`. So if it were up to me, I'd tend to leave it as-is.

---

However, what I have considered when writing the quest was **_excluding fuel station polygons which seem already micromapped_** with separate `amenity=compressed_air` nodes  (see https://github.com/streetcomplete/StreetComplete/pull/3934#issuecomment-1085150501), but:
- I could not find docs for that
- existing examples seemed too complicated for me to understand (much less re-implement in different quest!)
- I'm not sure how big of performance hit it would cause (I've seen discussions before of such polygon matching being possible performance issue)

If the performance hit is negligible, and someone knowledgeable enough would be willing to update the quest (or even better, write the docs demonstrating how to use it in simple case); that would IMHO be quite reasonable thing to do, as it would reduce confusion shown in this issue, without causing any new major disadvantages (there are always minor issues; e.g. while some data consumers might only parse one of the tags, that is minor issue that should ideally be fixed at their side).

**Comment by westnordost** [comment]
Alright

**Comment by riQQ** [comment]
> Uhh, `*=separate` is a really bad idea if it has not been documented to be a valid value right from the start (from the proposal)

There never was a proposal for this. So would documenting it in the wiki be enough?

> It is not solving any problems and introduces new.

It would solve the confusion, as there would be another answer `separate` that clearly applies to the situation. Which problems does it introduce?

**Comment by matkoniecz** [comment]
I would be happy to discuss it on tagging mailing list but

> It would solve the confusion

is not true at all, it would increase confusion. For start  it would redefine existing boolean `yes`/`no` tag. Large part of `=yes` is also mapped separately, There is no realistic chance that all `=yes` with separately mapped objects would be tagged as `=separate` and there would be no benefit from that.

>  So would documenting it in the wiki be enough?

No, as it is barely used and would redefine widely used tag.
