### ISSUE TITLE
Can't pick a quest that is next to another quest

### ISSUE THREAD

**Issue by angelovdev** [streetcomplete/StreetComplete#4026]
Having 2 quests of the same type on the map makes one of them unable to complete before completing the other one even though the objects are unrelated. See the screenshot below where I know the working hours of the small dot but I can't input them unless I input the working hours of the big quest.

![bug](https://user-images.githubusercontent.com/71898342/168338359-6be1d7b6-e1dc-4e85-9f99-d526dd88739d.jpg)

**How to Reproduce**
Zoom onto 2 close by quests of the same type.

**Versions affected**
Android 12
StreetComplete 43.0

**Comment by matkoniecz** [comment]
note that you can hide unsolvable quests, sometimes rotating screen allows you to see hidden ones

in general it is limitation of a current framework and is not really something that can be changed, AFAIK

**Comment by legofahrrad** [comment]
@angelovdev What would be your suggestion to solve this "bug"? Maybe it would be helpful to be able to zoom in further… Or do you want the quest icons to overlap each other? I don't think this would look nice.

As already mentioned by @matkoniecz hiding quests is the solution for now.

**Comment by westnordost** [comment]
Not fixable. Tangram-es (the map renderer) does not allow to zoom in further.
