### ISSUE TITLE
No quests are appearing

### ISSUE THREAD

**Issue by yaomtc** [streetcomplete/StreetComplete#4029]
I haven't used StreetComplete in awhile. Today I opened it and found no quests would load. The map loads. I've tried deleting cache, both from App Info and from within the StreetComplete settings. When StreetComplete is in the background there is a persistent "Syncing data..." notification, never ending until I Force Stop the app.

I see other people are posting logs. How do I access these?

**Versions affected**
43.0 (F-Droid) on Android 12

**Comment by matkoniecz** [comment]
It is a known major bug getting resolved right now.

**Comment by westnordost** [comment]
Same issue as #4028

**Comment by yaomtc** [comment]
Oops, I saw that issue in the list, but didn't click on it because I wasn't getting a crash. Turns out I misread the title. Thank you!
