### ISSUE TITLE
View existing POI, Create new POI and Delete non existing ones.

### ISSUE THREAD

**Issue by Blastd** [streetcomplete/StreetComplete#4031]
**Use case**
Pretty much the same feature we have in OSMAnd.
Creating Points of interest
Editing or deleting existing ones, so that we can easily edit the ever updating roads of our cities whith every shop that opens or closes.

**Proposed Solution**
[Creating a POI]
The context menu that appears when Long Pressing onto the map would show "Create new POI"

A menu, in the same style as the Quest's form would show in the lower half of the screen (scroll up to vertically expand it, scroll down or back button to discard input). It would contain:
- Name of the place
- Amenity
- Opening Hours
- Description
- (Don't know if it's feasible) Upload a picture (with capped mb or pixel size)
(In case it's possible, I would blacklist the usage of Facebook's mapillary)
- Custom Tags + autocomplete and an explanation of the tag used (plus a little hyperlink to a list of all the usable tags)

Also this could replace the Multi-quest creation that is currently in use, which can be triggered only if you state that a POI doesn't exist anymore.

[Viewing existing POI]
Adding a button to hide or view layers:
- Quests
- Underground quests
- Inside public buildings quests
- Non Quest POI

[Editing existing POI]
LongPressing a POI will select it. A menu appears in a quest's fashion with two buttons: Edit | Delete | Replace

●Edit will show the same UI as the Creation of POI, but with the fields already filled. A submit button and a cancel button

●Delete/Replace will ask for confirmation before proceeding to the elimination.
○Replacing will just use the Delete Method and the CreatePOI ui

Hopefully this is all the info that I had to give. It would be awesome to just use this flawless app

**Comment by legofahrrad** [comment]
Out of scope, this is basically remaking OsmAnd/Vespucci/etc.

**Comment by westnordost** [comment]
Mh yes, see @legofahrrad ... however, some basic form of this is maybe going to be added soon. (But if not, it's out of scope ;-)
