### ISSUE TITLE
Remove space before ellipses in English.

### ISSUE THREAD

**Issue by ZeLonewolf** [streetcomplete/StreetComplete#4032]
There should not be a space before ellipses in English. This seems to occur in several places in the strings.xml file.

_Originally posted by @1ec5 in https://github.com/streetcomplete/StreetComplete/pull/4030#discussion_r873253005_

**Comment by matkoniecz** [comment]
ellipsis is … or ...

**Comment by ZeLonewolf** [comment]
Specifically in cases like:
`a,b,c...`
versus
`a,b,c ...`

The former is correct, the latter has a space that doesn't belong.

**Comment by Cj-Malone** [comment]
> ellipsis is … or ...

both, the first should probably be used, but some people prefer the latter due to it being ASCII. Same with ' or ’

**Comment by FloEdelmann** [comment]
In the current English strings, all ellipses are `…` (not `...`) and all apostrophes are `’` (not `'`) already.

See also #1078 and https://github.com/streetcomplete/StreetComplete/commit/2510690d9f6cb7d15c7aca8e0a80cfaafc2e9d70.

I also commented on the proposed changes in #4030 to avoid introducing inconsistencies.

**Comment by westnordost** [comment]
was just one occurance.

**Comment by ZeLonewolf** [comment]
There's three occurrences in this block alone:

https://github.com/streetcomplete/StreetComplete/blob/24acd73465c21629a0f12e8e7d2f1991806e6841/app/src/main/res/values/strings.xml#L749-L757
