### ISSUE TITLE
Since yesterday cannot login anymore

### ISSUE THREAD

**Issue by tonsnoei** [streetcomplete/StreetComplete#4035]
Cannot login with the Android app. 

**How to Reproduce**
Install fresh android app
Press login button in the profile screen. 
A error toast is shown "authorization server not found" 

**Versions affected**
Latest

**Comment by 10992-osm** [comment]
Just to confirm, by latest you mean v43.2 (not v43.1)?

**Comment by timothywashere** [comment]
Version 43.2 is now available on Google Play, yay

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1126990804

If you have 43.2 and it still fails: please comment
