### ISSUE TITLE
Unable to reach the authorization server

### ISSUE THREAD

**Issue by spaghettiriot** [streetcomplete/StreetComplete#4036]
Quests stopped loading (magnifier icon remained with loading animation for 2 days), reinstalled app from F-Droid, tried to login and the dialogue "Unable to reach the authorization server" comes up every time.

**How to Reproduce**
Install StreetComplete
Follow prompts
Click star icon
Click LOGIN button
*dialogue appears*

**Versions affected**
Android 12
Samsung Galaxy S20 FE 5G
F-Droid 1.15
StreetComplete 43.0

**Comment by matkoniecz** [comment]
upgrade

https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1126990804

https://github.com/streetcomplete/StreetComplete/releases and Google store has new version without problem, F-droid has own private build process that may be still going on

**Comment by mnalis** [comment]
Luckily, there is now a fix https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1128462713 so it works again without waiting for new f-droid release (which can lag for a week or two)
