### ISSUE TITLE
Continuous attempt to establish a server connection

### ISSUE THREAD

**Issue by Wetterauer** [streetcomplete/StreetComplete#4037]
I noticed one thing today that I hadn't given any importance to before. On my app, the question mark (bottom) and the star (top) were spinning. Since I have hardly used SC in the last few days, I did not care. Then today I noticed that SC is constantly active on the network. Even when it is "shut down". Switching to WLAN did not change anything either. Only a deactivation brought success.
After a restart the whole thing started again. Only after I opened my profile and the settings did the app come to rest.

Translated with www.DeepL.com/Translator (free version)

**How to Reproduce**
not possible

**Versions affected**
Android 11; SC 43.0

**Comment by FloEdelmann** [comment]
Please see https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1126990804:

To fix this, please update to v43.2. If you're waiting for that version to be published in F-Droid, you can log out in the meantime, and log in after the update.

**Comment by matkoniecz** [comment]
Also, you can try restarting app/phone, per https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1128462713 it should also work
