### ISSUE TITLE
Further Parking Clarification Wording

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#4043]
Off the back of #4030 and in particular https://github.com/streetcomplete/StreetComplete/pull/4030#discussion_r873800941 .

@westnordost provided this excellent table:
Here is a little table I compiled right now from mapillary. Tap on each picture to get to the Mapillary track:

<table>
<tr>
<td>street_parking_on_kerb</td>
<td><a href="https://www.mapillary.com/app/?lat=53.589913099972&lng=9.9638282&z=17&pKey=2595847270723481&focus=photo&x=0.4907449129583573&y=0.5983507653427173&zoom=0"><img src="https://user-images.githubusercontent.com/4661658/168695379-6022aea1-98ef-4700-acba-f09f422382bd.png"/></a></td>
</tr>
<tr>
<td>street_parking_half_on_kerb</td>
<td><a href="https://www.mapillary.com/app/?lat=53.583887699972&lng=9.9440541&z=17&pKey=242779424309198&x=0.5107993077680335&y=0.5395690956835644&zoom=0&focus=photo"><img src="https://user-images.githubusercontent.com/4661658/168695006-3fd5c84e-4109-4d2a-8b1b-c790cb330f82.png"/></a></td>
</tr>
<tr>
<td>street_parking_on_street</td>
<td><a href="https://www.mapillary.com/app/?lat=53.586831388889&lng=9.9672280555556&z=17&pKey=338882334530473&focus=photo&x=0.5226299240228333&y=0.5016344371372468&zoom=0"><img src="https://user-images.githubusercontent.com/4661658/168695593-0fc1e2bf-89a1-43a8-9231-d7aeca5f78c8.png"/></a></td>
</tr>
<tr>
<td>street_parking_street_side<br><br>Same as street_parking_on_kerb<br>but only in dedicated spaces</td>
<td><a href="https://www.mapillary.com/app/?lat=53.576848099972&lng=9.9486697999722&z=19.672156152973546&pKey=291103746010338&focus=photo&x=0.5319529196160544&y=0.49578212198413985&zoom=0"><img src="https://user-images.githubusercontent.com/4661658/168695860-0959b264-181a-4ea5-99a5-1975dfd5d5c4.png"/></a></td>
</tr>
<tr>
<td>street_parking_painted_area_only<br><br>Same as street_parking_on_street<br>but only in dedicated spaces</td>
<td><a href="https://www.mapillary.com/app/?lat=53.6015992&lng=9.9260812&z=17&pKey=171822434847703&focus=photo&x=0.5325532263279752&y=0.4908342469998088&zoom=0"><img src="https://user-images.githubusercontent.com/4661658/168696359-98dd7cfe-deca-4b41-86ff-2b7d36f40d73.png"/></a></td>
</tr>
</table>

_Originally posted by @westnordost in https://github.com/streetcomplete/StreetComplete/pull/4030#discussion_r874225953_

FWIW I'm not sure I'd spot the subtlety of option 3 with the current BE version either.

What about when you have lay-bys for parking in, they're not in the main flow of traffic, so I'd call them off-street, but they're at the same level of road surface (so you'd call them on-street). Is the vertical or horizontal offset more important/critical?

_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/pull/4030#discussion_r874226117_

So given an example like:
<img src="https://www.teesdalemercury.co.uk/assets/images/articles/medium/5671.jpg"/>

Is it off street, as it's not in the main traffic flow, or on-street because it's part of the main road surface?

The current (American) choices are:
https://github.com/streetcomplete/StreetComplete/blob/7849ab4d026dfd5e6a4dd8a8f7134916f72eec95/app/src/main/res/values/strings.xml#L1395-L1402

I think this hits all of:
- Parallel
- On street
- Adjacent to street
- Adjacent to street only in dedicated spaces
- On street only in dedicated spaces

Or I guess more honestly I'm unclear which to prioritise, so don't really feel I can improve the British English wording (or indeed the American/general) one.

**Comment by westnordost** [comment]
The wiki does not clearly define it and when mapping this in reality, it is a matter of consideration whether one would say it is still on the street or not. 

The curb extension shown in the picture above might be just a choker after all and if there is just a choker at one point on the road  for example, I do not consider the parking cars in that street to be parking in  a lay-by.

For the British English, use "carriageway" or "roadway" (German: "Fahrbahn"). Apparently, there is no proper word for "the part of the road on which vehicles drive" (see [cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/roadway)) in en-US, this is why @ZeLonewolf chose "street".

**Comment by westnordost** [comment]
So anyway, you should use "carriageway" in the British English translation and for the other uncertainty, i.e. when exactly it would be on street and when exactly it would be lay-bys, it pretty much remains a matter of consideration.
