### ISSUE TITLE
Check if country allowes quests

### ISSUE THREAD

**Issue by whatevergit** [streetcomplete/StreetComplete#4045]
Hello!

I am in Italy at the moment and it seems like quests are deaktivated for the whole country.
The App doesn't check if quests are deaktivated, the search-ring is just running in endles cirlcles:
(See picture)
![Screenshot_20220519_074436_de westnordost streetcomplete](https://user-images.githubusercontent.com/102467674/169220799-e52fbfb1-901a-49ef-b41b-77616bbddd7a.jpg)

If a fellow mapper didn't hint to me what the problem is, i wouldn't have known it.

If it is possible, I would suggest that the App checks the lokal rules and wether quests are allowed or not. An error message explaining why the user doesn't get any quests would be very helpful.

**How to Reproduce**
Eather travel to Italy, or change your phone-settings to match an italian position (e.g. i am currently in Napoli).

**Versions affected**
I am using Version V43.1

Thank you!

**Comment by matkoniecz** [comment]
Is it still happening? It sounds like https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1126990804 which was resolved by https://github.com/streetcomplete/StreetComplete/issues/4028#issuecomment-1128462713 or upgrading

**Comment by whatevergit** [comment]
Thank you for the clue! After deinstall and reinstall the App now shows quests here in Napoli. 
Apperently just clicking 'update' in the f-droid store wasn't enough.
It is solved now for me.

**Comment by matkoniecz** [comment]
And to be clear

> I am in Italy at the moment and it seems like quests are deaktivated for the whole country.
> The App doesn't check if quests are deaktivated, the search-ring is just running in endles cirlcles:

is not the real problem at all and unrelated to what is actually happening.
