### ISSUE TITLE
Does this shop repair bicycles?

### ISSUE THREAD

**Issue by brierjon** [streetcomplete/StreetComplete#4046]
### General
Affected tag(s) to be modified/added: [service:bicycle:repair](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:repair)
Question asked: **Does this shop repair bicycles?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
 - Enables finding service and rendering the location on bike maps ie [Cyclosm](https://github.com/cyclosm/cyclosm-cartocss-style/blob/e6f051f639ab1198c1a14e941cc0dd8a05d14d3b/views.sql#L200-L202) and [Cyclofix](https://mapcomplete.osm.be)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
 - May need to enter depending on signage outside the store. Not all bike shops have websites nor clearly advertise their repair outside the shop.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Select for response if any of these condition are met.

- shop=outdoor - often do more than repair bikes so it may not be obvious and unless tagged, does not render as a bike resource.
- service:bicycle:second_hand=yes - if they sell second hand they probably repair, but it may be just for their bikes 
- shop=bicycle - may repair bikes, but confirmation is important to ensure this is correctly tagged shop type with available resources
- service:bicycle:retail = yes - if they sell they may repair, but it is useful to determine which places do not. Retail stores that sell, but don't repair are a useful distinction in how to return search results.
- service:bicycle:rental = yes - if they rent they may also repair and in a pinch it would be helpful to know where you can go for a quick repair.

This probably should be verified infrequently. Maybe 5+ years?

**Metadata needed:** 

**Proposed UI:**
A generic person with a wrench standing next to a bike on a bike stand.

**Comment by westnordost** [comment]
Already implemented (not released yet), see #4038

**Comment by FloEdelmann** [comment]
But maybe the element filter from #4038 can be tweaked a bit to include not only `shop=bicycle` like suggested here?

@matkoniecz What do yo think?

**Comment by matkoniecz** [comment]
It would be very spammy, "no" would be an overwhelming answer

Claim based on http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCJzaG9wIiE9ImJpY3ljbGUiIGFuxJfFi8SSdsWVZTrFlMWWxZjFpMS_Y2_Fnl_EiMWeIj0qIMSPbG9ixLzFiMKdCiovCltvdXQ6anPFrF1bdGltZcaBxoMyNTAwXTsKLy_Ej8SUxJ1yIHJlc3VsdHMKKArFtMaXIHF1xJLEmsSjcnQgZm9yOiDFiMKcxYzFjsWRxabFl8WZxZzFniDFoHLFomPFpMa9xag6xarFrGTFrsWdZMWxKsW6xqcgbm9kZVvFi8WNxY_FkcWTxZXGvsWaxojHg8eFx4fHoMeJx4vFrcWvx5DGlMeUd2F5x5rGusedxZLHiMWZIsejxL_HhMWjxaXHp8WZx4plxavHqsePx7jGlcW0xp5sxJRpxazHssecxZDHtce-x6LHssWhx7zHtsWpyIHHjMeOxbDHrcW0x5bHmMiNxY7Ij8efxafHt8e5yJTHhse9yKTFpMaedGFpbMiFx67HsMigx7TIo8ehx7jIk8e7yKjIljrIrMiuyLDInMadZciJxorIjMebyKHHnsiWyLjHpMiVyJHIvWXIrcivyLEpxpXGqXDEt27GscaexqDGosakxo7EmMeXecaVPsaVyZ9za8mDxqp0Ow&c=EL6egBlROA and http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCJzaG9wIiE9ImJpY3ljbGUiIGFuxJfFi8SSdsWVZTrFlMWWxZjFpMS_Y2_Fnl_EiMWeIj0qIMSPbG9ixLzFiMKdCiovCltvdXQ6anPFrF1bdGltZcaBxoMyNTAwXTsKLy_Ej8SUxJ1yIHJlc3VsdHMKKArFtMaXIHF1xJLEmsSjcnQgZm9yOiDFiMKcxYzFjsWRxabFl8WZxZzFniDFoHLFomPFpMa9xag6xarFrGTFrsWdZMWxKsW6xqcgbm9kZVvFi8WNxY_FksaOZG_GtCLGiMeDx4XHh8WVxr7FqWXFq8Wtxa_HkMaUx5R3YXnHmsa6x50ix5_HoXLHo8e1xaHFo8Wlx6jHiceLx63Hj8ejxpXFtMaebMSUacWsx7XHnMWxx7jGgsegx6LHpMS_x4THv8eIxZnHiserx4zHjsWwx7DFtMeWx5jIjsWOyJDHuciUx73Il8eGyIDFp8iaxp50YWlsyIbHscezyKTHt8inx7vIlce-yKvImcWkyK_IscizyKDGnWXIisaKyI3Hm8ilx57Ikse6x7zHpciYyIHIrmXIsMiyyLQpxpXGqXDEt27GscaexqDGosakxo7EmMeXecaVPsaVyaJza8mFxqp0Ow&c=BTKaCKDW6C

For example just 22 `shop=outdoor` are tagged with this tags.

**Comment by brierjon** [comment]
Thanks, I missed 4038, but the structure doesn't address the cases where the tag is missing.

@matkoniecz even with "no" being large proportion of answers this doesn't constitute useless or spammy data as it removes the need to infer and allows for strong metadata statements of presence and absence. Moreso the logic spammyness being based on 22 items using the bicycle:service:repair based on current usage is a flawed approach for assessing if a tag should be checked.

Relying on what the current state of the data alone is confirmation bias and the 22 using the tag is an evaluation of the artifact of practice and structure. The number only highlights there is a low number to currently tagged, but doesn't refute shop=outdoor not being an applicable tag to check.

Actually showing only 22 highlights why shop=outdoor should be evaluated in the repair quest given that many [REI brand stores](https://nsi.guide/index.html?t=brands&k=shop&v=outdoor&tt=rei) have bike repair as a service and is largely classified as shop=outdoor and [offers bicycle repair](https://www.rei.com/stores/bike-shop#locations) which as of September 2020 there were 165 locations in the USA. There are likely many other cases in which shop=outdoor may also have repair services. 

In Ohio, USA there is a good bike shop list, how well does that compare to POI on the map? These could either be shop=bicycle or shop=outdoor https://ohio.bike/ohios-bicycle-shops-listed/ has 168 bike shops in Ohio, and the one local to me is shop=outdoor (which I edited to add the bicycle:service:repair) recently which is 1 of the 22 mentioned above.

One reason why shop=outdoor may not yet have bicycle:service:repair, no editing suggests the key on related shops. For instance ID doesn't expose any bicycle:service:* prompts to users to add to shop=bicycle nor shop=outdoor so unless a user knows the cycling maps need this tag to render or they are working on queries relying on the tag, or started to look into the reasons why their local shop wasn't appearing. Building quests that are robustly checking in StreetComplete help to ground truth where tags are missing and yes, many questions may result in no, but "no" values are just as valuable as yes since they give a strong signal of presence/absence where inferences can be weak signals based on type, but the data is stronger with current and verified presence. 

The proposed 5 conditions should all separately trigger the  bicycle:service:repair quest independently to tag yes or no. StreetComplete provides systematic means of a census of existing points with those tags and help maintain over time by re-prompting. The current definition of spammy is subjective to what is "boring" for users from a developer standpoint instead of affording users the agency to determine what is boring for themselves. We should look for a more subjective term in how frequently one may encounter in terms of geographic area. For bike repair and shop=outdoor or shop=bicycle they are not geographically concentrated for users while walking around. Task design is important, but negative verification is a very useful task if a users wants to query and have reliable results. 

For me (OSM / StreetComplete user wolfgang8741) working to reach completeness is sufficient motivation no matter the number of repetitive tasks and the quest design may need to revise to provide clearer guidance of what is spam versus what do the current developers think is not fun as that may shift depending on who is developing tasks, but work against the goals of the community to have robust tagging rather than inferences.

**Comment by brierjon** [comment]
Another example where limiting the quest to shop=bicycle misses valid quests for repair services for bikes - [Dicks Sporting Goods](https://nsi.guide/index.html?t=brands&k=shop&v=sports&tt=dick) - with [bike repair services](https://www.dickssportinggoods.com/s/bike-services) and this is shop=sports

**Comment by matkoniecz** [comment]
> Moreso the logic spammyness being based on 22 items using the bicycle:service:repair based on current usage is a flawed approach for assessing if a tag should be checked.

22 items raise different issue: StreetComplete introducing completely new tagging use should be not done without discussion with wider community/checking/etc

If it is used just 22 times worldwide in such combination it means that it is quite unusual tagging and I would recommend to start from manually adding this tag. Or discussing with wider community whether adding this tag to every single `shop=outdoor` is a good idea. I am pretty sure that is dubious idea and would have no support in general OSM community.

> The current definition of spammy is subjective to what is "boring" for users from a developer standpoint instead of affording users the agency to determine what is boring for themselves.

Yes, SC is trying to not include questions which would be very spammy. And ones expected to be spammy are not eligible to be included.

**Comment by mnalis** [comment]
@brierjon I would think that for such spammy quests, other mobile editor (with bigger freedom of action) would be better match than StreetComplete. 

In particular, [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) with [Tag filters](https://vespucci.io/help/en/Tag%20filter/) is likely what would fit best (although [OsmAnd](https://wiki.openstreetmap.org/wiki/Osmand) with `POI overlay` might be simpler alternative; and additionally you can use `Map markers` there to avoid visiting already checked locations)

**Comment by 1ec5** [comment]
> If it is used just 22 times worldwide in such combination it means that it is quite unusual tagging and I would recommend to start from manually adding this tag. Or discussing with wider community whether adding this tag to every single `shop=outdoor` is a good idea. I am pretty sure that is dubious idea and would have no support in general OSM community.

Maybe this is a regional thing? StreetComplete is capable of enabling quests in certain countries where they make the most sense. A combination of `shop=outdoor` with either `bicycle:service:retail` or `bicycle:service:repair` wouldn’t likely generate any controversy in the U.S. REI is a good example of a large outdoor chain that happens to have a department that repairs bikes, but L.L Bean is another large outdoor chain that does not. Smaller chains and independent stores would vary. This is a consequence of `shop=outdoor` representing both outdoor recreational _equipment_ retailers (which would repair bikes) and outdoor recreational _clothing_ retailers (which would not).
