### ISSUE TITLE
Ask for more detailed surface type when generic "ground" is used

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#4054]
When walking a lot of long footpaths that have been mapped from aerial imagery the surface type is often "ground". I would like to be able to select a more detailed surface type on the individual sections. 
If no surface type has been set I can split the way up and used detailed surfaces types like dirt, grass, compacted.
I'm not going to do this using notes everytime the ground type changes, it would be very slow, at the moment I just leave them.
It also makes it harder to create steps when needed if they also have set lit=no there is no opportunity for me to do this.

**Comment by westnordost** [comment]
Nah, this is deliberate. It is true that `surface=earth` etc. can be categorized to be a subtype of `ground`, but in real-world, when a surface is natural (a trail), truth is that it is usually a mixture of roots, stones, some grass, moss, dirt, sand and whatever. It simply is not prudent to go into more detail there, especially because depending on the season, it may be sometimes grass, sometimes less grass but more earth.

**Comment by 10992-osm** [comment]
> Nah, this is deliberate. It is true that `surface=earth` etc. can be categorized to be a subtype of `ground`, but in real-world, when a surface is natural (a trail), truth is that it is usually a mixture of roots, stones, some grass, moss, dirt, sand and whatever. It simply is not prudent to go into more detail there, especially because depending on the season, it may be sometimes grass, sometimes less grass but more earth etc.

What you've said makes me think I should perhaps be tagging things as `ground` more than I do, I generally just go with `dirt` when perhaps a more generic `ground` would cover the minor variations that I normally ignore.

**Comment by timothywashere** [comment]
I'm talking about footpaths that are long, not mapping every 10m. They cross fields, where they should be marked as grass. They sometimes run through woods where they would be dirt. Sometimes they have been compacted and are suitable for bicycles or even wheelchairs.
I don't understand why you don't think it's worthwhile capturing this information.

**Comment by timothywashere** [comment]
Can't you tell whether the way has ever been surveyed by SC?
