### ISSUE TITLE
Quest "AddBicyclePump" very unclear on shop=bicycle

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4056]
I have not read the PR #3934 in detail before, but now I got these quests on my phone.

> Is there a working bicycle pump available for everyone here?  [Yes]/[No]

I really have no idea what to answer at a local bike shop with normal paid repair service. (To be uninfluenced I have not read the wiki page till now)

My blocking questions are:
* when? Is it OK to be accessible only when the shop is open? Or must it be 24/7 usable?
* where? Must this be outside? It is ok to go inside to ask for it?

**Comment by westnordost** [comment]
I had these issues with this quest as well. I was at a bicycle repair & 2nd hand bicycle shop that was closed, but saw from the outside that a bicycle pump was standing beside the counter.

**Comment by westnordost** [comment]
I'd say, obviously any bicycle shop **has** a pump and **may** just lend it to cyclists in need when they ask. Therefore, `service:bicycle:pump` should be `no` if there is not one obviously dedicated for it. 

- Does it need to be 24/7 usable? No, I don't think so, within opening hours is reasonable. Hence, it is only surveyable during opening hours
- Does it need to be outside? Not necessarily, but if it is not, it must be obvious through other means that it is completely fine to use it without asking first. How can it be obvious? I think if it is really inside, then this requires some signage in that regard ("free pump inside!")

**Comment by westnordost** [comment]
My suggestion is to use two texts:

For `amenity=bicycle_repair_station`: _Is there a working bicycle pump here?_

For `shop=bicycle`: _Is there a public bicycle pump here (at least when it's open)?_

**Comment by westnordost** [comment]
ping @mnalis

**Comment by mnalis** [comment]
> I'd say, obviously any bicycle shop **has** a pump and **may** just lend it to cyclists in need when they ask. Therefore, `service:bicycle:pump` should be `no` if there is not one obviously dedicated for it / a public one.

Agreed.

>  Does it need to be 24/7 usable? No, I don't think so, within opening hours is reasonable. Hence, it is only surveyable during opening hours

Agreed. Same with air compressor on `amenity=fuel`, they are mostly (at least around here) only available during working hours of the fuel station (the hose is disconnected using off-hours to prevent stealing / vandalism, I guess). So bicycle air pump would also be stowed away during off-hours in vast majority of the cases.

> Does it need to be outside? Not necessarily, but if it is not, it must be obvious through other means that it is completely fine to use it without asking first. How can it be obvious? I think if it is really inside, then this requires some signage in that regard ("free pump inside!")

Also agree. Pump is usually either directly visible outside, or signed.

> My suggestion is to use two texts:
> For `amenity=bicycle_repair_station`: _Is there a working bicycle pump here?_
> For `shop=bicycle`: _Is there a public bicycle pump here (at least when it's open)?_

Looks fine to me.
