### ISSUE TITLE
Provide extra info allowing to identify specific object such as bicycle parking

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4058]
**Use case**
Sometimes there are multiple bicycle parkings next to each other (wheelbender and proper stands). In such case asking about bicycle parking capacity is impossible to answer.

`getHighlightedElements` is not helping in case when parkings are directly next to each other.

And yes, it is an actual problem and I run into it.

Current label is

> Bicycle Parking

or

> Operator Name (Bicycle Parking)

I propose it to become

> Bicycle Parking - wheelbender

or

> Operator Name (Bicycle Parking - wheelbender)

**Proposed Solution**

Show `bicycle_parking` tag (translated using text from bicycle parking type quest)

Opening an issue as I suspect that @westnordost may veto this due to worry that `getNameAndLocationLabelString` may start growing more complex.

Though I think that it is worth it.

**Comment by westnordost** [comment]
Your use case could be solved by displaying different Icons for different types of bicycle parkings? If yes, which bicycle parkings would need to be distinguished?

On May 24, 2022 1:52:20 PM GMT+02:00, Mateusz Konieczny ***@***.***> wrote:
>**Use case**
>Sometimes there are multiple bicycle parkings next to each other (wheelbender and proper stands). In such case asking about bicycle parking capacity is impossible to answer.
>
>`getHighlightedElements` is not helping in case when parkings are directly next to each other.
>
>And yes, it is an actual problem and I run into it.
>
>**Proposed Solution**
>
>Show `bicycle_parking` tag (translated using iD presets)
>
>Opening an issue as I suspect that @westnordost may veto this due to worry that `getNameAndLocationLabelString` may start growing more complex.
>
>Though I think that it is worth it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4058
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by FloEdelmann** [comment]
Why not modify the title of these quests to include the translated iD preset?

E.g. `How many bicycles can be parked here?` → `How many bicycles can be parked here (%s)?`

**Comment by westnordost** [comment]
> Why not modify the title of these quests to include the translated iD preset?
> 
> E.g. How many bicycles can be parked here? → How many bicycles can be parked here (%s)?

Is it 2021 again? The translated iD preset name is already displayed below the question! Don't you remember, we change this?

**Comment by FloEdelmann** [comment]
The `%s` should then of course be filled with "wheelbender" or "stands", which is not yet part of the iD preset name.

**Comment by westnordost** [comment]
Nah, don't want to have (temporary) workarounds like that.
