### ISSUE TITLE
Displayed separately on map arrows should always point outwards

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4062]
When answering a sidewalk quest, the arrows that indicate that it is mapped separately don't always point to the appropriate side of the road.

**How to Reproduce**
Answer a sidewalk quest with the mapped separately answer:

![Screenshot_20220525-125441](https://user-images.githubusercontent.com/12725310/170473315-2f9dacc7-25d4-4af0-a6fa-d015edf73ff1.jpg)

I believe the arrows always point to the right no matter the orientation of the road. They should always point to the particular side of the road they are referring to regardless of the orientation.

**Comment by westnordost** [comment]
Do you have an idea for a different icon for which it doesn't matter on which side it is displayed? I really do not want to add the complexity here to figure out on which side the icon is displayed. After all, you could just rotate the map by 180° and then the icon on the (former) right side would point in the "wrong" direction.

**Comment by dbdean** [comment]
I don't have an idea. I guess I assumed that because the road graphics rotate with the road (or the text in this case), you could also make the arrow rotate with the road.

**Comment by matkoniecz** [comment]
> Like this with the cycleway quest, where the bicycle graphics always rotate with the road.

Note that in this case just extra work to support countries where people drive on left side took in total several hours.
