### ISSUE TITLE
Missing word in quest in Dutch translation

### ISSUE THREAD

**Issue by meiphoo7-Mae** [streetcomplete/StreetComplete#4069]
In the Dutch translation there's a problem with the quest "Is there an air compressor available here?"
The current Dutch translation is: "Bevindt zich hier een". It should be: "Bevindt zich hier een luchtcompressor?" So the subject  of the question is missing.
Also comparing this with the English wording I would like to suggest to change the Dutch translation to "Is hier een luchtcompressor aanwezig?"

**How to Reproduce**
Switch to the Dutch language and find an air compressor quest.

**Versions affected**
All versions since the quest was introduced are affected. The latest stable release is also affected. Android version is not important for this, I believe.

**Comment by mnalis** [comment]
I've added a FAQ entry now on how you can help by submitting better translation directly:

https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Translation_from_English_to_my_language_is_confusing_or_incorrect

**Comment by FloEdelmann** [comment]
Please also see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app for more instructions.

(@mnalis it might be worth linking to them in the FAQ, too.)

**Comment by meiphoo7-Mae** [comment]
Well, that was not a difficult operation. I've added the translation. We'll see if it will be accepted by the community. At least it is a complete sentence now. Thanks for your support and the directions about how to do this.

**Comment by mnalis** [comment]
> (@mnalis it might be worth linking to them in the FAQ, too.)

Done.
