### ISSUE TITLE
Map style not updated

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4071]
There were a few updates to https://github.com/streetcomplete/streetcomplete-mapstyle over the past year, but the last commit that actually is used in StreetComplete is https://github.com/streetcomplete/streetcomplete-mapstyle/commit/6755a442956dffc3f3120a8058c83c1049f7dddb / https://github.com/streetcomplete/StreetComplete/commit/9778c814d7c23370a40bf254cbaf0733a6c02481 (more than a year old).

Is there a reason for not merging later updates?

**Comment by matkoniecz** [comment]
Probably noone did it - I think that it would be fine to open PR doing this.
