### ISSUE TITLE
Detect cases where StreetComplete made no changes and quest reappears

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4074]
Currently user must spot problem and report it on their own after SC repeatedly asks the same quest.

Maybe app should raise "report bug" window in cases where after solving quest X then quest X is still eligible?

Or maybe it would be a good idea to scan changesets made by SC users? And detect cases where the same quest is solved repeatedly (how to distinguish it from undos being applied?)

Recent case, reported manually: https://www.openstreetmap.org/changeset/121873104

In theory some fuzzing could be run but it is likely not worth it.

**Comment by westnordost** [comment]
Sounds like a lot of effort to me, given that in case such a bug occurs, the only consequence is the creation of unnecessary versions of an element. I mean, we have an `int` for version numbers in OSM.
