### ISSUE TITLE
Consider enable markers for the blind in Greece

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#4085]
I was in Athens last week and happily used SC to complete the map. I noticed that quite a bit was todo even in central Athens. And I have no idea where to look why are some quests are disabled in e.g. Greece (pointers are welcome).

I noticed that at a very few curbs markers for the blind were built into the ground (to guide them / their white cane). However, the quest asking for such ground markers is disabled in Greece, (The vast majority of the curbs I encountered did not have them, though).

If this is the very seldom exception just in Athens and thus this question is of no relevance in practice in most of Greece, then I fully understand and simply close this issue, maybe with a pointer where I could look up those exclusions and their rationales in future cases.

If this was done by mistake or not heavily discussed, consider enabling this quest in Greece as well.

This is SC v44.0

**Comment by matkoniecz** [comment]
> The vast majority of the curbs I encountered did not have them, though

That is why it is disabled - if answer is basically always "no"  then such spammy quest is not enabled.

> maybe with a pointer where I could look up those exclusions and their rationales in future cases.

There was PR/issue discussing what should be enabled/disabled when it was introduced but I was unable to track it down quickly.

> If this is the very seldom exception just in Athens and thus this question is of no relevance in practice in most of Greece

That appeared to be situation when it was initially researched, it seems based on "vast majority of the curbs I encountered did not have them" it has not changed and presumably it is even more rare in rural Greece.

But once it changes: this quest can be easily enabled. You can map tactile paving for example with Vespucci.
