### ISSUE TITLE
Being immediately asked "is this still a cycleway situation here" after solving "cycleway type" quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4086]
**How to Reproduce**
I was in a bus on a long road split into many small segments (https://www.openstreetmap.org/changeset/121548465, https://www.openstreetmap.org/changeset/121524074) with auto-upload disabled, so every so often I was offered standard `Is there a cycleway here? What type?` quest, which I dutifully answered with `cycleway:both=no`. I also solved some other quests at the same time, like `shoulder`, `surface`, `building type`.

However about 3-4 times in that several dozens of kilometers (and about hundred of cycleway quests),  after I solved that `cycleway type` quest I was **_immediately_** presented with  `Is this still the cycleway situation here?` quest. It happened at **random** (and I could not reproduce it at will).

At one of them I did **not** answer the `Is this still the cycleway situation here?` quest, and instead I undid the original cycleway quest. When I then again answered that cycleway quest, the `Is this still the cycleway situation here?` did **not** pop up - so it might indicate that this is likely some kind of race condition in SC, and not related to problematic OSM data.

**Versions affected**
SC v43.2 vanilla f-droid upstream, Android 10 (on Huawei P30 Pro)

**Comment by matkoniecz** [comment]
Which specific road segments triggered this?

**Comment by matkoniecz** [comment]
> At one of them I did not answer the Is this still the cycleway situation here? quest, and instead I undid the original cycleway quest. When I then again answered that cycleway quest, the Is this still the cycleway situation here? did not pop up

that happened because the way was not old anymore (the same goes "is it existing" quest)

**Comment by matkoniecz** [comment]
In https://www.openstreetmap.org/changeset/121548465 none of ways had this quest solved twice

**Comment by mnalis** [comment]
Yeah, I always either canceled the quest or answered that nothing has changed (since it _really_ didn't change). It didn't occur to me at the time to try answering that it had changed... And the bus was moving too fast for me to leave a note at exact segment...

I'll try to do both things next time it happens; hopefully if it will help track it down.

**Comment by matkoniecz** [comment]
OK, I will close it for now. I suspect that it was actually separate geometry Tiny road section? someone mapped the same road section twice? Someone mapped lane as a separate carriageway?

If you spot it - please open a new issue and feel free to edit twice in such case, it will make investigation much easier.
