### ISSUE TITLE
Change deprecated barrier=curb to barrier=kerb

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4087]
According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb), the tag `barrier=curb` is deprecated and `barrier=kerb` should be used instead. The `curb` value is used by the AddBarrierType quests in the latest version of StreetComplete .

https://github.com/streetcomplete/StreetComplete/blob/b857f974d6fd1dde4c462f57fc8ac00e99d27bec/app/src/main/java/de/westnordost/streetcomplete/quests/barrier_type/BarrierType.kt#L18

The `curb` spelling should probably be replaced, as it is, for example, flagged as an unknown value by the JOSM validator.

**Comment by FloEdelmann** [comment]
Thanks for reporting!
