### ISSUE TITLE
Was unable to properly complete the sidewalk and cycleway availability on a split road

### ISSUE THREAD

**Issue by 05storm26** [streetcomplete/StreetComplete#4091]
I was unable to properly even understand how the road questioned in the "Is there a sidewalk here?" and the "Is there a cycleway here?" question looks like. 

https://www.openstreetmap.org/changeset/122163882#map=19/46.25711/20.13811&layers=C

When a road is split into two one way paths better visualize how the road looks. At the end I had to do the editing from the ID editor. 

**How to Reproduce**
Look at roads that split into two one way pieces next to each other and don't have sidewalks mapped near to them. It should be easier to understand from streetcomplete how the road is mapped. (Whether it is a single path or two paths for each direction.) 

Streetcomplete should properly handle adding the cycleway, and sidewalk properties for **both** paths.

**Versions affected**
Samsung one ui 3.1, Android 11, StreetComplete v44.0

**Comment by matkoniecz** [comment]
Which part is confusing? How to mark sidewalks if sidewalks are on each side of double carriageway road, but not between carriageways?

**Comment by 05storm26** [comment]
> How to mark sidewtlks if sidewalks are on each side of double carriageway road, but not between carriageways?

Yes, from the visualization of the road of streetcomplete it is not completely ovious that the road there is not a single osm path but two one way paths, that require you to set that inbetween them there are no sidewalk. 

People using streetcomplete might not notice that there is a road separation there and set the sidewalk=true on just on side of the road by accident, which is incorrect because that would put one of the sidewalk inbetween the two paths.

Also even though the sidewalk and cycleway property was unset on both one way paths streetcomplete only wanted to set this on one side, on one of the path only. It wouldn't show the sidewalk quest on the another.


In this situation IMHO streetcomplete should not only just recognize roads which don't have a parallel sidewalk already mapped and have no sidewalk property on the main road but also it should recognise that the road is split into two one way street and ask about sidewalk for both osm paths in a single quest.

**Comment by matkoniecz** [comment]
> might not notice that there is a road separation there and set the sidewalk=true on just on side of the road by accident

Do you mean that someone would set it only on https://www.openstreetmap.org/way/653620971 and not on https://www.openstreetmap.org/way/173909297 ?

> should recognise that the road is split into two one way paths and ask about sidewalk (and set them in one changeset) for both osm paths in a single quest

that is unlikely to be feasible, maybe skipping such roads would be possible

**Comment by 05storm26** [comment]
> Do you mean that someone would set it only on https://www.openstreetmap.org/way/653620971 and not on https://www.openstreetmap.org/way/173909297 ?

Yes someone could use streetcomplete sidewalk quest and set it on only the first path as sidewalk=yes because he/she didn't realitse that there are actually two paths there.

> that is unlikely to be feasible, maybe skipping such roads would be possible

Well recognising if the road has a parallel sidewalk path mapped is very similar so it doesn't seem impossible. You would just need to look at if the road is oneway and see if there is parallel road very close that is oneway and goes to the other direction, and treat them together in the sidewalk quest and set there sidewalk property together.

**Comment by matkoniecz** [comment]
> Well recognising if the road has a parallel sidewalk path mapped is very similar so it doesn't seem impossible.

"ask about sidewalk for both osm paths in a single quest" part is hard to add, not detection

**Comment by westnordost** [comment]
I think the suggested solution is not feasible. No other solutions come to mind. However, in the next version, there will be a dedicated "sidewalk" overlay in which one has an overview how things are currently mapped and is able to quickly correct it.
