### ISSUE TITLE
In countries where traffic law makes the use of some cyleway/track/zone mandatory add a quest where the user can set the bicycle to use_sidepath on roads which have no cycling infrastructure property on them but there exists a close parallel cycling infrasturcture osm path.

### ISSUE THREAD

**Issue by 05storm26** [streetcomplete/StreetComplete#4093]
In a lot of places the [use_sidepath](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath) option would be very useful on OSM paths where cycling is prohibited by local traffic laws but they are generally not marked as bicycle=no/use_sidepath. This causes some bicycle route planner software that uses OSM maps to plan for them which is annoying. [The introduced solution in OSM](https://wiki.openstreetmap.org/wiki/Proposed_features/use_sidepath) was to set bicycle=use_sidewalk on places where there is no table prohibiting cycling but the local traffic law prohibits cycling there anyway due to the parallel cycleway/path.

In lots of places this tag is not used very much resulting in wrong cycle route plannings.

Similarly how Streetcomplete can recognise roads which have no parallel sidewalk mapped and have no sidewalk property to give the user the sidewalk quest, we could have a "mandatory use cycleway parallel exists" quest that recognises roads that do have parallel paths which have bicycle=yes/designated property or have highway=cycleway but don't themselves have cycleway property (like shared_lane or track) (except maybe the cycleway=no, value) and ask the user if on the main road is cycling prohibited by law due to the parralell cycle infrastructure. If the user says yes StreetComplete could tag that segment of the main road as bicycle=use_sidepath.

**Comment by matkoniecz** [comment]
> but there exists a close parallel cycling infrasturcture osm path

in such case - why survey would be needed? It seems like editable remotely without real benefit by surveying

**Comment by 05storm26** [comment]
> in such case - why survey would be needed? It seems like editable remotely without real benefit by surveying

Hmm okay that's fair.

**Comment by matkoniecz** [comment]
@05storm26 It may be more fitting for Osmose, see https://github.com/osm-fr/osmose-backend

**Comment by BalooUriza** [comment]
I'd be more comfortable with this quest if use_sidepath wasn't both
redundant to, and deprecated by, "no" and mapping the sidepath.

**Comment by matkoniecz** [comment]
> if use_sidepath wasn't both redundant to, and deprecated by, "no" and mapping the sidepath.

Not always. See minimaps in https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath#Examples

> and deprecated by, "no" and mapping the sidepath

That is not correct at all: use_sidepath to be used needs separately mapped cycleway and is not deprecated by "no" anyway
