### ISSUE TITLE
add quest for direction of objects

### ISSUE THREAD

**Issue by TS-R** [streetcomplete/StreetComplete#4098]
**Use case**
For some objects direction information will be usefuel. For example direction of surveillance camera may be interesting to create maps of coverage. Also direction of viewpoints may be relevant information for creating touristic maps or hiking maps. Also direction of benches could be added to create maps showing the direction of view. May be there are ideas for additional objects where direction information will be useful.

**Proposed Solution**
There should be 3 options to answer.
- one single direction (should be the default option to determine the single direction directly)
- a range: for example 30-90 degrees (first determine the start of direction range and in second step determine the end of direction range in counterwise order)
- 360 degree - for example viewpoint with view in all directions

For first and second option the values could be determined with mobilephones compass feature.

- [x] 🚧 To be added tag is established and has a useful purpose:
[over 2m uses](https://taginfo.openstreetmap.org/keys/direction)

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one): yes 

- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary:
It's easy to answer if mobile phones compass feature.

- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam):
yes - every object may have an other direction. There are 360 possible values

- [x] 🕓 Applies to a reasonable number of map data (Worth the effort):
yes - there are big amount of objects that may have a direction, Some examples from my side. May be there are any additional ideas for objects which have a direction an where direction information may be relevant:
- amenity=bench
- tourism=viewpoint
- man_made=surveillance
- man_made=advertising (for billboard, board, poster_box, screen, sign, tarp, wall_painting)

**Comment by matkoniecz** [comment]
[New quest: Add direction to viewpoint](https://github.com/streetcomplete/StreetComplete/issues/776) (#776)

**Comment by westnordost** [comment]
Other than for tourist viewpoints, I don't really see the useful purpose of this. Maybe surveillance cameras, but again, useful purpose?

For the former, see the linked issue, for the latter, there were some long tickets regarding surveillance cameras already.

**Comment by letypequividelespoubelles** [comment]
It's usefull for other POI too, such as climbing, freeflyng, and high mountain natural things such as couloir, gully, etc.

**Comment by matkoniecz** [comment]
> climbing, freeflyng

how these are tagged? what direction means here?

> couloir, gully

should be mapped as ways

**Comment by letypequividelespoubelles** [comment]
From the wiki for climbing : "Orientation of the rock/wall face. Helps to asses at what hour of the day it might be sunny and how long it takes a wall to get dry after rain. If the cliffs are also tagged, too, this information may be derived but tagging still gives a quicker overview and limits to the climbable parts of cliffs.". Tagged as climbing:orientation=N for exemple

**Comment by matkoniecz** [comment]
Mapping cliffs is definitely better. It is typical that rock face is not nicely and clearly pointed in one direction and even if that is usable info when reduced to such direction, it is not easily surveyable.

**Comment by letypequividelespoubelles** [comment]
>Mapping cliffs is definitely better.
The best is to map the cliff AND to tag the direction of the climbing site. It's usefull when you search for a given orientation for exemple. Same for couloir.

>it is not easily surveyable
Fair enough. Moreover, for climbing site and freeflying takeoff, it's easily done by armchair mappers, this info is most of the time on publi topo.

**Comment by HolgerJeromin** [comment]
>Maybe surveillance cameras, but again, useful purpose?

IMO, yes: 

![image](https://user-images.githubusercontent.com/2410353/173315734-52975811-d7ba-4ed1-9d37-282dd7ac0e90.png)

https://sunders.uber.space/?lat=52.5170365&lon=13.3888599&zoom=18

**Comment by westnordost** [comment]
Only because you can render it doesn't make it a useful purpose. The whole surveillance tagging is already bordlerline useful.  The only reputable reason i can think of is to show "look at all this surveillance, isn't it distopian?", i.e. raise awareness.

Am 13. Juni 2022 10:48:38 MESZ schrieb Holger Jeromin ***@***.***>:
>>Maybe surveillance cameras, but again, useful purpose?
>
>IMO, yes: 
>
>![image](https://user-images.githubusercontent.com/2410353/173315734-52975811-d7ba-4ed1-9d37-282dd7ac0e90.png)
>
>https://sunders.uber.space/?lat=52.5170365&lon=13.3888599&zoom=18
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4098#issuecomment-1153649104
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by TS-R** [comment]
I think there is already a quest asking for surveillance mounting type. I think camera direction may be more usefuel than the already existing mounting type quest. And if the functionality for compass usage is integrated once it can be used for other objects which may typically have directions (bench, advertising, hunting stand, informtion panels).

By the way, surveillance coverage may also be interesting from security point of view.

> Only because you can render it doesn't make it a useful purpose. The whole surveillance tagging is already bordlerline useful. The only reputable reason i can think of is to show "look at all this surveillance, isn't it distopian?", i.e. raise awareness. Am 13. Juni 2022 10:48:38 MESZ schrieb Holger Jeromin ***@***.***>:
> >Maybe surveillance cameras, but again, useful purpose? IMO, yes: ![image](https://user-images.githubusercontent.com/2410353/173315734-52975811-d7ba-4ed1-9d37-282dd7ac0e90.png) https://sunders.uber.space/?lat=52.5170365&lon=13.3888599&zoom=18 -- Reply to this email directly or view it on GitHub: [#4098 (comment)](https://github.com/streetcomplete/StreetComplete/issues/4098#issuecomment-1153649104) You are receiving this because you commented. Message ID: ***@***.***>
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
> By the way, surveillance coverage may also be interesting from security point of view.

As far as I am informed, surveillance geberally does not prevent crime, only can help investigators after the fact.

**Comment by TS-R** [comment]
> > By the way, surveillance coverage may also be interesting from security point of view.
> 
> As far as I am informed, surveillance geberally does not prevent crime, only can help investigators after the fact.

So it can also be helpful for investigators to check if curtain area is in view of any camera ;-)

Also the direction of viewpoints or hunting stands may be interesting for some map ir data consumers like photographers or natural / animal interested users.

**Comment by westnordost** [comment]
Investigators will certainly not check OSM for that. You can look out from hunting stands usually in all directions. It is rather the shape of the clearing that determines the direction in which you have a wide view.

**Comment by mcliquid** [comment]
`natural=saddle` and `mountain_pass=yes` could be a another possibility.

About usefulness: The OpenTopoMap shows viewpoints only if it has a direction.

Another possible problem for StreetComplete: Especially viewpoints are often tagged with two cardinal directions. The input would be a bit difficult to measure and enter this correctly. So for example `direction=90-120`.

**Comment by matkoniecz** [comment]
for viewpoints I kind of see the point, but that is in https://github.com/streetcomplete/StreetComplete/issues/776 (https://github.com/streetcomplete/StreetComplete/issues/776)

**Comment by bgo-eiu** [comment]
I agree directionality is not equally useful on every feature it can be tagged on.

The most useful and simple thing that comes to mind is "What direction is this stop sign facing?" It only concerns direction as it pertains to the way the node is on so does not require reading a compass or anything.

Directionality is important for traffic signals too but harder to survey on foot.

Guidepost signs often point in a particular direction, but would need a more compass-like selection as they don't have to be attached to a way.

**Comment by mnalis** [comment]
> As far as I am informed, surveillance geberally does not prevent crime, only can help investigators after the fact.

I think it was found (I'm sure _it was found_ by camera sellers, but I think it was also found in more reliable sources) that they are an effective deterrent too. To the point that they sell fake cameras too (with just a blinking LED and casing, so it looks like real camera, but is much cheaper), so the potential thieves do not know which ones are real.

Although, I'm not sure there is much use of them on OSM (besides mentioned dystopian awareness). There is **_so much more information that is missing for such map to be usable_** for security planning (and won't ever be mapped, as it would defeat their very purpose if such reliable information was to become publicly available!):

- which areas have no cameras, and which have them but nobody mapped them?
- which cameras are fake, and which are real?
- not just azimuth angle, but also field of view the objective covers?
- not just azimuth angle, but also altitude/elevation angle, and 3D position of camera itself (x,y,z)
- sensor density (Mpixels) and compression quality ?
- focus range
- light sensitivity, IR lightling, ...

**Comment by westnordost** [comment]
I'll close that then. For viewpoint direction there is already a separate ticket.

**Comment by mnalis** [comment]
> For viewpoint direction there is already a separate ticket.

ref: probably https://github.com/streetcomplete/StreetComplete/issues/2514#issuecomment-812751366 and around
