### ISSUE TITLE
Do not ask if building type is correct when I've just entered it

### ISSUE THREAD

**Issue by joelsgp** [streetcomplete/StreetComplete#4099]
**Use case**
Sometimes when I'm surveying a building I'll enter the building type, e.g. "Office Building", then the quest to enter house number will appear. If the building has no house number, the app will ask me if the building type is correct, despite the fact I just entered it.

**Proposed Solution**
The `building_type` quest should set a flag that the type of a specific building has just been entered. The `address` quest (in `onNoHouseNumber()`) should only call `showNoHousenumberDialog()` if that building hasn't just had the building type quest completed by the same person.

**Comment by joelsgp** [comment]
not that familiar with kotlin, but with furhter looking I think this could be done by just checking the timestampEdited of the osmElement. If it's within the last minute, that probably means the same user was just completing quests on it, so don't ask "Is this correct?" about the building type.
```kotlin
private fun onNoHouseNumber() {
        val buildingValue = osmElement!!.tags["building"]!!
        val buildingType = BuildingType.getByTag("building", buildingValue)
        val timeSinceEdited = currentTimeMillis() - osmElement.timestampEdited  // added line
        if (buildingType != null and timeSinceEdited < 60) {  // edited line
            showNoHousenumberDialog(buildingType)
        } else {
            // fallback in case the type of building is known by Housenumber quest but not by
            // building type quest
            onClickCantSay()
        }
    }
```

**Comment by westnordost** [comment]
> ... if that building hasn't just had the building type quest completed by the same person

This information is not really kept/evaluated by StreetComplete.

Your suggestion would probably work - if you edited it less than 60ms ago, but I do not want to add such custom complexity in the code. FWIW, in my opinion, the warning should rightfully show anyway, even if the user just answered that it is an office building because that dialog contains information what (tagging it as not having a housenumber) it implies.

After all, an office building without a housenumber is quite unlikely. Maybe it is rather a building part of a larger office complex.

**Comment by joelsgp** [comment]
I've been using the app around a university and business park where there are lots of places without house numbers, so this change would make the experience more streamlined for me. You're right though, this is an edge case and in general it's best to keep it how it is and it's too minor to make it a setting

**Comment by westnordost** [comment]
Without house numbers, but maybe with building numbers? Mail carriers need to be able to deliver mail right?

**Comment by joelsgp** [comment]
Each college has a mail room, and the individual buildings have names or block ids like A/B/001. I didn't consider putting in the A/B part for house number, should I do that?

**Comment by westnordost** [comment]
Hm no, probably not. The building name/block id can/should be recorded somehow, but i forgot which would be the most fitting tag... maybe just "name"

**Comment by HolgerJeromin** [comment]
>> Mail carriers need to be able to deliver mail right?

> Each college has a mail room

But pizza delivery are a much more realistic problem :-)

But I know many office buildings on industrial campuses without a housenumber.

**Comment by joelsgp** [comment]
As far as pizza delivery goes - which I'm happily familiar with ; ) we generally just give the college name, and the delivery comes to the street right outside the college reception / mail room where we pick it up
