### ISSUE TITLE
replace steps ramp quest images (#2036) 

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4103]
See https://github.com/streetcomplete/StreetComplete/commit/7d5ab65024a057f23eab9325c73088239097ac6b

It turns out that licensing of this images is unclear and we may be missing necessary attribution/license mention. Simple attempts to track down this images failed, it seems that we may need to find new ones.

BTW, I needed to create some quick verification script, due to NGI0 requirements in my previous grant. I run it again last week and it found this problem (and some minor fixable ones). Maybe it would be a good idea to add it to some build/CI scripts? To catch such issues early? It is at https://github.com/matkoniecz/StreetComplete-license-chore/blob/master/scan.kt (was intended as single use initially, so was not refactored and with things piled upon it till it worked - so would need to be refactored)

**Comment by westnordost** [comment]
I am pretty sure that at least stroller and wheelchair ramp was contributed/linked by someone... but if you didn't find anything, well. Did you try a reverse image search?

**Comment by matkoniecz** [comment]
> Did you try a reverse image search?

Yes, nothing was found

> IIRC none and maybe bicycle ramp I heavily photoshopped, to get rid of leaves and other dirt.

That would likely make harder to find them again :(

**Comment by matkoniecz** [comment]
Current form:

![screen03](https://user-images.githubusercontent.com/899988/174390255-105fbb66-4cde-498b-9a28-5c7b81b2a0f8.png)

The first attempted replacements:

![screen06](https://user-images.githubusercontent.com/899988/174392086-d195478a-64e6-4718-8e19-e42ee45388ca.png)

I will try to take "no ramp" in situation where shadow/sun differentiates steps a bit and take stroller ramp photo from consistent perspective.

**Comment by FloEdelmann** [comment]
My two cents:

* The "stroller ramp" image looks like a very good replacement. Maybe the contrast can be tweaked a little bit, but I think it's fine already.
* The "no ramp" also looks okay, but I don't like the harsh shadow of the handrail. It's still a good replacement though.
* Suggestions for other images (they are all not perfect and you have probably already considered them):
  - for "no ramp": https://commons.wikimedia.org/wiki/File:Steps_at_Scarborough_-_geograph.org.uk_-_1949152.jpg
  - for "bicycle ramp": https://commons.wikimedia.org/wiki/File:Treppe_in_deutschem_Bahnhof_mit_Resten_von_altem_Gep%C3%A4ckband.jpg
  - for "wheelchair ramp": https://commons.wikimedia.org/wiki/File:Escada_e_rampa_em_Morro_de_S%C3%A3o_Paulo.jpg
  - for "wheelchair ramp": https://commons.wikimedia.org/wiki/File:Krop%C3%A1%C4%8Dkova,_schody_vchodu.jpg

**Comment by matkoniecz** [comment]
> for "no ramp": https://commons.wikimedia.org/wiki/File:Steps_at_Scarborough_-_geograph.org.uk_-_1949152.jpg

that is actually nice, but actually "no ramp" is relatively easy to catch

> for "bicycle ramp": https://commons.wikimedia.org/wiki/File:Treppe_in_deutschem_Bahnhof_mit_Resten_von_altem_Gep%C3%A4ckband.jpg

that is actually luggage ramp if anything, maybe we should list to reduce risk of mistagging them as bicycle ramps?

> for "wheelchair ramp": https://commons.wikimedia.org/wiki/File:Escada_e_rampa_em_Morro_de_S%C3%A3o_Paulo.jpg

ouch, that is a death trap - I am trying to include photos of sane infrastructure/situations

I actually got wheelchair ramp from a nearby park :)

> for "wheelchair ramp": https://commons.wikimedia.org/wiki/File:Krop%C3%A1%C4%8Dkova,_schody_vchodu.jpg

for me it seems stroller ramp due to how steep it is

now I see that it would be nice to have all stairs having the same orientation, but I think that I will focus first on a bicycle ramp image (please, if you find any good picture - similar in quality to existing one - please let me know)

**Comment by matkoniecz** [comment]
> The "no ramp" also looks okay, but I don't like the harsh shadow of the handrail. It's still a good replacement though.

@FloEdelmann - fixed, also I caught viable wheelchair ramp at https://www.openstreetmap.org/?mlat=50.07647&mlon=19.91853#map=17/50.07647/19.91853 (stroller is https://www.openstreetmap.org/?mlat=50.07859&mlon=19.92033#map=17/50.07859/19.92033 and no ramp is at https://www.openstreetmap.org/?mlat=50.07939&mlon=19.92141#map=17/50.07939/19.92141 which ironically has a ramp, just not visible in a photo :) ).

![screen06](https://user-images.githubusercontent.com/899988/176366138-1a7f0f93-fff6-4b28-91a4-d7cd9d9af5d4.png)

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/commit/6fd996559cb453ebec2998bef18fe6c14642f858 adds three but bicycle ramp remains unsolved for now (it is on my TODO list but I run out of time for NGI0 milestone which I used to work on this)

Still, if anyone can take any fitting bicycle ramp photo (clearly visible ramp, can be cut into such proportions, preferably bicycle visible for clarity) then you would be highly welcome!
