### ISSUE TITLE
Add `ref` for `power=substation`

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4106]
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref) [power=substation](https://wiki.openstreetmap.org/wiki/Tag:power%3Dsubstation) 
Question asked: **What is the number of this substation?**

Yard substations usually always have a number that you can see on it.

<details>
<summary>Examples</summary>

Wiki example:
`ref=160`
![Service_building](https://user-images.githubusercontent.com/25708359/173343039-c787f030-4abd-485a-863e-cbfdf0eec52d.png)

---

`ref=4939`
![1556547777_5](https://user-images.githubusercontent.com/25708359/173356121-a9116cb1-5a0d-42b2-9c87-ce84a4ca925f.jpg)

---

`ref=329`
![scale_2400](https://user-images.githubusercontent.com/25708359/173357325-2378851f-8583-4004-80cd-4ddce5fd9cfa.jpg)

---

```
ref=7595
phone=5433405
voltage=6000
```

![IMG_20220613_134716_222](https://user-images.githubusercontent.com/25708359/173357591-02a709d8-a9e2-471b-b75a-0c7da258fb8a.jpg)

</details>

<details>
<summary>Estimating the number of objects using Russia as an example</summary>

```
area(id:3600060189)->.b;
(
  way["power"="substation"][building](area.b);
);
out body;
>;
out skel qt;
```

30916 ways

```
area(id:3600060189)->.b;
(
  way["power"="substation"][building][!ref][!name](area.b);
);
out body;
>;
out skel qt;
```
18707 ways

60% of such substations are suitable for the quest

</details>

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
There are renders that show these numbers. https://frexosm.ru/power https://openinframap.org (I've seen a few more global renders, but I can't remember the links yet)
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
While I know what to answer if the plaque is missing or damaged. This can happen with any quest.
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)
Almost all yards have their own unique number
- [X] ⚠️ Safety 
1. It is necessary to ask only `power=substation + building=*` since the transformers are hidden inside the building.
2. A warning should be issued. Something like:
"⚠️ Don't come close! The number must be clearly visible from outside." 
3. Turn off the default quest.

p.s. So we already have a dangerous quest about measuring the width of the road, which is asked for highway=secondary :)

### Ideas for implementation

**Element selection:** 
`power=substation` + `building=*` without `ref` or `name`

Perhaps you can also select `power=substaion` + `man_made=street_cabinet`

There may be some tags to skip (`substaion=?` `location=?` `voltage>=10000`)

**Metadata needed:** 
The number plate scheme should work in Russia, Ukraine, Belarus... and other ex-USSR countries.

**Proposed UI:**

Simple number entry field

**Comment by mcliquid** [comment]
I can at least contribute for Germany and Austria that there is no ref number for transformer houses existing / visible on a sign.

**Comment by legofahrrad** [comment]
I like the idea :)
But there should be an option to tag explicitly that there is no ref number. What about `noref=yes` or even better `ref:signed=no`?

**Comment by westnordost** [comment]
The issue I see (with the examples shown) is that there are many numbers on such a building. It is unclear which one should be entered as a `ref`, to me at least. And I am a layman like any other user of he app. E.g. the last example, the ref could have been `B-1` too no?

**Comment by westnordost** [comment]
Also, it would require a lot of research about in which region(s) such a reference number is usually publicly visible at all. All that sounds a bit too much when compared with the useful purpose this information may serve. (E.g. just so that it can be displayed on a map is a little thin. The question is, why would someone want to look for the ref on a map?)

**Comment by HolgerJeromin** [comment]
We need to be explicit that `ref` does not need to be a number. Here this is often a streetname or streetname+housenumber (which still is a `ref` and not `addr:*`)
https://www.openstreetmap.org/node/4706172075
https://www.openstreetmap.org/node/8935404811

**Comment by legofahrrad** [comment]
Some photos from Bremen, Germany:
The ref number can easily be seen from the outside and thus the question for ref number is easy to answer.

<hr>

![771](https://user-images.githubusercontent.com/92865620/174351181-4d57e143-fa65-4324-b493-065a29c0d87a.jpg)
`building=service`
`power=substation`
`substation=minor_distribution`
`ref=771`
…

<hr>

![662](https://user-images.githubusercontent.com/92865620/174351589-dc434865-810e-43f4-b9c9-517aae9fe261.jpg)
`power=substation`
`substation=minor_distribution`
`ref=662`
…

<hr>

![5102_03](https://user-images.githubusercontent.com/92865620/174351898-da584f51-8d65-426a-9260-260c74a09716.jpg)

`power=substation`
`substation=minor_distribution`
`ref=5102`
…

<hr>

So, all in all the ref numbers are easy to read. Probably this is also a local thing, so it depends on the city how the ref numbers are set and if they are signed at all.

**Comment by peternewman** [comment]
On at least one UK substation, the most obvious "ref" is just the [OS grid reference](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid) (that's grid as in squares, not power grid). So it's just telling you exactly where it is, and at the same time uniquely identifying it. I'd need to check a few others to see if that's universally true.

**Comment by Cj-Malone** [comment]
> On at least one UK substation, the most obvious "ref" is just the [OS grid reference](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid) (that's grid as in squares, not power grid). So it's just telling you exactly where it is, and at the same time uniquely identifying it. I'd need to check a few others to see if that's universally true.

I think it's a company thing. SSE near me have clear [names and refs](https://www.openstreetmap.org/way/149942656), GTC in Scotland seem to also have [names and refs](https://www.openstreetmap.org/node/6653335119). This [one](https://www.openstreetmap.org/way/762114645) should probably be a name, not ref.

I wounder if there would be any point asking for an operator, or if that's just a UK thing.

**Comment by davidpnewton** [comment]
Western Power Distribution also show clear names and references for their substations in the UK.

**Comment by SK53** [comment]
@davidpnewton In the old EM Electricity region older substations will have two refs (usually separated by a slash). I checked with a friend who has worked on the distribution network for 40 years and one is the older East Midlands reference format 99A999 with the second being the 6 digit Western Power one. Examples : [52D0061/880820](https://www.openstreetmap.org/node/3897827481,) , [52D1521/880309](https://www.openstreetmap.org/way/299979515). I of course have numerous examples photographed too.

**Comment by davidpnewton** [comment]
@SK53 now that explains something. Around here they're 42D #### rather than 52D ####. I've seen instances where both that style of reference and the 6 digit one which corresponds to the Western Power Distribution ones found in the open data release they've made are present. I've also found ones where only a 4 digit reference is actually visible on the substation itself. I'd guess that each of those should really be prefixed by 42D but that for whatever reason that wasn't put on the plate on the substation.

The lodge near 52D0061/880820 has always bemused me. Obviously at one point it was right in place and context as the grand entrance to Wollaton Park, but it just looks so utterly anachronistic now being separated from the remains of the grounds by such a distance and indeed the ring road. Haven't been to the area for a while now, but I know Nottingham well.

**Comment by SK53** [comment]
@davidpnewton the 42D & 52D parts are indeed area codes of some form, so I think your surmise is correct. Presumably there's enough documentation only using the old codes to make it useful for maintenance work (my informant said that he's till got GPS co-ordinates of many pole-mounted substations on his Satnav).

Off-topic on the lodge, but read the historical note [here](https://britishlistedbuildings.co.uk/101270829-lenton-lodge-former-gateway-to-wollaton-park-and-attached-bollards-dunkirk-and-lenton-ward). It explains much of the incongruity.

**Comment by mccartney** [comment]
> why would someone want to look for the ref on a map?

OSINT and geo-localization?

**Comment by SK53** [comment]
> > why would someone want to look for the ref on a map?
> 
> OSINT and geo-localization?

fault reporting, ...
but also just "this is OSM & that's what we do"

**Comment by deevroman** [comment]
So, I generalize beforehand.

---

I'll try to explain why the last picture is still not very complicated.

"РТП" is an abbreviation of "Распределительная Трансформаторная Подстанция" (Distribution Transformer Substation) in Russian. For a Russian speaker, "ТП" is an understandable abbreviation. And seeing the number after such a reduction, it is clear that we are talking about the substation number.  Other abbreviations are also understandable for a Russian speaker: the phone number (by prefixes тел..=tel., voltage - 6 kV) "B-1" is a little more complicated, but seeing the РТП, you no longer need to look for other numbers.

But do not think that only abbreviations are used. Sometimes № is explicitly indicated, and sometimes it is not only inscriptions in paint, but also special plates. 

<details>
<summary>example</summary>

![IMG_20220912_232533_952](https://user-images.githubusercontent.com/25708359/189768300-edeb5e41-1a2b-430d-8c7a-9e90cebd67e0.jpg)

</details>

It is clear that there will be difficult situations, but this quest is no more difficult than entering the address of the house.

---

And here I smoothly lead to the application of information about the `ref`

Substation buildings in courtyards usually have the same address as houses + a suffix with a letter + a suffix with a subbuilding number. And it is quite difficult to write this address in osm and use it for someone. Therefore, the bases of electricians rely on the numbers of substations. Moreover, such a ref is more unique than an address, because it is unique within the service operator, which can serve several cities. Basically it's like a quest with fire hydrants, but the hydrants don't even have an address. https://github.com/streetcomplete/StreetComplete/issues/3059

Also, we should select only those countries/operators that use only numeric refs. (They tried to tell me about such an operator in the French matrix chat https://matrix.to/#/!fdQuIPZzzMzrCiZONx:matrix.org/$dzoKGH2g0BX1RU1z-f3CqEu-Po1haAEnLM7gf_OSnrM?via=matrix.org&via=tchncs.de&via=tedomum.net) But it seems there are not many such countries:(

p.s. Do not hesitate to clarify my wording, perhaps I have translated something incorrectly or do not know many regional peculiarities.

**Comment by wvanderp** [comment]
In the Netherlands most substation have a ref on them

See:

![PXL_20220827_150243954.jpg](https://user-images.githubusercontent.com/2423856/192157919-d42e534b-4c80-4e6c-a1e1-3e30097c9cc4.jpg)

![PXL_20220823_155726049.jpg](https://user-images.githubusercontent.com/2423856/192157951-f4099525-9e24-4854-a968-c1c88c8a9cde.jpg)

![PXL_20220717_122304641.jpg](https://user-images.githubusercontent.com/2423856/192157985-2f40d903-93cb-444a-8e58-1a6b0491029d.jpg)

**Comment by matkoniecz** [comment]
Looking at https://commons.wikimedia.org/wiki/Category:Distribution_substations_in_Russia and given

> "РТП" is an abbreviation of "Распределительная Трансформаторная Подстанция" (Distribution Transformer Substation) in Russian. For a Russian speaker, "ТП" is an understandable abbreviation. And seeing the number after such a reduction, it is clear that we are talking about the substation number. Other abbreviations are also understandable for a Russian speaker: the phone number (by prefixes тел..=tel., voltage - 6 kV) "B-1" is a little more complicated, but seeing the РТП, you no longer need to look for other numbers.

it seems believable to me that it is mappable, though there is a real risk that reality turns out differently and quest may need to be removed.

Though I am not fully sure about actual use of this data. But

> Therefore, the bases of electricians rely on the numbers of substations. Moreover, such a ref is more unique than an address, because it is unique within the service operator, which can serve several cities. Basically it's like a quest with fire hydrants, but the hydrants don't even have an address.

is not so outlandish use, I heard about companies maintaining hydrants using OSM data to locate hydrants because official data is incomplete/missing.

Though not fully convinced.

**Comment by mccartney** [comment]
Is it an option to add the quest and make it disabled by default?

**Comment by westnordost** [comment]
I am going to reject this quest suggestion because it would be difficult to ascertain for users whether "some number" / "some letters" on a substation would be the ref, or something else. There could also be several numbers on it, or none.

**Comment by mnalis** [comment]
FYI, this quest (in even more generic form) has since been added to [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (see https://github.com/Helium314/SCEE/issues/531)
