### ISSUE TITLE
Shoulder quest selection buttons are swapped

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4116]
Selecting the "shoulder" and "no shoulder" images in the `AddShoulderForm` picker results in the inverse selection being made.

https://user-images.githubusercontent.com/6892794/173794439-2bf8d305-2304-491a-9ab5-804532408f7d.mp4

**Versions affected**
[v45.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0-alpha1)

**Comment by westnordost** [comment]
Oof. Thank you!

**Comment by HolgerJeromin** [comment]
Should we publish a "hotfix" alpha2 apk to prevent more wrong data in osm?

**Comment by HolgerJeromin** [comment]
cc @westnordost

**Comment by mnalis** [comment]
...and publish it in https://www.westnordost.de/streetcomplete/banned_versions.txt ?

However, I think we should also (after it's banned) do an automated edit to fix `shoulder` quest done with `45.0-alpha1` (maybe best **delete** them, as versions of SC compiled from master would also identify themselves as `45.0-alpha`, but already contain the fix).
