### ISSUE TITLE
Changing sidewalk tags should remove any sidewalk-related tags

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4123]
**How to Reproduce**
When changing the `sidewalk=*` tag with the new **overlay feature,** SC should remove all `sidewalk:[side]:*=*` tags. E.g. when changing a street with `sidewalk=both` and `sidewalk:both:surface=paving_stones` to `sidewalk=right`, the surface-tag is wrong. The tag has to be changed to `sidewalk:right:surface=paving_stones`.

**Proposed Solution**
Different ideas here:
<ol>
  <li>remove them completely as proposed in the issue's title</li>
  <li>change them in the background fitting to the new situation</li>
  <ul>
    <li>SC detects the side-related tags and changes them automatically</li>
  </ul>
</ol>

**Versions affected**
[v45.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0-alpha1)

**Comment by westnordost** [comment]
I think it is better to remove everything if something changed. If it was tagged differently before, either 
- it was a mistake by a previous mapper
- or the street has been re-built
In both cases, I think it is prudent to not assume that the value for the other side is still correct.
