### ISSUE TITLE
sidewalk layer is not showing that road was marked as having separate sidewalk (sidewalk=separate)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4127]
I planned to use it to review for missing and wrong `sidewalk=separate` taggings and currently this seems not possible

https://www.openstreetmap.org/way/940791131#map=19/50.08019/19.91969

![screen01](https://user-images.githubusercontent.com/899988/174297795-95916fdc-9091-43bb-b5dd-ad8e8a2c6d69.png)

**Comment by meiphoo7-Mae** [comment]
I have more concerns about this overlay: I live in a relatively small town so I've mapped every single public sidewalk. On many roads (with sidewalks) the overlay shows a red track and a green track right next to each other. When the road itself is clicked upon it shows a graphic with question marks as if there's no sidewalk information at all.

Additional question: the popup menu of that graphic shows me the untranslated option "Split way". I want to contribute a proper translation so what is meant by a "Split way"?

**Comment by matkoniecz** [comment]
> I have more concerns about this overlay: I live in a relatively small town so I've mapped every single public sidewalk. On many roads (with sidewalks) the overlay shows a red track and a green track right next to each other. When the road itself is clicked upon it shows a graphic with question marks as if there's no sidewalk information at all.

you mapped sidewalks as separately existing `highway=footway`, right? In such case one may add on carriageway info that sidewalk exists and is mapped separately, right now this is not mapped that is why it is showing as red

> Additional question: the popup menu of that graphic shows me the untranslated option "Split way". I want to contribute a proper translation so what is meant by a "Split way"?

it is option to split way into parts, so each can be given a different asnwer

**Comment by meiphoo7-Mae** [comment]
Thanks.
Your explanation about "Split way" makes it clear to me what it means. I'll see if I can provide a translation.
I'm not sure right now how I mapped the sidewalks but I'll look at it again. Your suggestion sounds very plausible to me.
Since I appear to be the only mapper in my town it looks like I've some work to do. :smile:

**Comment by westnordost** [comment]
> I planned to use it to review for missing and wrong sidewalk=separate taggings and currently this seems not possible

This is deliberate. If the sidewalk tags on the highlighted road was missing, it would be marked as red.
