### ISSUE TITLE
red for missing data and black for `=no` is confusing, at least to me

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4128]
I keep expecting that red is for `no` and black is for missing data.

Maybe some ugly garish pink for missing data would be better?

**Comment by legofahrrad** [comment]
> Maybe some ugly garish pink for missing data would be better?

Pink would lead to confusion, at least in the dark theme. Railway tracks are already pink coloured.

**Comment by mnalis** [comment]
Ugly pink would work fine for me (the Vespucci also uses that for missing data there and it's quite clear and understandable).
 
Dark theme does indeed use pink for railway, perhaps that could be changed instead? I never liked that bright pink for railway (and bright cyan for bigger roads) anyway - it's supposed to be **dark** theme so I can comfortably use it low-light conditions, and not have eye-piercing spikes like that. Couldn't they just be tones of subdued dark greyish-violet like the rest of roads, or something?

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/streetcomplete-mapstyle/issues/107 (Maybe railways in dark mode are too prominent)

I actually started doing this, but want to solve https://github.com/streetcomplete/streetcomplete-mapstyle/pull/130 first

**Comment by westnordost** [comment]
Would it help if sidewalk=yes was blue, not green?

The reason for choosing red in all overlays as "is missing" is because red is the most disruptive color that is also associated with errors, prohibitions, destructive actions etc. E.g. you want your unit tests to be green, not red.
If "no sidewalk" was red, it could be perceived as something being wrong, something needing fixing.

A pink does not really have an association with errors and mistakes.

**Comment by boothym** [comment]
> Would it help if sidewalk=yes was blue, not green?

You cannot have green and red as the only thing differentiating between yes/no values if you want to be accessible to colourblind users, so yes blue would be better.

**Comment by mnalis** [comment]
Note that there are several types of color blindness, you can check how they perceive the colors for example [here](http://colorlab.wickline.org/colorblind/colorlab/) or [here](https://www.toptal.com/designers/colorfilter). 

General advice though is never use **just** color to indicate differences. (but also use different symbol, type of dashed line etc.)

**Comment by peternewman** [comment]
> A pink does not really have an association with errors and mistakes.

Maybe not that, but I, and clearly others in this thread use it as a "highlighter" colour. E.g. I'll flag a cell in a spreadsheet like that where the value is a bit of an estimate or

> "is missing"

 entirely.

For both lit and sidewalk, they are nominally a tri-state (is or isn't lit, sidewalk present or not) and then data is missing. With possibly some further refining of some values (e.g. lit/night and day/automatic are all essentially "true", likewise "yes" and "separate" are broadly the same for sidewalk). Which I'd have thought, and indeed seem to be, somewhat related.

**Comment by westnordost** [comment]
Thank you for the link, @FloEdelmann

**Comment by matkoniecz** [comment]
@westnordost 

> Would it help if sidewalk=yes was blue, not green?

Maybe? Hard to guess how I would react initially, without being aware what is being shown. But it would break green-red dynamic at least.
