### ISSUE TITLE
Unclear how to answer fire hydrant position quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4138]
I somewhat frequently stumble upon fire hydrants where I don't know how to answer the position quest.

Mostly this is when the hydrant is on a way that is neither a road nor a sidwalk, but there are also other things like paved patches in the grass.
Looks like I am not the only one with problems here: https://wiki.openstreetmap.org/wiki/Talk:Tag:emergency=fire_hydrant#Clarification_for_fire_hydrant:position?

What could be done here? Well, I don't really know, it probably depends on whether those cases are covered by any of the 4 documented values.

**Comment by TS-R** [comment]
I think the propose is not to describe the sururrounding area. I think it is about describing the accessibity in case of an emergency. So I think any location that is no street, sidewalk or parking space is intended to be taged as green.
Hydrant located in the green for example may be accessible always were hydrant on parking slot may be covered by parking cars.

**Comment by Helium314** [comment]
If you absolutely need actionable suggestions: remove this quest because not all answers can be tagged.

But I was hoping to get descriptions adjusted, e.g. *if* your interpretation is seen as acceptable.

**Comment by westnordost** [comment]
I have been tagging it similarily as according to @mnalis definition. Cycle tracks are "sidewalks" in that regard too as well as plazas or an "island" of paved stones in an otherwise grassy area. The fire hydrant position is about discoverability.

**Comment by mnalis** [comment]
Maybe something along lines of this would clarify it, @Helium314 ?

```diff
- On the sidewalk
+ On the sidewalk, cycleway, or other pedestrian area
+ On the sidewalk, cycleway, plaza, ...
- In grass or dirt
+ In grass or dirt, outside of walking area
``` 

Even shorter would be better if possible, while still retaining clarity. 
Or maybe even just one needs better description, and another one would be clearer by that also?

**Comment by Helium314** [comment]
Something along `On the sidewalk or other path` and `Outside of walking/driving area` would help, if this is actually acceptable tagging.

**Comment by HolgerJeromin** [comment]
> On the sidewalk, cycleway, or other pedestrian area

https://www.mapillary.com/app/?pKey=934935770641639

All this is pedestrian area, but still my feeling would be that we have `lane` and `sidewalk` here.

**Comment by mnalis** [comment]
> All this is pedestrian area, but still my feeling would be that we have lane and sidewalk here.

I agree. Do note that pedastrian areas would _also_ include things like squares, or paved paths through a park (which I would not consider "sidewalk" as it is not on a side of a road), etc.

**Comment by mnalis** [comment]
> Something along `On the sidewalk or other path` and `Outside of walking/driving area` would help, if this is actually acceptable tagging.

That would look reasonable descriptions to me. 

But if you _suspect at all_ that there is reasonable doubt this interpretation **_might not be acceptable_**, then that discussion absolutely should be raised on [Tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list) (and discussion linked to a [wiki talk page](https://wiki.openstreetmap.org/wiki/Talk:Tag:emergency%3Dfire_hydrant#Clarification_for_fire_hydrant:position?)).

And by all means, if you're not sure (i.e. have doubts) that you'd be tagging some specific correctly, select `Can't say` answer (that's what I do - or disable whole quest if such uncertainty happens way too often). According to the [taginfo](https://taginfo.openstreetmap.org/keys/fire_hydrant%3Aposition#values) there is less that 1% of mapped uncertainty (i.e. other custom values). 

<details>

<summary>That probably indicates either:</summary>

- it's happening more often, but users decide not to add `fire_hydrant:position` when not sure (perhaps leaving a note, or not)
- situations where users are not sure are not happening all that often
- majority of users are "sure" in interpretation described in more detail in this ticket; in which case everything is OK and no action is needed
- users are "sure", but one group in this definition, and another group in some other definition; in which case the tag distinction is doomed already, and both `sidewalk` and `green` are synonyms for same (more general) meaning "not on street nor on parking lot"

</details>

**Comment by westnordost** [comment]
Using the more comprehensive "walkway" term now (=sidewalk + other footways and engineered surfaces) and include "shrubbery" in green.
