### ISSUE TITLE
reduce required priviledges to upload GPS traces (do not require to "read your private GPS traces")

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4141]
**Use case**

PR https://github.com/streetcomplete/StreetComplete/pull/3573 implemented ability to upload GPS traces.

As noted in https://github.com/streetcomplete/StreetComplete/issues/4122#issuecomment-1159446934 this seems to require that users grant not only a right to `upload GPS traces` (which is obviously needed) but also a right to `read your private GPS traces` which should **not** be needed. That is unnecessary requirement which allows the SC to access all history and tracks by the user marked private, and as such should be eliminated in order to preserve as much of user's privacy, following the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). 

**example**:
I've done some testing and it seems that GPS tracks get uploaded just fine (as [API 0.6 docs suggest](https://wiki.openstreetmap.org/wiki/API_v0.6#GPS_traces)) when  `read your private GPS traces` is **not** granted, however SC does not seem to detect successful upload, and forces re-login and retries uploading traces.

That results in traces being uploaded multiple times, while OSM Note get created only when both `upload GPS traces` and `read your private GPS traces`  are finally granted.

e.g. https://www.openstreetmap.org/note/3230296 was created when I finally allowed both of them, while several traces (see multiple instances of `_54432_10_19T12_53_20.000000Z.gpx` at https://www.openstreetmap.org/user/mnalis%20ALTernative/traces).

**Proposed Solution**

SC should **not** require `read your private GPS traces` permission.

Original author @goldbattle [offered to look into it](https://github.com/streetcomplete/StreetComplete/issues/4122#issuecomment-1159621000).

**Comment by westnordost** [comment]
I created a PR  #4143 . Didn't test. Would you like to test it?

**Comment by mnalis** [comment]
Yes. Will try tommorow.

**Comment by mnalis** [comment]
As to when to update token permissions:

- users uploading changesets with problematic StreetComplete `44.x`: [this OsmCha](https://osmcha.org/changesets/?filters={%22editor%22%3A[{%22label%22%3A%22StreetComplete%2044%22%2C%22value%22%3A%22StreetComplete%2044%22}]})
- SC `44.x` notes with actual GPS Traces attached can be found in [this osm-note-viewer](https://antonkhorev.github.io/osm-note-viewer/#mode=search&q=GPS+Trace&sort=created_at&order=newest&closed=-1&from=20220710T000000Z&map=3/51.12421275782688/9.140625000000002) by updating `date range` and entering this in `Filter` field:
```
*
text ~= "StreetComplete 44"
```

(currently 4 notes in last week)

**Comment by westnordost** [comment]
Basically blocked by #4289 (by the fact that current versions of StreetComplete will currently not appear on F-Droid)

**Comment by mnalis** [comment]
While #4289 is still active (pending _either_ Google actually opensourcing the lib, _or_ the ARcode being moved to separate companion app), the f-droid part is fixed now, so this issue is no longer blocked.

**Comment by westnordost** [comment]
removed the "read your private GPS traces" permission now.
