### ISSUE TITLE
Ask for shoulder on motorways and links even if there is not cycling/pedestrian infrastructure

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4148]
**Use case**

I've recently noticed that I'm not being asked for shoulders where I think it would be reasonable (and shoulders exist), e.g. on this motorway: https://www.openstreetmap.org/note/3218529

It seems to because the code requires motorways to have cycling or pedestrian infrastructure in order for this quest to be asked:
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/shoulder/AddShoulder.kt#L35-L36

Looking at the other part of that query for other types of road it seems not to have that limitation (it may even explicitly look for `sidewalk=no` in order to allow it, which is completely opposite!).

I do not get the reasoning (especially as in my part of the world, motorways are prohibited from having them by law).
Is that intended behaviour? (why?) 

It looks like an error to me, because e.g.
`highway=primary`+`motorroad=yes` (without foot/bicycle=yes) seems it would be allowed, but `highway=motorway` wouldn't.

**Proposed Solution**

Enable shoulder quest on `highway=motorway` too. (or add a comment explaining a logic / why it's excluded)

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/commit/6908b2d9d42a0a0d5733269e43fbaeb196b87f9f - previously it was not asked at all, as nearly all motorways have shoulders

But in this case this info is especially valuable, so it started to be asked

> or add a comment explaining a logic / why it's excluded

feel free to make a PR

**Comment by mnalis** [comment]
> [...] nearly all motorways have shoulders

Thanks, @matkoniecz; so the reasoning being `shoulder=yes` is implicit on motorway, so no need to spam users. 

I'm still confused then **why we do ask** about shoulders for example for `highway=trunk` + [motorroad=yes](https://wiki.openstreetmap.org/wiki/Key:motorroad)? According to wiki, it would imply _"[...] road on which the traffic rules are the same as on a motorway"_; yet we treat it differently then `highway=motorway`? Is that on purpose?

> I would suggest asking at least where `bridge=*` or `tunnel=*` as these are more likely to have a `shoulder=no` compared to a regular section, does that sound reasonable?

Makes sense to me, @andrewharvey; I can add that too in PR then (if nobody complains).

**Comment by westnordost** [comment]
In general, the app does not ask about anything on motorways because this is an on-foot app and there is no way to access a motorway. Maybe it makes sense to ask if there is a shoulder in a tunnel, but while one may argue that you can see some properties of a motorway from an overpass or on top of a tunnel, certainly you won't see into the tunnel.

Hence, displaying quests to the user he cannot answer do not satisfy the 🐿️/🕵️/🤔 guidelines. (This is why nothing is asked for private roads/paths/etc too)

**Comment by mnalis** [comment]
Well, I obviously agree about `access=private`, but I'd note that StreetComplete is used in more **transportation modes** than just _on foot_, which was actually one of the reasons to implement [quest presets](https://github.com/streetcomplete/StreetComplete/issues/1654#issuecomment-741726535). 

While I certainly do more mapping on foot then in other transport modes, I do have quest presets for when I map while driving in **bus/coach**, or as a **passenger in a car** etc. - which do not have problem driving on motorways.

**Comment by andrewharvey** [comment]
>  this is an on-foot app

I've used SC, on foot, as a car passenger, on a bus, on a train, on a bicycle. I still need to unlock on a ferry, on a kayak, on a plane.

Bus or car passengers could still answer the quest about motorway tunnels, it's not an issue for those on foot as they won't come close to be able to answer the quest.

**Comment by westnordost** [comment]
See also #4155
