### ISSUE TITLE
shop replacement does not seem to work in wheelchair quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4149]
When solving wheelchair accessibility quests at this rent-a-car https://www.openstreetmap.org/note/3218096 I wanted to answer `It does not exist...` as the data changed, expecting that I would be asked to provide what is now there (as I was asked before in other quests, like `opening_hours`, when I chose `It does not exist...` option). 

However, it simply opened a window to leave a Note.

**How to Reproduce**
- find quest eligible for `wheelchair` , like https://www.openstreetmap.org/node/505656379
- choose `Other answers` / `It does not exist...`
- notice that you're prompted with `Create new note` (as opposed to `What's here now instead?`, which happens when you choose `It does not exist...` in for example `opening_hours` quest).

**Versions affected**
upstream v43.2, as well as my fork of 45.0-alpha1+, Android 10

**Comment by Helium314** [comment]
This is intentional, only shops can be replaced. See https://github.com/streetcomplete/StreetComplete/blob/4ae8fcec6305f6d653d9f6ae91e51e6b8ebc2f2f/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractOsmQuestForm.kt#L225

**Comment by mnalis** [comment]
Interesting, thanks for finding that. I wonder why, though?

Although https://github.com/streetcomplete/StreetComplete/blob/v43.2/app/src/main/java/de/westnordost/streetcomplete/osm/Shop.kt#L66-L79 gives some hints (possibly too large amenity? Although in my case that `car_rental` just is small office, same as `travel_agent` which is seemingly accepted)

But more importantly, it seems to me very confusing that **option which is named the same** does completely **_different things_**  - especially as the thing it does (`Leave note`) is **a duplicate** of another option in that same menu. 

Because, even if for some reason it is deemed that some location should not be allowed to have purpose changed, wouldn't it be less confusing to **hide** that `It does not exist...` option completely? Instead of leaving the option there, but making it do different thing (i.e. being the duplicate of already existing option  `Can't say / Leave note`)?

**Comment by peternewman** [comment]
I initially thought yes, but actually, personally I'd say the menu item shouldn't come and go for the same quest depending on the item being answered; "it does not exist" is the best option when available, so you want to encourage people to use it (and hence they need to know its there even if the first thing they try and change isn't eligible), but maybe for things like this there should be a little interstitial "this object is potentially too big to be replaced by SC, please leave a note with info of what's here now" or something similar.

**Comment by westnordost** [comment]
I'll close this then
