### ISSUE TITLE
Wrong picture in preview for shoulder quest

### ISSUE THREAD

**Issue by TS-R** [streetcomplete/StreetComplete#4153]
If "Is there shoulder" quest was selected and one of the both amswers was selected, the preview shows the wrong image. For example if I select no shoulder the preview is showing the shoulder image and vice versa.
The data uploaded to OSM is correct value which was choosen as answer.

**How to Reproduce**
Select any "is there shoulder" quest, tip on one street side. After selecting the answer the wrong image for preview is shown in preview area at display bottom 

**Versions affected**
v45 alpha1

**Comment by FloEdelmann** [comment]
Duplicate of #4116.

Thanks for reporting anyway!
