### ISSUE TITLE
New quest - leisure=pitch access

### ISSUE THREAD

**Issue by vehrmann** [streetcomplete/StreetComplete#4154]
### General
Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access)
Question asked: **Who is allowed to use this pitch?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose

> Out of ~2 million pitches 4.3% have the tag `access` ([taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations)).
> It is very useful for finding public pitches, especially pitches which are typically available for both public and private/customers'/members' usage (e.g. soccer pitches in Germany).

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

> Same answers as for `[leisure=playground][access=*]`:
> yes / private / customers / permissive
> Where `private` also could cover members of sports clubs (could maybe also be covered by `access=permit`, couldn't find anything in the wiki)

- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
> It should be obvious either by no sign at all (=public), a sign stating the access (e.g. for members only) or a fence/locked area
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Similar to the playground access quest ([#1134](https://github.com/streetcomplete/StreetComplete/pull/1134) and [#3712](https://github.com/streetcomplete/StreetComplete/pull/3712))

**Metadata needed:** 
Don't think so.

**Proposed UI:**
**Icon**
![image](https://user-images.githubusercontent.com/60914642/175518211-37e9e4b3-a3d0-49b9-8d47-5680d6572970.png)
combined with the key of e.g. the bicycle parking access quest
![image](https://user-images.githubusercontent.com/60914642/175518270-cb8c1cea-29ea-41fd-982d-00f83df493eb.png)

**Answers**
Similar to the playground access quest ([#1134](https://github.com/streetcomplete/StreetComplete/pull/1134) and [#3712](https://github.com/streetcomplete/StreetComplete/pull/3712))
Maybe inlcude member access

**Comment by westnordost** [comment]
Unlike for playgrounds though, you would not usually find a sign "for members of this sport club only" or similar on pitches that belong to a sports club.

**Comment by vehrmann** [comment]
> Unlike for playgrounds though, you would not usually find a sign "for members of this sport club only" or similar on pitches that belong to a sports club.

In that case a pitch would be fenced or access would be restricted in some other way.
I don't know a pitch without a sign which would be easily/legally be usable but belongs to a sports club.

**Comment by westnordost** [comment]
Well, I know plenty

**Comment by westnordost** [comment]
So I am closing this on the grounds that I am not convinced that this information is always apparent (for pitches that are NOT public):
> 🐿️ Easily answerable by everyone from the outside but a survey is necessary

Additionally, the cases
> access=customers for swimming pools: [example](https://www.openstreetmap.org/way/72919226)
> access=private for professional soccer training areas: [example](https://www.openstreetmap.org/way/24001008)
> access=permit (=for members only) for tennis courts: [example](https://www.openstreetmap.org/node/8629229313)

would be really hard to distinguish for surveyors. If e.g. a tennis court belongs to a sports center / club, it doesn't necessarily mean that you need to be a member to play there. It could be that they have day tickets too. And it goes the other way as well (maybe not for tennis courts, I don't know): it could even be a professional training areas where you can't even be a member to play. Again, these two are also hard to distinguish and certainly not from the outside, which also does not suffice the ...

> 🕵️ Publicly accessible: The information the users are supposed to collect must be easily accessible from the outside, don't lead users into trouble. I.e. users will not be able to answer reliably if a building has a basement or not, if a restaurant has toilets or not etc. without entering it.

guideline.
