### ISSUE TITLE
Quest interface improvements "What is signed at the entrance?"

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4160]
1. The Ok button does't go to the next field
2. "to" is getting malformed here

**How to Reproduce**

https://user-images.githubusercontent.com/25708359/175819955-c61bca56-80ee-4b0b-a0e2-c8711a990dac.mp4

**Versions affected**

StreetComplete 45.0 beta1
Samsumg Galaxy A52. Android 12 OneUI 4.1

via https://github.com/streetcomplete/StreetComplete/discussions/4157#discussioncomment-3026396

**Comment by matkoniecz** [comment]
> 1080 x 2400 pixels, 20:9 ratio (~407 ppi density)

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

**Comment by westnordost** [comment]
It looks like the ABC button better should go to the upper right corner

**Comment by matkoniecz** [comment]
I think that would require custom interface in this mode rather than reusing components, and in "just flat range" the issue would be anyway present...

**Comment by westnordost** [comment]
I don't quite understand. Can't it just float on top?

**Comment by matkoniecz** [comment]
First part of the fix: https://github.com/streetcomplete/StreetComplete/commit/6bcbe1b1bca79c2a47a03309ee92285f8f5f5816

**Comment by deevroman** [comment]
> First part of the fix



<details>
<summary>45.0 not fixed :(</summary>


![Screenshot_20220704-144453_StreetComplete](https://user-images.githubusercontent.com/25708359/177148269-814c650f-eaad-4e94-a2ac-9a47ee5df4f6.jpg)

</details>

**Comment by westnordost** [comment]
Well, the issue is still open.

**Comment by matkoniecz** [comment]
The problem is that I tried something that worked for building levels form and for some reason I cannot bring it to life. See https://github.com/matkoniecz/Zazolc/commits/updown

**Comment by westnordost** [comment]
I can take care of it if you like

**Comment by matkoniecz** [comment]
If you can figure what is going on here I would be thankful as honestly I am really confused.

**Comment by deevroman** [comment]
45.1 ![Screenshot_20220718-151214_StreetComplete.jpg](https://user-images.githubusercontent.com/25708359/179549063-66268493-c659-483d-b086-982c36f1ad4f.jpg)

Maybe replace with `—`?

**Comment by westnordost** [comment]
I think I found the culprit, see the linked commit. There was a fixed width on that textfield. So if you use a different font that is slightly larger or set the standard text size a bit higher, that would explain this behavior.
