### ISSUE TITLE
Enable bus stop ref in Ireland

### ISSUE THREAD

**Issue by andrewmccarthy** [streetcomplete/StreetComplete#4161]
**How to Reproduce**
The quest "What number or code identifies this stop" is "Never shown in Ireland", but all Irish bus stops have (as far as I know) a number, usually displayed on the stop.

Please enable this quest in Ireland!

**Versions affected**
v44.1

**Comment by westnordost** [comment]
And a name?

**Comment by andrewmccarthy** [comment]
Yes, they usually also have a name (although the name may not be unique if there are several adjacent stops). The visual style can vary, but this example is stop 136421 with name Leinster Street (Sráid Laighean in Irish).
![2020-04-04 13 54 20](https://user-images.githubusercontent.com/6887733/175832077-1a544451-1086-45d8-9ab0-706a5f030499.jpg)

**Comment by Cj-Malone** [comment]
@andrewmccarthy [NaPTAN](https://data.gov.ie/dataset/2017-national-public-transport-access-nodes-naptan) may interest you.

**Comment by westnordost** [comment]
Looks good, I enabled it
