### ISSUE TITLE
Lit quest doesn't show up

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4162]
I've activated all lit quests and the overlay for lit:

![Screenshot_2022-06-27-00-01-35-918_de.westnordost.streetcomplete.jpg.png](https://user-images.githubusercontent.com/614929/175835478-3f6339dd-5489-4d27-a1a8-b9338c31e77e.png)

But the lit quest doesn't show up for those red roads, so I can't add this information, which kinda defeates the purpose of the overlay:

![IMG_20220627_000210.jpg](https://user-images.githubusercontent.com/614929/175835496-e012ccda-abdd-4f3b-a0ff-8cd325817ea5.jpg)

(yes I've downloaded data for this area) 

Here are the tags for one of the red streets:

```
highway=residential
maxspeed=30
maxspeed:type=DE:zone30
name=Etzelstraße
```

**How to Reproduce**

Does reproduce always. 

**Versions affected**
45.0-beta1

**Comment by westnordost** [comment]
Lit quest is not shown when the lit overlay is shown.

**Comment by peternewman** [comment]
More specifically, tap a pink bit to answer it, or a green bit to correct/update what's currently mapped.
