### ISSUE TITLE
Sidewalk surface quest: Surface image obscures text

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4164]
**How to Reproduce**

- Find quest `What's the surface of the sidewalk here ?`
- Select surface
- Surface image is superimposed on illustration (Surface image is circular on illustration)

**Versions affected**
Android 12 - v45.0-beta1

**Comment by westnordost** [comment]
What exactly is the issue here?

**Comment by Jean-BaptisteC** [comment]
![Screenshot_20220627-181241~2](https://user-images.githubusercontent.com/87148630/176477991-2516be0f-723e-4065-b7c2-f3bca4dd9d50.png)

**Comment by westnordost** [comment]
And what is the issue?

**Comment by mnalis** [comment]
Ah, I see, so the **text** should be on **_uppermost_** layer, so it is always visible. Then below text would be the circle with material, and below that the background image of the road.
