### ISSUE TITLE
Add foot=use_sidepath when answer to "Is there a pavement along this street" is "displayed separately on map" for both sides

### ISSUE THREAD

**Issue by kuba-orlik** [streetcomplete/StreetComplete#4165]
**Use case**

In order for routing engines to plan precise and legal routes for pedestrians, the `foot=use_sidepath` tag has to be applied to roads that do not permit pedestrian traffic, to avoid issues like these:

* https://github.com/graphhopper/graphhopper/issues/2610
* https://github.com/organicmaps/organicmaps/issues/2816

**Proposed Solution**

If sidewalk is mapped separately for both sides of a road, it means that the road itself does not permit pedestrians to walk along that road and they should use the sidewalk. Adding `foot=use_sidepath` in such a scenario after gathering an answer for the "Is there a pavement along this street?" question could improve this situation

**Comment by westnordost** [comment]
Can `foot=use_sidepath` not be inferred by data consumers from the information `sidewalk=separate` (and variants)?

**Comment by matkoniecz** [comment]
> If sidewalk is mapped separately for both sides of a road, it means that the road itself does not permit pedestrians to walk along that road and they should use the sidewalk. Adding foot=use_sidepath in such a scenario after gathering an answer for the "Is there a pavement along this street?" question could improve this situation

Why StreetComplete would be needed here? JOSM with filters is much more efficient here, and 

> Is there a pavement along this street?

question cannot be used to mark `foot=use_sidepath` as it would be applied only if sidewalks are separately mapped. And asking "Is there a mapped pavement along this street?" is not benefiting from survey.

And SC already asks about sidewalks if possible (note that nearby footways along road cause this question to be skipped).

**Comment by matkoniecz** [comment]
> it means that the road itself does not permit pedestrians to walk along that road and they should use the sidewalk

Not in all countries, not in all cases.

In particular Poland has some `highway=living_street` and `highway=pedestrian` with sidewalks and pedestrians are still allowed to walk everywhere.

Also, routers can use `sidewalk=separate` and its variants.

Closing, as it would result in silently adding invalid data and mentioned places were not affected by StreetComplete.
