### ISSUE TITLE
Is it allowed to walk along this street?

### ISSUE THREAD

**Issue by kuba-orlik** [streetcomplete/StreetComplete#4166]
### General

Affected tag(s) to be modified/added: [foot](https://wiki.openstreetmap.org/wiki/Key:foot)
Question asked: **Is it allowed to walk along this street?**

* no - Access on foot or by pedestrians is prohibited or impossible
* Yes, on a sidewalk mapped separatetely** 
* Yes, it's designated for pedestrians

The end goal is to avoid issues like https://github.com/graphhopper/graphhopper/issues/2610 and https://github.com/organicmaps/organicmaps/issues/2816

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** select element without a `foot` tag

**Comment by mcliquid** [comment]
This quest is already implemented the other way around:

![Screenshot_20220627-185406](https://user-images.githubusercontent.com/3351668/175994695-fa07746d-72a4-410b-a7ad-f92b42c444c7.png)

**Comment by matkoniecz** [comment]
> The end goal is to avoid issues like https://github.com/graphhopper/graphhopper/issues/2610 and https://github.com/organicmaps/organicmaps/issues/2816

Do you know how such missing tagging can be efficiently added with JOSM? If you are interested in mapping missing data I can give some hints how to do this.

In general, mapping with SC is unlikely to be more efficient and likely to result in more mistakes.

**Comment by matkoniecz** [comment]
And for why existing quest is not asked far more often: see "AddProhibitedForPedestrians quest leads to bad OSM data" #2472 

Maybe it would be a good candidate for a new overlay? (@westnordost what you think here? - it could be used by more experienced mappers wishing to fix such missing routing data)

**Comment by westnordost** [comment]
That would be a very specific overlay. In priority, I'd want to get more general overlays going first.

**Comment by kuba-orlik** [comment]
@mcliquid:

> but without an explicit sign that pedestrians are forbidden, it's legally fine to walk on a intersection of a highway=tertiary, secondary or something else :)

Not in Poland, where if there's a sidewalk along the given part of the street, you can't walk on the street itself

@matkoniecz:

> Do you know how such missing tagging can be efficiently added with JOSM? If you are interested in mapping missing data I can give some hints how to do this.

Currently I only have time for mapping while being idle during commute, so StreetComplete is the limit of what I can handle atm. If you have any hints at hand, I'd gladly read those and keep for future reference :)

**Comment by matkoniecz** [comment]
@kuba-orlik Note that substantial improvements here can be done using sidewalk layer: you can spot where `sidewalk=separate` is missing and mark it, what gives hint for routers.

> Currently I only have time for mapping while being idle during commute, so StreetComplete is the limit of what I can handle atm. If you have any hints at hand, I'd gladly read those and keep for future reference :)

I would download data and use filters to exclude

- everything except roads
- roads with `sidewalk=separate`

and using TODO plugin, add everything to review and mark missing `sidewalk=separate` while reviewing ways one by one

Next I would select `sidewalk=separate` without `foot=use_sidepath` and again put it for review with TODO plugin and add this tag where missing and fix `sidewalk` values otherwise.

**Comment by kuba-orlik** [comment]
The sidewalk (labeled "Pavement" in my case) layer is great help indeed, thanks!
