### ISSUE TITLE
Fixing up shoulder corruption

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4170]
Bug was detected in `45.0-alpha1` and fixed afterwards which corrupts `shoulder=*` tags in https://github.com/streetcomplete/StreetComplete/issues/4116. 

Now that `45.0-beta1` has been published with correct code, I think that we should clean up the corruptions. Due to the issues mentioned in https://github.com/streetcomplete/StreetComplete/issues/4116#issuecomment-1164340337, it is probably best to just completely remove those problematic answers rather than trying to correct them. 

Suggestion on procedure:

- blacklist `45.0-alpha1` in https://www.westnordost.de/streetcomplete/banned_versions.txt
- revert the problematic changesets (currently [26 of them](https://osmcha.org/changesets/?filters={%22editor%22%3A[{%22label%22%3A%22StreetComplete%2045.0-alpha1%22%2C%22value%22%3A%22StreetComplete%2045.0-alpha1%22}]%2C%22comment%22%3A[{%22label%22%3A%22shoulder%22%2C%22value%22%3A%22shoulder%22}]%2C%22date__gte%22%3A[{%22label%22%3A%222022-06-13%22%2C%22value%22%3A%222022-06-13%22}]})) - or better remove `shoulder=*` tags on affected ways (because reverts would fail if way was changed after the `shoulder` tag was added)

---

However, would that completely fix the problem? What I'm not sure is whether SC version in database for upload is recorded when the **_quest was made_**, or is **_current_** SC version just attached before uploading?

Because if the later (what I am worried about), the user can make invalid answers with `45.0-alpha1` and then (even if ban that `45.0-alpha1` version) upgrade to `45.0-beta1` (or newer version when it becomes available) and upload the **_still incorrect_** results that now identify themselves as `45.0-beta1` and thus bypass the safety checks. How does that version blacklisting work in practice?

**Comment by matkoniecz** [comment]
> currently [26 of them](https://osmcha.org/changesets/?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22StreetComplete%2045.0-alpha1%22%2C%22value%22%3A%22StreetComplete%2045.0-alpha1%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22shoulder%22%2C%22value%22%3A%22shoulder%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222022-06-13%22%2C%22value%22%3A%222022-06-13%22%7D%5D%7D)

note https://github.com/mapbox/osmcha-frontend/issues/492 which can cause false positives and negatives here

**Comment by westnordost** [comment]
> blacklist 45.0-alpha1 in https://www.westnordost.de/streetcomplete/banned_versions.txt

done

**Comment by mnalis** [comment]
I've done some research, and it seems that **currently installed** version of StreetComplete is always used to mark uploaded data, no matter in what version of SC was the quest solved ([OpenChangesetsManager.kt#L55](https://github.com/streetcomplete/StreetComplete/blob/v45.0-beta1/app/src/main/java/de/westnordost/streetcomplete/data/osm/edits/upload/changesets/OpenChangesetsManager.kt#L55)). That means that if user upgrades to new version with fixed bug _before_ uploading the quests, the corrupted values of the quest would still get uploaded (with new version number), even if the problematic version is banned.

Would it be possible to update code for `45.0` release, so that on startup it drops all not-yet-uploaded `AddShoulder` answers? That way, we could be **sure** that from that version onward there will be _**no corruption uploaded**_.

**Comment by westnordost** [comment]
Given your last comment, though, I think I will remove v45-alpha1 from the blacklist again. alpha1 users should absolutely upload their faulty shoulder answers instead of upgrading to the beta and uploading them then so that it can be cleaned up properly later.

**Comment by peternewman** [comment]
> If that is correct, it would seem that `44.0` and `44.1` answers are also corrupted.

I don't think that's correct @mnalis , just based on the fact edits I've made tagged as "StreetComplete 44.1" have the expected shoulder value I'd imagine, not the reversed one.

**Comment by mnalis** [comment]
Hmmmm, that's strange @peternewman, as that piece of the code in c89f12ac5fbe443be223c66b66d34a568651419b looks like what the fix https://github.com/streetcomplete/StreetComplete/commit/a7ba7e873f648cd63b3ec3cd1d8824ef0935d2d4 changed...

_looking..._ Huh, you seem to be correct, my error. Moral of the story: **never** trust `git log` output without `--graph`. That commit was introduced in time before `44.0`, but was likely in some different branch which got merged just before `45.0-alpha1`.

**Comment by mnalis** [comment]
Another obvious thing (that only just occurred to me :smile:): when we get to fixing this after releasing `45.0`, we only need to undo the answers if they differ from `no`/`no` or `yes`/`yes` - as those two would be correct even in corrupted versions.

**Comment by westnordost** [comment]
Hm, is osmcha broken right now? It just loads and loads and loads, I can't get any result. (@mnalis, or would you like to do the reverting?)

**Comment by westnordost** [comment]
@mnalis, could you do this? OSMCha doesn't seem to work at all and I have no idea how else to find changesets that may include faulty changes.

**Comment by mnalis** [comment]
@westnordost OK I'll take a look

**Comment by mnalis** [comment]
I've done the checks and reverts.
 
Out of **23333** StreetComplete `AddShoulder` changesets, **32** of them were done with _45.0-alpha1_ (**30** _StreetComplete_, **2** _Zazolc_).

Luckily, as noted in https://github.com/streetcomplete/StreetComplete/issues/4170#issuecomment-1173612024, values which are `shoulder=no` or `shoulder=both` are not affected by the bug, so they can be ignored. As those turn out to be a majority, it leaves us with just two potentially problematic changesets:
- https://www.openstreetmap.org/changeset/122570719 by @matkoniecz 
- https://www.openstreetmap.org/changeset/122804550 by @legofahrrad

Moreover, from that **2** changesets, it seems only **3** ways were affected by shoulder orientation bug (i.e. values different than `no|both`):
- https://www.openstreetmap.org/way/93167152
- https://www.openstreetmap.org/way/424095545
- https://www.openstreetmap.org/way/4692786

I've now deleted those **3** `shoulder=left|right` tags in https://www.openstreetmap.org/changeset/125336972 via convenient [Level0](https://wiki.openstreetmap.org/wiki/Level0) editor.

---

Quick&dirty parsing of OSM changesets from GNU/Linux shell used for all this are available  (for interesting parties) in https://gist.github.com/mnalis/f77bbf938230616960ed3947fbcaa212
