### ISSUE TITLE
Better handle rechecking of "bicycle_capacity"

### ISSUE THREAD

**Issue by grrrrr** [streetcomplete/StreetComplete#4171]
At some point in time StreetComplete started asking to recheck if the capacity was correct on `amenity=bicycle_parking` especially when `check_date:capacity`is not set.

The problem is the way it's presented it looks like they have not been mapped before, simply asking what the capacity is, even if the info is in OSM.   This is confusing as it's then hard to tell from StreetComplete what has already got a capacity listed (correctly or incorrectly) and can result in extra foot work to re-check or computer work to check if it was already answered.

It would be very useful if instead, Street Complete asked something like;  "is the capacity at these bicycle stands still X"  which is similar to how some other checks are done,  e.g. `opening_hours`

**Comment by matkoniecz** [comment]
But to verify it then you need to count anyway, right?

**Comment by grrrrr** [comment]
@matkonecz,  At least where I am based, it's very rare for the count to change other than if all the stands were completely removed.

Having the task tell you if it has already been mapped (even if it has been changed) cuts down a bit of the urgency for re-checking.     E.g. I had to do multiple onsite checkings yesterday as I was being asked to fill the count in again, even though I know from passing them daily they have not changed.    But I could not just say "they have not changed"  I'm made put in the number again and as I don't remember the count I have to go around re-counting multiple stands

**Comment by westnordost** [comment]
`check_date:capacity` marks that the capacity has been checked again, not that "it has not changed, whatever was tagged before". To properly check if the capacity is still correct, you need to count them in any case because even if the situation didn't change, it may as well be that it was recorded incorrectly before.

**Comment by grrrrr** [comment]
@westnordost is there a way to separate/differentiate check vs re-check, so as not to be presented with or be able to ignore the re-check?  I know it's not in all cases but in my instance  I am the one adding bike stands in my region. I do it as 

1. via ID editor add stand at location based on open govt data
2. use StreetComplete to add further details once verified on the ground.

These stands do not change once installed (other than a few being removed)

**Comment by mnalis** [comment]
@grrrrr you can select in `Settings` under `Resurvey intervals` option `Ask less often`. It is a workaround, but should help you for now (I think it would ask you to resurvey every 8 years for `stands` and `wall_loops`, instead of every 4 years as it does currently).

**Comment by mnalis** [comment]
I might be reading it wrong, but to me it seems to say 4 years, so I assume that would be what default does: 
https://github.com/streetcomplete/StreetComplete/blob/db27e4a60aed83f7e54530aa96c45c827863d4fe/app/src/main/java/de/westnordost/streetcomplete/quests/bike_parking_capacity/AddBikeParkingCapacity.kt#L14-L23


But I could be wrong. Can you share an example OSM node where it asks you earlier?
