### ISSUE TITLE
Don't ask about pedestrian crossings on low-class roads in Canada and US

### ISSUE THREAD

**Issue by pnorman** [streetcomplete/StreetComplete#4175]
Although they do exist in Canada and the US, crossing islands are rare. In the US, there are 11118 crossing:island=yes, 71232 crossing:island=no, and a total of about 1 million crossings which are marked or have traffic signals.

In particular, I do not believe I have ever seen a crossing island on a residential or tertiary road that is not divided.

Similarly to how crossing on highway=service and all oneway roads are excluded from the quest, I recommend excluding highway=residential, unclassified, and tertiary from it. I'm skeptical about the value of the quest on other road classifications, but don't have data to support it.

**Comment by matkoniecz** [comment]
That is trickier to implement than with toilets (#4174) as would require different queries based on the area.

Thanks for reporting both issues!

**Comment by bgo-eiu** [comment]
Crossing islands are common on residential and service roads in the parts of the US I am familiar with, but I almost always map them with split ways, as in `footway=crossing` over the roadways and `footway=traffic_island` over the island, in which case `crossing:island` never gets used. It is not a rule to map them like this though, so it really depends on how mappers have chosen to represent the crosswalks.

**Comment by westnordost** [comment]
I'll close this as will not fix because it would not be trivial to implement (see https://github.com/streetcomplete/StreetComplete/issues/4175#issuecomment-1170922643) and such adaptions of behavior per-region (in general) would cost a lot of effort to maintain.
