### ISSUE TITLE
Feature Idea: Survey Mode

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#4179]
**Use case**
Sometimes High Streets are either not filled out at all (missing locations) or so outdated that a whole new resurvey is needed

**Proposed Solution**
A resurvey mode could let us see and modify (including shop reset) points and areas which don't otherwise have any quests. Also, allow us to create new objects on the fly.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0-beta1 https://www.openstreetmap.org/user/westnordost/diary/399378

**Comment by TurnrDev** [comment]
Oh that's nice!

**Comment by westnordost** [comment]
Closing, as a feature that kind of solves a similar use case as described has been implemented
