### ISSUE TITLE
The setting Keep screen on does not work

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4189]
**Versions affected**
StreetComplete 45.0
Samsumg Galaxy A52. Android 12 OneUI 4.1

**Comment by Jean-BaptisteC** [comment]
How reproduce:
- Open Street Complete
- Go to settings
- enable `keep screen on`
- Wait somes minutes

Screen turn off after somes times (time set on Android settings)

**Versions affected**
StreetComplete 45.0
Pixel 6. Android 12

**Comment by westnordost** [comment]
Curently the setting is only applied to the main screen when that main screen is created.

I changed it so that the setting is applied each time the screen comes back into foreground.
