### ISSUE TITLE
Add roof shape orientation

### ISSUE THREAD

**Issue by Coolawik** [streetcomplete/StreetComplete#4197]
**Use case**
We could tag buildings roof shape in app. Could you also add a choice of roof shape orientation for some of the selected roofs?

**Proposed Solution**
It could be useful for these chosen types of roofs:
1. gabled
2. hipped
3. half-hipped
4. round
5. gambrel
6. mansard
and create tag roof:orientation="along" or "across"

[article in OSM wiki](https://wiki.openstreetmap.org/wiki/Key:roof:orientation)

**Comment by matkoniecz** [comment]
#1063 (blocked by missing functionality in an upstream project, can be also solved by someone making such project - once that happens the blocked issue will be reopened)
