### ISSUE TITLE
Quests for Amenities at Campsites

### ISSUE THREAD

**Issue by markongh** [streetcomplete/StreetComplete#4198]
### General
For nodes and ways (areas) with the tag "tourism=camp_site" request information about amenities of that campsite.
Affected tag(s) to be modified/added: There are many keys/attributes of camp_sites listed here: https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site however, I am requested quests be created for the following attributes with the corresponding questions:
https://wiki.openstreetmap.org/wiki/Key:fee
Question asked: **Does this campsite require a fee?**
https://wiki.openstreetmap.org/wiki/Key:tents
Question asked: **Does this campsite allow camping in tents and is the terrain suitable for tents?**
https://wiki.openstreetmap.org/wiki/Key:caravans
Question asked: **Does this campsite allow camping in vehicles such as RVs, vans, trailers, etc.?**
https://wiki.openstreetmap.org/wiki/Key:openfire
Question asked: **Does this campsite allow open fires?**
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower
Question asked: **Does this campsite have shower facilities?**
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets
Question asked: **Does this campsite have toilet facilities?** 

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
This information will make it easier for people looking for campsites with certain amenities to find them, especially in conjunction with other OSM tools such as https://opencampingmap.org/
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
According to https://taginfo.openstreetmap.org/tags/tourism=camp_site#combinations of the 126,032 tourism=camp_site features...
12 171 (9.66%) have the fee=* tag
12 254 (9.72%) have the tents=* tag
9 134 (7.25%) have the caravans=* tag
4 694 (3.72%) have the toilets=* tag

### Ideas for implementation

**Element selection:** I am unsure what is meant by "Element selection" but all of these quests would modify key attributes within "tourism=camp_site" items, so quest items should show up on the tourism=camp_site object

**Metadata needed:** None.  These should be pretty consistent for all "tourism=camp_site" items.

**Proposed UI:** For all questions, a simple prompt with "Yes", "No", or "Can't Say..." If "Can't Say" is selected, suggest leaving a public note with the option to leave a note or hide the quest for the user.
This is the same prompt/UI for the quest to determine if there is an air compressor at fuel stations which could be repurposed for these camp_site quests.

**Comment by matkoniecz** [comment]
> Does this campsite require a fee?

are you sure that it passes

>  Not an overwhelming percentage of quests have the same answer (No spam)

**Comment by mnalis** [comment]
I also (as a cyclotourist) find two other features of camp sites extremely useful:
- `drinking_water=*` (2.15%)
- `power_supply=*` (2.63%)

(and of course `phone` / `website` / `contact:*`, but those are quite another type of entry)

**Comment by mnalis** [comment]
> are you sure that it passes
>   Not an overwhelming percentage of quests have the same answer (No spam)

According to quick taginfo check and some calculation:

- `fee=*` tag - 70% `yes` values
- `tents=*` tag - 94% `yes` values
- `caravans=*` tag - 71% `yes` values
- `toilets=*` tag - 77% `yes` values


So `tents=*` is possibly spammy, but the others look ok. (one might try more advanced overpass queries to check the stats of the rest which are not listed in taginfo - if they haven't used up their overpass quotas)

**Comment by matkoniecz** [comment]
> According to quick taginfo check and some calculation:
> fee=* tag - 70% yes values
> but the others look ok.

right now it is heavily biased toward `no` values, I expect that for remaining ones overwhelming answer is "yes, as usual" and asking for all of them is quit pointless.

I suspect the same for `toilets` and `showers` if such tag exists. And `tents` to be overwhelmingly yes.

`power_supply=yes` actually seems a valid, disabled by default, quest.

**Comment by mnalis** [comment]
- In my limited experience (it just about a two dozen campsites or so, geared towards cheaper ones), if it is payed and fenced camping site (i.e. `fee=yes`), it will also have `toilets=yes`, at least in huge majority of them. Unfortunately, those might often be ToiToi or alike chemical toilets only (esp. in smaller and cheaper and remote areas), and that may (but need not) result also in `drinking_water=no` (e.g. only wipes / desinfectant or such).

- `fee=no` are usually probably just a nice spots with no infrastructure whatsoever. While I would not map those as `tourism=camp_site` myself, they are a few on the OSM I've stumbled upon. But, those likely could be dealt with leaving a note, although I don't know what is the best way to handle those notes (they _are_ useful, especially in some areas where there is no real camp nearby, so just deleting them is not ideal, but I don't know of correct tagging to preserve then then `fee=no` - which really any but first-time camper will understand what that entails: _"you get what you pay for"_ :smile: )

- `caravans=*` makes sense to me too -- many smaller campsites are tent-only (people often offer them in back garden of the house or a bar, where only 3-5 tents would fit, and no caravan etc). While I have not specifically looked for reverse situation (i.e. caravans allowed but not tents) I suspect it would be much rarer situation. Perhaps it could be 3-answer quest `Who may camp here` - `Tents only` / `Caravan only` / `Both`? That would cover all situations with not much more work for user than yes/no quest for `caravan=*`.

- `showers` are not that certain in my experience either. They will surely be available at bigger campsites (i.e. ones with many concrete buildings), but often not present at smaller ones (where often only "building" is owner's kiosk for admittance at entrance). Although not nearly as rare as ones offering `laundry` machines (which are way below 10% IMHO, so probably not eligible for additional quest), `showers` certainly are not a certainty (maybe present at about 1/2 to 2/3 of camps I've visited).

**Comment by markongh** [comment]
What about in back country camping areas within National Parks where you may have to pay for a permit, but there are no facilities at the camp site location?  I think what Europeans refer to as "wild" camping tends to be more common in the United States as "back country" camp sites.

In Italy I have seen quite a few locations that are caravan/camper vans only with no pitches for tents (i.e. they are brick or paved parking spots intended for campers within facility catering to them).  I have seen these as both fee and no fee sites, usually depending on the level of services provided.  
I do like your implementation of the "Who may camp here?" question.  That single question could cover the caravan=* and tents=* tags at the same time.

I know there is debate about whether or not "an overwhelming percentage of quests have the same answer," but I also look at it as ensuring completeness of data in order to improve the usefulness of tools that may filter on that data.  This data would significantly improve the usefulness of a tool like https://opencampingmap.org/ 
StreetComplete already asks for data that is over 80% the same answer....for example parking=surface for parking is 82.84%.  That doesn't mean the data isn't useful.

**Comment by markongh** [comment]
> I also (as a cyclotourist) find two other features of camp sites extremely useful:
> 
>     * `drinking_water=*` (2.15% of campsites, with 59% `yes` values)
> 
>     * `power_supply=*` (2.63% of campsites, with 79% `yes` values - although in my experience it is much less than that cry, maybe 1/3 of them, and that is generous )
> 
> 
> (and of course `phone` / `website` / `contact:*`, but those are quite another type of entry, so not suggested here)

Yes, I also considered some of these other features as well, but wanted to keep it to simple yes/no responses for this bunch of quest suggestions.  drinking_water=* and power_supply=* would also be good though.

**Comment by westnordost** [comment]
What about [`camp_site=*`](https://wiki.openstreetmap.org/wiki/Key:camp%20site)?

**Comment by mnalis** [comment]
> What about [`camp_site=*`](https://wiki.openstreetmap.org/wiki/Key:camp%20site)?

It seems to me better to map separate simple tags then this (less popular) combined `camp_site`, both in ease of use and in usability at all (for example, if the camp has `drinking_water`+`toilets`+`shower` but no `power_supply`, it falls **_between_** `camp_site=standard` and `camp_site=serviced` so it needs those additional basic tags anyway). 

Also, SC specific, separate tags are better due to:
> :atom_symbol: Atomic quests: Per quest, only one thing should need to be answered by the user.

(i.e. for `camp_site=*` user would have to survey all the features before answering the quest; e.g. find out if there is a laundry, even if they do not care about that particular feature, but want to map if there is drinking water).  

---

Anyway, I plan to go camping on bicycle soon to several camping sites, so unless there are objections I'll try to implement (for starters):
- `drinking_water=*` `yes/no` quest
- `power_supply=*` `yes/no` quest
- 3-answer quest `Who may camp here?` ( `Tents only` / `Caravan only` / `Both`) for setting `tents=*` and `caravans=*`

**Comment by matkoniecz** [comment]
This boolean quests seems like a good idea to me.

"Who may camp here?" may be a bit spammy/hard to answer so I am not sure, but I am also not against it.

**Comment by westnordost** [comment]
@mnalis: Maybe the reason why that tag exists is because if a campsite lacks certain amenities, it would not even be considered a campsite anymore (in certain languages/regions), i.e. it at least constitutes a different type of campsite.

For example, "just a lawn on which you may camp" (+ maybe a toilet) is known in Germany as a "Biwakplatz" or "Trekkingplatz" (see also https://wiki.openstreetmap.org/wiki/DE:Trekkingpl%C3%A4tze ), noone would call these kind of places "Campingplatz". Since it is named differently, it is (from that point of view) a different "primary feature", i.e. would have a separate entry in the iD editor presets.

**Comment by vehrmann** [comment]
A thought on `power_supply=*`: when asked, it should be clear if that means a normal power socket e.g. in a building to charge phones etc. or if it means (usually outdoor) sockets at the actual spot to connect a caravan/RV.

**Comment by mnalis** [comment]
The PR #4213 covers most of this, but it does **not** implement following proposed/discussed tags:
- [fee=*](https://wiki.openstreetmap.org/wiki/Key:fee) and [toilets=*](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) as it is not certain if they are not spammy (although PR does allow for marking a site as [backcountry=yes](https://wiki.openstreetmap.org/wiki/Key:backcountry) which changes implied value to `no` for both of them).
- [openfire=*](https://wiki.openstreetmap.org/wiki/Key:openfire), which seems to me might be harder to know unless explicitly signed / asked about (especially if only allowed in certain parts of the bigger camp, it would require much work from SC user).
- [camp_site=*](https://wiki.openstreetmap.org/wiki/Key:camp_site), as it is not currently clear to me that it offers benefits not already conveyed by other tags.

If further discussion here warrants implementing them (or other tags), feel free to discuss the merits here - they might be implemented later as separate PR.

**Comment by markongh** [comment]
> Alternatively, I could also add [backcountry=*](https://wiki.openstreetmap.org/wiki/Key:backcountry) quest with `yes/no` answers, if you think that it would be useful? (**update**: I've added `backcountry` as OtherAnswer in PR).

I do think this would be useful as well, but the quest should be clear on the definition of 'backcountry' based on https://wiki.openstreetmap.org/wiki/Key:backcountry.

**Comment by markongh** [comment]
> > A thought on `power_supply=*`: when asked, it should be clear if that means a normal power socket e.g. in a building to charge phones etc. or if it means (usually outdoor) sockets at the actual spot to connect a caravan/RV.
> 
> Interesting idea @vehrmann; but do you know how to tag those differences in OSM? In places I've been (EU) both outdoor and indoor plugs have been [power_supply=cee_7_3](https://wiki.openstreetmap.org/wiki/Key:power_supply) (Type F/Schuko), so plug type cannot be used to differ them, and there does not seem to be established tag (to my knowledge) to map the difference.
> 
> So at the moment I plan to use `power_supply=yes` (perhaps with wording like `Can you charge your phone/laptop here?`) to map any camp where customer can recharge phone at least (but if there is accepted tag to map the difference, that could possibly be converted to multiple-answer quest).

A thought on this: I have often seen power hookups for caravans/camping vans/RVs referred to as "shore power."  This is stolen terminology from power hookups available for boats/ships when they are in port at a dock.  I do not have a caravan or RV so I don't typically speak the lingo, but perhaps this terminology can help distinguish between power outlets for small devices/appliances and caravans/RVs.

**Comment by Carnildo** [comment]
In regards to fees, I checked the data at http://www.uscampgrounds.info/index.html for the western United States.  About 10% of the campgrounds listed are "free or under $12"; spot-checking those suggests that about one in five of those is 1) free and 2) an actual campground, not dispersed camping.  98% "no"/2% "yes" seems spammy to me, and that's in the area where I'd expect to find the highest concentration of free campgrounds.

**Comment by mnalis** [comment]
> I do think this would be useful as well, but the quest should be clear on the definition of 'backcountry' based on https://wiki.openstreetmap.org/wiki/Key:backcountry.

@markongh It's currently shown as _**"Backcountry camping (no facilities)"**_ in PR https://github.com/streetcomplete/StreetComplete/pull/4213

If you think it should be further improved, feel free to suggest better text at https://github.com/streetcomplete/StreetComplete/pull/4213/files#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R852

**Comment by westnordost** [comment]
Just tagging the author of the open camping map as an important data consumer: @giggls

**Comment by giggls** [comment]
OK, I will add a few thoughts regarding this feature.

https://opencampingmap.org has a bug view itself!
While some of the bugs shown there are beyond the scope of StreetComplete (e.g. site should be mapped as a polygon rather than a single node) most of them are not.

### Here is what i consider the most important missing tags:

1. **campsite name**
campsite does not have a name

2. **campsite category** (see legend on website)
    Here are my supported categories:
    * **ordinary tourist campsite** (camping/caravaning) for tents and caravans/RV
    Tagging: tourism=camp_site, tents=yes, caravans=yes
    * **caravan site** caravans/RV often only glorified parking lots
    Tagging: tourism=camp_site, tents=no, caravans=yes or tourism=caravan_site
    * **tents only campsite** (very rare without backcountry tag)
    Tagging: tourism=camp_site, tents=yes, caravans=no
    * **backcountry very basic campsites**
    Tagging: tourism=camp_site, tents=*, caravans=*,backcountry=yes
    (caravans=yes would be very rare but possible)
    * **group only campsites**
    Tagging: group_only=yes or scout=yes as a special case
    * **nudist campsite**
    Tagging: nudist=yes or nudist=obligatory or nudist=customary or nudist=designated
    (I support them all because a customer should not choose such a site by default)
    * **private campsite**
    Tagging: Like all of the above but with access=private or access=members

    SQL code for category creation is here:
    https://github.com/giggls/osmpoidb/blob/master/gen_poi_campsites.sql

3. **contact information**
Some kind of contact information (centact:*, website or phone) should be available.

4. **campsite features**
    The most important features arguably are:
    * toilets=yes
    * shower=yes
    * drinking-water=yes
    * power_supply=yes
    * openfire=yes (on backcountry campsites)

    For most of these features it is better to map them as individual objects and it would be best to *not show them as missing from the site if this is already the case*, because mapping individual nodes is always better than adding tags to the campsite polygon. I know this is technically complex and I don't know if it would be a viable option to use my json-file for this.

**Comment by mnalis** [comment]
<details>

<summary>Many of those are implemented in StreetComplete (click to expand)</summary>

>     1. **campsite name**
>        campsite does not have a name

OK, we check for name already:
https://github.com/streetcomplete/StreetComplete/blob/6d6807896aa85907eb1fa2dd012e473ca26192ef/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt#L72

> 
>     2. **campsite category** (see legend on website)
>        Here are my supported categories:
>        
>        * **ordinary tourist campsite** (camping/caravaning) for tents and caravans/RV
>          Tagging: tourism=camp_site, tents=yes, caravans=yes
>        * **caravan site** caravans/RV often only glorified parking lots
>          Tagging: tourism=camp_site, tents=no, caravans=yes or tourism=caravan_site
>        * **tents only campsite** (very rare without backcountry tag)
>          Tagging: tourism=camp_site, tents=yes, caravans=no
>        * **backcountry very basic campsites**
>          Tagging: tourism=camp_site, tents=_, caravans=_,backcountry=yes
>          (caravans=yes would be very rare but possible)

We allow for those 4 types above:
https://github.com/streetcomplete/StreetComplete/blob/6d6807896aa85907eb1fa2dd012e473ca26192ef/app/src/main/java/de/westnordost/streetcomplete/quests/camping/CampType.kt#L3-L9

>     4. **campsite features**
>        The most important features arguably are:
>        
>        * toilets=yes
>        * shower=yes
>        * drinking-water=yes
>        * power_supply=yes

those 4 quests are implemented, I found them as most interesting too! https://github.com/streetcomplete/StreetComplete/tree/v46.0-beta1/app/src/main/java/de/westnordost/streetcomplete/quests/camping
        
</details>

I'll comment on non-implemented stuff in several comments, to hopefully make it more digestible. :smile:

**Comment by mnalis** [comment]
> 2. **campsite category** (see legend on website)
>        * **nudist campsite**
>          Tagging: nudist=yes or nudist=obligatory or nudist=customary or nudist=designated
>          (I support them all because a customer should not choose such a site by default)

(key is actually named [nudism=*](https://wiki.openstreetmap.org/wiki/Key:nudism)). I guess it is quite useful if one is looking for exactly such place; but I don't recall seeing it signed on any camp (as opposed to, say, beaches, where I have).

And even if I'd seen naked people inside it seems I'd have a terrible time trying to decide between `yes` / `obligatory` / `customary` / `permissive` / `designated`. Also, [taginfo for tourism=camp_site](https://taginfo.openstreetmap.org/tags/tourism=camp_site#combinations) does not mention `nudism=*` being used, which means that if it is used at all, it is used on less than `0.78%` of camp sites (which is last value listed).

So probably not a good match for SC Quest; perhaps an Overlay for nudism might be an option if there is enough interested parties, as there are several [tags to which it applies](https://wiki.openstreetmap.org/wiki/Key:nudism#Applies_to) ?

**Comment by mnalis** [comment]
> 2. **campsite category** (see legend on website)
>        * **private campsite**
>          Tagging: Like all of the above but with access=private or access=members

I could add OtherAnswer `This is private camp` which adds `access=private`, but I seem to recall from some other issue that that was not particularly welcome (as many other quests could have that as an OtherAnswer).  Or maybe I misremember? Would you like such OtherAnswer for camp sites @westnordost?

(`access=members` would probably need more information like _"members of what?"_ etc, which makes it impractical for SC and would not provide much difference to `access=private` for regular customers - you'd have to know you have a permission beforehand to access in either case)

**Comment by mnalis** [comment]
> 2. **campsite category** (see legend on website)
>        * **group only campsites**
>          Tagging: [group_only=yes](https://wiki.openstreetmap.org/wiki/Key:group_only) or [scout=yes](https://wiki.openstreetmap.org/wiki/Key:scout) as a special case

While `scout=yes` does not seem to have wiki, `group_only=yes` seems to indicate there might be other restrictions (like church groups only probably would be restricted to groups of believers or church members or something?). It might also require pre-booking or reserving in advance? Or does it accept any random group of people that comes by, but refuses individual persons (e.g. _technically_ my girlfriend and myself count as group :smile:). 

I myself don't recall ever encountering such a camp which allowed only groups of campers (but there were separate problem of course - where we as 5-person group wouldn't be allowed in while a single camper might, due to amount of free space remaining).

So it IMHO does not seem as a good match for SC quest. Also, [taginfo for tourism=camp_site](https://taginfo.openstreetmap.org/tags/tourism=camp_site#combinations) does not mention `group_only=*` being used, which means that if it is used at all, it is used on less than `0.78%` of camp sites (which is last value listed). So it'd likely be too spammy.

**Comment by mnalis** [comment]
>   3. **contact information**
>      Some kind of contact information (centact:*, website or phone) should be available.

I agree those are extremely important for campsites, and to my experience practically always available. I've formerly been adding them usually via OsmAnd (or more recently EveryDoor).
StreetComplete ExpertEdition does allow entering [phone and website contact information](https://github.com/Helium314/StreetComplete/tree/modified/app/src/main/java/de/westnordost/streetcomplete/quests/contact) too. It is "probably" :smile:  too spammy for [general use on amenities as implemented there](https://github.com/Helium314/StreetComplete/blob/89022d292051f67f9eebc5bed515f790b5d9ce2f/app/src/main/java/de/westnordost/streetcomplete/quests/contact/AddContactPhone.kt#L47-L70), but _perhaps_ it might be acceptable for camp sites?

**Comment by mnalis** [comment]
>   4. **campsite features**
>      * openfire=yes (on backcountry campsites)

That one at least should be easy to add as a simple `yes/no` quest with easy selection on `nodes with tourism=camp_site and backcountry=yes`. 

It is however not listed as taginfo combination for [backcountry=yes](https://taginfo.openstreetmap.org/tags/backcountry=yes#combinations), but due to taginfo limitations it only tells us that it is used in less than `8.72%` cases there. So if it is close to that number, it might be eligible (or it might be too spammy or hard to know; I don't have much experience with `backcountry` camping _or_ `openfire` signage)

**Comment by mnalis** [comment]
>   4. **campsite features**
>        * toilets=yes

Not asked currently by StreetComplete, as possibly spammy (basically all non-backcountry camps I've seen have had toilets, even if only chemical ones; see https://github.com/streetcomplete/StreetComplete/issues/4198#issuecomment-1179793163. But that might be just my EU-standard privilege, I admit). 

Taginfo does not list `toilets=no` as a separate [combination for tourism=camp_site](https://taginfo.openstreetmap.org/tags/tourism=camp_site#combinations) which would suggest there is less than `0.78%` of  campsites with no toilets (or taginfo peculiarities, such as ignoring tags not used at least several thousand times).

More detailed checking with Overpass shows about 1500 [no-toilets campsites](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnHRvxKjEhW09Y2FtcF9zacSVICBhbsSXxYtpbGV0cz1uxKvFm8SXYmFja2PFjG50cnkhPXllc8WIwp0KKi8KW8WMdDpqc29uXVt0aW1lxb86MjVdOwovL8SPxJTEnXIgcsW2dWzFogooCsWZxpMgcXXEksSaxKNydCBmb3I6IMWIxYrFjMS3c8WPxZHFk8WVxZfEnsWnxJtvxZ_FocWjxaXFmsWcxJjFqsWsxa7FsMWyxbTFtsW4xqEgbndbIsWLxY3GtiI9Isa4xZTFlsSVIsaGx5TGv8WgxaLHmCLFpcefKHt7YsSqeH19KcaRx7HGksaUcMS3xa_Gmcabxp1zCsW_xJhvZHnGkT7Gkce-c2tlxL1xdDs&c=B32ysg8GRB) worldwide, about half of which are [not marked backcountry=yes](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnHRvxKjEhW09Y2FtcF9zacSVICBhbsSXxYtpbGV0cz1uxKvFm8SXYmFja2PFjG50cnkhPXllc8WIwp0KKi8KW8WMdDpqc29uXVt0aW1lxb86MjVdOwovL8SPxJTEnXIgcsW2dWzFogooCsWZxpMgcXXEksSaxKNydCBmb3I6IMWIxYrFjMS3c8WPxZHFk8WVxZfEnsWnxJtvxZ_FocWjxaXFmsWcxJjFqsWsxa7FsMWyxbTFtsW4xqEgbndbIsWLxY3GtiI9Isa4xZTFlsSVIsaGx5TGv8WgxaLHmCLFpcefx5PFqcWrxa11xa_FsSLFsyLFtXPHnyh7e2LEqnh9fSnGkce-xpLGlHDEt8WvxpnGm8adcwrFv8SYb2R5xpE-xpHIi3NrZcS9cXQ7&c=BeB16NllfC) - which is about `1.17%` places without toilets (of about 129k camp sites total)..

`1.17%` still sounds **_statistically_** spammy to me, but that is quite important feature so mapping it would be very useful. Especially as one does not really encounter many camps in a typical day, so it would probably never **_feel_** annoyingly spammy. What do others think? 

I would be open to doing PR for `camp toilets` quest if it would be found acceptable.

**Comment by matkoniecz** [comment]
nudism

> So that is about 6% positive and other 6% negative matches mapped, so it seems not to be spammy (contrary to my experience).

That is because people are far, far more likely to map positive values. Still, 6% positive seems really high?

[754 mapped with `nudism`](http://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20nw%5B%22tourism%22%3D%22camp_site%22%5D%5B%22nudism%22%5D(%7B%7Bbbox%7D%7D)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&C=84.40594;112.85156;1&R)

[307 mapped with nudism!=no](http://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20nw%5B%22tourism%22%3D%22camp_site%22%5D%5B%22nudism%22%5D%5Bnudism!%3Dno%5D(%7B%7Bbbox%7D%7D)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&C=84.40594;112.85156;1&R)

[128 742](https://taginfo.openstreetmap.org/tags/tourism=camp_site) in total

So it is rather [0.2%](https://duckduckgo.com/?t=ffab&q=307%2F128742&ia=calculator) with positive value, and [0.34%](https://duckduckgo.com/?t=ffab&q=(754-307)%2F128742&ia=calculator) with negative, with positive value used far more often if actually applying.

**Comment by matkoniecz** [comment]
> I would be open to doing PR for camp toilets quest if it would be found acceptable.

Maybe asking for backcountry ones without toilet being mapped nearby would be a good idea?

> That seems non-spammy, but I don't have much experience with backcountry camping or openfire signage to say if it is likely to easily signed / visible / understandable to random SC user.

And I turn have not seen ANY campsite without fireplace, so my feedback is limited to claim that it would be spammy in Poland. I guess that in more dry areas like Spain it is more likely?

**Comment by giggls** [comment]
> (key is actually named [nudism=*](https://wiki.openstreetmap.org/wiki/Key:nudism)). I guess it is quite useful if one is looking for exactly such place; but I don't recall seeing it signed on any camp (as opposed to, say, beaches, where I have).

Rationale about making this a category in OpenCampingMap was that people do not want to stumble upon such a site by mistake when looking for a place to stay.

**Comment by giggls** [comment]
> > I would be open to doing PR for camp toilets quest if it would be found acceptable.
> 
> Maybe asking for backcountry ones without toilet being mapped nearby would be a good idea?
> 
> > That seems non-spammy, but I don't have much experience with backcountry camping or openfire signage to say if it is likely to easily signed / visible / understandable to random SC user.
> 
> And I turn have not seen ANY campsite without fireplace, so my feedback is limited to claim that it would be spammy in Poland. I guess that in more dry areas like Spain it is more likely?

Most of the "EifeL" campsites do not have a fireplace.
https://opencampingmap.org/#10/50.4531/6.4984/0/0/40

**Comment by giggls** [comment]
> I myself don't recall ever encountering such a camp which allowed only groups of campers (but there were separate problem of course - where we as 5-person group wouldn't be allowed in while a single camper might, due to amount of free space remaining).

These are very common in Germany and are usually owned by municipalities. You are often required to stay for at least a week or so and there is a minimum daily fee which makes them basically group-only. Most common use are youth summer camps. I really feel that they should be tagged accordingly because I often stumbled upon them often when looking for a place to sty on a cycling trip.

**Comment by matkoniecz** [comment]
> Rationale about making this a category in OpenCampingMap was that people do not want to stumble upon such a site by mistake when looking for a place to stay.

It DEFINITELY makes sense to show it in OpenCampingMap. But it would make a poor SC quest.

**Comment by mnalis** [comment]
> That is because people are far, far more likely to map positive values. Still, 6% positive seems really high?

Ooops, sorry everyone, it seems that [I don't know how to count in overpass](https://help.openstreetmap.org/questions/36071/overpass-turbo-loaded-and-displayed-difference) when polygons are involved! :cry: 
thanks to @matkoniecz for spotting it; I've now gone over them and corrected Overpass counts.

**Comment by mnalis** [comment]
> Maybe asking for backcountry ones [...]

That part looks reasonable (and easy to do) to me

> [...] without toilet being mapped nearby would be a good idea?

for that however, I'd likely need some help (that is, if I were to do the quest). 
I currently have no idea how to check if something is nearby current element and exclude quest based on that.

<looking...>
Would [AddTactilePavingCrosswalk.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/AddTactilePavingCrosswalk.kt) be an good example for that?

**Comment by westnordost** [comment]
I think it is generally fine to ask for toilets for any campsite. There is already a "has toilet" quest, maybe just add campsites.

I am also thinking whether having those other campsite quests disabled is really necessary. Campsites are usually semi-public grounds, i.e. you do not really need to go "inside" anywhere to walk (through) there.

**Comment by matkoniecz** [comment]
Shop/restaurants/etc also are semi-public.

**Comment by mnalis** [comment]
> I am also thinking whether having those other campsite quests disabled is really necessary. Campsites are usually semi-public grounds, i.e. you do not really need to go "inside" anywhere to walk (through) there.

I've done PR https://github.com/streetcomplete/StreetComplete/pull/4331 if that is found acceptable. (if not, just reject/close it).
I can see it going both ways, although I'd love them to be available by default.

- on one side, camp grounds are _technically **outside**_, so one is not really _"going inside"_ when passing through them. Also, camping sites are few and wide apart, so it is not really too spammy if they are enabled by default even if users choose not to solve them.
- on the other side, _some_ of the campsites (small more private ones?) _might_ object to random people just walking through without visiting reception area, especially e.g. if they are on loaded bicycles so might be possible new campers. But just walking on foot might not be a problem in majority of cases as @westnordost notes, I guess.
