### ISSUE TITLE
Payment method debit_card / credit_card = yes inaccurate?

### ISSUE THREAD

**Issue by sekerob** [streetcomplete/StreetComplete#4201]
Osmose flags the use of payment:debit_cards=yes and payment:credit_cards=yes as inaccurate for as long as I've been mapping (2 years active) and religiously being replacing them with specifically named cards when a flag is encountered on the map. Now see a StreetComplete user doing the 'yes' tagging for these generic payment references. 

The English wiki makes no comment, but the German wiki says about these general payment methods to only be used when **NOT** accepted. i.e. the answer can only be payment:debit_cards/credit_cards=no when so found.

quote "Dieses Tag sollte hauptsächlich benutzt werden, wenn Kreditkarten **_nicht_** akzeptiert werden. Wenn Kreditkarten akzeptiert werden, bitte dies mit einem spezifischeren Schlüssel angeben.".

What's right, Osmose or StreetComplete?

**Comment by Helium314** [comment]
> What's right, Osmose or StreetComplete?

Osmose even flags names from NSI, so I wouldn't trust Osmose to be "right". Osmose is a great help for finding issues, but not an authority.

**Comment by sekerob** [comment]
Is the German wiki then wrong too, to tell the user to use the tag only for no?

**Comment by matkoniecz** [comment]
I am closing this as I consider it as an Osmose usability issue. 

debit_card / credit_card = yes can be made more accurate, but is not incorrect - and in many regions spending time to make it more accurate is likely better used to map other things.

**Comment by mnalis** [comment]
related: https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785 (and rest of the issue)
