### ISSUE TITLE
playground access

### ISSUE THREAD

**Issue by scoid** [streetcomplete/StreetComplete#4205]
Playgrounds may be marked "Access = yes". You will tell us, that it is public access, yes?

Although this ambiguity is unclear, playgrounds https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dplayground often state the maximum age of children who are allowed to use the place.

Here I would like to see a clearer definition, like maximum age of the user in years.

This is important because there is often a lack of playgrounds for older children in cities, most of them become boring after 6 years.

For demonstration purposes, I would like to show in "my" municipality how urgently places for older children are needed.

I would be pleased if you could record this age discrimination.  Thank you very much and best regards.

**Comment by matkoniecz** [comment]
> most of them become boring after 6 years

That is subjective and out of OSM scope. "maximum age of the user in years" is taggable but that is for cases where certain age range is not allowed to play.

> most of them become boring after 6 years

I guess that you can map individual structures and their properties with Vespucci
