### ISSUE TITLE
Sidewalk overlay shows discard input dialog even though nothing was changed

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#4206]
**How to Reproduce**
1. Enable sidewalk overlay
2. Click any overlay section with no sidewalk tagging (pink on both sides)
3. Discard the answer form immediately by tapping outside of the form
4. Dialog to discard inputs is shown even though no changes were made

**Expected Behavior**
Discard dialog isn't displayed if no changes were made

**Versions affected**
v45.0

Relevant code (?)
https://github.com/streetcomplete/StreetComplete/blob/7c97885cb6c24f9f7defed22e4497a495ab7e4ab/app/src/main/java/de/westnordost/streetcomplete/overlays/sidewalk/SidewalkOverlayForm.kt#L54-L55

**Comment by westnordost** [comment]
can reproduce
