### ISSUE TITLE
Extend building type and house number quests to work for nodes

### ISSUE THREAD

**Issue by Ajedi32** [streetcomplete/StreetComplete#4212]
### General
Affected tag(s) to be modified/added:

- [building](https://wiki.openstreetmap.org/wiki/Key:building)=*
- [addr:housenumber](https://wiki.openstreetmap.org/wiki/Key:addr:housenumber)=*
- [addr:housename](https://wiki.openstreetmap.org/wiki/Key:addr:housename)=* or [nohousenumber](https://wiki.openstreetmap.org/wiki/Key:nohousenumber)=*
- [addr:conscriptionnumber](https://wiki.openstreetmap.org/wiki/Key:addr:conscriptionnumber)=*
- [addr:streetnumber](https://wiki.openstreetmap.org/wiki/Key:addr:streetnumber)=*
- [addr:block_number](https://wiki.openstreetmap.org/wiki/Key:addr:block_number)=*

Questions asked:

- What kind of building is this?
- What’s the house number of this building?

These quests already exist for ways and relations (even though relations [can't have the building tag?](https://wiki.openstreetmap.org/wiki/Key:building)), but do not show up when the building in question is mapped as a node. Mapping buildings as nodes is allowed, according to the wiki entry for [building](https://wiki.openstreetmap.org/wiki/Key:building)=*.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

Since this quest already exists for ways and relations, I think the above conditions have already been proven for most part.

Points may be slightly harder for surveyors to reliably identify than buildings with an already known shape, but not much harder than for any of the other quests that apply to nodes.

Not sure how many buildings are currently mapped as points, but [the wiki says it is allowed](https://wiki.openstreetmap.org/wiki/Key:building), and implementation effort here seems pretty minimal.

### Ideas for implementation

**Element selection:** Add `nodes` to https://github.com/streetcomplete/StreetComplete/blob/86a4b39b54a5bba426cf2ca6971672ed2dd08dd9/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L202 and https://github.com/streetcomplete/StreetComplete/blob/86a4b39b54a5bba426cf2ca6971672ed2dd08dd9/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L15

Assuming I'm understanding the code right, the "What street is this on?" quest already works with nodes and does not need to be modified.

**Metadata needed:** Not sure what this means.

**Proposed UI:** No UI changes necessary, I think?

**Comment by Ajedi32** [comment]
Ah, didn't see those. 

That's really unfortunate. I think address locations are likely to be way more valuable for most OSM users than knowing the exact footprint of every building, and requiring a building to be traced before you can attach an address to it introduces a significant barrier to contributing that information.

**Comment by arrival-spring** [comment]
> even though relations can't have the building tag?

My understanding is that the relation icon on the wiki refers to relations other than multipolygons. There shouldn't be any buildings mapped as relations other than those

**Comment by Ajedi32** [comment]
That's fair I guess, though I personally feel like I'd have little trouble identifying the building by its position relative to my GPS location.

Perhaps we can revisit this if Street Complete ever gets an option for overlaying aerial imagery.

**Comment by mnalis** [comment]
> Perhaps we can revisit this if Street Complete ever gets an option for overlaying aerial imagery.

- related: https://github.com/streetcomplete/StreetComplete/issues/56
