### ISSUE TITLE
Shoulder quest and oneway roads

### ISSUE THREAD

**Issue by salsifis** [streetcomplete/StreetComplete#4214]
The shoulder quest asks for the presence of a shoulder on both sides of the road for oneway roads. Here is an example. 

![Screenshot_20220715_070128_de westnordost streetcomplete](https://user-images.githubusercontent.com/1233345/179154196-5da7c1f2-1e19-486a-9ece-d59eab78ee27.jpg)

Shoulders on the left are very uncommon in right hand traffic countries, as well as right-hand shoulders in left-hand traffic countries. 

**Expected Behavior**
As for the lanes quest, the reverse direction is not proposed on oneway roads (or necessitates an option in menu)

**Versions affected**
v45. 0

**Comment by westnordost** [comment]
The existence of a shoulder **for both sides** is recorded in just **one** tag in OpenStreetMap: `shoulder=both/left/right/no`. Hence, always both sides need to be specified as per limitation of the tag of OpenStreetMap.
