### ISSUE TITLE
`maxweight` not showing more than one digit

### ISSUE THREAD

**Issue by crosspolar** [streetcomplete/StreetComplete#4216]
I found myself not able to enter "22t" when being asked for `maxweight` of bridge. Maybe the weight is unusual, but it seems that the ~~integer value is limited to 10 tons~~ (EDIT:) value for tons don't show more than one digit, see video below. ~~Is this a bug or a feature?~~
![IMG_20220709_191607](https://user-images.githubusercontent.com/18083323/179343281-ef8abd93-efe3-4533-a61a-a201b4c732e2.jpg)

**Comment by matkoniecz** [comment]
What happens when you confirm that you want to add it despite value being unusual?

**Comment by crosspolar** [comment]
How do you do that? 
https://user-images.githubusercontent.com/18083323/179346466-5a737f96-6ed0-43f6-b82d-254ea22a3bd6.mp4

**Comment by matkoniecz** [comment]
You click big orange button with tick marker on bottom right and confirm that you are sure.

Though another bug IS visible: entire weight limit, not just last number, should be visible.

**Comment by crosspolar** [comment]
Ok, then I had a misunderstanding with the app because I thought it is not possible to enter 22 tons but it is just not shown. I changed the issue's title
