### ISSUE TITLE
Don't ask entrance quest on railway=subway_entrance

### ISSUE THREAD

**Issue by Nielkrokodil** [streetcomplete/StreetComplete#4217]
I was asked which kind of entrance is this on a railway=subway_entrance node. In my opinion the current tagging is enough, there should be no entrance=* key added. 

The Question text is also strange, because it asks you what kind of entrance is it (German: Was für eine Art von Gebäudeeingang ist das?) and below in italics it answers it by describing the objects as subway entrance (German: U-Bahn-Eingang)

**How to Reproduce**

I found it at this node
https://www.openstreetmap.org/node/3737593755

**Expected Behavior**

Don't ask the entrance quest for this node. 

**Versions affected**

v45.0

**Comment by matkoniecz** [comment]
Thanks for reporting! Maybe only solely nodes without tags should be selected
