### ISSUE TITLE
Name quest on amenity=biergarten: Add option "This is no biergarten, it is outdoor seating"

### ISSUE THREAD

**Issue by Nielkrokodil** [streetcomplete/StreetComplete#4218]
**Use case**

In my area (Austria, Europe) many Restaurants have tables to eat and drink outside, but you are just allowed to use it when you eat and drink the restaurant's food. This should be tagged with leisure=outdoor_seating.
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Doutdoor_seating

Many of those objects are mapped wrongly with amenity=biergarten. In a biergarten you are allowed to eat your own food. 
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbiergarten

I believe many mappers are not aware of this mistagging, because the Bavarian Biergarten concept (which led to amenity-biergarten) is not commonly known around here (even if we are the neighboured country with the same language). 

**Proposed Solution**

When I am asked "What is the name of this Biergarten?" I would like to get an option to tell "This is no biergarten. It is (a restaurant's) outdoor seating." Outdoor Seatings usually have no name.

**Comment by matkoniecz** [comment]
For now I would create notes or edit with Vespucci - special answers are created where something is a general (not only local problem), is easy to explain and risk of mistakes is low.

**Comment by westnordost** [comment]
Yes, you should leave a note in that case
