### ISSUE TITLE
[Feature Request] Quest for Translating street names

### ISSUE THREAD

**Issue by molaeiali** [streetcomplete/StreetComplete#4220]
**Use case**
Adding translation for street names

**Proposed Solution**
I may choose a preferred  language in the menus, and if streets around me have not that language's name, I get a quest to add a translation for them (or maybe edit them if they are auto generated)

**Comment by riQQ** [comment]
Related #3411

**Comment by westnordost** [comment]
Translations? What do you mean? Which country do you have in mind?

**Comment by molaeiali** [comment]
As you can see on the OpenStreetMap website when you edit a route you can add Multilingual names for the streets in different languages, for example here we have 'English' and 'Persian' written names.

![Screenshot from 2022-07-17 22-17-13](https://user-images.githubusercontent.com/12999682/179418286-a382e92b-237b-4cfb-86d9-d3ea7596915b.png)

Even in StreetComplete right now we have the option to add Persian (fa) and English (en) names, but only for streets that are not named at all.
![Screenshot_20220717-221857_StreetComplete](https://user-images.githubusercontent.com/12999682/179418476-6b69f608-f62f-4104-81d1-4c4dffdcfafc.jpg)
![Screenshot_20220717-221907_StreetComplete](https://user-images.githubusercontent.com/12999682/179418480-40d3fc3a-5a90-4164-9a89-38e73693b232.jpg)

These will be used in applications like OSMAnd (You can change the map language) and MAPS.ME (Shows both local and en): 
![Screenshot_20220717-222530_OsmAnd~](https://user-images.githubusercontent.com/12999682/179418628-d46c031e-c93e-4c6a-a4c7-7e535f1cb7f3.jpg)
![Screenshot_20220717-222614_MAPSME](https://user-images.githubusercontent.com/12999682/179418665-2e0301ca-c5be-4024-9736-68f3bd2d4b9d.jpg)

The problem is that there is no way for adding them with ease in any editor. Hope I clarified my point.

**Comment by molaeiali** [comment]
> Translations? What do you mean? Which country do you have in mind?

Currently the usecase for me to use 'English' translations, is that the OSMAnd TextToSpeech reads street names in English very well, but will not read them in Persian at all. so I want to add as much English names for streets around me as possible. but there is no easy wizardy way for me to do this. I think StreetComplete approach to getting data from user is quite useful for this issue

**Comment by westnordost** [comment]
Are English/International names commonly shown on Persian street signs?

**Comment by molaeiali** [comment]
Yes there are

**Comment by letypequividelespoubelles** [comment]
Wouldn't this type of quest perfect for a new layer ?

**Comment by westnordost** [comment]
Do you have some example photos how that looks like on the street sign? Most importantly, are they translations into English or romanizations? "Flower Street" or "Khaaban Gul"?

**Comment by westnordost** [comment]
Actually, I noticed, you already have the option to supply an English/International version of the Persian street sign: Tap on the [+] button below "fa".

**Comment by westnordost** [comment]
Oh nevermind, you realized that already, but you want a way to edit the name. Yeah, @letypequividelespoubelles , maybe this could be an overlay.  But it could not a quest (see related #3411)

**Comment by molaeiali** [comment]
> Do you have some example photos how that looks like on the street sign? Most importantly, are they translations into English or romanizations? "Flower Street" or "Khaaban Gul"?

Sorry for using the term "translate", It's not a translation, it's romanization. "گل‌ها" -> "Gol ha", not "Flowers"

> Actually, I noticed, you already have the option to supply an English/International version of the Persian street sign: Tap on the [+] button below "fa".

Yes, but it's only for the streets without any name, if they only have the local name. you cannot add en to them, would be nice to be able to add it for the ones with only local names, nevermind editing the ones with 'en' already.

> Oh nevermind, you realized that already, but you want a way to edit the name. Yeah, @letypequividelespoubelles , maybe this could be an overlay. But it could not a quest (see related https://github.com/streetcomplete/StreetComplete/issues/3411)

I don't understand what an overlay is (maybe I'm a noob in StreetComplete) but the feature I'm asking is just like adding names to streets without names, It's adding 'en' name to streets without 'en' label (If editing is not possible)

**Comment by westnordost** [comment]
Oberlays are a new feature since v45, check the changelog
