### ISSUE TITLE
Inconsistent multi-polygon/relation quest behaviour

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#4223]
Take this multi-polygon relation for two buildings comprising one fast food operation (maybe in this particular case they should be two separate areas, but the point still stands):
https://www.openstreetmap.org/relation/11367803

I was able to add cards and roofs, but e.g. vegetarian and seating don't allow relations.

The payment tag actually says no relations:
https://wiki.openstreetmap.org/w/index.php?title=Key:payment

But it was added to SC in:
https://github.com/streetcomplete/StreetComplete/commit/d0fdc4401c23acb4303ac3c9d64596f5ffb63834

**How to Reproduce**
Try and answer the other quests and they don't appear.

**Expected Behavior**
Should be able to answer all appropriate quests or none!

**Versions affected**
SC 45.0

**Comment by matkoniecz** [comment]
> The payment tag actually says no relations:

note that it has also info that it is used on ares - what covers multipolygons

**Comment by peternewman** [comment]
Ah yeah, I completely missed that! :facepalm: 

Pedantically I don't see any filtering for other relations (e.g. if someone made a relation for all the McDonald’s stores, but perhaps that's generally unlikely?

**Comment by matkoniecz** [comment]
> if someone made a relation for all the McDonald’s stores

Then it should be deleted - see https://wiki.openstreetmap.org/wiki/Relations/Relations_are_not_Categories

**Comment by HolgerJeromin** [comment]
I am pretty sure StreetComplete filters relations with `type=multipolygon` for such quests (or at least should :-)
https://wiki.openstreetmap.org/wiki/Relation:site
is kind of popular and
https://wiki.openstreetmap.org/wiki/Tag:type=public_transport
really useful.

**Comment by westnordost** [comment]
I agree.

**Comment by westnordost** [comment]
So? You assigned it to yourself.

**Comment by peternewman** [comment]
> I propose to not process relations, possibly with exception of `amenity=place_of_worship` and `amenity=parking` where many validly marked objects will have it.

For reference see also campsites:
https://www.openstreetmap.org/relation/11246454

And I'd imagine farms would be similarly impacted. Probably things like school playing fields too, or other stuff that can be bisected by public roads.
