### ISSUE TITLE
Connect photo to osm_id not only note

### ISSUE THREAD

**Issue by fganzFR** [streetcomplete/StreetComplete#4224]
**Use case**
When i update quality of road (smoothness) like a défault (like crack) it woul be usefull to link a picture to this osm_id

**Proposed Solution**
When the quest il proposed to modify the attribute smoothness after the answer
- take the photo
- upload the photo
- store the photo
- link the photo to osm_id
-->

**Comment by JLZIMMERMANN** [comment]
Couldn't it be possible to take picture from StreetComplete letting use of some picture app like Flickr such like Openfirehydrant does ?

**Comment by FloEdelmann** [comment]
@JLZIMMERMANN Different feature request, see https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Can_I_choose_photos_from_the_gallery_for_uploading_to_notes.2C_instead_of_using_camera.3F

**Comment by matkoniecz** [comment]
https://github.com/Discostu36/OSM-Photos  may be of interest to people interested in such functionality

> GitHub user Discostu36 is currently [gathering](https://github.com/Discostu36/OSM-Photos) feedback for a ‘photo uploader for Wikimedia Commons’ which directly links newly surveyed images to an OSM POI after uploading it to Wikimedia Commons. The project aims to ease the contribution of new images to already existing OSM objects. It is currently still in a pre-development stage, but you can find it on GitHub and provide feedback or track progress.
