### ISSUE TITLE
NL: Fire hydrant form is confusing

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#4226]
I recently travelled to NL and was questioned about fire hydrants (brandkraan) diameters. A good example (not mine) is here:
https://commons.wikimedia.org/wiki/File:Positieaanduiding_afsluiters_brandkraan.png
For me, this reads as: 10.0. However, I could not enter neither a dot nor a comma. So I entered the value without comma and Streetcomplete said that the value was untypical (or similar) and required me to confirm.

I tried to research what these values mean, but I could not find the answer (with limited search capabilities on the phone); neither the DE nor NL wikipedia (but I don't speak Netherlands) gave me an answer. 

I see three options:
1.  The comma is correct, then this is an UI issue in SC
2.  There is no comma, then the logic for checking values is not working as expected
3. I entered incorrect values (this might be possible, though I'm rather confident I did not) then the warning is not helpful (enough)

For 3., it would be good if the warning box provided the expected constraints (e.g. "The value is usually between 80 … 120"). 

As I cannot completely rule out 3. - is there an (easy) way to review and possibly undo my entries for fire hydrants (not the other ones!!!) in NL?

**How to Reproduce**
Locate a place where a fire hydrant diameter quest is asked in NL. Enter values like 10.0.

**Expected Behavior**
Either
1. Accept the value with comma if this is correct in NL
2. Review the range logic for answers in NL if the comma is incorrect
3. If values are "out of expected range" print the expected range so the user knows that maybe he mistyped and can look at the sign again.

**Versions affected**
Android: 10
SC: v45.0

**Comment by FloEdelmann** [comment]
It is actually option number 3: The sign says "Ø 100", and the comma is not part of that number. It seems like the commas are always there for both sides, but the large number (which indicates how many meters you need to go in that direction to find the hydrant) is only there on one side. The diameter is then put into that empty space.

The sign in Germany looks similar, but puts the number above the "T" lines, so it's not possible to confuse the numbers there.

**Comment by westnordost** [comment]
This is how the form should look in the Netherlands

![image](https://user-images.githubusercontent.com/4661658/180173728-b2d9a42e-ddd6-4b79-9bbc-a2e92babbc60.png)

**Comment by westnordost** [comment]
I do not see any solution that would actually reduce confusion.

Trying to make the sign look closer to the original is not possible, because the ⌀ is sometimes on the left side and sometimes on the right side of the vertical white line.

Displaying the comma on the form below the actual input because it is this way on the sign will I think contribute as much to confusion for some people as leaving it away for other people.

**Comment by peternewman** [comment]
I think this bit would reduce confusion, you'd look again at the sign and be confident to ignore the comma if people had been confused by it.

> For 3., it would be good if the warning box provided the expected constraints (e.g. "The value is usually between 80 … 120").

It probably wouldn't hurt to have similar for the speed/height/weight quests too.

**Comment by westnordost** [comment]
What bit?

**Comment by peternewman** [comment]
The bit I quoted directly below, having the "warning box provided the expected constraints (e.g. "The value is usually between 80 … 120")."

**Comment by riQQ** [comment]
Maybe also give a hint in the warning dialog that the diameter on the sign is specified without comma.

**Comment by hmartink** [comment]
Yes, the suggestions by peternewman and riQQ are great.
