### ISSUE TITLE
Does an amenity accept cryptocurrencies for payment?

### ISSUE THREAD

**Issue by monsterbitar** [streetcomplete/StreetComplete#4228]
### General
Affected tag(s) to be modified/added: payment
Question asked: **Are Bitcoin (BTC) or Bitcoin Cash (BCH) accepted here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [-] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [-] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Same as for accept credit/debit card.

I made a copy of the credit/debit acceptance files and edited as best I could here, to help things get started. I also tried to but couldn't get gradle to work to compile so I could test locally before making this issue.

I'd be more than happy if this could be included and disabled by default for now (since it doesn't match all requirements above), and individual users who are interested in updating this specific data for their locations can enable it manually.

```
package de.westnordost.streetcomplete.quests.accepts_crypto

import de.westnordost.streetcomplete.R
import de.westnordost.streetcomplete.data.osm.mapdata.Element
import de.westnordost.streetcomplete.data.osm.mapdata.MapDataWithGeometry
import de.westnordost.streetcomplete.data.osm.mapdata.filter
import de.westnordost.streetcomplete.data.osm.osmquests.OsmFilterQuestType
import de.westnordost.streetcomplete.data.user.achievements.EditTypeAchievement.CITIZEN
import de.westnordost.streetcomplete.osm.IS_SHOP_OR_DISUSED_SHOP_EXPRESSION
import de.westnordost.streetcomplete.osm.Tags
import de.westnordost.streetcomplete.util.ktx.toYesNo

class AddAcceptsCrypto : OsmFilterQuestType<CryptoAcceptance>() {

    override val elementFilter = """
        nodes, ways, relations with (
          amenity ~ restaurant|cafe|fast_food|ice_cream|food_court|pub|bar
          or (shop and shop !~ no|vacant|mall)
        )
        and (!payment:bitcoin or !payment:bitcoincash)
        and !brand and !wikipedia:brand and !wikidata:brand
        and (!seasonal or seasonal = no)
    """
    override val changesetComment = "Survey whether payment with cryptocurrencies is accepted"
    override val defaultDisabledMessage = R.string.default_disabled_msg_go_inside
    override val wikiLink = "Key:payment"
    override val icon = R.drawable.ic_quest_card
    override val isReplaceShopEnabled = true
    override val achievements = listOf(CITIZEN)

    override fun getTitle(tags: Map<String, String>) = R.string.quest_accepts_cards

    override fun getHighlightedElements(element: Element, getMapData: () -> MapDataWithGeometry) =
        getMapData().filter(IS_SHOP_OR_DISUSED_SHOP_EXPRESSION)

    override fun createForm() = AddAcceptsCryptoForm()

    override fun applyAnswerTo(answer: CryptoAcceptance, tags: Tags, timestampEdited: Long) {
        tags["payment:bitcoin"] = answer.bitcoin.toYesNo()
        tags["payment:bitcoincash"] = answer.bitcoinCash.toYesNo()
    }
}
```

```
package de.westnordost.streetcomplete.quests.accepts_crypto

import de.westnordost.streetcomplete.R
import de.westnordost.streetcomplete.quests.AListQuestForm
import de.westnordost.streetcomplete.quests.TextItem
import de.westnordost.streetcomplete.quests.accepts_crypto.CryptoAcceptance.BITCOIN_ONLY
import de.westnordost.streetcomplete.quests.accepts_crypto.CryptoAcceptance.BITCOIN_AND_BITCOIN_CASH
import de.westnordost.streetcomplete.quests.accepts_crypto.CryptoAcceptance.BITCOIN_CASH_ONLY
import de.westnordost.streetcomplete.quests.accepts_crypto.CryptoAcceptance.NEITHER_BITCOIN_NOR_BITCOINCASH

class AddAcceptsCryptoForm : AListQuestForm<CryptoAcceptance>() {

    override val items = listOf(
        TextItem(NEITHER_BITCOIN_NOR_BITCOINCASH, R.string.quest_accepts_crypto_unavailable),
        TextItem(BITCOIN_ONLY, R.string.quest_accepts_crypto_bitcoin_only),
        TextItem(BITCOIN_CASH_ONLY, R.string.quest_accepts_crypto_bitcoin_cash_only),
        TextItem(BITCOIN_AND_BITCOIN_CASH, R.string.quest_accepts_crypto_bitcoin_and_bitcoin_cash),
    )
}
```

```
package de.westnordost.streetcomplete.quests.accepts_crypto

enum class CryptoAcceptance(val bitcoin: Boolean, val bitcoinCash: Boolean) {
    BITCOIN_AND_BITCOIN_CASH(true, true),
    BITCOIN_ONLY(false, true),
    BITCOIN_CASH_ONLY(true, false),
    NEITHER_BITCOIN_NOR_BITCOINCASH(false, false),
}
```

Strings:
```
    <string name="quest_accepts_crypto">Are Bitcoin (BTC) or Bitcoin Cash (BCH) accepted here?</string>
    <string name="quest_accepts_crypto_bitcoin_and_bitcoin_cash">Both Bitcoin and Bitcoin Cash</string>
    <string name="quest_accepts_crypto_bitcoin_only">Only Bitcoin</string>
    <string name="quest_accepts_crypto_bitcoin_cash_only">Only Bitcoin Cash</string>
    <string name="quest_accepts_crypto_unavailable">Neither Bitcoin nor Bitcoin Cash</string>
```

**Comment by westnordost** [comment]
It does not fulfill:

> 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
> 💤 Not an overwhelming percentage of quests have the same answer (No spam)

There are more issues with this, such as not being atomic, but the above (especially the no spam rule) is already a K.O. criterium, sorry.

**Comment by monsterbitar** [comment]
I see. To be clear, the card acceptance quest has the same situation, which is why I thought this would be worth a try.

Publicly accessible on foot: There's tons of places with "Bitcoin accepted here" stickers on their windows, the same way "VISA accepted here".

No spam: Almost all places would be clear no, the same way for most of the modern world they would be clear yes for card acceptance.

I had no intention of making this default-enabled and ask people in places where it's not relevant to do meaningless work, my goal was to make it an optional quest that people can enable if it makes sense to them.

Information on cryptocurrency acceptance have been in OSM since at least 2014, and there's multiple visualization tools out there since people are looking for this information.

**Comment by mnalis** [comment]
@monsterbitar Note that the cash/card quest do have dozens of thousands of usages, and do have some reasonable variation in them according to taginfo - from [7%](https://taginfo.openstreetmap.org/keys/payment%3Acash#values) - [15%](https://taginfo.openstreetmap.org/keys/payment%3Adebit_cards#values) of "no" values. 

Your particular country might differ, of course. If in your country some quest is too spammy (e.g. 99%+ of the same value) you can/should request that particular quest to be [excluded in some countries](https://github.com/streetcomplete/StreetComplete/blob/v45.1/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt#L57).

- [payment:bitcoincash](https://taginfo.openstreetmap.org/keys/payment:bitcoincash#values) seems to fails that spamminess check (less than `1000` uses, with `99.79%` being `yes`)
- however, [payment:bitcoin](https://taginfo.openstreetmap.org/keys/payment:bitcoin#values) is more reasonable: `~7400` uses, with `3.65%` being `no`. However based on guesswork, if all shop nodes were to get that `payment:bitcoin=*` tag, I assume `no` value would explode.


Possible workarounds for your problem: when asked whether shop accepts cards, choose `Leave a note` other answer, and name all payment methods (and/or take a picture). Then you (or some other interested mapper) later can use some other [OSM Editor](https://wiki.openstreetmap.org/wiki/Editors) to the map. 
  This is available right now to everyone, but with obvious disadvantage that it requires doing work twice.

**Comment by mnalis** [comment]
But perhaps  `accept_cards` quest could be modified to have an **Other Answer** of `In addition of cash+debit+credit cards, it also accepts crypto` which would set `payment:debit_cards=yes` + `payment:credit_cards` + [payment:cryptocurrencies=yes](https://wiki.openstreetmap.org/wiki/Key:payment#Cryptocurrencies)?

This perhaps might be considered as it would not be intrusive to current users, and if accepted, allows the possibility of followup-up quest (which triggers only on `payment:cryptocurrencies=yes`) could be implemented in similar vein as [more detailed card information idea](https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785).

Although `Other Answer` is not _perfect_ either (e.g. there exist some crypto-only etc. shops which would still require leaving Notes, but they should be rare enough), I would prefer this solution (and could do the PRs) if @westnordost would accept such solution (or something similar)?

**Comment by matkoniecz** [comment]
> I see. To be clear, the card acceptance quest has the same situation, which is why I thought this would be worth a try.

If there is any country at all where `=yes` answer to cryptocurrency would be higher than `=no` answer to credit card acceptance, then let us know.

Also, if there is some country where credit card acceptance is at 99%+ ratio then it may make sense to disable this quest there (though if it is disabled by default it may be OK to leave it if users tend to enable it just to mark specific location as not serving CC).

> But perhaps accept_cards quest could be modified to have an Other Answer of In addition of cash+debit+credit cards, it also accepts crypto

Is cryptocurrency treated as special variant of credit cards? (honestly, no idea - as in places where I was no cryptocurrency is accepted by any retail)

**Comment by mnalis** [comment]
> Is cryptocurrency treated as special variant of credit cards? (honestly, no idea - as in places where I was no cryptocurrency is accepted by any retail)
 
It works mostly similarly to credit card processing: 
- you indicate how you would like to pay (credit card / debit card / cash / cryptoXXX )
- you are presented with sum to pay on sellers display
- you exchange the information with the POS device ("card reader") at seller:
  -  QR code scan or NFC touch with mobile phone for **crypto** 
  - physical card NFC touch or physical card chip insertion or mobilephone NFC touch in case of physical/virtual **credit card**, 
- you confirm the transaction:
  -  PIN on **credit card** 
  -  PIN or fingerprint on mobile phone in case of **virtual credit card** 
  -  PIN or fingerprint on mobile phone in case of **crypto**

**Comment by matkoniecz** [comment]
But would reaction to "Are credit or debit cards accepted here?" be "I cannot answer it as they accept cryptocurrency cards"?

**Comment by mnalis** [comment]
I don't quite understand your question?
e.g. _Would a reaction to "Are credit or debit cards accepted here?" be "I cannot answer it as they accept **cash**"?_


- if there are **only credit/debit cards** accepted, I would guess user would just choose one of the offered 4 answers.
- if **both** credit and debit cards are accepted **as well as crypto**, there are few possible outcomes:
  - user does not know (or care) about crypto and only answers about credit/debit cards (same situation as now)
  - user notices shop also accepts crypto, looks in Other Answers and notices cards+crypto option, and chooses that (proposed improvement) instead of leaving note (which is current option)
- if **only crypto** is accepted (but not cash nor credit/debit cards) user would leave a note (as they would currently)

So IMHO compared to current SC, proposed OtherAnswer would only improve data entered, without unduly confusing users. 
But it would only solve **_majority_** of crypto issues, **not** all 100% of them (as some users would not care, or might miss that there is Other Answer)

**Comment by matkoniecz** [comment]
> Would a reaction to "Are credit or debit cards accepted here?" be "I cannot answer it as they accept cash"?

no, and that is why "In addition of cash+debit+credit cards, it also accepts cash" in "Other answers" section is not needed.

> instead of leaving note (which is current option)

are such notes actually appearing? I am looking from time to time at SC-produced notes and I do not remember anything cryptocurrency related ever appearing

**Comment by mnalis** [comment]
> no, and that is why "In addition of debit+credit cards, it also accepts cash" in "Other answers" section is not needed.

`cash` is not needed there as there exists **_separate_** `accept_cash` quest (only enabled in SE). Unfortunately, as crypto is not so geographically confined as `no cash`, it is not a good match as a disabled-in-some-country quest, and is too spammy otherwise to be regular available-everywhere quest (even if disabled by default), as noted by powers-that-be.

And as crypto is probably not (yet) popular enough to warrant full citizen rights (i.e. expand `accept_cards` to all 2<sup>3</sup>=8 answers instead of current 4, or convert it to multi-selection quest like recycling or [detailed payment type idea](https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785)), I suggested Other Answer as an (IMHO reasonably easy and non intrusive) way to allow to implement that somewhat rare but still non-insignificant answer.

> are such notes actually appearing? I am looking from time to time at SC-produced notes and I do not remember anything cryptocurrency related ever appearing

I have not looked in detail, but quick grep finds more than a thousand of them:
> % bzcat planet-notes-latest.osn.bz2 | ag '\b(bitcoin|btc\b|ethereum|eth\b|crypto)'   | wc -l
> 1136

**Comment by matkoniecz** [comment]
> quick grep finds more than a thousand of them

This is not limiting to StreetComplete notes produced on encountering this quest

**Comment by mnalis** [comment]
> This is not limiting to StreetComplete notes produced on encountering this quest

(yeah, I updated that comment before you answered - I cannot easily search for that anymore :cry:)

**Comment by mnalis** [comment]
There are surely some like https://www.openstreetmap.org/note/2880461 but manually searching for all of them one by one would be too much, so I'd hope the search [bug](https://github.com/ENT8R/NotesReview/issues/78#issuecomment-1186167223) gets fixed

**Comment by monsterbitar** [comment]
I don't think there are any places today where the number of merchants accepting any cryptocurrency is higher than the number of merchants not accepting cryptocurrencies. However, there are hot-spots around the world (like Townsville, Australia) where there are 5% ~ 15% or so merchant acceptance for a cryptocurrency.

From my perspective, even in such places it wouldn't make sense to have a default-enabled quest for this data.

However, for a certain set of individuals that care about this data it would be good to have a quest that can be enabled when those users want it. For example, in Townsville mentioned above, there are about 200 bitcoin cash accepting merchants, of which less than half is entered into openstreetmap.

For comparison, you can compare https://map.bitcoin.com/ (170 entries, private database) and https://where2.cash/ (84 entries. from OSM).

**Comment by mnalis** [comment]
Also related idea of mapping multiple currencies: https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785
