### ISSUE TITLE
Cycleway overlay

### ISSUE THREAD

**Issue by Rudloff** [streetcomplete/StreetComplete#4233]
**Use case**

It would be useful to have a way to see which ways lack `cycleway` tags in a given area.
For example, this could be used by cyclist groups mapping their neighborhood.

**Proposed Solution**

A new overlay could be created, similar to the sidewalk overlay.
Ways that don't have any cycle-way information would be displayed in red.

**Comment by arrival-spring** [comment]
I believe that this is on the cards, I guess the main question is a colour scheme to represent all of the possibilities.

**Comment by legofahrrad** [comment]
Would it be possible to show the cycleway illustrations on the roads, as it is in the quest form?

**Comment by arrival-spring** [comment]
Not with the current implementation, at the moment the things that can be set are the centre colour, the colour for each side and text to display on the way.

**Comment by NotSoImportant** [comment]
Very much like and want to use this ❤️ 

Suggestion for coloring:
- use the same as for side walk overlay (on both sides, yes=blue, no=nothing, not mapped=red)
- color any of the values supported by streetcomplete as "yes"
- on selection show detailed value (and be able to change with existing dialog) 

Additionially possible:
- highlight cycle roads with coloring the road center
- highlight cycle networks (relations) with coloring the road center
- highlight other bicycle infrastructure (like parking or shop), e.g. with colored rectangle like for parking overlay or with rendering their icons

**Comment by westnordost** [comment]
I'll implement this (properly) soon, don't worry

**Comment by westnordost** [comment]
Most probably it will remain but be disabled by default, just like with the sidewalks

**Comment by westnordost** [comment]
Implemented via #4657
