### ISSUE TITLE
sidewalk surface gets removed by StreetComplete 

### ISSUE THREAD

**Issue by scaidermern** [streetcomplete/StreetComplete#4235]
Answering the question whether roads have sidewalks removes the `sidewalk:left:surface` / `sidewalk:right:surface` tag:

![foo](https://user-images.githubusercontent.com/1040784/180717003-e6902079-b9f8-4500-a5a9-7e6c95b3cc7d.png)

https://www.openstreetmap.org/changeset/123944661

**Comment by legofahrrad** [comment]
See #4123, it is intentionally, not a bug.

**Comment by matkoniecz** [comment]
but in this case it is a bug as tags were changed but their meaning not, so `sidewalk:left:surface` should stay

**Comment by scaidermern** [comment]
Indeed. The previous tagging was correct, so the new tagging shouldn't remove this tag.

**Comment by arrival-spring** [comment]
I don't think the previous tagging was really correct, it was a mixture of the two types of sidewalk tagging.
`sidewalk=left` means sidewalk on the left only, so to mix this with `sidewalk:right=*` is wrong, I think.

The sidewalk quest is only asked on ways with sidewalk tagging where that tagging is incomplete (e.g. `sidewalk:right` without `sidewalk:left`) or invalid (e.g. both `sidewalk` and `sidewalk:right` or some unknown value for one of the tags).

**Comment by westnordost** [comment]
See @arrival-spring 

StreetComplete flagged this street as having conflicting (= invalid) tagging. The answer supplied (=_left sidewalk, right separately mapped sidewalk_) differed from the previously tagged state (=_invalid_), hence, the sidewalk surface information was removed.

The code for applying the tags is at [Sidewalk.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/sidewalk/Sidewalk.kt#L39-L70), the code for parsing the current sidewalk is in the same directory.
The tests for the behavior (i.e. documentation/examples) are likewise at [SidewalkKtTest.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/osm/sidewalk/SidewalkKtTest.kt) and in the same directory.
