### ISSUE TITLE
The red cross is not centered in the history

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4236]
In history of answer if you have answer this object doesn't exists, the red cross on icons is not centered.

**How to Reproduce**

- Click on any quest (with object which can be remove on OSM)
- Select others answers.. -> It does not exist
- Click on arrow at the left bottom
- Cross on object delete is not centered
<img src="https://user-images.githubusercontent.com/87148630/180800314-df884268-67be-4da9-963a-8f8729ba506a.png" width="300">

**Expected Behavior**
- Center red across on history

**Versions affected**
v45.1

**Comment by matkoniecz** [comment]
Why it would be a bug?

**Comment by westnordost** [comment]
Yes, this deliberate.
