### ISSUE TITLE
Slow GPS fix in SC while GMaps works fine.

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4238]
After opening the SC app there's a massive delay, like 2-4 minutes until a precise location is acquired. 

Doing a start of GMaps doesn't help StreetComplete, Mapy.cz, etc. to get a faster fix. 

While GMaps get an instant GPS fix 🤔

Not sure if that's related, but I think the issues started with the Android 12 and its precise/unprecise location modes per app. 

That said Google Maps and StreetComplete have exactly the same permissions:

![IMG_20220726_112802.jpg](https://user-images.githubusercontent.com/614929/180978418-aae6affc-87d0-4b50-9a6e-5ef7d553d3b9.jpg)

![IMG_20220726_112829.jpg](https://user-images.githubusercontent.com/614929/180978470-815e327f-041b-455b-9e7d-bf3750007195.jpg)

**How to Reproduce**
- Open the App
- See a wrong position with a 1 km radius around it. 
- This stays there for quite some time 

**Expected Behavior**
Have the GPS fix within the time the app is starting like before 

**Versions affected**
V45.1

**Comment by Helium314** [comment]
> Doing a start of GMaps doesn't help StreetComplete, Mapy.cz, etc. to get a faster fix.

So the Mapy.cz app has the same issue?

**Comment by westnordost** [comment]
I don't really see any thing we can do here. StreetComplete is using the correct Android APIs to access the location. If the API does not return any location to the app, we can take note of this, but it is not actionable.
