### ISSUE TITLE
Is this still here? - barrier=log

### ISSUE THREAD

**Issue by Stugeb** [streetcomplete/StreetComplete#4242]
**The suggestion:**

- enhancement for: "Is this still here?" - Quest
- Question: "Is this still here? (fallen tree)"
- Element: barrier=log
- Resurvey interval: 1 Year or less

**Information about barrier=log:**

- [taginfo](https://taginfo.openstreetmap.org/tags/barrier=log)
- [wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlog)
- [overpass turbo](https://overpass-turbo.eu/?template=key-value&key=barrier&value=log)

**Explanation:**

I think a lot of logs are mapped and mappers may forget about them pretty quickly. (At least I don't remember) Since most logs (that I know of) get removed after some time, I think this would help as it also affects routing.

**Som pros:**

- effects routing
- effects 7 394 objects (for comparison:  3 472 [amenity=ticket_validator](https://taginfo.openstreetmap.org/tags/amenity=ticket_validator))

**Some cons:**

- effects 7 394 objects (for comparison: 1 860 361 [amenity=bench](https://taginfo.openstreetmap.org/tags/amenity=bench))
- some logs don't get removed over time

**Additional Question:**

Should the same be done for [obstacle](https://wiki.openstreetmap.org/wiki/Key:obstacle)=fallen_tree?

**Comment by peternewman** [comment]
See #3382 it was blocked due to a lack of preset support which was probably part of why it wasn't there before.

They were added to iD in https://github.com/openstreetmap/id-tagging-schema/pull/506 which appears to be in a release.

**Comment by matkoniecz** [comment]
I would put it into 2 years resurvey to avoid making a new section.

obstacle=fallen_tree has no wiki page and I have no idea why it uses unusual key and duplicated `barrier=log` and used less. I see no reason to support it.
