### ISSUE TITLE
Localization for features

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#4244]
**Use case**
Supposing a user is asked whether the footway has lighting or not, the question is asked in Thai but the feature name is in English, which makes it confusing for the user as often there's no other indicator of what feature is being asked. So just that you understand the problem, I present the scenario in reverse

Is it lit here?
ทางเท้า

(user would see:
มีไฟส่องสว่างไหม?
footway)

**Proposed Solution**
It would be nice if "footway" and all the other features can be localized as well so the user has a clear idea of what's being asked of them.

**Comment by matkoniecz** [comment]
>  It would be nice if "footway" and all the other features can be localized as well so the user has a clear idea of what's being asked of them.

See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#id-presets - it is possible, but as we are using external data it happens in a different place. As bonus, translating there helps also other projects including the default editor)

**Comment by matkoniecz** [comment]
Note that translations need to imported into SC - so translating does not result in immediate changes.

**Comment by mishari** [comment]
@matkoniecz I just realized iD editor has a lot of preset strings, many of which are not relevant to Thailand or even StreetComplete, do you have any idea as to how I can prioritize the strings to be localized?

**Comment by matkoniecz** [comment]
Sadly I have no good idea here that would be faster than just not translating some entries or even simply translating all.

**Comment by matkoniecz** [comment]
But translating them will be helpful in general. For minimal solution: you can translate what you remember shown in English.

**Comment by mishari** [comment]
I just have another question, how long would a reviewed translation in iD editor's Transifex take to reach StreetComplete?
