### ISSUE TITLE
Prevent huge area uploads

### ISSUE THREAD

**Issue by SafetyIng** [streetcomplete/StreetComplete#4245]
Streetcomplete generates massively huge changesets (geographical expansion), so that urgent countermeasures must be taken here. It massively complicates the QM of OSM. Especially such large areas should be avoided. Examples can be found in the following CS:

https://www.openstreetmap.org/changeset/124041687
https://www.openstreetmap.org/changeset/124047734

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#A_changeset_made_with_StreetComplete_covers_a_massive_area%2C_why_is_this%3F_How_can_it_be_prevented%3F

**Comment by matkoniecz** [comment]
> that SC has to handle, if their users missuse the software

Not really. Any OSM editor can be misused in ways not preventable in feasible ways.

It would make sense only if it is typically happening due to edits which are not invalid wrong.

Making wrong edits more visible for reviewers is a good thing.

**Comment by SafetyIng** [comment]
> Making wrong edits more visible for reviewers is a good thing.

Only when it is able to find this edits. When I get 100 edits in a area and 50 are not really in this area, because SC has so big bboxes created, so this edits show up in my search area; then this is a problem.

**Comment by BalooUriza** [comment]
I'd suggest getting in touch with the user you're having trouble with, and
ask that they upload their StreetComplete changes before moving a large
distance away

**Comment by SafetyIng** [comment]
> with the user you're having trouble with, and ask that they upload their StreetComplete changes before moving a large distance away

When Streetcomplete would have a maximum bbox or other options to prevent this happening, than you don't need to get intouch with other users. Technical solutions are always preferable to a level 3 solution (personal behaviour).

**Comment by matkoniecz** [comment]
It would make sense to do something only if it is typically happening due to edits which are not invalid or wrong.

If large bbox happen due to user "mapping" places which they have not visited then it is misuse of SC.

If there is indicator that large (most?) of large bboxes is caused by people mapping places they visited then some action from SC side may make sense. Until it happens: see FAQ.
