### ISSUE TITLE
Add a badge for removing nodes

### ISSUE THREAD

**Issue by DoggoOfSpeed** [streetcomplete/StreetComplete#4247]
**Use case**
So to my knowledge, deleting nodes (saying that things don't exist) aren't counted towards progressing any badge/achievement. Considering how important removing out of date data is, it should probably be rewarded.

**Proposed Solution**
Add a badge to commemorate deletions of nodes

**Comment by arrival-spring** [comment]
I'm not sure it should be encouraged to delete things.

However, when you delete something it still counts as answering that quest, so counts towards that quest the same as saying that it does exit.

**Comment by DoggoOfSpeed** [comment]
> I'm not sure it should be encouraged to delete things.

Why not? I am sure that many people don't bother deleting out of date nodes as deleting is simply (relatively) harder, takes more time and clicks

> However, when you delete something it still counts as answering that quest, so counts towards that quest the same as saying that it does exit.

Very nice, was unaware of that :)

**Comment by westnordost** [comment]
Jup, you still get a ⭐ for answering that something is gone (now)

**Comment by westnordost** [comment]
What would be a nice achievement, IMO, would be one that you get for answering a number of **re-survey** questions. After all, wrong data is worse than no data, so keeping the data up-to-date is very important and worthy of awarding achievements.
However, it is not trivial to implement.

**Comment by DoggoOfSpeed** [comment]
Yeah, tbf deleting nodes is usually rarer than most other types of quests. Maybe having a "Maintainer" badge that counts both deletions and confirmations would be the solution...

> After all, wrong data is worse than no data.

Couldn't agree more
