### ISSUE TITLE
Can't update to v45.1

### ISSUE THREAD

**Issue by bonswouar** [streetcomplete/StreetComplete#4248]
**How to Reproduce**
- I currently have v45.0 installed (from F-droid)
- If I try to update to v45.1 (from F-droid), I get an error saying installation failed

**Expected Behavior**
Should be able to update

**Versions affected**
- v45 (to v45.1)
- Android 12 (LOS 19)
- microG 0.2.24.214816

**Additional information**
Tried to install v45.1 directly from the apk in github release with adb, got the error :
```
adb: failed to install StreetComplete-v45.1.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package de.westnordost.streetcomplete signatures do not match previously installed version; ignoring!]
```
I can try to uninstall it first, but I guess updating should work?

**Comment by Helium314** [comment]
Can you try installing the [apk from F-Droid](https://f-droid.org/repo/de.westnordost.streetcomplete_4503.apk) using adb? The error message might give a hint what is wrong.

**Comment by bonswouar** [comment]
@Helium314 my bad I didn't think that the signatures were different for Fdroid's apk
Well... I've just tried and it successfully installed it, so weird! I guess we'll never know, feel free to reopen this if somebody has the same issue

**Comment by Helium314** [comment]
Maybe something went wrong with the download in F-Droid? I also find that sometimes I am unable to install/update apps from F-Droid for no obvious reason...

**Comment by bonswouar** [comment]
@Helium314 I actually have tried few times do delete / redownload it from F-droid, but it didn't work (even waited few days just in case there's something wrong with their server), but yeah that seems to be the more logical explanation!

**Comment by mnalis** [comment]
@bonswouar shutting down the phone and starting it up again usually helps me with similar problems
