### ISSUE TITLE
Is "Does traffic_calming still exist" really needed for traffic_calming=island ?

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4249]
**Use case**
I got a resurvey quest for 
https://www.openstreetmap.org/node/747815025
with `traffic_calming=island`

https://wiki.openstreetmap.org/wiki/Key:traffic_calming

I really can not imagine a situation where an island is removed.

**Proposed Solution**
Skip resurvey quest for them.
Same probably for some of them which are part of the street itself:
hump, choker,chicane

bump and mini_bumps other can easier be removed or damaged, so they are Ok, IMO.

https://github.com/streetcomplete/StreetComplete/blob/7c97885cb6c24f9f7defed22e4497a495ab7e4ab/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L55

**Comment by westnordost** [comment]
It could be removed when a road is re-designed.

**Comment by matkoniecz** [comment]
Though maybe asking less often may make sense.

**Comment by legofahrrad** [comment]
> It could be removed when a road is re-designed.

After a construction site, when the road has been rebuilt, more than just deleting a traffic island is often necessary to adapt the new road situation to OSM (e.g. update street's geometry).
So I don't think StreetComplete is the right app to update the road after a construction.
