### ISSUE TITLE
"What kind of entrance" quest should not be created on covered ways

### ISSUE THREAD

**Issue by rohieb** [streetcomplete/StreetComplete#4250]
**How to Reproduce**
See e.g. https://www.openstreetmap.org/way/327386056, which crosses several buildings, but is tagged with `covered=collonade`. The quest is added at every intersection of the footway with a building.

**Expected Behavior**
The "what kind of entrance" quests should not be created in this instance, as there is no entrance, because the footway runs under the buildings. Looking at https://wiki.openstreetmap.org/wiki/Key:covered, there are also probably other instances of `covered=*` where this quest is irrelevant.

I think it could be solved by changing the `excludedWaysFilter` query to `ways with (tunnel and tunnel != no) or (covered and covered != no)` in app/src/main/java/de/westnordost/streetcomplete/quests/building_entrance/AddEntrance.kt

**Versions affected**
StreetComplete 45.0

**Comment by matkoniecz** [comment]
already fixed in https://github.com/streetcomplete/StreetComplete/commit/558ba28b16aceb7d7bfc2252b38f4f60fda0e7bc as far as I can see (which is likely not present yet in any released version)

**Comment by Helium314** [comment]
Well, according to the tag it's in 45.1, which was already released more than a week ago.

**Comment by matkoniecz** [comment]
>  StreetComplete 45.0

@rohieb Can you test it with 45.1 then?

**Comment by legofahrrad** [comment]
Tested with v45.1 and seems to be fixed now.

**Comment by rohieb** [comment]
Ah, my F-Droid doesn't seem to update automatically anymore… The quests were still there after the update to 45.1, but went away after I cleared the app cache. Thanks!
