### ISSUE TITLE
Cannot enter house number with slash

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#4251]
Not sure if this is a bug, but many properties in Thailand have house numbers with slashes in them. When StreetComplete enters a house number input mode, the keyboard changes to one that doesn't allow one to enter a slash.

![image](https://user-images.githubusercontent.com/503018/181683761-4bd0509f-463e-485a-a032-8012b44f23c0.png)

**Expected Behavior**
I would like to be able to enter a slash (/)

**Versions affected**
45.0

**Comment by Helium314** [comment]
Can you enter a slash when you bring up the full keyboard using the `ABC` button?

**Comment by mishari** [comment]
Yes I can, sorry didn't notice that button.

**Comment by westnordost** [comment]
See also #4196

So it looks like the "/" is common in Thailand too. Maybe the slash should not be regarded as "odd input" in any country.

**Comment by westnordost** [comment]
Housenumbers with a slash e.g. "99/9" are considered valid and the app will not warn about it "looking odd".

However, "99/99" is considered odd. I changed it to accept up to two digits/letters behind the slash before warning about it.
