### ISSUE TITLE
For overlays, when selecting one with unknown value - immediately open answer window

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4252]
**Use case**

Current interface requires:

- tap unanswered pink section
- tap "I want to answer" (via clicking select button)
- tap answer

Second step is almost entirely pointless (only rarely one needs to split way)

**Proposed Solution**

Automatically open answer selection where none is provided.

Problem (1): what about access to way split? It is still available but not in a clear way.

Problem (2): I tried to implement it and failed, as menu kept opening for all cases, also when answer is actually given.

Problem (3): Geometry info may be not obvious (though, you see exact effects of edit after it is made and one may still access geometry view...)

Alternative idea: maybe show not just "Select" button but make this answers listed?

Alternative view: maybe I found an actual problem but I am trying to solve it in a wrong way. Or there is no actual problem here?

**Comment by westnordost** [comment]
You mean the dialog should pop up right away? I am skeptical about that. The same as for quest applies: First, the user should be able to see on the map for which stretch of road this is shown.

Also, this won't work for the street side select, where the user **must** decide first for which side to answer. So having this functionality in some overlays but in others not would be inconsistent.

> Alternative idea: maybe show not just "Select" button but make this answers listed?

And showing a completely different interface when no data is specified also doesn't look nice. First of all, it is inconsistent, second, it is more implementation effort.

So, I'll close this as will not fix.
