### ISSUE TITLE
ability to see the already available poi

### ISSUE THREAD

**Issue by BuZZ-dEE** [streetcomplete/StreetComplete#4255]
ability to see the already available points of interest, so I can know if it makes sense post a poi hint.

**Comment by riQQ** [comment]
Related to #4253

**Comment by westnordost** [comment]
Closing as duplicate of #4253

**Comment by BuZZ-dEE** [comment]
Duplicate of #4253

**Comment by BuZZ-dEE** [comment]
@westnordost duplicate, but not planned or what does closed as not planned mean?

**Comment by matkoniecz** [comment]
Github shows "Won't fix, can't repro, duplicate, stale" in mouseover of "not planned".

And either way: it was closed as duplicate of open issue that stayed open.

**Comment by BuZZ-dEE** [comment]
@matkoniecz why I don't see: "[westnordost](https://github.com/westnordost) marked this as a duplicate of [#4253](https://github.com/streetcomplete/StreetComplete/issues/4253)" like in the other issue?

**Comment by riQQ** [comment]
@BuZZ-dEE it only works if the exact phrase "Duplicate of #x" is used. This wasn't the case here.

**Comment by BuZZ-dEE** [comment]
@riQQ thx for clarification. It is a little bit confusing, if there is no straight line how to deal with duplicates.
