### ISSUE TITLE
Remember default language for “Whats the name of this place”

### ISSUE THREAD

**Issue by Jrchintu** [streetcomplete/StreetComplete#4257]
**Use case**

While on survey, incase of hurry if you forget to change language (Local->English) and the language is set to 'local' rather than 'English' by default (i prefer to write answer in english) then it may create problem in naming of places due to wrong language. Tapping language change button is frustrating most of the time.

**Proposed Solution**

1) The best way to mitigate this problem is that the app should remember the most recently used/answered language for "whats name of this place quest", and giving that language 1st preference this will decrease the need to press '+' button, hence fixing this issue.

2) Else one more suggestion is that to show both the languages at same time rather than '+' icon, here also the preference to first line for language can be given to most recently used/answered langauge:
![IMG_20220731_202734](https://user-images.githubusercontent.com/75427894/182032291-57e3706d-383a-4de7-9dab-a308122ea7ed.jpg)

**Comment by matkoniecz** [comment]
Where you are editing?  In India? (I am asking, as this functionality is location dependent)

**Comment by Jrchintu** [comment]
> Where you are editing? In India? (I am asking, as this functionality is location dependent)

Yes

**Comment by westnordost** [comment]
In which state are you mapping?

**Comment by Jrchintu** [comment]
> In which state are you mapping?

I map throughout India, mostly in new Delhi

**Comment by westnordost** [comment]
So the feature request is to 
- save (for this session) or persist (forever) the language selected in the top-most row (=the default / pre-set one)
- and when the form is opened next time, if the country/subregion one is currently in, that language is available for selection, select it

**Comment by Jrchintu** [comment]
Had checked countrymetadata repo, new Delhi & Rajasthan has hindi as first suggestion (https://github.com/streetcomplete/countrymetadata/blob/master/data/officialLanguages.yml#L178)

**Comment by Jrchintu** [comment]
> So the feature request is to
> 
> * save (for this session) or persist (forever) the language selected in the top-most row (=the default / pre-set one)
> * and when the form is opened next time, if the country/subregion one is currently in, that language is available for selection, select it

Yes this sounds good to me.

**Comment by Jrchintu** [comment]
> So the feature request is to
> 
> * save (for this session) or persist (forever) the language selected in the top-most row (=the default / pre-set one)
> * and when the form is opened next time, if the country/subregion one is currently in, that language is available for selection, select it

Also i think, my [2] idea can also be implemented side-by-side ? Anything on that ?

**Comment by westnordost** [comment]
> Also i think, my [2] idea can also be implemented side-by-side ? Anything on that ?

Not sure if this is ideal because then there is room for edge cases like "only part of the last-selected" languages are available for selection in whatever state one is now

**Comment by Jrchintu** [comment]
> 

Yeah, this is problematic.

One last thing, can we do something to make it a bit easier to type in any language ? Like in [2] idea leave the part of 'ranking language' but at least we can consider decreasing the need to press '+' icon each time we need to change language ?

Suppose in case of new Delhi, there are 2 languages (as per our metadata) 'en' & 'hi'. With 'hi' as first (blank space will be visible), but for 'en' we need to press '+' or change by toggling (hi->en). But rather than showing '+' we can directly show both blank places ?

**Comment by westnordost** [comment]
> But rather than showing '+' we can directly show both blank places ?

People might be confused and think they need to fill in both(/all) languages, e.g. translate the English sign into Hindi etc. Also, for some countries, the list of official languages is quite long. In my experience, shop signs are usually in just one language.

**Comment by Jrchintu** [comment]
> > But rather than showing '+' we can directly show both blank places ?
> 
> People might be confused and think they need to fill in both(/all) languages, e.g. translate the English sign into Hindi etc. Also, for some countries, the list of official languages is quite long. In my experience, shop signs are usually in just one language.

Yeah, confusion will be there. Currently only visible option is changing order of language, but it may be controversial ?

And about shop signs, its not the case in India. Its common to see sign board in either local language or English sometimes both.

Btw, can we stick with https://github.com/streetcomplete/StreetComplete/issues/4257#issuecomment-1204404558 ?

**Comment by 1ec5** [comment]
> Had checked countrymetadata repo, new Delhi & Rajasthan has hindi as first suggestion (https://github.com/streetcomplete/countrymetadata/blob/master/data/officialLanguages.yml#L178)

According to the wiki, [the Indian mapping community’s convention](https://wiki.openstreetmap.org/wiki/India#Naming_in_different_scripts_and_languages) is to put English in `name` regardless of a state’s official languages. Based on this policy, Hindi would go in `name:hi` but not `name:en`. Is that still the current practice, or does the wiki need to be updated?

**Comment by Jrchintu** [comment]
> > Had checked countrymetadata repo, new Delhi & Rajasthan has hindi as first suggestion (https://github.com/streetcomplete/countrymetadata/blob/master/data/officialLanguages.yml#L178)
> 
> According to the wiki, [the Indian mapping community’s convention](https://wiki.openstreetmap.org/wiki/India#Naming_in_different_scripts_and_languages) is to put English in `name` regardless of a state’s official languages. Based on this policy, Hindi would go in `name:hi` but not `name:en`. Is that still the current practice, or does the wiki need to be updated?

Sorry, i have no prior knowledge regarding this, i think @westnordost can answer this.
