### ISSUE TITLE
Navigate by address / geocoder

### ISSUE THREAD

**Issue by Matthias84** [streetcomplete/StreetComplete#426]
Hi,

I guess many people work like myself: My GPS is disabled and I zoom / pan manually. So I would enjoy if I could quickly search for an address and get the right area. I use it just when I begin with tagging, so it's pretty ok to hide it within an submenu.

**Comment by krzyk** [comment]
This would also help in debugging problems.
Maybe even register for osm http in android, just like Osmand does (clicking on a link starting with with http(s)://www.openstreetmap.org/ and a location)?

**Comment by HolgerJeromin** [comment]
ref #190

**Comment by ENT8R** [comment]
https://mapzen.com/documentation/android/search/
Maybe this link can help...

**Comment by matkoniecz** [comment]
I am not really convinced that it is worth adding, mostly due to increased clutter in interface.

With disabled GPS StreetComplete will be heavily impacted anyway.

I would propose to decline this feature request.

**Comment by smichel17** [comment]
+1 — I don't think StreetComplete needs address search embedded. If you need this, you can search in a different app, share a `geo:` uri, and open it in StreetComplete.

When I was testing this, I noticed that it is not working for me (SC does not open at the location of the `geo:` uri), but that's a new bug which should be filed.

**Comment by matkoniecz** [comment]
Closing as it would add extra service that would have own bugs, downtimes, keys and at least some geolocations would be bad.

There would be increased clutter/complexity in interface.

`geo:` is supported as workaround (unless it got broken again)

And, as this would be used even less it would likely keep regressing.
