### ISSUE TITLE
On note creation, location pin and its icon are separated [RTL issue]

### ISSUE THREAD

**Issue by iriman** [streetcomplete/StreetComplete#4260]
Location pin and its icon are separated.

![image](https://user-images.githubusercontent.com/8467903/182042717-d1974e0c-a080-423d-8d42-4bc86be83daa.png)

**How to Reproduce**
* Change app language to Persian or Arabic or another right-to-left language.
* Long press to open menu
* Select create note

**Expected Behavior**
Correct display for the pin and its icon as in English version:
![image](https://user-images.githubusercontent.com/8467903/182043016-d12dab14-74c7-4526-ab9f-835c2a501ba7.png)

**Versions affected**
v45.1

**Comment by matkoniecz** [comment]
Thanks for reporting, RTL bug reports are especially useful as I (and likely also Tobias) never actually use RTL interface and such bugs can easily slip in testing.

**Comment by westnordost** [comment]
I cannot reproduce this when I set "Force RTL layout" in the developer settings. I also cannot reproduce it if I change language to Farsi. The Android Studio IDE also does not reproduce this problem when showing the layout in preview.

![image](https://user-images.githubusercontent.com/4661658/182684350-5b99be0c-53b0-49b4-82b7-b06da52697ed.png)

My guess is that this is specific to the specific Android device or version you are using. Which one is it?

**Comment by iriman** [comment]
My android is 7.1.1
And device is SM-J510F

I also tried out:
* Android locale: en & app language: fa 
* Android locale: fa & app language: system
* Android locale: en & app language: system (only here no problem)

![۲۰۲۲۰۸۰۳_۲۳۲۰۰۵](https://user-images.githubusercontent.com/8467903/182686655-7b029c7f-6d0b-4ddd-ac3e-63107936c8eb.jpg)
![۲۰۲۲۰۸۰۳_۲۳۱۹۵۵](https://user-images.githubusercontent.com/8467903/182686665-ba32585d-6a11-448c-8180-30d557d6bf46.jpg)
![۲۰۲۲۰۸۰۳_۲۳۲۰۱۴](https://user-images.githubusercontent.com/8467903/182686667-7e29e9d3-7f73-49aa-b31f-e544164ea7ca.jpg)

**Comment by westnordost** [comment]
I found one property in the https://github.com/streetcomplete/StreetComplete/blob/0857679a146abaf474f051f8e8d12225d9a10ff3/app/src/main/res/layout/marker_create_note.xml#L31 that is not necessary, maybe that is the property that is causing this bug on your device. I removed it. Please comment here if the issue is not resolved after when the next minor update was released
