### ISSUE TITLE
Dog control zone on beaches

### ISSUE THREAD

**Issue by codeinabox** [streetcomplete/StreetComplete#4267]
**Use case**
Many beaches in the UK operate a dog control zone where dogs only allowed on the beach at certain times and / or dates. For example in Cornwall beaches have the following restrictions https://www.cornwall.gov.uk/environment/animal-welfare-and-enforcement/dogs-on-beaches/

**Proposed Solution**
This is still WIP but I was thinking the following flow:

1. Does this beach have restrictions when dogs are allowed?
2. User can enter a time period similar to how parking restrictions work

**Comment by matkoniecz** [comment]
Dog zone area is likely to mismatch area of mapped `natural=beach` and require splitting them. Splitting areas is not possible in StreetComplete.

So sadly this is out of reach of StreetComplete.

**Comment by codeinabox** [comment]
This shouldn't involve splitting or creating a new area as the restrictions I've seen apply to whole beach

**Comment by matkoniecz** [comment]
But restrictions may appear only to part of for example https://www.openstreetmap.org/relation/11930745
