### ISSUE TITLE
Unable to edit tunnels with (lit-)overlay

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4269]
Using the lit overlay makes it impossible to edit tunnels. Also, the tunnel is not coloured by its lit status (red/green/grey…).
Similar with the sidewalk overlay: footway tunnels are not coloured in green and streets without a sidewalk which are supposed to be grey are not coloured as well.

<h2>How to Reproduce</h2>
Look for some tunnel and switch on one of the overlays.

<details><summary><h2>Screenshots</h2></summary>

![Screenshot_20220804-193929](https://user-images.githubusercontent.com/92865620/182915876-3f391a9b-bec0-4602-8d62-4e46eac82337.png)
![Screenshot_20220804-191453](https://user-images.githubusercontent.com/92865620/182915888-2f361b1d-74f0-4507-a906-6f68b6341293.png)
![Screenshot_20220804-191442](https://user-images.githubusercontent.com/92865620/182915897-ed1b4f9c-4364-474e-b10e-6ae3503228e0.png)

**Locations from the screenshots**

- https://www.openstreetmap.org/way/37726448
- https://www.openstreetmap.org/way/198475680
</details>

<h2>Expected Behavior</h2>
Be able to edit tunnels correctly with both lit- and sidewalk overlay and roads should be coloured.

<h2>Additional Information</h2>

- It looks as if  `layer=-1` must be set, to be unable to edit a way with the lit overlay. Tunnels with just `tunnel=yes` and missing `layer` are editable.
- May this be caused by "fix layering order in overlay" https://github.com/streetcomplete/StreetComplete/commit/2e56d464a6c47e2717918f3469b45c6e5fd6603f ?

<h2>Versions affected</h2>

- StreetComplete v45.2

**Comment by matkoniecz** [comment]
Thanks for a great report, also your diagnosis was correct.

Colour is text anyway and width is not going to be negative, so I guess that other values are safe.
