### ISSUE TITLE
Seating quest: answer for "no seating, but tables"

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4278]
The seating quest requires the user to select "No seating (takeout only)" if a place has no seating.
But there are some rare places (usually fast food) that have high tables without seating (and without service), so only the "No seating" part applies, while "takeout only" is not correct.

Maybe there could be an answer added reflecting this case, which sets `outdoor_seating=no` and `indoor_seating=no` without adding `takeaway=only`. Or ideally it would add appropriate tags, but I don't know what that would be.

**Comment by matkoniecz** [comment]
Currently leaving note is the proper solution, and "takeout only" ensures that correct answer will result in no mistaggings.

Given "some rare places" it seems not necessary to provide such answer, unless many notes are created about it or there is a systematic mistagging problem by many users.

**Comment by matkoniecz** [comment]
In general long tail of rare cases should be solved by notes, and it infeasible and not planned to cover it via answers. Large part is that every new answers requires extra work from translators (multiplied by all languages supported now and in future)
