### ISSUE TITLE
Can not change default camera application

### ISSUE THREAD

**Issue by Kaor** [streetcomplete/StreetComplete#4281]
i can't add photo, SC show "no camera application available" but i have one, i use "Open Camera"

**How to Reproduce**
Just add a note

**Expected Behavior**
choosing camera application

**Versions affected**
45.2

**Comment by HolgerJeromin** [comment]
Which Android version and Phone do you use?

**Comment by Kaor** [comment]
LineageOS 19 (android 12) on asus max pro M1
thank you

**Comment by westnordost** [comment]
The "Open Camera" app is apparently not registered as being able to take a picture. This is rather an issue of that app, StreetComplete just asks the Android system to take a picture (with the default camera app):

https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.TakePicture

**Comment by Helium314** [comment]
Maybe it's and Android 12 issue? On Android 9 it works with OpenCamera.

**Comment by westnordost** [comment]
I use android 12 and it works fine (with the Samsung default camera app)

**Comment by andypillip** [comment]
I have the same issue on Lineage 23—with the Google Pixel Camera installed.
When I check the app’s permissions, Camera is not listed anywhere, neither in Allowed, nor in Not Allowed.
I’d expect the “Add photo” button to ask for permissions, but instead it’s directly responding “no camera application available“.
Is there any workaround?

<img width="540" height="1170" alt="Image" src="https://github.com/user-attachments/assets/4b9b8ba2-cb73-4cf6-9d68-b28e2cd10b6d" />

**Comment by riQQ** [comment]
> I’d expect the “Add photo” button to ask for permissions, but instead it’s directly responding “no camera application available“.

That doesn't happen because StreetComplete never uses the camera directly but instead use an intent to open the default camera app.

---

There is the following open feature request that would solve your problem:
- #6222

**Comment by andypillip** [comment]
I see, thanks for the explanation.
Does that mean that Camera would never show up in permissions?

The feature request would work around my problem, not solve it, I guess.
In my eyes it’s still a bug, since despite a Camera app installed, it doesn’t open. I just don’t know on which level it is. Maybe in lineageOS?

**Comment by riQQ** [comment]
>  Does that mean that Camera would never show up in permissions?

Yes. It's not showing any Camera permissions for StreetComplete on my phone either and adding a foto to notes works (Pixel 6a with stock Android 17).

>  In my eyes it’s still a bug, since despite a Camera app installed, it doesn’t open. I just don’t know on which level it is. Maybe in lineageOS?

Yes, either a LineageOS bug or the Camera app not advertising its capabilities.
