### ISSUE TITLE
Enable "is cash accepted" quest in Germany

### ISSUE THREAD

**Issue by Zocker1999NET** [streetcomplete/StreetComplete#4286]
**How to Reproduce**

- be in Germany
- open the quest selection in the settings
- check that below the quest "Is cash payment accepted here?" it states "Never shown in Germany"

**Expected Behavior**

I would expect this quest to be enabled because in Germany it is allowed to forbid cash payment if you were informed about that before a contract (e.g. the buying) effectively happened. See [this short explanation from the Federal Office of Criminal Investigation (BKA)](https://www.bka.de/SharedDocs/FAQs/DE/Falschgeld/falschgeldFrage01.html) and this [longer version from another page](https://www.bka.de/SharedDocs/FAQs/DE/Falschgeld/falschgeldFrage01.html) (both im German). It is not common now, but I know some places which successfully forbid cash payments (especially when paying for parking lots).

**Versions affected**

v54.2 on Android 11 (LineageOS 18.1)

**Comment by matkoniecz** [comment]
> It is not common now

And that is why this quest is disabled. It is enabled in Sweden as this quest is not spammy there.

"in really very rare cases it will have a different answer" is not reason to enable or add quest, see "no spam" in https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md

**Comment by Zocker1999NET** [comment]
Thanks for your answer. I understand the reasoning behind why the quest is a "spammy" one, however I do not understand why the quest is "hard-disabled" (a.k.a. user cannot override that) instead of being just "soft-disabled" by default (a.k.a. users can enable that, if they want) like other quests are.

It depends on what you look at, you cannot even expect from restaurants in Germany that you can pay cashless. However everywhere a (vending) machine is involved, it can happen quite often that you cannot use cash but only can pay cashless. A good example are petrol/gas stations without personal (or at night only) where you can more often than not only pay cashless in Germany.

The current situation makes this quest IMO even more important because people wouldn't expect that they cannot pay with cash. That's why I would like to have that, because without, OSM fans, who can willingly accept "spammy" quests, would need to use another editor to enter this important but simple information. And that seems unnecessary because StreetComplete already supports the quest.

The quest is already disabled by default. So I would propose to let users be able to enable the quest everywhere, but change the "disabled message" so when users enable the quest, they will be additionally informed that this may be only "no" in rare cases, depending on the region they are living in.

**Comment by mnalis** [comment]
I can see your problem... StreetComplete is however geared towards users which might not understand the issue, and might thus spam themselves without realizing it after dismissing the warning (or even worse, attracting the wrath of OSM local communities), so it is unlikely it would be allowed to enable them, as noted above - as the number of confused non-expert users would be much greater than number of expert users that would benefit from it.

One option available to you is to fork the project and modify it to suit your needs (i.e. allow said spammy quests in your country). That's what I did initially for myself...

Or you might want to suggest this feature at ["Expert Edition" SC fork](https://github.com/Helium314/StreetComplete/). It already allows modifying quests filters to enable some quests to become more spammy (if they're already show), so it might be open to allowing users to enable country-spammy quests after additional warning (if that's not too complicated to implement).
