### ISSUE TITLE
Does this restaurant have outdoor seating?

### ISSUE THREAD

**Issue by matthiasfeist** [streetcomplete/StreetComplete#4287]
### General
Affected tag(s) to be modified/added: [outdoor seating](https://wiki.openstreetmap.org/wiki/Key:outdoor_seating)
Question asked: **Has this place outdoor seating?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by matkoniecz** [comment]
Already implemented, you can enable it in settings: https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#cite_ref-:33_34-1

**Comment by matthiasfeist** [comment]
Ah thanks. I just saw that this quest is disabled by default, which is a bummer...

**Comment by riQQ** [comment]
Maybe #538 or #1176 contain the reason for it being disabled by default. I think it was because of the seasonality.
