### ISSUE TITLE
Does this ATM allow depositing money?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#4292]
### General
Affected tag(s) to be modified/added: [cash_in](https://wiki.openstreetmap.org/wiki/Key:cash_in)
Question asked: Does this ATM allow depositing money?
Cash or banknotes might be a better alternative of money.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

I'm not sure how many ATMs actually allow cash in. From what I've seen, there aren't a lot of them.

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by mnalis** [comment]
That is quite useful information to have, I agree.
But good question about spammyness. I also assumed (by default) that they were rare... 

However, checking one of most popular [banks](https://www.pbz.hr/gradjani/poslovnice-i-bankomati.html) here (which has somewhat usable website to check this), it seems to claim they have **693** ATMs country-wide, of which **204** allow depositing cash, which is about `29%` (and way above my estimate!)

The other big one has [horrible website](https://www.zaba.hr/home/mapa/Bankomati), but visually estimated it looks about `10-15%` allow depositing cash, which sounds closer to what I'd expect.

Another smaller bank I've [found info about](https://www.hpb.hr/hr/hpb-uvela-23-uplatna-bankomata/3453) explicitly states  their ratio is about `7%` ( 23/326 ).

So, at least over here in Croatia, it seems it would **not** be overly spammy.

**Comment by westnordost** [comment]
Seems fine to me.  Usage numbers also check out. 

Is it always week visible on the machines whether cash in is possible? How does such a machine look in croatia?

**Comment by mnalis** [comment]
Here is an example: https://youtu.be/xrwMMkKPngU?t=40
Yes, look on the left side there is an image painted showing arrow to insert banknotes _into_ ATM

**Comment by matkoniecz** [comment]
Is there also market that you cannot do this? I have never noticed either in Poland, but maybe I missed it.

**Comment by Dimitar5555** [comment]
There is no marker that you can't do it. Usually ATMs which allow depositing money have two opennigs for money (https://cemac-eco.finance/wp-content/uploads/2021/05/1.jpeg) but some of them have only one openning. Another thing to look out is stickers on the ATM that show you how to deposit money and possibly signs above them but that's also not required.

**Comment by westnordost** [comment]
Hmm, so that exists, too. I thought all cash-in terminals have this kind of tray that mnalis noticed. Nevertheless, I think it would be OK as a quest. After all, it'd make no sense to have a cash-in terminal that didn't advertise on the outside that it can do that.

**Comment by vehrmann** [comment]
Nice idea.
How about these possible answers:
- no
- yes, notes only
- yes, notes and coins
- cannot answer / hide quest

**Comment by mnalis** [comment]
> Nice idea. How about these possible answers:

I think it would be better to make it a simple `yes`/`no` quest as originally proposed:

- wiki for [amenity=atm](https://wiki.openstreetmap.org/wiki/Tag:amenity=atm) documents **_only_** [cash_in=*](https://wiki.openstreetmap.org/wiki/Key:cash_in)
- [tagingo](https://taginfo.openstreetmap.org/tags/amenity=atm#combinations) for `amenity=atm` gives no results for used-in-the-wild tag with "coin" in its name
- the [proposed tagging](https://wiki.openstreetmap.org/wiki/Proposed_features/coins_/_notes_acceptance) does not seem to have [caught on](https://taginfo.openstreetmap.org/keys/cash_in:coins)
- coin-accepting depositing devices are (in my Croatian experience) extremely rare (and have a different name), so leaving a note if one wants to mark it is probably good enough (and less confusing to the users).  Especially as (over here at least) those are usually located only inside few selected banks, separated from cash-out ATMs (they usually do not offer cash out), and are a separate service you have to pay for (and not a regular ATM deposit - i.e. trying to deposit 1000 EUR in coins would **not** result in 1000 EUR increase on you account - as it would when depositing regular banknotes).
- Also possibly [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md): :atom_symbol: Atomic quests, :man_technologist: Users are no experts, :chipmunk: Easy answer

**Comment by mnalis** [comment]
Anyway, unless some new/old/wanna-be contributor would like to try [contributing a new quest](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md) (speak up if you're possibly interested - it's not hard and there are plenty of helpful devs), I'll have some free time in few days, so can do a PR for this as a simple `yes/no` quest if there are no objections.

**Comment by vvizzo** [comment]
> Is there also marker that you cannot do this? I have never noticed either in Poland, but maybe I missed it.

In Poland we have only positive sign (yes, you can by name of "wpłatomat") but no negative indicator.
