### ISSUE TITLE
`cycle_barrier:installation=*` helps emergency services

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4293]
### General
Affected tag(s) to be modified/added: [cycle_barrier:installation](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation)
Question asked: **Can this cycle barrier be opened? If yes, how?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
 - helpful for emergency vehicles, similar to bollard type
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)
 - 9,800 `barrier=cycle_barrier`, only 460 `cycle_barrier:installation=*`

### Ideas for implementation

**Element selection:** 
```
nodes with barrier = cycle_barrier and !cycle_barrier:installation
```
- maybe exclude `cycle_barrier=tilted`?

**Metadata needed:** 
none

**Proposed UI:**
similar to bollard type or cycle barrier type, photos (e. g. from the wiki) with labels to choose

mock-up (edited screenshot):
![grafik](https://user-images.githubusercontent.com/92865620/184981277-cafaa283-3887-4466-868b-deec5462401e.png)

**Icon:**
use some sort of adapted [no_bicycles.svg](https://github.com/streetcomplete/StreetComplete/blob/master/res/graphics/quest/no_bicycles.svg)?

**Comment by matkoniecz** [comment]
>  Not an overwhelming percentage of quests have the same answer (No spam)

Are you sure? It seems that vast majority will be `fixed`.

**Comment by legofahrrad** [comment]
In my area, there are also many openable cycle barriers or these swing-gate-mechanism-types (also tagged with `openable`)

**Comment by westnordost** [comment]
As icon, maybe a firefighter truck behind the 🚫

**Comment by legofahrrad** [comment]
> As icon, maybe a firefighter truck behind the 🚫

Sounds good, though this would also fit to all the other emergency achievement quests. (So maybe a bit unspecific?)

**Comment by legofahrrad** [comment]
Anyone want to create the quest? I can't code at all ;)

**Comment by matkoniecz** [comment]
> Anyone want to create the quest? I can't code at all ;)

It is quite simple to implement so I prefer to not jump on it myself. I posted about it in two places, lets see whether anyone responses.

If noone then I will likely do it in middle of researching why react app is not working as expected and investigating what is the proper way to display of overlay tutorial.

**Comment by mnalis** [comment]
I could code this if you prefer to do more complex things @matkoniecz, however I'm on limited data plan currently so would need someone (@legofahrrad  ?) to provide freely licensed photos (see [here](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md#new-photos)) to use in the quest. 

Current ones from [the wiki](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation) (and used in mockup here) seem to have licensing problem at the moment.

<details> 

e.g. https://wiki.openstreetmap.org/wiki/File:Cycle_barrier_fixed.jpg#Licensing etc. says it is CC-BY-SA 4.0 but without mentioning author, which is requirement.

I've tried to contact uploader on their [user talk page](https://wiki.openstreetmap.org/wiki/User_talk:Supaplex030#Licence_on_Key:cycle_barrier:installation_images?), but they have not commented on other (several months old) licensing questions posted there yet, or indeed edited their wiki page . So unless the situation resolves it soon, it is possible this request for clear licensing might be in for a long wait too.

</details>

**Comment by mnalis** [comment]
Hi @SupaplexOSM, would you please clarify the licensing of images on https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation (as mentioned on [User_talk:Supaplex030](https://wiki.openstreetmap.org/wiki/User_talk:Supaplex030#Licence_on_Key:cycle_barrier:installation_images?)) so they can be used for StreetComplete project? Thanks!

**Comment by SupaplexOSM** [comment]
I already did :)

**Comment by westnordost** [comment]
Note regarding the pictures:

The "magnifying glass" circles and arrows are a nice idea, but kind of get lost in these small icons (e.g. behind the text). They'd need to be re-positioned (and with a thicker border)

Or, use different pictures

Or, show just the section of the pictures that show the important thing (the existence of a firefighter-lock / the hinge and whatever)

**Comment by SupaplexOSM** [comment]
I have uploaded the "raw photos" on commons - feel free to re-compose them ;)
[total view](https://commons.wikimedia.org/wiki/File:Cycle_barrier_removable_total_view.jpg) | [detailed view](https://commons.wikimedia.org/wiki/File:Cycle_barrier_removable_close_view.jpg)

**Comment by legofahrrad** [comment]
Yes, it would only be consistent to allow re-tagging of barrier type. ("Other answers" → "no cycle barrier but other barrier" → tags `barrier=yes` and thus triggers barrier type quest)

**Comment by mnalis** [comment]
@legofahrrad I've written the code in PR https://github.com/streetcomplete/StreetComplete/pull/4406 (see the picture there how it looks currently and with what answers).

However, I see that you suggested 4 choices here which **do not coincide** with values of [cycle_barrier:installation=*](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation) wiki.  Was that intentional, and if so, how do you propose to tag those?

Also, we need pictures! @SupaplexOSM provided [here](https://github.com/streetcomplete/StreetComplete/issues/4293#issuecomment-1237753822) raw photos for  `removable` which is great, but we should do [something](https://github.com/streetcomplete/StreetComplete/issues/4293#issuecomment-1237507377) about the rest of them (`fixed` is OK, but we lack picture for `foldable`, and something better for `openable`)!

Who can help? Do any of you can find those around you and can snap few pictures (zoomed out and zoomed in on moving/locking part?)

**Comment by legofahrrad** [comment]
> However, I see that you suggested 4 choices here which do not coincide with values of [cycle_barrier:installation=*](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation) wiki. Was that intentional, and if so, how do you propose to tag those?

In my mock-up, I made two pictures both tagging `openable`, as there are two versions of `openable` (hinged upwards and swing gate).

Regarding `foldable`, I would drop this due to the rarity of foldable cycle barriers – users can leave a note then.
For the pictures I can try to find some cycle barriers.

PS: Thank you for creating the quest @mnalis :)

**Comment by mnalis** [comment]
> In my mock-up, I made two pictures both tagging `openable`, as there are two versions of `openable` (hinged upwards and swing gate).

So, both pictures of `openable` were intended by you to be tagged exactly the same @legofahrrad ?

While that is technically possible, that kind of UI however might be quite confusing, judging by the past issues (like https://github.com/streetcomplete/StreetComplete/issues/3717). I'd rather stick to _"one tagging - one picture - one answer"_ model if possible, even if it means just choosing the picture of more popular variant.

> For the pictures I can try to find some cycle barriers.

Thanks, I'll wait for them to update the quest!

**Comment by legofahrrad** [comment]
Hi mnalis,
you're right there were issues about "two pictures tagging the same". But I think it is something different, when there are `openable` cycle barriers which can be a thing with the hinge to the top, or if there are two swing gates. (What I wanted to say: These two types are different but have the same osm-tag, so I think two pictures would fit best.)

At the weekend I tried to start using Wikimedia Commons, so I took some photos of cycle barriers and uploaded them to Wikimedia Commons. I have some photos of fixed cycle barriers so far but I look around for some removable/foldable/… types.
https://commons.wikimedia.org/wiki/Special:ListFiles?limit=50&user=LEGOFAHRRAD&ilshowall=1
The photos are licenced under CC0, so you can do whatever you want to do with these ;)

**Comment by mnalis** [comment]
Thanks @legofahrrad , I've taken the `removable` picture from there... I didn't find `openable` example in your album, so I've found another one to hopefully demonstrate it; see picture in https://github.com/streetcomplete/StreetComplete/pull/4406#issuecomment-1272098377
