### ISSUE TITLE
Android 13 gives notification permission prompt on first run

### ISSUE THREAD

**Issue by jleedev** [streetcomplete/StreetComplete#4294]
Android 13 shows the runtime permission for notifications when the app first runs:

![Screenshot_20220817-131216](https://user-images.githubusercontent.com/23022/185205090-03c17ceb-bf9f-43b6-bea6-c9b4615aa56b.png)

Related reading: https://developer.android.com/guide/topics/ui/notifiers/notification-permission

While still targeting 12L (API level 32) or lower, it appears that this is triggered when the app creates a notification channel, so a fix could be to defer creating this until sometime later. It's still annoying, especially without any context in the app, but at least it's not the very first thing users see.

(But I wonder if it's actually required to create a notification channel purely to support a foreground Service?)

When targeting Android 13 (API level 33), it says "Apps don't need to request the POST_NOTIFICATIONS permission in order to launch a foreground service", so that's nice.

**Versions affected**
StreetComplete: 45.2
Android: 13

**Comment by westnordost** [comment]
> When targeting Android 13 (API level 33), it says "Apps don't need to request the POST_NOTIFICATIONS permission in order to launch a foreground service", so that's nice.

StreetComplete does not ask for permission to post notifications, so it sounds like this is a non-news 🤷

**Comment by westnordost** [comment]
A fix should include also upping the target API version to 33, simply because this alone might fix it. In any case, reading required as always when the target API version is upped.
