### ISSUE TITLE
What about cross walks with traffic lights?

### ISSUE THREAD

**Issue by NicoHood** [streetcomplete/StreetComplete#4298]
![IMG_20220816_191004.jpg](https://user-images.githubusercontent.com/6888294/185661897-95e0dcab-57cb-4cab-b1db-70cdf2f0941b.jpg)

We were on some holidays in the netherlands and i checked Street complete sometimes. They have cross walks with street Lichts. I marked them AS traffic light, but maybe We should also Mark them both AS normal cross walk?

But i am no expert in netherland traffic rules, just want to bring this up. Maybe the example pictures could also change dependent of the country?

**Comment by BalooUriza** [comment]
Doublecheck your tagging.  These should be highway=crossing,
crossing=traffic_signals.  StreetComplete does accurately tag it this way
and prompts what kind of crosswalk on highway=crossing.

**Comment by riQQ** [comment]
`crossing=traffic_signals` is correct, see also https://wiki.openstreetmap.org/wiki/Crossings#Street_crossings.

**Comment by matkoniecz** [comment]
OSM is using current tagging schema

https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:markings may be of interest to you - personally I support it but let's see what wider community thinks about it

If it would be clear that it is liked it may be a good idea to check how quest works
