### ISSUE TITLE
recheck recycled materials-quest is non-intuitive to mappers when several containers are mapped close to each other

### ISSUE THREAD

**Issue by Lukas458** [streetcomplete/StreetComplete#4303]
See https://www.openstreetmap.org/node/7609573820 , touched in https://www.openstreetmap.org/changeset/123716033

There exist two recycling containers in osm, nearly at the same place. 
The first one all the recycled materials which are open to be recycled there "24/7" and the second one only contains the glass bottles, because of the opening hours. Because the two nodes are nerly at the same place, the user will be unable to distiinguish which one is now tagged as the glass_bottles-container and whch one is for the other materials.

**How to Reproduce**
You need at least two mapped recycling containers which are very close to each other. This constellatin exists often in Germany, for example, because containers where glass bottles are recycled usually have opening times, which are maped with opening_hours. The opening_hours are valid only for the glass bottles container and nor for other containers which recycle other materials, so the glass bottles container is mapped separately.

**Expected Behavior**
A container which has recycling:*=... and opening_hours=* shuld not get any recycling:...=yes tags added for materials, for which the opening_hours do not apply. 

In principle, however, this has nothing to do with opening_hours, but generally with separately mapped containers. With separately mapped containers, it is always the case that at least one of the containers that exist in osm only recycles exactly **one** specific material out of a total of several materials which are accepted at this location.

Sometimes containers are also mapped separately because depending on the material accepted, the operator differs.

The user needs an information about which container he's aked about. Maybe the information, that THIS container which he's asked about, was mapped as the glass-bottles container until now, or which materials are tagged there until now? Maybe we can find a solution together for this. 
**I think simply showing two icons is not enough. Most mappers understand this in such a way that a container represents an entire location and that he/she is asked for the recycled materials of the ENTIRE location.**

**Versions affected**
version 45.0

**Comment by westnordost** [comment]
>  I think simply showing two icons is not enough. Most mappers understand this in such a way that a container represents an entire location and that he/she is asked for the recycled materials of the ENTIRE location.

Why not, though? Assuming that the recycling containers are placed correctly, you should be able to see which is which simply by looking at the icons on the map, i.e. how they are oriented towards each other.

**Comment by Helium314** [comment]
Another example of this issue, very close separately mapped glass and clothes containers.
The original glass container https://www.openstreetmap.org/node/5413118293 was changed by one user for both materials, apparenly unaware of the second container.
A bit later the original clothes container https://www.openstreetmap.org/node/5413118294 was changed by another user into a glass container, and a note created about a clothes container existing nearby. Maybe the positions of the containers were not mapped precisely.

(but I really don't know what could be done here)

**Comment by riQQ** [comment]
Maybe add a hint dialog asking the user to confirm that there is no second mapped container if any glass is combined with other materials?

**Comment by Lukas458** [comment]
To be honest, I also find it sometimes really difficult to judge how much "individual responsibility" can be assigned to the individual mapper when working. I do think that many people are simply unfamiliar with the separate mapping of containers (be it glass containers or other containers) and overlook it.

Of course, this "guilt" cannot be attributed to StreetComplete itself, at least not alone.

But somehow I think it's like bus connections. Everyone has the right to see where a bus is coming from, whether the route is still correct, whether the relation is mapped in OSM, to edit it, and so on. But if you let someone who has never heard of PTV 2 do it, there would also be chaos.

It's just not that easy to adequately reflect this micro-mapping practice in the app. If we have two separately mapped containers, these (i.e. which marerial now belongs in which container) can change their position very quickly. In some cases, after being emptied, containers are set up again in a different order than they were before. This is not intended to be justification for something, but that is one of the reasons why it is so difficult to draw direct conclusions about the materials recycled in this specific container based on the position of this specific container in OSM.

**Comment by westnordost** [comment]
Hm, especially the last paragraph sounds to me like a good argument against mapping single containers at all unless the containers are not related and have different operators as it is often the case with clothes containers.

**Comment by Elefant-aus-Wuppertal** [comment]
I do still have this issue with users, when th container for the glass bottles is mapped separately.

See for example : https://www.openstreetmap.org/node/6712991190/history

Users add all types of recycled materials to it, even though there should be only recycling:glass_bottles=yes on this single node, because I added this node because, the opening_hours (in Germany called "Einwurfzeiten") do only apply to the glass_bottles recycling, not to the other materials.

I consider this type of micromapping to be legitimate in order to be able to clearly assign the properties (especially opening_hours).

That's why it annoys me a little that data that don't belong together are finally being combined here.

What can we do to solve this issue?

**Comment by westnordost** [comment]
Well, if I remember correctly, it used to be the case or at least it was discussed that for recycling containers that are too close to other recycling containers, SC will not ask users at all about it.
However, this issue has been solved by always displaying nearby similar objects as the one currently selected to the user. In this case: Other recycling containers. So when the user edits the information for one container but sees there is another one just next to this one one the map, he will hopefully take this into account.

Not sure when this was implemented, but definitely before you created this ticket. 

Also, if the container has an operator or ref number, it will be shown just below the quest title. So if the operator is "Deutsches Rotes Kreuz Kleidersammlung" or whatever, the user will hopefully not select that you can also throw glass bottles in there.

But beyond that, I wouldn't know what to do about this. After all, users could just as well make the same mistake for this situation in any other editor. Actually, I'd expect users of classic editors to be even more trigger-happy deleting one of them when they think they spotted a duplicate.

**Comment by westnordost** [comment]
Uhh by the way, is this "Schwarzbachtrasse" as awesome as it looks on the map? Used to be for mining carts or something?

**Comment by Elefant-aus-Wuppertal** [comment]
> he will hopefully take this into account.

Haha, hopefully, yes :-) Sometimes users seem to do not, but so, I think I'll go into the changeset discussion then.

> Also, if the container has an operator or ref number, it will be shown just below the quest title

Oh okay, I see. That's new to me. Here it's unfortunately the same operator (and no ref), so unfortunately no property to differentiate the containers in this case, but thank you for mentioning that.
I'm glad that users are given the opportunity to distinguish between different containers standing next to each other.

> But beyond that, I wouldn't know what to do about this. After all, users could just as well make the same mistake for this situation in any other editor.

Hmm yeah, might be. In any case, thanks for your comments.

If you could look at this one: https://www.openstreetmap.org/node/8069145303
There is a `note` on it. Maybe it would be an option to show this in the app?
I know this problem is kind of specific, but maybe one could think about it in general, showing up a `description` or a `note` might be useful in other situations as well. Just as a suggestion.
<br>
> Uhh by the way, is this "Schwarzbachtrasse" as awesome as it looks on the map? Used to be for mining carts or something?

Oh yeah, haha, interesting thought. It is actually "only" a former railway line that has been converted into a cycle path. It takes its name from the Schwarzbach, which it crosses at a certain point. German branch lines called "rail buses" used to drive there.

**Comment by mnalis** [comment]
>  I know this problem is kind of specific, but maybe one could think about it in general, showing up a description or a note might be useful in other situations as well. Just as a suggestion.

Alternatively, `recycling quest` might be skipped on elements having `note=*` tag (as its existence likely indicates the issue is too complicated for AI, and human is required to evaluate specific issues detailed in freeform text)

**Comment by Elefant-aus-Wuppertal** [comment]
Yeah, I think this might be worth to think of. `note=*` is defined as a message for other mappers (e. g. of what to be careful about...).
