### ISSUE TITLE
Confirmation icon overlaps with options - easy to misclick

### ISSUE THREAD

**Issue by mccartney** [streetcomplete/StreetComplete#4307]
**Context**: I have been using SC for a while as a pedestrian and that works great for me. Recently, that led to me thinking I could answer SC quests when biking, so I bought a bicycle handlebar holder for a smartphone and started mapping when cycling. That works quite OK in most of the cases. But especially on non-firm surfaces, everything is shaky. Sometimes it's really hard to hit the exact place on the screen I wanted.

**Problem** 
Particularly in the road surface quest (and maybe others) there are a lot of graphic options and a confirmation icon :white_check_mark: drawn on top of it. Which led to me misclicking several times in 1 hour - I wanted to confirm my selection, but instead some other graphic tile got selected, etc.

In this example imagine I wanted to click :white_check_mark: to confirm, but I end up clicking Dirt instead
![image](https://user-images.githubusercontent.com/762437/186238059-dd2bb358-3167-4201-bc95-a459adb0dfd6.png)

Also I think the same kind of problem might be observed by people with finger agility challenges.

**Comment by mccartney** [comment]
Suggestions for consideration:
- make the confirm icon bigger?
- place elsewhere - i.e. not overlapping the options?

**Comment by westnordost** [comment]
Or, add an invisible view just below that button that is X px larger than the button, so there is some padding around it that does not allow taps to go through.
