### ISSUE TITLE
No shoulder quest in intersections?

### ISSUE THREAD

**Issue by mccartney** [streetcomplete/StreetComplete#4308]
I suggest not to ask the shoulder quest in intersections. I fail to even imagine how that would look like in practice. I think my report mostly applies to intersections of two streets, both of which have two separate lanes.

Example:
https://www.openstreetmap.org/way/154838108
![image](https://user-images.githubusercontent.com/762437/186489542-076032c0-e8f2-43af-a544-f93cdfcf056e.png)

**Comment by mccartney** [comment]
Related to #3727, #3834, #3613

**Comment by matkoniecz** [comment]
> I suggest not to ask the shoulder quest in intersections

Is there tagging to detect that? Or any sane method to recognise such ways?

**Comment by westnordost** [comment]
Intersections are not tagged in way that would distinguish them from any other road, hence it is not possible for StreetComplete either to specifically exclude intersections.

**Comment by mccartney** [comment]
> Is there tagging to detect that? Or any sane method to recognise such ways?

Trying to extrapolate from the https://www.openstreetmap.org/way/154838108 example:
- it's a short way
- which is also very near to other short ways

**Comment by mnalis** [comment]
@mccartney yes, that conditions are relatively easy for humans to detect. 
I'm not sure how **easily** it is achievable programmatically in StreetComplete, and how **resource-expensive** (i.e. slow) it would be if achiveable.

If it is however achievable relatively cheaply, I'd also note that the **_same conditions_** should be used to limit `smoothness` quest too (as suggested before at https://github.com/streetcomplete/StreetComplete/discussions/3626#discussioncomment-1956514)

**Comment by westnordost** [comment]
Generally,  it would be best to only ask for rural roads. However,  there is no tag to devote something explicitly as a rural road.
