### ISSUE TITLE
Position not stable

### ISSUE THREAD

**Issue by Ronchar07** [streetcomplete/StreetComplete#4311]
For a few days now, the map no longer centres on the exact position, but on places where I have been before, with a large blue circle, i.e. "inaccurate position". After restarting the app, there is a mostly correct position at first, but then the location is no longer tracked. Clearing the cache, deleting data, switching off energy-saving mode, reinstalling the app all do nothing. Have now solved about 700 tasks, never had problems before. Other apps centre exactly. 
Version 45.2, Android 8.0. Thanks for help!

**Comment by westnordost** [comment]
Nothing changed in the app,  it's using the android location api.

**Comment by westnordost** [comment]
Maybe check if you granted it access to the precise location. Otherwise,  I'm at a loss

**Comment by riQQ** [comment]
Long shot: Have you rebooted your phone?

**Comment by Ronchar07** [comment]
Yes, several times rebootet.

**Comment by FloEdelmann** [comment]
Maybe it is caused by #4139, which was first released in https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0?

Do you know in which versions it still worked for you?

**Comment by mnalis** [comment]
Have you tried in some other GPS-enabled apps if you have them installed (like [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd) or [Organic Maps](https://wiki.openstreetmap.org/wiki/Organic_Maps) etc.) does the problem occurs there too, or is it specific to StreetComplete only?

Has there been Android system update on your phone recently?

I'd search Android system settings for `Location`, and disable non-GPS locations. It goes by many different names: "Google Location Accuracy/History", "Wifi+Bluetooth positioning" etc. Basically disable any location options any options which does not mention GPS.

If that does not help, You can also try downloading [GPSTest](https://wiki.openstreetmap.org/wiki/GPSTest) application and:
- see does it shows location correctly when `Map` is selected
- select `clear assist data`, reboot the phone, start GPStest again (remember to turn it on), and then wait some time outside for full GPS data reacquire (warning: such a [cold start](https://en.wikipedia.org/wiki/Time_to_first_fix) might take up to 10-20min, depending how clear a view of the sky you have). You should see satellites start to pop in one by one, after there is more than 4 of them you might get a location fix (i.e. Lat/Long/Time will get values and start updating)

**Comment by Ronchar07** [comment]
First of all, thanks for all the tips! My Street Complete is running again. My Android system displayed an update, and after running it, everything was fine again. Very strange, because I had set the system to "automatic updates" and this update (from September 2020) was only offered to me now (!). It was also strange because the error occurred very suddenly, without any change to the configuration. Anyway, now it works again, and I think that's great.
