### ISSUE TITLE
"Is this a one-way street? In which direction" is asked of roads that are logically cul-de-sacs

### ISSUE THREAD

**Issue by SomeoneElseOSM** [streetcomplete/StreetComplete#4316]
Example way is https://www.openstreetmap.org/way/23736901

The only thing on the other side from the rest of the road network is https://www.openstreetmap.org/way/988136886 , a private service road.  Whilst the question isn't asked for e.g. https://www.openstreetmap.org/way/1078656749 (a cul-de-sac with not even a private service road on the other side of it), it would make sense to not ask the question about way 23736901 either, because it can't logically be a one-way.

**How to Reproduce**
Ensure the quest is turned on and browse around https://www.openstreetmap.org/way/23736901

**Expected Behavior**
Don't ask this question about https://www.openstreetmap.org/way/23736901 or e.g. https://www.openstreetmap.org/way/23736894 which forms part of a public cul-de-sac.

**Versions affected**
v45.2

**Comment by matkoniecz** [comment]
Note that it can be oneway and some other street may be not yet mapped - for example it could be oneway and this service road open to public

**Comment by westnordost** [comment]
This is too complex to find out. It basically involves creating a routing graph out of the street data. I have no intention to create another routing engine ;-) 
After all, it does not only affect the last road segment in a cul-de-sac but any other that leads to it as well.
