### ISSUE TITLE
The same name is used for different quests

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4318]
**How to Reproduce**
Open the quest list and find the height quests

![IMAGE 2022-08-29 14:15:06](https://user-images.githubusercontent.com/25708359/187189085-7b27a2f5-7ecb-4edd-9e3b-bb4e7de0770f.jpg)

The translations match because the same string is used.
<img width="717" alt="Снимок экрана 2022-08-29 в 14 11 52" src="https://user-images.githubusercontent.com/25708359/187189222-eb0ae425-0d54-4918-852d-e4416b7542f7.png">

**Expected Behavior**
It should be clear how the quests differ.

**Versions affected**
45.2

**Comment by westnordost** [comment]
Quests do not have names, they only have questions asked. And the question asked is the same for both quests.
