### ISSUE TITLE
answer width quest but quest won't stop showing up

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4323]
When answering the width quest at a node with `traffic_calming=choker` or similar, StreetComplete tags `maxwidth` but searches for missing `width`
https://github.com/streetcomplete/StreetComplete/blob/6d6807896aa85907eb1fa2dd012e473ca26192ef/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddRoadWidth.kt#L20-L22

**How to Reproduce**
Look for chokers etc. with missing `width` and answer the quest. It will show up again, though you answered it.

**Expected Behavior**
When answering the quest, it shouldn't show up again and again...

**Versions affected**
Happens due to new feature that also asks for width of chokers etc. (v46.0 beta1)

**Comment by westnordost** [comment]
Ah, damn. Thanks!
