### ISSUE TITLE
Aufschieben von Aufgaben

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4324]
Die Aufgaben-Reihenfolge lässt sich in den Einstellungen gut festlegen. Manchmal passt die voreingestellte oder persönlich festgelegte Reihenfolge nicht. Zum Beispiel habe ich gerade keine Zeit die Öffnungszeiten einzugeben oder bin an einem Haus bereits vorbei und sehe die Hausnummer nicht mehr. Dann bleibt mir nur die Aufgabe für mich zu verstecken. Wenn ich demnächst noch einmal am Objekt vorbei komme, wird mir die Frage dann nicht noch einmal gestellt.

Deshalb würde ich mir wünschen, daß man eine Aufgabe temporär ausblenden oder ganz an das Ende der Fragenkette schieben könnte.

**Comment by FloEdelmann** [comment]
Similar to #3952.

**Comment by matkoniecz** [comment]
That seems to be fully covered by https://github.com/streetcomplete/StreetComplete/issues/3952#issuecomment-1102986548

**Comment by FloEdelmann** [comment]
The suggestion to temporarily move one quest type to the end of the quest order is new.

**Comment by matkoniecz** [comment]
> That functionality would just open another bag of things that don't quite work for that use case: For example - how long will the quest be snoozed? Is it really possible to find any predefined time that would not feel unwanted in every case? I don't think so. https://github.com/streetcomplete/StreetComplete/issues/124 describes the root problem and that is that quests occlude one another, so that ticket is a better description would should be improved (if it was possible technically).

still seems to apply

**Comment by FloEdelmann** [comment]
I agree, just wanted to point out the new idea.
