### ISSUE TITLE
Tactile paving in Portugal

### ISSUE THREAD

**Issue by mikedld** [streetcomplete/StreetComplete#4325]
Tactile paving quests are currently disabled (or rather not enabled) in Portugal. Things have changed a bit since #750 and by my count there're currently
* 314 `yes` (13%) and 2088 `no` values for `tactile_paving` on `[highway=crossing]` nodes
* 19 `yes` (2%) and 895 `no` values for `tactile_paving` on `[highway=bus_stop]` nodes
* 19 `yes` (3%) and 605 `no` values for `tactile_paving` on `[kerb]` nodes
* 39 `yes` (62%) and 24 `no` values for `tactile_paving` on `[barrier=kerb]` nodes

Examples from Google StreetView:
* Lisbon: [38.7259498,-9.1497801](https://www.google.com/maps/@38.7259498,-9.1497801,3a,75y,76.65h,69.92t/data=!3m6!1e1!3m4!1sm-zkdZcPPNxkIxIfsJigMQ!2e0!7i16384!8i8192), [38.7427033,-9.1330129](https://www.google.com/maps/@38.7427033,-9.1330129,3a,75y,32.83h,62.83t/data=!3m6!1e1!3m4!1sNUMSFvjuwkTjsNTz28y-WA!2e0!7i16384!8i8192), [38.7674282,-9.0955926](https://www.google.com/maps/@38.7674282,-9.0955926,3a,75y,355.23h,79.62t/data=!3m6!1e1!3m4!1s7NjiauKnbPdsSpRfIHeQ5A!2e0!7i16384!8i8192)
* Porto: [41.1590853,-8.6356457](https://www.google.com/maps/@41.1590853,-8.6356457,3a,75y,330.82h,58.48t/data=!3m6!1e1!3m4!1sTQV72nOvVHCZMPVyJozT1w!2e0!7i16384!8i8192), [41.1535309,-8.5880169](https://www.google.com/maps/@41.1535309,-8.5880169,3a,75y,156.68h,51.39t/data=!3m6!1e1!3m4!1sKFIE3xBoIRXEdeZLBng2eg!2e0!7i16384!8i8192), [41.1791664,-8.5809407](https://www.google.com/maps/@41.1791664,-8.5809407,3a,75y,333.49h,73.86t/data=!3m6!1e1!3m4!1s3PeZe1PN2minOWpVXU0OJw!2e0!7i16384!8i8192)
* Coimbra: [40.2049808,-8.4088677](https://www.google.com/maps/@40.2049808,-8.4088677,3a,75y,356.99h,77.61t/data=!3m6!1e1!3m4!1sgppu7FC1CAzUBbJqAkiCpg!2e0!7i16384!8i8192), [40.1984839,-8.4027216](https://www.google.com/maps/@40.1984839,-8.4027216,3a,75y,18.98h,66.16t/data=!3m6!1e1!3m4!1s2Sku7rZkX7bbfhgOeQewaA!2e0!7i16384!8i8192), [40.2071672,-8.4204507](https://www.google.com/maps/@40.2071672,-8.4204507,3a,75y,319.32h,65.23t/data=!3m6!1e1!3m4!1sFyeaGCo592ZZQo44MfSMFw!2e0!7i16384!8i8192)

Please consider enabling at least `AddTactilePavingKerb` and `AddTactilePavingCrosswalk` quests. Still not sure about `AddTactilePavingBusStop` as I can't remember seeing it on bus stops myself.

**Comment by westnordost** [comment]
Since you are on-site and can confirm that tactile paving exists (to a degree), let's enable it then
