### ISSUE TITLE
Unable to assign street by tapping on quest

### ISSUE THREAD

**Issue by elevenchars** [streetcomplete/StreetComplete#4327]
When doing the quest to assign a street to a house, you cannot tap on the map to assign a street as described in the app. Please see attached video.

https://user-images.githubusercontent.com/11055681/187594356-9039b4d8-64fb-489f-bf29-e5a676249aef.mp4

**How to Reproduce**

- Find quest labeled "What street does (house)... belong to
- Attempt to assign a street by tapping on the map

**Expected Behavior**

The quest will be completed with the street the user taps.

**Versions affected**

v40.2

**Comment by Helium314** [comment]
This was fixed half a year ago, see #3797 
Does it still happen if you upgrade to a newer version?

**Comment by elevenchars** [comment]
i installed the latest version of this app from F-Droid. Is that page no longer maintained?

**Comment by elevenchars** [comment]
i see that the F-Droid page is indeed several major versions behind. Will profile stats and achievements be lost if I reinstall from Google Play?

**Comment by Helium314** [comment]
Unfortunately most of the recent versions have been removed from F-Droid since some closed-source dependency sneaked in, see #4289.

When re-installing you will get the stats / achievements back once you log in, but you will lose all your settings. If you use customized quest orders / presets this can be a serious annoyance and it may be worth waiting for the F-Droid builds to come back.

**Comment by elevenchars** [comment]
Just went ahead and installed v45.2 from the play store and this issue is not present there. Thank you for the help 😄 

Perhaps the F-Droid description should be updated to indicate that the app is pretty far out of date due to the licensing conflict.

**Comment by matkoniecz** [comment]
> When re-installing you will get the stats / achievements back once you log in, but you will lose all your settings.

And also not-yet-uploaded edits will be lost (see profile page to check is it relevant).
