### ISSUE TITLE
"Update quest settings on update"-dialog 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4328]
**Use case**
I've seen a couple of versions making changes to the standard quest settings, like version 46.0-beta1:

![IMG_20220830_160130](https://user-images.githubusercontent.com/614929/187663647-01ffc0a4-c3cc-4d17-b516-6c234d1b11bf.jpg)

That's kinda annoying, it does unasked changes to my profiles. 

**Proposed Solution**

It would be nice if this functionality could ask the user if they want to do the recommended changes to existing profiles - or ignore them.

For new quests a matrix display would be nice, where the new quests are on the x axis and the profiles are on y - so the user can decide to make changes to the recommendations.

**Comment by westnordost** [comment]
If you manually enabled or disabled a quest, you are not affected. Asking the user about this is not something I intend to implement.

**Comment by peternewman** [comment]
> If you manually enabled or disabled a quest, you are not affected. This affects only the default setting. Asking the user about this is not something I intend to implement.

But won't that apply for almost everyone for the ones that were enabled by default and have now been disabled?

> For new quests a matrix display would be nice, where the new quests are on the x axis and the profiles are on y - so the user can decide to make changes to the recommendations.

Even the ability to just filter to disabled quests would be nice.

**Comment by westnordost** [comment]
> But won't that apply for almost everyone for the ones that were enabled by default and have now been disabled?

Yes

**Comment by mnalis** [comment]
> But won't that apply for almost everyone for the ones that were enabled by default and have now been disabled?

I would guess that would be **_exactly the point_** -- if you did not manually modify that quest status, it should get new default - just like the new user installing the app the first time would get a new default. 

If one wants to have their custom set of quests, I would advise creating a **_new preset_** and setup their things there, and ignoring `Default` preset. It would then not change the defaults of the quests there, as opposed to `Default` preset which would (as it name should also imply) .

> Even the ability to just filter to disabled quests would be nice.

This I would second, it would be useful and I have wished for it many times. But there is not much space for UI for it. 

Sure, one could make for example clicking on `Enabled` heading to cycle the behaviour through `show all` / `show only unselected` / `show only selected`, but it could likely be confusing to new users unless there is additional texts or other visual info (just changing the background of the heading to three different colors might be too subtle for targeted SC population)

**Comment by matkoniecz** [comment]
> This I would second, it would be useful and I have wished for it many times. But there is not much space for UI for it.

I though about separate listing for just disabled quests, next to list of all quests that would allow enabling them (but not reordering)

**Comment by westnordost** [comment]
Such a UI (a button bar) would simply expand down from the search top bar and contract again when you are done.
