### ISSUE TITLE
remove unneeded quotes in strings

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4334]
**Use case**

in [app/src/main/res/values/strings.xml](https://github.com/streetcomplete/StreetComplete/blob/v46.0/app/src/main/res/values/strings.xml) some strings values are quoted (e.g. `"Paving stones"`) and some are not (e.g. `Unhewn cobblestone`). There seems to be no rule why it happens sometimes and not other times.

This is confusing (and asking for trouble when copy/pasting parts of them).

**Proposed Solution**

Preferably remove unneeded quotes (`"`) from **all** string values which have it. e.g.
>     <string name="quest_surface_value_sett">"Sett"</string>
should become:
>     <string name="quest_surface_value_sett">Sett</string>
 
(Alternatively, add the quotes to **all** string values. Just make it consistent...)

**Comment by westnordost** [comment]
This is so very very very unimportant that even the super sensitive Android Linter does not report that as a `(weak) warning` and not even as an `info`. Might as well sort all attributes in layout xmls alphabetically or something.

I think when there are no quotes, you cannot use certain characters without like (maybe) `<` but not sure, you'd have to look it up.
