### ISSUE TITLE
Ask for surface on indoor=yes ways (with different set of answers)

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4335]
### General
Affected tag(s) to be modified/added: [surface=*](https://wiki.openstreetmap.org/wiki/Key:surface)
Question asked: **What’s the surface here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary (well, one would _technically_ be "inside" when `indoor=yes`, but yes, it is easily answerable by pedestrian using that indoor footway, and needs on-the-ground survey)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) - there is [about 102k](https://taginfo.openstreetmap.org/keys/indoor#combinations) `indoor=*` `highway=*` ways, of which only [about 11k](https://taginfo.openstreetmap.org/tags/indoor=yes#combinations) have mapped `surface=*` tag.

### Ideas for implementation

**Element selection:** 
```
        ways with highway ~ corridor|path|footway|cycleway|pedestrian|steps|service
        and indoor ~ yes|room|area|corridor
        and access !~ private|no
        and (!conveying or conveying = no)
        and (!surface or surface older today -8 years)
```

**Proposed UI:**
Same UI as regular `surface quest`, just a different selection of answers (`paving_stones`, `concrete`, `asphalt`, `carpet`, `metal`, `wood`, `acrylic`).
@DeflateAwning have collected some pictures already (https://github.com/streetcomplete/StreetComplete/issues/4146#issuecomment-1168957735), and some can be reused for existing `surface` quest.

**Comment by DeflateAwning** [comment]
I'll be honest, I don't know how much value this has. I think it may have _some_ value, but I can't think of why anyone would reasonably care about this property. 

That said, I think the issue accurately states the best solution.

**Comment by matkoniecz** [comment]
Is https://taginfo.openstreetmap.org/tags/surface=carpet documented on wiki? How one would tag tiles covered in central half by carpet?

**Comment by mnalis** [comment]
> Is https://taginfo.openstreetmap.org/tags/surface=carpet documented on wiki?

The value `carpet` is documented at https://wiki.openstreetmap.org/wiki/Key:surface

> How one would tag tiles covered in central half by carpet?

Dunno, does that happen often? If it is mostly covered by carpet, then I'd guess as carpet. There  could always be generic `paved` answer (OtherAnswer?) to cover tricky cases (AKA _"It's complicated"_).

But yeah, maybe it isn't worth the effort. So closing, unless someone feels it would be very useful to them.
