### ISSUE TITLE
Ask bus stop quests also for platforms mapped as ways

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4341]
**Use case**
According to the wiki, the tag `public_transport=platform` can be used on nodes, ways, and areas. However, the bus stop quests  `AddBenchStatusOnBusStop`, `AddBinStatusOnBusStop`, `AddBusStopLit`, and `AddBusStopShelter` are currently only asked for platforms mapped as nodes. Only the `AddTactilePavingBusStop` is also asked for ways/areas.

**Proposed Solution**
Update the element filters of all bus stop quests to also include ways.

**Comment by westnordost** [comment]
Hmm, I see no reason to not do this.

**Comment by westnordost** [comment]
I think maybe the reason why it has only been nodes so far was that if it is mapped as an area, the chance that bins, shelters and benches would be mapped separately. But on the other hand, I think it is well accepted that `bin=yes` on a public transport platform is fine as an attribute even if a separate bin is mapped.

**Comment by davidpnewton** [comment]
Bin=yes et al show there's a bin nearby. The node for the bin itself shows the exact location.

**Comment by nicorikken** [comment]
In the Netherlands I now see new quests for bus stops that exist both as ways and as nodes, causing duplication of effort and data. I already did the quests for the nodes. Not sure yet if I should do the same quests for the ways as well.

**Comment by Helium314** [comment]
See recent discussion in #4690.
SC not only asks for bus stops (`highway=bus_stop`), but also for `public_transport=platform` which may be mapped separately.

**Comment by matkoniecz** [comment]
> which may be mapped separately.

but likely should not be - or should be not described/treated as representing bus stops

**Comment by mnalis** [comment]
> but likely should not be - or should be not described/treated as representing bus stops

I agree it is incorrect if one uses `highway=bus_stop` to map (say) **train** stops.

However, it seems [correct](https://wiki.openstreetmap.org/wiki/Tag:highway=bus_stop#Basic_tags) tagging to map bus stops with both `highway=bus_stop` and `public_transport=platform`. In fact, such PTv2+PTv1 compatibility seems to be quite common:  https://wiki.openstreetmap.org/wiki/Buses#Bus_stops

That being said, I do not see what could be easily done (unless whole of OSM jointly decide to remove PTv1 tagging and go just with PTv2, which seems unlikely [currently](https://taghistory.raifer.tech/#***/public_transport/platform&***/highway/bus_stop)). StreetComplete specific hacks (e.g. trying to ignore `highway=bus_stop` which are near `public_transport=platform`+`bus=yes` would likely be both expensive as well as only exchanging one set of problems for another). 

So I [agree](https://github.com/streetcomplete/StreetComplete/issues/4690#issuecomment-1356919286) that not doing anything (i.e. continue asking asking for duplicate information on "duplicate" OSM elements) seems like the best course of action.

**Comment by matkoniecz** [comment]
> tagging to map bus stops with both highway=bus_stop and public_transport=platform

Though mapping them as single object is preferable if someone really wants to map public_transport=platform


> unless whole of OSM jointly decide to remove PTv1 tagging and go just with PTv2

or drops bad parts of PTv2

**Comment by mnalis** [comment]
> Though mapping them as single object is preferable if someone really wants to map public_transport=platform

The whole reason people map `public_transport=platform` in my region is because they want to indicate a **way** where passengers wait for boarding, instead of a single **node** where the vehicle stops. It makes  sense to me, especially if platform is long (think: trains, trams) to use a way rather than a node... And for buses too in Croatia, as city planners here have a nasty habit of often placing `public_transport=platform` in the middle of `bicycle=designated` paths :cry:   

I always though of [public_transport=stop_position](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_position) (and **not** `public_transport=platform`) of having a closer function to  `highway=bus_stop` (which may also be used only as a **node**)... Although it does not help us here, as `platform` and not `stop_position` is semantically correct place to have `bin=yes|no` etc.

> or drops bad parts of PTv2

Of course (although "modified PTv2" should probably be called PTv3 instead)

**Comment by matkoniecz** [comment]
> I always though of [public_transport=stop_position](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_position) (and not public_transport=platform) of having a closer function to highway=bus_stop

from linked page:

> Use [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) and/or [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) and/or [railway](https://wiki.openstreetmap.org/wiki/Key:railway)=[platform](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform) to identify the place where passengers wait for the service.

**Comment by mnalis** [comment]
>   Use [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) and/or [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) and/or [railway](https://wiki.openstreetmap.org/wiki/Key:railway)=[platform](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform) to identify the place where passengers wait for the service.

I know (hence the disclaimer about it being wrong semantically), what I was trying (unsuccessfully it seems) to explain there is that one cannot use **node** (like `highway=bus_stop`) as a **way** (like `public_transport=platform`), so the only useful solution (if we ignore unrealistic removing of all `highway=bus_stop` from the map) is status quo - i.e. continue to ask for same things twice (annoying as that may be, just like in https://github.com/streetcomplete/StreetComplete/issues/3407).

**Comment by matkoniecz** [comment]
Another options are to drop `public_transport=platform`, map both as an area, map both as node.
