### ISSUE TITLE
few Street Parking strings are not translatable

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4342]
The overlay name itself is not translatable, as well as the "street width"
See screenshots below, I use my phone in German.
There are no strings on POEditor with the respective strings.

----

![image](https://user-images.githubusercontent.com/92865620/188201280-d6cee0ac-78a8-48be-a92a-e3c6b4a17eef.png)
![image](https://user-images.githubusercontent.com/92865620/188201363-0de3adc5-781b-4f2d-b6ff-f5ce2f797b6e.png)

----

**How to Reproduce**
Turn language in something other than English, use Street Parking Overlay

**Expected Behavior**
strings should be translatable using POEditor

**Versions affected**
v47.0-alpha1

**Comment by westnordost** [comment]
added
