### ISSUE TITLE
Mehrfachabfrage in Version 46.0

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4345]
Ich habe das Gefühl, dass in der Version in der aktuellen Version 46.0 sich einzelne Abfragen beliebig oft wiederholen lassen. (Manchmal(!) kommt dabei die Abfrage: „Sicher? Diese Antwort stimmt nicht dem überein, was bereits für diese Straße kartiert ist. . .

**Comment by matkoniecz** [comment]
That is #4105 and happens when given `surface` answer and already present `tracktype` mismatch

**Comment by legofahrrad** [comment]
Hier nochmal eine Antwort auf deutsch:
Wenn für einen Weg ein weicher `tracktype` (Antwort aus *"Wie gut ist dieser Weg befestigt?"*) eingetragen ist, aber dann mit der Frage *"Welche Oberfläche hat dieser Straßenabschnitt?"* eine feste Oberfläche wie z. B. Asphalt eingetragen wird, dann beschwert sich StreetComplete neuerdings, da sich die beiden Informationen widersprechen. Ein Weg kann keinen "weichen Untergrund", aber Asphalt als Oberfläche haben.
Durch das Bestätigen, dass der Weg eine Oberfläche aus Asphalt hat, entfernt StreetComplete dann die Info über den weichen `tracktype`. Dadurch kommt die Frage *"Wie gut ist dieser Weg befestigt?"* dann erneut. Dort solltest du dann mit z. B. "Befestigt" antworten, wenn der Weg aus Asphalt ist. Danach sollte dann keine "Mehrfachabfrage" entstehen.

**Comment by OpenGreenStreet** [comment]
Danke für die deutsche Erklärung! Das Phänomen hatte ich heute zum aller erste mal (und dann gleich mindestens in drei verschiedenen Situationen).

Im konkreten Fall habe ich, weil gefragt wurde, als Oberfläche „Kiesel“ gewählt und werde anschließend gefragt: „wie gut ist der Weg befestigt?“ Ich wähle dann „Befestigt“ und anschließend geht es wieder von vorne los.
Beispiel: https://www.openstreetmap.org/changeset/125734097 (Sorry, zum Nachvollziehen habe es sehr oft durchgespielt?)

**Comment by legofahrrad** [comment]
"Kiesel" wird eben als "unbefestigte Oberfläche" angesehen und damit auch in Widerspruch mit "Befestigt" gestellt. Dadurch kommt es dann eben zu der "Endlosschleife".

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/65265244/history - do you have photo of this way? Not sure whether `surface` or `tracktype` quest is confusing (or maybe German translation), but [surface](https://wiki.openstreetmap.org/wiki/Key:surface?uselang=en)=[pebblestone](https://wiki.openstreetmap.org/wiki/Tag:surface=pebblestone?uselang=en) + [tracktype](https://wiki.openstreetmap.org/wiki/Key:tracktype?uselang=en)=grade1 tagging is self-contradictory

**Comment by OpenGreenStreet** [comment]
Photo: https://westnordost.de/p/111045.jpg

**Comment by legofahrrad** [comment]
![grafik](https://user-images.githubusercontent.com/92865620/188276731-6b0fbac2-50fd-4f72-bf2a-78e90ab1ce43.png)
https://www.openstreetmap.org/note/3343969

For me, this looks like
```
surface=gravel
smoothness=bad
tracktype=grade2
```
Though the track is surrounded by paths only, so I would go with `highway=path` here too and thus don't tag `tracktype`.

**Comment by OpenGreenStreet** [comment]
Was wäre das in StreetComplete auf Deutsch?

Hier in Oberbayern sehen die meisten Forstwege so oder ähnlich aus:
https://commons.wikimedia.org/wiki/File:Kieselweg_2.jpg
https://commons.wikimedia.org/wiki/File:Kieselweg_3.jpg

Für mich kam in StreetComplete „Kiesel“ am nächsten. (Die Wege sind grundsätzlich befestigt aber die oberste Schicht ist loser Kiesel.)

**Comment by legofahrrad** [comment]
Ich weiß ja nicht, aber ich finde das sieht alles eher nach Schotter aus ;)
Kiesel sind für mich wirklich runde/ovale, eher große Steine. Wie hier zum Beispiel: https://commons.wikimedia.org/wiki/File:Path_made_of_loose_pebblestones_no1.jpg

**Comment by OpenGreenStreet** [comment]
hm, habe ich nicht so gesehen: Schotter ist für eher das, was die Bahn verwendet, vielleicht etwas feiner aber lose. Diese Wege sind aber sehr fest, fast wie Beton, aber Beton ist es definitiv auch nicht.
Wäre denn Schotter ein fester Weg?

**Comment by OpenGreenStreet** [comment]
Zitat: >> "Kiesel" wird eben als "unbefestigte Oberfläche" angesehen und damit auch in Widerspruch mit "Befestigt" gestellt. << könnte StreetComplete die Widerspruch nicht unterbinden (nicht zulassen)?

**Comment by legofahrrad** [comment]
https://commons.wikimedia.org/wiki/File:Gravel_farm_track.jpg
Das wäre auch `surface=gravel`, also Schotter aus meiner Sicht.

**Comment by OpenGreenStreet** [comment]
Okay und Danke, dann wähle ich bei nächster Gelegenheit Schotter.

**Comment by OpenGreenStreet** [comment]
Bliebe der Wunsch, dass StreetComplete möglich Widersprüche bei den Oberflächen abfangen würde

**Comment by Hanneska** [comment]
> Photo: https://westnordost.de/p/111045.jpg

Für mich sieht das eher nach `surface=compacted` aus, also verdichtet. https://wiki.openstreetmap.org/wiki/DE:Tag:surface%3Dcompacted

**Comment by OpenGreenStreet** [comment]
@Hanneska danke für Deine Rückmeldung. Welcher Oberflächentyp wäre dies in StreetComplete?

PS: beruhigend, dass es unterschiedliche Ansichten dazu gibt :-)

**Comment by Hanneska** [comment]
Die Oberfläche heißt ganz einfach Verdichtet.
![Screenshot_20220904-121247](https://user-images.githubusercontent.com/77938148/188308472-1d01be50-f6d3-4b45-9d3c-7a43f0c65ebc.png)

**Comment by OpenGreenStreet** [comment]
@Hanneska : okay, herzlichen Dank und viele Grüße

**Comment by westnordost** [comment]
> Bliebe der Wunsch, dass StreetComplete möglich Widersprüche bei den Oberflächen abfangen würde

Tut es ja. Du meinst damit aber vermutlich, dass die App eine widersprüchliche Antwort garnicht erst zulassen sollte.
Aber es kann ja immer sein, dass der bisher erfasste Wert falsch war oder sich mittlerweile geändert hat. Daher ist das, was der Nutzer **jetzt** antwortet tendenziell immer richtiger und aktueller als was vorher erfasst wurde. Insofern macht es keinen Sinn, Antworten auf Basis des vorherig erfassten Wertes auszublenden.

Übrigens, das oben abgebildete Foto würde ich mit "Feiner Splitt" (`surface=fine_gravel`) beantworten. Ich bin mir nicht sicher ob die deutsche Übersetzung von "Fine gravel" präzise ist, ich würde es einfach "Kies" nennen, wie der Kies auf einer Auffahrt oder auf einem Kiesweg. Sicherlich gibt es da regionale Unterschiede wie man das benennt.
Der Unterschied zwischen "Verdichtet" und "Feiner Splitt" ist aber ohnehin klein, als Faustregel verwende ich: Wenn da (viele) lose Steinchen sind, nehme ich "Kies", wenn sie (zumeist) festgetreten sind, nehme ich "Verdichtet". Ersteres ist in der Regel auf dünnen Reifen schwieriger zu durchqueren als letzteres.

---

Was das Ticket hier insgesamt angeht: Liege ich richtig, dass der Auslöser für die Verwirrung war, dass "befestigt" als "irgendeine Form eines menschengemachten Weges" interpretiert wurde?

**Comment by OpenGreenStreet** [comment]
Hi Tobias,danke für Deine Rückmeldung.Ich glaube, dass „verdichtet“ der Sache in den bayerischen Bergen am Nächsten kommt.Der Auslöser der Tickets war die Endlosschleife: ich konnte die Abfrage(n) beliebig oft wiederholen. Zur Verifizierung habe ich das mindestens drei mal durchgespielt.---Mit freundlichen Grüßen Armin KrejsaTel.: +4933414200464Mail: ***@***.***: Metager_________________Stromspeicherung (Power-to-X) und 100% Erneuerbare Energien für eine sichere, importunabhängige & brennstoffkostenfreie Energieversorgung | regionale Arbeitsplätze, Demokratie & Wertschöpfung | Frieden & Klimaschutz-100 Prozent Erneuerbare Energien so schnell als möglich: Eurosolar | Deutsche Gesellschaft für Sonnenenergie (DGS) | Solarenergie-Förderverein Deutschland (SFV)Am 04.09.22 um 15:57 schrieb Tobias Zwick
                
            
            
                
                    Von: "Tobias Zwick" ***@***.***>Datum: 4. September 2022An: "streetcomplete/StreetComplete" ***@***.***>Cc: "Author" ***@***.***>,"OpenGreenStreet" ***@***.***>Betreff: Re: [streetcomplete/StreetComplete] Mehrfachabfrage in Version 46.0 (Issue #4345)
                
                



Bliebe der Wunsch, dass StreetComplete möglich Widersprüche bei den Oberflächen abfangen würde



Tut es ja. Du meinst damit aber vermutlich, dass die App eine widersprüchliche Antwort garnicht erst zulassen sollte.

Aber es kann ja immer sein, dass der bisher erfasste Wert falsch war oder sich mittlerweile geändert hat. Daher ist das, was der Nutzer jetzt antwortet tendenziell immer richtiger und aktueller als was vorher erfasst wurde. Insofern macht es keinen Sinn, Antworten auf Basis des vorherig erfassten Wertes auszublenden.

Übrigens, das oben abgebildete Foto würde ich mit "Feiner Splitt" (surface=fine_gravel) beantworten. Ich bin mir nicht sicher ob die deutsche Übersetzung von "Fine gravel" präzise ist, ich würde es einfach "Kies" nennen, wie der Kies auf einer Auffahrt oder auf einem Kiesweg. Sicherlich gibt es da regionale Unterschiede wie man das benennt.

Der Unterschied zwischen "Verdichtet" und "Feiner Splitt" ist aber ohnehin klein, als Faustregel verwende ich: Wenn da (viele) lose Steinchen sind, nehme ich "Kies", wenn sie (zumeist) festgetreten sind, nehme ich "Verdichtet". Ersteres ist in der Regel auf dünnen Reifen schwieriger zu durchqueren als letzteres.



Was das Ticket hier insgesamt angeht: Liege ich richtig, dass der Auslöser für die Verwirrung war, dass "befestigt" als "irgendeine Form eines menschengemachten Weges" interpretiert wurde?

**Comment by westnordost** [comment]
Ok, nun, dann denke ich kann das hier geschlossen werden.
