### ISSUE TITLE
add overlay for disability editing

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#4349]
**Use case**
There are many datas in OpenStreetMap but while walking we need a way to gather in a logical way the physical answers for people using wheelchair, blind people...
The website named wheelmap only displays POI : we can do more.

**Proposed Solution**

Create a specific rendering (green,yellow, red...) that would do the same than the sidewalk overlay but more focused on details and quality of the path. By this way we would gather the quests that are spred.
- footway, sidewalks
- kerbs
- entrance
- crossing
- elevator
- ramp
- steps

I'm trying something in OSMdata [here](https://demo.openstreetmap.fr/map?profil=10&layers=653,37,layer;718,37,layer;731,37,layer;728,60,layer&pos=4.8112,44.1356,17)
![image](https://user-images.githubusercontent.com/4929752/188300544-d6946596-b0b0-4b94-928f-f0d9553792ea.png)

![image](https://user-images.githubusercontent.com/4929752/188300647-ee157b94-577e-44ec-945e-e320f148e002.png)
![image](https://user-images.githubusercontent.com/4929752/188300985-7a5feab8-de0b-4195-ada2-890c5c34d373.png)

**Comment by westnordost** [comment]
The feature request does not match with what overlays are. The "thematic openstreetmap editing" is more of a thing for MapComplete or MapContrib. An overlay that shows "*things*" for crossings, kerbs, ramps, steps,... that's not how it works. There are quests for that. Overlays just show **one aspect** (e.g. maxspeed) of the data, not anything related to a certain use case (e.g. anything car-routing-related).

By the way, what is this "OSM DATA" application? Is there an English translation? Is it open source? It looks really interesting!
