### ISSUE TITLE
Map jerky

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4350]
When i walk with StreetComplete open, map is jerky

**How to Reproduce**
- Open StreetComplete
- Enable GPS
- Walk with StreetComplete open -> Map jerky

**Expected Behavior**
Like in v46.0, map is fluid

**Versions affected**
v47.0-alpha1 - Android 13

**Comment by westnordost** [comment]
v46 is the same as v47-alpha1 only that v47-alpha1 has added the parking overlay. You mean it is jerky if you have that overlay active? Otherwise I must stem from something else.

**Comment by Jean-BaptisteC** [comment]
I have try today (with and without overlay) on the same road, i'm not able to reproduce.
I'm remember map be jerky after gps can't get location.

**Comment by westnordost** [comment]
Okay, I am also not able to reproduce any jerkyness when the location is unknown. Generally, the map should be a bit jerky while the quests are loading to appear on the map (i.e. after download, but also after opening the app and scrolling around as it loads the data from the local database)

**Comment by Helium314** [comment]
> I'm remember map be jerky after gps can't get location.

I noticed that too. If you didn't get a location at all since start of the app, something is using CPU a lot.
