### ISSUE TITLE
Is it necessary to make a reservation to visit this place? [add `reservation=*`]

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4351]
### General
Affected tag(s) to be modified/added: [reservation=*](https://wiki.openstreetmap.org/wiki/Key:reservation)
Question asked: **Is it necessary to make a reservation to visit this place?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- - oftentimes signs in the window, either with "no appointment needed!" or "call 12345678 to make an appointment!"
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
- - there are many restaurants, shops, etc. where the information is missing

### Ideas for implementation

**Element selection:** 
ask for example on
- `shop=hairdresser` or
- `amenity=restaurant`

**Metadata needed:** 
none, I guess

**Proposed UI:**
Just text answers with radio boxes, similar to seating quest

**Answer options:**
- `reservation=required` Reservation is required
- `reservation=yes` Reservation is possible but not necessary
- `reservation=no` Reservation is not possible

**Comment by westnordost** [comment]
I do not think this is a property that is sufficiently verifiable and surveyable on-site.

You write that oftentimes there will be signs like "no appointment needed!" or "call 12345678 to make an appointment!" but even more often, there will be no signs like that. A quest could always work if a sign can be expected pretty much *always*. I for one have never seen a sign that said "Reservation is possible but not necessary". And especially with documented values like `reservation=recommended`, it really becomes very fuzzy, as depending on the time and date and (current) popularity of the place, it may be recommended or not to reserve in advance.

Overall, I very much doubt the usefulness of that tag overall.
