### ISSUE TITLE
Parking overlay parsing not working correctly for parking:condition:both

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4353]
The parsing of the "new style tagging" `parking:condition` tag does not correctly identify a possible `parking:condition:both` value. Instead, it only identifies values set explicitly for the respective side (i.e. either `parking:condition:left` or `parking:condition:right`). The following code is only called with the `side` parameter set to `left` and `right`. Additionally, judging only by the code, the problem may also occur for the `parking:lane:both` key.

https://github.com/streetcomplete/StreetComplete/blob/1cc0d3338ce94e2ee6c0f66c99a58babf5826df1/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingParser.kt#L23-L41

**How to Reproduce**
For example, find street tagged with `parking:lane:both=no` and `parking:condition:both=no_stopping`. See that the app shows the `NoStreetParking` and not the `StreetStoppingProhibited` icon and stings.

**Expected Behavior**
Correctly parse `:both` values.

**Versions affected**
[v47.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v47.0-alpha1)

**Comment by legofahrrad** [comment]
I can reproduce; When adding "no stopping" to both sides and then clicking on the street again, it just says "no parking lane" (without taking *:condition into account)

**Comment by westnordost** [comment]
Thanks for the report! Since you already identified the culprit, would you like create a PR for fixing it?

**Comment by westnordost** [comment]
Ok np
