### ISSUE TITLE
"OSM Then and Now" is offline, should be removed…

### ISSUE THREAD

**Issue by eliasp** [streetcomplete/StreetComplete#4354]
**How to Reproduce**
- Open "My Profile"
- Go to "Link Collection" tab
- Open "OSM Then and Now"
- Find the message:
  > OSM then and now is no longer hosted here. If you're interested in hosting it, please see https://github.com/mvexel/thenandnow and let me know, so I can add a link or redirect from this place.
  > Goodbye

**Expected Behavior**
Find a website allowing me to compare OSM "then" to "now"

**Versions affected**
v46.0

I think all that has to be done is to revert 0f3bf77206d1345a0440ddd6aaf24d4f04321cca

**Comment by westnordost** [comment]
Hmpf, too bad
