### ISSUE TITLE
Parking overlay missing on tunnel segments

### ISSUE THREAD

**Issue by SupaplexOSM** [streetcomplete/StreetComplete#4355]
The new parking overlay (tested with v47.0-alpha1) is not displayed on road sections that are tagged with `tunnel=*` (but the road sections are still selectable). This is quite unfortunate here, as these street segments are independent from others and are therefore "forgotten" if you do not explicitly click on the "empty" space. I first thought it might have something to do with #4310, but it doesn't only affect segments under buildings (building_passage).

![SCparking_overlay_tunnel](https://user-images.githubusercontent.com/66696066/188335323-b2ab41ff-a6bd-46f7-b3fd-49ad637fb936.jpg)

Examples: [w186397837 - under building, tunnel=yes](https://www.openstreetmap.org/way/186397837), [w777345611 - under building, tunnel=building_passage](https://www.openstreetmap.org/way/777345611), [w31349228 - no building, tunnel=yes](https://www.openstreetmap.org/way/31349228) or probably any other road section with `tunnel=*`.

btw: Once again, it's a well-done new feature, and it allows the mapping of parking lanes in an amazingly fast and intuitive (and, thanks to the splitting option, adequately accurate) way!

**Comment by westnordost** [comment]
This is deliberate. Roads on which any parking is not expected (i.e. data consumers might want to default to "no" for these) the outline is not displayed if it is not set. But if there actually **is** parking, the app lets you define it (and well, also if there is none, but the point is that it is not shown as missing in these cases). Currently, these are

```kotlin
highway ~ service|pedestrian
or motorroad = yes
or expressway = yes
or junction = roundabout
or tunnel and tunnel != no
or bridge and bridge != no
or ~${(MAXSPEED_TYPE_KEYS + "maxspeed").joinToString("|")} ~ .*rural.*
or maxspeed >= 70
```

**Comment by SupaplexOSM** [comment]
Ok, but that is - at least for this quest - not a good idea for tunnels and bridges in my opinion. At least in urban contexts, the default there might not be "no". (And outside of urban contexts, roadside parking has little relevance.)

**Comment by westnordost** [comment]
Parking in tunnels? Where?

**Comment by SupaplexOSM** [comment]
Most "tunnels" in citys in OSM are not real tunnels - we seem to define the term very broadly. If I take a look to the tunnels I can find with Overpass in my hometown Berlin, then 85% are "building passages" (and the road/its width/it's parking lane usually does not change. I think this will be the case in many cities). Furthermore there are those tunnels that are more like "roads under wide bridges", see e.g. my third example above: [OSM](https://www.openstreetmap.org/way/31349228) | [Mapillary](https://www.mapillary.com/app/?pKey=504291151507706).

**Comment by HolgerJeromin** [comment]
Should better be covered=yes imo. But they exist...

**Comment by westnordost** [comment]
Ok, I removed tunnel and bridge from that filter. It is still quite uncommon, but especially if many `tunnel=building_passage` are actually (less precisely) tagged as `tunnel=yes`, I guess it makes sense to include.
