### ISSUE TITLE
Street Name quest should always show `addr:housenumber` (if it is tagged)

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4356]
**Use case**
At the moment https://www.openstreetmap.org/way/547023483 is asking '**What street is this on?**' for '**Adina Apartment Hotel Sydney Town Hall** (_Hotel Building_)', but is not indicating that it is tagged as `addr:housenumber` of 511. Without knowing the number when surveying on-site, it can be difficult to work out which street it is referring to.

**Proposed Solution**

Always show the `addr:housenumber` in the Street Name quest, even if the object also has a name.

**Comment by westnordost** [comment]
It's now (for street address quest only):

> house number 511: **Adina Apartment Hotel Sydney Town Hall** _(Hotel Building)_

(`house number: name (feature name)`)

and just on the other side:

> house name _St Andrews House_ - on floor 5: **Australian Bureau of Statistics New South Wales Division** _(government office)_

(`house number - floor: name (feature name)`)
