### ISSUE TITLE
stop asking for lanes on private roads

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4359]
https://github.com/streetcomplete/StreetComplete/blob/0d5871123928169e6aac1477fe60f4cf3fd1b7dd/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L12-L24

The filter doesn't include `access !~ private|no`, but it actually should.

**Comment by westnordost** [comment]
By the way, since you already are proficient where to look in the code, you are welcome to create a PR. Then, your name will also appear in the credits etc

**Comment by HolgerJeromin** [comment]
You can also add his name to the commit:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by westnordost** [comment]
Only code contributors are mentioned in the credits
