### ISSUE TITLE
Multiple history entries for the same quest in the history sidebar

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#4365]
I managed to create multiple history entries for the same quest and object. Sadly, I didn't record a screen video.
In this state, I undid the first answer. The quest didn't show up again (as expected). Then I undid the second answer and the quest showed up again. As far as I remember the answers were the same. I don't remember answering the quest twice but my memory is hazy on this. I do remember I was closing and opening the dialog again at least once.

<img src="https://user-images.githubusercontent.com/3404787/189413108-ffffeabe-d8e5-4ffb-9d63-c05ea4b7d553.png" height="250" />

*@matkoniecz on Slack*
> You can recreate it when emulator lags (managed today to answer 10 times to a single question - though that was using overlay, but I am pretty sure that I did it also with a quest)

**How to Reproduce**
I don't know how to reproduce it.

**Expected Behavior**
Only a single entry is created.

**Versions affected**
StreetComplete 45.2

**Comment by westnordost** [comment]
This has nothing to do with the history sidebar. You answered the same quest twice, which was possible only due to #4258

**Comment by matkoniecz** [comment]
Not sure is it really the same - https://github.com/streetcomplete/StreetComplete/issues/4258 describes situation where interface closed and quest has not disappeared.

This one is about case where one may answer quest (or trigger undo) and do this again, before quest interface disappears.
