### ISSUE TITLE
Öffnungszeiten (speziell bei Arztpraxen): „nach Vereinbarung"

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4368]
Aus meiner Sicht wäre es wünschenswert, wenn man, speziell bei Arztpraxen, bei den Öffnungszeiten „nach Vereinbarung" auswählen/hinterlegen könnte.
Beispiele:
https://www.google.de/imgres?imgurl=https%3A%2F%2Fwww.drjubitzlottholz.de%2Findex_htm_files%2F16554%402x.png&imgrefurl=https%3A%2F%2Fwww.drjubitzlottholz.de%2F&tbnid=ZIL_7aKZyI_weM&vet=12ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygUegUIARDOAQ..i&docid=AyvsVSQt3m0UPM&w=1202&h=1202&q=sprechzeiten%20nach%20vereinbarung&ved=2ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygUegUIARDOAQ

https://www.google.de/imgres?imgurl=https%3A%2F%2Fhasenleiser.net%2Fwp-content%2Fuploads%2F2021%2F05%2Fhallo-750x410.png&imgrefurl=https%3A%2F%2Fhasenleiser.net%2Fspe%2F&tbnid=loc_0Z3kY21W3M&vet=12ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygCegUIARCqAQ..i&docid=bsUUH_xt-3R8wM&w=750&h=410&itg=1&q=sprechzeiten%20nach%20vereinbarung&ved=2ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygCegUIARCqAQ

https://commons.wikimedia.org/wiki/File:ESA_EichrodterWeg48a_Bild2.jpg

So etwas lässt sich aus meiner Sicht nicht in SC beantworten.

Ich würde mir die Option(en) "Nach Vereinbarung" grundsätzlich und/oder für bestimmte Wochentage wünschen.

**Comment by legofahrrad** [comment]
Weitere Antworten → Keine regelmäßigen Öffnungszeiten → *nach Vereinbarung* eintippen

**Comment by OpenGreenStreet** [comment]
@legofahrrad : Danke für Deinen Hinweis. Frage: Kann ich auch eine Kombination eingeben? (Wie im Beispiel: Mo.-Do.: reguläre Öffnungszeiten und Freitag „keine regelmäßigen Öffnungszeiten“ hinzufügen) Oder muss ich dann gleich mit „keine regelmäßigen Öffnungszeiten“ beginnen und das ganze Schild abtippen? Das fände ich zu aufwendig.
Ich hätte mir gewünscht, dass ich über das Hinzufügen eines Wochentages im regulären Menü „nach Vereinbarung“ auswählen könnte statt eine Zeitspanne angeben zu müssen.

(Nebenbei: im Urlaub habe ich Öffnungszeitenschilder gesehen auf denen ungewöhnlicherweise ein offener Beginn vermerkt war: bei einem Bäcker: unter der Woche von 5 bis 17 Uhr und Sa. u. So.: bis 11 Uhr (ohne Beginn))

**Comment by legofahrrad** [comment]
*nach Vereinbarung* kann mit SC nur für "alle Zeiten" angegeben werden, nicht wie in deinen Beispielen nur für freitags etc.
Dafür müsstest du dann auf einen anderen Editor als SC zurückgreifen oder noch einfacher: einen Hinweis hinterlassen.

Das Tagging sollte für dein erstes Beispiel dann folgendermaßen aussehen:
```
opening_hours=Mo,Tu 13:00-19:00; We,Th 08:00-13:00; Fr "nach Vereinbarung"; Sa,Su,PH off
```
Im Falle von festen Öffnungszeiten, man aber trotzdem einen Termin braucht, kommen diese senkrechten Striche zum Einsatz "||". (bspw. `Fr 08:00-19:00 || "nach Vereinbarung"`)

---

> (Nebenbei: im Urlaub habe ich Öffnungszeitenschilder gesehen, auf denen ungewöhnlicherweise ein offener Beginn vermerkt war: bei einem Bäcker: unter der Woche von 5 bis 17 Uhr und Sa. u. So.: bis 11 Uhr (ohne Beginn))

Bei diesem Beispiel würde ich davon ausgehen, dass die Anfangszeit von unter der Woche auch am Wochenende gilt, da nichts anderes angegeben ist.
Aber generell ist das Angeben von einem offenen Anfang nicht möglich.

Dazu nochmal hier ein Beispiel: https://www.openstreetmap.org/node/9642736212
Die Toiletten sind ab 16 Uhr geschlossen, haben aber auch keine Anfangs-Öffnungszeit angegeben.

**Comment by OpenGreenStreet** [comment]
@legofahrrad hab‘ Dank für Deine detaillierte Rückmeldung. Ich arbeite lieber mit SC habe aber auch Vespucci als Alternative. (Das ist für mich aber nur zweite Wahl, weil es nich so schnell damit geht und man sich die Syntax merken muss . . .) Deshalb dieser Vorschlag hier.

**Comment by westnordost** [comment]
This is a duplicate of #3025. Reasons why it is not planned to be implemented (and a possible way forward for those inclined and able to invest coding-time into) are described there.
