### ISSUE TITLE
Quest suggestion: Does this poop bag dispenser have a trash can?

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#4370]
### General
Affected tag(s) to be modified/added: [`bin`](https://wiki.openstreetmap.org/wiki/Key:bin)
Question asked: **Does this poop bag dispenser have a trash can?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Links

* https://taginfo.openstreetmap.org/tags/vending=excrement_bags#combinations
* https://wiki.openstreetmap.org/wiki/Tag%3Avending%3Dexcrement_bags

### Ideas for implementation

**Element selection:**

```
nodes with
  vending = excrement_bags
  and (!bin or (bin = no and bin older today -12 years))
```

**Metadata needed:** None

**Proposed UI:** Simple Yes/No quest

**Comment by Lukas458** [comment]
Basically useful, but sometimes the trash_can is also mapped separately as amenity=waste_basket. In addition, the question would be whether only those garbage cans that are ONLY intended for dog excrement are considered "trash_can" or all garbage cans (which are located, for example, below the dog waste bag dispenser).

I think it's more likely the latter would be the case.

So I would definitely rule out anyone with an amenity=waste_basket in the immediate vicinity.

**Incidentally, I also find that everything that can be displayed with two nodes next to each other does not always have to be tagged twice, just because it often appears in reality as two objects standing next to each other.**

Bench and waste_basket are also ift next to each other, for example.

Will we soon be tagging every amenity=bench withbin=yes/no and every amenity=waste_basket with bench=yes/no?

**Comment by dbdean** [comment]
It may also be useful to ask the reverse: Does this dog waste bin have a poop bag dispenser? At least in my area, I've been mapping the bins, and not bothering to map the bag dispensers (under the assumption that most dog waste bins will have them).

At the moment, about 14K waste baskets are mapped as for dog waste, and 1.3K are tagged with having dog waste bags: https://taginfo.openstreetmap.org/tags/waste%3Ddog_excrement#combinations

**Comment by Lukas458** [comment]
Some people may use two nodes for this, as there are two amenities: One _amenity=waste_basket_ (with _waste=dog_excrement_, if so), and another with _amenity=vending_machine_ and _vending=excrement_bags_.

We should definitely keep that in mind when asking about it.

And what if there is a "normal" garbage can for any kind of garbage? (mostly tagged with amenity=waste_basket withour any _waste=*_ - tag)

**Comment by dbdean** [comment]
We can show both nodes when asking the question, and have a 'mapped separately' answer (but is there accepted tagging for that?). Also, they may often be too close together to really see the other node as well.

**Comment by haansn08** [comment]
It is likely that in any given city, all poop bag dispensers will have the same `bin=*` value.

**Comment by Helium314** [comment]
In my experience: no it is not

**Comment by Lukas458** [comment]
>We can show both nodes when asking the question, and have a 'mapped separately' answer (but is there accepted tagging for that?).

It ***could*** be using the value "separate", so bin=separate. But I think it's not the sense or mission of SC to give re-answer for things which are mapped already.

Anyway, I think that if both objects are available, both are already mapped very well - either with one or with two nodes.

If anything, it should really only be asked for the vending=excrement_bags where there is neither bin=yes nor an amenity=waste_basket nearby.

**Comment by qugebert** [comment]
I would try this next, if it is fine.

But some questions open:
What should be the maximum distance of nearby bins that would disable the quest?
And should it be a simple yes/no - Question or RadioButton with 
- Yes, general bin
- Yes but only for excrement bags
- No

**Comment by westnordost** [comment]
Hmm, I am not really sold on the usefulness to tag this and @FloEdelmann didn't provide any explanation.

Data users looking for waste bins will only look for `amenity = waste_basket`. To expect that someone (an app, a program or a person) looking for waste baskets should also look for many more features `+ bin=yes` seems unrealistic to me. Hence, when there is both a poop bag dispenser and a waste basket on the same pole, what makes more sense is to [map them as two features](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element).

Why then have `bin=*` on bus stops? For data users that are looking to display or to analyze the *features* the bus stops have, like for example you see the little ♿ icon next to a (subway) stop if it is wheelchair accessible. (IMO) it is still useful to map these bins as separate OSM elements, too.

While already for bus stops, it is a bit of a stretch (I haven't seen maps that display which bus stop has bins), for bins on the same pole (or close to, that is) as poop bag dispensers, it sounds even less useful.

From the information I have now, the only thing I could think of which could make this information useful if the "poop bag trash can" is not a proper trash can and it is somehow clear that it should only be used for these bags.

**Comment by qugebert** [comment]
I have no strong opinion on this, just thought this would be a easy open todo to finish.

**Comment by Elefant-aus-Wuppertal** [comment]
> (IMO) it is still useful to map these bins as separate OSM elements, too.

👍 

> From the information I have now, the only thing I could think of which could make this information useful was if the "poop bag trash can" is not a proper trash can and it is somehow obvious that it should only be used for these bags.

This would be shown on a separate object by tagging `waste=*`:

`amenity=waste_basket`
`waste=dog_excrement`.

**Comment by westnordost** [comment]
Oh well, no reply from issue creator, so I'll close this.
