### ISSUE TITLE
Ask the entrance type question also when a staircase ends at a building

### ISSUE THREAD

**Issue by Sorunome** [streetcomplete/StreetComplete#4372]
The new entrance type question is currently asked when e.g. a pedestrian path terminates at a building. Ask for it also if a staircase terminates at a building, as (over here at least), it is common to have small stair cases right before the entrance of e.g. an apartment block

**Comment by matkoniecz** [comment]
If it makes sense to ask about entrances where incoming way is `highway=pedestrian` it also can be added.
