### ISSUE TITLE
“This store was long vacant, what is there now?” Answer: it’s still vacant

### ISSUE THREAD

**Issue by Freso** [streetcomplete/StreetComplete#4373]
Right now I get three possible answers for the “This store was long vacant, what is there now?” quest:
1. Add the type of shop/place that is now there
2. That it’s closed for the season (could be bad Danish translation?)
3. "Something else (leave a note)"

The shop in question is still unused/vacant and has been since I added it. Maybe answer 2 is for this but the Danish translation is awkward? But if it’s not the fault of Danish localisation, then I feel like there should be a possibility to answer that it’s (still/again) vacant.

**Comment by legofahrrad** [comment]
![Screenshot_20220912-185300](https://user-images.githubusercontent.com/92865620/189712188-ed630510-1d5b-451b-8965-8f777dc57691.png)
 Option 2 is the option you're looking for

**Comment by FloEdelmann** [comment]
Note that you can improve translations yourself :)

See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by Freso** [comment]
Submitted a fixed (or better at least) translation. Thanks!
