### ISSUE TITLE
Add Every Door to the link collection list

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4377]
Version 2.0 has recently been released, so I think it can already be added to the collection of links.
https://github.com/Zverik/every_door
https://every-door.app

**Comment by westnordost** [comment]
Yeah, it's an app I would definitely recommend to people. However, I'd like to wait some time before including it in the link list as there have been many (cool) POI editors around which didn't stand the test of time, i.e. didn't really gain traction.

**Comment by westnordost** [comment]
So I have this list on my computer with links to things I will maybe include in the link list sooner or later. I just added it. This ticket, I will close for now.

**Comment by mnalis** [comment]
https://wiki.openstreetmap.org/wiki/Editor_usage_stats might came in handy when deciding

**Comment by westnordost** [comment]
Every Door (for the very least) jump-started with more users than is closest equivalent, OSM Go!, acquired ober 4 years

On September 17, 2022 2:35:01 AM GMT+02:00, Matija Nalis ***@***.***> wrote:
>https://wiki.openstreetmap.org/wiki/Editor_usage_stats might came in handy when deciding
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4377#issuecomment-1249960008
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by deevroman** [comment]
Of course, because Every Door is available for Android and iOS unlike Go Map!!

**Comment by mnalis** [comment]
Hopefully EveryDoor will manage to fix their non-free dependency problem too, so it becomes available on F-droid too https://github.com/Zverik/every_door/issues/167

**Comment by westnordost** [comment]
I meant OSM Go!, not GoMap!!

**Comment by deevroman** [comment]
Sorry🤦‍♂ how they seem to be named:)
