### ISSUE TITLE
Problem with F-droid builds

### ISSUE THREAD

**Issue by mpeter50** [streetcomplete/StreetComplete#4379]
This is not a bug in the app, but a problem related to the project.

**How to Reproduce**

1. Open an F-droid client
2. Search for StreetComplete
3. Open StreetComplete's store page
4. Open the previous versions dropdown

**Expected Behavior**

I expected to find recent versions of StreetComplete in the previous versions dropdown, but only 40.2 and older are available, from February.
It looks like F-droid currently offers 40.2 as the latest version, for some reason.

**Versions affected**

Not applicable.

**Additional notes**
The problem must have happened somewhat recently, as I have installed StreetComplete 45.2 from F-droid when it became available.

**Comment by FloEdelmann** [comment]
This is unfortunately on purpose currently, and caused by https://github.com/streetcomplete/StreetComplete/issues/4289

**Comment by mpeter50** [comment]
Oh, I see. Thanks for letting me know.

**Comment by mnalis** [comment]
Now that this has been worked around, newest StreetComplete `v47.0` is available on f-droid
