### ISSUE TITLE
AddEntrance asked for paths on top of underground building

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4381]
**How to Reproduce**
Scan for quests near https://www.openstreetmap.org/way/157711824 and see entrance quests, but there is no building visible.

**Expected Behavior**
No entrance quest, because paths are above the building. Probably it could be avoided when excluding buildings with `layer=-1` or `location=underground`

**Versions affected**
SC 47.0-alpha1

**Comment by westnordost** [comment]
@matkoniecz will you take care of this?
