### ISSUE TITLE
`building:part=house` should get the same quests as `building=house`

### ISSUE THREAD

**Issue by endim8** [streetcomplete/StreetComplete#4388]
Currently, `building:part=house` is ignored by streetcomplete, when it should receive the same quests as `building=house`

wiki description: https://wiki.openstreetmap.org/wiki/Tag:building%3Dterrace#How_to_map

**How to Reproduce**
example way: https://www.openstreetmap.org/way/554750019

**Expected Behavior**
it should display quests for housenumber, street, etc.

**Versions affected**
46.1

**Comment by westnordost** [comment]
Housenumber, street? No, certainly not. That's the (or, a) point of distinguishing between `building:part` and `building`

With respect, that "third approach" described on that wiki page by Dead10c in 2020 is a really bad idea. Just stick to `building=terrace` if the whole outline is mapped as one building or `building=house + house=terrace` if each house is mapped individually.
It is really not good that not any reference was given on Dead10c's edit - was that discussed? Was this description based on research, i.e. describing current tagging practice? Nobody knows.

**Comment by endim8** [comment]
ah, i didn't realise that it was so unused, less than 10k building:part=house tags.
i'll remove it from the wiki 👍

**Comment by westnordost** [comment]
Well, I guess 10k is not a small number. Still, StreetComplete will only ask for proper buildings, because building parts could be anything, e.g. just some roof or a tower or whatever part of some building, it does not warrant an own housenumber.

**Comment by matkoniecz** [comment]
Note that when asking is only about `building:part=house` (not all `building:part`) then 

> just some roof or a tower or whatever part of some building, it does not warrant an own housenumber

is not actually a problem
