### ISSUE TITLE
In overlay mode, the roads in parking lots are not drawn beautifully

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4389]
**How to Reproduce**
Turn on the parking overlay. 
Find parking lots through which the roads pass. Example `59.4116, 24.64647`
Tilt the map.

![Screenshot_20220918-185809_StreetComplete.jpg](https://user-images.githubusercontent.com/25708359/190916688-6526f47b-19d8-40ae-8180-d175057be83d.jpg)

**Expected Behavior**

**Versions affected**
47.0 alpha 1

**Comment by westnordost** [comment]
Hmm... maybe it would be possible to always render line-features on top of area-features. Or the other way round. Which would make more sense?
