### ISSUE TITLE
New Quest: What kind of fountain is this?

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#4390]
### General
Affected tag(s) to be modified/added: [fountain](https://wiki.openstreetmap.org/wiki/Key:fountain)
Question asked: **What kind of fountain is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
Status: de facto
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
Same list of option as the wiki page shows (including pictures)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
Can be detected in passing.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
Each fountain is individual
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
The tag `fountain` can be added for both `amenity=fountain` and `amenity=fountain`. Worldwide there are over 150k fountains and 250k drinking_water but only ~6k fountain=*.

### Ideas for implementation

**Element selection:** 
```
nodes, ways, relations with
)
          amenity=drinking_water
          or amenity=fountain
)
          and (!fountain)
```

**Proposed UI:**

The quest is technically identical with "What kind of memorial is this?" #4102, #1572 
Currently there are 10 possible tagging options.

If technically possible, quest could display only the 6 established fountains worldwide and additionally the roman ones in italy and the wallace in france.

**Comment by matkoniecz** [comment]
I am actually testing something like that, though it is targeted right now at "how drinking water is provided here".

**Comment by westnordost** [comment]
@matkoniecz you have ~10 tickets or so assigned to you already and 2 open pull requests. Before assigning even more work to you, please consider finishing your other work or unassigning yourself if you do not plan to do it after all to free it up for other contributors.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/pull/4423 did part for drinking water

I have not investigated whether it is useful and doable to do it for `amenity=fountain` and how it should be asked.

It is likely that some photos and text strings can be reused here.

**Comment by westnordost** [comment]
I've had a short look at it. I do not think it is useful or doable. The tags documented are too specific yet obviously incomplete. Hence, `fountain` key with values describing the appearance are somewhat freeform.

**Comment by matkoniecz** [comment]
So I guess that it needs overhaul of tagging scheme first (if that is worth doing at all - not sure what kind of info can be collected here)
