### ISSUE TITLE
New Quest: Ask for Changing Tables

### ISSUE THREAD

**Issue by dritter** [streetcomplete/StreetComplete#4391]
Hi there!
First off: Thanks for this awesome app! As a newly father it would be great to see all Locations with changing tables on [babykarte.openstreetmap.de](https://babykarte.openstreetmap.de) (repository: [babykarte](https://github.com/babykarte/babykarte)). It would be extremely helpful to know where you can change the diapers of your toddler. ;) 

### General
Affected tag(s) to be modified/added: [changing_table](https://wiki.openstreetmap.org/wiki/Key:changing_table)
Question asked: **Is there a changing table in this shop/restaurant?**

Changing Tables are usually to be found in:
- Restaurants
- Cafes
- Shops (especially drug stores)
- Public Buildings
- Museums
- Kindergartens
- Birth Centers
- Midwives
- Zoos

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  The only open question is how many tables are there..
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)
  Unfortunately not (all Restaurants alone is a great number), but IMHO it is worth it.

#### Badge
The "citizen" badge could be used as a reward. It even may be its own category.

#### UI
Main question would be "Is there a changing table at this location?".
Follow up questions would be:
- "Is there a fee to use this changing table?"
- "How many changing tables are there?"
- "Where is the changing table located?" -> This should be a defined List (see [Key:changing_table#Usage](https://wiki.openstreetmap.org/wiki/Key:changing_table#Usage))

**Comment by matkoniecz** [comment]
Good news, this quests exists. 

See https://wiki.openstreetmap.org/wiki/StreetComplete/Quests or https://taginfo.openstreetmap.org/keys/changing_table#projects or https://taginfo.openstreetmap.org/projects/streetcomplete#tags to check this kind of info.

See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/baby_changing_table/AddBabyChangingTable.kt

Note that it is disabled by default like other quests requiring visit inside.

**Comment by dritter** [comment]
Ah. Should have checked this first. Thanks for the info @matkoniecz , and sorry for the noise.
