### ISSUE TITLE
In overlay mode, roads behind buildings are drawn on top of buildings

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4394]
**How to Reproduce**
Enable overlay mode.
Find a tall building
Tilt the map
Roads that are bright because of the overlay mode begin to be drawn on top of buildings

Example: `59.94416° N, 30.49235° E`
<table>
<tr>
	<td>

![Screenshot_20220919-191507_StreetComplete.jpg](https://user-images.githubusercontent.com/25708359/191065509-8d85a8fe-104e-4ebf-91cc-744fa8d94f20.jpg)

</td>
	<td>

![Screenshot_20220919-192434_StreetComplete.jpg](https://user-images.githubusercontent.com/25708359/191065905-bee53e8e-5a7e-444b-993a-74c7646eeb15.jpg)

</td>
</table>

by the way, it was noticeable even here https://github.com/streetcomplete/StreetComplete/issues/4389#issue-1377104816

**Expected Behavior**

**Versions affected**
47.0 beta1

**Comment by westnordost** [comment]
This is kind of deliberate, even though those render artifacts (that only some parts of it seem to be on top) are unfortunate but I think a technical limitation.
