### ISSUE TITLE
Smoothness: Show actual values that my choice will result in

### ISSUE THREAD

**Issue by apophenic-treehugger** [streetcomplete/StreetComplete#4397]
**Use case**
Quest: _What's the surface quality of this road here?_
A choice is given that corresponds to values of [`smoothness=*`](https://wiki.openstreetmap.org/wiki/Key:smoothness), but the actual values in which each choice results are not shown.

Experienced mappers that normally use editors other than SC (like me) may be very familiar with the values of `smoothness=*` as defined in the [wiki](https://wiki.openstreetmap.org/wiki/Key:smoothness), like `smoothness=excellent`, `smoothness=intermediate`, etc. but may not necessarily know how these values translate to SC's terminology of "a little bumpy", etc

**Proposed Solution**
Show the actual value of smoothness in which my choice will result. For example little grey, bold, type-written **`smoothness=good`** on the bottom right next to each picture.

**Comment by mnalis** [comment]
That is likely intentional because SC is geared toward novice users (vast majorify of whom have no idea what this `tags` thing even is). Note that the quest also is not called `smoothness` but `Surface quality`. See FAQ at the beginning of https://github.com/streetcomplete/StreetComplete/pull/3617

As a workaround, when you press undo button at lower left part of the screen, it will tell you **_exact tags_** the answer you have selected have made to the ASM. So, as an advanced user, do it few times and you'll learn the tags SC uses for smoothness.

**Comment by apophenic-treehugger** [comment]
SC being primarily targeted at novices, does that mean that experts should be actively excluded?

I think forcing experiences mappers to "learn" SC language by awkwardly reverting their own edits back and forth won't exactly motivate them. Plus it makes it a pain for other users to understand the intentions behind those edits. Also I guess this strategy would contradict SC's mission to be as easily usable as possible.

What's the harm in discretely adding this extra information? I don't think any novice would be confused by a little hint in the bottom right saying "(smoothness=good)".

![smoothness](https://user-images.githubusercontent.com/81189494/191271817-fe065afd-937a-4b3a-98f8-38e79f110a9c.png)

**Comment by Helium314** [comment]
> SC being primarily targeted at novices, does that mean that experts should be actively excluded?

Experts are not excluded. Proof: Even if you know smoothness values, you can still answer the quest.
If you don't trust the app to do an appropriate conversion, I would recommend using an editor that is aimed towards experts.

**Comment by apophenic-treehugger** [comment]
Thanks.
What's the harm in adding the extra information, though?

**Comment by HolgerJeromin** [comment]
> What's the harm in adding the extra information, though?

This can confuse people, requires more time to read + understand and would be inconsistent. With other quests the tags are more complex so they can not be shown.

**Comment by matkoniecz** [comment]
>  What's the harm in adding the extra information, though?

Information overload, tricky translation, one of main points of SC is that interacting with tags can be avoided, implementation effort.

**Comment by matkoniecz** [comment]
Not saying that tags cannot be shown more prominently, but this does not seem to be a good idea.

**Comment by Helium314** [comment]
> There is some "show more info about quests" issue.

Do you mean #1913?
If such "more info" UI should ever be implemented, tags could also be shown there...

**Comment by matkoniecz** [comment]
> Do you mean https://github.com/streetcomplete/StreetComplete/issues/1913?

yes
