### ISSUE TITLE
check_date for smoothness

### ISSUE THREAD

**Issue by apophenic-treehugger** [streetcomplete/StreetComplete#4398]
**Use case**
Smoothness of highway surfaces (asphalt, sett, ...) degrades over time.

**Proposed Solution**
Add a tag `smoothness:check_date` when smoothness is input or checked by the user. Ask every X years to check and update surface smoothness. Quite similar to `check_date:opening_hours`,

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddPathSmoothness.kt#L24 - already done

**Comment by apophenic-treehugger** [comment]
Ah, great! I apparently only noticed the cases where it is not added.

I assume the check date is not added when the `smoothness=*` tag is created for the first time, is that right?

**Comment by Helium314** [comment]
Right.
Check dates are only added if the value does not change on a resurvey.

**Comment by apophenic-treehugger** [comment]
Thank you!

**Comment by matkoniecz** [comment]
Though I admit that I am unsure is it working well when both `smoothness` and `surface` and maybe `lit` are checking just object date...
