### ISSUE TITLE
AddTactilePavingCrosswalk seems to incorrectly set tactile_paving = yes on highway = crossing

### ISSUE THREAD

**Issue by yoasif** [streetcomplete/StreetComplete#4399]
**How to Reproduce**

1. answer "yes" to a question about whether there is tactile paving on both sides of a crosswalk. 

**Expected Behavior**
Per my reading of https://wiki.openstreetmap.org/wiki/Key:tactile_paving and the usage of tactile_paving = yes on nodes, the only time a node should be tagged with tactile paving is if the node has tactile paving. It makes sense to make the endpoint nodes of the crosswalk have tactile_paving = yes, but adding it to the "middle" of a crosswalk (where they may not be any tactile paving) doesn't seem to make a lot of sense. 

**Versions affected**

At least StreetComplete 45.2.

**Comment by matkoniecz** [comment]
See  #3407
