### ISSUE TITLE
Is this place air conditioned (parking bay that is)?

### ISSUE THREAD

**Issue by davidpnewton** [streetcomplete/StreetComplete#4400]
The new overlay for parking has a somewhat amusing bug. When parallel, perpendicular or diagonal parking is selected the next option is where on or next to the carriageway the parking is. However instead of displaying the correct text strings the following options are presented:

* On the carriageway
* Is this place air-conditioned?
* Yes,...
* Adjacent to the carriageway only dedicated spaces
* On the carriageway only in dedicated spaces

**How to Reproduce**
Use the new parking overlay and select parallel, perpendicular or diagonal parking options to display the incorrect strings.

**Expected Behavior**
Display text strings that actually make sense!

**Versions affected**
47.0 beta 1

**Comment by Helium314** [comment]
For some reason the UK tranlatons are messed up here...

**Comment by FloEdelmann** [comment]
Thanks for noticing and reporting.

This seems to be a copy-paste mistake in POEditor in `en-rGB`:

![grafik](https://user-images.githubusercontent.com/202916/191353577-cfe5fad6-cd01-42ff-b950-08e50024c26a.png)

I corrected it by reverting it to the previous value "Partially on carriageway".
