### ISSUE TITLE
Pyramid or pyramid shaped roof is not rendered correctly

### ISSUE THREAD

**Issue by Altonss** [streetcomplete/StreetComplete#4405]
Pyramid or pyramid shaped roof is not rendered correctly (is just rendered as a cube).

**Versions affected**
v45.2 from F-Droid

**Comment by Helium314** [comment]
Why specifically pyramid? Are other roof shapes rendered correctly?

**Comment by Altonss** [comment]
> Why specifically pyramid? Are other roof shapes rendered correctly?

I don't know if other roof shapes are rendered correctly :thinking:

**Comment by matkoniecz** [comment]
Roof shapes are simply not rendered at all and are not intended to be rendered right now, not sure is it possible to render them (answer is no, not sure what is the blocker).

**Comment by matkoniecz** [comment]
And if reported it should be done at https://github.com/streetcomplete/streetcomplete-mapstyle/issues (likely not worth doing, as it is almost certainly blocked)

**Comment by Altonss** [comment]
> And if reported it should be done at https://github.com/streetcomplete/streetcomplete-mapstyle/issues (likely not worth doing, as it is almost certainly blocked - unless you see how it can be implemented)

Thanks for the hint!
