### ISSUE TITLE
What material is the bench?

### ISSUE THREAD

**Issue by Timonade** [streetcomplete/StreetComplete#4407]
### General
Affected tag(s) to be modified/added: [amenity=bench](https://wiki.openstreetmap.org/wiki/Key:amenity=bench)
Question asked: **What material is the bench?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** `amenity=fuel` without `material=*`

**Comment by matkoniecz** [comment]
> and has a useful purpose

Is there any realistic use for that?

**Comment by Helium314** [comment]
see #3132

**Comment by mnalis** [comment]
As a side note, it has been implemented in [StreetComplete Expert Edition fork](https://github.com/Helium314/StreetComplete/releases) (in PR https://github.com/Helium314/StreetComplete/pull/363).
