### ISSUE TITLE
Adding a warning for photos expiring

### ISSUE THREAD

**Issue by ivanbranco** [streetcomplete/StreetComplete#4409]
Hi, seems like pictures attached to notes (https://westnordost.de/p/xxxx.jpg) expire 7 days after the note is closed (or something like that). The problem is that many people doesn't know it, and use them as tag values (2500 elements with the image=* tag at the moment). I thought at first a warning in-app could be showed, but then non-StreetComplete users closing the notes from another editor wouldn't know it anyway. So I think it would be a good idea to attach a little text to the note, such as:

```
Road is closed.

via StreetComplete xx.y

Attached photo(s):
https://westnordost.de/p/xxxxx.jpg
(The photo link will expire one week after the closing of the note.)
```

**Comment by matkoniecz** [comment]
I opened https://josm.openstreetmap.de/ticket/22397 and https://github.com/openstreetmap/id-tagging-schema/issues/591 to treat it as mistake in validators to further reduce damage and to repair what is already there.

Maybe a automated edit cleanup would be a good idea but I do not have energy for that right now and dealing with related approval discussion.

**Comment by westnordost** [comment]
IMO adding that sentence there is just too much cruft. E.g. in your example, the gist of the message is just "road is closed", the rest is just overhead. I am not on board with adding even more overhead. So I think it is better if this was a validation rule in iD and JOSM, as Mateusz already did.

**Comment by FloEdelmann** [comment]
Maybe just change "Attached photo(s):" to "Attached temporary photo(s):"?

**Comment by matkoniecz** [comment]
It seems not really clear and likely to make people scared that they will be lost before note is solved.

**Comment by mnalis** [comment]
> It seems not really clear and likely to make people scared that they will be lost before note is solved.

that might give the incentive to solve the note as soon as possible, which is not that much of a bad thing :)

We could explain it in the FAQ too (we should probably do it even if nothing changes of this front)

**Comment by mnalis** [comment]
Documented in FAQ "[Are the pictures taken with StreetComplete permanent?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Are_the_pictures_taken_with_StreetComplete_permanent?)"

**Comment by matkoniecz** [comment]
And [approved bot edit](https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/remove_links_to_temporary_files_hosted_on_westnordost.de) removes such tags
