### ISSUE TITLE
Helpbutton for answers

### ISSUE THREAD

**Issue by bash-git** [streetcomplete/StreetComplete#4410]
Hi,
especially for beginners some tags are confusing or irritating. 

A simple solution would be a questionmark button which links to the related osm wiki article.
Or a additional entry on other answers.
![helpbutton](https://user-images.githubusercontent.com/51889601/192097646-ec4e4762-dba4-4917-aed4-5aa045e1a1c9.png)

**Comment by FloEdelmann** [comment]
There is already an issue for that: #1913

Please add specific ideas in a comment on that issue.
