### ISSUE TITLE
Show all tasks on max zoom

### ISSUE THREAD

**Issue by Filip10** [streetcomplete/StreetComplete#4411]
Please show all tasks on max zoom only

When I zoom in as much as possible and I do not know how to complete some task. Every task which is nearby is just a not clickable node, so maybe this one I would know, but I can not see him/click on him.

**Comment by matkoniecz** [comment]
In many cases it is simple impossible as there is not enough space on the screen.

**Comment by mnalis** [comment]
related: https://github.com/streetcomplete/StreetComplete/issues/2878 and issues linked there

**Comment by Helium314** [comment]
also related: #4060, #124

**Comment by Filip10** [comment]
Thanks for these related issues. But I still think that it would be great if you can turn it on/off in settings to be able to see the one you want to see, or hide that one in the front for few minutes.

**Comment by mnalis** [comment]
@Filip10 yes, it would be great, that is not disputed. Unfortunately, (if you read the linked issues) we **cannot** do that, because the library StreetComplete is using does not support that (and workarounds we tried to think about are not very good either)
