### ISSUE TITLE
Flat range interface may result in weird input with RTL languages

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4412]
https://poeditor.com/projects/po_edit?id=97843&term=381790295&id_language=3#showComments381790295

> For right to left scripts which use right to left numbers and ranges, this should probably just be an ellipsis or similar to avoid confusion, so it shows 1 … 2 instead of 1 نوں‎ 2 which look kind of like 2 to 1. (As the video below shows, the numbers are input boxes, not part of the actual text, so no bi-directional control characters necessary thankfully.)

I suspect that problem may be deeper with people entering lower number where higher will go. In two weeks I will be able to talk with friend who has experience with Hebrew/Arabic and verify the problem and discuss what would be the best solution. I guess that switching position of boxes would work? But then special separate string value may be needed or resetting what was translated already in RTL languages if they used this kind of hack.

**Comment by westnordost** [comment]
ping

**Comment by westnordost** [comment]
No reply, closing.

**Comment by westnordost** [comment]
On RTL languages, the `view_entrance_flat_range.xml` actually looks like this, because the `LinearLayout` reverses its orientation on RTL languages:

![image](https://user-images.githubusercontent.com/4661658/211842726-68f35113-3755-4a3d-bb03-78017046cb52.png)
