### ISSUE TITLE
Quest recommendation: What can be recycled here?

### ISSUE THREAD

**Issue by crannofonix** [streetcomplete/StreetComplete#4415]
This quest should be added because it is important to know what things you can recycle at recycling centers, and what things you can't. ♻️🗺️

This quest will ask you "What can be recycled here?", and there are options such as (these are only some examples)

- Paper including newspapers, magazines, and etc 📄
- Cardboard 📦
- Glass bottles and jars 🍾
- Plastic products 🧴
- Metal

**Comment by matkoniecz** [comment]
Please check https://wiki.openstreetmap.org/wiki/StreetComplete/Quests before suggesting new ones
