### ISSUE TITLE
Android 13 (Material Design 3) app icon

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4416]
**Use case**
App icons on Android 13 can adapt their colour to the background image of the home screen, which looks really cool :)

**Proposed Solution**
Make the SC icon also adaptable, this instruction might be useful: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

#3650 may be related, though this issue is just about the app icon and not the style in the app itself.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/92865620/192349880-aec9e357-8928-4c63-a856-270182bc8634.png)
(just poorly edited with gimp)

**Comment by westnordost** [comment]
It is already adaptive (separate foreground and background).

**Comment by FloEdelmann** [comment]
But there is no `monochrome` layer:

https://github.com/streetcomplete/StreetComplete/blob/70cfe52452dd3ee14701526a08b84abb41633c2b/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L1-L5

**Comment by FloEdelmann** [comment]
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons:

> If you want to opt-in to supporting user theming of app icons, provide a single layer for the monochrome version of the icon.

and https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app (emphasis mine):

> You can then use the `<adaptive-icon>` element to define the foreground, background, and **monochromatic** layer drawables for your icons. The `<foreground>`, `<background>`, and **`<monochrome>`** inner elements all support the `android:drawable` attribute.

**Comment by westnordost** [comment]
ic
