### ISSUE TITLE
New quest: What type of shelter is this? (Specifying `shelter_type=*`)

### ISSUE THREAD

**Issue by sjakobi** [streetcomplete/StreetComplete#4418]
### General
Affected tag(s) to be modified/added: [`shelter_type`](https://wiki.openstreetmap.org/wiki/Key:shelter_type)
Question asked: **What type of shelter is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Any `amenity=shelter` that doesn't have a `shelter_type` tag yet.

**Metadata needed:** None

**Proposed UI:** Multiple choice with example images.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Key:shelter_type - quest should include only actually used values likely to be applicable (so no support for [nuclear](https://wiki.openstreetmap.org/wiki/Tag:shelter_type%3Dnuclear) value for example), but quest seems fitting

**Comment by westnordost** [comment]
see the linked pr
