### ISSUE TITLE
New cyphers for the royal cypher quest

### ISSUE THREAD

**Issue by osm-spiregrain** [streetcomplete/StreetComplete#4420]
This is low priority, at least for the moment.  New royal cyphers have been published, which are relevant to the royal cypher quest.  It could be some time before any of them appear on actual postboxes.   There is a separate design for Scotland, and one for England, Wales and NI (and presumably at least some other places).

The new designs are described here - https://www.bbc.co.uk/news/uk-63034255 and available on wikimedia https://en.wikipedia.org/wiki/Royal_cypher#/media/File:Royal_Cypher_of_King_Charles_III.svg and https://en.wikipedia.org/wiki/Royal_cypher#/media/File:King_Charles_III%E2%80%99s_Scottish_Royal_Cypher.jpg

**Comment by FloEdelmann** [comment]
See also https://github.com/streetcomplete/StreetComplete/pull/2583#issuecomment-1258641153
