### ISSUE TITLE
ask also about living streets' sidewalk surface, if there is a sidewalk

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4424]
https://github.com/streetcomplete/StreetComplete/blob/6823584ae986a0167dfa29c2600ca535c05d23c3/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddSidewalkSurface.kt#L17

There are more than 9,600 ways which are `highway=living_street` with `sidewalk=both|left|right` (see https://taginfo.openstreetmap.org/tags/highway=living_street#combinations)
The sidewalk surface quest should also appear on these living streets.

---

Maybe also add `highway=service`? (There are >37,600 ways tagged with `highway=service` and `sidewalk=both|left|right`; see https://taginfo.openstreetmap.org/tags/highway=service#combinations)

**Comment by westnordost** [comment]
Sure, if there is a sidewalk, it is valid to ask the surface for. Will you open a PR for that?

**Comment by legofahrrad** [comment]
> Will you open a PR for that?

Sorry, I wanna keep in my comfort zone ;)
Yeah, it's just one line of code – but
- downloading Android Studio
- forking StreetComplete
- what else have you to do to create a Pull Request? 😅

You can do it in seconds, can't you? @westnordost ;)

**Comment by westnordost** [comment]
You can edit it online:

![image](https://user-images.githubusercontent.com/4661658/193131904-300d2801-dfa6-4b2f-a62b-c09d294dafc6.png)

**Comment by legofahrrad** [comment]
Oof, never knew this! Thanks, then I'll give it a try at the weekend :)

**Comment by HolgerJeromin** [comment]
> You can edit it online

In the fork (done by github automagically) you can trigger a build. So you can download an apk in the phone and test your changes without installing anything on your computer!
