### ISSUE TITLE
Cannot download/upload or login to OSM

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4426]
Overnight I can no longer download or upload quests (without any obvious change on my side). I updated to the latest APK (v47.0) and it still is broken:

![Screenshot_20220929-131824](https://user-images.githubusercontent.com/12725310/192931228-993523e6-f831-4469-a3d4-fe56f7b74e7d.jpg)

I logged out of OSM to see if was an authorization issue and now I can't log back into OSM either:

![Screenshot_20220929-131903](https://user-images.githubusercontent.com/12725310/192931291-f6779b61-40f9-4dba-a441-c7aa719378d4.jpg)

**Comment by dbdean** [comment]
Maybe it's come good now? Things seem to be working. My star count hasn't updated though - it's only showing today's quests.

**Comment by HolgerJeromin** [comment]
Perhaps caused by solved https://github.com/openstreetmap/operations/issues/754
at least the server is [used](https://hardware.openstreetmap.org) for api/website.
