### ISSUE TITLE
Possibility of street parking overlay input on one side

### ISSUE THREAD

**Issue by bgo-eiu** [streetcomplete/StreetComplete#4427]
**Use case**

I have been trying out the street parking overlay feature, and I have been finding that when I am surveying much of the time, I cannot see the side of the street opposite me to tell the parking conditions along it, but the input only allows entering on both sides of the way. Examples of situations where this happens are when one side of the sidewalk is closed, or when the vehicles parked are too tall to see the signs, or the road is very wide and the opposite side is actually quite far away. Right now, I am on the bus, and the windows on one side are too low for me to see many signs from where I am sitting, but I can see them on the other side.

**Proposed Solution**

There could be an option like "Can't say...," or could say "can't see..." and that would leave that side alone. Asking to leave a note would be too much because this is the situation more often than not I am finding. Another possibility is having the "OK" check mark appear even when only one side is entered, and you can just leave one blank.

**Comment by riQQ** [comment]
Also mentioned here https://github.com/streetcomplete/StreetComplete/discussions/4362#discussioncomment-3733870.

**Comment by westnordost** [comment]
Hm, or even allow to just tag one side...? (I.e. the orange ✔️ button pops up even after selecting one side?)

**Comment by bgo-eiu** [comment]
If that is a possibility, than that sounds good yes
