### ISSUE TITLE
SC 47.0 still not available on Google Play Store

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#4432]
Hi there,

[Google Play Store](https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete) still shows v46.1 as the current version of StreetComplete although the release of v47.0 is now three days old. Did something go wrong here again? Hopefully it's not the same mess as it was the case with v40.0 (see #3748)...

The cycling cat

**Comment by riQQ** [comment]
At least in the past it sometimes took more than a week for a new version to be propagated from a GitHub release to an F-Droid release.

**Comment by cyclingcat** [comment]
Hi there,
,
I didn't mean F-Droid but Google Play store! Usually new versions were available within a few hours after their releases. If a new release didn't show up the next days, usually something went wrong (e. g. Google rejected it).

The cycling cat

**Comment by riQQ** [comment]
Sorry, my bad. I misread.

**Comment by westnordost** [comment]
Uhm, thank you for the notice, cyclingcat. Apparently I forgot to push the "release" button. (There are several forms you have to click through, as if one is doing an order in an online shop. So it seems I missed to click the final button  this time)

**Comment by westnordost** [comment]
I pressed that button now
