### ISSUE TITLE
Shop overlay : give specific color for new / old shop

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#4443]
**Use case**
The shop overlay should help to resurvey weather the name of activity has changed. 

**Proposed Solution**
A project has been designed in this usecase : Geocropping
https://geocropping.xsalto.com/
The idea is to change the colour helping to see old non checked POI. 
![Screenshot_2022-10-01-00-31-19-359_com.android.chrome.jpg](https://user-images.githubusercontent.com/4929752/193365020-8e6a7a2c-1450-46dc-815c-657ff8be8fe5.jpg)

**Comment by westnordost** [comment]
Re-survey for overlays is not supported yet. When it is implemented, this can be revisited. As of now, this is not possible.

**Comment by westnordost** [comment]
I know this somewhat reduces the usefulness of this overlay until something like that is supported.

However, for what the overlay is good already now is to add POIs where there are none yet and to fill any holes in partly mapped areas.

Checking for their existence is something that is facilitated with the usual quests (opening hours, check existence,...)

**Comment by JLZIMMERMANN** [comment]
I spend many time adding shops and hunting vacant shops.
Highlighting vacant shops and recently validated ones would be really helpful. 
![IMG_20221001_213721.jpg](https://user-images.githubusercontent.com/4929752/193425531-5afa30c5-ad5e-40ba-b157-4cdc915ce713.jpg)
Here you have a way given by the app OSMgo! 
![Screenshot_2022-10-01-21-38-32-867_fr.dogeo.osmgo.jpg](https://user-images.githubusercontent.com/4929752/193425581-12cb48ab-b336-426a-98ec-0fd95b343750.jpg)

**Comment by mnalis** [comment]
> I spend many time adding shops and hunting vacant shops. Highlighting vacant shops and recently validated ones would be really helpful. without having such graphic information we would need to open each POI.

I agree that it would be very useful, so hoping this can be revisited in the future! Highlighting very old POIs (https://github.com/Zverik/every_door/issues/275) as well as those having `fixme` tags (https://github.com/Zverik/every_door/issues/354) are very useful features of [Everydoor app](https://wiki.openstreetmap.org/wiki/Every_Door) which I appreciate.
