### ISSUE TITLE
Removing address doesn't work properly [Address Overlay]

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4446]
**How to Reproduce**
- Use the address overlay
- Tap on e. g. a house
- Clear the text from street and housenumber field
- Tab the orange checkmark
- (Check the history, no changes were recognised)
- After upload, nothing was changed in OSM data
- You can tap on the same house again, see that address is still there

**Expected Behavior**
Allow removing the address (if this was done on purpose?)
Clearing both text fields should remove the address

**Versions affected**
v48.0-alpha1

**Comment by westnordost** [comment]
Removing an address is actually not supported,  but of course the behavior you describe is a bug, then.

**Comment by legofahrrad** [comment]
Is it planned then to make the removing of an address possible?
I had an case yesterday that a service building was tagged with an address though there was no address.

**Comment by westnordost** [comment]
Hm, not right now, maybe at a later time. It has some complexity. I.e. it depends on the situation if the removal of the `addr:*` information should lead to the deletion of the element or just the deletion of the `addr:` tags. E.g. an entrance stays an entrance even without a housenumber. Same with a building. But a node with no further info on it should be deleted, unless it is part of a way or relation because then it might be relevant for the geometry of the way (a corner of a building) / the relation (housenumber tagged on a bus stop or whatever).

**Comment by matkoniecz** [comment]
> Is it planned then to make the removing of an address possible?

One of main problems here is various approach to cases of officially assigned addresses where nothing exists yet (assigned to random field/forest/wetland/industrial grounds).

AFAIK there is no consensus what should be done, often not even regional one

> But a node with no further info on it should be deleted, unless it is part of a way or relation

But if it is an associated street relation then it probably should be deleted

**Comment by westnordost** [comment]
>> But a node with no further info on it should be deleted, unless it is part of a way or relation

> But if it is an associated street relation then it probably should be deleted

Can you elaborate?

**Comment by matkoniecz** [comment]
address nodes like https://www.openstreetmap.org/node/2042228587 on removal of address info should be also deleted, despite belonging to relation: as [associatedStreet](https://wiki.openstreetmap.org/wiki/Tag:type=associatedStreet?uselang=en) on removal of address should stop containing it

**Comment by westnordost** [comment]
So, maybe the general rule is...:

Remove node if:
1. no other tags than `addr:*` tags exist on the node (i.e. node would have no tags after their removal)
2. it is not part of any way

But:
- being a member of a relation does not inhibit the node's removal

However, maybe some relations exist that (can) contain nodes with (potentially) no tags that are important for its geometry? Turn restrictions came to my mind (via node), but on the other hand, that node would be part of a way. For site relations, a node with no tags would also make no sense. In (bus) route relations, nodes would at least be tagged with being a bus stop or something.

**Comment by Helium314** [comment]
> no other tags than addr:* tags exist on the node (i.e. node would have no tags after their removal)

Maybe if only `source` is remaining it could also be removed. Though this may create issues e.g. in the Netherlands (https://github.com/streetcomplete/StreetComplete/issues/3244#issuecomment-912405388)

**Comment by legofahrrad** [comment]
When selecting a building without an address in the overlay, and then tapping "no address here" in the three-dots-menu, SC does nothing (because there is no address to remove) but shows one edit to upload (auto-upload off).

Should I open a new issue for that?

**Comment by legofahrrad** [comment]
**My suggestion:** When selecting a building without an address in the overlay, and then tapping "no address here" in the three-dots-menu, SC should add `noaddress=yes` or `nohousenumber=yes`. For those buildings without an address, SC should give a hint that somebody tagged the building as having no address and thus not show any fields for street or housenumber.

When users try to add `noaddress=yes` to any building types such as garages or sheds which are likely to have no address at all, there should come a warning, that `noaddress=yes` is intended for those buildings that are likely to have an address but actually don't have one.

---

In the current version, `nohousenumber=yes` gets just ignored, so if somebody tagged `nohousenumber=yes` (by mistake) on a building and then somebody else using SC address overlay adds the real housenumber, `nohousenumber=yes` stays, which should actually be removed when adding the housenumber.
