### ISSUE TITLE
New quest: valve types on bicycle pumps

### ISSUE THREAD

**Issue by Sukkoria** [streetcomplete/StreetComplete#4450]
### General
Affected tag(s) to be modified/added: [valves=](https://wiki.openstreetmap.org/wiki/Key:valves)
(described on [amenity=compressed_air](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air))
Question asked: **What kind of valves are compatible with this pump?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
-> I think it will be useful for cyclists and other riders of small vehicules with tires (e-scooters…)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
-> in my neighbourhood, the valve types are noted and drawn on the pump, there’s no need to inspect the pump output and recognize the valve type by eye (+ photos can be provided in the quest in this case)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
-> based on [the existing values in taginfo](https://taginfo.openstreetmap.org/keys/valves#values), the values are varied
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
-> There are currently [985 items using `valves=…`](https://taginfo.openstreetmap.org/keys/valves#overview) in OSM and [~ 9k service:bicycle:pump](https://taginfo.openstreetmap.org/keys/service%3Abicycle%3Apump#overview) + [~ 7k amenity=compressed_air](https://taginfo.openstreetmap.org/tags/amenity=compressed_air#overview), so there are items that could be improved?

### Ideas for implementation
**Element selection:** 
`amenity=compressed_air` or `service:bicycle:pump` without the key `valves`
[overpass-turbo request](https://overpass-turbo.eu/s/1mnE)

**Metadata needed:** 
No idea on this point; my observations are based on what I’ve seen in France.

**Proposed UI:**
To make easier to identify the valve type, I was thinking of a UI with photos (like the one to add surface types), using pictures like [in the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air#Valve_types) if the license is suitable, or pictures from [wikimedia commons](https://commons.wikimedia.org/wiki/Category:Bicycle_valves).

If this type of quest is OK, I would gladly develop the matching code during Hacktoberfest, or other simple quests depending on what is available from the Issues list.
Have a nice day and feel free to tell me about your insights on this one!

**Comment by matkoniecz** [comment]
In Poland two walve types are in use and bicycle pumps universally have both. Is situation different in France?

**Comment by slackline** [comment]
In the city I live in the UK the pumps that haven't been vandalised also have two types of valve (Schrader and Presta). There are other valves such as Dunlop (also known as Woods) and Tubeless valves for wheels without tubes but I've personally never used inner tubes/bikes that require these. Useful article on the [types of bike valve](https://www.bikelockwiki.com/bike-tire-valve-types/) and there is still scope for more variation elsewhere in the world.

**Comment by westnordost** [comment]
This is likely something that requires some "expert" knowledge. Not even people who own a bike may tell apart exactly how the different valve types look, and even less like a compatible bicycle pump would look. Off-the-shelve bicycle pumps (which may be found chained to the door of a bicycle shop etc.) also usually have it not labelled. Maybe they would have it labelled with what they are compatible with on the packaging, but obviously, public bicycle pumps have their packaging removed.
Same with air compressors at fuel stations. They'll most probably only support Schrader (=car valve) because they are not made *for* bikes, but many do actually not know this. So, this is already reason enough to not have this as a quest:

> 👨‍💻 Users are no experts
> 🐿️ Easy answer

Additionally, it is likely that every public pump will support anything that is common in whatever region the bicycle pump is situated. So, the data recorded will usually not be surprising and if it is surprising, I estimate that quite a high percentage of that would actually be input wrong (due to "👨‍💻 Users are no experts")

> 💤 No spam

**Comment by mnalis** [comment]
(related: discussion in https://github.com/streetcomplete/StreetComplete/issues/3053#issuecomment-878963548 and below)

**Comment by mnalis** [comment]
As related [discussion](https://community.openstreetmap.org/t/useful-subtags-for-amenity-bicycle-repair-station-for-streetcomplete-quest/118491/4) has recently popped up mentioning the need for quest, and new hacktoberfest is coming up, perhaps you @Sukkoria  (or someone else) would like to make a PR for [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork, which is fine with quests requiring expert domain knowledge)?

**Comment by mnalis** [comment]
(fixing closed status / tags; as this was implemented in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) only, and is `wontfix`ed in StreetComplete)
