### ISSUE TITLE
text not displayed correctly

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4451]
![grafik](https://user-images.githubusercontent.com/92865620/193465734-ce2888eb-d7ee-4f26-92ba-f08c09aa4974.png)
- actually it should be "Hausname _Gebäude 40_"

### How to reproduce ###
1. use the shop overlay (not sure whether this happens also with other overlays / no overlay)
2. tap on a shop which has a `addr:housename`
3. see that HTML-Tags are displayed instead of styled text

### Versions affected ###
v48.0-alpha1

**Comment by westnordost** [comment]
Can you tell me the location for reproduction?

**Comment by legofahrrad** [comment]
https://www.openstreetmap.org/node/7917525204
