### ISSUE TITLE
some shop icons are deformed [Shop Overlay]

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4455]
![grafik](https://user-images.githubusercontent.com/92865620/193606483-ef4ee433-162d-40dc-b8af-585bae7fbd24.png)
[location](https://www.openstreetmap.org/?mlat=53.10078&mlon=8.78682#map=19/53.10078/8.78682&layers=N)

The icons should be in their original ratio, if they are not square-shaped the margin should be white.

Examples for deformed icons are mobile phone shops, book shops and ice cream shops

**Versions affected**
v48.0-alpha1

**Comment by FloEdelmann** [comment]
For reference: Fixed by https://github.com/streetcomplete/StreetComplete/commit/9775e832951ec9386037a14a6ea360dc660b3f7b
