### ISSUE TITLE
The compressed air quest should not ask at fuel stations for boats

### ISSUE THREAD

**Issue by ambassador86** [streetcomplete/StreetComplete#4460]
When you are near a gas station for boats which is tagged as amenity=fuel and waterway=fuel it is not relevant to ask for compressed air. Boats do not need to inflate tyres. If they are big enough they already have an air compressor on board.

**How to Reproduce**
Navigate to a boat fuel station which is tagged with amenity=fuel and waterway=fuel like https://www.openstreetmap.org/node/1692354523 and the quest shows up.

**Expected Behavior** 
The quest should not show up for boat gas stations tagged with  amenity=fuel and waterway=fuel.
For the expected behavior the selector should be adjusted somewhere here https://github.com/streetcomplete/StreetComplete/blob/5b8a765adf65829cabe174d7804022d6e4e16df7/app/src/main/java/de/westnordost/streetcomplete/quests/air_pump/AddAirCompressor.kt#L21

**Versions affected**
v47.0

**Comment by Helium314** [comment]
> However, with the linked example I also assume that amenity=fuel is incorrect for a water-only fueling station and would need to be removed. 

Right, `amenity=fuel` is for road vehicles, see https://wiki.openstreetmap.org/wiki/Fuel
So either tagging is wrong, or it's also for road vehicles and thus compressed air should be asked.

I think it's better to find wrong tagging instead of trying to filter it, even if that leads to such issues.

**Comment by mnalis** [comment]
Yes, this quest should not be asked on waterway-only fuel stations, and indeed it is not.

Note that (at least over here in Croatia) many fuel stations on the coast and islands are both `amenity=fuel` **and** `waterway=fuel` (e.g. https://www.openstreetmap.org/way/290393231), where it is quite reasonable thing to ask.

If the node at https://www.openstreetmap.org/node/1692354523 is for **boats only**, then _**it is mistagged**_, and it should be marked only with [waterway=fuel](https://wiki.openstreetmap.org/wiki/Tag:waterway=fuel) **only** and **not** with [amenity=fuel](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel) - see `amenity=fuel` wiki which states:

> Fuel stations for watercraft, aircraft and rail vehicles are using different tags (see below).

So in StreetComplete, one should `leave a Note` stating that this is **boat-only** fuel station (i.e. `waterway=fuel`), and **not** fuel station for cars (i.e. `amenity=fuel`).

**Comment by mnalis** [comment]
Alternatively, if there is a huge number of such tagging mistakes (as evidenced by lots of [left notes](https://ent8r.github.io/NotesReview/) with "`Survey availability of air compressors`" text), one might consider adding `other option` to the quest which would remove `amenity=fuel` tag (named `Only boats can fuel here, not any ground vehicles` or similar).

However, currently it does not seem to be a lot of such notes, so perhaps there are not many such mistagged boat-only fuel stations which claim they fuel cars too?
