### ISSUE TITLE
Repeated outdoor/indoor seating quest

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4466]
https://www.openstreetmap.org/way/176882162

After answering the outdoor/indoor seating quest it pops up again. Even after "search for quests here" 

Default quest order
Auto upload is active

**How to Reproduce**

**Expected Behavior**

**Versions affected**

v48.0-alpha1

**Comment by matkoniecz** [comment]
Which answer you were giving?

**Comment by HolgerJeromin** [comment]
As you saw in the history:
Both

**Comment by westnordost** [comment]
Did you give the same answer three times? Or was it uploaded three times and you actually only answered once?

**Comment by HolgerJeromin** [comment]
Every upload was triggered by answering the quest (each as indoor+outdoor).

**Comment by westnordost** [comment]
Okay, I am pretty sure that it is the same issue as #4258
