### ISSUE TITLE
Quest suggestion: Two-Tier value for bicycle_parking

### ISSUE THREAD

**Issue by Winschu** [streetcomplete/StreetComplete#4473]
### General
Affected tag(s) to be modified/added: [Key:bicycle_parking](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking)
Question asked: Is it possible to also add _two-tier_ as an value for this key in the app? As I'm currently residing in the netherlands this type of bicycle parking seems to be pretty standard at train stations here.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

**Comment by legofahrrad** [comment]
Do you want to have "two-tier" as an answer option for the existing bicycle parking type quest? Or do you suggest a new quest? What should be added?

**Comment by Winschu** [comment]
> Do you want to have "two-tier" as an answer option for the existing bicycle parking type quest? Or do you suggest a new quest? What should be added?

My intention was to add a new answer option for the existing quest, correct.

**Comment by peternewman** [comment]
They are getting more common near stations in the UK too, for higher density bike parking.

**Comment by westnordost** [comment]
How do these bicycle stands differ from normal stands in terms of security or other important use cases? (I.e. why is it important to differentiate between these and normal stands?)

**Comment by peternewman** [comment]
Primarily because if you're on the top row you'd have to lift the bike up to some extent (I don't think they're counter-balanced). I think the support bit is generally lower so you probably can't lock to the frame of the bike itself?

I guess also because they're so physically different to the other options in the app currently. It's probably a hybrid of a wall loop and often covered, but not as secure as a shed. But I think both bike wheels go in and there's more support, so probably less likely to bend the wheel than a wall loop.

**Comment by Winschu** [comment]
> I guess also because they're so physically different to the other options in the app currently. It's probably a hybrid of a wall loop and often covered, but not as secure as a shed. But I think both bike wheels go in and there's more support, so probably less likely to bend the wheel than a wall loop.

Yeah I could post here an image as an example but the picture in the osm wiki for this key value is quite similar as it is in my location.

**Comment by Winschu** [comment]
> My main worry is following: are there two-tier bicycle parkings differing between each other as much as stands and wheelbenders?

Is this more a question of whether there is more than one type of this value (from different manufacturers) or several different constructions?

**Comment by Winschu** [comment]
> Mostly it is question are there various two-tier designs distinct enough to have own values.

Okay, then my question would be: Why should I select an value in the app for this object that is obviously not the right choice? What key-value that is already accessible in the app should I then use?

**Comment by mnalis** [comment]
@Winschu I think you misunderstood; the extra question (as I understand it) was are there different designs for two-tier parkings? E.g. should we have _"two-tier wheelbender"_, _"two-tier rack"_, _"two-tier lockers"_, etc. or are **all** _"two-tier bicycle parkings"_ of the basically same design? 

as for the:

> Okay, then my question would be: Why should I select an value in the app for this object that is obviously not the right choice?

the answer is simple and same for all quests for which there is no matching answer: `Other Answers` / `Can't say` / `Leave note`.

**Comment by peternewman** [comment]
> Mostly it is question are there various two-tier designs distinct enough to have own values.

Generally the ones I've seen before look pretty similar, although I did spot one interesting edge-case today, I think there must have been stands existing already, as the bottom tier is stands, whereas the top tier is the normal two-tier stuff!

**Comment by Winschu** [comment]
> @Winschu I think you misunderstood; the extra question (as I understand it) was are there different designs for two-tier parkings? E.g. should we have _"two-tier wheelbender"_, _"two-tier rack"_, _"two-tier lockers"_, etc. or are **all** _"two-tier bicycle parkings"_ of the basically same design?
> 
> as for the:
> 
> > Okay, then my question would be: Why should I select an value in the app for this object that is obviously not the right choice?
> 
> the answer is simple and same for all quests for which there is no matching answer: `Other Answers` / `Can't say` / `Leave note`.

Okay, thank you for the clarification. To answer the question: No I don't think there are multiple subtypes of this value.

**Comment by westnordost** [comment]
Then I think it is fair to add this value as it seems to be sufficiently distinct from other values (stands, building, wheelbenders)
