### ISSUE TITLE
Acoustic signals

### ISSUE THREAD

**Issue by Wetterauer** [streetcomplete/StreetComplete#4480]
It has happened to me several times now that I had StreetComplete activated on my phone during our walks, but then at some point I put it in my pocket and was only reminded of it when I got home.
It would be very handy if StreetComplete would generate an acoustic signal when you get close to an open task

**Comment by legofahrrad** [comment]
see #48 and related issues

**Comment by mnalis** [comment]
I've added a FAQ for this: "[Can we get acoustic/sound/haptic signal when we are near quest to solve? ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Can_we_get_acoustic/sound/haptic_signal_when_we_are_near_quest_to_solve?)"
