### ISSUE TITLE
Notes being questions are not displayed as quests

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4482]
**How to Reproduce**
Open SC and go to e.g. this area: https://www.openstreetmap.org/#map=19/48.10945/11.72678&layers=N
The two notes, which are currently open there, contain a `?`. Both are not displayed as quests when the option to show notes not phrased as a question is disabled. 

**Expected Behavior**
I see the notes as a quest and can add a comment or photo comment there.

**Versions affected**
v47.1

(After comment https://github.com/streetcomplete/StreetComplete/issues/4482#issuecomment-1273494363, this issue has been edited in order to be precise about the option to show notes not phrased as a question)

**Comment by Helium314** [comment]
Do you have the option to show notes not phrased as a question enabled?

**Comment by FloEdelmann** [comment]
But shouldn't it be asked anyway, because the note text actually contains a `?`?

https://github.com/streetcomplete/StreetComplete/blob/b0eb766e051b2955da9fd63b7b463d45e62f615e/app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestController.kt#L224-L242

**Comment by mnalis** [comment]
More importantly, `Show all notes`, even when checked, _will not actually_ show **all** notes.
Most notably, it **will not show your own new notes**:

https://github.com/streetcomplete/StreetComplete/blob/b0eb766e051b2955da9fd63b7b463d45e62f615e/app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestController.kt#L208-L210

I've suggested to implement an option to allow user to view his own notes before (https://github.com/streetcomplete/StreetComplete/issues/2692) but it has sadly been rejected.
