### ISSUE TITLE
Allow "sidewalk is marked separately" other answer on  "What's the surface of the sidewalk here?" quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4495]
**Use case**
I'm often offered quest `What's the surface of the sidewalk here?`, which wants to add `sidewalk:left:surface` and `sidewalk:right:surface` to the road. However, the sidewalks are already mapped separately as `highway=footway`.

It seems to happen when roads have old-style `sidewalk=both` / `sidewalk=left` tags. 
E.g. https://www.openstreetmap.org/note/3162147, https://www.openstreetmap.org/note/3112565, https://www.openstreetmap.org/note/3112572, etc.

In that case, user should have the "other answer" to say that the sidewalks are marked separately instead.

**Proposed Solution**
Show "other Answer" which would say _"the sidewalks are already mapped separately"_, and when chosen, fix the sidewalk tags as follows:

- `sidewalk=both` => `sidewalk:both=separate`
- `sidewalk=left` => `sidewalk:left=separate`
- `sidewalk=right` => `sidewalk:right=separate`

I can try to do the PR if that seems reasonable?

**Comment by legofahrrad** [comment]
Why don't you just use the Sidewalk Overlay to change it?

**Comment by legofahrrad** [comment]
Similar issue:  https://github.com/streetcomplete/StreetComplete/issues/3920, especially https://github.com/streetcomplete/StreetComplete/issues/3920#issuecomment-1165988346

**Comment by mnalis** [comment]
> Why don't you just use the Sidewalk Overlay to change it?

For basically the same reason I don't long click and choose _"open in Vespucci"_. 
Overlay seems fine for longer-time editing of one feature, but I find it **_very cumbersome for one-off edits_** so far.

<Details>
E.g. instead of:

- click other other
- click _"the sidewalks are already mapped separately"_

With _Sidewalk Overlay_ I instead have to:
- click hamburger
- click overlay
- find and click "Sidewalks"
- click "OK" (and not outside of window which I often do, which cancels the action)
- click on the road
- click on the left side
- verify situation on the screen (zooming and panning as needed) and choose "separate" or "no" to click on it
- click on the right side
- verify situation on the screen (zooming and panning as needed)  and choose "separate" or "no" to click on it
- click checkbox to confirm
- click hamburger
- click overlays
- find and click previous overlay I was using (usually shops or maybe addresses)
- click "OK" (and not outside of window which I often do, which cancels the action)

</details>

Thanks for the pointer to #3920 though! 
Yes, _"other answer"_ / _"The sidewalk situation is different"_  (which would remove `sidewalk=*` and `sidewalk:*=*`) is also quite acceptable!

I volunteer to do and test the PR for either option, if it would be accepted?

**Comment by westnordost** [comment]
Jesus, Matija, I would really appreciate if you would write much more concisely and to the point.

---

I don't see how your original suggested solution would work... what if there is a separately mapped sidewalk on the left but on the right side, the sidewalk is mapped on the street way? (But there is `sidewalk=both` tagged) Then that answer given by the user in good faith would just introduce differently wrong data.

**Comment by mnalis** [comment]
I tried to hide detailed explanations in `<details>` tag, which works for web, but probably not for you. Sorry, I'll try to be shorter.
Yes, you're correct, if only partially mapped, `sidwalk:both=separate` would indeed be wrong in my first suggestion.

Would _"other answer"_ / _"The sidewalk situation is different"_ (which would remove `sidewalk=*` and `sidewalk:*=*`)  PR be OK?

**Comment by westnordost** [comment]
Yes, I think there'd be nothing wrong with that.
