### ISSUE TITLE
Quests doing geometry checks are not shown again after undo

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#4496]
**How to Reproduce**
- Move the map to https://www.openstreetmap.org/node/6437109524
- Answer the quest *'What kind of building entrance is this?'* with any answer, e.g. *'Other entrance type'*
- Undo the answer
- Quest doesn't appear again

Bonus
- Hard quitting the app and restarting doesn't help
- *'Scan for quest here'* returns the quest

**Expected Behavior**
Quest comes back after undo

**Versions affected**
v47.1

**Comment by westnordost** [comment]
@matkoniecz this is your quest, could you look into that?

**Comment by matkoniecz** [comment]
Is there any other quest that is doing geometry checks and supporting undo? (entrance quest checks is it within building line and checks value of `building=` key)

**Comment by westnordost** [comment]
"Is there a crossing? " for example. 

All quests support undo.

**Comment by matkoniecz** [comment]
Looking at it:

```
    override fun isApplicableTo(element: Element): Boolean? =
        if (element !is Node || element.tags.isNotEmpty()) false else null
```

it seems that undone crossing quest will also disappear.

I also tested it and it actually happens.

So fixing this would require implementing doing geometry checks on undo.

**Comment by westnordost** [comment]
Eh, what are you on about? Don't you know what happens when that function returns null?

**Comment by Helium314** [comment]
Issue is that this is not valid for crossing and entrance quests: https://github.com/streetcomplete/StreetComplete/blob/2499d77d5a638804a46b8bddd886b4a34d5e506f/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestController.kt#L202-L204

**Comment by westnordost** [comment]
Thanks for the find, @Helium314

**Comment by matkoniecz** [comment]
> Eh, what are you on about? Don't you know what happens when that function returns null?

apparently not! I thought that it means that undo was not supported - but was unsure, so I tested it which seemed to confirm it.
