### ISSUE TITLE
Quest on cycle lanes does not fit actual options in Hungary (neither text nor images)

### ISSUE THREAD

**Issue by Antissimovero** [streetcomplete/StreetComplete#4502]
Hi All! I have identified a problem which is causing a lot of mistagging in Hungary.

The quest on cycle lanes has multiple issues:

1) The Hungarian translation is at almost every item mistaken - it seems to be a word-wordly translation, not taking into account the real and widely known Hungarian names of each type of infrastructure. E. g. it mixes up "cycle track" and "cycleway"; calls a non-segregated foot- and cycleway "common sidewalk" etc. How can I propose proper wording to get it implemented?

2) cycle_lane=exclusive is depicted with continuous white lane and is named "kerékpársáv" [cycle lane]. cycle_lane=advisory is depicted with dashed white line and it is named "kerékpársáv (szaggatott vonal)" [cycle lane (dashed line].
In reality,
- a normal cycle lane (kerékpársáv, cycle_lane=exclusive) is painted with yellow. The line can be either continuous or dashed (where it is allowed to cross e.g. for parking).
- an advisory cycle lane (called "nyitott kerékpársáv" [open cycle lane], cycle lane=advisory) is painted with white. The line is always dashed.
This problem leads to many normal cycle lanes being tagged as advisory, as the quest asks if the line is dashed, but that is not the difference between the two types.

Thanks,

Antissimo

**Comment by riQQ** [comment]
For translation see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by westnordost** [comment]
I'll take care of the picture

**Comment by Antissimovero** [comment]
> For translation see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

Thanks for the hint, I updated the translations.

**Comment by Antissimovero** [comment]
> I'll take care of the picture

Great, thank you! If it is possible to have separate pictures for Hungary, I try to describe what would be needed:

1. quest_cycleway_value_track: pictogram and arrow should be yellow
2. quest_cycleway_value_lane: line, pictogram and arrow should be yellow. Line can be both continuous and dashed (I'm not sure how to depict this, maybe part of the line continous, part dashed)
3. quest_cycleway_value_lane_soft: OK as it is (white dashed line, white pictogram and arrow)
4. cycleway_value_shared: pictogram and arrow shoud be yellow
5. quest_cycleway_value_bus_lane: the bicycle icon should be yellow. "BUS" should be "BUSZ"
6. quest_cycleway_value_sidewalk: the icons should be yellow (both the pedestrian and the cyclist)
7. quest_cycleway_value_lane_dual: all lines, pictograms and arrows should be yellow
8. quest_cycleway_value_track_dual: all lines, pictograms and arrows should be yellow

If this all is too much, 2. 4. and 7. are the most important, the rest is not misleading.

Thank you very much!

**Comment by westnordost** [comment]
I planned to make the exclusive cycle lane dashed yellow and the advisory cycle lane dashed white.

Why should the pictogram lane be yellow? Why should it be yellow on a bus lane? Can you link a source?

I do not plan to translate the "BUS" marking into each language, "BUS" must do.

Why would the track be yellow? It is on the sidewalk/behind the curb, usually there are no markings at all.

**Comment by Antissimovero** [comment]
Exclusive cycle lane dashed yellow (#2): it is yellow indeed. According to the Road Code, It can be continuous or dashed (at crossings and where there is a parking lane besides). Also refers to the two-way bike lane (#7). Reference: Hungarian Road Code, 18. § (road markings) (1) https://net.jogtar.hu/jogszabaly?docid=97500001.kpm This is indeed the most important, as this is mixed up often by StreetComplete users.

Advisory cycle lane (#3): dashed white - no need to change here, as the current image matches perfectly.

Pictogram lane (#4): it is simply yellow in Hungary. It is sometimes mixed up with advisory cycle lane, so it would be good to have a matching image with yellow picto. Reference: Road Code image "158/k. ábra" https://net.jogtar.hu/jogszabaly?docid=97500001.kpm, planning standards page 22, search for "22. oldal" https://ume.kozut.hu/dokumentum/84

Bus- and bike lane (#5): the bike icon is simply yellow in reality.  Reference: Road Code image "158/k. ábra" https://net.jogtar.hu/jogszabaly?docid=97500001.kpm, planning standards page 22, search for "22. oldal" https://ume.kozut.hu/dokumentum/84 image "158/i. ábra" planning standards pages 23 and 24, search for "23. oldal" https://ume.kozut.hu/dokumentum/84

Cycle track (#1, #8): for the yellow markings, see planning standards page 32 and 38, search for "32. oldal" and "38. oldal". https://ume.kozut.hu/dokumentum/84 

But as said, 2. 7. (exclusive cycleway, 2-way cycleway) and 4. (pictogram lane) are the most important, as they are getting mixed up by users. 
The rest is just about matching the images with the actual rules, but they are not misleading, so not that important.

I hope it is clearer now. Thanks,

**Comment by westnordost** [comment]
I am (also) going to research the bicycle markings in all the other countries (and document the findings in https://github.com/streetcomplete/countrymetadata/ ) to have this solved comprehensively. Help is appreciated, especially if it leads to some legislation source. Hungary I have all the info I need now, thank you, maybe someone can point me to other sources too.

**Comment by westnordost** [comment]
Does the nyitott kerékpársáv include a bicycle pictogram?

**Comment by Antissimovero** [comment]
> Does the nyitott kerékpársáv include a bicycle pictogram?

Yes.
Road Code 18.§  (10) [(text and translation)](https://www.deepl.com/translator#hu/en/(10)%20*%20%20A%20nyitott%20ker%C3%A9kp%C3%A1rs%C3%A1vot%20-%20amely%20a%20ker%C3%A9kp%C3%A1rosok%20k%C3%B6zleked%C3%A9s%C3%A9re%20kijel%C3%B6lt%20s%C3%A1v%20-%20az%20%C3%BAttesten%20felfestett%20feh%C3%A9r%20sz%C3%ADn%C5%B1%20szaggatott%20vonal%20%C3%A9s%20ker%C3%A9kp%C3%A1rt%20mutat%C3%B3%20burkolati%20jel%20is%20jelzi.%20)
