### ISSUE TITLE
Last answer shortcut button for only one streetside

### ISSUE THREAD

**Issue by Henry00572** [streetcomplete/StreetComplete#4503]
**Use case**
In the quest for sidewalk surfaces (for example) the previous answer is displayed as a shortcut in the bottom left of the quest popup. However, when the quest only asks for one side (e.g. quest for `sidewalk:right:smoothness` becaue `sidewalk=right` is already set), this shortcut doesn't show up.

Other examples include the `cycleway` and `shoulder` quests on `highway`s with `oneway=yes`.

**Proposed Solution**
It might just be a matter of changing one if-statement, but I'm not sure where the relevant code is. (Is it https://github.com/streetcomplete/StreetComplete/blob/00f00f60b192bda332dae5249b5fdcd099148f29/app/src/main/java/de/westnordost/streetcomplete/view/controller/StreetSideSelectWithLastAnswerButtonViewController.kt?)

**Comment by westnordost** [comment]
No. That would save you just one tap while burning its usefulness when you come back to a road with sidewalks on both sides.

**Comment by westnordost** [comment]
Hm, on the other hand it works this way for overlays right now, so it would be consistent. 

I remember now another reason why this was not done: Only one last-answer is saved. If you save it for just one side, and then open the quest for a road that has two sides, applying that last answer would not even fill the form completely (-> OK button does not appear), which doesn't really help the user. Fiddling about something like either saving two/three last-answers and checking which side... etc... is too complex.

For me the question is right now if for **overlays** the behavior should be the same as for quests, i.e. the selection is only saved if it specified for both.

**Comment by Henry00572** [comment]
I understand why I wasn't done. The ideal solution I imagined would have saved multiple last-answers and showed the one fitting to the quest, but you have to judge whether this is worth the effort for saving one tap. For the user it would also help if the last-answer to a twosided quest was partially shown for the next onesided quest as well, with only one side, but again this might be too complex.

I think quests and overlays should be consistent in general. As far as I know the current overlays only apply to properties of the `highway` itself or of both sides, but never of one side only, so the problem only arises when the user saves a partially filled in quest and in this case the partial answer might as well be displayed for the next quest.

**Comment by westnordost** [comment]
In quests,  you cannot answer partially (e.g. only on one side). With overlays however, you can.

**Comment by Henry00572** [comment]
That's reasonable.

> For me the question is right now if for overlays the behavior should be the same as for quests, i.e. the selection is only saved if it specified for both.

I think for overlays it's especially useful if a partial answer is also saved and can be accessed by the shortcut, because most streets are split in many parts and if you answer partially for one of them, you will often give the same partial answer for the remaining parts.

**Comment by westnordost** [comment]
Well, ... then I leave everything as-is.
