### ISSUE TITLE
Quest - type of manhole

### ISSUE THREAD

**Issue by Matthias84** [streetcomplete/StreetComplete#4504]
### General
Affected tag(s) to be modified/added: [manhole](https://wiki.openstreetmap.org/wiki/Key:manhole)
Question asked: **What kind of manhole is this?**

Usually the [big round covers](https://commons.wikimedia.org/w/index.php?search=schachtdeckel&title=Special:MediaSearch&go=Seite&type=image) indicate water system, while rectangle ones indicate power, communication or other technical systems.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

Every node with man_made=manhole but without a manhole=* tag

**Metadata needed:** 

**Proposed UI:**

Like the usual quest picker for single answers with a icon / photo of round or rect manholes.

**Comment by Helium314** [comment]
> To be added tag is established and has a useful purpose

What is the use of this tag?

> Easily answerable

The tag values in the liked wiki page are about what's inside, how can an unexpericenced user know about this?
Especially you say that "while rectangle ones indicate power, communication or other technical systems", but the values require being more precise, e.g. to separate between `power` and `telecom`. So It seems that the shape is not a not enough, and I assume it's also not reliable.
Are there other markings on the covers that provide the needed information?

**Comment by matkoniecz** [comment]
I see no reason to assume perfect correspondence of shape to function, and in my area `power` and `telecom` use both rectangular ones. With some not marked in any way.

**Comment by Matthias84** [comment]
Like street cabinets I see your point here, that it's hard(er) to distinguish for non local mappers.

But might it make sense to alter the quest to 'Is this a round manhole?' and  only then set the manhole=water  tag?
