### ISSUE TITLE
Quest - type of street cabinet

### ISSUE THREAD

**Issue by Matthias84** [streetcomplete/StreetComplete#4505]
### General
Affected tag(s) to be modified/added: [street_cabinet](https://wiki.openstreetmap.org/wiki/Key:street_cabinet)
Question asked: **What kind of street cabinet is it?**

Usually labels indicate the type of box and the operrator.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Every man_made=street_cabinet without any street_cabinet=* tag

**Metadata needed:** 

**Proposed UI:**

Nothing special, answers showing power, telecommunication (DSLAMs) or Boxes close  to rails / traffic lights, ...

**Comment by matkoniecz** [comment]
> To be added tag is established and has a useful purpose

how this can be used/is used?

> Easily answerable by any pedestrian from the outside but a survey is necessary

How someone is supposed to distinguish telecommunication/power/traffic lights control on a box without labels?

How mapper can distinguish traffic_control from traffic_monitoring (or tag something that does both)?

How one may distinguish power from street_lighting? Both will have warning about electricity.

**Comment by mnalis** [comment]
- related: https://github.com/streetcomplete/StreetComplete/issues/3157

**Comment by matkoniecz** [comment]
Closing as I have no idea how mapper can reliably classify street cabinets based solely on their location.

Maybe some areas have strictly assigned styles of street cabinets or almost always have labels, but which ones?

Also: how this can be used/is used?

**Comment by flacombe** [comment]
This is a local knowledge matter: appearance of cabinets make them distinguishable among different utilities.
But it requires country or regional specific pictures, to trigger mappers about shapes, colour or even operators logo.

It can't be done globally I'm affraid.
