### ISSUE TITLE
Option for map following current position

### ISSUE THREAD

**Issue by DSiekmeier** [streetcomplete/StreetComplete#4511]
**Use case**
I usually fulfill some quests while walking around the streets. In that case I manually have to scroll the map to see the current place or tap on the "jump to position" button. It would be nice is this happens automatically.

**Proposed Solution**
Selecting of the following feature should be done on the main screen. It might be integrated into the "current position" button via toggling maybe. The zoom level should not be changed.

**Comment by westnordost** [comment]
That's exactly what that button already does.  However, if you move the map manually, even by the tiniest amount, the follow-me mode is deactivated (button icon turns from orange to black). Then,  you need to tap it again to activate it again.
