### ISSUE TITLE
Quick change button for overlays

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#4512]
**Use case**

When mapping I find that the need to switch overlays occurs quite frequently as I am interested in mapping both street lighting and sidewalks and occasional parking restrictions. I would find it very useful to have a way of quickly swapping between overlays. At the moment this is currently the same 4 taps as to turn them on in the first place and means I often have to stop moving to do this even if mapping on foot.

**Proposed Solution**

My preferred solution for a quicker way to change overlay would be to add a button similar to the upload and menu buttons placed below the star that accesses your profile. In my preferred implementations this would ordinary display just the icon used for the overlay selection in the original menu and would expand in place to show the three options when tapped.  The "no overlay" option would be the only menu item requiring confirmation as it is the only one that removes the new button. Accidental activation of the new menu would be dismissed by tapping the current selection.

 Alternatively tapping the icon could display the original menu when tapped. This would only save one tap compared with the current interface but the taps would at least be in a single arc of the thumb.

To avoid confusing new users StreetComplete would not show this button if no overlay was active in the first place. The presence of the overlay icon will also serve as a reminder to users which overlay is active in instances where most of the ways are showing as unmapped, for example in lightly mapped areas where it may not be clear whether you are on a parking overlay or the sidewalks overlay.

**Comment by riQQ** [comment]
Another request in discussion: #4525

**Comment by westnordost** [comment]
Hmm, I am going to reject this feature request for now. Reasons:

<ol>
<li>Overlays were designed with the explicit design goal in mind to focus <b>on one thing only</b> (initially even to hide all quests while active). 

This design decision makes it possible to have a very streamlined interface and not cram everything related to one or several topics (e.g. cycleway, cycleway width, cycleway surface, smoothness, segregation to sidewalk....) somehow into one overlay.  
  
Imagine there were overlays for all the cycleway related things I mentioned above - even with a quick switcher as you propose, it would be super clumsy and inefficent, a pain in the ass, to switch forth and back all the time. There are (or should be) more efficient tools to "map all the things". Maybe in some future version of EveryDoor or a similar editor that attaches importance to both efficient mapping and UX but also with the design goal to "map all the things".</li>

<li>As you wrote, it only saves one tap. This is really not worth the screen space in my opinion, even if quick switching between overlays would be encouraged.</li>

<li>Additionally, on the suggestion made in #4525, this has two issues: Firstly, for small smartphones, at that position there is not really space for an additional button if you rotate the phone to landscape mode. Second, with the number of overlays quickly growing, it will become necessary to redesign the selection dialog, in the process probably also provide additional information (in the form of a short description about each overlay, possibly leading to that this selection screen must be full screen</li>
</ol>
