### ISSUE TITLE
Wireframe/Skeleton display option for some way based tasks.

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#4513]
**Use case**

When attempting to map sidewalks and cycle ways it is sometimes difficult to see if the display separately on map option should be selected due to the width of adjacent ways as rendered. This is especially common for higher ranked roads that display very wide on screen and are more likely to have separately mapped paths.

**Proposed Solution**

When quest is active and awaiting input add a button to 'slim down' rendering of ways to the display widths of a more zoomed out view. This could take the form of an icon showing an X-ray image or bone to denote that there is less "flesh" on the geometry, or if this might have too many negative connotations for some users then something like JOSM's wireframe view icon.

**Comment by InsertUser** [comment]
The area I'd thought of when writing this was [this bridge] whose abutters appear to have actually been mapped only as a cycleway now that I look more closely (need to check signage next time I pass as I thought it was only a cycleway on the north side). There are paths further west that render on top of the sidwalk overlay so maybe it's already fixed by the draw order when `foot=yes` is set? [This road] was also one where I wasn't sure if the sidewalk to the south had been mapped separately or not from the StreetComplete view.

[this bridge]: https://www.openstreetmap.org/way/168864265/
[This road]: https://www.openstreetmap.org/way/152259825

**Comment by Helium314** [comment]
Thanks!
So I think the issue is that `highway=trunk` is displayed as having 20 m width, and the sidewalk quest is asked (in this case) if a sidewalk is at least 8 m away from the center line.
Maybe this should be increased to at least 11 m (half the displayed width plus displayed path width).

@mnalis you're currently working on adjusting this minimum distance, right? I think the quest should not be asked if the path might be displayed inside roadway.

**Comment by mnalis** [comment]
> you're currently working on adjusting this minimum distance, right? 

Yes in this simple PR https://github.com/streetcomplete/StreetComplete/pull/4499; but the idea seems to be (https://github.com/streetcomplete/StreetComplete/issues/4494#issuecomment-1278117729) to **_ask the quest even more often_** (i.e. when the **_sidewalks are even closer to the road_**) which would probably only increase occurrence of this problem.

> I think the quest should not be asked if the path might be displayed inside roadway.

Reasonable idea, but the calculating code AFAIK works only with OSM element distances, and has no idea of Tangrem-ES rendering styles and their width calculations (i.e. IRL meters vs. screen pixels).

Another idea make sure the path has higher rendering priority/different color, so is shown even if the road is drawn too wide?)

**Comment by Helium314** [comment]
see [roads.yaml](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/map_theme/jawg/layers/roads.yaml)
You have width like `width: [[8, 1px], [14, 8px], [18, 20m]]`, so at high zoom the width is 20m, while at lower zoom it's given in pixels so roads are always shown.

**Comment by mnalis** [comment]
One would need to know programatically:
- what is current zoomlevel **at the moment** (or _at least_ what it was when quest was clicked on, as one can zoom in/out while inside a quest)?
- how to read that `roads.yaml` code from quest and how to parse interesting info from it.

---

So if one could know both (which sounds quite complicated to me), one could do something universal like:

```
if (roadWidthSpecifidInYamlForCurrentRoad() > calculatedDistanceInMeters() then return 'quest skipped';
```

Still, someone quite knowledgable would have to write `roadWidthSpecifidInYamlForCurrentRoad()` (we already have the equivalent for `calculatedDistanceInMeters()`). Doing that is waaay beyond my capabilities, though.

---

Alternatively, I one knew **only** the `zoom level` (which might be possible), but **not** how to parse the yaml: then one could hardcode values in quest, but that would IMHO look very kludgy and would need to be kept in sync manually (which sound way too maintenance-heavy to me!):

```
if (zoomlevel==18  and tags["highway"]=="motorway" and calculatedDistanceInMeters() < 20) then return `quest skipped`
if (zoomlevel==18  and tags["highway"]=="motorway_link" and calculatedDistanceInMeters() < 6) then return `quest skipped`
if (zoomlevel==18  and tags["oneway"]=="yes" and calculatedDistanceInMeters() < 10) then return `quest skipped`
if (zoomlevel==19  and tags["highway"]=="primary" and calculatedDistanceInMeters() < 6) then return `quest skipped`
[... and dozens of other similar checks ...]
```

---

Or did you envision it some other way, @Helium314 ?

**Comment by matkoniecz** [comment]
I would rather try to change

>  So I think the issue is that highway=trunk is displayed as having 20 m width, and the sidewalk quest is asked (in this case) if a sidewalk is at least 8 m away from the center line.

so ways are rendered as smaller than their range where sidewalk quests are suppressed.

**Comment by Helium314** [comment]
> Or did you envision it some other way, @Helium314 ?

I would simply require `getMinDistanceToWays` to be at least `width / 2 + path_witdh`, which would be 11 m for the case above.
e.g.
```kotlin

    private fun getMinDistanceToWays(tags: Map<String, String>): Float {
        val width = (
            (estimateRoadwayWidth(tags) ?: guessRoadwayWidth(tags)) +
            (estimateParkingOffRoadWidth(tags) ?: 0f) +
            (estimateCycleTrackWidth(tags) ?: 0f)
        ) / 2f +
        4f // + generous buffer for possible grass verge
        val displayedWidth = // something that returns 20 m  for trunk, etc...
        return width.coerceAtLeast(displayedWidth / 2 + 1f) // 1f is path width
    }
```

**Comment by mnalis** [comment]
Yeah, that would be my first case (`[...] So if one could know both (which sounds quite complicated to me), [...]`)

> I would simply require [...]
>         val displayedWidth = // something that returns 20 m  for trunk, etc...

That must be some new definition of the word `simply` that I wasn't previously aware of  :open_mouth: :smile:

**Comment by Helium314** [comment]
Compared to your approach of parsing the yaml file and using current zoom it's definitely simple.

**Comment by Helium314** [comment]
That's not what I meant... I would expect the user to zoom in if things are not clear, and then only the meter-values are relevant.

But anyway, I'm also testing an alternative as the cache now allows for much larger bbox highlighting. #3594 is implemented for cycleways and sidewalks in EE (though you'll need to compile the current version).

**Comment by Helium314** [comment]
> > Compared to your approach of parsing the yaml file and using current zoom it's definitely simple.
> 
> I maybe misunderstand, does not that `val displayedWidth // something that returns 20 m for trunk, etc...` mean exactly that? i.e. require parsing the yaml to determine how wide Tangrem-ES is displaying something?

Btw here you have exactly what I meant:
https://github.com/streetcomplete/StreetComplete/blob/7d480c80776607ddb244889bbaed2f567c5d1b47/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/components/StyleableOverlayMapComponent.kt#L99-L108
And yes, I still think it's simple.

**Comment by westnordost** [comment]
Hm, the source of this issue is that `highway=trunk` in Britain are much narrower (only two lanes) than one would expect. It seems, in Britain, `highway=trunk` is used as simply one level more important than `primary` in the road network.

**Comment by mnalis** [comment]
It happens elsewhere too... For example this is on `tertiary`. Left sidewalk is clearly visible as separately mapped, but on right side, it depends (on lower half of screenshot it is visible, on the middle and upper half not really).  

![small_Screenshot_20221021_152748_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/197910215-e0aeb391-2675-49b4-b200-2782974e343f.jpg)

My alternative idea was to make sure the path has higher rendering priority/different color than the road when answering the quest, so that it is shown even if the road is drawn too wide (and/or the path is drawn very close to the road).

**Comment by westnordost** [comment]
Hm, best solution I can think of is to make the roads appear even a bit more narrow (especially the trunk).

**Comment by matkoniecz** [comment]
@mnalis Where our case is located?

https://www.openstreetmap.org/way/168864265/ https://www.openstreetmap.org/way/152259825 were provided as examples already, I guess that narrowing trunk even more can be a viable solution (and better than completely new mode/setting increasing complexity)
