### ISSUE TITLE
Not asking how many bike can be parked in a `bicycle_parking=floor`

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#4514]
**Use case**
There is a lot of `bicycle_parking=floor` in my neighbourhood and StreetComplete is asking me how many bikes can be parked there. Here is a picture of one them from a local newspaper: https://www.ledauphine.com/transport/2021/12/16/isere-transport-metropole-de-grenoble-encore-plus-de-trottinettes-et-de-velo-a-assistance-electrique-en-2022

The issue is that it’s very difficult to say! There is no mark on the ground to clearly separate bikes space. They usually occupy roughly the space used by 5 bollards, so I’m tempted to respond 10… but ocasionnally, commercial shared biked are added there in bunch, and they can place much more bikes than 10 in the space.

**Proposed Solution**
I feel that it is outside the scope of StreetComplete to ask how many bikes can be parked in a `bicycle_parking=floor` (too difficult or too subjective to answer): I would add an exception to the quest. This quest already appears after the bicycle parking type quest, so it shouldn't cause additional difficulties.

Maybe there are places where `bicycle_parking=floor` have a clear demarcation between bikes. (I’m not aware of such, but I can imagine that this exists.)

**Comment by Helium314** [comment]
Can you link to such a place where SC asks?
`bicycle_parking=floor` is already excluded from the quest, and in a quick test I didn't get the quest for a `bicycle_parking=floor` without capacity.

**Comment by matkoniecz** [comment]
I bet that it is mistagged in OSM as `bicycle_parking=stands` or not marked as `floor`.

See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bike_parking_capacity/AddBikeParkingCapacity.kt#L18

Requiring `bicycle_parking` to be tagged is an option here.

**Comment by Mbodin** [comment]
I found it back. It was this one: https://www.openstreetmap.org/node/7035705719 And indeed, it wasn't an issue with StreetComplete, as it was tagged as `stands`. I mistook it for a nearby floor bike parking which is not yet mapped (I’m on the way to add it ☺).
