### ISSUE TITLE
Adjust opening hours in shop overlay

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4516]
**Use case**

Walking in the downtown in your holiday and see a sign "new opening hours since 2022-10-01".

**Proposed Solution**

Right now we have the dialog:

> [icon] shop type name
> Name: shop name

To solve this feature request we could have them below

> [icon] shop type name
> Name: shop name
> Opening hours:
> Mo-Fr: 9:00-17:00
> Sa: 10:00-14
> [edit opening hours]

or as a separate button to expand the view:

> [icon] shop type name
> Name: shop name
> [view opening hours]

**Comment by westnordost** [comment]
This is out of scope for what the overlays are intended for.

**Comment by mnalis** [comment]
One might've hoped that Shop overlay would allow to force answering other Shop quests too (not just `shop type` and `name`)...  (kind of like EveryDoor does when editing existing amenity)

Anyway, there is a (quite kludgy) workaround:

- in `Shop overlay`, change the name of the shop (like adding `!` to the shop name) and confirm it
- in `Shop overlay`, change back the name of the shop (like removing `!` from the shop name) and confirm it
 - now `opening_hours`, `payment types`, etc. quests will all be asked again

(I personally prefer to open EveryDoor and edit it there, though - as it does not lose all existing answers forcing me to re-answer everything, but allows me to change just the one attribute I want to change)

- but maybe something like https://github.com/streetcomplete/StreetComplete/issues/124#issuecomment-1272550816, allowing the user to answer *other quests* on current element, might solve this problem too (if it would show all matching quests but even if their resurvey period has not come up yet).

**Comment by westnordost** [comment]
Yeah, don't do that. Use EveryDoor for adding detailed data to POIs.

**Comment by RubenKelevra** [comment]
> **Use case**
> 
> Walking in the downtown in your holiday and see a sign "new opening hours since 2022-10-01".


You can just create a note for that, and do the edit at home. :) 

Sure having the ability to edit every detail would be nice, but that's going to be an endless list of feature requests ;) 

If you want to do live edits on a poi you can also just use Vespucci, press long on the map and select the app you want to edit with. :)

**Comment by mnalis** [comment]
FYI, in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork, that is achievable already:

One can select  `Show/edit tags` from the <code>&#xFE19;</code> menu while in _Shops overlay_, remove the `opening_hours` tag, and click on the newly created `opening_hours` icon which will open regular StreetComplete form for inputting new opening hours.

**Comment by mnalis** [comment]
- (ref: https://github.com/streetcomplete/StreetComplete/discussions/6877)
