### ISSUE TITLE
new shops without icon are not displayed in Shop Overlay

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4519]
**How to Reproduce**
add a new show with the shop overlay. Select a shop, which has no icon assigned, e.g. "Feinkostladen" (is the tag for that shop=deli?). Accept this new shop without giving it a name. Now you cannot see it on the map and thus cannot select it anymore in order to add a name.

**Expected Behavior**
I can see the shop on the map and can select it.

**Versions affected**
48.0-beta1

**Workaround**
I used the undo function to remove the shop and add it correctly again.

**Comment by mnalis** [comment]
I can confirm that. It seems that `shop=deli` (_"Delicatessen"_) does note have an icon, so it might be why problems arise there and not with other shops (there might be other shops without icons though - and thus also problematic).

![small_Screenshot_20221017_195930_de westnordost streetcomplete mn debug](https://user-images.githubusercontent.com/156656/196249382-21132988-406c-43bf-b0c7-58c936b7cdd9.jpg)

**Comment by Helium314** [comment]
Interestingly there is no `name` quest for `shop=deli`, which means that
https://github.com/streetcomplete/StreetComplete/blob/67114b83df09959dbea90126a426d69c382aa174/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt#L143-L144
must return false... even though we just selected this feature by its name.

**Comment by westnordost** [comment]
Some icons used in the iD presets are missing from the public repository where the icons come from. The repositories are 

https://github.com/streetcomplete/StreetComplete/blob/67114b83df09959dbea90126a426d69c382aa174/buildSrc/src/main/java/DownloadAndConvertPresetIconsTask.kt#L199-L211

In this case, the icon name is `fas-jar`. It is missing from https://github.com/FortAwesome/Font-Awesome/tree/master/svgs/solid .

Run `gradle downloadAndConvertPresetIcons` to see which icons cannot be downloaded.

**Comment by westnordost** [comment]
I've added a "fallback url" for font awesome, so the downloader first tries the 6.x branch because **I suppose** these are the most current ones, then falls back to the master branch

**Comment by matkoniecz** [comment]
I opened https://github.com/openstreetmap/id-tagging-schema/issues/616 and https://github.com/FortAwesome/Font-Awesome/issues/19387

**Comment by Strubbl** [comment]
Maybe i did not understand the solution yet. In SC, don't we want a fallback or default icon for amenitys/shops, which do not have an icon? This way newly added amenitys/shops would at least get displayed in the shop overlay.

**Comment by westnordost** [comment]
In StreetComplete, it's solved now

**Comment by tyrasd** [comment]
> And if I change it to [v6] the following icons are not found.

Well, fontawesome has a concept of _aliases_ (many were introduced to maintain backwards compatibility when icons were refined over time). It makes it a little bit harder to consume the icons directly, but if you can't use the js library they officially provide, I guess an alternative approach to _including old major versions in a fallback chain_ would be to consume the "raw" data (e.g. https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/metadata/icons.json) and parse the aliases manually.

PS: I will pay attention to in the future to include higher requirements of icon library versions in the changelog of the id-tagging-schema.
