### ISSUE TITLE
Building with tourism=chalet does not trigger building type quest, blocking building level and roof quest

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4521]
**How to Reproduce**
The quests for building levels and roof is not displayed for buildings, which have the tags building=yes and tourism=chalet.

E.g.: https://www.openstreetmap.org/way/209266481

**Expected Behavior**
The quests building levels and roof are displayed for this kind of building.

**Versions affected**
48.0-beta1

**Comment by Helium314** [comment]
Well, it's more that `building=yes``doesn't trigger the quest.

**Comment by Strubbl** [comment]
Ok, i mean, if i have a usual building with building=yes, the quest for the type of the building is shown. Afterwards the levels and roof quest.
My expectation here would be, that the type of the building is known to SC, so that levels and roof quest shall be asked. If the type of building is not clear to SC in the mentioned example, the quest for the type of building shall be shown.

**Comment by matkoniecz** [comment]
Maybe allowing `building=yes tourism=hotel|...` in [AddBuildingLevels.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.kt) makes sense?

**Comment by matkoniecz** [comment]
if you click "blame" button you will get https://github.com/streetcomplete/StreetComplete/blame/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L20 view showing latest commit that edited each line

in this case https://github.com/streetcomplete/StreetComplete/commit/f89bde74cc26859fcec5ee48d4c94f178eff63b9 is linked which mentions #1854 - reading through it may answer your question

**Comment by westnordost** [comment]
I think the current behavior is fine. The alternative would be that the building levels quest will need to ask also for `building=yes` **if** it also has any of a long list of other tags - `tourism=chalet` is certainly not the only one. Just think about for which buildings tagged with `amenity=*` the building levels should be asked.... I think it would become a very long list that would need to be maintained.

**Comment by westnordost** [comment]
So I'll close this for now. 

If someone is really interested in this, he can surely experiment with it and see what additional tags this should apply to. If the list is not too long and not too needy for maintenance, maybe it could be included.
