### ISSUE TITLE
Don't ignore contradictory `*:surface=*` and `surface=*` tags

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#4526]
**Use case**
When SC asks for `footway:surface=*` and `cycleway:surface=*` on a segregated `highway=path`, it does not change `surface=*`, even when it is contradictory. 

See for example [this path](https://www.openstreetmap.org/way/134592975).
<table>
<tr><td>biclycle</td><td>designated</td></tr>
<tr><td>cycleway:surface</td><td>paving_stones</td></tr>
<tr><td>foot</td><td>designated</td></tr>
<tr><td>footway:surface</td><td>paving_stones</td></tr>
<tr><td>highway</td><td>path</td></tr>
<tr><td>segregated</td><td>yes</td></tr>
<tr><td>surface</td><td>asphalt</td></tr>
</table>

**Proposed Solution**
Three possibilities (in ascending effort):
1. StreetComplete should delete a mismatching `surface=*` tag 
2. StreetComplete should change it according to `footway:surface` and `cycleway:surface`, but only if both are the same
3. StreetComplete should also change `surface=*` tag if `footway:surface` and `cycleway:surface` are not the same, but both are paved or unpaved (for example `footway:surface=paving_stones` and `cycleway:surface=asphalt` → `surface=paved`). If one way is paved and the other one unpaved, it should add them via semicolon (e.g. `surface=asphalt;dirt`).

**Comment by mnalis** [comment]
Make sense to me.

If someone wants to give it a try, leave a comment stating so. 
(if noone steps up, I can give it a try in few days, for option `2`  with fallbacking to `1` or maybe `3`)

**Comment by Discostu36** [comment]
One thing I forgot about is that options 2 and 3 of course could also be used to add missing `surface`-Tag, not only change it.

**Comment by RubenKelevra** [comment]
> One thing I forgot about is that options 2 and 3 of course could also be used to add missing `surface` tag, not only change it.

Nah, if there are two explicit surface information, I would keep them both. Explicit is always better than implicit IMHO. For example that could be the only part of the way which has the same surface and in the next part they differ again.

With just one tag I would second guess if the information is complete for this part.

**Comment by mnalis** [comment]
> Nah, if there are two explicit surface information, I would keep them both. Explicit is always better than implicit IMHO

Agreed, but if I understood @Discostu36 correctly (hopefully I did, as i did the PRs :smile:), it would keep both of them, **and then add** `surface` too. E.g. final result of such tagging would be:

```
cycleway:surface=asphalt
footway:surface=asphalt
surface=asphalt
```

and **_not_ just**:
```
surface=asphalt
```

**Comment by Discostu36** [comment]
@mnalis You understood my intent correctly. It is a bit redundant, but I think it is the best solution.
