### ISSUE TITLE
Unable to select the Sidewalk overlay if there is a Note on it

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4529]
Once upon a time I [left a note](https://www.openstreetmap.org/note/3095650) when answering Sidewalk quest. Now, when I enable Sidewalk overlay and try to click on that way (not on the note!), instead of opening Sidewalk overlay answer window, it opens that Note. 

**How to Reproduce**
- enable Sidewalk overlay (and disable all quests if wanted)
- navigate to this [Vinkovačka ulica](https://www.openstreetmap.org/way/144140926) road
- try to click on the road far away from the note
- Note window opens

https://user-images.githubusercontent.com/156656/196558340-71c1e5e8-7060-4664-bc66-321d5de0d51b.mp4

**Expected Behavior**
I would expect that instead of the Note window, an Sidewalk overlay chooser would open.

**Versions affected**
Both SC `47.2` upstream, and my fork with `48.0-beta1+`; Android 10

**Comment by mnalis** [comment]
It also happens with other way-related overlays, e.g. `Street lightning overlay` or `Street parking overlay` when clicking on that way.

**Comment by westnordost** [comment]
This is a feature, not a bug.

**Comment by westnordost** [comment]
Well that's how the notes work. They block **all** quests until they are solved, because **something** is amiss that must be solved first (outside of the app). And hence, also all editing with overlays.

However, thank you for the hint regarding the crash, I'll have a look.

**Comment by mnalis** [comment]
(added a [FAQ entry](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Editing_in_Overlay_mode_opens_Notes_instead))

**Comment by westnordost** [comment]
I added a fix now.  It will not crash anymore. Instead of "No, hide" if it is already hidden (as a quest), just "No" is displayed, which just closes the form. (Hiding has no effect on it being shown in overlays, only it being shown as a quest.)

https://github.com/streetcomplete/StreetComplete/commit/92b27342657f2b3837e01eae6a380be99b74c2c8
