### ISSUE TITLE
Wrong changeset comment "Determine road widths" 

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#4532]
I split the way to set the parking availability tags on one part of the road but it has an unusual chageset comment "Determine road widths"

https://www.openstreetmap.org/changeset/127793335
https://www.openstreetmap.org/way/1105290224#map=19/50.41296/-4.16306
https://www.openstreetmap.org/way/974385263/history

No road width tags have been set on either of the ways

A simple test did not reproduce

**Comment by timothywashere** [comment]
Could not reproduce

**Comment by Helium314** [comment]
It's a very late reply, but what happened is that the way was split (one v1 node and one v1 way created)
