### ISSUE TITLE
Notes created from overlay show the localized overlay name

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#4533]
**How to Reproduce**

Use StreetComplete not in English, but another language. Create a note from one of the overlay quests. This note now says in the beginning something similar to »In context of "Parkstreifen" overlay for [https://osm.org/​way/​1101049590](https://osm.org/way/1101049590) via StreetComplete 47.1«

**Expected Behavior**

The non-user-entered part of the node should be uniformly in one language, most likely English. This already happens for normal quests where the English quest name is used, regardless of the user's language (»What kind of building is this?«).

**Versions affected**

SC 47.2
Android 11

**Comment by FloEdelmann** [comment]
Already fixed by #4506, which is not yet released.
