### ISSUE TITLE
Street parking overlay creates duplicated tags

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4534]
The street parking overlay seems to tag ways with duplicated information for `:left` or `:right` and `:both`. From what I have seen so far, either the `:right` or `:left` key appears to duplicate the value of the `:both` key. I did not find any inconsistent information between these keys.

I do not know how to reproduce this issue, but I found many examples of this type of tagging on osmose, which reports this issue as "[Too many parking:lane:[side]](https://osmose.openstreetmap.fr/en/issues/open?item=3161&class=31614)". Listed below are some ways that now have duplicated `parking:condition` and/or `parking:lane` tags after they were edited using StreetComplete: 

- https://www.openstreetmap.org/way/1104454759/history
- https://www.openstreetmap.org/way/22943015/history
- https://www.openstreetmap.org/way/1104455061/history
- https://www.openstreetmap.org/way/1105429683/history
- https://www.openstreetmap.org/way/1104422600/history

Most of the changesets that introduced this type of tagging were created using v47.1 and v47.2 of StreetComplete.

**Comment by westnordost** [comment]
Nice, so you found the culprit?

>A good question would also be why many users edit the two sides one after another and not simultaneously

This was actually a requested feature and I am now using it too, it is very handy. Sometimes you can only see one side of the street from where you are.

**Comment by westnordost** [comment]
Hmm, sounds reasonable. But is this implementable with reasonable complexity?

**Comment by westnordost** [comment]
Yes. To be honest, I was just trying to sneakily nudge you into looking into the code more in detail so that maybe I you would create a PR to fix it :-P Sorry for that. But now that I confessed, would you? Otherwise of course, I'd come around to it of course, as this is a bug that must be fixed.

**Comment by westnordost** [comment]
I guess if either one side is specified with `null` or the parking situation did not change for that side, the subtags for that side should not be touched.
