### ISSUE TITLE
Add support for tagging structure as a library

### ISSUE THREAD

**Issue by Technerder** [streetcomplete/StreetComplete#4539]
**Use case**
It is already possible to tag buildings as "Government Building", Schools, etc but there is no option to tag them as libraries (unless I'm mistaken), being able to do this in the StreetComplete app as opposed to using the OSM editor would be lovely.

**Proposed Solution**
An additional button in the drop down menu for tagging a structure as a `Library` should be more than sufficient

**Comment by westnordost** [comment]
Use Civic (`building=civic`), that's fine. 

Note that the quest asks for the type of building, not what amenity is (currently) housed in it. Schools are usually purpose-built. A Building which houses libraries could be just as well a community center or even offices.
