### ISSUE TITLE
Rendering oddities

### ISSUE THREAD

**Issue by ChildishGiant** [streetcomplete/StreetComplete#4542]
Often when scrolling around things jump/flash but I've found a rectangle that doesn't sit well, reproduceably. https://www.openstreetmap.org/way/170988819
Here it is in Vespucci and osmand 
![Screenshot_20221022-124619~2.png](https://user-images.githubusercontent.com/13716824/197337873-a7bfb020-ee2b-43ed-acab-1527b88eab0c.png)
![Screenshot_20221022-124446~2.png](https://user-images.githubusercontent.com/13716824/197337881-01143ac6-3310-40a1-b3b7-1b9c508cc5e6.png)

And then in StreetComplete:
![Screenshot_20221022-124357~2.png](https://user-images.githubusercontent.com/13716824/197337897-c73630cc-06e3-4c74-8c49-c3225aa61523.png)

**Comment by westnordost** [comment]
Heh yeah, that's a body of water. There is some shader on it that animates the water "waves". That shader doesn't work well with very small bodies of water or bodies of water with sharp edges. Not exactly the rendering library tangram-es is to blame, it's rather the way shader-rendering is implemented in tangram-es which should not necessarily be viewed as a bug.

In any case, this is not solveable, as tangram-es is basically not maintained anymore and **if** they work on it some more, there are much more important things to fix (crash bugs, race conditions, ...).
