### ISSUE TITLE
Interrupting map animation with zoom buttons breaks all further animations

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4550]
As noted by @deevroman in https://github.com/streetcomplete/StreetComplete/discussions/4441#discussioncomment-3775425, if one interrupts running panning animation by pressing zoom-in or zoom-out button, all further zoom animation will be replaced by annoying chunky/delayed non-animated zoom change.

**How to Reproduce**

- Make a swipe so that the map continues to move by inertia.
- While the map is moving, press the `+`/`-` buttons
- All subsequent clicks on `+`/`-` buttons will be without animation.

**Expected Behavior**
- pressing zoom-in and zoom-out buttons should remain to have smooth animations, like they did have before the bug is triggered

There is a [manual workaround](https://github.com/streetcomplete/StreetComplete/discussions/4441#discussioncomment-3775861) which fixes situation. Would this be possible to fix in StreetComplete? Or, if the bug is instead inside Tangrem-ES core, could that workaround be applied automatically on `+`/`-` button press?

**Versions affected**
Android 10, SC `48.0-beta1` confirmed, but present in much older versions too (such as `43.1` - but maybe it was less likely to trigger in them? Or maybe I now just notice it more often)

**Comment by westnordost** [comment]
The camera animations are done in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/tangram/CameraManager.kt for whoever would like to have a look.

**Comment by bogomil** [comment]
I can confirm the bug on SC 57.1. It requires restart to make it back to the expected behavior!

**Comment by westnordost** [comment]
We are in the process of migrating to another map rendering library (MapLibre), so this bug is probably solved, then. See https://github.com/Helium314/SCEE/pull/516

**Comment by westnordost** [comment]
(I should make a list of issues solved with this migration for the changelog, it should be quite impressive)

**Comment by Helium314** [comment]
> (I should make a list of issues solved with this migration for the changelog, it should be quite impressive)

Also closed (previously unfixable) issues like #4449 to make the list even longer?

**Comment by westnordost** [comment]
Definitely! We need a sense of achievement! After all, the effort we have been pouring into it has been quite massive, no? For the background map style alone, it took me a whole week, I think.

**Comment by riQQ** [comment]
Another report of this is part 2 of #3275

**Comment by westnordost** [comment]
Will be fixed with #3123
