### ISSUE TITLE
vhf for leisure=marina 

### ISSUE THREAD

**Issue by PanderMusubi** [streetcomplete/StreetComplete#4551]
### General
Affected tag(s) to be modified/added: [vhf](https://wiki.openstreetmap.org/wiki/Key:vhf)
Question asked: **What is the VHF channel to contact marina XY?**

This information is usually posted on a sign when entering the marina or available on sailing boats and motor boats that are locally rented. This information is important to contact the marina to enter it safely in certain conditions when the sign cannot yet be read from a distance.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Integer as described in wiki. Give warning (are you sure) when entering 16 (emergency channel). Perhaps also for some other channels later. Don't use leading zero.

**Metadata needed:** 
leisure=marina

**Proposed UI:**
Prefill with previous value. Some countries use the same for these harbours.

**Comment by westnordost** [comment]
Closing because
- the VHF is not signed everywhere
- very low usage numbers
- most importantly, users will not know where to look for that. There may be many numbers at a marina

**Comment by PanderMusubi** [comment]
@westnordost and if at least one of the (`type=multipolygon`) members of `leisure=marina` has the tag `natural=coastline`, would that filter out the inland marinas?

**Comment by westnordost** [comment]
And you assume that every marina that is located at the coast will have a prominent sign denoting its radio channel, visible from the street?

**Comment by PanderMusubi** [comment]
No, is more for an app called WaterComplete. ;-) But I use also StreetComplete from the water by the way.

**Comment by westnordost** [comment]
I think every door is noch better suited for that ist case. Vhf is part of the id presets so it should be displayed for marinas(?)

**Comment by westnordost** [comment]
And you assume that every marina that is located at the coast will have a prominent sign denoting its radio channel, visible from the street?

**Comment by PanderMusubi** [comment]
If street is waterway, then yes.

**Comment by PanderMusubi** [comment]
By the way, I have added a picture to OSM Wiki regarding this. https://wiki.openstreetmap.org/wiki/Key:vhf

**Comment by ronnystandtke** [comment]
I just travelled through the Netherlands by boat using OsmAnd boat routing. Many bridges had to be contacted via VHF to be opened by operators and the vhf information in the OSM data set for every bridge was very valuable because we could contact the bridges early enough, even when the sign was very hard to see (too small, behind a tree or behind a curve). So thumbs up for adding this information!

**Comment by matkoniecz** [comment]
Note that main blockers are rather that this data is hard to collect to nonexperts 

See https://github.com/streetcomplete/StreetComplete/issues/4551#issuecomment-1291001958

**Comment by mnalis** [comment]
> Note that main blockers are rather that this data is hard to collect to nonexperts

True. The quest however could be [suggested to SCEE](https://github.com/Helium314/SCEE/issues) (StreetComplete _["Expert Edition"](https://wiki.openstreetmap.org/wiki/SCEE)_ fork), as it allows for quests requiring expert knowledge. 

Someone interested in solving such quests should request that, though.
