### ISSUE TITLE
Greek font is broken

### ISSUE THREAD

**Issue by sucrerouge123** [streetcomplete/StreetComplete#4554]
Greek font doesn't appear correctly in the map, as you can see in the screenshot of the app below.

**How to Reproduce**
Just visit any area in Greece which has named streets. Specifically you can visit 35.187123, 25.711711 and see that the street "Κωνσταντίνου Καραμανλή" appears as "Κωνσταντι΄νου Καραμανλη΄ " (the punctuation is not above the letter but right after it). Also, check the perpendicular nearby road "Ιωάννη Σακκά", which in the map is being shown as "Ιωα΄ννη Cακκα΄ " (the Greek capital letter Σ is represented as the Latin letter C, which sometimes happens in Greek texts of the Byzantine era and now is _only_ being used from the Greek Orthodox for specific purposes).

**Expected Behavior**
Greek alphabet should be represented as in the OSM map, which is correct.

**Versions affected**
v48.0

**Comment by westnordost** [comment]
You forgot to attach the screenshot.

**Comment by sucrerouge123** [comment]
Right!
![Screenshot_2022-10-26-15-27-26-799_de westnordost streetcomplete](https://user-images.githubusercontent.com/43409115/198113477-57a19a6f-34c4-46e9-85e1-d5fcd9df99f3.jpg)

**Comment by westnordost** [comment]
Can you link to the location on the map this is happening or better the exact element?

**Comment by sucrerouge123** [comment]
For instance this element is being shown incorrectly on the map, when the newly added shop overlay is enabled (this is shown in the screenshot above).

https://www.openstreetmap.org/node/5551458887

When you click on the element for some quest everything is fine!
![1666811497075](https://user-images.githubusercontent.com/43409115/198115851-8f98f638-dbcc-43e7-b134-d82f0b0e3cd1.jpg)

**Comment by westnordost** [comment]
Okay, I see the data from the map tiles on Jawg.io is also correct. 

I created an issue in https://github.com/tangrams/tangram-es/issues/2335 , but as this project is pretty much not maintained, this will probably never be fixed. Closing this one as this is an upstream issue.
