### ISSUE TITLE
Quests can obstruct other nearby quests because the map can't be zoomed in enough

### ISSUE THREAD

**Issue by hamishmb** [streetcomplete/StreetComplete#4555]
Some quests make it impossible to answer other quests, because they are blocked by the zoom level not going high enough.

**How to Reproduce**
Often seen at pedestrian crossings where the surface of the crossing also needs to be mapped.

**Expected Behavior**
Either:
1. It should be possible to zoom the map in more, solving the problem in most cases.
2. We should be able to temporarily (not permanently) hide one of the quests until the next refresh.
3. We should be able to maybe tap and hold, and then select "send quest to back" or similar?

**Versions affected**
Android 11, v47.2 (and previous versions)

**Comment by Helium314** [comment]
Please use the search function to find issues like #2878, #3952 or #124.
Closing as duplicate.

**Comment by mnalis** [comment]
I've now added a FAQ entry for [Some quests are obstructed by other quests, and I can't zoom in enough](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Some_quests_are_obstructed_by_other_quests,_and_I_can't_zoom_in_enough) with some workarounds listed.

**Comment by hamishmb** [comment]
Apologies, I didn't find those reports. Cheers for updating the FAQ!
