### ISSUE TITLE
Quests flicker and disappear during zoom/scroll

### ISSUE THREAD

**Issue by hamishmb** [streetcomplete/StreetComplete#4556]
Quests flicker and disappear during zoom/scroll. This happens especially often with power poles, for some reason.

**How to Reproduce**
1. Answer a power pole quest, or other similar quest that requires the map to zoom in and out a lot.
2. Repeat a few times.
3. Quests may flicker or disappear if you get lucky.
4. Quests may disappear entirely, resulting in you needing to manually pinch-to-zoom a few times to different random zoom levels, to get them to reappear.

Possibly happens more often when I answer a power pole quest during data sync - I'm not sure exactly what causes it to happen.

**Expected Behavior**
Quests do not flicker and temporarily disappear depending on zoom level.

**Versions affected**
Android 11, v47.2.

**Comment by westnordost** [comment]
This may be the same as #4522 or otherwise it is a will-not-fix because otherwise it is simply how tangram-es works.

**Comment by westnordost** [comment]
If you want to help at #4522, you could try out at which app version this issue was introduced by trying the same with older versions of the app. (Uninstall/reinstall necessary because it is not possible to downgrade the app)

**Comment by FloEdelmann** [comment]
Maybe your issue is already fixed by the caching and performance improvements in [version 48.0](https://github.com/streetcomplete/StreetComplete/releases/tag/v48.0). Can you try upgrading and see if it persists?

**Comment by hamishmb** [comment]
Hmm, I'm using the F-Droid version, so I'm not sure I'll be able to upgrade on my actual phone, but I could use an AVD. That'd probably be so laggy it wouldn't help anyway.

**Comment by mnalis** [comment]
F-droid release usually lags by a week or two in my experience, so `48.0` might be released soon...

**Comment by hamishmb** [comment]
I've got v48.0 now, I'll post back here again once I know for sure if the issue is gone for me - might take a while to be sure.
