### ISSUE TITLE
Doesn't recognise Simple Camera as a camera application

### ISSUE THREAD

**Issue by hamishmb** [streetcomplete/StreetComplete#4557]
StreetComplete doesn't recognise Simple Camera (https://github.com/SimpleMobileTools/Simple-Camera) as a camera application - when I try to attach a photo it pops up with a toast saying "No camera app available".

**How to Reproduce**
1. Install Simple Camera from F-Droid.
2. Disable the built-in camera.
3. Attempt to attach a picture to a note.
4. Observe issue.

**Expected Behavior**
StreetComplete should recognise Simple Camera as a camera application.

**Versions affected**
Android 11, v47.2

**Comment by riQQ** [comment]
Related to #4281

**Comment by mnalis** [comment]
Out of interest, when you go in your android settings and search for `Default apps`, can you under `Camera` select `Simple Camera`? 

If not, then it is likely `Simple Camera` app issue and should be reported there.
And if you can change it (and do!), does StreetComplete detects it then?

**Comment by westnordost** [comment]
This has nothing to do with StreetComplete. It just asks the system "I want to take a picture with the camera, please" and the rest is up to the Android system.

**Comment by hamishmb** [comment]
Interestingly, I have no camera section at all in "default apps". I have no idea why. I also have no idea why, but other applications seem to be able to find Simple Camera regardless of that. I'll go report this to them.

**Comment by Helium314** [comment]
I _can_ select Simple Camera when taking a photo, so not sure whether Simple Camera is the issue...

**Comment by hamishmb** [comment]
Huh, maybe that's my stock ROM then. Motorola did a lot of annoying things with it. I'll do some more research.

**Comment by Helium314** [comment]
Does it work with OpenCamera, or when you enable built-in camera?

Alternatively it might be necessary to add something to the manifest: https://github.com/esafirm/android-image-picker/issues/296#issuecomment-839696109

**Comment by mnalis** [comment]
> Interestingly, I have no camera section at all in "default apps".

In my Android 10 (EMUI 12), I need to click `more defaults` to see defaults for camera (main `default apps` screen _only_ shows `assist`/`browser`/`home`/`phone`/`SMS` apps)

If still default camera app cannot be found, I think the ordering might be the culprit; it seems @hamishmb did: 

- _Install Simple Camera from F-Droid._ (adds a new, non-default camera; as stock camera is the default).
- Disable the built-in camera. (removes the default camera as it no longer exists).
- (result: no default camera selected)

I'd suggest uninstalling simple camera, and then trying to do it other way around:
- **first** disable stock camera
- reboot
- only **then** install `Simple Camera`.  (If it is installed as the **only** camera app, it should became the **default camera** by default upon installing it. At least it seems to happen that way for other apps on my android). 
Does that perhaps help, @hamishmb ?

**Comment by hamishmb** [comment]
I think you're probably right there, @mnalis. I'll give those ideas a try and reply here again.

**Comment by hamishmb** [comment]
Interestingly, I don't have a "more defaults" section.

I did as you suggested, and interestingly nothing changed. Simple Camera is launched automatically from the lockscreen, and by my accessibility app, but doesn't seem to be set as a system default. The stock camera didn't seem to get set as a system default either, and there was no option to add it as a default, even after a reboot with the stock camera being the only camera app.

The plot thickens. I may have to follow up with the image picker, and with the Simple Camera people. I'll give this a go with an AVD, when I get those set up. Strange that it seems to work for other people.

**Comment by mnalis** [comment]
Interesting. You may want to try installing some other cameras and see if it works with them (to try to isolate if it is more of SimpleCamera issue, or more of your Android version issue).

**Comment by hamishmb** [comment]
I shall give that a try when I have some time.

**Comment by Walker9998** [comment]
Just until now I've been having the same exact issue but with another third party camera not installed via the play store and with no default camera app shown in my default apps settings page.

What ended up fixing it was re-enabling my phone's default camera app and from doing that Streetcomplete automatically switches to said camera app with no app selection prompt.
On the off chance it helps, in the about app system settings for the app the only permission I can give it is location (Android 11)

Streetmeasure for one reason or another worked just fine before I re-enabled that app (still does) but I can't give it any permissions at all
