### ISSUE TITLE
Cycle barrier quest could benefit from a clarifying sentence

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#4560]
**Use case**
I noticed the new cycle barrier quest “Can this cycle barrier be opened?”. It’s indeed nice and useful, but it was unclear to me what to answer when the cycle barrier can be opened, but needs a key for it: it can theoretically be opened, but it is unclear by whom, and this thus really depends on the intended use-case of the underlying tag.

**Proposed Solution**
I suggest adding a sentence below the question clarifying what to answer when a key is needed.

**Comment by mnalis** [comment]
Hmmm... initially it was made that way (see first picture in https://github.com/streetcomplete/StreetComplete/pull/4406), but then the texts got way too long and probably needed to be even longer to be clear (e.g. https://github.com/streetcomplete/StreetComplete/pull/4406#issuecomment-1272560242), so it was decided to go for simplicity instead.

I agree that the usage of that tag  [cycle_barrier:installation=*](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation) by itself does not tell the whole story: it only tells _if the cycle barrier is fixed or (re)moveable_. It does not say _**by whom** it can be (re)moved if it is (re)movable_ (there was some wiki talk [about it](https://wiki.openstreetmap.org/wiki/Talk:Tag:barrier%3Dcycle_barrier#liftable_by_maintainer)).

So, the intention is that _whether the key is required or not, if **somebody** can open/remove it, then it is openable/removable_. 
 
>  I suggest adding a sentence below the question clarifying what to answer when a key is needed.

After looking that PR discussion [there](https://github.com/streetcomplete/StreetComplete/pull/4406#issuecomment-1272560242), do you have a suggestion how to improve on current state while addressing concern discussed there? I.e. any suggestions for better **short** texts, that will remove the confusion, while being short enough to not cover important parts of the pictures?

**Comment by mnalis** [comment]
Or maybe changing the text of the question itself would be better (i.e. something along the lines _"Can this cycle barrier be opened (with or without key)?”_)

**Comment by westnordost** [comment]
Or

"Can this cycle barrier be opened (by firefighters)?”

?

**Comment by mnalis** [comment]
I've also though of _"Can this cycle barrier be opened (by **anyone**)?”_ but that `anyone` can easily be confused with `everyone` which is absolutely not what we mean! Somewhat better is `someone` or `whoever`, but still sounds unfinished/strange. And those words might be problematic/unclear to translate in some languages... 

That's why I suggested a little longer `with or without a key` which does not imply anything about who can open those barriers, and should be easily understandable and translatable (and we use that wording in `bollard` quest too). But if anyone has ideas, please do share them!

**Comment by Mbodin** [comment]
In the discussion, there are basically two discussed solutions: either add the information on the picture text, or within the question. I can imagine that both can be tricky with spacing. I personally like the addition of `with or without a key` in the question: it’s simple and clear.

Another solution would be to add a hint below the question, like the hint of the bike parking capacity quest: “Note that many stands can be used to park one bicycle on each side.” I think that it’s nicely styled for what we are looking for here.

**Comment by westnordost** [comment]
Let's go with @mnalis suggestion

> Can this cycle barrier be opened (with or without a key)?”

**Comment by westnordost** [comment]
yes, fuzzy
