### ISSUE TITLE
"Addresses" and "Shops" overlays editing perspective

### ISSUE THREAD

**Issue by retiolus** [streetcomplete/StreetComplete#4563]
**How to Reproduce**
Activate the new overlay for "Addresses" or "Shops".

**Expected Behavior**
In my opinion, as soon as one of these two overlays is activated the map should automatically be placed in a "2D" view, the 3D visualization is disturbing for adding points, the perspective often makes it possible to place them incorrectly in a building or on the sidewalk and not on the wall / entrance of the business.

**Versions affected**
v48.0

**Comment by westnordost** [comment]
Makes sense

**Comment by mnalis** [comment]
(related: https://github.com/streetcomplete/StreetComplete/issues/2206#issuecomment-1276657156)
