### ISSUE TITLE
Renaming a shop in the shop overlay deletes all other tags

### ISSUE THREAD

**Issue by schuetzm** [streetcomplete/StreetComplete#4567]
**How to Reproduce**
I wanted to fix the spelling of [this node](https://www.openstreetmap.org/node/8066089948) using the new shop overlay. When I clicked the save button, it then showed the quest for the opening hours, which made me suspicious, because I remember that I had already entered them for this shop. So I looked in the history to see which changes were made, and I found that SC had removed all other tags on the node in question: `wheelchair`, `opening_hours` (and `check_date` and `check_date:opening_hours` as well).

(I then undid the changes and renamed the shop using Every Door, therefore it's not visible in the nodes history.)

I guess this might be related to https://github.com/streetcomplete/StreetComplete/issues/4501. Maybe the thought was that if one shop is changed to a different one, then it's a totally new shop and the previous tags are not applicable anymore? But this is clearly not the case here; I only wanted to changed the name. Even if the type of the shop is changed, it's not necessarily the best idea to delete all other information, especially if it's not then immediately prompted for again by SC, even moreso doing it silently. I would even argue that if a shop closes and another open's in the same place, then it's better to delete the existing node and create a new one to signal that's it's a new entity now; under this model, there would never be any need to delete tags.

**Expected Behavior**
Only the name should change.

**Versions affected**
v48.0 (from F-Droid)

**Comment by peternewman** [comment]
> I guess this might be related to #4501. Maybe the thought was that if one shop is changed to a different one, then it's a totally new shop and the previous tags are not applicable anymore?

Yeah that's the idea, as far as I'm aware its effectively using the same code as "It does not exist..." when you answer say the opening hours quest.

> But this is clearly not the case here; I only wanted to changed the name. Even if the type of the shop is changed, it's not necessarily the best idea to delete all other information,

There's currently a carefully curated list of what should or shouldn't be deleted when a shop changes (so the shop key, but not the address info for example).

I did get tripped up on this too myself correcting a name where I hadn't got it quite right originally.

I'd think if anything what it maybe wants is an extra option to refine/improve stuff (effectively the reverse of "It does not exist...") on a small independent restaurant, that might be improving the preset from say "Restaurant" to "Italian Restaurant", so it just adds the `cuisine=italian` tagging, without dropping all the bits I or others have added.

Or in the case of a brand, it might either be a ghost that's renamed (e.g. https://osm.mathmos.net/ghosts/hsbc/ or https://osm.mathmos.net/ghosts/fridays/ ) or a supermarket you might be making the brand a bit more accurate (e.g. Tesco->Tesco Express). It would seem very rare that detail that has been tagged, but which isn't in the preset, will have changed, as it's effectively just the naming/branding that changed.

> I would even argue that if a shop closes and another open's in the same place, then it's better to delete the existing node and create a new one to signal that's it's a new entity now; under this model, there would never be any need to delete tags.

But then you'd have to re-enter say the address details again, despite the fact the shop is still in the same place in the street.

**Comment by westnordost** [comment]
So, it is correct that this is deliberate. But it can certainly lead to situations as described. Question is, what can be done in the UI to either make this clear to the user or enable him to (in the exception) NOT clear all previous shop-related tags, i.e. say "I am just correcting the name / the type"?

(P.S: You work at mathmos? I love those lamps!)

**Comment by peternewman** [comment]
> Question is, what can be done in the UI to either make this clear to the user

I'm not sure how important this is on it's own, given the only workarounds would be to leave a note or use another app.

I guess you could have a one line message "changing the name or type or shop will reset all other shop related info".

> or enable him to (in the exception) NOT clear all previous shop-related tags, i.e. say "I am just correcting the name / the type"?

As suggested, an other answer "Just refine/improve the tagging" or some better phrasing, which I guess might just relaunch the same form but as a dialogue or something?

> (P.S: You work at mathmos? I love those lamps!)

It's a different Mathmos:
https://www.mathmos.net/
https://www.mathmos.com/

But I do too, I've got one at home as well. It's also not my website, but Robert Whittaker's excellent site!

**Comment by HolgerJeromin** [comment]
What about detecting difference  (Hamming distance?) of old and new name.
If only a few chars have changed, keep the tags.

**Comment by mnalis** [comment]
> As suggested, an other answer "Just refine/improve the tagging" or some better phrasing, which I guess might just relaunch the same form but as a dialogue or something?

maybe, but that would be discoverable by users? Most would probably not be aware of that feature, and would still just change the name, which would still lead to situation like above.  

> What about detecting difference (Hamming distance?) of old and new name.
> If only a few chars have changed, keep the tags.

Hm, maybe, but only with user confirmation, and **_not automagically_**.

So, if in `shops overlay` only changed a name (and not a type where situation is clear), **_and_** that name is mostly similar to the old one, present a dialog to the user asking `Is this a different shop, or are you just correcting a typo in misspelled name?` with `different shop` / `just typo` answers, and then proceed accordingly.

**Comment by matkoniecz** [comment]
Maybe on rename ask user whether it is minor fix of name or a completely new shop of the same type?

I would not expect name editing action to blank tags/

**Comment by peternewman** [comment]
> Maybe, but would that be discoverable by users? Most would probably not be aware of that feature, and would still just change the name, which would still lead to removal of attributes like in what prompted this issue.

🤷 There are lots of other similar features "hidden" in the other answers menu.

As I see it, there are two options, either put it in the menu, or change the form to have two buttons, say change or improve, but ideally with two better sets of words.

**Comment by mnalis** [comment]
> Well, a user may want to correct the type of place too while the shop did not actually change. There is no Hamming distance for that.

There is no Hamming distance for that indeed, but to me the situation was looking clear in that case - if shop **_type_** changes, **always** assume new/different shop and clear tags. 

There might have been exception to that rule if original was `shop=yes` instead of `shop=specifictype`, **if** that is deemed important enough for added complexity (e.g. skip removing the tags if name **was not** changed, and **only** `shop=yes` was changed to `shop=convenience|supermarket|...`)

**Comment by peternewman** [comment]
> There is no Hamming distance for that indeed, but to me the situation was looking clear in that case - if shop **_type_** changes, **always** assume new/different shop and clear tags.
> 
> There might have been exception to that rule if original was `shop=yes` instead of `shop=specifictype`, **if** that is deemed important enough for added complexity (e.g. skip removing the tags if name **was not** changed, and **only** `shop=yes` was changed to `shop=convenience|supermarket|...`)

But as I said I don't think they are the only cases:

> I'd think if anything what it maybe wants is an extra option to refine/improve stuff (effectively the reverse of "It does not exist...") on a small independent restaurant, that might be improving the preset from say "Restaurant" to "Italian Restaurant", so it just adds the `cuisine=italian` tagging, without dropping all the bits I or others have added.
> 
> Or in the case of a brand, it might either be a ghost that's renamed (e.g. https://osm.mathmos.net/ghosts/hsbc/ or https://osm.mathmos.net/ghosts/fridays/ ) or a supermarket you might be making the brand a bit more accurate (e.g. Tesco->Tesco Express). It would seem very rare that detail that has been tagged, but which isn't in the preset, will have changed, as it's effectively just the naming/branding that changed.

**Comment by westnordost** [comment]
How about this:

1. When you change the preset, the name is cleared (that is already how it works, but also:)
2. When you change the name, the preset is cleared unless it was empty before (and unless one already changed the preset of course)

This is a strong signal to the user that indeed the change he makes means that the previous information is cleared.

3. Add other answer "Still same place but wrong name or type" (urg, any more brief string possible?). Tapping it will basically disable the clearing behavior. Only name+place are changed on edit. This is explained in a short message (maybe a toast: "Ok, place info will not be cleared on edit").

This functionality is still a bit hidden, but through point 1 and 2 it should be clearer to users what the default behavior of the app is. And the alternative seems to be to either have some kind of radio buttons visible always
(*) place changed
( ) still the same place
... which wastes too much space and will confuse users or a dialog that asks for this thing on every single edited place, which would be somewhat annoying.

**Comment by westnordost** [comment]
Another alternative would be to not clear anything in the UI  and only show this (annoying) dialog whenever only either the place type **or** the name has been changed.  However, it could very well be that both the type and name of a place are wrong, so that wouldn't work in such a case.

**Comment by matkoniecz** [comment]
> maybe a toast: "Ok, place info will not be cleared on edit"

And maybe show toast "Resetting all shop-specific info" on destructive edit to make it even more clear?

**Comment by westnordost** [comment]
Give me a show of hands, which alternatives do you find better?

**Comment by westnordost** [comment]
> And maybe show toast "Resetting all shop-specific info" on destructive edit to make it even more clear?

That toast would be shown when it is already too late (the edit has been made). That would be bad UI. (Should not rely on undo here)

**Comment by peternewman** [comment]
> How about this:
> 
>     1. When you change the preset, the name is cleared (that is already how it works, but also:)
> 
>     2. When you change the name, the preset is cleared unless it was empty before (and unless one already changed the preset of course)
> 
> 
> This is a strong signal to the user that indeed the change he makes means that the previous information is cleared.

I'm assuming the preset/name will only clear "on blur" i.e. when you defocus? It would be nice if it could also populate the other answers dialog with the corrected name, otherwise you'll have to do:
Select Aple store
Correct to Apple
Notice store type cleared
Other answers
It gets reset to Aple
Correct to Apple
Save it.

>     3. Add other answer "Still same place but wrong name or type" (urg, any more brief string possible?).

...wrong info?
...wrong details?

**Comment by peternewman** [comment]
LGTM, from what I can see, changing:
Feature: Restaurant->Italian Restaurant
Name: Fancy Restaurant->The Fancy Restaurant

Will still only bring up the confirmation dialogue, which is the only other edge case I could see.

**Comment by ivanbranco** [comment]
Hi, I just saw that the new "is this the same place?" prompt is shown also when creating a new place, which is confusing. I suppose it wasn't intended

**Comment by FloEdelmann** [comment]
@ivanbranco This is already reported in #4605.
