### ISSUE TITLE
Add website link to the app's about page

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4570]
As there are links on the about page to the GitHub repository, FAQ and so on, it would be useful to have a link to the [new website](https://streetcomplete.app/) there as well.

**Comment by westnordost** [comment]
Why?

**Comment by westnordost** [comment]
The app itself also links to FAQ, Github repository etc.

In fact, all the strings used on the website are from the app itself. The website shows nothing the about section of the app does not show.

**Comment by legofahrrad** [comment]
> Why?

Users see then that there is a website at all, and they could send the link to friends/family/... to show them (something about) the app. This (showing them then a website with description and screenshots) is often better than just saying "I'm using app XY".

**Comment by westnordost** [comment]
Hm, for now, I'll not do this. streetcomplete.app should be reasonably at the top of  google search results, as well as the play store and f-droid (and github), which are all fine.
