### ISSUE TITLE
A unit test is failing only between midnight and 1 am

### ISSUE THREAD

**Issue by YoshiRulz** [streetcomplete/StreetComplete#4575]
The "tag date comparison variants" test in `ElementFiltersParserAndOverpassQueryCreatorTest` fails when the system time is between 12:00 (midnight) and 1:00. I believe it's this case that's failing:
https://github.com/streetcomplete/StreetComplete/blob/c000b8e6539e553aed6c20eafceec2c78db5d4cd/app/src/test/java/de/westnordost/streetcomplete/data/elementfilter/ElementFiltersParserAndOverpassQueryCreatorTest.kt#L68
[This screencast](https://youtu.be/lH0KCDg8D5w?t=40s) shows it flipping from fail to pass at 1:00.
My system time zone is AEST (UTC+10), in case that matters.

**How to Reproduce**
`gradle :app:testDebugUnitTest`

**Expected Behavior**
Passes regardless of system time.

**Versions affected**
c6cedafad
This has been present for at least a couple of weeks.

**Comment by westnordost** [comment]
Yeah, I know. I removed the bug label because (I assume) the time zone stuff does not really affect the app as the element filter is used in scales where a few hours inaccuracy doesn't really matter.
Feel free to investigate, but I so far did not care about this.
