### ISSUE TITLE
Keep changeset bbox small

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#4582]
**Use case**
A user has auto-upload off and keeps solving a lot of quests offline in a lot of different places, e.g. on a vacation. Then later, he uploads them all at once. All the quests get sorted into changesets that span very large areas.

This is somewhat inconvenient for people keeping track of changes in their area because changesets are sorted by bbox in the osm.org UI for looking at local changesets. I.e. the list of changesets displayed for a local area always also includes changesets whose bbox spans the whole continent because e.g. one edit in the same changeset was made on the westernmost verge and the other on the easternmost verge of the continent.

This sometimes leads to clashes between StreetComplete users and those monitoring the changes. The former are oblivious about how this works internally. See also https://news.ycombinator.com/item?id=33035946

**Proposed Solution**
When adding another edit to a changeset, check if it would enlarge the bounding box of the current changeset over a certain threshold (5 km?). If yes, open another changeset instead and close the previous one.

**However, do this only if the edit made is guaranteed to have been made on-site! I.e. 1. location *on* and 2. the app did not need to ask the user whether he has really checked it on-site.**

This requires also persisting this information on creating an edit. The reason for this is that we do **not** want to hide misuse of this app that should only be used for on-site edits by users who solve quests all over the place while not really being there.

**Comment by mnalis** [comment]
(related https://github.com/streetcomplete/StreetComplete/issues/3640 and linked issues, and FAQ: [A changeset made with StreetComplete covers a massive area, why is this? How can it be prevented?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#A_changeset_made_with_StreetComplete_covers_a_massive_area,_why_is_this?_How_can_it_be_prevented?))

**Comment by Helium314** [comment]
> This is somewhat inconvenient for people keeping track of changes in their area because changesets are sorted by bbox in the osm.org UI for looking at local changesets

Actually I get the impression that this UI should be improved to require that edits were made inside this bbox...

> However, do this only if the edit made is guaranteed to have been made on-site! I.e. 1. location on and 2. the app did not need to ask the user whether he has really checked it on-site.

This needs to deal with some cases to no wrongly flag edits as _misuse_. E.g  when you're on a car and answer quest for a roundabout that has been cut into many segments. There is basically no chance that you answer some 25 quests while you're close enough, but it's still very easy to remember e.g. all asphalt, no cycleway, all lit and enter the answers while you're "far away".

**Comment by mnalis** [comment]
> E.g when you're on a car and answer quest for a roundabout that has been cut into many segments

This is true, but perhaps it can still work? i.e.:

> check if it would enlarge the bounding box of the current changeset over a certain threshold (5 km?).

so, if you add many such small segments of the road that you remember, each one of them would only enlarge the bbox by small amount (few hundreds meters?).Their cumulative enlargements could indeed be hundreds of km for a long trip of course, but as it was done in small increments, that still would not trigger that condition, and thus a changeset would be a subject for auto-splitting

> The reason for this is that we do not want to hide misuse of this app that should only be used for on-site edits by users who solve quests all over the place while not really being there.

However, _maybe alternatively_ we could **_always split the changeset_**, but mark the potentially non-survey edits by **not adding** `source=survey` changeset tag instead? (e.g. https://github.com/streetcomplete/StreetComplete/issues/298, https://github.com/streetcomplete/StreetComplete/issues/3248#issuecomment-914795588 and others)

**Comment by Helium314** [comment]
> so, if you add many such small segments of the road that you remember, each one of them would only enlarge the bbox by small amount (few hundreds meters?).Their cumulative enlargements could indeed be hundreds of km for a long trip of course, but as it was done in small increments, that still would not trigger that condition, and thus a changeset would be a subject for auto-splitting

But I really don't want to either frequently edit from inside the car just to avoid "misusing" the app, or to remember not editing after I had a 3 minute chat during which the car moved 5 km.

**Comment by westnordost** [comment]
Don't get hung up on the details. It's not as if the situation would deteriorate for cases where you really were on site but the app did not recognize this automatically.

**Comment by westnordost** [comment]
Also,  keep in mind that the "user has been near the object edited" detection is something that could be improved by taking into account the blue gps track line as displayed to the user. 

For example.

But that is a separate thing that could be done.

**Comment by crackwitz** [comment]
I just saw a changeset of SC 57.1 that spans half of Europe. Does this feature work as intended?

https://www.openstreetmap.org/changeset/149644179#map=5/52.922/16.765

**Comment by westnordost** [comment]
Yes, I tested it. The changeset is *not* kept small if the users's GPS location was not near the edited location.

**Comment by westnordost** [comment]
So, rather than asking the user in the changeset comment to not create big changesets, tell him to only do edits on-site, because with the former, he certainly doesn't know what you are talking about.

**Comment by crackwitz** [comment]
That user claims to have visited those places over the span of the last three months. That user certainly *was not aware* that this would cause a single changeset spanning half of Europe.

I don't care to read up on the years and years of debate over this, and who dug which trenches in this war. I did see discussion over where the user's GPS location was. I honestly don't see the point in that check. No casual beginner user will understand this distinction, nor the consequences of a prompt. They'll tap "yes sure fine now go away" on whatever dialog.

The point is: it's never-ending work to educate all those casual users of this app that *can* cause such changesets without being aware of it. It is *less* work to tweak this app into forming changesets that span a reasonable geographical area.

**Comment by goldfndr** [comment]
More explicitly: that changeset (created 2024-04-06T08:27:34Z) occurred after another StreetComplete 57.1 upload (149642955) from less than an hour earlier (created 2024-04-06T07:46:18Z). The normal behavior of StreetComplete is to upload all answers since last upload. So, unless more than one device was used with one OSM account, *keeping those changes in the "buffer"* was quite limited, less than an hour.

**Comment by matkoniecz** [comment]
> it's never-ending work to educate all those casual users of this app that can cause such changesets without being aware of it

It will create such changesets only if they ignore clear instructions. SC is for in-place survey.
