### ISSUE TITLE
Purple glow for quest "Is this place wheelchair accessible?" without reason?

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#4587]
I'm looking at node https://www.openstreetmap.org/node/9365567221 . (See screenshot below)

The neighbouring building got a purple glow. This means, that the same quest type is occurring there too, is that correct?

I tried both hiding and solving the address quests for that building, but after that, no other quest appeared. Is a wheelchair quest still there but not shown? Is the purple glow showing for a wrong reason? Did I misunderstand the meaning of the purple glow?

![spielweg](https://user-images.githubusercontent.com/4726277/199099947-d9d30b19-d84a-43d6-8878-a5d3b1fa18bb.png)

**Comment by Helium314** [comment]
see #4578

**Comment by matkoniecz** [comment]
That is one more bad consequence of merging POI and building into one object, rather than marking this two elements as two separate OSM elements

This is intentional highlighting of nearby shops and similar objects

**Comment by westnordost** [comment]
See https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#When_I_click_on_quest,_several_similar_icons_pop_up,_why?
