### ISSUE TITLE
"What’s the height limit below the bridge"-quest does something wrong

### ISSUE THREAD

**Issue by habi** [streetcomplete/StreetComplete#4588]
I'm not using StreetComplete, because I'm on iOS but I watch notes in my vicinity and in Switzerland.

There's a bunch of recent notes complaining that 'the height limit below the bridge' cannot be answered because there's no bridge.

Examples:

- https://www.openstreetmap.org/note/3422505
- https://www.openstreetmap.org/note/3422474
- https://www.openstreetmap.org/note/3421397
- https://www.openstreetmap.org/note/3399306

Some of the rather long ways actually do pass under a bridge, the notes in Bern show ways which have a `max_height` of 20 to 30 m :)

Could this quest be only shown closer to the bridges?

**Comment by peternewman** [comment]
> Examples:
> 
>     * https://www.openstreetmap.org/note/3422505

The bridge here seems pretty close to me:
https://www.openstreetmap.org/way/48443730

> Could this quest be only shown closer to the bridges?

There's already an option and a note to split the way, at which point it will only actually ask for the bit under the bridge.

https://github.com/streetcomplete/StreetComplete/blob/c000b8e6539e553aed6c20eafceec2c78db5d4cd/app/src/main/res/values/strings.xml#L1045

**Comment by matkoniecz** [comment]
I have solved all linked notes by splitting way (which could be also done in StreetComplete)

**Comment by habi** [comment]
My observations based on the three notes I just went through: https://www.openstreetmap.org/changeset/128331354

In all these situations (at least in Bern I *know*, all the other notes it's probable) the `max_height` is larger than 4 meters.
In this situation the height is not signed in Switzerland (see Art. 21 of [our signage regulation](https://fedlex.data.admin.ch/filestore/fedlex.data.admin.ch/eli/cc/1979/1961_1961_1961/20210101/de/pdf-a/fedlex-data-admin-ch-eli-cc-1979-1961_1961_1961-20210101-de-pdf-a-11.pdf)), does the user get  suggested to use [`maxheight=default`](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values) in this case?

**Comment by matkoniecz** [comment]
> does the user get suggested to use [maxheight=default](https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values) in this case?

yes, if user answers correctly then it will be applied

**Comment by Luzandro** [comment]
There are regularly notes that this task cannot be solved because it is not placed at the bridge, but in the middle of long sections of a road that run somewhere entirely else under a bridge and people are irritated, why they are asked about a bridge that's not there.

https://www.openstreetmap.org/note/4947361

https://www.openstreetmap.org/note/4909327

https://www.openstreetmap.org/note/4944482

https://www.openstreetmap.org/note/3808565

https://www.openstreetmap.org/note/3805187

https://www.openstreetmap.org/note/4883078

https://www.openstreetmap.org/note/3297741

https://www.openstreetmap.org/note/3392576

https://www.openstreetmap.org/note/3288484

Even if the question is answered, in my opinion it is more than questionable to impose a restriction on such long sections when it does not apply for the most part, which was closed as not an issue by @westnordost 
 https://github.com/streetcomplete/StreetComplete/issues/4589

**Comment by westnordost** [comment]
it is possible to split the way also from within the app. There is a text in the app that notifies the user of this possibility.

**Comment by mnalis** [comment]
Thanks for you feedback @Luzandro!

> but in the middle of long sections of a road that run somewhere entirely else under a bridge and people are irritated, why they are asked about a bridge that's not there.

I'm not familiar with the language enough to know if they are really _irritated_ or merely _confused_, but I would think that leaving the Note is a right and useful approach in that case. After all, another editor can then: 
- at least split the way appropriately and close the note (in which case next on-the-ground StreetComplete mapper would be able to answer the quest easily), or
- often even add a height limit to appropriate section after splitting (if users specified it in the Note like in at least some of those examples), 

Both lead to improvement of the map, so should be welcome (and are very purpose of the Notes IMHO).

> questionable to impose a restriction on such long sections when it does not apply for the most part,

As noted, that mapper is informed that they should split such long way in those cases. If they decide that it restriction applies to whole longer section, it is (like any other decision made by any other mapper) IMHO their choice 🤷. 

There is https://github.com/streetcomplete/StreetComplete/issues/6208 which should make that instruction more visible (i.e. automatically, and not only after clicks the info button when they are confused)

![Image](https://github.com/user-attachments/assets/dfbd603d-8763-4c2c-861b-7983ec8ffeba)
