### ISSUE TITLE
"What’s the height limit below the bridge" may result in incorrect data with very long ways - autosplit ways? Skip roads that go over crossings?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4589]
Yes, there is warning already. But many users miss it or ignore it. Maybe there should be a stronger protection to guard against it?

see https://www.openstreetmap.org/way/354570211#map=17/50.01216/21.96265

![screen04](https://user-images.githubusercontent.com/899988/199193993-329b6ad5-b42c-4ea0-ba94-00ac83009523.png)

StreetComplete added `maxheight` in https://www.openstreetmap.org/changeset/113477760

But it does not really apply to the left section, as car can leave road and is not affected at all.

Spotted when analysing #4588 (in that situation it resulted in notes, not damaged data)

**Comment by westnordost** [comment]
I don't think anything can be done beyond showing a warning.

Autosplit is the kind of "smart" behavior for which it is not foreseeable in which cases it will not do what is expected.

Skip roads that go over a crossing: I do not think that the possibility that a surveyor marks a too-long section of a road with a may height should result in that the height is not specified at all. Let's not forget that it is a (IMO slight) mistake of the user, not the app. And TBH, such data can always be corrected later by any contributor that follow after with JOSM etc. Specifying the maxheight below a bridge on the other hand requires to be on site, something **not** every contributor can do. For this reason, I would very much prefer cases like the one cited over not having this tagged at all.
Also, looking at what effect this has (on routing), a low maxheight wrongly set on the upper part of the shown road will just mean that trucks cannot be routed into Zawiszy Czarnego from Zolnierzy 9 Dywizji Piechoty (they need to take another route if that is really their destination), while if it is not tagged at all, trucks may be wrongly routed along Zolnierzy 9 Dywizji Piechoty and thus turning back and re-routing a possibly big detour.
