### ISSUE TITLE
Regression: thumbnails not shown in street parking overlay

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4590]
**How to Reproduce**
Attempt to add parking in the parking overlay, and find that the thumbnails are not showing for many of the options as they have in earlier versions.

![image](https://user-images.githubusercontent.com/12725310/199218796-f0b40ce1-e7d2-4c9a-b8cd-4b95e86d08c6.png)
![image](https://user-images.githubusercontent.com/12725310/199218828-d79e56d1-9849-4c2f-98b9-cf0e538d6e24.png)

**Expected Behavior**
Thumbnails should be shown so type of parking can be selected easily.

**Versions affected**
V90.0-beta 1 on Android 11

**Comment by westnordost** [comment]
Why is this a regression? Was it different in v48?

What device are you using?

**Comment by westnordost** [comment]
I can't reproduce this.

**Comment by westnordost** [comment]
The `StreetParkingDrawable` hasn't been changed recently except for https://github.com/streetcomplete/StreetComplete/pull/4509 by @tapetis 

This was already included in v48.0.

Could you check if you can reproduce this issue for v48.0-beta1? That version did not include the change yet. Also, which device do you use?

At first glance,[ the change made](https://github.com/streetcomplete/StreetComplete/pull/4509/commits/99be3a95aa4c8cc698030f7d9f49274940564ccb#diff-58c574c32a3bf2ee12b240ad7341258b73fe8809cd0343f409991c66d652c26b) looks innocent. @tapetis, any idea?

**Comment by mattjudge** [comment]
I'm experiencing this bug on a OnePlus 5T, resolution 2160 x 1080 px. App version 48.0.

**Comment by mattjudge** [comment]
I've confirmed that this bug does not affect v47.2 or v48.0-beta1, and is present in v48.0 and v49.0-beta1.
