### ISSUE TITLE
"This week"-statistics show stats of the last 7 days, not of this week only(?)

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4592]
Since v49 the profile screen contains more statistics, including some of "this week".
I wondered that the number showed a pretty high number even though it was Monday. Am I right assuming it counts the quests from the last 7 days instead of the last Monday (week beginning)?
I suggest to rename it, as the current name is confusing and not right then. E.g. "Last 7 days" instead of "this week"

**Comment by westnordost** [comment]
Yes, it counts the changes from the last 7 days, not from the start of this week. Ok, I guess I'll rename it then...
