### ISSUE TITLE
`parking:condition:either_side_only=yes`

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#4594]
**Use case**

when tagging the parking situation on "narrow" streets, I've seen an edit made where some streets were falsely tagged as one side parking only.
I think SC should make sure this does not happen.

**Proposed Solution**
* when parking is allowed on both sides, ask if the street would be too narrow to park on both sides at the same time.
Maybe in relation to the `width` if it is tagged. In theory the value of `parking:condition:either_side_only` can be derived from the width and parking-tagging, however, I feel it be better to tag it explicitly.

* Remind people that the tagging is only relevant for legal parking, not how people actually park there.
It may be legal to park on both sides of the street, but not at the same time, since the roadway is simply too narrow. 
Only signs are relevant.
  * for two cars at least, maybe two motorcycles on either side could work.
  * but the tag has no explicit definition

See the edit: https://www.openstreetmap.org/changeset/128351401
and how the tagging is represented here: https://parkraum.osm-verkehrswende.org/project-vector-tiles/#15.28/52.617135/13.308108
and the proposal for `parking:condition:either_side_only` https://wiki.openstreetmap.org/wiki/Proposed_features/Parking_lane_conditionals/Examples_of_old_style_of_tagging

The explicit problem I have with the edit is that only one side of the street is used by people to park, hence the wrong tagging.
Today it would be illegal to park on the other side too, but not if everyone decides to park on the other side, which is legal and should be tagged as such

**Comment by matkoniecz** [comment]
> I've seen an edit made where some streets were falsely tagged as one side parking only.

are you describing places where one side was tagged as having parking and other had no info at all, either about provided parking or about not providing parking?

Can you link specific objects?

**Comment by matkoniecz** [comment]
See also #4427

> I have been trying out the street parking overlay feature, and I have been finding that when I am surveying much of the time, I cannot see the side of the street opposite me to tell the parking conditions along it, but the input only allows entering on both sides of the way. Examples of situations where this happens are when one side of the sidewalk is closed, or when the vehicles parked are too tall to see the signs, or the road is very wide and the opposite side is actually quite far away. Right now, I am on the bus, and the windows on one side are too low for me to see many signs from where I am sitting, but I can see them on the other side.

**Comment by joshinils** [comment]
https://www.openstreetmap.org/way/281637525
https://www.openstreetmap.org/way/1095763092

both are wrongly tagged with
`parking:lane:right=no`
there are no signs forbidding parking. only the cars parked on the other side are the reason for not parking on the right, and i guess why they tagged it as such.

it would be correct to tag both sides with 
`parking:lane:both=parallel` + `parking:lane:both:parallel=on_street`
however the street is too narrow to park on both sides at the same time. but it is legal to choose both sides to park.

**Comment by westnordost** [comment]
I wouldn't say it is wrong, @joshinils . There is simply no way to record the situation as described yet. parking:condition:either_side_only=yes is not approved.

If it gets approved, it would (need to be) an "other answer" because apparently the condition is supposed to be valid for both sides? (Nice, another tag that breaks with the :left, :both: right scheme 🙄. Wouldn't `parking:condition:both=if_space` or something make more sense?)

**Comment by westnordost** [comment]
So at the moment I'd tend to reject this as not actionable, hoping it will be properly covered in the street parking revision proposal. The topic can then be reopened.

**Comment by joshinils** [comment]
> So at the moment I'd tend to reject this as not actionable, hoping it will be properly covered in the street parking revision proposal. The topic can then be reopened.

I understand. However, the person still tagged one side of the road as not legal to park, whereas it actually is.
It is wrong to not tag both sides with the parking data, since it is legal to park there, just not at the same time.

**Comment by matkoniecz** [comment]
In such case user can leave note, as usual with any weird case.

**Comment by joshinils** [comment]
> In such case user can leave note, as usual with any weird case.

Its not weird, any normal living street is too narrow and both sides allow parking.

**Comment by westnordost** [comment]
Yeah, it is quite a common case which have been overlooked in the original proposal I guess (because it was very much focused on tagging parking **lanes**, not just any parking).
