### ISSUE TITLE
Disable "What's the house number of this building?" quest in Latvia

### ISSUE THREAD

**Issue by i-ky** [streetcomplete/StreetComplete#4597]
**Use case**
In Latvia addresses in OSM are [automatically synced with government data](https://wiki.openstreetmap.org/wiki/Automated_edits/Latvia-bot) and there is a consensus in the community that addresses should not be altered manually (including via StreetComplete). Any imperfections in address assignment need to be addressed by adjusting automation scripts or editing contours of incorrectly mapped buildings.

**Proposed Solution**
"What's the house number of this building?" quest should be disabled in Latvia.

**Comment by matkoniecz** [comment]
> there is a consensus in the community that addresses should not be altered manually

Can you link mailing list discussion or forum discussion or something similar confirming this?

**Comment by i-ky** [comment]
Dear @matkoniecz,

There was [mailing list discussion](https://lists.openstreetmap.org/pipermail/talk-lv/2022-January/006357.html) (in Latvian) prior to automation implementation, quoting:
> Pie atjaunošanas arī jāņem vērā, ka OSM jau pievienotajos datos būs veikti manuāli labojumi adresēs, kas nesakritīs ar Adrešu reģistru. Tāpat var būt pievienoti jauni adrešu objekti vai atribūti. Šie labojumi jāizlabo atpakaļ vai jāatsauc (ideāli, ja ar ziņu lietotājam, kas veica labojumus, ka adreses tiek uzturētas automātiski un labojumi nav nepieciešami). Būtībā jānodrošina, ka pēc atjaunošanas OSM dati atbilst Adrešu reģistram.

Translation into English:
> When updating, it should also be taken into account that data already synced to OSM will have manual edits to addresses that will not match the Address Register. It can also contain new address objects or attributes. These edits must be corrected back or reverted (ideally with a message to the user who made the edits that addresses are maintained automatically and no edits are required). Basically it must be ensured that the OSM data corresponds to the Address Register after update.

Automatic address updates follow the logic above, except "message to the user" part has not been implemented yet, as far as I know.

The fate of manual edits and StreetComplete quest in question was also discussed in [Signal group chat](https://signal.group/#CjQKIBQDZFRYENhgTzY0czaSnYxt6-NCXdW5Rp2o6144bO4wEhCUSXKPmsjKnTbzUgLj0MpL). One can join it, but [due to specifics of Signal, message history will not be visible to new chat members](https://www.reddit.com/r/signal/comments/c7bj3a/is_there_a_way_for_new_members_of_a_group_to_see/). I can quote/translate the discussion around StreetComplete quest if you wish, I guess it would be impossible for me to prove the legitimacy of these quotes.

**Comment by matkoniecz** [comment]
Is this import already discussed on imports mailing list?

**Comment by i-ky** [comment]
> Is this import already discussed on imports mailing list?

Sorry, I don't know the answer. I have created this issue more from a "StreetComplete user" perspective, than from "import's author/maintainer" perspective.

**Comment by i-ky** [comment]
I guess here is the list of countries where `AddHousenumber` quest is disabled (with more links for more context): https://github.com/streetcomplete/StreetComplete/blob/34b96b76a3a3592171a2a7662b4ca9072ceab692/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L30-L38

**Comment by i-ky** [comment]
> Looks like there is a similarity here: #4360

Or even #229.

**Comment by westnordost** [comment]
I see no reason to not disable Latvia, as it is the same situation as for other countries in which it was disabled. Do you, @matkoniecz ?

**Comment by matkoniecz** [comment]
The only part that I am unsure about - is it already running project? But yes, it can be disabled - after all if it will end stuck on something quest can be enabled again.

**Comment by soshial** [comment]
It definitely is a running project, @matkoniecz, as you may see in [bot's history](https://www.openstreetmap.org/user/latvia-bot/history).
