### ISSUE TITLE
presets: the floating+ can hide new presets when you have a lot

### ISSUE THREAD

**Issue by amandasaurus** [streetcomplete/StreetComplete#4603]
I created many presets and now I can't select one because it is underneath the floating+ to make a new preset 

![Screenshot_2022-11-03-19-25-10-63_8a0120479a21d3140f77758520f645bd](https://user-images.githubusercontent.com/1547/199804329-072c917e-9ba9-43cd-9476-f09c8efa929f.jpg)

**How to Reproduce**
Add lots of presets 

**Expected Behavior**

Not sure.

**Versions affected**
49.0 beta 1

**Comment by westnordost** [comment]
Jeez
