### ISSUE TITLE
icons of vacant shops are sometimes wrong

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4607]
### How to Reproduce
Search for vacant shops that have additional tags, such as `building=house` or `indoor=room`
The icons of the house or the room are displayed on the map, but in the "editing window" is the correct icon for vacant shops.

![grafik](https://user-images.githubusercontent.com/92865620/200128013-5ec8867c-50c8-4dcc-b82b-2b6edaba588c.png)
![grafik](https://user-images.githubusercontent.com/92865620/200128041-edbf62e9-516d-4bf1-81cc-92107b811932.png)
Locations to reproduce: E. g.: [here](https://www.openstreetmap.org/way/201705739) or [here](https://www.openstreetmap.org/?mlat=53.11138&mlon=8.74746#map=18/53.11138/8.74746
)

### Expected Behavior
Show the correct icon on the map

### Versions affected
v49

**Comment by matkoniecz** [comment]
that appears to be one of consequences of https://github.com/westnordost/osmfeatures/issues/16 (normally they also got wrong icon - of `shop=yes`, not of `shop:disused=*`)

I wanted to look into it at some point, but first I want to complete already started stuff and then I would need to figure out how to configure gradle to use local version of `osmfeatures`

**Comment by westnordost** [comment]
Hmm, I am not sure what to do about that that wouldn't be hacky. Implementing the mentioned missing feature https://github.com/westnordost/osmfeatures/issues/16 would fix it, so I am closing this one as it should be solved upstream.

**Comment by FloEdelmann** [comment]
https://github.com/westnordost/osmfeatures/issues/16 is now implemented
