### ISSUE TITLE
Allow cloning quest presets

### ISSUE THREAD

**Issue by cascheberg** [streetcomplete/StreetComplete#4609]
**Use cases**
1. I want to have one (or multiple) custom presets that have few quests disabled that I never want to answer, and use that preset as a base for creating new presets.
2. I have multiple quest presets that in a way all focus on one type of quest, but are only different in the level of detail of enabled quests. It would be nice to be able to copy one present so that I only need to enable/disable a few quests instead of going through all quests all over again.

**Proposed Solution**
1. In the "Manage presets" screen, add an action to the per-preset three dot menu to clone a preset
2. or: when creating a new preset, always copy the settings of the currently selected preset

Additionally, I think it would make sense to automatically select a newly created preset, assuming that the whole point of creating a new preset is to use or modify it.

**Comment by mnalis** [comment]
I'd also like that, yes. It was initially proposed (e.g. https://github.com/streetcomplete/StreetComplete/issues/1654#issuecomment-648777826) but that specific part was not implemented... But then, neither was preset renaming, and that has arrived recently; so maybe this would too.

(The [StreetComplete Expert Edition fork](https://github.com/Helium314/StreetComplete/)  has that feature implemented: when adding a preset, it asks if you want to copy settings from some other preset.)

**Comment by mnalis** [comment]
There is somewhat clumsy workaround in `v49.0` the meantime: `rename preset to wanted new value`, `export preset + copy URL`, `rename preset back to old value`, `paste URL in browser and select SC to import the preset`. Although, it obviously does not work with `Default` preset, so I recommend people **_never modify that one_** in the first place, but always create new one if they want to change anything.
