### ISSUE TITLE
Expand »Does X still exist?« quest to COVID-19 testing stations and vaccination centers

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#4610]
**Use case**

At least in (parts of?) Germany (this may require some assessment of how things are elsewhere) the situation is that those two types of POI fluctuate a bit over time and become outdated much faster than, say, shops, or benches. Vaccination centers have often been placed in other buildings, like sports or event centers, temporarily. Test stations are often just containers or temporary huts that may have been removed due to lack of demand again a few months later.

**Proposed Solution**

Since object existence is already asked for, this could probably piggyback on the same question. Question interval may be as low as two months, perhaps, but maybe six months is a better value (albeit with the complication that we then just swap seasons, and thus demand for those things).

Around here I think vaccination centers existed for a few months at most (and some were long outdated after they've been removed again); as for testing stations, they seem a bit longer-lived in most cases.

**Comment by mnalis** [comment]
Related tags can be found in https://wiki.openstreetmap.org/wiki/COVID-19_-_How_to_Map:
probably [healthcare=sample_collection](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dsample_collection) and [healthcare:speciality=vaccination](https://wiki.openstreetmap.org/wiki/Tag:healthcare:speciality%3Dvaccination) + [vaccination](https://wiki.openstreetmap.org/wiki/Key:vaccination)=covid19 ?
