### ISSUE TITLE
AR camera is black after changing language

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#4611]
This only happens with the width quest. Not with notes, trying to take a picture for a note fixes the camera (once, not for other tries). Force closing the app fixes this.
**How to Reproduce**

Open app, change language, try to measure road width, screen is black. I can even turn it a bit and start measuring after tapping, the arrow is also not visible.

**Expected Behavior**

Normal screen of camera 
**Versions affected**

49.0

**Comment by FloEdelmann** [comment]
So you change the language in the app or in the Android system settings? If it's the latter, do you change the app for the whole system or only for StreetComplete? Also, what's your Android version?

**Comment by joshinils** [comment]
i changed it in the app

**Comment by Astrrra** [comment]
Can verify that this happens on Z Fold 4 with Android 12 (One UI 4) as well

**Comment by MonsterDruide1** [comment]
Also verifying this happens with Android 11 (MIUI 12) on Redmi Note 8 Pro.

**Comment by westnordost** [comment]
This is now obsolete because the measuring is done in a separate app.

**Comment by joshinils** [comment]
So this will work better in a version after 50.2 I assume? Currently, this is still broken.

**Comment by westnordost** [comment]
The standalone AR app will not let you change the language.
