### ISSUE TITLE
Improve maxspeed quest UI

### ISSUE THREAD

**Issue by cascheberg** [streetcomplete/StreetComplete#4612]
**Use case**
The maxspeed quest answer option "no sign" requires to answer two additional questions every single time. This is annoying an could be improved. The two questions that pop up are:
1. Are you sure no limit is posted?
2. Where is this street? (Rural / Built-up area)

**Proposed Solution**
For the first question, add an option to answer it only once per session (as it exists for "Are you sure you checked this on-site?" - "Don't show again for this session").
Include the answer options "rural" and "built-up area" (or other options, depending on the country) in the initial list of answer options, e.g.

- A sign
- It's within a (slow) zone
- It is a living street
- Built-up area, no sign, defaults apply
- Rural road, no sign, defaults apply

**Comment by westnordost** [comment]
Hmm. No. Reasons:
1. what is being asked int he second dialog can actually vary per-country. E.g. in the United Kingdom, it is not asked whether something is in a built-up area or not but something else. This may each require some additional explanation.
2. I don't really want to invest more time into the maxspeed quest while the tagging scheme is so broken that it requires to always specify the "road type" (e.g. urban/rural for Germany or others for other countries) just to record the information that there is no sign. Usage of alternative tags like [`maxspeed:signed`](https://taginfo.openstreetmap.org/search?q=maxspeed%3Asigned) which would allow for this question to be omitted is absolutely negligible, so there is no in-use alternative to the current `maxspeed:type=<country code>:<road type>` tagging.
3. Not really want to invest time to improve a disabled-by-default quest. (It is disabled by default for the above reason)

**Comment by westnordost** [comment]
I'd accept a PR for that,  but won't put in time myself.
