### ISSUE TITLE
Star count lost

### ISSUE THREAD

**Issue by Filbuntu** [streetcomplete/StreetComplete#4614]
Because I had problems to login into Maproulette, I revoked all OAuth 1 "Authorised Applications" of Maproulette tokens and some old StreetComplete tokens in my OSM profile. But when I returned to StreetComplete some hours later the star count was 0 and I may have had to login again. 
Could it be that I deleted the wrong token?
Is the star count connected to a certain token? 
I still have several active tokens under  OAuth 1 "Authorised Applications" for StreetComplete incl. the oldest one and I thought I could delete the old ones without compromising the data.

**How to Reproduce**
Not sure if I can reproduce it, but probably by deleting certain  OAuth 1 "Authorised Applications" tokens.

**Expected Behavior**
It would be great if StreetComplete recognises the OSM account (not by a token but by the user name) and restores the star count after tokens are deleted. 
I have had a nice number and I like to see if more people are beating me which shows that more people are mapping. And I am very happy if more people are improving OSM.

**Versions affected**
v48.0 (F-Droid)

**Comment by Helium314** [comment]
> It would be great if StreetComplete recognises the OSM account (not by a token but by the user name) and restores the star count after tokens are deleted.

Thats already what is happening. Maybe currently it takes a little longer than usual, because there is some re-processing going on for weekly stats.
But don't worry, you just may need to wait a little.

**Comment by FloEdelmann** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1299379519 and the following comments.

**Comment by Filbuntu** [comment]
Thank you both for the quick and reassuring replies!

> See [#4568 (comment)](https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1299379519) and the following comments.

Ah, there seems to be a coincidence with this as stated:
"So what I'll do now is to throw away the whole database (360MB) and let it be aggregated anew. This will take a while, in which there will be no statistics syncs possible"

I will wait patiently although I am an active user and sync should be quick:
" Hence, active users who use the app often will more quickly get to a state where their stats are up to date again."

But it may just take some time. 
Thanks again!

**Comment by Filbuntu** [comment]
I just read the posts[ in a bit more detail](https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1300103109):
> The re-populating is done bit by bit (a cron job that runs for 5 minutes every hour). Re-populating is about 2% done now (727 of 36800 users), so it looks like the whole thing will take a bit more than a month.

If you are one of the last ones, you will really need some patience 😊 and wait a month.
Does it mess up the database if new edits are done through StreetComplete in the meantime?

**Comment by matkoniecz** [comment]
> Does it mess up the database if new edits are done through StreetComplete in the meantime?

No. It is the same process that is handling exactly that and will catch up with them.

**Comment by Filbuntu** [comment]
Today (after 3 days) the count returned and the biggest bulk of stars is back. Some hundred stars are missing (at least from what the last count showed). Maybe the count was recounted/resorted and some double counting was deleted or the missing stars will arrive within a month or some stars are gone into the sky 🌃 😀.

**Comment by matkoniecz** [comment]
Or processing is still ongoing and for example last month of your edits is not yet processed.

**Comment by Filbuntu** [comment]
For the record: Today the recent edits/stars were added today. It looks like it is complete again. 
Thank you everyone, also for the great updates of the app pushed this week! May many more use the app to improve OpenStreetMap.
