### ISSUE TITLE
enhance POI creation from overlay, add amenity:playground

### ISSUE THREAD

**Issue by call-me-matt** [streetcomplete/StreetComplete#4616]
I noticed that in POI overlay I cannot add an amenity playground. But on the other hand, some very special tags like `Löwenbäcker Schaper` are in the list. I suppose [this list](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/osmfeatures/brands/presets-DE.json) is autgenerated as input? Maybe can you add a README to the folder in order to learn about the source and what is necessary to add `amenity:playground`, for example?

AS-IS: amenity:playground is missing in the list
TO-BE: a README should be created to learn how to add entries to the POI overlay creation menu without the risk of losing changes at a later moment in time if the list is re-created.

**Comment by legofahrrad** [comment]
The shop overlay is for adding shops. Bakeries are shops, playgrounds not. As simple as that.

**Comment by Helium314** [comment]
What you call "POI overlay" is called "shop overlay" in the app, hence you can only add things that are reasonably shop-like.
Why would you think a playground should qualify?

**Comment by call-me-matt** [comment]
You are right, it's only shops. Too bad there is this limitation.
Still would be good to add a readme to the folder where this list is coming from and how to modify

**Comment by call-me-matt** [comment]
just for reference if someone else stumbles across this issue: POIs can be added without limitations with [EveryDoor](https://every-door.app/) or [OSMand](https://www.osmand.net/)

**Comment by mnalis** [comment]
See also: https://github.com/streetcomplete/StreetComplete/issues/4343#issuecomment-1304780941
