### ISSUE TITLE
[sc.app] Link to OpenStreetMap

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4618]
I think linking directly to the main page of OSM is not following the user expectation.

I think linking to the [explanation page of what OSM is](https://www.openstreetmap.org/about), would follow the principle of least astonishment best.

What do you guys think?

**Comment by HolgerJeromin** [comment]
Probably better discussed here: https://github.com/streetcomplete/streetcomplete-website

**Comment by RubenKelevra** [comment]
> Probably better discussed here: https://github.com/streetcomplete/streetcomplete-website

Ah damn, this wasn't shown to me in the search. I'm sorry.

**Comment by FloEdelmann** [comment]
For reference: Moved to https://github.com/streetcomplete/streetcomplete-website/issues/3
