### ISSUE TITLE
Disable house number (and house name) quest for Latvia

### ISSUE THREAD

**Issue by soshial** [streetcomplete/StreetComplete#4621]
In Latvia, we have an [automatic bot](https://github.com/Davis-Klavins/osm-latvia-bot) that 1) adds addresses to OSM from the official state address database and, more importantly 2) deletes all new addresses that don't exist in the database.

As in the [bot description](https://wiki.openstreetmap.org/wiki/Automated_edits/Latvia-bot#Operating_Principles):
> Open data [published](https://data.gov.lv/dati/eng/dataset/valsts-adresu-registra-informacijas-sistemas-atvertie-dati) by the State Land Service are authoritative, thus almost all existing OSM address data that differs will be replaced/removed.

It means that even if user adds some address in StreetComplete, it will be removed by the bot the next day. I think, that @Davis-Klavins can provide more information on that.

**How to Reproduce**

**Expected Behavior**
Don't ask for house numbers and house-names. These quests should be shown as disabled in the list of quests. 

**Versions affected**

**Comment by Helium314** [comment]
Is there anything new compared to #4597?

**Comment by matkoniecz** [comment]
closing based on assumption that it is the same as https://github.com/streetcomplete/StreetComplete/issues/4597 which will be included in the next version

**Comment by matkoniecz** [comment]
please comment if it is not actually a duplicate

**Comment by soshial** [comment]
What a coincidence 6 days apart, @i-ky!
I created a duplicate, @matkoniecz, sorry for that.
