### ISSUE TITLE
New calendar UI is empty despite contributions

### ISSUE THREAD

**Issue by Altonss** [streetcomplete/StreetComplete#4623]
New calendar UI is empty despite contributions

**How to Reproduce**
Open the new calendar UI

**Expected Behavior**
There should be something in the calendar

**Versions affected**
Android 13, SC v 49.0 from F-Droid

**Comment by Helium314** [comment]
Probably you just need to wait. There is some processing happening that may take a while: https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1299379519

**Comment by matkoniecz** [comment]
yes, due to unrelated issue there is sadly some delay in statistics processing
