### ISSUE TITLE
Profile info does not get synced even after 2 days

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4624]
**How to Reproduce**
Had to reinstall SC on my mobile. After logging in, i expect the profile stats to be syncing. But they are in this state ("Your stats are still syncing") since 2 days ago. So i retried with logging in again. Still nothing happens after ~3 hours.

**Expected Behavior**
User stats are synced after e.g. 1 hour. What is the expected time to have the user stats synced? Do i have to upload a solved quest in order to trigger the process?

**Versions affected**
v49

**Comment by mnalis** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1299379519 and the following comments.

(We should probably keep one of those issues open and **pin** it until the situation is resolved, instead of closing them, as it only invites new ones to be opened)

**Comment by matkoniecz** [comment]
done with #4625
