### ISSUE TITLE
Profile data is being regenerated, statistics may be not displayed for now, it should appear before 2022-12-10 (estimated)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4625]
It is necessary to regenerate it as there was bug with recording location of edits.

As result StreetComplete statistics server needs to generate all statistics based on edit list. Due to large volume of data it will take some time.

See https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1299379519

Note that date is approximate.

**Comment by matkoniecz** [comment]
closing as effects are still seen but fix is implemented (implemented, deploy in progress)

**Comment by totoroot** [comment]
If we have logged in on a new device and it does not show our old edits because it has not yet been synced, but we have mapped in the meantime, will these contributions be recorded and counted towards our total edits or will this have to be resolved manually with our user ID once the profile data has been synced?

**Comment by matkoniecz** [comment]
> will these contributions be recorded and counted towards our total edits

Yes.

StreetComplete statistics server in not taking any data from phones, it is taking it only from public record of edits.

**Comment by westnordost** [comment]
Currently it is 12% done.

**Comment by westnordost** [comment]
31% done

**Comment by mnalis** [comment]
(With approx. `1.58%` daily progress, it looks more likely it would finish in the first week of January, rather then early December? i.e. `~44` more days unless tempo changes, or I miscalculated?)

**Comment by westnordost** [comment]
53% done

**Comment by westnordost** [comment]
95% done

**Comment by westnordost** [comment]
done now
