### ISSUE TITLE
autoremove source:TAG when editing TAG?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4626]
while progressing with #4378 I noticed that editing some tag will not delete `source:`

In some cases it is manually implemented - see https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface/SurfaceAnswer.kt#L50

But maybe it would be preferable to always remove it? For example if `stile` tag is being edited by SC then maybe old `source:stile` should be removed? (in all cases: when it is being added, replaced or removed)

**Comment by matkoniecz** [comment]
Maybe also `check_date:whatever` should be remove when tag `whatever` is edited?

For example `check_date:construction = 2022-09-07` is staying on https://www.openstreetmap.org/way/281648784 after solving construction quest

![screen05](https://user-images.githubusercontent.com/899988/201090824-3ff331a0-0c4c-4873-aef7-4b83291f0cd6.png)

(`access=no` staying is a bigger problem, but that is a separate issue)

**Comment by matkoniecz** [comment]
Asking mostly because I can add special handling in surface layer - but I am thinking about attempt to add general support for all edits.

Though it would need to be done in some smart way to avoid situation where StreetComplete removes `source:` tag or `check_date:` tags just added by StreetComplete itself

Not sure is it solvable and maybe each quest needs to deal with it on its own and trigger all cleanup manually...

**Comment by westnordost** [comment]
Hm, not sure. I am not a big fan of things like that.

**Comment by matkoniecz** [comment]
In meantime I was trying to design something that would work reliably and I found some traps/potential bugs and solutions for them.

So that may be trying to put too much magic and maybe instead it should be done (if done at all) manually. Maybe with some convenience function tracking down generic tags like `check_date` prefix?
