### ISSUE TITLE
expand overlay colour palette - add gray

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4627]
I am still trying to figure out some things with surface overlay, colour choice is among them

but in process of design it seems to me that two colours can be added to the official overlay colour set, see latest at https://davidmathlogic.com/colorblind/#%23444444-%23FF0000-%231A87E6-%232FACE8-%2330D4EE-%2310C1B8-%230DA082-%23F37D1E-%23EEBD0D-%23B6EF28-%23DDDDDD

It seems to be distinctive like other overlay colours (from each other and map) while testing them (at least for me)

![screen07](https://user-images.githubusercontent.com/899988/201343121-fbc01b02-3239-4d95-9a0a-ff0772844949.png)

gray is not vibrant but usable as last resort in case we need more colours, also for other overlays

**Comment by westnordost** [comment]
This does not stand out from the map though.

I do plan to make the background map greyscale for (certain?) overlays so that the highlighting contrasts more clearly from it. This means that greyscale "highlight" "colors" are out of question.

**Comment by matkoniecz** [comment]
@westnordost 

> This does not stand out from the map though.

In my testing it worked relatively nice.

![screen03](https://user-images.githubusercontent.com/899988/202401777-17af9feb-fd63-420a-8294-893ef836e008.png)

(there are colour blindness issues but making them exactly like other colour is worse for both - obviously, I am trying to find something working well in general. Maybe 100% white would work well?)

**Comment by westnordost** [comment]
Well as said, I plan to desaturate the background map for certain overlays. This also enables to add some more colors to the palette, in particular, lighter and darker colors that would otherwise not be standing out enough from the light map or the dark map, respectively.
