### ISSUE TITLE
Too low contrast in street lighting overlay

### ISSUE THREAD

**Issue by ahstro** [streetcomplete/StreetComplete#4629]
When using the street lighting overlay, it is really difficult to make out which segment is selected when selecting unmapped ways.

Zoomed out:
![Screenshot_20221112-162543_Street­Complete](https://user-images.githubusercontent.com/3090888/201481479-a394a9ef-79e7-4bd2-955a-554d155d96d1.png)

Zoomed in:
![Screenshot_20221112-162528_Street­Complete](https://user-images.githubusercontent.com/3090888/201481483-a3a80c24-f24f-4098-b14e-493f01d2508f.png)

**How to Reproduce**

1. Enable the street lighting overlay
2. Press an unmapped (red) way
3. Have difficulty seeing where the segment starts/ends

**Expected Behavior**

Use a color with higher contrast, so the selected segment is more easily spotted

**Versions affected**

49.0

**Comment by legofahrrad** [comment]
See #4417

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/4417

**Comment by ahstro** [comment]
Ah, thanks! My bad, tried searching, but poorly apparently 😅

**Comment by matkoniecz** [comment]
next people will be more likely to find it :)
