### ISSUE TITLE
Force feature when adding a new shop using Shop overlay

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4633]
**How to Reproduce**
I do not exactly know how to do this, but it is possible to add a new shop, which is only a node having a name tag, e.g. https://www.openstreetmap.org/changeset/128903788

**Expected Behavior**

It shall not be possible to add a node with a name tag only. A shop or amenity or any other feature tag should be enforced.

**Versions affected**
v49.1

**Comment by Helium314** [comment]
probably fixed in https://github.com/streetcomplete/StreetComplete/commit/2df7513cf8c16a2bccbcb3e128ad96fb9fe52acd

**Comment by westnordost** [comment]
Yes, fixed in v49.2
