### ISSUE TITLE
stop asking for building levels of building=farm_auxiliary

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4637]
Some have no clear building count.

For example this building may have a single open space inside or two levels, some have two levels in part of a building and two elsewhere:

![IMG_20220811_105317](https://user-images.githubusercontent.com/899988/202505853-420e00af-4d1d-4ba2-a11d-1bc0d3d039ce.jpg)

![IMG_20220811_105258](https://user-images.githubusercontent.com/899988/202505833-9d37084f-73c6-445f-8459-a993401c2d11.jpg)

pictured building: https://www.openstreetmap.org/way/323238779

See also:  stop asking for building levels of building=industrial #2835 

See https://github.com/streetcomplete/StreetComplete/blob/448d05a0ea0fd00f42f5d9efb7f0f779016f09ca/app/src/main/java/de/westnordost/streetcomplete/osm/BuildingLevels.kt for potential place of modifying code.

**Comment by rhhsm** [comment]
@matkoniecz I have some more suggestions for "stop asking" issues, such as stop asking for A/C for restaurants that don't have indoor seating or stop asking for bridge structure for steps tagged as bridge. Maybe a sticky post could be created where such suggestions can be added?

**Comment by matkoniecz** [comment]
@rhhsm in such cases it is perfectly fine to create new issues ( https://github.com/streetcomplete/StreetComplete/issues/new/choose or a green button near top )
