### ISSUE TITLE
Some more "stop asking" requests

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4643]
I noticed a few cases where I think no quest should be asked:

1. It should not be asked if restaurants have air conditioning for places that don't have indoor seating (i.e. no seating at all, or only outdoors). These are places such as only take-away or street food sites. It's likely that customers are inside for only a short time, so will not be very interested in whether it is air conditioned.
2.  Don't ask for bridge structure for steps tagged as bridge. These are steps with empty space below them, and they may cross a path at their higher part. None of the proposed bridge structures fit them well.
3. Don't ask for opening times of offices that don't usually serve walk-in customers. Most of these that I found are tagged office=it; I think it should not be asked for office=company as well. It should be asked for offices that serve the general public, such as lawyer, estate agent, employment agency, notary, therapist, travel agent, etc. There's a large grey zone of offices where it depends on the local habits whether they are open to consumer visits; these should still be asked, I think (it's easy enough to reply "no opening times visible")

**Comment by Helium314** [comment]
> Don't ask for bridge structure for steps tagged as bridge.

Here it's best to leave a note. `man_made=bridge` should only be used on areas, so tagging `highway=steps` on the same element is not recommended anyway. And if `man_made=bridge` is separate from steps, there is nothing that SC can do (except complicated analysis of nearby elements)

> I think it should not be asked for office=company as well

I'd recommend to read the filter in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt. It's not asked for `office=company` currently.

**Comment by rhhsm** [comment]
> > Don't ask for bridge structure for steps tagged as bridge.
> 
> Here it's best to leave a note. `man_made=bridge` should only be used on areas, so tagging `highway=steps` on the same element is not recommended anyway. And if `man_made=bridge` is separate from steps, there is nothing that SC can do (except complicated analysis of nearby elements)

OK, as long as it's not asked of ways, I'm fine. The case I found is here https://www.openstreetmap.org/way/544238414 (all steps are within bridge areas there)

> > I think it should not be asked for office=company as well
> 
> I'd recommend to read the filter in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt. It's not asked for `office=company` currently.

Thanks for the link. I think "it" should be removed. "notary" and "therapist" could be added, and maybe "solicitor" and "translator" (used quite rarely, but there are many legalised translation offices in my neighbourhood). "diplomatic" should only be asked when consular services are offered.

**Comment by matkoniecz** [comment]
> Don't ask for bridge structure for steps tagged as bridge. These are steps with empty space below them, and they may cross a path at their higher part. None of the proposed bridge structures fit them well.

Can you link some affected items? It sounds like bad data in OSM.

> The case I found is here https://www.openstreetmap.org/way/544238414

https://www.openstreetmap.org/note/3450345 - definitely bad data in OSM as far as I see. Maybe we can skip ones that are marked as indoor?

> It should not be asked if restaurants have air conditioning for places that don't have indoor seating (i.e. no seating at all, or only outdoors).

How it is being tagged? Can you link some affected items?

> offices

The problem here is no clear distinction between walk-in offices and ones completely internal (I commented about this on tagging mailing list some time ago but it had no real traction, some people proposed `access=private`/`access=no` for fully internal offices without walk-in acceptance)

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt#L78-L83

**Comment by matkoniecz** [comment]
>  "it" should be removed. "notary" and "therapist" could be added, and maybe "solicitor" and "translator" (used quite rarely, but there are many legalised translation offices in my neighbourhood). "diplomatic" should only be asked when consular services are offered.

potentially actionable but not researched that (is there a past discussion about that?)

https://taginfo.openstreetmap.org/tags/office=translator - just 173 uses makes it likely not worth handling

**Comment by rhhsm** [comment]
> > It should not be asked if restaurants have air conditioning for places that don't have indoor seating (i.e. no seating at all, or only outdoors).
> 
> How it is being tagged? Can you link some affected items?

https://www.openstreetmap.org/node/8554092645 https://goo.gl/maps/zViS3KUKevwwMmuGA This place you can't even enter as a customer, so it's silly to ask if it's air conditioned. But even if you could, you wouldn't spend much time in it if all you can do there is order your food and wait for it. I think it only makes sense to ask for air conditioning in places where you would spend considerable time (longer than in a typical shop, for instance) so it should have indoor_seating=yes

> > offices
> 
> The problem here is no clear distinction between walk-in offices and ones completely internal (I commented about this on tagging mailing list some time ago but it had no real traction, some people proposed `access=private`/`access=no` for fully internal offices without walk-in acceptance)

I guess most offices are not walk-in, so the default should be to assume they are private and no opening hours should be asked

**Comment by matkoniecz** [comment]
> It wouldn't be difficult to add "solicitor" and "translator", is it?

No, adding itself is relatively easy. But I would prefer to avoid analysing every single `office` value :)

> https://www.openstreetmap.org/node/8554092645

OK, I think that skipping `indoor_seating=no` objects makes perfect sense (not making edit for now)

> `office=it`

still not investigated this one

**Comment by matkoniecz** [comment]
`office=it` was added in https://github.com/streetcomplete/StreetComplete/commit/4e12e8727466e4f739912ab74f8824819a603f32

@dbdean Can you look through this thread? Do you think that `office=it` should be asked about opening hours?

See also #3982 where it was already discussed a bit. 

I would be tempted to add "that is an internal office, not accepting walk-ins" or similar. #2051 is not really applying as private/public state of an office is not impacting nearby objects.

**Comment by rhhsm** [comment]
> `office=it` was added in [4e12e87](https://github.com/streetcomplete/StreetComplete/commit/4e12e8727466e4f739912ab74f8824819a603f32)
> 
> @dbdean Can you look through this thread? Do you think that `office=it` should be asked about opening hours?
> 
> See also #3982 where it was already discussed a bit.

Maybe the high % of office=it that have opening hours is because the staff of such offices are more likely to be OSM contributors and have added their work place including opening hours, even though they are not walk-in?

**Comment by mnalis** [comment]
- I agree that  entries having `indoor_seating=no` (and `takeaway=only`!) should be skipped in `air-conditioning quest`. I can do PR for that, unless someone else prefers to?
- yes, I'd skip `Bridge type quest` on `indoor=yes` too. That seems reasonable (more complex detections of ways inside `man_mane=bridge` polygon like `steps` ways are likely not worth it).
- `opening_hours=*` on `office=it` is more complicated. According to [taginfo](https://taginfo.openstreetmap.org/tags/office=it#combinations), over `20%` of them have `opening_hours` mapped, which is a big number, especially as other keys which almost certainly have walk-in (e.g. [office=lawyer](https://taginfo.openstreetmap.org/tags/office=lawyer#combinations)) have similar or smaller percentage of `opening_hours=*` mapped. So I would not change that (at least not without much more in-depth research). See also https://github.com/streetcomplete/StreetComplete/pull/3982#pullrequestreview-949864205 and below for more details. Also, it might be country dependent (of even IT branch dependent). Anyway there is "No opening hours sign" which is correct answer there in such cases when there is no walk-in.

---

P.S. it would really be best than  **each such request is reported as separate issue**. While (just a little) more work for submitter, it has many advantages
