### ISSUE TITLE
Address overlay: show landuse=construction

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4646]
**Use case**
When checking new buildings and adding their adresses, it happens that no building is visible in Street Complete. However that does not mean it is not there in osm. Maybe it is just tagged as construction.
Adding new addresses without building is possible with the address overlay, but I am missing the context if this building is already planned in osm.
If I want to see this, currently I need to switch to another app or check osm data online.
I would like to see constructions inside of SC, while mapping new adresses.
This will also help to better locate the spot where to put the new address.

**Proposed Solution**
Show "landuse=construction" and "building=construction" on the map, at least when address overlay is activated.

**Comment by matkoniecz** [comment]
Can you link some `building=construction` that are not shown? Or at least such area where it would be useful?

**Comment by SLMapper** [comment]
Thank you. Yes indeed. So for `building=construction` everything is fine.

However for most of the constructions for buildings I get along, the building itself is not yet mapped. Instead only the plot of land is marked as `landuse=construction`. This is of course often done, because the future dimensions of the building are not yet known to the osm surveyor.
It would however still be nice to see this in Street Complete, to know that there is an address that could be added. Often people write their address on e.g. a sheet of paper, even before the building is finished.

**Comment by mnalis** [comment]
>  It would however still be nice to see this in Street Complete, to know that there is an address that could be added. Often people write their address on e.g. a sheet of paper, even before the building is finished.

Related: if you see house address there that is not mapped (or any other missing or incorrect detail for which there is no quest in StreetComplete), you can long-press at the location and choose `Create new note` to note (With a test, or a picture, or both) that situation (so you or other mappers can later map that building). 

As an alternative, on that long-press you can also choose `Open location in another app` like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) and map it immediately, if you prefer that (but that is more complicated).

**Comment by westnordost** [comment]
Closing because:

1. _building=construction is shown and even editable with the address overlay._

2. for landuses, you wouldn't want to add it to the landuse. So just add a housenumber node instead.
