### ISSUE TITLE
When adding a shop in the Shop overlay without entering a name, shop name quest does not appear

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4648]
While being off line during survey:
When adding a shop using the Shop overlay and entering a name, after tapping the check mark, the opening hours quest for that shop appears (expected behaviour).
When adding a shop without entering a name (because there is no name sign, for instance), neither the shop name nor the opening hours quest appears. The shop name quest does appear after coming on line.

**Expected Behavior**
After adding a shop without entering a name, the shop name quest should appear. Alternatively, "no sign" could be an available answer option for the name field, or it could be asked if the shop really has no name (confirming this leads to name:signed=no being added).

**Versions affected**
Android 10, StreetComplete 49.2, working off line

**Comment by rhhsm** [comment]
Addition: the shop name quest does appear in all other layers and without one, just not in the Shop overlay. Being online or not doesn't seem to matter. A workaround is to switch to another overlay and there answer that the shop has no name sign, but that's not very elegant ;)

**Comment by Helium314** [comment]
`AddPlaceName` is disabled intentionally when using the shop overlay. In general overlays disable a quest if they contain functiononality of that quest (e.g. lit overlay disables lit quest).

Though the "no name" answer should be considered in the overlay then, maybe added in the "..." menu.

**Comment by rhhsm** [comment]
> `AddPlaceName` is disabled intentionally when using the shop overlay. In general overlays disable a quest if they contain functiononality of that quest (e.g. lit overlay disables lit quest).
> 
> Though the "no name" answer should be considered in the overlay then, maybe added in the "..." menu.

Adding an option to add `name:signed=no` as an answer instead of leaving the name field empty would solve this issue

**Comment by westnordost** [comment]
> Adding an option to add name:signed=no as an answer instead of leaving the name field empty would solve this issue

Hm, I am not sure if this would be okay.

After all, in the sidewalk and parking overlay, you can also leave one side empty. That doesn't mean that the other side has no sidewalk or parking, it just means that you selected nothing yet.

It is the same for the name in the shop overlay.

**Comment by legofahrrad** [comment]
The address overlay has in the "…" menu an option "no address here" that adds noaddress=yes. Same could be interesting for the shop overlay for the name, e.g. an option saying "no name signed", tagging "name:signed=no".
If any user adds a name in the name field of the shop overlay to a shop afterwards, the name should be added and name:signed=no should be removed.

**Comment by westnordost** [comment]
Sounds counterintuitive though. Why would anyone seek this other answer option when he could just leave the name blank?

**Comment by matkoniecz** [comment]
> Why would anyone seek this other answer option when he could just leave the name blank?

Either way mappers would likely prefer to not get later name quest asking about objects they added, so some way of adding `name:signed=no` or `noname=yes` would be useful.

**Comment by westnordost** [comment]
Yes, we can agree on that.

**Comment by rhhsm** [comment]
There should be a way to add `name:signed=no` in the shop overlay, either as an answer option when adding the shop, or by enabling `AddPlaceName` so it can be added when the shop name quest pops up. In my area, there are many small privately owned shops that have no name but only advertise what they're selling on their shop window. About 20% of shops in my area have no name.
![image](https://user-images.githubusercontent.com/69100427/205445852-61df11fc-de98-46f1-a52c-9271baf8a3ed.png)

**Comment by westnordost** [comment]
Ok, I will do that, then

**Comment by westnordost** [comment]
Hm, on the other hand, the user should input the place type + the name. Hence, what exactly should that other answer option do? And when a place with `name:signed=no` is edited, what should be displayed plus how should the user be able to edit that information?

**Comment by matkoniecz** [comment]
> Hence, what exactly should that other answer option do?

Provide option to mark that shop name was checked. Sometimes I add shops without adding names - and add names as I get closer.

For some reason many shop owners consider unreadable signs as cool.

**Comment by westnordost** [comment]
Uhm, I mean, what should happen in the UI when the user selects that answer option? There needs to be some kind of feedback when tapping that option.

**Comment by matkoniecz** [comment]
add "No signed name" as a placeholder text for name field? Placeholder text would be grayed out text in text field, disappearing when user start typing there.
