### ISSUE TITLE
GPS position error

### ISSUE THREAD

**Issue by HerveB29** [streetcomplete/StreetComplete#4652]
Hello,
I am new on StreetComplete, found it easy and fun to use.
But I found a difference between my real pisition and the GPS position dusplayed on the app.
This is the only app on my smartphone with such an issue...and I use quite a large number of map apps, depending on my needs.
Thanks for your help....this issue make it difficult to use the app.
Of course I have selected the "exact position" autorisation.

Thanks,

HerveB29

**Comment by HerveB29** [comment]
By the way, device is a Samsung S21, running under Androi 12. I've tried installation through FDroid as well as Google Play...same problem

**Comment by westnordost** [comment]
The app uses just the position the Android system provides and not the "Google Location Services" which enhance the precision, so that will be the reason. "Google Location Services" is used by many map apps not concerned about privacy.

**Comment by HerveB29** [comment]
Hello,
Thanks for your answer. Having the exact position could really be usefull in some cases...but i understand your choice of privacy.
Thanks again,
Herve
-- 
Envoyé de mon smartphone. Veuillez excuser ma brièveté.

Le 28 novembre 2022 02:00:16 GMT+01:00, Tobias Zwick ***@***.***> a écrit :

**Comment by westnordost** [comment]
If the app would use "Google Location Services", it could also not be on F-Droid, as it is not open source.

**Comment by HerveB29** [comment]
I guess it should be possible: for exemple OSM And shows an acurate position, yet it is available on F-Droid...though with some warnings about some anti-funcrions.

Herve
-- 
Envoyé de mon smartphone. Veuillez excuser ma brièveté.

Le 29 novembre 2022 13:09:32 GMT+01:00, Tobias Zwick ***@***.***> a écrit :

**Comment by mnalis** [comment]
> I guess it should be possible: for exemple OSM And shows an acurate position, yet it is available on F-Droid

No - F-droid version of OSMand actually has  "Google Location Services" removed (so GooglePlay and F-Droid versions of OsmAnd behave differently in number of ways).

**Comment by HerveB29** [comment]
Good evening,
I was out at sea and wanted to be back ashore before repplying.

On OSMand (F-droid version) the fix is 7meters from my real position 
On street complete the fix is 390meters away from my real position, eastwards.

Even without google location services, a basic GPS chip should do better than this.

Thank you anyway for your answers,

Sincerely,

Hervé 
-- 
Envoyé de mon smartphone. Veuillez excuser ma brièveté.

Le 30 novembre 2022 01:47:15 GMT+01:00, Matija Nalis ***@***.***> a écrit :

**Comment by westnordost** [comment]
Sorry man, as I wrote, the app simply displays what the Android system returns. I don't know what Osmand is doing differently. If you or someone else can find that out, I'd be of course open to include that improvement, whatever that is.

**Comment by westnordost** [comment]
FYI the code is here:

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/util/location/FineLocationManager.kt

It tries to get the position both from the GPS location and also from the [network location](https://developer.android.com/reference/android/location/LocationManager#NETWORK_PROVIDER) (location based on nearby of cell tower and WiFi access points, requires data connection) and decides which location to use based on the algorithm at the bottom of that file.

**Comment by Helium314** [comment]
> decides which location to use based on the algorithm at the bottom of that file

That's probably the only thing SC does different than other applications, because for requesting GPS locations there is no alternative.

The time check could in principle cause issues. I remember GPS and system time slowly drifting apart on my phone, which was reset on reboot (probably on some older Android version, don't see this any more).
But I would expect things to go wrong only in combination with network location.

@HerveB29 do you have network location switched on? If so, could you try switching it off?

**Comment by HerveB29** [comment]
Hello,
Wi-fi ou Bluetooth analysis options in order to increase position won't 
change anything,
While if i don't allow SC to use precise location, I won't get any 
position on SC.
I havn't found any other settings under Android 12.

Cheers

Le 13/12/2022 à 11:04, Helium314 a écrit :

**Comment by Helium314** [comment]
Ok, I have no idea about Android 12 settings...
But network-based location is really the only thing I can imagine that would give a location with such an offset.

Does the location you get in SC behave like a normal GPS location? Like, does it move with you? Or is it just staying in one place?
Oh, or could you try starting SC while your phone is in airplane mode? I think in airplane mode you should only be able to get actual GPS location, without any network based locations.

**Comment by Helium314** [comment]
Differences between SC and OSMAnd location requests:
* SC asks for minimum distance between GPS updates of 1 m, OSMAnd for 0: should not cause significant differences
* SC checks whether the device has GPS before requesting updates, OSMAnd just uses `try`: this check might fail for some weird reason. In that case SC will never start GPS, which should be clear from the GPS indicator in status bar (assuming this still works the same in Android 12)
* See above: SC discards "bad" new locations, which could go wrong in weird cases

**Comment by HerveB29** [comment]
You just hit a point!

In airplane mode, the position given by SC is correct and follows me 
while moving.
If I exit airplane mode, the position will be wrong again  and will not 
follow me while moving.
A strange thing: if i get back to airplane mode, i won't get a correct 
position anymore, unless I restart my phone.

Le 14/12/2022 à 19:21, Helium314 a écrit :

**Comment by Helium314** [comment]
Good, that's a start!
So the time check may indeed be causing issues. Either the network location or the GPS location must have a wrong date.

Could you check whether GPS reports the correct time? You can do this by installing SatStat from F-Droid and check the time under "last fix obtained". Ideally it should show the correct date and the same time as your system clock.

**Comment by Sonickyle27** [comment]
Heya, I am seeing this issue on a Samsung Galaxy S9+ running LineageOS 17.1. The GNSS time on my phone has rolled over to 2003, and it is causing havoc with my location in StreetComplete. Apps like GPSTest and OsmAnd~ give my location fairly accurately within a few metres.
I haven't tried the Airplane Mode toggling get, but several months ago StreetComplete was reporting my location correctly, so I'm not sure what has happened since then to cause this issue.

**Comment by Helium314** [comment]
I had the same issue a few years ago on my S4 Mini. Sad to see there are no fixes by Samsung or LineageOS, especially because it's quite simple to do...

Airplane mode toggle should help in you case, but actually this should be fixed in SC.

@westnordost what is the reason for the older / newer checks in `FineLocationManager`?
Can we assume that at least GPS locations have been acquired very recently?

**Comment by westnordost** [comment]
There should be a comment in the code why these checks are done,  no?  It comes from an old post of a google dev on how to handle optimally sourcing location from multiple sensors.

**Comment by mnalis** [comment]
> what is the reason for the older / newer checks in FineLocationManager?

It makes sense to me when it compares GPS vs. network location (for GPS vs GPS, or Network vs. Network it is useless, as newer reading will always be newer or same age, never older)

>Can we assume that at least GPS locations have been acquired very recently?

Hmmm, I don't think so, because you could be under woods or inside and lost GPS signal for some time, but still get current coarse network location updates.

**Comment by Helium314** [comment]
> Hmmm, I don't think so, because you could be under woods or inside and lost GPS signal for some time, but still get current coarse network location updates.

Let me clarify: Can we assume that at least _freshly reported_ GPS locations have been acquired very recently?
(`Location.isBetterThan` is only called when the system reports a new location anyway)

> It makes sense to me when it compares GPS vs. network location (for GPS vs GPS, or Network vs. Network it is useless, as newer reading will always be newer or same age, never older)

In my experience in that case one has to consider that
* there might be a GPS rollover (GPS locations are 1024 weeks newer than reported)
* GPS time might be slightly off (I had a phone where system clock and GPS time were slowly drifting apart, after a few days without restarting the phone every new and correct GPS location was reported as minutes old. Though on another phone of the same model, things were working correctly)

I think time is only relevant if you would for whatever reason get old locations. But as far as I know, for GPS you can only get that if you request "last known location". For Network you might actually get an old location reported as new if WiFi scan throttling kicks in and the network location service doesn't properly deal with throttling.

https://web.archive.org/web/20180424190538/https://developer.android.com/guide/topics/location/strategies.html#BestEstimate (from the`FineLocationManager`) apparently just assumes location time is always correct, which sometimes just isn't true for various reasons.

**Comment by westnordost** [comment]
I think at this point you have concerned yourself with the subject much more than i ever did,  so i'd be happy to merge whatever solution you dem to be the best. Best then also include comments (e.g. as to why the reported time can not always be trusted etc) for documentation.

**Comment by mnalis** [comment]
> Let me clarify: Can we assume that at least freshly reported GPS locations have been acquired very recently?

Probably (although I certainly would not be surprised if different android versions have different quirks there) ... 
But do we currently know that it is indeed GPS location that is freshly reported (and not Network location fresh report) which triggered `isBetterThan` ?

> (Location.isBetterThan is only called when the system reports a new location anyway)

I am not an android developer, so I may be totally wrong here, but I was under impression that `Location.isBetterThan` would be called when _either_ GPS **_or_** Network location changes? If that is true, than it might be possible that for example there are continuous Network location updates but no GPS location updates, so  `isBetterThan` would still be called in that case (but only with updated Network location data)? 

---

Anyway, as westnorost said, you seem to be the expert here, so feel free to improve!

**Comment by Helium314** [comment]
> I was under impression that Location.isBetterThan would be called when either GPS or Network location changes?

Yes, every new location triggers `isBetterThan`.

I think a simple solution could be just assuming any new GPS location has been acquired very recently, and set new GPS location time to `nowAsEpochMilliseconds()` before calling `isBetterThan`.
In this case, time stuff can only break if network location time is completely off as well.

**Comment by Helium314** [comment]
@Sonickyle27 there is a fix in the next release.
Can you report whether GPS location works after next SC version is released? I don't have a device that has such GPS issues.

**Comment by Sonickyle27** [comment]
@Helium314 In version 51.1, yes it is working how I'd expect it to now!
