### ISSUE TITLE
Sidewalk overlay: Discourage setting sidewalk outside of landuse=residential

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4653]
**Use case**
When using the sidewalk overlay the red color of "missing data" for sidewalks nudges me to fix this and add sidewalk information. However outside of villages / cities in the vast majority of cases there is no sidewalk, so **adding `sidewalk=no` everywhere there makes little sense.**

**Proposed Solution**
Therefore I would like the sidewalk overlay to be visually dimmed from the red "missing data" indication to anything different / less prominent. E.g. I can think of having these with no color at all / transparent, so that they would not be visible on the map, but user can still click them to explicitly set a value.

Donwside: in dark mode it will not differ much from the black "no" value. However in most of the cases this anyhow is identical as shown above and it can easily be differenciated from the blue "yes" value.

![sidewalk_overlay](https://user-images.githubusercontent.com/104768113/204110300-63a0da9b-29ea-423b-bd9d-dfd5bed463ec.png)

![sidewalk_overlay_dark](https://user-images.githubusercontent.com/104768113/204110396-39f0a438-a694-497c-bebf-17453796d237.png)

**Comment by davidpnewton** [comment]
Except in those places where there _are_ pavements in those areas. I can think of several miles of rural roads near where I live which have pavements.

Beyond that relying on landuse=residential as the distinction is silly. What about landuse=industrial? What about landuse=retail? Roads running through those areas routinely have pavements as there is significant pedestrian traffic.

Then there's the practical difficulty of a query to get this displayed. An Overpass query relying on landuse=residential areas will be inherently much more complicated than one merely interrogating ways for pavement status. Such an Overpass query will run much more slowly and will thus reduce the performance of the app.

So this is a poor idea with significant holes in its practicality.

**Comment by HolgerJeromin** [comment]
@davidpnewton 
This app does not rely anymore (since 2020-11) on overpass api calls.
All OSM data is fetched, quests are calculated on device from that.

But yes, beside performance this is difficult to detect reliable.

**Comment by mnalis** [comment]
Also see [SC FAQ: "Why does StreetComplete often tag the absence of features?"](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_often_tag_the_absence_of_features?)

**Comment by SLMapper** [comment]
Thank you for your comments. Yes actually the proposal was not well thought through in regards to the data selection as well as formulating this proposal. I am sorry for this and try to do it better with:

### Sidewalk overlay: Do not require to set sidewalk outside of built-up areas

I still think it is a valid request to reduce the visual indication of missing data for sidewalks, **where outside of built-up areas**.
Why do I think this? Because this is one of the guidelines for quests (_not overlays, I know_): [No spam](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md#users)
> A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users

Yes there are areas where there actually are sidewalks in rural areas (and I know some), but the by far majority of rural roads has none. That is the reason why the sidewalk **quest** does not ask for sidewalks on these roads.

With this proposal
- it would still be possible to add sidewalk information (both _yes_ and _no_ values / "the absence of features"), but it will not prominently jump into your eyes as "missing data" like today

So how can we technically achive it? Maybe not by looking for the landuse (in case this would be an issue like you indicated above). Instead we could be using a part of the [roadFilter](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L109) used by the sidewalk quest. Not duplicating the sidewalk quest though, but only determining on which roads to keep the overlay prominent and where to dim it.

**Comment by westnordost** [comment]
Is there any property that is usually or often tagged on rural roads which is a very strong indicator for it being rural, i.e. it would be an absolute exception that this road has a sidewalk?
(E.g. `motorroad=yes` would be such a tag. For these, a missing sidewalk is already not shown as missing.)

**Comment by mnalis** [comment]
> Sidewalk overlay: Do not require to set sidewalk outside of built-up areas

Well it's an overlay, nobody is **_forcing_** you to click on all bright colors you see :smile: 

If tagging sidewalks makes no sense in particular area you're in, I'd suggest to not map it then (even better, turn off that overlay until you are back in the city so it doesn't needlessly distract you in the meantime). They are nicer overlays to use in between cities, like `lit` (or hopefully soon [surface](https://github.com/streetcomplete/StreetComplete/pull/4642)).

> but the by far majority of rural roads has none

Perhaps that is situation in your in your corner of the world, but is it the case worldwide? In others places, they exist more often. Here is [overpass](http://overpass-turbo.eu/s/1ohp) to check some area visually. 

> That is the reason why the sidewalk quest does not ask for sidewalks on these roads.

yes, but as you noted, overlay in not a quest. In fact, one of the _**main uses of overlay for me**_ is exactly to see where _SC logic guessed wrong_ and did not show me the quest and I would've wanted it shown, so I can [override](https://xkcd.com/251/) its decision. 

> but only determining on which roads to keep the overlay prominent and where to dim it.

Well I worry that the solution (if implemented) would more likely be _"either show them as missing, or do not show them at all"_ and **not** _"show it but more dim in case it is likely not important"_.  If it only dims it slightly, however, I'd be OK with that - but that would be probably be too much work for too little change.

**Comment by SLMapper** [comment]
> Well it's an overlay, nobody is **_forcing_** you to click on all bright colors you see 😄

Thank you mnails, that's just my perfectionism I guess - wanting to get everything done. I think I really just need to disable / switch or ignore the overlay in such case.

> that would be probably be too much work for too little change.

Probably, yes. So unless anybody involved still wants this feature I would go ahead and close this issue, ok?
@westnordost?

**Comment by matkoniecz** [comment]
> Is there any property that is usually or often tagged on rural roads which is a very strong indicator for it being rural, i.e. it would be an absolute exception that this road has a sidewalk?

rural maxspeed zone but coverage would be spotty and confusing

> So unless anybody involved still wants this feature I would go ahead and close this issue, ok?

+1
