### ISSUE TITLE
Existing cycleway data not being displayed

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#4654]
On a number of occasions I have received quests for cycling infrastructure asking "Is this still the cycling situation here?" - but the existing data is not shown, for example:

![Screenshot_20221128-204502.png](https://user-images.githubusercontent.com/19356194/204247406-7dbb1d18-95f4-47d5-b182-fa897b488e69.png)

In the above example, I have checked in OSM and there is indeed a tag for cycleway:both = shared_lane on this way.

**How to Reproduce**
- Find this way in SC - https://www.openstreetmap.org/way/27373134
- Have the cycleways quest activated
- Click on the quest

**Expected Behavior**
Existing cycleways should be displayed, for example:

![Screenshot_20221128-205835.png](https://user-images.githubusercontent.com/19356194/204248933-b7f288de-2084-41b9-bc56-14d312a801c5.png)

**Versions affected**
SC v49.2
Android 13 (build number TP1A.221105.002) on Pixel 6

**Comment by frankie2784** [comment]
According to this wiki, the ambiguity exists only in Belgium and the
Netherlands - https://wiki.openstreetmap.org/wiki/Key:cycleway:lane#Values

In Australia, cycleway:* = shared_lane is enough to understand the
situation in virtually all cases, so such ways are rarely tagged with an
additional :lane attribute.

Is there a way to contain the "ambiguous" interpretation to just those
countries named above, and display shared_lane as expected elsewhere?

**Comment by westnordost** [comment]
Why, do such "advisory" cycle lanes exist in Australia?

**Comment by frankie2784** [comment]
> Why, do such "advisory" cycle lanes exist in Australia?

I can't tell you _why_ they exist in all cases, all I can say is that they do. But we generally wouldn't class them as a "shared lane" in the sense that cars and bikes inherently share the same lane, rather it is a bike lane with dashed lines that a car has permission to veer into.

**Comment by westnordost** [comment]
And they regularly (must) do this? Or is the cycle lane only dashed where cars must be able to cross, for example at intersections or in front of driveways and street parking?

**Comment by frankie2784** [comment]
> And they regularly (must) do this? Or is the cycle lane only dashed where cars must be able to cross, for example at intersections or in front of driveways and street parking

I wouldn't say cars "must" cross into the lane. And no, I'm not talking about those more transitional lanes across driveways or at intersections. They are not the most common type of bike lane, but they do exist. I'll try and find some examples.

**Comment by westnordost** [comment]
Here for example they must: https://commons.wikimedia.org/wiki/File:Bygdev%C3%A4g.jpg

Known as a 2-1 road.

**Comment by frankie2784** [comment]
Here is an example: https://twitter.com/melbourneway/status/1462518473813233669

It may look like it's dashed because it's adjacent to parking, but most bike lanes adjacent to parking here are actually solid lines. It's not immediately obvious to me why these have been made as dashed lanes, perhaps something to do with road width. Nevertheless, as this tweet highlights, we'd call this an advisory lane, not a shared lane.

**Comment by westnordost** [comment]
Hmm, this is highly interesting. It would be very helpful to get my hands on the law text that regulates this kind of cycle lane. (E.g. is there a minimum width? Must there be a buffer between this and parking cars? What are the restrictions on motor vehicle access?)

A short look into http://www7.austlii.edu.au/cgi-bin/viewdb/au/legis/vic/num_reg/rsrr2017n41o2017289/ didn't result in anything.

It is a similar concept as the 2-1 lane, yet, I guess the distinction that must be made is whether the cycleway in this road is a "proper" cycle lane with the restrictions that come with it or if this is some kind of watered down cycle lane, because it is the latter for which this "advisory cycle lane" tag exists for.

**Comment by westnordost** [comment]
So anyway, regarding the original request, I'd rather keep it that way. Even if "suggestion lanes" do not exist elsewhere, I find it more precise if sharrows are tagged with the "pictogram" subtag if that is what the user selects.

**Comment by frankie2784** [comment]
> So anyway, regarding the original request, I'd rather keep it that way. Even if "suggestion lanes" do not exist elsewhere, I find it more precise if sharrows are tagged with the "pictogram" subtag if that is what the user selects.

I don't mind this so much, but in that case it probably shouldn't ask "is this still the situation here?" since it's not showing anything meaningful anyway. Perhaps it's better to just ask "what is the situation here?" if the current tags are ambiguous and you can't graphically represent them? The potential risk, I guess, is that the cycleway tags for a particular street may be accurate (although complex), but will be overwritten by more simplified (and potentially less accurate) tags if input via SC. Of course, it could go the other way too.

**Comment by frankie2784** [comment]
> Hmm, this is highly interesting. It would be very helpful to get my hands on the law text that regulates this kind of cycle lane. (E.g. is there a minimum width? Must there be a buffer between this and parking cars? What are the restrictions on motor vehicle access?)

Yea I'm not sure about specific regulations, bike lanes are typically managed at the local council level, and I think there is probably not a lot of hard regulation around their attributes - although there is obviously best practice.

Like I said, these kinds of lanes are the exception, not the norm - so maybe not something to worry too much about for the purposes of SC.

**Comment by westnordost** [comment]
Okay, if this is just a pilot project or something, then I will not include it. I.e. "advisory cycle lane" will continue to not be selectable in SC.

**Comment by frankie2784** [comment]
> I don't mind this so much, but in that case it probably shouldn't ask "is this still the situation here?" since it's not showing anything meaningful anyway. Perhaps it's better to just ask "what is the situation here?" if the current tags are ambiguous and you can't graphically represent them? The potential risk, I guess, is that the cycleway tags for a particular street may be accurate (although complex), but will be overwritten by more simplified (and potentially less accurate) tags if input via SC. Of course, it could go the other way too.

Just flagging my previous comment on the original issue in case you missed it

**Comment by westnordost** [comment]
I didn't miss it, it is not possible to do this technically.

**Comment by frankie2784** [comment]
> > Just flagging my previous comment on the original issue in case you missed it
> 
> FWIW that part is a duplicate of #3129 and #3291 and #2120 .

Thank you, this is helpful context - was not clear from the comments here why this is not easily resolvable

**Comment by frankie2784** [comment]
Just as an FYI - here is another example of an "advisory" lane on a main road in Melbourne. The road is perfectly wide enough to accommodate 4 lanes of traffic and two bike lanes. But the bike lanes are still dashed, meaning cars are "allowed" to travel in them. It is frankly bizarre.![PXL_20221209_202134958.jpg](https://user-images.githubusercontent.com/19356194/206790746-2d4539ef-5218-4f07-a474-d7ca6fb33494.jpg)

**Comment by westnordost** [comment]
Well, I guess for now you should tag them manually in iD or something, but if this kind of cycleway really becomes more common or official (in legislation), we can include it

**Comment by frankie2784** [comment]
Yep, that's what I've been doing when I come across something like this.

Also, this from the "Cycling Aspects of Austroads Guides" - Austroads being the primary transport standards body in Australia. Looks like advisory lanes have no regulatory function, but are still used to indicate the presence of cyclists and where they are expected to ride on the road. The specific treatment is left to the local council.

![Screenshot_20221210-081417.png](https://user-images.githubusercontent.com/19356194/206797285-7e3fcd56-6388-47b2-ae93-1942252228ee.png)

I guess the issue then goes back to that question of whether OSM tags should ideally reflect legislation, purely physical attributes or commonly understood usage. In this case, advisory lanes don't appear to be specifically legislated, yet they still have a physical presence and a generally agreed-upon meaning (and real-world implications) for cyclists and drivers on the ground.

It's an interesting one.

**Comment by westnordost** [comment]
Actually, this looks like a case where this could be included. Care to create a PR in this repo, adding Australia to these files and give the source of the information you linked?:

https://github.com/streetcomplete/countrymetadata/blob/master/data/hasAdvisoryCycleLane.yml
https://github.com/streetcomplete/countrymetadata/blob/master/data/advisoryCycleLaneStyle.yml

**Comment by frankie2784** [comment]
Done. Apologies, did this in GitHub UI and ended up generating a separate PR for each file.

**Comment by riQQ** [comment]
For reference:
https://github.com/streetcomplete/countrymetadata/pull/15
https://github.com/streetcomplete/countrymetadata/pull/16
