### ISSUE TITLE
Using maxheight on type:building relations results in all elements being rendered with that maxheight.

### ISSUE THREAD

**Issue by sekerob** [streetcomplete/StreetComplete#4659]
Since longer I've been using the maximum height=0 on type=building relations in order to get the building:part elements to each render in their own heights in StreetComplete, the only place I know to see buildings in 3D rendition. It works perfectly, but, in a discussion at https://www.openstreetmap.org/changeset/129527815 it was pointed out that the height tag on building relations 'should' be ignored by those who draw OSM data to render buildings in 3D and is supposed to carry the height of the very highest point of the building.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/streetcomplete-mapstyle/issues/121

See https://github.com/streetcomplete/StreetComplete/issues/2205 especially https://github.com/streetcomplete/StreetComplete/issues/2205#issuecomment-749139738

> So anyway, I think it makes no sense to leave this issue open. There is nothing that can be done about that in this project. The map tile provider (Jawg) is informed about this problem, maybe they will do something about it, maybe they won't.

**Comment by matkoniecz** [comment]
pinging @Joxit - what was outcome of https://github.com/streetcomplete/StreetComplete/issues/2205#issuecomment-719995625 ?

(pinging again because two years passed, let me know if I should ping less)
