### ISSUE TITLE
Nachfrage nach Anzahl der Dachgeschosse 

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#4661]
In der letzten Zeit hatte ich mehrmals den Fall, dass ich einen Gebäudetyp eingegeben habe und SC dann sofort nach dem Dachtyp fragte.
Nachforschungen ergaben, dass bei diesen Gebäuden bereits ein building:level gesetzt war, jedoch ein roof:level fehlte.
SC sollte in solchen Fällen nach der Anzahl der Dachgeschosse fragen.

**Comment by westnordost** [comment]
Das ist nicht korrekt. Die Aufgabe erscheint nur, wenn bisher kein `building:levels` gesetzt ist.

`building:level` ist kein gültiger Schlüssel, ich nehme an dass Du dich verschieben hast?

**Comment by Helium314** [comment]
`AddRoofShape` doesn't need `building:levels` any more, see #4261 / https://github.com/streetcomplete/StreetComplete/commit/448d05a0ea0fd00f42f5d9efb7f0f779016f09ca

**Comment by westnordost** [comment]
Ups, falsch gelesen.

Also es geht darum dass Dachform erfragt wird, obwohl Anzahl der Dachgeschosse nicht gesetzt ist?

**Comment by legofahrrad** [comment]
Es geht darum, dass StreetComplete auch bei fehlendem `roof:levels` aber vorhandenem `building:levels` nach den Geschossen fragt, um die Dachgeschosse zu ergänzen. Ich halte das ganze für gewisse Dachformen sinnvoll, für andere nicht. Bei einem Flachdach ist zum Beispiel klar, dass es keine Dachgeschosse geben kann. Bei einem Haus mit Satteldach, das building:levels aber kein roof:levels hat, ist nicht klar, wie viele Dachgeschosse es gibt. Dort sollte gefragt werden.

**Comment by biketeur** [comment]
YepAm 01.12.2022 19:34 schrieb Tobias Zwick ***@***.***>:
Ups, falsch gelesen.
Also es geht darum dass Dachform erfragt wird, obwohl Anzahl der Dachgeschosse nicht gesetzt ist?

**Comment by biketeur** [comment]
Ein Flachdach erkenne ich doch daran, dass roof:levels=0 gesetzt ist, oder sehe ich dass falsch?Am 01.12.2022 19:37 schrieb legofahrrad ***@***.***>:

Es geht darum, dass StreetComplete auch bei fehlendem roof:levels aber vorhandenem building:levels nach den Geschossen fragt, um die Dachgeschosse zu ergänzen. Ich halte das ganze für gewisse Dachformen sinnvoll, für andere nicht. Bei einem Flachdach ist zum Beispiel klar, dass es keine Dachgeschosse geben kann. Bei einem Haus mit Satteldach, das building:levels aber kein roof:levels hat, ist nicht klar, wie viele Dachgeschosse es gibt. Dort sollte gefragt werden.

**Comment by legofahrrad** [comment]
Ein Flachdach ist `roof:shape=flat` und impliziert damit `roof:levels=no`

**Comment by westnordost** [comment]
Jein. Es gibt auch Gebäude mit Flachdach bei dem das oberste Stockwerk kein ordentliches  Geschoss ist.

**Comment by westnordost** [comment]
Also, um nochmal zusammenzufassen:

1. Dass die Dachform auch für **bestimmte Gebäudetypen** schon gefragt wird auch wenn kein `roof:levels` gesetzt ist, ist so gewollt, siehe https://github.com/streetcomplete/StreetComplete/issues/4661#issuecomment-1334151536

2. Dass die `roof:levels` zu setzen optional ist (es wird bei Auslassen des Feldes einfach nichts getaggt) war schon von Anfang an so. Die Überlegung dahinter war, dass insbesondere in Ländern in denen Dachformen nicht üblich sind (also ausschließlich Flachdächer), es sehr spammig wäre, von Nutzern zu erwarten dass sie trotzdem überall "0" eingeben müssen.
  Dies führt natürlich dazu, dass wenn jemand vorher nur `building:levels` eingegeben hat, es per StreetComplete keine Möglichkeit mehr gibt, diese `roof:levels` nachzutragen. Was schade ist.

Mögliche Lösungen wären:
1. Ab jetzt immer auch die Eingabe von `roof:levels` verlangen. Da man meistens eh die favourite-buttons benutzt, sollte es für den Nutzer kaum einen Unterschied machen
2. Ein neuer Aufgabentyp: "Wie viele Stockwerke hat das Dach hier?" o.Ä.. Wird gefragt wenn Dachform gesetzt ist, aber kein `roof:levels` 

Lösung 1 wäre natürlich quasi kein Aufwand. Aber, nur 9.56% aller Gebäude die mit `building:levels` getaggt sind, sind auch mit `roof:levels` getaggt.

**Comment by Discostu36** [comment]
Ich denke, Lösung 2 ist die bessere, aber sie sollte vermutlich standardmäßig deaktiviert sein. Zumindest wo ich wohne, ist es von außen immer schwer zu beurteilen, ob ein Dach ein oder zwei Geschosse hat.

**Comment by westnordost** [comment]
Der Aufgabentyp ist doch standardmäßig deaktiviert.

**Comment by legofahrrad** [comment]
Es geht um den neuen Quest nur für Dachgeschosse.

**Comment by matkoniecz** [comment]
So, in conclusion: new, disabled by default quest asking only about `roof:levels` (or reasking about `building:levels` and `roof:levels` when `roof:levels` is unset?) could be added.

Maybe close this issue and open new one describing this conclusion, in English? And mark it as awaiting PR from potential interested people?

**Comment by matkoniecz** [comment]
But if such quest is considered as useful - then maybe StreetComplete should first add `roof:levels=0` when adding `building:levels` in building level quest?

**Comment by westnordost** [comment]
> So, in conclusion: new, disabled by default quest asking only about roof:levels (or reasking about building:levels and roof:levels when roof:levels is unset?) could be added.

> Maybe close this issue and open new one describing this conclusion, in English? And mark it as awaiting PR from potential interested people?

Yes, that would be good. Would you do this? This ticket has become a bit long, so I had to read all again to see what was the conclusion.

On your second comment: Nah, I see no reason to do that.

**Comment by matkoniecz** [comment]
> On your second comment: Nah, I see no reason to do that.

So StretComplete user would fill building level quest, leave roof level count empty as it has none and then immediately would be asked again about level count in roof?

Either explicit 0 is useful or it is not.

**Comment by westnordost** [comment]
Hm... it would only be asked again if the user supplied a non flat roof shape though, right?

**Comment by matkoniecz** [comment]
Yes, but still we would need to show the same quest - as otherwise someone could add correct roof level count and leave wrong non-roof level count present already.

**Comment by westnordost** [comment]
Why should the non-roof level count be wrong?

**Comment by matkoniecz** [comment]
This quest makes sense to ask only when some noticeable roof level count values is wrong.

If roof level count value is wrong, then non-roof building level count is also likely wrong.

Especially if someone counted roof-level as normal level.

**Comment by westnordost** [comment]
> This quest makes sense to ask only when some noticeable roof level count values is wrong.

Not really. There are plenty of buildings with no (full) roof levels that still have a non-flat roof shape.

**Comment by westnordost** [comment]
But anyway... I guess it would be alright if a "0" for the roof levels was pre-filled in the building levels quest and when tabbing into it / tapping on it, the whole text is selected so one can easily replace the value and make the roof levels a mandatory field. What should not happen is that the "0" is automatically added if not supplied.

**Comment by matkoniecz** [comment]
> Not really. There are plenty of buildings with no (full) roof levels that still have a non-flat roof shape.

Then what is proposed here? Is my

> So, in conclusion: new, disabled by default quest asking only about `roof:levels` (or reasking about `building:levels` and `roof:levels` when `roof:levels` is unset?) could be added.

a misinterpretation?

**Comment by matkoniecz** [comment]
> ... uhm, on the other hand, it is practically impossible to see from the ground whether a high-rise building (e.g. 9 floors and up) has no roof levels or has e.g. 1 roof level. So, forcing users to supply the number of roof levels may very well lead to wrong data rather than just not-filled-in data.

That is one of reasons why I proposed building level quest to be disabled by default

**Comment by westnordost** [comment]
Ok maybe this:

Make `roof:levels` into a mandatory field in the building levels quest and re-ask building level quest for buildings that do have a `roof:shape` that is not `flat` but no`roof:levels` set. But:
- on new entry, prefill the roof levels field with "0". When tabbing into it / tapping on it, the whole text is selected so it can easily be replaced
- make the `roof:levels` field only mandatory (and prefill with 0 etc) in country where the roof shape is not usually flat (https://github.com/streetcomplete/countrymetadata/blob/master/data/roofsAreUsuallyFlat.yml)
