### ISSUE TITLE
What kind of markings does this crossing have?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#4663]
### General
Affected tag(s) to be modified/added: [crossing:markings](https://wiki.openstreetmap.org/wiki/Key:crossing:markings)
Question asked: **What kind of markings does this crossing have?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
The tag has almost 25k uses as of 2022-12-02 and it's use is literally skyrocketing
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
In places with a lot of crossings, it may be overwhelming.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Nodes with `highway=crossing` and nodes with `highway=crossing + crossing:markings=yes`

**Metadata needed:** 
Not all countries have the same kind of crossing markings. For example I haven't seen ladder crossings in Europe. I wasn't able to find any structured data about it in Wikipedia. We will have to enable it per country as data is being added.

For all possible answers of this quest see https://wiki.openstreetmap.org/wiki/Key%3Acrossing%3Amarkings#Examples
We can exclude `yes` and `no`
**Proposed UI:**
Same as the kerb height quest.

**Comment by matkoniecz** [comment]
> and has a useful purpose

is there a potential use for this data except for 3D rendering?

**Comment by Dimitar5555** [comment]
Depending on the local legislation, there may be implied restrictions. For example on zebra crossings and on crossings controlled by traffic signals cyclists must dismount their bike while crossing. On "bicycle crossing paths" they are allowed to ride their bikes even if the crossing is controlled by traffic signals.

**Comment by westnordost** [comment]
You mention that depending on local legislation, the marking style may lead to different implied restrictions. As long as there is no documentation in the wiki on which markings imply which restrictions per legislation, the tag has no useful purpose other than for rendering.

For countries in which there is only one (legal) crossing road marking, the quest should not be shown at all. For others, only those road markings which actually exist should be selectable. As long as this information is not documented comprehensively in the wiki (or something), this cannot be implemented as a quest.

A new issue or this issue can be reopened if such documentation has been done.
