### ISSUE TITLE
Fehlende Abfragen 

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#4667]
Es geht um die Häuser 6, 12 und 15 in diesem Gebiet:

![Screenshot_2022-12-06-05-28-27-453_de westnordost streetcomplete](https://user-images.githubusercontent.com/80254292/205815584-1e40a8a4-0f94-4439-bfc4-e8f9419c4476.jpg)

Diese Häuser haben den Schlüssel building=yes, keine Schlüssel für building:level, roof:level und roof:shape.
Trotzdem bietet SC keine Anfragen an.
Scheint an den Schlüsseln bzgl. Photo-Voltaik zu liegen:

![Screenshot_2022-12-06-05-29-22-495_de blau android](https://user-images.githubusercontent.com/80254292/205817576-92447a15-2a54-465e-9a47-219dcf19277c.jpg)

**Comment by matkoniecz** [comment]
Is it even a correct mapping to map them as one object?

**Comment by biketeur** [comment]
Bei diesen Objekten handelt es sich um Einfamilienhäuser mit Photovoltaik auf dem Dach.
Sieht man auch auf Satellitenbild, z.b. Luftbilder von Metropole Ruhr.

**Comment by biketeur** [comment]
Ich habe mal mit Turbopass nach Fotovoltaik-Anlagen gesucht, sehr viele gefunden, und alle waren - wie mcliquid beschrieben hat - als separate nodes getaggt.Meine genannten Häuser sind also falsch getaggt. Trotzdem verstehe ich nicht, warum SC bei einem Objekt mit building=yes keine Abfragen kommen oder zumindest ein Hinweis, dass hier etwas nicht stimmt mit den vorhandenen tags.Mit welcher SW kann ich mit wenig Aufwand Haus und Photovoltaik-Anlage trennen?Am 06.12.2022 17:50 schrieb mcliquid ***@***.***>:



Bei diesen Objekten handelt es sich um Einfamilienhäuser mit Photovoltaik auf dem Dach. Sieht man auch auf Satellitenbild, z.b. Luftbilder von Metropole Ruhr.



Ja da ist klar, aber dann sollte die PV Anlage dennoch als separate Fläche kartiert werden und nicht im Haus. In der Regel füllen die Solarpanels auch nicht die gesamte Dachfläche sondern haben einen kleinen Abstand rundherum. Deshalb: Ein Feature, ein Element in OSM. Das Haus ist eines, die PV-Anlage ein anderes Element.

**Comment by biketeur** [comment]
Noch ein kleiner Nachtrag:
EveryDoor stört sich nicht an dem falschen tagging, hier kann ich Gebäudetyp, ... eingeben.

**Comment by matkoniecz** [comment]
In general, with incorrectly mapped data there should be no expectation of valid and thorough support.

Even data considered as correctly mapped can be ridiculously hard or impossible to support. 

And adding intricacies how to support invalid data is not viable, especially if problem is "quest selection skips valid targets" not "StreetComplete mangles data"

Again: once data is badly mapped then StreetComplete can misbehave, ask impossible to answer questions. If questions are nonsense or impossible to answer: leave note. If questions are not asked: well, at least edits will not break stuff. In this case adding special cases would end with horrifyingly complex condition, just to support some badly mapped features.

See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L11

> in the case of man_made, historic, military, aeroway and power, these tags already contain
> information about the purpose of the building, so no need to force asking it
> or question would be confusing as there is no matching reply in available answers
> same goes (more or less) for tourism, amenity, leisure. See #1854, #1891, #3233

**Comment by biketeur** [comment]
Danke, Holger!Werde ich im Laufe der Woche ausprobieren.Am 06.12.2022 21:42 schrieb Holger Jeromin ***@***.***>:

Mit welcher SW kann ich mit wenig Aufwand Haus und Photovoltaik-Anlage trennen?

ID Editor:
Create node (or area if visible) for the solar thing.
Select building, change "edit tag at the end" to text. Select the solar tags in the text input. Cut the text.
Select new node, paste solar tags.
