### ISSUE TITLE
Bicycle overlay creates multiple version of a way with same tagging

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4668]
**How to Reproduce**
Please see the version 9 to 12 of https://www.openstreetmap.org/way/326520704/history

Select the way in the Bicycle overlay and add, that on the left side there is no cycleway. Hit ok. The view of the overlay does not change and the left side of that way is still marked red. So you are encouraged to do that tagging multiple times. 

**Expected Behavior**
Mark left side of that way black and e.g. tag that there's no cycleway.

**Versions affected**
v50.0-beta1

**Comment by rhhsm** [comment]
May be related to #4258 ?
