### ISSUE TITLE
Can't confirm that road is a bicycle road [Cycleway Overlay]

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4671]
**How to Reproduce**
1. Choose any road in the cycleway overlay
    * doesn't matter if cycleway info is set or missing
2. tap "..."
3. "it is a bicycle road"
4. see that the confirm button isn't shown / grey and not clickable

**Screenshots**
![Screenshot 2022-12-06 194708](https://user-images.githubusercontent.com/92865620/205997572-ec8968f4-9ac0-43e9-bc37-7e974fbfe9cd.png)
see that there is no confirm button

**Expected Behavior**
the confirm button should be shown and when tapping it `bicycle_road=yes` should be added

**Versions affected**
v50.0-beta1

**Comment by legofahrrad** [comment]
Can this issue be reopened again? When selecting a way with the red highlighting and tapping then on the "it's a bicycle boulevard", the confirmation button won't show up.
v50.1

**Comment by westnordost** [comment]
Can reproduce. Reproducable only if the cycleway has been indicated as missing before.
