### ISSUE TITLE
way symbols cut off in Cycleway Overlay

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4672]
**How to Reproduce**
tap any paths in cycleway overlay,
compare e. g. footpaths and designated cycleways
![Screenshot 2022-12-06 at 19-45-56 Foto - Google Fotos](https://user-images.githubusercontent.com/92865620/205998386-8b6dd6d7-283d-4c18-aa74-809e95712c43.png)
cut off ↑
<br>
![Screenshot 2022-12-06 at 19-45-20 Foto - Google Fotos](https://user-images.githubusercontent.com/92865620/205998399-912a2e63-1047-494a-8e05-395cfe4f2a68.png)

**Expected Behavior**
icons shouldn't be cut off but text in multiple lines to have space for the icons

**Versions affected**
v50.0-beta1

**Comment by westnordost** [comment]
Yeah, I know. I fiddled around a bit with the layout, but wasn't able to either provide a workaround or find out what the issue was, i.e. why it displays like that in the first place. So, this is a will-not-fix (can not fix) from me.

**Comment by westnordost** [comment]
The layout shown is https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/layout/fragment_overlay_image_select.xml in case someone else wants to have a look.
