### ISSUE TITLE
explicit key=unknown excludes the object from the quest

### ISSUE THREAD

**Issue by dieterdreist** [streetcomplete/StreetComplete#4679]
**Use case**

**Proposed Solution**

as reported on the forum, 
https://community.openstreetmap.org/t/unknown-clean-up-in-piemonte/6563

existing bench=unknown tags lead to streetcomplete not asking questions about benches, ideally these would be treated like a missing tag.

**Comment by matkoniecz** [comment]
In this case this tag is unwanted and should not be added in the first place. I would recommend discussing it with local community and removing it - likely automated edits would be useful.

See https://github.com/streetcomplete/StreetComplete/issues/4667#issuecomment-1339852558

In general, with incorrectly mapped data there should be no expectation of valid and thorough support.

Even data considered as correctly mapped can be ridiculously hard or impossible to support.

And adding intricacies how to support invalid data is not viable, especially if problem is "quest selection skips valid targets" not "StreetComplete mangles data"

**Comment by dieterdreist** [comment]
while the unknown value for the bench key is really limited, the value is also found on access tags and others https://taginfo.openstreetmap.org/search?q=unknown#values
excluding them from the quests is not what you want. (providing special treatment on the other hand could encourage people to add it, what might not be ideal either)
