### ISSUE TITLE
Cannot set tag if note is attached to element

### ISSUE THREAD

**Issue by aikencz** [streetcomplete/StreetComplete#4680]
I cannot set a tag if an unresolved note has been previously attached to the element. It occurs for street sidewalks for example. The note pops up again and again although I choose to not add a comment (or if I add a comment).

**How to Reproduce**
1. Switch the "Sidewalks" overlay on.
2. Tap on a street and select adding a note instead of setting sidewalk tags.
3. Write a note.
4. Reload quests.
5. Tap on the same street.

**Expected Behavior**
The sidewalk dialog displays and I can set the sidewalk tags.

**Actual Behavior**
The attached note is shown. If a choose not to add a comment or I add a comment it still does not allow to set the tags.

**Versions affected**
Android 11
StreetComplete 49.2

**Example**
Here you can see a street that has sidewalks incorrectly set. There is my own note added in an older version of StreetComplete (without the sidewalk overlay feature). I would like to set correct sidewalk tags thus I tap on the street.

![Screenshot_20221211-164446_StreetComplete](https://user-images.githubusercontent.com/3749240/206913585-211cc964-5c3f-4116-9f82-eee07e47ad0d.jpg)

But it displays the attached note instead of displaying the sidewalk dialog. I can dismiss it or add a comment but nothing changes.

![Screenshot_20221211-164549_StreetComplete](https://user-images.githubusercontent.com/3749240/206913587-043f399b-0d85-4307-a689-24f1ec2bc787.jpg)

**Comment by Helium314** [comment]
see #4529:
> Well that's how the notes work. They block **all** quests until they are solved, because **something** is amiss that must be solved first (outside of the app). And hence, also all editing with overlays.

**Comment by mnalis** [comment]
FYI, the workaround is to open another editor (like [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd), [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) or [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci)) and **close** the note manually (and upload changes), and then use `menu` / `Scan for quests here` to update the StreetComplete.

**Comment by aikencz** [comment]
@mnalis Thanks for your suggestion.

**Comment by matkoniecz** [comment]
Obviously note should be closed only after solving it or if it was closeable for other reason.
