### ISSUE TITLE
English phrase seems a bit odd to me

### ISSUE THREAD

**Issue by ricloy** [streetcomplete/StreetComplete#4682]
Hi!
While I was translating to Italian on POEditor, I found [this](https://github.com/streetcomplete/StreetComplete/blob/56bd7b921e6c02dbc3fb44e932d6fe4f460f336f/app/src/main/res/values-en/strings.xml#L1596) phrase that seems a bit odd to me:
<img src="https://user-images.githubusercontent.com/6280373/207286237-302c77e9-8edd-4071-964f-87f580283a9e.png" width="400"/>

> **That** a cycleway goes into the other direction is extremely rare.

I think it should be corrected to:

> A cycleway **that** goes into the other direction is extremely rare.

Cheers,
Marco.

**Comment by westnordost** [comment]
Right, actually it should be "bike path", too, because the default English strings are American-English.

**Comment by westnordost** [comment]
So by the way,  where did you encounter such a cycleway? Or did the warning serve its purpose and it was a misclick?

**Comment by ricloy** [comment]
Oh, I found it by trying to reverse a random way on the "bike paths" overlay (StreetComplete v.50.0  from Google Play) but I didn't commit any change to OSM. I was just trying to understand where the phrase was actually used within the app.
