### ISSUE TITLE
Button for changing overlays on mainscreen 

### ISSUE THREAD

**Issue by Katzenstreu** [streetcomplete/StreetComplete#4686]
Hey,

I'm using the overlay quests a lot. But I can't recognise fast which kind of overlay is active without switching in the overlay drop down list.

First 
I wish an symbol, an indicator, which overlay is active.

Second
I suggest an easy method to change some own predefind overlay quests. I think most people are using some overlay quest types rarely far. Maybe we could activate some own defined overlay quests via checkbox. If we are outside it would be nice to change the most common own defined overlays fast with one click on the main screen. I've painted a mockup.

![Screenshot_20221215_081633_StreetComplete](https://user-images.githubusercontent.com/1107883/207801982-424a171d-41c2-4dcf-b088-f1c1bd632a23.jpg)

A long click would start the known dialog to activate and change the kind of overlay. But a short click would activate the next own predifined overlay.

In my case I would activate Straßenbeleuchtung, Bürgersteige, Parkstreifen and Fahrradwege because this are kind of quests. 

Best regards
Tim

**Comment by westnordost** [comment]
A quick-switcher for overlays is currently not planned. (Sorry, I am very opinionated when it comes down to the number of buttons (permanently) visible on the main map view.)

**Comment by mnalis** [comment]
(related rejected request for quick-switch of presets in https://github.com/streetcomplete/StreetComplete/issues/3827#issuecomment-1058071697.) 

Note that quick switch of overlays is much more important that of presets, as it happens all the time for many mappers. I.e. as a bicycle-mapping-oriented person, I would like to use `sidewalks overlay`, `bike paths overlay`, `surface overlay` and `street lighting overlay`. Unfortunately, I can only choose one, as switching between them by 4-clicks-action is way too annoying and time consuming (and I'd be switching them at least every 100 meters or so!).

I'd love 1-click "mode switch" as it exists in EveryDoor (its even 0-click sometimes - e.g. I can add amenity while in micromapping mode too!) . Even 2-clicks might be workable solution. But 4-clicks is way too much, so I end up using overlays very rarely. :cry: 

Another alternative would be to allow **some screen gesture**  for switching. That would avoid evil always-visible button (but that is likely more problematic to implement, and less discoverable)
