### ISSUE TITLE
NSI not adding names

### ISSUE THREAD

**Issue by Mannivu** [streetcomplete/StreetComplete#4688]
Today I added a shop and i searched for the brand name, i clicked on the correct brand and SC added the POI. However, I noticed that the name of the shop was not added ([this is the POI](https://www.openstreetmap.org/node/10267676636)) even if the entry in the NSI should automatically enter the name (see [the entry](https://nsi.guide/index.html?t=brands&k=shop&v=perfumery&tt=marionnaud#marionnaud-d22512)).

**How to Reproduce**
Add a shop and look for "Marionnaud": the app adds a POI without adding the name.

**Expected Behavior**
The POI should be added with the name

**Versions affected**
Android 12 SP1A.218012.016 (MIUI Global 13.0.1 Stable on XIAOMI 2201116TG); StreetComplete v 50.0

**Comment by Helium314** [comment]
The issues is in the shop overlay, not NSI or the feature dictionary (name is added correctly when you change a shop via _does not exist_ answer)

**Comment by matkoniecz** [comment]
Confirmed, and situation changed - I still need to verify whether it got recently broken (and test version that I have is old enough to be working) or is it something that got fixed and my test version is new enough to be without this issue.

**Comment by Helium314** [comment]
Name should be set correctly in
https://github.com/streetcomplete/StreetComplete/blob/259c32bb394b0b1ef16dbfb24219ae3715dd3509/app/src/main/java/de/westnordost/streetcomplete/overlays/shops/ShopsOverlayForm.kt#L287
so I guess the issue might be the [empty](https://github.com/streetcomplete/StreetComplete/blob/259c32bb394b0b1ef16dbfb24219ae3715dd3509/app/src/main/java/de/westnordost/streetcomplete/overlays/shops/ShopsOverlayForm.kt#L164) `newNames` list being applied in
https://github.com/streetcomplete/StreetComplete/blob/259c32bb394b0b1ef16dbfb24219ae3715dd3509/app/src/main/java/de/westnordost/streetcomplete/overlays/shops/ShopsOverlayForm.kt#L297

**Comment by matkoniecz** [comment]
Seems to be problem since 1cc3c96aa24e6a8fd7ae4d82f4797c127966f430
