### ISSUE TITLE
Multipolygon POIs not rendered correctly

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4689]
**How to Reproduce**
click on the opening hours quest of https://www.openstreetmap.org/node/9230317945 and see that https://www.openstreetmap.org/relation/5462872 is also highlighted in purple as expected. But it looks weird because it's a multipolygon. See Screenshot below.

![grafik](https://user-images.githubusercontent.com/92865620/208166815-a2f5e9b6-28ea-4083-aea2-dd4e3cfee9e5.png)

**Expected Behavior**
Multipolygons should be coloured inside of `outer` ways only.

**Versions affected**
v50.0

**Comment by westnordost** [comment]
The issue was that the second polygon was incorrectly interpreted as an inner ring of the first polygon.

**Comment by legofahrrad** [comment]
Using v50.1 and the issue isn't fixed yet. Looking at the example from the Hackerspace Bremen, it is still displayed as in the screenshot from the first comment.

**Comment by westnordost** [comment]
I explicitly tested it with the Hackerspace. So maybe the remaining issue is

**Comment by legofahrrad** [comment]
I'm on a Pixel 5 with Android 13

**Comment by westnordost** [comment]
Oh, I get it. Could it be that it is reproducible if you select an object **near** the hackerspace but it looks fiine if you select the hackerspace itself?

**Comment by legofahrrad** [comment]
yes, when using the shop overlay (because the hackerspace has no quest on it) and selecting the hackerspace, it works all fine. The **orange** highlighting is correct displayed.
When selecting a POI nearby (e. g. the "Bremer Textildruck" Fabric Store) the **pink** highlighting is displayed wrong.
