### ISSUE TITLE
Bus stops quests should check stop_area relations for existing data on linked objects

### ISSUE THREAD

**Issue by bxl-forever** [streetcomplete/StreetComplete#4690]
Commit [424f2d081cc0fce453a7ddaa2b40afbe72d56d93](https://github.com/streetcomplete/StreetComplete/commit/424f2d081cc0fce453a7ddaa2b40afbe72d56d93) extended bus stop quests to ways.

Here is a typical situation in cities where public transport is mapped quite accurately: a bus stop is mapped as a node, most tags (bench, bin, lit, shelter) are propely set on the node.  Near it, the bus platform is drawn as a way.  Both objects are linked through a stop_area relation (type=public_transport + public_transport=stop_area).

StreetComplete will ask users to fill data for the way, despite all the information already resides on the node.  Should the information be missing on the node, SC will ask the users for the same data twice, one for each object.  This creates useless data duplication and we might also end up with contradictory information.

Suggested fix: check if the bus stop (way|node) belongs to a stop area relation, then queries the other object in it, and only show the quest is the tags are missing on both.

**Comment by matkoniecz** [comment]
> bus stop is mapped as a node, most tags (bench, bin, lit, shelter) are propely set on the node. Near it, the bus platform is drawn as a way.

That seems to violate https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element - this two objects should not be mapped separately - it seems that they both represent the same thing

**Comment by bxl-forever** [comment]
I agree but we are dealing with a long-standing issue about how to map public transport, and AFAIK there is no consensus so far.

The situation seems to be that:
* The platform area does exist, it makes sense to have it (just like the shelter).
* The most logical course of action would be to remove the public_transport=platform tag from the way… but then iD would offer to "upgrade the tags" and sooner or later a newbie will click on it.
* Same if we remove public_transport=platform from the highway=bus_stop node.
* We could remove the highway=bus_stop node entirely and only use the platform area… but at the expense of poor rendering on osm-carto or the Transport Layer.  Tagging for the renderer is bad, though, but I’ve been looking at this problem for years, looking at how mappers in other major cities were attempting to deal with this, and couldn’t find a working solution so far.

The purpose of this ticket is that we could avoid having SC making the situation a bit worse.  Perhaps this discussion should be held on another forum.  (Or I could open a ticket for iD or osm-carto.)

**Comment by matkoniecz** [comment]
Can you link some example affected objects?

**Comment by rhhsm** [comment]
> Can you link some example affected objects?

https://www.openstreetmap.org/way/185354643 and the stop node at the left end of it: after I was asked by SC, both the stop and the platform now have info on lighting, shelter, bench, bin, etc.

**Comment by matkoniecz** [comment]
I would be tempted to declare that correctly tagged bus stop is using `highway=bus_stop` (on node or area) and ignore this duplicative alternative tagging.

**Comment by Helium314** [comment]
But according to wiki `highway=bus_stop` should only be used on nodes.
So if the `public_transport=platform` is mapped as way/area, the `highway=bus_stop` actually should be on a different element (and then SC asks for both).

**Comment by matkoniecz** [comment]
> But according to wiki highway=bus_stop should only be used on nodes.

In the discussion for that the claim was that it is needed as areas are impossible to establish - what does not apply in cases where such areas are being mapped.

**Comment by westnordost** [comment]
Well, the bus stop on that particular bus stop is duplicated here https://www.openstreetmap.org/way/185354643 and here https://www.openstreetmap.org/node/1938658746

And hence, StreetComplete also asks the question twice.

This is not a StreetComplete problem, but a tagging problem. Whether the tagging is correct according to the documentation in the wiki or not that relevant to the point that even if this tagging is fine, it is still a duplication. Asking the same question (or in general: repeating the same information) for both elements is thus also fine as long as the duplicate element is considered fine.
