### ISSUE TITLE
Score/ranks not transferred to a new device

### ISSUE THREAD

**Issue by sheilbronn** [streetcomplete/StreetComplete#4691]
I'm a huge and long-lasting fan of StreetComplete and just got myself a new smartphone (Galaxy S20 FE, replacing Galaxy S8)
I'm currently scoring in the Top 20 for Germany and Top 40 worldwide so I'd love  to keep my ranks... ;)

I checked the FAQs (https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ) and the other issues here (esp. [1485](https://github.com/streetcomplete/StreetComplete/issues/1485)) but couldn't find any solution.

**How to Reproduce**
I did the following only once so far (and haven't de-installed StreetComplete on the old smartphone):

1. Installed and started StreetComplete on new smartphone (Galaxy S20 FE)
2. Authenticated to OSM 
3. My Profile shows me as a "new user"...

**Expected Behavior**
Get the previously achieved count (54944) and ranks (17 Germany/33 globally) transferred to the new smartphone, too.

**Versions affected**
V50.0 on Galaxy S8
V50.0 on Galaxy S20 FE

Sorry if I'm overlooking something obvious....
Thanks for any suggestion and also making it available in the FAQs. 
Offcourse I'd be willing to test. Howver, for obvious reasons I'm hesitant to deinstall StreetComplete on the old phone as long as I haven't transferred everything....

**Comment by HolgerJeromin** [comment]
This is issue #4625
Will need another few weeks :)

**Comment by sheilbronn** [comment]
I just decided to deinstall and the reinstall StreetComplete on the new device:
After (re)authenticating to OpenStreetmap it says (in German) on "Mein Profil":
"Deine Statistiken synchronisieren noch. Schau später nochmal vorbei" ;)

So, now I'm quite curious whether it be will be successful on the second try..... I'll report back later.

**Comment by sheilbronn** [comment]
> This is issue #4625 Will need another few weeks :)

Sorry, I overlooked that. Thanks again!
