### ISSUE TITLE
Cycleway gets displayed on map but not in the overlay form

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4692]
**How to Reproduce**
[This way](https://www.openstreetmap.org/way/25140139) has a sidewalk on one side which is also dedicated for cycling **in both directions**. This can't be tagged with SC, because SC thinks a sidewalk can only be a oneway. This tagging leads to the situation that the correct cycleway is displayed on the map but not in the overlay form when tapping on the way.

![grafik](https://user-images.githubusercontent.com/92865620/208258936-bd15e485-fe08-41f4-8365-cf12d3a8e2e9.png)
https://www.openstreetmap.org/way/25140139
```
cycleway:left=no
cycleway:right=track
cycleway:right:bicycle:backward=yes
cycleway:right:bicycle:forward=designated
cycleway:right:oneway=no
cycleway:right:segregated=no
cycleway:right:surface=paving_stones
cycleway:right:traffic_sign:backward=DE:239,1022-10
cycleway:right:traffic_sign:forward=DE:240
dual_carriageway=yes
highway=secondary
lanes=3
lit=yes
maxspeed=50
name=Tiefer
oneway=yes
oneway:bicycle=no
shoulder=no
sidewalk=right
sidewalk:right:surface=paving_stones
smoothness=excellent
surface=asphalt
turn:lanes=left|through|through
wikipedia=de:Tiefer
```

**Expected Behavior**
Actually there should be one more option in the "select cyclway" dialog for "explicitly shared sidewalk, both directions"

**Versions affected**
v50.0

**Comment by matkoniecz** [comment]
@legofahrrad Why selecting "explicitly shared sidewalk" would not work?

![screen](https://user-images.githubusercontent.com/899988/208264068-817d10c5-301d-48dd-860b-5a615da86131.png)

Is it about phrasing? Then maybe renaming "explicitly shared sidewalk" to "explicitly shared sidewalk in both directions" and "none, no cycling allowed in this direction" to "none, no cycling allowed in this direction on the road" would help?

**Comment by matkoniecz** [comment]
If that would not work, which tags you expect StreetComplete to set?

**Comment by legofahrrad** [comment]
StreetComplete expects sidewalks with "bicycles allowed" always being one-way. When selecting the way mentioned in my first comment and then tapping on the "???" side and then selecting the "shared sidewalk" option, SC tags `cycleway:right:oneway=yes`. That's just wrong, because the sidewalk is for cycling in both directions. A new option "shared sidewalk, both directions" should solve this problem by adding `cycleway:right:oneway=no`.

**Comment by matkoniecz** [comment]
> StreetComplete expects sidewalks with "bicycles allowed" always being one-way

not always, but it is happening in this specific case

**Comment by westnordost** [comment]
With "dedicated", you mean 
<img src="https://upload.wikimedia.org/wikipedia/commons/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg" width="120"/>
?

**Comment by legofahrrad** [comment]
In this example not necessarily, no. The sidewalk has different traffic signs for the different direction.
`cycleway:right:traffic_sign:backward=DE:239,1022-10` (footway + bicycles allowed)
`cycleway:right:traffic_sign:forward=DE:240` (yes, that's the sign form your comment)

**Comment by westnordost** [comment]
Hm, couldn't this configuration exist also with anything else? I.e.

- footway + bicycles allowed in both directions
- dedicated footway + bicycles in both directions

Basically, if it is "footway + bicycles allowed", it is tagged as `cycleway:*=no` + `sidewak:*:bicycle=yes`. In other words, it is pretty much not a cycleway at all. Plus, at least in Germany, bicycles are just "guests" on the sidewalk and need to avert everyone else (and go max at walking speed). So, basically the same situation de-facto as if there wouldn't be a sign at all, only that the police doesn't have a reason to fine you.

**Comment by legofahrrad** [comment]
I'm not sure how well I understood you... but tagging roads with sidewalks with "bicycles allowed" as `cycleway:{side}=track` + `cycleway:{side}:segregated=no` is the established tagging scheme.
So,
> Basically, if it is "footway + bicycles allowed", it is tagged as cycleway:&ast;=no + sidewalk:*:bicycle=yes. In other words, it is pretty much not a cycleway at all.

isn't the best way to tag a road, if I see it correctly.

The only issue now is, that StreetComplete shouldn't break valid tagging by showing the "???".
I see no problem by adding an option for sidewalks that doesn't add `cycleway:{side}:oneway=yes` and think that this option should fit for my example from Bremen.

**Comment by westnordost** [comment]
> cycleway:{side}=track + cycleway:{side}:segregated=no is the established tagging scheme.

That's for <img src="https://upload.wikimedia.org/wikipedia/commons/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg" width="120"/>

**Comment by westnordost** [comment]
Anyway, I'll add "explicitly use sidewalk, both directions"
