### ISSUE TITLE
Quest suggestion: self_checkout

### ISSUE THREAD

**Issue by The-Nickname** [streetcomplete/StreetComplete#4693]
### General
Affected tag to be modified/added: [self_checkout](https://wiki.openstreetmap.org/wiki/Key:self_checkout)
Question asked: **Is there a self-checkout lane in this shop?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose (is established and useful (but not tagged that often in most areas))
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] **Not** 🐿️ easily answerable by any pedestrian from the outside but a survey is necessary
 - This quest should most likely not be enabled by default(similar to the "What kind of internet connection does this place offer?" etc quests)
- [ ] _Maybe_ 💤 Not an overwhelming percentage of quests have the same answer (No spam)
 - Not sure if it would be to spammy, so it might be better to carefully select what kind of `shop`s should ask for this quest(see implementation ideas).
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort(yes, many shop=*))

### Ideas for implementation

**Element selection:** According to the Wiki "[shop](https://wiki.openstreetmap.org/wiki/Key:shop)=*" is the only necessary condition, but maybe that would be too much💤.
If so a list of reasonable tags would include:
- `shop=supermarket` and maybe `shop=convenience`
- In countrys like Taiwan, Germany, Brittan and probably also the US, France, Poland and maybe even some other European nations
~~- All [General, department and mall store's](https://wiki.openstreetmap.org/wiki/Key:shop#General_store,_department_store,_mall)~~
~~- Probably all [Food, beverages](https://wiki.openstreetmap.org/wiki/Key:shop#Food,_beverages)~~
~~- Probably all [Clothing, shoes, accessories](https://wiki.openstreetmap.org/wiki/Key:shop#Clothing,_shoes,_accessories)~~
~~- Probably also [Stationery, gifts, books, newspapers](https://wiki.openstreetmap.org/wiki/Key:shop#Stationery,_gifts,_books,_newspapers)~~
~~- And as it seems also [chemist](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dchemist)s so maybe even some more like [cosmetics](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcosmetics) etc (but probably not hairdressers etc)~~
~~- Not sure about the other ones, it would probably be useful to see all shop=types where it is already tagged =yes~~

In the future it might also be worth to consider this as a verification quest e.g. "Does this shop still (not) offer self_checkout?", since this is becoming more and more wide spread.

**Metadata needed:** Idk

**Proposed UI:** Should be pretty straight forward, but I made a small mockup to illustrate which "blueprint" to use: 
![StreetComplete_options-draft](https://user-images.githubusercontent.com/120755240/208263647-b8f6a707-b46d-4245-ab1a-68a21a6af77b.png)

So 
self_checkout=yes if present
self_checkout=no if not (so SC doesn't ask the quest again)
self_checkout=only if no normal checkout counter

**Comment by rhhsm** [comment]
I wouldn't call this tag "established" with only 282 instances on taginfo.
It would be enormously spammy here in Bulgaria, where I know of 1 supermarket that introduced them last month. If introduced, it should be strongly restricted to a limited number of countries where self checkout is more common, and then probably only be asked for shops where they are common (`shop=supermarket` and maybe `shop=convenience`?). It can then be rolled out to other kinds of shops and other countries as self checkout becomes more common there too.

**Comment by matkoniecz** [comment]
> To be added tag is established and has a useful purpose

As @rhhsm points out: https://taginfo.openstreetmap.org/keys/self_checkout#chronology

Given that in 1 hours of mapping I could increase global tag usage by 10% by mapping nearby shops it does not seem established.

Also, what is the actual or theoretical use of this tag?

**Comment by matkoniecz** [comment]
For vegan food there is plenty of people wanting vegan only place or place where there will be meat.

Wheelchair accessibility has obvious usability.

But why someone would prefer one shop over another due to self checkout or lack of it? It is not even that shops with self-checkout will have smaller queues, many of them have anyway gigantic ones.

**Comment by westnordost** [comment]
I agree with @matkoniecz and @rhhsm here. To summarize, it is rejected because:
- the tag is really rarely used yet
- there isn't much of a useful purpose about it
- (it will have to be disabled by default anyway)

**Comment by Dimitar5555** [comment]
> It would be enormously spammy here in Bulgaria, where I know of 1 supermarket that introduced them last month.

Just 3 years later, almost every newly built large supermarket has self checkout lanes. Billa, Lidl and Kaufland have retrofitted a big part of their old stores with self checkout lanes. Some of them even had to add more such lanes where they were present due to high demand.

The tag's count is 1200 currently of which 675 are on `shop=supermarket`. I'm pretty sure that there are a lot more of them around the world now, so it seems reasonable to reconsider adding such quest for `shop=supermarket` as a starting point.

**Comment by The-Nickname** [comment]
@Dimitar5555 yes, although it might still be too spamy for some countries and even brands.
Maybe it would make sense to investigate which brands in which countries use it most and then only activate the quest for those, i.e. UK, Germany,... for `shop=supermarket` of `brand=` Billa, Lidl, Edeka, Kaufland,...

**Comment by matkoniecz** [comment]
If it is everywhere it fails "Maybe 💤 Not an overwhelming percentage of quests have the same answer (No spam)"

And "there isn't much of a useful purpose about it" remains applicable.

> almost every newly built large supermarket has self checkout lanes. Billa, Lidl and Kaufland have retrofitted a big part of their old stores with self checkout lanes.

that does not seem reason to enable it

(note, if quest rejected years ago becomes OK then it is better to open a new issue)
