### ISSUE TITLE
What features does this POI have?

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4697]
**Use case**
After answering the traffic island quest with "no" for the umpteenth time (so far I never answered "yes"), I was considering to propose a quest for pedestrian crossings that are raised (adding `traffic_calming=table` to the crossing node). They are much more common here, and I've seen them in many other countries including my home country. However, doing some researched showed that the `traffic_calming=table` tag is used much less frequently than `crossing:island` so for some it might be even more spammy than the traffic island quest (#1961 and #2030). It also adds one more quest to the list of quests that produce many `=no` values (#4191).

**Proposed Solution**
I propose to merge all pedestrian crossing quests into one, which asks for all the possible features a pedestrian crossing could have: traffic island, traffic calming table, tactile paving, traffic light, markings (#4663), etc. The "What kind of crossing is this?" quest can be taken as a start, but should be made multiple choice, so that a user can pick the features that are present by tapping on all the images that show the features that are there. SC should then add tags `=yes` for all those selected, and a checkdate, but should not add `=no` values for features not selected. SC can then assume that any crossing node that has a checkdate has been surveyed by a SC user and not show the quest for these nodes. If it is decided that a new feature should be added to the list, SC can then show the quest for all pedestrian crossings with a checkdate before the release date of the new version. It may seem like there will suddenly be a lot of quests appearing for pedestrian crossings that have been surveyed before, but a brand new quest for a new pedestrian crossing feature would have the same effect. Adding it to a combined quest like proposed here, it would give an opportunity to re-survey the previously existing features again and add any that were missing in the same go.

It will be a different way SC asks quests that may confuse users initially. However, the same concept can be applied to other POIs that can have many features, such as pedestrian traffic lights (call button, sound signals and vibration) and public transport stops (ask for Departures/Arrivals Board, Shelter, Bench, Lit and Rubbish Bin at the same time). Such quests can also offer the choice of less frequently occurring features without causing many `=no` values and would not feel spammy (the surface quest has many answer options that are rarely used, for instance, but this is not seen as a problem).

The quest could be shown as a list of pictures of possible features with a short text describing them and that can be selected by tapping them.

**Comment by Helium314** [comment]
> After answering the traffic island quest with "no" for the umpteenth time (so far I never answered "yes")

Why don't you disable the quest if it's annoyingly spammy? Or maybe better ask for the quest to be disabled for the country?

The main problem with `traffic_calming=table` on crossings (besides being rare) is that `traffic_calming=no` is not documented, so one would make sure to avoid ambiguity here.
(btw if you're interested in adding `traffic_calming=table` to crossings, this is possible in [SC_EE](https://github.com/Helium314/StreetComplete))

> Proposed Solution

In general I like the idea, but this will make it impossible to only care about specific quests. E.g. then you'll need to enter information about waste bins when you only care about tactile pavings.

**Comment by davidpnewton** [comment]
That assumes all raised crossings are a table. NOT true. I can think of multiple raised pedestrian crossings in the town where I live which are definitely humps and not tables. I have tagged accordingly.

**Comment by rhhsm** [comment]
> (btw if you're interested in adding `traffic_calming=table` to crossings, this is possible in [SC_EE](https://github.com/Helium314/StreetComplete))
> 
Thanks! Show all quests for the selected element at once, Level filter and Ability to create personal notes are definitely options I would like to use (hope they will eb implemented in the default SC soon)

> > Proposed Solution
> 
> In general I like the idea, but this will make it impossible to only care about specific quests. E.g. then you'll need to enter information about waste bins when you only care about tactile pavings.

Surely someone who is checking for tactile paving at a bus stop wouldn't mind reporting that there is a waste bin as well while he's there anyway? Maybe it needs to be stressed that all features present should be reported.

> That assumes all raised crossings are a table. NOT true. I can think of multiple raised pedestrian crossings in the town where I live which are definitely humps and not tables. I have tagged accordingly.

Those must be very narrow crossings then. But it could easily be added as an answer option.

**Comment by davidpnewton** [comment]
Not narrow crossings at all. Normally-sized zebra and puffin crossings.

https://www.geograph.org.uk/photo/5606785

That for example is a humped zebra crossing. No wider than a normal speed bump.

**Comment by Helium314** [comment]
Please note that we should be using the terms as they are used in OSM (wiki) to avoid confusion.
The example is clearly [`traffic_calming=table`](https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dtable) and not [`traffic_calming=hump`](https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dhump)

**Comment by matkoniecz** [comment]
> No wider than a normal speed bump.

but wider than traffic_calming=bump, what sounds like reason for having separate quest for each property as it gives more space to explain what is being asked about

![1200px-Ležeći_policajac_016](https://user-images.githubusercontent.com/899988/208876446-74858fe6-5e32-46ad-883c-6e87a24406b1.jpg)

**Comment by westnordost** [comment]
So, regarding this suggestion... in a nutshell, it is out of scope of StreetComplete. It is deliberate that SC quests always only ask one thing, that's one of the fundamental design decisions of this app. Yes, it would be faster if one could set all the things at the same time. But then, one could just use iD, Vespucci, possibly EveryDoor instead.
Regarding the traffic calming at pedestrian crossings: I think this is too rare that it makes sense to ask about plus, of course, there is no tag for "there is no traffic calming here".

**Comment by rhhsm** [comment]
> So, regarding this suggestion... in a nutshell, it is out of scope of StreetComplete. It is deliberate that SC quests always only ask one thing, that's one of the fundamental design decisions of this app. Yes, it would be faster if one could set all the things at the same time. But then, one could just use iD, Vespucci, possibly EveryDoor instead.

Indeed what I'm suggesting is a deviation from a fundamental design decision of SC so we should consider it very carefully. The strength of SC is its simplicity so it can easily be used by beginners (unlike Vespucci, for instance) and we should be careful not to compromise on that. But I think what I propose is still keeping SC simple to use. We should not reject a change of the rules just because it is against the rules to change the rules...

Can this issue be re-opened to collect a few more opinions?

**Comment by westnordost** [comment]
Your can create a discussion 

On December 24, 2022 8:24:09 AM GMT+01:00, Richard ***@***.***> wrote:
>> So, regarding this suggestion... in a nutshell, it is out of scope of StreetComplete. It is deliberate that SC quests always only ask one thing, that's one of the fundamental design decisions of this app. Yes, it would be faster if one could set all the things at the same time. But then, one could just use iD, Vespucci, possibly EveryDoor instead.
>
>Indeed what I'm suggesting is a deviation from a fundamental design decision of SC so we should consider it very carefully. The strength of SC is its simplicity so it can easily be used by beginners (unlike Vespucci, for instance) and we should be careful not to compromise on that. But I think what I propose is still keeping SC simple to use. We should not reject a change of the rules just because it is against the rules to change the rules...
>
>Can this issue be re-opened to collect a few more opinions?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4697#issuecomment-1364478338
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mnalis** [comment]
- (For interested parties, discussion is in https://github.com/streetcomplete/StreetComplete/discussions/4761)
