### ISSUE TITLE
cycleway=shoulder is ambiguous

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#4698]
Can we colour cycleway=shoulder differently to distinguish it from cycleway=no on the map?

**Comment by westnordost** [comment]
It is normal that some taggings are displayed wit the same color. But what color would you suggest?

- explicitly on sidewalks is cyan
- tracks are blue
- exclusive lanes are gold
- advisory lanes are orange
- sharrows are orange dashed
- on busways are lime
- none and on shoulders are black

Maybe also lime but dashed? Or black and dashed?s

**Comment by frankie2784** [comment]
I reckon black and dashed makes the most sense. Shoulders are not really similar to the shared busway, conceptually, so it probably shouldn't have the same colour scheme.
