### ISSUE TITLE
Black markings and dark mode

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#4699]
In dark mode, black markings - like those that indicate no cycleway or no footpath - are very difficult to see against the dark background.

For example, the below screenshot includes some streets obviously marked as missing data (red), some tagged with no cycleway (black), and some where SC doesn't explicitly ask for input, due to being a service road or freeway (no marking). It is difficult to distinguish between the latter two without zooming right in.

![Screenshot_20221224-054514.png](https://user-images.githubusercontent.com/19356194/209396458-93f6981f-ec74-452d-9a7a-a73335a53e92.png)

Here's the same in light mode, for context.

![Screenshot_20221224-055535.png](https://user-images.githubusercontent.com/19356194/209397121-07f2673e-bba8-4951-873f-7c7d5b84eddc.png)

Is there a lighter grey (or some other colour) that can be used instead of black when in dark mode?

**Comment by westnordost** [comment]
Ideally the overlay colors won't change between dark and light mode. A solution would be to generally brighten the black a bit. (However this collides with the 2 additional shades of grey added in https://github.com/streetcomplete/StreetComplete/pull/4642 , FYI @matkoniecz )

**Comment by matkoniecz** [comment]
I just eliminated dark gray there.

**Comment by matkoniecz** [comment]
how you feel about this slightly less blacker black? (note that dashes appeared as styling of shoulder available for cycling was changed)

![screen05](https://user-images.githubusercontent.com/899988/209423472-1b2cd75d-78e6-401b-b61d-1fe9f80e511f.png)
![screen06](https://user-images.githubusercontent.com/899988/209423473-578f09e4-cf40-4f2c-85f4-c5b9b0515a53.png)

(it is already applied in https://github.com/streetcomplete/StreetComplete/commit/92cf72581b5bb25f312833c77aae0b0650f29877 , but I guess going further is also possible)

**Comment by frankie2784** [comment]
Thanks for looking into this. Personally I find it's still not contrasted
enough against the background, especially if this were zoomed out much
farther. A couple of shades lighter would be better. But I also appreciate
that there's a compromise that needs to be made between light and dark mode.

**Comment by westnordost** [comment]
It might actually be worse.  What's the brightness of the dark mode's background-blue? The higher the difference between the "black" and the background, the better visible it will be.  Maybe 100% black actually works better?

On December 24, 2022 7:15:17 AM GMT+01:00, Mateusz Konieczny ***@***.***> wrote:
>how you feel about this slightly less blacker black? (note that dashes appeared as styling of shoulder available for cycling was changed)
>
>![screen05](https://user-images.githubusercontent.com/899988/209423472-1b2cd75d-78e6-401b-b61d-1fe9f80e511f.png)
>![screen06](https://user-images.githubusercontent.com/899988/209423473-578f09e4-cf40-4f2c-85f4-c5b9b0515a53.png)
>
>(it is already applied in https://github.com/streetcomplete/StreetComplete/commit/92cf72581b5bb25f312833c77aae0b0650f29877 , but I guess going further is also possible)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4699#issuecomment-1364470394
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So, the brightness of the background in dark mode is 23-26%.

The brightness of the "black" was 27% and with @matkoniecz change it is 33%. So, it is 10% difference in brightness. If it is completely black, the difference would be at least 20%.

With completely black, it looks like this:
![image](https://user-images.githubusercontent.com/4661658/209675975-9888a7ce-ea0c-4864-8c5e-596ac86e4fb8.png)
(for some reason when I take a screenshot, it is desaturated a bit)

**Comment by matkoniecz** [comment]
Yes, that is actually better

**Comment by frankie2784** [comment]
The colour change with the new version is good, thanks
