### ISSUE TITLE
Allow house number quest  in French Polynesia

### ISSUE THREAD

**Issue by jblemee** [streetcomplete/StreetComplete#4703]
House number quest is not authorized in french polynesia but it's been a couple of years since this country (finally) gives addresses to all buildings (house number + street name)

**How to Reproduce**
Go to : Settings => Quest selection => scroll to `house number` quest

**Expected Behavior**
Users should be allowed to activate this quests. 
It should be activate by default

**Versions affected**
Current version

![signal-2022-12-26-172654_002](https://user-images.githubusercontent.com/300704/209607912-44f5c191-2ba1-433a-96d8-edfaa4b6825c.png)

**Comment by matkoniecz** [comment]
This is disabled due to https://github.com/streetcomplete/StreetComplete/issues/2427 and https://t.me/osmfr/26320

Has anything changed since then?

**Comment by jblemee** [comment]
Look likes we have the same issue here : https://www.data.gouv.fr/fr/datasets/base-adresses-locales/

Too bad
