### ISSUE TITLE
Text is black/ hard to read when switching to dark mode

### ISSUE THREAD

**Issue by thibaultmol** [streetcomplete/StreetComplete#4704]
**How to Reproduce**

I THINK : have theme be on auto. Start with light mode.
Then open a question. (Mine was from the "marked lanes" quest)
Then have it auto switch to dark mode.
Then click on one of the answers that makes the question of "how many lanes" popup.
**Expected Behavior**

The background shouldn't be black yet. Now it's black on black 
![Screenshot_20221227_172752_StreetComplete](https://user-images.githubusercontent.com/1010226/209695015-22ad0669-cb2b-4ba8-b6f1-47c11cbf3167.jpg)

**Versions affected**

Latest

**Comment by matkoniecz** [comment]
Sounds like #2158

Actually, recently it appears quite reliable in emulator but I am not sure how to even debug this

**Comment by thibaultmol** [comment]
Maybe changing the time on your phone to right before it switches. But i don't know what time it uses to switch

**Comment by westnordost** [comment]
One thing all reproductions so far have in common is that it happens with dialogs only.
