### ISSUE TITLE
StreetComplete doesn't take in account cycle lanes only described with cycleway=lane

### ISSUE THREAD

**Issue by slasherfun** [streetcomplete/StreetComplete#4705]
Hi,

Issue: on ways tagged only with cycleway=lane, StreetComplete will consider that there is no cycleway:
- the cycleway layer will show the way as red (no info)
- the quest used will be "is this still the cycleway situation here" (and *not* "what's the cycleway situation here")
Example: https://www.openstreetmap.org/edit?way=23938435 
![Screenshot_20221227-201517](https://user-images.githubusercontent.com/10389790/209712892-17e33eeb-90a7-424b-9430-54b85fb83fac.jpg)  ![Screenshot_20221227-201533](https://user-images.githubusercontent.com/10389790/209712901-41b1089c-6ee2-4d81-b965-40a7f933a014.jpg)

Only having additional attributes such as cycleway:lane=advisory/exclusive will make StreetComplete consider that there is a cycle lane in that way.
Example: https://www.openstreetmap.org/way/392324633
![Screenshot_20221227-201647](https://user-images.githubusercontent.com/10389790/209712928-62ce0452-f30b-45db-bcec-e2b02482e7dd.jpg)

Expected: 
- take in account cycleway=lane as a minmal input that some sort of lane exists (and asks to specify what kind of lane it is maybe?)
- if cycleway=lane is insufficient to StreetComplete, maybe the quest "what's the situtation here" should be used instead of "is this still the situation here"

Don't hesitate to ping me if you need additional input!

**Comment by westnordost** [comment]
> take in account cycleway=lane as a minmal input that some sort of lane exists (and asks to specify what kind of lane it is maybe?)

An incomplete input is treated the same as a missing input. It is not planned to change this.

> if cycleway=lane is insufficient to StreetComplete, maybe the quest "what's the situtation here" should be used instead of "is this still the situation here"

To change the question text in this situation is not possible due to technical reasons.
