### ISSUE TITLE
Enable people to add road and sidewalk widths

### ISSUE THREAD

**Issue by Robinlovelace** [streetcomplete/StreetComplete#4708]
**Use case**

Road widths are objective and relatively easy to add in OSM. Width is also important for citizen science and policy impact because knowing the width of roads and sidewalks, and car storage lanes, can help prioritise cost effective interventions like new cycleways separated from potential fast moving motor traffic with cost effective 'light segregation'.

I am currently not sure if this functionality is in StreetComplete. I have tried clicking on bits of the UI on my Pixel 6 but no success yet, even after looking at this and following the links: https://github.com/streetcomplete/StreetComplete/releases/tag/v41.0

**Proposed Solution**

Better documentation of how to add road/sidewalk/other widths if it's possible. Add the functionality if not.

So cool that AR enabled phones can help here, although I've not got it working yet. Thanks!

**Comment by matkoniecz** [comment]
This is already implemented

Have you tried looking at quest list and searching for "wide"? See also https://wiki.openstreetmap.org/wiki/StreetComplete/Quests listing

**Comment by Robinlovelace** [comment]
Aha yes great, that did it. Testing it now...

**Comment by Robinlovelace** [comment]
One follow-up question: is adding "How wide is the sidewalk" and same for car storage area a reasonable quest request? Thanks.

**Comment by Robinlovelace** [comment]
Couple of follow ups .. I enabled the quests as shown before, this is great but for new users this setting is a bit buried so could be a usability issue? 
![Screenshot_20221230-114530](https://user-images.githubusercontent.com/1825120/210067382-e4464a05-3aa6-42f8-bcdc-02d86ec8620c.png)

**Comment by Robinlovelace** [comment]
More importantly after activating the quest I cannot see any width questions. Am I missing something?

**Comment by Robinlovelace** [comment]
![Screenshot_20221230-114847](https://user-images.githubusercontent.com/1825120/210067471-4b4559c1-53e6-4302-aca5-701bc7ff2732.png)

This is what I see, I'm going to add the width of Barrack Road in Leeds.

**Comment by Robinlovelace** [comment]
*trying to add the width* I meant apologies, was typing from mobile.

**Comment by matkoniecz** [comment]
I would try to start from solving other quests, for example surface quest is likely to be shown before width quest.

**Comment by Robinlovelace** [comment]
Sure will give it a go

**Comment by Robinlovelace** [comment]
Update on this: have done a load of other quests but width question but showing so far.

**Comment by Robinlovelace** [comment]
![Screenshot_20221230-122027](https://user-images.githubusercontent.com/1825120/210069707-aa2dbdc8-0453-4fac-89c1-a33c4f069084.png)

**Comment by Robinlovelace** [comment]
Update: a ruler has appeared.

![Screenshot_20221230-122825](https://user-images.githubusercontent.com/1825120/210070241-febb5a68-09f1-4ea5-a8b8-695cf7bbad47.png)
