### ISSUE TITLE
Expert Mode: Allow to edit tags directly

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#471]
Add an "Expert mode" option in the settings which when turned on, enables a couple of advanced features. Most prominently, and this is what this ticket is about, add a button to each quest which enables the user to instead of using the normal form, enter any key-value tags directly as response to the quest.

This has not highest priority right now and will roughly come after I implemented some leaderboards (v4 and later).

**Comment by rugk** [comment]
> (v4 and later)

Hehe, I guess you've changed your versioning scheme by now a little… :stuck_out_tongue_winking_eye:

**Comment by westnordost** [comment]
Not the versioning scheme, but the plans I had. If there would have been no input from the outside, i.e. the app would not have been noticed by anyone, it would look quite different now.

**Comment by matkoniecz** [comment]
I am wondering is it something actually useful and needed. Multiple times I switched to Vespucci, but it basically always involved changing geometry or deleting elements.

Basically never it was just changing tags on an element with a quest.

**Comment by matkoniecz** [comment]
Layer system would be much more useful as it would allow a general overwiev, not limited to just a current element.

In which situation someone would use it? (I am not looking for theoretical, I can imagine some that never happened to me).

Though if  #2774 #2773 would be rejected this would fit as sort of replacement.

**Comment by Helium314** [comment]
Related: what might also be interesting in expert mode is (somewhat) adjustable element selection. So e.g. I can choose to have the roof shape quest for higher buildings, have surface quests for service roads, disable the lit quest for roads,...

**Comment by mnalis** [comment]
Expert mode might be useful still, but I'm not so sure about manual entering of `value=keys` tags what this ticket is about specifically - it happens very rarely so I'm nowdays just fine with taking a Note with a picture, instead of entering less used tag manually on mobile device, checking it on wiki for exact syntax and related tags etc.  And when I do, I also usually go to Vespucci, as I need extra functionality (eg. fixing that address on neighboring building and not only one SC asks about, auto-tags suggestions etc).

**Comment by westnordost** [comment]
Yeah, I thought about this and I will drop this feature. Some more things to add additionally to what has been said already:
- if someone tags something different and maybe wrong, people first will think that StreetComplete does this wrong tagging, not that user. That's bad publicity, but also an additional triaging/maintenance effort to communicate this and resolve issues that are posted because of that on the issue tracker
- even if it is in some way marked in the changeset comment/tags that the user used custom tags, this is something which can easily be overlooked
- the use case that f.e. a user prefers to use another tag (f.e. `source:maxspeed` instead of `maxspeed:type`) is not really feasible, because he would need to enter expert mode and write this out on his smartphone keyboard for every single quest
- so the only use case that remains, that I see, is to tag something for which there is not option for. But then, in many/most cases except for the extreme rare ones, it is better to either leave a note (if unsure how to tag or there is no good tag for it) or to add this option to StreetComplete. The scenario that the user knows the exact value for a very rare tag is quite unrealistic. If I f.e. want to tag a certain rare kind of shop and I know there is some tag for thta, I search the wiki, taginfo and/or open up iD just to see if they have a preset for that. All these options are not really feasible on a smartphone, while on and about.

**Comment by mnalis** [comment]
- related: https://github.com/streetcomplete/StreetComplete/discussions/3003

**Comment by smichel17** [comment]
In particular, I think https://github.com/streetcomplete/StreetComplete/discussions/3003#discussioncomment-966353 (open element for editing in other app) would be a good alternative to adding arbitrary tag functionality.
