### ISSUE TITLE
"Explicitly shared use pavement, both directions" does not prefill on cycleway overlay form.

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4711]
**How to Reproduce**

Apply the option "Explicitly shared use pavement, both directions" to one side and anything to the other side and then select the way again. Or view a way such as [this](https://www.openstreetmap.org/way/728830682), with 
`cycleway:left=track`
`cycleway:left:oneway=no`
`cycleway:left:segregated=no`

The colouring is done correctly, but when tapping on the segment the form is not initiated.

![Screenshot_20221230-231753_2](https://user-images.githubusercontent.com/77166354/210117678-ca01bfb2-0df5-4bf0-a7a8-2a8730774464.png)

It looks like the issue is around here:

https://github.com/streetcomplete/StreetComplete/blob/66b8725af0f34684498a94cbea09d85e2822a625/app/src/main/java/de/westnordost/streetcomplete/osm/cycleway/CyclewayItem.kt#L86-L87

In that the direction isn't "both"

**Comment by westnordost** [comment]
I think I already fixed that, but unfortunately after the v50.1 release:

https://github.com/streetcomplete/StreetComplete/blob/66b8725af0f34684498a94cbea09d85e2822a625/app/src/main/java/de/westnordost/streetcomplete/osm/cycleway/CyclewayItem.kt#L103

Is this reproducible on master?

**Comment by westnordost** [comment]
Jup, just tested.
