### ISSUE TITLE
Add mapcomplete to the Link collection 

### ISSUE THREAD

**Issue by thibaultmol** [streetcomplete/StreetComplete#4712]
I noticed that mapcomplete hasn't been added to the link collection section of the app.

**Comment by westnordost** [comment]
It's a rather opinionated list. I have a private list of candidates that could be added in the future and mapcomplete is already on it for consideration.
However, from the point of view of a StreetComplete mapper, mapcomplete is less relevant than for other target groups as
1. some of streetcomplete's functionality is simply mirrored in mapcomplete (e.g. in OSM for the blind) in a less streamlined-for-phone users fashion
2. some of mapcomplete's unique feature is now being mirrored in streetcomplete (the overlays feature), also (IMO of course) in a more streamlined fashion.
What remains and will probably not be mirrored in StreetComplete are editable special interest maps such as the postbox map, the hackerspace map or the rainbow pedestrian crossings map. And this on its own is of course a lot less interesting than the capability of mapcomplete as a whole.
But in any case, it is on my list.
