### ISSUE TITLE
Bicycle overlay: small coloring change (for cycleway:lane=advisory)

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4713]
**Use case**
Make it more look like the reality

**Current color shema**
- `cycleway=lane + cycleway:lane=exclusive` = golden
- `cycleway=lane + cycleway:lane=advisory` = orange
- `cycleway=shared_lane + cycleway:lane=pictogram` (sharrow) = orange dashed
- path, footway, sidewalk = black
- `cycleway=shoulder` = black dashed
- on bus lane = lime
- shared sidewalk = cyan dashed
- shared path = cyan
- cycleway, separated foot/cycleway = blue

**Proposed Change**
- `cycleway:lane=advisory` = **golden dashed** (because on the ground it looks like "exclusive" but dashed)
- optional: `cycleway:lane=pictogram` (sharrow) = **black dashed** (like `shoulder`, because there is no real bicycle infrastructure)
- (I will propose to color all _path, footway, sidewalk_ with `bicycle=yes` in a different request, to not mix too many things here)

**Comment by westnordost** [comment]
In some countries,  all cycle lanes are dashed, in others, advisory cycle lanes age not dashed.

IMO this suggestion puts the advisory lane too close to an excllusive/normal lane while it is more similar to the pictogram lane

**Comment by SLMapper** [comment]
Ok, in my understanding those two lane types really are closer to each other than sharrows, but maybe that is my personal view or it also depends based on the country.
But if different countries have different visualizations then it is fine to keep it like it is.

**Comment by westnordost** [comment]
The same colors are used in all countries.  It is only the actual cycle lane markings (and hence their illustrations) that differ.

**Comment by SLMapper** [comment]
Sure, that's what I meant :+1
