### ISSUE TITLE
Bicycle overlay: Complete the picture by highlighting where cycling is allowed

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4714]
**Use case**
This is a follow up of https://github.com/streetcomplete/StreetComplete/issues/4669.

I want to be able to get a **full picture** of the bicycle friendly road network. Therefore I need to be able to visually distinguish where cycling is allowed and where not. 

Often connected bicycle road infrastructure consists of different types of ways or cycleways and might even frequently change between those. (This request is not about the signed cycling networks or routes, but about cycling infrastructure forming a network of bicycle friendly roads.)

Example: While traveling straight between two points you might be cycling on a hw=track, a cycle lane, a shared sidewalk, then a sidewalk where cycling is allowed, ...
Together they form some sort of bicycle network which is only well surveyable when being able to view all pieces together.
Today in SC I see many gaps in these networks and do not know if there really are gaps on the ground or not.

**Proposed Solution**
Highlight certain ways where bicycles are allowed in **gray**
- path, track (without `bicycle=no`) = gray
- sidewalk or footways with `bicycle=yes` = gray dashed

 (See https://github.com/streetcomplete/StreetComplete/issues/4713 for all current highlight colors)

**Alternative**
Highlight ways where cycling is **not allowed** `bicycle=no`. E.g. if the above would cause performance issues, because too many ways would get highlighted.

**Comment by matkoniecz** [comment]
Suns like "Bicycle overlay: bicycle=yes not visible" #4669 

is it the same one?

**Comment by SLMapper** [comment]
Partially only.
It is a new request based on the discussion there and changes done in the meanwhile.
Relevant changes done in SC:
- paths are being separately handled

Relevant changes in this new request:
- take a broader view
- do not only consider explicit `bicycle=yes` but also implicit allowed access (e.g. path or track)
- do not request to color it blue, but differently gray

**Comment by westnordost** [comment]
I too do not really understand the difference to #4669. We cannot show the difference between `no` and `yes` / not specified because of the reasons stated in #4669.

> do not only consider explicit bicycle=yes but also implicit allowed access (e.g. path or track)

This is considered. `highway=path` implies `bicycle=yes`. Hence, IIRC, `highway=footway + foot=yes + bicycle=yes` is displayed as "path".

**Comment by SLMapper** [comment]
Hmm, seems I am not formulating my thoughts understandable enough 🙃

Yes I understood that it's not possible to show the difference between implicit yes and explicit yes. That's why I re-thought it and proposing it differently in this issue here. 

My request is to show implicit and explicit yes the same way, but distinguish it from `bicycle=no` and `hw=footway`, which currently is displayed the same way = in black color. 

In addition I was proposing to extend the coloring to also include tracks (because they are similarly used for cycling networks), however this is not a high want as they are anyhow already visually distinguishable from paths or "normal" roads, right?

**Comment by westnordost** [comment]
`highway=footway` does not imply `bicycle=no`, it just implies `foot=designated`.

**Comment by mnalis** [comment]
So @SLMapper, if I'm understanding correctly, you're proposing three different bicycle-related colors.

There are however 5 bicycle-related categories that I see:

1. bicycles are **explicitly designated** (e.g. `highway=cycleway`, or `highway=*`+`bicycle=designated`) 
2. bicycles are **explicitly forbidden** (e.g. `highway=*` + `bicycle=no`)
3. bicycles are allowed (but **_NOT_ designated**)  **implicitly** (e.g. `highway=path`)
4. bicycles are allowed (but **_NOT_ designated**)  **explicitly** (e.g. `highway=*`+`bicycle=yes`)
5. bicycle access is **unknown** (e.g. bare [highway=footway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway), its wiki says _"minor pathways which are used **mainly** or exclusively by pedestrians"_ so bicycle status without extra tags is unknown)

So, how would you **color each of those 5** categories @SLMapper ?

**Comment by SLMapper** [comment]
@westnordost 
> `highway=footway` does not imply `bicycle=no`, it just implies `foot=designated`.

The [default access restrictions wiki page](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Worldwide) suggests to use the following default worldwide: "**footway: bicycle: no**"
(for Germany it suggests "bicycle: dismount")

The [English wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway) @mnails mentioned indeed says "used mainly or exclusively by pedestrians". The term "mainly" hower can be explained by when anything is tagged in addition, like stated under bullet point
> - Where a pathway is designated for pedestrians but is also allowed for bicycles you can use highway=footway and bicycle=yes.

The [German wiki](https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dfootway) is written differently, more focused on dedication (based on traffic signs or for sidepaths).

Both mention that shared ways should better be tagged as `hw=path`.
Of course you can still use `hw=footway` or `hw=cycleway` **together** with `bicycle=designated/yes` or `foot=designated/yes` to express the same reality.
But **without** these additonal tags a footway is considered for pedestrians only* and a cycleway for cyclists only.
(*A person with a dismounted bicycle is by law e.g. in Germany considered like a pedestrian)

@mnails I will answer the coloring question in a new reply...

**Comment by SLMapper** [comment]
> 1. bicycles are explicitly designated (e.g. highway=cycleway, or highway=*+bicycle=designated)
> 2. bicycles are explicitly forbidden (e.g. highway=* + bicycle=no)
> 3. bicycles are allowed (but NOT designated) implicitly (e.g. highway=path)
> 4. bicycles are allowed (but NOT designated) explicitly (e.g. highway=*+bicycle=yes)
> 5. bicycle access is unknown (e.g. bare highway=footway, its [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway) says "minor pathways which are used mainly or exclusively by pedestrians" so bicycle status without extra tags is unknown)
> 
> So, how would you color each of those 5 categories @SLMapper ?

1. already colored: **blue** (see #4713)
2. I suggested it only as an alternative - no color idea yet
3. I suggested **gray**
4. I suggested **gray dashed** - _actually this would only apply to `hw=footway` as  @westnordost [said](https://github.com/streetcomplete/StreetComplete/issues/4669#issuecomment-1358110637) it cannot be distinguished for path_ 
5. like 2 (see reason in post above)

Please be aware that I am only suggesting new highlights for `hw=path`, `hw=footway` (, maybe `hw=track`) and not any other roads.

**Comment by SLMapper** [comment]
Again reading https://github.com/streetcomplete/StreetComplete/issues/4714#issuecomment-1368991110 from what I understand there also cannot be done any differentiation between `hw=footway + bicycle=yes` and `hw=path`, can it?
If this is the case, just ignore the proposal part about using dashed color.

The only remaining request then would be to differentiate between
- `hw=footway` alias `hw=path + bicycle=no` and
- `hw=footway + bicycle=yes` alias `hw=path`

That is why I am asking to color the second one in gray.

**Comment by westnordost** [comment]
Thanks for the summary.

> hw=footway + bicycle=yes - color in gray dashed
> hw=footway alias hw=path + bicycle=no - keep in black

But I don't get it. This is #4669 all over again. I wrote previously that it is deliberate that `bicycle=no` and `bicycle=yes` are not distinguished.

**Comment by SLMapper** [comment]
Thank you. I think I also confused myself in the meanwhile. I somehow forgot about the whole "it is by purpose and people might not know what they are doing" thing and only thought about how I would imagine it to be. I apologize for this.

We also already discussed that there is no way to distinguish if "bicycle=yes" is signed or not. 
Maybe a new tagging could help, but maybe also the existing `traffic_sign` can be used - at least consistantly across the same country. But this would require a new quest (as you already mentioned). 
Of course this will not help right now, but having it as a quest could introduce it consistantly for the future. Maybe also editor presets should include/ask for it in this case.

As the "bicycle free" sign is very common (at least where I have been) I am searching for how to properly view and validate it along with other bicycle infrastructure. **My basic assumption is that a `bicycle=yes` on a footway either means there is a sign or it is wrongly tagged (e.g. should actually be a path or shared footway/cycleway)**.

Probably I have to use another tool (which would be unfortutate as for all other aspects SC fits very well). I am trying around with an overpass query with different coloring right now.

Do you have more ideas?

**Comment by westnordost** [comment]
`traffic_sign` doesn't really help because (a. we'd need the identifiers for all the countries and b.) there is no tag to denote that the particular `foot` and `bicycle` access restriction is not set due to a sign. So even a quest is out of question.

Yes, the bicycle free sign is very common in Germany. However, does it count as bicycle infrastructure? It is merely doing what is simply already legal/common elsewhere: Allowing bicycles on footways. And to be honest,
- cyclists will just use the sidewalk anyway even in lawful Germany if circumstances are convenient.
- technically, cyclists may only use the footway in "walking speed" with the "bicycle free" sign. Nobody does that, of course. But this somewhat diminishes the meaningfulness of that sign
- people knowledgeable in German (bicycle) infrastructure planning told me that the "bicycle free" sign is often used in situations where the traffic planners would like to keep bicycles off the roadway but the roadside footway is not broad enough to mandate a shared foot- and cycleway <img src="https://upload.wikimedia.org/wikipedia/commons/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg" width=24>, so they use instead the <img src="https://upload.wikimedia.org/wikipedia/commons/0/04/Zusatzzeichen_1022-10_-_Radfahrer_frei%2C_StVO_1992.svg" width=24> to at least indicate to cyclists that they "should" use the sidepath. In a nutshell: It is not a bicycle infrastructure, it is the utterance of the wish to keep bicycles of the roadway without actually providing any binding alternative.

**Comment by SLMapper** [comment]
Thank you for continuing to explain reasons against it to me.
Thank you also for doing a good job in cleaning up issues to keep the app simple and applicable to the whole world.
I see that my suggestion is not optimally fitting these needs right now.

Yes simply mouting a "bicycle free" sign is not be a good choice for bicycle infrastructure. And yes (as everywhere) some people are ignoring it or in reverse its absence. And yes it might partially not even be the best choice to follow its invitation to ride there ...
BUT the reality on the ground is full of it (as you acknowledged). And that is what we want to capture, don't we? The decision if to use it will be on e.g. the routers, not on the data collectors.

I love the bicycle overlay. For many situations it clearly shows data inconsistancy and missing data.
Today I validated* some bicycle routes in the city of Herrenberg. The city (and it's bicycle infrastructure) is not very big, but the "bicycle network" is very much fragmented between _advisory lanes_, _sharrows_, _shared paths_ ... and ... "bicycle free" on the sidewalk. 
So luckily I was able to [correct some of the mistakes and add missing data](https://osmhv.openstreetmap.de/changeset.jsp?id=130872355). However over and over I got frustrated, because one and another section had the "bicycle free" sign and I was unable to check (and correct) if it was reflected in OSM or not.

So, if it cannot be brought to the main SC app, @Helium314  is there a chance to add it into SC EE?

* by the way: do you have any idea how to use the bicycle overlay to mark everything somebody already validated to be correctly tagged (maybe adding last_check_date)?
Because validating bicycle infrastructure requires a decent amount of time (but is worth it) and so preserving validation status would be helpful to others (and yourself when not having to memorise it).

**Comment by westnordost** [comment]
> '* by the way: do you have any idea how to use the bicycle overlay to mark everything somebody already validated to be correctly tagged (maybe adding last_check_date)?

Not possible so far. I'll write a new issue soon in which I'll outline how a feature that enables this could look like so that it could be implemented by anyone interested.

**Comment by westnordost** [comment]
> So, if it cannot be brought to the main SC app, @Helium314 is there a chance to add it into SC EE?

I understand your troubles, but you really shouldn't ask Helium314 to add it to SC EE because the underlying issue is a tagging issue (no tag to denote if bicycle access restriction is due to a sign or implicit) which can't be solved by him but must be solved in discussion in the community.
If it was possible to distinguish via tags, it would be no problem to add it to the overlay.

**Comment by Helium314** [comment]
> So, if it cannot be brought to the main SC app, @Helium314 is there a chance to add it into SC EE?

What you can do in EE (if it's only a few sections) is using the tag editor for checking.
Otherwise there is the "custom overlay" which lets you highlight tag combinations, though obviously not while the bicycle overlay is active.

**Comment by SLMapper** [comment]
> no tag to denote if bicycle access restriction is due to a sign or implicit

I think the underlaying issue is that we have a different understanding of what `hw=footway` and `hw=footway + bicycle=yes` means.

My understanding (for Germany) is
- footway means there is a footway sign (or it is a sidewalk) - otherwise it should be tagged as `hw=path`, if needed with `bicycle=no` (_to me this is the actually problematic case where it is not clear if this restriction comes from a sign_) 
- `bicycle=yes` should always indicate that there is a "bicycle free" sign - otherwise it should either be tagged as `hw=path` or `bicycle=yes` is just a wish and not reality

I should ask the community if that is only my point of view or a general one.
