### ISSUE TITLE
New Quest: What cost to park here?

### ISSUE THREAD

**Issue by linux2good** [streetcomplete/StreetComplete#4720]
### General
Affected tag(s) to be modified/added: https://wiki.openstreetmap.org/wiki/Key:charge
Question asked: **What cost to park here?**
Currency code in charge tag will be automatically parsed by checking in which country this quest is located.
It would be also nice to add something similar but for toll roads.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
This quest should appear only after answering "Yes" to quest "Do you have to pay to park here?".

**Metadata needed:**

**Proposed UI:**
There is will be input box for a price and input box for a time, and currency sign after price input box. Currency sign will be automatically selected by app, and it will be uneditable.

**Comment by westnordost** [comment]
I find this tag a very bad idea. Charges changes all the time, the information is doomed to be somewhat wrong most of the time. Also, the amount paid is usually homogeneous for parkings administered by one city. Adding the same information a thousandfold would be somewhat spammy.

**Comment by matkoniecz** [comment]
I have serious doubts:

- pricing schemas are often extremely complex, depending on stay length, hour, day of week, vehicle type, various discounts, time of year
- this data changes often
- is anyone using this data?

**Comment by Helium314** [comment]
Maybe the quest could be limited to `access=customers`, so it would not be asked for city-regulated parking, but only for parkings that are likely to have different pricing.

**Comment by westnordost** [comment]
I am closing this because of:
- **IMO data about how much exactly something costs doesn't really belong into OSM**. It's really a bottomless barrel (of maintenance work) if we started doing that
- pricing schema can be complex -> needs complex UI
- information (can) often change
- no data consumer is using this data
- little interest in maintaining this data to be up-to-date
