### ISSUE TITLE
Cycleways can reverse direction when applying same selection to different ways

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#4722]
Add cycleways to a way such as the below:

![Screenshot_20230104-155535.png](https://user-images.githubusercontent.com/19356194/210487650-13e3b094-4d7f-4a60-9333-1fbc883bc796.png)

Then click a different way with a different orientation and SC offers the below suggested option:

![Screenshot_20230104-155712.png](https://user-images.githubusercontent.com/19356194/210487745-ff95e890-1a0b-446b-b8b4-9dfd19616e96.png)

Applying this option adds a lane to the left side of the road travelling in the opposite direction to traffic flow (in Australia):

![Screenshot_20230104-155525.png](https://user-images.githubusercontent.com/19356194/210488006-1da6973d-27da-4ae6-9bc8-e4b85cea1f20.png)

In fact, it tags the way with cycleway:left:oneway=-1

This is counterintuitive, and I notice this seems to only occur with the auto-complete.

Without carefully looking at the direction of the arrows could mean roads are being tagged with strangely aligned cycleways.

**Comment by westnordost** [comment]
I don't understand, what exactly is the issue?

**Comment by frankie2784** [comment]
Given the rarity of contra-flow lanes on regular roads, I propose that SC check the direction of suggested lanes so that they travel with traffic by default (left is always up, right is always down in Australia - opposite for Europe). i.e. SC should not auto-complete lanes in the contra-flow direction (unless requested by the user).

SC already provides a warning when trying to manually change the direction of the lanes (but it doesn't appear when auto-complete sometimes puts in a contra-flow lane):

![Screenshot_20230105-054402.png](https://user-images.githubusercontent.com/19356194/210628232-6806a032-57a4-4be6-9525-122bce2d3f6d.png)

In fact, you can see this warning pops up even when trying to change the lane to travel in the correct direction (the arrows in this case should be pointing up for standard left-side travel), which is also unnecessary.

**Comment by frankie2784** [comment]
> is it about lane being on left when filling it and then on the right when applying remembered selection?

No, it is that SC assumes the new lane is in the contra-flow direction (arrows on the left-side are down instead of up).

**Comment by frankie2784** [comment]
Here's another example:

![Screenshot_20230105-081051.png](https://user-images.githubusercontent.com/19356194/210650694-0fc4182e-9787-4520-8cf1-a56df5251e35.png)

SC suggests the "left" side as "up" in the above (correct). But when applied, actually puts the lane as "down" when viewed from the same orientation:

![Screenshot_20230105-081101.png](https://user-images.githubusercontent.com/19356194/210650734-7afb7af8-6069-45e5-b1d2-a3fe628d334c.png)

If I instead enter the cycleways manually, it now puts the lane arrow in the correct direction:

![Screenshot_20230105-081111.png](https://user-images.githubusercontent.com/19356194/210650834-cf299544-14f2-487f-84fd-80e3a5f75609.png)

I don't have an issue with the side of the road per se (there are obvious difficulties with showing which side is "left" and "right" with a more-or-less horizontally-aligned way). The main point is that if the lane is going to be applied to the north-side of the road, like the above, then it should assume that it is travelling east rather than west (again, this is for left-hand countries like Australia, Europe will be the opposite).

**Comment by westnordost** [comment]
I'd like to keep that button as dumb as possible. It fills in what it displays.

Any smartness that tries to guess the user's intention or guess how the road is supposed to look like with certain parameters is bound to be wrong some times and only contributes to its behavior regarded as inconsistent.

So,  do you have any suggestion on how to improve the behavior but stay consistent?

**Comment by frankie2784** [comment]
> I'd like to keep that button as dumb as possible. It fills in what it displays.
> 
> Any smartness that tries to guess the user's intention or guess how the road is supposed to look like with certain parameters is bound to be wrong some times and only contributes to its behavior regarded as inconsistent.
> 
> So,  do you have any suggestion on how to improve the behavior but stay consistent?

I would propose for simplicity that auto-complete should always assume that, for Australia, "left" is "up" and "right" is "down". That is, the bike lane should always follow the standard direction of traffic on each side of the road - it already does this when manually selecting lanes. The user can then choose to reverse any particular lane for rare exceptions to that rule.

**Comment by frankie2784** [comment]
> I'd like to keep that button as dumb as possible. It fills in what it displays.

In the case of the last example, it actually fills in the reverse direction of what it displays.

Clicking on this:

![Screenshot_20230105-081051~2.png](https://user-images.githubusercontent.com/19356194/210672745-62b46f97-5109-4398-9314-f3dab740467b.png)

Adds this:

![Screenshot_20230105-081101~3.png](https://user-images.githubusercontent.com/19356194/210672780-2d223c88-9b26-4168-930a-f4bd9cf325a6.png)

**Comment by westnordost** [comment]
So you say that the button should ignore any previously selected reverse direction and instead always display+apply the default direction?

If yes, why?

**Comment by frankie2784** [comment]
> So you say that the button should ignore any previously selected reverse direction and instead always display+apply the default direction?
> 
> If yes, why?

If it can also remember the previously chosen directionality then I guess that's fine too. However, reverse direction is exceedingly rare in real life, so it probably isn't a big deal to apply defaults every time. On top of that, applying defaults every time would safeguard against an accidental flip that goes unnoticed for multiple subsequent quests.

**Comment by westnordost** [comment]
> If it can also remember the previously chosen directionality then I guess that's fine too. 

What do you mean? Does it currently not remember that?

**Comment by frankie2784** [comment]
> > If it can also remember the previously chosen directionality then I guess that's fine too. 
> 
> What do you mean? Does it currently not remember that?

No it doesn't. That's the main issue I've been trying to get across (although it seems a couple of other related issues have emerged in this thread also).

See my first example. I tagged a cycleway manually, which added it in the regular direction of traffic flow (correct).

![Screenshot_20230104-155535~2.png](https://user-images.githubusercontent.com/19356194/210849096-e32eef1a-1580-4ebd-90ea-ddb68fb56f7a.png)

Then when I applied the "remembered" selection to the next way, for some reason it decided it was a contra-flow lane (incorrect).

![Screenshot_20230104-155525~2.png](https://user-images.githubusercontent.com/19356194/210849269-3cbbd387-671b-42a7-9bd8-98da20be72ee.png)

**Comment by westnordost** [comment]
Oh, now I get it. This is actually quite the nasty bug. Will fix it asap.

**Comment by westnordost** [comment]
This is actually pretty tricky to fix... the solution is a little bit dirty but at least does not result in a refactor that (just) makes everything more complicated.

the direction of the cycleway for the last answer button is now always rotated to what would be the default direction for any country.

**Comment by frankie2784** [comment]
Thanks for attending to this so quickly @westnordost. That's great.

There appears to be another tiny issue lurking here. I won't open another bug report, as this seems to be related?

Due to the previous issue, this way has been tagged as having two contra-flow lanes (instead of both flowing with traffic):
![image](https://user-images.githubusercontent.com/19356194/211222865-33d36b22-4781-45a2-84a9-4f8c53da6dc6.png)

This shows correctly in SC:
![Screenshot_20230109-094841](https://user-images.githubusercontent.com/19356194/211222933-8706f78b-d430-4fba-8b86-95ad2e59978a.png)

When I reverse these in SC:
![Screenshot_20230109-095001](https://user-images.githubusercontent.com/19356194/211223052-4a18df6f-ed30-49ba-8d5c-46820f19352e.png)

It does flip their direction in OSM, but it leaves these unnecessary "oneway" tags (it is a two-way street, so these tags represent just the regular flow on this road):
![image](https://user-images.githubusercontent.com/19356194/211223032-605b0cff-278c-4545-b5bd-edf8eef0ae36.png)

Not the biggest concern, but thought it was worth flagging this slightly untidy behaviour.

**Comment by westnordost** [comment]
StreetComplete deliberately does not remove explicitly set direction tags but just updates them if they are there. The consideration is that if the mapper previously cared enough to explicitly set the direction, he will have had a good reason to do this. In any case, the app should not remove any tags as long as they are not wrong. People get upset if an app automatically deletes (explicit) data, rightly so.

**Comment by frankie2784** [comment]
That makes sense. Thanks for clarifying.
