### ISSUE TITLE
Public transport quests for private platforms

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4723]
I get the shelter / tactile paving / lit / ... quests for a platform that is inaccessible to normal people and not part of a regular stop: https://www.openstreetmap.org/way/245311267
Should SC respect the `access=private` here and not ask?
Or is this some tagging issue, because `public_transport` could be interpreted as conflicting with `access=private`

**Comment by matkoniecz** [comment]
Is it some service platform in yards? In such case I would say that `public_transport = platform` is wrong, like putting it on freight train loading dock or train washing area would be.

**Comment by Helium314** [comment]
Not sure, it's quite narrow and barely suitable for other uses than accessing the other end of the train. The tracks next to the platform are definitely not part of the normal subway connections (and actually do have `service=yard` tag)

**Comment by matkoniecz** [comment]
Changed in https://www.openstreetmap.org/changeset/130861549 - looks like one more victim if iD editor asking to blindly "upgrade" tags (which got a bit better since that time)

**Comment by matkoniecz** [comment]
Though maybe `railway=platform` still triggers the quest? I admit that I have not checked this.

And https://wiki.openstreetmap.org/wiki/Tag:railway=platform?uselang=en is not really clear are only public transport platforms supposed to be tagged with this - which ideally would be clarified first before changing SC.

**Comment by Helium314** [comment]
> Though maybe `railway=platform` still triggers the quest? I admit that I have not checked this.

It's only 
```
          public_transport = platform
          or (highway = bus_stop and public_transport != stop_position)
```

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/219448424
on
https://de.wikipedia.org/wiki/Bahnstrecke_Ludwigshafen_Hbf%E2%80%93Ludwigshafen_BASF

is a real platform where you are only able to leave the platform if you are an employee of BASF.
