### ISSUE TITLE
Support nursing home

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#4725]
**Use case**
As a user I want to be able to select nursing home in the type of building meny

**Proposed Solution**

**Comment by matkoniecz** [comment]
is nursing home a distinct architectural style?

note that this quest asks not about business/amenity in a building, but about building type (and for example if there would be church operating in apartment building then answer would be "apartments", not "church")

**Comment by dpriskorn** [comment]
Oh. Then I might have misunderstood the task. The complex of buildings house apartments, a pool and common areas.

**Comment by mnalis** [comment]
Perhaps we should improve on wording; e.g. instead of _"What **kind** of building is this?"_ ask _"What **style** of building is this?"_

**Comment by westnordost** [comment]
Anyway, if you are not sure about `apartments`, you can simply select `residential`. We cannot add a special building value as selectable option for every kind of facility.

**Comment by dpriskorn** [comment]
residential sounds perfect. My tag knowledge is a little rusty these days and the interface is in danish and that doesn't really make it easier. 😅

**Comment by HolgerJeromin** [comment]
Or optimize the localization of the app :)
https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app
