### ISSUE TITLE
Support incrementing based on last committed house nummer with only numbers or number and letter

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#4726]
**Use case**
As a user I want to add house numbers without using the inbuilt android keyboard which sucks for this task

After committing "13a" the up and down arrows do not work. 
I would like them to work by stripping off the letter and doing the in/decrement 

**Proposed Solution**

**Comment by matkoniecz** [comment]
> inbuilt iOS keyboard

how you managed to run it on iOS?

**Comment by westnordost** [comment]
> After committing "13a" the up and down arrows do not work.

They do work in exactly the manner you described. Just tested. Please clarify what exactly does not work. A video might help.

**Comment by dpriskorn** [comment]
Oh. Okay. What about 13a-e, does that also strip everything but the number and increment?
What about 13-15 could we make that strip -15 and use the first number as a base always?

We could add an introduction educating the user how it works if necessary.

**Comment by letypequividelespoubelles** [comment]
>does that also strip everything but the number and increment?

In #4718 for India we do not want to stripe everything but the number. For exemple, we want that after B-46 with the increment we have B-45 or B-47.

**Comment by dpriskorn** [comment]
Oh. Good point. We could make the rules culture configurable. So in scandinavia we use one configuration and in Bahrat another. 
The app uses GPS so it could suggest a ruleset based on that

**Comment by letypequividelespoubelles** [comment]
Yes, maybe a standard configuration based on GPS is nice, plus the possibility to modify it ? The trick will be to have an easy and comfortable UX though.

**Comment by westnordost** [comment]
> Oh. Okay. What about 13a-e, does that also strip everything but the number and increment?
What about 13-15 could we make that strip -15 and use the first number as a base always?

It's 12 if you press - and 16 if you press +.
14 if you press + would make little sense.
