### ISSUE TITLE
Less zealous "checked on-site" dialogue 

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#4727]
When using Streetcomplete from a passenger seat I often find I am prompted as to whether I have really checked something on-site despite having just seen it.

**How to Reproduce**

Use Streetcomplete to answer questions from a moving vehicle, only selecting the quest after you pass it. Often despite having just seen a feature a prompt will open to interrogate the user about whether they checked in person.

Typical examples: 

- user has just passed a street that was lit, but is shown as unknown in the overlay
- user accidentally tapped the wrong quest and had to cancel and reselect the correct quest prompting the "you're too far" sreen

**Expected Behavior**

Now that a trace is shown for recent history I would expect all features within range of the last ~2-5s of travel to be within the boundary for "user has probably just seen this" and not trigger a prompt.

**Versions affected**

Versions to 50.1.

**Comment by Helium314** [comment]
What about clicking "don't show again for this session"?

**Comment by letypequividelespoubelles** [comment]
> What about clicking "don't show again for this session"?

I click on it almost every SC session, I agree with @InsertUser it's bothering.

**Comment by rhhsm** [comment]
I'm in favour of not asking this of experienced users (above a certain no. of stars or above a certain "Surveyor" level); it's really annoying...

**Comment by westnordost** [comment]
Yes, it would be possible to improve this behavior by looking not only at the position of the user at the time he solves this quest but also check if the quest was near it previously (during the last X minutes at least). It may be computationally expensive though to check the distance of thousands of points to the selected road, so some optimization (at least bbox checks) would be in order.

Also, it may be necessary to more persistently save the users' GPS track, maybe even on disk (i.e. in the database). Currently, it is just saved in the UI.

I previously mention that here: https://github.com/streetcomplete/StreetComplete/issues/4582#issuecomment-1297451867

**Comment by westnordost** [comment]
I marked it as an enhancement but I myself am not bothered so much about that dialog that I can hide for this session after a few clicks enough that I will ever go through the effort of implementing this.

**Comment by rhhsm** [comment]
I agree that this is not a problem worth spending much time on with fancy position tracking. However I do think that it should be assumed that after the dialogue has been shown X times to a user with a certain level Y of experience, that user has learnt something (or will never learn). Continuing to show it is annoying and an insult to the honesty of the user :)

**Comment by mnalis** [comment]
IDK... While I do count myself as experienced mapper, the warning has been useful to myself several times for stopping me editing wrong element (I often move and zoom map around).  Sure, sometimes (when in fast moving vehicle), it will needlessly warn about area where I was just a few dozen seconds ago.  In such cases, I _do_ skip it for a session (and do not find it as a problem). 

However, in majority of cases I'm on foot (as SC is [primarily supposed to be used](https://github.com/streetcomplete/StreetComplete/pull/4188)), and I only skip that specific warning, not whole session (and that only after verifying I am indeed answering correct element - e.g. by zooming out / panning) - even if I have to do it several times in a session.

**Fancy position tracking would indeed be best solution that would make both side happy**, but it as noted likely too much work for too little gain. Having a preference to turn off that warning, but which is only available to experienced mappers, is probably only marginally less work.

**Comment by InsertUser** [comment]
I did have a dialogue the other day where there was no tick box for no more propltsh this session, maybe that only appears after the second appearance.

> It may be computationally expensive though to check the distance of thousands of points to the selected road, so some optimization (at least bbox checks) would be in order.

> Also, it may be necessary to more persistently save the users' GPS track, maybe even on disk (i.e. in the database). Currently, it is just saved in the UI.

For what it's worth I was only really thinking of a minute at most. I didn't think the GPS rate was high enough to be more than ~ 60 points if they were all checked? If they're not stored in a place that is convenient for further processing though then it sounds like it's more trouble than it's worth.
