### ISSUE TITLE
Bicycle overlay: shared_lane not displayed when without pictogram

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4728]
**How to Reproduce**
See https://www.openstreetmap.org/edit?way=1082205731
Tags:
```
cycleway:left=lane
cycleway:right=shared_lane
```
shows up in "missing" red.

**Expected Behavior**
cycleway:*=shared_lane should be sufficinent to show up in orange dashed.
[wiki ](https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dshared_lane) says
> it **can** additionally be tagged with [cycleway:lane](https://wiki.openstreetmap.org/wiki/Key:cycleway:lane)=pictogram

**Versions affected**
SC 50.1

**Comment by SLMapper** [comment]
By the way I think `cycleway:*:bicycle=designated` is not correct for sharrows (also not for advisory lanes) as currently present here: https://www.openstreetmap.org/way/30073084

Should SC remove this when changing type to sharrow or advisory lane?
(tag was manually added in https://www.openstreetmap.org/changeset/91233650)

**Comment by westnordost** [comment]
This is deliberate. 

Also, one issue for every issue.

**Comment by SLMapper** [comment]
Sorry, I linked the wrong way: Correct one is:
https://www.openstreetmap.org/way/326115425

Why should it deliberately be not shown? There are currently [2709 ](https://overpass-turbo.eu/s/1pJA) of them in Germany.

**Comment by westnordost** [comment]
Because it is ambiguous.
