### ISSUE TITLE
Checking public telephones in Germany

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#4733]
### General
Deutsche Telekom plans to shut down all remaining public telephones until February 2023, and remove them all in the next two years or so. This could be an adaptation of the existing »check existence« quest, mainly to be able to hopefully adjust the database quickly to all those being gone or non-functional within a fairly short time span. Differences from the existing quest would (or could) be:

- Specific answer that also allows to tag non-functional status (disused prefix)
- Perhaps an increased resurvey interval, as the expectation is that removal could happen just a few weeks after last survey or so.

This could be a special quest in a specific region (I think that's possible already) for a somewhat limited time to help clear up data quickly. If that's out of scope here, no worries. I just thought it was worth a try.

Edit: Thinking about this, a possible other way to check this would be a MapRoulette challenge for all those telephone boxes near recent Mapillary / Kartaview images. But that depends on recent street-level imagery and won't be feasible for a few months at least, I guess.

Affected tag(s) to be modified/added: [amenity=telephone](https://wiki.openstreetmap.org/wiki/Tag:amenity=telephone)
Question asked: **Does this public telephone still exist?**

Answers:
- No, it's gone completely.
  - Change tag to removed:amenity=telephone (or remove element, although I think that's usually not done from SC)
- Yes, but it doesn't work anymore.
  - Change tag to disused:amenity=telephone

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  - This _may_ not apply, as the expectation is mainly that eventually for almost all POIs the answer will be that they're gone
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
  - 15300 nodes (amenity=telephone in Germany). Considering that Deutsche Telekom notes that only 11k are still operational, there seem to be quite a few that are defunct or gone already, anyway.

### Ideas for implementation

**Element selection:** [This](https://overpass-turbo.eu/s/1pJM) overpass query is a likely starting point. Perhaps limited to those where operator is Deutsche Telekom or empty.

**Comment by matkoniecz** [comment]
Are there public telephones in Germany not operated by Deutsche Telekom? For example on airports?

**Comment by ygra** [comment]
> Are there public telephones in Germany not operated by Deutsche Telekom?

There likely are, but I don't know how prevalent. Deutsche Telekom was required to operate and offer public telephone service until – I think – a few years ago. This was back from the time when it was still state-owned. Since the profit margins are likely slim to non-existent, I'm not sure how many other operators there are. But in niche applications there surely would be some, I guess.

> Are Deutsche Telekom public telephones in Germany in general marked as such?

They tend to look like this these days, but I'm sure closed forms remain in use as well: https://www.teltarif.de/img/i/i_telefonzelle-2ab.jpg

The magenta and capital T is typically very visible. They also don't operate on coins anymore for a while, only with special pre-paid cards that only work for that operator, so the operator must be visible to the user anyway, I guess.

I can take some detail pictures later, presuming the only phone box in this village isn't gone already.

**Comment by westnordost** [comment]
There is already a quest for that. The existence of public telephones is already checked every 2 years. In the app settings, you can dial that down to 1 year (Resurvey intervals -> "Ask more often").

It would be too much effort to add a new quest for this just to be about 0.5 to 1 years faster in updating the situation on-site.
