### ISSUE TITLE
"Do you have to pay to park here?" showed when parking has `access=customers` tag

### ISSUE THREAD

**Issue by linux2good** [streetcomplete/StreetComplete#4737]
Like in title. I also saw some changesets made with StreetComplete that adds `fee` tag on parking that has `access=customers` tag.

**How to Reproduce**

Go to parking that has `access=customers` tag

**Expected Behavior**

Do not show "Do you have to pay to park here?" when parking has `access=customers` tag

**Versions affected**

50.1

**Comment by westnordost** [comment]
Fee and customers only is not mutually exclusive

**Comment by westnordost** [comment]
I mean, it is very common that they are mutually exclusive. But it is in no way not possible or conceivable.
