### ISSUE TITLE
Current beta from appstore not installable 

### ISSUE THREAD

**Issue by MaestroGlanz** [streetcomplete/StreetComplete#4738]
Android is up to date, 4gb free space, app downloads in appstore, installation fails. 

Android 11.0.9.BE83BA

Might be a system issue. I'm not sure.

**Comment by westnordost** [comment]
Anyway, it is installable for me. If you used the app from F-Droid before, you need to first uninstall the app from F-Droid before installing from github or google play because the signatures are different.

**Comment by MaestroGlanz** [comment]
So, this has no effect:![Screenshot_20230107-201504_1.jpg](https://user-images.githubusercontent.com/27563281/211166922-0b47d103-47f6-4e7a-bb50-4b4b66d778cd.jpg)

**Comment by MaestroGlanz** [comment]
F-droid fails also. But if I check the version in the app, it says 50.1. But it still offers me to update.

**Comment by westnordost** [comment]
Update to what?
