### ISSUE TITLE
Bicycle parking shed with roof missing

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#4739]
**Use case**
As a user I want to have a new category "For bicycles" so I can easily find jicycle building types

**Proposed Solution**

**Comment by matkoniecz** [comment]
"Bicycle parking shed with roof missing" - where you want to see it? Because that does not seem to be a building or even shed to me.

**Comment by Helium314** [comment]
It took me a while, but I guess it's supposed to mean: _"Bicycle parking shed with roof" missing_

@dpriskorn if you want a new category, it would be very helpful to know which building types you expect there? A category for just one building is definitely not useful.

**Comment by matkoniecz** [comment]
"Bicycle parking shed" is just shed in building quest - is there some deep architectural difference between bicycle parking shed and a regular shed?

**Comment by matkoniecz** [comment]
And bicycle parking type quest has shed already as type.

Maybe it would be nice to have bicycle parking overlay like shop overlay to mark missing ones...

**Comment by dpriskorn** [comment]
Can I enter first shed/roof in the building quest and that unlocks a new quest asking what type of shed/roof and I can choose bike parking?

**Comment by Helium314** [comment]
You can suggest a new quest, but I have doubts it will be eligible. See the checklist when opening a new issue/quest suggestion, especially _Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)_.

**Comment by matkoniecz** [comment]
> Can I enter first shed/roof in the building quest and that unlocks a new quest asking what type of shed/roof and I can choose bike parking?

no, right now if there is just `building=yes` mapped then it will not ask about bicycle parkings.

Right now you can map bicycle parking itself with some other mapping tool.

**Comment by dpriskorn** [comment]
I closed it since what I wanted is not a good fit for this tool. I'll continue using notes to add bicycle parking.
