### ISSUE TITLE
Add 'previous choice' option to Street lit overlay

### ISSUE THREAD

**Issue by thibaultmol** [streetcomplete/StreetComplete#4741]
**Use case**
Currently if you're doing a bunch of the "is this street lit?" Entries; it is requiring more clicks than I feel like it should be doing

**Proposed Solution**
I think similar to the quest where you have to select every Street has a cycle way; there should be a button when you're trying to answer the streetlights quest in the bottom left corner with the last answer you gave. That would half the amount of taps

**Comment by westnordost** [comment]
Huh? But the answer can only be yes or no. How would a "last answer" button help? The "yes" and "no" answers are already displayed!

**Comment by thibaultmol** [comment]
Sorry, I'm referring to this quest

![Screenshot_20230109_053737_StreetComplete](https://user-images.githubusercontent.com/1010226/211241939-2c0a3373-6dc2-49a7-afa3-600bd0687b86.jpg)

**Comment by rhhsm** [comment]
#4640 #4622 I still think that showing the 4 options next to each other immediately after selecting a way is best, with the current value or the previous choice highlighted.
![image](https://user-images.githubusercontent.com/69100427/211291285-36ddf965-24cf-4bb2-85f6-48f569c65d3c.png)

**Comment by westnordost** [comment]
Makes sense and is easy to implement. As always, PR is welcome.

Of course this should be implemented in the `AImageSelectOverlayForm` so that all overlay forms with the same UI will profit from that. (Currently only lit and the separate cycleway form, but also upcoming surface form)

**Comment by westnordost** [comment]
On the other hand, it is only one tap saved. Not sure if this is worth the extra UI clutter. I dimly remember that I once marked a similar feature request as will not fix.

**Comment by thibaultmol** [comment]
It is only one click. But if you're marking a bunch of streets all after each other... It starts up get really annoying, that extra click

**Comment by matkoniecz** [comment]
Depends on how segmented streets and sidewalks are. In my area I often need to stop and stand to input everything.

And when surface is also missing and `highway=steps` quests are not solved...

https://www.openstreetmap.org/#map=18/50.07567/20.04641

![screen](https://user-images.githubusercontent.com/899988/211304183-fc910e82-b46c-46ed-8761-0aab390055b8.png)

**Comment by thibaultmol** [comment]
In some places a road can be split into quite a lot of sections due to
surface type, if it's a traffic calming table, separate lanes etc. So one
location can just have a lot of way objects

**Comment by westnordost** [comment]
Fair enough.

**Comment by rhhsm** [comment]
> On the other hand, it is only one tap saved.

It is 50% taps saved :)

**Comment by HolgerJeromin** [comment]
>  I dimly remember that I once marked a similar feature request as will not fix.

linked here:
https://github.com/streetcomplete/StreetComplete/issues/4741#issuecomment-1375424771

**Comment by michalgwo** [comment]
Maybe it will be better to remove the drop-down menu/dialog? If we make it possible to choose an answer directly without a drop-down menu/dialog, we won't need the 'previous choice' option.

What I mean is:
<img width="200" alt="Screenshot_2" src="https://user-images.githubusercontent.com/114614618/217633771-b97375f0-4c18-4859-b8ab-42974afaca72.png">

This is how it looks now:
<img width="200" alt="Screenshot_1675884557" src="https://user-images.githubusercontent.com/114614618/217633764-5434ed32-8438-41fd-a57c-e67b8320be9b.png">

**Comment by westnordost** [comment]
This was proposed before and rejected.

**Comment by rhhsm** [comment]
> This was proposed before and rejected.

That it is proposed again and again shows how annoying the present UI is...

**Comment by qugebert** [comment]
I would try on this next.
@FloEdelmann can you assign this to me, please?
Just one question: For the streetsidepuzzle-overlay there is a seperate ..controller-class. Should i keep this consistent and do it the same way or ist it okay if i put all code in the AImageSelectOverlayForm? (as it not as complex than the streetsidepuzzle)

**Comment by FloEdelmann** [comment]
I'd say if it's not that complex, then putting it in `AImageSelectOverlayForm` is fine. If it turns out to be too much code, it can still be extracted into a controller afterwards.

**Comment by westnordost** [comment]
For the (pre-draft - it is a branch) buildings overlay, I also considered refactoring the `AImageSelectOverlay` into a controller class, but at least to share functionality (which is the purpose of these controller classes), it didn't seem worth it to me.

**Comment by westnordost** [comment]
Are you working on this, @qugebert ? If not, I'd like to take this.

**Comment by westnordost** [comment]
Ah, well. Okay, then I take this over, thank you!
