### ISSUE TITLE
Significant changes hidden under the changeset "Add vegetarian diet type"

### ISSUE THREAD

**Issue by maro-21** [streetcomplete/StreetComplete#4743]
https://www.openstreetmap.org/changeset/110184031
Here a user modified two nodes:
- [6335821268](https://osm.mapki.com/history/node/6335821268): added `diet:vegetarian=yes` which is ok
- [6123853860](https://osm.mapki.com/history/node/6123853860): removed all tags from `amenity=fast_food` and added `amenity=restaurant`

The changeset comment should be different here because changing the whole POI is not just adding `diet:vegetarian=yes`, or there should be separate changesets.

Moreover, when you look into https://osm.mapki.com/history/node/6123853860, this changeset added version 3 and 5 of this node, but version 4 was added in a different changeset! Which makes achavi unable to display these changes: https://overpass-api.de/achavi/?changeset=110184031 (Let me know if this should be a separate issue)

I thought I could trust StreetComplete changeset names and don't check such minor changes as addding `diet:vegetarian=*`...

**Comment by matkoniecz** [comment]
In this case user ot vegetarian quest and select option "this place is gone" and retagged it.

Previously raised in #4187 - note that nowadays message will be different, see https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/diet_type/AddVegetarian.kt#L28

**Comment by matkoniecz** [comment]
@maro-21 Do you think that new edit description solves the problem?

**Comment by westnordost** [comment]
In any case, the way StreetComplete works, it is not possible to put changing the type of place (because the old place does not exist anymore) as response to whether a place serves vegetarian food or not into a disjunct changeset. And personally, I think this is the correct / expected behavior. See the linked #4187

**Comment by FloEdelmann** [comment]
Is it maybe possible to add the following additional information to the changeset comment dynamically?

* changeset contains split ways
* changeset contains replaced shops

**Comment by maro-21** [comment]
> @maro-21 Do you think that new edit description solves the problem?

No. Both "Survey whether places have vegetarian food" and "Add vegetarian diet type" mean the same to me. And if something else was changed, like closing a closed restaurant, it should be mentioned it the changeset comment or be split into two changesets.
