### ISSUE TITLE
Traffic lights sounds in Spain

### ISSUE THREAD

**Issue by paunofu** [streetcomplete/StreetComplete#4745]
**Use case**
At least in Spain, traffic lights sounds can be turned on with a remote control or with Bluetooth, so not always is sounding, only when requested. Not always is easy to answer if the traffic light has sound for blind people, especially if you don't know this information.

**Proposed Solution**
Maybe add a advise saying this. "Take care that some traffic lights do not always sound and they turn on with a remote control or Bluetooth. If the traffic signal is like this [2 images] it sounds"

![image](https://user-images.githubusercontent.com/94412187/211796433-07e2dfda-a185-4e4e-9dd8-dbaa4faa0f91.jpeg)![image](https://user-images.githubusercontent.com/94412187/211796453-22188cff-d3a7-4f8e-a7ec-f133d026b1c6.jpeg)

The images are examples, I can give better ones if the proposal is accepted.

**Comment by rhhsm** [comment]
Is this something specific for Spain? I've never seen such traffic lights. Maybe it would be sufficient to add an explanation to the translations of this quest description in the languages used in Spain (Spanish, Catalan, Basque, etc.)?

**Comment by paunofu** [comment]
Well, the bluetooth system I don't know if outside of spain exists, but the remote control is also used in France and maybe in other european countries

**Comment by mnalis** [comment]
Some possible workarounds (multiple can be applied if needed):
- change Spanish translation to cram that information in there. (No pics in that case, obviously. Can refer to FAQ though?)
- add description to all languages indicating possible problems with the quest
- disable the quest in Spain if it causes significant mistagging problems there 
- disable the quest by Default (but still allow it to be enabled after displaying such warning)
- discuss on [tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list) how such differences should be tagged, and when it is approved provide extra SC answers for new possibilities (i.e. change it from yes/no quest to _"pictures with descriptions"_ (like `surface quality`) quest.

**Comment by paunofu** [comment]
1. Changing the translations of the languages spoken in Spain it would be the fastest thing

2. Adding a description and disable by default is the best option in order to avoid misstaging. Adding a description is useful especially for the other countries that is also not sounding always.

3. My intention is to ask the mailing list, but first I'm asking the Spanish community in order to get information about all the country. Provisionally I'm using traffic_signals:sound:remote_operated= remote_control/bluetooth

https://overpass-turbo.eu/s/1qck

**Comment by westnordost** [comment]
Just the description should be updated (for all languages) to make it clear that user should look for a speaker, not for a button.

**Comment by mnalis** [comment]
(somewhat related recent OSM forum discussion: https://community.openstreetmap.org/t/button-operated-traffic-signals/7752)

**Comment by westnordost** [comment]
> (somewhat related recent OSM forum discussion: https://community.openstreetmap.org/t/button-operated-traffic-signals/7752)

I am time and again astonished by the lack of awareness by community members about that you cannot just redefine an in-use tag to what it "should" mean.
