### ISSUE TITLE
Quest disappears after POI is moved

### ISSUE THREAD

**Issue by ivanbranco** [streetcomplete/StreetComplete#4746]
I noticed a POI with a "opening hours" quest available, but I wanted to fix it's location before replying to the quest. I clicked the falafel icon and then "It's in a slightly different position" and moved the object. The quest disappeared.

I would expect the quest to remain active even after the POI is moved.

StreetComplete v50.2

**Comment by Helium314** [comment]
It's a resurvey quest, which only appears because the element element wasn't modified for a longer time. Moving a node changes the last edit date, so survey is not seen as necessary any more.

Just do it the other way round: answer the quest, and then move the shop.

**Comment by westnordost** [comment]
I see no way to resolve this unless StreetComplete would always record `check_date:opening_hours` and not only if the opening hours did not change since the last time visited or it is already set.  The last time I asked around in the community (2020) whether this is desired, most people tended to agree on that such `check_date:*` tags should only be used if necessary.

**Comment by mnalis** [comment]
> Just do it the other way round: answer the quest, and then move the shop.

Hmmm, if he answers the quest first, the quest will disappear as solved, would it not?
And if there is not quest showed anymore (as it is now solved) , how would he be able to click on it (in ordet to choose `It's in a slightly different position` ) ?

> I see no way to resolve this

One idea would be that SC does not change the timestamps of objects in memory (i.e. they should be changed only in upload phase and forgotten afterwards). Than any change made / quest solved in the current app session would not impact any other quest inside same session (unless user selected "flush" or "manual scan"). 
That would need however probably need reworking a significant amount of code (i.e. anything that updates object timestamp or `check_date:*` tags would need to moved to different place), so is probably not likely :cry:

**Comment by ivanbranco** [comment]
> And if there is not quest showed anymore (as it is now solved) , how would he be able to click on it (in order to choose `It's in a slightly different position` OtherAnswer ) ?

In the "Shops" layer you can click on every shop (even with no active quests) and move them.

**Comment by mnalis** [comment]
> In the "Shops" layer you can click on every shop (even with no active quests) and move them.

Ah, true. It does seems quite a bigger chore (especially if one currently uses other overlay). 
Not to mention  that (especially) the target users of SC might be quite confused by such strange workflow being required for something which for those unfamiliar with codebase _"should just work"_...

**Comment by Helium314** [comment]
@mnalis I had considered not changing the timestamp when moving a node, so resurvey would still work in offline mode, but I decided against it.
Not 100% sure why, but either it was some unexpected problems, or that the existence quest should not be asked again after moving a node, implicitly confirming existence.

**Comment by riQQ** [comment]
Couldn't StreetComplete mark elements internally as "should be resurveyed disregarding timestamp" non persistently, i.e. only until it is terminated / restarted.
This flag could be used in the condition for all resurveys besides existence (as existence is confirmed by changing anything else and not selecting 'doesn't exist anymore ' as Helium324 already said).

Too complex?

**Comment by mnalis** [comment]
> I would expect the quest to remain active even after the POI is moved.

Just to note, that it actually works (at least in SC `v51.1`) if you have auto-upload **disabled**. You can first move the POI, and then answer its quest, e.g.

https://user-images.githubusercontent.com/156656/227715598-e88d60c8-d990-4e11-89ea-ea53cd1753a1.mp4
