### ISSUE TITLE
Opening hours | By Appointment

### ISSUE THREAD

**Issue by MaFarine** [streetcomplete/StreetComplete#4748]
**Use case**
When filling opening hours, I encountered some shops that are opened only by appointment but I cannot fill that value.

**Proposed Solution**
Add an option that allow to set by appointment.
It could be the whole day or by appointment between certain hours.

**Comment by rhhsm** [comment]
You can select "No regular opening hours…" and then enter "By appointment" in the next dialogue.

**Comment by matkoniecz** [comment]
Note also that SC will never able to tag all possible opening hours, some will be really complex (nearby monastery has for example different opening hours for male and female tourists)

**Comment by MaFarine** [comment]
> You can select "No regular opening hours…" and then enter "By appointment" in the next dialogue.

Welle that does work if it is **only** by appointment but some days are and others arent.

In that case I'll only put the defined opening hours :)

All the best!

**Comment by matkoniecz** [comment]
> but some days are and others arent.

In such case you will need to use option to leave note - or fill well defined ones and create a note (long tap on map) about extra appointment only ones
