### ISSUE TITLE
Quest suggestion: Is this grit bin here the whole year?

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#4749]
### General
Affected tag(s) to be modified/added: [seasonal](https://wiki.openstreetmap.org/wiki/Key:seasonal)
Question asked: **Is this here the whole year?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
  → `seasonal` tag is established, but not widely used on `amenity = grit_bin` yet
  → can be used to re-enable #2726 for non-seasonal grit bins
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  → survey is necessary with at least half a year in between. That's why the quest should be disabled by default, like the indoor/outdoor seating quest
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  → not sure, might be depending on the area, see https://overpass-turbo.eu/s/1q7A
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
  → yes, see https://overpass-turbo.eu/s/1q7z

### Ideas for implementation

**Element selection:** `amenity = grit_bin and !seasonal`
**Proposed UI:** Yes/No quest form
**Quest icon:** Maybe a calendar, similar to https://www.svgrepo.com/svg/362042/calendar-clock

### Related issues

* #2726
* https://github.com/streetcomplete/StreetComplete/issues/2744#issuecomment-885065544
* https://github.com/streetcomplete/StreetComplete/issues/3943

**Comment by westnordost** [comment]
What do you need grit bins for outside winter? In other words, how would this information be useful?

**Comment by FloEdelmann** [comment]
Basically only to enable the "check existence" quest, at least for grit bins that are there the whole year.

**Comment by matkoniecz** [comment]
> In other words, how would this information be useful?

This allows local mappers who remember winter(s) when bin was there and summer(s) when it was gone to tag that it is seasonal, what in turn reduces risks that less local mapper will delete seasonal grit bin during summer.

**Comment by westnordost** [comment]
> what in turn reduces risks that less local mapper will delete seasonal grit bin during summer.

Then, why not only ask for the existence of grit bins that are not seasonal?

**Comment by matkoniecz** [comment]
> Then, why not only ask for the existence of grit bins that are not seasonal?

This applies not only to SC users, but also to other mappers.
