### ISSUE TITLE
SC asks me if a vacant shop is the same shop

### ISSUE THREAD

**Issue by ivanbranco** [streetcomplete/StreetComplete#4752]
In the "Shops" layer, if I click "It's vacant", StreetComplete asks me if the shop is still the same shop or a different one, as when you rename a shop. In this case tho I find it quite confusing, also because both choices seems to have identical effects.

I think it shouldn't ask that question 
or
it could ask "Is the name still visible?" (as suggested in the [disused:* wiki page](https://wiki.openstreetmap.org/wiki/Key:disused:*): _"It no longer has an operator as such - no beer is sold - but the name is still useful for navigation."_) and keep/delete the name=* based on the reply.

StreetComplete v50.2

**Comment by Helium314** [comment]
> both choices seems to have identical effects

Actually answering that it's the same shop only removes the name and sets the shop type to vacant, without any other tag changes. Best would be to just not ask, and properly set it to vacant.
