### ISSUE TITLE
bicycle parking type "bollard" not offered

### ISSUE THREAD

**Issue by brunnerpaul** [streetcomplete/StreetComplete#4755]
From https://www.openstreetmap.org/note/3519463

> Unable to answer "What type of bicycle parking is this?" for https://osm.org/node/9264905329 via StreetComplete 50.2:
Type is bollard which is sometimes tagged as stands though. Bollard is currently not given as an option in StreetComplete.
> 
> https://westnordost.de/p/128498.jpg
>>>

Are users expected to use the type "stands" instead?
The example images for "stands" and "bollard" are more similar than their text descriptions, see https://wiki.openstreetmap.org/wiki/Key:bicycle_parking.

**Comment by Helium314** [comment]
Duplicate of #1202? Or has anything changed since then?

**Comment by brunnerpaul** [comment]
Thanks for pointing that out, #1202 has all the relevant points. Will close here and reopen there as that issue had the "feedback required" tag for a while.
