### ISSUE TITLE
Is this pharmacy dispensing prescription drugs?

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4759]
### General
Affected tag(s) to be modified/added: [dispensing=yes/no](https://wiki.openstreetmap.org/wiki/Key:dispensing)
Question asked: **Is this pharmacy dispensing prescription drugs?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose. 
  Yes, over [140k uses](https://taginfo.openstreetmap.org/keys/dispensing#overview), and it is useful to know where you can get your prescription drugs.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary. 
  Yes. At least in Croatia, pharmacies that are authorized to sell prescription drugs announce that on the outside doors (along with opening hours etc.) 
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam). 
  According to [taginfo](https://taginfo.openstreetmap.org/keys/dispensing#values) , about 6% are `no`, but in reality many that should be `no` do not have this tag at all. Judging by personal experience, I'd say about 30% are `no` in Croatia .
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort). 
  Yes, over [360k amenity=pharmacy](https://taginfo.openstreetmap.org/tags/amenity=pharmacy)

### Ideas for implementation

**Element selection:** `amenity=pharmacy` or `healthcare=pharmacy` without `dispensing=*`.

**Metadata needed:** [Taginfo map](https://taginfo.openstreetmap.org/keys/dispensing#map) shows pretty wide distribution of the key, so I'd guess wordwide would be fine.

**Proposed UI:** simple yes/no quest.

---

Should be a good and simple choice for new wannabe-quest writers wanting to try writing a [new quest](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md). It's easy and straightforward, and can be done by copy/pasting from similar quests even if you don't know Kotlin (and even if don't program at all).
 
(Otherwise, if nobody else wants to try it, I can write it.)

**Comment by matkoniecz** [comment]
In which countries this distinction exists? AFAIK it does not in Poland.

**Comment by westnordost** [comment]
I don't understand the wiki description. Dispensing prescription drugs? Like, automatically? Or is it about that they offer prescription drugs at all? If the latter, what pharmacy does not offer prescription drugs? Would that not rather be a `shop=chemist` then?

**Comment by HolgerJeromin** [comment]
ref https://wiki.openstreetmap.org/wiki/Talk:Key:dispensing for more people (for example a well known Mateusz) confused by this tag.

**Comment by rhhsm** [comment]
I guess the number of countries where the distinction between dispensing and non-dispensing pharmacies exist and where this can be surveyed from the outside is very limited (I had also never heard of it). So far only Croatia? It should not be asked in Germany, the Netherlands, Denmark, Bulgaria, ...

**Comment by mnalis** [comment]
> In which countries this distinction exists? AFAIK it does not in Poland.

Well, taginfo for [dispensing=no](https://taginfo.openstreetmap.org/tags/dispensing=no#map) does seem to show it all around Europe :shrug: perhaps people can take a look into their own countries and make a sense of where/why it is mapped as such if it was not possible/intended?

> Or is it about that they offer prescription drugs at all? If the latter, what pharmacy does not offer prescription drugs? (Isn't that the very definition of pharmacy?) Would that not rather be a shop=chemist then?

Yes, it's about selling them at all (not about vending machines). I dunno, for me `shop=chemist` would be things like [dm-DrogerieMarkt](https://www.dm.de/), herbal medicine shops etc. If the naming "Apoteka" and offering between two pharmacies is 95% the same, I would not mark one as `shop=chemist` and another as `amenity=pharmacy` (maybe I should? Those wiki definitions seem to keep changing every time I look at them...)

To clarify, the difference in Croatia is:

- while **any** pharmacy will sell you popular stuff like cold remedies or painkillers based on ibuprofen and the like without any prescription (so say 95+% of the stuff they sell?), only those pharmacies with contracts with national health ministry are allowed to sell **certain groups of drugs** (say, heavy-opioid-based or other addictive/dangerous drugs), and then only on government-approved prescription (i.e. `dispensing=yes`) after you identify yourself.
- those that are `dispensing=yes` (i.e. only ones that will sell you **any and all** stuff on digitally signed / approved prescription) also give the customer heavy discounts or even free on those prescriptions (e.g. 50-100% off; the rest of the bill being payed transparently by the health ministry, which is digitally connected to such pharmacies, in order to allow digitally issued prescriptions and handle that price reductions. That also happens to mean that you can't get your prescription if the system is down :smiling_face_with_tear: - luckily happens very rarely though)

**Comment by Helium314** [comment]
> Well, taginfo for [dispensing=no](https://taginfo.openstreetmap.org/tags/dispensing=no#map) does seem to show it all around Europe

Interestingly, in some random checks it looks like that `dispensing=no` was mostly added a long time ago (most recent I found in ca 30-40 pharmacies: 5 years ago), while `dispensing=yes` was also tagged much more recently.

**Comment by matkoniecz** [comment]
> heavy-opioid-based or other addictive/dangerous drugs

OK, these are not appearing in all pharmacies - but I think they appear independently from each other and any pharmacy can order them, but only some deal with extra paperwork and legality is annoying.

It also mismatches "whether a pharmacy dispenses prescription drugs or not" wiki definition, this kind of drugs are subset of prescription drugs

**Comment by westnordost** [comment]
In any case:

This needs a list of countries in which 1. "non-dispensing" pharmacies exist and 2. it is signed clearly from the outside, best with a photo of evidence. One country is enough for this quest to be accepted (label: new quest), however the more countries there are, the more it makes sense to invest time implement it.

**Comment by mnalis** [comment]
> This needs a list of countries in which 1. "non-dispensing" pharmacies exist and 2. it is signed clearly from the outside, best with a photo of evidence

Here (circled in red by myself) is picture for Croatia (`HR`) ("HZZO" is "Hrvatski Zavod za Zdravstveno Osiguranje", and whole phrase means "contractual partner of Croatian Ministry of Health" that is to be shown on `dispensing=yes` pharmacies, and must **not** be shown for non-dispensing ones; with meanings as I've described before).
![hzzo_small](https://user-images.githubusercontent.com/156656/213923263-bb0a8ec8-9c8c-4532-b849-e66f9ba0d200.jpg)

> One country is enough for this quest to be accepted (label: new quest), however the more countries there are, the more it makes sense to invest time implement it.

Wiki pages I've read:
https://en.wikipedia.org/wiki/Over-the-counter_drug
https://en.wikipedia.org/wiki/Prescription_drug

seem to indicate similar distinction **should** exist at least in Netherlands, Canada, UK, _some states_ of USA, and Australia (and I guess at least few ex-Yugoslavian countries beside Croatia). Unfortunately, I do not know about signing practices in other countries at all, so if there are any users informed about the subject from those (or other!) countries that would like to provide pictures or explanations for [dispensing=*](https://wiki.openstreetmap.org/wiki/Key:dispensing) use there, it would be great.

> One country is enough for this quest to be accepted (label: new quest), however the more countries there are, the more it makes sense to invest time implement it.


I have no problem with investing time myself to write SC quest (and would probably do it for my & EE fork anyway), so that at least should not be a blocker. (of course, if someone new wants to try their hands at simple yes/no quest instead, just say so and I can help [guide](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md) you).

**Comment by matkoniecz** [comment]
> Here (circled in red by myself) is picture for Croatia (HR) ("HZZO" is "Hrvatski Zavod za Zdravstveno Osiguranje", and whole phrase means "contractual partner of Croatian Ministry of Health" that is to be shown on dispensing=yes pharmacies, and must not be shown for non-dispensing ones; with meanings as I've described before).

Can you consider uploading such photo to Wikimedia Commons? Do you want to mention this Croatia situation on https://wiki.openstreetmap.org/wiki/Key:dispensing ? That may help to reduce future confusion.

**Comment by westnordost** [comment]
So at least for Croatia, this could be implemented.

**Comment by rhhsm** [comment]
> Here (circled in red by myself) is picture for Croatia (`HR`) ("HZZO" is "Hrvatski Zavod za Zdravstveno Osiguranje", and whole phrase means "contractual partner of Croatian Ministry of Health" that is to be shown on `dispensing=yes` pharmacies, and must **not** be shown for non-dispensing ones; with meanings as I've described before). ![hzzo_small](https://user-images.githubusercontent.com/156656/213923263-bb0a8ec8-9c8c-4532-b849-e66f9ba0d200.jpg)

Such labels also occur on the windows of Bulgarian pharmacies, but this means that such pharmacies cooperate with the national health insurance fund so that if you buy prescription drugs there that are partially or wholly covered by the health insurance, they do the paperwork for you and you only pay them the part of the price that isn't covered (if any). At a pharmacy without such a label, you can buy such prescription drugs too, but you pay the full price and you have to claim the part that is covered by insurance yourself at the fund. Could this be the meaning in Croatia too?

> Wiki pages I've read: https://en.wikipedia.org/wiki/Over-the-counter_drug https://en.wikipedia.org/wiki/Prescription_drug
> 
> seem to indicate similar distinction **should** exist at least in Netherlands, Canada, UK, _some states_ of USA, and Australia (and I guess at least few ex-Yugoslavian countries beside Croatia).

As described on Wikipedia, there are 4 classes of drugs in the Netherlands. Prescription drugs can only be sold by pharmacies, but afaik all pharmacies in NL sell prescription drugs. Like @westnordost I always thought that a pharmacy is defined by the fact that it sells prescription drugs.

**Comment by westnordost** [comment]
Phew, okay. Back to "feedback" then...

**Comment by HolgerJeromin** [comment]
Just as a datapoint. This node got added dispensing=no by the wheelmap app. 
https://www.openstreetmap.org/node/361083029/history

**Comment by ivanbranco** [comment]
We have the same distinction in Italy, a "farmacia" is tagged with dispensing=yes and a "parafarmacia" with dispensing=no.

**Comment by rhhsm** [comment]
They have "parafarmacia" in Spain too: https://www.farma-amparo.es/blog/que-es-una-parafarmacia/ From what I understand from the Google translation, they can be tagged with `shop=chemist` (chemists also can sell over-the-counter drugs, so their product range is larger than that of a Spanish parafarmacia)

**Comment by westnordost** [comment]
If it is a different kind of place, it sounds like something that should be added to the iD presets as a country-specific preset then.

**Comment by mnalis** [comment]
> Such labels also occur on the windows of Bulgarian pharmacies (it say something like "this pharmacy works with the national health fund НЗК"), but this means that such pharmacies cooperate with the national health insurance fund so that if you buy prescription drugs there that are partially or wholly covered by the health insurance, they do the paperwork for you and you only pay them the part of the price that isn't covered (if any). 

While the reduced/waived price is indeed  a part of the `HZZO` National healthcare system in Croatia, I would not think that it is necessary condition for `dispensing=yes` (it depends on the country). If you look at my pictures at bottom there are additional two labels (red which is probably "Wiener osiguranje" a blue which is "Croatia osiguranje") which are two additional money reduction / coverage operators/schemes available at that pharmacy.   But that payments/refundations are orthogonal to whether they are filling prescriptions.

> At a pharmacy without such a label, you can buy such prescription drugs too, but you pay the full price and you have to claim the part that is covered by insurance yourself at the fund. Could this be the meaning in Croatia too?

Not really. Firstly, prescriptions here have been purely digital for some time now here, so `dispensing=no` pharmacy wouldn't even **know** what is your prescription (you'd have to remember / write down yourself if it is unrestricted drug and you prefer to buy it in `dispensing=no` pharmacy). Secondly, they wouldn't be able to sell you certain drugs which are prescribed by your doctor to yourself only (like antibiotics, heavy opiods, etc.)  

> Like @westnordost I always thought that a pharmacy is defined by the fact that it sells prescription drugs.

Hm, not in my mind (where pharmacy is defined as having pharmacist on duty):

- `amenity=pharmacy` is where there is employed **pharmacist** (i.e. licensed person with degree in pharmaceutical science). So even when buying over-the-counter drug, you can ask on advice which one to use, how much should you take for your symptoms, what they recommend for children of certain age and weight, will that drug interact with other medicines you're using etc.

- In `shop=chemist`, they don't have such persons, but regular (e.g. like in a supermarket) cashiers only. They _might_ be able to tell from experience which one is dishwasher salt and which one is an Aspirin (or not, depending on your luck :smile:), but they certainly aren't educated nor licensed in pharmaceutical sciences, so they can't provide advice, only sell you whatever box you picked up from the shelves yourself (or you named it to them - if they themselves give drugs, usually in order to prevent thefts). Of course, they can thus only sell "over-the-counter" (e.g. unrestricted) drugs.

- Now, if it has a pharmacist (i.e. it is `amenity=pharmacy`) it can be:
  -  `dispensing=yes` (meaning they can sell you **any prescription** you have) or 
  - `dispensing=no` e.g. so while they'll be able to advice you what is the best cough syrup or painkiller or antipyretic to give to your kid of certain age, and how often to give it, and when to get them to the hospital if it doesn't help; they won't be able to sell you for example antibiotics (or heavy opiods, or other restricted drugs depending on the country) that the doctor have prescribed to the kid.

(note that terms `pharmacist` / `chemist` / `druggist` might mean the same or similar things in different English dialects, but in OSM we should stick to meanings as defined in OSM wiki pages, which is often at odds with layman language usage)

As to why would an `amenity=pharmacy` choose **NOT** to be `dispensing=yes` (given that they have to employ the pharmacist anyway to be an `amenity=pharmacy`, which is the biggest hurdle probably), I can only guess (but few guesses for Croatia are: for a defined big list of popular drugs you must have fixed country-wide price,  and for reduced-price drugs they'll have to wait months [or worse] to be refunded by HZZO, which is not a speed-champion when it comes to payments). 

I think that is in line with what [dispensing=*](https://wiki.openstreetmap.org/wiki/Key:dispensing) says:

* `dispensing=yes` - A pharmacy with a dispensing pharmacist able to sell prescription drugs as well as over the counter drugs.
* `dispensing=no` - A pharmacy with a pharmacist that does not fill prescriptions, but does sell pharmacist-only drugs (e.g., pseudoephedrine in the US).

**Comment by matkoniecz** [comment]
> dispensing=no e.g. so while they'll be able to advice you what is the best cough syrup or painkiller or antipyretic to give to your kid of certain age, and how often to give it, and when to get them to the hospital if it doesn't help; they won't be able to sell you for example antibiotics (or heavy opiods, or other restricted drugs depending on the country) that the doctor have prescribed to the kid.

Would they be able to sell none of medicines requiring prescription? Or would they be restricted only from extreme ones like opioids?

**Comment by westnordost** [comment]
Anyway, looking at the example photos provided so far, it is an information that is not really surveyable for non-experts. I certainly wouldn't know what an "uvigorni partner hzzo-a" is and that blue-red icon in the second photo is also not something anyone would recognize.
Remember, StreetComplete quests ought to be solveable by anyone, not only locals. So, I'll close this as not planned.
