### ISSUE TITLE
Profile screen: Number 1 local rank for latest week does not have full wreath

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4762]
**How to Reproduce**
Be ranked first locally for the past week.

**Expected Behavior**
Rank 1 (and other high ranks) show full wreath

**Versions affected**
50.2

I am not sure what rank should require a full wreath for local rank, but I feel like number 1 definitely should have it.

The problem seems to be around here:

https://github.com/streetcomplete/StreetComplete/blob/66fafe8ec2971e823065d59310dc050c9df03464/app/src/main/java/de/westnordost/streetcomplete/screens/user/profile/ProfileFragment.kt#L310

The rank is surely always >=1 so this can never be 100?

Ping @matkoniecz

**Comment by matkoniecz** [comment]
Thanks for noticing, reporting and even diagnosing!

**Comment by arrival-spring** [comment]
Just got the beta update and now all my wreaths are full! Thanks for fixing this!

**Comment by matkoniecz** [comment]
Nice to see that someone cares about them :)
