### ISSUE TITLE
Cycling overlay: specific color for two way bike segments in one way streets

### ISSUE THREAD

**Issue by XioNoX** [streetcomplete/StreetComplete#4765]
**Use case**
Right now the same black line overlay is used for one way street where bikes are both allowed and not allowed to go in the opposite direction (unless there is a specific infrastructure (bike lane, etc)

**Proposed Solution**
It would be useful when walking around to have those in different color (eg. dashed gray?), so we can see if that road have changed since it was last tagged as "one way for bikes too".
This is particularly useful for example in France where more and more small streets are being converted as bi-directional for bikes (mandated by law).

Thanks

**Comment by westnordost** [comment]
Hmm, ... dashed black is already used for "shoulder". But well, I guess places in which there are shoulders are generally on the countryside while not-oneways-for-cyclists are generally in cities, so there should be little conflict.
