### ISSUE TITLE
Display name of amenity in Undo menu

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4767]
**Use case**

Sometimes I want to undo a quest (from multi-level Undo menu), but if there have been several quests, I am unsure which quest refers to which object (e.g. several closely-spaced shops, cafes etc. and `opening_hours` quest), because Undo menu (as opposed to Quest itself) doesn't show amenity name/type. E.g.

![small_Screenshot_20230126_180201_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/214977024-f6d8e1d1-5358-409c-8871-9841a86f544d.jpg) ![small_Screenshot_20230126_180220_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/214977028-d6c8dcc6-0234-473d-9a36-fb89363dde4d.jpg)

**Proposed Solution**

It would be great if the Undo entity when pressed would also contain name/type of the object on which the Quest was answered. E.g. in example above, second picture would also say _"Super Hrvoje (cafe)"_ below _"Are this opening hours still correct?"_. That would allow me to check if I'm undoing a right quest (instead of a closeby quest of same type!)

**Comment by Helium314** [comment]
Does it make sense to also show the location? So it would be the same as in the quest form, e.g. `on level 1: Super Hrvoje (Cafe)`
