### ISSUE TITLE
which products / services a shop offers (more details)

### ISSUE THREAD

**Issue by coffeepotprotocol** [streetcomplete/StreetComplete#4769]
**Use case**
Typical things a shop offers :
Sales
Parts
Repair
Rental

Not every shop is "specialized", it might also offer things you'd expect from other features. Or a shop offers similar services (i.e. repair or rental) for/of different things. An example would be https://taginfo.openstreetmap.org/keys/mobile_phone:repair. Whether they offer delivery might also be interesting.

**Proposed Solution**
Add optional services to the shop menu https://wiki.openstreetmap.org/wiki/Shop_suffix

**Comment by coffeepotprotocol** [comment]
Filter already implemented in OsmAnd
![motorcycle](https://user-images.githubusercontent.com/28932695/215179464-1308b8aa-81e0-4f60-8480-a75aa653d18c.jpg)

**Comment by westnordost** [comment]
See the https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md
