### ISSUE TITLE
CardAcceptance quest not appliable (in germany?)

### ISSUE THREAD

**Issue by MrKrisKrisu** [streetcomplete/StreetComplete#4773]
Affected tag(s) to be modified/added: [payment:*](https://wiki.openstreetmap.org/wiki/Key:payment:*#Keys)

### Problem Description

My issue is about the quest [accept cards](https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cards).

In my opinion, this quest is not usefully applicable in Germany. The quest only asks whether credit and / or debit cards are accepted. I can't answer the question correctly for any business, as it usually doesn't matter whether the card is debit or credit when paying.

Example:
The Girocard of the local Sparkasse is a debit card.
The standard Visa card of DKB [is a debit card](https://bank.dkb.de/fragen-antworten/visa-debitkarte).

A supermarket accepts debit cards according to OSM data.
-> probably means "Girocard only".
-> I have only my Visa Debit card and thought I can use it because OSM said "debit cards accepted".

### Ideas for implementation

For me, the information about which brands (girocard, visa, mastercard, ...) are accepted and whether contactless payment is possible would be more useful.

Possibly the quest can be replaced with checkboxes where the most used payment providers can be ticked - including the possibility of contactless payment.

This is also a good data basis for the acceptance of Google and Apple Pay.

#### Instead of this
![image](https://user-images.githubusercontent.com/4103693/215324559-c9be7aec-a20b-4191-aa66-d633c944c265.png)

#### Something like this, if possible within the functions in streetcomplete

- [ ] accepts girocard (yes/no/i dont know)
- [ ] accepts MasterCard (yes/no/i dont know)
- [ ] accepts VISA (yes/no/i dont know)
- [ ] accepts American Express (yes/no/i dont know)
- [ ] supports contactless (yes/no/i dont know)

**Metadata needed:** Maybe some payment options should be selected by country. for example, girocard is not appliable for other counties then germany.

**Comment by westnordost** [comment]
> In my opinion, this quest is not usefully applicable in Germany. The quest only asks whether credit and / or debit cards are accepted. I can't answer the question correctly for any business, as it usually doesn't matter whether the card is debit or credit when paying.

That is not my experience. Some accept debit cards but not credit cards. Not sure about the reverse. Though, yes, it is usually about girocard or not (colloquially but wrong: "EC Karte"). Girocard is a debit card service. 

In any case, your suggestion about an alternative quest has been discussed in some other quest suggestion ticket: #3219
