### ISSUE TITLE
cycleway:xxx:lane: exclusive in France

### ISSUE THREAD

**Issue by XioNoX** [streetcomplete/StreetComplete#4776]
When selecting "bike lane" in the cycling overlay, StreetComplete sets tags such as:

```
cycleway:left	lane
cycleway:left:lane	exclusive
```

While they're case `L1a` in https://wiki.openstreetmap.org/wiki/FR:Bicycle (there is no mention of `exclusive` in the whole doc)

I discovered that after an experience user lett a comment on my StreetComplete generated edit saying that the exclusive tag doesn't make sens in France. See the `note` in Version 6: https://www.openstreetmap.org/way/827671375/history#map=19/48.39610/-4.48358

A quick look in Overpass shows that those tags are only set by StreetComplete: https://overpass-turbo.eu/s/1qJD

Last, this old issue might help give context: https://github.com/streetcomplete/StreetComplete/issues/3461

To me it would be enough to just not add the tag `cycleway:XXX:lane	exclusive`. And not mark the roads in red in the overlay if this tag is missing.
However I'm not experienced enough so getting more feedback from French users might a good idea. Same goes to know if a there is a way to mass remove it everywhere it's set in OpenStreetMap.

**Comment by westnordost** [comment]
Why do you open a new issue if you already know it has been discussed in another?

Anyway. the tag is documented here https://wiki.openstreetmap.org/wiki/Key:cycleway:lane

For France, there are chaucidous which need to be distinguished from proper cycle lanes:
https://duckduckgo.com/?q=chaucidou&t=ffab&iax=images&ia=images

**Comment by westnordost** [comment]
The information whether it is necessary to distinguish proper cycle lanes from some kind of advisory/suggestion/etc. counterpart is by the way maintained in this repo:
https://github.com/streetcomplete/countrymetadata/blob/master/data/hasAdvisoryCycleLane.yml
, including how they are supposed to look like:
https://github.com/streetcomplete/countrymetadata/blob/master/data/advisoryCycleLaneStyle.yml
For France, it is "white dashes without pictogram".
