### ISSUE TITLE
Allow optional survey of private highways

### ISSUE THREAD

**Issue by JoeyJoJoJr** [streetcomplete/StreetComplete#4777]
**Use case**
Many service roads, footpaths etc. around me are on private land, such as factories. However, there is still a case for accurately mapping them, for example routing engines can use private ways in some circumstances (OSMAnd, Valhalla). I'd like to add their surfaces and lit conditions, and I have safe and legal access to the area to survey it. The same applies for any StreetComplete editor living on a private residential street. 

**Proposed Solution**
Add an option in settings, perhaps off by default, to allow survey of private areas. User accepts a small disclaimer to not trespass and only survey areas they are permitted to be in.

**Comment by HolgerJeromin** [comment]
> SCEE is a modified version of StreetComplete, aimed at experienced OSM users unhappy about the lack of advanced editing capabilities in normal StreetComplete.

With SCEE ( https://github.com/Helium314/SCEE ) you can edit the queries and remove the "private" filter.

**Comment by westnordost** [comment]
Jup, see @HolgerJeromin 

The app does not want to lead the user into private property if it is known to be private property.
