### ISSUE TITLE
Add red_turn signs on traffic lights

### ISSUE THREAD

**Issue by bombaata** [streetcomplete/StreetComplete#4780]
### General
Affected tag(s) to be modified/added: [red_turn](https://wiki.openstreetmap.org/w/index.php?title=Key:red_turn) and/or [traffic_signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals)
Question asked: **Which red turn sign is displayed?** (right/left/straight/right-left/straight-right/straight-left/all/no-sign)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
**This sign is quite common in France, called M12.**

### Ideas for implementation

**Element selection:** 
https://overpass-turbo.eu/s/1qLZ

**Metadata needed:** Don't know about this one.

**Proposed UI:** a SVG miniature of each sign

**Comment by HolgerJeromin** [comment]
Can you explain the "useful purpose" for this data?

**Comment by bombaata** [comment]
> Can you explain the "useful purpose" for this data?

These signs are useful to cyclists. They can be used for route calculation.

**Comment by westnordost** [comment]
Should this be tagged for each intersection? Or for each traffic light? `highway=traffic_signals` can be mapped both on intersections and on the vertices at which the actual crossing/traffic signals are located. https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#How_to_map

How to distinguish between these two?

**Comment by rhhsm** [comment]
Doesn't the signage on traffic lights correspond to the turn lane markings for those lights, and wouldn't routing software prefer to use these lane markings? It would make much more sense to develop a quest asking for turn lane markings as these are more common (I guess) and less ambiguous (traffic lights are often only tagged on one node, so it's hard to add the distinction of different markings on different traffic lights at the crossing which are present on the map as only one node).

**Comment by wielandb** [comment]
> Doesn't the signage on traffic lights correspond to the turn lane markings for those lights, and wouldn't routing software prefer to use these lane markings? 

Not necessarily. For example [this sign](https://wiki.openstreetmap.org/wiki/File:Zeichen_721_-_Gr%C3%BCnpfeilschild_mit_Beschr%C3%A4nkung_auf_den_Radverkehr,_StVO_2020.svg) from germany means simply that bicycles are allowed to turn right after stopping, even if the stop light is red. But there usually will be no special lane for bicycles because of that. 

>It would make much more sense to develop a quest asking for turn lane markings [...]

See #2574 about what technical challenges this would need to overcome. I see the same issues raised there for this quest suggestion.


As a general remark, from reading the wiki page it seems that this tag is not used very much, conflates existing tagging schemes and that there are usually better ways to tag special turning restrictions for special vehicles.

**Comment by westnordost** [comment]
Given that the tag proposed
- is not approved,
- has very low usage numbers when compared to the total amount of traffic signals (even if just counting france and just counting traffic signals that have been mapped in detail with `:forward` / `:backward`)
- there is discussion about the tag whether it makes sense / if it should not be recorded rather with a different tag or relation
- there is at least [another proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/turn_signals#Right_turn_on_red) to use different tags (although abandoned)

I find that the tag is not in use enough for it to be pushed through StreetComplete. Better put this through a proposal first, then this could be revisited.
