### ISSUE TITLE
How well lit is this street/footway/path(/bus stop)?

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4782]
### Rationale
Currently, there are multiple quests regarding if an object is lit or not. But there are vast variations on how well lit a place is.

Many people feel uncomfortable in poorly lit places, in the night.

### Existing tag

There's a tag, [`Key:lit:perceived`](https://wiki.openstreetmap.org/wiki/Key:lit:perceived), to capture the quality of the illumination. This tag is disputed (for good reason) as it's hard to capture this information objectively by different persons with the eyes.

### Quest idea

However, our smartphones come with a large array of sensors – one can capture brightness levels in Lux (lx). Granted, there's not an established tag for this – however, without an App which captures this, it's rather difficult to map.

The already proposed tag shows, that capturing this information is regarded useful and helpful to routers.

The quest could ask the user to point the smartphone's display straight up and walk the segment of the path, while the app reads the sensor. After some smoothing of the sensor values, the lowest value would be saved to the path.

Tag look like `lit:min_brightness=81` – unit would be Lux (lx).

### New Tag

If the response to this quest suggestion is positive, I would create a proposal for this tag.
 
### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is <strike>established</strike> (needs proposal) and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside, but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

#### Element selection:

Selection would be the same as for the general yes/no "Is this x lit?"-Quests, but the object requires to have `lit=yes` tagged already. Also the device is required to have the necessary sensor.

The quest would only appear two hours after sunset until two hours before sunrise.

#### Metadata needed:

no

#### Proposed UI:

Rendering could be “copied” from the "Walk the missing path" capturing for notes, just with the segment of the way shown on the map as well.

**Comment by matkoniecz** [comment]
`lit:min_brightness` - this tag has 0 uses right now - see https://taginfo.openstreetmap.org//search?q=lit%3Amin_brightness

completely new tagging should be invented/discussed not on this issue tracker but on general community discussion forums ( https://community.openstreetmap.org/ or tagging mailing list)

Note that single visit will not record actual minimum. It will depend for example on the phase of the moon.
