### ISSUE TITLE
Public phones in Germany

### ISSUE THREAD

**Issue by kmpoppe** [streetcomplete/StreetComplete#4788]
### General
Affected tag(s): [`amenity=telephone`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtelephone), [`disused:amenity=*`](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix)

Deutsche Telekom has started shutting down public phones across Germany, which has lead to a healthy discussion on [Discourse](https://community.openstreetmap.org/t/abschaltung-aller-offentlichen-telefone-in-de-ist-fur-anfang-2023-geplant/4712).

[Jakob48](https://community.openstreetmap.org/t/abschaltung-aller-offentlichen-telefone-in-de-ist-fur-anfang-2023-geplant/4712/53), [eiskalt-glaskar](https://community.openstreetmap.org/t/abschaltung-aller-offentlichen-telefone-in-de-ist-fur-anfang-2023-geplant/4712/55) and [Lukas458](https://community.openstreetmap.org/t/abschaltung-aller-offentlichen-telefone-in-de-ist-fur-anfang-2023-geplant/4712/57) (as well as myself) all thought that using StreetComplete to identify the current state of those phone could be a workable solution.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Number of elements affected

As of February 4th 1pm CET, there are 15,099 nodes (and 6 ways 🙄 ) with `amenity=telephone` in Germany. Of those 15,105 objects, 12,235 (~81%) have not been changed for at least 180 days, so there's a considerable amount of objects that will the quest shown immediately after release. (Numbers parsed from [Overpass Turbo](https://turbo.overpass.kumi.systems/?Q=%5Bout%3Ajson%5D%3Barea%5B%22name%22%3D%22Deutschland%22%5D%3B(node%5Bamenity%3Dtelephone%5D(area)%3B)%3Bout%20body%3B%0A) and the OSM API, see [phones.ods](https://github.com/streetcomplete/StreetComplete/files/10608667/phones.ods))

### Ideas for implementation

While the shutdown seems to have already happened between Jan 31st and Feb 1st 2023, obviously most physical objects are still in situ.

Therefore using the `CheckExistence` quest, which would ask for `amenity=telephone` every 2 years seems to be too long of a stretch.

**Element selection:** 

I, therefore, propose to create a new Quest (deactivated by default), that will make use of the `${lastChecked(...)}`-node filter expression but instead use 6 months as the age pointer and filter `amenity=telephone` and `disused:amenity=telephone`.

**Proposed UI:**

Question:
**Does this public phone still exist?**
Answers:
* Yes, and it's functional (==> only set `check_date`)
* Yes, but it's disfunct (==> change `amenity=telephone` to `disused:amenity=telephone`, set `check_date`)
* No, it has been removed (==> delete node)

Ideas and alternative solutions welcomed.

**Comment by riQQ** [comment]
See also #4733.
