### ISSUE TITLE
Ask if places have a backup generator

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4789]
### General
Affected tag(s) to be modified/added: [backup_generator](https://wiki.openstreetmap.org/wiki/Key:backup_generator) (disclaimer: I created this page to document an already in use tag)
Question asked: **Does this place have a backup generator?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
It is very useful to know if a place will still operate during load shedding [1] and some brands even advertise which locations have a generator on their website: [example](https://romanspizza.co.za/find-a-store).
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
Disabled by default as it requires entering a place at a particular time, similar to air conditioning quest.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
All shop-like elements.

**Metadata needed:**
Countries where backup generators are common, at least South Africa and by the looks of where the tag is used already, Philippines and Indonesia. 

**Proposed UI:**
Yes/No question, much like the air conditioning quest.

[1] South Africa has recently and continuously been having load shedding where power is off for hours at a time on a [schedule in different areas](https://www.eskom.co.za/distribution/customer-service/outages/municipal-loadshedding-schedules/), recent article: ["South Africa’s load shedding is practically permanent now"](https://www.citizen.co.za/news/south-africa/load-shedding/load-shedding-schedule-06-february-2023/)

**Comment by michalgwo** [comment]
Such a great idea, that I decided to implement it right away :satisfied: #4793

**Comment by mnalis** [comment]
(related: South Africa power infrastructure has been on last [osmweekly](https://weeklyosm.eu/archives/16282): https://techcentral.co.za/the-volunteers-mapping-south-africas-power-grid-and-more/219769/  and the article coincidentally happens to mention StreetComplete for filling missing details in the OSM)

I'm not sure about _"No spam"_ for most countries though (and that _"Easily answerable"_  looks like it might probably be noticeably harder to answer than airconditioning quest in majority of the countries). 
(There is always [SCEE](https://github.com/Helium314/SCEE) if it ends up being too problematic for upstream SC...)

**Comment by letypequividelespoubelles** [comment]
For countries, I.dia should be included too.
But how can you know if there is a backup generator?  Most of the time I don't see it !
And if there is no generator but solar panel + battery (which may become more common, as of is now cheaper and greener) ?  It should be yes, right?

**Comment by arrival-spring** [comment]
With regards to "no spam", that's why it would be restricted to certain countries.

Easily answerable - it does require being at a place during load shedding and seeing if the lights are on or whatever, so is also a bit situation specific, like air conditioning quest or even lit quest.

Solar panel - in OSM speak, these are `power=generator` so I think that would still count. Maybe the question needs rephrasing or a clarification adding for things like that. Maybe "Does this place have a generator or backup power source?"

**Comment by matkoniecz** [comment]
> Easily answerable - it does require being at a place during load shedding and seeing if the lights are on or whatever, so is also a bit situation specific, like air conditioning quest or even lit quest.

Or asking someone working there. I guess that in both cases it would require making it disabled by default?

**Comment by davidpnewton** [comment]
Definitely a disabled by default quest. Useful to know but it requires quite a bit more work than walking round a place for the most part.

**Comment by michalgwo** [comment]
There is no detailed information in the osm wiki on whether we should include solar panels as a backup_generator, but I think the point is to have information if there will be electricity when the power grid is off. I think most people won't know if the thing that generates power is a diesel generator or a solar panel, in the end, solar panels and also power generators.

**Comment by westnordost** [comment]
Definitely add Myanmar to that list.

Note that these countries have usually a very low number of contributors, especially on-site contributors. So, to be honest, I do not think it is worth it to implement. Now, you have already taken the initiative, so its only a question of whether it is worth to maintain. More comments in the PR.

**Comment by westnordost** [comment]
See discussion in https://github.com/streetcomplete/StreetComplete/pull/4793
