### ISSUE TITLE
Cycleway quest applies wrong tags

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4790]
Likely this is related to #4774, but this happens in in 51.0 beta1 (from GitHub)

* Open the cycleway quest for https://www.openstreetmap.org/way/43943837 (`cycleway=lane`)
* see current situation tagged as "???" (which is expected)
* either: set the available side to "none"
  * see added tags `oneway:bicycle=no`, `cycleway:left=lane`, `cycleway:right=no` (the first two are incorrect)
* or: set the available side to "advisory"
  * see added tags `oneway:bicycle=no`, `cycleway:both=lane`, `cycleway:right:lane=advisory` (the first two are incorrect)
* get the quest again, this time showing both sides
* set new side to "none"
* see tags are now correct

**Comment by westnordost** [comment]
Uh, this one is a bugger.

`cycleway=lane` on a `oneway=yes` is interpreted to mean

`cycleway:right=lane`
`cycleway:left` not set (`null`)

So, as the left side is `null`, the left side is also not shown in the UI.

However, as only the right side is **changed** by the user, only `cycleway:right=lane` + `cycleway:right:lane=advisory` is set and whatever the value that was in `cycleway` tag before is now updated to only apply for the left side. This is why we end up with `cycleway:left=lane`.

Probably will need to change the logic that expands `cycleway` into `cycleway:left` and `cycleway:right` in `CyclewayCreator.kt`. Not sure yet what's the cleanest way to do this.

**Comment by westnordost** [comment]
added the same logic for the creator as for the parser. Need to add tests.
