### ISSUE TITLE
Put progress bar in the middle of the screen

### ISSUE THREAD

**Issue by michalgwo** [streetcomplete/StreetComplete#4791]
**Use case**
When I started using this app, it took me a while till I realized there is a progress bar in the top-left corner. What do you think about putting it in a more visible place? For example in the middle of the screen? I can do this and submit it as a pull request if you find it useful.

Right now it looks like this:
<img width="150" alt="Screenshot_1675628139" src="https://user-images.githubusercontent.com/114614618/216843153-6fe79661-01cd-46fd-bc4b-af42030a75ce.png">

**Proposed Solution**
My proposition is to make it like this, which is more visible and looks better in my opinion:
<img width="150" alt="Screenshot_1675628449" src="https://user-images.githubusercontent.com/114614618/216843156-3e7874a4-03a4-4ba0-a25c-74f28b8ded53.png">

**Comment by Helium314** [comment]
It might be more visible, but I imagine it's really annoying if you're doing a download on slow internet in an area which you don't need right now.
This happens to be surprisingly often for me, and thus I was quite happy when the download indicator was moved from a large icon at the bottom to where it is now.

**Comment by michalgwo** [comment]
[Helium314](https://github.com/Helium314) You are right, I didn't think about that

**Comment by westnordost** [comment]
The point is that the download/upload is not modal. You can use the app, solve quests etc. while it is uploading/downloading.
