### ISSUE TITLE
Crashes when creating notes

### ISSUE THREAD

**Issue by hdevine825** [streetcomplete/StreetComplete#4794]
I have experienced crashes since about v50.0 when creating notes. The app will close just after opening the note editor, but before typing.

**How to Reproduce**
1. Select add note
2. App crashes

**Expected Behavior**
Able to type note details and save.

**Versions affected**
Streetcomplete v50.2
Android: 13
Devine: Pixel 5

**Comment by westnordost** [comment]
Were you adding photos?

**Comment by westnordost** [comment]
Did you get the app from the Play Store or from F-Droid?

**Comment by hdevine825** [comment]
I got it from the Play Store. It has not been while adding photos, in fact, the crash happens before I can tap the camera button.

**Comment by westnordost** [comment]
Does this happen always or sometimes?

**Comment by hdevine825** [comment]
I would estimate 10-20% of the times I try to add a note.

**Comment by westnordost** [comment]
Hm I see a few crash issues in the google play console. They might or might not be related to this and from looking at their stacktrace look like it should be relatively straightforward to find the cause. I'll look into that.

**Comment by westnordost** [comment]
I found an fixed an issue, that may have been the cause.

**Comment by FloEdelmann** [comment]
For reference: https://github.com/streetcomplete/StreetComplete/commit/8f41a14e75fa143cff79611926636e51ba1365a8
