### ISSUE TITLE
Beginner issue: Splitting ways decision not intuitive

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4796]
Hey guys,

### Intro

I showed StreetComplete multiple non-techi people in the past month and one issue in particular was pretty blatant:

### Issue

They had issues understanding from just using the app, that ways may need to be split. After explanation they tend to forget that they need to check this before answering a quest for a way section.

And after beeing remembered, they had trouble locating the option for this, especially on the quests with many options, like the "surface of the road" quest.

### Solution

My conclusion is, that this function need to be visible and reachable after clicking on a quest, not requiring to select "other answers..." first. 

### Rationale 

Reason beeing that the user can happily answer the quest, so there's no thought spend on clicking something else than the answer or complete a decision before answering.

### Current GUI

The GUI looks currently like this, e.g., a road surface quest is selected:

 
![Screenshot_2023-02-06-15-02-47-139-edit_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/614929/216994411-1032d928-1d14-4792-b9e0-ccb9be723633.jpg)

### Improved GUI

Todo

### Versions affected

All I guess, but can confirm this issue up to `v51.0-beta1`.

**Comment by westnordost** [comment]
Hm yeah I don't know about that. First, I wouldn't know how to move that option "up" to be visible at first glance without requiring some kind of description. Also, there are other things to consider, too, which should for one reason or another be more visible and not be behind "other answers".

@matkoniecz Oh, concrete plates pic width does not line up with the the rest O_o

**Comment by matkoniecz** [comment]
> @matkoniecz Oh, concrete plates pic width does not line up with the the rest O_o

Again? Fixed, thanks for spotting and a ping.

If that will happen again I will add some checks protecting against this...

**Comment by matkoniecz** [comment]
Another option would unrolling "Other answers..." menu and having each of them presented like "Other answers..." is right now, each one taking a line.

Change similar to how buildings selection menu was turned into one scrollable view.

**Comment by rhhsm** [comment]
Access to splitting ways is now described using two different phrases: "Differs along the way…" and "Split way". It would be more consistent if it was only one.

**Comment by FloEdelmann** [comment]
> > @matkoniecz Oh, concrete plates pic width does not line up with the the rest O_o
> 
> Again? Fixed, thanks for spotting and a ping.

For reference: https://github.com/streetcomplete/StreetComplete/commit/80166c41afc79e35f2335e324dcb39aa113fafcc

**Comment by westnordost** [comment]
Anyway, as written, I don't see how to better the UI without caveats that in themselves are (IMO) worse than the solution.

**Comment by westnordost** [comment]
I don't like it.  The very reason they are "hidden" behind one more tap is so that they do not clutter the UI

**Comment by matkoniecz** [comment]
There would be below and not seen until scrolled there (acceptance button can be clicked without scrolling to the bottom), so maybe clutter would not be so bad?

(still there is enough of accepted issues to keep me busy for a loooong time, including some where I planned to process them...)
