### ISSUE TITLE
Address overlay: Don't allow to add addresses to buildings in Italy

### ISSUE THREAD

**Issue by Mannivu** [streetcomplete/StreetComplete#4801]
Not really a bug, but I've found that with the "Addresses" layer enabled users can add addresses (addr:street and addr:housenumber) on buildings in Italy. This is a wrong method of mapping, since in Italy addresses are not linked to the building, but to the entrance of a property. For this same reason, the quest asking the address of a building has been disabled long ago on StreetComplete (#714). However, with the new layer users can add the address on building.

The quest is disabled
![The quest is disabled](https://user-images.githubusercontent.com/42747216/218144049-41b56e4c-dfcc-4e80-8af1-d67eba0da98c.png)

No asking on the building
![No asking on the building](https://user-images.githubusercontent.com/42747216/218144067-c60b6f68-55a8-4cd9-a33d-d9b24cca991c.png)

Selecting the building, I can add the address
![Selecting the building, I can add the address](https://user-images.githubusercontent.com/42747216/218144078-75b5e9c6-0d87-46a1-9674-405e22fb0751.png)

**Comment by westnordost** [comment]
Correct, this is the overlay. It does not ask the user to add housenumbers anywhere, it just enables him to add them, either on buildings or on nodes. The same as any other editor.

**Comment by opk12** [comment]
This is incompatible with the SC base assumption from the README:
> It can be used without any OpenStreetMap-specific knowledge.

> The app is aimed at users who do not know anything about OSM tagging schemes but still want to contribute to OpenStreetMap.

which determines UX design, quest eligibility, SC's self-advertising, community advertising and word of mouth.

Use cases:
- Tourist mapper prefers SC to stay safe from shooting himself in the foot.
- Local community or mapper chooses SC to lure clueless victims into OSM.
  - Is your official position that a mapathon aimed at newbies should always begin as `Do not click on buildings in the addresses overlay, yea we know, but it's wrong`.
- Local mapper who learns tagging by using SC: if SC allows it, then it must be allowed, no?

**Comment by westnordost** [comment]
Actually what could be done relatively easily would be to make buildings whose center point is in Italy not clickable if they do not have an address set on the building outline yet.

This would only be okay if it is not accepted practice anywhere in Italy to map addresses on building outlines. Do you have documentation (wiki link) and data (e.g. overpass or sophox query that shows that only an insignificant number of buildings have addresses tagged)?

**Comment by Mannivu** [comment]
> Actually what could be done relatively easily would be to make buildings whose center point is in Italy not clickable if they do not have an address set on the building outline already. (after all, if the data is already present, it should be possible to update it)

First of all, I thank you for taking this proposal into consideration.

> This would only be okay if it is not accepted practice anywhere in Italy to map addresses on building outlines. Do you have documentation (wiki link) and data (e.g. overpass or sophox query that shows that only an insignificant number of buildings have addresses tagged)?

We have that guideline on OSM Wiki https://wiki.openstreetmap.org/wiki/IT:Addresses#Come_inserire_gli_indirizzi_2 (see the bold sentence starting with **NON**.

**Comment by opk12** [comment]
What about making a building unclickable if the country is in AddHousenumber's `enabledInCountries`, which lists the countries with the community discussions / rationales ([see here](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L29))?

This is the easiest option, no-maintainance, future-proof (if the list changes) and will save you a ticket for each bypassed local community guideline. Do I open a separate ticket (or 7 tickets if you prefer) for the other countries?

**Comment by westnordost** [comment]
> What about making a building unclickable if the country is in AddHousenumber's enabledInCountries, which lists the countries with the community discussions / rationales ([see here](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L29))?

No, because these were disabled for various different reasons that do not conflict with adding housenumbers to buildings. E.g. in France it has been disabled because **in some places** it is considered okay to add housenumbers in the Italian fashion (at entrance gate to property).

What is still required here would be a link to data that shows that what is written in that wiki article is actually followed.

**Comment by letypequividelespoubelles** [comment]
> in France it has been disabled because in some places it is considered okay to add housenumbers in the Italian fashion (at entrance gate to property).

Hum, no. Adding housenumber in the italian fashion is the best practice and what wants the french community. But it's ok to add housenumber on buildings. Not good, but ok. So I do think that, for France too it should be impossible to add housenumber to building with the address overlay.

**Comment by westnordost** [comment]
best practice ≠ not allowed

Also, please note the last sentence of my last post.

**Comment by Helium314** [comment]
> What is still required here would be a link to data that shows that what is written in that wiki article is actually followed.

Actually this is not followed in Italy quite often, e.g. https://www.openstreetmap.org/way/348322410.

**Comment by mnalis** [comment]
> Actually this is not followed in Italy quite often, e.g. https://www.openstreetmap.org/way/348322410.

Address on that way was created back in 2015., and if I understand it correctly the [decision about address mapping](https://lists.openstreetmap.org/pipermail/talk-it/2018-January/061775.html) was not reached until 2018., so unless they had fully completed some massive bot (or organized edits) campaign, it is likely that there will still be pre-2018 leftovers... (but note that I haven't done any serious research into the subject)

**Comment by Mannivu** [comment]
@mnalis we haven't made a bot campaign because the address should be near a viable access (and in some cases, this can't be done).

@westnordost I understand your requirement to prove the Italian community is enforcing this, but I don't know how to prove it. I'm trying to make a map showing how many buildings without any leisure/shop/amenity inside has an `addr:housenumber`, hoping this will suffice. Otherwise I don't know how to prove you this is the current state of mapping in Italy.

**Comment by westnordost** [comment]
How about an overpass query that shows all buildings with addresses in Italy? And/or counts of address nodes vs addresses on buildings in italy?
Should be doable with sophox too, not sure if there is a working instance of it though

Am 17. Februar 2023 13:46:44 MEZ schrieb Manuel Tassi ***@***.***>:
>@mnalis we haven't made a bot campaign because the address should be near a viable access (and in some cases, this can't be done).
>
>@westnordost I understand your requirement to prove the Italian community is enforcing this, but I don't know how to prove it. I'm trying to make a map showing how many buildings without any leisure/shop/amenity inside has an `addr:housenumber`, hoping this will suffice. Otherwise I don't know how to prove you this is the current state of mapping in Italy.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4801#issuecomment-1434594520
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Mannivu** [comment]
> How about an overpass query that shows all buildings with addresses in Italy? And/or counts of address nodes vs addresses on buildings in italy?
Should be doable with sophox too, not sure if there is a working instance of it though

I did it, but then on the Telegram group of the Italian community some user told me that taking every building would bring in even the building that are tagged with an amenity/shop/craft/etc... So I'm trying to doing one that takes buildings without a commercial activiti tagged on the same area.

**Comment by Mannivu** [comment]
remembered we have a dedicated taginfo instance focused only on Italy. From this instance, you can see that in Italy there are [4 000 000+ addr:](https://taginfo.geofabrik.de/europe/italy/keys/addr%3Ahousenumber), but there are _only_ [94 000+ with an addr:housenumber tag](https://user-images.githubusercontent.com/42747216/219686180-3034b566-f38b-4fc1-990d-e1ab7e203e62.png) (the total of the addr:housenumber usage in Italy [is ~4 000 000](https://taginfo.geofabrik.de/europe/italy/keys/addr%3Ahousenumber)). I think this should clarify that the addr:housenumber o building is not the standard mapping in Italy.

**Comment by mnalis** [comment]
> I did it, but then on the Telegram group of the Italian community some user told me that taking every building would bring in even the building that are tagged with an amenity/shop/craft/etc... So I'm trying to doing one that takes buildings without a commercial activity tagged on the same area.

Using [this overpass](https://overpass-turbo.eu/s/1rul) to further clean it up by removing buildings which have `amenity`/`shop`/`craft`/`tourism` and similar suspects, it seems that there are about **65k** `building=*` ways with `addr:housenumber` on them.

So, about `1.60%` of all `addr:housenumber` in Italy are mapped on `building=*` polygons. (finding out how much of those are created with StreetComplete would need someone with more overpass-fu than myself, but two dozen random checks didn't show SC as being the editor that added those addresses, so I'd guess it is in minority). Also about half of them were being added in last year or two.

**Comment by westnordost** [comment]
Thanks for the link to the country-wise taginfos. I checked some other countries too. It looks like adding addresses to buildings should be disabled for Italy only. The reason why Netherlands, Norway, Czech Republic and Denmark are that low is because addresses are imported automatically (as nodes) from an official source, so this has nothing to do with that adding addresses to buildings is something that should not be done (but instead adding addresses anywhere is not necessary).

Country | % of housenumbers on buildings
---- | -----
Estonia | 98.00%
Belarus | 97.00%
Belgium | 95.00%
Ukraine | 95.00%
Ireland | 93.00%
Slovakia | 88.00%
Luxembourg | 87.00%
Bulgaria | 84.00%
Austria | 83.00%
United Kingdom | 83.00%
Finland | 81.00%
Germany | 79.00%
Switzerland | 79.00%
Sweden | 66.00%
Hungary | 66.00%
Lithuania | 63.00%
Poland | 56.00%
Latvia | 55.00%
Croatia | 51.00%
Greece | 38.00%
Spain | 30.00%
Romania | 25.00%
Portugal | 19.00%
France | 12.00%
Czech Republic | 4.00%
Italy | 2.00%
Netherlands | 0.00%
Norway | 0.00%
Denmark | 0.00%
