### ISSUE TITLE
Opening Hours spelling mistake

### ISSUE THREAD

**Issue by ForgottenHero** [streetcomplete/StreetComplete#4804]
When looking at a quest for opening hours the first option under "Other Answers" says "**Diggers** by month" instead of "**Differs** by month".
I tried looking through the files in [https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours](https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours) but couldn't trace it.

**How to Reproduce**
Locate a business with an "Opening Hours" quest.
Tap "Other Answers".
View the first option in the list.
![Screenshot_2023-02-09-21-34-28-574_de westnordost streetcomplete](https://user-images.githubusercontent.com/4233945/218225899-c9856ba0-ea89-45d2-9136-06b7c2f274b2.jpg)

**Expected Behaviour**
The first option in the list should read "Differs by month..."

**Versions affected**
SC 50.2
Android 12

**Comment by Helium314** [comment]
The Australian translation has several such issues, looks like someone copied the default (US) English strings by hand and made mistakes like "Privacy statemenr" and "Diggers by month..." (also note the `...` instead of `…`, which is in many strings).
You can fix it in [POEditor](https://poeditor.com/join/project/IE4GC127Ki), or wait for someone to do it.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

> like "Privacy statemenr" and "Diggers by month..." (also note the ... instead of …, which is in many strings).

Fixed this ones, not reviewed others. I wonder is it possible to just undo their edits.

**Comment by matkoniecz** [comment]
Help with reviewing and directly fixing it in POEditor ( https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app ) would be highly welcome!

**Comment by ForgottenHero** [comment]
Thanks Mateusz. I'll jump on POEditor and see if I can up that "Translated %".

**Comment by matkoniecz** [comment]
And apparently looking through translated already would be helpful! Though here using app for mapping may be good enough :)
