### ISSUE TITLE
StreetComplete suggests entrance=* for entrances onto the roof

### ISSUE THREAD

**Issue by BartekChom** [streetcomplete/StreetComplete#4805]
StreetComplete seems to want to mark entrances on the roof (where one can just walk on a roof/terrace/patio from external stairs; because `highway` touches a `building` (?)) with entrance=*, but it is probably not the correct meaning of this tag (entrance into a building).

**How to Reproduce**
StreetComplete gives for [node 8757243196](https://www.openstreetmap.org/node/8757243196) quest AddEntrance.

**Expected Behavior**
(Maybe I am just supposed to hide this quest. I have been using StreetComplete only for about one hour, but [I reported this problem as a note and somebody suggested to report it here](https://www.openstreetmap.org/note/3553778).)

I would prefer if there were a way to silence such quests for everybody without suggesting that the point is unpassable or allows entering into the building.

I see many possibilities:
* adding tag like `not_an_entrance=yes` (available `noexit=yes` seems to be unsuitable, because this point is in the middle of a way, but I may be misinterpreting this tag)
* recognizing that when the highway is on the level of the roof and does not end, it is not an entrance (maybe the level of the node should be marked explicitly too)
** I can imagine cases when one can enter the building by a trapdoor or a door with a "cabin" not worth mapping (unless we assume that such "cabins" must be mapped to clarify situation) exactly where a way crosses the outline of the building - can we assume that such cases should be mapped by hand without suggestions from StreetComplete?
* interpreting this as an entrance, something like `entrance=roof` (I guess that it would add a square in the default rendering which would be misleading - this suggests that such tagging would be wrong (trolltagging (unless I misinterpret this word)))
** Even if we accepted it, maybe better `entrance=onto_the_roof` to clarify that it is "an entrance onto the roof" not "an entrance from the roof" (in other words "an exit from the building onto the roof", good thing is that one does not talk about "an entrance from the building onto the roof") - if I really speak English well enough to talk about such subtle distinctions correctly.

After describing it I suspect that the first possibility is the best, but I am not sure.

**Versions affected**
v51.0, Android 9

**Comment by matkoniecz** [comment]
@BartekChom Is https://www.openstreetmap.org/way/860200139 shape really correct?

![screen](https://user-images.githubusercontent.com/899988/218269391-6280669a-54db-4d1d-b67c-bbd85db19adb.png)

Is https://www.openstreetmap.org/way/860356511 on roof of apartment building or more likely its garages?

I think that the best option would be to mark it as `location=roof` and skip such ways (see https://wiki.openstreetmap.org/wiki/Key%3Alocation)

**Comment by BartekChom** [comment]
Yes,  https://www.openstreetmap.org/way/860356511 is on roof of garages.

Add tag `location=roof` for everything that is on the roof? Thank you.

I am sorry, in what sense skip? Should I hide quests for myself? Should I remove all the ways on the roof? Does adding `location=roof` make quests disappear? Are you saying that adding `location=roof` should make quests disappear?

**Comment by matkoniecz** [comment]
> Add tag location=roof for everything that is on the roof? Thank you.

yes

> Are you saying that adding location=roof should make quests disappear?

Yes, and maybe it will require change in the code of this quest. I will check and add a matching test to ensure that this kind of situation will not trigger issues.

**Comment by matkoniecz** [comment]
Though in this specific case I would consider mapping like https://www.openstreetmap.org/way/571349203 https://www.openstreetmap.org/way/1098637689

What is preferred depends on whether you consider apartment tower and garages underground as a single structure or two different ones ( https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element )

But similar cases may appear where `location=roof` on roof of an apartment building is definitely valid so I will change the code.

**Comment by matkoniecz** [comment]
this should be included in the next app update ([v51.0](https://github.com/streetcomplete/StreetComplete/releases/tag/v51.0) was released yesterday)
 
> (Maybe I am just supposed to hide this quest. I have been using StreetComplete only for about one hour, but [I reported this problem as a note and somebody suggested to report it here](https://www.openstreetmap.org/note/3553778).)

in general - please report this kind of issues!

**Comment by BartekChom** [comment]
Thank you very much.

> Though in this specific case I would consider mapping like https://www.openstreetmap.org/way/571349203 https://www.openstreetmap.org/way/1098637689

Separate building... I am not sure. Waste disposal and entrance D (but actually only a tunnel leading to it) are also below patio.

**Comment by BartekChom** [comment]
Ile jest dwa dodać dwa?

**Comment by rhhsm** [comment]
Do I understand correctly that the issue described here is avoided only when the way is tagged with `location=roof`? I have a similar issue with this node https://www.openstreetmap.org/node/12842715185 which is at the top of steps leading to a terrace of the building (i.e. part of the building is under it) that then leads to entrances at the first floor level. Streetview https://maps.app.goo.gl/KAS9WJZY4eMy1WvAA However I wouldn't call that a roof.

May I suggest that the quest is also suppressed when a way that the node is part of has a `layer=*` (*>1) tag? When a way crosses a building, iD suggests adding `layer=1` to the higher of them to solve the conflict, so this is probably a more often used way to describe that a way is above a building. There are only about 3000 combinations of `location=roof` + `highway=*` so this is a rare combination (0.3% of the uses of `location=roof`).

Please let me know if I should open a new issue for this.

**Comment by matkoniecz** [comment]
Please, open a new issue. 

If it is a roof (see issue title) then IIRC location=roof fixes it - but from you description you claim it is not a roof, so it is distinct from your issue

If it is not a roof then it is a different issue and new should be opened

**Comment by matkoniecz** [comment]
>  terrace of the building (i.e. part of the building is under it)

Based on description it is in fact rooftop terrace
