### ISSUE TITLE
Changeset issues on POI move and opening hours re-survey

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#4806]
When a POI is moved and afterwards the opening hours are resurveyed, both changes are uploaded in the same version. But subsequently, another version is uploaded without any visible changes.

For example: https://www.openstreetmap.org/node/1350299845/history

Version 8 has updated location and opening hours check date. Version 9 has no changes.

At the time of editing, I had some connection problems, so it is also possible that the bug resulted from them.

**How to Reproduce**
1. Find a POI that asks for an opening hours re-survey
2. Select the option that the POI is at a slightly different place
3. Move the POI
4. Click on the opening hours re-survey icon a second time (at new location)
5. Now do re-survey the opening hours

**Expected Behavior**
Each change should be in a separate version with a fitting changeset comment.

**Versions affected**
v.51.0 on Android 12

**Comment by Helium314** [comment]
From version 8 to version 9 `check_date:opening_hours` changes from `2022-06-28` to `2023-02-11`, so the re-survey happens after the move.
Did you use the the history you linked, or some tool? I remember some tools had issues with several changes in a short period of time, and would display something wrong.

**Comment by Discostu36** [comment]
No, I did use that history. I'm certain it looked different yesterday. Or I was tired. But in both cases not a SC issue.
