### ISSUE TITLE
Maxheight measuring quest opens streetmeasure to measure a width, not a height

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#4808]
**How to Reproduce**

When answering the height for a building passage the new streetmeasure app opens and is ready to measure a width, i can not change this to measuring a height.

(Of course i manually opened the streetmeasure app and measured the height and entered the number, but i think now the source=Arcore tag is missing)

**Expected Behavior**

**Versions affected**

51.0

**Comment by westnordost** [comment]
Oh, you are right. A stupid oversight of mine.
