### ISSUE TITLE
Update parking tagging to new scheme 

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#4812]
### General
Affected tag(s) to be modified/added: see https://github.com/streetcomplete/StreetComplete/issues/4664
Question asked: Is the Parking situation here still the same?

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Same with regular updates, to e.g. opening_hours, the parking layer should receive updates regularly (with a reasonable interval which is probably a few years at minimum).

For any occurrence of the old schema the interval shall be 0, so an update to the new schema is asked immediately by default.

I think an implementation as a quest is better opposed to leaving it in the layer, since that way any and all small snippets of a way will get updated.

**Comment by matkoniecz** [comment]
Is it by any chance covered by https://github.com/streetcomplete/StreetComplete/pull/4768 ?

**Comment by joshinils** [comment]
> Is it by any chance covered by #4768 ?

yes, and no;
it mentions:
> when (re)tagging, always tag according to the new schema and clear any tags of the old schema

which means in practice, that the old tags will stay unchanged unless I actively change something, which will trigger an update to the new schema.

if the situation has not changed I need to change something to make it wrong, hit ok (thus changing to the new schema), and change it back to make the data correct.
this changeset then looks like this: [osm.org](https://www.openstreetmap.org/changeset/132516679) [osmcha](https://osmcha.org/changesets/132516679/)
which I would like to have as a standalone quest, since I can not see in SC where the old and new schema is used, both are interpreted and shown in the layer the same way.


I want to actively go after the old schema and upgrade the tagging to the new one.

**Comment by matkoniecz** [comment]
note that vast majority of cases can be migrated automatically and running bot like https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/retag_old_style_parking_conditions_in_Poland would be a better solution

doing it manually is not a good use of human time

**Comment by matkoniecz** [comment]
I will close this one as for cases where additional survey is needed SC is already asking (if specific case is missing: please report it separately) and in cases where automatic replacement is a good idea - then fully automatic replacement is preferable

(though remember about https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct and just my endorsement is not enough to start running a bot edit)
