### ISSUE TITLE
Check existence quest trying to delete ways

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4816]
When answering `no` to the check existence quest for https://www.openstreetmap.org/way/44386367, the edit history says the element was deleted, but the quest is asked again because SC can't delete ways.
(please don't delete the linked element, this is merely for testing)

**Comment by westnordost** [comment]
Also on the technical side I guess nothing really speaks against implementing that (free floating, i.e. not connecting to anything else?) ways could be deleted too, but this has a number of implications that make it somewhat complicated to deal with automatically. E.g. one wouldn't want to delete the building if the POI was mapped on a building.

**Comment by Discostu36** [comment]
I can't think of an example for a POI mapped to a building outline that will not be gone when the building is destroyed.

**Comment by Helium314** [comment]
The potential issue is the other way round. If SC asks whether the POI is gone, it shouldn't delete the building.

**Comment by Discostu36** [comment]
Ah, I see, sorry.
