### ISSUE TITLE
Construction quest answers

### ISSUE THREAD

**Issue by sun-geo** [streetcomplete/StreetComplete#4817]
I noticed changeset https://www.openstreetmap.org/changeset/132208914 which seems based on quest #685.

A part of the changeset is to update the way segment https://www.openstreetmap.org/way/710022337 which was changed from `highway=construction` to `highway=road`, see also the way history:
https://pewu.github.io/osm-history/#/way/710022337

I would expect the road classification of the former tag `highway=tertiary` instead of the used `highway=road`, so I wonder if this is a "bug" of the quest or a wrong selection of the user? How does the quest selection for possible answers looks like?

**Comment by matkoniecz** [comment]
See https://www.openstreetmap.org/way/710022337/history

As `construction=tertiary` was missing, sadly it was not specified what is being constructed there. It could be for example cycleway.

And checking history would not help: road reconstruction sometimes changes road class.

> if this is a "bug" of the quest or a wrong selection of the user?

neither 

it was a bug of OSM data

> How does the quest selection for possible answers looks like?

it asks whether construction is complete, user can answer "yes" or "no"

> I would expect the road classification of the former tag highway=tertiary 

If this classification is still applying: please update this way

**Comment by sun-geo** [comment]
Thanks for explanations. I agree - the change towards construction situation should be done by adding a suited `construction=*` tag. I'm happy if for JOSM-user there is a validation rule & warning, hopefully iD will follow this procedure.

Anyway, I wonder if you could do a determination of the "right" highway classification by getting the information from the ways which are connected to the starting- and end-node from the processed way?

**Comment by matkoniecz** [comment]
> I wonder if you could do a determination of the "right" highway classification by getting the information from the ways which are connected to the starting- and end-node from the processed way?

Not always, see https://www.openstreetmap.org/way/388081121 https://www.openstreetmap.org/way/1145641744 (if these ways would be marked right now as `highway=construction` and completed then such automatic marking would be bad.

**Comment by Helium314** [comment]
> I failed to achieve the same in case of iD - issue is still open somewhere.

I couldn't find it on iD issue tracker, are you sure it's there?

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/id-tagging-schema/issues/617

**Comment by sun-geo** [comment]
> > I wonder if you could do a determination of the "right" highway classification by getting the information from the ways which are connected to the starting- and end-node from the processed way?
> 
> Not always, see https://www.openstreetmap.org/way/388081121 https://www.openstreetmap.org/way/1145641744 - if just these ways would be marked right now as `highway=construction` and completed then such automatic smart marking would be bad.
> 
> `highway=road` is not completed, but is not completed in a clear detectable way.

You are right, didn't had such cases in my mind.

So, it seems the only way to find the initial road classification is to browse the way history.
I assume this isn't technical possible by StreetComplete?

**Comment by matkoniecz** [comment]
And checking history would not help: road reconstruction sometimes changes road class.
