### ISSUE TITLE
Reconsider hiding relevant quests on enabling overlay

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4818]
For start, overlay work really well especially for `lit` quest - and shop overlay is really great way to add missing shops. But there are some details that may be worth changing.

One of results of enabling overlay is hiding equivalent quests. I would propose to reconsider this and to remove this behaviour.

- this makes more important questions where data is missing or old more prominent
- in areas with high quest density tapping way specifically may be hard where other quests applying to this way or nearby objects are shown, showing quest labels reduces this problem
- tapping very short way segments is annoying or nearly impossible while quest icon does have a reasonable minimum size. It gets worse with ways going under other ways or over them. Showing quest icons solves it at least for ways detectable as needing survey
- quest interface for some quests does not need extra "tap on 'select' button" step
- it is less confusing - disappearance of say surface quests on enabling surface overlay is a bit confusing

In fact, I would consider doing the exact opposite and enable relevant quest even if disabled in settings.

I already tested version where quests are not disabled and I consider it as superior in usability.

**Comment by rhhsm** [comment]
I like it that by using an overlay, I have access to two quests for each element instead of just one. Ideally, all quests for an element should be accessible (#124), but 2 is better than 1.

**Comment by matkoniecz** [comment]
clearly this idea is not really like
