### ISSUE TITLE
NSI Location filter not working correctly

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4822]
Burger King is in the NSI but is not showing up for me when adding a shop, although all other expected brands that I have tried are there.

The NSI has a slightly obtuse location set for Burger King: [`{"include":["001"],"exclude":[[-88.3726,39.4818,32],"au"]}`](https://location-conflation.com/?locationSet=%7B%22include%22%3A%5B%22001%22%5D%2C%22exclude%22%3A%5B%5B-88.3726%2C39.4818%2C32%5D%2C%22au%22%5D%7D&referrer=nsi)

I have tried faking my location to a few different countries and I can't find Burger King in the presets anywhere I have tried.

**Versions affected**

Version 51

**Comment by westnordost** [comment]
`osmfeatures` library does not understand this syntax, this is why any presets with (such complex) syntax are excluded in https://github.com/streetcomplete/StreetComplete/blob/master/buildSrc/src/main/java/UpdateNsiPresetsTask.kt#L45-L46

I figure maybe at least the latlon+radius could be supported, but I really do doubt whether it is worth it. Maybe if someone else implemented it as a PR. In any case, this should be in the https://github.com/westnordost/osmfeatures/ repository.
