### ISSUE TITLE
Address overlay: Allow adding addresses to `entrance=*`

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#4823]
Oftentimes, entrances are already mapped. It would be nice if it was possible to tap on an entrance the same way as it is possible to tap on a building in order to add an address to the entrance. If an entrance has no address yet, instead just an icon of a door should be shown.

**Comment by matkoniecz** [comment]
Note that entrances may have special extra fields: unit range and entrance reference.

Would it be also considered as an address?

**Comment by westnordost** [comment]
I guess so... I mean, it would also make sense to extend the address overlay to also being able to edit this information. It is ultimately part of the address, too. But that would be a separate ticket.

**Comment by rhhsm** [comment]
Addressing traditions vary widely across the world. The most common seems to be to assign addresses to buildings (which SC assumes), but here in BG addresses are assigned to plots of land, and all buildings on that plot of land have the same address (there might not even be a building on the plot at all). If there are multiple housing units on the same address (such as for apartment blocks), details such as entrance letter and apartment number are added to the address.
I think assigning addresses to entrances should only be done for countries that have a tradition for this. For BG, the address should be assigned to the plot (or all house units on the plot), while only the detailed specification (such as entrance letter) should be added to the entrance to a block of flats. I.e. if the building already has an address mapped, that address should not be repeated on the entrance node.

**Comment by rhhsm** [comment]
To summarise my previous comment marked as off-topic: I think addresses should be attached to buildings only, unless there is a tradition in a country to attach addresses to entrances.

**Comment by matkoniecz** [comment]
This does not work in all cases, some documented at https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers and https://wiki.openstreetmap.org/wiki/Addresses#Multiple_buildings_for_one_housenumber

Free-floating nodes vs tagging buildings also has no general consensus.

**Comment by rhhsm** [comment]
My main concern is that this quest will lead to duplication. If an address is already mapped on a building, an entrance to this building should only be tagged with a reference using the entrance reference quest.

**Comment by mnalis** [comment]
Perhaps `entrance overlay` should not be offered for houses which already have a housenumber of them (or alternatively, it might delete housenumber from `building` when it is added to `entrance` - but that too might be unwanted) ?

**Comment by westnordost** [comment]
Why, you can all do this manually with the overlay.

**Comment by mnalis** [comment]
> Why, you can all do this manually with the overlay. No need for the quest-like smartness of only showing X when Y, just allow the user to edit everything related.

I _personally_ am I just fine with unrestricted editing functionality, it is just that SC target user group is more newbie (because of reputation and old newbie-protective old "quests" interface), and might not realize they are doing edits that will be frowned upon. While "overlay" interface is indeed geared more toward advanced users than it is to newbies, people using SC probably still don't expect to be given JOSM/Vespucci-class freedom/responsibilities (i.e. _"enough rope to hang themselves"_). cf. recent https://github.com/streetcomplete/StreetComplete/issues/4801

**Comment by deevroman** [comment]
What about countries where there is no address at the entrance? It looks strange that StreetComplete offers to add an entrance (judging by the icon on the map), but then requires an address.

**Comment by westnordost** [comment]
It's the address overlay, not the entrance overlay. That an address that is a vertex of a building is usually an address is the assumption the app makes.

Regarding entrance numbers or entrance refs, the long/mid-term solution would be to incorporate the ability to add this information within the address overlay itself but I'd rather leave this to the author of the related quest, @matkoniecz , or anyone else interested in that, of course.

**Comment by matkoniecz** [comment]
> Regarding entrance numbers or entrance refs, the long/mid-term solution would be to incorporate the ability to add this information within the address overlay itself but I'd rather leave this to the author of the related quest, @matkoniecz , or anyone else interested in that, of course.

For now I want to check how it works. I have not really used address overlay so far.

(I will be likely moving soon to part of city where importance of references on entrances is even more important, so some new features would be quite likely in such case)
