### ISSUE TITLE
Service areas aren't treated as areas

### ISSUE THREAD

**Issue by MMK21Hub** [streetcomplete/StreetComplete#4824]
When quests are shown on a `highway=services`, the outline is treated as a line, instead of treating it as an area. This is inconsistent with, for example, buildings or playgrounds.

### How to Reproduce
1. Use Overpass Turbo to find service areas near you
1. Find a service area in StreetComplete that has a quest (e.g. Are there any toilets here?)
1. Tap on the quest

### Expected Behavior
The quest pin appears in the middle of the area, and the area is highlighted when tapping on the quest

### Versions affected
StreetComplete v51.0 and v50.2 (older versions not tested)

### Screenshot
![A screenshot of StreetComplete, showing the outline of a service area being treated as a line](https://user-images.githubusercontent.com/50421330/219882018-e865abd5-704d-4896-a5d3-6905cde4ae09.png)

**Comment by matkoniecz** [comment]
Thanks!
