### ISSUE TITLE
Enable 'Is cash payment accepted here?' quest in the Netherlands

### ISSUE THREAD

**Issue by meiphoo7-Mae** [streetcomplete/StreetComplete#4826]
**Use case**

According to research done by an organisation for senior/elderly citizens about 2-5% of the shops only accepts electronic payments. They focused on shops but it might be equally valid for other places where payments are accepted.

**Proposed Solution**

Enabling the 'Is cash payment accepted here?' quest in the Netherlands (may be also in other EU countries) seems to be an appropriate choice.

**Additional context**
We've a discussion about this subject in the SCEE repo.
Please take a look at /Helium314/SCEE/issues/413 for more context about this, including a link to the website of the Dutch government which points out that accepting cash payments is not legally required in the Netherlands.

**Comment by matkoniecz** [comment]
What is the source of that 2-5%? Is it controversial or accepted claim? Is it closer to 2 or 5%? (asking as vast majority of things presented as research actually does not even pretend to be research, to say nothing about "research" falling apart at minimum inspection)

Maybe it would be worth asking on a forum of relevant community...

If 2% I would not be sure, if 5% then it would make sense.

**Comment by Helium314** [comment]
My reasoning for suggesting to ask for enabling in StreetComplete (and not only SCEE) is that the number of shops with `payment:cash=no` is about the same in NL and UK. And UK already had the quest enabled for a few months, and most likely more shops (though I didn't check).

More info on the 2-5% + linkwould probably help

**Comment by mnalis** [comment]
As reported by NL Times, it is confirmed by Netherland's central bank (DNB), and is 2-6% (depending on the size of the city - in big cities it is 6%, in smaller villages 2%): https://nltimes.nl/2023/02/16/dutch-central-bank-says-many-retailers-refuse-cash-payments 

So if that is true, I think this should would make quest acceptable in SC.

**Comment by westnordost** [comment]
Is this legal? Asking because as cash is legal tender, as far as I know in Germany shops **must** support cash.

**Comment by meiphoo7-Mae** [comment]
In addition to the links @mnalis provided I found a link to the actual survey.
The results of the survey can be found here:
https://www.dnb.nl/en/general-news/dnbulletin-2023/some-retail-sectors-refuse-cash-payments-too-often/

@westnordost:
Yes, in the Netherlands it is legal to refuse any form of legal tender.
More on this can be found on the site of the Dutch government:
https://www.rijksoverheid.nl/onderwerpen/geldzaken/vraag-en-antwoord/kan-ik-met-een-wettig-betaalmiddel-overal-betalen

That article is in Dutch. The translation of the most relevant part is:

----
**Can I pay everywhere with legal tender?**
The law does not require anyone to accept legal tender. Retailers may refuse cash (bills and coins) or payment by debit or credit card. However, retailers usually indicate which payment methods they do not accept. For example through window stickers or checkout stickers.

**Refuse cash**
A retailer decides for himself which means of payment he accepts.

----

**Comment by matkoniecz** [comment]
https://www.dnb.nl/en/general-news/dnbulletin-2023/some-retail-sectors-refuse-cash-payments-too-often/

> An average of 1 in 24 retailers (over 4%) clearly let customers know they do not accept cash.

> Most retailers (70%) do not indicate with stickers or signs how customers can pay for their purchases (see Figure 3).

so it seems to me that it makes sense a opt-in quest there, especially as on the current rate trend is toward blocking cash payments

**Comment by mnalis** [comment]
> so it seems to me that it makes sense a opt-in quest there, especially as on the current rate trend is toward blocking cash payments

Can we make quest opt-in for some countries, and default for others? Or would we also have to make Sweden opt-in then?

If we do not have that capability, my reading of https://nltimes.nl/2023/02/16/dutch-central-bank-says-many-retailers-refuse-cash-payments (as outsider not deeply researching the subject) would suggest it would be **preferred to leave it enabled automatically**, as it seems NL central bank has started mandating it must be signed if they do not accept it:

> At a third of the shops where customers can only pay by card, the retailer only makes it clear once customers are at the checkout. The **DNB** was **emphatic** in saying that it **must** be clear **in advance** that shops do not accept cash, for example, **with signs** saying only specific cards may be used for transactions.

**Comment by Helium314** [comment]
> Can we make quest opt-in for some countries, and default for others? Or would we also have to make Sweden opt-in then?

AddAcceptsCash is disabled by default anyway

**Comment by meiphoo7-Mae** [comment]
Thank you, everyone, for participating in this discussion  :+1:
