### ISSUE TITLE
charging_station socket:type2=2 should not ask capacity

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4828]
`amenity=charging_station`
`socket:type2=2`

Imo should not ask for capacity.

StreetComplete:quest_type=AddChargingStationCapacity

**How to Reproduce**

https://www.openstreetmap.org/node/7105628161/history 

**Versions affected**

StreetComplete 51.0

**Comment by Discostu36** [comment]
Why not?

1. There might be other sockets available but missing from data
2. Socket count and vehicle capacity (parking spaces) might not match.

**Comment by westnordost** [comment]
See @Discostu36
