### ISSUE TITLE
Quest suggestion: Unisex hairdressers

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#4829]
### General
Affected tag(s) to be modified/added: [`unisex=yes`](https://wiki.openstreetmap.org/wiki/Key:unisex) or [`female=yes`](https://wiki.openstreetmap.org/wiki/Key:female) or [`male=yes`](https://wiki.openstreetmap.org/wiki/Key:male) (for [`shop=hairdresser`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser))
Question asked: **Which customers does this hairdresser serve?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
    → most will probably be `unisex`, but the exceptions are not totally rare, see https://overpass-turbo.eu/s/1rx0 and https://taginfo.openstreetmap.org/tags/shop%3Dhairdresser#combinations
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
    → see https://overpass-turbo.eu/s/1rwX

### Ideas for implementation

**Element selection:**

```
nodes with
  shop = hairdresser
  and !unisex and !female and !male
```

Or, to cover edge cases like [this one I discovered](https://www.openstreetmap.org/node/4945998997):

```
nodes with
  shop = hairdresser
  and unisex != yes and female != yes and male != yes
```

In this case, should the respective other existing keys should be deleted, in addition to setting `unisex=yes` / `female=yes` / `male=yes`? Or should the unusual `only` value also be considered valid?

**Metadata needed:** None.

**Proposed UI:** Simple text selection: "All genders" / "Women only" / "Men only"

**Comment by Discostu36** [comment]
`unisex=yes` is not the same as `male=yes` and `female=yes`, is it?

**Comment by Discostu36** [comment]
I think there needs to be a "Woman and men are segregated" option, leading to `male=yes`, `female=yes`, `unisex=no`.

**Comment by FloEdelmann** [comment]
In iD, it is rendered as "Both genders", and only one of the three choices is allowed:

![grafik](https://user-images.githubusercontent.com/202916/219950059-fedbc66a-4a71-48f4-98d7-acfb00eeebb4.png)

The [wiki page for `unisex`](https://wiki.openstreetmap.org/wiki/Key:unisex) comments on the distinction of `unisex=yes` and `female=yes`+`male=yes`, but focuses on toilets. I doubt that there are unisex hairdressers that have segregated areas for men and women.

**Comment by Discostu36** [comment]
> I doubt that there are unisex hairdressers that have segregated areas for men and women.

I'd guess this to be standard in countries with muslim majority, but don't have first hand experience about that.

**Comment by FloEdelmann** [comment]
Most uses of `female=yes`+`male=yes` are in Central Europe, so I guess we can't draw a conclusion about gender segregation from the use of `female=yes`+`male=yes` vs `unisex=yes`: https://overpass-turbo.eu/s/1rx1

But `unisex=yes` is much more popular, so this quest should prefer it.

I've also updated the Overpass Query in the original post to show `female=yes`+`male=yes` differently: https://overpass-turbo.eu/s/1rx0

**Comment by mnalis** [comment]
I have some doubts about _":chipmunk: Easily answerable by any pedestrian from the outside but a survey is necessary"_. Sometimes it is explicitly spelled on the outside in Croatia, but sometimes it is not. 

Perhaps as disabled by default quest,  as it might need entering and asking the staff?

**Comment by rhhsm** [comment]
Good idea!

> I have some doubts about _"🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary"_. Sometimes it is explicitly spelled on the outside in Croatia, but sometimes it is not.
> 
> Perhaps as disabled by default quest, as it might need entering and asking the staff?

I think it is safe to assume that if it's not shown on the outside, it's unisex. If I were a male/female only hairdresser, I would put that info on the window to avoid having to refuse customers of the wrong gender all the time.

> > I doubt that there are unisex hairdressers that have segregated areas for men and women.
> 
> I'd guess this to be standard in countries with muslim majority, but don't have first hand experience about that.

I lived in Turkey for a year, and never saw unisex hairdressers. All were either male or female, and this is clearly indicated on the window. It might be a good idea to give local language translations of male/female in the quest, similar to how the days of the week are given in the local language for the opening hours quest.

**Comment by mnalis** [comment]
> unisex=yes is not the same as male=yes and female=yes, is it?

It seems to be [contested](https://wiki.openstreetmap.org/wiki/Key:unisex). It might be best to always remove `unisex=*` key and replace it with `male=*` + `female=*` for clarity.

> I think it is safe to assume that if it's not shown on the outside, it's unisex

I really wouldn't know, but if it is **really** so, it should be said in quest description, e.g. `if there is no signage on the outside, mark it is as male+female`

> If I were a male/female only hairdresser, I would put that info on the window to avoid having to refuse customers of the wrong gender all the time.

Well, yeah, don't get me started on _"If I were..."_ talk :smile: - there are zillion things I'm amazed that are so counterintuitive,  bad for your profits/health/wellbeing/environment and just plain wrong; and people still do it all the time against all logic. 
So, I definitely would not take _"it is only logical"_ argument as any basis for making a model of reality (if anything, I'd tend to assume that if it is logical, majority of the people are probably **not** doing it, but that might be a just a _little_ too cynical)

**Comment by rhhsm** [comment]
> > I think it is safe to assume that if it's not shown on the outside, it's unisex
> 
> I really wouldn't know, but if it is **really** so, it should be said in quest description, e.g. `if there is no signage on the outside, mark it is as male+female`

It would be best to mark it as not shown, like `name:signed=no` for shops that have no visible name.

**Comment by Discostu36** [comment]
> It might be best to always remove `unisex=*` key and replace it with `male=*` + `female=*` for clarity.

But it does mean two different things, even if there is no segregation. `Unisex` also includes people who don't identify as male or female.

**Comment by westnordost** [comment]
> In iD, it is rendered as "Both genders", and only one of the three choices is allowed

This is somewhat of a misinterpretation by iD and subsequent pushing of this tag by iD. It really should be a bug report over there and be fixed. Although, by this time `unisex` as a tag has pretty much been burnt already since this misinterpretation has been around now for so long. I remember there was a discussion about this already (with this conclusion, amongst other things), not sure whether on the mailing list or in the forum.

Anyway, `unisex` should not be used by StreetComplete because it is (now) quite ambiguous. If we really want to tag toilets, hairdressers, baths etc. that have separate areas for women and men, I fear a new tag would need to be invented for that or something (e.g. `segregated_by_sex` or something).

**Comment by westnordost** [comment]
> It would be best to mark it as not shown, like name:signed=no for shops that have no visible name.

How though? This involves several tags, so something like `sex:signed=no` is not possible.

**Comment by matkoniecz** [comment]
> This is somewhat of a misinterpretation by iD and subsequent pushing of this meaning by iD. It really should be a bug report over there and be fixed. Although, by this time unisex as a tag has pretty much been burnt already since this misinterpretation has been around now for so long. I remember there was a discussion about this already (with this conclusion, amongst other things), not sure whether on the mailing list or in the forum.

Yes, the general problem is that unisex tag is [skunked term](https://en.wikipedia.org/wiki/Skunked_term) as far as OSM tagging is concerned and there is no replacement.

And StreetComplete is not supposed to be introducing completely new tags on its own without agreement from OSM community.

> Although, by this time unisex as a tag has pretty much been burnt already since this misinterpretation has been around now for so long. I remember there was a discussion about this already (with this conclusion, amongst other things), not sure whether on the mailing list or in the forum.

On both :)

https://lists.openstreetmap.org/pipermail/talk/2018-April/thread.html#80559 https://forum.openstreetmap.org/viewtopic.php?pid=717805

**Comment by letypequividelespoubelles** [comment]
>I doubt that there are unisex hairdressers that have segregated areas for men and women.

![photo_2023-02-21_08-16-07](https://user-images.githubusercontent.com/54240434/220274504-54ac1a9f-b689-4dbd-9ac0-5fcc5c79e464.jpg)


Seen in Delhi, India.

**Comment by rhhsm** [comment]
> > I doubt that there are unisex hairdressers that have segregated areas for men and women.
> 
> Seen in Delhi, India.

Those are two hairdressers next door to each other :) I'd map them separately

**Comment by Discostu36** [comment]
> Those are two hairdressers next door to each other :) I'd map them separately

So in every country with gender segregation, every hairdresser who serves both sexes has to be mapped twice? I don't find that a good solution.

**Comment by rhhsm** [comment]
> > Those are two hairdressers next door to each other :) I'd map them separately
> 
> So in every country with gender segregation, every hairdresser who serves both sexes has to be mapped twice? I don't find that a good solution.

No. In this particular example, each shop has its own entrance.

**Comment by Discostu36** [comment]
I'd suspect this to be the standard case.

**Comment by FloEdelmann** [comment]
Okay, so if we consider the `unisex` tag as "burnt", the discussion about gender segregation is pointless, as we could only tag `female=yes`+`male=yes` or `female=yes`(+ maybe `male=no`) or `male=yes` (+ maybe `female=no`).

Should I open a new quest suggestion issue using only those tags to keep the discussion easy to follow?

**Comment by westnordost** [comment]
Would be better

Am 21. Februar 2023 10:58:19 MEZ schrieb Flo Edelmann ***@***.***>:
>Okay, so if we consider the `unisex` tag as "burnt", the discussion about gender segregation is pointless, as we could only tag `female=yes`+`male=yes` or `female=yes`(+ maybe `male=no`) or `male=yes` (+ maybe `female=no`).
>
>Should I open a new quest suggestion issue using only those tags to keep the discussion easy to follow?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4829#issuecomment-1438185337
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by FloEdelmann** [comment]
I created a follow-up suggestion issue: #4833
