### ISSUE TITLE
Hiding quests more easily

### ISSUE THREAD

**Issue by retiolus** [streetcomplete/StreetComplete#4830]
**Use case**

Hello, sometimes in blocks there are a lot of buildings that you can't see.

When I go out to do some StreetComplete I look on the unzoomed map where I haven't passed, having never completed the quests for these buildings I think I haven't passed here.

**Proposed Solution**

What I would like is to be able to hide these quests more easily,

Currently to hide a quest you need:
- click on the quest
- scroll down completely
- click on "Other answers..."
- click on "Can't say..."
- press "Hide"

So it takes 5 interactions before a quest is hidden, which is very annoying when you have to do it several times in a row.

![image](https://user-images.githubusercontent.com/65604466/220111756-3052d288-d583-4496-88a1-4b86e7c12847.png)

**Comment by Jean-BaptisteC** [comment]
Quests about buildings can disabled in settings and you don't is forced to answer at all quests :)

**Comment by mnalis** [comment]
ref: some related issues about less annoying multiple-hide functionality:
- https://github.com/streetcomplete/StreetComplete/issues/2569
- https://github.com/streetcomplete/StreetComplete/issues/4771
- quick-hide button in SCEE - https://github.com/streetcomplete/StreetComplete/issues/3952#issuecomment-1095306090

**Comment by mnalis** [comment]
Yes, not being able to get small circle to become real Quest icon is a known problem. 

See https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Some_quests_are_obstructed_by_other_quests,_and_I_can't_zoom_in_enough and linked tickets for more info.

**Comment by westnordost** [comment]
So an idea would be to show this in a context-menu on long-press. However, I think long-press should be reserved for #124 .

**Comment by mnalis** [comment]
> I don't want to disable the building quests... on the contrary they are the ones I answer the most. It's just a pain sometimes when the bubble of a building that's inside that you can't see overrides the bubble of a building you want to complete.

Also, if transition to Maplibre library works out (see https://github.com/streetcomplete/StreetComplete/issues/3123), it should allow you to zoom-in enough to see all quests (https://github.com/streetcomplete/StreetComplete/issues/4555 & others), thus solving this issue.

**Comment by westnordost** [comment]
Yeah, with MapLibre you can zoom in much further, so this solves the use case described in the initial post.
