### ISSUE TITLE
When using Shop overlay to correct shop tags, opening hours resurvey is not asked any more

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4834]
**How to Reproduce**

1. A quest to resurvey opening hours appears on a  shop node.
2. User notices a mistake in some other tag of the shop (spelling mistake in the name, pastry shop instead of bakery, etc.
3. User switches to Shop overlay and corrects the mistake
4. Resurvey opening hours quest has gone even though it was not checked

**Expected Behavior**
4. Resurvey opening hours quest is still there and can be checked and corrected if necessary

**Versions affected**
Android 10 / StreetComplete 51.0

This can be avoided when the opening hours are checked first before the mistake is corrected, but the functioning of the app should not depend on the order in which these actions are executed.
Probably a checkdate is added when the mistake is corrected, and as a result the resurvey quest disappears even though the opening hours were not checked.

**Comment by matkoniecz** [comment]
The same as https://github.com/streetcomplete/StreetComplete/issues/4746#issuecomment-1378887810

Opening hours resurvey when object is old and not modified, fixing other detail modifies it so it is no longer unmodified for a long time and it stops matching resurvey requirements.

Sadly, there are no nice obvious ways to fix it.

**Comment by rhhsm** [comment]
Sorry I missed that discussion...
