### ISSUE TITLE
Be able to define parts of building that are not marked as such

### ISSUE THREAD

**Issue by retiolus** [streetcomplete/StreetComplete#4836]
**Use case**

It often happens that parts of buildings are not properly associated with the building and they are considered to be a building in their own.

**Proposed Solution**

It would be necessary to be able to select two areas and to be able to say: this area belongs to this one, it is the same building. Maybe even specify if it is a balcony, outside stairs... etc. Or just "Building part".

![image](https://user-images.githubusercontent.com/65604466/220428273-916ff40e-73d7-4c73-8d2e-f0d41a61e408.png)
![image](https://user-images.githubusercontent.com/65604466/220428587-5ea1fafe-fc3c-4354-9d09-15e9197dfb07.png)

**Comment by matkoniecz** [comment]
that is a really tricky to handle automatically without user supervision

it gets worse when tags (for example building level count) differ between them and conversion to building parts is necessary

**Comment by rhhsm** [comment]
> that is a really tricky to handle automatically without user supervision

I guess it's also relatively rare, so not worth the effort. I'd make a note, and go home and edit the building in iD

**Comment by westnordost** [comment]
This is not possible in StreetComplete, as it can potentially be too complex. E.g. in your example in the starter post, to correct, this, the three building parts would need to be re-tagged to `building:part` and a new outline drawn around all three of them, while selected tags from the "main" building (now building:part)  would need to be moved to the new building outline.

Depending on how it is mapped, different actions may be necessary. This really cannot be done automatically.

**Comment by riQQ** [comment]
Duplicate of #3351
