### ISSUE TITLE
Does this gas station allow self-service? - enable in Germany

### ISSUE THREAD

**Issue by Timonade** [streetcomplete/StreetComplete#4837]
Hello today I noticed that the task "Does this gas station allow self-service?" is available only in Italy and Ukraine. 
But this quest should also be available in countries like Germany (see [overpass-turbo](https://overpass-turbo.eu/s/1rCZ)).

**Versions affected:** v51.0

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/pull/2822#issuecomment-1008845475

> In Germany, all stations have self service. You still need to go into the shop and pay for the gasoline.

Has it changed since last year?

If no, then I guess that https://overpass-turbo.eu/s/1rD1 are highly suspect

**Comment by michalgwo** [comment]
We should enable this quest in Bosnia and Herzegovina, some gas stations there are self-service, some aren't.

**Comment by Timonade** [comment]
I don't know of any gas station in Germany where you are served by a gas station attendant - you fill up the car and go into the gas station to pay. What's more, more and more gas stations are automated, which means you pay as much as you want to fill up, and then you fill up.

**Comment by matkoniecz** [comment]
> We should enable this quest in Bosnia and Herzegovina, some gas stations there are self-service, some aren't.

Are you sure there are many gas stations there banning people from operating gas pumps?

https://overpass-turbo.eu/s/1rDL

**Comment by michalgwo** [comment]
> > We should enable this quest in Bosnia and Herzegovina, some gas stations there are self-service, some aren't.
> 
> Are you sure there are many gas stations there banning people from operating gas pumps?
> 
> https://overpass-turbo.eu/s/1rDL

I'm not sure if they are literally banning people from operating gas pumps, but I know that once you arrive at a certain gas station, someone will immediately approach you to tank your car. About overpass results, It looks like the self_service tag is not that widely used in Bosnia and Herzegovina, if you run the opposite (look for self_service=yes) it will also return a few results.

**Comment by matkoniecz** [comment]
> I'm not sure if they are literally banning people from operating gas pumps

If they do not this then self-service is still allowed

**Comment by michalgwo** [comment]
> > I'm not sure if they are literally banning people from operating gas pumps
> 
> If they do not this then self-service is still allowed

Maybe we should rephrase the question then? Tag self_service doesn't imply if the service is banned or not, nor does the wiki (see https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel#Service). I think it will be better to make the question something like this:
Who refuels a car in this gas station?
- Driver
- Gas station employee
- Both are possible

**Comment by matkoniecz** [comment]
`self_service=no` means that self service is banned, in other words "only serviced by attendant"

**Comment by mnalis** [comment]
[self_service=*](https://wiki.openstreetmap.org/wiki/Key:self_service) has few other documented vales too: `yes`, `only`, `partially`, `no`.

**Comment by michalgwo** [comment]
> `self_service=no` means that self service is banned, in other words "only serviced by attendant"

In that case the question "Does this gas station allow self-service?" becomes hard to survey a prone to wrong answers. I bet a lot of people (that's what I would do before this conversation) when they are at a gas station and see that an employee refuels a car, just choose "No". In a gas station where it's normal for gas station employees to refuel your car, no one gonna ask if it's allowed to do it by themselves. Then my proposition becomes even more reasonable.
- If they choose driver -> add tag self_service=yes
- If they choose gas station employee -> add tag full_service=yes
- If they choose both are possible -> add tags self_service=yes and full_service=yes

In this case, we will never set self_service=no nor full_service=no, which could potentially generate a lot of wrong answers.

**Comment by matkoniecz** [comment]
> "Does this gas station allow self-service?" becomes hard to survey and prone to wrong answers.

That is why it is limited to places that often actually ban self-service.

**Comment by westnordost** [comment]
See previous comments.
