### ISSUE TITLE
It's not a street

### ISSUE THREAD

**Issue by MrFotts** [streetcomplete/StreetComplete#4838]
Asking for the name of a street when the "street" is actually just two driveways.  The "Other Answers" button does not offer any useful choice.

![image](https://user-images.githubusercontent.com/122483892/220709269-d2733b46-c275-4c34-af6f-c59aa2370f90.png)

**Comment by matkoniecz** [comment]
Have you tried using "It has no name..." answer in Other answers?

**Comment by matkoniecz** [comment]
I admit that this form also confused me a bit, but not sure is there enough space for that subform to fit directly in Other answers menu.

**Comment by westnordost** [comment]
See here: https://github.com/streetcomplete/StreetComplete/issues/4838#issuecomment-1440489352

Answer that it has no name, the app will then ask you why it has no name. There, you can answer that it is some kind of service road like a driveway.
