### ISSUE TITLE
tactile_paving in crossing : node & way 

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#4839]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:tactile_paving)
Question asked: **Is there a tactile paving ?**

The question should be with two kind with a specific vocabulary [here you have a link to [United Nations article](https://static.un.org/esa/socdev/enable/designm/AD1-04.htm)]: 
NODE : tactile marking with dots
WAY : guide strips with lines

![image](https://user-images.githubusercontent.com/4929752/220756823-b4fd5079-8570-41fc-abb1-9d493e2fa131.png)
![image](https://user-images.githubusercontent.com/4929752/220757843-9e706703-9668-4cba-b377-84ee51b9bc77.png)
DOTS are before a change (crossing, steps) and LINES to give the path to follow.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
NODE : the same tactile_paving question with it's picture could be kept even the option contrasted is not proposed (contrasted-yes-no would be welcome)
WAY : same answers but with other pictures only with guide lines.

**Comment by mnalis** [comment]
I'm not sure I follow "element selection". On which nodes/ways would this question be asked? **ALL** nodes/ways?
That sounds much too spammy. 

Also it seems it misses few things from template:
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

**Comment by JLZIMMERMANN** [comment]
It has been explained in the introduction : first begin in a crossing.
NODE : barrier=kerb
WAY : footway=crossing

**Comment by Helium314** [comment]
Why only dots on nodes, and not strips? If there are strips in place where the image has dots, what should the user answer, and what should be tagged?

**Comment by JLZIMMERMANN** [comment]
Dots are used to warn : before crossing ore raising a stair 
![image](https://user-images.githubusercontent.com/4929752/220853461-69d6f148-4643-4fa7-8876-3c388d47a7bb.png)
Lines are used to be detected as a way to follow in a secure way.
![image](https://user-images.githubusercontent.com/4929752/220853650-8e33dba2-0304-42b2-aa41-b9883570dba5.png)

**Comment by matkoniecz** [comment]
I am confused. Are you proposing a new quest? (in such case for some reason big chunk of template questing is missing) Proposing to modify existing one? (in such case: how exactly)

**Comment by matkoniecz** [comment]
> For kerbs, there is already a quest for tactile paving.

And for ways:

> - [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

**Comment by jmtrivial** [comment]
Hi all.

As described by [JLZIMMERMANN](https://github.com/JLZIMMERMANN), it should be very helpful for blind people to know if a crossing contains guide strips with lines. 

Adding a corresponding question for each way describing a pedestrian crossing might be a good way to improve the quality of the accessibility information.

+1 !

**Comment by Helium314** [comment]
Related issue: #3534

> Dots are used to warn : before crossing ore raising a stair

What should be done in places where your claim is incorrect and there are lines before a crossing, in the place your images show dots?

**Comment by Okeenea** [comment]
Hi everybody,

Like JLZIMMERMANN explained, guide strips and raised dots are two different solutions. They don't serve the same purpose.

Guide strips are meant to guide blind and visually impaired people to reach the other side of a crossing or a point of interest in a venue. They enable them to get around by themselves. 

Raised dots warn people of a potential danger like the beginning of a crossing, the presence of stairs or the end of a subway platform. This equipment don't help them get around. It's just here to make them safe. Raised dots are meant to keep them alert and prevent them from falling.

**Comment by mnalis** [comment]
> Raised dots warn people of a potential danger like the beginning of a crossing, the presence of stairs or the end of a subway platform

@Okeenea is that worldwide or country specific? Because, if you look at images in https://github.com/streetcomplete/StreetComplete/issues/3534, it seems that strips instead of dots are sometimes used to indicate start/end of stairs, which (if I understand your claim correctly) should be dots instead.

**Comment by Helium314** [comment]
> @Okeenea is that worldwide or country specific? Because, if you look at images in #3534, it seems that strips instead of dots are sometimes used to indicate start/end of stairs, which (if I understand your claim correctly) should be dots instead.

Such situation is what I was asking for. Simply ignoring/denying existence of lines in places where "dots are used" by repeatedly stating what dots "are used for" is not helping at all.

Further example: https://oekastatic.orf.at/mims/2019/41/17/crops/w=1280,q=60,r=1.5/326050_bigpicture_102817_img_0561.jpg?s=a3cd8914a0304b0e143c38dff422154878e47003

**Comment by mnalis** [comment]
> NODE : barrier=kerb
> WAY : footway=crossing

There [already exists](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#tactile_paving) `Does this crosswalk have tactile paving on both sides?`  and `Is there tactile paving on this curb here?` quests.

So as those quests seem to be already asked, but it is unclear if @JLZIMMERMANN is unaware of that quests existence, or if they are proposing some change to that quest or a quest with different objective? (that is probably because half of the template wasn't filled, as well as language barrier)

---

Additionally on the subject, it would be good to be able to mark `tactile=paving` on `highway=footway` too, but that would need an overlay instead of quest, as it would be too spammy otherwise (it was suggested in https://github.com/streetcomplete/StreetComplete/issues/4349 but as too broad - too many things to tag, so if someone wanted to [propose overlay](https://github.com/streetcomplete/StreetComplete/blob/master/OVERLAY_GUIDELINES.md) just for editing `tactile_paving=*` information on various ways/nodes, that would be far more likely to be accepted. Just please fill the template fully and with as much information as possible)

**Comment by JLZIMMERMANN** [comment]
> it would be good to be able to mark `tactile=paving` on `highway=footway`
In my idea a first beginning is to qualify 'footway=crossing' at least and then push the tag tactile_paving using a picture with guiding strip as example.
![image](https://user-images.githubusercontent.com/4929752/220915335-2244590a-4032-40e6-b062-2f61955f8a09.png)

**Comment by matkoniecz** [comment]
In such case which specific changes you are proposing to existing quests?

To the element selection? Pictures? What is being tagged? Question shown to user?

Please be specific.

**Comment by JLZIMMERMANN** [comment]
> To the element selection? Pictures? What is being tagged? Question shown to user?

Element selestion : WAY 'footway=crossing'
Pictures : 
Tagged : in an ideal way it would be tactile_paving=contrasted,yes,bad,no
![image](https://user-images.githubusercontent.com/4929752/220941096-18de8d8e-b2aa-4f0a-bd15-753d602073c2.png)

![image](https://user-images.githubusercontent.com/4929752/220940661-94948e44-35ab-46dc-8249-94fd58ee59a5.png)

![image](https://user-images.githubusercontent.com/4929752/220940306-e0922aa2-af1e-4cd6-afe6-63029fd8bd19.png)

![image](https://user-images.githubusercontent.com/4929752/220941886-72c6bda0-a898-4768-92de-1a43be251fd1.png)

Question shown : Is there a guiding strip on this crossing ?

**Comment by matkoniecz** [comment]
Is there any area where 

> - [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

would be fulfilled?

**Comment by JLZIMMERMANN** [comment]
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

This quest will be less than kerb that are already displayed, so yes it's not a spam quest ;-)

**Comment by matkoniecz** [comment]
It is NOT about number of questions.

Is it about whether overwhelming percentage of quests have the same answer.

**Comment by JLZIMMERMANN** [comment]
> overwhelming percentage of quests have the same answer

Very few crossings have such answers for blind people. Maybe it could be a default desactivated quest like some that are already liek this (roof...).
However, it would be welcome to push such question when tactile_paving are in each part of the kerb.

**Comment by matkoniecz** [comment]
> Very few crossings have such answers for blind people.

In which area? Maybe it should be disabled there again.

**Comment by JLZIMMERMANN** [comment]
> In such case which specific changes you are proposing to existing quests?

About the existing quest the is a picture that is not relevant : crossing needs dots mainly 
![image](https://user-images.githubusercontent.com/4929752/221024173-3e149b27-42c0-4b30-8f85-1d07e8bdd66b.png)
The picture to suppress is the mmeting of 2 guiding strips.
![image](https://user-images.githubusercontent.com/4929752/221024761-b4698812-1aaa-42f2-a4b2-9b91b07b643a.png)

**Comment by mnalis** [comment]
> About the existing quest there is a picture that is not relevant : crossing needs dots mainly
>  The picture to suppress is the meeting of 2 guiding strips.

Thanks @JLZIMMERMANN, you opinion seems clear in this post too! 

However, I think you are wrong is this case about "dots". It may be that dots are always used _**your**_ country, but it does not seem to be the case **worldwide**. E.g. see example picture provided by @Helium314 above: https://oekastatic.orf.at/mims/2019/41/17/crops/w=1280,q=60,r=1.5/326050_bigpicture_102817_img_0561.jpg?s=a3cd8914a0304b0e143c38dff422154878e47003: 
it is clearly a crossing, and it clearly uses `tactile_paving`, yet it **does not** use dots but orthogonal stripes. So some picture representing that option should definitely remain, as StreetComplete is supposed to be used in whole world.

**Comment by JLZIMMERMANN** [comment]
> it does not seem to be the case **worldwide**
Please consider the link I gave above from United Nations : 
![image](https://user-images.githubusercontent.com/4929752/221041115-d93bbd01-5d13-4d15-a909-897fde4021cd.png)

The picture you show is a very bad situation create a guiding strip in oblical way is dangerous.

**Comment by JLZIMMERMANN** [comment]
> * it would enable possibility to mark `tactile_paving=*` on other `highway=footway` and similar tags too (which would actually be quite useful in Croatia too, as we have those too and need to map them more, e.g. https://www.openstreetmap.org/way/358984327)

Indeed this is a very good example (in [Zagreb](https://www.google.com/maps/@45.7999579,15.9784532,3a,44.3y,217.77h,66.38t/data=!3m6!1e1!3m4!1sFn3oAz0niQJceM_lMxbG9g!2e0!7i13312!8i6656)) : LINES for paths and DOTS for awaring pedestrians
![image](https://user-images.githubusercontent.com/4929752/221042553-1032f792-c16c-4c25-8e58-601512b993f5.png)

**Comment by Helium314** [comment]
> The picture you show is a very bad situation create a guiding strip in oblical way is dangerous.

Yet it is reality, and you still didn't provide any useful information what the user should do/answer in such situation, and what should be tagged.
Note that this situation **must** be answerable (as per quest guideline you decided to omit: "Any answer the user can give must have an equivalent tagging").

**Comment by westnordost** [comment]
Uhh, so anyway, after reading through it I still not fully understand what this quest suggestion is really about. But anyway:

1. If it is about asking whether crossings (e.g. `highway=crossing`) have tactile paving: There is already a quest for that - `AddTactilePavingCrosswalk`

2. Adding the same information (whether the crossing has tactile paving or not) to crossings additionally mapped as ways (`highway=footway` + `footway=crossing`) would duplicate the information from the `highway=crossing` node at no gain. Also, that's not common practice.

3. If it is about recording whether there is tactile paving on each side separately (at the curbs), i.e. also when the ways are separately/micro-mapped, there is also already a quest for that, `AddTactilePavingKerb`.

4. if it is about recording the **pattern** of tactile paving on crossings or kerbs (dots, lines, lines in different directions, ...), there is 
    1. no approved tagging schema for that
    2. as the images posted here show, oftentimes both are used, the orientation of the stripes matter etc., so [this draft proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/detailed_tactile_paving) would be kind of problematic anyway for use on `highway=crossing` or even `barrier=kerb`

5. if it is about adding orientation lines made with tactile paving at their real geographic position (as shown in the last photo), this is not even anything that can be done with StreetComplete. So any further deliberation if there is a tagging schema, if it has a useful purpose, if it makes sense to do with the app etc. is superfluous

6. if it is about adding whether crosswalks do have continuous orientation lines across the whole crossing as shown in the second picture of [this post](https://github.com/streetcomplete/StreetComplete/issues/4839#issuecomment-1441354403), this does not fulfill the quest guidelines as a vanishingly small number of crossings have such paving, so it would be spammy to ask for every crosswalk with tactile paving. (Also, it is not clear how to tag this.)

**Comment by matkoniecz** [comment]
one specific suggestion was in https://github.com/streetcomplete/StreetComplete/issues/4839#issuecomment-1442399866 but it seems that no matter whether it is a good idea or not some places use lines in such situation

**Comment by JLZIMMERMANN** [comment]
The french page about tactile_paving has been improved. I'm doing also the same with other tags about disabilities to let understand more situations with good pratices or less.
(https://wiki.openstreetmap.org/wiki/FR:Key:tactile_paving)
