### ISSUE TITLE
Enable to add vacant shop in the shop overlay, remove workaround (requires 6.1.0 iD presets)

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#4842]
**Use case**
When mapping shops with overlay, I think it's better to map all shops, even vacant ones, if any, to have fulfill completion. It's now only possible with a trick : you have to create a shop (don't care wich type ) in shop overlay, then answer a quest of this shop "other option" "it's vacant".

**Proposed Solution**
While searching for types of shops in shop overlay, add a "vacant shop" entry.

Thanks!

**Comment by westnordost** [comment]
It's not possible to search for "vacant shop" because this is not an iD preset and the search is based on the iD presets. Are you not able to mark it as vacant using the "..." button?

**Comment by matkoniecz** [comment]
And potential upstream change is discussed inhttps://github.com/openstreetmap/id-tagging-schema/issues/602

**Comment by rhhsm** [comment]
I think it's already simple enough to add one: in shop overlay, press the red + button at the right location, select the 3 dots, and choose "It's vacant" (only option).

**Comment by westnordost** [comment]
Good,  so if that's working correctly, this is the working solution. The other solution is blocked by that iD ticket

**Comment by letypequividelespoubelles** [comment]
@rhhsm works perfectly, haven't seen it. Thanks.

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/id-tagging-schema/pull/828 was accepted, so it seems that after upgrade to 6.1.0 id presets it will be possible to remove that "can't say" workaround
