### ISSUE TITLE
Sidewalk overlay rendering issue 

### ISSUE THREAD

**Issue by brierjon** [streetcomplete/StreetComplete#4844]
Steps and Road crossings often have rendering artifacts where they won't display and when moving the screen flicker display and no longer display.

![Screenshot_20230223-092325.png](https://user-images.githubusercontent.com/717866/220935681-0f8810f9-7667-496c-8aeb-7f7dae2582ec.png)

**How to Reproduce**
Step rendering issue:
Enable Sidewalks overlay
View steps and crossings
See rendering of overlay disappear in some sections. When moving the map the overlay will at these points display and disappear.

**Expected Behavior**
Rendering of steps and intersections as normal when the overlay is enabled.

**Versions affected**
Android 13 build TQ1A.230205.001.D2 and StreetComplete version 51.0 on Pixel 5

**Comment by matkoniecz** [comment]
I noticed it already before - it was occasionally appearing far before overlays.

**Comment by westnordost** [comment]
It would be more helpful to post a short screenrecord. But either way, this is unfortunately something that cannot be fixed as the map rendering is done by an external library called tangram-es. You could create an issue there,  but by now the project has become pretty much abandoned so not really a chance it will be fixed.
