### ISSUE TITLE
sometimes SC doesn't recognize separately mapped sidewalks

### ISSUE THREAD

**Issue by Lukas458** [streetcomplete/StreetComplete#4845]
Hi,
sometimes it seems, that StreetComplete does not recognize a separately mapped sidewalk, even though its close to the street and mapped with footway=sidewalk.

**Examples:**

https://www.openstreetmap.org/note/3283819

https://www.openstreetmap.org/note/3451355

https://www.openstreetmap.org/note/3283820

**How to Reproduce**
Find a highway where the sidewalk is separately mapped, but maybe not 100% close to the highway.

In the examples given, there is nothing betwenn the highway and the sidewalk! (so no trees, parking lines or something). Otheriwse I would understand that SC cannot recognize the sidewalk, but so I do not understand it.

**Expected Behavior**
SC does not ask about the sidewalk's surfaces (and other thing like smoothness) at those pieces of roads, because the sidewalk is mapped separately there, so SC should ask for it at the sidewalk ways themselves.

**My question**
Why does SC not recognize that the sidewalk is mapped separately there?

**Issues**
Can led to mapping mistakes if user do not look closely but just answering SC's quest.

**Versions affected**
47.0

**Comment by Helium314** [comment]
https://www.openstreetmap.org/note/3283819 has `sidewalk=right`. If the sidewalk is mapped separately, it should have `sidewalk=separate`, or better `sidewalk:right=separate`.

**Comment by Lukas458** [comment]
Oh, I see...

Thanks.

I believe then the mapper made the mistake of answering the quest "is there sidewalk here?" from SC first with "yes, right" and then to map the sidewalk again separately.

**Comment by Helium314** [comment]
It's quite common that users add sidewalk paths and don't adjust the sidewalk tags of nearby roads. Though from reading the wiki, it's not clear whether `sidewalk=right` actually is a mistake when a separately mapped sidewalk exists.

**Comment by Lukas458** [comment]
Hmm,
the first that mappers often forget to adjust the sidewalk tags is definetely correct.

When reading https://wiki.openstreetmap.org/wiki/Key:sidewalk#Separately_mapped_sidewalks ,
it's relatively claer to me that people have to use sidewalk=separate or better sidewalk:right=separate if the sidewalk on the right side is separately mapped, sidewalk:left=separate if the one on the left side is mapped separately.

But as I know, on another wiki page the instructions may differ :DD

**Comment by matkoniecz** [comment]
Also, note that sidewalk overlay allows relatively easy fixes of such mistakes.

There is a really complex logic to avoid asking "is there sidewalk here" quest in presence of separately mapped `highway=footway` representing sidewalks but it trusts OSM data where sidewalk is mapped (for example that separate way could be on other level and displaced vertically).

>  Can led to mapping mistakes if user do not look closely but just answering SC's quest.

It is ugly double mapping and kind of wrong but horrifically wrong.

I think that this issue can be closed? And if a common problem maybe something can go into "can't say" menu.
