### ISSUE TITLE
No quests for traffic islands at crossing points on tertiary links

### ISSUE THREAD

**Issue by NathanARF** [streetcomplete/StreetComplete#4847]
Quests asking for traffic islands on crossing points (i.e. _Does this pedestrian crossing have an island?_) do not appear for `crossing=marked` or `crossing=uncontrolled` nodes on `highway=tertiary_link` ways. This may apply to other 'links' such as `highway=secondary_link`, though I have not tested this.

**How to Reproduce**
Go to a `crossing=marked` or `crossing=uncontrolled` node - on a `highway=tertiary_link` way - that does not have the tag `crossing:island=*` and scan for quests. The quest to specify whether there is a traffic island does not appear.

**Expected Behavior**
The quest to specify a traffic island at the crossing point should appear.

**Versions affected**
I am using StreetComplete version 51.0 on Android version 11

**Comment by matkoniecz** [comment]
Can you give examples of such ways where quest is missing and `oeway=yes` / `oneway=-1` is missing?

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_island/AddCrossingIsland.kt is disabled for oneway roads as

(a) islands there are unlikely

(b) very often ways are dual carriageways - not sure whether in such cases island between two carriageways should be tagged as a property on each crossing

**Comment by NathanARF** [comment]
I did not think about the `oneway=*` tag but that does indeed seem to be the case. My apologies then as this is disabled by default.
