### ISSUE TITLE
New Question: What kind of turning point/circle is this?

### ISSUE THREAD

**Issue by prx-lmo** [streetcomplete/StreetComplete#4854]
### General
Affected tag(s) to be modified/added: [Key:turning_circle](https://wiki.openstreetmap.org/wiki/Key:turning_circle)
Question asked: **What type of turning point/circle is this?**
Possible Answers are:
- circle
- oval
- knuckle
- hammer
- square

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Node tagged with [highway=turning_circle](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_circle)

**Metadata needed:** 
Not according to osm wiki

**Proposed UI:**
just take the pictures from the wiki

**Comment by arrival-spring** [comment]
Can you explain what the purpose of this tag is. Is there anything using it at all?

**Comment by Cj-Malone** [comment]
Rendering is the obvious answer, although I don't know if any use it yet.
