### ISSUE TITLE
Movement direction of escalators

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4857]
### General
Affected tag(s) to be modified/added: `https://wiki.openstreetmap.org/wiki/Key:conveying`
Question asked: **In which direction is this escalator moving?**
Answers: conveying=forward, backward, reversible

### Checklist

- [x ] 🚧 To be added tag is established and has a useful purpose. _Movement direction is essential info for pedestrian routing apps_
- [x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x ] 💤 Not an overwhelming percentage of quests have the same answer (No spam) _Of the escalators mapped with movement direction, 75% go forward, 17% backward, and about 8% both ways_
- [x ] 🕓 Applies to a reasonable number of map data (Worth the effort) _Of the 23.000 escalators mapped, about half have no movement direction info._

### Ideas for implementation

**Element selection:** 
Ways tagged with `highway=steps`, `conveying=yes` Might be expanded to ways tagged with `highway=footway`, `conveying=yes` (moving walkways).

**Proposed UI:**
Can look like the steps incline quest (arrows for forward and backward directions, double-headed arrow for reversible). I hope that using it as a start, it's not much work so worth the effort. In fact escalators are not included in the steps incline quest, but maybe they should. However the question phrasing should be adapted so it is clear that for the incline quest, it is asked which is the upper end of the escalator, while for the movement direction quest, it is asked in which direction it moves.

**Comment by arrival-spring** [comment]
How could I tell if an escalator is reversible or not?

**Comment by rhhsm** [comment]
Like this one? https://youtu.be/SpyViFhWXH4?t=36 Maybe others are not signed, so the surveyor would have to try them out.

**Comment by arrival-spring** [comment]
If it's not always signed, or requires surveying at multiple different times then that somewhat clashes with "Easily answerable by any pedestrian from the outside"

**Comment by matkoniecz** [comment]
on the other hand reversible ones are really rare...

**Comment by FloEdelmann** [comment]
They are not that rare in Munich. However, many reversible escalators are configured to only go up during the winter, to avoid bringing snow and moisture into the station buildings:

> Manchmal fahren die Rolltreppen ganz bewusst nur in eine Richtung: nach oben. Wenn viel Schnee fällt, soll so weniger Nässe und Splitt nach drinnen gelangen. Die Techniker sagen, dass man so größere Pannen vermeiden kann.

*(from https://www.sueddeutsche.de/muenchen/nahverkehr-wieso-rolltreppen-der-mvg-gefuehlt-so-oft-defekt-sind-1.2649157, at the very bottom)*

**Comment by rhhsm** [comment]
This quest would definitely need the "Other answers" option for cases which are hard to tell , for seasonally reversible ones, etc., so users can leave a note.

**Comment by FloEdelmann** [comment]
> seasonally reversible ones

That is hard (if not even impossible) to survey though, if you don't come around the same escalator during both summer and winter.

**Comment by rhhsm** [comment]
> > seasonally reversible ones
> 
> That is hard (if not even impossible) to survey though, if you don't come around the same escalator during both summer and winter.

Many things we survey are changeable: restaurants have outdoor seating that doesn't work in winter, street lighting may break and get repaired, a road's smoothness gets worse in winter and is repaired every spring, etc. We should not allow perfect to be the enemy of good. An escalator that can work reversibly but doesn't in winter is still a reversible escalator, I think. So maybe the answer options should be "It moves up", "It moves down" or "It can move in both directions", where the direction in which the reversible one moves may depend on current demand, rush hour, season, etc.

**Comment by westnordost** [comment]
So, escalators conveying in one direction are basically oneways for pedestrians. So I understand that in theory this information may be useful for pedestrian routing.

However, do places exist in reality where there is only one escalator going in one direction only and there is no way to go in the other direction (via non-conveying steps or an escalator in the other direction)? I kind of doubt that. And if there are places like that, I would expect that they are so rare that they do not justify adding (and maintaining) this info for every single conveyor.

**Comment by rhhsm** [comment]
I agree that most escalators have steps or another escalator going in the other direction close by. But they may be in different locations that a pedestrian routing app needs to direct its users to. This cut from a Sofia metro station 3D map shows that a platform can be reached in 4 ways, one with steps+escalators and 3 with only escalators. A navigation app needs to know the movement direction of the escalators to be able to send the user correctly and efficiently down one of the ways to the platform. One of the station exits can only be reached from the platform by escalator, but which one to take?
![image](https://user-images.githubusercontent.com/69100427/224387451-001d1b69-2df3-4fa9-8292-53fc13d147af.png)

Movement direction is prominently mentioned for escalators in the OSM wiki and the ID preset. Compared to the many quests for steps, asking only for movement direction and incline for escalators is not much, I think.

**Comment by mnalis** [comment]
I agree that escalators going up, and escalators going down are often in (sometimes quite) different locations, and that is annoying when you arrive at the wrong one. 

However (at least in Croatia), vast majority of escalators are in malls and other **indoor spaces**, where the **pedestrian routing doesn't work** anyway, so the usability here is currently very low.  Without precise working indoor-navigation it is also very hard to map or even know which escalator SC is really asking about. Given target SC audience (which are mostly not fluent in inner working of GPS and other navigation technologies), it is an additional problem.

Now, I can imagine a future when all malls have bluetooth beacons (or newer tech) and pedestrian navigation indoors works very precisely. I don't see happening in next decade or few, though. Perhaps when presence of [indoormark=beacon](https://wiki.openstreetmap.org/wiki/Tag:indoormark=beacon) manages to [rise](https://taginfo.openstreetmap.org/tags/indoormark=beacon#chronology) by few orders of magnitude? Or only ask for escalators not having `indoor=yes/...` tag and not being inside `building=*` polygons (that might be expensive, though)?

**Comment by matkoniecz** [comment]
> However, do places exist in reality where there is only one escalator going in one direction only and there is no way to go in the other direction (via non-conveying steps or an escalator in the other direction)? I kind of doubt that. And if there are places like that, I would expect that they are so rare that they do not justify adding (and maintaining) this info for every single conveyor.

In theory pedestrian routing can give bonus for routing when escalator matches direction of travel.

But not really convinced even myself with that argument.

**Comment by rhhsm** [comment]
Good point, @mnalis ! I'm starting to wonder why indoor mapping should be done at all...

**Comment by westnordost** [comment]
Why would routing not work indoor? I mean, as long as the corridors also have `highway=footway` going through them, it should be fine, no?

....

Hm right, it doesn't (with none of OSRM, Graphhopper or Valhalla)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=53.55208%2C9.99402%3B53.55173%2C9.99586#map=19/53.55187/9.99491

https://indoorequal.org/#map=18.28/53.551467/9.995975&level=3&poi=way:1000656488

.... but that doesn't mean that it couldn't work one day. I see nothing that would make it technically impossible to support  `level` for routing.

**Comment by rhhsm** [comment]
Routing depends on the app knowing where you are, and with GPS generally not being available indoor and other means in their infancy, it doesn't work indoor. The other useful application I can imagine is having a map on your phone or paper, but then this needs to render the movement direction of the escalator. That is probably not available either. Even the Sofia Metro map above doesn't show the movement direction of the escalators.
I guess this quest is "nice to have", but I can imagine there's higher priority work to be done first.

**Comment by westnordost** [comment]
Well, then, taking all this into account, I think it is not worth creating a quest then.

**Comment by kmpoppe** [comment]
Together with #5904, this might be a good combo addition - asking for the direction of a coveying object and then asking for the duration.

I don't really see why indoor mapping would be not worth the effort, malls in my neck of the woods have indoor WiFi and good GPS coverage. 

I agree that that's not representative and I also agree that comparatively few objects would be affected, but in combination the effort might start the usage for Vanilla SC for indoor mappers?

K

**Comment by westnordost** [comment]
Do (some) routers now work with OSM objects as targets, rather than the geo position? Vertically reading this quest suggestion, it sounds to me that back then I deemed it not worth creating because no router is able to do proper indoor routing.

Proper indoor routing would require that one can set a certain OSM object as a target (because that object can have a `level`) rather than a geo-position, which comes without a level information. I just tried again on the OSM website and it exclusively uses addresses / geo positions. But maybe that's just the interface.

**Comment by FloEdelmann** [comment]
There are certainly indoor routers like e.g. used in the KDE Kongress app: https://www.volkerkrause.eu/2024/07/06/kde-kongress-venue-maps.html

I don't know if it takes escalator directions into account, but it certainly could and should.

**Comment by matkoniecz** [comment]
Even for only taking geo position it may be still useful, for example when navigating to train station you often go through mall.

https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=50.065876%2C19.946116%3B50.067408%2C19.947583#map=18/50.066681/19.947819

![screen](https://github.com/user-attachments/assets/005c4ca7-14a3-45b9-8a6c-381603a78fbc)

**Comment by matkoniecz** [comment]
BTW, this specific route seems wrong as https://www.openstreetmap.org/way/766325866 is missing direction info.

**Comment by matkoniecz** [comment]
Though I worry about high bad answer rate - indoor multilevel objects where multiple objects can overlap on the map are really highly confusing to map, even to experienced people. And I got some reports about StreetComplete mappers being confused at higher rate than mappers in general.
