### ISSUE TITLE
Add "24/7" and "automatic" answer options to other lighting quests

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4859]
Currently the "Lit" quest has the answer options `24/7` and `automatic` available, as "Other answers" in the simple quest and as 2 additional icons (which I like more) in the overlay. Is my assumption correct that adding these answer options to other lighting quest such as the public transport stop/platform lighting quest and the sports pitch lighting quest would be very simple (copy-paste some code)? The use case I have in mind is underground subway platforms which are of course always lit, but there may be a few more (indoor tennis halls, for instance).

**Comment by rhhsm** [comment]
There are very few use cases indeed, so it should only be done if it is very little effort (which I hope it is).
There are above-ground subway stations that are not permanently lit.

**Comment by westnordost** [comment]
Because they are lit by a giant lightbulb in the sky
