### ISSUE TITLE
Ask if restaurants have a wheelchair accessible toilet where `toilets` is not already mapped

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4866]
**Use case**

Wheelchair accessibility of toilets is important information(`toilets:wheelchair`). The quest `AddWheelchairAccessToiletsPart` collects this for anywhere with
```
toilets = yes
and name
and access !~ no|private
```
(and resurvey)

In some countries, essentially all restaurants have toilets and many are not marked with `toilets=yes` so this quest would not show.
(See #1272 and #4860 for reasons for not asking for toilets for all restaurants).

**Proposed Solution**
Extend the element selection to include `amenity~restaurant|pub|bar` or `amenity~cafe|fast_food and indoor_seating=yes` without `toilets=no`. Also, add an other answer "There is no toilet here" to add `toilets=no`
Options:
1) Only apply that extra bit only in countries known to require toilets in restaurants (research to be done).
2) Apply that everywhere, since `AddWheelchairAccessToiletsPart` is disabled by default anyway.

**Comment by westnordost** [comment]
I think this could actually also be done in countries where toilets may not be legally required but at least somewhat to be expected.

**Comment by arrival-spring** [comment]
So not all the way to option 2 then, of just doing it everywhere?
Which countries I wonder don't expect toilets in restaurants at all?

**Comment by rhhsm** [comment]
Maybe assume that the large majority of restaurants worldwide have toilets, and wait for complaints from countries where this is not the case... (i.e. it should be made such that the quest is easy to switch off for certain countries)
