### ISSUE TITLE
Add clarification for cycleway width quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4867]
**Use case**
It is unclear what should be answered for `How wide is the bicycle path here`. Sure, it is clear in the most simple scenario (single oneway bicycle track), but is ambiguous in other cases.

E.g.
- where there are two cycletracks, each going in one direction. Should user measure width of one lane, or of both of them? e.g. like [here](https://www.openstreetmap.org/note/3577916#map=19/45.80039/15.97907): 
![small_134638](https://user-images.githubusercontent.com/156656/224446405-a8325dc4-3747-46a1-ae70-c70ac3be5592.jpg)

- when same path contains a footway, and two cycle tracks (one on each side of a footway), like for example [here](https://www.openstreetmap.org/note/3534932#map=19/45.79525/15.91931&layers=N): 
![small_129932](https://user-images.githubusercontent.com/156656/224446469-6f364de9-4768-4e9d-aafa-17f10d193eb6.jpg)

**Proposed Solution**
Quest should clarify what exactly is wanted of user, in the manner that `road width` quest does:
![small_Screenshot_20230311_000404_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/224446144-2597d3ad-a19a-4924-844c-a9113bd4a53b.jpg) vs. ![small_Screenshot_20230311_000422_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/224446118-b53de942-7a41-450f-8399-f7b91fc9eb9c.jpg)

**Comment by matkoniecz** [comment]
Which text you would propose?

--------------------------------------------

For the first case it clearly asks about cycleway width (bicycle path width), and this cycleway is formed by two lanes.

For the second I would leave note.

**Comment by mnalis** [comment]
> Which text you would propose?

Well I was hoping for some suggestions here; coming up with _short_ explanations has never been my forte :smiley: 

> For the first case it clearly asks about cycleway width (bicycle path width), and this cycleway is formed by two lanes.

I'm glad it is clear to you, because even after your explanation it is not clear to me.

So, your opinion is that in `cycleway:width=*` it should be recorded **width of both cycling lanes added together** (i.e. double the width of one cycleway lane)? So would I say too, but only with knowledge of wiki tags, like how [width:carriageway=*](https://wiki.openstreetmap.org/wiki/Key:width:carriageway) is defined. 

For the uninitiated to inner wiki definitions, however, it would seem way more intuitive that that is the width of one cycle way (one lane for cycling going in one direction), e.g. if I have cargo bike `1.9 m` wide:
- I can just barely use `highway=cycleway` + `oneway:bicycle=yes` + `cycleway:width=2.0`
- but I **cannot** safely use `oneway:bicycle=no` + `cycleway:width=3.0` (as I'll keep crashing to other bikes coming towards me as I'm eating heavily into their cycle lane).

> For the second I would leave note.

But why should there be any difference? In both cases it is exactly this:

```
highway=path
foot=designated
bicycle=designated
oneway:bicycle=no
segregated=yes
```

The only difference is (unrecorded) _finesse_ in the layout of that cycleway lanes and footway: 
- whether two cycleway lanes are separated just by `5 cm` white line, or 
- if two cycleway lanes are separated by `2.5m` footway.

Should the meaning of `cycleway:width`  vary depending on that difference in layout, even if the tagging above does not give a hint about the difference? That would make `cycleway:width` ambiguous.

**Comment by mnalis** [comment]
Digging deeper, I've found that `cycleway:width=*` (that this quests uses) is not really defined in the wiki.

- [width=*](https://wiki.openstreetmap.org/wiki/Key:width) wiki seem to mention it only in context of roads
(_"[cycleway:side:width](https://wiki.openstreetmap.org/wiki/Key:cycleway#Supplementary_details) and [sidewalk:side:width](https://wiki.openstreetmap.org/wiki/Sidewalks#Sidewalk_as_refinement_to_a_highway) are the width of cycle paths and sidewalks if they are mapped on the roadway"_)

- wiki for `Key:cycleway:width` redirect to [cycleway=*](https://wiki.openstreetmap.org/wiki/Key:cycleway) wiki, which also only talks about
 _"If tracks or lanes for bicycles are tagged on a highway [...]"_ and only gives examples of _"cycleway:[right](https://wiki.openstreetmap.org/wiki/Key:right):[width](https://wiki.openstreetmap.org/wiki/Key:width)=3, cycleway:[left](https://wiki.openstreetmap.org/wiki/Key:left):[width](https://wiki.openstreetmap.org/wiki/Key:width)=2.5"_

Neither of them mentions `cycleway:width=*` so one is left to guess... 

I guess that wiki for `cycleway:width` should be created with _some_ definition. If we all agree what is meant by that tag. Any takers?

---

Anyway, back to the title of this ticket, perhaps explanation along the lines of:

 _"If there is more than one cycling lane bundled together, please measure the combined width of all such lanes, going in all directions.  Measure whole cyclable surface, from painted line to painted line, or kerb to kerb.  Do not include width of sidewalks if present.  if cycling lanes are separated by footway or other things with significant width, or if unsure how to answer this quest, please leave a note with a picture."_

would at least cover known cases (if we agree that it is what is meant) and explain to users when to shift responsibility to more capable editors in other cases (so e.g. my second picture might be more clearly tagged as `highway=footway` + `foot=designated` + `bicycle=designated` + `segregated=yes` + `cycleway:left:width=0.8` + `cycleway:right:width=0.8`)

But preferably shorter and clearer, if someone can help :smiley:

**Comment by matkoniecz** [comment]
> So, your opinion is that in cycleway:width=* it should be recorded width of both cycling lanes added together (i.e. double the width of one cycleway lane)?

I would expect it to be recording width of cycleway (which may have turn lanes, for example), not of width of cycleway in one direction. Not entirely sure what to expect when cycleway is in parts.

> But why should there be any difference? 

Because first has single cycleway, second has two of them - but both are tagged as a single way.

> Digging deeper, I've found that cycleway:width=* (that this quests uses) is not really defined in the wiki.

Doing this would also help.

**Comment by riQQ** [comment]
> when same path contains a footway, and two cycle tracks (one on each side of a footway), like for example [here](https://www.openstreetmap.org/note/3534932#map=19/45.79525/15.91931&layers=N):
>
> ![picture](https://user-images.githubusercontent.com/156656/224446469-6f364de9-4768-4e9d-aafa-17f10d193eb6.jpg)

Shouldn't this be mapped as 2 separate cycle ways as they are physically separated?

**Comment by BalooUriza** [comment]
> Shouldn't this be mapped as 2 separate cycle ways as they are physically separated?

Yes.

**Comment by matkoniecz** [comment]
> Shouldn't this be mapped as 2 separate cycle ways as they are physically separated?

That is tricky as it is common and normal to treat such crossing as one element and combined segregated footway and cycleways are often mapped as a single object.

**Comment by westnordost** [comment]
I've read through this ticket and I do not think that the wording needs to be changed. The shown example with two cycleway markings (mapped all as one way) is an edge case where I would think it is completely fine to leave a note when the user is unsure. After all, this is not even anything specific to StreetComplete.

The answer to your question(s) is that it is always the whole width of the cycle path, i.e. all its lanes. If there are several physically separate lanes but they are mapped as one way in OSM, then it would be the width of all those lanes added together.
