### ISSUE TITLE
Crash: GridLayoutManager already attached to RecyclerView

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4869]
I received a SCEE crash report about `GridLayoutManager` being already attached to a `RecyclerView` (in code that is unchanged from StreetComplete):

       java.lang.IllegalArgumentException: LayoutManager androidx.recyclerview.widget.GridLayoutManager@42dde9a is already attached to a RecyclerView: androidx.recyclerview.widget.RecyclerView{676e3cb VFED..... .......D 0,53-980,2207 #7f0901d1 app:id/list}, adapter:de.westnordost.streetcomplete.view.image_select.GroupedImageSelectAdapter@40907a8, layout:androidx.recyclerview.widget.GridLayoutManager@42dde9a, context:de.westnordost.streetcomplete.screens.MainActivity@d280748

in
https://github.com/streetcomplete/StreetComplete/blob/4c01d0ff5a84ce71983b1fed0db26594aa00ee0b/app/src/main/java/de/westnordost/streetcomplete/quests/AGroupedImageListQuestForm.kt#L65

This is might be caused by `onViewCreated` being called twice after the form is created, which apparently can happen: https://stackoverflow.com/questions/23593965/when-would-fragments-ondestroyview-be-called-but-it-wouldnt-be-destroyed

Probably the adapter should be removed from the view in `onDestroyView`, or be created in `onCreateView` or `onViewCreated` (which would require a lot of quest forms to be adjusted, as they use `imageSelector` in `onCreate`).
Same issue likely applies to `AImageListQuestForm`.

**Comment by westnordost** [comment]
Hm, the issue is that the `RecyclerView` holds a reference to something outside of the view lifecycle: The `GridLayoutManager`. When the view is cleared, `GridLayoutManager` survives this because it is owned by `GroupedImageSelectAdapter` and since it still holds onto the `RecyclerView` of the cleared view, this is actually also a memory leak.
