### ISSUE TITLE
kerb and tactile_paving on ways and crossing-nodes

### ISSUE THREAD

**Issue by Nadyita** [streetcomplete/StreetComplete#4870]
**Problem**
SC always asks whether a crossing has tactile paving and what kind of kerb is there, even if there is already a way that is part of the crossing, that has these features mapped

An example would be [this crossing node](https://www.openstreetmap.org/node/9961851740).
The crossing node gets `tactile_paving=no` + `kerb=flush`, although [the crossing way](https://www.openstreetmap.org/way/1087252760) already has 2 nodes ([this](https://www.openstreetmap.org/node/9961851741) and [that](https://www.openstreetmap.org/node/10577000575)) with `barrier=kerb` + `kerb=flush` + `tactile_paving=no`

**Expected Behaviour**
If a `footway=crossing`, `cycleway=crossing` or `path=crossing` path crosses the `highway=crossing` and already has 2 nodes with `kerb=*` or `tactile_paving=*` as part of it, then SC should not ask about kerbs and/org tactile paving. The information on these 2 nodes is more precise (since it has the actual location of the kerb/tactile paving) and the one on the crossing node itself just redundant.

**Versions affected**
probably all, but at least v51.1

**Comment by mnalis** [comment]
- see https://github.com/streetcomplete/StreetComplete/issues/3407

**Comment by Nadyita** [comment]
So it's too complicated to figure out and thus, we don't do it :roll_eyes: 

> If the kerb is identical on both sides of a crossing and the location of the actual kerbs is not clear (e.g., due to a lack of high resolution imagery), `kerb=*` is sometimes added to the `highway=crossing` node **instead**.

Not additionally. But I get it, I better continue in the other thread.
