### ISSUE TITLE
Discardable tags are not removed

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#4873]
**How to Reproduce**

1. Find an element with a discardable tag (like `created_by`)
2. Answer a quest for that element and upload the changes

See https://www.openstreetmap.org/way/26666693 @ version 6 for an example

**Expected Behavior**

Discardable tags should be removed.

**Versions affected**

51.1

**Comment by matkoniecz** [comment]
This is a feature request, not a bug report.

I seem to remember it getting rejected by @westnordost but I cannot find it - so maybe I misremember it.

**Comment by arrival-spring** [comment]
Found it: #623

**Comment by westnordost** [comment]
I do wonder why josm and iD do it... so they do it without showing this to the user? That would be pretty unexpected from a power tool where the user should take all responsibility for what is tagged

**Comment by HolgerJeromin** [comment]
Ref https://wiki.openstreetmap.org/wiki/Discardable_tags

**Comment by Dimitar5555** [comment]
> I do wonder why josm and iD do it... so they do it without showing this to the user? That would be pretty unexpected from a power tool where the user should take all responsibility for what is tagged

I wonder why StreetComplete isn't removing them? Such ancient tags add only clutter and don't help in any way to current mappers. Despite that, there is consensus that they are not needed.

**Comment by mnalis** [comment]
> I do wonder why josm and iD do it... so they do it without showing this to the user?

Indeed; JOSM does not even *show* the existence of such [discardable](https://github.com/streetcomplete/StreetComplete/issues/4873) `created_by` tag by default, and removes it on upload (both can be changed in advanced preferences)

For deprecated tags, like `source=*` (which is nowdays supposed to be on changeset tags, not object tags), JOSM warns on upload and offers the button to `fix` it - e.g. by removing `source=*` tag of modified objects; but it does require user specifically asking JOSM to do that.

**Comment by westnordost** [comment]
Hm well, I guess if everybody does it™, then this could be considered after all. But I really find the effort vs gain here somewhat questionable. Not only when compared to doing an automated edit to remove all these tags once and be done with that instead of checking this list on every single object uploaded by every single editor and stealthily removing these tags without the user's knowing, but also the contribution in getting rid of these tags is likely quite small with StreetComplete. Just compare the number of elements touched by this app compared with desktop apps like JOSM.
And for what gain exactly, so that the planet.pbf if smaller in the end without having specifically touched (i.e. increased the version number) of every element that has such tags? How much smaller exactly would the planet be exactly?

**Comment by matkoniecz** [comment]
> I do wonder why josm and iD do it...

Because it would be nice to get rid of them and there is unreasonable opposition to large scale bot edits.

**Comment by Dimitar5555** [comment]
> but also the contribution in getting rid of these tags is likely quite small with StreetComplete. Just compare the number of elements touched by this app compared with desktop apps like JOSM:

The problem is that object touched by StreetComplete have very slim chances to get edited by other editors. What can they add to it if all data about it is added? It can get realigned or a new tag/updated tag but that's about it.

> And for what gain exactly, so that the planet.pbf if smaller in the end without having specifically touched (i.e. increased the version number) of every element that has such tags? How much smaller exactly would the planet be exactly?

Consider the fact that StreetComplete creates a separate changeset for every quest which rapidly inflates the version number and thus dumps more versions of that tag in the history planet files.

**Comment by westnordost** [comment]
> Consider the fact that StreetComplete creates a separate changeset for every quest which rapidly inflates the version number and thus dumps more versions of that tag in the history planet files.

Well, there is one easy fix for that. A bot edit that gets rid of these tags in one go.

**Comment by mnalis** [comment]
> Well, there is one easy fix for that. A bot edit that gets rid of these tags in one go.

see @matkoniecz above: _"[...] and there is unreasonable opposition to large scale bot edits"_

>Hm well, I guess if everybody does it™, then this could be considered after all. But I really find the effort vs gain here somewhat questionable

Does that mean, if someone were to write code to do it, it would be accepted? (Or not?)
If former, perhaps `needs PR` tag might be added?

**Comment by Dimitar5555** [comment]
You should know that it won't happen anytime soon.
