### ISSUE TITLE
StyleableOverlayManager adds multiple listeners

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4877]
`show()` is called when switching between overlays, and adds a mapDataListener every time it is called.
https://github.com/streetcomplete/StreetComplete/blob/a3569b1e8ab787ae5a3e36c1d476b691fc2bb2ea/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/StyleableOverlayManager.kt#L48-L53
This can lead to performance issues when the user frequently switches between overlays without switching to _none_ in between.

**Comment by westnordost** [comment]
Hmm, and also a memory leak. On `onStop`, the listener is only removed once.

**Comment by westnordost** [comment]
Yeah, looks this could be the actual cause of #4540. However, the safeguards added in #4544 are fine, I think there is no reason to revert them.

**Comment by westnordost** [comment]
This issue might actually be the cause for quite a number of crashes and issues, see the description of the commit right now. Thank you @Helium314 for finding this
