### ISSUE TITLE
Steps and escalators don't show in sidewalk and lit overlays

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4883]
I noticed that some steps and escalators are not showing in the sidewalk and lit overlays, see screenshot
![InkedScreenshot (17 mrt](https://user-images.githubusercontent.com/69100427/225989554-6cb72e77-6bfe-4635-aa7b-e077af8df424.jpg)

The steps with the missing step count is this one https://www.openstreetmap.org/way/1154777882
Notice that the steps and the escalator next to it appear as voids instead of blue lines or steps, while the paths show. At the other end of the subway platform (that doesn't show either), the steps do show (with or without the `tunnel=yes` tag), but not at the very end where they are covered by the pedestrian area. There are 2 more steps visible as voids in the pedestrian area. This is how it shows in the sidewalk overlay: in the lit overlay, only steps and escalators that have not been given a lit tag show up as voids instead of red lines. Once they are tagged, they show up in the expected colour.

**Expected Behavior**
Steps and escalators show up as paths do.

**Versions affected**
Android 10 and StreetComplete 51.1

**Comment by matkoniecz** [comment]
Is not highlighted way marked as indoor with `indoor=yes`? Indoor ways are not highlighted as missing data.

If not indoor, can you link one of marked ways?

https://www.openstreetmap.org/way/1154777882 should not show as missing data as it has valid lit tag - how it shows up now?

**Comment by rhhsm** [comment]
I found another example, this time with lit overlay. They are 3 parallel escalators, tagged `indoor=yes` and no `lit` tag, the middle one is https://www.openstreetmap.org/way/1136011640
![Screenshot (17 mrt2](https://user-images.githubusercontent.com/69100427/226010374-a4cdb3ee-2af0-4fdd-836c-12151493d5c6.png)
I would expect these escalators to show up red, not as if there is no overlay in their location (they do affect the colour of the `lit=yes` road above). Once I give them a `lit` tag, they show in the right colour, so why not when they haven't been tagged yet?
I could do some experiments in how these show up, but I don;t want to create changesets for real map objects...

**Comment by matkoniecz** [comment]
Indoor ways are deliberately excluded from display as missing data as they can be assumed to be lit.

**Comment by rhhsm** [comment]
> Is not highlighted way marked as indoor with `indoor=yes`? Indoor ways are not highlighted as missing data.

That makes some sense, although it would still be desirable to distinguish between way that are only lit at night (because they are near windows or skylights) and ones that receive no daylight and need to be permanently lit.

What about steps not showing as blue lines in the sidewalk overlay? I suppose some paths are shown as blue lines that could be pavements and so would lead to choosing "displayed separately". But steps can also be part of pavements (on steep streets) so should sometimes be shown too.

**Comment by Helium314** [comment]
In the sidewalk overlay this appears to be an oversight. Steps are included in the filter, but never shown unless they are tagged with `foot=yes` or `foot=designated`
https://github.com/streetcomplete/StreetComplete/blob/b2e2505ea3965a9fea9e35cfbf9be5c7aec4d210/app/src/main/java/de/westnordost/streetcomplete/overlays/sidewalk/SidewalkOverlay.kt#L60-L65

**Comment by westnordost** [comment]
Wait, then,  feel free to reopen if there is an issue. I only happened upon this ticket by chance

**Comment by rhhsm** [comment]
> In the sidewalk overlay this appears to be an oversight. Steps are included in the filter, but never shown unless they are tagged with `foot=yes` or `foot=designated`
> 
I assume steps are seldom tagged with these because they are obviously for pedestrians so no need to tag them as such (we did have some bicycle-designated steps here in Sofia a few years ago, though...). But I don't think, on second thoughts, that it is a problem that they're not displayed in blue in the sidewalk overlay: they're usually short anyway and JawgMaps does display them (though sometimes the location can be out of date, as in my second screenshot).

That the indoor escalators in the second screenshot are not displayed in red is OK, but that they do affect the way the road above (бул. Патриарх Евтимий) is displayed is a minor cosmetic issue. They are selectable, FYI.

**Comment by rhhsm** [comment]
Might be nice to show ways with `footway=sidewalk` in a slightly different way (different shade of blue)? Sometimes it's not clear in the field if a path parallel to a road has been tagged as the sidewalk of that road or should be considered as a separate path.

**Comment by rhhsm** [comment]
...and not to show paths that have `tunnel=yes` or `layer` or `level` with a negative number (underground, so unlikely to be relevant for sidewalks unless the road itself is underground)

**Comment by westnordost** [comment]
1 issue one ticket
