### ISSUE TITLE
Crash after rotate device when you save note

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4885]
**How to Reproduce**
- Long press on map to create note
- Write texte on note
- Open camera to take photos
- Rotate screen in landscape -> take photo
- Validate to go back on SC
- Rotate screen in portrait -> app crashed

I'm not able to reproduce each time, but crash appears frequently

**Expected Behavior**
App doesn't crashed and i can send note on OSM

**Versions affected**
Android 13 - v51.1

**Comment by westnordost** [comment]
Do you have the stacktrace?

**Comment by Jean-BaptisteC** [comment]
Not each time, app crashed i'm in outside

**Comment by westnordost** [comment]
Ok. Yes, normally I do

**Comment by westnordost** [comment]
No feedback, closing.
