### ISSUE TITLE
Prefer tagging crossing:markings=* and crossing:signals=* over crossing=*

### ISSUE THREAD

**Issue by ChildishGiant** [streetcomplete/StreetComplete#4886]
Here's an example change: https://www.openstreetmap.org/changeset/111677927 
You can see that currently it just adds `crossing:unmarked` but could also add `crossing:markings=no`

**Edit by @westnordost:** The accepted solution is described here https://github.com/streetcomplete/StreetComplete/issues/4886#issuecomment-1485667735

**Comment by mnalis** [comment]
> it just adds `crossing:unmarked` 

(I guess this is typo, it should be `crossing=unmarked` instead?)

> but could also add `crossing:markings=no`

It could, but **_should_** it? Wiki for [crossing:markings=*](https://wiki.openstreetmap.org/wiki/Key:crossing:markings) says:

> crossing:markings=no The absence of crossing markings at a crossing. Implied by crossing=unmarked. May be useful in combination with [crossing](https://wiki.openstreetmap.org/wiki/Key:crossing)=[traffic_signals](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals) where there is no marking on the ground, but there is a pedestrian signal.

So it seems to me it would be needless duplication of already implied information (e.g. like adding `foot=yes` to every `highway=footway`), and thus unproductive.

**Comment by ChildishGiant** [comment]
ah yeah that's a typo. ID marks crossings with only one of the two tags as incomplete and that's where I saw this pop up. I imagine there's a reason behind then adding that, but I'm not in the know

**Comment by matkoniecz** [comment]
> So it seems to me it would be needless duplication of already implied information (e.g. like adding foot=yes to every highway=footway), and thus unproductive.

Here we have additional wrinkle of `crossing=` being quite poorly/confusingly defined and having separate tags for separate properties actually makes quite a lot sense here.

**Comment by Helium314** [comment]
So should SC add needless `crossing:markings=no` just to make iD validator happy?
I think not, so better only do it if there are other reasons to add it.

Though a quest could be added to ask about `crossing:markings` if there are some, but it's unclear which ones (e.g. `highway=crossing`, `crossing=uncontrolled`).

**Comment by matkoniecz** [comment]
> just to make iD validator happy?
> so better only do it if there are other reasons to add it

`crossing:markings=`  `crossing_ref=`  ` crossing:island=` `crossing:signals=` are superior to trying to fit everything into `crossing=`

People used to use say `crossing=island` - this one is clearly unwelcome. But other crossing values have the same problem of trying to record multiple different properties at once.

**Comment by westnordost** [comment]
You have a point. Maybe do the following:

Replace the current crossing type quest with two quests: `AddCrossingMarkings` and `AddCrossingTrafficSignals`.

These will only asked if no `crossing=*` is set, yet (so, no iD validator happy-making). It is conceivable to only ask about the traffic signals or something to reduce asking so many questions for each intersection that are likely always the same.

**Comment by matkoniecz** [comment]
There is also SCEE version which has 3 extra options as answers.

**Comment by Helium314** [comment]
> There is also SCEE version which has 3 extra options as answers.

2 of them are actually about markings I commonly encounter (zebra, and traffic signals + zebra), the other one is not actually a separate answer but a hacky way to allow tagging a crossing as raised (on a speed table).

**Comment by matkoniecz** [comment]
just `AddCrossingTrafficSignals` seems to make sense

is there area where `AddCrossingMarkings` is truly important if `AddCrossingTrafficSignals` is answered?

**Comment by 1ec5** [comment]
> is there area where AddCrossingMarkings is truly important if AddCrossingTrafficSignals is answered?

Yes, signalized crossings aren’t required to be marked in the U.S. In practice, many large cities in populous states do typically mark all signalized crossings, but it’s very inconsistent elsewhere. I think it’s usually based on expected pedestrian traffic volume at the time of construction (which may be quite outdated).

**Comment by mnalis** [comment]
Comparison of popularity of the tags: https://taginfo.openstreetmap.org/compare/crossing/crossing:markings/crossing:signals

**Comment by 1ec5** [comment]
Given the relative youth of the approved `crossing:markings=*` and proposed `crossing:signals=*` keys, it’s probably more useful to compare trendlines. Note that these are imperfect comparisons because `crossing:markings=*` and `crossing:signals=*` are both orthogonal to many of the popular `crossing=*` values, and because both keys are thought to have implicit defaults in some regions:

* [`crossing=unmarked` versus `crossing:markings=no`](http://taghistory.raifer.tech/#***/crossing/unmarked&***/crossing%3Amarkings/no)
* [`crossing=marked` versus `crossing=uncontrolled` versus `crossing=zebra` versus `crossing:markings=*`](http://taghistory.raifer.tech/#***/crossing/marked&***/crossing/uncontrolled&***/crossing%3Amarkings/&***/crossing/zebra)
* [`crossing=traffic_signals` versus `crossing:signals=*`](http://taghistory.raifer.tech/#***/crossing/traffic_signals&***/crossing%3Asignals/)

**Comment by westnordost** [comment]
I've looked into it. `crossing:signals` is actually
- not based on any approved proposal
- it is not present in iD presets: It always uses `crossing=traffic_signals`
- [`crossing=traffic_signals` continues to dominate (also in growth) over `crossing:signals=yes`](http://taghistory.raifer.tech
/#***/crossing/traffic_signals&***/crossing%3Asignals/)

While `crossing:markings` have been approved, however, specifically the value that iD uses `crossing:markings=yes` was actually not part of the proposal. Also, iD does not use `crossing:markings=yes` **instead** of `crossing=marked` but **additionally** to it, which I do not quite understand. Also, iD has presets both for `crossing=uncontrolled` and `crossing=marked`, both with the same name, but apparently the former takes precedence when searching for it which means that iD now also tags `crossing=uncontrolled` for new crossings added.

**Comment by westnordost** [comment]
(Maybe @tyrasd can say a few words about the rationale of the current presets? In particular, why the duplication and why not use `crossing:signals` too?)

**Comment by westnordost** [comment]
Okay, from reading https://github.com/openstreetmap/id-tagging-schema/pull/590 and @1ec5 proposal for `crossing:signals` (why is it still in draft, though?), I understand that iD...:

- now uses `crossing` `=uncontrolled` / `=traffic_signals` to denote whether there are traffic signals
- (@1ec5 hopes that in the future, `crossing:signals` `=yes` (etc.) / `=no` could be used for that in the future)
- uses `crossings:markings` `=yes` (etc.) / `=no` to denote whether it is marked
- hence, `crossing=marked` and `crossing=unmarked` effectively are obsolete now, but iD still adds them for I suppose backward compatibility

**Comment by 1ec5** [comment]
> now uses crossing =uncontrolled / =traffic_signals to denote whether there are traffic signals

Kind of. The preset name for `traffic_signals` mentions signals but not markings, while the preset name for `uncontrolled` mentions markings but not signals. Whatever is left unmentioned has implicit defaults in some regions but is intentionally ambiguous in other regions.

> (@1ec5 hopes that in the future, crossing:signals =yes (etc.) / =no could be used for that in the future)

Yes, things are still in a state of flux. The main outstanding task is to decide on renaming `separate` and `shared` (which are in use due to this proposal) to something less confusing and rewriting the proposal accordingly. If you have any suggestions, please contribute them on the talk page.

I do hope to bring `crossing:signals` up for a vote at some point, hopefully soon. However, I expect it to be a time-consuming project because of the entrenched interests around the traditional three-way and/or animal classification schemes.

**Comment by kaneap** [comment]
@westnordost crossing:markings=yes was approved as part of the proposal, for what it's worth.

**Comment by westnordost** [comment]
Unfortunately, the [crossing:signals` proposal](https://wiki.openstreetmap.org/wiki/Proposal:Crossing_signalization) is still in limbo (even though everyone seems to agree that it is a good idea) and hence `crossing=traffic_signals` continues to be used overwhelmingly more than `crossing:signals`. 

On the other hand, `crossing:signals=yes` is unambiguous and although not used extensively, used enough that software should take this tag into account, i.e. support it one way or another.

Ping @1ec5 , why on earth is this still in draft?

What is clear, is that StreetComplete should stop adding `crossing=marked`, `=unmarked`, `=zebra` and `=uncontrolled` and tag `crossing:markings=yes/no` instead. It should remove `crossing` if the answer supplied conflicts with the user's answer and if the user answered "yes", it should not replace a more specific `crossing:markings` with `yes`.

**Comment by 1ec5** [comment]
> why on earth is this still in draft?

Mainly because I’ve been distracted with other things, including another proposal that’s been a draft for far too long. Getting there! One thing that would help is a gut check about the most sensible values to [replace `shared` and `separate`](https://wiki.openstreetmap.org/wiki/Proposal_talk:Crossing_signalization#Renaming_separate) with.

**Comment by westnordost** [comment]
Heh, well, I think you should replace it with `yes` and `no`. I wrote why in the comments.

Everyone thinks that `crossing:signals` is a good idea for `yes` and `no`, and a proposal that contained just that would get almost insta-approved. The existence of an approved `crossing:signals=yes/no` proposal would not prohibit possible extensions later.

**Comment by 1ec5** [comment]
> Heh, well, I think you should replace it with `yes` and `no`. I wrote why in the comments.

Thanks for your feedback; I responded on the talk page to avoid noise in this ticket.

> Everyone thinks that `crossing:signals` is a good idea for `yes` and `no`, and a proposal that contained just that would get almost insta-approved. **(If, in fact, a proposal is really still necessary, with 40k+ usages.)** The existence of an approved `crossing:signals=yes/no` proposal would not prohibit possible extensions later.

This is heartening to hear. I have been wracked by uncertainty about whether I could ever get past the `crossing=uncontrolled` lobby and `crossing=zebra` special interests. Supporting a popular but unapproved key would be your decision to make. id-tagging-schema’s maintainer has also expressed support for `crossing:signals` in principle, but I think he’s holding out for a formal proposal out of concern about the zebraphiles, so I’ll probably have to bring it to a vote anyhow.

You’re right that eliminating the `shared`/`separate` distinction would simplify the proposal, but it would also take away my main motivation for formally proposing this key. Without it, I’m confident that ad hoc usage would eventually make any opposition unsustainable anyways. I recognize that vehicular signal control is a regional concern, but it’s a major concern for some significant regions. The recent experience with [continuous crossings](https://wiki.openstreetmap.org/wiki/Proposal:Continuous_crossings) shows that the global community has some appetite for this sort of thing. 🤞
