### ISSUE TITLE
Wrong flag used for Saint Helena

### ISSUE THREAD

**Issue by Mr-Mime** [streetcomplete/StreetComplete#4887]
In the circular flag view, the wrong flag is used for Saint Helena.
Right now the British flag is shown/used.
I consider this as a minor bug, but still would be nice to see the correct flag here.

The correct flag would be this one: [Saint Flag](https://en.wikipedia.org/wiki/Saint_Helena#/media/File:Flag_of_Saint_Helena.svg)

This is the drawable I am talking about: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/drawable/ic_flag_sh.xml

**How to Reproduce**
Solve some quests in Saint Helena

**Expected Behavior**
Show the [correct flag](https://en.wikipedia.org/wiki/Saint_Helena#/media/File:Flag_of_Saint_Helena.svg).

**Versions affected**
51.1

**Comment by westnordost** [comment]
The iso code "SH" consists of several territories which all have different flags. They are all subdivisions of the United Kingdom however, hence, the flag is correct.

Anyway, adding flags for subdivisions of countries is not planned.

If you would like to see this, you can contribute the Android vector drawable version of AC, SH and TA to https://github.com/westnordost/flags-vector-drawables-android as a PR.

You need Android Studio to convert an SVG to Android Drawable. Also, you should remove details from the SVGs that are not really visible at that display size, simplify it for that display size and put the modified SVGs into https://github.com/westnordost/flags-vector-drawables-android/tree/master/res with appropriate description.
