### ISSUE TITLE
Follow compass but snap to roads

### ISSUE THREAD

**Issue by thany** [streetcomplete/StreetComplete#4889]
**Use case**
When walking out and about tagging stuff, I tend to rotate the map in such a way that whatever I'm roughly walking towards is pointing up on my screen.

This is very similar to orienting by compass, but:

1. Compass is not accurate enough, and could be offset on some devices, rotating the map to a confusing angle.
2. I might stop and turn around to look at something, which would rotate the map again, which I wouldn't expect.

Compass is both too course (in that it doesn't provider a precise and smooth angle to where the user is point their phone) and too precise (in that it registers a lot of small angle changes that aren't necessary to orient a map).

**Proposed Solution**
Rotate the map such that whatever road the user is on, is oriented vertically on screen, point up in the direction of movement.

Compass can augment this rotation, but it seems compass can largely be ignored in this mode.

I guess this mode is similar to how satnav devices work, that don't have an internal compass, and how Google Maps works when navigating at high speed (compass is ignored then).

**Comment by westnordost** [comment]
Fyi the compass is automatically calibrated if you draw imaginary 8ths (or ♾️) in the air with the smartphone in your hand.

**Comment by thany** [comment]
@westnordost I know and it helps, but it doesn't solve the issue that when I turn around to have a look at something, the map is no longer oriented to the direction I was going in.

To be clear, this is not a feature request to deal with bad compasses (even though this is absolutely a thing, especially when there's lots of metal around).

**Comment by westnordost** [comment]
I don't really understand this feature request though. So you want orientation by movement direction, but when the compass direction is more than e.g. 45° off from the movement direction, use compass direction instead? How would that solve

> Compass is not accurate enough, and could be offset on some devices, rotating the map to a confusing angle.

? After all, if your compass is not well calibrated, it will always be off somewhat, thus always triggering to look into another direction instead.

**Comment by matkoniecz** [comment]
Also, it could be misleading when user is going on footway where only main road is mapped - or where geometry of mapped road/path is bad.

**Comment by westnordost** [comment]
I don't really understand this feature request though. So you want orientation by movement direction, but when the compass direction is more than e.g. 45° off from the movement direction, use compass direction instead? How would that solve

> Compass is not accurate enough, and could be offset on some devices, rotating the map to a confusing angle.

? After all, if your compass is not well calibrated, it will always be off somewhat, thus always triggering to look into another direction instead.

**Comment by thany** [comment]
Ok, let's put it differently. Imagine on of these scenarios:

1. The device is being held in a weird angle for some valid reason.
2. The compass is broken and point upside down or something.
3. There is no compass at all.

In such cases, the compass is not usable, but direction is still very much useful.

> So you want orientation by movement direction, but when the compass direction is more than e.g. 45° off from the movement direction, use compass direction instead?

Not neccesarily. I don't *want* anything 😉
I never put it in the format of a business rule, and I shouldn't. 45 degrees might be a bit too tight though. And maybe compass can be ignored altogether if the user is moving. I just think it's useful to align the map not by compass, but by the path the user is walking on.

I'm just expressing a problem that I'm seeing happening, and proposing a solution. If you (author) think there is a better solution, I'm all ears to hear about it.

> or where geometry of mapped road/path is bad.

In such case it could fall back to figuring out orientation from the compass or geolocation.

**Comment by westnordost** [comment]
Hmm, sorry, maybe I don't get it. Or maybe there is a misunderstanding. You do know that the current "follow me" mode (i.e. tap on the GPS button another time) does **not** use the compass at **all but** the direction you are walking? So if you use that mode, the map is already oriented roughly into the direction you want.

Now if your suggestion is to use the compass direction to be able to kind of lean the map to the right and to the left a little in that mode, I have to say that will just not work in case the compass direction is not calibrated. But the compass not being calibrated is the very reason why you wouldn't want to have an exclusive compass direction mode in the first place.

So I am closing this.

However, what would maybe work and would maybe be a useful addition to the current follow-me mode is this: When rotating your screen to the left the map also rotates a bit to the left. When rotating to the right, the map also rotates a bit to the right. This is something someone interested in this would need to try out. It could be useful, it could feel somewhat weird - after all you basically have to input the data of quests on the left side of the road while holding your phone tilted to the left and you are getting close to a point where the device rotates the entire UI by 90° which may prove to be somewhat annoying.
