### ISSUE TITLE
Add amenity driving_school in AddOpeningHours quest

### ISSUE THREAD

**Issue by bmaggi** [streetcomplete/StreetComplete#4899]
**Use case**

* when mapping StreetComplete should (IMHO) propose to add opening hour to driving school (In France, driving_school propose theoretical training and have opening hours for that) 

**Proposed Solution**
* add  driving_school here https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt#L46

⚠️ This [issue ](https://github.com/streetcomplete/StreetComplete/issues/224) suggest that at some point (old java version) driving_school was already present in this quest (but it's not present at the start of the kotlin file) 

I can push a MR if this change is accepted

**Comment by matkoniecz** [comment]
I would say that adding it back would make sense, as far as I can see, seems to be accidentally gone when converting to Kotlin. It may be worth checking whether anything else got lost in opening hours quest.

Feel free to make PR, just test whether it works. Thanks for spotting it!

**Comment by bmaggi** [comment]
Here is the PR. I didn't test locally for the moment (I have to reinstall the android studio since my version is too old, will try to do it tomorrow)

Note that "horse_riding" also disappeared without explicit explanation but was probably included in this comment L 76
                // not sports_centre, dance etc because these are often sports clubs which have no
                // walk-in opening hours but training times
