### ISSUE TITLE
2D-/3D-mode of building representation  on "Shops" overlay after cancelling moving a shop

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#4901]
Using the overlay "Shops" it is possible to re-/positionning an existing/new shop.
Especially in big cities and/or locations with a lot of shops in neightbouring buildings it is sometimes difficult to position these shops correctly because of the 3D representation of the buildings.

When activation "Shops" overlay it were helpful to either have a switch for 2D/3D mode or the buildings are allways displayed in 2D mode.

**Comment by arrival-spring** [comment]
3D buildings are meant to be disabled when the shop overlay is active:

https://github.com/streetcomplete/StreetComplete/blob/37633303a29dd3ac97ad18432fa80d111e6bec62/app/src/main/java/de/westnordost/streetcomplete/overlays/shops/ShopsOverlay.kt#L35-L37

Can you provide a screenshot of where this is not the case?

**Comment by matkoniecz** [comment]
Also, I tested and it works fine for me (no 3D)

**Comment by ironspock** [comment]
SC v51.1
Steps to reproduce:
- activate overlay "shops"
- select a shop and try move it, BUT cancel the action
- afterwards buildings are displayed in 3D (refer to enclosed screenshot)
![Screenshot_Shops_overlay_3D_buildings](https://user-images.githubusercontent.com/68661025/227761794-f5f7045d-b8c9-4872-a4f9-8f11d8e346ff.jpg)

**Comment by ironspock** [comment]
So, it looks like being a bug
