### ISSUE TITLE
Sidewalk task not shown

### ISSUE THREAD

**Issue by schlagi123** [streetcomplete/StreetComplete#4903]
I miss the sidewalk task on some streets.
The sidewalk task is enabled.
The streets have separate mapped sidewalks, but on the the street the attribute sidewalk=separate is not mapped and the task is not shown.

**How to Reproduce**
[Here](https://www.openstreetmap.org/way/198064422#map=18/52.16091/10.32586) is an example.

**Expected Behavior**
Because of missing sidewalk attribute the task must shown.

**Versions affected**
v51.1

**Comment by matkoniecz** [comment]
> The streets have separate mapped sidewalks, but on the the street the attribute sidewalk=separate is not mapped and the task is not shown.

In such cases you need to enable sidewalk overlay. You can enable overlays in settings.

**Comment by schlagi123** [comment]
> In such cases you need to enable sidewalk overlay. You can enable overlays in settings.

The problem is, that this is in the most cases not the way I map things. I try to describe this. Most time I go down streets and map all tasks I can answer. But if I do not know that there is something to do, I can not do that. In this case it is very uncomfortable, because I need to switch often between all overlays.

In my opinion the overlays are very useful if you go throw the streets and you want only map a special aspect. But this is not the case by me.

**Comment by Helium314** [comment]
> Moreover on some streets the task is shown and on some other not.  So there is a bug.

No.
* If someone else already tagged a sidewalk, it would actually a bug if it was asked.
* If a sidewalk is not expected with reasonably high chance, asking would be a waste of user's time. So it's not asked for all road types.
* If there is a parallel footpath in short distance there it's a very high chance this is a separately mapped sidewalk, so asking would most likely be a waste of user's time.

If you're so focused on adding a sidewalk tag everywhere, then the overlay really is the best choice for you.

**Comment by matkoniecz** [comment]
> Moreover on some streets the task is shown and on some other not. So there is a bug.

Sidewalk quest is deliberately disabled when there is footway mapped along road as in such cases mistaken answers are quite likely.

As it is tricky case (you need to answer "separate sidewalk", not "has sidewalk" it is enabled only for people who are specifically interested in mapping sidewalks and enabled such overlay.

Also, you can handle such cases anyway with JOSM, far more efficiently than with SC.
