### ISSUE TITLE
Feature-Request: Overlay max. Speed

### ISSUE THREAD

**Issue by Un1matr1x** [streetcomplete/StreetComplete#4904]
**Use case**
Getting a quick overview of which roads (sections) are already recorded with their speed limit can be complicated, comparable to street lighting (earlier™).

**Proposed Solution**
Analogous to the overview of e.g. lighting and where it is already recorded, an overview of already recorded speeds would be useful as an activatable overlay.
Streets without defined limit are displayed in RED
Roads without explicit limit are shown in BLACK
Streets with explicit limit are displayed with a color from a color gradient depending on the limit, e.g. walking speed GREEN (#00ff00) to maximum limit (130km/h?) YELLOW (#ffff00)

When selecting the road, the already implemented question interface for the speed limit opens.

The way filter for the speed limit should also be applied to the overlay

**Comment by matkoniecz** [comment]
#4282
