### ISSUE TITLE
Number of floors re-requested while informed

### ISSUE THREAD

**Issue by MatthieuQ** [streetcomplete/StreetComplete#4908]
The number of floors is requested again in the application (v52.0) while they are well informed in open street map.

TAG : 
building:levels

Observed in Lyon, France

**Versions affected**
v52.0

![Screenshot_20230328_082007_StreetComplete](https://user-images.githubusercontent.com/633645/228170803-50ccb2b2-c489-49ea-bd33-c9262c69c90c.jpg)

**Comment by Helium314** [comment]
This is intentional, StreetComplete now asks if `roof:levels` is missing and roof is a shape that is not flat.

**Comment by matkoniecz** [comment]
> we have to set roof:levels to 0 rather than leaving the field blank?

yes

see #4821 https://github.com/streetcomplete/StreetComplete/issues/4661 and https://github.com/streetcomplete/StreetComplete/pull/4874
