### ISSUE TITLE
Entrance quest does not re-appear after undo

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4914]
**How to Reproduce**

1. Select an entrance quest, and enter an answer
2. Select "undo" to cancel the answer
3. Quest does not re-appear
4. Quest only re-appears after scanning for quests

**Expected Behavior**
Quest re-appears immediately after "undo"

**Versions affected**
Android 10, StreetComplete 52.0
I've recently noticed recently other cases where a quest did not appear like expected, so this bug might affect other quests too. Can't remember which ones, though...

**Comment by rhhsm** [comment]
> Can't reproduce. Is really this happening for _all_ entrance quests?

No. For some, it re-appears, for others, not. For instance for this building https://www.openstreetmap.org/way/166112309 all entrances have the problem, but for the one next to it https://www.openstreetmap.org/way/166112325 only the one on node 10178536601 has the problem, the others do re-appear. Can you reproduce what I can reproduce?

**Comment by Helium314** [comment]
Will try it later. But I guess it has to do with the size of the surrounding area that is used to determine quests.
When scanning for quests, a rather large area is used to check whether a quest is applicable. But later (when the element is changed by an edit) only a small area is used, mostly for performance reasons. This sometimes leads to inconsistencies that may also work out the other way, e.g. housenumber quest only showing after answering building levels (but staying after undo).

**Comment by rhhsm** [comment]
I noticed that the lanes quest, which is close to the top of my quest ranking list, sometimes only appears when I solved a max speed quest (which is much  lower on my list). Does that have a similar reason?
Will experiment a bit more tomorrow.

**Comment by Helium314** [comment]
> Does that have a similar reason?

No, actually this if fully intended, see
https://github.com/streetcomplete/StreetComplete/blob/36fe5145fe2b5f717620a0389de440e97ad1e9be/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L17-L21
For residential roads there is some maxspeed reuqirement for the lanes quest

(if a quest is an `OsmFilterQuestType` it only depends on tags, and maybe age in case of resurvey, but not on any surrounding elements)

**Comment by Helium314** [comment]
Maybe it would be good to be more specific: which entrance quest are you referring to?

**Comment by rhhsm** [comment]
The one where `entrance=staircase` nodes are quested and `ref=*` is added.
I've been trying to edit nodes 10178536601 and 10178536602 with SC. They are part of the same building area outline, were created in the same changeset, and are similar in all other ways I can imagine. I've been answering the quest (sometimes node 10178536601 first, sometimes node 10178536602 first, sometimes adding a label, sometimes replying it doesn't have a sign, at different zoom levels, hidden by the building 3D shape or not) and then undoing both answers (one or the other node first). Always node 10178536602 reappears but node 10178536601 doesn't. Node 10178536601 only re-appears after scanning for quests. Can anyone reproduce this?

**Comment by rhhsm** [comment]
It seems the distance between entrances is a factor: on apartment building way 166112309, all entrance nodes had the problem of not re-appearing. Now I added another entrance (node 10778134585): the 3 entrances that are closer to each other do re-appear, and the 2 that are further apart do not...

**Comment by Helium314** [comment]
My guess (without proper testing) is that [this part](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_entrance_reference/AddEntranceReference.kt#L88-L91) of checking whether the quest is applicable is the issue.
When undoing the edit, quests are created for the element, which is the entrance. If the quest requires surrounding map data, the are within 20m is loaded (actually square box in lat/lon coordinates).
```kotlin
val buildingEntrances = building.nodeIds
    .mapNotNull { mapData.getNode(it) } <-- here nodes that are outside the box return null, and are ignored
    .filter { entrancesFilter.matches(it) }
if (buildingEntrances.count() < 2) continue <-- no second entrance is inside the box, so the building is ignored
```
The obvious solution would be to increase the box size, but a. this is bad for performance, and b. you will still find quests that require even larger boxes.
Another solution would be adding all nodes of ways inside the box to the data, but that would also be bad for performance as some ways are very long.
Then instead of supplying the data, scanning for quest could request to load specific data, but this requires more changes to make it work, and it's not good for performance once again.

**Comment by matkoniecz** [comment]
Another option is super-specific indexing and tuning to support solely undoing and dynamic creation of this quest type (I think that it is sometimes not created despite that objects are eligible, based on mapping with it) - but that does not really seem worth it.

**Comment by rhhsm** [comment]
I'm not sure I understand what you just wrote, but if it's too much trouble to solve this little issue, go ahead and do more important things!

**Comment by Helium314** [comment]
It's not  really much work to fix the issue.
Much work is "only" involved if we don't want the fix to significantly slow down creation of quests after changing an element / answering a quest.

Having such not-reappearing quests is not nice, but already happens in other cases, so I think it's acceptable to have.
