### ISSUE TITLE
Add ability to tag material on power=tower

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4917]
### General
Affected tag(s) to be modified/added: [material](https://wiki.openstreetmap.org/wiki/Key:material)
Question asked: **What’s this pole made of?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):

- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) 
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

Add power=tower in [AddPowerPolesMaterial quests](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/powerpoles_material/AddPowerPolesMaterial.kt#L14)

In France and Tunisia, the most of time power tower is in steel, but sometimes power tower can be in wood or concrete

[Tower in Wood](https://wiki.openstreetmap.org/wiki/File:Tower-60kv-h.jpg)
[Tower in Concrete](https://wiki.openstreetmap.org/wiki/File:35kv_Transition_Tower.jpg)

**Comment by arrival-spring** [comment]
You say that most of the time towers are steel, what sort of percentage? Preferably backed up by tagging statistics. Otherwise this breaks the "no spam" rule.

**Comment by Jean-BaptisteC** [comment]
Yes you right
Here you can find percentage of material used on power tower https://taginfo.openstreetmap.org/tags/power=tower#combinations

**Comment by arrival-spring** [comment]
Worldwide:
`power=tower` 15.3M
`material=*` 417k (2.7%)
`material=steel` 215k
`material=wood` 100k
`material=metal` 69k
`material=concrete` 22k
That makes it seem like it would be worth adding, for some regions at least.

However, checking https://taginfo.openstreetmap.fr/tags/power=tower#combinations
`power=tower` 253k
`material=*` 3272 (1.3%)
`material=steel` 2441
`material=metal` 474
`material=concrete` 349
`material=wood` not shown (so less than 349)

So it isn't something that's been mapped very much so far, but more than 10% are not metal/steel, so maybe it's not too spammy.

**Comment by matkoniecz** [comment]
> So it isn't something that's been mapped very much so far, but more than 10% are not metal/steel, so maybe it's not too spammy.

Note that unusual values are much more likely to be mapped, so I would not expect at all that it would apply in general. I bet that actual occurrence % is drastically lower than 10% (if testing I would drop in random parts of France on google street view or look at Wikimedia Commons category - both can be biased but less fatally)

(I am not convinced at all that https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/powerpoles_material/AddPowerPolesMaterial.kt makes sense, and I am really sceptical also here)

**Comment by matkoniecz** [comment]
Lets start from objective test: is there reason to expect that more than 0.5% of `power=tower` is not metal? Even in limited areas? If yes, can you try testing and report results?

If `power=pole` exists and was not removed (I proposed it at some point) then I guess that "it is useless as far as I see it" is not actually a blocker. But still, no spam rule applies.

(also, I am still thinking that time on spending power pole materials is not worth any benefits here)

**Comment by matkoniecz** [comment]
Once 

> Lets start from objective test: is there reason to expect that more than 0.5% of power=tower is not metal? Even in limited areas? If yes, can you try testing and report results?

is anwered then this issue can be reopened.

**Comment by Jean-BaptisteC** [comment]
Ok, you right, in the most case material is metal
But, i think is not a spam because power=tower is placed every 500 meters is not like power=pole each 50 meters.

**Comment by mnalis** [comment]
For those interested in doing it (even if it may be spammy), [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork of StreetComplete does allow every user to easily modify such selections themselves, e.g.

![small_Screenshot_20230915_225447_de westnordost streetcomplete expert](https://github.com/streetcomplete/StreetComplete/assets/156656/04f750c1-8bb7-462f-890e-b793e22958b2)
