### ISSUE TITLE
Quest icons appear upside down

### ISSUE THREAD

**Issue by mookau** [streetcomplete/StreetComplete#4918]
![Screenshot_20230401-104804](https://user-images.githubusercontent.com/9105917/229251327-436b9ccb-7091-4e18-ae5d-26197631abb3.png)

Quest icons appear upside down.

**Comment by westnordost** [comment]
You are in Austria, aren't you? It's not a bug but a localization feature, actually. 

The icon orientation now adapts to the gravity of where the particular quest is displayed. In the upper side of the globe, the icons are still the way they were. Do you think it should be changed to be consistent with the underside?

**Comment by peternewman** [comment]
> You are in Austria, aren't you? It's not a bug but a localization feature, actually.
> 
> The icon orientation now adapts to the gravity of where the particular quest is displayed. In the upper side of the globe, the icons are still the way they were. Do you think it should be changed to be consistent with the underside?

I'm very sorry to report there's an outstanding localisation issue @westnordost , if you visit the lower side of the globe without restarting SC (or simply scroll there on the map say) you don't get the correct localisation for the area. Unless it's also respecting the local date which would be ahead where I tried (which I don't think is the case).

**Comment by westnordost** [comment]
Anyway, @mookau, in case you didn't notice by now, happy April Fools Day!

**Comment by mookau** [comment]
> Anyway, @mookau, in case you didn't notice by now, happy April Fools Day!

My fault for installing it on April 1st I guess.
