### ISSUE TITLE
Option to enable fancy path and location marker

### ISSUE THREAD

**Issue by opk12** [streetcomplete/StreetComplete#4919]
**Use case**
Today is April's fool. The blue path has turned rainbow and the Nyan cat replaces the blue location marker. On a second thought, this is actually in line with the "gamification" philosophy behind SC, regardless that the symbol is a smiling pet or anything that is colorful and cute. The choice of an Internet meme is a sign that many geeks are in OSM; but the general approach also makes sense when one tries to bring newcomers to SC. Some people who like cute things do fly away when they see the tags; but there is also a small, self-identified, underrepresented part of the OSM community, who likes a rainbow here and there; for me, seeing one in-app feels refreshing after a week in an environment that has grown on the toxic assumption that colorful means non-professional.

Is it too crazy of an idea to have an option to enable a rainbow path and cute location marker permanently? Maybe this could be the Nyan cat, maybe not, I just wanted to bring the idea on the table.

**Comment by CrsiX** [comment]
+1
I was surprised by the theme at first, but having it always enabled would be so much cooler for the people that appreciate it. Therefore, the current default should stay as is, but an opt-in "rainbow theme" or how you want to call it, would be really great.
Thanks for the great app, by the way :)

**Comment by westnordost** [comment]
Heh, wat. In what kind of environment are you working in, a bank? :-)

**Comment by westnordost** [comment]
Anyway, I am not against having an easter egg for the user to enable this feature forever but it would need to be hidden like it is activated by pressing X times on a certain button in a row or something like that.
