### ISSUE TITLE
Undo dialog: Make text selectable

### ISSUE THREAD

**Issue by hamishmb** [streetcomplete/StreetComplete#4924]
**Use case**
After creating a note, I often realise there's more to add - it would be nifty if I could edit the note rather than undoing and retyping it to make my edit.

<strike>**Proposed Solution**
Perhaps not-yet-uploaded notes could be shown over the map in a different colour so they can be tapped again to edit?</strike>

**EDIT by @westnordost**:
Accepted solution is described here: https://github.com/streetcomplete/StreetComplete/issues/4924#issuecomment-1497361215

**Comment by matkoniecz** [comment]
Note that notes can be closed, can receive additional comments but cannot edited once posted. That is how [notes](https://wiki.openstreetmap.org/wiki/Notes) are handled in osm.

**Comment by Helium314** [comment]
As a very low effort semi-solution: the note text in undo dialog could be made selectable

**Comment by hamishmb** [comment]
> Note that notes can be closed, can receive additional comments but cannot edited once posted. That is how [notes](https://wiki.openstreetmap.org/wiki/Notes) are handled in osm.

That makes sense. Please note, I'm not suggesting that already-uploaded notes should be editable, just that not-yet-uploaded notes should be.

**Comment by mnalis** [comment]
> As a very low effort semi-solution: the note text in undo dialog could be made selectable

lt would help only with text-only notes, though. If the note had pictures, you'd had to go back and manually retake them...

> just that not-yet-uploaded notes should be

I agree, that would be very nice. I don't know how hard it would be to implement, though. It does not sound trivial...

**Comment by Helium314** [comment]
> lt would help only with text-only notes, though. If the note had pictures, you'd had to go back and manually retake them...

Of of the reasons to call it _semi-solution_. Main other reason is that most users in need of this feature will not discover it on their own.

**Comment by westnordost** [comment]
Editing notes in the undo menu would be somewhat unexpected / inconsistent UI, IMO.  Also, it does not fit into an UX that does not really make a difference between uploaded changes and local changes (though from the technical point of view, there is a massive difference).

So, @Helium314 solutions sounds like a good compromise. One could also make the other text (e.g. what is tagged) in that dialog selectable. In fact, I did have the same use case as you a few days ago and subsequently tried to implement making the text selectable, but for some reason it did no work, so I didn't invest any more time in this. Whoever wants to try this again is welcome to. I'll rename the ticket accordingly.

**Comment by Helium314** [comment]
I managed to do it in a test a few days ago, I think it was something like changing
https://github.com/streetcomplete/StreetComplete/blob/06fd4e6ca29cdb674de154eee152021eea3cba97/app/src/main/java/de/westnordost/streetcomplete/screens/main/edithistory/UndoDialog.kt#L136
to `is NoteEdit -> createTextView(text?.let { CharSequenceText(it) }).apply { setTextSelectable(true) }`
Though maybe the setting selectable could done be in `createTextView` instead.
