### ISSUE TITLE
Add baby_feeding tag for gas station

### ISSUE THREAD

**Issue by micronull** [streetcomplete/StreetComplete#4926]
**Use case**

When planning a road trip with a young child, it is helpful to know where to stop for feeding and nursing. 
There are sometimes special rooms at gas stations.

The OSM can gain a competitive advantage with this information, over commercial alternatives. 

It can also be applied to shopping malls.

**Proposed Solution**

Add a selection option for gas stations.
https://wiki.openstreetmap.org/wiki/Key:baby_feeding
https://wiki.openstreetmap.org/wiki/Key:changing_table

**Comment by Helium314** [comment]
For which elements should this be asked?
Why is asking for changing tables at toilets not enough?
And in which countries? I never noticed something like a dedicated baby feeding room, so it might be a local thing.

**Comment by micronull** [comment]
> In this case if toilets are mapped separately it is covered already, and asking for entire mall is not too helpful.

Agreed

**Comment by matkoniecz** [comment]
I feel that adding toilets via #4912 would solve this, as it would be possible to add toilet if missing and then map it in detail.

Unless such rooms are in some areas not a parts of toilets?

**Comment by micronull** [comment]
> For which elements should this be asked?

 For example, at gas stations with cafes.


> Unless such rooms are in some areas not a parts of toilets?

These are separate rooms, as it is not hygienic to feed a baby in the toilet.

**Comment by micronull** [comment]
![image](https://user-images.githubusercontent.com/2688692/229450812-d3747a0a-957f-4ae9-82da-5f5dcf1af74e.png)
![image](https://user-images.githubusercontent.com/2688692/229450948-65abaaf3-6d96-4c92-8137-a5a4d34be6ce.png)

**Comment by micronull** [comment]
![image](https://user-images.githubusercontent.com/2688692/229451472-1cdc8d2d-47d3-40f2-b4b3-8edefd081601.png)

**Comment by matkoniecz** [comment]
> These are separate rooms, as it is not hygienic to feed a baby in the toilet.

Yes, but is it a part of toilet section? I have seen some cases where toilet had such an extra room.

**Comment by micronull** [comment]
I think yes.

**Comment by matkoniecz** [comment]
Then such separate rooms of a toilet are already covered by existing quests? And problem is that some toilets are not mapped on fuel stations, right?

**Comment by micronull** [comment]
Probably need a separate POI for the individual room. 🤔
You can just take note for now and do nothing.

**Comment by westnordost** [comment]
So, this could be asked for gas stations, malls, hospitals, maybe. However, this is conditional to 
- the tag actually being in use. Currently it has a very low usage
- a research in which countries/states these facilities would occur with a kind of regularity at all

So, for now I will close this as will not fix. If you find any data on if these things are common enough to ask for their existence in every mall / gas station etc., feel free to post here and maybe it can be revisited.
