### ISSUE TITLE
Colour intensity in "last mapping" overview depending on the number of changes made

### ISSUE THREAD

**Issue by ElbertCode** [streetcomplete/StreetComplete#4927]
**Use case**
The section "When you mapped lately" can be useful to motivate yourself or to see trends in your way of editing. However, since I map almost every day, this section is quite useless for me.

**Proposed Solution**
Make the fill color be more or less intense depending on how much you contributed, similar how it is made e. g. on GitHub profiles.

![the more changes, the more intense](https://user-images.githubusercontent.com/67899667/229577158-f2be54c0-5ab7-4b70-abdf-c5f7f3001cbc.png)

**Comment by arrival-spring** [comment]
This would also need changes here, https://github.com/streetcomplete/sc-statistics-service
At the moment it only counts days on which any mapping was done, rather than how many changesets.

**Comment by ElbertCode** [comment]
Are these any particular reasons to not change it? And which data does it use for the rank of the last seven days? Couldn't you combine the collection methods of these two to get the data needed?

**Comment by mnalis** [comment]
If implemented, it would be nice if it **auto-tuned to that specific user average**. 

E.g. for user who on average day maps 5-50 changes, 50 quests should be the **brightest** green... However, other user who on average day maps 50-500 quests, obviously the 50 quests is at lower end of the scale, so it should be the **darkest** green. 

Because, if one fixed scale is chosen, it will be useless for other users who do not fit that specific category (and the whole point of this github issue is to _cater to non-typical user_ -- i.e. I doubt that _majority_ of SC users constantly map almost every day!)

**Comment by matkoniecz** [comment]
I deliberately designed here ceiling to be something achievable by regular person (at least 1 edit every single day) even if requiring a bit effort.

Not saying that it cannot be changed, but I wanted to have something that would not push "do more" too far here. And for people more extreme, they can look at more involved stats linked in unlocked links.

**Comment by westnordost** [comment]
So, the primary reason why we have this view at all is to:
- motivate users to contribute regularly: If most of it is grey, it may motivate to finally go outside and map again; if they map very often, it may motivate to achieve some sort of streak
- for the fluff, i.e. have some more colors, statistics and things to look at in general to kind of make the whole thing less dry
- connected to the previous point, to give users the ability to... boast, e.g. by making a screenshot of it and sharing it with friends - so friends may motivate each other to contribute more/regularly or even together, too

I don't see how the suggestion would improve on any of these points. As @matkoniecz mentioned, it would only make the ceiling ("all green") higher, contributing even just one edit each day is still somewhat of an achievement. Unlike GitHub, which many people use for the day job, mapping (with StreetComplete) is a hobby.

So, I am closing this as will not fix.

**Comment by roberta-mb** [comment]
I find that last response by @westnordost  unfortunate. I do think this would encourage people to get out there and this feels directly in line with existing fluff such as ranking in previous 7 days and the growing size of the laurel crowns -- better "performance" is rewarded with a larger crown and could likewise be rewarded with brighter colours.
