### ISSUE TITLE
"Drinking Water" quest should not trigger on disused/historic wells

### ISSUE THREAD

**Issue by BenWiederhake** [streetcomplete/StreetComplete#4928]
StreetComplete asks "Is the water potable here?" even on wells that are already marked as `disused=yes, historic=yes`, so marking them as non-potable water seems unhelpful.

**How to Reproduce**
Step 1: Be in the vicinity of a disused/historic well, and search for quests.
Step 2: Observe that StreetComplete marks the well as a quest item, even though adding such information is not helpful.

The [Overpass Turbo **Wizard**](http://www.overpass-turbo.eu/) makes it easy to combine the quest trigger (taken from `AddDrinkingWater.kt`) and add `and (disused = yes or historic = yes)` to find all the places where StreetComplete will trigger a quest on a disused/historic well.

Here's the **Wizard** query, since the full Overpass query is long to paste here:
`(man_made = water_tap or man_made = water_well or natural = spring) and access !~ "private|no" and indoor != yes and drinking_water is null and "drinking_water:legal" is null and amenity != drinking_water and (seasonal is null or seasonal = no) and (disused = yes or historic = yes)`

**Expected Behavior**
StreetComplete should not ask whether the non-existent water in a historic well is potable.

**Versions affected**
I'm using SC 51.1, but since the query in `master` still doesn't mention `disused` or `historic`, I believe that also the latest version is affected.

EDIT: Original feature see #549

**Comment by matkoniecz** [comment]
`historic=* man_made=water_well` does not really mark inactive water well...

`ruins=yes` `disused=yes` are also quite nasty in this context and ideally would not be used but maybe skipping such items would make sense (but in such case that does not mean that this tagging scheme is a good idea)

**Comment by mnalis** [comment]
I agree that `disused=yes` + `man_made=water_well` (or others) is bad tagging. 
(It should've been `disused:man_made=water_well` etc.)

But I would definitely keep it in SC Quest, because it gives the ability to at least mark it as `drinking_water=no`.

If anything, one might also add `Other answer` of `It is disused` that would replace the matched `tag` with `disused:tag`; but that is probably too much work for too little gain (with any luck, `drinking_water=no` itself would equally well discourage people for going there searching for drinking water)

**Comment by matkoniecz** [comment]
In related news, I am already making a systematic edit (not a bot edit) to handle such tagging on drinking water, see https://gitlab.com/matkoniecz/osm-automation/-/blob/master/script_assisted_cleanup/remove_trolltags_from_drinking_water.py

Based on this report I plan to expand it to cover `man_made=water_well working=no` type of tagging
