### ISSUE TITLE
Answers on notes

### ISSUE THREAD

**Issue by ElbertCode** [streetcomplete/StreetComplete#4933]
**Use case**
When you leave a note with SC, it is often one that you expect a response to, whether it is because you have a question about how to enter it correctly, because you want to know if the problem has been fixed, or simply because you want to know what other mappers think about it. And since this app is (also) aimed at OSM beginners, it is likely to be the only way for many of its users to contribute. It would therefore be a useful addition if you could get answers to your own notes directly in the app.

**Proposed Solution**
There is already a notification functionality in the app, which is currently used for earned badges and the release notes of new versions and which could be expanded to include reply notifications. Also for the conversation interface, could the existing one  be reused. To not disturb users who don't want this notification, there could be a little checkbox at writing a note to disable the notifications for it.

**Comment by westnordost** [comment]
There is no API for this. There is an API for querying how many unread private messages one received, but no API for retrieving the changeset comments or note comments one received.  One always gets an email for that. While it may be nicer to be able to get these notifications in the app and respond in the app, the current method serves its purpose too.

In any case, https://github.com/openstreetmap/openstreetmap-website would be the right repo to request that, but that project suffers from a lack of people actually helping to implement the many things proposed already, so don't expect any movement if you cannot both convince the maintainers and also are prepared to implement it yourself.
