### ISSUE TITLE
Underlying map updates seem to be slow

### ISSUE THREAD

**Issue by c-schmitz** [streetcomplete/StreetComplete#4935]
The map in StreetCompleet does not seem to be the standard OSM Map and also no Mapnik.
It seems slow to update, since I can see that for at least 5 days new building that I created are not shown yet.
Can this be sped up for areas that have been changed?

**Comment by matkoniecz** [comment]
Not really. 

> does not seem to be the standard OSM Map and also no Mapnik.

Raster OSM Carto would not work well ( https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto ) and rendering with Mapnik directly on the phone would work terribly.

If someone would be willing to sponsor vector map tiles with faster updates and fulfilling other requirements, then it would be very welcome. Until that happens we are happy with the current sponsor, it is much more stable than one of previous attempts[1] ( see https://github.com/streetcomplete/StreetComplete/issues/175 ) and they exist, unlike Mapzen[1].

[1] And thanks also to them!

**Comment by matkoniecz** [comment]
Note that maybe flushing cache would help, though update times of about one week are normal.

**Comment by riQQ** [comment]
For more information, see #2479.
