### ISSUE TITLE
FeatureRequest Overlay "Emergency"

### ISSUE THREAD

**Issue by Un1matr1x** [streetcomplete/StreetComplete#4937]
**Use case**

While mapping with StreetComplete you might see f.e. a "emergency=fire_hydrant" in the wild and no quest here for it. So you start asking yourself: Is it completly mapped or isn't it mapped at all?
So with the system now, you can add a note an check it later (or somebody else check it), this doubles the workload per potencial node and might end in some not nice comments about already mapped objects. Or you have to check in another app if there is the node you see in the real world or you say "f it" if it ain't mapped I won't do it eighter.

**Proposed Solution**

Add an overlay like the shop-overlay, but for objects with the [Key:emergency](https://wiki.openstreetmap.org/wiki/DE:Key:emergency),
but at least for [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[access_point](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Daccess_point), [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[life_ring](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dlife_ring), [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[phone](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dphone), [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[fire_hydrant](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant) and [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[defibrillator](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator)  as they have already quests in SC implemented

**Comment by matkoniecz** [comment]
note that it can be also covered by #4912

**Comment by westnordost** [comment]
It would be covered by #4912. I think it is better to have one overlay for all kinds of street furniture that are not shops. Feel free to contribute the emergency stuff to the linked google doc
