### ISSUE TITLE
Allow changing path to steps in surface overlay

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4938]
**Use case**

When mapping with the surface overlay you may come across a section mapped as a path which is actually steps. There is no way to change it at the moment, unlike with the surface quest. If the surface is already set then even disabling the overlay makes it impossible to change to steps (except via e.g. the smoothness quest).

My workaround was to change the section to a wrong surface which would trigger the smoothness quest, use the smoothness quest to say that it was steps and then set the surface correctly so that the steps quests would trigger.

**Proposed Solution**

Add an other answer to allow changing to steps when a path or footway is selected.

**Comment by matkoniecz** [comment]
Also in lit quest, I guess.

**Comment by Helium314** [comment]
Would it be a good idea to add/move answers like _These are steps_ or  _This is indoors_ to the abstract overlay and quest forms, like e.g. split way?
Then the answers would automatically be available for new overlays and quests, and it would reduce the need for things like `SurfaceOrIsStepsAnswer`.

**Comment by matkoniecz** [comment]
"This is indoors" seems viable, especially if it will disable itself on objects already indoors.

---------------------------------

These are steps in abstract overlay will cause problems for say #4912 - where you may have linear bench

Or if any future overlay will get say streams as editable objects.

Though maybe it can disable itself and hide if there is no `highway=footway` or `highway=path` value on an object?

**Comment by Helium314** [comment]
> Though maybe it can disable itself and hide if there is no highway=footway or highway=path value on an object?

Yes, I thought of only adding the answer if the element matches `ways with highway ~ footway|path|cycleway|bridleway`, which is basically where the answer is allowed alredy in surface quest.

**Comment by rhhsm** [comment]
I've had a few cases where a residential road did not connect to another road as mapped, but had steps or a short bit of path at the end (hard to see on aerial images). https://www.openstreetmap.org/way/999989455 is an example. Would it be feasible to allow changing residential roads to steps or paths? I can imagine, though, that this idea would lead to others wishing similar changes in highway features (residential road -> living street, for instance), which could lead to wishes for a highway overlay in which any highway can be changed to another... If you want I can create a separate issue.

I'd like to say that I like the "These are steps" option a lot, and I use it often to map the countless little unmapped steps (often only 2-3 steps) that are abundant in my area and are a serious obstacle to wheelchairs.

**Comment by matkoniecz** [comment]
@rhhsm This is rare enough that risk of partial/bad edit outweights benefits of easy changing.

In such case user should leave note or edit with other editor.
