### ISSUE TITLE
SC wants to create duplicate kerb and tactile tags

### ISSUE THREAD

**Issue by BenWiederhake** [streetcomplete/StreetComplete#4939]
**How to Reproduce**
In the following scenario, screenshot from iD editor:

![Bildschirmfoto_2023-04-10_17-52-50](https://user-images.githubusercontent.com/2690845/230940973-501e2f81-ff67-4786-b9bc-7e2bbeb2c939.png)

There is a single way (`highway=footway, footway=crossing`) from node A through B, C, D, to node E. Nodes B and D are already correctly tagged as kerbs, as the iD editor also shows in the screenshot above. And yet, SC shows quests for the nodes A and E, which are (correctly) not tagged with `kerb=` at all, because it's connected to a `highway=footway, footway=sidewalk` way, and why would there be a kerb.
This quest caused me to make some "Determine the heights of kerbs" and "Specify whether kerbs have tactile paving" changesets, because I didn't see that a kerb was already tagged, but at a slightly different node.

This changeset (not in the screenshot) resulted in the footpath seemingly having four kerbs, the two original (and correct) kerbs, plus the two kerbs I just (accidentally) tagged.

I can DM you the actual coordinates, but would prefer to not make them public.

**Expected Behavior**
The result should be that no such changeset is made. I can see two approaches for that:

- Algorithmic: Detecting this scenario algorithmically and not even prompting for this quest would be ideal, but I don't know how that could possibly be done. Maybe something like this? "Walk the path towards the crossing, and search for other nodes with `kerb=` set, and if any such exist, do not raise a quest marker"
- Visual: I think the simplest option would be to display all kerbs on the map, just like some other quests show nodes/ways that are relevant for orientation. This should enable the user to raise their eyebrows and notice that there already is a kerb here.
(Maybe there's a way to tag that the kerb is elsewhere? I have a feeling that `kerb=no` would cause other issues?)

**Versions affected**
SC 51.1, but it should also affect the latest master branch.

**Comment by westnordost** [comment]
I did the research. In a nutshell: The data shown is incorrect.

See https://github.com/streetcomplete/StreetComplete/issues/1305#issuecomment-759709100 for a longer explanation.

Code is in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/kerb/KerbUtil.kt#L71

**Comment by westnordost** [comment]
Also scroll down for further illustrations, in particular the last comment should be helpful.

**Comment by matkoniecz** [comment]
Without knowing specific location it will be hard to answer (it is possible to recover location from geometry shown here or by looking at edit log, but it would take some time and presumably you are trying to keep it less accessible)

But you need to link some location or prepare synthetic test case as an unit test, otherwise investigating such case is not viable.

**Comment by westnordost** [comment]
> Hmm. Something is wrong though, in https://github.com/streetcomplete/StreetComplete/issues/1305#issuecomment-761006487 you explicitly mention the case I'm looking at

Uh no, your second picture still shows a situation alike 

<img src="https://user-images.githubusercontent.com/4661658/104744979-d5714280-574d-11eb-95d0-b848d211f5e0.png"/>

**Comment by BenWiederhake** [comment]
Yes, that's exactly the situation, I agree on that.

As far as I understand, SC should detect that the `crossing` way already contains `kerb` nodes, and thus not generate a quest.

Or, in case this is not possible, it should at least display existing other kerbs, so that the user can see that this was a false detection.

**Comment by BenWiederhake** [comment]
Nowhere; I'm suggesting it, I'm not describing how the algorithm currently works.

Currently, SC wants users to insert duplicate tags. That's not good.

So I'm suggesting to change SC such that it doesn't.

**Comment by westnordost** [comment]
Okay, you are suggesting that. Let me think about this

**Comment by matkoniecz** [comment]
Maybe skipping cases where crossing is touching both `sidewalk=separate` and `sidewalk=right/left/both` would be feasible and a good idea? 

That seems a root problem here (combined with lack of transition ways mentioned in https://github.com/streetcomplete/StreetComplete/issues/1305#issuecomment-759709100 - not sure is their lack considered as mapping error by mappers)

**Comment by BenWiederhake** [comment]
Maybe it's really easier to display all the kerbs in the surrounding area? This way the user could make sure that there's no duplicate kerbs.

(That would raise the question how to tag that, but that's another discussion.)

**Comment by westnordost** [comment]
I can't think of anything that would speak your suggestion, @BenWiederhake 

I created tests for this suggestion in a new branch named [kerb-crossings-4939](https://github.com/streetcomplete/StreetComplete/compare/kerb-crossings-4939) after having consolidated the other tests and added illustrations for the cases covered so far. Are you interested (or anyone else, if @BenWiederhake is not) in taking on the implementation and making this suggestion your contribution to the project?

**Comment by rhhsm** [comment]
I'd like to mention two more cases for your consideration:

1. SC is asking the kerb height quest on this node https://www.openstreetmap.org/node/3946857795 , however the question is actually about the height of **two** kerbs (on either side of the road) which are of different height here. The quest cannot be correctly answered.
2. SC is asking for kerb height for the 3 nodes where the paths (steps) cross the road on this way https://www.openstreetmap.org/way/157690082 where there are separately mapped kerb nodes that already have kerb heights. I answered the kerb height quest for the middle one, which leads to an "issue" detected by iD (screenshot). Accepting the suggested "update" leads to `barrier=kerb` being added to the node that is part of the road, which then leads to routing apps interpreting this as that cars travelling on this road have to go over this raised kerb. It is wrong of iD to suggest this and this has been reported but not yet resolved.
 ![image](https://user-images.githubusercontent.com/69100427/231425053-c35d230a-8e27-420a-804e-cd317fbbdcec.png)
 
I think SC should, at least for the time being until the iD problem has been sorted out, only ask the kerb height for nodes that have `barrier=kerb`, and leave it to human mappers to add kerb nodes to crossings like the one in bullet 1.

**Comment by westnordost** [comment]
The picture does fit, see the line below the link

El 12 de abril de 2023 7:43:19 CEST, Mateusz Konieczny ***@***.***> escribió:
>https://github.com/streetcomplete/StreetComplete/compare/kerb-crossings-4939#diff-87ac784bab050d25788c4fd4a9ab8368630891b4b31115a8c9caa5317436551dR189 - here illustration does not strictly match test data, is it intentional that it only sort-of fits?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4939#issuecomment-1504685148
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
This is off topic here, @rhhsm , it concerns a different quest. Open a new ticket about this. This touches upon the discussion here - https://community.openstreetmap.org/t/improving-the-wiki-documentation-of-barrier-kerb-and-kerb/97042 - in a nutshell, SC uses `kerb=raised` (without `barrier=kerb`) on intersections between footways and roads where there is *no* crossing.

**Comment by westnordost** [comment]
So, @BenWiederhake, does the heart mean that you'd like to try?

**Comment by BenWiederhake** [comment]
I intend to, yes.

If someone else beats me to it, I'd still be happy about it :D
