### ISSUE TITLE
Bug with roads tagged as cycleway=shared

### ISSUE THREAD

**Issue by codeinabox** [streetcomplete/StreetComplete#4941]
During a [changeset discussion](https://www.openstreetmap.org/changeset/131754219), the following bug was raised:

> I've tested with StreetComplete and can see that for some reason the app completely ignores "cycleway=shared" tags, which are used on roads the entire width of which are shared with vehicles. These can be signed in UK with either a blue rectangle sign or with cycle logos.

**Versions affected**
App version v52.0 on Android version 13

**Comment by westnordost** [comment]
See @matkoniecz

**Comment by codeinabox** [comment]
Thank you for the detailed explanation and clarification. I agree that `cycleway=shared_lane` is consistent with the approach detailed in the wiki. The purpose of this ticket was to raise the concerns of another OSM user who felt this behaviour in StreetComplete is a bug.

**Comment by westnordost** [comment]
I read through the changeset discussion. The user wrote that there is some sign that specifically designates that road for bicycles too and he wants to project this information (somehow) into OSM.

If there are pictograms on the ground, the tagging `cycleway=shared_lane` + `cycleway:lane=pictogram` is correct. If there is (additionally) a sign, he could also add `bicycle=designated`.

If indeed that sign signifies a sort of "cycle street" / "bicycle road" (see https://wiki.openstreetmap.org/wiki/Key:bicycle_road ), then `bicycle_road=yes` could be tagged. This would actually usually indeed by tagged _in place_ of a pictograms lane (aka "sharrows"). But to my knowledge, no such concept is known and used in the United Kingdom. Feel free to add it to the table in the wiki though, if it exists - in most listed countries, cycle streets do not actually have any concrete legal implications.

**Comment by matkoniecz** [comment]
> If there are pictograms on the ground, the tagging cycleway=shared_lane + cycleway:lane=pictogram is correct. If there is (additionally) a sign, he could also add bicycle=designated.

Why pictograms on the ground would not be enough for bicycle=designated? (not that it changes much or is very helpful for anything)

**Comment by BalooUriza** [comment]
On Wed, Apr 12, 2023 at 12:25 AM Mateusz Konieczny ***@***.***>
wrote:

> If there are pictograms on the ground, the tagging cycleway=shared_lane +
> cycleway:lane=pictogram is correct. If there is (additionally) a sign, he
> could also add bicycle=designated.
>
> Why pictograms on the ground would not be enough for bicycle=designated?
> (not that it changes much or is very helpful for anything)
>
I would say that it would be good for bicycle=designated.  Or if you wanted
to be more specific, bicycle:lanes=* where * has "designated" for the value
of the lane that is marked as a shared bicycle lane.
