### ISSUE TITLE
Kerb height quest can sometimes not be correctly answered

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4943]
SC is asking the kerb height quest on nodes where a path is crossing a road, for instance at this node https://www.openstreetmap.org/node/3946857795 In such cases the question is actually about the height of **two** kerbs (on either side of the road) which can be of different height. The quest cannot be correctly answered in cases where the kerbs on either side of the road are not equally high. Even when the kerbs are equally high, it's not very elegant that one tag value describes 2 things on the ground (one could say that it violates the "One feature, one OSM element" principle).

I think SC should not ask the kerb height quest on these kinds of nodes. Instead, we should wait until a human mapper creates 2 nodes tagged `barrier=kerb` on the path on either side of the road. Only then should SC ask about kerb height at the 2 nodes created by the human.

**Comment by matkoniecz** [comment]
> can sometimes not be correctly answered

In such case SC mapper should leave note or edit directly with Vespucci or similar editor and rescan or hide quest.

**Comment by mnalis** [comment]
> Instead, we should wait until a human mapper creates 2 nodes tagged barrier=kerb on the path on either side of the road

That is exactly what `Can't say` / `Leave note` does -- instruct human mappers to _"create 2 nodes tagged barrier=kerb on the path on either side of the road"_ (and tag them appropriately if enough information was left).

**Comment by rhhsm** [comment]
I realise that this issue is more a matter of how to tag such cases. Ideally, kerbs should be mapped separately, and as an alternative, tags like `kerb:left=`, `kerb:right=` and `kerb:both` should be established. This is not the right place to discuss this, however.
