### ISSUE TITLE
SC wants to create duplicate kerb tags

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4944]
SC is sometimes asking for kerb height for crossing nodes that already have nodes tagged `barrier=kerb` and `kerb=*` describing the kerb heights at that crossing. As an example, the 3 nodes where the paths (steps) cross the road on this way https://www.openstreetmap.org/way/157690082 already have separately mapped kerb nodes with kerb heights, but SC is asking for kerb height at the node in between the kerb nodes that are shared between the crossing oath and the road. This leads to duplicates, for example at the middle crossing where I answered the quest.

I think SC should not ask the kerb height quest for such nodes, but should filer them out.

I think this is related to #4939 and should probably be considered in connecting with that issue (a solution to that issue will probably solve this one too).

**Comment by matkoniecz** [comment]
see https://www.openstreetmap.org/node/3063961711 https://www.openstreetmap.org/node/3063961715/history

**Comment by westnordost** [comment]
First of all, it is not considered a mistake to specify the kerbs both on the intersection and on the individual kerb nodes. This is why I removed the bug label.

Second, well, I wrote about it here:
https://community.openstreetmap.org/t/tagging-kerbs-on-crossings/9290/24

**Comment by westnordost** [comment]
So I'll probably go with `crossing=informal` then after reading again through the linked thread if anything else came up.
