### ISSUE TITLE
SC wrong calculation

### ISSUE THREAD

**Issue by crannofonix** [streetcomplete/StreetComplete#4948]
Whenever I try moving a feature (SC does nothing wrong with that), the distance that StreetComplete shows is too much.![Screenshot_20230414-102200_StreetComplete.jpg](https://user-images.githubusercontent.com/92416370/231989008-d2f9cf4d-9d99-4dda-9e10-dce28db429fc.jpg)

**Comment by matkoniecz** [comment]
Is it about refusal to move on clicking "v" button or is it about 9.9 being larger than real distance or about something else?

Can you link location where you tried to move an object?

**Comment by matkoniecz** [comment]
Also, what is your SC version?

**Comment by westnordost** [comment]
Uh, I don't think so, @crannofonix 

![image](https://user-images.githubusercontent.com/4661658/232036931-55d4c838-ac5e-4167-a04b-88dfe625a011.png)
