### ISSUE TITLE
Country statistics in the app show countries where I never solved any tasks

### ISSUE THREAD

**Issue by c-schmitz** [streetcomplete/StreetComplete#4950]
I mapped alot of things recently in Germany and Spain (due to being there alot).
However, after tarring alof of highways in Spain I noticed new countries popping up in my StreetComplete statistics, like Switzerland, Italy  & Portugal. I am 100% sure I never did anything in these countries.

I assume that there are entities (highways) that I touched that are somehow related to the wrong countries.
How can that figured be out?

**Versions affected**
Latest SC version available on Android

**Comment by matkoniecz** [comment]
Have you uploaded changes regularly or have you enabled manual uploads and submitted together changes from Germany and Spain?

**Comment by Helium314** [comment]
Did you create any huge changesets?
E.g. a changeset containing changes in Germany and Spain might get attributed to Switzerland if it's in the center of the changeset bbox.

See also #2987

**Comment by c-schmitz** [comment]
@Helium314 Yes, that issue #2987 sounds like it would be the reason. I guess this can be closed then.
