### ISSUE TITLE
Time Zone issue when displaying recent activity statistic

### ISSUE THREAD

**Issue by jmizv** [streetcomplete/StreetComplete#4951]
The statistics showing the work of the recent days seems to have a bug when it is between 12am and 1am. See the screenshot which I've taken on April 16th 0:20am which is a Sunday (today). So I would expect to see one more green square and the grey square to move to Sunday because I've answered quest(s) on Saturday but none on Sunday (yet).

![photo_2023-04-16_21-24-52](https://user-images.githubusercontent.com/37914724/232337366-44e90e4e-a062-4fc5-b168-32536b2a75a3.jpg)

**How to Reproduce**

Check the stat between midnight and 1am.

**Expected Behavior**

After midnight a new square should be placed in the stat.

**Versions affected**

v52.0

**Comment by westnordost** [comment]
Currently, the day calculation is not made to the user's timezone but to the timezone of the service on westnordost.de (probably UTC+1). See 

https://github.com/streetcomplete/sc-statistics-service/blob/1c8fbb6ef86beb0c32e31e6b435e7ccc3385e84b/classes/ChangesetsDao.class.php#L148

The former would require the app to transmit the user's (current?) timezone, so would require changes on the app but also on the PHP script that returns the data. In my opinion, changing this is not worth it. After all, if the user is on vacation in another timezone, the daily-contribution graphic would potentially look completely different.

**Comment by mnalis** [comment]
That reminds me, I've noticed other discrepancies with that stat. For example, even when SC does display new empty box and I solve new quests and upload (new a midnight), sometimes that day would still show as unsolved. 

I'm not that worried if the day wraparound changes at wrong hour (although I'm at UTC+1 or UTC+2, someone at UTC+12 might be much more affected by that), but it might be worth at least making it consistent (probably by using UTC 00:00 on westnordost.de too, as it seems to be what api.osm.org uses)

**Comment by westnordost** [comment]
Making it UTC should be quite simple, just requires probably to use a different MariaDB function in the cited file. Would you like to look into it?

**Comment by westnordost** [comment]
Actually, I think it is already UTC. Unless the date saved into the `created_at` column is not in UTC, which is unlikely without having looked for it in the code, as this data is pulled from the OSM API.

https://mariadb.com/kb/en/date-function/

**Comment by mnalis** [comment]
By default, mysql time-related functions run in server timezone, which is set to system timezone.
Probably the easiest way to make sure that all operations use UTC is just set it manually.
For example, after connecting to the database, issue `set session time_zone='+0:00';` command, and it will persist for that session until connection is closed.

(or change it in mysql config file and restart mysql server and verify with `show global variables like 'time_zone';` - if your other mysql apps don't care or don't exist)

Otherwise, this is the difference that might happen:
```
% date; mysql -Ne "select now(), date(now()); set session time_zone='+0:00'; select now(), date(now());"
Tue Apr 18 01:31:46 CEST 2023
+---------------------+------------+
| 2023-04-18 01:31:46 | 2023-04-18 |
+---------------------+------------+
+---------------------+------------+
| 2023-04-17 23:31:46 | 2023-04-17 |
+---------------------+------------+
```

Possible problem might be either at inserting, or when retrieving/comparing.


I've just uploaded changeset at about `Tue Apr 18 01:23:10 CEST 2023`. Could you lookup into mysql table and tell me what `SELECT created_at, closed_at FROM changesets WHERE changeset_id=135035513;` says, @westnordost ?

I'll take a look in the source what happens later, but I'd like to know what gets inserted currently.

**Comment by westnordost** [comment]
created_at | closed_at
-- | --
2023-04-17 23:23:11 | 2023-04-17 23:45:46

**Comment by westnordost** [comment]
Any progress, @mnalis ?

**Comment by westnordost** [comment]
ping

**Comment by mnalis** [comment]
(uh, sorry, I'm here now; working slowly through my backlog).

I have a simple change for server side to make sure it works as intended (will PR in few days), but I have found that the app code itself misbehaves on its own, so it needs fixing too.  

That one is harder for me to debug as Android code is not my forte (and being able to test only between 23:30 and 02:30 does not help either :sweat_smile:). I'll produce mode detailed description of the strange behaviors I'm getting.

**Comment by mnalis** [comment]
Here is how bug manifests. 

- Starting situation: user is [UID #172435](https://www.openstreetmap.org/user/mnalis%20ALTernative/history). The last edit was in [changeset 140814288](https://www.openstreetmap.org/changeset/140814288) dated `Monday 2023-09-04 18:30 CEST`, with no further uploads after that.
- at `Wednesday 2023-09-06 23:29 CEST`, SC shows correct map of recent mapping days  (mapped on Monday, but not on Tuesday nor Wednesday)
- however, an hour later, at `Thursday 2023-09-07 00:28 CEST`, SC shifts whole map by one day, claiming **incorrectly** that last mapping was on Sunday, and that Monday, Tuesday, and Wednesday had no mapping. Compare the screenshots:
![small_Screenshot_20230906_232942_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/192b466e-c600-4868-ae36-24218b5698b2) ![small_Screenshot_20230907_002841_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/4a11fa01-a682-4937-b3be-ca592986cd72)
 - few minutes later, at `Thursday 2023-09-07 00:30 CEST`, I upload that 29 pending changes
 - one minute later, at `Thursday 2023-09-07 00:31 CEST`, SC screenshot additionally incorrectly claims that this new upload happened at **Tuesday**, which is totally wrong (it should've been **Thursday** if it followed CEST timezone, or **Wednesday** if it followed UTC). The same situation still shows almost an hour later at `Thursday 2023-09-07 01:20 CEST`
 - however, almost an hour later at  `Thursday 2023-09-07 02:08 CEST` (when UTC time would switch to next day too), screenshot again changes, shifting days back again as the first screenshot, which is correct if one assumes UTC (mapping days only on Monday and Wednesday). Compare screenshots:
 
![small_Screenshot_20230907_003129_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/94b60968-4d6b-4213-b1df-de78b6aebfd1) ![small_Screenshot_20230907_020809_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/48126997-2662-40d1-9d26-4a4400fe995b)

I'll try to dig into code in following days (might ask for some help then), but wanted to clearly document strange behaviours first.

**Comment by mnalis** [comment]
Primary suspects to change/debug: 
- [ ] `app/src/main/java/de/westnordost/streetcomplete/data/user/statistics/ActiveDatesDao.kt`
- [ ] `app/src/main/java/de/westnordost/streetcomplete/data/user/statistics/StatisticsController.kt`
- [ ] `app/src/main/java/de/westnordost/streetcomplete/data/user/statistics/StatisticsParser.kt`
- [ ] `app/src/main/java/de/westnordost/streetcomplete/util/ktx/LocalDate.kt`
- [ ] `app/src/main/java/de/westnordost/streetcomplete/screens/user/profile/DatesActiveDrawable.kt`
