### ISSUE TITLE
"What's here now instead?": confirmation button covered by keyboard is not reachable

### ISSUE THREAD

**Issue by massimostanzione** [streetcomplete/StreetComplete#4952]
When the alert is shown, after using the keyboard to search for an item in the shop type list, if the keyboard hides the "ok" button, as shown in the picture, there is no way to access it afterwards: trying to use the "back" phone button, as well as the provided one to hide the keyboard, in the bottom right of the screen, only makes the "What's here now instead?" alert to just close, making not possible to commit the chosen item from the shop types list, going back to the "Is this still here?" quest.

Nothing changes when selecting "It's vacant..." or "Something else (leave note)", or when pressing the "Fatto" ("Done", in Italian) blue keyboard button on the bottom right of it.

![Screenshot_20230416_223641_StreetComplete.jpg](https://user-images.githubusercontent.com/58670599/232341854-bdf689a5-b6ef-4f7f-96b0-f2cd21352f3d.jpg)

**How to Reproduce**

1. Open a "Is it still there?" quest
2. Press "No"
3. Select "A(n)..." then search for an item from the list by using the keyboard (e.g., type "pizza")

**Expected Behavior**

Expected the keyboard to hide, then letting the user press the "ok" button.

**Versions affected**

52.0

Android 13, Samsung Galaxy A51, default system keyboard.

**Comment by rhhsm** [comment]
Can't reproduce, everything looks fine as before.
Android 10, SC 52.0, LG Q60, Microsoft Swiftkey keyboard

**Comment by Helium314** [comment]
Are you sure the button is behind the keyboard? Or could it be that the button isn't there at all?

Does it happen for all "Is it still there?" quests? If not, can you link to the element where it happens?

**Comment by mnalis** [comment]
It also works here (Huawei P30 Pro, EMUI 12, [Simple keyboard](https://f-droid.org/en/packages/rkr.simplekeyboard.inputmethod/)), although I will note that keyboard is **not hidden** but remains displayed even after the input is done - however the issue does not  happen here as dialog window is shown just **above** the keyboard.


https://user-images.githubusercontent.com/156656/232638504-1cc61593-d038-4266-8ded-f24582a3fc2d.mp4

**Comment by arrival-spring** [comment]
This seems to be keyboard dependent. For me, GBoard, even with it set really tall, the dialog appears on top of the keyboard after selecting pizza fast food.

**Comment by massimostanzione** [comment]
@Helium314 it seems to happen to all the "Is it still there?" quests

After more testing, following what @mnalis said and shown, I noticed that when the keyboard is opened for the first time (i.e. `0:08` from his video, `0:11` from mine, below) the dialog is pushed up to make the dialog + keyboard both fit into the screen. Then, after selected an item from the list, the keyboard seems to "flash" as it was reloaded (`0:15` below). Maybe it was not closed properly?

By the way, I think this video could explain it better:


https://user-images.githubusercontent.com/58670599/232912055-23d1e567-c6b8-49a7-8144-fdc49122bb11.mp4
