### ISSUE TITLE
New quest: identify departure boards on traffic stops

### ISSUE THREAD

**Issue by menganito** [streetcomplete/StreetComplete#4955]
### General
Affected tag(s) to be modified/added: [departures_board=*](https://wiki.openstreetmap.org/wiki/Key:departures_board) The tag is de-facto and has 227,168 total uses. 
Question asked: **Is there a timetable on this bus stop?**
Asked for public transit stops, determine what kind of timetable/departure board does it use.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [✔️] 🚧 To be added tag is established and has a useful purpose
- [✔️] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [✔️] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ❔ depends] 💤 Not an overwhelming percentage of quests have the same answer (No spam) -This might be a problem in rural areas, where there are rarely any form of timetable other than a paper one (departure_board=timetable)
- [✔️] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection: should be asked for all nodes tagged with [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) or [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[station](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstation)** 

**Metadata needed:** 

**Proposed UI:**
*Question asked:* Is there a timetable on this bus stop?
*Possible replies* should correspond to the possible values of this tag:
- "No timeline". Tag as departures_board=no, plus maybe ask the user if they're sure and if they checked in the shelter too. 
- "Printed timeline only" Tag as departure_table=timetable. 
- "Electronic display with real time information" Tag as departure_table=realtime
- "Printed timeline supplemented by real time electronic display" Not sure, appears to be contested on the wiki. 
- "Other" Tag as departure_table=yes, ask user to leave a note. 
- There is also a valuse of departure board=delay, but I haven't experience with that one. 

*Icon* should be in line with other bus stop quests.
*Pictures* for replies could be taken directly from wiki (assuming the license is compatible).

**Comment by matkoniecz** [comment]
See  #2263 #1974 - has issues mentioned there are resolved now?

> has a useful purpose

Why it would be useful?

**Comment by menganito** [comment]
Hi matkoniecz,

It's useful to know what to look for in a traffic stop (for the traveller).
Electronic displays are better legible for the hard of seeing. 
If I were equidistant from two stops on the same line I would prefer to go to the one with real time display. 
It gives more detail and more information to the status of a traffic network.

That said, I didn't check the closed issues for this topic. Doesn't look like a lit has changed since then.

**Comment by westnordost** [comment]
If nothing changed since the prior issues, I'd mark this as a duplicate as this was already discussed.
