### ISSUE TITLE
What's the brand of this parcel locker?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#4959]
### General
Affected tag(s) to be modified/added: [brand](https://wiki.openstreetmap.org/wiki/Key:brand)
Question asked: **What's the brand of this parcel locker?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Empty input field, can be populated the same way that the ATM field is populated.

**Element selection:** 
`amenity=parcel_locker + !operator + !brand`

**Metadata needed:** 
Brands for each country (could be from NSI or from OSM data).

**Proposed UI:**
Same as ATM operator quest.

**Comment by Dimitar5555** [comment]
They seem quite surveyable to me. All parcel lockers are branded in one way or another.

![768x432.jpg](https://user-images.githubusercontent.com/19364673/233203424-37c46218-3649-4f08-a6cf-32cf0280468a.jpg)

![20338_0829_image.JPG](https://user-images.githubusercontent.com/19364673/233203425-5799795a-5f58-4825-be67-93f6953e1657.JPG)

![262.jpg](https://user-images.githubusercontent.com/19364673/233203422-eb63d6a2-65d9-44b2-bff1-82ded57ac58a.jpg)

![SpeedyAPSinfo.png](https://user-images.githubusercontent.com/19364673/233203423-23f92409-08ce-4da6-adb6-f8880ea59563.png)

**Comment by matkoniecz** [comment]
> They seem quite surveyable to me. All parcel lockers are branded in one way or another.

Yes, `brand` is surveyable.

`operator` is not

**Comment by Dimitar5555** [comment]
I've updated the issue accordingly.

**Comment by matkoniecz** [comment]
https://nsi.guide/index.html?t=brands&k=amenity&v=parcel_locker has them as brands

**Comment by westnordost** [comment]
Although it sounds useful, actually, less than 2000 parcel lockers (5%) have neither `operator` or `brand` set. So, while this suggestion looks valid, it has a very low priority because it applies to so few elements.

**Comment by timothywashere** [comment]
There are also parcel lockers currently tagged as vending machines which need updating to the current taghing scheme and this quest could fix that at the same time. I created a quest that did this for the UK in Pic4review but unfortunately a lot of them don't have mapillary images so there are many left to be fixed and identified with a brand.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup;parcel_mail_in - only 400 so unlikely to add much to 2000 quest candidates

Also, either it is a safe accepted replacement and can and should be done with bot rather SC, or it is not safe for SC to do this.

**Comment by timothywashere** [comment]
> Also, either it is a safe accepted replacement and can and should be done with bot rather SC
That's not a good reason on it's own to be honest. People have different skills and no-one who creates bots has done this, although it would be a simple and safe thing to change. There aren't many people who do this since it's heavily discouraged.

**Comment by matkoniecz** [comment]
And among reasons for avoiding silently doing tag deprecations in SC is that it is often quite controversial and disputed. And deprecating in general is a tricky area.

> People have different skills and no-one who creates bots has done this

Anyone capable of using JOSM and overpass can do such bot edit. The tricky step here is consensus for edit, not edit itself. Edit itself I would be able to prepare and start in about 6 minutes. If using JOSM then it would require more time to do it but still less than hour.

**Comment by timothywashere** [comment]
> Anyone capable of using JOSM 
Counts me out
