### ISSUE TITLE
Lit overlay doesn't allow to split ways (confirm button missing)

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4963]
**How to Reproduce**
- Enable the lit overlay
- Select a path
- Select the option to split it
- Add a split point
- No button to confirm this will appear

**Expected Behavior**
- A button to confirm the change should appear

**Screen capture**

https://user-images.githubusercontent.com/614929/233711328-65067b3d-5336-48d7-9e2e-cff7f0ba0974.mp4

**Versions affected**

Android 12

v52.0

**Comment by rhhsm** [comment]
Can't reproduce. Android 10

**Comment by riQQ** [comment]
Can't reproduce on Android 13 either.

**Comment by Helium314** [comment]
Is it really only the lit overlay?
I rather suspect the way is closed. In that case splitting at one point doesn't make sense.

**Comment by arrival-spring** [comment]
https://www.openstreetmap.org/way/1135792881

Because the way is a loop it must be split in two places to create two new ways.

**Comment by matkoniecz** [comment]
@RubenKelevra Is splitting possible on selecting two or more points?

**Comment by westnordost** [comment]
See @arrival-spring
