### ISSUE TITLE
Don't ask one way street quest for dead end streets

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4966]
A minor issue, but anyway: dead end streets are very unlikely to be one way, so even if they are narrow, the one way street quest should not appear for roads that share only one node with other roads.
![image](https://user-images.githubusercontent.com/69100427/233854664-cf8d6870-5c60-4017-8bf9-ff5197aae144.png)

**Comment by matkoniecz** [comment]
note that street currently mapped as dead end may be actually oneway, indicating that some other section is missing

**Comment by Helium314** [comment]
see https://github.com/streetcomplete/StreetComplete/issues/4316#issuecomment-1229546516

**Comment by rhhsm** [comment]
If it's too complicated to code for this, then please don't bother.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/4316#issuecomment-1229546516
