### ISSUE TITLE
AddEntrance quest not asked for multipolygon buildings

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4968]
Currently the quest only asked if the building is a way, see [AddEntrance.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_entrance/AddEntrance.kt#L44-L46)
But at the same time `buildingWaysFilter` contains `relations` too, so I'm not sure whether this is intended.

Anyway, this results in inconsistent behavior, as the quest is asked for some ways touching a building, but not for others, and there is no immediately obvious reason.

**Comment by matkoniecz** [comment]
I can try looking into it and change if doable without massive effort. Can you link some example location?

**Comment by Helium314** [comment]
It's not asked for https://www.openstreetmap.org/relation/7750171, but it was asked for the neighboring building.

I guess the fix would be adding nodes of all ways that are member of the relation.

**Comment by matkoniecz** [comment]
that is because https://www.openstreetmap.org/relation/7750171 has single entrance and https://www.openstreetmap.org/way/31097877 also has single entrance, skipping buildings with a single entrance is deliberate

**Comment by Helium314** [comment]
Umm... ok?
So should I open another issue that for non-multipolygon buildings like .https://www.openstreetmap.org/way/31097877 the entrance quest is (was) asked even if it has only one entrance?

**Comment by matkoniecz** [comment]
oh right, that is adding entrance - not adding entrance ref.

**Comment by matkoniecz** [comment]
@Helium314 Do you want to make a PR if you wrote code already?

**Comment by deevroman** [comment]
> Umm... ok? So should I open another issue that for non-multipolygon buildings like [openstreetmap.org/way/31097877](https://www.openstreetmap.org/way/31097877) the entrance quest is (was) asked even if it has only one potential entrance?

if this problem was solved in this PR (I did not find a another issue), then it has not been fixed yet and got into 52.1. For example, the quest is asked for https://openstreetmap.org/way/23917326 and https://openstreetmap.org/way/141570523
