### ISSUE TITLE
issue  with recycling:*=only

### ISSUE THREAD

**Issue by Marc-marc-marc** [streetcomplete/StreetComplete#4969]
go at https://www.openstreetmap.org/node/8494889249
amenity=recycling
opening_hours=24/7
recycling:aluminium=only
recycling_type=container
same with https://www.openstreetmap.org/node/8494889269 recycling:PET=only

the quest "recycling" still ask "what ca be left here for recycling ?"
despite it's alread in osm

**Expected Behavior**
don't ask, the =only said that all accepted recycling:*=* are set

**Versions affected**
v52.0 and a previous one (no ideal of the exact version I'm using the previous time I noticed the bug)

**Comment by matkoniecz** [comment]
It is asked as part of resurvey of old recycling containers.

**Comment by matkoniecz** [comment]
though https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt#L140 could be amended to check also for `only`

**Comment by matkoniecz** [comment]
I think that I would qualify `recycling:*=*` with values other than `no` and `yes` as tagging mistakes and bad data and therefore no special support is needed here.

Unless there is reason to treat it otherwise.

**Comment by Marc-marc-marc** [comment]
=only a "in use" tagging schema to show that all 

> Edit: `only` seems to be superfluous anyway, according to wiki "_If there is at least one of the following materials tagged, the default value for the rest is no._"

it's quite worrying to believe that a value means that the contributor has filled in everything
@matkoniecz asked the same question for fuel on tagging and nobody said that a value means that everything is filled in

**Comment by matkoniecz** [comment]
The difference is that OSM Wiki claims, for quite long time

> If there is at least one of the following materials tagged, the default value for the rest is no.

on https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling

and `only` is used extremely rarely.

Situation is different for fuels.

(if wiki documentation is wrong then it should be discussed/changed, but discussion should take place on tagging mailing list or official OSM forum, not here)
