### ISSUE TITLE
Cannot tap on some streets to get their name for AddressStreet quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4974]
I can click on majority of streets just fine. But some are unclickable - their name doesn't copy when I click on them.

**How to Reproduce**
- go to e.g. this location (Bosiljevska ulica - https://www.openstreetmap.org/way/907569608)
- try to solve addresses. 
- (Housenumber quest will work)
- but in AddressStreet quest `Bosiljevska ulica` street will **not** be clickable
- also `Dubrovačka ulica` street will **not** be clickable
- however `Ozaljska ulica` street will be clickable normally

Video: 

https://user-images.githubusercontent.com/156656/235010761-345bc365-f717-4699-8c10-6c82a5f361b1.mp4

Refreshing the map does not seem to help. It is always reproducible on that two streets, and seems to works on all other streets. Related issue https://github.com/streetcomplete/StreetComplete/issues/3816 is supposed to be fixed.
The two problematic roads are `highway=residential` and the one that is working is `highway=secondary`, but I've never before had issues with `residential` roads being ignored in that quest.

**Expected Behavior**
- when clicking on any of the streets, its name would get copied, so `AddressStreet` quest can be solved

**Versions affected**
EMUI 12, SC v52.0

**Comment by mnalis** [comment]
Interestingly, if I answer `surface` quest on that street, then I can click on it?


https://user-images.githubusercontent.com/156656/235012657-c99a10e0-5f3a-4577-8fb2-25cde1c8a224.mp4

**Comment by mnalis** [comment]
But it does seem to be related to that https://github.com/streetcomplete/StreetComplete/issues/3797. 

Indeed if I click closer to the end of the road, it starts to work. It seems strange though, as all data is loaded, and even when endpoint of the way is displayed on the visible part of the map,  clicking on road doesn't work unless click is closer to the edge. 

Also it doesn't explain why answering `surface` quests seems to fix the issue even if nodes of the way are no longer visible? Might it be caching related?


https://user-images.githubusercontent.com/156656/235013738-a8d7b37a-eef2-406c-8c67-d9cde7b4799e.mp4

**Comment by westnordost** [comment]
FYI this is because how this function is defined:

https://github.com/streetcomplete/StreetComplete/blob/438d995763ec994aeedbb41cda9ed6c9e50acbe6/app/src/main/java/de/westnordost/streetcomplete/data/osm/mapdata/MapDataCache.kt#L351-L357
