### ISSUE TITLE
Question for "has this stairs a ramp" should offer lift/elevator as option.

### ISSUE THREAD

**Issue by MaestroGlanz** [streetcomplete/StreetComplete#4977]
I just had a stairs, that had an diagonal elevator for wheelchairs. If there is no proper value in tag info, make one.

**Comment by rhhsm** [comment]
You mean this https://en.wikipedia.org/wiki/Stair_lift#Wheelchair_vertical_platform_stair_lifts
See https://community.openstreetmap.org/t/how-to-tag-wheelchair-lift/92137/4

I don't think these fulfil the "tag is established" criterion.

**Comment by westnordost** [comment]
So for now you'd have to create a note as there doesn't seem to be a tag established for that.
