### ISSUE TITLE
Do not ask about shelter from the rain on subway platforms

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4981]
Starting with some recent version, StreetComplete started asking about shelter on public transport platforms. Including about subway platforms that are deep underground and are not displayed on the map:

https://openstreetmap.org/way/183017444

![Screenshot_20230501_205918_StreetComplete](https://user-images.githubusercontent.com/25708359/235502495-ede5deeb-5f55-437a-ad97-aaee46791a6a.png)

**Comment by Helium314** [comment]
Subway stops can (counter-intuively) also be above ground.
Maybe a more general approach like not asking for level < 0 would be better. This would also avoid asking this quests for underground bus/tram stops.

**Comment by westnordost** [comment]
better `location=underground`

**Comment by deevroman** [comment]
> better location=underground

It seems you need to use both filters

<table>
<tr>
 <td> <img width="658" alt="Снимок экрана 2023-05-01 в 21 44 59" src="https://user-images.githubusercontent.com/25708359/235509570-93df1901-7627-4286-b6e8-fa857e35d156.png">
 <td> <img width="655" alt="Снимок экрана 2023-05-01 в 21 44 49" src="https://user-images.githubusercontent.com/25708359/235509582-ad1538d0-5820-4199-934e-969c0b7d01c6.png">
<tr>
 <td> 
<img width="646" alt="Снимок экрана 2023-05-01 в 21 47 35" src="https://user-images.githubusercontent.com/25708359/235509753-d26aca5f-a873-493a-be35-b579840eafff.png">
 <td> <img width="665" alt="Снимок экрана 2023-05-01 в 21 47 45" src="https://user-images.githubusercontent.com/25708359/235509764-e13ebddd-c494-41c2-b4f2-358d92dd666a.png">
</table>

**Comment by matkoniecz** [comment]
> It seems you need to use both filters

Negative layer does not mean that something is underground.

> Subway stops can (counter-intuively) also be above ground.

https://en.wikipedia.org/wiki/List_of_Moscow_Metro_stations

> Of the [Moscow Metro](https://en.wikipedia.org/wiki/Moscow_Metro)'s 229 stations, 78 are deep underground, 109 are shallow, and 42 (25 of them on the Central Circle) are at or above ground level. Of the latter there are 12 ground-level stations, four elevated stations, and one station ([Vorobyovy Gory](https://en.wikipedia.org/wiki/Vorobyovy_Gory_(Moscow_Metro))) on a bridge.

**Comment by westnordost** [comment]
I'd rather only use `location=underground` because `level=-1` (or `level=0` in Russia, USA, ...) ... well I see @matkoniecz beat me to it. It can also e.g. be sub-ground-level but still not be underground. (E.g. on the inverse of something like a railroad embankment)
