### ISSUE TITLE
AddEntranceReference performance issues

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4989]
`AddEntranceReference` quest takes really long to create. For the automatic scan on first start on my S4 mini it took 56 seconds for the larger (second) scan.

This is likely an effect of #4971. It does only happen in 52.1, but not in 52.0.
Performance of the `AddEntrance` quest, which was changed in #4971 too, is unaffected.
[Edit: How bad it is depends massively on bbox size. Zoom out and scan if you're ready to wait. My best time so far: 713717ms, and over a GB garbage collected during the scan]

(and actually the `AddEntranceReference` quest should be skipped at my location, but that's something for another bug report...)

**Comment by matkoniecz** [comment]
Thanks for noticing and reporting, I will look into it what is going wrong here

(unless someone else will be faster - I will amend this comment once I start looking at code)

**Comment by Helium314** [comment]
Looks like for each building, a set of all nodes in a way or multipolyon is created:
https://github.com/streetcomplete/StreetComplete/blob/86ae32f003a4c8b73ef8082247192be8da9ef700/app/src/main/java/de/westnordost/streetcomplete/quests/building_entrance_reference/AddEntranceReference.kt#L89-L98
* this set will be the same for all buildings anyway, so no need to create it for every building
* it's called `buildingsWayNodeIds`, but actually contains node ids of all ways, not just buildings
