### ISSUE TITLE
Country check returns too many countries

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4990]
Sometimes `AddEntranceReference` quest is not skipped despite it being disabled in the current country (see also #4989).

Using roughly the bbox visible in https://www.openstreetmap.org/#map=18/51.18222/14.42365 and some logging, the reason is that `countryBoundaries.getIntersectingIds(bbox)` returns `[DE, CZ, PL]`.
Both Czechia and Poland are more than 10 km away, so definitely do not intersect this bbox.

[Edit: for [https://www.openstreetmap.org/#map=19/48.32927/19.6702](https://www.openstreetmap.org/#map=19/48.32927/19.67027) the countries are `[CZ, SK, PL, HU]`, but this bbox doesn't even intersect with the bboxes of entire PL or CZ]

Maybe the issue is caused by the country data included in SC, or maybe it's actually not SC but rather https://github.com/westnordost/countryboundaries.

**Comment by westnordost** [comment]
> countryBoundaries.getIntersectingIds(bbox) returns [DE, CZ, PL].
> Both Czechia and Poland are more than 10 km away, so definitely do not intersect this bbox.

Hm, there is a misunderstanding of what the library returns. It does return the countries that are in the tile(s) the bbox is contained within. I'll change the documentation comment.

**Comment by westnordost** [comment]
Hence, this function can only be used to pre-filter the results:

I.e., first check if `countryBoundaries.getIntersectingIds(bbox)` returns any country for which the quest is active. If it does not, the quest can be skipped altogether. If it does, for every point, it must be checked whether it is in one of the countries for which it is active. You'll find this logic in the quest controller.

**Comment by Helium314** [comment]
I see thanks for the clarification.
Though checking for the quest and then skipping each one individually seems somewhat inefficient...
