### ISSUE TITLE
[v53.0 beta1] Back button does not exit a quest form

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4994]
**How to Reproduce**

Open a quest form by tapping on a quest
Use back gesture
App hangs for a few seconds
App works again but form is still open

Only way to close the form is to tap off it on the map

**Versions affected**

Android 10 with gesture navigation enabled
53.0 beta 1 installed from Google Play Store

Back works as expected in v52.0

This is probably related to work done by @tapetis

**Comment by westnordost** [comment]
Also, what happens if you made changes in the quest form? Is the dialog that ask about discarding changes being displayed?

**Comment by arrival-spring** [comment]
Ok, I'm not sure what was happening because it was reliably reproducible (only on quest forms, not other places), but is now working fine. I also tested installing the debug version via Android Studio and that works fine too.
