### ISSUE TITLE
Mentioning the local edits deletion in the v53 release notes

### ISSUE THREAD

**Issue by opk12** [streetcomplete/StreetComplete#4997]
The [release notes for 52.1](https://github.com/streetcomplete/StreetComplete/releases/tag/v52.1) warn to upload edits before upgrading to v53, if auto-upload is disabled, because those edits will be cleared on upgrade. Should this be mentioned in the [release notes for v53 beta1](https://github.com/streetcomplete/StreetComplete/releases/tag/v53.0-beta1) and for v53 (when it will be released)?

**Comment by westnordost** [comment]
No, because they have been cleared in v53 beta1. For those not using the beta, they will be cleared when upgrading to v53

**Comment by FloEdelmann** [comment]
Note that some people might read release notes from the Play Store before upgrading. But they will probably also have read the release notes for v52.1.
