### ISSUE TITLE
Reduce filtering of ways for sidewalk quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5000]
As mentioned in #4915, there are quite a few cases where the sidewalk quest is not asked for ways for which I would expect it to be asked, because of too strict filtering. I understood that there is a filter that ensures that the sidewalk quest is not asked for ways that are believed to have separately mapped sidewalks already by looking for nearby footways that are running in the same direction as the way. Examples mentioned include way https://www.openstreetmap.org/way/862062530 that is not quested because of https://www.openstreetmap.org/way/1056791202 that is of insignificant length, or way https://www.openstreetmap.org/way/23147663 that is not quested because of https://www.openstreetmap.org/way/499159632 that is a path that runs in continuation of it, and https://www.openstreetmap.org/way/673415848 that has a separately mapped sidewalk only on one side (if there is a sidewalk on the other side is unknown).

I think this filter should be reviewed to see:

1. if it's necessary at all. Now that `sidewalk:*=separate` can easily be added by the app, it's not such a waste of time any more. It's actually a good thing to add it, because (as I understood) pedestrian routing apps would like to have info on a separately mapped sidewalk and the road it is related to (I remember reading somewhere the suggestion to add the road name to the sidewalk too, to clarify they are related). https://wiki.openstreetmap.org/wiki/Sidewalks#Sidewalk_as_separate_way states that "the associated street/highway should also be tagged with `sidewalk=separate`" so shouldn't we help doing that with SC?
2. if it can be relaxed or refined, without too much effort, so that fewer roads are excluded from sidewalk questing. One could for instance only take footways tagged with `footway=sidewalk` into account instead of all paths, and demand that separetely mapped sidewalks are present on both sides of the road before excluding it. Determining if a (series of) sidewalk(s) is truly running parallel to a (series of) road(s) for a significant length is probably quite difficult?

**Comment by westnordost** [comment]
> Examples mentioned include way https://www.openstreetmap.org/way/862062530 that is not quested because of https://www.openstreetmap.org/way/1056791202 that is of insignificant length

What if this short way had actually `footway=crossing` tagged? I guess it could be ignored if it had that tagged.

Anyway, since already for some time, IIRC both for the cycleway quest and the sidewalk quests, the answer options "yes, but mapped separately" exist, I wonder if we could remove all these checks and require users to input that it has a separately mapped sidewalk in any case, as you suggest in point 1.

@matkoniecz what do you think? About suggestion 1 and 2?

**Comment by matkoniecz** [comment]
> Now that sidewalk:*=separate can easily be added by the app, it's not such a waste of time any more. It's actually a good thing to add it, because (as I understood) pedestrian routing apps would like to have info on a separately mapped sidewalk and the road it is related to 

That actually makes sense and would allow to drop some highly complex code resulting sometimes in confusing behaviours.

So I am for it.

> (I remember reading somewhere the suggestion to add the road name to the sidewalk too, to clarify they are related)

that is controversial/region dependent - and valid only if sidewalks have such names ("to clarify they are SOMETHING" is not valid by itself to add `name` tag, name tag is for names only)

> One could for instance only take footways tagged with footway=sidewalk into account instead of all paths,

This does not work well, as often sidewalks are not tagged with this (but if (1) would be accepted then (2) is not needed)
