### ISSUE TITLE
Lane quest is asked too much on residential roads

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5001]
I noticed that since a few months, lane quests are appearing on almost all residential roads, and that I reply "no lane markings" on almost all of them. Is this also the experience of other users in other parts of the world?

If so, I propose that a more strict filter is applied on questing residential roads for lanes. I understood that at the moment, the only filter is that residential roads should have a maxspeed>33 to be quested (it's a bit strange that a filter depends on the answer of a quest that's off by default).
I think that better filter values are possible so that only "major" residential roads that are more likely to have marked lanes are quested. One filter could be that residential roads are only quested for lanes if they have other surface markings such as a marked crossing. Another could be that they are quested if they have a crossing or node with traffic lights (most likely a crossing with a more major road). A third one could be that they are not quested when they are one way. If one section of a residential road passes the filter, all residential road sections that are connected to it and have the same name should be quested.

**Comment by westnordost** [comment]
That sounds too complicated of a filter to me. Also, crossings exist on very minor residential roads. The quest is quick and easy enough to answer, especially when there are no lanes and the data is useful, so I think it is perfectly fine to ask for any residential road that doesn't have a speed limit below 33 km/h.

**Comment by rhhsm** [comment]
Maybe it would be better to keep this issue open for a little longer than it took me to write it, to keep it visible and see if other users see this as a problem?

**Comment by matkoniecz** [comment]
> I reply "no lane markings" on almost all of them. Is this also the experience of other users in other parts of the world?

not for me

**Comment by mnalis** [comment]
>    I reply "no lane markings" on almost all of them. Is this also the experience of other users in other parts of the world?

In Croatia, about **4983** `highway=residential` have `lanes=*` ([overpass](http://overpass-turbo.eu/s/1uE9)) vs. **263** that have `lane_markings=no` ([overpass](http://overpass-turbo.eu/s/1uEa)). 

Of course `lanes` is both [older](https://taghistory.raifer.tech/#***/lanes/&***/lane_markings/) and more [popular](https://taginfo.openstreetmap.org/compare/lanes/lane_markings), and vast majority of [78k](https://taginfo.geofabrik.de/europe/croatia/tags/highway=residential) residential roads here is not tagged with either. 

To try to reduce that popularity bias, I've tried trying to search for `lane` in [taginfo for highway=residential in Croatia](https://taginfo.geofabrik.de/europe/croatia/tags/highway=residential#combinations) which shows **2 496** instances of  `lanes=1` (which should presumably be marked either as `oneway=yes` or as `lane_markings=no`) and **2 345** instances of `lanes=2`, which seem about equally used, and coincides with my experience (although note that I'm not really big on lanes mapping, but sometimes I get bored :smiley:). 

So, in Croatia, the quest seems to be fine as it is.

> Maybe someone sees an easier way to do something about it?

Well, [SCEE ("expert edition") fork](https://github.com/Helium314/SCEE) does allow one to modify on what elements the quest gets asked, so one could easily select that they don't want to be asked this quest on residential roads, for example by removing parts circled in red:
![small_Screenshot_20230508_001833_de westnordost streetcomplete expert_s](https://user-images.githubusercontent.com/156656/236705405-dc64b2aa-3ecf-4606-b899-862ca3da53c9.jpg)

But SCEE is not a good fit for everyone, of course.  Do read its [README.md](https://github.com/Helium314/SCEE/blob/modified/README.md) if you decide to try it.

Or, of course, you can always simply disable `lanes quest`. I do, most of the time (it is only enabled in my _"everything"_ [preset](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#I_want_to_setup_different_groups_of_enabled_quest,_and_select_them_depending_on_kind_of_trip_I'm_taking;_is_this_possible?), which I only use when bored and everything else is already solved). I would highly recommend everyone to disable quests that they find bothersome (or do not feel that they provide very useful data in their opinion), as it will in fact lead to happier mappers and thus more mapping!
