### ISSUE TITLE
StreetComplete started asking for entrance ref for single-entry buildings

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5002]
For example, the quest is asked for [openstreetmap.org/way/141570523](https://openstreetmap.org/way/141570523) and [openstreetmap.org/way/23917326](https://openstreetmap.org/way/23917326) (the last one has several entrances, but only one `entrance=main`)

Version: 52.1

**Comment by Helium314** [comment]
Already fixed in https://github.com/streetcomplete/StreetComplete/commit/19128100053aea52d69348f4295977a7cabe5d5e
