### ISSUE TITLE
Crash when adding node in parking overlay

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5005]
**How to Reproduce**
* split a long way road near one end
* go to the other end, enable parking overlay and click the plus button
* see a crash:
```
java.lang.NullPointerException
at de.westnordost.streetcomplete.overlays.street_parking.LaneNarrowingTrafficCalmingForm$initCreatingPointOnWay$1.invoke(LaneNarrowingTrafficCalmingForm.kt:89)
```

**Expected Behavior**
no crash

**Versions affected**
current latest, unreleased: https://github.com/streetcomplete/StreetComplete/commit/a460271dc55ef45c77ee1c2d86d5c1df209e14a9

Crash possibly happens because `modifyBBoxMapData` only adds nodes inside bbox
https://github.com/streetcomplete/StreetComplete/blob/a460271dc55ef45c77ee1c2d86d5c1df209e14a9/app/src/main/java/de/westnordost/streetcomplete/data/osm/edits/MapDataWithEditsSource.kt#L387

**Comment by westnordost** [comment]
Oh, splitting ways... yeah, `MapDataWithEditsSource` probably needs to be edited too.

**Comment by Helium314** [comment]
I only checked that 
```
            if (element is Way) {
                element.nodeIds.forEach { nodeId ->
                    val nodeKey = ElementKey(NODE, nodeId)
                    updatedElements[nodeKey]?.let { mapData.put(it, updatedGeometries[key]) }
                }
            }
```
in `modifyBBoxMapData` helps in the specific case.
But I didn't do more than that, and I don't think this is complete.
