### ISSUE TITLE
Crossing quests on ways

### ISSUE THREAD

**Issue by nlehuby** [streetcomplete/StreetComplete#5011]
there are several ways to map crosswalks: 
- the most common: on nodes with highway=crossing
- the other: in addition, have a way with highway=footway + footway=crossing. This is used especially when sidewalks are mapped as separate ways.

When this second method is used, StreetComplete may create duplicate information and ask questions although the information is already available.

**Issue 1:**
For the following quests
* ![crossing:island](https://wiki.openstreetmap.org/w/images/thumb/4/43/StreetComplete_quest_pedestrian_crossing_island.svg/45px-StreetComplete_quest_pedestrian_crossing_island.svg.png) crossing:island
* ![button_operated](https://wiki.openstreetmap.org/w/images/thumb/a/aa/StreetComplete_quest_traffic_light.svg/45px-StreetComplete_quest_traffic_light.svg.png) button_operated
* ![traffic_signals:sound](https://wiki.openstreetmap.org/w/images/thumb/a/a8/StreetComplete_quest_blind_traffic_lights_sounds.svg/45px-StreetComplete_quest_blind_traffic_lights_sounds.svg.png) traffic_signals:sound
* ![traffic_signals:vibration](https://wiki.openstreetmap.org/w/images/thumb/f/f4/StreetComplete_quest_blind_traffic_lights.svg/45px-StreetComplete_quest_blind_traffic_lights.svg.png) traffic_signals:vibration

StreetComplete asks the question on the highway=crossing node, even if the information is already filled in on the footway=crossing way.

I admit that the wiki is not very clear on whether the tags should be on the node or on the way. It seems more relevant to me on the way, as this information is of more interest to pedestrians than to motorists. 
But either way, adding information that already exists doesn't seem very useful.

I think it would be better not to ask these questions on a highway=crossing node which is part of a footway=crossing way (or even better: to ask them on the way instead)

**Issue 2:**
For the following quest:
* ![tactile_paving](https://wiki.openstreetmap.org/w/images/thumb/9/95/StreetComplete_quest_tactile_paving_crossing.svg/45px-StreetComplete_quest_tactile_paving_crossing.svg.png) tactile_paving

Here again, StreetComplete asks the question on the highway=crossing node, even if the information is already mapped on the start and end nodes of the footway=crossing way. We will therefore duplicate an already present info, potentially while being less precise (since we can qualify each side separately when the tag is on the intersection nodes)

Moreover, the precise mapping allows us to clarify the meaning of the tag: on the start and end nodes tactile_paving represents a warning strip, while on the way tactile_paving represents a guidance strip. 
On the highway=crossing node, it is not clear because tactile_paving can mean both.

So, in this case also, I think it would be better not to ask these questions on highway=crossing that are part of a footway=crossing (and keep only the question on intersection nodes)

**Comment by matkoniecz** [comment]
> StreetComplete asks the question on the highway=crossing node, even if the information is already filled in on the footway=crossing way.

Note that putting this info on way in addition to putting it on node is not necessary duplication but survivable, but putting it on way only is incomplete (like mapping `area:highway` without mapping road centerline).

As far as I know.

**Comment by mnalis** [comment]
- (related: https://github.com/streetcomplete/StreetComplete/issues/3407)

**Comment by westnordost** [comment]
See @matkoniecz
