### ISSUE TITLE
TilesRect test fails for some points

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5012]
This was already mentioned in https://github.com/streetcomplete/StreetComplete/issues/4980#issuecomment-1533484977

The test (modified from `TilesRectTest`
```kotlin
    fun `convert bbox to tiles rect and back results in same bbox`() {
        val points = listOf(
            p(53.0, 9.0),
            p(0.0, 0.0),
            p(48.179, 16.414),
            p(85.049, -179.989)
        )
        for (p in points) {
            val tile = p.enclosingTilePos(15)
            val bbox = tile.asBoundingBox(15)
            println(p)
            assertTrue(bbox.min.latitude <= p.latitude)
            assertTrue(bbox.max.latitude >= p.latitude)
            assertTrue(bbox.min.longitude <= p.longitude)
            assertTrue(bbox.max.longitude >= p.longitude)
            val r = bbox.enclosingTilesRect(15)
            val bbox2 = r.asBoundingBox(15)
            assertEquals(bbox, bbox2)
        }
    }
```
fails for the two last points.

When adjusting `asBoundingBox()` to use the +-1e-13 on all 4 positions, the test fails on `p(0.0, 0.0)`, but succeeds for the other points. (this should not be done, as per `asBoundingBox` documentation, but useful for testing)

Test failures are likely caused by some floating point imprecision.
Not sure whether there are any bad effects from this, besides cache reloading some tiles from database, as explained in #4985.
But in my understanding the test should not fail if the coordinates are changed...

**Comment by westnordost** [comment]
I concur that this should not happen. A bounding box should always (at floating point imprecision) be smaller or equal to the corresponding tiles rect, never larger.

**Comment by westnordost** [comment]
Hm, funny, if I paste your test code above into the test and execute it, it passes. (On a Mac, but I don't think it should make a difference, it is Java after all)

**Comment by westnordost** [comment]
Oh, nevermind, I forgot the @Test.

**Comment by westnordost** [comment]
I found a thing (doubles can only harbor 15 decimals, which means that if there are three in front of the comma, it would be 12 after, not 13). However, one test, the one that is near the north pole, still fails.

I suspect that the closer one gets to the north pole, the worse the precision gets... but, I'll have to see.

Also, not sure about lat = close to 90°, do the tiles actually start at, i.e. cover 90°? The lat2tile function returned odd results for such parameters.

**Comment by Helium314** [comment]
Looks like it's not just near the north pole, also `p(0.236, 47.235)` fails.

> Also, not sure about lat = close to 90°, do the tiles actually start at, i.e. cover 90°? The lat2tile function returned odd results for such parameter values.

Should it actually work? There is a limit at 85.0511°: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#X_and_Y
Above that, `lat2tile` returns negative tile numbers.

**Comment by Helium314** [comment]
`p(0.236, 47.235)` is ok when changing `tile2lat` from `180.0 * atan(sinh(PI - 2.0 * PI * y / numTiles(zoom))) / PI`
to `180.0 * atan(sinh(PI * (1.0 - 2.0 * y / numTiles(zoom)))) / PI`, but others like `p(85.049, -179.989)` or `p(68.0728, 45.133)` still fail.

**Comment by westnordost** [comment]
Hum well, then this is just floating point imprecision, isn't it? After all, the lat2tile etc. functions can hardly be incorrect, can they?

**Comment by westnordost** [comment]
Anyway, I added your change and I don't see anything else we can do about this.
