### ISSUE TITLE
Add dead area around quests when using overlay to prevent fat finger syndrome

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#5014]
**Use case**
When using overlays but trying to tap on a normal quest bubble, I'm always slightly missing the correct area for the quest and accidentally launching the overlay quest for the way underneath the quest bubble. Exiting out of the overlay quest is bit of a pain, using the back button at the bottom of the screen.

**Proposed Solution**
Please add a small 'dead' area around the normal quest bubble so that if I miss the tappable area it doesn't launch either the standard quest or the overlay quest.  I just have to tap again.

Thanks

**Comment by matkoniecz** [comment]
note that I often have opposite problem - I tap quests instead of overlays and sometimes such dead area would make some objects unclickable

(not saying that this problem does not exists, but it is a bit more complex)

**Comment by westnordost** [comment]
I don't think this is possible with tangram-es, sorry.
