### ISSUE TITLE
Allow setting Street name by tapping on another house

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#5015]
**Use case**
When giving a street name to a house where there is no road or path nearby with that name, it is very tedious to add the same street name to many houses.
This mainly happens to me where a terrace of houses has a different name to the road they are on, which is not uncommon in the UK.
or where a large number of houses are built with only footpaths running past the houses but car parks nearby. No-one has named the footpaths yet, because it requires survey.
You have to use copy and paste a lot, which requires long presses and takes ages. I may be trying to give street names to 100 houses in a terrace.

**Proposed Solution**
Allow tapping on a building where the street name is already set to say, "same as this one". This would auto-fill the street name in the dialogue, meaning you still have to confirm it is correct.
Perhaps limit this to only buildings you have just filled in if you think it would be dangerous.

Alternative solution: Add paste button to dialogue. In my version of android the paste button is available on all text entry fields when you have just used the"copy" menu to put somethingin the clipboard. Unfortunately this paste button disappears once you have used it once. If SC had it's own paste button, this would make things a lot easier also.

**Comment by Helium314** [comment]
Since you write this issue, I assume you're talking about the street name quest?
The overlay already pre-fills the previous street name.

Anyway, isn't a paste option available on long-pressing the street name input? Works for me on Android 9.

**Comment by mnalis** [comment]
> Anyway, isn't a paste option available on long-pressing the street name input? Works for me on Android 9.

`Long press` + `paste` works for me too in EMUI12 (Android 10) in Street name quest.

**Comment by timothywashere** [comment]
Yes, as I said, it takes ages using long press and paste for many houses

**Comment by westnordost** [comment]
Why does 

> The overlay already pre-fills the previous street name.

not solve your use case? You don't need to input the street name, it will be filled automatically with the last after you entered the housenumber.

**Comment by timothywashere** [comment]
> Why does
> 
> > The overlay already pre-fills the previous street name.
> 
> not solve your use case? You don't need to input the street name, it will be filled automatically with the last after you entered the housenumber.

Having to click on the building behind the quest instead of the quest?  Also it doesn't work
https://youtu.be/dSqH_xGwn8M

There's a greyed out default value but you can't submit it without changing the number

**Comment by westnordost** [comment]
There, second 36, you have it. The hinted street name is applied when you change the housenumber.

**Comment by timothywashere** [comment]
By changing the house number to an incorrect value, yes

**Comment by Helium314** [comment]
You can change it back again. But if the 300 (?) ms for a long press is too much time for you, I guess you won't like that either.

If you really do that without going to each house (and it looks like, because otherwise the 300 ms wouldn't bother you), then I recommend creating a note and do mass-tagging using a different editor.

**Comment by timothywashere** [comment]
> You can change it back again. But if the 300 (?) ms for a long press is too much time for you, I guess you won't like that either.
> 
> If you really do that without going to each house (and it looks like, because otherwise the 300 ms wouldn't bother you), then I recommend creating a note and do mass-tagging using a different editor.

Walking past terraced houses, yes the extra 300ms per house means it takes longer to tag them than walk past. So I either continue tagging them and miss whatever quests I was walking past in the mean time or leave some undone. Since I visit places I never go back to, it would be nice to get the address done.

**Comment by westnordost** [comment]
I've thought about this and decided against. Reasons:

Tapping on another house in the address overlay already has a different function: To select this house to edit/add the housenumber there. It would be inconsistent and unexpected if the UX for the address street name quest worked differently here because otherwise it completely works the same: Tap on the **road** it belongs to.
