### ISSUE TITLE
Incorrect suggestion when using Bike overlay

### ISSUE THREAD

**Issue by heragnar** [streetcomplete/StreetComplete#5016]
When adding bicycle lanes using the Bike path overlay the app does not offer the  _sidepath or protected bicycle lane, both directions_ option again when tagging multiple ways.

**How to Reproduce**

Select Overlay _Bike paths_
Tag a street with the _sidepath or protected bicycle lane, both directions_ option on the right and any other on the left.
Select a new street.
The _sidepath or protected bicycle lane_ option gets suggested instead.

**Expected Behavior**

The same option should get recommended [protected bicycle lane - both directions] instead of one direction only.

**Versions affected**

Android 6.0.1
StreetComplete 52.1

**Comment by westnordost** [comment]
>  The sidepath or protected bicycle lane option gets suggested instead.

What do you mean with "suggested" and "recommended"?

**Comment by heragnar** [comment]
Sorry for the confusion, I mean the little box that suggest you to use the previous selection.
![5016](https://github.com/streetcomplete/StreetComplete/assets/130934952/f6923a33-5b1e-4b6f-abd5-26f02a6f04b2)

**Comment by westnordost** [comment]
Fixed

**Comment by heragnar** [comment]
Thank you!
