### ISSUE TITLE
Can't login and no maps downloaded

### ISSUE THREAD

**Issue by petrarca-arezzo** [streetcomplete/StreetComplete#5019]
I do have a new phone, and installed StreetComplete, however there are no maps downloaded and the login doesn't work (login server no reachable). I have full internet access, i.e. no VPN, no add-blocker and all other apps are working fine. I can reach openstreetmap.org and openstreetmap.de in the browser.

There is no userul feedback regarding the maps (just a note that there was an issue); for the login it says that the login server is not reachable (but no hostname, domain or IP provided).

I'm on Android 12 and StreetComplete is on v52.1.

**Comment by Atrate** [comment]
Could you capture a log using ADB? (Though I'm not sure it will have relevant info)

[Instructions](https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/)

**Comment by matkoniecz** [comment]
is osm site reachable on phone browser?

**Comment by HolgerJeromin** [comment]
@matkoniecz 
He wrote

>  I can reach openstreetmap.org and openstreetmap.de in the browser

**Comment by petrarca-arezzo** [comment]
Yes, correct - I can reach e.g. osm.org, openstreetmap.org or openstreetmap.de perfectly fine in the browser. Is there anything different on how StreetComplete tries to access the 'login server' or the maps than the browser does? And what are the IPs, URLs Streetmap is reaching out to?

**Comment by mnalis** [comment]
> There is no userul feedback regarding the maps (just a note that there was an issue); for the login it says that the login server is not reachable (but no hostname, domain or IP provided).

- can you provide screenshot of that error @petrarca-arezzo? As far as I can tell, StreetComplete opens a normal browser window when you try to login.

- if you go in menu / `About` and try to click on various links to websites (like `FAQ` or `Project Home`), do any of those work, or also return an error?

- on lower-left part of main screen (where map should show), does it show text `(c) OpenStreetMap contributors` ? If it does, can you click on that, and does it open a webpage normally?

**Comment by petrarca-arezzo** [comment]
Hi all, thanks for all very fast replies - very much appreciated. What I did is to reboot my new phone which solved the issue (however for unknown reasons). So just for the future: a reboot on a new StreetComplete installation might be helpful :-)
