### ISSUE TITLE
Automatically present surface overlay choices when no surface is mapped

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#5020]
Partially related to: #4741 

When clicking on a way with no surface mapped, the user is presented with a window where the only choice is to tap on the "?" way and select a surface overlay. In such a case, this single tap is the only way to proceed, and, in my opinion, redundant. I think in such a case the user should be presented with the surface choices immediately, without having to make one more tap.

**Comment by matkoniecz** [comment]
It was discussed somewhere in https://github.com/streetcomplete/StreetComplete/pull/4642 or one of related issues

**Comment by westnordost** [comment]
It is a duplicate, it was requested for lit overlay too. The UI is the same.

I believe implementing #4741 would pretty much solve this use case.
