### ISSUE TITLE
In the tactile paving quest on the stairs, the answer buttons are arranged unusually

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5021]
In other quests, the Yes button is on the right edge

<img width="350" src="https://github.com/streetcomplete/StreetComplete/assets/25708359/c8fa19da-5df7-4547-b966-bdbe7660992c">

**Versions affected**
StreetComplete 53.0

**Comment by arrival-spring** [comment]
Apologies, I'll fix that soon.

While I'm there, I'll also switch round the top and bottom other answers so that top is on top.
