### ISSUE TITLE
No rendering of landuse=construction anymore?

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#5023]
**How to Reproduce**

1. Scroll to any landuse=construction area, e.g. https://www.openstreetmap.org/way/941919741
2. Look at the map
3. landuse=construction cannot be identified

**Expected Behavior**
I thought in past landuse=construction was rendered in the map. Am i wrong? Or did it stop working?
It would be nice if one can identify areas with landuse=construction on the map.

**Versions affected**
v53

**Comment by Helium314** [comment]
I think it never has been rendered (though maybe in the pre-jawg tiles?).
As it's not in https://www.jawg.io/docs/apidocs/maps/streets-v2/#landuse (background map tiles), it would only be possibile to show in overlays.

**Comment by rhhsm** [comment]
>  it would only be possibile to show in overlays.

That would be nice. Quite a few of the notes I make concern construction areas and buildings under construction that I hadn't seen before, but I often find later that they are already mapped.

**Comment by Strubbl** [comment]
> Quite a few of the notes I make concern construction areas and buildings under construction that I hadn't seen before, but I often find later that they are already mapped.

This is also the reason i am asking this.

**Comment by matkoniecz** [comment]
`landuse=construction` is not available in vector tiles we are using, see https://github.com/streetcomplete/streetcomplete-mapstyle/issues/108#issuecomment-942154877

**Comment by matkoniecz** [comment]
Though `can only progress by submitting work upstream` is not really accurate as Jawg wector tiles generation is not open source.

**Comment by rhhsm** [comment]
>  it would only be possibile to show in overlays.

I understand that it's not on offer in Jawg and we can't do much about it, but it would be nice if it's available in some way in a SC overlay. The address overlay seems most suitable for me. If a construction area and a building under construction would be selectable there (without being visible in Jawg), I could tap on the area of the map where it is and allow me to check if it's already mapped or not. Here in Bulgaria it's compulsory to have an information table that shows what kind of building is being built there, so the building quest could already be answered for it (it could add `construction=*`).

**Comment by matkoniecz** [comment]
> I could tap on the area of the map where it is and allow me to check if it's already mapped or not.

building under construction should be already shown on map

> the address overlay seems most suitable for me.

why?

**Comment by rhhsm** [comment]
> > I could tap on the area of the map where it is and allow me to check if it's already mapped or not.
> 
> building under construction should be already shown on map

Indeed, I didn't realise this
 
> > the address overlay seems most suitable for me.
> 
> why?

Because this is about buildings, and addresses are most often attached to buildings.
Construction areas are usually not the same shape as the building that's going to be there, so if a building type would be tagged to it, someone would later have to adjust the building footprint or add the individual buildings if there are more than 1. So it would be premature to add a building type: maybe construction areas could be made selectable, but not editable?

**Comment by matkoniecz** [comment]
But construction area is going to be entire plot, not just where building will be. And unlikely to be address taggable.

**Comment by Cj-Malone** [comment]
Related, I would like to see highway=construction/new highways rendered.

I can't remember the exact details, but I think it's only rendered when selected as a quest (maybe before as well?). Then after you answer it goes away (it wont be in the tiles yet), it makes adding address points relative to it impossible and I just have to sort of guess the location.

**Comment by matkoniecz** [comment]
> new highways rendered

there is some delay with data update but they will show up in map tiles

**Comment by Cj-Malone** [comment]
Yeah, delay until the changeset is uploaded to OSM, delay until Jawg update, delay until SC cache expires. I understand the cycle, but I think it's a poor user experience: "Is this road constructed?", "yes", road disappears.

In theory, SC could update the local tile, or store the road in another place. But it's probably a bit of a hack.

Anyway, it would be nice, but I understand if it's too much of a head ache.

**Comment by rhhsm** [comment]
> But construction area is going to be entire plot, not just where building will be. And unlikely to be address taggable.

That's what I said. It would be nice if, when you tap on a part of the screen where you suspect is a construction area, some area will be highlighted when there is a construction area already mapped
<img width="360" alt="Screenshot (15 mei 2023 21 15 07)" src="https://github.com/streetcomplete/StreetComplete/assets/69100427/2a8a13f1-a944-4309-9a32-4a5868b2efd0">
, or nothing happens when the construction area isn't mapped yet. And that's all: any highlighted area will not lead to an editable box with address details to appear.

**Comment by matkoniecz** [comment]
but why it would be worth doing specifically for address overlay?
