### ISSUE TITLE
Overlay Switch Button

### ISSUE THREAD

**Issue by eddisch** [streetcomplete/StreetComplete#5024]
**Use case**
Its annoying to constantly switch between overlays.

**Proposed Solution**
Add a small overlay switch button on the bottom.

**Additional Suggestion**
Maybe bind the Zoom buttons together?

![Screenshot_2023-05-14-19-47-33-368_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/73175017/9ecbf171-4d48-475c-9ada-19d82fd00cf7)

**Comment by eddisch** [comment]
and a feature to add overlays to this button so you switch only between your ones.

**Comment by Helium314** [comment]
see https://github.com/streetcomplete/StreetComplete/issues/4686#issuecomment-1356927958

**Comment by westnordost** [comment]
Actually,  I changed my mind, because:
- it is by now a large part of the editing functionality of SC and it makes sense to make the feature more prominent 
- like for team mode, it is useful to know if or in which overlay one is currently

**Comment by eddisch** [comment]
Yay!
