### ISSUE TITLE
Adding cycleway width for “lane” and “track” on a highway

### ISSUE THREAD

**Issue by vizsim** [streetcomplete/StreetComplete#5025]
### General
Affected tag(s) to be modified/added: [cycleway:width](https://wiki.openstreetmap.org/wiki/Key:cycleway:width)
Question asked: **How wide is the cycleway (along the highway) here?**

At the moment StreetComplete allows adding widths attribute to highways and accordingly to cycleways that are highway=cycleway.
However, if a cycleway is part of a highway (f.e. highway = secondary & cycleway:both = lane) it does not support to add f.e. “cycleway[:both]:width = 2” to this way. 
To clarify my point, please see as an example: https://overpass-turbo.eu/s/1uYv
 
Would it be possible to add this to StreetComplete or is it discouraged to use such namespace attributes in general?

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** highway!=cycleway & cycleway:left|right|both~lane|track

**Proposed UI:** Similar to the currently existing widths quests:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/16351144/8db87d04-9015-4c20-b605-8199302da47e)

**Comment by arrival-spring** [comment]
I think it's too much to ask of a user to measure the track/lane on both sides of a road just to solve a quest.

Also, there's the issue of seeing for how far the width is consistent, along both sides of the road.

Also, see https://github.com/streetcomplete/StreetComplete/pull/3735#pullrequestreview-891355704 referring to adding `sidewalk:surface`
> Let's add this quest but let's not add any further detailing quests for street-sides for now.

**Comment by vizsim** [comment]
good points, thanks for the review!

**both sides**:
what if it is solved by "split" the case cycleway:**both** = lane in two quests-items (cycleway:**left**:width = ? and cycleway:**right**:width = ?). I undestand that this could lead to overspecification if both are the same. would that be a no-go?

**consistent, along (both sides) of the road.**:
I totally understand that it would be unwanted to split a segment because a cycleway might differ f.e. 20cm within a segment. 

**detailing quests for street-sides**:
I see, maybe then it might be possible to only introduce this quest to **lane** (and not to track).


My motivation for this quest comes from a project, that measures overtaking events of vehicles and bicyles, [OpenBikeSensor](https://www.openbikesensor.org/). Linking (OSM) cycleway lane widths to overtaking distances would be very innsightful.
https://obs.adfc-brandenburg.de/map#12.50/52.48615513280768/13.42574812649469

**Comment by westnordost** [comment]
Hm, at least for `cycleway:*=lane`, no alternative tagging exists. It must always be added on the road-way. So, the statement "if you want to add more details, map it as a separate way first", does not apply.

This of course does not solve the other (UI) problems associated with adding more details to bike/footpaths mapped on the street way, though.

**Comment by westnordost** [comment]
But anyway, see @arrival-spring first post: IMO it is too much to ask of of a user to supply both sides of a road with this information, especially when it is about tiny chunks of street segments (because they have been split up due to other reasons).

So, if this can be implemented, then only in some overlay (which would allow to supply it only for one side first). However, an overlay just for bike path widths seem overkill to me.

**Comment by westnordost** [comment]
Anyway... as per this request, i.e. have a quest for this, I'll reject it for the above reasons. Regarding an overlay... we have to see. It would be quite the complex overlay, too, because both bike paths tagged on the road way and mapped separately need to be covered... plus bike+foot paths.
