### ISSUE TITLE
Wrong surface tags including overwriting correct tags on Dutch cycleways (again)

### ISSUE THREAD

**Issue by A67-A67** [streetcomplete/StreetComplete#5037]
This is the same issue as https://github.com/streetcomplete/StreetComplete/issues/2644. I thought it was resolved by not adding incorrect tags at cycleways with `sidewalk=yes|no|both`. However it seems even at those cycleways still the surface-tags gets changed to an incorrect scheme.

Example: Version 2 of https://www.openstreetmap.org/way/1040923733/history

This is an asphalt cycleway with a paving stones sidewalk. Just as for normal roads the surface of the cycleway itself should be in the tag surface, while secondary surfaces, like the sidewalk, go in secondary tags.

However, the StreetComplete quest SurfaceOverlay seems to overwrite the correct tagging. The correct `surface=asphalt` get changed to the less specific `surface=paved`. At the same time `cycleway:surface=asphalt` is added (while it is a cycleway...) and the sidewalk surface is added to `footway:surface` instead of `sidewalk:surface`.

**Comment by westnordost** [comment]
Is `segregated=yes` actually correct on the linked way?

If the cycleway should be treated like a street (i.e. has a sidewalk, not a `segregated=yes` + `foot=designated`), `segregated=yes` seems to be wrong here. After all, `segregated=yes`is not set either on roads with sidewalks.

**Comment by davidpnewton** [comment]
Cycle tracks don't have "sidewalks" in that way. If "segregated" is set to yes then that automatically implies access for pedestrians. However the wiki does suggest explicit access tags should be set. Hence the Streetcomplete problem.

The more fundamental problem is mixing sidewalk tagging with segregated cycle track tagging. If you mean to use sidewalk tagging then use sidewalk tagging. If you mean to use segregated cycle track tagging use it. Don't use an invalid and confusing mixture as in this case.

So regardless of the Streetcomplete situation the tagging is wrong here. Either remove the segregated tagging or remove the sidewalk tagging.

**Comment by A67-A67** [comment]
Cycleways in the Netherlands do have sidewalks, just as normal roads. They look and function in the same way. It is established tagging. In the other issue, this was clearly demonstrated.

The tag `segregated=yes` is redundant when the sidewalk is tagged. However, it often gets added due to validators (and StreetComplete) asking for the tag.

**Comment by riQQ** [comment]
StreetComplete only ask for segregation if no sidewalk is tagged. It doesn't introduce the invalid tagging:
https://github.com/streetcomplete/StreetComplete/blob/cee1cf445e47835acd0017d064744519848c59a6/app/src/main/java/de/westnordost/streetcomplete/quests/segregated/AddCyclewaySegregation.kt#L15-L28

**Comment by A67-A67** [comment]
So StreetComplete already introduces the wrong tag `segregated=yes` on cycleways where the sidewalk isn't added and then it changes the surface-tags to an incorrect format?

I've revived [the topic on the Dutch forum](https://community.openstreetmap.org/t/duitse-stijl-surface-tagging-op-fietspaden-door-streetcomplete/92572/9).

**Comment by matkoniecz** [comment]
> So StreetComplete introduces the wrong tag segregated=yes on cycleways where the sidewalk isn't added

If there is combined footway/cycleway with neither `segregated=` nor `sidewalk` tags, then StreetComplete edits will result in setting `segregated` tag (and maybe also `cycleway:surface` and `footway:surface` if it is `segregated=yes`) which is not an incorrect tagging.

**Comment by A67-A67** [comment]
`cycleway:surface` is a secondary tag, The primary tag is `surface`. If an object is a cycleway (`highway=cycleway`) the surface information of the cycleway itself should be added to the primary surface tag, not a secondary tag.

**Comment by davidpnewton** [comment]
Which validators? Not the iD one so far as I can tell. That's the one which would result in the most widespread changes. I checked by either removing the segregated or sidewalk tags without saving and it didn't trigger the validator in either case.

My guess would be Osmose as I have come across some improperly coded "error" detection routines in that validator that they have actually refused to fix. Not just accidentally put in there but actually refused to fix when clear problems have been pointed out to them with tagging examples.

**Comment by westnordost** [comment]
The issue at hand is the following:

1. `segregated=yes` with `highway=cycleway` + `foot=yes` (or `=designated`) or any other combination that signifies foot+bicycle is documented in the wiki and shall be interpreted by software as segregated foot+bike path

2. A `highway=cycleway` with a `sidewalk=*` is documented in the (Dutch) wiki and shall be interpreted as a bike path with a sidewalk, i.e. a bike path that is at least segregated from the footway by a kerb.

Now, if both taggings are mixed, i.e. it is 1. and 2. at the same time, the default interpretation will be that it is a...

**Segregated foot and bike path that additionally has a sidewalk.**

This is not a situation that one would expect to actually occur in the real world often (maybe on converted streets without the infrastructure actually having been changed), but this is what the tags express in that case. 

---

Does someone have some numbers on how many times that combination (cycleway + segregated + sidewalk) occur in OSM? How common/de-facto is this tagging?

**Comment by A67-A67** [comment]
I found 11376 ways with `highway=cycleway` + `sidewalk=*` + `segregated=yes` in the Netherlands on [https://overpass-turbo.eu/s/1vaX](Overpass).

`highway=cycleway` + `foot=yes` is in my opinion just a cycleway on which you're allowed to walk. In the Netherlands `foot=yes` is considered default and therefore redundant, because you're allowed to walk on a cycleway unless there is a parallel footway.

At least the JOSM validator asked in the past (and maybe still today) for `segregated=*` on cycleways where pedestrians are allowed. StreetComplete seems to ask for it when sidewalks haven't been added yet. This lead to 16298 ways with both `highway=cycleway` and `segregated=yes`. A mass removal is a lot of work and may cause other issues.

An opinions of some Dutch mappers is that `segregated=yes` is a more general way to say that there is a separation between the location where pedestians and other traffic should go. `sidewalk=*` is the more specific tag.

**Comment by westnordost** [comment]
> An opinions of some Dutch mappers is that segregated=yes is a more general way to say that there is a separation between the location where pedestians and other traffic should go. sidewalk=* is the more specific tag.

Hmm, over 11000 such taggings surely affirm this interpretation as in-use/de-facto tagging.
However, if this is going to be documented as how these tags should be interpreted, then the mentioned situation ...

> Segregated foot and bike path that additionally has a sidewalk.

...essentially becomes un-taggable. How big of a loss that is, I don't know,  but to me it seems like an unnecessary loss.

I recommend you put this to discussion in the forum and subsequently document the outcome in the wiku, so that (also other) data consumers can take this (double) tagging into account.

**Comment by matkoniecz** [comment]
> ...essentially becomes un-taggable. How big of a loss that is, I don't know, but to me it seems like an unnecessary loss.

1) having pedestrian sidewalk on cycleway with separate pedestrian space seems extremely unusual and can be still tagged with sidewalk marked as separate way

> I recommend you put this to discussion in the forum and subsequently document the outcome in the wiku

and please comment here once it happens (or once it is rejected)

**Comment by matkoniecz** [comment]
> I found 11376 ways with highway=cycleway + sidewalk=* + segregated=yes in the Netherlands on https://overpass-turbo.eu/s/1vaX

And 11238 (basically the same) after excluding sidewalk=no / none

**Comment by westnordost** [comment]
Even while the discussion is ongoing, would you say that it would make sense to always ignore `segregated=yes` if there is a sidewalk for the surface overlay, @matkoniecz ? ... since the amount of `segregated=yes` with `sidewalk=*` is substantial.

**Comment by matkoniecz** [comment]
Probably yes, unless it is result of for example some silly undiscussed bot edit.

It can be changed but would be a bit annoying (`segregated=yes` is checked in multiple places from what I remember) so it would be know that we will not get opposite request soon after.

**Comment by westnordost** [comment]
StreetComplete adds this tag in frame of the "Is the bike path segregated from the foo path here?" quest, which is only asked if `foot=yes` or `=designated` is also set on that bike path.
While bike paths with sidewalks exist in the Netherlands, surely bike paths segregated from the foot path not by a curb also exist.

**Comment by matkoniecz** [comment]
It also can be marked in surface overlay (if way tagged as both for pedestrian and cyclists and user uses extra answer that it is segregated into separate spaces)

**Comment by westnordost** [comment]
Following the linked forum discussion, it looks like the active people on the Dutch forum recognized the issue with a combined `segregated=yes + foot=designated` plus `sidewalk=*` tagging and are looking into removing this tagging. So it looks like no action is required from our side.

**Comment by Famlam** [comment]
@westnordost If I understand correctly, if someone tags `foot=yes` on a cycleway (which is unnecessary, but not invalid, unless there's a mandatory footway nearby or a sign that explicitly prohibits it), [Streetcomplete will keep adding segregated=yes](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/segregated/AddCyclewaySegregation.kt) (without asking whether it's segregated as a sidewalk). Subsequently, StreetComplete will add [cycleway:surface](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/surface/AddCyclewayPartSurface.kt) and the footway:surface equivalent in error.

Indeed we'll also need to remove foot=designated as that's in error on a Dutch cycleway, but that was unfortunately highly offtopic in that forum discussion. Keeping foot=yes off of the cycleways on the other hand is undoable, since many editors have presets to add this and people just tend to tick boxes that apply, even though tagging defaults is not necessary.

I believe there should still be a fix from the StreetComplete side, at least to ensure that the user adds sidewalk (if applicable instead of segregated), when asked whether the pedestrian part and the road are separated. If not this will be a recurring issue. People add foot=yes to a cycleway, StreetComplete adds segregated=yes (instead of sidewalk=left/right/both), StreetComplete subsequently adds bad surface tags, we file an issue, we bulk remove tags, people add foot=yes again, etcetera.

**Comment by matkoniecz** [comment]
Cycleway with dedicated sidewalk is `foot=designated` rather than `foot=yes` from what I know

> Indeed we'll also need to remove foot=designated as that's in error on a Dutch cycleway

Also on ones having dedicated sidewalks?

**Comment by Famlam** [comment]
One also doesn't tag foot=designated on every residential with sidewalks (and no pedestrian signs), not? Only if there's an explicit sign (which is very very rare on a designated cycleway). So yes, foot=designated is incorrect. But as streetcomplete (fortunately) doesn't add that tag, let's limit this discussion to the damaging edits please.

**Comment by matkoniecz** [comment]
One option is to disable `segregated` quest in Netherlands. Or add extra step asking about sidewalks vs paint-type separation, probably in Netherlands.

**Comment by westnordost** [comment]
What are the numbers on that?  How many cycleway+sidewalk exist in NL, how many cycleway segregated without sidewalk exist?

**Comment by Famlam** [comment]
I think either of the proposed solutions could work. Probably the latter is more relevant to StreetComplete in case there's more countries where cycleways can have sidewalks.

In The Netherlands, we have:
- 5079 x `highway=cycleway` + `segregated=yes` _without_ sidewalk=yes/left/right/both. This may include Streetcomplete-added cases and some [from the time JOSM required segregated=* on any cycleway via the validator, which hypothethically could've resulted in 3258 cases, using todays `foot=yes/designated` + `segregated=yes` numbers](https://josm.openstreetmap.de/changeset/17457/josm), so likely a significant portion is actually a sidewalk. 358 of them are bridges, they are probably correct.
- 20419 x `highway=cycleway` + `sidewalk=left/right/both/yes` (and 144x `sidewalk:left/right=yes`)
- 35111 x `highway=cycleway` + `segregated=no` and 2980 x `highway=cycleway` + `sidewalk=no` and no `segregated`
- 403 x `highway=cycleway` + `sidewalk=separate`
- roughly 160k cycleways of which the sidewalk / segregation still has to be added

**Comment by westnordost** [comment]
That sounds like StreetComplete should support a third option for cycleway segregation - cycleway with sidewalk - at least in the Netherlands.
