### ISSUE TITLE
Possibility to change the type of highway

### ISSUE THREAD

**Issue by ravenfeld** [streetcomplete/StreetComplete#5038]
In France in any case there are many roads that are badly tagged.
It would be nice if StreetComplete could propose to check this.

Would this be possible?

**Comment by matkoniecz** [comment]
how SC would detect roads that are badly tagged? How people with zero OSM experience would be guided to select correct answer?

(note, name quest allows limited road type retagging on some cases of missing names)

**Comment by ravenfeld** [comment]
Maybe just make a rendering that allows you to select the route. A bit like for the sidewalks, where I use the render to modify the information that is finally wrong.

To help people, via images it helps a lot.
I understand your point and yes, detecting that it is wrong is not possible I think.

**Comment by matkoniecz** [comment]
> To help people, via images it helps a lot.

The problem is that road looking in exactly the same way can be `trunk`, `primary`, `service`, `residential` and `track` depending on its role in road network.

**Comment by matkoniecz** [comment]
I thank that it fails

> Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary

requirement in general.
