### ISSUE TITLE
Feature request: Bus overlay

### ISSUE THREAD

**Issue by heragnar** [streetcomplete/StreetComplete#5041]
**Use case**
In cities, public transport infrastructure is a vital component, particularly in major cities. Apart from bus stops, there is limited information about public transport infrastructure being tagged on StreetComplete.

Mapping bus lanes is just as important as mapping bicycle lanes since they are both prevalent in cities. They often share the same roads in cities where there is no dedicated cycling infrastructure yet.

**Proposed Solution**
The `busway=*` tagging scheme is an ideal fit for how mapping overlays work in StreetComplete and is easy to understand. Simply select each side of the highway where there is a bus lane and indicate the direction of the lane. The app will take care of the rest.

According to the documentation, these schemes are orthogonal to each other, which means this implementation should not interfere with those who prefer a more detailed approach, such as `bus:lanes` and `lanes:psv`

**Proposed UI:**
If the feature is implemented, the appearance of the selector could be similar to this.
![busway](https://github.com/streetcomplete/StreetComplete/assets/130934952/b12daab1-3343-4f45-b424-6ce245c73512)

**Comment by matkoniecz** [comment]
> Simply select each side of the highway where there is a bus lane and indicate the direction of the lane.

Note that:

- busway may be marked already via lane-specific syntax and in such case surveying `busway` is of questionable utility
- in some places such lane allows not solely buses but also some combination of: taxi, motorcycles, bicycles, police etc - in such case not sure is tagging `busway` beneficial and "only bus" would be really confusing
- busway may be not on side of the road but also in the middle
- busway segments may be in form of buses allowed to go straight while other vehicles must turn right from a given lane (again, exceptions may be granted also for example for taxis)

**Comment by NathanARF** [comment]
This would be better done with a general lanes overlay, depicting all traffic lanes in each direction on road segments

**Comment by matkoniecz** [comment]
> This would be better done with a general lanes overlay, depicting all traffic lanes in each direction on road segments

See A/B Street for complex something like that is.

**Comment by heragnar** [comment]
> * busway may be marked already via lane-specific syntax and in such case surveying `busway` is of questionable utility

I believe most mappers don't find redundancy in tagging to be a significant issue. It's done consistently, and the wiki even says it's common to use these tags in this way.

> * in some places such lane allows not solely buses but also some combination of: taxi, motorcycles, bicycles, police etc - in such case not sure is tagging `busway` beneficial and "only bus" would be really confusing

I am not sure how to resolve this issue without adding an overlay for general lane information, which includes all possible scenarios. Additionally, the wiki does not explicitly state that using the "busway" tag excludes other types of transportation. Or maybe I'm wrong. Furthermore, the mockup that I presented was only a rough draft to illustrate my point, and it can be improved by using a pictogram of a bus or simply writing "BUS" instead to avoid any confusion.

> * busway may be not on side of the road but also in the middle

To be honest, I haven't come across many instances of this. Is this really common? Are these BRTs? If buses are running in the middle of the street with bus stops in the center lane, then I believe the streets should be split into three lanes with their respective access restrictions accordingly.

> * busway segments may be in form of buses allowed to go straight while other vehicles must turn right from a given lane (again, exceptions may be granted also for example for taxis)

I think that's beyond the scope of StreetComplete. Access restrictions can be managed using other editors. The purpose of this tag is to signify the existence of a bus lane, and not its restrictions.

**Comment by matkoniecz** [comment]
> To be honest, I haven't come across many instances of this. Is this really common?  

I would not say common, but it exists in some number. Also, may be local oddity basically not existing elsewhere.

https://www.google.pl/maps/@50.0778366,19.9369447,3a,75y,219.1h,80.31t/data=!3m7!1e1!3m5!1skQkatmmGqGQAStrrrf_G_g!2e0!5s20170801T000000!7i13312!8i6656?entry=ttu

![screen](https://github.com/streetcomplete/StreetComplete/assets/899988/e51baa06-2f14-4dbd-b1f2-8d502a317c68)


https://www.google.pl/maps/@50.0717162,19.9294086,3a,31.4y,236.86h,87.82t/data=!3m7!1e1!3m5!1ssWjMjr1BVlxRIVH40CXAGg!2e0!5s20190601T000000!7i16384!8i8192?entry=ttu

![screen01](https://github.com/streetcomplete/StreetComplete/assets/899988/094a0968-2cc6-43b3-bb3f-9c0e82e28c2f)

>  buses are running in the middle of the street with bus stops in the center lane, then I believe the streets should be split into three lanes with their respective access restrictions accordingly.

not such case, though this also exists in some places like https://www.google.pl/maps/@50.0646387,19.9461943,3a,75y,295.13h,91.4t/data=!3m7!1e1!3m5!1sz552dVn8IG1yAqASnBFckQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3Dz552dVn8IG1yAqASnBFckQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D100.19933%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?entry=ttu (and is mapped as separate carriageways)

> It's done consistently, and the wiki even says it's common to use these tags in this way.

Note that it was specifically about value of surveying it - if StreetComplete asks people to fill already tagged busways the utility of such survey is questionable

**Comment by westnordost** [comment]
I'll reject that based on the point that bus lanes are closely interwoven with the lane layout overall. I.e. if there shall be an overlay that targets that, it should be a general lanes overlay. However, this is very complex and it should better be done in an editor that works with satellite imagery rather than on-site survey - best if the roads are then shown WYSIWYG in that editor.

**Comment by matkoniecz** [comment]
> However, this is very complex and it should better be done in an editor that works with satellite imagery rather than on-site survey

on-site survey could be also sometimes useful in cases where trees cover roads or high-quality up to date imagery is not present

and where not everything is visible from aerial 

![screen02](https://github.com/streetcomplete/StreetComplete/assets/899988/877b27d0-3b92-4e21-8fcd-df718eae1903)
pictured: listing what exactly can drive on special lane

(still, that is likely to complex for SC)
