### ISSUE TITLE
ability to add a house name to an already numbered house

### ISSUE THREAD

**Issue by jnicho02** [streetcomplete/StreetComplete#5050]
**Use case**
When collecting house names and numbers, sometimes I notice a house has a name, but it has already been numbered so is not available to enter via StreetComplete. This often occurs if someone has armchair-mapped the house numbers. 

**Current Solution**
Create a note at the house. Remember to edit OSM when you get home. Often, I end up just skipping it, which is a shame because house names can only really be captured from on-the-ground surveys.

**Proposed Solution**
Reactivate a house number request?

This might be a bit too much of a special case for one type of quest...but maybe you have an idea on how it could work?

**Comment by Cj-Malone** [comment]
You can do this via the Addresses overlay (menu -> Overlays -> Addresses), where you can select a building or address node to update, similar to the house number quest. From there the bottom menu has "Address has a house name".

**Comment by riQQ** [comment]
> You can do this via the Addresses overlay (menu -> Overlays -> Addresses), where you can select a building or address node to update, similar to the house number quest. From there the bottom menu has "Address has a house name".

This is only correct if the name is part of the post address.

**Comment by jnicho02** [comment]
It *is* part of the post address....and I didn't know you could do that with the addresses overlay! Problem solved. Thank you @Cj-Malone
