### ISSUE TITLE
Adding parking:side=no deletes parking:left:orientation=* but not parking:side=fee=*

### ISSUE THREAD

**Issue by ivanbranco** [streetcomplete/StreetComplete#5051]
Adding `parking:side=no` deletes `parking:side:orientation=*` but not `parking:side:fee=*`
Example: [link](https://pewu.github.io/osm-history/#/way/42956567)

**How to Reproduce**
Add `parking:side=no` to a way with `parking:side:*=*` tags.

**Expected Behavior**
`parking:side:fee=*` should be deleted (as `parking:side:orientation=*`).

**Versions affected**
Android 13
StreetComplete v53.0

**Comment by westnordost** [comment]
This is not a bug. The overlay does not change any tags it does not tag itself. The overlay does not tag anything regarding fee. This is consistent on what is tagged in the cycleways, sidewalks etc. overlays.
