### ISSUE TITLE
Name for a farmyard in Switzerland

### ISSUE THREAD

**Issue by Codain** [streetcomplete/StreetComplete#5052]
In Switzerland (at least were I live) it is quite common for farms to have a name. This is useful since they are sometimes signed and advertised. Would be great to be able to name them.

**Comment by HolgerJeromin** [comment]
> This is useful since they are sometimes signed and advertised.

Would this be spammy? With too much quests which do not have a proper name.

How to prevent users from entering only the family name of the persons living there?

**Comment by matkoniecz** [comment]
with which tag farmyards are marked in OSM?

**Comment by Helium314** [comment]
Where should the name actually go? `landuse=farmyard`? `building=farm`? `place=farm`? `place=isolated_dwelling`?

**Comment by westnordost** [comment]
No reply.
