### ISSUE TITLE
Area shown as downloaded on map, but no data on device

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5068]
When invalidating downloaded tiles (e.g. on version upgrade), they are set to an age of 12 hours, to have auto-download starting on next occasion.
This has a negative effect on the (new) functionality of showing non-downloaded areas on the map: After an upgrade, the tiles will keep showing as dowloaded for two weeks (minus 12 hours), even if the map data has already been deleted.

This is a minor issue, but it partially defeats the purpose for showing the downloaded area.
My suggestion is not updating the timestamp of a tile if it's already older than the date to be set.

**Comment by Helium314** [comment]
@mnalis I have notices this sometimes, but as far as I remember this "fixed itself" after a while, maybe after scrolling the map to a different place and back again?

@westnordost would it be ok to simply change `DownloadedTilesDao.updateAllTimes`/`updateTime` to only update the timestamp if it is newer than `time`?
(and rename the functions for clarification)

**Comment by westnordost** [comment]
TBH I didn't quite grasp your initial message. But your solution sounds reasonable.
