### ISSUE TITLE
SC quest_type	AddOpeningHours: Don't ask if the defined specific start_date is still in the future

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#5072]
**Use case**
For an object (e.g shop) a specific start_date tag is defined (e.g. start_date=2023-06-15) and this date is still in the future

**Proposed Solution**
I can imagine two possible options:

1) Don't ask for the opening hours at all unless the defined specific start date has already passed.
2) Launch the quest only in case the start date is (very) closed. May be within a range of one/two weeks.

In case of this particular scenario is already considered in the SC program code then skip this issue.
If not refer to https://www.openstreetmap.org/node/1647259282/history as an possible use case.
Fortunately the opening hours are already indicated on the shop.

Best regards
ironspock

**Comment by matkoniecz** [comment]
If shop does not exist then it should not be tagged as `shop=supermarket` but as `construction:shop=supermarket` or in some other similar way (or not mapped at all).

Tagging like operating shop and adding extra tags with meaning `hahaha_actually_not=yes` is a case of a [trolltag](https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35702) and a really silly tagging scheme. And I would treat as broken OSM data.

**Comment by Helium314** [comment]
From the wiki, written in a big red box: "A feature should only have a start date after it really started...".

For such cases `opening_date` should be used, best in connection with a lifecycle prefix as mentioned by @matkoniecz (troll tag was also my first thought here)

**Comment by ironspock** [comment]
@matkoniecz @Helium314 
Ok, it is/was a misunderstanding/incorrect tag usage from my part. Thanks for making me aware of.

**Comment by Helium314** [comment]
If the shop would use the `construction` prefix, maybe SC could ask whether construction is completed (similar to buildings and highways), but that would only apply to a small number of places (see #4855)

**Comment by matkoniecz** [comment]
> maybe SC could ask whether construction is completed

Yes I though about this, but last time I checked such place worldwide counted in hundreds or less.
