### ISSUE TITLE
Similar quests not distinguishable (wheelchair quests) 

### ISSUE THREAD

**Issue by vehrmann** [streetcomplete/StreetComplete#5075]
Hello everyone, 
In the quest list, there are 4 identical wheelchair quests. The differences (except the icon color) are not obvious. 
This issue could be solved by adding a descriptive word in brackets to the quest title or by adding an info icon, which shows more details about a quest when clicking on it in the list.

![image](https://github.com/streetcomplete/StreetComplete/assets/60914642/b5b8259b-282a-4d4e-82bc-f70bcf438139)

**Comment by westnordost** [comment]
currently it just shows the icon and the question. Additional information is not available that easily. Or what did you have in mind? To show the element selection would be far too much information and far too technical.

**Comment by westnordost** [comment]
The two identical-looking ones by the way are 1. for toilets and 2. for other outside-places (currently only: dog park).

Maybe these two could be put instead into one quest only.

**Comment by FloEdelmann** [comment]
Or maybe rather merge both toilet-related quests into one?

The "toilet at this place" quest title could then used in the quest selection, and the "toilet at this place" or "this place" quest titles should be used for the actual quest depending on the element.

Or we can find a single new wording that works for both toilets themselves and places (e.g. restaurants) that contain toilets.

**Comment by vehrmann** [comment]
I looked into the wiki and think that the quests asking for wheelchair-access to **toilets** could be combined.
It would need to add different tags though, but this should technically be possible I guess?
Pseudocode:
`IF quest is shown for amenity = toilet`
`THEN add tag wheelchair=yes/no/limited`
`ELSE IF quest is shown for toilets = yes`
`THEN add tag toilets:wheelchair=yes/no/limited`

If this should be put into a new issue, I am happy to do so.

![image](https://github.com/streetcomplete/StreetComplete/assets/60914642/679a482f-9e1c-45c2-900f-c0e8b70f8646)

**Comment by vehrmann** [comment]
And the wheelchair quest asked for `leisure=dog_park` could be merged with the first one with the orange icon (which already asks this quest for (some) `leisure=*`)

**Comment by westnordost** [comment]
They can't be combined, the question is different and how it is tagged is different. One asks for the toilet **in** a place (e.g. a mall) while the other asks for whether the whole thing is wheelchair accessible (in that case, toilets / dog park)

**Comment by westnordost** [comment]
I've decided to leave it as it is. While maybe 2 quests could be merged into one, then it wouldn't be possible to only activate wheelchair quests related to public transport. I myself do not thinkg this is necessary, but maybe other do. And the advantage of having less quests also seems to be negligible, i.e. I don't really see the point in merging them.
