### ISSUE TITLE
Search function in quest list only works with full terms

### ISSUE THREAD

**Issue by vehrmann** [streetcomplete/StreetComplete#5076]
Dear all,
the seach function in the quest list seems to search only for full phrases (at least it is not case sensitive).
See attached screenshots below.

**How to Reproduce**
German version: Go to the quest list and search for "rad" as well as "fahrrad" -> different quests show up for each search

**Expected Behavior**
When searching for "rad" I'd expect to also see all quests containing the word "Fahrrad"

**Versions affected**
v53.1

![image](https://github.com/streetcomplete/StreetComplete/assets/60914642/5f93825e-8773-4eac-8abd-fa90a6b111d5)

**Comment by westnordost** [comment]
It's not a bug, it requires the word to **start** with what you input.

**Comment by westnordost** [comment]
I'll try it out. I suspect that it will return a lot of other "nicht nachvollziehbare" results too, because I suspect there are many words that have "rad" somewhere within it.

**Comment by mnalis** [comment]
**If the results happen to be too many**, the solutions I've usually seen (e.g. OsmAnd) for that _"show all matches" vs. "most common matches" dilemma_ seem to be to include all matches, but put common ones at the beginning of the list. The full workflow seems to be:

- firstly, put only **exact matches** (e.g. only exact word `rad` would be matched by regex `\brad\b`)
- then, add the matches **starting** with requested pattern, which aren't already in the list (e.g. regex `\brad` would match `radeln`)
- then, add all the matches which contain requested pattern **anywhere**, and which aren't already in the list (which would include everything else, e.g. `fahrrad`).

That has advantage that the things that are most commonly searched for are still at the beginning of the list so easily found (so no disadvantage to current implementation), but also has the advantage that if you wanted full search (as @vehrmann) it would also work; it would just be listed somewhat lower.

Disadvantage is that is little more implementation work, and that it is a little slower. But I don't think that should be a big issue here.

**Comment by westnordost** [comment]
Would need to try it out if it feels okay.

**Comment by westnordost** [comment]
I tested it, it didn't feel unexpected/weird.
