### ISSUE TITLE
Allow tapping a named street to fill out the name for sections of a street that are missing the name

### ISSUE THREAD

**Issue by grrrrr** [streetcomplete/StreetComplete#5083]
**Use case**

With StreetComplete you can manually type in the name of a street, in a lot of cases the way can be broken up into smaller joined ways.  for example if streets have been split to mark start / end of footpaths or cycle lanes.

As a result in areas without a name  you can end up having to re-input the name of a street on multiple ways

**Proposed Solution**

Similar to how you can select a street name for a building,

- select the name task on the section of street to add the name
- tap on section of street with a name already defined
- auto fill out the name for the unnamed section.

bonus: if name exists in other languages (e.g. name:fr, name:en) copy these over too

**Comment by arrival-spring** [comment]
When an adjoining road has a name, there is an arrow at the side of the text entry box that allows you to select the name. Is this not discoverable enough?

**Comment by grrrrr** [comment]
> Is this not discoverable enough?

Apparently not,  first I am noticing it :/
