### ISSUE TITLE
How many cargo bikes can be parked here?

### ISSUE THREAD

**Issue by NathanBnm** [streetcomplete/StreetComplete#5084]
### General
Affected tag(s) to be modified/added: Adding `capacity:cargo_bike` on [amenity=bicycle_parking](https://wiki.openstreetmap.org/wiki/Tag:amenity=bicycle_parking) (See [cargo_bike](https://wiki.openstreetmap.org/wiki/Key:cargo_bike))
Question asked: **How many cargo bikes can be parked here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

### Example

Here, for example, is a bike park with a space specifically designated for cargo bike:

<img width="1017" alt="Capture d’écran 2023-06-19 à 09 53 47" src="https://github.com/streetcomplete/StreetComplete/assets/45366162/c1572bad-757f-4a7b-889a-aa916d17761d">

The OSM data would be at least:

```
amenity=bicycle_parking
bicycle_parking=stands
capacity=7
capacity:cargo_bike=1
```

**Comment by HolgerJeromin** [comment]
>  🚧 To be added tag is established and has a useful purpose

1200 tags (half yes, half no) is IMO not really "established": 
https://taginfo.openstreetmap.org/keys/cargo_bike#overview

>  💤 Not an overwhelming percentage of quests have the same answer (No spam)

I have never seen such marking in germany.

>  🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary

Without such a marking the user would start guessing how many cargo bikes would fit ("the inner place is too small, but when the outer parking place would be free, this would fit a cargo bike").

**Comment by westnordost** [comment]
See @HolgerJeromin , it does not look like this is a tag where it is reasonable to ask for / add it to every `amenity=bicycle_parking`.
