### ISSUE TITLE
High change in "global rank" within one day - statistics are being recalculated

### ISSUE THREAD

**Issue by jmizv** [streetcomplete/StreetComplete#5086]
In the past weeks I could accomplish to get a global rank of almost 800 (cf. profile page). Yesterday I reached a global rank of about 250 but I did not solve that many quests. Today I'm down to rank 347 having solved less than 100 quests in 24hrs. My current solved quest counter shows: 8029.

Maybe this is no bug but there is a explanation for this? Has there been a change in computing these ranks?

**How to Reproduce**

Not sure about the reproduction but maybe others have seen this, too.

**Expected Behavior**

Maybe: not to crazy jumps in ranks?

**Versions affected**

53.1

**Comment by FloEdelmann** [comment]
Yes, see https://github.com/streetcomplete/StreetComplete/issues/5074#issuecomment-1598728083

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/StreetComplete/issues/5074#issuecomment-1599098753 - data is being regenerated

**Comment by mnalis** [comment]
Now mentioned in [FAQ#Why does the star counter not match the sum of previous stars and upload counter?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_the_star_counter_not_match_the_sum_of_previous_stars_and_upload_counter%3F)

**Comment by westnordost** [comment]
It is now done at approximately 50%.

However, the data for the top 100 users is already re-aggregated now. I just triggered it for the up to top 300 too. I think, anything beyond that will just be done on-demand.
