### ISSUE TITLE
Hint the type of check quest

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#5089]
**Use case**

All the check quests look the same, making it impossible to determine from the map view if a check quest can be completed.
I often find myself clicking on a check quest, only to find I cannot complete it because I'm not able to enter the building or am in a car and have a limited view.

![Screenshot_20230624-085320_1](https://github.com/streetcomplete/StreetComplete/assets/7458098/103a7520-dab6-425a-ad79-29dfcded5735)

To illustrate, just now I encountered a the above situation where it is a mystery what the check quest entail. The only way to find out is to click and read.

**Proposed Solution**

How about making specific icons for check quests? Some ideas come to mind:

- Normal quest or tag type icon with an overlay icon of the checkmark or a clock (time based check). The overlay makes it distinct from other quest types.
- Use regular icons to symbolize the type of check (like above) but instead of the white pin use a different color pin (green?) to make it distinct.

Both ideas might hinder legibility though. The first by cramming to much detail in the round logo, the second by leaving the clear white pin background.

**Comment by westnordost** [comment]
What quests exactly are you speaking about? The background color for two are already different. And, why can you not complete certain check quests? For which do you need to go inside?

**Comment by nicorikken** [comment]
I never noticed the color difference, they look almost similar, good you mention it. Perhaps the colors can be more distinct (option?). At least I can pay more attention so I actually observe the difference.

I had to go indoors to check the existence of an ATM, the same would hold for toilets. https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt

Perhaps the presence checks can be broken down to a number of different quests?

Considering that no-one else stepped in on this issue, I'm fine closing it. It can always be re-opened in the future and will remain available for reference.

**Comment by westnordost** [comment]
Generally, the orange ones are business or something, the green ones are amenities and stuff.

Ok I'll close it.
