### ISSUE TITLE
Move translations to Weblate

### ISSUE THREAD

**Issue by comradekingu** [streetcomplete/StreetComplete#5092]
Translators don't want to use the current closed, SaaS-only solution and prefer Weblate.

For how well-meaning #2980 is, the greater issue that translators care about is #2978 #1099 #1035

It isn't as credits inspired anyone to use a platform that doesn't have them, and moreover aren't getting them soon.
Meanwhile, it should be possible to just lock the project and leave it open for people to see who did what and set up shop
on Weblate.

**Comment by westnordost** [comment]
I prefer POEditor. Moving to another place also means losing all current translators.

**Comment by westnordost** [comment]
MapComplete is a completely different project than StreetComplete, how is this related? And how is this related to that the author added a nettiquette of sorts?

**Comment by jermanuts** [comment]
Hello, I can't contribute to StreetComplete due to being blocked when creating account (reCAPTCHA hell), I never had issues using Weblate. Also Weblate UX/UI is much better and has better discoverability while being FOSS.
