### ISSUE TITLE
surface quest answer "rock": add split photo and/or rename

### ISSUE THREAD

**Issue by georg-d** [streetcomplete/StreetComplete#5094]
**Use case**

Quite a number of Alpine paths have a surface of big, crushed (=not round) rock fragments like https://wiki.openstreetmap.org/wiki/File:Rock_Trail_Surface_at_Patapsco_Valley_State_Park.jpg – sometimes in a similar scree setting, sometimes the blocks were placed by humans e.g. in marshy parts of a path. 

Currently, the appropriate answer is EN "Rock" and DE "Fels", but I am again and again hesitant to choose that answer:

1. The value "rock" is, depending on the OSM key, _sometimes_ only applicable for rock that is _attached to the underlying bedrock_ (e.g. see https://wiki.openstreetmap.org/wiki/Tag:natural%3Drock) and I have no help in SC whether in the context _of this quest_, the rock must be fixed or may be loose.
2. The current photo in SC is quite ambigous; it could also depict gravel of inhomogenous size. 

So as a result, we have less answers than we may get, and the answers we get, they may be wrong more often than we may achive (after looking at actual OSM data, I assume others have similar problems to tell apart).

**Proposed Solution**

As with paving_stones / Pflastersteine, let's use a split photo, e.g. a mix of https://wiki.openstreetmap.org/wiki/Tag:natural%3Dbare_rock and https://wiki.openstreetmap.org/wiki/Key:surface#Unpaved

and/or

Rename to "rock or big edged stones" or better, clearer wording

**Comment by westnordost** [comment]
Current picture is https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/drawable-xxhdpi/surface_rock.jpg

So, you are missing a picture for bigger rocks like can be seen in https://wiki.openstreetmap.org/wiki/File:Rock_Trail_Surface_at_Patapsco_Valley_State_Park.jpg ?

**Comment by georg-d** [comment]
> So, you are missing a picture for bigger rocks like can be seen in https://wiki.openstreetmap.org/wiki/File:Rock_Trail_Surface_at_Patapsco_Valley_State_Park.jpg ?

Yes, a picture where bigger rocks/stones are more clearly recognizable, like they are in https://wiki.openstreetmap.org/wiki/File:Rock_Trail_Surface_at_Patapsco_Valley_State_Park.jpg where the tree makes clear which size the rocks are.

I suggest a split photo because the value `rock` is _also_ applicable to something like https://wiki.openstreetmap.org/wiki/File:Coastal_rock_formation.jpg (clearer when photo has small dimensions) or https://wiki.openstreetmap.org/wiki/File:Cascade_canyon_trail_teton_20190713_095423_1.jpg (similar issue as with current photo: not that clear when photo is displayed small)

**Comment by westnordost** [comment]
Actually, I will replace the current photo with the one you posted. The old picture is from Elliot Plack too (and I can't find the source, probably he just posted it in the chat), and if he decided that https://wiki.openstreetmap.org/wiki/File:Rock_Trail_Surface_at_Patapsco_Valley_State_Park.jpg is a more representative one that should go in the wiki (and the other not), then that is the one we shall use too.
