### ISSUE TITLE
Is this parcel locker inside a building?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#5098]
### General
Affected tag(s) to be modified/added: [indoor](https://wiki.openstreetmap.org/wiki/Key:indoor)
Question asked: **Is this parcel locker inside a building?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
`amenity=parcel_locker + !indoor`

**Metadata needed:** 
No

**Proposed UI:**
Yes/No/Add note should work.

**Comment by thany** [comment]
Would this also work for (publicly accessible) baggage lockers, like the ones at or near stations?

**Comment by Dimitar5555** [comment]
It could work, assuming there is a schema for tagging them.

**Comment by mnalis** [comment]
> It could work, assuming there is a schema for tagging them.

yes, there exists  [amenity=luggage_locker](https://wiki.openstreetmap.org/wiki/Tag:amenity=luggage_locker) (as well as [amenity=locker](https://wiki.openstreetmap.org/wiki/Tag:amenity=locker))

**Comment by westnordost** [comment]
See linked issue.
