### ISSUE TITLE
What are the opening hours of this parcel locker?

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#5099]
### General
Affected tag(s) to be modified/added: [opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours)
Question asked: **What are the opening hours of this parcel locker?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary

I'm not entirely sure on this one, since some parcel lockers are located inside of malls or shops and require the user to check the respective shop's opening hours. It may not be obvious to all users so they might enter 24/7.

- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
`amenity=parcel_locker + !opening_hours`

**Metadata needed:** 
None

**Proposed UI:**
Similar to the quest for opening hours of shops.

**Comment by arrival-spring** [comment]
Many parcel lockers that I see are outside and, although I haven't checked, I would assume that they are all 24/7. So to avoid "no spam", perhaps this should be limited to `indoor=yes`?

**Comment by Dimitar5555** [comment]
I thought of this thing after I added the idea, but I was busy and couldn't edit the post. Otherwise, I completely agree.

**Comment by westnordost** [comment]
To avoid misunderstandings and thus wrong taggings, the app should display whether a POI is inside (see #5170, in turn blocked by #5175) before this is implemented. (A PR can be created before, but cannot be merged until then.)

The filter should be something like
```
or amenity = parcel_locker and (indoor = yes or addr:floor or level:ref or level)
```

Additionally, it would make sense to also include ATMs, maybe more (see also POI list in #5175).

**Comment by qugebert** [comment]
now unblocked (after commit https://github.com/streetcomplete/StreetComplete/commit/0daa12bf83f5173fc37b56b76530abb3c6c53d90)

**Comment by westnordost** [comment]
Should not be a new quest but the opening hours quest should just be extended to include this, too.
