### ISSUE TITLE
Upgrade crossing=marked and crossing=zebra tags

### ISSUE THREAD

**Issue by Zaczero** [streetcomplete/StreetComplete#5100]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

nwr[crossing=marked]
nwr[crossing=zebra]

**Metadata needed:** 

**Proposed UI:**

Same answers as for the general crossing quest: uncontrolled, traffic_signals. Possibly make use of crossing:markings too.

**Comment by AndrewHain** [comment]
@westnordost `crossing=zebra` has been [deprecated](https://community.openstreetmap.org/t/voting-feature-proposal-deprecate-crossing-zebra-in-favor-of-crossing-markings/115293/138). https://wiki.openstreetmap.org/wiki/Proposal:Deprecate_crossing%3Dzebra_in_favor_of_crossing:markings

**Comment by mnalis** [comment]
> crossing=zebra has been [deprecated](https://community.openstreetmap.org/t/voting-feature-proposal-deprecate-crossing-zebra-in-favor-of-crossing-markings/115293/138).

@AndrewHain  Note that this issue has been closed for over 2 years (for reasons mentioned in https://github.com/streetcomplete/StreetComplete/issues/5100#issuecomment-1614665265), and StreetComplete  Quests  nowadays _already_ tag [crossing:markings=*](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_markings/AddCrossingMarkings.kt) and [crossing:signals=*](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_signals/AddCrossingSignals.kt) which that wiki recommends. 

If you think that StreetComplete should do something differently than it currently does, it would be best to open new GitHub issue and specify exactly what it is  (as comments on closed issues are likely to be missed).
