### ISSUE TITLE
Support render and quests on highway=platform

### ISSUE THREAD

**Issue by Zaczero** [streetcomplete/StreetComplete#5103]
**Use case**

It's odd to see gaps in ways where a highway platform mapped.

**Proposed Solution**

Enable rendering of highway platforms. It would also be nice to support quests such as surface.

**Comment by riQQ** [comment]
See streetcomplete/streetcomplete-mapstyle#105

**Comment by westnordost** [comment]
Gaps in ways?

**Comment by Helium314** [comment]
> Gaps in ways?

Some poeople map `highway=platform` as part of a separately mapped sidewalk. In SC, places like [this](https://www.openstreetmap.org/#map=19/48.26028/16.45528) appear to have a gap in the sidewalk.

**Comment by rhhsm** [comment]
Maybe it's only an issue for platforms mapped as areas? In my neighbourhood such platforms are mapped as ways, with additional `highway=footway` and `footway=sidewalk` tags, and these work fine.
I would welcome quests for surface, etc. for platforms that are not mapped as highways.

**Comment by Zaczero** [comment]
Examples:
https://www.openstreetmap.org/way/327979669
https://www.openstreetmap.org/way/1103271778

**Comment by matkoniecz** [comment]
> It's odd to see gaps in ways where a highway platform mapped.

This appears with incorrect mapping, there should be `highway=footway` there

**Comment by Zaczero** [comment]
@matkoniecz where did you get that from? From what I have seen so far, this is a very popular use-case for this tag.

**Comment by westnordost** [comment]
Anyway, feel free to continue this discussion but I'll close this issue because highway=platform cannot be rendered in the app, see the first comment.

**Comment by Zaczero** [comment]
So my understanding is that it's due to a Jawg limitation? I'm quite surprised to see that SC so heavily relies on a proprietary map provider.

**Comment by mnalis** [comment]
Do you know of other non-proprietary vector map provider which might suit StreetComplete better @Zaczero ?

**Comment by mnalis** [comment]
> No, I have never researched such things. 

Oh, OK.

> Why?

Well I thought you might have, as you said you're _"quite surprised to see that SC so heavily relies on a proprietary map provider"_. Which seemed imply to me that you might know of a better alternative, so you're surprised SC is not using that alternative instead.

**Comment by Zaczero** [comment]
I was just surprised because I had assumed that StreetComplete would not be proprietary at all.

**Comment by matkoniecz** [comment]
@Zaczero I would be happy to discuss whether it is on to skip highway=footway in such case, or is it being skipped in actual mapping.

But tagging mailing list or official OSM forums (please ping me there if you would start a thread) would be much better place for that
