### ISSUE TITLE
Overlay/Layer for Bicycle Stands

### ISSUE THREAD

**Issue by jabdoa2** [streetcomplete/StreetComplete#5110]
**Use case**
I would like to map/correct bicycle stands/parking. Currently, when StreetComplete asks for capacity or whatever a stand has a roof its sometimes hard to understand if this is mapped as one or three stands. Also a lot of stands are missing in my area so it would be nice to add those as well.

**Proposed Solution**
This could either become a new overlay (similar to shops) or it could become parts of the bicycle path overlay (Fahrradwege in German). I personally would prefer the latter. Basically a bicycle focused overlay.

**Comment by jabdoa2** [comment]
Just found that this is actually mentioned in #4912. Sorry for the duplicate.

**Comment by Helium314** [comment]
> its sometimes hard to understand if this is mapped as one or three stands

You always see bicycle parkings within ~30 m while the quest form is open.
