### ISSUE TITLE
Zoom-in when double-pressing GPS button like in other map apps

### ISSUE THREAD

**Issue by soredake** [streetcomplete/StreetComplete#5111]
**Use case**
It's useful.

**Proposed Solution**

How StreetComplete behaves:

https://github.com/streetcomplete/StreetComplete/assets/5204968/f7c1dec9-875f-4c47-be34-655a2994aeff

How OsmAnd behaves:

https://github.com/streetcomplete/StreetComplete/assets/5204968/1f8ae965-c01f-40a2-bbc0-ce1e4b6b2ed8

How google maps behaves:

https://github.com/streetcomplete/StreetComplete/assets/5204968/0352d92b-524c-4ac7-af75-3039ecdc8f8f

**Comment by westnordost** [comment]
This behavior is not as universal (and thus expected) as you think. 

OrganicMaps, Maps.ME and Mapy.cz all have a different behavior for this button - the same behavior as StreetComplete. Switch between North-Up and rotate to walking direction. And as a matter of fact, even Google Maps shares that very same behavior, only that when switching to the rotate-towards-compass-direction mode, it automatically zooms in to a certain minimum zoom.

Also, you can zoom in by double tapping anywhere on the map.

**Comment by soredake** [comment]
Maybe an option for this can be added?

**Comment by westnordost** [comment]
No
