### ISSUE TITLE
In a quest give more details about feature, eg level

### ISSUE THREAD

**Issue by stephankn** [streetcomplete/StreetComplete#5114]
**Use case**
I got asked whether something is still existing.
Toilets or ATM. Valid question, but I am at an airport. Which level is the feature in question located?

![Screenshot_20230702-195505](https://github.com/streetcomplete/StreetComplete/assets/251140/5c31a6ca-2ec4-4eab-89c0-42c29b191371)

Such few details provided does not allow me to answer the quest.

In other quests I also wished for further details like names in other languages.

**Proposed Solution**
How about providing a small i icon which gives me full tagging details of the element in question? Sounds like a quite generic solution to all quests where the details are not enough.

**Comment by stephankn** [comment]
Level seems to be actually listed. I see it on a different quest. Maybe data initially lacks level tag.

Point about different name tag remains.

**Comment by westnordost** [comment]
Restrooms usually do not have a name, so showing multiple names would not help in this case.

**Comment by stephankn** [comment]
Example where I would like to know name in latin script:

![Screenshot_20230702-205157](https://github.com/streetcomplete/StreetComplete/assets/251140/383132b1-364c-46d7-b05c-4b4612272988)

Probably other examples exist as well where additional details about a feature would be helpful. That's why I thought of a button to display all tags.

**Comment by stephankn** [comment]
Restroom is still there. Not certain about the location. The one upstairs is more on the eastern edge of the building.
Requires a full editor to check. I took photos.

**Comment by westnordost** [comment]
Why would a translated name be useful? After all, if you are on-site, this is what will be written on the machine. Even if you don't know the script (but I know, *you* do), you can check if it is the correct ATM by comparing the "runes" displayed in the app with what is displayed on the machine.

**Comment by stephankn** [comment]
My Thai reading is far from fluent and takes significant time.
TMB is significantly quicker to get as it is also written in Latin script on the machine.

What are reasons against providing a way to display the existing tagging?

**Comment by westnordost** [comment]
Reason against 

> How about providing a small i icon which gives me full tagging details of the element in question

is primarily the general decision for the app not to make the raw tags part of the interface as the app is aimed at and should be usable by without tradeoffs by non-technical people who do not know anything about the OSM tagging.

For showing the (English? which? all?) name also in the text field below the question, I primarily do not see added value that would warrant the extra effort and complexity.

**Comment by mnalis** [comment]
> general decision for the app not to make the raw tags part of the interface as the app is aimed at and should be usable by without tradeoffs by non-technical people who do not know anything about the OSM tagging

Agree and support that decision! 

That being said, [SCEE fork](https://wiki.openstreetmap.org/wiki/SCEE) (_"SC Expert Edition"_) of StreetComplete is aimed towards more advanced OSM mappers; so it can show raw tags in all quests (and allows the user to edit them too, should they wish to do so), while by default trying to look/behave mostly the same as upstream.
