### ISSUE TITLE
Can't enter lanes count when road has different lanes amount on the 2 directions 

### ISSUE THREAD

**Issue by Deddi-k** [streetcomplete/StreetComplete#5118]
On android 10, with street complete version 53.2, when I am asked "how many car lanes doea this road have", and I select "each side has a different number of lanes", I get a road icon with question marks for both directions. I can only enter the number of lanes to one direction. I can't switch to the other direction and enter the number of lanes there, or finish the edit.

**Comment by westnordost** [comment]
Have you tried tapping on these question marks?

**Comment by Deddi-k** [comment]
Yes. On one direction, tapping on the question marks opens a selection
panel for nember of lanes. But I couldn't tap or move to the other
direction, to select the number of lanes there.
Attached is a screenshot of the situation after entering the number of
lanes in the first direction. The other direction is not selectable.

בתאריך יום ג׳, 4 ביולי 2023, 17:21, מאת Tobias Zwick ‏<
***@***.***>:

**Comment by westnordost** [comment]
So, you tap on that side, but there is no UI feedback that you tapped it?

(The pciture attached via email didn't surface here on github)

**Comment by FloEdelmann** [comment]
@Deddi-k By the way (sorry for the off-topic): You seem to use your email client in Hebrew, right? Would you be interested in [translating the app](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app) to Hebrew? Hebrew translations are currently 50% complete; once it comes close to 100%, it can be enabled in the app.

**Comment by Deddi-k** [comment]
Correct. Tapping the second direction, which has question marks, doesn't do
anything. The only way out is to discard the changes.

בתאריך יום ג׳, 4 ביולי 2023, 17:34, מאת Tobias Zwick ‏<
***@***.***>:

**Comment by Deddi-k** [comment]
Yes, sure. I will look into it.

בתאריך יום ג׳, 4 ביולי 2023, 17:55, מאת Flo Edelmann ‏<
***@***.***>:

**Comment by Deddi-k** [comment]
Another off-topic: I saw in the settings that the quest "what number or
code identify this stop" is disabled in Isreal. Bus stops in Isreal do have
codes identify them, so I think this quest can be enabled.

בתאריך יום ג׳, 4 ביולי 2023, 18:25, מאת david karpin ‏<
***@***.***>:

**Comment by FloEdelmann** [comment]
I can reproduce the issue when the Android system language is set to Hebrew; it works fine in German. So probably it's an RTL (right-to-left text) issue.

**Comment by westnordost** [comment]
Fixed.

And, congratulations on the translations so far, you alone now contributed 24% of the translation to Hebrew! Keep going and your language can be included in the next update! :-)

**Comment by Deddi-k** [comment]
Thanks.
While translating, I found some of the terms hard to translate because they
are out of context and it is hard to understand what meaning in Hebrew will
fit. I saw each term has a "parameter name" written underneath in gray,
which sometimes give a bit more data, but doesn't always help to figure it
out.
Just 2 examples:
- in "Keep closer to the arrow but watch out for traffic!
ar_core_tracking_error_no_plane_hit" - what arrow is it? In Hebrew it can
be translated into few terms.
- in "Create new track recording
map_btn_create_track" - what does track refer to? I can think of a few
meanings in Hebrew which might fit.
Is there a way to get a better understanding of the context in which each
term is used in the system? Maybe to see an example of where it is being
used?

בתאריך יום ו׳, 7 ביולי 2023, 00:41, מאת Tobias Zwick ‏<
***@***.***>:

**Comment by westnordost** [comment]
Hmm, so one option is to search for the id of the string in the source code to get context. For example for the string id `unsynced_quests_description`: 
https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete+language%3Akotlin+unsynced_quests_description&type=code

This does not directly give a comment about the context, but reading the names within that file, you might get an idea in which screen the text is used.

Other than that, what might help is to change the reference language. So, you do not see the to be translated strings in English but e.g. in French.

---

Regarding the two examples you posted, the AR Core stuff `ar_core_tracking_error_no_plane_hit` actually has been put into another app, called [StreetMeasure](https://play.google.com/store/apps/details?id=de.westnordost.streetmeasure). Translations still happen in this project though, for simplicity. (See the screenshots in the play store to see which arrow is meant.)

> what does track refer to?

When you long-press on the map, you can start recording your GPS positions, this creates a GPS track which you can subsequently attach to a note.
