### ISSUE TITLE
Enable bus stop ref quest in Israel

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5119]
_Originally posted by @Deddi-k in https://github.com/streetcomplete/StreetComplete/issues/5118#issuecomment-1620450724_

> I saw in the settings that the quest "what number or code identify this stop" is disabled in Isreal. Bus stops in Isreal do have codes identify them, so I think this quest can be enabled.

@Deddi-k, could you please post a photo of how those reference numbers look like?

**Comment by Deddi-k** [comment]
I'm attaching 2 photos of how those reference numbers are displayed:
1. on the station's top sign (the sign has 2 sides, one in Hebrew \ Arabic and the other in English - the picture is of the English side)
2. on the routes sign in the station itself.

Those numbers are also shown in some of the navigation apps used in Israel (I've attached also a screenshot from the Moovit app which shows the reference number of a bus stop.

The Israeli National Authority for Public Transportation publishes the reference nunber of all stations in the GTFS format (as explained [here](https://www.gov.il/BlobFolder/generalpage/gtfs_general_transit_feed_specifications/he/GTFS_Developer_Information_2022.07.27.pdf)), so I believe the information can be imported from there.
![20230705_123249](https://github.com/streetcomplete/StreetComplete/assets/138598657/366555ce-4db1-4e6b-8ed0-da77b4d18d94)
![20230705_080758](https://github.com/streetcomplete/StreetComplete/assets/138598657/650145df-746a-48ff-99ad-1e1c04ff0d59)
![20230705_080820](https://github.com/streetcomplete/StreetComplete/assets/138598657/b79dd410-60ab-4aca-88cc-3c77c667ba1b)

**Comment by FloEdelmann** [comment]
The number seems to be clearly indicated, so enabling the quest in Israel should be no problem :slightly_smiling_face:
