### ISSUE TITLE
Enable `AddAcceptsCash` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5122]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddAcceptsCash

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> Are there many places that do not accept cash? Otherwise, (nearly) every answer would be "yes", so this quest would not pass the "no spam" guideline.

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> Regarding "AddAcceptsCash," many shops stop receiving cash only to receive cards, but I don't know the total number of shops accepting and not accepting cash.

---

To enable this quest and not violate the "No spam" rule, neither "yes" nor "no" should be the correct answer in more than 90% of all quests. Do you think this is realistic?

**Comment by westnordost** [comment]
No feedback, closing
