### ISSUE TITLE
Enable `AddEntranceReference` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5123]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddEntranceReference

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> Can you post a photo how those reference numbers look like?

by @matkoniecz in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1605309473

> Seems really rare: http://overpass-turbo.eu/s/1wtT http://overpass-turbo.eu/s/1wtU

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> "AddEntranceReference" could be used for houses with multiple doors with a different house number on each one, where a door connects directly to the second floor and another connection to another place in the house, for example. I know they exist, but I don't have details for the whole country.

---

To enable this quest and not violate the "No spam" rule, "no reference" should be the correct answer in less than 20% of all quests. Do you think this is realistic? Could you post a photo of those reference numbers, to see how easy it is to recognize?

**Comment by matkoniecz** [comment]
Going  by actual tag use this feature does not appear to exist in this region

This quest is also not suitable for cases where difference doors have different addresses
