### ISSUE TITLE
Enable `AddBusStopRef` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5124]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddBusStopRef

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> Can you post a photo how those reference numbers look like?

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> The bus stops have a number on them, and "AddBusStopRef" could be used for that. I don't know how many bus stops do not have numbers across the country, but I know there are more than 6000 bus stops with a ref number only in Bogota.

---

Could you post a photo of those reference numbers, to see how easy it is to recognize? Do nearly all bus stops have such a reference number, so that "no reference number" does not need to be answered in more than 10% of all quests?

**Comment by angoca** [comment]
https://www.mapillary.com/app/?pKey=594008284905754

https://www.mapillary.com/app/?pKey=552049902453929

https://www.mapillary.com/app/?pKey=329848595239867

**Comment by westnordost** [comment]
Well, I independently checked some bus stops in Bogota via google street view and any single one had a prominent ref number, so I'll just include that.
