### ISSUE TITLE
Enable `AddCycleway` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5125]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddCycleway

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> So many streets do have cycleways?

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1605199784:

> [Photo 1]
> [Photo 2]
> [Photo 3]
> https://en.wikipedia.org/wiki/Bogot%C3%A1%27s_Bike_Paths_Network

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> And you asked me, "So many streets do have cycleway?". I already wrote that only Bogota has more than 500 Km of cycleways, and other cities have a lot of cycleways too. However, I don't know the total kilometers of cycleways, so we are mapping them.

by @mnalis in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1623844508:

> I think it is misunderstood, it was never about **absolute** number of cycleways (or their total length). It is about **ratio** of _"roads that has cycleways"_ to _"roads that don't have cycleways"_. In other words: _**"what percentage of answers to that quest would have same answer?"**_
>
> So the information _"about 1 in 5 roads has cycleways"_ has great amount of wanted information (even if actual more precise number is _"1 in 3"_ or _"1 in 7"_ instead!), but _"there is 500km or cycleways"_ or _"there is 7k cycleways"_ would be useless, as it would not help answer the _"spamminess"_ question. 

---

Do you think that neither "yes" nor "no" would need to be chosen in more than 90% of all quests?

**Comment by westnordost** [comment]
No feedback, closing
