### ISSUE TITLE
Enable `AddFireHydrantDiameter` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5126]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddFireHydrantDiameter

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> Can you post a photo how the hydrant diameter sign looks like? Is nearly every hydrant signed by such a sign?

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> Similar thing for hydrants, I don't know the total, but I know there are different types of diameters with the number on them (4 inches, 6 inches, 8 inches).

---

To enable this quest and not violate the "No spam" rule, "diameter is not signed" should be the correct answer in less than 20% of all quests. Do you think this is realistic?

Also, could you please post a photo of those signs, as the quest needs to be adapted to the particular sign in the country.

**Comment by angoca** [comment]
4'' diameter hydrants.

![20230705_135912](https://github.com/streetcomplete/StreetComplete/assets/294317/c8417c5f-10a9-4a41-821f-05286b14d42b)
![20230705_141143](https://github.com/streetcomplete/StreetComplete/assets/294317/564e9aa5-0b51-4cdd-b63f-02b3bea861f5)

**Comment by angoca** [comment]
6 inches hydrants
![20230621_133819](https://github.com/streetcomplete/StreetComplete/assets/294317/17b643f5-de21-4909-a104-a7063e71d6fc)
![20230621_141131](https://github.com/streetcomplete/StreetComplete/assets/294317/442a23d6-c620-4b33-8e28-0994c88878c3)

**Comment by westnordost** [comment]
Interesting, I thought basically everyone used metric units except the US.

Anyway, there are several numbers on the fire hydrant and also apparently no sign where the diameter could always be excepted to be at the same position. So, there is the possibility that a layman (StreetComplete users are assumed to be laymen) inputs a wrong number. Hence, it is not eligible as a quest in Colombia.

FYI this is how a hydrant sign looks like in the UK and how it is displayed in the app:

![image](https://github.com/streetcomplete/StreetComplete/assets/4661658/470ec374-40d8-4d07-ba9c-188c82e4f96b)
