### ISSUE TITLE
Enable `AddFuelSelfService` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5127]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddFuelSelfService

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> So there are many fuel stations that do not allow self service? Otherwise, this would be spam again.

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> In Colombia, self-service for fuel is not popular, so it is very important to identify the self-service stations with AddFuelSelfService.

---

To enable this quest and not violate the "No spam" rule, neither "yes" nor "no" should be the correct answer in more than 90% of all quests. Do you think this is realistic?

Also please note that self-service in the StreetComplete sense means that you have to use the pump yourself, not about being able to pay at the pump directly.

**Comment by westnordost** [comment]
No feedback, closing
