### ISSUE TITLE
Enable `AddSummitCross` in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5128]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddSummitCross

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> In many mountains, the peak is marked with AddSummitCross, as we have Christian roots, so there are present everywhere, but I don't know how many peaks have a cross on them. And a quest like that at the peak won't be spam, as it could be the only available one in the area.

by @mnalis in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1623844508:

> That reasoning I agree with; for that particular quest; it there are even just a few crosses in peaks in whole country (which should certainly be possible to find out!), it should be enabled.

**Comment by mnalis** [comment]
As summit crosses [seem to exist](https://duckduckgo.com/?q=summit+cross+in+colombia&t=ftsa&iax=images&ia=images) in Colombia and are tagged [at least in some places](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCJzdW1taXQ6Y3Jvc3MiPSogxLogY29sb21iaWHFiMKdCiovCltvdcWRanNvbl1bdGltZcWtxZEyNV07Ci8vIGZldMWCIMSwxYAgxYjCnMWexaDFosWkxabEm8SrxL_FgcWDxLoKe3vEkG_FnmRlQXLFgMWSxZ_FocWjYX19LT4uxpVyxYLGocWAxb_GgcSPxJTEnXIgxqLFjGx0cwooCiAgxrRxdcSSxJrEo3J0xoNvcjrGi8WJxYvFjcWPxZHFk8WVxZfFmcWmx4Egbm_Gn1vHksWOxZDFksWUxZYiXSjGiWHGrcWAxq9oxrFhKcW_x4J3YXnHoMWMx6LHlcelxZfHqMeqx6zGlsewx7LHm8aibMSUacWyx7jHk8ejx5bHpse-xqLHq8auxrDIkMiDyIPGtHDEt27Hi8a6dca8xr7FusSYx555xb8-xb_IoHNrZcS9cXQ7&c=ArX5lNSdxM), and mountain peaks are far away, so not likely to be spammy (even for avid hikers), I think this quest should be enabled for Colombia
