### ISSUE TITLE
Enable tactile paving quests in Colombia

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5129]
Extracted from #5078, by @angoca:

> in Colombia, the following quests should be enabled because we have those kinds of features:
> * AddTactilePavingBusStop
> * AddTactilePavingCrosswalk

by @FloEdelmann in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1594230315:

> How common is tactile paving in Colombia?

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1605199580:

> [Photo 1]
> [Photo 2]
> [Photo 3]

by @angoca in https://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1622915405:

> Also, some sidewalks and bus stops have tactile paving, but I don't know the proportion of sidewalks with and without tactile paving.

---

To enable this quest and not violate the "No spam" rule, neither "yes" nor "no" should be the correct answer in more than 90% of all quests. Do you think this is realistic?

**Comment by westnordost** [comment]
No feedback, closing
