### ISSUE TITLE
Platform vs stop quest (name/shelter/waste basket) in tram/bus stops

### ISSUE THREAD

**Issue by AgaFra** [streetcomplete/StreetComplete#5132]
It's very tricky to respond in the correct way in quests as "Is there a shelter at this stop? Train Platform" or "What's the name of this stop? Train platform" for trams or buses. The question suggests that I should write the name of the stop. But the quest is about platform... All is clear in terms of rail, or bigger interchange. But I’m lost when there is only one stop and one platform - I don't know if I should write name under stop quest or under platform quest. And there is no option "platform doesn't have separate name". In case of shelter (or waste basket) - are those quests relate for this same object? I believe such situation happens when stop is a node and platform as [public_transport]=[platform].

**Comment by mnalis** [comment]
> But I’m lost when there is only one stop and one platform - I don't know if I should write name under stop quest or under platform quest

Now _I_ am confused: you have a platform for waiting/boarding the train/bus which has **one** name on its sign, but a stop position for same train/bus at that location has **different** name? Can you give picture/example how that looks like? It makes no sense to me that it should exist; over here a bus/train stop is just a point alongside waiting platform where vehicle will stop - it is basically just a "part of/point alongside" the passenger platform  

> And there is no option "platform doesn't have separate name". In case of shelter (or waste basket) - are those quests relate for this same object?

About being asked for duplicate information, that is likely because data is duplicate in OSM already (so you should also enter the same information twice), see related discussions:
- https://github.com/streetcomplete/StreetComplete/issues/4690#issuecomment-1356919286
- https://github.com/streetcomplete/StreetComplete/issues/4341#issuecomment-1358927732 and below

**Comment by AgaFra** [comment]
Thank you for the references to the discussions. Indeed, my problem is caused by double tagging. It asked me one time for a node, and another time for a way.

> > But I’m lost when there is only one stop and one platform - I don't know if I should write name under stop quest or under platform quest
> 
> Now _I_ am confused: you have a platform for waiting/boarding the train/bus which has **one** name on its sign, but a stop position for same train/bus at that location has **different** name? Can you give picture/example how that looks like? It makes no sense to me that it should exist; over here a bus/train stop is just a point alongside waiting platform where vehicle will stop - it is basically just a "part of/point alongside" the passenger platform (or I misunderstood that part)

Platform doesn't have a name at all, only a bus stop has. So I didn't know if I should put the name under the node or way quest.  
Which is this same problem as: [(https://github.com/streetcomplete/StreetComplete/issues/4341#issuecomment-1358385314)]

As far I can see, the conclusion is to keep asking this same question twice. But should I choose "There is no name sign..." option then, or maybe write once again the name of the stop? Ideally I would like to hide the platform quests (with ways) but still keep the stops quest (with nodes) - so in that way I will be not making more mess.

**Comment by westnordost** [comment]
Can you link to the point where this was asked? I have an issue with understanding the issue, maybe looking at how it is tagged there helps.

**Comment by AgaFra** [comment]
It's exactly this same problem as you pointed here: [https://github.com/streetcomplete/StreetComplete/issues/4690#issuecomment-1356919286](https://github.com/streetcomplete/StreetComplete/issues/4690#issuecomment-1356919286)

You can also take a look here on my example on the bus stop here: 
- node: [https://www.openstreetmap.org/node/6127066461](https://www.openstreetmap.org/node/6127066461)
- way:  [https://www.openstreetmap.org/way/1094230991#map=19/51.11275/17.05965](https://www.openstreetmap.org/way/1094230991#map=19/51.11275/17.05965)
SC is asking me for the platform name. 
![2023-07-25-103519](https://github.com/streetcomplete/StreetComplete/assets/79878967/38c3bef7-938b-40ca-aa09-1307feea2ac1)

As a first instinct, I wanted to write the name of the bus stop - as the icon for platform is this same as for the stop. But then we will have two names for this same stop - one for the node which already exists and one for the way. Then I wanted to choose "platform doesn't have separate name" but there is only an option "There is no name sign..." only which is not exactly this same. And in the end I wanted to hide quests with platforms as imo there is no right answer. But then I will hide the quests about bus stop names as well.

**Comment by westnordost** [comment]
> It's exactly this same problem as you pointed here: https://github.com/streetcomplete/StreetComplete/issues/4690#issuecomment-1356919286

Ah, then I do not need to re-understand the issue and can close this as duplicate :-)
Sooner or later, someone will notice (like you did) and come around and delete the duplicated information. In the meantime, I guess it doesn't really matter (for overall data quality of the OSM) if duplicated information is added to a duplicated POI. 

If you do not want to deal with it, you can also choose "Other answers..." -> "Can't say" -> and when asked whether to leave a not, answer "no, just hide".
