### ISSUE TITLE
Loop  AddTracktype <-> AddRoadSurface

### ISSUE THREAD

**Issue by qugebert** [streetcomplete/StreetComplete#5133]
Lately I've noticed a continuous loop between the quest types "AddRoadSurface" and "AddTracktype".

It seems to occur whenever a trail is specified as "highway"="track" and "surface"=compact and "tracktype"="grade1"

![output](https://github.com/streetcomplete/StreetComplete/assets/44033795/34e13d5a-6bb1-4137-a445-8b155d4562db)

You can see at the increasing count (top left), that it's a loop

**How to Reproduce**

Here are two examples:
https://www.openstreetmap.org/way/4397949/history
https://www.openstreetmap.org/way/561295124/history

You can see the loop in the history of the stated ways, or if you go to one of these ways in streetcomplete, you will see, that the questions are still asked.
I guess it's the combination "highway" = "track", "surface"="compacted", "tracktype"="grade1" which causes this bug.

If you look at the history of these ways, it seems like the Task "Specify road surfaces" deletes the tag "tracktype", this triggers the Task "Specify tracktypes" but i have no idea why the task "Specify road surfaces" is triggered again 

**Expected Behavior**

Once both questions have been answered, they should not be asked again

**Versions affected**

- StreetComplete 53.2
- StreetComplete 52.1

**Comment by westnordost** [comment]
Naja, das kommt daher dass du jeweils widersprüchliche Werte auswählst. Eine Straße mit verdichtetem Untergrund ist nicht befestigt. "Befestigt" bedeutet soetwas wie Asphalt, Beton, Steinpflaster usw.

**Comment by qugebert** [comment]
Danke für die schnelle Reaktion :)

Ich sehe da keinen Widerspruch in sich.
Im Wiki https://wiki.openstreetmap.org/wiki/DE:Tag:surface%3Dcompacted heisst es beispielsweise auch für compacted:
"Eine **befestigte** und verdichtete Deckschicht für Straßen und Wege"

Tatsächlich sehe ich aber eben auch im Wiki, dass Grade1 nur [Asphalt, Beton oder Pflastersteine] beinhaltet. 
Die allerwenigsten User schauen aber zunächst ins Wiki (habe ich ja auch nicht), um die genauen Kriterien nachzusehen und für viele ist ein verdichteter Weg eben direkt auch "befestigt". 
Selbst Behörden scheinen "befestigt" nicht als "Asphalt, Beton oder Pflastersteine" zu definieren. Wir haben hier im angrenzenden Forst (ehem. Truppenübungsplatz) überall Schilder "Betretungsverbot ausserhalb der **befestigten** Wege" und die Wege, welcher in der dazugehörigen Allgemeinverfügung als erlaubt aufgelistet sind, sind alle nur verdichtet.

Kurzum, dann ist die Bezeichnung "Befestigt" zumindest nicht so gewählt, dass es zu keinen Misverständnissen führen kann (QuestGuidelines: "the user interface must leave no space for misunderstandings") und auch das Foto ist nicht allzu eindeutig.

Vorschlag: Wir packen in den TrackType-Quest einen ähnlichen Warnhinweis, der darauf hinweist, dass "Befestigt" nur dann zu wählen ist, wenn eine der drei genannten Oberflächen zutrifft. Ich kann mich gerne auch selbst daran versuchen, den Hinweis da hinein zu bekommen, wenn du keine Einwände hast.

**Comment by westnordost** [comment]
Zum Vorschlag, ich denke nicht dass ein weiterer Warnhinweis Sinn macht. Der wird bloß auch weggeklickt. Dialoge werden in der Regel weggeklickt, so ist es halt.

Aber du hast Recht: wenn keine klare Definition besteht darüber welche Oberflächen unter "befestigt" fallen oder diese nicht mit der Definition von `paved` / `unpaved` übereinstimmt, dann ist dieses Wort möglicherweise nicht als Übersetzung geeignet.

_Befestigt_ / _unbefestigt_ ist (derzeit) die Übersetzung vom englischen _paved_ / _unpaved_. 

Ich denke, die Übersetzung sollte einfach geändert werden. Mögliche Kandidaten:

- _gepflastert_ / _ungepflastert_ - wortgetreue Übersetzung, auch genutzt auf [DE:Tag:surface=paved](https://wiki.openstreetmap.org/wiki/DE:Tag:surface%3Dpaved). Aber aus meiner Sicht passt das eigentlich nicht, meinem Wortverständnis nach ist eine asphaltierte Straße nicht "gepflastert". Oder?

- _versiegelt_ / _unversiegelt_ - möglicherweise passender, "unversiegelt" hört sich aber komisch an.

**Comment by westnordost** [comment]
Okay, zwei drittel finden dass befestigt / unbefestigt die beste Übersetzung ist, obwohl auch im Forum ein paar Leute sind, die meinen, sie hätten (bisher) Straßen mit wasserverdichteten Oberflächen zu befestigten Straßen gezählt.

Die anderen Optionen, _versiegelt_ und _gepflastert_ können auch anders verstanden werden, zum einen würden viele eine asphaltierte Straße nicht als _gepflastert_ ansehen, zum anderen würden einige wiederum gepflasterte Oberflächen nicht als (komplett) versiegelt ansehen.

Insofern ist und bleibt "befestigt" die beste Übersetzung. Ich hatte kurz darüber nachgedacht, dass man den Text in "befestigt / versiegelt" ändern könnte, aber das könnte wiederum so ausgelegt werden, dass die Option auszuwählen ist wenn etwas **entweder** befestigt oder versiegelt ist. Dies würde also das Missverständnis hier nicht verbessern.

Daher werde ich nichts an der aktuellen Übersetzung ändern.

**Comment by torhovland** [comment]
@westnordost I am not sure if this is exactly the same issue, but I noticed a similar loop today. There was a track that didn't have any other tags apart from `highway=track`. StreetComplete first asked me to specify the surface, then the tracktype, then the surface again, and I think, then the tracktype again (at which point I decided to hide the quest). See the following history:

![image](https://github.com/streetcomplete/StreetComplete/assets/55164/eb74530e-1c0e-4534-909b-ff70fd30ed75)

**Comment by matkoniecz** [comment]
Can you attach photo of `tractype=grade2 surface=dirt` track? As far as I can see these answers are contradictory.

**Comment by torhovland** [comment]
But you asked about grade 2. Well, if you imagine the grade 3 photo, but with hard dirt instead of grass in the middle of the track.

**Comment by westnordost** [comment]
Sounds like grade 3 then.

**Comment by torhovland** [comment]
Wait, so dirt by definition is always a soft material? There is no such thing as "compacted dirt"?

That's fine, then, but I still think this loop is unfortunate and could probably have been avoided.

**Comment by westnordost** [comment]
Anyway, @matkoniecz , didn't look up what you committed recently, but couldn't StreetComplete just keep out of the whole discussion by only detecting conflict between grade1 and paved surface?

**Comment by torhovland** [comment]
@matkoniecz I can see that you are treating `ground` specially (allowing it with `tracktype=grade2`) after the discussion in #4863. But I think that if you do that, you should similarly allow `earth`, `dirt`, `soil`, `salt`, and `ice`, because they can all be considered solid surfaces.

In other words, since this doesn't include `ground`, it shouldn't include all of the other ones here either:

```
val SOFT_SURFACES = setOf(
    "earth", "dirt", "soil", "grass", "sand", "mud", "ice", "salt", "snow", "woodchips"
)
```

**Comment by matkoniecz** [comment]
> Wait, so dirt by definition is always a soft material? There is no such thing as "compacted dirt"?

See description of surface in StreetComplete and in https://wiki.openstreetmap.org/wiki/Key:tracktype#Values

**Comment by matkoniecz** [comment]
> but couldn't StreetComplete just keep out of the whole discussion by only detecting conflict between grade1 and paved surface?

that would leave us with some wrong `surface` and `tracktype`

I guess that it could be made more smarter and show some extra info when encountering mismatch?

**Comment by westnordost** [comment]
Ugh, not more complexity here please. You see where it leads.

**Comment by mnalis** [comment]
> Ugh, not more complexity here please. You see where it leads.

I think complexity stems from mismatched tags, not StreetComplete handling (which is detected problems and avoiding corrupt data -- any such safety checks will by definition case more user confusion but less incorrect data then no checks at all, of course)

But I agree with @matkoniecz suggestion of trying to make better UX than _"quest loop"_ in such case of tag conflict to be a good idea. Possible alternatives to "quest loop":

- when mismatch is detected, upon removing old conflicting tag, display a popup saying why it was removed. While that might add tiny bit of code complexity, it should avoid much of _"huh?"_ user moments that current "quest loop" does, so would be better choice IMHO.
- alternatively, when mismatch is detected, simply refuse to accept the answer to add a new tag, instead displaying a message explaining to the user that they should leave a note with picture instead due to conflicting data.
