### ISSUE TITLE
Quest: What is/was mined here?

### ISSUE THREAD

**Issue by prx-lmo** [streetcomplete/StreetComplete#5134]
### General
Affected tag(s) to be modified/added: [resource](https://wiki.openstreetmap.org/wiki/Key:resource)
Question asked: **What is mined here?** if _disused=yes_ then **What was mined here?**

There are serveral old quarrys in the region where I live, like every town has one.
It would be nice to tag this data, the linked wiki entry has a complete list with pictures.
But this list should, for simplicity, be reduced to only those which not mined in shafts.
For eample: 
agregate, basalt, clay, coal, dimension stone, lime stone, salt, granite and kaolinite.
Maybe also to quarry-able ores like ilmenite, iron, gypsum, oilshale, asbestos, bentonite, pot ash and silica
But those may be over-the-top.
The user could (or should) leave a message if it's more complicated than that.

The data is useful for geologists and mineralists.
This question shouldn't be active by default

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
landuse=quarry && (resource unset || resource=stone)

**Comment by westnordost** [comment]
This does not satisfy the quest guidelines.

- 🐿️ This is often not surveyable on the ground, as it would require signs (for tourism purposes?) to be set up. Any other disused mine that is now not a tourist attraction or whatever will have no signs at all, just do not enter signs and a locked entrance. For in-use mines - they are not accessible for people not working there.

- 🕓 There is a very large number of minerals that could have been mined in a mine. To list these all in the quest, ...and that for the few mines that may have information posted.... sorry. Just no.

If you are interested in this topic and would like to map this, I think you'll find information about what was mined where also on the internet: I.e. those disused mines that are not just closed off but a point of interest for hikers etc. are likely to have either some mention in the wikipedia, some blog or some photos posted somewhere.
