### ISSUE TITLE
grid does not disappear in some areas

### ISSUE THREAD

**Issue by MakiWolf** [streetcomplete/StreetComplete#5137]
**How to Reproduce**

Happens in this area: https://www.openstreetmap.org/#map=17/46.43707/11.25036
![grafik](https://github.com/streetcomplete/StreetComplete/assets/73300633/c8faff4d-146a-4769-a22b-6c67b695bf6f)

**Expected Behavior**

Grid should disappear

**Versions affected**

53.2 from play store and latest build from source code (12.07.23)

**Comment by mnalis** [comment]
- I've seen that too; related: https://github.com/streetcomplete/StreetComplete/issues/5068#issuecomment-1589390187

**Comment by westnordost** [comment]
If you tab out and then tab in again, is the grid gone, then?

**Comment by MakiWolf** [comment]
I have made a screen recording now.
I did not notice this strange behavior in an other map area on the same device.
https://github.com/streetcomplete/StreetComplete/assets/73300633/5762bc15-8356-4a61-ad03-aecf7ae60b24

**Comment by westnordost** [comment]
Okay, but would you answer my question?

**Comment by mnalis** [comment]
> If you tab out and then tab in again, is the grid gone, then?

By _"tab out/tab in"_ you mean switch to another app and then switch back to StreetComplete?

**Comment by westnordost** [comment]
Yes.

**Comment by MakiWolf** [comment]
Also happens when switching to another app or closing and reopening the app and also in an fresh install on Android Studio Emulator (tested with Pixel 4 API 29). Also happens on other cities like in Zirl (Austria) on the same longitude. https://www.openstreetmap.org/#map=19/47.26540/11.25033

![grafik](https://github.com/streetcomplete/StreetComplete/assets/73300633/7af9b934-c1ec-47c4-9335-f4bf25c48c15)

**Comment by HolgerJeromin** [comment]
I had this too when the feature was new.
Manually "search for quest here" fixed it.

**Comment by Helium314** [comment]
@MakiWolf interestingly when I downloaded this area, I initially got the bug on the right half of the displayed area. After turning the screen off and on again, it was the left half (also after restarting SC).

**Comment by riQQ** [comment]
Had the same issue with v53.3, after turning the screen off and back on with StreetComplete in the foreground the grid went away / it fixed itself.

**Comment by westnordost** [comment]
This is very likely a problem in tangram-es, though, and hence, unfixable, since the former is not maintained anymore.

What we can do is to mitigate the issue. I had the impression that it more often occurs on lower zoom levels, so actually the grid is only turned on when zoomed in further already.

**Comment by MakiWolf** [comment]
> This is very likely a problem in tangram-es, though, and hence, unfixable, since the former is not maintained anymore.

@westnordost Maybe streetcomplete should make a fork of it, if it is really not maintained anymore? That open Pullrequests could be merged. Because issues will become more on never android versions. Is this the repositority? https://github.com/tangrams/tangram-es

**Comment by westnordost** [comment]
Well, *someone* could make a fork of it. I certainly won't because I am not experienced in C++ and thus couldn't properly review those PRs.
