### ISSUE TITLE
Map background outdated 

### ISSUE THREAD

**Issue by AnneWielis** [streetcomplete/StreetComplete#5139]
For recently updated objects, SC creates quests but the object isn't visible. Not sure if that is a bug, but it is annoying. Cleared cache, didn't help.

 SC53.1
![Screenshot_20230713-182747_](https://github.com/streetcomplete/StreetComplete/assets/41674213/88f3b32c-bae6-42f3-9835-f2696412e41e)

**Comment by westnordost** [comment]
We have no influence over when the background tiles are updated. You'll have to wait a few days or so.

**Comment by riQQ** [comment]
See #2479 for more details.
