### ISSUE TITLE
Cannot select street in "Which street is this on?"

### ISSUE THREAD

**Issue by Xcodo** [streetcomplete/StreetComplete#5140]
**How to Reproduce**

Try to answer the "Which street is this on?" quest on the building at `55.90652° N, 5.23320° W`. Tapping the road outside (the B8000/Shore Road) has no effect.
![Screenshot_20230714_120034_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/6715247/abe91287-2076-4eaa-85af-62bb0f2f592f)

**Expected Behavior**

The road can be selected and the quest completed.

**Versions affected**

v53.2 on Android 13, Samsung Galaxy S21 Ultra 5G

**Comment by FloEdelmann** [comment]
The road (https://osm.org/way/461635959) has only a `ref`, not a `name`. Not sure if `addr:street` should still be filled with "B8000" then.

**Comment by Xcodo** [comment]
I will fix this paricular road by adding the street name tags, thanks.

However I think that the quest should only be activated if there is something eligible nearby, otherwise it's quite confusing.

**Comment by westnordost** [comment]
That would be very difficult. The road a particular house belongs to can be very far away from the public road. (Think US country-side houses on huge properties with very long driveways). So not only would that zone in which to look for streets with names be incredibly large, it would be also (for that reason) be very slow to find.

Keep in mind that the "tap on road on map" is just a convenience function. You can still just input the name in the input field.
