### ISSUE TITLE
"Are credit or debit cards accepted here" is limited in possibilities

### ISSUE THREAD

**Issue by paultjevdh** [streetcomplete/StreetComplete#5142]
**Use case**
The quest proposes just no/both/credit/debit cards. 
This is a similar problem as #5136 : the options are too few and mutually exclusive. 
When I know from experience that a shop accepts debit cards, I would like to enter that, not excluding credit cards. I simply don't know that and I don't care to have to figure that out either. So currently my choice is not to answer this quest at all.

**Proposed Solution**
As in #5136 the ideal solution would be to have checkboxes in the GUI, but that seems not to be possible right now. The alternative is the solution provided in #5136: same behaviour as the recycling quest, but this requires images. To me it seems debit and credit cards  are difficult to distinguish.

**Comment by mnalis** [comment]
> When I know from experience that a shop accepts debit cards, I would like to enter that, not excluding credit cards

There is no direct way to do that with StreetComplete currently, you are correct. 
At best, you can select `Other answers` / `Can't say` / `Leave note` to indicate what you know, but that requires follow-up map editing (by you or some other mapper).

> As in https://github.com/streetcomplete/StreetComplete/issues/5136 the ideal solution would be to have checkboxes in the GUI, but that seems not to be possible right now

Note that even if regular checkboxes were an option, they would still not work for this case, as they give only 2 answers (`yes` and `no`). So even if they were existing, checking `debit` but not checking `credit` would be tagged the same as when you now answer `Only debit cards`  (i.e. `payment:debit_cards=yes` + `payment:credit_cards=no`), which is not what you want.

What one would need is tri-state solution (i.e. `yes`, `no` and `unknown`), like e.g. JOSM supports; but that in itself might be getting UI too complex for target group of StreetComplete users. (which are not required to be tech savvy at all)

> The alternative is the solution provided in https://github.com/streetcomplete/StreetComplete/issues/5136: same behaviour as the recycling quest, but this requires images

You mean something like this idea: https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785 ?

> To me it seems debit and credit cards are difficult to distinguish.

I guess it is country-dependent; in some of them the accepted cards are signed on the doors, so it is easier to answer the question. If it is too hard in your case, it is probably better to disable the quest, as leaving notes all the time will likely get boring pretty fast. There is plenty of other quests available, and it is most important that the mapper (you!) is having fun mapping!

**Comment by westnordost** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-1609338131

**Comment by paultjevdh** [comment]
You're completely right, it is much more complicated than I thought. It appears I posted a duplicate. Thanks for your reply though.
