### ISSUE TITLE
Does this bench have an inscription?

### ISSUE THREAD

**Issue by kristbaum** [streetcomplete/StreetComplete#5143]
### General
Would maybe help improve the data on [openbenches.org](https://openbenches.org)!
Affected tag(s) to be modified/added: [inscription](https://wiki.openstreetmap.org/wiki/Key:inscription)
Question asked: **Does this bench have an inscription?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Benches

**Metadata needed:** None

**Proposed UI:** No or the text of the inscription

**Comment by matkoniecz** [comment]
Fails

> Not an overwhelming percentage of quests have the same answer (No spam)

vast majority of benches have no inscription

**Comment by Helium314** [comment]
It might be a regional thing, but in more rural areas and near hiking trails I visit, many / most benches have inscriptions like "_sponsored by &lt;local group/company&gt;_" (though I don't see a useful purpose for tagging this)

**Comment by mnalis** [comment]
Also it does not say what should be tagged when there is **no** inscription, failing this requirement for _Quests_:
>  :thinking: Any answer the user can give must have an equivalent tagging

To @kristbaum I'd recommend some solution which is not quest-driven but user-action-driving for such tasks: [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) in particular seems like a good fit that is also easy to use - as a user can click on a bench and easily add an inscription **if they want to** (and obviously not click on it unless they want to add something, thus avoiding  _":zzz: No spam"_ problem)

**Comment by kristbaum** [comment]
> Fails
> 
> > Not an overwhelming percentage of quests have the same answer (No spam)
> 
> vast majority of benches have no inscription

I'm also not sure if that's true, I think it would be at least over 50% in my area, but apart of Openbenches.org there isn't any real data on it out there. And some of the answers would of course be "sponsored by local group", but that does seem like a relevant detail to me.
And if it is to "spam-y" it maybe still a fun quest if deactivated by default, until we know in which areas/countries most benches actually have an inscription.


> Also it does not say what should be tagged when there is **no** inscription, failing this requirement for _Quests_:
> 
> > thinking Any answer the user can give must have an equivalent tagging

That's a problem of course, would it be sensible to suggest a modification of the tag to have a "no" feature? There are at [least 100](https://taginfo.openstreetmap.org/tags/inscription=no#overview)tags with this already.

**Comment by matkoniecz** [comment]
Maybe in some rural areas benches are rare and often have inscriptions - but in which countries big cities have benches still mostly with inscriptions?

**Comment by mnalis** [comment]
> That's a problem of course, would it be sensible to suggest a modification of the tag to have a "no" feature? There are at [least 100](https://taginfo.openstreetmap.org/tags/inscription=no#overview) tags with this already.

Probably not a good idea, as it would introduce special value, which would mean the tag cannot be used as it was used previously, so it need a change in all data consumers of it (also as an additional smaller problem, it would then become impossible to tag literal text "no"). 
It might be preferable to find community consensus on inventing new tag like `inscription:signed=no` (functioning like e.g. [opening_hours:signed=no](https://wiki.openstreetmap.org/wiki/Tag:opening_hours:signed%3Dno)) but I can forsee significant amount people disagreeing there too (_"if there is no inscription, then you should simply not tag it, doh!'_) 

But before you rush to propose that - as noted by others; even if that particular problem was solved, it would _still_ probably not be a good candidate for StreetComplete quest.
