### ISSUE TITLE
Departure/arrivals board

### ISSUE THREAD

**Issue by JaffaKetchup** [streetcomplete/StreetComplete#5149]
### General
Affected tag(s) to be modified/added: [Departures/arrivals board](https://wiki.openstreetmap.org/wiki/Key:departures_board) and potentially [Passenger information display](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display)
Question asked: **Is there a departure board at this stop?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

- No
- Timetable
- Delay (?)
- Realtime

As taken from <https://wiki.openstreetmap.org/wiki/Key:departures_board>. As also mentioned there, perhaps it is worth automatically adding the [Passenger information display](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display) tag based on the answer: 'yes' for realtime, 'no' for all others.

**Proposed UI:**

I'm thinking something towards the image grid selection instead of pure text, as it may not immediately be clear what 'delay' means.

**Comment by mnalis** [comment]
see also:
- https://github.com/streetcomplete/StreetComplete/issues/4955
- https://github.com/streetcomplete/StreetComplete/issues/2263
- https://github.com/streetcomplete/StreetComplete/issues/1974
- https://github.com/streetcomplete/StreetComplete/issues/3553

**Comment by JaffaKetchup** [comment]
Ah, I searched for "departure board" before making this issue, but I couldn't find anything!
If this needs to be closed for the same reasons as the others, I guess that's fine - although I couldn't really figure out why they were closed. If the two separate tags are the issue, at least this way they both get answered in one shot.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/1974#issuecomment-661904019

**Comment by JaffaKetchup** [comment]
If the last change to that discussion was in 2022, is there really an issue? We can always future-proof somewhat by adding the proposed replacements for 'delay' as well.

**Comment by westnordost** [comment]
The discussion to clear up which tag(s) to use is not to be held here in the issue tracker though, so it is not relevant whether in this issue tracker the last post about it was one year ago. As far as I remember the linked tickets (thanks @mnalis), it is blocked until such time as a tagging recommendation emerges from discussions/proposal from the OSM community (forum, wiki, ,...).

**Comment by timothywashere** [comment]
> If the last change to that discussion was in 2022, is there really an issue? We can always future-proof somewhat by adding the proposed replacements for 'delay' as well.

It seems to me the tag delay is valid and no-one appears to be trying to replace it. The "confusion" seems to be the result of two people who have edited the wiki 5 years apart.
I use the tags on my P4R mission, which you can duplicate for your own home town if you wish
https://pic4review.pavie.info/#/mission/2208/summary

**Comment by RedAuburn** [comment]
`departures_board` has 251,700 uses.
`passenger_information_display` has 92,866 uses.

Given that there are 2.7x more `departures_board`, maybe adding this quest can be reconsidered?

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/1974#issuecomment-661904019 and https://github.com/streetcomplete/StreetComplete/issues/3553#issuecomment-984392821

Is it still applicable? If yes and it is stuck, feel free to bring it to tagging mailing list or https://community.openstreetmap.org/ to reach some conclusion.

(personally I consider this info as not really worth tagging as use of such info is quite marginal - this displays are useful (though not sure is it worth of cost placing them) but it is not like people will go to other tram or bus stop just because they have such departure/arrival board)

If you are interested why: because this avoids problem of people later creating issues and complaining that we use bad tag and should use A, not B. This should be clarified before SC starts using given tags.
