### ISSUE TITLE
Add a better explanation to team mode

### ISSUE THREAD

**Issue by mgorfer** [streetcomplete/StreetComplete#5154]
I was confused about team mode for a long time and looked around the internet to find out what it actually does. 
If it somehow connects two phones to choose how the quests are distributed over different regions.
It seems, it just hides 50% of the quests for each person if the feature is activated for two persons.
Maybe that was just me overthinking things, but I would appreciate a bit more information about that feature shown in the app.

**Comment by arrival-spring** [comment]
Maybe you could add to the description something like "then you will all see different quests."

That is implied by "split up quests", but maybe not explicit enough.

**Comment by westnordost** [comment]
no feedback

**Comment by Cwpute** [comment]
I had the same experience, and the suggestion from @arrival-spring would have actually helped !
I was worried teams would overwrite each other's contributions and only try to fill-in the most useful info :) but reading this discussion i am relieved :)
