### ISSUE TITLE
Center the recent answers when asking for amounts of floors of a building

### ISSUE THREAD

**Issue by jmizv** [streetcomplete/StreetComplete#5159]
**Use case**

See the screenshot. I've recently answered like >200 questions like that with the same answer: 1 and 0 roof floors. That way other recent answers disappeared and some space appeared. I think it would be better for the ergonomics to have these recent answers centered instead of aligning them to the left.

![grafik](https://github.com/streetcomplete/StreetComplete/assets/37914724/bab1689b-0fe6-4225-bea3-5b6e0a5a1c54)

**Proposed Solution**

I would suggest to center these options for a better ergonomics, i.e. as a right handed person my thumb could reach the most left option better when there are little options at all. This is especially helpful for larger smart phones.

Maybe this applies to other quests, too. But maybe there is another option or there are other constraints that would prohibit my suggestion?

**Comment by westnordost** [comment]
I understand where you are coming from, but this change would be inconsistent with the other forms: All these "apply last selection" buttons in other forms are left-aligned. To have this right-align, we'd need to check if this can be done for all forms in which such a button is shown. Not saying that it cannot be done, but someone has to look into all the form and see if it makes sense (i.e. there is not already a button on the right) for all.

**Comment by jmizv** [comment]
Thanks for the explanations. I'm fine with putting this to the backlog as it is only a nice-to-have.

**Comment by mnalis** [comment]
Another (ever better usability, but much more work) option would be to have a **preference for left/right handed persons**, and have forms tailored for each (probably not that hard as it looks on first sight, as most forms are generic enough so they don't need changes) . 

For some things it bothered me enough that in my fork I've hardcoded some right-handed things like that for myself (for example, I've moved that icon for taking pictures when leaving note from far left to far right instead, as I'm big notes user and often use phone one-handed).

---

Just moving things to the center (at least in this particular case) probably won't help much. When you fill in few more buildings with different heights, the list will fill up and look like this:

![small_Screenshot_20230726_195808_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/d59fa298-b0dc-456f-84fe-53db3c94955d)

So even if it were centered, it would help almost nothing, as positions would change very little, so far left icon (which you would need to reach most often) would be almost equally hard to reach as it is now :cry:  

Workaround might be Android (at least on EMUI) built-in one-handed mode, which resizes the screen to about 2/3 of original size on bigger phones, thus making everything reachable by thumb (at the expense of making screen smaller and harder to hit precisely; but also fixing all other issues like keyboard etc). 

(Same workaround thing may be accomplished by buying the smaller phone next time so the thumb can reach all of its area). Or one can perhaps train to become left-hand proficient instead, that sounds like it would solve many problems.  :smile:

**Comment by westnordost** [comment]
> Same workaround thing may be accomplished by buying the smaller phone next time so the thumb can reach all of its area

They do not exist anymore, though...

**Comment by mnalis** [comment]
>  They do not exist anymore, though...

OK, I'll bite :smiley: 

There are not a great many choices for sure, but they do exist - [gsmarena search for available products < 4.7"](https://www.gsmarena.com/results.php3?fDisplayInchesMax=4.7&sAvailabilities=1,2&sFormFactors=1,2,3,4,6,10,11&sOSes=2)

For example [Blackview N6000](https://www.gsmarena.com/blackview_n6000-12432.php) is 4.3", was released just days ago with Android 13, and seems to go for ~ $160 on Aliexpress (and more than double that on Amazon, heh). I have no idea if it is any good, though. Don't know if it will be rootable. At least it seems to be rugged and IP69K water resistant...

**Comment by westnordost** [comment]
> Thanks for the explanations. I'm fine with putting this to the backlog as it is only a nice-to-have.

Well, the issue tracker **is** the backlog as far as I am concerned. But stuff in here should be actionable and the suggestion just to sort the building floors buttons right-aligned falls short of that (i.e. a PR that would do that and only that would not be accepted). Instead, all forms where such "apply last selection" buttons are placed would need to be revisited (maybe other elements need to be moved to the other side respectively) and ideally the whole thing would be coupled with a "left-handed" option in the settings. 

So, this particular feature request is rejected, but a new ticket or PR could be opened that adapts the alignment of all the buttons (ideally/optionally aligned with a "left-or-right-handed" setting).

In any case, this is somewhat low-priority for me because even the smallest *mainstream* smartphones are too big to properly operate with one hand anyway, sadly.
