### ISSUE TITLE
Complete EVSE ID of a charging station

### ISSUE THREAD

**Issue by sideeffect42** [streetcomplete/StreetComplete#5163]
### General
Affected tag(s) to be modified/added: [ref:EU:EVSE](https://wiki.openstreetmap.org/wiki/Key:ref:EU:EVSE)
Question asked: **Scan the charge point IDs of this charger?** (if it is possible to add a QR code scanner to StreetComplete) or **Which IDs does this charger have?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
       it makes charge points identifiable, possible allowing map apps to query an API if the charger is currently occupied, query charging prices, or detect duplicates should charging stations be imported into OpenStreetMap from an external source.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
      only requirement is to scan a QR code or type the code that's printed below it.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
The way I understand [amenity:charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station) this tag is only acceptable for small charging stations where only one charge point is available, so it may make sense to only show this quest on `amenity:charging_station`s which are a node, not an area.

**Metadata needed:** 
No, the codes are unique and in use all over (at least) continental Europe.

**Proposed UI:**

Ideally the UI would display the EVSE IDs already present on the charging station if the number of EVSE IDs is less than either `capacity` or the number of all `socket`s combined.

The user should then have the ability to remove incorrect EVSE IDs or add new ones either by scanning a QR code or typing the ID using the keyboard.

**Comment by HolgerJeromin** [comment]
Correct Wikipage is: https://wiki.openstreetmap.org/wiki/Key%3Aref%3AEU%3AEVSE
With 5 566 ([Taginfo](https://taginfo.openstreetmap.org/keys/ref%3AEU%3AEVSE#overview)) mostly nodes tagged with the ref.

**Comment by sideeffect42** [comment]
> Correct Wikipage is: https://wiki.openstreetmap.org/wiki/Key%3Aref%3AEU%3AEVSE

Oops, something went wrong copying the link. I corrected it in OP.

**Comment by HolgerJeromin** [comment]
> Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

Does every charger has this signed? I am not sure. I would bet that especially private charger do not.

> The way I understand amenity:charging_station this tag is only acceptable for small charging stations where only one charge point is available, so it may make sense to only show this quest on amenity:charging_stations which are a node, not an area.

This node references a big parking space with 26 sockets:
https://www.openstreetmap.org/node/8943286969

**Comment by sideeffect42** [comment]
> > Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
> 
> Does every charger has this signed? I am not sure. I would bet that especially private charger do not.

I've seen quite a few chargers already and 99% of public chargers in Europe have an EVSE ID.
The ones which don't non-"commercial" chargers, like free charging offered by tourism offices or so, however these are becoming rarer by time as many of them will probably be converted to commercial charging stations sooner or later.

Also, as you mentioned, private chargers (e.g. in hotels) don't (usually) have an EVSE ID, but these could be answered by "does not have an EVSE ID" like it is currently handled for e.g. hydrant codes; if they are mapped on OSM at all.

> > The way I understand amenity:charging_station this tag is only acceptable for small charging stations where only one charge point is available, so it may make sense to only show this quest on amenity:charging_stations which are a node, not an area.
> 
> This node references a big parking space with 26 sockets: https://www.openstreetmap.org/node/8943286969

I am not an authority on OpenStreetMap "correct tagging", but this charger looks incorrectly mapped to me. 26 charge points cannot be a single point.
This charging station probably occupies half of the parking space there, so I would say it should be mapped as an area instead.

However, if you have the patience, you could of course add all 26 EVSE IDs 😄

**Comment by HolgerJeromin** [comment]
> 26 charge points cannot be a single point.

`amenity=charging_station` != `man_made=charge_point`

Wiki:

     Use the charging station tag to map locations where energy is supplied to electric vehicles, 
     like fuel stations for combustion vehicles. [...] Add a node node at the centre of the charge 
     points belonging to the charging station location or create a way around the area area with 
     charge points and associated parking slots.

> This charging station probably occupies half of the parking space there, so I would say it should be mapped as an area instead.

https://www.mapillary.com/app/?pKey=360276185920286&focus=photo

**Comment by sideeffect42** [comment]
Maybe I am misunderstanding the wiki (why I wrote "The way I understand amenity:charging_station"), but I interpret is as follows.

> A charging station may represent one individual charge point (without others close to it) or a group of charge points at a location. Different brands/operators on the same location should be mapped separately.

A amenity:charging_station can be either one charge point (one machine with one or more sockets) or multiple charge points (multiple machines), but only under the condition that they belong to the same brand/operator/network.

> Add a node node at the centre of the charge points belonging to the charging station location or create a way around the area area with charge points and associated parking slots. Add the tag [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=charging_station to the node node or area area.

It is not entirely clear but for me it makes sense to map a charging station as a node if you have only one charge point or only a few charge points (I'd say max. 3) which maybe occupy a small portion of a parking lot.
So you would map the parking lot as an area and put a node on it to point to the parking spots dedicated for EV charging.

But if you have a whole parking lot dedicated to EV charging (like in https://www.mapillary.com/app/?pKey=360276185920286&focus=photo) I would say that the whole parking lot should be mapped as amenity:charging_station ("create a way around the area area with charge points and associated parking slots").

In this case one could map all the charge points (the poles with the sockets) as nodes on the amenity:charging_station

**Comment by HolgerJeromin** [comment]
IMO this falls under the usual osm workflow.

1. Someone starts with a school as a node as he knows roughly its location.
2. Another one knows (or is bold enough to map from aerial images) the outline as a way.
3. A third mapper knows that this sports_hall over the street is integral part of the school and expands the school yard.

In no part of the osm history this is wrong tagging.

**Comment by sideeffect42** [comment]
@HolgerJeromin I see what you mean, and agree that having a charger mapped at all is already a large benefit, so let's say it's "suboptimally" mapped.

What if an option "this charging station contains more than N [TBD] charge points" was added to StreetComplete which would open a note for somebody more experienced to survey the location and map the station in full detail?

**Comment by HolgerJeromin** [comment]
> What if an option "this charging station contains more than N [TBD] charge points" was added to StreetComplete which would open a note for somebody more experienced to survey the location and map the station in full detail?

Any QA Tool can be extended to warn about "charging nodes with such a big number for `capacity`".
But this does not belong to this app.

**Comment by mnalis** [comment]
I'm not sure about _":chipmunk: Easily answerable by any pedestrian from the outside"_. In my little part of the EU, those mostly look like this ("elen:" is most popular national provider, powered by national electricity grid company) and I don't see QR code or a EVSE ID on it:

![pxl-100719-25335426](https://github.com/streetcomplete/StreetComplete/assets/156656/0f01e4e7-c529-4296-bd81-5e2c3e479511)

I'm not a car user, so I never tried, but I guess it might show me something more if I were brave enough to give it my credit card... But that does not seem easy. 

Also, is _":construction: To be added tag is established and has a useful purpose"_ says:

>  allowing map apps to query an API if the charger is currently occupied, query charging prices, or detect duplicates should charging stations be imported into OpenStreetMap from an external source.

While duplicates would need to be detected by import tool based on lat/lon even if EVSE ID is present; I'm interested in the first part -- there is an API that you can query for any EVSE ID, and it will give you occupancy/price information? Where?

---

If the quest turns out not being a good fit for StreetComplete, you may with to consider https://github.com/Helium314/SCEE fork - you can already add raw tags in it (after you enable that functionality) as it is; but it also might be more open to accepting such a quest (as it does not have a hard requirement about all quests being easy for users).

**Comment by westnordost** [comment]
Uhh, so it sounds like 

> 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary

is not a given because the code is not necessarily available on all stations. Also, the country + operator is already tagged separately, so it would only be about the operator-wide `ref` code which does not seem to be such an important information that it warrants requiring users to (install a QR code scanner and) open the QR code scanner app every time and copy&paste the result into SC every time they need to answer this quest.

**Comment by sideeffect42** [comment]
> Uhh, so it sounds like
> 
> > 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
> 
> is not a given because the code is not necessarily available on all stations.

Uhh, every charge point in the EU which takes part in the roaming network should have such a code.
There is a relatively small percentage of charging stations which are not a part of the network and do not have such a code (like as it seems the one photographed above).
Unfortunately, I could not figure out where this charging station is located and who "elen:" is.

In any case I don't understand why some charge points not having this ID is a reason against this quest.
FWIW, the same can be said about fire hydrants in the area I live, yet there still is a fire hydrant ref quest.

It took me some time to realise that this is the case and now I can just dismiss these quests in my area.
I don't think doing the same for EV charge points is any more complicated.

> Also, the country + operator is already tagged separately, so it would only be about the operator-wide `ref` code which does not seem to be such an important information that it warrants requiring users to (install a QR code scanner and) open the QR code scanner app every time and copy&paste the result into SC every time they need to answer this quest.

This is not correct.
Yes, the ID contains the country and operator, but the ID follows a EU standard form and is not just a meaningless operator-given ID like e.g. refs of fire hydrants.
Neither do you necessarily _need_ a QR code scanner. It may make be easier to scan large amounts of EVSE IDs than typing them in, but most if not all QR codes have the decoded number printed below them.

In fact, the EVSE could even be used to fill in country and operator automatically, because both are encoded in the EVSE ID and it would solve the problem of 10 people finding 12 ways to spell the operator name :-)

In any case, I realise that EV charging infrastructure is seemingly something too complex for StreetComplete users, so I will take my feature requests to https://github.com/Helium314/SCEE as @mnalis suggested.

**Comment by matkoniecz** [comment]
> Uhh, every charge point in the EU which takes part in the roaming network should have such a code.

Well, how many are actually clearly signed with it? Or at least in a standard place or location?

If I would be asked "Which IDs does this charger have?" I would have no idea how to answer as they do not have it clearly signed.
