### ISSUE TITLE
Sometimes wrong objects are highlighted

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#5166]
Sometimes (I haven't found a pattern) when I want to answer a quest (example shown below), many objects are highlighted on the map, for now apparent reason.

**How to Reproduce**
That is the tricky question. Sometimes it happens. As you usually close bugs where quickly, please kindly tell me before if this is intend and if not what I can do to give you the right information for fixing it (e.g. additional information you might need). Then I can produce a new bug with this information.

**Expected Behavior**
Only the object the quest referes to is highlighted.

**Versions affected**
53.2
![Screenshot_20230603-091004](https://github.com/streetcomplete/StreetComplete/assets/46402758/bfda4ffa-28ea-41e1-bb57-a954bf4ff953)

**Comment by arrival-spring** [comment]
The idea is that relevant nearby data is show, so you know you are answering for the correct object.

In this case you are adding the house number so the numbers of nearby buildings is relevant to orient yourself, especially when houses are closer together.

E.g. when adding opening hours other shops are shown to orient yourself as well, especially as some shops will no longer exist, so you can know you are answering about the correct shop.

So it is intended, but I can see why it might be confusing. Perhaps would it be better if just the data were shown (name, house number etc.), and the objects not highlighted (not sure if that's possible, just a thought though)?

**Comment by hmartink** [comment]
Ok, then it is just confusing and not a bug.

**Comment by westnordost** [comment]
> So it is intended, but I can see why it might be confusing. Perhaps would it be better if just the data were shown (name, house number etc.), and the objects not highlighted (not sure if that's possible, just a thought though)?

It would be possible, but sometimes the area / path of surrounding elements is just as important as the name/icon/...

**Comment by mnalis** [comment]
- ref: https://github.com/streetcomplete/StreetComplete/issues/4578, PR https://github.com/streetcomplete/StreetComplete/pull/3480

Added FAQ ["When I click on quest, several other objects get highlighted, is that a bug?"](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#When_I_click_on_quest,_several_other_objects_get_highlighted,_is_that_a_bug?)
