### ISSUE TITLE
Allow for amenity bicycle_parking

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#5167]
**Use case**
I recently were in Kopenhagen, which is quite bike friendly and which has dedicated buildings for bicycle parking. I was not able to set this (i.e., a garage is for cars and is misleading). 

Example: https://www.openstreetmap.org/way/644865647

Right now, I have to leave a note and wait for someone else to correct this (like in the above example).

Please add the option to add bicycle parking, like it is available for cars already.

**Proposed Solution**
Please add the option to add bicycle parking, like it is available for cars already.

Unfortunately I'm not an illustrator, so I'm unable to propose a graphical solution.

**Comment by westnordost** [comment]
> Please add the option to add bicycle parking, like it is available for cars already.

> Unfortunately I'm not an illustrator, so I'm unable to propose a graphical solution.

I think there is a misunderstanding here. It is not possible to add car parking as areas. It is only possible via the street parking overlay to specify whether and how cars are parking alongside a street. This may sound similar, but the data is represented very differently.

So if your feature request is to be able to add bicycle parkings, then this could be part of #4912 as an overlay for bicycle parkings alone seems to me to be too specialized to be useful.

**Comment by mnalis** [comment]
In add to the explanation above, ["building type"](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#building_type) quest is about architectural type of a building, not about what is being used for.

See SC FAQ _["Building Type Quest - Why don't I see the right types?"](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?)_ 

---

For the specific example you have given ([way 644865647](https://www.openstreetmap.org/way/644865647)) , building type is marked as a [building=roof](https://wiki.openstreetmap.org/wiki/Tag:building%3Droof) (which is the same you would be able to select in StreetComplete for that quest). 

In **_addition_**, that way is (currently) tagged as [amenity=bicycle_parking](https://wiki.openstreetmap.org/wiki/Tag:amenity=bicycle%20parking) to indicate that inside that building is bicycle parking. But adding that information (as noted above) is **currently not possible** to do with StreetComplete (but https://github.com/streetcomplete/StreetComplete/issues/4912, when implemented, should hopefully allow for adding missing bicycle parkings too. Currently however you can only add missing shops in _"Shops overlay"_).

**Comment by hmartink** [comment]
Having no better choice, I probably tagged it roof and left a note, so amenity was added by someone else later.

But there are actually buildings made  for bicycle parking, I actually own one of these. Like garage for cars, just for bicycles. https://cervotec.de/ is one company selling them. So they do exist, like garages.

**Comment by mnalis** [comment]
>  But there are actually buildings made for bicycle parking, I actually own one of these. Like garage for cars, just for bicycles. https://cervotec.de/ is one company selling them. So they do exist, like garages.

I believe you they exist, but it does not seem that they have documented [building=*](https://wiki.openstreetmap.org/wiki/Key:building) value in OSM, so it cannot be used in StreetComplete at the moment (that quests tags `building=*` values,  and StreetComplete only uses existing tags which have community approval)

Whether those bicycle parkings (judging by the picture from https://cervotec.de/) should even be tagged as `building=*` (and thus _**potentially**_ eligible for this quest, _if_ they were popular enough) is something that should be discussed with wider community first - while I personally don't have a problem with tagging such roofed bicycle parkings as buildings (as we have even e.g. [building=greenhouse](https://wiki.openstreetmap.org/wiki/Tag:building%3Dgreenhouse)), I have a feeling quite a few OSM mappers might disagree - see e.g. [this poll](https://community.openstreetmap.org/t/are-bus-stop-shelters-buildings/101199/11).

**Comment by hmartink** [comment]
Thanks for the explanation and the background.
