### ISSUE TITLE
Icon for quests concerning `barrier=cycle_barrier` is confusing

### ISSUE THREAD

**Issue by esilja** [streetcomplete/StreetComplete#5169]
Currently, the icon for "What type of bicycle barrier is this?" and "Can this cycle barrier be opened (with or without a key)?" is a "bicycle forbidden" sign, a bicycle on a red circle with a diagonal line:
<img src="https://wiki.openstreetmap.org/w/images/2/26/StreetComplete_quest_no_bicycles.svg" width="50px">

This made me think that a local `barrier=cycle_barrier` was mistagged, as it's definitely *not* used to prevent bicycle access. However, the [wiki has to say](https://wiki.openstreetmap.org/w/index.php?title=Tag:barrier%3Dcycle_barrier&oldid=2569415):

> Cycle barriers (or pedestrian chicanes) are fence-like barriers positioned along paths, footways, cycleways or tracks which serve to either slow cycle access or prevent it entirely depending on spacing and layout. Often made of steel, and laid out in a staggered chicane layout. The intent may also be to discourage motor vehicle access to the protected way: motorcycles and mopeds specifically.
> 
> Perhaps **counterintuitively, cycle barriers are sometimes intended to permit access by cyclists to cycle routes while denying access to other vehicles.** However, not all cycles are able to pass through them[[1]](https://wiki.openstreetmap.org/w/index.php?title=Tag:barrier%3Dcycle_barrier&oldid=2569415#cite_note-1).

I think the current icon is confusing for this reason. I don't know a good alternative icon. Perhaps a single bicycle would work?

(For a different example, the "What type of traffic calming is this?" doesn't have a crossed out car either, it's a car on a speed bump instead: <img src="https://wiki.openstreetmap.org/w/images/3/36/StreetComplete_quest_car_bumpy.svg" width="15px">)

**Comment by westnordost** [comment]
The bollard quest has a similar icon, though.

**Comment by esilja** [comment]
A bollard is usually used for restricting car access though, the bicycle barriers generally seem more about slowing them down.

**Comment by westnordost** [comment]
True, but actually I'd like to leave the icon as it is. The icon's primary purpose is recognition, it is the question asked that matters.
