### ISSUE TITLE
Show `indoor=yes` (at least for clocks) in quest

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#5170]
**Use case**
I got the "Survey if places still exist" quest on this [indoor clock](https://commons.wikimedia.org/wiki/File:Hamm_station_hall.jpeg):
https://www.openstreetmap.org/node/8648925337

I was really happy that I got the [outside front building clock](https://commons.wikimedia.org/wiki/File:Bahnhof_Hamm_(Westfalen).jpg) highlighted to be sure that this node was not misplaced:
https://www.openstreetmap.org/node/3323583513 

But I thought there would be another clock at another side of the outside building I had to check.

**Proposed Solution**
Having `indoor=yes` shown somewhere would help me a lot to be able to solve the quest without errors.

**Comment by westnordost** [comment]
I am really not sure if this tag is consistently used on all indoor things that it would make sense to make the user expect it by always displaying it. E.g. I think most shops in a mall do not have `indoor=yes` set.

So when `indoor=yes` is missing on a clock, wouldn't users who have seen a location-text like "Something (variety store) - indoor" also expect that if "indoor" is not mentioned, it will surely be outside? However, this is not the case when the tag is missing.

**Comment by westnordost** [comment]
Small things that are hard to find... well, maybe it would be helpful to have a quest that asks whether such a thing is indoor or not when it is inside a building outline (and does also not have `level` etc. tagged) and have that quest a higher priority than others asking things about these.

If this quest is implemented, then showing a "(indoor)" hint could be revisited. Feel free to create a quest request ticket for that. This ticket I'll close for now.

**Comment by westnordost** [comment]
Should not be implemented before  #5175

**Comment by HolgerJeromin** [comment]
now unblocked
