### ISSUE TITLE
Check existence of dovecotes/pigeonries

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5172]
**Use case**
I tend to see them less often these days, and they are easily abolished. Checking the existence regularly would help keep the map ut-to-date.

**Proposed Solution**
Add `man_made = dovcote` to the `CheckExistence` quest (maybe every 6 years?).

**Comment by westnordost** [comment]
They are difficult to see from the ground because they are often situated above ground, e.g. also on rooftops.
