### ISSUE TITLE
Possible ambiguous description of the tactile pavement quest (crossings) 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5173]
There seems to be some room for confusions regarding tactile pavements on crossings, stemming from a vage osm Wiki article about it.

Currently StreetComplete is searching for `highway=crossing` nodes and asks if it should add yes/no to `tactile_paving`.

However, there are crossings which feature tactile pavings along the crossing itself. So for this the same tag (`tactile_paving=yes/no`) is used. But on the actual way across the road, tagged with `highway=footway` and `footway=crossing`.

As StreetComplete is only showing a pin and asks "on both sides?" there's no clear way to differentiate between both cases for the end user.

This lead one user, who misunderstood this, to explicitly explain this feature wrongly in a diary entry to other users, which probably lead to a lot of wrongly mapped data by this user:

![Screenshot_2023-08-04-17-45-01-147-edit_com android chrome](https://github.com/streetcomplete/StreetComplete/assets/614929/e7dd5bd5-42c8-40d8-99ce-e65fc80ebb77)

[Diary entry](https://www.openstreetmap.org/user/une%20abeille/diary/402005)

I think this should be rephrased to be crystal clear what is and is not meant by this quest, to avoid such issues in the future. 

## Versions affected:

All until 53.3 (at least)

**Comment by pkoby** [comment]
See #3407

It is apparently referring to the ends of the crosswalk, despite being redundant to the kerb nodes, and even though it's tagging the crossing node, not the crossing way. IMO the crossing node should never have `tactile_paving` tags, only a crossing way or kerb nodes. If someone wants information about the kerbs, map the kerbs.

I don't think we're ever going to get any better explanation or change on this issue.

**Comment by RubenKelevra** [comment]
@pkoby wrote:
> I don't think we're ever going to get any better explanation or change on this issue. 

I think we could improve the sentence and explain which sides are meant.


>It is apparently referring to the ends of the crosswalk, despite being redundant to the kerb nodes, and even though it's tagging the crossing node, not the crossing way. IMO the crossing node should never have tactile_paving tags, only a crossing way or kerb nodes. If someone wants information about the kerbs, map the kerbs. 

I there's a road with tagged sidewalks, how would you map curbs? This only works if you completely map the sidewalks as separate path.

That's not a feasible amount of work for just tagging if there are tactile markings on the crossing.

**Comment by westnordost** [comment]
_"Does this crosswalk have tactile paving on both sides?"_ seems pretty clear to me.

That une_abeille had to explicity write in the diary entry that it should **not** mean what the wording in this app suggests but instead another thing is actually also a clear indicator for me that the wording is already clear.

>> I don't think we're ever going to get any better explanation or change on this issue.

> I think we could improve the sentence and explain which sides are meant.

What **is** your suggestion then to improve the wording? What would even be the problem with the current wording?

**Comment by pkoby** [comment]
From https://github.com/streetcomplete/StreetComplete/issues/3407#issuecomment-1492440669

> "Does this crosswalk have tactile pavings on both ends"

"Sides" could mean sides of the street, where the ends of the crosswalk are, or sides of the crosswalk, e.g. along the length of it. "Ends" should have no other meaning.

**Comment by westnordost** [comment]
So you say "ends" is better than "sides"?

**Comment by pkoby** [comment]
Yes.

**Comment by westnordost** [comment]
Done, thanks
