### ISSUE TITLE
Edit for chenge to POI when "It's at a slightly different marker position" give incorrect changeset comment. 

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#5174]
The changeset comment for changeset [139453655][1] is "Survey opening hours" when the actual edit did not add opening hours, it instead relocated the shop node slightly. 

[1]: https://www.openstreetmap.org/changeset/139453655

**How to Reproduce**

1. Select a node that has an opening hours quest visible. 
2. Instead of adding opening hours tap "OTHER ANSWERS" then "It's in a slightly different position".
3. Choose new location and upload manually when on WiFi.

**Expected Behavior**

The changeset comment will say something like "Update position of point of interest". 

**Versions affected**

Observed in v53.3

**Comment by westnordost** [comment]
This is not a bug but intended behavior. I am sure it was discussed in a previous ticket but I am too lazy to search for it now.

In a nutshell, the change is put into the changeset in which context it was made. The moving of the node was made in context of answering opening hours.
