### ISSUE TITLE
Ask "Is this inside a building?"

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5175]
### General
Affected tag(s) to be modified/added: [indoor=yes/no](https://wiki.openstreetmap.org/wiki/Key:indoor)
Question asked: **Is this inside a building?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose: 
  _Small objects are hard to find on a survey; adding the information whether it is inside or outside helps verifiability and also helps indoor renderers_
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  _Well, if it is not outside, it is probably inside (except if it does not exist). POIs inside buildings are usually only mapped for buildings that are publicly accessible (malls, train stations, ...)_
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)
  _Didn't check_

### Ideas for implementation

**Element selection:** All POIs of certain types within building outlines (or optionally also: just outside of building outlines) that have neither `indoor` nor `level`, `level:ref`, `location` etc. tagged

POIs to ask for:
- `amenity=parcel_locker` (see #5098)
- `amenity=clock` (see #5170)
- `emergency=defibrillator` (replaces `AddIsDefibrillatorIndoor` quest)
- `amenity=atm`
- some more from [here](https://docs.google.com/document/d/1tcLm0EDWoCBdkq1N0pKebtksJcF2vMtUgKc9h96fuF0)? More suggestions in the comments.

### Implementation

Very straightforward, just copy/replace `AddIsDefibrillatorIndoor` and adapt it accordingly to include other POIs too.

---

Implementation of this unblocks #5170.

cc @HolgerJeromin - your first quest?

**Comment by HolgerJeromin** [comment]
@qugebert Feel free to go ahead. I will not have time to implement this.

**Comment by qugebert** [comment]
Is this element selection ok?

nodes with
         (
         emergency = defibrillator
         or emergency = fire_extinguisher
         or amenity = atm
         or amenity = telephone
         or amenity = parcel_locker
         or amenity = luggage_locker
         or amenity = locker
         or amenity = clock
         or amenity = post_box
         or amenity = public_bookcase
         or amenity = give_box
         or amenity = vending_machine and vending ~ parking_tickets|public_transport_tickets
         or amenity = ticket_validator
         )
         and access !~ private|no
         and !indoor and !location

I'm not sure about the last 4 (public_bookcase,give_box,vending_machine,ticket_validator) but taginfo listed them as sometimes combined with indoor=yes

And should we enable the 'delete Element' Function? It was disabled for the defibrillator-task.

**Comment by mnalis** [comment]
> Is this element selection ok?

Looks reasonable to me. Although in StreetComplete AFAIK it is more commonly written with regexp, e.g. convert those multiple lines to `... or amenity ~ atm|telephone|parcel_locker|luggage_locker|...`

**Comment by westnordost** [comment]
Ah, missed this comment. Yes, the form as @mnalis is faster too, by the way.

The list looks fine. However, since it shall only be asked for nodes inside (or near-inside, if it is not too performance-intensive to implement), it could be expanded. E.g. it is common that sweets vending machines are inside malls etc. too.

We started to create a list of (street) furniture in the linked doc from #4912. But anyway, I figure this is something that could always be expanded later.
