### ISSUE TITLE
Inaccurate accounting of edits by country

### ISSUE THREAD

**Issue by draeklae** [streetcomplete/StreetComplete#5176]
In a gist: Edits in changesets over a large area (over multiple countries) are being mapped to the wrong country. 

So I failed to read the entire FAQ before using the app and ended up doing some remote editing based on info I'd gathered previously. (Lesson learned.) In particular, this ended up in [this changeset](https://www.openstreetmap.org/changeset/138842301).

Now on account of this changeset the app now shows me I have 6 edits in Poland, even though none of the changes actually affect Poland at all. It seems the edits are tallied based on the country that is at (or nearest to?) the center of the changeset edit box rather than the edits (ways) themselves.

Although in this case the bug comes from unsupported behavior (remote editing), I am reporting this since it might affect legitimate use cases too, e.g., when making multiple edits around the border between two or more countries.

**How to Reproduce**
Make edits that get merged into a single changeset that spans more than one country.

**Expected Behavior**
Edits are accounted for the country they actually affect.

**Versions affected**
Android 11, SC 53.3

**Comment by westnordost** [comment]
Yes, the country recorded for a whole changeset is the center of the bounding box of that changeset. It is not possible to record this per-change.

**Comment by draeklae** [comment]
I see... Is there any way of removing or ignoring specific changesets from the statistics? Or resetting the statistics altogether so only changes after a certain date are taken into account? (Since right now my history is "tainted" with that one Poland edit.) I tried erasing all app data but it keeps coming back.

**Comment by westnordost** [comment]
No.
