### ISSUE TITLE
Quest Modification: Height limit for railway crossings

### ISSUE THREAD

**Issue by gdprdatasubect** [streetcomplete/StreetComplete#5180]
**Use case**
Expand Quest: "What is the height limit here?" to `railway=level_crossing`

**Proposed Solution**

Ask if there is a maxheight displayed via signs if no tag `maxheight:signed=no` and `maxheight=default`
If there is a sign tag  `maxheight:signed=yes` and ask the user for the corresponding value for `maxheight`

**Comment by matkoniecz** [comment]
In which countries it is commonly signed? In Poland for example signage is unusual in such cases.

**Comment by mnalis** [comment]
Yeah, it does sound strange to me too, how would it even look? Do you have a picture @gdprdatasubect ?

I've always understood that it is [railway=level_crossing](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing) only if _"a road crosses a railway on the same level; i.e., without a bridge"_ - and as it is _level_, there is not bridge/tunnel, so there should not be any height limits?

Taginfo says that only `0.12%` of [railway=level_crossing](https://taginfo.openstreetmap.org/tags/railway=level_crossing#combinations)  have _[maxheight](https://taginfo.openstreetmap.org/keys/maxheight)=*_ tag, and the wiki does not mention that tag combination either.

**Comment by mnalis** [comment]
Thanks @gdprdatasubect, does this situation happen often in your country that `railway=level_crossing` has such height limitations? Can't say I've seen them much (or really at all) in Croatia.

Note [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md), especially _":zzz: No spam"_ and _":clock4: Effort vs impact"_. 

- If it does not happen often, perhaps as a workaround you can just long-press and leave a note (maybe even with a picture)? 

- But if it does happen often enough, then we would need list of countries where [it happens often enough](https://ent8r.github.io/blacklistr/), so such quest can be enabled there.

**Comment by arrival-spring** [comment]
It seems to be only/mostly relevant where there are overhead wires, so the quest could be limited to level crossings of railways with [electrified=contact_line](https://wiki.openstreetmap.org/wiki/Tag:electrified%3Dcontact_line)

**Comment by westnordost** [comment]
So, I guess it makes sense to ask for railway crossings with electrified contact lines.

**Comment by rhhsm** [comment]
I assume there is an international railway standard for the distance between rails and overhead wires? Then crossings with a height limit less than that standard should be very rare, and the quest would be very spammy?

**Comment by matkoniecz** [comment]
> So, I guess it makes sense to ask for railway crossings with electrified contact lines.

Not everywhere. In Poland it seems that catenary height is higher than highest standard vehicle size and therefore height limit are unsigned.

**Comment by westnordost** [comment]
Anyway, I do not think it is worth the effort to research in which countries a certain always-sufficient min height for electrified contact lines can be assumed, considering that such railway crossings are not that frequent that it would feel like spam to be asked maybe a little too often. From my side, it can be implemented as described: For all railway crossings that share a node with a railway line that has an electrified contact line.

The code is here in case anyone would like to create a PR:

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeight.kt

It would make sense to add a unit test for this case, too. Current tests for this quest are here:

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeightTest.kt

**Comment by westnordost** [comment]
@gdprdatasubect it would be useful if you uploaded the first photo you got there (if it is yours) also into the wiki to be mentioned in https://wiki.openstreetmap.org/wiki/Key:maxheight

**Comment by FloEdelmann** [comment]
FYI: Related question about this issue in the OSM Forum: https://community.openstreetmap.org/t/streetcomplete-fragt-bei-eisenbahn-weg-kreuzung-nach-durchfahrtshohe/103606/27

**Comment by claudiush** [comment]
The problem with this quest is that in cities with tram infrastructure (e.g. my experience in Leipzig) suddenly the whole city is plastered with these quests and it took me a few days to understand this wasn't triggered by a bug with the generic maxheight quest, but because the crossing tram lines have overhead wires. I don't know of a single crossing in Leipzig that has the maxheight signed for any tram crossing, so there seems to be very little value. Maybe ignore the quest for railway=tram ?

**Comment by westnordost** [comment]
It seems to be a useful information whether the maximum height on roads is limited due to the tram overhead wires, as these wires are not particularly high up. Then again, if such information is virtually never signed for trams, it indeed would make no sense in asking for it. Would need some input, how is it in other places with tram lines - or maybe the signs come earlier, not directly in front of the crossing?

**Comment by matkoniecz** [comment]
I have never ever seen such signs for tram crossings in Poland. Though in Poland it is extremely, extremely rare also for rail level crossings.

**Comment by mnalis** [comment]
Never seen in it on tram crossings in Croatia, extremely rare for rail level crossing too.

**Comment by westnordost** [comment]
Alright, I excluded tram lines
