### ISSUE TITLE
add quest profiles (for example for public transport)

### ISSUE THREAD

**Issue by rynr** [streetcomplete/StreetComplete#5185]
**Use case**
As a user whi had sometimes time to take a look at opening times or the width of a street, I'm sometimes sitting in a bus. I could limit the quests to the things I can answer while sitting in a bus, but then later I have to enable all the other things again.

**Proposed Solution**
There could be some quest profiles. For me, there could be a profile for public transport (containing number of tracks of a road, if there's pedestrian places around), on-the+fly (when I will not take the time to look at signs but the stuff I can easily add when just walking) and of course regular (when I have time).

**Comment by arrival-spring** [comment]
Settings > presets allows to create presets (profiles) and then you can select quests for each one.

Is this not discoverable enough, or not well named, or not well translated perhaps?

**Comment by rynr** [comment]
Oh, that is available already?
Then closer this issue, I'll check later if I can find it.

**Comment by rynr** [comment]
Yes, just found it. Sorry for the effort.
