### ISSUE TITLE
Building with opening hours is not tagged in the shop overview

### ISSUE THREAD

**Issue by flovo** [streetcomplete/StreetComplete#5188]
When using the shop overlay to add missing shops/institutions I found some buildings with opening hours are not marked on the map. 
For example for [this building](https://www.openstreetmap.org/way/78472533), there is neither an icon indicating that the location already is named/tagged, nor where the opening hours review  quest visible.
![Screenshot_20230814-001745_Street­Complete](https://github.com/streetcomplete/StreetComplete/assets/4864182/854625e7-dfef-4bdc-9c8e-4520ad051c07)

The problem here is that I almost added a duplicate POI as the opening hours seemed to be missing instead of updating the outdated hours.

**Comment by Helium314** [comment]
> The problem here is that I almost added a duplicate POI

You can't create a town hall in shop overlay anyway, so no danger of adding a duplicate.

**Comment by matkoniecz** [comment]
Note that it is town hall, not a shop.

**Comment by flovo** [comment]
As a user, I expected to find every entry in the shop overlay which is located in an building and with an sign with name and opening hours on the outside. 

----

I can create "Government Office".
![Screenshot_20230814-072012_Street­Complete](https://github.com/streetcomplete/StreetComplete/assets/4864182/d5ce238c-190b-4997-a05f-17abfe8ef0a2)
There are 5 " townhalls" around the place. In each residing (multiple) government offices. All sharing the same opening hours. When I tag each of these, the opening hours on the townhall are meaningless, as there's nothing but the offices inside.

Also the opening hours changed since the townhall was tagged, so the opening hours on the government offices would have different opening hours than the townhall, but in fact there's only a single sign on the outside. (All inside has the same opening hours) 

----

I checked the wiki for [townhall](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtownhall) and [government office](https://wiki.openstreetmap.org/wiki/Tag:office%3Dgovernment). I guess both can exist on the same building, but I'm not sure. So now I would create up to 3 government offices on each of the townhall building, all sharing the same opening hours and entry. So 4 times the same opening hours on 1 door of a building the size of a small 1 family house.
