### ISSUE TITLE
Cycleway quest asked again immediately for some oneways

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5190]
**How to Reproduce**
Answer the cycleway quest for https://www.openstreetmap.org/way/25631884.
Notice the quest is asked again.
Undo your answer and see that `cycleway=opposite_lane` was present and changed to a "normal" but unspecific lane, which is why the quest is asked again.

**Expected Behavior**
Since there already is a cycleway in opposite direction, the quest should show both sides from the start (like it does for similar situations on `highway=residential`).

**Versions affected**
53.3

**Comment by westnordost** [comment]
Err, I cannot... really reproduce this. Probably I did not understand the description. Look at this test case:

```kotlin
    @Test fun issue5190() {
        val tags = mapOf(
            "cycleway" to "opposite_lane",
            "oneway" to "yes")

        val parseResult = createCyclewaySides(tags, isLeftHandTraffic = false)

        assertEquals(
            LeftAndRightCycleway(
                left = CyclewayAndDirection(UNSPECIFIED_LANE, BACKWARD),
                right = null
            ),
            parseResult
        )

        val changesBuilder = StringMapChangesBuilder(tags)
        parseResult!!.applyTo(changesBuilder, isLeftHandTraffic = false)

        assertEquals(
            mapOf(
                "oneway" to "yes",
                "cycleway:left" to "lane",
                "oneway:bicycle" to "no",
                "cycleway:left:oneway" to "-1",
            ),
            changesBuilder
        )
    }
```

Parsing a `oneway=yes` with `cycleway=opposite_lane` and just applying the parse result without any changes **does** tag `oneway:bicycle=no` (etc.).

**Comment by westnordost** [comment]
Probably a UI issue rather than a parser / writer issue.
