### ISSUE TITLE
Bike Parking: Floor Markings

### ISSUE THREAD

**Issue by grafst** [streetcomplete/StreetComplete#5191]
**Use case**
Some of the Bicycle Parkings in my City are just markings on the ground, like this:
![Bike-share-parking](https://github.com/streetcomplete/StreetComplete/assets/8471055/e6e4eaee-750a-4db4-bb0d-2d0f18da5c49)
 There is currently no such option in streetcomplete.

**Proposed Solution**

I think it would be tagged as
[bicycle_parking=floor](https://taginfo.openstreetmap.org/tags/bicycle_parking=floor#overview)

I could make a PR if this something desired.

**Comment by westnordost** [comment]
You are sure that this isn't a parking space for bike rental instead?

Only rental bikes park there. Is it illegal to park your car wherever (it isn't in the way) in Switzerland?

**Comment by grafst** [comment]
It is just an example picture i grabbed from google. I can take a real one later.

**Comment by matkoniecz** [comment]
Is such type really common? From what I remember it was one of rare parking types when I implemented it but maybe it is getting more common

**Comment by mnalis** [comment]
[Taginfo](https://taginfo.openstreetmap.org/keys/bicycle_parking#values) says it is only used `0.46%`  as the bicycle parking type worldwide (although that is more than 2000 uses). 

There is always an option of leaving a note in `Other answers` / `Can't say` if it is one of less popular values.

> I can take a real one later.

That would be good in any case @grafst , as the picture on [the wiki](https://wiki.openstreetmap.org/wiki/Key%3Abicycle_parking) also seems to be of rental bike parking unless I'm mistaken.

**Comment by westnordost** [comment]
Alright, I would say that the kind of bike parking is rare enough that if one encounters such a bike parking, one can just leave a note instead. Adding a proper picture to the wiki would be really helpful in any case.

**Comment by BalooUriza** [comment]
I know of several marked bicycle parking spaces including at least two that
are explicitly reserved for the physically disabled.

**Comment by mnalis** [comment]
> I know of several marked bicycle parking spaces including at least two that are explicitly reserved for the physically disabled.

Could you share pictures, @BalooUriza? I'm somewhat confused if you're talking about places reserved only for physically disabled bicycle drivers (?) or about spaces which are shared between regular bicycle parkings and parking for cars belonging for disabled persons, or something else?

**Comment by BalooUriza** [comment]
Sure thing!  https://www.openstreetmap.org/node/7967019159 looks like
***@***.***/111247250984896076

**Comment by mnalis** [comment]
Thanks @BalooUriza, so it is for parking vehicles like those:  https://www.bikeabilitywales.org.uk/wp-content/gallery/cycles-lined-up/Wheelchair-cycles.jpg and https://www.pinterest.com/pin/454089574899306850/?

The former picture looks like cargo bicycles able to transport wheelchair user as "cargo" (i.e. requires additional able-bodied driver); but the latter one looks like wheelchair user can drive it by themselves and detach wheelchair from bike at destination (and presumably park non-wheelchair part of the vehicle at the parking space as you show in that Fediverse post)?

Do you know how would those parkings be marked in OSM? And how popular are they (most less-popular types of parking are left to  _"Leave note"_ functionality, as mentioned above in https://github.com/streetcomplete/StreetComplete/issues/5191#issuecomment-1682079898)

**Comment by westnordost** [comment]
I've seen plenty of "floor markings" bike parkings in Basel, e.g.

https://www.google.de/maps/@47.5589134,7.6007589,3a,75y,355.29h,63.58t/data=!3m9!1e1!3m7!1sP8SvMWy5mC7b7OBMOjfxRg!2e0!7i13312!8i6656!9m2!1b1!2i28?entry=ttu

, apparently used by anything with two wheels. There are also these bike parking areas with some bicycle stands sprinkled in-between, so you got something like 25% of bikes parked at stands, the rest just in that area.

**Comment by grafst** [comment]
Here finally the promised picture:

![ab3e491a-de51-458c-aa7a-43fe3022e073](https://github.com/streetcomplete/StreetComplete/assets/8471055/8b39e50b-3a09-4076-b0f0-445f69a00bcc)

**Comment by BalooUriza** [comment]
On Mon, Oct 16, 2023 at 6:45 PM Matija Nalis ***@***.***>
wrote:

> Thanks @BalooUriza <https://github.com/BalooUriza>, so it is for parking
> vehicles like those:
> https://www.bikeabilitywales.org.uk/wp-content/gallery/cycles-lined-up/Wheelchair-cycles.jpg
> and https://www.pinterest.com/pin/454089574899306850/?
>
No, anything larger than a mountain bike will not fit through the gate that
goes into the cage.  It's for any kind of bicycle that will fit in the
cage, and is displaying a handicap parking placard.

**Comment by mnalis** [comment]
> No, anything larger than a mountain bike will not fit through the gate that
goes into the cage.  It's for any kind of bicycle that will fit in the
cage, and is displaying a handicap parking placard.

Oh, OK @BalooUriza. It seemed to me to have different type of stand (much longer?), so I though it might be for specialized bicycle types. So it is basically just a regular bicycle parking with stands reserved for less-than-100%-handicap people (who still drive regular bicycles)? 

IOW in that [picture of yours](https://social.tulsa.ok.us/@BalooUriza/111247250984896076), parking space marked with wheelchar pictogram would be in OSM tagged as regular `amenity=bicycle_parking` + `bicycle_parking=stands`, just with additional `access=private`  ([access=permit](https://wiki.openstreetmap.org/wiki/Tag:access=permit) sounds tempting, but it is only for permits that _anyone_ can obtain). 

If so, that picture can already be solved in StreetComplete, via [Bicycle type quest](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#bike_parking_type) and [Bicycle access quests](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#parking_access), right?

_(Note there exist even more detailed additional tags that might be of interest for tagging such spaces, like [capacity:disabled=*](https://wiki.openstreetmap.org/wiki/Key:capacity:disabled)  and maybe  [private=disabled](https://wiki.openstreetmap.org/wiki/Key:private); but StreetComplete does not currently have quests for that level of detail AFAIR - I'd suggest to leave a Note instead if you're interested in detailed mapping of those; or use [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) ("Expert Edition") fork which allows for adding _any_ raw tags directly to the OSM)_

**Comment by BalooUriza** [comment]
> Oh, OK @BalooUriza. It seemed to me to have different type of stand (much longer?), so I though it might be for specialized bicycle types. 

Not nearly that well thought through.  This is probably meant for accessible human powered machines as you describe, however, such machines have no physical method of getting to the space in the first place.

> So it is basically just a regular bicycle parking with stands reserved for less-than-100%-handicap people (who still drive regular bicycles)?

De facto but not de jure, yes.

> IOW in that [picture of yours](https://social.tulsa.ok.us/@BalooUriza/111247250984896076), parking space marked with wheelchar pictogram would be in OSM tagged as regular amenity=bicycle_parking + bicycle_parking=stands, just with additional access=private ([access=permit](https://wiki.openstreetmap.org/wiki/Tag:access=permit) sounds tempting, but it is only for permits that anyone can obtain).

That one would be effectively private at the time I took that photo; please be aware that photo and knowledge of that site is from ~2010.  In addition to needing access to the cage, one would also need a disabled parking placard to use that specific space.  Also I'm not convinced _that_ was thought through either, since we _are_ talking about Portland, and the whole reason for having a cage in the first place is because anything metal that isn't set in concrete will get stolen there.

**Comment by westnordost** [comment]
ping

**Comment by westnordost** [comment]
ping

**Comment by mnalis** [comment]
> Here finally the promised picture:

@grafst unfortunately, your picture does not seem to have any markings on the floor that would clearly indicate that those spaces are specifically intended for parking of bicycles (instead of e.g. cars or motorbikes or whatever). Do you or @BalooUriza (or someone else?) can take a pictures of such place which would:

- be clearly marked as parking for bicycles by **markings on the floor**
- **lack any stands, wheelbenders, boxes** or any other physical infrastructure for locking the bicycle to
- **not being primarily intended / used for rental bikes** (like picture on the [wiki](https://wiki.openstreetmap.org/wiki/File:Parking_%C3%A0_v%C3%A9los_sans_arceaux.jpg) seems to unfortunately be). 


Ideally, the picture would show no rental-branded bicycles/scooters, but a one or two regular bicycles, while still clearly showing that it only has bicycle parking markings on the floor. 

(Croatia is however quite lacking in such parkings (at least I don't recall ever seeing one), so I cannot really take such picture myself.)

**Comment by westnordost** [comment]
I asked for help in the forum: https://community.openstreetmap.org/t/wanted-ein-reprasentatives-foto-fur-fahrradparkplatze-die-nur-markierungen-sind/111526

**Comment by gdabski** [comment]
I have one like this, but it lacks any parked bicycles.
![20240408_091856](https://github.com/streetcomplete/StreetComplete/assets/20536467/927aa1d8-92d2-4633-bae9-8dba12a89b01)

**Comment by westnordost** [comment]
It's a good example picture for the wiki. But I fear on a thumbnail-sized picture, almost nothing would be discernible.
