### ISSUE TITLE
Bike paths overlay: Show as "bike only" when foot=use_sidepath

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#5194]
As requested.

In the bike paths overlay, ways tagged as `highway=cycleway` and `foot=use_sidepath` currently display as "shared-user path".

For example:

![Screenshot_20230815-053752.png](https://github.com/streetcomplete/StreetComplete/assets/19356194/e7c26f46-a6f7-4b47-beeb-fe1c08dd7c89)

Where there is a bike-only path right next to a footway.

Tags on that way:

![Screenshot_20230815-053633.png](https://github.com/streetcomplete/StreetComplete/assets/19356194/a4968468-f6d5-4aba-aa95-9e789a91e1b8)

**How to Reproduce**

Any way tagged with `highway=cycleway` and `foot=use_sidepath` currently show this behaviour.

**Expected Behavior**

According to [this wiki](https://wiki.openstreetmap.org/wiki/Tag:foot%3Duse_sidepath), while `foot=use_sidepath` is non-standard, it is still used commonly enough (including where I live) on ways where pedestrian access is typically allowed that it should be treated as a negative access value more-or-less equivalent to `foot=no` for routing engines. I propose therefore that SC reflect this in its bike paths overlay, displaying the above example as a "bike-only path" since `foot=use_sidepath` denotes that it is not a shared-user path.

**Versions affected**

Android 13
SC v53.3

**Comment by mnalis** [comment]
(Thanks for using the template, it is much more understandable what the issue is now!)

I would agree with your suggestion, as wiki says:

> In some countries it is illegal for pedestrians to use a road if a parallel compulsory sidepath exists. On OSM, this can be indicated by tagging the main road as [foot](https://wiki.openstreetmap.org/wiki/Key:foot)=use_sidepath if the sidepath is mapped separately

So `foot=use_sidepath` can be used on `highway=cycleway` only if it is indeed forbidden for pedestrian to walk on the cycleway, **and** there is `highway=footway` already mapped parallel to it. Thus _"shared-user path"_ definitely sounds wrong on that `highway=cycleway` as pedestrians are forbidden there.

**Comment by westnordost** [comment]
I'd expect `foot=use_sidepath` to be tagged on the **street**, not the bike path. `highway=cycleway` already is exclusive to bikes unless otherwise specified with `foot=*`.

**Comment by frankie2784** [comment]
Default foot access on highway=cycleway differs by country. In mine, foot
access is assumed unless stated otherwise.

**Comment by westnordost** [comment]
Oh. That's new to me. Is this documented anywhere? And, how would a bike path look like in Australia where foot traffic is prohibited? Do combined (but segregated - by different paving or a drawn line) foot- and bike paths even exist?

**Comment by frankie2784** [comment]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway - see under "Foot access on cycleways" it states that "Different countries have their own rules as to whether foot access is allowed by default on cycleways"

After some more investigation this morning, I found that there is no reference to implied foot access on cycleways in Australia (my bad). However, I am aware of at least one local journey planning app in Victoria that assumes foot=yes on a cycleway without a foot tag. Hence why being explicit about access is always better than implicit in my view.

Some examples of segregated bike paths:

![image](https://github.com/streetcomplete/StreetComplete/assets/19356194/572f18cc-59cf-4a75-a163-f8c116e648ec)
![image](https://github.com/streetcomplete/StreetComplete/assets/19356194/db18ccf8-84ba-48e5-8d90-905bfe352409)

**Comment by westnordost** [comment]
Hm right, ... while I would never use `foot=use_sidepath` on a `highway=cycleway` (instead, `foot=no`), it is debatable if this should be classified as incorrect tagging. So, at least StreetComplete should rather interpret `foot=use_sidepath` as "something like no" rather than "something like yes" even though it will not tag it.
