### ISSUE TITLE
Does this caravan area have a .. ? 

### ISSUE THREAD

**Issue by petitminion** [streetcomplete/StreetComplete#5206]
If you want me to create one issue per question let me know. In the mean this is a proposition to tag objects tagged with this tag : [caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site)

### General
Affected tag(s) to be modified/added:  [fee](https://wiki.openstreetmap.org/wiki/Key:fee)
Question asked: **Does this caravan area have a [fee](https://wiki.openstreetmap.org/wiki/Key:fee)?**
response : yes/no

some question for theeses tags  :
-  [sanitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station)
- [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point)
- [power_supply](https://wiki.openstreetmap.org/wiki/Key:power_supply)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ x ] 🚧 To be added tag is established and has a useful purpose
- [ x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ x ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ x ] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**
An image of the objects (water point, sanitary dump etc) and three answer : 
- yes 
- no 
- not sure -> let a note
- specific answer (like `customers ` for  [sanitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station) )

**Comment by westnordost** [comment]
Would this be visible from the outside, whether it requires a fee or not? Or woudl this be visible from the "type" of caravan site? I.e. is it possible to acquire this information without trespassing and/or asking someone?

**Comment by petitminion** [comment]
yes it's quite obvious, you have to paid to be able to park so there is a barrier and a machine that allow you to paid.

**Comment by westnordost** [comment]
I see, so it looks like this is eligible. For the other tags, sounds to me that you already have to be inside the caravan site to be able to answer these, no? Caravan sites are usually not really "off limits" for people to just go through, but I think it would not be ok to "sniff about" to look for these things as long as you are not a customer.

**Comment by petitminion** [comment]
A lot of caravan area, at least in france are free because their is laws that make them mandatory in some spaces. There is an environmental need of [sanitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station) so they are freely accessible most of the time

**Comment by mnalis** [comment]
- related issue https://github.com/streetcomplete/StreetComplete/issues/4198 and PR https://github.com/streetcomplete/StreetComplete/pull/4213 where some of the suggestions have been discussed (and after discussion some of them implemented, although in different way, e.g. [backcountry=*](https://wiki.openstreetmap.org/wiki/Key:backcountry) vs. `fee=*` ). 
 
It would be good if you @petitminion could read those issue/PR and give feedback which of those quests would apply here too, and which remains to be added.

As I understand it, [tourism=caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site) is similar to [tourism=camp_site](https://wiki.openstreetmap.org/wiki/Tag:tourism=camp_site) + [caravans=yes](https://wiki.openstreetmap.org/wiki/Key:caravans)? So it seems logical to me that perhaps [code](https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/camping) for those might be enhanced to also include this tagging, and add missing details.

> There is an environmental need of [sanitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station) so they are freely accessible most of the time

if I understand correctly that it is almost always available, then there should be **no** quest for that?  (see _"💤 Not an overwhelming percentage of quests have the same answer (No spam)"_ tenet above)

**Comment by petitminion** [comment]
Camp_site and caravan_site are différent has you can see in the wiki off caravan_site. So Backcountry doesn't apply here. And I don't think this has something to do with the code of camp_site

> if I understand correctly that it is almost always available, then there should be no quest for that? 

Well actually I wasn't clear we saying that most of them are free. It's more that most of them can be accessed freely by foot, there is no physical delimitation since these are parkings. So it's not an issue to get in there by foot. 


Do you know any tools to have statistics about tags ?

**Comment by mnalis** [comment]
> Do you know any tools to have statistics about tags ? 

You mean, more detailed than taginfo.openstreetmap.org linked on those wiki pages?
One probably could use overpass-turbo.eu if needed, but you'd need to
know _exactly_ what you want statistics about?

**Comment by rhhsm** [comment]
At first I was as confused as @mnalis : what makes a caravan site so different from a camping site that a different quest is needed. But then I understood that this is not about caravans (trailers) but about motorhomes/campers/campervans. Maybe this confusion should be cleared first (at the wiki) before quests for such sites could be developed?

**Comment by petitminion** [comment]
> if I understand correctly that it is almost always available, then there should be no quest for that? (see "💤 Not an overwhelming percentage of quests have the same answer (No spam)" tenet above)

I looked into the statistics and  I think the quest for fees should be done, plz see https://taginfo.openstreetmap.org/tags/tourism=caravan_site#combinations. 

> Maybe this confusion should be cleared first (at the wiki) before quests for such sites could be developed?

I don't see how to make this more clear but feel free to do it : ```A caravan site, caravan park, [motorhome stopover](https://en.wikipedia.org/wiki/Motorhome_stopover) location or [RV park](https://en.wikipedia.org/wiki/RV_park) is a place where people with caravans / motorhomes / recreational vehicles can stay overnight, or longer, in allotted spaces known as "pitches" or "sites". They usually provide facilities including toilets, waste disposal, water supply, power supply etc..

They may also have some space for tents. If a site is primarily for tents, it should be tagged as [tourism](https://wiki.openstreetmap.org/wiki/Key:tourism)=[camp_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site). If [tents](https://wiki.openstreetmap.org/wiki/Key:tents) are allowed on a site it should be tagged with tents=[yes](https://wiki.openstreetmap.org/w/index.php?title=Tag:tents%3Dyes&action=edit&redlink=1).```

**Comment by qugebert** [comment]
I can try to implement the fee-quest, but is this really a simple yes/no-quest or might there be conditional fees like in the parking_fee quest?

**Comment by petitminion** [comment]
@qugebert  thx you :) Afaik there is only yes/no possibility

**Comment by westnordost** [comment]
Actually, I think the `AddGeneralFee` quest could just be extended.

**Comment by qugebert** [comment]
> Actually, I think the `AddGeneralFee` quest could just be extended.

Yes, i didn't know this quest but this makes sense.

**Comment by petitminion** [comment]
Should we speak here about the three other ones ? 

- [sanitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station)
- [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point)
- [power_supply](https://wiki.openstreetmap.org/wiki/Key:power_supply)

**Comment by rhhsm** [comment]
I think that before these quests are implemented in SC, the terminology involved should be clarified on the wiki. For instance, the tag is badly named as a caravan is generally thought of as https://en.wikipedia.org/wiki/Caravan_(trailer) while these quests are about sites for https://en.wikipedia.org/wiki/Motorhome Maybe the tag should be renamed `motorhome_site`? @petitminion will you bring it up on https://community.openstreetmap.org/c/general/tagging/70 or shall I do it?

**Comment by petitminion** [comment]
The wiki definition clearly state motorhomes and the terminology doesn't bother me. Also it will means a lot of work to change in osm side I suppose. So  I don't feel like asking to change it. 
 Also mr is merged and this issue will document it. But if you want to ask for a terminology change feel free to do it.
