### ISSUE TITLE
guidepost target group / activities

### ISSUE THREAD

**Issue by qugebert** [streetcomplete/StreetComplete#5208]
### General

The design of most of the guideposts is aimed at a specific target group, but does not rule out use by other target groups. The target group primarily addressed with the signpost is usually identified with one of the tags hiking=yes,bicycle=yes,mtb=yes,horse=yes, etc.

Some applications use this information
For example, waymarkedtraills.org has multiple overlays for hiking,biking,etc... and on these overlays, only guideposts with tagging for the selected activity are shown. Other applications have seperate views for hiking,biking,etc. too and might filter by these tags as well.

Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
See https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost
To describe the type(s) of the shown route(s), use the tags [hiking](https://wiki.openstreetmap.org/wiki/Key:hiking)=yes, [bicycle](https://wiki.openstreetmap.org/wiki/Key:bicycle)=yes, [mtb](https://wiki.openstreetmap.org/wiki/Key:mtb)=yes, [horse](https://wiki.openstreetmap.org/wiki/Key:horse)=yes or [ski](https://wiki.openstreetmap.org/wiki/Key:ski)=yes.

Some prefer the tagging guidepost={hiking,bicycle,...}

Question asked: **What is the target group of this guidepost?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [✓] 🚧 To be added tag is established and has a useful purpose
- [✓] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [?] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
        -> I guess in some cases it's not too obvious if the shown routes are dedictated to hikers,bikers,etc.
- [✓] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [✓] 🕓 Applies to a reasonable number of map data (Worth the effort) 
        -> 40.000 Nodes in Germany ([Overpass](https://overpass-turbo.eu/s/1za2)), idk how to find out how many affected nodes worldwide

### Ideas for implementation

**Element selection:** 
https://overpass-turbo.eu/s/1za2
`nwr["information"="guidepost"][!"guidepost"][!"mtb"][!"hiking"][!"bicycle"][!"horse"][!"guidepost:hiking"][!"guidepost:bicycle"][!"guidepost:mtb"][!"guidepost:horse"]`

`
override val elementFilter = """
        nodes with
        information = guidepost
        and !guidepost 
        and !bicycle and !hiking and !mtb and !horse and !foot
        and !guidepost:bicycle and !guidepost:hiking and !guidepost:mtb and !guidepost:horse and !guidepost:foot
    """
`

**Metadata needed:** 

**Proposed UI:**

Just like in recylcling_materials quest, we can select one (or more) activities for this guidepost. 
I could try to implement it myself, if this idea is not rejected outright.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/4758 where some issues was discussed.

**Comment by qugebert** [comment]
Oops, i wonder why i found only this Issue https://github.com/streetcomplete/StreetComplete/issues/2514, when i searched for "guidepost" before posting.

**Comment by matkoniecz** [comment]
maybe you have not checked closed ones?

**Comment by qugebert** [comment]
Yes, closed ones are not shown by default. My mistake.
