### ISSUE TITLE
Do not ask for path segregation in case either bicylce or foot is set to "no"

### ISSUE THREAD

**Issue by ironspock** [streetcomplete/StreetComplete#5213]
possible bug or enhancement on quest "How footway and bicycleway are segregated" (highway:path)

SC is asking for path segregation however the node already has a tag bicycle:no 
(refer to https://www.openstreetmap.org/way/990523743)

I'm not sure whether it's happen often or maybe it's better to change the node from highway:path to highway:footway via JOSM/ID/etc.

**Expected Behavior**
Do not ask for segregation in those cases.

**Versions affected**
v53.3

**Comment by qugebert** [comment]
I think this part of the query is wrong:

https://github.com/streetcomplete/StreetComplete/blob/b623dccefb4a45430b6664bbf78bc69b4aea4621/app/src/main/java/de/westnordost/streetcomplete/quests/segregated/AddCyclewaySegregation.kt#L21

In this case, we have a match of the combination highway = path and footway:surface

**Comment by westnordost** [comment]
Oh, that is definitely a bug. Thank you for the input, I will have a look at it now.

**Comment by westnordost** [comment]
It was added by @matkoniecz in #4642 , not sure why though. I don't really understand why the filter is there in the first place. Maybe he remembers?

(In any case, @ironspock , the way is tagged a bit weird: As a `highway=path` but `bicycle=no` (so a `highway=footway` then??) and then a `footway:surface` is set even though that's the only thing there is.)

**Comment by matkoniecz** [comment]
Weird tagging is present there, I opened https://www.openstreetmap.org/note/3851707

>  I don't really understand why the filter is there in the first place. Maybe he remembers?

to handle some not fully tagged ways, also `segregated` is looked at by surface overlay in some places so being sure that it is tagged was useful

I guess that case like reported here is blatantly invalid rather than missing tagging and could be skipped (though it would anyway cause confusion in surface overlay anyway...)

And maybe surface overlay should not simply check `segregated` but look at more complex info.

**Comment by qugebert** [comment]
> to handle some not fully tagged ways, also `segregated` is looked at by surface overlay in some places so being sure that it is tagged was useful

I see,  `footway:`-Prefix indicates, that there is more than only a footway and vice versa.
And why not exclude the ways, where one of both is tagged with no ?

**Comment by matkoniecz** [comment]
>  And why not exclude the ways, where one of both is tagged with no ?

In plan on fixing it this way + open notes in places with such tagging.
