### ISSUE TITLE
Adding name to railway platforms is inconsistent with wiki guidelines in most cases

### ISSUE THREAD

**Issue by burrscurr** [streetcomplete/StreetComplete#5215]
## Summary

As of now, the "What's the name of this stop?" quest (`AddBusStopName`) is asked for all `public_transport=platform`s. Due to #3374, this also applies to railway platforms. Though railway platforms are typically part of a station and don't have a name on their own, the quest encourages adding a name anyway.

## Wiki on `name` for public transport stops

The following table compares wiki guidance on how to map different types of public transport stops and their name. `public_transport=` is abbreviated as `pt=`. Bus stop tagging is included for comparison.

| Type                |  Tagging at the platform  | Tagging on stop position | Tagging on station | stop name tagging |
|---------------------|--------|-------------|-------------|-------------|
| bus stop            | `highway=bus_stop`                                  | -                                 | - | [on platform][bus] |
| bus stop (PTv2)     | `highway=bus_stop` + `pt=platform`    | `pt=stop_position`  | - | [recommended for platform, optional for stop position](https://wiki.openstreetmap.org/wiki/Public_transport#Buses) |
| railways (general)  | `railway=platform` + `pt=platform`    | `pt=stop_position`  | `railway=station/halt` | [discouraged on platform][rail-platform-1], [recommended on stop position][rail-general], [recommended on station][rail-station]|
| subways             | `railway=platform` + `pt=platform` + `subway=yes` | `pt=stop_position`  | `railway=station` + `station=subway` | [recommended on platform "for easier route editing"][subway-platform], [recommended on stop position][subway-stop], [recommended on station][subway-station] |
| tram stop           | `railway=platform` + `pt=platform` + `tram=yes`   | `pt=stop_position` + `railway=tram_stop` | - | [on stop position][tram-general] |

[bus]: https://wiki.openstreetmap.org/wiki/Buses
[rail-platform-1]: https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Platforms
[rail-general]: https://wiki.openstreetmap.org/wiki/Public_transport#Railways
[rail-station]: https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation
[tram-general]: https://wiki.openstreetmap.org/wiki/Public_transport#Trams
[subway-station]: https://wiki.openstreetmap.org/wiki/Tag:station%3Dsubway
[subway-platform]: https://wiki.openstreetmap.org/wiki/Metro_Mapping#Platform
[subway-stop]: https://wiki.openstreetmap.org/wiki/Metro_Mapping#Stop_Position

For bus stops, tagging the stop name on the platform is recommended, while tagging on the stop position is optional. For railways, tagging the name on the stop position (= on the track) is recommended, while tagging on the platform is either discouraged or optional. (The subway guidance on adding name to the platform looks to me like tagging for the renderer  - or editor, in this case.)

## Do platforms have a name on their own?

Typically, a railway platform is part of a named station, but does not have a name on its own. While the platform might have a sign with a name, this is probably the name of the *station* and not the *platform* itself.

At least for Germany, I personally don't know of railway *platforms* that have a name on their own. [This discussion](https://github.com/streetcomplete/StreetComplete/discussions/5145) seems to suggest this is also the case for the UK. Other countries might have conventions on how to use `name` (e.g. a combination of station name and platform number), but those seem more like `description` to me.

For bus stops, adding the station/stop name on the platform seems to be the preferred tagging scheme. This makes sense, because for bus stops, the station/stop is pretty much identical with the platform. For train stations, especially those with many platforms, this is not the case. Duplicating the station name on every platform (even if it does not have a name on its own) does not seem like a good practice in general, and is not in line with what the wiki says as well.

## Current SC behaviour

SC encourages adding a `name` to railway platforms anyway. For users unfamiliar with the tagging practices and wiki details described below, it is easy to think that, for instance, a sign pointing to the name of the station on the railway platform is the proper answer for that quest, while in most cases "has no name" would be the correct answer.

## Examples for problematic outcomes encouraged by SC

`name` on platform inconsistent with `name` on `stop_area`s:

- https://www.openstreetmap.org/way/1137279497
- https://www.openstreetmap.org/way/157634194

Found via [OSMcha](https://osmcha.org/?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222023-01-01%22%2C%22value%22%3A%222023-01-01%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Determine%20public%20transport%20stop%20names%22%2C%22value%22%3A%22Determine%20public%20transport%20stop%20names%22%7D%5D%2C%22modify__gte%22%3A%5B%7B%22label%22%3A%2210%22%2C%22value%22%3A%2210%22%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22StreetComplete%22%2C%22value%22%3A%22StreetComplete%22%7D%5D%7D)

[Unnecessary name labels on all platforms in a station](https://www.openstreetmap.org/way/834645016#map=18/48.14046/11.55634). See also [changeset/138591957](https://www.openstreetmap.org/changeset/138591957), which added all those names (no offense to the mapper!).

## Ideas how to handle this

- limit the  quest `AddBusStopName` to `highway=bus_stop` and create a separate quest for adding name to `public_transport=stop_position`s on `railway=...` ways
- Disable name quest on `railway=platform`s if the platform is a member of a `public_transport=stop_area` relation with a `public_transport=station` member
- Make the "has no name" option more prominent in the quest

**Open questions**

- My main experience with this are railway platforms in Germany. Are there other countries where railway platforms typically have a "real" name?
- Even though this is discouraged by the wiki, many railway platforms are  tagged with the station name regardless. How should SC handle this difference between wiki and established practice?

**Comment by rhhsm** [comment]
This should be considered for subway platforms too

**Comment by mnalis** [comment]
- (ref. related issue about duplicated info in similar situation: https://github.com/streetcomplete/StreetComplete/issues/5132)

**Comment by burrscurr** [comment]
I updated the issue description with a better overview over the different public transport types and how they handle tagging of platforms, stop positions and stations.

**Comment by westnordost** [comment]
Or actually, requiring `bus=yes` is going to be easier to maintain.

**Comment by burrscurr** [comment]
Thanks for addressing the issue and for the implementation.

I have one small possible addition: Can we also include tram stops (`railway=tram_stop`) in the query? The updated name quest currently does not apply to those, as they aren't `railway=station` or `railway=halt`s.

**Comment by riQQ** [comment]
Added in 5bf14bf2f8c07262aa291ebaafeec46b3ed45e15

**Comment by westnordost** [comment]
Public transport relations? Not sure if I understand you correctly. You want to skip the bus-stop-name-quest if it is a member of a relation that already has a name?

Hm, can you provide a link to the wiki that describes this? 

In any way, this should probably be a new ticket.

**Comment by Dimitar5555** [comment]
The quest is being asked for tram platforms with `tram=yes + bus=yes` is this intended? Maybe `tram=yes` platforms should be excluded?

Example for which the quest appears: https://www.openstreetmap.org/way/621942301
Example for which the quest appeared and was answered in the latest version (58.0): https://www.openstreetmap.org/way/1146015600/history

**Comment by westnordost** [comment]
Maybe it should, maybe it shouldn't. To make a decision, we need sources and numbers:

- what does the wiki suggest in that case?

- how much percent of `public_transport=platform + bus = yes + tram = yes` have names?

**Comment by Dimitar5555** [comment]
I've made a quick query. 91% of `public_transport=platform + bus=yes + tram=yes`.
```
[out:json][timeout:25];
nwr[public_transport=platform][tram=yes][bus=yes][!name]; //69+378+0=447
//nwr[public_transport=platform][tram=yes][bus=yes][name]; //1845+2672+20=4537
out count;
```

Sidenote: The data is skewed. Trams usually have their own `railway=tram_stop+public_transport=stop_position+name+etc...`. Buses on the other hand usually have platforms `highway=bus_stop+public_transport=platform+name+etc...`. When a bus and a tram share a stop, it's common to share the platform, but not the stop position since usually the buses drive on the road and not on the tracks. Even in cases where they drive on the tracks, they follow a road and if there is a bus stop position, it's on the road.

A possible simple solution would be to exclude `railway=platform`, regardless of other tags.

**Comment by westnordost** [comment]
Thanks!

But if 91% of these **do** have names, why do you want to change the quest, as it looks like common mapping practice then?
