### ISSUE TITLE
Video glitch

### ISSUE THREAD

**Issue by lcosmin** [streetcomplete/StreetComplete#5216]
[Video here](https://drive.google.com/file/d/1T69-6Dm7CfXKAEYpcS-xHytzqaSR-gZN/view?usp=drivesdk) 

**How to Reproduce**

I see it when using overlays, at the intersection of differently colored ways.

**Expected Behavior**

No glitch

**Versions affected**

Using StreetComplete 54.0 beta 1, Android 13, Samsung S20FE

**Comment by westnordost** [comment]
Yeah, I'd say this is an issue of tangram-es, the rendering library we use for the map whose development has been abandoned, so nothing we can do here.

**Comment by mnalis** [comment]
- (...apart from moving to another rendering library, like https://github.com/streetcomplete/StreetComplete/issues/3123)
