### ISSUE TITLE
Unclear barrier quest

### ISSUE THREAD

**Issue by kjonosm** [streetcomplete/StreetComplete#5218]
I just came around this [note](https://www.openstreetmap.org/note/3856450#map=11/52.4842/13.5139&layers=N) which I cannot resolve as the SC question seems not well tailored for this kind of barrier.

**How to Reproduce**
Find a `barrier=cycle_barrier` e.g. https://www.openstreetmap.org/node/1142432927

**Expected Behavior**
Exclude this kind of barrier from the SC quest.

**Versions affected**
53.3

**Comment by westnordost** [comment]
This is a quest that **specifically** asks for bicycle barriers and not any other barriers.

See https://wiki.openstreetmap.org/wiki/Key:cycle_barrier:installation

So, yes, whether it is openable or not, is a thing with bicycle barriers.

**Comment by westnordost** [comment]
Answered in the note.
