### ISSUE TITLE
Simplify `featureDictionaryFuture` interface in quests

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5219]
Currently, quests that want to use the feature dictionary, accept a `FutureTask<FeatureDictionary>`, e.g.

https://github.com/streetcomplete/StreetComplete/blob/80781a7f45cddf19223c46ed5ff1a35e3964bb0e/app/src/main/java/de/westnordost/streetcomplete/quests/QuestsModule.kt#L249

https://github.com/streetcomplete/StreetComplete/blob/80781a7f45cddf19223c46ed5ff1a35e3964bb0e/app/src/main/java/de/westnordost/streetcomplete/quests/amenity_cover/AddAmenityCover.kt#L16-L18

As suggested in https://github.com/streetcomplete/StreetComplete/pull/5212#issuecomment-1693484783 by @westnordost, this interface could be simplified to something like:

```kt
class MyQuest(private val getFeature: (tags: Map<String, String>) -> Feature?) { ... }
```

@qugebert Would you fancy giving it a try?

**Comment by westnordost** [comment]
@FloEdelmann there are lots of small things that could be slightly improved. It doesn't make sense to open issue tickets for all of those. A PR is welcome anyway.

**Comment by westnordost** [comment]
Regarding the feature dictionary, it's worth looking what other uses of the feature dictionary there are and whether it makes sense to simplify these, too.

(Did you pin the iOS ticket by mistake?)

**Comment by FloEdelmann** [comment]
> It doesn't make sense to open issue tickets for all of those.

Okay, I just thought I'd open an issue so that we don't forget it.

> Did you pin the iOS ticket by mistake?

No, I pinned it since it is a highly upvoted issue and contains many actionable tasks, to highlight it for contributors.

**Comment by qugebert** [comment]
Ich kanns schon versuchen, aber ich habe noch nicht ganz verstanden, was zu tun ist.

**Comment by westnordost** [comment]
> Ok, i can try this but i haven't really understood what i shall do.

Well, don't mind this then.

**Comment by qugebert** [comment]
> > Ok, i can try this but i haven't really understood what i shall do.
> 
> Well, don't mind this then.
Ok, I just didn't want to leave it unanswered, since I was addressed directly.
