### ISSUE TITLE
Ask if there's a fence between water and land

### ISSUE THREAD

**Issue by thany** [streetcomplete/StreetComplete#5221]
**Use case**
Where land meets water, for example at the edge of a pond or river or canal or moat or what have you, it's reasonably common for there to be some kind of fencing or barrier if a path is near enough and/or parallel to the water. Fences can be added to the map explicitly, but I'm not sure if they always should be.

Example of one such barrier: https://goo.gl/maps/eKc8R5kpbKYUshHD8
Example of a fence: https://goo.gl/maps/CtnwHU5eNLuQBiwP6
Something inbetween fence & barrier: https://goo.gl/maps/QXVwq4m9cc8Jryv27

**Proposed Solution**
In places where water meets land, ask if there's any physical barier or fence in between, and if so, add that to the map and present any additional quests that pertain to the newly added fence.

Now, I'm not sure if such fences *should* be mapped, but I feel like they ought to be. I'm no expert though.

**Comment by matkoniecz** [comment]
please open a new issue filling prepared template for a new quests

as it is stated it misses many fundamental properties needed, see https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md

This quest seems not implementable in StreetComplete for multiple reasons.

**Comment by mnalis** [comment]
As a workaround, one can always long click on a map, and leave a note (with a description and picture) there, to indicate there is missing fence, and then add it later in some full-fledged editor.
