### ISSUE TITLE
Wrong icon for the new overlay button on the main screen

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#5225]
**How to Reproduce**
Start SC v54.0. The new overlay button on the main screen shows the icon of the street surface quest instead of the correct one.

![Wrong_icon](https://github.com/streetcomplete/StreetComplete/assets/32601012/61ad4fae-c370-4962-97fc-765696061d4d)

**Expected Behavior**
The correct icon will be shown.

**Versions affected**
SC v54.0 on a Samsung tablet with Android 8.1. My other two Android devices (smartphones with Android 13 and 9 respectively) show the correct icon. I'm not sure if this happens because of the older Android version or the fact that it's a tablet computer.

The cycling cat

**Comment by FloEdelmann** [comment]
Probably the street surface overlay is currently activated?

**Comment by cyclingcat** [comment]
You're right. I must have accidentally activated it at some earlier time. (I rarely use StreetComplete on this device as I almost never carry it with me in the field.) So it's not a bug.

The cycling cat
