### ISSUE TITLE
Configurable changeset comment language

### ISSUE THREAD

**Issue by matheusmoreira** [streetcomplete/StreetComplete#5226]
**Use case**
Street Complete submits changesets with comments in the same language as the system language. I use English as the language on all my devices but I don't live in an English-speaking country. The result is changeset comments that may not be useful for other mappers.

**Proposed Solution**
Add a configuration setting to allow users to specify the language of the uploaded changeset comments independently of the language the app displays itself in.

**Comment by arrival-spring** [comment]
See #2581 and #5007 which were similar requests and were rejected.
