### ISSUE TITLE
Differentiate identically-named quest types

### ISSUE THREAD

**Issue by yaomtc** [streetcomplete/StreetComplete#5231]
There are three different quest types called "Is this place wheelchair accessible?" Two of them have the same icon in green, while the third is that same icon in orange.

Since it is not planned to combine these, they should be differentiated with a (parenthetical) or similar.

**Versions affected**
StreetComplete v53.3 on Android 13

**Comment by riQQ** [comment]
See #5075

**Comment by yaomtc** [comment]
Thanks! I've updated the report.

**Comment by yaomtc** [comment]
I didn't look at the code for this before, I did a search just now - it'd be more complicated to do this than I thought. Understandable.

**Comment by westnordost** [comment]
Oh, you did look through the code, cool!
