### ISSUE TITLE
Max height quest doesn't allow inputting two-digit height values

### ISSUE THREAD

**Issue by waldyrious** [streetcomplete/StreetComplete#5232]
I'm not sure if this is a regression of #3000 or a new issue altogether, but I am again unable to enter large height values (10m or more). This time it's not due to a limitation in the total number of characters (as was the case in #3000), but rather due to only being able to input a single digit before the decimal point.

Here's a screen recording of me hitting this limitation:

https://github.com/streetcomplete/StreetComplete/assets/478237/db48180b-3f51-4bb0-8461-67c5d1be17df

**Comment by waldyrious** [comment]
For additional context: Here in Portugal, it is quite common, at least in the North, to have extremely high "clearances" under highway bridges simply due to the geography of the terrain. Here are two notes I left due to being unable to enter the correct values in the app: [3865957](https://www.openstreetmap.org/note/3865957), [3865958](https://www.openstreetmap.org/note/3865958). For illustration [here's a Mapillary shot](https://www.mapillary.com/app/?lat=41.284097435318&lng=-8.2567562194753&z=17&pKey=4326783544021208&focus=photo) corresponding to the first note.

**Comment by matkoniecz** [comment]
> For illustration [here's a Mapillary shot](https://www.mapillary.com/app/?lat=41.284097435318&lng=-8.2567562194753&z=17&pKey=4326783544021208&focus=photo) corresponding to the first note.

Is there a sign there?

**Comment by waldyrious** [comment]
> Is there a height limit sign there?

Yes, of course — I couldn't obtain the height otherwise. It's here:

![image](https://github.com/streetcomplete/StreetComplete/assets/478237/2f175283-92fc-433f-b6a0-92e50101f94f)

Thanks for the quick fix, @westnordost!

**Comment by matkoniecz** [comment]
> Yes, of course — I couldn't obtain the height otherwise. It's here:

Oh, I completely missed it (even when pointed out on photo I cannot really read it). Thanks, that makes sense to me now!

**Comment by waldyrious** [comment]
> even when pointed out on photo I cannot really read it

Yeah, I can't read it from the photo either :) but that was just an old image I found to illustrate the situation. I surveyed the info directly as a passenger in a recent car trip that passed under that bridge.

**Comment by waldyrious** [comment]
For the record, there were a couple ways I added an incorrect maxheight to before I noticed this bug, in changeset https://www.openstreetmap.org/changeset/140555809. Fortunately someone alerted me to the implausible maxheights, and I removed them in https://www.openstreetmap.org/changeset/142592971.
