### ISSUE TITLE
Better vegetarian/vegan quest

### ISSUE THREAD

**Issue by fbarbe00** [streetcomplete/StreetComplete#5234]
When both the quest asking whether a place has vegetarian options and the quest for vegan options are enabled, show the vegan quest first, and if the answer is yes don't ask for vegetarian (since all vegan options are also vegetarian). Currently the vegetarian quest is shown first.
Alternatively, if you don't want to change the order, don't ask whether the place has vegan options if it doesn't have any vegetarian options.

**Comment by matkoniecz** [comment]
> don't ask whether the place has vegan options if it doesn't have any vegetarian options.

this is done already, as far as I know

**Comment by Helium314** [comment]
> this is done already, as far as I know

Except for ice cream shops, which are always assumed to sell vegetarian food.

**Comment by westnordost** [comment]
The current order and behavior is deliberate.

Whether a restaurant has vegetarian food or not is much easier to answer than whether it has vegan food or not. This is why that is asked first. If it does not have vegetarian food, it is not asked at all whether it has vegan food or not.
