### ISSUE TITLE
Inconsistent tags after changing `surface=compacted` to `surface=asphalt` on `grade2` `highway=track`

### ISSUE THREAD

**Issue by sjakobi** [streetcomplete/StreetComplete#5236]
See version 1 and 2 of [this `highway=track`](https://www.openstreetmap.org/way/1204707842/history). I think I initially split it off from https://www.openstreetmap.org/way/167985456 after noticing the asphalted section of the track. I _probably_ did this using the surface overlay. In version 2, I changed the `surface` from `compacted` to `asphalt`. This caused an inconsistency with the existing `tracktype=grade2`, which is generally used for unpaved surfaces.

**How to Reproduce**

I haven't tried to reproduce this yet.

**Expected Behavior**

I would have expected StreetComplete to delete the inconsistent `tracktype` and to present the `tracktype` task to the user. Alternatively, StreetComplete could automatically change the `tracktype` from `grade2` to `grade1`.

**Versions affected**

Android 11.
StreetComplete v53.3 _I think_.

**Comment by matkoniecz** [comment]
hmm, maybe StreetComplete should be more aggressive on deleting/complaining about mismatching tractype and surface when user made edit to either of them

(currently it detects some mismatches but it is not very aggressive to avoid complaining in loop about valid data)

**Comment by sjakobi** [comment]
> maybe StreetComplete should be more aggressive on deleting/complaining about mismatching tractype and surface when user made edit to either of them

 I agree. I think inconsistencies should be resolved as soon as possible. Otherwise they end up confusing users and become a time drain for the people who end up fixing them manually.

**Comment by matkoniecz** [comment]
#4105 #5133 #4863 were some major discussions specifically on this topic

**Comment by matkoniecz** [comment]
It seems OK to delete `tracktype=grade2` on changing `surface=compacted` to `surface=asphalt`

**Comment by rhhsm** [comment]
Unfortunately there are many interpretations of the meaning of `track_type` and thereby differences of opinion on what is an inconsistent tagging. If paved tracks are always `track_type=grade1`, why adding this tag at all?

**Comment by matkoniecz** [comment]
> If paved tracks are always track_type=grade1, why adding this tag at all?

Note that question here is about removing `tracktype=grade2` from road becoming tagged as paved.

**Comment by westnordost** [comment]
So, what's your opinion on this then, should `tracktype` be removed from roads that previously had anything but `grade1` but are tagged as paved? If so, should I assign this to you?

**Comment by sjakobi** [comment]
Thank you for fixing this, @matkoniecz! :)
