### ISSUE TITLE
Does this caravan area have a  water_point ? 

### ISSUE THREAD

**Issue by petitminion** [streetcomplete/StreetComplete#5238]
This is a proposition to tag objects tagged with this tag : [caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site)

### General
Affected tag(s) to be modified/added:   [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point)
Question asked: **Does this caravan area have a  [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point)?**
response : yes/no 

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ x ] 🚧 To be added tag is established and has a useful purpose
- [ x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ x ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ x ] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by qugebert** [comment]
Could we extend this one?
https://github.com/streetcomplete/StreetComplete/blob/3b074e1d077aad25071e9773f6471b2490077869/app/src/main/java/de/westnordost/streetcomplete/quests/camping/AddCampDrinkingWater.kt

But it uses the 'drinking_water' tag, not water_point

**Comment by petitminion** [comment]
I'm not very experienced with osm tags, but I suppose has the wiki said we should use [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point) for [caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site) it would be better to stick to it. 

[water_point](https://wiki.openstreetmap.org/wiki/Key:water_point) include drinking_water.

**Comment by matkoniecz** [comment]
> Does this caravan area have a water_point?

At least for me this question would be unclear and I would be confused.

**Comment by petitminion** [comment]
> At least for me this question would be unclear and I would be confused.

Indeed. `can we fill water tanks in this caravan/motorhomes area  ? ` would be better ? 

Do you know, if we tag an object with [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point) does it get tagged with  drinking_water automatically ? If not I think we should had the tag  drinking_water at the same moment.

**Comment by westnordost** [comment]
I think @qugebert 's suggestion is the best. Just extend the other quest and tag `drinking_water`, not `water_point`. They seem to be synonymous for caravan sites, anyway.
