### ISSUE TITLE
Does this caravan area have a power_supply ? 

### ISSUE THREAD

**Issue by petitminion** [streetcomplete/StreetComplete#5239]
This is a proposition to tag objects tagged with this tag : [caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site)

### General
Affected tag(s) to be modified/added:   [power_supply](https://wiki.openstreetmap.org/wiki/Key:power_supply)
Question asked: **Does this caravan area have a  [power_supply](https://wiki.openstreetmap.org/wiki/Key:power_supply)?**
response : yes/no/type

a list of `type` can be found here : https://wiki.openstreetmap.org/wiki/Key:socket
Maybe this quest could only allow to respond yes or no. And then we create a second quest to define the type of socket ? 

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ x ] 🚧 To be added tag is established and has a useful purpose
- [ x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ x ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ x ] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by qugebert** [comment]
How about extending the existing quest for camping sites? (just adding caravan_site to the element selection)
[app/src/main/java/de/westnordost/streetcomplete/quests/camping/AddCampPower.kt](https://github.com/streetcomplete/StreetComplete/blob/3b074e1d077aad25071e9773f6471b2490077869/app/src/main/java/de/westnordost/streetcomplete/quests/camping/AddCampPower.kt#L4)

If it is easily answerable by any pedestrian from the outside but a survey is necessary at camping sites, why not at caravan sites which are more likely public accessible for pedestrians.

**Comment by petitminion** [comment]
yes it suppose it works great o/ We only need to conditionally format the text to the camp type variables o/
