### ISSUE TITLE
Shop overlay, existence quests etc.: Include clubs

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5244]
Clubs, for example chess clubs, culture clubs, fishing clubs, freemasons etc. etc. are often situated in a rental that could otherwise be a shop or office. Hence, it would make sense to include them in the `isShopExpressionFragment` code.

@mnalis that would mean that maybe your list of things that should be changed if the place changes must be updated too.

**Comment by mnalis** [comment]
@westnordost `club` is already present in `KEYS_THAT_SHOULD_BE_REMOVED_WHEN_SHOP_IS_REPLACED`:

https://github.com/streetcomplete/StreetComplete/blob/c2d325e67a0eb0b90bea4802ff937bdcda6a46d9/app/src/main/java/de/westnordost/streetcomplete/osm/Shop.kt#L81

so if I understand it correctly, no further change is needed there?

**Comment by matkoniecz** [comment]
@mnalis I though that it is about fetching common tags used by `club=` and not used by other shoplike objects (maybe there is `club_theme` or something not used by shops)

Should we update https://github.com/mnalis/StreetComplete-taginfo-categorize/blob/master/Makefile#L3 to find common tags used by clubs?

**Comment by mnalis** [comment]
(Those are included now with https://github.com/streetcomplete/StreetComplete/pull/5501)
