### ISSUE TITLE
Add Quest for tower:construction (affects: man_made=mast; man_made=tower; man_made=communications_tower)

### ISSUE THREAD

**Issue by gdprdatasubect** [streetcomplete/StreetComplete#5251]
### General
Affected tag(s) to be modified/added: [Masts](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast), [Towers](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower), [Big towers](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcommunications_tower)
Question asked: **What kind of tower/mast is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
  - `tower:construction` is already established and useful e.g. for emergency ("what do you see around you?") and navigation
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  - When `tower:construction`  is set, the quest is fulfilled
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  - Sometimes Sat-Images don't have the necessary resolutions to see shadows
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  - There is quite a bit of variety in regards to the construction of towers
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
  - Differs a lot between regions and the mappers that are active there, see for example http://overpass-turbo.eu/s/1AuH

### Ideas for implementation

**Element selection:** 
Select all `man_made=mast`, `man_made=tower` and  `man_made=communications_tower` where `tower:construction` is not set

**Proposed UI:** Image-Based selection, similar to road-surfaces etc.

**Comment by mnalis** [comment]
Um, are you sure `What kind of tower/mast is this?` would be the ideal question for setting [tower:construction=*]( https://wiki.openstreetmap.org/wiki/Key:tower:construction)? To me answers to that question would be things like `communication tower`, `power tower`, `aerialway pylon` etc. 

`tower:construction` seems to be more about architectural design of the tower as far as I can tell.

**Comment by westnordost** [comment]
Hm, for me, all the masts on the respective wiki page look the same. Also, for towers, the values are somewhat odd. Is it about the tower, or what is on top? You know, because of the value `dome`, `dish`, ....

So, in this regard...

>> 🚧 To be added tag is established and has a useful purpose 

> tower:construction is already established and useful e.g. for emergency ("what do you see around you?") and navigation

I do not find this convincing. The presence of telecommunication masts yes, but how specifically they were constructed? I don't think so.

**Comment by mnalis** [comment]
> Also, for towers, the values are somewhat odd

yeah, key/value names are sometimes strange in OSM. But as we're are only about using this (well documented and wildly used) tag (and not proposing its renaming), I don't think it should concern us here (we could go all the way back to complaining that `highway=traffic_signals` is even more odd)

> I do not find this convincing. The presence of telecommunication masts yes, but how specifically they were constructed? I don't think so.

Some values might, e.g. `tower:construction=dish` is likely rarer and more telling than `tower:construction=lattice`.

But yeah, while I personally have never been lost enough that people asked me to describe construction type of the tower in the middle of nowhere, still there is more than [110k uses of tower:construction](https://wiki.openstreetmap.org/wiki/Key:tower:construction), so I'd say it does seem to tell that reasonably many people _do care_ about that tag enough. (The fact that I personally might not be interested in towers at all should thus not be given too much weight)

Still, if included, I guess it might be disabled by default, as average SC user is probably not going to see the utility of that quest... (then again, towers are not all that common, so having it enabled by default might be fine too, like we have for other rare quests of questionable in-real-life usefulness like `What's the structure of this bridge?`)
