### ISSUE TITLE
Dark theme colors too similar

### ISSUE THREAD

**Issue by dispread** [streetcomplete/StreetComplete#5252]
In dark mode it's hard to distinguish between normal land and greenery, especially when I'm out surveying. Can there be something done about this? Thanks.
![Screenshot_20230916_150159_StreetComplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/107815346/dd639c4b-ab46-4c5a-84ff-ff819c7a37c2)

![Screenshot_20230916_150150_StreetComplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/107815346/7d1bcafa-e90b-440c-b2ba-9acb36ab44a2)

**Comment by CTJoriginal** [comment]
We could use theme similar to "Dark (increased contrast)" from SCEE
![20230916_160330](https://github.com/streetcomplete/StreetComplete/assets/48687492/1c91dc7a-f3e8-488d-9f53-aa3433591780)

**Comment by westnordost** [comment]
Something like this was attempted. See https://github.com/streetcomplete/streetcomplete-mapstyle/pull/141

Feel free to read through it and try some variations yourself. The branch still exists.
