### ISSUE TITLE
Support locating storm inlets

### ISSUE THREAD

**Issue by CartoonFan** [streetcomplete/StreetComplete#5253]
**Use case**

Where I live, the storm drains often get quickly clogged with trash and leaves during the rainy season, causing water to gather around pedestrian crossings. This makes crossing the street more difficult than it needs to be, and sometimes the drains aren't easy to locate (water level, distance from the crossing, etc.), so it'd be helpful to have them on the map.

I'm not sure if this is the right place (or app) for this, though, so please feel free to point me in the right direction if it's not.

**Proposed Solution**

OSM already supports the manhole=drain (https://wiki.openstreetmap.org/wiki/Tag:manhole%3Ddrain) and inlet=kerb_opening (https://wiki.openstreetmap.org/wiki/Tag:inlet%3Dkerb_opening) tags, so I suppose you could just ask the user what kind of drain is at the location. The initial work of finding the drains might still need a different app, though.

Anyway, that's all I have at the moment. I just started using the app a few days ago, and it's been pretty fun so far! :grin:

**Comment by Helium314** [comment]
I guess your best chance would be asking to have them included in the proposed street furniture overlay #4912

**Comment by CartoonFan** [comment]
> I guess your best chance would be asking to have them included in the proposed street furniture overlay #4912

Thanks. Wouldn't have expected it to be grouped with furniture, but I'll check it out :+1:

**Comment by mnalis** [comment]
> so I suppose you could just ask the user what kind of drain is at the location. 

I'm not sure what exactly do you mean by _"what kind of drain is at the location"_? 

I'm guessing you mean a Quest which would trigger on `man_made=manhole or inlet=kerb_opening`. But do you envision as the answers to that question, and what each answer would add as a tag? (if I understood your intention correctly).

> The initial work of finding the drains might still need a different app, though.

As noted above, part of the suggestion for initially adding them to the map via street furniture overlay seems reasonable to me. 

Note that _prerequisite_ for that would be that this tag is already supported by [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema), which is used by several different applications (obviously [iD](https://wiki.openstreetmap.org/wiki/ID), but also StreetComplete and [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door)):
- `man_made=manhole` is already [supported](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/manhole.json), so this only needs approval in StreetComplete (and implementation of https://github.com/streetcomplete/StreetComplete/issues/4912 which might take some time -- you can try Every Door for adding them on mobile in the meantime)
- however, `inlet=kerb_opening` is not yet supported, so you would need to [request it there](https://github.com/openstreetmap/id-tagging-schema/issues) before it can be implemented in StreetComplete.

**Comment by CartoonFan** [comment]
> > so I suppose you could just ask the user what kind of drain is at the location.
> 
> I'm not sure what exactly do you mean by _"what kind of drain is at the location"_?
> 
> I'm guessing you mean a Quest which would trigger on `man_made=manhole or inlet=kerb_opening`. But do you envision as the answers to that question, and what each answer would add as a tag? (if I understood your intention correctly).

Unfortunately, I'm not really sure, myself. My best guess (after reading your comment) would be to ask the user about the type of inlet, as a Quest, once an inlet has been specified at the location (likely through another app, as you mentioned below). Is there some sort of generic inlet tag that would work as a placeholder?

> > The initial work of finding the drains might still need a different app, though.
> 
> As noted above, part of the suggestion for initially adding them to the map via street furniture overlay seems reasonable to me.
> 
> Note that _prerequisite_ for that would be that this tag is already supported by [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema), which is used by several different applications (obviously [iD](https://wiki.openstreetmap.org/wiki/ID), but also StreetComplete and [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door)):
> 
>     * `man_made=manhole` is already [supported](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/manhole.json?rgh-link-date=2023-09-17T12%3A34%3A37Z), so this only needs approval in StreetComplete (and implementation of [Overlay for street furniture (etc.) #4912](https://github.com/streetcomplete/StreetComplete/issues/4912) which might take some time -- you can try Every Door for adding them on mobile in the meantime)
> 
>     * however, `inlet=kerb_opening` is not yet supported, so you would need to [request it there](https://github.com/openstreetmap/id-tagging-schema/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) before it can be implemented in StreetComplete.

I'll try Every Door with it, and see how that works. Hopefully, I'll also find the time to let id-tagging-schema know about my request.

Thanks for your reply! :purple_heart: :pray:

**Comment by westnordost** [comment]
Well, it looks like you want to get storm inlets on the map. However, STreetComplete is not an app to get things on the map, but to add information to things already on the map. Primarily. This is certainly something that may go into a future "street furniture" overlay and I see you already added a note there.

For the time being, I think you are well served with Every Door.
