### ISSUE TITLE
App fails to download data in particular area of Santiago, Chile

### ISSUE THREAD

**Issue by draeklae** [streetcomplete/StreetComplete#5254]
The app consistently fails to download quests near Cerro Santa Lucia in Santiago, Chile with the message "Connection error while downloading data. Try again later." The whole area around it is fine, but there is a particular section of the map which always fails.

Here is a screenshot of the affected area: [https://imgur.com/a/q3YE21J](https://imgur.com/a/q3YE21J)

**How to Reproduce**
Zoom in to affected area, press sandwich menu and "Download data here"

**Expected Behavior**
Data is downloaded.

**Versions affected**
SC 54.0 on Android 12

**Comment by matkoniecz** [comment]
may be  #5181

**Comment by matkoniecz** [comment]
yep, this one, should be fixed in the next version
