### ISSUE TITLE
Trace Upload Note Captures Current Location Instead of Trace Location

### ISSUE THREAD

**Issue by ljdelight** [streetcomplete/StreetComplete#5256]
**Use case**
I started a trace and then started a drive. I stopped the trace but couldn't fill out the upload details right away. When I did, the Note used my current location, not the location related to the trace.

**Proposed Solution**
To resolve this issue, the Note should capture  the coordinates relevant to the trace itself, rather than the user's current location at the time of completing the upload details.

**Comment by westnordost** [comment]
The note uses the current location, yes, or actually, the location you select via long-press. The trace is "attached to" (actually: linked to from) the note.
