### ISSUE TITLE
Login/app authorization doesn't work

### ISSUE THREAD

**Issue by Makdaam** [streetcomplete/StreetComplete#5258]
The application "forgets" the authorization I've already given to my OSM Profile.

**How to Reproduce**
1. Run application.
2. Provide information about a map feature/complete a quest.
3. App complains it needs access to an OSM user account and asks to do it now (OK) or later (Later)
4. Click OK, log into the OSM profile, click Grant Access with 4 permissions turned on
5. Profile screen appears with my account name, 0 stars and 3 queued changes (as expected)
6. click the back arrow near the top left corner to get back to map view.
7. Go to 3.

After every execution of step 4. there's a new app authorization in my OSM Profile settings > Oauth 1 authorizations. So it looks like the client doesn't remember its oauth data. Restarting the app doesn't resolve the issue.

**Expected Behavior**
After step 6. the map view should appear and the queued changes should be submitted instead of a pop-up asking to log in again.

**Versions affected**
SC v54.0, Android 13

**Comment by westnordost** [comment]
Can you login normally on osm.org?

**Comment by Makdaam** [comment]
Yes, I have normal access to osm.org.

**Comment by Makdaam** [comment]
Not a bug, might be an RFE for a clearer error message, but probably doesn't affect many people.

**Comment by westnordost** [comment]
Unfortunately, the HTTP error code of the OSM API for trying to upload changes without authorization is the same as the error code when you are not allowed to do any edits, as far as I know.
