### ISSUE TITLE
Allow to upload all as one changeset

### ISSUE THREAD

**Issue by cd-FileX** [streetcomplete/StreetComplete#5260]
**Use case**

I currently got ~170 Changes I need to sync all as single changes. The upload as one change set (I think that's what it's called, just one commit-like with many changes) would be quicker and much more nice to view in the history of a user I think.

**Proposed Solution**

- Add a setting that allows to upload all currently not uploaded changes as one changeset
- Let the user group changes and upload them
- Automatically group changes of the same or similar type and upload them as one changeset

**Comment by HolgerJeromin** [comment]
This was discussed and rejected many times:
#3096 #2498 #21

**Comment by cd-FileX** [comment]
Ah, sorry. I only searched for open issues.
