### ISSUE TITLE
Plant classification + API

### ISSUE THREAD

**Issue by Sythelux** [streetcomplete/StreetComplete#5279]
**Use case**
I would like have quests for trees and bushes as I need them for a project especially (species, height, crown diameter and trunk thickness), as far as I know OSM needs the latin classification name, which you can set in SCEE, but I don't always have in mind, therefore I'm currently using Flora Incognita to classify and then copy the name.

**Proposed Solution**
Today I asked flora incognita for integration to StreetComplete on mastodon, which I got the answer, that there is an API and they can be contacted about it ([original toot in German](https://wisskomm.social/@FloraIncognita_DE/111136513980899492)).

So I imagine, similar to the street distance app being and extra app now, there could be a way to open flora incognita temporary for the quest "which tree species is this" which you can then use to specify and then SC pulls an answer from the API.

**Caveats**
I know that this would mean, that StreetComplete then relies on an external App and API, that it doesn't have control over, but maybe there is a way?

**Comment by westnordost** [comment]
I think this would generally be possible albeit somewhat of a precedence (relying on an external api, relying on an external app).

However, if you need something now, there is the [MapComplete Trees Theme](https://mapcomplete.org/trees.html) which seems to be pretty much exactly what you are looking for, including API support of PlantNet. Since this theme exists, to me it seems less meaningful to basically implement pretty much the same in this app as everyone who is interested in this topic could just use that theme.

**Comment by Helium314** [comment]
> OSM needs the latin classification name, which you can set in SCEE, but I don't always have in mind

See the description when you enable the quest in SCEE:
_You can provide suggestions from your own list of species with searchable names by providing a file in the data management settings menu, containing `<species> (<name>)`._
You can provide a file containing lines like `Quercus robur (pedunculate oak)` and then search for either the species or the name you have defined.

**Comment by Sythelux** [comment]
> I think this would generally be possible albeit somewhat of a precedence (relying on an external api, relying on an external app).
> 
> However, if you need something now, there is the [MapComplete Trees Theme](https://mapcomplete.org/trees.html) which seems to be pretty much exactly what you are looking for, including API support of PlantNet. Since this theme exists, to me it seems less meaningful to basically implement pretty much the same in this app as everyone who is interested in this topic could just use that theme.

Thank you. Well I would use MapComplete, but I really would like to use StreetComplete for it. It somehow is a very cool experience to run around with my little brother and answer those questions. I think before opening MapComplete I have Flora Incognita open in the back and copy the detected name, that is seemingly faster.

I'm not sure if a possible approach would be to have a "Plant companion app", like the street measure app and have PlantNet and Flora Incognita integration there and configurable. So StreetComplete would have a steady API and API changes in extra apps can be solved in the other repo.

**Comment by Sythelux** [comment]
> > OSM needs the latin classification name, which you can set in SCEE, but I don't always have in mind
> 
> See the description when you enable the quest in SCEE: _You can provide suggestions from your own list of species with searchable names by providing a file in the data management settings menu, containing `<species> (<name>)`._ You can provide a file containing lines like `Quercus robur (pedunculate oak)` and then search for either the species or the name you have defined.

Thank you for the suggestion. I can't provide a file, as I don't know what plants I encounter, when I walk through my City... like I don't actually now my domestic names of those plants. I use the combination of SC/SCEE and Flora Incognita also, because I want to learn the Species we have here. So an integration with a Plant Reconition app would be rather important.

**Comment by westnordost** [comment]
Do you know or would you be able to find out if the Flora Incognita or PlantNet app can be called from another app like the camera can? I.e. call the app and ask it to classify a plant, then return the result to the calling app? This would make implementation of such a quest / overlay much easier. (It would also not require the camera permission)

**Comment by Sythelux** [comment]
I'll send them a mail as they suggested on mastodon.

**Comment by westnordost** [comment]
Well, I guess there must be. MapComplete also does this, I am sure.

Anyway, I will close this issue as answered, as it was more of a question anyway:

Yes, it would be possible to create an overlay for tree classification and/but feature-wise, it would be very similar to the mentioned MapComplete Trees theme, so I do not really see the need for such an overlay. I still would accept a PR for this, but at the moment don't plan to work on this myself.
