### ISSUE TITLE
Improve selection of ways in overlays

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5282]
**Use case**
I often find it hard to select ways (roads, paths, etc.) for editing in the relevant overlays: it often takes many attempts and zooming in strongly to be able to select a way, apparently because the selection area is very narrow at low zoom levels. This can be especially irritating when surveying from a fast moving vehicle: in the time it takes to select a way, many other opportunities for adding data to the map are missed. Is that because of a combination of my thick fingers and my phone (LG Q60) or is that the experience of others too?

**Proposed Solution**
I wonder if it is possible to widen the selection area of ways so that the chance of hitting the one you want when tapping on the screen increases. Of course that would also increase the chance of selecting the wrong one when the density of ways is high, so it is a matter of finding an optimum. However this is also an issue when selecting nodes for splitting a way, so maybe the dialogue asking to zoom in when there are several nodes (ways) close to each other can be used.

**Comment by westnordost** [comment]
Hmm, I am not sure this is possible. The click area of elements is as big as how big the elements are displayed.

**Comment by westnordost** [comment]
Hmm, there is `setPickRadius` for the tangram map controller

**Comment by westnordost** [comment]
I've experimented with different values, and 8px still feel okay. Anything larger may feel like a bug. I've increased the pick radius from 1px to 8px.

In the end, you can always zoom in further if you are unable to tap the road.
