### ISSUE TITLE
wrong question about clearance height at level railway crossings

### ISSUE THREAD

**Issue by ownhardy** [streetcomplete/StreetComplete#5291]
I have observed with several level railway crossings that StreetComplete asks me about the clearance height there.

**How to Reproduce**
Go to a place where a level railway crossing is. I observed this for example at a 
* point with the following properties
   crossing:barrier=half
   crossing:light=yes
   railway=level_crossing
* where the crossing railway has the following properties:
   railway=rail
   tracks=1
   usage=main
* and the crossing street has:
   highway=path
   surface=asphalt
but I have also seen this with a
    highway=secondary

**Expected Behavior**
To my understanding at a point with "railway=level_crossing" the StreetComplete App should never ask for the clearance height. Normally there is hundreds of meters of free air above a level crossing.

**Versions affected**
Observed with StreetComplete V54.1, I have not observed this behavior with earlier versions. I use the app on a (quite old) Android phone.

**Comment by matkoniecz** [comment]
See #5180 #5223

> Normally there is hundreds of meters of free air above a level crossing.

Is there any indication on railway in OSM that it is not electrified?

**Comment by matkoniecz** [comment]
>  highway=path

That likely should be `railway=crossing` not `railway=level_crossing`

**Comment by ownhardy** [comment]
Oh yes, now I see what could be ment with this question. There is only limited space between the street and and electric wires on top of the railways. Sorry, this just didn't come to my mind before. (The railway crossings, where I observed this, do have electricity on top.)
But isn't this standardized? Shouldn't there be perfectly the same "clearance" height at every single railway crossing in one country? Otherwise the trains couldn't use these electricity wires properly, could they?
Maybe a better question for Street Complete would be something like: "Are there electricity lines above the railway at this crossing?" -> yes/no. And if a value in meters is needed in OSM, maybe Street Complete could then note the normal clearance value of this country in the OSM data.

**Comment by westnordost** [comment]
The quest is only asked for railway crossings of railways that **are** electrified with overhead wires. It is not asked on any other railway crossing.

Whether the railway is electrified with overhead wires is tagged on the railway line, not on the crossing. While it would be possible to create a quest that asks for this and tags it accordingly, it would then only be tagged on the piece of railway line that intersects with the crossing. So, in other words, it would be really somewhat incomplete mapping. Hence, I do not think such a quest would make sense. 

Isn't it standardized? Maybe, but, well, look at the linked issues. We already discussed this. There **are** railway crossings with a lower max height, and there **are** railway crossings whose max height are signed, see

https://community.openstreetmap.org/t/streetcomplete-fragt-bei-eisenbahn-weg-kreuzung-nach-durchfahrtshohe/103606/5

And for those that are not signed, it is quick and easy to answer that they are not signed.
