### ISSUE TITLE
Question for maxheight is asked over and over again

### ISSUE THREAD

**Issue by joergRossdeutscher** [streetcomplete/StreetComplete#5292]
I have a large amount of nodes where the question “Was ist die Durchfahrtshöhe hier?“ is repeated endless (personal raw translation: “What is the max height for driving through here?“)

I counterchecked that nodes in Vespucci. They already have attributes like:
highway=service
surface=wood
tunnel=building_passage
**maxheight=4
maxheight:sign = no**

In my opinion that data is already fine, correct and complete. SC shouldn't ask here at all.

If I delete both of the maxheight related attributes, I am asked only one question and it's done. Looks like combining both of them triggers the issue.

This is the case since the latest release, and I saw it was worked on some (max_)height-related features.

**How to Reproduce**
See node 340404170 (August-Kirch-Str. 17, Hamburg, Germany) as an example, but basically my “hood“ is plastered with a lot examples. See attached screenshot showing 53.567066 , 9.905047

**Expected Behavior**
I'd expect to not being asked that at all, because data looks already fine.

**Versions affected**
SC v.54.1

![SCR-20231004-lbty](https://github.com/streetcomplete/StreetComplete/assets/7712825/c526746a-a479-4317-9dc3-a2ddd266e2af)

**Comment by westnordost** [comment]
That very much looks like a bug. Will try to reproduce with https://www.openstreetmap.org/way/340404170

**Comment by westnordost** [comment]
Right, got introduced through this commit: https://github.com/streetcomplete/StreetComplete/commit/3693f9cab7e097b1f5a838de0357e5f436dd6fe2
