### ISSUE TITLE
Quest suggestion: what payment methods can you use at this vending machine?

### ISSUE THREAD

**Issue by WebFreak001** [streetcomplete/StreetComplete#5293]
### General
Affected tag(s) to be modified/added: [payment:*=](https://wiki.openstreetmap.org/wiki/Key:payment:*)
Question asked: **What payment methods can you use at this vending machine?**
or **Does this vending machine accept cash / cards / electronic purses (which ones?)**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose: if you are looking for vending machines with card payments or cash payments only in your area, you can use this
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one): possible if each payment type is its own quest
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary: usually written on the vending machine
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam): at least card payment is not always supported, cash may on the other hand not be supported on some kinds of vending machines, and some vending machines take coins only (like coin lockers)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort): lots of vending machines exist in all places, seen a lot in Germany and Japan that this would apply to

### Ideas for implementation

**Element selection:** 

For some things like electronic purses, the wiki suggests to put in which ones specifically, so it would need to show a list of electronic purses / providers for the current country and offer a fallback to a generic electronic_purses=yes if unknown (which can still show as a quest for others)

When asking for cash, the users should have an option to say yes/no or coins/notes only.

**Metadata needed:** 

payment methods can be very specific to the countries, see linked wiki page above.

**Proposed UI:**

**Comment by matkoniecz** [comment]
superset of #3923

**Comment by westnordost** [comment]
Hmm, I will close this ticket in favour of #3923 then. It may be a subset of what is proposed here, but if what is suggested here is implemented at all, it would be either part of #3923 or be an extension of what has been implemented for #3923. 

Also, if #3923 is extended, we should be cautious for which vending machines it is extended. We do not want to end up asking whether you can use your card on gumball machines.
