### ISSUE TITLE
New Quest: Building and Roof Materials

### ISSUE THREAD

**Issue by Claurt07** [streetcomplete/StreetComplete#5295]
### General
Affected tag(s) to be modified/added: [building:material](https://wiki.openstreetmap.org/wiki/Key:building:material) and [roof:material](https://wiki.openstreetmap.org/wiki/Key:roof:material)
Question asked: **What is the main material of the facade/walls?** and **What is the main material of the roof?**

Understanding the materials used in a building is essential for city planners, historic preservation efforts, emergency services like firemen, disaster management agencies, humanitarian response agencies, preparedness planning, etc. as it is a key indicator to understand the vulnerability of an area to different types of hazards. 
Verifying the material of the roof or the facade can be done with accuracy by most people, as it is visible from the street -- it's not much different than assessing the surface of roads which is already available as a quest. 

Note: More complex [building:walls](https://wiki.openstreetmap.org/wiki/Key:building:walls) and [building:structure](https://wiki.openstreetmap.org/wiki/Key:building:structure) require a higher degree of expertise and can hardly be assessed as you walk, so this is why I propose the former tags instead. 

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

Selecting all polygons:
`  way["building"]({{bbox}});
  relation["building"]({{bbox}});`
Note: This would leave out building-like structures under "man_made" or similar Keys that are suitable for this combination, but will help avoid elements that are not suitable in combination with the proposed tags (eg.- towers, antennas, bridges). 

**Metadata needed:** 
None? Some building materials might be more common in different areas and the colloquial terms might differ, but confusion can be minimized by using photographs on the UI (eg.0as currently displayed on the app for the road surfaces quest).

**Proposed UI:**

Using the most popular values from the wiki pages [building:materia](https://wiki.openstreetmap.org/wiki/Key:building:material) and [roof:material](https://wiki.openstreetmap.org/wiki/Key:roof:material) and having the UI as a grid with pictures, similar to the one used for surface material. This is also a good opportunity to avoid the incorrect values that are popular such as "timber_framing" or "masonry".

<html>
<body>

Select one: |   |  
-- | -- | --
 ![cement_block](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Hormig%C3%B3n_re-interpretado.jpg/150px-Hormig%C3%B3n_re-interpretado.jpg)  <br>Cement Block | ![Brick](https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Arvika_10skift_munkforband2_cropped.jpg/200px-Arvika_10skift_munkforband2_cropped.jpg) <br> Brick | ![plaster](https://wiki.openstreetmap.org/w/images/thumb/6/66/Plaster.png/200px-Plaster.png) <br> Plaster
![wood](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Valley_Forge_cabin.jpg/200px-Valley_Forge_cabin.jpg) <br> wood | ![concrete](https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Beobachtungstuerme_in_Fort_St._Elmo.jpg/200px-Beobachtungstuerme_in_Fort_St._Elmo.jpg) <br> concrete | ![steel](https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Former_Main_Roads_Migrant_Camp_in_Narrogin%2C_Western_Australia_%28exterior%29.jpg/200px-Former_Main_Roads_Migrant_Camp_in_Narrogin%2C_Western_Australia_%28exterior%29.jpg) <br> Steel
![Plastic](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Donaldson_Futuro_08-20-2012.jpg/200px-Donaldson_Futuro_08-20-2012.jpg) <br>  Plastic | ![stone](https://wiki.openstreetmap.org/w/images/thumb/c/cb/Stoneront.png/189px-Stoneront.png) <br> Stone | ![glass](https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Limestor_in_Dalkingen.jpg/200px-Limestor_in_Dalkingen.jpg) <br> glass
![mud](https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Mud_houses_are_commonly_found_in_various_regions_of_Afghanistan.jpg/200px-Mud_houses_are_commonly_found_in_various_regions_of_Afghanistan.jpg) <br> Mud | ![tin](https://4.bp.blogspot.com/_8R4LNN2EUCQ/TDHu_qFyq5I/AAAAAAAABN0/eWvEC1E7f7g/s400/DSC_7974_e.jpg) <br> Tin | ![reed](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Uros_Indian_woman_at_work_on_a_totora_island_in_the_titicace_lake_in_Peru.jpg/200px-Uros_Indian_woman_at_work_on_a_totora_island_in_the_titicace_lake_in_Peru.jpg) <br> Reed

</body>
</html>

Note: The UI for roof materials would look similar but with the values on [roof:material](https://wiki.openstreetmap.org/wiki/Key:roof:material)

**Comment by westnordost** [comment]
Wow, that tin house surely has some Fallout vibe going on, wouldn't have though that such tings exist in reality. https://duckduckgo.com/?q=fallout+4+junk+house&t=ffab&iar=images&iax=images&ia=images

Also, I find `building:material` a hilariously badly defined tag - so a `building:material=plaster` house is made of plaster? 😜 ... so no, it is about the surface of the walls of the house, so even the key name is quite misleading. And since it is about the building wall surface and not the actual building wall material, it is really a somewhat useless information to record.

But anyway, I already rejected this quest in the linked tickets.

**Comment by Claurt07** [comment]
Hello, those "fallout" houses unfortunately exist, but most times get overlooked, and there are few easy ways to map them so they are largely unrepresented-- hence this post. 
I agree the tag is misleading, but the good part of having something like StreetComplete is people mapping won't see that tag, but only a question and some values right? :) 

Building:material=plaster is house made of plaster? no, but but the materials used on the facade can be a good indicator as to what lies below (most likely masonry). Plus, most wood buildings wont be covered in plaster, neither the adobe houses or glass houses or tin. 

For roof:material the same, it is really valuable to have information especially on tin, glass and thatch roofs. 

But anyway, thanks for taking the time to develop and maintain such a great app and reading my post.

**Comment by matkoniecz** [comment]
>  I agree the tag is misleading, but the good part of having something like StreetComplete is people mapping won't see that tag, but only a question and some values right? :)

At some level sufficiently broken tagging scheme will not be supported by editors. I think this one reached this point.

(though this one was rejected already in general, see https://github.com/streetcomplete/StreetComplete/issues/1358#issuecomment-475990007 )

**Comment by Claurt07** [comment]
@matkoniecz Not fixated in any particular tag thats what I was trying to get at, but then its concerning to see how popular this one is (with an upward trend) -- it shows a gap as a lot of people are trying to map this and more people might be misled like I was. 

What would be the best way forward or what do you recommend? I want to try and contribute to this "issue". 

1. Propose/explore better tag to identify the surface material of a building and roof material? 
2. or you think the idea itself is bad and has no place in OSM? 

Obviously not an expert, but I guess popular editors can help revert trends on tagging or set new ones -- so I understand the concern. 
Thank you for giving me your opinion if you have time or refer me to the appropriate channel to continuing this discussion :)

**Comment by matkoniecz** [comment]
This case may be a bit stuck with 

group opposing deprecation of widely used tag

group refusing to use it due to heavily misleading name

I would try to invent more fitting name and try to convince people to migrate to it (if I would care about tagging this kind of info).

> or you think the idea itself is bad and has no place in OSM?

no, it seems OK to tag it (though personally I am not planning to either tag or use this data)

**Comment by westnordost** [comment]
Well, the root problem is verifiability, is it not? It very well may be that these tags started out to mean actually the building wall material and not the building wall surface material. But if it is not visible from the outside, what then? Or worse, you see e.g. bricks, but that's just facework and underneath you have concrete. There is not really any way an OSM surveyor can reliably collect this information.

**Comment by Claurt07** [comment]
Thank you for sharing your thoughts, this is really helpful for me to see different sides --
I guess most tags have the risk of reliability when collected (eg.- surface, surface quality, roof shape), what is the acceptable degree of inaccuracy and when is it worth risking consistency or nuance is maybe part of the matter. 

I agree that the verifiability and the consistency of data collected can be an issue for the intended user/surveyor of StreetComplete as things stand now with this tag -- I'll to do more research to see how its done by surveyors inside and outside OSM and see if there is a way to contribute to the conversation of making this tag and related ones more consistent. 

Thanks again for taking the time and sharing the insights :)
