### ISSUE TITLE
Food Waste in Recycling Quest

### ISSUE THREAD

**Issue by Kyle0** [streetcomplete/StreetComplete#5297]
Add a food waste type (recycling=food_waste), separate to garden waste type, to the recycling types quest for UK users, as food waste is collected separately to garden waste here (the idea probably being that anyone with a garden to generate garden waste has enough space to compost their organic waste themselves).

**Comment by westnordost** [comment]
Do you have some pictures? (Also, collecting (cooked) food waste separately from garden waste (compost) is absolutely standard) .

**Comment by Kyle0** [comment]
Pictures of what? The bins?

**Comment by westnordost** [comment]
Pictures of publicly accessible food waste recycling containers.

**Comment by Kyle0** [comment]
Not at the moment, I'll give you some later, if it is somehow important.

**Comment by westnordost** [comment]
Well, basically, I want to know if it is a common thing (in the UK) to have public food waste containers where paper, glass etc. 
containers would be. 

Food waste is not really recyclable the way garden waste (compost) is, basically food waste is either incinerated or dumped on a landfill - the same really as any other household waste. So, I find it odd to hear that this is a thing.

Admittedly, a single photo cannot prove that it is common, but I guess I just want to make sure first that we do not misunderstand each other. Probably, what would be more helpful is to see an article or something that explains this.
And then, the next question would be, **how** common is this, common enough that it is worth adding this option in StreetComplete, or would leaving a note here and there suffice?
Also, as to my understanding, non-compost food waste is not really recycleable, I wonder if `recycling=food_waste` is actually the correct tag to use? (I.e. there is also no `recycling=household_waste` - even if next to the container for paper, you find a waste container, it would be tagged not with `amenity=recycling`).

**Comment by Kyle0** [comment]
It is very common for recycling bins of various types (usually mixed paper/plastic, glass and food waste, but occasionally other types) to be kept together, particularly in high population density areas, as it is throughout the EU.
I can't speak for other countries but in the UK, food waste definitely is recycled/composted and any methane collected to feed into the national gas grid. Not every town does this, but many do. So it should definitely remain under recycling. I am surprised to hear you say that food waste is collected separately and then incinerated, just on cost grounds alone I highly doubt any local authority in any country would do this. I don't want to cause offense, but I don't think what you are saying is correct.
An example from my city can be found [here](https://www.edinburgh.gov.uk/foodwaste), and a [report from 2 years ago](https://anaerobic-digestion.com/anaerobic-digestion-plants/anaerobic-digestion-plants-uk/) states there are over 600 such food waste plants around the country. Again, I can't speak for other countries but here food waste recycling is definitely widespread. I am going to have to strongly disagree with your statement that food waste 'is not really recyclable'.

**Comment by westnordost** [comment]
Right, have it compost/collect methane sounds reasonable, sorry for making such assumptions without proper knowledge.

As far as I know, Hamburg incinerates all its household waste (except anything collected separately: packaging, paper, glass, ...). The fire sustains itself, i.e. it actually gives off some more energy than they need to put in to incinerate the fire.

**Comment by HolgerJeromin** [comment]
> As far as I know, Hamburg incinerates all its household waste

Kind of off topic here, but [Hamburg](https://www.stadtreinigung.hamburg/entsorgung-recycling/bioabfall/)  has a brown bin as every german city I know which should get all food (even cooked) and all grown stuff from the garden.

**Comment by westnordost** [comment]
@HolgerJeromin 

Uh, I didn't know even cooked food goes into the brown bin. We don't have one anyway, though. We do not even have bins, just trash bags for everything we throw onto the sidewalk. (Minus "Gelber Sack", but they make it really hard nowadays to get those bags in the first place.)
Anyway, if you are sure about this (brown bins), are you also sure that for every county, it is the same? For example it is not the same for "Gelber Sack" - in some places, only packaging, in others, such as Hamburg, any "Wertstoffe" (i.e. any iron, tin, plastic, ...), as far as I know

**Comment by HolgerJeromin** [comment]
The system "gelber sack" has changed since its beginning where there were some paying networks (one is "grüne punkt"). But now all packaging can be thrown into the yellow bins/bags regardless of any logo.
I am unsure how common the "put everything out of plastic or metall in it" is across Germany because this "upgrade" is paid by the city itself. ([ref](https://www.sueddeutsche.de/wirtschaft/recycling-ein-gelber-sack-den-niemand-versteht-1.3480098) )

**Comment by mnalis** [comment]
> Anyway, if you are sure about this (brown bins), are you also sure that for every county, it is the same?

In Croatia it is not. Brown bins are for compostable [recycling:green_waste=yes](https://wiki.openstreetmap.org/wiki/Key:recycling:green_waste)  only. So cooked food, meet, dairy etc. are strictly forbidden there, and must go to  [amenity=waste_disposal](https://wiki.openstreetmap.org/wiki/Tag:amenity=waste_disposal) instead (as we don't have separate `recycling:food_waste=yes`  containers).

See e.g. https://www.cistoca.hr/info-centar/najcesca-pitanja-gradjana-41/koja-vrsta-otpada-je-biootpad-sto-se-odlaze-u-smedji-spremnik/3935 for Croatia

**Comment by davidpnewton** [comment]
Are there food waste disposal containers for each household in the UK? Yes in some areas.

Are there publicly accessible food waste containers? Generally no. The one place you might find them is municipal recycling sites. As in recycling and waste disposal centres covering entire local government areas.

**Comment by Kyle0** [comment]
I find that food waste bins often are publicly accessible. Where they are not, the other recycling bin types in the same location also are not accessible to the general public. So if you are going to make that argument, then it needs to be applied to other types of recycling as well. In this case, some recycling locations shown on the map need to be removed. I can think of a few examples around me where this applies, and I'm sure there are many others elsewhere. I'm just asking for a consistent approach, whichever way this goes.

**Comment by westnordost** [comment]
@davidpnewton well, that sounds now like a contradiction of what @Kyle0 wrote... so food waste containers are in fact part of the household bin club, often found, locked, at apartment complexes? 

Locked recycling bins in front of apartment complexes are not mapped, are they?

**Comment by Kyle0** [comment]
@westnordost @davidpnewton There are public food waste containers all over the city where I live, and I think this is common in Scotland and the North of England (possibly Wales too). I don't remember any food waste bins elsewhere in Europe, but it has been a few years since I moved to the UK.

**Comment by westnordost** [comment]
But these are public, yes? I mean, not only public as in accessible by the public (i.e. not locked), but actually not belonging to any apartment complex or similar?

**Comment by davidpnewton** [comment]
> @westnordost @davidpnewton There are public food waste containers all over the city where I live, and I think this is common in Scotland and the North of England (possibly Wales too). I don't remember any food waste bins elsewhere in Europe, but it has been a few years since I moved to the UK.

Well this website allows finding of what can be recycled where:

https://www.recyclenow.com/recycling-locator

Taking a few locations in the north of England, namely Middlesbrough, Carlisle, Leeds and Chester with all 12 filter options for food was enabled gets the result:

* Middlesbrough has no facilities for recycling of food
* Carlisle has no facilities for recycling of food
* Leeds has no facilities for recycling of food
* Chester shows facilities for recycling of food 21 miles away in Kirkby just to the east of Liverpool

Where I live in the Midlands shows two facilities within 25 miles with a similar search.

So I'd say it's fairly safe to say that @Kyle0 is incorrect when referring to public food waste containers as "common" in the North of England. What would be interesting to know is what is the city he is referring to and see what the results are for that city.

**Comment by Kyle0** [comment]
Ok, so clearly nowhere in England does communal food waste. But I find interesting the immediate focus on the North of England, to the complete exclusion of Scotland and Wales, let alone anywhere else. I made it pretty clear in my original post that I live in Edinburgh. As for communal food waste outside England, here are some useful links:
- [Edinburgh](https://cityofedinburgh.maps.arcgis.com/apps/webappviewer/index.html?id=f159dbd910ac4f86ad50b7b2694be208): circles are communal bins, triangles are private bins
- [Glasgow](https://glasgowgis.maps.arcgis.com/apps/webappviewer/index.html?id=345f389a91ff4f1fa193b24df832fb05)
- [Paris](https://secretsofparis.com/practical/living-in-paris/recycling-in-paris-just-got-easier/)
- [Barcelona](https://www.barcelona.cat/cuidembarcelona/en/reciclar/resid/RM0125/53087500001000010)
- [Madrid](https://www.comunidad.madrid/en/servicios/consumo/reciclaje-donde-tirar-cada-producto)

As for the recyclenow link @davidpnewton posted, it only shows recycling CENTRES, not communal bins. I think I have sufficiently proved my point that public food waste collection points are widespread. I could have gone to provide more examples of other cities doing this, but I will leave that to someone else or another day.

**Comment by osmuser63783** [comment]
Here is a photo (also from Edinburgh). Note that garden waste is explicitly not allowed.

![20230415_094002](https://github.com/streetcomplete/StreetComplete/assets/127188803/69090f1c-8f46-4d39-a3df-815cfd0a3d55)

Some areas of Edinburgh have weekly kerbside collections, other areas have communal bins. In those parts of town that use communal bins, food waste bins can be found alongside the bins for glass and for mixed recycling. Although they are meant for residents of nearby streets, they are out on the street, so in practice they are accessible to the general public.

Garden waste is always collected in a wheelie bin. I’m not aware of any communal garden waste bins.

As it stands there are few things that are less than ideal with this quest:
- there is no way of tagging `recycling:food_waste=yes` through the app, the user has to leave a note. And I'm not sure, does StreetComplete maybe even remove a previously tagged `food_waste` from a `container` when the user answers the quest?
- the icon for “garden waste” shows an apple core and a twig. This is technically incorrect because an apple core isn’t garden waste (or is it when you have an apple tree in your garden? don't ask me 😂)
- when the user selects “garden waste”, the tag sets `recycling:green_waste=yes`. This also doesn't really make sense because `green_waste` is documented in the Wiki as meaning "Compost - leftover food, vegetables, fruit, usually except meat. In practice it also includes recycling:garden_waste"

How about the following as a (relatively) simple fix? If the user selects “green waste” (which could re-use the existing "garden waste" icon but should be called “green waste” or “biodegradable waste” or something like that, but not "garden waste") they can select between “food waste” (just the apple core), “garden waste” (just the twig), or both.

I also don't know how common it is around the planet that food waste and garden waste are collected separately. And I realise that making the UI more and more complex to accommodate all these small differences in how recycling is collected also makes it more complicated.

In an ideal world I would just need four buttons for 'my' city: One for mixed recycling (that is `cans`, `paper` and`plastic_packaging`), one for glass, one for food waste, and one for paper. But these presets would need to vary from city to city...

**Comment by westnordost** [comment]
> there is no way of tagging recycling:food_waste=yes through the app, the user has to leave a note. And I'm not sure, does StreetComplete maybe even remove a previously tagged food_waste from a container when the user answers the quest?

If the containers are tagged with any `recycling:*=*` it does not know, it does not ask anything about the containers.

> How about the following as a (relatively) simple fix? If the user selects “green waste” [...] they can select between “food waste” (just the apple core), “garden waste” (just the twig), or both.

Hmm, good idea. Though, I am not sure if it makes sense to separate "garden waste" from "compostable waste"(?) (Where) does it make a difference?

The point about the photo you posted is that you can also put stuff like fast food pizza, cooked noodles, meat etc. in that. This is not part of compostable waste.

So, for an icon.... a pizza slice and a sausage?

**Comment by osmuser63783** [comment]
Taginfo shows that `recycling:food_waste` is not uncommon in France (about 50% of global usage). This is known as [déchets alimentaires](https://actu.fr/grand-est/strasbourg_67482/strasbourg-c-est-quoi-ces-poubelles-nouvelle-generation-qui-arriveront-en-centre-ville_46449472.html). So maybe some feedback from the French community would be useful as well.

> The point about the photo you posted is that you can also put stuff like fast food pizza, cooked noodles, meat etc. in that. This is not part of compostable waste.

Are there any places where food waste is collected, but only compostable food waste is allowed in the bin, and therefore a pizza and a sausage could confuse users? Not sure.

**Comment by westnordost** [comment]
> Are there any places where food waste is collected, but only compostable food waste is allowed in the bin

Yes of course. Most places. The "brown bin" or "bio bin" in Germany is exactly that. Accepted are garden waste, uncooked vegetables, fruits, eggs, coffee, tea,...

**Comment by osmuser63783** [comment]
Sorry - I should have said, where food waste is collected separately from garden waste (and therefore should be tagged as `recycling:food_waste=yes`, not as `recycling:green_waste=yes`), but only compostable food waste is allowed in that bin?

**Comment by letypequividelespoubelles** [comment]
> Taginfo shows that recycling:food_waste is not uncommon in France (about 50% of global usage). This is known as [déchets alimentaires](https://actu.fr/grand-est/strasbourg_67482/strasbourg-c-est-quoi-ces-poubelles-nouvelle-generation-qui-arriveront-en-centre-ville_46449472.html). So maybe some feedback from the French community would be useful as well.

It's quite new, but we see a lot of food waste recycling bins. It's most of the time public, located in the street, near parks. I think the place where we have the more if it is in the city of Lyon.

**Comment by westnordost** [comment]
Anyway, I got confused by the long discussion.... so to recap, the following change would make sense for everyone? (Answer by thumbs-up or comment)

A new icon is selectable:

Organic waste - icon: twig and apple

When tapped, a submenu will open, with two choices:

1. Green waste - icon: twig and apple (seems to me is the correct term: https://en.wikipedia.org/wiki/Green_waste , alternative: "compostable waste"). If selected, `recycling:green_waste=yes` and `recycling:food_waste=no` is tagged.
2. Food waste - icon: twig, apple, pizza / sausage. If selected, `recycling:green_waste=yes` and `recycling:food_waste=yes` is tagged.

**Comment by letypequividelespoubelles** [comment]
I'm not sure it's always possible to recycle green waste in food waste recycling. So if selecting both it should be yes for both, if selecting only one, yes for this one and no for the other one

**Comment by westnordost** [comment]
No, that will lead to too much wrong taggings (green waste=no, food waste=yes).

Perhaps better to use alternative names.

Organic waste  -> select either "only compostable waste" or "any organic waste".

If anyone stumbles across "food waste only, no compostable waste", he will (have to) leave a note, then.

**Comment by osmuser63783** [comment]
No, sorry, this won't work. The food waste bins in Edinburgh that started this discussion do not accept garden waste (e.g. leaves, twigs and branches, grass cuttings, weeds). If you have a garden, the council will charge you extra for a garden waste collection...

Let's go back to the question, what do people want to tag?
- In some cities in the UK and France, there are food waste bins, people want to tag these as `recycling:food_waste=yes`
- in some places elsewhere e.g. in Germany there are places ("Biotonne") that accept both food waste and garden waste, and these are usually tagged as `recycling:green_waste=yes` (as far as I can see), though tagging them as `recycling:food_waste` and `recycling:garden_waste=yes` would be equivalent 

So you have a few options
- make food waste and green waste separate top-level level options. Accept some overlap between the two (as icons, food waste could have an apple core and a pizza slice while green waste gets an apple core and a twig). If someone finds a communal garden waste bin that doesn't accept food waste, they'll have to leave a note.
- make food waste and garden waste separate top-level options. Don't bother with green_waste. For a typical "Biotonne" (both food waste and garden waste), users are just expected to select both
- make biodegradable/organic/green waste a top level option (apple core and twig). When someone selects it, they get the options of "food waste only" (sets `recycling:food_waste=yes`), "garden waste only" (sets `recycling:garden_waste=yes`) or "both" (sets `recycling:green_waste=yes`)

No need to tag any `no`s which always carries the risk of accidental mistaggings.

**Comment by osmuser63783** [comment]
There is also, separately, the question which specific types of food a recycling site tagged `recycling:green_waste=yes` accepts (e.g. cooked food? meat? dairy?). It looks like in Croaria the answer to this question is different than in Germany. But we don't have tagging to express that, so I don't think this is a question StreetComplete needs to solve.

**Comment by letypequividelespoubelles** [comment]
>  -  make biodegradable/organic/green waste a top level option (apple core and twig). When someone selects it, they get the options of "food waste only" (sets recycling:food_waste=yes), "garden waste only" (sets recycling:garden_waste=yes) or "both" (sets recycling:green_waste=yes)
No need to tag any nos which always carries the risk of accidental mistaggings.

I'm highly in favor of this option. It's the same UX as the plastic or glass recycling top option.

**Comment by westnordost** [comment]
@osmuser63783 Oh, wow... well, I am genuinely curious why it is not allowed to put garden waste into the organic waste/food waste bin in some places. Do you know or do you know the source that explains this? Maybe it is just about planability, not how it is recycled - i.e. home owners with gardens need much more capacity during fall.

Anyway, as @osmuser63783 wrote that indeed there are places that do not allow garden waste but food waste (i.e. apples but not leaves), it is clear that my suggestion earlier will not work.

I also understand that the exact restrictions on what may go into the "biotonne" (and similar) will be dependent on the region and it makes no sense to tag it to that detail (as the restrictions may also change slightly etc.)

So, we have 
- `garden_waste`  - mostly twigs, leaves, grass, but of course also its produce (apples and whatever)
- `green_waste`- compostable waste, i.e. garden waste + certain food waste (usually not meat, often not cooked or processed things, but coffee, tea, eggshells etc. are usually fine)
- `food_waste` - any food waste, including meat, processed and cooked things

The important thing is, that `green_waste` in general is not garden waste + food waste, not any food, at least. 

I wonder if there needs to be an option for "garden waste but not compostable food waste". Doesn't really make sense to me.

**Comment by eginhard** [comment]
> @osmuser63783 Oh, wow... well, I am genuinely curious why it is not allowed to put garden waste into the organic waste/food waste bin in some places. Do you know or do you know the source that explains this? Maybe it is just about planability, not how it is recycled - i.e. home owners with gardens need much more capacity during fall.

For Edinburgh, food waste goes to a biogas plant, whereas garden waste is composted: https://www.edinburgh.gov.uk/recycling-3/happens-recycling

**Comment by matkoniecz** [comment]
> well, I am genuinely curious why it is not allowed to put garden waste into the organic waste/food waste bin in some places. Do you know or do you know the source that explains this?

Probably capacity issues - single cutting of small lawn can produce as much volume as entire block of flats will produce in several days

In https://www.facebook.com/mpokrakow/photos/a.294949281199347/271964363497839/ they mention that as of 2019 it was separate as it allowed them to compost green waste and it was a separate collection system working well

https://mpo.krakow.pl/pl/mieszkancy/harmonogramy/zielone https://mpo.krakow.pl/pl/edukacja/segregacja indicates they kept this system

(though this collection points are all private, internal to specific building and often locked up, so would not get `amenity=recycling`)

**Comment by osmuser63783** [comment]
Yes, and you don't want to carry your hedge clippings and lawn cuttings to a communal bin halfway down the street. So people pay extra for a garden waste collection. They get a wheelie bin they keep in their garden, and the council collects it every two weeks and makes some money off it.

I also don't think that "garden waste but not compostable food waste" makes any sense. For my area, you don't even need garden waste as an option in a StreetComplete quest. The tag "recycling:garden_waste=yes" will only be found on recycling centres, not communal bins.

**Comment by osmuser63783** [comment]
Thanks! 🎉

**Comment by rhhsm** [comment]
> I am genuinely curious why it is not allowed to put garden waste into the organic waste/food waste bin in some places.

Chemical engineer here! The difference is in the composition of the carbohydrates. Carbohydrates such as sugars and starch in food waste are easy to break down and ferment to biogas or alcohol by most bacteria and yeasts, while the cellulose carbohydrates in wood (garden waste) need special enzymes to break it down. Cows can eat garden waste, but that's because they have 5 stomachs to digest it. We have only one, so we can't eat garden waste (wood, grass, "dietary fibre") but only pizza and apples (starch and sugars).
