### ISSUE TITLE
Club Mate Quest

### ISSUE THREAD

**Issue by ConfusedAlex** [streetcomplete/StreetComplete#5305]
### General
Affected tag(s) to be modified/added: [drink:club-mate](https://wiki.openstreetmap.org/wiki/Key:drink:club-mate)
Question asked: **Does this shop sell Club Mate?**
Applications based on this data: [Mateka'te](https://matekarte.strubbl.de)

### Checklist
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

This quest most likely can't be solved from the outside. Therefore it should be disabled by default.

### Ideas for implementation

**Proposed UI:** No fancy new design is needed. A simple yes or no is sufficient.

**Comment by mnalis** [comment]
> - [x]  🚧 To be added tag is established and has a useful purpose

I would've expected that its wiki [status](https://wiki.openstreetmap.org/wiki/Tag_status) is then either `Accepted` or `De facto` if it is established?

> - [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

In what country(ies) is this the case? In Croatia, for example, it would likely be quite spammy (e.g. I've never in my life seen or heard about one of those, so it would probably be 99.99% `no` answers). [Taginfo map](https://taginfo.openstreetmap.org/keys/drink%3Aclub-mate#map) seems to indicate it is mostly mapped only in small number of western-european countries (where it is presumably popular). 

StreetComplete is designed to be used worldwide, so if some quests are only useful for some countries, it should be limited to them. (i.e. that `Metadata needed: (missing)` should be researched first)

>  Element selection: (missing)

One might guess from the text of the question it might be `shop=convenience or shop=supermarket or shop=beverages` ?

----

That being said, I don't think it would be good match for StreetComplete Quest. What makes that drink so above all others that it should be asked about **specifically** (its [wiki](https://wiki.openstreetmap.org/wiki/Key:drink:club-mate) is sadly lacking)? 

i.e. I would guess that much more people are familiar with (or requesting) [drink:wine](https://taginfo.openstreetmap.org/keys/drink%3Awine), [drink:beer](https://taginfo.openstreetmap.org/keys/drink%3Abeer), [drink:coffee](https://taginfo.openstreetmap.org/keys/drink%3Acoffee), [drink:cola](https://taginfo.openstreetmap.org/keys/drink%3Acola) etc.; yet it would be hugely impractical to have mappers being asked if shop carries **any possible type** of drink (or [food:*](https://wiki.openstreetmap.org/wiki/Key:food:*)) one by one. (you could spend whole day just mapping inventory of one shop!)

---

I however understand that people care about different things, and OSM [ATYL](https://wiki.openstreetmap.org/wiki/Any_tags_you_like) policy does allow for that. I just don't think it is a good match for StreetComplete Quest. 
I unfortunately cannot suggest alternative that allows for mapping that and is as easy to use as StreetComplete; besides creating your own fork and writing such quest for yourself ([It's not that hard](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md), but not a breeze either). 
If you'd rather not create your own fork; [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork looks similar for other quests, and does allow for creating custom quests and custom overlays; but it also requires some extra work by the mapper for those custom quests/overlays (either preparing the quest list, or adding the raw tag manually on every overlay match). Or you could use other mobile editor like [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door) or [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci). 

But if you only care about that specific (and/or few other) drink in all of OSM; your easiest bet might perhaps be to create a theme for [MapComplete](https://wiki.openstreetmap.org/wiki/MapComplete) (it is web-based and not a mobile app, but can be used on mobile; albeit not as nicely as an native mobile app of course)

**Comment by westnordost** [comment]
See @mnalis.
