### ISSUE TITLE
Quest AddBicycleBarrierInstallation removes barrier type

### ISSUE THREAD

**Issue by andrebk** [streetcomplete/StreetComplete#5310]
I came across [this changeset](https://www.openstreetmap.org/changeset/139107983), where a user has modified three `barrier=cycle_barrier`. The changeset lists `AddBicycleBarrierInstallation` as the quest answered.

I would expect this quest to set the key `cycle_barrier:installation=*`, but instead the only change is to set `barrier=yes`, which was previously `barrier=cycle_barrier`. This means instead of improving the feature, information has now been lost instead.

**How to Reproduce**

I would assume answering the `AddBicycleBarrierInstallation` quest would cause this, but not sure as I haven't "caught it in the act" so to speak.

**Expected Behavior**

Quest sets `cycle_barrier:installation=*` to appropriate value. Information about barrier type is not lost.

**Versions affected**

53.32, according to changeset.

**Comment by westnordost** [comment]
Correct. So, it is not a bug. The user deliberately selected that it is not a bicycle barrier.

The Norwegian text for the "other answer" in question is "Ikke en sykkelbariere, men en annen type bariere".

**Comment by andrebk** [comment]
Aah, I see. I understand how that might happen, in Norway there are almost no features meant to block bicycles, but its very common with these types of barriers to block motor vehicle traffic on foot/cycle paths. I usually map them as openable bicycle barriers, but technically their job is the exact opposite of blocking bicycles, so the semantics are quite confusing.
