### ISSUE TITLE
Quest: What is this bathing place called?

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#5316]
### General
Affected tag(s) to be modified/added: [name](https://wiki.openstreetmap.org/wiki/Key:name)
Question asked: **What is this bathing place called?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ x] 🚧 To be added tag is established and has a useful purpose
- [x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x ] 🕓 Applies to a reasonable number of map data (Worth the effort) 

### Ideas for implementation

**Element selection: name tag is missing** 

**Metadata needed:** 

**Proposed UI:**

**Comment by westnordost** [comment]
Bathing place? What do you mean?

**Comment by mnalis** [comment]
Interestingly, (order of magniture popular) [leisure=swimming_area](https://wiki.openstreetmap.org/wiki/Tag:leisure=swimming_area) marks it as possible tagging mistake?

Regarding _"🤔 Any answer the user can give must have an equivalent tagging"_, what if it does not have a name? 
Tag it as [informal=yes](https://wiki.openstreetmap.org/wiki/Key:informal) ?

**Comment by 02JanDal** [comment]
We've had some recent discussion in the Swedish forum on this, starting here: https://community.openstreetmap.org/t/import-av-badplatser-fran-lm-topografi-50/102458/40

Paraphrased and translated:

`leisure=bathing_place` or `amenity=public_bath` is the "primary" tag that should be present, and the one that should hold the name etc. The difference between them is in the level of surrounding facilities; `leisure=bathing_place` doesn't require more than a sign or similar (unless `informal=yes`*) but can have toilets, simpler changing facilities, and even showers, while `amenity=public_bath` requires significant facilities, like human-formed pools etc. The wiki says, for public baths: "A facility where you can go and take a bath, e.g. an onsen, a hot spring, a hammam or a thermal bath. It must have something more than just showers, but it may be anything from bath tubs up to large swimming pools."). As such bathing places will often be mapped as a node, as they commonly don't have a clearly defined area, while public baths should most of the time be mapped as an area. Regardless of if mapped as an area or not, both tags usually represent everything about the place, not only the water, but also the beach, facilities, etc. Note however that while bathing places will usually be free (even not allowed to charge for in Sweden), and public baths will usually have a fee, that is not a requirement for choosing between the two tags.

`leisure=swimming_area` on the other hand is only for the area of water, and has to be marked by "e.g. ... buoys or a netted enclosure ...", which makes it unsuitable to be mapped for most beaches etc. (as there is no verifiability on the ground).

Example of a `leisure=bathing_place` that should also have an area with `leisure=swimming_area` (notice the buoy line on the left and upper right of the picture):
![18cb3b28a5625f1a5372a5d26184e3d2-min](https://github.com/streetcomplete/StreetComplete/assets/3686998/35721335-0e45-43ab-b5b4-9ed1a4ee3d8a)

Example of a `leisure=bathing_place` that should _not_ have an area with `leisure=swimming_area`:
![image](https://github.com/streetcomplete/StreetComplete/assets/3686998/b6b722de-1c7a-4282-8944-7e9b17684b1a)


However, while I think we had a very good consensus on the above, the thing we're agreeing on the most is that the current wiki pages (including [this overview](https://wiki.openstreetmap.org/wiki/Swimming_and_bathing)) are quite confusing and unclear...

\* This is not clearly described on the wiki as of yet, but as there is currently no other way to tag it our consensus was to use that tag together with `leisure=bathing_place` (which on its own requires at least a sign). So a place that's suitable for bathing and used as such but not officially designated/signed would have `leisure=bathing_place` and `informal=yes`. And while such a place could have a name I think it's reasonable to regard it as "nameless" for the purpose of StreetComplete if the informal tag is present.

**Comment by mnalis** [comment]
> So, do either of the two commonly have a name?

I don't know about on the ground situation, but according to overpass turbo, at least:

-  `leisure=bathing_place`: [253/641](https://overpass-turbo.eu/s/1C7q)  `= 39%` have `name` tagged too
-  `leisure=swimming_area`: [2250/6006](https://overpass-turbo.eu/s/1C7r) `= 37%` have `name` tagged too
-  `amenity=public_bath`: [8224/10655](https://overpass-turbo.eu/s/1C7p)  `= 77%` have `name` tagged too

Presumably, some of those mapped have a name in reality, but name have not been mapped yet (thus the need for this quest)

**Comment by dpriskorn** [comment]
> -  `leisure=swimming_area`: [2250/6006](https://overpass-turbo.eu/s/1C7r) `= 37%` have `name` tagged too

These areas in Sweden are mostly with few exceptions a slightly erroneous import of bathing_places from Wikidata.

I'm currently cleaning them up.

**Comment by dpriskorn** [comment]
> We've had some recent discussion in the Swedish forum on this, starting here: https://community.openstreetmap.org/t/import-av-badplatser-fran-lm-topografi-50/102458/40
> 
> Paraphrased and translated:
> 
> `leisure=bathing_place` or `amenity=public_bath` is the "primary" tag that should be present, and the one that should hold the name etc. The difference between them is in the level of surrounding facilities; `leisure=bathing_place` doesn't require more than a sign or similar (unless `informal=yes`*) but can have toilets, simpler changing facilities, and even showers, while `amenity=public_bath` requires significant facilities, like human-formed pools etc. The wiki says, for public baths: "A facility where you can go and take a bath, e.g. an onsen, a hot spring, a hammam or a thermal bath. It must have something more than just showers, but it may be anything from bath tubs up to large swimming pools."). As such bathing places will often be mapped as a node, as they commonly don't have a clearly defined area, while public baths should most of the time be mapped as an area. Regardless of if mapped as an area or not, both tags usually represent everything about the place, not only the water, but also the beach, facilities, etc. Note however that while bathing places will usually be free (even not allowed to charge for in Sweden), and public baths will usually have a fee, that is not a requirement for choosing between the two tags.
> 
> `leisure=swimming_area` on the other hand is only for the area of water, and has to be marked by "e.g. ... buoys or a netted enclosure ...", which makes it unsuitable to be mapped for most beaches etc. (as there is no verifiability on the ground).
> 
> Example of a `leisure=bathing_place` that should also have an area with `leisure=swimming_area` (notice the buoy line on the left and upper right of the picture):
> ![18cb3b28a5625f1a5372a5d26184e3d2-min](https://github.com/streetcomplete/StreetComplete/assets/3686998/35721335-0e45-43ab-b5b4-9ed1a4ee3d8a)
> 
> Example of a `leisure=bathing_place` that should _not_ have an area with `leisure=swimming_area`:
> ![image](https://github.com/streetcomplete/StreetComplete/assets/3686998/b6b722de-1c7a-4282-8944-7e9b17684b1a)
> 
> 
> However, while I think we had a very good consensus on the above, the thing we're agreeing on the most is that the current wiki pages (including [this overview](https://wiki.openstreetmap.org/wiki/Swimming_and_bathing)) are quite confusing and unclear...
> 
> \* This is not clearly described on the wiki as of yet, but as there is currently no other way to tag it our consensus was to use that tag together with `leisure=bathing_place` (which on its own requires at least a sign). So a place that's suitable for bathing and used as such but not officially designated/signed would have `leisure=bathing_place` and `informal=yes`. And while such a place could have a name I think it's reasonable to regard it as "nameless" for the purpose of StreetComplete if the informal tag is present.

I really like this overview. Would you consider suggesting these clarifications on the relevant talk pages in the wiki?

**Comment by 02JanDal** [comment]
@dpriskorn We've started a discussion on the forum: https://community.openstreetmap.org/t/clarification-on-the-mapping-of-bathing-places/105017

**Comment by westnordost** [comment]
What is outcome of discussion. Has it been documented in the wiki?

**Comment by 02JanDal** [comment]
@westnordost I think it reached a consensus, though I've yet to document it on the wiki. Will try to do so this weekend.

**Comment by westnordost** [comment]
Has it been documented?

**Comment by paulklie** [comment]
> Has it been documented?

Aye, the wiki has been updated and there have not been any further updates for a while : https://wiki.openstreetmap.org/w/index.php?title=Tag:leisure%3Dbathing_place&oldid=2618757
This leads me to believe that concensus has been reached. Could we reopen this as well as https://github.com/streetcomplete/StreetComplete/issues/5318 https://github.com/streetcomplete/StreetComplete/issues/5319

**Comment by matkoniecz** [comment]
done

I also tried double-checking at https://community.openstreetmap.org/t/clarification-on-the-mapping-of-bathing-places/105017/52
