### ISSUE TITLE
Exclude `delivery=only` places from quests

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5320]
**Use case**
Currently quests like opening hours and outdoor seating are asked for [restaurants with `delivery=only`](https://www.openstreetmap.org/node/11270561323). According to [wiki](https://wiki.openstreetmap.org/wiki/Key:delivery), places with `delivery=only` may not even have a storefront, so there might not be a correct answer selectable, e.g. for outdoor seating.
Further a `delivery=only` restaurant that is not clearly visible from outside is at risk of being wrongly removed by a SC user.

**Proposed Solution**
Exclude elements with `delivery=only` from "orange quests" like opening hours, wheelchair access, smoking, outdoor seating, diet quests, possibly also existence.

**Comment by matkoniecz** [comment]
I would note that `delivery=only` object is not restaurant or shop at all and this is a mistagged feature.

(disclaimer: maybe there is no consensus on that and that is personal rant not general opinion? But I would start from opening notes on such objects and checking how many such warehouses and dark kitchens are mistagged)

**Comment by Helium314** [comment]
I agree that it's a troll tag, but it's already in (low) use.
For restaurants, [`craft=caterer`](https://wiki.openstreetmap.org/wiki/Tag:craft=caterer) might be more suitable. While _caterer_ doesn't appear right, such restaurants are explicitly included in the wiki description.

**Comment by riQQ** [comment]
> I remember some discussion on Community Forum

This
https://community.openstreetmap.org/t/how-to-tag-online-groceries-gorillas-getir-flink/101391 ?

**Comment by westnordost** [comment]
This only concerned online groceries, not fast food / delivery services.

Anyway, it is clear that in this case, `craft=caterer` should be used, it is documented in the wiki:

> This tag can apply to businesses that market themselves as caterers per se, as well as other commercial facilities that only cook meals for delivery, such as [ghost kitchens](https://en.wikipedia.org/wiki/Ghost_kitchen) and non-retail [traiteurs](https://en.wikipedia.org/wiki/Traiteur_(culinary_profession)).

...

and in general, StreetComplete does not handle tagging mistakes. Not only would it be a can of worms, a barrel without bottom, it actually hinders actually **fixing** the tagging mistake. Now, if someone walks by [Mamacita - California Burritos](https://www.openstreetmap.org/node/11270561323) and is asked about seating, vegetarian cuisine or whatever, the user will be able to correct the mistake by answering that it is not a restaurant but a ghost kitchen.
