### ISSUE TITLE
Migrate to OAuth 2.0

### ISSUE THREAD

**Issue by Zaczero** [streetcomplete/StreetComplete#5322]
**Use case**
OAuth 1.0a will be deprecated.
https://www.openstreetmap.org/user/pnorman/diary/401157

**Proposed Solution**
OAuth 2.0 is a lot simpler to implement, requires less maintenance and is generally stress free.

**Comment by FloEdelmann** [comment]
Cross reference: https://github.com/streetcomplete/StreetComplete/discussions/4301

**Comment by Helium314** [comment]
See also https://github.com/westnordost/osmapi/issues/33 which seems to be the better repository for this issue
