### ISSUE TITLE
[Quest] Does this restaurant/pub has a toilet?

### ISSUE THREAD

**Issue by inson1** [streetcomplete/StreetComplete#5323]
### General
Affected tag(s) to be modified/added: [toilet](https://wiki.openstreetmap.org/wiki/Key:toilet)
Question asked: **Does this restaurant/pub has a toilet?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

**Comment by matkoniecz** [comment]
see #4860 from https://github.com/streetcomplete/StreetComplete/issues?q=restaurant+toilet+is%3Aclosed - is reason for closing this still applying

**Comment by Helium314** [comment]
> @Helium314 In some countries you dont have to. It would make life easier if you know where are some toilets.

Then why ask everywhere instead of only in these countries?
