### ISSUE TITLE
An invisible note interferes with road selection in overlay mode

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5324]
**How to Reproduce**
1. Enable Surfaces overlay
2. Move the map [here](https://www.openstreetmap.org/#map=19/59.90251/30.50549&layers=N) 
3. Click on the sidewalk
4. Opens a [note](https://www.openstreetmap.org/note/3948708) that is located nearby

https://github.com/streetcomplete/StreetComplete/assets/25708359/79140b47-8e22-41c7-9e84-b8197fa44955

**Expected Behavior**
1. The sidewalk surface editing window opens

**Versions affected**
StreetComplete 54.1, Samsung Galaxy A52 Android 13 OneUI 5.1

**Comment by mnalis** [comment]
- Is it this issue? https://github.com/streetcomplete/StreetComplete/issues/4529  

https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Editing_in_Overlay_mode_opens_Notes_instead

**Comment by westnordost** [comment]
Jup, duplicate

**Comment by deevroman** [comment]
1. But if the note is not relevant to the selected sidewalk? For example, in this one I reported a missed footway, not a problem with the sidewalk.

2. Why not write about it in the interface?

**Comment by westnordost** [comment]
StreetComplete cannot know if it is related to a specific quest or overlay or not. So, the most cautious approach is to let notes block all other edits with StreetComplete.

**Comment by deevroman** [comment]
Notes left as a result of a quest start with "Unable to answer <quest name>..." or Overlays "In context of <Overlay name> overlay..." 

But why all this complexity when I can switch off overlay and add surface with a quest? :)

**Comment by westnordost** [comment]
You cannot add surface with a quest while a note is open for that element.

**Comment by deevroman** [comment]
I.e. in the case of a quest it is clear what the note refers to, but in the case of overlays it is not? Why?

**Comment by westnordost** [comment]
Sorry, I don't get what you mean.

**Comment by deevroman** [comment]
I'll try to show what the contradiction is with an example:

https://github.com/streetcomplete/StreetComplete/assets/25708359/b42218bc-50eb-4a5d-b13c-56f86b9f0c76

**Comment by westnordost** [comment]
Oh, that's a bug. The quest should not be created, i.e. overlay and quest should behave the same. Would you mind creating a new issue for htat and share the location where this is happening?

**Comment by deevroman** [comment]
in the first comment

**Comment by deevroman** [comment]
Created. But I would like to point out that the bug is more about opening a note that is not related to the selected object :) I don't understand when it's important to prevent the user from answering a quest because of some other note.

**Comment by Helium314** [comment]
see also #4700
