### ISSUE TITLE
An open note does not prevent the quest from being displayed

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5326]
**How to Reproduce**
1. Move the map [here](https://www.openstreetmap.org/#map=19/59.90251/30.50549&layers=N) 
2. Click on the sidewalk surface quest
3. The quest shouldn't be open because there's a note next to it.

This opens the note in Overlay mode:

1. Enable Surfaces overlay
2. Move the map
3. Click on the sidewalk
4. Opens a [note](https://www.openstreetmap.org/note/3948708) that is located nearby

https://github.com/streetcomplete/StreetComplete/assets/25708359/b42218bc-50eb-4a5d-b13c-56f86b9f0c76

**Expected Behavior**
Opens a [note](https://www.openstreetmap.org/note/3948708) that is located nearby

**Versions affected**
StreetComplete 54.1, Samsung Galaxy A52 Android 13 OneUI 5.1

via https://github.com/streetcomplete/StreetComplete/issues/5324

**Comment by Helium314** [comment]
Currently notes are blocking quests/overlays only if they are within a small distance (~1m) of the center of the element.
Do you think this should be changed?

**Comment by westnordost** [comment]
Alright, I made the implementation for note-detection near the center of an element identical for overlays as for quests. Note that it is not perfect: Sometimes notes up to 1.1m away from the center of the element are detected to be associated with the element, sometimes they have to be (much) closer. That's fine, though.
