### ISSUE TITLE
Add photo quests

### ISSUE THREAD

**Issue by pyrog** [streetcomplete/StreetComplete#5329]
**Use case**
- Ask user to take a picture of an OSM object.
- Could be limited to some tags, or associated with existing quest ([Guideposts](https://github.com/streetcomplete/StreetComplete/issues/2514#issuecomment-1465824161), [fire hydrants](https://github.com/streetcomplete/StreetComplete/issues/3059#issuecomment-1042640399), artworks, [BBQ](https://github.com/streetcomplete/StreetComplete/issues/4832)…)

**Proposed Solution**
- The quest should be only on objects without "picture" tags: `image`, `wikimedia_commons`, `mapillary`… 'see [Photo linking](https://wiki.openstreetmap.org/wiki/Photo_linking#Mapping)) 
- Should be limited to "some" objects
- Pictures should be uploaded to permanent storage (see [#1781](https://github.com/streetcomplete/StreetComplete/issues/1781#issuecomment-1774983333))
- OSM object must be tagged appropriately according to the storage chosen by the user.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/1601#issuecomment-544299633 is still applying as far as I know
