### ISSUE TITLE
Indoor quest is unclear for building=roof

### ISSUE THREAD

**Issue by infthi** [streetcomplete/StreetComplete#5333]
Currently the recently added Indoor quest asks a question "Is this inside a building?" with options [Yes] and [No]
I had no idea what to answer here for an object that was under a roof on a train station (roof only, no walls).
* One may answer "yes" because `building=roof` might be considered a building (and definitely is in terms of OSM). 
* One may answer "no" because, well, there were no walls/doors.

there seems a more suitable `covered` tag for this kind of setup.

Potential solution: add a third option "Covered only" which will set `covered=yes` (and, probably, `indoor=no`. Semantics from wiki are unclear).

**How to Reproduce**
Trigger the dialog for the "Is this inside a building?" quest

**Expected Behavior**
Quests shall be easy to answer per the "Easy answer" section from QUEST GUIDELINES.

**Versions affected**
Android 13
StreetComplete v55.0

**Comment by rhhsm** [comment]
I think most map users will consider an object that's only covered by a roof as outside. I assume the practical purpose of asking for this is that an `indoor` object may be behind doors that are closed some of the time (i.e. have opening hours).
