### ISSUE TITLE
Always ask if defibrillator (AED) is indoor

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5336]
**Use case**

In #5278, the `AddIsDefibrillatorIndoor` quest was replaced with the more generic `AddIsAmenityIndoor` quest. The old quest was asked for all `emergency = defibrillator` nodes, while the new quest only asks about nodes inside a building outline. E.g. for [node 11071807905](https://www.openstreetmap.org/node/11071807905) (see also [this node in OpenAEDMap](https://openaedmap.org/#map=17/48.093904/11.757235&node_id=11071807905)), the new quest is not shown.

It would be good to relax that filtering in the new quest for AEDs again. See also the original reasoning by @matkoniecz in #2068:

> It is done this way as in my experience many of them are mislocated, sometimes mapped as inside building despite being outside - or reverse may be happening what is even more irritating.
> 
> And if this data is supposed to be used to located AED then it is better to have them of good quality, at cost of some potentially redundant tagging.

**Proposed Solution**

Keep the new quest, but always show the quest for `emergency = defibrillator` nodes, even if they are not inside a building outline.

cc @qugebert

**Comment by westnordost** [comment]
Hmm, so why for defibrillators specifically? What is this property AEDs have that it makes sense to always ask for their location? Could other POIs have this property, too?

**Comment by matkoniecz** [comment]
For AED exact location is especially important if OSM data would be ever used for guiding people where nearest AED is.

Or for checking some other data source with similar goal.

**Comment by westnordost** [comment]
This is not about the exact location, this is another quest. This is about whether a thing is inside or outside of a building.

**Comment by westnordost** [comment]
Maybe the property I am looking for would be "is usually found on walls (of a building)".

A category to which ATMs may belong to, too? Or are there many fee-standing ones too, as there are vending machines in general that may also be free-standing?

**Comment by qugebert** [comment]
I think for such important (livesaving) things like AED, it's ok if we ask it always, but for atms this might be a bit too spammy.
On the other hand we now also have the defib-location quest, which provides more detailed information about how to find the aed anyway. So it should be ok, if we don't tag 'indoor' everytime, as this information should be covered by defibrillator:location anyway.
But i have ne really strong opinnion on this.

**Comment by FloEdelmann** [comment]
Asking if it is indoor or outdoor is much faster (one click) than entering a description of the precise location, so it probably will be answered more often. And since it may be life saving to know whether the AED is indoor, even if the exact location was not specified, I think that it is worth the exception.

Also, the location description quest can be answered more easily when there is an "indoor" or "outdoor" location label above; otherwise we might risk that people just answer e.g. "outdoor" in the free text field.
