### ISSUE TITLE
When answer a hairdresser question for both sexes it gets tagged male=yes + female=yes

### ISSUE THREAD

**Issue by sekerob** [streetcomplete/StreetComplete#5339]
Rather straight forward, yesterdays SC survey, today Osmose proposes that such hairdressers could be tagged with unisex=yes instead, albeit cannot recollect this tag being used beyond toilets and the [unisex wiki](https://wiki.openstreetmap.org/wiki/Key:unisex) does not go anywhere else either.

**Comment by Helium314** [comment]
Looke like a duplicate of #5055

**Comment by matkoniecz** [comment]
Osmose complaining about something is not strong indicator of it being a wrong tagging.

**Comment by matkoniecz** [comment]
This specific thing was discussed in https://github.com/streetcomplete/StreetComplete/issues/5055

If there is a strong indicator of a bad tagging ("Osmose complains about it" is not, it has many known false positives), please open an issue.
