### ISSUE TITLE
Version 55.0 via F-Droid crashes on startup

### ISSUE THREAD

**Issue by Uinsart** [streetcomplete/StreetComplete#5340]
Hello!
I installed the new Version 55.0 via the F-Droid store and since then it crashes upon startup of the app.
Version 54.1 worked fine with me.

**How to Reproduce**
Update the app to 55.0 from 54.1 on F-Droid.  Cleaning app cache didn't solve it.

**Expected Behavior**
Well, obviously it should not Crash :)

**Versions affected**
Add the Android and StreetComplete version here. 
I'm on Android 14 and patch level 05.10.23

**Comment by matkoniecz** [comment]
Getting crash log would help.

**Comment by Uinsart** [comment]
> Getting crash log would help.

Honestly I don't know how, it just gets force closed in the second I open it.
Anyway, deleting and reinstalling the app solves it...

**Comment by Uinsart** [comment]
So I guess if no-one else experiences this you can close the big report.
Thanks for your work on this app! I use it daily

**Comment by Uinsart** [comment]
Reinstall made the app work again

**Comment by westnordost** [comment]
You installed it from Google Play?

**Comment by Uinsart** [comment]
> You installed it from Google Play?

No, from f-droid again

**Comment by westnordost** [comment]
Ah. Well, it would usually ask you to send the crash report via email the next time when you open the app. But if it already crashed just when you open it, there is no chance for that, of course.

So, I am sorry, with this little information, we cannot hope to find the source of the issue. If a user who installed it from Google Play has the same problem, I should get a crash report for that and from there, we could continue this.

**Comment by westnordost** [comment]
(Ha, also, sorry, apparently I didn't read the title!)
