### ISSUE TITLE
Corrections and suggestions of questions for mapping accessibility, especially for the blind in the Czech Republic

### ISSUE THREAD

**Issue by maper64** [streetcomplete/StreetComplete#5343]
Good day,
I would like to comment on Street Map and OSM.org questions and tags related to mapping and especially mapping objects for the blind from the point of view of accessibility solutions.

1. Question: Does this stop have tactile paving - the setting is not displayed in the Czech Republic.
Reasoning - in the Czech Republic, the edges of sidewalks and crossings, so-called warning and signal strips, are marked with tactile paving.
On the contrary, replace this question - add
Does the stop have a so-called intelligent talking departure board?¨
However, this can only be found out by activating a special VPN radio, which I own as a visually impaired person.
There are also similar boards at the central station, departure and arrival boards - also to consider whether it should appear as a tag - I think so.

2. Barriers - in the Czech Republic, they can be supplemented with so-called additional sound signaling for the blind. A list of these places can possibly be found on the website of the blind organization www.sons.cz

3. What is the tzu surface - eg roads¨
I miss cement concrete tiles (does not apply to the blind)

4. Stairs - the question is whether they have tactile paving at the top and bottom. The question should also be whether the stairs for the visually impaired are marked with a color, most often yellow or white - the first and last step. It is even a far more common solution for barrier-free accessibility, even if accessible only to the sighted, seniors ... it helps in general.

5. What is the height of the curb - here I would replace this question with the question of whether there is an entrance to the sidewalk (for wheelchair users).
By the way, this is a counterproductive solution towards the blind, which is why warning and signal strips were created to alert the blind to the end of the sidewalk.

6. Transition - tactile paving before and after the transition, it is more related to what I wrote above, the warning about the end of the sidewalk.
The transition should have a tactile guide line in the middle - does it or doesn't it?

7. Does the crossing have signaling for the blind?
If the mapper does not have a VPN radio that activates the signaling or if he does not hear it by chance - it is activated by a blind person with a VPN radio, he will note that he does not have it, but in fact he may have it. It is an increasingly common phenomenon - newer traffic lights. It is only partially related to the button at the crossing - the button at the divided crossing, with the island, can help the blind to turn off the sound signaling on the already passed route.

8. It can also help not only the blind, or to the visually impaired, if it were mapped out that the crossing has a traffic light for cyclists - a traffic light at eye level, the visually impaired can see it better, it helps cyclists, pedestrians must watch out for cyclists, scooters...

9. Some crossings have reinforced lighting or even light down between the zebra stripes (Cíglerova, Prague 14, on the bridge), possibly. the zebra has a reflective coating, it can be seen even in the dark (Prague-Dolní Počernice experiment)

10. I would also note sound beacons for the blind, they are usually found on bank buildings, offices (Magistrates, courts, banks...), post offices, schools, or at entrances to the subway or even inside subway stations or at transport hubs - railway stations, train and bus, serve for orientation.

11. ATMs - I would note that the ATMs are sound, so far ČSOB and Česká spořitelna.

12. What is the type of passage. I don't know if there is information in the supplementary questions, for example, that there is a lowered ceiling in the passage.

13. Toilet - I would mark the toilet with a euro key - the list can be found on the NRZP - website of the National Council of the Disabled - guarantor of issuing keys and administration. Important especially for the blind, but also for wheelchair users and e.g. for ostomies. v and z question: Are the toilets accessible to people in wheelchairs? Just add the euro key - it also means that you don't have to pay for the toilet and that it is a separate barrier-free room.

14. in what way is the cycle path incorporated on the pavement?
The question is fine, but please - are there sidewalks where cyclists are allowed (tolerated) to ride ... please mark these roads as potential bike paths.
However, the worst for us visually impaired are rolling scooters anywhere - the danger of falling over these vehicles!!!

14. Does this place have disabled access? I would specify - for wheelchair users or the blind, or other disabilities, e.g. the deaf - the hall in the building has an induction loop that helps the hearing impaired hear, information boards for the deaf ... you can familiarize yourself with this in the relevant documents on making spaces accessible - exteriors and interiors .

Thank you for any comments you may have.

### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by matkoniecz** [comment]
> What is the tzu surface - eg roads¨
> I miss cement concrete tiles (does not apply to the blind)

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/drawable-xxhdpi/surface_paving_stones.jpg answer is covering this, right?

**Comment by matkoniecz** [comment]
(in general, it would be much better as a separate issues, not as a big grab bag)

**Comment by matkoniecz** [comment]
> Question: Does this stop have tactile paving - the setting is not displayed in the Czech Republic.

Are you sure? From looking at https://github.com/streetcomplete/StreetComplete/blob/ca49fcf063960f18ea21aee5b9ef77107b0c719b/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingUtil.kt#L10 it should be active there...

**Comment by maper64** [comment]
I thought this information should appear in this question because bus or
tram stops are not marked with tactile paving in the Czech Republic. It is
possible that there may be a warning line of pavement at the edge of the
pavement, but it may also be elsewhere and should not signal that it is a
public transport stop.
Thank you. Miloš

po 30. 10. 2023 v 15:17 odesílatel Mateusz Konieczny <
***@***.***> napsal:

**Comment by maper64** [comment]
I thought this information should appear in this question because bus or
tram stops are not marked with tactile paving in the Czech Republic. It is
possible that there may be a warning line of pavement at the edge of the
pavement, but it may also be elsewhere and should not signal that it is a
public transport stop.
Thank you.

po 30. 10. 2023 v 15:17 odesílatel Mateusz Konieczny <
***@***.***> napsal:

**Comment by matkoniecz** [comment]
> I thought this information should appear in this question because bus or
tram stops are not marked with tactile paving in the Czech Republic.

So you wanted to comment that   bus stop tactile paving should be no longer displayed in the Czech Republic, and that asking it is pointless, right?

**Comment by matkoniecz** [comment]
> Barriers - in the Czech Republic, they can be supplemented with so-called additional sound signaling for the blind. 

Where change would apply in StreetComplete?

-------------

https://github.com/streetcomplete/StreetComplete/issues/5343#issuecomment-1785311446 - remains unanswered

**Comment by maper64** [comment]
Yes, exactly.In the Czech Republic, stops were never highlighted with
pavement. the security lines, for example, on train platforms at stations
are something else. Thank you.

po 30. 10. 2023 v 17:11 odesílatel Mateusz Konieczny <
***@***.***> napsal:

**Comment by maper64** [comment]
In an additional question: does the protected crossing have additional
sound signaling for the blind? Thank you.

po 30. 10. 2023 v 17:12 odesílatel Mateusz Konieczny <
***@***.***> napsal:

**Comment by westnordost** [comment]
Alright, so as @matkoniecz wrote, issues need to be actionable. Braindumps like this should go into the discussions forum. But anyway, I've briefly looked at all your points and here are some short answers.

In general, for most points:
- use the openstreetmap forum or tagging mailing list for discussion and proposal of new tagging
- use the quest suggestion template when suggesting a new quest. **Important**: read the linked quest guidelines. Not everything that *can* be tagged in OSM should/can be available in StreetComplete as quests. Actually, none of what you propose would fulfill the quest guidelines of this app.

---

1. tactile paving quest for public transport stops is _already_ enabled in Czech Republic
2. sound signals for the blind quest is _already_ enabled everywhere
3. "paving stones", "concrete, "concrete plates" and "concrete lanes" can _already_ be selected in the app
4. would not fulfill quest guidelines
5. we can only present answers in SC what can be tagged in OSM
6. if I understand your request correctly, it's not possible to do this in SC
7. discuss new tagging proposals in the forum or mailing lists; would not fulfill quest guidelines
8. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines
9. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines
10. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines
11. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines
12. For tunnels and other places with height restriction, the height is _already_ asked
13. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines
14. it is _already_ asked whether a shared foot- and cycleway is segregated or not. For sidewalks on which cyclists are allowed, see issue #4913. Basically, I proposed a solution but I am not sure if there is enough community support for that (I got very little feedback on this, and the feedback I got mostly consisted of additional wishes)
15. discuss new tagging proposals in the forum or mailing lists;  would not fulfill quest guidelines

In general, it seems like for most of what you propose, there is no tagging documented in OpenStreetMap yet and thus has to be discussed first. Also for most of what you propose, it would not fulfill the quest guidelines and hence, could not be includedin StreetComplete as a quest. 
So, after you discussed these things in the community forums, it looks like it would make more sense to make it possible to tag these things in a specialized app for blind and/or wheelchair users, best an app that these people use daily anyway for orientation. There is at least openwheelmap.org, I don't know if there is anything related to visual impairment.
