### ISSUE TITLE
Unterstand Haltestelle 

### ISSUE THREAD

**Issue by Falco2two** [streetcomplete/StreetComplete#5352]
Der Bereich Haltestelle enthält automatisch einen Unterstand, so weit so gut.
Da die Haltestelle eine Endhaltestelle ist, ist dort kein Unterstand zu finden.

Bei Beantwortung der Frage Unterstand ja/nein mit Nein antwortet kommt als nächste Frage ist der Unterstand beleuchtet. Dies ist logischerweise falsch.

Mfg Patrick

**Comment by qugebert** [comment]
Sorry, so ist das nicht wirklich nachvollziehbar, hast du ein konkretes Beispiel dafür?

**Comment by qugebert** [comment]
Also offenbar dieser Changeset: https://www.openstreetmap.org/changeset/143524258
Die Fragestellung kann ich trotzdem noch nicht nachvollziehen. Für den dazugehörigen Quest "AddBusStopLit" finde ich nur den Titel "Ist diese Haltestelle beleuchtet?" aber keine Fragestellung mit "Unterstand" im Titel.

**Comment by HolgerJeromin** [comment]
Ich würde spontan sagen, dass sich der Ersteller hier verlesen hat und die Frage jedoch korrekt war.

**Comment by Falco2two** [comment]
Sorry der Fragesteller wollte auch keine riesen Diskussion hervorrufen :-)

Ich wollte nur mitteilen das nach dem Nein trotzdem - für mich - die falsche Abfrage kam. Wenn es nochmals so ähnlich passt schaue ich mir das noch einmal an und werde berichten!

**Comment by westnordost** [comment]
Sieht so aus als wurde sich hier verlesen, ich schließe das mal.

Der deutsche Text ist _"Ist diese **Haltestelle** beleuchtet?"_
