### ISSUE TITLE
Clarify the English text of the "on-site" warning

### ISSUE THREAD

**Issue by MattRC7** [streetcomplete/StreetComplete#5353]
**Use case**
I am brand new to contributing to OpenStreetMap (hi! 👋). Today I drove to pick up a pizza and noticed the store wasn't marked. I wanted to get home quick while the Pizza was hot. When I got back I tried to add the Store and encountered this warning:

![Screenshot_20231102-204455_1.png](https://github.com/streetcomplete/StreetComplete/assets/6463042/e1ee3977-f57a-45e8-b024-9a7174f9355b)

> Alt: Are you sure checked this on-site? Only information that was found on a survey should be entered.

As a total newbie, I have no idea what qualifies as a "survey," so I panicked and discarded my contribution. I checked the StreetComplete FAQ and did not find an answer.

**Proposed Solution**

I think there are a couple ways to help newbies like myself:
- If survey just means "in-person" add the words "in-person" somewhere in the message. Maybe even replace "survey" with "in-person".
- Add a note in the warning to see the FAQ for more info, and update the FAQ to explain what the warning means.

**Side Note**

This is a wonderful app and I appreciate all your hard work!

**Comment by mnalis** [comment]
Thanks for you feedback @MattRC7! While the term _"survey"_  might seem perfectly clear to people (like myself) who have been doing maps for some time ([obXKCD](https://xkcd.com/2501/)), it is very valueable to get feedback from new users who have not (yet :smiley_cat:) been _"contaminated"_ with such knowledge.

Indeed, it seems like a hard word -- one just have to look at [Survey](https://en.wikipedia.org/wiki/Survey) and [surveying](https://en.wikipedia.org/wiki/Surveying) on wikipedia, e.g.

> Surveying or land surveying is the technique, profession, art, and science of determining the [terrestrial](https://en.wikipedia.org/wiki/Land) [two-dimensional](https://en.wikipedia.org/wiki/Plane_(mathematics)) or [three-dimensional](https://en.wikipedia.org/wiki/Three-dimensional_space#In_Euclidean_geometry) positions of [points](https://en.wikipedia.org/wiki/Point_(geometry)) and the [distances](https://en.wikipedia.org/wiki/Euclidean_distance) and [angles](https://en.wikipedia.org/wiki/Angle) between them
> [...]
> Surveyors work with elements of [geodesy](https://en.wikipedia.org/wiki/Geodesy), [geometry](https://en.wikipedia.org/wiki/Geometry), [trigonometry](https://en.wikipedia.org/wiki/Trigonometry), [regression analysis](https://en.wikipedia.org/wiki/Regression_analysis), [physics](https://en.wikipedia.org/wiki/Physics), engineering, [metrology](https://en.wikipedia.org/wiki/Metrology), [programming languages](https://en.wikipedia.org/wiki/Programming_language), and the law. They use equipment, such as [total stations](https://en.wikipedia.org/wiki/Total_station), robotic total stations, [theodolites](https://en.wikipedia.org/wiki/Theodolite), [GNSS](https://en.wikipedia.org/wiki/Satellite_navigation) receivers, [retroreflectors](https://en.wikipedia.org/wiki/Retroreflector), [3D scanners](https://en.wikipedia.org/wiki/3D_scanner), LiDAR sensors, radios, [inclinometer](https://en.wikipedia.org/wiki/Inclinometer), handheld tablets, optical and digital [levels](https://en.wikipedia.org/wiki/Level_(instrument)), subsurface locators, drones, [GIS](https://en.wikipedia.org/wiki/Geographic_information_system), and surveying software

If I were not in that field for some time, I'd be thoroughly confused too if it applied to me as a random person with smartphone and StreetComplete app, or not!

---

Would `Only information that was found in-person should be entered.` be clearer, @MattRC7? 

Or (especially from native English speakers), any corrections / better suggestions?

**Comment by MattRC7** [comment]
Sorry for the response delay, GH notifications were disabled on my phone for some reason.

I think your suggestion is nearly spot-on! I'd just make one small tweak:


> Only information that was *verified* in-person should be entered.


I think "verified" (or alternatively "confirmed") sufficiently gets the point across that an in-person survey occurred at some point, regardless of whether you knew the information beforehand, and regardless of whether you entered the data after you left.

**Comment by mnalis** [comment]
Thanks @MattRC7, `Only information that was verified in-person should be entered.` indeed sounds better to me!
