### ISSUE TITLE
edit rate limits is coming (429 error)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5358]
at least mass manual upload hitting rate limit may benefit from some error message

https://github.com/openstreetmap/openstreetmap-website/pull/4319

It seems some StreetComplete users may actually hit this limit ( https://github.com/openstreetmap/openstreetmap-website/issues/2342#issuecomment-1784825890 ), though maybe it is rare enough that just generic error is enough

**Comment by zstadler** [comment]
The planned maximal rate for new users is 1000 changes/hour or 17 changes/minute.
https://github.com/openstreetmap/openstreetmap-website/pull/4319

Is this rate practically achievable with the kind editing performed in StreetComplete?

**Comment by Helium314** [comment]
Some people do extensive journeys without using internet connection. When back home, upload happens over wifi and can certainly be above the limit.
But this is very unlikely to happen for new users, unless someone decides to create a new account and go on a long offline survey immediately.

Though if the limit is enforced on a by-minute base, then everyone may exceed it when doing a few changes offline.

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/openstreetmap-website/issues/2342#issuecomment-1784825890 links example user (not checked whether their edits look plausible)

> Is this rate practically achievable with the kind editing performed in StreetComplete?

new user edits in offline mode, connects to wifi and uploads everything in one go? But that would require quite extreme early survey

**Comment by matkoniecz** [comment]
oh, thanks for update! In such case I guess it can be closed?
