### ISSUE TITLE
Disallow splitting a way in case of junction=roundabout

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5372]
Splitting a roundabout causes relations including it to break in certain edge cases. A StreetComplete-specific workaround might be possible to avoiding SC triggering this issue in the future : Split way functionality could be disabled on ways tagged with `junction=roundabout`.

Then little less data would be collected by the StreetComplete (e.g. roundabouts that only have partial sidewalks would not get sidewalk information), but it would avoid those kind of breakages. 

# **How to Reproduce**
Split a `junction=roundabout` that is part of a route relation and that is a full circle, i.e. is a roundabout that does not consist of several way segments.

The resulting roundabout will be split correctly, but the route membership will be wrong.

# **Background**

[wiki](https://wiki.openstreetmap.org/wiki/Relation:route#Bus_routes_and_roundabouts) seems to indicate that only two usages are to be used in such cases of roundabouts in relations.

Either:

> The whole roundabout is included in the route relation.
> while this is technically wrong (as bus would not in reality make one and a half circle to pass that roundabout as the visualization shows), it seems to be allowed and used by some mappers (likely because it is simpler to do). It may also be the case that data consumers have a special kludge to handle that situation (e.g. treat that whole roundabout way as an one simple node?),

or

> The roundabout is split and the part used by the bus route is included in the route relation.
> this is the only technically correct way to indicate exactly which part of the route the bus will actually take (and should IMHO always be used when adding roundabouts to the relations).

If the latter (technically fully correct) way of adding a roundabout to the route is used, after splitting the roundabout will always remain correct as it was. (that is fundamental definition of relations, that it does not matter of how many small parts it is comprised if they make the exact same geometry in the exact same order).

However if former (technically incorrect / oversimplified) way of adding a roundabout to the route is used, any splitting of the roundabout will expose that underlying wrongness even more (as less data consumers are likely to have kludge for that situation too). Note that anything that splits the roundabout in this case will always “break” the relations, as the tools can’t know that the original mapper “lied” when they created the relation. This is AFAICT what seems to have happened in this changeset.

(copied from https://community.openstreetmap.org/t/auftrennen-von-strassen-mit-sc-vs-opnv-relationen/105872/26 )

# **Expected Behavior**

User should either not be able to split`junction=roundabout`, at least those that are part of a route relation, or the splitting algorithm should properly deal with the described edge case.

# **Versions affected**
This particular example was made by StreetComplete 55.0 (see version `#19` [here](https://pewu.github.io/osm-history/#/way/28446137) ). However, this affects every version of StreetComplete in which it is possible to split ways.

**Comment by matkoniecz** [comment]
I see no way to split such ways without any negative side effects, at least no way without introducing extremely complex processing.

I guess that users can leave notes?

**Comment by Helium314** [comment]
Is this really also an issue for closed footways? Given that mapping closed sidewalks around entire block is quite common, not being able to split those might be quite annoying.

From the discussion I understand that the issue is with closed roundabout ways, where the route relation would need to contain forward and backward members after the split (and likely additional splits need to be done).
Does this also apply to non-closed roundabout ways?

**Comment by westnordost** [comment]
Sorry, @mnalis, you misunderstood me, I corrected the starter post. It's all your own words, so it should be fine.

**Comment by westnordost** [comment]
The workaround solution would likely disable splitting *all* closed roundabouts (and circulars?), regardless if there is a route relation on it or not.

Before anything is done:
- is the cited section of the wiki something that has been approved? Any related discussions to it (that e.g. explain how data consumers are supposed to deal with this?)
- Did this topic come up before in discussion during implementation for splitting ways?
- (I am contemplating whether it would be worth actually implementing the necessary algorithm to fix the relations automatically in this case... anyone interested in dirtying his hands on this? - e.g. writing test cases that should prove the TBD implementation to be correct.) In that regard, is any editing software known that handles route relations on splitting closed roundabouts correctly?

**Comment by mnalis** [comment]
> is the cited section of the wiki something that has been approved?

I've noticed in the wild, and also stumbled upon several threads which talk of it as accepted practice (even prefered in cases where there is no strong other reason to split them), e.g.:

- https://community.openstreetmap.org/t/mapping-q-relation-which-uses-part-of-roundabout/48282
- https://community.openstreetmap.org/t/aufraumen-von-routen-relationen/84364
- https://community.openstreetmap.org/t/kreisel-und-routen-kreisel-in-de-wiki/84377
- https://help.openstreetmap.org/questions/2751/roundabouts-as-part-of-bus-routes-or-cycle-routes-or
- https://wiki.openstreetmap.org/wiki/Talk:Tag:junction=roundabout#Splitting_roudabouts
- [[OSM-talk] Roundabouts - why is a separate segment required? (2018)](https://lists.openstreetmap.org/pipermail/talk/2018-February/080127.html)
-  [[OSM-talk] How to integrate a roundabout into a relation (2009)](https://lists.openstreetmap.org/pipermail/talk/2009-January/033517.html)


I have not read them in detail, though.

> Did this topic come up before in discussion during implementation for splitting ways?

-  this commit attempted to implement _"do not show option to split way for closed roundabouts"_: https://github.com/streetcomplete/StreetComplete/commit/e87c0a7321449752875a0c31722e411ac6b57d30

There is also of interest this thread: 
- https://community.openstreetmap.org/t/wege-trennen-mit-streetcomplete/87820/11 (by @westnordost in 2019, which seems to discuss current implementation if I'm reading it correctly?) 

> I am contemplating whether it would be worth actually implementing the necessary algorithm to fix the relations automatically in this case


I wouldn't say it's worth it - the gains are minimal, it seems very complex (if at all possible! note that e.g. PTv1 and PTv2 seem to require different handling) to implement in 100% error-free way, and some people will _still_ prefer whole roundabouts and revert such edits to that state even when technically correct. Especially that social aspect speaks against it; so it is IMHO better just not to touch them.

**Comment by westnordost** [comment]
Thank you for the detailed look into the topic! Particularly https://community.openstreetmap.org/t/wege-trennen-mit-streetcomplete/87820/11 is helpful where also this exact topic was discussed and which included a possible implementation in pseudo-code which I'll paste here for reference

```
if the way is closed, it has the tag junction=roundabout and it is a member of a route relation, then:

1. before the way is split up:

  for each route relation the way is a member of:
    find the nodes that connect the neighbouring ways to this way, if any
    add these nodes to the nodes at which the way is split up

2. when the relations of the way are updated with the splits:

  for each route relation the way is a member of:
    find the nodes that connect the neighbouring ways to this way, if any
    find the splits that connect to these nodes, if any
    if splits are found that connect to both neighbouring ways:
      select a sublist of splits spanning between the previously found splits
      order this sublist according to its neighbours in the relation
      replace the way with the sublist of splits
   otherwise:
      update this relation normally (=replace way with all splits)

* connect means usually first or last node of way 1 equals first or last node of way 2.
   However, if the way is a closed roundabout, it may be any node.
```

Back then, the conclusion was to not let users split up a way that is closed and a `junction=roundabout`, so it seems that the fact users are currently able to do that is simply a bug that was introduced later.

Hence, I should just fix that bug and add the workaround as suggested by you in the starter post back in place.

**Comment by HolgerJeromin** [comment]
If this is revisited later we could think about P shaped ways with route relations, too. But they should not be too often:
```
|
P
|

**Comment by HolgerJeromin** [comment]
For example splitting this way (prepend this would be one single P shaped OSM):
![image](https://github.com/streetcomplete/StreetComplete/assets/2410353/f7d370ef-a912-4c2b-b128-5779c52d3fe7)
I think after splitting the following part should perhaps not be part of a route relation:
![image](https://github.com/streetcomplete/StreetComplete/assets/2410353/a1dff8ce-9902-4d92-843b-93efc8e2e3b8)

But perhaps the P shaped way is wrong in a route relation in the first place.

**Comment by matkoniecz** [comment]
>  I think after splitting the following part should perhaps not be part of a route relation: 

why? If relation was initially valid then it should still be  a member
