### ISSUE TITLE
add building=civic

### ISSUE THREAD

**Issue by MakiWolf** [streetcomplete/StreetComplete#5379]
**Use case**

building=civic seems to be missing in SC.

https://wiki.openstreetmap.org/wiki/Tag:building%3Dcivic

**Proposed Solution**

add in building quest

**Comment by MakiWolf** [comment]
Not an issue, you can also select header category civic building and upload it.

**Comment by mnalis** [comment]
Updated the [SC FAQ: Building Type Quest - Why don't I see the right types?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types%3F)
