### ISSUE TITLE
Show nearby toilets when asking if mall has a toilet

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#5381]
1. Touch the icon for the quest, which asks if the mall has a toilet.
2. Now you see the mall highlighted and the question.
3. It would be nice if all nearby toilets would be highlighted now, too.

**Proposed Solution**

As with other quest, which highlight nearby similar features, it would be nice to have this for the quest mall/toilet, too.

**Comment by westnordost** [comment]
What you describe, is not a use case, though. "It would be nice" is not a use case.

**Comment by Strubbl** [comment]
ok

**Comment by qugebert** [comment]
I guess the use case is, that it might be easier to answer when you get a hint, where to search for a toilet.
