### ISSUE TITLE
Add enclosed terrace in France

### ISSUE THREAD

**Issue by retiolus** [streetcomplete/StreetComplete#5385]
**Use case**
Many shops in France have enclosed outdoor terraces, but it is not currently possible to define them in "What kind of building is this?" quest.

See: 
[image](https://westnordost.de/p/186769.jpg)
[image](https://westnordost.de/p/186768.jpg)

**Proposed Solution**

As [I've been told](https://www.openstreetmap.org/note/3992033#map=19/48.84553/2.35228), this should be tagged as :
```
building:levels=1
building=retail
material=glass
roof:levels=0
```

Would be cool to have a default in "Other" section in "What kind of building is this?"

**Comment by westnordost** [comment]
In this case, you can answer "Retail building".

**Comment by matkoniecz** [comment]
no answer will specify `material`, with building levels enabled quest you will be (IIRC) asked about `building:levels` and `roof:levels` (and no building type quest answer tags those)

**Comment by matkoniecz** [comment]
In general, having separate values for each `material` `building:levels` `roof:levels` in building type quest would not work well.
