### ISSUE TITLE
"Who is allowed to park here? Parking may be free or paid." - Disabled spaces?

### ISSUE THREAD

**Issue by PriceChild** [streetcomplete/StreetComplete#5392]
I found it confusing when I tried to answer this question a while back. https://www.openstreetmap.org/note/3723134#map=19/52.48181/-1.89864 was the note I [left](url).

The options are:
* Any member of the general public
* Any person visiting a specific place (e.g. customers only)
* Only individual(s) with permission

None of these options appear to describe a public parking space restricted to disabled people only? (Who might e.g. need to display a blue card)

This question appears after "What kind of parking is this?" (car park, adjacent to carriage way etc.)

Looking at https://www.openstreetmap.org/way/83021790 I see [parking_space](https://wiki.openstreetmap.org/wiki/Key:parking%20space?uselang=en-GB) already has [disabled](https://wiki.openstreetmap.org/wiki/Tag:parking_space%3Ddisabled) option which accurately describes the space. There are other items on the parking_space list that I would struggle to put into the 3 categories above. (e.g. is any ambulance in an emergency parking space an "individual(s)"?)

**How to Reproduce**
Find a "Who is allowed to park here? Parking may be free or paid." quest on a disabled spot. Try to answer it.

**Expected Behavior**
Clearer guidance over how to answer for a restricted parking space (Which isn't necessarily free or paid) for example disabled spots, emergency vehicles etc.

**Versions affected**
v53.0 - v55.0 at minimum

**Comment by westnordost** [comment]
Before you left the note, the parking was tagged with

```
amenity=parking
capacity:disabled=yes
parking=surface
source=survey
```

`capacity:disabled=yes` just means _"there are parking spaces for disabled people"_.

When you created this issue ticket, you looked at the current version of that way, which now is `amenity=parking_space`. StreetComplete does not ask anything for `parking_space`s. Someone changed the was in response to your note. 

There are many other possible and complex restrictions on parking in general, the question is really just about whether it is a public parking or not. Or in that case, a public, private or customers parking. Disabled parking spaces exist both for customer parking and public parkings.
 Do you have an idea for another wording that makes clear that this question is about that, and not about restrictions?

**Comment by PriceChild** [comment]
Cool, I think that makes sense.. but I don't know how to suggest new wording because I'm still not sure what the right answer would have been.

What is the right answer in this case? (A parking space on the side of the road that somebody with a disabled badge could use) The first option?

What osm tag does the question change?

**Comment by matkoniecz** [comment]
I would say that for places fully reserved for disabled SC should not ask as this is too confusing and for fully reserved for disabled user should leave a note...

**Comment by wielandb** [comment]
If I can give my 2 cents here to answer your question. A parking place beeing disabled people only is the same thing as a parking space beeing restricted to certain types of vehicles etc.

You can still answer the quest if you like under the new question "Which disabled people are allowed to park here?"
Because a disabled parking space can still be either 
- public (all disabled people are allowed to park there)
- customers (all disabled customers are allowed to park here)
- private (only certain disabled people are allowed to park here, e.g. certain parking permits)

Of course, if you are unsure if the disabled only circumstance is recorded at all, you can still leave a note. :)

**Comment by westnordost** [comment]
Well, I will close this, then.
