### ISSUE TITLE
New translation contributors not accepted?

### ISSUE THREAD

**Issue by hohMiyazawa** [streetcomplete/StreetComplete#5393]
When following the [instructions for helping translating StreetComplete](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app), I get the following message at POEditor:

> This project can't accept new contributors at this time. Please try again later.

I can't seem to find any documentation as to why translation has been disabled. Maybe update that?

**Comment by hohMiyazawa** [comment]
After selecting the languages, regardless if I'm signed in ("Join translation"), or not ("Create account and join translation")

**Comment by hohMiyazawa** [comment]
Changes nothing. (with a fresh browser cache)

Exact steps:
![step1](https://github.com/streetcomplete/StreetComplete/assets/58218853/865605eb-5f7d-4982-a42f-566a54426597)
![step2](https://github.com/streetcomplete/StreetComplete/assets/58218853/53f9b2ec-550c-4766-b668-c1fb9e804763)
![step3](https://github.com/streetcomplete/StreetComplete/assets/58218853/7e6a9cc7-ae29-4b2b-8706-faba37d09d69)

**Comment by westnordost** [comment]
Alright, I send them an email about it, let's hope they get back to me soon.

**Comment by westnordost** [comment]
They answered that indeed they changed some limits on free accounts but removed the limitation for my account again because my account is used for a FOSS project. Can you join now?

**Comment by hohMiyazawa** [comment]
That did indeed resolve the issuel

**Comment by westnordost** [comment]
Thanks for reporting it! Who knows how long this would have persisted otherwise.
