### ISSUE TITLE
Ask if `amenity=car_sharing` is still there

### ISSUE THREAD

**Issue by dreua** [streetcomplete/StreetComplete#5399]
It has been briefly mentioned in the original "is it still there" issue (#2074) but hasn't been implemented or discussed any further.

I assume it would be quite easy to add it to the "Is x still there" quest.

> I've just opened a few notes for car sharing stations which are probably gone. Would be useful to add this imo.

_Originally posted by @dreua in https://github.com/streetcomplete/StreetComplete/issues/2074#issuecomment-1841807400_

**Comment by catdogmat** [comment]
Hi, I'm going to start working on this.

**Comment by catdogmat** [comment]
PR #5400 will fix this issue.
