### ISSUE TITLE
Check for Stages of decay

### ISSUE THREAD

**Issue by Un1matr1x** [streetcomplete/StreetComplete#5402]
### General
Affected tag(s) to be modified/added: [https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_decay](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_decay)
Question asked: **Does this  really not exist anymore? {{object}}**
asked for [demolished:*](https://wiki.openstreetmap.org/wiki/Key:demolished:*)=*  [removed:*](https://wiki.openstreetmap.org/wiki/Key:removed:*)=* [razed:*](https://wiki.openstreetmap.org/wiki/Key:razed:*)=* [destroyed:*](https://wiki.openstreetmap.org/wiki/Key:destroyed:*)=* 

{{object}} might / could be generated from _lifecycle_prefix:*\*=\**_ f.e.:
removed:building » building
destroyed:amenity=bench » bench
for easier wording / naming of {{object}} i guess your dictionary of OSM map features can be used.

The check should only made after a large timespan after the last edit of the item and the quest should not be enabled by default.
The idea behind this quest is to clean up obsolete data

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
» Objects like https://www.openstreetmap.org/node/8339961245/history should / could be removed
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
» Yes - remove the item
» No - remove the prefix
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
» probably not, often the answer will be yes, therefore no default activation of the quest, only for users who want to actively clean up on site
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)
as you can see on the tag-history only for buildings, the numbers are up and rising
![taghistory](https://github.com/streetcomplete/StreetComplete/assets/534448/c192112b-9e6f-492c-a2ab-36e6cc38d734)
If we assume a duration of 5 years from tagging to removal, this would potentially mean up to 20,000 buildings in 2024 that were tagged accordingly in 2019 (statistically not a correct interpretation of the graphic, but sufficiently imprecise for a first impression of possible quest targets)

### Ideas for implementation

**Element selection:** 
`nw[~"^removed:.*$"~"."]({{bbox}});`
`nw[~"^destroyed:.*$"~"."]({{bbox}});`
`nw[~"^razed:.*$"~"."]({{bbox}});`
`nw[~"^demolished:.*$"~"."]({{bbox}});`

**Metadata needed:** 

**Proposed UI:**
Just a short text, in the same style like "Does this still exist"

- [ ] Other Answers (Hide)
- [ ] No
- [ ] Yes

**Comment by matkoniecz** [comment]
` removed:building » building` this get recreated exceedingly rarely

**Comment by Un1matr1x** [comment]
> this get recreated exceedingly rarely

this depends where you live I guess, but that's my point - if something is removed/razed/... for a long time, we should remove it from OSM

The "long time" (period to be clarified) is needed, that the object to remove isn't visible on f.e. satelite images, to prevent readding by maping from images

**Comment by wielandb** [comment]
Could you clarify what this quest should do? Am I understanding correctly that the quest should delete the object if the user answers positively?

**Comment by matkoniecz** [comment]
> that the object to remove isn't visible on f.e. satelite images, to prevent readding by maping from images

Yes, I agree (and do this occasionally, with active looking for candidates). But it is not a good fit for SC quest.

How SC user would guess from surveying location whether it is visible on aerial imagery?

**Comment by arrival-spring** [comment]
I suggested, #3158, something like this a while ago.

I think it would be best limited to only certain things, e.g. telephones, benches etc. and the filter would need to exclude where it is now something different (e.g. `disused:amenity=telephone` and `amenity=public_bookcase`)

**Comment by Un1matr1x** [comment]
> Could you clarify what this quest should do? Am I understanding correctly that the quest should delete the object if the user answers positively?

Yes, this Quest would have to remove objects, if the answer would be: "yes it doesn't exist anymore"


> How SC user would guess from surveying location whether it is visible on aerial imagery?

SC Users would not be able to check on the ground the aerial images, therefore the time period should be defined, how long the object has been marked as removed (no matter which prefix was used) - without having or even trying to collect exact data, I strongly assume that no aerial image available by default in OSM will be older than 5 years (fingers crossed)

> It seems unsurvivable problem to me - and as much as I would like to help in deleting historic data from OSM that have no place here, it seems not fitting into SC.

from the already mentioned #3158 seems to set the scope of SC away from this kind of quest.
on the other hand, this quest should not have the problem that objects marked as removed are "reassigned", as could be the case with disused, for example. However, I don't want to rule out the possibility that some mappers might use this approach, which could lead to collateral damage, and is therefore still not suitable for SC

**Comment by matkoniecz** [comment]
> I strongly assume that no aerial image available by default in OSM will be older than 5 years

Sadly, such assumption cannot be made as far as I know. Especially outside Europe and USA.

**Comment by Un1matr1x** [comment]
Then this is way out of scope of SC >> closed
