### ISSUE TITLE
Add option to deleted shop or office in "Is this still here?" quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5405]
**Use case**
I often find that when asked if a shop or (corporate) office is still there, I would like to completely remove the node (as is possible for telephones, vending machines, etc.).
In my area (Bulgaria), many garages were converted to shops when shop space was in short supply (early 90ies). Now that more shopping is done in larger chain shops and on internet, and parking space is in short supply, these garage shops are often converted back to garages, and will likely never be shops again. So to leave them tagged as vacant shops seems wrong to be, and will also result in them being quested again for the vacant shop quest.
Similarly, residential apartments were converted to offices in the past, and back to apartments more recently. Would be nice to remove these former offices that are unlikely to be offices ever again from the map.

![image](https://github.com/streetcomplete/StreetComplete/assets/69100427/1fb44a0a-8bc5-4943-81c1-fe6cd0f9a3b9)
(a second hand clothes shop and a beauty salon inside former garages, and former offices now used as apartments again above)

**Proposed Solution**
Below "It’s vacant…", add the answer option "It's completely gone, delete" (or "It's not a shop/office any more, delete"?) to the "Is this still here?" answer options.
In my experience, these cases almost always occur in residential buildings (esp. apartment buildings), so the answer option could only be given for nodes inside such areas, or could be omitted for shops inside `building=retail` areas and offices in `building=office` areas.

**Comment by westnordost** [comment]
Hm, it may not be clear to the user what this "delete" implies. E.g. could be interpreted as "Delete what? Delete the shop? Yes, there is no shop anymore, it is gone, it should be deleted.".

I.e., when is something "completely gone"? Well, unambiguously, when the building has been demolished, but in the case that it still stands, how should the user know what you (or us OSM mappers in general) regard as "completely gone"?

In other words, that we in OSM do not delete the node when it could become a shop, or at least an office (and similar) again but mark it as empty instead whilst we delete the node when it has been converted into an apartment, a garage or something else outside what would be selectable in the shop overlay, is a thing inherent of OpenStreetMap tagging culture, not something that a user that knows nothing of it would naturally assume.

So anyway, taking a step back, your issue is that you too often have to create a note in this case. Is this such a problem in your area?

**Comment by rhhsm** [comment]
The answer option can be phrased better (hadn't really thought about it yet) and should be confirmed by an "Are you sure?" question that also offers possibility for further clarification. Maybe "This is not a shop any more" followed by "Are you sure it is unlikely that another shop will be opened here soon?" I thought to use the word "delete" would make it clear for a bit more advanced OSM editors that that's the result of choosing that answer option.

"Delete this" is one of the most frequent notes I make, so having it as an answer option would reduce the number of notes I create, but this may be specific to my case. It's not a great problem, but I guess adding the answer option is not much work either.

**Comment by westnordost** [comment]
Hm well, what's selectable in that dialog is more than just shops.

Actually, it is planned to even expand this further, to "anything that usually has a name" or "places". See also #5152

**Comment by rhhsm** [comment]
It's very welcome to be able to add that a shop or office has changed into something else. But apartments and garages are usually not mapped separately, so I think it should be possible to answer that it has changed into something that isn't mapped (i.e. the node for it should disappear).

**Comment by Cj-Malone** [comment]
(In GB at least) I'd consider it destructive to actually delete the object if there is address data on it. We're in a decade long war for open addresses.

**Comment by mnalis** [comment]
> I'd consider it destructive to actually delete the object if there is address data on it

I absolutely agree. In fact, there are much more tags that should be preserved than just address data. 

So, even if deleting the node is implemented for those shops (which I'm not sure is a good idea); I'd forbid removal if the node contains **any tag**  which is not specifically shop-related; i.e. which is not listed in:

https://github.com/streetcomplete/StreetComplete/blob/c18d8675556657288fd968d1f211a759ab9ad957/app/src/main/java/de/westnordost/streetcomplete/osm/Shop.kt#L7

as removing such nodes would result in a unintended data loss.

- (ref: somewhat related https://github.com/Helium314/SCEE/issues/499 that mention issues in similar situations)

**Comment by rhhsm** [comment]
I agree that only information  related to the shop should be deleted.

Another case where I would have liked to be able to remove the shop info is where, in a shopping centre, two shop units had been merged into one new shop.

**Comment by westnordost** [comment]
Well, I'll rather mark this as will not fix then, as sometimes when a shop is gone, the address node should remain. It requires a full editor to see whether there is a separate address node or the address is tagged on the building already to resolve.
