### ISSUE TITLE
Bicycle parking: show other nearby parkings + provide available details

### ISSUE THREAD

**Issue by olecky** [streetcomplete/StreetComplete#5406]
**Use case**

Often there are several bicycle parkings in close vicinity, sometimes with different types of parking, or for different users. For example here: https://www.mapillary.com/app/?lat=51.300955999972&lng=3.0771475999722&z=17&pKey=314188593409217&focus=photo&x=0.5388933548076472&y=0.5993977910425428&zoom=0, there are two different types of bicycle parking next to each other, and when a question "How many bicycles can be parked here" popped up, I didn't want to answer, because I wasn't sure which one does the question apply to.

![Screenshot_20231216-152858](https://github.com/streetcomplete/StreetComplete/assets/108001288/d770603d-796e-485d-a6e7-56b1f3b280ed)

Moreover, it seems that this particular bicycle parking has had the capacity set for four years already (https://www.openstreetmap.org/node/6361816851), so I don't really know why the quest popped up. I don't see the other one on OSM. Having a clear idea which parking the question applies to, would also help debugging/spotting errors.

**Proposed Solution**

1. Make other bicycle parkings visible when answering the bicycle parking questions;
2. Add the already available details about the parking under the question (for example, "Bicycle Parking" -> "Bicycle Parking: stands, not covered", or sth similar).

**Comment by westnordost** [comment]
This is already the case. All already mapped bike parking in a certain radius are highlighted when you open the quest form. Did this stop working? Can someone confirm?

**Comment by cyclingcat** [comment]
Indeed, something strange seems to happen here. See this screenshot with some bicycle parking related quests:

![quest](https://github.com/streetcomplete/StreetComplete/assets/32601012/34ac03b4-d6a0-4eb9-8ab2-94251599fa13)

If you click on one of them ([OSM node 624717876](https://www.openstreetmap.org/node/624717876)), the symbol at one (!) of the other bicycle parking locations appears:

![yes](https://github.com/streetcomplete/StreetComplete/assets/32601012/28ce3801-9384-4b2b-86dd-d2811c26f49a)

If you click on a different one ([OSM node 699165390](https://www.openstreetmap.org/node/699165390)), no symbol appears at all:

![no](https://github.com/streetcomplete/StreetComplete/assets/32601012/b1f12d57-85c8-4cfd-aed1-7becaab70577)

(This was an arbitrary pick at an arbitrary location. I haven't investigated yet if there are any patterns behind this, but it was very easy to find such a position.)

The cycling cat

**Comment by Helium314** [comment]
That's because there is no need to show far away bicycle parkings, see
> All already mapped bike parking __in a certain radius__ are highlighted when you open the quest form

**Comment by westnordost** [comment]
Alright, so everything is working as expected
