### ISSUE TITLE
Multiplatform JSON parsing (use kotlinx.serialization-json)

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5409]
Use `kotlinx.serialization-json` for all JSON parsing. In some places in the code, the Java `org.json.JSONObject` is used to parse JSON.

### JSON is parsed in

- [`TrafficFlowSegmentsApi`](https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete+TrafficFlowSegmentsApi.kt&type=code) parses traffic flow segments from [a simple API](https://github.com/streetcomplete/oneway-data-api) 

- [`StatisticsParser`](https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete+StatisticsParser.kt&type=code)) parses user statistics from [another simple API](https://github.com/streetcomplete/sc-statistics-service)

- [`StreetCompleteImageUploader`](https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete+StreetCompleteImageUploader.kt&type=code) parses a little JSON from [an API to upload and activate photos](https://github.com/exploide/sc-photo-service)

`kotlinx.serialization-json` is already a dependency of this app.

**Comment by starsep** [comment]
I would like to work on it. 
I have branch for it: https://github.com/starsep/StreetComplete/tree/kotlinx.serialization-json with solution to TrafficFlowSegmentsApi

**Comment by FloEdelmann** [comment]
Great! Feel free to submit a (draft) pull request if you would like to receive feedback on your current implementation already :slightly_smiling_face:

**Comment by starsep** [comment]
> Great! Feel free to submit a (draft) pull request if you would like to receive feedback on your current implementation already 🙂

Done :). Draft PR: #5442
