### ISSUE TITLE
Month offset when selecting a date to filter on in the app log viewer

### ISSUE THREAD

**Issue by slasherfun** [streetcomplete/StreetComplete#5423]
**How to Reproduce**

- Open StreetComplete
- Toast menu, about, show logs
- Click on the filter menu make a selection, apply the filters
- Click on the share button on the top right
- If the filters selected include at least either debug or info, StreetComplete goes back to the map screen (crash?) or sometimes completely crashes (Android shows a message telling the app has crashed because of the bug that the developer should fix...)
- If the filters selected include at least verbose (but not debug or info), nothing happens when clicking on the sharing button
- If the filters selected only include either warning or error (or both), the sharing menu is displayed normally

In any case, there's nothing about the failed sharing tentative or the crash in the logs.

**Expected Behavior**
- The sharing options should be displayed whatever the selected log levels

**Versions affected**

56.0-beta1

**Comment by Helium314** [comment]
Looks like the time filter has some issues: `java.lang.IllegalArgumentException: j$.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0`

**Comment by slasherfun** [comment]
Good catch, doing additional testing in the filter:
- When opening the "to" date filter, default selection is 24 January 2024 (tested on 24 December 2023), which seems like an odd choice
- If I select any "to" date in January 2024, the app will crash immediately after confirming the selection
- If I select a "to" date later in December 2023 (for example 27 December 2023), no crash will occur, but exactly 0 line will be displayed (the "from" date has its default value of 24 December 0:00, so I definitely should have the lines from earlier today)
