### ISSUE TITLE
Just show name and ref as description for roads

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#5427]
For roads, I think it would be better if the `NameAndLocationLabel` showed the `name` and` ref` in preference to the `operator`.

E.g. here, everyone would know this as the "M6" (`ref`) so it should be shown as "Preston Bypass [M6]"
![Screenshot_20240101-192620~2](https://github.com/streetcomplete/StreetComplete/assets/77166354/dd730c6e-a2a3-4400-a02e-3622838a8bac)

And here simply "M6" instead:
![Screenshot_20240101-192340~2](https://github.com/streetcomplete/StreetComplete/assets/77166354/8ae242f2-9d0f-44bf-8e13-b48c67f50e74)

So for roads I think it should be
`name [ref]` or `name` (if no ref) or `ref` (if no name) and never show `operator`.

I'm asking rather than just opening a PR because I don't know if the operator of roads would actually be helpful information to show in any other countries. But even so, I would think that ref is more important than operator for roads.

**Comment by matkoniecz** [comment]
This proposed change makes sense to me.
