### ISSUE TITLE
Ask for `ref` of `railway=subway_entrance`

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5436]
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref) (for [railway=subway_entrance](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dsubway_entrance))
Question asked: **What number or code identifies this entrance?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
  → see https://taginfo.openstreetmap.org/tags/railway=subway_entrance#combinations
  → improves routing, is shown on many maps
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  → needs to tag `ref:signed = no` if necessary
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  → subway entrances are usually signed (at least in subway systems I know)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
  → https://overpass-turbo.eu/s/1FJb

### Ideas for implementation

**Element selection:**

```
nodes with
  railway = subway_entrance
  and !ref
  and ref:signed != no
```

Maybe exclude `highway = elevator`, too, as most `ref`s I've seen on elevator subway entrances are not human-readable.

**Metadata needed:** I think this can be enabled worldwide, but there might be areas where subway entrances never have a reference code.

**Proposed UI:** Similar to the bus stop ref quest.

**Related issues:**

* https://github.com/streetcomplete/StreetComplete/issues/212
* https://github.com/streetcomplete/StreetComplete/issues/4217

**Comment by Helium314** [comment]
> there might be areas where subway entrances never have a reference code

This should be checked, there are several cities where no subway entrance has a `ref` tagged: Prague, Rome, Madrid, Lissabon, New York, Mexiko City, Vienna (in some cases `ref` is tagged, but only with name of the subway line)

**Comment by FloEdelmann** [comment]
Oh, thanks for commenting. These are many more than I would have expected. Do you know that there are no subway entrance codes in these cities, or are just none entered in OSM yet?

Anyway, probably only enabling it in countries where this is common is the better approach then. Let's make this comment a collaboratively edited list of where the quest should/shouldn't be enabled (feel free to edit!)

---

Use [this Overpass query](https://overpass-turbo.eu/s/1FJs) to check for `railway = subway_entrance` nodes with and without `ref`.

### `at` :austria: Austria

:x: Vienna → `ref` tag often contains subway line instead of entrance code

### `be` :belgium: Belgium

:white_check_mark: Brussels

### `cz` :czech_republic: Czech Republic

:x: Prague → entrance codes are in `name` tag instead of `ref` tag

### `de` :de: Germany

:white_check_mark: Berlin
:grey_question: Bochum
:grey_question: Cologne (Köln)
:white_check_mark: Dortmund
:grey_question: Düsseldorf
:white_check_mark: Essen
:white_check_mark: Frankfurt
:white_check_mark: Hamburg
:white_check_mark: Hannover
:white_check_mark: Munich (München)
:grey_question: Nuremberg (Nürnberg)
:grey_question: Stuttgart

### `es` :es: Spain

:x: Madrid

### `fr` :fr: France

:white_check_mark: Paris

### `gb` :gb: Great Britain

:white_check_mark: London

### `it` :it: Italy

:grey_question: Milano
:x: Rome

### `mx` :mexico: Mexico

:x: Mexico City

### `pt` :portugal: Portugal

:x: Lissabon

### `us` :us: USA

:x: New York

**Comment by Helium314** [comment]
> Do you know that there are no subway entrance codes in these cities, or are just none entered in OSM yet?

I only checked OSM data, nothing tagged of course doesn't mean there are no refs.

Some cities with `ref`: Sofia, Tokyo, Buenos Aires, Sao Paulo, Bucharest (not much), Istanbul

**Comment by FloEdelmann** [comment]
> I only checked OSM data, nothing tagged of course doesn't mean there are no refs.

Okay, I'll change those from :x: to :grey_question: then. Thanks for the other ones, I'll add them to the list!

**Comment by Helium314** [comment]
Though I think Vienna really doesn't have any `ref`, at least I think I would remember that...

**Comment by matkoniecz** [comment]
As subway user I do not remember any in Warsaw, Poland.

**Comment by FloEdelmann** [comment]
> I've never noticed any `ref` on a subway entrance in Hamburg.

There seem to be some mapped already: https://overpass-turbo.eu/s/1FP9
But of course it's possible that not all stations in Hamburg do have them.

**Comment by FloEdelmann** [comment]
> As subway user I do not remember any in Warsaw, Poland.

Most entrances in Warsaw are tagged with a `ref`: https://overpass-turbo.eu/s/1FPa
Is this not signed at all in the stations?

**Comment by westnordost** [comment]
The green ones are elevators. For some reason they have some ref assigned, probably from an import.

**Comment by FloEdelmann** [comment]
Just some of the green ones are elevators.

**Comment by matkoniecz** [comment]
https://www.google.pl/maps/@52.2180237,21.0154454,3a,19.6y,135.89h,88.58t/data=!3m6!1e1!3m4!1sH8cuZBEMEaHlCne1COhm_g!2e0!7i16384!8i8192?entry=ttu

https://www.openstreetmap.org/node/1411552501

(`ref` may be internal, now shown, shown somewhere else and anyway I am not going to map from Google SV)

(but it matches me not noticing such codes)

**Comment by westnordost** [comment]
Team Kotlin!

**Comment by westnordost** [comment]
Rust is fine, too

**Comment by starsep** [comment]
> > Most entrances in Warsaw are tagged with a ref: https://overpass-turbo.eu/s/1FPa
> 
> https://www.google.pl/maps/@52.2180237,21.0154454,3a,19.6y,135.89h,88.58t/data=!3m6!1e1!3m4!1sH8cuZBEMEaHlCne1COhm_g!2e0!7i16384!8i8192?entry=ttu
> 
> ![screen](https://private-user-images.githubusercontent.com/899988/295655115-77cd8196-d314-4422-a0db-78842f774df9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDc3MDMsIm5iZiI6MTcwNTA0NzQwMywicGF0aCI6Ii84OTk5ODgvMjk1NjU1MTE1LTc3Y2Q4MTk2LWQzMTQtNDQyMi1hMGRiLTc4ODQyZjc3NGRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwODE2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWE5YWMyNjA4NWQzOGQ5MmY0ZDRjNWRmODQwM2VkYTczMDFiNDA0NjI4MTdlYzRlYjYyMjljMjU1NDY2NWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qfyWUx5JyyB7cLg3H2Wgx18WfFrhtm0Tj1vKw3KIDcA)
> 
> https://www.openstreetmap.org/node/1411552501
> 
> (`ref` may be internal, now shown, shown somewhere else and anyway I am not going to map from Google SV)
> 
> (but it matches me not noticing such codes)

Politechnika is one of the oldest stations. Warsaw Metro started in 1995. Politechnika was the most central station then.
Newer (especially M2) stations have better signage on platforms, undergrounds passages, and on the ground level.
Please see https://github.com/organicmaps/organicmaps/issues/1778#issuecomment-1005155500

**Comment by starsep** [comment]
> Are entrances themself having such number visible from street level?

On street level it unfortunately varies. Which might be argument for disabling quest by default. I mostly use refs while underground to exit at the right part of the intersection.

> or is it matching bus stop name suffixes?

No, they are indeed two separate numbering systems.

**Comment by westnordost** [comment]
Anyway, to me it does not look like one can assume that most subway entrances will have a ref number. Not to mention them being signed in a way that it is clear for a surveyor that a number displayed is the "ref number" of the particular subway entrance.
