### ISSUE TITLE
Don't ask about the width of highways with `foot=no` or busy streets

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5437]
**How to Reproduce**
[Here](https://www.openstreetmap.org/note/3835909) StreetComplete asked for the width of the road with the tags `highway=primary`,`foot=no`:

<img width=20% src="https://github.com/streetcomplete/StreetComplete/assets/25708359/2ecbd357-c74a-4be0-821e-66a665556e51">

[Panoramas](https://yandex.com/maps/2/saint-petersburg/?l=stv%2Csta&ll=30.456550%2C59.877800&panorama[direction]=47.162577%2C-5.048507&panorama[full]=true&panorama[point]=30.456113%2C59.877743&panorama[span]=108.894153%2C60.000000&z=19)

[Here](https://www.openstreetmap.org/way/77430298) `highway=secondary`,`foot=no`
[Panoramas](https://yandex.com/maps/2/saint-petersburg/?l=stv%2Csta&ll=30.502909%2C59.945144&panorama[direction]=333.057759%2C-5.421225&panorama[full]=true&panorama[id]=1255694444_626267057_23_1653648180&panorama[point]=30.502185%2C59.945064&panorama[span]=108.894153%2C60.000000&z=17.87)

[Here](https://www.openstreetmap.org/way/1220614498) `highway=secondary`
[Panoramas](https://yandex.com/maps/2/saint-petersburg/?l=stv%2Csta&ll=30.499960%2C59.913320&panorama[direction]=307.255324%2C-5.421225&panorama[full]=true&panorama[point]=30.500158%2C59.913234&panorama[span]=108.894153%2C60.000000&z=19)

**Expected Behavior**

1. Do not suggest measuring the width of roads with `foot=no`.

2. I'm not sure if this is a good idea for other countries, but according to the [classification of roads in Russia](https://wiki.openstreetmap.org/wiki/RU:Highway_classification), `highway =primary/secondary` in cities these are large roads, so it is dangerous and usually forbidden for pedestrians to go out on them. Outside of populated areas, sections of such roads are usually long, and it is useless to know their width.

**Versions affected**
56.0

**Comment by westnordost** [comment]
Some of these seem to be connectors, which are not really roads in that sense but just exist for connectivity. But I don't think it is possible to filter these out.

However, filtering out `foot=no` seems a good idea.

**Comment by tordans** [comment]
> Some of these seem to be connectors, which are not really roads in that sense but just exist for connectivity. But I don't think it is possible to filter these out.

This sounds like `footway=link` (and `cycleway=link`) which is an "in use" tag to segment (routing) connectivity road segments that to not have a real world representation.
* https://taginfo.openstreetmap.org/tags/footway=link#map
* https://wiki.openstreetmap.org/wiki/Proposal:Tag:footway%3Dlink
* https://taginfo.openstreetmap.org/tags/cycleway=link#map

**Comment by westnordost** [comment]
Yeah, but this is about roads.

**Comment by westnordost** [comment]
For roads, there is [`placement=transition`](https://wiki.openstreetmap.org/wiki/Tag:placement%3Dtransition), which is already filtered out.
