### ISSUE TITLE
Don't ask if path crosses barrier if the path *is* the barrier

### ISSUE THREAD

**Issue by osmuser63783** [streetcomplete/StreetComplete#5438]
Browsing through notes I just noticed a small issue where the quest how the path crosses the barrier was asked where it shouldn't be:
https://www.openstreetmap.org/note/3680127
https://www.openstreetmap.org/note/3680126

I suspect this is because the way https://www.openstreetmap.org/way/199858771 is tagged `highway=footway` *and* `barrier=city_wall`. As a result SC asks the quest on every node of the way.

Not sure how common this kind of double tagging is.

**How to Reproduce**
Look at Chester city walls:
![Screenshot_20240110_212838_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/127188803/aafba781-61a1-4785-9d2c-96d68fbd398e)

**Expected Behavior**
Don't ask the quest.

**Versions affected**
Originally reported in v52, still an issue in v56.0

**Comment by matkoniecz** [comment]
@osmuser63783

Thanks for reporting, current behaviour makes no sense and this tagging, while I would not use it, seems to not be clearly wrong.

**Comment by osmuser63783** [comment]
Wow, that was quick. Thank you!

**Comment by matkoniecz** [comment]
Note that change is not yet deployed: that requires making a new release and this bug is not big enough (see JOSM bug that in one old version swapped longitude and latitude on edit...) to justify making emergency one
