### ISSUE TITLE
Do not ask laundry quest if access=private

### ISSUE THREAD

**Issue by osmuser63783** [streetcomplete/StreetComplete#5441]
Not sure if bug report or feature request. I was under the impression that SC doesn't ask these types of quests (or any quest, really) for private features but "does this laundry provide self-service?" is asked for this laundry tagged access=private:
https://osm.org/node/8739999675

Found through a note where someone was evidently unable to answer the question: https://www.openstreetmap.org/note/3142845

(It's a year old but I still get asked the quest in v56.0)

**Comment by mnalis** [comment]
I do seem to recall the idea (of all objects with `access=private` being skipped in all quests)  being suggested,  but I don't think it was ever accepted  (of course, I cannot find that discussion now). 

So each quest adds (or doesn't add) those rules for itself currently... _"self-service laundry"_ quest happens to be one of those that doesn't check for private access:

https://github.com/streetcomplete/StreetComplete/blob/c18d8675556657288fd968d1f211a759ab9ad957/app/src/main/java/de/westnordost/streetcomplete/quests/self_service/AddSelfServiceLaundry.kt#L14

**Comment by matkoniecz** [comment]
Is it even valid to tag it this way? 

Is it private washing machine mapped there? It should be at most https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwashing_machine - and even that is dubious here

https://www.openstreetmap.org/note/4063178

**Comment by matkoniecz** [comment]
I retagged it based on provided info and opened https://www.openstreetmap.org/note/4063178

will close this issue, though without prejudice to starting filtering it out if actual case will be found (some shop on military base?)

**Comment by osmuser63783** [comment]
The Wiki says "You should tag the laundry area with [shop](https://wiki.openstreetmap.org/wiki/Key:shop)=[laundry](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dlaundry), and you can optionally tag the individual washing machines with [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=washing_machine."

I wasn't the one who mapped it, but I can see how someone who wants to map a laundry room shared by a while apartment building or housing estate would come to the conclusion, from reading the wiki, that shop=laundry fits better than amenity=washing_machine.

Of course the Wiki also says "Never use for washing machines that are not available for public use, due to [verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) and [privacy](https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information) concerns." so amenity=washing_machine access=private would contradict that.

Maybe we need a better tag for "room with multiple washing machines shared by an apartment building or housing estate". Maybe under the room key instead of amenity.

**Comment by osmuser63783** [comment]
(I've also replied to the note, in case you don't want to use the issue tracker for tagging discussions :-) )

**Comment by matkoniecz** [comment]
I will reply at note
