### ISSUE TITLE
Display Building-Level Quests Without Specifying Building Type

### ISSUE THREAD

**Issue by vankos** [streetcomplete/StreetComplete#5446]
**Use case**
I don't know if it's intentional or not, but
I've observed that without specifying the building type, there is no building-level quest. The thing is that I'm not always certain about the building type (for example, it's difficult to distinguish hostels or guest houses from private houses and apartments, or for old historical buildings, whether it's a museum, office, or government building without going inside). However, I can certainly count the number of levels in the building without knowing its type.

**Proposed Solution**

Display building-level quests even when the building type is not specified.

**Comment by HolgerJeromin** [comment]
This is intentional. 
We do not want this quest with garages, sheds (spam), roofs, churches, industrial manufacturing buildings (difficult to answer) and others.

**Comment by FloEdelmann** [comment]
See #2464 and <https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_the_house_number_quest_not_appear?>

**Comment by mnalis** [comment]
Also, see the [FAQ: Building Type Quest - Why don't I see the right types?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?)

- the quest is **not** about _what the building is being used for_, but about what is its architectural style. So, if it looks like single family home, mark it as such, even if it might currently be used as guest house or something else.
- Also, you can (somewhat non-intuitively) select the _category_ itself. So e.g. if you're not sure if that is apartment of house, just select the category `Residential` itself.
