### ISSUE TITLE
Unclear description of indoor quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5449]
I was asked "Is this within a building (OMV Petrol Station)?" about this node https://www.openstreetmap.org/node/10754518430 The node contains a `emergency=defibrillator` tag so I assume the quest is about the defibrillator. I think this is not very good tagging practice (opinions welcome), but I think SC is also in need of improvement by stating more clearly what the quest is about.
![Screenshots_2024-01-20-11-23-11](https://github.com/streetcomplete/StreetComplete/assets/69100427/e1e2c4fd-149a-4e37-90f8-7120383a3160)

**Expected Behavior**
I think the question should be "Is this defibrillator within a building?" or "Is this within a building (defibrillator)?"

**Versions affected**
v56.0 10

**Comment by matkoniecz** [comment]
I think in this case it falls under "broken OSM data results in SC behaving weirdly"

I opened https://www.openstreetmap.org/note/4078362

**Comment by rhhsm** [comment]
I think there could be good reasons to include the `emergency=defibrillator` in the node for the amenity. However, how to tag when you know there's a defibrillator in a certain place, but you don't know where, should be discussed elsewhere (in the Community Forum, I guess) so that the wiki can be updated with a recommendation.
However, I think it's also worth looking at why it "results in SC behaving weirdly", i.e. how did info on `amenity=fuel` and `name/operator/brand=OMV` end up in the question and `emergency=defibrillator` not, and if something can be improved here

**Comment by westnordost** [comment]
Well, IF that amenity has a defi but should be mapped as a property on the amenity rather than as an own feature, `defibrillator=yes` (if it existed) or similar would need to be used. (Like `bin=yes` on bus stops)

**Comment by westnordost** [comment]
> However, I think it's also worth looking at why it "results in SC behaving weirdly", i.e. how did info on amenity=fuel and name/operator/brand=OMV end up in the question and emergency=defibrillator not, and if something can be improved here

IIRC the `osmfeatures` library indeed returns a list of features that match a given set of tags. However, StreetComplete always only takes the first, IIRC the returned features are also ordered in a way that makes sense, so the first one is the "most likely" one.
As to why not display all the features returned: Wouldn't make sense, would only lead to more confusion. It only makes sense to treat one object = one feature. Many questions wouldn't make sense when asked for a combination of multiple features - "Is this tankstation / defibrillator in-doors?" for starters

**Comment by rhhsm** [comment]
Thanks for looking it up. I guess it's not worth the effort to make the feature selection smarter. I revived the https://community.openstreetmap.org/t/emergency-defibrillator/79692/8 discussion and gave you credit for suggesting to add `defibrillator=yes`
