### ISSUE TITLE
SC users add the operator=* as name=* to medical offices, but in Germany these offices in most times only have an operator=* and no name=*

### ISSUE THREAD

**Issue by fabi003** [streetcomplete/StreetComplete#5454]
Offices of physicians and therapists, at least in Germany, have in most times only an operator and no name, but SC users add the operator as name in a quest.

**How to Reproduce**

https://www.openstreetmap.org/node/3547205121/history

I fixed this POI before and than an SC user "determined place names" and added the operator only as name, so there is no real name for this office.

**Expected Behavior**

SC leave these offices out from the name=* quest. I use the operator=* tag only for the main operator, if the office is operated by more the one physician or therapist, as they are in most times not really the operators of the office and only employed by the real main operator.

The name is not mapped "for the renderer", even as many people do this.

**Versions affected**

At least StreetComplete 55.0.

**Comment by mnalis** [comment]
I'm not quite sure if I understand the issue correctly, but quick check shows that in Germany:


1. there are [295 places](https://overpass-turbo.eu/s/1GjN) of `amenity=doctors`  which has `operator` but not `name`
2. there are [23751 places](https://overpass-turbo.eu/s/1GjO) of `amenity=doctors`  which has `name` but not `operator` 
3. there are [5126 places](https://overpass-turbo.eu/s/1GjP) of `amenity=doctors` which has both `name` and `operator`, but they differ
4. there are [490 places](https://overpass-turbo.eu/s/1GjQ) of `amenity=doctors` which has both `name` and `operator` and they have the same value

Which of those taggings is preferred in Germany?

**Comment by fabi003** [comment]
I mean the cases 2. and 4.
For 4. the name=* is misused for the operator=*.
For 2. the operator may be unmapped, but in most real cases the name=*-tag is misused for the operator=*, at least I common fix such cases of misuse. This later is a common mistake and these offices are very often "mapped for the renderer", as nothing is displayed on the main map, if the name tag is empty.

**Comment by mnalis** [comment]
> For 2. the operator may be unmapped, but in most real cases the name=*-tag is misused for the operator=*, at least I common fix such cases of misuse. This later (2.) is a common mistake

Interesting, to me (as an outsider) it seems strange that by far the most popular usage (`2.`) is _"common mistake"_, while the least popular one (`1.`) is the most correct one (if I understood correctly). Was it perhaps recent change of policy?

Can you point me to the discussion where German community made that decision (or elsewhere where it is documented)?

**Comment by Helium314** [comment]
According to what is documented in wiki:
* [English](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddoctors)
  * _Tags to use in combination_ mentions "_[name](https://wiki.openstreetmap.org/wiki/Key:name)=* - The primary name: in general, the most prominent signposted name or the most common name in the local language(s)_"
  * _Useful combination_ contains `name`
* [German](https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Ddoctors)
  * _Tags to use in combination_ does _not_ contain `name`
  * _How to map_ **explicitly** asks to add a `name`
  * _Useful combination_ contains `name`

**Comment by matkoniecz** [comment]
> have in most times only an operator and no name

If there is a doctor running own cabinet, operating under their name (say, "Jacek Kowalski") with such name signposted - then I would map, as  a human directly editing tag, it as `name=Jacek Kowalski`. And also, I would treat it as a name of object.

Maybe I am editing it wrong. But can you point me some discussion or documentation that indicates that signposted name should not be treated as a name? Or that in such case sign does not count as signposted name?

**Comment by westnordost** [comment]
StreetComplete mappers are asked to add the name of the place. For doctors, the name as seen on the sign is very often the doctor's name himself.

---

Regarding the angle with `amenity=clinic`:

`amenity=doctors` was for "Arztpraxis" all along and has been documented as such since its inception in 2010. I do notice however that since recently, the **German** version of the article mentioned "Ärztezentrum" since its inception in 2015 until recently. This was simply an error. Translated versions of tag definitions should always be just, well, translations of the source article in English (plus optionally add information about the situation in this or that country), and never change the meaning of the tag.

So if you happen upon any `amenity=doctors` that ought to actually be `amenity=clinic` feel free to correct it, for it has been incorrect in the first place all this time.

**Comment by gdabski** [comment]
FWIW, the English Wiki still describes `doctors` as ranging _from a single doctor's office to larger outpatient facilities_. I would question why the German community deviated from definition in the first place.

**Comment by westnordost** [comment]
Well, I guess there is naturally a somewhat fluent transition from "single doctor's office" to "clinic". Though the line is drawn quite clearly on the OSM wiki, as it mentions that clinics have typically "10 or more doctors" and that it is a "medical centre" that does not admit inpatients, i.e. differs from (small) hospitals in that regard.

Note that the British English word "doctor's surgery" is really the German equivalent to "Arztpraxis", it does not imply that there is only one doctor:

> [...] is a [medical facility](https://en.wikipedia.org/wiki/Medical_facility) in which one or more medical [doctors](https://en.wikipedia.org/wiki/Physician), usually [general practitioners](https://en.wikipedia.org/wiki/General_practitioner) (GP), receive and treat [patients](https://en.wikipedia.org/wiki/Patient). [...]

https://en.wikipedia.org/wiki/Doctor%27s_office
