### ISSUE TITLE
Perform on-site check when opening notes

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5456]
**Use case**
Every now and then I stumble upon notes that appear weird when you assume that SC users actually visit the place where they open notes (typically they imply that the user does _not_ know the on-site situation).
It's not explicitly stated that users are expected to be where they open notes, so it's not clear whether above assumption is correct. I would like to clarify this.

**Proposed Solution**
SC is a survey tool, so an on-site check should be done when opening notes (same as when answering quests).

**Comment by westnordost** [comment]
Hm well, other than for quest answers, it is not for certain that whatever the user is going to post in a note is recording a supposed fact on the ground. After all, it is possible to just add a note with any content, not just in relation to a fact on the ground. For example, after a walk with StreetComplete, the user notices that there may be an error on the map, so he adds a note requesting for someone to check this.
Not sure how common this kind of note is in StreetComplete. You wrote that you stumbled upon many notes where the user didn't seem to be on-site. What kind of notes were these and why are you sure the user was not on-site?

**Comment by Helium314** [comment]
Ok, if SC notes are not seen as on-site thing then this issue can be closed.
