### ISSUE TITLE
Quest suggestion: post_office=post_partner tag (and related)

### ISSUE THREAD

**Issue by lodi-g** [streetcomplete/StreetComplete#5460]
Related: #2961 , I'm creating a new issue because the old one was closed due to lack of feedback and the scope of my suggestion is slightly different.

### General
Affected tag(s) to be modified/added: [post_office](https://wiki.openstreetmap.org/wiki/Key:post_office) (for the `post_partner` sub category)

Question asked: 

**1. Does this shop also provides postal services such as picking up or sending packages?**
Answer is yes/no. If yes, the tag `post_office=post_partner` is added to the node. If no, everything else is skipped.

**2. Which brands are available? Usually this is visible on the front window.**
Answer is multiple choice: DHL, UPS, Hermes Group, ([more here](https://wiki.openstreetmap.org/wiki/Key:post_office/postal_service_provider)), (free text)
The tags `post_office:brand` and `post_office:brand:wikidata` are added to the node (wikidata can not be added for the free text answer)

I'm not including the `parcel_to`, `parcel_from` and `parcel_pickup` here, because these information might be a bit complex to get from the street and their impact is limited IMHO.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) -> **Yes and no, see the problems section**.
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Problems to resolve

1. There are too many choices in the postal service provider table, and some of them are only relevant for a local area (e.g. Relais Colis in FR or Deutsche Post in DE). 

2. If the user answer "no", all other users will still have the quest even though the shop does not provide such services.

### Ideas for implementation

**Element selection:** `shop=*`, `amenity=*`, `craft=*` or `office=*` 
**Metadata needed:** I'm not sure exactly what this relates to. 
**Proposed UI:** Standard StreetComplete UI. I can draft a few mockups if you think there's interest.

Thanks for considering!

**Comment by matkoniecz** [comment]
> If the user answer "no", all other users will still have the quest even though the shop does not provide such services.

Then it fails https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md 

> 🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.
