### ISSUE TITLE
Add "Time picker style" option

### ISSUE THREAD

**Issue by vmartyanov** [streetcomplete/StreetComplete#5469]
**Use case**
When working with "Opening hours" quests I'm expecting troubles with default circular time picker: I have to hold UI element and drag it accurately, which is hard in cold weather or when I'm walking. Keyboard is much better, but I have to chose it every time!

**Proposed Solution**
Could you please add a settings for time picker style: current circular or keyboard? Users will chose what is better for them only once and will be happy with it :-)

**Comment by matkoniecz** [comment]
> and drag it accurately

note that you can also tap on the screen

See also #3796

https://github.com/streetcomplete/StreetComplete/issues/3796#issuecomment-1530533323

> I recently fiddled around with this a bit, but it didn't feel good. Just the appearance of the keyboard (and its disappearance when finished inputting) is quite disruptive. Typing 08002000 (08:00-20:00) is not really faster than tapping on 8, next, 20. So, this is no longer planned as enhancement. Anyone is of course invited to experiment with this himself.

So it seems it was attempted and can be revised if someone will prepare a working code.
