### ISSUE TITLE
Unclear fire hydrant diameter quest in Austria

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5470]
In SC 56.1 the `AddFireHydrantDiameter` quest got enabled in Austria. I checked 2 hydrants, but none of them had the necessary sign (not on the hydrant, and not nearby). I found some numbers on the hydrants (like `A100 - 16 - 1.50/E`), but none explicitly stated any kind of diameter.

The commit https://github.com/streetcomplete/StreetComplete/commit/e0e1b0476eee80221bfbf992bfd898dab355c333 added a link to images, including https://commons.wikimedia.org/wiki/Category:Fire_hydrant_signs_in_Austria.
Only on one of the three images there is a sign that looks like in the one displayed in the quest form.
On two signs on that page I cannot find a diameter at all. One of the 2 hydrants I checked had such a blue sign in vicinity, however I'm not sure whether it was actually related to the hydrant.

Is it expected that many/most hydrants will get the _not signed_ answer?

**Comment by westnordost** [comment]
> Is it expected that many/most hydrants will get the not signed answer?

At this point, neither expected or unexpected. I don't know how many hydrants would be signed in Austria.

Before this quest was introduced, I thought that every fire hydrant in Germany has this sign. Now, gut feeling, about 50% are signed.

The blue signs in Germany are as far as I know not hydrant signs but for the water supply.

Maybe if you asked in the Austrian community forum, you will get more helpful answers from Austrians? I have no problem with disabling the quest again for Austria.

**Comment by westnordost** [comment]
That's about numbering, not the hydrant diameter.

**Comment by westnordost** [comment]
Anyway, I would like to leave this in your hand. If you think it does not make sense to ask in Austria, just create a PR to disable it again. It would be nice if you asked around for more input, but in any case, both of you are more knowledgeable than me about this topic so whatever you decide has more weight than the decision I made solely base on a few pictures on wikimedia.

**Comment by hungerburg** [comment]
There might be some misunderstandings: The sign is used a lot, but not for the pillar type hydrants, instead for the underground hydrants. I made a picture showing both the sign and the hydrant and added an explanation, how to read the sign to learn the position of the hydrant. https://commons.wikimedia.org/wiki/File:Unterflurhydrant_Wegweiser.jpg

PS: The diameter (DN) of the underground pipe is of no interest for the fire brigades. They care about volume flow (l/min) and pressure. Pipe DN is not signed on over-ground hydrants. Never seen that.

**Comment by westnordost** [comment]
It looks like the vote is pretty clear, I'll remove AT again
