### ISSUE TITLE
Show `AddCrossingKerbHeight` for crossing without `crossing`

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5476]
With the recent changes to the crossing quests, `AddCrossingKerbHeight` is almost never asked because it requires a `crossing` tagged.
Since SC now tags `crossing` only for informal crossings, the quest will rarely show up when adding crossing details in SC only.

Proposed solution: skip the `crossing` requirement, or also ask if `crossing:signals` or `crossing:markings` are tagged.

**Comment by HolgerJeromin** [comment]
ref #5471

**Comment by westnordost** [comment]
Hmm, not sure why there was the check for `crossing` at all. After all, the quest is asked for any crossing, regardless of what is the value of `crossing` in the end. So, rather than to complicate the filter, I think it can simply be removed.

**Comment by westnordost** [comment]
Ah, well, the `AddCrossingType` quest was only asked for crossings that are not crossings with driveways. So, we should filter that out here, then.
