### ISSUE TITLE
Parking tags using depreciated version of tag?

### ISSUE THREAD

**Issue by CommentWalker** [streetcomplete/StreetComplete#5477]
I have been seeing deprecated tag errors popping up related to Streetcomplete entries regarding parking and wanted to see if they tag style is up to date.

According to the page 

https://wiki.openstreetmap.org/wiki/Deprecated_features

Parking tags should now be just parking:(both/right/left) instead of parking:lane:(both/right/left).  Just wanted to check if this has already been updated or not (I may be updating old errors)

**Comment by riQQ** [comment]
Should be old changes, as this was implemented at the beginning of the last year. See #4664.

**Comment by matkoniecz** [comment]
this seems fixed, thanks @riQQ 

If not - please link changeset made by v51.0 or later ( see https://github.com/streetcomplete/StreetComplete/blob/master/CHANGELOG.md )
