### ISSUE TITLE
What style of markings does this pedestrian crossing have?

### ISSUE THREAD

**Issue by CommentWalker** [streetcomplete/StreetComplete#5478]
For marked and signal controlled pedestrian crossings another tag that could be added is the style of markings (ie transverse or longitudinal lines).

The OSM wiki already has example images that would probably be fine to use as various imagery (in a similar style to the road surface type)

https://wiki.openstreetmap.org/wiki/Key:crossing:markings

**Comment by matkoniecz** [comment]
is there anything new compared to https://github.com/streetcomplete/StreetComplete/issues/4663 and #5102 ?
