### ISSUE TITLE
Lower priority for "is this place lit" quest during the day

### ISSUE THREAD

**Issue by cvate** [streetcomplete/StreetComplete#5487]
**Use case**
When solving quests during the daylight, the "Is this place lit" quest appears and has the same priority as the other quests.
It's difficult to determine whether a place is lit during the day, thus increases chances of inserting incorrect data.
As a consequence, it's distracting the user from solving the other quests which make sense.

**Proposed Solution**
Create a system where quests can be hidden or prioritized based on rules (night/day, rural/urban or region specific).
It would increase the quality of the inserted data and keep the user focused on relevant quests.

**Comment by matkoniecz** [comment]
See #3925 https://github.com/streetcomplete/StreetComplete/issues/3248#issuecomment-972375735 #1285

It was actually present and I really liked this feature but got removed.

Note that lit quest is disabled by default and we have lit overlay.

**Comment by mnalis** [comment]
Just to note to interested parties that [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) ("Expert Edition" fork of StreetComplete) does in fact offer the option to "automagically" the priority
