### ISSUE TITLE
[FR] Nudge to add a free license to uploaded photographs.

### ISSUE THREAD

**Issue by DeusFigendi** [streetcomplete/StreetComplete#5489]
Hey,
for what I found, this ist related to #3714

**Use case**
Now and then I come along an OSM-Note created with StreetComplete containing an image worth to represent the object. Well and I would love to link it somehow to the new created or just edited object in OSM. To do so I must currently ask the author frankly if she might upload it somewhere else or allow me (or the public) to do so.

In general that's fine but asking the author breaks my workflow, I am currently editing OpenStreetMap and when I'm done I'd like to close the note. And I'd like to do so at the moment and not in several hours or days or never whenever the author recognizes I asked her. For example [this note](https://www.openstreetmap.org/note/3086575) where I asked twiebke to use his(?) photograph he uploaded two years ago. I have no idea if he will ever answer, his last edit is three months ago, meanwhile I have an open OSM-Changeset which I doesn't finish, I have a browser tab open from https://openplaques.org where I'd love to add that photo… of coarse I could just send both and add the image later, but to be honest: If I did that edit/change the process is done for me and I probably wouldn't look back.

So it would be cool if those images where published under a general license so I could simply download and reupload them on a typical OSM compatible image platform. Attribution would be easy (I know the OSM account and screenname). And to achieve that those photos are published under a general license, StreetComplete could be a key element.

**Proposed Solution**
I think it would be useful if the user could decide over a simple checkbox to give her photo into the commons. I would prefer cc0 but I think cc-by is more common and would raise the acceptance rate.
A really cool way would be to brand/watermark the license and attribution into the image itself, but to be fair the easiest way would be a small note within the note just after the images url.

The choice of a license would nice but I see this isn't the core feature of StreetComplete, I add it to this request anyways.

Mockups:

![Screenshot_20240216_230416_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/1711504/30a9d498-1f98-4360-9ada-f2d75a20fb6b) ![Screenshot_20240216_230458_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/1711504/f8abd71d-2620-4df9-b277-9af03d97e8e2) ![Screenshot_20240216_2330](https://github.com/streetcomplete/StreetComplete/assets/1711504/abdf67e7-76a1-4e10-ab6d-bf68ebb6cfb7)

**Comment by matkoniecz** [comment]
Main issue is increased complexity, both in interface and in scaring away people from uploading images...

Note that you have more fun issues, like https://commons.wikimedia.org/wiki/Commons:Copyright_rules_by_territory/France#Freedom_of_panorama

**Comment by DeusFigendi** [comment]
> Main issue is increased complexity, both in interface and in scaring away people from uploading images...

Yes it does. I think it's worth it.

> Note that you have more fun issues, like https://commons.wikimedia.org/wiki/Commons:Copyright_rules_by_territory/France#Freedom_of_panorama

Why does this differ from the current situation? Don't you have these problems also if you publish without a general (free) license?

**Comment by mnalis** [comment]
> I think the image use as it happens now is covered by fair use or equivalent

I guess it depends on the country. [Croatia](https://zakon.hr/z/106/Zakon-o-autorskom-pravu-i-srodnim-pravima) for example does have exception for exterior freedom of Panorama, but not for interiors. It does however have another exception for private use, which covers interiors too, but with restrictions that it must not be (directly or indirectly) commercial in nature, and that it must not be intended or made available to public (and publishing as a link on osm.org Note would fall under making it available to public). It also would not match ephemeral copy exceptions, nor parody and similar exceptions.  So photos of interiors _might_ be problematic here, for example (if they are covered by non-expired copyrights). In countries without FoP, it might (or might not, depending on exact law) be problematic too. 

But IANAL, either. 

Perhaps CC0 would be best match? That way SC user (author of the photo) [would waive _their own_ copyrights on the photo, but it would not affect rights of any other potential copyright holders](https://wiki.creativecommons.org/wiki/CC0_FAQ#Does_CC0_really_eliminate_all_copyright_and_related_rights.2C_everywhere.3F) (e.g. of architects in countries without Freedom of Panorama)

**Comment by DeusFigendi** [comment]
> I guess it depends on the country.

You're probably right. Maybe it's still "not comercial" if one uses a more restrictive license just as cc-by-sa or cc-by-nc and maybe that also fulfills "fair use" in some countries but that might differ.

In the end it's no problem for streetcomplete or westnordost.de I think. The photos would be as long on the webspace as they are nowadays. It might be a problem for the user who's initial uploading the photo but I think if she may publish her own work for mapping purposes she should usually also have the right to grant other rights to use it.
And if someone else… me for example reuploades it at flickr or mapillary or wikicommons or mapilo or whereever… that person and that platform gets in trouble if this wasn't lawful.

But in any case I think this doesn't change anything legal for westnordost.de neither for streetcomplete and most likely not for the copyright owners (the uploaders).

By the way: [I still got no answer](https://www.openstreetmap.org/note/3086575) my changeset is still pending since a week.

**Comment by mnalis** [comment]
> But in any case I think this doesn't change anything legal for westnordost.de neither for streetcomplete and most likely not for the copyright owners (the uploaders).

I agree with that, while there are issues, they would be basically unchanged from current situation which has those same issues. (see my link to CC0 FAQ above).

The main issue I see is that StreetComplete is very averse to adding extra preferences and checkboxes (and for a good reason IMHO, given its primary target audience - and I say that even if I myself would often prefer something more complex). 

On the other hand, marking all uploaded images CC0 (or CC-BY or whatever) without asking the user would avoid making the software more complex, but might possibly be disagreeable to some users (although if I were to guess those disliking it would be a very tiny majority - I'd guess 99% of SC userbase don't care at all about OSM notes licensing, and of remaining 1% vast majority would likely be in favor of some open license - this being OSM and everything after all. But that is just my guess).

But even if such _"CC0 by default"_ were to be accepted, in addition to trivial code changes, there would probably need to be at least some notice / translation work,  to explain that new situation.

> By the way: [I still got no answer](https://www.openstreetmap.org/note/3086575) my changeset is still pending since a week.

Looking at their edit history, they only pop-in once about every 4 months, so I wouldn't hold my breath for quick answer (and also, some users never answer too)... But I feel your pain, having it sitting there and being unable to use it... the call of the Dark Side can get strong :smiling_face_with_tear:

**Comment by DeusFigendi** [comment]
> The main issue I see is that StreetComplete is very averse to adding extra preferences and checkboxes (…)
> On the other hand, marking all uploaded images CC0 (or CC-BY or whatever) without asking the user would avoid making the software more complex, but might possibly be disagreeable to some users

Yes I agree it's just a question if it's worth or not. I think I would not force users without choice.

Maybe it could add "© all images cc-by $username" to the notes textbox when an image is added, so the user can decide to remove it. That way the UI wouldn't change but user get the idea they could set their images free 🤔

On the other hand people might become irritated if they have to delete it every time they add an image… I don't know. But maybe it's worth a try and see if users complain about. (StreetComplete needs A/B-Tests… oh there's beta)

> Looking at their edit history, they only pop-in once about every 4 months, so I wouldn't hold my breath for quick answer 

Yea but that's often the problem and very often I don't ask in this cases I just waive it (so I don't use it without license). But I expect to get no answer so I just don't use it.
But it's just a pitty if the photo is of good quality and shows exactly what I would choose as a photo for that object and since StreetComplete supports image upload for a while this happens more often.

**Comment by westnordost** [comment]
Hm, I am somewhat reluctant to build more on top of the StreetComplete image upload functionality. I'd rather see effort spent towards bringing that functionality to openstreetmap.org proper. Two reasons that additionally speak for this also in context of this feature request are:

1. when posting on openstreetmap.org directly, it should be clear that photos uploaded are released under a license compatible with OSM - or at least, it is up to osm.org to make that clear.

2. StreetComplete scales down images uploaded to 1280px in width and a JPEG quality of 80% IIRC, this is not the resolution and quality one would like to have when publishing to wikimedia etc. - I expect that this limitation would be dropped if the image upload functionality would be added to osm.org proper, because, storage is cheap, at least to an organization like OSM compared to a cheap webspace rented by me.

The related tickets for openstreetmap in general are
- https://github.com/openstreetmap/openstreetmap-website/issues/395
- https://github.com/openstreetmap/operations/issues/206

I would say, the current state of this is "someone would need to implement it" and to be sure, operations should give a note about storage limits. Maybe implementation of attaching images to notes on osm.org could be a project in frame of the upcoming EWG microgrants program. It looks like the EWG are still outlining the details, but there has been a first announcement here: https://community.openstreetmap.org/t/osmf-2024-budget-project-presentation/109689

---

So, I don't consider this feature request wise because I think effort should be spent upstream (osm.org) instead. It would not only profit StreetComplete (users) but other apps and users who would like to attach more info to notes, make notes more useful in general.

I am still split whether I would accept a PR that adds an option to the settings that allows users to select a license for photos added to notes (fair use as default, cc-by, cc-0, ...). Adding a text that nudges users to use a free license would definitely make the note form too crowded. But without that, very few users will actually change the default setting to something else than "fair use", making the feature somewhat useless for people wanting to extract pictures from the osm notes and upload them to wikimedia or something.

**Comment by matkoniecz** [comment]
https://github.com/osmfoundation/ewg_bidding/issues/14 has some more specific plans

**Comment by pyrog** [comment]
> I think effort should be spent upstream (osm.org) instead. It would not only profit StreetComplete (users) but other apps and users who would like to attach more info to notes, make notes more useful in general.
❤️ 

See https://github.com/pietervdvn/MapComplete/issues/1451#issuecomment-2156685441
