### ISSUE TITLE
New quest: Is water drinkable? (drinking_water)

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#549]
[drinking_water](https://wiki.openstreetmap.org/wiki/Key:drinking_water) seems to be promising for a quest.

* [ ] Easy to answer, i.e. everyone can easily solve it (from the outside)
* [x] Easy user interface. (quite easy, depends on how much details to be implement)
* [x] Has a useful purpose. (important information)
* [x] Established tag. (seems to be; ~50 000 times used)
* [x] Low unanswerable quests. (i.e. low false positives, as every quest can be answered; at least if there is a sign)
* [x] It can be determined, if the quest is needed to be asked. (i.e. there is drinking_water=no)

It should be asked for [the things mentioned here](https://wiki.openstreetmap.org/wiki/Key:drinking_water#Applies_to_.28among_other_things.29), maybe only exclude toilets (they are too common?) and some other tags, where it is not alwayss clear that there is water at all (i.e. rest_area/camp_site).

### UI
> **Is the water of this \<type\> drinkable?**
> [Yes] | [No] | [A sign says it is drinkable]

**Comment by rugk** [comment]
Okay, problem: I just read through the wiki and the legal situation seems to be complex and it does not seem to be easy in every cases to decide whether it is drinkable or not…

So closing…
Still I at least have a checklist for new quest proposals, now…

**Comment by rugk** [comment]
@Binnette Just convince me that it *is* possible…

**Comment by rugk** [comment]
(And don't say: Just drink it and you'*ll see whether it works. :laughing: )

**Comment by Binnette** [comment]
So let's implement it with a "choose one" quest.

| Choose one :        | drinking_water | drinking_water:legal |
|---------------------|----------------|----------------------|
| Drinkable (no sign) | yes            | (do not set)         |
| Sign drinkable      | yes            | yes                  |
| Not drinkable (no sign)      | no             | (do not set)         |
| Sing not drinkable  | no             | no                   |
| Other answer...     |                |                      |
| Seems drinkable     | conditional    | (do not set)         |

**Comment by rugk** [comment]
The sign thing is clear, but what if there is no sign. Do you think it is easy to decide whether water is drinkable?

**Comment by Binnette** [comment]
Yes it is.

In city, there is no sign but water is drinkable: https://goo.gl/K2hp3W
In mountain, this water "seems drinkable": https://goo.gl/EJtyZw
And this seems not : https://goo.gl/PKuP4U

**Comment by rugk** [comment]
To get your answer possibilities into a new UI:

> **Is the water of this <type> drinkable?**
> [Drinkable sign] | [Drinkable] | [Not drinkable] | [Not drinkable sign]

4 is the maximum when only using text, but it could still be difficult to get it into that width.
We could use images/signs however, e.g. [this for not drinkable](https://openclipart.org/detail/10972/prohibition2).

**Comment by stefanb** [comment]
It often happens in or near restaurants, bars,  mountain huts...  that they declare the water as non-drinkable,  fueled by motivation of:
* increasing their sales of bottled beverages 
* limiting their legal liability
* saving their limited supply (eg rain water)

How to cover such situations?

**Comment by rugk** [comment]
drinking_water:legal = no; not set `drinking_water` (or set to `yes` if you are sure it actually is drinkable, but that may not be a good idea to offer to the user).

**Comment by kmpoppe** [comment]
Just to leave my two cents to what @stefanb said: OpenStreetMap's aim is to model the reality (to a degree) - so if there's a sign saying "No Drinking Water", this is the reality the fountain lives in and that's what needs to go into OSM. If there are more sinister reasons behind this (those you mentioned), these are just not to be seen with the naked eye ("from outside") and thus cannot be determined. Where inspecting the fountain of the presence of a sign is the easiest task you can ask the SC user for.

This quest could be easily implemented with the radio button list as there are many of those nowadays.

**Comment by stefanb** [comment]
@kmpoppe, what if OSM surveyor determines contrary to what is written. Either with an elaborate  water testing equipment or just applying local knowledge?

**Comment by stefanb** [comment]
But I agree this is more of a general tagging problem, not specific to a specific tagging tool, StreetComplete in this case.

**Comment by FloEdelmann** [comment]
> what if OSM surveyor determines contrary to what is written?

@stefanb There could be a "Sign is wrong" item in the "other answers" menu which lets users create a note instead. Then `drinking_water=yes, drinking_water:legal=no` (or vice-versa) could be applied manually afterwards.
