### ISSUE TITLE
Show location of entrances when adding/editing shops

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5497]
**Use case**
When editing shops and adding new ones in the right location, I think it is important to show the location of entrances. Often shops are located on the ground floor of apartment buildings that also have staircase entrances on that floor. To correctly add a new shop, it should be placed correctly relative to other shops (left/right of an existing one) but also correctly relative to entrances (left/right of one).

**Proposed Solution**
Show location of entrances in the shop overlay like they are already shown in the address overlay. I hope this is not too difficult and existing code can be copy-pasted. It would also be nice to have the entrances shown when answering a shop-related quest (name, hours, ...) like nearby shops are already shown, and like nearby entrances are shown in the entrance reference quest.

**Comment by FloEdelmann** [comment]
Currently, things that are highlighted in an overlay are also editable, and this should not be possible for entrances in the shop overlay. Adding another set of highlighted elements that are just shown "for reference" break with that convention.

**Comment by rhhsm** [comment]
> Currently, things that are highlighted in an overlay are also editable, and this should not be possible for entrances in the shop overlay. Adding another set of highlighted elements that are just shown "for reference" break with that convention.

I think that's a small price to pay for improved mapping accuracy. Strictly speaking, shops for shop-related quests and entrances shown at the entrance reference quest are not always editable (only when there's a quest for them). You'd have to switch to a suitable overlay if you want to edit them.

**Comment by westnordost** [comment]
You expect to be able to map shops more precisely if the entrances are shown. Hm well, I never have had the impression that it would increase precision. After all, you can also see the building outlines, plus of course your own position.
Maybe for really long buildings...

Anyway, keep in mind that shop entrances may also be mapped and are not visually distinguished from "apartment/staircase entrances".

Maybe entrances could be shown as small dots instead of full icons, like in the address overlay.

**Comment by matkoniecz** [comment]
> After all, you can also see the building outlines, plus of course your own position.
Maybe for really long buildings...

https://www.openstreetmap.org/#map=19/50.07879/19.92230

![screen01](https://github.com/streetcomplete/StreetComplete/assets/899988/5b5be0af-1fbf-4d1e-a4ea-5cc17058225e)

**Comment by westnordost** [comment]
Entrances with addresses are already shown, because addresses are shown.

**Comment by rhhsm** [comment]
> You expect to be able to map shops more precisely if the entrances are shown. Hm well, I never have had the impression that it would increase precision. After all, you can also see the building outlines, plus of course your own position. Maybe for really long buildings...

The building that @matkoniecz showed above has entrance references and paths leading to the entrances mapped, so that helps to guess where they are. But for this building (screenshot below) it's hard to guess where they are, while I think it's important to be able to check that the order of shops and entrances is correct (i.e. from top to bottom it might be shop - shop - entrance - shop - entrance -etc.). Staircase entrances are nice "anchors" because they usually occur at regular distances: if an apartment building has 3 staircase entrances, they are very likely to occur at 1/6, 1/2 and 5/6 of the length of the building.

![Screenshot (24 feb)](https://github.com/streetcomplete/StreetComplete/assets/69100427/42fb537e-26d7-46c9-a1ef-05b532c0819c)

> Anyway, keep in mind that shop entrances may also be mapped and are not visually distinguished from "apartment/staircase entrances".

It would work for me because very few shop entrances are mapped here, but it might be less helpful or even confusing for others.

> Maybe entrances could be shown as small dots instead of full icons, like in the address overlay.

Yes, that's what I had in mind. And if they have to be editable, I wouldn't mind. Would be nice if in a suitable overlay (probably not the shop overlay) an entrance could be selected so that its type could be changed (for instance change `entrance=yes` to `entrance=staircase`, so that in the next step a staircase ref can be added with the entrance reference quest). But that's another issue...
