### ISSUE TITLE
Enable 'Is cash payment accepted here?' quest in Finland

### ISSUE THREAD

**Issue by draeklae** [streetcomplete/StreetComplete#5500]
**Use case**
Like in many places since the pandemic, it is increasingly common in Finland for stores to not accept cash. The usual suspects are coffee shops, but some restaurants, medical clinics, etc. also do so. I think the only place you can be 100% sure of being able to pay with cash are grocery stores.

The cash payment quest is already enabled in Sweden, so the situation should be similar. I tried to find some concrete data about cash acceptance, but all I could find was, e.g., [how many transactions are done with cash](https://www.statista.com/statistics/1094945/cash-use-in-finland/), which is only about 10%. (See also [here](https://www.suomenpankki.fi/en/Statistics/payments-statistics/cash-statistics/kuluttajakysely/) for other official statistics.)

**Proposed Solution**
Add Finland to the list of countries where the quest is enabled.

**Comment by westnordost** [comment]
Do you live in Finland and this is your experience?

**Comment by draeklae** [comment]
Yes, I've been living in Finland for >1 year now. Coming from Germany it's something that doesn't take long to notice...
