### ISSUE TITLE
Disused amenity should not be quested for openign hours

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5502]
I was asked for opening hours of this doctor https://www.openstreetmap.org/node/2642121572/history (version 7) (and added the hours of the shop next door by mistake, because I had just been asked for its name). This node is tagged with `disused:amenity=yes`. Another mapper sent me a question about it by PM, so I reverted my edit (version 8) and checked that SC is again asking for its opening hours. I suspected that SC might miss that it is disused because the kind of amenity is not mentioned, so I changed it to `disused:amenity=doctors` but SC is still questing its hours.

**Expected Behavior**
SC should not ask for opening hours of any disused amenity (or in fact any POI that has a lifecycle prefix)

**Versions affected**
Android 10, StreetComplete v56.1

**Comment by Cj-Malone** [comment]
I suspect this is because of `healthcare=doctor`

**Comment by matkoniecz** [comment]
It was tagged as being in operation, see `healthcare=doctor`

**Comment by rhhsm** [comment]
Hmmm... so we have 2 tags (`amenity=doctors` and `healthcare=doctor`) that mean exactly the same and can be used together, and to indicate that it's disused, you'd have to add the `disused:` prefix to both... what a strange world OSM is, sometimes ;)

> You can have active POI with validly tagged lifecycle prefix of something else.

My imagination fails me...

**Comment by matkoniecz** [comment]
> Hmmm... so we have 2 tags (amenity=doctors and healthcare=doctor) that mean exactly the same and can be used together, and to indicate that it's disused, you'd have to add the disused: prefix to both... what a strange world OSM is, sometimes ;)

Yes, exactly :)

> My imagination fails me...

museum or gift shop in a former military bunker, museum in a preserved pharmacy ( https://muzeumkrakowa.pl/en/branches/eagle-pharmacy ), museum/library/warehouse in a former church...

And not sure how it is tagged but this a bit famous burger king probably also qualifies (note visible trace of removed nazi insignia on the left side)

![screen](https://github.com/streetcomplete/StreetComplete/assets/899988/20d34e39-d70d-48f1-86ce-9452eee61412)

**Comment by Cj-Malone** [comment]
I think they are examples of historic things, not disused things, they are after all, in use.

**Comment by rhhsm** [comment]
The first and third are examples where it's the building that's disused, but the second one is a good one, where one use that is still relevant has been replaced by another related use. I looked up that the combination of `disused:amenity=*` with `amenity=*` occurs more than 5000 times, so one amenity being replaced by another while the original one is still tagged is not as rare as I thought. Thanks for considering it!

**Comment by matkoniecz** [comment]
> I think they are examples of historic things, not disused things, they are after all, in use.

especially churches converted to museums could be converted to active use basically immediately - and while I would not put `disused:amenity=place_of_worship` it is not exactly incorrect.
