### ISSUE TITLE
Building Overlay : Put the most recent building on the right side.

### ISSUE THREAD

**Issue by waterced** [streetcomplete/StreetComplete#5534]
**Use case**
When using the Building Overlay in a residential suburbs area, one face repeatedly and successively clicking the same building and the validating button. To perform this quickly, one use the thumbs of the both hands, as the most recently used building and validate buttons are located on opposite sides of the screen.
![IMG_20240312_212209](https://github.com/streetcomplete/StreetComplete/assets/88687679/24fabc17-6cf5-4cd5-928c-3909b4280a12)

**Proposed Solution**
- Instead of placing recently used buildings type from left to right, locate them from right to left, allowing quick clicking with a single hand.

**Comment by mnalis** [comment]
> locate them from right to left, allowing quick clicking with a single hand.

Note that this kind-of assumes one is right handed... (i.e. it would make situation even worse for left handed people, while making it better for right-handed people). It would work for me personally, though :smiley: 

See e.g. https://github.com/streetcomplete/StreetComplete/issues/4464#issuecomment-1268184975 and below for related discussion about the issue.

Ideally IMHO, we should have a **preference about left/right-handedness** and customize UI forms for that. 
But that'd likely be non-insignificant amount of work.

**Comment by westnordost** [comment]
This would be inconsistent to other forms where such quick select buttons are used. IIRC the building type form has similar buttons, but e.g. for the cycleway overlay, there is also a quick select button and that button is always on the left side.

It is actually deliberate that this button is on the left side, i.e. far away from the "OK" button. It should eliminate the chance that the edit is done+uploaded accidentally - when the user's tap is registered by the touch screen as two taps.
