### ISSUE TITLE
Version 57.0 on Android 13 fails to start

### ISSUE THREAD

**Issue by michaelopdenacker** [streetcomplete/StreetComplete#5536]
Since I upgraded to version 57.0 on Android (actually /e/OS 1.20 - Android 13 on FairPhone5), the app doesn't start anymore.

How could I get more information to share for debugging?

**Versions affected**
Android 13, StreetComplete 57.0

**Comment by riQQ** [comment]
Most likely #5522

**Comment by michaelopdenacker** [comment]
I found a workaround that worked for me: uninstall the application and install it again.

**Comment by michaelopdenacker** [comment]
Ah, right, I did log in again but I forgot about my setting changes.
Thanks for the reminder!
