### ISSUE TITLE
New Quest: Moped one-way and cycleway information

### ISSUE THREAD

**Issue by PowerPlop** [streetcomplete/StreetComplete#5540]
### General
I'm suggesting to add some quests to improve navigating with a Moped. In Belgium a lot of roads and cycleways have additional rules regarding Moped-use which makes routing quite difficult.
Those exclusions are marked with a sign like this:

![image](https://github.com/streetcomplete/StreetComplete/assets/2457335/1f9d8942-7885-4d03-9e35-4759d53ab5a0)

**Existing tags**
Moped use: https://wiki.openstreetmap.org/wiki/Key:moped

Oneway: https://wiki.openstreetmap.org/wiki/Tag:oneway:moped%3Dno
-> Is this road oneway for a Moped?

Cycleway usage: https://wiki.openstreetmap.org/wiki/Road_signs_in_Belgium/M_Extra_signs
-> Is a Moped allowed on this highway/cycleway ?

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
-> Would improve navigation by Moped
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
-> Every cycleway can be tagged

### Ideas for implementation

**Element selection:** 

Oneway: The oneway quest can be extended or re-used to include a Moped option.
Cycleway: The existing cycleway form can be extended with an exclusion/allowed checkbox

![image](https://github.com/streetcomplete/StreetComplete/assets/2457335/168b9d92-c9ee-45cd-a88a-e0beea2a99cf)

If this suggestion is approved, I'll see if I can make an implementation (no Kotlin experience).

**Comment by westnordost** [comment]
I fear this would be too Belgium-specific. In particular, the quest and overlay should be rather about the physical presence of cycleways.

If a substantial amount (-> see "spam" in quest guidelines) of cycleways in Belgium has "moped allowed/disallowed" signs, then this could be a separate quest.

I recently was in Antwerpen for the State of the Map conference and did not see any such signs, but I may just not have noticed them.
So, if you want to propose a Belgium specific quest that asks about that, please create a new ticket for that but please research but forehand how prevalent this signage really is.

**Comment by westnordost** [comment]
Yes, please open a new quest suggestion

**Comment by mnalis** [comment]
> This data is available in https://www.geopunt.be/ . I'm currently looking at the WFS API specification to see if this can be exported.

As I side note @PowerPlop, if that data (of good accuracy) already exists in some dataset such as the one you linked, and if it is licensed as open data allowing it to be used in OSM, perhaps one might consider doing an [Import](https://wiki.openstreetmap.org/wiki/Import/Guidelines) instead (or in addition) of a country-restricted StreetComplete Quest.

 Because if it possible, that would certainly save a lot of mapper time.

**Comment by PowerPlop** [comment]
> I recently was in Antwerpen for the State of the Map conference and did not see any such signs, but I may just not have noticed them. So, if you want to propose a Belgium specific quest that asks about that, please create a new ticket for that but please research but forehand how prevalent this signage really is.

Just to confirm that the signs indeed exist in antwerp ;) 

![image](https://github.com/streetcomplete/StreetComplete/assets/2457335/1bf6c6a6-6faf-4142-95d1-0a92d02c5c63)





> As I side note @PowerPlop, if that data (of good accuracy) already exists in some dataset such as the one you linked, and if it is licensed as open data allowing it to be used in OSM, perhaps one might consider doing an [Import](https://wiki.openstreetmap.org/wiki/Import/Guidelines) instead (or in addition) of a country-restricted StreetComplete Quest.
> 
> Because if it possible, that would certainly save a lot of mapper time.

I did some digging and found some datasets with sign information that is publicly available. I even contacted the relevant government instance and delivered me a GDB dataset that could be downloaded.
I'll have a look at the import guidelines and see if i can map the sign information to Moped Access!
