### ISSUE TITLE
[Feature request] Display `fixme` tags.

### ISSUE THREAD

**Issue by dreirund** [streetcomplete/StreetComplete#5541]
**Use case**  
In OpenStreetMap there are notes as separate features, and `fixme` tags on nodes and ways within the OSM data.

StreetComplete shows only notes, but not `fixme` tags, although they are both used for similar kind of information (I recently encountered [`fixme=check street name`](https://www.openstreetmap.org/node/5073780897)).

**Proposed Solution**  
Add a config option to also display `fixme` tags and let the user edit the feature that exhibit that tag.

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion.
This was discussed (and rejected) in
#3084
