### ISSUE TITLE
sc hides other queries after answering lighting query

### ISSUE THREAD

**Issue by uegert** [streetcomplete/StreetComplete#5544]
Streetcomplete om my Samsung s10e often  'hides' additional query such as 'surface' after a query on lighting for path has been answered. There is no problem if I answer the surface first. Reverting the lighting, changing zoom level, restarting streetcomplete or clearing the cache do not help.

**How to Reproduce**
In SC, Find a path that has a lit=unknown and a query for surface. Switch lit=yes. Surface query disappears. It does not happen in all cases but frequently.

**Expected Behavior**
 surface query should persist

**Versions affected**
android 12, sc 57.1 and some versions before

**Comment by matkoniecz** [comment]
which quest is "lighting query"? (there is list of quests at https://wiki.openstreetmap.org/wiki/StreetComplete/Quests - no idea which ones is "lighting query")

**Comment by Helium314** [comment]
Maybe the issue template should be adjusted? @uegert put the text inside the `<!-- commented part -->`, and I can see that it's not obvious that this text will not be shown.

I edited the issue, just removed `<!--` and `-->`

**Comment by Helium314** [comment]
On the main topic: It's most likely that the surface quest is a resurvey. There are several issues about this already, but if I remember correctly this is a wontfix (quite tricky when you consider existence quests, and probably a lot of work).

**Comment by matkoniecz** [comment]
the same as #4746 #4520 - so closing (it is not obvious that it is the same issue, so do not worry too much about this)

mildly related to #4914
