### ISSUE TITLE
Don't ask if a bus stop has a shelter when it's underground?

### ISSUE THREAD

**Issue by RayBB** [streetcomplete/StreetComplete#5550]
**Use case**

Seems a bit odd to ask if a bus stop / station has a shelter when they are under ground.

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/streetcomplete/StreetComplete/assets/921217/3113d147-6280-4ca9-a2cb-265174d1b093)
  
</details> 

Location:
https://www.openstreetmap.org/#map=19/40.38446/-3.71817

**Proposed Solution**

Perhaps if the bus station is underground this question shouldn't be asked?

**Comment by Helium314** [comment]
How is the underground on the bus stops tagged? From the link it's not clear which stop you're referring to.
And why not just answer that the whole stop is covered?

**Comment by RayBB** [comment]
Maybe the best thing is to just answer that the whole stop is covered. I was posting here because it seemed like a weird question to ask for something that is underground. I'm simply posting here with hopes of improving the app or at least clarifying for myself. I don't have a strong opinion about if the quest should be asked.

The bus stops for example (https://www.openstreetmap.org/node/8712239294) are nodes that are part of a way that has `layer=-2`.

**Comment by Helium314** [comment]
From the [layer wiki](https://wiki.openstreetmap.org/wiki/Key:layer): Negative values do not imply that object is underground, use [location](https://wiki.openstreetmap.org/wiki/Key:location)=[underground](https://wiki.openstreetmap.org/wiki/Tag:location%3Dunderground) for this purpose.

Bus stops with negative levels or `location=underground` or `location=indoor` or `indoor=yes` are already excluded from the quest.

**Comment by Helium314** [comment]
So in my understanding the issue is incomplete tagging of the bus stops.

**Comment by westnordost** [comment]
Right, that's correct. You should tag `location=underground` on that bus stop.

**Comment by mnalis** [comment]
> You should tag location=underground on that bus stop.

Perhaps it would make sense to add it as `Other answers` (e.g. _"This stop is underground"_ => `location=underground`) ?

**Comment by matkoniecz** [comment]
This may be in area of "rare, just make a note or edit with Vespucci"

**Comment by mnalis** [comment]
> This may be in area of "rare, just make a note or edit with Vespucci"

Probably for bus stops, but I think [that quest](https://github.com/streetcomplete/StreetComplete/blob/38203c669a5448414f9965b95dcd8d6defee2e35/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.kt#L16-L27) is also asked on [public_transport=platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport=platform) where it might be more common? 

But I don't have much experience there (taginfo says some [2.4k](https://taginfo.openstreetmap.org/tags/public_transport%3Dplatform#combinations) of public transport platforms are already also tagged with `location=underground`)...
