### ISSUE TITLE
Missing Bench

### ISSUE THREAD

**Issue by RJGhugo** [streetcomplete/StreetComplete#5553]
This bench is already in OpenStreetMap, but not showing in StreetComplete (v57.1/FDroid):

https://www.openstreetmap.org/search?whereami=1&query=47.11197%2C8.50578#map=19/47.11197/8.50578

**Comment by RJGhugo** [comment]
Same problem:

https://www.openstreetmap.org/search?whereami=1&query=47.11947%2C8.50146#map=19/47.11947/8.50146

**Comment by RJGhugo** [comment]
Same problem:

https://www.openstreetmap.org/search?whereami=1&query=47.12691%2C8.50161#map=19/47.12691/8.50161

**Comment by HolgerJeromin** [comment]
> but not showing in StreetComplete (v57.1/FDroid):

Why or how should it be shown?

**Comment by RJGhugo** [comment]
I can see them on organic maps or open street map.

I can not see them in street complete.

So I asume, there are missing on the map.

**Comment by matkoniecz** [comment]
Have you enabled Things layer?

**Comment by RJGhugo** [comment]
Thanks, that was it!

"Kein/Nothing" Layer active!

I misinterpreted the Layer-Menu. Assuming that every thing is on by default and you deselect what you do not want...
