### ISSUE TITLE
UX: Adding religious (Christian) crossings is confusing while language is set to German (things overlay)

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#5557]
**How to Reproduce**

Let's say you stand before a Christian cross and want to add this with the things overlay…

1. Open things overlay.
2. Add thing.
3. Search for "cross" ("kreuz" in German).

What happens:
![Screenshot_20240323-140904_1](https://github.com/streetcomplete/StreetComplete/assets/11966684/332dd77b-0d81-466c-ba7f-fff0f0509d94)

The only result is the weirdly confusingly term "Kreuz ohne religiösen Wert" ("Cross without religious value"), which is… uhm… clearly wrong, in this case? (most free-standing crosses except on mountains maybe, in Germany likely have a religious value aka are Christian crosses).

As it is often found near a way, if you are clever, you search for "Weg" (way/road) and you get "Wegkreuz" ("way/road cross"?):
![Screenshot_20240327-181040_1](https://github.com/streetcomplete/StreetComplete/assets/11966684/0c48c296-ba8d-4297-b324-338a45fb470f)

Now, is this the correct one? I am personally puzzled…

**Expected Behavior**

Several things:
* why does not "Wegkreuz" appear when I search for "kreuz" – it should really do so?
* Maybe it can be clarified how to map/what religious crosses, given the other entry explicitly states "without religious value"

Personally, I just think (and did) map a Christian cross as a "Wegkreuz", and given https://de.wikipedia.org/wiki/Flurkreuz (which calls it "Flurkreuz" – a term, which allows you to find the Wegkreuz), I guess this is correct.

Also, I'd propose:
* maybe also make it findable when searching for "Christ"/"Jesus"/"Christian" or similar…

**Versions affected**

57.1

**Comment by matkoniecz** [comment]
> maybe also make it findable when searching for "Christ"/"Jesus"/"Christian" or similar…

Is it findable in iD editor when searching with such terms? If no and it should be then such aliases can be added by translators. See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#id-presets

**Comment by matkoniecz** [comment]
Apparently you need to opt in to translate German to see it. Is it confirmed that broken translation of iD presets is the source?

**Comment by riQQ** [comment]
Not finding 'Wegkreuz' when searching for 'kreuz' is a bug no matter what.

**Comment by westnordost** [comment]
Isn't the issue rather that the search dialog does not find "Wegkreuz" wenn searching for presets? (Does iD find it when entering Kreuz?)

**Comment by westnordost** [comment]
Looking at the osmfeatures library code, indeed the library does not do a full-text-search but a "starts with" search. I.e. the word has to start with the text typed.

However, if the preset for the wayside cross contains an alias "Kreuz" or even just a term with that name or that starts with that name, then it is probably a bug in osmfeatures library.
All assuming that in iD, it works fine as-is.

**Comment by rugk** [comment]
Okay, so what is actionable here?

* osmfeatures: make and issue or PR to change the search from "starts with" to "contains"?
* OSM wiki (etc.): clarify whether "Cross without religious value" is really not-religious? And if it is _not_, what do we have "Wegkreuz"/wayside cross/"Flurkreuz" for, then?
* ID (presets): adding "Christ"/"Jesus"/"Christian" as aliases

Do I miss sth.?

**Comment by westnordost** [comment]
First check how iD behaves. Does the issue exist for iD, too?

**Comment by westnordost** [comment]
The german translation of the preset is currently
```
                "historic/wayside_cross": {
                    "name": "Wegkreuz",
                    "terms": "wegkreuz,wegekreuz,flurkreuz"
                },
```

So, in the transifex, just "kreuz" should be added to the terms. I think that should solve the issue. The "Wegekreuz" preset will then be findable via the term.

**Comment by rugk** [comment]
Yeah seems ID "works" the same in German:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/11966684/fb163e98-e266-4733-90a6-3730e4d81a20)


![grafik](https://github.com/streetcomplete/StreetComplete/assets/11966684/03e2b53a-ddd7-445d-9bd3-226fd3a4a7e7)

**Comment by westnordost** [comment]
can't hurt to add christian etc as terms too, also for the English strings.

With that said, I will close this and trust that someone will update the German terms of the "Wegkreuz" preset :-)

**Comment by rugk** [comment]
Well… I would like to fix it for all languages and add "cross" there, so I am a little lost here. In https://github.com/search?q=repo%3Aopenstreetmap%2FiD%20wayside_cross&type=code I cannot find it…

Anyway, already requested to join the id translation project on transifex, which apparently needs to be approved first… :roll_eyes:

**Comment by rugk** [comment]
BTw if we speak about crosses, should not SC then also allow to add summit crosses? Ah I see the issue seems to be it is a modification actually: `[summit:cross](https://wiki.openstreetmap.org/wiki/Key:summit:cross)=[yes](https://wiki.openstreetmap.org/wiki/Tag:summit:cross%3Dyes)` at `[natural](https://wiki.openstreetmap.org/wiki/Key:natural)=[peak](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeak)`… (okay English wiki says in addition is okay too, so probably okay?)

**Comment by rugk** [comment]
> They seem to be contradictory to me. English wiki for man_made=cross also has a picture of a clearly religious wayside cross of no historic value as an example.

[Asked about this in OSM wiki now](https://wiki.openstreetmap.org/wiki/DE_talk:Tag:man_made%3Dcross#Ist_%E2%80%9EKreuz_ohne_historischen_oder_religi%C3%B6sen_Hintergrund%E2%80%9D_wirklich_richtig?)

**Comment by westnordost** [comment]
> Well… I would like to fix it for all languages and add "cross" there, so I am a little lost here. In https://github.com/search?q=repo%3Aopenstreetmap%2FiD%20wayside_cross&type=code I cannot find it…

Wrong repo. It's this one https://github.com/openstreetmap/id-tagging-schema
There is also a translate link.

**Comment by kjonosm** [comment]
> With that said, I will close this and trust that someone will update the German terms of the "Wegkreuz" preset :-)

Done

**Comment by mnalis** [comment]
> BTw if we speak about crosses, should not SC then also allow to add summit crosses? Ah I see the issue seems to be it is a modification actually: [summit:cross](https://wiki.openstreetmap.org/wiki/Key:summit:cross)=[yes](https://wiki.openstreetmap.org/wiki/Tag:summit:cross%3Dyes) at [natural](https://wiki.openstreetmap.org/wiki/Key:natural)=[peak](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeak)…

Isn't there a [quest for summit cross](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#summit)  already (if I'm understanding correctly what you want)?
