### ISSUE TITLE
Is check_date (existence) für roads and for things links place=suburb really wanted?

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [streetcomplete/StreetComplete#5564]
Hi,
is something linke this really wanted: https://www.openstreetmap.org/node/267904561/history

In https://www.openstreetmap.org/changeset/148807450 there has been added check_date onto **roads** and onto **place=suburb**.

Is this really wanted?

Thank you for your answers.

**How to Reproduce**
Use the "CheckShopExistence" Quest

**Expected Behavior**
Do not add check_date to things like roads and objects with place=* key

**Versions affected**
57.0

**Comment by Helium314** [comment]
This is SCEE, not StreetComplete.
It's not asked any more, see https://github.com/Helium314/SCEE/issues/521
But actually people who use SCEE should be able to decide for themselves whether it makes sense.
