### ISSUE TITLE
New Quest: (Belgium) Moped access to cycleway information

### ISSUE THREAD

**Issue by PowerPlop** [streetcomplete/StreetComplete#5565]
### General

This issue is a new version of https://github.com/streetcomplete/StreetComplete/issues/5540, i limit the request to a Belgium specific quest and focus on cycleway access.

I'm suggesting to add a new quest to improve navigating with a Moped. In Belgium a lot of roads and cycleways have additional rules regarding Moped-use which makes routing quite difficult.
Those exclusions are marked with a sign like this:

![image](https://github.com/streetcomplete/StreetComplete/assets/2457335/441703d7-341e-44ea-9c0b-98b9dc7c4f84)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose

Moped use: https://wiki.openstreetmap.org/wiki/Key:moped

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

This quest can be asked for every cycleway, I don't know how to limit is to a subset?

- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

![Screenshot_20240401-155458](https://github.com/streetcomplete/StreetComplete/assets/2457335/b2dd3545-af4b-41af-82c6-77bb367a616c)

https://github.com/streetcomplete/StreetComplete/pull/5567

**Comment by westnordost** [comment]
Ah, I see. Some questions / issues:

1. What if there is no sign, what should the user answer and how should it be tagged? What if there is just the fietspad-sign without any mention of mopeds? Is it allowed or forbidden, or unspecified? How is this case tagged?

2. I notice that the pictures are some ugly looks-like-gif. This should of course be replaced with a vector graphic and also without the Dutch wording. It's also a question is whether a depiction of the sign is useful at all? Could the question be misinterpreted otherwise?

3. In regards to the last message in #5540 - if an official government source is available and may be used, it would be somewhat preferable if this was done as an import. You wrote that you want to check this possibility. What came of it?

**Comment by PowerPlop** [comment]
> Ah, I see. Some questions / issues:
> 
> 1. What if there is no sign, what should the user answer and how should it be tagged? What if there is just the fietspad-sign without any mention of mopeds? Is it allowed or forbidden, or unspecified? How is this case tagged?

No sign = allowed
Fietspad sign without moped sign = allowed 

So I assume you need implicit knowledge to complete this quest.

Below picture show all possibilities (Verplichten,Toegelaten, Toelaten = Allowed, Verbieden = Forbidden)

![moped](https://github.com/streetcomplete/StreetComplete/assets/2457335/cd961a47-ce41-4612-b715-163e0f95cbe7)


> 2. I notice that the pictures are some ugly looks-like-gif. This should of course be replaced with a vector graphic and also without the Dutch wording. It's also a question is whether a depiction of the sign is useful at all? Could the question be misinterpreted otherwise?

Those pictures are the official signs in Belgium... but I don't deny they are ugly ^^. I included the signs to make it clear on how to decide on allowed or not. But I don't know if they really clarify it.
I would suggest removing them?  

> 3. In regards to the last message in [New Quest: Moped one-way and cycleway information #5540](https://github.com/streetcomplete/StreetComplete/issues/5540) - if an official government source is available and may be used, it would be somewhat preferable if this was done as an import. You wrote that you want to check this possibility. What came of it?

I opened a topic in the belgian OSM community: https://community.openstreetmap.org/t/importen-bromfiets-klasse-b-verkeersborden-informatie/110862
Apparantly the datasource was already known, but automatic mapping of the sign information to cycleways would be too difficult. Besides, the dataset could be outdated and not guaranteed to be correct.
We could use a tool like mapillary and the sign data to add them one by one, but then your app seemed like a better way to add this information?

**Comment by westnordost** [comment]
> So I assume you need implicit knowledge to complete this quest.

Not necessarily. The question just needs to be asked differently, i.e. ask about a sign. Then there are only three options: Yes, there is a sign that prohibits mopeds, yes, there is a sign that marks the cycleway as mandatory for mopeds and no, there is no sign. (Maybe difficult to find concise wording for this).
However, in the case of no sign, is it okay to tag `moped=yes`? Or `moped:signed=no`? The latter would seem to be more in line with what the user then actually answered.

> Those pictures are the official signs in Belgium... but I don't deny they are ugly ^^

I suggest to at least use the SVG version of them. On the other hand, there is not really anything unexpected on this sign, it depicts a moped and says whether it is verplicht or verboden. Also, if you use the whole sign, then what about the French-speaking part of Belgium?

> Apparantly the datasource was already known, but automatic mapping of the sign information to cycleways would be too difficult. Besides, the dataset could be outdated and not guaranteed to be correct.

Automatic, maybe. However, if the data may be used, it could be used to manually insert this information, i.e. on the left side of the screen, you have JOSM open and on the right side of the screen, you have that data source open. Anything related to signs (at the beginning / end) of roads is going to be a bit awkward with StreetComplete or on-site in general because we are basically requiring the user to walk down the whole road (or at least until the next intersection?) to be able to answer the quest correctly. Since other quests are usually solvable in just a few seconds, the unexpected extra effort to solve this quest may always lead to some users not being diligent and answering without really checking, which in turn may lead to less precise data.

**Comment by PowerPlop** [comment]
> Not necessarily. The question just needs to be asked differently, i.e. ask about a sign. Then there are only three options: »Yes, there is a sign that prohibits mopeds«, »yes, there is a sign that marks the cycleway as mandatory for mopeds« and »no, there is no sign«. (Maybe difficult to find concise wording for this). However, in the case of no sign, is it okay to tag `moped=yes`? Or `moped:signed=no`? The latter would seem to be more in line with what the user then actually answered.

I'll see if I can rewrite the quest. No sign would mean 'moped=yes' only when the visible sign is the bicycle, all other signs would imply moped=no;
Using moped:signed=no would be possible but I don't find any reference to this tag type? The goal would be to improve navigation with a moped and i'm afraid this tag isn't used by most routing apps?


> I suggest to at least use the SVG version of them. On the other hand, there is not really anything unexpected on this sign, it depicts a moped and says whether it is verplicht or verboden. Also, if you use the whole sign, then what about the French-speaking part of Belgium?

I would prefer removing them in that case. I agree they don't add anything useful.
I completely forgot about our french-speaking part, but they have a translated sign. 

![image](https://github.com/streetcomplete/StreetComplete/assets/2457335/7e362a1c-c6cb-498b-a1ca-85ea89a939df)


> Automatic, maybe. However, if the data may be used, it could be used to manually insert this information, i.e. on the left side of the screen, you have JOSM open and on the right side of the screen, you have that data source open.

Manually mapping in this way would be possible, but using the app (on the road) would be more fun. :)

> Anything related to signs (at the beginning / end) of roads is going to be a bit awkward with StreetComplete or on-site in general because we are basically requiring the user to walk down the whole road (or at least until the next intersection?) to be able to answer the quest correctly. Since other quests are usually solvable in just a few seconds, the unexpected extra effort to solve this quest may always lead to some users not being diligent and answering without really checking, which in turn may lead to less precise data.

I agree. Is this an argrument to not include it in Streetcomplete at this moment?
To be honest, I'm afraid the amount of Moped drivers, in Belgium, that use Streetcomplete would be quite minimal. I would be happy enough with my local apk build to use it as an easy tagging tool. I don't know if it's possible to login on the local version?

Let me know what you think, if you would say it has enough added value for StreetComplete I'll make an effort to rewrite the PR.

**Comment by westnordost** [comment]
> I agree. Is this an argrument to not include it in Streetcomplete at this moment?

No, just a note.
If quests turn out be both spammy and difficult to answer, we may consider disabling the quest by default. But IIRC you did some research before to confirm that signs about mopeds are neither ultra rare nor to be expected basically on every cycleway already.

Note that when you rewrite the quest, maybe it is not clear enough to limit the answer to one word, in which case the interface would probably rather be alike the `AddInternetAccessForm` quest form (i.e. with radio buttons)

**Comment by PowerPlop** [comment]
@westnordost I was wondering when this quest will be visible in the app on Google Play Store? Does it have to be included in a release first?

**Comment by westnordost** [comment]
I usually do updates not more often than monthly. There is some effort involved (plus effort for fork maintainers) and back when I released new versions almost bi-weekly, I actually got complaints that that's too often, which for the folks that use F-Droid, where updates don't happen basically invisible to users in the background, I can somewhat understand.

For the next version, I would (have liked) to actually include the huge effort that was put into migration to MapLibre (see https://github.com/Helium314/SCEE/pull/516 ), but I don't know when the issues that are release-blocking for us are solved upstream, so that's why it is probably safer to not wait for that.

**Comment by bxl-forever** [comment]
It’s a good thing the quest is turned off by default, because it can be misleading.

Many urban cycle tracks have been mapped as `highway=cycleway` next to `highway=footway`, when we have the Belgian D9 sign.
![D9](https://github.com/streetcomplete/StreetComplete/assets/23359667/5b981827-67b7-4685-92d3-ce61427d2277)

There are cases when this can be preferred over having `highway=cycleway` + `foot=yes`.

Legislation is clear about this: the D9 sign alone is enough to exclude mopeds.  Most users will not understand that the correct answer is "There is a sign that prohibits mopeds".  Instead, they will probably answer "There is no sign" (i.e. the user did not see the additional white sign forbidding mopeds), which will add `moped=yes` to the cycleway.

Same situation with the D10 sign.  Although mapping guidelines are clear, I have seen people mapping them are mere cycleways, and forgetting to add `foot=yes` to them.  The new quest will ask users to add some data, which normally should only get one single valid answer (`moped=no`).  We might end up with a lot of corrupted data.
![D10](https://github.com/streetcomplete/StreetComplete/assets/23359667/dc9b878f-71b7-45d9-9d24-d22bcf224a97)

Shouldn’t the text be written differently?  Something like "There is no sign, or the sign shows pedestrians along the cycleway".

**Comment by westnordost** [comment]
Your statement directly contradicts @PowerPlop's explanation here:

https://github.com/streetcomplete/StreetComplete/issues/5565#issuecomment-2031196204

Who is correct?

**Comment by Vakonof** [comment]
The dotted line is a bit misaligned. Mopeds are **not** allowed on D9 and D10 paths.
![2024-06-08 18_39_58-Fietsers in de - Praktische gids voor wegbeheerders](https://github.com/streetcomplete/StreetComplete/assets/11884358/46abcbb6-c96e-4be5-bf80-49e32c3cf985)
![Schermafbeelding 2024-06-08 184531](https://github.com/streetcomplete/StreetComplete/assets/11884358/354dab0f-aa7f-4662-bb3e-700e55c899fc)

**Comment by westnordost** [comment]
I see. The quest was implemented and approved based on the assumption cited above was correct. For the removal of doubt and documentation, could you cite and link from the traffic regulations / law text?

Also, can you say which bromfietsen A, B and P map to which `access` keys in OpenStreetMap? (In the image you posted, it looks like klasse A must use the path, and klasse P must use the path if the road has a speed limit of more than 50 kmh?)

**Comment by Vakonof** [comment]
Below text from the highway code states that drivers have to follow the roadway. It also lists a few situations where cyclists/mofas/moped/speed pedelecs are allowed to or have to follow cyclepaths. It doesn't state that mopeds can follow cyclepaths signed with D9/D10, thus the general rule that they have to follow the roadway applies.

[Artikel 9. Plaats van de bestuurders op de openbare weg](https://www.wegcode.be/nl/regelgeving/1975120109~hra8v386pu#flz2yoyx9u)
9.1.1. Wanneer de openbare weg een rijbaan omvat moeten de bestuurders deze rijbaan volgen.
9.1.2.
1° Wanneer de openbare weg een berijdbaar fietspad, aangeduid door wegmarkeringen zoals bepaald in artikel 74, omvat, dan moeten de fietsers en bestuurders van tweewielige bromfietsen klasse A, dit fietspad volgen voor zover het rechts in hun rijrichting ligt. Zij mogen een dergelijk fietspad niet volgen, wanneer dit links in hun rijrichting ligt.

Omvat de openbare weg een berijdbaar fietspad, aangeduid door het verkeersbord D7 of D9, dan moeten de fietsers en bestuurders van tweewielige bromfietsen klasse A, dit fietspad volgen, voor zover het in de door hen gevolgde rijrichting is gesignaleerd. Evenwel, wanneer een dergelijk fietspad links in hun rijrichting ligt, moeten zij dit niet volgen, indien bijzondere omstandigheden dit rechtvaardigen en op voorwaarde rechts in hun rijrichting te rijden.

Is een deel van de openbare weg aangeduid met het verkeersbord D10, dan moeten fietsers dit deel van de openbare weg gebruiken.

Daar waar de snelheid beperkt is tot 50 km/u of minder, hebben de bestuurders van ligfietsen en velomobielen, die een breedte hebben van maximum 1 meter, de keuze tussen het fietspad, het deel van de openbare weg aangeduid door het verkeersbord D10 of de rijbaan.

2° Daar waar de snelheid beperkt is tot 50 km per uur of minder, mogen de bestuurders van tweewielige bromfietsen klasse B en speed pedelecs in dezelfde omstandigheden het fietspad aangeduid door het verkeersbord D7 of door wegmarkeringen zoals bepaald in artikel 74 volgen, op voorwaarde dat zij de andere weggebruikers die zich hierop bevinden niet in gevaar brengen. Daarenboven mogen bestuurders van speed pedelecs in dezelfde omstandigheden het fietspad aangeduid door het verkeersbord D9 volgen.

Wanneer een hogere snelheidsbeperking geldt, moeten de bestuurders van tweewielige bromfietsen klasse B en speed pedelecs in dezelfde omstandigheden het fietspad aangeduid door het verkeersbord D7 of door wegmarkeringen zoals bepaald in artikel 74 volgen, wanneer dit aanwezig en bruikbaar is. Daarenboven moeten bestuurders van speed pedelecs in dezelfde omstandigheden het fietspad aangeduid door het verkeersbord D9 volgen.

**Comment by Vakonof** [comment]
Moped class A = `mofa`
Moped class B = `moped`
Moped class P = `speed_pedelec`

**Comment by westnordost** [comment]
I compiled the information above as a table

### Road signs mentioned above:

<table>
<tr>
<th>D7</th><th>D9</th><th>D10</th><th>Article 74</th>
</tr>
<tr>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Belgian_traffic_sign_D7.svg">
</td>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/6/6b/Belgian_traffic_sign_D9a.svg">
<img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Belgian_traffic_sign_D9b.svg">
</td>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/b/b5/Belgian_traffic_sign_D10.svg">
</td>
<td>
<img src="https://github.com/streetcomplete/StreetComplete/assets/4661658/182c3a5d-f00d-48de-8286-57e39d14e6e4"/>
</td>
</tr>
<tr>
<td>
<b>mandatory</b> for <code>bicycle</code> and <code>mofa</code>
<br><br>
<b>allowed</b> for <code>moped</code> and <code>speed_pedelec</code> if road speed limit is ≤ 50 km/h
<br><br>
<b>mandatory</b> for <code>moped</code> and <code>speed_pedelec</code> if road speed limit is > 50 km/h
</td>
<td>
<b>mandatory</b> for <code>bicycle</code> and <code>mofa</code>
<br><br>
<b>allowed</b> for <code>speed_pedelec</code> if road speed limit is ≤ 50 km/h
<br><br>
<b>mandatory</b> for <code>speed_pedelec</code> if road speed limit is > 50 km/h
</td>
<td>
<b>mandatory</b> for <code>bicycle</code>
</td>
<td>
<b>mandatory</b> for <code>bicycle</code> and <code>mofa</code>
<br><br>
<b>allowed</b> for <code>moped</code> and <code>speed_pedelec</code> if road speed limit is ≤ 50 km/h
<br><br>
<b>mandatory</b> for <code>moped</code> and <code>speed_pedelec</code> if road speed limit is > 50 km/h
</td>
</tr>
</table>

**Comment by westnordost** [comment]
So, how can this be solved?

**Comment by Vakonof** [comment]
I'm not sure what is technically possible in the app. Can the images be used to help differentiate the types of cycle paths, or should only text be used?
If images can be used, I'd propose something like the flow below.
![Screenshot_20240609_100734_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/11884358/ba6cfd59-ef43-443f-b7ac-b9e8321e9eed)

**Comment by PowerPlop** [comment]
I was aware that sign D9/D10 means no access for mopeds, but I assumed they would not be mapped as cycleways since they are 'shared' with pedestrians.
A more advanced question can of course solve this issue, but I think @westnordost  already stated that quest should be easy, quick and clear to solve.  

I was just looking for an app to quickly add moped tags on the go to improve navigation for mopeds. I understand that people without additional knowledge, might answer it incorrectly. But disabling it by default and only allowing it in Belgium, still allows moped drivers to quickly add this tag.

Feel free to remove or modify the quest, I can also fork the app for personal use. :)

**Comment by westnordost** [comment]
Unfortunately, even if deactivated, it is not acceptable to keep a quest where users can unknowingly add incorrect information. I deactivated the quest globally for now until a solution is found (and someone willing to implement it).

Thank you for the suggestion @Vakonof . This seems to be the most comprehensive and (for data users useful) approach, however is not compatible with StreetComplete's quest guideline of _atomic_ quests that are easy and quick to answer with a single question/answer.

I think the best solution to this would be to use `moped:signed=no` when the user answers "there is no sign". This is almost trivial to implement.

The downside of this, is that the information is still missing whether mopeds are really allowed on bike paths as long as it is not recorded whether the sign D7 or D9 (or nothing?) is preset. But for that, there could just be another quest exclusive to Belgium.

**Comment by bxl-forever** [comment]
Wise decision, thanks.

**Comment by mnalis** [comment]
> I deactivated the quest globally for now until a solution is found (and someone willing to implement it).

That would be ideal obviously if some non-confusion solution can be found.

> I was just looking for an app to quickly add moped tags on the go to improve navigation for mopeds
> Feel free to remove or modify the quest, I can also fork the app for personal use.

As an alternative to personal fork @PowerPlop, you might be interested to know that [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork) allows to add `moped` (and other access tags) in any highway-related overlay/quest, e.g.

![small_Screenshot_20240610_221221_SCEE](https://github.com/streetcomplete/StreetComplete/assets/156656/08a8a090-dd31-4c8f-ac4e-ba902dbbf9ed) ![small_Screenshot_20240610_221252_SCEE](https://github.com/streetcomplete/StreetComplete/assets/156656/34f8481f-f82e-4292-ae66-a33053dfdbbb)


(Additionally, in SCEE you can even create custom overlay to only highlight those cycleways which need adding those `moped` tags)

**Comment by davidpnewton** [comment]
As a first step to getting this tagging possible in Streetcomplete I'd suggest putting the is the speed limit 50 kph or lower or higher than 50 kph bit of things in.

That's data which can help inform routing even if not be completely definitive and is necessary for the other bits of the tagging to be implemented. It's also trivial to answer and code and tag in Streetcomplete. Only three answers: 50 kph or lower; higher than 50 kph or don't know.

The biggest thing for that would be sorting out exactly what tag to use for indicating the speed limit category of the adjoining road?
