### ISSUE TITLE
Question for street width is asked endless again and again

### ISSUE THREAD

**Issue by ratti** [streetcomplete/StreetComplete#5569]
**How to Reproduce**
See node https://www.openstreetmap.org/way/1228191464 , roughly located in Hamburg, Bernadottestraße 242a
1. Go to that place in SC, answer question on road width (see screenshot) with "3"
2. Get asked about street width _again_ (Countercheck in JOSM: maxwidth: is already given as "3")
3. Enter "3"
...and again and again.

**Expected Behavior**
- not getting asked at all, since "3" is already given
- If I get this wrong and the attribut is not "maxwidth", but something else: Ask once, store it, don't ask again.

**Versions affected**
57.1 from Github
![Screenshot_20240401-212656](https://github.com/streetcomplete/StreetComplete/assets/2254123/a33efa7b-c25a-43bc-a6d5-39c789bc06b2)

**Comment by westnordost** [comment]
Yes, very likely the same as #5545. I believe progress on tracking down the source can only be made after the next update, since I added some logging.

**Comment by ratti** [comment]
I found some time to play around with this and now I believe this is not related to #5545 , but a “simple“ issue with attribute dependencies.

I found it suspicious I could tag the whole street, but not the 2 parts that are a “schikane“ (narrow road for speed reduction). Comparing a working part with a not working part I noticed a difference:
- Road parts having “maxwidth“  are asking repeatedly for maximum width
- Road parts having “width“ are fine

So I changed that not working parts in JOSM and checked what would happen in SC.

Road: https://www.openstreetmap.org/way/1228191464

Initially attributes:
```
cycleway:left:surface=compacted
cycleway:right:surface=compacted
cycleway=track
highway=residential
lanes=1
lit=yes
maxspeed=30
maxwidth=3
name=Bernadottestraße
sidewalk:left:surface=paving_stones
sidewalk:right:surface=compacted
sidewalk=both
surface=sett
traffic_calming=choker
traffic_sign=DE:274.1[30]
zone:maxspeed=DE:30
```

Streetview permanently asks: “Wie breit ist die Fahrbahn hier?“ (How wide is the road here?) , to which I reply “3“
—> symbol does not disappear, question is re-asked.

Using JOSM to change “maxwidth=3“ to “width=3“
Upload from JOSM
Refresh in SC

Two new different question appear in SC (Surface type and one-way-road, but those shouldn't matter here) ⟶ problem is gone. Never get asked again.

Then, adding maxwidth=3 again per JOSM and upload: Question does not reappear in SC, issue remains solved

Wild guess: Having maxwidth without width is at least triggering the issue.

Since I now repaired that node: The same issue is here: https://www.openstreetmap.org/way/1228191460 , and I will not touch it.

**Comment by mnalis** [comment]
I can confirm that this specific example ([w1228191464](https://www.openstreetmap.org/way/1228191464)) is 100% reproducible here in SC `v57.1`; thus reopening.

Possibly related to [ROAD_NARROWERS](https://github.com/streetcomplete/StreetComplete/blob/da815f885fa4b4c115d1cd656caa60d540aaa5ca/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddRoadWidth.kt#L91C13-L91C27) logic?

**Comment by mnalis** [comment]
Thanks for both original report, and for taking extra time for digging into it more @ratti ! 

I've provided PR which should fix it for next release. (there is linked debug `.apk` there if you'd like to check how it works now before it's released)
