### ISSUE TITLE
Prettymapp using the description of Open Camping Map

### ISSUE THREAD

**Issue by Boing7678** [streetcomplete/StreetComplete#5570]
**In the projects page, Prettymapp has the same description as Open Camping Map**

# How to Reproduce

1. Open StreetComplete
2. Unlock prettymapp 
3. Tap on the hamburger menu on the top right
4. Tap on my profile 
5. Tap on the icon on the top right
6. Scroll down to Prettymapp 
# Expected Behavior

The description is "Create pretty multi-colored map posters of neighbourhoods", which is the description found in the files

# Detailed description 
```
Link(
        "prettymapp",
        "https://prettymapp.streamlit.app/",
        "Prettymapp",
        LinkCategory.GOODIES,
        R.drawable.ic_link_prettymapp,
        R.string.link_opencampingmap_description
    )
```
found in 
StreetComplete/app/src/main/java/de/westnordost/streetcomplete/data/user/achievements/AchievementsModule.kt
at line 486-493

Line 492 should be changed to
```R.string.link_prettymapp_description```
# Versions affected

StreetComplete 57.1 with Android 13
![Screenshot_2024-04-02-10-47-39-702_de westnordost streetcomplete-edit](https://github.com/streetcomplete/StreetComplete/assets/157311680/583f4719-6994-4cb9-9a50-fc0497590952)

**Comment by FloEdelmann** [comment]
Good catch! Would you like to open a PR to fix it yourself? Otherwise we can do it of course.

**Comment by Boing7678** [comment]
I don't have a computer with me, so I'd appreciate it if someone else fixed it, thanks!
