### ISSUE TITLE
Advertising totem can be added in things overlay but is not displayed

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5588]
Likely affects other things without dedicated icon

( I plan to look into this, I will assign myself once actual work will start - but feel free to take over this)

**Comment by westnordost** [comment]
Hints: Check if the icon is actually present. If it is not present, check what the download and convert preset icons task logged, maybe the icon is either missing or uses some svg features that the convert-task does not support. In general, maybe there should be a fallback icon (a dot) for such cases in general.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/overlays/things

**Comment by westnordost** [comment]
I cannot reproduce this with current master. Somehow, something was fixed, apparently.

**Comment by matkoniecz** [comment]
Or maybe my phone has again bizarre bugs that are Xiaomi's fault.

**Comment by westnordost** [comment]
Unlikely. The totem is special in that it has no icon in iD presets. Usually all presets have *some* icon.

**Comment by mnalis** [comment]
> Or maybe my phone has again bizarre bugs that are Xiaomi's fault.

Nah, it happens on my Samsung in 57.4 too... I'll recheck when F-droid picks up 58.0

**Comment by mnalis** [comment]
Tested in SC 58.0, and _advertising totem_ now seems to display normally in Things overlay...
