### ISSUE TITLE
Wording of the "Do you have to wait for a traffic signal to cross here?" quest is ambiguous

### ISSUE THREAD

**Issue by itspaulkelly** [streetcomplete/StreetComplete#5591]
The "Do you have to wait for a traffic signal to cross here?" quest confused me initially as I read it to mean that it is already known that pedestrian crossing signals exist here, but that information is needed about whether they have to be obeyed.

In the UK this is a "should" rule rather than a "must": rule 21 of [The Highway Code](https://www.gov.uk/guidance/the-highway-code/rules-for-pedestrians-1-to-35) says "You should only start to cross the road when the green figure shows".

Given that the response to this quest is setting whether crossing:signals=yes/no, wording such as "Are there traffic signals to show when to cross the road here" would be clearer.

**Comment by westnordost** [comment]
The reason why we do not ask directly for the presence of pedestrian traffic signals, as would be intuitive, is, that the (special?) situation in the US has been brought to my attention by @1ec5 : Oftentimes, there are no traffic signals _dedicated for pedestrians_ at intersections, but instead, according to the traffic regulations, pedestrians are expected to follow the (car) traffic signals. So, with the intuitive wording, users may answer "no" [, there are no pedestrian traffic signals] in these situation when actually `crossing:signals=yes` should be tagged for that crossing.

So, I understand, in the UK legislation, the traffic signal is optional for pedestrians.

For removing the "must" from the question while keeping in mind that for `crossing:signals=yes` to be set, there don't necessarily need to be dedicated pedestrian traffic signals, I think your wording suggestion is good.

Maybe _"Are there traffic signals that show when to cross here?"_ (a bit shorter)

**Comment by 1ec5** [comment]
> the (special?) situation in the US

In the U.S., it’s simply one of two allowed configurations, especially common in smaller towns with fewer pedestrians, or at intersections built by state highway departments that don’t have as much experience building urban pedestrian infrastructure. On the other hand, the examples we’ve found in other countries so far (Mexico, South Africa, Iran) have tended to be in urban centers.

> Maybe "Are there traffic signals that show when to cross here?" (a bit shorter)

This could work, as long as the user doesn’t mistakenly think it refers to a warning beacon that alerts motorists on the road to a crossing pedestrian. In many countries, these beacons are technically visible to pedestrians but aren’t intended for them, perhaps unlike the Belisha beacons in the UK. In the past, some mappers have wondered whether these are also traffic signals, but the consensus on the tagging list and wiki is that they aren’t.
