### ISSUE TITLE
deprecated shop values where fixing them requires resurvey as value is unclear - maybe treat them like shop=yes?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5594]
**Use case**
For example `shop=boutique` is highly confusing for many mappers as this is false friend in French with distinct meaning to English one.

Many, but not all would be well expressed by `shop=clothes` Some of them are completely different shops, again, especially in French speaking regions.

As result you cannot guess or fix tagging without resurvey or otherwise checking them.

**Proposed Solution**

in `shop=yes` quest start asking also in the same way about `shop=boutique` shops

See https://community.openstreetmap.org/t/shop-boutique-deprecation-proposal/104412 and https://wiki.openstreetmap.org/wiki/Tag:shop%3Dboutique

See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/shop_type/SpecifyShopType.kt for quest to be modified

**Comment by westnordost** [comment]
This feature request is too specific. It should rather be "Shall we treat deprecated shop types in the SpecifyShopType quest as if the shop type hasn't been specified yet?" , wouldn't you agree?

**Comment by matkoniecz** [comment]
I would rather phrase it as "deprecated shop values where fixing them requires resurvey as value is unclear"

Say `shop=mięsny` is deprecated but can be easily retagged to `shop=butcher` and asking people to resurvey it would be waste of time.

**Comment by westnordost** [comment]
Fair enough. So, I would say, that makes sense.

Are there any other `shop=` keys that are deprecated and could not be fixed by an automated edit because it could be either X or Y?

**Comment by matkoniecz** [comment]
`shop=hobby` is the only other worth bothering that I know, but I would need to recheck whether known alternatives got iD presets already (created some PRs/issues some time ago)

**Comment by matkoniecz** [comment]
`hobby` seems well covered:

<details>
<summary>verification code</summary>

```
import taginfo
import mwparserfromhell
import urllib

text = """** {{Tag|shop|bicycle}} – cycling
** {{Tag|shop|boat}} – sailing
** {{Tag|shop|fishing}} – fishing
** {{Tag|shop|hunting}} – hunting
** {{Tag|shop|outdoor}} – trekking, climbing, camping
** {{Tag|shop|photo}} – photography
** {{Tag|shop|sports}} – sport
* Indoor activity:
** {{Tag|shop|anime}} – manga, anime, cosplay
** {{Tag|shop|books}} – books
** {{Tag|shop|brewing_supplies}} – homebrewing
** {{Tag|shop|collector}} – stamps, coins, action figures
** {{Tag|shop|craft}} – painting
** {{Tag|shop|doityourself}} – do-it-yourself
** {{Tag|shop|fan}} – for fans of something, e.g. fan=harry_potter
** {{Tag|shop|games}} – board games, card games, RPG
** {{Tag|shop|model}} – scale models
** {{Tag|shop|music}} – recorded music
** {{Tag|shop|musical_instrument}} – musical instruments
** {{Tag|shop|radiotechnics}} – electronic components
** {{Tag|shop|stationery}} – cards, note books, pens, pencils
** {{Tag|shop|toys}} – toys
** {{Tag|shop|video_games}} – video games"""

# https://github.com/earwig/mwparserfromhell?tab=readme-ov-file#usage
wikicode = mwparserfromhell.parse(text)
templates = wikicode.filter_templates()
for template in templates:
   if template.name.lower() == "tag":
    key = str(template.get(1).value)
    value = str(template.get(2).value)
    print(key, value)
    entries_per_page = 500
    page = 1
    projects = []
    for entry in taginfo.query.projects_using_tag(key, value):
        projects.append(entry['project_id'])
    if "id_editor" not in projects:
        print(projects)
        raise


```

</details>

**Comment by westnordost** [comment]
An iD preset for "luxury clothes" doesn't exist yet.

**Comment by matkoniecz** [comment]
As I understand there was discussion that having such class is a mistake as it is utterly unclear what counts as one (in the same way as both actually luxury jewellers and trash "jewellers" are tagged in the same way).

And that `shop=boutique` in practise was also used for low-end shops that pretended a bit to not be a budget low quality shops.

I can start discussion thread at community forums to confirm this if you want.

**Comment by westnordost** [comment]
Well, I was just echoing what I read on the wiki page.

Also, boutiques **do** exist even though it is of course not a protected term. Classically, I've heard, these places are a bit like uh... style advisors, they have a small client base for which they kind of hand-pick clothes. I expect that it is of course a fluent transition to (expensive) clothes stores with clerks that extensively advice clients. Hence, I understand if `shop=boutique` should be removed because it is too ambiguous, but it still feels like an omission and potential data-loss to re-tag `shop=boutique` to `shop=clothes` with no subtag.

**Comment by westnordost** [comment]
So..., I don't want to have this ticket lying around here forever in some maybe-blocked limbo, so I treat it as an answered question:

**Yes, it is fine to ask users to specify the shop type (etc.) of ambiguous and deprecated `shop` values, as long as replacements for the previously selected shop type exist**

---

For shop=boutique, I would expect some kind of subtag of `shop=clothes` maybe with "boutique" as one of the terms or even aliases. For hobby - yeah, I will add it right away.
