### ISSUE TITLE
Don't ask "What barriers are used at this railway crossing?" for abandoned railways tagged in other ways

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#5597]
Similar to #2695.

This way:
https://www.openstreetmap.org/way/177660495/history/6

And specifically these nodes:
https://www.openstreetmap.org/node/9711611163/history
https://www.openstreetmap.org/node/9711611164/history

Triggered the railway crossing quest despite being tagged as `abandoned:railway=rail`

**How to Reproduce**
Check that way or other similar ones.

**Expected Behavior**
No quests show up.

**Versions affected**
SC 56.1

**Comment by westnordost** [comment]
I'd consider removing `railway=level_crossing` though, if they are not railway crossings.
