### ISSUE TITLE
No display of other things than the current layer

### ISSUE THREAD

**Issue by anthuil** [streetcomplete/StreetComplete#5599]
Hello everyone,

Since the 0.52 update (adding the "building" layer) I can't see any other objects than the ones from the active layer. I mean the background map, with road path and buildings shapes.

I added three screenshots of the same place, with different active layers (Buildings, Surface and Things).

![Building_overlay](https://github.com/streetcomplete/StreetComplete/assets/96052478/c161277b-2459-4960-9f4c-1476299d0128)
![Surface_overlay](https://github.com/streetcomplete/StreetComplete/assets/96052478/27f1816e-44dc-4321-ac06-ad0bf13c7bb4)
![Things_overlay](https://github.com/streetcomplete/StreetComplete/assets/96052478/5fc84ca5-52db-479e-a436-09b1f9621b1a)

While the app is still usable, it is really difficult to place shops and objects without the background to help you position them.

I tried changing the parameters, uninstalled and reinstalled the app, with no success.

I have no idea how to reproduce this, but it might be linked to my Android version that is starting to be quite old now (6.0.1).
The app version is 57.2

**Comment by matkoniecz** [comment]
see https://github.com/streetcomplete/StreetComplete/issues/5528 #5554

and https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0)

> I have no idea how to reproduce this, but it might be linked to my Android version that is starting to be quite old now (6.0.1).

yep, it is the source of problem

**Comment by westnordost** [comment]
In one sentence, the issue is that your phone is too old to trust certificates from Let's Encrypt by default, but the background map is downloaded from a server that is using these certificates. See the wiki link how you can fix this on your phone. (I expect you will have problems with many other apps too if you don't patch that.)

**Comment by matkoniecz** [comment]
Yeah, it is bug in Android itself so it cannot be solved by us (and Android and phone manufacturers is not making it easy to upgrade Android to fix it).
