### ISSUE TITLE
Trying to undo an edit breaks StreetComplete after switching between apps

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5600]
https://github.com/streetcomplete/StreetComplete/assets/25708359/a3f42de9-0cbe-441b-b7ac-ebe4cb2f90b6

**How to Reproduce**

1. Solve the quest
2. Click the Cancel quest button
3. Tap on the map or the cancel button on your phone
4. Press the button on your phone to switch between apps
5. Go back to StreetComplete
6. Highlight the last completed quest. However, it is not clear what the app expects next.

p.s. You can exit the quest by clicking the сancel quest button. The problem persists even if you complete new quests.

**Versions affected**

StreetCompelete 57.2
Samsung A52 
Android 14 OneUI 6.0

**Comment by westnordost** [comment]
Can reproduce
