### ISSUE TITLE
Canceling the quest doesn't work

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5602]
**How to Reproduce**
1. Solve the quest
2. Undo the edit
3. The quest disappears from history, but nothing changes

https://github.com/streetcomplete/StreetComplete/assets/25708359/e4909b6f-dce2-48e4-aaf2-e059a0d65bba

https://www.openstreetmap.org/way/1263228880/history

**Expected Behavior**

Changes are canceled on the map and in OSM

**Versions affected**

StreetCompelete 57.2
Samsung A52
Android 14 OneUI 6.0

**Comment by westnordost** [comment]
So the quest is not actually reverted, just removed from the edit history?

**Comment by deevroman** [comment]
Yes

**Comment by westnordost** [comment]
Hm, this bug is worth an update ASAP with fix. Looks like I will have some fun tomorrow.
