### ISSUE TITLE
Crash on selecting a path with the bike overlay on

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5604]
After updating to v57.3 I wanted to check the fix for #5596. 

But SC just crashes for me when I select a path. 

Tags on the path are 

```
highway=path
lit=no
smoothness=very_bad
surface=paving_stones
```

I've tried cleaning the cache and disabling and reenabling the overlay, with no avail. 

**How to Reproduce**
- Enable bicycle overlay 
- tap on a path 
- experience a crash of SC

**Expected Behavior**
- no crash

**Versions affected**
57.3

**Comment by westnordost** [comment]
Huh... that'd be bad. But I can't reproduce it. Can you tell me which path exactly you selected?

**Comment by RubenKelevra** [comment]
I've tried a couple. For example for way `1135830900` it crashes for me:


https://photos.app.goo.gl/hGa9VZugW92XuLY46

**Comment by westnordost** [comment]
I cannot reproduce it with this path.

Is there anything useful in the logs? (About -> Show logs)

**Comment by RubenKelevra** [comment]
No:

![Screenshot_2024-04-29-13-55-20-011-edit_de.westnordost.streetcomplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/43a6334b-3e19-4b82-b231-966c41093d18)

But here's the trace of a crash:

![Screenshot_2024-04-29-13-52-45-333-edit_com.miui.bugreport.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/b4b04f9c-dad7-4b88-80f9-bb8ce44c3b38)

**Comment by westnordost** [comment]
Oh... I understand. It will actually crash tapping on any path for you.

**Comment by RubenKelevra** [comment]
Yes

**Comment by RubenKelevra** [comment]
Thanks for the fast fix! :)

**Comment by westnordost** [comment]
You're welcome! 🙂
