### ISSUE TITLE
SC asking for maxheight quest with maxheight:forward and maxheight:backward present

### ISSUE THREAD

**Issue by mxxcon** [streetcomplete/StreetComplete#5609]
**How to Reproduce**
Look at way 1151405188.
![Screenshot_20240429_191033_Vespucci](https://github.com/streetcomplete/StreetComplete/assets/847140/4d88b58f-48fc-42d0-91dd-6c151ddce664)
![Screenshot_20240429_191004_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/847140/40a4cc2b-4994-497d-80b0-d221726d7a8b)

**Expected Behavior**
Maxheight quest should not come up. 

**Versions affected**
57.3

**Comment by matkoniecz** [comment]
If both are present then maybe adding one extra does not make sense.

I wonder how well it is supported in routers supporting `maxheight` - but that is a separate question, I guess.

**Comment by mxxcon** [comment]
> If both are present then maybe adding one extra does not make sense.

If `maxheight:forward/backward=` are present I think adding plain `maxheight=*` would be wrong..(and maybe there should be a validator for that too.)

What value would you put there? In my example the difference is just 2", but there can be more extreme situations where the difference is multiple feet/meters.

**Comment by westnordost** [comment]
The suggestion makes sense. If both are specified, not only is there no point in asking for the "general" height, but also if the height for the different lanes is different, there is usually neither a sign for the "general" height, but also it doesn't make sense to specify. Such situations occur if the tunnel roof is an arc.

**Comment by westnordost** [comment]
Example:

https://www.google.de/maps/@50.9757463,14.274041,3a,41.1y,8.64h,92.7t/data=!3m7!1e1!3m5!1sNY7QODtROc1daqzowhM7Dg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DNY7QODtROc1daqzowhM7Dg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D156.55505%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?entry=ttu

**Comment by HolgerJeromin** [comment]
> I also situation with different maxheight per lane in the same direction

That would be
`maxheight:lanes=3.7|3.9|3.7`

https://wiki.openstreetmap.org/wiki/Lanes

**Comment by westnordost** [comment]
added this for the same reason as above.
