### ISSUE TITLE
unable to upload

### ISSUE THREAD

**Issue by St897** [streetcomplete/StreetComplete#5624]
Hello,

i have attached the pictures from the phone

![4VkJnhwXTw-n2A8Fe8xhPA_52c458ee8cf092458e5d0806d151291fcd778ad4](https://github.com/streetcomplete/StreetComplete/assets/93713920/12c19581-5d4d-49f2-81a6-142276ad3c88)
![v06XFvJVR8OFFXADYV8CPg_e7147322e70343a7bf3e72d36ba4d54a8563e0d5](https://github.com/streetcomplete/StreetComplete/assets/93713920/e718e139-e4eb-4c81-9c14-500b51c29281)
![Da50NHsJRHGnehnUyBWFaA_f119d6167f4544975f60efd80add3fa6024521fd](https://github.com/streetcomplete/StreetComplete/assets/93713920/e518a072-24ec-4bc3-bf4c-d1dd7e8fa08a)
![e0fnBZq8Tl6EhlTVfGA2CQ_50b2571c8de519c282cfaf1694534eaef88d0e9a](https://github.com/streetcomplete/StreetComplete/assets/93713920/f1d3d061-c248-4bbd-be86-118484065562)

android 6 .. , ahum, installed via f-droid, used to work fine, the latest 90 changesets are unable to upload

hth

**Comment by FloEdelmann** [comment]
This might be the same error as in <https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0)>, i.e. a missing (or no longer valid) certificate.

**Comment by matkoniecz** [comment]
> android 6

definitely this

**Comment by matkoniecz** [comment]
Though if by any chance steps described there does not help: please comment.

But it matches #5528 #5554

**Comment by St897** [comment]
> This might be the same error as in https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0), i.e. a missing (or no longer valid) certificate.

yes, importing the certifcates fixed the problem; you can close this

**Comment by matkoniecz** [comment]
It is closed right now. Glad that this fix worked.
