### ISSUE TITLE
Enable Bus stop name quest for CA-QC

### ISSUE THREAD

**Issue by wolfy1339** [streetcomplete/StreetComplete#5625]
**Use case**

Allow users to add names to bus stops which currently do not have any in Canada.

At least in my area (CA-QC), if there is a shelter, the name will be posted on the shelter
**Proposed Solution**

Re-enable the quest, maybe more granularly.
It was asked previously for the MTA in NYC: https://github.com/streetcomplete/StreetComplete/issues/2126#issuecomment-773802224
The quest was disabled in https://github.com/streetcomplete/StreetComplete/commit/01fc6b530cdd4b8ac85d9fca8ce2b97617f0ef13 when the quest for `ref` numbers was added

**Comment by westnordost** [comment]
It is not possible to re-enable the quest only for bus stops that have shelters in Quebec. Do *all* bus stops in Quebec have a name?

**Comment by wolfy1339** [comment]
Of course they all have names... It's just that shelters have they more prominently displayed

It's the name announced on the bus, and shown on the screen inside the bus

**Comment by westnordost** [comment]
But is it visible on the bus stop itself?

**Comment by westnordost** [comment]
No feedback, closing.
