### ISSUE TITLE
Name quest for chapel calls it a church

### ISSUE THREAD

**Issue by Nielkrokodil** [streetcomplete/StreetComplete#5628]
See this note: https://www.openstreetmap.org/note/4234831
The chapel was tagged with:
```
amenity=place_of_worship
building=chapel
religion=christian
wheelchair=no
```
This is the standard tagging for a christian chapel. Nevertheless SC asks about a christian church instead.
The question text is: "What’s the name of this place?" – Christian Church

**How to Reproduce**

**Expected Behavior**

Ask What’s the name of this place? – Christian Chapel

**Versions affected**

StreetComplete 57.3

**Comment by matkoniecz** [comment]
we are using iD presets for that, see https://www.openstreetmap.org/edit?editor=id&way=637748178#map=19/48.20264/16.25494

if that is really wrong, then it may be worth discussing it at https://github.com/openstreetmap/id-tagging-schema

**Comment by Helium314** [comment]
iD also calls this element a church, so I'd say this is not an SC issue.
