### ISSUE TITLE
A few key has been deprecated.
like
building=clivic 
(use building=public)
maxspeed:type=sign
cycleway:both=k
(use cycleway=k)

### ISSUE THREAD

**Issue by Sylvia0476** [streetcomplete/StreetComplete#5629]
**How to Reproduce**

**Expected Behavior**

**Versions affected**

**Comment by westnordost** [comment]
On GitHub, you have a title field and a text field. The title field is for the title, the text field below is for the text.

Anyway, `building=civic` has not been deprecated. `maxspeed:type=sign` neither. `cycleway:both` neither.
