### ISSUE TITLE
Uh... has a small area to tap on

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5630]
Since a recent update, the `quest_generic_otherAnswers` string ("Other answers…" text) has been replaced with a new one, `quest_generic_otherAnswers2` ("Uh..."). I suppose this was done because for some cases, the space taken by the text needed to be reduced. However, I find that Uh... has a rather small area to tap on, so that I regularly missed it. Translating it as "Anders..." for the Dutch version I'm using improved it to a satisfactory level.

Would it be possible:
1. To use a slightly larger word than "Uh..." (maybe "Others..."), so it is easier to tap?
2. To use "Uh..." only in cases where the available space is very small, and use the old text ("Other answers…") where there is plenty of space (i.e. in most cases)?

Not a crucial issue, but when striving for perfection...

**Comment by Helium314** [comment]
I also stumbled upon this, though for a slightly different reason: the new (shorter) text is almost completely covered by the optional quick-hide button in SCEE. But I thought here the solution would be moving the button, as I didn't see the SC change as an issue by itself...

**Comment by mnalis** [comment]
ref: https://github.com/streetcomplete/StreetComplete/discussions/5573

**Comment by westnordost** [comment]
The button is not smaller than "yes" or "no". If it is too small, then the button areas in the button bar in general need to be enlarged.

**Comment by westnordost** [comment]
I checked in the code and tested it. The button actually fills the whole area. So if there is no other button in the bottom panel, you can click wherever in the button panel, if there is also e.g. "yes" and "no", you can still click on a third of the button panel.

The height of the button panel is also the same height as the size of the buttons in the map view. Doesn't seem to small to me.
