### ISSUE TITLE
"Place name:" becomes permanent default in street address quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5631]
In the street address quest, under Uh... (Other answers...), there is the option "It does not belong to a named street…" which leads to a field with white background where a neighbourhood name can be entered (which adds `addr:place=*`). This then becomes the default field when answering further street address quests. When the next street address quest is answered, you have to switch back to Street name by tapping the little triangle next to "Place name:" if you want to enter a street name instead of a neighbourhood name (i.e. go back to the field with the dark blue background). So far so good. However, when trying to answer further street address quests, Place name is always asked (i.e. it has become a permanent default) even if the previous answer was a Street name. Only restarting the app restores the default 

**Expected Behavior**
When answering the street address quest with a place name and for the next one a street name, the default field goes back to Street name:

**Versions affected**
It's been there for a long time, ever since I started using SC I think, but I hardly ever use this function (and others probably even more rarely) so I never reported it...
Definitely low priority...

**Comment by mnalis** [comment]
> However, when trying to answer further street address quests, Place name is always asked (i.e. it has become a permanent default) even if the previous answer was a Street name

Can confirm on `57.4`

**Comment by westnordost** [comment]
Street address quest or overlay?

**Comment by westnordost** [comment]
Ah nevermind, this is about the AddAddressStreet quest.
