### ISSUE TITLE
Trigger "medical laboratory" when "diagnostic" is searched (adding shops)

### ISSUE THREAD

**Issue by pandadeepimpact** [streetcomplete/StreetComplete#5637]
**Use case**

Medical laboratories commonly have "diagnostic" or "diagnostics" in their name, but no mention of "medical", and a lot even don't contain "laboratory" in their names. People don't regularly call them "medical laboratory" either (in my country, we don't have a specific term for them, people just say something like "go get your urine test there"), making it unlikely for most people to think of the words "medical" or "laboratory" when they encounter them.

**Proposed Solution**

When adding a POI, trigger "medical laboratory" when "diagnostic" is typed in the search box, to avoid the need for knowledge of the tag's name (which would beat the purpose of using StreetComplete), or worse, people skip adding these establishments to OSM when they can't think of what shop type to use (as StreetComplete requires adding the shop type first before the name).

**Comment by matkoniecz** [comment]
1) for many of these https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dsample_collection is a better match as such place only collects samples, and laboratory is in other or unknown location

2) aliases and search terms come from https://github.com/openstreetmap/id-tagging-schema - bad news is that they need to be improved elsewhere and we have no control over that another project, good news is that improvement come to also other editors, not only StreetComplete

**Comment by matkoniecz** [comment]
If this should be changed and is not yet fixed there (maybe it was changed and waits for release) and issue does not exist at https://github.com/openstreetmap/id-tagging-schema/issues - then creating new one may be a good idea

**Comment by pandadeepimpact** [comment]
[Done](https://github.com/openstreetmap/id-tagging-schema/issues/1222) :)

As for "Sample Collection", so far all establishments I encountered with "diagnostic" have their labs in the same location. It might be more confusing if both "Medical Laboratory" and "Sample Collection" will appear on that search term, as their difference is not apparent from their names alone, and StreetComplete provides no description for shops.

**Comment by rhhsm** [comment]
> 1. for many of these https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dsample_collection is a better match as such place only collects samples, and laboratory is in other or unknown location
> 
Thanks, I hadn't found that option yet! There's scope for improvement in the search terms for such places too, so they are found also when someone searches for "medical laboratory"

**Comment by matkoniecz** [comment]
> Thanks, I hadn't found that option yet! There's scope for improvement in the search terms for such places too, so they are found also when someone searches for "medical laboratory"

I opened https://github.com/openstreetmap/id-tagging-schema/pull/1223
