### ISSUE TITLE
Text for "Other answer" instead displays as "ER..."

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#5641]
Button for additional options on a quest just says "ER...", which seems like an error.

**How to Reproduce**

Tap on any quest that displays a button at the bottom to open a menu with other options. e.g. building levels, house number or street width. This button currently just says "ER..." which seems truncated. 

**Expected Behaviour**

I would expect the button to be labelled in a way that describes what options will be shown. (Didn't this used to say "OTHER ANSWER" or something along those lines?)

**Versions affected**

v57.3 
Language set to "system default" of English (United Kingdom).

**Comment by HolgerJeromin** [comment]
Not a bug. 
ref #5573
