### ISSUE TITLE
Ability to save edits locally

### ISSUE THREAD

**Issue by floledermann** [streetcomplete/StreetComplete#5642]
**Use case**

We are using StreetComplete in a research project where we want to evaluate the efficiency of various methods of mapping public urban space. In this context, it would help if we could save the edits made with the app locally instead of uploading them to OSM. We can disable automatic uploads, but as far as I know there is no way to access the edits made as a file or in any other form outside of the app.

**Proposed Solution**

When uploading is turned off, offer an entry in the Settings of About dialog that allows the export of the queued edits as a file. (I don't think this makes much sense when uploading is enabled, as then the changes can be accessed through OSM anyway.)

**Comment by Helium314** [comment]
You could use root privileges to access the SC database, which contains the local changes.

**Comment by FloEdelmann** [comment]
For reference: https://community.openstreetmap.org/t/forschungsprojekt-zum-mapping-von-parkplatzen-im-offentlichen-raum-in-wien/113258

**Comment by westnordost** [comment]
To cater to this kind of use cases is out of scope. Other than getting the SC sqlite database via root access to the device, you could:

- fork StreetComplete and implement an export of the edits list yourself

- each added change is logged. In the about menu, you'll find a screen with the recent logs (I think kept up to 14 days). You can filter the logs by "ElementEditsController" and you will find only the log entries that add the edit. What is logged is the quest/overlay type and the element that was edited (But not how it was edited). The logs can be exported to clipboard.

**Comment by Helium314** [comment]
@floledermann if you don't have any special needs regarding the format, I could create a special version of SC that can export local edits in some simple text file. (you wouldn't even need to log in with your OSM account for only doing local edits)

**Comment by HolgerJeromin** [comment]
> I could create a special version of SC that can export local edits in some simple text file.

OSC would be the obvious choice.
https://wiki.openstreetmap.org/wiki/OsmChange

**Comment by floledermann** [comment]
@Helium314 I was just made aware of your [SCEE fork](https://github.com/Helium314/SCEE), which sounds like a super interesting project. I am not sure if you are planning to include some sort of data export functionality to SCEE (or if it is already in there - on first glance I didn't see anything), but that would for sure be awesome for projects similar to ours. OSC looks like the format of choice to me too, as it can be integrated with other OSM-based tools.

Regarding our concrete project, we will have a meeting later this week to discuss which option to pursue further (it's not just up to me and unfortunately our resources are very limited in this project), so I don't want to waste anyone's volunteered time with a project we may end up not pursuing further. I will be in touch with you later regarding the question whether a special version of SC would be of help to us (I would also be willing to contribute a few hours of course, but I am not into Kotlin and/or Android dev right now so I would probably be relegated to testing or minor coding tasks, unfortunately).
