### ISSUE TITLE
Quest suggestion: Do the trees here have leaves all year around?

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5644]
### General

Affected tag(s) to be modified/added: [leaf_cycle](https://wiki.openstreetmap.org/wiki/Key:leaf_cycle)
Question asked: **Do the trees here have leaves all year around?**

### Checklist

Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [ ] 🚧 To be added tag is established and has a useful purpose
  It is approved and used over 4 million times. But use is probably "only" for academic/research, [QA](https://community.openstreetmap.org/t/notable-trees-of-osm/113020) and 3D rendering purposes. See <https://taginfo.openstreetmap.org/keys/leaf_cycle>.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  Not the whole year around though; just like the seating and grit bin quests, so it should be disabled by default. See <https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete%20default_disabled_msg_seasonal&type=code>.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  For `leaf_type=broadleaved`, 49% are tagged with `leaf_cycle=deciduous` and 11% are tagged with `leaf_cycle=evergreen`, see <https://taginfo.openstreetmap.org/tags/leaf_type=broadleaved#combinations>. [^1]
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

[^1]:  For `leaf_type=needleleaved`, 41% are tagged with `leaf_cycle=evergreen` and 1% are tagged with `leaf_cycle=evergreen`, see <https://taginfo.openstreetmap.org/tags/leaf_type=needleleaved#combinations>. So the quest should only be asked for `leaf_type=broadleaved`.

### Ideas for implementation

**Element selection:**  (similar to the existing `AddForestLeafType` and `AddTreeLeafType` quests)

```
ways, relations with
  (landuse = forest or natural = wood)
  and leaf_type = broadleaved
  and !leaf_cycle
```

```
ways with
  natural = tree_row
  and leaf_type = broadleaved
  and !leaf_cycle
```

```
nodes with
  natural = tree
  and leaf_type = broadleaved
  and !leaf_cycle
  and !~"(taxon|genus|species).*"
```

**Metadata needed:** Might only make sense where broadleaved evergreen trees are more common?

**Proposed UI:**

* "Yes" → `leaf_cycle=evergreen`
* "No" → `leaf_cycle=deciduous`

Other answers:

* "Only some leaves are kept the whole year" → `leaf_cycle=semi_evergreen`
* "Old leaves fall off right before new leaves grow" → `leaf_cycle=semi_deciduous`
* "Some yes, some no" → `leaf_cycle=mixed`

**Additional info:**

* #83

**Comment by westnordost** [comment]
This is difficult to answer because it is not visible in summer. Also, once the leaf type is added, its information value is very low, as only very few species that are broadleaved are evergreen. It is not worth asking for the leaf cycle in that case, IMO, might as well ask for the species then. #5279.

Additionally, it is spammy. The vast majority of broadleaved trees are deciduous.
