### ISSUE TITLE
Improve Postman achievement description

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5645]
As noticed in https://github.com/streetcomplete/StreetComplete/pull/5638#discussion_r1598853983, the current description for the Postman achievement doesn't match the [quests that count towards it](https://github.com/search?q=repo%3Astreetcomplete%2FStreetComplete+postman+language%3AKotlin&type=code&l=Kotlin):

https://github.com/streetcomplete/StreetComplete/blob/f4f7dcf465455da6694c6af8507f0c8b88c5b84b/app/src/main/res/values/strings.xml#L507

In particular, the postbox quests[^1] and new parcel locker quests[^2] don't match the description, while the address quests[^3] and the address overlay do.

[^1]: `AddPostboxRoyalCypher`, `AddPostboxRef`, `AddPostboxCollectionTimes`
[^2]: `AddParcelLockerBrand`, `AddParcelLockerMailIn`, `AddParcelLockerPickup`
[^3]: `AddRoadName`, `AddHousenumber`, `AddAddressStreet`

We should find a better description (and maybe also achievement title? → see #3009) that matches all these quests. Suggestions are welcome!

**Comment by mnalis** [comment]
perhaps something simple along the lines of:
```diff
- You helped to locate %d addresses!
+ You helped to locate %d addresses and other postal amenities!
```
