### ISSUE TITLE
Caused by: java.lang.AssertionError: Dispatch receiver type de.westnordost.streetcomplete.quests.width.AddWidthForm is not a subtype of de.westnordost.streetcomplete.quests

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5648]
maybe I should upgrade some of dependencies?

happens to me with 80c05fc404817a58e18f5d15077c45583be22f0f

log: https://gist.github.com/matkoniecz/8dfcaaaeb5504e2125c77cf4dcd924b0

**Comment by westnordost** [comment]
Rather sounds like an environment issue for me. I.e. update Android Studio and/or press "repair ide"

**Comment by westnordost** [comment]
Anyway, it compiles fine for me.
