### ISSUE TITLE
tracktype/surface conflicts are confusing

### ISSUE THREAD

**Issue by sjvudp** [streetcomplete/StreetComplete#5650]
After having collected several information bits about surface, lighting, etc. using different overlays, I had switch to the "Things" overlay.
Then I was asked for the surface of the same roads where I had set the property before, and even worse, it asked again and again for the same properties of the same roads.

**How to Reproduce**

Haven't tried, but maybe this:
Find some "unexplored" area, adding missing properties (like building types, road surface, house numbers, etc.) switching overlays.
Then switch to the "Things" overlay.

**Expected Behavior**

Mostly, properties still missing should be asked for.

**Versions affected**

Latest (v57.4)

**Comment by matkoniecz** [comment]
Things overlay should not result in new quests being asked and should only enable adding some features (note + button).

There is a related bug about some quests being reasked, and it is #5545

Can you post app log there? You have latest version with some new logging in place.

**Comment by Helium314** [comment]
What might also be relevant: were you offline all the time, or did you upload the answers where the quests were shown again?

**Comment by westnordost** [comment]
So, to summarize, please paste the log of when this issue occured. Use filters in the logs screen (Main menu -> About -> Logs)  to narrow down the logs to the time it actually happened. If you remember exactly for which elements on OSM this occured, it would even be more helpful, for then we can search in the logs for entries that mention those elements.

**Comment by sjvudp** [comment]
> Can you post app log there? You have latest version with some new logging in place.

When I checked the logs after reading the comment, it seems that (the log as displayed lacks the date, it seems) it only had entries for the current day, but I needed yesterday's logs.
OK, the default filter just showed the current day, so I could get yesterday's logs. I removed the part before leaving the house.

[log.txt](https://github.com/streetcomplete/StreetComplete/files/15370907/log.txt)

AFAIR the issue happened for https://www.openstreetmap.org/way/158959209

> were you offline all the time

Yes, I was offline while "on the road". That's what I usually do: Update the quests and regions I plan to visit, then go out offline, and eventually when returning back home online, upload the data.

**Comment by westnordost** [comment]
Right, this is (unfortunately) not related to #5545 but to the fact that `tracktype` is removed by StreetComplete in the surface quest or overlay if it thinks that the previously recorded `tracktype` value conflicts with now selected surface value.

In this case, StreetComplete thinks that `tracktype=grade1` conflicts with `surface=grass_paver`.

I agree that this decision dubious at best, but probably just plain wrong. Grass paver is pretty much a paved surface. And even if it was right, this is opaque to the users, how should a user know that grass pavers specifically should lead to a tracktype lower than grade1, it is not communicated.

@matkoniecz , it's your code, what would you say?

**Comment by westnordost** [comment]
The filter is definitely much too strict. The wiki simply says it is a "solid" surface. Even "ice" is solid.

**Comment by westnordost** [comment]
+ the commits after that. Should have done that in a branch and then merge it. Oh well.

**Comment by riQQ** [comment]
2aa7cc43d28abb5f1717b8ccb9cf8d47f7cddf79
9f9eaf6b4b2d14c3e5ab5e57a52d6925a06794b9
21f0f6e5d340140d6f5772d850c0f4358163cc8e
875a4fe55799e7ef37338396afa3b32631a4148e
27af0947d1500debcc9e87cd334520b278717fd3
