### ISSUE TITLE
Unable to edit amenity=post_box in "things overlay"

### ISSUE THREAD

**Issue by vizsim** [streetcomplete/StreetComplete#5651]
**How to Reproduce**
Unable to see existing `amenity=post_box` or able to add `amenity=post_box` in "things overlay":

when trying to add `amenity=post_box`. it does not show up in search:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/16351144/3e09b89f-6855-4af2-a22e-45743bdfb1ea)

existing `amenity=post_box` does not show up in streetcomplete:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/16351144/a7962cb3-a863-4c98-bb78-6bfa195f4944)
https://www.openstreetmap.org/node/331471850

existing `amenity=post_box` on osm.org:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/16351144/32921c27-641b-4df4-a01b-4221b5c57aae)

**Expected Behavior**
Able to see existing `amenity=post_box` and able to add `amenity=post_box`.

**Versions affected**
57.3

**Comment by vizsim** [comment]
ah sorry, didnt see/find that issue.
Just found this list 
https://docs.google.com/document/d/1tcLm0EDWoCBdkq1N0pKebtksJcF2vMtUgKc9h96fuF0/edit
and thought it is supposed to work.

thank you for the explanation.

**Comment by matkoniecz** [comment]
added note in doc
