### ISSUE TITLE
Use NSI data in preference to usage data for operators/brands

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5655]
**Use case**

Some quests (like `AddAtmOperator`, `AddParcelLockerBrand`, `AddClothingBinOperator` etc.) offer the user autocomplete for common operator/brand names for that country, which is great and saves on typing time and typos a lot!

However, those suggestions (e.g. [app/src/main/assets/country_metadata/HR.yml](https://github.com/streetcomplete/StreetComplete/blob/46a3605c1337f88d0d62a2e140121d1e6f9ffd03/app/src/main/assets/country_metadata/HR.yml#L3), [res/country_metadata/atmOperators.yml](https://github.com/streetcomplete/StreetComplete/blob/46a3605c1337f88d0d62a2e140121d1e6f9ffd03/res/country_metadata/atmOperators.yml#L2431)) are however of varying completeness and quality. For example in Croatia:

- `atmOperators` for Croatia for _"OTP banka"_ lists 7 different names:  _OTP,  OTP Bank,  otp banka,  otpbanka,  OTP banka, OTP Banka,  OTP banka d.d._ (and other banks are not much better, this is just an example).
- `parcelLockerBrand` also misses values e.g. for `DPD` (which is also currently mapped with different similar names).

That is suboptimal, and promotes again adding various variants of the names instead of the official ones.

**Proposed Solution**

[NSI](https://nsi.guide/) (name-suggestion-index) contains a curated list of preferred operator/brand names for countries per amenity, and is as such of much higher quality and without duplicates. 

It seems [QLeverCountValueByCountryTask.kt](https://github.com/streetcomplete/StreetComplete/blob/31ddb8693adad46704a59adb7c4dad28b65260f2/buildSrc/src/main/java/QLeverCountValueByCountryTask.kt#L20) is responsible to generate those lists.

I would suggest that appropriate script be **modified to use NSI instead, and only fall back to usage data** if no NSI entries are found for that amenity for that country. 

That way, **much higher quality** would be achieved. [^1]

In addition, using NSI it would **also be in sync** what `Thing Overlay` does  (for example when one searches for `OTP` to add `amenity=atm` for OTP bank).

_(see discussion starting at https://github.com/streetcomplete/StreetComplete/pull/5638#discussion_r1600431543 for more details about the issue.)_

[^1]: alternative solutions considered were to do [mechanical edits](https://wiki.openstreetmap.org/wiki/Automated_edits) for existing data and [imports](https://wiki.openstreetmap.org/wiki/Import) for low-usage/missing ones, but those are fraught with problems, time consuming, require separate effort for each country and each amenity, and won't fully solve the problem anyway, as people are updating the map all the time, and exact timing when StreetComplete will fetch the data is unknown, so unwanted variations of names will still seep in anyway unless one dedicates effort to do such mechanical edits daily

**Comment by westnordost** [comment]
I think it makes sense to replace the by-number-of-usages approach with NSI.

#3708 suggests to prepend the current data with NSI. This ticket proposes to only take the by-number-of-usages data if NSI does not exist. Both approaches I find effortful and complex to maintain.

I'd like to discuss **replacing** the by-number-of-usages data with **exclusive** use of NSI. This only makes sense if the coverage of frequent values in NSI is good.

Question is, for which of the quests (if not all?) that ask for the operator of a thing

- ATMs
- charging stations
- clothes containers
- parcel lockers

... is the NSI coverage comprehensive?

We already have the data on which brands/operators are tagged. Anyone willing to compare this with the NSI?

**Comment by mnalis** [comment]
> We already have the data on which brands/operators are tagged. Anyone willing to compare this with the NSI?

I'm afraid it would probably need not only a lot of (probably mostly manual) normalizing, but also local knowledge to get sensible results, though. 

For example, in Croatia [SC](/app/src/main/assets/country_metadata/HR.yml) lists `74` ATM operators, while in reality (and in [NSI](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&tt=atm&cc=hr)) there exist only `21`. Naive counting would indicate NSI for ATMs is very weak in Croatia, while in reality NSI for Croatian ATMs has just recently been updated to be near-perfect. 

Many of the differences in numbers are:
- various spellings duplicates as noted above, but some are
- banks which have been renamed (e.g. _"Kreditna banka Zagreb"_ => _"Agram banka"_) or
- acquired banks (e.g. _"Sberbank"_ => _"Nova hrvatska banka"_ => _"Poštanska banka"_) or 
- tagged by international group name instead of local bank name (e.g. _"Privredna banka Zagreb"_ => _"Intesa Sanpaolo"_)

Many of those would be very hard if not impossible to research for someone who isn't local. I don't know how situation is in other countries, but it might have some of the similar issues. 

One could always look up their own country at https://nsi.guide/index.html?t=brands&k=amenity&v=atm (just enter `Country code`) and verify how good it is for their country and report here their estimate (or even open [issue / PR at NSI](https://github.com/osmlab/name-suggestion-index/issues) to rectify the issues), but I'm skeptical that some global automated script could give us reasonable answer :cry:

**Comment by matkoniecz** [comment]
working Croatia SC link: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/country_metadata/HR.yml

**Comment by mnalis** [comment]
> Looked a bit for Poland and it seems to have an opposite problem: NSI lists cases where banks are not present here

Other than that _Nordea_ which has ceased to exist, how had the Poland data quality in NSI looked to you?

**Comment by westnordost** [comment]
> in Croatia [SC](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/country_metadata/HR.yml) lists 74 ATM operators ...

Let me clear up the requirements for this research: Neither some automatic script is necessary, nor it is necessary for a positive result that NSI covers all values present in the database. It should just cover the common and frequent options. The NSI options will just be shown as suggestions, after all. One can still write by hand.

**Comment by mnalis** [comment]
> Let me clear up the requirements for this research: Neither some automatic script is necessary, nor it is necessary for a positive result that NSI covers all values present in the database. It should just cover the common and frequent options. 

I'd like to help if that is not huge amount of work, but I'm unfortunately **still unclear** what such task (as you envision it) would entail. Could you be more precise / give example?

Because; to answer whether _"It covers the common and frequent options"_ I would still need **intimate knowledge of that specific country**. For example, NSI lists dozen or so of  [ATM operators in Bulgaria](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&tt=atm&cc=bg). 

However, I cannot even read Bulgarian cyrillic letters properly, much less say if that list is representative of situation in Bulgaria. So I would need to research Bulgarian banking system (with help of automated translators) so I could even try to answer whether NSI lists majority of popular banks there, or just 10% of them (and perhaps maybe most of them are small and irrelevant ones). 
IOW, it would be a complex task for someone not from Bulgaria (yet for someone living in Bulgaria, it might be a simple 1-minute answer _"yeah that looks like about most of the important ones"_).  

Doing such research for the _whole world_ would seem unreasonable amount of work to ask of a single person, so I'm guessing you're not asking for that; but then I am am unsure of what kind of "proof" would be satisfactory?

---

What I can say is it looks very good in Croatia, and @matkoniecz (if I understand him correctly) seem to indicate that most important Polish ATM brands are also present in NSI. While I might _guess_ it is also good in e.g. [Germany](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&tt=atm&cc=de), I have no means to verify that (without putting significant amount of work into it).

**Comment by matkoniecz** [comment]
Previously for this kind of situation there was shared document where people could mark that they checked info for given region.

**Comment by westnordost** [comment]
It's fine to compare currently tagged values (i.e. as they are specified in the YML files) with NSI: Are the most frequent options available in NSI? Countries where there is overall very little of this data filled in at all can be ignored.

**Comment by rhhsm** [comment]
> Because; to answer whether _"It covers the common and frequent options"_ I would still need **intimate knowledge of that specific country**. For example, NSI lists dozen or so of [ATM operators in Bulgaria](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&tt=atm&cc=bg).
> 
> However, I cannot even read Bulgarian cyrillic letters properly, much less say if that list is representative of situation in Bulgaria. So I would need to research Bulgarian banking system (with help of automated translators) so I could even try to answer whether NSI lists majority of popular banks there, or just 10% of them (and perhaps maybe most of them are small and irrelevant ones). IOW, it would be a complex task for someone not from Bulgaria (yet for someone living in Bulgaria, it might be a simple 1-minute answer _"yeah that looks like about most of the important ones"_).


Yeah that looks like about most of the important ones... though afaik Groupama doesn't operate ATM s in Bulgaria, and that a brand can be written in both Cyrillic and Latin script creates additional possibilities (Fibank vs. Първа инвестиционна банка). @Dimitar5555 created the brand iD presets for Bulgarian banks, parcel lockers and clothing recycling bins, so he should know better.

**Comment by mnalis** [comment]
> It's fine to compare currently tagged values (i.e. as they are specified in the YML files) with NSI: Are the most frequent options available in NSI? Countries where there is overall very little of this data filled in at all can be ignored.

Even if we look only at those ATM operators with more than 10 instances, that is still (`perl -ne 'print if /# (\d+)/ && $1 > 10' atmOperators.yml | wc -l`) about **1750** entries to check. Sounds like quite a chore to check manually one by one! 

Looking at `> 100` instances reduces that to more manageable 232 entries (still not a breeze to manually copy/paste one by one to https://nsi.guide by any standard, but in realm of possible). Would that suffice?

What I am particularly worried however is all different spellings (esp. acronyms which seems popular in some countries) and non-latin scripts, so many entries are possibly more work than just copy/paste.

**Comment by Dimitar5555** [comment]
> Yeah that looks like about most of the important ones... though afaik Groupama doesn't operate ATM s in Bulgaria, and that a brand can be written in both Cyrillic and Latin script creates additional possibilities (Fibank vs. Първа инвестиционна банка). @Dimitar5555 created the brand iD presets for Bulgarian banks, parcel lockers and clothing recycling bins, so he should know better.

Most banks are in NSI except Tokuda (recently bought by БАКБ), Bulgarian Development Bank (it works under special rules and you can't deposit money there), BigBank (online bank), Citi, Varengold, ING (I haven't seen offiices of the last three). I've just added a few which were missing (namely Ziraat, Texim, DBank and International Asset Bank). Also removed Groupama (they are not a bank here) and BNP Paribas (now part of Postbank).

For parcel lockers, I don't think that we are missing anything (except if something new hasn't come to the market). For the clothing recycling/donation bins, the big 3 or 4 companies are there. I'm unaware of other companies but there might be some in other municipalities.

**Comment by westnordost** [comment]
mnalis, you could do as Mateusz suggested and each document for which country you checked it down to what number. Note that on the path, you will inevitably find banks whose ATMs should be added to NSI, but this will anyway also be a positive contribution, as iD editors also profit from that.

**Comment by Cj-Malone** [comment]
Python doesn't like `NO` in yaml.

Here is my rough go at matching [atmOperators.yml](https://github.com/streetcomplete/StreetComplete/blob/eb55473b394a1c429ab78cac1e074e59f7fe3d77/res/country_metadata/atmOperators.yml) to NSI.

https://gist.github.com/Cj-Malone/a55600ec7d6d6b2894397061af584d67

**Comment by mnalis** [comment]
> https://gist.github.com/Cj-Malone/a55600ec7d6d6b2894397061af584d67

Thanks for the effort, @Cj-Malone  :heart: 

Unfortunately, as I was worried, automated approach produces huge number of errors, as to be unusable.

I'll take Croatia (`HR`) as an example as I'm familiar with it. Your scripts says there are 74 ATM operators in HR, and that only 37 (exactly  50%) are present in the NSI, and that 37 are missing.

However, in reality, that is highly incorrect. **Of the 37 `False` results, almost all are invalid guess by the script** (i.e. different spellings, alternate names, networks instead of operators, name instead of amenity, renamed/acquired banks, etc.) -- there is one which is indeed missing in NSI -- that is `shitcoins.club`, which is automated Bitcoin exchange and not classical ATM, which is pending https://github.com/osmlab/name-suggestion-index/issues/9542)  

While some of those might perhaps be matched with some kind of fuzzy matching , some with fetching Wikidata items and looking for alternate names / history of names / parent groups, some with more advanced AI, significant amount of incorrect non-matches would still remain. I'm thus worried that such **automated approach** (except in trivial cases, e.g. no entries at all in NSI) are more **likely to mislead us** than give useful insight. 

Manually going through the list will give _somewhat_ more precise results (i.e. you might _guess_ that `Erste Banka` and `Erste&Steiermärkische Bank` are the same thing, and checking wikidata [P1448](https://www.wikidata.org/wiki/Property:P1448) for [Q125756504](https://www.wikidata.org/wiki/Q125756504) would reveal that `Kreditna banka Zagreb` is actually `Agram banka`), but without local knowledge you'd likely still be stuck with many false results (feel free to try it to get a feel - would you guess that `Privredna banka` is the same as `PBZ bankomat`? That `Poštanska banka` is the same as `HPB`? As is `Jadranska banka`? How about `Nova hrvatska banka`, can you find which one of the matched operators it is? etc. some digging will reveal many of the answers, but it is not trivial at all...)

That is what I meant by _"unreasonable amount of time"_... I'm afraid such approach is doomed to failure; which is why I suggested **alternative approach of having per-country `prefersNSI` flag**...

**Comment by Cj-Malone** [comment]
The whole point of NSI is matching to OSM. They have a matcher, iD has a matcher, Rapid has a matcher. None of these matchers have AI or fetch Wikidata, they use the labels in the entry and `matchNames`. For items in this list, which fail to match to the valid NSI entry, the entry can, and should, be [updated](https://github.com/osmlab/name-suggestion-index/commit/69545cfbf087236e055ddb5795cec01cc96ca324) so everyone benefits. [GB](https://github.com/osmlab/name-suggestion-index/commit/320459e7a51dcbf6d877c84e0578a037e2adf29f)

But even if you still want to do your manual per country thing, I've just halved the list that need be checked. Spend your time on the ones that have failed to match.

**Comment by mnalis** [comment]
> The whole point of NSI is matching to OSM. They have a matcher, iD has a matcher, Rapid has a matcher.

Could we ask them to give us their statistics instead of trying to produce our own? Or is it the same as you shared?

> None of these matchers have AI or fetch Wikidata, they use the labels in the entry and `matchNames`. 

I believe you, I just observed that such simplistic approach seems to produce significantly lower quality of data (i.e. error bars of 50% on measurements).  I apologize if I offended.

> For items in this list, which fail to match to the valid NSI entry, the entry can, and should, be [updated](https://github.com/osmlab/name-suggestion-index/commit/69545cfbf087236e055ddb5795cec01cc96ca324) so everyone benefits. [GB](https://github.com/osmlab/name-suggestion-index/commit/320459e7a51dcbf6d877c84e0578a037e2adf29f)

Thanks, that is indeed useful. I'll certainly look up Croatian names and check if NSI `matchNames` should be updated! 
(I however do not feel qualified nor have enough free time to try to do that for whole world). 

Is there some documentation how `matchNames` should be used / for what it is appropriate and for what not @Cj-Malone ? I'm especially wondering about:

1. commonly used names? (I assume yes, e.g. `Erste banka`, `Erste bank`, `Erstebank`, `Erste` should all be added)
2. name differing only in case (e.g. `Erste Banka` vs. official `Erste banka`?). Or should matchNames always be in lowercase / is case insensitive?
3. commonly misspelled names? (e.g. `Raiffeisen` vs. `Raiffaisen` ?)
4. random misspellings present in OSM database? (e.g. `Euonet` instead of `Euronet`)
5. bank renaming? (e.g. `Kreditna banka Zagreb` decided to rebrand as `Agram banka` ?)
6. bank acquisitions? (e.g. `Jadranska banka` was acquired by `Hrvatska poštanska banka` a decade ago)
7. acronyms? (e.g. `HPB` for `Hrvatska poštanska banka`, also used as website www.hpb.hr)

 
> But even if you still want to do your manual per country thing, 

Yes, I think it would be easy to accomplish, and allow for incremental improvements, instead of investing a lot of effort into  all-or-nothing solution (esp. if result happens to end up being "nothing").

> I've just halved the list that need be checked. Spend your time on the ones that have failed to match.

I really do appreciate your work,  but as I noted [earlier](https://github.com/streetcomplete/StreetComplete/issues/5655#issuecomment-2150030005), I personally do not intend to spend my time on such drudgery, even if it is now only  3446 ATM operators instead of original 6713 to manually check.

**Comment by Cj-Malone** [comment]
I'm on my phone now, but I'll tag some people that may know more about the NSI matcher tomorrow. There may be an difference with them looking at name, and you at operator. But we will see.

I'm not offended, and I didn't spend much time on it. No worries.

I don't know if there are docs, but there is code in the NSI repo for name simplification. Again I'm on my phone, so won't link it right now.

Off the top of my head:

1. Spaces don't count. You only need one of them in the entry.
2. Case is ignored, as is punctuation.
3. Spelling mistakes would need to be a match name
4. Rare misspellings may get a bit more of push back, if there is any a few, just fix OSM.
5. Yeah, in some cases it might make sense to have `old_name` on the entry, this means searching OSM will be better. In other cases, it can be added as a match name.
6. Yeah, fine as a match name, not as `old_name`
7. Yeah, same short_name, brand:short or match name.

(Match names get used for matching, but never end up in OSM, display name gets shown in iD and Rapid, but isn't used for matching or added to OSM)
