### ISSUE TITLE
Old opening_hours=* seems not to be removed, if opening_hours:signed=no is set by StreetComplete

### ISSUE THREAD

**Issue by fabi003** [streetcomplete/StreetComplete#5660]
See https://www.openstreetmap.org/node/2240184500/history (version 11 from SC 57.1),
https://www.openstreetmap.org/node/2678567862/history (version 15 from SC 48.0) or
https://www.openstreetmap.org/node/2102640486/history (version 5 from SC 46.1).

**Comment by Helium314** [comment]
Why should they? Maybe the person who initially entered them just went inside and asked, so removal just because there is no sign might not be appropriate.

**Comment by matkoniecz** [comment]
Closing per @Helium314 

If opening hours could not be checked then they should not be removed.
