### ISSUE TITLE
Quests for opening hours are also asked for zoo=enclosure within a zoo

### ISSUE THREAD

**Issue by guerda** [streetcomplete/StreetComplete#5662]
Ways with the tags `tourism=zoo` and `zoo=enclosure` are included in the opening hours quest even if they are within a zoo. As enclosures can only have working hours outside of a zoo, it might be good to exclude it (if possible).

The quest makes sense for enclosures e.g. in a forest, so it should only skip enclosures surrounded by a zoo way.

**How to Reproduce**
1. Create a way with `tourism=zoo`
2. Add some ways with `tourism=zoo` and `zoo=enclosure` within the zoo.
3. Download StreetComplete tasks for this area

**Expected Behavior**
Opening hours quests are only asked for the zoo, not the enclosure.

**Versions affected**
v57.3

**Comment by matkoniecz** [comment]
> Ways with the tags tourism=zoo and zoo=enclosure are included in the opening hours quest even if they are within a zoo. 

If something is not a zoo and is tagged as `tourism=zoo` then it should be fixed in OpenStreetMap.

If there is zoo within zoo then SC should ask.

>  Opening hours quests are only asked for the zoo, not the enclosure.

They are. ("Ways with the tags tourism=zoo")

**Comment by matkoniecz** [comment]
In general, StreetComplete does not add elaborate filters to support handling of broken data.

**Comment by guerda** [comment]
> If something is not a zoo and is tagged as tourism=zoo then it should be fixed in OpenStreetMap.

Any enclosure should be tagged as `tourism=zoo` according to the wiki. https://wiki.openstreetmap.org/wiki/Tag:zoo%3Denclosure

**Comment by matkoniecz** [comment]
> The tag [zoo](https://wiki.openstreetmap.org/wiki/Key:zoo)=enclosure is used to describe a type of zoo (tagged with [tourism](https://wiki.openstreetmap.org/wiki/Key:tourism)=[zoo](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dzoo)) where the animals are kept in enclosures or cages.

So it should not be used on individual enclosures.

Later there is

> Part of zoo fits this description
> Create an [area](https://wiki.openstreetmap.org/wiki/Area) inside [tourism](https://wiki.openstreetmap.org/wiki/Key:tourism)=[zoo](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dzoo) and tag it [zoo](https://wiki.openstreetmap.org/wiki/Key:zoo)=enclosure.

Note that it has "Create an area inside tourism=zoo and tag it zoo=enclosure." without mention of tagging it also tourism=zoo. 

Maybe "do not tag it tourism=zoo in such case" should be explicitly mentioned there and general description should mention using it to tag individual enclosures?

And either way, no matter what https://wiki.openstreetmap.org/wiki/Tag:zoo%3Denclosure would say, tagging part of zoo as entire zoo would be wrong anyway.

I would be happy to discuss it more at tagging mailing list or official forum or OSM Wiki talk page - please leave here link if such discussion would be started.

**Comment by guerda** [comment]
Thanks for looking into this and discussing this. It makes sense to discuss this somewhere else.

**Comment by Helium314** [comment]
Possibly `tourism=zoo` is added because it's listed under **Requires**.
From thje wiki page it's not clear though whether the **Requires** exclusively refers to the element tagged with `zoo=enclosure`, or to surrounding areas or maybe nearby nodes with `tourism=zoo`.

**Comment by matkoniecz** [comment]
That part was self contradictory with wiki page itself so I edited it.

**Comment by matkoniecz** [comment]
I also started https://wiki.openstreetmap.org/wiki/Talk:Tag:zoo%3Denclosure#Part_of_zoo_fits_this_description_-_maybe_make_clear_that_part_of_zoo_should_not_be_tagged_as_a_zoo%3F
