### ISSUE TITLE
Ask if benches have armrests

### ISSUE THREAD

**Issue by bompstable** [streetcomplete/StreetComplete#5664]
### General
Affected tag(s) to be modified/added: [armrest](https://wiki.openstreetmap.org/wiki/Key:armrest)
Question asked: **Does this bench have armrests?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- ✅ 🚧 To be added tag is established and has a useful purpose
  - This provides useful information for older people and those with reduced mobility. People can use armrests to lean against and to help them get on and off the bench. Areas looking to upgrade the accessibility of their infrastructure can use this information to identify benches that need upgrading.
  - The tag is established but is not currently recorded for many benches - [taginfo:armrest](https://taginfo.openstreetmap.org/keys/armrest#overview) shows ~4,800 yes/no values at present.
- ✅ 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  - This is a yes/no answer
- ✅  🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- ✅ 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  - Many benches have armrests,  many do not
- ✅ 🕓 Applies to a reasonable number of map data (Worth the effort)
  - [taginfo:amenity=bench](https://taginfo.openstreetmap.org/tags/amenity=bench#overview) shows ~2.5M benches

### Ideas for implementation
**Element selection:** 
`amenity=bench` and `armrest !=*`

**Metadata needed:** 
I don't believe any metadata is needed.

**Proposed UI:**

Although this is a simple question with a yes/no answer, one potential confusion is that the answer to this question should be "yes" regardless of the number of armrests that a bench has. It may be useful to include some example pictures for which the yes answer applies. Examples for which the answer is yes:
- benches with an armrest at either end (the most common case)
- benches with armrests between each seat
- benches designed to allow people in wheelchairs to transfer onto them - some of these only have an armrest at one end (see https://wiki.openstreetmap.org/wiki/File:Wooden_bench_with_backrest_and_one_armrest.jpg)

Cases where the user cannot answer would likely be the same as for the existing "Does this bench have a backrest?" quest and some may no longer apply if the backrest quest is shown first.

Note, I'm interested in implementing this myself but want to first check it would be accepted.

**Comment by westnordost** [comment]
> 🚧 To be added tag is established and has a useful purpose 

I don't see the useful purpose fulfilled. The backrest quest was already pretty borderline, I think I wouldn't accept it if it was added today.

If I remember correctly, I only accepted the backrest quest because someone directly created a PR for that and because back then, neither the "does this still exist?"-quest nor the things overlay existed. So, it was argued that the quest is at least good for checking whether the bench still exists. This doesn't apply anymore, but no point in removing that quest now.

**Comment by jnicho02** [comment]
Just for context, the OP has been told by a UK Local Authority that they need to catalogue bench assets with their accessibility (backrest, armrest). Having it in StreetComplete would be a powerful way to answer their inevitable next question, "but how do we get people to survey this info?". It could then be another step on the way to getting Local Authorities to stop hoarding data and simply OSM it

**Comment by mnalis** [comment]
> "but how do we get people to survey this info?"

- Seeing that `armrest` has been added to [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/blob/87d7b90f93c822c879392466016c55b0e7932905/data/presets/amenity/bench.json#L5), I guess next release of [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door)  which fetches it should include support for that automatically, I think. It is also not hard to use app (and has advantage to working on _both_ Androids and iPhones, something StreetComplete doesn't do [yet](https://github.com/streetcomplete/StreetComplete/issues/5421)).

- Alternatively one might [suggest the quest](https://github.com/Helium314/SCEE/issues) to [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (_"Expert Edition"_ fork of StreetComplete) which might be open to including that quest (for example, it includes bench material quest which has been rejected here for similar reasons in https://github.com/streetcomplete/StreetComplete/issues/4407). 
  But SCEE is only available as manual `.apk`  download or from `F-droid` repository, which might add another obstacle to majority of people that are used only to Google Play (or whatever came preinstalled on their device) 

- Or, perhaps the best idea, one might improve [MapComplete benches theme](https://mapcomplete.org/benches) to include it? While not as sleek design as StreetComplete, it works on any browser (including mobiles ones), and so does not require installing anything, which should make it most easily accessible on _any_ device.

**Comment by bompstable** [comment]
Please note, I have no affiliation with any council or organisation that is directly involved in planning or providing seating.

As @jnicho02 notes above, I took part a while ago in volunteer tasks organised by my local council to survey the benches in the area. They had not got a clear record of the infrastructure in their area and so wanted people to physically visit locations and identify where there were benches. Amongst the information we were asked to collect was whether the benches had backrests and whether they had armrests. Since then my council has commissioned an accessibility assessment into their provision of facilities including seating and this contains some interesting information on benches which I will attempt to summarise here:

- Both backrests and armrests on benches are very important to people with mobility issues and other requirements
  - Backrests provide important support to people using a seat
  - Armrests:
    - help people to lower themselves on to the seat and to stand up afterwards
    - help wheelchair users to transfer laterally on to a seat
    - can also help people with visual impairments to identify benches as they are often contrasting colours
-  Benches without armrests or backrests result in difficult (or impossible) use for many people
- It is important to provide usable benches at frequent intervals to allow people to  to rest on visits or journeys to a location
- People with accessibility requirements are likely to plan their routes around available seating

I'm not sure if the report itself has been shared publicly, but it draws heavily on references to [BS 8300‑1:2018](https://images.reading.gov.uk/2021/10/8f-Appendix-6-BS-8300-1-2018-Built-Environment.pdf), and [Inclusive Mobility - A Guide to Best Practice on Access to Pedestrian and Transport Infrastructure - GOV.UK](https://assets.publishing.service.gov.uk/media/61d32bb7d3bf7f1f72b5ffd2/inclusive-mobility-a-guide-to-best-practice-on-access-to-pedestrian-and-transport-infrastructure.pdf).

I've also been told anecdotally that in surveys, older people have cited having nowhere to sit as a barrier to going out.

I would argue that the current simple tagging of whether a bench has a backrest and armrests in OSM provides very valuable accessibility information to prospective users of benches and to organisations involved in planning and assessing their provision of benches. With the sort of decent coverage of this information that a StreetComplete quest could achieve, resources could provide people with information from OSM about the suitability of available seating on their journeys and visits. To me, this sort of purpose is in line with the existing quests geared towards gather accessibility information on resources.

**Comment by westnordost** [comment]
Hmm, interesting. 

[Inclusive Mobility - A Guide to Best Practice on Access to Pedestrian and Transport Infrastructure - GOV.UK](https://assets.publishing.service.gov.uk/media/61d32bb7d3bf7f1f72b5ffd2/inclusive-mobility-a-guide-to-best-practice-on-access-to-pedestrian-and-transport-infrastructure.pdf) mentions armrests on page 102:

> Armrests are helpful for some [...]

[BS 8300‑1:2018](https://images.reading.gov.uk/2021/10/8f-Appendix-6-BS-8300-1-2018-Built-Environment.pdf) mentions armrests on page 50:

> b) For some seats, back support and arm rests should be provided as some people requiring support need both.

> d) Arm rests should be provided to help people lower themselves onto the seat and stand up. [...]

---

Although, I have to note, that the mention of armrests is almost a side-note compared to the many other things described in these documents: Height of the bench sitting area, height of the backrest, "type" of bench (perch seats, bench, benches that are actually rather seats with armrests next to each other, ...)

And the use case for all of this seems to be really mostly statistics, as I can't imagine someone searching for specific bench features on a smartphone.

**Comment by bompstable** [comment]
There are indeed many things that could be captured about benches but many would require measurements, which is rather too specialist for many mappers.

For now, I believe the simple information of "has a backrest" and "has armrests" is of demonstrable use. I am envisaging cases such as maps showing the type of bench with different icons, or enabling people to select which sorts of bench to include. This is similar to current usage of things like cycle parking information - stands, wheelbenders etc.

Of course, there's also the use cases I haven't imagined yet. There's always a bit of a chicken and egg situation with such data.

**Comment by Tex2002ans** [comment]
Fantastic @bompstable. I fully agree with this. :)

And as I mentioned in previous reports—something that's extremely easy to verify in-person, hard to tell by satellite. :)

**Side Note:** I just checked my "backrests" number in StreetComplete—and I've mapped 86 so far! Plus a quest like this would give me *another* excuse to add and sit down in every single one! :)

- - -

> The backrest quest was already pretty borderline, I think I wouldn't accept it if it was added today.

Hmmm... I find it enjoyable to map + feels like important data too.

For example, it helps differentiate between:

- A [flat rectangle slab to sit on](https://www.theparkcatalog.com/media/catalog/product/cache/11ac34c768bcc5f64a73a58f3e00ba27/1/1/112233.jpg)
- An [actual chair-type bench](https://makemesomethingspecial.com/wp-content/uploads/2018/05/personalised-benches-uk-makemesomethingspecial.com_.jpg).

(I find that 1st type tends to exist a lot near sports too. Where the 2nd type tends to exist along walkways.)

- - -

> I am envisaging cases such as maps showing the type of bench with different icons, or enabling people to select which sorts of bench to include.

Yeah. There's [already some that show different icons for `backrest=yes`/`no`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench#Rendering).

If this armrest tagging became more popular (current 5k->1 million like backrests!) then perhaps that can be adjusted too. :)

When I see little different icons on the map I've never seen before, it makes me click on it + look deeper into it... then I stumble upon extra tags I never even KNEW existed before! Then in future satellite/armchair mapping, I tend to add it at step 1! :)

- - -

> Of course, there's also the use cases I haven't imagined yet. There's always a bit of a chicken and egg situation with such data.

Yeah, that's how I feel too. Like if it gets added as a preset in iD, it makes it more visible, so more likely to be tagged. (Like yesterday, I ran across an odd one. Field Hockey = a preset, but Lacrosse = no. Field Hockey = ~5.4k uses. Lacrosse = ~600 uses.)

We get a great quest added in here like this "armrest" one, and slowly, incrementally, I suspect the usage will organically go way up. :)

**Comment by bompstable** [comment]
I was curious to see how this would be implemented so have created the above pull request.

**Comment by matkoniecz** [comment]
Maybe having backrest and armrest quests but disabled by default would make sense?

So only people actually interested in topic would get them? And people not into it would not get poor effort-to-value quests?

**Comment by bompstable** [comment]
I've tried to explain the value of this quest in my previous comments. I would question the argument that this is poor effort-to-value as it is very low effort and may provide important information for those with restricted mobility.

People can hide quests that they aren't interested in, but quests that are hidden by default may never be discovered.

The way I've implemented this only requires two new strings so hopefully isn't too much of a burden to translate.

**Comment by rhhsm** [comment]
I like these kind of low-value, low-effort quests, because it stimulates me to add these items to the map. Every bench added to the map in the Things overlay results in 1 and hopefully 2 quests by which I can earn stars :) Same for fire hydrants, trees, recycle bins, drinking water sources, etc.

> The way I've implemented this only requires two new strings so hopefully isn't too much of a burden to translate.

I'm translating SC to Dutch, and find it very little effort to translate a few strings each time a new version is released.

**Comment by Tex2002ans** [comment]
Based on:

- [piebro.github.io: "OpenStreetMap Statistics" > StreetComplete: "How Many Edits Does Each Quest Have?"](https://piebro.github.io/openstreetmap-statistics/#6773)

It looks like `AddBenchBackrest` is 31st most popular, with:

- 359,886

added since 2018. So it's more than 1/5th of [all marked in OSM so far](https://wiki.openstreetmap.org/wiki/Key:backrest)! :)

**Comment by mnalis** [comment]
- (for those interested, MapComplete has implemented armrests in https://github.com/pietervdvn/MapComplete/pull/2034)

**Comment by westnordost** [comment]
I finally rejected this quest suggestion. Sorry for contemplating it so long. See https://github.com/streetcomplete/StreetComplete/pull/5673#issuecomment-2246249378

**Comment by mnalis** [comment]
For those interested, `armrest=*` quest was included in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) some time ago.

**Comment by matkoniecz** [comment]
And https://github.com/Helium314/SCEE/issues/922 has me being really confused by it, which does not encourage me to include it in SC after all
