### ISSUE TITLE
Crossing kerb height quest should not be asked for roads that have no sidewalks

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5668]
I was asked for the kerb heights of this crossing https://www.openstreetmap.org/node/4580460754 https://maps.app.goo.gl/cG59Z6JmDuAA8zd26 which I think is silly as it has no sidewalks (and is tagged as such) and thus has no kerbs. Of course I could reply "no kerb" but that would be adding useless info as a road without sidewalks obviously has no kerbs. I can imagine two expected behaviours:

1. Crossing kerb height is not asked for crossings for which the road it crosses has no `sidewalk=*` tag (i.e. sidewalk quest has to be answered first to activate this quest)
2. Crossing kerb height is not asked for crossings for which the road it crosses has `sidewalk=no`

**Comment by mnalis** [comment]
> 2. Crossing kerb height is not asked for crossings for which the road it crosses has sidewalk=no

This one sounds reasonable to me.

(the first one sounds way too aggressive, esp. as `sidewalk=*` quest is not asked in many cases, like when there is separately mapped `highway=footway` nearby IIRC)

**Comment by rhhsm** [comment]
> This one sounds reasonable to me.
> 
> (the first one sounds way too aggressive

I think so too: making the quest dependent on the sidewalk quest is indeed aggressive considering that the number of cases is probably small. My reaction to getting the quest was to switch to sidewalk overlay to check if sidewalks had been tagged, and when I saw they were not, I tagged the road as not having sidewalks. To my surprise the quest didn't go away, so I opened this issue.

> , esp. as `sidewalk=*` quest is not asked in many cases, like when there is separately mapped `highway=footway` nearby IIRC)

Not since #5060

**Comment by Helium314** [comment]
> To my surprise the quest didn't go away, so I opened this issue.

As far as I remember the quest would not go away even if your idea was implemented, because quests are only re-created for the changed elements (in this case the road, not the crossing node).
