### ISSUE TITLE
Add Type "Floor" to bicycle_parking type Quest

### ISSUE THREAD

**Issue by Piagno** [streetcomplete/StreetComplete#5669]
"Floor" Type on the bicycle_parking=* quest cannot be chosen, even though it's possible it exists in many places.

Add the floor type to the bicycle_parking=* quest.
[https://wiki.openstreetmap.org/wiki/Key:bicycle_parking](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking)
Use the same picture as used on the Wiki.

**Comment by mnalis** [comment]
Should be already solved in https://github.com/streetcomplete/StreetComplete/issues/5191, available in `v58.0`. Which version are you using @Piagno ?

**Comment by Piagno** [comment]
I'm not using streetcomplete directly, but solve many notes of streetcomplete users. I just double-checked if it exists with the version on f-droid (57.3) and I didn't search the solved issues.
So this issue can be closed.

Thanks for checking matija.

________________________________
Von: Matija Nalis ***@***.***>
Gesendet: Sonntag, Juni 2, 2024 5:28:21 PM
An: streetcomplete/StreetComplete ***@***.***>
Cc: Flavio Piagno ***@***.***>; Mention ***@***.***>
Betreff: Re: [streetcomplete/StreetComplete] Add Type "Floor" to bicycle_parking type Quest (Issue #5669)


Should be already solved in #5191<https://github.com/streetcomplete/StreetComplete/issues/5191>, available in v58.0. Which version are you using @Piagno<https://github.com/Piagno> ?
