### ISSUE TITLE
Remove qwant maps

### ISSUE THREAD

**Issue by Chaman-veteran** [streetcomplete/StreetComplete#5676]
**How to Reproduce**

Unlock citizen 2 and watch links to other applications.

**Expected Behavior**

Following [this comment](https://github.com/Qwant/erdapfel/issues/1474#issuecomment-2114812144), Qwant maps is no longer maintained. It was first moved to another url (#5634), but AFAIK it's now redirecting to qwant.com.
As such, Qwant Maps needs to be removed from the link list.

**Versions affected**

57.4

**Comment by matkoniecz** [comment]
I guess that `Link` entry can be removed without any complicated migration setup anywhere else?

Looking at https://github.com/streetcomplete/StreetComplete/commit/798fe7f10c0f60c6141f474b1bbd273598215038 there is need to remove:

- icon
- relevant string
- entry referencing link code for the achievement

**Comment by westnordost** [comment]
Could maybe be replaces by https://osmapp.org/ or/and https://benmaps.fr/

**Comment by Jean-BaptisteC** [comment]
Or https://cartes.app/

**Comment by westnordost** [comment]
I love the map style of benmaps. But the problem with benmaps is that it quite heavily relies on mapbox stuff (traffic, satellite, ...) so more publicity may even be bad for him, as it might get quite expensive the more users there are. Plus of course, with mapbox, e.g. the "contribute to this map" link does not even lead to openstreetmap.

Main problem with cartes.app is that it is in French only, no translation.

So, I am going with osmapp now, cartes could maybe be added later.

**Comment by westnordost** [comment]
Also, I read that it is not an oversight that cartes is French only, as it is specifically a France-specific map.

**Comment by severo** [comment]
Update on cartes.app: it's not specific to France anymore. It is now available in multiple languages and all the services work worldwide. Can I propose a PR to add it to the list? If so: where would it make more sense?
