### ISSUE TITLE
What conflict(s) is this memorial for?

### ISSUE THREAD

**Issue by jmizv** [streetcomplete/StreetComplete#5681]
### General
Affected tag(s) to be modified/added: [Key:memorial:conflict](https://wiki.openstreetmap.org/wiki/Key:memorial:conflict)
Question asked: **What conflict(s) is this memorial for?**

The wiki page lists several conflicts that could be added to the `memorial:conflict` tag. Note that one could add more than one value to the tag, e.g. memorial for World War 1 and World War 2 would be `WW1;WW2`.

Looking at Germany, I find almost 6500 nodes and ways that would be selected by the StreetComplete element filter stated below. In Overpass:
```
[out:json][timeout:25];
area["name:de"="Deutschland"]->.de;
(nw["historic"="memorial"]["memorial"="war_memorial"][!"memorial:conflict"](area.de););
out meta geom;
```

There are already almost 1500 memorials tagged with their conflict(s) in Germany.

There are also about 600 war memorials in Australia that don't have this tag.

I would give it a try and implement this quest myself if/when the quest is approved to be implemented.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

I'm quite aware that answering this question might need some basic knowledge of history. And you probably need to approach the memorial. Therefore I hesitated to give an X to the squirrel in the above list.

### Ideas for implementation

**Element selection:** 

```
nodes, ways with historic=memorial
    and (memorial = war_memorial
        or memorial and war_memorial = yes)
    and !memorial:conflict
```

**Metadata needed:**

Not really sure about this.

**Proposed UI:**

I've taken some inspiration from other quests. I think that it would be hard to have some nice iconic pictures for each (!) conflict like we have this already for the other memorial question. So I would instead display at a minimum the name of the conflict and the given years, cf. wiki page. Maybe we could have flags or similar as icons to the conflicts so the user would have a clue, e.g. 
* :es: [Spanish Civil War 1936 - 1939](https://en.wikipedia.org/wiki/Spanish_Civil_War)
* :earth_africa: [World War II 1939 - 1945](https://en.wikipedia.org/wiki/World_War_II)
* :israel: [The Holocaust 1940 - 1945](https://en.wikipedia.org/wiki/The_Holocaust)
* :algeria: [Algerian War of Independence (1954-1962)](https://en.wikipedia.org/wiki/Algerian_War)

Regarding the ordering of the possible answers: I could imagine to have an UI where there is an ordered list of all conflicts and above that the five most recently used ones? But here I only have a basic UI: 

![mockup-streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/37914724/2aca5032-0524-4592-aa97-594b113be034)

**Comment by matkoniecz** [comment]
The tricky part is that history had a looooooooooot of conflicts which get memorialised.

Collecting them all and translating as part of SC is not feasible. And I am not aware of any good enough source to be used here, with info which conflict would be likely memorialised where.


In way that would not degrade this quest to end creating mostly notes.

**Comment by matkoniecz** [comment]
Actually freeform box may work here - though per https://wiki.openstreetmap.org/wiki/Key:memorial:conflict it seems to expect names in English...

https://taginfo.openstreetmap.org/keys/memorial:conflict#values seems to confirm this.

So user would need to know English names, so it fails "Easily answerable by any pedestrian" as not all of them will know English names. 

For example, I had no idea how https://en.wikipedia.org/wiki/Polish-Soviet_War was named in English before I checked internet right now.

**Comment by matkoniecz** [comment]
I think I will close it as not doable - but if by any chance someone has **reliable** source of conflict names, with their translations of decent coverage and ideally with info where each conflict is memorialised then it can be reopened.

Note that translations of names are required as this app is not limited to English speakers.

**Comment by mnalis** [comment]
> So user would need to know English names, so it fails "Easily answerable by any pedestrian" as not all of them will know English names.

Makes sense for StreetComplete. 

Freeform text solution should probably be eligible for [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork), should the @jmizv want to submit issue [there](https://github.com/Helium314/SCEE/issues).  I do not think that such list in SCEE would need to be translated, as quest requirements are much more relaxed in SCEE.

Another alternative UI might be dropdown list just from entries listed on https://wiki.openstreetmap.org/wiki/Key:memorial:conflict which could be automatically pulled from wiki and parsed on each new release. That would eliminate misspelling issues, but at a "drawback" of having to document conflicts on the wiki first and wait for next release. (and more complex implementation, of course)

**Comment by matkoniecz** [comment]
> Another alternative UI might be dropdown list just from entries listed on https://wiki.openstreetmap.org/wiki/Key:memorial:conflict which could be automatically pulled from wiki and parsed on each new release. That would eliminate misspelling issues, but at a "drawback" of having to document conflicts on the wiki first and wait for next release. (and more complex implementation, of course)

This may be enough for SCEE but it has no translations and very spotty coverage so it would be not enough for SC.

I have not investigated using Wikidata but I bet that coverage and "list armed conflicts without listing things which are not actually armed conflicts, maybe some rare mistakes would be allowed" would almost definitely fail. (and I am not signing up for maintaining such thing, I am already doing it with less user-exposed one and I have backlog of issues there)
