### ISSUE TITLE
Enable editing "Things" in the Things overlay

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5684]
**Use case**
I came across a bank today that had changed brand. It was easy to change the node for the bank in the "Places" overlay to the correct brand, but I found out that changing the brand of the ATM in that branch in the "Things" overlay is not possible

**Proposed Solution**
Enable editing of "Things" nodes in the Things overlay just like it is possible in the Places overlay. I can imagine that when the Things overlay was made, it was not thought necessary to enable editing of things. It would be very rare that a tree would have to be changed to a fire hydrant or a bench... However, assuming that the code needed can be copy-pasted with few modifications from the Places overlay, it could also be argued "Why not?" I see 2 use cases that could be common:

1. edits to branded things like ATMs, parcel lockers, etc in case one brand stops operating them and another brand replaces them, if a brand is taken over by another company, rebranding operations, etc.
2. correcting mistakes, such as `amenity=waste_basket` <-> `amenity=waste_disposal` <-> `amenity=recycling`, different playground equipment, `amenity=watering_place` <-> `amenity=drinking_water`, etc.

**Comment by matkoniecz** [comment]
> I can imagine that when the Things overlay was made, it was not thought necessary to enable editing of things. 

Actually, it was considered and deliberately removed.

In case like that intended flow is to mark currently existing one as gone (delete it) and create a new one.

For rebranded ATM it would make sense to edit its brand but for vast majority of cases retagging them raises a whole host of complexities and hidden side effects.

**Comment by rhhsm** [comment]
> In case like that intended flow is to mark currently existing one as gone (delete it) and create a new one.

Hadn't thought of that workaround. A shortcut for that could be add under the other answers: "It's something else" (or "It does not exist" to keep consistency with the Places overlay) which will delete the node (or all its tags, to keep the history) and create/retag the new "thing" node.

**Comment by rhhsm** [comment]
Where can I read about the disadvantages of my proposal so this issue was closed?

**Comment by mnalis** [comment]
- probably discussion around https://github.com/streetcomplete/StreetComplete/pull/5373#issuecomment-1850038791 seem relevant

**Comment by rhhsm** [comment]
> * probably discussion around [street furniture overlay #5373 (comment)](https://github.com/streetcomplete/StreetComplete/pull/5373#issuecomment-1850038791) seem relevant

Seems like I had similar thoughts, but came to a different conclusion. I don't have an idea how much effort it is to implement, so that could be a reason not to do it.
