### ISSUE TITLE
Add `parcel_mail_in=returns_only` option to parcel locker drop off quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5687]
**Use case**
The new Parcel Locker drop off quest (#5639) shows options Yes or No. However, the wiki gives a third option `parcel_mail_in=returns_only` (Machine does not allow sending parcels but returning parcels is allowed.) For one of the 4 brands of parcel lockers in Bulgaria, this would be the correct choice, and choosing No would be wrong.

**Proposed Solution**
Add the `parcel_mail_in=returns_only` option too (so the options would be "Yes", "No", and "return parcel only")

**Remark**
I find this quest quite spammy. So far, the reply to "Can you pick up parcels here?" has always been "Yes". I wonder if there any parcel lockers where you can't pick up parcels, because that's the reason for their existence, isn't it? Wrt. parcel drop-off, the possibility is likely to be the same for all parcel lockers of a certain brand, so the answer is likely to be the same for each brand. It would then be much more efficient to add this information to the parcel locker brand preset, and exclude that brand from the SC quest.

**Comment by westnordost** [comment]
@Arthur-GYT

**Comment by Arthur-GYT** [comment]
I'll will take a look as soon as I can.

**Comment by westnordost** [comment]
Regarding spamminess: Indeed, more than 99% of parcel lockers tagged with `parcel_pickup` do have `parcel_pickup=yes`, so indeed it seems to be a good idea to at least disable that quest by default.

Regarding brands: Hmm, really not sure if this would really always the same for the same brand. A situation where a brand have different types of lockers, some allowing e.g. mail-in and others not would be completely possible. Also, note that that quest just asks for the brand, and then just tags the `brand`, nothing else. It does not use any NSI presets.

**Comment by rhhsm** [comment]
Did some more research in the meantime: only 0.42% (130) of parcel lockers have `parcel_pickup=no`. They are fairly evenly spread over the world, i.e. there is no particular country where most of them are located. None of them are in Bulgaria. In the Netherlands, there were two: one DHL which according to DHL website does allow parcel pickup, and one PostNL where the website doesn't mention pickup at all, possibly because it's obvious. Both the DHL and PostNL parcel locker presets in iD contain `parcel_mail_in=yes` and `parcel_pickup=yes` tags. I suspect that a large number of parcel lockers with  `parcel_pickup=no` are wrongly tagged.
`parcel_mail_in` values are more spread: almost 90% yes, 8.6% no and about 2% return only, so seems more suitable for a quest.

**Comment by matkoniecz** [comment]
> one DHL which according to DHL website does allow parcel pickup

Have you fixed it or opened note for that?

**Comment by westnordost** [comment]
Note that `parcel_mail_in=returns_only` occurs very rarely, so it can be fine to just leave a note in this case.

**Comment by westnordost** [comment]
I've looked it over right now, and I prefer leaving the pickup quest active by default. It is true that the answer is pretty much always the same, but the user is already in front of the locker and just read the information on it, so he can immediately answer it.

**Comment by westnordost** [comment]
I went ahead and fixed it.

**Comment by rhhsm** [comment]
The more I think about this, the more I'm convinced that these quests should not be on SC at all, because they don't meet the quest guidelines and there are much better ways to add the information than a survey.

The parcel locker pickup quest is way too spammy, as the answer is almost always yes. Parcel lockers are there to pick up parcels, it's their main function. 99.53% of the `parcel_pickup` tag has value `yes` (isn't that "an overwhelming percentage"?), and I suspect that the almost 40% of parcel lockers that don't have this tag are also yes because it's the default value.

The parcel locker mail in quest probably also has an overwhelming percentage of quests with the same answer, if you look at each brand separately. The websites of parcel locker brands I've seen all describe their mail in possibilities in general terms, which suggest that for each brand, they either always allow (`yes`, 90% according to taginfo), not allow at all (`no`, 8.6%) or `returns_only` (2%). This information is then much easier to retrieve from the brand's website and added to the brand preset instead of asking SC users to survey each parcel locker to check it. I don't think we should waste SC users' time on this. The quest should only be active for parcel locker brands where the value varies between lockers, which I suspect are very few.

**Comment by matkoniecz** [comment]
In such case it is much better to open a new issue requesting removal (unless it was opened and closed already?)

Comments in old issues are likely to be missed

**Comment by mnalis** [comment]
I'd just add that usually it is better solution to request disabling quest by default if needed, instead of removing it.

(people who use those quests, for whatever reason, are likely to object to removal of already existing quests, especially if in their own small corner of the map the quest is more useful then globally)
