### ISSUE TITLE
Ask for `centralkey=eurokey` for toilets for people with disability

### ISSUE THREAD

**Issue by seyfeb** [streetcomplete/StreetComplete#5689]
### General
Affected tag(s) to be modified/added: [`centralkey=eurokey`](https://wiki.openstreetmap.org/wiki/Key:centralkey)

I am suggesting to ask if

[`centralkey=eurokey`](https://wiki.openstreetmap.org/wiki/Key:centralkey)

should be added to nodes that have [`amenity=toilets`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) and [`wheelchair=yes`](https://wiki.openstreetmap.org/wiki/Key:wheelchair) or [`toilets:wheelchair=yes`](https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair) set

Question asked: **Is a Eurokey required for accessing the disabled toilet?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
    According to multiple websites there are about 12k toilets using the lock for the Eurokey ([1](https://www.service.bremen.de/dienstleistungen/purchase-of-a-euro-key-for-disabled-toilets-144542), [2](https://disabledaccessibletravel.com/european-toilet-keys/), [3](https://shop.cbf-da.de/product_info.php?products_id=73)). Considering the next point this would amount to 1/5 of the answers.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
    I can not definitely answer this but if I understand correctly, [there are about ~60k objects](https://taginfo.openstreetmap.org/tags/toilets%3Awheelchair=yes#overview) tagged `toilets:wheelchair=yes`

### Ideas for implementation

**Element selection:** 

The quest should be shown for toilets for disabled persons, either tagged by

[`amenity=toilets`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets)
[`wheelchair=yes`](https://wiki.openstreetmap.org/wiki/Key:wheelchair)

or by

[`toilets:wheelchair=yes`](https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair)

**Metadata needed:** 

The quest should only be shown in countries where the Eurokey is available.

For Australia the quest should ask for `centralkey=mlak` and for UK it should be `centralkey=nks` according to [the wiki](https://wiki.openstreetmap.org/wiki/Key:centralkey).

**Proposed UI:**

As an icon the wheelchair symbol used for toilets with an additional key icon could be shown.

![StreetComplete_quest_wheelchair_key_green](https://github.com/streetcomplete/StreetComplete/assets/7623143/dc3aa1d1-4f08-49a8-8df3-df848d3afa85)

In the quest there could be an example image for a eurokey toilet lock like the one in the [wiki](https://wiki.openstreetmap.org/wiki/Key:centralkey) or one like the one in [this thread](https://community.openstreetmap.org/t/ist-das-ein-euroschlussel/108044/7) where the letters CBF (the association distributing the keys (at least in Germany)) are visible.

**Comment by westnordost** [comment]
I have strong regarding

> 👨‍💻 Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary

> 🐿️ Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible

That is pretty much expert knowledge. How should a user know when there is just a lock and when there is a lock openable with some standard key? Apparently, one cannot expect that "EUROKEY" is always labelled next to the lock. Also, according to the wiki at least, eurokey is German. This seems to me that it is not worth it to dive into that to find which standards are used in which countries.
Is there a tag for "wheelchair toilet is locked"? Because that would be more easily answerable than `centralkey`, although, (even) less useful.

> 🕵️ Publicly accessible on foot

Also, note that this is not fulfilled at least for `toilets:wheelchair=yes`.

**Comment by matkoniecz** [comment]
In addition to issues about which I got ninjaed in post above so will not repeat it...

> According to multiple websites there are about 12k toilets using the lock for the Eurokey ([1](https://www.service.bremen.de/dienstleistungen/purchase-of-a-euro-key-for-disabled-toilets-144542), [2](https://disabledaccessibletravel.com/european-toilet-keys/), [3](https://shop.cbf-da.de/product_info.php?products_id=73)). Considering the next point this would amount to 1/5 of the answers.

Are you sure that Europe has only 60 000 public wheelchair accessible toilets? I would expect more.

**Comment by seyfeb** [comment]
> How should a user know when there is just a lock [...]?

You are right. I'd assume it's not improbable that a Eurokey would fit if a wheelchair toilet in Europe is locked, but there is no guarantee unless you own a key and try it out. Which most don't, obviously ;)

> Is there a tag for "wheelchair toilet is locked"?

There is the [locked](https://wiki.openstreetmap.org/wiki/Key:locked) key, which in combination with the disabled toilet keys would result in "wheelchair toilet is locked".

> Also, according to the wiki at least, eurokey is German

Afaik, Eurokey originates in Germany but is also used in other European countries, see, e.g., [eurokey.ch](https://www.eurokey.ch/en/index.html).

> >    🕵️ Publicly accessible on foot

> Also, note that this is not fulfilled at least for toilets:wheelchair=yes.

I think the toilet itself is not accessible by foot when it is locked, but the lock should be accessible?

> Are you sure that Europe has only 60 000 public wheelchair accessible toilets? I would expect more.

It is certainly more. I was just referring the ones tagged on OSM, as pointed out , which would trigger the quest!

**Comment by westnordost** [comment]
So, I'll close this, based on 

> 👨‍💻 Users are no experts
> 🐿️ Easy answer

Need euro key to try it out or (international) clear standard how this is labelled, which as far as we know does not exist.

> 💤 Not an overwhelming percentage of quests have the same answer (No spam)

Not clear how much percent of wheelchair toilets would be locked (and specifically with eurokey)

**Comment by seyfeb** [comment]
Alright!
Just for reference, if anyone stumbles upon this thread: While researching the issue I found an app called [HandicapX](https://themenwelt.handicapx.de/der-euroschluessel-euro-key/) where users can share the locations and information such as special-key requirements of restrooms. I did not try it out, though.

**Comment by mnalis** [comment]
As a workaround @seyfeb, when answering StreetComplete quests for wheelchair accessibility for toilets,  instead of just answering `yes`, you can answer `Uh...` / `Can't say` / `LEAVE NOTE` and then indicate in that OSM Note that there exist wheelchair accessible toilet which is locked with eurokey (or whatever else).

Then you or anybody else can post-process those OSM Notes later (in iD or JOSM or whatever full-fledged editor) and add required tags to those places.

(You can also use `Things overlay` to add completely missing toilets, or long-press on the screen anywhere it add a Note)

**Comment by seyfeb** [comment]
@mnalis I'm aware, I can edit the node myself. My point was the point of StreetComplete, to make updating OSM easy and intuitive for the broad mass of people. But your hint may be helpful to others, so thanks for pointing that out!
