### ISSUE TITLE
Add missing building types: mall and clinic, and show the building type if it is not selectable in app.

### ISSUE THREAD

**Issue by realeatham** [streetcomplete/StreetComplete#5690]
Currently, there is no option for a mall / shopping center or a clinic / medical place smaller than a hospital and both show up as other building not selectable in app. The building type should be shown even if its not in the app and both clinic and mall should be added as types.

**Comment by matkoniecz** [comment]
> Currently, there is no option for a mall

what is wrong with "retail" option?

>  clinic / medical place smaller than a hospital

Is it really a distinct building form? I would assign them "civic" and tag POI itself as clinic/doctor office etc.

> The building type should be shown even if its not in the app 

Note that it is not really possible for app to magically interpret and translate any `building=*` value (it has aliases for some - which one exist in OSM data in nonnegligible numbers and are missing support?)

**Comment by realeatham** [comment]
>what is wrong with "retail" option?

Retail is one shop, a mall/ shopping center is a building for many and is used in osm data

>Is it really a distinct building form? I would assign them "civic" and tag POI itself as clinic/doctor office etc.

 👍

>Note that it is not really possible for app to magically interpret and translate any building=* value (it has aliases for some - which one exist in OSM data in nonnegligible numbers and are missing support?)

I mean just show the value. Like If it was mall, the app would show other not in app, and that mall was the value.

**Comment by mnalis** [comment]
See [FAQ: Building Type Quest - Why don't I see the right types?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?) and https://github.com/streetcomplete/StreetComplete/issues/3868 -- building type quest is only about specific **architectural type**, e.g. regular "house" was built/looks different than a  "hangar" which is different than a "garage". (and yes, it is not very useful information for end-users, which I guess is one of the reasons why _"What kind of building is this?"_ quest has been disabled by default).

But the quest is **not about what it is being used for** -- e.g. even if it was being build as "garage", it could nowdays be used a shed, or a "hangar" can be used as an marketplace, or a "church" can be used as a pub (all real-life examples).

To mark **what the building is actually being used for**, you need to use _**"Places Overlay"**_ in StreetComplete and add/modify/delete your clinic, doctors, etc. as POIs inside that building (there could be multiple ones inside building too).

**Comment by westnordost** [comment]
Thanks @mnalis, I have nothing to add. @realeatham please pay particular attention to his last paragraph. If you haven't used the overlays yet, the places overlay is a a very convenient way to add and update shops and other places. If you ran out of places to add, you can also check out the "things" overlay, to get into even more detail.
