### ISSUE TITLE
Object description in MarkCompletedBuildingConstruction quest can be confusing in combination with yes/no answers

### ISSUE THREAD

**Issue by stragu** [streetcomplete/StreetComplete#5691]
See how [this object](https://www.openstreetmap.org/way/1073700315/history) was changed by [this changeset](https://www.openstreetmap.org/changeset/152478418).
Looks like, for an object that only has `building=construction` but no use of the `construction` key, the quest only updates the `check_date` when answering that the construction is completed.

**How to Reproduce**

1. Find a MarkCompletedBuildingConstruction quest for an object with only the `building=construction` tag
2. Answer that the construction is completed

**Expected Behavior**

Shouldn't the tag be replaced with `building=yes`?

**Versions affected**

58.0

**Comment by mnalis** [comment]
Cannot reproduce.  Can you give link to specific building where that is happening to you?

For me, your situation that only `check_date` gets updated (and `building=construction` remains) happens only when _"No"_ is chosen as an answer to _"Is this building completed?"_ as it [should be](https://github.com/streetcomplete/StreetComplete/blob/d129eb8618ad01d37c793854fe44cd3cc0f55013/app/src/main/java/de/westnordost/streetcomplete/quests/construction/MarkCompletedBuildingConstruction.kt#L28-L39).

When I choose _"yes"_, it gets updated correctly:
![small_Screenshot_20240617_043739_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/156656/abc1c1ad-5c2d-4d84-92ca-9f3dc7ca9d4f) ![small_Screenshot_20240617_043600_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/156656/6dc6d726-1097-4c50-a1a9-6d19018fd80e)

**Comment by stragu** [comment]
Hm I think you're right, I just tested on another building and can't reproduce the issue...
I must have gotten confused by the question and picked the wrong answer, maybe focusing on the  "Building Under Construction" wording...
Sorry for the noise!

**Comment by mnalis** [comment]
But now that you mention it, I can see how it can be confusing with that _"building under construction"_ subtitle. 

- Perhaps _"Is this building still under construction?"_ (and inverting yes/no answers) would make it less likely to be misunderstood? (then again, there is translation effort involved to many languages, so it should we weighted against that)
- Or alternatively, keeping the question _"Is this building completed?"_, but changing _"yes"_ answer to _"completed"_ ?

**Comment by stragu** [comment]
Thanks for looking into it some more! You're right, both those methods would clarify the task. But I'll let contributors to StreetComplete decide what is best depending on translation effort + consistency with other tasks :)

**Comment by westnordost** [comment]
Hm, I prefer to keep it as it is because I don't see a clear improvement for when changing the wording. The current wording is simpler and does not contain an implicit negative. In doubt it is always better to ask for the positive for clarity because anwering a negative question adds (brain) complexity.

In some languages, the proper answer options for a negative question are not "yes" and "no" but rather something like in the example above. I am not entirely sure how it is in English, but in German (literally translated here to serve as example) it is like this:

> _Ist das Gebäude **nicht** fertig?_
> 
> <kbd>_Doch!_</kbd> -> **Nein**, ich **widerspreche**, es **ist** fertig
> <kbd>_Nein_</kbd> -> **Genau**, das Gebäude ist **nicht** fertig

> Is the building **not** completed?
>
> <kbd>_But yes, it is!_</kbd> -> **No**, I **contradict** this, it **is** completed
> <kbd>_No_</kbd>  -> **True**, the building is **not** completed
