### ISSUE TITLE
Activate quest #2126 and #1827, deactivate another one in Portugal

### ISSUE THREAD

**Issue by laralem** [streetcomplete/StreetComplete#5695]
Please activate the following quests in Portugal:
- What number or code identifies this stop? (#2126)
- Does this gas station allow self-service? (#1827)

And disable the following quest:
- Can only glass bottles and jars be recycled here, or any type of glass? 
I'm not sure what this one's number is, it doesn't look like #223 as it describes several tags, may be https://github.com/streetcomplete/StreetComplete/blob/v56.0/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_glass/DetermineRecyclingGlass.kt#L29 . Just disable the one related to recycling:glass=yes.
In Portugal we should use "recycling:glass_bottles=yes" and "recycling:glass=**no**". Only very specific ones are used in relatively rare cases and isolated from other recycling points. The most common is recycling:light_bulbs and it's only available in stores, specially large ones.

**Comment by matkoniecz** [comment]
> In Portugal we should use "recycling:glass_bottles=yes" and "recycling:glass=no"

and this quest is asked for `recycling:glass=yes` and in typical answer translates it to `recycling:glass_bottles=yes`

Do you still think it should be disabled? If yes, why?

> Please activate the following quests in Portugal:
> Does this gas station allow self-service? (https://github.com/streetcomplete/StreetComplete/issues/1827)

Why? It seems to not happen that it is banned, see http://overpass-turbo.eu/s/1N4t

**Comment by westnordost** [comment]
For later reference, you should link to a source (legislation, street imagery, overpass, ...) for activating or deactivating a quest.

**Comment by laralem** [comment]
I apologize. I'll try to explain better.

1. Activate - What number or code identifies this stop? (#2126)
   - Recently, at least en Porto region I've seen new signage in bus stops. For example:
     - https://www.noticiasmaia.com/stcp-inicia-intervencao-nas-paragens-de-autocarro-no-concelho-da-maia/ (ref=AL7)
     - https://www.flickr.com/photos/115661165@N05/51554730811/ (ref=RTP2)
     - https://www.stcp.pt/pt/noticias/paragens-stcp-estao-a-ser-substituidas-na-maia/ (ref=MAI - 0433)
     - You can search for the stop code in https://www.stcp.pt/en/travel/stops/ (test only with `RTP2` or `AL7`, as the other example `MAI - 0433` is from another company).

2. ~~Activate - Does this gas station allow self-service? (#1827)~~ 
   - I apologize. Forget this proposal to activate. As far as I know, all of them in Portugal allow self-service but some have an employee who can fill the tank if you want. I got confused, what was needed was a quest to add the tag `full_service=yes` or `full_service=no` but that would be a proposal and this is not the right place/ticket for that.

3. Deactivate - Can only glass bottles and jars be recycled here, or any type of glass?
   - > and this quest is asked for `recycling:glass=yes` and in typical answer translates it to `recycling:glass_bottles=yes` Do you still think it should be disabled? If yes, why?
   - Maybe because someone who doesn't know could wrongly answer `recycling:glass=yes`? Only by reading the wiki documentation page in detail [which I recently corrected](https://wiki.openstreetmap.org/w/index.php?title=Pt%3ATag%3Aamenity%3Drecycling&type=revision&diff=2720577&oldid=2553071) will know that. It would be more appropriate to propose that the Portuguese community add the tags `recycling:glass=no` and `recycling:glass_bottles=yes` to all glass recycling containers (not centers), instead of asking questions on StreetComplete and having to answer the same question over and over again, in the hope that they won't get it wrong, I think. Many people don't know exactly what types of glass, including me, until I review the information about what you can actually leave in the glass recycling container, as well as the other types of containers.
   - In other words: Is there any place in Portugal that accepts any type of glass? No. There are ordinary containers where the label `recycling:glass_bottles=yes` should be applied, while other types of glass should go in the ordinary garbage can as indicated at https://recicla.pt/abc-da-reciclagem/5-coisas-que-nao-deve-colocar-no-ecoponto-verde/ There are exceptions, such as light bulbs (`recycling:light_bulbs`), which should be placed in the container found in stores that sell them and some hypermarkets. This ones are indoors. There is another exception: mirrors, and I believe also window glass, can be left at recycling centers (`recycling_type=centre`), which does not apply to this mission.
   - The "official recycling rules" can be found at https://www.pontoverde.pt/assets/images/Sinaletica_Comunicacao_Autocolante_A5_bold_HQ.pdf (Unfortunately only in Portuguese).
On one of the websites of the same organization (pontoverde / green dot) you'll find this page, which you can view in translation since the other is a PDF: https://recicla.pt/abc-da-reciclagem/estara-a-colocar-tudo-certinho-no-ecoponto-verde/ Unfortunately both sites are poorly organized, but they are from the only organization in Portugal responsible for the organization (but not the logistics) of the recycling system.

**Comment by matkoniecz** [comment]
> Maybe because someone who doesn't know could wrongly answer recycling:glass=yes? 

This would at most result in keeping  `recycling:glass=yes` as it is asked where `recycling:glass=yes` is present already.

> Only by reading the wiki documentation page in detail [which I recently corrected](https://wiki.openstreetmap.org/w/index.php?title=Pt%3ATag%3Aamenity%3Drecycling&type=revision&diff=2720577&oldid=2553071) will know that.

What is missing in the question info to make this distinction clear?

**Comment by mnalis** [comment]
> It would be more appropriate to propose that the Portuguese community add the tags recycling:glass=no and recycling:glass_bottles=yes to all glass recycling containers (not centers),

If that is indeed **always** case, yes, [mechanical edit](https://wiki.openstreetmap.org/wiki/Automated_edits) might be proposed to Portuguese community. If accepted, it would reduce number of offered StreetComplete quests to almost zero (_"almost"_ - because someone might add `recycling:glass=yes` afterwards in some other editor later, and then SC would ask the mapper to clarify it -- but that than would likely be _very small_ number of cases)

**Comment by westnordost** [comment]
> Recently, at least en Porto region I've seen new signage in bus stops.

Quests can only be activated country-wise. But we can activate it and review that decision later.
