### ISSUE TITLE
Fire enclosures can have a grate

### ISSUE THREAD

**Issue by Riksu9000** [streetcomplete/StreetComplete#5698]
In the quest about bbq fuel, there's a description indicating the difference between a bbq and a fire enclosure is whether it has a cooking surface. This is incorrect, as many fire pits have grates, and the openstreetmap wiki documents grate=yes/no as an additional tag to firepits.

https://github.com/streetcomplete/StreetComplete/blob/ad9fbc68c813e3222282fa4f9db8d82521f12f43/app/src/main/res/values/strings.xml#L1345
https://duckduckgo.com/?q=nuotiopaikka&iar=images&iax=images&ia=images

**Comment by westnordost** [comment]
> [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=[firepit](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfirepit) – Fire ring or fire pit - structure where you may have an [openfire](https://wiki.openstreetmap.org/wiki/Key:openfire)=*. Use it instead of [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=bbq if there is no [grill/grate/cooking surface](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dbbq#BBQ_without_grill/grate/cooking_surface) provided.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbbq

**Comment by Riksu9000** [comment]
I think it should be worded something along the lines of "a grill without a grate is classified as a firepit", without making a statement about whether fire pits have grates or not.

**Comment by mnalis** [comment]
>  "a grill without a grate is classified as a firepit"

Improvement to make text clearer would be welcome!

That particular  suggestion however sounds _**even more confusing**_ to me. If it doesn't have a grate (or other cooking surface), it's not a grill, so it makes no sense to be **talking about a grill** properties if it is **not a grill** at all?

IOW, it sounds like _"a building without walls is classified as a xxxxx"_ or _"a bird without wings is yyyyy"_ -- well, if there are no walls, it is not a building, and if it doesn't have wings, it's hardly a bird.

So some rewording might help. Also, I remember there was a need to specifically mention other non-grate cooking surfaces in community discussion linked in https://github.com/streetcomplete/StreetComplete/pull/5371  (IIRC, in Australia most grills (which they call "BBQs") do not have a grill/grate (but flat metal cooking surface), and there were others examples too?)

Perhaps after reading up on that thread one might come up with better description which still covers all use cases but is less confusing?

**Comment by Riksu9000** [comment]
Thanks for  the tips. I've come up with two more suggestions.
"Grills must have a cooking surface, as opposed to fire enclosures."
"If there is no cooking surface, it's a fire enclosure."
What do you think?

**Comment by westnordost** [comment]
The dialog currently goes like this:

\> What is this grill powered by?

\< Uh...
\< It's a fire enclosure

\> Are you sure?
\> Fire enclosures don’t have a cooking surface (e.g. grate/plate), as opposed to grills.

\> [Yes, I am sure] [I will check]

---

So, I think your second suggestion will do fine:
"If there is no cooking surface (e.g. grate/plate), it’s a fire enclosure."

**Comment by Riksu9000** [comment]
Thanks!
