### ISSUE TITLE
Requesting Signed Route option for bike paths

### ISSUE THREAD

**Issue by Coehill** [streetcomplete/StreetComplete#5707]
**Use case**
My town has numerous signed routes for bicycling which consist of a green sign containing "🚲 Route". These offer the best routes in areas that do not yet have proper bike infrastructure.

**Proposed Solution**
Add an option for "Signed bicycle route" from the "bike paths" menu. It should be a colour closer to red since it is poor bicycle infrastructure, like sharrows, yet still preferable to no infrastructure.

**Comment by matkoniecz** [comment]
Mapping bicycle routes in StreetComplete is not possible right now and not planned, so showing them in editor is not a good idea.

If mapping bicycle routes is somehow doable in this or separate overlay (very unlikely to be a good idea) separate issue for it should be created.

**Comment by Coehill** [comment]
@matkoniecz Routes can be mapped by the lcn=yes tag.  Relations for larger, overarching routes are mapped differently.  I propose that if the road has no lcn=yes tag, and no bicycle route relation, then we can add the lcn=yes tag.
