### ISSUE TITLE
New Quest: Is this bike parking permanent?

### ISSUE THREAD

**Issue by Coehill** [streetcomplete/StreetComplete#5708]
There is often bike parking that is a temporary stand which is placed outside a shop. It is important for the user to know this because a) it offers reduced security and b) it may only be available seasonally.

**Comment by matkoniecz** [comment]
1) how user would know whether stand is present seasonally?

2) please use quest template (third from top in https://github.com/streetcomplete/StreetComplete/issues/new/choose )

**Comment by Helium314** [comment]
> how user would know whether stand is present seasonally?

To be fair: this question is already asked for grit bins, so users are somehow expected to know (and for a shop you can at least go inside and ask).

**Comment by Coehill** [comment]
In addition to @Helium314's comment, temporary stands are not bolted into the ground. They may or may not be seasonal, but either way, they are easily removable.

**Comment by Coehill** [comment]
> 1. how user would know whether stand is present seasonally?
> 
>     2. please use quest template (third from top in https://github.com/streetcomplete/StreetComplete/issues/new/choose )

I noticed that you closed this issue. Did you want me to open a new issue with thst template?

**Comment by matkoniecz** [comment]
yes, if it fulfils requirements stated there

**Comment by matkoniecz** [comment]
(at least in Poland number of temporary bicycle parkings mapped in OSM is vanishingly small, but maybe it is different elsewhere)
