### ISSUE TITLE
What kind of water is this?

### ISSUE THREAD

**Issue by burrscurr** [streetcomplete/StreetComplete#5709]
This was also suggested in #3542, but the person that created the issue deemed it not necessary anymore and closed the issue. Personally, I think this quest would be a great new quest for SC. Let me elaborate:

### General
Affected tag(s) to be modified/added: [`water`](https://wiki.openstreetmap.org/wiki/Key:water)
Question asked: **What kind of whater is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose (`natural=water` can be a pond/lake/reservoir/basin/fountain/ditch/canal/wastewater/... The `water` tag helps to characterize the water more precisely and is widely used since >10 years)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (see section below)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary (distinguishing the different sub-types can sometimes be tricky, but finding a fitting and reasonable answer shouldn't be too difficult in the vast majority of cases)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (depends on the area, in a rural context, specific types like `water=pond` may be very common)
- [x] 🕓 Applies to a reasonable number of map data (yes, see https://overpass-turbo.eu/s/1Nme)

Overall, this quest seems structurally similar to the building type quest:
 - specific tag values may be dominat, depending on the area (`building=residential` vs. `natural=pond`)
 - large number of sub-types
 - there are specific sub-types, but some real-world examples don't fit perfectly and  may reasonably be characterized as one sub type or another (--> selection of meaningful, distinct types that are suggested to the user is very important)

### Ideas for implementation

**Element selection:**  ways with `natural=water` without `water` or `amenity=fountain`

**Metadata needed:** There may be very specific types of subtypes in some countries, but I'm not sure whether they would be common enough to include in a country-specific set of options. Probably not necessary.

**Proposed UI:** Maybe similar to building type quest, grouping similar values together

### Types of water

Here are the different types of water I could identify from looking at applicable elements and researching the wiki/taginfo for established tagging.

**Natural**

 - `water=lake` (important to convey that this is a natural body of water, not a  category based on size)
 - `water=river` (surprisingly, I found some examples of river areas without this tag, but overall it is rare)
 - `water=oxbow` (a former part of a river bend, now disconnected from the main stream; could be tricky to identify, but probably rare anyway)
 - ~`water=lagoon`~ (probably limited to specific geographic areas, and unlikely to encounter on foot; may not be worth including)

**Man-made**

 - `water=pond`
 - `water=reservoir` (maybe be tricky to distinguish from a large lake without additional information (e.g. lakes/reservoirs in Sweden/Norway))
 - `water=basin` (may be difficult to distinguish from a pond; its function for storing water (temporary) should become clear from the image)

**transportation**

 - `water=canal`
 - `water=harbour`
 - `water=lock` (may be too rare)

**in urban environments**

 - `amenity=fountain` (There is `water=fountain` as well, but the `amenity=fountain` tagging seems to be more common. There are also some mappers who prefer to tag `amenity=fountain` as a node in the middle of the water area ([example](https://www.openstreetmap.org/node/268084311)))
 - `water=ditch` (common in parks)
 - `water=reflecting_pool` (shallow, still water area)

**something else**
 - `water=moat` (around castles, may also fit well with moats common in zoos)
 - ~`water=wastewater`~ (quite easy to map from aerial imagery, therefore probably not worth including)

#### Gaps/what's missing?

Overall, I feel like those types listed above capture the range of different bodies of water quite well. There are some gaps, however, where established tagging is missing or seems like a stretch:

 - small natural water areas embedded into swamps/marshlands ([example](https://www.openstreetmap.org/way/941912050#map=16/51.0347/11.0243), though this is in a (disused?) quarry, the point should come across). Kinda like a lake, but less "defined", maybe more like an `water=oxbow` in appearance, though not necessarily in origin
 - small artificial/decorative water elements in urban areas that aren't fountains, but also not quite ponds ([example](https://www.mapillary.com/app/?lat=51.034120552086&lng=13.785289966846&z=17&pKey=763980117648477&focus=photo&x=0.2438275184942783&y=0.545289313986234&zoom=0))
 - excavation lake (came across quite a lot of those, unclear which tagging would be appropriate, if duck-typing is applied `water=lake` fits reasonably well)

**Comment by matkoniecz** [comment]
> Any answer the user can give must have an equivalent tagging (see section below)

Important thing to check: are known, accepted and documented values of `water` covering all and every single valid `natural=water`?

Given last section it seems to be potentially a problem.

**Comment by burrscurr** [comment]
I did some more research:

Wiki defines [`water=lake`](https://wiki.openstreetmap.org/wiki/Tag:water%3Dlake) as

> a natural or semi-natural body of relatively still fresh or salt water, localized in a basin that is surrounded by land

which clearly fits the "small natural water areas embedded into swamps/marshlands" category mentioned in my initial description. I'd also say that quarry lakes / lakes in quarries are `water=lakes`, since they are at least semi-natural (e.g. due to ground water or preciptiation), are localized in a basin (even if its of artificial origin). (I also found [a discussion](https://community.openstreetmap.org/t/baggersee-und-landuse-quarry/9397/4) (german) suggesting `water=lake` and perhaps additional sub-tags.)

Regarding different types of urban artificial or decorative water bodies: If this is no well-defined specific type of water body, I don't think it makes much sense to search for a tag. Thats where I see parallels to the `building=` key: There are distinct archetypes of buildings, but also many real-world buildings that combine the characteristics of multiple building types and are hard to characterize. For instance, there are a variety of small residential buildings that neither fit `building=detached` and `building=apartments` perfectly, and could be reasonably described as either one of those, since they combine characteristics of both. (Which is fine, I think, as long as this mixed building type is not a specific thing that can be clearly distinguished.) In the `water` world, I'd say that still water can be characterized as `water=pond`, and if it is entirely surrounded by artificial material it's `water=basin`, and if there is moving water, maybe `natural=water` + `amenity=fountain` fits best.

**Comment by mnalis** [comment]
> Regarding different types of urban artificial or decorative water bodies: If this is no well-defined specific type of water body, I don't think it makes much sense to search for a tag

One StreetComplete [Quest guideline](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) to be specially aware here is _"🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that **any answer** given by the user **must result in something being tagged**"_ (emphasis mine). So there should be a tag available matching every water body (it might be more or less precise, or course, but it should exist and be clear to the user which one to use)

I've updated the [overpass](https://overpass-turbo.eu/s/1Nq9) to skip those which should not be tagged, and immediately found few problematic cases e.g. [w851426135](https://www.openstreetmap.org/way/851426135) or [w699356950](https://www.openstreetmap.org/way/699356950). E.g. decorative water places seem ill-described with [water=basin](https://wiki.openstreetmap.org/wiki/Tag:water%3Dbasin). Tagging them as `natural=water` + `amenity=fountain` is also problematic, as there often might fountain mapped nearby, so that would be claiming multiple fountains where there is only one. One might perhaps turn them  info [multipolygon relation](https://wiki.openstreetmap.org/wiki/Multipolygon) in cases where they might be considered part of fountain proper; but such solution of course is not well-suited for SC.

---

As for the quest element selection, it should skip not only elements with `amenity=fountain` or `water=*` but also `waterway=*.`

**Comment by matkoniecz** [comment]
> So there should be a tag available matching every water body

though note that option "leave note" is also OK if it applies for tiny part of objects eligible for quest

still, there should be no case where user leaves note and it is being closed with "then we should add no tag" and quest returns, this or another user leaves note...

**Comment by westnordost** [comment]
I find this is not eligible as a quest because what water body exactly it is is somewhat difficult to verify: Is it a river or rather a canal? Is it a pond or rather a basin?
If you are in front of an oxbow, you might think it is a river. Only on satellite imagery, you'll see that it is indeed an oxbow.
In any case, it appears to me that most of this should be easier to answer with aerial imagery, i.e. with a desktop editor.

**Comment by burrscurr** [comment]
Hmm thats true. At least for some kinds of water (like oxbows). For other types (lake or pond; river or canal) there is at least some uncertainty when mapping from aerial imagery, too. I cannot judge what kind of level of "a user may make an error when answering the quest" would be tolerable, if there is no path for adding this quest feel free to close this issue.

**Comment by westnordost** [comment]
Well, this is one of those suggestions where it is not completely clear whether it suffices the quest guidelines or not. But, I lean towards that it is not worth it. Maybe it could also be added to SCEE first and see how it goes, i.e. if it would be fine or not.

An additional point (that also applies to the orchard produce quest, which is disabled by default now, IIRC) is that these areas can be quite large and the user neither has the possibility to split these areas up nor really should be expected to check the whole (possibly very large) area displayed to solve just one quest.

So, yeah, I'd rather close this now, but I think it could be added to SCEE and if the issues I am worried about don't really surface, it could maybe be transplanted to StreetComplete after all.
