### ISSUE TITLE
Make description of defibrillator location language-specific

### ISSUE THREAD

**Issue by daPhipz** [streetcomplete/StreetComplete#5710]
**Use case**

When asked where a defibrillator is located, there is no indication in which language the text should be written. Should it be the user's mother tongue, the local language, or English?

**Proposed Solution**

Either (my preferred scenario) ask the user to provide the description in English and/or their mother tongue (I don't know if `defibrillator:location:de=` is possible).
Alternatively, specify in what language the description should be in.

Also, maybe add a check quest if the location is still valid, it may have changed after some time or the original description might be of poor quality if it didn't come from a native speaker.

**Comment by westnordost** [comment]
`defibrillator:location:de` is certainly possible to tag, the issue is that the app does not know in which language the user will write. So, better add a hint that one should use the local language or otherwise English.

The existence of defibrillators are already checked again regularly.
