### ISSUE TITLE
Kerb quests are not asked for connection of two crossings and one sidewalk

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5717]
I'm not sure there's a great way to resolve this issue, because I think the difficulty stems from differing mapping styles. Please reference issue #2654. The mapper of those crossing ways extends them up the kerb ramp to the sidewalk and maps the kerb node as a node on the crossing way. In contrast, I map the sidewalk to the point where the kerb ramp (concrete usually) meets the roadway (asphalt). So there are little stubs of sidewalk reaching out towards the road.

Sometimes, the ends of some crosswalks meet at a single kerb ramp at a corner: 
![image](https://github.com/streetcomplete/StreetComplete/assets/7786285/94f3bd63-bb03-41ca-b717-e4138b8a4d50)

In this instance, two crossing ways and one sidewalk meet at one node, and I don't think there's a different way to map it. But StreetComplete doesn't ask about kerbs here because of the previous issue removing that check.

**Versions affected**
v57.1

**Comment by matkoniecz** [comment]
it is impossible to catch all cases and SC prefers false negatives to false positives, #2654 forced SC to stop asking in such cases

in theory more elaborate checks could be added but it has complexity and performance costs

**Comment by pkoby** [comment]
It looks like tagging those nodes with `barrier=kerb` and nothing else triggers the quests for height and tactile paving, so that might be a good strategy to add to my mapping for this case. It makes perfect sense to avoid false positives.

**Comment by matkoniecz** [comment]
yes, with explicit `barrier=kerb` sc does not need to guess and be careful

I think I will close this, unless someone has idea how to detect these reliably without murdering performance or false positives
