### ISSUE TITLE
Wrong changeset comment with wrong edit

### ISSUE THREAD

**Issue by maro-21** [streetcomplete/StreetComplete#5718]
In these changesets a user changed correct `highway=path` to `highway=road`. With the changeset comment that they're checking construction. There was no construction.

https://overpass-api.de/achavi/?changeset=153420054
https://overpass-api.de/achavi/?changeset=153428241

**Comment by Helium314** [comment]
The changeset was done with [SCEE](https://github.com/Helium314/SCEE), not with StreetComplete. The user apparently changed the element filter is an unsuitable way, which broke the quest. Please tell the user.

**Comment by matkoniecz** [comment]
standard cs links:

https://www.openstreetmap.org/changeset/153420054

https://www.openstreetmap.org/changeset/153428241
