### ISSUE TITLE
Change the image for `parking=surface` to improve differentiation

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#5721]
**Use case**
I see some times that street-side parking is entered as `parking=surface`, especially by beginners. I would therefore like to suggest replacing the image for `parking=surface`.
[Here](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/drawable-xxhdpi/parking_type_surface.jpg) is the current image for reference.
The current picture only shows four cars, which in my opinion does not quite fulfill the purpose. It doesn't have to be, but often a `parking=surface` has an access road which is not visible in the picture. Osmose also offers an "error" if a `parking=surface` has no access road.

**Proposed Solution**
I would like to suggest showing a picture here that shows more cars, at least one access road and the typical parking lanes. Here are four ideas:
* * https://commons.wikimedia.org/wiki/File:IKEA_Glasgow_car_park_-_geograph.org.uk_-_5092604.jpg
* https://commons.wikimedia.org/wiki/File:Meir_Park,_Tesco_car_park_-_geograph.org.uk_-_4520519.jpg
* https://commons.wikimedia.org/wiki/File:Central_Car_Park,_Salisbury_-_geograph.org.uk_-_2610108.jpg
* https://commons.wikimedia.org/wiki/File:Car_park_-_West_Quay_retail_park_-_geograph.org.uk_-_5512766.jpg

What do you think?

**Comment by matkoniecz** [comment]
image was changed in https://github.com/streetcomplete/StreetComplete/commit/820565241f132ee9f0864b0b712d7b004e0728d7

have you seen #2897 ? (it is linked from there, I have not yet read it but was given as justification)

**Comment by matkoniecz** [comment]
see also  #3421

**Comment by matkoniecz** [comment]
SC and wiki are in a bit different contexts, but if image is better also for wiki it can be changed also there

for SC it is more important than options shown in app are clearly distinct and highlight difference between each other without giving false hints, for OSM Wiki it is more important to have typical example of a given type, especially at specific tag page

**Comment by matkoniecz** [comment]
it was reopened with question about wiki, I answered and closed as improvements/fixes on OSM Wiki are out of scope for this issue tracker (though welcome and useful!)

**Comment by FloEdelmann** [comment]
But still, for this repo, this issue should be closed as "not planned", not closed as "completed".
