### ISSUE TITLE
Shows a missing cycleway on one side if the other side has any cycleway information

### ISSUE THREAD

**Issue by Langlaeufer** [streetcomplete/StreetComplete#5722]
Visualization in Cycleway-Overlay

 bicycle_road=yes 
 oneway=yes 
 oneway:bicycle=no

yellow dashed line with red right border and black dashed left border.

![image](https://github.com/streetcomplete/StreetComplete/assets/15994341/ebe264d9-016d-4670-a13b-c68b547dcfa0)
https://www.openstreetmap.org/way/7979092

**Expected Behavior**
should not be red bordered because there is no cycleway-tag missing on a bicycle_road

**Versions affected**
SCEE 58.1

**Comment by westnordost** [comment]
This is not a bug.

There is no `cycleway` tag on the way linked, therefore it is shown that this information is missing. It is physically possible for bicycle roads to have cycleways, e.g. if the physical cycleway has not been removed after a road has been designated as a bicycle road. (The designation just requires a sign, while the removal of a possible prior cycleway requires re-construction of the road, hence it probably that both don't happen at the same time).

**Comment by westnordost** [comment]
I do wonder, though, why Alleestraße has nothing highlighted, though?

**Comment by Langlaeufer** [comment]
Because bicicle roads typicaly don't have cycleways and your software also dooes not  allow to tag a cycleway on a bicycle road

**Comment by Langlaeufer** [comment]
BTW: Wenn du möchtest dass SC betreffende Dinge hier und nicht in der SC Community diskutiert werden, solltest du meiner Meinung nach etwas Diskussion abwarten bevor Fehlermeldungen  geschlossen werden.

**Comment by westnordost** [comment]
Chill, man. I closed the issue because you posted it as a bug. I tend to treat bug reports that are not bugs like answered questions - I close them. You can also post enhancement requests.

Anyway, good point. I forgot that there is already some filtering done that conditionally does not show a missing `cycleway` in red but as transparent instead. I would be consistent to extend that to bicycle roads.

**Comment by westnordost** [comment]
Hmm, actually, `bicycle_road`s are already in that filter. The reason why it is highlighted anyway is that if a road has any information that is displayed for one side (i.e. in this case - "none but contraflow allowed"), then the other side is always shown as red when there is no information.

Not sure why I implemented it like that, though. Maybe that could be dropped.

**Comment by westnordost** [comment]
Contemplating it, I think this should be dropped and whether a missing `cycleway` should be shown in red should be decided individually per-side, also in light of #5716
