### ISSUE TITLE
Unable to reach authorization server when trying to login

### ISSUE THREAD

**Issue by radmorecameron** [streetcomplete/StreetComplete#5723]
**How to Reproduce**
- login to app with email and password (im a new user that hadnt authorized this app before)
- click authorize
![Screenshot_20240706-002811](https://github.com/streetcomplete/StreetComplete/assets/55817894/9e427bf6-6899-45db-8069-730da4cada37)

- get toast message that says "Unable to reach authorization server"
![Screenshot_20240706-002901](https://github.com/streetcomplete/StreetComplete/assets/55817894/0bdade38-3290-4c17-900b-3fa4ff89373b)

**Expected Behavior**
App logs in

**Versions affected**
58.1

**Comment by matkoniecz** [comment]
Can you login at https://www.openstreetmap.org/ from your phone?

**Comment by westnordost** [comment]
Let's find the cause for this. 

Could you please try logging in again, after failure immediately go back, then go to **Menu -> About -> Show logs**. The error should be logged there. You can reduce the number of shown logs by filtering by "Login".

**Comment by westnordost** [comment]
Hm, there is not more? I would have expected that the reason is printed, too. Maybe in the next line?

Basically, this error is thrown when the authorization API did not return a valid response, i.e. "probably some temporary server problem we cannot do anything about anyway". In this case, more specifically, the returned authorization URL is not in the format as expected.

Now, I can login, I just checked.

So, for some reason in your case, the authorization URL does NOT include the authorization code in your case but ALSO does not contain an error description.

Two more things that may help track down where this is coming from:
- Do you login through a third party, like Google?
- What happens if you click on "Deny"?

**Comment by westnordost** [comment]
Hmm... that's weird. How can it be that only you are affected, and others, like I, can login normally?

Can you try another app, e.g. Vespucci? Can you login normally there? They should use the same login mechanism. What's your username on OSM?

**Comment by westnordost** [comment]
Oh, that's a good lead! Maybe in the callback URL it is not properly encoded? I will check that.

**Comment by mnalis** [comment]
> Oh, that's a good lead! Maybe in the callback URL it is not properly encoded? I will check that.

FYI my OSM username used for SC also has space in the middle (`mnalis ALTernative`), and I seem to be able to login / logout normally in SC 58.1 (as I was able in previous versions too). Just tried now (Android 14)

**Comment by westnordost** [comment]
Hm, okay, so I guess this lead is a dead end. But just to confirm, you could try to change your name on OSM to not include a space (and after testing, change it back, IIRC changing the display name is possible just like that).

That according to the osm website the access token has been dispensed is to be expected. This should happen for StreetComplete, too.

**Comment by westnordost** [comment]
@radmorecameron I created a special version of v58.1 that properly logs the error message that includes the (apparently faulty) authorization URI. 

Could you install this APK and check the logs screen after failing to log in again?

https://www.westnordost.de/misc/StreetComplete-v58.1-logintest.apk

If you installed the App from Google play, it will just install over it. If you installed the app from F-Droid, you'd have to remove it first (it has a different signature).

**_Important_**: The log message contains in one form or another your access token generated for StreetComplete. Before posting it here, you should revoke access for it in your settings on the openstreetmap website!

Android usually does not allow you to install apps from sources other than Google Play, but there is some option in the setting to allow it (once).

**Comment by westnordost** [comment]
Oh, hmm. So then, it looks like, it was really a server-side problem that now has been resolved somehow.

Thanks for testing!

**Comment by RubenKelevra** [comment]
@westnordost someone reported having the same issue on Mastodon today:

https://pouet.chapril.org/@zekounet/112790429884941290

**Comment by openbrian** [comment]
I also had this issue.  Unlike others, no space in userne, but like others username had capitals.  I upgraded from 55.1 to 58.2 and this resolved the issue.  V55.1 does have the ability to show logs, so I could not capture them.

**Comment by westnordost** [comment]
Last month there was some DDOS attack on OpenStreetMap, causing the server to respond with some unexpected error codes, partly for example with "HTTP 403 Forbidden", causing StreetComplete to think that the user's access token was revoked (-> logged out automatically).

**Comment by mnalis** [comment]
(ref: https://github.com/streetcomplete/StreetComplete/issues/5724#issuecomment-2223211328 and below, https://github.com/streetcomplete/StreetComplete/issues/5773)
