### ISSUE TITLE
No "What can be left here for recycling?" for recycling containers mapped as way

### ISSUE THREAD

**Issue by fxedel** [streetcomplete/StreetComplete#5735]
An `amenity=recycling` with [`recycling_type=container`](https://wiki.openstreetmap.org/wiki/Tag:recycling_type%3Dcontainer) may be mapped as a single node or as an area. While nodes are [way more common](https://taginfo.openstreetmap.org/tags/recycling_type=container#overview) (373 388) than ways/areas (10 977), there is definitely a good reason to map larger recycling container areas as an area, for example this one, which consists of 23 individual containers:

![IMG_20240710_191819](https://github.com/streetcomplete/StreetComplete/assets/7782229/7401dbfd-efaa-4d26-9e6d-43003105e6d6)

The corresponding OSM way is: https://www.openstreetmap.org/way/1276097081

Of course, also areas should be enriched with the `recycling:*` tags to specify what can be recycled there.

**How to Reproduce**
Go to an recycling container area (any overlay is fine), no quest arises.

**Expected Behavior**
Quest "What can be left here for recycling?" should arise.

**Versions affected**
v58.2

Note: If I understand PR #4936 correctly, this already works for the glass recycling quest. The fix for all recycling containers could be similar.

**Comment by westnordost** [comment]
Are you sure that it is not asked for recycling areas? Looking at the code, it certainly should. See #4907

**Comment by mnalis** [comment]
Agree with the premise that it should be asked on a ways too, and it seems to me that it is asked on other ways, as cursory look at the code would suggest it should do:

https://github.com/streetcomplete/StreetComplete/blob/8636a3b62f5d464cc87cb98899bc9b403e7cbaef/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt#L18-L25

however I can confirm (in 58.1) that that it is **not** being asked on that specific [way 1276097081](https://www.openstreetmap.org/way/1276097081) for some reason.

**Comment by mnalis** [comment]
playing in SCEE, Quest is also not shown on [way 1276097081](https://www.openstreetmap.org/way/1276097081), but if I edit that node to add any unrelated tag (like `level=0`), suddenly the quest pops up! Could be it related to node timestamp? There is this override which perhaps might influence it? :

https://github.com/streetcomplete/StreetComplete/blob/8636a3b62f5d464cc87cb98899bc9b403e7cbaef/app/src/main/java/de/westnordost/streetcomplete/quests/recycling_material/AddRecyclingContainerMaterials.kt#L38-L45

**Comment by westnordost** [comment]
Oh, I see the mistake. It's in line 36.

**Comment by fxedel** [comment]
Thanks for the quick fix @westnordost! :heart:
