### ISSUE TITLE
No way to enter level data for houses/apartments etc

### ISSUE THREAD

**Issue by mattwelke** [streetcomplete/StreetComplete#5738]
I used to be able to enter in level data for buildings. This was a few years ago. I was using quests at the time, not the overlay feature, because it hadn't been released yet. I would occasionally be prompted with a quest to enter the level data in, at least for apartment buildings. I don't recall the quest appearing for other building types.

Now, I notice that I am never prompted with a quest to enter in levels info for buildings that don't have it, even apartments with other info except levels. And if I switch to the buildings overlay, I can't find a way to enter the data that way either.

For some context, the reason this is important to me is because I'm volunteering with a local political party and having data about where apartment buildings with many people living in them helps us use our canvassing time most effectively. So I'm trying to map the apartment buildings in my area including level data. StreetComplete is my preferred way to enter in this data in the go, so it would be useful for me to be able to enter this data in via StreetComplete.

**How to Reproduce**
1. Load data for quests where some buildings lack level data, note the lack of level quests, or
2. Switch to the building overlay and pull up a building, note the lack of level data in the UI or how to input it

**Expected Behavior**
1. Quests for levels appear on buildings without it, and
2. In the building overlay, there is a way to enter in level data

**Versions affected**
Android 14
StreetComplete 58.2

**Comment by mattwelke** [comment]
Actually, I somehow had these two quests disabled:

![Screenshot_20240711_004211_StreetComplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/7719209/3f27e497-b8e7-4032-8bd1-5a457efd45f6)

I'm pretty this will fix my problem. Even though there isn't a way to enter this type of data in using the building overlay, I should be able to now see quests asking me what type buildings are, and I'm guessing that once I enter in house, apartment, etc, I'll then see a quest asking me how many levels it has.

I can leave this open for now and report back later after my next survey.

**Comment by matkoniecz** [comment]
Yes, these quests have become  disabled by default at some point. 

Enabling these types will enable relevant quests
