### ISSUE TITLE
androidTest quests.oneway_suspects has unresolved reference to data

### ISSUE THREAD

**Issue by kmpoppe** [streetcomplete/StreetComplete#5743]
In AndroidStudio Koala (2024.1.1), with a fresh clone of the SC repo, there's an unresolved reference to `data` in

https://github.com/streetcomplete/StreetComplete/blob/406bc57d693de364b47e7414fe3cf906d5402ab4/app/src/androidTest/java/de/westnordost/streetcomplete/quests/oneway_suspects/WayTrafficFlowDaoTest.kt#L6

which makes the test project fail to build (the main app build fine).

Am I missing a package reference or something?

**Comment by matkoniecz** [comment]
AFAIK this quest was removed - apparently not fully

**Comment by mnalis** [comment]
- ref. https://github.com/streetcomplete/StreetComplete/pull/5725
