### ISSUE TITLE
For buildings with parts, renders entire outline of building instead of just building parts

### ISSUE THREAD

**Issue by mattwelke** [streetcomplete/StreetComplete#5747]
According to [Simple 3D Buildings](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings), when you map out the individual parts of a building with `building:part=*`, you should still include a building outline where the tags representing info about the entire building are placed.

There are multiple apartment buildings in my area where they appear to have been mapped correctly according to these instructions, but they are not rendered correctly in StreetComplete.

Here's an [example](https://www.openstreetmap.org/way/34777153). Note how it appears as if it were one building with a uniform height/number of levels.

![image](https://github.com/user-attachments/assets/0d66b8ef-e83d-43c7-a35f-2d0e72ba138e)

This is despite the fact that the individual building parts have different height levels tagged.

![image](https://github.com/user-attachments/assets/05eb67da-a1ca-435d-9c40-3b4d46dc0bfc)

![image](https://github.com/user-attachments/assets/6dcc8c07-5a6a-4942-a21f-cd007c84bc22)

This pattern continues as you inspect the building parts along the building until the end of the building which is 17 levels.

![image](https://github.com/user-attachments/assets/da0d4358-06c2-4021-a29a-354b7b2db554)

The building outline is mapped and tagged correctly (based on how I interpret the OSM wiki page) as an area that surrounds each of these building parts with levels set to 17.

![image](https://github.com/user-attachments/assets/068af3e1-585b-4c2a-bfcd-0424acd33b15)

I believe this is why StreetComplete renders it as one monolithic building. It appears to be including the building outline in how it renders. That would explain why the entire monolithic rendering is 17 levels in this example. That's the tag on the apartment building area.

I don't think this issue seriously impedes using StreetComplete. For example, I'm still able to complete quests. This is just how the map looks. Where it does slightly impede me completing quests is when I'm looking at the map for an area I'm new to and I don't recognize what I'm seeing on the map until I realize how the buildings around me might be rendered by it. Once I get situated, it's easier to continue completing quests. It would be nicer though if the map reflected the buildings I'm walking near while I survey.

**How to Reproduce**
See above

**Expected Behavior**
See above

**Versions affected**
Android: 14
StreetComplete: v58.2

**Comment by westnordost** [comment]
Not a bug but a missing feature in both the rendering library (tangram-es) we use and in the source data (jawgMaps) we use.

Neither tangram-es nor MapLibre-native (the lib we are migrating to) supports roof shapes. JawgMaps does either not have `building:part`s in their data or it is not correctly processed (i.e. the building height of a building outline should be set to undefined when the building is completely covered in building:parts) - see also https://www.jawg.io/docs/apidocs/maps/streets-v2/#building
