### ISSUE TITLE
recycling bin quest miss "Restmüll" (non-recyclable waste)

### ISSUE THREAD

**Issue by Mannshoch** [streetcomplete/StreetComplete#5753]
**How to Reproduce**
We have public bin which allow to recycle Aluminum, PET, Paper, and what is missing "non-recyclable waste"
if you click on such a Bin icon you couöd not setup all possibility.

**Expected Behavior**
One additional icon for "non-recyclable waste"

**Versions affected**
58.2

**Comment by riQQ** [comment]
Recent discussion in #5736

**Comment by westnordost** [comment]
Non-recycleable waste is not recycleable. Tagging it with `amenity=recycling` is a mistake. 

If you come upon such a container, you can correct this tagging mistake by answering "Uh..." -> "It's for general waste". It will be re-tagged to `amenity=waste_disposal`.

**Comment by westnordost** [comment]
And in case the waste disposal is grouped with other - recycling - containers, as far as I know, the only correct solution according to the documentation is to add a new node for the general waste container next to the recycling container element. This can not be done in StreetComplete, so in case there is recycling + general waste, a note needs to be created.

**Comment by westnordost** [comment]
I noticed that the quest only highlights nearby `amenity=recycling`, not nearby `amenity=waste_disposal`. Maybe it should highlight the latter, too?

**Comment by Mannshoch** [comment]
In Switzerland you find this recycling bin:
https://igora.ch/index.php?rex_img_type=download-web&rex_img_file=recycling-station_1.jpg 
on every trains station several times. It's their standard bin.
As you see the left bin is for non-recyclable waste. Such Bins also exist in several other country.

I do not like the idea to have a second node. Is it possible to somehow change the documentation? May the rule could be that 'waste_disposal' is only allowed on a recycling node if at least one recycling possibility is on the same location.

It's my personal opinion, but I think a recycling node it self is wrong. Every recycling is also a waste disposal. A waste disposal should have an additional recycling value.

**Comment by matkoniecz** [comment]
> This can not be done in StreetComplete, so in case there is recycling + general waste, a note needs to be created.

things overlay should enable this, right

> I do not like the idea to have a second node. Is it possible to somehow change the documentation? 

Yes, but StreetComplete does not control OSM tagging. You can login with OSM account and discuss at https://community.openstreetmap.org/c/general/tagging/70 what is the preferred method of mapping this (note: I would advise to avoid arguments in form "it would be easier for StreetComplete if...")

**Comment by matkoniecz** [comment]
So I will close this issue, once documentation is changed (with consensus of community or at least without opposition) then it can be reopened or new one opened.

**Comment by westnordost** [comment]
Yeah, same in Germany. But I wouldn't map these as recycling containers. They are rather just bins, I'd say.

Recycling containers are places you actively carry your recycleable waste - paper, glass, ... to. You wouldn't go to a train station, mall, etc. to do that only because their bins separate waste.

So at least IMO, using amenity=recycling is also wrong for these bins.

**Comment by Mannshoch** [comment]
https://community.openstreetmap.org/t/is-amenity-waste-basket-recycling-good-for-tagging-combined-garbage-recycling-bins/101616/40

**Comment by mnalis** [comment]
>> only correct solution according to the documentation is to add a new node for the general waste container next to the recycling container element. This can not be done in StreetComplete, so in case there is recycling + general waste, a note needs to be created.

> things overlay should enable this, right

I can (in StreetComplete v58.2 Things Overlay)  choose `Garbage Dumpster`, which gets tagged as `amenity=waste_disposal`, so that _correct solution_ mentioned above should be **_possible right now_** IMHO; yet I am reading both those comments as indicator that you think this is not (yet) possible? Misunderstanding or?

> I noticed that the quest only highlights nearby amenity=recycling, not nearby amenity=waste_disposal. Maybe it should highlight the latter, too?

I think it would be useful...

**Comment by matkoniecz** [comment]
Often yeah cans would fit well and better than garbage dumpsters

**Comment by matkoniecz** [comment]
And yes, both can be added with things overlay.
