### ISSUE TITLE
Mixed use building typed

### ISSUE THREAD

**Issue by bradbeattie** [streetcomplete/StreetComplete#5755]
Building type enquiry allows me to select commercial, but asks if it's retail or office. Well, in some cases it's both! https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element#Situations_where_multiple_elements_may_be_needed says mixed use buildings should be designated `building=*`, but the StreetComplete UI has no concept of that.

**Comment by FloEdelmann** [comment]
Note that `building=*` in the wiki is just a placeholder for "any value". I'd say in this case, `commercial` is perfectly fine (it's a supercategory of retail and office), so you can select that and complete the quest.

**Comment by mnalis** [comment]
Related SC [FAQ: Building Type Quest - Why don't I see the right types?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?)

StreetComplete _"Building Quest"_ (as opposed to _"Building Overlay"_ - it is unclear which one you used) under `Uh...` menu at the bottom has option `It has multiple purposes` which, when clicked, explains ***"Simply select the main purpose of this building. E.g. if there is a shop on the ground floor with apartments above it, it is still  mainly an apartment building"***.

Also, if such information is very important for your use case, there is also an option in StreetComplete to `Leave Note` (with text and pictures), and then you later manually appropriate create appropriate [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)  in full-fledged desktop editor like iD/JOSM. But vast majority people won't care that much about building types.
