### ISSUE TITLE
add operator:signed=no option to "Add operator for old clothes container quest"

### ISSUE THREAD

**Issue by wurzel-3** [streetcomplete/StreetComplete#5764]
**Use case**

 I encountered some containers which where not signed, which generated a lot of notices from unexperienced Streetcomplete users when encountering this situation without this option 

**Proposed Solution**

Add an operator:signed=no option to the  "Add operator for old clothes container quest"

**Comment by wurzel-3** [comment]
#570

**Comment by mnalis** [comment]
There are more than 250 (hit the limit) [notes about that quest](https://ent8r.github.io/NotesReview/?view=map&query=Who%20accepts%20donations%20for%20this%20clothing%20bin&limit=250&status=all), many of which seems to be about `operator:signed=no`
