### ISSUE TITLE
highway=busway

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5766]
Check which quests should be asked for `highway=busway` and which overlays should show `highway=busway`.

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/issues/5749#issuecomment-2235881375 has some hints (and possibly other comments)

**Comment by riQQ** [comment]
In my opinion this issue should be closed in favor of #5749 as there is already some information there. Do you agree?

**Comment by westnordost** [comment]
Oh, I didn't notice the existence of this ticket.

**Comment by riQQ** [comment]
Duplicate of #5749
