### ISSUE TITLE
Asked to add opening hours to a dentist even though some have been entered before

### ISSUE THREAD

**Issue by Vuizur** [streetcomplete/StreetComplete#5768]
For this dentist: https://www.openstreetmap.org/node/2757267215#map=19/50.91480/13.35268 , opening hours exist and can be read by Organic maps, but I get the quest "What are the opening times of this place?", without the old time being displayed anywhere by Streetcomplete. I would have expected to be asked "Are these times still accurate?", like with most other POIs I encountered.

**Versions affected**

SC 58.2
Android 14

**Comment by kmpoppe** [comment]
Can confirm. 

When entering any value for that node, the undo changelog displays "updated `opening_hours`=..." in contrast to a place where there really are no opening hours tagged, where it says "added `opening_hours`=...".

Could the reason possibly be that the existing OH are too complicated for SC to interpret them?

**Comment by HolgerJeromin** [comment]
The mixure of comma and semicolon could push the POI into the "too complex to show" category.

**Comment by kmpoppe** [comment]
Well, the comma and semicolon mix also makes for a combination in the evaluation tool that's probably wrong... updating...

**Comment by kmpoppe** [comment]
Updated the OH, as they are now younger than 1 year, the quest is now gone. Let's close this Issue and see in 366 days whether it works correctly then ;-)

**Comment by Vuizur** [comment]
Thanks a lot to everybody for fixing it so quickly! 👍
