### ISSUE TITLE
Question highlights wrong area / way.

### ISSUE THREAD

**Issue by chrneumann** [streetcomplete/StreetComplete#5777]
For the restaurant at https://www.openstreetmap.org/node/1225244006, StreetComplete highlights the wrong area.

![signal-2024-08-01-172429_002](https://github.com/user-attachments/assets/814f5e2b-d94d-4544-b5c2-bf79ff9d96e1)

**How to Reproduce**
Try to answer a question for the restaurant. https://www.openstreetmap.org/way/4824560 gets highlighted.

**Expected Behavior**
https://www.openstreetmap.org/way/138261037 should get highligted.

**Versions affected**
StreetComplete 58.2, Android 14

**Comment by matkoniecz** [comment]
It is highlighting all nearby relevant areas, in this case hospital, not only quest object.

Quest object is marked with a quest marker.

**Comment by matkoniecz** [comment]
And https://www.openstreetmap.org/way/138261037 is not a restaurant, it is a building where restaurant is located.

Restaurant is correctly mapped as a node, see https://www.openstreetmap.org/node/1225244006

**Comment by chrneumann** [comment]
> It is highlighting all nearby relevant areas, in this case hospital, not only quest object.

Ok, I don't understand why the hospital area is relevant, and no other areas, including the building. A bit confusing.

**Comment by matkoniecz** [comment]
It highlights amenities/POIs and no other eateries or shops are mapped there (you can add them with places overlay if something is missing)

**Comment by chrneumann** [comment]
Okay, was not obvious for me. Sorry for the confusion.
