### ISSUE TITLE
Quest: What types of trolleys are available here?

### ISSUE THREAD

**Issue by Swarkin** [streetcomplete/StreetComplete#5778]
### General
Affected tag(s) to be modified/added: [`trolley:*:*`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtrolley_bay#Trolley_Type)
Question asked: **What types of trolleys are available here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)
  - This might not apply, however I believe it would be a good addition due to accessibility reasons. On top of that, [the tag usage seems to be growing](https://taginfo.openstreetmap.org/tags/amenity%3Dtrolley_bay#chronology).

**Comment by matkoniecz** [comment]
in my experience such special trolleys often may be missing because all are in use or may be placed into random locations

in other words, just because trolley bay is without any trolleys of some type, it does not mean they are unavailable at all

(also, why this data is useful enough to collect is not really clear to me)

**Comment by Swarkin** [comment]
Resurveying may be needed then every x amount of time.
When available, I've always seen several trolley bays split up per type of trolley, sometimes with labeling so that they do not get mixed up. This is also why I've ticked the second option.

The data is useful for poor sighted people, wheelchair drivers, parents with small children, or customers at hardware stores.

**Comment by Swarkin** [comment]
Do you think I should move this to the SCEE repo?

**Comment by westnordost** [comment]
Yes
