### ISSUE TITLE
Add Option(s) for Sports Pitches in "Things" Overlay

### ISSUE THREAD

**Issue by CurlingMan13** [streetcomplete/StreetComplete#5781]
**Use case**
When mapping a part using StreetComplete, the Things overlay can be used to add benches, trash cans, hydrants, etc.  However, there is no way to add a sports pitch, such as a basketball court, tennis court, etc.

**Proposed Solution**
Add ability to add sports pitch as a node.  One thing that needs to be considered is; What if it is already mapped as an area?  One solution would be to disallow placement of new sports pitch nodes within the area of another one.  For example, you can't add a tennis court node within the area of a tennis court.

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch

This would be more beneficial in rural areas where features have not been mapped and there is appreciation that someone is adding details to OSM.

**Comment by mnalis** [comment]
> Shouldn't most sports areas be tagged as a way? 

that is significantly preffered, yes (only about 3% of the pitches are mapped as a node).

As a workaround, I'd suggest long pressing on the map and choosing to leave a note, indicating what type of a pitch it is (maybe even with associated picture or a few), so it can be added properly as an area by another mapper (or even yourself) later in more full-featured editor with help of showing aerial imagery. There should not be so much of them that it becomes menial task...

**Comment by HolgerJeromin** [comment]
Table tennis is possible to add.
This is probably the only pitch where a node is ok`ish

**Comment by matkoniecz** [comment]
we are already also adding chess tables and giant chess, maybe more :)

**Comment by HolgerJeromin** [comment]
> And a soccer pitch as a node does not seem correct to me, as this should be adjusted again later.

A soccer pitch node is IMO not wrong but still an improvement to OSM.
Sure they can be optimized. But imo no need to force a note -> armchair mapper chain.

**Comment by rhhsm** [comment]
If this proposal is accepted, please include playgrounds as well. In my area, most playgrounds are mapped as nodes.

**Comment by HolgerJeromin** [comment]
> If this proposal is accepted, please include playgrounds as well. 

I am surprised, that `leisure=playground` is not included.
Perhaps we should create a separate item for that.
It was excluded in the document list from #4912 (with note "see dicussion" but I do not find a discussion). 
Many `playground=*` stuff is included but was rejected in the document.

@matkoniecz WDYT?

**Comment by westnordost** [comment]
These, along with car parks, playgrounds, parks etc. are deliberately excluded.

The only "pitches" that can still be considered as things are chess boards, table soccer, table tennis and teqball tables.

The current guidelines are:

> Small map features that are often mapped as points and usually cannot be entered. 
>  
> To demarcate this category from others, the following are not included: 
> - structures that are big enough that they would rather be classified alongside buildings   (e.g. water towers) 
> - permanent features of the landscape (e.g. geysers, peaks, springs) 
> - things that are features on other map features that wouldn't make sense on their own (e.g.  crossings, traffic lights, entrances, golf holes) 
> - things that should not be mapped as points - even if allowed - and landuses (e.g. car parks,   dog parks, playgrounds) 

A sport pitch is definitely not a "thing", but rather an (outdoor) "place".



However, these are also deliberately excluded from places, the current guidelines are:

> Map features like shops or amenities that usually have a name and can be entered.
>
> To demarcate this category from others, the following are not included:
>  - things that are rather structures or buildings than places (e.g. communication towers, train station)
> - landuses, outside-things (golf courses, zoos, marketplaces, car parking)

I.e. places in StreetComplete are things that usually can be entered.

So, currently, it is not possible to add outside place POIs like golf courses, parks, car parks, marketplaces, zoos, water parks, theme parks, pitches etc.

**Comment by mnalis** [comment]
Just to note for interested parties that [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) does allow (via long press / `Add POI`) to add any [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) `point` preset, including `leisure=playground` or `leisure=pitch`. 

Of course, adding them as nodes is suboptimal (areas as better, but you need [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) on the mobile to draw areas). 

But I guess one could always use [overpass to find such nodes](https://overpass-turbo.eu/s/22VD) later and improve them with comfort of armchair desktop mapping via aerial imagery, so it is better than leaving notes about missing playgrounds/pitches...
