### ISSUE TITLE
Consider publishing the app on Accrescent

### ISSUE THREAD

**Issue by realeatham** [streetcomplete/StreetComplete#5784]
Accrescent is an app store made for privacy and security. It is recommended by grapheneos. Adding it (and street measure) there would be good for people who don't use f-droid or gplay.

**Comment by HolgerJeromin** [comment]
Ref https://accrescent.app/
Did not found many recent Information about it...

**Comment by westnordost** [comment]
Never heard of that before, usage is probably near zero. Not really worth it to support it when any (recurring) action is required to appear on that store. Even though (currently?) not open source, the OpenApk-store approach seems better considering the "app store" market is saturated - i.e. no action required by app authors expect maybe an approving nod.

In any case, I tried to register myself as a developer on accrescent and got this error message.

> Registration not permitted
>
> Accrescent developer registration is currently invite-only. Please come back when registration opens for everyone.

One year ago, there was a thread about Accrescent on reddit, and people reported the same. So, yeah... 🤷‍♂️
