### ISSUE TITLE
Sending everything in one changeset instead of multiple

### ISSUE THREAD

**Issue by SleepyAks** [streetcomplete/StreetComplete#5785]
## Hi!
I recently started using StreetComplete as a way of mapping on the go. But today I looked at my account stats on hdyc.neis-one.org and saw number of changesets done from StreetComplete. It was the moment I realized, that every single quest has its own changeset. I don't like it this way, but not becuase it partially ruins my stats, but because I hate small changesets and situations where something, that could be easily done in one changeset is split between a dozen of them.
## Solution?
Add a setting, that if toggled, would send everything in one changeset and describe what quests were done in either changeset description or in a comment under the changeset. Additionally:
1. This setting should be "inactive" (e.g. you can't toggle it) if the "Upload answers automatically" is not toggled to "Off".
2. It should be (in my opinion) enabled automatically (but not activated automatically, reason above)
I, of course, hope it gets added to StreetComplete. Have a good day/night!
SleepyAks
## Post Scriptum
1. I won't be surprised if it has been already suggested, but rejected.
2. I also won't be surprised if it just can't be changed simply because that's how the app works.

**Comment by westnordost** [comment]
> Post Scriptum

Exactly. I'll close this as duplicate. I don't want to search through the issue tracker to link the correct discussions / issues, so just in a nutshell some of the reasons:
- current behavior is necessary to attribute the user by-quest statistics correctly
- current behavior is useful for spotting systematic wrong-tagging done by SC (either by users misunderstanding the question, i.e. wording that could be improved, or by an actual bug in SC)
- it is easy to filter out SC changesets (of certain quest types) in quality assurance tools such as OsmCha

**Comment by mnalis** [comment]
@SleepyAks For more details, see:

- [SC FAQ: How does the app handle uploads?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_does_the_app_handle_uploads?)

and

- https://github.com/streetcomplete/StreetComplete/issues/21 and links to it
