### ISSUE TITLE
Additional answer (power=tower) for Power Poles Material quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5793]
A more common tagging mistake (in my experience) of power poles is that some poles are actually lattice towers that should have been tagged with `power=tower`. They typically occur where a minor power line splits or changes direction (example here https://www.openstreetmap.org/way/845380419). It's hard to see on (aerial) imagery that these are different. So far I answered the quest with "steel" and then changed these to `power=tower` when home again (if I remembered) but it would be nice if I could change them within SC.

_Originally posted by @rhhsm in https://github.com/streetcomplete/StreetComplete/issues/5657#issuecomment-2143700086_
            
In fact for this situation, I think it would be preferable to add it as an answer option with a photo of a small tower, to make it clear how a tower is different from a pole, instead of an alternative under "Uhh..." where no photo can be shown. 
![640px-Small_pylon](https://github.com/user-attachments/assets/3bcaa20a-ab82-4b95-82fa-f69b6e0fd35e)

Choosing the answer option would replace power=pole with power=tower. I don't think it is necessary to add a material tag, as I can't imagine there are towers that are not made of steel.

**Comment by westnordost** [comment]
Is is something that can happen that within one power line, there are a few power poles and a few power towers?

**Comment by rhhsm** [comment]
Yes, minor power lines often are mostly poles, but have towers at positions where the line changes direction, splits or crosses a road.

**Comment by westnordost** [comment]
I was asking that because I am wondering how often the whole line is mistagged and how often indeed there is just a single tower that is a tower and not a pole.

If the former is at least a possibility that should not be discarded, I think it would be better to leave a note, so that someone in front of a computer who has access to aerial imagery can check it.

**Comment by rhhsm** [comment]
Maybe "All supports of this power line are towers, not poles" could be an answer under "Uhh..."? It would be a good reason to leave a note, but an armchair mapper may not be able to help much using aerial imagery because it's already difficult to map a power line and its supports using imagery; distinguishing a tower from a pole is even more difficult. See the are around the example I gave above https://www.openstreetmap.org/edit?way=845380419#map=17/43.62806/25.03910 (at zoom level 17 you can see that the symbols for pole and tower nodes are different). From the imagery (Esri Clarity) you can see where the supports are because of the shadows they cast and because the land around their base is not worked, but determining which one is a pole and which a tower is very difficult. There is a larger power line with only towers a bit further south and here you can see they are towers because of the shadows cast by the cross-arms. The towers of the minor line don't have cross-arms.

**Comment by westnordost** [comment]
Depends on the quality of the aerial imagery. In some areas, armchair mappers may not be able to discern it, in some areas, they do.

**Comment by rhhsm** [comment]
Of course it can be handled with notes, but my experience is that they could be many for the same power line. An added advantage of adding an answer option with a photo is that it would clarify for inexperienced users (which are SC's prime target audience) that a tower is different from a pole and that there are different tags for them. I suspect that quite a few beginners are just answering "steel" without realising that there's some wrong information on the map that they could have corrected (i.e. they won't leave a note)
