### ISSUE TITLE
Add overlay for entrances

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#5798]
**Use case**

It is nice to have entrances for buildings.

They are rendered on many maps and helpful to plan approach to a building (no need to crawl through the garden of the private house.

Example of an important entrance [node](https://www.openstreetmap.org/node/12082822249):
![image](https://github.com/user-attachments/assets/8e54050b-703e-40cc-adb5-a8035dd7ee78)

**Proposed Solution**

Quite similar to the address overlay but without the added addresses.
On the building way SC would create a node with `entrance=yes` (or even more fancy `=staircase` or others.)

**Comment by westnordost** [comment]
That sounds much too specific to me. I also fail to see the useful purpose, as entrances with housenumbers can already be added. Theoretically, the buildings overlay could be expanded to allow entrances vertices to be displayed, added and removed, but I don't really see the point.

**Comment by matkoniecz** [comment]
> entrances with housenumbers can already be added

but entrances without house number can not be

in some areas (for example Poland - and probably other areas where entrance ref quest is enabled) entrances have no house numbers but codes

**Comment by HolgerJeromin** [comment]
All house numbers are in many regions already on the buildings. So the address overlay (in its current form) is not usable.

**Comment by rhhsm** [comment]
As @matkoniecz suggested, I would like to be able to add at least staircase entrances so that I can then add the `ref` code with the entrance ref quest

**Comment by westnordost** [comment]
Sounds rather that there should be an option in the address overlay to say that it has no housenumber but.... an entrance ref.

**Comment by HolgerJeromin** [comment]
> Sounds rather that there should be an option in the address overlay to say that it has no housenumber but.... an entrance ref.

Or no house number in the case of a normal residential (detached) house. 

In Germany I know entrance with refs mostly for industrial or [school](https://www.openstreetmap.org/node/11826952090) buildings (for the [police](https://www.berlin.de/schulbau/neubau/planungsvorgaben/201901_amokkennzeich.pdf)).

**Comment by rhhsm** [comment]
> Anyway, I'll reject this feature request for an overlay for entrances. The only use I see for this would be to allow adding entrances that have ref numbers, but then this shoudl rather be an extension to the address overlay rather than an own overlay (and only allow to add ref numbers, instead of not-housenumbers-but-entrances).

I agree. It could be an additional answer option under the three dots "It's a staircase entrance with a reference code" which would add a node tagged with `entrance=staircase` and trigger the entrance reference quest if appropriate. Something like the "It does not belong to a named street…" option that adds `addr:place=*`

IIRC the "address on entrance" system is only used in Italy? Then we could consider putting that option as an alternative answer, and assume by default that the added entrance is a staircase entrance with ref code, because it occurs in more than one country. Or let the default depend on the country of the added node...

**Comment by westnordost** [comment]
> IIRC the "address on entrance" system is only used in Italy?

Not sure what you mean. You can add addresses on entrances (and entrances with addresses) in every country with STreetComplete

**Comment by rhhsm** [comment]
> > IIRC the "address on entrance" system is only used in Italy?
> 
> Not sure what you mean. You can add addresses on entrances (and entrances with addresses) in every country with STreetComplete

Yes, but this seems to be in actual use only in Italy https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources Most countries appear to add addresses either on a building or on special address nodes. The overview is not complete though; maybe someone more skilful than me could check where in the world nodes occur that have both an `entrance=*` tag and an `addr:*` tag?

**Comment by westnordost** [comment]
No, it is just as fine to have it on the entrance node, actually, the most precise method. You see this often in cities with apartment blocks, where other methods are just less precise or not possible (due to multiple house numbers per building)

**Comment by matkoniecz** [comment]
> Yes, but this seems to be in actual use only in Italy https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources

Italy has addresses only on entrances (or mostly on entrances). In other countries it is also possible to have address assigned to entrance (or be tagged on it) but it is more rare.

Also, Italy is (hopefully) unique in having these entrance address node be sometimes placed on entrance to property, such as a gate - not attached to a building
