### ISSUE TITLE
Add option for pedestrian and bicycles can walk/drive on the road

### ISSUE THREAD

**Issue by cd-FileX** [streetcomplete/StreetComplete#5801]
**Use case**

There is often the case for me where I am being asked by SC if there is a bicycle way or an extra way for pedestrians.
If this is not the case, but it is allowed to walk/drive on the road, then there is no option.

**Proposed Solution**

Add an option for no separated way but accessible/walkable

**Comment by HolgerJeromin** [comment]
Do you have in image for such situation?
Mapillary or google streetview?

**Comment by matkoniecz** [comment]
> There is often the case for me where I am being asked by SC if there is a bicycle way or an extra way for pedestrians.
> If this is not the case, but it is allowed to walk/drive on the road, then there is no option.

For sidewalks there is separate quest asking whether pedestrians are banned.

If there is no sidewalk and they are allowed, just answer that there is no sidewalk.

For cycleway - leave note if there is total bicycle ban, if allowed with no infrastructure select matching option.
