### ISSUE TITLE
Wi-Fi password quest

### ISSUE THREAD

**Issue by vfosnar** [streetcomplete/StreetComplete#5805]
### General
Affected tag(s) to be modified/added: [internet_access:password](https://wiki.openstreetmap.org/wiki/Tag:internet_access%3Dwlan)
Question asked: **What is the Wi-Fi password here?**

- input box -> internet_access:password = value
- Uh... The Wi-Fi doesn't have a password -> internet_access:password = no
### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by vfosnar** [comment]
The quest will have to be disabled by default according to the guidelines. I can implement the quest if it gets a pass.

**Comment by goldfndr** [comment]
Sometimes the WAP will be "open" but have a captive portal with prompting for a password. For example here, Claim Jumper and Ezells Chicken restaurants, Factoria shopping mall, Issaquah school district, Best Western and Quality Inn hotels, AMC stubs cinemas, TH nail salon. Perhaps the "Uh..."

**Comment by vfosnar** [comment]
If it's prompting for a shared password then its still some kind of internet access password. More problematic is the case of per-customer credentials. Maybe we should also add an option "yes, but unknown" -> internet_access:password = yes

**Comment by westnordost** [comment]
This is private information and should not be recorded in OpenStreetMap at all.

**Comment by vfosnar** [comment]
I don't see a problem with uploading such data to OSM but I respect your position

**Comment by mnalis** [comment]
related topic on OSM wiki: https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information

**Comment by vfosnar** [comment]
doesn't seem problematic based on what's on the wiki too, also https://github.com/Helium314/SCEE/issues/603#issuecomment-2294899314

**Comment by matkoniecz** [comment]
> related topic on OSM wiki: https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information

this is not exhaustive listing of all possible things to not map

overall such wifi password info seems useful only to people wishing to bypass wifi usage limitation set by its author - and I see no value in mapping it

**Comment by vfosnar** [comment]
> useful only to people wishing to bypass wifi usage limitation set by its author

How? Give me one example where it wouldn't be super inconvinient to do so- I don't want to support jerks, I just think this argument doesn't have any value in the modern age

> and I see no value in mapping it

as I said, having to ask for the password, blocking queue for minutes because they don't remember it and stuff instead of clicking a button in my maps sound inconvenient enough

**Comment by mnalis** [comment]
I've opened https://community.openstreetmap.org/t/opinions-on-internet-access-password/117581 for discussion, as merit of `internet_access:password=*` in not StreetComplete-specific, but applies to whole of OSM. Let's continue the discussion there.
