### ISSUE TITLE
Don't ask for buildings name in a relation that already has a name

### ISSUE THREAD

**Issue by vfosnar** [streetcomplete/StreetComplete#5806]
"What's the name of this place?" quest should be disabled for buildings that are in a relation with the `name` tag set

![Screenshot_20240817-123448_Street­Complete](https://github.com/user-attachments/assets/dd4891f2-6511-40f6-bc6f-c257d076ca23)

**How to Reproduce**

**Expected Behavior**

**Versions affected**

**Comment by westnordost** [comment]
It doesn't ask for the building name, but for the name of the government office.

If in that building there is not a single government office, then `office=government` should not be tagged on that building but on the relation.

**Comment by vfosnar** [comment]
oh sorry then it's my bad, thanks
