### ISSUE TITLE
Problem of layout in privacy statement

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5811]
**How to Reproduce**
- Open app -> Go to about -> Privacy statement 

|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/cb47cacf-9e21-4a5a-8d91-8ea12e983658" height=400 />|<img src="https://github.com/user-attachments/assets/aa2d8375-dbd7-4b72-97a5-34f70e3e2014" height=400 />|

**Expected Behavior**
- No empty line at the start
- New line before location title

**Versions affected**
Android 14 - v58.2 and V59.0-alpha1

**Comment by westnordost** [comment]
Will be fixed on the alpha1 release. (Must be fixed in POEditor, but it already is, just hasn't been imported from there yet)
