### ISSUE TITLE
Links not clickable in changelog dialog

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5814]
**How to Reproduce**

1. Upgrade to [v59.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v59.0-alpha1).
2. Tap the message button to show the changelog.
3. Tap any link, e.g. an issue number or a contributor.
4. See that nothing happens :slightly_frowning_face: 

**Expected Behavior**
The web browser app opens to show the link.
Also note that it *does* work fine in the version history page.

**Versions affected**
StreetComplete v59.0-alpha1
Android 13

**Comment by westnordost** [comment]
It's fixed in #5799 but since this didn't go into v59.0,  I'll fix it independently.
