### ISSUE TITLE
Quests don't show up until map is moved after download

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5823]
I noticed that quests are not rendered after loading a new section, if the map is not moved. Looks like there might be missing some kind of refresh command. 

**Screenshot**

https://github.com/user-attachments/assets/e712c3e6-cca9-40ad-8e1e-487e10b9377d

**How to Reproduce**
- Move map to a not yet loaded section. 
- Download section
- See no quests rendered after download is completed

**Expected Behavior**
Quests pop up after download and processing is completed. 

**Versions affected**
Android 12
SC 59.0 Alpha 1

**Comment by RubenKelevra** [comment]
> But anyway, from the video it looks like you perhaps zoomed out too much for them to be visible in the first place? Is this reproducible if you are zoomed in more?

Yeah (note the already rendered quests on the left). This was captured right after the download was finished. 


https://github.com/user-attachments/assets/cd39aefb-d399-4ae6-9423-83dd97306747

**Comment by westnordost** [comment]
Okay, my suspicion is that this actually is deliberate impmlementation on our side and done for performance reasons. Quests will only pulled from the database when a certain maximum area / maximum number of tiles are in view. Once they have been pulled from the database however, they continue being displayed even on lower zoom levels.

**Comment by RubenKelevra** [comment]
Ah yeah, that makes sense that it doesn't happen if you're zoomed in further.

However the justification doesn't make much sense for this usecase: If you download a larger area you expect the app to lag for a second - maybe - while processing. So I think it would be fine to force loading them from the database once on manual downloads - if possible.

The reason being is that if you download an area manually you going to be zoomed out as much as possible - if you wanna preload the area.

Not showing the new quests in this case is weird and might be confusing for users.

**Comment by westnordost** [comment]
I can confirm that data is definitely showing up immediately and thus it has something to do with being zoomed out that much.

**Comment by Helium314** [comment]
Maybe you could increase the 16 tile limit in quest pins manager? I set it to 32 in SCEE, and didn't have noticeable performance issues on S4 Mini.

**Comment by westnordost** [comment]
Ok, if Mr. Performance says that it's no problem, let's do that.
