### ISSUE TITLE
Ask for crossing markings

### ISSUE THREAD

**Issue by JokelaR** [streetcomplete/StreetComplete#5826]
### General
Affected tag(s) to be modified/added: [`crossing:markings=*`](https://wiki.openstreetmap.org/wiki/Key:crossing:markings), 
Question asked: **What kind of street markings does this crossing have?**

This would further expands on the crossing:markings tagging work added in #5471 by filling in the specific type of markings, instead of simply yes/no.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
  - `crossing:markings` is both widely used, and encouraged by iD's presets. Standalone `crossing=marked` is in fact considered "incomplete" by such presets now. 
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  - Any `crossing:markings=` value would be wanted, and as such `=no` is also an option.
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  - Crossing markings are trivial to perceive, and omnipresent in urban areas. 
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** `crossing=`, except where `crossing=unmarked`, `crossing=no`, or `crossing=informal` (or `informal=yes`), and where `crossing:markings` is either not present, or `crossing:markings=yes`. 
The biggest issue with that last part I can foresee is that there might be some legitimate uses of `crossing:markings=yes` for extremely complex or undocumented markings, but they are currently crowded out by the default iD presets upgrading marked crossings. 

**Proposed UI:** A visual simplified icon grid roughly matching the diagrams on the OSM Wiki would probably be the most easy to identify options out of.

### Other considerations
Upgrading `crossing=marked` to `crossing=uncontrolled`+`crossing:markings=*` is also something that could be considered, but I'm uncertain after looking into the history of controversy when it comes to `crossing=marked`.

**Comment by FloEdelmann** [comment]
For reference:

* https://github.com/streetcomplete/StreetComplete/issues/4663
* https://github.com/streetcomplete/StreetComplete/issues/5102

**Comment by JokelaR** [comment]
I'm a bit confused on the reasoning behind closing the previous issues under the grounds of the wiki not documenting the legislative purpose of differing markings. 

We all agree that under some traffic laws the markings may have further meaning outside of their literal design, and those meanings are derived by the road users from the design of the markings. Which one is a layperson more able to identify on the street, the legislative meaning, [or the ground truth](https://wiki.openstreetmap.org/wiki/Good_practice#Map_what's_on_the_ground)? 

My personal area of knowledge is Finland, so I know that in Finland, `zebra:double` under current legislation is an indication that cars yield to cyclists, while `zebra` means they don't. If you wanted to implement Finland-specific Quests for "does the car yield", I'd find the reasoning more consistent, but it doesn't really feel like the best route to this.

**Comment by westnordost** [comment]
The number of selectable choices should be reduced to the choices that can exist on a per-country basis, as I've written in the linked issues. This requires prior research that has to be documented well on the wiki.
