### ISSUE TITLE
Touch buffer around quest pins seems larger on MapLibre than on Tangram

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5827]
I have the new SC 59.0-alpha1 and SCEE 58.21, so I'm able to compare directly.

There seems to be a bit of a buffer around the pins so that an inaccurate touch still selects a quest. However, that buffer seems wider on 59.0, so when trying to use overlays (specifically buildings), I'm often selecting quests instead of the underlying building, even with a touch that wouldn't select a quest in older versions.

**Comment by westnordost** [comment]
It should be exactly the same. The assumed finger radius is 24 pixel.

**Comment by westnordost** [comment]
Anyway, I think it makes sense to remove that buffer for quests. The quest pins are already as large as buttons, so they don't really need that buffer. It is the overlays that do need this buffer.
