### ISSUE TITLE
Barrier opening: Should not ask for barriers that are not vertices of a way

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5830]
The new `AddBarrierOpening` quest also asks for the width of free-floating bollards, i.e. those that are not part of a way, e.g. https://www.openstreetmap.org/node/7518331648

It does not make sense to ask this question for these.

**Versions affected**
v59.0-alpha1

**Comment by Nick-Tallguy** [comment]
**railway_crossing**  uses the same filter arrangement.

**overpass turbo** (Copied from another query - please check!) finds crossings not on a highway.

     [bbox:{{bbox}}];
     node[railway=crossing] -> .allnodes;
     way[highway](bn.allnodes);
     node(w)[railway=crossing] -> .waynodes;
     (.allnodes; - .waynodes;);
     out;

Not many of these, but <https://www.openstreetmap.org/node/2054502295> found, and is also found using StreetComplete as a crossing quest - should be excluded by the filter.

**Comment by westnordost** [comment]
Not quite. The filter will *exclude* nodes that are vertices of certain ways. But don't worry, I know how to implement this and I will do it today.
