### ISSUE TITLE
Level scale (indoor)

### ISSUE THREAD

**Issue by tonio4open** [streetcomplete/StreetComplete#5831]
Hello,

**Use case**
If you are in a train station or in a shopping centre, your have full of quests at the same place ([attached example](https://github.com/user-attachments/assets/e5f61b63-2853-4d37-8081-43f88e6ad161): Gare de Lyon, in Paris), because StreetComplete doesn't care the "level" tag on the map. And it's not quick nor easy to open each quest and to read the indicated level of the POI to identify if you are at the good level to solve the quest.

**Proposed Solution**
As on [indoor=](https://indoorequal.org/), put an optional level scale on the screen to select the level of the quests to display.

Thanks for that ! and thanks for the excellent StreetComplete !

**Comment by FloEdelmann** [comment]
This was previously rejected because of UI clutter, see #2874 and #3068.

**Comment by tonio4open** [comment]
Thanks @FloEdelmann to highlight that. I didn't find them in my initial search...

And too bad :slightly_frowning_face:
