### ISSUE TITLE
Underground fire hydrant icon missing in 59 alpha

### ISSUE THREAD

**Issue by davidpnewton** [streetcomplete/StreetComplete#5832]
**How to Reproduce**
Open Streetcomplete 59 alpha and find an underground fire hydrant. In previous versions the icon was the same as that for a pillar fire hydrant. In the alpha it is the same as that for an advertising totem.

**Expected Behavior**
Display same icon for underground fire hydrant as for pillar fire hydrant.

**Versions affected**
Android 14
One UI 6.1
Streetcomplete 59.0 alpha 1
Samsung Galaxy A55

**Comment by westnordost** [comment]
That would be an issue for the iD presets. But there is no separate preset for underground fire hydrants, so I am confuse. Would you please provide for which element this can be reproduced?
