### ISSUE TITLE
Remove "display order" from quest selection title

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5833]
In #5719, the quest reordering functionality was removed:

> Reordering quests with drag & drop is no longer supported because this is a missing feature in compose so far

However, the setting is still called "Quest selection *and display order*" (emphasis mine). Since this is not possible anymore, the setting should be renamed to just "Quest selection".

Or is it supposed to come back later? But even then, it should be renamed in the meantime because it is confusing.

**Comment by westnordost** [comment]
Yes, maybe it can come back later. See this comment in the code. https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/settings/quest_selection/QuestSelectionScreen.kt#L34-L39

I don't want to change the strings while the situation may change soon.
