### ISSUE TITLE
(MapLibre) SC incorrectly rotates "direction cone" when rotating the map with gesture

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5834]
SC v59.0-alpha1 incorrectly rotates "direction cone" while the user is pointing the phone in the same direction, but tries rotate map with gesture on the phone screen.

**How to Reproduce**
- stand still and e.g. face a building with a phone
- without moving a phone direction, do rotate gesture with finger on the screen
- notice that direction cone starts pointing to other directions, instead of continuing to always face the building!

It is easier to explain with a video:
https://github.com/user-attachments/assets/7804ee86-cb20-4e73-b4c8-a934c56991a1

**Expected Behavior**

Screen should rotate (see dark-mode SCEE example video below), but direction cone should continue facing the same object (as the user and the physical phone are still obviously facing that direction). IOW the direction cone should rotate with the rest of the rotated screen.

https://github.com/user-attachments/assets/79e3198c-d729-4c7e-a93e-080c2bce2460 

**Versions affected**

SC v59.0-alpha1 (not present in previous non-MapLibre versions) on Android 14

**Comment by westnordost** [comment]
Already fixed https://github.com/streetcomplete/StreetComplete/commit/89511f4149b1c0e7bc7a61a51a8d7bf63b7233ad
