### ISSUE TITLE
(MapLibre) SC zoom gesture often problematic (and rotate too

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5836]
**Use case**

in Maplibre SC v59.0-alpha1, zoom gesture if often not recognized correctly, see videos below:

https://github.com/user-attachments/assets/661e4fc6-1ebf-42a1-bd7f-d392feac038f

https://github.com/user-attachments/assets/dfcd232e-8044-49af-be6a-151398b39a06

Even **when I try to pinch/stretch a lot, it is _often_ not zooming out/in,** but doing nothing (or slightly panning/rotating). Sometimes it work just fine, though. I can't tell if that is a MapLibre feature or a bug :shrug: 

Also, why trying to zoom, it is **too easy to accidentally rotate screen instead**

**Proposed Solution**

In Tangrem-ES,  both worked fine:
- zooming in/out gesture (pinch/stretch) just worked always
- and also, when zoom gesture started, rotating required a little "extra push", so accidental rotates were avoided

I'm not sure if something about those can be influenced from StreetComplete side, or if that is totally unchangeable behaviour fully determined by MapLibre (and thus  should be reported there)?

**Comment by westnordost** [comment]
Yes, this is MapLibre and MapLibre does not offer to implement it differently. You'll have to open a ticket at the maplibre-native issue tracker if it bugs you
