### ISSUE TITLE
Cannot take photo

### ISSUE THREAD

**Issue by oliver** [streetcomplete/StreetComplete#5841]
I cannot attach a photo to a note: after taking the photo, the picture is just displayed, but nothing else happens.

**How to Reproduce**

- click on an open note on the map
- in the discussion view, click on the "take photo" icon at bottom left
- camera UI comes up
- click on the trigger button
- "shutter beep" is played, and a picture is taken
- the picture is shown slightly scaled down on the screen, with nothing else visible. Tapping on the picture or sliding does not change anything. So far I only found the solution to click the Android Back button; but then it appears that the picture is not actually attached.

**Expected Behavior**

After tapping the trigger button in camera UI, I expect the picture to be attached. Maybe there should be a confirmation screen. At any rate, I expect something to happen besides just showing the picture with no further UI elements :-)

**Versions affected**

This happens with StreetComplete v58.2 from F-Droid, under Android 13 (LineageOS 20).

**Comment by mnalis** [comment]
You must **also** type some text, and then "OK" button will become visible. It is not possible to create picture-only notes, there must be some accompanying text.

That is indeed UI confusion, IMHO.  I'd suggest `OK` button to be always displayed, but grayed-out/disabled until the user enters some text.

**Comment by westnordost** [comment]
This is a bug in your camera app. Let me guess: You are using OpenCamera. There should be a ✅ button on the **lower right** (and a "Retry" button on the lower left). And there is, but it is invisible. Try just clicking in that area.

**Comment by oliver** [comment]
@westnordost : yes, tapping into the lower right corner does work!

And yes, the app that comes up appears to be the LineageOS Camera app (I hadn't recognized it because I use another camera app usually). Do you know if this is a known issue with the LOS Camera app?

**Comment by riQQ** [comment]
It's a common, old bug. Has already been reported in #5555 and probably more tickets I can't find right now.

**Comment by mnalis** [comment]
I've added [SC FAQ: How do I attach a picture to the note?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_do_I_attach_a_picture_to_the_note?)

(it probably might be expanded if needed for non-lineageOS case)

**Comment by westnordost** [comment]
> (I hadn't recognized it because I use another camera app usually)

You can your change your default camera app in the android settings.

> Do you know if this is a known issue with the LOS Camera app?

No, I don't know. Feel free to create an issue at LineageOS.

**Comment by oliver** [comment]
This is probably the matching issue in LineageOS: https://gitlab.com/LineageOS/issues/android/-/issues/6839

According to https://github.com/nextcloud/android/issues/12645#issuecomment-2097496526 this is fixed in LineageOS 21.0-20240502 .

Thanks for your help, and for building StreetComplete! It really helps me improving OSM data in my area.
