### ISSUE TITLE
Support Limiting Number of Quests Visible

### ISSUE THREAD

**Issue by alexschneider** [streetcomplete/StreetComplete#5843]
**Use case**
I'd like to contribute to OSM but looking at all the quests available is overwhelming, even after curating the quests to exclude the most common ones.

**Proposed Solution**

Radius and/or distance mode where you can select the number of quests you want to complete, the distance you want to travel or the radius you want the quests to be within, and it'll display a random selection of that number of quests within that radius or distance for you to accomplish.

**Comment by Helium314** [comment]
Better just enable team mode. If you select 2 players, you'll get half the number of quests, quarter if you select 4.

**Comment by mnalis** [comment]
Few comments that perhaps might be helpful too:

- I'd recommend creating two different presents (via `Settings` / `Manage presets` / `+`): one with **just a few quests** which you find most useful, and the other with several more of them. Then you can use the former (which should never be overwhelming, but always rather sparse) for most cases, and only switch to latter when find out that you've cleared that area and want more.
(there were also other ideas/approaches to the issue, some more automatic like e.g. https://github.com/streetcomplete/StreetComplete/issues/2944, but this works - just is somewhat manual, especially initially to create the presets)

- There is also `v59.0` release in the preparation, which, when released, will have less-overwhelming look (there will still be the same amount of quests, but they'd be displayed as clusters, so it would not look so threatening).

- And a general hint: Don't feel bad about disabling many quests, even if they look quite useful: instead disable as much of them as needed to make it fun and not like insurmountable task to accomplish! That will benefit both you and OSM much more in the long run!) 
  In fact, I'd recommend you choose `Deselect all`, and then only enable a few that you like the most (and periodically check the map that it doesn't get too crowded -- if it does, start deselecting things again!)
