### ISSUE TITLE
#5845 reappeared, can't get rid of it

### ISSUE THREAD

**Issue by clamyahoo** [streetcomplete/StreetComplete#5847]
#5845 reappeared, sorry, I can't get rid of it. I attached a screenrecord now to make it more clear. 
The Bad Thing is: On openstreetmap, I can access. My account is fine. It seems to happen when I have to confirm that Streetcomplete has the right to make changes on OSM. Is there another authentication necessary?

**Comment by westnordost** [comment]
But really, this is not a bug in StreetComplete. I've already written that you can trust the error message displayed.

**Comment by clamyahoo** [comment]
Ok, then I'll try to find out what the Problem is.

**Comment by westnordost** [comment]
Ah, I see you posted the screenrecord in the other issue.
