### ISSUE TITLE
Scale down POI icons on lower zoom levels

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5848]
**Use case**
In v59.0-alpha1, the minimum zoom level to show POI icons in the Things overlay was reduced, and colliding icons are not hidden anymore, to allow having a better overview and prevent entering already existing POIs.

However, that makes the individual icons indistinguishable because they are likely to collide in micromapped areas:

| Zoomed out | Zoomed in |
|---|----|
| <img alt="Screenshot_20240827-231326_Street­Complete.png" src="https://github.com/user-attachments/assets/b5d7e3bc-143f-47be-8f4b-3cb749c8baf2" width="250"> | <img alt="Screenshot_20240827-231353_Street­Complete.png" src="https://github.com/user-attachments/assets/c7da6780-d7be-4bd6-9cf7-9ddf67a7defd" width="250"> |

**Proposed Solution**
I suggest to scale down POI icons on lower zoom levels, so that the individual icons are less likely to collide with each other, making them more likely to be recognized and distinguished.

I think it might not even be a problem if the different types cannot be well distinguished because they are too small, since at those low zoom levels you likely only want to see if anything is mapped here at all, and should be encouraged to zoom in to add new things anyway.

**Comment by westnordost** [comment]
From a technical perspective, this should be doable.

But how far would you have to scale down these benches or for that matter other map features that are close-by so that they don't overlap?

I was about to ask why icon-piles need to be distinguished at all on lower zoom levels, as... well, you wrote it yourself... on low zoom levels, you just want to see if anything is mapped at all... so why scale them at all?

**Comment by matkoniecz** [comment]
If they would continue to be well recognisable it would be prettier.

**Comment by HolgerJeromin** [comment]
I find especially the building icons in building overlay far to large in latest alpha.

**Comment by mnalis** [comment]
> If they would continue to be well recognisable it would be prettier.

If those benches had an one-pixel black outline, at least one of them (the last drawn) would be recognizable. I have no idea if that is supported by MapLibre, though (nor whether it is easy to automatically add such an outline - obviously manually redrawing hundreds of new icons might be somewhat undesirable :smiley_cat: )

**Comment by Helium314** [comment]
> If those benches had an one-pixel black outline, at least one of them (the last drawn) would be recognizable. I have no idea if that is supported by MapLibre, though (nor whether it is easy to automatically add such an outline - obviously manually redrawing hundreds of new icons might be somewhat undesirable 😺 )

Outlines are added using MapLibre ("halo"), not sure if this merged appearance is wanted or a bug (for text it does not happen).
Adding an outline to the icon itself is (technically) possible, but then icons can't be colored using the _iconColor_ property any more (MapLibre limitation for non-sdf-icons).
