### ISSUE TITLE
Selecting quests for long ways in navigate mode zooms the map out way too far

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5858]
In navigate mode (the arrow icon), when I select a quest that has a very long geometry, the map zooms out way farther than necessary to fit the shape on the screen. Then when zooming back in, sometimes it doesn't zoom back to the original level, possibly because a draw process hiccups the zoom (_cf._ #5813).

https://github.com/user-attachments/assets/570b1682-cb8a-4cb7-8e2f-6c087f235a23

**How to Reproduce**

Find a really long line (long street, long fence), and be zoomed in to a reasonable closeness (block level, z19ish?). Make sure you're in navigate mode and the map is tilted. Tap the long line quest.

**Expected Behavior**

It should zoom out only to fit the geometry, as it does in crosshair/untilted mode. Also, if it helps, if I turn off animations system-wide, then it zooms out correctly, but switches to crosshair/untilted.

**Versions affected**

v59.0-alpha2

**Comment by Helium314** [comment]
> It should zoom out only to fit the geometry, as it does in north-up mode

Is it really dependent on map rotation (north up), in addition to tilt?

**Comment by pkoby** [comment]
Oh, good point. What I called north-up is the untilted centered mode (the crosshair). I'll change that.

It's the tilt that does it. The more tilted, the farther it zooms out. I just got a fence to zoom me out to half the USA.

**Comment by westnordost** [comment]
Reported upstream. Also tested a bit more and added some information not previously mentioned here. If you find any more info, please add it there.
