### ISSUE TITLE
Graphical glitch of cluster labels when zoomed out in navigate mode

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5859]
When the map is tilted in navigate mode, zooming out to the lowest zoom level with clustered points has a graphical glitch where the number labels go all wiggly.

https://github.com/user-attachments/assets/7c24179a-d3a1-4796-ab85-1cf8423dbea1

**How to Reproduce**

Zoom out in navigate mode (arrow icon) to the smallest zoom level that still has clusters. Issue persists in north-up mode too, until zoomed back in.

**Expected Behavior**

Numbers should still appear as numbers.

**Versions affected**

v59.0-alpha2

**Comment by HolgerJeromin** [comment]
Btw: is the tilted "flat" compass icon on the top right a bug or feature?

**Comment by westnordost** [comment]
> Btw: is the tilted "flat" compass icon on the top right a bug or feature?

Feature

**Comment by westnordost** [comment]
What is your Android OS version and what is your device?

**Comment by westnordost** [comment]
I noticed that the text is still wiggly even when you disabled tilt. Is it reproducible without navigation mode?

**Comment by HolgerJeromin** [comment]
My device (Motorola, Android 14) loose numbers but does not push the text around:

![Screenshot_20240831-071629](https://github.com/user-attachments/assets/ea53e9be-28c9-441f-baa2-7b523ab082d0)

**Comment by westnordost** [comment]
Mine, too.

**Comment by westnordost** [comment]
Can you reproduce the rendering issue with the places or address overlay?

**Comment by westnordost** [comment]
Reported upstream. Any additional information can be posted there.

**Comment by westnordost** [comment]
upstream there are difficulties reproducing it. If you can reproduce it, please state your phone model and Android version, maybe it is a device or Android-version specific issue.
