### ISSUE TITLE
List of options for quest "Can you drop off parcels here?" contains "There is no restroom here" instead of "Only for return deliveries". 

### ISSUE THREAD

**Issue by sannoization** [streetcomplete/StreetComplete#5864]
List of options for quest "Can you drop off parcels here?" contains "There is no restroom here" instead of "Only for return deliveries". But tags are set correctly after choosing this option.

**How to Reproduce**

1. Choose quest "Can you drop off parcels here?"
2. Choose "Uh.."
3. See option "There is no restroom here"

**Expected Behavior**

List of options contains "Only for return deliveries"

**Versions affected**

Android
POCO F5 Android 14
StreetComplete v.58.2

https://github.com/user-attachments/assets/9ebbb073-e3df-46f7-afec-92b3e9309cc4

**Comment by mnalis** [comment]
Thanks for reporting that [bug](https://github.com/streetcomplete/StreetComplete/blob/8636a3b62f5d464cc87cb98899bc9b403e7cbaef/app/src/main/java/de/westnordost/streetcomplete/quests/parcel_locker_mail_in/AddParcelLockerMailInForm.kt#L13-L16), @sannoization ! 

That quest however will already be removed completely in next release (see #5763 for reasons why), so I'll mark it as completed. (it also seems to be [already fixed](https://github.com/Helium314/SCEE/blob/205de3dd3e995d3533073cf6efdb86a3c5fdd1b7/app/src/main/java/de/westnordost/streetcomplete/quests/parcel_locker_mail_in/AddParcelLockerMailInForm.kt#L13-L16) in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE), for those still wanting to continue solve those)
