### ISSUE TITLE
 "What is the width of the opening" allows a maximum of 9.99 meter, not enough

### ISSUE THREAD

**Issue by ratti** [streetcomplete/StreetComplete#5865]
Note: The question "What is the width of the opening" is in a alpha-version of SC, but was picked for SCEE already. I have this finding in SCEE only, because I use the stable version of SC, but I was asked to open the ticket here, since it's the upstream. The related SCEE ticket is [here](https://github.com/Helium314/SCEE/issues/628)

The question "What is the width of the opening" allows a maximum of 9.99 meter, which is not enough for industrial entrances, flood protection gates etc.

**How to Reproduce**
Find that question somewhere, try to answer i.e. "18". Higest number I can type is 9.99 , not 10.

**Expected Behavior**
While some validation  is useful, hangars or flood gates should be possible.

**Does it happen in normal StreetComplete?**
It looks like SCEE merged this feature from a SC alpha I can't test.

**Versions affected**
SCEE 58.22
SC:  59.0-alpha , which I don't use

<img width="1039" alt="SCR-20240901-mvim" src="https://github.com/user-attachments/assets/cb43164c-e35e-454a-9c8c-61abc68eef5c">

I can imagine easily requiring large values on:

-     Stormflood barriers going across multiple road lanes
-     Entrances to heavy industrial companies
-     Airport hangar doors for jumbo jets
-     I didn't come across that, but I guess at the ocean coast there even might be “gates“ wider than 100 meters, wild guess.

**Comment by matkoniecz** [comment]
Can you link OSM object where you encountered it and would be shown by this quest?

**Comment by westnordost** [comment]
https://www.openstreetmap.org/node/12147581454#map=19/53.544222/9.918755
