### ISSUE TITLE
[alpha-4] border on the right side of the bar in statistics

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#5867]
As mentioned in https://github.com/streetcomplete/StreetComplete/pull/5855#issuecomment-2323646736
@kmpoppe has 1 bar of 11 with it.
My android 14 shows this line with 9 of 12 visible bars.

alpha-4

![Screenshot_20240902-093458~2](https://github.com/user-attachments/assets/f85d87d3-549e-4c9a-bdba-902af596734b)

**Comment by westnordost** [comment]
The darker bar indicates how much you added in the last seven days. Although, the rendering should not look like that but the rounded rect should align with the rounded rect of the overall bar.

Any suggestions on the UI for showing the progress in the last seven days?

**Comment by matkoniecz** [comment]
Maybe just put label "dark green is how much was added in last 7 days"?

Without this it looks like a rendering bug and I would not guess that it is what is being shown.

Or drop it?

**Comment by goldfndr** [comment]
Perhaps append (+countNew) to the text if non-zero?

**Comment by westnordost** [comment]
> Without this it looks like a rendering bug

Well it currently is a rendering bug. The dark green area should appear as part of the progress bar, only tinted in a darker green. When this is fixed, would you still say that it looks like a rendering bug?

**Comment by kmpoppe** [comment]
Well I didn't guess that meaning either. I've just seen that this is also active for "by country" which, for me, is just a 1 pixel wide stripe.

![Screenshot_20240902_140946_StreetComplete.jpg](https://github.com/user-attachments/assets/b373bde1-9d98-4185-ba88-513085d450b5)

If that was incorporated into the bar it would be almost invisible I guess.

As you have a separate statistic for "the last 7 days" on the main profile page, it makes sense for the dark green parts also meaning the last 7 days but it's just not as obvious as I think it needs be.
I'd add an example bar at the top ("changes older than 7 days", "changes during the last 7 days").

K

**Comment by westnordost** [comment]
That'd be too many bars on the top. Thrice-nested navigation doesn't look good. Also, on landscape mode, this is already borderline to little space.

**Comment by HolgerJeromin** [comment]
With the country info I see in the tooltip overall (`#118`) and last7days (`#148`). Is that the info the dark green should show?

With the quest type info I still not understand what info should be visible (added screenshot in first comment as you all have already seen).

**Comment by kmpoppe** [comment]
> With the country info I see in the tooltip overall (`#118`) and last7days (`#148`). Is that the info the dark green should show?

No, the # are your rank, the dark green part of the bar is the part of the overall changes that you uploaded in the last 7 days - so light green + dark green = 100% of your changes to date.

**Comment by HolgerJeromin** [comment]
I think the problem with my account is: 
The last week is far less time compared to the other 21200 changes :-)

**Comment by kmpoppe** [comment]
Yeah, see also 3100 changes and like 9 in that week for me 😁

**Comment by westnordost** [comment]
So, the current visualization might actually be a bit demotivating, even?

Am 2. September 2024 19:55:59 MESZ schrieb Kai Michael Poppe ***@***.***>:

**Comment by kmpoppe** [comment]
Only stating for myself, I love the statistics, I don't draw motivation for working on anything OSM related out of them, though.

I'm merely wondering whether your intended purpose will work for all (most)  users. 
Judging by Holger's and my usage of the app it might be less useful after a certain amount of total edits, but might be totally fine for other users?

K

**Comment by HolgerJeromin** [comment]
Perhaps we need to switch to logarithmic scale once the week bar is smaler than 10 (?) Pixels.

>So, the current visualization might actually be a bit demotivating, even?

When the last week is so invisible compared to the whole contribution no few missing pixel will stop such an addicted mapper :-)

**Comment by westnordost** [comment]
I changed this now, there is no longer a second progress bar but instead a button on the lower right corner with which one can switch between overall and last-seven-days statistics.

**Comment by riQQ** [comment]
For reference: e4a019a720eb753e45454e6ea44f2afbb1d62c31
