### ISSUE TITLE
F-Droid repository seems outdated 

### ISSUE THREAD

**Issue by MarcinOrlowski** [streetcomplete/StreetComplete#5869]
The F-Droid seems to serve outdated version (v55.1, last update 9 months ago).

![Screenshot_2024-09-02-19-49-29-48_66a3b1c2c181ff92b8bf945e748b6fb7.jpg](https://github.com/user-attachments/assets/90e35319-cffc-47c4-ad7a-e27a8a912ea5)

**Comment by riQQ** [comment]
What phone / Android version are you using? Maybe support was dropped after v55.1.

**Comment by MarcinOrlowski** [comment]
Sorry, my bad. It seems all is up to date.

It seems my firewall tricked F-Droid there's no more recent index file to fetch.
