### ISSUE TITLE
Crossing Markings Quest - improve wording

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5872]
Currently the wording of the Crossing Markings Quest is pretty ambiguous, as it does not specify where the markings are supposed to be:

![Screenshot_2024-09-04-07-31-31-204-edit_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/bcd8b95e-cfe8-46df-a81c-17c678a3ed66)

Here are some examples, which are technically "markings":

![Screenshot_2024-09-04-07-35-47-365-edit_com google android apps maps](https://github.com/user-attachments/assets/68332ff9-e812-4e59-8389-2ab2c3a6d969)
![Screenshot_2024-09-04-07-36-46-217-edit_com google android apps maps](https://github.com/user-attachments/assets/d85d5690-bcab-483c-8856-7424c5146991)
![Screenshot_2024-09-04-07-38-00-025-edit_com google android apps maps](https://github.com/user-attachments/assets/c110ac8f-6767-4cb4-a45a-7dc0e7850f05)
![Screenshot_2024-09-04-07-38-43-812-edit_com google android apps maps](https://github.com/user-attachments/assets/d0d33231-7ea3-4871-a1f6-4386a0fdab97)
![Screenshot_2024-09-04-07-40-25-988-edit_com google android apps maps](https://github.com/user-attachments/assets/81c3f3a2-b880-4c03-a802-37ad6108f677)

But all of them doesn't fit the OSM definition of markings.

So the question should be more along the lines of "Does this crosswalk have painted markings of any kind across the road?"

### Version

SC 58.x / 59.x

**Comment by kmpoppe** [comment]
The source code currently says
```
        /* We only tag yes/no, however, in countries where depending on the kind of marking,
         * different traffic rules apply, it makes sense to ask which marking it is. But to know
         * which kinds exist per country needs research. (Whose results should be added to the
         * wiki page for crossing:markings first) */
```
I think this is part of the problem, there are currently no examples of "valid" `crossing:marking` values - i.e. pictures/graphics - in SC, which might lead to misunderstandings in what the correct answer to the quest is. If the diagrams from the wiki page were used to determine how the crossing is marked, all your examples would most likely be recognised as `no`.

I would argue that with 14 documented values (ignoring `yes` and all the `rainbow` ones which are listed as questionable) it wouldn't be a problem to just show all of them as diagrams and just let the user pick. If that results in 90% `zebra` (which taginfo would imply if it's not yes or no), so be it - of course there could always be the option "other" (which could tag `yes`) and "leave a note because it looks totally different".

**Comment by davidpnewton** [comment]
"I think this is part of the problem, there are currently no examples of "valid" crossing:marking values - i.e. pictures/graphics - in SC, which might lead to misunderstandings in what the correct answer to the quest is. If the diagrams from the wiki page were used to determine how the crossing is marked, all your examples would most likely be recognised as no."

There are in SCEE. There's a toggle to enable precisely those sorts of diagrams as an "advanced" mode of the system. So if they were wanted in Streetcomplete itself it would be trivial to implement.

**Comment by riQQ** [comment]
For reference, the SCEE implementation:

![Screenshot SCEE quest](https://github.com/user-attachments/assets/dee18af9-3a1b-462f-883b-3f32717758a3)

**Comment by westnordost** [comment]
SCEE implementation would be fine as soon as we know in which countries which crossing markings can exist. Someone would need to research that. Until then, I don't want to hear about it.

How about _"Does this crossing have markings on the roadway?"_ ?

**Comment by RubenKelevra** [comment]
> Someone would need to research that.

I'm happy to do the research for that for Germany. I think it would be necessary to do this on a country per country basis here, as this requires local knowledge and maybe some understanding of the language to look up legal documents on that matter - as it's hardly mapped at all atm. So we shouldn't stick to the OSM values currently in use here. 

I'll submit the results for Germany in a feature request.

---

Back to topic, 

> How about _"Does this crossing have markings on the roadway?"_ ?

I think it's better, but still missing the "across" part. Meaning that it crosses the travel direction of car traffic.

As some of my examples do have markings on the road surface, but none have markings across the car travel direction, which this tag is about.

So maybe just a bluntly state: "Does this crossing have markings on the road which goes across other directions of traffic?"

**Comment by RubenKelevra** [comment]
> > I'll submit the results for Germany in a feature request.
> 
> Hm, better put that in the wiki. It wouldn't make sense to change to use the SCEE-UI before not many countries are covered.

You mean OSM wiki? There's already a page for `crossing:markings` in German.

I thought we make a feature request and have people submit their countries, until it makes sense to implement?

> Or "Does this crossing have markings across the roadway?

That's fine!

**Comment by RubenKelevra** [comment]
I'll do a PR for the change :)

**Comment by davidpnewton** [comment]
At least so far as the UK is concerned?

For traffic signal controlled pedestrian crossings, whether standalone crossings or crossings associated with signal controlled junctions the only markings used are dots. That applies to pelican, puffin, toucan and pegasus crossings and crossings at junctions. A cycle only route across signal controlled junctions uses dashes.

For marked crossings without signal control the vast majority of them use zebra+dots. That's zebra crossings (yes that's right the UK zebra crossings  on public highways don't actually use "zebra" markings in the OSM sense!).

The rarer (much, much rarer) type are so-called parallel crossings, aka zebra crossings where cyclists are allowed to use a separate crossing alongside the pedestrian zebra crossing. That uses zebra markings for the pedestrian bit and dashes with pictograms at each kerb for the cycle bit.

https://www.legislation.gov.uk/uksi/2016/362/schedule/14/made

See diagram 1001.3 and down in that legislation for diagrams of the markings.

**Comment by RubenKelevra** [comment]
> Ok, please put such information in the wiki (in some consolidated, non-prose form). Linking to legislation is always a good idea.

Alright. I've looked a bit around for Germany, and I think I got an overview of what needs to be put into the wiki.

I guess it makes sense to at least open a discussion here, however to communicate about the effort. I'll do this instead.

Main issue for Germany is right now, that the wiki has less options than are actually in use in Germany, as we got mixed bicycle and pedestrian crossings, like this:

![640px-Kombinierte_Querungsanlage_Radweg_Zebrastreifen](https://github.com/user-attachments/assets/e52dfeaf-39a1-4cb7-a0cb-b0eebed836ab)

Which would be somewhat like`crossing:markings=zebra;surface+dashes`?

**Comment by RubenKelevra** [comment]
Here's the discussion:

https://github.com/streetcomplete/StreetComplete/discussions/5875

**Comment by westnordost** [comment]
> Main issue for Germany is right now, that the wiki has less options than are actually in use in Germany, as we got mixed bicycle and pedestrian crossings, like this

Uh, great. 😐 Kind of not thought out well, that tagging scheme. Will need to be discussed in the forum. But your example is really common, interesting that it didn't come up in the proposal discussion.

**Comment by mnalis** [comment]
> Which would be somewhat like `crossing:markings=zebra;surface+dashes+pictograms`?

No... If I understand that [wiki section](https://wiki.openstreetmap.org/wiki/Key:crossing:markings#More_difficult_cases) correctly, [that picture](https://github.com/streetcomplete/StreetComplete/issues/5872#issuecomment-2332023745) (very common in Croatia too for `segregated=yes` footway+cycleway) should be marked with `footway:crossing:markings=zebra` + `cycleway:crossing:markings=dashes;pictograms` _**instead**_ of using unprefixed `crossing:markings=*` with some homebrewed syntax such as that.
