### ISSUE TITLE
Minor visual glitch at bridges

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5876]
**How to Reproduce**
Use SC with MapLibre, move to https://www.openstreetmap.org/way/37667150 and see part of the Bridge on top of the road:
![Screenshot_20240901-130653_Street­Complete_Dev](https://github.com/user-attachments/assets/f050b516-7caf-4a40-b761-2be924681519)

At most bridges this will not occur, I assume what we see is the rounded line cap, but only if there is some angle between bridge edge and road that's far enough from 90°.

**Expected Behavior**
Bridge is below the road, like it was in 58.2.

**Additional information**
The problem could be related to z-order, assuming order is _road on bridge_ on top, then _bridge structure_, then _normal road_.

**Versions affected**
Android 10, SC 59.0-alpha2 (and SCEE with alpha4 merged)

**Comment by westnordost** [comment]
Bridge structures are rendered above non-bridge roads, unlike in osm carto where roads are **always** rendered above any structure. So, I don't think this is fixable.
