### ISSUE TITLE
If Font is enlarged (via Android accesibility settings) Map Copyright notice moves incorrectly towards the middle of the screen

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5881]
Following up on https://github.com/streetcomplete/StreetComplete/issues/520#issuecomment-2335156185, I've found that increasing `Font size` in Android settings results is map copyright notice moves inconveniently towards the middle of the screen, e.g.:
 
![small_Screenshot_20240907_163456_StreetComplete](https://github.com/user-attachments/assets/ea10f64e-4457-4abb-b7e0-47c77220b281)

**How to Reproduce**
- In Android settings, under `Accessibility` / `Vision enhancements` / `Font size and style` increase Font size to the max
- start StreetComplete
- map copyright is annoyingly on the middle of the screen

**Expected Behavior**
- map copyright would remain on the bottom of the screen, below zoom buttons

**Versions affected**
Android 14, StreetComplete `v59.0-alpha4`

**Comment by westnordost** [comment]
Heh, interesting. Will be looked at in frame of #5799
