### ISSUE TITLE
Adding restaurants, cafés and pubs to the internet access quest

### ISSUE THREAD

**Issue by Vuizur** [streetcomplete/StreetComplete#5885]
There currently exists a disabled-by-default quest asking for internet access, but it only asks for libraries and tourist accommodations. 

I think it would be great add restaurants/pubs/cafés as well, because this is easier to survey and at least in Germany there is a wide variety of yes/no answers.
And for people wanting to work from a café it is pretty useful, for example.

Another possible node to add to this quest suggested in a previous ticket was shop=mall.

**Comment by mnalis** [comment]
Although see https://github.com/streetcomplete/StreetComplete/pull/1620#issuecomment-547648419

**Comment by Vuizur** [comment]
Oh, I missed that PR... I guess I should ask at SCEE.

**Comment by Helium314** [comment]
For SCEE you don't need to ask, you can adjust the filter yourself and add whatever poi you like.
