### ISSUE TITLE
Tapping Location button from arrow to crosshair rotates north up instead of just untilting

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5886]
Correct me if I'm wrong, but I think on the change from Tangram to MapLibre, the action on tapping the location button has changed slightly. Tapping the black crosshair (or arrow) centers on location. Tapping the orange crosshair tilts and points in direction of movement and changes to the orange arrow. That's all the same as it was before. 

But I remember that tapping the orange arrow would just un-tilt the map, but keep the map rotated in the same direction (but no longer follow movement direction). The compass in the top right would rotate back to north on tap. This was helpful when walking down a road, because you could align the map in the direction of travel, then un-tilt with the arrow button if you want a flat view. Now you have to manually rotate the map in un-tilted mode, which is impossible with one hand. Sometimes tilted mode doesn't show what you want (especially with the user dot right in the center of the screen, rather than shifted towards the bottom when in arrow mode).

**Comment by westnordost** [comment]
I don't remember changing anything there. If it indeed worked as you described, it was by accident / coincidence / a small oversight.

**Comment by westnordost** [comment]
Actually, I **did** fix it, so I change it, thinking it was a bug. d00e885d

**Comment by westnordost** [comment]
Initially a bug or not, I understand that that this behavior was useful (insert mandatory XKCD comic about spacebar heating here), so I will revert it.

**Comment by westnordost** [comment]
This behavior might be non-straightforward to keep when I migrate the main screen to viewmodels, though, which may reverse my opinion on it, but for now, reverting to old behavior is fine.
