### ISSUE TITLE
Display osm objects without Wikidata tag.

### ISSUE THREAD

**Issue by petitminion** [streetcomplete/StreetComplete#5887]
Wikidata tag is very usefull to link wikipedia, wikimedia with osm. 

There is a tool to match wikidata to osm : https://wiki.openstreetmap.org/wiki/OSM_%E2%86%94_Wikidata_matcher

But it doesn't provide and fast way to check if local object are tagged with wikidata. Maybe adding a wikidata quest to show untagged object  could help editors to find local osm object that need to be tagged with wikidata id ?  

To find the object's wikidata id the user could use the commons android app.  A link into streetcomplete could allow to open the app ? 

Probably this quest should be disable by default.

**Comment by HolgerJeromin** [comment]
This issue tracker has a form for new quest.
Please use that next time.

* What objects do you have in mind?
* How to add this on the road?
* How to tag "no WD"?
* I am pretty sure most of the element here has no WD object...

**Comment by westnordost** [comment]
Yeah, this doesn't work for StreetComplete. See the [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md).

**Comment by petitminion** [comment]
@westnordost  could you elaborate ? Is it about  "Users are no experts" ?

**Comment by westnordost** [comment]
Mainly **🤔 No unanswerable quests**. Few objects have a wikidata object.

But yes, also 🐿️ Easy answer / 👨‍💻 Users are no experts / 💵 Valuable Surveyors, as the questions should be answerable quickly, without extra tools or knowledge, only being on-site is necessary.

**Comment by matkoniecz** [comment]
See https://map.osm.wikidata.link/map/ for tool designed to do this kind of editing.

Note how in nearly all areas only small part of objects will have wikidata assigned.

And not even "it looks like object XYZ has `wikidata=QXYZ` assigned, can you confirm?" would work well as you often have more complex cases and "no" answers would need to be recorded in external service.

**Comment by mnalis** [comment]
> Yes, https://map.osm.wikidata.link/map/ is tool designed to do this kind of editing.

That link is broken (404), correct one seems to be https://map.osm.wikidata.link/

**Comment by petitminion** [comment]
make sens, maybe asking to implement geolocalization to  https://map.osm.wikidata.link/ can make the trick to allow smartphone editing
