### ISSUE TITLE
Cycling on sidewalk (in both directions) answer is missing

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5888]
Thanks for adding back the differentiation of cycling on the sidewalk being allowed vs. a shared use sidewalk. (not sure when that happend, but it was missing a while) 

However there's an option missing:

Cycling on the sidewalk is allowed in both directions - on none side. Meaning: Riding on the sidewalk is not a one way.

The equivalent of "shared use path" however has such an option:

![Screenshot_2024-09-10-07-22-48-133-edit_de westnordost streetcomplete](https://github.com/user-attachments/assets/dfc086ac-6c16-40e1-acc1-3984345d0e29)

Btw: Wouldn't shared use sidewalk not be less confusing here?

**Use case**
We got sidewalks which are marked from both directions for usage with bikes:

![Screenshot_2024-09-10-07-29-08-179-edit_com google android apps maps](https://github.com/user-attachments/assets/323fc4bf-1838-432d-a30d-fabd3ab2f333)

**Proposed Solution**
Just another button. Not sure about the tagging thought.

**Comment by davidpnewton** [comment]
"Btw: Wouldn't shared use sidewalk not be less confusing here?"

No. Sidewalk is a term specifically referring to a path next to a road. There are plenty of unsegregated cycle tracks that do not follow the route of a road and are thus not "sidewalk" in any sense of the meaning of the word.

**Comment by RubenKelevra** [comment]
> "Btw: Wouldn't shared use sidewalk not be less confusing here?"
> 
> No. Sidewalk is a term specifically referring to a path next to a road. There are plenty of unsegregated cycle tracks that do not follow the route of a road and are thus not "sidewalk" in any sense of the meaning of the word.

I think you're missing the point here. The quest is regarding infrastructure along a road. So sidewalk is always the appropriate term here.

**Comment by lgommans** [comment]
> there's an option missing:
> 
> Cycling on the sidewalk is allowed in both directions - on [one] side

I had this same problem yesterday. Not sure which I ended up picking anymore, also because the effect seems virtually identical: you can cycle on the same path as pedestrians can walk on, either because a sign says it's ok or because a sign says it's a shared path. I'm also not sure how to differentiate between a path where it says "cycling ok" but means it only for one direction, and one where the same sign means both directions.

> We got sidewalks which are marked from both directions for usage with bikes:

The picture doesn't show anything that indicates both directions though? Since there is no oneway variant of it, it stands to reason that it means that, but honestly I wouldn't know

**Comment by RubenKelevra** [comment]
> 
> > We got sidewalks which are marked from both directions for usage with bikes:
> 
> The picture doesn't show anything that indicates both directions though? Since there is no oneway variant of it, it stands to reason that it means that, but honestly I wouldn't know

Well, that's on the left side of the road. If the sign is facing you, it means you're allowed to ride in this direction. 

I the other direction there's the same sign, just facing the other way.

**Comment by wielandb** [comment]
🎶 Now this looks like a job for me...🎶

I also thought about that when implementing that change, but thought it would clutter up the UI too much for the limited times I thought it would apply. If @westnordost is okay with it, I can implement that addition.

We should keep in mind that we still need to think about if theese options should be only enabled in certain countries, following my post on the forum that got out of hand a bit. :D

**Comment by westnordost** [comment]
Cool, yeah, I think it should be added (at the very bottom). I can imagine that it is a bit common in rural areas where there is just one path on one side of a rural road for both cyclists and pedestrians which however is not broad enough to legally force cyclists to use it.

**Comment by wielandb** [comment]
For tagging:
My intuitive way to tag it would be 
`sidewalk:<side>:bicycle=yes`
`sidewalk:<side>:oneway:bicycle=no`

**Comment by westnordost** [comment]
I guess it would be weird to have `cycleway:<side>:oneway=no` when there is `cycleway:<side>=no`, so your suggestion sounds good.

**Comment by RubenKelevra** [comment]
Thanks @wielandb
