### ISSUE TITLE
Quest Auto Select mode for streetcomplete'ing while cycling

### ISSUE THREAD

**Issue by a-0-dev** [streetcomplete/StreetComplete#5891]
**Use case**
I can cover much longer distances cycling than walking, and especially properties like surface condition/material, lanes, existence of seating etc. are poorly mapped deep in the countryside. Yet, commercial and free/OS apps strongly rely on these for navigation and more.

Currently, StreetComplete requires a lot of visual attention and interaction, so one basically must stop every second quest to answer them and will have a hard time selecting the next one while cycling.

**Proposed Solution**
In my opinion, the ideal solution would be to create a semi-automatic mode in StreetComplete which
- automatically selects a quest of a restricted set of types (not all types make sense, mostly existence of items like trash cans, banks, ... and surface quests)
-  presents it in an easily-legible manner with **big** buttons to answer / at best, does some short text-to-speech summary
- if possible (I know that is super hard and likely out-of-scope) allows voice-answering - be it with numbers (e.g. 3=asphalt) or at least for yes/no questions)

**Outro**
I'd be happy to discuss this with you. I know it's a fundamental change of how the app currently works and totally understand if this is too much for you or not in line with the scope of the app! Still, since the benefit to the OpenStreetMap would be so great, and your app already is as fantastic as it is, I didn.- want to miss the chance to propose this :)

**Comment by riQQ** [comment]
Regarding voice-answering:
- #4719

Somewhat related, rejected even though with smaller scope:
- #48
- #5680

**Comment by a-0-dev** [comment]
Thanks for the quick & helpful reply! I guess the feature request can then be closed as "out of scope", I agree. I'll head over to the SCEE project linked in last discussion you listed, maybe it's feasible for their app and community.

**Comment by mnalis** [comment]
Firstly, I'd highly **advise against solving quests while riding a bicycle**. Sooner or later, it will end badly (in better cases just with a broken phone, if worse, with broken driver). Mapping OSM details is just not worth it. If you are driving a lot where area is not well mapped, may I suggest enabling gpx recording (e.g. in [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd) or whatever), and:

- [video mapping](https://wiki.openstreetmap.org/wiki/Video_mapping) and uploading images to [Panoramax](https://wiki.openstreetmap.org/wiki/Panoramax) (from which the surfaces, missing POIs etc. can be mapped by you or by others later). That is lowest risk.
- [audio mapping](https://wiki.openstreetmap.org/wiki/Audio_mapping). Little higher risk, but much lower than trying to interact with a phone screen while driving.


> * automatically selects a quest of a restricted set of types (not all types make sense, mostly existence of items like trash cans, banks, ... and surface quests)

That is kind of already present. See `Settings` / `Manage presets`. You can make several presets, each containing certain quests only. Of course, you need to select which of the preset you want to use (computer can't really read your mind).

>  * presents it in an easily-legible manner with big buttons to answer / at best, does some short text-to-speech summary

Is it not easily legible and with big buttons already? Your Android built-in accessibility features should allow for enlarging fonts (and even text-to-speech, but I'd imagine it would be even harder to use _while_ riding a bicycle!) 

Anyway, it seems what you want would be a huge change for StreeetComplete, and thus likely not a good match. 
Have you perhaps considered that other apps might suit you better (if you cannot be discouraged from dangerous riding, which I'd still advise you to consider!)

E.g.  [OSMTracker](https://wiki.openstreetmap.org/wiki/OSMTracker_(Android))  seems to have interface with big buttons and short texts made explicitly for such purposes as easy and quick hitting? While it does not cover all the things that StreetComplete does, it does include most useful ones (like road types, surfaces, adding POIs, leaving audio notes etc).


> * if possible (I know that is super hard and likely out-of-scope) allows voice-answering - be it with numbers (e.g. 3=asphalt) or at least for yes/no questions)

also related to accessibility features. See related:
- https://github.com/streetcomplete/StreetComplete/issues/520
