### ISSUE TITLE
Feature: Display some relevant existing data for quests

### ISSUE THREAD

**Issue by laundmo** [streetcomplete/StreetComplete#5895]
**Use case**
I primarily thought of this due to tracktype and surface. I'd love to know, when selecting the surface, which tracktype the track already has.

I can imagine there are a few other quests where a way to see related information would be helpful.

**Proposed Solution**
In the dialog of the quest it already shows some metadata like the type of feature. I propose displaying additional data here, which would differ by quest and whether its known.

Heres some very limited initial ideas:
- Surface: tracktype
- Surface Quality: tracktype, surface

I'm sure there are a few more cases where this would be useful. It could also lead to noticing (slightly) wrong entries much more easily.

**Comment by laundmo** [comment]
Well, whst surface do i sepect for 2 compacted lanes with grass in between, it may be unclear whether to choose grass or compacted depending on how much of either there is. tracktype could be the deciding factor there, where 4 or 5 would be primarily grass, and lower primarily compacted.

But you may be right that seeing it in person should trump anything set before. But then there really needs to be some clearer guidance on which to select if a surface is mixed.

**Comment by matkoniecz** [comment]
in general, if you are unsure: leave a note with a photo

**Comment by laundmo** [comment]
i mean, sure, if i want to send dozens of notes a day. every second track without a surface here is some of the mixed variety which i had thought tracktype might help clear up

but yeah, i didn't properly consider that as someone local there, i should not rely on data entered from elsewhere.

**Comment by mnalis** [comment]
Mixed surfaces are always a challenge and are never going to be precise... 

If it happens rarely and in sections (e.g. compacted which has few grass-sections),  one solution is to split the way and mark each section with its own surface. However that does not work (or is not desirable) when such changes happen every few meters (or are intermixed all the time) 

Another option is to use more generic values for such mixed surfaces (like `Unpaved (generic)`), and SC will ask for `surface:note` where one can detail what is exact situation in appropriate level of details (e.g. from _"mixed compacted and grass"_ to _"originally compacted surface has deteriorated, and patches of grass are now covering from 20-50% of the path instead"_).

**Comment by matkoniecz** [comment]
well, for road with tracks and middle out of day grass it may be better to tag what is in tracks - but either way it would be probably better to discuss it on forum/in note
