### ISSUE TITLE
Names of street disappear on the map when there are a lot of unsolved quests (white dots)

### ISSUE THREAD

**Issue by meiphoo7-Mae** [streetcomplete/StreetComplete#5902]
Except from a few rare visitors I'm the only mapper in my area, so there are still a lot of unsolved quests. In the previous version of SC it seems that the number of dots was reduced artificially in order to be able to show the name of streets. In the new versions the map looks more crowded with dots and for most of the streets the names are not shown anymore, even when zoomed in to the max. For me this makes the app effectively unusable. Currently the only solution is disabling questions to make the map less crowded. But still I feel that the names of streets should be shown at all times.

**How to Reproduce**

Take any of the new alpha/beta versions and visit an area where there are many unsolved quests. If there's a large enough number of white dots the names of streets are not visible any more on the map.

**Expected Behavior**
Like in the previous versions that the names of the streets are visible at all times, no matter the amount of unsolved quests.

**Versions affected**

It happens in the alpha/beta 59 versions. Older versions are not affected.

**Comment by westnordost** [comment]
Not a bug, but I understand that because both the quest dots and on lower zooms the quest clusters block the display of road names, it can become difficult to orient oneself due to these missing names.

I'll have a look if it is possible to make the quests not block the display of road names.

**Comment by westnordost** [comment]
I was partly successful.

Pins must collide with each other and thus also collide with text, i.e. pins still hide road name text. However, the dots don't collide with text anymore and more importantly, the clusters that appear when zooming out don't collide anymore.

**Comment by meiphoo7-Mae** [comment]
Sounds good. I can't wait to test it in the next release.
Thank you!

**Comment by westnordost** [comment]
I also created a feature request up-upstream: https://github.com/maplibre/maplibre-gl-js/issues/4718

**Comment by HolgerJeromin** [comment]
@westnordost Did you reported in the correct repo?
`maplibre-gl-js` looks wrong. You opened other issues in `maplibre-native`.

**Comment by westnordost** [comment]
That's why I wrote up-upstream. New style properties are usually introduced in maplibre-gl-js first, then ported later to native.

**Comment by meiphoo7-Mae** [comment]
Bummer, that enhancement apparently didn't make it into version 59, or may be it did. But in either case it looks to me as if the situation has even worsened. About 1 in 25 streets has a label with a name.
In the meantime I doubt if it has to do with placement of dots or pins.

Please take a look at this screenshot:
![Screenshot_2024-09-18-21-49-34-66_8a0120479a21d3140f77758520f645bd](https://github.com/user-attachments/assets/af5b5d81-6459-4c37-94fd-89d3329147a5)

This is from SC v 59.0.
There's exactly one single pin on the street that forms the left part of the loop (and a few other pins in the vicinity at the bottom of the screenshot). There's plenty of space for a label with the name. Still no label.

Now take a look at this screenshot:
![Screenshot_2024-09-18-21-56-45-22_58502f6a51123cb1c0d46bb0f8141155](https://github.com/user-attachments/assets/676c2a02-5526-4722-9297-504900a9d066)

This is from SCEE v 58.22 (I didn't update SCEE right away, because better safe than sorry...)
The same street with one pin on it (and even more pins in the vicinity at the bottom of this screenshot than shown in the screenshot above) now has projected its name three times on it.

It looks to me this hasn't much to do with the number of dots or pins but that it is somehow a bug or an unsuitable choice of design in the placement of labels.
The algorithm responsible for placing the labels apparently wants to place the label exactly one time and at a predefined position and if that position happens to be occupied by something else then too bad: no label.

**Comment by westnordost** [comment]
It did make it in v59, but only really improves the situation when zoomed out - i.e. when quest clusters are visible, not the pins. See my last comment.

**Comment by westnordost** [comment]
>  In the meantime I doubt if it has to do with placement of dots or pins.

It does. You can confirm that by deselecting all quests in the settings so that there are no pins on the map.

You are right about that there is plenty of space someplace else to place the label, but apparently this is not how it works in MapLibre, i.e. the label is placed at a specific position and if that doesn't work because it would collide with another symbol, no different position is tried.
