### ISSUE TITLE
Most of the About screens are unreadable in dark mode in 59.0

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5906]
`Version` / `Credits` / `Privacy` screens are unreadable,  as the use black letters on dark grey background. It was normally readable in previous versions.

![small_Screenshot_20240918_190949_StreetComplete](https://github.com/user-attachments/assets/0b160593-7f92-4fc7-89ef-b53f62e54302)

**How to Reproduce**
- upgrade to 59.0 release
- use dark mode
- open menu / `About` / `Version` (or `Credits`, `Privacy`, etc.)

**Expected Behavior**
Expected that the text is readable (e.g. white letters on dark grey background)

**Versions affected**
SC v59.0, Android 14

**Comment by mnalis** [comment]
Also reproducible with SC `59.0` on Android 6. It worked normally in `59.0-beta1`

**Comment by westnordost** [comment]
> Also reproducible with SC 59.0 on Android 6. It worked normally in 59.0-beta1

Huh, damn, ... what even changed between v59 and v59-beta1? Mostly just dependencies...

**Comment by kmpoppe** [comment]
Pinned this issue to (hopefully) let observant reports know, that this was a known bug which has been fixed.

**Comment by mnalis** [comment]
as a workaround until next release, people can select text for copying, and it makes selected portion readable:

![small_Screenshot_20240925_162853_StreetComplete](https://github.com/user-attachments/assets/9847e452-2eb9-4f0d-ab20-8bf51fe55dad)

(or they can visit the [GitHub web releases page](https://github.com/streetcomplete/StreetComplete/releases/) if they have Internet available, of course)
