### ISSUE TITLE
no upload or download via wifi only via mobile data

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#5909]
For some time now I have not been able to upload or download tasks via wifi networks. I always get the message “Connection error while uploading/downloading answers/data. Try again later.” However, uploading and downloading via mobile data works without any problems.

**How to Reproduce**

Try to upload/download something while you are only connected to wifi.

**Expected Behavior**

Uploading and downloading do not result in an error message.

**Versions affected**

```
eOS 2.3        Android 13 SC v59.0-beta1
LineageOS 18.1 Android 11 SC v58.2
```

**Comment by tiptoptom** [comment]
Upland and download with Vespucci through wifi works for me.

**Comment by westnordost** [comment]
I see, interesting.

What about EveryDoor?

Are you able to download when not logged in?

Otherwise, do you have a debug environment? (I.e. Android Studio installed, project checked out)

**Comment by mnalis** [comment]
Do android permissions say that the StreetComplete has Internet access (e.g. `Settings > Apps & notifications > StreetComplete > Mobile data & Wi-Fi`)? Is `Data saver` perhaps enabled for the app? 

Only other idea is perhaps you have some VPN/firewall (like e.g. Rethink) installed, which could've set up have some per-app limits?

**Comment by tiptoptom** [comment]
> Do android permissions say that the StreetComplete has Internet access (e.g. `Settings > Apps & notifications > StreetComplete > Mobile data & Wi-Fi`)? Is `Data saver` perhaps enabled for the app?

In fact, I seem to have deactivated WiFi usage on my old device and when I transferred data, the setting also appeared on my new phone.

That's super funny. :joy: 
Sorry for the false alarm and thanks for the hint.
