### ISSUE TITLE
Ask for all equipment at `amenity=bicycle_repair_station`

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5910]
(As asked in https://github.com/streetcomplete/StreetComplete/issues/5870#issuecomment-2352615247 opening this as a new issues in correct template; also see there for previous discussions)

### General
Affected tag(s) to be modified/added: [service:bicycle:pump](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:pump), [service:bicycle:stand](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:stand), [service:bicycle:tools](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:tools), [service:bicycle:chain_tool](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:chain_tool)
Question asked: **What equipment is available on this bicycle repair station?**
Quest description shown: **If non-standard equipment not listed is available here, please leave a note instead. /  Select all that apply:**  

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary (yes, with [accepted](https://github.com/streetcomplete/StreetComplete/issues/5870#issuecomment-2332180185) exception on `chain_tool`  requiring a closer look)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
nodes, ways with amenity=bicycle_repair_station and
(
    !service:bicycle:pump
    or !service:bicycle:stand 
    or !service:bicycle:tools
    or !service:bicycle:chain_tool
)
```

**Metadata needed:** -

**Proposed UI:** Multiselect quest in style of `What can be left here for recycling?`, with 4 pictures (in two rows) with text corresponding to `Pump`, `Stand`, `General tools`, `Chain tool`.
 
However, while selecting an option would mark equivalent tag as `yes`, deselecting (as opposed to recycling quest which just ignores them) would tag it as `no` (to prevent quest being re-asked ad infinitum if not all equipment is present). 

On quest startup, quest answers should be pre-populated with existing data (e.g. if node is tagged only with `amenity=bicycle_repair_station`+`service:bicycle:pump=yes`, `Pump` answer should be pre-selected, and all others deselected). 

Also, preferably, if any `service:bicycle:*` tag was not present, quest should automatically be marked "dirty" (i.e. just like as if the answer has been modified by a user), as aborting quest is not the same as just clicking OK (OK will tag all non-selected answers as `=no`, even if initially they were just missing); but that is not requirement, just an idea.

(Also, once this quest is implemented, existing `quests/air_pump/AddBicyclePump.kt` could be modified to not ask for pumps on `amenity=bicycle_repair_station`, as it would be redundant.)

**Comment by westnordost** [comment]
Needs good pictures or icons. 

> On quest startup, quest answers should be pre-populated with existing data (e.g. if node is tagged only with amenity=bicycle_repair_station+service:bicycle:pump=yes, Pump answer should be pre-selected, and all others deselected).

The recycling quest doesn't have this, though. In general, the quest should behave similar as the recycling materials quest for consistency. If any changes (in usability, behavior) are made for one, it should be made for the other, too.

**Comment by mnalis** [comment]
> Needs good pictures or icons.

Agreed. I'm not sure if icons would cut it (beside `pump` and perhaps `general tools` I have no idea how it would even look). So, I'll repeat my [appeal](https://github.com/streetcomplete/StreetComplete/issues/5870#issuecomment-2333878463) to people interested in seeing this quest become reality:

>  If other people would help find [representative and appropriately licensed photos](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md#new-photos) for `pump` / `stand`/ `general tools` / `chain tool`; I can help with writing the quest itself as outlined in `4.2`.

Or of course if people can take their own photos which could be used, and would be clear and recognizable on small screen, that would be great too!

> If any changes (in usability, behavior) are made for one, it should be made for the other, too.

(Generally I agree; recycling quest would benefit there too I think. But I don't think that I'd be able to complete such task in Kotlin :crying_cat_face: )

**Comment by westnordost** [comment]
I think the pump pictures are not good, not recognizable enough as a pump.

Maybe there are better stand-pictures, or the text needs to be a bit longer to explain that you can affix your bike frame onto it while you work on it.

**Comment by westnordost** [comment]
https://commons.wikimedia.org/wiki/File:Station%C3%A4re_Fahrradpumpe.jpg looks fair, or otherwise the generic https://commons.wikimedia.org/wiki/File:Bike_pump.jpg would be fine, too.

The previous pump pictures were not good IMO because they were not well recognizable as a pump.
