### ISSUE TITLE
Bubbles with amount of solved quests and countries in My profile - back

### ISSUE THREAD

**Issue by michalskop** [streetcomplete/StreetComplete#5911]
**Use case**
In a recent update, the moving bubbles with type of quests ("by type") and countries ("by country") in My profile were replaced with a bar chart. For me, a regular user, and my partner, a heavy user, these were a killer feature gamifying the whole app and the process of mapping itself. So we are really very sad :-( these bubbles are gone.

**Proposed Solution**
a) return the bubbles back instead of the bar charts
or
b) add a possibility into the settings to display either the bubbles or the bar charts
or
c) add a switch directly to the screen with the charts to switch between bubbles and charts

**Comment by mnalis** [comment]
I feel you, my wife and kid also dearly miss the bubbles (and [I'm sad at their loss](https://github.com/streetcomplete/StreetComplete/issues/5595#issuecomment-2078248583) too).

Unfortunately, support for existing bubbles was missing when trying to make StreetComplete multiplatform - i.e. make it able to run also on iOS devices (iPhones etc), and not only on Android  (details could be found in https://github.com/streetcomplete/StreetComplete/issues/5595)

**Comment by westnordost** [comment]
See #5595 . They or something else playful and interesting _could_ come back - only someone would need to (be able to) implement it. In the meantime I tried my best to make the bar charts look nice. They are certainly more informative.
