### ISSUE TITLE
Rotation of pointer pin doesn't make sense

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#5919]
When the user's location is outside of the viewed area, instead a pointer shown at the border of the screen is shown that points at the direction into which the map needs to be scrolled to find the user's location.

This only works when the map is rotated north-up, for other rotations, the rotation of the location pointer pin doesn't make sense.

**Comment by peternewman** [comment]
Does this also resolve the issue where the pointer is often invisible/off-screen @westnordost or was that due to this bug anyway?

**Comment by HolgerJeromin** [comment]
@peternewman in my tests: yes. I can not have the marker offscreen anymore with the newest version

**Comment by westnordost** [comment]
Yes

Am 25. September 2024 23:00:38 MESZ schrieb Peter Newman ***@***.***>:
