### ISSUE TITLE
Crash on map interaction (v59.0)

### ISSUE THREAD

**Issue by vanMacG** [streetcomplete/StreetComplete#5920]
After updating to v59.0 I am no longer able to interact with the map.
The app starts fine and I can browse the settings and rest of the UI.I can even move the world map around. But as soon as the position is located and it auto zooms in, or when I manually zoom in, the app crashes instantly.
Downgrade to v58.2 and it works again.

**How to Reproduce**
Reproducible on my side. Doesn't matter if I update or make a clean fresh install.

**Versions affected**
I'm on Android 11 (LineageOS) and StreetComplete is v59.0

**Comment by westnordost** [comment]
Which device do you use?

**Comment by vanMacG** [comment]
> Which device do you use?

Samsung Galaxy S5 (klte)

**Comment by westnordost** [comment]
This device uses a Qualcomm Adreno 330 GPU. I fear you are affected by this issue in MapLibre-native https://github.com/maplibre/maplibre-native/issues/2206 which is outside our control. It is unclear whether this issue will be fixed (soon) as the MapLibre team focuses their efforts rather on newer devices.

For the time being, unfortunately you will be stuck on StreetComplete v58.x, there's nothing we can do.

**Comment by westnordost** [comment]
In F-Droid, you can select which StreetComplete version you would like to install. Otherwise (if don't use F-Droid), you can download the releases as APKs directly from the releases page here on github.

**Comment by vanMacG** [comment]
> This device uses a Qualcomm Adreno 330 GPU. I fear you are affected by this issue in MapLibre-native [maplibre/maplibre-native#2206](https://github.com/maplibre/maplibre-native/issues/2206) which is outside our control. It is unclear whether this issue will be fixed (soon) as the MapLibre team focuses their efforts rather on newer devices.
> 
> For the time being, unfortunately you will be stuck on StreetComplete v58.x, there's nothing we can do.

Ok. Thanks for confirming the issue and looking into it. I'll watch the upstream issue and give it a try if it'll be solved.

**Comment by vanMacG** [comment]
After updating from 60.1 to 60.2 the issue is fixed for me ❤

**Comment by westnordost** [comment]
Interesting, I didn't know that MapLibre folks fixed something in this regard. Thanks for the feedback! I guess the linked issue can be unpinned now.
