### ISSUE TITLE
Add option to disable "Whats the name of ..." for allotments

### ISSUE THREAD

**Issue by SlowMo24** [streetcomplete/StreetComplete#5924]
This is a continuation of https://github.com/streetcomplete/StreetComplete/issues/2186 as requested by https://github.com/streetcomplete/StreetComplete/issues/2186#issuecomment-2364984092 .

**TL;DR**

**Use case**

I think the name quest is important. Therefore I would like to keep it enabled. But there are many allotments in my vicinity and many of them don't have a name. I would therefore like to disable the quest _only for allotments_.

**Proposed Solution**

In the list where I can toggle tasks, add a sub-element to "What's the name of..." that says: 

- [ ] show for allotments

which can be toggled to turn it off for this land-use type (and maybe others?).

**Context**

There are two aspects from my personal experience that I would like to add to the discussion as context:

**Many allotments don't have a name**

What % of allotments actually has a name aka is it a relevant question? We cannot answer the question using OSM. If we could, the streetcomplete-quest would be completed. Globally [82%](https://taginfo.openstreetmap.org/tags/landuse%3Dallotments#combinations) of allotments are missing a name but this share highly depends on the location. In my vicinity, many allotments are just single plots between farmland. So while we can clearly see the StreetComplete effect in the Regierungsbezirk Karlsruhe or the city of Heidelberg, the main growth there happens in the `name:signed` tag:

[![image](https://github.com/user-attachments/assets/a8fc5334-71d4-40ff-81c2-78f47b617dd6)](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=key&time=%2F2024-08-21T07%3A00Z%2FP1M&key=landuse&value=allotments&types=node%2Cway%2Crelation&measure=count&groupByKeys=name%2C+name%3Asigned&adminids=-22027)

[![image](https://github.com/user-attachments/assets/1155f32f-b38e-48c2-a5e8-3a78117ec118)](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=key&time=%2F2024-08-21T07%3A00Z%2FP1M&key=landuse&value=allotments&types=node%2Cway%2Crelation&measure=count&groupByKeys=name%2C+name%3Asigned&adminids=-285864)

Every name is important and enriches the database. But the question of "How many `name:signed=no` are acceptable to have one additional `name=*`, before we consider the question as distracting?" arises.

Contrasting example of the city of Berlin that has very few areas of open field and where the quest may actually be relevant to categorise those remaining 272 OSM elements:

[![image](https://github.com/user-attachments/assets/f86a2d6c-37d0-4abf-a2b8-dda91648782b)](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=key&time=%2F2024-08-21T07%3A00Z%2FP1M&key=landuse&value=allotments&types=node%2Cway%2Crelation&measure=count&groupByKeys=name%2C+name%3Asigned&adminids=-62422)

**Are we trying to solve a OSM tagging scheme shortcoming?**

I think that the quest tries to circumvent a shortcoming of OSM (thereby enshrining it). I think this is a discussion to be held in the community forum, but is relevant for context here.
Most of the times, when allotments have a name, they carry the name of the organisation that manages it. Meaning the place actually does not have a name but displays the ownership and management body prominently. I (personally!) know 0 allotments, that have a proper name. So we should rather establish something like tagging these places with [club=allotments](https://wiki.openstreetmap.org/wiki/Key:club) which then certainly gets a name.

It could be that the question "Whats the name of..." should actually be "Is this allotment managed by a club or institution?" for allotments.

**Comment by goldfndr** [comment]
For the single plots between farmland, would excluding allotments=plot (and/or plots=1) suffice?

**Comment by SlowMo24** [comment]
> For the single plots between farmland, would excluding allotments=plot (and/or plots=1) suffice?

While [1.6%](https://taginfo.openstreetmap.org/tags/landuse%3Dallotments#combinations) of allotments have that tag globally, it would not help with the problem at hand. 0% of allotments have that tag in the Baden-Württemberg:

[![grafik](https://github.com/user-attachments/assets/e09cf823-01d8-4582-b4e9-8aa6a10889fc)](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=key&time=%2F2024-08-21T07%3A00Z%2FP1M&key=landuse&value=allotments&types=node%2Cway%2Crelation&measure=count&groupByKeys=name%2C+name%3Asigned%2C+allotments&adminids=-62611)

Baden-Württemberg is another strong case for my issue with the `name:signed` tag rising while the `name` tag stays relatively stable (assuming [`name:signed=no` which is true in 99.38% of the cases globally](https://taginfo.openstreetmap.org/keys/name%3Asigned#values)).

While your suggestion would be a good solution for single plots in between farmland (if it was used), it would fail for multiple adjacent private plots. My interpretation of the wiki documentation of [`allotments=plot`](https://wiki.openstreetmap.org/wiki/Tag:allotments%3Dplot) is, that it is meant to be used on a dedicated OSM object, not on the same way/OSM object as `landuse=allotments`.

**Comment by matkoniecz** [comment]
Have you checked how this stats look on a global scale? If situation there would be the same it would be quite obvious what should be done.

If that distortion is limited to this specific place it becomes less obvious what is the best solution.

**Comment by westnordost** [comment]
Are you worried about that answering that quest is too spammy (in some regions)? Or what exactly do you see as the issue?

IIRC the app also asks for the name of kiosks (any shops, actually), while at least in Germany it is rather rare that a kiosk has a signed name. I never thought this is a problem though. Answering that is has no name is really quick, so, not really an issue.

As per the original suggestion: It is not possible to have per-quest settings in StreetComplete. In SCEE it might be possible. So, at least in StreetComplete, the question would rather be whether names should *never* or *always* be asked for allotments.

**Comment by westnordost** [comment]
By the way, where did you get your profile picture from?

**Comment by mnalis** [comment]
> Are you worried about that answering that quest is too spammy

That is how I understood it... Although while it does seem the area have a lots of them, so it might get boring soon  - perhaps a 5-10 per kilometer walked in worst case scenario (in 12 minutes or so, provided there are very little other quests in the area)? Once a minute with 99.9% same _"no name"_ would sound demotivating (unless one was happy _"wow! free stars increase!"_ aspect of gamification :smiley_cat: )  

> It is not possible to have per-quest settings in StreetComplete. In SCEE it might be possible.

Just to confirm, in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) it is indeed possible to remove _"allotments"_ from the name quest (by going to `Settings` / `Quest selection and display order` and finding `What's the name of this place?` and clicking on the cog to the right of it) 

> in StreetComplete, the question would rather be whether names should never or always be asked for allotments

For StreetComplete, I see no good solutions for @SlowMo24 unfortunately.
 
It cannot be disabled per country (as it would disable whole quest for ***all*** names, not just for allotment names), and globally it does seem that over 18% of allotments currently have tagged name - the number that is likely to go up as  only 0.56% have `name:signed=no`. So it would make sense to me SC should continue to ask the name for allotments.

And most of `landuse=allotments` in that area seem to have no other tags that might potentially be used to exclude them from the name quest.

Also, splitting the quest in two (one for allotment names and other for all other names) would probably a bad idea (we don't want to get down that slippery slope which might eventually result in hundred different name quests, one for each tag)

**Comment by SlowMo24** [comment]
> It is not possible to have per-quest settings in StreetComplete
> It cannot be disabled per country 
> Also, splitting the quest in two (one for allotment names and other for all other names) would probably a bad idea
> Just to confirm, in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) it is indeed possible to remove "allotments" from the name quest

Thank you all for taking the time to explain. Yes, for me it was about spam, demotivation and nuisance (seeing >10 of these quests around you anywhere outside the city: https://overpass-turbo.eu/s/1RSH ). I'm very excited about the quest itself (because its so nice to see a new name on the map) and got annoyed that each time it pops up its just someone's datcha I have to visit off the main track to verify they didn't name it. But it's not life threatening, I can live with it and will try to focus on 

> "wow! free stars increase!" aspect

more :-) .

> Have you checked how this stats look on a global scale? If situation there would be the same it would be quite obvious what should be done.

Here they are but for me personally it does not provide much information. OSM is hyperlocal (certainly nothing new I can tell you ;-) ) and regional trends always fall under the bus for global analyses:

[![grafik](https://github.com/user-attachments/assets/5e856b3e-3983-4942-b493-00289d9612ae)](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=key&time=%2F2024-08-21T07%3A00Z%2FP1Y&key=landuse&value=allotments&types=node%2Cway%2Crelation&measure=count&groupByKeys=name%2C+name%3Asigned%2C+allotments&bboxes=-175.0804122%2C-77.915669%2C173.6756871%2C80.4165944)

> By the way, where did you get your profile picture from?

I can't remember the original source, somewhere [here](https://lens.google.com/search?ep=gsbubu&hl=de&re=df&p=AbrfA8o4IlDMakiks1QN8hTZtI41OuDWXlAW0BKJIouLq2AIvFqCYc1VVuJEeJFfll1kuDcM4uD7usVyGxYZtU_P7mu-IwnvZgzSPlAFEek1SIMoXn9G_Sh9PUw6tag8-_30zcySrhjrkNGeKbiEspdfJBW0KUcsf0aVdo2qHfVLAQaU1gKsyMvTCDz_LZQdhjRtM2LL9E6VRQe_4w%3D%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKREUzWmpaa1pqVmxMV014TlRRdE5HWmlZaTA0TVRSbUxXTXhOV05pWkRNNVltSTNaQklmTUROb00yTllVSFpYZUhOUlRVbG5SM0JuU1V4dVVESnZXSGxvTFVsNGF3PT0iLG51bGwsbnVsbCxbW251bGwsbnVsbCwiMi0wIl0sWyJhZjg1MzM0Yi1hMTAxLTQ5ZTEtOWMwYy03MWZkNjlkZGExYTAiXV0sbnVsbCxudWxsLG51bGwsbnVsbCxbImFmODUzMzRiLWExMDEtNDllMS05YzBjLTcxZmQ2OWRkYTFhMCJdXQ==)

**Comment by westnordost** [comment]
Hmm, not sure if I just by accident picked one that is not representative, but 

https://www.openstreetmap.org/way/1025386509

doesn't look like I'd expect allotments to look.

![imagen](https://github.com/user-attachments/assets/f3b77821-ea09-42b3-be3c-83655ea5f74d)

Auf deutsch scheint das so eine Art ... Gemeinschaftsgärtnerei(?) zu sein? In Hamburg weiß ich von einem Feld, wo der Bauer einfach so Parzellen vermietet (und sie als Service bewässert usw.) und man dann dort sein eigenes Gemüse anbauen kann:

https://www.openstreetmap.org/way/859280843

Mag das sowas sein?

Ich sehe aber auch, dass dies zumindest in diesem Fall auch als `allotments` getaggt wurde.

**Comment by westnordost** [comment]
Anyway, for the time being, I'll close this issue.

`landuse=allotments` is currently documented as explicitly not community gardens in the wiki. The picture above would probably be rather be a community garden according to that definition or a `landuse=plant_nursery` (horticulture, de:Gärtnerei).
(StreetComplete doesn't ask the name for neither.)

**Comment by mnalis** [comment]
Perhaps `Uhh...` answer of `It's community garden, not allotments` which would retag it with `leisure=garden` + `garden:type=community` might work, if that is as common misconception / mistagging as it seems?

**Comment by matkoniecz** [comment]
So far it seems localised to area around this town/city.

**Comment by SlowMo24** [comment]
> Anyway, for the time being, I'll close this issue.

yes, sorry if my [comment](https://github.com/streetcomplete/StreetComplete/issues/5924#issuecomment-2380576792) was not clear in that direction.

> Hmm, not sure if I just by accident picked one that is not representative

I don't have a formal assessment of the data quality (especially for that tag) in the area but I would guess you have picked a special example by accident. Allotments (in the non-organised form) are very common in this area while the organised form (Verein) also occurs regularly.

I agree that your image rather shows a mix of vineyards or fruit/vegetable farms, maybe intermixed with allotments. It should be redrawn/retagged :-). 

> landuse=allotments is currently documented as explicitly not community gardens in the wiki

There are so many shades of organisation. E.g. https://www.openstreetmap.org/way/95194971 is very close to a community garden but each member rents a plot...

> common misconception

I feel like the wiki and the tag in general could benefit from some effort to better define it and also define tags that cover other forms (organised, individual, community garden). But again this is nothing to be discussed here but rather in the community forum.

**Comment by matkoniecz** [comment]
>  but I would guess you have picked a special example by accident

it seems that there are many open notes in this area, disputing whether similar objects should be mapped as allotments

if there is confusion here maybe discussing tagging of them at OSM forum or tagging mailing list would help?
