### ISSUE TITLE
VAT identification number

### ISSUE THREAD

**Issue by vfosnar** [streetcomplete/StreetComplete#5933]
### General
Affected tag(s) to be modified/added: [ref:vatin](https://wiki.openstreetmap.org/wiki/Key:ref:vatin)
Question asked: **What VAT identification number does this place have?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam) - it's pretty common to have them signed on the outside here in Czech Republic, may be different in other countries
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:**

**Metadata needed:** 

**Proposed UI:**

- input box: VAT IN
- other answers:
  - it's not signed -> ref:vatin:signed = no - this is not being used but it's following the rules of composed keys https://wiki.openstreetmap.org/wiki/Key:*:signed
  - the place does not exist
  - ...

**Comment by matkoniecz** [comment]
I went through some small sample in https://commons.wikimedia.org/wiki/Category:Shops_in_the_Czech_Republic ( say https://commons.wikimedia.org/wiki/File:Praha_Haje_Arkalycka_Kik.jpg https://commons.wikimedia.org/wiki/File:2022-07-13_Praha,_Galerie_Butovice,_diskontn%C3%AD_prodejna_Action_02.jpg https://commons.wikimedia.org/wiki/File:Alza.cz,_Brno_(2).jpg ) but either it was not there or I missed it.

Where it typically is?

> may be different in other countries

I would assume that it would be Czech-specific, at least in Poland I have never seen it.

**Comment by Helium314** [comment]
> but either it was not there or I missed it

I would guess it's too small to see on these photos. Maybe left of the credit cards in https://commons.wikimedia.org/wiki/File:2022-07-13_Praha,_Galerie_Butovice,_diskontn%C3%AD_prodejna_Action_02.jpg or on the rightmost part of the entrance door in https://commons.wikimedia.org/wiki/File:Alza.cz,_Brno_(2).jpg


> I would assume that it would be Czech-specific

Judging by taginfo, it's also common in Germany and Hungary (and mostly a European thing)

> to be added tag is established and has a useful purpose

What is the useful purpose? Are there any consumers for this tag?

**Comment by vfosnar** [comment]
> I would guess it's too small to see on these photos.

It's pretty common to use a large enough font to see it from streetview etc., but it's not common on chain stores. I can take some pictures when I go for a walk.

> What is the useful purpose? Are there any consumers for this tag?

Talking OSM not right now, but can be useful to verify shop owners etc. in the future. I want to use it and I would be okay with implementing this quest myself.

**Comment by mnalis** [comment]
It is relatively common in Croatia (see e.g. https://user-images.githubusercontent.com/156656/220413690-951d7fd4-c41d-40f6-a7e4-b193a768c421.jpg), but the displayed `OIB` is not really in `ref:vatin` format, so it would be failing _"👨‍💻 Users are no experts"_ unless some per-country app logic was added (for Croatia, you need to add leading `HR` and any missing leading zeroes to pad the number to 11 digits) - and adding such logic for all countries would likely be failing _"🕓 Effort vs impact"_. [^1]

While I do add the tag myself sometimes, I must admit that big issue is satisfying StreetComplete's _"🤷 Useful purpose"_. I.e. are there any data consumers actually using it?

---

[^1]: It however might fit [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) which has more relaxed quest inclusion rules (e.g. requiring domain expertise from the user is fine). That being said, if you're using SCEE and you're comfortable with fixing the VAT ID format yourself, you might as well just use raw tag editor (in its Expert Mode) to add `ref:vatin` manually (which is what I do currently) 

    One advantage that quest over raw tag editor might have, would be if it implemented those formatting issues automatically, and checked the number validity (for Croatia, using [ISO 7064, module 11.10](https://en.wikipedia.org/wiki/Personal_identification_number_(Croatia))), but that puts effort through the roof if more than one country is to be supported.

**Comment by davidpnewton** [comment]
Utterly pointless for the UK. UK VAT numbers only appear on receipts, invoices and other financial paperwork. They cannot be surveyed. So I'd implemented disable it for the UK.

**Comment by HolgerJeromin** [comment]
> Utterly pointless for the UK. UK VAT numbers only appear on receipts, invoices and other financial paperwork.

Same in DE

**Comment by vfosnar** [comment]
![20240929_111104_lmc_8 4](https://github.com/user-attachments/assets/157c80e2-a947-4583-a9fa-6d40f4045647)

This is an entrance to a local pub, you can see both DIČ (VAT) and IČO (CZ & SK company identifier)

But sometimes the visibility us much worse, in the next photo it's at the bottom of the opening hours (otevírací doba) paper

![20240929_111036_lmc_8 4](https://github.com/user-attachments/assets/0cae90d0-23d6-4422-9e35-018c6527a154)

**Comment by westnordost** [comment]
> 🚧 Established tags / 🤷 Useful purpose

As others have mentioned, it's not clear what is the useful purpose to record this information in OSM. Currently, there are no users and it remains unknown what might be the users.

> 👨‍💻 Users are no experts / 🐿️ Easy answer 

Will be very country-specific. I.e. in some/most? countries, it doesn't make sense to ask because shops don't need to state this info publicly. In those countries where they have to state it, it's still expected to be somewhat hidden (e.g. some abbreviation used for VAT) and/or provided each in a different location. So, it may be difficult and cumbersome to note down that number.

> 🕓 Effort vs impact

Others have noted that apart from the information whether this quest should be asked at all for a country, the number as displayed on the sign might need to be prepended by some identifier to fit `ref:vatin`, which adds to the overall complexity to implement this. Is it worth the effort to implement? And then, is it worth...

> 💵 Valuable Surveyors

...asking mappers to note down this number for every shop they find (in a country where this quest is enabled)? I don't think so, see also "useful purpose".

So, all in all, it seems clear to me that it doesn't meed the quest guidelines. Some points of these guidelines are softened for SCEE, if you want to implement this yourself (and hence "🕓 Effort vs impact" doesn't count, because it is you who makes the effort), maybe this could fit for SCEE instead. Better consult their quest guidelines before posting a PR there, though.

**Comment by Helium314** [comment]
> Better consult their quest guidelines before posting a PR there, though.

The PR was actually already created before you closed the issue

**Comment by vfosnar** [comment]
Sorry for not responding to your comment earlier,

#### 1. it was pretty easy to implement
country specific validation:
```kotlin
return when (countryPrefix) {
    "CZ" -> vatin.length in 2 + 8..2 + 10 && vatin.substring(2).all { it.isDigit() }
    "SK" -> vatin.length == 2 + 10 && vatin.substring(2).all { it.isDigit() }
    else -> vatin.length >= 2 + 2 // Romania
}
```

#### 2. won't be enabled by default
I'd never want to make this enabled by default, as you said surveyor's time is valuable

**Comment by westnordost** [comment]
Cool, looks sleek. I am happy that you created a PR over at SCEE
