### ISSUE TITLE
Created notes with '&' in them show up immediately with whatever was after the '&'

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#5938]
**How to Reproduce**
Answer a roof-shape quest with **Uh...**, **Can't Say**, **Leave Note**, and put in "Hipped & gabled". 

A note will then show up on the object with the text of the note just being " gabled", even though the note in OSM is created is

> Unable to answer "What basic shape does this building’s roof have?" – house number 22: Detached House – https://osm.org/way/47098470 via StreetComplete 59.1:
> 
> Hipped & gabled

Example:

![image](https://github.com/user-attachments/assets/6974f33a-6128-4dcc-bd71-0f3fd9199d71)

And see https://www.openstreetmap.org/note/4460941#map=18/-27.515940/153.031070&layers=N

I haven't check if this happens with notes in other circumstances.

**Expected Behavior**
The OSM note should be created, the quest disappears, and nothing else shows in SC for that object.

**Versions affected**
SC v59.1 on Android 14

**Comment by kmpoppe** [comment]
I would assume that
https://github.com/streetcomplete/StreetComplete/blob/fc2645ee6f200566ff17bf9a52b6826a6364c27b/app/src/main/java/de/westnordost/streetcomplete/quests/note_discussion/NoteDiscussionForm.kt#L178
is to blame for that.

As the underlying TextView has autoLink=web enabled and the TextView's content therefore is treated like HTML, the text of the note's comment probably would need to replace the ampersand with it's corresponding html-entity (&amp;amp;).

**Comment by westnordost** [comment]
Thanks for the investigation! I'll look into whether it can be reproduced after I html-escape the text.

**Comment by kmpoppe** [comment]
FWIW, a simple replace might not be sufficient, you might want to regex replace only those ampersands that are NOT part of http(s?)... strings because those links might otherwise break. But that could also be too much effort?!

**Comment by mnalis** [comment]
> FWIW, a simple replace might not be sufficient, you might want to regex replace only those ampersands that are NOT part of http(s?)... strings

Yeah, it should first link-ify the string, and then html escape only remaining text (not links), so e.g. Note wih content:

`test&more at http://example.com/?q=test&page=1`

should probably first have URLs be converted to actual links like this:

`test&more at <A HREF="http://example.com/?q=test&page=1">http://example.com/?q=test&page=1</A>`

and then only the _text_ portions HTML-escaped to get to final:

`test&amp;more at <A HREF="http://example.com/?q=test&page=1">http://example.com/?q=test&amp;page=1</A>`


(but the actual way how to do that depends of how stuff is done in Kotlin/libraries; the above suggestion is from my perl / HTML::Element perspective)

**Comment by westnordost** [comment]
Well, turned out that the cause was something completely different.

**Comment by westnordost** [comment]
Also see https://github.com/pdvrieze/xmlutil/issues/241
