### ISSUE TITLE
Do not automatically remove amenity details in Places overlay when extra details are added via NSI

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5940]
**Use case**
Sometimes, some existing amenity/shop has lacking (e.g. no `brand`, `brand:wikidata` etc) details, or shortened (or slightly misspelled) name (e.g. `Raiffaisen bank` or `RBA` instead of correct `Raiffeisen bank`). 

Nice way to quickly remedy that is Places Overlay, where one just searches for correct brand in NSI, and all the ideal data (correct most popular name, `brand`, wikidata etc.) is filled in automatically!

That works **great** when existing amenity does not have much extra details, e.g. it only has `amenity=bank` (and maybe `name=*`).

However, if amenity had extra details (e.g. `amenity=bank` + `name=RBA` + `opening_hours` + `wheelchair` + `drive_through` + `bic`) when NSI for _"Raiffeisen bank"_ is selected, all those extra details (`opening_hours`, `wheelchair`, ...) are ***removed without question***, which makes using NSI for such improvements unusable (as it breaks more stuff than it fixes)

It seems to be because [shouldAlwaysReplaceShop](https://github.com/streetcomplete/StreetComplete/blob/85f2c9febdd5619d363c8065fb322a6bf995a080/app/src/main/java/de/westnordost/streetcomplete/overlays/places/PlacesOverlayForm.kt#L277-L284) gets triggered.

(Inspired by https://github.com/Helium314/SCEE/discussions/670#discussioncomment-10818963)

**Proposed Solution**

I would suggest that in such cases when **selected NSI does not change the type** of the feature, user should be presented with [confirmReplaceShop()](https://github.com/Helium314/SCEE/blob/a5043084be37f44bbe5bd5529b4d2e52157c1f5a/app/src/main/java/de/westnordost/streetcomplete/overlays/places/PlacesOverlayForm.kt#L297) dialog instead (that should happen automatically if `shouldAlwaysReplaceShop` is `false`), thus allowing them to choose to preserve all those pre-existing details like `opening_hours` etc.

Furher refinement to slightly reduce effort for mapper (but not strictly necessary) would be to set `shouldNotReplaceShop` instead if **both the feature type _and_ the name remain the same**, which would automatically preserve pre-existing data without even asking the user.

**Comment by westnordost** [comment]
The issue that lead to the current behavior of replacing the feature even when the name was not changed: #5195

Anyway, your suggestion sounds reasonable.

So the check would go

`(isFeatureWithName || wasFeatureWithName) && hasChangedFeatureType`

Do you want to implement this yourself?

**Comment by westnordost** [comment]
Ah I see you self-assigned this, cool!

A few hints:
- `Feature.isSuggestion` denotes whether it is a brand feature or not (e.g. Raiffeisen bank, ...)
- a `Feature` doesn't know it's parent (Raiffeisen bank -> Bank), but it does have an `id`, which is basically a path. E.g. for "Raiffeisen Bank (Croatia)", we have as `id` `"amenity/atm/raiffeisenbank-4d8c03"`
- [`String.substringBeforeLast`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.text/substring-before-last.html) might be handy
