### ISSUE TITLE
Support 'is mapped separately' for compressed air devices

### ISSUE THREAD

**Issue by meiphoo7-Mae** [streetcomplete/StreetComplete#5947]
**Use case**

Apparently since #3053 for fuel stations the question is asked if there's compressed air. The possible answers are yes or no.
I think it would be useful if the option 'is separately mapped' is added to the options, which for example is also available for separately mapped sidewalks. OSM supports the key 'compressed_air', so a separately mapped device is possible.

In the area where I map there are several 'larger' car service garages/auto shops that also have a fuel station. They do have a compressed air device but not necessarily at the actual fuel station. Sometimes it is even at the other side of the building for example near the entrance of the garage making it invisible for visitors of the fuel station. So an answer on the quest about the presence of the device at the fuel station itself is not entirely valid when the device is actually located elsewhere near the building because either 'yes' (there's a compressed air device) and 'no' (the device is not at the actual fuel station) are possible answers. The option 'is mapped separately' would solve this ambiguity.

**Proposed Solution**

As pointed out above I think I would be useful if the option 'separately mapped' is added to the options.
Edit: I can't find if this option is supported in OSM.

**Comment by matkoniecz** [comment]
Both in case of separately mapped compressor and not separately mapped compressor tagging is the same in OSM.

**Comment by meiphoo7-Mae** [comment]
Thanks for your answer and sorry to have bothered you. I should not have asked this.
The confusion is caused by an not entirely correct translation.
The original English version is: 'Is there an air compressor available here' while the translated version boils down to: 'Is an air compressor present here'.
Something being present at a location is different from something being available at a location.
In the current case: an air compressor which is located near but not at the fuel station is indeed still available, which means the correct answer would be 'yes'.
So, I agree with you.

**Comment by matkoniecz** [comment]
>  The confusion is caused by an not entirely correct translation.

In such case help would be highly welcome! See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app
