### ISSUE TITLE
"Actually, there is a sidewalk, but it is displayed separately on the map." - applied answer may be wrong, sidewalk may be only on one side

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5952]
`quest_accessible_for_pedestrians_separate_sidewalk` has

> Actually, there is a sidewalk, but it is displayed separately on the map.

wording.

If selected https://github.com/streetcomplete/StreetComplete/blob/9f6475f25b70e264e35f803c8cb19dba0b81fb1d/app/src/main/java/de/westnordost/streetcomplete/quests/foot/AddProhibitedForPedestrians.kt#L63 will apply `sidewalk:both=separate`

But sidewalk may be actually only on one side. Maybe adding `sidewalk=separate` would be better? Or just remove existing `sidewalk*` tags?

**Comment by westnordost** [comment]
`sidewalk=separate` is invalid tagging, as far as I know.

But yeah, the `sidewalk` tag could just be removed. The wording of the other answer would then also need to be changed to "Actually, there is a sidewalk". However, note that the sidewalk quest is disabled by default.

**Comment by matkoniecz** [comment]
> sidewalk=separate is invalid tagging, as far as I know.

AFAIK it is fine, and while `:left` `:right` `:both` may be preferred for extra detail, this is also accepted and in use and understood

see https://taginfo.openstreetmap.org/tags/sidewalk=separate#overview

**Comment by westnordost** [comment]
Actually, I like my proposal better. It also reduces unnecessary text length and gives the user the opportunity to specify it more precisely afterwards. (StreetComplete interprets `sidewalk=separate` as `sidewalk:both=separate`, and so do all other data consumers)

**Comment by westnordost** [comment]
I did that now
