### ISSUE TITLE
Handle man_made=pier to surface quest and / or overlay

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#5955]
**Use case**
I found myself on this way:
https://www.openstreetmap.org/way/322432187/history/7

```
bicycle=no
bridge=boardwalk
foot=yes
man_made=pier
surface=wood
```

I was surprised by the "gap" this "path" had in the surface overlay.
In the end I retagged it as `highway=footway` because it could not be described as ([wiki](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier)) 

> long, narrow structure extending into the water to afford a berthing place for vessels, to serve as a promenade

Even if the documentation is cautious to not require that definition all images are supporting that.

**Proposed Solution**
* We could at least add that to the surface overlay.
* But also we could add this to the surface quest.
* Perhaps we can add a menu entry to retag as `highway=footway` or `highway=path` (this is where the problems starts...).

**Comment by matkoniecz** [comment]
in this case I would say it is a bad OSM data, with missing `highway=footway` and it is beyond SC to fix it

> Perhaps we can add a menu entry to retag as highway=footway or highway=path (this is where the problems starts...).

note that some piers are mapped as areas but `highway=footway` should still be line

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/322432187/history is actually a good example of this complexity - here `man_made=pier` was removed by mapper (and it looks like likely correct edit)

in some cases it should not be removed

in some cases only part of linear pier should be marked as walkable

in some cases linear footway should be added within area pier

sometimes access tags need to be added

sometimes it will be cycleway, steps or service road or something else

and probably more complexity, I am not so familiar with sea-things

---------------------

this seems to complex to handle within SC
