### ISSUE TITLE
Unclear what to do when the pavement is already on the map

### ISSUE THREAD

**Issue by JeromeA** [streetcomplete/StreetComplete#5956]
Go to Oswestry road in Oxford, UK.
The quest shows the following: https://imgur.com/a/dHXIV0L

The current options are:
- add a new pavement (should I put no pavements to say that there are no pavements in addition to the ones already on the map? Should I put pavement on both sides, to confirm that the existing pavements are correct?)
- click on "uh?", which shows 3 options: No pavement at all, Differ along the way, and Can't say.

I saw in a separate github issue that there may be cases where StreetComplete offers the option to say that the pavement is already shown on the map, but it does not happen in this specific case, and maybe that's the problem here.

**Versions affected**
59.2

**Comment by matkoniecz** [comment]
when you tap on `?` marked side you should have option with orange arrow for separately mapped sidewalk, visible already on the map

here it applies for both sides

is it not available?

**Comment by JeromeA** [comment]
Yes, you are right, it does show this option. I was too confused to reach that point. Now that I see what this is changing on OSM (the separate value), it all makes sense.

Thanks!

**Comment by matkoniecz** [comment]
I guess it can be closed then, unless you have an idea what can be improved to prevent this confusion.

**Comment by mnalis** [comment]
Perhaps additional `Uh...` answer of `Pavement marked separately` (which just provided instructions, similar to `No pavement at all`) would've helped clear the confusion?

Or changing/extending the existing `No pavement at all` answer to `No pavement at all, or separate pavement` (with similarly extended description window when it is clicked), if extra answer is too much?

**Comment by JeromeA** [comment]
Having the app asking you about the pavement while the pavement is shown on the screen definitely calls for a click on the `Uh...` button.

I support the idea of adding a case to the `Uh...` list.

**Comment by westnordost** [comment]
I don't know. The interface has been this way for years and this is the first time someone got confused by it. We don't know whether this is a single occurrence or whether there is a general issue. After all, having once tapped on the "?" in the interface should already answer any uncertainty.

This is why I also don't quite understand why the "There is no pavement at all" - other-answer was added in the first place by @matkoniecz . By the way, it was also added for the cycleway quest, so such an "displayed separately on the map" option would need to be added there, too.
Anyone got a link to the issue in whose frame that other answer option was implemented?

**Comment by FloEdelmann** [comment]
* https://github.com/streetcomplete/StreetComplete/pull/3740

**Comment by riQQ** [comment]
When I started using StreetComplete I also didn't know initially that you have to tap both sides with the question marks. And it was the same for a friend I gave my phone to try out StreetComplete.

**Comment by matkoniecz** [comment]
> This is why I also don't quite understand why the "There is no pavement at all" - other-answer was added in the first place by @matkoniecz 

there was very significant number of notes, from various people that were opening notes instead of filling this data

**Comment by westnordost** [comment]
Hmm, so can we say the same about this case? (mapped separately)

**Comment by matkoniecz** [comment]
I have not really seen many confused notes. Will look through SC notes a bit and report back.

**Comment by matkoniecz** [comment]
From looking through https://antonkhorev.github.io/osm-note-viewer/#mode=search&q=StreetComplete&sort=created_at&order=newest&closed=0&to=20240818T000000Z&map=1/23/25 and https://antonkhorev.github.io/osm-note-viewer/#mode=search&q=separate&sort=created_at&order=newest&closed=0&map=1/22/0 it is not a common problem, at least it does not result in notes about this.

**Comment by westnordost** [comment]
Thanks, @matkoniecz . Then, I'll rather close this issue as "question answered" / "will not fix"
