### ISSUE TITLE
Wording is confusing: Cycling quest (sidewalk) 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5963]
Currently the wording in the cycling quest (for roads) is a bit confusing:

<img alt="Screenshot_2024-10-15-16-01-33-125-edit_de westnordost streetcomplete" src="https://github.com/user-attachments/assets/4719d347-d8d9-4324-bd64-a6d2483d7189" width="300">

One answer talks about the "sidewalk" while the other one talks about a "path". 

This sounds like these are different things, which they are not. Both means, from my understanding, that there's a sidewalk which allows cycling. One time as shared use path, one time with a "cycling is OK, but pedestrians have priority". 

**How to Reproduce**
Select a cycling quest for a road and tap on one side of the road.

**Expected Behavior**
I think "path" should be replaced with "sidewalk" to avoid confusion. 

**Versions affected**
v59.2

**Comment by FloEdelmann** [comment]
@RubenKelevra Note that I have reduced the display size of your screenshot (by using HTML and specifying the `width` attribute) so that the issue description is more readable.

**Comment by RubenKelevra** [comment]
Yeah, the term is correct. But for any mixed use way, not specifically for a sidewalk which runs along a road.

So the term would be right if we talk about a path along the shore line or through a park.

In this case we want to ask the users specifically if the sidewalk can be used by bicycles, and thus we should switch.

Especially since we ask specifically for info about the sidewalk in the other answer.

**Comment by westnordost** [comment]
Really can't say if the mention of "path" is really an issue. After all, look at the wording for `cycleway=track`. Native speakers would need to take a look at this.

**Comment by RubenKelevra** [comment]
Here's a rural design guide showing "shared-use paths":

https://ruraldesignguide.com/physically-separated/shared-use-path

And there's a clear destinction from "sidewalks":

https://ruraldesignguide.com/physically-separated/sidewalk

And "sidepaths" which have separations, but are mixed use:

https://ruraldesignguide.com/physically-separated/sidepath

**Comment by westnordost** [comment]
I asked for opinions in the OSM slack US language channel.

**Comment by westnordost** [comment]
In the OSM slack US #language channel, someone wrote that they'd call the first "shared-use sidewalk".

**Comment by RubenKelevra** [comment]
Yeah, that's also what I would call them.

**Comment by RubenKelevra** [comment]
Thanks!

**Comment by RubenKelevra** [comment]
The improvement didn't made it into the German translation.

Here's now "sidewalk" (=Bürgersteig) mentioned for the "it's okay to cycle" case, and otherwise there's no mention of the sidewalk.

This could lead to users erroneously choosing the case where the sidewalk is mentioned:

![Screenshot_2024-10-26-20-30-32-920-edit_de.westnordost.streetcomplete.jpg](https://github.com/user-attachments/assets/d6b9602c-0f7d-45af-9fdf-58b5e804db00)

**Comment by matkoniecz** [comment]
> The improvement didn't made it into the German translation.

see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

(you can search for "fuzzy" translations, it should find cases where original was tweaked, you can fix them and/or switch of fuzzy marker)

**Comment by westnordost** [comment]
Ich seh kein Problem mit der deutschen Übersetzung.
