### ISSUE TITLE
Wording + pictogram is confusing: Cycling quest (protected bike lane)

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5964]
I think the wording and the pictogram for protected bike lanes could be improved:

Currently it looks like this:

<img alt="Screenshot_2024-10-15-16-08-59-253-edit_de westnordost streetcomplete" src="https://github.com/user-attachments/assets/7f107fe6-e340-4c2b-80c2-d2fae0d24cc0" width="300">

The word "sidepath" could be confusing, due to the tag `use_sidepath=*` in OSM, which means that there's a seperate way next to the road, which the router should use.

I think we can drop it and call the option simply "protected bicycle lane". 

Regarding the pictogram: I think it gives the impression, that a protected bike lane needs to have different pavement, like a sidewalk would. 

This is not the case, as for the US as an example: They just paint them on, and add guards so cars can't drive there:

![pcyctrk_02_sanfrancisco_may10](https://github.com/user-attachments/assets/1611ce3b-bd72-43a1-a6a3-365588afc8a8)

[Source](https://nacto.org/publication/urban-bikeway-design-guide/cycle-tracks/one-way-protected-cycle-tracks/)

I think it would be better to split the pictogram in half vertically and show on one half a protected bike lane on the road with bollards and one half the current pictogram, to avoid this mixed signaling to the users. 

**How to Reproduce**
This dialog can be found when clicking on a road and then one side of the road, to add cycling information to it. 

**Versions affected**
SC 59.2

**Comment by westnordost** [comment]
"Sidepath" is the US-English word for (UK-English) "track" when it comes to cycling, as far as I know.

**Comment by RubenKelevra** [comment]
According to this rural design guide, "sidepaths" are mixed use, while being physically separated:

https://ruraldesignguide.com/physically-separated/sidepath

While "separated bike lane" are only for cyclists, so no mixed use and physically separated:

https://ruraldesignguide.com/physically-separated/separated-bike-lane

Since we set the tag `cycleway=track` if this is selected, I think the correct answer description isn't "sidepath or protected bike lane", but "separated (or protected) bike lane".

The examples for separated bike line also include this example of a protected bike lane:

![Screenshot_20241015_172602](https://github.com/user-attachments/assets/665d9995-336a-4e8b-bff2-a74fd90c7275)

**Comment by westnordost** [comment]
I asked for opinions in the OSM slack US language channel.

**Comment by mnalis** [comment]
> I think we can drop it and call the option simply "protected bicycle lane".

I disagree. "protected bicycle lane" would still hugely suggest to me it is a ***lane***, which I'd understand to be physically part of the same road, with same height,  etc. 

IOW, I'd certainly **not** consider _"protected bicycle **lane**"_ to cover **Sidepaths** (i.e. something on a elevated physical level, separated by kerbs, often different surface material, often shared with pedestrians, maybe even a line a bushes/trees/etc between it and a regular road lanes for motorists,  etc).

Thus, suggested change (removing _"sidepath or"_) would make it **much more confusing** for me (as a non-native speaker of English)

> The word "sidepath" could be confusing, due to the tag `use_sidepath=*` in OSM

Nah. Vast majority of SC users are not that familiar with such level of OSM tags intricacies (heck, even ***I*** am not quite familiar with that specific tag), and those who are, are also well adopted to determine what exactly is being tagged.

> I think it would be better to split the pictogram in half vertically and show on one half a protected bike lane on the road with bollards and one half the current pictogram, to avoid this mixed signaling to the users.

I don't think that making the display more complex would makes it easier for users. Perhaps fully changing that picture depending on the country being edited (like e.g.  `bicycle lane` is looking differently in different countries) might help; but I'm not sure if significant work (mostly of researching how it looks in each of the world countries) would be worth the effort. (Especially as even a single country might have multiple ways how it looks - which makes it even more important that full explanation `sidepath or protected bicycle lane` remains and is not shortened!)

**Comment by westnordost** [comment]
In the OSM slack US #language channel, someone wrote that they'd call a bike path along a road but beyond the curb (i.e. it's not a protected lane) a "roadside (bike|cycle)way".

**Comment by westnordost** [comment]
What would maybe also work (better than current wording) is to swap the order:

"protected bicycle lane or sidepath"

I.e. this makes "protected bicycle ..." adhere to "sidepath" too.

**Comment by RubenKelevra** [comment]
@mnalis yeah you made some good points, but given the displayed icon I must disagree. I think people are more inclined to select the most fitting icon, not the most fitting text.

A common example for me would be sidewalks with asphalt surfaces.

I select the asphalt surface and then the icon switches to showing stones on the pictogram, and I am every single time confused, why it selected "paving_stones", when I tapped asphalt, until I read "asphalt":

![Screenshot_2024-10-19-17-06-45-709-edit_de westnordost streetcomplete](https://github.com/user-attachments/assets/91035e06-55ea-4d7c-a039-1412582587ad)

So if we use a pictogram, instead of images it should represent both situations we're asking for IMHO.

**Comment by RubenKelevra** [comment]
> What would maybe also work (better than current wording) is to swap the order:
> 
> "protected bicycle lane or sidepath"
> 
> I.e. this makes "protected bicycle ..." adhere a bit to "sidepath" too.

Yeah, this brings out the detail, that it must be protected. I like that one.

How about asking the US person(s) on some example images what they would intuitively select, based on text and based on pictograms?

**Comment by westnordost** [comment]
After a discussion in the slack chat, the US English native speakers settled on "protected bicycle lane or bicycle path".

Mentioning "sidepath" or "roadside" is not necessary after all, because it is clear from the context that it is. Plus, neither of the two would make the path designated for bikes, so would need to add "bicycle sidepath" etc. anyway.

**Comment by westnordost** [comment]
Regarding the pictures: As long as "protected bicycle lanes" and "bicycle paths" are both tagged the same, there is no way to distinguish them and thus it doesn't make sense to have two different answer options. Latest in the overlay (or on re-survey), SC wouldn't know whether to display a protected bicycle lane or a bicycle path.

Showing both in the same image also would rather confuse than help.

Why rather show a bicycle path than a protected bicycle lane: Because there are many many more bicycle paths than protected bicycle lanes.

**Comment by RubenKelevra** [comment]
> Regarding the pictures: As long as "protected bicycle lanes" and "bicycle paths" are both tagged the same, there is no way to distinguish them and thus it doesn't make sense to have two different answer options. Latest in the overlay (or on re-survey), SC wouldn't know whether to display a protected bicycle lane or a bicycle path.
> 
> Showing both in the same image also would rather confuse than help.

I think you misunderstood my proposal regarding the image:

The idea was to have one option and one rectangle image, like currently, but split it with a diagonal line showing two things: A protected bike lane in one half and a bicycle path on the other half.

So you can tell, visually, that you should use it for protected bike lanes as well.

**Comment by westnordost** [comment]
I *did* understand it. I think it would rather be confusing because in the street side selection UI, the illustration is tiled. So, you'd end up with a kind of dashed appearance, switching between protected bike lane and bike path the whole way. 

And while it is indeed possible to have a different icon in the selection dialog than in the street side selection UI, so the icon could have this thing with the diagonal line, it then would latest be confusing when the illustration in the street side selection UI looks different than the selected icon. .oO("Where is my protected bike lane!")

**Comment by RubenKelevra** [comment]
Ah! Okay, yeah I thought just about this dialog, not about the visualization of the street.


Hm.


Yeah I think it makes sense to keep the current picture, while it's potentially confusing it's better than the alternative, until a tag for a protected bike lane emerges.

Thanks for the work you put into this, highly appreciated!

**Comment by RubenKelevra** [comment]
The improvement didn't made it into the German translation (="bicycle path or protected bike lane"):

![Screenshot_2024-10-26-20-29-45-823-edit_de.westnordost.streetcomplete.jpg](https://github.com/user-attachments/assets/a778b383-0601-4131-abbb-6c955f41cd15)

**Comment by matkoniecz** [comment]
the same as in https://github.com/streetcomplete/StreetComplete/issues/5963#issuecomment-2439694315

see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

(you can search for "fuzzy" translations, it should find cases where original was tweaked, you can fix them and/or switch of fuzzy marker)

**Comment by westnordost** [comment]
Ich seh kein Problem mit der deutschen Übersetzung.
