### ISSUE TITLE
Add surface=acrylic option for sports pitches

### ISSUE THREAD

**Issue by knkski** [streetcomplete/StreetComplete#5965]
### General
Affected tag(s) to be modified/added: [leisure=pitch](https://wiki.openstreetmap.org/wiki/Key:leisure), [surface=acrylic](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dacrylic)
Question asked: The question is already asked as **What's the surface here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Already implemented

**Metadata needed:** Not sure, common in the U.S.

**Proposed UI:** Add surface=acrylic to the list of options available when selecting the surface of a `leisure=pitch` element

**Notes**: Adding this as a "Quest suggestion", because it didn't seem like a feature or bug.

I'm a little vague on how to tag certain sports pitches, notably tennis courts and some basketball courts. I've inspected them while using StreetComplete, and I've left the quests unsolved for now. From what I can tell, the surfaces are acrylic, with concrete or asphalt underneath. It's hard to tell for sure without being an expert, but that's what visual inspection and the internet seem to think.

If there's another option that should be used instead like `surface=paved`, it would be good if StreetComplete could guide users towards that option. You can enter that, but it shows up as "Paved (generic)", which seems like it's a less-specific option, with a picture that is just bare concrete/asphalt. If that's the preferred option, maybe StreetComplete could change the input for `leisure=pitch` to show a different picture when answering `surface=*`?

Here's an example of a tennis court currently tagged as `surface=paved`, but should be tagged as `surface=acrylic` AFAICT:

https://www.openstreetmap.org/way/39153147

Here's an example of a tennis court tagged with `surface=acrylic`:

https://www.openstreetmap.org/way/362822900

[leisure=pitch taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations) doesn't show any results for combinations with `surface=acrylic` for some reason, even though it's more common than some of the tags shown

**Comment by westnordost** [comment]
Isn't this the same as `surface=tartan`? Or where is the difference?

**Comment by knkski** [comment]
From what I can tell, they're different. [Here](https://en.reformsports.com/how-to-choose-the-floor-for-a-tennis-court/)'s a site that lists them separately:

> - **Acrylic Tennis Court Floors**
>   - Acrylic courts are also preferred a lot on the ground of tennis courts due to its durable, performance oriented and hygienic properties. It is easy to apply and offers several color combinations and economic as well. Acrylic tennis court floor can be obtained by applying several layers reaching up to 2-6 mm thickness.
>
> - **Tartan Floor Tennis Courts**
>   - Tartan floor is a flexible floor type made of rubber EPOM granules and SBR granules. It is considered to be the best quality and most efficient floor type which can be used in the tennis courts. It can be applied as hot cast with a thickness around 6 mm and 20 mm.

**Comment by westnordost** [comment]
Most people, I think, wouldn't know when a surface is "acrylic". Is there also an easier word for this?

So I understand that "tartan" is "rubber granule". But what is "acrylic"? Smooth plastic?

**Comment by matkoniecz** [comment]
> [leisure=pitch taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations) doesn't show any results for combinations with surface=acrylic for some reason

4027 worldwide - https://overpass-turbo.eu/s/1SJy

**Comment by matkoniecz** [comment]
> But what is "acrylic"? Smooth plastic?

I think so

**Comment by knkski** [comment]
I also found [this PDF](https://www.itftennis.com/media/2169/surfaces-surface-types.pdf) from the International Tennis Federation that lists these types:

| Type                 | Description                                                                    |
|----------------------|--------------------------------------------------------------------------------|
| Acrylic/Polyurethane | Textured, pigmented, resin-bound coating.                                      |
| Artificial clay      | Sand-dressed and/or rubber-dressed surface with the appearance of clay.        |
| Artificial grass     | Synthetic surface with the appearance of natural grass.                        |
| Asphalt              | Bitumen-bound aggregate.                                                       |
| Carpet               | Textile or polymeric material supplied in rolls or sheets of finished product. |
| Clay                 | Unbound mineral aggregate.                                                     |
| Concrete             | Cement-bound aggregate.                                                        |
| Grass                | Natural grass grown from seed.                                                 |
| Hybrid clay          | Clay-dressed systems supported by a carpet matrix.                             |
| Other                | E.g. modular systems (tiles), wood, canvas.                                    |

Tartan isn't listed, not sure what to make of that. Here's also the wikipedia article about hardcourts in general:

https://en.wikipedia.org/wiki/Hardcourt

**Comment by westnordost** [comment]
I guess tartan is considered as a type of artificial clay in this document

**Comment by westnordost** [comment]
So, the names of surface choices (to distinguiish tartan from acryl) could be
- Acrylic resin (smooth plastic)
- Tartan (rubber granule)

**Comment by westnordost** [comment]
review of linked PR is welcome
