### ISSUE TITLE
Rendering Problems with Sidewalk and Cycleway Overlay 

### ISSUE THREAD

**Issue by Langlaeufer** [streetcomplete/StreetComplete#5973]
If someone changes the geometry of roads in osm then the white roads and overlayed colored sidewalks or cycleways are not aligned anymore. It seams the old road-geometrie is drawn in white over the sidepaths which are generated form the new geometry.

**How to Reproduce**
change the position of streets in OSM then reload the data in SC, select sidewalk or cycleway overlay

**Expected Behavior**
Use the new geometrie for both road and sidewalk or draw the sidewalk over the old roads

**Versions affected**
SC / SCEE 59.0-2

**Comment by Langlaeufer** [comment]
![Screenshot_20241018_093338_SCEE](https://github.com/user-attachments/assets/7ebdd0ec-a001-41a7-bdba-b03e73891aea)
![Screenshot_20241018_093309_SCEE](https://github.com/user-attachments/assets/53c50161-7ec9-4e9d-9840-4b141b54950b)

**Comment by matkoniecz** [comment]
Yes, map tiles in background can be outdated as they update slower. 

This should be fixed within few days. 

Currently map tiles that would update faster are not really available.

**Comment by matkoniecz** [comment]
In principle it may be possible to do it for high zoom, but would require to implement the same system twice. 

It is also likely to be much less performant.

If someone would be interested in implementing this, I would advise to open an issue first to discuss it. 

Note that there is active effort to achieve minutely updated vector tiles, funded by OSMF

**Comment by mnalis** [comment]
> Yes, map tiles in background can be outdated as they update slower.

That is the main problem, yes. See _[SC FAQ: "The map looks stale, how often does the background map get updated?"](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_map_looks_stale,_how_often_does_the_background_map_get_updated?)_ for details.

>  [...] or draw the sidewalk over the old roads

I was wondering about this specific suggestion for a partial fix / workaround, though. I would expect that the element being edited (i.e. sidewalks in this case; e.g. red in the pictures above) would be **rendered at the top**.

Instead, it seems that it is being rendered _**below**_ the Jawg base road layer. Is there a reason for that?

**Comment by Langlaeufer** [comment]
> Is there a reason for that?

I guess this looks nicer at junctions when you can hide the overlaps of the (sidepath) lines under the white road-filler.
