### ISSUE TITLE
amenity=funeral_hall

### ISSUE THREAD

**Issue by bwbuz** [streetcomplete/StreetComplete#5981]
**Use case**
There is no possibility to assign the above tag.

**Proposed Solution**
Please make an appropriate addition under the religious buildings.

**Comment by matkoniecz** [comment]
Do you mean building type quest? It asks about building type: and funeral hall may operate in dedicated building, in a repurposed garage or warehouse.

If you want to map places, you can enable Place overlay for mapping POIs (I expect funeral hall to be there but not checked).

**Comment by mnalis** [comment]
Yes, if you want to add missing [amenity=funeral_hall](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuneral_hall), you can do so via `Places Overlay`  (second icon from the right on the top of the map) - just click `+` and search for `Funeral Service Hall` (note that there also exists `Funeral Home`, which tags [shop=funeral_directors](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfuneral_directors) instead)

**Comment by bwbuz** [comment]
Thanks for the tips - I haven't worked with this overlay before - this is a solution for me. Kind regards
