### ISSUE TITLE
Visibility ways/colors in zoom-levels

### ISSUE THREAD

**Issue by thofrey** [streetcomplete/StreetComplete#5986]
**Use case**
Show for example overlay if ways have tag "lit" - but same for other overlays.

In version 58.2 the ways were shown red/green, even in a low zoom level. This way I could see a large area and make a plan where to go first. In Version 59.2 the overlay removes the colors much earlier, so I can see only small areas. Planning my way gets really hard, as I have no overview.

This feature request is valid for StreetComplete as for SCEE. 
As I did not found any issue in both github´s, I am not sure if this is an issue or a decision, so I propose it as a feature request.

Example 58.2 - Zoom before colors are removed - the whole village is visisble with colored ways
![streetcomplete-58-2](https://github.com/user-attachments/assets/997b6bd7-de20-4e08-a3da-6f1779116437)

Example 59.2 - Zoom when colors are removed - even a very small area has no colors anymore.
![scee-59-2](https://github.com/user-attachments/assets/a6d2d2d8-826f-4e9e-92e6-3ca208a36744)

**Proposed Solution**
The behaviour in version in version 58 was perfect for me.

**Comment by westnordost** [comment]
The two screenshots show different places

**Comment by thofrey** [comment]
Sorry for not marking it clearly. It shows the same place/village. 
Here the marking of from first screenshot used for the second. Verified behavior in SCEE 59.2 and StreetComplete 59.2. 

Village = Bietigheim/Baden.
![grafik](https://github.com/user-attachments/assets/09014861-4c8a-4f76-9e3b-8592649a4380)

Can you reproduce or have I overseen some setting?

**Comment by matkoniecz** [comment]
I faintly remember that maplibre counts zoom levels differently, so maybe minimal zoom level for overlays needs to be changed.

I can confirm that `lit` overlay appears later than I remember it appearing.
