### ISSUE TITLE
Advisory bicycle lane cannot be retagged into regular bicycle lane

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5988]
https://www.openstreetmap.org/note/4499785

**How to Reproduce**

Enable cycleway overlay

Be in area without advisory lanes

Find advisory lane

Try to tag it as normal lane 

Fail, likely because advisory/proper lane distinction is not tagged in areas without such distinction

**Expected Behavior**

I can retag advisory lane to regular one, or apparently badly tagged advisory lanes are shown as regular ones.

**Versions affected**

59.3

Android 10

**Comment by westnordost** [comment]
Why was it tagged that way in the first place?

**Comment by matkoniecz** [comment]
SC bug/missing feature. Poland has no advisory bicycle lane, but it can have ones with solid lane and with dashed lane.

AFAIK effect here is whether vehicles can cross it (say, to park on sidewalk or to change lane if bicycle lane is between car lanes). Maybe it can allow/block using it for overtaking?

User tagged it with old SC version that has not blocked advisory lanes in Poland, probably selected it as this road section has dashed lanes on bicycle lanes.

**Comment by westnordost** [comment]
Okay, I agree that when selecting "unspecific lane", the `cycleway:lane` tag should be removed.

**Comment by westnordost** [comment]
By the way, this was deliberate implementation, it was even tested. The comment was:

> does not remove any cycleway:lane tag because this value is not considered explicit

But I can't follow this reasoning. The "unspecified lane" option is, after all, not selectable in countries where a distinction between advisory lane and exclusive lane is made.
