### ISSUE TITLE
[v60.0-alpha1] Ugly text wrapping in main menu

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5993]
See screenshot:

<img alt="Screenshot_20241030-161329_Street­Complete.png" src="https://github.com/user-attachments/assets/70afec1d-d309-46a8-9c8f-b7c395bb994b" width="300">

Best case would be to avoid wrapping if possible. If there is not enough space, either move the whole item (including icon) to the next row, or hyphenate the text (e.g. "Ein- stellungen" or "Einstel- lungen" or "Einstellung- en" rather than "Einstellunge n").

**Comment by westnordost** [comment]
The second would be (only) solvable by inserting a shy hyphen into the translation.

On my phone, the items are displayed in two rows. Quick solution would be to change the min width of the items to be a little broader. But, of course, there'll always be a language with longer text. Anyway, the text should also be centered when wrapped.

**Comment by westnordost** [comment]
Hm actually, the buttons have a fixed width. So, that's odd (that it looks fine for me but not for you).
