### ISSUE TITLE
Do not show `roof:levels` quest on buildings where both `building:levels` and `roof:height` are present

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#5996]
Note: this is about a quest which I believe is disabled by default, so this feature request is low priority ☺

**Use case**
Here is a concrete example: https://www.openstreetmap.org/way/32603233
This building basically has the following tags:
```
building=office
building:levels=1
roof:height=0.5
roof:shape=hipped
```
However, on StreetComplete, the “How many levels above the basement does this building have?” quest appear (with precompleted `building:levels` as 1): it basically wants me to fill-in the `roof:levels` tag. This seems to me as a contradiction with what is explained in this section of the wiki: https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#Usage_of_height,_roof:height,_building:levels,_roof:levels

**Proposed Solution**
I would disable the “How many levels above the basement does this building have?” quest when both `building:levels` and `roof:height` are already present.

**Comment by westnordost** [comment]
Makes sense.

Also excluded from the quest buildings that have `height + roof:height` set.
