### ISSUE TITLE
60.0-alpha2 does not show correct version

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5999]
IIRC this was noticed in some previous alpha/betas too, but I don't recall if it was supposed to be fixed or if the cause was never found (I can't seem to find that issue now).

**How to Reproduce**
1. install 60.0-alpha2
2. click menu / `About`
3. see `Version v60.0-alpha1` (incorrect)
4. click on that `Version` line, and see correct changelog for `v60.0-alpha2`)

**Expected Behavior**
in step **3**, correct version `v60.0-alpha2` should be shown instead.

**Versions affected**
v60.0-alpha2 on Android 14

**Comment by HolgerJeromin** [comment]
Same here. You mean
https://github.com/streetcomplete/StreetComplete/discussions/5812#discussioncomment-10476258

**Comment by westnordost** [comment]
Yeah, I forgot to run the gradle task and/or forgot to make a clearn build.
