### ISSUE TITLE
Add POI has vertical offset

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#6003]
**How to Reproduce**

Select shop or things layer.
Add a new POI.

**Expected Behavior**

The new POI should be created exact in the crosshair.
But it is created 1cm above (position of the marker pin is correct).

**Versions affected**

v60.0-alpha2

**Comment by mnalis** [comment]
can confirm:


https://github.com/user-attachments/assets/d2785532-cbde-4918-b64a-7f73018dde71

**Comment by westnordost** [comment]
What, I thought I fixed that... hmm...
