### ISSUE TITLE
Is this clock inside a building? - clock is on the building

### ISSUE THREAD

**Issue by RedAuburn** [streetcomplete/StreetComplete#6006]
There should be an option for the clock being on the building

![Screenshot_20241113-173551_SCEE.png](https://github.com/user-attachments/assets/4e8ada0b-c783-4067-88da-866aca4902d1)

Photo of building: https://commons.m.wikimedia.org/wiki/File:Meridian_House,_Greenwich_High_Road,_Greenwich_-_geograph.org.uk_-_5035849.jpg

**Comment by westnordost** [comment]
Just answer "no". When it is on the outside of a building, that counts as outside.

A typical example for a clock that is inside a building is the clock(s) within a train station.
