### ISSUE TITLE
Ticket validator icon is confusing

### ISSUE THREAD

**Issue by dokutan** [streetcomplete/StreetComplete#6007]
The icon for `amenity=ticket_validator` in the things overlay is the generic vending machine icon. This is confusing, as ticket validators aren't vending machines, but are commonly placed near transit ticket and other (sometimes generic) vending machines.

I propose two solutions:
1. Reuse the existing ticket vending machine icon for ticket validators, this is not ideal but still better than the current icon.
2. Add a new icon for ticket validators.

**Comment by FloEdelmann** [comment]
StreetComplete uses the iD presets and its icons for the Things overlay, so please better discuss the issue in https://github.com/openstreetmap/id-tagging-schema. For reference:

* https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/ticket_validator.json defines icon `temaki-vending_machine`
* https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/vending_machine.json defines icon `temaki-vending_machine`
* https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/vending_machine/public_transport_tickets.json defines icon `temaki-vending_tickets`

**Comment by dokutan** [comment]
Thanks, i have opened https://github.com/openstreetmap/id-tagging-schema/issues/1387.
