### ISSUE TITLE
make addr:housenumber appear earlier on the map, especially for object-related quests

### ISSUE THREAD

**Issue by chrt223** [streetcomplete/StreetComplete#6010]
**Use case**
Most quests about objects depends on precise placement, a in many case, the street number is a very good hint for precise placement (especially if a GPS is not available).

https://github.com/streetcomplete/StreetComplete/issues/6009 makes is even more significant since many artifacts related to buildings/entrance (like camera) are positioned near the street number.

**Proposed Solution**
Provide an option to display street numbers when doing object-related quests.

**Comment by matkoniecz** [comment]
Do you mean addr:housenumber ?

**Comment by matkoniecz** [comment]
I am pretty sure these are displayed, at least when you zoom in. Can you show example of not displayed one?

**Comment by chrt223** [comment]
https://www.openstreetmap.org/node/2709957324

![address-quest](https://github.com/user-attachments/assets/9849fbf6-385c-404d-b182-7c93426ab6a5)
![object-quests](https://github.com/user-attachments/assets/bd1e33fb-5f35-4e1f-8788-af3be2216cfc)

**Comment by mnalis** [comment]
And do the housenumbers appear if you zoom-in **more**, @chrt223 ?

- (Possibly related to https://github.com/streetcomplete/StreetComplete/issues/5902 ?)

**Comment by chrt223** [comment]
> And do the housenumbers appear if you zoom-in **more**, @chrt223 ?

Oh, so true!

But these are shown **only if screen view covers less than 25m**.
Problem is that many areas, housenumbers don't exist and **interpolation was used to determine first/last numbers for blocks of 100m x 100m** (it's been done for entire cities, without `addr:inclusion` a decade ago).

These first/last housenumbers serve as an indicator of distance aren't available if you want to add an object at the middle of the block (either they don't appear due to insufficient zoom level, either they are outside the view).

=> In area were parcels of 10m to 20m are not uncommon, showing housenumbers at a 200m screen-view zoom-level would be saner (at least for some quests and in some areas)

**Comment by matkoniecz** [comment]
Maybe it is one more unintentional effect of "zoom levels have different meaning in new map renderer"

**Comment by mnalis** [comment]
> [...] as an indicator of distance aren't available

- relatedly, https://github.com/streetcomplete/StreetComplete/issues/5765 when implemented should also help for indicating distances

**Comment by westnordost** [comment]
So, I checked, and indeed with the maplibre style, the housenumbers appeared exactly one zoom level later than with the tangram style. I changed it so that it matches the previous behavior.

**Comment by chrt223** [comment]
Still not quite that.
It's an improvement, but even at this zoom level, housenumbers still appear too late (using the latest v60.0 version) :

Less than 100m per screen-height, and still no visible house number:
![nonum](https://github.com/user-attachments/assets/34df5a46-fbb6-410a-9fe4-cb674d61465c)


Below ~80m, they (finally) appear:

![num](https://github.com/user-attachments/assets/70774b9b-4ce7-4bb7-9902-8df402ef3f65)

... but it's too late.

Whatever the magic distance is, , it's should be > 110m (with a margin of error)

Because placing an object in front of StreetName 1035 when only 1001 and 1999 are visible already implies some approximation (We'd need a dynamic ruler to evaluate distance between two points). But if one of the `1001` or the `1099` marks isn't visible, it's unacceptably imprecise.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/maplibre-streetcomplete-style/pull/2 - it still needs rebuild, merging into new release and being released and updating phone app before you will see it
