### ISSUE TITLE
Allow "barrier permanently removed" to barrier quests

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#6015]
**Use case**

To make the city more bicycle friendly my city has removed some barriers and put some cover cap inside. 
So it is possible to put in again a bollard.

**Proposed Solution**
Right now I have to retag it via vescpucci.
Would be nice if this would be easier (for the simple cases: node on way) via SC itself.
Placing an entry in "er..." menu would be an option:
Looking at [Taginfo](https://taginfo.openstreetmap.org/search?q=barrier#keys) we could tag:
* [was:barrier](https://taginfo.openstreetmap.org/keys/was%3Abarrier)
* [removed:barrier](https://taginfo.openstreetmap.org/keys/removed%3Abarrier)

**Comment by mnalis** [comment]
I've looked at e.g. _"What type of barrier is this?"_ quest and it at least seems to have _"Uh..."_ /  _"It does not exist"_ answer. If that not adequate to tag a barrier which was removed? Or is that answer misbehaving (e.g. breaking geometry by removing whole node?)

Or do you think that changing the tag to `was:barrier=*` is more useful than just removing `barrier=*` tag?

**Comment by westnordost** [comment]
Deleting the node is already enabled on
- AddBicycleBarrierType
- AddBarrierType
- AddBicycleBarrierInstallation
- AddStileType
- AddTrafficCalmingType

It was missing for, I added it
- AddStepCountStile

For 
- AddBarrierOnPath
- AddBarrierOnRoad

we can't delete the node, because there are no tags on the node. It is the common node of a road with a barrier line. In StreetComplete, we cannot delete lines.

**Comment by matkoniecz** [comment]
> we can't delete the node, because there are no tags on the node. It is the common node of a road with a barrier line. So, the barrier line would need to be removed if the barrier really is no more. But in StreetComplete, we cannot delete lines.

and if there is no barrier then creating note is a good idea, it indicated a mapping error

the most common cause of this I have seen is putting `barrier=fence` on `landuse=residential` and then gluing landuse to roads

**Comment by HolgerJeromin** [comment]
Sorry missed the point that I got this problem with the barrier_opening/AddBarrierOpening.kt quest.
