### ISSUE TITLE
Add a toggle for quests when an overlay is enabled

### ISSUE THREAD

**Issue by Chepycou** [streetcomplete/StreetComplete#6018]
**Rationale**
When using some overlays, one could want to toggle off the quests in order to be able to click on the overlay target (buildings, roads ...) without having the quests also linked to these popping up. I haven't so far found a way of doing so.

**Use-case example**
An example of this would be when, using the building overlay, the user is setting the type of buildings that are quite small. In this case, the quests (like building color) pretty much cover the whole building, making it quite hard for him to tap the building itself. 

**Proposed Solution**
I'd personally just add a quest logo right next to the overlay logo, a simple press would add something like a diagonal bar onto the logo and hide the quest layer, leaving the user free to use the overlay. The user may re-enable the quests just by tapping the button again.

_PS : I actually use [SCEE](https://github.com/Helium314/SCEE) but thought this may be relevant in the main project also. Do I have to put the same feature request on their tracker or not (do they cherry-pick upgrades from this repo)?_

**Comment by FloEdelmann** [comment]
Another place to put such a toggle would be inside the overlay menu, because that toggle is only relevant while an overlay is selected.

> Do I have to put the same feature request on their tracker or not (do they cherry-pick upgrades from this repo)?

Usually SC updates are merged into SCEE after some time. So you don't have to repeat your request here. But you can of course suggest it there if it's rejected here.

**Comment by Chepycou** [comment]
> Another place to put such a toggle would be inside the overlay menu, because that toggle is only relevant while an overlay is selected.
Good point, I meant for it to be only shown when the overlay is on and to be displayed right next to the overlay icon : 
![1](https://github.com/user-attachments/assets/9bf02386-10a0-4f68-ac4d-b142e3553a28) ![2](https://github.com/user-attachments/assets/4cd91c73-96f9-495e-a8ea-6a76db09eb33).
Here is an ugly mockup due to my poor GIMP skills :point_up:

**Comment by mnalis** [comment]
>  When using some overlays, one could want to toggle off the quests in order to be able to click on the overlay target (buildings, roads ...) without having the quests also linked to these popping up. I haven't so far found a way of doing so.

Well, there are quest presets in `Settings` / `Manage presets`. You could create new preset (called e.g. _"no quests"_) and make it have no quests selected at all. Then when you want to hide all quests to have overlay-only, you'd switch to that _"no quests"_ preset, and  when you want your default (or any other) preset, you'd make that one active.

In SCEE, with quick button, changing preset is 3 clicks. Which is admittedly noticeably worse than your suggestion of single click, but still, it exists as an option, so might be usable if you are not switching between _"no quests"_ and _"want quests"_ ***constantly*** (and it does not use any extra screen estate, which is at premium on mobile, of course) . 

Of course switching presets also exists in regular StreetComplete, but it is 6 clicks instead, which might be significantly more annoying.

---

Also, see related:
- https://github.com/streetcomplete/StreetComplete/issues/5762
- https://github.com/streetcomplete/StreetComplete/issues/3827

**Comment by Chepycou** [comment]
Thank you, @mnalis, I see, 
The switch preset button in SCEE makes it actually quite usable (compared to the 9/6 buttons for presets).

Do you think it may be of interest to suggest the toggle on the SCEE feature request page ? I'm thinking that since the right-hand side ribbon already takes the right side of the screen, a toggle quests could easily be added in here (and fits more to the "Expert" audience).

**Comment by Chepycou** [comment]
Thank you, @mnalis, I see, 
The switch preset button in SCEE makes it actually quite usable (compared to the 9/6 buttons for presets).

Do you think it may be of interest to suggest the toggle on the SCEE feature request page ? I'm thinking that since the right-hand side ribbon already takes the right side of the screen, a toggle quests could easily be added in here (and fits more to the "Expert" audience).

**Comment by westnordost** [comment]
See @mnalis, in a nutshell, I am sure this came up in one form or another before. My answer remains the same.

- at least on small screens (where is this screenshot from, that's a humongous screen!), there is not enough space for an extra button there
- I am very cautious to add extra buttons to the main screen. That button would add no extra functionality that isn't already there, just a shortcut.
