### ISSUE TITLE
Simple location search and routing / navigation feature in-app

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#6026]
**User Story:**
As a user, I would like StreetComplete to navigate me to a previously searched destination so that I don't have to switch apps while solving quests to reach my destination.

**Use Case:**
When being in a foreign city/region, you almost always need a navigation app to reach a specific destination in the city. The route calculation and route display directly in the app makes it very easy for the user to follow a route and complete quests at the same time. 

**Function description:**
StreetComplete has an integrated magnifying glass symbol that can be used to access a search function. This searches the OSM database in the same way as the search on osm.org. When you select a result, the route to this result is calculated and then the route to it is displayed on the map as a discreet line.
To limit the function, only destinations within a certain radius can be selected.
Furthermore, it does not require any navigation instructions, distance information or similar. The function should only require the display of a line on the map to just follow virtually.

**Things to Discuss:**
- Does it require re-routing if you stray from the path?
- What is the maximum length of the route? (Target group: pedestrians, possibly cyclists - approx. 50-100km?)

It's similar to #3950 , #1757 , #5369 and others but with direct routing approach in the app itself.

**Comment by matkoniecz** [comment]
I would say it is going onto "it is mapping app, not navigation app". Starting to add navigation features and associated interface complexity seems clearly out of scope.

"Does it require re-routing if you stray from the path?" alone has a lot of complexity, but main risk is going further into OSMAND-type interface where you can do anything but new user can do nothing.

**Comment by mnalis** [comment]
Yeah, geocoding is a big task in itself, and routing is doubly so. It would be an incredibly huge task (even more so if it supported multiple navigation modes/vehicles and/or route deviation detection / route recalculation).

- As a possible workaround, you can create route in `.gpx` format (in [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd) on mobile, or [brouter](https://wiki.openstreetmap.org/wiki/BRouter), or [graphhopper](https://graphhopper.com/maps) on desktop or whatever) and use [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) to display that track (as requested in https://github.com/streetcomplete/StreetComplete/issues/1757) and even preload quests alongside it (as requested in https://github.com/streetcomplete/StreetComplete/issues/473)

- Another alternative is using your Android built-in split-screen or picture-in-picture functionality and display _**both**_ StreetComplete _and_ e.g. OsmAnd (or simpler app like  [Luftlinie](https://f-droid.org/packages/de.westnordost.luftlinie/)) _at the same time_ (either on equal screen split, or giving navigation app little or much smaller space)
