### ISSUE TITLE
Does this laundry provide self-service - doesn't disappear for the map after complication 

### ISSUE THREAD

**Issue by Blackkness7** [streetcomplete/StreetComplete#6027]
<!-- 

https://github.com/user-attachments/assets/426b6784-8918-4114-b387-b10719b979dd

**Versions affected**
V59.3

**Comment by burrscurr** [comment]
Could you please describe in more detail

- What happened (ideally, also add a link to the osm element for which this happened) and
- what did you expect to happen (e.g what should SC do in your opinion)?

**Comment by burrscurr** [comment]
Could you please describe in more detail

- What happened (ideally, also add a link to the osm element for which this happened) and
- what did you expect to happen (e.g what should SC do in your opinion)?

**Comment by matkoniecz** [comment]
Sounds like #4736 #4258  #4668 #4466 t #4466 #4124 #4086 (not sure do we have open issue for that right now)

@Blackkness7 which version of SC you are using? Is it some ancient one?

**Comment by mnalis** [comment]
> Is it some ancient one?

I've just updated  https://github.com/streetcomplete/StreetComplete/issues/5545#issuecomment-2502636497 as I've had similar issue (with SCEE 58.2) today. So, not that ancient; it should have both the logging and the supposed fix.

**Comment by matkoniecz** [comment]
then closing as duplicate of  #5545 which was reopened

**Comment by riQQ** [comment]
Duplicate of #5545
