### ISSUE TITLE
No map is displayed on Android 7.1 in SC 59.0+

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#6029]
No background map nor SC quests / overlays are being displayed at all on my device running Android 7.1 in newer (v59.0+) SC versions. Old versions (58.2 and below) work fine on the same device.

**How to Reproduce**
- Install the  SC 58.2 on device running Android 7.1
- see that everything works fine
- Install the SC 59.0 on the same device
- no map nor quests are displayed. Other elements (buttons, menus, intros etc.) work fine.

Screenshot  of SC 59.0 and its log, and Screenshot of SC 60.0-alpha2 in dark mode:

![small_Screenshot_20241128-123500](https://github.com/user-attachments/assets/eee00bba-6e2e-4343-864c-eda23492a5a4)![small_Screenshot_20241128-130812](https://github.com/user-attachments/assets/0f521275-d5e1-4dc0-8f1a-13a5cf69fdd9)

[SC59.0_on_galaxy_S2_log.txt](https://github.com/user-attachments/files/17947662/SC59.0_on_galaxy_S2_log.txt)

**Expected Behavior**
- It should work normally on Android 7. `app/build.gradle.kts` says we're `minSdk = 21`, which should be [Android 5.0](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels) or above.
- alternatively, if new versions are not supposed to work on older android versions, we should increase the `minSdk`

**Versions affected**
SC 59.0 to SC 60.0-alpha2, Android 7.1.2 (LineageOS 14.1) on Samsung Galaxy S2 ([GT-I9100](https://www.gsmarena.com/samsung_i9100_galaxy_s_ii-3621.php))

**Comment by westnordost** [comment]
Might be the same issue as #5599 #5528 #5554.

Could you try to install the certificates following the [FAQ entry](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0))?

If this doesn't solve it, then it must be an issue with MapLibre-native, since MapLibre was introduced in v59. Actually, quite likely, as with such old devices (2011!) the MapLibre team doesn't usually test.

**Comment by mnalis** [comment]
> Might be the same issue as https://github.com/streetcomplete/StreetComplete/issues/5599 https://github.com/streetcomplete/StreetComplete/issues/5528 https://github.com/streetcomplete/StreetComplete/issues/5554.

> Could you try to install the certificates following the [FAQ entry](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0))?

I have, but it didn't help. And it shouldn't be that issue anyway because:
- older SC 58.2 works, and it uses same https://tile.jawg.io  for fetching tiles. If those were TLS issues due to expired CAs, _both_ SC versions should be failing.
- app log indicates `[MapTilesDownload] Downloaded 17 tiles (445kB) in 1.4s`, `[MapDataDownload] Downloaded 852 nodes, 96 ways and 3 relations in 2.9s` etc. which should mean both tiles and data were successfully downloaded -- yet neither is being displayed.

> If this doesn't solve it, then it must be an issue with MapLibre-native, since MapLibre was introduced in v59. Actually, quite likely, as with such old devices (2011!) the MapLibre team doesn't usually test. A look in the logs might reveal the source of the issue.

That was my primary suspect too... However, I have since installed 2 different [MapLibre-native based](https://github.com/maplibre/maplibre-native/discussions/690) apps ([Transportr 2.2.1](https://f-droid.org/en/packages/de.grobox.liberario/) and [EVMap 1.9.6](https://f-droid.org/en/packages/net.vonforst.evmap/)) on that same device and they both display the map just fine. 

Perhaps those apps use different way to display the map, or different version of the library?

**Comment by westnordost** [comment]
They use version 10.x of MapLibre. A lot of things changed for 11.x, including a requirement for OpenGL ES 3.0.

Anyway, according to my information, Samsung Galaxy S2 doesn't support OpenGL ES 3.0. So, TBH I don't know why you were able to install this at all on that device, but in any case, this is not worth looking into.

**Comment by mnalis** [comment]
> Anyway, according to my information, Samsung Galaxy S2 doesn't support OpenGL ES 3.0. So, TBH I don't know why you were able to install this at all on that device, but in any case, this is not worth looking into.

Stock Samsung Galaxy S2 were released with older android version, but in the good old days those phones could be upgraded to CyanogenMod and later LineageOS, which is how this specimen ended up on LineageOS 14.1 (Android 7.1.2), which is why the app could be installed (it requires Android 5 or higher)

 However, as you note, it only support GLES 2.0 (according to [CPU Info](https://f-droid.org/packages/com.kgurgul.cpuinfo/)), so if that is no-go for newer MapLibre versions, than that is a wontfix...
