### ISSUE TITLE
Ref for recycling containers

### ISSUE THREAD

**Issue by NathanBnm** [streetcomplete/StreetComplete#6031]
### General
Affected tag(s) to be modified/added: Add [ref](https://wiki.openstreetmap.org/wiki/Key:ref) to [amenity=recycling](https://wiki.openstreetmap.org/wiki/Tag:amenity=recycling) + [recycling_type=container](https://wiki.openstreetmap.org/wiki/Tag:recycling_type=container)
Question asked: **What’s the identification number here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Same as for fire hydrants

**Comment by HolgerJeromin** [comment]
> has a useful purpose

Can you exlain this a bit? 

>  Easily answerable by any pedestrian from the outside but a survey is necessary

I am not sure if all of them have a ref in Germany.

**Comment by NathanBnm** [comment]
In France most of them have an identifier. I'm currently referencing them in my area and it would great if I could add it directly from StreetComplete.

These identifiers are useful for further maintenance. The containers are sometime moved and it could help to find them.

**Comment by FloEdelmann** [comment]
In SCEE, you should rather use the "general ref" quest and edit its filter, because the changelog message will be better: "Specify refs" rather than "Determine emergency access point refs"

**Comment by westnordost** [comment]
The stated useful purpose is not convincing.

Also, not all recycling containers have refs. There is also not a good reason for this, they are usually not anchored to the ground but can be replaced by others anytime.

Also, generally `amenity=recycling` + `recycling_type=container` are groups of container**s**, not single containers.
