### ISSUE TITLE
Open location in another app not working properly

### ISSUE THREAD

**Issue by Dhruv80576** [streetcomplete/StreetComplete#6032]
after long press on map it displays a option open in another application which doesn't open the desired location selected in another app.

**How to Reproduce**
Long press on the map and click open in another app, select another app like gmaps. Desired location in not pointed in that app.

**Expected Behavior**
It should point to the exact coordinates selected in that app.

**Versions affected**
v59.3

**Comment by matkoniecz** [comment]
note that it is possible that coordinates were mangled by target app

can you share location? is the same location opening well in say osmand/vespucci?

**Comment by westnordost** [comment]
Cannot reproduce. Neither with Organic Maps nor with Google Maps.

**Comment by westnordost** [comment]
no feedback, closing as can't reproduce.
