### ISSUE TITLE
Don't ask for roof shape (and possibly other attributes) for building=foundation.

### ISSUE THREAD

**Issue by RicoElectrico** [streetcomplete/StreetComplete#6035]
**How to Reproduce**

Go to the map when there's building=foundation
e.g. https://www.openstreetmap.org/note/3857526
**Expected Behavior**

You won't be asked about irrelevant details such as roof shape (there is no roof!), house number, levels count...
**Versions affected**

53.3, Android version unknown

**Comment by westnordost** [comment]
The answer is: "flat".

`roof:shape=flat`

The question is being asked, because the building had `building:levels=1`. The roof shape quest is asked for anything that has either ̀ roof:levels` or `building:levels` set.
