### ISSUE TITLE
The text in the undo edit menu is broken

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#6043]
**How to Reproduce**

Solve the quest and undo it.

<table>

<tr>

<th>

<img src="https://github.com/user-attachments/assets/d34d4962-3b12-407e-a902-3ce351d147a8">

</th>

<th>

<img src="https://github.com/user-attachments/assets/c5c98808-239a-4bae-856d-ee32b768ccd2">

</th>

</tr>

</table>

**Versions affected**

60.0 
Samsung A52 Android 14 OneUI 6.1

**Comment by westnordost** [comment]
Hmm, that's the name of the element changed. This description is shown in the normal quest form, too. But there, it displays fine?

I guess this is probably reproducible with any edit done in locale with cyrillic script?

**Comment by deevroman** [comment]
The problem is most likely not in the phone locale, but in the language of the name= tag. In the quest form the text is displayed correctly

**Comment by westnordost** [comment]
can you link the OSM id of an element with which I can reproduce this?

**Comment by deevroman** [comment]
https://www.openstreetmap.org/node/1693339456/history

geo:59.946265,30.511321?z=18
