### ISSUE TITLE
Cannot download via Fdroid 

### ISSUE THREAD

**Issue by andywillis** [streetcomplete/StreetComplete#6047]
404 error trying to retrieve the APK file

**How to Reproduce**
Search for Streetcomplete in Fdroid and try to install.

**Expected Behavior**
I expect the app to install.

**Versions affected**
58.2

Screenshot attached 

![Screenshot_20241222-181708](https://github.com/user-attachments/assets/b81f4fa7-88e9-4c52-925e-bb906585574a)

**Comment by rusty-snake** [comment]
Well, this does sound very much like an F-Droid problem and not an StreetComplete problem.

Did you tried to successfully sync the F-Droid repository index?

**Comment by westnordost** [comment]
You should report this at F-Droid, this has nothing to do with StreetComplete the app.
