### ISSUE TITLE
Quest suggestion: What is this fence made of?

### ISSUE THREAD

**Issue by CorruptComputer** [streetcomplete/StreetComplete#6051]
### General
Affected tag(s) to be modified/added: check [Tag:barrier=fence](https://wiki.openstreetmap.org/wiki/Tag:barrier=fence) to add [Key:material](https://wiki.openstreetmap.org/wiki/Key:material)
Question asked: **What is this fence made of?** (default off maybe?)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  - This one I'm not 100% on, often times entire neighborhoods will conform to the same fence type, but from neighborhood to neighborhood they may be different.
  - For example, these are all wood fences in the neighborhood, but the apartment complex to the north west has some metal fences: https://overpass-turbo.eu/s/1W9b
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Similar to how road surfaces are shown, a selection list with various materials pictured like:
- `material=wood`
- `material=concrete`
- `material=metal`
- `material=stone`
- `material=plastic`
- `material=brick`
- etc.

**Metadata needed:** 
Maybe sorting the fences by the most common already in that country? Not really sure.

**Proposed UI:**
Similar to this, but with the fence materials pictured instead:
![Screenshot_20241225-130447](https://github.com/user-attachments/assets/75443e01-632c-4587-b20b-8181f7ece2e1)

**Comment by matkoniecz** [comment]
What is the use of such data? Beyond "anything can be 3D rendered"?

**Comment by CorruptComputer** [comment]
What is the use case for "What basic shape does this building's roof have?" or "Whats this pole made of?" besides being able to more accurately render the map data? I think thats a perfectly valid use case.

**Comment by matkoniecz** [comment]
> "Whats this pole made of?"

there was some theoretical potential use, but if I would be deciding on this then I would remove this quest

> "What basic shape does this building's roof have?"

primarily 3D, but it is very major feature

**Comment by westnordost** [comment]
Closing because I don't see **🤷 Useful purpose** being fulfilled. "So that it can't be rendered" is not a sufficient reason, because this could be used to justify anything.

**Comment by rYR79435** [comment]
Could you add this request to SCEE, @CorruptComputer (if it doesn't exist over there already)? Thanks
