### ISSUE TITLE
Add more spacing between links in notes

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#6053]
**Use case**
When OSM Notes have multiple URLs (usually links to multiple SC pictures), those are very close together, making it hard to click correct one (in SC 60.0). E.g.

![small_Screenshot_20241227_154204_StreetComplete](https://github.com/user-attachments/assets/6cb557cb-85a0-4cdb-a843-7ad0f59a818c)

**Proposed Solution**
If there are multiple links in the Note one after another, add some vertical spacing between them.

Alternatively, one could increase spacing between all lines, but that would waste screen estate in other cases.

**Comment by westnordost** [comment]
The text from the note is just a plain string, though.

**Comment by matkoniecz** [comment]
And it is formatted into form with clickable links via allowing it in text field properties. Technically, starting to format it manually is possible but it opens entire warehouse of cans of worms.

**Comment by westnordost** [comment]
Not a warehouse... but still, usually there is not really a necessity to actually look at photos of a note when one is on-site oneself?

**Comment by mnalis** [comment]
> usually there is not really a necessity to actually look at photos of a note when one is on-site oneself?

Well, yes, because very often the note text is not descriptive enough and looking at the pictures is needed to understand what is actually being noted. Even this particular example "There are this 3 items" is problematic without looking at those 3 pictures. And if the note is freeform (i.e. created freely on the map and not as a response to a quest, it is often even more ambiguous)

**Comment by westnordost** [comment]
I added a note to the master ticket for the migration to jetpack compose that should be considered when the notes comments display is being migrated.
