### ISSUE TITLE
Clicking on image links in a Note sometimes opens the wrong links

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#6054]
At first I though it was just my fat fingers (see https://github.com/streetcomplete/StreetComplete/issues/6053), but it seems there is a bug _too_. Sometimes (it looks like first time a new image is clicked) it opens the wrong (previously opened) image, instead of the one that was clicked on.

**How to Reproduce**
- find a note with multiple links (e.g. https://www.openstreetmap.org/note/4470251)
- click on the first image 3 times. Notice that every time correct first image ([244956.jpg](https://westnordost.de/p/244956.jpg)) is being opened
- now click on the second image ([244957.jpg](https://westnordost.de/p/244957.jpg)). 
- notice that first image ([244956.jpg](https://westnordost.de/p/244956.jpg)) is incorrectly being opened instead!
- subsequent clicks on the second image seem to open second image ([244957.jpg](https://westnordost.de/p/244957.jpg)) correctly

Video:

https://github.com/user-attachments/assets/14012952-d3b6-4c64-8407-6a2df2f17e19

Especially telling is `00:00:29`, when I clearly click on third image ([244958.jpg](https://westnordost.de/p/244958.jpg)) yet first image  ([244956.jpg](https://westnordost.de/p/244956.jpg)) is being opened, when there could be no "fat fingers" issue.

**Expected Behavior**
It should open the image I clicked on every time. 

AFAICT It used to work correctly in the past; but I'm not sure in which version it broke exactly. (Bug is also present at least in SCEE 58.2). 

**Versions affected**
SC 60.0, Android 14

**Comment by kmpoppe** [comment]
As note 4470251 is now closed, I tried replicating it with https://www.openstreetmap.org/note/4470202, where there's a link to the node and one image, and could so do (v60.0) as described by @mnalis. It seems that after that the url-to-open is "lagging behind" until another quest is opened - when going back to the note then, the correct url opens upon first click again, and then breaks immediately.

**Comment by westnordost** [comment]
Does this only occur when opening the links from the android app, or also when opening the links from the browser?

**Comment by westnordost** [comment]
Only from the Android app.

I can kind of reproduce it, I think, maybe it is just fat fingers. If it is not, this seems to be rather a bug in the `autoLink=web` feature for TextView. I am not sure if anything can be done about it, and anyways, this is still the Android view code, i.e. would be reimplemented (differently) in compose anyway hopefully sooner or later.

**Comment by kmpoppe** [comment]
I'm pretty sure it's not fat fingers because the two links in the note I used are spaced apart quite a distance.
If it's an Android View error, I'd also guess we're lost.

**Comment by westnordost** [comment]
lost, until that part is being refactored to compose. That is something that could be done any time (after all, the migration is done bottom-up, so the note discussion thing as a whole can still be android-view-based, but the list of user comments could already be a compose widget)

**Comment by kmpoppe** [comment]
That's something I must yield to your expertise, if that's something that could be done, the better :)

**Comment by matkoniecz** [comment]
I think it is more of invitation to help with migration to Compose

**Comment by westnordost** [comment]
(will not fix in current implementation, need to look at it after migration to compose)
