### ISSUE TITLE
Error when uploading for deleted element

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#6060]
**How to Reproduce**
1. download data for an area
2. delete an element in that area using a different editor and save changes to OSM
3. delete the same element in SC (probably could also edit tags)
4. see "Upload error" dialog, with the error being
`de.westnordost.streetcomplete.data.ApiClientException: Client request(POST https://api.openstreetmap.org/api/0.6/changeset/xxx/upload) invalid: 410 Gone. Text: "The node with the id yyy has already been deleted"`

**Expected Behavior**
The error should be treated like other modifications of that element (throw a `ConflictException`, which will be handled by discarding the edit)

**Versions affected**
SC 60.0 (F-Droid)

**Comment by matkoniecz** [comment]
`StreetComplete/app/src/main/java/de/westnordost/streetcomplete/data/osm/mapdata/MapDataApiClient.kt` suggests that it is supposed to be covered:

```
                // current element version is outdated, current changeset has been closed already
                HttpStatusCode.Conflict,
                // an element referred to by another element does not exist (anymore) or was redacted
                HttpStatusCode.PreconditionFailed,
                // some elements do not exist (anymore)
                HttpStatusCode.NotFound -> {
                    throw ConflictException(e.message, e)
                }
```

though 410 is 

`public val Gone: HttpStatusCode = HttpStatusCode(410, "Gone")`

has OSM API changed behaviour on such edit conflicts by any chance?

**Comment by matkoniecz** [comment]
I guess that adding here one more clause is easy, most of fun is testing

**Comment by matkoniecz** [comment]
per https://wiki.openstreetmap.org/wiki/API_v0.6 412 PreconditionFailed appears when way (etc) is trying to be uploaded with deleted nodes, while 410 Gone appears when trying to directly edit deleted element
