### ISSUE TITLE
Map will not display

### ISSUE THREAD

**Issue by thebiblelover7** [streetcomplete/StreetComplete#6064]
The map will not load at all. Quests will load, but no map.

**How to Reproduce**
Open StreetComplete, wait a couple minutes and observe that there is no map loaded.

![Screenshot_20241230-105255](https://github.com/user-attachments/assets/114ade81-ad6e-49de-b9eb-41bd4b78b0c8)

**Expected Behavior**
Map should load

**Versions affected**
Android 15; Pixel 6; StreetComplete v60.0

**Comment by westnordost** [comment]
Not reproducible. The maps are from jawg.io. Don't the maps from jawg.io work at all for you on your smartphone? E.g. 
https://www.jawg.io/en/maps

**Comment by thebiblelover7** [comment]
Hmm... that is really weird... now, opening StreetComplete and jawg.io work.... I can't reproduce it either now... It must have been my internet connection, even though I tried with VPNs, and just normal data...

Thanks for your help :)

**Comment by matkoniecz** [comment]
or maybe jawg.io server had some short hiccup and was not working?
