### ISSUE TITLE
Street parking showcase is mirrored

### ISSUE THREAD

**Issue by FitikWasTaken** [streetcomplete/StreetComplete#6065]
It's supposed to show sidewalks on the sides and the road in the middle, however it shows them mirrored for me. (With road on the sides and sidewalks in the middle)
![Screenshot_20241230-165328](https://github.com/user-attachments/assets/a6168b0f-8078-450a-95f8-3df65476efb1)
![Screenshot_20241230-170627](https://github.com/user-attachments/assets/d74cd770-f036-452a-b673-4b58343d4011)

**How to Reproduce**
I'm not sure, ever since I've downloaded the app it has been this way, other overlays like sidewalks work fine. I thought it might have to do something with my app language being Hebrew, but I've changed it, and it's still broken.

**Expected Behavior**

**Versions affected**
Android 14
SC 60.0

**Comment by mnalis** [comment]
I'm not sure I'm quite understanding the issue, but are you saying that _"road on the sides and sidewalks in the middle"_ because on lower half of the screen (in Overlay window where you're choosing answers) the middle is colored light grey and  left and right sides of it are dark grey?

If so, it is likely because of the dark mode being used. 

If you go in menu, choose `Settings` then `Theme` and then choose `Light`, do the colors look more sensible to you then?

**Comment by westnordost** [comment]
Sidewalks? This is the overlay for parking. There are no sidewalks here.

**Comment by westnordost** [comment]
The dark gray is the road. There are no sidewalks in the parking overlay 😀

**Comment by mnalis** [comment]
> There are no sidewalks in the parking overlay

Well, in (second subquest) answer `Partially on the street` in parking overlay, there is an assumption that ***another*** part of the car is **not** on the street but on adjacent surface,  which is (at least over here) in majority of the cases indeed sidewalk... The picture even shows car parked half on the street, and another half on the other differently colored surface (e.g. sidewalk).

> The dark gray is the road. 

Yes, road is dark grey in `Light theme`, where I understand @FitikWasTaken was not confused.

In `Dark theme` however (See pics at the top of the issue in original report) where the confusion arised, the colors are inverted, i.e. road is light gray (and sidewalk is dark grey).

---

I'm thinking the suggestion is to keep road & sidewalk colors the same in both light and dark themes - i.e. always use dark grey for road, and light grey for sidewalk. 

That might work IMHO and be less confusing?

**Comment by mnalis** [comment]
E.g. change dark mode from current:
![dark_old](https://github.com/user-attachments/assets/ebd54bb5-45f8-466d-b182-deb29a83779a)

to something like this (quick mockup, excuse the artifacts) in order to reduce the confusion:
 ![dark_new](https://github.com/user-attachments/assets/08594658-279e-4d63-bb7d-0678aab16ad5)

**Comment by westnordost** [comment]
The color of the street doesn't change. It is the same in light and dark mode.

**Comment by matkoniecz** [comment]
I guess that changing sidewalk from transparent/changing colour in dark mode to having the same colour also in dark mode maybe may be potentially OK for PR?

**Comment by mnalis** [comment]
> The color of the street doesn't change. It is the same in light and dark mode.

But the color of the sidewalk does change from lighter than road to darker then road. That creates the same [optical illusion](https://en.wikipedia.org/wiki/Checker_shadow_illusion) as if the color was different -- human brain can't tell the difference.

> I guess that changing sidewalk from transparent/changing colour in dark mode to having the same colour also in dark mode maybe may be potentially OK for PR?

That would work too to avoid confusion (although my [mockup](https://github.com/streetcomplete/StreetComplete/issues/6065#issuecomment-2566524478) suggestion keeps the dark mode darker, which might be preferred)
