### ISSUE TITLE
POEditor link doesn't have the complete list of translators, contrary to what the credits screen says

### ISSUE THREAD

**Issue by antonv6** [streetcomplete/StreetComplete#629]
Credits screen links to `https://poeditor.com/projects/view?id=97843`, but there doesn't seem to be any way to list translators. It's basically a "join this public project" page (except hardly anything there is public if you're not logged in). Maybe as the project manager you can see the list of translators on POEditor, but nobody else can.

**Comment by westnordost** [comment]
Hm, that's unfortunate. I think it should. I will ask the POEditor guys if this can be changed (for public projects).

**Comment by westnordost** [comment]
I see the feature request already exists here. I voted for it and added a comment. You (and other) could also vote for it.

https://poeditor.uservoice.com/forums/171919-general/suggestions/31242085-public-url-to-view-project-contributors

As such a page does not exist yet, there is not much more I can do for now because maintaining a complete list of translators manually is really too much effort with that many one-time few-string contributors. So far, I only manually update the contributors list in the app every so often with the main 3-4 contributors for a language.

**Comment by matkoniecz** [comment]
As it appears that POEditor fixing this is unlikely, maybe either adding script to fetch that data and store in SC would be OK?

Or change description to mention that logging in is sadly mandatory to see that info? Maybe link that uservoice request?

**Comment by westnordost** [comment]
I think there is no API that gets all the contributors by language (sorted by # of contributions):
https://poeditor.com/docs/api#contributors

**Comment by matkoniecz** [comment]
But for minor users order does matter so strongly? So it would be possible to fetch all, skip major ones (sadly maintained manually) and save all remaining ones for display in an alphabetic list?

**Comment by westnordost** [comment]
A good ~50% of users that joined the project have actually 0 contributions

**Comment by matkoniecz** [comment]
OK, so script version is likely not feasible at all :(

What would be better?

Keeping it as an eternally open issue?

Describe that you need to log in?

Remove link completely?

**Comment by matkoniecz** [comment]
Personally I would describe that you need to log in. I thought about linking user voice but it seems that they just ignore it anyway so not worth encouraging people (especially as voting requires agreeing to receive marketing spam).

**Comment by westnordost** [comment]
No strong opinion on this.

**Comment by matkoniecz** [comment]
In theory parsing pages such as https://poeditor.com/projects/stats?id=97843&type=contributor&id_user=257233&start=2017-09-01&stop=2022-06-26 and https://poeditor.com/projects/stats?id=97843&type=contributors&start=2021-05-01&stop=2021-05-31 is a viable response.

But it would take some time to implement and requires being logged in to see that (not complicated to work around that, but is more irritating to implement and requires storing password in plaintext somewhere).

**Comment by peternewman** [comment]
> But it would take some time to implement and requires being logged in to see them, likely with an admin account (not complicated to work around that, but is more irritating to implement and

Just to confirm as a mere mortal I only seem to be able to see my contributions in the languages I've translated, and not the stats of other people.

> requires storing password in plaintext somewhere).

GitHub Action secrets could store the password securely for you, but I'd agree a lot of effort.

**Comment by matkoniecz** [comment]
With #2980 being done it should be also possible to build own replacement - or remove this link entirely if current attribution is good enough.

**Comment by matkoniecz** [comment]
This link is now gone and replaced by a proper homegrown listing.

**Comment by matkoniecz** [comment]
@westnordost You are not listed as translator for German, is it correct or intentional?

**Comment by westnordost** [comment]
Hm I don't know... I should be there, but maybe the admin/this-user is not listed as a contributor in POEditor
