### ISSUE TITLE
Is this restaurant kosher/halal?

### ISSUE THREAD

**Issue by yotamN** [streetcomplete/StreetComplete#639]
### General
For nodes with amenity=restaurant there should be a quest asking if the restaurant is kosher and/or halal. This question should only apply in countries with enough Jews/Muslims. For the kosher question only Israel, Gibraltar, United States and Canada have more than 1% Jews, for the halal question you can [look at Wikipedia](https://en.wikipedia.org/wiki/Islam_by_country).

Maybe it can also be added to supermarkets and convenience stores but I'm not sure how common is it.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

The answer for diet is mostly yes or no so I'm not sure if it would be spam.

**Comment by westnordost** [comment]
Hmm, users would need to be instructed how to detect whether a restaurant offers kosher and/or halal food. How would that be done?

Also, how would it be tagged?

**Comment by yotamN** [comment]
Most restaurant will write somewhere, maybe on their sign that they are kosher, I will see if I can take an example picture soon. I don't know if it's the same for halal food, maybe someone Muslim would be able to answer that.

There is diet:kosher and diet:halal tags with yes, no and only options

**Comment by rugk** [comment]
The quest would be similar to https://github.com/westnordost/StreetComplete/issues/479…, but may indeed be useful as it's own quest.

**Comment by matkoniecz** [comment]
@rugk dots ended as part of link, as results it leads to 404 page

It was supposed to go to #479

**Comment by gappleto97** [comment]
I'm not sure that it would need any more instruction than determining if something is vegan or not.

**Comment by gappleto97** [comment]
@yotamN, while I'm not Muslim, I've seen a few restaurants that advertise themselves as halal. There was one right next to my workplace when I was in California.

**Comment by rugk** [comment]
Remember the quest must be easily solvable by users who are not "experts" in what the quest asks. As such by non-Muslim users, here, of course.
And I think that it really needs explanation (that may vary by country maybe though), or the quest could be disabled by default.

Also it is cumbersome to tag all the "no" answers here in many countries, as such restaurants are likely in the minority. As such, this would not fulfill the "no spam" requirement of sc quests.

As such in many European countries the quest may actually be disabled/blacklisted by default. But I really can imagine that in some countries such a quest would actually be useful. It just needs around ~50% (it maybe even less) of the quest answers to be answerable with yes.
Actually it just needs to be like the vegetarian quest. This can be made very similar.

**Comment by gappleto97** [comment]
If this violates the anti spam rule, then how does the vegan one not? Most restaurants dont have vegan main dishes, in my experience.

**Comment by rugk** [comment]
Yes, that's also a reason why the quest is disabled by default, AFAIK. The same could be done with this quest here. And as said, it could also be adjusted by region.

**Comment by yotamN** [comment]
@rugk It's pretty easy to identify a kosher restaurant, here is an example for a kosher McDonalds:
![img_20171019_155203b](https://user-images.githubusercontent.com/5249239/39660678-df4eefc4-504c-11e8-9669-1a1c2e37aa7c.jpg)

**Comment by ENT8R** [comment]
As already said earlier: this really depends on the country... I've never seen something like this in a country like Germany or the US...

**Comment by matkoniecz** [comment]
@ENT8R  It is also extremely rare in Poland, Slovakia, Ukraine and many other countries.

@yotamN Is sign like that (kosher/not kosher) appearing on every single fast food/restaurant?

Also, is it in the Israel or in other region?

**Comment by matkoniecz** [comment]
Can someone give any example of any region where

- nearly all places selling food (or some subgroup of it like amenity=restaurant) are marked whatever place is kosher or not kosher?
- places are sometimes kosher and sometimes not kosher?

The same for halal.

**Comment by matkoniecz** [comment]
So every single restaurant that has no kosher sign is not kosher?

How many restaurants are not kosher? 1%? 10%? 50%?

**Comment by matkoniecz** [comment]
Given that we have not even single example of region where

* nearly all places selling food (or some subgroup of it like amenity=restaurant) are marked whatever place is kosher or not kosher (everything has either sign "kosher/not kosher" or unsigned places are known to belong to one category)?
* places are sometimes kosher and sometimes not kosher (so answer is not always the same)?

(the same for halal)

it seems that this quest does not fit StreetComplete.

**Comment by rugk** [comment]
> nearly all places selling food […] are marked whatever place is kosher or not kosher 

As for vegetarian/vegan or not it's also not done and we have a vegan/vegetarian quest. As said, of course it needs to be disabled by default, because you may need to go inside.

> places are sometimes kosher and sometimes not kosher

We did not yet have a definite answer (@yotamN still has not replied to your last question), but it has been suggested this could certainly be the case in countries like Israel, etc.

**Comment by ENT8R** [comment]
But it is only the country Israel in which a quest like this would make sense or are there some other countries which were not mentioned before?

**Comment by reinhart1010** [comment]
@yotamN @ENT8R some countries (such as Indonesia) have their Halal certification standards for restaurants. Hence, it's actually easy to tag Halal restaurants there.

Some of them also provide QR Codes to allow customers to look at their Halal certificate validity online.

**Comment by rugk** [comment]
> Some of them also provide QR Codes to allow customers to look at the validity of their Halal certificate online.

Wow, cool. Can you show an example for that?
I mean, maybe it is a little too much implementation work, but of course StreetComplete could integrate a QR code scanner, scan that, and then automatically tag the correct answer… If it is just a PDF though, that may be harder.

**Comment by reinhart1010** [comment]
Here it is. (Taken from [an article in a local news website](https://m.republika.co.id/berita/inpicture/nasional-inpicture/15/01/14/ni66jh-mengecek-restoran-halal-lewatem-qr-codeem-lppom-mui))

![qr-code-halal-mui](https://user-images.githubusercontent.com/17312341/50041605-39664000-008a-11e9-9dd9-07ecdf072619.jpg)

**Comment by matkoniecz** [comment]
Info from Israel: 

- binary yes/no kosher is good enough for non orthodox
- it would be helpful information to some to know who is the certifying agency (probably for orthodox)
- the vast majority of the kosher restaurants have the “kosher” “כשר” clearly displayed and if not, the kosher certificates will be very prominently displayed inside. But there are exceptions.

**Comment by matkoniecz** [comment]
Summary would be that it in general requires going inside. Therefore I plan to implement it as disabled by default. With quest disabled by default I am unsure is it necessary to make it limited to Israel.

**Comment by peternewman** [comment]
I don't think it should be limited to just Israel, London has a number of large Jewish communities:
https://en.wikipedia.org/wiki/List_of_Jewish_communities_in_the_United_Kingdom

For example:
https://en.wikipedia.org/wiki/Golders_Green#Jewish_community
https://en.wikipedia.org/wiki/Stamford_Hill#Haredi_Jewish_community

Likewise for the Halal ones it can be quite common in some areas to have Halal restaurants and supermarkets.

**Comment by westnordost** [comment]
kosher quest implemented by @matkoniecz

**Comment by yrtimiD** [comment]
@matkoniecz , I'm not familiar with street complete framework, can it be enabled by default in Israel but not limited to Israel only?

**Comment by riQQ** [comment]
This was implemented by #2244.

**Comment by matkoniecz** [comment]
> can it be enabled by default in Israel but not limited to Israel only?

1) it is not possible right now and would require extra implementation

2) SC has quests that involve going inside into shop/restaurant/etc disabled by default

**Comment by rugk** [comment]
> Note: At the time of this writing the site contained in the QR Code shows a 500 Internal Server Error message,

It still has. Seems it's not really a reliable data source. :sweat_smile: 

Otherwise it would have been a suggestion to integrate that, but well…
