### ISSUE TITLE
Rearranging of quests is broken.

### ISSUE THREAD

**Issue by Natenom** [streetcomplete/StreetComplete#893]
Version: 4.0

How to reproduce:
  * Go to settings -> Advanced -> Quest selection
  * Click RESET.
  * Move "Does this bench have a backrest" (last position on the list) to the second position.
  * Move "Is this bicycle parking covered pro tected from rain)?" to the third position.
  * Now scroll down in the list until you can't see the bench quest anymore and then up again. The bench quest was movedto  a random position. Position 2 is now used by "building number quest" and position 3 by "bicyling parking covered quest".

I can always reproduce this, also with other quests.

**Comment by Natenom** [comment]
It works if you avoid moving quests to the first few positions.

**Comment by westnordost** [comment]
Hmm, I can't. With second position, you mean after the note quest? After moving the bicycle parking to position 3, do you exit the quest selection screen and reenter it?

**Comment by Natenom** [comment]
Pos1 is the note quest. No, just scroll down and up again.

**Comment by Natenom** [comment]
Okay, this is wired; I did that ~10 times before reporting this bug. But now it doesn't happen anymore...

**Comment by RubenKelevra** [comment]
I can confirm this bug, as soon as you scroll down and up again the bench quest is gone and on the second place is "Which is the name of the street?" (or similar - I use the German locale).

But actually, the bug start even earlier:

-Reset
-Scroll down, and drag the Bench task to the second place
-everything looks fine.
-scroll down & up again and the street name task is gone.

**Comment by westnordost** [comment]
I'll try with your reproduction.

**Comment by westnordost** [comment]
Hm, can't reproduce.

**Comment by RubenKelevra** [comment]
@westnordost Maybe it's just an issue on a specific device type or on a specific version of Android?

So on Android 8.0 on a OnePlus 5T it's definitely 100% reproducible.

**Comment by westnordost** [comment]
I will give you a bit an insight about how it works:

1. When you open that dialog, the list of quests is **once** sorted by the custom order you specified and then displayed. Rotating the smartphone counts as reopening the dialog.
2. When you click RESET, the custom order you specified is cleared, then the list of quests is **once** sorted by the custom order again (which is empty, so nothing is sorted in effect)
3. When you move items around in the list, the custom order is updated and the display is updated **independently from another**. In other words, if the display is wrong, it does not mean that the order in the internal model is wrong.

Would you please after you have experienced the bug in the display rotate your device? How is the order then?

**Comment by matkoniecz** [comment]
I just tested

> -Reset
> -Scroll down, and drag the bench task to the second place
> -everything looks fine.
> -scroll down & up again and the street name task is on a random position.

And managed to reproduce this issue. Note that leaving Quest selection menu and entering it resulted in name quest on correct position (third, after bench quest).

I may make a video recording if that would be useful.

**Comment by westnordost** [comment]
I don't think it would be useful. I believe you that what you wrote is exactly what happens.

If you can reliably reproduce it, what would help if you debugged it ;-) (no, really, actually. But I know it is a lot to ask)

**Comment by RubenKelevra** [comment]
Well, what do you think of adding a the internally number which is used for sorting for a beta build to the playstore or a custom apk you provide, than we would be able to debug this issue better (I guess). Testing a bit around with rotation and reopening the app and will report later.

**Comment by RubenKelevra** [comment]
Let me do a guess here... the "moving the last to the first place" operation is a pretty long one, since all elements need to be touched and moved +1, right? So this looks like a race condition that this background update of the data isn't completed but interrupted by the scrolling and the occuring reread of stored sort-ids and redraw operation.

The bug occurs but do not break the data stored but the display of the items for a short time, so exiting and reopening does "fix" the display again.

**Comment by westnordost** [comment]
No. Just making assumptions about the origin of the bug without having read the code is not helpful.

**Comment by ENT8R** [comment]
I just tried it on my phone (LineageOS 14.1/Android 7.1) but I can't reproduce it at all... 😕

**Comment by RubenKelevra** [comment]
Alright then, but the occuring of this bug depends on scrolling immediately after changing the order of items, reloading of the list cure this error again. So this looks for me still like a view on an ongoing operation at the wrong time.

**Comment by westnordost** [comment]
So, can anyone reproduce this?

**Comment by matkoniecz** [comment]
Yes - https://github.com/westnordost/StreetComplete/issues/893#issuecomment-368352955 (but I prefer to handle other issues before debugging this, especially [12 that I reported](https://github.com/westnordost/StreetComplete/issues/created_by/matkoniecz))

**Comment by jtracey** [comment]
I'm also seeing this on my device (StreetComplete 21.0, LineageOS 16/Android 9). Not just scrolling, leaving and returning also causes things to reorder themselves. I don't have a consistent way to reproduce it, but it does happen consistently, given enough time.

**Comment by rouelibre1** [comment]
Ran into the issue on my device (StreetComplete v24.2 / Android 8.0.0 / Device SM-A520F)
Moving an element all the way up seemed to trigger it, leaving and returning also caused things to re-order themselves. Moving elements up a few rows at a time seemed to help (I finally got the arrangement I was after).
