### ISSUE TITLE
add "No fee, but time restricted" answer-option to fee quest

### ISSUE THREAD

**Issue by rza31** [streetcomplete/StreetComplete#981]
### General
Affected tag(s) to be modified/added: [Key:maxstay](https://wiki.openstreetmap.org/wiki/Key:maxstay)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
By the Quest for parking=fee you can select between no, yes, yes/no from to

There is also a possibility of disk parking. Parking is free at the specified time.

**Comment by westnordost** [comment]
Would be independent of the fee quest. I.e. there are parking lots where it does not cost a fee but there is a maxstay, is there not?

Though, what to tag if there is no maxstay? Think of countries which are not regulated that much in that way or simply in small towns / on the countryside.
Also, for these cases, it might be somewhat spammy to always answer "no, no maxstay here". What is the gain to record this information?

**Comment by ENT8R** [comment]
See also #102 which was rejected

**Comment by westnordost** [comment]
Ah okay, so it is a duplicate then.

**Comment by MrSunday334** [comment]
If its part of the parking fee quest, it would only be asked if no value for the parking fee is existing. So no tag spamming is possible? 
Is there a fee: Yes, No, No (but only limited time) etc.

**Comment by ENT8R** [comment]
But then a completely different tag (maxstay=*) would be set than for the other answers (fee=*) which would mean that every parking which already has a maxstay value set would be excluded from the parking **fee** quest

**Comment by rza31** [comment]
For example <code> maxstay=1 @ (08:00-18:00)</code>, you can stay 1 hour between 8 and 18. 
A fee isn't necessary .
It must be set the tag **maxstay** instead **fee**. 
maxstay=no shouldn't possible trough the app. See also [taginfo=maxspeed](https://taginfo.openstreetmap.org/keys/maxstay#values).

**Comment by ENT8R** [comment]
> It must be set the tag maxstay instead fee.

Which was already proposed in #102 and rejected...

**Comment by rza31** [comment]
The tag maxstay is used over all 5 continents. With mapping on the ground the tag can be easy verified by the traffic sign. 
At parking areas without traffic sign no maxstay can be tagged,  don't allow maxstay=no.
Parking with parking disc is only an other type of fee=no. The owner allows free parking for a specific time.

**Comment by rugk** [comment]
So you assume that if it costs a fee no maxstay is set? (Sounds reasonable, IMHO)

**Comment by westnordost** [comment]
Can someone give a summary what the concrete suggestion would be then and why it would make sense?

**Comment by rugk** [comment]
First, I'd would adjust the title. I don't know what "Disk parking" is. Replace it with "maxstay".

Suggestion: Add the answer "No, but time-limited" to the parking fee quest.
Why it makes sense: See the points listed at https://github.com/westnordost/StreetComplete/issues/981#issuecomment-374347125

**Comment by westnordost** [comment]
Nevermind, I understand now:
Add an answer-option called "No fee, but time restricted" and show a time dialog like for the (to-be-implemented) postbox quest.

**Comment by westnordost** [comment]
Eh, what am I saying. This has nothing to do with a time dialog. It should be a duration dialog.

**Comment by RubenKelevra** [comment]
@rugk well, we call it parking disk here... a physical disk with the arrival time you place behind your windscreen.

But also parking tickets for half an hour or one hour for free are not that common. You can extend those by an hour, if you want to stay longer.

But let us just focus on the easiest part, right now: park disk indicated arrival time with a fixed allowed stay time like 30 minutes, 60 minutes, 120 minutes

**Comment by RubenKelevra** [comment]
@westnordost since you already talked about that, is an opening_hours task (especially for customer parking spaces) also planned? :)

**Comment by rugk** [comment]
Ahh… that's what is meant by "disk marking". Just wrong word order… :smile:  

> is an opening_hours task (especially for customer parking spaces) also planned? :)

What? Opening hours quest exists today. As for other planned things maybe search the issue tracker,… That's why we have it.

**Comment by RubenKelevra** [comment]
@rugk opening_hours and parking gave me zero open tickets, that's why I asked.

**Comment by Codain** [comment]
Hi, I'm living in a city where parking is free but limited in duration and we have to put a disc telling the arrival time.

I would recommand to:
1. Add a new option "No, but time limited" in the parking fee quest with no additional duration setting at the moment;
2. Create a new quest for all free public parkings in osm asking if a max stay rule applies and, if yes, wether a disc is required. This would help catching already mapped public free parkings.

**Comment by peternewman** [comment]
See also pretty much every supermarket and shopping centre in the UK; most are free for n hours.
